### ISSUE TITLE
shift date by x month (column)

### ISSUE THREAD

**Issue by markxwang** [pola-rs/polars#10000]
### Problem description

I have several use cases (economic/financial data) that involve manipulating monthly data, such as
- Calculate month difference (e.g., 2022-10 and 2023-05)
- Shift a date column by x month (which is another column)  (e.g. 2020-10 + 10)

Conventionally I use `pandas.Period` type which can achieve month difference and shift easily.

Polars does not have a period type, so I stick to the datetime. 
Month difference is still doable (I can do year diff * 12 + month diff). 

Month shift is a lot more difficult. I have two options
- `dt.offset_by`, which can shift a date column by a single number (not a column of integers)
- `pl.duration`, which can shift a date column by another column, but it does not have month option.

I wonder if it is possible to introduce `month` (or `month_saturating`) into `pl.duration`? I appreciate that the month option was not there in the first place probably for some really good reason.

**Comment by MarcoGorelli** [comment]
hey @markxwang - there's a PR open right now to address this 😄 https://github.com/pola-rs/polars/pull/9967

**Comment by cmdlineluser** [comment]
So I just noticed there is a `Duration::from_months()`

https://github.com/pola-rs/polars/blob/c07c8f28119daba6b437552495469393d7dd2ce3/polars/polars-time/src/windows/duration.rs#L271

Is there perhaps a reason why this shouldn't be exposed via `pl.duration(months=...)`?
