### ISSUE TITLE
with_columns ignores pl.when() condition

### ISSUE THREAD

**Issue by yusufuyanik1** [pola-rs/polars#10001]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

data = {
    "Name": ["David", "David", "Emma", "David", "Emma"],
    "Occupation": ["Engineer", "Engineer", "Chef", "Engineer", "Chef"],
}

df = pl.DataFrame(data)

def custom_func(s):
    return s[5]

df.with_columns(
    pl.when(pl.col("Name") == "David")
    .then(pl.col("Occupation").apply(custom_func).alias("5th letter of occupation"))
    .otherwise(pl.lit("This is not David"))
)

### Issue description

Applies the function inside then() block even though when() condition is not met.

In the Reproducible example I am expecting to create a new column where:
when name == David
return 5th letter of occupation

otherwise:
return "This is not David"

Looks it is trying to apply the custom function even when the name is NOT David. And since Emma's occupation has less than 5 letters, it fails. (index out of range error)

### Expected behavior

I would expect polars not to run the then block when the when condition is not met.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.0 (main, Mar  1 2023, 12:33:14) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.15
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9```

</details>

**Comment by mcrumiller** [comment]
A couple of notes:

1. If you fence in your code with three backticks it formats it as code.
2. Your `.alias`, being inside of a when/then, ends up being discarded.
3. Polars computes when/then chains in parallel, and *then* filters. This is why you're seeing this problem. Here is the issue, but a little bit clearer:

    ```python
    import polars as pl
    from polars import col, when

    df = pl.DataFrame({
        'a': [1, 2, 3],
        'b': ['a', 'b', 'c'],
    })
    df.select(
        when(col('a') < 0).then(col('b').cast(pl.UInt8)) # invalid cast but never occurs
        .otherwise(col('a'))
    )
    ```
    ```
    exceptions.ComputeError: strict conversion from `str` to `u8` failed for value(s) ["b", "c", "a"];
    if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`
    ```
The first branch  *never* occurs, but we still get an error.

**Comment by ritchie46** [comment]
Yes, this is expected behavior.

**Comment by yusufuyanik1** [comment]
Thanks for looking into it and the notes.
An inefficient way to do the task would be this, leaving it in case someone else has a similar problem:
```
import polars as pl
from polars import col

df = pl.DataFrame({
    'a': [1, 2, 3],
    'b': ['1', 'b', 'c'],
})

def convert(n):
    try:
        n= str(int(n) *2)
    except:
        pass
    return n

df.select(
    col('b').apply(convert)
)
```

Please let me know if there is a better way of doing a conditional column operation in an unparallel way.

**Comment by cmdlineluser** [comment]
You can use `pl.when().then().apply()` to run it only on the matching items.

It requires repeating the condition inside `.then()` e.g.
```python
df.with_columns(
   pl.when(pl.col("Name") == "David")
     .then(pl.when(pl.col("Name") == "David").then(pl.col("Occupation")).apply(custom_func))
     .otherwise(pl.lit("This is not David"))
     .alias("5th letter if David")
)

# shape: (5, 3)
# ┌───────┬────────────┬─────────────────────┐
# │ Name  ┆ Occupation ┆ 5th letter if David │
# │ ---   ┆ ---        ┆ ---                 │
# │ str   ┆ str        ┆ str                 │
# ╞═══════╪════════════╪═════════════════════╡
# │ David ┆ Engineer   ┆ e                   │
# │ David ┆ Engineer   ┆ e                   │
# │ Emma  ┆ Chef       ┆ This is not David   │
# │ David ┆ Engineer   ┆ e                   │
# │ Emma  ┆ Chef       ┆ This is not David   │
# └───────┴────────────┴─────────────────────┘
```
Or perhaps `.fill_null()` after could be used instead:

```python
df.with_columns(
   pl.when(pl.col("Name") == "David")
     .then(pl.col("Occupation"))
     .apply(custom_func)
     .fill_null("This it not David")
     .alias("5th letter if David")
)
```
Although depending on your exact task - there may be a way to do it using Polars expressions - avoiding the need for `.apply()`

> Using apply is strongly discouraged as you will be effectively running python “for” loops. This will be very slow. Wherever possible you should strongly prefer the native expression API to achieve the best performance.
