### ISSUE TITLE
Add `pl.Config.set(dict)` or `pl.Config.set(key=value, ...)`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10002]
### Problem description

Currently, if you want to set multiple options at once, you have to call `pl.Config...` multiple times:

```python
pl.Config.set_tbl_cols(15)
pl.Config.set_tbl_rows(20)
...
```

It would be useful to have a `pl.Config.set(dict)` or `pl.Config.set(key=val, ...)` that sets multiple items at once. I know that we have `pl.Config.save` and `load` but that involves reading from a file, which is slightly different.

**Comment by cmdlineluser** [comment]
I have been using this syntax:
```python
pl.Config(tbl_cols=15, tbl_rows=20)
```
I discovered this in the context manager section:

https://pola-rs.github.io/polars/py-polars/html/reference/config.html#use-as-a-context-manager

**Comment by mcrumiller** [comment]
@cmdlineluser I wasn'ta ware you could pass variables into `pl.Config` like that. Thanks!
