### ISSUE TITLE
Split `date_range` into `datetime_range` and `date_range`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10006]
### Problem description

Currently, `date_range` is overloaded to be able to produce ranges of both `Date` and `Datetime` types.

This works fine, but wouldn't it be much clearer if we just had different range types for each?
* `date_range`
* `time_range`
* `datetime_range` _(new)_

Thoughts?

**Comment by ritchie46** [comment]
Yes, they could probably still use the same core implementation, but returning different types is a bit iffy indeed. I am in favor of splitting it up.

**Comment by MarcoGorelli** [comment]
yeah, all for reducing overloads

the logic for detecting the schema in the lazy case is overly complicated right now, would be so much simpler if `date_range` always returned `Date` and `datetime_range` always returned `Datetime`

https://github.com/pola-rs/polars/blob/980dac2452ed9af19c86b53c127d85b85aeb5549/polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs#L341-L398

**Comment by stinodego** [comment]
Great. If #10005 gets merged, I'll add `datetime_range` and deprecate the datetime functionality from `date_range`.
