### ISSUE TITLE
selecting engine="adbc" for postgresql results in errors

### ISSUE THREAD

**Issue by quantsupport** [pola-rs/polars#10015]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
connection_uri = "postgres://postgres:password@localhost:5432/db"
query = "SELECT * FROM candle1mf"
pl.read_database(query=query, connection_uri=connection_uri, engine="adbc")
```
results in the following error:
ImportError: ADBC postgres driver not detected; if ADBC supports this database, please run `pip install adbc-driver-postgres pyarrow`

However, running "pip install adbc-driver-postgres" results in the following error: "ERROR: No matching distribution found for adbc-driver-postgres"

This seems to be because of a confusion around whether to call it "postgres" or "postgresql". The pip package is actually called adbc-driver-postgres**QL**

Happily a quick fix to this is to change the name of the module in **database.py** on line 173 from this:
module_name = f"adbc_driver_{module_suffix}.dbapi"

to this 
module_name = f"adbc_driver_{module_suffix}ql.dbapi"

### Issue description

Adding 'ql' onto the end of the module name seems to fix the issue

### Expected behavior

I expect the code to just run as I listed it above

### Installed versions

<details>

```
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              2.0.2
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          2.0.18
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Yeah, this is correct as per https://arrow.apache.org/adbc/0.1.0/driver/cpp/postgresql.html. Their instructions:

```python
pip install adbc_driver_postgresql
```

**Comment by alexander-beedie** [comment]
FYI: the standard PostgreSQL URI prefix is "postgresql", though the abbreviation is listed in [the docs](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6) as an acceptable alias, so we should account for that - I'll take a look.

**Comment by mcrumiller** [comment]
Ok, I'm entirely sure this is an issue, your connection URI doesn't follow the specification listed at https://arrow.apache.org/adbc/0.1.0/driver/cpp/postgresql.html, it should be `postgresql://` which resolves this issue.

**Comment by mcrumiller** [comment]
@alexander-beedie beat me to the punch :)

**Comment by quantsupport** [comment]
> FYI: The confusion doesn't come from the module name - it comes from the URI ;)

Lol! I should have guessed. Thanks for looking - the responsiveness is truly awesome. 

Cheers
