### ISSUE TITLE
Implement Python dataframe interchange protocol natively

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#10035]
### Problem description

The Python dataframe interchange protocol is becoming more and more prevalent. 

For us to be able to interchange with third party libraries, I don't want to have an obligatory dependency on pyarrow.

I think we can revive the old PR made by @stinodego and fill in the missing parts.

As an intermediate solution we can use what worked already from that PR and only require pyarrow for the methods we don't support yet.

**Comment by MarcoGorelli** [comment]
This came up recently talking with scikit-learn devs - `df.__dataframe__(allow_copy=False).column_names()` should be extremely cheap and always work, but with polars it may fail because it first has to call `.to_arrow()`, which may not work with `allow_copy=False`

**Comment by ritchie46** [comment]
Yes, because of discussion with them I opened this issue. ^^

**Comment by stinodego** [comment]
I'll pick this up in a week. I'll implement a quick fix for the issue mentioned above and then revive the native implementation.

**Comment by stinodego** [comment]
I'll re-open this as there is a part two: `from_dataframe`

I'll be working on that next.

**Comment by mkleinbort-ic** [comment]
Hello. Is this in the works? Just checking

**Comment by stinodego** [comment]
You can check this PR for the progress:
https://github.com/pola-rs/polars/pull/10701
