### ISSUE TITLE
Mention when functions are feature-conditional

### ISSUE THREAD

**Issue by multimeric** [pola-rs/polars#1003]
#### Describe your feature request

Certain functions/methods, e.g. [`DataFrame.to_ndarray()`](https://docs.rs/polars/0.14.7/polars/prelude/struct.DataFrame.html#method.to_ndarray) are not compiled by default, and require something like `polars = { version = "*", features = ["ndarray"] }` in your `Cargo.toml`. Now I'm a very new Rust user, but I found it confusing that this wasn't mentioned in docs. I'm a bit surprised the Rust documentation generator doesn't do this automatically, because it's annotated in the code itself. But considering that it doesn't, should the actual method documentation explain this?

**Comment by ritchie46** [comment]
The documentation on master has a tag next to the [to_ndarray](https://pola-rs.github.io/polars/polars/frame/struct.DataFrame.html#method.to_ndarray) function saying **This is supported on crate feature ndarray only.**. 

The opt-in features are also described in the main page of the documentation [here](https://pola-rs.github.io/polars/polars/index.html#compile-times-and-opt-in-features). 

Now, I don't know why the mentioned tag is not visible on `doc.rs`, maybe I must set a feature for that.

**Comment by multimeric** [comment]
Hmm yes this seems to be a new feature. I don't quite understand, but [this page](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html) implies it's still considered unstable, so maybe that's why `doc.rs` doesn't use it? In any case, you've provided a few alternative ways of viewing feature tags, and the main docs might be automatically updated in the future so thank you.
