### ISSUE TITLE
pl.read_ndjson silently drops the rest of the file when it encounters invalid json

### ISSUE THREAD

**Issue by TomBurch** [pola-rs/polars#10041]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from pathlib import Path

import polars as pl

path: Path = Path('./test_data')
with open(path, 'wt') as file:
    for i in range(0, 100):
        file.write('{"a": "1", "b": 2.0}\n')
    file.write('{"a": "3", "b": NaN}\n')
    for i in range(0, 100):
        file.write('{"a": "5", "b": 6.0}\n')

df = pl.read_ndjson(path)
print(df)

shape: (100, 2)  # <--------- This should be 200
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ …   ┆ …   │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
└─────┴─────┘
```

### Issue description

When an ndjson file has a line of invalid json (e.g. `NaN` or `.1`) `read_ndjson` will read up to the invalid line and silently discard the rest of the file.

### Expected behavior

My expectation would be something like:
- If `ignore_errors=False`, raise an error
- If `ignore_errors=True`, ignore the line and keep processing

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.7
sqlalchemy:          1.4.48
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by rikkaka** [comment]
A `JsonReader<'a, R>` is used to read a ndjson file. At [here](https://github.com/pola-rs/polars/blob/bb413034890fced83e203110f8da7cf115e55479/polars/polars-io/src/json/mod.rs#L175-L191C6)，
```rust
    fn new(reader: R) -> Self {
        JsonReader {
            reader,
            rechunk: true,
            ignore_errors: false,
            infer_schema_len: Some(100),
            batch_size: 8192,
            projection: None,
            schema: None,
            schema_overwrite: None,
            json_format: JsonFormat::Json,
        }
    }
```
the `infer_schema_len` is set to Some(100). So only the head 100 rows are used to infer the schema. If the invalid value is located before the 100th row, it will raise an Error.
When the invalid value is neglected and it proceeds to the process of parsing the lines, we go into [this function](https://github.com/pola-rs/polars/blob/cdacbfea44609344e8222cde58040870a1ad4713/polars/polars-io/src/ndjson/core.rs#L303C7-L303C7). 
```rust
fn parse_lines(bytes: &[u8], buffers: &mut PlIndexMap<BufferKey, Buffer>) -> PolarsResult<()> {
    let mut buf = vec![];


    // The `RawValue` is a pointer to the original JSON string and does not perform any deserialization.
    // It is used to properly iterate over the lines without re-implementing the splitlines logic when this does the same thing.
    let mut iter =
        serde_json::Deserializer::from_slice(bytes).into_iter::<Box<serde_json::value::RawValue>>();
    while let Some(Ok(value)) = iter.next() {
        let bytes = value.get().as_bytes();
        parse_impl(bytes, buffers, &mut buf)?;
    }
    Ok(())
}
```
The `Some(Ok(value))` seems incorrectly used here to match iter.next(). As a result, the "while let" loop will shut down when iter.next() returns an Err as it encounters an invalid value. So it will read up to the invalid line and silently discard the rest of the file.

To fix the bug, we need to handle the cases where the value inside Some is Ok and Err separately.

**Comment by rikkaka** [comment]
But as the iter will end the iteration upon encountering an invalid value, it might be more difficult to ignore the line and keep processing.
