### ISSUE TITLE
.implode() returns list(list()) instead of list()

### ISSUE THREAD

**Issue by pastastical** [pola-rs/polars#10042]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data = {"a":[1,1,1], "b":[2,3,4] }
pl.DataFrame(data).groupby("a").agg(
    pl.col("b").implode()
)
```
<html>
<body>
<small style="color: rgb(255, 255, 255); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(17, 17, 17); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (1, 2)</small>

a | b
-- | --
i64 | list[list[i64]]
1 | [[2, 3, 4]]

</body>
</html>

### Issue description

When aggregating a group column using .implode(), the result is a column of type list(list()) instead of list().

### Expected behavior

```python
data = {"a":[1,1,1], "b":[2,3,4] }
pl.DataFrame(data).groupby("a").agg(
    pl.col("b").implode()
)
```
<html>
<body>
<small style="color: rgb(255, 255, 255); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(17, 17, 17); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (1, 2)</small>

a | b
-- | --
i64 | list[i64]
1 | [2, 3, 4]

</body>
</html>

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by cmdlineluser** [comment]
You can just remove the `.implode()` - #6487

**Comment by ritchie46** [comment]
This is expected as @cmdlineluser refers to in https://github.com/pola-rs/polars/pull/6487
