### ISSUE TITLE
pl.scan_csv should report name of non-existent file

### ISSUE THREAD

**Issue by exyi** [pola-rs/polars#10043]
### Problem description

`pl.read_csv` reports the filename if the file doesn't exist, but `pl.scan_csv` doesn't do that

```ipython
In [1]: pl.read_csv("does.not.exist")
...
FileNotFoundError: No such file or directory: does.not.exist

In [2]: pl.scan_csv("does.not.exist")
OSError: No such file or directory (os error 2)
```

This makes it harder to debug issues in my code

EDIT: sorry for empty issue, I pressed enter key accidentally before writing the description

**Comment by cmdlineluser** [comment]
It looks like this may be the place to catch the current error:

https://github.com/pola-rs/polars/blob/8b0588fcdec2940126cfbb85ec3af13364490f57/polars/polars-lazy/src/frame/file_list_reader.rs#L68-L70

Looking at what the `if` block does, it seems like perhaps something like this would work?
```python
} else {
   self.clone()
       .finish_no_glob()
       .map_err(|_e| {
           polars_err!(
               ComputeError: "No such file or directory: {}", self.path().display() 
           )
       })
}
```
Although I'm not sure if it's possible for other errors to hit that codepath.
