### ISSUE TITLE
Using `Series.is_in(Series)` strips the name of the input Series

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10072]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

a = pl.Series("a", [1, 2])
b = pl.Series("b", [1, 3]).is_in(a)
print(a)
```
```
shape: (2,)
Series: '' [i64]  <- note that the name is stripped!
[
        1
        2
]
```

### Issue description

The input should not be modified.

I currently use a `clone()` as a workaround.

This started happening in Polars 0.18.7. On Polars 0.18.6 there was no issue.

### Expected behavior

Name should be preserved.

### Installed versions

master

**Comment by mcrumiller** [comment]
Possibly related to #8955?

**Comment by mcrumiller** [comment]
Possibly related to #8955?
