### ISSUE TITLE
`null_on_oob` set to False in `list.take` with single indices doesn't return error

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10079]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [[1, 2, 3], [], [None, 3], [5, 6, 7]],
        "b": [['2'], ['3'], [None], ['3','Hi']],
        
    }
)
print(df.select(pl.col("a").list.take([999], null_on_oob=False)))

shape: (4, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [null]    │
│ [null]    │
│ [null]    │
│ [null]    │
└───────────┘

print(df.select(pl.col("a").list.take(999, null_on_oob=False)))
shape: (4, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [null]    │
│ [null]    │
│ [null]    │
│ [null]    │
└───────────┘
```

### Issue description

Null_on_oob set to False doesn't work when you pass a one integer wrapped in a list as indices. Same thing happens when you only pass a single integer (which also isn't mentioned in type hints that it accepts an integer).

### Expected behavior

```python
print(df.select(pl.col("a").list.take([999], null_on_oob=False)))
```
```python
ComputeError: take indices are out of bounds
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22000-SP0
Python:              3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.17
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Looks like there is a fast path check if the length is 1 and it dispatches to `lst_get()` instead of `lst_take()`

https://github.com/pola-rs/polars/blob/fdbdd1c75c5376f7c26d5bbefc3b941a69edefe2/polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs#L229-L237

I think the single integer may fall under the type hint of `Expr`
