### ISSUE TITLE
DataFrame .rename method should ignore mapping dict keys that are not found in the column names

### ISSUE THREAD

**Issue by adrivn** [pola-rs/polars#10091]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

column_names_mapper = {"A": "a_renamed", "B": "b_renamed"}
column_names_mapper_with_another_key = {"A": "a_renamed", "B": "b_renamed", "C": "c_renamed"}
df = pl.DataFrame({"A": [1,2,3], "B": [4,5,6], "D": [7,8,9]})
df.rename(column_names_mapper) # works as intended
df.rename(column_names_mapper_with_another_key # raises an exception
```

### Issue description

The `.rename` method for DataFrames throws an error when the mapper/dictionary instance passed to it contains key:value pairs which are not found in the DataFrame columns. Raises an exception of type `SchemaFieldNotFoundError`. More details here, using the example above:

```python
SchemaFieldNotFoundError                  Traceback (most recent call last)
Cell In[43], line 7
      5 df = pl.DataFrame({"A": [1,2,3], "B": [4,5,6], "D": [7,8,9]})
      6 df.rename(column_names_mapper)
----> 7 df.rename(column_names_mapper_with_another_key)

File [c:\Projects\Python\Envs\main\Lib\site-packages\polars\dataframe\frame.py:3526](file:///C:/Projects/Python/Envs/main/Lib/site-packages/polars/dataframe/frame.py:3526), in DataFrame.rename(self, mapping)
   3499 def rename(self, mapping: dict[str, str]) -> DataFrame:
   3500     """
   3501     Rename column names.
   3502 
   (...)
   3524 
   3525     """
-> 3526     return self.lazy().rename(mapping).collect(no_optimization=True)

File [c:\Projects\Python\Envs\main\Lib\site-packages\polars\lazyframe\frame.py:1508](file:///C:/Projects/Python/Envs/main/Lib/site-packages/polars/lazyframe/frame.py:1508), in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1497     common_subplan_elimination = False
   1499 ldf = self._ldf.optimization_toggle(
   1500     type_coercion,
   1501     predicate_pushdown,
   (...)
   1506     streaming,
   1507 )
-> 1508 return wrap_df(ldf.collect())

SchemaFieldNotFoundError: C
```

### Expected behavior

The method should ignore key:value pairs not found in the list of column names, and rename the rest (which are indeed found in the mapper/dictionary object).

Instead, it raises an `SchemaFieldNotFoundError`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
pandas:              2.0.2
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.16
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

to be honest I find the current behaviour expected - like this, you're notified immediately if you mis-spelled something in your renaming dict

you can just manually filter the dict before hand with one line of code anyway
```python
df.rename({key: value for key, value in column_names_mapper_with_another_key.items() if key in df.schema})
```

**Comment by adrivn** [comment]
> thanks for the report
> 
> 
> 
> to be honest I find the current behaviour expected - like this, you're notified immediately if you mis-spelled something in your renaming dict
> 
> 
> 
> you can just manually filter the dict before hand with one line of code anyway
> 
> ```python
> 
> df.rename({key: value for key, value in column_names_mapper_with_another_key.items() if key in df.schema})
> 
> ```

Thank you. Yes, I came up with pretty much the same workaround. Nonetheless, I figured it might be a good idea to notify of this behavior, given pandas implementation allows it (less friction when transitioning).

**Comment by ritchie46** [comment]
> given pandas implementation allows it (less friction when transitioning).

This is not something we take into consideration. We try to do what makes sense from our point of view.

**Comment by MarcoGorelli** [comment]
> Nonetheless, I figured it might be a good idea to notify

indeed, thanks - high quality issues with reproducible examples are what allow libraries to improve

closing for now then
