### ISSUE TITLE
use_earliest might be mis-designed

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#10090]
`use_earliest` is an argument to `replace_time_zone`, and can take three values:
- None: raise on ambiguous times
- True: use earliest of ambiguous times
- False: use latest of ambiguous times

Example:
```python
>>> pl.Series([datetime(2020, 10, 25, 1)]).dt.replace_time_zone('Europe/London')
# raises
>>> pl.Series([datetime(2020, 10, 25, 1)]).dt.replace_time_zone('Europe/London', use_earliest=True)
shape: (1,)
Series: '' [datetime[μs, Europe/London]]
[
        2020-10-25 01:00:00 BST
]
>>> pl.Series([datetime(2020, 10, 25, 1)]).dt.replace_time_zone('Europe/London', use_earliest=False)
shape: (1,)
Series: '' [datetime[μs, Europe/London]]
[
        2020-10-25 01:00:00 GMT
]
```

Now, it would be nice to be able to pass an expression to `use_earliest`

BUT - because the `null` values would be meaningful, they would need to be explicitly looped over. So, as far as I understand, this would mean having to loop over values in the chunked arrays, rather than operating directly on the primitive arrays

Maybe the API should be changed:
```
ambiguous : {'use_earliest', 'use_latest', 'raise'}
```
?

**Comment by stinodego** [comment]
I agree, I think an enum would be better suited for this parameter. The parameter indicates the strategy we should use for handling ambiguous timestamps. The parameter name `ambigous` makes sense, with the following values:
* `raise`
* `earliest`
* `latest`
* `null`
* `infer`
 
The last two would still need to be implemented. I am not fully convinced by `earliest` and `latest`, I think there may be a better name. `dst` and `standard`?

Related topic: do you think we need a `non_existent` parameter as well?

**Comment by MarcoGorelli** [comment]
Yeah that looks good.

On the names earliest/ latest, I just went with what chrono uses for their LocalResult https://docs.rs/chrono/latest/chrono/offset/enum.LocalResult.html

Implementing use_earliest was straightforward with chrono, but `non-existent` would require some workaround - not sure it's worth it, especially if nobody has requested it

**Comment by stinodego** [comment]
Right, earliest/latest seems fine then! We can start with a refactor with just raise/earliest/latest, and possibly add null/infer options later.

About non-existent: we can leave that for another time. Out of curiosity, what happens now when trying to create a non-existent timestamp?

**Comment by MarcoGorelli** [comment]
aalright, kinda got this working - much easier since `try_binary_elementwise_values` has been introduced!

I'll proceed as you suggested then

> Out of curiosity, what happens now when trying to create a non-existent timestamp?

it raises:
```python
In [22]: pl.Series([datetime(2020, 3, 29, 1)]).dt.replace_time_zone('Europe/London')
---------------------------------------------------------------------------
ArrowErrorException                       Traceback (most recent call last)
Cell In[22], line 1
----> 1 pl.Series([datetime(2020, 3, 29, 1)]).dt.replace_time_zone('Europe/London')

File ~/tmp/.venv/lib/python3.10/site-packages/polars/series/utils.py:102, in call_expr.<locals>.wrapper(self, *args, **kwargs)
    100     expr = getattr(expr, namespace)
    101 f = getattr(expr, func.__name__)
--> 102 return s.to_frame().select(f(*args, **kwargs)).to_series()

File ~/tmp/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py:7452, in DataFrame.select(self, *exprs, **named_exprs)
   7350 def select(
   7351     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7352 ) -> DataFrame:
   7353     """
   7354     Select columns from this DataFrame.
   7355
   (...)
   7450
   7451     """
-> 7452     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~/tmp/.venv/lib/python3.10/site-packages/polars/utils/deprecation.py:93, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     88 @wraps(function)
     89 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     90     _rename_keyword_argument(
     91         old_name, new_name, kwargs, function.__name__, version
     92     )
---> 93     return function(*args, **kwargs)

File ~/tmp/.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py:1695, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, streaming)
   1683     comm_subplan_elim = False
   1685 ldf = self._ldf.optimization_toggle(
   1686     type_coercion,
   1687     predicate_pushdown,
   (...)
   1693     streaming,
   1694 )
-> 1695 return wrap_df(ldf.collect())

ArrowErrorException: InvalidArgumentError("datetime '2020-03-29 01:00:00' is non-existent in time zone 'Europe/London'. Non-existent datetimes are not yet supported")
```
