### ISSUE TITLE
`sink_parquet`: argument `row_group_size` is not working correctly

### ISSUE THREAD

**Issue by pyjads** [pola-rs/polars#10108]
`df.sink_parquet(filepath, row_group_size=1000)`

The syntax does not create the correct row_group_size and according to documentation 

`If None and use_pyarrow=True, the row group size will be the minimum of the DataFrame size and 64 * 1024 * 1024.`

If I use the syntax:
`df.sink_parquet(filepath, row_group_size=1000, use_pyarrow=True)`

I get below error:
LazyFrame.sink_parquet() got an unexpected keyword argument 'use_pyarrow'

**Comment by ritchie46** [comment]
What is you point about pyarrow? Sink parquet doesn't have a `pyarrow` argument?

**Comment by ritchie46** [comment]
What is the row-group size you observe currently?

**Comment by pyjads** [comment]
for a particular lazyframe, I use the syntax.
`df.sink_parquet(filepath, row_group_size=200)`

I then check the metadata of the parquet file.

Here is the metadata of the file

num of rows: 1151838

num of row groups: 483
row groups:

row group 0:
--------------------------------------------------------------------------------
total byte size: 421313
num of rows: 1159

num of columns: 21
columns:

**Comment by aut0clave** [comment]
https://github.com/pola-rs/polars/blob/868f6e5154efdcc7c7c019ebe65b227df99ce333/py-polars/polars/lazyframe/frame.py#L1593-L1958

**Comment by pyjads** [comment]
any update on the task?

**Comment by stinodego** [comment]
Fixed the docs in #10669

If someone can reproduce the issue with the `row_group_size`, this can be accepted and fixed.

**Comment by RansomT** [comment]
I can reproduce this issue, sink_parquet seems to ignore row_group_size.

Running in a container:
    image:                 python:slim-bookworm
    polars version:    polars==0.19.2
    python version:   Python 3.11.5


>>> import polars as pl
>>> import pyarrow.parquet as pq
>>>
>>> lf = pl.scan_parquet('example.parquet')
>>> lf.sink_parquet('test_sink.parquet', row_group_size=5000)
>>> pq.read_metadata('test_sink.parquet')
<pyarrow._parquet.FileMetaData object at 0x7f133c1a6020>
  created_by: Arrow2 - Native Rust implementation of Arrow
  num_columns: 95
  num_rows: 50000
  num_row_groups: 32
  format_version: 2.6
  serialized_size: 194730


Doing same with full DataFrame


>>> full_df = pl.read_parquet('example.parquet')
>>> full_df.write_parquet('test_write.parquet', row_group_size=5000)
>>> pq.read_metadata('test_write.parquet')
<pyarrow._parquet.FileMetaData object at 0x7f13377e2b10>
  created_by: Arrow2 - Native Rust implementation of Arrow
  num_columns: 95
  num_rows: 50000
  num_row_groups: 10
  format_version: 2.6
  serialized_size: 70129

**Comment by igoichuk** [comment]
I reproduced the same issue using polars 0.19.3. It makes no difference if you provide row_group_size value or leave it None, sink_parquet() generates the same number of row groups (big number of smallish groups). While write_parquet() works as expected.

**Comment by stinodego** [comment]
Closing in favor of #13092 as it has a reproducible example.
