### ISSUE TITLE
Expr equality containing rolling_* does not work

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#10101]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.col("A").rolling_sum(10).meta.eq(pl.col("A").rolling_sum(10))
```

### Issue description

I'm guessing that expr equality is maybe not fully implemented, but here is one such example I ran into when writing tests:

```python
pl.col("A").rolling_sum(10).meta.eq(pl.col("A").rolling_sum(10))
```
returns False. On the other hand,
```python
pl.col("A").sum().meta.eq(pl.col("A").sum())
```
returns True

### Expected behavior

Polars can identify that the two rolling expressions are equal.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            macOS-13.2-arm64-arm-64bit
Python:              3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          3.7.0
numpy:               1.24.3
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.5
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
While trying to debug this, I tried `.write_json()`
```python
pl.col("A").rolling_sum(10).meta.write_json()
# ValueError: Error("serialize not supported for this 'opaque' function", line: 0, column: 0)
```
Perhaps this is a related to the underlying issue.

**Comment by erinov1** [comment]
You're probably right, seems like it was a serdes issue for some other expressions: https://github.com/pola-rs/polars/issues/8109

**Comment by ritchie46** [comment]
Yes, the `rolling_` logic needs to be rewritten from `apply` to `apply_private`. 

This PR shows how this is done with the `log` function: https://github.com/pola-rs/polars/pull/8126/files

This is a good first issue.

**Comment by alvaroqueiroz** [comment]
Hello, can I work on this issue?
if so, assign to me!

**Comment by erinov1** [comment]
@alvaroqueiroz that would be great. I don't think people will be clamoring to submit PRs for this one, so I'm sure you are fine without an assignment from one of the maintainers.
