### ISSUE TITLE
`pl.from_pandas` does not include index even when parameter is True

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#10119]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd

df_pd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

df_pl = pl.from_pandas(df_pd, include_index=True)

┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘
```

### Issue description

The `include_index` parameter does not seem to work in the latest Polars release

### Expected behavior

Index is included in the Polars dataframe

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by cmdlineluser** [comment]
It seems this option only loads "non-default" indexes.
> Load any non-default pandas indexes as columns.

https://github.com/pola-rs/polars/blob/808bc594ac03d1f53a0fae4e1031a7c759abd033/py-polars/polars/utils/_construction.py#L1503-L1521

https://github.com/pola-rs/polars/blob/808bc594ac03d1f53a0fae4e1031a7c759abd033/py-polars/tests/unit/test_interop.py#L170

**Comment by stinodego** [comment]
This is not a bug, but I can see how it can be confusing. Not sure if we should change this.
