### ISSUE TITLE
Deprecate `from_rows`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#1011]
With the newly added functionality in the DataFrame constructor, the `from_rows` method in `functions.py`, as well as the `DataFrame.from_rows` method, seem outdated. We can deprecate those and suggest using the `DataFrame` constructor instead with the `orientation='row'` argument. That seems more Pythonic.

Now that I think about it, we should deprecate `from_arrow` and `from_pandas` as well, and build this into the constructor of `Series`/`DataFrame` (partly already there).

**Comment by ritchie46** [comment]
> Now that I think about it, we should deprecate from_arrow and from_pandas as well, and build this into the constructor of Series/DataFrame (partly already there).

The `from_pandas` and `from_arrow` may produce a `Series` as well as a `DataFrame`. IMO the specific constructors may still exists in the API. The constructor dispatches to them. Explicitness can improve readability.

In pandas API there is also `DataFrame.from_dict` and `DataFrame.from_records`.

**Comment by stinodego** [comment]
All right, if you look at it that way: we could 'unpack' the constructor to make all types that it can interpret explicit functions. So DataFrame would get a `from_dict`, `from_pandas`, `from_ndarray`, etc. Same for Series. That would actually make the constructors much more readable, too. Does that sound like a good idea?

We can then keep the `from_pandas` etc. in `functions.py` to automatically infer whether it should create a Series or Dataframe. Although I'm not sure why you'd want to do that.

**Comment by ritchie46** [comment]
> DataFrame would get a from_dict, from_pandas, from_ndarray, etc. Same for Series. That would actually make the constructors much more readable, too

I think that's a good idea.

> We can then keep the from_pandas etc. in functions.py to automatically infer whether it should create a Series or Dataframe. Although I'm not sure why you'd want to do that.

Perhaps its a good idea to create a `conversion.py` module. This should make it more clear that we convert from external datatypes to polars and infer the needed polars type. This should have an `from_arrow`, `from_pandas`, `from_numpy`, and maybe other future types.

**Comment by stinodego** [comment]
Okay, I'll give that a shot later this week!

**Comment by stinodego** [comment]
I did some work, encountered a few things.

First of, moving some of the constructor logic to the `from_x` methods doesn't work. The `from_x` methods must be static or classmethods, and so it doesn't make sense to use those in a class constructor. So, I'm leaving the constructors intact for now. I saw pandas has an internal `constructions` module where they put all this logic; seems kinda neat to me. That could be a separate refactor.

Then about the `from_x` methods, since the constructor can handle everything, they all look kinda like this:
```python
    @classmethod
    def from_dict(
        cls,
        data: Dict[str, Sequence[Any]],
        columns: Optional[Sequence[str]] = None,
        nullable: bool = True,
    ) -> "DataFrame":
        return cls(data, columns=columns, nullable=nullable)
```

A `from_numpy` method would also take the `orientation` arg, but otherwise looks the same. That brings me to my point: there is no sense in having a `from_rows` method. It would look exactly the same as the `from_numpy` method, since all logic is defined in the constructor.

So I would suggest that we have a limited amount of `from_x` methods:
* `from_dict`
* `from_records` -> for when you have to specify row or column orientation
* `from_arrow` -> because this logic isn't in the constructor yet
* `from_pandas` -> just to make this explicit; could also leave this out

I really don't see a place for a `from_rows` that does exactly what `from_records` does but with `orient='row'` specified. Sooo, deprecate it? 👼

**Comment by ritchie46** [comment]
> The from_x methods must be static or classmethods, and so it doesn't make sense to use those in a class constructor

You could use `self._df =from_x(...)._df` in the constructor. It would improve readability and code duplication. 

I actually want to make the separate DataFrame class methods private and document the `pl.from_x` and the DataFrame constructor as idiomatic.


> I really don't see a place for a from_rows that does exactly what from_records does but with orient='row' specified. Sooo, deprecate it? 

Agree. :slightly_smiling_face:

**Comment by stinodego** [comment]
> > The from_x methods must be static or classmethods, and so it doesn't make sense to use those in a class constructor
> 
> You could use `self._df =from_x(...)._df` in the constructor. It would improve readability and code duplication.

I saw that pattern in the Series constructor. There's a few things about that I don't like:
* It just feels wrong to have a class constructor call another method that constructs an object of that same class, then take part of that object, and then use it in the constructor to finish building the class. Convoluted and inefficient.
* The DataFrame constructor currently converts all inputs to a list of Series objects first, then has some logic to handle the `columns` arg. I'd have to duplicate that logic in each `from_x` method, or create a function somewhere that I'd have to use in each of the `from_x` methods. Not great for readability.

Why don't we put all this conversion logic in a `construction.py`. Keeps the DataFrame class clean and easy to read. Keeps the `from_x` methods nice and simple. No convoluted hacky solutions needed. _(check out [the competition](https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/construction.py))_

> I actually want to make the separate DataFrame class methods private and document the `pl.from_x` and the DataFrame constructor as idiomatic.

Sounds good to me. But if the DataFrame constructor is idiomatic, why have `DataFrame.from_x` methods at all? Just call the constructor from `pl.from_x`.

**Comment by ritchie46** [comment]
> The DataFrame constructor currently converts all inputs to a list of Series objects first, then has some logic to handle the columns arg. I'd have to duplicate that logic in each from_x method, or create a function somewhere that I'd have to use in each of the from_x methods. Not great for readability.

So you'd propose doing that only in the `__init__`? A function seems ok to me. 

> It just feels wrong to have a class constructor call another method that constructs an object of that same class, then take part of that object, and then use it in the constructor to finish building the class. Convoluted and inefficient.

Doing it in private specific constructors is fine by me as well. I think that's what you are proposing here? 

>> Why don't we put all this conversion logic in a construction.py somewhere. Keeps the DataFrame class clean and easy to read. Keeps the from_x methods nice and simple. No convoluted hacky solutions needed. (check out the competition)

I think I agree. :)


> Sounds good to me. But if the DataFrame constructor is idiomatic, why have DataFrame.from_x methods at all? Just call the constructor from pl.from_x.

That was easier for FFI. But the end user should not know about our FFI preferences that's why I'd like private specific constructors:

* `DataFrame._read_csv`
* `DataFrame._read_ipc`

etc.

And then use the top level functions `pl.read_csv`, etc. to dispatch to the private constructors. The private constructors may have all logic to keep things DRY. Then we also don't need `self._df =from_x(...)._df`, and can dispatch to the private constructors from the `__init__`.

**Comment by stinodego** [comment]
Hmm, I can't envision the solution 100% yet, but I think I have enough to go on for now. I'll work on this some more tonight or in the weekend.

**Comment by stinodego** [comment]
The code for parsing a pandas DataFrame in the constructor is completely different from the parsing logic in `pl.from_pandas`; most notably the `pl.from_pandas` (and `pl.from_arrow`) takes a `rechunk` argument; should this be available in the `DataFrame` constructor as well?

**Comment by ritchie46** [comment]
> The code for parsing a pandas DataFrame in the constructor is completely different from the parsing logic in pl.from_pandas; most notably the pl.from_pandas (and pl.from_arrow) takes a rechunk argument; should this be available in the DataFrame constructor as well?

I think that if we encounter a pandas table or an arrow table in the constructor we should dispatch to `pl.from_pandas` using that functions default arguments. If users want more control, they ought to use the specialized functions.

**Comment by ritchie46** [comment]
Deprecated.
