### ISSUE TITLE
Polars `apply` changing key order in returned dict

### ISSUE THREAD

**Issue by desmond-dsouza** [pola-rs/polars#10128]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars import Struct, Field

## With this dtype defined (note reverse-alpha field order):
Similarity = Struct([
    Field('z', pl.Float64),
    Field('y', pl.Float64),
    Field('x', pl.List(pl.Int64))
])

## When I run this `apply` returning a fixed dict that matches `Similarity` in keys, type, and order:

df = pl.DataFrame({'a': [0, 1]})
df.with_columns(
    pl.col('a')
    .apply(lambda d: {'z':1.1, 'y': 0.1, 'x': [2]},
           return_dtype=Similarity))

## I get this SchemaError with key order mismatch (note key order): 
## **SchemaError: 
## expected output type ...**

Struct([
  Field { name: "z", dtype: Float64 }, 
  Field { name: "y", dtype: Float64 }, 
  Field { name: "x", dtype: List(Int64) }])

##**...got (note alphabetical key order)...**

Struct([
  Field { name: "x", dtype: List(Int64) }, 
  Field { name: "y", dtype: Float64 }, 
  Field { name: "z", dtype: Float64 }])
```

### Issue description

It appears that Polars is sorting the keys of returned dicts in alphabetical order, causing a difference from the order in the `return_dtype` struct. 

### Expected behavior

The code above should just run without any Schema error, as it does without the `return_dtype` spec:
```python
df.with_columns(
    pl.col('a')
    .apply(lambda d: {'z':1.1, 'y': 0.1, 'x': [2]},
           return_dtype=Similarity))

shape: (2, 1)
┌───────────────┐
│ a             │
│ ---           │
│ struct[3]     │
╞═══════════════╡
│ {[2],0.1,1.1} │
│ {[2],0.1,1.1} │
└───────────────┘

```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            macOS-11.7.8-x86_64-i386-64bit
Python:              3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by avimallu** [comment]
What is `Struct` here? Your code doesn't seem reproducible - `name 'Struct' is not defined`; which package is this from?

**Comment by cmdlineluser** [comment]
It looks like the codepath taken is this:
https://github.com/pola-rs/polars/blob/6f50fb8ff53fb1a29f3c94479f1a199a1bc38452/py-polars/src/apply/lazy.rs#L45

Which ends up calling:
https://github.com/pola-rs/polars/blob/6f50fb8ff53fb1a29f3c94479f1a199a1bc38452/py-polars/src/conversion.rs#L687

Adding in some `dbg!()` calls  in `get_struct()` show the correct order, however `pyseries.series` has the field names sorted.

Which suggests this may happen in the `PySeries` creation part?

**Comment by cmdlineluser** [comment]
A minimal example of the problem:
```python
pl.select(pl.lit("").apply(lambda x: dict(c=1, b=2, a=3)))

# shape: (1, 1)
# ┌───────────┐
# │ literal   │
# │ ---       │
# │ struct[3] │
# ╞═══════════╡
# │ {3,2,1}   │ # should be {1,2,3}
# └───────────┘
```
https://github.com/pola-rs/polars/blob/6f50fb8ff53fb1a29f3c94479f1a199a1bc38452/py-polars/src/apply/mod.rs#L55
A BTreeMap sorts its keys so the original field order is not retained.
