### ISSUE TITLE
Discussion: Generalised database driver support

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#10121]
@alexander-beedie following up on our discussion in https://github.com/pola-rs/polars/pull/10111

From what I've seen, most Python database drivers implement [PEP 249](https://peps.python.org/pep-0249/) plus some extra methods for Arrow fetching:

- [Snowflake](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api): `fetch_arrow_all()`
- [Databricks](https://github.com/databricks/databricks-sql-python/blob/main/src/databricks/sql/client.py#L703): `fetchall_arrow()`
- [Turbodbc](https://turbodbc.readthedocs.io/en/latest/pages/advanced_usage.html#obtaining-apache-arrow-result-sets): `fetchallarrow()`
- [ADBC](https://github.com/pola-rs/polars/blob/fad5b133dbb50b874df29c69cef62de9d5793b3b/py-polars/polars/io/database.py): `fetch_arrow_table()`

Exception:

- [Connectorx](https://github.com/pola-rs/polars/blob/fad5b133dbb50b874df29c69cef62de9d5793b3b/py-polars/polars/io/database.py#L144): `read_sql`
- [DuckDB](https://duckdb.org/docs/api/python/overview.html#result-conversion): `arrow()`

My idea is to accept any connection object that follows PEP 249 and has a list of "fetch arrow table" method names that we brute-force on the connection object.

Then we can remove connection handling completely from Polars.

This adapter could also live in a project outside of Polars, then it could be used with Pandas and other Arrow readers.

**Comment by alexander-beedie** [comment]
> Then we can remove connection handling completely from Polars.

This won't happen completely as there is no such thing as a `connectorx` connection, so we will need to continue to support string URIs. However, I also agree that we should allow user-instantiated connections and get out of the connection-handling business in this case  ;)

This will also allow us to take advantage of a lot more drivers with minimal work on our side; a map of driver to Arrow return functionality (as listed above) would be a good start.

> This adapter could also live in a project outside of Polars

This "adaptor" is likely to be trivial - no need to raise it to the status of an entire project  ;) 

Anyway, let's not rush - I'll take a look over some of the options above and have a think about how to clean up the API.

**Comment by alexander-beedie** [comment]
@jonashaag: Done! Available in the upcoming `0.19.0` :)
