### ISSUE TITLE
`null_count()` for Structs is inconsistent.

### ISSUE THREAD

**Issue by magarick** [pola-rs/polars#10130]
It has been said that elements of a struct series are null when all of their fields are null. But alas, `null_count()` doesn't seem to know that.
If every field has at least one null, it will return the total count across all fields. If there exists a field with no nulls it will return 0. I think I see where the issue is, but before fixing it, what behavior do we want? And do we want the ability to ask for either the number of "null rows" AND "total nulls"? Example:
```python
>>> a = pl.DataFrame({"x": [None, 0, 0, 1, 1], "y": [0, 0, 1, 0, 1]}).to_struct("xy")
>>> b = pl.DataFrame({"x": [1, None, 0, 0, 1, 1, None], "y": [None, 0, None, 0, 1, 0, 1]}).to_struct("xy")
>>> a.null_count()
0
>>> b.null_count()
4
```

**Comment by ritchie46** [comment]
Yes, I think we want an option that clarifies struct null count behavior. 

For one, internally I'd like both behaviors.

**Comment by magarick** [comment]
You can also get it to do this
```python
>>> s = pl.Series([{'a': 1, 'b': 2}])
>>> r = pl.Series([{'a':None, 'b': None}], dtype=pl.Struct({'a': pl.Int64, 'b': pl.Int64}))
>>> s.append(r)
shape: (2,)
Series: '' [struct[2]]
[
	{1,2}
	{null,null}
]
>>> s.null_count()
0
```

I found the bug and I'll fix it. I'll also include a `total_null_count` field in `StructChunked` then you get both.

**Comment by jonashaag** [comment]
In #10142 the null count behaviour is changed to always count all-null structs as null. I think this can surprising. Intuitively I'd not consider an all-null struct to be "absent data".

**Comment by magarick** [comment]
@jonashaag I agree with you that in principle there's a difference. After all the set ${}$ is not the same as ${{}}$. If you take a look at in `crates/polars-core/src/chunked_array/logical/struct_/mod.rs` it's got the comment
```
/// Different from  [`StructArray`](arrow::array::StructArray), this
/// type does not have its own `validity`. That means some operations
/// will be a bit less efficient because we need to check validity of all
/// fields. However this does save a lot of code and compile times.
```
Maybe @ritchie46 has some insights into this design decision. It could be worth the tradeoff depending on how structs are used in practice. For me, I see them mostly as a convenient way to represent a sub-DataFrame inside of expressions and work around the fact that the API wants functions to produce and consume only series.
