### ISSUE TITLE
Support `null_strategy` parameter for GroupBy/LazyGroupBy

### ISSUE THREAD

**Issue by Ludecan** [pola-rs/polars#10155]
### Problem description

Sorry if there's a better way to do this, I'm still getting the hang of Polars, but it seems to me like GroupBy/LazyGroupBy aggregations could use the `null_strategy` parameter that DataFrame aggregations have?
If I have the following dataframe:

```
df = pl.DataFrame(
    data={
        "groups": [0, 0, 0, 1, 1, 1],
        "values": [1, 2, 3, 1, None, 2]
    }
)
```
I'd like to calculate the group means propagating Nulls, ie if a group has a Null value I'd like the group's mean to be Null.
A groupby mean ignores the Nulls and I can't seem to find a way to propagate them:
```
df.groupby("groups").mean()
```
Gives:
groups | values
-- | --
i64 | f64
0 | 2.0
1 | 1.5

Where I would like:
groups | values
-- | --
i64 | f64
0 | 2.0
1 | Null

Would it make sense to add the `null_strategy` parameter to GroupBy/LazyGroupBy aggregation functions to do this?
Is there another idiomatic way to do what I'm trying to do?
Thanks in advance

**Comment by avimallu** [comment]
There is an [encompassing issue tracking this across Polars](https://github.com/pola-rs/polars/issues/10016) - pheraps you can contribute your opinion there?

**Comment by Ludecan** [comment]
Thanks, shared my take there. I'm closing this issue.
