### ISSUE TITLE
Not yet initialized with incompatible `.is_in` when `object` flag is disabled

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#10157]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series([]).is_in(pl.Series([[]]))
# => PanicException: not yet initialized
```

### Issue description

When I remove the `"object"` flag from the features of the py-polars build, this happens.

### Expected behavior

Should not raise

### Installed versions

Latest master

**Comment by jonashaag** [comment]
Hm I can't reproduce with the latest release

**Comment by jonashaag** [comment]
Related, this crashes:

```
pl.Series([1]).is_in(pl.Series([[]]))
PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("cannot unpack series, data types don't match"))
```

**Comment by ritchie46** [comment]
Then don't remove the object flag? Functionality will break if you don't compile all of polars' features. We are not guaranteeing anything less here.

**Comment by jonashaag** [comment]
Do you consider this case incorrect use of the is_in feature flag? Clearly is_in requires something that's enabled by the object flag. I could make an attempt to fix the flags.

**Comment by ritchie46** [comment]
It is more that we have a lot to do and if people turn off feature flags, ofcourse stuff breaks.

**Comment by jonashaag** [comment]
Not sure I understand what you are trying to say. In any case I'm going to close this because it's unsupported territory.

This is at least the second time removing `object` from the flags broke random other stuff, maybe it's just not a good idea to disable `object`.

Generally it's not obvious what flags can be turned off easily to reduce compilation times, and what flags are going to break things. A curated "mini" set of py-polars feature flags would be really nice as a starting point for contributors that don't know the ins and outs of each of the feature flags.

**Comment by ritchie46** [comment]
They are not intended to be turned off
 They only serve for development use cases. Of you want to use polars and compile from scratch all features should be turned on, otherwise functionality may break.
