### ISSUE TITLE
Write_delta doesn't update schema Uint -> Int while comparing schemas

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10153]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.from_repr("""┌─────────────────┬───────────────────┬───────┬────────────────────────────────┐
│ source_actor_id ┆ source_channel_id ┆ ident ┆ timestamp                      │
│ ---             ┆ ---               ┆ ---   ┆ ---                            │
│ u32            ┆ i64               ┆ str   ┆ datetime[us]      │
╞═════════════════╪═══════════════════╪═══════╪════════════════════════════════╡
│ 123456780       ┆ 9876543210        ┆ a:b:c ┆ 2023-03-25 10:56:59.663053  │
│ 803065983       ┆ 2055938745        ┆ x:y:z ┆ 2023-03-25 12:38:18.050545  │
└─────────────────┴───────────────────┴───────┴────────────────────────────────┘""")

df.write_delta('test', mode='append') # First write is fine since no overwrite schema is passed and DeltaLake writer handles the casting
df.write_delta('test', mode='append') # fails  at second write

ValueError: Schema of data does not match table schema
Table schema:
source_actor_id: uint32
source_channel_id: int64
ident: large_string
timestamp: timestamp[us]
Data Schema:
source_actor_id: int32
source_channel_id: int64
ident: string
timestamp: timestamp[us]
```

### Issue description

The current setup of write_delta will always fail when the dataframe contains unsigned integers. Since DeltaLake doesn't support Unsigned primitive types, the table_schema.to_pyarrow(as_large_types=True) will never contain unsigned integers, hence it returns False and then writing fails because the original df.to_arrow().schema was passed that contains Uints.

https://github.com/delta-io/delta-rs/issues/1528#issuecomment-1656407891

> 
> Actually, there are two issues at play here, one is on polars side not handling the unsignedness while creating the schema to write with, and the other one is the wrong comparison in the writer.
> 
> Polars is doing [this](https://github.com/pola-rs/polars/blob/868f6e5154efdcc7c7c019ebe65b227df99ce333/py-polars/polars/dataframe/frame.py#L3356C1-L3363C56):
> 
> ```python
>         # Workaround to prevent manual casting of large types
>         table = try_get_deltatable(target, storage_options)  # type: ignore[arg-type]
> 
> 
>         if table is not None:
>             table_schema = table.schema()
> 
> 
>             if data_schema == table_schema.to_pyarrow(as_large_types=True):
>                 data_schema = table_schema.to_pyarrow()
> ```
> 
> `data_schema == table_schema.to_pyarrow(as_large_types=True)` will result in False because the left-hand side will have unsigned integers and the right-hand side will have integers.

### Expected behavior

Polars to handle the unsigned integer casting to signed integers when writing delta tables. 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.11.4 (main, Jul 16 2023, 15:13:18) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.1
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
Thanks for the report. I confirmed the issue.

@chitralverma Could you perhaps take a look at this?

**Comment by ion-elgreco** [comment]
> Thanks for the report. I confirmed the issue.
> 
> @chitralverma Could you perhaps take a look at this?

I've made an attempt to fix it. It works, however perhaps there is a smarter way of doing it. Could you perhaps have a look at the PR?
