### ISSUE TITLE
Parse Expr for rolling_apply to extend rolling* 

### ISSUE THREAD

**Issue by graceyangfan** [pola-rs/polars#10169]
### Problem description

Since polars has few rolling* operator and many operators for LazyDataFrame/Expr,Is possible to parse pl.Expr into some polars original computing logical so that users can fast extend rolling* function and keep the original speed of its operator,for example:
if we want `rolling_sum` for  column `A` over column `B`,users can define something like this: 
```
pl.rolling_apply(pl.col("A").sum(),windows_size=5).over("B")
```
such as `rolling_arg_max':
```
pl.rolling_apply(pl.col("A").arg_max(),windows_size=5).over("B")
```
This could reduce the work to define every new operator

**Comment by magarick** [comment]
Would using "ordinary" functions like `min`, `max`, `mean`, etc. inside a `groupby_dynamic` do what you want?

**Comment by graceyangfan** [comment]
@magarick  I has trying groupby_rolling to achieve same function,but `groupby` always return a new lazydataframe,when it comes into complex logical computing,Expr computing is much elegant,it can generate pipeline more easily.for example,if we want expression like this:
`expression = pl.rolling_apply(pl.col("A").sum(),window_size =5 ).over("B") + pl.rolling_apply(pl.col("C").sum(),window_size =5 )).over("D")`
then we only need to do:``` df.with_columns(factor = expression)```
but if we use groupby,we have to join the results with df 
``` 
df1 = df.with_columns(pl.arange(0,pl.count()).alias("index"))
df1= df.groupby_rolling("index",period="5i",by="B").agg(pl.col("A").sum().alias("x"))
df2= df.with_columns(pl.arange(0,pl.count()).alias("index"))
df2= df.groupby_rolling("index",period="5i",by="D").agg(pl.col("C").sum().alias("y"))
df3 = df1.join(df2,***)#ingore some 
df3 = df3.with_columns(factor = pl.col("x") + pl.col("y")]
```

**Comment by graceyangfan** [comment]
Since `groupby_rolling` is going to be include in select,so this topic can be closed
