### ISSUE TITLE
Make Contributing to Polars easier/more accessible

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10166]
### Problem description

Hello everyone,
I and many other people love polars and want to contribute to it.

Raising issues is a great start, but contributing "code" (documentation, tests, bug fixes, features, optimizations, etc.) is even cooler.

Today I tried to follow the instructions in the contributing guide to get started, but I encountered a few issues:

- `make test` failed with with some errors. No idea how I fixed it, but I did somehow...
- `rust-analyzer` has a few complaints. `Failed to spawn one or more proc-macro servers`
- Linting / Inlay hints are only partially working.
- Lots of `Code is inactive` due to some `cfg` flags.
- No real idea where to start
- No idea how the project is structured
- No idea how to run the tests, which tests to run, where to write tests, etc.
- ...

What I would love to see:
- DevContainer (`.devcontainer/devcontainer.json`) setup for the project
    - this is huge! It allows people to get started with the project in a few clicks and have a working environment!! (vscode, codespaces)
    - I can imagine that many people would like to contribute to polars, but are not familiar with the rust ecosystem. This would help them a lot!
- Documentation on how to get started with the project
    - How is the project structured?
    - What are the main components / data structures / concepts?
    - How to run the tests?
    - How / where to write rust code?
    - How / where to write python code?
    - How to build/compile the project and import + test it in python?
    - ...

**Comment by cmdlineluser** [comment]
> DevContainer 

I think there is a pull request for this: https://github.com/pola-rs/polars/pull/9697

> `make test` failed with with some errors. No idea how I fixed it, but I did somehow...

1 or 2 tests appear to be "flaky" from what I've seen, there's also 1 that seems to always fail when I `make test` locally:
```
FAILED tests/unit/test_serde.py::test_pickle_lazyframe_nested_function_udf
```

As for what the contributing page currently has, it seems to cover the basic points you've listed?

https://github.com/pola-rs/polars/blob/6943c6d5e38292f0edba54c4a12cd4f8b6f0bea4/CONTRIBUTING.md?plain=1#L113-L124


Within [py-polars](https://github.com/pola-rs/polars/tree/main/py-polars) you have the following structure:
```
py-polars/src/    # rust
py-polars/polars/ # python
py-polars/tests/  # tests
```
It doesn't seem to specifically mention building, I found that from `make` / `make help`
```
$ make help
Available commands:
  .venv              Set up virtual environment and install requirements
  build              Compile and install Polars for development
  build-release      Compile and install a faster Polars binary
  clean              Clean up caches and build artifacts
  clippy             Run clippy
  coverage           Run tests and report coverage
  doctest            Run doctests
  fmt                Run autoformatting and linting
  help               Display this help screen
  pre-commit         Run all code quality checks
  requirements       Install/refresh all project requirements
  test               Run fast unittests
  test-all           Run all tests
```
So it's `make build` to compile/install for development.

You can see what it actually does by looking at the Makefile:
https://github.com/pola-rs/polars/blob/6943c6d5e38292f0edba54c4a12cd4f8b6f0bea4/py-polars/Makefile#L25-L26

**Comment by stinodego** [comment]
I fully appreciate this sentiment. Polars is not simple project by any means. It's my mission to make the barrier for entry as low as possible, but it's not really possible to sit down and write a fully comprehensive document that explains everything.

For example, you mention you have trouble setting up `rust-analyzer`, but that really goes beyond the scope of what we can include in our contributing guide. Some knowledge of the Rust ecosystem is expected.

In the end, it's a combination of eliminating technical debt, writing documentation, and improved tooling that will help lower the bar for contributors.

Regarding your suggestions:

* Proposal to add devcontainer is [here](https://github.com/pola-rs/polars/issues/9690). It is accepted and will hopefully be added soon.
* Project structure will probably not make it to a Markdown file any time soon. This is quite fluid, and we're not going to rewrite our documentation with every refactor. There is some very high-level info in the contributing guide.
* We should probably write down some core concepts though about the data structures. But don't expect too much detail here. You'll have to bite the bullet and read the code.
* Your other points are in the contributing guide already. If you need more detail, please be more specific about what you're running into and I can see if I can add it (or open a PR yourself!).

Our Discord is also a great place to ask for help setting up your stuff. Link is in the contributing guide.

I will close this issue as there are no concrete actionable items here for me to pick up. But know that I take this topic seriously and will continue to work on this.
