### ISSUE TITLE
read_database incurs 'pyodbc.Connection' object has no attribute 'split

### ISSUE THREAD

**Issue by jhowa1** [pola-rs/polars#10177]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import pyodbc
import polars as pl

cxcn = pyodbc.connect(DSN=r'aw2019')
cursor = cxcn.cursor()

query = "SELECT current_timestamp"

# Reading data using Pandas
data = pl.read_database(query, cxcn)

```

### Issue description

This SQL statement works with Pandas read_sql.   

Traceback (most recent call last):
  File "polars_debug.py", line 12, in <module>
    data = pl.read_database(query, cxcn)
  File "C:\python310\lib\site-packages\polars\utils\decorators.py", line 37, in wrapper
    return function(*args, **kwargs)
  File "C:\python310\lib\site-packages\polars\io\database.py", line 115, in read_database
    return _read_sql_connectorx(
  File "C:\python310\lib\site-packages\polars\io\database.py", line 146, in _read_sql_connectorx
    tbl = cx.read_sql(
  File "C:\python310\lib\site-packages\connectorx\__init__.py", line 216, in read_sql
    conn, protocol = rewrite_conn(conn, protocol)
  File "C:\python310\lib\site-packages\connectorx\__init__.py", line 42, in rewrite_conn
    backend, connection_details = conn.split(":", 1) if conn else ("", "")

### Expected behavior

The query should complete uneventfully

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.2
pandas:              2.0.0
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cjackal** [comment]
`pl.read_database` only accepts connection string, not arbitrary connection object. But I guess filtering out non-string `conn` earlier in polars side would give better UX.

**Comment by jhowa1** [comment]
ADBC is a great idea, but too young for my requirements.   ConnectX has issues with encrypt=true.   Just commented on an issue here:  [https://github.com/sfu-db/connector-x/issues/509](url)

I love the ideas behind both engines, but we need engine=ODBC for the workaround scenario.   My environment doesn't accept just turning off encrypted connection make something like connect-x work.

**Comment by cjackal** [comment]
If it is just about connecting to your DB using ODBC protocol and getting a polars dataframe as a return, [arrow-odbc](https://github.com/pacman82/arrow-odbc-py) may be sufficient. It returns a `pyarrow.RecordBatch`, which can be passed to `polars.from_arrow`.

**Comment by alexander-beedie** [comment]
I'll be allowing `read_database` to take user-supplied connection objects in the near future (see https://github.com/pola-rs/polars/issues/10121), so we can cover more bases. Should solve this issue.

**Comment by alexander-beedie** [comment]
@jhowa1: FYI: the upcoming `0.19.0` will be able to accept user-supplied database connections/cursors directly - this should include pyodbc :)

**Comment by jhowa1** [comment]
Will be watching for it and have code ready to go.   Thank you very much
for the work!!
