### ISSUE TITLE
corr() produces NaN on constant columns

### ISSUE THREAD

**Issue by pietz** [pola-rs/polars#10176]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 8, 3], "b": [4, 4, 4]})
df.select(pl.corr("a", "b"))
```

### Issue description

Using corr() on a constant column produces a NaN as a result. Not sure thats wanted.

### Expected behavior

I'm not familiar with the specifics of the algorithm but I would expect it to be 0.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.10.9 (main, Jan 12 2023, 17:05:32) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.4
sqlalchemy:          2.0.16
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by cjackal** [comment]
As the std of constant column is 0, correlation w/ constant column is a division by zero, so NaN is totally reasonable.

**Comment by pietz** [comment]
Makes sense. I was just used to polars not producing NaNs, I guess. Can be closed.
