### ISSUE TITLE
Incorrect set of rows when using not is_in condition on a lazy data frame that is created using a left join 

### ISSUE THREAD

**Issue by ashishbajpai** [pola-rs/polars#10181]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
import polars as pl

df1 = pl.DataFrame({
    "Groups": ['A', 'B', 'C', 'D', 'E', 'F'],
    "values0": [1, 2, 3, 4, 5, 6]
}).lazy()

df2 = pl.DataFrame({
    "values22": [1, 2, None, 4, 5, 6],
    "values20": [1, 2, 3, 4, 5, 6]
}).lazy()

df_all = df2.join(df1, left_on = 'values20', right_on = 'values0', how = 'left')

df_all.collect().shape
df_all.collect()

# expect 2rows and getting 2- All good 
df_all.filter(pl.col('Groups').is_in(['A','B'])).collect().shape
df_all.filter(pl.col('Groups').is_in(['A','B'])).collect()

# expect 3 rows and getting 6 
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect().shape
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect()

# if i apply the filter twice i get the right set of results
# expect 3 rows and getting 3 -- All good
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect().shape
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect()

# if i collect the results first and then apply the filter that also works
# expect three rows and getting 3 -- All good
df_all.collect().filter(~pl.col('Groups').is_in(['A','B', 'F']))

### Issue description

Getting incorrect set of rows when using not is_in condition in the filter with a lazy data frame that is created using left join.

### Expected behavior

import polars as pl

df1 = pl.DataFrame({
    "Groups": ['A', 'B', 'C', 'D', 'E', 'F'],
    "values0": [1, 2, 3, 4, 5, 6]
}).lazy()

df2 = pl.DataFrame({
    "values22": [1, 2, None, 4, 5, 6],
    "values20": [1, 2, 3, 4, 5, 6]
}).lazy()

df_all = df2.join(df1, left_on = 'values20', right_on = 'values0', how = 'left')

df_all.collect().shape
df_all.collect()

# if i apply the filter twice i get the right set of results
# expect three rows and getting 3 -- All good
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect().shape
df_all.filter(~pl.col('Groups').is_in(['A','B', 'F'])).filter(~pl.col('Groups').is_in(['A','B', 'F'])).collect()

# if i collect the results first and then apply the filter that also works
# expect three rows and getting 3 -- All good
df_all.collect().filter(~pl.col('Groups').is_in(['A','B', 'F']))

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.24.3
pandas:              2.0.2
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          2.0.18
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

**Comment by avimallu** [comment]
This looks like a case of an incorrect push-down of filter in lazy mode. Simpler version of your code:

```py
import polars as pl

df1 = pl.DataFrame({
"Groups": ['A', 'B', 'C', 'D', 'E', 'F'],
"values0": [1, 2, 3, 4, 5, 6]
}).lazy()

df2 = pl.DataFrame({
"values22": [1, 2, None, 4, 5, 6],
"values20": [1, 2, 3, 4, 5, 6]
}).lazy()

df_all = df2.join(df1, left_on = 'values20', right_on = 'values0', how = 'left')

print(df_all.filter(pl.col('Groups').is_in(['A','B','F'])).collect())
# Below should be opposite of above in terms of boolean
print(df_all.filter(~pl.col('Groups').is_in(['A','B','F'])).collect())
```
