### ISSUE TITLE
Wheels are added to releases with some delay, breaking `pip install`

### ISSUE THREAD

**Issue by Gattocrucco** [pola-rs/polars#10201]
As mentioned before in #1421, #6970, #8873, sometimes polars does not `pip install` right away because a release has been issued without attaching the binary wheels, the missing wheel triggers a source compilation, and the environment is not set up to support such compilation.

For example, in polars 0.18.10, the delay between the source release and the macOS binary release [is 20 min](https://pypi.org/project/polars/0.18.10/#files):

<img width="561" alt="image" src="https://github.com/pola-rs/polars/assets/9684110/2bf6e77a-3942-4ef7-bd91-3aa14496f13c">

I adopted polars for a library in Jan 2023, and this popped up two times making the CI fail. Right now I'm going to find a way to circumvent the issue (maybe pip has an option to require a version with binary wheels?), but it never happened to me with other libraries, so I guess it is common practice to make the release only when all files are ready.

**Comment by stinodego** [comment]
I am in favor of updating our CI to first build all the wheels, and only then publish to PyPI. That will solve your issue.

**Comment by stevenlis** [comment]
@stinodego Any reason why conda-forge is not officially maintained?
https://anaconda.org/conda-forge/polars

**Comment by ritchie46** [comment]
What do you mean with officially?

**Comment by stevenlis** [comment]
@ritchie46 Someone told me on Discord that it's not maintained by you or @stinodego. Maybe they are wrong? I use conda to manage my envs and usually have to wait for a while to update polars from conda-forge's end. There is usually a delay, sometimes up to one or two days, compared to PyPI.

**Comment by stinodego** [comment]
We cannot publish to conda-forge in our CI pipelines. There is a delay due to the conda-forge release process that we do not control ourselves.

For any further discussion on our conda-forge releases, please open a separate issue.

**Comment by owenprough-sift** [comment]
It's beautiful: https://github.com/pola-rs/polars/actions/runs/6356128493
