### ISSUE TITLE
Filter operation doesn't propagate null values

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#10204]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "w": [1,2,3],
    "f": [0,1,None],
})
print(df.filter(pl.col("f") != 0))

shape: (1, 2)
┌─────┬─────┐
│ w   ┆ f   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 1   │
└─────┴─────┘
```

### Issue description

Filter operation throws out all nulls. 

### Expected behavior

Same output as
```python
print(df.filter((pl.col("f") != 0) | pl.col("f").is_null()))

shape: (2, 2)
┌─────┬──────┐
│ w   ┆ f    │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 2   ┆ 1    │
│ 3   ┆ null │
└─────┴──────┘

```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.10
Index type:          UInt32
Platform:            Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python:              3.10.6 (main, Feb 10 2023, 10:36:46) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.24.2
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            2.0.2
sqlalchemy:          2.0.17
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by avimallu** [comment]
This is expected behavior - the `null` *is* propagated here per the second series (`null != 0` gives `null`). See https://github.com/pola-rs/polars/issues/9329 for a long discussion on a similar case. Long story short, use `.eq_missing` when you want this behavior. 

Also related https://github.com/pola-rs/polars/issues/10024.

**Comment by LdRoW** [comment]
Thanks a lot, will use specialized methods.
