### ISSUE TITLE
Apply inefficient warning : issue with if / else

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#10210]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
    "rank": [1, 2, 3]
})

df.with_columns(
    pl.col("rank").apply(lambda x: "first" if x==1 else "not first")
)
```

### Issue description

The recommendation from the engine is:
In this case, you can replace your `apply` with the following:
  - pl.col("rank").apply(lambda x: ...)
  + (pl.col("rank") == 1) & 'first'

Which does not reproduce the same processing as the lambda function

### Expected behavior

Correct Polars expression recommendation, using when  / then.

Apart from this small thing, it's a great functionality! outstanding job to the team

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.10
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              2.0.1
pyarrow:             11.0.0
pydantic:            1.10.6
sqlalchemy:          1.4.47
xlsx2csv:            0.8.1
xlsxwriter:          3.1.0
```

</details>

**Comment by stinodego** [comment]
I cannot reproduce this. I do not get a warning (master branch).

**Comment by MarcoGorelli** [comment]
Can reproduce

```python
In [1]: df = pl.DataFrame({
   ...:     "rank": [1, 2, 3]
   ...: })
   ...:
   ...: df.with_columns(
   ...:     pl.col("rank").apply(lambda x: "first" if x==1 else "not first")
   ...: )
<ipython-input-1-a8a16ebd6519>:6: PolarsInefficientApplyWarning:
Expr.apply is significantly slower than the native expressions API.
Only use if you absolutely CANNOT implement your logic otherwise.
In this case, you can replace your `apply` with the following:
  -  pl.col("rank").apply(lambda x: ...)
  +  (pl.col("rank") == 1) & 'first'

  pl.col("rank").apply(lambda x: "first" if x==1 else "not first")
```

Thanks for the report, definitely looks like a bug - we shouldn't (intentionally) be suggesting replacements for `if/then` statements

**Comment by cjackal** [comment]
I can reproduce w/ pypi `polars==0.18.10` (linux, if os depends)

**Comment by MarcoGorelli** [comment]
cc @alexander-beedie (just FYI - will take a closer look later)

**Comment by stinodego** [comment]
Weird that I don't get the warning. Maybe my Python version (3.11.2)? In any case, as long as Marco can reproduce it we're good 👍

**Comment by alexander-beedie** [comment]
Interesting; I haven't done if/else support yet... must be a rogue opcode 🤔
