### ISSUE TITLE
groupby/agg returns incorrect results with comm_subexpr_elim

### ISSUE THREAD

**Issue by knowecho** [pola-rs/polars#10215]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
print(
    pl.DataFrame({
        'a': [1, 2, 3],
        'b': [1, 1, 1],
    })
    .lazy()
    .groupby(
        'a',
    )
    .agg(
        (pl.col('a').sum() * pl.col('a').sum()).alias('x'),
        (pl.col('b').sum() * pl.col('b').sum()).alias('y'),
    )
    .collect()
)
```

Incorrect output:
```
shape: (3, 3)
┌─────┬───────────┬─────┐
│ a   ┆ x         ┆ y   │
│ --- ┆ ---       ┆ --- │
│ i64 ┆ list[i64] ┆ i64 │
╞═════╪═══════════╪═════╡
│ 1   ┆ [36]      ┆ 1   │
│ 3   ┆ [36]      ┆ 1   │
│ 2   ┆ [36]      ┆ 1   │
└─────┴───────────┴─────┘
```

### Issue description

Column `x` has type `list[f64]`, but it should have type `f64`.
It seems column `x` is repeating a value once for each row in the group. (e.g. if you make `a` have 2 unique values then you will get lists of length 1 instead of length 2.) This value is incorrect too.
Column `y` has the correct value.

The optimized plan (from explain) shows it is incorrectly moving the calculation of column `x` out of the groupby:
```
AGGREGATE
	[col("__POLARS_CSER_binary: *!sum!sum").alias("x"), [(col("b").sum()) * (col("b").sum())].alias("y")] BY [col("a")] FROM
   WITH_COLUMNS:
   [[(col("a").sum()) * (col("a").sum())].alias("__POLARS_CSER_binary: *!sum!sum")]
    DF ["a", "b"]; PROJECT 2/2 COLUMNS; SELECTION: "None"
```

Setting `comm_subexpr_elim=False` in the call to `collect` gives the correct output.
Downgrading to version 0.18.8 gives the correct output. Output is correct in 0.18.8 and 0.18.9.

Removing the expression for column `y` from the call to `agg` causes column `x` to have the correct value.
Changing one of the `/` to `*` gives the correct output, but changing both to `*` gives the wrong output.
Changing one of the `sum` to `mean` gives the correct output, but changing all 4 to `mean` gives the wrong output.
Removing the `lazy` and `collect` gives the correct output.

### Expected behavior

```
shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ x   ┆ y   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 3   ┆ 9   ┆ 1   │
│ 2   ┆ 4   ┆ 1   │
│ 1   ┆ 1   ┆ 1   │
└─────┴─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.10
Index type:          UInt32
Platform:            Linux-5.10.154-1.base.x86_64-x86_64-with-glibc2.10
Python:              3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) 
[GCC 10.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.19
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks for the report. I know what the issue is. Shall fix and patch.
