### ISSUE TITLE
`PanicException` for `str.to_date` & `str.to_datetime` with `strict=False`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10223]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series(
    name='date',
    values=['2019-01-01', 'ab'], # <<< PanicException
    # values=['2019-01-01', 'a'], # <<< This does NOT Panic
).str.to_date(exact=False)

pl.Series(
    name='datetime',
    values=['2019-01-01 00:00:00', 'ab'], # <<< PanicException
    # values=['2019-01-01 00:00:00', 'a'], # <<< This does NOT Panic
).str.to_datetime(exact=False)
```

### Issue description

`str.to_date` & `str.to_datetime` panic when `strict=False` and text cannot be parsed and has length of >1 it seems

### Expected behavior

normal `ComputeError` with conversion/parsing failed message

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-12.6.1-x86_64-i386-64bit
Python:              3.11.4 (main, Jul 25 2023, 17:08:27) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

> # values=['2019-01-01', 'a'], # <<< This does NOT Panic

doesn't it? it does for me
```python
In [1]: pl.Series(
   ...:     name='date',
   ...:     values=['2019-01-01', 'a'],
   ...: ).str.to_date(exact=False)
---------------------------------------------------------------------------

ComputeError: strict conversion to dates failed.

You might want to try:
- setting `strict=False`
- explicitly specifying a `format`

```

**Comment by MarcoGorelli** [comment]
@JulianCologne just for my understanding, what's your use-case for `exact=False`? It's a performance foot-gun, I'd expect it to always be much more performant to clean your data beforehand

**Comment by JulianCologne** [comment]
@MarcoGorelli thanks for asking

I have acually zero use for `exact=False` 

Came across the bug by accident because I was working on a PR to improve error messages for `to_date`, `to_datetime` and `to_time` and wanted to check with different inputs that nothing unexpected happens :D
