### ISSUE TITLE
Panick in apply call, still produces correct result

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10237]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3]})

result = df.select(pl.all().apply(lambda x: x > 50))
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("wildcard has no root column name"))', /home/stijn/code/polars/crates/polars-plan/src/utils.rs:207:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
shape: (3, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ false │
│ false │
└───────┘
```
Replacing `pl.all()` with `pl.col("a")` will not result in the error message.

### Issue description

See above. Somehow using the wildcard triggers an error message here.

### Expected behavior

No panic error message.

### Installed versions

master

**Comment by jhanley634** [comment]
My python 3.11.4 / polars 0.18.7 does not reproduce this error.

However, when I ask pip to upgrade to 0.18.8, I _do_ see the same error. The source line in that version was: `polars/polars-lazy/polars-plan/src/utils.rs:202:47`

**Comment by ritchie46** [comment]
The expression itself produces the error:

```
pl.all().apply(lambda x: x > 50)
```

**Comment by ritchie46** [comment]
It does a try except to catch the panic, which is a bug. We should not handle panics as if they are errors.
