### ISSUE TITLE
DataFrame.groupBy().agg_mean() produce unexpected result if agg_col has more than one chunks.

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10242]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
#[test]
fn test_agg_mean() -> PolarsResult<()> {
    let series_a = Series::new("a", &[1, 1, 2, 2]);
    let mut series_b = Series::new("b", &[3.0, 3.0]);
    series_b.append(&Series::new("c", &[4.0, 4.0]));
    let df = DataFrame::new(vec![series_a, series_b])?;
    let mean = df.groupby(["a"])?.mean();
    dbg!(&mean?);
    Ok(())
}
```

![image](https://github.com/pola-rs/polars/assets/19502505/13c965bb-801c-4f87-bf5c-c0ca821dc3c7)

### Issue description

After #8294, we uses the first chunkedArray to call `take_agg_no_null_primitive_iter_unchecked` or `take_agg_primitive_iter_unchecked_count_nulls`. If this series has more than one chunks, the result will be UB.

### Expected behavior

![image](https://github.com/pola-rs/polars/assets/19502505/d44079a6-f956-4856-ba67-ff2af57064d8)

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by reswqa** [comment]
I tried to fix this issue locally and the results met expectations. If this bug is effective, I am willing to submit a PR.

**Comment by ritchie46** [comment]
We actually should rechunk. The `groupby(..).mean` is something I want to remove and I only want this logic to be accessible via the lazy API. This API ensures the chunks are properly handled. 

In the mean time we could add a `as_single_chunk_par` call, just before we call `agg_mean`.

**Comment by reswqa** [comment]
Thanks for the quick reply! 

> We actually should rechunk.

Yes, actually we have already call `self.rechunk` in `agg_mean`, but somehow we didn't use it.

I have open a pull request to fix this, but I am not familiar with this codebase, so any comments are welcome.
