### ISSUE TITLE
The pandas Series.mode() equivalent.

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [pola-rs/polars#1025]
Is there any equivalent to `pandas.Series.mode`?
https://pandas.pydata.org/docs/reference/api/pandas.Series.mode.html

I am doing something like the following  with lambda function which is not ideal for threading purposes.
```python
import polars as pl
import numpy as np
data_df = pl.read_csv('data_file.csv')
m_df = data_df.groupby(['col1', 'col2']).agg([pl.col('col3').apply(lambda x: np.bincount(x).argmax())]) 
```
Which can be replaced by
```python
m_df = data_df.groupby(['col1', 'col2']).agg([pl.col('col3').mode()]) 
```

**Comment by ritchie46** [comment]
Added and released. :+1:
