### ISSUE TITLE
join_asof does not accept a Null on the "by" column

### ISSUE THREAD

**Issue by guillempalou** [pola-rs/polars#10264]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({
    "time": pl.date_range(date(2018,1,1), date(2018,1,8), eager=True),
    "group": [1,1,1,1,2,2,2,2],
    "value": [0,0,None,None,2,None,1,None]
})
df.join_asof(df, on="time", by="value")
```

### Issue description

The above snippet fails with a non-informative rust panic error. Stacktrace is as follows
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("chunked array is not contiguous"))', /Users/runner/work/polars/polars/crates/polars-core/src/frame/asof_join/groups.rs:299:35
...
PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("chunked array is not contiguous"))
```
 I'm not sure whether it is intended behavior, but 
```
df.join(df,by="value")
```
works and outputs the correct dataframe.

### Expected behavior

`join_asof` returns a valid dataframe or fails with a more informative error.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-11.6.6-x86_64-i386-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment]
`join_asof` doesn't allow for nulls in the join column, but the `by` column is just a regular join, meaining we should definitely support that.

@ritchie46 I'm not sure how to fix this, but the issue is [here](https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/asof_join/groups.rs#L297-L304). `cont_slice()` fails because there are multiple chunks (is this always the case with null-containing series? I tried a `rechunk()` and it didn't work).

**Comment by ritchie46** [comment]
`cont_slice` gives you a slice if there are no nulls. Give that there are nulls, it fails.

**Comment by zundertj** [comment]
Is the intention to fix this (not sure I can do this myself), or should we document that nulls on the `on` and `by` columns are never allowed? It seems particularly inconvenient if there are nulls in the `by` column in the left dataframe, if you want to keep those entries like in a regular join, you would need to filter out those rows pre the join_asof, and concat back after? The right dataframe is not much of an issue, other than having to filter out nulls.

**Comment by coastalwhite** [comment]
I am unable to reproduce this issue with the following code.

```python
import polars as pl
from datetime import date

df = pl.DataFrame({
    "time": pl.date_range(date(2018,1,1), date(2018,1,8), eager=True),
    "group": [1,1,1,1,2,2,2,2],
    "value": [0,0,None,None,2,None,1,None]
})

print(df.join_asof(df, on="time", by="value"))
```

Instead, I get the following output.

```
shape: (8, 4)
┌────────────┬───────┬───────┬─────────────┐
│ time       ┆ group ┆ value ┆ group_right │
│ ---        ┆ ---   ┆ ---   ┆ ---         │
│ date       ┆ i64   ┆ i64   ┆ i64         │
╞════════════╪═══════╪═══════╪═════════════╡
│ 2018-01-01 ┆ 1     ┆ 0     ┆ 1           │
│ 2018-01-02 ┆ 1     ┆ 0     ┆ 1           │
│ 2018-01-03 ┆ 1     ┆ null  ┆ null        │
│ 2018-01-04 ┆ 1     ┆ null  ┆ null        │
│ 2018-01-05 ┆ 2     ┆ 2     ┆ 2           │
│ 2018-01-06 ┆ 2     ┆ null  ┆ null        │
│ 2018-01-07 ┆ 2     ┆ 1     ┆ 2           │
│ 2018-01-08 ┆ 2     ┆ null  ┆ null        │
└────────────┴───────┴───────┴─────────────┘
```
