### ISSUE TITLE
Inconsistency for elementwise comparison for eager vs lazy modes

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#10274]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [103]: df1 = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]})

In [104]: df2 = pl.DataFrame({'a': [1,2,3], 'b': [4,5,7]})

In [105]: df1 == df2
Out[105]:
shape: (3, 2)
┌──────┬───────┐
│ a    ┆ b     │
│ ---  ┆ ---   │
│ bool ┆ bool  │
╞══════╪═══════╡
│ true ┆ true  │
│ true ┆ true  │
│ true ┆ false │
└──────┴───────┘

In [106]: df1.lazy() == df2.lazy()
Out[106]: False
```

### Issue description

`LazyFrame.__eq__` isn't implemented, so it just falls back to the default Python object `__eq__`, which returns something different than it does for `DataFrame.__eq__`

### Expected behavior

Is it possible to do element-wise comparisons for `LazyFrame`s, like it is for `DataFrame`s?

If not, it might be a better experience to raise `NotImplementedError` on `LazyFrame.__eq__`?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            2.0.2
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Lazyframe don't have a formalized shape. I don't think they should support this.

**Comment by mcrumiller** [comment]
@ritchie46 they do once they're collected. I think it makes sense to have an `==` operator that `collect` can be called on.

**Comment by ritchie46** [comment]
They would need to block predicate and slice pushdown. I don't want that complexity in the query optimizer. Data should be joined first before it can be compared

**Comment by alexander-beedie** [comment]
> If not, it might be a better experience to raise `NotImplementedError` on `LazyFrame.__eq__`?

Looking at the relevant [CPython source](https://github.com/python/cpython/blob/d2340ef25721b6a72d45d4508c672c4be38c67d3/Objects/object.c#L700), I believe the correct exception is `TypeError` ;)
And I agree, we should raise one for all of the LazyFrame equality/comparison dunder methods 👍

**Comment by MarcoGorelli** [comment]
> Looking at the relevant [CPython source](https://github.com/python/cpython/blob/d2340ef25721b6a72d45d4508c672c4be38c67d3/Objects/object.c#L700), I believe the correct exception is TypeError :)

right - thanks, Alex "Python Wizard" Beedie!

@mcrumiller do you want to repurpose your PR to raise `TypeError`?

**Comment by mcrumiller** [comment]
> @mcrumiller do you want to repurpose your PR to raise TypeError?

Sure thing! Give me a little while, still official "at work"...

**Comment by mcrumiller** [comment]
@MarcoGorelli should be good to go now. Fairly simple PR.
