### ISSUE TITLE
LazyFrame + apply + collect(streaming) results in an exception

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#10288]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import json

import polars as pl


df = pl.LazyFrame({"map": [{"a": "b"}]})
df2 = df.select(pl.col('map').apply(json.dumps))

print(df2.collect())
# ┌────────────┐
# │ map        │
# │ ---        │
# │ str        │
# ╞════════════╡
# │ {"a": "b"} │
# └────────────┘
print(df2.collect(streaming=True))
# exceptions.ComputeError: ComputeError: The output type of 'apply' function cannot determined.
# The function was never called because 'skip_nulls=True' and all values are null.
# Consider setting 'skip_nulls=False' or setting the 'return_dtype'.
```

### Issue description

Creating a polars `LazyFrame`, applying a method on it and collecting it works fine.
However, when you collect that same dataframe in streaming mode results in an vague error message.

(setting the `return_dtype=pl.Utf8` on the apply-method made it work in both cases)

### Expected behavior

I would expect that both should work as-is.

Alternatively / Additionally I would also suggest an improvement on the error message to clarify that the `skip_nulls` and `return_dtype` needs to be set on the apply-method (I was looking into the collect message because that's where the error happened).

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

Process finished with exit code 0
```

</details>

**Comment by ritchie46** [comment]
As the docstring states:

**Comment by svaningelgem** [comment]
Thanks for the clarification. Maybe then my "bug" becomes more like an improvement request for the thrown error.

**Comment by svaningelgem** [comment]
Yes, but because you're busy with a lazy dataframe the error only appears on the `collect`. So you need to go find in which method in your chain this should be added. Hence my suggestion.
I'll leave it up to your expertise to decide.

I was just pondering about this: `We allow this, but it is considered a bug in the user's query.`: why not make it an error in both ways? Because now it's inconsistent and at first glance looks like a streaming bug. However, it's a user error. In such a case I prefer to always get an error.
Just saying 😁

**Comment by ritchie46** [comment]
Yes, we might make that more strict one day. I understand your sentiment.

**Comment by mcrumiller** [comment]
@ritchie46 any reason to keep `return_dtype` optional? I vote a warning that in the future it'll be mandatory. Should simplify some of the code too having it mandatory.

**Comment by orlp** [comment]
I would be in favor making `return_dtype` mandatory on `apply`. I will close this issue and make a new issue dedicated to the discussion of making it mandatory.

**Comment by cmdlineluser** [comment]
Does anybody know what would be needed to implement `.apply(json.dumps)` natively?

The `loads` equivalent uses:
https://github.com/pola-rs/polars/blob/bfabdd50639b271da45027809cf720771e3c6685/crates/polars-ops/src/chunked_array/strings/json_path.rs#L81

Does this mean if `polars_json::ndjson::serialize` existed, we could go the other way?

**Comment by odedroze** [comment]
so how can I solve it, can someone add a code script please ?

**Comment by cmdlineluser** [comment]
@odedroze It depends on what your UDF returns.

In the example given here, it `json.dumps` returns `str` (i.e. `pl.Utf8`) - so you just tell Polars that via `return_dtype=`

```python
>>> df.select(pl.col('map').map_elements(json.dumps, return_dtype=pl.Utf8)).collect(streaming=True)
shape: (1, 1)
┌────────────┐
│ map        │
│ ---        │
│ str        │
╞════════════╡
│ {"a": "b"} │
└────────────┘
```
