### ISSUE TITLE
Delineate the company and the project

### ISSUE THREAD

**Issue by magarick** [pola-rs/polars#10285]
The recent funding announcement means more resources will be available to improve Polars. This is great. Unfortunately it also risks creating the appearance of a conflict of interest, even if unintentional.

If the project, while still open source, is essentially "owned" by the company, it raises the risk of prioritizing the company's needs at the expense of the project. People may also be concerned that the company could change its mind about open source one day. Now, I'm not saying, or even suspecting that any of this will happen, but I think it's better to be as clear as possible from the outset. DuckDB, for instance, has a nice model where there are actually three entities, including a nonprofit foundation that holds most of the rights to the underlying technology. Something similar would boost the community's confidence, ensure that governance isn't dominated by an entity with no accountability to contributors and users, help align incentives between the company and community, and encourage more contributions and even other sources of development funds .

To reiterate, I currently have no reason to fear, but you can never be too careful. Ideally, this comment would go on a discussion page but I don't see one. I guess it's issue-related in that something discussing this could be written and put in the repo, at the very least to reassure people. Once again, congratulations and I hope this is the start of something even greater than what you've already built.

**Comment by mcrumiller** [comment]
I missed the funding memo, can someone link?

**Comment by orlp** [comment]
@mcrumiller https://www.pola.rs/posts/company-announcement/

**Comment by magarick** [comment]
FWIW, there are grants to support the development of such governing bodies for the open source part, like this one https://new.nsf.gov/funding/opportunities/pathways-enable-open-source-ecosystems-pose. I know it's US-based but I think only the proposer has to be in the US and they don't necessarily need to be the project's creator. It would be surprising if other countries didn't offer similar programs as well. Something like this could be very helpful to clearly define the open part of the project without taking up company resources.

**Comment by stinodego** [comment]
I will close this as there is no actionable items here.
