### ISSUE TITLE
pl.scan_pyarrow_dataset does not return partition key as column

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10296]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
```

```
import polars as pl
import pyarrow.dataset as ds

mytab = pl.scan_pyarrow_dataset(ds.dataset("my_table_name"))
mytab.filter(pl.col('CALENDAR_DATE') == '2023-08-01').limit(10).collect()

```
[my_table_name.zip](https://github.com/pola-rs/polars/files/12259738/my_table_name.zip)

I get the error:
ComputeError: ArrowInvalid: No match for FieldRef.Name(CALENDAR_DATE) in USER_ID: double
TRX_CNT: double

### Issue description

pl.scan_pyarrow_dataset() does not return the partition key as column, if reading partitioned parquet file (see attachment)

### Expected behavior

I should get back all 3 columns:
- calendar_date
- user_id
- trx_cnt

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-4.18.0-372.51.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:              3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.0.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.02.0
matplotlib:          3.7.2
numpy:               1.21.6
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          1.4.27
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2

```

</details>

**Comment by lucazanna** [comment]
Hi 

you can try adding to the following parameter when creating the pyarrow dataset:
partitioning='hive'

It works for me with this parameter

**Comment by lmocsi** [comment]
Could it be the default mode of operation?

**Comment by lucazanna** [comment]
I think that would be a question for pyarrow rather than Polars. However not all datasets are Hive partitioned, so the hive partitioning would not make sense in all cases 

All this said, an addition to the Polars guide about this could be a good addition

**Comment by orlp** [comment]
This is not a problem with polars, `pyarrow` simply ignores the folder names of your data (which hive partitioning uses) if you don't explicitly turn on the hive partition option. The data is simply not provided to Polars.

I will edit the API docs on `pl.scan_pyarrow_dataset` to give a brief mention about this pitfall.
