### ISSUE TITLE
Scan parquet with groups limit

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#10293]
### Problem description

For instance, we have a df saved as parquet:
type | version | value
-- | -- | --
str | u16 | u32
a | 1 | 10
a | 1 | 9
a | 1 | 12
a | 2 | 15
b | 3 | 20
a | 3 | 8
a | 2 | 11

When read from this file we may need to get all values for only 2 groups (type & version) and in this case we do not need to read whole df in memory.
E.g. ```pl.scan_parquet('path_to_file', limit_groups=(2, ['type', 'version']))```
type | version | value
-- | -- | --
str | u16 | u32
a | 1 | 10
a | 1 | 9
a | 1 | 12
a | 2 | 15
a | 2 | 11

For now, I was able to achieve it just doing the following:
```python
df_groups = df.select(['type', 'version']).unique().sample(n=2)
df.filter(
            pl.all([df[c].is_in(df_flow.sample(n=flow_limit)[c]) for c in flow_prep_gb_cols])
        )
```
or with inner join
```python
df.join(df_groups, on=['type', 'version'], how='inner')
```
Also, it may be useful to have a limit_groups method for dataframe/series.
Maybe related to #10291

**Comment by orlp** [comment]
This optimization should not be a user-facing option, and should automatically be handled by the query engine. Polars already does quite a few optimizations like this so we'd need to see if it's not already handled and what's needed to make it so.

**Comment by orlp** [comment]
Thinking about it some more, this optimization also doesn't really make much sense in full generality. There is no guarantee that parquet stores your data grouped in the same way as your query asks for. Either way this is not something we wish to explicitly support by user directive, this will be part of further query engine optimization under-the-hood.

**Comment by s-b90** [comment]
@orlp Thanks for answer.  I think it definitely will make sense in combination with #10291
For instance, if we need only 1st value for each group, and we need only 2 groups.

type | version | value
-- | -- | --
str | u16 | u32
a | 1 | 10
a | 1 | 9
a | 1 | 12
a | 2 | 15
b | 3 | 20
a | 3 | 8
a | 2 | 11

In this case, the result should be:
type | version | value
-- | -- | --
str | u16 | u32
a | 1 | 10
a | 2 | 15

And it can be achieved not reading whole parquet till the end.

But in general, the question was regarding memory usage, not only the speed performance.
If the scan engine will be able to skip rows ```b | 3 ``` and ```a | 3 ``` because it already has 2 groups ```a | 1 ``` and ```a | 2``` I think it can reduce memory usage, doesn't it?

**Comment by s-b90** [comment]
> They just happen automatically by the query engine, not by the user suggesting to read less information explicitly.

Sure, it will be definitely much simpler.

Will wait for an update here. Thank you!

**Comment by s-b90** [comment]
Hi @orlp, one more question here. I understood that optimization behavior for scan_parquet should be under the hood.
But would it be appropriate maybe to create DataFrame/LazyFrame method `limit_by` for such tasks when dataframe already loaded?
I totally understand that we can achieve this results by using existing API. For example, take just the first element in groups and limit groups number to 2.
```python
df_unique_groups = df.select(['type', 'version']).unique().sample(n=2)
df = df.join(
    df_unique_groups, on=['type', 'version'], how='inner'
).groupby(['type', 'version']).head(2)
```
But if we replace this with following, I think computations can be done more effective:
```python
df = df.limit_by(limit_per_group=1, group=['type', 'version'], n_groups=2)
```
In such case, we don't need to create intermediate dataframe df_unique_groups, make extra groupby etc. Pls correct me if I am wrong.
Can I create a feature request for this method?

**Comment by orlp** [comment]
@s-b90 I don't understand what exactly you wish to query. Now you've introduced a random sample?

As for the extra groupby, I don't know if we do it currently, but in princple that could be shared with the join under the hood.

**Comment by s-b90** [comment]
It is all about reducing. And limit_by is filtering by group.
```python
df = pl.DataFrame([
    {'brand': 'volvo', 'model': 'XC60', 'cnt': 10},
    {'brand': 'volvo', 'model': 'XC60', 'cnt': 9},
    {'brand': 'volvo', 'model': 'XC60', 'cnt': 12},
    {'brand': 'volvo', 'model': 'XC90', 'cnt': 15},
    {'brand': 'nissan', 'model': 'Frontier', 'cnt': 20},
    {'brand': 'volvo', 'model': 'V90', 'cnt': 8},
    {'brand': 'volvo', 'model': 'XC90', 'cnt': 11},
    {'brand': 'nissan', 'model': 'Frontier', 'cnt': 15},
    {'brand': 'nissan', 'model': 'Armada', 'cnt': 5},
])
```
My task is to get from df any 2 groups ['brand', 'model'] and their first value.
To achieve it, I'm doing the following:
1) Getting the first value from each group
```python
df.groupby(['brand', 'model']).head(1)
```

2) Get random 2 groups (is much complicated). It can not be chained in standard polars one line pipe. So:
    2.1) I should firstly generate unique values
    ```python
    df_uniq = df.select(['brand', 'model']).unique().limit(2)
    ```
    2.2) Then filter df by it 
    ```python 
    df.join(df_uniq, on=['brand', 'model'], how='inner')
    ```

If combine this:
```python
df_uniq = df.select(['brand', 'model']).unique().limit(2)
df = df.groupby(['brand', 'model']).head(1).join(
    df_uniq, on=['brand', 'model'], how='inner'
)
```

brand	| model |	cnt
-- | -- | --
str | str | u32
"nissan" |	"Frontier"	| 20
"volvo" | "XC90" |15

The minuses of this approach are:
1)  that we break single polars pipeline for calculating `unique` values. 
2) that we should do groupby 2 times. First to get unique values, the second is to get first element per group.

I think that it is possible to achieve it in more efficient way.
That is why I suggested implementing `limit_by` method. It is similar to Clickhouse  [LIMIT BY](https://clickhouse.com/docs/en/sql-reference/statements/select/limit-by) clause but with additional filter by number of group (n_groups parameter).
```python
df = df.limit_by(limit_per_group=1, group=['brand', 'model'], n_groups=2)
```

**Comment by orlp** [comment]
That's the beauty of Polars' lazy API, we don't need a dedicated `LIMIT BY n` option or syntax. That is exactly equivalent to `.groupby(...).agg(...).head(n)`. Polars doesn't work like Pandas or most other dataframe libraries that each operation happens exactly as you state it when you state it. We first compute the whole computation graph and then optimize it.

> My task is to get from df any 2 groups ['brand', 'model'] and their first value.

```python
>>> df.lazy().groupby(['brand', 'model']).agg(pl.col('cnt').first()).head(2).collect()
shape: (2, 3)
┌────────┬────────┬─────┐
│ brand  ┆ model  ┆ cnt │
│ ---    ┆ ---    ┆ --- │
│ str    ┆ str    ┆ i64 │
╞════════╪════════╪═════╡
│ volvo  ┆ XC90   ┆ 15  │
│ nissan ┆ Armada ┆ 5   │
└────────┴────────┴─────┘
```

**Comment by s-b90** [comment]
Ok, got you!
Thanks for example. Just want to add that oneliner for cases when we need not just first value could look like that (because group sizes can be smaller that `limit_per_group`):
```python
limit_per_group=2
groups_limit=3
df.lazy().groupby(['brand', 'model']).agg(
    pl.exclude('brand', 'model').head(limit_per_group)
).head(groups_limit).explode(pl.exclude('brand', 'model')).collect()
```
Will wait for graph optimizations in that scenario in the future. Thank you!
