### ISSUE TITLE
Concerning that != comparison between non-null and null is always false

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#10294]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({'x1':['A', 'B', None], 'x2':['A', None, 'C']})

# ┌──────┬──────┐
# │ x1   ┆ x2   │
# │ ---  ┆ ---  │
# │ str  ┆ str  │
# ╞══════╪══════╡
# │ A    ┆ A    │
# │ B    ┆ null │
# │ null ┆ C    │
# └──────┴──────┘

df.filter(pl.col('x1')!=pl.col('x2'))

# Expected
# ┌──────┬──────┐
# │ x1   ┆ x2   │
# │ ---  ┆ ---  │
# │ str  ┆ str  │
# ╞══════╪══════╡
# │ B    ┆ null │
# │ null ┆ C    │
# └──────┴──────┘
# Actual
# ┌─────┬─────┐
# │ x1  ┆ x2  │
# │ --- ┆ --- │
# │ str ┆ str │
# ╞═════╪═════╡
# └─────┴─────┘
```

### Issue description

At some point in the last few months `nulls` and `non-null values` began evaluating as false when compared via "not-equals" `!=` operator.

### Expected behavior

I expect `pl.lit('A') != None` to evaluate to `True`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.0
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2022.8.2
matplotlib:          3.7.2
numpy:               1.22.4
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            1.10.2
sqlalchemy:          1.4.44
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

**Comment by MarcoGorelli** [comment]
hey @mkleinbort-ic 

> nulls and non-null values began evaluating as false

isn't it that they evaluate as `null`, i.e. that the `null` propagates?

for reference, pandas does the same for nullable types
```python
In [6]: pd.Series([None], dtype='Int64[pyarrow]') != pd.Series([None], dtype='Int64[pyarrow]')
Out[6]:
0    <NA>
dtype: bool[pyarrow]
```

**Comment by mkleinbort-ic** [comment]
I see, I can accept that.

It does feel strange as per the code I shared... but I'll keep it in mind.

**Comment by avimallu** [comment]
Copy pasting for some context and alternatives from another post:

This is expected behavior as mentioned by @MarcoGorelli. See https://github.com/pola-rs/polars/issues/9329 for a long discussion on a similar case. Long story short, use `.eq_missing` when you want this behavior.

**Comment by mkleinbort-ic** [comment]
In my case the answer was 

```python
.filter(pl.col('x1').is_null() | pl.col('x2').is_null() # This is what I was aiming for
```

**Comment by spookytomtom** [comment]
Just leaving a comment here. This should be highlighted a bit more, it caused a bit of a headache for me as well coming from pandas. I did a course on Udemy and read Python Polars Definite Guide, but this missed me completely.

**Comment by cmdlineluser** [comment]
It is mentioned in the [`.filter()` docs](https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.filter.html) and there is an `.eq_missing()` example.

> If you are transitioning from Pandas, and performing filter operations based on the comparison of two or more columns, please note that in Polars any comparison involving null values will result in a null result, not boolean True or False.

[`.remove()`](https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.remove.html) also exists now which has different null semantics. 

```python
df.remove(pl.col.x1 == pl.col.x2)
# shape: (2, 2)
# ┌──────┬──────┐
# │ x1   ┆ x2   │
# │ ---  ┆ ---  │
# │ str  ┆ str  │
# ╞══════╪══════╡
# │ B    ┆ null │
# │ null ┆ C    │
# └──────┴──────┘
```

`remove` doesn't seem to be mentioned in the User Guide yet.
