### ISSUE TITLE
str.extract_groups wrong lazy dtype

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#10305]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.LazyFrame(
    data={
        "url": [
            "http://vote.com/ballon_dor?candidate=messi&ref=python",
            "http://vote.com/ballon_dor?candidate=weghorst&ref=polars",
            "http://vote.com/ballon_dor?error=404&ref=rust",
        ]
    }
)
pattern = r"candidate=(?<candidate>\w+)&ref=(?<ref>\w+)"
df = df.select(captures=pl.col("url").str.extract_groups(pattern)).unnest("captures")

assert df.schema == {"candidate": pl.Utf8, "ref": pl.Utf8}
```

### Issue description

Super cool that `str.extract_groups` finally made it in PR #10179!

However it's broken on lazy frames due to a incorrect return dtype.

In the example, the `unnest` crashes because `extract_groups` is returning the default `{'captures': pl.Utf8}` dtype.

```
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    assert df.schema == {"candidate": pl.Utf8, "ref": pl.Utf8}
           ^^^^^^^^^
  File "/usr/local/python/3.11.3/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 628, in schema
    return self._ldf.schema()
           ^^^^^^^^^^^^^^^^^^
exceptions.SchemaError: expected struct dtype, got: `str`
```

### Expected behavior

`df.schema` should be `{"candidate": pl.Utf8, "ref": pl.Utf8}`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            Linux-5.15.0-1042-azure-x86_64-with-glibc2.31
Python:              3.11.3 (main, Apr 14 2023, 19:54:24) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
@cmdlineluser can you take this one?

**Comment by cmdlineluser** [comment]
Checking now @ritchie46

**Comment by cmdlineluser** [comment]
Hm, so without calling `.unnest()` and just collecting, the correct schema is there:
```python
df.select(captures=pl.col("url").str.extract_groups(pattern)).collect().schema
# {'captures': Struct([Field('candidate', Utf8), Field('ref', Utf8)])}
```
```rust
[/Users/user/git/polars/crates/polars-ops/src/chunked_array/strings/extract.rs:42] data_type.clone() = Struct(
    [
        Field {
            name: "candidate",
            data_type: LargeUtf8,
            is_nullable: true,
            metadata: {},
        },
        Field {
            name: "ref",
            data_type: LargeUtf8,
            is_nullable: true,
            metadata: {},
        },
    ],
)
```

**Comment by cmdlineluser** [comment]
I think this is the problem?
https://github.com/pola-rs/polars/blob/bfabdd50639b271da45027809cf720771e3c6685/crates/polars-plan/src/dsl/function_expr/strings.rs#L98

The other `.str` function I know that returns a struct is `str.splitn` which lives elsewhere:

https://github.com/pola-rs/polars/blob/bfabdd50639b271da45027809cf720771e3c6685/crates/polars-plan/src/dsl/string.rs#L347

I'm guessing this is what generates the "dynamic schema"

https://github.com/pola-rs/polars/blob/bfabdd50639b271da45027809cf720771e3c6685/crates/polars-plan/src/dsl/string.rs#L387

Does this mean if something returns a struct it cannot live inside `/function_expr/`?

**Comment by ritchie46** [comment]
It should not generate the same dtype, but a struct type with fields based on the pattern.
