### ISSUE TITLE
Replace unmaintained wasm-timer dependency

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#10314]
### Problem description

in https://github.com/pola-rs/polars/blob/main/crates/polars-core/Cargo.toml

see https://github.com/tomaka/wasm-timer/issues/21#issuecomment-1380544611

**Comment by orlp** [comment]
We only use the crate in one place as far as I can see, to choose a unique ID for the categorical string cache.

**Comment by jqnatividad** [comment]
Nice!  Removed a lot of unneeded dependencies too!
