### ISSUE TITLE
Add more numpy functions to "Inefficient apply" warnings

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#10311]
### Problem description

At the time or writing, as per [here](https://github.com/pola-rs/polars/blob/main/py-polars/polars/utils/udfs.py#L91), it looks like polars maps the following numpy functions to polars expression methods. 
"cbrt", "cos", "cosh", "sin", "sinh", "sqrt", "tan", "tanh" 

This request is to add more functions to that mapping. A few examples (but by no means exhaustive) of potential additions are `abs`, `sign`, `log10`, `degrees`.

Be mindful of the note [here](https://github.com/pola-rs/polars/pull/10003#issue-1814440929)
> Note that I have only whitelisted a handful of numpy functions to start with; it's trivial to add more (literally just add the function name to the whitelist), but each one needs verification that we are indeed doing exactly the same thing in the default case - I'll whitelist additional functions as I confirm this.

One example where the default is not the same is `std`.

It would probably be prudent to validate each individual function with a test to ensure consistency between the two now and over time.

For a more exhaustive list of functions, a good starting point would be comparing parameterless polars expression methods to [the numpy docs](https://numpy.org/doc/stable/reference/routines.math.html).  I'll get a list started.

**Comment by alexander-beedie** [comment]
> It would probably be prudent to validate each individual function with a test to ensure consistency between the two now and over time.

Agreed 😎

**Comment by MarcoGorelli** [comment]
thanks for the request! agree

regarding tests - we're already explicitly checking the outputs here:

https://github.com/pola-rs/polars/blob/2d5511be3963448f4dde42b01470f1fa0c258302/py-polars/tests/unit/operations/test_inefficient_apply.py#L51-L66

where we compare:
- the result using `apply`
- the result using the expression

so as long as these extra functions are added to

https://github.com/pola-rs/polars/blob/82c168504a61c9e5bac877ebae5f4ecb892fb986/py-polars/tests/test_udfs.py#L27

then it should be fine

**Comment by MarcoGorelli** [comment]
Btw, interested in making a PR @henryharbeck ? Happy to help out if so

**Comment by henryharbeck** [comment]
Thanks for the pointers @MarcoGorelli, much appreciated!
Yes, I think that'd be great. It looks to be a good first issue. 

Will be my first open source contribution, so will reach out if I need any assistance. Thanks in advance for offering

I'll get a draft PR in over the next few days

**Comment by brunerm99** [comment]
@henryharbeck @MarcoGorelli Hey! Is this still being worked on? Thought I'd give it a try as a first contribution if not. I've been doing some testing and it doesn't seem too bad. 

Also, do y'all think the current test `DataFrame` in https://github.com/pola-rs/polars/blob/2d5511be3963448f4dde42b01470f1fa0c258302/py-polars/tests/unit/operations/test_inefficient_apply.py#L40 is sufficient? It seems like some of the operations could benefit from being tested a little further, for example:
- Testing the trigonometric functions within a range of $-2\pi \rightarrow 2\pi$ or a little outside. Currently only tests `[1, 2, 3]`.
- Adding some negative numbers in the mix which could be helpful for functions like `np.abs`. 

I wrote a little snippet below to generate a test `DataFrame` which would cover some of these. The random characters in `b` may be bad practice for a test, not sure. 

```python
import string, random  # only listing additional imports
from datetime import date

nrows = 10
df = pl.DataFrame(
    {
        "a": np.arange(nrows),
        "b": [
            f"{random.choice(string.ascii_letters)}{random.choice(string.ascii_letters)}"
            for _ in range(nrows)
        ],
        "c": [
            f'{{"{letter}": {index}}}'
            for index, letter in enumerate(string.ascii_letters, start=1)
        ][:nrows],
        "d": pl.date_range(date(2023, 1, 1), date(2023, 10, 1), "1d", eager=True)[
            :nrows
        ],
        "e": np.linspace(-2 * np.pi, 2 * np.pi, nrows),
    }
)

# Example df:
┌─────┬─────┬───────────┬────────────┬───────────┐
│ a   ┆ b   ┆ c         ┆ d          ┆ e         │
│ --- ┆ --- ┆ ---       ┆ ---        ┆ ---       │
│ i64 ┆ str ┆ str       ┆ date       ┆ f64       │
╞═════╪═════╪═══════════╪════════════╪═══════════╡
│ 0   ┆ Km  ┆ {"a": 1}  ┆ 2020-01-01 ┆ -6.283185 │
│ 1   ┆ hd  ┆ {"b": 2}  ┆ 2020-01-02 ┆ -4.886922 │
│ 2   ┆ zy  ┆ {"c": 3}  ┆ 2020-01-03 ┆ -3.490659 │
│ 3   ┆ HK  ┆ {"d": 4}  ┆ 2020-01-04 ┆ -2.094395 │
│ …   ┆ …   ┆ …         ┆ …          ┆ …         │
│ 6   ┆ Fi  ┆ {"g": 7}  ┆ 2020-01-07 ┆ 2.094395  │
│ 7   ┆ km  ┆ {"h": 8}  ┆ 2020-01-08 ┆ 3.490659  │
│ 8   ┆ af  ┆ {"i": 9}  ┆ 2020-01-09 ┆ 4.886922  │
│ 9   ┆ nM  ┆ {"j": 10} ┆ 2020-01-10 ┆ 6.283185  │
└─────┴─────┴───────────┴────────────┴───────────┘
```



This could all be overkill, just thought it was worth considering.

**Comment by MarcoGorelli** [comment]
the testing there is just to check that the suggestion is right - correctness of the trigonometric functions should be done elsewhere. I'd just keeping the existing testing strategy here

please do go ahead and submit a PR if this interests you, would be great to expand the list of numpy functions
