### ISSUE TITLE
Big overhead cause slow performance Series.pow for small and medium(~5k rows) dataset

### ISSUE THREAD

**Issue by aploium** [pola-rs/polars#10316]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import random
s_sample=pl.Series([random.random()*2 for _ in range(42)], dtype=pl.Float32)

# case: direct pow for polars is quite slow, 28.2μs is too long for just 42 elements
%%timeit
s_sample**1.5
# 28.2 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

# it's even way faster to do this if we convert it to numpy first
%%timeit
s_sample.to_numpy()**1.5
# 4.2 µs ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

# and even faster than native if we convert back from numpy :)
%%timeit
pl.Series(s_sample.to_numpy()**1.5)
# 7.25 µs ± 9.19 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

# it's strange, both polars and numpy are slower than pure python
py_list=s_sample.to_list()
%%timeit
new=[x**1.5 for x in py_list]
# 1.07 µs ± 3.59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

Update: after test bigger Series size, I guess polars may consume too many time in somewhere other than the pow compute itself
```python
s_1k=pl.Series([random.random()*2 for _ in range(1000)], dtype=pl.Float32)

%%timeit
s_1k**1.5
# 31.8 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
# compared to 28.2μs for an array of 42 element, 1000 element only gets 2μs more.

# however, at 1k element size, the overhead makes it still better to compute in numpy
%%timeit
s_1k.to_numpy()**1.5
# 8.81 µs ± 6.26 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

```

### Issue description

Series.pow may have big overhead, cause it performance slow for small and medium(<5k rows) dataset.

In practice, I think <5k rows should be a big usage, which cause the overhead becomes uneconomical.

In my case, my dataset that need pow operation(in a performance critical place) is about 10~100rows, well, I may need convert them to pure python and back. LoL

### Expected behavior

the pow operation should be faster, or at least same speed as of numpy

### Installed versions

<details>

--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            Linux-6.2.1-060201-generic-x86_64-with-glibc2.35
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.0
pydantic:            1.10.2
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

</details>

**Comment by ritchie46** [comment]
It runs an expression simplification and type coercion optimization. In this case it doesn't do much. But in other cases it does. 

How much of your runtime did our pow latency occupy?

**Comment by aploium** [comment]
> It runs an expression simplification and type coercion optimization. In this case it doesn't do much. But in other cases it does.
> 
> How much of your runtime did our pow latency occupy?

about 10%, if pow cost 28.2μs


However, after I continue refactor my code (from pandas to polars), I found polars have overhead in many places, not only the pow().  
Heres are my (almost) full code snippet in production.

```python
import polars as pl
import random
df_sample=pl.DataFrame({
    "a":[random.random()*2 for _ in range(42)],
    "b":[random.randint(1,12) for _ in range(42)]
})

#  polars compute logic
%%timeit
df_sample.lazy().with_columns(
    weight_a=pl.col("a")**1.5,
    weight_b=1 / (pl.col('b') + 10),
).with_columns(
    weight_sum=(pl.col("weight_a") / (pl.col("weight_a") + 1e-5)
                + pl.col("weight_b") * 0.8 / (pl.col("weight_b").sum() + 1e-5)
                ).fill_nan(1e-5),
).with_columns(
    # only final_result is required, all col above is auxiliary
    # but I don't know how to omit storage these auxiliary cols.
    final_result=pl.col("weight_sum") / pl.col("weight_sum").sum()
).collect()

# 178 µs ± 466 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
And the same logic I convert to numpy and numba
```python
import numba
def calc_numpy(np_a, np_b):
    np_weight_a=np_a ** 1.5
    np_weight_b=1 / (np_b + 10)
    np_weight_sum=(np_weight_a / (np_weight_a.sum() + 1e-5)
                                + np_weight_b * 0.8 / (np_weight_b.sum() + 1e-5)
                                )
    
    np.nan_to_num(np_weight_sum, copy=False)
    final_result=np_weight_sum / np_weight_sum.sum()
    return final_result

calc_numba = numba.njit(calc_numpy)

# numpy result, include the pl->np conversation cost
%%timeit
np_a=df_sample['a'].to_numpy()
np_b=df_sample['b'].to_numpy()
calc_numpy(np_a, np_b)
# 25 µs ± 339 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
# ---------------------
# first, please run once without "timeit" for jit warmup
%%timeit
np_a=df_sample['a'].to_numpy()
np_b=df_sample['b'].to_numpy()
calc_numba(np_a, np_b)
# 8.88 µs ± 83.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

As you see results above, there may be huge overhead in polars for small dataset(42 rows)
```
polars: 178 µs
polars->numpy: 25 µs
polars->numba: 8.88 µs
```

And I also tested for 1k and 5k rows

 --  | 42 rows | 1k rows | 5k rows
-- | -- | -- | --
polars | 178 µs | 200 µs | 232 µs
polars->numpy | 25 µs | 33.5 µs | 64.4 µs
polars->numba | 8.88 µs | 18.7 µs | 62.7 µs


In my production, polars is far more faster than pandas in big-size data, and I'm replacing pandas to polars gradually.
However it's definitely would make world better if polars can to do some fast path for these small and medium size data:) 
For these data, optimizations on expressions may not have benefit.

**Comment by ritchie46** [comment]
Your whole runtime is in the microseconds? Why are you optimizing then? 

Polars runs the optimizations so that the expensive operations are fast. Things that already have acceptable performance run a bit slower because we first optimize, but it shouldn't matter I most cases. 

That's why I ask, what is your total runtime?

**Comment by aploium** [comment]
because it's within a reinforcement learning environ step, this process will repeat tens of millions times

**Comment by ritchie46** [comment]
Now, we are talking. And every step is dependent on the previous one? If so, I would go for a matrix library.

If not, you can make a long table and do a groupby over all sorted steps. This will yield a lot of parallelization and vectorization benefits. The optimization pass will be amortized over all steps.

**Comment by aploium** [comment]
Thanks for your care, however these step is state dependent, which cannot be pre-calc. Actually, I definitely had done things that CAN be prepared or batched, the `a` and `b` in real production already are results for many pre-calc. 
And my specific bottomneck above, can be solved by using numba.

**Comment by ritchie46** [comment]
Yes, on these very small row numbers it can even be that our parallelization hurts performance. I think this iterative computation is better for a matrix library/ numba as we cannot scale up the problem to something that benefits more from optimization and parallelization.

**Comment by ritchie46** [comment]
If you can make a rust version of this, I can make flamegraph and see if we have some low hanging fruit.

**Comment by aploium** [comment]
I'm very sorry but I dont know rust

**Comment by aploium** [comment]
I think my initial thought maybe: 
"wow, polars is blazing fast and it's api design is so beautiful comparing to pandas, I can finally use DataFrame as a basic datastructure like dict/list/set, let's use it everwhere!"

that may be too strict to polars

**Comment by ritchie46** [comment]
It makes sense for a lot of things, but your use case is dependent on previous operations `R(R(R(R, ...) ) )`, where R is very small, that is hard to optimize. 

If I have some time, I can take a look at the flamegraph to have more info.

**Comment by aploium** [comment]
Than you, I'll close this issues

**Comment by ritchie46** [comment]
There is a large sleep chunk in our parallelism. I am taking a look.

![image](https://github.com/pola-rs/polars/assets/3023000/f7be76c4-6b60-4032-ada8-da10055f08fa)

**Comment by ritchie46** [comment]
Yes, it is parallelization overhead. I can cut it in half by not parallelizing literal evaluation and forcing the `with_columns` to run sequential. For the latter, I shall add a user argument so users can control that. 

It is not possible for us to determine when this should run sequentially.

**Comment by orlp** [comment]
> because it's within a reinforcement learning environ step, this process will repeat tens of millions times
the total one step is about 1ms, so 200 μs is import to me

Polars is not designed to be used for iterative number crunching, especially not on relatively small datasets. It is designed to do analytical queries on (large) datasets. I think a numerical library like numpy or pytorch would be more appropriate here.

Closing this as Ritchie has merged the features that allows forcing sequential runners.
