### ISSUE TITLE
Implement `get_pointer` for small integer and `Utf8` types

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10323]
### Problem description

In order to implement the dataframe interchange protocol (#10035), we need to implement `get_pointer` for all types supported by the dataframe protocol.

The following types panic:
* `Int8`
* `Int16`
* `UInt8`
* `UInt16`

The following types throw a ComputeError:
* `Utf8`

### Example: small int
```python
pl.Series([1, 2, 3], dtype=pl.UInt8)._s.get_ptr()
```
```
thread '<unnamed>' panicked at 'not implemented', src/series/mod.rs:695:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: not implemented
```

### Example: Utf8
```python
pl.Series(["a", "b", "a"])._s.get_ptr()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
exceptions.ComputeError: Cannot take pointer of nested type
```

**Comment by ritchie46** [comment]
What should utf8 return then? The pointer to the bytes data? 

Say we have a utf8 column `["foo", None, "bar", ""]`, this would return a pointer to this on the heap: `b"foobar"`

**Comment by stinodego** [comment]
> What should utf8 return then? The pointer to the bytes data?
> 
> Say we have a utf8 column `["foo", None, "bar", ""]`, this would return a pointer to this on the heap: `b"foobar"`

Yes I think that's what we need... I'd say just merge your PR and I can check if it works in practice!
