### ISSUE TITLE
`str.json_extract` does not read a mixed dtype column as UTF8 when specified in struct schema

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10320]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
bad_dict = {
    "col1":1,
    "col2": [2, [1,3]]
}
df = pl.DataFrame(pl.Series('dict', [json.dumps(bad_dict)]))

struct = pl.Struct(
    {
        'col1':pl.Int16, 
        'col2':pl.Utf8, 
     }
    )

print(df.select(pl.col('dict').str.json_extract(struct)))
shape: (1, 1)
┌───────────┐
│ dict      │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {1,null}  │
└───────────┘
```

### Issue description

I sometimes have to handle data where json schema's are of low quality and may contain mixed dtypes. Currently I can parse all jsons into a string and use `.str.json_extract()` to either the full json, while passing an override for these mixed dtype columns. In some cases I know it should have been one specific dtype, in other cases I just want to parse it as string, but this doesn't seem to work.

With `json_path_match($.col2)` it will parse the value as string.

### Expected behavior

When I specify Utf8 for a column with potential mixed dtypes it should parse it as a string.

```python
print(df.select(pl.col('dict').str.json_extract(struct)))
shape: (1, 1)
┌───────────┐
│ dict      │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {1,"[2,[1,3]] "}  │
└───────────┘

```
### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.25.0
pandas:              2.0.2
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.17
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by cmdlineluser** [comment]
Hmm, but isn't that like saying if you did
```python
pl.Series([{"foo": [1, 2, 3]}], dtype=pl.Struct({"foo": pl.Utf8}))
```
You would expect Polars to convert `[1, 2, 3]` into a string instead of raising an error?

Can you leave `col2` out of the schema and load it separately?
```python
df.select(
   pl.struct(
      pl.col("dict").str.json_extract(pl.Struct({"col1": pl.Int16})).struct["col1"],
      pl.col("dict").str.json_path_match("$.col2")
   )
)

# ┌─────────────────┐
# │ col1            │
# │ ---             │
# │ struct[2]       │
# ╞═════════════════╡
# │ {1,"[2,[1,3]]"} │
# └─────────────────┘
```

**Comment by ion-elgreco** [comment]
> Hmm, but isn't that like saying if you did
> 
> ```python
> pl.Series([{"foo": [1, 2, 3]}], dtype=pl.Struct({"foo": pl.Utf8}))
> ```
> 
> You would expect Polars to convert `[1, 2, 3]` into a string instead of raising an error?

Yes, because I expect it to override the dtype, since I passed my own.

> 
> Can you leave `col2` out of the schema and load it separately?
> 
> ```python
> df.select(
>    pl.struct(
>       pl.col("dict").str.json_extract(pl.Struct({"col1": pl.Int16})).struct["col1"],
>       pl.col("dict").str.json_path_match("$.col2")
>    )
> )

> ```

Yes, that's what my current workaround is, but I would still consider it a bug  because `str.json_path_match` is able to load this mixed dtype col as a string.

**Comment by ion-elgreco** [comment]
Support has been added for this in: https://github.com/pola-rs/polars/pull/11057
