### ISSUE TITLE
Add `.str.head` and `.str.tail`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10337]
### Problem description

These could simply be syntactic sugar for `.str.slice(0, n)` and `.str.slice(-n)`, but they are pretty common string operations and make the code a bit more obvious when used.

**Comment by orlp** [comment]
I don't mind the functions existing per se, but I don't like the proposed names. They're not very descriptive, and make no sense for languages that read right-to-left such as Hebrew or Arabic.

**Comment by cmdlineluser** [comment]
When I searched for this functionality previously, I thought `.str.head()` / `.str.tail()` may have existed.

**Comment by mcrumiller** [comment]
I was basing the names off of the standard [`left and right`](https://www.postgresql.org/docs/9.1/functions-string.html) SQL operators, which we often mimick. These functions are semantically distinct from `head`/`tail` for exactly the reasons @orlp mentioned. `LEFT` in SQL doesn't necessarily mean "the beginning of the string", it means "the left n characters of the string."

**Comment by orlp** [comment]
> I was basing the names off of the standard [left and right](https://www.postgresql.org/docs/9.1/functions-string.html) SQL operators, which we often mimick.

In many cases I don't think copying what SQL does is a good choice, especially when it comes to naming. When choosing between two otherwise equivalent options it can nudge the decision, but I don't think that's the case here.

> for exactly the reasons @orlp mentioned: LEFT in SQL doesn't necessarily mean "the beginning of the string," it means "the left n characters of the string."

I don't think we want to define our operators in terms of locality sensitive things such as reading order. What if a string contains both Hebrew and English? Furthermore, a "character" is an incredibly ill-defined concept. Emoji, combining codepoints, etc, you don't want to get into that mess, trust me.

I'd much prefer `head` and `tail` that always keep a given amount of Unicode codepoints (which corresponds to bytes for ASCII) from respectively the start/end of the string.

**Comment by mcrumiller** [comment]
> I'd much prefer head and tail that always keep a given amount of Unicode codepoints (which corresponds to bytes for ASCII) from respectively the start/end of the string.

I'm not married to left and right, but I am a bit confused. `head` and `tail` to me indicate "start" and "end" of the string, which more ambiguous when locality exists. For Hebrew languages, `head` means the start of the string, which starts from the right. For `.left` and `.right` there is zero ambiguity, because directions don't depend on locality.

I'll implement this as head and tail since I'm obviously outvoted here, unless some others want to chime in.

**Comment by orlp** [comment]
>  For .left and .right there is zero ambiguity, because directions don't depend on locality.

But they do! Consider the following string:

الدب القطبي

That is (according to Google translate) Arabic for "polar bear". If I save that piece of text in a file and take the first 4 codepoints:

```python
with open("in.txt") as f, open("out.txt", "w") as o:
    o.write(f.read()[:4])
```

We get:

الدب


The first four codepoints for this Arabic string... are the *rightmost* glyphs.

**Comment by mcrumiller** [comment]
> The first four codepoints for this Arabic string... are the rightmost glyphs.

Yes, but you didn't call a `left` function! You referenced the *first* 4 characters via the accessor `[:4]`. But since we are using a proxy for `slice`, I suppose the naming should depend on the behavior of `slice`. Do you happen to know offhand if `str.slice(0, n)` follows locality (i.e. will it return the rightmost glyphs in your hypothetical Arabic file)?

**Comment by orlp** [comment]
> Do you happen to know offhand if str.slice(0, n) follows locality (i.e. will it return the rightmost glyphs in your hypothetical Arabic file)?

I will eat a shoe if `str.slice` functions differently than Python's `s[:4]`, which is also called slicing. If I do turn out to be wrong, after eating said shoe, we should fix that.

**Comment by orlp** [comment]
I don't know what our policy on Rust/Python functionality parity is, perhaps @ritchie46 or @stijndegooijer can comment.

**Comment by ritchie46** [comment]
Yes, we prefer to to have the lazy/expression API in sync. Can you add the `slice` aliases on the rust side too and then add docs entries for python?

**Comment by orlp** [comment]
Should `head` and `tail` support negative arguments?

E.g. `.str.head(-3)` is everything *except* the last three characters, and `.str.tail(-5)` is everything *except* the first 5 characters.

**Comment by mcrumiller** [comment]
@orlp that's the case for dataframes and series, so I think we should.

> **Parameters:**
> **n**
> Number of elements to return. If a negative value is passed, return all elements except the last `abs(n)`.
