### ISSUE TITLE
Improve `read_csv`: schema, consistency, date parsing

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10340]
### Problem description

I think `read_csv` is one of the most important/used methods in polars because it is this entrypoint when getting started and used all the time and should be as nice, intuitive and flexible as possible! :)

Some improvements I would love to see with reasons + examples

Short version:
- add `infer_schema` (True/False)
- add date format (like pandas has available)
- make parsing behaviour consistenst across types (my biggest "pain"; maybe even a BUG?)

## Add `infer_schema`

**Reason:**
- I remember when starting with polars I wanted to read a csv without any parsing and could not find this parameter
- This is currently "hidden" behind `infer_schema_length=0` and therefore hard to find and not intuitive
- would be cool to have this explicit and easy to find parameter!

current:
```python
pl.read_csv(
    source='...',
    infer_schema_length=0,  
)
```
problems:
- very cryptic and non intuitive for newcommers
- hard to find
- it is like saying: "I practiced 0 minutes of piano today" instead of "I did not practice"

proposal:
```python
pl.read_csv(
    source='...',
    infer_schema=False,  # default: True?  
)
```
benefits:
- intuitive and very easy to understand/find
- separation of concerns; do not "overload" parameter with multiple things
  - do you want to infer data types: `infer_schema` Yes/No
  - how many lines should be read to infer: `infer_schema_length` 1/10/100?

## Add `date_format` 

**Reason**
- very common use case to parse dates when reading csv files
- not everyone uses standard date format
- much nicer/cleaner to parse dates when reading instead of adding another transformation step afterwards

current:
```python
DTYPES = {'date1': pl.Utf8, 'date2': pl.Utf8} # not exactly what I want...

data = '''
int,float,date1,date2
3,3.4,31.01.2023,05.05.2023
3,3.4,28.02.2023,06.06.2023
'''

pl.read_csv(
    source=StringIO(data),
    dtypes=DTYPES,
).with_columns(
    pl.col(['date1', 'date2']).str.to_date(format='%d.%m.%Y'),
)
```
problems:
- cannot specify my desired schema directly because only standard dates can be parsed
- additional transformation step required

proposal:
```python
DTYPES = {'date1': pl.Date, 'date2': pl.Date} # Yes, this is what I want!

data = '''
int,float,date1,date2
3,3.4,31.01.2023,05.05.2023
3,3.4,28.02.2023,06.06.2023
'''

pl.read_csv(
    source=StringIO(data),
    dtypes=DTYPES,
    date_format='%d.%m.%Y',  # <<< NEW
)
```
benefits:
- able to specify desired schema directly
- no additional transformation required

Options/Ideas on `date_format` parameter
- 1: `str`: one format for all date columns
- 2: `dict[str,str]` (Optional): specify a format for each column (could theoretically be useful but must be strange csv if it uses different date formats)
- 3: `Sequence[str]` (Optional): specify multiple formats to check one after another (useful when allowing multiple formats and in data exploration)

## Consistent parsing across types

This is my biggest gripe currently to be honst and this might even be a bug/unintentional because I could not find it explained in the docs ^^ 

**Reason**
- I should be able to do the folling things when reading 
    - read everything as str
    - specify types and try to parse, if invalid use null
    - specify types and force to parse, if invalid then crash ->> this is not possible for all types and really useful in production ETL

currently:
```python
DTYPES = {
    'int': pl.Int64,
    'float': pl.Float64,
    'date': pl.Date,
}

DATA_VALID = 'int,float,date\n3,3.4,2023-01-31'
DATA_INVALID_INT = 'int,float,date\nX,3.4,2023-01-31'
DATA_INVALID_FLOAT = 'int,float,date\n3,X,2023-01-31'
DATA_INVALID_DATE = 'int,float,date\n3,3.4,X'

pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ok; int: null
    # source=StringIO(DATA_INVALID_FLOAT),  # ok; float: null
    # source=StringIO(DATA_INVALID_DATE),   # ok; date: null
    dtypes=DTYPES,
    ignore_errors=True,  # Ignore problems; use null instead
)

pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ComputeError: Could not parse `X` as dtype `i64` at column 'int' (column number 1)
    # source=StringIO(DATA_INVALID_FLOAT),  # ComputeError: Could not parse `X` as dtype `f64` at column 'float' (column number 2)    
    # source=StringIO(DATA_INVALID_DATE),   # ok with date: null <<<<<<< PROBLEM! WHY??
    dtypes=DTYPES,
    ignore_errors=False,  # Do NOT ignore problems; please crash; (Not working on temporal types...)
)
``` 
problems:
- this behaviour seems very unitiutive and unexpected. Is this intended? Bug? I cant find any explanation in the docs?
- in my opinion `ignore_errors=False` should crash independend on type if conversions fails
- there is absolutely no way to differentiate if a date value was empty or could not be parsed

proposal:
```python
pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ComputeErrorComputeError: Could not parse `X` as dtype `i64` at column 'int' (column number 1)
    # source=StringIO(DATA_INVALID_FLOAT),  # ComputeError: Could not parse `X` as dtype `f64` at column 'float' (column number 2)    
    # source=StringIO(DATA_INVALID_DATE),   # ComputeError: ... <<<<<<<< Yes, consistent Error!
    dtypes=DTYPES,
    ignore_errors=False,
)
```
benefits:
- consistent parsing of all dtypes
- intuitive behaviour
- being able to differentiate between emtpy date values and parsing errors

**Comment by orlp** [comment]
Could you please split up your concerns in separate issues instead of combining it all into one super-issue? Then we can discuss, track and decide on each request individually.
