### ISSUE TITLE
PanicException when calling take_every on LazyFrame with a 0

### ISSUE THREAD

**Issue by danielm-dk** [pola-rs/polars#10346]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data = {"a": [1]}
lf = pl.LazyFrame(data)

lf.take_every(0).collect() # PanicException
```

### Issue description

Passed the number 0 to take_every on a lazy dataframe and got a PanicException:

`
thread '<unnamed>' panicked at 'assertion failed: step != 0', /rustc/0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8/library/core/src/iter/adapters/step_by.rs:33:9
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/mid/Desktop/polarstest/m2.py", line 6, in <module>
    lf.take_every(0).collect()
  File "/Users/mid/Desktop/polarstest/.env/lib/python3.9/site-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/Users/mid/Desktop/polarstest/.env/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1600, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: assertion failed: step != 0
`

### Expected behavior

Expected a ValueError with a reasonable message

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.9.6 (default, May  7 2023, 23:32:44)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
Yes, this should give a better error. It's not a bug though, `take_every(0)` is nonsensical.
