### ISSUE TITLE
`read_csv`: add `infer_schema` parameter

### ISSUE THREAD

**Issue by Julian-J-S** [pola-rs/polars#10342]
## Add `infer_schema`

**Reason:**
- I remember when starting with polars I wanted to read a csv without any parsing and could not find this parameter
- This is currently "hidden" behind `infer_schema_length=0` and therefore hard to find and not intuitive
- would be cool to have this explicit and easy to find parameter!

current:
```python
pl.read_csv(
    source='...',
    infer_schema_length=0,  
)
```
problems:
- very cryptic and non intuitive for newcommers
- hard to find
- it is like saying: "I practiced 0 minutes of piano today" instead of "I did not practice"

proposal:
```python
pl.read_csv(
    source='...',
    infer_schema=False,  # default: True?  
)
```
benefits:
- intuitive and very easy to understand/find
- separation of concerns; do not "overload" parameter with multiple things
  - do you want to infer data types: `infer_schema` Yes/No
  - how many lines should be read to infer: `infer_schema_length` 1/10/100?

**Comment by ritchie46** [comment]
I agree. Could you make a PR? This can just be handled on the python side.
