### ISSUE TITLE
Define "character" in `str.slice` docstring

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10349]
### Problem description

From #10339, the docstring for `str.slice` currently is:

```
        Create subslices of the string values of a Utf8 Series.

        Parameters
        ----------
        offset
            Start index. Negative indexing is supported.
        length
            Length of the slice. If set to ``None`` (default), the slice is taken to the
            end of the string.
```

It's a bit ambiguous as to whether or not a slice returns bytes or characters/codepoints. Using the following:

```python
>>> import polars as pl

>>> # the following is Google's translation of "polar bear" into Arabic. It is 21 bytes with 11 code points.
>>> s = 'الدب القطبي'
>>> [len(c.encode()) for c in s]
[2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2]
```
Polars slices return codepoints:
```
>>> s2 = pl.Series([s])
>>> len(s2.str.slice(0, 1)[0].encode())
2
```
We should probably specify this. I think I'll go by [@avimallu's recommendation](https://github.com/pola-rs/polars/pull/10339#issuecomment-1668028304).

**Comment by orlp** [comment]
For reference, this is what Rust's [`str::chars`](https://doc.rust-lang.org/std/primitive.str.html#method.chars) method has as it's documentation:

> As a string slice consists of valid UTF-8, we can iterate through a string slice by [char](https://doc.rust-lang.org/std/primitive.char.html). This method returns such an iterator.

> It’s important to remember that [char](https://doc.rust-lang.org/std/primitive.char.html) represents a Unicode Scalar Value, and might not match your idea of what a ‘character’ is. Iteration over grapheme clusters may be what you actually want. This functionality is not provided by Rust’s standard library, check crates.io instead.

**Comment by mcrumiller** [comment]
@ritchie46 I ended up just doing small implementations since I wasn't sure where aliasing should stop; maybe the compiler can detect some shortcut this way. Looks like everything is working.
