### ISSUE TITLE
`read_csv`: add `date_format` parameter (like pandas)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10343]
## Add `date_format` (like pandas)

**Reason**
- very common use case to parse dates when reading csv files
- not everyone uses standard date format
- much nicer/cleaner to parse dates when reading instead of adding another transformation step afterwards

current:
```python
DTYPES = {'date1': pl.Utf8, 'date2': pl.Utf8} # not exactly what I want...

data = '''
int,float,date1,date2
3,3.4,31.01.2023,05.05.2023
3,3.4,28.02.2023,06.06.2023
'''

pl.read_csv(
    source=StringIO(data),
    dtypes=DTYPES,
).with_columns(
    pl.col(['date1', 'date2']).str.to_date(format='%d.%m.%Y'),
)
```
problems:
- cannot specify my desired schema directly because only standard dates can be parsed
- additional transformation step required

proposal:
```python
DTYPES = {'date1': pl.Date, 'date2': pl.Date} # Yes, this is what I want!

data = '''
int,float,date1,date2
3,3.4,31.01.2023,05.05.2023
3,3.4,28.02.2023,06.06.2023
'''

pl.read_csv(
    source=StringIO(data),
    dtypes=DTYPES,
    date_format='%d.%m.%Y',  # <<< NEW
)
```
benefits:
- able to specify desired schema directly
- no additional transformation required

Options/Ideas on `date_format` parameter
- 1: `str`: one format for all date columns
- 2: `dict[str,str]` (Optional): specify a format for each column (could theoretically be useful but must be strange csv if it uses different date formats)
- 3: `Sequence[str]` (Optional): specify multiple formats to check one after another (useful when allowing multiple formats and in data exploration)

**Comment by fernandocast** [comment]
Hello I'm new to polars and I would like to contribute on this project ,
could you please assign this issue to me?

**Comment by MarcoGorelli** [comment]
Closing as duplicate then
