### ISSUE TITLE
API: Deprecate `time_zone` in to_datetime (use `.dt.replace_time_zone` instead)

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#10348]
`to_datetime` has a `time_zone` argument https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.to_datetime.html , and I'm suggesting that it be deprecated

Why?

This was asked on Discord today:
```python
In [41]: pl.Series(['2020-10-25 01:00']).str.to_datetime(time_zone='Europe/London')
---------------------------------------------------------------------------
ArrowErrorException: InvalidArgumentError("datetime '2020-10-25 01:00:00' is ambiguous in time zone 'Europe/London'. Please use `use_earliest` to tell how it should be localized.")
```

In this case, `to_datetime` doesn't have a `use_earliest` argument, so there's nothing users can do.

One solution could be to add `use_earliest` to `to_datetime`.

But, even simpler, would be to deprecate `time_zone` from `to_datetime`. If users want to set a particular time zone, they can then call `.dt.replace_time_zone`, which does have a `use_earliest` argument

**Comment by stinodego** [comment]
I'm not 100% sure on this one. I chose to add `use_earliest` when I updated `pl.datetime`. I think we should do the same here.

Having users add `.dt.replace_time_zone(...)` to every datetime-related call does not seem very ergonomic.

**Comment by MarcoGorelli** [comment]
ah good point, thanks!

**Comment by stinodego** [comment]
Still, we should address this, either with the extra `use_earliest` argument or something else. So thanks for the report! I'm accepting this.
