### ISSUE TITLE
`read_csv`: consistent parsing across types (possible bug?)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10344]
## Consistent parsing across types

This is my biggest gripe currently to be honst and this might even be a bug/unintentional because I could not find it explained in the docs ^^ 

**Reason**
- I should be able to do the folling things when reading 
    - read everything as str
    - specify types and **try** to parse, if invalid use null
    - specify types and **force** to parse, if invalid then crash ->> this is not possible for all types and really useful in production ETL

currently:
```python
DTYPES = {
    'int': pl.Int64,
    'float': pl.Float64,
    'date': pl.Date,
}

DATA_VALID = 'int,float,date\n3,3.4,2023-01-31'
DATA_INVALID_INT = 'int,float,date\nX,3.4,2023-01-31'
DATA_INVALID_FLOAT = 'int,float,date\n3,X,2023-01-31'
DATA_INVALID_DATE = 'int,float,date\n3,3.4,X'

# Consistent: on error -> null
pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ok; int: null
    # source=StringIO(DATA_INVALID_FLOAT),  # ok; float: null
    # source=StringIO(DATA_INVALID_DATE),   # ok; date: null
    dtypes=DTYPES,
    ignore_errors=True,  # Ignore problems; use null instead
)

# NOT consistenst! On error: int/float -> Error; Temporal types -> null !?!?
pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ComputeError: Could not parse `X` as dtype `i64` at column 'int' (column number 1)
    # source=StringIO(DATA_INVALID_FLOAT),  # ComputeError: Could not parse `X` as dtype `f64` at column 'float' (column number 2)    
    # source=StringIO(DATA_INVALID_DATE),   # ok with date: null <<<<<<< PROBLEM! WHY??
    dtypes=DTYPES,
    ignore_errors=False,  # Do NOT ignore problems; please crash; (Not working on temporal types...)
)
``` 
problems:
- this behaviour seems very unitiutive and unexpected. Is this intended? Bug? I cant find any explanation in the docs?
- in my opinion `ignore_errors=False` should crash independend on type if conversions fails
- there is absolutely no way to differentiate if a date value was empty or could not be parsed

proposal:
```python
pl.read_csv(
    source=StringIO(DATA_VALID),            # ok
    # source=StringIO(DATA_INVALID_INT),    # ComputeErrorComputeError: Could not parse `X` as dtype `i64` at column 'int' (column number 1)
    # source=StringIO(DATA_INVALID_FLOAT),  # ComputeError: Could not parse `X` as dtype `f64` at column 'float' (column number 2)    
    # source=StringIO(DATA_INVALID_DATE),   # ComputeError: ... <<<<<<<< Yes, consistent Error!
    dtypes=DTYPES,
    ignore_errors=False,
)
```
benefits:
- consistent parsing of all dtypes
- intuitive behaviour
- being able to differentiate between emtpy date values and parsing errors

**Comment by orlp** [comment]
Is it only dates that have this problem?

**Comment by orlp** [comment]
Thank you for your detailed investigation. I'll look at it later to see which things need to be changed.

**Comment by ritchie46** [comment]
This is due to the fact that some dtypes are directly supported in our reader, whilst other are casted after the parsing (from another dtype, e.g. Utf8 or I64).

I shall ensure we respect the `ignore_errors` flag during this cast.
