### ISSUE TITLE
Invalid time unit conversion in arrow conversions for list[datetime] types

### ISSUE THREAD

**Issue by edavisau** [pola-rs/polars#10354]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

When converting from a `pa.list_(pa.timestamp("s"))` dtype to `pl.List(pl.Datetime("ms"))` dtype, 
```python
from datetime import datetime
import pyarrow as pa
import polars as pl

arr = pa.array([[datetime(2023, 8, 8, 9, 53), datetime(2024, 8, 8, 9, 53)]], type=pa.list_(pa.timestamp("s")))
result = pl.from_arrow(arr)

assert arr.to_pylist() == result.to_list()
# Left: [[datetime.datetime(2023, 8, 8, 9, 53), datetime.datetime(2024, 8, 8, 9, 53)]]
# Right: [[datetime.datetime(1970, 1, 20, 13, 51, 28, 380000), datetime.datetime(1970, 1, 20, 22, 38, 30, 780000)]]
```

### Issue description

Seems to only happen for the "s" time unit, since it is not supported in polars

Also worth noting that `pa.timestamp("s")` to `pl.Datetime("ms")` works fine when not using the list type.

### Expected behavior

assertion above should succeed

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          3.7.0
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            1.10.5
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Quick triage: think we're missing a scaling path for _nested_ Timestamp/Duration/Time arrow dtypes (with "seconds" precision) in the `fn to_physical_and_dtype` function [[source](https://github.com/pola-rs/polars/blob/833113be90b0f1fa3380c4f05d5bd8dafcf3830d/crates/polars-core/src/series/from.rs#L488)] in `polars-core/series/from.rs` (if _not_ nested, `fn try_from_arrow_unchecked` will appropriately scale the underlying by `MILLISECONDS`).

**Comment by ion-elgreco** [comment]
@alexander-beedie  is this https://github.com/pola-rs/polars/issues/10160 possibly related to the above issue?

**Comment by stinodego** [comment]
Looks like this has been fixed.
