### ISSUE TITLE
(Python) `pl.from_pandas` inconsistent with `DataFrame` constructor

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#1035]
The `from_pandas` in `convert.py` has logic that is completely different from the logic of `pandas_to_pydf` in `construction.py`. To me, it's not clear which logic is prefered or what is even the difference; I think we should be consistent, though. Which way to go on this?

Also, `Series` doesn't have a `_from_pandas` classmethod at all. We should add that.

**Comment by ritchie46** [comment]
I didn't realize we had 2 implementations for this. The logic in `convert.from_pandas` is up to date. The other one can be removed. It also does not handle time conversion properly.

**Comment by stinodego** [comment]
All right, I'll try to update that!
