### ISSUE TITLE
Treat datetimes like '2023-07-31 00:00:00' equivalent with '2023-07-31'

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10368]
### Problem description

In a hive-partitioned parquet file, Spark handles partition values '2023-07-31 00:00:00' like it was '2023-07-31'.
Would be nice, if polars could do that too.
So instead of:
pl.col('CALENDAR_DATE') == '2023-07-31 00:00:00'
I could use:
pl.col('CALENDAR_DATE') == '2023-07-31'

Where CALENDAR_DATE is a datetime[ns] type of column.

**Comment by lmocsi** [comment]
# Working example:
```
import polars as pl
import pyarrow.dataset as ds

mytab = pl.scan_pyarrow_dataset(ds.dataset("my_table_name", partitioning='hive'))
mytab.filter(pl.col('CALENDAR_DATE') == '2023-08-01 00:00:00').collect()

# Should work for this as well:
#mytab.filter(pl.col('CALENDAR_DATE') == '2023-08-01').collect()

```

[my_table_name.zip](https://github.com/pola-rs/polars/files/12290365/my_table_name.zip)

**Comment by MarcoGorelli** [comment]
hi - is `'CALENDAR_DATE'` of dtype `Utf8` (string)? if so, then only matching the exact string will work

if it's a datetime column, then you can compare with `dt.date(2023, 8, 1)` or `dt.datetime(2023, 8, 1)`

**Comment by orlp** [comment]
```python
>>> mytab.schema
{'USER_ID': Float64, 'TRX_CNT': Float64, 'CALENDAR_DATE': Utf8}
```

You don't have `datetime[ns]`, your date is still a string. Parse it appropriately and it works:

```python
>>> mytab = mytab.with_columns(pl.col('CALENDAR_DATE').str.strptime(pl.Datetime))
>>> mytab.filter(pl.col('CALENDAR_DATE').dt.date() == pl.date(2023, 8, 1)).collect()
shape: (4, 3)
┌─────────┬─────────┬─────────────────────┐
│ USER_ID ┆ TRX_CNT ┆ CALENDAR_DATE       │
│ ---     ┆ ---     ┆ ---                 │
│ f64     ┆ f64     ┆ datetime[μs]        │
╞═════════╪═════════╪═════════════════════╡
│ 1000.0  ┆ 434.0   ┆ 2023-08-01 00:00:00 │
│ 1001.0  ┆ 11.0    ┆ 2023-08-01 00:00:00 │
│ 1002.0  ┆ 3.0     ┆ 2023-08-01 00:00:00 │
│ 1003.0  ┆ 555.0   ┆ 2023-08-01 00:00:00 │
└─────────┴─────────┴─────────────────────┘
```

**Comment by lmocsi** [comment]
Can polars take advantage of partitioning after
`pl.col('CALENDAR_DATE').str.strptime(pl.Datetime)
`
And then filtering on CALENDAR_DATE?

**Comment by orlp** [comment]
In principle yes, I don't know whether it does currently.
