### ISSUE TITLE
extreme memory usage when streaming

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#10362]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Environment: I'm working on a 4G pod

**First step**: create a huge dataframe -- this needs about 10-12G of memory and can take a while. Probably there is a better way to do this, but this is the way I know (until I'm properly educated that is 😅)
```python
import polars as pl
import random

create_from = {
    'col_1': ['R', 'Z', 'V', 'P'] ,
    'col_2': ['28', '27', '29', '99'] ,
    'col_3': ['08', '05', '07', '99', '06'] ,
    'col_4': ['05', '04'] ,
    'col_5': ['09', '04', '03', '02', '01', '05', '99', '06', '07', '08'] ,
    'col_6': ['0'] ,
    'col_7': ['2', '1', '0'] ,
    'col_8': ['IK010', 'IK011', 'IK012'] ,
    'col_9': ['010', '080', '040', 'ZZZ', '100', '050', '030', '020', '090', '070', '060'] ,
    'col_10': ['09', '98', '01', '04'] ,
    'col_11': ['+999999999999999', '+000000040000000', '+000000020000000'] ,
    'col_12': ['+999999999999999', '+000000006000000', '+000000012500000'] ,
    'col_13': ['-05000'] ,
    'col_14': ['-05000'] ,
    'col_15': ['-05000'] ,
    'col_16': ['-05000'] ,
    'col_17': ['-05000'] ,
    'col_18': ['-05000'] ,
    'col_19': ['-05000'] ,
    'col_20': ['-05000'] ,
    'col_21': ['-05000'] ,
    'col_22': ['-05000'] ,
    'col_23': ['-05000'] ,
    'col_24': ['-05000'] ,
    'col_25': ['-05000'] ,
    'col_26': ['-05000'] ,
    'col_27': ['-05000'] ,
    'col_28': ['-05000'] ,
    'col_29': ['-05000'] ,
    'col_30': ['-05000'] ,
    'col_31': ['-05000'] ,
    'col_32': ['-05000'] ,
    'col_33': ['-05000'] ,
    'col_34': ['-05000'] ,
    'col_35': ['-05000'] ,
    'col_36': ['-05000'] ,
    'col_37': ['-05000'] ,
    'col_38': ['-05000    '] ,
}

data = {
    col: []
    for col in create_from
}

for _ in range(11_500_000):
    for col, values in create_from.items():
        data[col].append(random.choice(values))

pl.DataFrame(data).write_parquet("dummy.parquet", compression="snappy")
```
** NOTE 1 ** (see under)

** Second step **: Try to read this in again via a streaming LazyFrame:
```python
pl.scan_parquet(file).collect(streaming=True).write_csv("out.csv")
```

==> This will kill my pod (when I increase the mem-size, it works but I notice it jumps to around 6GB).
==> The crash happens when doing `collect`. So it's not really streaming as I feel it's reading all data.

### Issue description

- NOTE 1= This will generate a 400M parquet file. But somehow spark is able to write this as a 24M file. Both snappy compression... But I don't understand why the size difference. Doesn't matter too much, but still.
  ```text
  spark creation: [24_455_333 bytes]
  ############ file meta data ############
  created_by: parquet-mr version 1.12.1 (build 2a5c06c58fa987f85aa22170be14d927d5ff6e7d)
  num_columns: 38
  num_rows: 11404800
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 8718

  own creation: [427_449_041 bytes]
  ############ file meta data ############
  created_by: Arrow2 - Native Rust implementation of Arrow
  num_columns: 38
  num_rows: 11500000
  num_row_groups: 43
  format_version: 2.6
  serialized_size: 90545
  ```

- NOTE 1 (2): I don't think the size of the file matter for this specific issue

### Expected behavior

I expect that the `collect` works in streaming mode by limiting the amount of memory used (ie: chunked approach).

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-5.4.249-163.359.amzn2.x86_64-x86_64-with-glibc2.26
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by svaningelgem** [comment]
Small additional comment:
The file is 400M. The data size is +- 2_449_500_000 bytes (without any structure information of course!). So it's strange that it jumps from 0.8G -> 6.2G on my pod.

**Comment by fernandocast** [comment]
Hello I'm new to Polars,
There is any chance to contribute on this issue?

**Comment by mishpat** [comment]
I think there's some confusion here: "collect", even with "streaming=True", collects all the data into memory. If your file is bigger than memory, it will not be successful. Streaming is intended to be for situations where the final data set will fit into memory, e.g. if `pl.scan_parquet({file}).filter({some filter}).collect(streaming=True)` where the filter will eliminate a number of rows so that the output saves to memory.

If the last step is data ending up on disk instead of memory, you can call `ldf.sink_parquet` instead. This is what @fernandocast suggested for #2 and it's already implemented.

**Comment by svaningelgem** [comment]
Thanks for the explanation @mishpat . I thought that the write-part would work as a sink when using the `streaming=True`.
I don't understand than the streaming part... Is it just so that the filters etc are applied in a streaming fashion?

I'd like to elevate this to a feature request then: to create a `sink_csv`/`sink_json`/`sink_...`.
The problem is that the original file easily fit into memory (24M/400M fits into 4G). And can be chunked easily while writing out. But I need a CSV (in this case). Not a parquet...

Additionaly question: will the `iter_rows()` chunk data too? Or will it be worked out by collecting to memory, and then processed by retrieving each row from memory?

**Comment by mishpat** [comment]
In reverse order of your questions: `iter_rows` only works on DataFrames, which will be in memory.

A `sink_csv` is likely not forthcoming anytime soon unless someone with a lot of enthusiasm is around, it's not a super common use case I think. You can try to split your dataframe into smaller, in-memory chunks and then just concat the csvs themselves in the filesystem.

And finally, `.collect(streaming=True)` will operate in streaming fashion on everything _before_ it in the call chain, as you read them left to right. If you look at the User Guide example (https://pola-rs.github.io/polars-book/user-guide/concepts/streaming/) there is a filter and a groupby aggregation, so the final frame could be able to fit in memory even if the original file may have been too large. But once you call `collect` in the chain, no matter what, the lazyframe gets pulled into memory as a dataframe.

**Comment by svaningelgem** [comment]
Thanks for the detailed explanations!

I'll see if I can get a crash-course in rust to contribute this feature ;-)
