### ISSUE TITLE
Make sort APIs consistent, ergonomic and extensible

### ISSUE THREAD

**Issue by ttencate** [pola-rs/polars#10365]
### Problem description

Polars as of 0.31.1 has the following `sort` functions:

```rust
Series::sort(&self, descending: bool) -> Series
SeriesTrait::sort_with(&self, options: SortOptions) -> Series
SeriesTrait::arg_sort(&self, options: SortOptions) -> IdxCa

LazyFrame::sort(self, by_column: &str, options: SortOptions) -> LazyFrame
LazyFrame::sort_by_exprs<E, B>(self, by_exprs: E, descending: B, nulls_last: bool, maintain_order: bool) -> LazyFrame

DataFrame::sort(&self, by_column: impl IntoVec<SmartString<LazyCompact>>, descending: impl IntoVec<bool>, maintain_order: bool) -> DataFrame
DataFrame::sort_with_options(&self, by_column: &str, options: SortOptions) -> DataFrame
DataFrame::sort_in_place(&mut self, by_column: impl IntoVec<SmartString<LazyCompact>>, descending: impl IntoVec<bool>, maintain_order: bool) -> Result<&mut DataFrame, PolarsError>

Expr::sort(self, descending: bool) -> Expr
Expr::sort_with(self, options: SortOptions) -> Expr
Expr::arg_sort(self, sort_options: SortOptions) -> Expr

ListNameSpace::sort(self, options: SortOptions) -> Expr

prelude::arg_sort_by<E>(by: E, descending: &[bool]) -> Expr
```

This reveals the following inconsistencies:

- `SeriesTrait::sort_with` but `DataFrame::sort_with_options`
- `LazyFrame::sort` takes a single column, but `DataFrame::sort` takes a list
- `LazyFrame::sort_by_exprs`, `DataFrame::sort_in_place` and `prelude::arg_sort_by` do not use `SortOptions` but a bunch of booleans

Furthermore, I have a call in my code that looks like this:

```rust
        .sort_by_exprs(
            [col("..."), col("..."), col("..."), col("...")],
            [false, true, false, false], false, false)
```

It's hard to read without IDE support; you'd need to look at the documentation to see which bool does what.

Passing two iterables which must be the same length is also not very nice. Better to have a single iterable whose elements contain all the necessary data.

This API is also not very extensible; we had a breaking change in the 0.31.0 release because the `maintain_order` bool was added as an extra argument. Using `SortOptions` consistently would help there (#9820).

### Suggested direction for improved API

But can we make this even more consistent while also making it more ergonomic? Maybe each type should have only a single `sort` function, which takes an options struct. Let's say `ColumnSortOptions` for a single column, `FrameSortOptions` for multiple columns:

```rust
// Prelude function by() returning a ColumnSortOptions, which implements Into<FrameSortOptions>
lazy_frame.sort(by(col("foo") + col("bar")))
data_frame.sort(by("foo"))

// Chaining
lazy_frame.sort(by(col("foo")).nulls_last().maintain_order())
data_frame.sort(by("foo").descending().nulls_first())

// Construction of FrameSortOptions from an array
lazy_frame.sort([by(col("foo")), by(col("bar"))].descending()])
data_frame.sort([by("foo"), by("bar")])
// Or maybe even this, but chaining would be difficult
lazy_frame.sort([col("foo"), col("bar")])
data_frame.sort(["foo", "bar"])

// The multithreaded flag is not specific to any one column so it would need some more legwork
lazy_frame.sort(FrameSortOptions::from([by(...), by(...)]).multithreaded(false))

// Series and Expr don't need a column name to sort by; prelude functions asc() and desc() return a ColumnSortOptions
col("foo").sort(asc())
series.sort(desc().nulls_last())
```

Probably the options structs would need to be generic, because we need it to work both for column names and for `Expr`s.

I don't know how feasible all this is, but I think it would be _nice_.

**Comment by orlp** [comment]
This could definitely use streamlining, yes. However `sort` and `arg_sort` are two different beasts and should not be combined. `sort_in_place` also has a different signature.
