### ISSUE TITLE
`write_csv` should have a `lineterminator`

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#10371]
### Problem description

When creating CSV files for Windows on a Linux system, it'd be enormously helpful to have (like pandas) a `lineterminator` option to specify we want "\r\n" instead of the default "\n".

**Comment by orlp** [comment]
This seems reasonable enough, although I'd like to invite comments about the parameter name. I think `lineterminator` is a bit of an eyesore, even if it is compatible with `pandas` and `csv`.

**Comment by svaningelgem** [comment]
@orlp : I would default to `os.linesep` as that's the most logical.
On the other hand, there is something to say for consistency (ie: always `\n`)...

**Comment by alexander-beedie** [comment]
> I would default to os.linesep as that's the most logical.

I wouldn't; Mac and Linux are both `\n`, and Windows is the odd one out with a two-char `\r\n`. Most programmatic consumers of delimited files will either expect `\n` already or will handle it transparently.

> On the other hand, there is something to say for consistency

👍  This :)

**Comment by svaningelgem** [comment]
> Mac and Linux are both `\n`, and Windows is the odd one out with a two-char `\r\n`.

One could argue that Windows has the biggest market share 😛 


That said, as a dev myself, I do like consistency!

**Comment by orlp** [comment]
@alexander-beedie Just as a nitpick, Mac is historically `\r`, to complete the fun :)

**Comment by alexander-beedie** [comment]
> @alexander-beedie Just as a nitpick, Mac is historically `\r` (yes, just `\r`), to complete the fun :)

Lol... _"The good old days..."_ While we're at it, maybe we should add a version-check to see if we're running on pre-Darwin PowerPC architecture and raise a `GetWithTheTimesException` 🤣
