### ISSUE TITLE
Example of LazyGroup#agg cannot run properly

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10374]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    #[test]
    fn group_by_with_multiple_agg_col() -> PolarsResult<()> {
        let df = df!("date" => [1,2,3], "rain" => [3,2,1])?;
        let lazy_frame = df.lazy();
        let group_by = lazy_frame.
            groupby_stable([col("date")])
            .agg([
                col("rain").min(),
                col("rain").sum(),
                col("rain")
                    .quantile(lit(0.5), QuantileInterpolOptions::Nearest)
                    .alias("median_rain"),
            ]);
        let df = group_by.collect()?;
        dbg!(&df);
        Ok(())
    }
```

### Issue description

The doc of `LazyGroup#agg` take the following code as example:
```rust
use polars_core::prelude::*;
use polars_lazy::prelude::*;
use polars_arrow::prelude::QuantileInterpolOptions;

fn example(df: DataFrame) -> LazyFrame {
      df.lazy()
       .groupby_stable([col("date")])
       .agg([
           col("rain").min(),
           col("rain").sum(),
           col("rain").quantile(lit(0.5), QuantileInterpolOptions::Nearest).alias("median_rain"),
       ])
}
```

But it can not run properly as `Error: Duplicate(ErrString("column with name 'rain' has more than one occurrences\n\nError originated just after this operation:\nDF [\"date\", \"rain\"]; PROJECT */2 COLUMNS; SELECTION: \"None\""))`.

BTW, it seems that the same problem also exists in the example code in https://pola-rs.github.io/polars/polars_lazy/index.html#joins-filters-and-projections.

### Expected behavior

One of the following options:
* Maybe this error is by design, so we should only fix the document. For example, adding `alias` to these duplicate columns.
* Automatically rename `col("rain").max()` to `rain_ Max`, or at least do this when `check_names()`.
* Other solutions.

I would like to hear your opinions. Regardless of which solution we ultimately choose, I am willing to submit a PR to fix this.

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by ritchie46** [comment]
Where can you find this example? It needs an alias indeed, because in the snippet you provided, duplicate columns are created.
