### ISSUE TITLE
`int_ranges()` performance seems to degrade with more than `49_151` rows

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#10376]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import time
import polars as pl

N = 49_152
df = pl.DataFrame({'Qty': range(1, N)})

start = time.perf_counter()

print(
    df.with_columns(
        pl.int_ranges(1, pl.col('Qty') + 1)
          .alias('List')
    )
)

print(time.perf_counter() - start)

# shape: (49_151, 2)
# ┌───────┬─────────────────┐
# │ Qty   ┆ List            │
# │ ---   ┆ ---             │
# │ i64   ┆ list[i64]       │
# ╞═══════╪═════════════════╡
# │ 1     ┆ [1]             │
# │ 2     ┆ [1, 2]          │
# │ 3     ┆ [1, 2, 3]       │
# │ 4     ┆ [1, 2, … 4]     │
# │ …     ┆ …               │
# │ 49148 ┆ [1, 2, … 49148] │
# │ 49149 ┆ [1, 2, … 49149] │
# │ 49150 ┆ [1, 2, … 49150] │
# │ 49151 ┆ [1, 2, … 49151] │
# └───────┴─────────────────┘
# 3.4095361250219867
```

With `N = 49_153`

```python
# shape: (49_152, 2)
# ┌───────┬─────────────────┐
# │ Qty   ┆ List            │
# │ ---   ┆ ---             │
# │ i64   ┆ list[i64]       │
# ╞═══════╪═════════════════╡
# │ 1     ┆ [1]             │
# │ 2     ┆ [1, 2]          │
# │ 3     ┆ [1, 2, 3]       │
# │ 4     ┆ [1, 2, … 4]     │
# │ …     ┆ …               │
# │ 49149 ┆ [1, 2, … 49149] │
# │ 49150 ┆ [1, 2, … 49150] │
# │ 49151 ┆ [1, 2, … 49151] │
# │ 49152 ┆ [1, 2, … 49152] │
# └───────┴─────────────────┘
# 10.579734208004083
```

### Issue description

I just noticed there was quite a big difference in runtime for 2 similar `int_ranges()` examples.

I've narrowed it down to `49_151` rows which takes ~3.5 seconds.

`49_152` rows seems to consistently take ~3x longer.

### Expected behavior

Perhaps there is an underlying issue that is causing the jump in runtime for 1 extra row.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by avimallu** [comment]
Can confirm this. Also on the same platform as yours (MacOS, but M2).

**Comment by mcrumiller** [comment]
Maybe leaning into conspiracy-theory land, but:

```shell
>>> hex(49_151)
'0xbfff'
>>> hex(49_152)
'0xc000'
```

Surely there's some unintended byte boundary being hit?

**Comment by mcrumiller** [comment]
Also that it looks like anything, but the total number of elements, using `n*(n+1)/2`, goes from 1,207,934,976 to 1,207,984,128. Doesn't seem to cross any boundaries there either.

**Comment by ritchie46** [comment]
Not looked at the code, but it could be you hit a realloc?

**Comment by ritchie46** [comment]
I think we should do a pass to determine the needed capacity.

**Comment by ritchie46** [comment]
Cannot reproduce. Though, you are already reaching 1.2 GB of list data at that point you already have `sum(range(1, N) * 8 / 10**9)` = 9.7 GB of list data. If you hit a realloc at that point it will be costly.
