### ISSUE TITLE
The tilde negation operator in expr ignores null value rows.

### ISSUE THREAD

**Issue by shanduoliu** [pola-rs/polars#10377]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data = {"a": [1, 2, 3], "b": [3, 4, 8], "c":[None, 3, 0]}
df = pl.DataFrame(data)
expr = (pl.col("c") == 3)
df1 = df.filter(expr)
df2 = df.filter(~expr)
print(df)
print(df1)
print(df2)
```

### Issue description

The tilde negation operator in expr ignores null value rows. df2 above returned only the third row of the df.

### Expected behavior

df2 above should have returned the first and the third row of the df.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            Windows-10-10.0.17763-SP0
Python:              3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:51:25) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.5.0
matplotlib:          3.7.2
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.0
pydantic:            1.10.7
sqlalchemy:          1.4.48
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by avimallu** [comment]
Copy pasting context and alternatives from another post:

This is expected behavior. See https://github.com/pola-rs/polars/issues/9329 for a long discussion on a similar case - other issues where this exact same problem was raised are also linked. Long story short, use `.eq_missing` when you want this behavior.

**Comment by shanduoliu** [comment]
Thanks @avimallu, this helps. Appreciate it.

**Comment by ritchie46** [comment]
close as duplicate: https://github.com/pola-rs/polars/issues/9329

Thank you @avimallu
