### ISSUE TITLE
Ability to simply subtract a dataframe from another (set operation)

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10390]
### Problem description

Given two dataframes of the same structure, it would be nice to have the subtract set operation, eg:
```
import polars as pl
d = [[2,i,1] for i in [111,222,333,444,555,666]]
df = pl.DataFrame(data=d, schema={'ID': pl.Int64, 'PRODUCT_CODE': pl.Utf8, 'VALUE': pl.Int64})
d2 = [[2,i,1] for i in [999,444,555,777,888]]
df2 = pl.DataFrame(data=d2, schema={'ID': pl.Int64, 'PRODUCT_CODE': pl.Utf8, 'VALUE': pl.Int64})

```
Anti-join does it now, like:
`df.join(df2,on=['ID','PRODUCT_CODE','VALUE'],how='anti')
`

but would be nice to have something simple like:
`df.minus(df2)
`
where you don't have to hassle with columns (especially if you have 100+ columns).

Similarly to pl.concat(), but here not adding dataframes together, but subtracting them.

**Comment by orlp** [comment]
I think a good question is also why column wildcards do not work for the `on` parameter.

**Comment by mcrumiller** [comment]
I opened this exact issue (#9804) a while back and have a PR (#9805) for it, and have been waiting for feedback before proceeding.

**Comment by mcrumiller** [comment]
If this were implemented, I would want to call it `set_difference` instead of `minus`.

To get around your column hassle (until wildcard works as @orlp pointed out it should), just use `df.columns`:

```python
df.join(df2, on=df.columns, how="anti")
```
```
shape: (4, 3)
┌─────┬──────────────┬───────┐
│ ID  ┆ PRODUCT_CODE ┆ VALUE │
│ --- ┆ ---          ┆ ---   │
│ i64 ┆ str          ┆ i64   │
╞═════╪══════════════╪═══════╡
│ 2   ┆ 111          ┆ 1     │
│ 2   ┆ 222          ┆ 1     │
│ 2   ┆ 333          ┆ 1     │
│ 2   ┆ 666          ┆ 1     │
└─────┴──────────────┴───────┘
```

**Comment by ritchie46** [comment]
> I think a good question is also why column wildcards do not work for the `on` parameter. Then it could just be `df.join(df2, on=pl.all(), how='anti')`.

Expansion should be trivial to add on `left_on` and `right_on`. If we allow it on the `on` itself, we also have to determine the UNION between two schemas. I think we can add that. Is this more common?

**Comment by mcrumiller** [comment]
@ritchie46 it might muddling up the API, what about an `on=pl.intersection()` or something similar?

**Comment by orlp** [comment]
@avimallu I take issue with the `setdiff` notation, because Polars DataFrames are not sets. `setdiff` would mean removing duplicate columns in the result as well, which I don't think is what we want.

**Comment by mcrumiller** [comment]
> I take issue with the setdiff notation, because Polars DataFrames are not sets.

I agree with this, `pl.struct` works here as a stand-in for sets. Although joins currently don't work:

```python
df = pl.select(pl.struct(pl.Series([1, 2, 3]).alias('a')))
df.join(df, on='a', how="left")
```
```
pyo3_runtime.PanicException: not implemented
```

**Comment by avimallu** [comment]
> @avimallu I take issue with the `setdiff` notation, because Polars DataFrames are not sets. `setdiff` would mean removing duplicate rows in the result as well, which I don't think is what we want.

Sure - it doesn't necessarily have to be called that; my point was that it is a useful operation. My inspiration for the use of that term comes from [data.table's setops for their data frames](https://rdatatable.gitlab.io/data.table/reference/setops.html).

**Comment by stinodego** [comment]
I don't think we should add a `DataFrame.minus` operation as an alias for an anti-join. Subtracting two dataframes could mean a lot of things - there is already [confusion ](https://github.com/pola-rs/polars/issues/10390#issuecomment-1671361573) in this very topic. An anti-join is an anti-join.

Regarding joining on a wildcard, there is an issue open for that. Until that is implemented (if we do go ahead with that), you can simply do `df.join(df2, on=df.columns, how="anti")` which I think is completely fine.
