### ISSUE TITLE
Add `synchronize_categoricals()`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10393]
### Problem description

I encounter this situation often enough that I feel it may be useful to others: you have `df1` with some categoricals that were generated separately from `df2` and thus use disparate string caches. The following example shows what you currently have to do to get them to play nicely:

```python
import polars as pl
from polars import col

df1 = pl.DataFrame({
    'a': pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
})
df2 = pl.DataFrame({
    'a': pl.Series(['d', 'e', 'f'], dtype=pl.Categorical)
})

df1.vstack(df2) # error!! df1 and df2 use different string caches
```
If you get `df1` and `df2` from separate processes, your only recourse is the following:

```python
with pl.StringCache():
    df1 = df1.with_columns(col('a').cast(pl.Utf8).cast(pl.Categorical))
    df2 = df2.with_columns(col('a').cast(pl.Utf8).cast(pl.Categorical))

df1.vstack(df2) # works!
```

This seems a bit wasteful to do a full conversion. It would be nice to able to do:

```python
pl.synchronize_categoricals((df1, df2, ...))
```
...or something similar.

**Comment by alexander-beedie** [comment]
Could perhaps also consider something like this...
```
with pl.StringCache( synchronise=True ):
    df1.vstack( df2 )
```

**Comment by mcrumiller** [comment]
@alexander-beedie I like that. I would also like an additional method to simply update the revmap to the current cache, as in:

```python
# df1.vstack(df2) # Error: different caches

with pl.StringCache(synchroni[s|z]e=True): # yes I'm from America :(
    df1 = df1.cat.synchronize()
    df2 = df2.cat.synchronize()

df1.vstack(df2) # OK
```

**Comment by deanm0000** [comment]
I like the feature. I hope it gets implemented. In the interim there are other workarounds, in particular for memory constrained situations. You can save each df to a parquet file then reopen each in the same string cache context.

If you're joining rather than stacking then pyarrow is happy to join 2 tables by a categorical column that isn't in sync.
