### ISSUE TITLE
Add pl.others() as a way to select "the rest of the columns"

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#10394]
### Problem description

Just a minor feature request, but I often find myself doing 

```python
df.select('col1', 'col2', pl.all().exclude('col1', 'col2'))
```

I think it'd be nice to have

```python
df.select('col1', 'col2', pl.others())
```

Assuming this is easy to implement internally.

There are also some more... complex usecases:

```python
df.select(cs.by_dtype(pl.Float64).cast(pl.Float32), cs.by_dtype(pl.Utf8).cast(pl.Categorical), pl.others())
```

Not sure about the name, maybe `pl.other()`, `pl.others()`, `pl.other_columns()`
And maybe this should be in the `selectors` namespace.

Thoughts?

**Comment by mcrumiller** [comment]
This is identical to `pl.all()` in which you want to change the column ordering, correct?  @alexander-beedie knowing that, would something like a `pl.all(show_first=["col1", "col2"])` be achievable? Or something along that route?

@mkleinbort-ic for the time being, you could always register `.put_first` in the dataframe namespace as follows:

```python
@pl.api.register_dataframe_namespace("order")
class SortedFrame:
    def __init__(self, df: pl.DataFrame):
        self._df = df
    def with_first(self, columns: str | tuple[str] | list[str]):
        columns = [columns] if isinstance(columns, str) else columns
        return self._df.select(
            *columns,
            *set(self._df.columns).difference(columns)
        )

df = pl.DataFrame({
    'a': [1, 2, 3, 4],
    'b': [1, 2, 3, 4],
    'c': [1, 2, 3, 4]
})
df.order.with_first('b')
```
```
shape: (4, 3)
┌─────┬─────┬─────┐
│ b   ┆ a   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   │
│ 2   ┆ 2   ┆ 2   │
│ 3   ┆ 3   ┆ 3   │
│ 4   ┆ 4   ┆ 4   │
└─────┴─────┴─────┘
```

**Comment by mkleinbort-ic** [comment]
Yes, I have something similar: 

```python
def shift_columns_left(df:pl.DataFrame, columns:list[str])->pl.DataFrame:
    'Reorders the columns in df so that the specified columns appear first.'
    return df.select([pl.col(columns), pl.all().exclude(columns)])
```

Also,  `pl.all(show_first=["col1", "col2"])` is pretty good, though something feels odd about adding keywords to such a pure expression. All things being the same I think I'd prefer a `pl.others()`

**Comment by stinodego** [comment]
Just FYI, you don't have to type out `pl.all().exclude('col1', 'col2')`. Simply `pl.exclude('col1', 'col2')` is the same thing, as stated in the [exclude docs](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.exclude.html).

On topic, I don't like the suggestion of `pl.others` or similar. The expression would magically depend on other inputs to the same function (`select` or other). That is the type of magic I am not fond of. I'm afraid this will create many ugly edge cases.

**Comment by alexander-beedie** [comment]
Indeed, this doesn't work well/obviously as soon as you have to interact with _expressions_ rather than _columns_. For example, what is the right thing to do in this case:
```
df.select( (pl.col('a') * pl.col('b')).alias('c'), pl.others() )
```
We have used `a` and `b`, but in a compound fashion - are they part of `others` or not? If there was already a `c`, have we replaced it (in which case would `others` automatically exclude the existing one), or is it a duplicate column error?

While `df.select('col1', 'col2', pl.all().exclude('col1', 'col2'))` is a bit longer to type, it's also extremely clear what is happening, and doesn't give rise to any questions like these ;)

**Comment by stinodego** [comment]
> A cleaner solution which doesn't have the same issues might be something like a reorder_columns(...) method at the frame level; I could see that working quite well thinking

I don't think it's really worth the extra API surface. If you need to reorder some columns, it's very easy to write your own helper function to do so, as shown in this thread.

**Comment by mkleinbort-ic** [comment]
Indeed.

Logically to me that HAS to be equivalent to

```python
df.with_columns(c = pl.col('a') * pl.col('b'))
```

The way I'd implement it FYI would be:

```python
df.select(*{some expressions}, pl.other())

# is syntactic surgar for 

df.select(*{some expressions}, [col for col in df.columns if col not in df.select(*{some expressions}).colums])
```

In your example:

```python
expr = (pl.col('a') * pl.col('b')).alias('c')
df_ans = df.select(expr , [col for col in df.columns if col not in df.select(expr).colums])
```

**Comment by stinodego** [comment]
Okay, I'll be closing this as 'not planned'.

If you have any super convincing arguments to the contrary, feel free to post them and we may re-open.

**Comment by mkleinbort-ic** [comment]
Not super convincing but today I wrote a unit test to make sure that:

```python
df.select(cs.temporal(), cs.string(), cs.numeric()) # Just reordering columns by data type
```

Did not drop any columns.

The intended business logic was: 
```python
df.select(cs.temporal(), cs.string(), cs.numeric(), cs.anything_else()) # Just reordering columns by data type
```
