### ISSUE TITLE
scan_parquet from io.BytesIO()

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#10413]
### Problem description

Add ability to accept io.BytesIO() as source parameter for `scan_parquet`. As for now, it accepts only a path to file/s.
This feature may be useful in cases when your program receives parquet through rest API or socket, directly into memory.

**Comment by ritchie46** [comment]
I am pretty sure that this is a duplicat. :thinking:

**Comment by s-b90** [comment]
True, I'm sorry. I've found some related issues #4950 #9511. They all are about `scan_csv` but you definitely can close this as a duplicate. Just don't forget about parquet also :)

**Comment by Object905** [comment]
It would also be great if scan_* and read_* functions had similar input "type" for files.
Also it will be nice so that they accepted list of BytesIO or path-like, to process them in parallel like with glob pattern.

**Comment by adamgreg** [comment]
My application has Parquet embedded as BLOBs in SQL tables, and processes and combines them lazily. I would love to see support for this - at the moment I have to use `read_parquet()` and miss out on pushdown optimisations.

**Comment by aberres** [comment]
A similar use case here. We have a bunch of Parquet files in memory I want to work with, without having all of them in memory at the same time.

**Comment by shoz** [comment]
I would be very happy with this improvement.  I have about a million parquet files stored as binaries in Redis and I want to read them as LazyFrame to save memory space.

**Comment by HWiese1980** [comment]
This is still open. Has here been progress? I need this functionality too.

**Comment by cmdlineluser** [comment]
@HWiese1980 Coincidentally, it was added on main a few hours ago https://github.com/pola-rs/polars/pull/18532

**Comment by HWiese1980** [comment]
Hah! That's quite the timing! :-D Thanks!

**Comment by s-b90** [comment]
Can confirm that everything is working. Thanks @coastalwhite!
