### ISSUE TITLE
py-polars.enable_string_cache() does not simply turn on/off

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/polars#10425]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> pl.using_string_cache()
False
>>> pl.enable_string_cache(True)
>>> pl.enable_string_cache(True) # double-tap True
>>> pl.enable_string_cache(False)
>>> pl.using_string_cache()
True # NOT False !
>>> pl.enable_string_cache(False)  #double-tap False
>>> pl.using_string_cache()
False # now it is False
```

### Issue description

[in rust-polars ](https://github.com/pola-rs/polars/blob/c4ac8597b01725dd4d3562396bb5230ec3a71517/crates/polars-core/src/chunked_array/logical/categorical/stringcache.rs#L67) have some RAII approach to enable/disable. However this is not fully behavior-safe implemented reference counting, and each thread is required to only enable once and then disable to get reference counting right. The py-function has wrapped enable_string_cache() as if it was an on/off switch.

[in py-polars the docs simply states pl.enable_string_cache(toggle) is an on/off switch](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.enable_string_cache.html#polars-enable-string-cache)

maybe enable_string_cache() should not be a public function as it has global side effects, and any use should go
through `IUseStringCache`which is probably the RAII behaviour-safe version intended for use.

### Expected behavior

It depends, but if pl.enable_string_cache(toggle) should be a simple on/off  switch, then 

```python
>>> import polars as pl
>>> pl.using_string_cache()
False
>>> pl.enable_string_cache(True)
>>> pl.enable_string_cache(True)
>>> pl.enable_string_cache(False)
>>> pl.using_string_cache()
False
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            macOS-12.6.6-x86_64-i386-64bit
Python:              3.9.17 (main, Jun 20 2023, 17:04:52) 
[Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I think we should document remove boolean the argument. That way you can only turn it on, or use the context manager, which is RAII.

**Comment by mcrumiller** [comment]
Yeah, I mentioned in #8631 that it seems awkward having "enable" and "True" together, it feels redundant. If the boolean does something, the function should be named `set_string_cache(True|False)`, or the boolean should be removed entirely.

**Comment by sorhawell** [comment]
@mcrumiller  I agree `set_string_cache()` would be a better name for a switch, but under the hood it is[ actually a reference counter](https://github.com/pola-rs/polars/blob/c4ac8597b01725dd4d3562396bb5230ec3a71517/crates/polars-core/src/chunked_array/logical/categorical/stringcache.rs#L67). Above zero means someone still thinks the string_cache should be active.

It could be `enable_string_cache()` only increased and thereby forces the string_cache always "on".
But then also exposing the public rust function `reset_string_cache()` with brings the counter to zero and cleans up. 

Then documentation should warn the user these function are very crude, and advice the user to prefer any context_manager like `with_string_cache()` or a function-decorator or similar.

**Comment by ritchie46** [comment]
Yes, I think we should call it enable and expose a reset. Care to make a PR?

**Comment by sorhawell** [comment]
I will check in on this issue in a week when I return from vacation :)

**Comment by mcrumiller** [comment]
So out of curiosity, does each `with pl.StringCache()` context have its own cache, or is it that a series uses its own string cache or the global one?

Edit: from testing, looks like it's the former. I'm a bit confused now, it seems like:

1. You can use enable a "global" string cache, shared by all categoricals that are made after this is enabled;
2. You can use a context manager, in which case all strings within that manager use their own isolated string cache; or
3. You can use nothing, in which case a series will have its own string mapping and nobody else can interact with it.

Is the "global" string cache a special cache compared to those created with a context manager?

**Comment by deanm0000** [comment]
As long as the string cache is getting revisited, does it make sense to introduce an environment variable like POLARS_STRING_CACHE_ENABLED that, when set to True at import time would turn the global string cache on?

I know there has been some contention between people wanting it always on so they don't have to explicitly turn it on and people who don't want to keep seeing questions about joins not working against those who want Mac performance by default.

I am ambivalent on the default debate but the environment variable approach seems like it'd appease everyone.

**Comment by mcrumiller** [comment]
@deanm0000, while I'm in the camp of wanting to always using the global string cache, I don't like the idea of an environmental variable that changes actual behavior of polars. Env vars should change *how* polars does operations (e.g. prevent partitioning, or changing print behavior), but IMO it shouldn't change *what* polars does. This could lead to really annoying reproducibility problems: if someone else runs the exact same code, there's not even the *expectation* that it will run the same.

**Comment by sorhawell** [comment]
I apologize for unmet promises. I have changed job and cannot for time being contribute.

**Comment by stinodego** [comment]
No problem at all, of course. Good luck with the new job!
