### ISSUE TITLE
Rename apply -> apply_elementwise for greater separation from pandas?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#10423]
This has come up at the pandas sprint - I hadn't realised how many inconstencies there are in `pandas.Series.apply` https://github.com/pandas-dev/pandas/issues/52140 . Everyone agrees that it's super-inconsistent, the question is just what to do about it
A potential solution being discussed is to make `.apply` always operate on the whole series, whereas `.map` will always operate elementwise

If that is accepted, then `pandas.Series.apply` will be a bit like `polars.Expr.map`, and `pandas.Series.map` will be a bit like `polars.Series.apply`

To reduce current and future confusion, maybe polars should have separate names, so that people don't make a (false) analogy to pandas?

Like
- `polars.Series.apply` -> `polars.series.apply_elementwise`
- `polars.Expr.map` -> `polars.Expr.map_arraywise`
?

I'm not sure about the solution, I just wanted to suggest making a clear separation from the pandas API here so that polars won't have to rename in the future if/when the solution to the pandas issue mentioned above goes through

**Comment by ritchie46** [comment]
They will be swapped around. 😅

Apply works on the smallest element unit of that operation. In select that are scalars, but during a groupby, those elements are series containing that group.

I am not entirely sure what good names would be.

**Comment by cmdlineluser** [comment]
Just looking at the current docs:
Name|Description
:-|:-
`polars.Expr.apply`|Apply a custom/user-defined function (UDF) in a GroupBy or Projection context.
`polars.Expr.map`|Apply a custom python function to a Series or sequence of Series.

`.map` also has this note:

> If you want to apply a custom function elementwise over single values, see [apply()](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.apply.html#polars.apply). A use case for map is when you want to transform an expression with a third-party library.

(There's also `.map_dict`, which is an elementwise operation.)

---

Even though they are somewhat related, I get the feeling that the `.apply` part should be its own thing. 

(It may also benefit from not having apply in its name to further distance itself from existing pandas `.apply` code examples out there.)

I lack naming skills, `.function` was my best attempt.
```python
df.with_columns(
   pl.col("foo").function(lambda x: ...)
)
```
Name|Description
:-|:-
`pl.Expr.function`|Pass values to a custom/user-defined function. In a select context, the function is called once per row. In a groupby context <sup>(`.groupby`, `.over`)</sup>, the function is called once per group.

Perhaps `udf` is also a consideration, but having the `df` substring bugs me for some reason.
```python
df.with_columns(
   pl.col("foo").udf(lambda x: ...)
)
```

**Comment by MarcoGorelli** [comment]
this has already happened, so closing
