### ISSUE TITLE
request scan_dataset() functionality 

### ISSUE THREAD

**Issue by MatthewRGonzalez** [pola-rs/polars#10438]
### Problem description

I noticed a discussion re: group aggregations on arrow datasets at https://github.com/apache/arrow/issues/13747. @ritchie46 noted:
> Polars is not able to push down the filter into a pyarrow dataset. Only in readers directly implemented by polars. (scan_parquet, scan_csv, etc). So that means the dataset is first completely read in memory. We could see if we can translate out predicate to filters pyarrow understands.

As an extension of this discussion, I propose a `scan_dataset()` function that would operate similarly to `scan_parquet()`. This function would add value to the ecosystem by improving the speed of operations akin to `do_polar()`:

```
# copied from https://github.com/apache/arrow/issues/13747. 

# pyarrow 8.0.0
# duckdb 0.5.1
# polars 0.14.18
ib = dataset("install-base-from-vdw-standard/", filesystem=fs, partitioning="hive")

ib.count_rows()
# 1415259797
ib.schema
"""
bev: bool
market: int16
function_group: int32
part: int32
kdp: bool
kdp_accessory: bool
yearweek: int32
qty_part: int32
vehicle_type: int32
model_year: int32
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [{"name": null, "field_n' + 1081
"""

def do_duckdb():
    sql = """
        SELECT i.part,
               i.bev,
               i.market,
               kdp_accessory,                   
               yearweek,
               SUM(i.qty_part) as qty_part_sum,
        FROM ib i
        WHERE vehicle_type=536
        GROUP BY
           i.part,
           i.bev,
           i.market,
           i.kdp_accessory,
           yearweek
    """
    conn = duckdb.connect(":memory:")
    result = conn.execute(sql)
    table = result.fetch_arrow_table()
    return table


def do_polar():
    table = (
        pl.scan_ds(ib)
        .filter("vehicle_type" == 536)
        .groupby(["part", "bev", "market", "kdp_accessory", "yearweek"])
        .agg(pl.col("qty_part").sum())
        .collect()
        .to_arrow()
    )
    return table

%time table = do_duckdb()
# memory consumption increased temporarily with 2GB, 18.8s

%time table = do_polar()
# memory consumption increased slowly to fill almost all memory (32GB) before
# normalizing, 4min 54s
```

**Comment by cjackal** [comment]
Is [`polars.scan_pyarrow_dataset`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_pyarrow_dataset.html#polars-scan-pyarrow-dataset) what you seek?

**Comment by alexander-beedie** [comment]
> Is [`polars.scan_pyarrow_dataset`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_pyarrow_dataset.html#polars-scan-pyarrow-dataset) what you seek?

That's the one  ;)

**Comment by MatthewRGonzalez** [comment]
That's exactly what I was looking for. Sorry for missing it in the docs. Thank you!
