### ISSUE TITLE
`.groupby.last` and `groupby.mean` are much slower on windows

### ISSUE THREAD

**Issue by Elvynzs** [pola-rs/polars#10435]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl


data = pl.Series(name="somedata", values=np.random.randn(10**6))
gp = pl.Series(name="somegroups", values=np.repeat(np.arange(10), 10**5,))
df = pl.concat([data.to_frame(), gp.to_frame()], how="horizontal")
%timeit df.groupby("somegroups").tail(1) # 1.42 ms ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
%timeit df.groupby("somegroups").last() # 69.9 ms ± 5.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### Issue description

If you run the above code, you'll notice that using  `.last` to aggregate the results is anomarly slow.

On my computer, `.tail(1)` takes about 2ms, but `.last()` takes 70ms.

_(I also noticed #10432 being reported earlier today, which is a different issue but may have a similar underlying cause)_

### Expected behavior

I expected both methods to perform similarly, but using `.last` is unexpectedly slow (nearly 50x slower).

Also, it may be uncorrelated, but I noticed that the following code does not work :

```python
... #Same code as before
df.groupby(gp.alias("outsidegroup")).tail(1) #Crashes : InvalidOperationError: `explode` operation not supported for dtype `i32`
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.0
numpy:               1.24.2
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.12
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

--------------

**Edit** : Seeing the replies, I wondered if results would be better using WSL. They are, but last is still 2x slower.

> 4.18 ms ± 251 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
> 9.35 ms ± 99.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**UPDATE 1** : 

From my testing, this issue also affects `groupby.mean` (and possibly other methods). When `groupby.mean` or `groupby.last` are ran on Windows, they are slower than when ran through WSL (Windows Subsystem for Linux), or through native Linux, on the same PC. See https://github.com/pola-rs/polars/issues/10435#issuecomment-1677585820.
However more testing would be required. In my case, the issue is mostly solved if use polars in a Linux environment, however https://github.com/pola-rs/polars/issues/10435#issuecomment-1676239236 reports slow code even in Linux

**Comment by cmdlineluser** [comment]
My results:
```
2.36 ms ± 37.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.91 ms ± 34 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]
```

**Comment by taozuoqiao** [comment]
I have similar results:
```
2.77 ms ± 79.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
76.8 ms ± 6.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.19
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

**Comment by ritchie46** [comment]
My results: 

```
2.23 ms ± 92.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.11 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

We run the `last` groupby on the streaming engine, as we expect that one to be faster for this low cardinality result. You can force polars to use the default engine by setting `POLARS_NO_PARTITION=1`. 

However, looking at the results, it seems to be a windows issue. As Both macOS and linux have comparable results. Maybe the windows `mimalloc` is not properly configured to deal with our heap allocations? Could someone try tuning mimalloc and see if that improves it?

**Comment by Elvynzs** [comment]
So @ritchie46 answer made me curious, so I went ahead and quickly tested the same code using WSL.

Two key results :
* **The "slow code" runs faster on WSL than on Windows**
* **I think this issue affects all aggregations with a low cardinality**.
  * I tested `.groupby("somegroups").mean()` and it is much faster through WSL (60ms on windows vs 6.39ms via WSL)

**Comment by Elvynzs** [comment]
I have checked today, on two computers with versions `0.20.20`, `0.20.30`. In both cases, the `.last()` version is faster, it seems that this issue is solved now, so I'll close the issue.

.tail(1) : 3.43 ms ± 55.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
.last() : 472 µs ± 9.35 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
