### ISSUE TITLE
Recommended profiler that can track polars memory allocations?

### ISSUE THREAD

**Issue by arogozhnikov** [pola-rs/polars#10434]
Hi, I am facing sharp peaks of memory usage in application (memory overfills so swap is used). 

Application uses polars in a number of places, and I believe this is the cause, but can't track a particular place where this happens.

I've tried `fil_profiler` and `memray` without much success: either profiler crashes, or can't identify frame source `unnamed (unnamed)`.

**Comment by ritchie46** [comment]
I would take a look at heaptrack.

If you want to understand more of what in polars causes it (if polars is the culprit), you need to compile with debug symbols.

**Comment by arogozhnikov** [comment]
tried independently several operations, and yes, this was polars.

> I would take a look at heaptrack.

does it work with python? see no mention of that.

**Comment by arogozhnikov** [comment]
>  you need to compile with debug symbols.

ah, good to know. So this was expected 🙂

**Comment by ritchie46** [comment]
> does it work with python? see no mention of that.

It shows the symbols of the compiled functions that allocate. The language that runs it doesn't matter.

**Comment by ritchie46** [comment]
If you've got an MWE, we can take a look.

**Comment by arogozhnikov** [comment]
> If you've got an MWE, we can take a look.

I've been counting total number of rows in a weird way, I don't think that's case worth digging. I've changed to pl.count() and it worked with small footprint


> It shows the symbols of the compiled functions that allocate. The language that runs it doesn't matter.

thank you, will try next time I'll run into memory issues
