### ISSUE TITLE
pyo3_runtime.PanicException on polars.DataFrame.apply

### ISSUE THREAD

**Issue by grbu** [pola-rs/polars#10448]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```import polars as pl

if __name__ == '__main__':
    good_df1 = pl.DataFrame(data={'id': 1, 'data': 1})
    print(good_df1)
    good_df2 = pl.DataFrame(data={'id': [1, 2], 'data': [1, 1]})
    print(good_df2)
    bad_df = pl.DataFrame(data={'id': [1, 2], 'data': 1})
    print(bad_df)
    apply_res1 = good_df1.apply(lambda t: (t[0],))
    print(apply_res1)
    apply_res2 = good_df2.apply(lambda t: (t[0],))
    print(apply_res2)
    causes_exception = bad_df.apply(lambda t: (t[0],))
    print(causes_exception)
```

### Issue description

I've ran into an issue with polars.DataFrame.apply, though I suspect the issue isn't specific to apply function and is caused by a malformed dataframe.

When I run the code in the example with RUST_BACKTRACE=full I get the following output:
shape: (1, 2)
┌─────┬──────┐
│ id  ┆ data │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ 1    │
└─────┴──────┘
shape: (2, 2)
┌─────┬──────┐
│ id  ┆ data │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ 1    │
│ 2   ┆ 1    │
└─────┴──────┘
shape: (2, 2)
┌─────┬──────┐
│ id  ┆ data │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ 1    │
│ 2   ┆ 1    │
└─────┴──────┘
shape: (1, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ i64      │
╞══════════╡
│ 1        │
└──────────┘
shape: (2, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ i64      │
╞══════════╡
│ 1        │
│ 2        │
└──────────┘
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`: impl error', D:\a\polars\polars\polars\polars-core\src\series\iterator.rs:70:9
stack backtrace:
   0:     0x7ffb1c4ca67f - ffi_select_with_compiled_path
   1:     0x7ffb1a83427b - BrotliDecoderVersion
   2:     0x7ffb1c4b9c4f - ffi_select_with_compiled_path
   3:     0x7ffb1c4ccc8b - ffi_select_with_compiled_path
   4:     0x7ffb1c4cc879 - ffi_select_with_compiled_path
   5:     0x7ffb1c4cd8ea - ffi_select_with_compiled_path
   6:     0x7ffb1c4cd365 - ffi_select_with_compiled_path
   7:     0x7ffb1c4cd2b9 - ffi_select_with_compiled_path
   8:     0x7ffb1c4cd2a4 - ffi_select_with_compiled_path
   9:     0x7ffb1c58cce5 - ffi_select_with_compiled_path
  10:     0x7ffb1c58d0e9 - ffi_select_with_compiled_path
  11:     0x7ffb1c59316a - ffi_select_with_compiled_path
  12:     0x7ffb19ff7b7d - <unknown>
  13:     0x7ffb19ff4062 - <unknown>
  14:     0x7ffb1a02a893 - <unknown>
  15:     0x7ffb19ab39dd - <unknown>
  16:     0x7ffb1a2ab2a1 - PyInit_polars
  17:     0x7ffb64ff9560 - PyMem_RawMalloc
  18:     0x7ffb64fbc1f1 - PyEval_EvalFrameDefault
  19:     0x7ffb64fbc7c7 - PyEval_EvalFrameDefault
  20:     0x7ffb64f9d3b9 - PyMapping_Check
  21:     0x7ffb6501b656 - PyEval_EvalCode
  22:     0x7ffb6501b4df - PyArena_Free
  23:     0x7ffb6501b3df - PyArena_Free
  24:     0x7ffb64fbd115 - PyEval_EvalFrameDefault
  25:     0x7ffb64fba937 - PyFunction_Vectorcall
  26:     0x7ffb64fbd1fe - PyEval_EvalFrameDefault
  27:     0x7ffb64fba937 - PyFunction_Vectorcall
  28:     0x7ffb64fc1c61 - PyEval_EvalFrameDefault
  29:     0x7ffb64f9d3b9 - PyMapping_Check
  30:     0x7ffb6501b656 - PyEval_EvalCode
  31:     0x7ffb6501b4df - PyArena_Free
  32:     0x7ffb6501b3df - PyArena_Free
  33:     0x7ffb64fbd115 - PyEval_EvalFrameDefault
  34:     0x7ffb650106eb - PyObject_IsTrue
  35:     0x7ffb650e408d - PyOS_getsig
  36:     0x7ffb64fc33b1 - PyEval_EvalFrameDefault
  37:     0x7ffb650106eb - PyObject_IsTrue
  38:     0x7ffb650e408d - PyOS_getsig
  39:     0x7ffb64fc33b1 - PyEval_EvalFrameDefault
  40:     0x7ffb650106eb - PyObject_IsTrue
  41:     0x7ffb64f9c963 - PyCapsule_GetPointer
  42:     0x7ffb64ff92ed - PyMem_RawMalloc
  43:     0x7ffb64fbc1f1 - PyEval_EvalFrameDefault
  44:     0x7ffb64fba937 - PyFunction_Vectorcall
  45:     0x7ffb64fbbe94 - PyEval_EvalFrameDefault
  46:     0x7ffb64fbc7c7 - PyEval_EvalFrameDefault
  47:     0x7ffb64fbe512 - PyEval_EvalFrameDefault
  48:     0x7ffb64fbc7c7 - PyEval_EvalFrameDefault
  49:     0x7ffb64fbc7c7 - PyEval_EvalFrameDefault
  50:     0x7ffb64fbc7c7 - PyEval_EvalFrameDefault
  51:     0x7ffb64fba937 - PyFunction_Vectorcall
  52:     0x7ffb64fbbe94 - PyEval_EvalFrameDefault
  53:     0x7ffb64fba937 - PyFunction_Vectorcall
  54:     0x7ffb64fbd1fe - PyEval_EvalFrameDefault
  55:     0x7ffb64f9d3b9 - PyMapping_Check
  56:     0x7ffb6501b656 - PyEval_EvalCode
  57:     0x7ffb6501b242 - PyArena_Free
  58:     0x7ffb6501b1c2 - PyArena_Free
  59:     0x7ffb650e9b84 - PyRun_SimpleFileObject
  60:     0x7ffb650e98a9 - PyRun_SimpleFileObject
  61:     0x7ffb650e96ac - PyRun_AnyFileObject
  62:     0x7ffb650774c7 - PySys_FormatStderr
  63:     0x7ffb650775e3 - PySys_FormatStderr
  64:     0x7ffb65078890 - Py_RunMain
  65:     0x7ffb65078721 - Py_RunMain
  66:     0x7ffb65077e0d - Py_Main
  67:     0x7ff697731230 - <unknown>
  68:     0x7ffbe2ed55a0 - BaseThreadInitThunk
  69:     0x7ffbe46e485b - RtlUserThreadStart
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `2`,
 right: `1`: impl error

The first 2 dataframes do not cause an issue, bad_df passes initialization and seems to hold the same data as good_df2 but an exception is thrown when calling the apply function.

### Expected behavior

If the dataframe is malformed it should fail on init, if it is valid it should not fail on apply.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.15
Index type:  UInt32
Platform:    Windows-10-10.0.22000-SP0
Python:      3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
----Optional dependencies----
numpy:       1.24.4
pandas:      2.0.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.2
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems this may have already been fixed, I get no exception using the latest version: `0.18.13`

**Comment by grbu** [comment]
Yes, you are correct. Thank you and sorry for the inconvenience.
