### ISSUE TITLE
ColumnNotFound when CSE takes effect

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10441]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Enable `comm_subexpr_elim`. 

Run the following code:

```rust
let df = df!("a" => [1,2,3], "b" => [3,2,1])?;
let lazy_frame = df.lazy().select(
               [col("a").sum() + col("a").sum() + col("b").sum()]
               ).collect()?;
```

You will get `Error: ColumnNotFound(ErrString("b"))`.

### Issue description

Through some investigation, I have found that this is due to the `alp's schema(i.e. project's schema)` is used when `find_cse`:

https://github.com/pola-rs/polars/blob/6634621bff01a0c2006c576c473b38c7a98741d1/crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs#L657-L670

This will prevent us from finding `b's Field` when we alias the expression:
https://github.com/pola-rs/polars/blob/6634621bff01a0c2006c576c473b38c7a98741d1/crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs#L604-L608

IIUC, this can be fixed by pass the `input schema` instead of `project schema / current alp's schema` to `find_cse`. 
BTW, for `HStack` and `Aggregate`, the same applies.

```rust
let input_schema = lp_arena.get(input.clone()).schema(lp_arena);
```

### Expected behavior

Get the same result as when `comm_subexpr_elim` is not disabled.
```
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 18  │
└─────┘
```

### Installed versions

<details>

Latetest `main` branch(commit: 6634621b).

</details>

**Comment by reswqa** [comment]
If the above analysis is correct, I am willing to submit PR to fix it and look forward to your reply.

**Comment by ritchie46** [comment]
Good catch! Indeed the wrong schema. Fix coming up!
