### ISSUE TITLE
Update "scan_csv" documentation

### ISSUE THREAD

**Issue by ndeen** [pola-rs/polars#10440]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
file_path = filepath.csv

df = pl.scan_csv(file_path, separator='|').collect()

df2 = pl.scan_csv(file_path, sep='|').collect()
```

### Issue description

The documentation is wrong: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_csv.html

we should not be using 'separator' we should be using 'sep'. but the documentation doesn't tell us this.

### Expected behavior

"scan_csv() got an unexpected keyword argument 'separator'"

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Windows-10-10.0.17763-SP0
Python: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:09:20) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.22.3
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.3
```

</details>

**Comment by cmdlineluser** [comment]
Your version of polars is `0.16.1` - the docs reflect the latest version of polars `0.18.3`.

`sep` has since been renamed to `separator`

**Comment by alexander-beedie** [comment]
Closing; as @cmdlineuser says, you should probably update to a more recent polars release. The docs are correct for the current version (this parameter name was updated several months ago, in early March)  ;)
