### ISSUE TITLE
The semantics of VisitRecursion::Skip are a bit vague or not fully adhered to

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10451]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Enable `comm_subexpr_elim`.

```rust
let df = df!("a" => [1,2,3], "b" => [3,2,1])?;
let lazy_frame = df.lazy().select(
            [col("b").sum() + col("a").sum().over([col("b")]) + col("b").sum()]
        ).collect()?;
```

### Issue description

I expect `col("b").sum()` to be recognized as a common subexpression, but it does not. Is it possible that this is not meant to be reused by design? If that's the case, feel free to close this and the corresponding pull request. 😆 

Through some investigation, I found that this is because we did not traverse the sibling expression of window expr (i.e. `col("b").sum()`). Of course, this is because we will tell the visitor `VisitRecursion::Skip` to prevent it from accessing this one.

We can see in the comments that `Skip` should skip applying op on children. 

https://github.com/pola-rs/polars/blob/befaa30b1a1b3e26e72085d915223c0b4e469998/crates/polars-plan/src/logical_plan/visitor/mod.rs#L17-L18

But In fact, we also prevented recursive access to sibling expressions. I'm a bit confused, should `Skip` prevent the traversal of sibling expr and the subsequent `post-visit` of this expr?

https://github.com/pola-rs/polars/blob/befaa30b1a1b3e26e72085d915223c0b4e469998/crates/polars-plan/src/logical_plan/visitor/expr.rs#L15-L23

https://github.com/pola-rs/polars/blob/befaa30b1a1b3e26e72085d915223c0b4e469998/crates/polars-plan/src/logical_plan/visitor/visitors.rs#L23-L31

### Expected behavior

Maybe `col("b").sum()` should be reusable?

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by ritchie46** [comment]
No, I believe the `Skip` behavior is correct. We don't want to apply cse within window expressions. As those subexpressions are not equal. Some are applied in a groupby context, while others are executed in a select context.

**Comment by reswqa** [comment]
> We don't want to apply cse within window expressions

I agree that the sub-expr of window should not be applied to CSE. What I want to express is that the expression on the left side of Brinary (+) has been ignored (due to the heterosexual washing of window)

**Comment by ritchie46** [comment]
Right, I understand. Though I don't think your proposed changes in #10452 are the way to go. As it now has `Continue` behavior.

I would have to take a better look.

**Comment by reswqa** [comment]
> As it now has Continue behavior.

Actually, they are different because I did not modify the logic here:

https://github.com/pola-rs/polars/blob/befaa30b1a1b3e26e72085d915223c0b4e469998/crates/polars-plan/src/logical_plan/visitor/visitors.rs#L15 -L21

That is to say, `Skip` will only skip visiting to childs, while `Continue` will not. For the access of sibling exprs, it now has Continue behavior. Because the comments states that `Skip` means `keep recursive but skip applying op on the children`.

**Comment by ritchie46** [comment]
Ok, thanks for the clarification. I will take a better look first think tomorrow morning then. It is getting later here. :)

Semantically, I agree with you. I just have to ensure the code is correct.

**Comment by reswqa** [comment]
>  It is getting later here. :)

Ah, I'm really sorry, I didn't notice your time zone. Thank you for your prompt reply!

**Comment by ritchie46** [comment]
No worries! Until tomorrow. :)
