### ISSUE TITLE
Floating `-0.0` != `0.0` in `groupby`, `n_unique` and `value_counts`

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#10457]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_series_equal, assert_frame_equal

s = pl.Series([0.0, -0.0], dtype=pl.Float64)

# passes
assert_series_equal(s, s.abs())

# all asserts below this line fail
assert s.n_unique() == 1
assert_frame_equal(s.value_counts(), s.abs().value_counts())
df = s.rename("s").to_frame()
assert len(list(df.groupby("s"))) == len(list(df.groupby(pl.col("s").abs())))

```

### Issue description

`0.0` is keyed to a different group from `-0.0` in key-based operations.

### Expected behavior

Floating `0.0` should be treated as equal to `-0.0` for any key-based operation, including `groupby`, `n_unique` and `value_counts`.

For `.hash()`, it currently also produces different hashes for `0.0` and `-0.0`, however it seems like `pandas` and `numpy` also have this behavior. If `polars` is to match `pandas`/`numpy`, then the behavior of `.hash()` should probably be left as-is.

```python
import polars as pl
import pandas as pd
import numpy as np
from pandas.util import hash_pandas_object, hash_array

print(pl.Series([0.0, -0.0], dtype=pl.Float64).hash())
# shape: (2,)
# Series: '' [u64]
# [
#         0
#         12405440148778172310
# ]
print(hash_pandas_object(pd.Series([0.0, -0.0], dtype="float64")))
# 0    3713087409444908179
# 1    7265526215548662568
# dtype: uint64
print(hash_array(np.array([0.0, -0.0], dtype="float64")))
# [                  0 2720858781877447050]

```

Additionally, if it helps to determine the behavior that `polars` wants for the sign bit, note that `pandas` follows the sign of the first-seen value during `value_counts` / `groupby`:

```python
import pandas as pd
from pandas.testing import assert_series_equal

s = pd.Series([0.0, -0.0], dtype="float64")

assert s.nunique() == 1
assert_series_equal(s, s.abs())
assert_series_equal(s.value_counts(), s.abs().value_counts())

# 0.0 occurs first
print(s.value_counts())
# 0.0    2
# Name: count, dtype: int64
print(s.groupby(s).indices.keys())
# dict_keys([0.0])

# -0.0 occurs first
print(s[::-1].value_counts())
# -0.0    2
# Name: count, dtype: int64
print(s[::-1].groupby(s[::-1]).indices.keys())
# dict_keys([-0.0])
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:              3.11.4 (main, Jul 13 2023, 14:31:04) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.12
sqlalchemy:          1.4.47
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I would argue you shouldn't group on floating point keys. Because of these hashing properties and floating equality being a concern we don't support the full floating spec in groupby related operations.

We implement it for practicaly reasons, but in a pure sense, I am against this operation on floating point values. They shouldn't even support hash. As they break the hash + equallity expectations.

This is not something that will change.

**Comment by nameexhaustion** [comment]
There are some cases where it is inevitable that we need to group on floating point keys - for example when performing value counts of a column, which is essentially an indirect grouping operation. From a technical perspective, I'd agree that it is correct to consider them different by looking at their memory representations. However, from a numeric view, `-0.0` and `0.0` both have a "zero" value, and should thus be treated as equal to each other.

I'll present the two different behaviors that can apply:
```python
>>> print(df)
shape: (2, 1)
┌──────┐
│ s    │
│ ---  │
│ f64  │
╞══════╡
│ 0.0  │
│ -0.0 │
└──────┘
```
- Current:
```
>>> df["s"].value_counts()
shape: (2, 2)
┌──────┬────────┐
│ s    ┆ counts │
│ ---  ┆ ---    │
│ f64  ┆ u32    │
╞══════╪════════╡
│ 0.0  ┆ 1      │
│ -0.0 ┆ 1      │
└──────┴────────┘
```
- Proposed:
```
>>> duckdb.query("SELECT s, COUNT() AS counts FROM df GROUP BY 1")
┌────────┬────────┐
│   s    │ counts │
│ double │ int64  │
├────────┼────────┤
│    0.0 │      2 │
└────────┴────────┘
```

From a numerical perspective, I'd argue it's preferred to say that the column contains one unique value, the "zero" value, rather than two unique values that are somehow both equal to "zero". And if I were to be presenting to someone about the results of the analysis I do, I would most likely not be showing `-0.0` and `0.0` separately. As such, I'd strongly recommend for the current behavior to be reconsidered - even a function parameter to toggle the behavior.

> The better argument is of course that grouping by floats is intrinsically error-prone. Decimal might be a suitable choice if this is a real use-case, as that has precision guarantees that Float64 does not.

Decimals certainly have higher precision, but I don't believe this has anything to do with precision - this is purely for handling zero-valued floats that have different sign bits.

> They shouldn't even support hash. As they break the hash + equallity expectations.

As a bonus, I can suggest another option for hash equality aside from the one in the issue description, where `-0.0` and `0.0` both hash to the same value:

```
>>> duckdb.query("SELECT s, hash(s) FROM df")
┌────────┬─────────┐
│   s    │ hash(s) │
│ double │ uint64  │
├────────┼─────────┤
│    0.0 │       0 │
│   -0.0 │       0 │
└────────┴─────────┘
```

In fact, this is exactly what `duckdb` (and presumably `pandas`) does as well - https://github.com/duckdb/duckdb/blob/a8ce02cc2e740d8973d26ccdb77d0068c69c9124/src/common/types/hash.cpp#L30C1-L30C1

**Comment by alexander-beedie** [comment]
The suggestion for `Decimal` isn't about precision itself, it's about stability; floating point values are not exact/stable in the same way that `Decimal` values are, hence floating point values not being good candidates for group keys.

**Comment by nameexhaustion** [comment]
If this is accepted - can I give a try at a PR?

**Comment by orlp** [comment]
I have convinced Ritchie that we can cheaply normalize this in the hash, so I'll fix this.
