### ISSUE TITLE
`cast` of `str` to `date` unexpected

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10478]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({
    "int": [0, 1, 2],
    'str': ['0', '1', '2'],
    "date": ["2020-08-21", "2020-08-22", "2020-08-23"],

})with_columns(
    date_int=pl.col('int').cast(pl.Date),
    date_str=pl.col('str').cast(pl.Date),
    date_cast=pl.col('date').cast(pl.Date, strict=False),
    date_parse=pl.col('date').str.to_date(),
)
┌─────┬─────┬────────────┬────────────┬────────────┬───────────┬────────────┐
│ int ┆ str ┆ date       ┆ date_int   ┆ date_str   ┆ date_cast ┆ date_parse │
│ --- ┆ --- ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---        │
│ i64 ┆ str ┆ str        ┆ date       ┆ date       ┆ date      ┆ date       │
╞═════╪═════╪════════════╪════════════╪════════════╪═══════════╪════════════╡
│ 0   ┆ 0   ┆ 2020-08-21 ┆ 1970-01-01 ┆ 1970-01-01 ┆ null      ┆ 2020-08-21 │
│ 1   ┆ 1   ┆ 2020-08-22 ┆ 1970-01-02 ┆ 1970-01-02 ┆ null      ┆ 2020-08-22 │
│ 2   ┆ 2   ┆ 2020-08-23 ┆ 1970-01-03 ┆ 1970-01-03 ┆ null      ┆ 2020-08-23 │
└─────┴─────┴────────────┴────────────┴────────────┴───────────┴────────────┘
```

### Issue description

one of the latest updates allows to `cast` to temporal types like `pl.Date`

However it is not **parsing** (interpreting the str) the column to a date but converting to an integer and using that as the underlaying date value.

### Expected behavior

I expect str column to **parse** values to its correct type instead of to an integer and using that.

In this case I expected the same result as using `.str.to_date`

## Examples

Integer to Date (cast / reinterpret values as date)
- `[0, 1]` -> `[1970-01-01, 1970-01-02]`

String to Date (**parse** strings to date)
- `['0', '1']` -> `[null, null]`: these are not dates! (currently: `[1970-01-01, 1970-01-02]`)
-  `["2020-08-21", "2020-08-22"]` -> `[2020-08-21, 2020-08-22]` (currently: `[null, null]`)

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.14
Index type:          UInt32
Platform:            macOS-13.5-x86_64-i386-64bit
Python:              3.11.4 (main, Jul 25 2023, 17:08:27) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by ritchie46** [comment]
Anybody has the discussion we had on this recently?

Did we already implement this?

**Comment by MarcoGorelli** [comment]
This is the issue, but I don't think it's been implemented yet? https://github.com/pola-rs/polars/issues/9994

**Comment by brayanjuls** [comment]
I am working on this. I am going to send a PR soon.
