### ISSUE TITLE
Add option to include source filename and filepath in dataframe

### ISSUE THREAD

**Issue by D1xieFlatline** [pola-rs/polars#10481]
### Problem description

When reading data from a large number of files, it can be helpful to keep track of the source file for a few reasons:
- Identifying the source of data issues
- Ability to reload a specific file rather than refreshing the entire data set
- Giving users visibility into where data came from

You can always capture the file name/path in a variable and add that to the df after a file is loaded, but this creates extra steps and doesn't seem to work well with globs.

Adding options to include the name/path of source files when a file is read would be a nice quality of life feature.

I propose adding twonew parameters to each file input function:

- include_source_path: If True, includes the file path as an additional column. Default: False
- include_source_name: If True, includes the file name as an additional column. Default: False

**Comment by MarcoGorelli** [comment]
Hey - I think https://github.com/pola-rs/polars/issues/5117#issue-1398256074 would allow you to do this

**Comment by D1xieFlatline** [comment]
Hi Marco, thanks for sharing that enhancement. I think that looks useful, but after reading the linked examples I see two key differences from this suggestion:

- Users need to tag metadata rather than providing an option to capture it automatically when a dataframe is created
- It doesn't appear that metadata is automatically passed on when a dataframe is written to a file

I find that I  add some variation of these three lines every single time I read a file into a dataframe, and I think I'd still need to do some version of that if #5117 was implemented.

```
pl.lit(source_path).alias('SOURCE_FILEPATH'),
pl.lit(source_file).alias('SOURCE_FILENAME'),
pl.lit(source_sheet).alias('SOURCE_SHEETNAME'),
```

**Comment by MarcoGorelli** [comment]
Thanks for your suggestion!

Writing
```python
pl.lit(source_path).alias('SOURCE_FILEPATH'),
pl.lit(source_file).alias('SOURCE_FILENAME'),
```
looks fine, I don't really see the advantage compared with
```
include_source_path=True,
include_source_name=True,
```

Closing then

**Comment by MSKDom** [comment]
I'm sorry but how does the above actually address the concerns? If you are doing it file by file then it is fine, but using bulk read commands do not expose that option.

**Comment by MarcoGorelli** [comment]
Thanks for the ping - reopening for now, will take another look in the week

**Comment by MSKDom** [comment]
Just to clarify and add some context.

I've used CSV bulk read on path e.g. `foo/*/*.csv`. Part of the filename is a timestamp of when it was processed/uploaded, so something like this would be immediately solve the issue as I could simply apply a transform on that column to extract it. 

Instead I had to traverse the file tree, use existing standard library globing to find matches and read file by file. Not a massive workaround, but does hinder the ability to use built in methods as well as making it a bit slower.

**Comment by cmdlineluser** [comment]
I think another valid use case is when using a remote glob? e.g. `scan_csv("http://.../foo/*.csv")` 

In which case the workaround approach is not applicable.

For reference, DuckDB has `filename=true` for its readers

- https://duckdb.org/docs/data/multiple_files/overview#filename

**Comment by MarcoGorelli** [comment]
per discussion: accepted (pending some discussion on the dtype of the `filename` column)

**Comment by deanm0000** [comment]
I wonder if this would intrinsically fix https://github.com/pola-rs/polars/issues/14936 or if that issue would still persist.

**Comment by MSKDom** [comment]
It would persist @deanm0000. This only appends metadata to files, that issue is due to scan/collect timing difference.

**Comment by klwlevy** [comment]
I have the same problem as described by @MSKDom, i.e. having to loop over files to import instead of bulk loading because I need some filename info inside my created DataFrame.

**Comment by pietrolesci** [comment]
+1. Having a functionality similar to DuckDB's `filename` flag would be great!
