### ISSUE TITLE
Lazy evaluation failed in groupby/agg context with pl.when

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#10490]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "a": [1, 1, 2, 2],
        "b": [1, 2, 3, 4],
        "c": [2, 3, 4, 5],
    }
)

df.lazy().groupby("a").agg(
    [
        pl.when(pl.col(col).is_null().all()).then(None).otherwise(1).alias(col)
        for col in ["b", "c"]
    ]
).collect()
```

### Issue description

This relative common statement failed with the latest polars version - 0.18.14, with the following error message:
```
exceptions.ShapeError: shapes of `mask` and `other` are not suitable for `zip_with` operation
```

I am not sure whether it is a real issue with the package or an issue with my environment setup since it is a very common usage of Polars and I cannot believe such an error could be introduced.

But, after checking a few times carefully, it seems like the same code does work on previous polars versions, e.g., 0.18.6, 0.18.13, with exact same machine/os/environment.

### Expected behavior

No error.

### Installed versions

<details>

```
0.18.14
```

</details>

**Comment by ritchie46** [comment]
It is a new optimization that introduced this bug. Will take a look and try to patch.
