### ISSUE TITLE
Multiple filters in LazyFrame on same column throws shape error

### ISSUE THREAD

**Issue by ngriffiths13** [pola-rs/polars#10499]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.from_dict(
    {"a": [None, None, 3, None, 5, 0, 0, 0, 9, 10], "b": [1, 1, 2, 2, 3, 3, 4, 4, 5, 5]}
)

df.lazy().filter((pl.col("a").null_count() < pl.count()).over("b")).filter(
    ((pl.col("a") == 0).sum() < pl.count()).over("b")
).collect()
```

### Issue description

Doing the above causes an error that the second filter has the wrong shape. It is comparing the full DataFrame of length 10 to the filtered shape of 8. 
`ShapeError: filter's length: 10 differs from that of the series: 8`

This same error does not happen if you collect in between the 2 filter calls.

### Expected behavior

I would expect for the DataFrame to filter out both where `b==1` and `b==4` without throwing any errors. 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.3.1-arm64-arm-64bit
Python:              3.11.3 (main, Jul 14 2023, 09:34:26) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.5.0
matplotlib:          3.7.2
numpy:               1.24.3
pandas:              1.5.3
pyarrow:             10.0.1
pydantic:            1.10.12
sqlalchemy:          2.0.15
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
This might be a bug in the optimizer, scoping column references properly can get tricky, especially when doing it symbolically.

For the moment you can do the following, although of course this should be patched:

```
df.lazy().filter((pl.col("a").null_count() + (pl.col("a") == 0).sum() < pl.count()).over("b")).collect()
```

**Comment by reswqa** [comment]
> This might be a bug in the optimizer.

Yes, this is caused by cached group-tuples . The second filter use the `groups` computed by the first filter, but it's does not have enough rows as the previous filtration.
