### ISSUE TITLE
support more datatype specific type hint for Expr/Series/LazyFrame/DataFrame

### ISSUE THREAD

**Issue by Sage0614** [pola-rs/polars#10508]
### Problem description

currently polars support type hint like this:

```
import polars as pl

sample_df = pl.DataFrame({
    "x": ["A","B","C"],
    },
    schema={
        "x": pl.Utf8,
    })

def new_func(x: pl.Expr) -> pl.Expr:
    return x +1

sample_df.select( new_func(pl.col("x")).alias("x2"))

print(sample_df)

```

This type error won't be found until runtime:
`exceptions.ComputeError: arithmetic on string and numeric not allowed, try an explicit cast first`

because the new_func I defined only supposed to work with numeric type, but not string, but they are both Expr anyway.

my question is,
similar to what you can do in python `list[int]` instead of `list[]`

is it possible to support type hint like this:

```
def new_func(x: pl.Expr[pl.Int64]) -> pl.Expr[pl.Int64]:
    return x +1
```

so that when I compose longer expression pipelines, I can use static type checking tools to find the incompatibility earlier?

similarly, we can write function that safely assume the input DataFrame/LazyFrame schema:

`def new_func(df: pl.DataFrame[pl.Utf8,pl.Float64]) ->pl.DataFrame[pl.Boolean] `

Having this will make development data processing pipline based on polars less error prone.

**Comment by alexander-beedie** [comment]
That's an interesting idea... might be possible if we make Expr a Generic type? 🤔 I'll need to experiment a bit to see if this is plausible (if anyone else is a secret Python typing expert, please weight-in! ;)

**Comment by zundertj** [comment]
A similar request has been made before here: https://github.com/pola-rs/polars/issues/3623. In summary, it is not an easy task, and likely will need to compromise on accuracy. In your example, the dataframe constructor would need to infer that it has a Utf8, and that information needs to be carried on the dataframe. Python's typing support is improving each version, but I don't see yet how the general case can be supported here. Also, here you provided the schema explicitly, but often that information is not provided. Especially with data that is coming from a parquet file, a database, or other sources external to the code.

That said, I think for purely expressions it is possible to provide support. This way, you could code up the type logic, by specifying for individual columns there types using expressions, and building more complex expression using those.

Amend `Expr`:

```python
from typing import TypeVar
T = TypeVar("T")

class Expr(Generic[T]):
     ....

    @overload
    def __add__(self: Self[T], other: Self[T]) -> Self[T]:
        ...

    @overload
    def __add__(self: Self[T], other: T) -> Self[T]:
        ...

    def __add__(self, other: Any) -> Self[T]:
        return self._from_pyexpr(self._pyexpr + self._to_pyexpr(other))
```

User code:

```python
from typing import TypeVar
import polars as pl

Int = TypeVar("Int", pl.Int8, pl.Int16, pl.Int32, pl.Int64)

def new_func1(x1: pl.Expr[Int], x2: pl.Expr[Int]) -> pl.Expr[Int]:
    return x1 + x2
```

would pass mypy, whereas the following would not:
```python
def new_func2(x: pl.Expr[Int]) -> pl.Expr[Int]:
    return x + "hello"  # No overload variant of "__add__" of "Expr" matches argument type "str" 
```

This would not work with just the two overloads (but could be added)
```python
def new_func3(x: pl.Expr[Int]) -> pl.Expr[Int]:
    return x + 1   # No overload variant of "__add__" of "Expr" matches argument type "int"
```

But we could instead use normal Python types levering the second overload:
```python
def new_func4(x: pl.Expr[int]) -> pl.Expr[int]:
    return x + 1

def new_func5(x: pl.Expr[str]) -> pl.Expr[str]:
    return x + "hello"
```

It would require a lot of overloads being added to the code base though, and it won't solve the more ambitious goal of tracking data types on dataframes, so it is an open question to me whether it is worth doing. 

On tracking through dataframes, I seem to run often into needing `typing.cast`:

```python
df = pl.DataFrame({"dt": [date(2020,1,1), date(2020,1,2)]})
my_date = df.select(pl.col("dt").min()).item()  # requires wrapping by typing.cast(date, ...) to get typing coverage in the remainder of the code
```

**Comment by Sage0614** [comment]
fair enough about the DataFrame/LazyFrame schema related difficulty, 

The immediate benefit I would see for the Expr & Series to have this feature here is,

` pl.col("a").is_nan().arccos()`

`pl.Series().is_nan().arccos()`

These should be the case that static type checking tool would raise a red flag, even though from the context the input is pl.Unknown, we still have enough knowledge that output of is_nan() is pl.Boolean and arccos() shouldn't be a valid method and shouldn't appear in the autocompletion suggestion.
