### ISSUE TITLE
invalid timezone when converting from pandas

### ISSUE THREAD

**Issue by adfea9c0** [pola-rs/polars#10501]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
dates = pd.date_range("2020-01-01 12:30:00 +05:00", periods=3)
dates
>>> DatetimeIndex(['2020-01-01 12:30:00+05:00', '2020-01-02 12:30:00+05:00',
>>>                '2020-01-03 12:30:00+05:00'],
>>>               dtype='datetime64[ns, pytz.FixedOffset(300)]', freq='D')

pl.from_pandas(dates)
>>> shape: (3,)
>>>   datetime[ns, +05:00]
>>>   invalid timezone
>>>   invalid timezone
>>>   invalid timezone
```

### Issue description

Ambiguous error 'invalid timezone' when converting some output of `pd.date_range`

### Expected behavior

Correct parsing of the datetimes. I think polar supports fixed offsets? https://pola-rs.github.io/polars-book/user-guide/transformations/time-series/timezones/

### Installed versions

<details>

```
0.18.4
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report - the user guide needs updating actually, 

> +01:00: fixed offsets. May be useful when parsing, but you almost certainly want the "Area/Location" format above instead as it will deal with irregularities such as DST (Daylight Saving Time) for you.

is no longer true: fixed offsets are only supported for individual elements, rather than as the dtype of a column

I'd suggest you convert to UTC beforehand, and then convert back to your given timezone

**Comment by adfea9c0** [comment]
Ack, thank you for the quick reply! I'll leave the issue open RE user guide?

**Comment by MarcoGorelli** [comment]
yup, thanks!

**Comment by adfea9c0** [comment]
Sorry one follow-up -- it seems this doesn't raise but I'm not sure how to test for this error either. It seems `.is_null()` actually returns false on these invalid timezone items. How can I check for this failure?

**Comment by MarcoGorelli** [comment]
> it seems this doesn't raise

it does in the latest version 😄 if you upgrade you should see it

closing for now then, but thanks for reporting - high-quality bug reports are what helps software improve
