### ISSUE TITLE
The `polars-py` fails with basic example 

### ISSUE THREAD

**Issue by groundf** [pola-rs/polars#1051]
#### Are you using Python or Rust?

Python (3.9.1  [MSC v.1927 64 bit (AMD64)])

#### What version of polars are you using?

0.8.13

#### What operating system are you using polars on?

Windows 10 64bit

#### Describe your bug.

The basic example from the documentation 

```
dataset = pl.read_csv("https://j.mp/iriscsv")
df = dataset[dataset["sepal_length"] > 5].groupby("species").sum()
```

panics with the error message

```
Traceback (most recent call last):
  File "C:\Playground\dataframe-libs\polars_demo.py", line 11, in <module>
    df = dataset[dataset["sepal_length"] > 5].groupby("species").sum()
  File "C:\Playground\dataframe-libs\.venv\lib\site-packages\polars\eager\frame.py", line 2527, in sum
    return self.select_all().sum()
  File "C:\Playground\dataframe-libs\.venv\lib\site-packages\polars\eager\frame.py", line 2696, in sum
    return wrap_df(self._df.groupby(self.by, self.selection, "sum"))
RuntimeError: Any(ShapeMisMatch("the Series used as keys should have the same length as the DataFrame"))
```

**Comment by ritchie46** [comment]
Thanks for the issue report. We changed the backend and this regression was not noted.

If you downgrade to `polars==0.8.12` it works as expected. I will update right away.

**Comment by ritchie46** [comment]
This is now fixed and released. If you run `pip install polars==0.8.14` everything should run fine.

**Comment by groundf** [comment]
> pip install polars==0.8.14

Now it works! Thank you for your work and support. All the best.
