### ISSUE TITLE
Display 5 columns from dataframe instead of 8

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#10510]
The columns get messy printing 8 columns on the terminal.

Ideally the best solution would be to pick the number of columns automatically based on terminal space but lowering the default would improve drastically this user experience problem.

**Comment by mcrumiller** [comment]
I'm the opposite, I almost always immediately increase the number of columns to 25.

I believe @alexander-beedie is the one most familiar with output sizing. Alex, would it be bad to have `DataFrame.__str__` pass a `preferred_width=os.get_terminal_size()[0]` to help determine how many columns to display? That might be rather nice. We could also then have `pl.Configs.tbl_cols("auto")`.

**Comment by alexander-beedie** [comment]
> lowering the default would improve drastically this user experience problem.

This feature (setting 5 cols) already exists; just call `pl.Config.set_tbl_cols(5)` when you start your session; the current default is probably more reasonable though (certainly I don't usually have any trouble displaying 8 columns - this is obviously very data-dependent though, and it sounds like you either often have wide data or a narrow terminal. This is definitely not the case for everyone though).

I agree that we should make a more dynamic determination given the available width; however, it can be hard to detect and then sensibly assign the available space into width/column buckets - I made a (relatively) [recent commit](https://github.com/pola-rs/polars/pull/9744) not that long ago that helps us make _noticeably_ better column width allocations, and this was a necessary first step before trying to do anything more sophisticated. Took a while to get around to that, as it's extremely fiddly - it's one of those problems where you change one thing and what you're looking at improves, only to discover that it makes something else worse...

Nevertheless, I will definitely follow-up on this later and try to have us do a better job but it's one of those problems that's easy to describe but really hard to manage all the edge-cases of, so it gets easily put-off as it's such a time-sink 😅

> Alex, would it be bad to have DataFrame.__str__ pass a preferred_width=os.get_terminal_size()[0] to help determine how many columns to display?

`os.terminal_size()` is not very reliable; as an example, calling it in my current PyCharm/IPython shell immediately gets me `OSError: [Errno 25] Inappropriate ioctl for device` ;)

Aside from that, if you want to take control over the formatting and you know your typical environment we have plenty of `pl.Config` options available that will let you tailor your preferred defaults. The sheer variability of user shells/widths/data is one of the problems - it's hard to find a single default that everyone agrees on (hence heading in the direction of something more dynamic is preferable).

**Comment by mcrumiller** [comment]
> Yes :) os.terminal_size() is not very reliable; as an example, calling it in my current PyCharm/IPython shell immediately raises an OSError: [Errno 25] Inappropriate ioctl for device exception.

Well, I didn't mean that *specifically*, but moreso if we could have *some* method of determining terminal size. But on thinking harder, I'm guessing that the python team already thought long and hard about it and, if `os.get_terminal_size()` can't do the job, it's probably not practical here.

Also @arturdaraujo -- what system are you on that five columns is too wide? Can I buy you a new monitor? #jokingbutonlysortof

**Comment by arturdaraujo** [comment]
I use vscode and sometimes spyder, the terminal is often 1/4 of the monitor in my setup. My guess is that most hobbyists and student data scientists out there are using Spyder from Anaconda with a very limited terminal space but I understand that changing to 5 columns is not ideal.

I gotta say I feel like this issue is the last bit of "user experience" upgrade that is missing to surpass pandas in ux. Polars is better in every other aspect hands down. 

# my average space on vscode: os.terminal_size(columns=59, lines=24)

**Comment by universalmind303** [comment]
I also think 8 is a pretty sensible default. The cols can also be set via env variables (`POLARS_FMT_MAX_COLS`), so it should be easy enough to set that as the default inside your `~/.zshrc` or equivalent.

**Comment by alexander-beedie** [comment]
Will close this out as we're not going to set it to 5 by default, and I think we all more-or-less agree that it would be great if we could reliably detect the available width and/or have a more dynamic way to assign columns into the given space.
