### ISSUE TITLE
replace_time_zone fast path if the timezone already matches

### ISSUE THREAD

**Issue by jamesHargreaves12** [pola-rs/polars#10516]
### Problem description

`replace_time_zone(None)` takes the same amount of time when run on a series that is timezone-aware as one that is not timezone-aware.

Repro:
The final line of this code snippet takes over a second on my 2016 MacBook Pro. The type of the utc_time column is  `datetime[μs]` and so we can just check that and exit.
```
import polars as pl
from datetime import datetime, timedelta

df = pl.DataFrame({
    "utc_time":  [(datetime.utcnow() + timedelta(minutes=i)) for i in range(10_000_000)]
})

df2 = df.with_columns(df["utc_time"].dt.replace_time_zone(None))
```

**Comment by MarcoGorelli** [comment]
thanks @jamesHargreaves12 for the report, and sorry for having missed this (please do feel free to ping me if you come across other time zone oddities) - fix incoming

**Comment by MarcoGorelli** [comment]
as an aside, I'd suggest not using `utcnow` https://blog.ganssle.io/articles/2019/11/utcnow.html
