### ISSUE TITLE
Should add an opposite number expression (polars.Expr.opposite)

### ISSUE THREAD

**Issue by ytskuh** [pola-rs/polars#10521]
### Problem description

Consider the following situation: you have a `pl.DataFrame` with lots of columns, and you want to apply a computation "+1" to all the columns that has name that meets a regular expression r, you can do this
```
df.with_columns(pl.col(r)+1)
```
but not this
```
df.with_columns(1+pl.col(r))
```
That's because ```ComputeError: The name: 'literal' passed to `LazyFrame.with_columns` is duplicate```.
But what if you want to apply an opposition? You can't do that unless using fold which is absolutely should not be necessary...

**Comment by cmdlineluser** [comment]
> But what if you want to apply an opposition?

Could you show an example of what this means?

What would `.opposite()` do? How would it be used?

To have a literal on the LHS, I think you'd need: `(1 + pl.col(r)).keep_name()`

**Comment by reswqa** [comment]
This is because for binary expr, we use the name of the left field as the name of the result. `pl.col (r)` actually generates multiple expressions with the same pattern(for example, [1 + pl.col("a"),  1 + pl.col("b")]) all named `literal`, resulting in the same column names. 

As @cmdlineluser suggests: `keep_name` will change its name to the name of `leaf column` instead of the left name(literal here).

**Comment by ytskuh** [comment]
> > But what if you want to apply an opposition?
> 
> Could you show an example of what this means?
> 
> What would `.opposite()` do? How would it be used?
> 
> To have a literal on the LHS, I think you'd need: `(1 + pl.col(r)).keep_name()`

I mean x.opposite() = -x



> This is because for binary expr, we use the name of the left field as the name of the result. `pl.col(r)` actually generates multiple expressions with the same pattern(for example, `[1 + pl.col("a"), 1 + pl.col("b")]`) all named `literal`, resulting in the same column names.
> 
> As @cmdlineluser suggests: `keep_name` will change its name to the name of `leaf column` instead of the left name(`literal` here).

But then I get a ```PanicException: `keep_name`, `suffix`, `prefix` should be last expression```

**Comment by reswqa** [comment]
> But then I get a PanicException: `keep_name`, `suffix`, `prefix` should be last expression

Could you show your code with `keep_name`?

**Comment by ytskuh** [comment]
Sorry for that. Maybe I made a mistake in my previous code. I tried to repreduce it using
```
df = pl.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
})
df.with_columns((-pl.col("^a|b$")).keep_name()).drop("c")
```
but that works fine. It's all my fault and thanks very much for your patience.
