### ISSUE TITLE
`set_tbl_hide_column_data_types` not respected by HTML rendering

### ISSUE THREAD

**Issue by adaitche** [pola-rs/polars#10523]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.Config.set_tbl_hide_column_data_types(True)

df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [3, 4, 5],
        "c": [5, 6, 7],
    }
)

# execute in a separate Jupyter cell; observe that data types are not included in the output
print(df)

# execute in a separate Jupyter cell; observe that data types are included in the output
df
```

### Issue description

The setting `pl.Config.set_tbl_hide_column_data_types(True)` is not respected when rendering a DataFrame to HTML (via the method `_repr_html_` I assume). After enabling this setting, I still see data types in the HTML output, however not in the text rendering.

The same is true for to `Config.set_tbl_hide_dataframe_shape` and possibly more setting.

### Expected behavior

Settings like 
- set_tbl_hide_column_data_types
- set_tbl_hide_dataframe_shape

should apply not only to text rendering of DataFrame, but also to the HTML rendering.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.10.12 (main, Jun 20 2023, 08:28:40) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.6.3
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
FYI: this will be closed by https://github.com/pola-rs/polars/pull/10449, which I'm just about to double-check.

**Comment by alexander-beedie** [comment]
https://github.com/pola-rs/polars/pull/10449 just merged; closing.
