### ISSUE TITLE
`cut`/`qcut` lazy schema is incorrect when `include_breaks=True`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10524]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.LazyFrame({'a': [1,2]}).select(pl.col('a').cut([1.5], include_breaks=True))

lf.schema 
# {'a': Categorical}

lf.collect().schema
# {'a': Struct([Field('break', Float64), Field('category', Categorical)])}
```

### Issue description

`include_breaks` changes the output type. This is against our guidelines of one expression = one output type.

Not sure what the solution should be here.

### Expected behavior

Lazy schema must match the schema after collecting.

### Installed versions

main

**Comment by orlp** [comment]
> One can argue that cut with include_breaks = true / false can potentially be seen as different expression(It's a bit untenable).

I would argue that, see also my proposal here: https://github.com/pola-rs/polars/issues/10468#issuecomment-1680368759.

> This is against our guidelines of one expression = one output type.

I think the core of our guideline is that the output schema is completely predictable from the input schema, and not dependent on the data. But a constant boolean parameter does not violate this.
