### ISSUE TITLE
Incorrect optimization of trivial AND/OR with boolean literal in series

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10530]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> df = pl.DataFrame({'x': [False, True]})
>>> df.select(pl.col('x') & False)
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ false   │
└─────────┘
```

### Issue description

We optimize this expression by replacing `x & False` with the literal `False`, but this is not correct in our current optimizer. We should temporarily disable this optimization until our logical plan optimizer is schema-aware.

### Expected behavior

The length of the series should be preserved.

### Installed versions

Irrelevant.

**Comment by orlp** [comment]
Fixed with https://github.com/pola-rs/polars/pull/10531, which is unfortunately a pessimization for `selects` with more than one column that would benefit from this. However, to fix this properly while keeping the optimization would require a significant rewrite of the logical plan optimizer, so we'll leave that for later.

**Comment by ritchie46** [comment]
Yeap. Can we close this now?
