### ISSUE TITLE
count overflows with large number of rows

### ISSUE THREAD

**Issue by banteg** [pola-rs/polars#10548]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
> from pyarrow.dataset import dataset
> import polars as pl

> pl.scan_parquet("data/*.parquet").select(pl.count()).collect()
shape: (1, 1)
┌───────────┐
│ count     │
│ ---       │
│ u32       │
╞═══════════╡
│ 741477685 │
└───────────┘

> dataset("data").count_rows()
5036444981
```

### Issue description

i have a large parquet dataset with over 5 billion rows. `count` uses `u32` which overflows twice here, returning an incorrect result.

### Expected behavior

polars makes it feasible to work with giant datasets (mine is 290 gb), so it should support working with billions of rows by bumping `count` dtype to `u64`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Python:              3.10.11 (main, Apr 16 2023, 22:20:30) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a6
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            1.10.12
sqlalchemy:          2.0.19
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Use https://pypi.org/project/polars-u64-idx/ as stated here; https://github.com/pola-rs/polars#going-big

**Comment by banteg** [comment]
thank you, this works for me

<img width="627" alt="Screenshot 2023-08-17 at 12 09 09" src="https://github.com/pola-rs/polars/assets/4562643/c6b75276-a175-435f-8ce5-b5762e0b8744">
