### ISSUE TITLE
`pl.lit(array)` ignores dtype argument

### ISSUE THREAD

**Issue by exyi** [pola-rs/polars#10546]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

All of the following

```python
> pl.DataFrame({ "a": ["A"]}).with_columns(pl.lit([1], dtype=pl.Float64))
┌─────┬─────┐
│ a   ┆     │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ A   ┆ 1   │
└─────┴─────┘
pl.DataFrame({ "a": ["A"]}).with_columns(pl.lit([None], dtype=pl.Float64))

┌─────┬──────┐
│ a   ┆      │
│ --- ┆ ---  │
│ str ┆ f32  │
╞═════╪══════╡
│ A   ┆ null │
└─────┴──────┘
pl.DataFrame({ "a": ["A"]}).with_columns(pl.lit([1.2], dtype=pl.Float32))
┌─────┬─────┐
│ a   ┆     │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ A   ┆ 1.2 │
└─────┴─────┘
```

Making the `dtype` a list does not help

```
pl.DataFrame({ "a": ["A"]}).with_columns(pl.lit([1.2], dtype=pl.List(pl.Float32)))
┌─────┬─────┐
│ a   ┆     │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ A   ┆ 1.2 │
└─────┴─────┘
``` 

### Issue description

When I use `pl.lit([ ... ], dtype=X).alias("...")` to add columns to a data frame, it ignores the provided `dtype` and infers it's own. Using `pl.Series` instead of `pl.lit` works, and when `pl.lit` contains a constant (not entire column), it works too. I guess `pl.lit` wasn't supposed to be used this way. I find it troublesome because it works almost.

### Expected behavior

I'd expect the column to have the specified `dtype`. Alternatively, I'd get an exception or warning that `pl.lit` isn't supposed to be used in this way and I should switch to `pl.Series`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-6.1.45-1-lts-x86_64-with-glibc2.38
Python:              3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.1
pandas:              1.5.3
pyarrow:             10.0.1
pydantic:            1.10.9
sqlalchemy:          1.3.24
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
The recommended way to unambiguously pass arrays into `lit` is currently via `Series`, eg:
```python
pl.DataFrame({
    "a": ["A", "B"],
}).with_columns(
    x = pl.lit( pl.Series([[10,20,30]], dtype=pl.List(pl.Float64)) ),
)
# shape: (2, 2)
# ┌─────┬────────────────────┐
# │ a   ┆ x                  │
# │ --- ┆ ---                │
# │ str ┆ list[f64]          │
# ╞═════╪════════════════════╡
# │ A   ┆ [10.0, 20.0, 30.0] │
# │ B   ┆ [10.0, 20.0, 30.0] │
# └─────┴────────────────────┘
```
In an upcoming release we plan to normalise the behaviour of literal sequence/array inputs for `lit` so that you _won't_ have to wrap with Series, which will hopefully also address this issue properly.

**Comment by stinodego** [comment]
This has been fixed.
