### ISSUE TITLE
n_rows is executed after infer_schema_length with _csv() methods?

### ISSUE THREAD

**Issue by ldacey** [pola-rs/polars#10544]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

this fails:
```python
import polars as pl
import tempfile

case_numbers = [f"{i:06d}" for i in range(1, 1001)]
test = ["test" for _ in range(1, 1001)]

df = pl.DataFrame({'test': test, 'case_number': case_numbers})

df[622, "case_number"] = "CASE-NO0A60"

with tempfile.NamedTemporaryFile(delete=True, suffix=".csv") as temp_file:
    filename = temp_file.name
    df.write_csv(filename)
    pl.read_csv(filename, n_rows=1)
```

this works and so does setting infer_schema_length=0

```python
import polars as pl
import tempfile

case_numbers = [f"{i:06d}" for i in range(1, 1001)]
test = ["test" for _ in range(1, 1001)]

df = pl.DataFrame({'test': test, 'case_number': case_numbers})

df[622, "case_number"] = "CASE-NO-0A60"

with tempfile.NamedTemporaryFile(delete=True, suffix=".csv") as temp_file:
    filename = temp_file.name
    df.write_csv(filename)
    pl.read_csv(filename, n_rows=1, infer_schema_length=623)
```

### Issue description

It seems like infer_schema_length is run before n_rows which has caused some issues for me with certain sources. For example, when I want to read 1 or 0 rows and just find the header on a file stored on cloud storage.

### Expected behavior

When I specify n_rows=1, ideally I would only read the first row of data and I would not scan other values. Perhaps infer_schema_length should be set to n_rows automatically if n_rows < infer_schema_length?

The other issue is that setting `infer_schema_length`=1 should only read the first row of data (which is an integer) and n_rows should only read the first row of data (also an integer), but somehow I get this error:

> return wrap_df(ldf.collect())
>                    ^^^^^^^^^^^^^
> exceptions.ComputeError: Could not parse `CASE NO-049521` as dtype `i64` at column 'Case#' (column number 1).
> The current offset in the file is 381 bytes.

That implies that if I set infer_schema_length=0, I will be reading all data into memory temporarily as Ut8 which seems like a waste. I really only want to get the headers so they I can pass the explicit dtypes argument.

At what point does the n_rows argument actually kick in?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.3.1-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.9
sqlalchemy:          1.4.48
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by ldacey** [comment]
FYI, this is still an issue on 0.19.1

**Comment by deanm0000** [comment]
Try setting the sample_size = 1 or whatever your n_rows are. I made this report that might be related https://github.com/pola-rs/polars/issues/8677

**Comment by ldacey** [comment]
That works, thank you. I didn't know about that option and never thought to test it. I tried infer_schema_length and tried n_threads, but the sample_size argument just never came to mind.

I can close this as well, or do you think this is actually a bug or should be documented somewhere? When I use n_rows = 1 I expect to only read the first row personally.

**Comment by deanm0000** [comment]
I guess close as duplicate.

**Comment by ldacey** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/8677
