### ISSUE TITLE
Can Py-polars be in a separate repo from polars?

### ISSUE THREAD

**Issue by mikelui** [pola-rs/polars#10545]
### Problem description

Or have dependencies on official releases?

I run into dependency clashes in some ecosystems, when trying to unify the build for both. This seems to be because a py-polars release depends on its own internal version of polars which may have its version set to an official release (while not being an official release).

I'm sure there are good arguments to keep py-polars on w/e commit polars rs is on, but to the layman it seems overly complex to have polars and py-polars splitting the internal native polars versioning.

**Comment by ritchie46** [comment]
No, we want python polars to use the latest main. Having it in a separate repo would complicate that. You can vendor both rust polars and python polars if you want to unify them.

**Comment by mikelui** [comment]
Thanks for the clear answer!
