### ISSUE TITLE
`pl.col('^pattern1$', '^pattern2$')` doesn't match regular expressions

### ISSUE THREAD

**Issue by hleumas** [pola-rs/polars#10543]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl
df = pl.DataFrame({
    'col1': [1, 2, 3],
    'col2': [4, 5, 6],
    'val1': ['a', 'b', 'c'],
    'val2': ['A', 'B', 'C'],
})

df.with_columns(pl.col('^col.*$').prefix('matched_')) # this works
df.with_columns(pl.col('^col.*$', '^val.*$').prefix('matched_')) # this doesn't
df.with_columns(pl.col('^col.*$', 'val1').prefix('matched_')) # neither does this
```

### Issue description

`pl.col` tries to match all the inputs as strings if there is more than one and doesn't check for regular expressions

### Expected behavior

To check for regular expressions on all the inputs.

### Installed versions

<details>
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by reswqa** [comment]
You may workaround this by `df.with_columns(pl.col('^col.*$').prefix('matched_'),pl.col('^val.*$').prefix('matched_'))`. I have submitted a patch try to fix this.
