### ISSUE TITLE
expr does not have cut attribute

### ISSUE THREAD

**Issue by rayal34** [pola-rs/polars#10547]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This is a direct copy from the `cut` example:
```python
g = pl.repeat("a", 5, eager=True).append(pl.repeat("b", 5, eager=True))
df = pl.DataFrame(dict(g=g, x=range(10)))
df.with_columns(q=pl.col("x").cut([2, 5]))
```
The error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_468505/193494312.py in <module>
      1 g = pl.repeat("a", 5, eager=True).append(pl.repeat("b", 5, eager=True))
      2 df = pl.DataFrame(dict(g=g, x=range(10)))
----> 3 df.with_columns(q=pl.col("x").cut([2, 5]))

AttributeError: 'Expr' object has no attribute 'cut'
```

### Issue description

The error states that the expression does not have the `cut` attribute but, according to the docs, it should be supported.

I noticed that my polars version is 0.18.4 when the latest should 0.18.15.

### Expected behavior

The above example should run without error.  (`cut` works properly on a series)

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.15.0-75-generic-x86_64-with-debian-bullseye-sid
Python:      3.7.10 (default, Aug  4 2023, 23:07:28) 
[GCC 9.4.0]

----Optional dependencies----
numpy:       1.21.6
pandas:      1.3.5
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.3.0
matplotlib:  3.4.3
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

**Comment by s-banach** [comment]
Look at your version.

**Comment by cmdlineluser** [comment]
`Expr.cut` was added in `0.18.5` - you need to upgrade your version of Polars.
