### ISSUE TITLE
Sum of float32 numbers is wrong for n > 2**28

### ISSUE THREAD

**Issue by edavisau** [pola-rs/polars#10553]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

In this example I am summing an array of ones, so the sum should be the same as the number of values

```python
import polars as pl
import numpy as np

num_values = 2**28 + 1
arr = np.ones(num_values, dtype=np.float32)
result = pl.from_numpy(arr).sum().to_series(0)[0]

assert int(result) == num_values
```

### Issue description

Things I also tested
- Problem still appears using polars-u64-idx
- There was no problem with float64, although there might be a higher threshold 

### Expected behavior

Assertion should succeed.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          3.7.0
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            1.10.5
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by edavisau** [comment]
perhaps this is clearer
```python
import polars as pl

num_values = 2**28 + 1
result = pl.ones(num_values, dtype=pl.Float32, eager=True).sum()

assert int(result) == num_values
```

**Comment by adarshconcertai** [comment]
Float does not infinite precision even for Integer they can represent. Also float32 has significantly less precision than float64.

Below is a table of precision of float32 on integer of different range. [wiki reference](https://en.wikipedia.org/wiki/Single-precision_floating-point_format)
<img width="855" alt="image" src="https://github.com/pola-rs/polars/assets/132476642/17d810f2-1ff9-4657-a2a2-7d5f65ba1ab8">


floating number get rounded off when they cannot be represented exactly. Below is a python snippet to show exactly that.

<img width="230" alt="image" src="https://github.com/pola-rs/polars/assets/132476642/85cb348d-0431-4bf4-9802-ee99e1a54d38">

**Comment by orlp** [comment]
This isn't necessarily an issue with Polars, this is just one of the quirks of how floating point numbers work.

Perhaps in the future we can use a more numerically stable summation algorithm like [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm), but that is a far more subtle issue.

**Comment by edavisau** [comment]
Hi all, thanks for explaining that! I would not have thought it was due to the precision of float32.

Does the summation of these floats occur within polars or arrow2? If it's the latter then would it be worth creating an issue there? (even if I don't expect it to be done any time soon)

Below is a comparison of different library behaviours

```python
# Numpy
np.ones(800_000_000, dtype=np.float32).sum()  # = 800000000.0
# PyArrow
pa.array(np.ones(800_000_000), type=pa.float32()).sum()  # = 800000000.0  (although it becomes pa.DoubleScalar)
# Polars
pl.ones(800_000_000, dtype=pl.Float32, eager=True).sum()  # = 268435456.0
```

**Comment by orlp** [comment]
@edavisau I've decided to re-open this issue, I've been working on a [pairwise summation](https://en.wikipedia.org/wiki/Pairwise_summation) implementation that will fix this.

I'm on a holiday for the next couple days but I expect to  have it done by the end of next week.

**Comment by edavisau** [comment]
Great to hear, thanks!
