### ISSUE TITLE
use_statistics doesn't use row groups statistics to skip data in polars.scan_parquet

### ISSUE THREAD

**Issue by MacHu-GWU** [pola-rs/polars#10567]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = (
    pl.scan_parquet(
        "s3://bucket/key.parquet,
    )
    .filter(pl.col("col_1") <= 1000)
    .select(
        "col_1",
        "col_2",
    )
    .collect()
)
print(df.shape)
```

### Issue description

I created a test dataset that has 10 columns and 10M rows and with 100 row groups (100k rows per row groups) snappy file, snappy compressed. The value is random int from 1 ~ 1M. Total file size is 550MB after compression

When it is on local, scan_parquet is significantly faster than read_parquet, and I guess it is because it is lazy reader and use statistics to skip row groups. How ever, when it comes to S3, read_parquet, scan_parquet doesn't make much difference.

I already take S3 IO into account that the test is done in AWS Lambda function runtime which takes 10 sec to be fully download using boto3 multi thread download and takes around 50 sec to be done with single thread download.
I already take the S3 IO part time consumption out but scan_parquet and read_parquet are equally slow. It doesn't seems like skip pages using the statistics. I know it is using the fsspec + s3fs under the hood, and I confirm that fsspec + s3fs uses single thread with polars when reading parquet. 

Any one could add more document to explain how does ``use_statistics`` argument works?

### Expected behavior

scan_parquet should be significanly faster than read_parquet when reading from s3 because it skips a lot of IO.

### Installed versions

<details>
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by ritchie46** [comment]
We don't natively support s3 reading yet. Currently the file is implicitly downloaded by the python file handler we use for web indirected data.

**Comment by MacHu-GWU** [comment]
@ritchie46  thank you for quick reply. I see. My current solution is to download it from S3 using multi thread download API (very fast, like 75-100MB per second), then read the local file using scan_parquet, which is blazingly fast (0.05 second to scan 10M rows with statistics). However, the price is that I have to write the data to disk, which is an IO.

Thanks for this awesome library!

**Comment by MacHu-GWU** [comment]
@ritchie46  BTW, is there a opportunity I can post a blog to polars? I write a blog on my personal blog about using AWS + Lambda + Polars + Athena with the trick I demonstrate above to offload 20+ AWS Glue Spark jobs into AWS Lambda. This saves one of AWS client 70% ETL cost (around $250,000 per month) and is able to release 80% faster (development experience, capability for unit test, CICD, and deployment are way easier with Lambda)

**Comment by ritchie46** [comment]
This is supported now.

@MacHu-GWU I just read this now. Have you got any link to the blog post? I am very interested in your solution/story.

**Comment by ritchie46** [comment]
I will close the issue, but my question still remains. :)

**Comment by MacHu-GWU** [comment]
@ritchie46  https://learn-big-data-on-aws.readthedocs.io/02-Best-Practices/Polars-vs-Pandas-Benchmark-in-AWS-Lambda/index.html
This is my blog post. In my example, polars can handle 2X larger data and 2X faster using the same amount of memory.
