### ISSUE TITLE
Filter then Select New Column Panic on empty filtered data

### ISSUE THREAD

**Issue by potter420** [pola-rs/polars#1056]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

pypolars=0.8.14

#### What operating system are you using polars on?

Amazon Linux 2

#### Describe your bug.

Filter a dataframe and select to create new columns panic when print or out put but not when assigning

#### What are the steps to reproduce the behavior?

```python
df1 = pl.DataFrame({
        'a':[1,2]
    }).filter(pl.col('a')==0)
   .select(['a',pl.lit(1).alias('b')]) //Does not panic
print(df1) //Panic here

df1 = pl.DataFrame({
    'a':[1,2]
}).filter(pl.col('a')==0).with_columns(
    [pl.lit(1).alias('b')]
).select(['a']) // Now it will actuallyreturn a RunTime error
```
#### What is the actual behavior?

```python
PanicException: The columns lengths in the DataFrame are not equal.
```
When trying to `to_arrow` the dataframe.

```python
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("all columns in a record batch must have the same length")', /github/workspace/polars/polars-core/src/frame/mod.rs:1693:72
```

#### What is the expected behavior?

Either it should raise exception at assigning steps (eager mode) or the new column should have zero length
I would prefer the later since during processing with lazy mode, it's kind of hard to guess which data will have 0 length. Some are perfectly valid 0 length data.

**Comment by ritchie46** [comment]
@potter420, it should be fixed now. Thanks for the notification.
