### ISSUE TITLE
arr.get() no longer supported in python

### ISSUE THREAD

**Issue by genegc** [pola-rs/polars#10577]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df1 = pl.DataFrame({
    'foo': [{'hi':'world', 'bye':'now'}, {'hi':'world2', 'bye':'now2'}],
    'bar': ['a', 'b']
})
df = df1.with_columns(pl.col('foo').arr.get(0)).alias('mytest')
```

### Issue description

Did this functionality get removed intentionally?
It's claimed on [this thread](https://chat.stackoverflow.com/transcript/6/2023/5/31/2-24) that "This is busted between 0.17.12 and 0.18.0"

### Expected behavior

expected it to allow for retrieval of array element

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by cmdlineluser** [comment]
You can use `.list.get()`

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html

`.arr` was renamed to `.list`

Then a new `pl.Array` type was added which uses the `.arr` namespace.
