### ISSUE TITLE
`pl.read_csv()` inconsistently handles ragged CSVs, sometimes silently truncating data

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10585]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> from io import StringIO
>>> pl.read_csv(StringIO('A,ragged\nB\nC'), has_header=False)  # scenario 1
shape: (3, 2)
┌──────────┬──────────┐
│ column_1 ┆ column_2 │
│ ---      ┆ ---      │
│ str      ┆ str      │
╞══════════╪══════════╡
│ A        ┆ ragged   │
│ B        ┆ null     │
│ C        ┆ null     │
└──────────┴──────────┘
>>> pl.read_csv(StringIO('A\nB,ragged\nC'), has_header=False)  # scenario 2
shape: (3, 1)
┌──────────┐
│ column_1 │
│ ---      │
│ str      │
╞══════════╡
│ A        │
│ B        │
│ C        │
└──────────┘
>>> pl.read_csv(StringIO('A\nB\nC,ragged'), has_header=False)  # scenario 3
shape: (3, 1)
┌──────────┐
│ column_1 │
│ ---      │
│ str      │
╞══════════╡
│ A        │
│ B        │
│ C        │
└──────────┘
```

### Issue description

When reading "ragged" CSVs with variable numbers of columns per row, `pl.read_csv()` behaves inconsistently depending on whether the ragged data is on the first line: 

- If so (scenario 1 above), it expands the data frame to encompass the ragged data and right-pads with `null`. 
- If not (scenarios 2 and 3 above), it silently truncates the ragged parts without giving an error. 

Ragged CSVs are relatively common in the wild, and silently truncating them without giving an error is dangerous!

### Expected behavior

The correct behavior is either to disallow ragged data and give an error in all cases, or to behave like scenario 1 in all cases (which seems preferable). 

For what it's worth, pandas also doesn't handle ragged data consistently (though at least it doesn't silently truncate the data). It has the same behavior as polars in scenario 1, but gives an error in scenarios 2 and 3:

```python
>>> pd.read_csv(StringIO('A\nB,ragged\nC'), header=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../mambaforge/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../mambaforge/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File ".../mambaforge/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../mambaforge/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 2
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by trueb2** [comment]
>For what it's worth, pandas also doesn't handle ragged data consistently (though at least it doesn't silently truncate the data). It has the same behavior as polars in scenario 1, but gives an error in scenarios 2 and 3:

Pandas is handling the rows according to documentation. Pandas has an `on_bad_lines` argument to handle rows with too many columns like these 'ragged' rows.

<details>
<summary> on_bad_lines docs description </summary>
on_bad_lines{‘error’, ‘warn’, ‘skip’} or callable, default ‘error’
Specifies what to do upon encountering a bad line (a line with too many fields). Allowed values are :
‘error’, raise an Exception when a bad line is encountered.
‘warn’, raise a warning when a bad line is encountered and skip that line.
‘skip’, skip bad lines without raising or warning when they are encountered.
</details>

Scenario 1 tells the parser that there are going to be 2 columns because the first row has two columns. Scenario 2 and 3 tells the parser there is going to be one column.Therefore, a (bad) ragged row with 'too many fields' only appears in scenario 2 and 3.

**Comment by Wainberg** [comment]
That's good context. It sounds like pandas's choice was made for parsing efficiency. Their approach is inconsistent because they don't give an error when a row has _fewer_ columns than the first row, only when it has more. 

So, two options for polars could be:

1. Give an error if any row has a different number of columns than the first row.
2. Keep all columns and right-pad with nulls for rows shorter than the longest row.

Assuming option 2 is slow, option 1 seems like a reasonable default. Option 2 could be enabled with `ragged=True`. The error message for option 1 could suggest `ragged=True` but caution that it might be slow.

**Comment by calumrussell** [comment]
I was unable to test this fully but I believe that `read_csv` within the core polars package handles this as you were expecting. But py_polars is calling `scan_csv` giving the result above (and may be doing something else on the Python side).

Expected behaviour seems quite hard to define in this case because any solution that doesn't have hard-coded columns passed to `read_csv` from the client will have edge cases (I think).

**Comment by Wainberg** [comment]
I'd agree there are multiple potential expected behaviors, but polars's current behavior of lopping off the ends of rows without giving a warning is definitely not one of them ;) 

Options 1 and 2 above both feel more intuitive to me and don't seem to have edge cases, or maybe I'm just not thinking of them?

**Comment by trueb2** [comment]
The pyarrow implementation throws effectively the same error as pandas.
<details>
<summary> Pyarrow Expected 1 columns, got 2 </summary>

```
>>> pl.read_csv(StringIO('A\nB\nC,ragged'), has_header=False, use_pyarrow=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/polars/io/csv/functions.py", line 232, in read_csv
    tbl = pa.csv.read_csv(
          ^^^^^^^^^^^^^^^^
  File "pyarrow/_csv.pyx", line 1235, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1244, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 1 columns, got 2: C,ragged
```

</details>

<hr/>

I have a preference for exact parity with pandas, pyarrow, and MATLAB when not prohibitive. I see a lot of malformed CSV data in research datasets. Whether or not the CSV parses with pandas is almost a gold standard in ubiquity.

The choice of python engine and a callable to handle bad lines is pretty useful, but I expect that there are prohibitive performance considerations in expanding the current behavior with an `on_lines_with_extra_columns` argument supporting more than 'error', 'warn', or 'skip'. 

I disagree with adding a `ragged` argument; I think it is ambiguous and is not parallel to other parsers. Here is documentation from another parser, MATLAB's readmatrix and DelimitedTextImportOptions. Amongst those Replacement Rules, there is also a MissingRule - Procedure to manage missing data.

<details>
<summary>ExtraColumnsRule - Procedure to handle extra columns</summary>

<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Roboto, sans-serif; font-size: 13px;">Procedure to handle extra columns in the data, specified as one of the values in this table.</p><div class="table-responsive" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; min-height: 0.01%; overflow: auto hidden; width: 1333px; margin-bottom: 21px; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Roboto, sans-serif; font-size: 13px;">

Extra Columns Rule | Behavior
-- | --
'addvars' | To import extra columns, create new variables. If there are N extra columns, then import new variables as 'ExtraVar1', 'ExtraVar2',..., 'ExtraVarN'. Extra columns of data are imported as if their VariableTypes are char.
'ignore' | Ignore the extra columns of data.
'wrap' | Wrap the extra columns of data to new records. This action does not change the number of variables.
'error' | Display an error message and abort the import operation.

</div>
</details>

<hr/>

>So, two options for polars could be:
>1. Give an error if any row has a different number of columns than the first row.

Even though every row in a CSV file is supposed to have the same number of columns, it seems that this is a non-standard option for a CSV parser by default. "Bad" lines seem to be extra columns, not too few columns, as they fall under replacement options.

>2. Keep all columns and right-pad with nulls for rows shorter than the longest row.

This is supported in MATLAB via addvars, and this is manually supported in pandas by specifying the number of columns or having the maximum columns in the first row. We get NaNs when specifying two columns to pandas, but we get errors when specifying two columns to polars.

<details>
<summary> read_csv with columns specified </summary>

```
>>> pd.read_csv(StringIO('A\nB\nC,ragged'), names=['x', 'y'])
   x       y
0  A     NaN
1  B     NaN
2  C  ragged
```

```
>>> pl.read_csv(StringIO('A\nB\nC,ragged'), new_columns=['x', 'y'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/polars/io/csv/functions.py", line 382, in read_csv
    return _update_columns(df, new_columns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/io/csv/_utils.py", line 33, in _update_columns
    df.columns = list(new_columns)
    ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 1123, in columns
    self._df.set_column_names(names)
exceptions.ShapeError: 2 column names provided for a dataframe of width 1
```

```
>>> pl.read_csv(StringIO('A\nB\nC,ragged'), columns=['x', 'y'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/polars/io/csv/functions.py", line 354, in read_csv
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 784, in _read_csv
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
exceptions.ColumnNotFoundError: unable to find column "x"; valid columns: ["A"]
```

</details>

<hr/>

If you weren't intending to read 2D matrix data into data frame or matrix, then the standard `csv` module would parse ragged data without issue as a list of lists. Polars can have a Series of Series, although I do not know how it would be configured to read in that manner via the read_csv interface (potentially, via a specified dtype and an alternative separator.)

<details>
<summary> csv.reader </summary>

```
>>> import csv
>>> r = csv.reader(StringIO('A\nB\nC,ragged'))
>>> for row in r:
...     print(row)
...
['A']
['B']
['C', 'ragged']
```

</details>

**Comment by Wainberg** [comment]
@trueb2 Great points! So it sounds like you're proposing two changes that would make polars consistent with pandas:

1. By default, give an error when a line has more columns than the first line (e.g. `pl.read_csv(StringIO('A\nB\nC,ragged'))`) instead of silently truncating the extra columns.
2. Allow `new_columns` to be longer than the number of columns in the first row (e.g. `pl.read_csv(StringIO('A\nB\nC,ragged'), new_columns=['x', 'y'])`) to enable reading of ragged data. This simultaneously solves the problem of computational efficiency (since the exact number of columns to be parsed is known from the start) and what to name the ragged columns.

Would these be reasonably straightforward to implement?

**Comment by ritchie46** [comment]
Polars does a schema inference over `N` lines. I think we should use those `N` lines to determine the number of fields. Then if we find more fields during parsing we can throw an error. 

In any case, after schema inference, the schema is fixed. We cannot  and will not add fields after that.

**Comment by ritchie46** [comment]
Then this branch needs to default to an error:

https://github.com/pola-rs/polars/blob/c33d7055f1350a362dda2b14b3f7bb8e1c0f5f8a/crates/polars-io/src/csv/parser.rs#L489

We need a new `raise_on_ragged_lines` or `ignore_ragged_lines` argument.

**Comment by Wainberg** [comment]
You don't necessarily even need a new argument - `ignore_ragged_lines` seems like an uncommon use case (maybe I'm missing one though). You can just throw the error always and recommend either:

1. setting `infer_schema_length=None` to parse ragged data with no issues at the cost of speed; or
2. setting `new_columns` to be as long as you need to encompass all the ragged columns. (Assuming you'd like to allow `new_columns` to be longer than the number of columns in the first row, which as @trueb2 points out is supported by pandas.)

**Comment by ritchie46** [comment]
> setting infer_schema_length=None to parse ragged data with no issues at the cost of speed; or

This is super slow and we want the csv readers to work in a streaming fashion. If you only care about the first `n` fields, polars can then effectively read them for you.

**Comment by Wainberg** [comment]
For sure, _if_ you mentioned it in the error, it would definitely have to be with that caveat.

Thoughts on the `new_columns` change? That seems like a more computationally efficient solution.

**Comment by ritchie46** [comment]
Isn't that our existing schema? If that is longer than a row we already fill with nulls.

**Comment by Wainberg** [comment]
I don't think you can use the `dtypes` argument to load both columns of `pl.read_csv(StringIO('A\nB,ragged\nC'), has_header=False)`, because the ragged column doesn't have a name that you can refer to.

In pandas, you can load it with `names`:

```
>>> pd.read_csv(StringIO('A\nB,ragged\nC'), header=None, names=['col1', 'col2'])
  col1    col2
0    A     NaN
1    B  ragged
2    C     NaN
```

But the equivalent code fails in polars:

```
>>> pl.read_csv(StringIO('A\nB,ragged\nC'), has_header=False, new_columns=['col1', 'col2'])
Traceback (most recent call last):
[...]
exceptions.ShapeError: 2 column names provided for a dataframe of width 1
```

Would it be possible to support the same behavior in polars? Currently, I think the only way you can read the entirety of a ragged file (without truncation) is by setting `infer_schema_length=None`, which like you say is generally a bad idea.

**Comment by ritchie46** [comment]
I will add a `schema` argument that lets user define their own schema. That shall resolve the second issue.

**Comment by ritchie46** [comment]
@Wainberg with #10665 you can:

```python
pl.read_csv(io.StringIO('A\nB,ragged\nC'), has_header=False, schema={"A": pl.Utf8, "B": pl.Utf8})
```

**Comment by Wainberg** [comment]
That solves it too! Thanks for taking care of this so quickly.

**Comment by mcrumiller** [comment]
Can this be closed?
