### ISSUE TITLE
`read_csv` whitespace inconsistency (leading trimmed, trailing kept)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10587]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd
from io import StringIO

DATA_NO_SPACE = "str,int,float\nabc,4,5.67"
DATA_LEADING_SPACE = "str,int,float\n abc, 4, 5.67"
DATA_TRAILING_SPACE = "str,int,float\nabc ,4 ,5.67 "

DATA = ...

pl.read_csv(source=StringIO(DATA))
pd.read_csv(filepath_or_buffer=StringIO(DATA))
```

### Issue description

polars `read_csv` treats whitespace inconsitent depending on the location. 
Currenty leading whitespace is removed and trailing whitespace is kept. 
This seems inconsistent and leads to unexpected results (see whitespace in cols and types):

![image](https://github.com/pola-rs/polars/assets/25177421/861d3dd9-0e1a-404b-9416-ca534254d34c)

Pandas on the other hand parses all 3 versions the same and with the "correct" dtypes (str, int, float)
I do NOT say that pandas is correct in ignoring whitespace

I see 3 good options:
- keep ALL whitespace (leading and trailing). Some "unofficial" csv specs say that whitespace is part of a filed and must not be ignored
- trim ALL whitespace (leading and trailing). This is usually what the user expects. If you require leading and trailing whitespaces in a column you can always quote the text
- add an option to `read_csv` like `trim_whitespace`

### Expected behavior

be consistent in either trimming leading and trailing whitespace or keep both or give an option to choose

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by stinodego** [comment]
The types are now parsed correctly, but for string types the leading vs. trailing whitespace is still treated differently. This should probably be fixed.

**Comment by JulianCologne** [comment]
> The types are now parsed correctly, but for string types the leading vs. trailing whitespace is still treated differently. This should probably be fixed.

I don't think you can call it "correct" here because it depends on the interpretation of whitespace.

I remember @ritchie46 wanting to follow the unofficial csv spec which states that all whitespace belongs to the value!

This could make parsing easier and make the str type "correct" for ALL example columns if there is leading/trailing whitespace.

Of course there could also be a parameter to optionally toggle trimming whitespace.

**Comment by akmalsoliev** [comment]
Hey, I am facing similar issue, specifically when there is leading and trailing white space:
`[" 15.44 ", " 18.58 ", … " 15.44 "]`

full error:
```
polars.exceptions.ComputeError: conversion from `str` to `f64` failed in column 'my_column' for 35 out of 222 values: [" 15.44 ", " 18.58 ", … " 15.44 "]
```

**Comment by JulianCologne** [comment]
This is "fixed" in the sense that all whitespace is kept which is according to the csv spec.

You have to "strip" the whitespace after reading and then convert to your desired data type 😉

**Comment by akmalsoliev** [comment]
> This is "fixed" in the sense that all whitespace is kept which is according to the csv spec.
> 
> You have to "strip" the whitespace after reading and then convert to your desired data type 😉

Great! Thanks for the clarification, took that into account. Agree that it is better to have original state.

**Comment by jklymak** [comment]
> This is "fixed" in the sense that all whitespace is kept which is according to the csv spec.
> 
> You have to "strip" the whitespace after reading and then convert to your desired data type 😉

I'm not a huge polars user, but having a `strip=True` argument would be helpful here.  Pandas has `skipinitialspace`, which would have helped our use-case.

**Comment by ritchie46** [comment]
You can strip whitespace later. 

`pl.read_csv(..).select(pl.col(pl.String).str.strip_chars())`

**Comment by jklymak** [comment]
Sure, and then convert the appropriate columns to float, but that is a bit of a song and dance to deal with "malformed" (but pretty common and easier to read?) csv files.
