### ISSUE TITLE
Wrong documentation on polars_core::datatypes::AnyValue::List

### ISSUE THREAD

**Issue by swfsql** [pola-rs/polars#1058]
On it's [definition](https://github.com/pola-rs/polars/blob/4af944380df6ae4408f0e77316e18ae3e3ae6a0c/polars/polars-core/src/datatypes.rs#L230), the `List` has documentation related to "Naive Time", which probably is of another variant or enum.

**Comment by ritchie46** [comment]
Thanks, will fix it!

**Comment by ritchie46** [comment]
Fixed in #1059
