### ISSUE TITLE
`pl.read_csv(gzipped)` reads the wrong number of rows when both `skip_rows` and `n_rows` are specified

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10584]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
print({n_rows: len(pl.read_csv('https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/injuries.tsv.gz', separator='\t', skip_rows=50, n_rows=n_rows)) for n_rows in (12, 13, 60, 61, 62, 63)})  # {12: 12, 13: 12, 60: 12, 61: 12, 62: 42, 63: 42}
```

### Issue description

If you ask for 13-61 rows, it only reads in 12. If you ask for 62 or 63, it jumps to 42. Same issue when downloading the file locally before reading. The issue goes away if you remove either `skip_rows` or `n_rows` or if you `gunzip` beforehand.

### Expected behavior

It should read in exactly `n_rows` each time, so the result should be `{12: 12, 13: 13, 60: 60, 61: 61, 62: 62, 63: 63}`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by mcrumiller** [comment]
I can confirm this odd behavior: this only occurs when the file is gzipped. I believe that it's incorrectly reading the number of lines. The file has 255,064 lines, but we have the following:

```
>>> len(pl.read_csv("injuries.tsv.gz", separator="\t", n_rows=1, skip_rows=61))
1
>>> len(pl.read_csv("injuries.tsv.gz", separator="\t", n_rows=1, skip_rows=62))
exceptions.NoDataError: not enough lines to skip
>>> len(pl.read_csv("injuries.tsv.gz", separator="\t", n_rows=2, skip_rows=61))
1
```
polars thinks there are only 62 rows in the file.
