### ISSUE TITLE
feat: Parsing strings to duration

### ISSUE THREAD

**Issue by ohines** [pola-rs/polars#10593]
### Problem description

Maybe I am missing something but currently there does not seem to be a clean way to convert a string e.g. of format `%H:%M:%S` to a number of minutes/ seconds etc.

# Reproducible example
```python
import polars as pl
from datetime import datetime

df = pl.DataFrame({"a": ["01:00:01"]})

df.with_columns((pl.col("a").str.strptime(pl.Datetime, "%H:%M:%S") - pl.lit(datetime(1, 1, 1))).dt.seconds())
# the target behaviour - converts string to 3601

df.with_columns(pl.col("a").str.strptime(pl.Time, "%H:%M:%S").dt.second())
# Not the target behaviour - converts string to 1

df.with_columns(pl.col("a").str.strptime(pl.Time, "%H:%M:%S").dt.seconds())
# exceptions.SchemaError: invalid series dtype: expected `Duration`, got `time`
# similar of pl.Datetime

df.with_columns(pl.col("a").str.strptime(pl.Duration).dt.seconds())
# ValueError: dtype should be of type {Date, Datetime, Time}
```

I think a good solution might be to implement either (a) `dt.seconds` for `pl.Time` objects similar to `dt.second` (and the same for minutes, hours, ...

Or (b) implement `strptime(pl.Duration)` which may have the added benefit of allowing for e.g
```python
df = pl.DataFrame({"a": ["01:00:01"], "b": ["01:00:02"]})

df.with_columns(
  (
    ((pl.col("a").str.strptime(pl.Datetime, "%H:%M:%S") - pl.lit(datetime(1,1,1)))) + 
    ((pl.col("b").str.strptime(pl.Datetime, "%H:%M:%S") - pl.lit(datetime(1,1,1))))
  ).alias("c")
)
# the target behaviour column `c` is a duration of `2h 3s`

df.with_columns((pl.col("a").str.strptime(pl.Duration) + pl.col("b").str.strptime(pl.Duration)).alias("c"))
# simplified syntax
```

Happy to work on either (a) and/ or (b) if this is something the maintainers would like

**Comment by mcrumiller** [comment]
There's a parse function that converts a standard polars duration string (e.g. `3d1h5m`) to a duration struct [here](https://github.com/pola-rs/polars/blob/main/crates/polars-time/src/windows/duration.rs#L72-L201), but nothing in Python.

**Comment by ohines** [comment]
> it's not really standard to use that in any of our functions.

I that not the standard for `pl.Time`? e.g.
```python
 df = pl.DataFrame({"a":["2023-08-18 22:55:00"]})

df.with_columns(pl.col("a").str.strptime(pl.Time,"%Y-%m-%d %H:%M:%S"))
# returns time object with `22:55:00`
```

**Comment by mcrumiller** [comment]
Oh, my bad! I haven't used `pl.Time` much and probably shouldn't have chimed in.

**Comment by ohines** [comment]
I have since realised that it is possible to do
```
df.with_columns(pl.col("a").str.strptime(pl.Time, "%H:%M:%S").cast(pl.Duration).dt.seconds())
```
I will open a PR that implements option (a) but using `second_of_day` and `minute_of_day`. These functions are roughly equivalent to `day, `weekday` and `ordinal` but for times rather than days.

**Comment by MarcoGorelli** [comment]
If I've understood what you're asking for, I think you could do
```python
In [48]: df
Out[48]:
shape: (1, 1)
┌──────────┐
│ a        │
│ ---      │
│ str      │
╞══════════╡
│ 01:00:01 │
└──────────┘

In [49]: def total_seconds_in_day(time):
    ...:     return time.dt.second() + time.dt.minute()*60 + time.dt.hour()*3600
    ...:

In [50]: df.with_columns(time=pl.col("a").str.strptime(pl.Time, "%H:%M:%S")).with_columns(seconds=total_seconds_in_day(pl.col('time')))
Out[50]:
shape: (1, 3)
┌──────────┬──────────┬─────────┐
│ a        ┆ time     ┆ seconds │
│ ---      ┆ ---      ┆ ---     │
│ str      ┆ time     ┆ u32     │
╞══════════╪══════════╪═════════╡
│ 01:00:01 ┆ 01:00:01 ┆ 3601    │
└──────────┴──────────┴─────────┘
```

If so, then I'm not sure about adding `second_of_day` to the API, am just a bit concerned about this being a rabbit hole for ending up with too much - somebody else could then reasonably say "if you have `second_of_day`, I'd like `second_of_month` and `second_of_year`"

**Comment by ohines** [comment]
Tbf you could keep `second_of_day` and drop `second`, `minute`, and `hour` because they are simple transformations of the former 🚀

**Comment by ohines** [comment]
Closing due to concerns about API bloat.
