### ISSUE TITLE
Rename string namespace `strip` to `strip_chars` - add `strip_prefix`/`strip_suffix`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10603]
### Problem description

`.str.strip(s)` treats `s` as a set and strips them regardless of order. This is different from almost every other library, where `s` is considered either a prefix or suffix to strip. Example:

```shell
>>> s = pl.Series(["aaabbbccc", "aaabbbccc_abcsuffix"])
>>> s.str.strip("abcsuffix")
shape: (2,)
Series: '' [str]
[
        ""
        "_"
]
```

This is not intuitive: `str.strip` detect any of the characters `abcsuffix` and stripped them off from right to left.

**Comment by cmdlineluser** [comment]
It does copy the behaviour of Python's `str.strip()`
```python
>>> "aaabbbccc".strip("abcsuffix")
''
>>> "aaabbbccc_abcsuffix".strip("abcsuffix")
'_'
```
It is not intuitive though as you say, seems like it should have been named `.strip_chars()` or something.


[`.trim_matches()`](https://doc.rust-lang.org/std/primitive.str.html#method.trim_matches) appears to be the equivalent in Rust from what I can tell?

Python 3.9 added `str.removeprefix()` and `str.removesuffix()` which seem to be called `.strip_prefix()` and `.strip_suffix()` in Rust.

**Comment by stinodego** [comment]
This is a tough one.

In itself, I would argue that `strip` is intuitive enough, as it is analogous to Python's `strip`. And it's implemented by `trim_matches` which operates on characters, and I'd say it's useful in its current form.

However, I also agree that a `strip_prefix` and `strip_suffix` would be useful for stripping strings. Easy enough to add, but then there will be confusion over what `strip` does (people will expect it to strip a string rather than characters).

So we can add those, but then we would either have to rename `strip` to something else, or we would have to name `strip_prefix/suffix` something else (e.g. `remove_prefix/suffix` like in Python? I don't really those names though).

**Comment by cmdlineluser** [comment]
Yeah, good points.

The prefix/suffix can currently be done with `.replace()` e.g. `.replace("^prefix", "")` and `.replace("suffix$", "")`

However, if that were to change to `.replace("^prefix", "", regex=True)` 

https://github.com/pola-rs/polars/issues/6120#issuecomment-1374860297

> Regarding the regex arguments
Maybe we should make regex opt-in by adding a regex keyword argument? I am open to a discussion on this.

... then specific prefix/suffix removal functions would become more desirable.

**Comment by ritchie46** [comment]
I agree that we must name what we strip. I would propose `strip_chars`.

**Comment by MarcoGorelli** [comment]
agree

> In itself, I would argue that strip is intuitive enough, as it is analogous to Python's strip.

maybe it's just me, but I've had a bug in one of my packages because a contributor had misunderstood what Python's strip did (and I hadn't noticed when reviewing) 🙈 So I'd support `strip_chars`

**Comment by stinodego** [comment]
I'm OK with `strip_chars`.

Do we want to also add `strip_prefix` and `strip_suffix`? Should be easy enough since they are backed by a Rust native function.

**Comment by ritchie46** [comment]
Yes, let's add those as well.

**Comment by mcrumiller** [comment]
I think to be consistent we should have `lstrip_chars` and `rstrip_chars`.

**Comment by stinodego** [comment]
Ok, after thinking about this a bit more, I think we should do the following:

| Polars (current) | Polars (new) | Rust-equivalent | Python-equivalent |
| -- | -- | -- | -- |
| `strip` | `strip_chars` | `trim_matches` | `strip` |
| `lstrip` | `strip_chars_start` | `trim_start_matches` | `lstrip` |
| `rstrip` | `strip_chars_end` | `trim_end_matches` | `rstrip` |
| - | `strip_prefix` | `strip_prefix` | `removeprefix` |
| - | `strip_suffix` | `strip_suffix` | `removesuffix` |

Rust makes a somewhat arbitrary distinction between `trim` and `strip`. ChatGPT tells me the two are quite similar in meaning:

<details>

> "Strip" and "trim" are two words that are often used interchangeably, but they can have slightly different meanings depending on the context. Here are the primary differences:
> 
> ### Strip:
> 
> * To remove or take off: When you "strip" something, you are typically removing or taking off a layer, covering, or part of something. For example, you can strip paint from a wall, strip the bark from a tree, or strip the outer layer of a wire to expose the metal underneath.
> 
> * To remove clothing: "Stripping" can also refer to the act of removing clothing or garments, often in a sensual or provocative manner, as in a striptease.
> 
> ### Trim:
> 
> * To cut or reduce: "Trimming" involves cutting away or reducing the size, length, or excess of something. For instance, you can trim the branches of a tree, trim your hair, or trim a piece of fabric to make it fit better.
> 
> * To make neat or orderly: "Trim" can also refer to making something neat, orderly, or well-groomed. For example, you can trim the edges of a lawn to make it look tidy, or you can trim a document to remove unnecessary words or content.
> 
> In summary, while "strip" often involves removing or taking off something, "trim" usually involves cutting or reducing something to make it neater or more manageable. However, there can be overlap between these terms in certain contexts, so it's important to consider the specific situation and usage to determine the correct meaning.

</details>

Reading this, I get how the Rust devs arrived at `trim` for stripping characters/whitespace and `strip` for whole strings. But I feel like `strip_chars` is more explicit and it helps discoverability to have these similar methods named similarly.

@ritchie46 are you on board with this as well? Then @henrikig can finish up his PRs for these :)

**Comment by mcrumiller** [comment]
@stinodego we had a debate about this earlier with @orlp and we settled on `head` and `tail` for substrings at the start/end of the string. Do you think `strip_chars_head`/`strip_chars_tail` would be more consistent?

**Comment by stinodego** [comment]
You mean `strip_chars_head` instead of `strip_chars_start`? I'd rather follow the Rust convention here.

**Comment by mcrumiller** [comment]
I did. I just wanted to bring that up, I'm fine with `start`.

**Comment by stinodego** [comment]
The only part I don't really like is that `strip_chars` doesn't really indicate that it will remove whitespace if no input is given. But do we really want a separate `strip_whitespace` set of methods? I don't think so.

**Comment by orlp** [comment]
@mcrumiller How I see it is that `head` and `tail` refer to a specific subsection of respectively the `start` and `end`. They are not directions. To give an analogy by changing axis to vertical, head and tail are like "top and bottom" whereas start and end are like "up and down".

 So I would also prefer `start` and `end`.

@stinodego I like your proposal 👍 

> The only part I don't really like is that strip_chars doesn't really indicate that it will remove whitespace if no input is given. But do we really want a separate strip_whitespace set of methods? I don't think so.

I think stripping whitespace by default is fine. I think Rust would've done the same if it had default arguments in the first place.

**Comment by orlp** [comment]
So in line with @stinodego's proposal we have the following steps:

- [ ] Rename `strip` to `strip_chars`
- [ ] Rename `lstrip` to `strip_chars_start`
- [ ] Rename `rstrip` to `strip_chars_end`
- [ ] Add a new function `strip_prefix` that removes a specified argument string from the beginning of the input string **at most once**. So `"foofoo".strip_prefix("foo") == "foo"`.
- [ ] Similarly, add a function `strip_suffix` that works the same as `strip_prefix` except at the end of the input string.

There is only the question of whether `strip_prefix`/`strip_suffix` should support Regex arguments. My vote would go towards no, that functionality is already covered by `.str.replace("^pat", "")` and `.str.replace("pat$", "")`, and I don't think that it could be made significantly more efficient by 'specializing' into something that only removes from the start/end. But please do correct me if I'm wrong here.

**Comment by henrikig** [comment]
> So in line with @stinodego's proposal we have the following steps:
> 
> * [ ]  Rename `strip` to `strip_chars`
> * [ ]  Rename `lstrip` to `strip_chars_start`
> * [ ]  Rename `rstrip` to `strip_chars_end`
> * [ ]  Add a new function `strip_prefix` that removes a specified argument string from the beginning of the input string **at most once**. So `"foofoo".strip_prefix("foo") == "foo"`.
> * [ ]  Similarly, add a function `strip_suffix` that works the same as `strip_prefix` except at the end of the input string.

Made some changes to the two PRs (#10813 and #10958), so they should now be ready for final reviews. In total, they address the five proposed changes listed in this comment.

**Comment by ritchie46** [comment]
Good for me. :) Thanks all.
