### ISSUE TITLE
groupby fails: InvalidOperationError: `vec_hash_combine` operation not supported for dtype ...

### ISSUE THREAD

**Issue by wKollendorf** [pola-rs/polars#10610]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

**Not working**
```
df = pl.DataFrame({
	"a": [1,2,3]
	,"b": [[1],[2],[3]]
	,"c": [1,2,3]
}).groupby(pl.all().exclude("c"), maintain_order=True).all()
```
**Working**
```
df = pl.DataFrame({
	"a": [1,2,3]
	,"c": [1,2,3]
}).groupby(pl.all().exclude("c"), maintain_order=True).all()
```
**Working**
```
df = pl.DataFrame({
	"b": [[1],[2],[3]]
	,"c": [1,2,3]
}).groupby(pl.all().exclude("c"), maintain_order=True).all()
```

### Issue description

When grouping a dataframe containing mixed dtype (list + any other) the operation fails with:
```
exceptions.InvalidOperationError: `vec_hash_combine` operation not supported for dtype `list[i64]`
```

### Expected behavior

Grouping works with any dtype combination.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-6.1.0-10-amd64-x86_64-with-glibc2.36
Python:              3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by reswqa** [comment]
When perform group-by over multiple keys, we need combine the hashes of all these keys. I guess we can not find a suitable way to combine the hash of a list with other keys. 🤔

**Comment by ritchie46** [comment]
We must implement the trait `VecHash` for `ListChunked` similar to how we implemented `IntoGroupsProxy` for `ListChunked`.

Most of the code in `IntoGroupsProxy` can be reused.

**Comment by reswqa** [comment]
Thanks!, Very helpful prompt information, let me try to implement it. 😄
