### ISSUE TITLE
Unexpected difference between negating and filtering using == and is_in()

### ISSUE THREAD

**Issue by lyngc** [pola-rs/polars#10613]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Polars
```
import polars as pl
df = pl.DataFrame({
    "a": [1, 2, None],
    "b": ["1", "2", "3"]
})
df.filter(~(pl.col("a") == 2)) # returns first row only
df.filter(~(pl.col("a").is_in([2]))) # returns first and last row
```
Pandas
```
import pandas as pd
df = pd.DataFrame({
    "a": [1, 2, None],
    "b": ["1", "2", "3"]
})
df.loc[~(df["a"] == 2)] # returns first and last row
df.loc[~(df["a"].isin([2]))] # returns first and last row

```

### Issue description

In this example, we are trying to remove rows where `pl.col("a") == 2`.
However, there is a difference in what rows that get removed when negating and either checking this using `==` or `is_in()`.

When using `==` also the last row in the dataframe gets removed, although it is not equal to 2. When checking this using `is_in()`, the last row is kept as expected. This might unexpectedly remove data that is not intended to be removed.

There is no difference in Pandas where the first and last row is kept with either logic.

I feel like this difference is quite dangerous as I would probably write `~(pl.col("a") == 2)` when there is only one condition to exclude rows, but if there are two conditions, then I would write that as `~(pl.col("a").is_in([2, 3]))`.

### Expected behavior

Only rows that satisfy the condition `pl.col("a") == 2` should be removed.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.6.3
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Nulls propagate in `==`. You must use `eq_missing` to have nulls evaluate as `False`.

**Comment by lyngc** [comment]
Seems a bit unintuitive that `is_in()` is not just an extension of many `==` checks. Also requires some Polars knowledge to know this and not make mistakes, which makes it harder to persuade the team into migrating towards Polars from Pandas.

**Comment by ritchie46** [comment]
Pandas nullable dtypes behave the same. 

```python
import pandas as pd

arr = pd.array([1, 2, None], dtype=pd.Int64Dtype())
arr == 2
```

```
<BooleanArray>
[False, True, <NA>]
Length: 3, dtype: boolean
```

Polars already does what pandas wants to do in the future on this respect. Current defaults in pandas are no reason to have them in polars.

**Comment by lyngc** [comment]
Thanks for the explanation. Polars is amazing and appreciate all the work you guys are doing!

**Comment by ritchie46** [comment]
I think we must propagate nulls in `is_in` as well to fix the inequality. Will look at that.
