### ISSUE TITLE
consolidate clip, clip_max, clip_min

### ISSUE THREAD

**Issue by Sage0614** [pola-rs/polars#10628]
### Problem description

for the reason described in #10618 , it is better to consolidate `clip`, `clip_max`, `clip_min` api 

into just `clip` , `clip( lower_bound = -math.inf)` `clip(upper_bound = math.inf)`

**Comment by stinodego** [comment]
I think it's fair to set the arguments for `clip` to `None` by default, and internally dispatch to `clip_max`/`clip_min` if there is no upper/lower bound. And ValueError if both are None. We can get rid of `clip_max` and `clip_min`.

I think that would be an API improvement.
