### ISSUE TITLE
consolidate `eq`/`eq_missing` and `ne`/`ne_missing`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10657]
### Problem description

As per #10618, we can update to `eq(missing=True)` and get rid of `eq_missing`, same with `ne`.

I actually think we should have the parameter named `null_equal`, as in [frame_equal](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.frame_equal.html), since that's a bit more descriptive. But I *also* think `nulls_equal` (plural) would be even better. Thoughts?

**Comment by ritchie46** [comment]
I don't want go too far with this as it deviates our API from the rust API. Having an `eq_missing` doesn't save you any characters/ nor more or less explicitness. 

For the docs argument, we should add a `See Also` section.

**Comment by mcrumiller** [comment]
Closing as the docs were updated instead.
