### ISSUE TITLE
concat_list does not work for one item in groupby context

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#10659]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a":[1,2,3], "b":[1,1,1]})

df.select(pl.concat_list(pl.sum("a")))
df.groupby("b").agg(pl.concat_list(pl.sum("a")))
```

### Issue description

`pl.concat_list` works fine in `select` context but not in `groupby` context with the following error message:
```
exceptions.ComputerError: cannot aggregate, the column is already aggregated
```

### Expected behavior

`df.groupby("b").agg(pl.concat_list(pl.sum("a")))` will generate:
```
c     a
---  --------
i64  list[i64]
---  --------
1     [6]
```

### Installed versions

<details>

```
0.18.15
```

</details>

**Comment by reswqa** [comment]
Why not use `df.groupby("b").agg(pl.sum("a"))` directly? IIUC, double aggregation is forbidden by design.

**Comment by Arengard** [comment]
is this... it?

´´´df.groupby("b").agg(pl.sum("a").implode())´´´

**Comment by stinodego** [comment]
> is this... it?

Right, that is actualy the way to go here.

The code in the original post doesn't work, because the `concat_list` wraps the aggregation. So then there will be two aggregations which doesn't make sense.

**Comment by paladin158** [comment]
> Why not use `df.groupby("b").agg(pl.sum("a"))` directly? IIUC, double aggregation on group is forbidden by design.

I update my original post, where I just provided a minimal example without putting many background. The reproducible is just one case of a general use case.

**Comment by paladin158** [comment]
> I am not 100% sure this is a bug...
> 
> For reference, after the new release of Polars, you will be able to achieve the desired behavior by using `cast`:
> 
> ```python
> df.groupby("b").agg(pl.col("a").sum().cast(pl.List(pl.Int64)))
> ```
> 
> Or simply use `concat_list` AFTER your groupby operation:
> 
> ```python
> df.groupby("b").agg(pl.col("a").sum()).with_columns(concat_list("a"))
> ```

For the cast, I do need to make sure the inner dtype is consistent with the original dtype. For your second solution, please read my updated post, where I just want to make a general code work in the case where there is only one element.
