### ISSUE TITLE
Support `Expr.fill_null(strategy="min")` for string columns

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10666]
### Problem description

As reported in #9284

The following does not work:

```python
import polars as pl

s = pl.Series(["a", None, "c", None, "e"])

s.fill_null(strategy="min")
# InvalidOperationError: fill-null strategy Min is not supported
```

This is supported for integer columns, would be nice if this could also work on string columns.

**Comment by mcrumiller** [comment]
Since categoricals have an ordering (lexical vs physical) we should probably support those too if it's not too difficult. Not sure if should be separate issue.
