### ISSUE TITLE
read_ndjson truncates strings with utf8 escape sequences

### ISSUE THREAD

**Issue by alexzubiaga** [pola-rs/polars#10661]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Reading json strings containing unicode escape sequences truncates the end of the string.

```python
pl.read_ndjson(r'{"field": "\ufffd1234"}'.encode('utf-8'))
```

Returns the truncated string "\ufffd1" instead of the expected "\ufffd1234"
```
shape: (1, 1)
┌─────────┐
│ field   │
│ ---     │
│ str     │
╞═════════╡
│ \ufffd1 │
└─────────┘
```

### Issue description

read_json, scan_json and scan_ndjson are also affected.

### Expected behavior

I would expect the full string "\ufffd1234"

```
shape: (1, 1)
┌────────────┐
│ field      │
│ ---        │
│ str        │
╞════════════╡
│ \ufffd1234 │
└────────────┘
```

### Installed versions

<details>

```--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.3.0
matplotlib:          <not installed>
numpy:               1.23.5
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            1.10.4
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cjackal** [comment]
This issue has been reported several times: #9791, #10034

I have tried to debug this issue myself but this one is really tough; regression happens at `polars==0.18.4` but git + compilation flag diff say little about the cause.

**Comment by ritchie46** [comment]
@orlo could you take a look at this one?

**Comment by ritchie46** [comment]
This is similar to #9791. I believe there is something UB going on. This only occurs in the released python binaries and not in develop builds. I couldn't reproduce this in a rust release build.

Given that this occurs in both json and ndjson, I expect this happens in simdjson, but I am not entirely sure.

If we have a repro in rust we can better verify what happens.

**Comment by ritchie46** [comment]
> So I can reproduce on Apple M1 with `make build-release`, but not with `make build-opt`. I suspect it's something that only triggers with `lto="fat"`. Testing that now.

Good luck with the bug hunt!

**Comment by orlp** [comment]
Just `lto="fat"` wasn't enough, trying again with `lto="fat", incremental=false, codegen-units=1`. If that doesn't work then the only differentiator is... `debug`. Which is going to be fun if it only occurs with `debug=false`.

**Comment by ritchie46** [comment]
> Which is going to be fun if it only occurs with debug=false.

Ouch, that would be terrible. 🙈
