### ISSUE TITLE
Series constructor ignores time zone of Datetime `dtype` 

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10662]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime
import polars as pl

s = pl.Series(
    "date",
    [datetime(2010, 1, 1)],
    dtype=pl.Datetime(time_zone="EST"),
)
```
```
shape: (1,)
Series: 'date' [datetime[μs]]
[
        2010-01-01 00:00:00
]
```

### Issue description

See title.

Using `lit` I can produce the correct result:

```python
pl.select(
    pl.lit(datetime(2010, 1, 1), dtype=pl.Datetime(time_zone="EST")).alias("date")
).to_series()
```

### Expected behavior

The output should have the given time zone:

```
shape: (1,)
Series: 'date' [datetime[μs, EST]]
[
        2010-01-01 00:00:00 EST
]
```

### Installed versions

main

**Comment by stinodego** [comment]
Maybe @MarcoGorelli is interested in taking a look at this one?

**Comment by MarcoGorelli** [comment]
sure, thanks! self-assigning then, but if anyone from the community wants to give this a go, feel free to ping and I'll leave it to them
