### ISSUE TITLE
Using wildcard as join key leads to panic

### ISSUE THREAD

**Issue by 0xbe7a** [pola-rs/polars#10663]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.show_versions()

df = pl.DataFrame({"x": [1]})
df2 = pl.DataFrame({"x": [1], "y": [2]})
df.join(df2, on=pl.all())
```

### Issue description

Polars panics when using a wildcard expression as a join key

```
thread '<unnamed>' panicked at 'should be no wildcard at this point', local_dependencies/polars-plan/src/logical_plan/aexpr/schema.rs:210:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/belastoyan/Documents/polars-bug-playground/minimal.py", line 7, in <module>
    df.join(df2, on=pl.all())
  File "/Users/belastoyan/micromamba/envs/polars/lib/python3.11/site-packages/polars/dataframe/frame.py", line 5814, in join
    .join(
     ^^^^^
  File "/Users/belastoyan/micromamba/envs/polars/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 3209, in join
    self._ldf.join(
pyo3_runtime.PanicException: should be no wildcard at this point
```

### Expected behavior

Polars should either throw an exception if the operation is unsupported or perform the join over all columns of df.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I think we should return an error here. Currently we don't know to which schema we need to expand and we don't support SET expansions (where we take the SET DIFFERENCE of 2 schemas).

**Comment by mcrumiller** [comment]
This was discussed [here](https://github.com/pola-rs/polars/issues/10390#issuecomment-1671496947) already in #10390. Not sure if there was any resolution to that conversation.

**Comment by stinodego** [comment]
I changed the panic to a `ComputeError`.

It would be nice to be able to actually support something like this - but it's not immediately clear to me what the wildcard should expand to. A new issue with a feature request is welcome to discuss this further.
