### ISSUE TITLE
scan_csv dtypes assignment throws unsupported data type when used with streaming

### ISSUE THREAD

**Issue by michauorin** [pola-rs/polars#10672]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars

# Assigning dtype works as expected when using scan_csv without streaming
with open("test_positive.csv",'w') as file:
    file.write("a\n0\n127\n255\n4000")
polars.scan_csv("test_positive.csv", dtypes={'a':polars.UInt8})\
    .collect()

# The same operation throws unsupported data type with streaming
with open("test_negative.csv",'w') as file:
    file.write("a\n0\n127\n255\n4000")
polars.scan_csv("test_negative.csv", dtypes={'a':polars.UInt8})\
    .collect(streaming=True)

# ComputeError: unsupported data type when reading CSV: u8 when reading CSV

```

### Issue description

Using scan_csv combined with .collect(streaming=True) throws an unsupported data type error with certain data types.

It is possible to assign [U]Int32 or 64, but the same operation for integers of size 16 and 8 throws an error.

Both assignments work as expected when using just .collect() without streaming.

### Expected behavior

Scan-collect will produce a dataframe with column a of type UInt8:

```
a
--
u8
0
127
255
null
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.14.0-162.18.1.el9_1.x86_64-x86_64-with-glibc2.34
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by reswqa** [comment]
Throw exception is the correct behavior for your example. If you want to set the failed parsing value to `null`, you should set `ignore_errors=True` for  `scan_csv`.

BTW, I also test this with & without `streaming` mode in current main branch, both of them throw exception. This may fixed via #10641.

**Comment by michauorin** [comment]
Excuse me the bad example, I needlessly added the failed parsing.

The following code also throws an exception for me despite all rows fitting into an UInt8:
```python
import polars

with open("test.csv",'w') as file:
    file.write("a\n0\n1\n2\n3")
polars.scan_csv("test.csv", dtypes={'a':polars.UInt8})\
    .collect(streaming=True)

# ComputeError: unsupported data type when reading CSV: u8 when reading CSV
```

Furthermore, even after adding `ignore_errors=True` collect throws the same error, regardless of the presence of over-limit integers in the csv or lack of thereof.

Thanks for the pointer though!
I will try getting the current main branch to see if the linked PR fixes this behaviour.

**Comment by reswqa** [comment]
Ok, now I see your point. This error seems still exist in main branch if there are no issues with my build.
