### ISSUE TITLE
`Series.eq` does not work correctly for `List` types

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10698]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([[1], [1,2]])
s == [1]
```
```
shape: (1,)
Series: '' [bool]
[
        true
]
```

### Issue description

I tried various variations for comparison, but it seems like broadcasting does not work correctly here. The result is always of length 1.

### Expected behavior

```
shape: (2,)
Series: '' [bool]
[
        true
        false
]
```

### Installed versions

main

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/10138 has also cropped up a couple of times recently which looks like it could be the same (or related) underlying issue.
