### ISSUE TITLE
Implement in-place `Series.invert` method for boolean series

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#10699]
### Problem description

Required for [#10035](https://github.com/pola-rs/polars/issues/10035)

I need a way to invert a bitmask in a zero-copy manner. Something like:

```
import polars as pl

s = pl.Series([True, False])
s.invert()
print(s)
```
```
shape: (2,)
Series: '' [bool]
[
        false
        true
]
```

I know I can do `s == False`, but this will do a copy.

**Comment by ritchie46** [comment]
We often are not allowed to do that in place as the data is owned by one or multiple tables. I think we should just allocate for this one.

**Comment by stinodego** [comment]
All right, can do that 👍 

We might be able to implement this later if there is a specific need for this.
