### ISSUE TITLE
CI failing for Python Windows 3.11

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10693]
### Issue description

Seeing this on recent pull requests:

https://github.com/pola-rs/polars/actions/runs/5955162773/job/16153193024?pr=10696

### Test Python / windows (3.11)
```
   ...
   Compiling rand_chacha v0.3.1
error[E0463]: can't find crate for `ppv_lite86`
  --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rand_chacha-0.3.1\src\guts.rs:12:5
   |
12 | use ppv_lite86::{dispatch, dispatch_light128};
   |     ^^^^^^^^^^ can't find crate
...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "D:\\a\\polars\\polars\\py-polars\\Cargo.toml" "--lib"`
```

**Comment by stinodego** [comment]
I tried Googling this but I couldn't come up with anything... 😕

**Comment by mcrumiller** [comment]
Not sure why it's claiming it can't find `ppv-light86` on crates.io, I have no problem installing it locally.

**Comment by mcrumiller** [comment]
Ok, I'm noticing that the error says it can't find `ppv_light86`. The package uses a hyphen and not an underscore. Is something doing a string replacement somewhere?

**Comment by mcrumiller** [comment]
I think for some reason the compilation order isn't following the dependency list. I'm not sure how to go about fixing this, but I just [finally] set up my windows environment to compile everything and it went fine.

In the output I linked above, we have:
```
   NOTE: above this, ppv-lite86 was never compiled beforehand
   ...
   Compiling polars-arrow v0.32.0 (D:\a\polars\polars\crates\polars-arrow)
   Compiling rawpointer v0.2.1
   Compiling matrixmultiply v0.3.7
   Compiling rand_chacha v0.3.1
error[E0463]: can't find crate for `ppv_lite86`
  --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rand_chacha-0.3.1\src\guts.rs:12:5
   |
12 | use ppv_lite86::{dispatch, dispatch_light128};
   |     ^^^^^^^^^^ can't find crate
```
When I compile locally, `ppv-lite86` is compiled beforehand:
```
   Compiling rand_core v0.6.4                                                                                                                                                                                                                                                                                                                   
   Compiling polars-arrow v0.32.0 (D:\Projects\polars\crates\polars-arrow)
   Compiling ppv-lite86 v0.2.17          <---see here
   Compiling rawpointer v0.2.1
   Compiling heck v0.4.1
   Compiling rand_chacha v0.3.1          <---see here
   Compiling crossterm_winapi v0.9.1
```

Did something happen and a proper dependency graph is no longer being generated?

**Comment by mcrumiller** [comment]
Another update: the `Cache Rust` step is failing due to space limitations. If you go to https://github.com/pola-rs/polars/actions/caches you'll see:

![image](https://github.com/pola-rs/polars/assets/1896992/1eae0292-77a1-4d8d-bead-432d1c431b2a)

I don't know if this is related or not. The [page on Caches in github](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) seems to indicate it's involved in dependencies. I don't know the details but this might be a place to start looking.

**Comment by stinodego** [comment]
The cache storage limit doesn't matter - GitHub will just start evicting old caches to create new ones.

But caches might be involved - let's see what happens if I get rid of the existing caches.

**Comment by stinodego** [comment]
Yep, deleting the cache seems to have done it.

We actually ran into cache issues before and I have an issue open for it, will have to give it some priority.
#10148

**Comment by stinodego** [comment]
@mcrumiller Thanks a lot for the assistance here, by the way!

**Comment by mcrumiller** [comment]
Happy to help!
