### ISSUE TITLE
write_excel method is overwriting the existing sheet there is no option to append data

### ISSUE THREAD

**Issue by gm-gwu** [pola-rs/polars#10692]
### Problem description

While writing data to an existing Excel file, If there is an existing sheet, the write_excel method overwrites the entire sheet instead of appending data from the specified position, previous data is lost. All the other sheets are also deleted. 

Is there a feature planned similar to pandas.ExcelWriter to overlay if sheet exists?

**Comment by alexander-beedie** [comment]
> Is there a feature planned similar to pandas.ExcelWriter to overlay if sheet exists?

Thanks for the request; you can write multiple DataFrames to a single sheet, but _only_ if you are creating them all in the same Workbook context. You cannot, however, take an _existing_ workbook, open it, and append new frame data into an existing sheet. This feature is not planned, as the underlying library that we use to write Excel data (`xlsxwriter`) does not support this.

In case it is sufficient for your use-case, here's an example of writing multiple frames to the same sheet:
```python
from xlsxwriter import Workbook
import polars as pl

df1 = pl.DataFrame( {"x":["aa","bb","cc"], "y":[123,234,345]} )
df2 = pl.DataFrame( {"x":["mm","nn","oo"], "y":[456,567,456]} )
df3 = pl.DataFrame( {"x":["xx","yy","zz"], "y":[345,234,123]} )

with Workbook( "dataframe.xlsx" ) as wb:
    df1.write_excel(wb, worksheet="sheet1", position="B4", table_style="Table Style Light 9")
    df2.write_excel(wb, worksheet="sheet1", position="B9", table_style="Table Style Light 11")
    df3.write_excel(wb, worksheet="sheet1", position="B14", table_style="Table Style Light 14", 
        hide_gridlines = True,
        sheet_zoom = 125,
        autofit = True,
    )
```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/pola-rs/polars/assets/2613171/04c5954f-9097-4179-8191-15b89f70a9b2" width="228">
  <img src="https://github.com/pola-rs/polars/assets/2613171/99e51d69-fb76-47fa-b036-a4dd536c38dc" width="228">
</picture>
