### ISSUE TITLE
Pyarrow 5.0.0 is released

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1069]
Pyarrow 5.0.0 is released:
https://arrow.apache.org/release/5.0.0.html

I don't think there are big (incompatible) changes, so I assume polars should work with both 4.0.* and 5.0.* (`py-polars/pyproject.toml`).

**Comment by ritchie46** [comment]
Yes good one. Both should work indeed.

**Comment by ghuls** [comment]
I only don't know how to specify multiple major versions:

https://www.python.org/dev/peps/pep-0440/#id61 lists only examples for subversions.

Not sure it this works:
```
diff --git a/py-polars/pyproject.toml b/py-polars/pyproject.toml
index a1f3851..18dac2e 100644
--- a/py-polars/pyproject.toml
+++ b/py-polars/pyproject.toml
@@ -8,7 +8,7 @@ dependencies = [
     "numpy",
     # the Arrow memory format is stable between 4.0 and 5.0-SNAPSHOTS
     # (which the Rust libraries use to take advantage of Rust API changes).
-    "pyarrow==4.0.*"
+    "pyarrow==4.0.*,5.0.*"
 ]
```

**Comment by ritchie46** [comment]
Isn't it something like `pyarrow>=4.0`?

**Comment by ritchie46** [comment]
fixed and released.
