### ISSUE TITLE
pl.read_database exception results in dumping plaintext connection string (including username and password) to logs

### ISSUE THREAD

**Issue by apbeers** [pola-rs/polars#10697]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
query = 'select * from my_table'
connection_string = f'snowflake://{mock_user}:{mock_pwd}@account/database/schema?warehouse=warehouse&role=role'   
return pl.read_database(query, connection_string)

pyo3_runtime.PanicException: not implemented: Connection: snowflake://plaintext_user:plaintext_pwd@account/database/schema?warehouse=warehouse&role=role not supported!!
```
I obfuscated the query and connection info, but I’m currently running the same query using the official snowflake library. My issue is not that the connection threw an exception, it is that the exception dumped plaintext credentials to the log output

### Issue description

When a pl.read_database() connection throws an exception, it dumps the plaintext credentials to the logs. I was running my query against an internal snowflake instance.

### Expected behavior

I except the sensitive credentials to be obfuscated in the log output

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Windows-10-10.0.22000-SP0
Python:              3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
 
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by zundertj** [comment]
As you are not setting the `engine` argument, `read_database` defaults to [ConnectorX](https://github.com/sfu-db/connector-x) as the driver. The error message is beyond the control of Polars. I would suggest to open a ticket on their issue tracker.

**Comment by alexander-beedie** [comment]
FYI: you should be using `read_database_uri` for this call ;)

I think we can add some basic mitigation for this problem (and I have just done so), but as @zundertj says you should really raise this Issue with `connectorx`, as it's their error being generated here.
