### ISSUE TITLE
Add support for cast `LargeUtf8` to `LargeList(LargeUtf8)`

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10709]
### Problem description

I have a huge dataset (almost million JSONs) containing a lot of nested fields that can either have String Dtype or List(String) Dtype. Ideally everything should be in this dataset a list of Strings. Currently there is no quick way of casting all these fields automatically to List(string). So I need to load everything with a lot of custom Struct schema's and then using `.str.json_extract` :

Small example of the current workflow:
```python
df = pl.DataFrame(
    pl.Series("dict", [json.dumps(item) for item in data["dicts"]])
)

df.with_columns(
    pl.col("dict").str.json_extract(struct_schema_default).alias("parsed_dict_utf"), # This reads everything as UTF8
    pl.col("dict").str.json_extract(struct_schema_list_version).alias("parsed_dict_list"), # This reads  everything as List(Utf8)
)
```
Then there are a lot of coalesce and concat_list steps to combine the UTF8 and List(Utf8) columns.

But if the below casting would be supported,
```python
ArrowErrorException: NotYetImplemented("Casting from LargeUtf8 to LargeList(Field { name: \"item\", data_type: LargeUtf8, is_nullable: true, metadata: {} }) not supported")
```
Then it could be simplified very much because I only need one struct schema instead of 15+ schema's. To parse all fields that contain Utf8 automatically to LargeList(Utf8)

**Comment by reswqa** [comment]
This should supports in upstream. I have already supported the conversion of `primitive type` -> `LargeList type`. Unfortunately, just now I checked and there seems to be some issues with the implementation, missing support for `Binary`, `Utf8 / LargeUtf8`, `Boolean`. I will find time to fix it.

**Comment by ion-elgreco** [comment]
> This should supports in upstream. I have already supported the conversion of `primitive type` -> `LargeList type`. Unfortunately, just now I checked and there seems to be some issues with the implementation, missing support for `Binary`, `Utf8 / LargeUtf8`, `Boolean`. I will find time to fix it.

Awesome! This would tremendously reduce the boilerplate code to parse my data 😄

**Comment by elseagle** [comment]
@reswqa - thanks for the reply on this. We are also facing same issue in my company and I wanted to follow up, if you had fixed this on have it on roadmap to be fixed soon. Thanks!

**Comment by reswqa** [comment]
>  if you had fixed this on have it on roadmap to be fixed soon.

Yes, on my roadmap. I will find time to fix it as soon as possible.
