### ISSUE TITLE
series arg_min & arg_max seems inconsistent with min & max

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10707]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

The following comments about whether it is okay are just my intuition and may not necessarily be correct.

```python
    int_has_null = pl.Series("a", [None, 1], dtype=pl.Int32)
    assert int_has_null.max() == 1 # ok
    assert int_has_null.min() == 1 # ok 
    assert int_has_null.arg_max() == 1 # ok
    assert int_has_null.arg_min() == 0 # weird

    int_all_null = pl.Series("a", [None], dtype=pl.Int32)
    assert int_all_null.max() is None # ok 
    assert int_all_null.min() is None # ok 
    assert int_all_null.arg_max() == 0 # ok
    assert int_all_null.arg_min() == 0 # ok

    boolean_has_null_true = pl.Series("a", [None, True], dtype=pl.Boolean)
    assert boolean_has_null_true.max() is True # ok
    assert boolean_has_null_true.min() is True # ok, maybe.
    assert boolean_has_null_true.arg_max() == 1 # ok
    assert boolean_has_null_true.arg_min() == 0 # weird

    boolean_has_null_false = pl.Series("a", [None, False], dtype=pl.Boolean)
    assert boolean_has_null_false.max() is False # ok
    assert boolean_has_null_false.min() is False # ok
    assert boolean_has_null_false.arg_max() is None # weird
    assert boolean_has_null_false.arg_min() == 0 # weird

    boolean_all_null = pl.Series("a", [None], dtype=pl.Boolean)
    assert boolean_all_null.max() is None # ok
    assert boolean_all_null.min() is None # ok
    assert boolean_all_null.arg_max() == 0 # ok
    assert boolean_all_null.arg_min() == 0 # ok

```

### Issue description

I believe part of the reason is that we did not consider null value when calculating `min` & `max`, but we did consider this when calculating the `arg` counterpart, and we used the comparison rule for `Option<T>` in rust (i.e. `None < Some (_)`).

### Expected behavior

Not very sure which behavior is right(though I tend to the behavior of `min&max`), but at least they should be consistent.

### Installed versions

<details>

Main branch.

</details>

**Comment by reswqa** [comment]
I can submit a PR to keep them consistent, but before that, we need to identify which behavior is what we want. @ritchie46  Any thought about this?

**Comment by ritchie46** [comment]
Yes, they should be consistent.

**Comment by reswqa** [comment]
Do you also prefer the way of handling null values in min/max?

**Comment by ritchie46** [comment]
I am not sure, but I think `arg_min` should always point to the same value as the `min`.

**Comment by reswqa** [comment]
> `arg_min` should always point to the same value as the min.

Yes, the key point is that we treat `None` as the minimum value for `arg` operation, but not for `non-arg` operation. In theory, modifying either side can ensure that `arg_min` point to the same value as `min`, but if we choose `min` to fit `arg-min`, the following behavior may seem strange to me:

```python
s = pl.Series("a", [None, 1], dtype=pl.Int32)
assert s.min() == None
```

**Comment by ritchie46** [comment]
I think we should modify arg_min to point to the minimal non-null values

**Comment by orlp** [comment]
So, how I see it, is that `null` values should always (at least by default) be consistently treated as not being there at all unless there is a very good reason otherwise.

**Comment by reswqa** [comment]
> null values should always (at least by default) be consistently treated as not being there at all

IIUC, your suggestion as follows:

```python
    int_all_null = pl.Series("a", [None, None, None], dtype=pl.Int32)
    assert int_all_null.max() is None
    assert int_all_null.min() is None
    assert int_all_null.arg_max() == None
    assert int_all_null.arg_min() == None
```

**Comment by orlp** [comment]
@reswqa That is correct, my proposal would give the following answers for your test cases above

```rust
    int_has_null = pl.Series("a", [None, 1], dtype=pl.Int32)
    assert int_has_null.max() == 1
    assert int_has_null.min() == 1
    assert int_has_null.arg_max() == 1
    assert int_has_null.arg_min() == 1

    int_all_null = pl.Series("a", [None], dtype=pl.Int32)
    assert int_all_null.max() is None
    assert int_all_null.min() is None
    assert int_all_null.arg_max() == None
    assert int_all_null.arg_min() == None

    boolean_has_null_true = pl.Series("a", [None, True], dtype=pl.Boolean)
    assert boolean_has_null_true.max() is True
    assert boolean_has_null_true.min() is True
    assert boolean_has_null_true.arg_max() == 1
    assert boolean_has_null_true.arg_min() == 1

    boolean_has_null_false = pl.Series("a", [None, False], dtype=pl.Boolean)
    assert boolean_has_null_false.max() is False
    assert boolean_has_null_false.min() is False
    assert boolean_has_null_false.arg_max() == 1
    assert boolean_has_null_false.arg_min() == 1

    boolean_all_null = pl.Series("a", [None], dtype=pl.Boolean)
    assert boolean_all_null.max() is None
    assert boolean_all_null.min() is None
    assert boolean_all_null.arg_max() == None
    assert boolean_all_null.arg_min() == None
```
