### ISSUE TITLE
Enable string cell wrapping in Notebook HTML

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#10704]
### Problem description

In order to dispaly whitespace charatctoer `\n`, this PR (https://github.com/pola-rs/polars/pull/10644) disabled text wrapping in Notebook html.

Currently, notebook html dynamically adjusts wrapping based on the resizing of the notebook window. If the string is longer than the `pl.Config.set_fmt_str_lengths()` defined. It will be trimmed as `...`.

```python
import polars as pl

pl.Config.set_fmt_str_lengths(n=80)
pl.DataFrame(data={
    "c1": "long " * 10,
    "c2": "very long" * 100,
})
```

Disabling text wrapping might not be ideal. If the text is no longer wrapped, using `pl.Config.set_fmt_str_lengths()` will result in excessively long columns since Notebook can no longer dynamically wrap texts and has to respect the setting, making it difficult to work with certain dataframes on a small laptop screen.

I suggest displaying newline characters as `\n` (https://github.com/pola-rs/polars/issues/10700) so that there will be no confusion between newline and wrapping, and enabling text wrapping in the notebook HTML.

Another option is to add a `Config` that allows users to choose their preference.

**Comment by stevenlis** [comment]
@JulianCologne Could you pls add a screen recording to show the behavior after https://github.com/pola-rs/polars/pull/10644?

**Comment by alexander-beedie** [comment]
I suspect we should update `pre` to `pre-wrap`, as @JulianCologne suggested in the linked issue, rather than change the rendering to show the non-printing chars (though we probably _should_ show the non-printing chars in the _non_-Notebook table repr, as per Issue: https://github.com/pola-rs/polars/issues/7493).
