### ISSUE TITLE
Make DataFrame operators non-broken, or deprecate them

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10714]
### Problem description

It's a deliberately provocative title, but DataFrame operators are fundamentally broken in at least two ways:

1. No support for broadcasting. Expressions and Series have it:

```python
>>> a = pl.Series('a', [1, 2, 3])
>>> a - a.mean()
shape: (3,)
Series: 'a' [f64]
[
        -1.0
        0.0
        1.0
]
```

DataFrames don't - and I doubt most people would find this either expected or desirable:

```python
>>> df = pl.DataFrame({'a': [1, 2, 3]})
>>> df - df.mean()
 a
 -1.0
 null
 null
shape: (3, 1)
```

2. A bunch of operators are missing entirely (see #10608):

```python
>>> df ** 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for ** or pow(): 'DataFrame' and 'int'
>>> -df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary -: 'DataFrame'
>>> 1 - df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for -: 'int' and 'DataFrame'
```

If the polars team believes that ["a DataFrame is not a tensor"](https://github.com/pola-rs/polars/issues/10608#issuecomment-1684889152) and that it's dangerous to assume you can apply math operations to them because some columns may not be numeric, then all DataFrame operators should be deprecated - and so should all mathematical operations on them, including `df.mean()`. After all, you can just do `df.with_columns(cs.numeric().mean())`, right?

If the consensus is instead that it's okay to do math on DataFrames and either raise an error or give a `null` result when operating on non-numeric columns, then implement broadcasting and the remaining operators! DataFrame math is broken without them!

**Comment by Wainberg** [comment]
That's fair, though it's straightforward to split it into two operations, one for the numbers and one for the strings. Being too permissive can lead to bugs.

**Comment by mcrumiller** [comment]
FYI I think we should keep `==` and `!=` operators.

**Comment by Wainberg** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/14061 and https://github.com/pola-rs/polars/issues/10608.
