### ISSUE TITLE
allow_duplicates in qcut is not working

### ISSUE THREAD

**Issue by xuJ14** [pola-rs/polars#10711]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
g = pl.repeat("a", 5, eager=True).append(pl.repeat("b", 5, eager=True))
df = pl.DataFrame(dict(g=g, x=[1]*5+[2]*5))
df.with_columns(q=pl.col("x").qcut(2, allow_duplicates=False).over('g'))
```

### Issue description

In the doc, allow_duplicates is explained as: If True, the resulting quantile breaks don’t have to be unique. This can happen even with unique probs depending on the data. Duplicates will be dropped, resulting in fewer bins.

If I am right, the result should be Null for all elements, since I set `allow_duplicates=False`

But I got:
<html>
<body>

g | x | q
-- | -- | --
str | i64 | cat
"a" | 1 | "(-inf, 1]"
"a" | 1 | "(-inf, 1]"
"a" | 1 | "(-inf, 1]"
"a" | 1 | "(-inf, 1]"
"a" | 1 | "(-inf, 1]"
"b" | 2 | "(-inf, 2]"
"b" | 2 | "(-inf, 2]"
"b" | 2 | "(-inf, 2]"
"b" | 2 | "(-inf, 2]"
"b" | 2 | "(-inf, 2]"

</body>
</html>

### Expected behavior

What I want is like:
<html>
<body>

g | x | q
-- | -- | --
a | 1 | NaN
a | 1 | NaN
a | 1 | NaN
a | 1 | NaN
a | 1 | NaN
b | 2 | NaN
b | 2 | NaN
b | 2 | NaN
b | 2 | NaN
b | 2 | NaN

</body>
</html>

which is generated by pandas:
```python
g = pl.repeat("a", 5, eager=True).append(pl.repeat("b", 5, eager=True))
df = pl.DataFrame(dict(g=g, x=[1]*5+[2]*5)) # +list(range(5))
pddf = df.to_pandas()
pddf['q'] = pddf.groupby('g').apply(lambda x:pd.qcut(x['x'],2, labels=False, duplicates='drop')).reset_index(level=0, drop=True)
pddf
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.3.0-28-generic-x86_64-with-glibc2.27
Python:              3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
This is not a bug. `qcut(2)` will  give you one cut point, so there cannot be a duplicate. The result is expected.

**Comment by xuJ14** [comment]
I see. Then I think the total range should be [minimum, maximum] not (-inf, inf), right? If the range is (-inf, inf), all the values are the same, and we set quantiles to be 2 (as I did with my code ), it does not make sense that we can still get a group for all the same values. I think the results of my Pandas code should be the right answer.

**Comment by stinodego** [comment]
Thanks for the input. I think this will be addressed in the redesign of the methods - see https://github.com/pola-rs/polars/issues/10468
