### ISSUE TITLE
`to_numpy()` converts `pl.Utf8` columns to `object`, not `str`

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10710]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.DataFrame({'col1': ['A', 'B', 'C']}).to_numpy()
array([['A'],
       ['B'],
       ['C']], dtype=object)

>>> pl.from_numpy(pl.DataFrame({'col1': ['A', 'B', 'C']}).to_numpy()).dtypes
[Object]
```

### Issue description

`to_numpy()` converts `pl.Utf8` columns to the `object` dtype in NumPy, not `str`. Among other issues, this causes a conversion to `pl.Object` when converting back with `from_numpy()`.

This issue could be addressed by adding a `to_numpy` dtype arg as requested in #7283, but converting to str should really be the default.

### Expected behavior

The expected behavior can be restored by calling `.astype(str)` on the NumPy array, albeit with an additional memory cost due to the array copy:

```
>>> pl.DataFrame({'col1': ['A', 'B', 'C']}).to_numpy().astype(str)
array([['A'],
       ['B'],
       ['C']], dtype='<U1')
>>> pl.from_numpy(pl.DataFrame({'col1': ['A', 'B', 'C']}).to_numpy().astype(str)).dtypes
[Utf8]
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by Wainberg** [comment]
Actually, on second thought, the conversion to `object` may actually be preferable due to the memory overhead when string lengths are highly variable. For instance, when trying to `astype(str)` a NumPy array with `dtype=object` just now, I got this error:

`numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.04 TiB for an array with shape (1287657831,) and data type <U650`

So maybe the issue is more so that `from_numpy()` doesn't automatically infer that the object array only contains strings?

**Comment by Wainberg** [comment]
Actually, even specifying `schema={'colname': str}` in `from_numpy()` isn't allowed when the input array has `dtype=object`: `exceptions.ComputeError: cannot cast 'Object' type`. 

How can I add a `dtype=object` NumPy array of strings to a polars dataframe, without converting to `dtype=str` on the NumPy side and running out of memory?

**Comment by Wainberg** [comment]
Ok, I was able to get it working with:

`pl.from_arrow(pa.array(numpy_array_of_strings_with_object_dtype, type=pa.large_utf8()))`

So I guess the ask is for `from_numpy()` to a) automatically infer that a `dtype=object` array of strings contains strings, and b) to be able to do the conversion when `schema={'colname': str}` is specified. If I had to pick one, b) seems more critical.

**Comment by cjackal** [comment]
> Ok, I was able to get it working with:
> 
> `pl.from_arrow(pa.array(numpy_array_of_strings_with_object_dtype, type=pa.large_utf8()))`
> 

I think the `polars` equivalent of your `pyarrow` example would be like this:
```python
import numpy as np
import polars as pl

arr = np.array(["x"*i for i in range(10000)])
s = pl.Series(values=arr, dtype=pl.Utf8)
s
```

so option b) is already doable in `polars` using series constructor.

**Comment by Wainberg** [comment]
That creates `arr` with a string dtype. It doesn't work with object:

```python
import numpy as np
import polars as pl

arr = np.array(["x"*i for i in range(10000)], dtype=object)
s = pl.Series(values=arr, dtype=pl.Utf8)  # exceptions.ComputeError: cannot cast 'Object' type
```

**Comment by cjackal** [comment]
Ahh right I was lost in the middle of your comments.

**Comment by cjackal** [comment]
While not so comparable in terms of performance, one workaround is
```python
import numpy as np
import polars as pl

arr = np.array(["x"*i for i in range(10000)], dtype=object)
s = pl.Series(values=list(arr), dtype=pl.Utf8)
```

list(arr) is zero copy and list creation time is marginal compared to pystr to large_ut8 construction time, so may not be that bad as a current workaround I guess. Of course, the main fault is at `numpy` inappropriate as a string manipulation toolkit, conversion from/to numpy to arrow suffers massive overhead.

**Comment by cjackal** [comment]
A yet faster option:
```python
import polars as pl
import pandas as pd

pl.from_pandas(pd.Series(arr))
```
... which implies that `.from_numpy` should use this shortcut for `.from_pandas`?

**Comment by Wainberg** [comment]
The two options have nearly identical runtimes:

```python
import numpy as np
import pyarrow as pa
import pandas as pd
import polars as pl
from timeit import timeit

arr = np.array(["x"*i for i in range(10000)], dtype=object)
timeit(lambda: pl.from_arrow(pa.array(arr, type=pa.large_utf8())), number=10)  # 0.375243382062763
timeit(lambda: pl.from_pandas(pd.Series(arr)), number=10)  # 0.3756672830786556
```

`pl.from_numpy(array)` should automatically convert NumPy string arrays with `dtype=object` to `pl.Utf8`, not `pl.Object`. `pl.from_pandas(pd.Series(array))` already does this correctly.

**Comment by s-banach** [comment]
Why are you going to numpy for strings? Pandas is going to add pyarrow as a dependency in version 3.0, specifically to get away from using numpy for string columns.

**Comment by Wainberg** [comment]
I'm applying a Cythonized version of [this function](https://github.com/ericminikel/minimal_representation/blob/master/minimal_representation.py#L3-L31) to 1.2 billion data frame rows. I don't think this kind of transformation is expressible in polars in an efficient way (some of the shared prefixes and suffixes are dozens of characters long), but it would be cool if it were!

In any case, there are plenty of NumPy string arrays with `dtype=object` in the wild, and `pl.from_numpy()` should handle them correctly by converting them to `pl.Utf8` rather than `pl.Object`.

**Comment by ritchie46** [comment]
Not on topic for this issue, but itis for cython and polars: 

I would recommend looking to pyo3_polars if you are compiling custom functions. Then you don't have to go through python and will keep things fast.

https://github.com/pola-rs/pyo3-polars
