### ISSUE TITLE
`rank()` returns a Float32 Series, leading to floating-point error

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10724]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.Series([1, 2, 3]).rank().dtype
Float32
>>> pl.Series([1., 2., 3.]).rank().dtype
Float32
```

### Issue description

`rank()` always returns a Series of type `Float32`, leading to floating-point error. There doesn't seem to be a way to modify this behavior.

### Expected behavior

`rank()` should default to either always returning a Series of `Float64` dtype, or returning a Series of integer dtype when all ranks are integers and `Float64` otherwise. 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by cjackal** [comment]
Just out of pure curiosity, what is your use cases for float64 rank precision? My first impression (from my working experience) is that if you have to deal with rank of large data, then it would be best sort them and work with index instead.

**Comment by mcrumiller** [comment]
Hmm. The only time a non-integer rank can be returned is when `method="average"`, which is the default case. It's normally acceptable to have the output dtype depend on the input dtype, but I think in general we try to avoid having the output dtype depend on an input flag.

I'm a bit unsure whether we should return integers in all other method cases. An integer definitely makes way more sense for an integer rank, as it's both more performant and also uses less space.

The first unrepresentable integer for `float32` is 2^24+1 = 16777217, as we can see here:

```shell
>>> from numpy import float32 as f
>>> f(16777215) + f(1) 
16777216.0 # ok
f(16777216)
>>> f(16777216) + f(1)                   
16777216.0 # not ok
```

...meaning that our `rank` function has a current upper limit of 16,777,216 for ranks. This is probably high enough, but maybe not in some cases, so we should either document or change the implementation. Did you hit this upper limit?

**Comment by ritchie46** [comment]
I think it is fine to change dtype based on flag. The flag changes the semantics of an algorithm. We could decide that f32 it too low a precision though

**Comment by mcrumiller** [comment]
@ritchie46 how about `f64` for `method="average"` and `IdxSize` for all else?

**Comment by ritchie46** [comment]
Yes, the `f64` is maybe a better fit for the average one. :+1:
