### ISSUE TITLE
python import polars failed

### ISSUE THREAD

**Issue by mengde092** [pola-rs/polars#10722]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
import polars

<jemclloc> Unsupported system page size
memory allocation of 8 bytes failed

### Issue description

python version 3.10.12
getconfig PAGESIZE
65536
install package :polars-0.18.15-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

### Expected behavior

<jemclloc> Unsupported system page size
memory allocation of 8 bytes failed

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>
polars-0.18.15-

**Comment by stinodego** [comment]
There really isn't enough information in here for us to help you.

**Comment by mengde092** [comment]
@stinodego is polars is not match aarch64 on system page size 65536? polars version:
polars-0.18.15-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl 

and i must get it by source by step 
Install the latest Rust compiler

Install maturin: pip install maturin

cd py-polars and choose one of the following:

make build-release, fastest binary, very long compile times
make build-opt, fast binary with debug symbols, long compile times
make build-debug-opt, medium-speed binary with debug assertions and symbols, medium compile times
make build, slow binary with debug assertions and symbols, fast compile times
Append -native (e.g. make build-release-native) to enable further optimizations specific to your CPU. This produces a non-portable binary/wheel however.
