### ISSUE TITLE
`Series.value_counts` produces a data frame with duplicate column names

### ISSUE THREAD

**Issue by radugrosu** [pola-rs/polars#10732]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
print(to_markdown(pl.Series("counts", [1]).value_counts()))
```
gives a data frame with two identically named columns
```markdown
+----------+----------+
|   counts |   counts |
+==========+==========+
|        1 |        1 |
+----------+----------+
```

### Issue description

If the series' name is the same as the one created internally by `value_counts` the resulting data frame has duplicate names.

### Expected behavior

The expected behaviour is up the the devs to define.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.4.0-1109-azure-x86_64-with-glibc2.27
Python:              3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            2.3.0
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment]
@stinodego what do we normally do when polars has pre-defined column names but the column already exists? Just add a "2" on the end, or whatever number will give us a unique name?

```python
pl.DataFrame({"counts": [1], "counts2": [2]}).value_counts()
...???
```

**Comment by radugrosu** [comment]
> @stinodego what do we normally do when polars has pre-defined names but the name already exists? Just add a "2" on the end?

I think a `DuplicateError: duplicate column names found` would be more consistent with the polars.

**Comment by stinodego** [comment]
Wow, this should not be possible. Interesting. Thanks for the report.

This should raise a `DuplicateError` indeed.
