### ISSUE TITLE
The `testing` module is not exposed

### ISSUE THREAD

**Issue by korommatyi** [pola-rs/polars#10736]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.testing
```

### Issue description

The testing module is not included in `__init__.py`.

### Expected behavior

`testing` is accessible as `pl.testing`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.22.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.18
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
This is by design, so as to optimise import time of the main polars module.
If you want testing functions, you need to import it explicitly  ;)

**Comment by korommatyi** [comment]
OK, that makes sense, thanks for the quick answer. What do you think about mentioning this somewhere in the docs? As a `pandas` user just learning `polars`, this was surprising since based on the API docs, I assumed this works the same as in `pandas`.

**Comment by stinodego** [comment]
All the doc examples for the testing module show `from polars.testing import ...`. I think the docs are sufficient on this.

**Comment by alexander-beedie** [comment]
> What do you think about mentioning this somewhere in the docs?

Makes sense to me; done!  #10741 👍
