### ISSUE TITLE
Sum of u32 column is wrong if the result is bigger than max u32 value

### ISSUE THREAD

**Issue by matveev-project** [pola-rs/polars#10740]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({'cnt': [2_000_000_000, 2_000_000_000, 2_000_000_000]})
df = df.with_columns(pl.col('cnt').cast(pl.UInt32))
print(df[:1]['cnt'].sum(), df[:2]['cnt'].sum(), df[:3]['cnt'].sum())
```
output:
2,000,000,000 4,000,000,000 1,705,032,704

### Issue description

I have a table with 11 bln rows, then do group by and put rows count in 'cnt' column with UInt32 type (max value is about 600k). Resulting table is still pretty big - 565M rows so it's wise to keep types as small as possible
When I try to do simple sum on 'cnt' column - got wrong result

My understanding that polars assumes the sum (at least of i32) will be the same i32 type
I checked running sum, once sum is getting bigger than 2^32-1 sum starts from zero

Example above is artificial, to illustrate the core of the problem

Changing type to i64 will solve the problem, but will be massive overhead on big table serving sole purpose fixing the sum

### Expected behavior

Same code with pandas, illustrates expected result

```python
import pandas as pd
df = pd.DataFrame({'cnt': [2_000_000_000, 2_000_000_000, 2_000_000_000]})
df['cnt'] = df['cnt'].astype('int32')
print(df[:1]['cnt'].sum(), df[:2]['cnt'].sum(), df[:3]['cnt'].sum())
```
output:
2,000,000,000 4,000,000,000 6,000,000,000

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.15.0-78-generic-x86_64-with-glibc2.29
Python:              3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by aut0clave** [comment]
Interesting, because the docs specifically mention upcasting to avoid overflow: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.sum.html#polars.Expr.sum

**Comment by avimallu** [comment]
AFAIK Polars does not check for overflow because it is expensive, which while unfortunate is I guess ultimately a tradeoff. The upcasting that @aut0clave mentioned works only for integer types up to `UInt16`, and does not cover `UInt32`. Perhaps it should be added.

Also, as an FYI: the way you're using Polars (slicing and indexing) is not the recommended way to perform calculations in Polars - don't expect it to behave like Pandas, use the expression API.

**Comment by matveev-project** [comment]
@avimallu What is the polars way to do `df['cnt'].sum()`?`

**Comment by avimallu** [comment]
```py
df.select(pl.col("cnt").sum())
```

Take a look through the user-guide to avoid anti-patterns - it'll make your code a lot more readable and faster. :)

**Comment by ritchie46** [comment]
> Interesting, because the docs specifically mention upcasting to avoid overflow: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.sum.html#polars.Expr.sum

Only for dtypes smaller than 32 bits we upcast. 

We don't do overflow checks for other dtypes. This is a conscious decision.

**Comment by avimallu** [comment]
@ritchie46, would you be open to mentioning this in the user-guide? I think this does pop up often enough that it needs a mention - I don't remember seeing it when I first went through the guide.

**Comment by ritchie46** [comment]
Yes, I would. Care to open a PR? :)
