### ISSUE TITLE
Support for series unique & arg_unique & n_unique for list(string | temporal | bool)

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10746]
### Problem description

The new dev build feature for series unique is really nice! However I noticed that string, temporal or bool as inner dtypes are not supported yet, I am not sure if this was intentional. @reswqa 

**String**
```python
test_string = pl.Series("a", [["1"," 2"], ["3"], ["1", "2"], ["4", "5"], ["2"], ["2"]])
test_string.unique()

InvalidOperationError: `unique` operation not supported for dtype `str`
```

**Temporal**
```python
test_datetime = pl.Series("a", [[datetime(2018,1,1),datetime(2018,1,12)], [datetime(2000,1,1)], [datetime(2018,1,1),datetime(2018,1,12)], [datetime(2020,1,1),datetime(2020,1,12)], [datetime(2020,1,12)], [datetime(2020,1,12)]])
test_datetime.unique()

InvalidOperationError: `unique` operation not supported for dtype `datetime[μs]`
```

**Boolean:**
```python
test_bool = pl.Series("a", [[True,True], [False], [True,True], [False, False], [False], [True]])
test_bool.unique()

InvalidOperationError: `unique` operation not supported for dtype `bool`
```

**Comment by reswqa** [comment]
Yes, for list, currently only inner type is supported as a numerical type. This is because currently group by list does not support other inner types. I will take the time to study if there is a better way, but the current situation is like this.

But there is indeed a problem with the error message. It should print the complete type instead of the inner type, and I will fix this asap.

**Comment by ion-elgreco** [comment]
> Yes, for list unique,currently only numeric inner type is supported. This is because currently group by list does not support other inner types. I will take the time to study if there is a better way, but the current situation is like this.
> 
> But there is indeed a problem with the error message. It should print the complete type instead of the inner type, and I will fix this asap.

Ah ok good to know! In the mean time for non-numeric inner dtypes, casting a list to a struct and then hashing also works.

**Comment by ritchie46** [comment]
I will close this issue as this is not related to `unique`, but rather supporting all list types as group_by key. Which we will when we rewrite/add lists as row encoding.

Created an issue for this: #10747

**Comment by dpinol** [comment]
> > Yes, for list unique,currently only numeric inner type is supported. This is because currently group by list does not support other inner types. I will take the time to study if there is a better way, but the current situation is like this.
> > But there is indeed a problem with the error message. It should print the complete type instead of the inner type, and I will fix this asap.
> 
> Ah ok good to know! In the mean time for non-numeric inner dtypes, casting a list to a struct and then hashing also works.

Hi @ion-elgreco ,
what do you mean by hashing?
How can I convert a column with value [2,2] to [2] from a struct? 
```pl.DataFrame({"A": [[2,2]]}).select(pl.col("A").list.to_struct())```

thanks

**Comment by dpinol** [comment]
`test_string.list.eval(pl.element().unique())` works perfectly. @reswqa thanks!
