### ISSUE TITLE
`map()` with scipy.stats functions creates a Series of Series

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10766]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
from scipy.stats import norm, rankdata

>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(lambda x: x + 1))
 a
 2
 3
 4
 5
 …
 9998
 9999
 10000
 10001
shape: (10_000, 1)
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(np.log))
 a
 0.0
 0.693147
 1.098612
 1.386294
 …
 9.21004
 9.21014
 9.21024
 9.21034
shape: (10_000, 1)
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(rankdata))
 a
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 …
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
shape: (10_000, 1)
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(norm.cdf))
 a
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 …
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
shape: (10_000, 1)
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(norm.cdf))[0, 0]
shape: (10_000,)
Series: '' [f64]
[
        0.841345
        0.97725
        0.99865
        0.999968
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        …
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
        1.0
]
```

### Issue description

Using `map()` with scipy.stats functions (and possibly others, I haven't checked exhaustively) leads to every element of the output Series containing the entire result array as a Series. This isn't the case with standard user-defined functions or NumPy ufuncs. 

### Expected behavior

All of the examples should look like the first two.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by deanm0000** [comment]
np.log is a ufunc so if you do

```
np.log(pl.Series(range(1, 10001)))
``` 
then the output is still a Series even though you're using a np function

because it's a ufunc you can do this too:
```
pl.DataFrame({'a': range(1, 10001)}).with_columns(np.log(pl.col('a')))
```

For `rankdata` and others that aren't ufuncs, they return numpy arrays which polars is broadcasting in the same way it would a literal.

To get the desired behavior you have to wrap them in `pl.Series` like this...
```
pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(lambda x: pl.Series(rankdata(x))))
```

Alternatively, you could wrap it upfront like this:
```
from scipy.stats import rankdata as rankdata_raw
rankdata=lambda x: pl.Series(rankdata_raw(x))
```

and then your original input would work.

I'm not sure if the need to wrap the special function in pl.Series is a bug or if there's a reason for that but this is the (or at least a) workaround.

**Comment by Wainberg** [comment]
It does fine with things that aren't ufuncs too:
```python
>>> import polars as pl
>>> from scipy.stats import pearsonr
>>> pearsonr(pl.Series([1, 2, 3]), pl.Series([5, 4, 6]))
PearsonRResult(statistic=0.4999999999999999, pvalue=0.6666666666666667)
```
Maybe there's something special about norm and rankdata?

**Comment by deanm0000** [comment]
Being able to take a series isn't enough to make something a valid ufunc. You're not running pearsonr in a dataframe context so it doesn't really apply to the prior case. The thing that makes a ufunc "special" is that you can give a Series and it will return a Series. 

```
pl.DataFrame({'a':[1,2,3], 'b':[4,5,6]}).select(pl.struct('a','b').map_batches(lambda x: pearsonr(x.struct['a'], x.struct['b'])))
shape: (1, 1)
┌──────────────────┐
│ a                │
│ ---              │
│ list[f64]        │
╞══════════════════╡
│ [1.0, 1.3416e-8] │
└──────────────────┘
```
I don't think that's what you're after.

***btw I updated to 0.19 so map is now map_batches


Incidentally, scipy has the [scipy.special](https://docs.scipy.org/doc/scipy/reference/special.html) namespace which has a bunch of methods which are all (or at least almost all) ufuncs so you wouldn't have to do anything extra to have them work. One of those is `ndtr` which does the same thing as scipy.stats.norm.cdf with loc=0 and scale=1. 

Additionally polars has [rank](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.rank.html#polars.Expr.rank) internally so you wouldn't need to use scipy's implementation.

For instance:

```
import polars as pl
import numpy as np
from scipy.stats import rankdata
df=pl.DataFrame({'a':np.random.randint(0,100,100)})
df.with_columns(
    plrank=pl.col('a').rank(),
    scirank=pl.col('a').map_batches(lambda x: pl.Series(rankdata(x)))
)
```

**Comment by Wainberg** [comment]
Yes, there are definitely workarounds. This seems like clearly undesirable behavior though:

```python
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(rankdata))
 a
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 …
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
 [1.0, 2.0, … 10000.0]
shape: (10_000, 1)
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(pl.col('a').map(norm.cdf))
 a
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 …
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
 [0.841345, 0.97725, … 1.0]
shape: (10_000, 1)
```

**Comment by deanm0000** [comment]
I appreciate that it isn't desirable. It's not going to be considered a bug as the documentation for map_batches says:

> The output of this custom function must be a Series. 
As such it's up to the user to conform the custom function to outputting a Series.

For the specific case of `rankdata` you should use the polars rank expression instead of scipy's rankdata.

For the specific case of scipy.stats.norm.cdf, you should use scipy.special.ndtr instead as it's a ufunc and doesn't even require you to invoke `map_batches` such as:

```
from scipy.special import ndtr
from scipy.stats import norm
pl.DataFrame({'a': range(1, 10001)}) \
    .with_columns(
        b=ndtr(pl.col('a')),
        c=pl.col('a').map_batches(lambda x: pl.Series(norm.cdf(x)))
        )
```

**Comment by Wainberg** [comment]
Feature enhancement then? :)

**Comment by Wainberg** [comment]
This is now fixed via https://github.com/pola-rs/polars/pull/13277 :)
