### ISSUE TITLE
is_in broken with "cannot cast list type"

### ISSUE THREAD

**Issue by lorepozo** [pola-rs/polars#10764]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

issue affects both python and rust.

```python
import polars as pl

df = pl.DataFrame({
    "lst": [[1.0, 2.0, 3.0, 4.0, 5.0], [3.14, 5.28]],
    "n": [3.0, 2.0],
})

df.select(pl.col('n').is_in('lst'))
```

### Issue description

This issue affects both python and rust. I built latest `main` at c1487afa88a7d8c5930e8ec64a074b7d025107a9 — not yet released, would end up going into py-0.18.16 or rs-0.33.0 whever they go out. The currently released version seems to be working fine so it's a regression I stumbled into that has not yet been released. FYI @ritchie46 looks like you're actively developing around here.

### Expected behavior

expected behavior:
```
shape: (2, 1)
┌───────┐
│ n     │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ false │
└───────┘
```

actual behavior:
```
File ~/scratch/polars/py-polars/polars/dataframe/frame.py:7663, in DataFrame.select(self, *exprs, **named_exprs)
   7561 def select(
   7562     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7563 ) -> DataFrame:
   7564     """
   7565     Select columns from this DataFrame.
   7566
   (...)
   7661
   7662     """
-> 7663     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~/scratch/polars/py-polars/polars/utils/deprecation.py:95, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     90 @wraps(function)
     91 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     92     _rename_keyword_argument(
     93         old_name, new_name, kwargs, function.__name__, version
     94     )
---> 95     return function(*args, **kwargs)

File ~/scratch/polars/py-polars/polars/lazyframe/frame.py:1692, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, streaming)
   1680     comm_subplan_elim = False
   1682 ldf = self._ldf.optimization_toggle(
   1683     type_coercion,
   1684     predicate_pushdown,
   (...)
   1690     streaming,
   1691 )
-> 1692 return wrap_df(ldf.collect())

ComputeError: cannot cast List type (inner: 'Float64', to: 'Float64')
```

### Installed versions

on `main` branch at c1487afa88a7d8c5930e8ec64a074b7d025107a9, I used `make build` with python version 3.10.10 and latest stable rust (1.72.0).

**Comment by reswqa** [comment]
It maybe caused by #10614. We lost our branch of handing `ListType` type but forced `rhs` cast to `FloatType`.
