### ISSUE TITLE
UDFs passed to `map` don't appear to receive appropriately windowed Series from `over` 

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#10778]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

def csum( srs ):
    # replicate cumulative sum as a UDF
    print( f"Called 'csum' with {srs}" )
    return pl.Series( np.cumsum(srs) )

df = pl.DataFrame({
    'key': ["x","x","x","y","y"], 
    'val': [2,3,8,5,3],
})
df.with_columns(
    csum_pl = pl.col("val").cumsum().over( pl.col("key") ),
    csum_udf = pl.col("val").map( csum ).over( pl.col("key") ),
)
# shape: (5, 4)
# ┌─────┬─────┬─────────┬──────────┐
# │ key ┆ val ┆ csum_pl ┆ csum_udf │
# │ --- ┆ --- ┆ ---     ┆ ---      │
# │ str ┆ i64 ┆ i64     ┆ i64      │
# ╞═════╪═════╪═════════╪══════════╡
# │ x   ┆ 2   ┆ 2       ┆ 2        │
# │ x   ┆ 3   ┆ 5       ┆ 5        │
# │ x   ┆ 8   ┆ 13      ┆ 13       │
# │ y   ┆ 5   ┆ 5       ┆ 18       │  # << "csum_udf" ignores the  
# │ y   ┆ 3   ┆ 8       ┆ 21       │  # window declared by "over"
# └─────┴─────┴─────────┴──────────┘  # and keeps on going
```

### Issue description

It seems that `over` is not properly respected by `map` functions; the given UDF should receive windowed Series, but appears to receive the _entire_ (non-windowed) Series.

The given example shows that the UDF version of the cumulative sum function keeps going past the window boundary, and the inner "print" confirms that it was given the entire Series once, instead of being given two Series representing the two windows in the test data.

### Expected behavior

`map` functions should receive Series data from each window, not the entire Series.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.5.1-arm64-arm-64bit
Python:              3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
----Optional dependencies----
adbc_driver_sqlite:  0.6.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            2.3.0
sqlalchemy:          2.0.20
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by ritchie46** [comment]
That's intended. Maps don't take groups into account. It should use `map_elements`/`apply`.

That's why I wanted `map_batch` because `map` should only be applied if you understand it's constraints.

**Comment by alexander-beedie** [comment]
Argh, the upcoming `0.19.0` aliases can't come soon enough, hah... It wasn't immediately obvious to me that window functions would be considered groups for the purpose of `apply` (I'll go add some docstring examples to better-demonstrate this usage).

Can/should we raise an error here?
Curious now if calling `over` against a `map` is ever going to be valid/reasonable 🤔

**Comment by ritchie46** [comment]
If it does something like this, it is fine: `col(..).map(lambda series: series * 2).sum().over(..)`

E.g. any elementwise operation.

**Comment by alexander-beedie** [comment]
> If it does something like this, it is fine: `col(..).map(lambda series: series * 2).sum().over(..)`  E.g. any elementwise operation.

_"I'll get my coat..." 🤣_

**Comment by ritchie46** [comment]
Yes, that's why I think we should rename `Expr.map` it is a bit dangerous to use.

**Comment by alexander-beedie** [comment]
> Yes, that's why I think we should rename `Expr.map` it is a bit dangerous to use.

Seriously... I was staring right at it and still missed it. I'll consider having proved this point as performing a public service. _"Let the renaming begin..."_ ;)
