### ISSUE TITLE
Add support for join cardinality (`validate='x:x'`) when join key is a list of many columns

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#10784]
### Problem description

```python
# this works
df = df.join(df2, on='column1', how='left', validate='m:1')

# this is currently unsupported
df = df.join(df2, on=['column1', 'column2'], how='left', validate='m:1')
```

Add support for the `validate='x:x'` arg when the `on=` arg is a list.

**Comment by QuentinSoubeyranAqemia** [comment]
That would be very helpful, I'm wrangling complex data and I have silent data duplication due to not being able to validate the joins.

I tried merging on `pl.struct` columns as a work-around and was met with a `PanicException: not implemented`.

**Comment by ritchie46** [comment]
added in #15559

**Comment by DeflateAwning** [comment]
Very awesome! This is a huge win for my team, as we use that validate argument extensively!

**Comment by s1lvester** [comment]
Thank you so much for this @ritchie46 ❤️

**Comment by QuentinSoubeyranAqemia** [comment]
Awesome!

**Comment by DeflateAwning** [comment]
Hmm was this included in the Python `v0.20.21` release today?

With v0.20.21, I got the following error:

```
1:1 validation on a LEFT is not yet supported for multiple keys
```

I assumed that, with closing of this issue, it'd be supported now. Let me know if I'm missing something! 

@ritchie46

**Comment by s1lvester** [comment]
This is already be part of python v0.20.20

**Comment by maxzw** [comment]
The main branch still states the following in the `join` docstring.
```
                - This is currently not supported the streaming engine.
                - This is only supported when joined by single columns.
```
I also reproduce the same as @DeflateAwning.
I also don't see any python files changed in the referred PR #15559, so I don't understand why this issue has been closed.

Perhaps there is still work to be done on the python-side?

**Comment by ritchie46** [comment]
Ah, that are just some checks that redundant now. Will remove them.
