### ISSUE TITLE
Pickling struct with null list unpickles with incorrect dtype

### ISSUE THREAD

**Issue by dkumor** [pola-rs/polars#10781]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pickle
df = pl.Series([{'a':None}],dtype=pl.Struct([pl.Field('a',pl.List(pl.Utf8))]))
print(df.dtype)
print(pickle.loads(pickle.dumps(df)).dtype)
```
Output:
```
Struct([Field('a', List(Utf8))])
Struct([Field('', List(Null))])
```

### Issue description

The dtype is not being reproduced after an unpickle - both the field name and the list type are lost.

### Expected behavior

Both print statements should show the same thing.

### Installed versions

<details>

```
--------Version info---------
Polars:       0.18.15
Index type:     UInt32
Platform:      macOS-13.5.1-arm64-arm-64bit
Python:       3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite: <not installed>
cloudpickle:     <not installed>
connectorx:     <not installed>
deltalake:      <not installed>
fsspec:       2022.11.0
matplotlib:     3.6.3
numpy:        1.24.2
pandas:       1.5.2
pyarrow:       12.0.0
pydantic:      <not installed>
sqlalchemy:     <not installed>
xlsx2csv:      0.8.1
xlsxwriter:     <not installed>
```

</details>

**Comment by c-peters** [comment]
Relates to #9182 

@ritchie46, @orlp. This also results from `series::new` however in this case there is data but is it null, hence type inference will fail. Could we add a dtype parameter when constructing the series to avoid future issues like these?

**Comment by ritchie46** [comment]
There should be such a method already. Ping me later to search it when not on mobile.

**Comment by c-peters** [comment]
Do you mean `from_chunks_and_dtype_unchecked`?

**Comment by c-peters** [comment]
ping @ritchie46

**Comment by ritchie46** [comment]
I think youu need one of those:

```rust
Series::new_empty() // creates an empty series of that dtype

Series::full_null() // creates a series of that dtype and sets values as null
```
