### ISSUE TITLE
EWM Mean/Std should work with a "times" column

### ISSUE THREAD

**Issue by guillempalou** [pola-rs/polars#10794]
### Problem description

When doing EW smoothing filters, we should be able to decay the smoothing factor by an additional times/index column, much like pandas does with its `times` argument in [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ewm.html)

Currently, the way to achieve such thing is to perform a groupby_rolling and compute all decays for each point, which leads to a complexity of O(N^2), but the algorithm should be O(N).

I think it would be a great addition.

**Comment by orlp** [comment]
I find the `times` column a bit unclear. As soon as you introduce an explicit time dimension instead of an index-based window there are actually two different kind of 'times' relevant:

1. the timestamps associated with the observed values, and
2. the windows at which we want to sample the exponentially decaying average.

It's not clear to me what the correct choice of the second is, given the first. The naive solution could give vastly unequal window sizes.

**Comment by leeauk21** [comment]
I think having a times column is definitely crucial for any ewm functions. Samples maybe collected at random snaps of time and you don't want to decay them by the sequence that you receive them but by the actual time. At least this will be very useful in HFT. Please implement this so I could use polars instead of pandas at work. putting 3 months worth of market orders and LOB into memory kills my 48core & 200Gb ram PC. Guys please implement this haha!

**Comment by guillempalou** [comment]
I don’t think it’s just a matter of HFT, I think in general it’s good to allow timestamps for temporal functions and not assume uniform sampling. 

Additionally, the rolling mean function already implements this https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.rolling_mean.html

One can define the window size in terms of timedeltas, rather than samples. It would be great to have this also for the alpha parameter in ewm.

**Comment by MarcoGorelli** [comment]
hi @guillempalou , @leeauk21 - I've added this to polars-xdt https://marcogorelli.github.io/polars-xdt-docs/api/polars_xdt.ewma_by_time.html

Example:
```python
import polars as pl
import polars_xdt as xdt
from datetime import date, timedelta
df = pl.DataFrame(
    {
        "values": [0, 1, 2, None, 4],
        "times": [
            date(2020, 1, 1),
            date(2020, 1, 3),
            date(2020, 1, 10),
            date(2020, 1, 15),
            date(2020, 1, 17),
        ],
    }
)
df.with_columns(
    ewma=xdt.ewma_by_time(
        "values", times="times", halflife=timedelta(days=4)
    ),
)
shape: (5, 3)
┌────────┬────────────┬──────────┐
│ values ┆ times      ┆ ewma     │
│ ---    ┆ ---        ┆ ---      │
│ i64    ┆ date       ┆ f64      │
╞════════╪════════════╪══════════╡
│ 0      ┆ 2020-01-01 ┆ 0.0      │
│ 1      ┆ 2020-01-03 ┆ 0.585786 │
│ 2      ┆ 2020-01-10 ┆ 1.523889 │
│ null   ┆ 2020-01-15 ┆ null     │
│ 4      ┆ 2020-01-17 ┆ 3.233686 │
└────────┴────────────┴──────────┘
```

Could you please verify that this is what you're asking for, and that it addresses your use-case? If so, then I think we can have a conversation about possibly upstreaming it to Polars' `ewm_mean`

**Comment by guillempalou** [comment]
Sorry for the late reply,

This is exactly what I was referring to. Decay (or alpha in the doc
examples) should be a function of the time deltas between intervals.

Thanks a lot for the example, @marcogorelli

-------
Guillem
***@***.***

**Comment by MarcoGorelli** [comment]
marking accepted then - this should be a separate `ewm_mean_by` function, as not all `ewm_mean` args will be relevant

**Comment by wbeardall** [comment]
Hi all, 

I've been trying out the new functionality, and just want to confirm something; the implementation for `xdt.ewma_by_time` seems to return a series with default name taken from the `times=...` kwarg, as opposed to the data column(s), which is the behaviour of `pl.col(...).ewm_mean(...)`.

As-is, running the following in the base library works as expected

```
# Succeeds
df.with_columns(pl.col(pl.NUMERIC_DTYPES).ewm_mean(com=1))
```

but, when attempting a similar use-case with `xdt.ewma_by_time`, as below,

```
# Fails
df.with_columns(xdt.ewma_by_time(pl.col(pl.NUMERIC_DTYPES), times=pl.col(time_key), half_life=halflife))
```

throws the following

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polars/dataframe/frame.py", line 8366, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: the name: 'time' passed to `LazyFrame.with_columns` is duplicate

It's possible that multiple expressions are returning the same default column name. If this is the case, try renaming the columns with `.alias("new_name")` to avoid duplicate column names.

Error originated just after this operation:
DF ["time", "c1", "c2", "c3"]; PROJECT */10 COLUMNS; SELECTION: "None"
```

Iterating over the columns, as follows, works as expected, but only if `.alias(c)` is included, which leads be to believe that the current implementation derives its default name from the times column, and not from the data column, as might be expected.

```
# Succeeds
numeric = df.select(pl.col(pl.NUMERIC_DTYPES))
df.with_columns(*[
    xdt.ewma_by_time(pl.col(c), times=pl.col(time_key), half_life=halflife).alias(c)
    for c in numeric.columns
])
```

Is this expected, and, if so, is there an intended mechanism for running `xdt.ewma_by_time` with multiple column inputs?
Thanks!

**Comment by MarcoGorelli** [comment]
Thanks @wbeardall for trying this out! Good to iron out issues before this reaches Polars itself 💪 

Indeed, that was an issue - it should take the name from the values column, not the time one. I just pushed out a new release, and now the example you provided should work. Could you please `pip install -U polars-xdt` and try again?

**Comment by wbeardall** [comment]
@MarcoGorelli I can confirm that the fix works on my end, thanks! All the best.
