### ISSUE TITLE
PanicException when using the same GroupBy LazyFrame twice: `pyo3_runtime.PanicException: called 'Option::unwrap()' on a 'None' value`

### ISSUE THREAD

**Issue by TNieuwdorp** [pola-rs/polars#10793]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# Create a LazyFrame
lazy_df = pl.LazyFrame(
    {
        "group_column1": ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
        "group_column2": ['X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y'],
        "value_column": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }
)

# Separate computations works fine
lazy_df_grouped = lazy_df.groupby(['group_column1', 'group_column2'])
lazy_df_grouped_first = lazy_df_grouped.first().collect()
print(lazy_df_grouped_first)
lazy_df_grouped = lazy_df.groupby(['group_column1', 'group_column2'])
lazy_df_grouped_last = lazy_df_grouped.last().collect()
print(lazy_df_grouped_last)

# Two computations on the same frame cause a PanicException
lazy_df_grouped = lazy_df.groupby(['group_column1', 'group_column2'])
lazy_df_grouped_first = lazy_df_grouped.first()
lazy_df_grouped_last = lazy_df_grouped.last()
```

### Issue description

When executing both `first()` and `last()` on the same grouped lazyframe, even without calling `collect()`, this creates a `PanicException`, suggesting that these operations change something in place. Regardless of the operation (`first()`, `last()`, others), the second operation always causes a `PanicException`.

```
>>> lazy_df_grouped_last = lazy_df_grouped.last()
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lazygroupby.rs:22:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thijs/Projects/bla/python/.venv/lib/python3.11/site-packages/polars/lazyframe/groupby.py", line 453, in last
    return self.agg(F.all().last())
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thijs/Projects/bla/python/.venv/lib/python3.11/site-packages/polars/lazyframe/groupby.py", line 154, in agg
    return wrap_ldf(self.lgb.agg(pyexprs))
                    ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

This error is the same as https://github.com/pola-rs/polars/issues/10792 but the issue seems to come from a different piece of code. (This frame is not empty)

### Expected behavior

Expected behaviour is like the individual calls above the PanicException. The lazy grouped frame should not be changed at all and is reusable for different computations on the same frame.

### Installed versions

<details>

```
>>> pl.__version__
'0.18.15'
```

</details>

**Comment by reswqa** [comment]
We take the `LazyGroupBy` from `Option` every time an `agg` is executed,  this prevents our continuous calls. Maybe we should clone it per-invoke?
