### ISSUE TITLE
Rename `Expr.is_not()` to `Expr.not()` or `Expr.negate()`

### ISSUE THREAD

**Issue by jeroenjanssens** [pola-rs/polars#10807]
### Problem description

The `Expr` object many methods that start with `is_`, e.g., `is_null()`, `is_in()`, and `is_first()`. You could say that they answer a question (with `True`s and `False`s).

The `Expr.is_not()` method, however, doesn't really answer a question, but performs an action&mdash;it negates a boolean expression.

For this reason I believe it would more consistent if the method `is_not()` would be renamed to `not()`. Another suggestion, if you'd prefer a verb, is to rename it to `negate()` (cf. PySpark[1] and the R package `purrr` [2]). 

Curious to hear what others think of this. 

_Side note: Python has the `is not` operator [3] (i.e., `operator.is_not(a, b)`) which checks for identity between two objects (and therefore does answer a question). I'm not saying that this causes confusion; just wanted to point it out._

### References

1. https://dist.apache.org/repos/dist/dev/spark/v3.5.0-rc1-docs/_site/api/python/reference/pyspark.sql/api/pyspark.sql.functions.negate.html#pyspark.sql.functions.negate
2. https://purrr.tidyverse.org/reference/negate.html
3.  https://docs.python.org/3/library/operator.html#operator.is_not

**Comment by cjackal** [comment]
I'd like to suggest the unary op `.not_()` following the patterns in other (binary) operations (`.and_()`, `.or_()`, `.eq()`, ...):
It is an equivalent of [`operator.not_` in stdlib](https://docs.python.org/3/library/operator.html?highlight=operator#operator.not_).
We may further move it [under `operators` tab](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/operators.html); anyway `.is_not()` is an op.

**Comment by ion-elgreco** [comment]
I like the `negate `one.

**Comment by stinodego** [comment]
Or `invert`, like `__invert__` / `~`.

**Comment by ritchie46** [comment]
I really don't like invert. I never read programming in booleans in terms of inverting. More often in `not` or `negate`. I think `negate` most accurately describes that we are having an action.

I agree with the unlucky naming of `is_not`. My bad. I would welcome a PR for this one.

**Comment by jeroenjanssens** [comment]
Thanks everybody for their feedback. I would be happy to make a PR for this. Everybody good with that?

**Comment by ritchie46** [comment]
Please. :)

**Comment by orlp** [comment]
II would prefer `not_` over `negate` because `x.negate()` can be misinterpreted as meaning `-x` which is incorrect.

**Comment by jeroenjanssens** [comment]
Indeed booleans as well as numbers can be negated. So how about we make `Expr.negate()` work with both booleans and numbers?

**Comment by orlp** [comment]
@jeroenjanssens The problem is that negation has a different meaning for both. It is very common to think of booleans as integers 0, 1 so it's very confusing when `bool.negate` maps `0` to `1` but `int.negate` maps `0` to `0`.

Better to avoid the `negate` terminology altogether IMO.

**Comment by jeroenjanssens** [comment]
Good point @orlp. I'll rename `.is_not()` to `.not_()`. Passing in anything other than a Boolean will still raise a SchemaError.

**Comment by mcrumiller** [comment]
Why `not_` and not just `not`? Underscores usually imply something private. Numpy has some of these and I always felt it was a bit weird.

**Comment by cjackal** [comment]
> Why `not_` and not just `not`? Underscores usually imply something private. Numpy has some of these and I always felt it was a bit weird.
> 
@mcrumiller How about `Expr.and_()`, `Expr.or_()`? We just follow [python standard patterns in `operator`](https://docs.python.org/3/library/operator.html?highlight=operator#mapping-operators-to-functions), so `Expr.not_()` (counterpart of `operator.not_`) seems to me the best choice with API consistency.

**Comment by stinodego** [comment]
> Underscores usually imply something private.

An underscore prefix implies private, and underscore suffix implies a clash with builtin functions.
