### ISSUE TITLE
Multiple quantiles in one select will return only one result

### ISSUE THREAD

**Issue by abstractqqq** [pola-rs/polars#10815]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

a = np.random.random(1000)
b = np.random.random(1000)
df = pl.DataFrame({
    "a":a,
    "b":b
})
cols=["a","b"]
df.lazy().select(
    *(pl.col(c).quantile(0.75, interpolation="midpoint").suffix("_3") for c in cols),
    *(pl.col(c).quantile(0.25, interpolation="midpoint").suffix("_1") for c in cols),
).collect()
# Will return 0.75 quantile twice for both _1 and _3
#shape: (1, 4)
#┌──────────┬──────────┬──────────┬──────────┐
#│ a_3      ┆ b_3      ┆ a_1      ┆ b_1      │
#│ ---      ┆ ---      ┆ ---      ┆ ---      │
#│ f64      ┆ f64      ┆ f64      ┆ f64      │
#╞══════════╪══════════╪══════════╪══════════╡
#│ 0.754651 ┆ 0.741345 ┆ 0.754651 ┆ 0.741345 │
#└──────────┴──────────┴──────────┴──────────┘

a = np.random.random(1000)
b = np.random.random(1000)
df = pl.DataFrame({
    "a":a,
    "b":b
})
cols=["a","b"]
df.lazy().select(
    *(pl.col(c).quantile(0.25, interpolation="midpoint").suffix("_1") for c in cols),
    *(pl.col(c).quantile(0.75, interpolation="midpoint").suffix("_3") for c in cols),
).collect()
# Will return 0.25 quantile twice for both _1 and _3
#shape: (1, 4)
#┌──────────┬──────────┬──────────┬──────────┐
#│ a_1      ┆ b_1      ┆ a_3      ┆ b_3      │
#│ ---      ┆ ---      ┆ ---      ┆ ---      │
#│ f64      ┆ f64      ┆ f64      ┆ f64      │
#╞══════════╪══════════╪══════════╪══════════╡
#│ 0.251569 ┆ 0.231781 ┆ 0.251569 ┆ 0.231781 │
#└──────────┴──────────┴──────────┴──────────┘
```

### Issue description

When there are multiple quantile expressions in one select for the same column, the result will only return the value for the first statement. I suspect this is caused by common subplan elimination falsely identifying the quantile expressions for the same column as the same expression, without taking into consideration the actual value in the quantile.

### Expected behavior

```python
a = np.random.random(1000)
b = np.random.random(1000)
df = pl.DataFrame({
    "a":a,
    "b":b
})
cols=["a","b"]
df.lazy().select(
    *(pl.col(c).quantile(0.25, interpolation="midpoint").suffix("_1") for c in cols),
    *(pl.col(c).quantile(0.75, interpolation="midpoint").suffix("_3") for c in cols),
).collect()
```

Should show quantile 0.25 and 0.75 for both columns "a" and "b", not the first quantile computed for the columns.

### Installed versions

<details>

--------Version info---------
Polars:              0.19.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.1
pydantic:            1.10.9
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by ritchie46** [comment]
Yes, that is an invalid CSE hit. I got a fix. Will patch later today.
