### ISSUE TITLE
Parameterized Queries and Return LazyFrame

### ISSUE THREAD

**Issue by matquant14** [pola-rs/polars#10835]
### Problem description

The new read_database function, using an existing db connection, looks really promising.  I'd like to make the following enhancement requests for this feature:

1. Can the read_database function be enhanced to allow parameterized queries in order to avoid SQL injection?  
2. Also, can there be an ability to return a LazyFrame instead of a DataFrame after the SQL query is executed and results are fetched?

**Comment by alexander-beedie** [comment]
> The new read_database function, using an existing db connection, looks really promising. 

Thanks! Hopefully it will prove useful for you :)

1. We aren't supplying any values to the query, we simply receive it "as-is" from the caller and use the caller's existing connection to execute it; I don't think there is any vector for polars-mediated SQL injection here (the caller has a raw connection available to them, meaning they can execute absolutely anything they want anyway). If you think I'm missing something, can you elaborate?

2. We don't have any way of pushing predicates/etc down into the SQL query, so the result is necessarily eager; you can just add  `.lazy()` to the returned DataFrame and go from there 👍

**Comment by matquant14** [comment]
Thanks for your feedback @alexander-beedie.

Noted on the LazyFrame.  I created a wrapper function that does that w/ a lazy flag as a parameter.

```
def polars_read_sql(query,connection,lazy:bool = False,**kwargs):
    if lazy:
        return pl.read_database(query,connection,**kwargs).lazy()
    
   return pl.read_database(query,connection,**kwargs)
```
Re the SQL injection...

"they can execute absolutely anything they want directly against the target database "

I think that's what I'm getting at.  Say I'm executing a SQL query like

```SELECT * FROM customers where id = 01234```

Then someone could inject there own code and write

`SELECT * FROM customers where id = 01234 OR 1=1; Drop Table customers;`

Instead you would want to use

```SELECT * FROM customers where id = ?``` 

to help prevent the injection.  Then when using the cursor object to extract the data, you could pass along the parameter.  Something like below

```
sql = SELECT * FROM customers where id = ?
param = '01234'
results = cursor.execute(sql, params=param,**kwargs).fetchall()
columns = [desc.name for desc in cursor.description]

df = pl.DataFrame(results,schema=columns)

```

I've actually already implemented something like this using Snowflake and it's cursor object (before the enhancement to the read_database function). 
```
def fetch_sf_cursor_pl(
        cursor: SnowFlakeCursor, sql: str, **kwargs
) -> Tuple[pl.DataFrame|pl.LazyFrame,str]:
    """
    Fetches data from Snowflake using a Snowflake cursor and executes the given SQL query.

    :param cursor: Snowflake cursor object.
    :type cursor: snowflake.connector.SnowflakeCursor
    :param sql: SQL query to be executed.
    :type sql: str
    :param kwargs: Additional parameters to be passed to cursor.execute().
    :type kwargs: dict
    :return: A tuple containing the fetched data in a Polars DataFrame or LazyFrame
             and the Snowflake query ID.
    :rtype: tuple
    """
    lazy = kwargs.pop("lazy", False)

    results = cursor.execute(sql, **kwargs).fetchall()
    column_names = [desc.name for desc in cursor.description]
    sfqid = cursor.sfqid

    if lazy:
        return pl.LazyFrame(results, schema = column_names), sfqid

    return pl.DataFrame(results, schema = column_names), sfqid
```

I understand it might be a little harder to implement when working w/ different engines and database connections.

**Comment by alexander-beedie** [comment]
Let me try and restate a bit; as the _caller_ has the connection (it's not provided by polars), there is nothing we can do to stop the caller from executing anything they like against the database - there is no injection attack being mediated by polars here.

Protecting against injection is only relevant when the API (eg: polars) is providing access to the resource (eg: database) and the caller is providing arbitrary SQL. But we _aren't_ providing access to the database, the caller is - by definition they already have complete freedom to delete tables, alter schemas, or do anything else their connection allows  ;)

**Comment by alexander-beedie** [comment]
@matquant14: FYI, you'll soon be able to passthrough to the underlying connection's `execute` method, which will allow you to use parameterised queries without needing a custom shim✌️

**Comment by matquant14** [comment]
@alexander-beedie that's great to hear!  I'll be looking forward to the enhancement! 

thanks very much for all the work you and the rest of the contributors are putting forth.

**Comment by rupurt** [comment]
I'd love to use polars `read_database` as a data extraction and transformation layer. Is it possible to stream the cursor result sets into the polars write formats without loading the entire result into memory? The number of output formats polars supports would take a bunch of extra work to hand roll in python. I can't seem to glean how to do it from the docs. 

e.g.

```python
result_df = pl.LazyFrame(columns = ['rowid', 'userid', 'ip', 'ts'])
fetch_row_array_size = 4096

with pyodbc.connect(conn_str) as conn:
    with conn.cursor() as cursor:
        cursor.execute('SELECT RowId, IP, UserID, Timestamp FROM UserAccessLogs')
        
        while True:
              # fetch "chunks" of the total query result as a result set
              rows = cursor.fetchmany(fetch_row_array_size)
              if not rows:
                  break
             current_df = pl.DataFrame.from_records(rows, columns =['rowid', 'userid', 'ip','ts'])
             result_df = result_df.append(current_df)
       
        # Ideally this would be called before fetching each result set, and as the records are appended they get written to the output file
        result_df.write_csv("output.csv")
```

**Comment by tgrandje** [comment]
I concur with @rupurt 's wish, though I have some suggestions: 
1. using `sqlparse` to retrieve the columns names at the final stage of concatenation
2. maybe using a pl.concat instead of appending the dataframes (I'm not sure about this as I'm to new to polars after years practising pandas)
3. as I'm using sqlalchemy to open my connection, I end up with a slightly different code, something like this (not sure if this is portable to pydobc) :

```
with engine.connect() as conn:
    with conn.execute(sql).cursor as cursor:
        while True:
              ....
```

Should we open a new issue about this?

**Comment by alexander-beedie** [comment]
@rupurt, @tgrandje: an issue that was closed several months ago is not the ideal place to try and get up to date information on a different (if tangentially related) issue - the chances of anyone seeing your query is very, _very_ low (I'm essentially only noticing it by accident)  ;)

Our Discord channel (or StackOverflow) would be better. In this case it does just seem like you haven't spotted the "iter_batches" parameter on `read_database`. Whether the entire result set is materialised up front or not depends on the backend, but internally Polars will establish the equivalent of that "fetchmany" loop and return frames of "batch_size" rows. Cheers.
