### ISSUE TITLE
Add polars datetime now()

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10832]
### Problem description

```
import polars as pl
from datetime import datetime
df = pl.DataFrame({"prod": ['apple', 'orange', 'banana'], "start_date": [datetime(2023,5,16), datetime(2033,11,30), None]})

df.filter((pl.col('prod') != 'apple') &
          (pl.col('start_date').fill_null(datetime.now()) >= datetime.now())
          )

```
This should return both orange and banana, but returns only orange.
(Since the expression should be evaluated in one step, so the same datetime.now() value should be included on both sides of the equation mark.)

**Comment by cmdlineluser** [comment]
But the 2 calls wont produce the same value:
```python
>>> datetime.now(); datetime.now()
datetime.datetime(2023, 8, 31, 16, 4, 11, 923252)
datetime.datetime(2023, 8, 31, 16, 4, 11, 927127)
```
If you call it once:
```python
now = datetime.now()

df.filter(
   (pl.col('prod') != 'apple') &
   (pl.col('start_date').fill_null(now) >= now)
)

# shape: (2, 2)
# ┌────────┬─────────────────────┐
# │ prod   ┆ start_date          │
# │ ---    ┆ ---                 │
# │ str    ┆ datetime[μs]        │
# ╞════════╪═════════════════════╡
# │ orange ┆ 2033-11-30 00:00:00 │
# │ banana ┆ null                │
# └────────┴─────────────────────┘
```

**Comment by cjackal** [comment]
While the expression is evaluated once, your `datetime.now()` are evaluated twice. You should set it as a variable first.

```python
from datetime import datetime
df = pl.DataFrame({"prod": ['apple', 'orange', 'banana'], "start_date": [datetime(2023,5,16), datetime(2033,11,30), None]})

now = datetime.now()
df.filter((pl.col('prod') != 'apple') &
          (pl.col('start_date').fill_null(now) >= now)
          )
shape: (2, 2)
┌────────┬─────────────────────┐
│ prod   ┆ start_date          │
│ ---    ┆ ---                 │
│ str    ┆ datetime[μs]        │
╞════════╪═════════════════════╡
│ orange ┆ 2033-11-30 00:00:00 │
│ banana ┆ null                │
└────────┴─────────────────────┘
```

**Comment by cjackal** [comment]
You can provide such background yourself (e.g. by overriding `datetime.now` for a moment)?

**Comment by cmdlineluser** [comment]
The `datetime.now()` calls happen first before `.filter()` - so Polars only sees the 2 different datetime values.

I guess you would need a Polars Expression equivalent of `.now()`

**Comment by orlp** [comment]
> Could it not be optimized like this, in the background?

No, Polars just sees the computed datetime value that Python gives.

I'm quite hesitant to add a `now()` function to polars itself because it is an absolute minefield when combined with lazy/eager evaluation. It can become rather confusing as to when "now" actually is.
