### ISSUE TITLE
pl.read_database() successfully runs command queries but raises

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#10843]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

conn = get_connection(...) # get your SQLAlchemy connection

# both of these commands raise the same exception, but the SQL succeeds
pl.read_database("CREATE TABLE my_table (name VARCHAR(20))", conn)
pl.read_database("INSERT INTO my_table VALUES ('polars')", conn)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\python-toolbox\.venv_toolbox\Lib\site-packages\polars\utils\deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python-toolbox\.venv_toolbox\Lib\site-packages\polars\io\database.py", line 270, in read_database
    return cx.execute(query).to_frame(batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python-toolbox\.venv_toolbox\Lib\site-packages\polars\io\database.py", line 205, in to_frame
    frame = frame_init(batch_size)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python-toolbox\.venv_toolbox\Lib\site-packages\polars\io\database.py", line 162, in _from_rows
    self.result.cursor.description
AttributeError: 'NoneType' object has no attribute 'description'
```
...but as you can see, the commands succeeded:
```
pl.read_database("SELECT * FROM my_table", conn)
```
```
shape: (1, 1)
┌────────┐
│ name   │
│ ---    │
│ str    │
╞════════╡
│ polars │
└────────┘
```

### Issue description

`pl.read_database()` works on command-like queries, e.g. a `CREATE TABLE` statement. These queries do not have a return value, and so polars errors, but the command still succeeds.

### Expected behavior

No error, no return value.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a5
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.10
xlsx2csv:            0.8.1
xlsxwriter:          3.1.0
```

</details>

**Comment by mcrumiller** [comment]
FYI, I think because of the name `read_database`, these types of queries probably should not succeed. I would suggest either creating an `exec_database` which is identical but does not expect a return value, or else rename `read_database` to something else and allow non-result commands to be issued.

**Comment by alexander-beedie** [comment]
I don't really understand why you'd pass those types of statements (CREATE/INSERT) into this function; it's pretty clear that it's supposed to receive a query and will build DataFrame results from it.

Since you already have the connection you can just pass CREATE and INSERT statements to that directly; I can't think why you'd want to mediate those calls via a totally unnecessary interaction with polars? 😅

**Comment by mcrumiller** [comment]
@alexander-beedie I agree completely, thanks for the quick PR.
