### ISSUE TITLE
'POLARS_MAX_THREADS' doesn't actually work in Python

### ISSUE THREAD

**Issue by Shanxce** [pola-rs/polars#10847]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os
os.environ['POLARS_MAX_THREADS'] = '4'

import psutil
import polars as pl

print(pl.threadpool_size())

df = pl.DataFrame({'a': [1,2,3],
                   'b': [4,5,6]})
df = df + 1

print(pl.threadpool_size())
print('Num threads before: {}'.format(psutil.Process().num_threads()))
```

```
4
4
Num threads before: 149
```

### Issue description

Polars 'POLARS_MAX_THREADS' doesn't actually work, although it does create POLARS_MAX_THREADS number of threads at beginning, but after i do some calculation, the number of threads it uses boost a lot. 

The threads it use actually equals to the number of cores on the machine.

### Expected behavior

The threads it use should equals to the number of POLARS_MAX_THREADS.

### Installed versions

<details>

![image](https://github.com/pola-rs/polars/assets/66676755/2c29331e-49f3-4064-bc66-e30151b89e51)

</details>

**Comment by ritchie46** [comment]
I am fairly positive that polars respect num_threads on the rust side. What does psutil measure here? As it returns a number higher than my no of cpu cores.

**Comment by Shanxce** [comment]
> I am fairly positive that polars respect num_threads on the rust side. What does psutil measure here? As it returns a number higher than my no of cpu cores.

It is total threads number used in this process. So in my example, it is 'POLARS_MAX_THREADS (init threads polars create) + number of cpu cores (extra threads polars create when calculate df = df + 1) + other threads used (e.g., numpy's extra threads)'.

**Comment by ritchie46** [comment]
It sees that for dataframe arithmetic we don't use the pool. Fix coming up.
