### ISSUE TITLE
Unique produces wrong results with large datasets

### ISSUE THREAD

**Issue by Ashafix** [pola-rs/polars#10852]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import os
os.environ['ARROW_LIBHDFS_DIR'] = '/opt/cloudera/parcels/CDH-5.16.2-1.cdh5.16.2.p4378.3970/lib64/'
import polars as pl
import pydoop.hdfs
import pyarrow.dataset as ds

filepath = 'user/ashafix/dummy_large_data/'
nameservice = 'custom-nameservice'
dataset = ds.dataset(f"hdfs://{nameservice}/{filepath}", format="parquet")
df = pl.scan_pyarrow_dataset(dataset)

results = df.select('CLIENT_ID').unique().collect()
print(results)
"""
shape: (100_000_000, 1)
┌──────────┐
│ CLIENT_ID   │
│ ---      │
│ i32      │
╞══════════╡
│ 65578752 │
│ 862016   │
│ 57088000 │
│ 37065344 │
│ …        │
│ 33763391 │
│ 3718975  │
│ 79786751 │
│ 66764607 │
└──────────┘
"""

results = df.unique().select('CLIENT_ID').unique().collect()
print(results)
shape: (8_618_559, 1)
"""
┌──────────┐
│ CLIENT_ID   │
│ ---      │
│ i32      │
╞══════════╡
│ 88259136 │
│ 56899136 │
│ 37698944 │
│ 78808320 │
│ …        │
│ 32087423 │
│ 75653823 │
│ 44269951 │
│ 38316159 │
└──────────┘
"""

results = df.unique().select('CLIENT_ID').collect()
print(results.unique())
"""
┌──────────┐
│ CLIENT_ID   │
│ ---      │
│ i32      │
╞══════════╡
│ 88259136 │
│ 56899136 │
│ 37698944 │
│ 78808320 │
│ …        │
│ 32087423 │
│ 75653823 │
│ 44269951 │
│ 38316159 │
└──────────┘
"""
```

### Issue description

Using `unique` prior to other operations leads to wrong results. This only occurs with larger datasets (>20GB of parquet files), smaler datasets produce correct results.

Generation of sample data.
* 100M client IDs are generated and shuffled
* For each ID a random start date is picked and between 1 to 150 lines with the ID, a date and some random data are created

Not sure if the actual data makes any difference but I wanted to have data which is similar to the data where the issue was encountered.

```python

import random
import datetime
import tqdm
import numpy as np

client_ids= [i for i in range(100 * 10**6)]
random.shuffle(client_ids)
with open('fakedata_random_large.txt', 'w') as f:
    for i in tqdm.tqdm(client_ids):
        date = datetime.date(year=random.randrange(1950, 2023), month=random.randrange(1, 12), day=random.randrange(1, 28))
        for j in range(np.clip(np.random.lognormal(mean=3, sigma=2, size=1), 1, 150).astype(int)[0]):
            date = date + datetime.timedelta(days=random.randrange(0, 10))
            line = f'{i}\t{date}\t{random.random()}\n'
            f.write(line)
```

Conversion to parquet was done via Apache Drill
```sql

CREATE TABLE dfs.d.`data/dummy_random_large_data` 
AS SELECT 
CAST(COLUMNS[0] as INT) AS CLIENT_ID,
TO_DATE (COLUMNS[1], 'yyyy-MM-dd') AS EVENT_DATE,
CAST(COLUMNS[2] AS FLOAT) AS DATA
from dfs.d.`data/fakedata_random_large.txt`
```

Using duckdb produced correct results, i.e. the issue is not caused by the parquet files or pyarrow.

### Expected behavior

~df.unique().select('COL').collect() should give the same number of rows as df.select('COL').unique().collect()~
df.unique().select('COL').unique().collect() should give the same number of rows as df.select('COL').unique().collect()

The issue is exemplified by unique but it happened with other functions as well. Large datasets produce smaller absolute numbers than smaller ones.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.1
Index type:          UInt32
Platform:            Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.31
Python:              3.9.16 (main, Jun  1 2023, 17:24:29) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.0
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
> `df.unique().select('COL').collect()` should give the same number of rows as `df.select('COL').unique().collect()`

Why should it? `df.unique()` considers *all* columns when doing its uniqueness test, and only selects column `COL` afterwards. The latter *first* extracts only column `COL` and only then does its uniqueness test. They are not the same:

```python
>>> df = pl.DataFrame({"x": [1, 1, 2], "y": [1, 2, 3]})
>>> df.unique().select("x")
shape: (3, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
│ 1   │
└─────┘
>>> df.select("x").unique()
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```

**Comment by Ashafix** [comment]
Apologies, the statement was misleading, what I meant is that `df.unique().select('COL').unique().collect()` (note the double `unique()`) should give the same number of rows as `df.select('COL').unique().collect()`. The second example (`df.unique().select('CLIENT_ID').unique().collect()`) gives less rows than the first example (`df.select('CLIENT_ID').unique().collect()`)

**Comment by orlp** [comment]
@Ashafix Do you have NaNs in your dataset? Our handling of NaNs around equality/hashing isn't proper yet everywhere, so that could explain it.

**Comment by Ashafix** [comment]
@orlp There are no NaNs at any position. The issue only occurs when the dataset becomes "large", 20 0.5G parquet files, all good, 40, the issue occurs.

**Comment by ritchie46** [comment]
This probably is a bug in our streaming unique. Can you show us the output when you start the process with `POLARS_VERBOSE=1`? 

I can take a look at this one in a few days.

**Comment by ritchie46** [comment]
I cannot reproduce this on the streaming engine with a smaller dataset and out-of-core forced. Cannot run the whole dataset as I go OOM whilst creating it.

@Ashafix it could also be that you surpass 4 billion rows. Your nested loop produces approximately 4.7 billion lines. Have you tried `polars-big-idx`?

And I'd still really appreciate a `POLARS_VERBOSE=1`.

**Comment by Ashafix** [comment]
@ritchie46 
I've tried setting the enivronment variable POLARS_VERBOSE to 1 but no additional output was sent to stdout.
Also running it in a context with didn't produce additional output. Not sure if I'm doing it right.

When running the 3 queries with `streaming=True`, the numbers were unchanged.

The parquet is about 400M rows
```python
df.select(pl.count()).collect()`
shape: (1, 1)
count
--
u32
404782699
```

**Comment by ritchie46** [comment]
> Using polars-u64-idx I am not able to run the above script on an instance with 512GB RAM. Calling df.unique().select('CLIENT_ID').unique().collect() causes the engine to crash with status 1.

Yes, OOM. try explicitly using `collect(streaming=True)` Though I am not sure we support pyarrow readers in the streaming API yet. :thinking:

**Comment by ritchie46** [comment]
I am confused why you didn't get a warning about the maximum size reached. Will look into that.

**Comment by ritchie46** [comment]
Fix coming up. Next time you should get a panic. For your use-case you need polars-u64-idx.

We hope to support pyarrow readers in streaming soon.

**Comment by Ashafix** [comment]
After updating to polars 0.19.3, the code now throws the expected error.

`pyo3_runtime.PanicException: ("polars' maximum length reached. Consider installing 'polars-u64-idx'.: TryFromIntError(())“,) `
