### ISSUE TITLE
Implement `array_to_string` function in sql

### ISSUE THREAD

**Issue by Barsik-sus** [pola-rs/polars#10858]
### Problem description

I encountered a problem where I needed to concatenate the values within a column, which is stored as a list, using SQL. I attempted to find a suitable SQL function for this task but couldn't find any. While I can achieve the desired result in code using `col(name).list().join(sep)`, I am unable to achieve the same outcome directly in SQL.

An example of what the expected functionality would do:

Suppose I have a table df with the following data:
|         a        |
|------------------|
|['Hello', 'World']|

I want to perform an SQL operation that concatenates the list values within column a using a separator, resulting in the following output:
`SELECT array_to_string(a, ', ') FROM df`:
|         a        |
|------------------|
|  'Hello, World'  |

**Comment by orlp** [comment]
But this isn't what `concat_ws` does in databases. There it concatenates columns with the given separator. E.g. in DuckDB:

```sql
CREATE TABLE foo (name TEXT, city TEXT);
INSERT INTO foo VALUES ('alice', 'amsterdam'), ('bob', 'berlin');
SELECT concat_ws('/', name, city) FROM foo;
┌──────────────────────────────┐
│ concat_ws('/', "name", city) │
│           varchar            │
├──────────────────────────────┤
│ alice/amsterdam              │
│ bob/berlin                   │
└──────────────────────────────┘
```

It does not concatenate lists:

```sql
CREATE TABLE foo (names TEXT[], city TEXT);
INSERT INTO foo VALUES (['alice', 'allison'], 'amsterdam'), (['bob', 'bobson'], 'berlin');
SELECT concat_ws('/', names), city FROM foo;
┌─────────────────────────┬───────────┐
│ concat_ws('/', "names") │   city    │
│         varchar         │  varchar  │
├─────────────────────────┼───────────┤
│ [alice, allison]        │ amsterdam │
│ [bob, bobson]           │ berlin    │
└─────────────────────────┴───────────┘
```

**Comment by orlp** [comment]
The function you *want* and have implemented is called `array_to_string` in Postgres and DuckDB:

```SQL
CREATE TABLE foo (names TEXT[], city TEXT);
INSERT INTO foo VALUES (['alice', 'allison'], 'amsterdam'), (['bob', 'bobson'], 'berlin');
SELECT array_to_string(names, '/'), city FROM foo;
┌───────────────────────────────┬───────────┐
│ array_to_string("names", '/') │   city    │
│            varchar            │  varchar  │
├───────────────────────────────┼───────────┤
│ alice/allison                 │ amsterdam │
│ bob/bobson                    │ berlin    │
└───────────────────────────────┴───────────┘
```
