### ISSUE TITLE
Strange behavior around int_range with Uint32

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10867]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```python
>>> pl.select(pl.int_range(pl.lit(3).cast(pl.UInt32), -1, -1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7663, in select
    return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.NoDataError: no data in `end` evaluation
```

### Issue description

The above produces a mysterious error, but only for `pl.Uint32`.

### Expected behavior

The same behavior as when the cast is to any other type, e.g. `Uint64`:

```python
>>> pl.select(pl.int_range(pl.lit(3).cast(pl.UInt8), -1, -1))
shape: (5, 1)
┌─────┐
│ int │
│ --- │
│ i64 │
╞═════╡
│ 3   │
│ 2   │
│ 1   │
│ 0   │
│ -1  │
└─────┘
```

Well, except that this still has the incorrect lower bound as noted in https://github.com/pola-rs/polars/issues/10865.

### Installed versions

0.19.1

**Comment by stinodego** [comment]
Yeah, there's some 'special case' for UInt32 that I think should be removed. It's probably in there for the purpose of creating indexes though 🤔 worth further investigation.

**Comment by detrin** [comment]
I could try to investigate, cloning polars right now.

**Comment by detrin** [comment]
So I see we have

```rust
#[pyfunction]
pub fn int_range(start: PyExpr, end: PyExpr, step: i64, dtype: Wrap<DataType>) -> PyExpr {
    let dtype = dtype.0;

    let mut result = dsl::int_range(start.inner, end.inner, step);

    if dtype != DataType::Int64 {
        result = result.cast(dtype)
    }

    result.into()
}
```
https://github.com/pola-rs/polars/blob/main/py-polars/src/functions/range.rs#L8

**Comment by detrin** [comment]
Then we have
```rust
#[cfg(feature = "range")]
/// Generate a range of integers.
pub fn int_range(start: Expr, end: Expr, step: i64) -> Expr {
    let input = vec![start, end];

    Expr::Function {
        input,
        function: FunctionExpr::Range(RangeFunction::IntRange { step }),
        options: FunctionOptions {
            allow_rename: true,
            ..Default::default()
        },
    }
}
```
https://github.com/pola-rs/polars/blob/c4fdbfe2c7f7ce7616ad9301981bc5d616c3beef/crates/polars-plan/src/dsl/functions/range.rs#L13

**Comment by detrin** [comment]
Okay so the step is -1 of type i64. I have a hunch that that is the core of that issue, that the type of step is defined there.

**Comment by detrin** [comment]
This is the actual rust evaluation that is going on https://github.com/pola-rs/polars/blob/c4fdbfe2c7f7ce7616ad9301981bc5d616c3beef/crates/polars-plan/src/dsl/function_expr/range.rs#L32

**Comment by detrin** [comment]
So I played around with the rust part to realize that this is okay. So my suggestion is that the issue is `pl.select()` rather than `pl.int_rage()`

```rust 
fn main() {
    let start: i32 = 3;
    let end: i32 = -1;
    let step: i64 = -1;
    let l = (end..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
}
```

**Comment by milicevica23** [comment]
I played around with that and found out that it works with end >= 0 but not with end < 0

**Comment by milicevica23** [comment]
So @stinodego was right the problem is with index type which is Uint32

I am not sure how to fix it but at least the explanation of the wrong behavior 
1. We take just start type for comparison
2. go int Uint32 branch of the match 
3. cast end to Uint32 -> therefore it worked for positive numbers otherwise exception
4. call of int_range<Uint32> would not work anyway with negative end 

![image](https://github.com/pola-rs/polars/assets/46800472/b7684812-3357-4537-8364-9566debda98e)

So what we should do is to miss first match branch, but i am not sure what is the best way to do so? @stinodego
What was the intention of that branch, what is the use case with index which should potentialy work?
