### ISSUE TITLE
unexpected print to console?

### ISSUE THREAD

**Issue by bernardodionisi** [pola-rs/polars#10861]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

On a mac M1 machine the following code

```python
import polars as pl
date = pl.date(pl.col("year"), 1, 1)
```
prints 'ambiguous: Utf8(raise)' to console.

### Issue description

Possibly unexpected print to console: 'ambiguous: Utf8(raise)'. It does not seem to happen, for me, on linux.

### Expected behavior

no print?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.1
Index type:          UInt32
Platform:            macOS-13.5.1-arm64-arm-64bit
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.0
pydantic:            1.10.11
sqlalchemy:          2.0.17
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
@stijndegooijer or @MarcoGorelli, have you got any idea about this one?

**Comment by cmdlineluser** [comment]
Looks like it may be:
https://github.com/pola-rs/polars/blob/be26528a072d9a4bfad062783091b758bcd42e8f/py-polars/src/functions/lazy.rs#L243

**Comment by alexander-beedie** [comment]
Yup, it's that; spotted/fixed  ;)
