### ISSUE TITLE
Feature Request: Selectors for Columns with Missing Data and Conditional Selectors

### ISSUE THREAD

**Issue by adityaxbiswas** [pola-rs/polars#10870]
### Problem description

It would be extremely handy for data manipulation if there was a pre-built selector for grabbing all columns with any missing values (or alternately, no missing values).

I believe this should be feasible and fast, since the null counts are simply metadata on the underlying arrow arrays.

With respect to conditional selectors, I mean that you provide the selector with a boolean expression that determined whether to select the column or not.  Here's a stackexchange link that demos one way to do this, but it seems a little verbose:
https://stackoverflow.com/questions/75446886/selecting-columns-based-on-a-condition-in-polarshttps://stackoverflow.com/questions/75446886/selecting-columns-based-on-a-condition-in-polars
The relevant section translated to the missing data selection problem (as an example) looks like

```python
df.select(
   col.name for col in 
   df.select(pl.all().null_count() > 0) 
   if col.all()
)
```

It would be very useful if this pattern could be wrapped up into a standard function or something.  I know that the following code works

```python
df[:,(df.null_count() > 0).row(0)]
```

But this feels more like pandas syntax than the "polars way" of doing things.

**Comment by cmdlineluser** [comment]
The URL you've given is broken (duplication): https://stackoverflow.com/questions/75446886/selecting-columns-based-on-a-condition-in-polars

Your specific `.null_count()` is a little different and can be simplified:
```python
df = pl.DataFrame({
   "foo": [1, None, 2], 
   "bar": [None, 3, 4], 
   "baz": [1, 2, 3]
})

df.select(col for col in df if col.null_count() > 0)

# shape: (3, 2)
# ┌──────┬──────┐
# │ foo  ┆ bar  │
# │ ---  ┆ ---  │
# │ i64  ┆ i64  │
# ╞══════╪══════╡
# │ 1    ┆ null │
# │ null ┆ 3    │
# │ 2    ┆ 4    │
# └──────┴──────┘
```
(Technically, you can omit the `> 0` in this case also.)

**Comment by alexander-beedie** [comment]
With the current selector infrastructure this isn't possible - not that we couldn't write a python-side method in `selectors` that did this, as we absolutely could. What I mean by that is that the "real" underlying selector code (down in Rust) only operates against the frame _schema_. So, writing a selector that expands into suitable columns based on knowledge of data in the frame isn't currently supported. It's an interesting idea though; will have to look a bit harder at the code to see if it's reasonable or not to allow selector expansion to look at the frame properties as well as the schema properties 🤔
