### ISSUE TITLE
Allow multiple conditions for filter

### ISSUE THREAD

**Issue by datapythonista** [pola-rs/polars#10888]
### Problem description

Has it been considered to allow more than one condition to `DataFrame.filter` and `LazyFrame.filter`?

```python
# this would also be possible:
iris_df.filter(pl.col('species') == 'setosa',
               pl.col('petal_length') >= 1.2,
               pl.col('petal_width') >= 0.3)

# and would be equivalent to this, which IMHO is much less readable
iris_df.filter((pl.col('species') == 'setosa')
               & (pl.col('petal_length') >= 1.2)
               & (pl.col('petal_width') >= 0.3))
```

Feels like it's a very common use case, and would allow more readable code. In particularly because not being able to overload `and` and having to use `&` and it's inconvenient operator precedence.

I guess the change would be very easy to implement, the API a bit more complex but still quite simple, and the change would be backward compatible.

**Comment by avimallu** [comment]
Have you tried the `and_` and `or_` variants that allow you to combine conditions?

**Comment by datapythonista** [comment]
> Have you tried the `and_` and `or_` variants that allow you to combine conditions?

Thanks @avimallu, very good point. I also think the result is also less readable than accepting multiple conditions:

```python
iris_df.filter((pl.col('species') == 'setosa')
                   .and_(pl.col('petal_length') >= 1.2)
                   .and_(pl.col('petal_width') >= 0.3))
```

If `polars.and_` existed (I don't think there is) the code would be a bit more readable IMHO:

```python
iris_df.filter(pl.and_(pl.col('species') == 'setosa',
                       pl.col('petal_length') >= 1.2,
                       pl.col('petal_width') >= 0.3))
```

But still, to me personally, and if I'm not missing anything, the proposed syntax seems clearer and easier to read, and implementing it and the final API seem simpler enough to make it worth. Just a personal opinion of course.

**Comment by avimallu** [comment]
Oh, my point was that you don't need the second `and_`. Just add your third condition as the second argument for the first call to `and_`.

**Comment by datapythonista** [comment]
> Oh, my point was that you don't need the second `and_`. Just add your third condition as the second argument for the first call to `and_`.

You are right. I added two more examples to my comment, to show how what you say would look like, and one with `pl.lit(True)` to avoid the impression that conditions are nested. But I still find that the proposed here would be simpler, better and more readable for users.

**Comment by cmdlineluser** [comment]
You can also use `.all_horizontal` / `.any_horizontal`

```python
.filter(pl.all_horizontal(
    pl.col('species') == 'setosa',
    pl.col('petal_length') >= 1.2,
    pl.col('petal_width') >= 0.3
))
```

**Comment by s-banach** [comment]
I use .ge() instead of >=, that helps a little.

**Comment by orlp** [comment]
I don't think we'd want this. The whole point of Polars and why it's so nice to use is that the API consists of small composable functions, rather than specific functions/arguments/syntax for each specific case. Also I disagree that accepting multiple arguments is more readable than  combining with `&`, in the former case it's unclear if *all* conditions need to be met, or just *any* condition, while in the case of `&` it's entirely unambiguous.
