### ISSUE TITLE
Allow `glimpse()` to be customized by exposing two local variables as function arguments

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10889]
### Problem description

`glimpse()` [defines](https://github.com/pola-rs/polars/blob/py-0.19.1/py-polars/polars/dataframe/frame.py#L4012-L4013) two local variables with the maximum number of values to be shown and the maximum column name length that will print without truncation:

```python
# always print at most this number of values, mainly used to ensure
# we do not cast long arrays to strings which would be very slow
max_num_values = min(10, self.height)
max_col_name_trunc = 50
```
It would be really neat to expose these as arguments to `glimpse()`, especially the first one! It might be worth giving them more descriptive names though, say `max_elements_per_column` and `max_col_name_width`?

**Comment by alexander-beedie** [comment]
Makes sense to me 👍
