### ISSUE TITLE
Panic 'index out of bounds' when using sum_horizontal and a column selection resulting in no columns selected

### ISSUE THREAD

**Issue by andber1** [pola-rs/polars#10894]
### Checks

 - [x] I have checked that this issue has not already been reported.
 - [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    let df = DataFrame::new(vec![Series::new("col1", [1.0])]).unwrap();
    let df = df
        .lazy()
        .with_column(sum_horizontal([col("*").exclude(["col1"])]).alias("sum"))
        .collect()
        .unwrap();
```

### Issue description
When running the example the following panic occurs:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', .../polars-plan-0.32.1/src/dsl/expr_dyn_fn.rs:290:27
```
The column selection `col("*").exclude(["col1"])` is empty and the example does not do something useful. However, I would not expect a panic in this case.

### Expected behavior
I would expect no panic and that this corner case works just as it does when using a `fold_exprs` instead of `sum_horizontal`. This example works:
```rust
    let df = DataFrame::new(vec![Series::new("col1", [1.0])]).unwrap();
    let df = df
        .lazy()
        .with_column(
            fold_exprs(
                lit(0.0),
                |acc, x| Ok(Some(acc + x)),
                [col("*").exclude(["col1"])],
            )
            .alias("sum"),
        )
        .collect()
        .unwrap();
```

### Installed versions
polars = { version = "0.32.1", features = ["lazy"] }

PS: The issue template for Rust bug reports does not work. I tried to follow the template manually.

**Comment by cmdlineluser** [comment]
Python repro:
```python
df = pl.DataFrame({"col1": [1]})

df.select(pl.sum_horizontal(pl.exclude("col1")))

# thread '<unnamed>' panicked at /Users/user/git/polars/crates/polars-plan/src/dsl/expr_dyn_fn.rs:290:27:
# index out of bounds: the len is 0 but the index is 0
```

**Comment by andber1** [comment]
>>PS: The issue template for Rust bug reports does not work. I tried to follow the template manually.
> 
> A bit off-topic, but in what sense does it not work?

When I clicked on "New Issue" a bug report was not an option. It was fixed just a few minutes ago. See #10896.
