### ISSUE TITLE
Allow str.slice to take Exprs instead of a fixed offset/length

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10890]
### Problem description

Right now you can only pass a fixed offset and length to str.slice. It would be much more useful if you could pass in an Expr instead, so you can vary the length/offset arbitrarily as needed in your query.

This can have a variety of uses, for example the computation of n-grams as in https://github.com/pola-rs/polars/issues/10833.

**Comment by mcrumiller** [comment]
I got stuck on this exactly issue when trying to implement `head`/`tail` in #10339.

**Comment by alexander-beedie** [comment]
Closed by #13747 👌
