### ISSUE TITLE
Add README.md's to all internal crates pointing to the main crate

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10909]
I think it would look better on crates.io if the internal crates are marked as such, with a link to the main `polars` crate in a `README.md`. Right now it seems rather confusing, e.g.: https://crates.io/crates/polars-plan

**Comment by stinodego** [comment]
Good idea!

**Comment by KacpiW** [comment]
Looks like a good first issue. Would you mind if I could help you with that?

**Comment by stinodego** [comment]
Sure!
