### ISSUE TITLE
Intra-doc links in rust api documentation

### ISSUE THREAD

**Issue by mrogowski11** [pola-rs/polars#10904]
### Problem description

I think it would be a good idea to provide direct links to rustdoc pages of structs, traits etc. As is, when you read documentation and want to read up on, let's say, `DataFrame` you need to search the whole doc or manually navigate to frame module. It would increase quality of life if you could click an element and be redirected to a corresponding doc page (in this case [DataFrame](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html)).

At the time of writing the issue:
![image](https://github.com/pola-rs/polars/assets/18427783/83f5d7c6-db88-4796-947f-db37020bd2e9)
Proposal:
![image](https://github.com/pola-rs/polars/assets/18427783/c6cf4b31-8297-4299-b773-528139de0a19)

If such a change is desired I could work on it.

**Comment by orlp** [comment]
Such a change is always welcome in principle, it's just a lot of work.

The only concern I have is that our current Rust API is... really messy. We are leaking our internals all over the place in the current Rust version. The plan is to add another abstraction layer in the future such that the public-facing `polars` crate is nice and clean, and ideally has feature-parity and synchronization with the Python version.

The problem with that is that some objects will move around in their canonical location, some will disappear, etc. If a lot of doc comments refer to a specific location / object it might be a lot of refactor work in the future to also update all doc comments. Are there tools for that?

**Comment by mrogowski11** [comment]
@orlp LSPs are able to handle simple refactors (like renaming) inside docstrings. Adaptation to structural changes would be trickier. I do not think there are any tools to automate the whole process. At the same time dangling links (created after refactors) can be easily spotted by _cargo doc_ (it outputs warnings in such cases) so any future updates would be a matter of bunch of search-and-replace based on its output.

**Comment by stinodego** [comment]
This would be welcome! At least linking the main objects should be easily doable.

As a side-note, I prefer the syntax where the full link is put separately below the docstring:

```rust
/// Some text... [`Arc::get_mut`][Arc::get_mut] 
/// More text...
///
/// [Arc::get_mut]: std::sync::Arc::get_mut
```
