### ISSUE TITLE
Github and RustSec Advisories on lexical

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#10910]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

lexical is an active dependency

### Issue description

https://github.com/advisories/GHSA-c2hm-mjxv-89r4
https://rustsec.org/advisories/RUSTSEC-2023-0055.html

with the lexical maintainer even specifically calling out polars using lexical as one of his accomplishments:
https://github.com/Alexhuszagh

### Expected behavior

replace lexical with an alternative crate/approach as detailed in the advisories

### Installed versions

master

**Comment by orlp** [comment]
Yes, we're already aware of this and in the process of moving away from lexical.

**Comment by orlp** [comment]
Relevant PR: https://github.com/pola-rs/polars/pull/10655.

**Comment by stinodego** [comment]
I'll close this as we're working on it and have the dependabot alert to track this.
