### ISSUE TITLE
Extremally poor performance with very long expressions

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#10926]
### Checks

- [X] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl 
import time 

def loop_add(c:pl.Expr, n:int)->pl.Expr:
    for _ in range(n):
        c = (c+c) / 2 # This is obviously a dummy operation, but the issue is still present
    return c

df = pl.DataFrame({
    'x':[1,2,3]
})


for n in [1,10,100]:
    t_start = time.time()
    
    df.with_columns(
        x2 = loop_add(pl.col('x'), n=n)
    )
    
    t_end = time.time()
    duration = t_end - t_start
    
    print(f'Duration running {n=}: {duration:.0f}')
```

### Log output

```shell
Duration running n=10: 0.04
Duration running n=20: 69.85
Duration running n=30: (Consumed 100Gb of memory+ and then crashed the server)
```

### Issue description

For some reason the code above performs extremely badly.

The operation should take milliseconds at most but takes well over 1 minute with n=20, and with n=30 it crashed the server.

### Expected behavior

Execution should be quick

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.0
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2022.8.2
matplotlib:          3.7.2
numpy:               1.22.4
pandas:              2.1.0
pyarrow:             10.0.1
pydantic:            1.10.2
sqlalchemy:          1.4.44
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by mcrumiller** [comment]
> The operation should take milliseconds at most

I think you're underestimating the power of recursion here, the number of column references you have equals 2^(n+1):

```
# stage 1: 2 column references
(c+c) / 2

# stage 2: 4 column references
((c+c) / 2+(c+c) / 2) / 2

# stage 3: 16 column references
((((c+c) / 2+(c+c) / 2) / 2+((c+c) / 2+(c+c) / 2) / 2) / 2+(((c+c) / 2+(c+c) / 2) / 2+((c+c) / 2+(c+c) / 2) / 2) / 2) / 2
```

`n = 10` gives you 2048 column references, which is pretty complex as-is, so 0.04s seems reasonable to me.

`n = 20` gives you an expression with 2,097,152 column references. That's over *two million* references to pl.col(), yeah it's gonna take a while, it has to build a giant AST.

`n = 30` gives you 2,147,483,648, or *two billion* references to `pl.col`. If an entire `pl.col` object were just one byte, we're already talking 2.1GB of data here *just to use a single character to represent the column*. The expression is much larger than that.

I don't think there's any problem here.

**Comment by mcrumiller** [comment]
I think this might actually open the door to a feature request for more optimizations when arithmetic is involved.

**Comment by mkleinbort-ic** [comment]
I still think there should be some optimization. The same function if executed eagerly should take only a few moments. 

```python
import pandas as pd 
import time 

def loop_add(c:pd.Series, n:int):
    for _ in range(n):
        c = (c+c) / 2 # This is obviously a dummy operation, but the issue is still present
    return c

df = pd.DataFrame({
    'x':[1,2,3]
})


for n in [10, 20, 30]:
    t_start = time.time()
    
    df.assign(
        x2 = lambda x: loop_add(x['x'], n=n)
    )
    
    t_end = time.time()
    duration = t_end - t_start
    
    print(f'Duration running {n=}: {duration:.2f}')
   
   
>>> 
Duration running n=10: 0.00
Duration running n=20: 0.00
Duration running n=30: 0.00

 ```


Do you think the engine could be extended to optimize the plan in a sub-expression kind of way.

**Comment by mkleinbort-ic** [comment]
For completeness, here is an "eager" polars implementation:
```python
import polars as pl 
import time 

def loop_add(c:pl.Expr, n:int):
    for _ in range(n):
        c = (c+c) / 2 # This is obviously a dummy operation, but the issue is still present
    return c


for n in [10, 20, 30]:
    df = pl.DataFrame({
        'x':[1,2,3]
    })


    t_start = time.time()
    
    for i in range(n):
        df = df.with_columns(x=loop_add(pl.col('x'), n=1)
    )
    
    t_end = time.time()
    duration = t_end - t_start
    
    print(f'Duration running {n=}: {duration:.2f}')
    
 ```
 Runs in < 1ms
