### ISSUE TITLE
Typespec of polars `pipe` incorrect on constrained TypeVar

### ISSUE THREAD

**Issue by GRcharles** [pola-rs/polars#10929]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

`test.py`:
```python
from typing import TypeVar

import polars as pl

Frame = TypeVar("Frame", pl.LazyFrame, pl.DataFrame)

df = pl.DataFrame()


def identity(f: Frame) -> Frame:
    return f


r_df: pl.DataFrame = df.pipe(identity)
```

run `mypy test.py`

### Log output

```shell
test.py:14: error: Incompatible types in assignment (expression has type "Frame", variable has type "DataFrame")  [assignment]
test.py:14: error: Argument 1 to "pipe" of "DataFrame" has incompatible type "Callable[[Frame], Frame]"; expected "Callable[[DataFrame], Frame]"  [arg-type]
test.py:14: note: This is likely because "identity" has named arguments: "f". Consider marking them positional-only
Found 2 errors in 1 file (checked 1 source file)
```

### Issue description

in the `pipe` function of a pl.DataFrame, polars binds the input argument to DataFrame, but just keeps the output type as is.

However, this approach does not work when the input variable is a TypeVar - to correctly type this, the output type needs to be bound when the input type is.

Adding the following to `polars.dataframe.frame.DataFrame` above the existing definition for `pipe` fixes the issue:
```
@overload
    def pipe(
        self,
        function: Callable[Concatenate[DataFrame, P], DataFrame],
        *args: P.args,
        **kwargs: P.kwargs,
     ) -> T:
        ...
```

note a similar fix is also needed for the pipe operator in `polars.dataframe.frame.LazyFrame`

### Expected behavior

mypy shows no type errors

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.0
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.19
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
`mypy` is correct here. `DataFrame.pipe` requires a callable with the first argument a `DataFrame`. Your function has a `TypeVar` as a first argument.
