### ISSUE TITLE
column of type `int` compared to `list[int]` of length 1 evaluating as `true`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#10920]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 2], "b": [[1], [1, 2]]})

df.filter(pl.col('a') == pl.col('b'))
# shape: (1, 2)
# ┌─────┬───────────┐
# │ a   ┆ b         │
# │ --- ┆ ---       │
# │ i64 ┆ list[i64] │
# ╞═════╪═══════════╡
# │ 1   ┆ [1]       │
# └─────┴───────────┘

df.select(pl.col('a') == pl.col('b'))
# shape: (2, 1)
# ┌───────┐
# │ a     │
# │ ---   │
# │ bool  │
# ╞═══════╡
# │ true  │
# │ false │
# └───────┘
```

### Issue description

Comparing a column of type `int` to a column of type `list[int]` evaluates as `true` if the list has a length of 1 and the values are the same.

(seems to be for float also, str raises as expected)

### Expected behavior

Should not be equal.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.1
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Just to add, this appears to have changed in `0.19.0`

It raises in `0.18.15`
```python
# v0.18.15
pl.select(pl.lit(1) == pl.lit([[1]]))

# ArrowErrorException: NotYetImplemented(
# "Casting from Int32 to LargeList(Field { name: \"item\", data_type: Int64, is_nullable: true, metadata: {} }) 
# not supported")
```
And it appears to be a "numeric" issue (as opposed to int specific):
```python
# v0.19.2
pl.select(pl.lit(1.0) == pl.lit([[1]]))

# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ bool    │
# ╞═════════╡
# │ true    │
# └─────────┘
```

**Comment by reswqa** [comment]
> Just to add, this appears to have changed in 0.19.0. It raises in 0.18.15.

FYI, We support the conversion of primitive type to list type in `0.19.0`. The `==` operation will attempt to cast the left and right sides into a super type for comparison, resulting in this phenomenon. I'm not sure if casting to nested types should be prohibited when making this comparison here.

**Comment by stinodego** [comment]
Right, so I am not sure this is a bug.

@ritchie46 what should we do here?

**Comment by ritchie46** [comment]
I don't think we should cast to nested types.

**Comment by stinodego** [comment]
So I tried removing the code that allows casting a list and a non-list to a list:
https://github.com/pola-rs/polars/blob/4bfa765536d03ea4e87f2f1c85d604ab6fdb05c0/crates/polars-core/src/utils/supertype.rs#L237-L241

This 'fixes' the example, in the sense that it will panic:
```
pyo3_runtime.PanicException: cannot coerce datatypes: ComputeError(ErrString("failed to determine supertype of i64 and list[i64]"))
```

However, that stops a lot of other things from working as expected, mostly in the context of grouped aggregation:

```python
import polars as pl

df = pl.DataFrame(
    {
        "x": ["a", "b", "a", "b", "a", "b"],
        "val": [1, 20, 100, 2000, 10000, 200000],
    }
)
result = df.group_by("x").agg(pl.col("val") + pl.col("val").shift().fill_null(0))
print(result)
# polars.exceptions.ComputeError: failed to determine supertype of list[i64] and i64
```
I'm not sure how to proceed here.

**Comment by cmdlineluser** [comment]
This now produces an appropriate SchemaError.

```python
SchemaError: could not evalulate comparison between series 'a' of dtype: i64 and series 'b' of dtype: list[i64]
```
