### ISSUE TITLE
Should all functions that use `pattern` also have an argument `literal`?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#10930]
### Problem description

Originally I was just surprised that `str.count_match()` doesn't have an argument `literal` and then I realized that several functions that have `pattern` don't have a `literal` argument. Does it make sense to add this argument in all functions where we can use `pattern`?

Currently, those functions have both `pattern` and `literal`:

* `str.contains()`
* `str.replace()`
* `str.replace_all()` 

and those functions only have `pattern`:

* `str.count_match()`
* `str.extract()`
* `str.extract_all()`
* `str.extract_groups()`

---

Slightly related to https://github.com/pola-rs/polars/issues/4819#issuecomment-1362679588

**Comment by orlp** [comment]
I think yes.

**Comment by orlp** [comment]
In hindsight, it doesn't make much sense for the `extract` variants to have a `literal` argument.
