### ISSUE TITLE
polars hiccup with pyarrow 5.0

### ISSUE THREAD

**Issue by davideger** [pola-rs/polars#1093]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

Polars 0.8.16, Pyarrow 5.0

#### What operating system are you using polars on?

Google colab (x86-64)

#### Describe your bug.

```
Requirement already satisfied: polars in /usr/local/lib/python3.7/dist-packages (0.8.16)
Requirement already satisfied: pyarrow>=4.0.* in /usr/local/lib/python3.7/dist-packages (from polars) (5.0.0)
```
It looks like pyarrow 5.0 is incompatible with the distribution of polars 0.8.16.  I get this error message on import:
```

/usr/local/lib/python3.7/dist-packages/pyarrow/_compute.pyx in init pyarrow._compute()

ValueError: pyarrow.lib.Codec size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
```

If I force `pyarrow=4.0.1` the issue goes away.

**Comment by ritchie46** [comment]
Could you try version `0.8.17`. Does that work with pyarrow 5.0?

**Comment by davideger** [comment]
Aha that fixed it, thank you!
