### ISSUE TITLE
Partial schema in from_dicts doesn't work any longer?

### ISSUE THREAD

**Issue by indigoviolet** [pola-rs/polars#10943]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

In [1]: import polars as pl

In [2]: pl.__version__
Out[2]: '0.19.2'

In [3]: pl.from_dicts([{"a": 1, "b": 2}], schema=["a"])
Out[3]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘

In [4]: pl.from_dicts([{"a": 1, "b": 2}], schema=["b"])
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 pl.from_dicts([{"a": 1, "b": 2}], schema=["b"])

In [5]: pl.from_dicts([{"a": 1, "b": 2}], schema={"a": None})
Out[5]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘

In [6]: pl.from_dicts([{"a": 1, "b": 2}], schema={"b": None})
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Cell In[6], line 1

```

### Issue description

>If you want to drop some of the fields found in the input dictionaries, a _partial_ schema can be declared, in which case omitted fields will not be loaded. Similarly, you can extend the loaded frame with empty columns by adding them to the schema.

### Expected behavior

Output for partial `b` should be like partial `a`, keeping only the `b` column

### Installed versions

<details>

```
In [3]: pl.show_versions()
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            macOS-13.4-arm64-arm-64bit
Python:              3.11.3 (main, May  7 2023, 17:43:38) [Clang 16.0.3 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.0
matplotlib:          3.7.2
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by ritchie46** [comment]
So this does work when the partial schema is a `dict`. Have we ever supported a partial schema with list input?

**Comment by hxzhao527** [comment]
https://github.com/pola-rs/polars/blob/d3721f15167c080df6c843bb6d8b07105e1fc932/py-polars/polars/utils/_construction.py#L624-L629

above code do this _magic_.
but it is not *sub_set* but *sub_slice*.

maybe we need this
```python
    if set(pydf_columns).issuperset(set(columns)):
        column_subset = columns
    elif len(columns) == len(pydf_columns):
        pydf.set_column_names(columns)
    else:
        raise ShapeError(f"{len(columns)} column names provided for a dataframe of width {len(pydf_columns)}")
```

**Comment by indigoviolet** [comment]
> So this does work when the partial schema is a `dict`. Have we ever supported a partial schema with list input?

@ritchie46 I am confused -- it doesn't work even when the partial schema is a dict?

> ```python
> In [6]: pl.from_dicts([{"a": 1, "b": 2}], schema={"b": None})
> ---------------------------------------------------------------------------
> ShapeError                                Traceback (most recent call last)
> Cell In[6], line 1
> ```

**Comment by ritchie46** [comment]
Oh, right. only `pl.from_dicts([{"a": 1, "b": 2}], schema={"a": None})` seems to work.
