### ISSUE TITLE
Can support for arrow_odbc be added to pl.read_database?

### ISSUE THREAD

**Issue by ldacey** [pola-rs/polars#10941]
### Problem description

Is it possible to add support for another database library? Ref #10649

https://github.com/pacman82/arrow-odbc-py

This is a python wrapper around a rust library and retrieves data directly in pyarrow format. I have used it for a while after switching from Turbodbc and have not faced any issues.

I tried to pass the results of the connect_to_database() function I saw, but it was not accepted by pl.read_database().

**Comment by alexander-beedie** [comment]
Thanks for the issue; unfortunately I wasn't able to install this library on a Mac (it failed to install and/or build from both `pip` and `conda`) in order to start looking at integration. 

I have started setting up a virtualised x86 environment at home (on a QNAP NAS, hah), so once that's up & running I'll return to this.

**Comment by ldacey** [comment]
I tried to install on an M2 Macbook and ran into issues as well hmm. Interesting because I used this library to get away from the issues I had with installed Turbodbc with pip (on Linux in a Docker Image). I did not try locally on my macbook until just now though. ODBC is a mess, especially if you need to have several drivers installed (I have to support MS SQL, MySQL, PostgreSQL, and Snowflake). Hopefully I can use ADBC for PG in the future, but I am not sure what the best solution is for MS SQL which a lot of enterprise data is sourced from...

**Comment by alexander-beedie** [comment]
> I tried to install on an M2 Macbook and ran into issues as well hmm. Interesting because I used this library to get away from the issues I had with installed Turbodbc with pip (on Linux in a Docker Image). I did not try locally on my macbook until just now though. ODBC is a mess, especially if you need to have several drivers installed (I have to support MS SQL, MySQL, PostgreSQL, and Snowflake). Hopefully I can use ADBC for PG in the future, but I am not sure what the best solution is for MS SQL which a lot of enterprise data is sourced from...

I believe `connectorx` has MsSQL support, so you could use `read_database_uri` for now?
(Will get `arrow-odbc` integrated either way, but that might help you out).

**Comment by alexander-beedie** [comment]
> I tried to pass the results of the connect_to_database() function I saw, but it was not accepted by pl.read_database().

I had a look at that, but turns out that it's a completely opaque object that an only be used internally by `arrow-odbc`; as a result, I've allowed `read_database` to take the ODBC connection string directly (just pass to the "connection" param).
