### ISSUE TITLE
Literal bool in `pl.when` causes incorrect broadcasted length

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10947]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"x": [1, 2, 3]})
conditions = [
    True,
    pl.col('x').first() == 1,
    False,
    pl.col('x').first() == 0,
]
for cond in conditions:
     print(df.select(pl.when(cond).then(pl.col('x')).otherwise(pl.lit(1))).sum()[0,0])
```

### Log output

```shell
6
6
1
3
```

### Issue description

When `pl.when` receives a literal boolean argument, it simply chooses one of the branches and discards the other entirely, which is not correct if one of the branches needs to be broadcast to match lengths. This could only be done in a valid manner if our optimizer was length-aware and inserted an explicit broadcast operator.

### Expected behavior

```
6
6
3
3
```

### Installed versions

0.19.1

**Comment by henryharbeck** [comment]
To build on this, it seems to only to be an issue when both the `when` and `otherwise` are literals, and no other non-literals are selected. E.g.
```python

df = pl.DataFrame({"x": [1, 2, 3]})

df.select(pl.when(False).then(pl.col("x")).otherwise(pl.lit(1)))
# ┌─────┐
# │ x   │
# ╞═════╡
# │ 1   │
# └─────┘

df.select(pl.lit(4), pl.when(False).then(pl.col("x")).otherwise(pl.lit(1)))
# ┌─────────┬─────┐
# │ literal ┆ x   │
# ╞═════════╪═════╡
# │ 4       ┆ 1   │
# └─────────┴─────┘

# not until a non-literal is selected that the literal gets broadcast
df.select("x", pl.when(False).then(pl.col("x")).otherwise(pl.lit(1)).alias("y"))
# ┌─────┬─────┐
# │ x   ┆ y   │
# ╞═════╪═════╡
# │ 1   ┆ 1   │
# │ 2   ┆ 1   │
# │ 3   ┆ 1   │
# └─────┴─────┘

**Comment by stinodego** [comment]
This seems to have been fixed.
