### ISSUE TITLE
Extra technical detail in certain docs

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#10950]
### Problem description

Here are a few questions off the top of my head:
- According to the docs, `not Series.has_validity() ==> Series.null_count() is 0`.
  Does the converse hold? I.e., `Series.has_validity() ==> Series.null_count() > 0`?
  The docs don't answer either way.
 - Is `Series.arg_max` guaranteed to return the index of the *first* maximum value?
 - Is a left join guaranteed to preserve the row order of the left DataFrame?
  - Are there circumstances in which functions like `filter` and `drop_nulls` are guaranteed to preserve row order?
  
I'm sure I've had other questions over time, these are just the ones I was thinking about this morning.
I guess you don't want to promise any of these details, because it would limit your freedom to change algorithms over time.
But if any of these things *are* guaranteed, it would be nice to see them in the docs.

**Comment by ritchie46** [comment]
> Does the converse hold? I.e., Series.has_validity() ==> Series.null_count() > 0?

No it doesn't. Regarding docs, I think we should only document guarantees as the list of non-guarantees is endless.

> Is Series.arg_max guaranteed to return the index of the first maximum value?

Currently it does, but I don't think we want to guarantee that with streaming and parallelism optimizations.

> Is a left join guaranteed to preserve the row order of the left DataFrame?

Yes.

EDIT: This was a guarantee under the then current implementation. It should not be a formal guarantee and can be subject to change.

> Are there circumstances in which functions like filter and drop_nulls are guaranteed to preserve row order?

They are guaranteed to preserve row order.

Could you make a PR, documenting those guarantees?

**Comment by s-banach** [comment]
Do these order guarantees also apply to `Expr.filter()` and Expr.drop_nulls()`?
(I don't precisely know how to word the guarantee in those cases, since they are much more general.)

**Comment by ritchie46** [comment]
> > I think we should only document guarantees as the list of non-guarantees is endless.
> 
> In general, I agree with you. However, I have seen someone on stackoverflow claiming that `has_validity()` is equivalent to `null_count() > 0`. In this specific case, could I add a disclaimer to avoid confusion?

That should be corrected on Stackoverflow
