### ISSUE TITLE
Add some way to retain indexing of list when exploding list column

### ISSUE THREAD

**Issue by TheWizier** [pola-rs/polars#10951]
### Problem description

I encountered this problem where I have a dataframe looking something like this:
```
>>> a = pl.DataFrame({"a":[1,1,1,1], "b":[[3,4,5], [3,4], [5,6], [5]]})
>>> a
shape: (4, 2)
┌─────┬───────────┐
│ a   ┆ b         │
│ --- ┆ ---       │
│ i64 ┆ list[i64] │
╞═════╪═══════════╡
│ 1   ┆ [3, 4, 5] │
│ 1   ┆ [3, 4]    │
│ 1   ┆ [5, 6]    │
│ 1   ┆ [5]       │
└─────┴───────────┘
```

Now the order of the items in this list was important so I wanted to explode b and add an index column but the best way I managed to find to do this was by doing:
```
a.with_row_count().explode("b").with_columns(
    pl.first().cumcount().over("row_nr").alias("list_idx")
).drop("row_nr")
```
One solution to this could be something along the lines of:
```
a.explode("b", with_index="list_idx")
```

**Comment by avimallu** [comment]
```py
(
    pl.DataFrame({
        "a": [1,1,1,1],
        "b": [[3,4,5], [3,4], [5,6], [5]]})
    .with_columns(
        pl.int_ranges(0, pl.col("b").list.lengths()))
    .explode("b", "int_range")
)
```

**Comment by stinodego** [comment]
> `a.explode("b", with_index="list_idx")`

I don't think it's worth adding such a parameter right now. The solution proposed by @avimallu is great, I'd suggest using that.
