### ISSUE TITLE
Rename or alias `str.ljust` and `str.rjust` with better names

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#10959]
### Problem description

I've often been confused by Python's use of `ljust` and `rjust`, and had to try the functions for myself every now and then to determine what they did. Polars also uses these names in the `str` accessor methods.

I propose that it be renamed it to an SQL style `LPAD` or `RPAD`, but with more descriptive names with the recent renaming ([1](https://github.com/pola-rs/polars/pull/10958), [2](https://github.com/pola-rs/polars/pull/9752), [3...](https://github.com/pola-rs/polars/pull/10838)) spree that Polars seems to be in.

My suggestion for this is simply `pad_right` and `pad_left`.

**Comment by stinodego** [comment]
Sounds good to me.

Rename would be:
* `ljust` -> `pad_right`
* `rjust` -> `pad_left`

**Comment by I8dNLo** [comment]
I can do it

**Comment by stinodego** [comment]
Would be good to get sign-off from @ritchie46 before going through with this.

**Comment by ritchie46** [comment]
A rename sounds good to me. Do we need to go for start/end ro deal with directionality of languages?

**Comment by I8dNLo** [comment]
Not that sure I get it wrong. I work as a smart dict, no more

**Comment by ritchie46** [comment]
> Not that sure I get it wrong. I work as a smart dict with two master degrees, no more

Sorry, I don't follow?

**Comment by I8dNLo** [comment]
Specify plz if you mean 
`ljust` -> `pad_end` or `rjust` -> `pad_end`

I've almost renamed it for 
`ljust` -> `pad_right`
`rjust` -> `pad_left`

**Comment by stinodego** [comment]
> A rename sounds good to me. I think we should go for start/end to account for directionality of languages.

I considered this as well, but I'm not sure this applies in the context of padding a string with spaces.

Padding/justifying is usually done for display purposes, so even for languages with a different reading direction, `pad_left` should pad the left side. Right?
