### ISSUE TITLE
Column Selection Based on Condition

### ISSUE THREAD

**Issue by chandlerliuliu** [pola-rs/polars#10967]
### Introduction
Big fan of Polars, especially on the expression syntax, it's just so easy and readable!
I think it's really nice to select columns based on regular expressions, datatypes, and even bitwise conditions on the column name level. I only gathered people who had similar needs here:
https://stackoverflow.com/questions/75446886/selecting-columns-based-on-a-condition-in-polars
edit: I just saw the closed issue related to: https://github.com/pola-rs/polars/issues/10870#issue-1878187969 (I don't know if having a separate method would be any different?)

However, it comes to times, when there are just too many columns when doing a data cleaning or transformation task, where I would need to select columns based on the condition of the data held by the Series.

There are many "workarounds" in such cases; however, it would be nice if it's nicely integrated into Polars `select` or a new select method like `select_where`.

### Scenario
Let me show this in a more specific context:
Let's say I am working on survey data where I'm dealing with multiple choice data, and I want to one hot encode these types of columns.

My current workarounds:
```
multichoice_cols = (
    df
    .select(
        col
        for col in df.select(pl.col(pl.Utf8)).columns
        if df.collect()[col].str.contains(", ").any()
        )
    .columns
)

(
    df
    .select(
        "Timestamp",
        *[pl.col(col).fill_null("not filled") for col in multichoice_cols],
    )
    # ... continue my chain here 
)
```

In Pandas, it's "easy" to just utilize the `.loc` method to select based on condition and I can just chain that from there:
```
(
    df
    .select_dtypes("object")
    .loc[:, lambda df: df.apply(lambda col: col.str.contains(", ").any()).to_list()]
)
```
But since Pandas is never easy it's a little too OO, as you see it's not very intuitive. I thought  `select_where` could be a nice addition to the Polars expression syntax methods or adjustment for `select `method

### Possible `select_where` method
I would say the function should **Select all columns where the given condition is True** on the Series level (Expr).

```
(
    df
    .select_where(pl.col(pl.Utf8).str.contains(", ").any())
)
```
It could act like the `filter` method where it only takes a **predicate** (Expression that evaluates to a boolean Series). So it could take a number of chained condition as the following:
```
(
    df
    .select_where(
        pl.col(pl.Utf8).str.contains(", ").any()
        .and_(cs.starts_with("address"))
    )
)
```
Potentially, it's also possible to just enhance the select method, but I felt like it's so much useful as a combination of selecting specific columns and doing a `with_columns` at the same time.

Do you think integrating such a new feature into Polars would be feasible and beneficial?

**Comment by orlp** [comment]
This goes against one of our core policies in Polars, namely that the schema/shape of the data never depends on the data itself. Without this many optimizations become impossible to do. So I don't think we want to support this as a built-in function and this use-case will always have to be a two-step process with a `collect` in between.


However I think this isn't as bad as you make it seem however, if you had written it a bit different.

```
import polars as pl
import polars.selectors as cs

has_comma = df.select(pl.col(pl.Utf8).str.contains(",").any())
comma_cols = [col for col in has_comma.columns if has_comma[col, 0]]
df.select("Timestamp", cs.by_name(comma_cols).fill_null("not filled"))...
```

This only involves one non-Polars native step, which is the extraction of `comma_cols`.

**Comment by chandlerliuliu** [comment]
I see, the motivation lies behind my original intuition coming from Pandas. It's really a small hiccup.
I thought to myself the usage of expr.any() if I cannot filter the column like I filter the rows.
So to obey the policy, the solution below is probably the most intuitive way I thought about "filtering columns".

```
(
    df
    .select(
        pl.col("Timestamp"),
        pl.col(
            df.select(pl.col(pl.Utf8).str.contains(", ").any())
            .melt()
            .filter("value")
            .collect()["variable"]
            .to_list()
        ),
    )
    .collect()
)
```

I guess what I'm trying to say is, these kinds of situations say a One-Hot encoded dataframe, where the data became the schema (I don't know if I can say that). Perhaps, maybe there could be another mechanism to treat columns as data as well. Maybe there should be a separate expression for columns separated from the series-wise data expression. Or this may also be the motivation behind the `pl.selectors` class. I don't have a lot of knowledge in terms of designing a query engine, but this is kind of from a DataFrame-user-interface perspective. I hope this makes sense.

**Comment by orlp** [comment]
@chandlerliuliu 

> Perhaps, maybe there could be another mechanism to treat columns as data as well.

We actively do not want that in Polars, in general. In fact I think it's a key difference between Polars and Pandas, in Polars the data is always columnar, whereas Pandas is very much flexible about your data representation/axes. Polars is much closer to relational algebra from SQL in that regard, albeit that our DataFrames are ordered tables rather than unordered multisets of relations.

**Comment by chandlerliuliu** [comment]
Thanks for the patience. I think this really helps me understand Polars and core design principles behind the scene.

**Comment by cmdlineluser** [comment]
Currently, there is [`pl.selectors.expand_selector()`](https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html#polars.selectors.expand_selector)
```python
lf = pl.LazyFrame({
    "Timestamp": [1, 2, 3, 4],
    "id": [5, 6, 7, 8],
    "a": ["", "foo", None, None],
    "b": ["a, b", None, None, None],
    "c": ["c, d", "e", "f", "g"]
})

cs.expand_selector(lf, cs.string().str.contains(", ").any())
# ('a', 'b', 'c')
```
```python
lf.select(cs.string().str.contains(", ").any()).collect()
# shape: (1, 3)
# ┌───────┬──────┬──────┐
# │ a     ┆ b    ┆ c    │
# │ ---   ┆ ---  ┆ ---  │
# │ bool  ┆ bool ┆ bool │
# ╞═══════╪══════╪══════╡
# │ false ┆ true ┆ true │
# └───────┴──────┴──────┘
```
Would it make sense for the "filter" type function that only returns `true` values to be added there?
```python
cs.filter(lf, cs.string().str.contains(', ').any())
# ('b', 'c')
```

**Comment by chandlerliuliu** [comment]
@cmdlineluser I think from what I gathered from @orlp. I don't think it's the matter of where such `filter` function goes. This feature or interface is against the Polars core principle, and it will mess with the query optimization.

However, now comes to think of it. I think just for the semantics, maybe these type of feature should be more or less a **syntactic sugar**. But honestly, it feels like a separate entity since it's kind of not what Polars stands for. If that's what you meant perhaps it does belong to the `pl.selector` class after all.

**Comment by orlp** [comment]
@cmdlineluser Your proposed `cs.filter` would create a lazy pipeline with a variable schema.

**Comment by alexander-beedie** [comment]
There are sufficient ways of doing this on the user-side, and I don't think we want this as a first-class part of the Polars API above, due to all the reasons listed so will close as "not planned".
