### ISSUE TITLE
Rename `take` to `gather`

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10972]
I'm not a huge fan of `take` as a name. We got it from pandas/numpy, but I don't think it's particularly clear, and in Rust `take` is already taken (hehe) by functions that remove some value from a data structure leaving the data structure empty/default, (e.g. `Option::take` or `std::mem::take`), making `take` doubly confusing.

Would there be interest in renaming it to `take_idx`, or (IMO) preferably `gather`? Tensorflow/PyTorch offer `gather` (with `take` mapping to it), and generally in high-performance computing this operation (grabbing data at a bunch of indices) is referred to as a gather (whereas storing to a bunch of indices is a scatter): https://en.wikipedia.org/wiki/Gather/scatter_(vector_addressing).

Would be interested to hear in what everyone else thinks.

**Comment by deanm0000** [comment]
What about get_list. Between get and take, I forget which returns a list and which returns a value. If take were renamed to get_list it would be obvious what the difference was and having the two methods have similar names would be reflected in that they do similar things.

**Comment by orlp** [comment]
@deanm0000 `take` does not produce a list, it produces a `Series`. That only becomes a list if nested within another `Series`. I think giving a similar name to `get` and `take` only further increases confusion.

`gather` is also more obvious than `take` in that regard in that it implies plurality, producing a Series. No one goes to 'gather' one thing.

**Comment by mcrumiller** [comment]
Doesn't [`item`](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.item.html) already do the same thing on Series? I think an `Expr.item()` would make a lot of sense here. You could have a separate `items` for the multiple-item case.

**Comment by deanm0000** [comment]
I'll concede your point about Series vs list but I don't share your intuition that no one gathers just one thing.  

I like @mcrumiller's suggestion of having item (renaming get) and items renaming take

**Comment by orlp** [comment]
I think `item` is a worse name than all of them to be honest in terms of descriptiveness.

**Comment by deanm0000** [comment]
If you can get rid of take and just have get do both things depending on the inputs then that's my favorite.

**Comment by orlp** [comment]
@deanm0000 I need to do some more thinking on whether that's possible, especially with regards to broadcasting behavior.

**Comment by deanm0000** [comment]
Yeah, to be honest, I figured it'd be a big under taking to combine them without breaking existing behavior. All things considered it's probably not worth it. While I do like the idea that it be renamed to get_list or get_series or get_mutli, or get_whatever, it isn't going to break my heart if you really like gather and go with that.

**Comment by erinov1** [comment]
How about `select_rows`? That is consistent with the DataFrame `row` method, which picks out a single row (as @mcrumiller pointed out, the analogue on Series is `item`, but I don't think that's as clear as `row`; neither is a verb). Btw this method should also be added to DataFrame? It currently has no `take` method.

**Comment by cjackal** [comment]
I also agree that `gather` is the de facto standard nomenclature in ML world, +1 on this renaming.

**Comment by ritchie46** [comment]
Given that `gather` and `scatter` is already a well defined in HPC, I am in favor of this. No need to reinvent the wheel. 

So we should rename `take` and `set_at_idx`.

**Comment by randolf-scholz** [comment]
> I also agree that `gather` is the de facto standard nomenclature in ML world, +1 on this renaming.

`.take` is used by the following frameworks:

- `torch.Tensor`
- `numpy.ndarray`
- `pandas.Series`
- `pandas.DataFrame`
- `pyarrow.Array`
- `pyarrow.Table`

and of course any framework that mirros numpy syntax (`jax`, `tensorflow.experimental.numpy`)
