### ISSUE TITLE
Categorical `Series.to_pandas()`

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#10977]
### Problem description

- `DataFrame.to_pandas()` can handle categorical, but `Series.to_pandas()` cannot.
- Pyarrow can send `dictionary(int64, utf8)` types to pandas, but not `dictionary(uint32, utf8)`.
- I guess `DataFrame.to_pandas()` is converting the dictionaries to int64 under the hood.
Hopefully some lines of code can be copy-pasted to `Series.to_pandas()`.

Sorry to bother you, but I'm also very curious what the future of Categorical interop is going to be.
I guess some things are going to change as a result of the dataframe interchange protocol?
Is there a reason we don't make an upstream request for pyarrow.to_pandas() to handle `uint` dictionaries?

**Comment by stinodego** [comment]
Minimal reproduction:

```python
import polars as pl

s = pl.Series("x", ["a", "b", "a"], dtype=pl.Categorical)
result = s.to_pandas()
# pyarrow.lib.ArrowTypeError: Converting unsigned dictionary indices to pandas not yet supported, index type: uint32
```
