### ISSUE TITLE
Allow quote parameter to be None in `write_csv`

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10992]
### Problem description

I'd like to generate a javascript data file in polars. When writing it out, I'd like polars NOT to quote anything, but currently the quote parameter has to be exactly 1 chars long - it cannot be None.

```
import polars as pl
data = ['// 2023.09.01.',
        'var mydata = [',
        '[11.407538,22.003241,51,,"L","T",,67',
        '[12.547899,21.033232,112,,"L","T",,139',
        '];']
df = pl.DataFrame(data, schema=['X'])
df.write_csv('myfile.js', has_header = False, quote = None)

```

**Comment by alexander-beedie** [comment]
Just added a new option that will cover this case.
Once it's merged and the new release is out, you'll able to set `quote_style = "never"`.

**Comment by stinodego** [comment]
You're using `write_csv` to write something that's not a CSV. That won't work.

For your example, you can do the following instead:

```
s = df.to_series()
with open("myfile.js", "w") as f:
    f.writelines(line + "\n" for line in s)
```
