### ISSUE TITLE
Sorting categorical values does not respect `inf` and `-inf`

### ISSUE THREAD

**Issue by matthias-Q** [pola-rs/polars#10990]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
df = pl.DataFrame({"values":np.random.rand(10)})
breaks = [0.2, 0.4, 0.6, 0.8]
df = df.with_columns(
    pl.col("values").cut(breaks).alias("values")
)

df.select("values").unique().sort(by="values")
```

This results in:
```
Out[51]: 
shape: (5, 1)
┌─────────────┐
│ values      │
│ ---         │
│ cat         │
╞═════════════╡
│ (0.6, 0.8]  │
│ (-inf, 0.2] │
│ (0.8, inf]  │
│ (0.2, 0.4]  │
│ (0.4, 0.6]  │
└─────────────┘
```

### Issue description

Categorical values can have interval edges with `-inf` and `inf`. When sorting them, they should be at the start/end, respectively.

### Expected behavior

The example from above should look like this:
```
┌─────────────┐
│ values      │
│ ---         │
│ cat         │
╞═════════════╡
│ (0.8, inf]  │
│ (0.6, 0.8]  │
│ (0.4, 0.6]  │
│ (0.2, 0.4]  │
│ (-inf, 0.2] │
└─────────────┘
```

### Installed versions

<details>
In [53]: pl.__version__
Out[53]: '0.19.2'
</details>

**Comment by matthias-Q** [comment]
Is it an issue of `cut()` or `sort()`? I mean sort tries to reorders categorical values and results is a wrong order.

**Comment by orlp** [comment]
@matthias-Q The issue is that `cut` generates categoricals that do not have the correct ordering. It generates them in the order it first encounters them rather than pre-generating them.

**Comment by matthias-Q** [comment]
Looks like `pl.Categorical` data types cannot be sorted:

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": ["(0.6, 0.8]", "(-inf, 0.2]", "(0.8, inf]", "(0.2, 0.4]", "(0.4, 0.6]"],
        "bar": ["xx", "1xx", "2xx", "aa", "2aa"],
        "baz": ["xx", "1xx", "2xx", "aa", "2aa"],
    },
    schema_overrides={"foo": pl.Categorical, "bar": pl.Categorical},
)

print(df.sort(by="foo"))
print(df.sort(by="bar"))
print(df.sort(by="baz"))
```

Output:
```
shape: (5, 3)
┌─────────────┬─────┬─────┐
│ foo         ┆ bar ┆ baz │
│ ---         ┆ --- ┆ --- │
│ cat         ┆ cat ┆ str │
╞═════════════╪═════╪═════╡
│ (0.6, 0.8]  ┆ xx  ┆ xx  │
│ (-inf, 0.2] ┆ 1xx ┆ 1xx │
│ (0.8, inf]  ┆ 2xx ┆ 2xx │
│ (0.2, 0.4]  ┆ aa  ┆ aa  │
│ (0.4, 0.6]  ┆ 2aa ┆ 2aa │
└─────────────┴─────┴─────┘
shape: (5, 3)
┌─────────────┬─────┬─────┐
│ foo         ┆ bar ┆ baz │
│ ---         ┆ --- ┆ --- │
│ cat         ┆ cat ┆ str │
╞═════════════╪═════╪═════╡
│ (0.6, 0.8]  ┆ xx  ┆ xx  │
│ (-inf, 0.2] ┆ 1xx ┆ 1xx │
│ (0.8, inf]  ┆ 2xx ┆ 2xx │
│ (0.2, 0.4]  ┆ aa  ┆ aa  │
│ (0.4, 0.6]  ┆ 2aa ┆ 2aa │
└─────────────┴─────┴─────┘
shape: (5, 3)
┌─────────────┬─────┬─────┐
│ foo         ┆ bar ┆ baz │
│ ---         ┆ --- ┆ --- │
│ cat         ┆ cat ┆ str │
╞═════════════╪═════╪═════╡
│ (-inf, 0.2] ┆ 1xx ┆ 1xx │
│ (0.4, 0.6]  ┆ 2aa ┆ 2aa │
│ (0.8, inf]  ┆ 2xx ┆ 2xx │
│ (0.2, 0.4]  ┆ aa  ┆ aa  │
│ (0.6, 0.8]  ┆ xx  ┆ xx  │
└─────────────┴─────┴─────┘
```

so, I agree that it would be nice if `cut` would return it sorted, but generally, categorical values cannot be sorted at the moment.

**Comment by orlp** [comment]
@matthias-Q They can be sorted, they're just sorted by something else than you're used to. See https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.cat.set_ordering.html.

Internally categoricals are just stored as integers, with those integers mapping to a dictionary of strings. This dictionary is built up string by string the first time each such string is encountered. The default is not to order by the string values, but rather by the internal integer values, as this is much, much faster.

**Comment by matthias-Q** [comment]
Ok, then this is not a bug. I understand that the default is the faster ordering, but it feels weird anyways.

**Comment by stinodego** [comment]
We are working on improving the Categorical type, stay tuned for a (hopefully) better user experience 😸
