### ISSUE TITLE
Rename `group_by` to `group`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10993]
### Problem description

Please don't roast me for this, I'm just trying to improve the library. :)
The recent renaming of 'groupby' to 'group_by' got me thinking about the 'by' in polars methods names. I think it would be better to move it to the arguments.

## Reasoning

Method names should idealy convey concise actions.

Imagine wanting to sort a DataFrame by a column.
The action you want to perform is **'sort'** (not 'sort by').
The column is a detail of the action, not the action itself.

Also a lot a people these days want to be very presice/specifc in their code and explicitly state argument names or use  inlay hints.

Please have a look at the following comparsion:
![image](https://github.com/pola-rs/polars/assets/25177421/5212d441-e0b6-460f-afd2-401a53bdf5ab)

IMO the `sort(by='col')` version is more readable and concise.
It immediately conveys the action of **sort** with the detail of **by** as an argument.

The `group_by(by='col')` on the other hand is a bit harder to read and has redundancy in the name.

**Comment by cmdlineluser** [comment]
Just to clarify, is this suggesting rename `.group_by()` to `.group()`?

**Comment by JulianCologne** [comment]
exactly!
As you can see in the screenshot `sort` and `group_by` have the same general structure but `sort` is much cleaner if you ask me.

Looking at the bigger picture it would be cool and consistent to also rename (all) other `*by*` methods like `partition_by`, `offset_by` ...
Minimal effort to get consistency would be to rename `sort` to `sort_by` but as I tried to argument moving the `by` keyword in the arguments presents a better api

**Comment by orlp** [comment]
If anything, it is `DataFrame.sort` that should be renamed to `sort_by`, since it matches `Expr.sort_by` and not `Expr.sort`.

**Comment by stinodego** [comment]
Thanks for the suggestion, but this one is not happening.

Parameter names are important, but function names are more important.

As established in the recent topic on renaming to `group_by`, this is an established operation and we want to adhere to the standard naming here.

I suggest using positional syntax in the arguments section as we may (possibly, don't quote me on this) even remove the option to specify `by=` in the future, just like we already have for `select` and `with_columns`. E.g.:

```python
df.group_by("a", "b")
df.sort("a", descending=True)
```
