### ISSUE TITLE
`ColumnNotFoundError` if columns order changes after scan

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11006]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

pl.DataFrame({'a' : ['1'], 'b' : ['1']}).write_parquet('tmp.parquet')
df = pl.scan_parquet('tmp.parquet')
pl.DataFrame({'b' : ['2'], 'a' : ['2']}).write_parquet('tmp.parquet')
df.select('a').collect()

```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/home/robin_ga/.local/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/local/home/robin_ga/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: a
```

### Issue description

Question: Should it be allowed the rewrite the file between the scan and the collect. Maybe yes, but the user should make sure the schema didn't change.

Here the schema is the same, but the order of the column changed, could it be managed by polars ?

### Expected behavior

Either no error, or at least a better error message, `exceptions.ColumnNotFoundError: a` is wrong, as the column `a` exists. 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          <not installed>
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
sqlalchemy:          2.0.1
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
I would rather support putting an OS-level file lock on the parquet file while we're reading it to prevent writes rather than the can of worms opened by supporting the one billion ways a file can be modified by others while you are reading it.

**Comment by gab23r** [comment]
I understand, I use this as a feature quite a lot and I have to admit that its super powerful, it uses the power of the lazyness to its maximum !

**Comment by stinodego** [comment]
Thanks for filing the bug report. This is not something we want to fix. Rather, as @orlp mentions, we want to make sure this is prohibited completely. Then you will get a more informative error message.
