### ISSUE TITLE
polars.Series.series_equal with strict=True considers Int64 and Float64 series equal

### ISSUE THREAD

**Issue by severinh** [pola-rs/polars#11001]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)
# Returns True, but expected it to return False
```

### Log output

```shell
No log output
```

### Issue description

The Polars documentation for `Series.series_equal` ([link](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.series_equal.html#polars.Series.series_equal)) says the following: If `strict=True` then `Don’t allow different numerical dtypes, e.g. comparing pl.UInt32 with a pl.Int64 will return False`.

However, `pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)` returns `True`, even though the two series have different numerical dtypes (`Int64` and `Float64`).

### Expected behavior

Either
1. change the implementation so that `pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)` returns `False`, or 
2. update the documentation to clarify why Polars returns `True` in this case.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.1
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.0
pydantic:            2.2.1
sqlalchemy:          2.0.16
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for raising the Issue!
I think I can see what's going on here...🤔

**Comment by severinh** [comment]
Wow, I did not expect the Polars team to react so quickly to my minor bug report. Thanks a lot!

Overall, Polars and the team behind it continue to amaze me. It's such a joy to build software with it, and I always look forward to the slew of improvements in each new release.
