### ISSUE TITLE
Type recognition is incorrect when Series data is lists of float and int

### ISSUE THREAD

**Issue by balakhaniyan** [pola-rs/polars#11009]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series([[1], [2.5], [3.25]]).dtype
```

### Issue description

I ran this code snippet, but got `List(Int64)` as result and when I changed 1 to 1., it became correct
Maybe it just checks first element

### Expected behavior

Result of dtype must be `List(Float64)`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by xuJ14** [comment]
I have a similar question. When I want to do `pl.concat`, like:

```python
df1 = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [4, 5, 6],
    }
)
df2 = pl.DataFrame(
    {
        "a": [1.0, 2.0, 3.0],
        "b": ["4", "5", "6"],
    }
)
```

Since the dtype are not the same for column a, I know that this can not be concated. And I also know that this can be solved like: 
```python
print(
    df2.with_columns(
        [pl.col(n).cast(t) for n, t in df1.schema.items()]
    )
)
```
But this only works if I know the schema of df1 is right. Thus, I wonder if there are some methods to deal with the problem when I do not know which schema is right, i.e. to automatically deal with the dtype conflict. Or at least for `int8` to 'int16' to `float8` to `float16` etc.

**Comment by cmdlineluser** [comment]
@xuJ14 Perhaps you're looking for `how="vertical_relaxed"` - https://stackoverflow.com/a/76898962/19355181

**Comment by xuJ14** [comment]
> @xuJ14 Perhaps you're looking for `how="vertical_relaxed"` - https://stackoverflow.com/a/76898962/

It can not combine with `how="diagonal"`, i.e. the number and order of the columns are not the same. (What a terrible vendor)

**Comment by orlp** [comment]
We should definitely not silently truncate floats to integers.

**Comment by Wainberg** [comment]
This issue has also been reported here: https://github.com/pola-rs/polars/issues/9500.

**Comment by Wainberg** [comment]
Here's a related issue: https://github.com/pola-rs/polars/issues/10601

**Comment by stinodego** [comment]
Closing in favor of #11156
