### ISSUE TITLE
Segfault reading invalid CSV

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#11019]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Create a CSV called `temp_test.csv` (which is intentionally created to mimic a failed file transfer partway through the transfer):
```csv
"WellCompletionCWI","FacilityID","ProductionMonth","ReportedHoursProdInj","ProdAccountingProductType","ReportedVolume","VolumetricActivityType"
"SK0000608V001","SK BT B1H3780","202001","","GAS","1.700","PROD"
"SK0127960V000","SK BT 0018977","202001","","GAS","45.500","PROD"
"SK0127960V000","SK BT 0018977","
```

```python
df = pl.read_csv(
  'temp_test.csv',
  infer_schema_length=10_000_000_000_000,
  dtypes={'ProductionMonth': pl.Utf8, 'ReportedHoursProdInj': pl.Int16, 'ReportedVolume': pl.Float64},
)
```

### Issue description

Even though the CSV file is invalid (due to a failed file transfer), it should not cause Polars to outright crash. Instead, an error message should be displayed or similar. 

As it is, this may even represent a security vulnerability if it's possible to craft a CSV file that causes it to crash in a certain way.

### Expected behavior

Some sort of error should occur, in the same way that pandas throws an error on this same test file.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-6.1.0-1021-oem-x86_64-with-glibc2.35
Python:              3.9.18 (main, Aug 25 2023, 13:20:14) 
[GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              2023.9.0
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by cmdlineluser** [comment]
It also appears to raise an exception without the `dtypes`:
```python
pl.read_csv(b"""
"WellCompletionCWI","FacilityID","ProductionMonth","ReportedHoursProdInj","ProdAccountingProductType","ReportedVolume","VolumetricActivityType"
"SK0000608V001","SK BT B1H3780","202001","","GAS","1.700","PROD"
"SK0127960V000","SK BT 0018977","202001","","GAS","45.500","PROD"
"SK0127960V000","SK BT 0018977","
""".strip()
)
# thread '<unnamed>' panicked at /Users/user/git/polars/crates/polars-io/src/csv/buffer.rs:87:23:
# slice index starts at 1 but ends at 0
# PanicException: slice index starts at 1 but ends at 0
```
Probably the same underlying issue, but may be useful for debugging.

**Comment by DeflateAwning** [comment]
Thanks for the way shorter repro! Sorry I had a bit extra in there earlier

**Comment by reswqa** [comment]
I believe the culprit lies in the single quotation mark at the end of the last line.  This led Polars to infer that it should be wrapped in double quotes, but in fact, it did not.

**Comment by mrogowski11** [comment]
The cause of the problem is here:
https://github.com/pola-rs/polars/blob/d7411e0160a9e38b10ba26843590efa9b4067792/crates/polars-io/src/csv/utils.rs#L664
or if you want to look at it from the other side:
https://github.com/pola-rs/polars/blob/d7411e0160a9e38b10ba26843590efa9b4067792/crates/polars-io/src/csv/buffer.rs#L203-L206
[escape_field's contract](https://github.com/pola-rs/polars/blob/d7411e0160a9e38b10ba26843590efa9b4067792/crates/polars-io/src/csv/utils.rs#L657-L659) specifies that _bytes_ has to end with a quote character but it does not require for it to have a a minimum length of 2.  And so it tries to index "1..0".

<br/>A potential solution to address this issue can be implemented in the [caller's code](https://github.com/pola-rs/polars/blob/d7411e0160a9e38b10ba26843590efa9b4067792/crates/polars-io/src/csv/buffer.rs#L203-L206), by introducing a simple check like the following:
```
let bytes_len = bytes.len();
if bytes_len == 1 || bytes[bytes_len -1] != self.quote_char {
    polars_bail!(ComputeError: "invalid utf-8 sequence");
}
```

<br/>With this change, the application will panic with a more descriptive error message:
```
Traceback (most recent call last):
  File "/a/polars/py-polars/csv.py", line 3, in <module>
    a = pl.read_csv(b"""
        ^^^^^^^^^^^^^^^^
  File "/a/polars/py-polars/polars/io/csv/functions.py", line 364, in read_csv
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/a/polars/py-polars/polars/dataframe/frame.py", line 768, in _read_csv
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: Could not parse `"` as dtype `str` at column 'ProductionMonth' (column number 3).
The current offset in the file is 307 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `"` to the `null_values` list.
```
