### ISSUE TITLE
pl.read_database() is multiplying my float column by 10^12

### ISSUE THREAD

**Issue by aleewen** [pola-rs/polars#11017]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```

### Issue description

I'm having an issue where pl.read_database() is returning a table, but multiplying my float column by 10^12.
pd.read_sql() works just fine. I am using a SQL Alchemy engine and haven't tried the others. The data type in the SQL Server it's pulling from is [decimal](28, 12)

### Expected behavior

The value should be returned as a float, not multiplied by 10^12.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by stinodego** [comment]
I would expect https://github.com/pola-rs/polars/pull/10776 may have fixed this. Are you on the latest version?

If so, can you try to create a reproducible example?

**Comment by stinodego** [comment]
I'll close this issue for now. If you're still having this issue after installing version `0.19.3`, please open a new bug report and include a reproducible example. We'll take a look.
