### ISSUE TITLE
Can return incorrect results from selector combination with `|`

### ISSUE THREAD

**Issue by antoniocali** [pola-rs/polars#11021]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import date, datetime

df = pl.DataFrame(
    {
        "id": [9, 4, 2],
        "place": ["Mars", "Earth", "Saturn"],
        "date": pl.date_range(date(2022, 1, 1), date(2022, 1, 3), "1d", eager=True),
        "sales": [33.4, 2142134.1, 44.7],
        "has_people": [False, True, False],
        "logged_at": pl.datetime_range(
            datetime(2022, 12, 1), datetime(2022, 12, 1, 0, 0, 2), "1s", eager=True
        ),
    }
).with_row_count("rn")

import polars.selectors as cs
out = df.select(cs.by_name("rn") | ~cs.numeric())
print(out)

```

### Log output

```shell
shape: (3, 4)
┌────────┬────────────┬────────────┬─────────────────────┐
│ place  ┆ date       ┆ has_people ┆ logged_at           │
│ ---    ┆ ---        ┆ ---        ┆ ---                 │
│ str    ┆ date       ┆ bool       ┆ datetime[μs]        │
╞════════╪════════════╪════════════╪═════════════════════╡
│ Mars   ┆ 2022-01-01 ┆ false      ┆ 2022-12-01 00:00:00 │
│ Earth  ┆ 2022-01-02 ┆ true       ┆ 2022-12-01 00:00:01 │
│ Saturn ┆ 2022-01-03 ┆ false      ┆ 2022-12-01 00:00:02 │
└────────┴────────────┴────────────┴────────────
```

### Issue description

Just followed documentation on polars book I encountered this example.

It seems to me something is wrong on selection output because `rn` column is missing

### Expected behavior

`rn` column should be present 

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by reswqa** [comment]
I feel that `rn` should indeed be selected as you expected. `|` should include all selected columns by `lhs` and `rhs` (after deduplication). But considering that this is an example presented in the `polars-book`, I'm not sure if it is by design.  🤔 

@alexander-beedie, what do you think about this? If this is a valid issue, I am willing to submit a PR.

**Comment by alexander-beedie** [comment]
> @alexander-beedie, what do you think about this? If this is a valid issue, I am willing to submit a PR.

On the face of it I think it looks like a valid issue, but I won't be able to confirm until tomorrow evening (travelling today, not back until later on Sunday ;))

**Comment by reswqa** [comment]
Thanks for the quick reply, enjoy your time. ^^

**Comment by antoniocali** [comment]
I also open the issue on the Polars book repo and author confirmed that when he wrote the example he expected the output with rn.

 https://github.com/pola-rs/polars-book/issues/398#issuecomment-1710752527

**Comment by reswqa** [comment]
I guess this is caused by #9240. I keep the pull request as draft before we confirm this is a valid issue. :)

**Comment by alexander-beedie** [comment]
> Thanks for the quick reply, enjoy your time. ^^ 

Ok, got back a little later than expected; took look at this and constructed a few similar tests and can confirm that this is definitely a real Issue - if you've got a fix in mind, please go ahead!  ;)

**Comment by antoniocali** [comment]
I do have a question regarding the change @reswqa 
Beat with me because I don't know Rust, and I don't know neither the codebase of polars.

I've just checked your changes for this particular issue

https://github.com/pola-rs/polars/pull/11026/files#diff-4fb16e96dc159a6f0c26e28c3f06d271467b6f8b30ae3c70c7ea534971ac3897

```rust
Selector::Add(lhs, rhs) => {
            replace_selector_inner(*lhs, members, scratch, schema, keys)?;
            replace_selector_inner(*rhs, members, scratch, schema, keys)?;
            let mut rhs_members: PlIndexSet<Expr> = Default::default();
            replace_selector_inner(*rhs, &mut rhs_members, scratch, schema, keys)?;
            members.extend(rhs_members)
        }
```

Is there a reason why `lhs` parameter is now unused?
