### ISSUE TITLE
Can't select column named '*' - should such a name be disallowed?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11022]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [27]: df = pl.DataFrame({'*': [1,2,3], 'a': [4,5,6]})

In [28]: df.select('*')
Out[28]:
shape: (3, 2)
┌─────┬─────┐
│ *   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

In [29]: df.select('a')
Out[29]:
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 4   │
│ 5   │
│ 6   │
└─────┘
```

### Issue description

If there's no way of selecting a column named '*', should that be disallowed as a column name?

### Expected behavior

Probably that an error be raised, saying that '*' is a protected column name?

### Installed versions

<details>

```

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.3
numpy            : 1.25.1
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.1.2
Cython           : None
pytest           : 7.3.1
hypothesis       : 6.82.4
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : 2023.7.0
fsspec           : 2023.6.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.0
snappy           : None
sqlalchemy       : 2.0.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
None

```

</details>

**Comment by balakhaniyan** [comment]
* in polars.select is like SQL* and returns all columns regardless column names. so it is better to change your column name to index or something similar

**Comment by stinodego** [comment]
> If there's no way of selecting a column named '*'

That's not exactly true. I can do the following:
* `df["*"]`
* `df[:,0]`
* `df.get_column("*")`
* `df.drop("*")  # drop the column named *`

So there are plenty of ways to interact with a column named `*`. But indeed, there are some cases where we interpret the `*` as "all columns". 

I don't think disallowing the column name `*` is a good move. It's a pretty niche situation, and in that situation, some people may want to have their column named `*`.

**Comment by MarcoGorelli** [comment]
> I think that wildcard syntax helps more people than the people who are helped by disallowing * columns.

yup, agreed - closing then, thanks
