### ISSUE TITLE
Low visibility for previously visited links in dark mode

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#11029]
### Problem description

The current dark mode color scheme for Doc's website makes previously visited/highlighted links a bit hard to read.

<img width="392" alt="CS-RSjlHrko@2x" src="https://github.com/pola-rs/polars/assets/33796896/773526e9-d514-4d7d-b758-ebc529ea6d7a">

![CS-bCPL5Xez@2x](https://github.com/pola-rs/polars/assets/33796896/d3ea6c50-9816-4902-ba91-4c0048846022)

**Comment by stinodego** [comment]
We could change this in the CSS, but what color would be better?

**Comment by cjackal** [comment]
I personally like no visual highlight for previously visited links, which many other pydata projects (pandas, ...) are adopting.

**Comment by stevenlis** [comment]
@stinodego Indeed, I can't remember the last time I saw a web document with visited links highlighted. Even the PyData Sphinx Theme [website](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html#) doesn't have that feature. Is there a way to disable this, like @cjackal suggested?

It seems that Polars doesn't define a [color](https://github.com/pola-rs/polars/blob/5b14a76e03eaf12629e98378d7aa9b03ab3e99d2/py-polars/docs/source/_static/css/custom.css) just like many other documentation websites I saw. However, I'm not sure why Polars is the only one that has visited links highlighting. I'm not familiar with CSS, but it seems like pandas has this:
```
a:visited:not(.btn):not(.dropdown-item):not(.nav-link) {
text-decoration: none;
}
```
https://github.com/pandas-dev/pandas/blob/723feb984e6516e3e1798d3c4440c844b12ea18f/web/pandas/static/css/pandas.css

**Comment by stinodego** [comment]
We didn't have the highlighting until recently 🤔 not sure what changed exactly.

**Comment by stinodego** [comment]
@stevenlis The CSS snippet you posted doesn't seem to fix it.

If anyone finds a way to fix this, a PR is welcome.

**Comment by stevenlis** [comment]
For some reason, this issue occurs in Chrome-based browsers, Safari, but Firefox does not highlight at all.
