### ISSUE TITLE
Column level lineage

### ISSUE THREAD

**Issue by Haeri** [pola-rs/polars#11031]
### Problem description

Dear polars team,

It would be very useful to introduce a feature that allows tracing back columns within dataframes and exposing their composition in the Polars library. Such functionality would have a significant impact on data governance and pipeline validation.

On the user side, implementing such a feature is challenging due to the unpredictability of transformations. However, within the library itself, capturing the inputs used to generate new outputs should be a straightforward process.

For the implementation, my naive suggestion would be to introduce an UUID list per column and inherit those IDs for every transformation that takes place.

For example:

DF_A:
- id: [UUID_1]
- name: [UUID_2]
- last_name: [UUID_3]

now concatenating name and last_name and creating full name could give

DF_B:
- id: [UUID_1]
- name: [UUID_2]
- last_name: [UUID_3]
- full_name: [UUID_2, UUID_3]

Therefore, we would know from which columns full_name was constructed without looking into the code.

Best regards,
Haeri

**Comment by stinodego** [comment]
Indeed, as Marco showed, you can do this with the `meta` namespace.

If this does not address your needs, please re-open this and be more specific on exactly the functionality you're looking for.

**Comment by Haeri** [comment]
Thanks for the quick response!

The meta suggestion seems to be very close to what I need but unfortunately, I was not able to get it fully working. As it seems meta is only available on an expression rather than a dataframe. Is it possible to extract meta also for a dataframe?

Here is my expected code:

```python
import polars as pl

df = pl.DataFrame({
    'id': [1, 2, 3],
    'name': ['peter', 'andreas', 'alex'],
    'last_name': ['parker', 'ânderson', 'kordz'],
})

concat_df = df.with_columns(
    pl.concat_str(
        [
            pl.col("name"),
            pl.col("last_name"),
        ],
        separator=" ",
    ).alias("full_name"),
)

print(concat_df["full_name"].meta.root_names()) # AttributeError: 'Series' object has no attribute 'meta'
```

**Comment by cmdlineluser** [comment]
I think your updated example warrants re-opening this as @stinodego suggested.

> If this does not address your needs, please re-open this and be more specific on the exact functionality you're looking for.

**Comment by Haeri** [comment]
Unfortunately, I am unable to re-open my own issue, since it was closed by a repo collaborator.

**Comment by cmdlineluser** [comment]
@ldacey There is [`meta.write_json()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.meta.write_json.html#polars.Expr.meta.write_json) (just using `json.loads` here to "pretty print" the result)
```python
json.loads(
    pl.concat_str(
       [
          pl.col("name"),
          pl.col("last_name"),
       ],
       separator=" ",
    ).alias("full_name").meta.write_json()
)
```
```python
{'Alias': [{'Function': {'input': [{'Column': 'name'},
     {'Column': 'last_name'}],
    'function': {'StringExpr': {'ConcatHorizontal': ' '}},
    'options': {'collect_groups': 'ApplyFlat',
     'fmt_str': '',
     'input_wildcard_expansion': True,
     'auto_explode': True,
     'cast_to_supertypes': False,
     'allow_rename': False,
     'pass_name_to_apply': False,
     'changes_length': False,
     'check_lengths': True,
     'allow_group_aware': True}}},
  'full_name']}
```

**Comment by Haeri** [comment]
Any chance for this to be considered in the future?

**Comment by phitoduck** [comment]
Would internal lineage tracing make polars a candidate to become a ["producer" in the OpenLineage project](https://openlineage.io/ecosystem)? 

I *think* that would potentially mean that you could get column-level lineage from polars transformations into lineage-tracing UI's such as AWS DataZone.

![Image](https://github.com/user-attachments/assets/b63609c7-770f-4e4e-8c50-e2b2126d1740)

**Comment by afeldman1** [comment]
Is column-level lineage on the roadmap for polars?

**Comment by Noghpu** [comment]
I think it was planned to be added to polars cloud, so probably not going to end up in core
