### ISSUE TITLE
Add join validation on `multiple keys`

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#11046]
### Description

Currently it's not possible to do join validation on multiple keys. Would be nice to have so I can avoid creating surrogate keys.
```python
df.join(
        df_2,
        on=["id","revision"],
        suffix="_default",
        validate="m:1",
    )
```

**Comment by mkleinbort-ic** [comment]
Duplicate of https://github.com/pola-rs/polars/issues/10784.

**Comment by ion-elgreco** [comment]
Will close this one then! @mkleinbort-ic
