### ISSUE TITLE
Incorrect `DataFrame` schema produced in some situations when given empty `List` dtype data

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#11044]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Can reproduce from Python like so:
```python
import polars as pl
from polars.polars import PyDataFrame

pydf = PyDataFrame.from_dicts(
    [{"a":0, "b":None}],
    None,
    {'a':pl.Int64,'b':pl.List(pl.Int64)},
)
print( pydf.dtypes() )
# [Int64, List(Null)]   << inner List dtype became Null
```
Note: using `PyDataFrame` directly here to avoid going through the `_post_apply_columns` function that otherwise hides the error by casting it back to the correct dtype.

### Log output

Traced the issue as far as `Series` creation from `AnyValueBuffer` in the Rust-side `from_rows_iter_and_schema` function [[here](https://github.com/pola-rs/polars/blob/8d5de9531fd6cedcc34370be77941a77885d555f/crates/polars-core/src/frame/row/dataframe.rs#L71)], but haven't found how best to fix it... 

Output from local `dbg!` statements while investigating:

```shell
[.../row/dataframe.rs:76] s.is_empty() = false
[.../row/dataframe.rs:83] s.dtype() = List(Null)
[.../row/dataframe.rs:83] schema.get_at_index(1) = Some(("b",List(Int64)))
```
^^ Can see that `schema` is correct at this point, but `Series` drops the inner `List` dtype on conversion from buffer.

### Issue description

Edge-case that can result in the creation of DataFrames with an incorrect schema. 

### Expected behavior

The DataFrame should have the correct schema, not lose the inner `List` dtype.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
----Optional dependencies----
adbc_driver_sqlite:  0.6.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.2
fsspec:              2023.9.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            2.3.0
sqlalchemy:          2.0.20
xlsx2csv:            0.8.1
xlsxwriter:          3.1.3```

</details>

**Comment by reswqa** [comment]
Maybe we need a special branch for `any_values_to_list` if `avs` is empty. 🤔

**Comment by alexander-beedie** [comment]
(Was accidentally closed by the choice of wording in #11047; reopening ;)

**Comment by theelderbeever** [comment]
I am still seeing this error in `polars v1.1.0` and am not sure what the workaround is.

**Comment by stucash** [comment]
It might have got even more complicated; I was in a process of replacing `pandas` completely in my code base (production), the data I retrieved from a data server was raw list of dictionaries of float64 and int64, however polars complained that int64 incompatible with schema which has a float64 for that particular column. 

I've then manually saved those data down and `pl.read_csv` into memory and did a `pl.concat` by hand and it went through. It is likely when I saved it down and read it back, the `dtype` has changed. It is then very hard to reproduce the error.

**Comment by alexander-beedie** [comment]
> I am still seeing this error in `polars v1.2.1` and am not sure what the workaround is.

FYI: this was fixed at some point, though I'm not sure by which PR; however, can confirm that we now see the correct inner dtype ✌️
```python
print( pydf.dtypes() )
# [Int64, List(Int64)]
```
