### ISSUE TITLE
Add Support for "associated joins" that are only executed if required

### ISSUE THREAD

**Issue by drgif** [pola-rs/polars#11049]
### Description

I want to propose a feature to lazily execute joins only if fields from the right side of the join are required. Consider a join like this:

`lf = headers.join(items).join(additional_item_info)`

In our use case we create models that are shared between hundreds of customers. Each customer needs slightly different fields from the resulting LazyFrame. When a customer doesn't need fields from `additional_item_info`, I do not want to execute that join because it is extremely expensive to get the data.

I propose to add an `associate` option to `.join()` (defaulting to `false` and possibly limited to left joins). When `associate` is true:
- if projection requires no fields from the right side AND there is no higher level filter on fields from the right side -> drop the join entirely
- in all other cases, leave the join as is

To clarify:
- `headers.join(items).join(additional_item_info.filter('add_field1' = 0)).select('header1', 'item1')` should drop the join
- `headers.join(items).join(additional_item_info).filter('add_field1' = 0).select('header1', 'item1')` should leave the join as is

I am aware that this influences the resulting dataframe's cardinality, that's why it should be implemented as an option

**Comment by orlp** [comment]
I don't think this should be an option at all. This should be an optimization automatically applied.

**Comment by drgif** [comment]
Hm, are you sure? I would be a fan of automatic application, but it changes result cardinality in most cases which is different than what you would expect from the equivalent SQL query. Consider this example:

```python
lf1 = pl.LazyFrame({"a": [1]})
lf2 = pl.LazyFrame({"a": [1, 1], "b": [2, 3]})

result = lf1.join(lf2, on="a", how="left").select("a")
```

This would normally yield duplicate rows:
```python
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
└─────┘
```

With the "association optimization" it would yield:
```python
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

**Comment by orlp** [comment]
@drgif Could you give an example query with like 5-10 rows and 3-4 columns that would show what you want? Because right now it seems to me what you want is just a semi-join:

```rust
lf1 = pl.LazyFrame({"a": [1]})
lf2 = pl.LazyFrame({"a": [1, 1], "b": [2, 3]})

result = lf1.join(lf2, on="a", how="semi").select("a").collect()
```

```
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

**Comment by drgif** [comment]
Sorry, I will try to be more clear. Consider these lazyframes:

```python
lf1:
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
│ a1  │
│ a2  │
└─────┘
lf2:
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ a1  ┆ b1  │
│ a2  ┆ b2  │
└─────┴─────┘
lf3:
shape: (4, 2)
┌─────┬─────┐
│ b   ┆ c   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ b1  ┆ c1  │
│ b1  ┆ c2  │
│ b2  ┆ c3  │
│ b2  ┆ c4  │
└─────┴─────┘
```

Consider this "associated join":
```python
joined = (
    lf1
    .join(lf2, on="a", how="left", associate=True)
    .join(lf3, on="b", how="left", associate=True)
)
```

=============================

`joined.select("a").collect()`: execute no join, only get data from `lf1`
```
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
│ a1  │
│ a2  │
└─────┘
```

`joined.select(["a", "b"]).collect()`: Only join `lf1` and `lf2`
```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ a1  ┆ b1  │
│ a2  ┆ b2  │
└─────┴─────┘
```

`joined.select(["a", "b", "c"]).collect()`: Join all three dataframes
```
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
│ a1  ┆ b1  ┆ c1  │
│ a1  ┆ b1  ┆ c2  │
│ a2  ┆ b2  ┆ c3  │
│ a2  ┆ b2  ┆ c4  │
└─────┴─────┴─────┘
```

`joined.select(["a", "c"]).select()`: Still join all three dataframes because we require column `b` from `lf2` to get to column `c` from `lf3`
```
shape: (4, 2)
┌─────┬─────┐
│ a   ┆ c   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ a1  ┆ c1  │
│ a1  ┆ c2  │
│ a2  ┆ c3  │
│ a2  ┆ c4  │
└─────┴─────┘
```

It's a "join on demand", depending on the requested fields. It's for reusability of complex models in simpler scenarios

**Comment by orlp** [comment]
I don't think we should introduce operators that fundamentally have different behavior based on what comes later. That's a nightmare for optimization.

So if there is no change of behavior, then this could and should be done automatically. If there *is* a change of behavior of the operator based on which selects come afterwards like your earlier example I don't think we should add it.

**Comment by drgif** [comment]
I totally understand your concern. I would implement it as an extended projection pushdown but yes, it goes beyond optimization. 

I will instead try to create a pyo3 extension that implements this and share it here
