### ISSUE TITLE
Cast `dtype` to `LargeList(dtype)` not working in `str.json_extract`

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#11053]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import json
import polars as pl
test_data = [{
    "col1": ['12345'],
    'col2': '12345',
    
}]

schema = pl.Struct( {
            "col1": pl.List(pl.Utf8),
            "col2": pl.List(pl.Utf8),
            })

df = pl.DataFrame(data= [json.dumps(item) for item in test_data])

df = df.with_columns(
    pl.col("column_0")
    .str.json_extract(schema)
    .alias("casted_json")).unnest('casted_json')

print(df)
┌───────────────────────────────────┬───────────┬───────────┐
│ column_0                          ┆ col1      ┆ col2      │
│ ---                               ┆ ---       ┆ ---       │
│ str                               ┆ list[str] ┆ list[str] │
╞═══════════════════════════════════╪═══════════╪═══════════╡
│ {"col1": ["12345"], "col2": "123… ┆ ["12345"] ┆ null      │
└───────────────────────────────────┴───────────┴───────────┘
```

### Issue description

Parsing a Json with a schema does not seem to work properly. The `Utf8 `is casted to `pl.List(utf8)` but the value is silently dropped.

### Expected behavior

Properly cast the strings to list(strings) so you get this:

```python
shape: (1, 3)
┌───────────────────────────────────┬───────────┬───────────┐
│ column_0                          ┆ col1      ┆ col2      │
│ ---                               ┆ ---       ┆ ---       │
│ str                               ┆ list[str] ┆ list[str] │
╞═══════════════════════════════════╪═══════════╪═══════════╡
│ {"col1": ["12345"], "col2": "123… ┆ ["12345"] ┆ ["12345"] │
└───────────────────────────────────┴───────────┴───────────┘
```

### Installed versions

Build from latest dev branch.

**Comment by ion-elgreco** [comment]
@reswqa 😄

**Comment by reswqa** [comment]
The default behavior of arrow2 cast non-nested type to list is per-value(`u8` characters for `Utf8Type`) per-list.
That's to say:

```python
s = pl.Series("col2", "12345",dtype=pl.Utf8)
res = s.cast(pl.List(pl.Utf8))
```

You will get 
```python
Series: 'col2' [list[str]]
[
	["1"]
	["2"]
	["3"]
	["4"]
	["5"]
]
```
instead of 
```python
Series: 'col2' [list[str]]
[
	["12345"]
]
```

As for the null result you got, I will take a closer look.

**Comment by ion-elgreco** [comment]
> The default behavior of arrow2 cast non-nested type to list is per-value(`u8` characters for `Utf8Type`) per-list. That's to say:
> 
> ```python
> s = pl.Series("col2", "12345",dtype=pl.Utf8)
> res = s.cast(pl.List(pl.Utf8))
> ```
> 
> You will get
> 
> ```python
> Series: 'col2' [list[str]]
> [
> 	["1"]
> 	["2"]
> 	["3"]
> 	["4"]
> 	["5"]
> ]
> ```
> 
> instead of
> 
> ```python
> Series: 'col2' [list[str]]
> [
> 	["12345"]
> ]
> ```
> 
> As for the null result you got, I will take a closer look.

But that's with a single value, giving multiple values does what I expected the cast to do, essentially wrapping each value in a list)

```python
s = pl.Series("col2", ["12345",'12345'],dtype=pl.Utf8)
res = s.cast(pl.List(pl.Utf8))
print(res)

shape: (2,)
Series: 'col2' [list[str]]
[
	["12345"]
	["12345"]
]
```

**Comment by reswqa** [comment]
Yep, my mistake. You are right.

**Comment by ion-elgreco** [comment]
> The default behavior of arrow2 cast non-nested type to list is per-value(`u8` characters for `Utf8Type`) per-list. That's to say:
> 
> ```python
> s = pl.Series("col2", "12345",dtype=pl.Utf8)
> res = s.cast(pl.List(pl.Utf8))
> ```
> 
> You will get
> 
> ```python
> Series: 'col2' [list[str]]
> [
> 	["1"]
> 	["2"]
> 	["3"]
> 	["4"]
> 	["5"]
> ]
> ```
> 
> instead of
> 
> ```python
> Series: 'col2' [list[str]]
> [
> 	["12345"]
> ]
> ```
> 
> As for the null result you got, I will take a closer look.

Isn't that rather due to the fact that pl.Series infers each character as an element:

```python


s = pl.Series("col2", ["12345"],dtype=pl.Utf8)
print(s)
res = s.cast(pl.List(pl.Utf8))
print(res)

shape: (1,)
Series: 'col2' [str]
[
	"12345"
]
shape: (1,)
Series: 'col2' [list[str]]
[
	["12345"]
]
```

**Comment by reswqa** [comment]
Yes, it does work as expected. :)

I will take a look about the `str.json_extract`.

**Comment by ion-elgreco** [comment]
> Yes, it does work as expected. :)
> 
> I will take a look about the `str.json_extract`.

Great! 😄 Thanks, already having this is an awesome feature, having it work in `str.json_extract` will be the cherry on the top!

**Comment by reswqa** [comment]
Alright, just find this follows an independent logic and is not a conventional cast, so the previous PR is not helpful in this regard.

I have proposed a PR to support this, but I prefer this to be a new feature rather than a bug-fix. As this ticket has not been accepted by maintainer, so let's wait for the reviewer's opinion. :)

**Comment by ion-elgreco** [comment]
> Alright, just find this follows an independent logic and is not a conventional cast, so the previous PR is not helpful in this regard.
> 
> I have proposed a PR to support this, but I prefer this to be a new feature rather than a bug-fix. You can take a look at the test cases inside and see if they are what you expected. As this ticket has not been accepted by maintainer, so let's wait for the reviewer's opinion. :)

I could create a new issue as a feature request, but perhaps @stinodego can also change the labels of this issue to a feature request..
