### ISSUE TITLE
numpy boolean vectors get converted as "objects" instead of cast to bool

### ISSUE THREAD

**Issue by davideger** [pola-rs/polars#1105]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.8.17

#### What operating system are you using polars on?

Google Colab

#### Describe your bug.

When constructing a dataframe for either pandas or polars from a dict of columns, pandas will accept a numpy array of bools as bools, but polars treats the same columns as opaque objects.

```
import numpy as np
import polars as pl
import pandas as pd

data = {
    'playground_id': list(range(40)),
    'good_for_kids': np.random.binomial(1, .2, 40).astype(bool),
    'num_reviews':   np.random.randint(1, 100, 40)
}

df = pd.DataFrame(data)
dl = pl.DataFrame(data)

# this shows for me a dataframe of 5 of the 40 rows
df[df.good_for_kids & (df.num_reviews > 50)]
# this shows an exception
dl[dl.good_for_kids & (dl.num_reviews > 50)]
```

```
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-60-3341a10344fe> in <module>()
----> 1 dl[dl.good_for_kids & (dl.num_reviews > 50)]

/usr/local/lib/python3.7/dist-packages/polars/eager/series.py in __and__(self, other)
    271 
    272     def __and__(self, other: "Series") -> "Series":
--> 273         return wrap_s(self._s.bitand(other._s))
    274 
    275     def __or__(self, other: "Series") -> "Series":

PanicException: boolean: DataTypeMisMatch("Object(\"object\") != bool")
```

`dl.dtypes == [polars.datatypes.Int64, polars.datatypes.Object, polars.datatypes.Int64]`

It is possible to work around this by casting the numpy boolean array to a native python bool list, but it is somewhat extra work to integrate with polars.

**Comment by ritchie46** [comment]
> It is possible to work around this by casting the numpy boolean array to a native python bool list, but it is somewhat extra work to integrate with polars.

Yes, I will fix this.

FYI: 0.8.18 is out 🙂
