### ISSUE TITLE
Support `numpy.random.Generator` objects as random seeds.

### ISSUE THREAD

**Issue by wfondrie** [pola-rs/polars#11075]
### Description

NumPy has moved towards passing `numpy.random.Generator` objects instead of seeds to maintain the random state, and it would be nice to pass these objects to Polars as well for consistency. With NumPy is looks something like this:

```python
import numpy as np

rng = np.random.default_rng(42) # Create the Generator
my_int = rng.integers(1, 9999)  # Get a random integer
```

In Polars, it would be nice to pass this object to methods like `DataFrame.sample()` as the `seed` parameter:
```python
import numpy as np
import polars as pl

rng = np.random.default_rng(42) # Create the Generator

# Sample a DataFrame:
sampled = pl.DataFrame({"a": [1, 2, 3]}).sample(1, seed=rng)
```

As for implementation, it would be fairly easy to merely draw an integer, like:
```python
    def sample(
        self,
        n: int | None = None,
        *,
        fraction: float | None = None,
        with_replacement: bool = False,
        shuffle: bool = False,
        seed: int | np.random.Generator | None = None,
    ) -> Self:
    ...
    try:
        seed = seed.integers(0, 10000)
    except AttributeError:
        pass
    ...
```

I'm also happy to put in a PR with this feature.

**Comment by orlp** [comment]
This is incompatible with our goals for the engine, we do not want to depend on Python for our core compute.
