### ISSUE TITLE
One column got discarded when `collect_all` many lazyframes

### ISSUE THREAD

**Issue by fachra** [pola-rs/polars#11083]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# test.py
import polars as pl
import numpy as np


def func(frame, cols):
    partis = frame.partition_by(by="a", include_key=True)

    lfs = []
    for idf in partis:
        lfs.append(idf.lazy().with_columns(**cols))
    dfs = pl.collect_all(lfs)

    # to print the missing column
    normal = set()
    abnormal = set()
    for idf in dfs:
        if idf.shape[1] == (3 + 150 + 1):
            normal = set(idf.columns)
        else:
            abnormal = set(idf.columns)
    if len(abnormal) > 0:
        print(normal.difference(abnormal))

    return pl.concat(dfs).sort("a")


if __name__ == "__main__":
    for seed in range(50):
        print(seed)
        np.random.seed(seed)
        df = pl.DataFrame(
            {
                "a": sorted(list(range(3000)) * 1000),
                "b": np.random.randint(0, 50000, 3000 * 1000),
                "c": np.random.randn(3000 * 1000),
            }
        )

        croll = pl.col("c").rolling_std(window_size=30, min_periods=1)
        cols = {
            **{f"croll*{i}": croll * i for i in range(150)},
            "croll/b": pl.when(pl.col("b") > 0.01)
            .then(croll / pl.col("b"))
            .otherwise(0),
        }
        func(df, cols)

```

### Issue description

The issue occurs in the line `dfs = pl.collect_all(lfs)`. The list `lfs` contains 3000 lazyframes that have the same number of columns (in my case, the number is 154). However, after collecting, some dataframes lose one column (in my case, the column 'croll*37' is lost). But if you change the total number of the columns of the dataframes, the lost column may change.

The code that I provided may not be a minimal example, because the appearance of this bug is indeterminate. I am not able to locate which part is relevant to the issue. In the image below, I ran the code given above three times and each time the program reported an error at different iteration. So, you may get different results running my program.

In my Windows system, running `test.py` will cause the program to crash at the first iteration.

After running some tests, it seems that changing `pl.when(pl.col("b") > 0.01)` to `pl.when(pl.col("b") > 0)` prevents this from happening.

![bug_collect_all](https://github.com/pola-rs/polars/assets/22255286/4270b07f-776f-4436-9e47-a2a48a9646bc)

### Expected behavior

No columns are discarded. All dataframes in `dfs` have the same number of columns.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-5.4.0-150-generic-x86_64-with-glibc2.10
Python:              3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          1.4.27
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
There's a lot going on in your code example. Could you try to create a minimal example that reproduces the behavior?

**Comment by fachra** [comment]
Thank you for looking into this issue. Here is a shorter version. But it's really no different in essence from the previous example. I've reduced the length of the code and the amount of data, but at the cost of a lower probability of the bug appearing. The program needs to be looped many times before the bug appears. In my experience, raising `n_group`, `n_elem`, and `n_col` increases the probability of this bug occurring.

I actually spent a long time on this bug, but I still haven't found a code that can certainly reproduces the bug.

```python
import polars as pl
import numpy as np

n_group = 1000
n_elem = 10
n_col = 40

np.random.seed(0)
df = pl.DataFrame(
    {
        "a": sorted(list(range(n_group)) * n_elem),
        "b": np.random.randint(0, 50000, n_group * n_elem),
        "c": np.random.randn(n_group * n_elem),
    }
)

cols = {
    **{f"c*{i}": pl.col("c") * i for i in range(n_col - 4)},
    "c/b": pl.when(pl.col("b") > 0.01).then(pl.col("c") / pl.col("b")).otherwise(0),
}

partis = df.partition_by(by="a", include_key=True)
lfs = [idf.lazy().with_columns(**cols) for idf in partis]

for i in range(500):
    print(i)
    dfs = pl.collect_all(lfs)
    df2 = pl.concat(dfs)  # raise ShapeError occasionally due to the bug in collect_all
    # df2  = pl.concat(lfs).collect() # This is also buggy. But the probability of it occurring is lower.
```


The following screenshot shows me encountering this bug on the 258th loop running the above code.
![collect_all_bug](https://github.com/pola-rs/polars/assets/22255286/b4909af4-d242-4900-a869-a6dff0ce73d7)

**Comment by fachra** [comment]
This bug still exists in 0.19.3.

**Comment by stinodego** [comment]
I can no longer reproduce this on the main branch.
