### ISSUE TITLE
Naming consistency of aggregation

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#11092]
It's slightly odd that you use `.select()` for data frames and `.agg()` for grouped data frames.

A couple possible options:
* Allow `.select()` and `.agg()` for both cases
* Rename `.agg()` to `.select()`

It think having them both be named `.select()` makes the most sense and is the most consistent.

``` python
import polars as pl
from polars import col

df = pl.DataFrame({'x': [1, 2, 3], 'y': ['a', 'a', 'b']})

df.select(col('x').mean()) # Works
df.agg(col('x').mean()) # Fails

df.group_by('y').select(col('x').mean()) # Fails
df.group_by('y').agg(col('x').mean()) # Works
```

**Comment by ion-elgreco** [comment]
I don't really see the confusion, almost every dataframe library (Spark DF API, Pandas, Dask) does this.

**Comment by markfairbanks** [comment]
There are 3 options
1) Same name: `df.select()`, `grouped_df.select()`
1) Different names: `df.select()`, `grouped_df.agg()`
1) Both work: `df.select()`, `df.agg()`, `grouped_df.select()`, `grouped_df.agg()`

I don't think `polars` should do its API bc other packages do. I think consistency is one of the best parts of the polars API. Option 1 seems the most logical to me 🤷‍♂️ 

pandas uses option 1 and allows `.agg()` on both grouped and ungrouped. Spark uses option 2 (I'm not familiar with Dask so I can't speak to that one). So whatever decision polars makes will naturally follow one package or the other, but that shouldn't be the reason it's chosen IMO.

**Comment by orlp** [comment]
My vision for the future is where the `group_by` operator on the dataframe is removed entirely, where your examples would be

```python
df.select(pl.col('x').mean())
df.select(pl.col('x').mean().group_by('y'))
```

similar to how `over` already works for window functions.

**Comment by ion-elgreco** [comment]
> My vision for the future is where the `group_by` operator on the dataframe is removed entirely and made a first-class expression method instead. Your examples would be:
> 
> ```python
> df.select(pl.col('x').mean())
> df.select(pl.col('x').mean().group_by('y'))
> ```
> 
> This is similar to how `over` already works for window functions.

How would that work if you want to do many aggregations on different columns with group_by('y')?

**Comment by orlp** [comment]
@ion-elgreco  Sorry, I edited my example, I forgot that in the original example the original `y` column would also be included. If you wanted to do many aggregations it would be

```python
df.select(
    (
        pl.col('y'),
        pl.col('x').mean(),
        pl.col('x').std(),
        pl.col('age').min(),
    ).group_by('y'))
)
```

**Comment by ion-elgreco** [comment]
> @ion-elgreco Sorry, I edited my example, I forgot that in the original example the original `y` column would also be included. If you wanted to do many aggregations it would be
> 
> ```python
> df.select(
>     (
>         pl.col('y'),
>         pl.col('x').mean(),
>         pl.col('x').std(),
>         pl.col('age').min(),
>     ).group_by('y')
> )
> ```
> 
> which is short-hand for
> 
> ```python
> df.select(
>     pl.col('y').group_by('y'),
>     pl.col('x').mean().group_by('y'),
>     pl.col('x').std().group_by('y'),
>     pl.col('age').min().group_by('y'),
> )
> ```

Hm, doesn't that leave the door open for people trying to do aggregations on different columns in one select, which probably won't work since it yields less rows one aggregation than the other?

**Comment by orlp** [comment]
> Hm, doesn't that leave the door open for people trying to do aggregations on different columns in one select, which probably won't work since it yields less rows one aggregation than the other?

@ion-elgreco Of course, but I fail to see how that's of any particular concern or special to this. That will fail in just the same way `df.select(pl.col('x').filter(a), pl.col('x').filter(b))` will fail for different conditions `a`, `b`.

**Comment by ion-elgreco** [comment]
> > Hm, doesn't that leave the door open for people trying to do aggregations on different columns in one select, which probably won't work since it yields less rows one aggregation than the other?
> 
> @ion-elgreco Of course, but I fail to see how that's of any particular concern or special to this. That will fail in just the same way `df.select(pl.col('x').filter(a), pl.col('x').filter(b))` will fail for different conditions `a`, `b`.

Fair point 😄

**Comment by stinodego** [comment]
I'll close this as 'not planned'. We have some ideas for improving the API here, as @orlp has shown. But renaming `agg` to `select` is not in the cards.
