### ISSUE TITLE
Add section for data visualization to the user guide

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars#11108]
Hi!

In the documentation we should cover how to interact with plotting libraries (e.g. Seaborn, Streamlit, Matplotlib, Plotly, Altair ....). For Data science use cases

- [ ] Explain the Dataframe Interchange Protocol (python only) (https://data-apis.org/dataframe-protocol/latest/index.html)
- [ ] For each library a seperate page showing some basic examples and/pr if they are supported

**Comment by CBell045** [comment]
Is there anything else to do on this issue? I was looking to contribute and it seems like this has been done [here](https://docs.pola.rs/user-guide/misc/visualization/) (https://docs.pola.rs/user-guide/misc/visualization/)

**Comment by stinodego** [comment]
I think this can be closed.
