### ISSUE TITLE
Update UDF section for latest version

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#11104]
Rename of apply functions should be reflected in the guide.

https://pola-rs.github.io/polars-book/user-guide/expressions/user-defined-functions/

**Comment by Mickychen00** [comment]
Have it been added into users guide?

**Comment by stinodego** [comment]
> Have it been added into users guide?

It was updated in #11104. You can see the new page here:

https://pola-rs.github.io/polars/user-guide/expressions/user-defined-functions/
