### ISSUE TITLE
PanicException when filter on sorted columns

### ISSUE THREAD

**Issue by potter420** [pola-rs/polars#1110]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.8.19

#### What operating system are you using polars on?

Amazon Linux 2

#### Describe your bug.

Panic Exception when filter on sorted columns

#### What are the steps to reproduce the behavior?

```python
import polars as pl

a = pl.DataFrame({
    'col1': ['a']*500 + ['b']*500,
})
a.filter(pl.col('col1')!= 'b')
```
#### What is the actual behavior?

```
PanicException: range end index 257 out of range for slice of length 251
```
Additional rust panic output:
```
thread '<unnamed>' panicked at 'assertion failed: start + len <= bitmap.len()', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d545253/src/array/growable/utils.rs:26:13
thread '<unnamed>' panicked at 'range end index 23875 out of range for slice of length 23872', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d545253/src/array/growable/utf8.rs:75:thread '14
```

#### What is the expected behavior?

Seem like bug when dividing array into chunks for filtering. the following code work fine:

```python
a = pl.DataFrame({
    'col1': ['a', 'b']*500,
})
a.filter(pl.col('col1')!= 'b')

```

And the code above work fine with polars 0.8.16

**Comment by ritchie46** [comment]
Thanks @potter420. This bug was introduced because we switched the backend from `arrow-rs` to `arrow2`. I will patch the python release back to `arrow-rs` until this is fixed. I will ping you when it is released. :slightly_smiling_face: 

@jorgecarleitao FYI

**Comment by ritchie46** [comment]
@potter420 patched and released.
