### ISSUE TITLE
Is it possible to create a dataframe from row-like (Vec<Struct>) data?

### ISSUE THREAD

**Issue by tomlister** [pola-rs/polars#1111]
Hi,

Is it possible to create a dataframe from row-like (Vec<Struct>) data?

i.e A vec of OHLCFrame?
```rust
struct OHLCFrame {
    close_time: i64,
    open_price: f64,
    high_price: f64,
    low_price: f64,
    close_price: f64,
    volume: f64,
    quote_volume: f64
}
```

Cheers.

Also, I have a pretty cool issue number :)

**Comment by kkonghao** [comment]
Yes I think it is necessary that I also have the same data processing requirements to add a new row to the dataframe

**Comment by ritchie46** [comment]
Haha.. congrats on the number.

You can use [from_rows](https://pola-rs.github.io/polars/polars/frame/struct.DataFrame.html#method.from_rows). If performance is important,  I'd recommend to see if you can still create data in a columnar fashion with the builders.

**Comment by tomlister** [comment]
Dank u.
Ben je Nederlands? Ik spreek beetje Nederlands.

**Comment by tomlister** [comment]
Bit confused as how to cast of convert to rows to supply an argument to from_rows

**Comment by ritchie46** [comment]
Jep, Nederlands. 😄

A `Row` can have any combination of datatypes. In your case its all `f64`, but Polars cannot know that normally. So you will have to wrap the `f64` data in the `AnyValue` enum to be able to wrap them inti a `Row`.

**Comment by tomlister** [comment]
Thanks.

Sorry for being a pest. How do I enumerate row by row?

**Comment by ritchie46** [comment]
> Sorry for being a pest. How do I enumerate row by row?

How do you mean? What do you want to do?

**Comment by tomlister** [comment]
Let's say we have a dataframe.

How would one go about iterating over it by row?

i.e (this is not the way to do it but will suffice in explaining what I'm trying to do)
```rust
for (idx, row) in df.iter().enumerate() {
let { close_time, close_price } = row;
}
```

**Comment by ritchie46** [comment]
You can use [get_row](https://pola-rs.github.io/polars/polars/frame/struct.DataFrame.html#method.get_row) to access by index. This however quite slow as the data is layed out columnar in memory. Every row access comprises many cache misses.

Often the same goal can be acquired in a columnar fashion. In you're case, I'd first select the `close_time` and `close_price` columns and work on them.

Ideally I would also do the arithmetic on columns.

**Comment by tomlister** [comment]
Okay, cheers I understand now.

Dank je
