### ISSUE TITLE
.round pl.Float32 produces unpredictable result

### ISSUE THREAD

**Issue by wKollendorf** [pola-rs/polars#11120]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
print(pl.DataFrame({"a": [1404.87854, 1.2334556, None]}))
print(pl.DataFrame({"a": [1404.87854, 1.2334556, None]}).with_columns([pl.col.a.cast(pl.Float32).round(2)]))

shape: (3, 1)
+------------+
¦ a          ¦
¦ ---        ¦
¦ f64        ¦
¦------------¦
¦ 1404.87854 ¦
¦ 1.2334556  ¦
¦ null       ¦
+------------+
shape: (3, 1)
+-------------+
¦ a           ¦
¦ ---         ¦
¦ f32         ¦
¦-------------¦
¦ 1404.880005 ¦
¦ 1.23        ¦
¦ null        ¦
+-------------+
```

### Issue description

Rounding Float32 is not predictable. I think for all numbers < 10 the result is as expected. When the number is > 10, then rounding is performed but the number of decimals is not as it should.

Also it is irrelevant if we first round Float64 and then cast to Float32.

### Expected behavior

.round works for Float32 as for Float64

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Windows-10-10.0.17763-SP0
Python:              3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cjackal** [comment]
Are you aware of the [representation error in floating point arithmetic](https://docs.python.org/3/tutorial/floatingpoint.html#representation-error)? Your example is not particular to `polars` but inherent in any float32 rounding:

```python
import numpy as np

f"{np.round(np.float32(1404.87854), 2):.6f}"
# 1404.880005
```

**Comment by wKollendorf** [comment]
> Are you aware of the [representation error in floating point arithmetic](https://docs.python.org/3/tutorial/floatingpoint.html#representation-error)? Your example is not particular to `polars` but inherent in any float32 rounding:
> 
> ```python
> import numpy as np
> 
> f"{np.round(np.float32(1404.87854), 2):.6f}"
> # 1404.880005
> ```

Yep, but I was hoping there would be a nice "workaround".

**Comment by alexander-beedie** [comment]
> Yep, but I was hoping there would be a nice "workaround".

If you need precision guarantees then the only real "workaround" here is to use `Decimal` values instead ;)
