### ISSUE TITLE
connectorx `partition_on` not working

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#11137]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.read_database_uri("select 1", url, partition_on="x")
```

### Issue description

Sorry again for no copy & paste.

<img width="1123" alt="image" src="https://github.com/pola-rs/polars/assets/175722/2a10b55f-dcdd-4132-aaa9-73edc549f3e1">

### Expected behavior

Should work or give better error message.

### Installed versions

Polars 0.19.2

**Comment by alexander-beedie** [comment]
IF I'm reading the error correctly, it looks like you should raise this with `connectorx` - seems to be coming from their code; we just pass-through to them here.
