### ISSUE TITLE
'generator' object has no attribute 'fetcharrowbatches'

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#11131]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```py
conn = my_create_turbodbc_connection()
pl.read_database("select 1", conn, batch_size=42)
```

### Issue description

Sorry for the screenshots, I don't have copy & paste on the machine.

<img width="1353" alt="Screenshot 2023-09-15 at 13 29 28" src="https://github.com/pola-rs/polars/assets/175722/679b280e-6bfe-44d1-b50f-91b1d83d983a">

<img width="636" alt="Screenshot 2023-09-15 at 13 29 44" src="https://github.com/pola-rs/polars/assets/175722/783057c4-3519-4c32-9afb-6483b2f87e87">

### Expected behavior

Should work (?)

### Installed versions

Polars 0.19.2 from conda-forge

**Comment by ritchie46** [comment]
@alexander-beedie can you take this one?
