### ISSUE TITLE
Polars Explode with `List[null]` type

### ISSUE THREAD

**Issue by uditrana** [pola-rs/polars#11147]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

%env POLARS_VERBOSE=1

expl_len = 3
json = [{"id": 0, "a": list(range(expl_len)), "null": [np.nan] * expl_len},
        {"id": 1, "a": list(range(expl_len)), "null": [np.nan] * expl_len},
        {"id": 3, "a": list(range(expl_len)), "null": [np.nan] * expl_len},]
pl.from_pandas(pd.json_normalize(json), nan_to_null=True).explode(["a", "null"])
```

### Log output

```shell
ShapeError: exploded column(s) "null" doesn't have the same length: null as the dataframe: 9
```
```


### Issue description

This issue seems to only happen with Nones/Nulls and not `np.nan`. If you set `nan_to_null=False` it works as it is supposed to. 

Furthermore, if you do use Expression syntax `list.lengths()` to see how Polars perceives the lengths before the explode... it comes out correctly as expected (i.e. "a" and "null" always have the same list lengths)

### Expected behavior

Explosion happens without bug

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Python:              3.11.4 (main, Aug  3 2023, 21:56:41) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I can run the code on latest polars. Please update.
