### ISSUE TITLE
Name of column with unary operator '-' becomes 'literal'

### ISSUE THREAD

**Issue by bsdfan** [pola-rs/polars#11149]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'a1': [1, 2, 3],
    'a2': [4, 5, 6],
    'b1': [7, 8, 9]
})

print(df.select(-pl.col('a1')))
#shape: (3, 1)
#┌─────────┐
#│ literal │
#│ ---     │
#│ i64     │
#╞═════════╡
#│ -1      │
#│ -2      │
#│ -3      │
#└─────────┘
```

### Issue description

Name of `-pl.col('a1')`  is changed to 'literal'.

Due to this problem, following codes raise an Exception.

```python
df.with_columns(-pl.col('^a.$'))

#ComputeError: The name: 'literal' passed to `LazyFrame.with_columns` is duplicate
#
#Error originated just after this operation:
#DF ["a1", "a2", "b1"]; PROJECT */3 COLUMNS; SELECTION: "None"
```

### Expected behavior

Column name should not be changed.
`pl.col('foo') * (-1)` works well.

```python
print(df.select(pl.col('a1') * (-1)))
#shape: (3, 1)
#┌─────┐
#│ a1  │
#│ --- │
#│ i64 │
#╞═════╡
#│ -1  │
#│ -2  │
#│ -3  │
#└─────┘
```

`-pl.col('a1')` and `pl.col('a1') * (-1)` should be same results.

In older version (ex. 0.14.29), `-pl.col('a1')` works fine.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.109+-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             9.0.0
pydantic:            1.10.12
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> @alexander-beedie any thought about this?

It's an interesting one - I think we _should_ handle this without exposing the user to the underlying implementation, in observance of the "principle of least surprise" :)  I have a reasonable-looking way to do this; will make a quick PR 👍
