### ISSUE TITLE
Get/set categorical levels?

### ISSUE THREAD

**Issue by nspies-celsiustx** [pola-rs/polars#1115]
Is there a way to observe and set the levels in a `pl.Categorical`? I'd like to stack a number DataFrames together, and the levels haven't always been observed in each frame.

For example, the following yields an error, presumably because `"c"` has not been included in the `df2["A"]` Categorical. 

```python
In [3]: import polars as pl

In [4]: df1 = pl.DataFrame({"A":pl.Series(["a", "b", "c"]).cast(pl.Categorical)})

In [5]: df2 = pl.DataFrame({"A":pl.Series(["a", "b"]).cast(pl.Categorical)})

In [6]: df1
Out[6]:
shape: (3, 1)
╭─────╮
│ A   │
│ --- │
│ cat │
╞═════╡
│ "a" │
├╌╌╌╌╌┤
│ "b" │
├╌╌╌╌╌┤
│ "c" │
╰─────╯

In [7]: df2
Out[7]:
shape: (2, 1)
╭─────╮
│ A   │
│ --- │
│ cat │
╞═════╡
│ "a" │
├╌╌╌╌╌┤
│ "b" │
╰─────╯

In [9]: df1.vstack(df2)
thread '<unnamed>' panicked at 'assertion failed: Arc::ptr_eq(self.categorical_map.as_ref().unwrap(),\n            other.categorical_map.as_ref().unwrap())', /github/workspace/polars/polars-core/src/chunked_array/mod.rs:457:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-9-04c50023b33d> in <module>
----> 1 df1.vstack(df2)

/opt/conda/envs/py37/lib/python3.7/site-packages/polars/eager/frame.py in vstack(self, df, in_place)
   1764             return None
   1765         else:
-> 1766             return wrap_df(self._df.vstack(df._df))
   1767
   1768     def drop(self, name: Union[str, tp.List[str]]) -> "DataFrame":

PanicException: assertion failed: Arc::ptr_eq(self.categorical_map.as_ref().unwrap(),\n            other.categorical_map.as_ref().unwrap())
```

However, I know beforehand that `"c"` should be an acceptable value in the categorical. I'm looking for something like the `categories` argument to [`pandas.Categorical(values, categories)`](https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html).

(Also, a more explicit error message above would be greatly appreciated, eg `Can't concatenate Categorical column "A" because the levels don't match.`)

**Comment by ritchie46** [comment]
Hi @nspies-celsiustx , with #1116 you are able to set a global string cache where the categorie indexes are synchronized. 

This will be released next friday. You can compile from source if you want to functionality right away.

**Comment by nspies-celsiustx** [comment]
Looks beautiful! I am truly amazed at not only the fantastic library you've built but also your rapid responses to my and others' bug and feature requests. Keep up the great work @ritchie46.

**Comment by ritchie46** [comment]
> Looks beautiful! I am truly amazed at not only the fantastic library you've built but also your rapid responses to my and others' bug and feature requests. Keep up the great work @ritchie46.

Thanks, will do! :smile:
