### ISSUE TITLE
group_by_dynamic example does the wrong thing

### ISSUE THREAD

**Issue by swpease** [pola-rs/polars#11165]
### Description

The example [here](https://pola-rs.github.io/polars-book/user-guide/transformations/time-series/rolling/#using-expressions-in-group_by_dynamic) doesn't do what it says it should. Specifically, the time column is the same date repeated three times for each month, rather than the first three dates of each month:

![image](https://github.com/pola-rs/polars/assets/14047942/b4079e80-792c-40d3-87c1-6d4d4f79a2dc)

Ref issue [244](https://github.com/pola-rs/polars-book/issues/244) from the polars-book github page.

### Link

https://pola-rs.github.io/polars-book/user-guide/transformations/time-series/rolling/#using-expressions-in-group_by_dynamic

**Comment by cmdlineluser** [comment]
The repeating `time` column is because of the `.explode()` - perhaps the `.explode()` should just be removed?

[`.dt.month_end()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.dt.month_end.html#polars.Expr.dt.month_end) exists now which could be used for `days_in_month`
```python
df = (
    pl.date_range(
        start=datetime(2021, 1, 1),
        end=datetime(2021, 12, 31),
        interval="1d",
        eager=True,
    )
    .to_frame("time")
)

(df.group_by_dynamic("time", every="1mo", period="1mo", closed="left")
   .agg(
       pl.col("time").dt.day().reverse().head(3).alias("day"),
       pl.col("time").first().dt.month_end().dt.day().alias("days_in_month")
   )
)

# shape: (12, 3)
# ┌─────────────────────┬──────────────┬───────────────┐
# │ time                ┆ day          ┆ days_in_month │
# │ ---                 ┆ ---          ┆ ---           │
# │ datetime[μs]        ┆ list[u32]    ┆ u32           │
# ╞═════════════════════╪══════════════╪═══════════════╡
# │ 2021-01-01 00:00:00 ┆ [31, 30, 29] ┆ 31            │
# │ 2021-02-01 00:00:00 ┆ [28, 27, 26] ┆ 28            │
# │ 2021-03-01 00:00:00 ┆ [31, 30, 29] ┆ 31            │
# │ 2021-04-01 00:00:00 ┆ [30, 29, 28] ┆ 30            │
# │ …                   ┆ …            ┆ …             │
# │ 2021-09-01 00:00:00 ┆ [30, 29, 28] ┆ 30            │
# │ 2021-10-01 00:00:00 ┆ [31, 30, 29] ┆ 31            │
# │ 2021-11-01 00:00:00 ┆ [30, 29, 28] ┆ 30            │
# │ 2021-12-01 00:00:00 ┆ [31, 30, 29] ┆ 31            │
# └─────────────────────┴──────────────┴───────────────┘
```
