### ISSUE TITLE
Rust example on homepage: replace group_by with groupby

### ISSUE THREAD

**Issue by faysou** [pola-rs/polars#11168]
### Description

On the home page, in the rust example, group_by should be replaced by groupby so the example compiles.

### Link

https://www.pola.rs

**Comment by mcrumiller** [comment]
You need to run `cargo update -p polars`. See the [Rust Polars 0.33 changelog](https://github.com/pola-rs/polars/releases/tag/rs-0.33.0) from an hour ago in which `groupby` was replaced with `group_by`.

**Comment by alexander-beedie** [comment]
As @mcrumiller says, `group_by` is actually now the correct/current syntax: https://github.com/pola-rs/polars/pull/10654
