### ISSUE TITLE
Decimals have incorrect Float64 type even when the python feature is disabled

### ISSUE THREAD

**Issue by joe-stifler** [pola-rs/polars#11177]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let value = -4654825170126467706_i64;
    let x = Int128Chunked::from_vec("", vec![value as i128])
        .into_decimal_unchecked(Some(38), 0)
        .into_series();
    let y = Int64Chunked::from_vec("", vec![value]).into_series();

    let lazy_data = df!("x" => x.clone(), "y" => y.clone()).unwrap().lazy();
    let lazy_data = lazy_data.select(&[col("x") - col("y")]);
    let data = lazy_data.collect().unwrap();

    let result = data.select_at_idx(0).unwrap().get(0).unwrap();
    assert_eq!(result, AnyValue::Decimal(0, 0));
}
```

### Log output

```shell
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Decimal(390, 0)`,
  right: `Decimal(0, 0)`', src/main.rs:15:5
```

### Issue description

Decimal types are cast to float64 types, even when the Python feature is disabled. This issue results in misleading operations between decimals and i64 values when using Rust.

### Expected behavior

The left result in the assertion must be `Decimal(0, 0)`.

### Installed versions

```
[dependencies]
debug-here = "0.2.2"
polars = { version = "0.33.1", features = ["lazy", "dtype-decimal"]}
```

**Comment by orlp** [comment]
This appears to have been fixed at some point because I can no longer reproduce on `main`.
