### ISSUE TITLE
OOM even with streaming=True

### ISSUE THREAD

**Issue by romanzdk** [pola-rs/polars#11173]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
(pl
	.scan_csv('some.csv', separator=';', has_header=False, new_columns=header, dtypes=dtypes, infer_schema_length=100000, null_values=['\\N'])
	.with_columns(
		pl.col('dt').dt.year().alias('year'),
		pl.col('dt').dt.month().alias('month')
	)
	.collect(streaming=True)
	.write_parquet('result.parquet', use_pyarrow=True, pyarrow_options={"partition_cols": ["year", "month"]})
)
```

### Log output

```shell
avg line length: 219.16211
std. dev. line length: 9.879884
initial row estimate: 440436576
no. of chunks: 1 processed by: 1 threads.
```

### Issue description

I am trying to split 90GB CSV into smaller chunks by year/month. I run jupyter notebook in container with 5GB RAM but running this code kills the container on OOM. I thought `streaming=True` should address the issue with memory smaller than needed to load the entire dataframe. Is this expected? If not - how to address this, please?

### Expected behavior

Not crashing on OOM.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.4.0-148-generic-x86_64-with-glibc2.35
Python:              3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          2.0.15
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by JulianCologne** [comment]
remove `.collect(streaming=True)`
- this loads the whole df into memory, you do not want that!

replace `.write_parquet` with `.sink_parquet`
- `.write_xxx` is used when you have all data im memory
- `.sink_xxx` is used when streaming data

**Comment by romanzdk** [comment]
Right but then `sink_parquet` does not have `pyarrow_options` 🤔

**Comment by ritchie46** [comment]
> Right but then sink_parquet does not have pyarrow_options 🤔

Because it doesn't use pyarrow. It must use the polars parquet writer.
