### ISSUE TITLE
`.to_pandas()` converts date to datetime wrongly if outside pandas supported bounds for timestamps

### ISSUE THREAD

**Issue by remsidave** [pola-rs/polars#11174]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.from_repr("""
┌─────┬──────────────────┐
│ id  ┆ date             │
│ --- ┆ ---              │
│ i64 ┆ str              │
╞═════╪══════════════════╡
│ 1   ┆ 18 July 2020     │
│ 2   ┆ 31 December 9999 │
└─────┴──────────────────┘
""")

df.with_columns(pl.col("date").str.to_date("%d %B %Y")).to_pandas()

```

### Issue description

The polars date column holds the date 9999-12-31 which is outside pandas supported date bounds. When converting the polars dataframe to a pandas df, it converts the date which is outside pandas supported timestamp wrongly.

This is the resulting pandas dataframe from the reproducible example where the original date 9999-12-31 is converted to 1816-03-29 ... datetime without a warning.

|    |   id | date                          |
|---:|-----:|:------------------------------|
|  0 |    1 | 2020-07-18 00:00:00           |
|  1 |    2 | 1816-03-29 05:56:08.066277376 |

### Expected behavior

raising the pandas out of bounds error if polars dates are out of pandas timestamp bounds (as done when using polars datetime instead of polars date) when converting it to a pandas df.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.1.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.5.0
gevent:              <not installed>
matplotlib:          3.6.3
numpy:               1.22.4
pandas:              1.5.2
pyarrow:             8.0.0
pydantic:            1.8.2
sqlalchemy:          1.4.39
xlsx2csv:            <not installed>
xlsxwriter:          3.0.3
```

</details>

**Comment by ritchie46** [comment]
The conversion to pandas is done by pyarrow. Can you open the issue there?

**Comment by Bidek56** [comment]
This code works fine for me using Polars 0.19.3, Pands 2.1 and pyarrow 13 on a MacOS 13.5.2:
```
df = pl.from_repr("""
┌─────┬──────────────────┐
│ id  ┆ date             │
│ --- ┆ ---              │
│ i64 ┆ str              │
╞═════╪══════════════════╡
│ 1   ┆ 18 July 2020     │
│ 2   ┆ 31 December 9999 │
└─────┴──────────────────┘
""")

df.with_columns(pl.col("date").str.to_date("%d %B %Y")).to_pandas()
```
I get:
```
    id      date
0   1 2020-07-18
1   2 9999-12-31
```

**Comment by alexander-beedie** [comment]
I can also confirm that it works on both macOS and Ubuntu; maybe it's a Windows-specific issue?

FYI: from your `show_versions` result you also have an old version of `pyarrow`.
Try updating that from v8.0 (yours) to v13.0 (current) and see if that helps?

**Comment by remsidave** [comment]
thanks for your feedback. I can reproduce the erroneous date conversion also on macOS as long as pandas < 2.0.0. @alexander-beedie I updated  pyarrow to 13.0.0 and the behaviour remains identical, as long as pandas < 2.0.0 the date gets converted wrongly and with pandas >= 2.0.0 it works

**Comment by Bidek56** [comment]
@remsidave Sounds like you have a solution then. Pls close the ticket. Thx
