### ISSUE TITLE
read_excel schema_overrides missing

### ISSUE THREAD

**Issue by matquant14** [pola-rs/polars#11184]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from openpyxl import load_workbook
from pathlib import Path

xl_file=Path("my_xl.xlsx")
wb=load_workbook(xl_file)
sheets=wb.sheetnames
wb.close()

df=pl.read_excel(xl_file, 
sheet_name = sheets[1], 
schema_overrides = {'Date Announced': pl.Date, 'Date Withdrawn': pl.Date,                                                     
'Rank Date': pl.Date}
)

```

### Issue description

Calling the read_excel function and trying to overwrite some data types using the schema_overrides parameter but am getting an error saying that parameter is unexpected.  Documentation shows it exists.  Was this removed?  Am I missing something?  I'm using 0.19.2, FYI

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

### Expected behavior

expected behavior would include the schema to change the data type for the specified columns

### Installed versions

<details>

```
Polars:              0.19.2
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  0.6.0
cloudpickle:         2.2.1
connectorx:          0.3.2a7
deltalake:           0.10.1
fsspec:              2023.5.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.1.0
pyarrow:             12.0.1
pydantic:            2.1.1
sqlalchemy:          2.0.19
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by mcrumiller** [comment]
That was added in `0.19.3` via #10884. You can see the [code for `0.19.2`](https://github.com/pola-rs/polars/blob/5aa9d040e90e45f77d41a7a2f5d7b0937f76574d/py-polars/polars/io/excel/functions.py#L18-L26) doesn't have that parameter.

**Comment by matquant14** [comment]
ah ok, thanks @mcrumiller.  is there a way for the documentation to include the patch number of the release?  Right now it just says 0.19, but it would be helpful to know which stable version the documentation is referencing.  i.e. 0.19.3 vs. 0.19.2

**Comment by mcrumiller** [comment]
Yeah I agree. The thinking probably was then all 0.19.x should have the same API but that's obviously not the case.

**Comment by alexander-beedie** [comment]
We can include a `.. versionadded` tag in the docstring in these cases rather than require new doc branches; I'll see about adding one since I'm probably going to extend this function again with another param or two shortly 🤔
