### ISSUE TITLE
Add ability to assign to multiple columns

### ISSUE THREAD

**Issue by CaselIT** [pola-rs/polars#11192]
### Description

Hi polars team,

I've looked multiple times for a way of doing the equivalent of `pandas_df.loc[mask, cols] = new_value`.
I think the current api comes close to allowing it using `pl.when`, the only issue is that there seem to be no way of assigning a value to multiple columns using `pl.col`.

Example of what I'm looking for is
```py
In [1]: import polars as pl
   ...: df = pl.DataFrame({'name': list('abcde'), 'value1': [0,1,2,3,4.0], 'value2': [3,2,1,2,3.0], 'x': [1,1,0,1,0]})
   ...: df
Out[1]:
shape: (5, 4)
┌──────┬────────┬────────┬─────┐
│ name ┆ value1 ┆ value2 ┆ x   │
│ ---  ┆ ---    ┆ ---    ┆ --- │
│ str  ┆ f64    ┆ f64    ┆ i64 │
╞══════╪════════╪════════╪═════╡
│ a    ┆ 0.0    ┆ 3.0    ┆ 1   │
│ b    ┆ 1.0    ┆ 2.0    ┆ 1   │
│ c    ┆ 2.0    ┆ 1.0    ┆ 0   │
│ d    ┆ 3.0    ┆ 2.0    ┆ 1   │
│ e    ┆ 4.0    ┆ 3.0    ┆ 0   │
└──────┴────────┴────────┴─────┘

In [2]: df_result = pl.DataFrame({'name': list('abcde'), 'value1': [0,1,99,3,99.0], 'value2': [3,2,99,2,99.0], 'x': [1,1,0,1,0]})
   ...: df_result
Out[2]:
shape: (5, 4)
┌──────┬────────┬────────┬─────┐
│ name ┆ value1 ┆ value2 ┆ x   │
│ ---  ┆ ---    ┆ ---    ┆ --- │
│ str  ┆ f64    ┆ f64    ┆ i64 │
╞══════╪════════╪════════╪═════╡
│ a    ┆ 0.0    ┆ 3.0    ┆ 1   │
│ b    ┆ 1.0    ┆ 2.0    ┆ 1   │
│ c    ┆ 99.0   ┆ 99.0   ┆ 0   │
│ d    ┆ 3.0    ┆ 2.0    ┆ 1   │
│ e    ┆ 99.0   ┆ 99.0   ┆ 0   │
└──────┴────────┴────────┴─────┘
```

The best way I found is to use the following, that works I think could be better.
```py
In [3]: cols = df.select(pl.col(pl.Float64)).columns
   ...: df.with_columns(pl.when(pl.col('x') == 0).then(99).otherwise(pl.col(col)).alias(col) for col in cols)
Out[3]:
shape: (5, 4)
┌──────┬────────┬────────┬─────┐
│ name ┆ value1 ┆ value2 ┆ x   │
│ ---  ┆ ---    ┆ ---    ┆ --- │
│ str  ┆ f64    ┆ f64    ┆ i64 │
╞══════╪════════╪════════╪═════╡
│ a    ┆ 0.0    ┆ 3.0    ┆ 1   │
│ b    ┆ 1.0    ┆ 2.0    ┆ 1   │
│ c    ┆ 99.0   ┆ 99.0   ┆ 0   │
│ d    ┆ 3.0    ┆ 2.0    ┆ 1   │
│ e    ┆ 99.0   ┆ 99.0   ┆ 0   │
└──────┴────────┴────────┴─────┘
```

I think that if `pl.col` had a way of specifying a value to set it to, one could do `pl.col(...).lit(value)`.
The example above could become
```py
df.with_columns(pl.when(pl.col('x') == 0).then(pl.col(pl.Float64).lit(99)).otherwise(pl.col(pl.Float64)))
```

This feature could also be used outside of when, to write things like `df.with_column(pl.col('^ham.*$").lit(42))`.

An alternative could be to allow `pl.col().when` but I don't know how to express the otherwise in the example above: `pl.col(pl.Float64).when(mask).then(99).otherwise(??)` and it's maybe less flexible.

I've tried searching but I haven't found any related issue.
Thanks for reading

**Comment by cmdlineluser** [comment]
You can use the float type selector directly inside `.otherwise`, `.keep_name()` handles the naming of multiple columns.
```python
df.with_columns(
   pl.when(pl.col('x') == 0)
     .then(99)
     .otherwise(pl.col(pl.Float64))
     .keep_name()
)

# shape: (5, 4)
# ┌──────┬────────┬────────┬─────┐
# │ name ┆ value1 ┆ value2 ┆ x   │
# │ ---  ┆ ---    ┆ ---    ┆ --- │
# │ str  ┆ f64    ┆ f64    ┆ i64 │
# ╞══════╪════════╪════════╪═════╡
# │ a    ┆ 0.0    ┆ 3.0    ┆ 1   │
# │ b    ┆ 1.0    ┆ 2.0    ┆ 1   │
# │ c    ┆ 99.0   ┆ 99.0   ┆ 0   │
# │ d    ┆ 3.0    ┆ 2.0    ┆ 1   │
# │ e    ┆ 99.0   ┆ 99.0   ┆ 0   │
# └──────┴────────┴────────┴─────┘
```

**Comment by CaselIT** [comment]
Thanks, I did not know about `keep_name()`. Maybe it could be mentioned in the doc of `when`?

Unless then ability of doing `df.with_column(pl.col('^ham.*$").lit(42))` is something that it judged useful, this feature request can be closed

**Comment by alexander-beedie** [comment]
> You can use the float type selector 

@cmdlineluser: Nice solution! I'd probably use the "actual" float selector though (that way you'd readily catch Float32 _and_ Float64 types, for example) :)
```python
import polars.selectors as cs

df.with_columns(
   pl.when(pl.col('x') == 0)
     .then(99)
     .otherwise(pl.col(pl.Float64))
     .keep_name()
)
```

**Comment by cmdlineluser** [comment]
> I did not know about keep_name(). Maybe it could be mentioned in the doc of when?

Yeah, seems like a `.keep_name()` example could be useful there.

It may also be worth noting that if you flip the logic of the condition so that the selector is inside the `.then()` - the `.keep_name()` is not needed.
```python
df.with_columns(
   pl.when(pl.col('x') != 0)
     .then(pl.col(pl.Float64))
     .otherwise(99)
)

# shape: (5, 4)
# ┌──────┬────────┬────────┬─────┐
# │ name ┆ value1 ┆ value2 ┆ x   │
# │ ---  ┆ ---    ┆ ---    ┆ --- │
# │ str  ┆ f64    ┆ f64    ┆ i64 │
# ╞══════╪════════╪════════╪═════╡
# │ a    ┆ 0.0    ┆ 3.0    ┆ 1   │
# │ b    ┆ 1.0    ┆ 2.0    ┆ 1   │
# │ c    ┆ 99.0   ┆ 99.0   ┆ 0   │
# │ d    ┆ 3.0    ┆ 2.0    ┆ 1   │
# │ e    ┆ 99.0   ┆ 99.0   ┆ 0   │
# └──────┴────────┴────────┴─────┘
```
Or if you prefer [`cs.float()`](https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html#polars.selectors.float) as @alexander-beedie pointed out.

**Comment by CaselIT** [comment]
Thanks for the suggestion regarding the selectors. In the general case they are indeed better.

> It may also be worth noting that if you flip the logic of the condition so that the selector is inside the .then() - the .keep_name() is not needed.

nice to know!

**Comment by CaselIT** [comment]
> Unless the ability of doing `df.with_column(pl.col('^ham.*$").lit(42))` is something that it judged useful, this feature request can be closed


it seems that `when` can be abused to do that:
```
df.with_columns(pl.when(False).then(pl.col(pl.Float64)).otherwise(pl.lit(42)))
```

**Comment by CaselIT** [comment]
the following works
```py
pl.Expr.lit = lambda s, v: pl.when(False).then(s).otherwise(v)
df.with_columns(cs.float().lit(42))

# shape: (5, 4)
# ┌──────┬────────┬────────┬─────┐
# │ name ┆ value1 ┆ value2 ┆ x   │
# │ ---  ┆ ---    ┆ ---    ┆ --- │
# │ str  ┆ f64    ┆ f64    ┆ i64 │
# ╞══════╪════════╪════════╪═════╡
# │ a    ┆ 42.0   ┆ 42.0   ┆ 1   │
# │ b    ┆ 42.0   ┆ 42.0   ┆ 1   │
# │ c    ┆ 42.0   ┆ 42.0   ┆ 0   │
# │ d    ┆ 42.0   ┆ 42.0   ┆ 1   │
# │ e    ┆ 42.0   ┆ 42.0   ┆ 0   │
# └──────┴────────┴────────┴─────┘
```

but I suppose it's good enough for a PR
