### ISSUE TITLE
Writing Single Column CSV Adds Null Value To End

### ISSUE THREAD

**Issue by jjjbeatyjjj** [pola-rs/polars#11198]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
#this is done in s3
s3_location = 'copy the attached file into s3 and put your s3 location here'
fs = s3fs.S3FileSystem()

#read the attached csv from an s3 location
df = pl.read_csv(f's3://{s3_location}/data/test/test.csv', has_header=False)

#write a csv back to s3 as only the first column
df_y = pl.DataFrame(df[:,0])
with fs.open(f's3://{s3_location}/data/test/test-only-actual.csv', mode='wb') as f:
    df_y.write_csv(f,has_header=False)

#read the single column csv and convert to a numpy array
df = pl.read_csv(f's3://{s3_location}/data/test/test-only-actual.csv')
y_true = df[:,-1].to_numpy()

#print the numpy array and notice the NaN at the end
print(y_true)
```

[test.csv](https://github.com/pola-rs/polars/files/12665026/test.csv)

### Log output

[ 8.  8. 13. 12.  9.  8. 11. 13. 10.  8.  9.  9. 11. 10.  6. 11.  8. 10.
 11.  7. 11. 10.  8.  8. 10. 11. 11.  8.  7. 10. 13.  8. 14. 19.  8.  7.
  5. 13. 13. 10. 10.  3.  7.  8.  9. 15.  6. 10. 14.  8.  5.  8.  7. 13.
  5.  5.  9. 10.  4.  9. 13.  8. 10.  8. 16.  6.  7. 10.  8. 13. 27.  8.
  6. 14.  5.  8. 10.  8.  8.  9. 11.  9. 13. 15. 10. 10.  6. 10.  6. 10.
  7.  7. 18.  9.  9.  7.  7.  8. 13. 15.  9. 15. 10.  9.  8. 10.  8.  4.
 11. 10. 10. 11. 11. 11. 13. 11.  8.  8. 10. 10.  9.  9.  5.  6.  6.  7.
  4.  6.  9.  5.  8. 11.  9.  6. 10.  7. 12.  9.  4. 13.  7.  9. 10. 11.
 11.  9.  6. 12. 14. 21.  6. 14. 11.  7.  7. 11. 10. 12.  9. 10.  9. 10.
 11.  6. 11. 20.  9.  7.  8.  8. 11.  8. 10.  9.  8.  6.  5.  9. 14.  8.
 12. 11. 10. 10.  7.  9. 10.  8. 11. 11. 10.  5. 14.  8. 10. 15.  9. 11.
  9. 16.  9.  9. 10.  7. 14. 11.  6.  4. 22.  8.  9. 13.  9.  7. 10. 11.
  9. 15. 16. 11. 15.  9.  9.  7. 17. 12.  8. 10. 11.  5.  8.  9.  8.  6.
  9.  8.  8. 10. 15.  6. 13. 12.  9.  7.  9. 10.  6. 14. 10.  8.  8.  8.
 15.  7.  4.  8.  7. 13.  8. 12.  9. 10. 11.  8.  6.  8.  8. 10. 11.  8.
 11.  6. 12.  9. 11.  8.  9.  8. 11. 14. 11.  4.  7.  6.  9.  6. 10. 12.
  6.  7. 15. 16. 18.  9.  9. 11. 14. 11. 11. 11. 10. 17.  8. 18. 13. 10.
  9.  9.  7.  6.  8.  9.  9.  7. 12. 13. 10. 16. 12.  8. 10.  8. 10. 11.
  8.  9. 11.  3. 11. 11. 12. 11.  9. 13.  9. 10.  8.  7. 10.  6. 11. 13.
  7. 10.  9. 11.  8.  8.  8.  6. 12. 12.  6. 11.  7.  7.  8. 11. 10. 17.
  6.  9.  8. 12. 10. 13. 16. 12.  9. 13.  9. 16.  8.  9.  8. 10. 10. 10.
  8.  8. 10. 10. 12. 11. 10. 11. 10.  9.  9.  7.  6.  6.  8.  7. 11. 11.
 17. 10.  8. 10.  7. 15. 10.  9.  8. 11. 11. 11. 17.  7. 10. 13.  7. 11.
  9. 11.  9.  9. 13.  6.  9.  8.  8.  8. 11. 10.  8. 12.  9. 15. 22.  9.
 13. 11.  7. 15. 11.  8. 10. 10.  9.  9.  7. 10.  6. 15.  6.  7. 14.  7.
 10.  6.  9. 12. 11. 11.  9.  4. 17. 11. 10. 10.  7. 12. 21.  8.  8.  5.
  7. 17.  9.  7. 10.  9. 18. 10.  6. 12. 11.  5. 13. 11. 13.  8.  9. 10.
 10. 11.  8. 10.  8. 13. 21.  8. 11. 12. 10.  9.  6. 10.  5.  7. 10. 18.
 11.  8.  7.  6. 12.  8.  6.  8.  9.  8.  9.  4.  8.  6. 10.  6. 10.  8.
  7.  8.  7. 11. 10. 10. 10.  8. 10.  7.  9.  9.  8. 14. 10.  8. 11. 13.
  9.  8. 12. 11.  7. 11.  9.  6. 11. 12.  9. 15.  8. 10.  9.  9. 10. 15.
  7. 14. 12. 10. 13.  9.  7.  8.  7.  7. 11. 11. 12. 14.  9.  8. 11.  8.
  7. 23. 11.  8. 17.  9.  7. 11. 21. 10. 11. 13.  9.  9.  9. 15.  8.  5.
 11. 10. 13. 14. 10. 12.  9. 15.  7. 10. 10. 10. 14. 10.  8.  8. 11. 11.
 10. 15.  9.  8.  8.  8.  7. 14. 14.  7. 10. 15. 10. 10. nan]

### Issue description

When writing a single column csv from a dataframe, the functionality appends a null value to the end. I believe this is happening because you are appending ',\n' to the end of every value in the dataframe. that last line break inadvertently creates a null value when writing the csv. You will need to keep the line break from happening on the last line of the dataframe.

### Expected behavior

Ideally, a single csv can be written from a dataframe without appending a null value

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-4.14.320-243.544.amzn2.x86_64-x86_64-with-glibc2.31
Python:              3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.7.1
gevent:              <not installed>
matplotlib:          3.5.2
numpy:               1.25.2
pandas:              1.4.4
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          1.4.39
xlsx2csv:            <not installed>
xlsxwriter:          3.0.3
```

</details>

**Comment by jjjbeatyjjj** [comment]
PS- love polars, thank you for the great work!

**Comment by Bidek56** [comment]
Using a simple `data.csv` which has:
```
a
1
2
3
4
5
``` 

and the following code:
```
df = pl.read_csv("data.csv")
df.write_csv("write_df.csv")
df = pl.read_csv("write_df.csv")
y_true = df[:, -1].to_numpy()
print(y_true)
```
I get: `[1 2 3 4 5]` which looks fine to me.

**Comment by jjjbeatyjjj** [comment]
> Using a simple `data.csv` which has:
> 
> ```
> a
> 1
> 2
> 3
> 4
> 5
> ```
> 
> and the following code using Polars 0.19.3:
> 
> ```
> df = pl.read_csv("data.csv")
> df.write_csv("write_df.csv")
> df = pl.read_csv("write_df.csv")
> y_true = df[:, -1].to_numpy()
> print(y_true)
> ```
> 
> I get: `[1 2 3 4 5]` which looks fine to me.

Weird, I don't think the problem is the conversion to a numpy array. If I print the data frame that reads the single column csv of the data I provided I get this:

![image](https://github.com/pola-rs/polars/assets/40673686/e92fe74f-05f7-4cfe-bac9-fb64b360f291)

When I look at the end of the csv in edit mode I see this:
![image](https://github.com/pola-rs/polars/assets/40673686/9a31326c-ede6-42a5-b932-83aa8c038b6a)

I am running this out of a sagemaker notebook btw

**Comment by Bidek56** [comment]
Maybe it's a `Sagemaker` issue? 
Please try the examples above using either VS code notebooks or a command line. Both work fine for me.

**Comment by Bidek56** [comment]
Another idea would be to try using numpy 1.26, you are using numpy: 1.25.2

**Comment by jjjbeatyjjj** [comment]
> Another idea would be to try using numpy 1.26, you are using numpy: 1.25.2

If you take the numpy logic out, it still doesn't work. Must be something to do with writing the dataframe to csv and reading it back out. Interestingly, if I use the same code I shared to write the single column csv with polars and read it back in with pandas, pandas does not add the null value! Weird! It must be a weird sagemaker edge case.

**Comment by Bidek56** [comment]
If it's a Sagemaker issue, pls close this ticket. Thx

**Comment by jjjbeatyjjj** [comment]
> If it's a Sagemaker issue, pls close this ticket. Thx

I don't think this is a Sagemaker issue as much as it is the way polars behaves when reading and writing to s3. There isn't a fix that needs to occur on from the Sagemaker's side

**Comment by ritchie46** [comment]
Can you make a minimal working example that only needs a local filesystem? This example should not need to first spill to s3.

**Comment by Bidek56** [comment]
> Can you make a minimal working example that only needs a local filesystem? This example should not need to first spill to s3.

https://github.com/pola-rs/polars/issues/11198#issuecomment-1726384381

**Comment by jjjbeatyjjj** [comment]
As I have stated, polars does not work in s3 when reading/writing a single column csv.

As expected, you can use the csv shared in the initial post and run the below code that is leveraging local file structures.
`
df = pl.read_csv('abalone/test.csv', has_header=False)
df_y = pl.DataFrame(df[:,0])
df = pl.read_csv('abalone/test-only-pred.csv')
y_true = df.to_numpy()
print(df)
`
Here is the output:
![image](https://github.com/pola-rs/polars/assets/40673686/201ae9bb-ecd8-4e83-90f0-48f350277073)

**Comment by ritchie46** [comment]
Then it doesn't seem like a polars problem. We don't do anything with s3. If you can reproduce with the local file system please open a new issue.
