### ISSUE TITLE
`df.head(n)` should ignore `pl.Config` (and probably other descriptives)

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#11203]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({'a': range(100)}).head(15)
```

### Issue description

Certain functions should probably initiate an override of the default outputs. If you have `pl.Config.set_tbl_rows(9)` but then you call `df.head(15)`, you can't see your 15 rows, which is a nuisance.

### Expected behavior

Show all requested rows.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.7
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by ritchie46** [comment]
No, I don't think it should. It is perfectly valid to call head with 1 million rows. The responsibility of head is limiting the output size, not interfere with formatting defaults.

**Comment by alexander-beedie** [comment]
Yup; seems odd to have functions arbitrarily opt-out of explicitly-set global defaults.
