### ISSUE TITLE
Missing documentation on new API for `to_datetime` and `strptime`

### ISSUE THREAD

**Issue by beeb** [pola-rs/polars#11209]
### Description

When trying to use casting from a string to a datetime on version 0.33.2 I am faced with missing documentation.

Indeed, I'm doing the following:

```rust
// undocumented `to_datetime`
let df = df
        .clone()
        .lazy()
        .select([
            col("time")
                .str()
                .to_datetime(None, None, StrptimeOptions::default(), "latest")
        ])
        .collect()?;

// as per documentation
let df = df
        .clone()
        .lazy()
        .select([
            col("time")
                .str()
                .strptime(DataType::Datetime(TimeUnit::Microseconds, None), StrptimeOptions::default())
        ])
        .collect()?;
```

Neither of those work.

In the first case, I noticed the addition of a `to_datetime` method which requires 4 arguments, the latest being of type `Expr` with label `ambiguous`. By digging through the repository I noticed mentions of values `"earliest"` and `"latest"` used withing this context, but when passing a `&str` like above it doesn't compile (mismatched types `Expr` vs `&str`)

In the second case, the documentation examples (e.g. [here](https://pola-rs.github.io/polars-book/user-guide/expressions/casting/#dates)) do not work, because of a missing third argument. It's also this `ambiguous` parameter that is nowhere documented.

If I put `"latest"` as a third parameter to strptime, the compile time error as with `to_datetime` happens.

How can I construct the `ambiguous` parameter?

**Comment by MarcoGorelli** [comment]
I'm not at my keyboard now, but from memory you may need to wrap it in `lit`?

**Comment by beeb** [comment]
@MarcoGorelli yes the solution was `strptime(DataType::Datetime(TimeUnit::Microseconds, None), StrptimeOptions::default(), Expr::Literal(LiteralValue::Utf8("latest".to_string())))`, I found out by messing around for a while ^^
