### ISSUE TITLE
polars with python3.10

### ISSUE THREAD

**Issue by zhaozhongfeng1990** [pola-rs/polars#11208]
### Description

where's  get  polars-0.19.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl version

**Comment by ritchie46** [comment]
Polars works with python 3.10. What is your question? Can you explain a bit more why this doesn't work for you?

**Comment by stinodego** [comment]
It's on PyPI like the other releases:
https://pypi.org/project/polars/0.19.3/#files
