### ISSUE TITLE
Scan_pyarrow_dataset cannot filter on hive-style partitions created with org.apache.spark.version: '3.4.1'

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#11211]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl
import pyarrow.dataset as ds
df = pl.scan_pyarrow_dataset(ds.dataset(parq_path+filename, partitioning='hive'))
df.filter(pl.col('partition_column') == 'value').head(5).collect()
```
Not sure if this belongs to polars or pyarrow.
If I run the above code on a hive-partitioned parquet file created with org.apache.spark.version: '3.4.0' it runs fine.
If I run it on a file (having 8 simple columns) created with org.apache.spark.version: '3.4.1', it runs out of 32 GB memory.

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/1000920000/ipykernel_20287/639707983.py", line 1, in <module>
    df.filter(pl.col('MONTH_CODE') == 'M999912').head(5).collect()
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1703, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: ArrowMemoryError: malloc of size 84720832 failed
```

### Issue description

Runs out of 32 GB memory.
Seems, like partition filtering does not work.

### Expected behavior

Return the top 5 rows of the filtered partition.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-4.18.0-372.51.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:              3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.0.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.02.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.23.5
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          1.4.27
xlsx2csv:            <not installed>
xlsxwriter:          3.1.3
```

</details>

**Comment by ritchie46** [comment]
What is the difference in partitioning? Can you give some more info on that? The filters are done by pyarrow, so this probably should be mentioned upstream.

**Comment by lmocsi** [comment]
I do not see any difference in partitioning.

**Comment by lmocsi** [comment]
It seem, that the issue is not with pyspark version, but with something other. :(
(Must be some issue with the data inside.)

**Comment by lmocsi** [comment]
The bug must be on pyarrow side.
