### ISSUE TITLE
Selectors requiring explicit type aliases for autocompletion/type hints

### ISSUE THREAD

**Issue by dangotbanned** [pola-rs/polars#11226]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

``` python

# noqa: D100
import polars as pl
from polars import selectors as cs
from polars.selectors import SelectorType as SelectorType_selectors
from polars.selectors import _selector_proxy_
from polars.type_aliases import SelectorType as SelectorType_type_aliases

"""Example (1)"""
pl.col("a", "b").mul(2).add(2).sub(1)
cs.integer().mul(5).add(2).sub(1)
cs.integer().as_expr().mul(5).add(2).sub(1)

"""Various Type Aliases (1)"""
int_selector: SelectorType_selectors = cs.integer()
int_selector_type_aliases: SelectorType_type_aliases = cs.integer()
int_selector_proxy: _selector_proxy_ = cs.integer()

"""Expected behaviour (1)"""
int_selector.mul(5).add(2).sub(1)
int_selector_type_aliases.mul(5).add(2).sub(1)
int_selector_proxy.mul(5).add(2).sub(1)

"""Example (2)"""
pl.col("c").dt.offset_by("1y")
cs.date().dt.offset_by("1y")
cs.date().as_expr().dt.offset_by("1y")

"""Various Type Aliases (2)"""
date_selector: SelectorType_selectors = cs.date()
date_selector_type_aliases: SelectorType_type_aliases = cs.date()
date_selector_proxy: _selector_proxy_ = cs.date()

"""Expected behaviour (2)"""
date_selector.dt.offset_by("1y")
date_selector_type_aliases.dt.offset_by("1y")
date_selector_proxy.dt.offset_by("1y")

```

### Issue description

VS Code: 1.82.2
Python Extension: v2023.16.0
Pylance Extension: v2023.9.21

This isn't a new issue for me, but have been working around it by either explicitly typing the result of a selector (as in the examples) or writing as a ```pl.col("a")``` first and then replacing with a selector afterwards. 

It is frustrating however and was surprised I couldn't find this raised before. 

![Selectors VS Code](https://github.com/pola-rs/polars/assets/125183946/20285d70-9833-42f7-b323-d7c2abdb42fc)

### Expected behavior

Access to Expr autocompletion, either directly from a selector ``` cs.date().dt.offset_by("1y") ``` or via ``` cs.date().as_expr().dt.offset_by("1y") ```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.1
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          3.1.3
```

</details>

**Comment by thomasaarholt** [comment]
Came just now to report the same thing:
```python
from typing import reveal_type
import polars.selectors as cs
foos = cs.ends_with("foo")
reveal_type(foos) # unknown
```

**Comment by alexander-beedie** [comment]
Hmm, I don't see either of the same issues, either in the code editor or console. If I try with the example code in the console it correctly resolves as `_selector_proxy_` _and_ I get autocomplete in both the console and editor 🤔 

#### Revealed type
<img width="385" alt="Screenshot 2023-09-21 at 18 40 35" src="https://github.com/pola-rs/polars/assets/2613171/05549dcc-1c1f-43f7-be93-8c8731098ccf">

#### Autocomplete
<img width="385" alt="Screenshot 2023-09-21 at 18 41 12" src="https://github.com/pola-rs/polars/assets/2613171/173d5552-9783-4291-851e-9c3edc7f0fb3">

---

Perhaps this is a VSCode vs PyCharm (what I'm using) issue. Either way, we shouldn't have two definitions of `SelectorProxy`; perhaps that's causing a problem for VSCode. I'll try to install it and see if I can reproduce.

**Comment by alexander-beedie** [comment]
Confirmed... looks like only VSCode has a problem with this, despite the type seemingly being identified correctly (and as `_selector_proxy_` inherits from `Expr` I'm not sure why VSCode doesn't show suitable autocomplete...)

<img width="433" alt="Screenshot 2023-09-21 at 22 29 41" src="https://github.com/pola-rs/polars/assets/2613171/1b6240fa-3f03-4fd6-9fe2-c660b83a7e40">

**Comment by thomasaarholt** [comment]
If you can make a MVP of the problem, then Eric over at pylance/pyright is great at identifying whatever we or pyright ( are doing incorrectly.

**Comment by alexander-beedie** [comment]
> If you can make a MVP of the problem, then Eric over at pylance/pyright is great at identifying whatever we or pyright ( are doing incorrectly.

I think I may already have a fix that keeps both IDEs/type-checkers happy, which involves getting rid of the second `SelectorType` definition. Best guess there was some sketchy entanglement going on, hmm...

PyCharm remains happy, and the copy of VSCode I just installed now shows the following:

<img width="402" alt="Screenshot 2023-09-21 at 23 08 45" src="https://github.com/pola-rs/polars/assets/2613171/37339de4-ea3d-4260-b708-0430b9ac31e8">

**Comment by thomasaarholt** [comment]
Great! Thanks for looking at this so quickly!

**Comment by alexander-beedie** [comment]
> Great! Thanks for looking at this so quickly!

No problem; autocomplete is a big part of the dev experience and selectors are important  :)

**Comment by dangotbanned** [comment]
@alexander-beedie Wow, didn't expect this to be solved so quickly. Thanks for this. 

I find ``` selectors ``` so helpful for simplifying expressions, really looking forward to having the intended typing
