### ISSUE TITLE
Encountered error when compile polars 0.33.2

### ISSUE THREAD

**Issue by qqlearn123** [pola-rs/polars#11238]
I got such an error as below when compiling polars v0.33.2 together with pyo3 v0.19 and pyo3-polars v0.7.0, using rustup nightly-2023-08-26.
```
error[E0635]: unknown feature 'proc_macro_span_shrink'

92 feature(proc_macro_span, proc_macro_span_shrink)
```

Not sure what is the cause of this error. But when I specify `proc-macro2 = "1.0.67"` in Cargo.toml. The error is gone.

But another error came up which caused `arrow2` failing to compile:
```
error[E0599]: no function or associated item named 'from_native_utc_and_offset' found for struct'DateTime' in the current scope
```

**Comment by Bidek56** [comment]
I do not see a git tag for `v0.33.2` so did you even pull the code?

**Comment by qqlearn123** [comment]
> I do not see a git tag for `v0.33.2` so did you even pull the code?

Check here: docs.rs/polars/latest/polars/

**Comment by alexander-beedie** [comment]
I'd suggest deleting the `Cargo.lock` in the project root so it can be rebuilt, and perhaps follow that with a `cargo clean`.
