### ISSUE TITLE
Support expression inside `sample` function

### ISSUE THREAD

**Issue by teenjuna** [pola-rs/polars#11244]
### Description

Recently I found myself in a situation where I needed to do this:
```py
df = df.with_columns(pl.col("SomeList").sample(pl.col("N")).alias("SomeList"))
```

Basically for each row, I wanted to replace a list in `SomeList` column to a length specified in the `N` column.

Right now, the `sample` function doesn't support expressions, one can't do it. As @MarcoGorelli said in Discord, _this may be a good feature request though, as part of the great expressification_.

**Comment by MarcoGorelli** [comment]
you're right, it's not supported, but on Discord I'd suggested something like
````python
df.with_columns(pl.col('SomeList').list.eval(pl.element().sample(n)))
```

but - even if `sample` did support expressions - I don't think it'd work to pass `sample(pl.col('n'))` in there inside of `.list.eval` anyway?

maybe `.list.sample` is warranted then?

**Comment by MarcoGorelli** [comment]
sounds good!

**Comment by cmdlineluser** [comment]
There was a similar/related query on SO recently: https://stackoverflow.com/questions/77135485/

The user wanted to do a `sample()` inside `.group_by()` with a variable sample size `min(n, group_size)`
