### ISSUE TITLE
Construct DataFrame from `SQLModel`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11242]
### Description

I wish I could construct a polars DataFrame from a list of `SQLModel` object

the following panics with `PanicException: Unknown not supported`:

```
from sqlmodel import Field, SQLModel, create_engine, Session, select
import polars as pl

class User(SQLModel, table=True):
    id: int = Field(primary_key=True)
    name: str

engine = create_engine('sqlite:///database.db')
SQLModel.metadata.create_all(engine)

with Session(engine) as session:
    user1 = User(name='user')
    user2 = User(name='user2')
    session.add(user1)
    session.add(user2)
    session.commit()

with Session(engine) as session:
    users = session.exec(select(User)).all()

pl.DataFrame(users)

```

**Comment by alexander-beedie** [comment]
I can pretty much see how to do this without us needing to know anything about that module as `SQLModel` objects are _also_ `pydantic` models (which we already support).

**Comment by alexander-beedie** [comment]
Done; and for bonus points I found a way to make DataFrame init a bit faster for models with a smaller number of fields 👍

**Comment by gab23r** [comment]
Thanks @alexander-beedie !
