### ISSUE TITLE
`.rank()` panics when `pl.Utf8` series contains `null`

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#11252]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Ranking strings panics if a null value is present:
```python
pl.Series([None, "", "z", "a"]).rank()  # panics: InvalidOperation(ErrString("fill-null strategy MaxBound is not supported"))
```

Ranking other dtypes (e.g. ints) behaves correctly:
```python
pl.Series([None, 30, 20, 9]).rank()
#shape: (4,)
#Series: '' [f64]
# [
# 	null
# 	3.0
# 	2.0
# 	1.0
# ]
```

### Issue description

Rank panics on string data - only if a null value is present.

### Expected behavior

`.rank()` on strings should behave exactly like ranking integers or other dtypes with regard to null-handling.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Python:              3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
I'll fix this on Monday.

**Comment by orlp** [comment]
It's going to take a bit longer, I want to refactor the code to solve it properly instead of just the symptom.

**Comment by moritzwilksch** [comment]
Thanks, appreciate the heads up, looking forward to the PR 👀
