### ISSUE TITLE
Github Polars Topics

### ISSUE THREAD

**Issue by linusheinz** [pola-rs/polars#11264]
### Description

Considering the the Polars plugin system and the increasing number of Polars-focused projects, I believe it would be cool to include a dedicated "Polars" tag or topic in the "About" section. This would help to discover and explore other projects related to Polars.

**Comment by ritchie46** [comment]
Not entirely sure what you mean. Could you make a PR? :)

**Comment by linusheinz** [comment]
Not necessary https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics , so there exists something like https://github.com/topics/pandas

**Comment by ritchie46** [comment]
Now I understand! Added. :+1:
