### ISSUE TITLE
`fill_nan` is not a valid aggregation in `group_by`

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#11293]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 1, 2, 2], "b": [1, 2, 0, 0]})

df.group_by("a").agg((pl.col("b") / pl.col("b").std()).fill_nan(0).sum())
```

### Log output

```shell
The predicate '[(col("b").cast(Float64)) / (col("b").std())].is_not_nan()' in 'when->then->otherwise' is not a valid aggregation and might product a different number of rows than the group_by operation would. This behavior is experimental and may be subject to change
```

### Issue description

I don't quite get why I receive such a warning message. Although the results are correct, I am not sure about the implications of such a warning.

### Expected behavior

No warning message.

### Installed versions

<details>

```
0.19.3
```

</details>

**Comment by taozuoqiao** [comment]
I would avoid `when->then->otherwise` related expressions in the `agg` context, and prefer something like
```python
(
    df.with_columns(
        pl.col("b").truediv(pl.col("b").std().over("a")).fill_nan(0).alias("b")
    )
    .group_by("a")
    .agg(pl.col("b").sum())
)
```

**Comment by stinodego** [comment]
Related to #10055

`fill_nan` does a `when->then->otherwise` behind the screens, apparently.
