### ISSUE TITLE
return list of `TypedDict` in `iter_rows`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11307]
### Description

Since #6292, we lost typing goodies from `iter_rows(..., named=True)`.
Using `TypedDict` would reconcile both word ( allow all column names + typing goodies )

**Comment by gab23r** [comment]
Actually, I think that even before #6292, we had no typing goodies because it was implemented with `collections.namedtuple` and not `typing.NamedTuple` But anyway...

**Comment by stinodego** [comment]
I don't see how this is possible? The data is dynamic, the typing is static. `TypedDict` is for when you know the exact dict entries beforehand.

I'll close this for now, but feel free to change my mind by showing how this would work and I'll re-open.

**Comment by gab23r** [comment]
You're right, it works only in a interactive environment like jupyter. But we can't have static typing. So I understand that it is not worth.

**Comment by alexander-beedie** [comment]
Sounds like you may want to create an iterator of data that populates an _existing_ typed NamedTuple, BaseModel, dataclass? (I also don't see how TypedDict is applicable here :)

```python
from typing import NamedTuple

class MyDataObject( NamedTuple ):
    x: date
    y: str
    z: int

import polars as pl
df = pl.DataFrame( {"x":[date.today()], "y":["abc"], "z":[123]} )

for row in df.iter_rows():
    print( MyDataObject(*row) )
   
# MyDataObject(x=datetime.date(2023, 9, 26), y='abc', z=123)
```

**Comment by gab23r** [comment]
I admit that I am not at ease with the concepts. my idea was:

```
from typing import TypedDict
import polars as pl
from datetime import date

movies_factory = TypedDict('Movie', {'x': date, 'y': str, 'z': int})
df = pl.DataFrame( {"x":[date.today()], "y":["abc"], "z":[123]} )

for row in df.iter_rows():
    print(movies_factory(zip(df.columns, row)))

# {'x': datetime.date(2023, 9, 26), 'y': 'abc', 'z': 123}

```
But I understand that static typing is not possible with this technique and I do not want to take you guys to much time ! 
Thank you!
