### ISSUE TITLE
Optimize group_by_rolling to use a linear scan

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#11300]
After we have good tests from #11286 we should optimize the `group_by_rolling` implementations to use linear scans. There is no need to use a binary search, we can simply slide the window, alternatingly incrementing the start and endpoints of the window.

**Comment by orlp** [comment]
The general algorithm (in pseudocode) is:

```python
times.sort()
window_start = 0
window_end = 0

results = []
for i in range(n):
    while window_start < n and times[i] - left_window_width < times[window_start]:
        window_start += 1
    while window_end < n and times[i] + right_window_width > times[window_end]:
        window_end += 1
    results.append((i, window_start, window_end))
```

**Comment by orlp** [comment]
@MarcoGorelli Will this also not trivially solve the duplicates case?

**Comment by MarcoGorelli** [comment]
nice! yeah sounds right
