### ISSUE TITLE
pl.DataFrame does'nt support list of `collections.nametuple`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11306]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

from collections import namedtuple
Test = namedtuple('Test', ['id', 'info'])
data = [Test(1, 'a'), Test(2, 'b')]
pl.DataFrame(data) # AttributeError: 'Test' object has no attribute '__annotations__'

```

### Log output

```shell
```

### Issue description

Create a `DataFrame` from a list of `collections.nametuple is not supported

### Expected behavior

It can be surpising for user that `typing.NamedTuple` is supported but not `collections.nametuple`. We should either support both  or throw an error saying that you should use typed nametuples.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by alexander-beedie** [comment]
Looks like a trivial fix; will have it addressed shortly - thanks for the report 👍
