### ISSUE TITLE
Add version constraints to Python dependencies

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#11311]
The (optional) dependencies of our Python package are not constrained to any version. Some have a minimum version (e.g. `pyarrow >= 7.0.0`), but none have a maximum version.

This is problematic for a number of reasons:
* New breaking releases of any dependency will immediately break our CI. That was fine when we had 2 or 3 dependencies, but now we have a whole list of dependencies for various integrations, and our CI is breaking every other day.
* We cannot promise to always support the latest version. At the very least, this promise will be broken during the time between the breaking dependency release and our next release. If we're not able to fix the integration quickly (for example, new `deltalake` release with many breaking changes while our resident `deltalake` expert is on sabbatical for three months), we might get a lot of confused users expecting the integration to work when it doesn't.

I propose we do the following:
* Set a maximum version for all our dependencies (e.g. `pyarrow >= 7.0.0, <14.0.0`).
* Run dependabot more frequently (let's say weekly) to pick up on any new breaking releases quickly.

This should save us a bunch of stress/annoyance around breaking CI pipelines and help avoid confusing users.

If I glance over at our friends at pandas, they have a million dependencies and do not define maximum versions. Any idea how they address this issue @MarcoGorelli ?

**Comment by stinodego** [comment]
Thanks for the input, I'll read up on this!

**Comment by ritchie46** [comment]
> Run dependabot more frequently (let's say weekly) to pick up on any new breaking releases quickly.

Isn't that the same as our CI failing? :')

**Comment by stinodego** [comment]
> Isn't that the same as our CI failing? :')

While dependabot PRs might fail, the CI will still work correctly for other PRs.

**Comment by stinodego** [comment]
>> Set a maximum version for all our dependencies
>
> I think this is generally frowned upon - there's a pretty long article here on it https://iscinumpy.dev/post/bound-version-constraints/ . To be honest I'd caution against it

After reading this, I agree. I'll close this issue and rethink this.
