### ISSUE TITLE
Not consistent `has_validity` while `read_csv` in string fields

### ISSUE THREAD

**Issue by CarlosVecina** [pola-rs/polars#11317]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
pl.read_csv(DATA_URL)

df["alone"].null_count()
# 0
df["alone"].has_validity()
# True
```

In the latest version (0.19.3), it works when I use: (not in the 0.17 version)
```python
df = pl.read_csv(TRAIN_DATA_URL, dtypes={"alone": pl.Categorical})
```

### Issue description

I'm using the `has_validity` method as recommended in the PyPolars documentation in order to check nulls in columns. It usually works, but I'm facing difficulties with some dataframes. Is it supposed to occur with strings? If so, I'm willing to learn more about bitmaps. 

### Expected behavior

For this df, it is known that this column does not have null values.

I've tried to convert to numpy and then to polars back and it is fixed. I've also tried to change types with `dtypes` arg of `read_csv()` but I still don't know what I am missing. My best effort then is pointing out this read function. 

Note: I've updated to 0.19.3 and now with the dtype mapping to Categorical, it works.

Opening this PR in order to someone with more experience with the package spot the issue in my usage or in the module logic.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.120+-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             9.0.0
pydantic:            1.10.12
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by CarlosVecina** [comment]
Okay, checking #10950, it seems an expected behaviour. Seeing that it is a common misconception, may we have a brief explanation? Kindly asking for some insights @s-banach :) 

(btw now I'm pretty sure it is not an actual bug, but can't remove the bug label)

**Comment by alexander-beedie** [comment]
This may help a little; as @reswqa says if there is no validity bitmap then it is definitely true that there are no `null` values, but the converse is _not_ true. Here's an example to demonstrate one of the ways this can come about:

```python
df = pl.DataFrame({"x": [1,2,3,4,5,None]})

df["x"].has_validity()      # => True  (contains a null value)
df["x"][:3].has_validity()  # => True  (though no values are null)
```
The second call to `has_validity()` clearly references data that contains no `null` values but it _does_ have a validity bitmap, as it represents a zero-copy slice into an existing Series - it would be a significant overhead to assess every new slice for `null` values and create/maintain separate bitmaps for each  ;)

**Comment by ritchie46** [comment]
We should update the docs. Has_validity is not the way to check if the array has nulls. Null_count is that.

**Comment by alexander-beedie** [comment]
> We should update the docs. Has_validity is not the way to check if the array has nulls. Null_count is that.

I'll have a quick run through the code; makes me think we may have a few internal paths that make the same assumption ;)

**Comment by alexander-beedie** [comment]
Ouch; found three places where we make the same mistake on the Python side. PR (with bonus test coverage) incoming 😅

**Comment by CarlosVecina** [comment]
Awesome, I'm excited to see this quick response from maintainers/collaborators. Thank you all. 
Now it is clear the `has_validity()` and `null_count()` different aiming, and I am happy to have spotted this minor issue.
