### ISSUE TITLE
Support for read_database to accept SQLAlchemy selectable

### ISSUE THREAD

**Issue by amrit110** [pola-rs/polars#11334]
### Description

Currently the read_database accepts SQL queries as strings (https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_database.html). It would be nice if we could query databases by passing SQLAlchemy selectables as a query. Dask and Pandas support this (https://docs.dask.org/en/stable/generated/dask.dataframe.read_sql.html).

**Comment by alexander-beedie** [comment]
Doesn't sound unreasonable ;)
I'll take a look at how best to integrate this.

**Comment by alexander-beedie** [comment]
Done; available in the just-release `0.19.6` 👌
