### ISSUE TITLE
Use statistics before downloading row group in scan_parquet

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pola-rs/polars#11346]
### Description

Recently natively support reading parquet gcp, azure and aws was added in #11210 which will turn out to be a very nice feature I'm sure - thank you! :-D  In https://github.com/pola-rs/polars/pull/11210#issue-1904597139 it is mentioned the option to add an optimiziation to read statistics before downloading row group when reading parquet from the cloud. This is simply the feature request for this :-)

**Comment by deanm0000** [comment]
@ritchie46 I see a lot of commits around cloud readers. I'm curious if you already did this without realizing it was an issue.

**Comment by ritchie46** [comment]
already done indeed.
