### ISSUE TITLE
batch_size argument  ignored in polars.read_database

### ISSUE THREAD

**Issue by lfpll** [pola-rs/polars#11340]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I'm testing with airflow, found out that the argument batch_size is ignored and it returns all my values.

```python
import polars as pl
from sqlalchemy import create_engine

con = 'postgresql://postgres:toptal@127.0.0.1:5433/airflow'

pl.read_database('select * from dag_tag' ,eng,batch_size=4)
```

This prints all the values

![image](https://github.com/pola-rs/polars/assets/6969067/f218774e-d476-49da-afd7-841f7c20322e)

I believe it was expected to be 4 by 4 rows.

I tested also with flight and turbodbc.

Flight has the same result, turbodbc is broken because of lack of method fetcharrowbatches.

### Issue description

The behavior of read_database does not work as expected, `batch_size` does not really work and the rows do not comes in pieces multiple of the `batch_size`

### Expected behavior

To get the files in batches of the batch_size as expected

### Installed versions

<details>

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by alexander-beedie** [comment]
I think you may have a misleading idea of how `batch_size` works; it is not a "limit" ;)

Rather, it refers to the size of the internal round-trip batches sent by the database as the result set is returned - so `read_database` will always return _all_ the rows for your query, no matter the `batch_size`. A low value is _very_ inefficient as you would be forcing a round-trip back to the database every 4 rows (in your example above) as the results is returned ;)

Also, if `turbodbc` doesn't work for you, it sounds like your version of the library was not compiled with the Arrow extensions (hence it is missing `fetcharrowbatches`); in the most recent version of polars you should see a `turodbc` error along the lines of _"does not support Apache Arrow"_ in this case. To get a version with these extensions I'd suggest installing from `conda`.
