### ISSUE TITLE
0.19.4 missing windows wheel on pypi

### ISSUE THREAD

**Issue by chrisoro** [pola-rs/polars#11355]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```

### Issue description

Build failed: https://github.com/pola-rs/polars/actions/runs/6324389140/job/17173808344
therefore wheel not uploaded: https://pypi.org/project/polars/#files

### Expected behavior

Wheel uploaded

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by jjfantini** [comment]
+1

**Comment by ritchie46** [comment]
Should be fixed now.
