### ISSUE TITLE
perf regression for  group_by_rolling (in some cases)

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11352]
Running
```python
from IPython import get_ipython
ipython = get_ipython()

import polars as pl
from datetime import date, datetime
import numpy as np

df = pl.DataFrame(
    {
        "ts": pl.datetime_range(
            date(1900, 1, 1),
            date(2100, 1, 1),
            "1m",
            eager=True,
        )
    }
)
df = df.with_columns(value=pl.Series(np.ones(len(df))))

ipython.run_line_magic("timeit", "df.group_by_rolling('ts', period='2d', offset='-2d').agg(pl.col('value').mean())")
ipython.run_line_magic("timeit", "df.group_by_rolling('ts', period='2d', offset='-1d').agg(pl.col('value').mean())")

```

with both Polars 0.19.3 and 0.19.4 I see

- 0.19.3:
```console
$ ipython t.py
1.16 s ± 77.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
8.8 s ± 353 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

- 0.19.4:
```console
$ ipython t.py
2.68 s ± 242 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.42 s ± 273 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So, looks like https://github.com/pola-rs/polars/pull/11326 has made things more consistent, but has worsened the fastest path (`group_by_values_iter_lookbehind`)?

**Comment by ritchie46** [comment]
Do you know which paths were triggered in old vs new?

**Comment by orlp** [comment]
@MarcoGorelli If you post a benchmark with a random source, could you please seed it with a fixed seed so everyone can reproduce?

**Comment by MarcoGorelli** [comment]
yup, thanks - I've updated to just use `np.ones`, so there's no randomness

I haven't checked the code paths

**Comment by ritchie46** [comment]
I think I know what it can be. We know that the endpoint is exactly at current data point, so we don't have search from start. But we still need to consume duplicates, what they other code didn't do I believe.

I will post a PR shortly. Care to give that one a spin?

**Comment by MarcoGorelli** [comment]
sure, will do

I've repurposed #11286 as a "improve tests" PR, if you wanted to get that in it should help with checking correctness of further perf improvements (as less invalid tests get skipped)

**Comment by MarcoGorelli** [comment]
I just did a `make build-release` of `https://github.com/pola-rs/polars/pull/11354`, with commit `3562477171905cacdaa72a0643b142616d5041a3`, and (for the same script as above) see:

```python
2.49 s ± 298 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.23 s ± 75.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

maybe this isn't an issue though? I guess some perf regression is to be expected if duplicates are to be handled. it's still super-fast anyway, the example above is with a 105_190_561 million-row dataframe

**Comment by MarcoGorelli** [comment]
closing then as this isn't a real issue (as noted, the 0.19.3 version gave wrong results in some cases)
