### ISSUE TITLE
Error when installing polars - pyproject.toml did not run successfully

### ISSUE THREAD

**Issue by niko86** [pola-rs/polars#11356]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pip install polars[all]
```

### Issue description

When I try to install Polars 0.19.4 using pip in Python 3.11, i then get the following error:

```
error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      error: failed to load manifest for dependency `polars`
     
      Caused by:
        failed to parse manifest at `C:\Users\user\AppData\Local\Temp\pip-install-x92k7lka\polars_fe4f0b46996d4a06b3ea6e501af16360\local_dependencies\polars\Cargo.toml`
     
      Caused by:
        error inheriting `polars-algo` from workspace root manifest's `workspace.dependencies.polars-algo`
     
      Caused by:
        `workspace.dependencies` was not defined
      ðŸ’¥ maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-modern-metadata-u4eszmxv', '--interpreter', 'C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\user\AppData\Local\Temp\pip-modern-metadata-u4eszmxv --interpreter C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

I've reinstalled the windows version of python, used miniconda. I have Rust installed using the latest rust installer for windows running version rustc 1.72.1 (d5c2e9c34 2023-09-13).

### Expected behavior

N/A

### Installed versions

Polars didn't install

**Comment by mkleinbort-ic** [comment]
I have a different installation issue with Polars 0.19.4:

![image](https://github.com/pola-rs/polars/assets/112868935/47ebc365-2dfb-4fd5-b00c-c80ec1c181f1)

**Comment by JulianCologne** [comment]
similar problem here. Python 3.11.5 on windows

![image](https://github.com/pola-rs/polars/assets/25177421/c013efab-5c30-469d-83d2-7c53e7dcf64e)

**Comment by mkleinbort-ic** [comment]
Same issue, but I think it comes from https://github.com/pola-rs/polars/issues/11355

**Comment by avimallu** [comment]
There is some delay between the release on Github and compiled binaries being available on PyPi. Linux is compiled first, followed by Mac and then Windows - it is a frequently reported problem. Wait for a few hours, and it should get there.

**Comment by ritchie46** [comment]
Should be fixed now.
