### ISSUE TITLE
read_parquet has different behaviour for use_pyarrow

### ISSUE THREAD

**Issue by amrit110** [pola-rs/polars#11364]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

# Throws error
```python
import polars as pl
df = pl.read_parquet(path_to_directory)
```

# Works as expected
```python
import polars as pl
df = pl.read_parquet(path_to_directory, use_pyarrow=True)
```

### Log output

```shell
IsADirectoryError: expected a file path; 'path/to/directory' is a directory
```

### Issue description

The `read_parquet` function seems to have different behaviour depending on the flag `use_pyarrow`. When `use_pyarrow=False` which is the default, the `source` if it is a directory containing multiple parquet files, it throws an error. Whereas, if `use_pyarrow=True`, it does not and reads all the files correctly. With `use_pyarrow=False` reading of multiple files occurs correctly when passing a glob pattern instead so `pl.read_parquet("path_to_directory/*.parquet")`.

### Expected behavior

When `use_pyarrow` is False, it should also be able to read a directory of parquet files, assuming the path to directory is passed.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.0-83-generic-x86_64-with-glibc2.31
Python:              3.10.12 (main, Aug 24 2023, 10:07:14) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.24.4
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.12
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
No, we will not guarantee the same behavior. They are completely different implementations. This is a gotcha. Polars has different semantics.

**Comment by deanm0000** [comment]
This isn't a bug. That's the intended behavior.

When you specify use_pyarrow=True then you get this but wrapped in `pl.from_arrow`

```
                pa.parquet.read_table(
                    source_prep,
                    memory_map=memory_map,
                    columns=columns,
                    **pyarrow_options,
                )
```

There are other differences too. For instance the default for pl.write_parquet is that statistics are off and to use ztd compression whereas for pyarrow the default is statistics are on with snappy compression.
