### ISSUE TITLE
Banner "Switch to stable version" incorrectly displayed

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#11367]
### Description

Banner "Switch to stable version" is displayed only when I'm on the docs for the stable version: 

![image](https://github.com/pola-rs/polars/assets/52219252/77165557-3ecf-4dd4-ba7b-0ae1dea76312)

![image](https://github.com/pola-rs/polars/assets/52219252/dc173be2-0da0-466f-8188-bf695d878684)

**Comment by orlp** [comment]
I believe this has been resolved.
