### ISSUE TITLE
Potential unsound transmute between `Vec`s

### ISSUE THREAD

**Issue by shinmao** [pola-rs/polars#11375]
Hi, I am wondering how it is guarded by the type system to soundly transmute between `Vec`:
https://github.com/pola-rs/polars/blob/998d14d745db22665efaa3f5e7dab61430460336/crates/polars-core/src/frame/mod.rs#L236-L238
From my understanding, `Vec` has an unstable layout e.g., it might reorder the fields, transmute between two `Vec`should be risky.

**Comment by ritchie46** [comment]
It is undefined but the same for every same type. We checked that the structs are Series. Therefore we know we have a `Vec<Series>`. We are essentially not transmuting as `Vec<Series> == Vec<Series>`.

**Comment by shinmao** [comment]
gotcha. you precheck the type with S::is_series().
