### ISSUE TITLE
Selecting only a literal from a DataFrame loses dimensionality

### ISSUE THREAD

**Issue by joelthompson** [pola-rs/polars#11397]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"a": [0, 1, 2]}).select([pl.lit("a")])
```

### Issue description

The example results in:

```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ a       │
└─────────┘
```

The dimensionality of the original frame is dropped. I realize the reproducible example might seem contrived, but I ran into this in real work.

### Expected behavior

I would expect it to maintain the dimensionality of the original frame and produce:

```
shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ a       │
│ a       │
│ a       │
└─────────┘
```

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            macOS-13.6-x86_64-i386-64bit
Python:              3.9.17 (main, Jun 15 2023, 07:48:58)
[Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
This is intended behaviour: #9713 #6360

**Comment by joelthompson** [comment]
This all seems inconsistent.

`pl.DataFrame({"a": [0, 1, 2]}).select()` has `shape: (0, 0)` when I would expect `shape: (3, 0)` because I'm not slicing any of the columns.

And if "singletons broadcast to the size of the result" then `pl.DataFrame({"a": [0, 1, 2]}).select().select(pl.lit("a"))` should return a `shape: (0, 1)` rather than a `shape: (1, 1)`.
