### ISSUE TITLE
Better docs around cloud readers

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#11399]
### Description

Update the read from cloud provider pages to reflect new functionality. Note that things are subject to change.

I'm working on this.

**Comment by braaannigan** [comment]
@stinodego 
I propose to change the AWS page to a generic cloud storage page so we're not maintaining very similar content on all three. Is that ok with you?

**Comment by stinodego** [comment]
Added in https://github.com/pola-rs/polars/pull/11646
