### ISSUE TITLE
Use IPC for serialization / deserialization

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars#11407]
### Description

Currently, we rely on our own custom JSON model for (de)serialization. It would be faster to use the IPC format when pickling/unpickling data.

**Comment by alexander-beedie** [comment]
Doh; I meant to do this a while back https://github.com/pola-rs/polars/issues/7773#issuecomment-1483742448.
Want me to grab it, or you have something in-flight?  ;)

**Comment by c-peters** [comment]
No need, I am almost finished with it.
