### ISSUE TITLE
Dependency `xxhash-rust` is incompatible with the license of the project

### ISSUE THREAD

**Issue by stephanbuys** [pola-rs/polars#11406]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

```

### Issue description

The crate `xxhash-rust` which is a dependency of `polars-core` is licensed under BSL-1.0 with no license file attached. This license isn't compatible with the MIT license of the project.

### Expected behavior

Dependencies should not be proprietary or copyleft, not if the main project is MIT or Apache-2 licensed.

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by stephanbuys** [comment]
Apologies, you're correct, I mixed the two up.

**Comment by alexander-beedie** [comment]
> Apologies, you're correct, I mixed the two up.

It happens; somewhat confusing that they share an acronym ;)
