### ISSUE TITLE
Faster way to count rows in a parquet file

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#11404]
### Description

To my knowledge the fastest way to count the number of rows in a parquet file with Polars is

```py
pl.scan_parquet(...).select(pl.count()).collect()
```

While a bit verbose, it is also pretty slow compared to how fast it could be.

On an example 100 M rows parquet file, Polars takes 1 s while PyArrow can read the number of rows from the metadata in 3 ms.

**Comment by ritchie46** [comment]
Polars now has fast count queries for parquet, ipc, csv and json.

**Comment by MusKaya** [comment]
> Polars now has fast count queries for parquet, ipc, csv and json.

Hi @ritchie46 , can you clarify how fast count is supported right now? via which method?
```
pl.scan_parquet(...).select(pl.count()).collect()
```
or something else?

**Comment by cmdlineluser** [comment]
@MusKaya You can see `FAST COUNT` in the query plan.

```python
print(
    pl.scan_parquet("1.parquet").select(pl.len()).explain()
)

# FAST COUNT (Parquet) [1.parquet] as "len"
#  DF []; PROJECT */0 COLUMNS
```

**Comment by Wojtechnology** [comment]
I'm getting a different result when my lazyframe is being scanned from GCS:
```python
lfs[0].select(pl.len()).explain()

'SELECT [len()]\nFROM\n  Parquet SCAN [gs://.../...]\n  PROJECT */23 COLUMNS'
```
I'm using polars version `1.29.0`. Is `FAST COUNT` not implemented for remote parquet files? I do see that there are functions like `read_parquet_schema` and supposedly they don't need to load the data, but if the file is not available locally (e.g. in GCS), would it require downloading the entire file? I know pyarrow doesn't require the entire file, it's able to read the metadata only from the remote blob store.
