### ISSUE TITLE
Support for `read_database_uri` to accept SQLAlchemy selectable

### ISSUE THREAD

**Issue by amrit110** [pola-rs/polars#11426]
### Description

In the recent release 0.19.6, support was added to `read_database` to accept SQLAlchemy selectables (#11383), this is great!. Could this also be done for the `read_database_uri` method (https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_database_uri.html)? This would be quite helpful since the method also supports partitioning the query across threads. 

On a separate note, could such a query be done lazily to read from the database to tackle memory overhead? So the API would be similar to streaming API like `scan_parquet`, where based on the partition column and size/num partitions, the function would return a LazyFrame. If this is even possible, I could create a separate feature request for that.

**Comment by alexander-beedie** [comment]
> In the recent release 0.19.6, support was added to `read_database` to accept SQLAlchemy selectables (#11383), this is great!. Could this also be done for the `read_database_uri` method (https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_database_uri.html)? 

It cannot, as `read_database_uri` does not work with SQLAlchemy connections - it uses a Rust library, `connectorx`, which obviously knows nothing of SQLAlchemy  ;)

> On a separate note, could such a query be done lazily to read from the database to tackle memory overhead?

It's not going to happen anytime soon, even if it turns out to be possible, but there's already an Issue for this one: https://github.com/pola-rs/polars/issues/9091.
