### ISSUE TITLE
rename `group_by_rolling(..).agg` to `rolling(..).select(..)`.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#11432]
### Description

The functionality would remain exactly the same and the code branches internally as well. (We can keep this abstracted in the group by LP).

But IMO the `group_by_rolling` is a misnomer, as it always returns the same number of rows, but only creates rolling windows. 
We could therefore add a `with_columns` and a `select` under the rolling functionality. Whereas a `group_by`, typically is only a `select` as it also must aggregate columns that are passengers in the operations. 

We can make this a very soft landing and only deprecate the existing `group_by_rolling`.

**Comment by orlp** [comment]
I definitely agree we should remove the `group_by` terminology from the rolling window functions, although ideally instead of
```
df.rolling(cond...).select(data...)
```
I'd prefer it if it were usable in expression form like `over`, that is
```
df.select(
    (data...).rolling(cond...)
)
```

**Comment by ritchie46** [comment]
Yes, @orlp. Maybe we should prioritize the expression variant and just phase out `group_by_rolling`. That's definitely the API I want to have eventually.

**Comment by lucazanna** [comment]
What about rolling_eval ?

that would be aligned to cumulative_eval and list.eval

i now think of methods finishing with eval as methods allowing to specify custom expressions

**Comment by cmdlineluser** [comment]
It's similar to how it's expressed with Pandas `.rolling()`/`.expanding()`<sup>[[1]]</sup>

<sub>[[1]]: https://pandas.pydata.org/pandas-docs/stable/user_guide/window.html#window-expanding</sub>

[1]: https://pandas.pydata.org/pandas-docs/stable/user_guide/window.html#window-expanding

**Comment by ritchie46** [comment]
We will have both. We will have an expression and the `rolling` context. The full context can also do group_by on other keys and therefore also changes the order of other output. This is something that isn't allow in the expression engine. I will follow up with more details.

**Comment by graceyangfan** [comment]
@ritchie46 waiting it for a long time!!! tanks

**Comment by ritchie46** [comment]
On second thought I want to keep `.agg` a we remain doing aggregation over the windows.

@stinodego could you take this one from the python side? It can reuse all the group_by architecture, so it should be just a name swap. In rust, we can just rename the `group_by_rolling` to `rolling`.
