### ISSUE TITLE
tab-complete doesn't work for `pl.col(...)` in IPython

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11433]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

If I do `pl.DataFrame(data).` and hit 'tab', I get a lot of valid hints:

![image](https://github.com/pola-rs/polars/assets/33491632/a89a7cc5-6444-4dea-8b03-6ca11b4fb7d5)

But not if I do the same with `pl.col`:

![image](https://github.com/pola-rs/polars/assets/33491632/38b132ab-f689-4eb4-a363-0502d86bf0b0)

It does however work if I assign `pl.col('a')` to a variable

![image](https://github.com/pola-rs/polars/assets/33491632/218b54e8-6d85-4834-aa2e-173c67fbd691)

### Issue description

This came up in training yesterday as being quite annoying

Arguably it may be an IPython bug, but still, is there anything that could be done within Polars to help?
I'll experiment with this a little

### Expected behavior

tab-complete to help as much as possible

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.9.2
gevent:              23.9.1
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            2.3.0
pyiceberg:           0.5.0
pyxlsb:              1.0.10
sqlalchemy:          2.0.21
xlsx2csv:            0.8.1
xlsxwriter:          3.1.5
```

</details>

**Comment by MarcoGorelli** [comment]
ooh I might have it!

opening a PR shortly

![image](https://github.com/pola-rs/polars/assets/33491632/1d3462bf-59d2-48de-8794-7f96a0672c82)

**Comment by MarcoGorelli** [comment]
Looks like this was due to https://github.com/pola-rs/polars/pull/10874 (@stijndegooijer just FYI, no blame!)

0.19.1

![image](https://github.com/pola-rs/polars/assets/33491632/bbeb8415-c381-4197-ada8-334dd1418d0e)

0.19.2:

![image](https://github.com/pola-rs/polars/assets/33491632/7688132d-dc64-4507-8164-3efc637a87d1)

**Comment by stinodego** [comment]
> Looks like this was due to https://github.com/pola-rs/polars/pull/10874

Yeah I figured. A fix would be welcome, though I guess it's an IPython issue?

**Comment by MarcoGorelli** [comment]
Alex has said he might have a fix, so should all be good

**Comment by alexander-beedie** [comment]
Got it! (at last) :))
Landing a PR in a few minutes.
