### ISSUE TITLE
Expressions should have the same plan after CSE? `value_counts` + `unnest` vs `struct.field`

### ISSUE THREAD

**Issue by baggiponte** [pola-rs/polars#11459]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data = pl.LazyFrame({"col": ["red", "red", "white"]})

print(
    (
        data
        .select(
            pl.col("col").value_counts(),
        )
        .unnest("col")
        .explain() # optimisations are on by default
    ),
    (
        data
       .select(
            pl.col("col").value_counts().struct.field("col"),
            pl.col("col").value_counts().struct.field("counts"),
        )
        .explain()
    ),
    sep="\n\n" # just a bit more spacing
)
```

### Log output

```shell
UNNEST by:[col]
   SELECT [col("col").value_counts()] FROM
    DF ["col"]; PROJECT 1/1 COLUMNS; SELECTION: "None"

SELECT [col("col").value_counts().struct.field_by_name(col)(), col("col").value_counts().struct.field_by_name(counts)()] FROM
  DF ["col"]; PROJECT 1/1 COLUMNS; SELECTION: "None"
```

### Issue description

Perhaps optimisations for such calls still need to be written? The different result might be due to `unnest` being called outside of a context.

### Expected behavior

The query plans should be the same, I guess?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.6
Index type:          UInt32
Platform:            macOS-13.3-arm64-arm-64bit
Python:              3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I don't know why this works in eager, but if the `sort` argument is not set, the output of `value_counts` is random and thus doesn't guarantee two calls to return the same order:

From the docstring:
```
        sort
            Sort the output by count in descending order.
            If set to ``False`` (default), the order of the output is random.
```

We however, should be able to proof that we can use CSE for this one, which can result in the same order as happy side-effect.

**Comment by ritchie46** [comment]
@reswqa interested in expressifying this one? :)

**Comment by ritchie46** [comment]
The CSE will pick this expression up if we write it properly as a `Expr::Function` instread of an `Epxr::AnonymousFunction`. This is a good one to pick up as first issue.

**Comment by JulianCologne** [comment]
serious question: 
is there actually a scenario where this would be useful?

```python
df.select(
    pl.col("col").value_counts().struct.field("col"),
    pl.col("col").value_counts().struct.field("counts"),
)
```

This seems like playing with fire to me and hoping the engine magic would save you from getting burned.

I personally would not want to use this in production code.
Expecially if there are consice alternatives like
```python
# option 1
df.select(
    pl.col("col").value_counts(),
)
.unnest("col")

# option 2
df.get_column("col").value_counts()
```

**Comment by cmdlineluser** [comment]
> is there actually a scenario where this would be useful?

@JulianCologne Probably not.

From the few similar examples I've seen, I think it may be because people assume that `.value_counts()` is sorted by default (that's how it works in pandas?) and are unaware of the mismatch issue.

 There is also
```python
# option 3
df.group_by("col").count()
```
 (which I think is essentially what `.value_counts()` ends up running internally.)

As for option 2: `.get_column()` does not exist for LazyFrames.
```python
# AttributeError: 'LazyFrame' object has no attribute 'get_column'
```

Option 1 is certainly valid, but some people seem to dislike having separate `.unnest()` calls and look for alternatives to keep everything inside a single "context".

**Comment by baggiponte** [comment]
> Option 1 is certainly valid, but some people seem to dislike having separate .unnest() calls and look for alternatives to keep everything inside a single "context".

Can confirm. I resorted to this because I am defining some Python functions that return expressions so that I can call them inside a select context and have an ETL pipeline be a bit more informative. Using `unnest` means I have to exit the context.

**Comment by 2361187728** [comment]
I'm new hand
