### ISSUE TITLE
the trait `FromIterator<&&str>` is not implemented for `polars::prelude::Series`

### ISSUE THREAD

**Issue by frozenranger** [pola-rs/polars#1147]
Hi @ritchie46 

Great module! I really like using dataframes, especially since I come from a python background with pandas.

I was wondering if it is possible to implement this or if there is a simple work around:

for example

```let mut x = Series::new("events", ["1", "2", "3"]); //works no problem!```

however

```let mut x: Series = ["1", "2", "3"].iter().collect();```

//fails with value of type `polars::prelude::Series` cannot be built from `std::iter::Iterator<Item=&&str>` the trait `FromIterator<&&str>` is not implemented for `polars::prelude::Series`

Also if I create the series I cannot append &str either unfortunately:

```x.append(&["4", "5", "6"].iter().collect()).unwrap(); // fails with the same error as above```

However when using ints or floats there are no problems

Do you have a quick fix that I can use or do you see this being added in a future update?
Sorry if this is a super noob question / request

Thank you for your time :)

**Comment by jorgecarleitao** [comment]
Could you try `let mut x: Series = ["1", "2", "3"].iter().map(|x| x.as_ref()).collect();`?

**Comment by frozenranger** [comment]
Thanks for the fast reply! 

I get this error:

let mut x: Series = ["1", "2", "3"].iter().map(|x| x.as_ref()).collect();
   |                                                        --^^^^^^--
   |                                                        | |
   |                                                        | cannot infer type for type parameter `T` declared on the trait `AsRef`
   |                                                        this method call resolves to `&T`

**Comment by ritchie46** [comment]
Hi @frozenranger, you have a reference too much. As the error suggests, it is not implemented for `std::iter::Iterator<Item=&&str>`, It is implemented for `&str`.

Try this:

```rust
let x: Series = ["1", "2", "3"].iter().copied().collect();
```

**Comment by frozenranger** [comment]
Ah... Perfect :)

thank you so much!

Also I noticed if I want to append the series later I need to include the &, before the array / box as seen below

'''	let mut x: Series = ["1", "2", "3"].iter().copied().collect();

	println!("{:?}", x);

	x.append(&["4"].iter().copied().collect()).unwrap();

	println!("{:?}", x); '''

if I don't include the & for example ```x.append(["4"].iter().copied().collect()).unwrap();''' I get the same error but it notes it as a &str

**Comment by frozenranger** [comment]
Also I think it may help some new people if you added this example to your docs regarding series :) Thank you so much for all this active work!

https://pola-rs.github.io/polars/polars/prelude/struct.Series.html

**Comment by ritchie46** [comment]
> I know that the function requests a "&Series" not a Series or anything else... so I put "&" in front of everything then?

Yeap, that's it.
