### ISSUE TITLE
Error with "is_in" method after upgrading to polars 0.33.0

### ISSUE THREAD

**Issue by Nnamdi-sys** [pola-rs/polars#11484]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
// check if any adjclose values are 0.0
let zero_series = Series::new("zero", vec![0.0; df.height()]);
let mask = !df.column("adjclose")?.is_in(&zero_series)?;
df = df.filter(&mask)?;
```

### Log output

```shell
no method named `is_in` found for reference `&polars::prelude::Series` in the current scope.
```

### Issue description

Getting the following error when trying to use the is_in method in polars 0.33.0:

no method named `is_in` found for reference `&polars::prelude::Series` in the current scope.

It works in Polars 0.32.1

### Expected behavior

I expect a boolean chunked array returned in the from the code below:
let mask = !df.column("adjclose")?.is_in(&zero_series)?;

### Installed versions

<details>

polars = { version = "0.33.0", features = ["lazy"] }

</details>

**Comment by ritchie46** [comment]
That's not supported on the series directly anymore. You should use the expressions for this.

**Comment by Nnamdi-sys** [comment]
> That's not supported on the series directly anymore. You should use the expressions for this.

got it. Thanks a lot!

**Comment by rob-p** [comment]
Can someone please give an example about how to do this?  That is, about how to transform a previous usage of the `is_in` function on `Series` into an expression?
