### ISSUE TITLE
polars.DataFrame.update returns a larger and larger dataframe

### ISSUE THREAD

**Issue by nconsulting** [pola-rs/polars#11493]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

all_rows = []
for x in range(20):
    row = {"A": 2, "B": 100.5, "C": -1}
    all_rows.append(row)
plc = pl.DataFrame(all_rows, schema={"A": pl.Int32, "B": pl.Float32, "C": pl.Float32})
print(plc)

for y in range(200):
    all_rows = []

    for x in range(20):
        row = {"A": 2, "B": 100.5, "C": 1 + x * 0.5}
        all_rows.append(row)
        new_df = pl.DataFrame(all_rows, schema={"A": pl.Int32, "B": pl.Float32, "C": pl.Float32})

    plc = plc.update(new_df, on=["A","B"])
    print(plc.select(pl.count())[0,0])
```

### Issue description

While updating a Polars dataframe with another dataframe, the dataframe that gets updated grows substantially in size. While the dataframe being updated should remain the same size. This fills up the RAM and ultimately it runs out of memory. It also happens when you update based on one column, instead of 2 as shown in my code example. Output of the original dataframe is 20 and output for the size of the dataframe becomes:

400 
8000
160000
3200000
64000000

and then I run out of memory.

### Expected behavior

The dataframe being updated should remain the same size.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.6
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
openpyxl:            3.1.2
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            2.3.0
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.47
xlsx2csv:            <not installed>
xlsxwriter:          3.1.0
```

</details>

**Comment by mcrumiller** [comment]
This is [intended behavior](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.update.html), `update` is syntactic sugar for a join. You're specifying your update based on columns `A` and `B` which aren't unique (in fact, they are all the same value), so you're performing a many-to-many join, which results in a cross-product rows with matching keys.

If you want to use the row number instead, don't specify `on`.

**Comment by nconsulting** [comment]
The example I provided was a simplified version of my code, just to show the, for me, unexpected behavior. In my code it doesn't happen all the time that rows are added. I have multiple A B columns that are different but not unique. Sometimes the C column gets updated as I expect. But sometimes it adds extra columns with the new C value, but leaves the "old" rows with the old C value in the ever growing dataframe. The documentation says: how: ‘left’ will keep the left table rows as is. That is what threw me off, since my left dataframe kept on growing.

I'm unable to add a unique row number. My identifier is the A B combination and I want to change all the A B combinations in one go. Is there another way to do this, so I get the intended behavior? The source dataframe should not change in size, only its values should change.

**Comment by nconsulting** [comment]
I think I found a way to get the behavior I'm looking for. I have to make sure that the dataframe I'm updating with only has unique values.

**Comment by mcrumiller** [comment]
You're right, that's a documentation issue that is confusing. What it means is that rows will never disappear, but they *can* be duplicated if there are multiple rows in the other frame that match that row's key.

**Comment by mcrumiller** [comment]
I've already got a pending `update` PR so I'll just improve the docstring there.
