### ISSUE TITLE
`any()` and `any_horizontal()` with `.over()`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#11497]
### Description

I have the following code
```python
df = pl.DataFrame(
    {
        "a": ['1', '1', '2', '2'],
        "b": [False, True, False, False],
    }
)

df.with_columns(
    pl.when(pl.col('b').any().over('a'))
    .then(1).otherwise(0)
)
```
Since it is mentioned in the documentation that `pl.any()` is "Syntactic sugar for `col(names).any()`", I expect
```python
df.with_columns(
    pl.when(pl.any(pl.col('b')).over('a'))
    .then(1).otherwise(0)
)
```
But got `ValueError: could not convert value 'Unknown' as a Literal`, and had to use `pl.any_horizontal()`
```python
df.with_columns(
    pl.when(pl.any_horizontal(pl.col('b')).over('a'))
    .then(1).otherwise(0)
)
```

Suggestions:

- I thought `.over()` works similar to `group_by`, but I don't understand why it converts rows into a horizontal structure given `mapping_strategy=group_to_rows`, requiring the use of `pl.any_horizontal()`.

- Since `Expr.any()` lacks an axis parameter, it is unclear to me when to use `pl.any()` versus `pl.any_horizontal()` for converting `Expr.any()` into a top-level function. Providing a few examples would be helpful, I believe.

Docs:
- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.any.html
- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.any.html
- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.any_horizontal.html
- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.over.html

**Comment by mcrumiller** [comment]
Which version are you on? I'm checking a few versions and your code runs fine all the way back to 0.18.

**Comment by stevenlis** [comment]
@mcrumiller I'm on `0.19.6`.

**Comment by cmdlineluser** [comment]
I did bump into that error elsewhere: https://github.com/pola-rs/polars/issues/11060#issuecomment-1715747614

Just noticing now that the docstring for any/all state they only accept strings and not exprs. 

> polars.any(*names: [str](https://docs.python.org/3/library/stdtypes.html#str),

(not sure if this changed when the horizontal functions were introduced?)

So it seems the issue is `pl.col('b')` as using just `pl.any('b')` appears to work.

```python
df.with_columns(
    pl.when(pl.any('b').over('a'))
      .then(1).otherwise(0)
)

# shape: (4, 3)
# ┌─────┬───────┬─────────┐
# │ a   ┆ b     ┆ literal │
# │ --- ┆ ---   ┆ ---     │
# │ str ┆ bool  ┆ i32     │
# ╞═════╪═══════╪═════════╡
# │ 1   ┆ false ┆ 1       │
# │ 1   ┆ true  ┆ 1       │
# │ 2   ┆ false ┆ 0       │
# │ 2   ┆ false ┆ 0       │
# └─────┴───────┴─────────┘
 ```
I also don't think using `.any_horizontal` generates the result you're after.
```python
df.with_columns(
    pl.when(pl.any_horizontal(pl.col('b')).over('a'))
    .then(1).otherwise(0)
)

# shape: (4, 3)
# ┌─────┬───────┬─────────┐
# │ a   ┆ b     ┆ literal │
# │ --- ┆ ---   ┆ ---     │
# │ str ┆ bool  ┆ i32     │
# ╞═════╪═══════╪═════════╡
# │ 1   ┆ false ┆ 0       │ # <- you want 1 here?
# │ 1   ┆ true  ┆ 1       │
# │ 2   ┆ false ┆ 0       │
# │ 2   ┆ false ┆ 0       │
# └─────┴───────┴─────────┘
```

**Comment by stevenlis** [comment]
@cmdlineluser I see. Thank you. You're correct. It appears that the function `pl.any()` does not accept expressions like `pl.any_horizontal`, which confused me.

**Comment by cmdlineluser** [comment]
They did accept expressions previously, I must have missed the change.

It looks like it happened in `0.19.0` https://github.com/pola-rs/polars/pull/10602/files
