### ISSUE TITLE
scan_parquet with google cloud storage (gcs) fsspec option endpoint_url fails with unknown configuration key

### ISSUE THREAD

**Issue by daviskirk** [pola-rs/polars#11517]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.scan_parquet("gcs://foo/bar.parquet", storage_options={"endpoint_url": "http://127.0.0.1:9090"})
```

### Log output

```shell
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.10/site-packages/polars/io/parquet/functions.py", line 258, in scan_parquet
    return pl.LazyFrame._scan_parquet(
  File "/python3.10/site-packages/polars/lazyframe/frame.py", line 427, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
exceptions.ComputeError: unknown configuration key: endpoint_url
```

### Issue description

This line worked in polars version 0.19.6 but in 0.19.7 the exception is raised.

Trying to work with fsouza/fake-gcs-server to allow testing which is the reason for setting the endpoint_url.

### Expected behavior

Perhaps this is actually an upgrade and more of a documentation issue, but I assumed that per the docs:
```
If the cloud provider is not supported by us, the storage options are passed to fsspec.open()
```
meant that I would pass the fsspec options (as an fsspec.open file handler is not supported) would be passed accordingly.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-6.2.0-33-generic-x86_64-with-glibc2.37
Python:              3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.8
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.39
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
It decides if it's a provider that is supported based on the url. Since it starts with gcp it reckons that it's supported. Once it makes that determination it's not going to revert back to fsspec. As such you're getting the error because object_store doesn't support the "endpoint_url".

**Comment by daviskirk** [comment]
That makes sense, sorry for the confusion. Even as such, 
just using scan_parquet without any options:
 
```
pl.scan_parquet("gcs://01331216-62d3-11ee-b46d-0690d518e6f0/29af6fdd-f0f7-4483-9857-259219e0c41d.parquet", storage_options={})
```

works but on 0.19.6 but on 0.19.7 the same gives us:

```
ComputeError: Generic GCS error: Unknown url scheme cannot be parsed into storage location: gcs
```

The same for `gs://...`. 

Leaving out the storage options completely also is not allowed (allowed in 0.19.6, but I guess this makes more sense with regard to the last answer)
```
ComputeError: configuration 'gcp' must be provided in order to use 'gcs' cloud urls
```

I'm sure I'm just missing something, but perhaps some clarification in the docs would help with this, at least for the simplest case of, "scan a gcs object with default credentials".

**Comment by ritchie46** [comment]
> ".

This.

We link to these configuations in the docstring: https://docs.rs/object_store/0.7.0/object_store/gcp/enum.GoogleConfigKey.html

Does any of these make it work? I am not that experience in cloud, so you will have to guide me a bit on how to make this easier. ;)

**Comment by daviskirk** [comment]
First of all thanks for trying to help, and for building the rest of this amazing library!

I can't get it to work with any of the options in https://docs.rs/object_store/0.7.0/object_store/gcp/enum.GoogleConfigKey.html but perhaps I'm misinterpreting the rust docs as well (how they map to a python dictionary). For python data scientists perhaps a basic idea of how to interpret the options would be nice?

Any sort of working example would might get me far enough to understand where I'm going wrong. For anyone using gcs for example the "default" should get the default credentials and be able to access buckets/objects the user has access to.
I guess this doesn't work by default but I can't figure out how to pass application credentials to the options either (this is probably just my missing rust knowledge):
In https://docs.rs/object_store/0.7.0/object_store/gcp/enum.GoogleConfigKey.html# there's a reference to `ApplicationCredentials` and within that `application_credentials_path` but both 
```
storage_options={"application_credentials": ...}
storage_options={"application_credentials_path": ...} 
```
result in a:
```
ComputeError: unknown configuration key: application_credentials
```

All other combinations give me the generic
```
ComputeError: Generic GCS error: Unknown url scheme cannot be parsed into storage location: gcs
```

I also tried to find an example of these in the tests but couldn't find any for google (are the tests missing completely or am I looking in the wrong spot)?


```
ComputeError: Generic GCS error: Unknown url scheme cannot be parsed into storage location: gcs
```

**Comment by daviskirk** [comment]
Closing this as the issue is ill defined

**Comment by firmai** [comment]
I am confused still, why would this not work, more detailed explanation needed.

```
import json
key_gcp = {"GOOGLE_SERVICE_ACCOUNT_KEY": json.dumps(service_account_info)}

pl.scan_parquet('gs://sovai-accounting/dataframes/prices.parq', storage_options=key_gcp)
```

**Comment by Skumin** [comment]
> I am confused still, why would this not work, more detailed explanation needed.
> 
> ```
> import json
> key_gcp = {"GOOGLE_SERVICE_ACCOUNT_KEY": json.dumps(service_account_info)}
> 
> pl.scan_parquet('gs://sovai-accounting/dataframes/prices.parq', storage_options=key_gcp)
> ```

Not OP, but this doesn't work for me on Polars 0.20.30 - getting an unknown configuration key error. If I instead use `google_service_account_key`, I get a different error saying that only one of service account key and service account path can be provided, even though I'm not providing the path. Would you know how to fix this, please?

**Comment by RainJayTsai** [comment]
> > I am confused still, why would this not work, more detailed explanation needed.
> > ```
> > import json
> > key_gcp = {"GOOGLE_SERVICE_ACCOUNT_KEY": json.dumps(service_account_info)}
> > 
> > pl.scan_parquet('gs://sovai-accounting/dataframes/prices.parq', storage_options=key_gcp)
> > ```
> 
> Not OP, but this doesn't work for me on Polars 0.20.30 - getting an unknown configuration key error. If I instead use `google_service_account_key`, I get a different error saying that only one of service account key and service account path can be provided, even though I'm not providing the path. Would you know how to fix this, please?

Change To
```
storage_options = {'google_service_account': '/path/to/gcp/sa.json'}
pl.scan_parquet('gs://sovai-accounting/dataframes/prices.parq', storage_options=storage_options)
```

NOTE: polars version: 1.7.1
