### ISSUE TITLE
0.19.7 Regression: InvalidOperationError: `is_in` cannot check for List(Utf8) values in Utf8 data

### ISSUE THREAD

**Issue by dkumor** [pola-rs/polars#11523]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
    "a": ["a","b","c"],
    "b": [["c","d"],["b","d"],["a","b"]],
})
df.with_columns(
    col("a").is_in(col("b")).alias("a_is_in_b")
)
```
This gives the error:
```
InvalidOperationError: `is_in` cannot check for List(Utf8) values in Utf8 data
```

### Issue description

Checking containment with string columns errors in 0.19.7. It works correctly in 0.19.6. My intuition is that checking e.g. a string categorical column should be allowed.

### Expected behavior

Same code as above run on 0.19.6 gives:

```
shape: (3, 3)
┌─────┬────────────┬───────────┐
│ a   ┆ b          ┆ a_is_in_b │
│ --- ┆ ---        ┆ ---       │
│ str ┆ list[str]  ┆ bool      │
╞═════╪════════════╪═══════════╡
│ a   ┆ ["c", "d"] ┆ false     │
│ b   ┆ ["b", "d"] ┆ true      │
│ c   ┆ ["a", "b"] ┆ false     │
└─────┴────────────┴───────────┘
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by alexander-beedie** [comment]
Got a simple fix; PR incoming...
Thanks for the report 👍
