### ISSUE TITLE
`Expr.is_in().not_()` no longer return `Null` since `0.19.*`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#11525]
### Description

I have code in `0.18.15`:
```python
import polars as pl
pl.DataFrame(
    {'a': ['1', '2', '3', None]}
).filter(
    pl.col('a').is_in(['1', '2']).is_not()
)
```

```
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ str  │
╞══════╡
│ 3    │
│ null │
└──────┘
```

But in `0.19.*`
```python
pl.DataFrame(
    {'a': ['1', '2', '3', None]}
).filter(
    pl.col('a').is_in(['1', '2']).not_()
# or:  ~ pl.col('a').is_in(['1', '2'])
)
```
```
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
│ 3   │
└─────┘
```

I'm unsure if this is a bug or not and how to achieve the previous result (i.e., making `is_in()` treat nulls as `False`).

**Comment by nameexhaustion** [comment]
Yes, this is intended, and it is a breaking change. It was changed to make the NULL handling consistent with the equality `==` operator which uses Kleene logic / NULL propagation. (relevant issue https://github.com/pola-rs/polars/issues/10613).

So in your case either `pl.col('a').is_in(['1', '2']).fill_null(False).not_()` or `pl.col('a').is_in(['1', '2']).not_() | pl.col('a').is_null()` works.

**Comment by stevenlis** [comment]
@nameexhaustion Thank you! Perhaps `is_in()` should have a `null_strategy` parameter that allows users to treat null values as False.

**Comment by JulianCologne** [comment]
Hi @stevenlis 
I understand your problem, but as @nameexhaustion already stated the negation of NULL is still NULL.

I am personally not a fan of adding a `null_strategy` because you have this "problem" of missing data (NULL) with every function (where to start and where to stop?) and there are already building blocks in place to solve this:

```python
df = pl.DataFrame({'a': ['1', '2', '3', None]})

# null problem
df.with_columns(
    is_in=pl.col('a').is_in(['1', '2']),
    is_in_not=pl.col('a').is_in(['1', '2']).not_(),
)
┌──────┬───────┬───────────┐
│ a    ┆ is_in ┆ is_in_not │
│ ---  ┆ ---   ┆ ---       │
│ str  ┆ bool  ┆ bool      │
╞══════╪═══════╪═══════════╡
│ 1    ┆ true  ┆ false     │
│ 2    ┆ true  ┆ false     │
│ 3    ┆ false ┆ true      │
│ null ┆ null  ┆ null      │ <<<<<
└──────┴───────┴───────────┘

# fill nulls
df.with_columns(
    is_in=pl.col('a')
    .is_in(['1', '2'])
    .fill_null(False), # <<< fill after checking
)
df.with_columns(
    is_in=pl.col('a')
    .fill_null('xx') # <<< fill before checking
    .is_in(['1', '2']),
)
┌──────┬───────┐
│ a    ┆ is_in │
│ ---  ┆ ---   │
│ str  ┆ bool  │
╞══════╪═══════╡
│ 1    ┆ true  │
│ 2    ┆ true  │
│ 3    ┆ false │
│ null ┆ false │
└──────┴───────┘
```

**Comment by stevenlis** [comment]
@JulianCologne Thank you for the explanation. I believe not all functions, but only those that test equality and return a Boolean value, will. In my opinion, all functions should have a parameter to allow users to handle missing values. For me, the problem lies in what is returned by `.is_in()`, so it would be clearer to have a parameter in `is_in()`. You could argue that `null_strategy` is not needed at all since you can always fill or find another way to deal with those. 

But when you use `is_in().fill_null(False).not_()`, you must carefully remember that since you have `.not_()` at the end, it should be filled with False after an is_in equality comparison is performed instead of True. It would be easier if we could handle this filling within `is_in()`. If I want `is_in()` to consider those nulls, it should be True; otherwise, it should be False. You don't need to think backwards. Dealing with this issue every time, such as with `str.contains`, is highly prone to errors when filling afterward. Btw, I remember in some [methods](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains), pandas has this `na` param to let user decide.

I believe it's beneficial to ensure consistency, but considering that nulls now require explicit handling, users should have the option to decide how to handle them.

**Comment by orlp** [comment]
As the other commenters explained, this is intended. We do not wish to add null-specific options to every function if `fill_null` already exactly does what is desired.
