### ISSUE TITLE
Make separate input parameters for passing cloud options to object_store vs fsspec OR revert to fsspec if encounter error with object_store

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#11524]
### Description

There seems to be a good bit of confusion around the recent upgrade to using object_store. Since object_store isn't as flexible in its inputs as fsspec, some people are getting errors where they once didn't. There's also confusion around how `read_parquet` didn't change but `scan_parquet` did.

I have two ideas on that. 

1. (a)Have two parameter inputs to determine which library to use. For backward compatibility storage_options would use fsspec and then there'd be a new parameter, maybe called object_stor_options although I'm indifferent as to its name. (b) OR only storage_options but then there's an optional force_fsspec that would default to False but people can set it to True.

2. (Alternatively) Keep only the storage_options parameter but if there's an object_store related error or deficiency then revert to fsspec before raising the error to the user. Maybe give them a warning.

Here are some issues that this would either solve or, at least, mitigate:

https://github.com/pola-rs/polars/issues/11520

https://github.com/pola-rs/polars/issues/11517

https://github.com/pola-rs/polars/issues/11372

I would guess these sort of issues will only increase as people who aren't glued to the polars update page start updating their local version to breaking changes.

**Comment by ritchie46** [comment]
I agree this is confusing. The goal is to have fsspec fased out for scanning. Maybe we should keep a dict with allowed object-store names and dispatch to fsspec when you pass fsspec options and printing a large warning.
