### ISSUE TITLE
scan_parquet can't accept non-String storage_options

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#11520]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.scan_parquet("s3://foo/bar.parquet", storage_options={"anon": True}).collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "/workspaces/example/example.py", line 3, in <module>
    df = pl.scan_parquet(
         ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.5/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 254, in scan_parquet
    return pl.LazyFrame._scan_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.5/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 426, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'cloud_options': 'bool' object cannot be converted to 'PyString'
```

### Issue description

As of Polars 0.19.4, `scan_parquet` crashes trying to pass certain options down to the fsspec adapter. It appears to be trying to cast all values or strings. Interesting, the eager `read_parquet` works fine.

### Expected behavior

Pass the `storage_options` object as is to fsspec adapter.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-6.2.0-1012-azure-x86_64-with-glibc2.31
Python:              3.11.5 (main, Sep 13 2023, 17:42:58) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
Since 0.19.4 scan_parquet has used the rust library object_store for cloud access. It has different inputs than fsspec. [Here's](https://docs.rs/object_store/0.7.0/object_store/aws/enum.AmazonS3ConfigKey.html) are the keys it's looking for. None of them are anon. Maybe you can just use the region. I don't have a link to a public parquet file on s3 to try it out.

read_parquet still uses fsspec which is why that still works as expected.
