### ISSUE TITLE
`sample()` gets super slow larger series/frames

### ISSUE THREAD

**Issue by aldanor** [pola-rs/polars#11531]
### Description

Once series/frame size is sufficiently large, sampling becomes obscurely slow (perhaps because of the underlying `SmallRng`?)

Not critical, but still. Here's a quick edge-case example:

```py
s = pl.Series(np.zeros(int(1e9), np.int64))
%time s.sample(1)

CPU times: user 4.6 s, sys: 16.5 ms, total: 4.62 s
Wall time: 4.63 s
```

**Comment by orlp** [comment]
It's because we use an iterator sample method that loops over the entire range. Let me fix that.
