### ISSUE TITLE
scan_parquet with hive partiioning fails with a filter producing empty result followed by select

### ISSUE THREAD

**Issue by ddutt** [pola-rs/polars#11536]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

tmp_lf.filter(filters).select(fields).collect()
*** exceptions.ColumnNotFoundError: namespace
tmp_lf.filter(filters).collect()
*** exceptions.ShapeError: unable to append to a dataframe of width 24 with a dataframe of width 21
```

Its hard to provide a working code as it needs a hive-partitioned parquet folder. 

### Issue description

The conditions to produce the error are:
* Have a hive-partitioned folder
* do a scan_parquet with hive_partitioning=True
* add a `filter` that returns an empty dataframe
* add a `select` that selects one or more of the hive partition names
* do collect

You can verify the issue by either removing the filter, making the filter return some data, or selecting only fields not created from hive partition names

### Expected behavior

proper results or an empty dataframe with all the selected columns to be returned.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Python:              3.11.3 (main, Apr 27 2023, 19:02:17) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
You can use pyarrow to make a partitioned dataset:

```python
    pq.write_to_dataset(
        df.to_arrow(),
        root_path=root,
        partition_cols=columns,
        use_legacy_dataset=True,
    )
```

**Comment by ritchie46** [comment]
Until this is fixed, this works if you set `use_statistics=False`.
