### ISSUE TITLE
`read_csv` vs `write_csv`: inconsistency between `line_terminator` and `eol_char`

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#11545]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"test": ["bar", "baz"]}).write_csv("out.csv", line_terminator="\r\n")
print(pl.read_csv("out.csv", eol_char="\n"))
```

### Issue description

When writing, it's called `line_terminator`, but when reading it's called `eol_char`.

### Expected behavior

Choose one of both in all csv methods (sink, scan, write)

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.9.2
gevent:              23.9.1
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            2.4.2
pyiceberg:           0.5.0
pyxlsb:              1.0.10
sqlalchemy:          2.0.21
xlsx2csv:            0.8.1
xlsxwriter:          3.1.6```

</details>

**Comment by alexander-beedie** [comment]
Well-spotted; looks like we're _also_ inconsistent with `quote` and `quote_char` in those methods too 😅

**Comment by svaningelgem** [comment]
For what it's worth:
`eol_char` could potentially be 2 chars (`\r\n`). However, I verified and it is reading in the data correctly in any case, so I don't know how important this is. It is however confusing for the end-user I think.

**Comment by alexander-beedie** [comment]
> `eol_char` could potentially be 2 chars (`\r\n`) 

Good point; we should prefer `line_terminator` to `eol_char` for that reason (while also updating `quote` → `quote_char`).

**Comment by ritchie46** [comment]
We don't support multiple chars in reading. `eol_char` is still `\n` if you have `\r\n` terminators.

**Comment by svaningelgem** [comment]
> We don't support multiple chars in reading. `eol_char` is still `\n` if you have `\r\n` terminators.

Indeed, I can confirm this works fine. However, I think the documentation should be updated  to avoid confusion by users.
WDYT?

**Comment by alexander-beedie** [comment]
> I think the documentation should be updated to avoid confusion by users. WDYT?

Making it clear in the docs sounds fine to me.
