### ISSUE TITLE
Parquet reading silently drops data

### ISSUE THREAD

**Issue by m00ngoose** [pola-rs/polars#11548]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl
import numpy as np

df = pd.DataFrame({'test': [[np.ones(2099) for _ in range(2000)]]})
df.to_parquet("test.parquet")

df2 = pl.read_parquet("test.parquet")
print(df2['test'].list.lengths()[0])
```
Prints: 1999

### Issue description

Also seen on other python versions and on scan_parquet.
Only seen for list-valued cells, and only ever the last row has data missing.
Pandas / use_pyarrow=True both handle it correctly.
Also observed with parquet files not written by pandas.

### Expected behavior

```python
df3 = pl.read_parquet("test.parquet", use_pyarrow=True)
print(df3['test'].list.lengths()[0])
```
Prints: 2000

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.3.4
numpy:               1.22.4
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             8.0.0
pydantic:            1.8.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.37
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mkleinbort** [comment]
Just checking, but are you sure the issue is on Polars?

This code works well:
```python
import pandas as pd
import polars as pl
import numpy as np

df = pd.DataFrame({'test': [[np.ones(2099) for _ in range(2000)]]}).pipe(pl.from_pandas)
df.write_parquet("test.parquet")

df2 = pl.read_parquet("test.parquet")
print(df2['test'].list.lengths()[0])
```
Prints: 2000

I think pandas to parquet might be serialising the data in a funny way.

**Comment by m00ngoose** [comment]
It's true I haven't conclusively demonstrated which library is at fault, but let me add to the original ticket I've also observed it with parquet files not written by pyarrow. My prior is that I'm more suspicious of polars reading.

**Comment by cjackal** [comment]
> Just checking, but are you sure the issue is on Polars?
> 
> 
> 
> This code works well:
> 
> ```python
> 
> import pandas as pd
> 
> import polars as pl
> 
> import numpy as np
> 
> 
> 
> df = pd.DataFrame({'test': [[np.ones(2099) for _ in range(2000)]]}).pipe(pl.from_pandas)
> 
> df.write_parquet("test.parquet")
> 
> 
> 
> df2 = pl.read_parquet("test.parquet")
> 
> print(df2['test'].list.lengths()[0])
> 
> ```
> 
> Prints: 2000
> 
> 
> 
> I think pandas to parquet might be serialising the data in a funny way. 
> 
> 
> 
> 

At least `pyarrow` sides with `pandas`:

```python
df = pa.table({"test": [[np.ones(2099) for _ in range(2000)]]})
pa.parquet.write_table("test.parquet")

pl.read_parquet("test.parquet")["test"].list.lengths()[0]
# 1999
```

I'm pretty sure polars' parquet reader (arrow2) does not handle `RLE_DICTIONARY` encoding correctly.

**Comment by deanm0000** [comment]
pandas doesn't write parquets. By default it uses pyarrow to write them so there's no pandas agreeing with pyarrow. It's just pyarrow.

For example if you do...

```
pq.write_table(pl.DataFrame({'test': [[list(np.ones(2099)) for _ in range(2000)]]}).to_arrow(), 'test_pl_to_pa.parquet')
pl.read_parquet('test_pl_to_pa.parquet').explode('test').shape[0]
## 1999
```

so the behavior is actually unrelated to pandas.

An even more bizarre result is...

```
pq.write_table(pl.DataFrame({'test': [[list(np.ones(2099)) for _ in range(2000)]]}).to_arrow(), 'test_pl_to_pa_nodict.parquet', use_dictionary=False)
pl.read_parquet('test_pl_to_pa_nodict.parquet').explode('test').shape[0]
## 63
```

but
```
pl.read_parquet('test_pl_to_pa_nodict.parquet', use_pyarrow=True).explode('test').shape[0]
2000
```

**Comment by nameexhaustion** [comment]
The table can be simplified to either

`pl.select(pl.arange(0, 262_145, dtype=pl.UInt32).implode().alias("x"))`, which will stop loading after 262,144 items
`pl.select(pl.arange(0, 131_073, dtype=pl.UInt64).implode().alias("x"))` which will stop loading after 131,072 items

**Comment by Bidek56** [comment]
So it works fine up to 1999, any `range()` greater than 1999 results in 1999, so I wonder if there's a buffer limit somewhere.
