### ISSUE TITLE
Chunk sizes for vstacked frames

### ISSUE THREAD

**Issue by aldanor** [pola-rs/polars#11561]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```py
r = np.random.RandomState(0)
res = []
for _ in range(50):
    n_frames = r.randint(2, 7 + 1)
    n_cols = r.randint(1, 3 + 1)
    n_rows = r.randint(0, 2 + 1, n_frames).tolist()
    frames = [pl.DataFrame(np.zeros((n_rows[i], n_cols))) for i in range(n_frames)]
    concat = pl.concat(frames, rechunk=False)
    nonempty = sum(n != 0 for n in n_rows)
    n_chunks = concat.n_chunks()
    if n_chunks != nonempty:
        print(f'{n_frames=}, {n_cols=}, {nonempty=}, {n_chunks=}, {n_rows=}')
```

### Log output

```shell
n_frames=5, n_cols=2, nonempty=4, n_chunks=5, n_rows=[2, 0, 1, 1, 1]
n_frames=5, n_cols=3, nonempty=1, n_chunks=2, n_rows=[0, 2, 0, 0, 0]
n_frames=7, n_cols=2, nonempty=4, n_chunks=6, n_rows=[2, 0, 0, 1, 0, 1, 2]
n_frames=6, n_cols=2, nonempty=2, n_chunks=4, n_rows=[2, 0, 0, 2, 0, 0]
n_frames=5, n_cols=1, nonempty=1, n_chunks=2, n_rows=[0, 0, 0, 2, 0]
n_frames=7, n_cols=2, nonempty=4, n_chunks=5, n_rows=[0, 1, 2, 0, 1, 2, 0]
n_frames=2, n_cols=2, nonempty=1, n_chunks=2, n_rows=[1, 0]
n_frames=5, n_cols=1, nonempty=2, n_chunks=4, n_rows=[2, 0, 0, 2, 0]
n_frames=5, n_cols=3, nonempty=2, n_chunks=3, n_rows=[2, 0, 0, 0, 1]
n_frames=4, n_cols=2, nonempty=0, n_chunks=1, n_rows=[0, 0, 0, 0]
n_frames=2, n_cols=1, nonempty=1, n_chunks=2, n_rows=[1, 0]
n_frames=7, n_cols=2, nonempty=4, n_chunks=5, n_rows=[1, 0, 0, 0, 1, 1, 2]
n_frames=7, n_cols=2, nonempty=4, n_chunks=5, n_rows=[1, 0, 0, 0, 1, 2, 1]
n_frames=3, n_cols=2, nonempty=1, n_chunks=2, n_rows=[2, 0, 0]
n_frames=7, n_cols=1, nonempty=6, n_chunks=7, n_rows=[2, 2, 0, 2, 2, 2, 1]
n_frames=7, n_cols=1, nonempty=4, n_chunks=5, n_rows=[0, 0, 2, 2, 1, 1, 0]
n_frames=3, n_cols=3, nonempty=2, n_chunks=3, n_rows=[2, 2, 0]
n_frames=6, n_cols=3, nonempty=3, n_chunks=4, n_rows=[2, 0, 1, 1, 0, 0]
n_frames=7, n_cols=3, nonempty=4, n_chunks=6, n_rows=[0, 2, 0, 1, 1, 1, 0]
n_frames=4, n_cols=2, nonempty=3, n_chunks=4, n_rows=[1, 0, 1, 2]
n_frames=3, n_cols=3, nonempty=1, n_chunks=2, n_rows=[0, 1, 0]
n_frames=5, n_cols=2, nonempty=3, n_chunks=4, n_rows=[1, 2, 0, 2, 0]
n_frames=4, n_cols=1, nonempty=1, n_chunks=3, n_rows=[2, 0, 0, 0]
n_frames=2, n_cols=2, nonempty=1, n_chunks=2, n_rows=[2, 0]
```

### Issue description

(May not really be a bug report since this may be the intended working behaviour, however, it's pretty obscure and hard to guess the result by just looking at it)

`pl.concat(rechunk=False)` (and `concat_df!()` on Rust side) have somewhat weird behaviour when it comes to the resulting number of chunk sizes if there's any empty frames being concatenated, see the attached example and try to guess the underlying logic.

Wouldn't it make sense to have more consistency / predictability in regards to the number of resulting chunks? (I.e. skip empty chunks, gather all non-empty ones together).

### Expected behavior

```py
pl.concat(frames, rechunk=False).n_chunks()
  ==
max(1, sum(len(f) != 0 for f in frames))
```

### Installed versions

<details>
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:33:12) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.24.4
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

</details>

**Comment by orlp** [comment]
This is a fairly trivial fix. There's no reason to keep empty chunks around.
