### ISSUE TITLE
`.with_columns_seq()` doesn't recognize transformations from prior steps

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#11570]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars import col

(
    pl.DataFrame({"x": [1, 1, 1]})
    .with_columns_seq(
        col("x") * 2,
        (col("x") * 2).alias("double_x")
    )
)
```

```
shape: (3, 2)
┌─────┬──────────┐
│ x   ┆ double_x │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 2   ┆ 2        │
│ 2   ┆ 2        │
│ 2   ┆ 2        │
└─────┴──────────┘
```

### Issue description

I might just be missing the point of `.with_columns_seq()`, but shouldn't the expressions build on each other?

`.with_columns()` naturally doesn't allow this, but I'm not entirely sure the point of `.with_columns_seq()` if this type of example doesn't work.

### Expected behavior

This is the output I expected.

```
shape: (3, 2)
┌─────┬──────────┐
│ x   ┆ double_x │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 2   ┆ 4        │
│ 2   ┆ 4        │
│ 2   ┆ 4        │
└─────┴──────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.8.0
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by c-peters** [comment]
`with_columns_seq` runs the expressions sequentially instead of in parallel. It does not assign the results expression by expression, but constructs the new `DataFrame` after all expressions have been computed. To achieve the desired results, you can chain the `with_columns` / `with_columns_seq` calls

```
import polars as pl
from polars import col

(
    pl.DataFrame({"x": [1, 1, 1]})
    .with_columns(
        (col("x") * 2).alias("x")
    ).with_columns(
        (col("x") * 2).alias("double_x")
    )
)
```

**Comment by markfairbanks** [comment]
What is the advantage/point of `_seq`? As far as I can tell it’s just `with_columns` but slower?

**Comment by cmdlineluser** [comment]
@markfairbanks I recall it was created in response to https://github.com/pola-rs/polars/issues/10316

I think the TL;DR is it was for a specific case with small datasets where the overhead/cost of enabling parallelization was too much.

**Comment by markfairbanks** [comment]
Gotcha. I'm going to close this because it looks like the docs are trying to explain that and I just misunderstood them 🤷‍♂️

**Comment by uditrana** [comment]
I came to github to file the same issue as this! 

Would converting assigning results by expression incure significantyl more overhead? My company has started using Polars a lot recently, and I'm seeing a lot of really long chained `with_columns().with_columns().with_columns()...` that would look so much cleaner under one big "with_columns_seq()` where the expressions can build on each other. 

Would there ever be consideration to adding this feature as a flag or a separate `with_columns` variant?

**Comment by tomicapretto** [comment]
I also came here for the same reason as @uditrana, it would be very good to be able to do all in a single call. In the case I'm working now, I end up using 5 chained `with_columns`, and what's funny, is that one of them is only for a single transformation haha.
