### ISSUE TITLE
Unsafe code in GroupsProxy::take_groups_last

### ISSUE THREAD

**Issue by Mibu287** [pola-rs/polars#11584]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

At [Line 378 - proxy.rs](https://github.com/pola-rs/polars/blob/c01d599d0439923857aa9c2cd90a6228e24dab9c/crates/polars-core/src/frame/group_by/proxy.rs#L378), `get_unchecked` is called on each element vector of `GroupsIdx.all` with the safety argument "_idx has at least one eletment, so -1 is always in bounds_". However, this argument is not always true, `GroupsIdx.all` can contains empty vectors. For example:

```rust
use polars::{
    prelude::{NamedFrom, PolarsTemporalGroupby},
    time::{ClosedWindow, Duration, RollingGroupOptions},
};

fn main() {
    let df = polars::df!(
        "Event" => &["Rain", "Sun", "Rain", "Sun", "Rain", "Sun"],
        "Date" => &[1, 1, 3, 3, 2, 2]
    )
    .unwrap()
    .sort(&["Date"], vec![false], false)
    .unwrap();

    let (_, _, groups) = df
        .group_by_rolling(
            vec![df.column("Event").unwrap().clone()],
            &RollingGroupOptions {
                index_column: "Date".into(),
                period: Duration::parse("2i"),
                offset: Duration::parse("-2i"),
                closed_window: ClosedWindow::Left,
                check_sorted: false,
            },
        )
        .unwrap();

    println!("{:?}", groups);
}
```

### Log output

```shell
Idx(GroupsIdx { sorted: false, first: [0, 0, 0, 1, 1, 1], all: [[], [0], [0, 2], [], [1], [1, 3]] })
```

### Issue description

The only call sites of the method is in file "crates/polars-ops/src/series/ops/is_last_distinct.rs". By reading that file, I can see that it's not a bug per-se. However, as we are programming in Rust, no safety issue should be ignored.

Suggested fix: Rewrite `GroupsProxy::take_groups_last` method as a private function in file `is_last_distinct.rs` ==> Its safety argument can be easily verified. I am happy to make a PR if you want.

### Expected behavior

N/A

### Installed versions

<details>

default

</details>

**Comment by ritchie46** [comment]
We should mark the function as `unsafe`. As we call this when we uphold that invariant.
