### ISSUE TITLE
polars.abi3.so file size has increased in the last few versions

### ISSUE THREAD

**Issue by armenak-baburyan** [pola-rs/polars#11599]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```bash
for VERSION in 0.19.7 0.19.6 0.19.5 0.19.3 0.19.2 0.19.1 0.19.0; do echo -n "$VERSION  --> " && docker run --rm python:3.11-slim bash -c "pip install --quiet --root-user-action=ignore polars==$VERSION && ls -lah /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so"; done
```

### Log output

```shell
0.19.7  --> -rwxr-xr-x 1 root root 85M Oct  8 22:40 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.6  --> -rwxr-xr-x 1 root root 85M Oct  8 22:40 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.5  --> -rwxr-xr-x 1 root root 64M Oct  8 22:40 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.3  --> -rwxr-xr-x 1 root root 57M Oct  8 22:41 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.2  --> -rwxr-xr-x 1 root root 56M Oct  8 22:41 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.1  --> -rwxr-xr-x 1 root root 56M Oct  8 22:41 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
0.19.0  --> -rwxr-xr-x 1 root root 56M Oct  8 22:41 /usr/local/lib/python3.11/site-packages/polars/polars.abi3.so
```

### Issue description

I'm not sure if this is a bug or not, but I noticed that the installed package size has increased in the last few versions. The file `polars.abi3.so` has increased in size from 56 MB to 85 MB.

### Expected behavior

I expect a smaller file size.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-5.4.0-156-generic-x86_64-with-glibc2.36
Python:              3.11.5 (main, Sep  7 2023, 12:46:15) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
It's not a bug. We have vendored some dependencies on the Rust side. The increased file size is expected.

However, we are monitoring this and the compilation times and are looking to make improvements where possible.

**Comment by lmmx** [comment]
Just to share an update to my previous comment, I think the result I achieved was actually quite good and might be worth considering to help either for users or as part of the dev process (but maybe controversial)?

![Screenshot from 2023-12-01 12-58-33](https://github.com/pola-rs/polars/assets/2979452/c8fd2887-8d00-4fb9-bf51-d87e20888c57)

> Left: polars after UPX-compression, right: polars before UPX compression (but built from source with size optimisations)

I don't know if the official wheels would consider doing this in the build process to reduce package size... It does impact the file size reduction when zipped (the zip algorithm doesn't compress already compressed things as much). Happy to share more details of my build process if it's helpful.

You can basically achieve the same result by just pointing `upx --best` at the `polars.abi3.so` to reduce it from 57.3MB to 18.9MB (I found `--lzma` always breaks it). I think I've covered the essential functionality in tests (but running an actual test suite would be better).

**Comment by ritchie46** [comment]
> Edit to clarify: I was referring above to the combined size of polars[pyarrow] [and thus with NumPy], and I have now managed to squeeze it all in! Still would love to see attention on shrinking the ABI .so size back down 😃

Polars runs without any numpy or pyarrow requirement. Pyarrow especially is huge and is an optional dependency to give you interop with arrow. It is not required to run polars.

> It's not a bug. We have vendored some dependencies on the Rust side. The increased file size is expected.

Vendoring isn't the cause for our increase. Without vendoring we still compile the logic in our static binary, so that doesn't change anything. The increase is cause because we included an async runtime (tokio) so that we can process cloud datasets async. 

The vendoring will actually decrease our code size, as we can remove stuff we don't use.

**Comment by Ana0112** [comment]
@lmmx hey is it possible to share the steps u followed to installed a smaller size polars.

I need to use it in aws lambda. So far tried building from source but the size is large.

I followed this approach to install polars 
[https://github.com/pola-rs/polars/issues/10916](url)

**Comment by MarcoGorelli** [comment]
I'm using Polars in AWS lambda and it works great. The limit there is 250 MB, and Polars fits comfortably in it. In fact, even Polars + 2 plugins + fsspec + s3fs fits comfortably in it

For anyone struggling to include Polars, my first suggestion would be to check that you're not accidentally pulling Pyarrow / pandas / numpy in

![Screenshot 2024-04-18 124557](https://github.com/pola-rs/polars/assets/33491632/988ba292-a227-4a3b-bb6d-b8b52572f132)

**Comment by twoertwein** [comment]
It could be nice to document which feature flags increase the size a lot. Then people can better decide if it is worth for them to compile polars from scratch. polars.abi3.so is now at 100MB.

> The increase is cause because we included an async runtime (tokio) so that we can process cloud datasets async.

If there is enough demand, it might be worth having a cloudless-polars package on pypi?

**Comment by Don-Burns** [comment]
> I'm using Polars in AWS lambda and it works great. The limit there is 250 MB, and Polars fits comfortably in it. In fact, even Polars + 2 plugins + fsspec + s3fs fits comfortably in it
> 
> For anyone struggling to include Polars, my first suggestion would be to check that you're not accidentally pulling Pyarrow / pandas / numpy in
> 
> ![Screenshot 2024-04-18 124557](https://github.com/pola-rs/polars/assets/33491632/988ba292-a227-4a3b-bb6d-b8b52572f132)

Sadly looks like this has grown quite a bit, now at the point where I can't update to latest polars ver as the jump from 1.36.1 -> 1.38.0 looks to be ~30mb uncompressed for lambdas. This is without any extras, just `pip install polars` for python 3.11

```
 ↳ du -h -d 2 .
165M    ./polars_1_38_0/polars_runtime_32-1.38.0
4.5M    ./polars_1_38_0/polars-1.38.0
169M    ./polars_1_38_0
137M    ./polars_1_36_1/polars_runtime_32-1.36.1
4.5M    ./polars_1_36_1/polars-1.36.1
141M    ./polars_1_36_1
```

script to replicate on python 3.11
```sh
pip download polars==1.36.1 --dest ./polars_1_36_1
pip download polars==1.38.0 --dest ./polars_1_38_0
cd polars_1_36_1 && wheel unpack polars_runtime_32-1.36.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && wheel unpack polars-1.36.1-py3-none-any.whl
cd ../polars_1_38_0 && wheel unpack polars_runtime_32-1.38.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && wheel unpack polars-1.38.0-py3-none-any.whl
cd ..
rm **/*.whl # remove wheels since packages are unpacked
du -h -d 2 .
```

I understand it is not the goal of the project, but if it could be kept ~100mb would greatly increase usability with lambda without needing to work on containers etc. IMO

**Comment by renre-Jonathan-Dowling** [comment]
The move to polars 1.40.1 increased size again to 201 Mb

201M	./polars_1_40_1/polars_runtime_32-1.40.1
4.5M	./polars_1_40_1/polars-1.40.1
205M	./polars_1_40_1
