### ISSUE TITLE
interpolate preserves datatype - should it return Float instead for method='linear'?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11595]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [29]: pl.DataFrame({'a': [1, None, 2, None, 3]}).select(pl.col('a').interpolate(method='linear'))
Out[29]:
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
│ 2   │
│ 2   │
│ 3   │
└─────┘
```

### Issue description

`interpolate` preserves the data type - should it return `Float*` instead, at least for `method='linear'`?

for reference, `numpy.interpolate` would return float, even if the interpolated values were integers:
```python
In [30]: x = np.array([1,2,4])

In [31]: y = np.array([1,2,4])

In [32]: np.interp(np.array([1,2,3,4]), x, y)
Out[32]: array([1., 2., 3., 4.])
```

### Expected behavior

```python
In [29]: pl.DataFrame({'a': [1, None, 2, None, 3]}).select(pl.col('a').interpolate(method='linear'))
Out[29]:
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ 1.5 │
│ 2.0 │
│ 2.5 │
│ 3.0 │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.1
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             12.0.1
pydantic:            2.0.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
There are more issues here. `DataFrame.interpolate` and `LazyFrame.interpolate` lack the method option, and always use linear. `Series.interpolate` and `Expr.interpolate` have a "nearest" method option as well...

...but honestly, is 'nearest' even interpolation? Shouldn't that just be a method option for `fill_null` instead?

**Comment by orlp** [comment]
I would personally be in favor of deprecating the method argument for `interpolate`, moving `nearest` to `fill_null` and always returning floats from `interpolate`.

**Comment by ritchie46** [comment]
I do want to keep the `method` as we can extend with cubic/quadratic in the future. I do agree we must return floats. 

Moving `nearest` to `fill_null` makes sense to me.

**Comment by deanm0000** [comment]
Shouldn't there be some means of specifying how ties are handled? It looks like right now if there's a null in between 2 non-nulls that it takes the next value but it maybe preferable to take the previous value. What about having "nearest-back" and "nearest-forward" so the user has to decide what to do in a tie.

**Comment by stinodego** [comment]
The bug has been addressed, but some good API change considerations have been raised in this issue. So I am repurposing it as an enhancement proposal.

**Comment by stinodego** [comment]
> Shouldn't there be some means of specifying how ties are handled? It looks like right now if there's a null in between 2 non-nulls that it takes the next value but it maybe preferable to take the previous value. What about having "nearest-back" and "nearest-forward" so the user has to decide what to do in a tie.

This makes sense. I am closing this issue, but feel free to open an issue for this.

**Comment by stinodego** [comment]
Regarding removing the `nearest` strategy and moving it to `fill_null`:

There is something to be said for it, but `nearest` is also present in the interpolation options for `quantile`.

"nearest" may not technically be interpolation, but it is definitely useful. I don't see a strong need to change this right now. If someone feels differently, a new issue on this is welcome.
