### ISSUE TITLE
refactor(py-polars): remove `#pyo3(signature...`'s

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#11614]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

in py-polars, I noticed quite a lot of `#[pyo3(signature = ...`s. [reference guide](https://pyo3.rs/main/function/signature).

Example: `PyDataFrame.read_parquet`) has this signature.
But sometimes even methods without this are exposed to python after all (example: `pl.scan_csv`).

I'm just wondering if it wouldn't be better to annotate it with `#[pyfunction]` and `#[pyclass]` and let pyo3 handle the rest? Because in nearly all situations, it's just a reiteration of the functions attributes. Only in some minor circumstances there are defaults added. These should be kept of course.

What my proposal would be under this ticket is to clean up the default signatures that are generated by pyo3 anyhow.
This would greatly reduce the code duplication between the annotation and the function definition.

### Installed versions

<details>

```
main branch
```

</details>

**Comment by stinodego** [comment]
I think they are there to appease `clippy`. If you can find a cleaner way to do this, I think that would be welcome.

**Comment by ritchie46** [comment]
They are required to compile as we use `Option` as a required argument whereas pyo3 sees that differently.

**Comment by svaningelgem** [comment]
> They are required to compile as we use `Option` as a required argument whereas pyo3 sees that differently.

Please check the PR. I don't think it's necessary for pyo3 nor compilation. I just had to add a parameter into a `clippy.toml` toml file to silence the warnings...

**Comment by ritchie46** [comment]
The PR is about too many arguments, not pyo3? Or am I looking at the wrong place?

**Comment by svaningelgem** [comment]
Sorry, I'm mixing stuff :(

> They are required to compile as we use `Option` as a required argument whereas pyo3 sees that differently.

pyo3 assignes a None by default to an option, thus making it an optional argument.

As @stinodego pointed out in another message: we want polars to be in the driving seat, so when passing arguments from python to polars, polars should decide the defaults imho. Hence, to me it seems thus logical that any non-critical argument could be a None value.
Unless we want "None" to be a valid value of course. However, I don't know polars enough if that's the case (I don't think I saw one, but I leave that up to your judgement).

Just my 2ct :)
