### ISSUE TITLE
Consider adding a new `.name` expression namespace

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#11639]
## Description

Had a chat with @stinodego for this one to see if there's something here; it passed the first sanity-check, so looking for some additional input/thoughts now ;)

We currently have several expressions that modify the output _names_ of their parent, rather than modifying the _data_ associated with them. We could consolidate these, help make it clear that they operate on the expression names, and offer a coherent place to put new functionality by introducing a new `.name` namespace.

## Initial proposal

Move the following into a dedicated `name` namespace:

* `keep_name()` → `.name.keep()`
* `map_alias()` → `.name.map()`
* `prefix()` → `.name.prefix()`
* `suffix()` → `.name.suffix()`

**Also**: shouldn't move `alias` into the new namespace - I see the namespace (arguably) as somewhere to put functionality that modifies/transforms existing names rather than _assigning_ names (though this distinction may be a bit thin). Probably more to the point it would be unnecessarily annoying for everyone for no real gain 😅 

## Subsequently

This move into `.name` could be followed by adding conveniences such as `to_lowercase`, `to_uppercase`, `to_titlecase`, etc (which could then exist as first-class citizens in Rust, rather than needing to use a `map_alias` call back into Python).  

(Note that there are also versions of these in the `str` namespace that operate on the underlying data - having a dedicated `name` namespace would cleanly disambiguate usage intended to modify names from usage intended to modify data).

## Some examples
```python
cs.all().name.to_lowercase()
cs.numeric().name.suffix("_num")
pl.col("^.*urgent.*$").name.to_uppercase()
```

Thoughts, modifications, missing expressions?
(Certainly not a must-have feature, but potentially clean/useful 🤔)

**Comment by mkleinbort-ic** [comment]
Cosmetic suggestion call the namespace `alias`:

```python
pl.col('x').alias('good_x')
cs.all().alias.to_lowercase()
cs.numeric().alias.suffix("_num")
pl.col("^.*urgent.*$").alias.to_uppercase()
```

But not convinced this addresses a current pain-point (in my code at least).

**Comment by mcrumiller** [comment]
I prefer `name`, it's more straightforward that the computer sciencey-sounding `alias`. When performing a `select`, you're not really aliasing, you're assign a name:

```python
df.select(my_expr.alias("this is the name, not an alias"))
```

**Comment by mkleinbort-ic** [comment]
Ok, I admit, you have almost won me over. 
I think my concern is that `pl.col('Something').name` gives me "attribute" vibes, but I could get used to it as a namespace.

**Comment by stinodego** [comment]
This looks good - will help discoverability and help add more related functionality in a discoverable way. Has my blessing!

**Comment by alexander-beedie** [comment]
> This looks good - will help discoverability of existing methods and help add more related functionality in a discoverable way. Has my blessing!

Will get it done ✌️
