### ISSUE TITLE
Potentially missed supporting selectors in some additional frame methods in pull/10255

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#11635]
### Description

Looking at the work done in https://github.com/pola-rs/polars/pull/10255, it seems like adding selector functionality to `DataFrame.melt` and `LazyFrame.unnest` was either missed in the PR, or has reverted back to earlier functionality of just strings as column names.

This feature request is to add this functionality.

If this was intentional or there is any reason why they can't/shouldn't be added, please let me know.

I've checked the rest of the methods mentioned in that PR and they all (according to the current docs) accept selectors (or now expressions in the case of `explode`)

**Comment by alexander-beedie** [comment]
Ahh, I think there is a simple/innocent explanation here - the selector support weren't _removed_ from `DataFrame.melt` and `LazyFrame.unnest`, it was simply missed/overlooked the first time around 😅 I'll take a look and fix it tomorrow.

**Comment by henryharbeck** [comment]
I thought that may have been the case - just didn't want to assume, haha.
Thanks very much! 😄
