### ISSUE TITLE
Add .locate method as an affordance for filtering dataframes

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#11642]
### Description

I found the following method extremally convenient in my code:
```python
def _locate(df:pl.DataFrame, **kwargs)->pl.DataFrame:
    '''Used to quickly find rows via equality checks.
    
    Example:
    # This
    df.locate(year=2020, quarter=2, metric='Sales')
    
    # is equivalent to 
    df.filter(pl.col('year')==2020).filter(pl.col('quarter')==2).filter(pl.col('metric')=='Sales')
    '''
            
    df_ans = df.filter(pl.all_horizontal([pl.col(k)==v for k,v in kwargs.items()]))
    
    return df_ans

pl.DataFrame.locate = _locate
```

I usualy would not recommend these methods be added to polars, but I was showing a friend the library on a clean installation and realized how much I would miss it if it were gone.

It allows you to write code like this:

```python
# Get the SignOn events for user #9
df_selected = df.locate(userId=9, eventType='SignOn')

# Equivalent to 
df_selected = df.filter(pl.col('userId')==9 & pl.col('eventType')=='SignOn')

```
Incidentally it also supports expressions:

```python
# Get the most recent SignOn date for user #9
df_selected = df.locate(userId=9, eventType='SignOn',eventDate=pl.col('eventDate').max().over('userId','eventType'))   
```

Thoughts? Is the task of retrieving a subset of rows via a few columns common enough to merit a shorthand?

**Comment by MarcoGorelli** [comment]
> I was showing a friend the library on a clean installation and realized how much I would miss it if it were gone

😄 yeah I was also showing Polars to someone, who asked how they could do something like `df.loc[('a', 'b', 'c'), 'd']` from pandas (they had a multiindex), and I showed them `filter` + `col` and they said `uurrggh, that's so much more verbose`

I think this looks nice, but am also keen to avoid the "20 ways of doing the same thing" complaint that's often brought up against pandas

Will think about this one

**Comment by alexander-beedie** [comment]
I think the use of `**kwargs` syntax there actually works well; it meets the bar for being clear/obvious and descriptive, and we have previously had a positive response (in terms of readability/utility) to suitable/judicious use of `**kwargs` (in `with_columns`, for examples). 

One alternative suggestion - instead of having two separate methods, we should probably just allow `filter` to handle the `**kwargs` instead (much as we allow `select` and `with_columns` to handle a list of cols or a set of kwargs).

Then we avoid the problem of having multiple methods doing the same thing, and as we already do this elsewhere it's consistent (@MarcoGorelli, what would think of that approach?)

**Comment by mkleinbort-ic** [comment]
Indeed to all the above, I "made this" because I was porting a multi-index codebase from Pandas to polars and I needed some equivalent to avoid a major re-write.

**Comment by MarcoGorelli** [comment]
> we should probably just allow filter to handle the **kwargs instead

hmm nice!

from a quick attempt, this seems to work nicely:
```python
In [1]: df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]})

In [2]: df.filter(a=2, b=5)
Out[2]: 
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 5   │
└─────┴─────┘
```

I just did
```diff
diff --git a/py-polars/polars/dataframe/frame.py b/py-polars/polars/dataframe/frame.py
index dbf5e3977c..da2a65e10a 100644
--- a/py-polars/polars/dataframe/frame.py
+++ b/py-polars/polars/dataframe/frame.py
@@ -3898,7 +3898,8 @@ class DataFrame:
 
     def filter(
         self,
-        predicate: (Expr | str | Series | list[bool] | np.ndarray[Any, Any] | bool),
+        predicate: (Expr | str | Series | list[bool] | np.ndarray[Any, Any] | bool) = None,
+        **kwargs,
     ) -> DataFrame:
         """
         Filter the rows in the DataFrame based on a predicate expression.
@@ -3959,6 +3960,11 @@ class DataFrame:
         └─────┴─────┴─────┘
 
         """
+        if predicate is None and kwargs:
+            predicate = F.all_horizontal([F.col(k)==v for k,v in kwargs.items()])
+        else:
+            raise ValueError("Either `predicate` or `kwargs` should be provided")
+
```

**Comment by mkleinbort-ic** [comment]
A major pro of the "filter" approach, does this work?

```python
df.filter(a>=2, b<=5)
```

**Comment by mcrumiller** [comment]
> I think the use of **kwargs syntax there actually works rather well

This is a big improvement, but it's also still pretty verbose when you have to type out a lot of column names, especially if those have clunky column names. I don't want to clutter the API, but I was thinking of some way of doing the following:

```python
class PolarsFilter:
    _columns = []
    
    def __init__(columns):
        self._columns = columns

    def filter(values):
        return pl.all().filter(
            pl.all_horizontal(pl.col(k)==v for k,v in zip(_columns, values))
        )

df = pl.DataFrame(...)
pf= PolarsFilter("Name", "Age", "Birthdate")

df.select(pf.filter("Alex", 100, date(1923, 10, 10)) # happy 100th birthday!
```

**Comment by alexander-beedie** [comment]
> Not trying to fall into feature creep, but does the "filter" approach support more than equality?

Not right now, but it could if we were to tweak `filter` to make `predicate` a `*predicates` args instead, and also have `**named_constraints` (oin other words... pretty much exactly as we do in `with_columns` ;)

**Comment by mcrumiller** [comment]
> df.filter(a>=2, b<=5) # Does this work?

That's a python limitation most likely, it'll complain about `a` not being defined. Using `pl.col(a)>=2` could be made to work, but then it's starting to get a bit verbose again.

**Comment by alexander-beedie** [comment]
There are some additional (minor) advantages of `*predicates` vs `predicate`:

* Can easily splat a collection of predicates into `filter`.
* Don't have to think about operator precedence and parentheses.

**Comment by MarcoGorelli** [comment]
> df.filter( *predicates, **constraints)

not totally sure I follow (and if I do, I'm not sure it would be easier or more legible than filter + col), could you show an example syntax please?

**Comment by alexander-beedie** [comment]
> could you show an example syntax please?

```python
# just `*predicates`
df.filter( pl.col("a") >= 0, pl.col("b").is_not_null(), ~pl.col("").str.starts_with("!") )

# just `**constraints`
df.filter( x=0, y="xxx", z=date.today() )

# mix of `*predicates`, `**constraints`
df.filter(
    pl.col("dt").dt.quarter() > 2,
    value = 0,
    other = None,
)
```

**Comment by MarcoGorelli** [comment]
Yeah this looks great! OK I'd misunderstood then, I thought you were suggesting a way of using inequality constraints

I think this is plenty good enough already:
- use `.filter(x=0, y='xxx')` for a quick and ergonomic way of filtering `loc`-style
- `.filter(pl.col(...) ...)` for anything more complicated
- mix-and-match the above as you wish

**Comment by mkleinbort-ic** [comment]
Agreed, I love the syntax, you can imagine the possibilities:

```python
df.filter(pl.col('date') > pl.date(2020,1,1), userId = 5)
```
very ergonomic, much wow

**Comment by alexander-beedie** [comment]
Will finish this up shortly, but just for fun here's another interesting use-case for the upgraded `filter` that people may not have immediately spotted; using Pydantic / FastAPI model objects to easily filter against matching data  ;) 

```python
from pydantic import BaseModel
from datetime import date
import polars as pl

class DataModel(BaseModel):
    x: date
    y: str
    z: int
    
model_data = [
    DataModel( x=date.today(), y="aa", z=123 ),
    DataModel( x=date.today(), y="bb", z=456 ),
    DataModel( x=date.today(), y="cc", z=789 ),
]

df = pl.DataFrame( data=model_data )
print(
    df.filter( **model_data[1].model_dump() )
)
# shape: (1, 3)
# ┌────────────┬─────┬─────┐
# │ x          ┆ y   ┆ z   │
# │ ---        ┆ --- ┆ --- │
# │ date       ┆ str ┆ i64 │
# ╞════════════╪═════╪═════╡
# │ 2023-10-14 ┆ bb  ┆ 456 │
# └────────────┴─────┴─────┘
```
