### ISSUE TITLE
illegal hardware instruction in Mac OS with M1 chip (under Rosetta)

### ISSUE THREAD

**Issue by mushroomfire** [pola-rs/polars#11650]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pip install polars
import polars
```

### Log output

```shell
zsh: illegal hardware instruction.
BTW., if I use conda install -c conda-forge polars, I will obtain the segmentation faults when I try to use it.
```

### Issue description

The problem should be related to the M1 chip. I install polars-lts-cpu, i can import it and work well. But I really hope the polars can support Mac OS with M1 chip.
BTW., the system is MacOS 11.2.3.

### Expected behavior

It should work, just like in windows and ubuntu.

### Installed versions

<details>

```
0.19.7
```

</details>

**Comment by cmdlineluser** [comment]
Works OK on an M1 chip here (albeit with Mac OS 12.x)
```python
pl.show_versions()
# --------Version info---------
# Polars:              0.19.8
# Index type:          UInt32
# Platform:            macOS-12.6.7-arm64-arm-64bit
# Python:              3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]
```

**Comment by orlp** [comment]
Could you please provide the full output from `pl.show_versions()` (through `polars-lts-cpu`)?

**Comment by alexander-beedie** [comment]
Ahh, I think I probably have an explanation for this (and a potential fix, here: https://github.com/pola-rs/polars/pull/11654).
@orlp: What do you think? 🤔

**Comment by mushroomfire** [comment]
Hi, @alexander-beedie @orlp 
Here is the output through polars-lts-cpu:
```bash
Python 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
>>> polars.show_versions()
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-10.16-x86_64-i386-64bit
Python:              3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.3
numpy:               1.24.3
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```
If need any information, please let me know.

**Comment by mushroomfire** [comment]
Here is the output from polars-0.19.8:
```bash
Python 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
zsh: illegal hardware instruction  python```

**Comment by alexander-beedie** [comment]
> Anaconda
> Platform: macOS-10.16-x86_64-i386-64bit
> Python: 3.8.0 (default, Nov  6 2019, 15:49:01) 

Ok, this is exactly what I suspected; is there a reason that you have to run an older version of Anaconda that doesn't have native Apple Silicon support? 

Your version of Python is running under the Rosetta translation layer, but Anaconda has had native Apple Silicon support for quite a while now (since the `2022.05` [release](https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1). If it is possible for you, I'd _strongly_ advise updating to a more recent Anaconda/Python version with native Apple Silicon support ;)

(We can still fix the build to prevent the error, but you'll have a better experience in general if you run natively-optimised binaries instead).

**Comment by orlp** [comment]
Closed in favor of https://github.com/pola-rs/polars/issues/11658. If you must use polars under Rosetta Python, install `polars-lts-cpu` instead.

**Comment by mushroomfire** [comment]
I have installed the arm anaconda and I can use polars now. Thanks a lot.
