### ISSUE TITLE
Missing implementation of set_symmetric_difference

### ISSUE THREAD

**Issue by ArturKotAllegro** [pola-rs/polars#11665]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

[Example from docs](https://pola-rs.github.io/polars/docs/python/version/0.18/reference/expressions/api/polars.Expr.list.set_symmetric_difference.html#polars.Expr.list.set_symmetric_difference)
```python

df = pl.DataFrame(
    {
        "a": [[1, 2, 3], [], [None, 3], [5, 6, 7]],
        "b": [[2, 3, 4], [3], [3, 4, None], [6, 8]],
    }
)
df.with_columns(
    pl.col("b").list.set_symmetric_difference("a").alias("sdiff")
)
```

### Log output

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 8
      1 df = pl.DataFrame(
      2     {
      3         "a": [[1, 2, 3], [], [None, 3], [5, 6, 7]],
      4         "b": [[2, 3, 4], [3], [3, 4, None], [6, 8]],
      5     }
      6 )
      7 df.with_columns(
----> 8     pl.col("b").list.set_symmetric_difference("a").alias("sdiff")
      9 )

AttributeError: 'ExprListNameSpace' object has no attribute 'set_symmetric_difference'
```

### Issue description

Hello,
Seems like documentation points to the non-existent method.

Both in MacOS (m1 macbook pro) and Debian, both installed via pip with-in miniconda enviroment.

### Expected behavior

As in example from documentation:
```python
shape: (4, 3)
┌───────────┬──────────────┬───────────┐
│ a         ┆ b            ┆ sdiff     │
│ ---       ┆ ---          ┆ ---       │
│ list[i64] ┆ list[i64]    ┆ list[i64] │
╞═══════════╪══════════════╪═══════════╡
│ [1, 2, 3] ┆ [2, 3, 4]    ┆ [4, 1]    │
│ []        ┆ [3]          ┆ [3]       │
│ [null, 3] ┆ [3, 4, null] ┆ [4]       │
│ [5, 6, 7] ┆ [6, 8]       ┆ [8, 5, 7] │
└───────────┴──────────────┴───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
Python:      3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
I think you are just on a (relatively) old version of polars there; the given method name has been `set_symmetric_difference` for a while. Note that we have only recently added (major) versioning of the docs, so some of the recent method name updates have not been captured. If you update polars you'll find that the method name and docs line-up correctly 👍

**Comment by ArturKotAllegro** [comment]
Unfortunately, I couldn't update to 0.19.0 on python 3.7 as 0.18.4 is the most recent update for 3.7. 

But true, on polars==0.19.0 and python 3.8 works like a charm.

Thanks a lot for Your help.
