### ISSUE TITLE
Inexact number comparison in DataFrame.frame_equal

### ISSUE THREAD

**Issue by tversteeg** [pola-rs/polars#1167]
In pandas [`assert_frame_equals`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html) has the `check_exact` flag which allows for inexact number comparisons with tolerances defined by the `rtol` (relative tolerance) and `atol` (absolute tolerance). This would be nice to have in polars as well, since it allows for ignoring floating point rounding errors.

**Comment by ritchie46** [comment]
Yes.. a special assert function is probably better. Then we can also pretty print in case of false evaluation.

**Comment by ghuls** [comment]
https://docs.rs/float_eq/0.6.1/float_eq/ might help.

**Comment by ghuls** [comment]
https://docs.rs/float_eq/0.6.1/float_eq/ might help.

**Comment by ghuls** [comment]
https://docs.rs/float_eq/0.6.1/float_eq/ might help.

**Comment by ghuls** [comment]
https://docs.rs/float_eq/0.6.1/float_eq/ might help.

**Comment by ritchie46** [comment]
> https://docs.rs/float_eq/0.6.1/float_eq/ might help.

I would not want to implement this in Rust to keep the compile times in check.

In python we could write this check. I think a `assert_equal` function similar to pandas might be welcome. This could also prettty print the difference in case of a false assertion.

On the float equal, we could do something like this:

```python
(col("a") - col("b")).abs() <= (atol + rtol * col("b").abs())
```

**Comment by evbo** [comment]
While not perfect, if you need basic dataframe comparison the string format does some useful rounding. But of course you won't be able to control the tolerance I don't think:

```rust
assert_eq!(df.to_string(), expected_df.to_string());
```
