### ISSUE TITLE
Include Support for Asynchronous Database Driver 

### ISSUE THREAD

**Issue by barmanroys** [pola-rs/polars#11676]
This request is a result of this [stackoverflow question](https://stackoverflow.com/questions/77166897/how-to-form-a-polars-dataframe-from-sql-alchemy-asynchronous-query-result) as I am facing this same error. 

Basically, it seems polars is not yet compatible with aiomysql driver and AsyncSession in SQLAlchemy. So it cannot query the database in an asynchronous manner. 

Given the emergence of asynchronous workflows in python, I believe it is a necessary addition.

**Comment by WilliamStam** [comment]
add another request for this. performance is heavily hit when querying using sqlalchemy and then after that turning it to a dataframe.

**Comment by alexander-beedie** [comment]
This was closed by https://github.com/pola-rs/polars/pull/15162 👌
