### ISSUE TITLE
`DataFrame.update` is ignored is edge case

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11684]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

(
    pl.DataFrame({'a': [0,1]})
    .update(pl.DataFrame({'a': [2,3]}), on = 'a', how='outer')
)
#shape: (2, 1)
#┌─────┐
#│ a   │
#│ --- │
#│ i64 │
#╞═════╡
#│ 0   │
#│ 1   │
#└─────┘


```

### Issue description

The update fonction is totally ignored in this case, this should not be the case. If you had other columns in the dataframe the bug disappear  

### Expected behavior

```
#shape: (2, 1)
#┌─────┐
#│ a   │
#│ --- │
#│ i64 │
#╞═════╡
#│ 0   │
#│ 1   │
#│ 2   │
#│ 3   │
#└─────┘


```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.6
Index type:          UInt32
Platform:            Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.1.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.1
openpyxl:            <not installed>
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.41
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Hmm... "outer" isn't actually supposed to be supported at all here; the bug is letting that get through without raising an error - `update` should only take "inner" and "left" 😅

**Comment by gab23r** [comment]
Would make given the name of the function, I ended up using it in outer as a fast way to update existing + create new (insert/upsert at the same time)

**Comment by alexander-beedie** [comment]
Yup; already got `outer` working locally; will add some tests and commit shortly.

**Comment by cmdlineluser** [comment]
Just while experimenting with the given example, I noticed other join strategies are also allowed:
```python
df1.update(df2, how='cross')

# shape: (9, 3)
# ┌─────┬──────┬──────────────────────────────────┐
# │ a   ┆ b    ┆ __POLARS_ROW_COUNT__POLARS_RIGHT │
# │ --- ┆ ---  ┆ ---                              │
# │ i64 ┆ i64  ┆ u32                              │
# ╞═════╪══════╪══════════════════════════════════╡
# │ 1   ┆ 4    ┆ 0                                │
# │ 1   ┆ 5    ┆ 1                                │
# │ 1   ┆ 4    ┆ 2                                │
# │ 2   ┆ null ┆ 0                                │
# │ 2   ┆ 5    ┆ 1                                │
# │ 2   ┆ null ┆ 2                                │
# │ 3   ┆ null ┆ 0                                │
# │ 3   ┆ 5    ┆ 1                                │
# │ 3   ┆ null ┆ 2                                │
# └─────┴──────┴──────────────────────────────────┘
```
`semi` and `anti` produce `ColumnNotFound` exceptions.

Perhaps they need to be disallowed.

**Comment by alexander-beedie** [comment]
> Just while experimenting with the given example, I noticed other join strategies are also allowed:

Argh; I literally disallowed every other flavour of join on my branch as the last thing I did, but didn't push it into the PR... Thanks for spotting this! Fixed...😎👍
