### ISSUE TITLE
Add median to the output of `df.describe()` method

### ISSUE THREAD

**Issue by AltaherPresto** [pola-rs/polars#11691]
### Description

It would be nice to have the `median` also included in the output of the `df.describe()` method.
Data analysts often prioritize the median over the mean because it's less susceptible to distortion by outlier values.

relevant docs: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.describe.html#polars.DataFrame.describe

![image](https://github.com/pola-rs/polars/assets/92849024/9f47be1b-df6c-40f7-b267-b6e97745444b)

**Comment by alexander-beedie** [comment]
Median is already there; it's the [50% quantile](https://support.speedcurve.com/docs/average-median-percentiles#50th-percentile-median) shown in the table ;)

**Comment by AltaherPresto** [comment]
@alexander-beedie 
thanks for the info

can the describe() method be expanded to at least match the `descriptive statistics` function in Excel?

thanks again

![image](https://github.com/pola-rs/polars/assets/92849024/7510afe1-5265-4bd9-a7d8-730d0b176467)
