### ISSUE TITLE
docs(rust): SQL keywords page is not populated

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#11706]
### Description

When reading the documentation:
- [python](https://pola-rs.github.io/polars/user-guide/sql/select/#functions)
- [rust](https://pola-rs.github.io/polars/user-guide/sql/select/#join)

Context:
> For a full list of supported functions go the [API documentation](https://docs.rs/polars-sql/latest/src/polars_sql/keywords.rs.html). The example below demonstrates how to use a function in a query.

(both python & rust docs go to the same link)

This link however does not contain a list of keywords, but rather the code to generate the list.

However, from a documentation perspective I'd expect a list of keywords / functions.

I raise this FR to implement this (likely as an added step in the github workflow?).

**Comment by stinodego** [comment]
It doesn't deserve any beauty awards, but apparently that's the source code where the list of supported keywords is defined. So it's a nice way to make sure the list is complete.

I don't see anything wrong here?

**Comment by svaningelgem** [comment]
What I want to say with this ticket is that it at the least should generate the list and dump it into an html. Otherwise people reading the docs need to look through all the files to get the list. And to see what is, and what isn't supported.

wdyt?

**Comment by stinodego** [comment]
That's some CI pipeline overhead/complexity that I don't want right now. There's many other things that I want fixed first before considering something like that.

**Comment by svaningelgem** [comment]
Maybe you can give me a hint on how I could implement this? I'm willing to take up the challenge. And the functions are there, so I should be able to include them into a small dumper-function?

**Comment by stinodego** [comment]
It's not about the challenge of implementing it. I do not want this complexity in the CI pipeline right now.

**Comment by svaningelgem** [comment]
https://blog.codinghorror.com/the-broken-window-theory/
