### ISSUE TITLE
from_arrow() mixes up order of values and schema

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#11718]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import pyarrow as pa
import polars as pl

schema = {"b": float, "a": int}
df_pd = pd.DataFrame({"a": [1, 2], "b": [1.5, 2.5]})

df_pa = pa.Table.from_pandas(df_pd)
print(df_pa)

df_pl = pl.from_arrow(data=df_pa, schema=schema)
print(df_pl)
```

### Issue description

The pandas dataframe has two columns: an integer in the "first" column, and a float in the "second column".

When I call the function `pl.from_arrow()`, the schema has to be in the same order as the columns even though it is a dictionary.

Specifically,`pl.from_arrow(data=df_pa, schema={"b": float, "a": int})` will continue to have the values from the first column "a" inserted in the first column now titled "b" with type float. The values from the second column "b" are still in the second column but now titled "a".

### Expected behavior

I expect the resulting table to be independent of the order in which I provide the dictionary. Specifically, I expect the output of `pl.from_arrow(data=df_pa, schema={"a": int, "b": float})`  and `pl.from_arrow(data=df_pa, schema={"b": float, "a": int})` to be the same.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.24.4
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None
```

</details>

**Comment by MariusMerkleQC** [comment]
@AdrianOchsQC @JakobEverdingQC @ThomasBlauthQC

**Comment by nameexhaustion** [comment]
The underlying issue behind this has to do with a much wider inconsistency around the API - see https://github.com/pola-rs/polars/issues/11632 for the details.

**Comment by stinodego** [comment]
The `schema` argument will take precedence over the original data. In this case, the behavior is expected.
