### ISSUE TITLE
Series.to_numpy fails with dtype=Null, but only if PyArrow is not installed

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#11729]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
series = pl.Series([], dtype=pl.Null)
series.to_numpy()
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/tabeline/.venv/lib/python3.11/site-packages/polars/series/series.py", line 4173, in to_numpy
    np_array = self._s.to_numpy()
               ^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: 'to_numpy' not supported for dtype: Null
```

### Issue description

`Series.to_numpy()` raises an exception when the `dtype` of the series is `Null`. However, this only happens when PyArrow is not installed. When PyArrow is installed, a different code path is taken so that an array with an `object` data type is returned. Because NumPy does not have a proper null data type, either behavior is defensible, but giving different behavior based on what else is installed makes debugging hard.

### Expected behavior

`Series.to_numpy` has the same behavior whether or not PyArrow is installed

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Python:              3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              1.5.3
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
>```

</details>

**Comment by ritchie46** [comment]
This is a good first issue. You must create a nan array in such a case.
