### ISSUE TITLE
Subtracting two columns of unsigned int results in unsigned int even when results could be negative.

### ISSUE THREAD

**Issue by blaylockbk** [pola-rs/polars#11721]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

(
    pl.DataFrame({"a": [1, 2, 3], "b": [3, 1, 5]})
    .cast(pl.UInt32)
    .with_columns((pl.col("a") - pl.col("b")).alias("a minus b"))
)

```
![image](https://github.com/pola-rs/polars/assets/6249613/d74e8d5f-f06a-4e34-a4d2-f0fafb62cf90)

This was on Polars 0.19.8

### Issue description

When subtracting two columns of type unsigned integer, the resulting column is also an unsigned integer, and thus negative numbers are nonsense values. I came across this problem when trying to subtract two columns of "counts" from an aggregation. I guess I was caught off guard that the pl.count() aggregation returned an uint and not regular int. 

### Expected behavior

After thinking about it, I take it that this is the expected behavior, but I expected the resulting difference column to be cast to a signed integer so the value could be negative. Or, a warning to suggest something is wrong (because it would result in negative numbers). It is weird to me to see the large number in place of the negative number. 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            2.4.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ion-elgreco** [comment]
This has been brought up already a couple times, most recent here: https://github.com/pola-rs/polars/issues/11465

Maybe pick up the discussion there.

**Comment by blaylockbk** [comment]
Ah, thanks for pointing me to that. 😊 I'll close this because it's a duplicate.
