### ISSUE TITLE
Comparison with a pl.Serie (Int) and a float number

### ISSUE THREAD

**Issue by MathieuCayssol** [pola-rs/polars#11736]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
def comp_int_float(x):
    return x < 1.5

pl.DataFrame(
    {"a": [1,1,2,2]}
).select(
    comp_int_float(pl.col("a"))
)

comp_int_float(pl.Series([1,1,2,2]))
```

### Issue description

When I compare a Series with int values to a float (less than comparison), it returns the wrong result in Eager mode. The behavior using expression in a context is correct.

![Capture d’écran 2023-10-14 à 19 48 54](https://github.com/pola-rs/polars/assets/49449000/696333f6-6ef6-4e14-9e65-a0331997e937)

Is this an expected behavior? (e.g: in eager case, you have to cast the Serie to the correct type).

### Expected behavior

This one:

```python
def comp_int_float(x):
    return x < 1.5

pl.DataFrame(
    {"a": [1,1,2,2]}
).select(
    comp_int_float(pl.col("a"))
)
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-11.7.9-x86_64-i386-64bit
Python:              3.11.5 (main, Aug 24 2023, 15:23:14) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Here's a much simpler example:

```python
pl.Series([0, 1, 2, 3]) < 1.5
shape: (4,)      
Series: '' [bool]
[
        true     
        false    
        false    
        false    
]
```

**Comment by mcrumiller** [comment]
Here's a much simpler example:

```python
>>> pl.Series([0, 1, 2, 3]) < 1.5
shape: (4,)
Series: '' [bool]
[
        true
        false # this should be true
        false
        false
]
```

**Comment by mcrumiller** [comment]
It seems to be peppered everywhere than when performing a logical comparison such as `lhs` < `rhs`, the `rhs` is cast to the lhs type. This of course is changing `[0, 1, 2, 3] < 1.5` to `[0, 1, 2, 3] < `1`, since the 1.5 gets truncated to an int.

**Comment by MathieuCayssol** [comment]
Okay, make sense. In this case, we would expect:
```
pl.DataFrame(
    {"a": [1,1,2,2]}
).select(
    comp_int_float(pl.col("a"))
)
```
to have the same behavior

**Comment by mcrumiller** [comment]
Actually no, this is happening on the python side. Give me a few.
