### ISSUE TITLE
`duration` doesn't handle subseconds correctly

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#11747]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.select(pl.duration(seconds=1, microseconds=1000, time_unit='ms'))
```
```
shape: (1, 1)
┌──────────────┐
│ duration     │
│ ---          │
│ duration[ms] │
╞══════════════╡
│ 1s           │
└──────────────┘
```

### Issue description

When `time_unit` is milliseconds, all nanosecond/microsecond information is lost.
When `time_unit` is microseconds, all nanosecond information is lost.

### Expected behavior

Information should be preserved.

### Installed versions

main branch

**Comment by MarcoGorelli** [comment]
> When time_unit is milliseconds, all nanosecond/microsecond information is lost.

How do you suggest that it be retained whilst respecting the user's given time unit? Not saying it can't be, I just don't currently see it

**Comment by stinodego** [comment]
> > When time_unit is milliseconds, all nanosecond/microsecond information is lost.
> 
> How do you suggest that it be retained whilst respecting the user's given time unit? Not saying it can't be, I just don't currently see it

I have a fix ready. Basically:
* if time unit is `us`, you add nanoseconds // 1_000
* if time unit is `ms`, you add microseconds // 1_000 and nanoseconds // 1_000_000
