### ISSUE TITLE
Add transpose method to dataframe

### ISSUE THREAD

**Issue by tversteeg** [pola-rs/polars#1176]
Similar to [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transpose.html).

**Comment by ritchie46** [comment]
```python
df = pl.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
print(df)

print(pl.DataFrame(df.rows()))
```
```
shape: (2, 2)
╭──────┬──────╮
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 1    ┆ 3    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2    ┆ 4    │
╰──────┴──────╯
shape: (2, 2)
╭──────────┬──────────╮
│ column_0 ┆ column_1 │
│ ---      ┆ ---      │
│ i64      ┆ i64      │
╞══════════╪══════════╡
│ 1        ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3        ┆ 4        │
╰──────────┴──────────╯
```

**Comment by tversteeg** [comment]
Thanks! Would it make sense to create an alias for that function called `transpose`? If not it might be a good idea to add the keyword "transpose" in the description somewhere of `rows` so searching it yields it.

**Comment by ritchie46** [comment]
Yes, will add the alias. :+1:

**Comment by alippai** [comment]
@ritchie46 I'm wondering whether it would make sense to introduce a lazy transpose - skipping the extra allocation (turning it into an iterator) if there is a subsequent operation

**Comment by ritchie46** [comment]
Now that I think of it. I will support this natively, as going to python rows is super expensive.

> @ritchie46 I'm wondering whether it would make sense to introduce a lazy transpose - skipping the extra allocation (turning it into an iterator) if there is a subsequent operation. Edit: this might fit ndarray more, eg it could optimize DF * DF.transpose()

@alippai Currently these operation sadly cannot be done in lazy. I need to know the schema of every node in the query plan. An operation like `pivot`, and `transpose` create the schema based on the data (which is unknown at that point).

**Comment by alippai** [comment]
Makes sense, I really appreciate the implementation detail!

**Comment by jorgecarleitao** [comment]
fwiw, spark supports it (lazily), but it is a shotgun shot to the foot, as it performs two queries, one of them to compute the distincts _during planning_.

**Comment by alippai** [comment]
Just to get the complexity of the task: an n x m sized 2D single type (int/float) specialization of the DF type would be needed for this, right?

**Comment by ritchie46** [comment]
> fwiw, spark supports it (lazily), but it is a shotgun shot to the foot, as it performs two queries, one of them to compute the distincts during planning.

Ouch.. that's definitely a shotgun.

In such I cases, I'd rather have a user doing something like this, and document why'd they want this:

```python
temp = long_query().transpose().collect()

(temp.lazy()
 .select(..)   # continue from here.
 )
```

**Comment by ritchie46** [comment]
> Just to get the complexity of the task: an n x m sized 2D single type (int/float) specialization of the DF type would be needed for this, right?

For max performance I guess something like that. I am planning to use the `AnyValue` enums (these are enums around all possible dtypes). Then we can turn the `DataFrame` into rows. Infer the schema per row and read the rows as columns.

**Comment by ritchie46** [comment]
Added in 2fa53db88550d6f308ba4f4a9e7f93ed567647d6
