### ISSUE TITLE
`scan_parquet` throws irritation error message when readon from cloud storage without passing options

### ISSUE THREAD

**Issue by aberres** [pola-rs/polars#11777]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = (
    pl.scan_parquet(
        "gs://cloud-samples-data/bigquery/us-states/us-states.parquet",
        #storage_options={},
    )
    .select("*")
    .collect()
)
```

### Log output

```shell
File "/Users/armin/venv/weplan3.11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 428, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: configuration 'gcp' must be provided in order to use 'gs' cloud URLs
```

### Issue description

When using `scan_parquet` with a file from a Google bucket, an error message is thrown when not explicitly passing `storage_options={}` but omitting the parameter.

### Expected behavior

Passing an empty parameter like in the working example below is unnecessary.

```
import polars as pl

df = (
    pl.scan_parquet(
        "gs://cloud-samples-data/bigquery/us-states/us-states.parquet",
        storage_options={},
    )
    .select("*")
    .collect()
)
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-13.3-arm64-arm-64bit
Python:              3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]
```

</details>

**Comment by ritchie46** [comment]
You say that it works if you pass an empty storage options?

**Comment by aberres** [comment]
@ritchie46 Yes, exactly. I clarified the expected behavior above.

There is no configuration I want to pass as we are using application default credentials in notebooks and GKE workload identity for production workloads.

**Comment by Wouittone** [comment]
I just stumbled onto this issue as well, what seemed strange to me at first is that the `read_parquet` function functions as intended when no `storage_options` is passed:

```
%time pl.read_parquet("gs://cloud-samples-data/bigquery/us-states/us-states.parquet").head()
CPU times: user 6.86 ms, sys: 0 ns, total: 6.86 ms
Wall time: 270 ms
Out[6]:
shape: (5, 2)
┌────────────┬───────────┐
│ name       ┆ post_abbr │
│ ---        ┆ ---       │
│ str        ┆ str       │
╞════════════╪═══════════╡
│ Alabama    ┆ AL        │
│ Alaska     ┆ AK        │
│ Arizona    ┆ AZ        │
│ Arkansas   ┆ AR        │
│ California ┆ CA        │
└────────────┴───────────┘
```

**Comment by ritchie46** [comment]
@Wouittone the read_parquet uses another backend. We are in the process of moving all reading to our backend. So that `read_parquet` behaves differently is unrelated.
