### ISSUE TITLE
ComputeError when converting timezone-aware datetimes from Pandas or PyArrow

### ISSUE THREAD

**Issue by jeromedockes** [pola-rs/polars#11774]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

pds = pd.to_datetime(["2023-10-16T17:19:02+02:00"])
pl.from_pandas(pds) # exceptions.ComputeError
```

also

```python
import datetime
import pyarrow as pa
import polars as pl

d = datetime.datetime.strptime("2023-10-12T17:36:50+0200", "%Y-%m-%dT%H:%M:%S%z")
a = pa.array([d])
pl.from_arrow(a) # exceptions.ComputeError
```

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/timezone_example.py", line 5, in <module>
    pl.from_pandas(pds) # exceptions.ComputeError
    ^^^^^^^^^^^^^^^^^^^
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/convert.py", line 717, in from_pandas
    return pl.Series._from_pandas("", data, nan_to_null=nan_to_null)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/series/series.py", line 354, in _from_pandas
    pandas_to_pyseries(name, values, nan_to_null=nan_to_null)
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/utils/_construction.py", line 597, in pandas_to_pyseries
    return arrow_to_pyseries(
           ^^^^^^^^^^^^^^^^^^
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/utils/_construction.py", line 188, in arrow_to_pyseries
    pys = PySeries.from_arrow(name, array)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: unable to parse time zone: '+02:00'. Please check the Time Zone Database for a list of available time zones
```
```


### Issue description

converting from a pandas Series with fixed offset timezones raises an exception.
The same thing happens with pyarrow arrays

### Expected behavior

no exception

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Python:              3.11.5 (main, Aug 25 2023, 13:19:50) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.3
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by MarcoGorelli** [comment]
thanks @jeromedockes for the report

IMHO the bug is in pandas for setting `+02:00` as the time zone. It's ambiguous which time zone the given timestamp corresponds to. For example, `'2023-02-16T17:19:02+02:00'` could be both `'Europe/Sofia'` (which observes daylight saving time) or 'Africa/Cairo' (which doesn't observe daylight saving time)

I'd suggest not trying to guess for users and converting to UTC if they just pass a timestamp without specifying a time zone

Polars only supports time zones from the IANA time zone database - you can check
```
import zoneinfo
zoneinfo.available_timezones()
```
for a full list

**Comment by stinodego** [comment]
Possibly the error message could suggest to convert to UTC first?

**Comment by jeromedockes** [comment]
thanks for explaining! this makes a lot of sense; the [documentation](https://pola-rs.github.io/polars/user-guide/transformations/time-series/timezones/) on time zones could maybe state this more explicitly? It lists fixed offsets as "examples of valid time zones"

**Comment by stinodego** [comment]
> thanks for explaining! this makes a lot of sense; the [documentation](https://pola-rs.github.io/polars/user-guide/transformations/time-series/timezones/) on time zones could maybe state this more explicitly? It lists fixed offsets as "examples of valid time zones"

Good catch, this must be updated!
