### ISSUE TITLE
fix explode on lists with empty values

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#1177]
The explode is super cheap in current state. Only when the list has got empty lists, it is incorrect. Maybe store statistics for this, as the performance of explode is great as is and is used a lot in aggregation context.

**Comment by olivier-lacroix** [comment]
@ritchie46 , I see exploding empty lists currently removes the rows.

Is there a way to replace these? it seems literals of list (e.g. `pl.lit([-1])`) panics ?

**Comment by ritchie46** [comment]
Fixed in #1314

**Comment by ritchie46** [comment]
fixed and released
