### ISSUE TITLE
Allow `map_elements` to cache computed results

### ISSUE THREAD

**Issue by aberres** [pola-rs/polars#11775]
### Description

This is a follow-up to a discussion with @MarcoGorelli on [LinkedIn](https://www.linkedin.com/posts/marcogorelli_if-you-want-to-apply-a-really-custom-function-activity-7114670373480067072-AqZN).

@MarcoGorelli showed how using a pre-computed dict with `map_dict` can be much faster than using `map_elements`.

![image](https://github.com/pola-rs/polars/assets/20811121/41b15f7e-b03b-48ad-96ce-958295dfe22f)

The following question came to my mind: Wouldn't it be great if `map_elements` could (optionally) cache and reuse the results if a side-effect-free callable is passed (even if using `map_elements` is discouraged?

PS: I just noticed that the docs recommend using `@lru_cache` - I was naively expecting that the caching could happen on the Rust side. If this is a pure Python thing, feel free to close this issue right away.

**Comment by deanm0000** [comment]
If the function call is happening on the Python end then why would rust cache it? Seems like the desired feature is already documented @stinodego is this a close?
