### ISSUE TITLE
Error when mutating with cast + append expressions and "performant" feature is enabled

### ISSUE THREAD

**Issue by philss** [pola-rs/polars#11787]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let df = df!("a" => [Some(1), None, Some(3)], "b" => [20.0, 40.0, 60.0]).unwrap();

    let out = df
        .lazy()
        .with_columns([
            (col("a").cast(DataType::Float64).append(col("b"), false))
                .slice(1, 3)
                .alias("concat1"),
            (col("a") + col("b")).alias("add1"),
        ])
        .collect()
        .unwrap();

    println!("{}", out);
}
```

### Log output

```shell
Finished dev [unoptimized + debuginfo] target(s) in 13.98s
     Running `target/debug/polars_exprs_example`
run StackExec with 1 CSE
thread 'main' panicked at src/main.rs:15:10:
called `Result::unwrap()` on an `Err` value: ShapeMismatch(ErrString("unable to add a column of length 0 to a dataframe of height 3"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

When trying to explicitly cast a column before appending it to another column, and then having another column to be added in the same "with_columns", I get an error of `ShapeMismatch`. The curious thing is that this only happens when the "`performant`" feature is enabled, and there is another expression/column to add - if we remove that "col1" line, it works.

We got this when trying to upgrade from Polars v0.32 to v0.33.

After writing this down, I noticed that the log says that is running with "1 CSE". So I tried to disable the "common subexpression elimination optimization" and it works after that. Do you think disabling this optimization is the solution?

### Expected behavior

It should work with the "`performant`" feature enabled. The expected output is the following:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/polars_exprs_example`
run StackExec
shape: (3, 4)
┌──────┬──────┬─────────┬──────┐
│ a    ┆ b    ┆ concat1 ┆ add1 │
│ ---  ┆ ---  ┆ ---     ┆ ---  │
│ i32  ┆ f64  ┆ f64     ┆ f64  │
╞══════╪══════╪═════════╪══════╡
│ 1    ┆ 20.0 ┆ null    ┆ 21.0 │
│ null ┆ 40.0 ┆ 3.0     ┆ null │
│ 3    ┆ 60.0 ┆ 20.0    ┆ 63.0 │
└──────┴──────┴─────────┴──────┘
```

### Installed versions

<details>

"fmt", "lazy", "performant"

</details>

**Comment by ritchie46** [comment]
I believe we already fixed this on main, can you try if latest main fixes it for you?

**Comment by ritchie46** [comment]
I can run this on main.
