### ISSUE TITLE
Unexpected behavior when indexing with a slice and a specific column

### ISSUE THREAD

**Issue by neonlogic** [pola-rs/polars#11800]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
assert type(df[1:, "a"]) == pl.Series
```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Users\Xxx\test\test.py", line 3, in <module>
    assert type(df[1:, "a"]) == pl.Series
AssertionError
```

### Issue description

When I specify a column, I don't expect the result to still be a DataFrame.

### Expected behavior

I thought `df[1:, "a"]` would be equivalent to `df[1:]["a"]` and `df["a"][1:]`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by rjthoen** [comment]
This indeed looks like unintended behavior as a series is returned when a column is specified by location instead:

`import polars as pl
df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
type(df[1:, 1]`

Returns

`<class 'polars.series.series.Series'>`

**Comment by stinodego** [comment]
Agreed, this should result in a Series.
