### ISSUE TITLE
Inconsistent auto_explode for apply and apply_many

### ISSUE THREAD

**Issue by zhangyt26** [pola-rs/polars#11808]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    pub fn apply<F>(self, function: F, output_type: GetOutput) -> Self
    where
        F: Fn(Series) -> PolarsResult<Option<Series>> + 'static + Send + Sync,
    {
        let f = move |s: &mut [Series]| function(std::mem::take(&mut s[0]));

        Expr::AnonymousFunction {
            input: vec![self],
            function: SpecialEq::new(Arc::new(f)),
            output_type,
            options: FunctionOptions {
                collect_groups: ApplyOptions::ApplyGroups,
                fmt_str: "",
                ..Default::default()
            },
        }
    }

vs

    pub fn apply_many<F>(self, function: F, arguments: &[Expr], output_type: GetOutput) -> Self
    where
        F: Fn(&mut [Series]) -> PolarsResult<Option<Series>> + 'static + Send + Sync,
    {
        let mut input = vec![self];
        input.extend_from_slice(arguments);

        Expr::AnonymousFunction {
            input,
            function: SpecialEq::new(Arc::new(function)),
            output_type,
            options: FunctionOptions {
                collect_groups: ApplyOptions::ApplyGroups,
                fmt_str: "",
                auto_explode: true,
                ..Default::default()
            },
        }
    }
```

### Issue description

apply uses default, but apply_many has that true.
and dsl::apply_multiple makes that option available.

### Expected behavior

making auto_explode as an argument makes the most sense to me. 

I also found the comment confusing: https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/logical_plan/options.rs#L194

1. math is wrong on sum
2. head_1 is probably a bad example, I like head_2 so that it is at least showing more than one elements, that is different than sum

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by ritchie46** [comment]
> I agree that `auto-explode` should not be automatically set to `true`.

Sorry, I beat you to it. ;)
