### ISSUE TITLE
Streaming aggregation involving a List of Categorical column causes panic

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#11810]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    const ROW_COUNT: usize = 3;

    let numbers = Series::new("numbers", [1; ROW_COUNT]);

    let categoricals = Series::new("categoricals", vec![Series::new("list", ["str"; 2]); ROW_COUNT])
        .cast(&DataType::List(Box::new(DataType::Categorical(None)))).unwrap();

    let df = DataFrame::new(vec![numbers, categoricals]).unwrap();

    df.lazy()
        .with_streaming(true)
        .group_by(["numbers"])
        .agg([col("categoricals").first()])
        .collect()
        .unwrap();
}
```

### Log output

```shell
run UdfExec
RUN STREAMING PIPELINE
df -> primitive_group_by -> ordered_sink
RefCell { value: [] }
thread '<unnamed>' panicked at /Users/bytenybbler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-pipe-0.33.2/src/executors/sinks/group_by/mod.rs:54:40:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot construct Categorical from these categories; at least one of them is out of bounds"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

Inside the aggregation, using `col("categoricals")` instead of `col("categoricals").first()` will NOT cause this panic. This seems to be because the issue arises from within the `primitive_group_by` step.

### Expected behavior

This aggregation should not cause a panic inside Polars.

### Installed versions

<details>

polars = { version = "0.33.2", features = ["lazy", "dtype-categorical", "streaming"] }

</details>

**Comment by ByteNybbler** [comment]
Calling `polars::enable_string_cache()` before calling `collect` seems to prevent the panic.

This is because a Series cast occurs, turning `u32` into `cat`, and it attempts to call `CategoricalChunked::from_global_indices`. Without the string cache being enabled, the string cache is empty, and so the out-of-bounds check fails.

This seems closely related to #11792.

**Comment by ritchie46** [comment]
Fixed.
