### ISSUE TITLE
Streaming aggregation on Categorical List column panics when plan includes cast

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#11815]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let numbers = Series::new("numbers", [1]);
    
    let categoricals = Series::new("categoricals", vec![Series::new("list", ["str"; 1]); 1]);

    let df = DataFrame::new(vec![numbers, categoricals]).unwrap();

    df.lazy()
        .with_streaming(true)
        .with_columns([
            col("categoricals").cast(DataType::List(Box::new(DataType::Categorical(None))))
        ])
        .group_by(["numbers"])
        .agg([col("categoricals").first()])
        .collect()
        .unwrap();
}
```

### Log output

```shell
run UdfExec
RUN STREAMING PIPELINE
df -> hstack -> primitive_group_by -> ordered_sink
RefCell { value: [] }
thread '<unnamed>' panicked at /Users/bytenybbler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-pipe-0.33.2/src/executors/sinks/group_by/mod.rs:54:40:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot cast List inner type: 'UInt32' to Categorical"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

`physical_agg_to_logical` seems to attempt to convert `list[u32]` to `list[cat]` but fails.

This specific panic only seems to happen when the cast occurs during the query execution.

### Expected behavior

Polars should handle aggregating categorical lists without a panic.

### Installed versions

<details>

polars = { version = "0.33.2", features = ["lazy", "dtype-categorical", "streaming"] }

</details>

**Comment by ritchie46** [comment]
We shouldn't allow casting to categorical types without a global string cache here. The cast will create a local string cache for every batch, but then in a group_by operation the data from different batches is aggregated, but the information of the string-mappings and don't have to match.

Currently we only support local an global, but we should allow for enum types. That should solve this problem.
