### ISSUE TITLE
Add groupby in asof join

### ISSUE THREAD

**Issue by natemcintosh** [pola-rs/polars#1182]
# Add `by`, `left_by`, or `right_by` arguments to `asof` join. 

I love pandas `merge_asof()` and I was super excited to see `asof` join be added to polars! The ability to match up columns between the two dataframes and then perform the `asof` join is useful in many cases. If there is a way to do this without adding new features to `asof`, that works as well (although I have yet to figure out how to do it). 

Use cases:
- The pandas documentation uses the example of matching stock data on a ticker name
- At work, I very often need to join "truth" tables (what is actually happening in the simulation) to table of what the system believes is happening.
  - The truth table might contain info to the effect "Sensor A is seeing a cat and a dog at t=10.1", "Sensor B is seeing a horse and a dog at t=11.23"
  - The system table might contain info to the effect "We believe sensor A is seeing two dogs at t=12.3", "We believe sensor B is seeing a horse and a dog at t=11.4"

This is a low priority request

**Comment by ritchie46** [comment]
Hi @natemcintosh. Thanks for your interest. However, I don't really understand your request? You can already select the columns to join by.

**Comment by natemcintosh** [comment]
Hi @ritchie46, thanks for getting back to me! 

Sorry, I should have been more clear: specifying these (`by`, `left_by`, `right_by`) would perform a `groupby` on both input dataframes, and then perform the `asof` join on each matching group, joining on the `left_on` and `right_on` columns. 

The pandas [merge_asof](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html) docs have an example using the `by=...` argument on some stock data, grouping each stock by its ticker name. Grouping by the ticker name ensures, for example, that you don't join `MSFT` quotes to `AAPL` trades. 

Let me know if that doesn't make sense.

**Comment by ritchie46** [comment]
> The pandas merge_asof docs have an example using the by=... argument on some stock data, grouping each stock by its ticker name. Grouping by the ticker name ensures, for example, that you don't join MSFT quotes to AAPL trades.

Hmm... I don't know much about trading. :sweat_smile: 

Could you provide me with an example on what you want and how you achieve that in pandas? That would help me a lot.

**Comment by natemcintosh** [comment]
Hi @ritchie46, yes! Here's an example. 

Imagine we are running a simulation of people buying things. The people have bank accounts with money in them, and they want to buy certain products. In each run of the simulation we have three people: Larry, Curly, and Moe. We'll also run this simulation many times, with small variations each time; we'll label each of these runs with a Monte-Carlo number, 1-N. 

We have two tables
- the amounts in their bank accounts: `bank_accts`
- things that Larry, Curly, and Moe want to buy: `want_to_buy`

**What we want to do:** Every time Larry, Curly, or Moe want to buy something (i.e. for each row in `want_to_buy`) check if they have enough money in their bank account (i.e. find the row in `bank_accts` with latest update). To find the correct row, we have to make sure that we are looking at the correct time (asof join already does this), for the correct person, and in the correct Monte-Carlo run (this is the part that it doesn't do yet).

This code sets up the dataframes
```python
import random

import pandas as pd

# Create the bank_accts dataframe
bank_accts = pd.DataFrame(
    dict(
        monte_carlo_id=[x for x in range(1, 11) for _ in range(10)],
        time=random.choices(range(101), k=100),
        person=random.choices(["Larry", "Curly", "Moe"], k=100),
        amount=random.choices(range(1000), k=100),
    )
).sort_values(by="time", ignore_index=True)

# Create the want_to_buy dataframe
want_to_buy = pd.DataFrame(
    dict(
        monte_carlo_id=[x for x in range(1, 11) for _ in range(100)],
        time=random.choices(range(20, 110), k=1000),
        person=random.choices(["Larry", "Curly", "Moe"], k=1000),
        item=random.choices(["shoes", "shirt", "socks", "jeans"], k=1000),
        cost=random.choices(range(100), k=1000),
    )
).sort_values(by="time", ignore_index=True)
```
Looking at these dataframes, we'll have something like this
```python
In: bank_accts
Out:
    monte_carlo_id  time person  amount
0                4     0    Moe     731
1                9     2  Larry     870
2                3     3    Moe      92
3                2     3  Larry     765
4                2     3  Curly     342
..             ...   ...    ...     ...
95               6    96  Curly     401
96               9    98  Curly     451
97               8    98    Moe     830
98               1   100  Larry      94
99               9   100  Curly     506

[100 rows x 4 columns]


In: want_to_buy
Out: 
     monte_carlo_id  time person   item  cost
0                 3    20    Moe  jeans    82
1                 2    20    Moe  jeans    14
2                 2    20  Curly  socks    60
3                 9    20  Larry  socks    40
4                 2    20  Curly  shoes    79
..              ...   ...    ...    ...   ...
995               1   109  Larry  socks    72
996               9   109    Moe  shoes    45
997               1   109    Moe  shoes    19
998               6   109  Curly  jeans    29
999               2   109  Larry  socks    50

[1000 rows x 5 columns]
```

**Carrying out the grouped merge_asof in pandas**. If we had only person, and one simulation run, we could simply call `pd.merge_asof(want_to_buy, bank_accts, on="time")`. However, we want to make sure that we pull the bank account for the correct person, and for the correct Monte-Carlo run number. 

```python
In: pd.merge_asof(want_to_buy, bank_accts, on="time", by=["monte_carlo_id","person"])
Out: 
     monte_carlo_id  time person   item  cost  amount
0                 3    20    Moe  jeans    82   179.0
1                 2    20    Moe  jeans    14     NaN
2                 2    20  Curly  socks    60   342.0
3                 9    20  Larry  socks    40   870.0
4                 2    20  Curly  shoes    79   342.0
..              ...   ...    ...    ...   ...     ...
995               1   109  Larry  socks    72    94.0
996               9   109    Moe  shoes    45   845.0
997               1   109    Moe  shoes    19   233.0
998               6   109  Curly  jeans    29   401.0
999               2   109  Larry  socks    50    93.0

[1000 rows x 6 columns]
```

**Comment by natemcintosh** [comment]
Amazing! You are a miracle worker
