### ISSUE TITLE
Cannot GROUP_BY + explode in a streaming fashion

### ISSUE THREAD

**Issue by LukeMathWalker** [pola-rs/polars#11829]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
let df = LazyFrame::scan_parquet(
    "example.parquet",
    ScanArgsParquet::default(),
)?
.with_streaming(true)
.select(&[col("A"), col("B")])
.group_by([col("A")])
.agg([col("B").explode()]);
```

### Issue description

According to the documentation, both group by and explode should be supported in the streaming engine. When we try to call `sink_parquet` on the `LazyFrame` shown in the example, it panics with:

```
sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: false }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Expected behavior

It should be able to execute the plan in streaming mode.

### Installed versions

```toml
polars = { git="https://github.com/pola-rs/polars.git", rev="89cc1e2d67448183aa622e1b5f7130793b29b081", features = ["cloud_write", "strings", "streaming", "lazy", "parquet", "aws"] }
```

^ The latest commit on the `main` branch.

**Comment by ritchie46** [comment]
There is an operation data type in your query that we don't support yet.

You can open a feature request if you identified that one. But we don't support all types/operations yet.

Having an issue for all possible ways we don't support it is not helpful, so I will close this one.

**Comment by LukeMathWalker** [comment]
I'd be happy to, but I'm not sure how to identify which operation+data type combination is not supported from the printed query plan?

**Comment by ritchie46** [comment]
The operation we don't allow streaming is `pl.col().explode()`. We do support it on the dataframe level.

**Comment by buggtb** [comment]
> The operation we don't allow streaming is `pl.col().explode()`. We do support it on the dataframe level.

Just so you know, that single sentence unblocked us from weeks of confusion on where explodes were supported and removed a couple of lambdas that sent processing of our pipeline from 110 minutes to 7 minutes...
