### ISSUE TITLE
pl.DataFrame.update - does nothing when the updating value is null

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#11821]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
test_a = pl.DataFrame({"a": [1, 2, 3], "b": ["4", "5", "6"]})
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

test_update_a = pl.DataFrame({"a": [1, 2, None], "b": ["4", "5", None]})
shape: (3, 2)
┌──────┬──────┐
│ a    ┆ b    │
│ ---  ┆ ---  │
│ i64  ┆ str  │
╞══════╪══════╡
│ 1    ┆ 4    │
│ 2    ┆ 5    │
│ null ┆ null │
└──────┴──────┘

update = test_a.update(test_update_a, on="a", how="left")
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

```

### Issue description

pl.DataFrame.update - does nothing when the updating value is null

### Expected behavior

```
DataFrame should be updated with null values

update 
┌──────┬──────┐
│ a    ┆ b    │
│ ---  ┆ ---  │
│ i64  ┆ str  │
╞══════╪══════╡
│ 1    ┆ 4    │
│ 2    ┆ 5    │
│ null ┆ null │
└──────┴──────┘
```

### Installed versions

--------Version info---------
Polars:              0.19.9
Index type:          UInt32
Platform:            Windows-10-10.0.22000-SP0
Python:              3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.0.0
connectorx:          0.3.2_alpha.2
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.6.1
numpy:               1.25.2
openpyxl:            3.0.9
pandas:              1.5.0
pyarrow:             13.0.0
pydantic:            1.10.2
pyiceberg:           <not installed>
pyxlsb:              1.0.10
sqlalchemy:          2.0.22
xlsx2csv:            0.8
xlsxwriter:          3.0.9

**Comment by mcrumiller** [comment]
I think we should update `update` (heh) to make this a parameter, which should be false by default (i.e. the default should be to just use the values in the right frame, regardless of null status). But that would be breaking behavior, so perhaps we should make it true by default. What do you think @alexander-beedie ?

I can see a use case of `update` being "we have more recent data, use that instead." A null value may mean, say, the person is deceased, or has disappeared from a list (is no longer relevant) or any number of things, and therefore we should be able to propagate their null status if we want.
