### ISSUE TITLE
Arithmetic between signed integers and `UInt64` results in a float type

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#11837]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s1 = pl.Series([1], dtype=pl.Int32)
s2 = pl.Series([2], dtype=pl.UInt64)

result = s1 + s2
print(result)
```

### Log output

```shell
shape: (1,)
Series: '' [f64]
[
        3.0
]
```

### Issue description

I'm puzzled by this. Any reason for this to result in a float type?

Using `UInt32` instead of `UInt64` results in an integer as expected.

### Expected behavior

Result in a `Int64` or a `UInt64` type. Definitely not a float.

### Installed versions

main branch

**Comment by orlp** [comment]
Because we defined it that way in `supertype.rs`: https://github.com/pola-rs/polars/blob/89cc1e2d67448183aa622e1b5f7130793b29b081/crates/polars-core/src/utils/supertype.rs#L76.

**Comment by mcrumiller** [comment]
I could see this going anyway. One would think `u64(10) + i64(-1) = u64(8)`, but if that's the case, what's `u64(0) + i64(-1)`, and how would this be implemented?

**Comment by stinodego** [comment]
Hm yeah. I guess I didn't think this through very well. `UInt64` is trickier than I thought.

I guess I'll close this, since it's intended and for a good reason.

**Comment by ptiza** [comment]
There also have been lots of discussion around this behavior on numpy and it's still ongoing:

- https://github.com/numpy/numpy/issues/5745
- https://github.com/numpy/numpy/issues/7126
- https://github.com/numpy/numpy/issues/20905

Latest suggestion was to just follow C/C++ behavior. I agree on this issue that this behavior is unexpected and I would rather risk an overflow than losing precision due to a cast to float64.

**Comment by ptiza** [comment]
> I could see this going any way. One would think `u64(10) + i64(-1) = u64(9)`, but if that's the case, what's `u64(0) + i64(-1)`, and how would this be implemented?

Just cast to i64 instead. You "only" risk a signed integer overflow instead of losing precision. However, this is not UD in Rust, afaik.

**Comment by ghuls** [comment]
When I 

> Hm yeah. I guess I didn't think this through very well. `UInt64` is trickier than I thought.
> 
> I guess I'll close this, since it's intended and for a good reason.

For what it is worth, when I fixed the supertypes long ago, I followed the numpy way.
