### ISSUE TITLE
Randomly sampling elements from a Series of lists

### ISSUE THREAD

**Issue by kevinhu** [pola-rs/polars#11832]
### Description

Hi! I've been using Polars for some large data manipulation tasks and am loving the experience so far. One common use case is randomly selecting an element from each cell of a Series of lists, where the Series is from a LazyFrame.

So far, I'm using the following pattern:

```python
def choice(data, col_name):
    return data.with_columns(pl.col(col_name).map_elements(random.choice))

sampled = df.pipe(choice, col_name="lists").collect(streaming=True)["lists"]
```

However, this runs pretty slowly, so I was wondering if there's a more native way to do it. I was looking through the [List module](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html) but couldn't find anything applicable there.

**Comment by cmdlineluser** [comment]
You could use [`.list.eval()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.list.eval.html#polars.Expr.arr.eval) but perhaps there should be a direct `.list` method?

```python
df = pl.LazyFrame({"lists":[[1,2],[1,2,3],[7,8,9]]})

df.with_columns(random = 
   pl.col("lists").list.eval(pl.element().sample(1)).flatten()
).collect()

# shape: (3, 2)
# ┌───────────┬────────┐
# │ lists     ┆ random │
# │ ---       ┆ ---    │
# │ list[i64] ┆ i64    │
# ╞═══════════╪════════╡
# │ [1, 2]    ┆ 2      │
# │ [1, 2, 3] ┆ 2      │
# │ [7, 8, 9] ┆ 7      │
# └───────────┴────────┘
```

**Comment by alexander-beedie** [comment]
@reswqa: Exposing `sample` for this use-case would be great :))

@kevinhu: FYI: if your nested lists are relatively small, you may find the following construction is faster than mapping `random.choice`: 
```python
df.with_columns(
    sampled = pl.col("lists").list.eval( 
        pl.element().shuffle().head(1)
    ).list.get(0),
)
```
I see about a 3x speedup over `random.choice` with 20-elem sublists...
```python
df = pl.DataFrame({
    "n": range(1_000_000)}
).with_columns( lists=pl.int_ranges(-10,10) )

# shape: (1_000_000, 3)
# ┌────────┬────────────────┬──────────┐
# │ n      ┆ lists          ┆ selected │
# │ ---    ┆ ---            ┆ ---      │
# │ i64    ┆ list[i64]      ┆ i64      │
# ╞════════╪════════════════╪══════════╡
# │ 0      ┆ [-10, -9, … 9] ┆ 7        │
# │ 1      ┆ [-10, -9, … 9] ┆ -3       │
# │ 2      ┆ [-10, -9, … 9] ┆ -2       │
# │ 3      ┆ [-10, -9, … 9] ┆ -6       │
# │ …      ┆ …              ┆ …        │
# │ 999996 ┆ [-10, -9, … 9] ┆ -3       │
# │ 999997 ┆ [-10, -9, … 9] ┆ -6       │
# │ 999998 ┆ [-10, -9, … 9] ┆ 2        │
# │ 999999 ┆ [-10, -9, … 9] ┆ -6       │
# └────────┴────────────────┴──────────┘
```
...but a true/native `sample` should significantly outperform that  ;)
