### ISSUE TITLE
Issue while using outer-join/align with streaming

### ISSUE THREAD

**Issue by LeitnerMi** [pola-rs/polars#11842]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    df1 = pl.DataFrame({"a": [1], "b": [3]})
    df2 = pl.DataFrame({"a": [2], "c": [4]})

    df1 = df1.lazy()
    df2 = df2.lazy()

    df3 = df1.join(df2, how="outer", on="a")
    df4 = pl.concat([df1, df2], how="align")

    df3.sink_csv("./out.csv")
    df4.sink_csv("./out.csv")
```

### Log output

```shell
pyo3_runtime.PanicException: sink_Csv(CsvWriterOptions { has_header: true, batch_size: 1024, maintain_order: true, serialize_options: SerializeOptions { date_format: None, time_format: None, datetime_format: None, float_precision: None, separator: 44, quote_char: 34, null: "", line_terminator: "\n", quote_style: Necessary } }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

I am handling data, which i have to join and am getting a memory-exception. Therefore I looked at LazyFrames and encountered streaming. I could reduce my problem to the specific align-concatenation. I researched and found out that not every operation is compatible with the streaming mode, therefore I tried to do a workaround and and did an outer-join with all overlapping columns as keys. 

As of the userguide the join operation should be compatible with streaming, therefore I am confused. Is this expected behaviour? Furthermore I am working with local files.

Is there a streamable alternative for this problem or can this be fixed on my side?

### Expected behavior

The csv should be written to the local filesystem in streaming mode.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.9
Index type:          UInt32
Platform:            Linux-6.5.6-200.fc38.x86_64-x86_64-with-glibc2.37
Python:              3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None
```

</details>

**Comment by ritchie46** [comment]
We haven't implemented outer join yet for the streaming engine. It is on our roadmap.
