### ISSUE TITLE
Custom plugins not working with py-polars 0.19.9

### ISSUE THREAD

**Issue by qqlearn123** [pola-rs/polars#11851]
Custom plugins implemented previously with py-polars 0.19.8 and rust-polars 0.33 on longer work if I upgrade py-polars to 0.19.9.
Whenever it runs, just get kicked off from Python.

**Comment by mcrumiller** [comment]
Can you provide an example?

**Comment by MarcoGorelli** [comment]
for reference, https://github.com/MarcoGorelli/polars-business works with 0.19.9

**Comment by ritchie46** [comment]
They are under active development. The published rust on crates.io is outdated.
