### ISSUE TITLE
Misleading description of `.diff()` methods

### ISSUE THREAD

**Issue by LaurynasMiksys** [pola-rs/polars#11874]
### Description

It seems that documentation for `.diff(n)` method for `pl.Expr` [(link)](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.diff.html#polars.Expr.diff) and `pl.Series` [(link)](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.diff.html#polars.Series.diff) have misleading descriptions on what the function actually performs. 

It claims to do the following:

> Calculate the n-th discrete difference.

however, in the example provided (and actual code executed), it computes the _first_ discrete difference between values shifted by _period_ `n`. 

I believe, the original confusion might be coming from the differences between `np.diff(n)` and `pd.{Series/DataFrame}.diff(periods)` interfaces. The [NumPy version](https://numpy.org/doc/stable/reference/generated/numpy.diff.html) implements the _true_ n-th discrete difference, while [pandas](https://pandas.pydata.org/docs/reference/api/pandas.Series.diff.html) states that the method implements _first_ order difference, where `periods` argument controls the difference in array locations of elements. 

As a minimum, the documentation of `polars` should be corrected to indicate the first-order difference calculation. 

Moreover, to make `polars` API more self-consistent, I would also suggest renaming the argument `n` to `periods`, which is being used in the method `.shift()`. Semantically, `pl.col("a").diff(n)` is (almost) identical to `pl.col("a") - pl.col("a").shift(periods)`, hence, it would make sense to use the same arg-name. Additionally, this change would make it consistent with `pandas` API and its semantic meaning of the function. Keeping current arg-name (`n`) would preserve `numpy`'s API, but have different meaning, which user's might find confusing.

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.diff.html#polars.Expr.diff

**Comment by stinodego** [comment]
This is a good observation. We should update the documentation accordingly.

However, I am not a fan of `periods` as a parameter name. The parameter indicates the _number_ of places to shift before calculating the difference. As such, I think `n` is perfectly fitting.

What does "periods" even mean exactly in this context? _(I am not a mathematician)_

You're right that the parameter name should align with `shift`, but I think we should rename that parameter  to `n` instead.

**Comment by LaurynasMiksys** [comment]
I had a suspicion that this might have a meaning in `pandas`, where if the given Series/DataFrame has `DatetimeIndex`, then shifting/diff-ing would respect gaps in the index values. In such case, `periods` would "operate" on index values rather than locations. However, simple test convinced me that it's not the case, so even in `pandas` the arg naming is somewhat dubious. 

I think consistent naming within `polars` should be ideal end-state. However, the only small issue I had with keeping it `n` was identical naming and signature with `numpy.diff` which has distinct semantic meaning.

**Comment by stinodego** [comment]
> However, the only small issue I had with keeping it n was identical naming and signature with numpy.diff which has distinct semantic meaning.

I don't think this is a big issue, as long as we're being clear in the docs.

Could you update your PR accordingly?
