### ISSUE TITLE
`Series.null_count()` for Categorical types only considers the first chunk

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#11910]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

with pl.StringCache():
    s1 = pl.Series(["", ""], dtype=pl.Categorical)
    s2 = pl.Series([None, "", ""], dtype=pl.Categorical)

s = pl.concat([s1, s2], rechunk=False)

print(s.null_count())  # 0
```

### Issue description

Caught by parametric tests [here](https://github.com/pola-rs/polars/actions/runs/6592015533/job/17911807871).

Introduced by #11889

`null_count` is wrong for chunked Series of type Categorical.

### Expected behavior

Output for example should be `1`.

### Installed versions

main branch

**Comment by alexander-beedie** [comment]
> Caught by parametric tests [here](https://github.com/pola-rs/polars/actions/runs/6592015533/job/17911807871).

Glad I made randomised chunking the default in our hypothesis series/frame generation, heh 😅
```
chunked : bool, optional
    ensure that Series with more than one element have ``n_chunks`` > 1.
    if omitted, chunking is applied at random.
```

**Comment by stinodego** [comment]
> Glad I made randomised chunking the default in our hypothesis series/frame generation, heh 😅

Yes, it has caught a lot of stuff for me already, also with the interchange protocol!
