### ISSUE TITLE
[python] Implement array expressions

### ISSUE THREAD

**Issue by sa-** [pola-rs/polars#1191]
Hello!

It would be pretty useful to implement all the functions listed [here](https://spark.apache.org/docs/latest/api/sql/index.html#array) that start with `array`, and also `concat` and `element_at`, so that one doesn't have to use a lambdas.

Additionally, `array_flatten` (different from the polars flatten function that is an alias for explode) would also be useful.

To list them out

- [ ] array
- [ ] array_contains
- [x] array_distinct
- [ ] array_except
- [ ] array_intersect
- [ ] array_join
- [x] array_max
- [x] array_min
- [x] array_sum
- [x] array_mean
- [x] array_reverse
- [ ] array_position
- [ ] array_remove
- [ ] array_repeat
- [x] array_sort
- [ ] array_union
- [ ] arrays_overlap
- [ ] arrays_zip
- [x] concat (maybe called array_concat because that name is clearer)
- [ ] element_at(array|dict, element_key)
- [ ] array_flatten (in case each row in a column is a nested array, but we would like it to be a flat array)

Cheers

**Comment by ritchie46** [comment]
Seems like good addition to me. Probably good to have this under a `arr`/`list` namespace, similar to `str` and `dt`.

**Comment by sa-** [comment]
Cool - if you could show me where there could be implemented, I would be happy to contribute too.

**Comment by ritchie46** [comment]
More in #1205

**Comment by olivier-lacroix** [comment]
Is there any way to get the length of arrays?

**Comment by ritchie46** [comment]
> Is there any way to get the length of arrays?

Added in #1305

**Comment by olivier-lacroix** [comment]
Fantastic @ritchie46 !

**Comment by ritchie46** [comment]
Added concat: #1327

**Comment by s-b90** [comment]
Is it possible to add  `std` of arr?

**Comment by ghuls** [comment]
The following array expressions are implemented now:
```
arr.arg_max
arr.arg_min
arr.concat
arr.contains
arr.diff
arr.eval
arr.first
arr.get
arr.head
arr.join
arr.last
arr.lengths
arr.max
arr.mean
arr.min
arr.reverse
arr.shift
arr.slice
arr.sort
arr.sum
arr.tail
arr.unique
```

`arr.eval` allows you to run other polars expressions on the array:
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.series.list.ListNameSpace.eval.html

**Comment by ritchie46** [comment]
Yep.. I think we can close this. Especially with eval in place.

**Comment by indigoviolet** [comment]
nit: @ritchie46 why did you choose to call it `arr.lengths`? Wouldn't `length` or `size` be more conventional?
