### ISSUE TITLE
`DataFrame.take`

### ISSUE THREAD

**Issue by randolf-scholz** [pola-rs/polars#11911]
### Description

`polars.Series`, `pandas.Series`, `pandas.DataFrame`, `pyarrow.Array` and `pyarrow.Table` all support the `.take(indices)` method, which given a collection of integer indices selects the sub-series/table of the corresponding rows. Maybe worth considering as an addition to `polars.DataFrame`?

**Comment by cmdlineluser** [comment]
I think it is actually there on the `PyDataFrame` object, it just needs exposing from py-polars.

```python
df = pl.DataFrame({"foo": ["a", "b", "c"], "bar": ["d", "e", "f"]})

pl.DataFrame._from_pydf(df._df.take([1, 1, 1, 2, 2]))

# shape: (5, 2)
# ┌─────┬─────┐
# │ foo ┆ bar │
# │ --- ┆ --- │
# │ str ┆ str │
# ╞═════╪═════╡
# │ b   ┆ e   │
# │ b   ┆ e   │
# │ b   ┆ e   │
# │ c   ┆ f   │
# │ c   ┆ f   │
# └─────┴─────┘
```

**Comment by stinodego** [comment]
We do not plan on adding this. See discussion in the linked PR.
