### ISSUE TITLE
SQL cross join incorrect filter plan

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#11927]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
    "id":['1','2','3']
})

df2 = pl.DataFrame({
    "id":['4','5','6']
})
ctx = pl.SQLContext(df=df, df2=df2)

ctx.execute(
    """
    SELECT *
    FROM df
        CROSS JOIN df2
    WHERE df.id = df2.id
    """,
    eager=False,
)

naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)
SELECT [col("id"), col("id_right")] FROM
FILTER [(col("id")) == (col("id"))] FROM
CROSS JOIN:
LEFT PLAN ON: []
DF ["id"]; PROJECT */1 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
DF ["id"]; PROJECT */1 COLUMNS; SELECTION: "None"
END CROSS JOIN

```

### Issue description

The filter plan is incorrect on the right-hand side of the join. In the select you can see the same columns got renamed to _right, but in the filter it doesn't properly recognize df2.id as df2.id_right. When I pass id_right it works.

### Expected behavior

Pass the correct filter down in the plan.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.10
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:              3.10.12 (main, Aug  9 2023, 14:47:34) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.12.0
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.23.5
openpyxl:            <not installed>
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.22
xlsx2csv:            0.8.1
xlsxwriter:          3.1.9
```

</details>

**Comment by ritchie46** [comment]
Is the output incorrect? Can you reproduce with the polars dataframe API?

Could you show me an example with the incorrect output.

**Comment by ion-elgreco** [comment]
@ritchie46 

SQL output (wrong):

<html>
<body>
<small style="color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (9, 2)</small>

id | id_right
-- | --
str | str
"1" | "4"
"1" | "5"
"1" | "6"
"2" | "4"
"2" | "5"
"2" | "6"
"3" | "4"
"3" | "5"
"3" | "6"


</body>
</html>

DataFrame API output (correct)
`df.join(df2, how="cross").filter(pl.col("id") == pl.col("id_right"))`

<html>
<body>
<small>shape: (0, 2)</small><table border="1" class="dataframe" style="border-spacing: 0px; border-collapse: collapse; border: none !important; vertical-align: middle; text-align: right;"><thead style="border-spacing: 0px; border-collapse: collapse; border: none !important; font-weight: bold; background-color: rgba(130, 130, 130, 0.16); color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tr style="border-spacing: 0px; border-collapse: collapse; border: none !important; vertical-align: middle; text-align: right;"><th style="border-spacing: 0px; border-collapse: collapse; border: none !important; vertical-align: middle; text-align: right; padding: 4px 8px; white-space: pre-wrap;">id</th><th style="border-spacing: 0px; border-collapse: collapse; border: none !important; vertical-align: middle; text-align: right; padding: 4px 8px; white-space: pre-wrap;">id_right</th></tr><tr style="border-spacing: 0px; border-collapse: collapse; border: none !important; vertical-align: middle; text-align: right; background-color: rgba(130, 130, 130, 0.08);"><td style="border-spacing: 0px; border-collapse: collapse; border: none !important; padding: 4px 8px;">str</td><td style="border-spacing: 0px; border-collapse: collapse; border: none !important; padding: 4px 8px;">str</td></tr></thead>
</body>
</html>
