### ISSUE TITLE
Ceil date/datetime enhancement

### ISSUE THREAD

**Issue by JustinKurland** [pola-rs/polars#11936]
### Description

`truncate` and `month_start` and `month_end` are extremely convenient. With `truncate` one can very easily, at any temporal unit of analysis quickly "floor" the datetime to whatever the desired resolution. Presently, however "ceiling" a datetime is a bit more difficult. 

When conducting time series analysis often we want to ceil dates, which is why `month_end` is convenient. I am wondering if either a singular `ceil_date` could be developed or alternatively, one offs like for `month_start` and `month_end`. Below are examples, and also an example of error messages that occur depending on the nature of the series. 

```
s = pl.datetime_range(
    datetime(2001, 1, 1),
    datetime(2002, 1, 1),
    eager=True,
)

# Week Start (floor week)
s.dt.truncate("1w")

# Month Start (floor month)
s.dt.month_start()

# Quarter Start (floor quarter)
s.dt.truncate("1q")

# Year Start (floor year)
s.dt.truncate("1y")

# Week End (ceil week)
s.dt.offset_by('1w').dt.truncate('1w').dt.offset_by('-1d')

# Month End (ceil month)
s.dt.month_end()

# Quarter End (ceil quarter)
s.dt.offset_by('1q').dt.truncate('1q').dt.offset_by('-1d') 
## ComputeError: cannot advance '2001-01-31 00:00:00' by 3 month(s). 
## If you were trying to get the last day of each month, you may want to try 
##`.dt.month_end` or append "_saturating" to your duration string.

# Year End (ceil year)
s.dt.offset_by('1y').dt.truncate('1y').dt.offset_by('-1d')
```

**Comment by Rohxn16** [comment]
i would like to work on this issue, please assign this to me.

**Comment by MarcoGorelli** [comment]
Hi @JustinKurland 

What's your expected output for `s.dt.ceil('1h')`? It's not totally clear to me how well-defined the operation is

The ceil quarter, you can do
```python
s.dt.offset_by('1q_saturating').dt.truncate('1q').dt.offset_by('-1d')
```

**Comment by JustinKurland** [comment]
@MarcoGorelli here is a quick example of what the expected would be for 1h

"2009-08-03 12:01:59.23" 1h ceil_date would be "2009-08-03 13:00:00 UTC"

**Comment by MarcoGorelli** [comment]
right, so for ceiling by 1 hour, you want to go to the beginning of the next hour, but for ceiling by 1 month, you want to go to the end of the current month?

I think this sounds a bit inconsistent 😄 

having said that, just adding
- .dt.year_end
- .dt.year_begin

but I'm not totally convinced, will come back to this - thanks for the suggestion anyway

**Comment by JustinKurland** [comment]
@MarcoGorelli I happen to agree that it appear to be perhaps slightly off, but it happens to be consistent with the only ceiling_date function I am familiar with from any package/library, [lubridate](https://lubridate.tidyverse.org/reference/round_date.html). Have a look at what is implemented there for ceiling_date.

**Comment by RobertLD** [comment]
I also found myself needing this functionality recently and had to resort to a hodge-podge composition of pl.Expr's to accomplish the task.

**Comment by MarcoGorelli** [comment]
which hodge-podge did you use? wouldn't `.dt.truncate('1m').dt.offset_by('1m')` suffice?

**Comment by RobertLD** [comment]
> which hodge-podge did you use? wouldn't `.dt.truncate('1m').dt.offset_by('1m')` suffice?

In the case of a datetime such as "2023-10-5 10:00" I would expect to receive "2023-10-5 10:00" back. The example would return "2023-10-5 10:01"

**Comment by MarcoGorelli** [comment]
right, thanks

for now I think this could work (and is probably similar to what you came up with?):
```python
In [22]: def ceil(col, by):
    ...:     truncated = col.dt.truncate(by)
    ...:     return pl.when(
    ...:         col == truncated
    ...:     ).then(col).otherwise(truncated.dt.offset_by(by))
    ...:

In [23]: df = pl.DataFrame({'ts': [datetime(2023, 10, 5, 10), datetime(2023, 10, 5, 10, 0, 1)]})

In [24]: df.with_columns(ts_ceil=ceil(pl.col('ts'), '1m'))
Out[24]:
shape: (2, 2)
┌─────────────────────┬─────────────────────┐
│ ts                  ┆ ts_ceil             │
│ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════╪═════════════════════╡
│ 2023-10-05 10:00:00 ┆ 2023-10-05 10:00:00 │
│ 2023-10-05 10:00:01 ┆ 2023-10-05 10:01:00 │
└─────────────────────┴─────────────────────┘
```

Not totally sure about the name though, because `ceil` is the opposite of `floor`, not of `truncate`, although I don't know of any antonym of `truncate` which would fit well here

**Comment by MarcoGorelli** [comment]
I've added this to [polars-xdt](https://github.com/MarcoGorelli/polars-xdt):
```python
In [2]: import polars as pl

In [3]: import polars_xdt  # noqa: F401

In [4]: from datetime import datetime, date

In [5]: df = pl.DataFrame({'ts': [datetime(2023, 10, 5, 10), datetime(2023, 10, 5, 10, 0, 1)]})

In [6]: df.with_columns(ts_ceil=pl.col('ts').xdt.ceil('1m'))
Out[6]:
shape: (2, 2)
┌─────────────────────┬─────────────────────┐
│ ts                  ┆ ts_ceil             │
│ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════╪═════════════════════╡
│ 2023-10-05 10:00:00 ┆ 2023-10-05 10:00:00 │
│ 2023-10-05 10:00:01 ┆ 2023-10-05 10:01:00 │
└─────────────────────┴─────────────────────┘
```

Closing then, but thanks for the request!
