### ISSUE TITLE
Config.set_fmt_table_cell_list_len missing from API docs

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11935]
### Description

this was added in https://github.com/pola-rs/polars/pull/11409/files, but looks like it's missing from the api

I think it just needs adding to `py-polars/docs/source/reference/config.rst`

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/config.html

**Comment by cmdlineluser** [comment]
I guess the title should say `fmt_table_cell_list_len`

**Comment by Rohxn16** [comment]
i would like to work on this issue

**Comment by MarcoGorelli** [comment]
> I guess the title should say `fmt_table_cell_list_len`

I think the method name is with the `set_`

https://github.com/pola-rs/polars/blob/46e70094af11f92d7a6f64069118712171e8bd55/py-polars/polars/config.py#L586-L587

**Comment by cmdlineluser** [comment]
Apologies @MarcoGorelli - I wasn't entirely clear, the title names `set_fmt_str_lengths` as opposed to `set_fmt_table_cell_list_len`

**Comment by MarcoGorelli** [comment]
my bad, thanks!

**Comment by MarcoGorelli** [comment]
@Rohxn16 cool, PRs welcome

**Comment by Rohxn16** [comment]
Ok i will start working on it at 7 am IST.

**Comment by MarcoGorelli** [comment]
I wonder what time that is where I live

oh wait, I can use Polars to find out!

```python
In [9]: pl.Series([datetime(2023, 10, 23, 7)]).dt.replace_time_zone('Asia/Kolkata').dt.convert_time_zone('Europe/London')
Out[9]:
shape: (1,)
Series: '' [datetime[μs, Europe/London]]
[
        2023-10-23 02:30:00 BST
]
```

**Comment by Rohxn16** [comment]
@MarcoGorelli I have added a PR on this issue, please tell me if I need to change anything. I have never worked on a big codebase like this before, especially on documentation that's why I choose a good first issue. I'm tryna learn how to work with larger codebases.
