### ISSUE TITLE
Raise if expression if passed to pl.DataFrame?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11930]
### Description

A fairly common source of confusion when using `int_range` / `date_range` is the following:
```python
In [1]: print(pl.DataFrame({
   ...:     'a': pl.int_range(0, 10),
   ...:     'b': pl.int_range(1, 11),
   ...: }))
shape: (1, 2)
┌───────────────────┬───────────────────┐
│ a                 ┆ b                 │
│ ---               ┆ ---               │
│ object            ┆ object            │
╞═══════════════════╪═══════════════════╡
│ 0.int_range([10]) ┆ 1.int_range([11]) │
└───────────────────┴───────────────────┘
```

I had a trainee ask me "why does it look so weird" 😄 . I think @braaannigan had a similar experience whilst teaching

Trying to do the same with `pl.Series` would raise:
```python
In [4]: pl.Series(pl.int_range(0, 10))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 pl.Series(pl.int_range(0, 10))

File ~/tmp/.venv/lib/python3.10/site-packages/polars/series/series.py:328, in Series.__init__(self, name, values, dtype, strict, nan_to_null, dtype_if_empty)
    320     self._s = iterable_to_pyseries(
    321         name,
    322         values,
   (...)
    325         strict=strict,
    326     )
    327 else:
--> 328     raise TypeError(
    329         f"Series constructor called with unsupported type {type(values).__name__!r}"
    330         " for the `values` parameter"
    331     )

TypeError: Series constructor called with unsupported type 'Expr' for the `values` parameter
```

Maybe the dataframe case should also raise then? The given output looks very unlikely to ever be desired

**Comment by ritchie46** [comment]
Yes, this happens more often than we'd want. I think we should raise and add a keyword argument. Allow `allow_expression_objects=False`

**Comment by deanm0000** [comment]
I think erroring is a good idea generally. It would probably be helpful if that error message suggested that pl.select can be used to create DataFrames from expressions.

**Comment by stinodego** [comment]
I don't think it's worth a parameter. This should error. You can pass a list or a Series of expressions if you really want to insert expression objects into a DataFrame.
