### ISSUE TITLE
Provide view() method for purely numeric DataFrame

### ISSUE THREAD

**Issue by mushroomfire** [pola-rs/polars#11948]
### Description

Is it possible to provide a feature just like polars.Series.view() for purely numerical polars.DataFrame?
It is **zero-copy** and will be very useful for interpolation with Numba or Taichi. Now I have to use to_numpy(), which clones data.

**Comment by ritchie46** [comment]
The memory in a dataframe is not contiguous. Every column is allocated somewhere else. So `to_numpy` on a 2D DataFrame always needs to clone data to create contiguous memory slab.
