### ISSUE TITLE
Introduce **kwargs in group_by

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#11957]
### Description

For example

```
df.group_by(Month=pl.col('dt').dt.truncate('1mo)).agg(pl.all().sum())
```

I realize the same effect is available by using `alias` but just to be consistent with everywhere else.

**Comment by stinodego** [comment]
Sure, can add this.

**Comment by deanm0000** [comment]
@stinodego are you still doing this one? If not, I think I can do it.

**Comment by stinodego** [comment]
All right, feel free to open a PR!
