### ISSUE TITLE
"connection closed before message completed" on `collect_all` from S3

### ISSUE THREAD

**Issue by djbarker** [pola-rs/polars#11954]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
path = "s3://foo/bar/{thing}.parquet"
lazys = [pl.scan_parquet(path.format(thing) for thing in things]
datas = pl.collect_all(lazys)
```

### Issue description

In the example above, when running on AWS batch, on running `collect_all` I see transient failures with the error
```
exceptions.ComputeError: Generic S3 error: response error "request error", after 0 retries: error sending request for url (https://s3.<path_to_specific_file>.parquet): connection closed before message completed
```
I have not seen this behaviour locally when reading from the same S3 bucket. But cannot rule it out. I had a look on google and could not find anything related but there were some similar errors relating to timeouts and reusing connection objects. 

If it's relevant:
```bash
conda list | grep s3
s3fs                      2023.4.0        py310h06a4308_0    conda
s3transfer                0.6.0           py310h06a4308_0    conda
```

### Expected behavior

It should successfully collect all the lazy frames.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-5.14.0-162.6.1.el9_1.x86_64-x86_64-with-glibc2.31
Python:              3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Does it work if you run `collect`? And have you provided proper login env vars?

**Comment by djbarker** [comment]
Do you mean running collect on each frame? Yes that seems to work.
I have not specifically set up any env vars when running remotely (on AWS). But it seems to work sometimes so I think they must be correctly configured. Which env vars need setting? I could try that.

**Comment by ritchie46** [comment]
Can you make an MWE with a public s3 dataset?

**Comment by jclaytonawin** [comment]
This happens also for piping s3 partitions into a multipart upload:
` LazyFrame::scan_parquet(agg_path, args).unwrap()
            .with_streaming(false)
            .select([
                all(),
            ])
            .sink_parquet_cloud(sink_path, cloudopts, Default::default())
            .unwrap();`

**Comment by jclaytonawin** [comment]
This happens also for piping s3 partitions into a multipart upload:
```
LazyFrame::scan_parquet(agg_path, args)
.unwrap()
.with_streaming(true)
.select([all(),])
.ink_parquet_cloud(
  sink_path,
  cloudopts, 
  Default::default()
)
.unwrap();
```
