### ISSUE TITLE
Rounding to significant figures

### ISSUE THREAD

**Issue by owrior** [pola-rs/polars#11968]
### Description

Recently I have been working on a project where we needed to round to significant figures and realised there is no way to do this in pandas, numpy or polars. I found [this](https://stackoverflow.com/questions/18915378/rounding-to-significant-figures-in-numpy/59888924#59888924) as the best solution.

```
def signif(x, p):
    x = np.asarray(x)
    x_positive = np.where(np.isfinite(x) & (x != 0), np.abs(x), 10**(p-1))
    mags = 10 ** (p - 1 - np.floor(np.log10(x_positive)))
    return np.round(x * mags) / mags
```

However it would be nice to have it as part of a package. Would it be possible to include this? 

I have implemented this already here #11959 which is about 20% faster than the numpy one here already. However I can imagine there is a better way than using the zip_with maybe? 

Thank you!

**Comment by orlp** [comment]
Perhaps this could be a boolean keyword-only argument for [`round`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.round.html#polars.Expr.round)?

    Expr.round(decimals: int = 0, *, significant = False)

If set to `True` it would round to the specified number of significant digits.

**Comment by owrior** [comment]
I was thinking that but then thought it might be distinct enough (given the use with integers to) to have in a separate function. Happy to go with what you would prefer though!

**Comment by owrior** [comment]
@orlp should I make the name more expressive or anything?

**Comment by orlp** [comment]
@owrior

I had a discussion with @stinodego and I believe we settled on adding this functionality, but as a separate function named `round_sig_figs`.

**Comment by owrior** [comment]
@orlp 

Thank you very much for this it will be a great help. Can you let me know if my PR is looking good? I have refactored to this function as requested.
