### ISSUE TITLE
How about changing the type hint in `BasicCursor.execute` to use `Callable`?

### ISSUE THREAD

**Issue by phi-friday** [pola-rs/polars#11980]
### Description

```python
# polars.type_aliases

class BasicCursor(Protocol):  # noqa: D101
    def close(self) -> None:
        """Close the cursor."""

    def execute(self, *args: Any, **kwargs: Any) -> Any:
        """Execute a query."""
```
to
```python
class BasicCursor(Protocol):  # noqa: D101
    def close(self) -> None:
        """Close the cursor."""
    
    execute: Callable[..., Any]
    """Execute a query."""
```

Benefits of the change:

When using pyright, using sqlalchemy.orm.Session and sqlalchemy.engine.Connection will not cause errors.

**Comment by alexander-beedie** [comment]
Unfortunately that formulation doesn't work with `mypy`, hmm... 🤔

**Comment by phi-friday** [comment]
@alexander-beedie I'm not uncomfortable with it now, and I'm always grateful for it. Thanks for the answer.

**Comment by alexander-beedie** [comment]
> Thanks for the answer.

No problem; even though we can't use the hint given above, I think I'll re-open this issue so that we can try and find some typing that works reasonably for both (ideally we should give good results on both mypy _and_ pylance) ;)
