### ISSUE TITLE
Introduce a means to prevent errors and return null for all operations (or if that isn't feasible, just dot)

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#11985]
### Description

Inspired by [this](https://stackoverflow.com/questions/77352151/how-can-i-do-the-dot-product-of-a-window-and-a-constant-vector-in-polars/77353027#77353027) question.

In this question, the issue is taking the dot product on a rolling basis but the first term is too short so the whole thing raises an error. It'd be nice if there was a means to just get null where errors exist instead of raising. To avoid confusion, I do **not** want that to be the default behavior. I'm just saying it'd be nice if there was a way to get that behavior. I can think of 3 ways that might be handled

1. a wrapper

```
df_.rolling("id_", period="2i").agg(try_null(pl.col("value").dot(pl.lit(const))))
```

2. by parameter (for instance, how cast is) 
```
df_.rolling("id_", period="2i").agg(pl.col("value").dot(pl.lit(const), strict=False))
```

3. maybe even as a context

```
with pl.ignore_errors():
    df_.rolling("id_", period="2i").agg(pl.col("value").dot(pl.lit(const)))
```

I don't really have a strong opinion on the implementation or usability of any of these so consider them as being in no particular order.

**Comment by cmdlineluser** [comment]
Something odd seems to be happening.

Even without the 1-value window it raises:
```python
df = pl.DataFrame({'value': [[1, 1], [1, 2], [2, 2], [2, 3], [3, 3], [3, 4], [4, 4]]})

df.select(pl.col("value").list.eval(pl.element().dot(pl.lit([.5, .5]))))
# PanicException: Cannot apply operation on arrays of different lengths
```
But `.drop_nulls()` allows it to run:
```python
df.select(pl.col("value").list.eval(pl.element().drop_nulls().dot(pl.lit([.5, .5]))))
# shape: (7, 1)
# ┌───────────┐
# │ value     │
# │ ---       │
# │ list[f64] │
# ╞═══════════╡
# │ [1.0]     │
# │ [1.5]     │
# │ [2.0]     │
# │ [2.5]     │
# │ [3.0]     │
# │ [3.5]     │
# │ [4.0]     │
# └───────────┘
```

**Comment by ritchie46** [comment]
That would make things very expensive. And therefore not something I want to add.
