### ISSUE TITLE
Adding a .list.combinations() feature

### ISSUE THREAD

**Issue by ThomasMAhern** [pola-rs/polars#11999]
### Description

[jqurious](https://stackoverflow.com/users/19355181/jqurious) suggested submitting this request in response to a question I had: https://stackoverflow.com/questions/77354114/how-would-i-generate-combinations-of-items-within-polars-using-the-native-expres

It would be very useful to have a way to generate combinations of items within a list inside a Polars column without resorting to `.map_elements()` + itertools (or the "cross-join with itself and filter out the redundant entries" answer)

Code I had:
```python
(pl.DataFrame({'col': [['a', 'b', 'c']]})
   .with_columns(pl.col('col')
                   .map_elements(lambda list_o_things: [sorted((thing_1, thing_2))
                                                        for thing_1, thing_2 
                                                        in itertools.combinations(list_o_things, 2)])
                )
)
```

Cross join solution:
```python
df=pl.DataFrame({'col': [['a', 'b', 'c']]})
(df
  .explode('col')
  .join(
      df.explode('col'), how='cross')
  .filter(pl.col('col')<pl.col('col_right'))
  .select(pl.concat_list('col','col_right').implode())
  )
```

**Comment by orlp** [comment]
I personally feel this is a bit overly specific, and also leads to patterns that don't have good performance.

**Comment by ritchie46** [comment]
I want to defer this one to the plugins. :)
