### ISSUE TITLE
use of unstable library feature 'unicode_internals'

### ISSUE THREAD

**Issue by claudiofsr** [pola-rs/polars#11990]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

rustup check
stable-x86_64-unknown-linux-gnu - Up to date : 1.73.0 (cc66ad468 2023-10-03)
rustup - Up to date : 1.26.0

Try to compile 

polars version 0.34

with

cargo b

The output:

```rust
error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/git/checkouts/polars-b0d90607192fd414/60adaef/crates/polars-ops/src/chunked_array/strings/case.rs:80:36
   |
80 |         match iter.skip_while(|&c| Case_Ignorable(c)).next() {
   |                                    ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/git/checkouts/polars-b0d90607192fd414/60adaef/crates/polars-ops/src/chunked_array/strings/case.rs:81:24
   |
81 |             Some(c) => Cased(c),
   |                        ^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/git/checkouts/polars-b0d90607192fd414/60adaef/crates/polars-ops/src/chunked_array/strings/case.rs:78:29
   |
78 |         use core::unicode::{Case_Ignorable, Cased};
   |                             ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/git/checkouts/polars-b0d90607192fd414/60adaef/crates/polars-ops/src/chunked_array/strings/case.rs:78:45
   |
78 |         use core::unicode::{Case_Ignorable, Cased};
   |                                             ^^^^^

For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-ops` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Log output

```shell
POLARS_VERBOSE=1 cargo b

   Compiling polars-ops v0.34.0
error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-ops-0.34.0/src/chunked_array/strings/case.rs:80:36
   |
80 |         match iter.skip_while(|&c| Case_Ignorable(c)).next() {
   |                                    ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-ops-0.34.0/src/chunked_array/strings/case.rs:81:24
   |
81 |             Some(c) => Cased(c),
   |                        ^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-ops-0.34.0/src/chunked_array/strings/case.rs:78:29
   |
78 |         use core::unicode::{Case_Ignorable, Cased};
   |                             ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'unicode_internals'
  --> /home/claudio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-ops-0.34.0/src/chunked_array/strings/case.rs:78:45
   |
78 |         use core::unicode::{Case_Ignorable, Cased};
   |                                             ^^^^^

For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-ops` (lib) due to 4 previous errors
```

### Issue description

use of unstable library feature 'unicode_internals'

[unicode](https://doc.rust-lang.org/core/unicode/index.html)

[case.rs](https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/chunked_array/strings/case.rs)

### Expected behavior

Error

### Installed versions

<details>

Replace this line with a list of feature gates

Cargo.toml:

[dependencies.polars]
version = "0.34"
features = [
    "abs", # Convert all values to their absolute/positive value.
    "concat_str", # Concat string data in linear time
    "dtype-array",
    "dtype-date",
    "dtype-struct",
    "dtype-datetime",
    "dtype-duration",
    "dtype-categorical",
    "is_in", # Check for membership in Series
    "lazy", # Lazy API
    "lazy_regex", # Use regexes in column selection
    "list_eval", # Apply expressions over list elements
    "list_take", # take sublist by multiple indices
    "parquet", # Read Apache Parquet format
    "repeat_by",
    "round_series", # round underlying float types of Series
    "serde-lazy", # Support for serde serialization and deserialization.
    "strings", # Extra string utilities for Utf8Chunked
]

</details>

**Comment by ritchie46** [comment]
Hmm.. @orlp can you take a look? I believe you did a refactor on this one.

**Comment by rob-p** [comment]
I am seeing this as well, with a clean build on rust 1.73.

**Comment by ritchie46** [comment]
On it. Will patch.

**Comment by orlp** [comment]
@ritchie46 Sorry I didn't see the notification yet.
