### ISSUE TITLE
Can't change the writeable flag for df.to_numpy()

### ISSUE THREAD

**Issue by mushroomfire** [pola-rs/polars#12001]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

df = pl.DataFrame({'a':[1, 2, 3, 4, 5], 'b':[1, 2, 4, 5, 3]})

array = df.to_numpy()
# array = np.array(df) # This is Okay.
array.flags.writeable = False
array.flags.writeable = True # Here raise an error.
```

### Log output

```shell
array.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

### Issue description

I can't change the WRITEABLE flag for df.to_numpy(). It is abnormal.

### Expected behavior

It should change the WRITEABLE flag.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.3
numpy:               1.24.4
openpyxl:            <not installed>
pandas:              2.0.0
pyarrow:             11.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
> It is abnormal.

It is because numpy doesn't own the memory. You need to deepcopy to be able to write to the memory.

**Comment by mushroomfire** [comment]
I can't see the comments at github, but I am noticed by the email by @Ritchie Vink. I think the deepcopy should be done by the df.to_numpy(), because it clones data.

**Comment by stinodego** [comment]
You cannot simply set the writable flag of a NumPy array this way.

To create a writable NumPy array from a DataFrame, use `DataFrame.to_numpy(writable=True)`.
