### ISSUE TITLE
Rename `frame_equal` and `series_equal` to `frame_equals` and `series_equals` (or just `equals`)

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12000]
### Description

`df1.frame_equals(df2)` feels more grammatical than `df1.frame_equal(df2)` because you would say "df1 equals df2" but not "df1 equal df2". Similarly, `series1.series_equals(series2)` feels more grammatical than `series1.series_equal(series2)`. Another option would be to call these both `equals` like pandas.

**Comment by stinodego** [comment]
It should just be `equals`. But this functionality is used heavily in the Rust test suite (there is no `assert_frame_equal` in Rust), so I'm not sure about changing this right now.
