### ISSUE TITLE
scan_parquet does not parse gcs / gcp urls correctly

### ISSUE THREAD

**Issue by daviskirk** [pola-rs/polars#12006]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.scan_parquet("gs://example.com/test.parquet", storage_options={})
```

### Log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dek/anaconda/envs/excavator/lib/python3.10/site-packages/polars/io/parquet/functions.py", line 268, in scan_parquet
    return pl.LazyFrame._scan_parquet(
  File "/home/dek/anaconda/envs/excavator/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 455, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
polars.exceptions.ComputeError: Generic GCS error: URL did not match any known pattern for scheme: gs://example.com/test.parquet
```

### Issue description

The URL of gcs object store files isn't being parsed correctly.
After reading https://github.com/pola-rs/polars/issues/11778, I realized that I could use the examples used there, but not mine.

The problem is that the GCS bucket has period characters and this causes the error:

```python
pl.scan_parquet("gs://example.com/test.parquet", storage_options={})
```

gives:

```
ComputeError: Generic GCS error: URL did not match any known pattern for scheme: gs://example.com/test.parquet
```

whereas without any periods in the bucket, the parsing works. Unfortunately, we can't work with buckets without "periods" as the domains are used to be verified.

Could it be that the URL parsing is incorrect?

### Expected behavior

What the example above should output is the "no body" error if an object isn't available:

```python
pl.scan_parquet("gs://example.com/test.parquet", storage_options={})
```

```
ComputeError: Generic GCS error: response error "No Body", after 0 retries: HTTP status client error (403 Forbidden) for url (https://storage.googleapis.com/examplecom/test%2Eparquet)
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            Linux-6.2.0-35-generic-x86_64-with-glibc2.37
Python:              3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.8
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.39
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Open an issue upstream.

**Comment by tustvold** [comment]
Fix in https://github.com/apache/arrow-rs/pull/4992

FWIW this is confined to the URL parsing, the store implementation does support this, so if there is a mechanism to construct the store manually that should allow you to workaround this until the fix is released.

**Comment by ritchie46** [comment]
> FWIW this is confined to the URL parsing, the store implementation does support this, so if there is a mechanism to construct the store manually that should allow you to workaround this until the fix is released.

Clear, thanks for the quick fix. :+1:
