### ISSUE TITLE
naming conventions for Expr.cum* and Series.cum*

### ISSUE THREAD

**Issue by rancomp** [pola-rs/polars#12013]
### Description

Currently, the names of cumulative functions under `Expr` and `Series` do not conform to the general style of polars. Specifically, the names have two words clamped. For example we have cumsum standing for  cumulative sum. In polars, different words are separated with an underscore, e.g., group by function is written as `group_by` and not the version where group and by are joined to one word.

I propose the following changes are made:
**Current names**:`cumcount, cummax, cummin, cumprod, cumsum, cumulative_eval`
**Proposed names**: `cum_count, cum_max, cum_min, cum_prod, cum_sum, cum_map`.

**Note**: `cumulative_eval` has two changes to it: `cumulative->cum` and `eval->map`.
Furthermore, `cumulative_eval` has the `periods` argument which was recently deprecated in favor or `n` IIRC.

This is a large breaking change, so it's probably better to reiterate the commitment to the polars styling conventions.

**Comment by stinodego** [comment]
I think we need to do this :smiling_face_with_tear:
