### ISSUE TITLE
Performance of Scan Parquet in Azure Cloud Read

### ISSUE THREAD

**Issue by horizondeep** [pola-rs/polars#12021]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

////////////////////Trying with Scan Parquet in Polars//////////////////////////////////////////////
let start = Instant::now();
const TEST_S3: &str = "azure://test-func/10003.parquet";
let AccountName = "blobstore";
let AccountKey = "blobkey";
let cloud_options=cloud::CloudOptions::default().with_azure([(Key::AccountName,AccountName),(Key::AccessKey,AccountKey)]);

let mut args = ScanArgsParquet::default();
args.parallel = ParallelStrategy::RowGroups;
args.cloud_options = Some(cloud_options);

let df_blob = LazyFrame::scan_parquet(TEST_S3, args)?
        .with_streaming(true)
        .select([
            // select all columns
            all(),
        ])
        .collect()?;
    //
    let duration_row_mapping = start.elapsed();

    println!("Time elapsed in reading blob data is: {:?}", duration_row_mapping);

    //Time elapsed in reading blob data is: 3.387758s

///////////////////////Trying Directly with MicrosoftAzure Builder/////////////////////////////////////////////////////
let STORAGE_ACCOUNT = ""blobstore";
let KEY = "blobkey";
let CONTAINER_NAME = "test-func"
const INPUT_LOCATION: &str = "10003.parquet";

let start = Instant::now();

let object_store = MicrosoftAzureBuilder::new()
	.with_account(STORAGE_ACCOUNT)
	.with_container_name(CONTAINER_NAME)
	.with_access_key(KEY)
	.build()?;

let data = object_store.get(&Path::from(INPUT_LOCATION)).await?;

let df = ParquetReader::new(std::io::Cursor::new(data.bytes().await?)).read_parallel(ParallelStrategy::RowGroups).finish().unwrap();

let duration_row_mapping = start.elapsed();

println!("Time elapsed in reading blob data is: {:?}", duration_row_mapping)

//Time elapsed in reading blob data is: 1.7203642s



```
 

### Issue description

LazyFrame::Scan_Parquet does not seem to offer the expected efficiency when reading from Azure Blob Storage. Its performs worse than ParquetReader when reading file of the same size from Azure Blob Storage.

### Expected behavior

It should be atleast equal in terms of performance to the "ParquetReader" if not better if you are reading a whole file without filtering.

### Installed versions

<details>

polars = { version = "0.34.1", features = ["serde", "json", "polars-io","rank", "lazy","azure","dtype-struct","parquet","streaming","cloud"] }
object_store = "0.7.1"
</details>

**Comment by Bidek56** [comment]
Are you running this test inside of Azure? Could it be a network latency?

**Comment by horizondeep** [comment]
> Are you running this test inside of Azure? Could it be a network latency?

Running both codes from my local. I repeated this testing more than 10 times but difference between Scan_parquet and Parquetreader is same, so doesn't seem to be a network latency issue.

**Comment by ritchie46** [comment]
How many row groups and columns does the file have?

**Comment by ritchie46** [comment]
How does it compare when you don't use the streaming engine?

**Comment by horizondeep** [comment]
let df_blob = LazyFrame::scan_parquet(TEST_S3, args)?
        .with_streaming(false)
        .select([all(),])
        .collect()?;


//Time elapsed in reading blob data is: 3.1000554s

**Comment by horizondeep** [comment]
I did even select only 2 columns in the below code but still "Scan_Parquet" is slower in comparison to "ParquetReader". So if am reading all columns with ParquetReader and only 2 columns with 'Scan_Parquet', 'ParquetReader' still beats 'Scan_Parquet' in performance.

let df_blob = LazyFrame::scan_parquet(TEST_S3, args)?
        .with_streaming(true)
        .select([
            // select all columns
            col("UPC_ID"),col("PG_ID")
        ])
        .collect()?;

//Time elapsed in reading blob data is: 2.2121809s

While reading the whole file with 'Object_Store' and 'Parquet_Reader' its taking around ~1.7 secs.

**Comment by ritchie46** [comment]
@horizondeep can you do a retry with this PR? #12061

**Comment by horizondeep** [comment]
@ritchie46 I tried with the above PR but the timing is still coming same as previous ones.

**Comment by ritchie46** [comment]
Alright, thanks. Will come back to you. ;)

**Comment by ritchie46** [comment]
Can you try again? :)

**Comment by horizondeep** [comment]
Hi @ritchie46. Their is performance improvement in the scan parquet. 
All columns reading:
Time elapsed in reading blob data from Scan_Parquet is: 2.3-2.4 (earlier 3.2-3.4 secs for various runs)

But still the Microsoft Azure Builder is performing better.
All columns reading:
Time elapsed in reading blob data from MSBUILDER is: ~1.9s

Also just wanted to check if am pulling the right code from polars repo for scan parquet:
polars = { git = "https://github.com/pola-rs/polars.git",  branch = "download",features = ["serde", "json", "polars-io","rank", "lazy","azure","dtype-struct","parquet","streaming","cloud","async"] }

**Comment by ritchie46** [comment]
Great to hear. The streaming engine can probably not get the limit you have, as you have some assumptions we cannot have. That is that the results fit into memory and that the query will not be stopped early. So you can download all in batch as you have more information than we have.

**Comment by horizondeep** [comment]
So is it right to assume that if we have to download all the data without any filtering, "scan_parquet" will be inferior in performance to "ParquetReader"?

**Comment by ritchie46** [comment]
Yes, as it stands it is. 

If you know you can fit all data in memory and you know you need all data, you can simply download all data and that is faster. 

However....

`scan_parquet` can already do compute in between. So you actually have a compute intensive query, scan_parquet can still be optimal, as in your case you split entirely by IO and then COMPUTE.

**Comment by ritchie46** [comment]
Just to be sure, I believe we can still improve. More work on this follows.

**Comment by horizondeep** [comment]
> Just to be sure, I believe we can still improve. More work on this follows.

Sure @ritchie46. Eagerly waiting for it.

**Comment by horizondeep** [comment]
Hi @ritchie46. Sent it over the mail. Plz check.
