### ISSUE TITLE
offset parameter in group_by_dynamic skips values

### ISSUE THREAD

**Issue by namiyousef** [pola-rs/polars#12035]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

My understanding of the `offset` parameter in groupby dynamic is that I can offset the calculation window. So suppose that I want to a daily sum of a certain timeseries, but that I want "day" to be considered from 6am today to 6 am the day after.

```python
timestamps = [
            "2021-01-01 00:00:00",
            "2021-01-01 00:00:01",
            "2021-01-01 00:01:00",
            "2021-01-01 00:05:00",
            "2021-01-01 01:00:00",
            "2021-01-01 06:00:00",
            "2021-12-31 23:55:00",
            "2022-01-01 00:00:00",
        ]
df = pl.DataFrame(
    {
        "date": timestamps,
        "values": [1, 2, 3, 4, 5, 6, 7, 8],
    }
).with_columns(
    pl.col("date").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S")
)

print(
    df.sort("date")
    .group_by_dynamic(
        "date",
        every="1d",
        offset="6h",
        include_boundaries=True,
        closed="left",
        label="left",
        start_by="window",
    )
    .agg(pl.col("values"))
)
```

### Log output

```shell
The output looks as follows:
│ 2021-01-01 06:00:00 ┆ 2021-01-02 06:00:00 ┆ 2021-01-01 06:00:00 ┆ [6]       
│ 2021-12-31 06:00:00 ┆ 2022-01-01 06:00:00 ┆ 2021-12-31 06:00:00 ┆ [7, 8]
```

### Issue description

If this is by design, then it's not a bug. But is there a reason why the boundary is ignored?

### Expected behavior

│ 2021-12-31 06:00:00 ┆ 2021-01-01 06:00:00 ┆ 2021-12-31 06:00:00 ┆ [1,2,3,4,5]       

To be included as well

### Installed versions

<details>

--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            macOS-12.6.6-x86_64-i386-64bit
Python:              3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by ritchie46** [comment]
pinging @MarcoGorelli here.

**Comment by JulianCologne** [comment]
I am not sure if this behaviour is intended or a bug, but it seems like setting `offset=-18h` produces your expected result

```python
(
    df.sort("date")
    .group_by_dynamic(
        "date",
        every="1d",
        offset="-18h",  # <<<<<<<<<<<<
        include_boundaries=True,
        closed="left",
        label="left",
        start_by="window",
    )
    .agg(pl.col("values"))
)
┌─────────────────────┬─────────────────────┬─────────────────────┬─────────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ date                ┆ values          │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---             │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ list[i64]       │
╞═════════════════════╪═════════════════════╪═════════════════════╪═════════════════╡
│ 2020-12-31 06:00:00 ┆ 2021-01-01 06:00:00 ┆ 2020-12-31 06:00:00 ┆ [1, 2, 3, 4, 5] │
│ 2021-01-01 06:00:00 ┆ 2021-01-02 06:00:00 ┆ 2021-01-01 06:00:00 ┆ [6]             │
│ 2021-12-31 06:00:00 ┆ 2022-01-01 06:00:00 ┆ 2021-12-31 06:00:00 ┆ [7, 8]          │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────┘
```

**Comment by MarcoGorelli** [comment]
I think this is expected then? Closing then, but please do ping me if I've missed something, thanks 🙏
