### ISSUE TITLE
When a hive partitioned parquet file also contains the same column as a key used in the partitioning scheme it creates a duplicate column

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#12036]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

If you have a parquet file with:
```
yo, test
haha, 5
```

```python
In [22]: ldf = pl.scan_parquet("table/**/*.parquet") # path table/yo=haha/file.parquet

In [23]: ldf.columns
Out[23]: ['yo', 'test']

In [24]: ldf.collect()
Out[24]:
shape: (1, 3)
┌──────┬──────┬──────┐
│ yo   ┆ test ┆ yo   │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ i64  ┆ str  │
╞══════╪══════╪══════╡
│ haha ┆ 5    ┆ haha │
└──────┴──────┴──────┘

In [25]: ldf.collect().columns
Out[25]: ['yo', 'test', 'yo']
```

### Issue description

Probably shouldn't get duplicate columns, probably should get either a runtime error for conflicting columns (maybe another option is to suffix one of the columns with something to de-duplicate the columns).

### Expected behavior

There probably should be an error for a conflicting column or maybe even dropping the column in the paruqet file in favor of the hive key (or maybe it should be configurable how clashes are handled).

### Installed versions

<details>

```
In [36]: pl.show_versions()
--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.9.6 (default, Aug 11 2023, 19:44:49)
[Clang 15.0.0 (clang-1500.0.40.1)]

----Optional dependencies----
adbc_driver_sqlite:  0.5.1
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           0.10.0
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.2
pyarrow:             12.0.1
pydantic:            2.0.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.18
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by ritchie46** [comment]
Ah good one. We should error. I am not a fan of adding suffixes as the hive partitioned are being used for optimizations. If you filter by column `"yo"`, which one did you mean? I don't want to go down that path.

**Comment by ritchie46** [comment]
> I think it'd be useful to support my proposal as the person querying the data often has no control over how it's written, with your PR that data is just unusable with that schema and hive partition scheme set.

I think for now it solves the bug. The other is a feature request. I think this is something we can consider, but it requires a change of how we deal with partitions and much more changes to the code.

Can you make a feature request out of your proposal?
