### ISSUE TITLE
`pl.read_excel()` returns null for filtered rows

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12054]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue Description

Setup: single sheet, one column with numbers 1-10. First five rows are filtered out.

#### test.xlsx
Data | Filter
-----|-------
![image](https://github.com/pola-rs/polars/assets/1896992/d8b511cf-6f98-4bc9-a77e-0c6e28b1ff57) | ![image](https://github.com/pola-rs/polars/assets/1896992/597ec2a9-a21a-4550-a803-e03ba519792d)

```shell
>>> import polars as pl
>>> pl.Config.set_tbl_rows(10)
>>> pl.read_excel("test.xlsx")
shape: (10, 1)
┌──────┐
│ A    │
│ ---  │
│ i64  │
╞══════╡
│ null │
│ null │
│ null │
│ null │
│ null │
│ 6    │
│ 7    │
│ 8    │
│ 9    │
│ 10   │
└──────┘
```

Note that with `engine="openpyxl"` this does not occur.

This can be resolved by using `xlsx2csv_options={"skip_hidden_rows": False}` which I believe should be the default.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.26.1
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             11.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.7
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by alexander-beedie** [comment]
> This can be resolved by using xlsx2csv_options={"skip_hidden_rows": False} which I believe should be the default.

Agreed  👍
