### ISSUE TITLE
Numpy section typo

### ISSUE THREAD

**Issue by DavidYoonsik** [pola-rs/polars#12076]
### Description

import polars as pl
import numpy as np

df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

out = df.select(np.log(pl.all()).name.suffix("_log"))
print(out)

'name' makes error...
just delete, then error is gone!

### Link

https://pola-rs.github.io/polars/user-guide/expressions/numpy/

**Comment by cmdlineluser** [comment]
It's actually using the new `.name` namespace which is not in the last release.

https://pola-rs.github.io/polars/docs/python/dev/reference/expressions/api/polars.Expr.name.suffix.html

```python
>>> df.select(np.log(pl.all()).name.suffix("_log"))
# shape: (3, 2)
# ┌──────────┬──────────┐
# │ a_log    ┆ b_log    │
# │ ---      ┆ ---      │
# │ f64      ┆ f64      │
# ╞══════════╪══════════╡
# │ 0.0      ┆ 1.386294 │
# │ 0.693147 ┆ 1.609438 │
# │ 1.098612 ┆ 1.791759 │
# └──────────┴──────────┘
```

The API docs are versioned (notice the `/dev/` in the URL) whereas I guess the User Guide is not?

**Comment by alexander-beedie** [comment]
> It's actually using the new `.name` namespace which is not in the last release.

Yup, exactly so; we're just about to release `0.19.12` (which [contains the update](https://github.com/pola-rs/polars/pull/11973) with the new `name` namespace), at which point both versions of this call will work (with `.name.suffix` being the preferred/non-deprecated form going forward). 

@stinodego, any thoughts on user guide versioning? 🤔

**Comment by stinodego** [comment]
This happened because we did a pre-release and my CI setup did not account for this. Normally, we only release the user guide when a new version is released.

I'll adjust accordingly.
