### ISSUE TITLE
Expose `object_store::limit::LimitStore` and/or `object_store::throttle::ThrottleConfig` for cloud functionality (python)

### ISSUE THREAD

**Issue by samdyzon** [pola-rs/polars#12079]
### Description

Hi Ritchie et al.,

We have been using Polars (python) with huge success in our cloud-backed data analysis tooling, but have found that AWS S3 will throw status `503` responses when attempting to run `scan_parquet` jobs on datasets with large numbers of partitions and files to scan. The AWS documentation suggests that 503 responses can be a result of rate limiting by S3.

I see that the `cloud_storage` crate has methodologies created for handling concurrency limits and request throttling, but as far as I can tell Polars does not include this functionality in `storage_options` or any other configuration available. Would it be possible to expose these to help users tune their workflows in the event of cloud storage rate limiting?

Thanks for your awesome work.

**Comment by ritchie46** [comment]
We are still actively developing the cloud functionality. As it is at the moment the objectstores are not synchronized, so it would not make sense to limit the individual stores.

I also think this error will be much, much less prevalent in next release.

**Comment by samdyzon** [comment]
Ok, no worries - I think I understand what you mean. When you mean next release, do you mean `0.19.12` which was released a few hours after your comment? I see something there about downloading parquet files, I'll try to give it a test and see if that helps with our problem.

**Comment by ritchie46** [comment]
Yeap, that's the one.
