### ISSUE TITLE
Make `values` in `pl.pivot()` optional

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#12087]
### Description

As of version 0.19.12 in Polars, you are required to explicitly define the `index`, `columns`, and `values` parameters. However, once you have defined the `index` and `columns`, the `values` columns are essentially implied, i.e., the rest of the columns are all `values` columns. It would be more convenient if you have multiple values columns. Making the `values` parameter optional could possibly be helpful (similar to the default behavior in Pandas).

**Comment by mcrumiller** [comment]
This makes sense to me as, at least in my experience, the most common use case is for `values` to refer to all remaining columns not in index/columns. However, if `values` becomes a keyword-only argument and `index`/`columns` are not, then this requires a breaking change as `values` must be moved past the first two args.

**Comment by stinodego** [comment]
This would be a welcome addition.

We have to do this in two steps:

1. Add the `deprecate_nonkeyword_parameters` decorator to `pivot`. This is required because the parameter order will have to change.
2. Change the function signature to `index, columns, values=None`, and implement the new functionality.

**Comment by mcrumiller** [comment]
@stinodego some of the work in my previous PR (which I'll close since I don't think we want that behavior) is probably relevant/reusable so I'll see if I can get this done fairly quickly using your two steps.

**Comment by stinodego** [comment]
> @stinodego some of the work in my previous PR (which I'll close since I don't think we want that behavior) is probably relevant/reusable so I'll see if I can get this done fairly quickly using your two steps.

All right. One thing to note is that the functionality for inferring the columns should be implemented in Rust - this wasn't the case in your initial PR.

**Comment by mcrumiller** [comment]
Thanks @stinodego, I'll do my best and if I can't do it I'll see if someone else can pick it up.
