### ISSUE TITLE
date_ranges -> date_range_horizontal?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#12095]
### Description

I've seen people get confused over `date_range` vs `date_ranges`. It's easy to miss the `s` at the end which makes the function do something totally different

Would renaming `date_ranges` to `date_ranges_horizontal` be more consistent with the rest of the API (e.g. `sum_horizontal`) and reduce confusion?

It's a bit verbose, but I think it's also a relatively rare operation compared with the more common `date_range`?

**Comment by MarcoGorelli** [comment]
Same with `int_range` / `int_ranges` - @stinodego thoughts?

**Comment by stinodego** [comment]
I can see how `date_ranges` and similar methods can be confusing.

Not sure about `horizontal` though as it's not really a horizontal operation... I'd like to reserve `_horizontal` for horizontal aggregations.

**Comment by MarcoGorelli** [comment]
Just for my understading, is it just the fact that it doesn't aggregate?

In my head this is exactly what I'd expect a horizontal operation to look like
```python
In [7]: df.with_columns(pl.date_ranges('start', 'end'))
Out[7]:
shape: (2, 3)
┌────────────┬────────────┬───────────────────────────────────┐
│ start      ┆ end        ┆ date_range                        │
│ ---        ┆ ---        ┆ ---                               │
│ date       ┆ date       ┆ list[date]                        │
╞════════════╪════════════╪═══════════════════════════════════╡
│ 2020-01-01 ┆ 2020-01-02 ┆ [2020-01-01, 2020-01-02]          │
│ 2020-01-02 ┆ 2020-01-04 ┆ [2020-01-02, 2020-01-03, 2020-01… │
└────────────┴────────────┴───────────────────────────────────┘
```

**Comment by stinodego** [comment]
`date_ranges` is no different from an operator like `+`  in that it takes two columns and creates a new column. I wouldn't call `+` a horizontal operation.

Horizontal operations in our API operate on any number of columns and perform some sort of (folding) aggregation.

**Comment by MarcoGorelli** [comment]
> Horizontal operations in our API operate on any number of columns

right, and these ones are just binary - that's clear, thanks, closing then

**Comment by stinodego** [comment]
> I've seen people get confused over date_range vs date_ranges. It's easy to miss the s at the end which makes the function do something totally different

I still think this is a valid point, so feel free to open a new issue if you think of a more fitting name!

**Comment by cmdlineluser** [comment]
Would `_list` be reasonable?
```python
int_range()
int_range_list()

date_range()
date_range_list()
```
