### ISSUE TITLE
Incorrect merge of categorical columns if they overlap

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars#12091]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
s1 = pl.Series(['a','b','c'],dtype=pl.Categorical)
s2 = pl.Series(['b','c','d'],dtype=pl.Categorical)
s1.extend(s2)
```

### Log output

```shell
shape: (6,)
Series: '' [cat]
[
	"a"
	"b"
	"c"
	"a"
	"b"
	"c"
]
```

### Issue description

For operations that combine two local categoricals (`zip_with`, `append`, `extend`) we incorrectly merge the two types. Right now we do a simple concat of both categories and bump the underlying physical (or in case of `extend` do not change the physical at all). When the categories overlap, this leads to strange results where there are duplicates in the categories list.

### Expected behavior

```
shape: (6,)
Series: '' [cat]
[
	"a"
	"b"
	"c"
	"a"
	"b"
	"d"
]
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-6.2.0-35-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.11.0
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.0
pydantic:            2.4.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            0.8.1
xlsxwriter:          3.1.6```

</details>

**Comment by ritchie46** [comment]
Good point. I think it is time for a proper implementation of merge that resolves both local, global and user-defined alike.

The current behavior can still exist as a fast path, but we must have checked there are no duplicates.
