### ISSUE TITLE
Support / integration for physical units, e.g. `astropy.units`

### ISSUE THREAD

**Issue by s-m-e** [pola-rs/polars#12114]
### Description

Just looking through the issues and documentations, units are mentioned nowhere - hopefully I have not overlooked something. I'd be interested to know if this has ever been a topic in `polars` and/or if there is some intention to support units, e.g. through [astropy.units](https://docs.astropy.org/en/stable/units/) or any other similar package / mechanism (there are many by now).

On a related note, if I was planning to extend `polars` similar to what `GeoPandas` does for `Pandas` for instance, what would be my options if I was planning to introduce the notion of units within a "third-party package on top of polars"?

**Comment by stinodego** [comment]
Related to #9866

We do not plan to implement this functionality directly in Polars.

You can implement an integration as a plugin. See the docs:
https://pola-rs.github.io/polars/user-guide/expressions/plugins/

More simple integrations could be done as a custom namespace. See the docs on extending the API:
https://pola-rs.github.io/polars/py-polars/html/reference/api.html
