### ISSUE TITLE
skip_rows for read_ipc

### ISSUE THREAD

**Issue by qinwf** [pola-rs/polars#12157]
### Description

add an option likes polars.read_csv(skip_rows) for large ipc file.

**Comment by ritchie46** [comment]
It is recommended to write that in your query.

```python
# skip first 100 rows.
pl.scan_ipc().slice(100, ..)
```

**Comment by deanm0000** [comment]
@stinodego not sure why ritchie didn't close this one while he was responding but anyway, here's a close candidate.
