### ISSUE TITLE
No mention of `name` accessor/method in latest stable documentation

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#12152]
### Description

I just used `.suffix` after a long time, and I got the following `DeprecationWarning`:

```
DeprecationWarning: `suffix` is deprecated. It has been moved to `name.suffix`.
```

But when I look up the documentation for `Expr.suffix`, I do not see any deprecation mentions, or any link/reference to the `name` accessor. Am I missing something, or was this an oversight in the deprecation? I see that docstrings were added in the [commit](https://github.com/pola-rs/polars/commit/ffb22ac15cf550718a43d13ccd6e4180a204962d) that introduced this, but it's not reflecting online.

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/columns.html

## Update
It's been determined in this thread that the latest version seems to be shown for 0.19.9 instead of 0.19.12 (current stable at the time of writing this).

**Comment by cmdlineluser** [comment]
It is in the "dev" version of the docs:

https://pola-rs.github.io/polars/docs/python/dev/reference/expressions/name.html

**Comment by ion-elgreco** [comment]
In the dev docs it's visible under `name`

**Comment by avimallu** [comment]
Ah, my bad. I did check this, but was too in a hurry to search better.

This brings an interesting point - the latest versions aren't `dev` releases, right? Shouldn't these be displayed in the *current* version of the docs?

**Comment by cmdlineluser** [comment]
Just in trying to find more info on the subject (as I don't know the answer):

https://github.com/pola-rs/polars/issues/11105#issuecomment-1771289741

> 0.x points to the latest 0.x release, so 0.19 currently points to 0.19.9

Which suggests it should now point to 0.19.12 and be included? (unless I'm misunderstanding)

**Comment by avimallu** [comment]
Ah, then it probably must be a case where "natural sorting" needs to be implemented i.e. to avoid 0.19.12 < 0.19.9...?

**Comment by stinodego** [comment]
> Ah, then it probably must be a case where "natural sorting" needs to be implemented i.e. to avoid 0.19.12 < 0.19.9...?

It's not, but I'll investigate what happened here.
