### ISSUE TITLE
`.str.regex_escape()`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12154]
### Description

Could [`Regex::escape()`](https://docs.rs/regex/latest/regex/fn.escape.html) be exposed?

It would allow for a native version of the common pattern:
```python
import re
import polars as pl

words = ["foo[]", "bar?", "baz."]

pl.select(pl.lit("|".join(map(re.escape, words))))

# shape: (1, 1)
# ┌─────────────────────┐
# │ literal             │
# │ ---                 │
# │ str                 │
# ╞═════════════════════╡
# │ foo\[\]|bar\?|baz\. │
# └─────────────────────┘
```

```python
pl.col("words").str.regex_escape().str.concat("|")
```

I know the namespace seems to indiciate the "type" but the naming has just made me wonder if a `.regex` namespace would make sense.

```python
pl.col("foo").regex.escape()
pl.col("foo").regex.replace()
```

Instead of the `literal: bool` parameter certain methods have.

**Comment by deanm0000** [comment]
The regex namespace is tricky b/c a lot of things in `str` would overlap. Like where does replace_all go? Would it be in both? I guess if there was `regex.replace_all()` and `str.replace_all()` then the literal parameter could come out and the literal=True version is the one in str and literal=False is in regex.

That said, I like short namespaces so if I get a vote, I'm voting for `re` over `regex` in particular b/c in the latter case, would it  actually have to be made `reg_ex` for snake case?

**Comment by cmdlineluser** [comment]
> Would it be in both?

That was the idea. (But perhaps it's not a good one.)

It was just a side thought that appeared after typing `.str.regex_replace()`

**Comment by deanm0000** [comment]
I mean I think it's fine, I just don't think the maintainers want too much redundancy.

**Comment by cmdlineluser** [comment]
Closed in favour of https://github.com/pola-rs/polars/issues/19207
