### ISSUE TITLE
illegal hardware instruction (Python 3.11.4, mac OS 14.0, m1/Silicon, not using rosetta/x86)

### ISSUE THREAD

**Issue by RobertCalise** [pola-rs/polars#12166]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
❯ .venv/bin/python
Python 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
[1]    62095 illegal hardware instruction  .venv/bin/python
```

### Log output

```shell
❯ POLARS_VERBOSE=1 .venv/bin/python
Python 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
[1]    62168 illegal hardware instruction  POLARS_VERBOSE=1 .venv/bin/python
```

### Issue description

As noted in the title, I am unable to use polars with Python 3.11 on my Mac M1. 

I initially encountered this using a pipenv-created virtual environment. However, I have also recreated a virtual environment manually and  installed via pip (`pipenv run pip install --force-reinstall -v "polars==0.19.12"`) to ensure the latest version of polars was installed.

### Expected behavior

I should be able to import and use polars

### Installed versions

<details>

```
N/A - polars cannot import
```

</details>

**Comment by orlp** [comment]
You say you're not using Rosetta, but I find that hard to believe. Can you do `pip install polars-lts-cpu` (which is the workaround regardless) and post `pl.show_versions()`?

**Comment by RobertCalise** [comment]
@orlp You're right, and this is a surprise to me. My assumption was that Python was running natively (I'm not manually activating Rosetta in my terminal), but apparently it is still running under emulation. Apologies, will adjust accordingly. Thanks for the rapid response here, closing this issue.
