### ISSUE TITLE
Panic on concurrent sink_parquet()

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#12167]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from random import randint
from threading import Thread

import polars as pl

df = pl.DataFrame({
    'A': [randint(0, 10**10) for _ in range(1000)],
    'B': [randint(0, 10**10) for _ in range(1000)]
})
df.write_parquet('test1.pq', compression='zstd')
df.write_parquet('test2.pq', compression='zstd')
df.write_parquet('test3.pq', compression='zstd')
df.write_parquet('test4.pq', compression='zstd')

def _sink_pq(target_path, file_paths):
    dfs = [pl.scan_parquet(file_path) for file_path in file_paths]
    pl.concat(dfs).sink_parquet(target_path, compression='zstd', maintain_order=False)



for i in range(1000):
    t1 = Thread(target=_sink_pq, args=('target1.pq', ['test1.pq', 'test2.pq']))
    t2 = Thread(target=_sink_pq, args=('target2.pq', ['test3.pq', 'test4.pq']))
    t1.start()
    t2.start()
    t1.join()
    t2.join()

```

### Log output

```shell
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
pyo3_runtime.
PanicException: Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

### Issue description

When sink_parquet executes in different threads at the same time, it may lead to PanicException: Cannot start a runtime from within a runtime.

### Expected behavior

Make sink_parquet thread safe.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-6.2.0-35-generic-x86_64-with-glibc2.35
Python:              3.11.6 (main, Oct 23 2023, 22:48:54) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I will take a look, but I am not entirely sure this is something we can/should fix as it could mean that we lose the ability to have an async runtime.

But I will take a look. It should at least be possible if we don't do async stuff.

**Comment by deanm0000** [comment]
It's a weird use case b/c typically when you're streaming you wouldn't have the ram to be doing a lot of things concurrently. If you do have the ram to do it all concurrently then with a few tweaks you can make it work through the async collect method.

```
async def _sink_pq(target_path, file_paths):
    dfs = pl.concat([pl.scan_parquet(file_path) for file_path in file_paths])
    dfs = await dfs.collect_async()
    def _write(dfs, target_path):
        dfs.write_parquet(target_path, compression='zstd')
    t1=Thread(target=_write, args=(dfs, target_path))
    t1.start()

tasks = [asyncio.create_task(_sink_pq(f"target{x}.pq", [f"test{x%2+y}.pq" for y in range(1,3)])) for x in range(1,101)]
await asyncio.wait(tasks)
```

Alternatively you can use multiprocessing instead of threads 
https://pola-rs.github.io/polars/user-guide/misc/multiprocessing/

**Comment by s-b90** [comment]
> It's a weird use case b/c typically when you're streaming you wouldn't have the ram to be doing a lot of things concurrently. If you do have the ram to do it all concurrently then with a few tweaks you can make it work through the async collect method.
> 
> ```
> async def _sink_pq(target_path, file_paths):
>     dfs = pl.concat([pl.scan_parquet(file_path) for file_path in file_paths])
>     dfs = await dfs.collect_async()
>     def _write(dfs, target_path):
>         dfs.write_parquet(target_path, compression='zstd')
>     t1=Thread(target=_write, args=(dfs, target_path))
>     t1.start()
> 
> tasks = [asyncio.create_task(_sink_pq(f"target{x}.pq", [f"test{x%2+y}.pq" for y in range(1,3)])) for x in range(1,101)]
> await asyncio.wait(tasks)
> ```
> 
> Alternatively you can use multiprocessing instead of threads https://pola-rs.github.io/polars/user-guide/misc/multiprocessing/

My task is simple: concat several parquet fiels in single parquet in streaming manner to not overload memory.
As I understand, dfs.collect_async() will load all frames into memory and only after that, it will write it into parquet file.
So the case of using sink_parquet is generally in reducing memory usage.
Of course, I'm not using threading just to speed up files concatenation.  My program using threads for long pipelines, at the end of each there is file concatenation. There was just a small reproducible example in description. Maybe it will help others.
Thanks for fix @ritchie46 and for polars!
