### ISSUE TITLE
Add `DataType.is_integer()` and similar for data type checking

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#12196]
### Proposal

Add methods to the DataType class for checking the data type. This already exists on the Rust side, e.g. `is_integer`, `is_temporal`, etc.

```python
# dtype group
if dtype.is_integer():
    ...

# specific dtype
if dtype.is_datetime():
    ...
```

This replaces the current method of checking data types:

```python
# dtype group
if dtype in pl.INTEGER_DTYPES:
    ...

# specific dtype
if dtype == pl.Datetime:
    ...
```

It also replaces Series methods for checking dtypes, e.g. `series.is_integer()` will be deprecated and replaced by `series.dtype.is_integer()`. If you think about it, a Series is not an integer, the data type is.

#### Datatypes with properties

Checking for a data type with certain properties can still be done using the equality operator. This does not change.

```
if dtype == pl.Datetime(time_zone="UTC"):
    ...

if dtype == pl.List(pl.Int16):
    ...
```

Though an alternative syntax is now also available:

```
if dtype.is_datetime() and dtype.time_zone == "UTC":
    ...

if dtype.is_list() and dtype.inner.is_int16():
    ...
```

In the future, when data types are instantiated, we can also consider adding optional parameters to `is_datetime` such that the following syntax becomes possible:

```python
if dtype.is_datetime(time_zone="UTC"):
    ...

if dtype.is_list(pl.Int16):
    ...
```

This would allow checking certain properties but not others (e.g. check time zone but not time unit).

### Implementation

Implementation is extremely simple. The class hierarchy is already in place, we only have to add classmethods to the `DataType` class like so:

```python
class DataType:

    @classmethod
    def is_integer(cls) -> bool:
        return issubclass(cls, IntegerType)
```

### Pros / cons

The new method has some advantages:

* Offers auto-completion
* Very readable syntax
* Mirrors the Rust functionality
* Offers some relief for the issues related to some data types being classes while others being instances (#6163)

I really cannot think of a negative here.

### Methods

Data type groups:

* [x] `is_integer`
* [x] `is_signed_integer`
* [x] `is_unsigned_integer`
* [x] `is_float`
* [x] `is_numeric`
* [x] `is_temporal`
* [ ] `is_nested`

Single data types:

* [ ] `is_boolean`
* [ ] `is_int8` / `is_int16` / `is_int32` / `is_int64` 
* [ ] `is_uint8` / `is_uint16` / `is_uint32` / `is_uint64` 
* [ ] `is_float32` / `is_float64`
* [ ] `is_date`
* [ ] `is_time`
* [ ] `is_binary`
* [ ] `is_string` / `is_utf8` (aliases of each other)
* [ ] `is_categorical`
* [ ] `is_null`

Single data types with properties:

* [ ] `is_datetime(time_unit, time_zone)`
* [ ] `is_duration(time_unit)`
* [ ] `is_decimal(precision, scale)`
* [ ] `is_list(inner)`
* [ ] `is_array(inner, width)`
* [ ] `is_struct(schema)`

### References

PyArrow has similar functionality, but implemented as functions, i.e. `pa.types.is_integer`:
https://arrow.apache.org/docs/python/api/datatypes.html#type-checking

**Comment by MarcoGorelli** [comment]
first impression - nice!

**Comment by orlp** [comment]
One advantage (?) of it being a function rather than a method is that `pl.types.is_integer(int)` works whereas `x.is_integer()` doesn't work if `x` isn't a Polars data type.

**Comment by stinodego** [comment]
> One advantage (?) of it being a function rather than a method is that `pl.types.is_integer(int)` works whereas `x.is_integer()` doesn't work if `x` isn't a Polars data type.

I'm not sure we would want that to work. PyArrow also doesn't work like that:

```
>>> import pyarrow as pa
>>> pa.types.is_integer(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/code/polars/.venv/lib/python3.11/site-packages/pyarrow/types.py", line 66, in is_integer
    return t.id in _INTEGER_TYPES
           ^^^^
AttributeError: type object 'int' has no attribute 'id'
```

And you could make a case that this should return False, or True... confusing. You would also lose auto-completion. I'm not a fan.

**Comment by ritchie46** [comment]
> If you think about it, a Series is not an integer, the data type is.

Wholeheartedly agree.

Agree on all clustered `is_*`.

I am not sure about the specific ones. E.g. `is_i32` etc. But we can decide that one later I think.

**Comment by stinodego** [comment]
> Agree on all clustered is_*.

Great, there's a PR up for those already!

> I am not sure about the specific ones. E.g. `is_i32` etc. But we can decide that one later I think.

Actually, those are really important. Let me try to explain my thinking here.

### The issue

We currently use the equality operator for type checking single types, e.g. `dtype == pl.Int32`. This syntax is quite readable and intuitive. However, it gets finnicky with datatypes that have properties, like `Datetime`.

```python
# Define our data type
dtype = pl.Datetime("ns", time_zone="UTC")

# Do some checks
dtype == pl.Datetime  # True, thanks to our custom equality implementation
dtype == pl.Datetime("ns", time_zone="UTC")  # True
dtype == pl.Datetime(time_zone="UTC")  # False!?
```

The last equality operation returns False because the data type is instantiated as thus it sets the `time_unit` to the default value `"us"`, which does not match our dtype. To check for a Datetime with a specific time zone, we need to write:

```python
dtype == pl.Datetime and dtype.time_zone == "UTC"  # type: ignore[union-attr]
```

Mypy doesn't like this, but it works. However, clearly this syntax is very cumbersome. And I would classify it was a workaround for unexpected behavior.

### Impact

The current way to determine a data type leads to unexpected behavior in some cases that is cumbersome to work around. That should be reason enough to consider alternatives. But it also blocks the implementation of #6163.

The way I currently envision that solution, calling `pl.Datetime` will be a shortcut for calling `pl.Datetime()`, thus it will result in a data type instance with default properties: `time_unit="us"`, `time_zone=None`.

However, that change would break the current equality operation:

```python
dtype = pl.Datetime("ns", time_zone="UTC")

dtype == pl.Datetime  # False!
dtype == pl.Datetime("ns", time_zone="UTC")  # True
dtype == pl.Datetime(time_zone="UTC")  # Still False
```

So we need a good way to check that a certain data type object is of a certain type.

### The solution

The solution outlined in this issue solves the above issues quite elegantly.

Checking for a data type is done calling a method on the object itself. Next to existing methods like `is_integer`, `is_temporal`, I can use `is_datetime`. That's very natural - as a user, I would expect that method to exist. And it has auto-completion.

It's also easy to facilitate the transition to instantiated data types. `dtype.is_datetime()` still works, whether it's a class or an instantiated class.

Once we make the transition to instantiated data types, it will also be easy to add optional parameters for checking properties. For example, it will be easy to check a time zone but ignore the time unit using `is_datetime(time_zone="UTC")`.

### Conclusion

So this is quite an elaborate story. And that's really the issue: the way our data types work have become unnecessarily complicated. We _need_ to make some changes here, and I think these type checking methods are necessary to improve the situation.

**Comment by alexander-beedie** [comment]
FYI: `is_integer()` could behave much like `is_datetime` so we don't have an enormous over-representation of _specific_ integer types, eg -

`dtype.is_integer()` matches all integers
`dtype.is_integer(32)` matches `i32` and `u32`
`dtype.is_signed_integer(32)` matches only `i32`

etc.

**Comment by stinodego** [comment]
I don't think that's a good idea. That leaves room to accidentally type `dtype.is_integer(31)`. The autocomplete is what makes this proposal work. I don't see the problem with having a some methods on the DataType class. We don't have _that_ many data types.

**Comment by alexander-beedie** [comment]
> I don't think that's a good idea. That leaves room to accidentally type `dtype.is_integer(31)`. 

That would just raise an error ;)

It seems consistent with `datetime` behaviour, which (currently) doesn't seem to have dedicated methods per time_unit (or, god help us all, per timezone :)) Otherwise is the proposal to have a catch-all `is_integer()` _in addition_ to all of the specialisations?

**Comment by stinodego** [comment]
> It's certainly explicit, but then why wouldn't we also want is_datetime_ms, is_datetime_us, and is_datetime_ns in addition to is_datetime?

Those aren't different datatype classes though. These type checking methods should mimic the data type classes / inits, at least that makes sense to me. If we had a `UInt` class with a `bit_width` parameter then I would agree with you.

**Comment by alexander-beedie** [comment]
Fair enough; that's more related to an implementation detail though, rather than something fundamental to the experience of _using_ the API.

Just to lay it all out, this would be... 

`is_integer()`
`is_signed_integer()`
`is_unsigned_integer()`
`is_integer_8()`
`is_integer_16()`
`is_integer_32()`
`is_integer_64()`
`is_signed_integer_8()`
`is_signed_integer_16()`
`is_signed_integer_32()`
`is_signed_integer_64()`
`is_unsigned_integer_8()`
`is_unsigned_integer_16()`
`is_unsigned_integer_32()`
`is_unsigned_integer_64()`

...vs...

`is_integer(...)`
`is_signed_integer(...)`
`is_unsigned_integer(...)`

...where "..." would be empty/None to match _all_ sizes, or 8, 16, 32, 64 for a _specific_ size. 

I'm not going to the matresses[^1] over it, but my instinct is that the latter is both tidier, and more consistent (API-wise) with how datetime/duration (eg: `is_datetime("ms")`) and nested dtypes (eg: `is_list(Utf8)`) would be specified.

[^1]: https://en.wiktionary.org/wiki/go_to_the_mattresses

**Comment by stinodego** [comment]
Not exactly - I laid out all the methods in the OP. There would be no `is_signed_integer_16` as this is not a data type. With regards to integers, it would be:

Groups:
* `is_integer`
* `is_unsigned_integer`
* `is_signed_integer`

Single dtypes:
* `is_int8` / `is_int16` / `is_int32` / `is_int64` 
* `is_uint8` / `is_uint16` / `is_uint32` / `is_uint64` 

I would say `dtype.is_int8()` is a lot cleaner than `dtype.is_integer(8)` having to type out the correct bit width yourself.

**Comment by alexander-beedie** [comment]
> Not exactly - I laid out all the methods in the OP. 

Indeed, I over-typed those ;)

Seems there is no way to say "give me the 32 bit integers" this way though (irrespective of signed/unsigned) - which is a common use-case where you're looking at memory usage. I guess you can always compose it as `is_int32() | is_uint32)` 🤷

**Comment by stinodego** [comment]
Yeah, there will be some composing. If you want "all temporal types but not Time", you'll type `dtype.is_temporal() and not dtype.is_time()`. I think that's completely fine.

**Comment by stinodego** [comment]
After discussion with Ritchie, we'll only do dtype groups for now. The single-data type checks do not work nicely for nested types.

That means this can be closed now. I'll be approaching this differently.
