### ISSUE TITLE
Upsample on integer index documented, but not working

### ISSUE THREAD

**Issue by sm-Fifteen** [pola-rs/polars#12207]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

vert_df1 = pl.DataFrame(
    {
        "array_name": ["arr_1"] * 4,
        "array_idx": [0, 3, 4, 5],
        "array_val": [33, 34, 34, 33],
    }, {
        "array_name": pl.datatypes.Utf8,
        "array_idx": pl.datatypes.UInt32,
        "array_val": pl.datatypes.Float32
    }
).set_sorted("array_name", "array_idx")

vert_df1.upsample(
    time_column="array_idx", every="1i", by="array_name"
)
```

### Log output

```shell
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[13], line 15
      1 import polars as pl
      3 vert_df1 = pl.DataFrame(
      4     {
      5         "array_name": ["arr_1"] * 4,
   (...)
     12     }
     13 ).set_sorted("array_name", "array_idx")
---> 15 vert_df1.upsample(
     16     time_column="array_idx", every="1i", by="array_name"
     17 )

File .pyenv310\lib\site-packages\polars\dataframe\frame.py:5727, in DataFrame.upsample(self, time_column, every, offset, by, maintain_order)
   5723 every = _timedelta_to_pl_duration(every)
   5724 offset = _timedelta_to_pl_duration(offset)
   5726 return self._from_pydf(
-> 5727     self._df.upsample(by, time_column, every, offset, maintain_order)
   5728 )

ComputeError: upsample not allowed for index column of dtype u32
```

### Issue description

While the docs for `upsample()` mention the possibility of using `every="1i"` to upsample over a linearly increasing index count, presumably working like described in `group_by_dynamic()` where it implies that the column is an integer value instead of a datetime value, upsample does not work on index columns. It appears to only support datetime columns.

Additionally, the `offset` parameter only accepts datetime values, not integer values.

### Expected behavior

`upsample` with an index period specifier should work to fill gaps in integer index columns. The code example above should return a dataframe with new rows added for `array_idx = 1` and `array_idx = 2`, but no values for `array_val`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Windows-10-10.0.19042-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         3.0.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              1.4.4
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.3.24
xlsx2csv:            <not installed>
xlsxwriter:          3.1.9
```

</details>

**Comment by JulianCologne** [comment]
Can confirm.
This is only implemented for [Datetime](https://github.com/pola-rs/polars/blob/faa9c63a4c82033328c99c34ba6b0b894a5fc2bd/crates/polars-time/src/upsample.rs#L169C6-L169C6)

This might be confusing as the docs are every similar for this and `rolling` or `group_by_dynamic` ( though they mention explicitly that they work with `i32` and `i64`)

I definetly see use cases for `upsample` working with ints and implenetation should be quite easy (?) as the calculation is actually done as integers anyway.

If this is impleneted is might make sense to deprecate the `time_column` argument in favor of the `index_column` that `rolling` or `group_by_dynamic` use.

**Comment by MarcoGorelli** [comment]
thanks for the report - yeah this one should work on unsigned integers too, they should be preserved under upsampling

**Comment by sm-Fifteen** [comment]
Mind you, the main use case I'm thinking of for this is something like

```py
vert_df1.upsample(
    time_column="array_idx", every="1i", by="array_name", offset=0, 
).group_by("array_name").agg(
    pl.col("array_val").sort_by("array_idx")
)
```

to pivot vertically stored sparse arrays into actual Polars arrays (as opposed to numbered columns) and to ensure that there are no missing elements in various other uniform/grid-like data formats. I'm not sure if that use of offset matches with what it's used for with time series, because that parameter isn't documented for `upsample()` either.

**Comment by cmdlineluser** [comment]
Looking at how upsample works:
https://github.com/pola-rs/polars/blob/ea414351f1e38cd2b339775369074b5907dee438/crates/polars-time/src/upsample.rs#L190-L201

It seems in this example, it would end up doing the equivalent of:
```python
(df.group_by("array_name")
   .agg(array_idx = pl.int_range(pl.min("array_idx"), pl.max("array_idx") + 1))
   .explode("array_idx")
   .join(df, on=["array_name", "array_idx"], how="left")
)
```
Just out of interest, as you actually want the final list column, I wonder if this can also be done inside `.agg()` directly somehow?
```python
idxs = pl.int_range(pl.min("array_idx"), pl.max("array_idx") + 1)

(df.group_by("array_name")
   .agg(
       idxs.is_in("array_idx").not_().arg_true(), 
       "array_idx", 
       "array_val"
   )
)   

# shape: (1, 4)
# ┌────────────┬───────────┬──────────────┬──────────────────────────┐
# │ array_name ┆ int       ┆ array_idx    ┆ array_val                │
# │ ---        ┆ ---       ┆ ---          ┆ ---                      │
# │ str        ┆ list[u32] ┆ list[u32]    ┆ list[f32]                │
# ╞════════════╪═══════════╪══════════════╪══════════════════════════╡
# │ arr_1      ┆ [1, 2]    ┆ [0, 3, 4, 5] ┆ [33.0, 34.0, 34.0, 33.0] │
# └────────────┴───────────┴──────────────┴──────────────────────────┘
```

**Comment by MichalLebeda** [comment]
The error message is also very confusing, it seems like the problem is with the column type, not that the feature is missing
