### ISSUE TITLE
Typo on read_excel page

### ISSUE THREAD

**Issue by ianozsvald** [pola-rs/polars#12208]
### Description

"engine in ocnjunction with the" should read "conjunction":
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

**Comment by mcrumiller** [comment]
Duplicate of #11931 which has already been fixed via #11934.

**Comment by stinodego** [comment]
Will be fixed with the next release.
