### ISSUE TITLE
Unexpected behavior from the “_saturating” suffix

### ISSUE THREAD

**Issue by knutmerket** [pola-rs/polars#12218]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import date

# Create a Polars DataFrame
data = {
    "customer_id": [1],
    "sales_sum": [100.50],
    "booking_date": [date(2020, 7, 31)],
    "merchant_id":["13"]
}

df = pl.DataFrame(data)

(df
.sort(["booking_date", "customer_id"])
.rolling(index_column="booking_date", period="1mo_saturating", by="customer_id")
.agg(
    pl.col("sales_sum").sum().alias("sales_sum_1mo"),
    pl.col("merchant_id").n_unique().alias("merchants_for_cust_1mo"),
)
)
```

### Log output

```shell
┌─────────────┬──────────────┬───────────────┬────────────────────────┐
│ customer_id ┆ booking_date ┆ sales_sum_1mo ┆ merchants_for_cust_1mo │
│ ---         ┆ ---          ┆ ---           ┆ ---                    │
│ i64         ┆ date         ┆ f64           ┆ u32                    │
╞═════════════╪══════════════╪═══════════════╪════════════════════════╡
│ 1           ┆ 2020-07-31   ┆ 0.0           ┆ null                   │
└─────────────┴──────────────┴───────────────┴────────────────────────┘
```

### Issue description

I'm doing some rolling aggregations on different time periods. When using the “_saturating”-suffix for months in the period-argument of polars.DataFrame.rolling I'm seeing some unexpected behavior.

This may not be a "bug" per se, but I do believe most would agree that it's unexpected behavior. Though I'm not 100% sure what expected behvaior would be in this case.

In the provided example we are using .rolling where a date column is the index and the grouping is done of customer.

In the cases where the customer has only one order in the rolling period under consideration, and that order was placed on the last day of a month (where the end day number of the month is higher than the enda day number of the month we are rolling back to) zeroes and nulls are returned. I.e. the order(s) on the date we are looking back from are omitted from the aggregations.

It makes sense from one point of view (from July 31 we go back to the last day of the previous month, June 30, and then forward one month, to July 30), but I can't think of any usecase where this is actually what the user wants.

### Expected behavior

Unsure. June 30 - July 31 or July 1 - July 31?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-4.14.326-245.539.amzn2.x86_64-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

</details>

**Comment by knutmerket** [comment]
The more I think about this issue the more confused I feel about what an appropriate behavior would be. For my use case it is probably better to avoid ambiguity by using day periods instead ("calendar month" compliance not required). But perhaps some sort of warning should be issued when the user uses a backwords-looking manipulation such as "rolling" with a "_saturating"-suffix?

**Comment by ritchie46** [comment]
I am going to ping @MarcoGorelli first to have his opinion.

**Comment by MarcoGorelli** [comment]
> This may not be a "bug" per se, but I do believe most would agree that it's unexpected behavior

Yeah agree, will think about this one

**Comment by MarcoGorelli** [comment]
currently, the windows are:

- (t + offset, t + offset + period]
- ...

where by default `offset` is `-period`. Maybe there's a way of doing `t + (offset + period)` rather than `(t + offset) + period`, so that in the default case (`offset == -period`), the upper bound won't change

**Comment by JulianCologne** [comment]
> doing `t + (offset + period)` rather than `(t + offset) + period`

wow, great idea! I think this might work!

This addresses the problem perfectly because the "bug" currently is:
- `t + offset`
- conditinally CHANGE the date (e.g. 2020-06-31 -> 2020-06-30)
- add `period` 

even if `offset = -period` this will not end at the same date (if saturation occurs)

This might be premature optimization but for the most common use case (probably 95%+) where we use `offset = -period` there is **no need to calculate the upper bound** (t already IS the upper bound)!

**Comment by MarcoGorelli** [comment]
thanks - just tried this, and the output from https://github.com/pola-rs/polars/issues/12216#issue-1975651328 would then look like this:
```python
shape: (5, 4)
┌────────────┬───────────┬────────────┬────────────┐
│ date       ┆ vals      ┆ date_min   ┆ date_max   │
│ ---        ┆ ---       ┆ ---        ┆ ---        │
│ date       ┆ list[i64] ┆ date       ┆ date       │
╞════════════╪═══════════╪════════════╪════════════╡
│ 2020-06-29 ┆ [1]       ┆ 2020-06-29 ┆ 2020-06-29 │
│ 2020-06-30 ┆ [1, 2]    ┆ 2020-06-29 ┆ 2020-06-30 │
│ 2020-07-30 ┆ [3]       ┆ 2020-07-30 ┆ 2020-07-30 │
│ 2020-07-31 ┆ [3, 4]    ┆ 2020-07-30 ┆ 2020-07-31 │
│ 2020-08-01 ┆ [3, 4, 5] ┆ 2020-07-30 ┆ 2020-08-01 │
└────────────┴───────────┴────────────┴────────────┘
```
which looks like you're expected output

Will clean it up, a PR should be on its way before too long

**Comment by JulianCologne** [comment]
> Defining addition between `Duration`s is really tricky. Is `Duration{months=1, negative=false} + Duration{weeks=4, negative=true}` positive or negative?

oh yes, I see the problem 🤔 


> But the good news is that I don't think it's necessary. Rather, @JulianCologne 's suggestion of using an early return solves everything.

yeah 😎 


> then I think this should work? For non-default `offset`s, the exact desired output may vary across users, but if we document the above, then it should at least be clear what to expect

agree, this looks like a great solution!

**Comment by JulianCologne** [comment]
@MarcoGorelli I was thinking about rolling a lot and it might be worth rethinking the implementation/parameters to make rolling easier for users and also simplify implementation (while also removing all weird corner cases like this issue).
I shared my thought here: https://github.com/pola-rs/polars/issues/12049#issuecomment-1796426869

### Quick Summary

```python
df.rolling(
    by: ...,
    preceding: ... = None,
    following: ... = None,
    closed: ...,
)
```

Windows will be the following
- `t_i - preceding, t_i + following`

Very intuitive to use and also simpler to implement without any corner cases (also people know this idea of `preceding`/`following` from sql window/over functions which use the same keywords!)

### Examples
- last month saturating (this issue): `predecing = '1mo_saturating'`
- 3 past days: `predecing = '3d'`
- 5 next days: `following = '5d'`
- 1 week centered = `preceding = '3d'`, `following= '3d'`

### Note
`group_by_dynamic` will not be affected. It's window concept is different and parameters like `every`/`period`/`offset` make a lot of sense there but imo not for `rolling`
