### ISSUE TITLE
Add .transform method

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#12222]
### Description

It is not uncommon to have a list of functions to transform a dataframe, and to store them in a dictionary keyed by column name. It'd be nice to be able to "apply" these functions easily.

For example:

```python

def foo(col:pl.Expr)->pl.Expr:
    ...

def bar(col:pl.Expr)->pl.Expr:
    ...

transformations = {
    'Income': foo, 
    'Age': foo, 
    'Taxes': bar, 
    'Weight': bar,
    'Height': foo,
}

# Imagine some appropriate data
df = ...

# This is how I would currently apply these transformations
df.with_columns(**{ pl.col(col_name).pipe(func) for col_name, func in transformations.items()})

# This is what I'm proposing (equivalent to the above)
df.with_columns(pl.all().transform(transformations))

# Or maybe
df.with_columns(pl.all().transform(**transformations))
```

**Comment by mkleinbort-ic** [comment]
To add a few more notes to the proposed usage:

This:

```python
df.with_columns(**{ pl.col(name).pipe(func).name.suffix('_transformed') for name, func in transformations.items()})
```

Should become:
```python
df.with_columns(pl.all().transform(**transformations).name.suffix('_transformed'))
```


Though, to argue against myself, I could also do this:

```python
transformation_expressions = {pl.col(name).pipe(func for name,func in transformations.items()}
```

Then this works:

```python
df.with_columns(**transformation_expressions)
```

Though is not as composable as the proposed `.transform` method.

**Comment by mkleinbort-ic** [comment]
Yes, our old friend Pandas calls it `transform`, but I never liked the name much.

**Comment by stinodego** [comment]
> `df.with_columns(**{ pl.col(col_name).pipe(func) for col_name, func in transformations.items()})`

I don't see a lot wrong with this.

Modifying `pipe` to allow dict inputs definitely seems like a bad idea.

I'm not convinced we need to add anything to the API here.

**Comment by mkleinbort-ic** [comment]
It can be convenient - we have many of these "transformations" dicts lying around (eg. in config files).

It would not be hard to implement this feature as a pl.DataFrame -> pl.DataFrame function

E.g
```python
from typing import Callable 

def my_transform(df, transformations_dict:dict[str, Callable]):
    return df.with_columns(**{ pl.col(col_name).pipe(func) for col_name, func in transformations_dict.items()})

df.pipe(my_transform, transformations_dict={...})
```
But that implementation is very hard to compose with other methods (eg. `.over()`, `.name.suffix()`, etc...)

Alternatively this could be implemented on the `pl.Expr` object - but that's beyond my understanding of the polars internals. I can imagine this function:

```python
def my_transform(pl.Expr, transformations_dict:dict[str, Callable])->pl.Expr:
    ...

df.with_columns(pl.all().pipe(my_transform, transformations_dict).over('countryId').suffix('_normalized'))
```

But no idea how it could be implemented. 

Ps. I like this as an extension of `.pipe()` - I can imagine it being abused but that's not too bad. I imagine this would probably work:

```python
transformations_dict = {
   cs.numeric(): foo, 
   cs.string(): bar, 
   cs.temporal(): baz,
} 
```
And I imagine these two would be equivalent:

```python
df.with_columns(cs.numeric().pipe(foo), cs.string().pipe(bar), cs.temporal().pipe(baz))
df.with_columns(pl.all().pipe(**transformations_dict))
```

**Comment by ritchie46** [comment]
> df.with_columns(**{ pl.col(col_name).pipe(func) for col_name, func in transformations.items()})

This is a perfect valid solution.

I definitely don't think we should bloat our API for this. If you want to store functions in dictionaries, you shouldn't fear a little bit of functional programming to apply these functions.

**Comment by mkleinbort-ic** [comment]
More general question then... is there a way to pipe a group of expressions to another function/method?

I ask because it's unclear to me how to pipe the  result of `[pl.col(col_name).pipe(func) for col_name, func in transformations.items()]` to further operations (eg. `.name.suffix()` or `.over()`, or `.mean()`, etc..)

More genraly, if I have a group of `pl.Expr` objects `[expr1, expr2, expr3]`

How can I use methods on them?

```python

df.with_columns(pl.col('A', 'B', 'C').name.suffix('_transformed')) # This works
df.with_columns(pl.col(expr1, expr2, expr3).name.suffix('_transformed')) # This code does not work, but the fix is unclear
```

See here some sample code to illustrate the issue:

```python
df = pl.DataFrame({
    'feature_1': [0.5],
    'feature_2': ['A']
})

expr1 = pl.col('feature_1') + 1
expr2 = pl.col('feature_2').str.to_lowercase()

df.with_columns(
    pl.col(expr1, expr2).name.suffix('_transformed') # How would you solve this?
)
```

**Comment by alexander-beedie** [comment]
Actually... having just put together a prototype I quite like this - feels quite clean and consistent with what we offer via `with_columns` kwargs, etc. I'll put it up as a Draft PR in a second so everyone can take a second look with actual code 🤔

**Comment by ion-elgreco** [comment]
Looks very useful to me for feature engineering. I can just create config of features an pass those around between training jobs.

**Comment by mkleinbort** [comment]
> Looks very useful to me for feature engineering. I can just create config of feature transform functions and pass those around between training jobs.

That's my use case.

**Comment by cmdlineluser** [comment]
> More generally, if I have a group of pl.Expr objects [expr1, expr2, expr3]
> How can I use methods on them?

As you have expression the objects, you can loop through them:
```python
df = pl.DataFrame({
    'feature_1': [0.5],
    'feature_2': ['A']
})

expr1 = pl.col('feature_1') + 1
expr2 = pl.col('feature_2').str.to_lowercase()

exprs = expr1, expr2

df.with_columns(
    expr.name.suffix('_transformed') for expr in exprs
)

# shape: (1, 4)
# ┌───────────┬───────────┬───────────────────────┬───────────────────────┐
# │ feature_1 ┆ feature_2 ┆ feature_1_transformed ┆ feature_2_transformed │
# │ ---       ┆ ---       ┆ ---                   ┆ ---                   │
# │ f64       ┆ str       ┆ f64                   ┆ str                   │
# ╞═══════════╪═══════════╪═══════════════════════╪═══════════════════════╡
# │ 0.5       ┆ A         ┆ 1.5                   ┆ a                     │
# └───────────┴───────────┴───────────────────────┴───────────────────────┘
```

I think this came up previously but can't recall the issue, It sounds like you may be asking for a "container" of multiple expressions?

```python
exprs = pl.exprs(
    pl.col('feature_1') + 1,
    pl.col('feature_2').str.to_lowercase()
)

df.with_columns(exprs.name.suffix('_transformed'))
```

**Comment by mkleinbort** [comment]
> I think this came up previously but can't recall the issue, It sounds like you may be asking for a "container" of multiple expressions?

yes, and I like `pl.exprs` - it would also solve the ask mentioned in https://github.com/pola-rs/polars/pull/12228#issuecomment-1793470652 

I think it could be called `pl.exprs`, `cs.exprs`, `cs.select`, or be extra functionality on `pl.col`

In general we don't have a way in polars to chain methods across lists/dicts of expressions - `pl.exprs` would allow:

```python
def min_max_scaler(col.Expr)->pl.Expr:
    return (col - col.min()) / (col.max() - col.min())

def standard_scaler(col.Expr)->pl.Expr:
    return (col - col.mean()) / col.std()

transformations = {
    'Age': standard_scaler, 
    'Income': standard_scaler, 
    'HomeSize': min_max_scaler
}

transformation_expressions = [pl.col(name).pipe(func) for name, func in transformations.items()

df.with_columns(
         pl.exprs(transformation_expressions).name.suffix('_scaled),
         pl.exprs(transformation_expressions).over('Region').name.suffix('_scaled_by_region')
)

```

etc...

**Comment by mkleinbort-ic** [comment]
Closing this in favour of https://github.com/pola-rs/polars/issues/12262, since the ask there would make the implementation of the ask here trivial. 

In particular, if python lists of expressions could casted to an expression, then it'd be easy to implement column-level transformations via `pl.Expr.pipe`.
