### ISSUE TITLE
Add support for UTF-8 BOM option in CSV Output

### ISSUE THREAD

**Issue by hirohira9119** [pola-rs/polars#12241]
### Description

While polars can only output CSV in UTF-8 encoding, the default encoding in Windows is ANSI.
This causes problems as an application may not correctly interpret non-ASCII characters, when they cannot detect the correct UTF-8 encoding.
In particular, some applications does not allow users to specify the default encoding (e.g. Excel).

A easy way to solve this issue is to use the UTF-8 Byte Order Mark (BOM).
Simply add the 3-byte magic sequence at the beginning of the file, the application can recognize the encoding as UTF-8 with BOM.
And there is no need to convert the data.

Currently, I am achieving this by explicitly writing the BOM in the code, like this:

```python
# Current
with open('a_file_path.csv', 'wb') as f:
    utf8bom = ''.encode('utf_8_sig')
    f.write(utf8bom)
    df.write_csv(f)
```

I believe it would be convenient if this functionality could be provided through the polars API.
Specifically, I am proposing the following addition:

```python
# New option for write_csv & sink_csv
"""
has_bom: bool = False
    Whether to include BOM in the CSV output.
"""
df.write_csv('a_file_path.csv', has_bom=True)
```

I would like to discuss the following points and seek input:

1. Minimalism:
While this feature is relatively simple, it does add an extra option to write_csv and sink_csv.
Given the minimalism of these API, would it be acceptable?

2. Naming:
I used "has_bom" as the parameter name in the example.
Are there alternative names or suggestions, such as "has_utf8bom," that would be more suitable?

3. Parameter position:
I will place "has_bom" after "has_header", considering the nature and meaning of the parameter.
Is there a more suitable position?

If these are resolved, I am willing to start the implementation and create a pull request.

**Comment by chandlerliuliu** [comment]
I would very much appreciate if both reading and writing include more encoding options. Sometimes I would still have to convert to_pandas in order to write to_csv(filename, encoding='utf-8-sig')
