### ISSUE TITLE
profile Expression in select context

### ISSUE THREAD

**Issue by fecet** [pola-rs/polars#12258]
### Description

It would be quite helpful if we can know how many time each expression taking. I have tried `lazyframe.pofile` but I just know there is a  large`with_columns` or `select` .

Not sure if it's duplicated with https://github.com/pola-rs/polars/issues/4654.

**Comment by ritchie46** [comment]
You can run them separately and benchmark them right? I don't think we have to include this in polars.

**Comment by fecet** [comment]
Is my understanding correct? `cache` means polars doesn't need to do group each time for same over group?

I have tried sequentially way to select, time consuming is almost the same. But I noticed every expression with `over` was very expensive (~0.3s for 96000 groups).
