### ISSUE TITLE
Weird behaviour in RAM usage when using df.filter

### ISSUE THREAD

**Issue by Chuck321123** [pola-rs/polars#12274]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from memory_profiler import profile

print("After importing memory profiler")

@profile
def my_function():

    import polars as pl
    import numpy as np
    import pandas as pd
    import random
    import time
    
    # Number of rows
    num_rows = 1000000
    
    # Create a Polars DataFrame with two columns
    df = pd.DataFrame({
        'Column1': range(1, num_rows + 1),
        'Column2': range(1, num_rows + 1)
    })
    
    # Polars version
    df = pl.DataFrame(df)
    
    df = df.filter(pl.col("Column1") <= (num_rows/2))
    
    df = df.filter(pl.col("Column1") <= (num_rows/4))
    
    df = df.to_pandas()
    
    # # Pandas version
    # df = df[df['Column1'] < (num_rows/2)]
    
    # df = df[df['Column1'] < (num_rows/4)]

my_function()
```
![Polars filter bug #1 - Temporary increases RAM](https://github.com/pola-rs/polars/assets/123987501/74cccca7-1a23-4377-b7a8-6d329fc8d4e3)
![Polars filter bug #2 - Releases too much RAM](https://github.com/pola-rs/polars/assets/123987501/95ff956a-729a-45ec-8450-67f7d7a4e87c)
![Polars filter bug #3 - Another weird behaviour](https://github.com/pola-rs/polars/assets/123987501/6cd0d35b-036e-4a30-99d1-0fe3a7f2a21a)
![Pandas filter (How the RAM should be handled)](https://github.com/pola-rs/polars/assets/123987501/f023b68d-7c75-41da-9deb-cc38ab4231aa)

### Issue description

So the expected results after using any kind of filter syntax is to release RAM from the dataframe as you delete rows from the df, but that is not always the case in polars. In polars it sometimes doesnt release the ram until several lines afterwards. Another time, it releases too much ram, but increases it afterwards, and some third time it even increases the ram temporary before releasing the ram a coule of lines later, but sometimes not the wished amount. The last scenario is very unpractical when you have several scripts running on a raspberry pi which doesnt manage ram too well in the first place. However, in pandas, it is quite straight forward. If you filter half of the rows, then half of the dataframe's ram is releases immediately which is a wishful scenario. Please see the pictures above so you will understand.

### Expected behavior

If you delete half of the rows in a dataframe then half of the dataframe's RAM should be released immediately. That doesnt happen in polars and causes weird behaviour in the RAM management.

### Installed versions

<details>

```
cloudpickle:         3.0.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.2
pyarrow:             14.0.0
python=3.12
polars=0.19.12
```
Same bug happens in older python and polars versions as well such as python 3.11.3 with polars 0.19.2
</details>

**Comment by s-banach** [comment]
What happens if you manually run gc.collect()?

**Comment by ritchie46** [comment]
The memory is released, but the memory allocator may keep it around because memory allocators would be slow if they always return pages to the OS. This is how memory allocators work.
