### ISSUE TITLE
PolarsPanicError Terminates Python Process with `signal 6: SIGABRT`

### ISSUE THREAD

**Issue by giresg** [pola-rs/polars#12279]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os
import polars as pl

os.environ["RUST_BACKTRACE"] = "1"
os.environ["POLARS_VERBOSE"] = "1"

try:
    pl.Series("a", [1, 2, 3]).reshape(())
except pl.PolarsPanicError as pe:
    print("Panic Exception Caught: ", pe)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/ops/to_list.rs:55:13:
dimensions cannot be empty
stack backtrace:
libunwind: stepWithCompactEncoding - invalid compact unwind encoding

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

### Issue description

Running `make test` on `polars/py-polars` will execute tests that throw a `PolarsPanicError`. The tests are constructed as if `PolarsPanicError` can be caught with a `try-catch` statement but it's not. Instead, the python process aborts with `signal 6: SIGABRT`.

PyO3's `panic.rs` documentation states: 

> "Like SystemExit, this exception is derived from BaseException so that it will typically propagate all the way through the stack and cause the Python interpreter to exit."

So the `PolarsPanicError` should behave as an `Exception` but doesn't.

The first and biggest issue is that the unit tests do not execute normally: `tests/unit/test_errors.py .......Fatal Python error: Aborted`

The second is more of a style issue. Looking through the codebase, the `panic!` macro is executed multiple times in situations where a `polars_ensure` or `polars_bail` fit better:

<img width="731" alt="image" src="https://github.com/pola-rs/polars/assets/7747862/5b80a134-eaa8-4d81-b746-bf7024c40e8f">

### Expected behavior

1. Unit-tests execute successfully
2. `PolarsPanicError` does not terminate Python with `signal 6: SIGABRT`
3. (or) `PolarsPanicError` usage is re-examined to throw errors (`polars_ensure` or `polars_bail` or others)  instead of `panic!` in Rust code. Leave `panic!` for unrecoverable/critical errors

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13-rc.1
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
No it shouldn't be recoverable. If you get a panic you should report this and we should fix this and return an error.

**Comment by giresg** [comment]
@ritchie46 consider this a bug report. Output as specified in the `Log Output` section. The code snippet I provided reproduces the error on my Apple Silicon machine. Unfortunately, I don't have access to another machine to test the issue on other processor architectures.

Happy to provide more details.

**Comment by alexander-beedie** [comment]
@giresg: could you confirm if you see this on the release build, or is this only for debug builds? (It looks like you may have compiled your own, as I see your `show_versions` is reporting `0.19.13-rc.1`)

**Comment by orlp** [comment]
@giresg This is a bug in the XCode linker, not in Polars. Try updating your XCode version (15.1 Beta works for me). (https://github.com/XcodesOrg/xcodes) may help with that.

**Comment by alexander-beedie** [comment]
FYI: the specific fix for this is listed in the Xcode release notes here - 
https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Linking

**Comment by giresg** [comment]
@alexander-beedie I did not see this issue on release builds. I only experience this error on debug builds while setting up my dev environment. I've edited the title of the issue to make it explicit that this is an issue with the unit tests running on a dev environment.

For completeness and future reference, these are the versions:

xcode command line tools: 2399
rustup: 1.26.0
rustc: 1.75.0-nightly
polars: HEAD d5cb4d1b50 on main branch

**Comment by alexander-beedie** [comment]
FYI: in case it wasn't clear from the above and it's still bothering you, you can fix this (until the release version of Xcode 15 is available) by installing the Xcode 15 beta...

https://developer.apple.com/xcode/resources/

...and then setting that as your default like so:
 `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/`
 
When polars is next built in debug, the updated/fixed Xcode will be used and you won't see unexpected segfaults in tests.
