### ISSUE TITLE
Cannot add a literal prefix in aggregation

### ISSUE THREAD

**Issue by Bonnevie** [pola-rs/polars#12285]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This is a very minor modification of the  [aggregation docs](https://pola-rs.github.io/polars/user-guide/expressions/aggregation)

```python
import polars as pl

url = "https://theunitedstates.io/congress-legislators/legislators-historical.csv"

dtypes = {
    "first_name": pl.Categorical,
    "gender": pl.Categorical,
    "type": pl.Categorical,
    "state": pl.Categorical,
    "party": pl.Categorical,
}

dataset = pl.read_csv(url, dtypes=dtypes).with_columns(pl.col("birthday").str.to_date(strict=False))


def get_person() -> pl.Expr:
    return pl.lit("John ") + pl.col("last_name")
    # this works: return pl.col("first_name") + pl.lit(" ") + pl.col("last_name")


q = (
    dataset.lazy()
    .sort("birthday", descending=True)
    .groupby("state")
    .agg(
        get_person().first().alias("youngest"),
        get_person().last().alias("oldest"),
    )
    .limit(5)
)

df = q.collect()
print(df)

```

### Log output

```shell
Traceback (most recent call last):
  File "/rabo/unumed/analytics/analytics/aggregation/tmp_test.py", line 32, in <module>
    df = q.collect()
  File "/rabo/conda/analytics/lib/python3.10/site-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/rabo/conda/analytics/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.InvalidOperationError: output length of `map` (1) must be equal to the input length (12139); consider using `apply` instead

Error originated in expression: 'Utf8(John ).str.concat_horizontal([col("last_name")])'
```

### Issue description

Trying to add a prefix to a string column prior to aggregation fails with a somewhat opaque error. You can add suffixes without issue: the key seems to be that the first part of the string concatenation should be a column.

This is a variation of https://github.com/pola-rs/polars/issues/10080 which sees the same problem in a `list.eval` context. The issue was diagnosed to be due to the `pl.lit` not being broadcast to the appropriate size.

### Expected behavior

Ordinary string operations like adding a prefix should be handled transparently in the aggregation context. 
Alternatively, a slightly more informative error message might be warranted.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.10.186-179.751.amzn2.x86_64-x86_64-with-glibc2.35
Python:              3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.21.6
pandas:              1.3.5
pyarrow:             12.0.1
pydantic:            2.2.1
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Your example runs for me on the current release `0.19.12`

```python
shape: (5, 3)
┌───────┬───────────────────┬─────────────────┐
│ state ┆ youngest          ┆ oldest          │
│ ---   ┆ ---               ┆ ---             │
│ cat   ┆ str               ┆ str             │
╞═══════╪═══════════════════╪═════════════════╡
│ MT    ┆ John Gianforte    ┆ John Cavanaugh  │
│ AR    ┆ John Griffin      ┆ John Yell       │
│ PR    ┆ John Acevedo-Vilá ┆ John Larrinaga  │
│ MD    ┆ John Kratovil     ┆ John Contee     │
│ IL    ┆ John Schock       ┆ John Stephenson │
└───────┴───────────────────┴─────────────────┘
```

**Comment by ritchie46** [comment]
This works on the latest polars version, so I will close this.

**Comment by alexander-beedie** [comment]
Note that you checked the box that says _"I have confirmed this bug exists on the latest version of Polars"_  but the `show_versions()` output indicates you're actually on `0.18.15`  ;)

The issue appears to be fixed on more recent versions (I checked with `0.19.12`), so I'll close this out - thanks  ;)

**Comment by Bonnevie** [comment]
ah, sorry to waste your time. Was sure I was on the newest since I just installed it, but I guess that'll be a lesson for me to verify next time!
