### ISSUE TITLE
Unable to import polars - crashes Python

### ISSUE THREAD

**Issue by nconsulting** [pola-rs/polars#12292]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
```

### Log output

```shell
Unhandled exception at 0x00007FFC0F776F3D (polars.pyd) in python.exe: 0xC000001D: Illegal Instruction.
```

### Issue description

When I run my Python code, as soon as it hits the import polars command it crashes and Visual Studio Community shows the exception: Unhandled exception at 0x00007FFC0F776F3D (polars.pyd) in python.exe: 0xC000001D: Illegal Instruction.

### Expected behavior

Import polars and move forward with the rest of the program

### Installed versions

<details>

```
I'm unable to run pl.show_versions()

Some PC information:

Python 3.10.10  (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Polars 0.19.12
Windows 10 64bit - 22H2
```

</details>

**Comment by raphaeltamaki** [comment]
Just dropping to confirm that if in Apple's Roseta OS the kernel *always* dies when trying to import polars, and changing the installation to the package above does solve the problem
