### ISSUE TITLE
assert_series_equal fails to raise on large-ish integers - should `check_exact` default to True for integers?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#12328]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [15]: from polars.testing import assert_series_equal

In [16]: left = pl.Series([1577840521123000])

In [17]: right = pl.Series([1577840521123543])

In [18]: assert_series_equal(left, right)

```

### Issue description

I'd have expected the above to raise. It doesn't because the default is `check_exact=False`

I get that `check_exact=False` is a good default for floats, but is it for ints?

### Expected behavior

I'd have expected the above to raise

### Installed versions

<details>

```
In [19]: pl.show_versions()
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.1
openpyxl:            <not installed>
pandas:              2.2.0.dev0+541.g51f3d03087
pyarrow:             12.0.1
pydantic:            2.0.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by stinodego** [comment]
> I get that check_exact=False is a good default for floats, but is it for ints?

I would say no. I know that pandas does inexact checking for integers by default, but I don't like it.

I would be in favor of doing inexact checking for floats only.

**Comment by MarcoGorelli** [comment]
agree - brought it up in the pandas community call today and it was agreed it should change there too
