### ISSUE TITLE
Horizontal sum in Rust Polars is not working

### ISSUE THREAD

**Issue by horizondeep** [pola-rs/polars#12324]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    use polars::prelude::*;

    let s0 = Series::new("store_qty", [1,1,1,2,2,2,3,3,3]);
    let s1 = Series::new("store_qty_1", [101, 101, 101,201,201,201,301,301,301]);
    let s2 = Series::new("week_id", [202301, 202302,202303, 202301, 202302,202303,202301, 202302,202303]);

    let mut df_input = DataFrame::new(vec![s0, s1, s2]).unwrap();

    df_input.lazy().with_columns([sum_horizontal(&[col("^store.*$").fill_null(0.0000)]).alias("sum_qty")]).collect().unwrap();


```

### Log output

//Not able to find the function sum_horizontal in the current scope

### Issue description

Horizontal Sum is required if you want to add rows of multiples columns and generate final column but it seems this functionality has been depreciated in current version.

### Expected behavior

Should have sum_horizontal function in current Polars version which can do summation at row level for various columns like earlier versions. See below for polars 0.33.2:

pub fn sum_horizontal<E>(exprs: E) -> [Expr](https://docs.rs/polars/0.33.2/polars/prelude/enum.Expr.html)
where
    E: [AsRef](https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html)<[[Expr] 
     (https://docs.rs/polars/0.33.2/polars/prelude/enum.Expr.html)]>

### Installed versions

<details>

polars = { version = "0.34.2", features = ["parquet","serde", "json", "lazy", "pivot", "rank", "log","lazy_regex","horizontal_concat","polars-lazy","dtype-struct","dtype-array","concat_str","is_in","polars-io","strings","cum_agg"] }

</details>

**Comment by horizondeep** [comment]
@ritchie46 Please look into this.

**Comment by stinodego** [comment]
Please provide a reproducible example, otherwise we cannot help you!

**Comment by horizondeep** [comment]
@stinodego Please check now..

**Comment by horizondeep** [comment]
Tried this as well with latest version of Polars in Rust, but whenever I try to create a new column it throws an error:
    
     use polars::prelude::*;
    
    let s0 = Series::new("store_qty", [1,1,1,2,2,2,3,3,3]);
    let s1 = Series::new("store_qty_1", [101, 101, 101,201,201,201,301,301,301]);
    let s2 = Series::new("week_id", [202301, 202302,202303, 202301, 202302,202303,202301, 202302,202303]);

    let mut df_input = DataFrame::new(vec![s0, s1, s2]).unwrap();

    let a1 = Expr::Function{input:vec![col("^store.*$")],function:FunctionExpr::SumHorizontal, options: Default::default()};
    let p2 = df_input.clone().lazy().with_columns([(a1).alias("final")]).collect().unwrap();

   //value: ComputeError(ErrString("The name: 'final' passed to `LazyFrame.with_columns` is duplicate

**Comment by cmdlineluser** [comment]
I think you can use `polars_plan::dsl::sum_horizontal`

```rust
use polars::prelude::*;
use polars_plan::dsl::sum_horizontal;

fn main() -> PolarsResult<()> {
    let s0 = Series::new("store_qty", [1, 1, 1, 2, 2, 2, 3, 3, 3]);
    let s1 = Series::new("store_qty_1", [101, 101, 101, 201, 201, 201, 301, 301, 301]);
    let s2 = Series::new(
        "week_id",
        [
            202301, 202302, 202303, 202301, 202302, 202303, 202301, 202302, 202303,
        ],
    );

    let mut df_input = DataFrame::new(vec![s0, s1, s2])?;

    let df = df_input.lazy().with_columns([sum_horizontal(&[
        cols(["store_qty", "store_qty_1"]).fill_null(0.0000)
    ])?
    .alias("sum_qty")]);

    dbg!(df.collect());

    Ok(())
}
```
```rust
[examples/sum_horizontal/src/main.rs:21] df.collect() = Ok(
    shape: (9, 4)
    ┌───────────┬─────────────┬─────────┬─────────┐
    │ store_qty ┆ store_qty_1 ┆ week_id ┆ sum_qty │
    │ ---       ┆ ---         ┆ ---     ┆ ---     │
    │ i32       ┆ i32         ┆ i32     ┆ f64     │
    ╞═══════════╪═════════════╪═════════╪═════════╡
    │ 1         ┆ 101         ┆ 202301  ┆ 102.0   │
    │ 1         ┆ 101         ┆ 202302  ┆ 102.0   │
    │ 1         ┆ 101         ┆ 202303  ┆ 102.0   │
    │ 2         ┆ 201         ┆ 202301  ┆ 203.0   │
    │ 2         ┆ 201         ┆ 202302  ┆ 203.0   │
    │ 2         ┆ 201         ┆ 202303  ┆ 203.0   │
    │ 3         ┆ 301         ┆ 202301  ┆ 304.0   │
    │ 3         ┆ 301         ┆ 202302  ┆ 304.0   │
    │ 3         ┆ 301         ┆ 202303  ┆ 304.0   │
    └───────────┴─────────────┴─────────┴─────────┘,
)
```

**Comment by cmdlineluser** [comment]
> Which version of polars-plan you are using?

I used the latest checkout from `main`.

**Comment by AnatolyBuga** [comment]
Why was ```sum_horizontal```/`max_horizontal` etc moved (or made unavailable in polars crate) ?

**Comment by ritchie46** [comment]
You use it via the lazy API activated via the lazy feature

**Comment by giomf** [comment]
> Why was `sum_horizontal`/`max_horizontal` etc moved (or made unavailable in polars crate) ? Docs of `polars-plan` advise against external usage

I have the same question. Why is this closed If it is not recommended to use polars-plan directly.

**Comment by ritchie46** [comment]
As answered in https://github.com/pola-rs/polars/issues/12324#issuecomment-1826891583

**Comment by giomf** [comment]
I have the lazy feature flag activated but still have to use `use polars_plan::dsl::sum_horizontal` which also means I have to add the crate to my cargo.toml to use sum_horizontal.

What am I missing here?

**Comment by cmdlineluser** [comment]
@giomf 

It seems `polars_lazy::dsl` is supposed to be used instead e.g. `polars_lazy::dsl::sum_horizontal`

(This required adding `polars-lazy` to Cargo.toml - so I'm not sure if it is 100% correct.)

**Comment by ritchie46** [comment]
You must activate the `lazy` feature and import everything via the `polars` crate, not via the sub crates.

**Comment by cmdlineluser** [comment]
Oh right.

So `polars::lazy::dsl::sum_horizontal`

**Comment by giomf** [comment]
> Oh right.
> 
> So `polars::lazy::dsl::sum_horizontal`

Thanks that was the missing part.
However I thought that `use polars::prelude::*;` would be sufficient.

**Comment by AntoinePrv** [comment]
I also came here wondering why I was not able to use `min_horizontal` from the polars prelude, when the `lazy` feature is in fact activated.
