### ISSUE TITLE
Get Duplicates based on subset using keep = First or Last (should work just like pandas)

### ISSUE THREAD

**Issue by Keerthesre1** [pola-rs/polars#12337]
When "keep = first or keep = last" is used on the selected subset columns we need to get the duplicates based on subset column leaving first record when keep = first ,leaving last record when keep = last. We need output just like the we use the same concept in the pandas.

**Comment by cmdlineluser** [comment]
Are you talking about [`.unique()`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.unique.html#polars.DataFrame.unique) ?

```python
df = pl.select(
    A = ['foo', 'bar', 'foo', 'bar'],
    B = ['a', 'b', 'c', 'd']
).explode(pl.all())

df.unique('A', keep='first')
# shape: (2, 2)
# ┌─────┬─────┐
# │ A   ┆ B   │
# │ --- ┆ --- │
# │ str ┆ str │
# ╞═════╪═════╡
# │ foo ┆ a   │
# │ bar ┆ b   │
# └─────┴─────┘

df.unique('A', keep='last')
# shape: (2, 2)
# ┌─────┬─────┐
# │ A   ┆ B   │
# │ --- ┆ --- │
# │ str ┆ str │
# ╞═════╪═════╡
# │ bar ┆ d   │
# │ foo ┆ c   │
# └─────┴─────┘
```

**Comment by Keerthesre1** [comment]
> Are you talking about [`.unique()`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.unique.html#polars.DataFrame.unique) ?
> 
> ```python
> df = pl.select(
>     A = ['foo', 'bar', 'foo', 'bar'],
>     B = ['a', 'b', 'c', 'd']
> ).explode(pl.all())
> 
> df.unique('A', keep='first')
> # shape: (2, 2)
> # ┌─────┬─────┐
> # │ A   ┆ B   │
> # │ --- ┆ --- │
> # │ str ┆ str │
> # ╞═════╪═════╡
> # │ foo ┆ a   │
> # │ bar ┆ b   │
> # └─────┴─────┘
> 
> df.unique('A', keep='last')
> # shape: (2, 2)
> # ┌─────┬─────┐
> # │ A   ┆ B   │
> # │ --- ┆ --- │
> # │ str ┆ str │
> # ╞═════╪═════╡
> # │ bar ┆ d   │
> # │ foo ┆ c   │
> # └─────┴─────┘
> ```

"NOT UNIQUE "

I will give you simple example for you to understand. Imagine

col1            col2         col3
1                   7               3
1                   2               4
1                   7               9
1                   7               9

Scenario-1:  if i use keep = first then my output should be

OUTPUT:  1                   7               9
                  1                   7               9

Scenario-2:  if i use keep = last then my output should be

OUTPUT: 1                   7               3
                 1                   7               9
                 
                 
LOGIC:   1     7     3              1        2       5
                1     7     9              1       2        3
                1     7     9              1        2        4
                
=> based on matching sets for keep = first means it skips the first record in each matching set and give me the output as 
  
  1     7     9              1       2        3
  1     7     9              1        2        4

=> based on matching sets for keep = first means it skips the first record in each matching set and give me the output as 

1     7     3              1        2       5
1     7     9              1       2        3


so i didn't find it polars.


can you just help me with this?

**Comment by cmdlineluser** [comment]
> We need output just like the we use the same concept in the pandas.

Could you perhaps show the exact pandas commands you are using to produce the Scenario outputs?

```python
df = pl.DataFrame({
    'col1': [1, 1, 1, 1], 
    'col2': [7, 2, 7, 7], 
    'col3': [3, 4, 9, 9]
})

df.to_pandas().drop_duplicates(keep='first')
#    col1  col2  col3
# 0     1     7     3
# 1     1     2     4
# 2     1     7     9
```

https://github.com/pola-rs/polars/issues/7614 is a previous duplicates related issue which may have some useful information.

**Comment by Keerthesre1** [comment]
> > We need output just like the we use the same concept in the pandas.
> 
> Could you perhaps show the exact pandas commands you are using to produce the Scenario outputs?
> 
> ```python
> df = pl.DataFrame({
>     'col1': [1, 1, 1, 1], 
>     'col2': [7, 2, 7, 7], 
>     'col3': [3, 4, 9, 9]
> })
> 
> df.to_pandas().drop_duplicates(keep='first')
> #    col1  col2  col3
> # 0     1     7     3
> # 1     1     2     4
> # 2     1     7     9
> ```
> 
> #7614 is a previous duplicates related issue which may have some useful information.

pandas.DataFrame.duplicated(subset=None, keep='first')[[source]](https://github.com/pandas-dev/pandas/blob/v2.1.2/pandas/core/frame.py#L6576-L6717)

Requires same functionality in polars.

**Comment by cmdlineluser** [comment]
Hm yes, I don't think that behaviour was discussed in the linked issue.

It looks like this?

```python
subset = pl.struct("col1", "col2")

df.with_columns(
   first = subset.is_first_distinct().not_().over(subset),
   last =  subset.is_last_distinct().not_().over(subset)
)

# shape: (4, 5)
# ┌──────┬──────┬──────┬───────┬───────┐
# │ col1 ┆ col2 ┆ col3 ┆ first ┆ last  │
# │ ---  ┆ ---  ┆ ---  ┆ ---   ┆ ---   │
# │ i64  ┆ i64  ┆ i64  ┆ bool  ┆ bool  │
# ╞══════╪══════╪══════╪═══════╪═══════╡
# │ 1    ┆ 7    ┆ 3    ┆ false ┆ true  │
# │ 1    ┆ 2    ┆ 4    ┆ false ┆ false │
# │ 1    ┆ 7    ┆ 9    ┆ true  ┆ true  │
# │ 1    ┆ 7    ┆ 9    ┆ true  ┆ false │
# └──────┴──────┴──────┴───────┴───────┘
```

**Comment by Keerthesre1** [comment]
> Hm yes, I don't think that behaviour was discussed in the linked issue.
> 
> It looks like this?
> 
> ```python
> subset = pl.struct("col1", "col2")
> 
> df.with_columns(
>    first = subset.is_first_distinct().not_().over(subset),
>    last =  subset.is_last_distinct().not_().over(subset)
> )
> 
> # shape: (4, 5)
> # ┌──────┬──────┬──────┬───────┬───────┐
> # │ col1 ┆ col2 ┆ col3 ┆ first ┆ last  │
> # │ ---  ┆ ---  ┆ ---  ┆ ---   ┆ ---   │
> # │ i64  ┆ i64  ┆ i64  ┆ bool  ┆ bool  │
> # ╞══════╪══════╪══════╪═══════╪═══════╡
> # │ 1    ┆ 7    ┆ 3    ┆ false ┆ true  │
> # │ 1    ┆ 2    ┆ 4    ┆ false ┆ false │
> # │ 1    ┆ 7    ┆ 9    ┆ true  ┆ true  │
> # │ 1    ┆ 7    ┆ 9    ┆ true  ┆ false │
> # └──────┴──────┴──────┴───────┴───────┘
> ```

It's Working. 

Thank You!

**Comment by Keerthesre1** [comment]
> Thanks @cmdlineluser.
> 
> @Keerthesre1 I assume we can close this issue now?

YES WE CAN

**Comment by cmdlineluser** [comment]
Just to clarify, the `.over(subset)` should be removed as it not needed. 

https://pola-rs.github.io/polars/user-guide/expressions/structs/ should explain `pl.struct` in more detail.

**Comment by create-nuxt-app6** [comment]
It dawned on me https://nasirregimen.github.io/webpack-splitchunks401/
