### ISSUE TITLE
Casting UTF8 to UTF8 results in error

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#12340]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
#[cfg(test)]
mod tests {
    use anyhow::{anyhow, Result};
    use polars::prelude::*;

    #[test]
    fn test_casting_to_self() -> anyhow::Result<()> {
        let df = df! {
            "a" => ["a"],
        }?;
        let res = df
            .lazy()
            .with_column(lit("some string").cast(DataType::Utf8).alias("c"))
            .collect()?;
        dbg!(res);
        Ok(())
    }
}
```

### Log output

```shell
Error: cannot cast non numeric any-value to numeric dtype
```

### Issue description

Casting a utf8 literal to utf8 should be a noop in my opinion. This was the behaviour previously and was changed back in July.

The "failing" behaviour was introduced between the commits
`af8596582a7f1c300d225cc5ab5aba067a0434c8` (2023-07-15) and `ff56742e4a0bac5c5b9d4d8a7292e676fcc152cb` (2023-07-27). I can not pinpoint the exact commit when this behaviour was introduced as I'm not able to get a working build for any commit in between these two.

### Expected behavior

A cast of a type to itself should be a noop imo.

### Installed versions

<details>

`polars = { git = "https://github.com/pola-rs/polars", rev = "30e4471c13fc838795fb95a98ea19e01408cffda", features = ["lazy"] }`

</details>

**Comment by cmdlineluser** [comment]
It looks like it may have changed after https://github.com/pola-rs/polars/commit/fdbdd1c75c5376f7c26d5bbefc3b941a69edefe2

**Comment by SimonSchneider** [comment]
Thanks for the quick responses, I tested the PR and it solves the issue 🎉 Also good note regarding only being broken on debug builds.
