### ISSUE TITLE
Rust with pyo3-polars lags behind pandas/numpy for simple aggregation in Python

### ISSUE THREAD

**Issue by ak-gupta** [pola-rs/polars#12352]
## UPDATE 2.0

I have updated the example code so I can easily bypass the `fill_nan` step in the Polars code. I have
included a couple results below.

Without the `fill_nan` step Polars is a lot faster than NumPy. Interestingly, the Python Polars code is
also much faster than my Rust polars code. I'm not sure why that is.

### Single-row

**Command**: `python -m pytest tests/test_speed.py --nrows 1 --metric mean --handle-nan 0 --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars (Python) | 1.1337                         | 1.1979             |
| Polars          | 6.5150                         | 2.6089             |
| NumPy           | 16.1983                        | 6.3998             |

### 10 000 000 Rows

**Command**: `python -m pytest tests/test_speed.py --nrows 10000000 --metric mean --handle-nan 0 --benchmark-sort=mean`

|                 | Average execution time (in ms) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars (Python) | 1.6124                         | 0.0514             |
| Polars          | 1.7093                         | 0.2848             |
| NumPy           | 14.1508                        | 0.3727             |

## UPDATE

I have updated the issue description to include code and benchmarks for python-polars. My observations
are as follows:

* Pandas/NumPy is still faster than Polars for the mean and median calculations for data with less
  than 100 000 rows.
* At 100 000 rows, the median calculation is faster with Polars.
* At 10 000 000 rows, the mean calculation is faster with Polars.
* For this simple code, rust-polars and python-polars are similarly performant. However, python-polars
  has a lower standard deviation in 6 of 10 benchmarks.

### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

## `src/lib.rs`

```rust
#[cfg(all(target_os = "linux", not(use_mimalloc)))]
use jemallocator::Jemalloc;
#[cfg(any(not(target_os = "linux"), use_mimalloc))]
use mimalloc::MiMalloc;

#[global_allocator]
#[cfg(all(target_os = "linux", not(use_mimalloc)))]
static ALLOC: Jemalloc = Jemalloc;

#[global_allocator]
#[cfg(any(not(target_os = "linux"), use_mimalloc))]
static ALLOC: MiMalloc = MiMalloc;

use polars::prelude::*;
use pyo3::prelude::*;
use pyo3_polars::PyDataFrame;

// Calculate the mean of a column
#[pyfunction]
fn calculate_mean_pl(a: PyDataFrame, colname: String, handle_nan: bool) -> Option<f64> {
    let df: DataFrame = a.into();
    let df = match handle_nan {
        true => {
            df
                .lazy()
                .select([col(&colname).fill_nan(lit(NULL))])
                .collect()
                .expect("Unable to coerce NaN values.")
        },
        false => df
    };

    df[colname.as_str()].mean()
}

// Calculate the median of a column
#[pyfunction]
fn calculate_median_pl(a: PyDataFrame, colname: String, handle_nan: bool) -> Option<f64> {
    let df: DataFrame = a.into();
    let df = match handle_nan {
        true => {
            df
                .lazy()
                .select([col(&colname).fill_nan(lit(NULL))])
                .collect()
                .expect("Unable to coerce NaN values.")
        },
        false => df
    };

    df[colname.as_str()].median()
}

/// A Python module implemented in Rust.
#[pymodule]
fn polars_speed_test(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(calculate_mean_pl, m)?)?;
    m.add_function(wrap_pyfunction!(calculate_median_pl, m)?)?;

    Ok(())
}
```

## `Cargo.toml`

```toml
[package]
name = "polars-speed-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "polars_speed_test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20"
polars = { version = "0.34", default-features = false, features = ["cse", "lazy", "nightly", "performant"] }
pyo3-polars = "0.8"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[target.'cfg(any(not(target_os = "linux"), use_mimalloc))'.dependencies]
mimalloc = { version = "0.1", default-features = false }

[target.'cfg(all(target_os = "linux", not(use_mimalloc)))'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

[profile.release]
lto = "fat"
codegen-units = 1
```

## `pyproject.toml`

```toml
[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "polars-speed-test"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "numpy~=1.26",
    "pandas~=2.1",
    "polars~=0.19",
    "pyarrow~=14.0"
]

[tool.maturin]
features = ["pyo3/extension-module"]


[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-benchmark"
]
```

## `polars_speed_test/__init__.py`

```python
"""Import modules."""

from typing import List

import numpy as np
import pandas as pd
import polars as pl

from polars_speed_test.polars_speed_test import calculate_mean_pl, calculate_median_pl

def calculate_mean_np(a: pd.DataFrame, colname: str) -> float:
    """Calculate the mean using nanmean.

    Parameters
    ----------
    a : pd.DataFrame
        The input dataframe.
    colname : str
        The name of the column.

    Returns
    -------
    float
        The output of nanmean.
    """
    return np.nanmean(a[colname])

def calculate_mean_pypl(a: pl.DataFrame, colname: str, handle_nan: bool) -> float:
    """Calculate the mean using python-polars.

    Parameters
    ----------
    a : pl.DataFrame
        The input DataFrame.
    colname : str
        The name of the column.
    handle_nan : bool
        Whether or not to handle float NaN values.

    Returns
    -------
    float
        The column mean.
    """
    if handle_nan:
        df_no_nan = (
            a.lazy()
            .select([pl.col(colname).fill_nan(None)])
            .collect()
        )

        return df_no_nan[colname].mean()
    else:
        return a[colname].mean()

def calculate_median_np(a: pd.DataFrame, colname: str) -> float:
    """Calculate the median using nanmedian.

    Parameters
    ----------
    a : pd.DataFrame
        The input dataframe.
    colname : str
        The name of the column.

    Returns
    -------
    float
        The output of nanmedian.
    """
    return np.nanmedian(a[colname])

def calculate_median_pypl(a: pl.DataFrame, colname: str, handle_nan: bool) -> float:
    """Calculate the median using python-polars.

    Parameters
    ----------
    a : pl.DataFrame
        The input DataFrame.
    colname : str
        The name of the column.
    handle_nan : bool
        Whether or not to handle float NaN values.

    Returns
    -------
    float
        The column name.
    """
    if handle_nan:
        df_no_nan = (
            a.lazy()
            .select([pl.col(colname).fill_nan(None)])
            .collect()
        )

        return df_no_nan[colname].median()
    else:
        return a[colname].median()

__all__: List[str] = [
    "calculate_mean_np",
    "calcualte_mean_pypl",
    "calculate_mean_pl",
    "calculate_median_np",
    "calculate_median_pypl",
    "calculate_median_pl"
]
```

### `tests/conftest.py`

```python
"""Create data through a CLI option."""

import numpy as np
import pytest

def pytest_addoption(parser):
    """Add an option for defining the number of rows and the metric."""
    parser.addoption(
        "--nrows", action="store", default="1", help="The number of rows to use for benchmarking."
    )
    parser.addoption(
        "--metric", action="store", default="mean", help="Whether to calculate 'mean' or 'median'"
    )
    parser.addoption(
        "--handle-nan",
        action="store",
        default="1",
        help="Whether or not to fill NaN values with null prior to metric. '0' means False, '1' means True."
    )


@pytest.fixture
def data(request):
    """Generate random data."""
    np.random.seed(42)

    return {
        "a": np.random.normal(size=int(request.config.getoption("--nrows"))).tolist()
    }


@pytest.fixture
def metric(request):
    return request.config.getoption("--metric")


@pytest.fixture
def handle_nan(request):
    return bool(int(request.config.getoption("--handle-nan")))
```

### `tests/test_speed.py`

```python
"""Compare the speed of the Numpy and Polars calculations."""

import pandas as pd
import polars as pl

import polars_speed_test as pst


def test_metric_np(data, metric, benchmark):
    """Test the single row performance."""
    data = pd.DataFrame(data)
    if metric == "mean":
        func = pst.calculate_mean_np
    elif metric == "median":
        func = pst.calculate_median_np
    else:
        raise ValueError("Invalid metric.")

    def test_func():
        func(data, colname="a")

    benchmark(test_func)


def test_metric_pl(data, metric, handle_nan, benchmark):
    """Test the single row performance in polars."""
    data = pl.DataFrame(data)

    if metric == "mean":
        func = pst.calculate_mean_pl
    elif metric == "median":
        func = pst.calculate_median_pl
    else:
        raise ValueError("Invalid metric.")

    def test_func():
        func(data, colname="a", handle_nan=handle_nan)

    benchmark(test_func)


def test_metric_pypl(data, metric, handle_nan, benchmark):
    """Test the single row performance in python-polars."""
    data = pl.DataFrame(data)

    if metric == "mean":
        func = pst.calculate_mean_pypl
    elif metric == "median":
        func = pst.calculate_median_pypl
    else:
        raise ValueError("Invalid metric.")

    def test_func():
        func(data, colname="a", handle_nan=handle_nan)

    benchmark(test_func)
```

# Commands Used

```console
$ maturin develop --release --extras tests
$ python -m pytest tests/test_speed.py --nrows <NUMBER_OF_ROWS> --metric <mean|median> --benchmark-sort=mean
```

## Overview

Hi there!

I'm trying to write some data transformation using Polars in Rust with `pyo3` to expose a Python API. My primary motivation is to assess possible performance improvements over Pandas/NumPy. I noticed that, for simple aggregation, my Rust-backed code is not as performant as NumPy. Additionally, I'm seeing more variability in the execution time for the Rust-backed code.

#8436 reports a similar issue but their Polars code is written in Python.

I also saw [this comment](https://www.reddit.com/r/rust/comments/1673ska/comment/jyp1zsw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) that mentions methods for optimizing the Python binary, so I copied those settings from `py-polars`.

I am running my code in an Ubuntu docker container with Python 3.9 on a Macbook Pro (M1 Pro processor). The Docker daemon has 6 cores/14GB allocated. I am not using Rosetta 2 (`uname -m` returns `aarch64` in my container).

Any help would be greatly appreciated!

### Single-row

**Command**: `python -m pytest tests/test_speed.py --nrows 1 --metric mean --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 16.8306                        | 6.3084             |
| Polars          | 116.3921                       | 20.4009            |
| Polars (Python) | 124.2515                       | 22.4100            |

**Command**: `python -m pytest tests/test_speed.py --nrows 1 --metric median --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 19.5454                        | 5.7543             |
| Polars (Python) | 117.6355                       | 18.1941            |
| Polars          | 122.9208                       | 25.9227            |

### 1 000 Rows

**Command**: `python -m pytest tests/test_speed.py --nrows 1000 --metric mean --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 17.9272                        | 4.7231             |
| Polars          | 109.2868                       | 12.0086            |
| Polars (Python) | 111.1885                       | 10.3694            |

**Command**: `python -m pytest tests/test_speed.py --nrows 1000 --metric median --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 21.9768                        | 2.0294             |
| Polars          | 112.8184                       | 12.9552            |
| Polars (Python) | 115.8722                       | 10.3586            |

### 100 000 Rows

**Command**: `python -m pytest tests/test_speed.py --nrows 100000 --metric mean --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 111.6838                       | 10.1106            |
| Polars          | 199.9848                       | 20.2114            |
| Polars (Python) | 211.3914                       | 12.9004            |

**Command**: `python -m pytest tests/test_speed.py --nrows 100000 --metric median --benchmark-sort=mean`

|                 | Average execution time (in us) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars (Python) | 460.1264                       | 23.0691            |
| Polars          | 625.0976                       | 72.5570            |
| NumPy           | 925.6552                       | 26.1714            |

### 1 000 000 Rows

**Command**: `python -m pytest tests/test_speed.py --nrows 1000000 --metric mean --benchmark-sort=mean`

|                 | Average execution time (in ms) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| NumPy           | 1.0855                         | 0.0424             |
| Polars          | 1.2698                         | 0.3187             |
| Polars (Python) | 1.4913                         | 1.2957             |

**Command**: `python -m pytest tests/test_speed.py --nrows 1000000 --metric median --benchmark-sort=mean`

|                 | Average execution time (in ms) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars          | 4.1794                         | 0.1642             |
| Polars (Python) | 4.5509                         | 0.1293             |
| NumPy           | 9.6420                         | 0.1534             |

### 10 000 000 Rows

**Command**: `python -m pytest tests/test_speed.py --nrows 10000000 --metric mean --benchmark-sort=mean`

|                 | Average execution time (in ms) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars          | 11.3284                        | 0.0906             |
| Polars (Python) | 11.4301                        | 0.0943             |
| NumPy           | 13.9873                        | 0.0587             |

**Command**: `python -m pytest tests/test_speed.py --nrows 10000000 --metric median --benchmark-sort=mean`

|                 | Average execution time (in ms) | Standard Deviation |
| --------------- | ------------------------------ | ------------------ |
| Polars          | 43.1144                        | 2.2647             |
| Polars (Python) | 43.7406                        | 0.3703             |
| NumPy           | 90.3902                        | 0.1814             |

### Expected behavior

I expected that my Rust-backed python bindings would be more performant than the Python code.

### Installed versions

<details>

I have tried various feature flags based on the documentation. Right now I am using

`polars = { version = "0.34", default-features = false, features = ["cse", "lazy", "nightly", "performant"] }`

</details>

**Comment by ritchie46** [comment]
Can you include python polars? That gives us more information.

**Comment by ak-gupta** [comment]
Will do! I'll add some code and update the benchmarks.

**Comment by ak-gupta** [comment]
Updated!

**Comment by ritchie46** [comment]
You are doing a nan fill first. I wouldn't expect this to be faster as you are benchmarking two operations.

**Comment by ak-gupta** [comment]
Right, I added that step to make sure the two operations were equivalent given the same input. I guess the argument is that a Polars pipeline would have `null` values instead of NaN, so that step _should_ be unnecessary, right?

I added another update to the code/issue that reflects the performance when I bypass the `fill_nan` step. In rust,

```rust
    let df = match handle_nan {
        true => {
            df
                .lazy()
                .select([col(&colname).fill_nan(lit(NULL))])
                .collect()
                .expect("Unable to coerce NaN values.")
        },
        false => df
    };
```

(I'm not very experienced in Rust, so please let me know if there's an easier way to do this)

In python,

```python
    if handle_nan:
        df_no_nan = (
            a.lazy()
            .select([pl.col(colname).fill_nan(None)])
            .collect()
        )

        return df_no_nan[colname].mean()
    else:
        return a[colname].mean()
```

I see that without `fill_nan` the Polars code has an advantage. The most surprising result is that now python polars is much faster than my code!

**Comment by ak-gupta** [comment]
Following up on my last comment/update, I see this was added to the README for `pyo3-polars` with regards to the expression plugin pattern:

> This is new functionality and not entirely stable, but should be preferred over 2. as this will circumvent the GIL and will be the way we want to support extending polars.

Does that mean that my Rust polars code is being affected by the GIL? Is it some sort of "serialization" when converting from `PyDataFrame` to `DataFrame`?

Sorry for the questions and let me know if this is the appropriate forum. I'm fascinated with the potential performance gains I could see by rewriting some of my old code using both Polars and Rust-backed Python.

**Comment by ritchie46** [comment]
> I see that without fill_nan the Polars code has an advantage. The most surprising result is that now python polars is much faster than my code!

That might be due to differences in compilation. 

I am not sure there is an action point for us. I will close this issue. If you have generic questions over why your code is faster, please use our discord or SO. The issue tracker is meant for issues.
