### ISSUE TITLE
How to Convert Pandas filters to Polars Filter? Is there any function that we can Use?

### ISSUE THREAD

**Issue by Keerthesre1** [pola-rs/polars#12359]
I want to convert the pandas filter to polars filter in easy way but here i am writing it in function which is making it difficult to define so many check conditions.

Ex:         PANDAS FILTER :   df=df[df['Dr/Cr Ind']=='Dr']

How to convert the given example filter to polars.

**Comment by MarcoGorelli** [comment]
something like
```python
df = df.filter(pl.col('Dr/Cr Ind') == 'Dr')
```

**Comment by Keerthesre1** [comment]
> something like
> 
> ```python
> df = df.filter(pl.col('Dr/Cr Ind') == 'Dr')
> ```

Yes manually we can convert.But how do I convert it with functions?

**Comment by MarcoGorelli** [comment]
hi @Keerthesre1  - could you ask usage questions on stackoverflow please?

**Comment by cmdlineluser** [comment]
@MarcoGorelli I think they may actually be asking if this can be done "automatically"?

It has made me wonder if the `Inefficient map_*` parser could actually be used to "rewrite" pandas code?
