### ISSUE TITLE
Invalid state DataFrame creatable (columns with different lengths)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12367]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [1, 2],
        "b": [None, None],
    }
)

# this DataFame has unequal column lengths (1 and 0) but CAN be created
df2 = df.select(
    pl.all().drop_nulls().first().name.suffix("_first"),
)

# printing panics
print(df2) # PanicException: The column lengths in the DataFrame are not equal.

# but can still work with it
df2.with_columns(
    pl.all().len()
)
shape: (1, 2)
┌─────────┬─────────┐
│ a_first ┆ b_first │
│ ---     ┆ ---     │
│ u32     ┆ u32     │
╞═════════╪═════════╡
│ 1       ┆ 0       │
└─────────┴─────────┘
```

### Issue description

It is possible to create an (invalid?) DataFrame with different column lengths.
Should this be possible?

### Expected behavior

It should not be possible to create/calculate a DataFrame with different column lengths.

I think the cause for this is probably (almost) always that some functions return a zero-sized DataFrame which is somehow accepted and not broadcasted correctly? (I came across this when looking into #12363 where `first/last` return 0-size dfs)

### Installed versions

<details>

```
0.19.12
```

</details>

**Comment by ritchie46** [comment]
You deserve a sticker for finding this! :D
