### ISSUE TITLE
Creating two new columns at once, with second dependent on first new column

### ISSUE THREAD

**Issue by dl-lim** [pola-rs/polars#12376]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

# Create a numpy array with some values
a = np.array([1, 2, 3, 4, 5])

# Create another numpy array that is equal to 1 minus the values in the original one
b = 1 - a

# Create a polars DataFrame with four columns
df = pl.DataFrame({
    "a": [1, 2, 3, 4, 5],
    "b": [6, 7, 8, 9, 10],
    "c": [11, 12, 13, 14, 15],
    "d": [16, 17, 18, 19, 20]
})

# Add two new columns to the DataFrame using the with_columns method
df = df.with_columns(
    e = pl.col("a") + pl.col("b"),
    f = pl.col("e") * pl.col("c")
)

# Print the updated DataFrame
print("df with new columns:")
print(df)

```

### Log output

```shell
Error originated just after this operation:
DF ["a", "b", "c", "d"]; PROJECT */4 COLUMNS; SELECTION: "None"

---------------------------------------------------------------------------
ColumnNotFoundError                       Traceback (most recent call last)
File <command-2211326584961669>, line 17
      8 df = pl.DataFrame({
      9     "a": [1, 2, 3, 4, 5],
     10     "b": [6, 7, 8, 9, 10],
     11     "c": [11, 12, 13, 14, 15],
     12     "d": [16, 17, 18, 19, 20]
     13 })
     16 # Add two new columns to the DataFrame using the with_columns method
---> 17 df = df.with_columns(
     18     e = pl.col("a") + pl.col("b"),
     19     f = pl.col("e") * pl.col("c")
     20 )
     22 # Print the updated DataFrame
     23 print("df with new columns:")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/polars/dataframe/frame.py:7942, in DataFrame.with_columns(self, *exprs, **named_exprs)
   7794 def with_columns(
   7795     self,
```
```


### Issue description

Column e was just created in the with_columns, and f is dependent on e.

Is it not possible to create e and f in the same with_columns, without having to do with_columns twice?

### Expected behavior

A new df is to be created with all 6 columns

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.15.0-1049-azure-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.5.2
numpy:               1.21.5
openpyxl:            3.1.1
pandas:              1.4.4
pyarrow:             8.0.0
pydantic:            1.10.6
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
you'll need to chain the two calls
```python
# Add two new columns to the DataFrame using the with_columns method
df = df.with_columns(
    e = pl.col("a") + pl.col("b"),
).with_columns(
    f = pl.col("e") * pl.col("c")
)
```

closing then, but thanks for the issue

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/9062 has a detailed discussion on this topic if interested.

> I don't want this extra complexity in polars. If you want to use an update column, you need two with_columns. This makes it much more readable, simple, and explainable.
