### ISSUE TITLE
Polars SQL doesn't support LIKE queries

### ISSUE THREAD

**Issue by osawyerr** [pola-rs/polars#12399]
### Description

Hi there polars SQL doesn't support SQL `LIKE` queries e.g.

`select * from customer where c_name LIKE 'Customer1%'`

**Comment by alexander-beedie** [comment]
FYI: we currently have good support for the regex operators, which offer a superset of LIKE functionality; have a look here for details: https://github.com/pola-rs/polars/issues/9104#issuecomment-1627484267.

**Comment by ritchie46** [comment]
> FYI: while we don't have LIKE itself yet, we do have good support for the regex operators which offer a superset of LIKE functionality; have a look here for details: [#9104 (comment)](https://github.com/pola-rs/polars/issues/9104#issuecomment-1627484267). In the meantime I'll take another look at adding proper LIKE support 🤔

Seems like a special case of regex right?

**Comment by cmdlineluser** [comment]
For the wildcards, it looks like `%` and `_` are equivalent to `.*` and `.` in regex.

`LIKE` also seems to behave similar to `re.fullmatch()` by default, as opposed to `re.search()`

- https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE


```python
df = pl.DataFrame({"c_name": ["Customer1", "Customer2", "Customer10"]})

df.with_columns(
   a = pl.sql_expr(r"c_name ~ '^Customer1'"),
   b = pl.sql_expr(r"regexp_like(c_name, '^Customer1')"),
   c = pl.sql_expr(r"starts_with(c_name, 'Customer1')")
)

# shape: (3, 4)
# ┌────────────┬───────┬───────┬───────┐
# │ c_name     ┆ a     ┆ b     ┆ c     │
# │ ---        ┆ ---   ┆ ---   ┆ ---   │
# │ str        ┆ bool  ┆ bool  ┆ bool  │
# ╞════════════╪═══════╪═══════╪═══════╡
# │ Customer1  ┆ true  ┆ true  ┆ true  │
# │ Customer2  ┆ false ┆ false ┆ false │
# │ Customer10 ┆ true  ┆ true  ┆ true  │
# └────────────┴───────┴───────┴───────┘
```

**Comment by ritchie46** [comment]
Here is the arrow2 implementation. We only need the binary version as we can use that for utf8 as well. We also need a few adaptations as we can cache regex building etc.

**Comment by orlp** [comment]
I think the easiest solution would be to rewrite `LIKE` queries to our regex calls or `.starts_with` / `.ends_with` as appropriate in the SQL front-end.

**Comment by alexander-beedie** [comment]
@osawyerr: done ;)
