### ISSUE TITLE
v0.19.13 whl is not supported on old Linux x86-64 system

### ISSUE THREAD

**Issue by qqlearn123** [pola-rs/polars#12390]
On my system (Linux x86-64), I can install all Python polars versions fine up until v0.19.12, but fail to install the binary distribution for v0.19.13.

After taking a look at the PyPi site, the reason I guess is v0.19.13 used manylinux_2_28 whereas all other previous versions used manylinux_2_17.

It would be greatly appreciated if we can have backward compatibility, so that the new polars version can still be installed on my current system?

Or is this incompatibility (with old Linux system) intended because of dependencies of the new polars version?

**Comment by s-banach** [comment]
See https://github.com/briansmith/ring/issues/1789#issuecomment-1791469879

I don’t understand any of the technical details, maybe they could use the older manylinux for x86 and the newer version for arm builds?

**Comment by stinodego** [comment]
Unfortunately, we can no longer support version 2.17 due to compatibility issues with some of our dependencies. I upgraded to 2.28, but another option is 2.24. I have uploaded those wheels now - could you try installing again?

**Comment by qqlearn123** [comment]
2.24 does not work as well. So, this means there is no way for polars to support old x86-64 Linux systems any more going forward?

I think this is a relative big thing. It is not like dropping support for Python3.7 since all other libs/pkgs dropped support as well. But in this case, other major Python pkgs do have old Linux system support.

**Comment by qqlearn123** [comment]
Also after a bit of tracking issues, I saw the incompatibility issue is related to aarch-64 in particular? So, it is probably unfair that x86-64 systems are affected because of this?

**Comment by stinodego** [comment]
I guess we can keep releasing older manylinux wheels for x86-64.

Though glibc 2.24 came out in 2016 so it's probably worthwhile to look into upgrading your software. We will not be supporting an older version forever.

**Comment by messense** [comment]
> We will not be supporting an older version forever.

[CentOS Linux 7 will reach end of life (EOL) on June 30, 2024](https://www.redhat.com/en/topics/linux/centos-linux-eol).

CentOS 7 is the major OS that stucks with glibc 2.17, so I would recommend upgrade x86_64 to newer manylinux version after June 30, 2024, which is not far from now. As for polars users using CentOS 7, you are better off upgrade your system soon.
