### ISSUE TITLE
`.map_dict` ignores `return_dtype=` 

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12410]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

mapping = {"a": {"b": "c"}}
return_dtype = pl.Struct({"b": pl.Utf8})

pl.select(
    pl.lit("a").map_dict(mapping, return_dtype=return_dtype)
      .struct["b"]
)
# polars.exceptions.StructFieldNotFoundError: b
```

### Issue description

From this new SO question: https://stackoverflow.com/questions/77470787/is-it-possible-to-map-dict-on-a-nested-dictionary

(The user actually hits 3 different bugs at the same time which is rather interesting.)

As `.map_dict` uses `.map_batches` internally, it seems like `return_dtype` needs to be passed along?

https://github.com/pola-rs/polars/blob/86978f1077ef7f472f86630a028ad0b3b1a15ace/py-polars/polars/expr/expr.py#L9413

Changing this to `self.map_batches(func, return_dtype)` returns the expected result:

```python
shape: (1, 1)
┌─────┐
│ b   │
│ --- │
│ str │
╞═════╡
│ c   │
└─────┘
```

### Expected behavior

`return_dtype` should be respected.

### Installed versions

<details>

Latest commit from `main`

</details>

**Comment by moritzwilksch** [comment]
related to #11332
