### ISSUE TITLE
How to convert pandas filter to polars?

### ISSUE THREAD

**Issue by Keerthesre1** [pola-rs/polars#12429]
I want to convert the python pandas filter to python polars filter.

df.loc[:, df.dtypes == object] = df.loc[:, df.dtypes == object].applymap(lambda x: str(x).strip())

df.loc[:, df.dtypes == object] = df.loc[:, df.dtypes == object].replace('nan', np.NaN)

df[dateCols['fileColumn']] = pd.to_datetime(df[dateCols['fileColumn']], format=dtpattern, errors='raise')

can Someone convert these three pandas filters to polars? Converting the pandas filter to polars is a little bit tricky.

**Comment by ritchie46** [comment]
Please open a stackoverflow question.
