### ISSUE TITLE
str.strip_chars() says it can strip all whitespace but it cannot

### ISSUE THREAD

**Issue by DOH-FAA3303** [pola-rs/polars#12425]
### Description

The documentation says that `strip_chars()` will remove all whitespace by default **but it does not remove whitespace in the middle of a string.** This could be intended so i'm not sure if it's considered a bug. But it isn't clear in the documentation how this function should work.

![image](https://github.com/pola-rs/polars/assets/92396451/d03c4741-02d0-48ab-8e51-9c7c28e5b66d)

# Reproducible Example

```python

df = pl.DataFrame({
    "a": " hello",
    "b": " hello hi",
    "c": " hello hi "
    })
df

```

a | b | c
-- | -- | --
str | str | str
" hello" | " hello hi" | " hello hi "

see how `strip_chars()` only removes leading and trailing white space
```python
df.with_columns(pl.all().str.strip_chars())
```

a | b | c
-- | -- | --
str | str | str
"hello" | "hello hi" | "hello hi"

`str.replace(" ","")` will similarly only remove whitespaces once (unless specified with the `n=` parameter). 

You need to use both `strip_chars()` and `str.replace()` to remove all whitespaces. **This is a little unintuitive and could lead to issues if you're not aware**

```python
df.with_columns(pl.all().str.strip_chars().str.replace(" ",""))
```

a | b | c
-- | -- | --
str | str | str
"hello" | "hellohi" | "hellohi"

 

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.strip_chars.html

**Comment by DOH-FAA3303** [comment]
This is embarrassing, the documentation does say that it only removes leading and trailing characters. It's still a little weird that you need both strip_chars() and str.replace() to remove all whitespace!

**Comment by cmdlineluser** [comment]
It's how the strip methods in Python work if you're not familiar: https://docs.python.org/3/library/stdtypes.html#str.strip

You can also just use [`.replace_all()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.replace_all.html)
