### ISSUE TITLE
MemTracker::free_memory_fraction_since_start can return NaN

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#12424]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

This behavior seems like it might be OS-dependent and does not happen consistently. You can find it in a streaming groupby sink that uses `OocState`.

### Issue description

Calling `MEMINFO.free()` sometimes erroneously(?) returns 0. This means calling `MemTracker::new` will sometimes set its `available_at_start` variable to 0. This means that calling `MemTracker::free_memory_fraction_since_start` will return NaN as long as `MEMINFO.free()` continues to return 0. This affects control flow based on memory pressure in operations such as streaming groupby sink.

This behavior seems OS-dependent. So far I've only been able to reproduce this on an Apple M1 Mac.

### Expected behavior

`MemTracker::free_memory_fraction_since_start` should not return NaN. I wonder what a sensible default would look like. Maybe return 0 in the place of NaN?

### Installed versions

<details>

Rust polars 0.34.2

CPU: Apple M1 Pro

</details>

**Comment by ritchie46** [comment]
Hmm... Have you got a repro. Maybe with the sysinfo crate. It could be a bug upstream.

**Comment by ByteNybbler** [comment]
I'm realizing now that `MEMINFO.free()` returning 0 was likely because I was running some other processes on my Mac at the time, so it wasn't an upstream sysinfo bug -- there actually was no memory that was considered available. From my understanding, "available memory" is distinct from what sysinfo considers to be "free memory".

These circumstances are pretty exceptional, but I do wonder if NaN could be handled by just returning 0 instead from `MemTracker::free_memory_fraction_since_start`.

**Comment by ritchie46** [comment]
Yes, or we always add a 1. That way we never divide by zero. Can you make a PR?
