### ISSUE TITLE
Failure parsing %B specifier in strptime

### ISSUE THREAD

**Issue by edavisau** [pola-rs/polars#12427]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import date
import polars as pl

pl.Series(values=[date(2023, 3, 1)], dtype=pl.Date).dt.strftime("%B %Y").str.to_date("%B %Y")
```

### Issue description

Returns error 
`polars.exceptions.ComputeError: Conversion from `str` to `date` failed in column '' for 1 out of 1 values: ["March 2023"]`

### Expected behavior

It should recover the original date 2023-03-01

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
gevent:              <not installed>
matplotlib:          3.7.0
numpy:               1.23.5
openpyxl:            3.1.1
pandas:              1.5.3
pyarrow:             13.0.0
pydantic:            1.10.5
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.46
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I think this may be similar to https://github.com/pola-rs/polars/issues/11416 in the fact that the underlying `chrono` library is strict and it requires an actual day.

**Comment by edavisau** [comment]
Ahhh that makes sense, cheers!
