### ISSUE TITLE
Add `pl.row_num()` as syntactic sugar for `pl.int_range(0, pl.count())`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12420]
### Description

Having a quick expression to grab an integer-based row number is often requested and would be pretty useful. Instead of the usual options:

```python
df.with_row_count("#").select(col("#") < ...).drop(#") # or:
df.select(pl.int_range(0, pl.count()) < ...)
```
This would simplify to:
```python
df.select(pl.row_num() < ...)
```

**Comment by lyngc** [comment]
Prefer `pl.row_num()` if anything. nbr is not an intuitive abbreviation in this case imo.

**Comment by cmdlineluser** [comment]
A somewhat related suggestion was for `pl.cumcount()` to be a top-level function. #7120 (although that is `unsigned int`)

In trying to see what this is called elsewhere, it seems `row_number()` is commonly used (SQL, Spark, TidyVerse, ...?) - perhaps it makes sense to line up with those.

**Comment by stinodego** [comment]
There already is `DataFrame.with_row_count`:
https://pola-rs.github.io/polars/docs/python/dev/reference/dataframe/api/polars.DataFrame.with_row_count.html

Adding this new expression shortcut seems fine with me. It should either be called `pl.row_count()` to align with the existing DataFrame method, or it both should be renamed to `row_number`.

**Comment by deanm0000** [comment]
I think `row_number` is "better" but I don't think it's so much better that it's worth renaming `with_row_count`. 

What about naming the expression `row_number` and deprecating `with_row_count`? I realize deprecating it is more severe than just renaming it. Personally, I've never wanted `with_row_count` on a stand alone basis. I only ever use it as a precursor to do something else in a `with_columns`. If I can get `row_number` directly in the context then I, for one, would never use `with_row_count`.

Apart from how I use it, it does seem odd that it's the only `with_*` to supplement `with_columns`. There's no `with_summary` or `with_shifted` or anything else so it may just be good to retire as being out of place.

**Comment by cmdlineluser** [comment]
@deanm0000 

I think someone pointed out in a previous discussion that `with_row_count` is useful because it inserts the column at a specified position.

If it was only an expression you would need to use `.select()`

```python
df.select(pl.row_number(), pl.all())
```

(Or, at least, that's what I think the suggestion was.)

**Comment by stinodego** [comment]
Keep in mind that we don't need any of these methods - they are simply for convenience.

With that in mind, the DataFrame method makes sense because row numbers make a lot of sense in a DataFrame context - people trying to mimic indexes.

I think it's fine to have both.

**Comment by deanm0000** [comment]
Wait a minute. Shouldn't this just be adding `pl.cumcount()`? Is there any different behavior between let's say `df.with_columns(i=pl.first().cumcount())` than `df.with_columns(i=pl.int_range(0, pl.count())`?

It seems they do the same thing even if `pl.first()` has some nulls. Of course if we had `pl.cumcount()` then having nulls in any columns would be moot anyways.

Also, if I do timeit on a 1M row df, then cumcount takes 272 µs ± 30.8 µs per loop whereas int_range takes 1.63 ms ± 30.5 µs per loop.

**Comment by cmdlineluser** [comment]
They differ in types, `.cumcount()` is unsigned (but so is `.with_row_count()`)

```python
pl.select(pl.lit('foo').cumcount()).schema
# OrderedDict([('literal', UInt32)])
```
```python
pl.select(pl.int_range(0, 1)).schema
# OrderedDict([('int', Int64)])
```
```python
pl.select(pl.lit('foo')).with_row_count().schema
# OrderedDict([('row_nr', UInt32), ('literal', Utf8)])
```

I guess the idea of wanting `Int64` is so you don't have to cast if you want to use it e.g. 

```python
.rolling(index_column = pl.foo(), ...
```

versus

```python
.rolling(index_column = pl.foo().cast(int), ...
```

**Comment by Wainberg** [comment]
+1 for having `pl.row_number()` and `df.with_row_number()`, each of which create a `row_number` column. Although having `pl.row_count()` and `df.with_row_count()` create a `row_count` column also works, it's most important for all three of them to be the same.

**Comment by stinodego** [comment]
> Small nit - if it's called "row number", should it start counting from 1 by default like SQL does instead of 0?

I considered this but I don't think so. We start counting at 0, right? I find the SQL behavior here strange.

**Comment by mcrumiller** [comment]
If that's the case then I think I would prefer `row_index`. Having zero-indexed rows is the most common use case.

**Comment by stinodego** [comment]
I also considered `row_index`. Maybe that's better indeed.

**Comment by orlp** [comment]
My vote goes to `row_index`. I would also be in support of a rename of `with_row_count` to `with_row_index`.

**Comment by mcrumiller** [comment]
Would it be too much clutter to include both? a `with_row_count` for those who want to match SQL and `with_row_index` for those who want zero-indexed behavior?

An alternative is `with_row_index(start=0)` which would be one function, with default behavior of 0-indexed, and allow for easy arbitrary start positions.

**Comment by orlp** [comment]
@mcrumiller `with_row_count`/`with_row_index` already support an `offset` parameter. You can pass `offset = 1` and get SQL's behavior.

I don't think it'd really be necessary for `pl.row_index()` since you can just write `pl.row_index() + offset`.

**Comment by ritchie46** [comment]
There

> They differ in types, `.cumcount()` is unsigned (but so is `.with_row_count()`)
> 
> ```python
> pl.select(pl.lit('foo').cumcount()).schema
> # OrderedDict([('literal', UInt32)])
> ```
> 
> ```python
> pl.select(pl.int_range(0, 1)).schema
> # OrderedDict([('int', Int64)])
> ```
> 
> ```python
> pl.select(pl.lit('foo')).with_row_count().schema
> # OrderedDict([('row_nr', UInt32), ('literal', Utf8)])
> ```
> 
> I guess the idea of wanting `Int64` is so you don't have to cast if you want to use it e.g.
> 
> ```python
> .rolling(index_column = pl.foo(), ...
> ```
> 
> versus
> 
> ```python
> .rolling(index_column = pl.foo().cast(int), ...
> ```

We can except a dtype in the expression.

I'd like to slow this down a little bit. I don't think we should add an expression for this. We have ranges, a well known construct in many programming languages.

**Comment by Wainberg** [comment]
> We have ranges, a well known construct in many programming languages.

Yes, though I'd argue `pl.int_range(0, pl.count()).alias('row_index')` is quite a mouthful compared to `pl.row_index()` for such a common operation!

In practice people would probably just use `with_row_count()` or whatever it gets renamed to. Though by your argument, shouldn't `with_row_count()` also be deprecated? After all, we have ranges ;)

**Comment by mcrumiller** [comment]
> Though by your argument, shouldn't with_row_count() also be deprecated? After all, we have ranges ;)

This doesn't really help when trying to bring someone to your point of view....

That being said, I agree that this whole conversion is being muddled. I think many of us agree that being able to quickly index columns and frames by integer number is very useful and common enough that it warrants some function. The cleanest solution to me is a single expression `pl.row_index()`, and alongside of that a single dataframe function `df.with_row_index()`. I even think `pl.index()` alone would be nice, but it may cause confusion with pandas indexes.

```python
# default signatures
df.with_index(start=0, dtype=pl.UInt32)
df.with_row_index(start=0, dtype=pl.UInt32)  # 
```

**Comment by stinodego** [comment]
I also think it's worth adding a `pl.index()` function, but if Ritchie isn't on board, we don't need to rush this. I'll add a note to the `int_range` docs with an example on how to create an index column.

**Comment by mcrumiller** [comment]
I know this is closed, but I really think a `pl.row_index()` expression would save a lot of grief when people want to deal with row numbers, over having to use `pl.int_range(pl.len())`. It's a lot clearer what the intent is. I can't tell from the above comments if it was firmly decided "no" we don't want that, or if we wanted to discuss more.

**Comment by cmdlineluser** [comment]
Just with the naming in the new idiom: `pl.int_range(pl.len())` 

I am reminded of `range(len())` in Python and how `enumerate()` is recommended instead of it.

Perhaps it could be nice to have the same name for the frame method and expression:

```python
df.enumerate() 
df.select(pl.enumerate(), pl.all())
```

**Comment by mcrumiller** [comment]
Use `pl.int_range(pl.len())`:

```python
import polars as pl

df = pl.DataFrame({
    "group": [1, 1, 1, 2, 2],
    "value": [1, None, 2, 3, 4],
})

df.sort('value', descending=True).with_columns(pl.int_range(1, pl.len()+1).over('group').alias('nth'))
```
```
shape: (5, 3)
┌───────┬───────┬─────┐
│ group ┆ value ┆ nth │
│ ---   ┆ ---   ┆ --- │
│ i64   ┆ i64   ┆ i64 │
╞═══════╪═══════╪═════╡
│ 1     ┆ null  ┆ 1   │
│ 2     ┆ 4     ┆ 1   │
│ 2     ┆ 3     ┆ 2   │
│ 1     ┆ 2     ┆ 2   │
│ 1     ┆ 1     ┆ 3   │
└───────┴───────┴─────┘
```

**Comment by mkleinbort-ic** [comment]
Sorry I deleted my comment, I realized I could just use `.rank()`

**Comment by mcrumiller** [comment]
Careful though, rank won't give you a rank for nulls.

**Comment by mkleinbort-ic** [comment]
Thank you. 

In my case I don't have nulls so this will be ok.

Can't say I love `pl.int_range(1, pl.len()+1)`, but this is a closed issue and thus not a place to discuss.

**Comment by mcrumiller** [comment]
@mkleinbort-ic I work around this now by always defining a `row_index` expression:

```python
import polars as pl

def row_index():
    return pl.int_range(1, pl.len()+1)

df = pl.DataFrame({
    "group": [1, 1, 1, 2, 2],
    "value": [1, None, 2, 3, 4],
})
df.sort('value', descending=True).with_columns(row_index().over('group').alias('nth'))
```

Doesn't have to be a function but it's more obvious that it's computing something.

**Comment by Oreilles** [comment]
I also really think that `pl.row_index()` would be a valuable addition to polars.

Using `pl.int_range(pl.len())` is more verbose and do not reflect the intent of `pl.row_index()`.

Furthermore, `int_range` returns `pl.Int64` wherehas `with_row_index()` returns `pl.Uint32`, meaning that the two are not even compatible by default if you were to use these as a join key, which is the primary use case for an row index.
