### ISSUE TITLE
pl.all_horizontal() and pl.any_horizontal seem to be inversed 

### ISSUE THREAD

**Issue by McNickSisto** [pola-rs/polars#12438]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(
    {
        "a": [False, False, True, None, True],
        "b": [False, True, None, None, True],
        "c": ["w", "x", "y", "z","a"],
    }
)
```

```python
df.with_columns(pl.all_horizontal("a", "b").is_null())
```

<html>
<body>

a | b | c | all
-- | -- | -- | --
bool | bool | str | bool
false | false | "w" | false
false | true | "x" | false
true | null | "y" | true
null | null | "z" | true
true | true | "a" | false

</body>
</html>

```python
df.with_columns(pl.any_horizontal("a", "b").is_null())
```

<html>
<body>
<br class="Apple-interchange-newline">

a | b | c | any
-- | -- | -- | --
bool | bool | str | bool
false | false | "w" | false
false | true | "x" | false
true | null | "y" | false
null | null | "z" | true
true | true | "a" | false

</body>
</html>

### Issue description

Potential operation inversion between **pl.all_horizontal()** and **pl.any_horizontal()** when filtering for **is_null()**.

### Expected behavior

Expecting that pl.all_horizontal(true, null) returns false as the **AND** bitwise operation. While pl.any_horizontal(true, null) should return true.

```Python
df.with_columns(pl.any_horizontal("a", "b").is_null())
```

<html>
<body>

a | b | c | all
-- | -- | -- | --
bool | bool | str | bool
false | false | "w" | false
false | true | "x" | false
true | null | "y" | true
null | null | "z" | true
true | true | "a" | false

</body>
</html>

```Python
df.with_columns(pl.all_horizontal("a", "b").is_null())
```

<html>
<body>
<br class="Apple-interchange-newline">

a | b | c | any
-- | -- | -- | --
bool | bool | str | bool
false | false | "w" | false
false | true | "x" | false
true | null | "y" | false
null | null | "z" | true
true | true | "a" | false

</body>
</html>

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Windows-10-10.0.17763-SP0
Python:              3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]```

</details>

**Comment by stinodego** [comment]
`is_null` works correctly and should not be included in this example.

The horizontal functions use Kleene logic to determine the outcome - there is no possibility to ignore nulls yet.
Check the examples of the vertical aggregations to see examples.

The results here are correct.

**Comment by JulianCologne** [comment]
@stinodego yes, is works correct but I can see how for a new user this is confusing:

**`pl.all_horizontal("a", "b").is_null()` /  `pl.any_horizontal("a", "b").is_null()`**

Sounds a little like: check if horizontally ALL/ANY values are null

But really is: horizontally compute bitwise AND/OR and afterwards check for null


```python
df.with_columns(
    all_bool=pl.all_horizontal("a", "b"),
    any_bool=pl.any_horizontal("a", "b"),
    all_null=pl.all_horizontal(pl.all().is_null()),
    any_null=pl.any_horizontal(pl.all().is_null()),
)
# ┌───────┬───────┬──────────┬──────────┬──────────┬──────────┐
# │ a     ┆ b     ┆ all_bool ┆ any_bool ┆ all_null ┆ any_null │
# │ ---   ┆ ---   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
# │ bool  ┆ bool  ┆ bool     ┆ bool     ┆ bool     ┆ bool     │
# ╞═══════╪═══════╪══════════╪══════════╪══════════╪══════════╡
# │ false ┆ false ┆ false    ┆ false    ┆ false    ┆ false    │
# │ false ┆ true  ┆ false    ┆ true     ┆ false    ┆ false    │
# │ true  ┆ null  ┆ null     ┆ true     ┆ false    ┆ true     │
# │ null  ┆ null  ┆ null     ┆ null     ┆ true     ┆ true     │
# │ true  ┆ true  ┆ true     ┆ true     ┆ false    ┆ false    │
# └───────┴───────┴──────────┴──────────┴──────────┴──────────┘
```


It might be a great utility feature to add `all_null` / `any_null`

**Comment by McNickSisto** [comment]
@stinodego @JulianCologne thanks for the explanation, just seemed a bit counter intuitive at first
