### ISSUE TITLE
Only add hive columns if it was a wildcard in the path

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#12445]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
file_path="abfs://myds/year=2022/*/0000.parquet"
df=pl.scan_parquet(file_path).collect()
"year" in df.columns
# True
```

### Issue description

I think the code looks for any path that has = and then adds that as a column to the df. I don't think it should do this unless the path was a wildcard. For instance, in the above, the * was for month and that should be added.

### Expected behavior

On the python side, we can do this like 

`df=pl.scan_parquet(file_path).drop([x.split('=')[0] for x in file_path.split('/') if "=" in x]).collect()`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:              3.10.13 (main, Nov  1 2023, 14:20:38) [GCC 10.2.1 20210110]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         3.0.0
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.1
openpyxl:            3.1.2
pandas:              2.1.2
pyarrow:             14.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              1.0.10
sqlalchemy:          2.0.23
xlsx2csv:            0.8.1
xlsxwriter:          3.1.9
```

</details>

**Comment by ritchie46** [comment]
It does this because `hive_partitioning` defaults to `True`.
