### ISSUE TITLE
rename `str.parse_int` into `str.to_integer`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#12441]
### Description

I had a hard time finding this function : `str.parse_int`.
`str.to_time`, `str.to_date`, `str.to_datetime`, `str.to_decimal` already exist, so it would make sense to name `parse_int`  `to_intger`. In this case it would be tab-completion friendly

**Comment by stinodego** [comment]
Yeah I think this is a good call.

**Comment by stinodego** [comment]
After looking into this, there are some additional things I want to pick up in one go. Closing in favor of #12451
