### ISSUE TITLE
Allow tuple keys in `schema_override` parameter of `read_excel`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12447]
### Description

It would be nice to be able to simplify
```python
schema_overrides = {
    "column_a": pl.UInt8,
    "column_b": pl.UInt8,
}
```
to
```python
schema_overrides = {
    ("column_a", "column_b"): pl.UInt8,
}
```

**Comment by mcrumiller** [comment]
@alexander-beedie

**Comment by alexander-beedie** [comment]
Should be generic to all `schema_overrides` if we do this; will have a think.

**Comment by mcrumiller** [comment]
My thinking here was that other Excel functions like `write_excel(..., conditional_formats={})` treats tuples of keys as the same format applied to multiple columns as described [here](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_excel.html). Why allowed there and not here?

**Comment by cmdlineluser** [comment]
I'm not sure if this is a terrible suggestion or not but I was reminded of this by reading #12537

> replace many with the same (n:1)
>    `replace([v1, ,v2, ...], <new>)`

It seems like there are a few places where this type of syntax is useful/desired.

People can do it manually with comprehensions, but would a "utility" function help at all?

It still requires extra code from the user but it would mean not having to support it in each function directly.
 
```python
schema_overrides = pl.util.something({
    ("column_a", "column_b"): pl.UInt8,
})
```


<sub>P.S. @mcrumiller I only read https://github.com/pola-rs/polars-book/issues/329#issuecomment-1599038028 the other day. It was very useful feedback - so thank you for that. Thankfully, someone will actual writing ability took over. (I couldn't figure out any other way to reply.)</sub>

**Comment by alexander-beedie** [comment]
Hmm, ok, will let the idea marinate little longer  ;)
(Am in Spain for a few days, so limited time at the moment).

**Comment by alexander-beedie** [comment]
Have been back and forth on this for too long, heh. Going with my first instinct here; it's too non-standard to implement everywhere. 

Also, it shuts down potential use-cases such as overriding a single field in a struct, which might be a more valid use for tuple-indexing schema_overrides? Not sure about that one either, but on the off-chance we end up indexing into something nested I don't want to have blocked it by having a less-obvious expansion already occupying that syntax 🤔
