### ISSUE TITLE
Illegal instruction when importing polars on mac osx

### ISSUE THREAD

**Issue by paulf81** [pola-rs/polars#12454]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
conda create -n test_env python
conda activate test_env
pip install polars
python
```

### Log output

```shell
Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 12:29:27) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
Illegal instruction: 4
```

### Issue description

Lately when installing polars into a clean conda environment I get an error "Illegal instruction: 4" as an output.  

### Expected behavior

I am currently not able to import polars into a conda environment in which both python and polars versions are not specifically mentioned on mac os.  

### Installed versions

  Using cached polars-0.19.13-cp38-abi3-macosx_10_12_x86_64.whl.metadata (14 kB)

**Comment by paulf81** [comment]
I installed polars-lts-cpu based on this section:
https://github.com/pola-rs/polars#legacy

And now imports successfully, so maybe same issue as others

**Comment by paulf81** [comment]
For what it's worth, I've found I can successfully import up to 0.19.5 but any version after that has this issue

**Comment by alexander-beedie** [comment]
I can see that your wheel references `x86_64`; assuming your machine is running an M1/M2/M3 chip, is your `conda` version native for Apple Silicon? If it is not then you _must_ run the `polars-lts-cpu` build as Rosetta translation (which allows `x86_64` code to run on these chips) cannot handle AVX instructions. However, if you have the native version of condo you should have no trouble.

**Comment by ritchie46** [comment]
>  pinning to 0.19.5 is the more general solution because up to this version we don't need to specify a special build.

No it is not? If you want to run under rosetta, you need to use polars-lts-cpu. That's intended.

**Comment by paulf81** [comment]
Thank you very much for your reply!  But, how should I package my project that relies on polars for cross-platform support?  Should I specify the LTS version for everyone as the common denominator?

**Comment by paulf81** [comment]
Could I request an opinion on this solution?  In our repo, polars is a requirement, I was thinking a more correct approach than specifying the LTS version as a common denominator, would be to add a "mac" option to the pip install such that if selected the LTS version is installed in place of the normal distribution.  Thanks very much for any suggestions!!!

**Comment by orlp** [comment]
@paulf81 The real answer is to install the correct version of Python on the M* Mac machines, instead of the emulated Rosetta version.

We already have an issue open for doing better detection of the CPU capabilities and giving a proper error message instead of just an illegal instruction error: https://github.com/pola-rs/polars/issues/11658.
