### ISSUE TITLE
Let `pl.DataFrame.rename` and `pl.LazyFrame.rename` accept a `Callable[[str],str]`

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#12452]
### Description

Currently `rename` accepts a `dict[str,str]` mapping the existing column name to the new column name

It'd be good to also support a python callable - e.g. `lambda x: x.upper()` or `lambda x: x.split('_')`, etc...

**Comment by mkleinbort-ic** [comment]
Currently this works, but it's not very pretty
```python
df.pipe(lambda x: x.rename({c:c.replace('_v2','') for c in x.columns}))
```

**Comment by mkleinbort-ic** [comment]
Syntactic sugar - same behaviors as 
```python
df.select(pl.all().name.map(lambda x: x.replace('_v2',''))
```

Ps. I forgot about `name.map`, but the ask remains.

**Comment by mcrumiller** [comment]
(Also #11752 if anyone aside from me wants that as well)

**Comment by mkleinbort-ic** [comment]
I've reflected on this - now that I remember about `.name.map` I don't think this is needed. I'll close the issue to clear up the tracker.
