### ISSUE TITLE
Deltalake: Issue with specified schema for large dtypes

### ISSUE THREAD

**Issue by fierzdev** [pola-rs/polars#12467]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pyarrow as pa
import polars as pl
my_schema = pa.schema([pa.field("string", pa.string(), nullable=False), pa.field("large_list", pa.large_list(pa.field("large_string",pa.large_string())))])
df = pl.DataFrame({"string": ["string", "string"], "large_list": [["large string"], ["large_string"]]})
df.write_delta("deltatable", delta_write_options={"schema": my_schema})  # This works
df.write_delta("deltatable", delta_write_options={"schema": my_schema}, mode="append")  # this fails because of schema errors

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/polars/dataframe/frame.py", line 3649, in write_delta
    write_deltalake(
  File "/opt/conda/lib/python3.10/site-packages/deltalake/writer.py", line 201, in write_deltalake
    raise ValueError(
ValueError: Schema of data does not match table schema
Data schema:
string: string not null
large_list: large_list<large_string: large_string>
  child 0, large_string: large_string
Table Schema:
string: large_string not null
large_list: large_list<item: large_string>
  child 0, item: large_string
>>> 

```

### Issue description

When writing to a deltatable and specifying a pyarrow schema, errors can occur when we want to write to the same table again. This seems to happen because Polars uses large_dtypes on default (https://github.com/pola-rs/polars/blob/ae7ed5c8df5b8337ef5e520bb4a0fa6c16610b75/py-polars/polars/dataframe/frame.py#L3655-L3656) and, if I interpret that right, thus overwrites the schema even if that does not use large dtypes. 

### Expected behavior

When the schema is specified, it should not automatically use large dtypes in my opinion, but stick to the defined schema to avoid such errors. 
This could be solved by not settings large_dtypes to True, if a schema is specified. 

I'd be happy to contribute if you agree that this would be the wanted behaviour.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.15.0-88-generic-x86_64-with-glibc2.31
Python:              3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.13.0
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by fierzdev** [comment]
Tagging @ion-elgreco here as I think this is related to https://github.com/pola-rs/polars/pull/12260

**Comment by ion-elgreco** [comment]
I'm working on something upstream to consolidate some parts of this: https://github.com/delta-io/delta-rs/pull/1820

However in your case, i need to think about how we want to handle this. Basically you are passing a schema with mixed normal and large types which won't ever result in a correct schema match. Unless you pass overwrite_schema.

Can you explain why you are passing a custom schema with mixed large and normal, since using normal types doesn't make sense for Polars data because you have the possibility that downcasting doesn't fit in memory

**Comment by fierzdev** [comment]
The data that is stored in the "string" column is typically rather small. As the documentation of Pyarrow mentions "This data type may not be supported by all Arrow implementations. Unless you need to represent data larger than 2GB, you should prefer string().", we thought we'd stick to Strings here. 
And on the other hand, the strings in the large_string column are much longer, so that's why we decided to go for a mixed schema. But here we can also change everything to be large_string.

**Comment by ion-elgreco** [comment]
@fierzdev Polars only uses large types so it's already in memory like that.

**Comment by fierzdev** [comment]
Good to know. If there is no reason why this should be handled by Polars, we can close the issue.
