### ISSUE TITLE
Add graphviz in the list of optional dependencies

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#12477]
### Description

I don't know if the list of dependencies in the readme is supposed to be exhaustive. In that case `graphviz` is missing from the list

```python
pl.LazyFrame().show_graph()
# ImportError: Graphviz dot binary should be on your PATH
```

**Comment by sky-2002** [comment]
@universalmind303 Shoud this be added to [this](https://github.com/pola-rs/polars/blob/main/py-polars/requirements-dev.txt) file or where?

**Comment by alexander-beedie** [comment]
Note that the Python `graphviz` package does not install the required binary; it only helps you construct "dot" files. It's not a dependency of Polars as we construct those files ourselves.

See: https://graphviz.org/download/

* Mac: `brew install graphviz`
* Linux: `sudo apt install graphviz`
* Windows: download a suitable binary from the link above.

@NexVeridian has a PR incoming that makes the error/info message a little clearer here, providing the downloadd link.
