### ISSUE TITLE
Add dedicated horizontal aggregation methods to dataframe

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#12484]
### Description

Ref https://github.com/pola-rs/polars/issues/12444#issuecomment-1810826957

We want to get rid of the overloaded methods currently on `DataFrame`:
* `sum`
* `min`
* `max`
* `mean`

We will add `sum_horizontal` etc. as replacement for the `axis=1` version of these methods.

**Comment by Wainberg** [comment]
Awesome! Could these also be added? (Many of these are also missing for expressions, see https://github.com/pola-rs/polars/issues/9966).

`df.all_horizontal()`
`df.any_horizontal()`
`df.arg_max_horizontal()`
`df.arg_min_horizontal()`
`df.median_horizontal()`
`df.n_unique_horizontal()`
`df.product_horizontal()`
`df.quantile_horizontal()`
`df.std_horizontal()`
`df.var_horizontal()`

**Comment by stinodego** [comment]
Yes. Right now I am focused on cleaning up irregular parts of the API. Completeness comes later. There's already an issue for adding the extra horizontal functions 👍
