### ISSUE TITLE
Panic when lazily slicing nested parquet column from offset 0

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#12480]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let filename = "out.parquet";
    let num_rows = 1_000_000;

    let df = df![
        "ints" => vec![Series::new("inner", [1; 1]); num_rows],
    ].unwrap();

    df.lazy().sink_parquet(filename.into(), Default::default()).unwrap();

    let lf = LazyFrame::scan_parquet(filename, Default::default()).unwrap();
    let df = lf.slice(0, 1).collect().unwrap();
    assert_eq!(df.height(), 1);
}
```

### Log output

```shell
run UdfExec
RUN STREAMING PIPELINE
df -> parquet_sink
RefCell { value: [] }
thread '<unnamed>' panicked at /Users/bytenybbler/Documents/Rust/Work/polars/crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:392:5:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

The panic only occurs when slicing from offset 0. Slicing from nonzero offsets does not cause this panic.

The column must have nesting to cause this panic.

The column must contain a sufficiently large amount of data for this panic to occur.

### Expected behavior

Slicing from offset 0 should not panic when scanning nested parquet.

### Installed versions

<details>

polars = { version = "0.34.2", features = ["lazy", "streaming", "parquet"] }

</details>

**Comment by cmdlineluser** [comment]
This is odd. `py-polars` can read the file back in, but `.slice(0, 1)` is returning `31_776` rows.

```python
pl.scan_parquet("out.parquet").slice(0, 1).collect()

# shape: (31_776, 1)
# ┌───────────┐
# │ ints      │
# │ ---       │
# │ list[i32] │
# ╞═══════════╡
# │ [1]       │
# │ [1]       │
# │ [1]       │
# │ [1]       │
# │ …         │
# │ [1]       │
# │ [1]       │
# │ [1]       │
# │ [1]       │
# └───────────┘
```

Does this suggest something is wrong with the writing of the file?

**Comment by ByteNybbler** [comment]
The panic occurs due to a subtraction overflow, which is only detected when rust polars is compiled in debug mode. In release mode, the overflow will be ignored, and I believe that's why `py-polars` is returning that incorrect DataFrame. I get a similar result when running rust polars in release mode.
