### ISSUE TITLE
Walrus operator gives linting error as arg to `df.write_csv( file_path := 'folder/filename.csv' )`

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#12495]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df.write_csv( file_path := 'folder/filename.csv' )
```

```python
df_removed_update.write_csv(
    df_removed_update_csv_file_path := os.path.join(self.data_folder, 'df_removed_update.csv')
)
```

Then use pyright or pyright to lint the file, and see that it gives a linting error:

```
No overloads for "write_csv" match the provided argumentsPyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

### Issue description

Walrus operator gives linting error. 

### Expected behavior

No linting error should happen.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-6.1.0-1025-oem-x86_64-with-glibc2.35
Python:              3.9.18 (main, Aug 25 2023, 13:20:14) 
[GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.1.0
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
What about if you put an extra set of parenthesis? It might be getting confused between variable naming and parameter argument naming.

So like `df.write_csv( (file_path := 'blah.csv') )`

In either case, I'm using VSC and my linter doesn't complain with or without the extra parenthesis.

**Comment by DeflateAwning** [comment]
Same issue still:
```
No overloads for "write_csv" match the provided argumentsPyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
frame.py(2459, 9): Overload 2 is the closest match
```

Try with Pyright, if you're not using that already. Pyright has more stringent checks that Pylance's defaults.

**Comment by stinodego** [comment]
What should the type hint be in this case? I hadn't heard of walrus operators affecting type checking.

**Comment by alexander-beedie** [comment]
On the face of it this doesn't appear to be anything to do with Polars; however, I have condensed the underlying error down into a small self-contained test case and raised an [issue](https://github.com/microsoft/pyright/issues/6470) for you in the `pyright` repository.

**Comment by alexander-beedie** [comment]
FYI: the `pyright` maintainers have just merged a fix - will be in their next release :)

**Comment by DeflateAwning** [comment]
Wow, very impressive. Thanks for helping pass the issue along to the proper place! Sorry I assumed the issue was with Polars; I should have done a bit more digging first
