### ISSUE TITLE
hypothesis lower version constraint should be upgraded

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#12518]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

With an older `hypothesis` version this line

```python
from polars.testing.parametric import dataframes
```
fails

### Log output

```shell
tests/test_polars_delta.py:20: in <module>
    from polars.testing.parametric import dataframes
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/polars/testing/parametric/__init__.py:6: in <module>
    from polars.testing.parametric.primitives import column, columns, dataframes, series
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/polars/testing/parametric/primitives.py:29: in <module>
    from polars.testing.parametric.strategies import (
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/polars/testing/parametric/strategies.py:98: in <module>
    alphabet=characters(max_codepoint=1000, exclude_categories=["Cs", "Cc"]),
E   TypeError: characters() got an unexpected keyword argument 'exclude_categories'
```

[full logs](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:9:28)

### Issue description

Seems like it's a new argument, so the lower version constraint should be bumped

### Expected behavior

Version should be bumped

### Installed versions

<details>

```
--------Version info---------
Polars:              0.1[9](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:7:10).13
Index type:          UInt32
Platform:            Linux-6.2.0-[10](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:7:11)15-azure-x86_64-with-glibc2.35
Python:              3.10.13 (main, Aug 28 2023, 08:28:42) [GCC [11](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:7:12).4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.5.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
openpyxl:            <not installed>
pandas:              2.0.2
pyarrow:             [12](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:7:13).0.0
pydantic:            1.10.9
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.[15](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:7:16)
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None```

</details>

**Comment by cmdlineluser** [comment]
Looks like it changed in [6.85.0](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/docs/changes.rst#6850---2023-09-16)

Although Polars does seem to request `6.88.1`

https://github.com/pola-rs/polars/blob/84b0cba004cd417c32328e6819515c2fad4ffeba/py-polars/requirements-dev.txt#L60

**Comment by danielgafni** [comment]
hmm, wondering why [wasn't](https://github.com/danielgafni/dagster-polars/actions/runs/6892360215/job/18749466204?pr=46#step:6:1) `hypothesis` upgraded by Poetry in this case...

My CI installs the latest available `polars` version (by doing `poetry add polars=~0.19.0`) and `hypothesis` should have been upgraded.

**Comment by danielgafni** [comment]
ok apparently `poetry add` does not update some (only some) transient dependencies. Not sure why. A `poetry lock` solves this on my end.
