### ISSUE TITLE
Option to suppress error messages in DataFrame.drop()

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#12520]
### Description

It would be nice, if we could have an option to suppress error messages (like polars.exceptions.ColumnNotFoundError) when dropping columns that no longer exist, so that this expression does not throw an exception.
Something like:
df.drop('mycolumn', suppress_errors=True)

**Comment by cmdlineluser** [comment]
Are you using an older version?

Currently, it no-ops
```python
>>> pl.select(A = 1).drop('foo')
shape: (1, 1)
┌─────┐
│ A   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
└─────┘
```
There is in fact a request to make it error instead: #11913

**Comment by stinodego** [comment]
Closing in favor of #11913
