### ISSUE TITLE
Error when `shift` used inside a `when` call in a `group_by` aggregation.

### ISSUE THREAD

**Issue by noam-delfina** [pola-rs/polars#12526]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
   'a': [1, 1, 1],
   'b': [1, 2, 5],
})

df.group_by('a').agg(
   col=(
     pl.when(pl.col('a').shift(1) > 2).then(pl.lit('abc'))
     .when(pl.col('a').shift(1) > 1).then(pl.lit('def'))
     .otherwise(pl.lit(None))
   ).first()
)
```

### Log output

```shell
ComputeError: predicates length: 3 does not match groups length: 1

Error originated in expression: '.when([(col("a").shift([1])) > (2)]).then(Utf8(abc)).otherwise(.when([(col("a").shift([1])) > (1)]).then(Utf8(def)).otherwise(null.cast(Utf8)))'
```

### Issue description

The error is thrown here (https://github.com/pola-rs/polars/blob/536f334cadd20bfb79729f5a33ea81f501492304/crates/polars-lazy/src/physical_plan/expressions/ternary.rs#L196), which seems to be related to the fact that `shift` is used.

Note that the error disappears if the exact same code is run, but the call to `shift(1)` in the two `when` calls are removed:

```python
df = pl.DataFrame({
   'a': [1, 1, 1],
   'b': [1, 2, 5],
})

df.group_by('a').agg(
   col=(
     pl.when(pl.col('a') > 2).then(pl.lit('abc'))
     .when(pl.col('a') > 1).then(pl.lit('def'))
     .otherwise(pl.lit(None))
   ).first()
)
```

### Expected behavior

Expected output in this case would be:

```
shape: (1, 2)
┌─────┬──────┐
│ a   ┆ col  │
│ --- ┆ ---  │
│ i64 ┆ f32  │
╞═════╪══════╡
│ 1   ┆ null │
└─────┴──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
Python:              3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.5.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             11.0.0
pydantic:            1.10.11
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I ran into this error message in another form recently: #12242 (#12382 is also closely related)

Running this example through `finish_as_iters()` produces the expected result.

https://github.com/pola-rs/polars/blob/4a58499bdf97203c940a3c82c1113905e8c6087d/crates/polars-lazy/src/physical_plan/expressions/ternary.rs#L200-L201

**Comment by noam-delfina** [comment]
@cmdlineluser Thanks for the comment. Can I ask whether and how I can run through `finish_as_iters()` in python? I cannot find any relevant documentation, and don't see that function in the `polars` or `polars.Expr` namespace. That sounds like it would be a useful workaround for the time being. Thanks.

**Comment by cmdlineluser** [comment]
Apologies for any confusion, I was debugging the issue at the Rust level and manually modifying the Polars code and recompiling it.

@nameexhaustion has fixed all 3 issues (thank you!) and it will part of the next release.

**Comment by noam-delfina** [comment]
@cmdlineluser @nameexhaustion Got it, thanks very much! And thanks also to @nameexhaustion for the quick fix of another bug I filed last week (https://github.com/pola-rs/polars/issues/12354)!
