### ISSUE TITLE
`pl.Series.fill_nan` changes the series name

### ISSUE THREAD

**Issue by PierreAttard** [pola-rs/polars#12535]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np

s = pl.Series([np.nan], name="s")
s2 = s.fill_nan(None)

print(s.name, s2.name)

# Both series must have the same name
assert s.name == s2.name
```

### Issue description

On the last version of polars (0.19.13), there is a regression. 

The method `pl.Series.fill_nan` changes the name of the series into the word "literal" whereas it should not change te name of the series.

On the version 0.19.9, the behavior is good, it means that 

```python
s = pl.Series([np.nan], name="s")
s2 = s.fill_nan(None)

s.name == s2.name

```

Maybe this issue is linked with #12521 ?

### Expected behavior

The expected behavior is that `pl.Series.fill_nan` does not change series name.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            1.10.12
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by c-peters** [comment]
This works on main
