### ISSUE TITLE
Add `replace` to replace values (like pandas)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12537]
### Description

A very common use case is to replace some values and keep the rest.
This currently seems to be surprisingly difficult in polars.

## Example

```python
df = pl.DataFrame(
    {
        "country": ["us", "gb", "fr", "es", "de"],
        "val": [4, 6, -1, 7, 9999],
    }
)

# current solution(s)
df.with_columns(
    c1=pl.col("country").map_dict(
        remapping={"gb": "uk"},
        default=pl.first(),
    ),
    c2=pl.when(pl.col("country") == "gb")
    .then(pl.lit("uk"))
    .otherwise(pl.col("country")),

    v1=pl.col("val").map_dict(
        remapping={-1: 0, 9999: 0},
        default=pl.first(),
    ),
)

# suggested
df.with_columns(
    c1=pl.col("country").replace("gb", "uk"),
    v1=pl.col("country").replace([-1, 9999], 0),
)
```

## Pandas
Pandas has `replace` with a lot of functionality. [pandas replace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html)
I would not like to go as far as pandas but there are many usefull variants like:

replace single value (1:1)
- `replace(<current>, <new>)`

replace many with the same (n:1)
- `replace([v1, ,v2, ...], <new>)`

replace many with many (n:n)
- `replace([v1, ,v2, ...], [w1, w2, ...])` or dict
- `replace({v1: w1, v2: w2, ...})`

**Comment by mkleinbort-ic** [comment]
This exists under the name [map_dict](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.map_dict.html#polars.Expr.map_dict)

**Comment by JulianCologne** [comment]
@mkleinbort-ic  thanks for your input, but did you even read my issue? I gave just the example you posted 😜 

Polars has come far way and you can do almost anythink at this point.
But for a few very common use cases the api is not optimal yet and this is one on them.

yes, as you said and as I gave example in my issue discription there is `map_dict` but it quite cumbersome to work with for such an easy task and polars will always be compared to pandas which has a nicer solution for this currently.

### Replace a single value (1:1)
```python
.replace(v1, r1)
```
is much nicer, more untuitive and ergonomic than
```python
.map_dict(
    remapping={v1: r1},
    default=pl.first(),
)
```

### Replace multiple values with the same (n:1)
```python

.replace([v1, v2, v3, v4, v5], r1)
```
VS
```python
.map_dict(
    remapping={
        v1: r1,
        v2: r1,
        v3: r1,
        v4: r1,
        v5: r1,
    },
    default=pl.first(),
)
```

### Replace multiple values with multiple vlaues (n:n)
```python
.replace([v1, v2, v3, v4, v5], [r1, r2, r3, r4, r5])
```
or
```python
.replace(
    remapping={
        v1: r1,
        v2: r2,
        v3: r3,
        v4: r4,
        v5: r5,
    }
)
```
VS
```python
.map_dict(
    remapping={
        v1: r1,
        v2: r2,
        v3: r3,
        v4: r4,
        v5: r5,
    },
    default=pl.first(),
)
```

**Comment by cjackal** [comment]
I think your n:1 remapper example is unfair; one can do
```python
pl.when(pl.col(c).is_in(vs)).then(r1).otherwise(pl.col(c))
```
which is comparable to pandas' `.replace(vs, r1)`

**Comment by cmdlineluser** [comment]
There are some potentially interesting replies starting after https://github.com/pola-rs/polars/issues/10755#issuecomment-1703333545 where I asked a similar question previously.

**Comment by cmdlineluser** [comment]
For case1 I think it came up previously (#10755) that there would be a specific function for it i.e.

`.replace_values(...)` -> `.map_dict(..., default=pl.first())`

**Comment by ritchie46** [comment]
Maybe we can expose a `replace` method, that dependent on the input, dispatched to either `when -> then -> otherwise` or `map_dict`.

E.g. make it more convenient and under the hood try to find the best way to replace values.

**Comment by alexander-beedie** [comment]
> Maybe we can expose a `replace` method, that dependent on the input, dispatched to either `when -> then -> otherwise` or `map_dict`.

Related optimisation opportunity - if we see `when/then` being used where `map_dict` would be more suitable (eg: a chain of equality checks like `when x == 1 then "a" when x == 2 then "b" when x == 3 then "c" ...), dispatch accordingly? I saw this being done at work on a chain of hundreds of values, and the speedup from switching the code over was a transform/lookup that ran 1-2 orders of magnitude faster 😅

**Comment by stinodego** [comment]
I am going to close this in favor of https://github.com/pola-rs/polars/issues/10755

As I posted there: we should rename `map_dict` to `replace`.

The syntactic sugar for the various mappings are easily done by doing some functional programming, so I don't think we should be adding that.
