### ISSUE TITLE
pl.concat crashes Python with how='diagonal_relaxed'

### ISSUE THREAD

**Issue by luukhopman** [pola-rs/polars#12543]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

 ```python
import polars as pl

pl.concat(
    items=[
        pl.DataFrame({'a': range(1)}).transpose(),
        pl.DataFrame({'a': range(10000)}).transpose(),
    ],
    how='diagonal_relaxed',
)
```

### Issue description

Python consistently crashes when I run the code provided as example. I was able to reproduce this in multiple environment and on multiple systems. In general it seems to occur if items to be concatenated have large differences in the number of columns. With `how='diagional'`, the same concatenation runs fine.

### Expected behavior

The code should run without crashing Python.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.10.192-183.736.amzn2.x86_64-x86_64-with-glibc2.31
Python:              3.10.9 (main, Jun  1 2023, 17:32:48) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.5.0
gevent:              <not installed>
matplotlib:          3.7.0
numpy:               1.24.2
openpyxl:            3.1.2
pandas:              2.0.2
pyarrow:             12.0.0
pydantic:            1.10.7
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.47
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks, can confirm we have a stackoverflow.

**Comment by henryharbeck** [comment]
Hi @stinodego, this issue can potentially be closed. The reproducible example no longer raises for me.

**Comment by luukhopman** [comment]
Thanks, I can confirm it no longer occurs since `0.20.24`.
