### ISSUE TITLE
Unable to compile polars-lazy v0.35.2

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#12564]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Compilation failed at the stage of `polars-lazy`.

My `dependencies` section in Cargo.toml is like below:
```
[dependencies]
polars = { version = "0.35.2", features = ["dtype-struct", "lazy", "nightly"] }
polars-core = "0.35.2"
```

### Log output

The compilation error is as follows:
```
error[E0599]: no method named 'as_stats_evaluator` found for struct `std::sync::Arc<(dyn physical_plan::expressions:PhysicalExpr + 'static)>` in the current scope
```

### Issue description

Compilation failed at the stage of `polars-lazy`.

### Expected behavior

Compile without error.

### Installed versions

```
rust polars - v0.35.2
rustup - nightly-2023-11-15
```

**Comment by ritchie46** [comment]
Yeap. Just fixed it. Will release a patch.
