### ISSUE TITLE
Treat string input as column name where string literal is not allowed

### ISSUE THREAD

**Issue by bkos** [pola-rs/polars#12578]
### Description

As mentioned on discord with @stinodego, in cases where string literal is not allowed as input (e.g. in `expr.add`, `expr.truediv`, etc.), it would be very convenient to treat string input as column name. Currently it throws the compute error.
```python
df = pl.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3]})

# Works fine 
df.with_columns(pl.col('a').truediv(pl.col('b')))

# Error
df.with_columns(pl.col('a').truediv('b'))
```
`ComputeError: arithmetic on string and numeric not allowed, try an explicit cast first`

**Comment by stinodego** [comment]
I think we should do the following:

* Expr operator _methods_ (i.e. `eq`, `truediv`, ...) follow the regular rules for parsing expressions, i.e. strings are parsed as column names, other inputs are parsed as literals.
* Expr _operators_ (i.e. `==`, `//`, ...) are always parsed as literals. Somehow it feels weird to have `pl.col("foo") == "a"` parse that `"a"` as a column name.

**Comment by stinodego** [comment]
Actually, I changed my mind. The operator methods and the operators should function exactly the same. But we can indeed treat some methods differently from others. Equality methods should treat inputs as string literals, other methods such as `pow` can parse string inputs as a column name.
