### ISSUE TITLE
Use jemalloc for macOS builds (Python, CLI, etc) and update docs

### ISSUE THREAD

**Issue by cardoso** [pola-rs/polars#12579]
I'd love to get some thoughts here and benchmarks from other setups to compare.

### Description

According to my benchmarks, jemalloc also has a 20%-to-30% benefit in performance over the system allocator on macOS.

Tested on a parquet file of ~327mb with a column containing some huge strings. In average it takes 7s compared to 9s with the system allocator (22%) for this particular file. I converted it with the default settings from an uncompressed ~16gb csv file.

```
[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
```

Relevant: polars_arrow::array::utf8::Utf8Array<O>::try_new

![flamegraph](https://github.com/pola-rs/polars/assets/5606812/e3c9ea54-fd67-4457-aef9-0132d6959c1a)

PS: I also run some smaller queries in smaller files without the huge column at the beginning of the flamegraph. I'm ignoring those for now.

```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Model Number:	MK1H3LL/A
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	10151.41.12
  OS Loader Version:	10151.41.12
  Serial Number (system):	DXC02KQV03
  Hardware UUID:	FF1048B0-A2AD-575A-8AE6-0CF85CF66A4B
  Provisioning UDID:	00006001-000A69020C9A801E
  Activation Lock Status:	Enabled
```

**Comment by ritchie46** [comment]
Yes, already added that. Can you make a PR to update the docs?

**Comment by cardoso** [comment]
Thanks @ritchie46 . 🙌  I'll update the docs.
