### ISSUE TITLE
Correlation in Polars v0.19.14 is different from Numpy and Polars previous versions by a not negligible amount

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#12571]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

# sample df
rng = np.random.default_rng(1)
n = 1000
v1 = rng.integers(1, 5, n)
v2 = rng.integers(1, 10, n)
v3 = rng.normal(0, 1, n)
df = pl.DataFrame(dict(v1=v1, v2=v2, v3=v3))

# polars
df.select(
    [
        pl.corr("v1", "v2").alias("v1_v2"),
        pl.corr("v1", "v3").alias("v1_v3"),
        pl.corr("v2", "v3").alias("v2_v3"),
    ]
).transpose().to_series().to_list()

# numpy
[np.corrcoef(v1, v2)[0, 1], np.corrcoef(v1, v3)[0, 1], np.corrcoef(v2, v3)[0, 1]]
```

### Log output

```shell
# polars v0.19.14
[0.0324787932825922, 0.04403037651034829, -0.03309041344421535]

# numpy
[0.03370584561421432, 0.04522495151174331, -0.031896298576485106]

# polars v0.19.13
[0.03370584561421432, 0.04522495151174331, -0.031896298576485106]
```

### Issue description

About 3% or 1e-3 difference in correlation is introduced between Polars v0.19.14 and Numpy or previous Polars versions (in my example). I think it is the result of the new online algorithm which improves performance.

But, in my opinion, this ~3% or 1e-3 difference is not negligible to extend of numerical errors (typically ~1e-6) and should be considered breaking changes. I highly suggest we should still at least honor a (conventional) method which gives the same results as other mainstream methods, like the one in Numpy (or Pandas or previous Polars versions). And, we could name the new method something like, `corr_fast` but with the warning that it could give different results bigger than numerical error magnitude.

Or if possible, refine the online algorithm to make it as close as the original method (<1e-6).

### Expected behavior

Same results as previous versions or Numpy or within 1e-6.

### Installed versions

<details>

```
v0.19.14
```

</details>

**Comment by ritchie46** [comment]
Yeap, seems reasonable. Will make it a fast option.

**Comment by ritchie46** [comment]
#12572

**Comment by orlp** [comment]
The new PR should have slightly better speed benefits at the same accuracy: https://github.com/pola-rs/polars/pull/12590.
