### ISSUE TITLE
Using `.filter()` with keyword args `col=[list_of_values]` raises `ComputeError`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12580]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"A": [1, 2]})

df.filter(A = [1, 2, 3])
# ComputeError: cannot evaluate two Series of different lengths (2 and 3)
# Error originated in expression: '[(col("A")) == (Series)]'
```

### Issue description

If `len(list_of_values) == df.height` it does appear to produce the "expected" result:

(that is, if you expected it to be an "is_in" comparison)

```python
df = pl.DataFrame({"A": [1, 2]})

df.filter(A = [1, 2])
# shape: (2, 1)
# ┌─────┐
# │ A   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# └─────┘
```

```python
df.filter(A = [1, 5])
# shape: (1, 1)
# ┌─────┐
# │ A   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# └─────┘
```

If the list is longer, it raises

```python
df.filter(A = [1, 2, 3])
# ComputeError: cannot evaluate two Series of different lengths (2 and 3)
# Error originated in expression: '[(col("A")) == (Series)]'
```

The fact that it works in some cases may gave the false impression that is supported which may not be intended.

### Expected behavior

I'm not sure.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.14
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.6 (main, Oct  2 2023, 20:46:17) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by JulianCologne** [comment]
I agree that this might not be what you expect but I think this will change soon anyway when `[1,2,3]` will get interpreted as `lit([1,2,3])`, right?
```DeprecationWarning: Behavior for `lit` will change for sequence inputs. The result will change to be a literal of type List. To retain the old behavior, pass a Series instead, e.g. `Series(sequence)`.```

also just to clarify, even if the length are equal this does not do an `is_in` operation
```python
df = pl.DataFrame({"A": [1, 2]})
df.filter(A = [2, 1])
shape: (0, 1)
┌─────┐
│ A   │
│ --- │
│ i64 │
╞═════╡
└─────┘
```

**Comment by cmdlineluser** [comment]
Thanks @JulianCologne - I should have thought of that as another case to test.

I see what is actually happening now:
```python
>>> df["A"] == pl.Series([2, 1])
# shape: (2,)
# Series: 'A' [bool]
# [
# 	false
# 	false
# ]
```
