### ISSUE TITLE
Unable to convert series to json and assign it to new column 

### ISSUE THREAD

**Issue by amplifinn-admin** [pola-rs/polars#12581]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```

### Issue description

Unable to convert series to json and assign it to new column 

### Expected behavior

>>> pandas_df1 = pd.DataFrame({"col1": [1,1,1,1,1,1], "col2": [7,2,7,7,2,2], "col3": [9,4,9,3,9,5]})
>>> 
>>> pandas_df1
   col1  col2  col3
0     1     7     9
1     1     2     4
2     1     7     9
3     1     7     3
4     1     2     9
5     1     2     5
>>> 
>>> 
>>> pandas_df1['Json'] = pandas_df1[['col1', 'col2']].apply((lambda x: x.to_json()), axis=1)
>>> pandas_df1
   col1  col2  col3                 Json
0     1     7     9  {"col1":1,"col2":7}
1     1     2     4  {"col1":1,"col2":2}
2     1     7     9  {"col1":1,"col2":7}
3     1     7     3  {"col1":1,"col2":7}
4     1     2     9  {"col1":1,"col2":2}
5     1     2     5  {"col1":1,"col2":2}

### Installed versions

--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            macOS-13.0-arm64-arm-64bit
Python:              3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              21.12.0
matplotlib:          3.8.1
numpy:               1.21.2
openpyxl:            3.0.5
pandas:              1.5.3
pyarrow:             14.0.0
pydantic:            1.8.2
pyiceberg:           <not installed>
pyxlsb:              1.0.10
sqlalchemy:          1.4.50
xlsx2csv:            0.8.1
xlsxwriter:          3.0.1

**Comment by cmdlineluser** [comment]
The "Reproducible example" section is empty so there is no Polars code example.

**Comment by amplifinn-admin** [comment]
How do we do it in polars, with the sample code of pandas?
Need to convert set of columns to json and assign it to new column

**Comment by cmdlineluser** [comment]
Oh right.

It looks like #11728 (I don't think there is currently a "built in" way to do this - I could be mistaken)

```python
df = pl.DataFrame(
    {'col1': [1, 1, 1, 1, 1, 1],
     'col2': [7, 2, 7, 7, 2, 2],
     'col3': [9, 4, 9, 3, 9, 5]}
)

df.with_columns(
    json = pl.struct("col1", "col2").map_elements(json.dumps)
)

# shape: (6, 4)
# ┌──────┬──────┬──────┬────────────────────────┐
# │ col1 ┆ col2 ┆ col3 ┆ json                   │
# │ ---  ┆ ---  ┆ ---  ┆ ---                    │
# │ i64  ┆ i64  ┆ i64  ┆ str                    │
# ╞══════╪══════╪══════╪════════════════════════╡
# │ 1    ┆ 7    ┆ 9    ┆ {"col1": 1, "col2": 7} │
# │ 1    ┆ 2    ┆ 4    ┆ {"col1": 1, "col2": 2} │
# │ 1    ┆ 7    ┆ 9    ┆ {"col1": 1, "col2": 7} │
# │ 1    ┆ 7    ┆ 3    ┆ {"col1": 1, "col2": 7} │
# │ 1    ┆ 2    ┆ 9    ┆ {"col1": 1, "col2": 2} │
# │ 1    ┆ 2    ┆ 5    ┆ {"col1": 1, "col2": 2} │
# └──────┴──────┴──────┴────────────────────────┘
```

**Comment by cmdlineluser** [comment]
[`.str.json_extract()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.json_extract.html#polars.Expr.str.json_extract)

**Comment by amplifinn-admin** [comment]
After extract expected output is:
┌──────┬──────┐
 │ col1 ┆ col2 │
 │ ---  ┆ ---  │
 │ i64  ┆ i64  │
╞══════╪══════╡
 │ 1    ┆ 7    │
 │ 1    ┆ 2    │
 │ 1    ┆ 7    │
 │ 1    ┆ 7    │
│ 1    ┆ 2    │
│ 1    ┆ 2    │
└──────┴──────┘
