### ISSUE TITLE
Drop duplicates

### ISSUE THREAD

**Issue by JoHNNyB92** [pola-rs/polars#1260]
Hello once again :)

I have written a code that in some point drop duplicates from dataframes. With the same dataframes the pandas return different number of rows compared to polars. 

df = df.drop_duplicates()
Pandas -> (195, 3)
Polars-> (10815, 3)

Attached you may find the dataframe:
[example_drop.csv](https://github.com/pola-rs/polars/files/7075654/example_drop.csv)

**Comment by ritchie46** [comment]
Are you sure?

```python
df = pl.read_csv("example_drop.csv")
print(df.shape)
print(df.drop_duplicates().shape)
```

```
(13475, 4)
(195, 4)
```

**Comment by JoHNNyB92** [comment]
It seems that maybe i have done something wrong. If i observe something strange again i will post it here :D Thanks again :D

**Comment by ztsweet** [comment]
@ritchie46 I came across the same mistake. the data is online and involves the Intranet of the company. i am sorry that i cannot provide reference data set. This operation with polars=0.12.15. The test data set is about 20,000 rows and 32 columns, and there are many null values involved in the data,The data types involved are  polars.datatypes.Datetime,
 polars.datatypes.Float64, polars.datatypes.Int64,polars.datatypes.Utf8

**Comment by ritchie46** [comment]
> @ritchie46 I came across the same mistake. the data is online and involves the Intranet of the company. i am sorry that i cannot provide reference data set. This operation with polars=0.12.15. The test data set is about 20,000 rows and 32 columns, and there are many null values involved in the data,The data types involved are polars.datatypes.Datetime, polars.datatypes.Float64, polars.datatypes.Int64,polars.datatypes.Utf8

If I cannot reproduce it I cannot fix it. Could you add a MWE?

**Comment by ztsweet** [comment]
@ritchie46 I emailed you the test data
