### ISSUE TITLE
Segmentation error in Docker using M1 Pro after installing polars

### ISSUE THREAD

**Issue by LeOndaz** [pola-rs/polars#12608]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I've installed polars on Docker-compose (3 containers) and all of them exit with the same logs

The API instance is using python3.9 slim buster with some env
```
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv" \
    POETRY_VERSION=1.2.2
```

### Log output

```shell
celerybeat_1    | <jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
celerybeat_1    | <jemalloc>: (This is the expected behaviour if you are running under QEMU)
celerybeat_1    | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
celerybeat_1    | bash: line 1:    12 Segmentation fault      poetry run celery -A api beat -l info --pidfile=''
```

### Issue description

Installing polars on M1 Pro inside docker causes the logs

### Expected behavior

Work?

### Installed versions

<details>
```
0.19.15
```
</details>

**Comment by alexander-beedie** [comment]
Could you provide the requested output for `show_versions`?
"Latest" will be different depending on when we see or look at the issue...  ;)

**Comment by LeOndaz** [comment]
> @LeOndaz: Could you provide the requested output for `show_versions`? "Latest" will be different depending on when we see or look at the issue; if your issue is something introduced recently that can make a meaningful difference as to how easy it is track down  ;)

Done, manually, not the original output cause as mentioned, I can't run polars

**Comment by stinodego** [comment]
This is a known issue. I'm not an expert on this, but we have seen this reported before. Virtualization on Mac M1 has some issues and does not offer the CPU optimalizations that Polars requires.

You can install `polars-lts-cpu` instead of `polars`, which should work.
