### ISSUE TITLE
Python crashes on rolling computation with string data (Windows)

### ISSUE THREAD

**Issue by Elvynzs** [pola-rs/polars#12628]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
ser = pl.Series(["Some String A"]*1500 + [None]*500 + ["Some String B"]*1500)
roll_ser = ser.to_frame().with_row_count(name="row_nr").rolling(pl.col("row_nr").cast(int), period="1000i")
a = roll_ser.agg(
    n_na=pl.concat_list(pl.exclude("row_nr")).flatten().is_null().sum(),
)
```

### Log output

```shell
N/A ?
```

### Issue description

I encountered the bug on a more complex scenario, and the reproducible example is what I got after spending ~1 hour trying to make a minimal reproducible example.

Here are a few notes that may help reproduce the bug :

* Reducing the length of any repeating element by enough will make the crash disappear
* Reducing the window size by enough will also make the crash disappear
* Using short enough strings will make the crash disappear
* **The same example did not crash through WSL.**
* On my machine, for a given crashing input, it will crash 100% of the time.
* On top of crashing Python, it can crash the task manager, and I think it also disconnected wi-fi twice (??).
* On my initial example, Python crashed after showing "memory allocation of XXXXX bytes failed".
  * Using the reproducible example, Python crashes silently without this message appearing.

### Expected behavior

N/A (It should not crash)

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.5.3
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.0.0
pyarrow:             11.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
If it helps with elimination, I cannot reproduce this on macOS.

**Comment by Elvynzs** [comment]
Using the given code snippet, I have successfully reproduced the crash on two separate laptops running Windows with slightly different python environments. So this seems to be an issue with the memory management on Windows.

**Comment by PierreAttard** [comment]
I had the same issue on Windows, but it works on WSL2.

**Comment by Elvynzs** [comment]
The example now works fine on the latest polars versions, I am closing this issue
