### ISSUE TITLE
Display struct dtypes using Python dictionary syntax

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12620]
### Description

This is how struct dtypes are displayed now:
```python
>>> pl.DataFrame({'a': {'i': 1, 's': 'foo'}}).dtypes[0]
Struct([Field('i', Int64), Field('s', Utf8)])
```

What if instead, they displayed as:

```python
>>> pl.DataFrame({'a': {'i': 1, 's': 'foo'}}).dtypes[0]
Struct({'i': pl.Int64, 's': pl.Utf8})
```
Much cleaner, no? 

After all, polars already recognizes the dictionary syntax:

```python
>>> pl.DataFrame({'a': {'i': 1, 's': 'foo'}}).dtypes[0] == pl.Struct({'i': pl.Int64, 's': pl.Utf8})
True
```

**Comment by ion-elgreco** [comment]
Would be more readable and ideally configured in the config.

**Comment by stinodego** [comment]
Honestly, I am not sure why the `Field` class exists at all. `Struct` should just accept a schema input just like the `DataFrame` constructor and many other functions :thinking:

**Comment by alexander-beedie** [comment]
> Honestly, I am not sure why the `Field` class exists at all. `Struct` should just accept a schema input just like the `DataFrame` constructor and many other functions 🤔

`Struct` _does_ accept a schema dict ;)  

Internally `Field` is probably required for (at least) hashing (a dict of name/type isn't hashable). Still, we don't really need to expose it. Cleaning up the `repr` is a good move 👌
