### ISSUE TITLE
The column created by with_row_count() should be called "row_count", not "row_nr"

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12624]
### Description

The column created by with_row_count() should be called "row_count", not "row_nr", for consistency with the function name.

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/12420#issuecomment-1809861488 may be relevant.

> or both should be renamed to `row_number`

**Comment by stinodego** [comment]
It will probably become `row_number`. Will pick this up as part of https://github.com/pola-rs/polars/issues/12420

**Comment by alexander-beedie** [comment]
> It will probably become `row_number`. Will pick this up as part of #12420

Yup, this would be best; matches the SQL equivalent window function 👍
