### ISSUE TITLE
`df.with_columns(pl.all().sum())` should return a DataFrame of length 1, not len(df)

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12639]
### Description

`with_columns()` automatically broadcasts its result back to the original length of the DataFrame, even when using `pl.all()`. This leads to differing behavior between `select()` and `with_columns()` that some might find surprising:

```
>>> pl.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]}).select(pl.all().sum())
 a  b
 6  15
shape: (1, 2)
>>> pl.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]}).with_columns(pl.all().sum())
 a  b
 6  15
 6  15
 6  15
```

Shouldn't these both return a DataFrame of length 1?

**Comment by cmdlineluser** [comment]
I thought it was implied that `.with_columns()` cannot modify the length of its input?

(Perhaps this is worth mentioning in the docs?)

**Comment by stinodego** [comment]
This is intended. We can definitely do a better job of explaining broadcasting in our user guide though. If you'd like to make an issue for improving the docs on broadcasting I'd accept it.
