### ISSUE TITLE
`pl.from_dicts` ignores tzinfo in input Python `datetime` objects

### ISSUE THREAD

**Issue by lizeyan** [pola-rs/polars#12638]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime
import polars as pl
item = {'create_time': datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=datetime.timezone.utc)}
display(pl.from_dict(item))
display(pl.from_dict(item).item())
display(pl.from_dicts([item]))
display(pl.from_dicts([item]).item())
```

Actual output:
```
shape: (1, 1)
┌────────────────────────────────┐
│ create_time                    │
│ ---                            │
│ datetime[μs, UTC]              │
╞════════════════════════════════╡
│ 2023-11-22 14:27:59.173645 UTC │
└────────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
shape: (1, 1)
┌────────────────────────────┐
│ create_time                │
│ ---                        │
│ datetime[μs]               │
╞════════════════════════════╡
│ 2023-11-22 14:27:59.173645 │
└────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645)
```

Expected output:
```
shape: (1, 1)
┌────────────────────────────────┐
│ create_time                    │
│ ---                            │
│ datetime[μs, UTC]              │
╞════════════════════════════════╡
│ 2023-11-22 14:27:59.173645 UTC │
└────────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
shape: (1, 1)
┌────────────────────────────────┐
│ create_time                    │
│ ---                            │
│ datetime[μs, UTC]              │
╞════════════════════════════════╡
│ 2023-11-22 14:27:59.173645 UTC │
└────────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
```

### Log output

```shell
No log output
```

### Issue description

`pl.from_dicts` will ignore the tzinfo information in the input data. Just like `pandas.DataFrame.from_records`:
```
In [7]: import datetime
   ...: import polars as pl
   ...: import pandas as pd
   ...: item = {'create_time': datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=datetime.timezone.utc)}
   ...: pd.DataFrame.from_records([item])
Out[7]:
                       create_time
0 2023-11-22 14:27:59.173645+00:00
```

### Expected behavior

Dataframe constructed through pl.from_dicts should retain the timezone information from the input data.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.11.4 (main, Jul 31 2023, 11:37:30) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.9
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.17
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by lizeyan** [comment]
The problem seems lies in schema inference:
```python
In [5]: import datetime
   ...: import polars as pl
   ...: item = {'create_time': datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=datetime.timezone.utc)}
   ...: display(pl.from_dict(item))
   ...: display(pl.from_dict(item).item())
   ...: display(pl.from_dicts([item], schema={'create_time': pl.Datetime(time_zone='UTC')}))
   ...: display(pl.from_dicts([item], schema={'create_time': pl.Datetime(time_zone='UTC')}).item())
shape: (1, 1)
┌────────────────────────────────┐
│ create_time                    │
│ ---                            │
│ datetime[μs, UTC]              │
╞════════════════════════════════╡
│ 2023-11-22 14:27:59.173645 UTC │
└────────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
shape: (1, 1)
┌────────────────────────────────┐
│ create_time                    │
│ ---                            │
│ datetime[μs, UTC]              │
╞════════════════════════════════╡
│ 2023-11-22 14:27:59.173645 UTC │
└────────────────────────────────┘
datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
```

**Comment by cmdlineluser** [comment]
It looks like `.from_dicts()` just passes it directly to the DataFrame constructor.

https://github.com/pola-rs/polars/blob/e17cea3788e0752898b6a96fd234a6aba07b6344/py-polars/polars/convert.py#L171

```python
pl.DataFrame(item)
# shape: (1, 1)
# ┌────────────────────────────────┐
# │ create_time                    │
# │ ---                            │
# │ datetime[μs, UTC]              │
# ╞════════════════════════════════╡
# │ 2023-11-22 14:27:59.173645 UTC │
# └────────────────────────────────┘
```
```python
pl.DataFrame([item])
# shape: (1, 1)
# ┌────────────────────────────┐
# │ create_time                │
# │ ---                        │
# │ datetime[μs]               │ # <- NO Timezone
# ╞════════════════════════════╡
# │ 2023-11-22 14:27:59.173645 │
# └────────────────────────────┘
```

**Comment by lizeyan** [comment]
> **[Update]:** It seems the `DataFrame()` issue was reported in #12151
> 
> 
> It looks like `.from_dicts()` just passes it directly to the DataFrame constructor.
> 
> https://github.com/pola-rs/polars/blob/e17cea3788e0752898b6a96fd234a6aba07b6344/py-polars/polars/convert.py#L171
> 
> ```python
> pl.DataFrame(item)
> # shape: (1, 1)
> # ┌────────────────────────────────┐
> # │ create_time                    │
> # │ ---                            │
> # │ datetime[μs, UTC]              │
> # ╞════════════════════════════════╡
> # │ 2023-11-22 14:27:59.173645 UTC │
> # └────────────────────────────────┘
> ```
> 
> ```python
> pl.DataFrame([item])
> # shape: (1, 1)
> # ┌────────────────────────────┐
> # │ create_time                │
> # │ ---                        │
> # │ datetime[μs]               │ # <- NO Timezone
> # ╞════════════════════════════╡
> # │ 2023-11-22 14:27:59.173645 │
> # └────────────────────────────┘
> ```

Yes. So I think that the problem seems lies in schema inference.
https://github.com/pola-rs/polars/issues/12638#issuecomment-1823775938

**Comment by lizeyan** [comment]
Thank

> **[Update]:** It seems the `DataFrame()` issue was reported in #12151
> 
> 
> It looks like `.from_dicts()` just passes it directly to the DataFrame constructor.
> 
> https://github.com/pola-rs/polars/blob/e17cea3788e0752898b6a96fd234a6aba07b6344/py-polars/polars/convert.py#L171
> 
> ```python
> pl.DataFrame(item)
> # shape: (1, 1)
> # ┌────────────────────────────────┐
> # │ create_time                    │
> # │ ---                            │
> # │ datetime[μs, UTC]              │
> # ╞════════════════════════════════╡
> # │ 2023-11-22 14:27:59.173645 UTC │
> # └────────────────────────────────┘
> ```
> 
> ```python
> pl.DataFrame([item])
> # shape: (1, 1)
> # ┌────────────────────────────┐
> # │ create_time                │
> # │ ---                        │
> # │ datetime[μs]               │ # <- NO Timezone
> # ╞════════════════════════════╡
> # │ 2023-11-22 14:27:59.173645 │
> # └────────────────────────────┘
> ```

Yes, you are right. Seems this is a duplicated issue.
