### ISSUE TITLE
Segfault in `set_intersection`

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#12634]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# Only on linux-64
df = pl.DataFrame({"42": [42] * 1_000_000})
X.select(pl.col("42").list.set_intersection([]))).to_pandas()
```

### Issue description

Crash when using `set_intersection`

### Expected behavior

No crash

### Installed versions

Any Polars >= 0.19.10 (did not check older) on Linux-64

**Comment by jonashaag** [comment]
Maybe related crash

```py
pickle.load(open("repro2.pkl", "rb")).select(pl.col("42").list.set_intersection([]))
```

[repro.zip](https://github.com/pola-rs/polars/files/13444366/repro.zip)

**Comment by ritchie46** [comment]
Can reproduce. Will fix it.
