### ISSUE TITLE
DataFrame is iterable, but breaks expectations (just like pandas)

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#12630]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Here's something which, for the longest time, has annoyed me about pandas:
- `len(df)`
- `len([x for x in df])`

don't match.

Polars has inherited this
```python
In [6]: df = pl.DataFrame({'a': [1,1,2], 'b': [4,5,6]})

In [7]: len(df)
Out[7]: 3

In [8]: len([x for x in df])
Out[8]: 2
```

### Issue description

I think the above breaks the expectations of newcomers who are used to the concept of iterables, but aren't used to pandas' oddities

### Expected behavior

I don't know yet, just wanted to open the issue for now

But if both `len(df)` and `len([x for x in df])` are valid, I think the UX would be better if they matched, especially for users who are experienced programmers but not used to pandas

EDIT
----
A suggestion I have is
- `DataFrame.__iter__` raises
- `DataFrame.iter_columns()` iterates over columns

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.1
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             12.0.1
pydantic:            2.0.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by ritchie46** [comment]
This doesn't make much sense to compare them like this IMO.

`df.len()` returns the height. 

`[col for col in df]` iterates over columns. If we would iterate over rows it would be different. 

Maybe iteration should be explicit in its direction?

**Comment by Wainberg** [comment]
You could imagine a scenario where `for row in df` returns each row as a tuple of Python objects, like [df.iter_rows()](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.iter_rows.html), and you would need to write `for row in df.columns` to iterate over the columns. Personally I'd say iterating over the columns is much more common, so I like the current behavior. Plus, it matches pandas :)

**Comment by MarcoGorelli** [comment]
> Personally I'd say iterating over the columns is much more common

True, but wouldn't you usually use `pl.all()`? Just out of interest, what do you iterate over columns for?

> it matches pandas :)

kinda - in pandas, it iterates over column names, whereas in Polars it iterates over the columns themselves:
```python
In [25]: [i for i in df]
Out[25]:
[shape: (3,)
 Series: 'a' [i64]
 [
        1
        1
        2
 ],
 shape: (3,)
 Series: 'b' [i64]
 [
        4
        5
        6
 ]]

In [26]: [i for i in df.to_pandas()]
Out[26]: ['a', 'b']
```

I'm not suggesting to iterate over rows (that would be worse)

But a solution I would suggest is:
- `DataFrame.__iter__` raises
- `DataFrame.iter_columns()` iterates over columns

**Comment by MarcoGorelli** [comment]
> it's not that usefu

exactly :) I'd suggest breaking with pandas here, and just having `iter_columns` (horizontal analogue to the already-existing `iter_rows`)

> if column_name in df

Right, that's arguably another oddity. The following raises instead of returning `True`:
```python
In [68]: [i for i in df][0] in df
---------------------------------------------------------------------------
TypeError: the truth value of a Series is ambiguous
```
, as `DataFrame.__iter__` is over `Series` but `__contains__` checks column names

**Comment by ritchie46** [comment]
@MarcoGorelli I am open to making it more explicit. Can you make a PR?

**Comment by Wainberg** [comment]
Iteration isn't something you need to do very often in polars, but it is nice to be able to think of a DataFrame as a dictionary-like object (mapping column names to columns) from time to time. 

I quite like how in pandas:
- `df.items()` is an iterator over (column name, column) pairs, analogous to `dictionary.items()` which iterates over (key, value) pairs
- `for column in df` iterates over the colum names, analogous to `for key in dictionary` which iterates over the keys

So, I would advocate for DataFrame iteration to iterate over the columns, not just to be consistent with pandas but also to be consistent with Python dictionaries.

**Comment by MarcoGorelli** [comment]
Are you sure it'd be consistent with Python dictionaries? Because there, the `len([i for i in x]) == len(x)` equality holds (as it does in every Python object I'm aware of except for pandas and Polars DataFrames - anyone know of any other exceptions?)

```python
In [8]: dct = {'a': 1, 'b': 2, 'c': 3}

In [9]: len([i for i in dct])
Out[9]: 3

In [10]: len(dct)
Out[10]: 3
```

**Comment by Wainberg** [comment]
I'd argue that the inconsistency isn't in iteration, so much as in what `len()` means! :)

**Comment by stinodego** [comment]
> I'd argue that the inconsistency isn't in iteration, so much as in what `len()` means! :)

I agree with this sentiment.

Implementing an explicit `iter_columns` is a good idea regardless.

In Rust, a DataFrame is just a Vec of Series. So iteration is done over columns. 
Implementing `__iter__` is just a convenient way for users to use Python syntax to do the same.

The problem is with `len(df)` returning the `height` when it should return the `width`.

**Comment by MarcoGorelli** [comment]
> The issue here is with len(df) returning the height when it should return the width 

Yeah I wish that was still an option, it's what R does
```R
> df <- data.frame (first_column  = c("value_1", "value_2", "value3"),
                  second_column = c("value_1", "value_2", "value3")
                  )
> length(df)
[1] 2
```
but in Python DS everyone's too used to the dataframe's length being the number of rows, way too disruptive to change unfortunately

Maybe I'm the only one bothered by `len(list(df)) != len(df)`, but whatever, I'll learn to live with it 😄 

Updating then, thanks all for inputs

**Comment by mcrumiller** [comment]
Chiming in, a dataframe isn't a matrix, it's a collection of columns. Basic iteration should definitely be over columns. Coming from pandas, I'd expect [s for s in df] to be a list of `pl.Series` object. It's definitely not as useful in polars due to expression syntax, but column iteration makes the most sense to me.

I agree `len(df)` = height is confusing, but that's just the standard. Who knows why--the length of a room usually refers to the longer of the two dimensions, and in a dataframe there are usually more rows than columns. But `width` and `height` are much more straightforwad.

**Comment by MarcoGorelli** [comment]
> Coming from pandas, I'd expect [s for s in df] to be a list of pl.Series object

in pandas it would be a list of column names, not a list of Series (thus adding to the confusion)
```python
In [1]: df = pd.DataFrame({'a': [1, 2]})

In [2]: [s for s in df]
Out[2]: ['a']
```
