### ISSUE TITLE
Statistics no longer used to prune reads when using `over` against parquet table

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#12637]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
#This is completely skips using statistics and ends up downloading all files
ldf = pl.scan_parquet(S3_PATH, storage_options=storage_options)
ldf.with_columns((pl.col("numeric_column") * 2).alias("test").over(pl.col("group_by_id"))).filter(pl.col("group_by_id") == 5).collect(streaming=True) # streaming vs non-streaming has the same result
# runs in 15s

#Which manages to prune all the files
ldf = pl.scan_parquet(S3_PATH, storage_options=storage_options)
ldf.with_columns((pl.col("numeric_column") * 2).alias("test")).filter(pl.col("group_by_id") == 5).collect(streaming=True)
# runs in 1s

#The dataframes come out equal, but the former scans all the files vs the latter which only scans filters with `group_by_id == 5` in them.
```

### Log output

```shell
POLARS PREFETCH_SIZE: 128
querying metadata of 128/203 files...
reading of 128/203 file...
POLARS ROW_GROUP PREFETCH_SIZE: 128
POLARS ROW_GROUP PREFETCH_SIZE: 128
...

```

### Issue description

n/a

### Expected behavior

Statistics should still prune all the files where possible

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Linux-5.4.259-180.361.x86_64-x86_64-with-glibc2.26
Python:              3.11.5 (main, Aug 31 2023, 23:10:05) [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)]

----Optional dependencies----
adbc_driver_sqlite:  0.6.0
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.10.1
fsspec:              2023.6.0
gevent:              23.9.1
matplotlib:          3.7.2
numpy:               1.24.4
openpyxl:            <not installed>
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            2.3.0
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by datenzauberai** [comment]
See https://github.com/pola-rs/polars/issues/11678

**Comment by ritchie46** [comment]
It is exactly similar to what @datenzauberai says. We should allow the predicate to be pushed down if the predicate refers to the group key.

**Comment by datenzauberai** [comment]
> @datenzauberai do you know what Ritchie meant by value?

It's a delicate optimization, because you have to make sure to only reorder operations in such a way, that the result stays the same. Imagine the following:

`df.group_by("country").agg(pl.col("sales").sum()).filter(pl.col("sales").gt(0))`

You must not push that filter down before the aggregation, because the aggregation manipulates a value it depends on.

In a complex query it can be tricky to decide if a filter can be pushed down or not.

**Comment by datenzauberai** [comment]
It depends on what is left of the `over(x, y)` statement, but in general: yes, it can be optimised in theory. Practically it might not be that easy to add the optimisation.
