### ISSUE TITLE
Allow for selecting all struct columns via the column selectors when omitting the struct schema.

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#12650]
### Description

The current column selectors API is... strict. It requires the full schema of a struct to select a struct column by dtype

```python
df = pl.DataFrame({'x': [{'A':1, 'B':2}]})

# Correct way to select this struct column
df.select(cs.by_dtype(pl.Struct([pl.Field('A', pl.Int64), pl.Field('B', pl.Int64)])))

```

I think there should be some way to select any struct.

In practice I think one or both of the following should select all struct columns:

```python
df.select(cs.by_dtype(pl.Struct())) # Struct with no fields

df.select(cs.by_dtype(pl.Struct)) # un-instantiated Struct DataTypeClass
```

**Comment by cmdlineluser** [comment]
I think this may already be on the TODO list: #11067

**Comment by mkleinbort-ic** [comment]
Agreed, this is a duplicate of #11067
