### ISSUE TITLE
Initializing a list column with a numpy 2D-array takes too long

### ISSUE THREAD

**Issue by stfdxv** [pola-rs/polars#12669]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np

a = np.arange(10_000_000).reshape(-1, 1)  # instant
print(a)
df = pl.DataFrame({"a": a})  # about a minute
print(df)
```

### Log output

```shell
No error
```

### Issue description

Creating a numpy 2D-array takes a few milliseconds on my machine.
But initializing a polars dataframe's column with this array takes more then a minute.

### Expected behavior

Should be instant.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Not sure what the difference is, but this is is also instant:
```python
pl.from_numpy(a, schema="a").with_columns(pl.col("a").reshape((-1, 1)))
```

**Comment by alexander-beedie** [comment]
Yup; we seem to have one optimised codepath and one _really_ naive one - I'll see about combining them so we only use the fast-path 😅

**Comment by alexander-beedie** [comment]
FYI: fixed in `0.19.17` - should be _dramatically_ faster👌

**Comment by stfdxv** [comment]
@alexander-beedie thanks! I really appreciate your work.
Now the bad news. There is another unlucky case, which takes about a minute on my laptop.
```python
# polars>=0.19.16,<=0.19.17
import polars as pl
import numpy as np

# shape (-1,2) looks like the worst one
a = np.arange(1_000_000_000).reshape(-1, 2)  # about 1 second
print(a)
df = pl.DataFrame({"a": a})  # about 1 minute
print(df)
```
I can open a new issue if needed.

**Comment by alexander-beedie** [comment]
> I can open a new issue if needed.

That would be best, thanks; easier to track since this one is already closed 👍
