### ISSUE TITLE
Serious Bug: `null` inside `when`/`then` evauates to `True`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12665]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "val": [1, 2, 3, 4],
        "threshold": [4, None, None, 1],
    }
)

df.with_columns(
    comparison=pl.col("val") > pl.col("threshold"),
    when=pl.when(pl.col("val") > pl.col("threshold"))
    .then(1)
    .otherwise(0),
)
shape: (4, 4)
┌─────┬───────────┬────────────┬──────┐
│ val ┆ threshold ┆ comparison ┆ when │
│ --- ┆ ---       ┆ ---        ┆ ---  │
│ i64 ┆ i64       ┆ bool       ┆ i32  │
╞═════╪═══════════╪════════════╪══════╡
│ 1   ┆ 4         ┆ false      ┆ 0    │
│ 2   ┆ null      ┆ null       ┆ 1    │ <<<<<<<<<<<<<<<<<<<<<<< should be 0
│ 3   ┆ null      ┆ null       ┆ 1    │ <<<<<<<<<<<<<<<<<<<<<<< should be 0
│ 4   ┆ 1         ┆ true       ┆ 1    │ 
└─────┴───────────┴────────────┴──────┘

df.filter(
    pl.col("val") > pl.col("threshold"),
)
shape: (1, 2)
┌─────┬───────────┐
│ val ┆ threshold │
│ --- ┆ ---       │
│ i64 ┆ i64       │
╞═════╪═══════════╡
│ 4   ┆ 1         │
└─────┴───────────┘
```

### Issue description

`when` evaluating to `null` should **NOT** execute the `then` block.
`null` should be treated as `False` just like when filtering in the example above.

Unfortunately just found this in a production workflow when rewriting polars to pyspark for databricks deployment and found out results were off by a lot 🤣 😒 

### Expected behavior

Only `True` result should trigger `then` evaluation in `when` block
`null` should evaluate to `False` and **NOT** trigger `then` 

### Installed versions

<details>

```
0.19.15
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report, I think I agree with your expected output

**Comment by ritchie46** [comment]
fix coming up.
