### ISSUE TITLE
Add a "prefix_tuple" method to column functions

### ISSUE THREAD

**Issue by paddymul** [pola-rs/polars#12662]
#### Describe your feature request

I want a feature `prefix_tuple` that acts like `prefix` but makes the column name instead of a string.

So instead of `F.all().null_count().prefix("null_count:")` which results in a column names of `null_count:a` `null_count:b`
I would like
`F.all().null_count().prefix_tuple("null_count")` 
which results in a column names of `('null_count', 'a')` `('null_count', 'b')`

This could also be a keyword argument to prefix`.prefix('null_count', tuple=True)`

As a writer of a generic library - Buckaroo that aims to deal with any DataFrame.  I have code that does the equivalent of pandas `stack`/`unstack`.  Currently I split column names resulting from on `:` which feels hacky.  I could come up with more and more elaborate escaping splitting sequences, but that is a banddaid.

**Comment by mkleinbort-ic** [comment]
Polars does not support non-string column names:

```python
pl.DataFrame(
    {
        ('A','B'):[1]
    }
)


>>> TypeError: Series name must be a string
```

**Comment by mkleinbort-ic** [comment]
If you want to fake a tuple-like column name I recommend `.name.map`

```python
pl.DataFrame(
    {'A':[1,2]}
).with_columns(
    pl.all().name.map(lambda x: f'("null_count", "{x}")')
)

# shape: (2, 2)
# ┌─────┬─────────────────────┐
# │ A   ┆ ("null_count", "A") │
# │ --- ┆ ---                 │
# │ i64 ┆ i64                 │
# ╞═════╪═════════════════════╡
# │ 1   ┆ 1                   │
# │ 2   ┆ 2                   │
# └─────┴─────────────────────
```

**Comment by alexander-beedie** [comment]
Looks like a good approach; to better-handle some edge cases with embedded quotes, I'd suggest a minor modification, having the `map` expression construct an _actual_ tuple from which you can take the `str`: 

`pl.all().name.map( lambda x: str(('null_count', x)) )`

**Comment by paddymul** [comment]
I thought I had managed to construct a polars dataframe with actual tuple column names, but apparently I fooled myself.  At this point I will use JSON for the column names,  more reliable then calling eval.

**Comment by alexander-beedie** [comment]
> I thought I had managed to construct a polars dataframe with actual tuple column names, but apparently I fooled myself. At this point I will use JSON for the column names, more reliable then calling eval.

Sounds like a plan; let us know as & when anything else comes up  ;)
