### ISSUE TITLE
`read_database_uri` parameters

### ISSUE THREAD

**Issue by bmarcj** [pola-rs/polars#12661]
### Description

The `read_database` supports sql parametrs, allowing for defending against sql injection attacks when the query involves external data. 

`read_database_url` does not have this argument, but has significantly improved performance by making use of adbc or connectorx. Would it be possible to add this functionality?

**Comment by alexander-beedie** [comment]
Unfortunately not at the moment, as it would rely on `connectorx` implementing this feature, and currently they have not. I'd suggest raising it as a feature request with them, because once it exists there we could certainly take advantage of it.

Looks like you can follow-up on this thread on their GitHub repo: https://github.com/sfu-db/connector-x/issues/208

**Comment by bmarcj** [comment]
Thanks for the response. 

While I agree about connector-x, I was thinking of the adbc driver. Does the adbc driver does support parameter binding?

**Comment by alexander-beedie** [comment]
> While I agree about `connectorx`, I was thinking of the `adbc` driver. Does the `adbc` driver does support parameter binding?

Only partially; apparently it works consistently when binding values for _inserts_ (which isn't useful for querying), but on the query level it looks to be hit or miss (for instance, it's [not](https://github.com/apache/arrow-adbc/issues/1144) supported for Snowflake). What backend are you looking at?

**Comment by bmarcj** [comment]
Ah, I guess we're at the bleeding edge here. Hopefully given time the situation will change.

Many thanks for the detailed response!

**Comment by alexander-beedie** [comment]
> Ah, I guess we're at the bleeding edge here. Hopefully given time the situation will change.

Indeed!

> Many thanks for the detailed response!

No problem; as & when the situation changes I'll be more than happy to make the update ;)
