### ISSUE TITLE
Wrong/inconsistent results for `polars.corr` introduced by py-polars v0.19.16

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#12681]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import pandas as pd

df = pl.DataFrame({"a": [1.0] * 71, "b": [-1.1, 2.2] * 30 + [3.3] * 11})

df.select(pl.corr("a", "b"))[0, 0]
np.corrcoef(df["a"].to_numpy(), df["b"].to_numpy())[0, 1]
```

### Log output

```shell
# polars v0.19.16
-inf

# numpy
nan

# polars < v0.19.16
nan
```

### Issue description

The results are inconsistent anymore with Numpy and previous Polars versions as well.

### Expected behavior

The result should be `nan` for polars v0.19.16.

### Installed versions

<details>

```
v0.19.16
```

</details>

**Comment by ritchie46** [comment]
@orlp can you take this one?

**Comment by orlp** [comment]
Oops, I guess it's already fixed now. @ritchie46
