### ISSUE TITLE
rolling_mean / rolling_std give NAN unexpectedly

### ISSUE THREAD

**Issue by Unnamed-1408** [pola-rs/polars#12682]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# load minimum reproducible data
test = pl.read_csv('data.csv', separator=",")
# casting to Float64
test = test.select(pl.all().cast(pl.Float64))
# print the result
test.select(pl.all().rolling_mean(2))
```

### Log output

```shell
>>> test.select(pl.all().rolling_mean(2))
shape: (1_600, 1)
┌──────┐
│ data │
│ ---  │
│ f64  │
╞══════╡
│ null │
│ null │
│ null │
│ null │
│ …    │
│ NaN  │
│ NaN  │
│ NaN  │
│ NaN  │
└──────┘
```

### Issue description

The `rolling_mean` and `rolling_std` gives NAN unexpectedly. The csv file can be found [here](https://github.com/pola-rs/polars/files/13464756/data.csv). The 10 last rows of this file is not NAN at all, but it still gives NAN.
The 10 last rows of data

```
>>> test.tail(10)
shape: (10, 1)
┌────────────┐
│ data       │
│ ---        │
│ f64        │
╞════════════╡
│ -54.220762 │
│ 0.039191   │
│ 16.128451  │
│ 66.690626  │
│ …          │
│ 132.856056 │
│ -59.429643 │
│ 55.074115  │
│ 0.0119     │
└────────────┘
```

### Expected behavior

Get correct results

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Linux-5.15.0-88-generic-x86_64-with-glibc2.17
Python:              3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0]
```

</details>

**Comment by c-peters** [comment]
FYI 

The error comes from the `-inf` on line 1499.

If I run `test.tail(102).select(pl.all().rolling_mean(2))` everything works fine, but `test.tail(103).select(pl.all().rolling_mean(2))` does not. Somehow there is a bug with `-inf` carrying over to the other windows...

An easier minimal reproducible example would be
```
df = pl.DataFrame(pl.Series("col",["-inf","5","5"]).cast(pl.Float64))
df.select(pl.col("col").rolling_mean(2))
shape: (3, 1)
┌──────┐
│ col  │
│ ---  │
│ f64  │
╞══════╡
│ null │
│ -inf │
│ NaN  │
└──────┘
```
