### ISSUE TITLE
Add a "report not working example" button to the examples in the documentation

### ISSUE THREAD

**Issue by Jupitersbay** [pola-rs/polars#12693]
### Description

Hi Richie,

could you please add a button to simply report not-working-examples in the documentary? This could be a cheap way to keep the documentation clean all the time. 

Here is an example of a not-working-script:
https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.cum_sum_horizontal.html#polars.cum_sum_horizontal

Greetz,
Marlon

**Comment by MarcoGorelli** [comment]
hi @Jupitersbay 

these examples are checked in CI and do in fact work if you have the latest version
```python
In [150]: df = pl.DataFrame(
     ...:     {
     ...:         "a": [1, 8, 3],
     ...:         "b": [4, 5, None],
     ...:         "c": ["x", "y", "z"],
     ...:     }
     ...: )
     ...: df.with_columns(pl.cum_sum_horizontal("a", "b"))
Out[150]:
shape: (3, 4)
┌─────┬──────┬─────┬───────────┐
│ a   ┆ b    ┆ c   ┆ cum_sum   │
│ --- ┆ ---  ┆ --- ┆ ---       │
│ i64 ┆ i64  ┆ str ┆ struct[2] │
╞═════╪══════╪═════╪═══════════╡
│ 1   ┆ 4    ┆ x   ┆ {1,5}     │
│ 8   ┆ 5    ┆ y   ┆ {8,13}    │
│ 3   ┆ null ┆ z   ┆ {3,null}  │
└─────┴──────┴─────┴───────────┘
```

**Comment by Jupitersbay** [comment]
Wow! Must have been changed in the last week. Between 19.12 and 19.13. I am impressed!
Thank you for the info, Marco

**Comment by MarcoGorelli** [comment]
yup :) cool, closing then, but thanks for the report, chances to improve docs are always welcome!
