### ISSUE TITLE
Simple filter operation fails with pl.scan_parquet when any other column is Decimal

### ISSUE THREAD

**Issue by jkc1** [pola-rs/polars#12700]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.scan_parquet(
    [
        "s3://some-bucket/file1.snappy.parquet",
        "s3://some-bucket/file2.snappy.parquet",
    ],
    storage_options={
        "aws_access_key_id": "...",
        "aws_secret_key_id": "...",
        "aws_region": "...",
    }
).filter(
    pl.col("some_col") == 5  # type of some_col is pl.Int32
).collect()

```

### Log output

When I run this on v0.19.16 I get a panic with an error message that looks something like:

```shell
pyo3_runtime.PanicException: operator does not support primitive `Int128`
```

### Issue description

Unfortunately I can’t, share the file that causes this error, but I did check that it’s otherwise unremarkable (and worked just fine with `pl.read_parquet`).

I tried create a runnable example with [this dataset](https://registry.opendata.aws/aws-public-blockchain/), but I wasn’t able to figure out what invocation of `storage_options` I needed to pass in order to get uncredentialed reads to work (i.e. the equivalent of `--no-sign-request` with `awscli`). 

### Expected behavior

The code should filter and not panic

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by cmdlineluser** [comment]
Can you perhaps share the schema? 

```python
pl.scan_parquet(...).schema
```

Or even the just types if the column names are sensitive.

(This `Int128` error has come up previously (#12393) but it was with regards to the Decimal type.)

**Comment by jkc1** [comment]
Yeah I saw a separate decimal type [issue](https://github.com/pola-rs/polars/issues/12375#issuecomment-1815558851) a few days ago and thought that I was my problem, but it turns out it wasn't.

I'm 99% sure all of the columns in my dataset are i32 (or at least that's what df.schema reports when I use `pl.read_parquet` instead of `pl.scan_parquet`). I suppose it could be possible that they're decimal in the parquet files and some type inference is going on. Let me check and also see if I can come up with a MWE that at least creates the parquets.

**Comment by ritchie46** [comment]
Can you show the full stacktrace?

**Comment by jkc1** [comment]
Okay sorry - was having a hard time coming up with a MWE but just managed to get it - turns out this has nothing to do with S3 but _does_ have to do with Decimal types. See below for details:

Copy the code below into a file (e.g. `create_example_parquet.py`). Create a python environment with pyspark (I used 3.5.0 but any version in the 3.x.x series should work). Run it with `spark-submit create_example_parquet.py`.

```python
from decimal import Decimal
from pathlib import Path
from shutil import rmtree

from pyspark.sql import SparkSession
from pyspark.sql.types import IntegerType, DecimalType, StructType, StructField



spark = SparkSession.builder.getOrCreate()
spark.createDataFrame(
    [
        (10, Decimal(5)),
        (10, Decimal(4)),
        (10, Decimal(19)),
        (20, Decimal(7)),
        (30, Decimal(5))
    ],
    schema=StructType([
        StructField("a", IntegerType()),
        StructField("b", DecimalType())
    ])
).coalesce(1).write.parquet("spark_decimals")


with open(list(Path("spark_decimals").glob("*.parquet"))[0], "rb") as rf:
    with open("spark_decimals.parquet", "wb") as wf:
        wf.write(rf.read())

rmtree("spark_decimals")
```

The script creates a parquet file `spark_decimals.parquet` that's got a column of i32 and a column of `Decimal(precision=10, scale=0)`.

Then, in a separate env with just `polars==0.19.16`, this works (although it casts the decimal column to f64):
```python
import polars as pl
pl.read_parquet("spark_decimals.parquet").filter(pl.col("a") == 10)
```

but this fails:
```python
import polars as pl
pl.scan_parquet("spark_decimals.parquet").filter(pl.col("a") == 10).collect()
```

Here's the full stacktrace:

```python
thread '<unnamed>' panicked at crates/polars-parquet/src/arrow/read/statistics/mod.rs:162:47:
operator does not support primitive `Int128`
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 pl.scan_parquet("spark_decimals.parquet").filter(pl.col("a") == 10).collect()

File /opt/conda/envs/py310/lib/python3.10/site-packages/polars/utils/deprecation.py:100, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     95 @wraps(function)
     96 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     97     _rename_keyword_argument(
     98         old_name, new_name, kwargs, function.__name__, version
     99     )
--> 100     return function(*args, **kwargs)

File /opt/conda/envs/py310/lib/python3.10/site-packages/polars/lazyframe/frame.py:1788, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, _eager)
   1775     comm_subplan_elim = False
   1777 ldf = self._ldf.optimization_toggle(
   1778     type_coercion,
   1779     predicate_pushdown,
   (...)
   1786     _eager,
   1787 )
-> 1788 return wrap_df(ldf.collect())

PanicException: operator does not support primitive `Int128`
```

**Comment by jkc1** [comment]
Not sure that it's relevant, but note that I'm not filtering on the decimal column in the MWE, I'm filtering on the i32

**Comment by cmdlineluser** [comment]
So it looks like the same issue as before, but just with `.scan_parquet` involved.

```python
import polars as pl
import tempfile

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": ["6", "7", "8"],
    }
)

df = df.with_columns(pl.col("bar").cast(pl.Decimal))

f = tempfile.NamedTemporaryFile()
df.write_parquet(f.name)

f.seek(0)

# pl.read_parquet = OK
pl.scan_parquet(f.name).filter(foo = 2).collect()

# PanicException: operator does not support primitive `Int128`
```

**Comment by jkc1** [comment]
Ah, I tried to repro with the polars decimal type but couldn’t figure out how to get it to not cast to f64 on write. Your MWE is much clearer/simpler.

**Comment by ritchie46** [comment]
We need to write with statistics to trigger the bug:

```python
import polars as pl
import tempfile

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": ["6", "7", "8"],
    }
)

df = df.with_columns(pl.col("bar").cast(pl.Decimal))

f = tempfile.NamedTemporaryFile()
df.write_parquet(f.name, statistics=True)

f.seek(0)

# pl.read_parquet = OK
pl.scan_parquet(f.name).filter(foo = 2).collect()
```

Thanks for getting the simple MRE. :)

**Comment by cmdlineluser** [comment]
Ah, interesting.

It raises for me without writing statistics (but I'm stuck on an older version of pyarrow on this machine - it probably has something to do with this.)

Will use `statistics=True` for debugging in the future - thanks.
