### ISSUE TITLE
Ploting Charts

### ISSUE THREAD

**Issue by SandeshGowda-0094** [pola-rs/polars#12703]
### Description

I Think no description is needed for this request...
We all are working with data, sometimes we get bored seeing the number, sometimes we can't understand seeing just the numbers.

At the most least we need basic plots, if 3d is supported it would be `awesome`.
if someone starts to work on this feature eventually 3d will be supported in future, polars is a great library which makes the analysis simpler having support for plotting charts directly through Polars makes analysis more simpler

pretty please someone having expertise in polars and matplotlib or bokeh or plotly, start on this feature, even I will also try my best to contribute and get an opportunity to work on a feature for polars which will be world wide adopted by polarians.

**Comment by alexander-beedie** [comment]
FYI: you can already use Polars directly with most of those libraries ;)
This is a (relatively) recent development, but here are a few examples:

* https://www.rhosignal.com/posts/polars-seaborn/
* https://www.rhosignal.com/posts/polars-matplotlib-plotly/#plotly
* https://plotly.com/blog/polars-to-build-fast-dash-apps-for-large-datasets/

**Comment by SandeshGowda-0094** [comment]
My bad, I should have checked the documentations thoroughly, before raising feature request.
thanks, a lot.
and sorry for the trouble.
