### ISSUE TITLE
`min_periods` is not taken into account when `window_size` is a duration in all `rolling_` functions

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#12715]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

test = (
    pl.DataFrame(
        {
            "Date": [
                "1973-05-01",
                "1973-05-02",
                "1973-05-03",
            ],
            "value": [1, 2, 3],
        }
    )
    .with_columns(pl.col("Date").cast(pl.Date))
    .set_sorted("Date")
)

test

shape: (3, 2)
┌────────────┬───────┐
│ Date       ┆ value │
│ ---        ┆ ---   │
│ date       ┆ i64   │
╞════════════╪═══════╡
│ 1973-05-01 ┆ 1     │
│ 1973-05-02 ┆ 2     │
│ 1973-05-03 ┆ 3     │
└────────────┴───────┘

test.with_columns(
    with_index=pl.col("value").rolling_max(
        window_size=2, closed="both", min_periods=2, 
    ),
    with_time=pl.col("value").rolling_max(
        window_size="1d", by="Date", closed="both", min_periods=2
    ),
)

shape: (3, 4)
┌────────────┬───────┬────────────┬───────────┐
│ Date       ┆ value ┆ with_index ┆ with_time │
│ ---        ┆ ---   ┆ ---        ┆ ---       │
│ date       ┆ i64   ┆ i64        ┆ i64       │
╞════════════╪═══════╪════════════╪═══════════╡
│ 1973-05-01 ┆ 1     ┆ null       ┆ 1         │
│ 1973-05-02 ┆ 2     ┆ 2          ┆ 2         │
│ 1973-05-03 ┆ 3     ┆ 3          ┆ 3         │
└────────────┴───────┴────────────┴───────────┘
```

### Issue description

The columns `with_index` and `with_time` do not return the same values: it looks like `min_periods` is not taken into account when the `window_size` is a duration.

### Expected behavior

I would expect the columns `with_index` and `with_time` to be identical, but it looks like `min_periods` is ignored when `window_size` is a duration. The same behavior is observed with `rolling_quantile()`, `rolling_min()`, `rolling_sum()` and `rolling_mean()`.

If this is the expected behavior, then the documentation should be updated to say that `min_periods` is only applied when `window_size` is an integer.

If this is a bug, maybe this will be solved by #12049, I don't know.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.16
Index type:          UInt32 
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MariusMerkleQC** [comment]
Bump: I have encountered exactly the same problem, this would be great to fix!

**Comment by MarcoGorelli** [comment]
thanks for the report, will take a look

**Comment by MarcoGorelli** [comment]
Hi @MariusMerkleQC / @etiennebacher - could you describe your use case please?

I'd just like to figure out if the only use case for this is when you know you have evenly-spaced data, in which case I don't think need a temporal window at all (just `.rolling_max(window_size=2, closed="both", min_periods=2)` should be enough?)

Just double-checking there's actually a need for this, thanks 🙏

**Comment by MarcoGorelli** [comment]
Going to ask @dylan-lee94 as well

**Comment by MariusMerkleQC** [comment]
Good question!

Let's say I want to compute the rolling mean of the last 200 days. Then I would like this to work with the same code independent of whether your data is by second, minute, hourly, daily, or weekly. 

The same way of thinking goes for the minimum number of periods for which a value should exist: if I want data for at least 100 days to compute a rolling mean, this should work with the same code independent of whether your data is by second, minute, hourly, daily, or weekly.

Does that make sense?

**Comment by MarcoGorelli** [comment]
>  if I want data for at least 100 days

I don't know if this would do that, as `min_periods` would only ensure that have at least, say, 100 observations

But it seems useful anyway, there's a few linked issues, and it would mirror what pandas does

**Comment by dylan-lee94** [comment]
> Going to ask @dylan-lee94 as well

I'm using `polars.Expr.rolling_sum` for stock return calculations, in particular for computing 1 month trailing stock returns. Here `min_periods` ensures that the 1 month trailing return Null when there is not enough data available for the entire window size.

**Comment by fdetsch** [comment]
> Hi @MariusMerkleQC / @etiennebacher - could you describe your use case please?
> 
> I'd just like to figure out if the only use case for this is when you know you have evenly-spaced data, in which case I don't think need a temporal window at all (just `.rolling_max(window_size=2, closed="both", min_periods=2)` should be enough?)
> 
> Just double-checking there's actually a need for this, thanks 🙏

@MarcoGorelli Another use case would be predictive maintenance for irregular shop floor data. One swallow does usually not make a summer, so you need a certain amount of data in a time-based moving window before drawing any conclusions. 
Of course, one could concurrently monitor the rolling count of observations in the same time window and then reject other rolling metrics accordingly, but this just adds another layer of complexity when the same could also be achieved through setting `min_periods`.

**Comment by dylan-lee94** [comment]
@MarcoGorelli how would #13342 behave when `min_periods` is set to a dynamic temporal size? I am looking to compute 1 month trailing returns, where the first month should be set to `NULL`.

**Comment by MarcoGorelli** [comment]
`min_periods` takes an integer, not a temporal size - could you open a new issue with a reproducible example + expected output please?

**Comment by dylan-lee94** [comment]
> `min_periods` takes an integer, not a temporal size - could you open a new issue with a reproducible example + expected output please?

I just opened a new issue, #13566
