### ISSUE TITLE
Another segfault in `set_intersection`

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#12716]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"42": ["42"] * 500_000})
df.select(pl.col("42").list.set_intersection([]))
```

### Issue description

ref https://github.com/pola-rs/polars/issues/12634

### Expected behavior

No crash

### Installed versions

- linux-64
- pl 0.19.16

**Comment by orlp** [comment]
Can't reproduce on 0.19.17 on Apple M1.

**Comment by MarcoGorelli** [comment]
can reproduce on 0.19.17 on wsl2 (ubuntu)
```
In [1]: pl.__version__
Out[1]: '0.19.17'

In [2]: df = pl.DataFrame({"42": ["42"] * 500_000})
   ...: df.select(pl.col("42").list.set_intersection([]))
Segmentation fault
```

**Comment by cmdlineluser** [comment]
Here also:
```
Segmentation fault: 11
```
```
Polars:              0.19.16
Index type:          UInt32
Platform:            macOS-10.12.6-x86_64-i386-64bit
```
(Building 0.19.17 now)

**Comment by ritchie46** [comment]
Ah, right. I believe I only fixed primitive types. Can take this one a bit later.
