### ISSUE TITLE
Better support for string formating with `pl.format`

### ISSUE THREAD

**Issue by adaliaramon** [pola-rs/polars#12720]
### Description

As it stands, `pl.format` can be used for string formatting in expressions. However, it only supports replacing `{}` placeholders, with no further control of the formatting. I would like `pl.format` to ideally work like f-strings in Python, where I can, for example, round or zero-pad numbers. Currently, I have to resort to `map_elements` for more complex formatting.

**Comment by alexander-beedie** [comment]
Closing (as https://github.com/pola-rs/polars/issues/7133 is the existing issue for this) 👍
