### ISSUE TITLE
.replace can replace integers with strings but not strings with integers

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#12728]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": ["b","c"]})
df.select(pl.col("a").replace({"b":1,"c":2}))

```

### Log output

```shell
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ str  │
╞══════╡
│ null │
│ null │
└──────┘
```

### Issue description

This expression works for mapping an integer column to strings and used to work for strings to integers

### Expected behavior

shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ 1 │
│ 2 │
└──────┘

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             macOS-12.6.7-x86_64-i386-64bit
Python:               3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:54) [Clang 13.0.1 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           0.3.1
deltalake:            0.9.0
fsspec:               2023.5.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.1
pyarrow:              13.0.0
pydantic:             1.10.7
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.12
xlsx2csv:             0.8.1
xlsxwriter:           3.0.3```

</details>

**Comment by cmdlineluser** [comment]
Just for reference, with `.map_dict`:
```python
df.with_columns(replace=pl.col("a").map_dict({"b":1,"c":2}))
# shape: (2, 2)
# ┌─────┬─────────┐
# │ a   ┆ replace │
# │ --- ┆ ---     │
# │ str ┆ i64     │
# ╞═════╪═════════╡
# │ b   ┆ 1       │
# │ c   ┆ 2       │
# └─────┴─────────┘
```
(Is anybody else not seeing a deprecation warning with `.map_dict`?)

**Comment by stinodego** [comment]
For now you can pass `default=None` to preserve the behavior of `map_dict`. I'll look into this issue.

> (Is anybody else not seeing a deprecation warning with .map_dict?)

I am getting the warning - would be interested in a MRE if you have one, if you are not getting a warning it means our deprecation utils are flawed.

**Comment by cmdlineluser** [comment]
Thanks @braaannigan @stinodego - some sort of user error on my part.

`pl.__version__` was `0.19.17` so not entirely sure what was going on, but restarting a fresh environment I now get the warning.
