### ISSUE TITLE
from_pandas deletes named index info

### ISSUE THREAD

**Issue by paddymul** [pola-rs/polars#12727]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
named_index_df = pd.DataFrame({'a':[1,2,3]}, index=['foo', 'bar', 'baz'])
```
results in a single column polars dataframe.  The `['foo', 'bar', 'baz']` data is dropped.

<img width="546" alt="Screen Shot 2023-11-27 at 5 14 49 PM" src="https://github.com/pola-rs/polars/assets/40453/53471a3a-b204-4d9b-8625-a50ee6dd887e">

### Issue description

It's surprising behavior that data encoded in a pandas index is dropped by polars.  I realize polars doesn't support indexes, but it should be able to have a column named `index`

### Expected behavior

I wrote a quick convience function that does the right thing.
```python
def convert_named_index_df(df):
    pldf = pl.from_pandas(df)
    if type(df.index) == pd.core.indexes.base.Index:
        if pd.api.types.is_object_dtype(df.index):
            return pldf.with_columns(
                pl.Series(name="index", values=df.index.to_list())).select(['index'] + pldf.columns)
    return pdf
```
<img width="718" alt="Screen Shot 2023-11-27 at 5 15 21 PM" src="https://github.com/pola-rs/polars/assets/40453/f189947f-4906-4df2-b74e-13e413d8efed">

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.14
Index type:          UInt32
Platform:            macOS-11.7.4-arm64-arm-64bit
Python:              3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            1.10.9
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by mcrumiller** [comment]
As per #6847 from way back, you need to set `include_index=True`:

```python
import pandas as pd
import polars as pl

named_index_df = pd.DataFrame({"a": [1, 2, 3]}, index=["foo", "bar", "baz"])
df = pl.from_pandas(named_index_df, include_index=True)
print(df)
```
```
shape: (3, 2)
┌──────┬─────┐
│ None ┆ a   │
│ ---  ┆ --- │
│ str  ┆ i64 │
╞══════╪═════╡
│ foo  ┆ 1   │
│ bar  ┆ 2   │
│ baz  ┆ 3   │
└──────┴─────┘
```

**Comment by paddymul** [comment]
Sorry.  I looked at existing bug reports, but probably not enough documentation.
