### ISSUE TITLE
Got a regression from 0.19.15 -> 0.19.16 with scan_parquet

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#12729]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
A `scan_parquet` on my dataset now produces an error when collected.
```

### Log output

```shell
`polars.exceptions.ComputeError: not implemented: reading dictionaries of type (ByteArray, Utf8)` and it used to work fine before.
```

### Issue description

See log output

### Expected behavior

Should successfully read my data

### Installed versions

<details>

```
Broke when using 0.19.16 (but succeeded with 0.19.15)
```

</details>

**Comment by ritchie46** [comment]
Can you share me a file to reproduce this? We should be able to read this with another branch. E.g. with less code bloat.
