### ISSUE TITLE
Panic in CsvWriter on finish() with DataFrames containing 2D Series objects

### ISSUE THREAD

**Issue by taeh98** [pola-rs/polars#1273]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

None

#### What version of polars are you using?

polars = "0.14.7"

#### What operating system are you using polars on?

Ubuntu 20.04.2 LTS

#### Describe your bug.

I get a panic when calling finish() on a CsvWriter variable with a DataFrame variable when the DataFrame variable contains one or more Series variables which themselves hold Series variables as values (i.e. 2D Series variables - like a 2D array).

#### What are the steps to reproduce the behavior?

Reproduce with https://gist.github.com/taeh98/71e84a5b30f6fd38839a6d1126860116

#### What is the actual behavior?

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("column types must match schema types, expected List(Field { name: \"\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) but found LargeList(Field { name: \"item\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) at column index 1")', ........ /polars-core-0.14.8/src/frame/mod.rs:1700:72

stack backtrace:
... main.rs:36:5 (from above gist)
```

#### What is the expected behavior?

DataFrame object is written to the csv file

#### Notes

- The difference seems to be List vs LargeList (in arrow?)
- In the gist example, when you remove the values_series object from the DataFrame df the error goes away, so its presence definitely causes the error

**Comment by ritchie46** [comment]
Yes the arrow csv writer does not permit nested structures. I will see if I can add support for that.

**Comment by ritchie46** [comment]
I've been thinking about this, and I don't think this should be supported by the csv-writer. Polars should be able to make the round trip of anything it writes. Having nested data in a csv-files makes the parser a lot more complicated.

I also don't see any notion of nested types and how to handle them in [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180), which is as close as a standard for the csv file format I could find for csv files.

**Comment by taeh98** [comment]
> I've been thinking about this, and I don't think this should be supported by the csv-writer. Polars should be able to make the round trip of anything it writes. Having nested data in a csv-files makes the parser a lot more complicated.
> 
> I also don't see any notion of nested types and how to handle them in [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180), which is as close as a standard for the csv file format I could find for csv files.

Thanks for your reply.

It may not make sense to hold Series variables as values within another Series variable from the point of view of the relationships between data types, the semantics of what they are meant to represent, etc. You will definitely be able to judge that better than I.

I've been playing around with it for a little bit and as yet have been unable to find a way to create a 2D column/Series - even as a Series of slices, vectors, ChunkedArray variables, etc. Please could you confirm for me whether there is a way of achieving my desired functionality - a Series whose values are themselves arrays of some sort? In my opinion, It is definitely a useful or crucial feature (for instance recording repeated measurements in a scientific experiment) in some cases as well as [established functionality in pandas](https://stackoverflow.com/questions/38840319/put-a-2d-array-into-a-pandas-series). It may be the case that there is some way of achieving this I am not aware of. If this is the case, I think it would be useful to document how to create a "2D Series" for others who may have the same problem I did.

Thank you for your time and help.

**Comment by ritchie46** [comment]
>  Please could you confirm for me whether there is a way of achieving my desired functionality - a Series whose values are themselves arrays of some sort?

You could use the [list builder](https://pola-rs.github.io/polars/polars/chunked_array/builder/fn.get_list_builder.html) or do something like this:

```rust
let s0 = Series::new("a", &[1i64, 2, 3]);
let s1 = Series::new("b", &[1i64, 1, 1]);
let s2 = Series::new("c", &[2i64, 2, 2]);
// construct a new ListChunked for a slice of Series.
let list = Series::new("foo", &[s0, s1, s2]);
```

**Comment by taeh98** [comment]
> > Please could you confirm for me whether there is a way of achieving my desired functionality - a Series whose values are themselves arrays of some sort?
> 
> You could use the [list builder](https://pola-rs.github.io/polars/polars/chunked_array/builder/fn.get_list_builder.html) or do something like this:
> 
> ```rust
> let s0 = Series::new("a", &[1i64, 2, 3]);
> let s1 = Series::new("b", &[1i64, 1, 1]);
> let s2 = Series::new("c", &[2i64, 2, 2]);
> // construct a new ListChunked for a slice of Series.
> let list = Series::new("foo", &[s0, s1, s2]);
> ```

Thank you for your reply.

Would this not still create a Series whose values are themselves Series variables? I thought that was something you were opposed to?

I tried your code, and got this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("column types must match schema types, expected List(Field { name: \"\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) but found LargeList(Field { name: \"item\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) at column index 0")', /home/.../polars-core-0.14.8/src/frame/mod.rs:1700:72

```

This is the same error I had originally. It was thrown on the "CsvWriter::new(&mut output_file)" line. Here's the exact code I used:

```
use std::fs::File;

use polars::prelude::{CsvWriter, DataFrame, NamedFrom, SerWriter, Series};

fn main() {
    let s0 = Series::new("a", &[1i64, 2, 3]);
    let s1 = Series::new("b", &[1i64, 1, 1]);
    let s2 = Series::new("c", &[2i64, 2, 2]);
    // construct a new ListChunked for a slice of Series.
    let list = Series::new("foo", &[s0, s1, s2]);

    let df: DataFrame = DataFrame::new(vec![list]).unwrap();

    let mut output_file: File = File::create("out.csv").unwrap();

    CsvWriter::new(&mut output_file)
        .has_headers(true)
        .finish(&df)
        .unwrap();
}
```

**Comment by ritchie46** [comment]
> Would this not still create a Series whose values are themselves Series variables? I thought that was something you were opposed to?

I think there is some confusion here. I am not opposed to nested data structures, e.g. Arrays in `Series`. But I am opposed to writing those data structures to the csv format. 

IMO this should be written to a format that supports nested data. Think about `parquet` or `json`.

**Comment by taeh98** [comment]
> > Would this not still create a Series whose values are themselves Series variables? I thought that was something you were opposed to?
> 
> I think there is some confusion here. I am not opposed to nested data structures, e.g. Arrays in `Series`. But I am opposed to writing those data structures to the csv format.
> 
> IMO this should be written to a format that supports nested data. Think about `parquet` or `json`.

I've thought about what you said and I think you're right. I think with CSV files it doesn't actually make a tonne of sense to have arrays in a single cell, so I ended up separating out the single CSV I intended to make into multiple different ones so each cell is just a single value.

Thanks.

**Comment by ghuls** [comment]
Yesterday I whished this feature existed. had a usecase for this feature.

I found a way to do it with apply, cast to Utf8 and str_concat, but there might be a more efficient way of doing it.
```python
In [162]: df3.head(10)
Out[162]:
shape: (10, 2)
┌────────────┬─────────────────┐
│ num_motifs ┆ num_list        │
│ ---        ┆ ---             │
│ u32        ┆ list [i32]      │
╞════════════╪═════════════════╡
│ 62         ┆ [5, 6, ... 21]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 64         ┆ [6, 7, ... 30]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 11491      ┆ [-1, 5, ... 39] │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 389        ┆ [6, 7, ... 30]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2786       ┆ [24]            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 619        ┆ [7, 8, 9]       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 6921       ┆ [7, 8, ... 30]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 169        ┆ [5, 6, ... 14]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 688        ┆ [5, 6, ... 26]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 191        ┆ [5, 6, ... 12]  │
└────────────┴─────────────────┘

In [163]: df3.with_column(pl.col("num_list").apply(lambda x: x.cast(pl.Utf8).str_concat("|")).flatten().alias("list_stringyfied")).head(10)
Out[163]:
shape: (10, 3)
┌────────────┬─────────────────┬─────────────────────────────────────┐
│ num_motifs ┆ num_list        ┆ list_stringyfied                    │
│ ---        ┆ ---             ┆ ---                                 │
│ u32        ┆ list [i32]      ┆ str                                 │
╞════════════╪═════════════════╪═════════════════════════════════════╡
│ 62         ┆ [5, 6, ... 21]  ┆ 5|6|7|8|9|10|11|12|13|14|15|16|1... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 64         ┆ [6, 7, ... 30]  ┆ 6|7|8|9|10|11|12|14|15|17|18|19|... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 11491      ┆ [-1, 5, ... 39] ┆ -1|5|6|7|8|9|10|11|12|13|14|15|1... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 389        ┆ [6, 7, ... 30]  ┆ 6|7|8|9|10|11|12|13|14|15|16|17|... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2786       ┆ [24]            ┆ 24                                  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 619        ┆ [7, 8, 9]       ┆ 7|8|9                               │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 6921       ┆ [7, 8, ... 30]  ┆ 7|8|9|10|11|12|13|14|15|16|17|18... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 169        ┆ [5, 6, ... 14]  ┆ 5|6|7|8|9|10|11|12|13|14            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 688        ┆ [5, 6, ... 26]  ┆ 5|6|7|8|9|10|11|12|13|14|15|16|1... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 191        ┆ [5, 6, ... 12]  ┆ 5|6|7|8|9|10|11|12                  │
└────────────┴─────────────────┴─────────────────────────────────────┘

In [166]: print(df3.with_column(pl.col("num_list").apply(lambda x: x.cast(pl.Utf8).str_concat("|")).flatten().alias("list_stringyfied")).head(10).select(["num_motifs", "list_stringyfied"]).to_csv(sep="\t"))
num_motifs      list_stringyfied
62      5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|21
64      6|7|8|9|10|11|12|14|15|17|18|19|20|22|25|26|30
11491   -1|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|33|36|39
389     6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|24|25|27|29|30
2786    24
619     7|8|9
6921    7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30
169     5|6|7|8|9|10|11|12|13|14
688     5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|24|25|26
191     5|6|7|8|9|10|11|12
```

**Comment by zundertj** [comment]
Closing this issue, as the consensus seems to be that polars should not add this functionality, and workarounds, be it maybe not optimal performance, do exist.
