### ISSUE TITLE
Allow `.alias` to take a list of names to generate duplicate columns

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12749]
### Description

I have a common use-case where I require duplicate columns, and it's a bit cumbersome to have:

```python
df.with_columns(
    ...long expression
    .alias("a")
).with_columns(
    col("a").alias("b"),
    col("a").alias("c"),
)
```

A nice shorthand would be to create duplicate columns via a list in `alias`:

```python
df.with_columns(
    ...long expression
    .alias(["a", "b", "c"])
)
```

...or an additional `.aliases` (plural) for this case.

**Comment by Wainberg** [comment]
I always like doing something like `.with_columns(**{'a': col for col in ('b', 'c'})` in situations like this!

**Comment by mcrumiller** [comment]
@Wainberg same, but still requires an extra call to `with_columns` which I was hoping to avoid. Just for ergonomics.

**Comment by Wainberg** [comment]
You could also imagine
```
df.with_columns(
    ...long expression
    .duplicate(["a", "b", "c"])
)
```
to make it more explicit that you're duplicating the column.

**Comment by stinodego** [comment]
I don't think creating duplicate columns in this way is common enough to warrant specialized syntax like this.

Also, this is currently not trivial to implement.

**Comment by henryharbeck** [comment]
Found this from an SO link, so for anyone looking in the future...

This can be achieved in a single context with the walrus operator

```python
df = pl.DataFrame({"existing_col": ["a", "b", "c"]})

df.with_columns(
    a:=pl.lit(1).alias("a"),
    **{key: a for key in ("b", "c")},
)
# shape: (3, 4)
# ┌──────────────┬─────┬─────┬─────┐
# │ existing_col ┆ a   ┆ b   ┆ c   │
# │ ---          ┆ --- ┆ --- ┆ --- │
# │ str          ┆ i32 ┆ i32 ┆ i32 │
# ╞══════════════╪═════╪═════╪═════╡
# │ a            ┆ 1   ┆ 1   ┆ 1   │
# │ b            ┆ 1   ┆ 1   ┆ 1   │
# │ c            ┆ 1   ┆ 1   ┆ 1   │
# └──────────────┴─────┴─────┴─────┘
```

or just plain old variable assignment beforehand
```python
my_expr = pl.lit(1)

df.with_columns(**{key: my_expr for key in ("a", "b", "c")})
# same output
```
