### ISSUE TITLE
Add support for arrow timestamp type

### ISSUE THREAD

**Issue by kdkavanagh** [pola-rs/polars#1274]
Arrow has a type `pa.timestamp` with arbitrary precision, e.g `pa.timestamp('ns')`.   Currently Polars will convert to `date64(ms)`, which ends up being a lossy conversion.  I'm happy to add this support if you can point me in the right direction.   In the meantime, the workaround is to manually convert to int64.

```
>>> pa.array([1626704355052908971], pa.timestamp('ns')).cast(pa.int64())
<pyarrow.lib.Int64Array object at 0x7fff9f650948>
[
  1626704355052908971
]
>>> polars.Series(pa.array([1626704355052908971], pa.timestamp('ns'))).to_arrow().cast(pa.int64())
<pyarrow.lib.Int64Array object at 0x7fff9f650888>
[
  1626704355052
]
```

**Comment by ritchie46** [comment]
> Arrow has a type pa.timestamp with arbitrary precision, e.g pa.timestamp('ns'). Currently Polars will convert to date64(ms), which ends up being a lossy conversion. I'm happy to add this support if you can point me in the right direction. In the meantime, the workaround is to manually convert to int64.

This is correct. Eventually I also want to support arrow timestamp. But this would mean we need to add another datatype and date related utils for that dtype.

**Comment by zundertj** [comment]
I think #3609 has solved this?

**Comment by ritchie46** [comment]
Yes, this has been added indeed.
