### ISSUE TITLE
Some issues with local categorical merge functionality

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#12753]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Question 1
In the first example, we merge two different categorical encodings in a way that produces a warning:
```python
import polars as pl

df1 = pl.Series(name="x", values=["A", "B"], dtype=pl.Categorical).to_frame()
df2 = pl.Series(name="x", values=["B", "A"], dtype=pl.Categorical).to_frame()
pl.concat([df1, df2])
"""
UserWarning:
Local categoricals have different encodings, expensive re-encoding is done to perform this merge operation.
Consider using a StringCache or an Enum type if the categories are known in advance
"""
```
Is there a way to indicate to polars that I am deliberately merging categoricals, to avoid this warning?

### Question 2
In the second example, we attempt to do this merge under a StringCache, provoking an error:
```python
import polars as pl

df1 = pl.Series(name="x", values=["A", "B"], dtype=pl.Categorical).to_frame()
with pl.StringCache():
    df2 = pl.Series(name="x", values=["B", "A"], dtype=pl.Categorical).to_frame()
    pl.concat([df1, df2])
"""
StringCacheMismatchError: cannot compare categoricals coming from different sources,
consider setting a global StringCache.
"""
```
This is an artificial example, since I'm not using the StringCache for anything.
But maybe it should just do the categorical merge here, rather than raising an error?

### Issue description

See examples.

### Expected behavior

See examples.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             Linux-3.10.0-1160.99.1.el7.x86_64-x86_64-with-glibc2.17
Python:               3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  0.6.0
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.25.2
openpyxl:             3.1.2
pandas:               2.1.0
pyarrow:              13.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.16
xlsx2csv:             0.8.1
xlsxwriter:           3.1.2
```

</details>

**Comment by ritchie46** [comment]
> Is there a way to indicate to polars that I am deliberately merging categoricals, to avoid this warning?

You can silence this warning. @c-peters shall we rename it to a performance-warning? Or maybe even more specific, so users can target which warnings they silence.

>  But maybe it should just do the categorical merge here, rather than raising an error?

Why? You clearly set your string cache wrong. It should be set for both the categoricals. Merging rev-maps is very expensive and you don't want this to happen implicitly.

**Comment by mcrumiller** [comment]
Is there a new undocumented enum type, or is that a rust warning making its way through to python?

**Comment by c-peters** [comment]
Regarding question 1, I have made a PR to allow filtering specific warnings.
