### ISSUE TITLE
Import Polars exit code 132

### ISSUE THREAD

**Issue by gen-li** [pola-rs/polars#12754]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```

### Issue description

After I pip install polars and import polars as pl, I got the error "Process finished with exit code 132 (interrupted by signal 4: SIGILL)"

Can anyone help with it? Please Can anyone help with it? Please Can anyone help with it? Please

### Expected behavior

import polars as pl
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by gen-li** [comment]
I solve the issue temporarily by using `pip install polars-lts-cpu`

**Comment by ritchie46** [comment]
This is expected if you run on a relatively old CPU or you run under rosetta in mac. Polars is compiled with a feature flagged not supported by your CPU.

**Comment by ritchie46** [comment]
I will close this as it is not a bug.
