### ISSUE TITLE
`read_csv` whitespace bug at line start and number parsing inconsistencies (adopt pandas style)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12763]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd
from io import StringIO

DATA_STR = "both,leading,trailing,both2\n     X     ,     X,X     ,     X     "
DATA_NUM = "both,leading,trailing,both2\n     7     ,     7,7     ,     7     "

pl.read_csv(StringIO(DATA_STR))
pl.read_csv(StringIO(DATA_NUM))

pd.read_csv(StringIO(DATA_STR))
pd.read_csv(StringIO(DATA_NUM))
```

### Issue description

There is at least 1 bug and some unexpected behaviour regarding whitespace in csv files. (see also #10587 )

# BUG:

Leading whitespace is ignored the the start of a new line but respected anywhere after.

# Unexpected behaviour

Numbers with leading but no trailing whitespace are parsed as numbers.
Numbers with trailing whitespace are parsed as strings.

# Examples

### Polars

- `     X     ` (at start of the line) -> `X     ` BUG: only at start of the line leading whitespace is trimmed 💥 
- `     X` -> `     X` ✅ 
- `X     ` -> `X     ` ✅ 
- `     X     ` -> `     X     ` ✅ 

### Pandas

- `     X     ` (at start of the line) -> `     X     ` ✅ 
- `     X` -> `     X` ✅ 
- `X     ` -> `X     ` ✅ 
- `     X     ` -> `     X     ` ✅ 

### Polars

- `     7     ` -> `7     `  Why text? ❓ 
- `     7` -> 7 (i64) Why number? ❓ 
- `7     ` -> `7     ` Why text? ❓ 
- `     7     ` -> `     7     ` Why text? ❓ 

### Pandas

- `     7     ` -> 7 (i64) ✅ 
- `     7` -> 7 (i64) ✅ 
- `7     ` -> 7 (i64) ✅ 
- `     7     ` -> 7 (i64) ✅ 

### Expected behavior

Whitespace at the start of a new line should be respected and not trimmed. This is correct in all other columns.
Maybe add an `trim_whitespace` option to specify if whitespace should be trimmed or not (according to the non-official csv specs whitespace belongs to the format and should be respected)

numbers (ints/floats) should consistently be parsed correctly regardsless of leading/trailing whitespace.
Only parsing numbers with leading whitespace and returning strings for numbers with trailing whitespace is inconsistent and very unexpected as a user. Pandas does this very well.

### Installed versions

<details>

```
0.19.17
```

</details>

**Comment by ritchie46** [comment]
>     X    (at start of the line) -> X     BUG: only at start of the line leading whitespace is trimmed 💥

Fair enough.

But if whitespace should be respected, I think that answers your `why_text` question. Whitespace belongs to text data, not to numeric data.

**Comment by JulianCologne** [comment]
@ritchie46 thats for your fast responst.



> But if whitespace should be respected, I think that answers your `why_text` question. Whitespace belongs to text data, not to numeric data.

not really. It is inconsistent. 😕 
- `     7` -> 7 (number)
- `7     ` -> `7     ` (text with whitespace)

To be consistent it should either be
- `     7` -> `     7` (text with whitespace)
- `7     ` -> `7     ` (text with whitespace)

or
- `     7` -> 7 (number)
- `7     ` -> 7 (number)


Python example
```python
int('7'), int('     7'), int('7     '), int('     7     '),
# (7, 7, 7, 7)
```

**Comment by ritchie46** [comment]
What i mean is that if we will not trim whitespace. Any whitespace should go to a text column. Not to a number. That would make it consistent.

**Comment by JulianCologne** [comment]
> What i mean is that if we will not trim whitespace. Any whitespace should go to a text column. Not to a number. That would make it consistent.

yes, I agree!

That means that the current implementation is incorrect in the case of `     7` to parse it as 7 (number) instead of keeping whitespace and keeping it as `     7`, right? :)

**Comment by ritchie46** [comment]
Yes. The whitespace should be handled in post processing.

We might consider a trim whitespace option, but it shouldn't be default as that changes the data.
