### ISSUE TITLE
Specialized `convert_and_replace_timezone`

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#12761]
### Description

Let's say we have a dataframe with two columns. The current date in UTC and the local timezone. Currently it's not that easy to convert it first the local timezone and then replace the timezone with None without using pl.when.then with a filter.

```python
import polars as pl
from datetime import datetime
import pytz

df = pl.DataFrame({
    'id': [1,2],
    "date_col": [datetime(2020,10,10, tzinfo=pytz.UTC), datetime(2020,10,10, tzinfo=pytz.UTC)],
    'timezone': ['Europe/London', 'Africa/Kigali']
})

exprs =[
    pl.when(pl.col('timezone')==tz)
    .then(pl.col('date_col').dt.convert_time_zone(tz).dt.replace_time_zone(None))  
    for tz in ['Europe/London', 'Africa/Kigali']
    ]

df.with_columns(
    pl.coalesce(exprs)
)
```

It would be nice if we could do this in one go:

`df.select(local_date=pl.col('date_col').dt.convert_and_replace_timezone(convert=pl.col('timezone'), replace=None)`.

This way the end result is in one datetime and tz format but the intermediate step can hold different tz's.

@MarcoGorelli

**Comment by MarcoGorelli** [comment]
so starting from a tz-aware datetime, and a column of time zones `timezone`, you'd like to get the local datetime for each row according to the time zone in the `timezone` column

not sure about the name, but a useful way to do this does seem useful. I don't think there's currently any way to do it lazily

**Comment by ion-elgreco** [comment]
@MarcoGorelli correct!

Yeah this pl.when.then trick works only if you know the timezones that the data will contain ahead.

**Comment by ion-elgreco** [comment]
@MarcoGorelli ah nice one, then we go both directions. Alright, I will add the other one as well.

I still find naive not saying much imho then I think your naive_local is more clear than if we want to mention naive

**Comment by MarcoGorelli** [comment]
> I still find naive not saying much imho then I think your naive_local is more clear than if we want to mention naive

I think `to_local_datetime` is fine too, the comment was just to demonstrate the pair of functions

I'd suggest naming it like that if you prefer it, we can always do a final function name bikeshed before shipping it 😄

**Comment by ion-elgreco** [comment]
@MarcoGorelli is it okay to change the python expr naming only or should it be consistent across the rust and python API?

**Comment by stinodego** [comment]
I like the functionality this adds, but it also overlaps with the existing functionality, which can be confusing.

`to_naive(None) would be the same as `replace_time_zone(None)`. And `from_naive(None, tz)` would be the same as `replace_time_zone(tz)`.

With regards to naming, maybe it can be called `remove_time_zone`/`add_time_zone`. That makes it clear it's about time zones and that it the input/output will be tz-aware/tz-naive or vice versa. The additional time zone expression can me thought of as "according to this time zone". Also gels well with the existing methods.

**Comment by ion-elgreco** [comment]
@stinodego I would say that's a small overlap :) Both target different use cases

Regarding the naming, we are not only removing or adding a timezone. We rather do `convert` to TZ and then `replace` TZ with None, and the other way around.  Only saying remove or add doesn't make that entirely clear and could give different impressions of what it does.

 From all the options my preference would go to the `to/from_naive_local_datetime`

**Comment by stinodego** [comment]
@MarcoGorelli any input on the naming of these functions? I find it hard to decide. In your presentation at pydata, you made a crystal clear case for when to use `replace_time_zone` vs `convert_time zone`. I feel like adding these two new methods makes things a bit muddy.

I'd like to look at the 4 method names and know what they do immediately. Maybe they shouldn't be separate methods but parameters instead? I'm not sure. Input is appreciated.

**Comment by MarcoGorelli** [comment]
I'm honestly not sure - you're right that it's gone from "2 clear and distinct functions" to "4 functions with some overlap"

I'm _tempted_ to say that there two new ones could be in a Polars plugin instead, so that Polars only has the most commonly used time zone functions (and they can remain simple and clearly named), and the relatively less common case of converting from multiple time zones can be handled there?

Maybe I could rename `polars-business` to `polars-time-series-extras` and we put this in?

**Comment by ion-elgreco** [comment]
@MarcoGorelli happy to migrate it to your plugin

**Comment by stinodego** [comment]
Thanks guys. I'll be closing this then!
