### ISSUE TITLE
Can we replace `hashbrown` with the standard library `HashMap`?

### ISSUE THREAD

**Issue by sanmai-NL** [pola-rs/polars#12805]
### Description

I checked [the `hashbrown` docs](https://github.com/rust-lang/hashbrown#readme) and looked at the Polars source code, and didn't notice any particular reason to keep using `hashbrown` instead of `HashMap` from the standard library.

> Since Rust 1.36, this is now the HashMap implementation for the Rust standard library. However you may still want to use this crate instead since it works in environments without std, such as embedded systems and kernels.

The latter seems to be outside the application domain of Polars, no? Rust 1.36 was released around 4 July 2019, so that seems to be fine especially given the current dependency on modern Rust `nightly-2023-11-15`.

**Comment by ritchie46** [comment]
I will close this as at this point in time we cannot.

**Comment by sanmai-NL** [comment]
@ritchie46 Currently, Polars depends on the `hashbrown` features `ahash`, `inline-more`, `allocator-api2` and `rayon` as well as on Rust nightly.  `hashbrown` itself depends on unstable features `core_intrinsics`, `dropck_eyepatch`, `min_specialization`, `extend_one`, `allocator_api`, `slice_ptr_get`, `maybe_uninit_array_assume_init`, `strict_provenance`. Being able to swap out this dependency for the standard library and one unstable feature instead of multiple seems like good option for me. 🙂
