### ISSUE TITLE
pl.write_database with adbc not writing to a specified schema

### ISSUE THREAD

**Issue by StuffbyYuki** [pola-rs/polars#12803]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# my dataframe
df = pl.DataFrame({'brand': ['Volvo', 'BMW', 'Toyota'], 'model': ['p1800', 'M1', 'Celica'], 'year': [1968, 1978, 1975]})

# this results in writing the dataframe to the public schema
df.write_database(table_name="sandbox.cars_output", connection=uri, engine="adbc", if_exists='replace')
```

### Issue description

When writing a dataframe to a Postgres database with `pl.write_database` using adbc, the specified schema don't get reflected in the result. It writes to the public schema instead. And the whole string I specify in the `table_name` parameter becomes the table name created in the public schema. But with sqlalchemy, it writes to the specified scheme with no problems. 

<img width="361" alt="image" src="https://github.com/pola-rs/polars/assets/43386707/23728617-bcc7-4684-a473-e82852d08e48">

### Expected behavior

I expect the dataframe written to the specified schema, "sandbox", instead of the "public".

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.11.3 (main, Apr 15 2023, 22:27:28) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  0.7.0
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            0.12.0
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.1.1
pyarrow:              12.0.0
pydantic:             2.4.2
pyiceberg:            0.5.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.22
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
This is probably an issue for adbc rather than polars.

That said I believe you can do what you need with

```
df.write_database(table_name="cars_output", connection=f"{uri}?currentSchema=sandbox", engine="adbc", if_exists='replace')
```

Citing [this](https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc) for that hint.

If your uri already has parameters then change my ? to a & alternatively you could use a library to make it more robust like [this](https://stackoverflow.com/questions/2506379/add-params-to-given-url-in-python)

**Comment by deanm0000** [comment]
@stinodego might be a close, not sure if polars wants to take this on or leave to adbc and possibly connectorx or leave to user to augment their conn string.

**Comment by StuffbyYuki** [comment]
@alexander-beedie Updated both versions and it works like a charm. Thanks guys!
