### ISSUE TITLE
parquet dict encoded panic

### ISSUE THREAD

**Issue by lucky6qi** [pola-rs/polars#1281]
I got error message
`RuntimeError: Any(ArrowError(InvalidArgumentError("all columns in a record batch must have the same length")))`
when I do groupby for col1 with na:
`df.groupby(["col1"]).agg([pl.col("col2").count()]).collect()
`
Is it intended? 
Only solution is to to fill_null for col1 ?

Or is there any plan to handle na like spark?

**Comment by ritchie46** [comment]
Hey @lucky6qi? Have you got a minimal example to reproduce this? I don't understand where the error related to an arrow `RecordBatch` comes frome? Do you scan parquet data?

To answer your question, it does not matter that you have null values in a groupby operation.

**Comment by lucky6qi** [comment]
> Hey @lucky6qi? Have you got a minimal example to reproduce this? I don't understand where the error related to an arrow `RecordBatch` comes frome? Do you scan parquet data?
> 
> To answer your question, it does not matter that you have null values in a groupby operation.

I found that if I use scan_parquet, it will end up error. But if I change to read_parquet, it is fine. So the behaviour in lazy/eager mode is different.

**Comment by lucky6qi** [comment]
> ```python
> pl.read_parquet(..., use_pyarrow=False)
> ```

It gives another error during reading:
RuntimeError: Any(ArrowError(NotYetImplemented("Decoding \"Plain\"-encoded, dictionary-encoded optional V1 pages is not yet implemented for Binary")))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-7279137a7e0e> in <module>
      1 import polars as pl
----> 2 pl_df = pl.read_parquet("20210810app_data.snappy.parquet",use_pyarrow=False)

~/repos/cortex_eds_automated_ranking/env/lib/python3.6/site-packages/polars/io.py in read_parquet(source, use_pyarrow, stop_after_n_rows, memory_map, columns, storage_options, **kwargs)
    485             )
    486         return pl.DataFrame.read_parquet(
--> 487             source_prep, stop_after_n_rows=stop_after_n_rows
    488         )
    489 

~/env/lib/python3.6/site-packages/polars/eager/frame.py in read_parquet(file, stop_after_n_rows)
    573         """
    574         self = DataFrame.__new__(DataFrame)
--> 575         self._df = PyDataFrame.read_parquet(file, stop_after_n_rows)
    576         return self
    577 

RuntimeError: Any(ArrowError(NotYetImplemented("Decoding \"Plain\"-encoded, dictionary-encoded optional V1 pages is not yet implemented for Binary")))

**Comment by jorgecarleitao** [comment]
In arrow2 this has just been fixed this morning xD

**Comment by ritchie46** [comment]
> In arrow2 this has just been fixed this morning xD

Haha.. You heard it @lucky6qi, next release. :smile:

**Comment by ritchie46** [comment]
added and released.
