### ISSUE TITLE
`write_parquet` writes invalid Parquet (multiple dictionaries for a single column)

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#12811]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

File from https://github.com/jonashaag/tmp

```python
import pyarrow.parquet as pq
pl.read_parquet("pl-12811.parquet").write_parquet("/tmp/blah")
pq.read_table("/tmp/blah")
# => Column can not have more than one dictionary.
```

### Issue description

Polars seems to sometimes use more than one dictionary per column when writing a Parquet file.

IIUC that's [not allowed](https://github.com/apache/parquet-format?tab=readme-ov-file#column-chunks):

> At most one dictionary page can be placed in a column chunk.

### Expected behavior

Should write Parquets that are compatible with PyArrow

### Installed versions

0.19.18
Linux-64

**Comment by deanm0000** [comment]
Duplicate of https://github.com/pola-rs/polars/issues/12801

**Comment by jonashaag** [comment]
Thank you!
