### ISSUE TITLE
Support reading whitespace-delimited tabular data

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12829]
### Description

As encouraged by @stinodego, I'd like to request support for whitespace-delimited tabular data, either via a `delim_whitespace=True` argument to `pl.read_csv()` (like pandas) or more generally by supporting a regex `separator` (also like pandas). This is a common use-case particularly in bioinformatics, and isn't straight-forward to work around. It could use a separate code path from the main CSV reader, to avoid a performance penalty for regular CSV reading.

**Comment by ritchie46** [comment]
This has be requested earlier, and my answer remains the same. 

We will only support single byte delimiters. Anything more exotic is not something that polars will do. Things as regex parsing delimiters is something that better fits a dedicated tool for that specific file format.

If your whitespace is single byte. Polars can parse it by setting it as a seperater, delimiter.
