### ISSUE TITLE
Remove lifetime from CategoricalChunkedBuilder

### ISSUE THREAD

**Issue by leifu1128** [pola-rs/polars#12820]
### Description

The lifetime association with appended values is quite cumbersome to work with, and it does not seem necessary. Is there a reason you wouldn't want to store ```String``` in ```StrHashLocal``` instead? 

Also unrelated, there is a typo for this method:

pub fn ~~exits~~ exists(&self, s: &str) -> bool {
        let h = self.local_mapping.hasher().hash_one(s);
        let key = StrHashLocal::new(s, h);
        self.local_mapping.contains_key(&key)
    }

**Comment by orlp** [comment]
> Is there a reason you wouldn't want to store String in StrHashLocal instead?

Yes, this would result in a separate allocation for each string.

**Comment by c-peters** [comment]
I think we can do without and not store the string

**Comment by leifu1128** [comment]
You can for example use Rc, or cache and re-use the same String allocation:

```rust
struct Categorical<'a> {
    cached: BTreeSet<Rc<str>>,
    inner: CategoricalChunkedBuilder<'a>,
    len: usize,
}

impl Categorical<'_> {
    fn push(&mut self, entry: &str) -> Result<()> {
        if !self.cached.contains(entry) {
            self.cached.insert(Rc::from(entry));
        }
        let rc = self.cached.get(entry).unwrap();
        let p = Rc::as_ptr(rc);
        self.inner.append_value(unsafe { &*p });
        self.len += 1;
        Ok(())
    }
}
