### ISSUE TITLE
Doc/website bug: Doc version picker wrongly shows `0.20 (stable)`

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars#12838]
### Description

In the py-polars docs, it shows `0.20 (stable)` in the file picker, but there doesn't seem to be such a version yet:
<img width="1619" alt="image" src="https://github.com/pola-rs/polars/assets/25161793/9eb0749a-8eb2-4338-b78d-eed479a0294a">
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_ndjson.html

When I click on that version I get redirected to 0.19

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_ndjson.html

**Comment by stinodego** [comment]
I was afraid this might happen 😕 will revert #12509 for now

**Comment by corneliusroemer** [comment]
Glad I spotted a real issue :) Keep up the good work!
