### ISSUE TITLE
Discussion: can the selectors API be merged into the expressions API?

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12851]
### Description

The functionality in the selectors API is enormously useful! At the same time, having selectors as a separate concept from expressions, and in a separate namespace that's recommended to have its own import, can be confusing for new users. 

Can the selectors API be merged into the expressions API? Selector functions duplicate what's already available using just expressions, so it would be easy to move these functions to the global namespace and have them return expressions instead of selectors:

- `cs.all()`, `cs.first()` and `cs.last()` duplicate `pl.all()`, `pl.first()` and `pl.last()`. 
- Selection by dtype (`cs.by_dtype()`, `cs.categorical()`, `cs.date()`, `cs.datetime()`, `cs.duration()`, `cs.float()`, `cs.integer()`, `cs.numeric()`, `cs.string()`, `cs.temporal()`, `cs.time()`) can already be done with `pl.col()`. For instance, `df.select(cs.string())` is equivalent to `df.select(pl.col(pl.Utf8))`, and `cs.numeric()` is equivalent to `df.select(pl.col(pl.NUMERIC_DTYPES))`. 
- Selection by name (`cs.by_name()`, `cs.contains()`, `cs.ends_with()`, `cs.matches()`, `cs.starts_with()`) can also be done with `pl.col()`. `cs.by_name(a, b)` can be directly substituted with `pl.col(a, b)`, `cs.contains(regex)` with `df.select(pl.col(f'^.*{regex}.*$'))`, etc.

The one part that's exclusive to selectors is set operations. Selectors allow you to distinguish between set operations (`&`, `|`, `~`, `^`, `-`) on columns and bitwise/arithmetic operations on the underlying columns (by converting the selector to an expression via `as_expr()`). 

Set operations could be implemented for expressions either by using boolean operators (`and`, `or`, `not`), or dedicated expression methods (`set_intersection`, `set_union`, `set_difference`, `set_symmetric_difference`, `set_negation`). 

So instead of `df.select(cs.temporal() & cs.matches("foo"))`, you could do `df.select(pl.temporal() and pl.matches("foo"))` or `df.select(pl.temporal().set_intersection(pl.matches("foo")))`.

Personally I'm a fan of using boolean operators, because they're consise and not already implemented for expressions. 

Very interested to hear folks' thoughts! cc: @stinodego

**Comment by alexander-beedie** [comment]
You've already spotted some of the properties that make `selectors` distinct from expressions (such as set ops), but there are a few more; for example, there are functions that can specifically take (and then expand) a selector that _cannot_ take arbitrary expressions (and they are typed accordingly as we can distinguish between the two - we couldn't do this if selectors were blurred into expressions).

Then there is the simple clarity that comes from having selectors and selector-specific functions live in one simple `cs` ("column selector") namespace - I think there are around 20 such functions at the moment, and there will be more in the near future (as I still haven't gotten around to adding support for compound/nested dtypes). If you want to select something, you immediately know where to look. Interspersing them in amongst regular expressions loses that, and it's not like the top-level namespace isn't already quite full  ;))

**Comment by Wainberg** [comment]
@cmdlineluser I love this! `pl.col.numeric()`, `pl.col.matches('foo|bar')` and so on are concise and extremely clear as to their intent. 

You could also keep `pl.col` as an object rather than a module. Either way, the difficult part is that you'd have to recognize that `pl.col.matches` is an expression referring to the `matches` column, whereas `pl.col.matches('foo|bar')` is a function.

@alexander-beedie in my proposal, you'd get consistent set op behavior with `and`, `or` and `not`. `&`, `|`, `^`, and `~` would always do bitwise operations and `-` would always do arithmetic. Seems clearer than bitwise operators doing one thing for selectors and another for expressions. 

I also completely disagree that "If you want to select something, you immediately know where to look." As I argued in my original post, there are currently two ways of doing everything: one way with `pl.col`, another way with selectors.

**Comment by mcrumiller** [comment]
I wasn't aware of the `col.a` behavior to reference column `a`. This sounds a lot like how pandas allows `df.a` to refer to `df["a"]` although it's discouraged. Should we not discourage this practice as well? IMO it lends itself to ambiguity.

**Comment by Wainberg** [comment]
@mcrumiller that was implemented in 0.19.2 to universal acclaim ;) https://github.com/pola-rs/polars/pull/10874

**Comment by Wainberg** [comment]
So, here's my modest proposal: support `and`, `or` and `not` for set logic on expressions, and deprecate selectors.

1. Remove `cs.all()`, `cs.first()` and `cs.last()` as duplicates of `pl.all()`, `pl.first()` and `pl.last()`.
2. Remove `cs.by_dtype()` and `cs.by_name()` as duplicates of `pl.col()`.
3. Move `cs.categorical()`, `cs.date()`, `cs.datetime()`, `cs.duration()`, `cs.float()`, `cs.integer()`, `cs.numeric()`, `cs.string()`, `cs.temporal()`, and `cs.time()` to the global polars namespace as `pl.categorical()`, `pl.date()`, `pl.datetime()`, `pl.duration()`, `pl.float()`, `pl.integer()`, `pl.numeric()`, `pl.string()`, `pl.temporal()`, and `pl.time()`. Make these functions return expressions.
4. Move `cs.contains()`, `cs.ends_with()`, `cs.matches()`, and `cs.starts_with()` to the global polars namespace as `pl.contains()`, `pl.ends_with()`, `pl.matches()`, and `pl.starts_with()`. Make these functions return expressions.
5. Deprecate regular expression matching with `pl.col()` (e.g. `pl.col(f'^{regex}$')`) as a duplicate of `pl.matches()`.
6. Move `cs.expand_selector()` to the global polars namespace as `pl.expand_expression()`, and have it take an expression instead of a selector as the second argument. 

This would preserve all the core functionality currently provided by selectors, while reducing API duplication and substantially simplifying column selection. The distinction between expressions and selectors is one of the most confusing parts of polars, and removing selectors would help make the library more accessible for new learners.

**Comment by Wainberg** [comment]
@kszlim The `pl.col` API isn't particularly constrained. Everything you can do with selectors, you can already do with expressions - even set operations!

Your example doesn't use any of the special powers of selectors. You could get the same result with `int_cols = pl.col(pl.INTEGER_DTYPES)` or `int_cols = pl.col(pl.Int64)`. Selector set operations are, for example, `df.select(cs.temporal() & cs.matches("foo"))`. 

The fact that you're confused about what's selector-specific behavior and what's expression behavior kind of proves my point that it's confusing to have two different APIs that do essentially the same thing. They should be merged into one somehow!

**Comment by stinodego** [comment]
I agree with Alex that selectors are not expressions, they should be treated differently.

I don't like the existing API of having to import selectors separately and have them available under `cs`. But I don't know what a better solution would be.

The solutions proposed in this issue don't sound like the way to go to me.

**Comment by Wainberg** [comment]
@alexander-beedie I realize I never responded to your points from earlier:

> You've already spotted some of the properties that make selectors distinct from expressions (such as set ops), but there are a few more; for example, there are functions that can specifically take (and then expand) a selector that cannot take arbitrary expressions (and they are typed accordingly as we can distinguish between the two and provide the function with accurate typing via SelectorType - which we couldn't do if selectors were blurred into generic expressions).

`cs.expand_selector()` seems pretty niche, and doesn't seem like a sufficient reason on its own to keep selectors.

> Selectors also have distinct __hash__ and __invert__ behaviour, and the binary/set operators can behave differently (but consistently) on selectors because we know that they are selectors rather than vanilla expressions. For example:
> df.select(cs.float() | cs.datetime())  # select float or datetime columns
> df.select(pl.col(pl.FLOAT_DTYPES) | pl.col(pl.DATETIME_DTYPES))  # invalid operation error
> As soon as you see the cs namespace you can be assured that you'll get consistent set op behaviour. These operations don't necesarily translate to generic expressions, and if selectors/expressions were mixed together in one namespace it may not be immediately obvious which behaviour you're going to get.

You're proving my point - the fact that `|` does something different for selectors and expressions is part of what makes selectors so confusing! If selectors were merged into expressions, `and`/`or`/`not` could provide the set logic, and `&`/`|`/`~`|`-` wouldn't do different things depending on whether it's an expression or selector.

> Then there is the simple clarity that comes from having selectors and selector-specific functions live in one simple cs ("column selector") namespace - I think there are around 20 such functions at the moment, and there will be more in the near future (as I still haven't gotten around to adding support for compound/nested dtypes). If you want to select something, you immediately know where to look. 

That's the thing - if you want to select something, you don't know where to look, because right now we've got two parallel APIs for doing the same thing: `pl.col` and `pl.selectors`. These two APIs almost fully duplicate each other, as I went over in [my original post](https://github.com/pola-rs/polars/issues/12851#issue-2021453785).

Would love to hear @ritchie46's thoughts on my proposal [above](https://github.com/pola-rs/polars/issues/12851#issuecomment-1837216868) :)

**Comment by cmdlineluser** [comment]
<blockquote>

So instead of 

```python
df.select(cs.temporal() & cs.matches("foo"))
```

you could do

```python
df.select(pl.temporal() and pl.matches("foo"))  
# or
df.select(pl.temporal().set_intersection(pl.matches("foo")))
```

</blockquote>

What about `.col()` itself accepting selectors?

```python
df.select(pl.col(pl.temporal() & pl.matches("foo")))
```

I think having a top-level `pl.matches` would be confusing though as people would try to use it as an expression.

It seems like the "selector functionality" still needs its own namespace.

**Comment by Wainberg** [comment]
> I think having a top-level `pl.matches` would be confusing though as people would try to use it as an expression.

No no, you're misunderstanding. `pl.matches` would _be_ an expression. There would be no selectors, everything would be an expression. Expressions would have the set logic that selectors currently have, except implemented with the `and`, `or` and `not` operators instead of the `&`, `|` and `~` operators.

**Comment by cmdlineluser** [comment]
I probably didn't word that too well.

`pl.count("foo")` is shorthand for `pl.col("foo").count()`

Having a top-level function with a general name like `matches` that operates on column names instead of values just seems less than ideal.

**Comment by stinodego** [comment]
Closing in favor of #13757
