### ISSUE TITLE
Add `fill_infinite`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12857]
### Description

We have `fill_null` and `fill_nan`. It would be nice to have a `fill_infinite` as well (useful for cases where, say, uploading to MS SQL server, which does not allow for infs).

**Comment by ritchie46** [comment]
I think this is a bit too specific. We have to stop somewhere and go to `when(col(..).is_infinite()).then(value).otherwise(col(..))`.

We have `fill_nan` because saidly there are some tools that produce `NaN` for missing data. For `inf` this isn't the case.

**Comment by mcrumiller** [comment]
I understand--no problem.
