### ISSUE TITLE
Is it possible to load a csv file with multi frames in polars?

### ISSUE THREAD

**Issue by mushroomfire** [pola-rs/polars#12860]
### Description

Considering a csv file:
```bash
Frame 1
a b c
1 2 3
4 5 6
Frame 2
a b c
1 2 3
4 5 6
Frame 3
```

How to load this kind of csv into multi DataFrames in polars?

**Comment by ritchie46** [comment]
You need to skip_rows and determine the amount of rows to read. We will not split this automatically for you.

A csv file maps to a single dataframe and always will in polars.
