### ISSUE TITLE
`group_by(pl.first())` raises `__POLARS_GB_GROUP_INDICES` has more than one occurrences `DuplicateError`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12869]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

list(pl.DataFrame().group_by(pl.first()))
# DuplicateError: column with name '__POLARS_GB_GROUP_INDICES' has more than one occurrences
```

### Issue description

When using `.first()` / `.last()` (which I guess is `Nth` internally) without an explicit name as a `by` argument raises.

Naming the expression resolves the issue.
```python
list(pl.DataFrame().group_by(pl.first().alias("_first")))
# []
```

### Expected behavior

No exception.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.11.6 (main, Nov  2 2023, 04:39:40) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Wainberg** [comment]
This also happens with e.g. `list(pl.DataFrame({'a': [1]}).group_by(pl.all()))`. The error happens regardless of what's in the DataFrame.

**Comment by Wainberg** [comment]
@ritchie46 this is a bad bug, could you accept this issue?

**Comment by cmdlineluser** [comment]
It seems like [`.agg_groups()`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.agg_groups.html#polars.Expr.agg_groups) can be used instead of adding `temp_col` to the frame?

https://github.com/pola-rs/polars/blob/fe8b7a8c0d8092a78bb3a78539ceb0783d38d2bd/py-polars/polars/dataframe/group_by.py#L97-L101

The issue being it's possible for `.by` or `.more_by` to select the temp column.
