### ISSUE TITLE
Running `explode` on string columns with non-ascii characters does not maintain the other columns properly

### ISSUE THREAD

**Issue by a-wang24** [pola-rs/polars#12884]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
print(pl.DataFrame({"name": ["MÁ", "Ms"]}).with_row_count().explode("name"))

shape: (4, 2)
┌────────┬──────┐
│ row_nr ┆ name │
│ ---    ┆ ---  │
│ u32    ┆ str  │
╞════════╪══════╡
│ 0      ┆ M    │
│ 0      ┆ Á    │
│ 0      ┆ M    │  # this should be row_nr = 1
│ 1      ┆ s    │
└────────┴──────┘

# this is correct
print(pl.DataFrame({"name": ["ab", "cd"]}).with_row_count().explode("name"))

shape: (4, 2)
┌────────┬──────┐
│ row_nr ┆ name │
│ ---    ┆ ---  │
│ u32    ┆ str  │
╞════════╪══════╡
│ 0      ┆ a    │
│ 0      ┆ b    │
│ 1      ┆ c    │
│ 1      ┆ d    │
└────────┴──────┘
```

### Issue description

When running `explode` on a dataframe string column with non-ascii characters, the row count is not maintained correctly across characters.

### Expected behavior

This is the same example as the one above. I expect the second `M` to have a `row_nr` of 1
```python
print(pl.DataFrame({"name": ["MÁ", "Ms"]}).with_row_count().explode("name"))

shape: (4, 2)
┌────────┬──────┐
│ row_nr ┆ name │
│ ---    ┆ ---  │
│ u32    ┆ str  │
╞════════╪══════╡
│ 0      ┆ M    │
│ 0      ┆ Á    │
│ 1      ┆ M    │ 
│ 1      ┆ s    │
└────────┴──────┘
```

### Installed versions

I am using `polars-lts-cpu`

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             macOS-14.1.2-x86_64-i386-64bit
Python:               3.9.10 (main, Nov 12 2023, 16:54:03)
[Clang 15.0.0 (clang-1500.0.40.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              <not installed>
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
I didn't even know you could explode a string. Does `str.split('')` do the same?

**Comment by ritchie46** [comment]
I am starting to think we should remove this support. As doing this over unicode boundaries will be very expensive and complicated.

**Comment by cmdlineluser** [comment]
[`.str.explode()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.explode.html#polars.Expr.str.explode) may offer a workaround until it is fixed.

```python
df = pl.DataFrame({"name": ["MÁ", "Ms"]}).with_row_count()

(df.group_by("row_nr")  
   .agg(pl.col("name").str.explode())
   .explode("name")
)

# shape: (4, 2)
# ┌────────┬──────┐
# │ row_nr ┆ name │
# │ ---    ┆ ---  │
# │ u32    ┆ str  │
# ╞════════╪══════╡
# │ 0      ┆ M    │
# │ 0      ┆ Á    │
# │ 1      ┆ M    │
# │ 1      ┆ s    │
# └────────┴──────┘
```

**Comment by a-wang24** [comment]
> [`.str.explode()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.explode.html#polars.Expr.str.explode) may offer a workaround until it is fixed.

Thank you! I will use that in the meantime

**Comment by stinodego** [comment]
Exploding strings is no longer supported in the frame-level methods. It's still available in the string namespace for backward compatibility.

**Comment by ritchie46** [comment]
Yes, and we should deprecate that as well. It's hard to maintain. Will easily hit our maximum string limit and is not super useful AFAIC.
