### ISSUE TITLE
Stream dataframe from generator

### ISSUE THREAD

**Issue by Minitour** [pola-rs/polars#12897]
### Description

I am trying to work with large JSON objects (2gbs). These are nested objects that cannot be loaded directly with Polars. Therefore I am using [ijson](https://github.com/ICRAR/ijson) to stream events in the form of tuples.

As of today, Polars cannot take a generator as a source of stream because what is happening is that it simply exhaust the generator into memory instead of processing it as expected in a stream like fashion.

```python
f = open('really_big_file.json', 'rb')
events = ijson.parse(f) # this is a generator
df = (
    pl.LazyFrame(events, schema=['path', 'name', 'value']) # This exhausts the generator and loads everything into memory 
   .filter(pl.col('name').is_in(['number', 'start_map', 'string', 'null', 'boolean'])) 
   .group_by(['path', 'name'])
   .count()
   .collect(streaming=True)
)
```

Workarounds:
Write the generator into CSV and use `scan_csv`. The only problem with that is that I have to wait for the file to be written before starting to process it which makes things slower, because sometimes writing the events into disk result in a file bigger than the original JSON.

**Comment by ahmadmaj** [comment]
Facing the same issue here.

**Comment by ElinoyFa** [comment]
Having the same issue

**Comment by alexander-beedie** [comment]
> instead of processing it as expected in a stream like fashion.

Actually this behaviour _is_ expected ;)
As per the `LazyFrame` docstring:
```
Notes
-----
Initialising `LazyFrame(...)` directly is equivalent to `DataFrame(...).lazy()`.
```

**Comment by deanm0000** [comment]
Why is your workaround to save csv rather than parquet?

**Comment by alexander-beedie** [comment]
> A scan_records method that takes any Iterable[dict] might be nice.

Perhaps, but you can't scan a Python generator without consuming it, which naturally implies you have to either read the whole thing (as done now) or you are limited to working only with the streaming-compatible ops. And then there's the question of parallelising it, as the generator is ephemeral (it exists, and can only be read, from a single process/thread), so there is very limited upside.

It's probably better simply to push people towards the existing high-performance methods rather than introduce a convenience path that is _guaranteed_ to be inefficient, as iterating over Python rows is -and always will be- sloooooow.

**Comment by Minitour** [comment]
> Why is your workaround to save csv rather than parquet?

Because using the generator I can simply append a new line at the end of the CSV. I won't be able to do the same thing with Parquet.

**Comment by deanm0000** [comment]
You could do something like [this](https://stackoverflow.com/questions/77593648/how-to-split-100-million-18-5-gb-csv-rows-into-50k-each-small-excel-files/77601125#77601125) but change the batched_csv reader in that answer to your json generator (wrapped in a dataframe constructor) and also change the writer from excel to parquet (with statistics=True) and then use glob patterns with scan_parquet to roll them all up into a single lazyframe.
