### ISSUE TITLE
Adding `expm1` as expression

### ISSUE THREAD

**Issue by trendelkampschroer** [pola-rs/polars#12891]
### Description

It would be nice to be able to have `expm1`, cf. https://en.wikipedia.org/wiki/Exponential_function#Computation, available as a `polars` expression. The inverse `log1p` is already available as an expression.

I am currently using 
```python
 t = (values / 2).tanh()
pl.when(values.abs() < 0.1).then(2.0 * t / (1.0 - t)).otherwise(values.exp() - 1.0)
```
with an arbitrarily defined threshold of `0.1` to get a 'stable' implementation of `expm1` but it's probably sub-optimal, because of the conditional, and a user needs to define a meaningful threshold requiring knowledge of the "region of stability" of the naive `exp(x) - 1` implementation.

Would be happy to try implementing this myself, but I have little/zero knowledge of Rust and experience with the complexity/scope of adding this feature to polars - but I am happy to receive guidance and eventually try it out.

Btw, thanks a lot for creating, supporting, and making polars freely available.

**Comment by deanm0000** [comment]
The numpy function https://numpy.org/doc/stable/reference/generated/numpy.expm1.html#numpy.expm1

Is a ufunc so you can use it directly such as `df.with_columns(np.expm1(pl.col('values')))`

**Comment by trendelkampschroer** [comment]
I am re-opening this because of #13557, i.e. in a `group_by` context a `polars.Expression` cannot simply be replaced by a `numpy` 'ufunc'.

**Comment by deanm0000** [comment]
https://github.com/pola-rs/polars/pull/14135
