### ISSUE TITLE
Can not use more than 16 cpu cores  on  64 cpu cores PC

### ISSUE THREAD

**Issue by dignfei** [pola-rs/polars#12907]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
res = pl.read_ipc(file)
```

### Issue description

When the CPU has 64 cores, reading a 100GB file can only use 16 cores, resulting in slow speed

### Expected behavior

use all 64 cores

### Installed versions

--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-5.15.45-amd64-desktop-x86_64-with-glibc2.35
Python:               3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.1
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              12.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

**Comment by ritchie46** [comment]
Please make a proper issue that is reproducable. There is nothing here that seems like a bug or that we can do anything with.

Reading an IPC file is memory mapped, so I don't expect any CPU usage here.

**Comment by deanm0000** [comment]
@stinodego probably can close.
