### ISSUE TITLE
evaluate Expr outside DataFrame context

### ISSUE THREAD

**Issue by swo** [pola-rs/polars#12914]
### Description

For some Exprs, it is perfectly sensible to evaluate outside the context of a DataFrame, but there is no Expr method like `.collect()` or `.eval()` that evaluates it _outside_ a DataFrame.

Actual behavior:
```python
x = pl.date(2023, 12, 6)
# <class 'polars.expr.expr.Expr'>
# 2023.dt.datetime([12, 6, 0, 0, 0, 0, Utf8(raise)]).strict_cast(Date).alias("date")
x_eval = pl.DataFrame().with_columns(x.alias('x'))['x'][0]
# <class 'datetime.date'>
# 2023-12-06
```

Maybe nice behavior:
```python
x = pl.date(2023, 12, 6)
x_eval = x.eval()
# <class 'datetime.date'>
# 2023-12-06
```

My specific motivation is coming from R tidyverse and lubridate, where the same date and datetime functions would inside and outside dataframes. It's a nice-to-have to be able to use polars Series and Expr functionality outside dataframes, for testing or non-table computations

**Comment by cmdlineluser** [comment]
There is the [`pl.select()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.select.html#polars.select) helper.

```python
pl.select(pl.date(2023, 12, 6))
# shape: (1, 1)
# ┌────────────┐
# │ date       │
# │ ---        │
# │ date       │
# ╞════════════╡
# │ 2023-12-06 │
# └────────────┘
```

```python
pl.select(pl.date(2023, 12, 6)).item()
# datetime.date(2023, 12, 6)
```

**Comment by swo** [comment]
This makes a ton of sense. Thanks for your help!
