### ISSUE TITLE
stackoverflow on `update` on lazy frames in a loop

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#12924]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
lf = pl.DataFrame({'a': [0], 'b': [1], "d": None, "e": None}).lazy()

for i in range(1000):  # works for 100
    lf1 = pl.DataFrame({"a": range(i,i+3), "b": range(i, i+3)}).lazy()
    lf = lf.update(lf1, on="a", how="outer")

print(lf.collect())
```

### Issue description

Segmentation fault (core dumped)

### Expected behavior

Would expect the DF to be evaluated as it is with lower arg in the for loop.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.1.64-1-MANJARO-x86_64-with-glibc2.38
Python:               3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.1
gevent:               23.9.1
matplotlib:           3.8.2
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
I'm not sure if a segfault is expected, but realize that lazy frames create a plan, and on your moment of `.collect` you are effectively performing 1,000 simultaneous `join` operations. We'll have to defer to others as to whether this is reasonable or not.

**Comment by alexander-beedie** [comment]
Curious if this is extracted from a real use-case?
(And, if so, what is it? :)

**Comment by ritchie46** [comment]
This is a stackoverflow. You create a humongous logical plan by recursing. It is expected to happen at a certain point. 1000 recursions seems like a fine limit to me.

**Comment by jmakov** [comment]
> Curious if this is extracted from a real use-case? (And, if so, what is it? :)

I'm getting a lot of DFs from `ray.io` workers and I'm updating the resulting DF in the main thread. I wanted to use the lazy API as otherwise the `for` loop takes ages (calling `.update`). And when doing so I stumbled upon this exception.

**Comment by ritchie46** [comment]
> To avoid what's "reasonable" and what's not, perhaps a warning can be shared somewhere in the docs about how complex/long plan polars supports. A nice msg for the user would also be awesome e.g. QueryPlanException("Number of query plans greater than supported: got 1001, but max 100 possible") as opposed to a segfault.

It isn't that trivial. We haven't got a runtime like python has to inspect the stack. 

To solve your issue you can collect once in e.g. 100 iterations.

**Comment by mcrumiller** [comment]
@jmakov what is your use case here? I'm questioning whether `update` is the way to go. If you are constantly replacing values with new data, perhaps you should instead be `vstack`ing, followed by a `df.unique(keep="last")`, or something of the sort.

**Comment by mcrumiller** [comment]
@jmakov are the timestamps all unique, or are some timestamps shared across dataframes, and you need to aggregate those records?

**Comment by jmakov** [comment]
@mcrumiller so the (timestamp, colX) are unique.

**Comment by mcrumiller** [comment]
Here's how I would probably try doing it, without seeing an example I'm not sure if it'll work for you:

```python
import polars as pl
from polars import col

# sample frames, assuming timestamp is integer right now, and that the "column" column contains data
df1 = pl.DataFrame({"timestamp": [1, 2, 3], "col1": [1, 2, 3]})
df2 = pl.DataFrame({"timestamp": [4, 5, 6], "col2": [4, 5, 6]})
df3 = pl.DataFrame({"timestamp": [7, 8, 9], "col3": [7, 8, 9]})
df4 = pl.DataFrame({"timestamp": [10, 11, 12], "col4": [10, 11, 12]})
df5 = pl.DataFrame({"timestamp": [13, 14, 15], "col5": [13, 14, 15]})

dfs = [df1, df2, df3, df4, df5]

for i in range(len(dfs)):
    column = dfs[i].columns[1]
    dfs[i] = dfs[i].select(
        "timestamp",                              # get the timestamp
        pl.lit(int(column[3:])).alias("Column"),  # extract column num as a value
        col(column).alias("Value"),               # store the value
    )

# concat into single DF with 3 columns
df = pl.concat(dfs)

# if you want your original columns, perform a pivot operation
df = df.pivot(
    values="Value",
    index="Column",
    columns="timestamp",
    aggregate_function=None,  # use a function here if your timestamps aren't all unique
).sort(by="Column")
```

**Comment by mcrumiller** [comment]
Do you have any control of the process? This sounds like trying to use polars to solve a poorly formatted data issue. I'm happy to give more suggestions if you could provide a clearer description of your files and what they contain.
