### ISSUE TITLE
Ambiguous name for `arrow` in polars-parquet

### ISSUE THREAD

**Issue by jankislinger** [pola-rs/polars#12938]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```shell
cargo new polars-test-proj
cd polars-test-proj
cargo add polars@0.35.4 --features=dtype-full,parquet,lazy
cargo build
```

### Log output

```shell
error[E0659]: `arrow` is ambiguous
 --> /home/jan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-parquet-0.35.4/src/lib.rs:3:9
  |
3 | pub use arrow::{read, write};
  |         ^^^^^ ambiguous name
  |
  = note: ambiguous because of multiple potential import sources
  = note: `arrow` could refer to a crate passed with `--extern`
  = help: use `::arrow` to refer to this crate unambiguously
note: `arrow` could also refer to the module defined here
 --> /home/jan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-parquet-0.35.4/src/lib.rs:2:1
  |
2 | pub mod arrow;
  | ^^^^^^^^^^^^^^
  = help: use `crate::arrow` to refer to this module unambiguously

For more information about this error, try `rustc --explain E0659`.
error: could not compile `polars-parquet` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

### Issue description

It is not possible to build empty library with latest varsion of polars with feature `parquet`.

I tried following the hint and changed line 3 to `pub use crate::arrow::{read, write};` and the build finished. Should that be changed or my system is flawed?

### Expected behavior

It should build

### Installed versions

<details>

             + csv
             + docs
             + dtype-array
             + dtype-categorical
             + dtype-date
             + dtype-datetime
             + dtype-decimal
             + dtype-duration
             + dtype-full
             + dtype-i16
             + dtype-i8
             + dtype-slim
             + dtype-struct
             + dtype-time
             + dtype-u16
             + dtype-u8
             + fmt
             + lazy
             + parquet
             + polars-io
             + polars-lazy
             + polars-time
             + temporal
             + zip_with

</details>

**Comment by jamesperez2005** [comment]
@ritchie46 any chance you can publish a release containing the fix for this issue any time soon? That would be greatly appreciated

**Comment by tzeitim** [comment]
@jamesperez2005 :

> ritchie46 any chance you can publish a release containing the fix for this issue any time soon? That would be greatly appreciated

If you are in a rush just do it manually as they did in here:

https://github.com/pola-rs/polars/pull/12939/files

Find where is the source. E.g. from the OP:

`/home/jan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-parquet-0.35.4/src/lib.rs`
