### ISSUE TITLE
Add an argument `strict` to constructors, cast, etc to ensure the integer range etc on python polars (and otherwise) instead of silently converting to null.

### ISSUE THREAD

**Issue by ztane** [pola-rs/polars#1293]
We were trying Python polars 0.9.1 / 0.9.2 with large integers, > 2 ** 64. To our dismay, the following expression:

```
polars.Series('a', [2 ** 65])
```

would produce

```
shape: (1,)
Series: 'a' [i64]
[
        null
]
```

Similar problems would happen with cast - for example: 

```
>>> polars.Series('a', [2 ** 16]).cast(dtype=polars.Int16)
shape: (1,)
Series: 'a' [i16]
[
        null
]
```

We're especially interested in using Polars for data conversion tasks (mapping series to other types, CSV to parquet and conversions) as we're constantly let down by Pandas' handling of nullable integers and data type conversions and especially the memory consumption - but we would definitely want to have strict datatype conversions. 

It is apparent that Polars *does* check the value properly as otherwise it couldn't/wouldn't produce `null` there - perhaps there could be `strict=True` argument that would throw on coming upon an invalid value, just like Pandas does (and Pandas does it by default) - it wouldn't even have to throw with the *first* value but some value.

Here's the behaviour from pyarrow:

```
>>> pyarrow.table({'a': [2**64]})
Traceback (most recent call last):
OverflowError: Python int too large to convert to C long
```

and pandas (pandas will make an *object* array of ints >= 2**64, so you need to specify a dtype):

```
>>> pandas.DataFrame({'a': [2**64]}, dtype='int64')
Traceback (most recent call last):
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
OverflowError: The elements provided in the data cannot all be casted to the dtype int64
```

**Comment by ritchie46** [comment]
I think this makes a lot of sense. I will add strict behavior.

**Comment by ritchie46** [comment]
Added and released. :+1:
