### ISSUE TITLE
Unsupported aggregation functions return `None` on String columns

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#12935]
Reproduction:

```python
df = pl.DataFrame({"s": ["test", "foo"], "l": [[1], [2]]})
print(df)
print(df["s"].sum(), df["s"].min(), df["s"].max())
print(df["l"].sum(), df["l"].min(), df["l"].max())
```

This prints:

```
shape: (2, 2)
┌──────┬───────────┐
│ s    ┆ l         │
│ ---  ┆ ---       │
│ str  ┆ list[i64] │
╞══════╪═══════════╡
│ test ┆ [1]       │
│ foo  ┆ [2]       │
└──────┴───────────┘
None foo test
None None None
```

I'd expect `sum`/`min`/`max` to give proper errors for unsupported dtypes instead of silently returning None.

**Comment by mcrumiller** [comment]
Slightly related, should a utf8 `sum` be a concatenation of all elements?

```python
pl.Series(["a"]) + pl.Series(["b"])
```
```
Series: '' [str]
[
        "ab"
]
```

**Comment by thomasfrederikhoeck** [comment]
Should't `min` and `max` also make sense for `utf-8` since they have ordering?

**Comment by thomasfrederikhoeck** [comment]
@mcrumiller I was a bit to fast on the trigger (I reailised and deleted :-D )

**Comment by orlp** [comment]
@mcrumiller

> Slightly related, should a utf8 sum be a concatenation of all elements?

I'd prefer not, the error message will redirect you to .str.concat which is the appropriate implementation.

**Comment by stinodego** [comment]
This has been fixed for lists.

We should still update String `sum` to redirect to `str.concat`.
