### ISSUE TITLE
Add support to group_by + implode in stream mode

### ISSUE THREAD

**Issue by chriss1245** [pola-rs/polars#12930]
### Description

I am making some crazy stuff with group_by and map_groups.

 I understand that stream mode should not be available for all the things i do, but I think that it would be interesting to be able to use stream mode to save the result of a group_by + implode.  This way I would be able to apply a more memory efficient  aggregation.

**Comment by cmdlineluser** [comment]
Do you have any specific code examples?

Perhaps there is an alternative approach for what you're doing. 

Anytime I've used `.implode()` it seems to negatively impact performance/memory usage greatly.

**Comment by ritchie46** [comment]
Implode is by definition not a good fit for a streaming algorithm as it needs to keep all data around. We will focus initially on algorithms that benefit for streaming implementations.

**Comment by chriss1245** [comment]
I see... That sounds logical.  Thanks a lot!
