### ISSUE TITLE
min/max incorrectly can return nan on sorted arrays

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#12931]
Reproduction:

```python
s = pl.Series([1.0, float('nan')])
print(s.max(), s.sort().max())
```

This prints `1.0 nan`.

This is due to the optimization that we pick the first/last element for min/max on sorted arrays.

**Comment by daniel-vainsencher** [comment]
I just hit this.

While trying to understand how polars deals with nans and nulls in computing quantiles, I happened to find 

https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.nan_max.html

which documents that "This differs from numpy’s nanmax as numpy defaults to propagating NaN values, whereas polars defaults to ignoring them." I found that pleasantly surprising, and then immediately found it to be wrong. Took a while to understand it had to do with my sorting the series. 

This kind of breakage in invariants can be hard to debug, though I still think P-medium sounds about right.
