### ISSUE TITLE
Can't filter or join on equality of frozensets

### ISSUE THREAD

**Issue by AhmedAliStats** [pola-rs/polars#12933]
Don't know if this should be considered a bug or a feature request.

I can't filter on equality of frozensets and can't join on a column of frozensets.

```
import polars as pl

df1 = pl.DataFrame({'A': [1, 1, 2, 2], 'C': [1, 2, 3, 4]})
df2 = pl.DataFrame({'B': [3, 3, 4, 4], 'C': [1, 2, 3, 4]})
df1 = df1.group_by('A').agg(pl.col('C').map_elements(frozenset))
df2 = df2.group_by('B').agg(pl.col('C').map_elements(frozenset))

# join on frozensets
df1.join(df2, how='left', on='C')

# filter on frozensets
df1.join(df2, how='cross').filter(pl.col('C') == pl.col('C_right'))
```

Are there any workarounds?

EDIT: this holds true for sets as well.

EDIT2: Here's a workaround for whoever needs to do this and doesn't care about performance (use at your own risk)
```
# filter on frozensets
df1 = df1.join(df2, how='cross')
df1 = df1.filter([row['C'] == row['C_right'] for row in df1.iter_rows(named=True)])
```

**Comment by cmdlineluser** [comment]
Looks like sets result in a column with a dtype of `object` which essentially makes it unusable.

```python
pl.DataFrame({"A": [{1, 2}]})
# shape: (1, 1)
# ┌────────┐
# │ A      │
# │ ---    │
# │ object │
# ╞════════╡
# │ {1, 2} │
# └────────┘
```

> Are there any workarounds?

Can you implement the logic in Polars directly without using sets?

**Comment by orlp** [comment]
We don't yet support joins on *lists* (something we do want), but once we do you can sort the values within each list before joining.

As a workaround for now you can concatenate the lists to strings and join on that.

**Comment by orlp** [comment]
That said, we will never support directly joining on Python (frozen)sets, or other `object`s as it is inherently incredibly slow.
