### ISSUE TITLE
Duplicated text on the official website

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#12943]
### Description

Not sure this is the right place to report it but on the official website (https://pola.rs/), in the section "How Polars will make your life easier", there is duplicated text in the first paragraph:

> Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimiser. way to execute using its query optimiser.

**Comment by c-peters** [comment]
Thank you, issue is fixed now.
