### ISSUE TITLE
Casting to unsigned integer can overflow even if `strict=True`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#12949]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.select(pl.lit(-1).cast(pl.UInt32)).item()
```

### Log output

```shell
4294967295
```

### Issue description

With `strict=True` (enabled by default), this should raise an error.

### Expected behavior

Raise an error.

### Installed versions

main branch

**Comment by mcrumiller** [comment]
This only appears to be the case for directly casting a literal:

```python
import polars as pl
from polars import col

s = pl.Series("a", [-1], dtype=pl.Int8)

# series: correctly errors
s.cast(pl.UInt8)

# column expr: correctly errors
s.to_frame().select(col("a").cast(pl.UInt8))

# literal: incorrectly succeeds
pl.select(pl.lit(-1, dtype=pl.Int8).cast(pl.UInt8))
```
