### ISSUE TITLE
`main` branch still has version==`0.19.18`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#12970]
The version was bumped to 0.19.19 in https://github.com/pola-rs/polars/commit/2a12aba5dc73631d13d98fc7d6d0ef3c30aacd8b in a nonstandard fashion and the `main` branch was never updated.

**Comment by stinodego** [comment]
We will bump it straight to 0.20.0 in the next release.

**Comment by stinodego** [comment]
We will bump it straight to 0.20.0 in the next release.

**Comment by alexander-beedie** [comment]
(oops; looks a little aggressive on my part, but was just removing a duplicate comment. won't bother doing that again! 🤣)

**Comment by stinodego** [comment]
Must've happened due to poor WiFi on the train 🤔 

GitHub UI has a 'mark as duplicate' option, you can use that in the future.
