### ISSUE TITLE
error[E0433]: failed to resolve: use of undeclared type `ParquetReader`

### ISSUE THREAD

**Issue by Crispy13** [pola-rs/polars#12972]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
// https://docs.rs/polars/latest/polars/docs/eager/index.html#read-parquet

use polars::prelude::*;
use std::fs::File;

// open file
let file = File::open("some_file.parquet").unwrap();

// read to DataFrame
let df = ParquetReader::new(file).finish()?;

```

### Issue description

```
...
polars = { version = "0.35.4", features = ["lazy", "concat_str", "strings", "polars-io"] }
...
```

```
error[E0433]: failed to resolve: use of undeclared type `ParquetReader`
```

The errors is shown even after adding the above line to `Cargo.toml`

### Expected behavior

No errors are shown.
According to the page, `https://docs.rs/polars/latest/polars/prelude/struct.ParquetReader.html`
It seems that the only needed feature is `polars-io`.
But `cargo add polars --features polars-rs` is not enough and the error was solved after adding 'parquet' features additionally.

### Installed versions

<details>
```
...
polars = { version = "0.35.4", features = ["lazy", "concat_str", "strings", "polars-io"] }
...
```

</details>

**Comment by ritchie46** [comment]
You must add the `parquet` feature. Not `polars-io`.

**Comment by Crispy13** [comment]
Do we need to edit the documentation?
It says "add `polars-io`" not `parquet` feature.
