### ISSUE TITLE
Avoid dispatching more Series functions to the expression engine

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#13009]
### Description

As a following up to #12928, there are many `Series` functions that 1) don't rely on the expression dispatch decorator, but 2) still dispatch to the expression engine. As shown in the previous issue, using the expression engine is significantly slower than a direct line to the Series.

Functions that could easily benefit from this are:

* `any`
* `all`
* `product`
* `std`
* `var`
* `value_counts`
* `is_between`
* `slice`
* ~~`entropy`~~
* ~~`cut`~~
* ~~`qcut`~~
* ~~`nan_max`~~
* ~~`nan_min`~~

**Comment by ritchie46** [comment]
I think `slice`, `all`, `any` are worth it.

The other ones will likely be removed from `Series` in the future.

**Comment by mcrumiller** [comment]
Hi @ritchie46, sorry I saw your comment after making the PR.

Is it worth keeping these implementations around until those functions are removed at least, or should I pull the implementations on everything that's not `slice`/`all`/`any`? Also, I use `product`/`std`/`var`/`is_between`/`value_counts` all the time in Series, what's the rationale for remvoing those?
