### ISSUE TITLE
Should n_cols.max(1) * thread_factor be in parenthesis here?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#13019]
https://github.com/pola-rs/polars/blob/ac7ffa67db1ac531a402413831b546515b537ab5/crates/polars-pipe/src/pipeline/mod.rs#L26-L35

Our `thread_factor` is going to be 1 if we have 12 or more threads, otherwise it'll be a greater than 1.

So then our final chunk size, w/o parenthesis, gets bigger for fewer threads.

For example if we have 3 threads then our thread_factor=12/3=4

Let's say we have 10 columns

Then 50_000/10 * 4=20_000

It seems like it should be 50_000/(10*4)=1250

Of course, I don't really understand the thread_factor logic so I may be way off here. Maybe that number should be the reciprocal of what it is with no parens?

**Comment by ritchie46** [comment]
Thge idea is that it get's bigger. Your have one chunk per thread. So if you have less threads, we can enlarge the chunk size and have the same memory pressure.

**Comment by deanm0000** [comment]
I see, that makes sense. I was thinking maybe bigger chunks could be exacerbating time out issues with reading from the cloud.
