### ISSUE TITLE
Allow comparing dates with strings in SQL

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#13025]
### Description

Polars does currently not support this:

```python
from datetime import date

c = pl.SQLContext()
c.register("df", pl.DataFrame({"a": [date(2022, 1, 2), date(2022, 1, 2), date(2022, 1, 3)]}))
c.execute("select * from df where a > '2023-01-01'").collect()

```

You need to cast the literal, eg cast('2023-01-01' as date). Every other sql system I know does support that comparison and it would be nice if polars did, too.

**Comment by alexander-beedie** [comment]
I know of a few that don't, and others that can return incorrect results in various edge-cases if you use a literal without clarifying that it's temporal...😉 

You can use the simpler PostgreSQL-style cast syntax to make it less burdensome though: 

`'2023-01-01'::date`
