### ISSUE TITLE
join_asof does not raise a ColumnNotFoundError when the by_left/by_right columns can't be matched - e.g. by_left=None, by_right=['entityId']

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#13020]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import date, timedelta
import polars as pl 
import numpy as np

df1 = pl.DataFrame({'asOfDate': (date(2020,i,1) for i in range(1,12+1))})


data_for_df2 = []
for entity in list('ABCDE'):
    for some_date in range(100):
        data_for_df2.append(
            {'entityId': entity, 'eventDate': date(2020,1,1) + timedelta(days=np.random.randint(0,365))}
        )


df2 = pl.DataFrame(data_for_df2)

# df1.pipe(print)
# shape: (12, 1)
# ┌────────────┐
# │ asOfDate   │
# │ ---        │
# │ date       │
# ╞════════════╡
# │ 2020-01-01 │
# │ 2020-02-01 │
# │ 2020-03-01 │
# │ 2020-04-01 │
# │ …          │
# │ 2020-09-01 │
# │ 2020-10-01 │
# │ 2020-11-01 │
# │ 2020-12-01 │
# └────────────┘

# df2.pipe(print)
# shape: (500, 2)
# ┌──────────┬────────────┐
# │ endityId ┆ eventDate  │
# │ ---      ┆ ---        │
# │ str      ┆ date       │
# ╞══════════╪════════════╡
# │ A        ┆ 2020-06-23 │
# │ A        ┆ 2020-08-18 │
# │ A        ┆ 2020-06-02 │
# │ A        ┆ 2020-04-19 │
# │ …        ┆ …          │
# │ E        ┆ 2020-10-17 │
# │ E        ┆ 2020-10-12 │
# │ E        ┆ 2020-04-13 │
# │ E        ┆ 2020-03-12 │
# └──────────┴────────────┘

# Code that I think is not working as intended:
df_ans = df1.sort('asOfDate').join_asof(df2.sort('eventDate'), left_on='asOfDate', right_on='eventDate', by_left=None, by_right=['entityId'])

# df_ans.pipe(print)
# shape: (12, 3)
# ┌────────────┬──────────┬────────────┐
# │ asOfDate   ┆ entityId ┆ eventDate  │
# │ ---        ┆ ---      ┆ ---        │
# │ date       ┆ str      ┆ date       │
# ╞════════════╪══════════╪════════════╡
# │ 2020-01-01 ┆ B        ┆ 2020-01-01 │
# │ 2020-02-01 ┆ C        ┆ 2020-02-01 │
# │ 2020-03-01 ┆ D        ┆ 2020-03-01 │
# │ 2020-04-01 ┆ D        ┆ 2020-04-01 │
# │ …          ┆ …        ┆ …          │
# │ 2020-09-01 ┆ A        ┆ 2020-09-01 │
# │ 2020-10-01 ┆ E        ┆ 2020-10-01 │
# │ 2020-11-01 ┆ B        ┆ 2020-11-01 │
# │ 2020-12-01 ┆ C        ┆ 2020-12-01 │
# └────────────┴──────────┴────────────┘
```

### Issue description

The `by_right` parameter is being ignored, resulting in only one row in the output for each row in the left df.

### Expected behavior

When doing an asof join with a `by_right` key and no `by_left` columns I'd expect either of the following results:

1. An error, probably a `ColumnNotFoundError`
2. A result equivalent to an outer join and filtering for the last record in the right df with an `eventDate` before the `asOfDate` (as per the backward strategy) for each group described by the `by_right` parameter.

ie. equivalent to

```python
(df1
  .join(df2, how='cross')
  .filter(pl.col('eventDate') <= pl.col('asOfDate'))
  .group_by('asOfDate', 'entityId')
  .agg(pl.col('eventDate').max())
)

# shape: (58, 3)
# ┌────────────┬──────────┬────────────┐
# │ asOfDate   ┆ entityId ┆ eventDate  │
# │ ---        ┆ ---      ┆ ---        │
# │ date       ┆ str      ┆ date       │
# ╞════════════╪══════════╪════════════╡
# │ 2020-06-01 ┆ E        ┆ 2020-06-01 │
# │ 2020-07-01 ┆ E        ┆ 2020-06-30 │
# │ 2020-03-01 ┆ E        ┆ 2020-02-29 │
# │ 2020-07-01 ┆ D        ┆ 2020-06-28 │
# │ …          ┆ …        ┆ …          │
# │ 2020-07-01 ┆ C        ┆ 2020-06-24 │
# │ 2020-04-01 ┆ E        ┆ 2020-03-31 │
# │ 2020-02-01 ┆ E        ┆ 2020-01-30 │
# │ 2020-12-01 ┆ B        ┆ 2020-12-01 │
# └────────────┴──────────┴────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Windows-10-10.0.22621-SP0
Python:               3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.5.1
cloudpickle:          2.2.0
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.9.1
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.22.4
openpyxl:             3.0.10
pandas:               2.1.4
pyarrow:              10.0.1
pydantic:             1.10.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.44
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9```

</details>

**Comment by mkleinbort-ic** [comment]
In the interim, for anyone stumbling on this issue

```python

def _my_join_asof(
        self,other: pl.DataFrame,
        *,left_on = None, right_on = None, on = None,
        by_left = None, by_right = None, by = None,
        strategy = 'backward', suffix = '_right',
        tolerance = None
        ) -> pl.DataFrame:
    
    assert by_right is not None, f'This does not seem to be an appropriate use of the my_join_asof function due to {by_right=}'
    assert by_left is None, f'This does not seem to be an appropriate use of the my_join_asof function due to {by_left=}'
    assert by is None, f'This does not seem to be an appropriate use of the my_join_asof function due to {by=}'
    
    if left_on is None and right_on is None and on is not None:
        left_on, right_on = on, on
        
    df_left = self.sort(left_on)
    df_right = other.sort(right_on)
    
    # Helper cross join:
    df_left_per_entity = df_left.join(df_right.select(by_right).unique(), how='cross').sort(left_on)
    
    # Actual as of join:
    df_ans = df_left_per_entity.join_asof(
                                    df_right, 
                                    left_on = left_on, 
                                    right_on = right_on, 
                                    by_left = by_right, 
                                    by_right = by_right,
                                    
                                    # Pass on of parameters
                                    strategy=strategy, suffix=suffix, tolerance=tolerance
    )
    
    return df_ans

df1.pipe(_my_join_asof, df2, left_on='asOfDate', right_on='eventDate', by_left=None, by_right=['entityId'])

```

**Comment by mcrumiller** [comment]
The `by` arguments are designed as additional columns to join on prior to performing the `join_asof`. They aren't "group by" columns. This is the equivalent of calling `df1.join(df2, right_on="A")`, which makes no sense--what is column `A` supposed to join against? For every `by_left` parameter, you need a `by_right` parameter.

There used to only be a single `by` argument, but because frames may have different names for the join columns, allowing the left/right frames to have different names for the join column was warranted.

**Comment by mkleinbort-ic** [comment]
That can make sense, but then probably best to raise a `ColumnNotFound` error when the `by` columns are not present. 

In other parts of the codebase the `by` parameter is used to do the operation "per group" - the [.rolling](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.rolling.html#polars.DataFrame.rolling) method comes to mind.

**Comment by mkleinbort-ic** [comment]
We could get into a philosophical discussion whether first joining on a column in the right df that is missing from the left df should result in a cross-join like behaviour, but that was probably not the intended use.

**Comment by mcrumiller** [comment]
> That can make sense, but then probably best to raise a ColumnNotFound error when the by columns are not present.

I agree with this.

**Comment by mkleinbort-ic** [comment]
FYI from ChatGPT (prompt: Give me an example of where joining two tables on a column that is missing from one of them results in a cross join-like result)

Let's consider an example using Python and SQL, where we try to join two tables on a column that's missing from one of them.

### Scenario:
We have two tables: `employees` and `departments`. Suppose `employees` has columns `employee_id`, `name`, and `department_id`, while `departments` has columns `department_id` and `department_name`.

### Tables Example:

**employees**
| employee_id | name     | department_id |
|-------------|----------|---------------|
| 1           | Alice    | 10            |
| 2           | Bob      | 20            |
| 3           | Charlie  | 30            |

**departments**
| department_id | department_name |
|---------------|-----------------|
| 10            | HR              |
| 20            | Finance         |

### SQL Query:
```sql
SELECT *
FROM employees
JOIN departments ON employees.department_name = departments.department_name;
```

### Problem:
The `employees` table doesn't have a `department_name` column. We intended to join on `department_id`, but mistakenly wrote `department_name`.

### Result:
This will result in a cross join because the condition in the `ON` clause is always false (as `department_name` doesn't exist in `employees`). The result set will be a combination of every row in `employees` with every row in `departments`, which looks like this:

| employee_id | name    | department_id | department_id | department_name |
|-------------|---------|---------------|---------------|-----------------|
| 1           | Alice   | 10            | 10            | HR              |
| 1           | Alice   | 10            | 20            | Finance         |
| 2           | Bob     | 20            | 10            | HR              |
| 2           | Bob     | 20            | 20            | Finance         |
| 3           | Charlie | 30            | 10            | HR              |
| 3           | Charlie | 30            | 20            | Finance         |

### Conclusion:
Attempting to join on a non-existent column in one of the tables results in a Cartesian product of the two tables, akin to a cross join. It's a common pitfall that can lead to unexpectedly large and incorrect result sets. Always double-check your join conditions!

**Comment by mcrumiller** [comment]
Ok, I can see in the wild that this may occur, but it sounds dangerous to me. If someone is intentionally using a missing column in order to perform a cross-join then they should probably be more explicit. This feels like it's relying on hidden features.

What flavors work this way? I know in the main ones that I use (Postgresql, MSSQL, Oracle), doing a `table1 JOIN table2 ON table1.nonexistent_column = table2.existent_column` would give an error.

**Comment by mkleinbort-ic** [comment]
Oh, don't get me wrong - I totally support raising a `ColumnNotFound` error, but when I didn't get one my brain thought "Oh, cool, free cross join"

Re SQL dialect, not sure, might have been a GPT hallucination. I remember the "joining on missing resulting in a cross join" being a weird quirk in some code I worked on a while back - it might have been some issue with natural joins in generated SQL now that I think about it.

In any case, I wanted the cross join behaviour for my use-case, but happy for the `.join_asof` to raise an error.

**Comment by cmdlineluser** [comment]
Anything I've seen related to ASOF joins say they only return a single row/value:

<sub>https://www.timescale.com/blog/implementing-asof-joins-in-timescale/</sub>

> In simple terms, an ASOF join will, for each row in the left table, find a corresponding single row in the right table

<sub>https://duckdb.org/docs/guides/sql_features/asof_join.html#outer-asof-joins</sub>

> Because AsOf produces at most one match from the right hand side

<sub>https://code.kx.com/q4m3/9_Queries_q-sql/#998-as-of-joins</sub>

> As-of joins are so-named because they most often join tables along time columns to obtain a value in one table that is current as of a time in another table.

**Comment by mkleinbort-ic** [comment]
Yep, I agree - just leaving the issue open due to the "should raise a ColumnNotFoundError"

Will rename the issue for clarity
