### ISSUE TITLE
Polars series logical operators

### ISSUE THREAD

**Issue by alephfirmino** [pola-rs/polars#13037]
### Description

I would like to suggest adding Polaras series logical operators, since it already have arithmetical operators.

**Comment by alexander-beedie** [comment]
Can you clarify what you are looking for here, maybe with a small example or use-case? Thanks :)

**Comment by alephfirmino** [comment]
Just like pandas do: 
![image](https://github.com/pola-rs/polars/assets/136003542/df06d036-3c27-4ee3-8dbf-5ee70e05deba)

**Comment by alexander-beedie** [comment]
> Don't these already exist?

Indeed, hence my request for clarification ;)

```python
import polars as pl

s1 = pl.Series([True, True, False, True, False])
s2 = pl.Series([False, True, False, False, True])

s1 & s2  # and
s1 | s2  # or
s1 ^ s2  # xor
~s2      # not
```

@alephfirmino: Could you let us know if you think we're missing anything here? All of the above operators already work with polars `Series`.

**Comment by alephfirmino** [comment]
I'm talking this in Rust Polars. Not in Python Polars.

**Comment by alephfirmino** [comment]
Here don't include the logical operations: [](https://docs.rs/polars/latest/polars/series/struct.Series.html ).

**Comment by ptiza** [comment]
> Here don't include the logical operations: https://docs.rs/polars/latest/polars/series/struct.Series.html .

Please see https://docs.rs/polars/latest/polars/series/trait.SeriesTrait.html#method.bitand

**Comment by stinodego** [comment]
Closing this as these already exist.
