### ISSUE TITLE
Clarify when to use the pl.Expr.arr namespace vs. the pl.Expr.list namespace

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#13045]
### Description

The documentation does not clarify when to use [pl.Expr.arr](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/array.html) vs. [pl.Expr.list](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html)

Note that the following are all the methods available in [pl.Expr.arr](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/array.html)

[Expr.arr.max](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.max.html#polars.Expr.arr.max)

[Expr.arr.min](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.min.html#polars.Expr.arr.min)

[Expr.arr.sum](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.sum.html#polars.Expr.arr.sum)

[Expr.arr.to_list](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.to_list.html#polars.Expr.arr.to_list)

[Expr.arr.unique](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.unique.html#polars.Expr.arr.unique)
</html>

And all of these are available in the [pl.Expr.list](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html) namespace.

**Comment by avimallu** [comment]
Lists and Arrays are two different data types - you should use them based on the column you're referring to. Is that unclear somehow in the docs?

FWIW, the fact that they're different data types is also clearly mentioned in the user guide [here](https://pola-rs.github.io/polars/user-guide/expressions/lists/).

**Comment by mkleinbort-ic** [comment]
Yes, it's clear in the user guide.

For anyone encountering this issue:
1. All entries in an `Array` type column must be the same length, entries in a `List` type column can have different lengths
2. `Array` columns may grow to include functionality missing from the `List` columns, but this is a WIP.
