### ISSUE TITLE
`polars.Expr.zip_with`

### ISSUE THREAD

**Issue by tim-stephenson** [pola-rs/polars#13054]
### Description

There exists a `polars.Series.zip_with`. Could (and should) this exists as a feature available for 'Expressions' as well?

I am expecting that either:

- It is possible, but there would be is no performance improvement of using it
- It is not possible (for some reason)
- Yes, it is possible

**Comment by cmdlineluser** [comment]
It looks like the behaviour would be equivalent to `pl.when().then().otherwise()`?

**Comment by tim-stephenson** [comment]
I was unaware of `pl.when().then().otherwise()`. Thank you.
