### ISSUE TITLE
Transform letters to uppercase letters

### ISSUE THREAD

**Issue by wangjiawen2013** [pola-rs/polars#13056]
### Description

Hi,
The following code on rust doc reported an error:
```
use polars::prelude::*;
use polars::df;

let mut df = df![
    "letters" => ["a", "b", "c", "d"],
    "numbers" => [1, 2, 3, 4]
]?;


// coerce numbers to floats
df.try_apply("number", |s: &Series| s.cast(&DataType::Float64))?;

// transform letters to uppercase letters
df.try_apply("letters", |s: &Series| {
    Ok(s.utf8()?.to_uppercase())
});
```
Error:
[E0599] Error: no method named `to_uppercase` found for reference `&polars::prelude::ChunkedArray<Utf8Type>` in the current scope
    ╭─[command_49:1:1]
    │
 15 │     Ok(s.utf8()?.to_uppercase())
    │                  ──────┬─────  
    │                        ╰─────── method not found in `&ChunkedArray<Utf8Type>`
────╯

### Link

https://docs.rs/polars/latest/polars/docs/eager/index.html#dataframe-1

**Comment by ritchie46** [comment]
You must activate the `strings` feature.

**Comment by wangjiawen2013** [comment]
I cannot activate the `strings` feature. 
`polars = {version = "0.35.4", features = ["strings","ndarray","lazy","concat_str","rows","round_series"]}`
The following error occured:
unresolved import `core::unicode`
