### ISSUE TITLE
Count of a boolean expr.

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#13078]
### Description

I understand this is extremely minor, but it kind of drives me crazy.

If I have two columns `x` and `y` and want to count the rows where they are equal.
I wish I could write something like `pl.count().where(pl.col("x") == pl.col("y"))`.  
It looks like the best approach right now is something like a dummy column of ones.

```python
import numpy as np
import polars as pl

rng = np.random.default_rng(seed=0)
df = pl.DataFrame({
    "x": pl.Series(rng.integers(-100, 100, 1_000_000)).cast(pl.Utf8),
    "y": pl.Series(rng.integers(-100, 100, 1_000_000)).cast(pl.Utf8),
})
```

```python
%%timeit
df.select(pl.col("x").eq(pl.col("y")).sum())
"""11.3 ms ± 172 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)"""
```

```python
%%timeit
df.with_columns(
    pl.lit(1, dtype=pl.UInt8).alias("z")
).select(pl.col("z").where(pl.col("x").eq(pl.col("y"))).len())
"""9.37 ms ± 320 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)"""
```

**Comment by s-banach** [comment]
Yeah, that’s how I code it in practice.
It’s an extremely small performance gap, I guess it’s not worth the time to implement anything else.

**Comment by cmdlineluser** [comment]
Isn't the ones approach "twice as slow" in that output? `170us` vs `320us`?

They time pretty much identical for me (even with larger row count)

```python
df.select(pl.col("x").eq(pl.col("y")).sum())
# 7.82 ms ± 6.55 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

df.with_columns( pl.lit(1, dtype=pl.UInt8).alias("z")
).select(pl.col("z").where(pl.col("x").eq(pl.col("y"))).len())
# 7.83 ms ± 6.79 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by stinodego** [comment]
I don't think we need a different kind of expression for this. Perhaps there can be an optimized path in the backend for this.

I'll close this for now as I don't think there's anything actionable here that we should pick up right now.
