### ISSUE TITLE
Add `Expr.scatter`

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#13087]
### Description

Currently `scatter` is only available on `Series`. It would be more useful if it was also available on expressions.

**Comment by MarcoGorelli** [comment]
scatter takes two arguments: the indices, and the new values. I think you're missing the values from your example

going to cc @orlp on this one

**Comment by wukan1986** [comment]
may be

```python
pl.full_like(pl.col('A'), fill_value=None).scatter(pl.col('A').arg_not_null(), pl.col('A').drop_nulls())

or

pl.scatter(pl.col('A').arg_not_null(), pl.col('A').drop_nulls())
```

**Comment by orlp** [comment]
I think allowing arbitrary expressions with scatter is useful, and shouldn't be too difficult to add. I'd like to keep the current signature though, so `Expr.scatter(indices, values)` where `indices` and `values` are equal length (or `values` has length one and is being broadcasted).

**Comment by orlp** [comment]
@wukan1986 I edited the original post to just focus on the feature request instead of the specific example.

**Comment by wukan1986** [comment]
https://github.com/pola-rs/polars/issues/12925#issuecomment-2552764629

A solution has already been found
