### ISSUE TITLE
read_parquet/scan_parquet using gcs emulator

### ISSUE THREAD

**Issue by daviskirk** [pola-rs/polars#13085]
### Description

 Is there a way to use STORAGE_EMULATOR_HOST to connect to a local google gcs emulator?

**Additional context**
I am using `fake-gcs-server` for testing applications that use gcs and utilizing https://github.com/fsouza/fake-gcs-server. However, I can't find a way to use it with polars.
I was previously using `read_parquet` as a workaround but as of 0.20 this is no longer possible as we cannot use fsspec urls any more.

Is there any recommended solution for this?  Or is this just missing functionality in `object_store`?

The previous workflow is to run:

```
docker run -d --name fake-gcs-server -p 127.0.0.1:9090:9090 -v ${PWD}/examples/data:/data fsouza/fake-gcs-server -scheme http -port 9090 -external-url http://127.0.0.1:9090
```

and then either set the environment variable STORAGE_EMULATOR_HOST or just configure the python fsspec client to use this emulator url.

**Comment by ritchie46** [comment]
I am not sure. This might be best requested upstream at object-store. Can you mention this issue here, so we can track it?

**Comment by daviskirk** [comment]
So unfortunately I can't get it to work as documented in https://github.com/apache/arrow-rs/issues/5263. That said I can't say why it isn't working so it might help anyone that is trying to figure out the same problem (and feel free to tell me if I was just doing something stupid if anyone does get it to work)

**Comment by daviskirk** [comment]
Solution is documented in https://github.com/apache/arrow-rs/issues/5263
