### ISSUE TITLE
use_jemalloc is missing

### ISSUE THREAD

**Issue by yurivict** [pola-rs/polars#13095]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

n/a

### Issue description

Currently ```use_mimalloc``` defines what allocation will be used.
When ```use_mimalloc=false``` - jemalloc is used, and when ```use_mimalloc=true``` - mimalloc is used.

It doesn't make sense that ```use_mimalloc``` drives memory allocator selection, because there could be other choices for a memory allocator library.

System allocator is always available, tcmalloc is also also potentially available. There should be corresponding "use_xx" build options for them.

### Expected behavior

It would make more sense to have separate build option use_jemalloc/use_mimalloc/use_system_malloc/etc.

### Installed versions

n/a

**Comment by ritchie46** [comment]
This is not a bug. Do you have feature request? What is your issue with jemalloc? Can you explain why you want somehting different? It is not in our interest to expose every memory allocator under the sun.

**Comment by yurivict** [comment]
My understanding is that jemalloc is a copy of what the FreeBSD system memory allocator is.
jemalloc conflicts with the system memory allocator in FreeBSD and prints some error message.
jemalloc is routinely disabled on FreeBSD when some packages attempt to use it because it doesn't make sense to use it.
Same should be done with polars.

**Comment by yurivict** [comment]
It also doesn't make sense that mimalloc has to be used when jemalloc is disabled, because only one switch (```use_mimalloc```) drives this.

I am not suggesting to expose all possible memory allocators, but it would make a lot more sense to have separate switches ```use_mimalloc``` and ```use_jemalloc```, so that each library would be able to be enabled separately, or system allocator would be used otherwise.

**Comment by stinodego** [comment]
We use either mimalloc or jemalloc. If you want to use a different allocator, please open a feature request and explain why.

**Comment by yurivict** [comment]
I want to switch to mimalloc. How can I do it?

**Comment by stinodego** [comment]
`polars-lts-cpu` uses mimalloc. Or you can compile from source and enable the right flags.
