### ISSUE TITLE
Difference between `.to_dicts()` and `.rows(named=True)`

### ISSUE THREAD

**Issue by gusutabopb** [pola-rs/polars#13097]
### Description

Given the DataFrame below, both `df.to_dicts()` and `df.rows(named=True)` produce the exact same output.

```python
df = pl.DataFrame(
    {
        "x": ["a", "b", "b", "a"],
        "y": [1, 2, 3, 4],
        "z": [0, 3, 6, 9],
    }
)

df.rows(named=True)  # or df.to_dicts()
```

```
[{'x': 'a', 'y': 1, 'z': 0},
 {'x': 'b', 'y': 2, 'z': 3},
 {'x': 'b', 'y': 3, 'z': 6},
 {'x': 'a', 'y': 4, 'z': 9}]
```

However, the implementations ([`to_dicts`](https://github.com/pola-rs/polars/blob/py-0.20.0/py-polars/polars/dataframe/frame.py#L2029-L2047), [`rows`](https://github.com/pola-rs/polars/blob/py-0.20.0/py-polars/polars/dataframe/frame.py#L9480-L9539)) look slightly different. ~~From some very simple benchmarks, it looks like `.rows(named=True)` is about 6-7x faster than `.to_dicts()`~~.

Why are there two ways to achieve the exact same thing? Is one approach more efficient than the other?
It'd be nice to have the differences documented and/or the deprecating one of the two approaches.

### Link

- https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.rows.html#polars.DataFrame.rows
- https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.to_dicts.html#polars.DataFrame.to_dicts

**Comment by alexander-beedie** [comment]
@gusutabopb: It's a convenience method; internally it calls the `iter_rows(named=True)` method.

@stinodego: I can dig into the performance diff unless you're about to jump on it (`iter_rows` didn't used to be that much slower than `rows` - will confirm/repro and see if something changed 🤔)

**Comment by gusutabopb** [comment]
Hi @alexander-beedie - please disregard my comments about performance. Looks my micro benchmarking was a bit too "micro". 

My main point here is to know whether there's any practical difference between the two methods (and if so get it documented). In case there's not difference I believe it'd be better to have just deprecate one of the methods to have a cleaner API.

<details>
<summary>For full disclosure though, here's how I ran the benchmarks</summary>

### Environment:
 - Ubuntu 22.04 VM
 - 32GB RAM
 - 12 cores
 - Intel Xeon Silver 4316 CPU @ 2.30GHz
 - Polars 0.20
 - Python 3.10


### Original benchmark




Using the sample dataframe from `rows` documentation:

```python
df = pl.DataFrame(
    {
        "x": ["a", "b", "b", "a"],
        "y": [1, 2, 3, 4],
        "z": [0, 3, 6, 9],
    }
)
```

And Jupyter's `%timeit`:

```
%timeit df.rows(named=True)
# 30.9 µs ± 55.5 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

```
%timeit df.to_dicts()
# 141 µs ± 639 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

From the above, it looks like there's a 6-7x performance difference.

### Slightly better benchmark

However, trying again with a more realistic DataFrame (sorry - can't share the data) with the following characteristics:

- Shape: `(57014, 10)`
- Schema
  - Col0: Datetime(time_unit='ns', time_zone=None)
  - Col1: Utf8
  - Col2: Utf8
  - Col3: Int64
  - Col4: Utf8
  - Col5: Float64
  - Col6: Float64
  - Col7: Float64
  - Col8: Utf8
  - Col9: Utf8

The performance differences were gone:

```
%timeit df.rows(named=True)
# 188 ms ± 2.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

```
%timeit df.to_dicts()
# 176 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

**Comment by alexander-beedie** [comment]
> However, trying again with a more realistic DataFrame (sorry - can't share the data) with the following characteristics:

The schema and the size is totally sufficient, thanks for that ;)

**Comment by alexander-beedie** [comment]
Ok, good news -  I can explain why one of those paths was slower, and also why the full schema took a slightly _different_ path causing `rows` and `to_dicts` to  benchmark the same. Even better, I can make a modest update that will result in _all_ paths running with the fastest timings. PR incoming...

**Comment by stinodego** [comment]
Regarding the duplication in the API:

There is something to be said for `to_dicts` in that it mirrors `from_dicts`.
There is also something to be said for `rows(named=True)`, as it mirrors the API of `iter_rows` and `row`.

So I think keeping the current API is fine, but let's dispatch `rows(named=True)` to `from_dicts` and have the implementation there be the one with the best performance characteristics.
