### ISSUE TITLE
Implement GPU support

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [pola-rs/polars#13111]
### Description

@stinodego closed the previous [issue](https://github.com/pola-rs/polars/issues/5978) that mentioned GPU support and said there were no plans to support GPU in the future but was open to a feature request. Seeing as author of the previous issue didn't open a new feature request, I'm doing so instead. 

We're using Pandas for a data processing pipeline and there were long-standing plans to migrate to Polars as our data volume is expected to increase in Q2-Q3 of 2024.  Seeing as CuDF is available, it's unlikely that we'll go ahead with those original plans. 

I'm still a proponent of Polars, as there are obvious improvements over Pandas. However, the migration doesn't make sense now that RapidsAI offer comparable/ faster speeds with no code change unless Polars also offers GPU support.  

In the long run, it's difficult envisage any widely used data processing library which do not offer GPU accelerated compute.  Namely if the speed problem can be solved by buying relatively inexpensive consumer-grade hardware, spending developers' time (considerably more expensive) on rewriting code would be a less attractive option.  Hence this feature request.

**Comment by avimallu** [comment]
Right now, to get the performance that's mentioned in the Rapids cuDF blog post, you seem to require the Nvidia Grace Hopper chip, which costs above USD 10,000 (IIRC). See [this link](https://developer.nvidia.com/blog/rapids-cudf-accelerates-pandas-nearly-150x-with-zero-code-changes/)

So unless you're okay with that upfront added cost, I think the migration of Pandas to Polars would be the more economically feasible option.

Planning 10 years ahead is great, and I'm pretty sure nobody can really predict with high accuracy what the state of affairs will be then, but it doesn't seem prudent to wait around until then to upgrade your current Pandas based pipeline.

**Comment by stinodego** [comment]
I will repeat my reply to the previous issue here:

We do not have concrete plans to implement ways to leverage the GPU in the near future.

For some context, you can see Ritchie's answer to this question during the EuroSciPy 2023 conference:
 https://youtu.be/GTVm3QyJ-3I?t=3199

I will keep this issue open for further discussion.

**Comment by MarcoGorelli** [comment]
> There are benchmarks online that show ~60x speed up using RTX4080 over the same pandas operations running on intel i9

could you share this please? just tried searching but didn't find it

**Comment by ritchie46** [comment]
GPU support might come. It seems a perfect project for a certain provider of hardware accelerated products. But that's also what it is. A project on itself. The polars project itself will not work on GPU acceleration, but will do its best to enable it.

> I'm still a proponent of Polars, as there are obvious improvements. However, the migration doesn't make sense now that RapidsAI offer comparable/ faster speeds with no code change, unless Polars also offers GPU support.

We'd like to argue that there are benefits IN the code change. ;)

**Comment by wukan1986** [comment]
On consumer-grade GPU,  VRAM is a big problem, and it will be embarrassing if data is large. 

It is more appropriate to use `DSL` in the professional field. Currently in the field of quantitative research, the `WorldQuant Alpha101 Formula` is a classic example. Some examples are as follows

```
Alpha#002   (-1 * correlation(rank(delta(log(volume), 2)), rank(((close - open) / open)), 6))
Alpha#028    scale(((correlation(adv20, low, 5) + ((high + low) / 2)) - close))
Alpha#101   ((close - open) / ((high - low) + .001))
```

Formulas are suitable for quickly verifying ideas, and it requires tools to translate into polars or pandas, so I developed a translation tool.
You can refer to it to implement the `cudf` version, or use `cudf.pandas` directly

https://github.com/wukan1986/expr_codegen

You can try it online
https://exprcodegen.streamlit.app/

Sorry, my English is poor, so the comments and documents are in Chinese. You can use the translation tool provided by your browser to read them.

**Comment by rupurt** [comment]
Apple silicon changes the game here. The unified mememory model is how folks can run large AI models on consumer hardware for inference. Check out the metal framework. I feel like any query engine that isn’t leveraging that power will be obsolete in 2025/26…

**Comment by feynon** [comment]
> On consumer-grade GPU,  VRAM is a big problem, and it will be embarrassing if data is large. 
> 
> It is more appropriate to use `DSL` in the professional field. Currently in the field of quantitative research, the `WorldQuant Alpha101 Formula` is a classic example. Some examples are as follows
> 
> ```
> Alpha#002   (-1 * correlation(rank(delta(log(volume), 2)), rank(((close - open) / open)), 6))
> Alpha#028    scale(((correlation(adv20, low, 5) + ((high + low) / 2)) - close))
> Alpha#101   ((close - open) / ((high - low) + .001))
> ```
> 
> Formulas are suitable for quickly verifying ideas, and it requires tools to translate into polars or pandas, so I developed a translation tool.
> 
> https://github.com/wukan1986/expr_codegen
> You can refer to it to implement the `cudf` version, or use `cudf.pandas` directly
> 
> 
> You can try it online
> https://exprcodegen.streamlit.app/
> 
> Sorry, my English is poor, so the comments and documents are in Chinese. You can use the translation tool provided by your browser to read them.

There's a paper I read where they (researchers at Apple) demonstrated an alternative approach to use flash rather than RAM memory: https://arxiv.org/abs/2312.11514
