### ISSUE TITLE
.pivot panics when using a column containing Structs

### ISSUE THREAD

**Issue by SebastienFries** [pola-rs/polars#13120]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "index": [1, 2, 3, 1, 2, 3],
        "item_type": ["a", "a", "a", "b", "b", "b"],
        "item_id": [123, 123, 123, 456, 456, 456],
        "values": [4, 5, 6, 7, 8, 9],
    }
)
df = df.with_columns(pl.struct(["item_type", "item_id"]).alias("columns")).drop("item_type", "item_id")
df = df.pivot(index="index", columns="columns", values="values")  # this panics
```

### Log output

```shell
run StackExec
run UdfExec
thread '<unnamed>' panicked at crates/polars-ops/src/frame/pivot/positioning.rs:145:25:
assertion failed: idx < buf.len()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
9.27s - Error processing internal command.
Traceback (most recent call last):
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1783, in process_internal_commands
    int_cmd.do_it(self)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 528, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1166, in internal_evaluate_expression_json
    eval_result = pydevd_vars.evaluate_expression(py_db, frame, expression, is_exec=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 370, in new_func
    return _run_with_unblock_threads(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 334, in _run_with_unblock_threads
    return _run_with_interrupt_thread(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 305, in _run_with_interrupt_thread
    return original_func(py_db, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 580, in evaluate_expression
    ret = eval_in_context(expression, updated_globals, updated_locals, py_db)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 268, in eval_in_context
    result = eval(compiled, global_vars, local_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/home/ubuntu/repos/polars/py-polars/polars/dataframe/frame.py", line 7322, in pivot
    self._df.pivot_expr(
pyo3_runtime.PanicException: assertion failed: idx < buf.len()
```

### Issue description

I am not expecting the pivot operation to panic here - see section below for the output I would expect.
I've done some debugging to try to pinpoint where the error comes from:

1 - Rust ```assertion failed: idx < buf.len()``` panic occurs here:
https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/frame/pivot/positioning.rs#L145

2 - ```buf``` is initialised here:
https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/frame/pivot/positioning.rs#L110

and inspection of the variables when running the code using the reproducible example's dataframe shows that on this line```n_cols=2``` and ```n_rows=3``` giving ```buf.len()=6```, which are all correct.

3 - The issue comes from ```col_locations``` here:
https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/frame/pivot/positioning.rs#L131
 which instead of being```[0,0,0,1,1,1]``` as I would expect it to be based on the content of the column ```columns``` of the reproducible examples's dataframe, incorrectly is ```[0,1,2,3,4,5]```. 
This makes ```col_idx``` take values it shouldn't be taking and induces ```idx``` to be larger than ```buf.len()``` in this for loop here:
https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/frame/pivot/positioning.rs#L136-L144

4 - ```col_locations``` is created here:
https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/frame/pivot/positioning.rs#L216-L219
where each ```v``` in the iteration seems distinct -which shouldn't be the case, there are 6 elements iterated over, which should take only 2 distinct values- and thus considered a new entry of ```col_to_idx``` at each iteration yielding the incorrect ```col_locations``` with value ```[0,1,2,3,4,5]```. This problem is not occurring when the column ```columns``` contains eg integers or &str instead of structs.

I attempted to look into how ```column_agg_physical``` is created using ```to_physical_repr``` and what's happening in ```phys_iter``` but I am new to rust and polars and I felt like I was reaching the limit of my debugging setup (VSCode + CodeLLDB which is not so great to inspect variables).

________________________________________________________

PS: Just before I forget to mention it in case it turns out important: when initially running into this bug with my actual data, the pivot operation did not systematically panic but the bug seemed to arise at random. With the example above the bug arises 'almost' systematically, but still happened that running in a notebook, the pivot operation did not panic but returned instead an incorrect result:

<img width="660" alt="image" src="https://github.com/pola-rs/polars/assets/152778559/4f872f6e-c44b-499d-8b31-b983c54a8753">

PS2: the documentation of ```to_physical_repr``` details the behaviour for all inputs types except for Struct
https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/series/mod.rs#L439-L440.

PS3: To give some context as to why I have been trying to use structs with pivot: coming from pandas, I was quite a keen user of multiindexes, one of the example usage being like the below which I was somehow trying to replicate in polars - pivotting the dataframe with some (date) index in rows and applying eg ffill or whatever time-related transformation to each column:

<img width="441" alt="image" src="https://github.com/pola-rs/polars/assets/152778559/6e4ed0c2-c52c-456e-b711-1bd1caa24c30">

### Expected behavior

<img width="162" alt="image" src="https://github.com/pola-rs/polars/assets/152778559/6bc4dfab-5ecb-4f60-87a8-5c35e6322917">

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.0
Index type:           UInt32
Platform:             Linux-6.2.0-1016-aws-x86_64-with-glibc2.35
Python:               3.11.6 (main, Oct 25 2023, 13:46:41) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I've been unable to reproduce a panic from your example, although the output differs from your expected result.

```python
shape: (3, 3)
┌───────┬───────────┬───────────┐
│ index ┆ {"a",123} ┆ {"b",456} │
│ ---   ┆ ---       ┆ ---       │
│ i64   ┆ i64       ┆ i64       │
╞═══════╪═══════════╪═══════════╡
│ 1     ┆ 4         ┆ null      │
│ 2     ┆ null      ┆ 5         │
│ 3     ┆ null      ┆ null      │
└───────┴───────────┴───────────┘
```

**Comment by SebastienFries** [comment]
> I've been unable to reproduce a panic from your example, although the output differs from your expected result.
> 
> ```python
> shape: (3, 3)
> ┌───────┬───────────┬───────────┐
> │ index ┆ {"a",123} ┆ {"b",456} │
> │ ---   ┆ ---       ┆ ---       │
> │ i64   ┆ i64       ┆ i64       │
> ╞═══════╪═══════════╪═══════════╡
> │ 1     ┆ 4         ┆ null      │
> │ 2     ┆ null      ┆ 5         │
> │ 3     ┆ null      ┆ null      │
> └───────┴───────────┴───────────┘
> ```

You do however reproduce the behaviour I talk about in my "PS:" point in the issue description, which output definitely looks wrong. Did you get that within a notebook? That's how I got it.

**Comment by cmdlineluser** [comment]
I'm just using an interactive `ptipython` shell session.

The output is wrong, if we manually `.hash()` the struct for example - they are correctly grouped:

```python
(df.select("index", "values", columns=pl.struct("item_type", "item_id"))
   .with_columns(pl.col("columns").hash())
   .pivot(index="index", columns="columns", values="values")  
)

# shape: (3, 3)
# ┌───────┬─────────────────────┬─────────────────────┐
# │ index ┆ 8674754049853045206 ┆ 4753434814725995468 │
# │ ---   ┆ ---                 ┆ ---                 │
# │ i64   ┆ i64                 ┆ i64                 │
# ╞═══════╪═════════════════════╪═════════════════════╡
# │ 1     ┆ 4                   ┆ 7                   │
# │ 2     ┆ 5                   ┆ 8                   │
# │ 3     ┆ 6                   ┆ 9                   │
# └───────┴─────────────────────┴─────────────────────┘
```

**Comment by SebastienFries** [comment]
Sure, if you replace the Struct column with whatever other primitive type identifying uniquely each struct value, it will work. The problem occurs because Structs are not properly handled somewhere in the rust code, which I tried to pinpoint in the issue description.

**Comment by cmdlineluser** [comment]
@ritchie46 It panics with a non-release build.

**Comment by stinodego** [comment]
I do get a panic with the original xample.

**Comment by MarcoGorelli** [comment]
came across this on the way towards https://github.com/pola-rs/polars/issues/11663, will try to tackle it
