### ISSUE TITLE
Add `offset` parameter to `gather_every`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#13133]
### Description

I have a use case where I have a frame of three interleaved sets that I need to de-interleave. I currently have to filter based on row number % 3, which is fine, but there is a `gather_every` which would be useful were it able to perform an offset as well.

This would be applicable frame, lazyframe, series, and expr.

```python
df.select(
    pl.col("a").gather_every(3, offset=0).alias("a"),  # rows 0, 3, 6, ...
    pl.col("a").gather_every(3, offset=1).alias("b"),  # rows 1, 4, 7, ...
    pl.col("a").gather_every(4, offset=2).alias("c"),  # rows 2, 5, 8, ...
)
```

**Comment by deanm0000** [comment]
You can get that effect with gather and int_range like this

```
df.select(
    a=pl.col('a').gather(pl.int_range(0,pl.count(),3)),
    b=pl.col('a').gather(pl.int_range(1,pl.count(),3)),
    c=pl.col('a').gather(pl.int_range(2,pl.count(),3))
    )
```

The first argument of your `gather_every` corresponds to the `step` and your `offset` is the `start` of int_range.
