### ISSUE TITLE
Correct type hinting of polars datatypes in pydantic basemodels

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#13136]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I found the following dtype type-hinting behaviour a bit confusing. I'm trying to add a field of type `pl.Float64` into a pydantic model, and am running into issues:

```python
import polars as pl
from polars.datatypes import DataTypeClass

dtype1: pl.DataType       = pl.Float64() # Type "PolarsDataType" cannot be assigned to type "DataType"
dtype2: DataTypeClass     = pl.Float64() # Type "PolarsDataType" cannot be assigned to type "DataTypeClass"
dtype3: pl.PolarsDataType = pl.Float64() # works
```

When I try to use the third option as a type hint in pydantic v2.5.2, it doesn't work:

```python
from pydantic import BaseModel
import polars as pl

class Foo(BaseModel, arbitrary_types_allowed=True):
    dtype: pl.DataType = pl.Float64() # uses the incorrect type hint according to pyright, but works

class Bar(BaseModel, arbitrary_types_allowed=True):
    dtype: pl.PolarsDataType = pl.Float64() # uses the correct type hint, but fails

Foo() # works
Bar() # fails
```

I think this is due to `PolarsDataType` being a type alias, and I'd rather use the type hint in `Foo` , since it feels more correct and appropriate. Is the pyright message in `Foo` due to a bug in polars?

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             macOS-14.1.2-arm64-arm-64bit
Python:               3.11.4 (main, Sep 17 2023, 16:35:04) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.13.0
fsspec:               2023.12.2
gevent:               23.9.1
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              10.0.1
pydantic:             2.5.2
pyiceberg:            0.5.1
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by stinodego** [comment]
Did this pop up with the `0.20` release or did it also happen before?

In the first example, `mypy` only complains about `dtype2` which is correct, since you passed an instantiated object. It seems pyright has a bug by not recognizing `dtype1` as correct.

`mypy` does not complain about any of the pydantic code. Though it seems pydantic does not allow random type aliases as its types, which makes sense. Use `pl.DataType` and use the new instantiated types.

I would recommend opening an issue with the pyright repo.

**Comment by thomasaarholt** [comment]
I somehow made a mistake. When I now check the above code, `pl.DataType` works as expected for both regular type hinting and pydantic. I think I somehow had a environment with polars 0.19 running, and _that_ had the above issues. (I must have run `pl.show_versions` in a separate environment somehow...)
