### ISSUE TITLE
Add `count` method on DataFrame/LazyFrame

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13145]
### Description

Until recently, this would have just returned the frame height, which is the same for each column, so the method did not make much sense. However, now that `count` ignores null values, it makes sense for it to be added as a frame method to complement other aggregations.

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3], "b": ["x", "y", None]})
df.count() 
```
```
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ u32 ┆ u32 │
╞═════╪═════╡
│ 3   ┆ 2   │
└─────┴─────┘
```

For reference, we already have `null_count`, `max`, `mean`, etc. as aggregations.
https://pola-rs.github.io/polars/docs/python/dev/reference/lazyframe/aggregation.html

I think this would simply be a `df.select(pl.all().count())` on the background (implemented on the Rust LazyFrame).

**Comment by stinodego** [comment]
@TNieuwdorp has expressed interested in picking up this issue so I'm assigning it to him.

**Comment by deanm0000** [comment]
Can we have a pl.cum_count expression since pl.first().cum_count() is dependent on the data too please

**Comment by TNieuwdorp** [comment]
> Can we have a pl.cum_count expression since pl.first().cum_count() is dependent on the data too please

I don't think it's relevant to this issue, maybe it'd help to open up a new issue according to the template for that? :)

**Comment by deanm0000** [comment]
Actually there's another request that I forgot about for row_count so just ignore me
