### ISSUE TITLE
Categorical Series.replace() broken

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#13164]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series(["a", "b"], dtype=pl.Categorical)
print(s.replace({"a": "c"}))

"""
shape: (2,)
Series: '' [str]
[
	"a"
	"b"
]
"""
```

### Issue description

Seems to be a regression since 0.20.0.

### Expected behavior

"a" gets replaced by "c".

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.22621-SP0
Python:               3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.1.0
pyarrow:              11.0.0
pydantic:             2.1.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
I'm going to have to look into what happens here exactly. But you should realize that in the newly implemented `replace` function, what you are doing is replacing a string by a string, in a column that is not a string column.

In the meantime, you can use this:

```python
import polars as pl

pl.enable_string_cache()

s = pl.Series(["a", "b"], dtype=pl.Categorical)
r = s.replace(
    old=pl.lit("a", dtype=pl.Categorical),
    new=pl.lit("c", dtype=pl.Categorical),
)
print(r)
```

**Comment by stinodego** [comment]
Yeah, we have to cast `old` to the dtype of the input, just like we do in the 'normal' path. I have a PR in the making :)

**Comment by s-banach** [comment]
If `x` and `y` are both categorical Series, would you ever consider a feature like `x.cast(y.dtype)` as a way of explicitly re-encoding `x` to have the same categorical mapping as `y`?

**Comment by stinodego** [comment]
I will update this to raise an error.

Previous to `0.20`, this worked behind the scenes by casting to a string and then casting back. You can still do the same by manually casting the input series to a string before calling `replace`.

I am 'repurposing' this issue to update the logic to support replacing categorical columns instead of raising an error. I think this should be possible with the new updates to Categoricals by @c-peters .

**Comment by stinodego** [comment]
Actually I'll close this and open a new issue for supporting this internal cast.
