### ISSUE TITLE
Enum fill_null behavior

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#13165]
### Description

For example, I just tested
```python
import polars as pl

dtype = pl.Enum(["a", "b"])
s = pl.Series(["a", "b"], dtype=dtype)
s.fill_null("b").dtype # Categorical(ordering='physical')
```

I thought the output might still be `Enum(["a", "b"])` .

I was also sort of hoping that `s.fill_null("c").dtype` would be `Enum(["a", "b", "c"])`, but maybe that's a separate can of worms.

**Comment by c-peters** [comment]
Thanks, this seems to be a bug in the round trip from the underlying physical I'll have a look

**Comment by c-peters** [comment]
Enum types are meant to be strict and fixed from a user perspective, we don't want to support 'automatic' conversion / appending at the moment.

You could explicitly add them with
```
s.cast(pl.Enum(["a","b","c"])).fill_null("c")
```

**Comment by s-banach** [comment]
> Enum types are meant to be strict and fixed from a user perspective, we don't want to support 'automatic' conversion / appending at the moment.

Should `s.fill_null("c")` raise an error like in pandas? Force users to explicitly recast?

No strong opinion, I just hope you can make all the hard decisions and stabilize Enums before 1.0 so I can build on top of it!
Thanks.

**Comment by c-peters** [comment]
Yes, Enums are fixed and should not automatically append new elements.
