### ISSUE TITLE
Over None gives None instead of str

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#13173]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(data = {"color": ["yellow", "yellow"], "color2": [None, "light"], "val": ["2", "3"]})

df = df.with_columns(pl.min("val").over(["color", "color2"]).alias("min_val_per_color"))
print(df)
```

### Issue description

When the column `"val"` is of type `pl.Utf8`, it will set the aggregated value to `None` if any value in the group is `None. You get the additional column "min_val_per_color: [None, 3]".

### Expected behavior

I would expect the dataframe to get the additional column "min_val_per_color: [2, 3]". This is also what happens when the datatype of "val" is numeric.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
None
```

</details>

**Comment by cmdlineluser** [comment]
This last worked in `0.19.19`

Seems to have changed after https://github.com/pola-rs/polars/commit/34330eccf22fcde8e46d2aa7d564d9d65ef644bc
