### ISSUE TITLE
The Python read/scan_parquet api docs reference an incorrect object_store version

### ISSUE THREAD

**Issue by robvanmieghem** [pola-rs/polars#13175]
### Description

The storage_options doc links to version 0.7.0 of object_store while polars uses 0.8.
Instead of putting a fixed version in there, `latest` might be better. 

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_parquet.html#polars.read_parquet

**Comment by ritchie46** [comment]
Can you open a PR?

**Comment by robvanmieghem** [comment]
Just did so.
