### ISSUE TITLE
Panic when writing parquet after vstack involving null column

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#13170]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let row_count = 400_000;
    let nulls = Series::new_null("nulls", row_count);
    let ints = Series::new("ints", vec![8; row_count]);
    let df = DataFrame::new(vec![nulls, ints]).unwrap();

    let mut df = df.vstack(&df).unwrap();
    df.align_chunks();

    let writer = ParquetWriter::new(vec![]);
    writer.finish(&mut df).unwrap();
}
```

### Log output

```shell
thread 'main' panicked at /Users/bytenybbler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.35.4/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

Conditions required for the panic to occur:
- At least one column of the `DataFrame` must have a `DataType` of `Null`.
- At least one column of the `DataFrame` must **not** have a `DataType` of `Null`.
- The `DataFrame` must be involved in a `vstack` operation.
- The `DataFrame` must be written to parquet after the `vstack`.
- The number of rows in the `DataFrame` must be sufficiently large. In the case of the example above, the panic starts to manifest once there are a few hundred thousand rows.

It doesn't seem to make a difference whether `DataFrame::align_chunks` is called or not.

### Expected behavior

Polars shouldn't panic when writing a `vstack`ed `DataFrame` to parquet when a `Null` column is involved.

### Installed versions

<details>

polars = { version = "0.35.4", features = ["parquet"] }

</details>

**Comment by cmdlineluser** [comment]
Reproduced in Python:

```python
import polars as pl
import tempfile

f = tempfile.NamedTemporaryFile()

df = pl.DataFrame({"nulls": [None] * 400_000, "ints": [8] * 400_000})
df.vstack(df).write_parquet(f.name)

# thread '<unnamed>' panicked at /Users/user/git/polars/crates/polars-arrow/src/chunk.rs:20:31:
# called `Result::unwrap()` on an `Err` value: 
#    ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
```
