### ISSUE TITLE
Rewrite DataFrame.describe in Rust

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#13199]
### Description

Currently this function is written in Python, but I think it is useful outside of Python as well, so if there is no reason to write it in Python, it is worth moving it to the Rust side.
It would be useful to have this function available in polars CLI, for example.

**Comment by stinodego** [comment]
`describe` is a convenience function - it's nice to have in interactive sessions like Python notebooks. It doesn't make much sense in Rust.

I think we actually had something like it in Rust, but Ritchie recently removed it. So we're not planning to add it for now.

**Comment by nazq** [comment]
I needed the same so created this gist for anyone to use https://gist.github.com/nazq/f3fc6e6b15c895fb8b474013c4932d62
