### ISSUE TITLE
Replace with dictionary only consisting of None

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#13204]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl


df = pl.DataFrame(data={"color": ["red"]})

print(df.with_columns([pl.col("color").replace({None: 0})]))

```

### Issue description

When the dictionary in `.replace()` only contains `None` as a key, one will get the error 

```
polars.exceptions.InvalidOperationError: is_in operation not supported for dtypes `str` and `null`
```

As soon as you extend the dictionary to include one non-null key, the code runs without an error, e.g. when running

```python
import polars as pl


df = pl.DataFrame(data={"color": ["red"]})

print(df.with_columns([pl.col("color").replace({"green": 1, None: 0})]))

```

### Expected behavior

I would expect the code to not raise an error as it was the case in `polars` versions `< 0.20.x`.

### Installed versions

<details>

--------Version info---------
Polars:               0.20.0
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.11.7 | packaged by conda-forge | (main, Dec 15 2023, 08:41:36) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              12.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.49
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
None
```

</details>

**Comment by stinodego** [comment]
Thanks for opening an issue! This has been fixed in https://github.com/pola-rs/polars/pull/13176 and will work as expected in the next release.
