### ISSUE TITLE
sink_csv sometimes hangs

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#13202]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1]})
df.lazy().sink_csv("foo.csv")
df.lazy().sink_csv("foo.csv")
```

### Log output

```shell
RUN STREAMING PIPELINE
df -> csv_sink
RefCell { value: [] }
```

### Issue description

I don't know the exact conditions, but if I run `sink_csv` on the same file twice in a row, there is a high probability that it will hang.

This was originally discovered in pola-rs/r-polars#601 (so it's an issue on the Rust side)

### Expected behavior

Python sessions should not hang.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It doesn't appear to reproduce with `POLARS_MAX_THREADS=1` 

I think #12918 is the same issue which still reproduces for me.
