### ISSUE TITLE
Add DataType method for checking categorical data types (Categorical/Enum) e.g. `is_categorical()`

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#13203]
### Description

Ran into a footgun when trying to check if a dtype is already dictionary-encoded:
https://stackoverflow.com/questions/77698828/difference-between-x-in-list-vs-x-in-dict-and-x-in-set-where-x-is-a-pol/

Maybe `s.dtype.is_dictionary()` (or `is_dictionary_encoded`, or whatever it should be named) would help people avoid my mistake.

**Comment by stinodego** [comment]
We have decided not to add `dtype.is_categorical()` and similar methods, as this does not translate well to nested types.

You can use `s.dtype == pl.Categorical` for checking if something is a categorical.

**Comment by stinodego** [comment]
We have decided against this for now. Just use `dtype in (pl.Categorical, pl.Enum)`.
