### ISSUE TITLE
Implement `median` for the list namespace

### ISSUE THREAD

**Issue by FriedLabJHU** [pola-rs/polars#13211]
### Description

The `median` expression function exists in the rust implementation of `PyExpr` but not in the Python implementation.

**Comment by stinodego** [comment]
`Expr.median` exists and is exposed correctly.
`Expr.list.median` does not exist - neither on the Python nor the Rust side.

I'll take this as a feature request to implement `list.median`, which is a fair request.

**Comment by stinodego** [comment]
Actually this is a duplicate of #12163, so I'll close this.
