### ISSUE TITLE
Make `replace` work for local Categoricals

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13215]
Following up on #13164

In `replace`, we cast the `old` input to the type of the expression. This currently doesn't work for local Categoricals, but I think it theoretically _could_ work. Example:

```python
s = pl.Series(["a", "b"], dtype=pl.Categorical)
s.replace("a", "c", default=None)
# InvalidOperationError: casting to a non-enum variant with rev map is not supported for the user
```

It fails because it's trying to strict cast `lit("a")` to the original series dtype (Categorical). Can we allow this somehow?
Expected output would be:
```python
expected = pl.Series(["c", None], dtype=pl.Utf8)
```

Next step would be to allow replacements _by_ a local categorical and returning a categorical, avoiding strings altogether:

```python
s = pl.Series(["a", "b"], dtype=pl.Categorical)
old = pl.Series(["a"])  # gets cast to the dtype of `s`
new = pl.Series(["c"], dtype=pl.Categorical)

r = s.replace(old, new)

expected = pl.Series(["c", "b"], dtype=pl.Categorical)  # supertype of `s` and `new` is still a Categorical
```

@c-peters would you mind taking a look at this?

**Comment by c-peters** [comment]
Sure!
