### ISSUE TITLE
Split out the `.dt` namespace, with a Duration one?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#13210]
### Description

This came up in conversation yesterday in the dataframe consortium call - the `.dt` space contains methods which are either available for dates, datetimes, times, or durations.

Dates, datetimes, and times, they all have some overlap. E.g. `.second` is supported on all three, but `.dt.dst_offset` only for tz-aware datetimes.

Duration methods, on the other hand, don't have any real overlap? Let's take a look

- truncate: date/datetime
- round: date/datetime
- combine: date/datetime
- to_string: date/datetime/time
- strftime: date/datetime/time
- year: date/datetime
- is_leap_year: date/datetime
- iso_year: date/datetime
- quarter: date/datetime
- month: date/datetime
- week: date/datetime
- weekday: date/datetime
- day: date/datetime
- ordinal_day: date/datetime
- time: datetime/time
- date: datetime/date
- datetime: datetime
- hour: datetime/time
- minute: datetime/time
- second: datetime/time
- millisecond: datetime/time
- microsecond: datetime/time
- nanosecond: datetime/time
- epoch: datetime/date/duration (but, see https://github.com/pola-rs/polars/issues/13208)
- timestamp: datetime/date/duration
- with_time_unit: datetime/duration
- cast_time_unit: datetime
- convert_time_zone: datetime
- replace_time_zone: datetime
- total_days: duration
- total_hours: duration
- total_minutes: duration
- total_seconds: duration
- total_milliseconds: duration
- total_microseconds: duration
- total_nanoseconds: duration
- offset_by: datetime, date
- month_start: date, datetime
- month_end: date, datetime
- base_utc_offset: datetime
- dst_offset: datetime
- days: duration
- hours: duration
- minutes: duration
- seconds: duration
- milliseconds: duration
- microseconds: duration
- nanoseconds: duration

There's practically no overlap between Duration and the rest. The only exceptions are:
- `epoch`, though I think this one should raise for Duration: https://github.com/pola-rs/polars/issues/13208
- `timestamp` - not sure what the difference with `epoch` is meant to be?
- `with_time_unit` - this one's only meant for correcting wrong units, and I think it may be worth deprecating it https://github.com/pola-rs/polars/issues/13209

Given the almost complete separation, is it ideal that have all of these under the same `.dt` namespace?

Not totally sure on the solution (maybe `.td`, short for the corresponding Python stlib equivalent `timedelta`?), I just wanted to bring it up because the Polars API looks really solid now but this is one thing that's arguably a little wart

**Comment by deanm0000** [comment]
I vote to leave as is. Durations are inextricably linked to times, the former doesn't have any meaning without the latter. For me, if I'm ever dealing with "hours" (for example) without it being the result of time arithmetic then I just keep it as a numeric anyway. As a tangent, I sometimes try to do `.dt.strptime` instead of `.str.strptime` which is totally my mistake but I think if there was dt and td as separate things then I, and maybe others, would get them mixed up even though I understand the logic of their proposed separation.

**Comment by MarcoGorelli** [comment]
>  if there was dt and td as separate things then I, and maybe others, would get them mixed up even though I understand the logic of their proposed separation.

yeah true

might just be fine to accept it as a historical pandas decision which now everyone copies, and that's just the way it is, no big deal

leaving open a little in case anyone thinks otherwise, then will close

**Comment by ion-elgreco** [comment]
It could make sense but I don't think `td` would make it readable. To close to `dt`

**Comment by deanm0000** [comment]
My take isn't based on pandas. I was an R data.table guy before polars got me to stop using reticulate and embrace Python. Also, I was just saying "td" as a placeholder, my opinion stands regardless of the new name.

**Comment by MarcoGorelli** [comment]
closing then, the status quo is alright - thanks all!
