### ISSUE TITLE
df.n_unique() should operate column-wise

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13230]
### Description

Currently, `df.n_unique()` gives the total number of unique rows in a DataFrame. This is inconsistent with other aggregation/reduction functions like `df.max()`, `df.mean()`, `df.median()`, `df.min()`, `df.product()`, `df.std()`, `df.sum()`, and `df.var()`, which operate column-wise and aggregate to a single row, rather than a single number. 

That said, the current behavior of `df.n_unique()` is occasionally useful, and could be supported via an optional argument.

**Comment by avimallu** [comment]
I think `df.n_unique()` is just as inconsistent as `df.unique()` if you want to look at it that way. I would most definitely not want the latter to aggregate by column, and `n_unique` is a supplementary function. A similar kind of argument can be made for a few functions that manipulate the DataFrame (`first`, `head`, …).

In addition, `n_unique()` is considered a descriptive function, not aggregate. I think it's fine, and when needed, `df.select(pl.col(x).n_unique() for x in df.columns)` should be used.

**Comment by Wainberg** [comment]
That's a fair point tbh. (Although `df.select(pl.col(x).n_unique() for x in df.columns)` can be done more simply as `df.select(pl.all().n_unique())`.) I'll close this issue.
