### ISSUE TITLE
Support all shape-preserving NumPy/SciPy functions in the expression engine

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13234]
### Description

Currently, you can apply arbitary NumPy/SciPy functions to entire Series or DataFrames. The Series/DataFrame is auto-converted to a NumPy array first:

```python
>>> from scipy.stats import norm
>>> norm.cdf(pl.DataFrame({'a': range(1, 10001)}))
array([[0.84134475],
       [0.97724987],
       [0.9986501 ],
       ...,
       [1.        ],
       [1.        ],
       [1.        ]])
```

You can also apply NumPy **ufuncs** to individual columns via the expression engine:

```python
>>> from scipy.special import ndtr  # a ufunc that's equivalent to norm.cdf
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(ndtr(pl.col.a))  # or pl.col.a.pipe(ndtr)
 a
 0.841345
 0.97725
 0.99865
 0.999968
 …
 1.0
 1.0
 1.0
 1.0
shape: (10_000, 1)
```

However, non-ufuncs aren't supported in the expression engine, even ones that preserve the shape of their inputs:

```python
>>> pl.DataFrame({'a': range(1, 10001)}).with_columns(norm.cdf(pl.col.a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/expr/expr.py", line 997, in pipe
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 2066, in cdf
    x = np.asarray((x - loc)/scale, dtype=dtyp)
                   ~~~~~~~~~^~~~~~
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/expr/expr.py", line 245, in __truediv__
    return self._from_pyexpr(self._pyexpr / self._to_pyexpr(other))
                                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/expr/expr.py", line 133, in _to_pyexpr
    return F.lit(other)._pyexpr
           ^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/functions/lit.py", line 120, in lit
    elif _check_for_numpy(value) and isinstance(value, np.ndarray):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/series/series.py", line 296, in __init__
    self._s = numpy_to_pyseries(
              ^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/utils/_construction.py", line 248, in numpy_to_pyseries
    return PySeries.new_object(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'val': iteration over a 0-d array
```

Supporting this would dramatically improve NumPy/SciPy compatibility!

**Comment by MarcoGorelli** [comment]
You can do it with `map_batches` for now
```python
In [12]: pl.DataFrame({'a': range(1, 10001)}).with_columns(cdf=pl.col.a.map_batches(lambda x: pl.Series(norm.cdf(x))))
Out[12]:
shape: (10_000, 2)
┌───────┬──────────┐
│ a     ┆ cdf      │
│ ---   ┆ ---      │
│ i64   ┆ f64      │
╞═══════╪══════════╡
│ 1     ┆ 0.841345 │
│ 2     ┆ 0.97725  │
│ 3     ┆ 0.99865  │
│ 4     ┆ 0.999968 │
│ …     ┆ …        │
│ 9997  ┆ 1.0      │
│ 9998  ┆ 1.0      │
│ 9999  ┆ 1.0      │
│ 10000 ┆ 1.0      │
└───────┴──────────┘
```

**Comment by Wainberg** [comment]
Agreed, that's a good workaround for now, though it's too verbose to be a good long-term solution. Also, failing to wrap the output with `pl.Series()` leads to some [pretty unintuitive behavior](https://github.com/pola-rs/polars/issues/10766).

**Comment by ritchie46** [comment]
But how would this work? I mean ufuncs are designed to be generic. How can we tell that a function passed is order preserving?

**Comment by Wainberg** [comment]
@ritchie46 I think in general, you'd need to make a Python set containing all the NumPy/SciPy functions that are shape-preserving (take a single input, and return a single output of the same size), and then look up whether the called function is in that set.

But you don't need to be completely exhaustive. For instance, the shape-preserving functions that I'd guess Polars users would want to use most frequently are [functions of probability distributions](https://docs.scipy.org/doc/scipy/reference/stats.html#probability-distributions) (e.g. `norm.pdf`, `bernoulli.cdf`) which are all bound methods of objects inside `scipy.stats._continuous_distns` or `scipy.stats._discrete_distns`. 

All continuous distributions have these shape-preserving methods (sometimes with different keyword arguments instead of loc and scale, but that doesn't matter):
```
pdf(x, c, d, loc=0, scale=1) | Probability density function.
logpdf(x, c, d, loc=0, scale=1) | Log of the probability density function.
cdf(x, c, d, loc=0, scale=1) | Cumulative distribution function.
logcdf(x, c, d, loc=0, scale=1) | Log of the cumulative distribution function.
sf(x, c, d, loc=0, scale=1) | Survival function (also defined as 1 - cdf, but sf is sometimes more accurate).
logsf(x, c, d, loc=0, scale=1) | Log of the survival function.
ppf(q, c, d, loc=0, scale=1) | Percent point function (inverse of cdf — percentiles).
isf(q, c, d, loc=0, scale=1) | Inverse survival function (inverse of sf).
```
All discrete distributions have the same ones, except that `pdf` and `logpdf` are called `pmf` and `logpmf`.

So supporting specific categories of commonly-used functions could be a good place to start. I would be happy to submit a pull request once there's agreement on which functions to support.

**Comment by ritchie46** [comment]
I don't see us making a mapping for any function under the sun. It should be either something generic like `ufunc`s or via `map_batches`. We could see if we can make `map_batches` more convenient by automatically convering to `Series`. 

But as of now, everything is possible as is. You must convert to `Series` because you work with polars. A little bit of data type hygiene isn't so bad IMO.

**Comment by Wainberg** [comment]
@ritchie46 I see where you're coming from. Would you accept an issue to make `map_batches` auto-convert its outputs to Series? 

If you're open to it, I could also put in an issue to delegate `numpy_func(pl.col.a)` and `pl.col.a.pipe(numpy_func)` to `map_batches`, so that NumPy functions always behave the same way (to the end user) regardless of whether they're ufuncs or not.

**Comment by ritchie46** [comment]
> Would you accept an issue to make map_batches auto-convert its outputs to Series?

If this works trivially, I am for this.
