### ISSUE TITLE
Move build logic out of Github Actions

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#13264]
Our build process is becoming increasingly complex, and too many decisions are made in the Github Actions workflow. This makes it difficult to locally produce certain builds / test the build process. We should probably move this logic into dedicated scripts and let the Github Action simply call this script.

**Comment by stinodego** [comment]
I refactored the workflow to be a bit more sensible and have less duplication.

I'm not sure about moving the logic out of GitHub Actions. The current setup nicely works for various operating systems - I think it might be tricky to replicate that outside of GitHub Actions without introducing a lot of additional complexity. I don't think it's worth it at this point.
