### ISSUE TITLE
add clip function

### ISSUE THREAD

**Issue by qinwf** [pola-rs/polars#1326]
#### Describe your feature request

pandas.DataFrame.clip is a useful function.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.clip.html

**Comment by ritchie46** [comment]
Polars supports numpy `__ufunc__`, so you can use `np.clip` on polars sereis and expressions.

**Comment by qinwf** [comment]
I want to run `clip` on all columns with upper bound array and lower bound array for a very big data frame with parallel threads.

I will explore how to do this with `polars`.

now I use `modin.Dataframe.clip()`, it has the same behaviors as `pandas.Dataframe.clip()`

**Comment by qinwf** [comment]
an example

```python
In [1]: import pandas
   ...: 
   ...: df = pandas.DataFrame(
   ...:     {
   ...:         "A": [1, 2, 3, 4, 5],
   ...:         "B": [5, 4, 3, 2, 1]
   ...:     }
   ...: )

In [2]: df
Out[2]: 
   A  B
0  1  5
1  2  4
2  3  3
3  4  2
4  5  1

In [3]: df.clip(upper=[3,2],lower=[1,2], axis=1)
   ...: 
Out[3]: 
   A  B
0  1  2
1  2  2
2  3  2
3  3  2
4  3  2

```

**Comment by ritchie46** [comment]
It seems that `np.clip` is not a `ufunc`. I have added a `clip` method. You can use that in the next release.

Until then you can do:

```python
def clip(name, min_val, max_val):
        return (
            pl.when(col(name) < min_val)  
            .then(min_val)
            .when(col(name) > max_val)
            .then(max_val)
            .otherwise(col(name))
        ).alias(name)
    

df = pl.DataFrame(
        {
            "A": [1, 2, 3, 4, 5],
            "B": [5, 4, 3, 2, 1]
        }
)

df.select(
    [clip(name, low, high) for name, low, high in zip(["A", "B"], [0, 1], [2, 3])]
)

```

**Comment by ritchie46** [comment]
added and released.

**Comment by qinwf** [comment]
Thank you so much!
