### ISSUE TITLE
Allow `pl.col(pl.Enum)` for selecting all Enum columns

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13269]
### Description

This gives an error in the master branch of polars, as well as in 0.20.2:

```python
>>> pl.col(pl.Enum)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/py-polars/polars/functions/col.py", line 287, in __new__
    return _create_col(name, *more_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../polars/py-polars/polars/functions/col.py", line 43, in _create_col
    return wrap_expr(plr.dtype_cols([name]))
                     ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'dtypes': Enum types must be instantiated with a list of categories
```

**Comment by collinprince** [comment]
Believe I have a fix and have tested that it covers this issue and allows users to select columns by `pl.col(pl.Enum)` expression. @c-peters it looks like you have done much of the work in `Enum` development, so wanted to check with you if this "feels right"/doesn't go against your intended design.
