### ISSUE TITLE
API Reference: Link to source code isn't working if selected version is "dev"

### ISSUE THREAD

**Issue by alexanderpils** [pola-rs/polars#13266]
### Description

If you click on "source" in the API Reference of any function and you are on the version "dev" you get a "404 - page not found" error.
See example screenshot below:
![image](https://github.com/pola-rs/polars/assets/43525933/a819fe42-867c-4b9f-9c26-74e52cd06294)
![image](https://github.com/pola-rs/polars/assets/43525933/cc6338da-30f9-4104-a819-4b1eb8e286fe)

The problem seems to be that in the link:
https://github.com/pola-rs/polars/blob//py-polars/polars/dataframe/frame.py#L3631-L3819
after blob the version is missing and as far as I understand the "dev" version should link to main. So the link should be
https://github.com/pola-rs/polars/blob/main/py-polars/polars/dataframe/frame.py#L3631-L3819

**Comment by stinodego** [comment]
Thanks for the report - will fix!
