### ISSUE TITLE
Polars is 1000x slower than pandas at constructing a DataFrame from a 1000 x 20,000 NumPy array

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13282]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import numpy as np, pandas as pd, polars as pl; from timeit import timeit
>>> arr = np.zeros((1000, 20000), order='F')
>>> timeit(lambda: pd.DataFrame(arr), number=1)
0.00011860299855470657
>>> timeit(lambda: pl.DataFrame(arr), number=1)
0.12338529899716377
```

### Issue description

Polars is 1000x slower than pandas at constructing a DataFrame from a 1000 x 20,000 NumPy array. 

This is a common use-case in bioinformatics, where there are ~20,000 protein-coding genes. It's slow enough to be a major bottleneck in some code I'm writing to analyze single-cell RNA sequencing data.

### Expected behavior

This should be extremely fast since the NumPy array is Fortran-contiguous. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```
</details>

**Comment by s-banach** [comment]
Pandas just keeps a view of the 2D array. Polars copies it to separate 1D arrays.
I guess you're asking if polars could make columns from views into a 2D array.
There are probably pros and cons to this.

**Comment by MarcoGorelli** [comment]
if you don't use the classical numpy-backed dtypes, pandas is slower:
```
In [6]: timeit(lambda: pl.DataFrame(arr), number=1)
Out[6]: 0.12597480899967195

In [7]: timeit(lambda: pd.DataFrame(arr, dtype='Float64[pyarrow]'), number=1)
Out[7]: 0.34044090200040955

In [8]: timeit(lambda: pd.DataFrame(arr, dtype='Float64'), number=1)
Out[8]: 1.1483286539987603
```

>  It's slow enough to be a major bottleneck in some code I'm writing to analyze single-cell RNA sequencing data.

Initialising a dataframe is a bottleneck? I've very surprised, would be curious to hear more details about your usecase. Are you repeatedly instantiating dataframes?

**Comment by mcrumiller** [comment]
The bottleneck in this case is [`new_f64`](https://github.com/pola-rs/polars/blob/main/py-polars/src/series/construction.rs#L77-L91) getting called 20,000 times, as per `cProfile`:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    238/1    0.001    0.000    0.603    0.603 {built-in method builtins.exec}
        1    0.000    0.000    0.603    0.603 check_numpy.py:1(<module>)
        1    0.005    0.005    0.468    0.468 frame.py:353(__init__)
        1    0.017    0.017    0.463    0.463 _construction.py:1382(numpy_to_pydf)
        1    0.040    0.040    0.409    0.409 _construction.py:1484(<listcomp>)
    20000    0.038    0.000    0.366    0.000 series.py:242(__init__)
       33    0.001    0.000    0.341    0.010 __init__.py:1(<module>)
    20000    0.025    0.000    0.274    0.000 _construction.py:214(numpy_to_pyseries)
    20000    0.238    0.000    0.238    0.000 {built-in method new_f64}           <----HERE
    282/2    0.001    0.000    0.134    0.067 <frozen importlib._bootstrap>:1167(_find_and_load)
    282/2    0.001    0.000    0.134    0.067 <frozen importlib._bootstrap>:1122(_find_and_load_unlocked)
    269/2    0.001    0.000    0.134    0.067 <frozen importlib._bootstrap>:666(_load_unlocked)
```

In this case function immediately dispatches to [`mmap_numpy_array`](https://github.com/pola-rs/polars/blob/main/py-polars/src/series/construction.rs#L39-L49) so that's probably where most of the time is spent (the python profile doesn't pick this up since it's down in the rust call stack).

**Comment by ritchie46** [comment]
Hmm.. I see there is something wrong with the numpy release. Something expensive is happening. I expected the drop to be free. Taking a look.

![image](https://github.com/pola-rs/polars/assets/3023000/421e16c2-7ba1-4280-be93-aba245f0c2b6)
