### ISSUE TITLE
transpose a dataframe (or a slice of dataframe) in Rust

### ISSUE THREAD

**Issue by wangjiawen2013** [pola-rs/polars#13306]
### Description

Hi,
How to transpose a dataframe (or a slice of dataframe) in Rust polars (not python polars) ?  Though there is a method called `transpose`, there is no documentation of it.

**Comment by Biswas-N** [comment]
Hi, not sure if this helps. Here's a [link](https://docs.rs/polars-core/0.35.4/src/polars_core/frame/row/transpose.rs.html#260) pointing to the tests written for `transpose` method.

**Comment by wangjiawen2013** [comment]
It works, thank you very much.

And hope more examples on how to set headers.
