### ISSUE TITLE
null does not count as a value for `Categorical` in `unique`/`n_unique`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13305]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series(["CA", "DE", "FR", None], dtype=pl.Categorical)
result = s.n_unique()
print(result)  # prints 3 - should be 4

result = s.unique()
print(result)  # shows the three non-null elements
```

### Log output

```shell
3
shape: (3,)
Series: '' [cat]
[
        "CA"
        "DE"
        "FR"
]
```

### Issue description

`unique` should include a null value if the column contains any. This is not the case for Categorical columns.

### Expected behavior

Include a null value.

### Installed versions

main branch

**Comment by ritchie46** [comment]
Right that is a wrong fast path. The fast_unique flag should only be respected if there are not null values.
