### ISSUE TITLE
read_csv: dtypes date32 and date64 are not inferred correctly anymore

### ISSUE THREAD

**Issue by benmaier** [pola-rs/polars#1330]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.9.3, but the behavior first appeared in v 0.8.12

#### What operating system are you using polars on?

macOS 11.3

#### Describe your bug.

When reading a csv-file with a column that contains dates and times in iso-string format, the date32-type and date64-type will not be inferred correctly.

#### What are the steps to reproduce the behavior?

**test.csv**

```
date,datetime,val
2021-08-01,2021-08-01 04:34,2
```

```python
import polars as po

df = po.read_csv('test.csv')
print(df)
```

#### Actual behavior
```
shape: (1, 3)
╭──────────────┬────────────────────┬─────╮
│ date         ┆ datetime           ┆ val │
│ ---          ┆ ---                ┆ --- │
│ str          ┆ str                ┆ i64 │
╞══════════════╪════════════════════╪═════╡
│ "2021-08-01" ┆ "2021-08-01 04:34" ┆ 2   │
╰──────────────┴────────────────────┴─────╯
```

#### Expected behavior

```
shape: (1, 3)
╭──────────────┬─────────────────────┬─────╮
│ date         ┆ datetime            ┆ val │
│ ---          ┆ ---                 ┆ --- │
│ date32(days) ┆ date64(ms)          ┆ i64 │
╞══════════════╪═════════════════════╪═════╡
│ 2020-08-01   ┆ 2020-08-01 04:34:00 ┆ 2   │
╰──────────────┴─────────────────────┴─────╯
```

 This is the behavior that the function had in version 0.8.11, and apparently the inference of date32 and date64 was lost in 0.8.12

**Comment by ritchie46** [comment]
This is due to the switch to polars' native parser. Parsing of dates, needs to be done after the csv is parsed. If you want old behavior, you can set `use_pyarrow` to `true`.

**Comment by benmaier** [comment]
ok, cool, thanks!
