### ISSUE TITLE
Support for STDEV in SQL

### ISSUE THREAD

**Issue by ameysami** [pola-rs/polars#13302]
### Description

The sql interpreter does not know STDEV or STDEVP as known functions and therefore errors out when a user attempts to use them. 
`SELECT *, STDEV(COLUMN_X) FROM INPUT_TABLE` errors out with the following error message:
polars.exceptions.InvalidOperationError: unsupported SQL function: stdev

Please note, while you can obviously use the python methods for calculating standard deviation, it is useful to also have that capability in SQL as well. Primarily to satisfy different preferences, but also as addition of support for such important functions can lead to trivial development of an equivalent method to pandas eval, which I believe is a highly used feature for data scientists when feature engineering tabular data.

**Comment by alexander-beedie** [comment]
We already support STDEV, but we favour PostgreSQL syntax, which expects STDDEV (note the extra 'D'). I don't think it's unreasonable to support both spellings though, as a quick look over various dialects show that it's a coin-flip between which each one uses. I'll add both.
