### ISSUE TITLE
Windows Process finished with exit code -1073741795 (0xC000001D)

### ISSUE THREAD

**Issue by Guf-Hub** [pola-rs/polars#13316]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
    from datetime import datetime

    df = pl.DataFrame(
        {
            "integer": [1, 2, 3],
            "date": [
                datetime(2022, 1, 1),
                datetime(2022, 1, 2),
                datetime(2022, 1, 3),
            ],
            "float": [4.0, 5.0, 6.0],
        }
    )

    print(df)
```

### Log output

```shell
Process finished with exit code -1073741795 (0xC000001D)
```

### Issue description

I downloaded polars, I run the code in Pycharm, it crashes with an error, apparently at the import stage.

### Expected behavior

shape: (3, 3)
┌─────────┬─────────────────────┬───────┐
│ integer ┆ date                ┆ float │
│ ---     ┆ ---                 ┆ ---   │
│ i64     ┆ datetime[μs]        ┆ f64   │
╞═════════╪═════════════════════╪═══════╡
│ 1       ┆ 2022-01-01 00:00:00 ┆ 4.0   │
│ 2       ┆ 2022-01-02 00:00:00 ┆ 5.0   │
│ 3       ┆ 2022-01-03 00:00:00 ┆ 6.0   │
└─────────┴─────────────────────┴───────┘

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```
(0.19.19) it doesn't give me a newer one via pip
</details>

**Comment by mcrumiller** [comment]
pip should be giving you 0.20.2 right now. Can you please run:

```shell
python -m pip install --upgrade polars
```

Although I suspect this is not polars related.

**Comment by stinodego** [comment]
Could you please run `pip install polars==0.20.3-rc.2` and run `import polars` and paste the output here?

**Comment by stinodego** [comment]
Closing this as there is not enough information to go on right now.

**Comment by Guf-Hub** [comment]
C:\Users\mnosa\PycharmProjects\wb_stat_loader\venv\Lib\site-packages\polars\_cpu_check.py:236: RuntimeWarning: Missing required CPU features.

The following required CPU features were not detected:
    avx2, fma, bmi1, bmi2, lzcnt
Continuing to use this version of Polars on this processor will likely result in a crash.
Install the `polars-lts-cpu` package instead of `polars` to run Polars with better compatibility.

Hint: If you are on an Apple ARM machine (e.g. M1) this is likely due to running Python under Rosetta.
It is recommended to install a native version of Python that does not run under Rosetta x86-64 emulation.

If you believe this warning to be a false positive, you can set the `POLARS_SKIP_CPU_CHECK` environment variable to bypass this check.

  warnings.warn(

Process finished with exit code -1073741795 (0xC000001D)

![image](https://github.com/pola-rs/polars/assets/72359732/e3553925-9fb0-423b-b92c-7a906c6f7475)

**Comment by mcrumiller** [comment]
It looks like you're on an old CPU, try installing polars for legacy CPU:

```shell
pip install polars-lts-cpu
```

**Comment by Guf-Hub** [comment]
Victory, thank you
![image](https://github.com/pola-rs/polars/assets/72359732/e6c9b5ae-8546-4d3e-b921-d937a427db76)


Why is polars==0.20.3-rc.2 not installed by default via pip in the dock there is no description for downloading and polars-lts-cpu, I did polars [all]

**Comment by Ilia-Kosenkov** [comment]
In case somebody finds this and has the same issue on Windows `arm` machine, you are likely running `amd64` python with `amd64`-specific `polars` in emulation mode. `polars` likely assumes it can use `x86_64` vectorization instructions, which are... absent on `arm64` (and are not translated by Windows it seems).
For me, the process drops silently on `import polars`. The only culprit was the exit code `-1073741795 (0xC000001D)`

<details>
<summary>A pwsh script to check arch/python/exit code</summary>

```pwsh
Write-Host $env:PROCESSOR_ARCHITECTURE

python --version

python -c "import sys; print(sys.version);import polars as pl; print(pl.__version__)"

Write-Host $LASTEXITCODE
$byteRep = [BitConverter]::GetBytes($LASTEXITCODE)
[Array]::Reverse($byteRep)
Write-Host "0x$([Convert]::ToHexStringLower($byteRep))"
```
</details>

Here is what I got:

> ARM64
Python 3.12.0
3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:26:13) [MSC v.1935 64 bit (AMD64)]
-1073741795
0xC000001D

Fortunately though, `polars-lts-cpu` does the trick.

**Comment by cmdlineluser** [comment]
@Ilia-Kosenkov It's `polars[rtcompat]` starting from 1.34.0

- https://docs.pola.rs/user-guide/installation/#legacy-cpu

- https://github.com/pola-rs/polars/pull/25010#issue-3549170671

> For future work we can use the CPU check to dynamically choose between `rtcompat` or not.
