### ISSUE TITLE
Segfault on `repeat` with `Array` dtype

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#13324]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

* Works with `List`:
  ```python
  dtype = pl.List(pl.UInt8)
  pl.repeat([42], n=3, dtype=dtype, eager=True)

  # shape: (3,)
  # Series: 'repeat' [list[u8]]
  # [
  #   [42]
  #   [42]
  #   [42]
  # ]
  ```

* Segfaults with `Array`:
  ```python
  dtype = pl.Array(pl.UInt8, width=1)
  pl.repeat([42], n=3, dtype=dtype, eager=True)

  # 💣 Process finished with exit code 138 (interrupted by signal 10: SIGBUS)
  ```

### Issue description

Segfault using `Array` dtype with `repeat`.

### Expected behavior

Create a Series with the indicated dtype from repeated array elements:
```python
# shape: (3,)
# Series: 'repeat' [array[u8, 1]]
# [
#   [42]
#   [42]
#   [42]
# ]
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3-rc.2
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.14.0
fsspec:               2023.12.2
gevent:               23.9.1
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.24
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
Ouch, taking a look.

**Comment by ritchie46** [comment]
It also creates a listarray?

```python
>>> dtype = pl.Array(pl.UInt8, width=1)
>>> pl.repeat([42], n=3, dtype=dtype, eager=True).dtype
List(UInt8)
```

**Comment by alexander-beedie** [comment]
> It also creates a listarray?
> 
> ```python
> >>> dtype = pl.Array(pl.UInt8, width=1)
> >>> pl.repeat([42], n=3, dtype=dtype, eager=True).dtype
> List(UInt8)
> ```

Ahh, I must have a local fix for the dtype-passing in place - was about to drop another PR that slightly improves `ones` and `zeros`, which is how I came across the segfault. Let me commit that, then you  should be able to repro!

**Comment by ritchie46** [comment]
Nah, I do think something is wrong in rust. You should not be able to create this state.

**Comment by alexander-beedie** [comment]
> Nah, I do think something is wrong in rust. You should not be able to create this state.

Ahh, might have misunderstood; there's definitely something wrong, I just wasn't sure if you could repro it?

**Comment by alexander-beedie** [comment]
PR for `ones`, `zeros`, and `repeat` dtype fixes just landed: https://github.com/pola-rs/polars/pull/13326. 
Should be able to repro with this as it won't lose track of the indicated dtype.

**Comment by alexander-beedie** [comment]
Nice! I see you could repro after all...  :)
