### ISSUE TITLE
Allow Categoricals and Enums to have numeric categories

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13320]
### Description

https://github.com/pola-rs/polars/issues/10430 proposed that Categoricals should support integer categories, although that issue hasn't been accepted yet. It would be nice to support integer categories for Enums as well, and also to support floating-point categories like pandas:

```python
>>> pd.Series([0.1, 0.3, 0.5]).astype('category')
0    0.1
1    0.3
2    0.5
dtype: category
Categories (3, float64): [0.1, 0.3, 0.5]
```

You could even imagine supporting any polars dtype as the categories (list categories, anyone?) though that might be a fair amount more work and isn't as important as supporting integer categories.

**Comment by stinodego** [comment]
Closing in favor of #10430
