### ISSUE TITLE
Support `to_numpy` for List types without pyarrow requirement

### ISSUE THREAD

**Issue by dpinol** [pola-rs/polars#13322]
### Description

Hi,
imho it's a bit confusing that DataFrame/Series to_numpy with no arguments work fine without pyarrow installed for basic datatypes, but it produces the following error when having list types.
`polars.exceptions.ComputeError: 'to_numpy' not supported for dtype: List(Int64)  `

E.g. with works without pyarrow:
```
import polars as pl
df=pl.DataFrame({"B": [3, 6]})
df.to_numpy()
```

But this causes the ComputeError above:
```
import polars as pl
df=pl.DataFrame({"A": [[1, 2], [4, 5]]})
df.to_numpy()
```

thanks

**Comment by ritchie46** [comment]
Rather, we should support that export.

**Comment by stinodego** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/14334
