### ISSUE TITLE
Enum display possibly incorrect?

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#13330]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {"x": ["1"]*3,"y": ['1']*3},
    schema={"x": pl.Enum(['1']), "y": pl.Enum(['1'])},
)

shape: (3, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ cat ┆ cat │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 1   ┆ 1   │
│ 1   ┆ 1   │
└─────┴─────┘
```

### Issue description

It shows categorical and not enum in the display

### Expected behavior

Show as enum instead of cat

### Installed versions

<details>

```
Latest build from main.
```

</details>

**Comment by alexander-beedie** [comment]
Enum is a subtype of categorical, but the display trait wasn't checking for that; just pushed a small fix 👍
