### ISSUE TITLE
Request: nth_value aggregator function

### ISSUE THREAD

**Issue by vieiro** [pola-rs/polars#13340]
### Description

Sometimes we need to extract the "nth largest/smallest value" within a group. 

For instance, given the DataFrame with groups `a`, `b` and `c`:

```python
import polars as pl

df = pl.DataFrame({
        'id'   : [1,    2,    3, 10,   11,  12,  13,  24],
        'group': ['a', 'a', 'a', 'b', 'b', 'b', 'b', 'c'],
        'value': [1,    2,    3,  1,    2,   9,   4,   7],
    })
```

```bash
shape: (8, 3)
┌─────┬───────┬───────┐
│ id  ┆ group ┆ value │
│ --- ┆ ---   ┆ ---   │
│ i64 ┆ str   ┆ i64   │
╞═════╪═══════╪═══════╡
│ 1   ┆ a     ┆ 1     │
│ 2   ┆ a     ┆ 2     │
│ 3   ┆ a     ┆ 3     │
│ 10  ┆ b     ┆ 1     │
│ 11  ┆ b     ┆ 2     │
│ 12  ┆ b     ┆ 9     │
│ 13  ┆ b     ┆ 4     │
│ 24  ┆ c     ┆ 7     │
└─────┴───────┴───────┘
```

We would like to obtain the group, the id and the value of the **3rd largest element of each group** (ordered by `value`). We could use the `head(3)` and `last()` aggregators like so:

```python
test = df.group_by('group').agg(
    pl.all().sort_by(pl.col('value'), descending=False).head(3).last()
)

print(test)
```

And we'd get:

```bash
shape: (3, 3)
┌───────┬─────┬───────┐
│ group ┆ id  ┆ value │
│ ---   ┆ --- ┆ ---   │
│ str   ┆ i64 ┆ i64   │
╞═══════╪═════╪═══════╡
│ c     ┆ 24  ┆ 7     │
│ a     ┆ 3   ┆ 3     │
│ b     ┆ 13  ┆ 4     │
└───────┴─────┴───────┘
```

Which correctly finds the third largest values of groups `a` (`value = 3`), and `b` (`value = 4`). But fails on group `c` stating that the third largest value is the one with id `24` and value `7`, when in reality there's no such thing as "third largest value" on group `c`, because group `c` has only one element.

One could argue that since the group `c` has a single element, then the largest `value` of group `c` is also the second largest, and the third largest, etc., but in practical uses one would expect a `null` value being returned, meaning that `c` has no three elements.

Having an `nth_value(n)` aggregator function that behaves similar [to the Postgres' nth-value window function](https://www.postgresql.org/docs/16/functions-window.html) (i.e., that returns NULL if the window has no nth-element) would be handy.

With such an `nth_value` one should be able to write:

```python
print(test)

# Proposed syntax
test = df.group_by('group').agg(
    pl.all().sort_by(pl.col('value'), descending=False).nth_value(3)
)
```

To get:

```bash
shape: (3, 3)
┌───────┬───────┬───────┐
│ group ┆   id  ┆ value │
│ ---   ┆   --- ┆ ---   │
│ str   ┆   i64 ┆ i64   │
╞═══════╪═══════╪═══════╡
│ c     ┆ null  ┆ null  │
│ a     ┆   3   ┆ 3     │
│ b     ┆   13  ┆ 4     │
└───────┴───────┴───────┘
```

**Comment by vieiro** [comment]
As an ugly (non parallelizable?) workaround:

```python
def nth(n:int):
    return lambda series: None if series.len() < n else series[n-1]

test2 = df.group_by('group').agg(
    pl.all().sort_by(pl.col('value'), descending=False).apply(nth(3))
)
print(test2)
```
Correctly returns the expected result:
```bash
shape: (3, 3)
┌───────┬──────┬───────┐
│ group ┆ id   ┆ value │
│ ---   ┆ ---  ┆ ---   │
│ str   ┆ i64  ┆ i64   │
╞═══════╪══════╪═══════╡
│ c     ┆ null ┆ null  │
│ b     ┆ 13   ┆ 4     │
│ a     ┆ 3    ┆ 3     │
└───────┴──────┴───────┘
```

**Comment by alexander-beedie** [comment]
FYI, you can get 90% the way there natively with `slice`...
```
grouped = df.group_by('group').agg(
    pl.all().sort_by(pl.col('value'), descending=False).slice(2,1)
)
# shape: (3, 3)
# ┌───────┬───────────┬───────────┐
# │ group ┆ id        ┆ value     │
# │ ---   ┆ ---       ┆ ---       │
# │ str   ┆ list[i64] ┆ list[i64] │
# ╞═══════╪═══════════╪═══════════╡
# │ a     ┆ [3]       ┆ [3]       │
# │ b     ┆ [13]      ┆ [4]       │
# │ c     ┆ []        ┆ []        │
# └───────┴───────────┴───────────┘
```
...then just turn the returned one-element lists into scalar values:
```python
grouped.with_columns(
    pl.col("id","value").list.first()
)
# shape: (3, 3)
# ┌───────┬──────┬───────┐
# │ group ┆ id   ┆ value │
# │ ---   ┆ ---  ┆ ---   │
# │ str   ┆ i64  ┆ i64   │
# ╞═══════╪══════╪═══════╡
# │ a     ┆ 3    ┆ 3     │
# │ b     ┆ 13   ┆ 4     │
# │ c     ┆ null ┆ null  │
# └───────┴──────┴───────┘
```

**Comment by ritchie46** [comment]
So we must add an option to return `Null` on oob in `get`. Then you can use `when/then/otherwise`.

**Comment by alexander-beedie** [comment]
> So we must add an option to return `Null` on oob in `get`. Then you can use `when/then/otherwise`.

If `get` can return null on oob, presumably we could just use it directly?
Wouldn't need the conditional evaluation.

**Comment by deanm0000** [comment]
There's these:

Expr.get
Expr.list.get
Expr.gather


Expr.list.gather already has null_on_oob parameter.
