### ISSUE TITLE
Error when reading a polar Csv

### ISSUE THREAD

**Issue by SEBASW117** [pola-rs/polars#13365]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
datos = pl.read_csv('datos_abiertos.csv'
[datos_abiertos.csv](https://github.com/pola-rs/polars/files/13806341/datos_abiertos.csv)
)
datos.head(2)
```

### Log output

```shell
ComputeError: could not parse `3122806977 - 3122885930` as dtype `i64` at column 'Teléfono' (column number 11)

The current offset in the file is 57933 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `3122806977 - 3122885930` to the `null_values` list.

Original error:  bytes non-empty
```

### Issue description

I am trying to read a simple CSV with polars, but this gives me the error mentioned above, I already inspected the CSV and saw that there are two phone numbers separated by a hyphen, I know that the error is solved if I tell polars to read everything as a string, but this prevents me from working with the data types later, how can I solve this error please help

### Expected behavior

![Captura de pantalla 2024-01-01 184925](https://github.com/pola-rs/polars/assets/132231700/d73770fc-cdce-4c53-978a-ad1d0692a345)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by Wainberg** [comment]
You can use `dtypes={'Teléfono': str}` to read just that column as a string, or set `infer_schema_length` to `None` (or to a larger number than the default of 100). This isn't a bug, though.
