### ISSUE TITLE
Switch to the fancy_regex crate

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13362]
### Description

Rust's `regex` crate does not support backreferences or lookaround. Backreferences in particular are ubiquitous in regex replacement. For instance, this behavior is not supported in polars:

```python
>>> import pandas as pd
>>> pd.Series(['ham', 'hem']).str.replace('h(.)m', r'b\1d', regex=True)
0    bad
1    bed
dtype: object
```

Fortunately, since 2022 there's been a new crate called `fancy_regex` ([Github repo](https://github.com/fancy-regex/fancy-regex), [docs.rs page](https://docs.rs/fancy-regex/latest/fancy_regex)) that seems to be backward compatible with the `regex` crate while adding support for backreferences and lookaround. Crucially, if these features are not used, `fancy_regex` delegates to `regex`, so the performance penalty for existing polars code that uses regexes should be nearly non-existent. 

It should be very simple to switch from `regex` to `fancy_regex`: just a drop-in replacement. I'd be happy to submit a pull request if this issue is accepted.

**Comment by alexander-beedie** [comment]
I would be surprised if there was much support for doing this 🤔 

The primary reason is the efficiency and hard guarantees about worst-case performance that you get from NFA regex engines (the standard rust crate, RE2, and pretty-much all of the other best-performing regex engines).

Backtracking engines can result in absolutely _catastrophic_ performance degradation with naive regex patterns (even ones that don't, at first glance, appear to be especially problematic). I know that `fancy_regex` espouses a hybrid approach, trying to delegate to the standard `regex` crate when "fancy" features are not required (which is good), but even their own performance section points out that patterns triggering worst-case performance are more or less unavoidable if you want to support features that require backtracking: https://github.com/google/fancy-regex/blob/master/PERFORMANCE.md

These are not small differences either; we're talking tens of seconds vs tens of _micro_seconds for some of the given examples.

A couple of reads on the topic:
* Techniques to Improve Regex Performance: [Concluding Thoughts](https://www.loggly.com/blog/five-invaluable-techniques-to-improve-regex-performance/#:~:text=The%20best%20performance%20boost%20of,grep%2C%20awk%2C%20or%20Re2.) (TLDR: use an engine based on NFA)
* [Regular Expression Matching Can Be Simple And Fast](https://swtch.com/~rsc/regexp/regexp1.html)

**Comment by Wainberg** [comment]
I mean, `str.replace` is not terribly useful without backreferences. The fact that they can occasionally be very slow in certain pathological situations doesn't seem like a compelling reason to not support them. Again, switching to this crate will not slow down existing code.

In practice, there just isn't a systemic problem with speed when using backreferences, which is why they're supported by every dataframe library I'm aware of... except polars. I'm not aware of any dataframe library that even mentions catastrophic backtracking as an issue in their documentation, which you would expect to see if this happened frequently in practice.

If you want to drive away new users, not supporting basic functionality available in other dataframe libraries they're coming from is a good way to do it! That said, I absolutely get where you're coming from, and at a bare minimum this ought to be prominently documented in any polars regex functions that would support backreferences.

@stinodego, thoughts on this from a user experience perspective?

**Comment by cmdlineluser** [comment]
https://docs.rs/regex/latest/regex/struct.Regex.html#replacement-string-syntax

```python
>>> pl.Series(['ham', 'hem']).str.replace('h(.)m', 'b${1}d')
shape: (2,)
Series: '' [str]
[
	"bad"
	"bed"
]
```

**Comment by Wainberg** [comment]
@cmdlineluser Ok wow, was not aware of that functionality! Tbh this mostly addresses my concern, since backreferences are a lot more important than lookaround and the Rust crate's "replacement strings" (`$1` etc.) are pretty similar to backreferences. Could something like `pl.Series(['ham', 'hem']).str.replace('h(.)m', 'b${1}d')` go into the documentation for `str.replace` as an example?

**Comment by stinodego** [comment]
I'll close this as we _do_ support the requested functionality and Alex makes an excellent case for keeping the existing regex implementation.

**Comment by alexander-beedie** [comment]
> I mean, `str.replace` is not terribly useful without backreferences. 

I think you may have mixed-up backtracking and backreferences; obviously NFAs support the latter.

> If you want to drive away new users, not supporting basic functionality available in other dataframe libraries they're coming from is a good way to do it!

Let's not get dramatic here ;)
(especially as back references _are_ supported by NFA regex engines, including the standard regex crate used by polars).

**Comment by Wainberg** [comment]
My point of confusion was that the regex crate says explicitly that:

> it lacks several features that are not known how to implement efficiently. This includes, but is not limited to, look-around and backreferences

but then implements "replacement strings", which are... basically the same as backreferences? Maybe the authors of the regex crate said it lacks backreferences, but they actually meant it lacks backtracking?

It sounded like you were arguing against the idea of supporting backreferences in polars, which would have been a pretty extreme position (since you almost always use them when replacing things). But I think we're all on the same page now.

**Comment by alexander-beedie** [comment]
> It sounded like you were arguing against the idea of supporting backreferences in polars, which would have been a pretty extreme position (since you almost always use them when replacing things). But I think we're all on the same page now.

In fairness I just realised that even I've started blurring the terminology now! Proper backreferencing is a stricter form of what we've been talking about where you get to refer to a previously captured part of a pattern _from within the same pattern_. That's the part that makes it a potential footgun - referring to the capture group in a subsequent replacement (which _is_ supported) is fine. 😉
