### ISSUE TITLE
Add sql query to compare binary column

### ISSUE THREAD

**Issue by junsongzhao** [pola-rs/polars#13360]
### Description

I'm working with binary columns. The sql query cannot do comparison on binary columns. Here is one example
```python
import polars as pl

df = pl.DataFrame({
    "bdata": [b'\x01',b'\x02',b'\x03'],
    "misc":['abc','def','ghi'],
})
with pl.SQLContext(mytable=df) as ctx:
    ctx.execute(f"select * from mytable where bdata > b'01'", eager=True)

# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/.../3.9/lib/python/site-packages/polars/sql/context.py", line 274, in execute
#     res = wrap_ldf(self._ctxt.execute(query))
# polars.exceptions.ComputeError: SQL value SingleQuotedByteString
```

**Comment by alexander-beedie** [comment]
Looks like a simple fix; thanks for the straightforward example 👍 
(I minimised it for a quick repro).

**Comment by alexander-beedie** [comment]
@junsongzhao: FYI, the update just merged, and will be available in the next release. Note that `b'<value>'` is not actually a _byte_ string though; we favour PostgreSQL dialect, where this is a _bit_ string (eg: `b'10011110'`). To match bytes, you can use one of the following syntaxes: `'<value>'::bytes` (requires the new update) or inline hex escapes, which I think may work even without the new update (eg: `'\x01\xFF'`).
