### ISSUE TITLE
shift_and_fill should have two different generics

### ISSUE THREAD

**Issue by TheDan64** [pola-rs/polars#13363]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

shift_and_fill is currently defined as:

```rust
fn shift_and_fill<E: Into<Expr>>(self, n: E, fill_value: E)
```

### Log output

```shell
N/A
```

### Issue description

because both parameters use the same generic, they must be the same type. You can't do something like `shift_and_fill(1, true)`.

A work around is to do `shift_and_fill(lit(1), lit(true))` - at the cost of API ergonomics.

### Expected behavior

`shift_and_fill(1, true)` to work

```rust
fn shift_and_fill<E: Into<Expr>, E2: Into<Expr>>(self, n: E, fill_value: E2)
```

would do it.

### Installed versions

<details>
    "abs",
    "avx512",
    "csv",
    "cum_agg",
    "dtype-slim",
    "fmt",
    "lazy",
    "object",
    "performant",
    "random",
    "rolling_window",
    "temporal",
</details>

**Comment by ritchie46** [comment]
Yeap, agree. Can you make a PR?
