### ISSUE TITLE
Add documentation on replacement strings to str.replace and str.replace_all

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13366]
### Description

@cmdlineluser [pointed out today](https://github.com/pola-rs/polars/issues/13362#issuecomment-1873494043) that `str.replace` supports "replacement strings", as in the following example where `${1}` refers to the first capture group:

```python
>>> pl.Series(['ham', 'hem']).str.replace('h(.)m', 'b${1}d')
shape: (2,)
Series: '' [str]
[
	"bad"
	"bed"
]
```
It would be worth briefly mentioning this feature in the documentation for [`Expr.str.replace`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.str.replace.html), [`Series.str.replace`](https://docs.pola.rs/py-polars/html/reference/series/api/polars.Series.str.replace.html), [`Expr.str.replace_all`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.str.replace_all.html) and [`Series.str.replace_all`](https://docs.pola.rs/py-polars/html/reference/series/api/polars.Series.str.replace_all.html), and including an example like the one above.

**Comment by stinodego** [comment]
Definitely, could you make a PR?

**Comment by cmdlineluser** [comment]
There probably needs to be a note/warning because `$` in the replacement is basically a metacharacter.

```python
pl.Series(['ham']).str.replace('(.*)', 'foo$bar')
# shape: (1,)
# Series: '' [str]
# [
# 	"foo"
# ]
```

`$bar` is looking for the named capture group:

```
pl.Series(['ham']).str.replace('(?<bar>.*)', 'foo$bar')
# shape: (1,)
# Series: '' [str]
# [
#	"fooham"
# ]
```

In pandas, this raises an exception:

```python
pd.Series(['ham']).str.replace('(.*)', r'foo\g<bar>', regex=True)
# IndexError: unknown group name 'bar'
```

**Comment by Wainberg** [comment]
@cmdlineluser yeah that should be a warning, could you make a separate issue for it?

**Comment by cmdlineluser** [comment]
I just mean a Warning section in the docs

<img width="916" alt="Screen Shot 2024-01-02 at 08 30 40" src="https://github.com/pola-rs/polars/assets/99486669/877e86b5-558e-4a84-8ddf-ecaf7887073b">
