### ISSUE TITLE
Misleading docstring for`Series::to_float()`

### ISSUE THREAD

**Issue by legendre6891** [pola-rs/polars#13367]
### Description

Hi! `Series::to_float()` suggests that it will cast `f32` to `f64`, but in fact it will keep `f32` intact. Perhaps the doc string needs to be adjusted? 

> /// Cast numerical types to f64, and keep floats as is. 

Cheers

https://github.com/pola-rs/polars/blob/0c471c22fd91abd6cce317df1998db3b7ebf7ea9/crates/polars-core/src/series/mod.rs#L331-L337

**Comment by stinodego** [comment]
It explicitly states that floats are kept as is. So I would not say this is misleading at all.

If you can come up with a better formulation feel free to open a PR though!

**Comment by legendre6891** [comment]
You are right! I had misread the comment - thanks
