### ISSUE TITLE
Add method/setting to return the day of the week as a String or Categorical (vs. the current Int8 implementation) 

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#13374]
### Description

It's a small feature ask, aiming to easily get a date's day of the week as a string/categorical.

This is not hard to do:

```python

WEEKDAY_NAMES = {
            1:'Monday',
            2:'Tuesday',
            3:'Wednesday',
            4:'Thursday',
            5:'Friday',
            6:'Saturday',
            7:'Sunday'
        }

df.with_columns(dayOfWeekName = pl.col('date').dt.weekday().replace(WEEKDAY_NAMES)
```

But it is a super common task, and I've written that hard-coded dict one-too-many times. 

I would consider adding a `named` keyword to weekday() that returns the pre-defined weekdays or adding a `weekday_name()` method to the `dt` namespace.

Note that I'd just monkey-patch this on my end, but I could not figure out how to do that on the `pl.Expr.dt` namespace.

**Comment by cmdlineluser** [comment]
You can use to_string/strftime instead of a dict - but a direct method seems like a good idea.

```python
>>> pl.Series([datetime.date.today()]).dt.to_string("%A")
shape: (1,)
Series: '' [str]
[
	"Tuesday"
]
```

I think it's `.day_name` in pandas.

**Comment by mkleinbort-ic** [comment]
Ok, that solves it

**Comment by mkleinbort-ic** [comment]
Maybe I was too quick. My issue is solved, but I'll leave this issue open till EOD in case anyone wants to advocate for a dedicated method.

**Comment by ritchie46** [comment]
No need to clutter the API if we have `to_string` with many options right?

**Comment by MarcoGorelli** [comment]
yeah agree that the current API should be sufficient

closing then but thanks for the suggestion!
