### ISSUE TITLE
`version` parameter in deprecation warnings is neither used nor guaranteed to be correct

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#13377]
### Issue Description

```python
def issue_deprecation_warning(message: str, *, version: str) -> None:
    """ ... """
    warnings.warn(message, DeprecationWarning, stacklevel=find_stacklevel())
```

I'm a bit unsure as to how the version parameter is meant to be used, as it requires that the developer know what the next polars release version number will be, which isn't possible in a PR: there's no guarantee the PR will be merged into main prior to the next version, so manually identifying the version in which the deprecation takes effect isn't easy to do.

What's the solution here? The best idea that comes to mind is for the release CI to run a script that replaces a specific deprecation tag/keyword with the version currently being released. In this case, we could remove the `version` parameter, and the above function would look something like:

```python
def issue_deprecation_warning(message: str, *, version: str) -> None:
    """ ... """
    warnings.warn(
        message,
        f"As of version ##deprecation_tag##, {DeprecationWarning}",
        stacklevel=find_stacklevel()
    )
```

and the CI could replace `##deprecation_tag##` with the version string. This way the tagged version would remain in the repo in perpetuity, and we would not need to rely on developers accurately providing the version.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3-rc.2
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.3 (main, Apr 15 2023, 14:44:51) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.14.0
fsspec:               2023.12.2
gevent:               23.9.1
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.24
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by stinodego** [comment]
It was added as a hint to other developers to help determine when the functionality can be removed. It doesn't have to be extremely accurate - patch version doesn't really matter. It's described clearly in the docstring:

```
version
        The Polars version number in which the warning is first issued.
        This argument is used to help developers determine when to remove the
        deprecated functionality.
```

I don't want to introduce more architecture around this to enforce version correctness. Additional checks on this will have runtime impact, which I want to avoid. And I also don't want to introduce additional CI checks for this.

The parameter is doing its job perfectly fine. I don't see any issues here.
