### ISSUE TITLE
Revert "outer" join back to behave like new "outer_coalesce"

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#13378]
### Description

After upgrading to the latest polars version I was surprised that my pipelines all produce multiplied columns until I checked the changelog and saw that "outer" was renamed to "outer_coalesce".

Please revert "outer" back to the previous behavior. Duplicating columns is a very unexpected behavior for "outer" joins.

Better:
1) have a separate "outer_explicit" option if I would really want to keep both columns. Did not see this in any other framework yet though
2) explicit join conditions: 
```sql
SELECT table1.key_column_a as a, table2.key_column_b as b 
FROM table1 FULL OUTER JOIN table2 
ON table1.key_column_a = table2.key_column_b
```

**Comment by ritchie46** [comment]
No, we will not. This follows behavior from SQL. `outer_joins` coalesce removes information. You can always set that `outer_coalesce`. We will not ping-pong between behaviors.

**Comment by Hoeze** [comment]
OK, then I'll start changing my code.
Thank you for your quick answer :+1:
