### ISSUE TITLE
map_dict behaviour broken

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#13370]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I don't have a fully reproducible example at the moment, but I noticed all the current behavior with `map_dict` got broken in quite unexpected ways.

Switching to replace and it works again. I know map_dict got deprecated but having the behaviour broken is quite surprising to see.

### Issue description

.

### Expected behavior

.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:               3.10.12 (main, Aug  9 2023, 14:47:34) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.14.0
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.1
numpy:                1.23.5
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              11.0.0
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by MarcoGorelli** [comment]
> I don't have a fully reproducible example at the moment

do you have a partially reproducible one? not really sure what to do here 😄

**Comment by ion-elgreco** [comment]
@MarcoGorelli hehe :) I will have to create on later

**Comment by ritchie46** [comment]
Isn't `map_dict` deprecated as well?

**Comment by ion-elgreco** [comment]
@ritchie46 it is but I was expecting it to still work as usual until removed :)

**Comment by cmdlineluser** [comment]
It's a bit of an odd edge case because the original `.map_dict` Python implementation is gone.

`.map_dict` dispatches to `.replace` which has since been re-implemented in Rust #13002

https://github.com/pola-rs/polars/blob/a6d62939ea5a8f9eed156e0420103c7bc0a96dae/py-polars/polars/expr/expr.py#L9815

**Comment by ritchie46** [comment]
is the replace broken as well then?

**Comment by ion-elgreco** [comment]
Maybe, I will check later. My map_dict code was using default=pl.first() and that didn't work anymore.
