### ISSUE TITLE
Plot example in docs has wrong value

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#13408]
### Description

In the docs the plot example has a wrong date for the last value

```python
from datetime import date
df = pl.DataFrame(
    {
        "date": [date(2020, 1, 2), date(2020, 1, 3), date(2020, 1, 3)],
        "stock_1": [1, 4, 6],
        "stock_2": [1, 5, 2],
    }
)
df.plot.line(x="date", y=["stock_1", "stock_2"])
```

the last value shoud be `date(2020, 1, 4)` (day should be 4 not 3)

### current
![image](https://github.com/pola-rs/polars/assets/25177421/2b40c8fe-2ea6-49fb-9e07-e462a6d1e074)

### new
![image](https://github.com/pola-rs/polars/assets/25177421/6a86929a-c074-40bf-bef7-8b2fcd8c2a52)

### Link

https://docs.pola.rs/py-polars/html/reference/dataframe/plot.html#plot

**Comment by MarcoGorelli** [comment]
thanks @JulianCologne for the report
