### ISSUE TITLE
Possible deprecated use of .year  in "aggregations"

### ISSUE THREAD

**Issue by Lvulis** [pola-rs/polars#13418]
### Description

Looking at the Expressions/Aggregations/Filtering section, the "compute_age" function doesn't work in `0.19.19`.
```Python
def compute_age() -> pl.Expr:
    return date(2021, 1, 1).year - pl.col("birthday").dt.year()
```
 There are a few things here - there is no `date` object found (use `pl.date` instead), and the `pl.date` object has no `.year` method. I found this function worked but get quite different results from the current docs (which are probably outdated calls from that url). 

```Python
def compute_age() -> pl.Expr:
    return pl.date(2021, 1, 1)..year() - pl.col("birthday").dt.year()
```

### Link

https://docs.pola.rs/user-guide/expressions/aggregation/#filtering

**Comment by mcrumiller** [comment]
Yikes, yeah that needs updating, and the formula will not correctly compute the age. Quick help though: the date is a `datetime.date` object, which does have the year property:

```python
from datetime import date  # see here
import polars as pl

def compute_age():
    return date(2021, 1, 1).year - pl.col("birthdate").dt.year()

df = pl.DataFrame({
    "birthdate": [date(1950, 1, 1)],
})

df.select(compute_age())
```
```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 71      │
└─────────┘
```

**Comment by Lvulis** [comment]
Ah, thanks! That makes way more sense. Is the need for an update because of the overall syntax?

Also, I'm revisiting reading through docs after the holidays and just had this doc open so jogging my memory here. I see `date` and `datetime` are imported from `datetime` in the Column Selections subchapter/section. Would it make sense to add an explicit import call to `datetime` on this page as well?
