### ISSUE TITLE
Comparison of NaNs behaves different inside polars than in the native data type.

### ISSUE THREAD

**Issue by romarowski** [pola-rs/polars#13413]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
a = pl.Series([float('nan'), float('nan')])
print(a>10)
print(a<10)
print(float('nan')>10)
print(float('nan')<10)
```

| bool |
|-------|
| true |
| true |

| bool |
|-------|
| false |
| false |

False

False

### Issue description

I am not sure if this is the expected behavior which it might be but could not find it in the doc.

### Expected behavior

I guess I would expect comparison to NaN to return False but maybe there are good reasons why this is not good.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
Our logic is that NaN values are considered greater than any non-NaN value, and equal to themselves. So this is not a bug.

I can't tell you much about the considerations here - @orlp could. I don't know why Python made their design choice.

**Comment by orlp** [comment]
This is documented in the user guide: https://docs.pola.rs/user-guide/concepts/data-types/overview/#floating-point.

Python made their design choice because they follow the IEEE-754 standard. We made our design choice because having a total order of floats is more useful for having consistent ordering for sorting and searching than being pedantic about how NaNs are technically not ordered. Most databases make this choice as well.

**Comment by romarowski** [comment]
thank you really appreciate the explanation.
