### ISSUE TITLE
.fill_null on date columns changes (valid) dates into integers

### ISSUE THREAD

**Issue by knutmerket** [pola-rs/polars#13411]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import date, timedelta

# Cols
dates = [date.today()+ timedelta(days=i) for i in range(5)]
other_col = [1, 2, 3, 4, None]

# Create Polars DataFrame
data = {'date': dates, 'values': other_col}
df = pl.DataFrame(data)

# Replace nulls with zeros. This is where the date col is changed into an i32 col with the dates represented as integer values
(df
.select(pl.all().fill_null(0))
#.with_columns(pl.all().fill_null(0))
)
```

```
Out[2]: 
shape: (5, 2)
┌───────┬────────┐
│ date  ┆ values │
│ ---   ┆ ---    │
│ i32   ┆ i64    │
╞═══════╪════════╡
│ 19725 ┆ 1      │
│ 19726 ┆ 2      │
│ 19727 ┆ 3      │
│ 19728 ┆ 4      │
│ 19729 ┆ 0      │
└───────┴────────┘
```

Datetime output:

```
Out[4]: 
shape: (5, 2)
┌──────────────────┬────────┐
│ datetime         ┆ values │
│ ---              ┆ ---    │
│ i64              ┆ i64    │
╞══════════════════╪════════╡
│ 1704284838841649 ┆ 1      │
│ 1704371238841661 ┆ 2      │
│ 1704457638841664 ┆ 3      │
│ 1704544038841666 ┆ 4      │
│ 1704630438841667 ┆ 0      │
└──────────────────┴────────┘
```

### Issue description

The problem is pretty simple: Using .fill_null() on a date column will return the date column as an i32 column where valid date values are changed into their integer representation. The same behavior happens with datetime columns (but i64 instead of i32). I haven't tested with other column dtypes than these.

I am currently on polars 0.19.12, but MarcoGorelli confirmed (Discord) that the issue exists on the latest version too.

### Expected behavior

In this example, since there are no nulls in the date/datetime column, the expected behavior would be that the date column remained unchanged.

In cases where the date/datetime column did in fact contain nulls, I would expect an error message if the value parameter set in .fill_null was not a valid value for the dtype of the column (e.g. 0 as in this example, or a string, etc.)

### Installed versions

<details>

```
In [2]: pl.show_versions()
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-4.14.326-245.539.amzn2.x86_64-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          3.7.0
numpy:               1.24.1
openpyxl:            3.1.0
pandas:              2.0.1
pyarrow:             11.0.0
pydantic:            1.10.6
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            0.8.1
xlsxwriter:          3.1.5
```

</details>

**Comment by mcrumiller** [comment]
I'm not sure if this is an error, but maybe it is. If you `fill_null` with a different dtype than the series, the series gets upcast to whatever dtype works:

```python
import polars as pl
from datetime import date

print(pl.Series([date(2023, 1, 1), None]).fill_null("a"))             # series converted to str
print(pl.Series([date(2023, 1, 1), None]).fill_null(pl.lit([1, 2])))  # series converted to list
print(pl.Series(["a", None]).fill_null(1))                            # series remains str
print(pl.Series([1, None]).fill_null("a"))                            # series converted to str
```

Temporals and ints are more or less interchangeable (because temporals happen to be backed by ints) so I'm not sure how we want to handle that casting. I don't like the idea of underlying physical dtypes affecting output behavior (i.e. if our date implementation were to change to non-ints, would fill_null behavior change too?). @MarcoGorelli what do you think?

**Comment by MarcoGorelli** [comment]
I think I'd expect `fill_null` to only accept
- a value of the same type
- `null`

and to raise on anything else

**Comment by mgirlich** [comment]
Not so long ago in the R language the tidyverse team had similar issues and they came up with the [vctrs package](https://vctrs.r-lib.org/index.html) to solve this and provide some solid theory to it as well. Important concepts are [type and size stability](https://vctrs.r-lib.org/articles/stability.html) and [prototypes and sizes](https://vctrs.r-lib.org/articles/type-size.html).
Another interesting idea is the difference between [casting and coercion](https://vctrs.r-lib.org/articles/s3-vector.html#casting-and-coercion).
Introducing this solved a lot of issues and made all of the tidyverse (so in particular dplyr and tidyr) so much more predictable and also much easier to understand.

> I think I'd expect `fill_null` to only accept
> 
> * a value of the same type
> * `null`
> 
> and to raise on anything else

Looking at this with the theory from the vctrs package in mind I would argue that this is not quite correct. Instead, it should try to find a common type and cast the values to this common type. So, one could still fill Int64 with Int32 and I think also Int64 with Float64:

```python
df = pl.DataFrame({"x": [0, None]})
df.with_columns(pl.col("x").fill_null(2.5))
```

```
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ f64 │
╞═════╡
│ 0.0 │
│ 2.5 │
└─────┘
```

**Comment by stinodego** [comment]
Thanks for the report. Closing in favor of https://github.com/pola-rs/polars/issues/13789
