### ISSUE TITLE
Harmonize Expr.where with Expr.filter, or deprecate it

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13425]
### Description

`Expr.filter` is currently:

```python
Expr.filter(*predicates: IntoExprColumn | Iterable[IntoExprColumn], **constraints: Any) 
```
whereas `Expr.where` is still:
```python
Expr.where(predicate: Expr)
```

`Expr.where` should either be harmonized to have the same signature as `Expr.filter`, or be deprecated. I personally like deprecating it because there's a `df.filter` but no `df.where`, so deprecating `Expr.where` would be more consistent.

**Comment by stinodego** [comment]
Agreed, let's deprecate.
