### ISSUE TITLE
No module named `polars.testing`

### ISSUE THREAD

**Issue by AroneyS** [pola-rs/polars#13422]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from polars.testing import assert_frame_equal
# ModuleNotFoundError: No module named 'polars.testing'
```

### Issue description

Installed polars v0.20.3 using conda.
Has the Polars testing module been removed? Similar error for

```python
import polars as pl
pl.show_versions()
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# AttributeError: module 'polars' has no attribute 'show_versions'
```

### Expected behavior

Load assert_frame_equal function from testing module.

### Installed versions

<details>

```
AttributeError: module 'polars' has no attribute 'show_versions'
```

</details>

**Comment by mcrumiller** [comment]
There is something wrong with your installation, both the import and the `show_versions` should work.

**Comment by AroneyS** [comment]
I think its this: https://github.com/conda-forge/polars-feedstock/issues/205

**Comment by stinodego** [comment]
I think so too. Closing this for now. If the issue persists after the conda-forge issue is resolved, please comment here and I'll re-open.
