### ISSUE TITLE
Allow strptime to work with Hour but not minute (ie. assume 0)

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#13449]
### Description

Suppose I have

```
pl.select(pl.lit("2023010413-0500").str.strptime(pl.Datetime, "%Y%m%d%H%z"))
```
It generates an error `ComputeError: Invalid format string: Please either specify both hour and minute, or neither.`

It should just assume if the minute is missing that it's 0. To workaround this is both annoying and tedious because of the string splitting involved but because of the string manipulation, much less efficient.

**Comment by MarcoGorelli** [comment]
I agree but this is blocked by chrono unfortunately https://github.com/chronotope/chrono/issues/1075

**Comment by deanm0000** [comment]
Curse those handsome devils
