### ISSUE TITLE
selectors not initilized when using python v 3.10 and above

### ISSUE THREAD

**Issue by blongbs** [pola-rs/polars#13451]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
python version 3.12.0
polars v 0.20.3
OS windows 11 KB5033369 (OS Build 22000.2652)
```

### Log output

```shell
using vscode prior to running any python code the feature
import polars.selectors as cs is not found
```

### Issue description

with polars v 0.20 and above the selectors lib is not functional. the feature does not work with python v 3.10; 3.11; or 3.12.

### Expected behavior

polars v 0.19.3 works correctly and loads the selectors. Odd the newest version is missing

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by alexander-beedie** [comment]
Hmm, it definitely does work. However, we did hear that the latest `conda` build is broken in a way that sounds quite similar to what you're describing; you can see this issue for details: https://github.com/conda-forge/polars-feedstock/issues/205. Can you confirm if you installed via conda? (Note that we don't provide the conda builds ourselves, so you should probably follow that issue for resolution) 👍

**Comment by stinodego** [comment]
I am closing this as it is almost certainly related to the conda-forge issue that Alex linked. If not, please post here and I will reopen.
