### ISSUE TITLE
Address `py-polars/rust-toolchain.toml` symbolic link preventing compilation in Windows

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#13466]
### Issue Description

Currently, the only thing stopping a fresh `git clone` from compiling directly on Windows is the usage of the symbolic link in `polars/py-polars/rust-toolchain.toml` which points to `polars/rust-toolchain.toml`. Git for Windows does not enable symbolic links by default, as it requires administrator access, and as a result the symbolic link file results in an invalid toml file that prevents compilation.

This issue arose on Discord and the suggestion was to use WSL. However, since this is the *only* thing preventing compilation on Windows, I think we should replace the symbolic link with a file copy, and just ensure that we keep the two in sync. Enabling Windows compilation is pretty useful for people that want to compile for their particular hardware with all optimizations enabled.

**Comment by stinodego** [comment]
I don't want to get rid of the symbolic link. Having the toolchain information in multiple places is error prone. The file is there to facilitate `pip install` of the sdist (maturin wants it there).

If you can find another way to make maturin find the toolchain information, it's welcome.

**Comment by mcrumiller** [comment]
@stinodego totally understandable, I'll look into it.

`pip install` works fine, it's when you run `maturin develop` or `maturin build` in the `py-polars` folder (which is where you have to run the command) it complains that the `rust-toolchain.toml` file is invalid, the reason being that the contents of the file are:

```toml
../rust-toolchain.toml
```

I'll see if I can find a good workaround that won't interfere with non-Windows users.

**Comment by stinodego** [comment]
Perhaps this is something that can be fixed by maturin. @messense what do you think?

**Comment by mcrumiller** [comment]
@stinodego I may have a solution.

According to the [rustup book](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), if a file called `rust-toolchain` (without toml extension) exists, it takes precendence over a `rust-toolchain.toml` file.

I'm replicating the Makefile as a windows batch file (`make.bat`) which will enable Windows users to run and compile everything. I've added to that script a check to see if `py-polars/rust-toolchain.toml` is either a sym link or a hard link to the file in the base directory. If it is neither (meaning the symlink didn't properly configure when the polars repo was grabbed), then a hard link is created from `rust-toolchain.toml` to `py-polars/rust-toolchain` (no extension). This doesn't interfere at all with our repository and it means for Windows users, they'll be using that file instead.

An alternative, which I'm not sure is possible, is to have `py-polars/rust-toolchain.toml` be a hard link instead of a sym link. Windows symbolic links require administrator access but hard links do not (why I have no clue).

**Comment by stinodego** [comment]
Apparently this is an issue with Git for Windows not properly supporting symbolic links.

I really don't want to include any additional tech or workarounds for this at this point. We clearly mention in the user guide that the setup for Windows may not work as expected and suggest using WSL.

I want to thank you for signalling this issue - we can take it into account if we restructure our build process in the future. But the solutions put forward so far (separate set of makefiles for windows, move away from `make`, get rid of the symbolic link) simply don't sound like good steps forward at this point.

We can reconsider in the future.

**Comment by mcrumiller** [comment]
@stinodego can I add a very minor section in the user guide for "compiling on Windows" that describes the `rust-toolchain` fix? This is not even really for development (which should be done on WSL) but more for peopl who want to perform a native compliation step to get more performance if they use Python in Windows.

**Comment by stinodego** [comment]
Definitely! I think the existing note can be amended. Maybe something like this:

> Note that if you are a Windows user, the steps below might not work as expected; try developing using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Under native Windows, you may have to manually copy the contents of `toolchain.toml` to `py-polars/toolchain.toml`, as Git for Windows may not correctly handle symbolic links.
