### ISSUE TITLE
Add a method to extract a column as a series

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1346]
Would it be possible to add a method to grab a column as a series?

Not sure of a name, but something like `.pull()` or `.grab()`?

Edit: Per [this comment](https://github.com/pola-rs/polars/issues/1346#issuecomment-918352312), maybe `.get_column()`.

So this:
```python
import polars as pl
from polars import col
import numpy as np

df = pl.DataFrame({'groups': ['a', 'a', 'b'],
                   'values': np.arange(1, 4)})

df.get_column('values')
```

Would be equivalent to this:
```python
df['values']
```

Similar idea to how these are equivalent:
```python
df.select('groups', 'values')
df[['groups', 'values']]
```

**Comment by ghuls** [comment]
You can get it with:
```python
In [16]: df.select(['values']).get_columns()[0]
Out[16]: 
Series: 'values' [i64]
[
	1
	2
	3
]
```

**Comment by markfairbanks** [comment]
> You can get it with: df.select(['values']).get_columns()[0]

@ghuls Thanks for the response, but this seems like a much longer option compared to `df['values']`.

One of the main reasons for this FR is that polars relies on method chaining - but there isn't an easy one to grab a single column as a series.

**Comment by ghuls** [comment]
A new `get_column`method would probably be the most consistent (with the `get_columns`

**Comment by markfairbanks** [comment]
That sounds good to me - `.get_column()` would return a single column as a series, `.get_columns()` would return the columns as a list of series.

It makes sense to be able to specify the column you want in `.get_column()`:

```python
df.get_column('values')
```

Does it also make sense to be able to select columns within `.get_columns()`, with the default being all columns?

```python
df.get_columns('groups', 'values')
```

**Comment by ritchie46** [comment]
`def get_column() -> pl.Series` seems good to me.

**Comment by markfairbanks** [comment]
Works great, thanks @ritchie46 👍

**Comment by Buedenbender** [comment]
Sorry to dig this up Is there anything similar for the lazy API / the LazyFrame? Or would one need to `.collect()` first?

**Comment by wangjiawen2013** [comment]
> Sorry to dig this up Is there anything similar for the lazy API / the LazyFrame? Or would one need to `.collect()` first?

I have the same question!
