### ISSUE TITLE
Request for the function to delete only columns that are nan or null

### ISSUE THREAD

**Issue by jnhyeon** [pola-rs/polars#13479]
### Description

In pandas, dropna(axis=0) removes row-based data, and dropna(axis=1) deletes column-based data.

I need the function to delete by column in polars' drop_nans or drop_nulls as well.

Thank you

**Comment by ritchie46** [comment]
Changing the schema based on the data is a design footgun. It is something that is forbidden in most of Polars API except for `pivot`, but that is also the reason `pivot` doesn't exist on the lazy API.

If you want to you can use easily make a function that does this. See below.

But now your design will break once you get new business data with different missing as downstream code expected `column b` to be available. 

```python
df = pl.DataFrame({
    "a": [1, None],
    "b": [1, 2],
})


def select_no_nulls(df: pl.DataFrame) -> pl.DataFrame:
    has_nulls = df.select(pl.all().is_null().any()).to_dict()
    
    selection = []
    for (name, has_nulls) in has_nulls.items():
        if not has_nulls.item():
            selection.append(name)
            
    return df.select(selection)
    
df.pipe(select_no_nulls)
```

**Comment by jnhyeon** [comment]
I understand Polars' design philosophy.
The code you gave me works fine.
Thank you
