### ISSUE TITLE
pl.Expr.cum_count should not count nulls ALSO create pl.cum_count for counting rows

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#13473]
### Description

`pl.Expr.count` was recently changed to not count nulls but `pl.Expr.cum_count` wasn't also changed. If `pl.Expr.cum_count` is changed to not count nulls then it would be nice to have a `pl.cum_count` to count rows without influence of `pl.first()` having nulls in it.

**Comment by mcrumiller** [comment]
Reference issue: #5396

**Comment by stinodego** [comment]
I am working on the `cum_count` function.

**Comment by sun-rs** [comment]
@stinodego to be honest, if `cum_count` starts at 0 is wrong, when you get the first element from a list, why use 0 as index, if should be 1. People use list or pandas for so many years. I think it is hard to change the habit.

**Comment by stinodego** [comment]
An index starts at 0. Indexing has nothing to do with `cum_count`, which is an aggregation function.

`cum_count` returns an equivalent of the the `count` aggregation at each point in the column. If we take the `count` of a column consisting of a single non-null element, the result is 1, not 0.
