### ISSUE TITLE
The default algorithm of the quantile is not the same between Pandas and py-polars

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#13480]
Edit: this is not a bug of Rust, See below comments.

### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I noticed in https://github.com/pola-rs/r-polars/pull/601#discussion_r1431563084

Sorry I don't understand the details of the difference in calculation methods, but here is an example that I can reproduce in Python:

```python
>>> import pandas as pd
>>> import polars as pl
>>> pl_df = pl.read_csv("https://raw.githubusercontent.com/plotly/datasets/77bbf9b631991002983d9bdba2af21ecab7e2eb8/mtcars.csv")
>>> pl_df.quantile(0.75)
shape: (1, 12)
┌──────────────┬──────┬─────┬───────┬───┬─────┬─────┬──────┬──────┐
│ manufacturer ┆ mpg  ┆ cyl ┆ disp  ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
│ ---          ┆ ---  ┆ --- ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ str          ┆ f64  ┆ f64 ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
╞══════════════╪══════╪═════╪═══════╪═══╪═════╪═════╪══════╪══════╡
│ null         ┆ 22.8 ┆ 8.0 ┆ 318.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
└──────────────┴──────┴─────┴───────┴───┴─────┴─────┴──────┴──────┘
>>> pl_df.to_pandas().quantile(0.75, numeric_only=True)
mpg      22.80
cyl       8.00
disp    326.00
hp      180.00
drat      3.92
wt        3.61
qsec     18.90
vs        1.00
am        1.00
gear      4.00
carb      4.00
Name: 0.75, dtype: float64
```

### Issue description

Pandas and Polars have different values for the 0.75 quartile point in the "disp" column of the mtcars dataset.

Polars reports 318.0
Pandas reports 326.0

R reports 326.0

``` r
quantile(mtcars$disp)
#>      0%     25%     50%     75%    100%
#>  71.100 120.825 196.300 326.000 472.000
```

<sup>Created on 2024-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`mtcars$disp` is this:

```r
> mtcars$disp |> sort() |> cat(sep = "\n")
71.1
75.7
78.7
79
95.1
108
120.1
120.3
121
140.8
145
146.7
160
160
167.6
167.6
225
258
275.8
275.8
275.8
301
304
318
350
351
360
360
400
440
460
472
```

Perhaps the following differences in calculation results are also relevant?

```python
>>> import pandas as pd
>>> pd.Series([318, 350]).quantile(0.25)
326.0
>>> import polars as pl
>>> pl.Series("a", [318, 350]).quantile(0.25)
318.0
```

### Expected behavior

The value should 326.0.

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by Object905** [comment]
Seems like this difference is due to different default values for `interpolation` argument.
For pandas it is `linear`, while in polars it is `nearest`.

```python
In [1]: import pandas as pd

In [2]: pd.Series([318, 350]).quantile(0.25)
Out[2]: 326.0

In [3]: import polars as pl

In [4]: pl.Series("a", [318, 350]).quantile(0.25)
Out[4]: 318.0

In [5]: pl.Series("a", [318, 350]).quantile(0.25, interpolation="linear")
Out[5]: 326.0

In [6]: pd.Series([318, 350]).quantile(0.25, interpolation="nearest")
Out[6]: 318
```

**Comment by eitsupi** [comment]
> Seems like this difference is due to different default values for `interpolation` argument.
> For pandas it is `linear`, while in polars it is `nearest`.

Thanks for pointing this out!
Sorry for my lack of research, i.e., this is due to a difference in default values for Python functions, not a bug in Rust......

Would it be worth changing the default value to the same as Pandas? (maybe this is came from R?)

According to the R documentation, the default value seems to come from S?
https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile

**Comment by ritchie46** [comment]
> Would it be worth changing the default value to the same as Pandas?

Why? You can specify the behavior you want right?

**Comment by deanm0000** [comment]
Polars makes no sales pitch that it aspires to mirror pandas. Instead you can (mostly) count on polars's defaults to be the most computationally and/or memory efficient.

**Comment by eitsupi** [comment]
I think there is basically no problem, but it seems that `describe` calculates percentiles using the default algorithm, so `describe` will probably display different values ​​for Pandas and Polars.
This may be unexpected for users. (And there are no options here that allow the user to change the behavior)

```python
>>> import polars as pl
>>> pl.Series("a", [318, 350]).describe()
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2.0       │
│ null_count ┆ 0.0       │
│ mean       ┆ 334.0     │
│ std        ┆ 22.627417 │
│ min        ┆ 318.0     │
│ 25%        ┆ 318.0     │
│ 50%        ┆ 350.0     │
│ 75%        ┆ 350.0     │
│ max        ┆ 350.0     │
└────────────┴───────────┘
>>> import pandas as pd
>>> pd.Series([318, 350]).describe()
count      2.000000
mean     334.000000
std       22.627417
min      318.000000
25%      326.000000
50%      334.000000
75%      342.000000
max      350.000000
dtype: float64
```

**Comment by ritchie46** [comment]
> will probably display different values ​​for Pandas and Polars.

Which is fine.
