### ISSUE TITLE
Make df.n_unique() and df.approx_n_unique() have the same semantics

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13498]
### Description

Currently `df.n_unique()` give the number of unique rows (as a scalar), whereas `df.approx_n_unique()` gives the number of unique elements in each column (as a `DataFrame`). These should have the same semantics.

**Comment by ritchie46** [comment]
This is the problem of exposing those things on a `DataFrame`. Things get ambigous (rows, vs columns). I think `approx_n_unique` should be deprecated and finally removed from the `DataFrame`.
