### ISSUE TITLE
`melt` panics when `id_vars` is a non-existing column

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13493]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = (
    pl.DataFrame({"col0": [0], "col1": ["a"], "col2": ["b"]})
    .lazy()
    .melt(id_vars="row_nr")
    .collect()
)
# pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-plan/src/logical_plan/builder_functions.rs:22:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 6, in <module>
    .melt(id_vars="row_nr")
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 5409, in melt
    self._ldf.melt(id_vars, value_vars, value_name, variable_name, streamable)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

In lazy mode this panics. In eager mode, this returns a somewhat sensible error:

polars.exceptions.SchemaFieldNotFoundError: row_nr

### Expected behavior

Throw a proper error.

### Installed versions

main branch

**Comment by lukemanley** [comment]
This no longer panics. It now raises:

```ColumnNotFoundError: 'unpivot' on column: 'row_nr' is invalid```
