### ISSUE TITLE
Remove Pandas dependency from `write_database` (using SQLALchemy)

### ISSUE THREAD

**Issue by fdcastel** [pola-rs/polars#13513]
### Description

The current implementation relies on pandas `to_sql()`. This is just a wrapper for SQLAlchemy, which does all the heavy lifting.

If interested, I could work on a PR to remove this dependency and write a proper Polars -> SQLAlchemy implementation, focusing on performance (whenever possible ,given SQLAlchemy capabilities).

Related: https://github.com/pola-rs/polars/pull/7322

**Comment by alexander-beedie** [comment]
FYI: we have an earlier issue touching on the rewrite for `write_database`, can find it here: https://github.com/pola-rs/polars/issues/7852. It's going to be a significant bit of work to ensure that it is (relatively) backend agnostic and fast-path aware without taking on additional dependencies (hence not having started on it yet!)

Do you happen to have a lot of familiarity with database write/insert performance from python across a range of backends? If so, please feel free to contribute to the linked issue with any insights ;)

(In the meantime I'll close this out as a duplicate - thanks for the interest!)
