### ISSUE TITLE
`sink_ndjson()` doesn't appear in docs

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#13533]
### Description

`sink_ndjson()` doesn't appear on the docs website, but it was implemented a few weeks ago in #10786.

![image](https://github.com/pola-rs/polars/assets/52219252/732f2c55-e303-450a-87ad-2491b7f59262)

### Link

https://docs.pola.rs/docs/python/dev/search.html?q=ndjson

**Comment by cmdlineluser** [comment]
I think it just needs to be added here:

https://github.com/pola-rs/polars/blob/67507fffbff54679a4ff0e11f602b41e3ad6b99f/py-polars/docs/source/reference/io.rst?plain=1#L55-L58
