### ISSUE TITLE
Implement .collect() as alias for .clone() for DataFrame

### ISSUE THREAD

**Issue by erikamundson** [pola-rs/polars#13549]
### Description

It would be convenient to allow calls to `.collect()` on a DataFrame to return a copy (same behavior as `.clone()`).

Currently LazyFrame allows `.lazy()` which allows us to write a function that accepts either a LazyFrame or a materialized DataFrame and returns a Lazy copy of that object. 

```python
def ensure_lazy(frame: DataFrame | LazyFrame) -> LazyFrame:
    return frame.lazy()
```

It would be useful to also be able to write a similar function that always returns a materialized DataFrame.

```python
def ensure_materialized(frame: DataFrame | LazyFrame) -> DataFrame:
    return frame.collect()
```

We can get around it right now by calling `frame.lazy().collect()` but there may be additional overhead to converting from DataFrame to Lazy and back again, rather than just cloning the DataFrame directly.

Happy to give this a go myself if approved.

**Comment by Wainberg** [comment]
I mean, if `lf.lazy()` is a lazyframe, then `df.collect()` should be a dataframe.

**Comment by MarcoGorelli** [comment]
I think this was discussed and rejected, could you search the issue tracker please?

**Comment by erikamundson** [comment]
Ah sorry @MarcoGorelli I missed that when searching. Will close this one.
