### ISSUE TITLE
Ordering guarantees for implicit window functions like `cum_sum` and `forward_fill`

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#13544]
Does Polars prevent predicates from being pushed through projections that use implicit window functions like `cum_sum` or `forward_fill`? Polars should in theory do something like that, because the result can depend on whether or not the predicate gets pushed through the projection. Here's an example where the results are different depending on whether the selection (predicate) happens before or after the projection:

```python
In [1]: import polars as pl

In [2]: df = pl.DataFrame({"x": [1, 2, 3, 4]})

In [3]: (
   ...:     df
   ...:     .with_columns(x_cum_sum = pl.col("x").cum_sum())
   ...:     .filter(pl.col("x") != 3)
   ...: )
Out[3]:
shape: (3, 2)
┌─────┬───────────┐
│ x   ┆ x_cum_sum │
│ --- ┆ ---       │
│ i64 ┆ i64       │
╞═════╪═══════════╡
│ 1   ┆ 1         │
│ 2   ┆ 3         │
│ 4   ┆ 10        │
└─────┴───────────┘

In [4]: (
   ...:     df
   ...:     .filter(pl.col("x") != 3)
   ...:     .with_columns(x_cum_sum = pl.col("x").cum_sum())
   ...: )
Out[4]:
shape: (3, 2)
┌─────┬───────────┐
│ x   ┆ x_cum_sum │
│ --- ┆ ---       │
│ i64 ┆ i64       │
╞═════╪═══════════╡
│ 1   ┆ 1         │
│ 2   ┆ 3         │
│ 4   ┆ 7         │
└─────┴───────────┘
```

More generally speaking, is there any way to ensure that the implicit window functions are applied to rows with a well-defined order? This is related to my still open request to add an `ORDER BY` keyword to the `over` method: #8662.

If there are already some guarantees around the ordering of implicit window functions, it would be good to document them in the manual and the API docs.

**Comment by stinodego** [comment]
I think you answered your own question with your examples. Predicates should not be pushed down if it affects the result. If it does, that's a bug.

This seems pretty natural to me, but maybe it's not to everyone. If you feel like this isn't clear in the documentation, you're welcome to add to it. I think the relevant section is here:
https://docs.pola.rs/user-guide/lazy/optimizations/

I'll close this for now.
