### ISSUE TITLE
Datetime value assignment ignored

### ISSUE THREAD

**Issue by mdaehl** [pola-rs/polars#13547]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Running 
```python
from datetime import datetime
import polars as pl

df = pl.DataFrame(
    {
        "date": [None, None],
        "count": [1, 2]
    },
    schema={"date": datetime, "count": pl.Int64}
)

df[0, "date"] = pl.Series([datetime.today()])
print(df)
```
results in:
```
shape: (2, 2)
┌──────────────┬───────┐
│ date         ┆ count │
│ ---          ┆ ---   │
│ datetime[μs] ┆ i64   │
╞══════════════╪═══════╡
│ null         ┆ 1     │
│ null         ┆ 2     │
└──────────────┴───────┘
```

However, when atleast one value in the date column is set, the assignment works as desired. The code:
```python
from datetime import datetime
import polars as pl

df = pl.DataFrame(
    {
        "date": [None, datetime.today()],
        "count": [1, 2]
    },
    schema={"date": pl.Datetime, "count": pl.Int64}
)

df[0, "date"] = pl.Series([datetime.today()])
print(df)
```
results in:

```
shape: (2, 2)
┌────────────────────────────┬───────┐
│ date                       ┆ count │
│ ---                        ┆ ---   │
│ datetime[μs]               ┆ i64   │
╞════════════════════════════╪═══════╡
│ 2024-01-08 22:32:00.113570 ┆ 1     │
│ 2024-01-08 22:32:00.111568 ┆ 2     │
└────────────────────────────┴───────┘
```

### Issue description

As shown in the example, the assignment of a date to a specific entry in a Datetime column is ignored without any info or error message. Therefore, if a date column is initalized with solely None values, it is impossible to set any date afterwards.

### Expected behavior

The expected behaviour is shown in the second code example. Assigning a new value to a cell should actually change the dataframe.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.1
openpyxl:             3.1.2
pandas:               2.1.2
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by mcrumiller** [comment]
Hi @mdaehl, a few issues here:

* you are trying to assign a series to a scalar position. Polars allows you to assign assignments using the syntax you have provided, but you need to specify a scalar. Example:
    ```python
    import polars as pl

    df = pl.DataFrame({"a": [1, 2, 3]})
    df[1, "a"] = 5
    ```
    ```
    shape: (3, 1)
    ┌─────┐
    │ a   │
    │ --- │
    │ i64 │
    ╞═════╡
    │ 1   │
    │ 5   │
    │ 3   │
    └─────┘
     ```
    However, you are trying to assign it a series. So, while you're getting weird results, I think they should probably all error.
* Regardless, it looks like the scalar assignment does not work for dates any way. This is probably an error, but we'll ask @ritchie46 or @stinodego whether or not the assignment operator should work for scalars as in the example above.

For now, you can use expression syntax, as follows:

```python
from polars import col, when
df = df.with_row_count("#").with_columns(
    when(col("#") == 0).then(datetime.today()).otherwise(col("date")).alias("date")
).drop("#")
```
```
shape: (2, 2)
┌────────────────────────────┬───────┐
│ date                       ┆ count │
│ ---                        ┆ ---   │
│ datetime[μs]               ┆ i64   │
╞════════════════════════════╪═══════╡
│ 2024-01-08 18:19:20.908023 ┆ 1     │
│ 2024-01-08 18:18:42.589946 ┆ 2     │
└────────────────────────────┴───────┘
```

**Comment by ritchie46** [comment]
@stinodego can you take a look at this one? I think we should raise here.

**Comment by stinodego** [comment]
I tracked this down to an issue in the `scatter` implementation. It happens here:
https://github.com/pola-rs/polars/blob/df139a6017ba4039d5fac4a8ce91925e99874cd2/crates/polars-ops/src/chunked_array/scatter.rs#L110-L128

The underlying array and its validity is mutably adjusted. However, the `null_count` of the ChunkedArray now no longer matches the validity of the underlying array.

Not sure what the best fix would be here.
