### ISSUE TITLE
Add docs example `dt.strftime('%A')` to get the day of the week

### ISSUE THREAD

**Issue by thomascamminady** [pola-rs/polars#13554]
### Description

I frequently find myself in a position where I prefer to work with workdays by name, rather than by their integer value so I run
```python
df.with_columns(
    pl.col("datetime")
    .dt.weekday()
    .replace(
        {
            1: "monday",
            2: "tuesday",
            3: "wednesday",
            4: "thursday",
            5: "friday",
            6: "saturday",
            7: "sunday",
        }
    )
    .cast(pl.Categorical)   # I have no strong feeling about the casting to categorical.
)
```

I think it would be nice if there exists a method that does this directly, something like
```python
df.with_columns(
    pl.col("datetime")
    .dt.day_name()
)
```

Note: I am new to contributing in open source software. If this would be a feature of interest, I'd be happy to give implementing it a try. I'd probably need some guidance though.

**Comment by MarcoGorelli** [comment]
you can do `.dt.to_string('%A')`

**Comment by MarcoGorelli** [comment]
closing then, but thanks for the suggestion!

**Comment by thomascamminady** [comment]
Oh, sorry for missing that. Thanks

**Comment by alexander-beedie** [comment]
FYI: in case you're wondering what the format string is, `to_string` is functionally an alias to `strftime`, so you could equally write `pl.col("datetime").dt.strftime("%A")`.

**Comment by alexander-beedie** [comment]
> I'm happy to give this a try as a first PR if that's okay :)

Sure, go for it; documentation contributions are very welcome 😎👍

**Comment by cmdlineluser** [comment]
I know there is a desire for not cluttering the API (#13374) but `day_name` and `month_name` seem common enough to warrant their own alias. 

```python
.dt.to_string("%A")
.dt.day_name()

.dt.to_string("%B")
.dt.month_name()
```

They're self-documenting, easier to find in the docs, etc.

**Comment by alexander-beedie** [comment]
The additional wrinkle with these formats (and one reason it isn't _quite_ so straightforward) is that the machine locale influences the output; you are not guaranteed a stable result. One user may get "Wednesday", another "Mercredi", and another "Mittwoch" ;)

**Comment by MarcoGorelli** [comment]
Are you sure about this? I thought chrono's `Datetime.format` (which Polars uses for `.to_string()`) always gives `"Monday" - "Sunday"` for `%A`, which is why in https://github.com/pola-rs/polars/issues/12341 they were asking for an option to pass the locale

**Comment by mkleinbort** [comment]
I would appreciate the functionality. In practice I would only use it for troubleshooting/EDA or to display nice data in a GUI setting, so being locale specific is not a big issue for me so long as it's very clear in the method docs.

**Comment by MarcoGorelli** [comment]
After discussion, `day_name` and `month_name` shouldn't necessarily default to English, but supporting different locales is out-of-scope for Polars - I'll add this to polars-xdt then

A doc note / example in `strftime` to get the day name / month name would still be good to have though
