### ISSUE TITLE
 ComputeError when applying an UDF in a `group_by` aggregation

### ISSUE THREAD

**Issue by trendelkampschroer** [pola-rs/polars#13557]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

if __name__ == "__main__":
    frame = pl.from_dict({"id": ["a", "a", "b", "b"], "values": [0.1, 0.1, -0.1, -0.1]})
    frame.group_by(by="id").agg(pl.col("values").log1p().sum().pipe(np.expm1))
>>>
Traceback (most recent call last):
  File "bug_udf_in_aggregation.py", line 5, in <module>
    frame.group_by(by="id").agg(pl.col("values").log1p().sum().pipe(np.expm1))
  File "polars/dataframe/group_by.py", line 240, in agg
    self.df.lazy()
  File "polars/lazyframe/frame.py", line 1749, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot aggregate, the column is already aggregated

Error originated in expression: 'col("values").log1p().sum().python_udf()'


```

### Issue description

The same expression was working in `polars-0.19.19`.

### Expected behavior

Should apply the UDF to the 'sum', no exception should be raised.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.3
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
I'm guessing this has to do with https://github.com/pola-rs/polars/pull/13181.

I'm on mobile otherwise I'd test myself but what if you put the np function in a separate `with_columns` after the agg?

**Comment by trendelkampschroer** [comment]
Thanks a lot for suggesting this fix. To me the current state seems a bit unintuitive, i.e. 

```python
import polars as pl

def expm1(values: pl.Expr) -> pl.Expr:
    return values.exp() - 1.0

if __name__ == "__main__":
    frame = pl.from_dict({"id": ["a", "a", "b", "b"], "values": [0.1, 0.1, -0.1, -0.1]})
    frame.group_by(by="id").agg(pl.col("values").log1p().sum().pipe(expm1))
```

is working perfectly fine, but with an unstable implmentation of `expm1`.

This means I cannot simply use a` numpy` 'ufunc' for replacing a missing compute expression. IMHO this diminishes the reusablity of ufuncs. 

Having the ability to substitute a 'ufunc' for an expression is a great thing since `polars` is free to implement only those expressions for specialised numerical operations that it deems important for a wide enough user base.

In that light I am thinking about reopening https://github.com/pola-rs/polars/issues/12891 since having available a stable `expm1` implementation would actually be beneficial now.

**Comment by deanm0000** [comment]
Turns out all the stock prebuilt ufuncs are elementwise so I made a PR to change how they're dispatched to using that flag.
