### ISSUE TITLE
Sorting with capitals produces wrong order

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#13589]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

df = pl.DataFrame(
    {
        "str_0": ["no", "YES"],
        "str_1": ["no", "yes"],
    }
)
print(df.sort("str_0"))
print(df.sort("str_1"))

```

outputs

```
shape: (2, 2)
┌───────┬───────┐
│ str_0 ┆ str_1 │
│ ---   ┆ ---   │
│ str   ┆ str   │
╞═══════╪═══════╡
│ YES   ┆ yes   │
│ no    ┆ no    │
└───────┴───────┘
shape: (2, 2)
┌───────┬───────┐
│ str_0 ┆ str_1 │
│ ---   ┆ ---   │
│ str   ┆ str   │
╞═══════╪═══════╡
│ no    ┆ no    │
│ YES   ┆ yes   │
└───────┴───────┘

```

### Issue description

Sorting strings with mixed capitals has wrong sorting result.

### Expected behavior

The resulting dataframes in the example should have the same ordering

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
This is actually correct; uppercase letters sort before lowercase letters for strings.

For example (Python):
```python
sorted(["no", "YES"])
# ['YES', 'no']
```

If you want a case-insensitive sort you will have to adjust the case in the sort expression:
```python
df.sort(pl.col("str_0").str.to_lowercase())
```

**Comment by thobai** [comment]
Thanks for the quick response, @alexander-beedie. Yet, I'm still confused as I get the opposite order when doing the same query with columns of type Categorical:

```python
df = pl.DataFrame(
    {
        "str_0": ["no", "YES"],
        "str_1": ["no", "yes"],
    }
).with_columns(pl.col(pl.Utf8).cast(pl.Categorical))
print(df.sort("str_0"))
```

outputs

```
shape: (2, 2)
┌───────┬───────┐
│ str_0 ┆ str_1 │
│ ---   ┆ ---   │
│ cat   ┆ cat   │
╞═══════╪═══════╡
│ no    ┆ no    │
│ YES   ┆ yes   │
└───────┴───────┘
```

It seems it is sorting by the physical value of the Categorical column, which to me is at least confusing, although I do see use cases where this might be helpful (e.g. joins on sorted columns of type Categorical). 

Is this intended? So do I have to always cast Categorical to Utf8 in order to get proper sorting?

**Comment by cmdlineluser** [comment]
The default ordering for Categoricals is `physical`


> polars.Categorical(ordering: CategoricalOrdering | [None](https://docs.python.org/3/library/constants.html#None) = 'physical')

You can choose `lexical` 

```python
pl.DataFrame({
    "str_0": ["no", "YES"],
    "str_1": ["no", "yes"],
}).sort(pl.col(pl.String).cast(pl.Categorical("lexical")))

# shape: (2, 2)
# ┌───────┬───────┐
# │ str_0 ┆ str_1 │
# │ ---   ┆ ---   │
# │ str   ┆ str   │
# ╞═══════╪═══════╡
# │ YES   ┆ yes   │
# │ no    ┆ no    │
# └───────┴───────┘
```

**Comment by alexander-beedie** [comment]
> Is this intended? So do I have to always cast Categorical to Utf8 in order to get proper sorting?

@thobai: It's intended, in the sense that the default ordering for `Categorical` is "physical" (so essentially unordered), which results in sort using the underlying ID rather than the string being encoded. However, don't worry! You _don't_ need to convert to string to get lexically ordered categorical.

In the latest releases you can declare your col as `pl.Categorical(ordering="lexical")` (or just `pl.Categorical("lexical")`). In earlier releases you'd have to cast the column explicitly using `col.cat.set_ordering("lexical")`. I'd recommend the more recent (and more user-friendly) syntax 😉
