### ISSUE TITLE
Clarify documentation for the `agg_list` argument in `Expr.map_batches`

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13612]
### Description

The [documentation for `Expr.map_batches`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.map_batches.html) pithily describes the function of the `agg_list` argument as `"Aggregate list"`. What does this argument do? It would be good to update the documentation.

**Comment by deanm0000** [comment]
It seems to be for map_elements. I don't think it has a practical usage outside of map_elements using it but I haven't messed with it much

**Comment by Wainberg** [comment]
`map_elements` doesn't have an `agg_list` argument, though.

**Comment by deanm0000** [comment]
Sorry, to clarify, map_elements calls map_batches and in doing so it sets that parameter in different conditions that I don't remember off hand.

**Comment by cmdlineluser** [comment]
Looks like it controls `Apply::ApplyList`

https://github.com/pola-rs/polars/blob/a8bdc76000c059afdac1f215e3b95654a0057712/crates/polars-plan/src/dsl/python_udf.rs#L209-L210

Which is defined here:

https://github.com/pola-rs/polars/blob/a8bdc76000c059afdac1f215e3b95654a0057712/crates/polars-plan/src/logical_plan/options.rs#L162-L172

**Comment by Wainberg** [comment]
Does it actually do anything? I haven't been able to find an example where it changes the result.
