### ISSUE TITLE
// integer division in python not working 

### ISSUE THREAD

**Issue by JoHNNyB92** [pola-rs/polars#1362]
Pretty straight forward i think it is very easy to be tested with every polars dataframe. If not, i can provide my example to check.

What I mean is that 5//2 should return 2, not 2.5.

Thanks a lot :D

**Comment by ritchie46** [comment]
Thanks, fixed in #1364

**Comment by JoHNNyB92** [comment]
My pleasure, thanks for your awesome job.

**Comment by ritchie46** [comment]
> thanks for your awesome job.

Your welcome!

Fixed and released.
