### ISSUE TITLE
Align null-value handling for all string concatenation functions

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#13633]
# Description
We currently have the following functions to `join/concat` strings, but they don't handle null values in exactly the same way:

### `str.concat`

It has an `ignore_nulls` argument to determine whether to ignore or propagate null values.

- ignore nulls
```python
s = pl.Series(["a", None, "b"])
s.str.concat(ignore_nulls=True)

# output 
Series: '' [str]
[
	"a-b"
]
```

- propagate nulls
```python 
s = pl.Series(["a", None, "b"])
s.str.concat(ignore_nulls=False)

# output
Series: '' [str]
[
	null
]

```

### `concat_str`
It propagates null values

```python
pl.select(pl.concat_str(pl.lit("a"), None, pl.lit("b")))

# output
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ null    │
└─────────┘
```

### `list.join`/`arr.join`
It take null values as string `null`. :)

```python
s = pl.Series([["a", None, "b"]], dtype=pl.List(pl.String))
s.list.join("-")

# output
Series: '' [str]
[
	"a-null-b"
]
```

# Proposal
Personally, there's a bit of weird that passing null values as the string `null`, but it both makes sense to ignore and propagate. So I propose aligning their behavior all toward `str.concat`. That is, introduce an `ignore-nulls` argument for `concat_str` and `list.join`, `arr.join`.

**Comment by JulianCologne** [comment]
yes, very nice ideas! I also found the insertion of the text `"null"` very strange 😆 

One proposal from my side: remove the `-` as the default and use an emtpy string instead! Reasons:
- `-` is super arbitrary, could be anything else `_`, `|`, `&`, `/` ...
- a default if often the "neutral" element like zero or in this case an empty string
- concatenation/joining texts together without any separator is very common! (more common than using `-` I would argue)
- very user friendly! Default just puts text together; If you want a separator be specific! 

thoughts? 😉

**Comment by alexander-beedie** [comment]
An `ignore_nuls` param for `concat_str` would be great, as it would both align with the equivalent Series function and allow us to properly replicate SQL behaviour when concatenating strings that include nulls, eg:

`CONCAT_WS(':', 'x',NULL,'y',NULL,NULL,'z')  →  'x:y:z'`

I also strongly agree with @JulianCologne that the default separator should be the empty string; `-` is an odd default. I think we should make a breaking change to fix this (in addition to adding `ignore_nulls` 🤔)

**Comment by alexander-beedie** [comment]
> Since this could be breaking change, let's wait a little while, and if there are no objections, I will prepare the corresponding PRs. :D)

Sounds good! And, yes, `""` is definitely the right default choice 💯👌
