### ISSUE TITLE
Rename argument-less pl.count() to pl.len()

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#13673]
We've had some back-and-forth internal discussion on this, but reports such as https://github.com/pola-rs/polars/issues/13669 convinced us that `pl.count()` (without an argument) counting the total number of rows is confusing when `pl.count(col)` only counts the non-null rows in that column.

The current behavior *is* similar to SQL, where `COUNT(*)` counts all rows but `COUNT(foo)` only the non-null rows in column `foo`. But it's still a bit confusing, especially to those unfamiliar with SQL.

So we're deprecating `pl.count()` (without an argument), renaming it in favor of a new function `pl.len()`. `pl.count(col)` is left unchanged, it still only counts non-null values.

**Comment by mcrumiller** [comment]
Do we want to use `pl.length()` so as not to clash with the native `len` which is pretty ubiquitous?

**Comment by orlp** [comment]
We already use `.len()` all over the place: https://docs.pola.rs/py-polars/html/search.html?q=len.

**Comment by stinodego** [comment]
> len of what?

It's the length of the context.

**Comment by deanm0000** [comment]
It doesn't seem confusing to me that `pl.count()` counts rows without regard to nulls. I mean what else could that do?

To take the next step, if we do `pl.count(col)` how could that not so something related to `col`? If we know/expect it to do something related to `col` then what else could that do besides count the values (ie not nulls) of that col?

Ultimately, I'm mostly indifferent but that's my 0.02

**Comment by cmdlineluser** [comment]
I think this means `GroupBy.count()` -> `GroupBy.len()` needs to also happen?

**Comment by mcrumiller** [comment]
No, because Groupy returns frames and not series, and there is no concept of a null row.

**Comment by stinodego** [comment]
`pl.cum_count()` would not make sense anymore, though. Maybe it becomes `pl.cum_len()`? Feels bad though.

**Comment by mkleinbort** [comment]
Also, I think a lot of the SQL users will be sad that pl.count() changes behaviour.

(I'm literally bummed out by this change)

**Comment by orlp** [comment]
> Also, I think a lot of the SQL users will be sad that pl.count() changes behaviour.

The SQL front-end would not change due to this.

And `pl.count` doesn't *change* behavior, part of its interface will be removed. I'm not proposing that `pl.count()` does something different, just that it will not be allowed anymore (giving a `DeprecationWarning` or error to use `pl.len()`).

**Comment by stinodego** [comment]
I was initially also sceptical of this change, as I felt `pl.count()` was a very nice parallel with `COUNT(*)` in SQL. However, after doing the update (see linked PR), using `pl.len()` just feels a lot more natural in the various place where you'd use it.

**Comment by mkleinbort** [comment]
Does `pl.len()` create a column called `'count'`?

**Comment by MarcoGorelli** [comment]
no, check the diff https://github.com/pola-rs/polars/pull/13719/files

**Comment by alexander-beedie** [comment]
> Also, I think a lot of the SQL users will be sad that pl.count() changes behaviour.

FYI: when you operate on polars frames using the SQL interface you will always get SQL behaviour (we will not change the meaning of a SQL function with respect to the SQL interface 👌)
