### ISSUE TITLE
Compilation fails with `performant` feature

### ISSUE THREAD

**Issue by campbellcole** [pola-rs/polars#13684]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```sh
$ cargo new repro
$ cd repro
$ cargo add polars --no-default-features
$ cargo check --features polars/performant,polars/lazy
...
error[E0422]: cannot find struct, variant or union type `HConcat` in this scope
  --> /home/campbell/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/logical_plan/optimizer/cse.rs:51:32
   |
51 |         Union { inputs, .. } | HConcat { inputs, .. } => {
   |                                ^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0422`.
error: could not compile `polars-plan` (lib) due to 1 previous error
```

### Issue description

This only happens when the `performant` feature is enabled. Without it, any combination of features that I've tested works, but as soon as it's enabled, this error appears.

### Expected behavior

It should compile.

### Installed versions

<details>

`lazy,performant`

</details>

**Comment by nwagner84** [comment]
This issue also occurs when the `performant` feature is not enabled. I get the same error with the following features:

```toml
polars = { version = "0.36.2", features = ["ipc", "csv", "sql", "lazy", "dtype-categorical", "dtype-struct"] }
```

**Comment by orlp** [comment]
I think this is already fixed because I can not reproduce on the latest main.

**Comment by BorisChenCZY** [comment]
```rust
 #[cfg(feature = "horizontal_concat")]
    HConcat {
        inputs: Vec<Node>,
        schema: SchemaRef,
        options: HConcatOptions,
    },
```

This will only be able to compile if feature added `horizontal_concat `in 0.36.2.
I believe this should be a bug? At least `performant `feature should depend on `horizontal_concat`

**Comment by evbo** [comment]
@orlp can you please open? It is reproduced with the following features:

```toml
polars = { version = ">= 0.36.2", features = ["performant", "lazy", "cross_join", "find_many", "parquet", "dynamic_group_by", "cum_agg", "round_series", "lazy_regex", "list_eval", "list_drop_nulls", "list_any_all", "strings"]}
```

As noted by @BorisChenCZY issue goes away if you include `horizontal_concat` feature

**Comment by orlp** [comment]
@evbo Your mentioned set of features (replacing `lazy_regex` with `regex`) does not cause an issue on `main`. It's already fixed. Please use the latest main version when seeing if things still reproduce.
