### ISSUE TITLE
In rolling_* functions, setting min_periods larger than window_size returns null everywhere

### ISSUE THREAD

**Issue by EtienneT** [pola-rs/polars#13686]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Example code doing the behavior:
```python
df = df.with_columns(
    Price = pl.col('BasePrice').rolling_mean(window_size='20d', min_periods=103, by='Time', closed='right').over(['Node', 'Hour'])
)
```

### Issue description

Something changed between polars 0.19.0 and 0.20.4 for all the rolling_ methods.  In 0.19.0, you could have a min_periods larger than window_size and it didn't matter.  The returned column had some null values, but not all null.

Now if you set min_periods larger than window_size, the resulting column will return null everywhere.  No warning or error, just null everywhere.  This was not the behavior in 0.19.0.

### Expected behavior

We should get a warning or an error or we should return null for windows that don't have enough min_periods.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.9.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.0
numpy:                1.25.2
openpyxl:             <not installed>
pandas:               2.1.0
pyarrow:              13.0.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
could you make a reproducible example with expected output please? this looks correct to me but I may have misunderstood

**Comment by mcrumiller** [comment]
`min_periods` is supposed a be the minimum number of data points required before the calculation is performed on the window. If the size of the window is smaller than that threshold, it makes sense that only null values would be returned. I would expect anything else to be an error.

**Comment by EtienneT** [comment]
Here is some code to reproduce the issue.  It returns a total of 24000 rows with null values for price (all rows).

Simply changing min_periods to 10 will have far less null values (2160).

```
# Generate data for 10 nodes, 100 days, 24 hours a day, total 24000 rows

df = pd.DataFrame([(d, h, n, np.random.randint(0,10)) for h in range(0,24) for n in range(0,10) for d in pd.date_range('1/1/2020', periods=100, freq='D')], columns=['date', 'Hour', 'Node', 'BasePrice'])
df['Time'] = df.date + pd.to_timedelta(df.Hour, unit='h')

df = pl.DataFrame(df)
df = df.sort(['Node', 'Time'])

(df.with_columns(
    Price = pl.col('BasePrice').rolling_mean(window_size='10d', min_periods=11, by='Time').over(['Node', 'Hour'])
).sort('Node', 'Hour', 'Time')
.select(pl.col('Time'), pl.col('Hour'), pl.col('Node'), pl.col('Price'))
.select(pl.col('Price').is_null().sum()))
```

As a side note, I am receiving this error message even though the dataframe is sorted.  I get the same error even if I sort only by Time (the column passed to the `by` parameter or rolling_mean:

```
UserWarning: Series is not known to be sorted by `by` column in rolling_mean operation.

To silence this warning, you may want to try:
- sorting your data by your `by` column beforehand;
- setting `.set_sorted()` if you already know your data is sorted;
- passing `warn_if_unsorted=False` if this warning is a false-positive
  (this is known to happen when combining rolling aggregations with `over`);

before passing calling the rolling aggregation function.

  (df.with_columns(
```

**Comment by MarcoGorelli** [comment]
Looks correct to me:
```python
In [35]: df.rolling('Time', period='10d', by=('Node', 'Hour')).agg(pl.col('BasePrice')).with_columns(pl.col('BasePrice').li
    ...: st.len()).max()
Out[35]:
shape: (1, 4)
┌──────┬──────┬─────────────────────┬───────────┐
│ Node ┆ Hour ┆ Time                ┆ BasePrice │
│ ---  ┆ ---  ┆ ---                 ┆ ---       │
│ i64  ┆ i64  ┆ datetime[ns]        ┆ u32       │
╞══════╪══════╪═════════════════════╪═══════════╡
│ 9    ┆ 23   ┆ 2020-04-09 23:00:00 ┆ 10        │
└──────┴──────┴─────────────────────┴───────────┘
```

None of the rows have at least 11 elements in their group, so the result is null

Could you please point out which row should not be `null`?

**Comment by mcrumiller** [comment]
There are a few issues with your data.

1. Your `Time` column is not sorted, because you sorted first by `Node`, then by `Hour`, then by `Time`. This is a requirement for `rolling_mean` and is part of the reason why your output is not what you expect.
2. For the portions of the `Time` column that *are* monotonic, the output makes perfect sense. Your data are spaced at intervals of one day, and you are asking for a window size of of 10 days, which is 10 data points' worth of data (note: if you want to include the end points, use the `closed="both"` input parameter). You are then requiring that 11 data points be available before the mean is computed. Since each window only has 10 data points, your threshold of 11 data points is never reached; consequently, all values are null.

I've tested the rolling mean function using monotonic data and it appears to be working correctly.

**Comment by EtienneT** [comment]
Sorry for the confusion, I guess what really tripped me up is that in 0.19.0, you could pass a very large min_periods without any problem.  Then I updated to 0.20.4 and the exact same code returned null everywhere for some of my columns which confused me.  I think we can close this bug, the new behavior makes sense.

**Comment by MarcoGorelli** [comment]
Awesome, thanks

Yeah in previous versions it wasn't respected, that was a bug

Note that the time column only needs to be sorted within each group. The warning there is a false positive, but it'll be sorted out

**Comment by EtienneT** [comment]
Thinking about it a bit more during the night I realized that I misread the documentation.

I wanted to calculate rolling_mean only if the group had enough data (larger than min window).  So for example if a new Node appeared in my data, I wanted to wait to have at least 30 days of data for it before calculating the rolling_mean of 10d.  The data had time to stabilize.  I think in 0.19.0, you could use min_periods this way, but I haven't re-tested it recently...

Reading the documentation carefully for min_periods it is clear that this is not the case.

Maybe it would be a good idea to warn users in the documentation that if min_periods is larger than window_size, all resulting rows will be null.

And finally thanks for your time guys for the awesome library!
