### ISSUE TITLE
[request] dtypes optimisation function

### ISSUE THREAD

**Issue by lcrmorin** [pola-rs/polars#13687]
### Description

From what I understand polars has better memory management than pandas, thanks to its lazy evaluation. 
However it is handling datatypes in quite the same fashion (you have to specify them if you want to optimise them). However, over the years I've found that handling datatypes properly is a very important source of performance gain (memory usage and sometimes running time). 

It is possible to build a dtypes optimisation function manually, typically:

```
def reduce_memory_usage_pl(df, name):
    """ Reduce memory usage by polars dataframe {df} with name {name} by changing its data types.
        Original pandas version of this function: https://www.kaggle.com/code/arjanso/reducing-dataframe-memory-size-by-65 """
    print(f"Memory usage of dataframe {name} is {round(df.estimated_size('mb'), 2)} MB")
    Numeric_Int_types = [pl.Int8,pl.Int16,pl.Int32,pl.Int64]
    Numeric_Float_types = [pl.Float32,pl.Float64]    
    for col in df.columns:
        col_type = df[col].dtype
        c_min = df[col].min()
        c_max = df[col].max()
        if col_type in Numeric_Int_types:
            if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                df = df.with_columns(df[col].cast(pl.Int8))
            elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                df = df.with_columns(df[col].cast(pl.Int16))
            elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                df = df.with_columns(df[col].cast(pl.Int32))
            elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                df = df.with_columns(df[col].cast(pl.Int64))
        elif col_type in Numeric_Float_types:
            if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                df = df.with_columns(df[col].cast(pl.Float32))
            else:
                pass
        elif col_type == pl.Utf8:
            df = df.with_columns(df[col].cast(pl.Categorical))
        else:
            pass
    print(f"Memory usage of dataframe {name} became {round(df.estimated_size('mb'), 2)} MB")
    return df
```

(from: https://www.kaggle.com/code/demche/polars-memory-usage-optimization)

I think there would be a general interest in such a function being implemented natively... bc currently this is a bit niche, require manually recoding the thing and is not generally done despite being a good practice.

We can imagine the following improvements:
- options to specify dtypes optimisation ('lossless' v.s. 'lossy' dtypes reduction)
- some float to int conversion when there is a constant step (say 0.1, 0.2 ... 0.5 to 1 2 ... 5)
- running the lossless version after data reading functions (instead of schema inference)

Is it something that would make sense ?

**Comment by mcrumiller** [comment]
You can use [`shrink_dtype`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.shrink_dtype.html) for ints and floats:

```python
df = pl.DataFrame({
    "a": pl.Series([1, 2, 3], dtype=pl.Int64),
    "b": pl.Series([1, 2, 3], dtype=pl.UInt64),
    "c": pl.Series([1.1, 1.2, 1.3], dtype=pl.Float64)
})
print(df.select(pl.all().shrink_dtype()))
```
```
shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i8  ┆ u8  ┆ f32 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1.1 │
│ 2   ┆ 2   ┆ 1.2 │
│ 3   ┆ 3   ┆ 1.3 │
└─────┴─────┴─────┘
```

**Comment by alexander-beedie** [comment]
As @mcrumiller says, this already exists in the form of `shrink_dtype`, handling int/float dtypes; if you can take a look and see if you think it's missing something that would be handy. I wouldn't auto-convert strings to Categorical, but perhaps there could be some threshold of uniqueness you could set to opt-in to that opportunistically if the cardinality makes it appear worthwhile 🤔

**Comment by avimallu** [comment]
@alexander-beedie, I'd caution you from R's rather infamous [`stringsAsFactor`](https://simplystatistics.org/posts/2015-07-24-stringsasfactors-an-unauthorized-biography/).

**Comment by stinodego** [comment]
Closing as the requested functionality already exists.
