### ISSUE TITLE
Dead links in source

### ISSUE THREAD

**Issue by atouchet** [pola-rs/polars#1370]
#### Describe your bug.

The links listed here no longer work:

https://github.com/pola-rs/polars/blob/bb3de7723d95f03abcae7eb76ffcad3528f88d40/polars/src/docs/performance.rs#L13
https://github.com/pola-rs/polars/blob/bb3de7723d95f03abcae7eb76ffcad3528f88d40/polars/src/docs/performance.rs#L18
https://github.com/pola-rs/polars/blob/bb8801610b84fcf6c9cc0dcd151848f0300f6bca/py-polars/polars/lazy/expr.py#L966

**Comment by ritchie46** [comment]
Check, the first 2 are relocated to https://github.com/pola-rs/polars-static/tree/master/docs

**Comment by atouchet** [comment]
Note: The book link still doesn't work.

**Comment by ritchie46** [comment]
> Note: The book link still doesn't work.

Would https://pola-rs.github.io/polars-book/user-guide/howcani/apply/udfs.html be the updated page? That's the closest looking equivalent I could find.

Ah, yest. That's the one.
