### ISSUE TITLE
Read a remote excel file with `read_excel`

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#13718]
### Description

It would be nice to be able to read a remote excel file natively. It seems the functionality already exists in `read_csv`.

```python
file = "https://file-examples.com/wp-content/storage/2017/02/file_example_XLSX_5000.xlsx"

# FileNotFoundError. During handling of the above exception, another exception occurred: InvalidXlsxFileException
pl.read_excel(file)

# Of course not the correct format, but works
pl.read_csv(file)
```

And as a hopefully convincing use case: 
My team ingests a lot of statistical data from industry bodies, regulators, etc. Often this is in the form of excel files available for download at some link. We really enjoy the polars API for ETL scripts and cleaning / reshaping data, so this addition would make things even more convenient.

**Comment by hsnprsd** [comment]
Can someone assign this issue to me?

**Comment by Wainberg** [comment]
@hsnprsd I would just go ahead and submit a pull request :) the core developers have a lot on their plate and don't have time to respond to every issue, but I'm sure they'd be happy if this were supported.

**Comment by alexander-beedie** [comment]
> Can someone assign this issue to me?

Ahh... I had left this open in my tabs right after you posted it to remind myself to take care of it and now I refresh the page I see you were hoping to make the PR yourself! Sorry about that. If you're interested in following-up further, the `_process_http` utility function that does the work is extremely bare-bones at the moment and could likely benefit from some more industrialisation (not sure if it follow redirects, etc - if you test the PR and find you still can't access other remote files then I'm sure we'd welcome some improvements there!) 👍
