### ISSUE TITLE
Allow df.drop(pl.col(...))

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13710]
### Description

`select()` can take column names, expressions or selectors, but `drop()` can only take column names and selectors, so things like this give an error:

```python
df.drop(pl.col(other_df.columns).exclude(join_column))
```

This seems overly restrictive. I get that we want to disallow nonsense like:

```python
df.drop(pl.col.a.sum())
```

but if the point of selectors is to provide type-safety by making a distinction between "raw" and transformed columns, why not make `pl.col` a selector? After all, it always produces "raw" columns. That could also be a path forward towards reducing the [API duplication between `pl.col` and the `pl.selectors` namespace](https://github.com/pola-rs/polars/issues/12851).

The same issue also affects:

- `df.cast` (and `lf.cast`)
- `df.drop` (and `lf.drop`)
- `df.drop_nulls` (and `lf.drop_nulls`)
- `df.partition_by`
- `df.pivot`
- `df.melt` (and `lf.melt`)
- `df.rows_by_key`
- `df.to_dummies`
- `df.unique` (and `lf.unique`)
- `df.unnest` (and `lf.unnest`)
- `df.unstack`

**Comment by stinodego** [comment]
We will not add this. The mentioned functions only make sense when specifying existing columns. Hence expressions do not make sense, as you noted. Column selectors do make sense, as they expand to a list of existing column names, and most of those methods do in fact support this.
