### ISSUE TITLE
Support "mean" in `describe` for bools

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#13735]
### Description

Data often contains columns with flags (yes/no, true/false).

Getting a quick overview of the column requires actually only 2 things
1. amount of valid/invalid values -> available! (count/null_count) ✅ 
2. ratio between yes/no values -> NOT available 🟥 

This can be easily solved by adding the "mean" value of the boolean column
- `[True, False, False, None]` -> 0.33 (33% True)
- `[True, True, True, None]` -> 1.00 (100% True)
- `[False, False, False, None]` -> 0.0 (0% True)
- `[None, None, None, None]` -> 0.0 (0% True)

### Current State:

Problem: almost useless for bool columns. Only information is the null_count
```python
pl.DataFrame({"bool": [True, False, False, None]}).describe()

shape: (9, 2)
┌────────────┬───────┐
│ describe   ┆ bool  │
│ ---        ┆ ---   │
│ str        ┆ str   │
╞════════════╪═══════╡
│ count      ┆ 3     │
│ null_count ┆ 1     │
│ mean       ┆ null  │ <<<<< this would be really usefull to get the Yes/No-Ratio
│ std        ┆ null  │
│ min        ┆ False │
│ 25%        ┆ null  │
│ 50%        ┆ null  │
│ 75%        ┆ null  │
│ max        ┆ True  │
└────────────┴───────┘
```

**Comment by alexander-beedie** [comment]
I'm sold; it seems genuinely useful.

**Comment by taki-mekhalfa** [comment]
Happy to take this one
