### ISSUE TITLE
Rename `drop` to `drop_columns`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#13745]
### Description

`drop` is a very generic and unspecific name. Just had to look up what is acutally does. ooohhh it drops columns I see...
It is nice if you know exactly what a function does without reading the docs.

## Proposal: `drop` -> `drop_columns`

`drop_columns` is much clearer for the user and fits in with `with_columns`, `get_columns` ...

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - tbh I think `drop` is fine, appending `_column` everywhere hurts ergonomics - e.g. `cast` -> `cast_column`, `explode` -> `explode_columns`, `rename` -> `rename_columns`...I think these would be unnecessarily verbose

**Comment by JulianCologne** [comment]
Agree that adding ˋcolumnsˋ everywhere is too much!

However, in this case it is really useful because ˋdropˋ is ambiguous imo. Drop what??

Cast is clear: cast column types
But drop: drop rows? Drop columns? Drop Schema/types? Hmm maybe ˋremove_columnsˋ would be even better 😄

**Comment by cjackal** [comment]
The very same logic applies to `select`, `filter`, ... (select what? rows? columns? filter what?). Should we change all of them for clarity?

And I personally want to avoid the nightmare of full screen of deprecation warnings on `.drop` just by running a single data preprocessing pipeline, so -1 for such a huge change.

**Comment by alexander-beedie** [comment]
Hmm... we do have `insert_column` and `replace_column`; having `drop_column` alongside them would actually feel very natural as there is a clear connection between these three functions and they obviously play in the same space. Aligning the naming (just for these) isn't a crazy thought.

Having said that, `drop` doesn't really compete for attention with anything else - if I was presented with a standalone `insert` or `replace` it would feel ambiguous. But... when I see `drop` I _don't_ find myself thinking about anything other than columns (for rows I would first think about words like "filter", "constrain", "where"). That could just be my frequent proximity to SQL (where you would issue `ALTER TABLE <tbl> DROP COLUMN`), so I can't speak to everyone's expectation here. I could honestly go either way on this one 🤔 @stinodego, I believe a referee is called for on this one :)

**Comment by MarcoGorelli** [comment]
> I don't find myself thinking about anything other than columns

yeah, if you see it in context, you'll see something like
```
df.drop('a', 'b')
```
Polars doesn't have row labels, so `'a'` and `'b'` could only be column labels

**Comment by mcrumiller** [comment]
If we really wanted to be consistent we would name it `.without_columns()` but I don't think anybody wants that :D

**Comment by stinodego** [comment]
It is actually named `drop_columns` in Rust :)

I think it should just be `drop`. While we like to be explicit and `drop_columns` is more explicit than `drop`, as Alex mentioned, `drop` isn't really confusing. I think it's fine to keep this as is.

For what it's worth, it's also called `drop` in pyspark.

_(I will rename the Rust API to match Python here)_

**Comment by JulianCologne** [comment]
I think after many years of experience in the "data" space (pandas, polars, spark, sql, ...) it is sometimes hard to understand the struggles of people new to the area.

For us `drop("x")` is super clear! Remove column "x"! But is it really that clear? Does the function communicate that?

Isn't `drop_column("x")` or `remove_column("x")` much clearer for newcomers or other team members taking a look at the code?

tbh I am personally perfectly fine with `drop`. Just sometimes trying to think from the point of view of newcomers, other teams members etc.

I was actually going to say that you can ofc also use `drop(columns="x")` to document functionality better but this has a deprecation warning 😮  (DeprecationWarning: named `columns` param is deprecated; use positional `*args` instead)

**Comment by mcrumiller** [comment]
I'm chuckling a bit at the irony of this issue resulting in a change of `drop_columns` to `drop`. Sorry @JulianCologne 😆
