### ISSUE TITLE
Unintentional breaking change  0.20.3 -> 0.20.4 in pl.col().cum_count()

### ISSUE THREAD

**Issue by Object905** [pola-rs/polars#13740]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

0.20.4
```python
import polars as pl
df = pl.DataFrame([[1,1, 2,1, 3, 2]], {"a": pl.UInt32})
df.select(pl.col("a").cum_count())

shape: (6, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ 5   │
│ 6   │
└─────┘
```

0.20.3
```python
import polars as pl
df = pl.DataFrame([[1,1, 2,1, 3, 2]], {"a": pl.UInt32})
df.select(pl.col("a").cum_count())

shape: (6, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 0   │
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ 5   │
└─────┘
```

### Issue description

After upgrade to 0.20.4 cum_count started giving results starting with 1 instead of 0. While this was not documented in Deprecation/Breaking changes section of release.

### Expected behavior

I've adjusted my code to work with with newest version. But perhaps this is a bug or breaking change that got into minor version.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             Linux-6.6.10-arch1-1-x86_64-with-glibc2.38
Python:               3.12.1 (main, Dec 25 2023, 16:18:48) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               23.9.1
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
```

</details>

**Comment by Object905** [comment]
Created an issue, just to make sure.
 In documentation i'ts starting with 1.

**Comment by MarcoGorelli** [comment]
thanks @Object905 for the report

this was changed in https://github.com/pola-rs/polars/pull/13535 - though technically breaking, it could be argued that this was incorrect to begin with

**Comment by stinodego** [comment]
This was introduced as a bugfix - starting at 0 was incorrect.

You can get behavior similar to what you had by using `pl.int_range(pl.count())`.
