### ISSUE TITLE
polars::functions::concat_df_horizontal not found in `polars::functions

### ISSUE THREAD

**Issue by polarbeargo** [pola-rs/polars#13755]
### Description

I'm trying to use `polars::functions::concat_df_horizontal ` followed the source code [link](https://docs.pola.rs/docs/rust/dev/src/polars_core/functions.rs.html#11) but somehow keep encounter the following feature not found:
```
use polars::prelude::*;
let df_horizontal_concat = polars::functions::concat_df_horizontal(&[df2, df3])?;
    |                                                   ^^^^^^^^^^^^^^^^^^^^ not found in `polars::functions
```
My Cargo.toml:
```
[dependencies]
polars = { version = "0.33.0", features = ["lazy", "csv", "horizontal_concat", "diagonal_concat"] }
```
Also tried the following:
```
polars-core = { version = "0.33.0", features = ["horizontal_concat"] }
```
Hope you can help me know how to use  `polars::functions::concat_df_horizontal `.

### Link

https://docs.pola.rs/docs/rust/dev/src/polars_core/functions.rs.html#11

**Comment by mcrumiller** [comment]
You are using an older version of polars `0.33.0`, make sure when you use the API docs you have the correct version set. The function in `0.33.0` is called [`hor_concat_df`](https://docs.rs/polars/0.33.0/polars/functions/fn.hor_concat_df.html).

**Comment by polarbeargo** [comment]
Thank you so much for your help @mcrumiller !
