### ISSUE TITLE
Decide whether `columns` or `new_columns` are used in the `schema` and `dtypes` parameters in `read_csv

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#13764]
### Description

`columns` and `new_columns` both describe the dataframe (one source, one output), but the `schema` and `dtypes` parameters do not specify whether the old or new column names should be specified as keys, and this can lead to ambiguity in the case that `new_columns` contains one of the old column names in a different position.
 
I propose that if `new_columns` is present, then these are the names that should be used, the rationale being that `new_columns` are often clearer names anad also are often used when the source header names are very messy.

**Comment by stinodego** [comment]
Has been decided, see:
https://github.com/pola-rs/polars/issues/15431#issuecomment-2155890712
