### ISSUE TITLE
cmake requirement for local environment setup

### ISSUE THREAD

**Issue by jlb52** [pola-rs/polars#13774]
### Description

Hello!

I just tried to setup my local environment for contribution, and I ran into an issue while running `make test`.

More specifically, I received the following error message:

```
Compiling rustls v0.21.10
error: failed to run custom build command for `libz-ng-sys v1.1.12
```

...followed by a range of other failures.

At one point in the error log, I saw:
```
failed to execute command: No such file or directory (os error 2) 
is `cmake` not installed?
```

I went ahead and installed cmake (via brew) and then was able to run `make test` succesfully.

I understand many developers will already have this installed, but my suggestion is to add a few sentences in the documentation suggesting an installation of this software in case it's not yet installed.

I'm happy to add this myself if it's helpful. 

Best,
Jackson

### Link

https://docs.pola.rs/development/contributing/#contributing-to-the-codebase

**Comment by stinodego** [comment]
Hi @jlb52 ,

Great to you see you managed to identify the problem and finish setting up your environment.

Unfortunately, we cannot include everything in the contributing guide - some basics you just have to figure out yourself. In this case, as there is a clear error message telling you to install `cmake`, I don't think it's necessary to include this in the contributing guide.

**Comment by jlb52** [comment]
@stinodego No problem! Thanks for the response. 

Best,
Jackson
