### ISSUE TITLE
Align `int_range` and `int_ranges` signatures

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#13787]
### Description

Since the last release, the `end` argument of `int_range` is optional. if set to None, the value of `start` is used and `start` is set to `0`.
This is great, it would be nice to have to same thing on `int_ranges` and maybe `time_range` and `time_ranges` as well

**Comment by stinodego** [comment]
Initially I didn't think this was worth adding, but I guess it can't hurt. `time_range` already has similar behavior I think.

**Comment by stinodego** [comment]
`time_range` and `time_ranges` already have some logic in place for omitted `start`/`end` inputs:

https://github.com/pola-rs/polars/blob/20f7d6a9343c920ad912dde375c71d13e3ea3f6c/py-polars/polars/functions/range/time_range.py#L145-L148

I don't think aligning this with the new `int_range` behavior is worthwhile - there is something to be said for this logic. So let's keep it for now.
