### ISSUE TITLE
py-polars: `when` `then` `otherwise` documentation should cover how to input string literals

### ISSUE THREAD

**Issue by arnabadas** [pola-rs/polars#13805]
### Description

If I want to conditionally enter <kbd>A</kbd> character in a column `pl.when(<condition>).then("A").otherwise(1)` won't work as there is no such column with the name <kbd>A</kbd>. You have to type `pl.when(<condition>).then(pl.lit("A")).otherwise(1)`. **Using `pl.lit` is not apparent from the documentation as there is no such example.**

**Unpopular opinion:** In my opinion, being explicit is the best. `then` and `otherwise` should only consider `expr`. Have the user to write `pl.col` if they want to refer to columns or else `pl.lit` if they want to refer to literals is in my opinion the best thing because I think the syntax mentioned above is inconsistent.

**Comment by cmdlineluser** [comment]
@mcrumiller I think it was changed because inside `when()` a string was always parsed as a column name?

```python
df = pl.DataFrame({"A": [True, False, True], "B": [1, 2, 3], "C": [4, 5, 6]})

df.with_columns(when = pl.when("A").then("B").otherwise("C"))
# shape: (3, 4)
# ┌───────┬─────┬─────┬──────┐
# │ A     ┆ B   ┆ C   ┆ when │
# │ ---   ┆ --- ┆ --- ┆ ---  │
# │ bool  ┆ i64 ┆ i64 ┆ i64  │
# ╞═══════╪═════╪═════╪══════╡
# │ true  ┆ 1   ┆ 4   ┆ 1    │
# │ false ┆ 2   ┆ 5   ┆ 5    │
# │ true  ┆ 3   ┆ 6   ┆ 3    │
# └───────┴─────┴─────┴──────┘
```

(I'm not sure if `col` was ever required in `when`)

**Comment by mcrumiller** [comment]
Even that seems a bit muddled, we should require `when(pl.col("A"))`. After all, `when(3)` errors because `3` does not evaluate to a boolean, but `when("a")` does not.

**Comment by cmdlineluser** [comment]
Yeah, I guess it's to match up with:

```python
df.with_columns(foo = "A") # implicit `pl.col`
# shape: (3, 4)
# ┌───────┬─────┬─────┬───────┐
# │ A     ┆ B   ┆ C   ┆ foo   │
# │ ---   ┆ --- ┆ --- ┆ ---   │
# │ bool  ┆ i64 ┆ i64 ┆ bool  │
# ╞═══════╪═════╪═════╪═══════╡
# │ true  ┆ 1   ┆ 4   ┆ true  │
# │ false ┆ 2   ┆ 5   ┆ false │
# │ true  ┆ 3   ┆ 6   ┆ true  │
# └───────┴─────┴─────┴───────┘
```

I'm not sure if there was any previous discussion about a `col` requirement for `when`.

**Comment by mcrumiller** [comment]
Yeah, I see how this gets messy. Requiring `pl.col(...)` any time you reference a call would mean lots of code bloat. I typically import `pl.col` as `col` to reduce it a little bit, but I get it. But I still don't like the `then(str)` usage.

**Comment by cmdlineluser** [comment]
Hmmm, it's even more muddled than I thought:

```python
df.select(pl.when(pl.col("A") == "A").then(1))
# shape: (3, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ i32     │
# ╞═════════╡
# │ null    │
# │ null    │
# │ null    │
# └─────────┘
```

Which seems to be evaluating `pl.col("A") == pl.lit("A")`?

**Comment by mcrumiller** [comment]
The fact that our columns are defined by string labels is going to lead us to this issue _somewhere_ and there's not really a way around it. We either force users to always refer to columns via `pl.col(...)`, which is quite cumbersome but unambiguous, or we use shortcuts which make general coding easier, but also lead to ambiguity. I prefer the former but do admit that it can make ugly code, especially when `col` is not imported directly from the polars module.

**Comment by JulianCologne** [comment]
> The fact that our columns are defined by string labels is going to lead us to this issue _somewhere_ and there's not really a way around it. We either force users to always refer to columns via `pl.col(...)`, which is quite cumbersome but unambiguous, or we use shortcuts which make general coding easier, but also lead to ambiguity. I prefer the former but do admit that it can make ugly code, especially when `col` is not imported directly from the polars module.

100% agree!

I personally really love consistency and explicitness and would happily type a few more characters to make it really clear what my intention is 😄 

Meaning: everything I enter will be treated as a Literal `pl.lit(x)` by default. If I want to refer to a column I an required to use `col(...)`

- `3` -> `pl.lit(3)`
- `3.141` -> `pl.lit(3.141)`
- `date(2024, 1, 1)` -> `pl.lit(date(2024, 1, 1))`
- `"x"` -> `pl.col("x")`  😢

**Comment by stinodego** [comment]
The documentation for `when` explicitly mentions that strings are parsed as column names. So I'll close this as completed.

The discussion about whether or not string literals should be interpreted as column names has been had many times before. We are not planning on changing this.
