### ISSUE TITLE
Parquet File Size Larger than CSV File Size

### ISSUE THREAD

**Issue by elibenporat** [pola-rs/polars#1381]
Polars 0.16 in Rust

I'm not sure if this is a Polars issue specifically, but I'm not sure which parquet crate is being used. I ran a simple test to convert a 74GB csv to parquet. The parquet version ended up at 107GB (roughly), which surprised me, as I was expecting some compression, but ended up with a bigger file. 

The CSV reading was amazing by the way! Read the 74GB file in 138 seconds, with proper schema inference. Quite magical.

```rust
    let filename = r#"D:\Baseball\baseball.csv"#;
    let parquet = r#"D:\Baseball\baseball.parquet"#;

    let start = time::Instant::now();

    let csv = CsvReader::from_path(filename).expect("Couldn't find filename")
        .infer_schema(Some(10_000))
        .has_header(true)
        .finish()
        .expect("Csv Error")
        ;
    
    let end = time::Instant::now();

    let time_taken = end.checked_duration_since(start).expect("time error").as_secs();
    
    
    let r = File::create(parquet).expect("couldn't create the file");
    
    let writer = ParquetWriter::new(r);
    writer.finish(&csv).expect("Couldn't write the file");
```

**Comment by ritchie46** [comment]
I think I don't compress the parquet file. I will add an option for that! It is already supported by arrow2.

> The CSV reading was amazing by the way! Read the 74GB file in 138 seconds, with proper schema inference. Quite magical.

Thanks! I put a lot of effort in that, so great that it works out. :)

**Comment by elibenporat** [comment]
Awesome. Looking forward to seeing how well it compresses (and how quick it is).

**Comment by ritchie46** [comment]
@elibenporat, give it a spin #1385

**Comment by elibenporat** [comment]
Works! 74.4 GB CSV is now a 11.5 GB parquet file, using the default compression (took about 180 seconds for the write, compared to 130 seconds for the read). The equivalent Tableau .hyper clocks in at about 16.2 GB (not apples to apples obviously).

I assume this will likely improve over time if RLE or Dictionary encoding is employed in the Parquet2 crate.

**Comment by ritchie46** [comment]
> I assume this will likely improve over time if RLE or Dictionary encoding is employed in the Parquet2 crate.

This question I have to defer to @jorgecarleitao. I don't know anything about parquet.

I think the write is also single threaded, whereas the csv-parser is multi-threaded.

**Comment by jorgecarleitao** [comment]
Two options:

* use `Encoding::DeltaLengthByteArray` and a `Utf8Array` to the writer
* use `Encoding::RleDictionary` and a `DictionaryArray` to the writer

Also, we can make the writer multi-threaded and will likely become the fastest parquet writer out there: I offer some guides [here](https://jorgecarleitao.github.io/arrow2/io/parquet_write.html#write-to-parquet). Basically: rayon the encoding+compression, and single-thread the writing to a `Write`.

**Comment by ritchie46** [comment]
> Also, we can make the writer multi-threaded and will likely become the fastest parquet writer out there: I offer some guides here. Basically: rayon the encoding+compression, and single-thread the writing to a Write.

This one will be added to my todo-list. ;)

**Comment by ritchie46** [comment]
Vlosex by #1385
