### ISSUE TITLE
`select()` interface is inconsistent with lists

### ISSUE THREAD

**Issue by mgirlich** [pola-rs/polars#13827]
### Description

How a list is handled in `select()` depends on whether it is the only argument or not:

```python
import polars as pl
df = pl.DataFrame({
    "x": [1, 2, 3],
    "y": ["a", "b", "c"],
    "z": [-1, -2, -3]
})

# a list of strings selects the columns in the list
df.select(["x", "y"])
```

```
shape: (3, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
│ 2   ┆ b   │
│ 3   ┆ c   │
└─────┴─────┘
```

```python
# ... unless there is another argument after the list
df.select(["x", "y"], "z")
```

```
shape: (3, 2)
┌────────────┬─────┐
│ literal    ┆ z   │
│ ---        ┆ --- │
│ list[str]  ┆ i64 │
╞════════════╪═════╡
│ ["x", "y"] ┆ -1  │
│ ["x", "y"] ┆ -2  │
│ ["x", "y"] ┆ -3  │
└────────────┴─────┘
```

We get the expected behaviour when wrapping the list in `pl.col()`:

```python
df.select(pl.col(["x", "y"]), "z")
```

```
shape: (3, 3)
┌─────┬─────┬─────┐
│ x   ┆ y   ┆ z   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ -1  │
│ 2   ┆ b   ┆ -2  │
│ 3   ┆ c   ┆ -3  │
└─────┴─────┴─────┘
```

**Comment by stinodego** [comment]
This is intended behavior.

**Comment by mgirlich** [comment]
Can you explain this a bit more? To me it feels very surprising that adding an argument changes the meaning of the first argument.

**Comment by stinodego** [comment]
`select` and many other functions take positional inputs. This is convenient as it allows you to specify arguments without having to enclose them in brackets. However, passing inputs as a list can also be convenient, so we have a special case that if you pass a single iterable, it gets parsed as separate inputs. If you pass multiple inputs, each input is parsed as a separate input. And list inputs are a valid single input too (list literals).
