### ISSUE TITLE
Allow fill_null to accept Expr for Series

### ISSUE THREAD

**Issue by chaaland** [pola-rs/polars#1383]
I'm running into the following issue when trying out this library

Currently, the following code inserts a 42 at the start of `df`

```
import polars as pl

df = pl.DataFrame([0,1,2,3], columns=["foo"])
df = df.shift(1).fill_null(pl.lit(42))
```

Doing the same thing for a Series fails however
```
import polars as pl

s = pl.Series("foo", [0,1,2,3])
s.shift(1).fill_null(pl.lit(42))
```

The use case I have requires that I just shift a single column of my DataFrame, fill the missing value with a constant, and assign it back.

An alternative would be to implement `shift_and_fill` for Series (which as far as I can tell does not exist)

**Comment by ritchie46** [comment]
> The use case I have requires that I just shift a single column of my DataFrame, fill the missing value with a constant, and assign it back.

Try this:

```python
df.with_column(
   col("foo").shift_and_fill(42)
)
```

**Comment by ritchie46** [comment]
Both suggestions are added: #1384

**Comment by chaaland** [comment]
Thanks for the quick follow up! I had solved my issue by just operating a dataframe with a single column and then using `hstack` to add it to the original dataframe. However, I didn't know about `with_column` so I'll give that a try

**Comment by ritchie46** [comment]
Added and released
