### ISSUE TITLE
Implement bitwise NOT

### ISSUE THREAD

**Issue by jeroenjanssens** [pola-rs/polars#13841]
### Description

Polars supports four Boolean operations: conjunction, disjunction, exclusive or, and negation. The table below lists their corresponding inline operators and methods. 

Operation    | Inline Operator | Method        
-------------|-----------------|----------------
Conjuction   | `&`             | `Expr.and_(…)`
Disjunction  | `\|`            | `Expr.or_(…)` 
Exclusive or | `^`             | `Expr.xor(…)` 
Negation     | `~`             | `Expr.not_(…)`

Of those four, the first three also accept integers to perform bitwise operations. While bitwise operations are perhaps a bit niche, it would be logical to complete the set. 

In other words, can we make the method `Expr.not_()` and the corresponding inline operator `~` also accept integers?

### Current workaround

In the upcoming book *Python Polars: The Definitive Guide*, we're currently circumventing the absence of bitwise NOT by taking the two's complement of the value minus one:

```python
bits = (
    pl.DataFrame({
        "x": [1, 1, 0, 0, 1, 10],
        "y": [1, 0, 1, 0, 2, 34]
    }, schema={"x": pl.UInt8, "y": pl.UInt8})
    .with_columns(
        (pl.col("x") & pl.col("y")).alias("x & y"),
        (pl.col("x") | pl.col("y")).alias("x | y"),
        (pl.col("x") ^ pl.col("y")).alias("x ^ y"),
        (-pl.col("x") - 1).alias("~x")
    )
)
bits

# shape: (6, 6)
# ┌─────┬─────┬───────┬───────┬───────┬─────┐
# │ x   │ y   │ x & y │ x | y │ x ^ y │ ~x  │
# │ --- │ --- │ ---   │ ---   │ ---   │ --- │
# │ u8  │ u8  │ u8    │ u8    │ u8    │ u8  │
# ╞═════╪═════╪═══════╪═══════╪═══════╪═════╡
# │ 1   │ 1   │ 1     │ 1     │ 0     │ 254 │
# │ 1   │ 0   │ 0     │ 1     │ 1     │ 254 │
# │ 0   │ 1   │ 0     │ 1     │ 1     │ 255 │
# │ 0   │ 0   │ 0     │ 0     │ 0     │ 255 │
# │ 1   │ 2   │ 0     │ 3     │ 3     │ 254 │
# │ 10  │ 34  │ 2     │ 42    │ 40    │ 245 │
# └─────┴─────┴───────┴───────┴───────┴─────┘
```

**Comment by jeroenjanssens** [comment]
It appears that with Polars 0.20.6, my workaround doesn't work anymore we cannot get the negative of unsigned integers:

```
InvalidOperationError: `neg` operation not supported for dtype `u8`
```

That by itself makes sense, and is hopefully another argument for a dedicated bitwise `Expr.not_()` method and corresponding inline operator (`~`).

**Comment by ritchie46** [comment]
I think we should have bitwise negation for integers. Agree
