### ISSUE TITLE
Auto unnest?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#13843]
### Description

There has been some consternation around expressions only returning one column per expression. 

To ease some of that I wonder if it makes to talk about making (I think in eager mode only) structs auto unnest when they're new

for example if you start with

```
df = pl.DataFrame({'x': [{'x1':10, 'x2':20}]})
# and then do
df.with_columns(a=pl.lit(1))
```

the `x` wouldn't auto unnest because it's not a new column.

If you did something like:

```
df2.with_columns(
    pl.col("col").str.extract_groups(r"(\S+) (\S+) (.+)")
)
```

then that would auto unnest the "col" column because `col` wasn't a struct before the `with_columns` but it is after so it would auto unnest

It begs the question of what happens if you want to keep the struct. One idea is to make it by name so if it has an inherited name (ie. it wasn't named by the user as in the above) then it would auto unnest. In that way if you want to keep a struct then you give it a new name.

Another use case would be `when/then/otherwise` where the user wants multiple outputs on the same `when` condition such as with [this](https://github.com/pola-rs/polars/issues/13769)

**Comment by mkleinbort** [comment]
Although I do want unnest functionality at the expression level I don't think it should be the default. 

One idea would be to have 

.with_columns(**pl.col('x'))

Be equivalent to .unnest('x')

But I don't love this either.

**Comment by deanm0000** [comment]
I don't really have a strong opinion on an Expression based unnest since in other discussions it's been dismissed as not possible/practical. I was just trying to think of way to bridge that gap and make things easier for some use cases where people want to skip having a struct. I'm not a strong advocate for it per se but thought it'd be worth a discussion, at least.

**Comment by mkleinbort-ic** [comment]
In the context of the dataframe-level `.with_columns()` I thought it technically possible to do:


```python
df2.with_columns(
    **pl.col("col").str.extract_groups(r"(\S+) (\S+) (.+)")
)

```

To skip to the unnested struct.
