### ISSUE TITLE
rolling_map() not using nulls to determine window size with min_periods

### ISSUE THREAD

**Issue by lee170** [pola-rs/polars#13856]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"Z": [None, 1, 2, 3, 4, 5]})

df = df.with_columns(
    pl.col("Z").rolling_map(lambda x: x.product(), window_size=3, min_periods=3)
    .alias("Z_rolling_product")
)

print(df)
```

Z     | Z_rolling_product
--    | --
i64  | i64
null | null
1     | null
2    | 2
3    | 6
4    | 24
5    | 60

### Issue description

According to the documentation, the min_periods argument to `rolling_map() ` is "The number of values in the window that should be non-null before computing a result", but, the minimum number of non-null values appears to be too low by 1.  For example, min_periods = 3 is computing a result with 2 non-null values.

### Expected behavior

In the above code, with min_periods set to 3, a result is computed with only 2 non-null values.  Z_rolling_product should be null on the third row, not 2.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
It's not off by one, it's simply not using null values to determine window validity:

```python
df = pl.DataFrame({"Z": [0, 1, None, 3, 4, 5]})

out = df.with_columns(
    pl.col("Z").rolling_map(lambda x: x.product(), window_size=3, min_periods=3)
    .alias("Z_rolling_product")
)
```
```
┌──────┬───────────────────┐
│ Z    ┆ Z_rolling_product │
│ ---  ┆ ---               │
│ i64  ┆ i64               │
╞══════╪═══════════════════╡
│ 0    ┆ null              │
│ 1    ┆ null              │
│ null ┆ 0                 │
│ 3    ┆ 3                 │
│ 4    ┆ 12                │
│ 5    ┆ 60                │
└──────┴───────────────────┘
```

**Comment by lee170** [comment]
Doesn't the documentation say the min_periods is the number of non-null values for a computation?  I interpret that as meaning 3 non-null values are needed to calculate a rolling product, e.g., 1*2*3=6.  It's not clear why it's computing 1*2=2 from a window of (null, 1, 2).

**Comment by mcrumiller** [comment]
Yes, I agree. What I am saying is that the issue isn't an off-by-one error, it's a "nulls aren't used to determine window validity" error. In my example above, we should output all null values until `Z = 5`.

**Comment by MarcoGorelli** [comment]
thanks for the report / triage

so, looks like `rolling_*` aggregations are fine, except for `rolling_map`?
```python

In [75]: import polars as pl  # incorrect
    ...:
    ...: df = pl.DataFrame({"Z": [None, 1, 2, 3, 4, 5]})
    ...:
    ...: df = df.with_columns(
    ...:     pl.col("Z").rolling_map(lambda x: x.sum(), window_size=3, min_periods=3)
    ...:     .alias("Z_rolling_sum")
    ...: )
    ...:
    ...: print(df)
shape: (6, 2)
┌──────┬───────────────┐
│ Z    ┆ Z_rolling_sum │
│ ---  ┆ ---           │
│ i64  ┆ i64           │
╞══════╪═══════════════╡
│ null ┆ null          │
│ 1    ┆ null          │
│ 2    ┆ 3             │
│ 3    ┆ 6             │
│ 4    ┆ 9             │
│ 5    ┆ 12            │
└──────┴───────────────┘

In [76]: import polars as pl  # correct
    ...:
    ...: df = pl.DataFrame({"Z": [None, 1, 2, 3, 4, 5]})
    ...:
    ...: df = df.with_columns(
    ...:     pl.col("Z").rolling_sum(window_size=3, min_periods=3)
    ...:     .alias("Z_rolling_sum")
    ...: )
    ...:
    ...: print(df)
shape: (6, 2)
┌──────┬───────────────┐
│ Z    ┆ Z_rolling_sum │
│ ---  ┆ ---           │
│ i64  ┆ i64           │
╞══════╪═══════════════╡
│ null ┆ null          │
│ 1    ┆ null          │
│ 2    ┆ null          │
│ 3    ┆ 6             │
│ 4    ┆ 9             │
│ 5    ┆ 12            │
└──────┴───────────────┘
```

?

**Comment by mcrumiller** [comment]
@MarcoGorelli I just put in a fix, but I wonder if we should augument `rolling_map` to allow for null values to be included in the window and have the user decide what to do. The reason being that `rolling_map` is intended to be slow but very flexible with an arbitrary user function applied.

**Comment by mcrumiller** [comment]
(in other words, discard my fix but instead update the docs to say that `min_periods` simply says how many values we require).

**Comment by lee170** [comment]
I think it would be better if min_periods specified the number of non-null values, or there were an option to require it do so.  It's intuitive and similar to Pandas behavior (not suggesting Polars must follow Pandas, just that it's widely expected behavior).  For example:
```
df = pd.DataFrame({"Z": [None, 1, 2, 3, 4, 5]})
df["Z_rolling_product"] = df[["Z"]].rolling(3).apply(lambda x: x.product())
```

Results in:


Z      | Z_rolling_product
--     | --
NaN | NaN
1.0   | NaN
2.0   | NaN
3.0   | 6.0
4.0   | 24.0
5.0  | 60.0
