### ISSUE TITLE
New style filter with kwargs doesn't perform predicate pushdown with statistics

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#13861]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import tempfile
pl.Config.set_verbose(True)

with tempfile.TemporaryDirectory() as tempdir:
    pl.DataFrame({"a": [1, 1, 1, 1, 1]}).write_parquet(f"{tempdir}/1.parquet", statistics=True)
    pl.DataFrame({"a": [2, 2, 2, 2, 2]}).write_parquet(f"{tempdir}/2.parquet", statistics=True)
    ldf = pl.scan_parquet(f"{tempdir}/*.parquet")
    ldf.filter(a=1).collect()
    ldf.filter(pl.col("a") == 1).collect()

```

### Log output

```shell
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
```

### Issue description

Statistics aren't utilized with the kwarg style filter arguments, I couldn't verify if this applies to when/then either.

### Expected behavior

parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             macOS-14.2-arm64-arm-64bit
Python:               3.9.6 (default, Nov 10 2023, 13:38:27)
[Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report, @alexander-beedie fancy taking a look?

**Comment by MarcoGorelli** [comment]
there difference between the two is that the first one uses `eq_missing`

https://github.com/pola-rs/polars/blob/14440ca91212493c69128dacdf07df84af5325af/py-polars/polars/lazyframe/frame.py#L2700-L2702

but the second one `eq`. Why is it `eq_missing`?

**Comment by ritchie46** [comment]
Hmm.. this really should be `eq`. Having inconsistencies in our equality is not something that I want so implicit.

Also the fact that this is a performance foodgun is bad. 

@alexander-beedie can we improve the plan here?

**Comment by alexander-beedie** [comment]
Hmm... yes actually; if somebody specifically uses kwargs to indicate `x = None` then we probably should honour that? At least it feels like that to me. _But_... we don't need to use `eq_missing` for anything  except None, and we couldd actually just use `is_null` there anyway 🤔

**Comment by mcrumiller** [comment]
If we're talking about a `filter`, doesn't `eq` and `eq_missing` return the same result? keyword args don't allow for `neq` which is where `_missing` would have an effect.

```python
import polars as pl
from polars import col

df = pl.DataFrame({
    "a": [1, 2, 3, None, None, 6, 7, 8, 9, 10]
})

# both return same result, null results always are filtered out
df.filter(col("a").eq(3))
df.filter(col("a").eq_missing(3))
```

**Comment by alexander-beedie** [comment]
> If we're talking about a `filter`, doesn't `eq` and `eq_missing` return the same result? 

Nope; pretend it's named `eq_including_nulls` instead (or equivalent :)
```python
df = pl.DataFrame({"a": [1,None,3]})
df.filter(pl.col("a").eq(None))  # won't match 'null'
df.filter(pl.col("a").eq_missing(None))  # will match 'null'
```

**Comment by mcrumiller** [comment]
Ahh, wasn't aware of that distinction, I figured both would match.

I personally don't see why anyone would ever want to use `filter` and not match what they explicitly provided. If they call `.filter(a=None)` I would think they would want all rows where `a` is None, and if they matched nothing and later found it `a` actually had rows with `None` they'll probably file an issue. Am I missing something here?

With regular functions this would be a problem because `None` indicates a lack of an argument provided, but in `kwargs` that is not an issue, because no argument = no key = no `None` value.

**Comment by alexander-beedie** [comment]
> Am I missing something here?

Probably not; `x = None` being equivalent to `x.is_nul()` is probably fine; as you say, it's _extremely_ explicit what you are asking for. The broader point is to make sure that we don't ever use `eq_missing` instead of `eq` during filter accumulation.

**Comment by mcrumiller** [comment]
> Note that we do generate a `UserWarning` if you write `pl.col("x") == None`, suggesting `pl.col("x").is_null()` instead:
> 
> ```
> UserWarning: 
>   Comparisons with None always result in null. 
>   Consider using `.is_null()` or `.is_not_null()`.
> ```

This makes sense, especially since `== None` fails for Series:

```python
>>> pl.Series([1, 2, 3]) == None
TypeError: argument 'rhs': 'NoneType' object cannot be interpreted as an integer
```
