### ISSUE TITLE
schema_overrides is broken when converting from string to numeric

### ISSUE THREAD

**Issue by tgperkins** [pola-rs/polars#13862]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.from_dicts([{'a': '1', 'b': '2'}, {'a':1, 'b':2}], schema_overrides={'a': pl.Int32, 'b': pl.Int32})
```
or
```python
pl.DataFrame([{'a': '1', 'b': '2'}, {'a':1, 'b':2}], schema_overrides={'a': pl.Int32, 'b': pl.Int32})
```

### Log output

```shell
ComputeError: could not append value: "1" of type: str to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`

it might also be that a value overflows the data-type's capacity
```

### Issue description

Version 0.19.13 introduced this bug. The error occurs when converting a string to either a float or int when using a list of dictionaries to create a dataframe.

### Expected behavior

The schema_override should once again correctly cast the columns to the correct types.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
I am not convinced we must parse strings into numbers. Parsing is compute that can become ambiguous. What if you have these strings? `"001", "1.0", "1,1",` In this case the schema override correctly errors. You pass string data and then later must parse them into integers via a `with_columns` call.

**Comment by mcrumiller** [comment]
@ritchie46 should we remove str -> numeric casts elsewhere as well then? I think all of our casts should be consistent regardless of context, i.e. series cast = expr cast = lit cast. Right now we can do:

```python
pl.Series(["1", "2", "3"]).cast(pl.Int32)          # works
pl.Series(["1.5", "2.5", "3.5"]).cast(pl.Float32)  # works
pl.Series(["1.5", "2.5", "3.5"]).cast(pl.Int32)    # fails
```

**Comment by ritchie46** [comment]
@mcrumiller I think the cast is fine. This is what I would expect.

My point is that `casting` string to integers is compute. It should be done as data processing in polars, not in the reader.
