### ISSUE TITLE
Make deprecated functions recognizable by language servers/static analysis tooling

### ISSUE THREAD

**Issue by libklein** [pola-rs/polars#13875]
### Description

Most LSPs and static analysis tools provide warnings about the usage of deprecated functions (or at least indicate that a function is deprecated). This, at least for pyright, does not work with the polars codebase (See example). The reason for this is that polars uses a custom deprecation decorator, which is unfortunately not recognized by pyright ([source code](https://github.com/microsoft/pyright/blob/d21168ee6474245813049f309f8ff06267cb7aca/packages/pyright-internal/src/analyzer/typeUtils.ts#L392)). 

I'd suggest using the approach suggested in [PEP-702](https://peps.python.org/pep-0702/), which will arrive in python 3.13 anyway, and use the deprecated decorator of the typing_extensions module. This would entail changing @deprecate_function into @deprecated. I've experimented with adding the @deprecated decorator to the function returned by the polars-internal decorator, but this is not picked up by pyright. 

I'd be happy to go forward and put a PR in if you believe that this approach is sensible. Feel free to suggest better approaches, I'd be eager to learn more.

Example:
![image](https://github.com/pola-rs/polars/assets/42714034/734003e5-4799-4f62-8a20-42a48bc56e1d)

**Comment by mcrumiller** [comment]
I just dove into the `deprecated` class to see how easy it would be to port the static analysis portion to our deprecations. It is not easy and I gave up after 5 minutes. Maybe someone with more exprerience with decorates and static analysis tools can look into this (@alexander-beedie?).

Making a call-out to #13377 as it's related. The only difference between our `deprecate_function` and `typing_extensions.deprecated` is that we have a `version` parameter, but this parameter is both not actually used by our deprecation function and also is not guaranteed to be correct.

We already use `typing_extensions` extensively throughout the codebase, and although some work went into our deprecation utilities, I wonder if we could off-load our deprecation utilities to this class. Does anybody know if `typing_extensions` supports all of our deprecation types, including renamed parameters, keyword-only deprecations, etc.?

**Comment by stinodego** [comment]
Using built-in functionality is definitely preferable (thank you for educating me on this one). However:

We don't ship with `typing_extensions`, so we would have to add a required dependency for this. And as described in the PEP, requiring `typing` imports during runtime is weird. I would be opposed to this if the only benefit is some IDE highlighting.

If we don't want to include `typing_extensions`, we would have to wait until it becomes available in the `warnings` module in Python 3.13. And then we would have to wait until we drop Python 3.12 support. Which will be 5 years out or so.

So while the PEP sounds good to me and I look forward to using a standardized way of deprecation, I don't think it is relevant just yet. I'll close this as not planned.
