### ISSUE TITLE
Add "calamine" and (maybe) "rxls" engines to read_excel

### ISSUE THREAD

**Issue by SaelKimberly** [pola-rs/polars#13874]
### Description

Hello! 

I've finally published my `rxls` xlsx/xlsb reading engine to [PyPi](https://pypi.org/project/rxls/), after a long time, and extensive testing on real files.

Also, I've update [benchmarks](https://github.com/SaelKimberly/rxls/blob/main/benchmarks.ipynb), and add `calamine` engine to it. Maybe, you will be interested 😃

**Comment by cmdlineluser** [comment]
Just adding for reference:

`calamine` popped up recently in https://github.com/pola-rs/polars/pull/13495#issuecomment-1880005811

(I assume in response to the popular blog post at the time: https://hakibenita.com/fast-excel-python)

**Comment by alexander-beedie** [comment]
I'll take another look at this; the first time I experimented adding `calamine` the type-parsing was not very good and the conversion to python-native data (for subsequent load into the frame) was _extremely_ slow (so it would parse into its own opaque format very quickly, but then you couldn't actually do much with it). 

My understanding from the latest posts is that these issues have been solved, so I'll look to integrate it again 🤔

**Comment by SaelKimberly** [comment]
Sure, I will take a look, tomorrow, I think 🙂

I haven't done this yet, because of benchmark was restarted after each call with %time or %memit, so it requires a couple of time to manually aggregate results (tables are actually hand-made markdown 😅).

**Comment by SaelKimberly** [comment]
So, `rxls` benchmarks file was updated (added some barplots for stats). 😃
