### ISSUE TITLE
add rolling_std

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#1388]
Currently, there are a couple rolling_ expressions available: min, max, mean, sum.  

For my usecase I also need to use the same but for the standard deviation. For now I can use rolling_apply with a custom function as is shown in the [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.rolling_apply.html?highlight=rolling#) with a lambda. But since it is also stated there that  `"Prefer the specific rolling window fucntions over this one, as they are faster."` , it would be nice to have this built-in.

**Comment by ritchie46** [comment]
I assume you mean `rolling_std`. I think I will add an option to create a rolling function out of expressions. That way we could use all the expressions as a rolling function.

Syntax idea:
```python
# apply a rolling rank + sum
col("foo").rolling().rank().sum()
```

**Comment by romanovacca** [comment]
"I assume you mean rolling_std" > indeed.

The suggestions sounds good, that would work nicely

**Comment by ritchie46** [comment]
>  I think I will add an option to create a rolling function out of expressions.

This is easier said than done. :smile:. For now, I settle with the explicit implementations; see #1389

**Comment by ritchie46** [comment]
Added and released
