### ISSUE TITLE
`set_sorted(COL)` before `head` blocks N_ROWS pushdown, also seems to drop the setting column as sorted

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#13887]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from tempfile import TemporaryDirectory
from pathlib import Path

df = pl.DataFrame({"a": list(range(10000))})
with TemporaryDirectory() as tmp:
    tmp = Path(tmp)
    for x in range(5):
        df.write_parquet(tmp / f"{x}.parquet")

    ldf = pl.scan_parquet(tmp / "*.parquet")
    ldf_sort_first = ldf.set_sorted("a").head(5)
    print(ldf.explain())

    ldf_sort_later = ldf.head(5).set_sorted("a")
    print(ldf_sort_later.explain())
```

### Log output

```shell
Parquet SCAN 5 files: first file: /tmp/tmp486vqawl/0.parquet
  PROJECT */1 COLUMNS
```

```
 WITH_COLUMNS:
 [col("a").set_sorted()]

    Parquet SCAN 5 files: first file: /tmp/tmp486vqawl/0.parquet
    PROJECT */1 COLUMNS
    N_ROWS: 5
```
```


### Issue description

As described in title

### Expected behavior

Should have identical query plans

### Installed versions




```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
Python:               3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.10.0
fsspec:               2023.4.0
gevent:               <not installed>
hvplot:               0.8.4
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              12.0.1
pydantic:             1.10.9
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

**Comment by ritchie46** [comment]
Hope to take this after the strings are done. Free to be done by someone else in the meantime. This should be fixed.
