### ISSUE TITLE
Support reading Parquet with partitioned float columns written by `pyarrow` 15.0.0

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13892]
CI is currently broken after the new pyarrow release. Issue are tests related to partitioned Parquet files.

Link to CI failing workflow:
https://github.com/pola-rs/polars/actions/runs/7602639650/job/20703899485?pr=13888

Or reproduce locally by updating pyarrow: `pip install -U pyarrow`
And then running: `pytest tests/unit/io/test_hive.py -m 'write_disk'`

**Comment by mcrumiller** [comment]
Ahh I spent a long time trying to figure out how my PR had broken this. Thanks @stinodego.

**Comment by stinodego** [comment]
Here's a minimal reproduction:

```python
from pathlib import Path

import pyarrow as pa
import pyarrow.dataset

import polars as pl

df = pl.DataFrame({"float": [1.0, 1.0, 2.5, 2.5], "data": [1, 2, 3, 4]})

parquet_path = Path() / "parquet_new"

partitioning = pa.dataset.HivePartitioning(pa.schema([("float", pa.float64())]))
pa.dataset.write_dataset(
    df.to_arrow(),
    base_dir=str(parquet_path),
    format="parquet",
    partitioning=partitioning,
    existing_data_behavior="delete_matching",
)

lf = pl.scan_parquet(parquet_path / "**/*.parquet", hive_partitioning=True)
print(lf.collect())
# polars.exceptions.SchemaError: cannot extend/append Int64 with Float64
```

The issue is with partitioning on float data. The new code truncates `1.0` to `1` in the folder name. The old code used to write `1.0` out fully.

**Comment by deanm0000** [comment]
Looks like it's "only" a problem with it parsing the hive folders but it can read the underlying files one at time so at least there's that.

**Comment by mcrumiller** [comment]
I took a little look into this. For hive partitioning, the schema is derived from the folder urls, so if arrow is writing out floats as ints, there is nothing we can do if all the floats in the initial dataset are integers. I don't believe that the actually-written parquet file metadata even contains the key metadata, as column order isn't preserved anyway (keys are written last into the df).

If we do end up with a mix of ints/floats (e.g. [1.0, 1.5, 2.0] is a mix), then at least one of the folder paths will indicate that we have a float dtype, and in that case we could probably perform an initial scan of al* folders to evaluate the schema.

[Here](https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/logical_plan/builder.rs#L199-L203) is where the first path gets parsed (with parsing code [here](https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/logical_plan/schema.rs#L73-L88)).

**Comment by deanm0000** [comment]
> Has anybody opened an issue for this in the apache repo?

Even if they change it in their next release so the directory is a=1.0 instead of a=1, IMO, it's too late, the genie is already out of the bottle. People are going to have these datasets they'll want to read.

I think, [here](https://github.com/pola-rs/polars/blob/f42759228ae1e212514eec3a70212ac2db6b1186/crates/polars-plan/src/logical_plan/builder.rs#L153-L157) instead of just taking the first file, it needs to iterate [parse_url](https://github.com/pola-rs/polars/blob/f42759228ae1e212514eec3a70212ac2db6b1186/crates/polars-plan/src/logical_plan/hive.rs#L38) over all `paths` so it can find supertypes amongst all of the possibilities of a=1, a=1.5, and even a="one".

**Comment by mcrumiller** [comment]
@deanm0000 that would improve things but would not fix the underlying issue. If for example someone did this:

```python
df = pl.DataFrame({"float": [1.0, 2.0, 3.0], "int": [1, 2, 3]})
df.write_parquet(...)
```
Then there is not enough information in the output to determine that the `float` column should be floats.

**Comment by deanm0000** [comment]
You're right, if someone ends up with a hive dataset from that then the reader will have to interpret "float" as an int. That said, there's nothing to be done about it. Someone with a dataset like that will just have to cast "float" to `pl.Float64` explicitly. 

Perhaps this is a good segue into having discussing a hive partition dtype parameter? Sort of like the csv reader has a dtype (or is it schema) parameter but this would only apply to columns coming from hive folders. More directly, it'd be like [this](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.HivePartitioning.html) except it could just be a dict as opposed to it needing to be a class.

**Comment by mcrumiller** [comment]
FYI I opened a tangential issue at https://github.com/apache/arrow/issues/39763 but as @deanm0000 mentioned, we still need to resolve the existing one where the folder names are mixed ints/floats.

**Comment by nameexhaustion** [comment]
Fixed by https://github.com/pola-rs/polars/pull/17079
