### ISSUE TITLE
Simple optimization rules

### ISSUE THREAD

**Issue by Dandandan** [pola-rs/polars#139]
- [x] lit(x)  OP lit(y) -> lit(x OP y)
   -  [x] Plus
   -  [x] Mul
   -  [x] Div
    - [x] Minus
    - [x] Gt
    - [x] Lt
    - [x] Eq
    - [x] Neq
    - [x] Other
 - [ ] 0 + x -> x
 - [ ] x - 0 -> x
 - [ ] 0 * x -> 0
-  [ ] x / 1 -> x
 - [x] true AND x -> x
 - [x] false AND x -> false
 - [x] false OR x -> x
 - [x] true OR x -> true
 - [x] not (not x) -> x
 - [x] not (lit x) -> lit(!x)

**Comment by Dandandan** [comment]
More general than the first one: Would be nice if we can fold all constant expressions, including not, eq, binary ops etc.

**Comment by universalmind303** [comment]
Closing as we now support simplifying these expressions
