### ISSUE TITLE
Parametric tests fail in ways that isn't visible in CI

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#13911]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

N/A

### Issue description

Hypothesis tests either aren't run in CI, or are run with insufficient number of examples or run time. The result is that some tests are failing, unnoticed. A few days ago one set of tests in `test_roundtrip.py` was broken when run on my computer, and today (Jan 22, 2024) a different set of tests are broken.

As a result I repeatedly had to do the work of figuring out if the failing tests were my branch's fault or not.

### Installed versions

```
$ git log -1
commit bb2d2353d83b91c6c5f60d10f4a8eec98dea40c5 (HEAD, origin/main, origin/HEAD, itamarst/main, main)
Author: Ritchie Vink <ritchie46@gmail.com>
Date:   Mon Jan 22 13:53:06 2024 +0100

    python polars 0.20.6-rc.1 (#13906)
```

**Comment by ritchie46** [comment]
Is `main` broken now? I am surprised the parameteric tests don't run. Though for CI, I must defer to @stinodego.

**Comment by MarcoGorelli** [comment]
I think you just need to update your pandas version

**Comment by itamarst** [comment]
Earlier today I was on 2.1.4. I just upgraded to 2.2.0, and now I'm getting just failing tests to DeprecationWarning on `test_roundtrip.py`, rather than what I was getting before. So, maybe. Any sense why DeprecationWarnings would be errors locally but not in CI?

**Comment by itamarst** [comment]
Anyway can't reproduce with Pandas 2.2.0 so closing, sorry for the noise.
