### ISSUE TITLE
Add describe() for LazyFrame

### ISSUE THREAD

**Issue by niccolopetti** [pola-rs/polars#13928]
### Description

Currently `describe` is not implemented for lazyframes, and you have to first materialize into a Dataframe before being able to call `describe` , however all methods called into describe seem to be supported by Lazyframe:
[polars.LazyFrame.count](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.count.html)
[polars.LazyFrame.max](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.max.html#)
[polars.LazyFrame.mean](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.mean.html)
[polars.LazyFrame.median](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.median.html)
[polars.LazyFrame.min](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.min.html)
[polars.LazyFrame.null_count](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.null_count.html)
[polars.LazyFrame.quantile](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.quantile.html)
[polars.LazyFrame.std](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.std.html)
[polars.LazyFrame.sum](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.sum.html)
[polars.LazyFrame.var](https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.var.html)

so why don't we allow LazyFrame.describe() ?

**Comment by stinodego** [comment]
`describe` is meant as a way to get some quick insights in your data. It could work on a LazyFrame, but then you would have to call `collect()` right after anyway, otherwise you're not much wiser. It just doesn't make sense as a lazy method.

Just `collect` first and then use `describe`.

**Comment by niccolopetti** [comment]
> `describe` is meant as a way to get some quick insights in your data. It could work on a LazyFrame, but then you would have to call `collect()` right after anyway, otherwise you're not much wiser. It just doesn't make sense as a lazy method.
> 
> Just `collect` first and then use `describe`.

But what if the Dataframe is so big that it wouldn't fit in memory?

**Comment by alexander-beedie** [comment]
Yup, I think it's worthwhile - I can see that there are plenty of cases where you don't want to materialise GBs of data into a local frame just to run `describe()` on it 🤔

**Comment by mcrumiller** [comment]
"looks pretty lazy!" sounds like a valid description to me, can we just return that?
