### ISSUE TITLE
Add as_dict option in LazyFrame serialize

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#13925]
### Description

If we want to extract some info from a LazyFrame's serialization, for example, the file list, we have to parse the json of `serialize`. While it isn't a big deal to do `json.loads(lf.serialize())` it seems like it'd be better to do `lf.serialize(as_dict=True)` and skip json altogether.

**Comment by stinodego** [comment]
I don't think an additional parameter for this is warranted. We might add additional serialization options in the future, and then `as_dict` doesn't make sense.

You can already implement your intended behavior by parsing the JSON string with `str.json_decode`, if you really need to dig into a serialization string, you can use that. But generally, I would recommend against that practice. A serialized LazyFrame is just a bucket of bytes, that happens to be JSON with the current implementation.

If there is specific information about the logical plan that you need to extract, and you don't currently have the ability to do so, please open an issue for that. We can see if we can implement it.
