### ISSUE TITLE
`Series.arg_min`/`arg_max` give incorrect results when dtype is categorical with lexical ordering

### ISSUE THREAD

**Issue by petrosbar** [pola-rs/polars#13968]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.Series(["d", "c", "b", "a"], dtype=pl.Categorical(ordering="physical")).arg_max()
# Returns 3

# But...

pl.Series(["d", "c", "b", "a"], dtype=pl.Categorical(ordering="lexical")).arg_max()
# ...returns also 3. It should be 0!
```

### Issue description

`Series.arg_min` and `Series.arg_max` return incorrect results when called on categoricals that are defined to have a lexical ordering. It seems that the returned value of the functions is the same as that with `physical` ordering.

### Expected behavior

`Series.arg_min`/`max` with `dtype=pl.Categorical(ordering="lexical")` should behave the same as `dtype=pl.String`.

```python
pl.Series(["d", "c", "b", "a"], dtype=pl.Categorical(ordering="lexical")).arg_max()
# Should be 0
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by petrosbar** [comment]
@stinodego I'll be happy to give it a shot.

**Comment by stinodego** [comment]
Great! Looking forward to the PR.
