### ISSUE TITLE
Initially empty series causes memcpy_values to index OOB

### ISSUE THREAD

**Issue by TheDan64** [pola-rs/polars#1396]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

`"lazy", "random", "temporal", "dtype-date64", "dtype-u64", "object"`

#### What version of polars are you using?

Latest or nearly latest master (`06448f61bea22f1a7407bbfa1c3a364354192713`)

#### What operating system are you using polars on?

Win10

#### Describe your bug.

Program crashes when it uses the length of the original input vec?

#### What are the steps to reproduce the behavior?

```rust
    use polars::prelude::ChunkAgg;
    let data = vec![
        1.3; 42
    ];
    let mut series = Series::new("data", Vec::<f64>::new());
    let series2 = Series::new("data2", data.clone());
    let series3 = Series::new("data3", data);
    let df = DataFrame::new(vec![
        series2,
        series3,
    ])?;

    for column in df.get_columns().iter() {
        series.append(column)?;
    }
    series.f64().unwrap().quantile(0.25)?.unwrap();
```

#### What is the actual behavior?

`thread 'main' panicked at 'source slice length (42) does not match destination slice length (0)', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\slice\mod.rs:3058:13`

#### What is the expected behavior?

The program shouldn't crash and should be able to calculate the quantile as expected. This is a regression from a previous version

**Comment by ritchie46** [comment]
Thanks for the MWE  @TheDan64. This fix is in #1397.
