### ISSUE TITLE
Implement NumPy array interface protocol

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13980]
This should help NumPy interop:
https://numpy.org/doc/stable/reference/arrays.interface.html

**Comment by baggiponte** [comment]
This means one could eventually to `import torch; torch.tensor(dataframe)`, am I right? But it would still be up to Polars dev team to minimise the number of copies made, etc.

**Comment by stinodego** [comment]
> This means one could eventually to `import torch; torch.tensor(dataframe)`, am I right? But it would still be up to Polars dev team to minimise the number of copies made, etc.

Actually, `torch.tensor` does not seem to be using the NumPy protocol. We implement `__array__` but it still cannot take a DataFrame. You have to explicitly export to NumPy first, or use our new functionality `df.to_torch()`.

**Comment by stinodego** [comment]
After some research I do not think it is worth implementing the protocol. It is not a good match for describing arrow data, since it does not support bitpacked booleans. Anything with nulls becomes impossible to describe.

We have now optimized our `__array__` implementation to provide zero copy conversions where possible. I think that should suffice for integrations.

If someone can make a strong case for implementing `__array_interface__`, I will consider reopening this.
