### ISSUE TITLE
float to Decimal: `cast` works but `to_decimal` fails

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#13988]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame(
    {
        "x": [1, 1.2, 1.23],
    }
).with_columns(
    # OPTION 1: works
    d=pl.col("x").cast(pl.Decimal(scale=2)),

    # OPTION 2: fails (SchemaError: invalid series dtype: expected `String`, got `f64`)
    d2=pl.col("x").str.to_decimal(),
)
```

### Log output

```shell
SchemaError: invalid series dtype: expected `String`, got `f64`


# Option 1 works:
shape: (3, 2)
┌──────┬───────────────┐
│ x    ┆ d             │
│ ---  ┆ ---           │
│ f64  ┆ decimal[38,2] │
╞══════╪═══════════════╡
│ 1.0  ┆ 1             │
│ 1.2  ┆ 1.20          │
│ 1.23 ┆ 1.23          │
└──────┴───────────────┘
```

### Issue description

converting from float to decimal works using `cast` but fails using `to_decimal`.

### Expected behavior

conversion should work both ways.

Ofc it would be better to convert from str and not float irl is happends that you need to go from float to decimal

---
Note: I am opening a lot of Decimal Issues (Decimals are required for many financial calculations where I currently use pyspark). I heard a bigger Decimal update is coming soon? Not sure abount the roadmap but happy to help.

### Installed versions

<details>

```
0.20.5
```

</details>

**Comment by tlm365** [comment]
@JulianCologne I think there is a misunderstanding here. In official docs: [polars.Expr.str.to_decimal](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.str.to_decimal.html#polars-expr-str-to-decimal) - Convert a String column into a Decimal column. But datatype of `col("x")` original is `f64` not `String`.
I guess you understand that `pl.col("x").str` is method cast `col("x")` to `String`, but it not. In fact, `pl.col("x")` is `pl.Expr` and `.str.to_decimal()` is method cast String to Decimal.

So, it will works if code look like this
```
pl.DataFrame(
    {
        "x": [1, 1.2, 1.23],
    }
).with_columns(
    # OPTION 1: works
    d=pl.col("x").cast(pl.Decimal(scale=2)),

    # OPTION 2:
    d2=pl.col("x").cast(pl.Utf8).str.to_decimal()
)

shape: (3, 3)
┌──────┬──────┬──────────────┐
│ x    ┆ d    ┆ d2           │
│ ---  ┆ ---  ┆ ---          │
│ f64  ┆ f64  ┆ decimal[*,2] │
╞══════╪══════╪══════════════╡
│ 1.0  ┆ 1.0  ┆ 1            │
│ 1.2  ┆ 1.2  ┆ 1.20         │
│ 1.23 ┆ 1.23 ┆ 1.23         │
└──────┴──────┴──────────────┘
```

**Comment by JulianCologne** [comment]
@tlm365 yes, you are totally correct! Not sure what I was thinking... too many things probably 😆 . Closing for now.
