### ISSUE TITLE
Possible performance issue with predicate push-down when reading Parquet from Azure Blob

### ISSUE THREAD

**Issue by imm-ds** [pola-rs/polars#13990]
## Issue Description

I have encountered an opportunity for performance improvement when testing using Polars via ClickHouse to access Parquet Azure Storage. 

In short 

```python

client  =  clickhouse_connect.get_client(host='localhost', port=18123)
q = 'SELECT * FROM url(f'{ CONNECTION_STRING }', Parquet) WHERE userId = 13614'
pl.from_arrow(client.query_arrow(q))
```

**is 8x faster than scanning, filtering, and collecting a parquet file via Polars**

```python
pl.scan_parquet( f'{CONNECTION_STRING }').filter(userId =  13614).collect()
```

To me this indicates that Polars is not fully leveraging predicate push-downs when reading from blob storage. 

Note that here I'm simply running Clickhouse on the same computer running Polars - there is no co-location of storage & compute, and this works with new files meaning it's likely not related to caching.

## Code Demonstrating the Issue

This references a 300mb parquet file in blob storage. 6m+ rows, sorted first by `userId` (int64, 40k unique values) and then by `asOfDate` (date; 40 unique values).

```python
import clickhouse_connect
import polars as pl
storage_options = dict(sas_token=AZURE_LIMITED_SAS_TOKEN, account_name=AZURE_BLOB_STORAGE_ACCOUNT_NAME)

BLOB_STORAGE_NAME: ...
FILE_NAME = ... 
    
client  =  clickhouse_connect.get_client(host='localhost', port=18123) # Just running clickhouse locally
    
TABLE  =  f"url('{CONNECTION_STRING}', Parquet)"
Q0  =  f'SELECT * FROM {TABLE}'
Q1  =  f'SELECT * FROM {TABLE} WHERE userId = 13614' # Some random userId
Q2  =  f"SELECT * FROM {TABLE} WHERE asOfDate = '2020-01-01'" # Some random date
    
def get_clickhouse(q, client=client)->pl.DataFrame:
	return pl.from_arrow(client.query_arrow(q))
	    
df_lazy  =  pl.scan_parquet(f'az://{BLOB_STORAGE_NAME}/{FILE_NAME}', storage_options=storage_options)
	
# using scan parquet to access Azure
df_pq1 = df_lazy.filter(userId = 24937).collect() # 8.06 seconds
	
# using Clickhouse connect to access Azure
df_ch1 = get_clickhouse(Q1) # 1.24 seconds
	
# using scan parquet to access Azure
df_pq2 = df_lazy.filter(asOfDate = pl.date(2020,1,1)).collect() # 9.63 seconds
	
# using Clickhouse connect to access Azure
df_ch2 = get_clickhouse(Q2) # 8.10 seconds
```

## Details

-   **Polars Version**: 0.20.3
-   **ClickHouse Version**: 0.7.0

## Expected Behavior

I expect similar or improved performance when using Polars' `scan_parquet` to access Parquet files on Azure Storage, as compared to using ClickHouse directly.

## Actual Behavior

The performance is noticeably slower when using `scan_parquet` with Azure Storage, and it becomes more pronounced when compared to accessing the same data using ClickHouse.
|Query|Polars|Clickhouse|Speed vs Polars
|--|--|--|--|
|Q1 (filtering on an sorted column) | Wall time: 8.06 s |Wall time: 1.24 s|**6.5x**|
|Q2 (filtering on a un-sorted column)| Wall time: 9.63 s |Wall time: 8.1 s |**1.2x**

**Comment by deanm0000** [comment]
try the latest version, I think your issue is fixed.

**Comment by alexander-beedie** [comment]
Thanks for the report; this should be [fixed](https://github.com/pola-rs/polars/pull/13864) on `main`, and will be in the upcoming `0.20.6` 👍

**Comment by ritchie46** [comment]
Already fixed
