### ISSUE TITLE
Allow scan_parquet to specify a list of columns similar to read_parquet

### ISSUE THREAD

**Issue by cdmoye** [pola-rs/polars#13993]
### Description

Currently, in `read_parquet`, you can specify a list of columns to include in the resultant DataFrame. In `scan_parquet`, there's not a similar construct available for the resulting LazyFrame. 

Sure, I can drop all the columns I'm not interested in with a `drop` on the end. But, does that happen before the `collect` or `sink_parquet` or after? It's unclear to me. 

Adding a columns specification parameter similar to that in `read_parquet` seems the clearest way.

**Comment by ritchie46** [comment]
No, write your query The optimizer will select the columns you need automatically.

You just write `pl.scan_parquet(..).select([my_columns]).rest_of_query()`

**Comment by cdmoye** [comment]
So, instead of having a columns parameter, just do the select after the scan. Got it. It's still a little disorienting, imo, to have that difference in usage. But I can certainly live with it :)
