### ISSUE TITLE
`coerce_arrow`'s rechunk option is never used

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#13992]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

NA

### Issue description

The `coerce_arrow` function has an option called `rechunk`, but I don't see where this is specified.
I am wondering if this is a forgotten option. (I am particularly concerned that the rechunk option is not propagated when called in `arrow_to_pyseries`)

https://github.com/pola-rs/polars/blob/06c019045b119961bd205d8956d96da4d4da08b4/py-polars/polars/utils/_construction.py#L1790

https://github.com/pola-rs/polars/blob/06c019045b119961bd205d8956d96da4d4da08b4/py-polars/polars/utils/_construction.py#L182-L184

### Expected behavior

The option is used, or the option should be removed.

### Installed versions

Current dev version

**Comment by ritchie46** [comment]
Can you try removing it?

**Comment by eitsupi** [comment]
Sure, I will send a PR.
