### ISSUE TITLE
Is it possible to make self joins more able to be parallel without deadlock?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#14003]
### Description

I stumbled on this [SO question](https://stackoverflow.com/questions/75979236/what-is-the-difference-between-polars-collect-all-and-polars-lazyframe-collect/77883327#77883327) and discovered this:

https://github.com/pola-rs/polars/blob/a6ee1e9dd1151a7d1aab390d45125e3c23425b14/crates/polars-lazy/src/physical_plan/planner/lp.rs#L479-L482

I wonder if there's any way to improve that check or workaround the deadlock issue such that more self joins can be parallel.

**Comment by ritchie46** [comment]
The joins are still parallel. We only don't evaluate the sources in parallel. But the operators below still work with their own paralellism.

**Comment by deanm0000** [comment]
hmm.

If you can spare a couple minutes to look at that SO question, one extra detail is that, looking at htop, in their Option 1 my cores were all maxed out but in option 2 they were all at around 80%. If the parallel joins: off is a red herring then my next guess is that serial/parallel paths are just different so in their option 2 so there's underutilized cpu.

It's not a big deal but just thought it was interesting.
