### ISSUE TITLE
Unable to call str() from a column like col().str()

### ISSUE THREAD

**Issue by hrishim** [pola-rs/polars#14034]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

let out = df_csv.clone().lazy().select([
        col("Date"),
        col("Date").str().alias("datetime"),
        col("Close")
    ]).collect();

```

The above code is similar to the [example](https://docs.pola.rs/user-guide/expressions/strings/#accessing-the-string-namespace) in the documentation

I get a compiler error:
```
error[E0599]: no method named `str` found for enum `Expr` in the current scope
  --> src/main.rs:84:21
   |
84 |         col("Date").str().alias("datetime"),
   |                     ^^^ help: there is a method with a similar name: `std`
```

My dataframe looks like:

```
┌─────────────┬──────────┐
│ Date        ┆ Close    │
│ ---         ┆ ---      │
│ str         ┆ f64      │
╞═════════════╪══════════╡
│ 01 Jan 2024 ┆ 21741.9  │
│ 29 Dec 2023 ┆ 21731.4  │
│ 28 Dec 2023 ┆ 21778.7  │
│ 27 Dec 2023 ┆ 21654.75 │
│ …           ┆ …        │
│ 09 Jul 1990 ┆ 289.69   │
│ 06 Jul 1990 ┆ 289.04   │
│ 05 Jul 1990 ┆ 284.04   │
│ 03 Jul 1990 ┆ 279.02   │
└─────────────┴──────────┘
```

### Log output

```shell
error[E0599]: no method named `str` found for enum `Expr` in the current scope
  --> src/main.rs:84:21
   |
84 |         col("Date").str().alias("datetime"),
   |                     ^^^ help: there is a method with a similar name: `std`
```

### Issue description

I tried code that is similar the example in the documentation. I get a compiler error.

### Expected behavior

Code should compile correctly. col("Data").str().alias("datetime") should create a new column from the original 

### Installed versions

<details>

Replace this line with a list of feature gates
polars = { version = "0.36.2", features = ["lazy","temporal","random","dtype-datetime","dtype-duration"] }

</details>

**Comment by ritchie46** [comment]
You must activate the `strings` feature.

**Comment by hrishim** [comment]
@ritchie46 - Thank you that worked.

What I am trying to do is to create a new column of datetime from a column that has dates as strings ?

So I essentially need to call  this function NaiveDate::parse_from_str(EVERY_ENTRY_OF_DATE, "%d %b %Y") on every entry of col("Date") and add the result to a new column. How can I go about this ?

**Comment by hrishim** [comment]
Not a bug. My misunderstanding
