### ISSUE TITLE
Add `pl.hypot` function

### ISSUE THREAD

**Issue by DJDuque** [pola-rs/polars#14031]
### Description

There is already a `pl.arctan2(y, x)` function, it might make sense to add a `pl.hypot(x, y)`.

Currently, I am doing:
```
df = (
    pl.read_csv(input_file)
    .with_columns(
        pl.arctan2("y", "x").alias("theta"),
        (pl.col("x").pow(2) + pl.col("y").pow(2))
        .sqrt()
        .alias("r"),
    )
)
```

And this is probably a pattern common enough to benefit from a `pl.hypot` function:
```
df = (
    pl.read_csv(input_file)
    .with_columns(
        pl.arctan2("y", "x").alias("theta"),
        pl.hypot("x", "y").alias("r"),
    )
)
```

**Comment by stinodego** [comment]
This feels too specialized to be part of the main Polars API.

Similar to #3043, this might be added to a cookbook of sorts: https://github.com/pola-rs/polars/issues/13064
