### ISSUE TITLE
Polars date arithmetic is not correct

### ISSUE THREAD

**Issue by akmr999** [pola-rs/polars#1404]
#### Are you using Python or Rust?
 **Python**.

#### What version of polars are you using?
polars-0.9.9

#### What operating system are you using polars on?
Windows

#### Describe your bug.
Polars date arithmetic is not correct. More details below.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

# Create a simple dataset on which we can reproduce the bug.
test = pl.read_csv('test_dates.csv', use_pyarrow=True)

# output month diff
test.acquisition_date.dt.month() - test.order_date.dt.month()

# output day diff
(test.acquisition_date.dt.day() - test.order_date.dt.day())
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?
![image](https://user-images.githubusercontent.com/91093911/134073311-dae8d760-2a96-45c3-b9a7-0754a5cf04ba.png)

![image](https://user-images.githubusercontent.com/91093911/134077152-8bcafa50-0ae7-4874-a947-c051d638e113.png)

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/91093911/134077028-28d24e24-f6ab-492e-b679-e0369d07659f.png)

Month diff should be an integer between 0 to 12 and day diff an integer between 0 and 31

File to reproduce this error. Apologies in advance if I missed something
[test_dates.csv](https://github.com/pola-rs/polars/files/7198657/test_dates.csv)

**Comment by ritchie46** [comment]
This is not really a bug. If you subtract for instance month 11 from month 2, you end up with a negative number which does not really make sense. In the case on unsigned integers, which we've got here, you underflow and end up with a large number, which also does not make sense.

You first need to do the arithmetic on the dates and only then extract the month numbers.

**Comment by akmr999** [comment]
Thank you for the quick response. Sorry this is all a bit new for me.

**Comment by akmr999** [comment]
Hi @ritchie46,

I had been converting polars' dataframe to pandas to achieve date related functionality and would really like to stick to polars. I have few basic questions:
1. What is the right way to calculate _months_ in the code below? 
2. Group by clause below really looks clunky. What is the recommended approach for creating year/month combo for group by? In pandas, I would convert it to month periods like this df['order_date'].dt.to_period('M'). Is there anything equivalent in polars?

Thanks in advance! 

`
test_x = test.lazy().groupby([pl.col('acquisition_date').dt.year().alias('acq_year'), pl.col('acquisition_date').dt.month().alias('acq_month'), pl.col('order_date').dt.year().alias('ord_year'), pl.col('order_date').dt.month().alias('ord_month')]).agg(
    [
        pl.col('order_date').count().alias('dummy_count'),        
    ]
).sort(['acq_year', 'acq_month','ord_year','ord_month'])


cohort = test_x.select(
    [
        pl.col('*'),
        ((pl.col('ord_year') - pl.col('acq_year'))*12 + (pl.col('ord_month') - pl.col('acq_month'))).alias('months')
    ]
)

cohort.collect()

` 
![image](https://user-images.githubusercontent.com/91093911/134239715-dbbe9299-ef7e-485e-9caa-26181339670e.png)
