### ISSUE TITLE
misleading min_horizontal() message for sum(axis=1)

### ISSUE THREAD

**Issue by ozanciga** [pola-rs/polars#14054]
### Description

when using something like `(df.select('col') == label).sum(axis=1)`  i get

> <string>:2: DeprecationWarning: The `axis` parameter for `DataFrame.sum` is deprecated. Use `DataFrame.min_horizontal()` to perform horizontal aggregation.

however i believe the message should suggest `sum_horizontal()` instead.

separately i'm not sure why sum(axis=1) is not good practice, but that's just preference and habit on my part

### Link

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.sum.html

**Comment by mcrumiller** [comment]
Hi @ozanciga, we should definitely fix the deprecation warning, as it should say to use `sum_horizontal` instead.

Regarding the `axis` parameter, it's not that it's not good practice, it's that the parameter is being deprecated and so, in future releases, that parameter will simply not work. Polars tries to keep separate operations as separate functions, and horizontal aggregations and vertical aggregations can be easily mixed up, especially when an `axis` parameter that is based on a somewhat arbitrary index is used (developers must know that axis=0 is vertical and axis=1 is horizontal, and this is not completely obvious to new users). See [this comment](https://github.com/pola-rs/polars/issues/12444#issuecomment-1810826957) for more details on this decision to separate out horizontal functions.
