### ISSUE TITLE
`read_csv` broken logic for date/datetime type/schema inference and parsing

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#14064]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from io import StringIO

# try switching rows 1 and 2
DATA = """date
banana
2020-01-01

xxx"""

pl.read_csv(
    source=StringIO(DATA),
    try_parse_dates=True,
)
```

### Issue description

date/datetime type/schema inference and parsing seems to be "broken" on multiple levels.

I would also strongly suggest renaming `try_parse_dates` to something like `infer_date_types` / `infer_temporal_types`. Why `try`? This can be completely consistent with how other types like int/float are handled. 

## Only 1 single date value infers whole column to be of type `Date`

```python
DATA = """date
2020-01-01
banana

xxx"""

pl.read_csv(
    source=StringIO(DATA),
    try_parse_dates=True,
)

shape: (4, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │ <<<<< why Date? There is only 1 value that looks like a date??
╞════════════╡
│ 2020-01-01 │
│ null       │ <<<<< (next issue): this should raise ("banana")!
│ null       │
│ null       │ <<<<< (next issue): this should raise ("xxx")!
└────────────┘
```

imo this should be consistent with the other types like `int/float` where ALL values must be of the correct type. Otherwise the column is inferred as `str`. You can always enforce a date column using `dtypes`. But imo it should never cast a column to `Date` because maybe 1 of 20_000 rows "looks" like a date.

## `ignore_errors` parameter not respected

Same code as above.

`ignore_errors` should mean the following
- `False`: "be strict", all invalid values should raise an error;
- `True`: all invalid values should be set to `null`.

This works for the other types like int/float but NOT for date/datetime.
For those it will (almost [see next bug]) always set invalid values like "banana" to `null`.

## Order of csv rows matters?!?

same code as above BUT lines 2 and 3 switched so "banana" is the first row with values.

results:
```
ComputeError: could not parse `banana` as dtype `date` at column 'date' (column number 1)
```

There seems to be some weird logic where 
- First row okay -> ignore all future errors and set to `null`
- First row NOT okay -> be strict and raise error

### Expected behavior

I expect no weird surprises but clear behaviour like it is for int/float.

This is what I expect: behave just like `int`

## Data type only inferred if all values are valid, otherwise set to `str`

```python
DATA = """int
1

banana
4"""

shape: (4, 1)
┌────────┐
│ int    │
│ ---    │
│ str    │ <<<<<< str because "banana" is no int
╞════════╡
│ 1      │
│ null   │
│ banana │
│ 4      │
└────────┘
```

## `ignore_errors` parameter respected

same DATA as above

```python
pl.read_csv(
    source=StringIO(DATA),
    ignore_errors=True,  # <<<<<
    dtypes={"int": pl.Int32}, # <<<< types specified because "banana" makes column "str" otherwise
)

shape: (4, 1)
┌──────┐
│ int  │
│ ---  │
│ i32  │
╞══════╡
│ 1    │
│ null │
│ null │ <<<<<< error ignored as specified
│ 4    │
└──────┘
```

Don't ignore errors. Be strict. This correctly raises an error
```python
pl.read_csv(
    source=StringIO(DATA),
    ignore_errors=False,  # <<<<<
    dtypes={"int": pl.Int32},
)

# YES! I explicitly want to error on invalid values
# ComputeError: could not parse `banana` as dtype `i32` at column 'int' (column number 1)
```

### Installed versions

<details>

```
0.20.6
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report
