### ISSUE TITLE
Add Series::hmin, hmax, clamp

### ISSUE THREAD

**Issue by elbaro** [pola-rs/polars#1408]
#### Describe your feature request

```rs
let min_values = series1.hmin(&series2)?;  // series1.len == series2.len == min_values.len
let max_values = series1.hmax(10.5)?;

let clamped1 = series1.clamp(-0.5, 0.5);
let clamped2 = series2.clamp(&series1, 0.5);
```

**Comment by zundertj** [comment]
Please note that #2369 adds `clip`, which is what is sometimes called `clamp`.  What would `hmin` and `hmax` do?

**Comment by elbaro** [comment]
`hmin` is the min of two series. The name means horizontal min which I borrowed from somewhere I don't remember now. Please use a better name if you have any.

**Comment by mkleinbort-ic** [comment]
I think you could achieve this via 

```
df = pl.DataFrame({'A':[1,2,3,4],'B':[4,3,2,1]}) 
df.with_column(pl.concat_list(['A','B']).arr.min().alias('hmin') 
```

**Comment by ritchie46** [comment]
> `hmin` is the min of two series. The name means horizontal min which I borrowed from somewhere I don't remember now. Please use a better name if you have any.

See: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.min.html#polars.min
