### ISSUE TITLE
S3: `scan_parquet` fails while `read_parquet` succeeds

### ISSUE THREAD

**Issue by caseytomlin** [pola-rs/polars#14102]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s3_path = "s3://...parquet"
pl.read_parquet(s3_path)  # ok
pl.scan_parquet(s3_path)  # fails
```

### Log output

```shell
`ComputeError: Generic S3 error: Client error with status 403 Forbidden: No Body`
```

### Issue description

I have a feeling this is answered somewhere but didn't find. Similar to some existing issues, eg [this](https://github.com/pola-rs/polars/issues/11372).

Note that `AWS_PROFILE` is set, which has a default region

### Expected behavior

`scan_parquet` and `read_parquet` fail or succeed in the same ways (regarding S3 accessibility)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-5.15.0-1050-aws-x86_64-with-glibc2.31
Python:               3.9.10 (main, Sep 21 2023, 13:02:36) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.23.5
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             1.10.14
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Please update to latest version. We changed backend.

**Comment by caseytomlin** [comment]
Is it correct that now simply having `AWS_PROFILE` set will _not_ work for both `read_` and `scan_` (while previously this worked for `read_` but not for `scan_`)? Is there some simple method I am missing that is more pandas-like (that doesn't require me to explicitly pass the AWS id and secret as `storage_options`)?

**Comment by stinodego** [comment]
> Is it correct that now simply having `AWS_PROFILE` set will _not_ work for both `read_` and `scan_` (while previously this worked for `read_` but not for `scan_`)? Is there some simple method I am missing that is more pandas-like (that doesn't require me to explicitly pass the AWS id and secret as `storage_options`)?

That is correct. Previously, we used `fsspec`, which does a better job of detecting various secrets/variables (we have not implemented all of this yet). If you _need_ to keep using `fsspec` I believe you can do:

```python
import polars as pl
import fsspec

url = "s3://bucket"
with fsspec.open(url) as f:
df = pl.read_parquet(f)
```

**Comment by s-banach** [comment]
By the way, `fsspec` does not work anymore:
``` python
with fsspec.open(url) as f:
    df = pl.read_parquet(f)
# TypeError: argument 'paths': 'bytes' object cannot be converted to 'PyString'
```

I'm trying to identify why polars read_parquet and scan_parquet randomly give me 403 errors on S3 sometimes, when other times they read the same file without error.

I was wondering if I could use s3fs or fsspec or something to force them to work as the first step in debugging.

**Comment by stinodego** [comment]
@s-banach that's surprising to me - can you open an issue for this?
