### ISSUE TITLE
In 0.37.0 `horizontal_concat` is listed as a feature flag in the docs but doesn't exist

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#14104]
### Description

On https://docs.rs/polars/latest/polars/index.html `horizontal_concat` is listed as a feature flag. That's actually not the case as seen here: https://docs.rs/crate/polars/latest/features

Related issue: https://github.com/pola-rs/polars/issues/13755

Also some of the flags are not documented on the [main docs page](https://docs.rs/polars/latest/polars/index.html) at all e.g. `ipc_streaming`, `cloud`
### Link

https://docs.rs/polars/latest/polars/index.html

**Comment by stinodego** [comment]
The undocumented features can be their own topic. You maybe you can submit a PR and add those?

**Comment by jmakov** [comment]
My issue is even if I wanted to open a PR, how to know what e.g. the `cloud` or `array_count` flag does other than trying to understand the source.
