### ISSUE TITLE
Document that Kleene logic is followed in any_horizontal and all_horizontal, expand examples

### ISSUE THREAD

**Issue by pascalschwahn** [pola-rs/polars#14130]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'a': [True, False, None],
    'b': [None, None, None],
}).with_columns([
    pl.any_horizontal('a', 'b').alias('any')
])

print(df)
```

### Log output

```shell
shape: (3, 3)
┌───────┬──────┬──────┐
│ a     ┆ b    ┆ any  │
│ ---   ┆ ---  ┆ ---  │
│ bool  ┆ null ┆ bool │
╞═══════╪══════╪══════╡
│ true  ┆ null ┆ true │
│ false ┆ null ┆ null │
│ null  ┆ null ┆ null │
└───────┴──────┴──────┘
```

### Issue description

The behavior of any_horizontal() is not intuitive, since the combination of (true, null) leads to true, but (false, null) leads to null. 

### Expected behavior

Only if all inputs of any_horizontal() are null, the return value should be null.
Expected Output:

| a  | b | any |
| ------------- | ------------- | ------------- |
| true | null | true |
| false | null | **false** |
| null | null | null |

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
looks correct based on https://en.wikipedia.org/wiki/Three-valued_logic ?

pandas does the same
```python
In [6]: lhs = pd.Series([True, pd.NA, False], dtype='boolean[pyarrow]')

In [7]: lhs | pd.NA
Out[7]:
0    True
1    <NA>
2    <NA>
dtype: bool[pyarrow]
```

**Comment by pascalschwahn** [comment]
The Wikipedia article explains it well! Thank you! Would it be possible to include such an example in the documentation? Currently only the case (true, null) is shown. Then I would not have identified it as a possible error.
[pl.any_horizontal() documentation](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.any_horizontal.html#polars.any_horizontal)

**Comment by MarcoGorelli** [comment]
yeah I think it'd be worthwhile to add extra rows to the example `df`, showcasing the various combinations, thanks for the suggestion
