### ISSUE TITLE
sort_by in cumsum and similar aggregate functions

### ISSUE THREAD

**Issue by soerenwolfers** [pola-rs/polars#14139]
### Description

Aggregate functions such as `cumsum` should get a `sort_by` parameter. 

**Simple example:**

For example, if I had a dataframe with sales such as 
```
sales = pl.DataFrame(
    {
        'amount': [1, 2, 3, 4, 5, 6],
        'time': [1.1, 2.2, 0.1, 1.2, 2.1, 0],
    } 
)
```
it would be possible to do
```
sales.select(
    pl.col('amount').cumsum(sort_by='amount').alias('cumAmountBySize'),
    pl.col('amount').cumsum(sort_by='time').alias('cumAmountByTime'),
    pl.col('amount'),
    pl.col('time'),
)
```
where the first cumulation can be used to see how important all sales below a certain level are compared to the total, and the second cumulation can be used to see how sales cumulate over a given period. 

Even if you just want a single cumulative sum, the currently possible dataframe-sorting solution
```
sales.sort('time').select(
    pl.col('amount').cumsum().alias('cumAmountByTime'),
    pl.col('amount')
)
```
is worse than 
```
sales.select(
    pl.col('amount').cumsum(sort_by='time').alias('cumAmountByTime'),
    pl.col('amont')
)
```
because the former doesn't preserve ordering, which may be an inconvenience depending on context.

**Advanced example:**

Another strength of my proposal is that it can help avoid repetitive and unmaintainable code when combined with `.over()` or `.groupby()`.

For this, let's look at a slightly more involved example with sales of different products:
```
sales = pl.DataFrame(
    {
        'product': ['a', 'b', 'a', 'b', 'a', 'b'],
        'amount': [1, 2, 3, 4, 5, 6],
        'time': [1.1, 2.2, 0.1, 1.2, 2.1, 0],
    } 
)
```
and let's say we want to create a new column with the cumulative-by-time sales per product.
Currently, the best option I am aware of is
```
sales.select(
    pl.col('amount').sort_by('time').cumsum().over('product').alias('cumAmount'), 
    pl.col('time').sort_by('time').over('product'),
    pl.col('amount').sort_by('time').over('product'),
    pl.col('product').sort_by('time').over('product'),
)
```
which is not only ugly but also runs a high risk of me accidentally writing the entirely incorrect
```
sales.select(
    pl.col('amount').sort_by('time').cumsum().over('product').alias('cumAmount'), 
    pl.col('time'),
    pl.col('amount'),
    pl.col('product')
)
```
or getting the order of `sort_by` / `cumsum` / `over` wrong (all 6 permutations work, but only one gives the correct result!).

With a `sort_by` parameter, I could write the entirely natural 
```
sales.select(
    pl.col('amount').cumsum(sort_by='time').over('product').alias('cumAmount'), 
    pl.col('time'),
    pl.col('amount'),
    pl.col('product')
)
```

Note that this is similar to what one would write, e.g., in PostgreSQL:
```
SELECT
sum(amount) OVER (
    PARTITION BY product
    ORDER BY time
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
) as cumProfit,
time,
amount,
product
FROM sales
```

Maybe it's even better to get even closer to SQL syntax and move the new parameter into the `.over` (and allow an empty columns specification). This way you'd only have to add the extra parameter into a single signature, you'd have happier SQL migrants, and you could add future extra parameters like `ascending` or `range` in the same place. 

PS:

Like in the simple example, the advanced example has a dataframe-sort solution
```
sales.sort('time').select(   
 
    pl.col('amount').cumsum().over('product').alias('cumAmount'), 
    pl.col('time'),
    pl.col('amount'),
    pl.col('product')
)
```
but besides suffering from the previously mentioned problems of reordering rows, it's
- less natural and doesn't allow different sortings for different windows/over adjunctions
- less performant because sorting groups individually is faster than sorting the entire dataframe (and even if it wasn't in this use case, this pattern of sorting a dataframe before group by is an antipattern because it will always require special  case-wise optimization in the query planner to make it fast in all sorts of scenarios).

**Comment by cmdlineluser** [comment]
May be relevant:

- #8662

Which is asking for:

```python
pl.col('amount').cum_sum().over('product', order_by='time').alias('cumAmount')
```

**Comment by soerenwolfers** [comment]
You are right. I think it's the same ask but I think I have extra arguments for why it can be useful, so I'll copy my arguments to there and close this post
