### ISSUE TITLE
No module named 'connectorx.connectorx_python'

### ISSUE THREAD

**Issue by nick-youngblut** [pola-rs/polars#14138]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Using polars to read from a postgres db, as described at https://docs.pola.rs/user-guide/io/database/ results in the following error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/connectorx/__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
ModuleNotFoundError: No module named 'connectorx.connectorx_python'
```

It appears that this is due to https://github.com/sfu-db/connector-x/issues/186, and using an ARM chip.

It would be helpful to at least include a warning about this compatibility issue at https://docs.pola.rs/user-guide/io/database/#connectorx. 

### Issue description

Dependency issue with connectorx, apparently just for ARM chips.

### Expected behavior

As described in https://docs.pola.rs/user-guide/io/database/#connectorx, one just "simply" needs to run:

```shell
$ pip install connectorx
```

### Installed versions

<details>

```
requests==2.31.0
python-dotenv==1.0.0
sqlalchemy==2.0.25
psycopg2==2.9.9
polars==0.20.6
gspread==6.0.0
```

</details>

**Comment by deanm0000** [comment]
I'll update the docs tomorrow (well I'll put a PR in, can't control how quickly it'll be merged).

**Comment by alexander-beedie** [comment]
Looking at their build targets they _do_ actually support `aarch64`, specifically:

`aarch64-unknown-linux-gnu`
`aarch64-apple-darwin` (aka: apple silicon)

Are you on a Windows ARM64 variant?

**Comment by nick-youngblut** [comment]
> It doesn't look like you're on Windows ARM64 variant, so can you provide more details?

I'm using an M2 macbook. The Dockerfile that I'm using for my VS Code devcontainer:

```
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /my_project

# Install system dependencies
# Install system dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    libpq-dev \
    procps \
    curl \
    less \
    tree \
    screen \
    vim \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt file into the container
COPY requirements.txt ./

# Copy the package files into the container
COPY ./my_project ./

# Install any needed Python packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
```

My requirements.txt is the same as what I listed above:

```
requests==2.31.0
python-dotenv==1.0.0
sqlalchemy==2.0.25
psycopg2==2.9.9
polars==0.20.6
gspread==6.0.0
```

**Comment by stinodego** [comment]
This is an issue with the connectorx package, not with Polars. While Polars does build a Linux aarch wheel, connectorx does not.

You can either build connector-x from source, or use a different database connector such as ADBC.
