### ISSUE TITLE
`ColumnNotFoundError` when running lazy query but not eager query

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#14141]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Unfortunately, the following has been my experience with developing complex queries in Polars:

1. I develop and run a very complex query in eager mode, and it works as expected.
2. I attempt to run the query in lazy mode, and it throws a weird error that doesn't make sense.

This issue captures the error that I encountered when trying to run my most recent complex query in lazy mode. (I didn't create an issue the last time a complex query in lazy mode failed to run.) I don't have time right now to boil my complex query (on proprietary data) into a MWE. When I run this query in lazy mode, it results in a spurious `ColumnNotFoundError`. However, that column definitely should be there---I have triple checked for typos in the column name, and the query works as expected in eager mode.

One thing to note is that `intermediate_lazy_data_frame.columns` does not show the column that is later not found when I `collect` the query, but `intermediate_lazy_data_frame.collect().columns` _does_ show that column (where `intermediate_lazy_data_frame` is the lazy dataframe one or two steps before the operation that causes the `ColumnNotFoundError`).

In case this is useful, there error occurs during an `agg`.

Here is the error that I am getting:

```python
File c:\Users\...\projects\...\venv\Lib\site-packages\polars\lazyframe\frame.py:1940, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1937 if background:
   1938     return InProcessQuery(ldf.collect_concurrently())
-> 1940 return wrap_df(ldf.collect())

ColumnNotFoundError: my_column_name
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

**Comment by cmdlineluser** [comment]
This behaviour has popped up in a few different issues recently.

- https://github.com/pola-rs/polars/issues/12917

You can try disablng projection_pushdown to see if it is the same "cause" of the problem.

```python
.collect(projection_pushdown=False)
```

**Comment by CameronBieganek** [comment]
Thanks for the suggestion. Unfortunately, when I try `.collect(projection_pushdown=False)`, I still get the same error.

**Comment by cmdlineluser** [comment]
D'oh.

You can try the other 5 which may help isolate it down to a particular area:

```
    predicate_pushdown
        Do predicate pushdown optimization.
    projection_pushdown
        Do projection pushdown optimization.
    simplify_expression
        Run simplify expressions optimization.
    slice_pushdown
        Slice pushdown optimization.
    comm_subplan_elim
        Will try to cache branching subplans that occur on self-joins or unions.
    comm_subexpr_elim
        Common subexpressions will be cached and reused.
    no_optimization
        Turn off (certain) optimizations.
```

I think `no_optimization=True` disables them all.

**Comment by deanm0000** [comment]
There's nothing to do without a MWE. There's a known issue that unnest on a struct can cause that in certain instances. If you can come up with a MWE then please open an issue with it.
