### ISSUE TITLE
Allow df[boolean_mask] and series[boolean_mask] as an alternative to filter()

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#14153]
### Description

Even though filter() is the recommended approach, this would allow functions that do indexing with boolean masks to support both polars and NumPy without having to explicitly handle both cases.

**Comment by cmdlineluser** [comment]
It used to work that way:

- https://github.com/pola-rs/polars/pull/4342

**Comment by stinodego** [comment]
We want you to use `filter`, as it's much more readable and explicit.
