### ISSUE TITLE
Implements list.gather_every

### ISSUE THREAD

**Issue by Dmitry-k42** [pola-rs/polars#14177]
### Description

I need to get every second item of the list. Example:
```
df = pl.DataFrame({
    'col': [
        ['a', 'b', 'c'],
        ['d', 'e', 'f'],
    ]
})
```
Now the only way I see is using `apply` method which is discouraged to use due to performance issues:
```df['col'].apply(lambda x: x[::2])```
Also I see good fit method `slice` but unfortunately it doesn't have `step` parameter. If it would have it I can write:
```df['col'].list.slice(0, step=2)```
I find it much more readable and elegant solution than existing one. Backward compatibility is respected as well.
Please consider the proposal, thanks!

**Comment by cmdlineluser** [comment]
I believe you're asking for a dedicated `.list.gather_every()`

Another workaround is `list.eval` to access [`Expr.gather_every()`](https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.gather_every.html#polars.Expr.gather_every)

```python
df.with_columns(
   pl.col("col").list.eval(pl.element().gather_every(2))
)

# shape: (2, 1)
# ┌────────────┐
# │ col        │
# │ ---        │
# │ list[str]  │
# ╞════════════╡
# │ ["a", "c"] │
# │ ["d", "f"] │
# └────────────┘
```
