### ISSUE TITLE
Native string formatting support

### ISSUE THREAD

**Issue by jakob-keller** [pola-rs/polars#14179]
### Description

Are there any plans to support basic string formatting without resorting to `map_elements`? I am thinking of at least a subset of functionality provided by Python's [`format()` built-in function](https://docs.python.org/3/library/functions.html#format).

One obvious use case is to apply a thousands separator:

```python
import polars as pl

pl.DataFrame(
    {"number": range(995, 1005)},
).with_columns(
    formatted=pl.col("number").map_elements(lambda x: format(x, ","), pl.String),
)
shape: (10, 2)
┌────────┬───────────┐
│ number ┆ formatted │
│ ---    ┆ ---       │
│ i64    ┆ str       │
╞════════╪═══════════╡
│ 995    ┆ 995       │
│ 996    ┆ 996       │
│ 997    ┆ 997       │
│ 998    ┆ 998       │
│ 999    ┆ 999       │
│ 1000   ┆ 1,000     │
│ 1001   ┆ 1,001     │
│ 1002   ┆ 1,002     │
│ 1003   ┆ 1,003     │
│ 1004   ┆ 1,004     │
└────────┴───────────┘
```

As far as I understand, [`polars.Config.set_thousands_separator`](https://docs.pola.rs/py-polars/html/reference/api/polars.Config.set_thousands_separator.html) only applies in the context of "printing".

Bonus: This functionality would ideally also be available in `pl.format()`, e.g. by moving towards the Python "f-strings" syntax.

**Comment by mkleinbort-ic** [comment]
Yes, this would be a good feature.

The issue is mainly tracked here: https://github.com/pola-rs/polars/issues/7133

**Comment by mullimanko** [comment]
Thank you for your answer @mkleinbort-ic. Would you like to post your code on [this stackoverflow question](https://stackoverflow.com/questions/78633199/how-to-include-thousand-separator-in-numbers-in-polars-output)? If not, would you please allow me that I post it there?

It could look like this:  

You can use [`map_elements`][1], if you would like to set the thousands separator only on specific columns or if `pl.Config` doesn't bring the desired result:

    import polars as pl
    
    df = pl.DataFrame(
        {
            "A": [1_000, 1_000_000],
            "B": [1_000, 1_000_000],
        },
    )
    
    df.with_columns(pl.col("B").map_elements(lambda x: f"{x:,}", pl.String))  
    
    # Results in (note that the data type is then String):
    # ┌────────────┬───────────────┐
    # │ A          ┆ B             │
    # │ ---        ┆ ---           │
    # │ i64        ┆ str           │
    # ╞════════════╪═══════════════╡
    # │ 1000       ┆ 1,000         │
    # │ 1000000    ┆ 1,000,000     │
    # └────────────┴───────────────┘

Source: [f-string formatting code][2] by mkleinbort-ic is licensed under [MIT License][3]


  [1]: https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.map_elements.html#polars.Expr.map_elements
  [2]: https://github.com/pola-rs/polars/issues/14179#issuecomment-1921311838
  [3]: https://github.com/pola-rs/polars/blob/main/LICENSE
