### ISSUE TITLE
read_excel plus "calamine" engine issues when loading Excel data with some empty values

### ISSUE THREAD

**Issue by adrivn** [pola-rs/polars#14174]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Load the attached Excel data sample file, containing sparse data.
```python
import polars as pl

pl.read_excel(
    "sample_data_blanks_instead_of_nulls.xlsx",
    engine="calamine",
)
```

### Log output

```shell
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[17], line 1
----> 1 pl.read_excel(
      2     "C:/Users/adrivn/Desktop/Unorganized Stuff/sample_data_blanks_instead_of_nulls.xlsx",
      3     engine="calamine",
      4 )

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\utils\deprecation.py:133, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    128 @wraps(function)
    129 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    130     _rename_keyword_argument(
    131         old_name, new_name, kwargs, function.__name__, version
    132     )
--> 133     return function(*args, **kwargs)

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\io\spreadsheet\functions.py:249, in read_excel(source, sheet_id, sheet_name, engine, engine_options, read_csv_options, schema_overrides, raise_if_empty)
    246     msg = f"cannot specify `read_csv_options` when engine={engine!r}"
    247     raise ValueError(msg)
--> 249 return _read_spreadsheet(
    250     sheet_id,
    251     sheet_name,
    252     source=source,
    253     engine=engine,
    254     engine_options=engine_options,
    255     read_csv_options=read_csv_options,
    256     schema_overrides=schema_overrides,
    257     raise_if_empty=raise_if_empty,
    258 )

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\io\spreadsheet\functions.py:428, in _read_spreadsheet(sheet_id, sheet_name, source, engine, engine_options, read_csv_options, schema_overrides, raise_if_empty)
    425 try:
    426     # parse data from the indicated sheet(s)
    427     sheet_names, return_multi = _get_sheet_names(sheet_id, sheet_name, worksheets)
--> 428     parsed_sheets = {
    429         name: reader_fn(
    430             parser=parser,
    431             sheet_name=name,
    432             read_csv_options=read_csv_options,
    433             schema_overrides=schema_overrides,
    434             raise_if_empty=raise_if_empty,
    435         )
    436         for name in sheet_names
    437     }
    438 finally:
    439     if hasattr(parser, "close"):

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\io\spreadsheet\functions.py:429, in <dictcomp>(.0)
    425 try:
    426     # parse data from the indicated sheet(s)
    427     sheet_names, return_multi = _get_sheet_names(sheet_id, sheet_name, worksheets)
    428     parsed_sheets = {
--> 429         name: reader_fn(
    430             parser=parser,
    431             sheet_name=name,
    432             read_csv_options=read_csv_options,
    433             schema_overrides=schema_overrides,
    434             raise_if_empty=raise_if_empty,
    435         )
    436         for name in sheet_names
    437     }
    438 finally:
    439     if hasattr(parser, "close"):

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\io\spreadsheet\functions.py:784, in _read_spreadsheet_calamine(parser, sheet_name, read_csv_options, schema_overrides, raise_if_empty)
    781         type_checks.append(check_cast)
    783 if type_checks:
--> 784     apply_downcast = df.select([d[0] for d in type_checks]).row(0)
    786     # do a similar check for datetime columns that have only 00:00:00 times.
    787     if downcast := [
    788         cast for apply, (_, cast) in zip(apply_downcast, type_checks) if apply
    789     ]:

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\dataframe\frame.py:8144, in DataFrame.select(self, *exprs, **named_exprs)
   8044 def select(
   8045     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   8046 ) -> DataFrame:
   8047     """
   8048     Select columns from this DataFrame.
   8049 
   (...)
   8142     └───────────┘
   8143     """
-> 8144     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)

File c:\Users\adrivn\envs\main\Lib\site-packages\polars\lazyframe\frame.py:1940, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1937 if background:
   1938     return InProcessQuery(ldf.collect_concurrently())
-> 1940 return wrap_df(ldf.collect())

ComputeError: Series length 91 doesn't match the DataFrame height of 287
```

### Issue description

[sample_data_blanks_instead_of_nulls.xlsx](https://github.com/pola-rs/polars/files/14123273/sample_data_blanks_instead_of_nulls.xlsx)
[sample_data_nulls.xlsx](https://github.com/pola-rs/polars/files/14123274/sample_data_nulls.xlsx)

The attached Excel spreadsheets contain, for simplicity of reproduction, a total of 12 columns (A:L) with a row count of 287 (288 if you include header). One file has null/empty values with the "NULL" string placeholder, the other does not (empty/blank cell value instead). The data has integer columns, strings, float/double/numeric, and dates in timestamp format. Some of the columns have every row populated, some do not (55/287, 38/287, etc.)

Upon loading the data using `read_excel` with the new `engine=calamine` integration, it results in a `ComputeError: Series lenght <# of rows without empty values> doesn't match the DataFrame height of <# total rows in the Excel spreadsheet>`

I have tested this same behavior using the `openpyxl` and default `xlsx_to_csv` engines and the data can and is read correctly.

### Expected behavior

The data should be loaded correctly into memory as a DataFrame, and the datatypes inferred as it happens when using the `openpyxl` engine.

<small>shape: (287, 12)</small><table border="1" class="dataframe"><thead><tr><th>ID</th><th>ALMOST_INT</th><th>NEARLY_STR</th><th>FULL_STR</th><th>FEW_STR</th><th>FEWER_STR</th><th>SINGLE_STR</th><th>ALMOST_FLOAT</th><th>HALF_INT</th><th>HALF_DATE</th><th>FEW_INT</th><th>FEW_DATE</th></tr><tr><td>i64</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>null</td><td>f64</td><td>i64</td><td>datetime[μs]</td><td>i64</td><td>datetime[μs]</td></tr></thead><tbody><tr><td>1</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>&quot;CCC&quot;</td><td>null</td><td>null</td><td>null</td><td>41</td><td>2024-02-01 05:20:37.525</td><td>null</td><td>null</td></tr><tr><td>2</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>39.6</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>3</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>55.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>4</td><td>1</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>44.4</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>5</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>19.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>6</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>&quot;CCC&quot;</td><td>&quot;DDD&quot;</td><td>null</td><td>67.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>7</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>70.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>8</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>56.4</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>9</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>55.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>10</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>&quot;CCC&quot;</td><td>null</td><td>null</td><td>50.4</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>11</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>&quot;CCC&quot;</td><td>&quot;DDD&quot;</td><td>null</td><td>3.6</td><td>44</td><td>2024-02-01 05:20:37.525</td><td>null</td><td>null</td></tr><tr><td>12</td><td>null</td><td>null</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>39.6</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>276</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>31.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>277</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>40.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>278</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>31.2</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>279</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>33.6</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>280</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>52.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>281</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>42.0</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>282</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>18.0</td><td>25</td><td>2024-02-01 05:20:37.525</td><td>null</td><td>null</td></tr><tr><td>283</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>26.4</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>284</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>52.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>285</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>&quot;CCC&quot;</td><td>&quot;DDD&quot;</td><td>null</td><td>10.8</td><td>28</td><td>2024-02-01 05:20:37.525</td><td>null</td><td>null</td></tr><tr><td>286</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>40.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>287</td><td>1</td><td>&quot;AAA&quot;</td><td>&quot;BBB&quot;</td><td>null</td><td>null</td><td>null</td><td>4.8</td><td>null</td><td>null</td><td>null</td><td>null</td></tr></tbody></table></div>

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           2.0.23
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9

```

</details>

**Comment by deanm0000** [comment]
That engine uses the package fastexcel. I think https://github.com/ToucanToco/fastexcel/pull/164 will fix it.

**Comment by deanm0000** [comment]
If, after they get their next version out with that merged, it still doesn't work then give it a try directly with their library. If that doesn't work post an issue on their board. If it works directly with them but not polars then post again here.
