### ISSUE TITLE
read_database function truncates seconds to 6 decimals, unable to achieve nanosecond precision

### ISSUE THREAD

**Issue by gera0220** [pola-rs/polars#14188]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```sql
CREATE TABLE dbo.test(
	Id INT IDENTITY(1,1),
	Name VARCHAR(MAX),
	SomeDate DATETIME2(7) DEFAULT GETDATE()
)

INSERT INTO dbo.test(Name)
VALUES('TestDate')
```

```python
query = "SELECT * FROM dbo.test"
conn = pyodbc.connect(f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}')
cursor = conn.cursor()
pl.read_database(query , cursor, schema_overrides = {"ModifiedAt": pl.Datetime(time_unit='ns'), "SomeDate ": pl.Datetime(time_unit='ns')})
```

### Log output

shape: (1, 3)
┌─────┬──────┬────────────────────────────┐
│ Id  ┆ Name ┆ DateOpen                   │
│ --- ┆ ---  ┆ ---                        │
│ i64 ┆ str  ┆ datetime[ns]               │
╞═════╪══════╪════════════════════════════╡
│ 1   ┆ Test ┆ 2024-02-01 14:21:38.646666 │
└─────┴──────┴────────────────────────────┘

### Issue description

Decimales get truncated when use the pl.read_database even when I specify that it should receive nanoseconds, but when I change time_unit to 'us' or 'ms' it does works. 

### Expected behavior

Get 9 decimales. If there are not enough decimals in the source add 0s.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-10-10.0.22621-SP0
Python:               3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
Does it work if you query through the cursor directly and not through `read_database`?

**Comment by gera0220** [comment]
Mmm apparently no. I get:

``` python
[(1, 'TestDate', datetime.datetime(2024, 2, 1, 18, 15, 17, 923333))] 
```

**Comment by mcrumiller** [comment]
I see that you're using the `DATETIME2` data type which indicates that you're using MS SQL server. The [`DATETIME2`](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16) documentation reveals that the precision limit is 100ns. You will not be able to get nanosecond precision using `DATETIME2`, or any MSSQL temporal datatype for that matter. If you really need more precision, you'll have to use an additional numeric column.

The issue here is not with polars.

**Comment by deanm0000** [comment]
@alexander-beedie is there anything to do here? Seems like a close but I'll defer to you.

**Comment by gera0220** [comment]
Sorry, maybe I wasn't clear enough or maybe I'm not totally understanding haha. My datetime value in my sql server database is, let's say 2024-01-01 10:50:05.1234567. When I try to read it with polars I only get 10:50:05.123456, so when I tried to get nanoseconds I was really trying to get all my record value

**Comment by gera0220** [comment]
But now that I tried other ways. You're totally right. There's no issue with Polars. Thank you all!

**Comment by mcrumiller** [comment]
I am not getting this issue.

### SQL code
```sql
CREATE TABLE test_date (
    my_date DATETIME2
);
INSERT INTO test_date VALUES ('2024-01-01 10:50:05.1234567');
SELECT * FROM test_date
```
_ | my_date
--|-------
1 | 2024-01-01 10:50:05.1234567

### polars code

```python
import polars as pl
conn = "..." # get uri
print(pl.read_database_uri("SELECT * FROM my_date", conn))
```
```
shape: (1, 1)
┌───────────────────────────────┐
│ my_date                       │
│ ---                           │
│ datetime[ns]                  │
╞═══════════════════════════════╡
│ 2024-01-01 10:50:05.123456700 │
└───────────────────────────────┘
```

**Comment by gera0220** [comment]
You're right! Apparently there's no issue using `read_database_uri`. The problem only happens with `read_database`

**Comment by mcrumiller** [comment]
I get the same result regardless of whether I use `read_database` (which FYI dispatches to `read_database_uri` when a connection string is supplied) and `read_database_uri`.

**Comment by gera0220** [comment]
Well, to be honest the reason why I've been avoiding the `read_database_uri` is because the password contains a "/" and gives me issues because of "invalid port". I've tried with `urlib.parse.quote_plus`/`urlib.parse.quote` as docs mention, but I think only contemplate the "?" sign. Not sure. Also, I know this is not the issue reason haha

**Comment by mcrumiller** [comment]
You should be able to just use `quote` as follows, it applies to many special characters, not just `?`:

```python
from urllib.parse import quote

pw = quote(pw)
```

**Comment by gera0220** [comment]
You're totally right. My problem is another one. Thank you!

**Comment by deanm0000** [comment]
I think the issue is resolved if not let me know

**Comment by alexander-beedie** [comment]
@gera0220: I'd _strongly_ suggest using [arrow_odbc](https://github.com/pacman82/arrow-odbc) here instead of `pyodbc` (we support both). You'll get much, _much_ better performance loading into Polars, and there's a chance it may better-preserve the available precision. 

`pyodbc` is more limited as it returns data to Python first, and only _then_ can we load it into a DataFrame. Python datetimes are limited to microseconds, hence you'll always lose any additional precision. On the other hand, `arrow_odbc` constructs Arrow data directly, _without_ going through Python, and we can zero-copy this into the DataFrame for a large speedup.

**Comment by gera0220** [comment]
Oh! Perfect. Thanks @alexander-beedie. I'll check it out
