### ISSUE TITLE
Rust user guide?

### ISSUE THREAD

**Issue by lumost** [pola-rs/polars#1420]
Great library! I'm working with the Rust interface directly and noticed that the helpful user guide only applies to python. Would it be feasible to have the user guide available in both rust and python?

**Comment by ritchie46** [comment]
Almost everything written in the user guide is an 1 in 1 mapping to the rust lazy API. So you could read the python examples as pseudocode.😉

The rust docs has some Rust specific content. And have you checked to cookbooks? 

https://docs.rs/polars/0.16.0/polars/#cookbooks
