### ISSUE TITLE
polars hangs on loading parquet files within processes from multiprocessing.Process

### ISSUE THREAD

**Issue by tchaton** [pola-rs/polars#14219]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I am using `from multiprocessing import Process` and spawning processes. It seems it hangs on reading the file.

It seems to happen when I do the following in the main process before starting the processes:

```python
        #     import polars as pol
        #     df = pol.scan_parquet(path)
        #     num_rows = df.select(pol.len()).collect().item()
        #     df.clear()
        #     return num_rows
```

I don't have a reproducible example just yet. 

### Log output

```shell
It just hangs
```

### Issue description

```python

def load(self, item):
	import polars as pol
	df = pol.read_parquet(item.filepath, row_index_offset=item.start, n_rows=item.end - item.start, parallel="row_groups")
	
	print(df)
	
	if self.to_pandas:
	    df.to_pandas()
	
	return df
```

### Expected behavior

It doesn't hang

### Installed versions

<details>

```
polars                    0.20.6
```

</details>

**Comment by cmdlineluser** [comment]
Have you seen the multiprocessing guidelines re: `fork/spawn`? 

> Using fork as the method, instead of spawn, will cause a dead lock.

- https://docs.pola.rs/user-guide/misc/multiprocessing/

**Comment by ritchie46** [comment]
As @cmdlineluser says this is written in our docs. This a bug in multiprocessing as it assumes no living mutexes in processes. 

I would advice against using multiprocessing for this. Polars already paralellizes the work for you. Trying to parallelize more would hurt Polars' performance.
