### ISSUE TITLE
indexing bool column gives NotImplemented error

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#1422]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

3.7

#### What operating system are you using polars on?

MAC OSX 11.2.3

#### Describe your bug.

When indexing a dataframe, it returns a NotImplementedError whenever the column is a boolean. When indexing a column with integers, it works fine.

#### What are the steps to reproduce the behavior?

```
df = pl.DataFrame(
        {
            "A": ["apple"] * 10,
            "true": [True] * 10,
            "false": [False] * 10
        }
    )

```
df["A"][0]  gives
```
'apple'
```
df["true"][0] gives
```
NotImplemented
```
df["false"][0] gives
```
NotImplemented
```

**Comment by ritchie46** [comment]
Just released. 🙈 Will fix it.
