### ISSUE TITLE
Missing data when using read_csv on large file

### ISSUE THREAD

**Issue by wsyxbcl** [pola-rs/polars#14235]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
taxon_file = "path/to/NameUsage.tsv"
df_taxon = pl.read_csv(taxon_file, separator='\t', infer_schema_length=20000)
```

### Issue description

The `NameUsage.tsv` used for test can be downloaded via [this link](https://api.checklistbank.org/dataset/286246/export.zip?extended=true&format=ColDP). By passing it to read_csv, a (4826119, 70) shaped dataframe is generated  with no error, while the original tsv file has 5052356 rows.

### Expected behavior

The size should be consistent

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Linux-6.7.1-arch1-1-x86_64-with-glibc2.38
Python:               3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              <not installed>
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.44
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9


```

</details>

**Comment by taki-mekhalfa** [comment]
There is an issue with quotations (`"`)

At line `83285`:
`ttp://www.nhm.ac.uk/research-curation/research/projects/chalcidoids/database/detail.dsml?VALAUTHOR=Statz&VALGENUS=Pteromalus&HOMCODE=0&VALDATE=1938&VALSPECIES=pulchellus&ValidAuthBracket=false              "Tertiary "yellow-brown slate"."`

If you want to embed an `"` inside another pair, you need to escape it.

If you don't intend to use `"` as a quotation char (to enable for multiline support), just pass `quote_char=None`.

PS: your file seems to have 5_073_152 if you ignore quotes

**Comment by ritchie46** [comment]
Thank you @taki-mekhalfa. That means the csv-file is ill defined. Or it should use a different quotation character.

**Comment by taki-mekhalfa** [comment]
> Thank you @taki-mekhalfa. That means the csv-file is ill defined. Or it should use a different quotation character.

Maybe it's good to report this kind of errors when possible?

**Comment by wsyxbcl** [comment]
Oops, thank you all for the help.

An error or warning would be useful in such cases.
