### ISSUE TITLE
automate changelog creation

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#1423]

**Comment by tiphaineruy** [comment]
I've looked a bit into that.
Convention seems to change commit style to using: https://www.conventionalcommits.org/en/v1.0.0/#summary
then several tools exist that take care of the automatic generation of the changelog.

Rust world seems to already have a good contender:
https://github.com/orhun/git-cliff

I've tried to make it work on polar with limited success:
( different tag convention:  v0.x , 0.x, py-polars-v0.x ... , and commits with different conventions too
missing tags : 0.0.10-> 0.0.12 -> 0.0.16 when you list > git tag)  

do you still want to separate the changelog of polars and py-polars  ?

Working setup:

```
cargo install git-cliff
git cliff --init

in  created cliff.toml file, set:

header = """
# Changelog Polars

The Python bindings of `polars` have their own changelog.\n
"""

and

conventional_commits = false
```

then you can just

> git tag 0.17.0

and then run 

> git cliff -t 0.17.0 -p CHANGELOG.md -l 


this will prepend the changelog with

```
## [0.17.0] - 2021-09-25

### Bug Fixes

- Fix memcpy of multiple chunks; closes 1396

- Fix invalid ReplaceDropNulls optimization

- Fix apply with list output type

- Fix rolling_mean on integers: closes #1411

- Fix mac universal wheel build

- Fix and test boolean Series indexing
```

Although this is a working solution, i'm not sure it is ideal 
-> doesn't really separate py-polars and polars-core
-> without: https://www.conventionalcommits.org/en/v1.0.0/#summary the messages lack context

Food for thoughts

**Comment by jorgecarleitao** [comment]
Some background on how I have been doing it in arrow2 using this [configuration](https://github.com/jorgecarleitao/arrow2/blob/main/.github_changelog_generator), [this process](https://raw.githubusercontent.com/jorgecarleitao/arrow2/main/DEVELOPMENT.md), and then do small adaptations on [github releases](https://github.com/jorgecarleitao/arrow2/releases).

The big plus for me with this process is that it is not tied to commits, which means that we can change the issues, PRs and labels pre-release to fit well in the changelog.

**Comment by ritchie46** [comment]
Thanks for your ideas. In any case, we will need to work a bit more standardized with regards to commits and PRs. And I think the separate changelog is not sacred. It turns out I don't keep it up to date very well, so a single up to date changelog is better than none IMO.

**Comment by ritchie46** [comment]
The short success with github-changelog-generator didn't last. I keep getting into rate-limit issues (even with a auth token):

```
Octokit::Forbidden: GET https://api.github.com/repos/pola-rs/polars/issues/181/events?per_page=100: 403 - You have exceeded a secondary rate limit. Please wait a few minutes before you try again. // See: https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits
Exceeded retry limit
```

related issue: https://github.com/github-changelog-generator/github-changelog-generator/issues/656

**Comment by astrojuanlu** [comment]
Is this the reason why there haven't been any new entries in the changelog in the past months? https://github.com/pola-rs/polars/blob/1f0ccec/py-polars/CHANGELOG.md

**Comment by ritchie46** [comment]
Yes, I wasn't able to automate it. The rate limit issues in github-changelog-generator.

And it was too much of a burden on me. Polars is very rapid moving and I spent a lot of time on it and maintaining the changelog took a lot of my time. If we can automate it in CI with at least some commit differences on that are generated on a polars tag, we are already in a better state.

**Comment by cnpryer** [comment]
Resurfacing this, has anyone tried this yet? https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
