### ISSUE TITLE
`infer_schema_length` description is uncomplete

### ISSUE THREAD

**Issue by FBruzzesi** [pola-rs/polars#14232]
### Description

Both in [DataFrame](https://docs.pola.rs/py-polars/html/reference/dataframe/index.html) and [LazyFrame](https://docs.pola.rs/py-polars/html/reference/lazyframe/index.html), `infer_schema_length` parameter is described with the wrong default (`None` instead of `N_INFER_DEFAULT `- which is 100), and the behavior for when it is set to `None` is not explained.

**Comment by MarcNuebel** [comment]
In [scan_ndjson](https://docs.pola.rs/py-polars/html/reference/api/polars.scan_ndjson.html), [read_json](https://docs.pola.rs/docs/python/dev/reference/api/polars.read_json.html) the behavior of `None` is also not described.

And in [str.json_decode](https://docs.pola.rs/py-polars/html/reference/series/api/polars.Series.str.json_decode.html) it doesn't use `N_INFER_DEFAULT`, but `100` is hard-coded.

For `LazyFrame`, the `_scan_ndjson` method even has `None` as default, different to everywhere else

**Comment by FBruzzesi** [comment]
Hey @MarcNuebel, thanks for pointing these out.

I had opened a [PR](https://github.com/pola-rs/polars/pull/14233/files) and had already addressed `scan_ndjson` and `read_json`.

I missed the other two cases you reported though:

- Not sure if `str.json_decode` is intended to be different
- `_scan_ndjson` would be a breaking change, I will wait for maintainers feedback
