### ISSUE TITLE
Code examples disappearing from official docs, even though they appear when building locally

### ISSUE THREAD

**Issue by valorien** [pola-rs/polars#14250]
### Description

The [data structures](https://docs.pola.rs/user-guide/concepts/data-structures/) section of the docs includes code examples showing how to create both `Series` and `DataFrame` objects.
When building the docs **locally**, both code examples are shown just fine:

### Local docs build

![image](https://github.com/pola-rs/polars/assets/3483790/61995b07-df23-4e64-a847-bed54a359e85)

![image](https://github.com/pola-rs/polars/assets/3483790/5f9007c9-7fec-4804-b7b7-baf7be5e69f0)

**However**, on the official web version of the docs, these same code examples are missing.
(Tested using several browsers, both on a PC and a smartphone):

### Official docs (web)

![image](https://github.com/pola-rs/polars/assets/3483790/5f89c84d-4264-4b57-8831-eb2bc4968c27)

![image](https://github.com/pola-rs/polars/assets/3483790/64713396-124a-4c88-80a9-84cbf13515c3)

Is it possible that the process of publishing the docs to the web corrupts them somehow?

### Link

https://docs.pola.rs/user-guide/concepts/data-structures/

**Comment by ritchie46** [comment]
When were those examples added? The docs may not been published yet.

**Comment by valorien** [comment]
Seems like you're right. They were added 3 days ago with https://github.com/pola-rs/polars/pull/14146.
I guess the change hasn't been published yet.
