### ISSUE TITLE
polars series to mlx array

### ISSUE THREAD

**Issue by johnros** [pola-rs/polars#14252]
### Description

It could be useful to have a series method to convert to mlx arrays. 
Currently possible with 
```
# %pip install mlx
import mlx.core as mx
mx.array(s.to_numpy())
```

**Comment by alexander-beedie** [comment]
If I'm looking at the correct package, `mlx`[^1] is Apple Silicon only, along the same lines as numpy? While it looks like a great package (and I'm on Apple Silicon myself) I can't see us adding a dedicated method for that conversion given how straightforward it is to initialise from our existing `numpy` export, and the constrained platform support 😅 

[^1]: https://pypi.org/project/mlx/

**Comment by johnros** [comment]
Very well. That makes sense. 
Just FYI- for those doing linear algebra on Apple Silicone, mlx is indeed insanely(!) fast.

**Comment by alexander-beedie** [comment]
FYI: we did investigate the buffer protocol, but there appear to be some potential side-effects on numpy interop that aren't fully explored yet; I think we'll close this as "not planned" for now. If the `mlx` folks think adding `__array__` support is reasonable that would be another clean solution.
