### ISSUE TITLE
Split `replace` functionality into two separate functions

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#14302]
### Description

imo the `replace` function got a little overloaded and complicated.
It feels like it is doing two similar but different things.
I propose to split it into two functions. I see the two functions as follows:

### 1. `replace` (KEEP type, change some/all values)
- allways keeps the original data type
- replace usually some (or all) values with some other value
- examples: `col('x').`
  - `replace(-1, 0)` 
  - `replace([1, 2, 3], 0)`
  - `replace({-1: 0, 999999: 1})`
  - `replace(['DE', 'FR', 'IT'], 'EU')`

### 2. `map` (CHANGE type, change ALL values)
- (usually) changes the data type
- maps ALL values to some other value
- examples: (`map` might be free again in "1.0" or use another name?)
  - `map({"N/A": 0, "__": 0})` str -> int (default: null)
  - `map({1: "A", 2: "B", 3: "C"}, default="Z")` int -> str
  - `map([123, 456], ["US", "UK"], default=pl.col("country"))` int -> str (default: country column)

## Resons for the split
- `replace` is becoming increasingly consufing expecially with the `return_dtype` parameter. It is hard to just keep the current type if you dont know the current type in advance.
- having clear and separate functions makes it easier to understand and use
- polars/pyspark also have `replace` to change a portion of values while keeping the type and `map` to transform all values and (optionally) change the type.

**Comment by stinodego** [comment]
Yes, I also feel we must do something here. Not sure about splitting the function though.

**Comment by deanm0000** [comment]
I like the functionality but, if it were up to me, I'd rather see it as a parameter option than a separate function

**Comment by JulianCologne** [comment]
Like the split into two functions.
However, I would recommend changing the naming of `replace_all` which is very unintuive! #16557 

Reasons:
- the core idea of replacement is to take something away and put in something equivalent BUT what `replace_all` actually does is a mapping or transformation which has totally different meaning!
- `replace` is generally know as changing some values and keeping the type
- `replace_all` sounds like `replace` is only changing the first occurance and `replace_all` changes all
- ((In string replacement context some languages acutally have `replace` & `replace_all` doing almost the same which adds confusion [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) / [Java](https://www.w3schools.com/java/ref_string_replaceall.asp)))

**Comment by stinodego** [comment]
I share those concerns, but I don't think there's a better name.

`map` in Polars is linked to mapping with UDFs. `map` = slow, try to avoid.

The two functions are very similar so having both share the `replace` prefix is good for discoverability.

If you have the golden suggestion I'm open for it.

**Comment by JulianCologne** [comment]
I thought that maybe since `map` is long deprecated there is a chance to "reuse" it again for V1.0 🤔 

haha yeah naming things is somehow the hardest part in programming 😄

**Comment by cmdlineluser** [comment]
For alternative suffix ideas, these came to mind:

- `replace_by` - *"replace by mapping old -> new"*
- `replace_with` - *"replace with the mapping of old -> new"*

Not sure if they are an improvement over `_all` - tricky one to name.

**Comment by orlp** [comment]
@JulianCologne For the moment the best thing we came up with is

- `replace_some`, keeps the same dtype,
- `replace_all`, must provide a default value, can change the dtype.

If someone has a better idea we're all ears.

**Comment by stinodego** [comment]
It will become `replace` and `replace_strict`.

**Comment by deanm0000** [comment]
Which one is which? I can see `strict` referring to keeping the same dtype or to requiring a default value be entered. From a backward compatibility perspective, I guess `replace` should be the one that doesn't require extra inputs and `replace_strict` would be the one to require extra inputs. I'm not trying to bike shed, I'm just curious.

**Comment by orlp** [comment]
@deanm0000 `replace` requires the same `dtype`, and may silently replace only some values, ignoring any value that wasn't in the provided mapping.

`replace_strict` will cause an error if there is a value that wasn't replaced, and thus may map to a different `dtype`. There will be an optional argument for `replace_strict` to give a default value instead of erroring.
