### ISSUE TITLE
pl.read_csv() fails to read full file but completes operation without error message; cannot read more than 2,225 lines?

### ISSUE THREAD

**Issue by frasertajima** [pola-rs/polars#14300]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python


import polars as pl
#import numpy as np
import cupy as np
colspecs = [(None, None)]
kindle_clipping_file="My Clippings scribe.txt"
data = pl.read_csv(kindle_clipping_file, columns=[0], has_header=False)
with pl.Config(fmt_str_lengths=300, tbl_rows=30):
    display(data)
```

![Screenshot from 2024-02-05 18-34-45](https://github.com/pola-rs/polars/assets/69366820/ffd8d08f-096b-48b9-99b6-f2b77fa1eae6)

should be (after using pandas to read the same file and then converting to polars dataframe):

![Screenshot from 2024-02-05 18-34-27](https://github.com/pola-rs/polars/assets/69366820/f461ecc4-ca1f-4b7b-b1c8-6e61c6ac0ffc)

### Log output

```shell
There is no sterr. The problem is that the pl.read_csv() completes without an error message.
```

### Issue description

On a file with 10,000 plus lines, it only reads 2,225 lines but it does so without indicating any error or failure to read the full file (which is very undesirable). I tried renaming the file but had the same behaviour. Is 2,225 lines a hard limit reading a text file?

In Pandas, it reads the full 10,574 lines on the same file (and I manually confirmed that pandas reads in the entire file to the end). I can read the same file in pandas first and then convert to polars so it works fully:
``` python
import pandas as pd
import polars as pl
import cupy as np
colspecs = [(None, None)]
kindle_clipping_file="My Clippings scribe.txt"

# Read the fixed-width file with pandas
# using polars.read_csv() stops reading after 2,225 rows???
# need to pd.read_fwf then convert to polars to ensure at 10,000 rows read in
datapd = pd.read_fwf(kindle_clipping_file, colspecs=colspecs, header=None)

# Convert the pandas DataFrame to a Polars DataFrame
data = pl.from_pandas(datapd)
# must rename pandas column 0 to column_1 for the next section below
data = data.rename({"0": "column_1"})
#data = pl.read_csv(kindle_clipping_file, columns=[0], has_header=False)
with pl.Config(fmt_str_lengths=300, tbl_rows=20):
    display(data)
```

My entire notebook is here: https://github.com/frasertajima/kindle_clippings/blob/main/Kindle_scribe_my_clippings_reader_polars_cupy2.ipynb

I assume I am doing something wrong in Polars but did not notice when working with smaller files. Is this a polars issue or me? The dangerous aspect is that the operation completed without any indication of error. I only noticed after double checking and not finding recent entries in the kindle clipping.txt file. It should really crash with a message if it cannot read the entire file.

### Expected behavior

Expected to load 10,574 lines from the file, not 2,225.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.6.14-200.fc39.x86_64-x86_64-with-glibc2.38
Python:               3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.3
openpyxl:             3.0.10
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             2.4.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by frasertajima** [comment]
[My Clippings scribe.txt](https://github.com/pola-rs/polars/files/14174657/My.Clippings.scribe.txt)
Is the data file.

**Comment by JulianCologne** [comment]
@frasertajima not sure what you expect.
Your file has nothing to do with a csv file but you are using `read_csv`?

Hack:
```python
pl.read_csv(
    source="My.Clippings.scribe.txt",
    has_header=False,
    quote_char=None,
    separator="`", # >>> make sure this does not appear in the data...
).drop_nulls()
# 10_574, 1
```

or use python to read the file and create an generator/iterator over the lines and give it to `pl.DataFrame`

**Comment by frasertajima** [comment]
Thank you JulianCologne. I see I was pushing pl.read_csv() too far and assumed too much pd.read_fwf() equivalency. Entirely my fault as pandas has a much richer i/o API and I was not alert to the nuance! I think it is much safer to read in pandas when the file is not csv or parquet and convert to polars afterwards. 

Your hack works but is, as you note, fragile. The more robust approach for me is to use pandas and then convert to polars until polars has an equivalent to the pd.read_fwf() API call. An eye opening lesson! Many thanks for your prompt reply!

My preference for Polars over Pandas tripped me up into a really dumb error and I was completely thrown off by the API call working for the most part. One entry per line in csv is not the same as one entry per line in read_fwf(). I will pay much closer attention to the API. Thanks.

**Comment by alexander-beedie** [comment]
> Thank you JulianCologne. I see I was pushing pl.read_csv() too far and assumed too much pd.read_fwf() equivalency. 

You weren't "pushing it too far", these are simply different functions - a fixed width file and a delimited file are not the same thing 😉 

A slight variation on @JulianCologne's suggestion is to use `\x08` as the "fake" delimiter, because this is a control code representing a `DELETE` - in other words, you can't type it, so it can't appear in your input data (unless your input data is binary, which would immediately be completely invalid for any delimited file).

Observationally I think you can also do the entire parsing stage with a couple of basic polars expressions. The following results in the same output as all of the code in your linked notebook.
```python
import polars as pl

lf = pl.scan_csv(
    source      = "My.Clippings.scribe.txt", 
    has_header  = False, 
    new_columns = ["txt"], 
    separator   = "\x08",
).filter(
    pl.col("txt") != "==========",
)

df = lf.select( 
    txt = pl.col("txt").reshape((-1,3)),
).select(
    source = pl.col("txt").list.get(0),
    ref    = pl.col("txt").list.get(1),
    quote  = pl.col("txt").list.get(2),
).collect()
```
```python
with pl.Config(fmt_str_lengths=30):
    print(df)
    
    # ┌───────────────────────────────────┬───────────────────────────────────┬───────────────────────────────────┐
    # │ source                            ┆ ref                               ┆ quote                             │
    # │ ---                               ┆ ---                               ┆ ---                               │
    # │ str                               ┆ str                               ┆ str                               │
    # ╞═══════════════════════════════════╪═══════════════════════════════════╪═══════════════════════════════════╡
    # │ As Twitter destroys its brand by… ┆ - Your Highlight on Location 12-… ┆ reached 2.1 million               │
    # │ These Are the Plunderers: How Pr… ┆ - Your Highlight on page 142 | L… ┆ The GNC trade generated more tha… │
    # │ These Are the Plunderers: How Pr… ┆ - Your Highlight on page 142 | L… ┆ Boom times ended with a hard sto… │
    # │ These Are the Plunderers: How Pr… ┆ - Your Highlight on page 227 | L… ┆ Another former worker at the fac… │
    # │ These Are the Plunderers: How Pr… ┆ - Your Highlight on page 228 | L… ┆ “It’s a horrific thing to ask th… │
    # │ …                                 ┆ …                                 ┆ …                                 │
    # │ Financial Times - calibre (calib… ┆ - Your Highlight on page 80 | Lo… ┆ it is far from clear that Xi is … │
    # │ Financial Times - calibre (calib… ┆ - Your Highlight on Location 175… ┆ Chinese authorities’ promise of … │
    # │ Financial Times - calibre (calib… ┆ - Your Highlight on Location 176… ┆ As a result, the benchmark MSCI … │
    # │ Financial Times - calibre (calib… ┆ - Your Highlight on Location 177… ┆ That is a stark contrast to atti… │
    # │ barrons 05-02-2024 (Nook) (Newsp… ┆ - Your Highlight on page 169 | L… ┆ Nvidia, the fund’s single larges… │
    # └───────────────────────────────────┴───────────────────────────────────┴───────────────────────────────────┘
```

**Comment by JulianCologne** [comment]
@frasertajima both polars `read_csv` as well as pandas `read_fwf` are not ideal for your example file 😉 

- `read_csv`: read text file in csv "Comma Separated Values"; files containing table like data with a separater betwee values
- `read_fwf`: read text file with fwf "Fixed Width Format"; files containing table like data with fixed column widths

when you have a text/csv file it depends on the **content** what kind of reader you should use. Only because a file ends with ".csv" does not mean anything.

For you use case I personally recommend use opening the file using python and iterating over the rows.

**Comment by frasertajima** [comment]
One downside to loading the text file using the elegant polars code by Alexander Beedie above instead of `pd.read_table()` is that

`sort_df = new_df.unique(subset=['source'])`
returns different, jumbled results on each run
`sort_df = new_df.unique(subset=['source'], maintain_order=True)`
is more stable, but source column entries have bled into other columns and the shape of 2,391 is too large (it should be 221 as per pandas)

I don't understand why using the polars code would bork .unique()--I am probably wrecking something again or the separator is backfiring somehow. To be safe I will stick to version 2 of my notebook with pandas and the `pd.read_table() `API for now as the unique sources result of 221 is within expectations.

Using pd.read_table() and converting the pandas dataframe to polars is ok with 221 sources:
![Screenshot from 2024-02-06 13-06-18](https://github.com/pola-rs/polars/assets/69366820/55f25cbb-941b-47b1-95cd-d39796057e27)

Using the polars API .unique() has unexpected results with columns being transposed and 2,391 sources:
![Screenshot from 2024-02-06 13-08-15](https://github.com/pola-rs/polars/assets/69366820/bd1d36fb-89cd-4441-9dd9-82f7908ab36a)
.
