### ISSUE TITLE
Adding an optional suffix to overlaping columns when joining dataframes

### ISSUE THREAD

**Issue by LemonPy29** [pola-rs/polars#1432]
Hi @ritchie46, thank you for the awesome library! I was hoping if we could add an extra argument to the join's functions to replace the default suffix `_right` with a custom one, similar to the pandas api. 

The other day I was joining several dataframes with the same column names using the lazy api, and I didn't want to allocate until I finished joining them all. My problem was that I kept getting `_right` at the end, so I tried to rename the columns before the next join, but unfortunately the lazy api doesn't have a rename method as the eager one does. I ended up allocating in order to rename the columns. So this feature could eventually help on this case and maybe other ones. 

I have not so much experience with rust but I was trying to do it by myself. Searching the code base I found this function `finish_join` which is responsible for the rename, so I think something like this could potentially work 

```Rust
pub(crate) fn finish_join(
        &self,
        mut df_left: DataFrame,
        mut df_right: DataFrame,
        right_suffix: Option<&str>,
    ) -> Result<DataFrame> {
        /// ...

        let r_suff = right_suffix.unwrap_or("right");

        for name in rename_strs {
            df_right.rename(&name, &format!("{}_{}", name, r_suff))?;
        
       /// ...
    }
```
I dont' know if it's good because eventually the same argument should probably be added to all the callers of this function.  

Let me know if you think it's worth to add it.

**Comment by ritchie46** [comment]
Renaming + Suffix coming up!
