### ISSUE TITLE
[Python] Scan_parquet() should be able to accept directory as input

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#14342]
### Description

As of polars version 0.20.7 pl.scan_parquet() only accepts reference to files.
Should be able to accept reference to a directory, like pl.scan_pyarrow_dataset() does.
Implementation seems quite simple: should just append '/**/*.parquet' to the given input directory, and you have the file reference, that can be fed to the existing pl.scan_parquet() function.

**Comment by Smotrov** [comment]
BTW `/**/*.parquet` would not work is parquet files have no extensions. Such files could be generated by AWS Athena for example.

**Comment by nameexhaustion** [comment]
closed by https://github.com/pola-rs/polars/pull/17017
