### ISSUE TITLE
For many use-cases, the sum of Nulls really should be Null

### ISSUE THREAD

**Issue by MarkMoulton** [pola-rs/polars#14354]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({'a': [1, 2, 3, None], 'b': [5, 6, 7, None], 'c': [None, None, None, None]}, schema={'a': pl.Int32, 'b': pl.Int32, 'c': pl.Int32})
shape: (4, 3)
┌──────┬──────┬──────┐
│ a    ┆ b    ┆ c    │
│ ---  ┆ ---  ┆ ---  │
│ i32  ┆ i32  ┆ i32  │
╞══════╪══════╪══════╡
│ 1    ┆ 5    ┆ null │
│ 2    ┆ 6    ┆ null │
│ 3    ┆ 7    ┆ null │
│ null ┆ null ┆ null │
└──────┴──────┴──────┘

df.sum()
shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i32 ┆ i32 ┆ i32 │
╞═════╪═════╪═════╡
│ 6   ┆ 18  ┆ 0   │
└─────┴─────┴─────┘

df.sum_horizontal()
shape: (4,)
Series: 'sum' [i32]
[
	6
	8
	10
	0
]
```

### Issue description

Contrary to the "reported issue" checkbox, this issue has already been reported and put to bed.  I am expressing an opinion.  Before 2023 or so, Polars returned Null for a sum of Nulls.  That was the correct decision.  It now returns zero.  Not only does this new policy break a lot of code (mine at least), it risks introducing real statistical biases in code that _appears_ to work and forces the user to perform ugly hacks to get around the behavior.

The _sum_(empty_set) = 0 analog has some use in mathematics and became a convention.  However, it is entirely inappropriate for data science.  Zero is a number with a real-world consequences:  zero degrees Celsius, zero dollars in the bank.  Null is not a number; no data was collected.  The two must not be conflated.  So now, when I see a zero after doing an summation in Polars, I don't know whether no data was collected or my bank balance really is $0.00.  As a statistician, this new convention creates a real problem for my work.  Every summation has to be scrutinized and disambiguated.

This is just feedback from one member of your user community.  You may think it's not big deal, but I assure you it is.

### Expected behavior

A sum of Nulls should return Null, or there should be a way to specify strategy.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-13.4.1-arm64-arm-64bit
Python:               3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.2
numpy:                1.25.0
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              11.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
I understand the need for a way to propagate nulls / a null identity. This can be discussed in https://github.com/pola-rs/polars/issues/10016

**Comment by ritchie46** [comment]
We provide you with all the tools to do `null` aggregation. You can write an expression to do that yourself:

```python
from typing import Callable
import polars as pl

def null_agg(col: str, agg: Callable[[pl.Expr], pl.Expr]) -> pl.Expr:
    return pl.when(pl.col(col).null_count() > 0).then(None).otherwise(agg(pl.col(col)))

pl.DataFrame({
    "a": [1, 2, None, 3]
}).select(
    null_sum = null_agg("a", lambda c: c.sum()),
    zero_sum = pl.col("a").sum()
)
```
