### ISSUE TITLE
Dispersion measures in the `arr` namespace not externally available

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#14355]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

/

### Log output

```shell
/
```

### Issue description

This might be a documentation issue, I'm not sure.

`std`, `var` and `median` functions for the `arr` namespace were added in https://github.com/pola-rs/polars/pull/13245, but they do not appear in the list of implementations: https://docs.rs/polars/latest/polars/prelude/struct.ArrayNameSpace.html#implementations

Am I missing something?

For context, I noticed this when adding the `arr` namespace in `r-polars`. Other functions (`max`, `sum`, `unique`, etc.) are found but I get the error "no method named `std` found for struct `polars::prelude::ArrayNameSpace` in the current scope". Note that I use rust-polars 0.37.0, not the dev version, but those measures were implemented before the 0.37.0 release.

### Expected behavior

/

### Installed versions

/

**Comment by ritchie46** [comment]
They are available on the `Lazy` API.

**Comment by etiennebacher** [comment]
I think the issue is that those functions were not yet added in the Array namespace for the version of rust-polars that I use. This is weird because I use the commit tagged in [`rs-0.37.0`](https://github.com/pola-rs/polars/releases/tag/rs-0.37.0), which includes the PR "`list` & `array` measures of dispersion"

However, if I have navigate the repo at the commit tagged in rs-0.37.0, we can see that those changes are not included: https://github.com/pola-rs/polars/blob/rs-0.37.0/py-polars/src/expr/array.rs

**Comment by etiennebacher** [comment]
I suppose there's not much to do here, I can wait for 0.38.0
