### ISSUE TITLE
sort: add ability to specify how NaN and inf should be sorted

### ISSUE THREAD

**Issue by bike-picket** [pola-rs/polars#14356]
### Description

`DataFrame.sort` has `nulls_last` argument. For my use case, I want to show NaN, inf last if sorting by descending, but it is not currently supported.

Could `sort` signature be extended with two more arguments? For example:
* nans_last
* infs_last

**Comment by bike-picket** [comment]
A related comment: https://github.com/pola-rs/polars/issues/5420#issuecomment-1304436558

**Comment by deanm0000** [comment]
You can sort by expressions so you can already do this without needing new parameters. 

Here's an example
https://stackoverflow.com/a/77700711/1818713

It's not specifically about inf or nan but it's all just putting a binary expression in front of the numeric who behavior you want to change

**Comment by stinodego** [comment]
We do not plan to implement this. You'll have to accept the default or manipulate your data to make sure the NaNs / infs end up in the right place.
