### ISSUE TITLE
The `dtype` argument of `Series` does not enforce the actual dtype

### ISSUE THREAD

**Issue by Gattocrucco** [pola-rs/polars#14379]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series('a', ['1', '2', '3'], pl.UInt32)
t = pl.Series('a', ['1', '2', '3']).cast(pl.UInt32)

print(s.dtype) # -> String
print(t.dtype) # -> UInt32
```

```
String
UInt32
```

### Issue description

When I explicitly specify the data type of a series, I have the strong expectation that it will be the actual data type of the object created. `Series`, instead, seem to ignore the user-provided type if it is of a differend "kind" than the data (in the example, an integer type with string values).

### Expected behavior

I'd like the behavior of `Series(..., <type>)` to either be equivalent to `.cast(<type>)`, or to raise an error if the provided data is not compatible with `<type>`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by alexander-beedie** [comment]
Ideally we would error here; the dtype is not (and should not become) an implied `cast` op; compute should be explicit. The use of dtype is to inform the constructor what it should allocate for the input data (eg: what size of integer/float to create) and/or to handle the case where only `null` values are given so nothing can be inferred.

**Comment by stinodego** [comment]
I am working on this.

For the first case: this will throw an error, as strings cannot be directly interpreted as integers. If you set `strict=False`, you will get a series of integers.

**Comment by stinodego** [comment]
Closing in favor of #14427
