### ISSUE TITLE
Enable retries on connection reset by peer when doing scan_parquet against an object store

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#14384]
### Description

When querying a large s3 dataset with over 10000 files of size ~300MB, scan parquet will fail with high probability without any retry because of connection reset by peer, this is true even though I'm querying an s3 bucket in the same availability zone from an ec2 instance.

I get:
```
Generic S3 error: Error after 0 retries in 221.182308ms, max_retries:10, retry_timeout:10s, source:error sending request for url (https://s3.us-west-2.amazonaws.com/some_bucket/some_parquet_id.parquet): connection error: Connection reset by peer (os error 104)
```

This is fine when querying less files, but with many files this almost invariably happens.

A strategy mentioned in discord by @alexander-beedie that would be useful to implement and is basically absolutely necessary for polars to scale to very large cloud datasets could be:

```
This is an interesting one, and something I had to account for back in my days at JPM - I had written a multithreaded load method for our in-house dataframe (also mine 😅) from potentially thousands of files on a remote web server. given that a large risk run might generate as many as 20,000 files the chances that every one of them would load successfully every time was *very* low. i was writing C++ back then, but the solution (taking advantage of libcurl) was to have the downloaders draw from the pool of files, tracking two failure conditions - the total number of failures of the pool as a whole, and the number of failures of specific files. if a single file failed, you would increment the total failure count of both the pool and the file by one. each file was allowed to fail three times (each time being put back in the download pool) before the download as a whole would be considered failed, and the pool was allowed to register up to 50 total failures. this kept things very solid - only genuine/persistent network issues would tend to trigger an overall failure - transient failures would just be absorbed/handled transparently...
```

**Comment by ritchie46** [comment]
Have you tried setting the `retry` to non-zero?

**Comment by ritchie46** [comment]
Is there a repro on a public dataset that I could use to trigger this? I want to fix this.

**Comment by ritchie46** [comment]
What is your query? Eager/ streaming/ projection pushdown. Please, help me a bit ;)

**Comment by ritchie46** [comment]
Thanks. I have some vacation days, but I hope to get to this.

**Comment by tustvold** [comment]
We don't retry once response streaming has started, this could be added but would be a relatively non-trivial piece of logic.

As it stands this appears to be an issue specific to polars, and in particular the way it performs IO. The fact setting a prefetch helps, makes me even more confident you are flooding the network. Given this, the fact adding retries doesn't resolve the error, and the creator of hyper advised against this, I'm very lukewarm on making changes to the retry logic in object_store.

My recommendation would still be to try using LimitStore, and failing that use network analysis tools like VPC flow logs or tcpdump.

I would also be interested if datafusion runs into the same issues, as this might be a useful datapoint.

I am on holiday for the next 2-3 weeks, but will try to respond sporadically

**Comment by ritchie46** [comment]
@tustvold currently Polars has a single object store per file. That's why we have the global semaphore logic. Is it possible to load a a dataset from a single object-store? Then we could use `LimitStore`. 

Though we still need a semaphore to throttle multiple queries running a the same time. To my understanding the Limitstore, should have a similar effect as the global semaphore budget.

**Comment by tustvold** [comment]
That looks to be a different error. This could point to a couple of things, from some network throttling or futures not being polled in a timely manner. I'm not familiar with how polars has opted to hook up tokio, but it is important to keep CPU-bound tasks such as decoding parquet off the threadpool used for performing IO.

**Comment by ritchie46** [comment]
Hmm.. that's an interesting observation @tustvold. The decoding is indeed in an `async`. I will see if I can push that on the rayon thread pool and `await` the result on a queue. @kszlim here we made this change. Can you give it a spin?  https://github.com/pola-rs/polars/pull/15083

**Comment by ritchie46** [comment]
> I believe this could be improved even further, as having a oneshot channel where the parallelization is only across a few RGs probably has more overhead as opposed to having a MPSC channel where all the readers send all their bytes chunks to a single thread 

The row groups are already downloaded in an mpsc queue. The oneshot channel allows us to`await` that task and then other tasks can run. I think it should work as intended now.

Yes, we could do that for the metadata as well, but I don't expect the metadata deserialization to block long. 

In any case, great to hear about the improvements! :)
