### ISSUE TITLE
timestamp column is written as date column

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#1441]
#### Are you using Python or Rust?

**Python**

#### Describe your bug.

When I have a dataframe with a timestamp column such as : `2021-01-01 00:15:00` , where the column type is `Date64`,
if I then use the df.to_csv() function, the resulting csv file only shows `2021-01-01`, without the time.
 
#### What are the steps to reproduce the behavior?

```
df = pl.DataFrame(
        {
            "timestamp": ["2021-01-01 01:00:00","2021-01-01 02:00:00","2021-01-01 03:00:00"],
            "open": [100] * 3,
            "close": [110] * 3,
            "high": [120] * 3,
            "low": [99] * 3,
        }
    )
df["timestamp"] = df['timestamp'].str.strptime(pl.datatypes.Date64, "%Y-%m-%d %H:%M:%S")
df.to_csv("testing.csv")
```

#### What is the expected behavior?

I woudl expect it to be written with the time included.

**Comment by ritchie46** [comment]
https://github.com/jorgecarleitao/arrow2/pull/453
