### ISSUE TITLE
Return additional columns with aggregation expressions

### ISSUE THREAD

**Issue by thatcort** [pola-rs/polars#14411]
### Description

It would be great to be able to include additional columns when aggregating a data frame with a function that returns data frame row values (`min`, `max`, `first`, `last`, etc.). I'm imagining that each of those aggregation functions could be continued with a `with_columns()` call that would return the values from the specified columns for the selected row. That way we could request e.g. the min value of column A in each group with the corresponding values from columns B and C for that row. It could look something like:
```
df = pl.DataFrame({
    'Z': [1, 1, 2, 2],
    'A': [0, 1, 1, 2],
    'B': [3, 4, 5, 6],
    'C': [9, 8, 7, 6] 
})
df.group_by('Z').agg(pl.col('A').min().with_columns(['B', 'C']))

Z   A   B   C
-------------
1   0   3   9
2   1   5   7
```

**Comment by edavisau** [comment]
In the case of min/max, I don't think this would work as there may be multiple rows where the value is minimal/maximal: e.g. Z=[1, 1, 2, 2] and A=[3, 3, 4, 4] in your example

Have you tried
`df.filter(pl.col("A") == pl.col("A").min().over("Z"))`?

**Comment by thatcort** [comment]
@edavisau Thanks for the suggestion. I wasn't familiar with `.over()`
