### ISSUE TITLE
str.replace() with period replaces other characters instead

### ISSUE THREAD

**Issue by matterhorn103** [pola-rs/polars#14426]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data = {
    "Saldo": [
        "921,31",
        "944,16",
        "1.013,61",
        "1.466,13",
        "1.471,13"
    ]
}

df = pl.DataFrame(data)

print(df)
print(df.select(pl.col("Saldo").str.replace(".", "")))
print(df.select(pl.col("Saldo").str.replace(".", "a")))
print(df.select(pl.col("Saldo").str.replace("1", "a")))
print(df.select(pl.col("Saldo").str.replace(",", ".")))
```
Output:
```
shape: (5, 1)
┌──────────┐
│ Saldo    │
│ ---      │
│ str      │
╞══════════╡
│ 921,31   │
│ 944,16   │
│ 1.013,61 │
│ 1.466,13 │
│ 1.471,13 │
└──────────┘
shape: (5, 1)
┌─────────┐
│ Saldo   │
│ ---     │
│ str     │
╞═════════╡
│ 21,31   │
│ 44,16   │
│ .013,61 │
│ .466,13 │
│ .471,13 │
└─────────┘
shape: (5, 1)
┌──────────┐
│ Saldo    │
│ ---      │
│ str      │
╞══════════╡
│ a21,31   │
│ a44,16   │
│ a.013,61 │
│ a.466,13 │
│ a.471,13 │
└──────────┘
shape: (5, 1)
┌──────────┐
│ Saldo    │
│ ---      │
│ str      │
╞══════════╡
│ 92a,31   │
│ 944,a6   │
│ a.013,61 │
│ a.466,13 │
│ a.471,13 │
└──────────┘
shape: (5, 1)
┌──────────┐
│ Saldo    │
│ ---      │
│ str      │
╞══════════╡
│ 921.31   │
│ 944.16   │
│ 1.013.61 │
│ 1.466.13 │
│ 1.471.13 │
└──────────┘
```

### Log output

```shell
No output produced (no error is raised).
```

### Issue description

I was attempting to circumvent the fact that polars doesn't yet support parsing floats with , as the decimal separator by manually replacing commas with decimal points using `str.replace(",", ".")` This actually works well.

However, trying to do similar to remove the thousands separators, which are periods in my data, does not work. Instead, random characters are replaced with the desired character, and the searched character is left intact. Bizarrely, characters are replaced even from strings that didn't contain a period.

With `str.replace(".", "")`:
`921,31` becomes `21,31`
`1.013,61` becomes `.013,61`

With `str.replace(".", ",")`
`921,31` becomes `,21,31`
`1.013,61` becomes `,.013,61`

With `str.replace(".", "a")`
`921,31` becomes `a21,31`
`1.013,61` becomes `a.013,61`

### Expected behavior

Periods in strings should naturally be replaced with the character provided as the second argument of `str.replace()`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Linux-6.7.4-1-default-x86_64-with-glibc2.39
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by avimallu** [comment]
It looks like you're using regular expressions without knowing it - `.` matches *any* character. In case of eager matching by regex, which is what `str.replace` does, it replaces the first matching character - also the first character since `.` matches everything. Specifying `literal=True` to avoid this:

```py
import polars as pl

data = {
    "Saldo": [
        "921,31",
        "944,16",
        "1.013,61",
        "1.466,13",
        "1.471,13"
    ]
}

df = pl.DataFrame(data)

print(df)
print(df.select(pl.col("Saldo").str.replace(".", "", literal=True)))
```

produces

```py
shape: (5, 1)
┌──────────┐
│ Saldo    │
│ ---      │
│ str      │
╞══════════╡
│ 921,31   │
│ 944,16   │
│ 1.013,61 │
│ 1.466,13 │
│ 1.471,13 │
└──────────┘
shape: (5, 1)
┌─────────┐
│ Saldo   │
│ ---     │
│ str     │
╞═════════╡
│ 921,31  │
│ 944,16  │
│ 1013,61 │
│ 1466,13 │
│ 1471,13 │
└─────────┘
```

**Comment by alexander-beedie** [comment]
As @avimallu says, this isn't a bug; you just need to read the docstring and set `literal=True`  ;)

```
Replace first matching regex/literal substring with a new string value.

Parameters
----------
pattern
    A valid regular expression pattern, compatible with the `regex crate
    <https://docs.rs/regex/latest/regex/>`_.
value
    String that will replace the matched substring.
literal
    Treat `pattern` as a literal string.
n
    Number of matches to replace.
```

**Comment by alexander-beedie** [comment]
As @avimallu says, this isn't a bug; you just need to read the docstring and set `literal=True`  ;)

```
Replace first matching regex/literal substring with a new string value.

Parameters
----------
pattern
    A valid regular expression pattern, compatible with the `regex crate
    <https://docs.rs/regex/latest/regex/>`_.
value
    String that will replace the matched substring.
literal
    Treat `pattern` as a literal string.
n
    Number of matches to replace.
```

**Comment by matterhorn103** [comment]
Ah ok, sorry for the spurious report! It did seem like a very odd bug. :smile: 

Made me realize I know next to nothing about regex and need to brush up on it, at least.

I do wonder whether the default should be `literal=True` to avoid confusing dumb people like me? I feel like very few find and replace implementations use regex... Kate supports regex for its find and replace for example, but not by default.
