### ISSUE TITLE
A numeric type is converted to a string type

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#1444]
#### Describe your feature request

Please describe the behavior you want and the motivation. Please also provide
examples of how polars would be used if your feature request were added.

If you're not sure what to write here, then try imagining what the ideal
documentation of your new feature would look like Then try to write it.
#####like pandas
import pandas as pd
s = pd.Series([1, 2, 3])
s.astype(str)

**Comment by ztsweet** [comment]
sorry, i have get it.
#
import polars as pl
s = pl.Series([1, 2, 3])
s.cast(pl.datatypes.np.str)

**Comment by ritchie46** [comment]
> import polars as pl
s = pl.Series([1, 2, 3])
s.cast(pl.datatypes.np.str)


You should use the polars dtypes: `s.cast(pl.Utf8)`

**Comment by ztsweet** [comment]
@ritchie46 thanks 👍
