### ISSUE TITLE
Broken docstrings, double backslash -> single backslash

### ISSUE THREAD

**Issue by bjrtx** [pola-rs/polars#14454]
### Description

Consider e.g. https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L2049-L2093

The expression `.. math:: O(n + k \\log{}n - \frac{k}{2})` within a docstring should be `.. math:: O(n + k \log{}n - \frac{k}{2})`, introduces an unwanted linebreak (see the [`Expr.bottom_k` doc](https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.bottom_k.html) and the screenshot below). 

I've found this in: `Series.bottom_k`, `Series.top_k`, `Expr.bottom_k` and `Expr.top_k`.

![linebreak](https://github.com/pola-rs/polars/assets/57685415/26dcfe03-a86b-4959-b9f7-97dfa92525d7)

### Link

https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.bottom_k.html

**Comment by MarcoGorelli** [comment]
thanks @bjrtx - interested in submitting a PR to fix?

**Comment by bjrtx** [comment]
> thanks @bjrtx - interested in submitting a PR to fix?

Yes, hopefully by Saturday.
