### ISSUE TITLE
Should all panics be reported as "bug"?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#14463]
### Description

I'm unsure whether all panics should be reported or if they are considered as "standard" error messages. For example, the code below panicks but it also gives a clear message about what's wrong, and it's a user mistake (should have been `.list.sort()`). Is it something that should be reported?

```python
import polars as pl
pl.Series([[1, 2]]).sort()
```
```
thread '<unnamed>' panicked at crates\polars-core\src\series\series_trait.rs:341:9:   
`sort_with` operation not supported for dtype `list[i64]`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\polars\series\series.py", line 3426, in sort   
    return self._from_pyseries(self._s.sort(descending, nulls_last))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: `sort_with` operation not supported for dtype `list[i64]`
```

I couldn't find information about this in the docs. It would be useful to include something along the lines of "Any panic should/shouldn't be reported" in the [Reporting bugs](https://docs.pola.rs/development/contributing/#reporting-bugs) section.

### Link

https://docs.pola.rs/development/contributing/#reporting-bugs

**Comment by ritchie46** [comment]
Those that are reachable by user code by using our API should yes. The above example should raise an error.

**Comment by etiennebacher** [comment]
Ok, I can open a separate issue for this example
