### ISSUE TITLE
Unexpected behavior of `DataFrame.item` for list dtype

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#14460]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({'col': [['1', '2']]}).item()
# shape: (2,)
# Series: '' [str]
# [
# 	"1"
# 	"2"
# ]

pl.DataFrame({'col': [['1', '2']]}).row(0)[0]
# ['1', '2']

```

### Issue description

As per the documentation of `item`: "Return the DataFrame as a scalar, or return the element at the given row/column".

I thought that `item` on a list dtype column would return a python list. `row(0)[0]` is returning a python list. Is there any reason for this difference ?

### Expected behavior

`item`on `list` return python list (like `item` on `struct` dtype return python dict

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-14.1.1-x86_64-i386-64bit
Python:               3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.26
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by gab23r** [comment]
I think this explain even better the issue, I have a series of one element which is a list. I want to get the element.
Today I can't ( or I don't know ) how to do it easily

```python
s = pl.Series([['1', '2']]).
s.item()
# shape: (2,)
# Series: '' [str]
# [
# 	"1"
# 	"2"
# ]

s[0]
# shape: (2,)
# Series: '' [str]
# [
# 	"1"
# 	"2"
# ]


s.row(0)
# AttributeError: 'Series' object has no attribute 'row'

# workaround
s.head(1).to_list()[0]
# ['1', '2']

```

**Comment by stinodego** [comment]
This is intended. Converting the data from Series to a list would be a relatively expensive operation, while returning a Series is free. You should think of a `List` column as a Series where each element is another Series.

If you want a Series as a list, you can use `to_list`:

```python
import polars as pl

s = pl.Series([["1", "2"]])
result = s.item().to_list()
print(result)
```
