### ISSUE TITLE
Excessive Disk Storage Consumption with scan_parquet and sort Operations

### ISSUE THREAD

**Issue by arghaffari** [pola-rs/polars#14479]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
%%timeit
a = pl.scan_parquet("../Mega Project/all_row_data.parquet").sort("transaction_datetime").collect(streaming=True)
```

When running the above command, it starts consuming an excessive amount of disk storage (~400 GB), whereas the parquet file size is only around 1.8GB. For comparison, running a similar operation in DuckDB consumes around 5GB.

![image](https://github.com/pola-rs/polars/assets/8070577/8d76ccd8-4289-41cd-9616-364722a7019e)

### Log output

```shell
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 get_ipython().run_cell_magic('timeit', '', '\na = pl.scan_parquet("../Mega Project/all_row_data.parquet").sort("transaction_datetime").collect(streaming=True)\n')

File ~\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:2493, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2491 with self.builtin_trap:
   2492     args = (magic_arg_s, cell)
-> 2493     result = fn(*args, **kwargs)
   2495 # The code below prevents the output from being displayed
   2496 # when using magics with decorator @output_can_be_silenced
   2497 # when the last Python token in the expression is a ';'.
   2498 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~\anaconda3\Lib\site-packages\IPython\core\magics\execution.py:1185, in ExecutionMagics.timeit(self, line, cell, local_ns)
   1183 for index in range(0, 10):
   1184     number = 10 ** index
-> 1185     time_number = timer.timeit(number)
   1186     if time_number >= 0.2:
   1187         break

File ~\anaconda3\Lib\site-packages\IPython\core\magics\execution.py:173, in Timer.timeit(self, number)
    171 gc.disable()
    172 try:
--> 173     timing = self.inner(it, self.timer)
    174 finally:
    175     if gcold:

File <magic-timeit>:1, in inner(_it, _timer)

File ~\AppData\Roaming\Python\Python311\site-packages\polars\lazyframe\frame.py:1940, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1937 if background:
   1938     return InProcessQuery(ldf.collect_concurrently())
-> 1940 return wrap_df(ldf.collect())

PanicException: called `Result::unwrap()` on an `Err` value: Io(Os { code: 112, kind: StorageFull, message: "There is not enough space on the disk." })
```

### Issue description

Running the provided command with a 1.8GB parquet file results in unexpected and excessive disk storage consumption of more than 400GB permanently. This behavior significantly deviates from the expected and comparable usage seen with DuckDB for a similar operation, which only consumes around 5GB of disk storage temporarily. This issue has been observed on a Windows 10 platform.

```
%%timeit
duckdb.sql("""CREATE OR REPLACE VIEW all_row_data AS
SELECT *
FROM read_parquet('../Mega Project/all_row_data.parquet');""")

duckdb.sql("""SELECT *
FROM all_row_data
ORDER BY transaction_datetime;""").pl()
```

### Expected behavior

The expected behavior would be for the scan_parquet().sort().collect(streaming=True) operation to complete with a reasonable amount of disk storage consumption.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.15.1
fsspec:               2023.10.0
gevent:               23.9.1
hvplot:               0.9.1
matplotlib:           3.8.1
numpy:                1.26.2
openpyxl:             3.0.10
pandas:               2.1.1
pyarrow:              11.0.0
pydantic:             2.5.2
pyiceberg:            0.5.1
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
This isn't a bug. The sort is done out of core and needs to spill to disk. You can remove the directory.

We can look into compression methods for spilling or better garbage collection. But that's a feature request.

**Comment by arghaffari** [comment]
Thank you. It would be appreciated if we could continue to implement this as a feature. By the way, @ritchie46, the process was halted midway and consumed 400GB after running out of storage. Can we reduce the storage consumption to at least 1/80 of the current size, similar to DuckDB's efficiency at this scale, by implementing some form of compression as a feature? To me, this amount seems excessively large for sorting a 1.8GB dataset in fewer than 10 runs using %%timeit.

**Comment by fdcastel** [comment]
Just passing to say that this one also hit me today. 

Same scenario: everything fast on a ~5GB parquet file. (50M rows). 

But when I added a `.sort()`... god forbid! 🐢 

Drive usage peaked at 100% -- I seriously thought my NVMe drive was dying... 😅

**Comment by ritchie46** [comment]
> Same scenario: everything fast on a ~5GB parquet file. (50M rows).

How much was htat in memory?

**Comment by ritchie46** [comment]
Can I get a repro on this?

**Comment by fdcastel** [comment]
> How much was htat in memory?

Machine has 32GB RAM. Around ~4GB occupied initially (from OS and other apps).

Running the code quickly maxed out all available memory. After a while I opened Task Manager and did see the NVMe drive at 100% too. 

Cpu (12-core Ryzen 3900X) had spikes of 100% usage and then down to 15%~20%.

Windows 11
Python 3.11
Polars 0.20.10



> Can I get a repro on this?

Sure! I can prepare one in two days, tops (sorry, busy week here).

How can I send you ~5GB of data? Google Drive?

**Comment by ritchie46** [comment]
> How can I send you ~5GB of data? Google Drive?

I guess that would work. How much is the df in memory?

**Comment by fdcastel** [comment]
> I guess that would work. How much is the df in memory?

Cannot give you a precise number. But a crude test with Windows Task Manager and `read_parquet()` in VSCode debugger bring the memory from 6.0GB to 11.5GB (*).

_(*) Interestingly, during `read_parquet` execution the RAM was maxed out (at 32GB) for around 1~2minutes and then went down to 11.5GB after its completion. Dataframe has ~59M rows._

I'm writing a quick test now (for the original problem, with `scan_parquet()`). To what Google Account I can send the files via Google Drive?

If you don't wish to disclose it here, my email is my github username at gmail dot com.

**Comment by ritchie46** [comment]
ritchie@polars.tech

**Comment by fdcastel** [comment]
Sent!

**Comment by arghaffari** [comment]
You can also test it out using my dataset sent here https://github.com/pola-rs/polars/issues/14480 for both issues.

**Comment by ritchie46** [comment]
Thanks! Will take a look after my vacation. My internet connection is too poor. Will take 16h to download. :')
