### ISSUE TITLE
`from_arrow` much slower with 0.20.6

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#14472]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I can try to come up with one if requested.

### Issue description

With the 0.20.6 release, probably due to the new string type, `from_arrow()` is much slower:

```
t.shape
# => (2009470, 10)
pl.from_arrow(t).dtypes
# => [String, String, Date, Date, String, Date, Date, String, String, String]

# Polars 0.20.5
%timeit pl.from_arrow(t, rechunk=False)
# => 456 µs ± 2.16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

%timeit pl.from_arrow(t)
# => 27.6 ms ± 503 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

# Polars 0.20.6 and 0.20.7
%timeit pl.from_arrow(t, rechunk=False)
# => 47.4 ms ± 504 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit pl.from_arrow(t)
# => 77.3 ms ± 796 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### Expected behavior

Should be faster maybe? Or is this an inevitable penalty for the new string type if the Arrow input uses the old string type?

### Installed versions

Polars 0.20.{5,6,7}
PyArrow 15

**Comment by ritchie46** [comment]
>  Or is this an inevitable penalty for the new string type if the Arrow input uses the old string type?

This

**Comment by jonashaag** [comment]
Ok, if there is nothing that can be improved here feel free to close.
