### ISSUE TITLE
Excessive Memory Consumption Leading to Kernel Error in Polars

### ISSUE THREAD

**Issue by arghaffari** [pola-rs/polars#14480]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# Polars code causing excessive memory consumption
raw_data = (
    pl.scan_parquet("../Mega Project/all_row_data.parquet")
    .with_columns(
        pl.when(pl.col("transaction_type") == "RETURN")
        .then(pl.col("final_value").mul(-1))
        .otherwise(pl.col("final_value"))
    )
    .group_by(["customer_id", "sold_item_store_code", "transaction_id"])
    .agg(
        pl.col("loyalty_membership_creation_datetime").min(),
        pl.col("final_value").sum().alias("total_transaction_final_value"),
        pl.col("discount_value").sum().alias("total_transaction_discount_value"),
        pl.col("quantity").sum().alias("total_transaction_quantity"),
        pl.col("transaction_channel").first(),
        pl.col("division_name").mode().first(),
        pl.col("sub_division_name").mode().first(),
        pl.col("department_level_one_name").mode().first(),
        pl.col("department_level_two_name").mode().first(),
        pl.col("department_level_three_name").mode().first(),
        pl.col("transaction_datetime").first()
    )
    .filter(pl.col("total_transaction_final_value") > 0)
    .collect(streaming=True)
)

```
This code consumes all available memory, resulting in a Kernel error and termination of the process.

![image](https://github.com/pola-rs/polars/assets/8070577/ffd174de-e3b0-479f-8ad7-743dbb3cbb33)

### Log output

```shell
Due to the nature of the problem (Kernel error), capturing specific log outputs related to memory consumption is not straightforward. The process terminates unexpectedly without detailed error messages.
```

### Issue description

When executing the provided Polars code, it leads to excessive memory consumption, ultimately causing a Kernel error and termination of the process. This occurs with a 1.8GB parquet file, which should be manageable given the system's resources. In contrast, executing a similar operation in DuckDB with the same dataset consumes significantly less memory and completes successfully within a few seconds.

```
raw_data = duckdb.sql("""
SELECT 
    customer_id,
    MIN(loyalty_membership_creation_datetime) AS first_loyalty_membership_creation_datetime,
    sold_item_store_code,
    transaction_id,
    SUM(CASE WHEN transaction_type = 'RETURN' THEN final_value * -1 ELSE final_value END) AS total_transaction_final_value,
    SUM(discount_value) AS total_transaction_discount_value,
    SUM(quantity) AS total_transaction_quantity,
    FIRST(transaction_channel) AS transaction_channel,
    FIRST(division_name) AS division_name,
    FIRST(sub_division_name) AS sub_division_name,
    FIRST(department_level_one_name) AS department_level_one_name,
    FIRST(department_level_two_name) AS department_level_two_name,
    FIRST(department_level_three_name) AS department_level_three_name,
    FIRST(transaction_datetime) AS transaction_datetime,
    COUNT(transaction_id) AS basket_size,
FROM "../Mega Project/all_row_data.parquet"
GROUP BY customer_id, sold_item_store_code, transaction_id
HAVING SUM(CASE WHEN transaction_type = 'RETURN' THEN final_value * -1 ELSE final_value END) > 0
""").pl()
```

![image](https://github.com/pola-rs/polars/assets/8070577/4769b886-962e-49cd-bfb8-98bea40413ba)

### Expected behavior

The expected behavior would be for the Polars operation to process the data efficiently, similar to DuckDB, without consuming excessive memory or causing a Kernel error. Ideally, memory usage should remain within reasonable limits throughout the operation.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.8
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.15.1
fsspec:               2023.10.0
gevent:               23.9.1
hvplot:               0.9.1
matplotlib:           3.8.1
numpy:                1.26.2
openpyxl:             3.0.10
pandas:               2.1.1
pyarrow:              11.0.0
pydantic:             2.5.2
pyiceberg:            0.5.1
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9```

</details>

**Comment by mcrumiller** [comment]
@arghaffari, how hard would it be to add sample code that can generate a file with a similar size and schema?

**Comment by ritchie46** [comment]
This isn't a bug. You go out of memory. Polars doesn't support the mode aggregation in a streaming manner.

**Comment by arghaffari** [comment]
@ritchie46 I tested it out without using `streaming=True`, but no difference it still crashes!
![image](https://github.com/pola-rs/polars/assets/8070577/ceee5cbf-69c6-48bd-8947-f979e2eba2d9)

**Comment by ritchie46** [comment]
Yes, you go out of memory.

**Comment by arghaffari** [comment]
I'm not that technical to know what happens under the hood, but I'm curious to know why it doesn't happen in Duckdb so I'll hash some of my sensitive data and share it with you, should I share it here or send it directly to an email or whatever? @ritchie46

**Comment by arghaffari** [comment]
@ritchie46 @mcrumiller You can download it from here (Hashing has changed the size of the file):
https://drive.google.com/file/d/1RJjXIDMn0cBpNsSRxhZAmuQjuvPH7Wkh/view?usp=drive_link
For your convenience, I wrote the script based on new names:

```
raw_data = (
    pl.scan_parquet("output.parquet")
    .with_columns(
        pl.when(pl.col("transaction_type") == "RETURN")
        .then(
        pl.col("modified_final_value").mul(-1)
        )
        .otherwise(
            pl.col("modified_final_value")
        )
    )
    .group_by(["hashed_customer_id", "hashed_sold_item_store_code", "transaction_id"])
    .agg(
        pl.col("loyalty_membership_creation_datetime").first(),
        pl.col("modified_final_value").sum().alias("total_transaction_final_value"),
        pl.col("modified_discount_value").sum().alias("total_transaction_discount_value"),
        pl.col("modified_quantity").sum().alias("total_transaction_quantity"),
        pl.col("transaction_channel").first(),
        pl.col("division_name").mode().first(),
        pl.col("sub_division_name").mode().first(),
        pl.col("department_level_one_name").mode().first(),
        pl.col("department_level_two_name").mode().first(),
        pl.col("department_level_three_name").mode().first(),
        pl.col("transaction_datetime").first()
    )
    .filter(
        pl.col("total_transaction_final_value") > 0
    )
    .collect()
)
```

**Comment by arghaffari** [comment]
You can use this dataset for this issue as well.
https://github.com/pola-rs/polars/issues/14479

**Comment by ritchie46** [comment]
I requested access for the file.

**Comment by arghaffari** [comment]
granted!

**Comment by ritchie46** [comment]
@arghaffari this is expected. The file expands to a huge table that doesn't fit into memory. At least not on my 32GB machine.

Polars cannot do this query streaming because we don't support the `mode` aggregation in streaming mode, hence we collect to memory and you go OOM.

We want to improve streaming support, but that is an ongoing process. Operations that don't support streaming isn't a bug, so I will close this issue.
