### ISSUE TITLE
`scan_parquet` leaks memory with small row group sizes

### ISSUE THREAD

**Issue by borchero** [pola-rs/polars#14482]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Dataframe generation:

```python
import polars as pl

# 100M * 2 * 8 bytes = 1.6 GB
df = pl.DataFrame({
    "col1": [0x5555555555555555 for _ in range(100_000_000)],
    "col2": [0x4444444444444444 for _ in range(100_000_000)],
})
df.write_parquet("df.parquet")
```

Leaking code snippet:

```python
import gc
import time
import polars as pl

ldf = pl.scan_parquet("df.parquet")
time.sleep(1)

df = ldf.collect()
time.sleep(1)

del df
del ldf
for _ in range(10):
    gc.collect()
time.sleep(1)
```

### Log output

```shell
n/a
```

### Issue description

@delsner and I are experiencing a memory leak whenever using `pl.scan_parquet` after creating a `.parquet` file using `pl.write_parquet` (with default parameters). We first noticed this issue when calling `collect()` on a lazy frame initialized from `pl.scan_parquet` in a loop which caused ever increasing memory usage.

We used [`memray`](https://bloomberg.github.io/memray/index.html) to analyze memory usage and try to identify the leak. The memory usage of the "leaking code snippet" above is as follows:

```bash
PYTHONMALLOC=malloc python -m memray run --native --output output-test.bin test.py
python -m memray flamegraph output-test.bin -o flamegraph-test.html
python -m memray flamegraph --leak output-test.bin -o flamegraph-test--leak.html
```

![image (2)](https://github.com/pola-rs/polars/assets/22455425/67ee3fde-0d64-438b-8235-6143755e164f)

As we can see, memory usage does not drop (neither heap size nor RSS) once the collected data frame goes out of scope. The memray flamegraph shows plenty of small (~5-50 MiB) leaking allocations once the program has finished.

---

Interestingly, ff customizing `write_parquet` to use larger row groups (which seem to be rather small by default, see [docs](https://docs.pola.rs/py-polars/html/reference/api/polars.DataFrame.write_parquet.html)), we don't see the same behavior: memory is deallocated as one would expect:

![image (3)](https://github.com/pola-rs/polars/assets/22455425/78cbab2a-abf9-4d79-aed6-b06e3ab815d0)

---

This issue is likely (closely) related to https://github.com/pola-rs/polars/issues/3972 which appears to have been fixed quite some time ago.

### Expected behavior

Both heap size and RSS should drop to the baseline once the collected data frame goes out of scope.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  0.9.0
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.15.3
fsspec:               2023.12.2
gevent:               23.9.1
hvplot:               0.9.2
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.25
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
This isn't a memory leak. If we make a lot of small allocations, the heap gets fragmented and the memory allocator cannot return all memory to the OS. The memory is still available for the process.

**Comment by borchero** [comment]
> the memory allocator cannot return all memory to the OS

Intuitively, this is a little hard to grasp 😅

> The memory is still available for the process.

But yes, further tests confirm this. Thanks for the clarification that this is, indeed, not an issue with polars itself!

**Comment by borchero** [comment]
One related question maybe: what's the reasoning behind `pl.write_parquet` writing so many small row groups causing these tiny allocations?
