### ISSUE TITLE
replace(): InvalidOperationError: casting from Utf8View to Boolean not supported

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#14499]
### Description

I'm getting an `InvalidOperationError: casting from Utf8View to Boolean not supported` from the following:

```python
import polars as pl
df = pl.DataFrame({'a': ['Yes', 'No', 'N/A']})
df.with_columns(
    pl.col('a').replace(
        {'Yes': True, 'No': False, 'N/A': None},
        return_dtype=pl.Boolean
    )
)
```
But this used to work with `map_dict()` in version `0.19`.

Right now, you have to chain another `.cast()` to it.
```python
df.with_columns(
    pl.col('a').replace(
        {'Yes': 1, 'No': 0, 'N/A': None},
        return_dtype=pl.Int64
    ).cast(pl.Boolean)
)
```

**Comment by ritchie46** [comment]
@stinodego does something go wrong here in the schema or supertype here?

**Comment by stinodego** [comment]
Indeed this is expected behavior, but we should probably change it. See https://github.com/pola-rs/polars/issues/14302

**Comment by stevenlis** [comment]
@nameexhaustion But if your mapping does not include all values in the column and you want to retain the original value while changing the type, previously I could use `default=pl.first()` and `return_dtype`. I believe the current replace() API no longer supports that, as I now have to pass `default=None` to make a type change, correct?

**Comment by stinodego** [comment]
This would also not have worked previously. You are creating a boolean column (`return_type=pl.Boolean`) but you want to keep your old string values. That's not possible. Strings cannot be cast to boolean.

**Comment by stevenlis** [comment]
@stinodego I see. Thank you for the explanations.
