### ISSUE TITLE
read_excel + calamine/fastexcel: Allow fallback/default schema override when mixed datatypes detected.

### ISSUE THREAD

**Issue by adrivn** [pola-rs/polars#14495]
### Description

Excel files aren't really known for types enforcement, so as analysts we -more often than not- must deal with lots of preprocessing/wrangling before using any data contained in a workbook.

Upon trying to load a massive dataset from Excel, some columns contain mixed data types (strings and dates) and I get this error:

```python
RuntimeError: Could not create RecordBatch from sheet ENERGY USAGE Q4

Caused by:
    0: Could not build schema for sheet ENERGY USAGE Q4
    1: could not figure out column type for following type combination: {Utf8, Timestamp(Millisecond, None)}
```

As the data contains over 50k rows and 100+ columns, its very time-consuming to open the file, and inspect where the column that throws the error might be. Will there be only one? Will there be many? If so, which? and what records aren't properly formatted? All these shouldn't be manually inspected: instead, I propose an addition that might come in handy.

Some sort of parameter/option for the `read_excel` method, that enables automatic conversion to String or Utf8 datatype, if any error during the load is encountered. I'm not good at naming, but perhaps `fallback_schema_as_str` could do.

The method would then look like this: `pl.read_excel('file.xlsx', engine='calamine', fallback_schema_as_str=True)`

Using fastexcel v0.9.0 and polars v0.20.8

```--------Version info---------
Polars:               0.20.8
Index type:           UInt32
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           2.0.23
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9```

**Comment by PrettyWood** [comment]
Before adding a flag on fastexcel side to fallback on string (which may be a good idea but I want to wait and see the usage before adding new params and overload the API), we can first support mix types with dates and timestamps. I'll have a look tomorrow

**Comment by alexander-beedie** [comment]
Closing this here, in favour of the upstream issue 👌
