### ISSUE TITLE
Float32 accuracy issue

### ISSUE THREAD

**Issue by Macfly** [pola-rs/polars#14497]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({'data':799.32}, schema={'data':pl.Float32})['data'][0]
```

### Issue description

it prints 799.3200073242188

### Expected behavior

Expecting 799.32 (like with the type pl.Float64)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Linux-6.1.75-99.163.amzn2023.x86_64-x86_64-with-glibc2.34
Python:               3.10.13 (main, Sep 21 2023, 10:13:35) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.1.2
pyarrow:              15.0.0
pydantic:             2.4.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
Maybe consider opening an issue at IEEE_754? ;)

**Comment by mcrumiller** [comment]
@Macfly to expound a bit on Ritchie's answer, numbers are stored in the computer in binary format with a limited number of bits, and so we cannot represent all numbers exactly. If you take a look at https://www.omnicalculator.com/other/floating-point and select `Number to Floating Point` and enter `799.32`, you'll see that the number stored as a 32-bit float actually represents the number 799.32000732421875. If you set the number of bits to 64, you get a whole lot more precision, but it's still not exact: 799.32000000000005.

**Comment by Macfly** [comment]
I understand the floating accuracy but why with Numpy and Pandas, it is displayed as 799.32 with float32.
Is there something special with polars that always show the exact floating representation?
