### ISSUE TITLE
LazyFrame::sum() should LazyFrame instead of Result<LazyFrame>

### ISSUE THREAD

**Issue by benjamin-lieser** [pola-rs/polars#14503]
### Description

Logically I can't see why this function can fail.
Looking from the code there can be an `Err` from an internal call to `LazyFrame::schmema()`. I does not make sense to me to expose this error here, it should get returned in the `collect()` call.
Currently this makes error handling at the call side quite convoluted.

If there is a way for this function to fail than at least document it.

Similar issues exist for `min`, `max`, `mean`

**Comment by stinodego** [comment]
Expr.sum() can fail when called on unsupported data types (e.g. `List`). So it makes sense for LazyFrame.sum() to fail too, right?

**Comment by benjamin-lieser** [comment]
Expr.sum() returns an Expr not Result<Expr>
So the analog for the LazyFrame would be that this would error at collect() not already at sum()
I see the argument that `sum` should fail on `List`, but I would still argue that the correct place for the error would be collect().

**Comment by ritchie46** [comment]
It needs the schema to determine which columns to `sum`. The schema operation is fallible. You can see this in the code.
