### ISSUE TITLE
Change default table rows displayed in Notebooks to 10 (`pl.Config.set_tbl_rows(10)`)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#14515]
### Description

In every polars data analysis project I use this "boilerplate" line `pl.Config.set_tbl_rows(10)` because the default of showing 25 (?) rows is just too much imo.

It covers too much space in the notebook without giving any real benefit. It would be nicer if I could see more of the surrounding code.

Also 25 seems to be very arbitrary?
Most libraries use 5 rows for head/foot and when displaying the full df then use the same 5 rows for the head, then dots (...) and then 5 for the foot. I think this is a very good and reasonable default.

Would love to get some opinions of other polars users! imo the current default is not ideal 😃

**Comment by cmdlineluser** [comment]
I thought it was changed from 8 to 10

- #13699

But it seems for Series it's still at 25?

**Comment by JulianCologne** [comment]
> I thought it was changed from 8 to 10
> 
> * [feat(python,rust): raise default frame/series repr height from 8 to 10 #13699](https://github.com/pola-rs/polars/pull/13699)
> 
> But it seems for Series it's still at 25?

huh? 😮 

This is definitely NOT working for me! Anyone else having the problem?

I just tested with `0.20.8` on
- local notebook (fresh .env)
- google collab notebook
- databricks notebook

ALL of them show 25 rows 🤣

**Comment by JulianCologne** [comment]
found the "problem"

its different between the html and plain text output

<img width="581" alt="image" src="https://github.com/pola-rs/polars/assets/25177421/4d634cac-fb1c-4639-b48c-3688eb2a2b06">

**Comment by stinodego** [comment]
I think it's a good idea to match the two.
