### ISSUE TITLE
Support custom Python objects in dataframes (and better clarity)

### ISSUE THREAD

**Issue by staadecker** [pola-rs/polars#14523]
### Description

Pandas supports custom Python objects in dataframes which is a very powerful feature. For example, [this library](https://github.com/Gurobi/gurobipy-pandas) allows for the rapid creation of large optimization models by storing its custom objects in Pandas dataframes. Having a similar support in Polars would be a game changer.

Additionally, currently it is unclear what "limited support" exists for Python objects. I was able to store some Python objects in a polars dataframe but not others. Why is this?

**Comment by stinodego** [comment]
We have an `Object` type. That should be what you're looking for.

> Additionally, currently it is unclear what "limited support" exists for Python objects.

With limited support, we mean that most Polars operations (e.g. aggregations / arithmetic) will not work on Object columns.

> I was able to store some Python objects in a polars dataframe but not others.

If there are certain objects you cannot store, please make a bug report!
