### ISSUE TITLE
ShapeMisMatch error when vstacking two dataframes with equal amount columns, but different number of rows

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#1452]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.9.11

#### Describe your bug.

When using .vstack(), do grow a dataframe vertically, it only works when the dataframes have the same length.

```
df1 = pl.DataFrame({
    "foo": [1, 2],
    "bar": [6, 7],
    "ham": ['a', 'b']
    })
df2 = pl.DataFrame({
    "foo": [3, 4, 5],
    "bar": [8 , 9, 8],
    "ham": ['c', 'd','s']
    })

df1.hstack(df2)
```

`RuntimeError: Any(ShapeMisMatch("Could not create a new DataFrame from Series. The Series have different lengths"))
`

This is not intended behaviour right? I can image this error for if the columns do not match, but not for the number of rows.

I'm trying to append new data to an existing dataframe, and get the above issues.

**Comment by ritchie46** [comment]
In the example you are doing a `hstack`, a horizontal stack, so the number of rows must be equal.

**Comment by romanovacca** [comment]
i'm guessing monday mornings arent doing me any good. Thanks!
