### ISSUE TITLE
Creating Series from empty arrow chunked array loads pandas

### ISSUE THREAD

**Issue by char101** [pola-rs/polars#14549]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import sys, duckdb
>>> 'pandas' in sys.modules
False
>>> duckdb.execute('select 1 where false').pl()
shape: (0, 1)
┌─────┐
│ 1   │
│ --- │
│ i32 │
╞═════╡
└─────┘
>>> 'pandas' in sys.modules
True
```

```python
>>> import sys, duckdb
>>> 'pandas' in sys.modules
False
>>> duckdb.execute('select 1').pl()
shape: (1, 1)
┌─────┐
│ 1   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
└─────┘
>>> 'pandas' in sys.modules
False
```

### Issue description

Creating polars series from empty arrow chunked array loads pandas. Since the array is empty, skipping the empty `pa.array([], array.type)` in

https://github.com/pola-rs/polars/blob/815732bc0f5bc06e07f3a995c164fa87e3c53ce8/py-polars/polars/utils/_construction.py#L242-L243

might help with optimizing app startup time.

### Expected behavior

Creating series from empty arrow array does not load pandas.

### Installed versions

<details>

--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Windows-10-10.0.19044-SP0
Python:               3.12.2 (main, Feb  7 2024, 21:34:59) [Clang 18.1.0rc ] 64 bit (AMD64) with MSC v.1936 CRT]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

</details>

**Comment by char101** [comment]
`duckdb.execute(...).pl()` creates a polars dataframe from arrow table. `duckdb` itself is just for convenience here. The problems is in the `[]` in `pa.array([], array.type`. Anything other than an `numpy.ndarray` will load pandas:

https://github.com/apache/arrow/blob/a03d957b5b8d0425f9d5b6c98b6ee1efa56a1248/python/pyarrow/array.pxi#L52-L55

**Comment by stinodego** [comment]
I can see if we can avoid calling the pyarrow array constructor in this way, but this issue should really be opened with pyarrow.
