### ISSUE TITLE
Support arthimetic on Python objects

### ISSUE THREAD

**Issue by staadecker** [pola-rs/polars#14568]
### Description

A common behavior for Python objects is to override the __add__ or __mul__ functions to allow multiplying or adding objects together. For example in [this library](https://github.com/Gurobi/gurobipy-pandas) built on-top of Pandas, dataframe columns storing custom Python objects are multiplied together to and then aggregated with .sum() to create optimization models.

Having similar support for multiplying and adding custom Python objects in dataframes would be incredibly helpful.

**Comment by stinodego** [comment]
We will not support this natively, but you can already do this if you want using the various `map` functions together with a UDF:

```python
import polars as pl

df = pl.Series("a", [1, 2, 3], dtype=pl.Object).to_frame()

result = df.select(pl.col("a").map_batches(lambda x: sum(x), agg_list=True))
print(result)
```
```
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 6   │
└─────┘
```
