### ISSUE TITLE
No `null_strategy` in `sum_horizontal` anymore

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#14581]
### Description

There is a `null_strategy` in `sum` but it is missing from `sum_horizontal`.

```python
import polars as pl

df = pl.DataFrame({'a': [1, None], 'b': [2, 3]})
df.with_columns(
    df.sum(axis=1, null_strategy='propagate')
)
```
```
shape: (2, 3)
┌──────┬─────┬──────┐
│ a    ┆ b   ┆ sum  │
│ ---  ┆ --- ┆ ---  │
│ i64  ┆ i64 ┆ i64  │
╞══════╪═════╪══════╡
│ 1    ┆ 2   ┆ 3    │
│ null ┆ 3   ┆ null │
└──────┴─────┴──────┘
```

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.sum_horizontal.html#polars.sum_horizontal

https://github.com/pola-rs/polars/issues/10016

**Comment by stinodego** [comment]
This function never had a null strategy argument to begin with.

Closing in favor of https://github.com/pola-rs/polars/issues/10016

**Comment by stevenlis** [comment]
@stinodego Is there any reason for the inconsistency between this top-level function and the dataframe method?

**Comment by stinodego** [comment]
The reason is that the horizontal expressions are newer and we're not sure yet about the right API.
