### ISSUE TITLE
Add return_dtype in `Expr.cut`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#14580]
### Description

The default data type returned by `Expr.cut` as of version 0.20.9 is `Categorical`. Currently, there is an `Enum` dtype. It might be beneficial to include an argument in the expression to manage the return dtype, especially when `labels` are non-lexical (e.g., Low, Mid, High). Although there is no documentation available for the usage of `Enum` at the moment, I presume these two dtypes also operate differently. Providing users with a choice could be advantageous.

**Comment by stinodego** [comment]
The return dtype will be an Enum: #13038
