### ISSUE TITLE
Wrong polars dtype for empty Series

### ISSUE THREAD

**Issue by Northern-Arc** [pola-rs/polars#14599]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
>>> import polars as pl
>>> ser1 = pl.Series('str', dtype=str)
>>> ser2 = pl.Series('int', dtype=pl.Int32)
>>> print(ser1, ser2)
shape: (0,)
Series: 'str' [null]
[
] shape: (0,)
Series: 'int' [i32]
[
]

### Issue description

According to the API reference, ser1 should have dtype [str] since I have appointed it. Nevertheless, the dtype remains [null]. However, ser2 has the right dtype.

### Expected behavior

>>> import polars as pl
>>> ser = pl.Series('str', dtype=str)
>>> print(ser)
shape: (0,)
Series: 'str' [str]
[
]

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.10
Index type:           UInt32
Platform:             Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.18
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.27
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by JulianCologne** [comment]
hi @Northern-Arc 

native python dtypes are not suppored afaik, you need to use the polars dtypes

- `int` -> `null` BUT
- `pl.Int32` -> `Int32` (you example
- `str` -> `null` BUT
- `pl.String` -> `str`

```python
pl.Series('str', dtype=pl.String)

shape: (0,)
Series: 'str' [str]
[
]
```

**Comment by alexander-beedie** [comment]
> native python dtypes are not suppored afaik, you need to use the polars dtypes

We do actually have a dedicated codepath for the standard python types, but we definitely prefer the more specific polars-native equivalent (as python `int` can't tell you if it's `i8`, `i32`, `u64`, for example).

**Comment by Northern-Arc** [comment]
> hi @Northern-Arc
> 
> native python dtypes are not suppored afaik, you need to use the polars dtypes
> 
>     * `int` -> `null` BUT
> 
>     * `pl.Int32` -> `Int32` (you example
> 
>     * `str` -> `null` BUT
> 
>     * `pl.String` -> `str`
> 
> 
> ```python
> pl.Series('str', dtype=pl.String)
> 
> shape: (0,)
> Series: 'str' [str]
> [
> ]
> ```

Thank you!
