### ISSUE TITLE
Finding length of "len" column results in DuplicateError

### ISSUE THREAD

**Issue by taekeharkema** [pola-rs/polars#14592]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"len": [1, 1, 2, 3]}).group_by("len").len()
```

### Log output

```shell
DuplicateError: column with name 'len' has more than one occurrences

Error originated just after this operation:
DF ["len"]; PROJECT */1 COLUMNS; SELECTION: "None"
```

### Issue description

You cannot take the length of groups determined by a column which itself is named `len`. The same, incidentally, is true for the old `count` column. Sometimes, in data analysis, this comes in handy as you want to summarise occurrences of counts.

### Expected behavior

It would be nice to have either a parameter determining the name of the `len`-column.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.10
Index type:           UInt32
Platform:             Linux-5.15.0-1054-azure-x86_64-with-glibc2.10
Python:               3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the question

you can do `.agg(pl.len().alias(<your name goes here>))`
