### ISSUE TITLE
`from_pandas` incorrect type for all null columns

### ISSUE THREAD

**Issue by Usernamelesss** [pola-rs/polars#14601]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.from_pandas(pd.DataFrame({"A": [None]}))
# shape: (1, 1)
# ┌──────┐
# │ A    │
# │ ---  │
# │ str  │ # <- str ???
# ╞══════╡
# │ null │
# └──────┘
```

### Issue description

As described [here](https://github.com/pola-rs/polars/issues/14326#issuecomment-1952977696) and thanks to the @cmdlineluser reply looks like that for an all null column polars chose the wrong type when converting from pandas

### Expected behavior

The expected output should be the same we obtain with a polars DataFrame

```python
pl.DataFrame({"A": [None]})
# shape: (1, 1)
# ┌──────┐
# │ A    │
# │ ---  │
# │ null │
# ╞══════╡
# │ null │
# └──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Linux-5.15.0-92-generic-x86_64-with-glibc2.31
Python:               3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]

```

</details>

**Comment by stinodego** [comment]
This is a conscious design choice. See the linked PR for discussion. Ritchie's response:

> I am not sure here. Why not `Object` type then? We have one.
> 
> I am also not sure because often pandas strings are objects. Pandas is ambiguous. We cannot fix that so we have to be a little more lenient here. You will now fix #14601 and for that fix, tons of other issues will open about strings not being correctly read.

To avoid the issue  in the original description, explicitly specify a schema if you are working with non-string object columns that could be empty, e.g.:

```python
import polars as pl
import pandas as pd

pd_df = pd.DataFrame({"A": [None]})
df = pl.from_pandas(pd_df, schema_overrides={"A": pl.Time})
print(df)
```
```
shape: (1, 1)
┌──────┐
│ A    │
│ ---  │
│ time │
╞══════╡
│ null │
└──────┘
```
