### ISSUE TITLE
partition_by on LazyFrame

### ISSUE THREAD

**Issue by Addiictet** [pola-rs/polars#14603]
### Description

Hey everyone,

I am currently facing the use-case of loading a large amount of data and having to save it to separate parquet files. I want to do this lazy with streaming, but I as of now there is no way to use partition_by on a LazyFrame.

Is there a way to make this happen?  
Ideally, I could write `pl.scan_parquet("data/*.parquet").partition_by("category").sink_parquet("newdata/{}.parquet")`, 
where the pattern in `sink_parquet` is filled with the partition keys.

**Comment by cmdlineluser** [comment]
`.partition_by` probably has an unfortunate name in this sense as it is returns a Python list (or dict) and is unrelated to *"hive partitioning"*.

I think what you're asking is for `sink_parquet` to support hive partitioning?

The closest discussion I can seem to find is:

- #11500

Hopefully someone with more knowledge on the topic can correct me here.

**Comment by Addiictet** [comment]
Thanks a lot!

That's basically it, although the other discussion does not seem to focus on the lazy aspect, which is the most important for me.

**Comment by stinodego** [comment]
Closing in favor of #11500

**Comment by qiuxiaomu** [comment]
#15960 has mentioned a `partition_by` as well. Reading documentations of both `PyArrow` and `Polars`, in particular `write_table`, `write_to_dataset` and `write_dataset` for Arrow, `write_parquet` and `sink_parquet` for Polars, I see that `partition_by` seemed to be a `Polars` concept (which is still subject to change); on the other hand, what this issue and #15960 wanted, probably was a way to access `pyarrow_options` on `sink_parquet`, which in turn provides `partition_cols`. This `partition_cols`, is actually the feature requested. We basically hope there's automatic directory handling in correspondence with column names specified; for cases such as a dataframe coming with "name", "date", a series of values at hourly rate, this feature would save the blob into `base_dir`/`name`/`date`/data.parquet.

**Comment by coastalwhite** [comment]
The original feature request is covered by partitioning sinks https://docs.pola.rs/api/python/version/1/reference/api/polars.PartitionByKey.html
