### ISSUE TITLE
df.assert_schema(expected_schema)

### ISSUE THREAD

**Issue by KDruzhkin** [pola-rs/polars#14620]
### Description

I often write long chains of transformations, e.g.:

```python
result_df = (
    pl.scan_csv(...)
    .filter(...)
    .join(...)
    .select(...)
    .group_by(...).agg(...)
    .group_by(...).agg(...)
    .with_columns((pl.col(...) * pl.col(...)).alias(...))
    ...
)
```

Such chains are elegant, but hard to reason about (_"What is the shape of the data on line 7?"_).

To make it more readable and error-proof, I would like to have **assertions** in the middle of the chain.

```python
result_df = (
    pl.scan_csv(...)
    ...
    .assert_schema({"a": pl.UInt32, "b": String, ...})  # <==
    ...
)
```

**Comment by JulianCologne** [comment]
yes, agree!
Have already shared by idea about something more general `.assert` / `.expect` here: https://github.com/pola-rs/polars/issues/11064#issuecomment-1717191983

Would love to see: 

### `.assert(...)` or `.expect`

- assert that some conditions are met like: datatypes, max < x, min > 0, schema = ...
- with configuration options to turn on for "testing" (full evalutation) or "production" (ignore assertions)

### `.inspect(...)`

- allow printing / debugung current df values 
- `df.select(...).with_columns(...).inspect(lambda df: print(df.schema)).select(...).inspect(lambda df: print(df.describe()).group_by...`

**Comment by KDruzhkin** [comment]
Interesting.

But schemas are different from other properties. You can get the schema of a LazyFrame without collecting it.

The more general `assert` and `inspect` methods of LazyFrames would only add delayed actions.

**Comment by KDruzhkin** [comment]
Wrote #16311 specifically about dropping/forgetting/ignoring values that are used only for assertions.

**Comment by stinodego** [comment]
You can already do this using `pipe`:

```python
import polars as pl

def assert_schema(
    lf: pl.LazyFrame, schema: dict[str, pl.PolarsDataType]
) -> pl.LazyFrame:
    if lf.schema != schema:
        msg = (
            "Wrong LazyFrame schema:\n"
            f"• expected: '{schema}',\n"
            f"• observed: '{dict(lf.schema)}'."
        )
        raise AssertionError(msg)
    return lf

lf = pl.LazyFrame({"a": [1, 2, 3], "b": [4.0, 5.0, 6.0]})
lf.select("a").pipe(assert_schema, schema={"a": pl.Float64})
```
```
AssertionError: Wrong LazyFrame schema:
• expected: '{'a': Float64}',
• observed: '{'a': Int64}'.
```

I don't think this is worth adding to the Polars API.

For a more general 'assertion / raising' utility, please see #11064

**Comment by KDruzhkin** [comment]
> You can already do this using `pipe`:

Nice. I somehow missed `pipe`.

Maybe, it deserves a more prominent place in the docs? The user guide mentions it only in passing ([Pipe littering](https://docs.pola.rs/user-guide/migration/pandas/#pipe-littering): _"Don't"_).
