### ISSUE TITLE
Initialize `LazyFrame` from `LazyFrame`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#14626]
### Description

From a DataFrame you can initialise a DataFrame:
```python
pl.DataFrame(pl.DataFrame()) # works

```
But it doesn't work with LazyFrame:
```python
pl.LazyFrame(pl.LazyFrame())
# TypeError: DataFrame constructor called with unsupported type 'LazyFrame' for the `data` parameter
```

My final use case is for subclassing LazyFrame ( I know that this subclassing will not persist with polars manipulation but that's what I want)

```python
class FreshLazyFrame(pl.LazyFrame):
    
    def __init__(
        self,
        *args,
        name: str,
        **kwargs
    ):
        super().__init__(*args, **kwargs)
        self.name = name
        
    def _repr_html_(self):
        return f"<h1>{self.name}</h1>" + super()._repr_html_()

display(FreshLazyFrame(pl.DataFrame(), name = 'MyLazyFrame')) # works
display(FreshLazyFrame(pl.LazyFrame(), name = 'MyLazyFrame')) # fails
```
But I think the feature request is more broad than is specific use case. And being able to do `pl.LazyFrame(ldf)` is convenient

**Comment by stinodego** [comment]
We could easily support this. Not sure if we should, though. I'm trying to think of a reason why this would be a bad idea, but I've got nothing so far.

**Comment by stinodego** [comment]
The issue with this is: what should the other parameters do? If I specify a `schema`, what happens? Or `schema_overrides`? Should we cast the LazyFrame? Now we have to implement constructor logic specifically for LazyFrames.

I don't think it's a good idea to allow this.

**Comment by gab23r** [comment]
If it adds a lot of complexity, I imagine that we would need a better use case than this one.

In the meantime, I followed your guidance concerning subclasses here https://github.com/pola-rs/polars/issues/2846
It works well.

**Comment by stinodego** [comment]
> In the meantime, I followed your guidance concerning subclasses here https://github.com/pola-rs/polars/issues/2846#issuecomment-1711799869
> It works well.

Good to hear. In that case, I'll close this as not planned for now. I may change my mind if there is a compelling use case.
