### ISSUE TITLE
LazyFrame.deserialize() should document the security implications

### ISSUE THREAD

**Issue by douglas-raillard-arm** [pola-rs/polars#14623]
### Description

Since LazyFrame.deserialize() can end up calling into pickle/cloudpickle, it makes it unsafe to use on non-trusted input, so it would be good if it stated it similarly to the Python doc:

### Link

https://docs.python.org/3/library/pickle.html
https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.deserialize.html

**Comment by ritchie46** [comment]
Can you make a PR?

**Comment by douglas-raillard-arm** [comment]
I'm following my employer's legal process to be able to contribute to polars, after that I should be able to make a PR. I'm currently discovering the API and exploring how I can use it best for our [use case](https://gitlab.arm.com/tooling/lisa), hence all the issues I opened recently :)

**Comment by douglas-raillard-arm** [comment]
Here we go: https://github.com/pola-rs/polars/pull/15282
