### ISSUE TITLE
Very high incremental compile time and binary size using basic polars CsvReader

### ISSUE THREAD

**Issue by mr-pascal** [pola-rs/polars#14640]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let file_name = "mycsv.csv";
    polars::io::csv::CsvReader::from_path(file_name)?
        .infer_schema(Some(10))
        .with_try_parse_dates(true)
        .has_header(true)
        .finish()?;

    Ok(())
}

```
```toml
[package]
name = "rust-datascience"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.37.0", features = [] }
```

### Issue description

**EDIT: I am talking about incremental compile time here, NOT about a clean one. And the main issue is the high incremental compile time, not the binary size**

Hey guys,

Using the minimal example provided above, it appears that the resulting binary, running `cargo build,` is **500MB** in size, and the compile time is 10-20 seconds. (used CPU: AMD® Ryzen 7 5700u with radeon graphics × 16, so not that slow)
While this could also be a question, it appears as a bug to me when I follow the documentation, and suddenly, there is this tremendous binary created for just reading a CSV file.

When I don't add the `use polars::prelude::*;` and remove the `.finish()?;` line of code, the binary is still 430 MB.

### Expected behavior

It doesn't take 10-20 seconds, but at most one or so to rebuild (incremental) the application after adding a print statement.
At most a couple of megabytes are added to the binary instead of 500 MB for only using a CSVReader.

### Installed versions

<details>

rustc:	rustc 1.78.0-nightly (3406ada96 2024-02-21)
Host: x86_64-unknown-linux-gnu
Target: x86_64-unknown-linux-gnu

polars = { version = "0.37.0", features = [] }

</details>

**Comment by mr-pascal** [comment]
@kszlim thanks for the tip, but especially for development, the binary size isn't my main concern, but having a 10-20 sec compile time for 5 LoC that does almost nothing is not acceptable

**Comment by ritchie46** [comment]
> @kszlim thanks for the tip, but especially for development, the binary size isn't my main concern, but having a 10-20 sec compile time for 5 LoC that does almost nothing is not acceptable

Are you serious? It compiles the whole reader and all data-types involved. It also returns a `DataFrame` with the support of a `DataFrame`. Polars' CSV reader doesn't exist in a vacuum.

And please tone it down a little with "ridiculous". You don't have to use Polars.

**Comment by mr-pascal** [comment]
I am sorry if there is a misunderstanding here, but I am NOT talking about a "clean" of "full" compile here.
I am talking about an incremental compile, all dependencies compiled already. A full/clean build is absolutely fine that it takes quite a while when dependencies have to be compiled.

Easy example: 
1. I do a cargo build of the full program (the above 5 LoC)
2. I add a print statement
3. I hit cargo build again -> it takes 10-20 seconds, just because of the added print statement

**Comment by stinodego** [comment]
I don't think there is any concrete actions for us to take here.
