### ISSUE TITLE
raise when date_range would return Date but time_zone was specified

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#14656]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Correct:

```python
>>> pl.date_range(datetime.date(2000, 1, 1), datetime.date(2000, 1, 3), datetime.timedelta(days=1.5), eager=True, time_zone='America/New_York')
shape: (2,)
Series: 'literal' [datetime[μs, America/New_York]]
[
        2000-01-01 00:00:00 EST
        2000-01-02 12:00:00 EST
]
```

Incorrect:

```python
>>> pl.date_range(datetime.date(2000, 1, 1), datetime.date(2000, 1, 3), datetime.timedelta(days=2), eager=True, time_zone='America/New_York')
shape: (2,)
Series: 'literal' [date]
[
        2000-01-01
        2000-01-03
]
```

### Issue description

When the output of `pl.date_range()` is a date (rather than a datetime), the time zone is ignored (since dates don't support time zones).

### Expected behavior

The output should be a datetime with the specified timezone, not a date. Or at a minimum, there should be an error when time zones are specified and the output would be a date.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.9
Index type:           UInt32
Platform:             Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by mcrumiller** [comment]
In your first example, you're using `date_range` to construct a `Datetime` series, which is [explicitly warned against](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.date_range.html) in the docs:

> **Deprecated since version 0.19.3**: In a future version of Polars, `date_range` will always return a `Date`. Please use [`datetime_range()`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.datetime_range.html#polars.datetime_range) if you want a `Datetime` instead.

Both of your cases look correct to me. In the first case, New York uses EST, and your output is labeled EST.

The second "incorrect" case also look correct to me. When converting from datetime to date, the time zone is completely irrelevant: Dec 31 at 23:59 is still Dec 31 regardless of what time zone you're in. You're starting on Jan 1, incrementing by 2 days at a time, up until the 3rd. So you get the 1st and the 3rd.

**Comment by Wainberg** [comment]
@MarcoGorelli sounds good!

**Comment by stinodego** [comment]
This will all be taken care of in the scheduled deprecation. We should not make changes to deprecated functionality if not absolutely necessary.
