### ISSUE TITLE
Rust streaming feature fails to compile

### ISSUE THREAD

**Issue by michaeleisel** [pola-rs/polars#14654]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

After adding the streaming feature to polars 0.37.0, I get the error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `futures`
   --> /home/meisel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-pipe-0.37.0/src/executors/sources/parquet.rs:260:43
    |
260 |                         .block_on(async { futures::future::try_join_all(init_iter).await })?;
    |                                           ^^^^^^^ use of undeclared crate or module `futures`

error: aborting due to previous error
```

Here are my imports in Cargo.toml:
```
polars = { version = "0.37.*", features = ["lazy", "parquet", "ndarray", "async", "is_in", "polars-ops", "streaming"] }
polars-io = { version = "0.37.*", features = ["lazy", "parquet"] }
```

From the code in the file that the error reports, it looks like it just didn't import futures.

### Issue description

-

### Expected behavior

It should compile

### Installed versions

<details>

I don't know what a "feature gate" is, but I've listed the features of the polars crate above

</details>

**Comment by ritchie46** [comment]
You can add the `cloud` feature to resolve it for now.
