### ISSUE TITLE
pathological parquet reading performance.

### ISSUE THREAD

**Issue by jerome-f** [pola-rs/polars#14657]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
# pandas block
import glob as gb
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import os,sys

a=sys.argv[1]
df = pd.concat([pd.read_parquet(f"{a}_chunk_{i}.parquet") for i in range(len(gb.glob(f"{a}_chunk_*.parquet")))])

df.to_parquet(f"df-{a}.parquet")
```

```
# polars block
import glob as gb
import polars as pl
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import os,sys

a=sys.argv[1]
df = pl.concat([pl.read_parquet(f"{a}_chunk_{i}.parquet") for i in range(len(gb.glob(f"{a}_chunk_*.parquet")))])

df.write_parquet(f"df-{a}.parquet")
```

### Log output

```shell
The above code block executed in < 15 mins on pandas each parquet file chunk is ~4GB and took 2+ hours without output on polars. When I looked at the resource usage the process was using only one thread and just occupying memory with status "S".
```

### Issue description

read write I/O slower than pandas

### Expected behavior

polars should be way faster than pandas. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.10
Index type:           UInt32
Platform:             Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
Python:               3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  0.10.0
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.15.3
fsspec:               2023.12.2
gevent:               23.9.0.post1
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              13.0.0
pydantic:             2.6.1
pyiceberg:            0.6.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.27
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
```

</details>

**Comment by mcrumiller** [comment]
Is there any way you can provide some sample files (by either a link or write something to generate similar files)? A working test makes diagnosing the issue much easier.

**Comment by ritchie46** [comment]
You are benchmarking pyarrow here, not pandas.

Have you got a MWE? Otherwise there is nothing we can do here.

**Comment by jerome-f** [comment]
@ritchie46 I am not necessarily benchmarking. And if it is indeed pyarrow then polars is getting stuck at some point getting a response from pyarrow library. Unfortunately I am not at liberty to share the same parquet file. I will try to generate one. The file has 32 columns with mixed type and long strings. (another possibility is that polars tried to convert string columns to category and got stuck there, haven't tried presecifying column datatype ).  There is no MWE the process is stuck on a single core for a while waiting for another process to respond.

**Comment by ritchie46** [comment]
How much difference is there? If it is within a reasonable bound there is no issue here. polars has a native parquet reader that has different performance charactereristics from that of pyarrow.

**Comment by jerome-f** [comment]
pandas takes 85.62468147277832 seconds to read the file,

**Comment by MarcoGorelli** [comment]
Thanks for the report @jerome-f - if it's not possible to share the file, perhaps you could share the shape and schema?

**Comment by ritchie46** [comment]
Could you maybe send the file privately to me? It can be a ton of things.

Or if you have created the file yourself, maybe you can obfuscate data?

**Comment by jerome-f** [comment]
@nameexhaustion Thanks for this essentially my parquet file has ~4 million records 8 columns are long strings and it is easy to see even with 40,000 records the performance lags in native parquet reader.

**Comment by ritchie46** [comment]
I expect this is due to our string type refactor. This seems to be accidentally quadratic. Taking a look.

**Comment by ritchie46** [comment]
![image](https://github.com/pola-rs/polars/assets/3023000/e490f0cf-60d9-476a-88c9-f3ac9ea54a3b)

**Comment by ritchie46** [comment]
Found the culprit. Fix coming up. This likely fixes more perf issues since the new string type. We accidentally validate all data every parquet page.

**Comment by ritchie46** [comment]
Timings after #14705 

```
shape: (9, 3)
┌────────┬─────────────┬──────────────┐
│ n_rows ┆ polars_time ┆ pyarrow_time │
╞════════╪═════════════╪══════════════╡
│ 1000   ┆ 0.077893    ┆ 0.228986     │
│ 5000   ┆ 0.22578     ┆ 0.316295     │
│ 10000  ┆ 0.433595    ┆ 0.635857     │
│ 15000  ┆ 0.626575    ┆ 0.981144     │
│ 20000  ┆ 0.836397    ┆ 1.317413     │
│ 25000  ┆ 1.054086    ┆ 1.684996     │
│ 30000  ┆ 1.277393    ┆ 1.894178     │
│ 35000  ┆ 1.499118    ┆ 1.941129     │
│ 40000  ┆ 1.713368    ┆ 2.676958     │
└────────┴─────────────┴──────────────┘

```
