### ISSUE TITLE
`.over(columns).flatten()` does not work as expected when the groups are not clustered together.

### ISSUE THREAD

**Issue by aerjayc** [pola-rs/polars#1467]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.9.12

#### What operating system are you using polars on?

CentOS Linux 7 (Core)

#### Describe your bug.

`.over(columns).flatten()` does not work as expected when the groups are not clustered together.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

# Create dataset where groups are not all clustered together
df = pl.DataFrame({
    'group': ['a', 'b', 'a', 'b'],
    'value': [1.0, 2.0, 3.0, 4.0]
})

# Get the reverse order of each group, though
# the same issue occurs with other operations
# like .cumsum()
df.with_column(
    pl.col('value')
      .reverse()
      .over('group')
      .flatten()
      .suffix('_reverse')
)
```

#### What is the actual behavior?

Suddenly group `'b'` has `1` and `'a'` has `4`:
```
shape: (4, 3)
┌───────┬───────┬───────────────┐
│ group ┆ value ┆ value_reverse │
│ ---   ┆ ---   ┆ ---           │
│ str   ┆ f64   ┆ f64           │
╞═══════╪═══════╪═══════════════╡
│ "a"   ┆ 1     ┆ 3             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "b"   ┆ 2     ┆ 1             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "a"   ┆ 3     ┆ 4             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "b"   ┆ 4     ┆ 2             │
└───────┴───────┴───────────────┘
```

#### What is the expected behavior?

Here's what I expected it to do:
```python
df.groupby('group').agg([
    pl.col('value'),
    pl.col('value')
      .reverse()
      .suffix('_reverse')
]).explode(['value', 'value_reverse'])

shape: (4, 3)
┌───────┬───────┬───────────────┐
│ group ┆ value ┆ value_reverse │
│ ---   ┆ ---   ┆ ---           │
│ str   ┆ f64   ┆ f64           │
╞═══════╪═══════╪═══════════════╡
│ "b"   ┆ 2     ┆ 4             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "b"   ┆ 4     ┆ 2             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "a"   ┆ 1     ┆ 3             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "a"   ┆ 3     ┆ 1             │
└───────┴───────┴───────────────┘
```
Doing it like this is less elegant though, and you can't easily do things like adding a `.reverse().over('group')`-ed column with another column.

Also, if the groups are clustered together (by e.g. sorting), we get the expected result:
```python

df.sort('group').with_column(
    pl.col('value')
      .reverse()
      .over('group')
      .flatten()
      .suffix('_reverse')
)

shape: (4, 3)
┌───────┬───────┬───────────────┐
│ group ┆ value ┆ value_reverse │
│ ---   ┆ ---   ┆ ---           │
│ str   ┆ f64   ┆ f64           │
╞═══════╪═══════╪═══════════════╡
│ "a"   ┆ 1     ┆ 3             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "a"   ┆ 3     ┆ 1             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "b"   ┆ 2     ┆ 4             │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "b"   ┆ 4     ┆ 2             │
└───────┴───────┴───────────────┘
```

I wasn't sure if I should've submitted this as a bug or as a feature request, since essentially I'm requesting for a Group-aware `.flatten()` method, or like an optional argument in `.over()` for this, like `.over(flatten=True)`. But I wasn't sure if this was expected behavior so I raised it as a bug instead.

**Comment by ritchie46** [comment]
Yes this is expected behavior. The right way, is to first sort on the column you want to flatten. I have been thinking about a way to make it also work with randomized groups, but I haven't yet come up with a solution that would do that efficiently. And I am also not certain if that behavior should be the same as `flatten` for consistency.
