### ISSUE TITLE
add regex to `col("..").exclude("..")`

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1468]
Would it be possible to allow `col()` expressions in `.drop()`?

```python
import polars as pl
from polars import col

df = pl.DataFrame(
    {'x': range(3),
     'y': range(3),
     'z': range(3)}
)

df.drop(col('x'))

df.drop([col('x'), col('y')])
```

**Comment by ritchie46** [comment]
I am not opposed to the idea, I am just dumping my doubts atm.

As of yet, I don't see an added benefit, as the type `Expr` is less clear than a `str`. What would it mean if we pass `pl.lit("foo")` or `col("x").rank() + 1`? These are valid expressions, but are not really useful here. So we would need to find the column names I think?

From a lazy API point of view, I want to discourage `drop` usage in favor of `select` as this give me as a query optimizer the information of the columns you certainly do want, so I assume I can drop the rest for you.

**Comment by markfairbanks** [comment]
The reason for this feature request is I was looking to be able to do something like this:

```python
import polars as pl
from polars import col

df = pl.DataFrame({'x1': range(3), 'x2': range(3), 'y': range(3)})

df.drop(col("^x.*$"))
```

**Comment by markfairbanks** [comment]
Another possible option might be to allow regex in `.exclude()`?

```python
import polars as pl
from polars import col

df = pl.DataFrame({'x1': range(3), 'x2': range(3), 'y': range(3)})

df.select(col("*").exclude("^x.*$"))
```

**Comment by ritchie46** [comment]
> Another possible option might be to allow regex in .exclude()?

That one makes sense. Let's add that.

For the time being, the exclude accepts also a list, so you could do a list comprehension on `df.columns`.

**Comment by markfairbanks** [comment]
And an extension of this - any thoughts on adding `pl.exclude()` as shorthand for `col('*').exclude()`?

```python
import polars as pl
from polars import col

df = pl.DataFrame({'x1': range(3), 'x2': range(3), 'y': range(3)})

df.select(pl.exclude('x1'))
```

**Comment by ritchie46** [comment]
> And an extension of this - any thoughts on adding pl.exclude() as shorthand for col('*').exclude()?

See #1472
