### ISSUE TITLE
how to support polars in pycaret?

### ISSUE THREAD

**Issue by celestinoxp** [pola-rs/polars#14697]
### Description

I have a question that seems simple, but after I start thinking about it, it seems to be a little complicated...

The well-known Pycaret package only uses Pandas... but with the growing popularity of Polars, I'm starting to think about opening a pull-request to support Polars... the question is how this should be done....

there are many pd.DataFrame(...) lines, and I can't use an if condition to check the dataset type to know whether I should use pd.DataFrame(...) or pl.DataFrame(...)

Does anyone know how to do it? Any ideas?

![image](https://github.com/pola-rs/polars/assets/41735311/61446793-5220-42b4-990b-b523238a72f5)

**Comment by stinodego** [comment]
It's great that you're considering adding support for Polars in pycaret. However, our issue tracker is not the place to discuss this. You could try our [Discord](https://discord.gg/4UfP5cfBE7).
