### ISSUE TITLE
Add aggregation function to convert groups of identical values to that value

### ISSUE THREAD

**Issue by kalekundert** [pola-rs/polars#14692]
### Description

Consider a data frame with two columns that vary together:
```
>>> df = pl.DataFrame({'a': [1, 1, 2, 2], 'b': ['a', 'a', 'b', 'b']})
>>> df
shape: (4, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
│ 1   ┆ a   │
│ 2   ┆ b   │
│ 2   ┆ b   │
└─────┴─────┘
```
More specifically, consider a data frame where two columns *should* vary together like this, but might not due to errors in the underlying data set, or perhaps just in the programmer's understanding of the data set.  When grouping by one such column, what I'd like is a way to aggregate the other column such that:

- If every value in the group is the same, the result is that value.
- If not every value in the group is the same, an exception is raised.

I can't figure out a way to get this behavior with the current API, although of course I could be missing something.  I'll note that if you can be sure that the two columns vary together, then it's easy to do this aggregation using `.first()`.  But this approach will silently hide errors if the two columns don't always vary together, so it strikes me as dangerous.
```
>>> df.group_by('a').agg(pl.col('b').first())
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
│ 2   ┆ b   │
└─────┴─────┘
```

I'd like to propose two different ways of getting the behavior I described above:

- Add `Expr.unanimous()`: This function would directly implement the logic above: it'd check if every row in the column has the same value, then either return that value or raise an error.  There could also be a flag that causes `unanimous()` to return null instead of raising.
  ```
  >>> df.group_by('a').agg(pl.col('b').unanimous())
  ```

- Add `Expr.list.one()` and `Expr.list.only()`: These functions would check that a list has at most one element, then convert that element into a scalar.  `one()` would require the list to have exactly one element, while `only()` would return null for empty lists.  Only `one()` is strictly needed for the issue I'm proposing here, but these two functions are so complementary that I don't think it'd make sense to add one without the other.
  ```
  >>> df.group_by('a').agg(pl.col('b').unique().list.one())
  ```

Let me know if there's support for adding any (or all) of these functions.  I don't know much rust, but if this is something that wouldn't be too hard to do, I'd be willing to try making a PR.

**Comment by stinodego** [comment]
I think you're just looking for `DataFrame.unique`:
https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.unique.html

If not, please provide an example where this method does not fulfill your requirements.

**Comment by kalekundert** [comment]
Sorry I didn't make this more clear.  I want to use this method in a group-by context, where there might be other columns being aggregated in different ways, so it's not enough to just find unique rows:
```
>>> df = pl.DataFrame({'a': [1, 1, 2, 2], 'b': ['a', 'a', 'b', 'b'], 'c': [2, 4, 6, 8]})
>>> df
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 2   │
│ 1   ┆ a   ┆ 4   │
│ 2   ┆ b   ┆ 6   │
│ 2   ┆ b   ┆ 8   │
└─────┴─────┴─────┘
>>> df.group_by('a').agg(pl.col('b').unanimous(), pl.col('c').mean())
shape: (2, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ f64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 3.0 │
│ 2   ┆ b   ┆ 7.0 │
└─────┴─────┴─────┘
```

Here's an example of where the method would raise.  Not that the last value in the 'b' column is now `'c'`:
```
>>> df = pl.DataFrame({'a': [1, 1, 2, 2], 'b': ['a', 'a', 'b', 'c'], 'c': [2, 4, 6, 8]})
>>> df
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 2   │
│ 1   ┆ a   ┆ 4   │
│ 2   ┆ b   ┆ 6   │
│ 2   ┆ c   ┆ 8   │
└─────┴─────┴─────┘
>>> df.group_by('a').agg(pl.col('b').unanimous(), pl.col('c').mean())
Traceback (most recent call last):
  ...
IntegrityError: found different values in column 'b'
```

**Comment by MarcoGorelli** [comment]
`Series.item` reduce the dimension by 1 with a check on the shape

Maybe `list.item` would make sense here then?

So you'd get
```
In [3]: df
Out[3]:
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1]       │
│ [2]       │
└───────────┘

In [4]: df.select(pl.col('a').list.item())
Out[4]:
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```
and
```
In [6]: df
Out[6]:
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1]       │
│ [2, 3]    │
└───────────┘

In [7]: df.select(pl.col('a').list.item())

ValueError: can only call 'list.item()' if the list is of length 1 (list is of length 2)
```

**Comment by kalekundert** [comment]
Yeah, I think that's the same as the `list.one` function I proposed above, perhaps with a more consistent name.

I think it'd be nice to add all of the functions I proposed, but a function like that would be sufficient.

**Comment by cmdlineluser** [comment]
With regards to raising, this may be relevant:

> the problem is that such a raise operator blocks most optimizations

ref: https://github.com/pola-rs/polars/issues/11064#issuecomment-1715196959

The null variation could currently be done with when/then

```python
df.group_by('a').agg(
   pl.when(pl.col('b').n_unique() == 1)
     .then(pl.col('b').first()),
   pl.col('c').mean()
)

# shape: (2, 3)
# ┌─────┬──────┬─────┐
# │ a   ┆ b    ┆ c   │
# │ --- ┆ ---  ┆ --- │
# │ i64 ┆ str  ┆ f64 │
# ╞═════╪══════╪═════╡
# │ 1   ┆ a    ┆ 3.0 │
# │ 2   ┆ null ┆ 7.0 │
# └─────┴──────┴─────┘
```

**Comment by stinodego** [comment]
> The null variation could currently be done with when/then

This is the way to go for now.

For the raising behavior, this can be discussed further in https://github.com/pola-rs/polars/issues/11064
Closing in favor of that issue.
