### ISSUE TITLE
Weakref to LazyFrame/DataFrame/Series is broken

### ISSUE THREAD

**Issue by douglas-raillard-arm** [pola-rs/polars#14726]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import weakref
import polars as pl

weakref.ref(pl.LazyFrame())
weakref.ref(pl.DataFrame())
weakref.ref(pl.Series())
```

### Log output

```shell
Traceback (most recent call last):
  File "testweakref.py", line 4, in <module>
    weakref.ref(pl.LazyFrame())
TypeError: cannot create weak reference to 'LazyFrame' object
```

### Issue description

The polars release 0.20.11 started using the `__slots__` mechanism. However, this breaks the weakref module unless a `__weakref__` slot is explicitly added:

> When __slots__ are defined for a given type, weak reference support is disabled unless a '__weakref__' string is also present in the sequence of strings in the __slots__ declaration. See [__slots__ documentation](https://docs.python.org/3/reference/datamodel.html#slots) for details.

https://docs.python.org/3/library/weakref.html

### Expected behavior

The snippet should run without raising any exception

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.11
Index type:           UInt32
Platform:             Linux-5.15.0-92-generic-x86_64-with-glibc2.29
Python:               3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.4
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by mcrumiller** [comment]
Is this a concern for you, or did you happen to notice it? I ask because it's not expected that a python object support weak references out of the box: lists and dicts don't, for example.

**Comment by douglas-raillard-arm** [comment]
I merely noticed it, but some people might be interested in e.g. building `WeakValueDictionary` with polars type as values to implement some sort of cache. I almost ended up doing so to trigger custom code upon deallocation (unlinking the backing parquet file), but then I realized that it wouldn't propagate to `LazyFrame` derived from the initial one, so instead I used `.map_batches()` to attach a custom object with `def __call__(self, x): return x` and registered that object that in a `WeakSet`. This way I can use an atexit handler to cleanup everything in that `WeakSet` in case `__del__` did not run, which unfortunately is what happens for global variables (prevalent in jupyterlab notebook). 

On Python 3.8, adding the `__weakref__` slot makes a `pl.DataFrame` go from 40 to 48 bytes.

**Comment by m1hawkgsm** [comment]
Hi! Posting here since I do in fact have a concern where this breaks behavior:

I was trying to use Altair to make charts with polars dataframes; for larger dataframes, Altair relies on VegaFusion, which uses weak references. As a result of the `0.20.11` change, I can't use Altair with polars (or at least, with large dataframes).  Link to issue [here](https://github.com/altair-viz/altair/issues/3349).

I'm not sure what the implications of adding this support are (seems simple?), or if there's suggested alternatives.

**Comment by douglas-raillard-arm** [comment]
It turns out that I plan on using weakref for real to "attach" some metadata to a LazyFrame. My main use cases are:
* Let client code get the name of the event that the DataFrame contains
* Have a way to internally track whether a LazyFrame is backed by a DataFrame or by a parquet file. If it is backed by a DataFrame, I need to serialized it to parquet instead of .serialize() as JSON serialization of a large data blob would be very inefficient. If however the LazyFrame is already backed by a parquet file, I can just serialize() the logical plan (cheap) and let it reference the already-existing parquet.

In both cases, it's a best effort basis until I can implement those better (with custom attributes for the name and by inspecting the logical plan from python without having to serialize()) so I don't expect the metadata to stay attached after manipulations of the LazyFrame

**Comment by henryharbeck** [comment]
Hi @stinodego @douglas-raillard-arm 
I think this issue can be closed now.

The `__slots__` PR was reverted (https://github.com/pola-rs/polars/pull/14857) and the repro no longer raises.
