### ISSUE TITLE
Allow converting unknown values to `null` in `pl.Enum`

### ISSUE THREAD

**Issue by TimonKnigge** [pola-rs/polars#14725]
### Description

When I call `.cast(pl.Enum(my_categories))`, there is an error when we encounter an unknown value. I think it would be helpful to allow something like `.cast(pl.Enum(my_categories, missing_policy='set_to_null'))`. Which converts any unknown encountered value to null (open to other policies as well).

Context is that I have some categorical data in one dataframe, and I may regularly want to join it with some other table to look up values associated with this categorical. My first dataframe never changes so I would like to use an enum rather than a categorical, but my second dataframe may contain new values (which I'm happy to map to null). But currently I can't really do this join without first converting the column in the second dataframe to the relevant enum, which errors out.

**Comment by mcrumiller** [comment]
To clarify, you mean that if you cast a series `s` to an enum, and `s` contains values that are not in the enum's set of categories, then those values should be converted to null? I like this idea. I think a `default` parameter or something of the sort would be nice, which would also allow outside values to take on a default value.

**Comment by TimonKnigge** [comment]
Maybe what I wrote above isn't ideal because maybe this 'missing policy' thing shouldn't be a property of the enum, but of the computation (the cast or otherwise).

**Comment by c-peters** [comment]
Similarly to underflows/overflows we could set the values to `null` if the strict parameter in `cast` is set to false.
