### ISSUE TITLE
Reconsider the use of `Self` in type annotations of `DataFrame` and `LazyFrame` 

### ISSUE THREAD

**Issue by borchero** [pola-rs/polars#14741]
### Description

# Background

Currently, many methods for `polars.DataFrame` and `polars.LazyFrame` return `Self` to indicate that an instance of the same class is returned. As far as I can tell, this type annotation is accurate even if one was to subclass these classes (the methods I checked actually return an instance of the subclass in this case).

## Why is this a problem?

However, this introduces problems if one attempts to build a schema validation library along the lines of [pandera](https://github.com/unionai-oss/pandera). Let's say I define a schema

```python
class MySchema(Schema):
    a: int
    b: float
```

that I use to mark my lazy frame as adhering to the schema. Similar to what is being done in the `pandera.typing` module, I create a generic type named `PolarsLazyFrame` that

- is a subclass of `pl.LazyFrame`
- allows to be annotated with the schema of choice (e.g. `PolarsLazyFrame[MySchema]`)
- but is never instantiated and only used for the type checker.

The problem with the current use of `Self` in `pl.LazyFrame` is that methods like `select` will return the original type. For example:

```python
ldf: PolarsLazyFrame[MySchema]
new_ldf = ldf.select("a")
```

`new_ldf` now has type `PolarsLazyFrame[MySchema]` although a generic `pl.LazyFrame` would be more appropriate.

## What would need to be changed to support this?

In essence, all the current uses of `Self` would need to be replaced by type hints of the enclosing class (e.g. `-> LazyFrame` rather than `-> Self`). To ensure that this type annotation is valid even at runtime, one might want to actually create instances of `LazyFrame` rather than `Self`, e.g. by using `wrap_ldf` from `polars.utils`.

All of this should not have any impact on current users of polars as [subclassing is explicitly unsupported](https://github.com/pola-rs/polars/issues/2846#issuecomment-1711799869).

**Comment by stinodego** [comment]
Could you give a more complete example of what a generic like this looks like? 

I am open to changing the Self annotation, but I don't really see why that would be required.

**Comment by stinodego** [comment]
Thanks for the explanation.

Since you are overriding certain methods anyway, would it not make sense to also override methods like `cast` and `select` as well? I would figure those are the methods you would want to override. A type checker will probably complain about that, but you can override that since you know what you're doing.

Perhaps have a look at how patito works: https://github.com/JakobGM/patito

Apparently they have managed to make this work. It's still not clear to me how the Self return type is stopping you from doing something similar.

**Comment by borchero** [comment]
I had a look at `patito` and it suffers from the same issue:

```python
import patito as pt

class MySchema(pt.Model):
    a: int
    b: str

df = MySchema.DataFrame({"a": [1], "b": ["1"]})  # this becomes pt.DataFrame[MySchema]
df_out = df.select(pl.col("a").alias("c"))       # this is still pt.DataFrame[MySchema]!
```

That being said, `patito` "solves" this issue by never promising the user that `pt.DataFrame[MySchema]` _actually_ adheres to `MySchema` and requires the user to call `validate()` on the data frame to verify adherence at runtime. As a result, the generic data frame with the schema hint has little value for the type checker though...

`patito` runs in the additional issue that (truly) subclassing a `pl.DataFrame` is not officially supported.

**Comment by stinodego** [comment]
I still fail to see how using LazyFrame instead of Self would solve the issue. Returning a generic lazyframe is not going to help you enforce static typing. You would have to make it return a `LazyFrame[SomeNewSchema]`. And if you're overriding return types anyway, what does it matter if the return type on the original LazyFrame is Self or not?

I am hesistant to change this because it the current typing is correct. Changing from Self to LazyFrame would make it less correct.

Maybe @alexander-beedie can understand this request better than I can.

**Comment by borchero** [comment]
Sorry if my explanations weren't clear enough yet (the explanation is a little finicky, unfortunately), I'll try again based on your most recent message @stinodego :smile:

> Returning a generic lazyframe is not going to help you enforce static typing

As outlined above, always returning a generic lazy frame is not ideal but still better than the current state for the following reason:

- Currently, `Self` is returned for all methods, even those which are not schema-preserving (such as `select`). This results in objectively wrong type inference in many cases (at least for a `PolarsLazyFrame` generic over its schema).
- Always returning `LazyFrame` does not give the benefit of schema-preserving methods (such as `filter`) as any operation on the lazy frame results in losing the schema information. This is, however, better than the current state as, at least, no mistakes are made. For methods that are known to be schema-preserving, the `PolarsLazyFrame` may choose to overwrite the return type. This comes with the downside that it is tightly coupled to a polars version.
- The ideal setting would, thus, be: return `Self` for schema-preserving methods, return `LazyFrame` for non-schema-preserving methods. The downside is the implicit contract which is now pushed into polars itself. I cannot evaluate whether this is desirable/achievable.

> what does it matter if the return type on the original LazyFrame is Self or not?

The problem is that this makes the schema-validation library _very_ dependent on a particular version of polars. Type hints would need to be adjusted for every new method introduced on a lazy frame.

> I am hesistant to change this because it the current typing is correct. Changing from Self to LazyFrame would make it less correct.

I fully agree with this and tried to indicate it in my initial comment as well: methods which do not return `Self` should be augmented to return `LazyFrame._from_ldf(pyldf)` (or whatever the actual method name) rather than `cls._from_ldf(pyldf)`.

**Comment by stinodego** [comment]
> This comes with the downside that it is tightly coupled to a polars version.

I don't think you can avoid being coupled to a Polars version. We may add new methods at any time, which may or may not be schema-preserving. We may also remove existing methods (after deprecating them) or change the schema-impact of existing methods. So you cannot promise correct static typing in a version-agnostic manner.

I'll close this as not planned, as I don't think changing the typing will facilitate anything desirable.

Perhaps you can have a look at https://github.com/pola-rs/polars/issues/3623 and suggest a way we can incorporate schema-based static typing directly into Polars.

**Comment by borchero** [comment]
> We may add new methods at any time, which may or may not be schema-preserving

Fair enough, I think that would be the reason to differentiate between returning `LazyFrame` and `Self` :smile: thus, whether a method is schema-preserving would be determined by the version of polars currently installed.

Anyways, it makes sense to move this discussion to #3623, thanks! I believe that the same discussion would at one point surface there though 😅
