### ISSUE TITLE
Dataframe creation for row-oriented data is slow/uses lots of memory

### ISSUE THREAD

**Issue by aberres** [pola-rs/polars#14742]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd

row_data = 4_000_000 * [("737", "COC", "CP", "HAM", "737", "COC", "CP", "FRA")]

#~10 seconds+5Gi memory
pl.DataFrame(
    row_data,
    orient="row",
    schema={f"{i}":pl.String for i in range(8)},
)

#1 second, 1.3Gi memory
pl.from_pandas(pd.DataFrame.from_records(row_data))
```

### Issue description

While constructing Polars frames from row-oriented data, I noticed a significant overhead in memory and CPU time. 

Creating a Pandas frame first is 10x faster.

Using `pl.Enum` as dtype does not seem to make a difference. Using floats instead of strings improves the situation, but Pandas still performs better.

### Expected behavior

Performance should ideally not be worse than Panda's. 

Memory usage should (ideally) not greatly exceed the memory usage of the final frame.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.11
Index type:           UInt32
Platform:             macOS-13.3-arm64-arm-64bit
Python:               3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]```

</details>

**Comment by alexander-beedie** [comment]
FYI, testing on the latest version (polars 1.50) I actually get identical timings now... can you install the same version and confirm if this is still an issue or not? Running on my own machine (an Apple Silicon Mac) I get the following results using your example above:

```
polars: Elapsed time: 1.7053 seconds
pandas: Elapsed time: 1.7125 seconds
```
