### ISSUE TITLE
[Polars Python 0.20.12] Importing polars fails due to 'RuntimeError: unknown feature flag "pclmulqdq"'

### ISSUE THREAD

**Issue by jasperswallen** [pola-rs/polars#14759]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
Python 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/venv/lib/python3.11/site-packages/polars/__init__.py", line 11, in <module>
    polars._cpu_check.check_cpu_flags()
  File "/home/me/venv/lib/python3.11/site-packages/polars/_cpu_check.py", line 231, in check_cpu_flags
    raise RuntimeError(msg)
RuntimeError: unknown feature flag "pclmulqdq"
```

### Issue description

When importing polars 0.20.12, I receive a runtime error. This is a critical breaking change - Polars 0.20.10 did not raise this error.

### Expected behavior

`import polars` will be functional.

### Installed versions

`pl.show_versions()` cannot be run, since polars cannot be imported.

OS:

22.04 Ubuntu through WSL2. Also seen in 22.04 Ubuntu native machines.

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

```
$ uname -a
Linux <machine name> 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Python:

```
$ python3 -V
Python 3.11.7
```

**Comment by alexander-beedie** [comment]
@jasperswallen: That release has been removed; we'll release a follow-up `0.20.13` shortly (and close the hole that allowed the breaking release to escape CI) 👌
