### ISSUE TITLE
with_context not present for pl.DataFrame

### ISSUE THREAD

**Issue by h4ck4l1** [pola-rs/polars#14775]
### Description

Hello polars team,
Big fan. I just observed that lazyframes have the method with_context while eager ones do not.
I just wanted to know reason behind that. 
Thankyou!

**Comment by h4ck4l1** [comment]
It makes no difference to me though as its only a matter of calling .lazy() when using .with_context. I am just curious.

**Comment by cmdlineluser** [comment]
I think `.with_context` existed as a workaround for the lack of a horizontal concat on LazyFrames.

That was recently added:

- https://github.com/pola-rs/polars/pull/13139

I recall reading in one of the previous issues that `.with_context` may end up being deprecated now?

**Comment by mcrumiller** [comment]
> I recall reading in one of the previous issues that .with_context may end up being deprecated now?
 
I don't think it should, `with_context` allows for aggregate operations on different sized frames, which is nice:

```python
>>> import polars as pl
>>> ldf1 = pl.LazyFrame({"a": [1, 2, 3]})
>>> ldf2 = pl.LazyFrame({"b": [1, 2, 3, 4]})
>>> ldf1.with_context(ldf2).select(pl.all().sum()).collect()
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 6   ┆ 10  │
└─────┴─────┘
```

**Comment by h4ck4l1** [comment]
> > I recall reading in one of the previous issues that .with_context may end up being deprecated now?
> 
> I don't think it should, `with_context` allows for aggregate operations on different sized frames, which is nice:
> 
> ```shell
> >>> import polars as pl
> >>> ldf1 = pl.LazyFrame({"a": [1, 2, 3]})
> >>> ldf2 = pl.LazyFrame({"b": [1, 2, 3, 4]})
> >>> ldf1.with_context(ldf2).select(pl.all().sum()).collect()
> shape: (1, 2)
> ┌─────┬─────┐
> │ a   ┆ b   │
> │ --- ┆ --- │
> │ i64 ┆ i64 │
> ╞═════╪═════╡
> │ 6   ┆ 10  │
> └─────┴─────┘
> ```

Yes exactly. and .with_context should also be extended to pl.DataFrames if theres no downsides to it

**Comment by stinodego** [comment]
`LazyFrame.with_context` will be deprecated with the release of `1.0.0` (https://github.com/pola-rs/polars/pull/16860). We will not fix any bugs associated with it and we will not be adding it to `DataFrame`.

Please use `pl.concat(..., how="horizontal")` instead to combine DataFrames/LazyFrames into a single context.

**Comment by h4ck4l1** [comment]
I wish I'd atleast know the reason cuz I started(opened) this issue out of curiosity, but thankyou for communicating the changes, now I am sure what to use and what not to.

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/16444#issuecomment-2127314162

> Yes! I want to deprecate and remove `with_context`. It is hacky and buggy design.

**Comment by h4ck4l1** [comment]
@cmdlineluser Thankyou!
