### ISSUE TITLE
Cannot upgrade to 0.38.0: count_rows_ipc not found in this scope

### ISSUE THREAD

**Issue by drauschenbach** [pola-rs/polars#14777]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```bash
$ cargo build
...
   Compiling polars-row v0.38.0
   Compiling polars-json v0.38.0
   Compiling polars-parquet v0.38.0
   Compiling polars-time v0.38.0
   Compiling polars-io v0.38.0
error[E0425]: cannot find function `count_rows_ipc` in this scope
  --> /Users/davidr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.38.0/src/logical_plan/functions/count.rs:49:21
   |
49 |                     count_rows_ipc(&mut reader)
   |                     ^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `polars-plan` (lib) due to 1 previous error
```

### Issue description

Upgrading a Rust project to Polars 0.38.0 fails because polars-plan fails to compile.

### Expected behavior

All Polars modules build based on their current Polars dependencies.

### Installed versions

Upgrading from 0.37.0 to 0.38.0.

**Comment by ritchie46** [comment]
What were your feature flags?
