### ISSUE TITLE
is_between behavior

### ISSUE THREAD

**Issue by jerome-f** [pola-rs/polars#14784]
### Description

Hi,

I noticed that the is_between statement only works if the lower_bound and upper_bound are sequential

df = pl.DataFrame({"num": [1, 2, 3, 4, 5]})

df = pl.DataFrame({"num": [1, 2, 3, 4, 5]})

print(df.with_columns(pl.col("num").is_between(2, 4).alias("is_between")))

df.with_columns(pl.col("num").is_between(4, 2).alias("is_between"))

shape: (5, 2)
┌─────┬────────────┐
│ num ┆ is_between │
│ --- ┆ ---        │
│ i64 ┆ bool       │
╞═════╪════════════╡
│ 1   ┆ false      │
│ 2   ┆ true       │
│ 3   ┆ true       │
│ 4   ┆ true       │
│ 5   ┆ false      │
└─────┴────────────┘

(5, 2)
num | is_between
-- | --
i64 | bool
1 | false
2 | false
3 | false
4 | false
5 | false

is this intentional

**Comment by avimallu** [comment]
The [docs](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.is_between.html) do say:

> Check if this expression is between the given **lower** and **upper** bounds.

and so I would assume that this *is intentional*.

**Comment by alexander-beedie** [comment]
> I noticed that the is_between statement only works if the lower_bound and upper_bound are sequential

This is expected; in that sequence of values there are no values that are both `>=` the lower bound and also `<=` the upper bound, so you will have no matches.
