### ISSUE TITLE
Add empty `attr` dictionary to lazy/dataframe

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#14815]
### Description

As of #13236 we can no longer dynamically add attributes to `DataFrame` and `LazyFrame` objects. However, sometimes it is desirable to add user attributes to frames for later use.

I propose here to add to `__slots__` an empty `attr` dictionary  so that users can store user-defined attributes in their tables, as in:
 
```python
import polars as pl

df = pl.DataFrame()
df.attr["name"] = "my_dataframe"
```

**Comment by stinodego** [comment]
This is not reliable, as not all DataFrame methods preserve the class. If you were to `df.sort()`, the data would be gone.

Also, it kind-of defeats the purpose of `__slots__`.

Closing in favor of #5117

**Comment by mcrumiller** [comment]
One of the _benefits_ of `__slots__` is that this is no longer possible.

I'd call it more of a side effect. The primary benefit is faster access to the `_df` variable in almost all of the python methods, and adding another variable to `__slots__` does not remove that benefit. I think it's worthwhile to allow a single variable for user-defined parameters. This is prevalent in other languages as well. A good resolution of the other issue would be preferred but that seems substantially more difficult and less likely to be realized.
