### ISSUE TITLE
saving parquet with utf8view doesn't use RLE_ENCODING

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#14814]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pyarrow.parquet as pq
data = {'id' : ['abcdefgh'*6] * 3_000_000,
        'code' : ['20032'] * 3_000_000}

df = pl.DataFrame(data)
df.write_parquet("try.parquet", use_pyarrow=False)
pq.ParquetFile("try.parquet").metadata.to_dict()[
            "row_groups"
        ][0]["columns"][0]["encodings"]

# ('PLAIN', 'RLE')
```

### Log output

```shell
no log out
```

### Issue description

I tried to take a crack at this but I hit a wall.

The first thing I did was to add `PhysicalType::Utf8View` to this match

https://github.com/pola-rs/polars/blob/a34e2b018fd171b0a655e27d6dfd671d7c6c6837/crates/polars-io/src/parquet/write.rs#L248-L252

Unfortunately that wasn't sufficient.

I tracked it down to here

https://github.com/pola-rs/polars/blob/a34e2b018fd171b0a655e27d6dfd671d7c6c6837/crates/polars-parquet/src/arrow/write/pages.rs#L170-L176

where it fails going back to this chunk that called it

https://github.com/pola-rs/polars/blob/a34e2b018fd171b0a655e27d6dfd671d7c6c6837/crates/polars-parquet/src/arrow/write/mod.rs#L200-L212

As you can see the note `// We didn't succeed, fallback to plain`

### Expected behavior

should be able to save a parquet and get rle_dictionary with new string type

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13 (main branch, as of commit 14809)
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  0.9.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.15.1
fsspec:               2023.12.2
gevent:               23.9.1
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.5.3
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.25
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
What is the problem/bug?
