### ISSUE TITLE
Hive Partition Schema

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars#14838]
### Description

When doing hive partitioning it would be great if Polars could support other data types (e.g. dates, datetimes) similar to other frameworks (e.g. [duckdb](https://duckdb.org/docs/data/partitioning/hive_partitioning.html#autodetection) , [bigquery](https://cloud.google.com/bigquery/docs/hive-partitioned-queries#detection_modes)).

**Comment by baycoder0** [comment]
+1

I had a similar issue open before: https://github.com/pola-rs/polars/issues/12894

@ritchie46 is this something the core team has plans around by chance? If not, I'm willing to take a stab at it given some guidance on the desired design.

**Comment by deanm0000** [comment]
@baycoder0 c-peters is part of the core team.

I think you'd want to get started here

https://github.com/pola-rs/polars/blob/e1a417920d530b0a87a3e9614787205e8fd965ae/crates/polars-plan/src/logical_plan/hive.rs#L71-L83

**Comment by deanm0000** [comment]
The csv datetime parser seems to be over [here](https://github.com/pola-rs/polars/blob/main/crates/polars-io/src/csv/buffer.rs)

**Comment by deanm0000** [comment]
Additionally, this is highly related to https://github.com/pola-rs/polars/issues/13892

**Comment by ritchie46** [comment]
What we require first is schema inference on hive partitions. Otherwise some parts may be strings and/or different date formats. There needs to be something in place for schema inference and communicating that schema result between the partitions first.

**Comment by fcocquemas** [comment]
Are you still considering a parameter to pass a hive partitions schema, similar to how you can pass `dtypes` to override the inference? This is something @deanm0000 suggested in #13892.

There are some cases where it would be nice to override the regexp-based schema inference. For instance:
- It might be hard to detect all date formats correctly (Is this string `%d/%m/%Y` or `%m/%d/%Y`?). In some cases (e.g. 8 digit number), it may look like a date, but really be an Integer or a String.
- BOOLEAN_RE would match `value=TRUE`, even when it might represent a String, not a Boolean.

Having schema inference as a default is convenient, but an option to override would be nice.

**Comment by nameexhaustion** [comment]
Datetime support has been added by https://github.com/pola-rs/polars/pull/17256
