### ISSUE TITLE
replace_time_zone()'s ambigouous argument doesn't work correctly

### ISSUE THREAD

**Issue by Sage0614** [pola-rs/polars#14842]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime

pl.show_versions()
df = pl.DataFrame(
    {
        "test": [datetime(2011, 3, 13, 2, 55, 0)],
    }
)

df.with_columns(
    edt=pl.col("test").dt.replace_time_zone("America/New_York", ambiguous="latest")
)

```

### Log output

```shell
Traceback (most recent call last):
  File "/home/swang/bug_report/debug.py", line 11, in <module>
    df.with_columns(
  File "/home/swang/.pyenv/versions/3.11.4/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8301, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swang/.pyenv/versions/3.11.4/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1939, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: datetime '2011-03-13 02:55:00' is non-existent in time zone 'America/New_York'. Non-existent datetimes are not yet supported
```

### Issue description

As far as I understand this is not the ambigious argument supposed to work, for non exist time it should convert to first available time after the day light saving change if I use "latest" option

### Expected behavior

 for non exist time it should convert to first available time after the day light saving change if I use "latest" option

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.4 (main, Aug 24 2023, 11:18:03) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.2
numpy:                1.25.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              13.0.0
pydantic:             1.10.12
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report - this looks expected, I think you're asking for a `non_existent` argument, see https://github.com/pola-rs/polars/issues/11579

closing in favour of that one then

**Comment by Sage0614** [comment]
@MarcoGorelli will you consider the propose of #13758 at the same time?  when you say in #11579

> whereas ambiguous datetimes are a fact of life, non-existent ones indicate a data error which should probably be cleaned by the user

I agree with that, but there's no simple way to branch part of the data to be problematic and handle it separately, like if else in pthon. I do try to flag the data error with when-then-otherwise logic, and replace_time_zone is only supposed to handle the 'clean' branch, but no, all code path need to work simutaneously. it is a pain to use the when-then-otherwise logic when the code can potentially error or panic.

**Comment by MarcoGorelli** [comment]
[this](https://github.com/pola-rs/polars/issues/11579#issuecomment-1752541589) is the suggestion I'm making there, so to have `non_existent` take `'null'` or `'raise'`

**Comment by Sage0614** [comment]
> [this](https://github.com/pola-rs/polars/issues/11579#issuecomment-1752541589) is the suggestion I'm making there, so to have `non_existent` take `'null'` or `'raise'`

I am aware of that and I am not complaining about not having the option in replace_time_zone here, 
I am discussing the general case, what can user do when they have some use case where polars currently gives an error/panic?
some of problem are fixed by polars team in a week, some of the problem are fixed by maybe in a year, but if I need to use polars in production, I cannot wait till tomorrow.

So, I am asking polars team in addition to the parallel version of when-then-otherwise, to also provide us a version of when-then-otherwise, where exactly one branch of the when-then-otherwise will be executed, so, if I encounter some error/panic, I can have a quick workaround by filtering the data and handle the cases that causes the error with a when-then-otherwise clause, and when the problem is fixed by polars team I can just switch back to the offical solution, with minimal code change.

**Comment by MarcoGorelli** [comment]
I'd suggest explaining this in #13758

**Comment by deanm0000** [comment]
In the specific case of non-existent time zones there are two work arounds that I've used.

One is at the end of [this](https://github.com/pola-rs/polars/issues/12146).

The other is to create a clean range and then join to the unclean.

So suppose you have

```
unclean = pl.select(a=pl.datetime_range(pl.datetime(2022,3,13), pl.datetime(2022,3,14), '30m'))
```

Doing the following will produce an error

```
unclean.with_columns(pl.col('a').dt.replace_time_zone('America/Chicago'))
ComputeError: datetime '2022-03-13 02:00:00' is non-existent in time zone 'America/Chicago'. Non-existent datetimes are not yet supported
```

To get around that without looping with a try/except block (as above), you can do

```
clean=pl.select(b=pl.datetime_range(unclean.select(pl.col('a').min().dt.replace_time_zone("America/Chicago")).item(),
                                    unclean.select(pl.col('a').max().dt.replace_time_zone("America/Chicago")).item(),
                                    unclean['a'].diff().min())).with_columns(
                                        a=pl.col('b').dt.replace_time_zone(None)
                                    )
unclean.join(clean, on='a', how='left')
shape: (49, 2)
┌─────────────────────┬───────────────────────────────┐
│ a                   ┆ b                             │
│ ---                 ┆ ---                           │
│ datetime[μs]        ┆ datetime[μs, America/Chicago] │
╞═════════════════════╪═══════════════════════════════╡
│ 2022-03-13 00:00:00 ┆ 2022-03-13 00:00:00 CST       │
│ 2022-03-13 00:30:00 ┆ 2022-03-13 00:30:00 CST       │
│ 2022-03-13 01:00:00 ┆ 2022-03-13 01:00:00 CST       │
│ 2022-03-13 01:30:00 ┆ 2022-03-13 01:30:00 CST       │
│ 2022-03-13 02:00:00 ┆ null                          │
```
