### ISSUE TITLE
Link directly to contributing guide from `index.md`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#14855]
### Description

The [Contributing Guide section](https://github.com/pola-rs/polars/blob/main/docs/index.md#contributing) in `index.md` on the main page:

![image](https://github.com/pola-rs/polars/assets/1896992/c66d0766-b9c2-4498-ae1a-2bb0d42cf317)

Brings you [here](https://github.com/pola-rs/polars/blob/main/CONTRIBUTING.md). Is there a reason we have this interim page which doesn't seem to provide any value?

**Comment by stinodego** [comment]
Could you make a PR?

**Comment by mcrumiller** [comment]
Sure.
