### ISSUE TITLE
`.take()` for data frames

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1486]
Basically a row selector for data frames that works like `pl.Series.take`

```python
import polars as pl

df = pl.DataFrame({'x': range(3), 'y': ['a', 'a', 'b']})

df.take([0, 2])

shape: (2, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 0   ┆ "a" │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ "c" │
└─────┴─────┘
```

**Comment by ritchie46** [comment]
I don't want to clutter the API surface with everything available on expressions.

As there is a `take` expression, you can do `df.select(pl.all().take([0, 2]))`.

You could also use indexing: `df[[0, 2]]`

**Comment by markfairbanks** [comment]
Gotcha makes sense. Both of these seem like good options
