### ISSUE TITLE
`deepcopy` from copy does not work on `polars.Series.dtype`

### ISSUE THREAD

**Issue by PierreAttard** [pola-rs/polars#14877]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from copy import deepcopy

print(pl.Series([1, 2]).dtype)
print(pl.Series([1, 2]).dtype == pl.Int64)

deepcopy(pl.Int64)
deepcopy(pl.Series([1, 2]).dtype)  # raise error AttributeError: 'Int64' object has no attribute '__dict__'
```

### Log output

```shell
Traceback (most recent call last):
  File "<ipython-input-11-eee5c94028d9>", line 1, in <module>
    deepcopy(pl.Series([1, 2]).dtype)
  File "C:\Users\PierreAttard\AppData\Local\Programs\Python\Python310\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "C:\Users\PierreAttard\Documents\environment\python310\diagenv310\lib\site-packages\polars\datatypes\classes.py", line 96, in __reduce__
    return (_custom_reconstruct, (type(self), object, None), self.__dict__)
AttributeError: 'Int64' object has no attribute '__dict__'
```

### Issue description

Hi,

I try to deepcopy (with deepcopy from copy) an object which have a field with a value `pl.Series([1, 2]).dtype`. 
But when I `deepcopy` that object (with copy), I have the error `AttributeError: 'Int64' object has no attribute '__dict__'`.

See `Reproducible example` for more information. 

### Expected behavior

I would like to `deepcopy(pl.Series([1, 2]).dtype)`  without error.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.2
numpy:                1.24.4
openpyxl:             <not installed>
```

</details>

**Comment by dpinol** [comment]
I can reproduce it with polars 0.20.13, but not on 0.20.10.
Both with python 3.11.5

**Comment by stinodego** [comment]
This was reported in https://github.com/pola-rs/polars/issues/14771 and fixed in https://github.com/pola-rs/polars/pull/14778
