### ISSUE TITLE
Document how to change the 5min default timeout in pl.read_parquet from cloud storage

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#14871]
### Description

This PR: https://github.com/pola-rs/polars/pull/13023 fixed a number of timeout issues when reading from cloud storage. 

That said, the 5min timeout should be configurable - only that it's not clear how to configure this in the polars documentation.

**Comment by ritchie46** [comment]
I turned them off in #14809

Now that is similar to the defaults in the reqwest library. I wonder if we would want them.

**Comment by mkleinbort-ic** [comment]
Ok, I'll close the issue then, and maybe re-open if I hit timeout issues after this is released.
