### ISSUE TITLE
pl.Series.value_counts should make sort=True default.

### ISSUE THREAD

**Issue by ribbondz** [pola-rs/polars#14889]
### Description

In data analysis, when sort=True distributions for the column can be more easily observed. This would saving some typings for most of people.

**Comment by stinodego** [comment]
The default should be whichever is fastest. Many people will use `value_counts` as part of a processing pipeline where order doesn't matter. We don't want those people unknowingly sorting their data, which may be an expensive operation. If you explicitly want sorted output, you can pass `sort=True`.
