### ISSUE TITLE
Get category mapping for categoricals

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#14883]
### Description

While usually internal implementations should remain hidden, categorical data is universally known to be represented by integers, and this representation is often useful to developers. I propose we expose the rev mapping in the API via the following:

* `Series.cat.get_map` - get map for categorical series as dictionary
* `pl.StringCache.get_map` - get global categorical map.

This has also come up on discord a few times. We usually refer people to `s.unique()`, but that does not always show all of the categories.

**Comment by deanm0000** [comment]
I like them both. For the first one though you can do:

```
s=pl.Series("a",['apple','banana', 'apple'],dtype=pl.Categorical)
```

```
{x[1]:x[0] for x in s.cat.get_categories().to_frame().with_row_index('i').iter_rows()}
{'apple': 0, 'banana': 1}
```

**Comment by c-peters** [comment]
The indices of the `cat.get_categories()` are equal to the physicals. I'm not convinced that we really need a new method for this as the method by @deanm0000 will provide you the mapping
