### ISSUE TITLE
Cannot read data from s3 with `storage_options`

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#14893]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import boto3
import polars as pl

def get_storage_options():
    credentials = boto3.Session().get_credentials()
    return {
        "aws_access_key_id": credentials.access_key,
        "aws_secret_access_key": credentials.secret_key,
        "aws_region": "us-east-2",
    }

filename = "s3://my-bucket/test_data.parquet"
df = pl.read_parquet(filename, storage_options=get_storage_options())
```

The bucket in this example has been created with a KMS key for encryption:
`Encryption type: Server-side encryption with AWS Key Management Service keys (SSE-KMS)`
The EC2 instance accessing the bucket has an IAM role that grants the use of the KMS key.

The `storage_options` in question are the ones used in the guide:
https://docs.pola.rs/user-guide/io/cloud-storage/#reading-from-cloud-storage

### Issue description

`polars.exceptions.ComputeError: Generic S3 error: Client error with status 403 Forbidden: No Body`

I was getting this error at work, so I went home and created an AWS account and set everything up independently. I still get this error.

### Expected behavior

Read the parquet file.
It works without `storage_options`, besides a warning message that polars is inferring the region.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Linux-6.2.0-1018-aws-x86_64-with-glibc2.35
Python:               3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by s-banach** [comment]
@stinodego I guess I just needed to add `credentials.token` to the dictionary.
Can you add this to the User Guide? 

```python
import boto3
import polars as pl

def get_storage_options():
    credentials = boto3.Session().get_credentials()
    return {
        "aws_access_key_id": credentials.access_key,
        "aws_secret_access_key": credentials.secret_key,
        "session_token": credentials.token,
        "aws_region": "us-east-2",
    }

filename = "s3://my-bucket/test_data.parquet"
df = pl.read_parquet(filename, storage_options=get_storage_options())
```

**Comment by stinodego** [comment]
Can you tell me under which circumstances it's necessary to add the `session_token`? It may be worth adding to the user guide if we can pinpoint that bit of information.

**Comment by s-banach** [comment]
I only have access to S3 with encryption, and I always need `session_token` to use `scan_parquet`.

I don't understand S3 well enough to figure anything out except by copy-pasting other people's code snippets off the internet.
I don't understand how `read_parquet` can succeed without specifying `storage_options` but `scan_parquet` cannot.
