### ISSUE TITLE
read_csv - Error when parsing CSV with leading whitespace 

### ISSUE THREAD

**Issue by manglisani** [pola-rs/polars#14897]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
dftest = pl.read_csv(source="filein.csv",
                 has_header=False,
                 skip_rows=0,
                 separator=chr(0000),
                 infer_schema_length=0,
                 new_columns=["empty_header"])

```
filein.csv (leading spaces at the begining of lines are replaced with underscore chars here to show how it is the data file):
____xxxxxxxxxx   1 240219 17:44 00000207  0 16       blabla          xxx
____yyyyyyyyyy   1 240219 17:44 00000207  0 16       blabla          zzz
____wwwwwwwwww   1 240219 17:44 00001207  0 16       blabla          jjj
____zzzzzzzzzz   1 240219 17:44 00000207  0 16       blabla          hhh

### Log output

```shell
shape: (4, 1)
empty_header
str
"xxxxxxxxxx   1…
"    yyyyyyyyyy…
"    wwwwwwwwww…
"    zzzzzzzzzz…
```

### Issue description

Hello, I am currently using the Polars library and I am encountering an issue.  I am try to read a fixed field CSV file, which begins each line with a variable number of space characters for data alignment. Since the file doesn't have any header rows, the data is read starting from the first line. However, during the reading process, the spacing characters in the first line are removed, which disrupts the data structure of the first line.

### Expected behavior

The correct behavior should be to leave the data of the first record unchanged as happens for subsequent records.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.1
pyarrow:              15.0.0
pydantic:             1.10.13
pyiceberg:            0.3.0
pyxlsb:               1.0.10
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by cmdlineluser** [comment]
Minimal repro:

```python
pl.read_csv(b"""\
     1,2
     3,4
     5,6""",
   has_header = False
).with_columns(pl.all().str.replace_all(" ", "[x]"))

# shape: (3, 2)
# ┌──────────────────┬──────────┐
# │ column_1         ┆ column_2 │
# │ ---              ┆ ---      │
# │ str              ┆ str      │
# ╞══════════════════╪══════════╡
# │ 1                ┆ 2        │ # ERROR: `column_1` leading spaces lost
# │ [x][x][x][x][x]3 ┆ 4        │
# │ [x][x][x][x][x]5 ┆ 6        │
# └──────────────────┴──────────┘
```

**Comment by manglisani** [comment]
After update of new version (0.20.16) the issue is resoved.

**Comment by cmdlineluser** [comment]
I still get this:

```python
pl.__version__

pl.read_csv(b"""\
     1,2
     3,4
     5,6""",
   has_header = False
).with_columns(
   pl.all().str.replace_all(" ", "[x]")
)
```
```python
'0.20.16'
shape: (3, 2)
┌──────────────────┬──────────┐
│ column_1         ┆ column_2 │
│ ---              ┆ ---      │
│ str              ┆ str      │
╞══════════════════╪══════════╡
│ 1                ┆ 2        │
│ [x][x][x][x][x]3 ┆ 4        │
│ [x][x][x][x][x]5 ┆ 6        │
└──────────────────┴──────────┘
```
