### ISSUE TITLE
concat_str "vertically" in aggregation context

### ISSUE THREAD

**Issue by KevDAll** [pola-rs/polars#1490]
#### Describe your feature request

Please describe the behavior you want and the motivation. 

It would be very helpful if polars.concat_str could be applied "vertically" as an expression method in aggregation contexts to mimic "group_concat" in SQL.

Currently I can define:
```
def polars_group_concat(col: str, seperator: str = ',', distinct: bool =False) -> polars.Expr:
  expr = polars.col(col)
  if distinct:
    expr = expr.unique().drop_nulls()
 else:
    expr = expr.drop_nulls()
 return expr.list().apply(lambda x:  seperator.join(x))
```

However, this is very slow.  Aggregating to a list without converting to a string is approximately 6X faster when I test it.   However to insert the results into a varchar column in a DB I need to convert the result to a string.  

I tried:
expr.drop_nulls().apply(lambda x: np.array2string(x.to_numpy(), sep=',')  but copying to data into numpy took even longer than the native python string join, and my understanding is a copy is required for strings, so "view" will not work.  

Ideally I would want a method which is:
```
polars.expr.concat_str(sep: str = ',', distinct: bool = False):
"""
aggregate utf-8 expression values to a delimited string.  Only valid in an aggregation context ,
parameters:
sep: string value to use to seperate values
distinct: syntatic sugar for polars.expr.unique().concat_str(sep)
"""
```

The distinct argument is obviously not required as polars.expr.unique() can be applied before the concat_str.

**Comment by ritchie46** [comment]
Seems a good addition under the `str` namespace  :+1: . So the syntax would be:

`pl.col("foo").unique().str.concat(sep)`.
