### ISSUE TITLE
Take advantage of partitions in group_by in streaming mode

### ISSUE THREAD

**Issue by alkment** [pola-rs/polars#14911]
### Description

Currently group_by on a LazyFrame, with partitioned data underlying it, doesn't seem to be able to take advantage of the partitioning scheme.

My data is too large to fit into memory. My hope was that polars would calculate the aggregation for each partition, which easily fits into memory, and  concatenate the results of each partition.
When running the code below polars runs out of memory, indicating that it's not able to take advantage of the partitions.
```
pl.scan_parquet('./dt=*/*.parquet',hive_partitioning=True).group_by(['dt','ticker']).agg(pl.col('mid').median()).collect(streaming=True)
````

**Comment by ritchie46** [comment]
Median is supported in streaming mode. We are actively working on improving the streaming engine. We have a lot of plans and todo.

I will close this issue, as having many issues for this isn't helpful. Thanks for the proposal.
