### ISSUE TITLE
dtype flag of `read_csv` doesn't overwrite the dtypes during inference

### ISSUE THREAD

**Issue by martinapippi** [pola-rs/polars#1492]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.9.12

#### What operating system are you using polars on?

Ubuntu 20.04
 
#### Describe your bug.

dtype flag of `read_csv` doesn't overwrite the dtypes during inference when dealing with strings data. 

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import io

body = '\n0 0.0702271 0.0274737 0.164752 5.79834 0.610352 0.183105\n'

df = pl.read_csv(
        io.StringIO(body),
        sep=" ",
        has_headers=False,
        new_columns=[
            "datetime",
            "v_top_x",
            "v_top_y",
            "v_top_z",
            "freq_x",
            "freq_y",
            "freq_z",
        ],
        dtype={
            "datetime": pl.Int32,
            "v_top_x": pl.Float32,
            "v_top_y": pl.Float32,
            "v_top_z": pl.Float32,
            "freq_x": pl.Float32,
            "freq_y": pl.Float32,
            "freq_z": pl.Float32,
        },
    )
df
```

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/46439957/136234490-091a052b-8a94-47a9-b29b-674a4824cf07.png)

#### What is the expected behavior?

The dtypes should be overwritten.

**Comment by ghuls** [comment]
@ritchie46 I have some code already, which also should work if `projection` is used.
