### ISSUE TITLE
Deadlock when running complex query

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#14939]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
couldn't get MRE, previous code was not causing it anyways
```

### Log output
Output right before deadlock:
```
parquet file must be read, statistics not sufficient for predicate.
group_by keys are sorted; running sorted key fast path
group_by keys are sorted; running sorted key fast path
group_by keys are sorted; running sorted key fast path
dataframe filtered
FOUND SORTED KEY: running default HASH AGGREGATION
ASOF join dataframes finished
estimated unique values: 1
run STREAMING HASH AGGREGATION
RUN STREAMING PIPELINE
[df -> generic-group_by -> ordered_sink]
finish streaming aggregation with local in-memory table
```

### Issue description

Deadlocks when running the collection in a loop many times.

### Expected behavior

Doesn't deadlock

### Installed versions

<details>

```
Python 3.11.7 (main, Dec  5 2023, 22:00:36) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
>>> polars.show_versions()
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Linux-5.10.213-179.855.x86_64-x86_64-with-glibc2.26
Python:               3.11.7 (main, Dec  5 2023, 22:00:36) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```


Occurs since 0.20.3
```
</details>

**EDIT**:
I no longer thing it has anything to do with `map_batches` or `map_elements`, i've removed them from my code and it still occurs. Seems like it gets hung shortly after:

```
estimated unique values: 1
run STREAMING HASH AGGREGATION
RUN STREAMING PIPELINE
[df -> generic-group_by -> ordered_sink]
finish streaming aggregation with local in-memory table
```

This is also a `scan_parquet` against the cloud with a few joins.

**Comment by orlp** [comment]
> I'll try to make something more reproducible later if required.

A minimal working example reproducing the problem would be much appreciated.

**Comment by ritchie46** [comment]
Do you use `map_elements`/ `map_batches`? Then I think we can deadlock because of the python GIL.

**Comment by ritchie46** [comment]
You could get a backtrace in gdb. 👀

**Comment by ritchie46** [comment]
@kszlim that's a good find. We should always drop mutexes before we spawn work with rayon as we don't want to hold the mutex when pushing other tasks on the work scheduler. This snippet in the window functions was indeed holding a rwlock when parallelizing work with rayon. Will issue a PR.
