### ISSUE TITLE
`with_columns_seq` should assign by expression

### ISSUE THREAD

**Issue by uditrana** [pola-rs/polars#14935]
### Description

Polars values itself in having a clean, readable interface. To that end, they should expose a `with_columns` style option/function that allows you to do sequential operations _with_ assignment between operations. This has come up before #11570 .

Current:
```Python
df.with_columns(
    pl.col("a").add(1).alias("a_plus_1"),
).with_columns(
    pl.col("a_plus_1").add("a").alias("2a_plus_1"),
)
```

Ideally:
```Python
df.with_columns_seq_assign(
    pl.col("a").add(1).alias("a_plus_1"),
    pl.col("a_plus_1").add("a").alias("2a_plus_1"),
)
```

**Comment by McNickSisto** [comment]
I second this.

**Comment by cmdlineluser** [comment]
The actual previous discussion for the desired functionality is:

- https://github.com/pola-rs/polars/issues/9062

(The `_seq` in this function is about parallelism.)

**Comment by uditrana** [comment]
Yea, seems like @ritchie46 was pretty firm with his process in that Issue. It is a bit odd to me because the Polars API seems to have introduced multiple variants (e.g. with_columns_seq) of methods... so maybe philosophy has changed on this matter.

**Comment by avimallu** [comment]
For reference, @uditrana, I don't think the philosophy has directly changed. `with_columns_seq` was created (https://github.com/pola-rs/polars/pull/10322) specifically to

> serve[s] merely as an optimization on small data, when parallelism overhead is too costly.

**Comment by ritchie46** [comment]
This has been discussed and we will not change the semantics of a `with_columns`. They will get their state from their context, not from incremental updates. The `seq` refers to sequential and is recommended to not be used. It is a micro-optimization that sometimes is worth it on tiny data.

**Comment by uditrana** [comment]
Yea, I wasnt really suggesting changing `with_columns` core semantics, but rather an alternative option like the `seq` version for specific use cases. But not worth pushing further if you all don't see it as a useful stylistic addition.
