### ISSUE TITLE
Support Array `zero-copy` from numpy array.

### ISSUE THREAD

**Issue by franz101** [pola-rs/polars#14946]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import pyarrow as pa
import polars as pl
# Working example
values = np.random.rand(1_000_000, 512).flatten()
typ = pa.list_(pa.field("name", pa.float64()), 512)
result = pa.FixedSizeListArray.from_arrays(values, type=typ)
arrow_table = pa.Table.from_arrays([result], names=["arr"])
# Crashes memory
df = pl.DataFrame(
    {
        "arr": np.random.rand(1_000_000, 512),
    },
    schema={
        "arr": pl.Array(inner=pl.Float64, width=512),
    },
)
```
https://colab.research.google.com/drive/1_c9xUIoAdDgtc2hOridsvUcE5IxFhBxN?usp=sharing

### Log output

```shell
Memory used by pyarrow 4.8gb
Memory used by polars 7gb
```

### Issue description

I know arrow is not optimal for arrays but this example should work:
https://colab.research.google.com/drive/1_c9xUIoAdDgtc2hOridsvUcE5IxFhBxN#scrollTo=VBpvlRvcXR5u

As you can see pyarrow works but polars crashes memory.

It works with smaller arrays though

### Expected behavior

Same or less memory than yarrow

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.1.58+-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.25.2
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             2.6.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.28
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
We should be able to do this zero-copy. Currently there is one copy, I think. It isn't a bug, more a feature request. Also the naming of the issue is a but dramatic.

**Comment by ritchie46** [comment]
We are now.
