### ISSUE TITLE
sink parquet make the disk full after spilling, even for small data

### ISSUE THREAD

**Issue by djouallah** [pola-rs/polars#14948]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

https://colab.research.google.com/drive/1pfAPpIG7jpvGB_aHj-PXX66vRaRT0xlj#scrollTo=IpjjaxGw1s5b

### Issue description

disk become full 

### Expected behavior

polars should write the parquet without the excessive spills 

### Installed versions

polars-0.20.14

**Comment by ritchie46** [comment]
Thanks, taking a look.

**Comment by ritchie46** [comment]
So with that fixed went on a local run from 90GB and growing to 2GB.. :sweat_smile:
