### ISSUE TITLE
Incorrectly identifies list[f64] column as Object when one of the inner lists contains Int

### ISSUE THREAD

**Issue by abstractqqq** [pola-rs/polars#14941]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Type for distance is object, which is wrong. The reason is that the second list contains an int and a float.
```python
pl.DataFrame({
    "id": range(5),
    "connections":[[1,2,3,4], [2,3], [4], [0,1,2], [1]],
    "distance":[[0.4, 0.3, 0.2, 0.1], [0.1, 1], [0.5], [0.1, 0.1, 0.1], [0.1]]
})
```
After some testing, I found that for "distance" to be parsed as object, the inner list must have > 1 elements. 

E.g. 5 is an int, but it is in a single element list. Type is correct.
```python
pl.DataFrame({
    "id": range(5),
    "connections":[[1,2,3,4], [2,3], [4], [0,1,2], [1]],
    "distance":[[0.4, 0.3, 2.0, 0.1], [0.1, 1.0], [5], [0.1, 0.1, 0.1], [0.1]]
})
```

### Issue description

Wrong type when turning mixed lists into list[f64]

### Expected behavior

For int and float mixed lists, they should be casted to super types.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             Linux-6.7.4-arch1-1-x86_64-with-glibc2.39
Python:               3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
@stinodego this seems to be a regression.

**Comment by stinodego** [comment]
Indeed this is a regression. Simpler reproducer:

```python
import polars as pl

s = pl.Series([[0.1, 1]])
print(s)
```
```
shape: (1,)
Series: '' [o][object]
[
        [0.1, 1]
]
```

There must be something in the Python-side constructor logic that falls back to objects in this case.

**Comment by ritchie46** [comment]
I think this is high priority. Creating objects is really bad and leads to lots of unexpected things.

**Comment by cmdlineluser** [comment]
I'm not sure if it's the exact same regression, but there was a similar example in https://github.com/pola-rs/polars/issues/14324

```python
import polars as pl

s = pl.Series([[{'B': 1}], [{'B': 2}, {'B': 'N/A'}]])
print(s)
```
```python
shape: (2,)
Series: '' [o][object]
[
	[{'B': 1}]
	[{'B': 2}, {'B': 'N/A'}]
]
```
