### ISSUE TITLE
Add `.cat.to_enum()` for fast Categorical -> Enum casting

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#14952]
### Description

Some polars functions like `pl.cut` returns Categorical variables. In order to cast these to Enum, we have to use pretty verbose syntax to get the categories before we can create the Enum. Example:

```python
import polars as pl
from polars import col

df = pl.DataFrame({"foo": [-2, -1, 0, 1, 2]})
df2 = df.with_columns(col("foo").cut([-1, 1]).alias("cut"))

# convert to Enum
df2 = df2.with_columns(
    col("cut").cast(
        # this is cumbersome
        pl.Enum(categories=df2["foo"].unique().drop_nulls())
    )
)
```

It would be nice to directly convert categoricals to Enums without having to specify categories:

```
df2 = df2.with_columns(col("cut").cat.to_enum())
```

**Comment by markxwang** [comment]
It would be even nicer if the bins are correctly ordered when passed to enum

**Comment by c-peters** [comment]
Yes, I agree with @markxwang here. Enum is an orderded datatype, for `cut` I would much rather return an `Enum` directly than a categorical. See #13038.

**Comment by mcrumiller** [comment]
@c-peters I see you self-assigned. I have a working impl, if you haven't started already should I just submit my PR?

**Comment by mcrumiller** [comment]
@c-peters I agree with you, and now I'm even hesitant to add this for `Series`, since the only reason is to workaround existing API issues where a categorical is returned instead of an enum.

Also, if we add an `Enum` as a return dtype to `pl.cut`, then we again are going to have a really hard time (read: impossible) propagating the schema in an expression context. What if someone uses `pl.cut` in a when/then and provides alternative values to what `cut` returns? Let's keep as categorical and reserve enums exclusively for static categoricals.

Do you agree here? I vote we just close and I'll cancel my PR.

**Comment by c-peters** [comment]
For `pl.cut` we do know the categories as they are the `labels` by the user or a derivative of the `breaks` parameter. So the schema would still be known after the operation. 

But I agree, let's keep the Enums simple for now and exclusively use it for statics

**Comment by Longistamina** [comment]
Hello guys, I think I found a way to do this inline using ```.pipe()``` method. The trick is that we use ```.pipe(lambda f: ....)``` to get eager direct access to the column, not via expression. Hence, this might affect the performance. Here is how it works.

```
import polars as pl

tb = (
    pl.DataFrame({
        "Name": ["Monster1", "Monster2", "Monster3", "Monster4", "Monster5"],
        "Level": ["1", "3", "2", "1", "3"]
    })
    .pipe(lambda f: f.with_columns(Level = f["Level"].cast(pl.Enum(f["Level"].unique().sort().to_list()))))
)

print(tb)
# shape: (5, 2)
# ┌──────────┬───────┐
# │   Name   ┆ Level │
# │    ---   ┆  ---  │
# │    str   ┆  enum │
# ╞══════════╪═══════╡
# │ Monster1 ┆   1   │
# │ Monster2 ┆   3   │
# │ Monster3 ┆   2   │
# │ Monster4 ┆   1   │
# │ Monster5 ┆   3   │
# └──────────┴───────┘
```
