### ISSUE TITLE
`.alias()` causes `ComputeError` when applied to expression in GroupBy context `agg()`

### ISSUE THREAD

**Issue by TNieuwdorp** [pola-rs/polars#14954]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I couldn't reproduce the data with a smaller example. Instead I've attached the file with which it happens.
The error occurs with the following dataset: [sales_data.csv](https://github.com/pola-rs/polars/files/14547701/sales_data.csv)

```python
import polars as pl
df = pl.read_csv("sales_data.csv")
print(
    df
    .select("Country", "Profit")
    .group_by("Country")
    .agg(
        (pl.col("Profit") > 1000).alias("Profit > 1000"),
    )
)
```

### Log output

```shell
estimated unique values: 6
run PARTITIONED HASH AGGREGATION
ComputeError: returned aggregation is of different length: 297 than the groups l
ength: 6
```

### Issue description

When adding `.alias("Profit > 1000")` behind the expression in the aggregation, it crashes. If it's left out it works. Changing this to a text that's not a statement ("Profit bigger than 1000") doesn't remove the error.

### Expected behavior

Expected behaviour is that it prints the dataframe with a second column titled like the Alias and a list of true/false for each element in the group according to the mask in the expression.

### Installed versions

<details>

```

--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             macOS-14.3.1-x86_64-i386-64bit
Python:               3.11.6 (main, Dec 10 2023, 21:42:27) [Clang 15.0.0 (clang-
1500.0.40.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fastexcel:            0.9.1
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

`1000` seems to the be minimum number of rows needed for it to error on my system.

```python
(pl.read_csv("sales_data.csv").head(1000)
    .select("Country", "Profit")
    .group_by("Country")
    .agg(
        (pl.col("Profit") > 1000).alias("Profit > 1000")
    )
)
# ComputeError: returned aggregation is of different length: 125 than the groups length: 6
```

`.head(999)` works as expected.

**Comment by mcrumiller** [comment]
There is a bug here, but I think there is also confusion about what you're trying to do.

Calling `.agg(pl.col("Profit"))` returns a list of all profits--one for each country value:

```python
>>> df.group_by("Country").agg(col("Profit"))
shape: (6, 2)
┌────────────────┬─────────────────────┐
│ Country        ┆ Profit              │
│ ---            ┆ ---                 │
│ str            ┆ list[i64]           │
╞════════════════╪═════════════════════╡
│ Canada         ┆ [590, 590, … 630]   │
│ Germany        ┆ [160, 53, … 746]    │
│ Australia      ┆ [1366, 1188, … 655] │
│ United Kingdom ┆ [1053, 1053, … 112] │
│ France         ┆ [427, 427, … 655]   │
│ United States  ┆ [524, 407, … 542]   │
└────────────────┴─────────────────────┘
```

Calling `col("Profit") > 1000` then returns lists of True/False values:

```python
df.group_by("Country").agg(col("Profit") > 1000))
shape: (6, 2)
┌────────────────┬─────────────────────────┐
│ Country        ┆ Profit                  │
│ ---            ┆ ---                     │
│ str            ┆ list[bool]              │
╞════════════════╪═════════════════════════╡
│ Germany        ┆ [false, false, … false] │
│ United States  ┆ [false, false, … false] │
│ United Kingdom ┆ [true, true, … false]   │
│ Canada         ┆ [false, false, … false] │
│ France         ┆ [false, false, … false] │
│ Australia      ┆ [true, true, … false]   │
└────────────────┴─────────────────────────┘
```

This is probably not what you intended (my guess is you meant `col("Profit").sum() > 1000`). But regardless, here is where the alias fails:

```python
df.group_by("Country").agg((col("Profit") > 1000).alias("test"))
```
```
polars.exceptions.ComputeError: returned aggregation is of different length: 193 than the groups length: 2
```

This appears to be failing becausethe lists are of different lengths. The 193 changes if you rerun the command over and over.

This error doesn't occur if you simply aggregate into a list, but once you do another operation, the alias appears to fail.
