### ISSUE TITLE
Add union `union`/`or` operator to combine Enums

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#14962]
### Description

It would be very useful to be able to create a new Enum by combining two other enums, as in:

```python
>>> enum1 = pl.Enum(["a", "b", "c"])
>>> enum2 = pl.Enum(["c", "d", "e"])
>>> enum1 | enum2
Enum(categories=['a', 'b', 'c', 'd', 'e'])
```

**Comment by avimallu** [comment]
I feel that a lot of features that Polars users are looking for in Categorical or Enum data types can be referenced back to the [`forcats` package ](https://forcats.tidyverse.org/)from R's `tidyverse`.
