### ISSUE TITLE
Nalgebra support

### ISSUE THREAD

**Issue by j-h-stevens** [pola-rs/polars#14985]
### Description

Convert Polars DataFrame to Nalgebra's DMatrix; similar functionality as "to_ndarray<N>".

**Comment by orlp** [comment]
I don't think we want to add this at this point. You can write the conversion from `ndarray` to `DMatrix` yourself, or use a crate like https://lib.rs/crates/nshare (haven't tested it, `ndarray` recommends it).

**Comment by LockedThread** [comment]
> When the Rust tabular data/tensor data community agrees on an interchange format / common library we'll be more than happy to support it, but I don't feel like adding a different export and conditional compilation / features for every new matrix / tensor library under the sun.

ndarray is having some [maintainership turmoil right now](https://github.com/rust-ndarray/ndarray/issues/1272). My company has moved to [nalgebra](https://github.com/dimforge/nalgebra) because of it's vibrant community and amazing documentation.

**Comment by akern40** [comment]
@LockedThread I'm sorry to hear that `ndarray` wasn't fulfilling your company's needs! I'd really like to hear some more about what made you switch over, what features were missing, what documentation was needed, etc. This isn't the place to do that, but if you head to that issue you linked to (rust-ndarray/ndarray#1272) and scroll to the bottom, I'm soliciting feedback from the community. Would love to have your participation.

**Comment by LockedThread** [comment]
> @LockedThread I'm sorry to hear that `ndarray` wasn't fulfilling your company's needs! I'd really like to hear some more about what made you switch over, what features were missing, what documentation was needed, etc. This isn't the place to do that, but if you head to that issue you linked to (rust-ndarray/ndarray#1272) and scroll to the bottom, I'm soliciting feedback from the community. Would love to have your participation.

Thank you for reaching out. I put a comment with our major reasons in the other chat.
