### ISSUE TITLE
Confusing typo in the heredoc of the `Series.replace` method

### ISSUE THREAD

**Issue by scur-iolus** [pola-rs/polars#15008]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There is a typo in the Python documentation [on this page](https://docs.pola.rs/py-polars/html/reference/series/api/polars.Series.replace.html#polars.Series.replace) regarding the `old` argument:

> Also accepts a mapping of values to their replacement as syntactic sugar for `replace(new=Series(mapping.keys()), old=Series(mapping.values()))`.

In this short code sample, `new` and `old` have been mistakenly switched (see also the example provided).

This should be easy to fix!

### Expected behavior

Instead, it should be:

> Also accepts a mapping of values to their replacement as syntactic sugar for `replace(old=Series(mapping.keys()), new=Series(mapping.values()))`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             Linux-5.15.0-100-generic-x86_64-with-glibc2.31
Python:               3.11.8 (main, Feb 25 2024, 16:41:26) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Good catch.
