### ISSUE TITLE
Mode Value option for fill null

### ISSUE THREAD

**Issue by h4ck4l1** [pola-rs/polars#15007]
### Description

Fill the most repeated values in the column in place of null.
I don't know how you would do this in a very wide dataset i.e., with lots of columns

**Comment by cmdlineluser** [comment]
Do you mean you want to do this?

```python
df.with_columns(
    pl.all().fill_null(pl.all().drop_nulls().mode().first())
)
```

**Comment by h4ck4l1** [comment]
Yes, Thankyou.
but also having only mean in strategy, without mode feels weird

**Comment by cmdlineluser** [comment]
Ah okay - so you are asking for `.fill_null(strategy="mode")` to be added?

I think you can leave the issue open until you get an official response from the devs in that case.
