### ISSUE TITLE
Add column selector equivalent to `any_of`

### ISSUE THREAD

**Issue by TylerGrantSmith** [pola-rs/polars#15023]
### Description

In `dplyr`/`tidyselect` there are selectors that allow for the strict or non-strict selection of columns.  
 https://tidyselect.r-lib.org/reference/all_of.html

In my particular use case I want to be able to use something like `df.select(cs.any_of(vars))` and have it not error if `vars` contains names not found in the data.  This can be crudely replicated right now using a pattern like `df.select(~~cs.by_name(*vars))`

```python
import polars as pl
import polars.selectors as cs

vars = ["huey", "duey", "louie"]
df = pl.DataFrame({"huey": [], "duey": []})

df.select(~~cs.by_name(*vars))
 # shape: (0, 2)
# ┌──────┬──────┐
# │ huey ┆ duey │
# │ ---  ┆ ---  │
# │ null ┆ null │
# ╞══════╪══════╡
# └──────┴──────┘
```

**Comment by mcrumiller** [comment]
Also the simple:

```python
df.select(c for c in vars if c in df.columns)
```

**Comment by TylerGrantSmith** [comment]
> Also the simple:
> 
> ```python
> df.select(c for c in vars if c in df.columns)
> ```

Sure but that breaks down if you start from `pl.scan_csv` instead of `df`

**Comment by cmdlineluser** [comment]
If it is of any interest - my initial thought was set intersection:

```python
cs.all() & cs.by_name(vars)
```
