### ISSUE TITLE
polars-arrow-0.38.2 no `TimeDelta` in the root

### ISSUE THREAD

**Issue by rs0d** [pola-rs/polars#15026]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

```

### Issue description

use chrono::{DateTime, Duration, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, TimeDelta};
  |                                   Duration::try_milliseconds(v).expect("out-of-range in duration conversion")
    |               ^^^^^^^^^^^^^^^^
    |               |
    |               function or associated item not found in `Duration`
    |               help: there is an associated function with a similar name: `milliseconds`                                                 ^^^^^^^^^ no `TimeDelta` in the root

### Expected behavior

![1](https://github.com/pola-rs/polars/assets/34772657/9415c251-4bb2-456c-8966-3f5d01b083ac)
![5](https://github.com/pola-rs/polars/assets/34772657/6f3ae832-403d-4ebf-9214-00845d61ac86)
![2](https://github.com/pola-rs/polars/assets/34772657/96add312-3726-4714-b20a-e9b4ea35ef2c)

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

**Comment by ritchie46** [comment]
Run  `cargo update`.
