### ISSUE TITLE
Default to Arrow String type instead of LargeString

### ISSUE THREAD

**Issue by kevinjqliu** [pola-rs/polars#15047]
### Context
I noticed that Polars converts Python string to Arrow `LargeString` type when the Dataframe's `.to_arrow()` function is called. This can be seen in [this example](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.to_arrow.html#polars.DataFrame.to_arrow).

Digging into the Rust code, string is converted to the Arrow `LargeUtf8` data type. ([1](https://github.com/pola-rs/polars/blob/82932c65db24e5542e45fb35374a46142b417ddc/crates/polars-core/src/datatypes/dtype.rs#L376), [2](https://github.com/pola-rs/polars/blob/82932c65db24e5542e45fb35374a46142b417ddc/crates/polars-core/src/series/into.rs#L124)) 
It looks like in Rust, there's a `pl_flavor` boolean flag that can be set to use the regular Arrow string instead ([1](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#method.to_arrow_field), [2](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#method.try_to_arrow)) but this is not available in Python. 

According to the Arrow docs, LargeString "may not be supported by all Arrow implementations. Unless you need to represent data larger than 2GB, you should prefer string()." ([doc](https://arrow.apache.org/docs/python/generated/pyarrow.large_string.html#pyarrow.large_string)).

Because of the `LargeString` Arrow data type, I encountered issues integrating the Python Iceberg (pyiceberg) library with Polars. See https://github.com/pola-rs/polars/issues/9795#issuecomment-1992104377. Granted the issue can be fixed upstream in the pyiceberg library by integrating LargeString https://github.com/apache/iceberg-python/issues/520. 

### Ask
Given the above, I think it's a good idea to default to the regular Arrow string when converting from Dataframe to Arrow.

**Comment by ritchie46** [comment]
We will not do that. Arrow default string can only hold 2GB of data per column, leading to all kinds of slicing requirements. We deem the default string utterly unusable for our use cases. You can always cast from `LargeString` to `String` and implement your own slicing if required.

**Comment by kevinjqliu** [comment]
> We deem the default string utterly unusable for our use cases

I'm still new to Polars. What are some use cases of `LargeString`? 


> You can always cast from LargeString to String and implement your own slicing if required.

We will probably do this for pyiceberg. https://github.com/apache/iceberg-python/issues/520

> It looks like in Rust, there's a pl_flavor boolean flag that can be set to use the regular Arrow string instead ([1](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#method.to_arrow_field), [2](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#method.try_to_arrow)) but this is not available in Python.

Is it feasible to expose this boolean flag in py-polars as well?

**Comment by deanm0000** [comment]
`pl_flavor` doesn't refer to the difference between a [`large_string`](https://arrow.apache.org/docs/python/generated/pyarrow.large_string.html#pyarrow.large_string) and a [`string`](https://arrow.apache.org/docs/python/generated/pyarrow.string.html). It refers to the difference between a `large_string` and a [`utf8_view`](https://github.com/apache/arrow/blob/98a0fc85709970e3270c2dd29ef077d60fa10f74/cpp/src/arrow/type.cc#L3106-L3109) which doesn't seem to be implemented in pyarrow yet.

It seems @ritchie46 intended to close this as not planned so I'll do that now. Sorry if I'm mistaken on that point.

**Comment by ritchie46** [comment]
> I'm still new to Polars. What are some use cases of LargeString?

Our in-memory engine favors large chunks (often single chunked dataframes). It is pretty easy to reach the 2GB string limit on user data that way.

> Is it feasible to expose this boolean flag in py-polars as well?

This is to convert to string_view and is only temporary until arrow consumers implement `binview`.
