### ISSUE TITLE
Unsorted min/max on all-NaN array returns inf/-inf

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#15058]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.Series('x', 2 * [float('nan')]).to_frame().select(min=pl.min('x'), max=pl.max('x'))
shape: (1, 2)
┌─────┬──────┐
│ min ┆ max  │
│ --- ┆ ---  │
│ f64 ┆ f64  │
╞═════╪══════╡
│ inf ┆ -inf │
└─────┴──────┘
```

### Issue description

.

### Expected behavior

Should probably both return `NaN`?

### Installed versions

0.20.15

**Comment by orlp** [comment]
Yes, these should both return `nan`.
