### ISSUE TITLE
write categorical to csv without casting

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#1506]
First will fix upstream: https://github.com/jorgecarleitao/arrow2/issues/508

**Comment by ghuls** [comment]
Would it be hard to read certain columns of a CSV file directly to a Categorical?

**Comment by ritchie46** [comment]
> Would it be hard to read certain columns of a CSV file directly to a Categorical?

We'd need to write a builder. Currently we only create them from iterators.

**Comment by ritchie46** [comment]
@ghuls it is quite complicated. Every thread must synchronize the string cache and later in rechunking we also need to do work to keep the catergories in sync.
