### ISSUE TITLE
Reading the same file with different paths

### ISSUE THREAD

**Issue by MatsMoll** [pola-rs/polars#15113]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
first_df = pl.scan_parquet("https://raw.githubusercontent.com/MatsMoll/aligned-example/main/data/loan_table.parquet").collect()
second_df = pl.scan_parquet("https://raw.githubusercontent.com/MatsMoll/aligned-example/main/data/zipcode_table.parquet").collect()
```

### Issue description

Issue on `0.20.15`:

<img width="1451" alt="Screenshot 2024-03-17 at 19 46 32" src="https://github.com/pola-rs/polars/assets/4439131/f30df767-bdad-4bb1-bdaf-1560fe0b4c4b">

### Expected behavior

Expected result working on `0.20.10`
<img width="1450" alt="Screenshot 2024-03-17 at 19 47 32" src="https://github.com/pola-rs/polars/assets/4439131/a76004e2-fabb-4e1b-8022-00a1d6194dca">

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             macOS-14.0-arm64-arm-64bit
Python:               3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.13.0
fastexcel:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.1
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              12.0.1
pydantic:             2.5.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by mcrumiller** [comment]
Can you explain what exactly the issue is?

**Comment by MatsMoll** [comment]
@mcrumiller When trying to read two different files, will it return the first read file, as shown in the images in the "Issue description" section.
