### ISSUE TITLE
Conditional conversion to date fails in column with multiple date formats

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#15134]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

In [1]: import polars as pl

In [2]: df = pl.DataFrame({'d': ['2024-03-18', '2000-01-01', 'Apr 20, 2021', 'May 07, 2020']})

In [3]: df
Out[3]: 
shape: (4, 1)
┌──────────────┐
│ d            │
│ ---          │
│ str          │
╞══════════════╡
│ 2024-03-18   │
│ 2000-01-01   │
│ Apr 20, 2021 │
│ May 07, 2020 │
└──────────────┘

In [4]: df = df.with_columns(
   ...:     pl.when(pl.col('d').str.contains("-", literal=True))
   ...:                 .then(pl.col('d').str.to_date("%Y-%m-%d"))
   ...:                 .otherwise(pl.col('d').str.to_date("%b %d, %Y")))


```

Error:
```
ComputeError: conversion from `str` to `date` failed in column 'd' for 2 out of 4 values: ["Apr 20, 2021", "May 07, 2020"]

```

### Issue description

When converting two different date formats in the same column, it fails, as shown in the example.

### Expected behavior

The example should work.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             Linux-6.1.0-1035-oem-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

```

Also, ran it with:

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             Linux-6.1.0-1035-oem-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

</details>

**Comment by MarcoGorelli** [comment]
hi @DeflateAwning - I think you want to set `strict=False` here

**Comment by MarcoGorelli** [comment]
indeed that works:
```

In [5]: In [4]: df = df.with_columns(
   ...:    ...:     pl.when(pl.col('d').str.contains("-", literal=True))
   ...:    ...:                 .then(pl.col('d').str.to_date("%Y-%m-%d", strict=False))
   ...:    ...:                 .otherwise(pl.col('d').str.to_date("%b %d, %Y", strict=False)))

In [6]: df
Out[6]:
shape: (4, 1)
┌────────────┐
│ d          │
│ ---        │
│ date       │
╞════════════╡
│ 2024-03-18 │
│ 2000-01-01 │
│ 2021-04-20 │
│ 2020-05-07 │
└────────────┘
```

closing then, but thanks for the report!

**Comment by DeflateAwning** [comment]
Hold on hold on, I don't want strict though. I want it to fail _if_ neither of the date formats is valid. 

It appears that it's trying to evaluate the dates early, regardless of the `pl.when(...)` condition being true. 

This still seems like unexpected behaviour. Can you please make a case for why this is expected?

**Comment by MarcoGorelli** [comment]
> It appears that it's trying to evaluate the dates early, regardless of the pl.when(...) condition being true.

Yup, that's the case, see the warning in https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.when.html

**Comment by DeflateAwning** [comment]
Huh fair enough; I guess it'd be nice to be able to turn that "feature" off, but that would have to go in a separate ticket.
