### ISSUE TITLE
SQL Query Hangs When Using scan_parquet off S3

### ISSUE THREAD

**Issue by stephenskory** [pola-rs/polars#15172]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This version works giving the output supplied

```python
import polars as pl
df0 = pl.DataFrame({"foo": ["a", "b", "c"], "bar": [0, 1, 2]}).lazy()
df1 = pl.DataFrame({"muh": ["x", "y", "z"], "bar": [0, 1, 2]}).lazy()
ctx = pl.SQLContext(register_globals=True)
query = f"""SELECT df0.foo, df0.bar, df1.muh
FROM df0
JOIN df1 ON df0.bar = df1.bar
WHERE df0.bar IN (0, 1)"""
out = ctx.execute(query).collect()
print(out)
```

I saved the dataframes to disk (e.g. `df0.write_parquet("/tmp/df0.parquet")`), and this works:

```python
import polars as pl
df0 = pl.read_parquet("/tmp/df0.parquet")
df1 = pl.read_parquet("/tmp/df1.parquet")
ctx = pl.SQLContext(register_globals=True)
# snip...
```

Lazy loading locally works as well:

```python
import polars as pl
df0 = pl.scan_parquet("/tmp/df0.parquet")
df1 = pl.scan_parquet("/tmp/df1.parquet")
ctx = pl.SQLContext(register_globals=True)
# snip...
```

I then uploaded those two `df` files to s3 for the next two tries. This first version works giving the same output as before (all examples above and below are on an EC2 instance):

```python
import polars as pl
import boto3
session = boto3.session.Session()
credentials = session.get_credentials().get_frozen_credentials()
storage_options = {
        "aws_access_key_id": credentials.access_key,
        "aws_secret_access_key": credentials.secret_key,
        "aws_session_token": credentials.token,
        "aws_region": session.region_name,
    }
df0 = pl.read_parquet("s3://bucket/df0.parquet",
                    storage_options=storage_options)
df1 = pl.read_parquet("s3://bucket/df1.parquet",
                    storage_options=storage_options)
ctx = pl.SQLContext(register_globals=True)
# snip...
```

If I take the above example and _only_ swap the two instances of `read_parquet` for `scan_parquet`, the program hangs and the only way to free the command line is to `kill -9` the process.

```python
# snip...
df0 = pl.scan_parquet("s3://bucket/df0.parquet",
                    storage_options=storage_options)
df1 = pl.scan_parquet("s3://bucket/df1.parquet",
                    storage_options=storage_options)
# snip...
# hang...
```

### Log output

```shell
join parallel: true
POLARS PREFETCH_SIZE: 16
querying metadata of 1/1 files...
reading of 1/1 file...
POLARS PREFETCH_SIZE: 16
querying metadata of 1/1 files...
parquet file must be read, statistics not sufficient for predicate.
POLARS ROW_GROUP PREFETCH_SIZE: 128
reading of 1/1 file...
parquet file must be read, statistics not sufficient for predicate.
POLARS ROW_GROUP PREFETCH_SIZE: 128
```

### Issue description

I think the code examples show basically the problem. Doing a JOIN in-memory works, doing local both eager and lazy works, and with eager `read_parquet` off of S3. However, doing the same with lazy loading off S3 results in a hard-hang.

When I do an operationally equivalent test with actual data on S3 (~100mb), all the same cases work/hang. With lazy loading off S3 I do see a network traffic and CPU load spike, but no output and the same hang. When the program is hanging I do not see any network or CPU load after the initial network/CPU spike.

### Expected behavior

```shell
shape: (2, 3)
┌─────┬─────┬─────┐
│ foo ┆ bar ┆ muh │
│ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ str │
╞═════╪═════╪═════╡
│ a   ┆ 0   ┆ x   │
│ b   ┆ 1   ┆ y   │
└─────┴─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-5.15.0-1055-aws-aarch64-with-glibc2.31
Python:               3.11.5 (main, Sep 11 2023, 13:14:08) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               0.9.0
matplotlib:           3.8.0
numpy:                1.24.3
openpyxl:             3.0.10
pandas:               2.1.4
pyarrow:              11.0.0
pydantic:             1.10.12
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

**Comment by stephenskory** [comment]
FWIW I just ran the above examples on my laptop (M1 Mac) and all examples _including_ the lazy-S3 version worked. This indicates that _something_ is amiss on the EC2 instance with my Python/Polars stack, but I'm still stuck. Any ideas or suggestions? Just re-install everything? Is there a way to get any kind of useful error message?

**Comment by ritchie46** [comment]
Does this occur in the dataframe API as well?

**Comment by aberres** [comment]
I am runing into this issue with `0.20.16` when reading Parquet files from Google Cloud Buckets with code like this

```python
df_pl = pl.concat(
    (pl.scan_parquet(c.url, storage_options=storage_options) for c in results),
    how="diagonal",
    # Ideally this reduces the memory usage
    rechunk=False,
).collect()
```
