### ISSUE TITLE
Enum literals evaluate to equal for CSE when one dtype is subset of another

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#15170]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If two enums are used in a `collect` with CSE enabled, then their literals will evaluate to true, even if they have different categories, *as long as one's categories is a subset of the other's*.

```python
import polars as pl

dt1 = pl.Enum(["a"])         # CAUSES ERROR
# dt1 = pl.Enum(["a", "c"])  # DOES NOT CAUSE ERROR -- dt1 is not a subset of dt2
dt2 = pl.Enum(["a", "b"])

out = pl.LazyFrame().select(
    pl.lit("a", dtype=dt1).alias("dt1"),
    pl.lit("a", dtype=dt2).alias("dt2"),
).collect()

print(out.dtypes)
```
Second literal should have `categories=['a', 'b']`.
```
[Enum(categories=['a']), Enum(categories=['a'])]
```

### Installed versions

main

**Comment by mcrumiller** [comment]
@c-peters

**Comment by c-peters** [comment]
There seems to be bug related to equality check for the underlying categories. It is not exhaustive at the moment

**Comment by mcrumiller** [comment]
@c-peters I managed to simplify the example a bit.

**Comment by mcrumiller** [comment]
I found the issue. Will probably need some helping making the appropriate test, as it's not really enum-related.
