### ISSUE TITLE
Unsorted positional inputs to pl.Expr.is_between should be sorted or raise an error

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#15185]
### Description

Polars is very forgiving regarding the order of the inputs to `pl.Expr.is_between`

Technically no value satisfies `10 < x < 0` - but also that does not make much sense.

```python

pl.DataFrame({
    'x': [1,2,3,4,5,6]
}).with_columns(
    x1 = pl.col('x').is_between(0,10),
    x2 = pl.col('x').is_between(10,0),
)
shape: (6, 3)
┌─────┬──────┬───────┐
│ x   ┆ x1   ┆ x2    │
│ --- ┆ ---  ┆ ---   │
│ i64 ┆ bool ┆ bool  │
╞═════╪══════╪═══════╡
│ 1   ┆ true ┆ false │
│ 2   ┆ true ┆ false │
│ 3   ┆ true ┆ false │
│ 4   ┆ true ┆ false │
│ 5   ┆ true ┆ false │
│ 6   ┆ true ┆ false │
└─────┴──────┴───────┘
```

Maybe there should be an error if the lower bound is greater than the upper bound.

The current behavior is maybe ok if the user passes `lower_bound=10`, `upper_bound=0`

but something like
```python
bounds = (0, -10)
df.filter(pl.col('x').is_between(*bounds))
```

Should either be equivalent to 
```python

df.filter(pl.col('x').is_between(-10, 0))
```
or raise an error

**Comment by mcrumiller** [comment]
Addendum: `in_bounds` would also allow us to extend `is_between` to array dtypes in an obvious way, where `Y.is_between(X1, X2)` evaluates to true iff `x1_i <= y_i <= x2_i` for all `i`. With the current definition this is technically true but it's a bit ambiguous from the wording.
