### ISSUE TITLE
Community PR reviews

### ISSUE THREAD

**Issue by Goldmaa** [pola-rs/polars#15203]
### Description

Adding community PR reviews could be useful - improves confidence in code for reviewers with merge permissions and once a community member has reviewed a PR it also allows them to pin this repo in their profile (spreading it)

**Comment by stinodego** [comment]
I disabled this because we got some random people approving PRs with 'LGTM'. That is noise I would like to avoid.

Anyone can review a PR in this repo, you just cannot 'approve' or 'request changes'. That makes sense to me and I'd like to keep it that way.

Also, I believe anyone can pin any repo to their profile. That is not tied to reviews.

**Comment by Goldmaa** [comment]
@stinodego you have to contribute to the repo in some way - before I made this issue, I couldn't pin this repo (it wouldn't show up in the search bar when you click to edit pins) - I could immediately after I created the issue.
Also see GitHub documentation here:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile
![image](https://github.com/pola-rs/polars/assets/90787028/db8fa0d4-fac5-4acc-abe8-f64b5afb972d)
The comment on noise does make complete sense though. Random idea, maybe have an issue people can comment on to "contribute" then recommend this at the bottom of the README followed by pinning? I doubt it would be that important either way though

**Comment by stinodego** [comment]
> The comment on noise does make complete sense though. Random idea, maybe have an issue people can comment on to "contribute" then recommend this at the bottom of the README followed by pinning? I doubt it would be that important either way though

I don't think that's necessary. Getting people to pin Polars to their profile shouldn't be a goal. If they contribute, they can pin it. Sounds fair to me. No need to work around GitHub policies here.
