### ISSUE TITLE
concat fails with data frames containing new Date or Datetime datatypes

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#1520]
#### Are you using Python or Rust?

Python3.8, Python3.9, Python3.10 (all are affected).

#### What version of polars are you using?

0.10.2

#### What operating system are you using polars on?

Linux Mint 20.2 Uma, base: Ubuntu 20.04 focal

#### Describe your bug.

The concat function does not work properly with series that are Date or Datetime

#### What are the steps to reproduce the behavior?
Here is a simple example:

```python
import polars as pl

# Step 1: create two data frames
df_1 = pl.DataFrame({
    "my_date" : ["2020-01-01", "2021-01-01"],
    "my_num" : [2020, 2021]
})

df_2 = pl.DataFrame({
    "my_date" : ["2020-07-01", "2021-07-01"],
    "my_num" : [2020, 2021]
})

# Step 2: convert to Date
df_1 = df_1.lazy().with_column(
            pl.col("my_date")
            .str.strptime(pl.datatypes.Date, "%Y-%m-%d")
            .keep_name()).collect()

df_2 = df_2.lazy().with_column(
            pl.col("my_date")
            .str.strptime(pl.datatypes.Date, "%Y-%m-%d")
            .keep_name()).collect()

# Step 3: concatenate (error occurs)
tmp = pl.concat([df_1, df_2])
```

#### What is the actual behavior?
I receive the following error.
```
thread '<unnamed>' panicked at 'implementation error, cannot get ref Int32 from Date', /github/workspace/polars/polars-core/src/series/mod.rs:651:13
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.10/site-packages/polars/functions.py", line 52, in concat
    out = pl.wrap_df(_concat_df(items))
pyo3_runtime.PanicException: implementation error, cannot get ref Int32 from Date
```

#### What is the expected behavior?
This code does work if Step #2 is commented out (i.e., the dates are left as strings).  

Also note that this code also fails if the conversion in Step #2 is to polars.datatypes.Datetime.  (The error is almost identical - with Int64 replacing Int32 in the error message above).

This issue came about when I updated previously working code that concatenated data frames with multiple series previously typed as Date32 and Date64.

#### Some other feedback
Polars is so incredibly fast (and feature-rich) that I find myself abandoning R and its data.table package.  Indeed, one guilty pleasure is to code lots and lots of steps with "lazy" data frames and then run collect() at the end -- and then sit back to watch in htop as the cores on my Threadripper Pro go to work.  It's ahhhh ... pretty amazing!

**Comment by ritchie46** [comment]
Thanks for the issue report. We have refactored the date/datetime backed code to allow for more future types (a time type and timezones are in scope). 

This should be fixed by #1522. I have also immedeately released a patch to pypi (so if you try again in a few hours it should work). 


> Polars is so incredibly fast (and feature-rich) that I find myself abandoning R and its data.table package. Indeed, one guilty pleasure is to code lots and lots of steps with "lazy" data frames and then run collect() at the end -- and then sit back to watch in htop as the cores on my Threadripper Pro go to work. It's ahhhh ... pretty amazing!

Haha. Can we put this quote on the website? :smile:

On that note, there is also a new function [pl.concat_all](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.collect_all.html?highlight=collect_all#polars.collect_all). This allows you to put multiple `lazy` dataframes on the polars thread pool. :rocket:
