### ISSUE TITLE
Upgrade PyO3 to 0.21 and switch to new API

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#15215]
### Description

In PyO3 0.21, `&'py PyAny` will be replaced by `Bound<'py, PyAny>`. The benefits for upgrading are increased performance, the costs of not upgrading are that the old API is deprecated and will, eventually, go away: https://polar.sh/davidhewitt/posts/replacing-pyo3-api-pt1

https://pyo3.rs/latest/migration documents the upgrade process (at time of writing 0.21 is still beta, but will presumably be released soon).  Based on their suggestions, I think this would look like this for Polars:

1. First PR: Switch to 0.21, enable `gil-refs` feature, fix other migration issues.
2. A series of PRs that migrate over to `Bound`. The development process would involve disabling `gil-refs` temporarily, locally only, to spot APIs that need migration, but given this would probably be a series of PRs, the feature should continue to be on in `main`.
3. Final PR: When no deprecation warnings are left, disable `gil-refs`.

* [x] #15621
* [x] #15666
* [x] #15669
* [x] #15785
* [x] #15864
* [x] #15890
* [x] #16078
* [x] #16142 
* [x] #16155 
* [ ] https://github.com/pola-rs/pyo3-polars/issues/81
* [x] #16158

**Comment by itamarst** [comment]
This is something I can help work on.

**Comment by stinodego** [comment]
Yes we will definitely upgrade to the new PyO3 version when it's released. I had planned to work on that myself but if it's something you're interested in working on I think it's fine if you want to do the honors here.

**Comment by itamarst** [comment]
0.21.1 is out, so I will start on this either this week or next.

**Comment by stinodego** [comment]
> Something about support for chrono? Need to get reminder from @stinodego

PyO3 has support for the Python `datetime` module:
https://pyo3.rs/main/doc/pyo3/types/struct.pydatetime

However, this was never available under the `abi3` feature flag.

So we have a bunch of workarounds in place to materialize `datetime` objects. Specially, we have defined Python functions here:
https://github.com/pola-rs/polars/blob/main/py-polars/polars/_utils/convert.py

...that are called from Rust, for example here:
https://github.com/pola-rs/polars/blob/main/py-polars/src/conversion/any_value.rs#L162-L173

The 0.21 release notes mention:

> Extended chrono / datetime conversions, including support for the abi3 feature and the chrono-tz crate

So I am expecting that we can now take advantage of native PyO3 datetime support. And I expect a good performance boost + code cleanup to come from this.

**Comment by itamarst** [comment]
I'm gonna say this is done, insofar as it covers the main Polars repository, and the pyo3-polars issue is already filed for that repository.

**Comment by stinodego** [comment]
Thanks a lot for the thorough work @itamarst !
