### ISSUE TITLE
Add parameter `name` to `GroupBy.len()`

### ISSUE THREAD

**Issue by mgirlich** [pola-rs/polars#15222]
### Description

The column created by `GroupBy.len()` is always called `len`. It would be handy to have an argument `name` to change the name instead of having to use `rename()`.

**Example**
```python
df = pl.DataFrame(
    {
        "a": ["apple", "apple", "orange"],
        "b": [1, None, 2],
    }
)
df.group_by("a").len().rename({"len": "n"})
```

could change to

```python
df.group_by("a").len(name="n")
```

**Comment by cmdlineluser** [comment]
The GroupBy methods are shortcuts for `.agg` 

https://github.com/pola-rs/polars/blob/474ac3478f8117f6bdc4992fae21f57c3bfdd86d/py-polars/polars/dataframe/group_by.py#L474

Using it directly could also be an option instead of `.rename`

```python
df.group_by("a").agg(n = pl.len())
```

**Comment by mgirlich** [comment]
Good point. I would still think `len(name="n")` would be useful as - to me - it feels more expressive than the option with `agg()`.
