### ISSUE TITLE
Add shortcut for `explode().unnest()`

### ISSUE THREAD

**Issue by mgirlich** [pola-rs/polars#15223]
### Description

When reading data from JSON I frequently have columns of type `list[struct[n]]`, e.g.

```python
df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [
            [{"x": 1, "y": "a"}, {"x": 2, "y": "b"}],
            [{"x": 3, "y": "c"}, {"x": 4, "y": "d"}],
            None
        ]
    }
)
```

and then extract the data in `b` to a new dataframe e.g. to write it into a database:

```python
(
    df
    # optionally remove rows with empty `b` values
    .filter(pl.col("b").list.len() > 0)
    .explode("b")
    .unnest("b")
)
# ┌─────┬─────┬─────┐
# │ a   ┆ x   ┆ y   │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ str │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 1   ┆ a   │
# │ 1   ┆ 2   ┆ b   │
# │ 2   ┆ 3   ┆ c   │
# │ 2   ┆ 4   ┆ d   │
# │ 2   ┆ 5   ┆ e   │
# └─────┴─────┴─────┘
```

It would be nice to have a helper for this common pattern.

**Comment by deanm0000** [comment]
@stinodego any interest in having this added or is this an example where if the user wants a convenience function then they should just make one for their own usage?

@mgirlich you can monkey patch this in pretty easily

```
pl.DataFrame.explest = lambda df, col: (
    df.explode(col).unnest(col)
)
```

then it's just

```
df.explest('b')
```

**Comment by stinodego** [comment]
I don't think a combined explode/unnest is too useful. Calling explode followed by unnest is perfectly fine. These are concepts that everyone understands. I don't want to add another way to do this.

Adding a recursive 'fully unnest/explode' functionality would probably be useful though.

**Comment by alexander-beedie** [comment]
> I don't think a combined explode/unnest is too useful. Calling explode followed by unnest is perfectly fine. These are concepts that everyone understands. I don't want to add another way to do this.

@stinodego: you're not even a little bit tempted by `unplode`? 😁

**Comment by stinodego** [comment]
Hehe, nope. If you find you're using this pattern a lot, I would recommend defining a utility function and use `pipe`:

```python
import polars as pl

def explest(df: pl.DataFrame, col: str) -> pl.DataFrame:
    return df.explode(col).unnest(col)

df.pipe(explest, "b")
```
