### ISSUE TITLE
Rename `rle()` struct fields to `len` and `value`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#15230]
### Description

Remove the plural from [`Series.rle()`](https://docs.pola.rs/docs/python/dev/reference/series/api/polars.Series.rle.html#polars.Series.rle) and [`Expr.rle()`](https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.rle.html#polars.Expr.rle) field names.

(Similar to what was done for `value_counts`: https://github.com/pola-rs/polars/issues/11462)

Current:

```python
>>> pl.Series([1, 1, 2, 3]).rle().struct.unnest()
shape: (3, 2)
┌─────────┬────────┐
│ lengths ┆ values │
│ ---     ┆ ---    │
│ i32     ┆ i64    │
╞═════════╪════════╡
│ 2       ┆ 1      │
│ 1       ┆ 2      │
│ 1       ┆ 3      │
└─────────┴────────┘
```

Desired:

```python
>>> pl.Series([1, 1, 2, 3]).rle().struct.unnest()
shape: (3, 2)
┌─────────┬────────┐
│ len     ┆ value  │
│ ---     ┆ ---    │
│ i32     ┆ i64    │
╞═════════╪════════╡
│ 2       ┆ 1      │
│ 1       ┆ 2      │
│ 1       ┆ 3      │
└─────────┴────────┘
```

(Choosing `len` to match up with `list.len()`)

**Comment by cmdlineluser** [comment]
Side note: Would it make sense for `rle()` to also return the row index? `{index, value, len}`

The particular use-case being wanting the original row index after performing a `.filter()`

```python
df = pl.DataFrame({"foo": ["a", "a", "a", "b", "c", "c"]})

df.select(pl.col("foo").rle())
# shape: (3, 1)
# ┌───────────┐
# │ foo       │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {3,"a"}   │
# │ {1,"b"}   │
# │ {2,"c"}   │
# └───────────┘
```

We can calculate it from the length, but it's a little awkward:

```python
(df.select(pl.col("foo").rle())
   .with_columns(
      index = pl.col("foo").struct["lengths"].cum_sum().shift().fill_null(0)
   )
   #.filter(...)
)
# shape: (3, 2)
# ┌───────────┬───────┐
# │ foo       ┆ index │
# │ ---       ┆ ---   │
# │ struct[2] ┆ i32   │
# ╞═══════════╪═══════╡
# │ {3,"a"}   ┆ 0     │
# │ {1,"b"}   ┆ 3     │
# │ {2,"c"}   ┆ 4     │
# └───────────┴───────┘
```

**Comment by stinodego** [comment]
@cmdlineluser I am tempted to also change the field order of the struct to `value`/`len`. That way it matches `value_counts`. What do you think?
