### ISSUE TITLE
Support for non-uniform sample times for `ewm` functions, extending #2148

### ISSUE THREAD

**Issue by wbeardall** [pola-rs/polars#15233]
### Description

It would be very useful to be able to specify non-uniform sample times for `ewm` functionality. [Pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ewm.html) provides this using the `times` kwarg. As someone who works with non-uniform sampling in data frequently, this functionality is essential for properly calculating EW statistics.

Under a Polars design pattern, the implementation might look something like

```
df.with_columns(pl.col("data").ewm_mean(halflife="1min", times=pl.col("time")).alias("data_ewm"))
```

**Comment by MarcoGorelli** [comment]
I've added this to the polars-xdt plugin: https://marcogorelli.github.io/polars-xdt-docs/api/polars_xdt.ewma_by_time.html

I'm planning on upstreaming it to Polars in the new few weeks

For now, if you could try it out in the plugin and confirm that it does the right thing, that'd be great 🙏

**Comment by MarcoGorelli** [comment]
anyway, closing in favour of https://github.com/pola-rs/polars/issues/10794, but thanks for the issue!

**Comment by wbeardall** [comment]
Ah thank you, don't know how I missed that! I'll check out the plugin. :)
