### ISSUE TITLE
`descending` arg looks backwards in `top_k`

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#15236]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This came up here: https://discord.com/channels/908022250106667068/1082941945216782397/1220375752428753027

```python
import polars as pl
df = pl.DataFrame({'a': [1,3,2]})
df.top_k(k=1, by='a', descending=False)
```

### Log output

```shell
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 3   │
└─────┘
```

### Issue description

If I read `df.top_k(k=1, by='a', descending=False)`, I expect it to mean "get the top 1 smallest element". However, it actually finds the top 1 largest element (contradicting `descending=False`?)

Conversely, `df.top_k(k=1, by='a', descending=True)` finds the smallest element

### Expected behavior

Not sure, it requires more discussion. But for a start, there should be an issue about it :)

Polars used to have `reverse` arguments for sorting functions, but they were changed to `descending`. But in this case, `reverse` does feel quite natural

I don't really know what to suggest, but comments are very welcome

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.8 (main, Feb 25 2024, 16:39:33) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.1
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Confusing in general. I would expect the `descending` parameter to change the sorting out of the output, not what the "top" values are. We have a `bottom_k()` function for that already.

**Comment by MarcoGorelli** [comment]
> not what the "top" values are. We have a bottom_k() function for that already.

you can pass multiple values to `descending` though, so `bottom_k` isn't a full replacement:
```
In [44]: df = pl.DataFrame({'a': [1, 2, 3], 'b': [6, 5, 4], 'c': [7,8,9]})

In [45]: df.top_k(k=2, by=['a', 'b'], descending=[True, False])
Out[45]:
shape: (2, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 6   ┆ 7   │
│ 2   ┆ 5   ┆ 8   │
└─────┴─────┴─────┘
```

**Comment by mcrumiller** [comment]
I see. Seems like a single function called `extrema` would work better, but people will undoubtedly be searching for `top_k` and `bottom_k` since those are pretty prevalent in other libraries.

**Comment by mcrumiller** [comment]
A somewhat more explicit but verbose would be a `sort_method` parameter that's a list of "ascending" and "descending":

```python
import polars as pl

df = pl.DataFrame({
    "a": [1, 1, 2, 2, 3, 3],
    "b": [2, 1, 2, 1, 2, 1],
})

# (a=3, b=2)
df.top_k(k=1)

# (a=3, b=1)
df.top_k(k=1, sort_method=["ascending", "descending"])

# (a=1, b=1)
df.bottom_k(k=1) 

# (a=1, b=2)
df.bottom_k(k=1, sort_method="descending", "ascending")
```

**Comment by mcrumiller** [comment]
And actually, just renaming `descending` to `sort_descending` would be more obvious. And then the `bottom_k` parameter could be `sort_ascending`.

**Comment by MarcoGorelli** [comment]
I don't think it can just be renamed, because then the output of `sort_descending=False` actually would be sorted descending

I feel like suggesting `find_smallest`, so then code can just be updated without other changes?

Current behaviour:
```
In [46]: import polars as pl
    ...: df = pl.DataFrame({'a': [1,3,2]})
    ...: df.top_k(k=3, by='a', descending=False)
Out[46]:
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 3   │
│ 2   │
│ 1   │
└─────┘
```
Proposed new api:
```
In [46]: import polars as pl
    ...: df = pl.DataFrame({'a': [1,3,2]})
    ...: df.top_k(k=3, by='a', find_smallest=False)
Out[46]:
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 3   │
│ 2   │
│ 1   │
└─────┘
```

**Comment by mtomko** [comment]
I ran across this yesterday in a different context - it looks to me like the underlying Rust code is doing it backwards:

https://github.com/pola-rs/polars/blob/31df06d668d81aa04da975b2f66f5c6711e0572b/py-polars/polars/lazyframe/frame.py#L1550

I don't like this behavior but it feels like the Python and Rust code should be kept consistent, so my temptation would be to look in to addressing the problem upstream of the Python bindings.

**Comment by stinodego** [comment]
We will rename the parameter to `reverse` in `top_k` and `bottom_k`.
