### ISSUE TITLE
Reading CSV, Polars seems to ignore the provided Schema

### ISSUE THREAD

**Issue by djouallah** [pola-rs/polars#15254]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I am attaching a full reproducible example here, 

https://github.com/djouallah/Light_ETL_Challenge/blob/main/Light_ETL_Challenge.ipynb

```
colmn=[
'I','UNIT','XX','VERSION','SETTLEMENTDATE','RUNNO',
    'DUID','INTERVENTION','DISPATCHMODE','AGCSTATUS','INITIALMW',
    'TOTALCLEARED','RAMPDOWNRATE','RAMPUPRATE','LOWER5MIN',
    'LOWER60SEC','LOWER6SEC','RAISE5MIN','RAISE60SEC',
    'RAISE6SEC','MARGINAL5MINVALUE','MARGINAL60SECVALUE',
    'MARGINAL6SECVALUE','MARGINALVALUE','VIOLATION5MINDEGREE'
]
raw = pl.scan_csv(f'{raw_landing}/csv/*.CSV',skip_rows=1, new_columns=colmn,has_header=False, infer_schema_length=0,truncate_ragged_lines=True)
transform =(
    raw
    .filter(pl.col("I")=='D')
    .filter(pl.col("UNIT")=='DUNIT')
    .filter(pl.col("VERSION")=='3')
    .drop("XX")
    .drop("I")
)
```

### Issue description

basically, there are more than 25 columns, but Polars so far seems to account only for the total columns founds at row =1

### Expected behavior

Polars should read a csv with variable column numbers

### Installed versions

Python polars-0.20.16

**Comment by ritchie46** [comment]
Have you tried setting the full schema? Setting only `columns` will set the names of the schema, but Polars will still determine the schema itself, which in this case will likely be done based on the header.

We accept a `schema` argument that will help you completely overwrite the schema.

**Comment by djouallah** [comment]
does not seems to be working, it is still ignoring the schema

<img width="1156" alt="image" src="https://github.com/pola-rs/polars/assets/12554469/3775e885-a454-4c23-a4a8-2f455f6ac58f">

**Comment by cmdlineluser** [comment]
If I understand correctly, this appears to be a minimal repro?

Data:

```shell
wget https://nemweb.com.au/Reports/Current/Daily_Reports/PUBLIC_DAILY_202401270000_20240128040505.zip
unzip PUBLIC_DAILY_202401270000_20240128040505.zip
```

`.read_csv` works as expected.

```python
import polars as pl

pl.read_csv(
    "PUBLIC_DAILY_202401270000_20240128040505.CSV",
    skip_rows=1,
    schema=dict.fromkeys([f"column_{n}" for n in range(1, 131)], pl.String),
    has_header=False
)
# shape: (424_519, 130) # <- OK: 130 Columns
# ...
```

The same arguments with `.scan_csv` raises an exception:

```python
# ComputeError: found more fields than defined in 'Schema'
# Consider setting 'truncate_ragged_lines=True'.
```

With `truncate_ragged_lines=True` the file is read but we no longer get 130 columns.

```python
pl.scan_csv(
    "PUBLIC_DAILY_202401270000_20240128040505.CSV",
    skip_rows=1,
    schema=dict.fromkeys([f"column_{n}" for n in range(1, 131)], pl.String),
    has_header=False,
    truncate_ragged_lines=True
).collect()

# shape: (424_519, 25) # <- ERROR: 25 Columns
# ...
```

**Comment by djouallah** [comment]
Perfect is there any limitation using read_csv instead of scan ?

**Comment by cmdlineluser** [comment]
I suppose the data is not actually needed.

Simpler repro:

```python
import polars as pl
import tempfile

with tempfile.NamedTemporaryFile() as f:
    f.write(b"""
A,B,C
1,2,3
4,5,6,7,8
9,10,11
""".strip())
    f.seek(0)
    
    df = pl.read_csv(f.name, schema=dict.fromkeys("ABCDE", pl.String), truncate_ragged_lines=True)
    # shape: (3, 5)
    # ┌─────┬─────┬─────┬──────┬──────┐
    # │ A   ┆ B   ┆ C   ┆ D    ┆ E    │
    # │ --- ┆ --- ┆ --- ┆ ---  ┆ ---  │
    # │ str ┆ str ┆ str ┆ str  ┆ str  │
    # ╞═════╪═════╪═════╪══════╪══════╡
    # │ 1   ┆ 2   ┆ 3   ┆ null ┆ null │
    # │ 4   ┆ 5   ┆ 6   ┆ 7    ┆ 8    │
    # │ 9   ┆ 10  ┆ 11  ┆ null ┆ null │
    # └─────┴─────┴─────┴──────┴──────┘
    
    lf = pl.scan_csv(f.name, schema=dict.fromkeys("ABCDE", pl.String), truncate_ragged_lines=True).collect()
    # shape: (3, 3)
    # ┌─────┬─────┬─────┐
    # │ A   ┆ B   ┆ C   │
    # │ --- ┆ --- ┆ --- │
    # │ str ┆ str ┆ str │
    # ╞═════╪═════╪═════╡
    # │ 1   ┆ 2   ┆ 3   │
    # │ 4   ┆ 5   ┆ 6   │
    # │ 9   ┆ 10  ┆ 11  │
    # └─────┴─────┴─────┘
```

**Comment by filabrazilska** [comment]
Hi,
the difference between `read_csv` and `scan_csv` is in the fact that the former uses the passed-in schema for the `schema` attribute in `CsvReader` whereas the latter uses is for the `dtypes` attribute.
When changed the two behave the same (see my commit above). That said I don't know if anyone depends on the original behaviour so not sure if the maintainers are willing the accept this change.

**Comment by filabrazilska** [comment]
The documentation for `scan_csv` seems to suggest that the `schema` param should indeed be used for `schema` rather than `dtypes`: https://docs.pola.rs/py-polars/html/reference/api/polars.scan_csv.html

**Comment by djouallah** [comment]
Any updates on this?

**Comment by ritchie46** [comment]
Thanks for the report and thank you for the minimal repro @cmdlineluser. Taking a look.

**Comment by djouallah** [comment]
@ritchie46 there is a regression with the latest update

```
PanicException                            Traceback (most recent call last)
<timed exec> in <module>

[<ipython-input-11-3bc5859e5af2>](https://localhost:8080/#) in polars_clean_csv(x)
     33   z = transform.with_columns(pl.col("SETTLEMENTDATE").str.to_datetime())
     34   columns = list(set(transform.columns) - {'SETTLEMENTDATE','DUID','UNIT'})
---> 35   final=z.with_columns(pl.col(columns).cast(pl.Float64),YEAR=pl.col("SETTLEMENTDATE").dt.iso_year()).collect()
     36   return final.to_arrow()

[/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py](https://localhost:8080/#) in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager, **_kwargs)
   1815         callback = _kwargs.get("post_opt_callback")
   1816 
```
-> 1817         return wrap_df(ldf.collect(callback))
   1818 
   1819     @overload

PanicException: called `Option::unwrap()` on a `None` value

**Comment by cmdlineluser** [comment]
Thanks @djouallah - it seems that was a different issue.

I made a minimal repro for you in https://github.com/pola-rs/polars/issues/16437 which has just been fixed.

`0.20.29` will be released soon.

**Comment by evbo** [comment]
I am seeing similar behavior but for `nd_json`. Issue linked here: https://github.com/pola-rs/polars/issues/18244
