### ISSUE TITLE
Incorrect Explanation in polars.Expr.dt.timestamp

### ISSUE THREAD

**Issue by Ebraheem1** [pola-rs/polars#15275]
https://github.com/pola-rs/polars/blame/ec8f5e3a414c857a65bbb3db83720275282b14b4/py-polars/polars/expr/datetime.py#L1419-L1451

Here you show that the default value should be microseconds `us`, however, in the example you use the default as `ns`.

**Comment by mcrumiller** [comment]
Indeed.
