### ISSUE TITLE
docs(Python): Specification to the `offset` parameter in `pl.Expr.dt.truncate`

### ISSUE THREAD

**Issue by TrevorWinstral** [pola-rs/polars#15283]
### Description

# Description
In the [docs](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.dt.truncate.html) for `pl.Expr.dt.truncate` the offset parameter is described as: "Offset the window". This does not specify if the window is offset before or after the truncation is performed. For instance in the following example:

```
import polars as pl

df = (
    pl.DataFrame()
    .with_columns(
        time=pl.datetime_range(
            pl.datetime(2024, 1, 1, 8), pl.datetime(2024, 1, 10, 16), "30m"
        )
    )
    .filter(pl.col("time").dt.time().is_between(pl.time(11), pl.time(13)))
)
print(df.with_columns(truncated=pl.col("time").dt.truncate("1d", offset="12h")))
```

Which outputs:

| time                | truncated           |
| ------------------- | ------------------- |
| datetime[μs]        | datetime[μs]        |
| 2024-01-01 11:00:00 | 2024-01-01 12:00:00 |
| 2024-01-01 11:30:00 | 2024-01-01 12:00:00 |
| 2024-01-01 12:00:00 | 2024-01-01 12:00:00 |
| 2024-01-01 12:30:00 | 2024-01-01 12:00:00 |
| 2024-01-01 13:00:00 | 2024-01-01 12:00:00 |
| …                   | …                   |
| 2024-01-10 11:00:00 | 2024-01-10 12:00:00 |
| 2024-01-10 11:30:00 | 2024-01-10 12:00:00 |
| 2024-01-10 12:00:00 | 2024-01-10 12:00:00 |
| 2024-01-10 12:30:00 | 2024-01-10 12:00:00 |
| 2024-01-10 13:00:00 | 2024-01-10 12:00:00 |

We can see that the times before and after 12:00 are each truncated to the same bucket, as they each are a part of the same day, meanwhile if the window was actually being offset by 12 hours, we would expect the entries associated with times before 12:00 to be truncated to the window starting at 12:00 on the previous day. Instead what is happening is that the times are truncated to the day, and then after the truncation are offset by 12 hours. If this is the desired effect, then it should be properly documented, along the lines of: "The offset applied to each window after truncation". 

The current output can easily be replicated by doing `df.with_columns(truncated=pl.col("time").dt.truncate("1d").offset_by("12h"))`, 
meanwhile in order to offset the window by 12 hours _pre-truncation_ (which is what I implicitly assumed was going on), one has to use:
`df.with_columns(truncated=pl.col("time").dt.offset_by("-12h")).dt.truncate("1d", offset="12h"))`.

To me, with the current documentation, it seems at least unclear whether or not the window is offset pre- or post- truncation, and this should be specified. 

On a personal note I am not sure exactly what the added value of offsetting the window post-truncation with an argument to the function when it seems very natural to write it as I have (in the replication) rather than with an arg. I would implicitly assume when we say we offset the truncation window, this happens before we truncate, but this could just be a personal bias.

### Link

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.dt.truncate.html

**Comment by mcrumiller** [comment]
I think we should deprecate/remove the `truncate` parameter. It is a separate operation and we shouldn't need to tell `truncate` to perform additional operations at the beginning or the end when we can easily do them ourselves.

There must have been a reason for including it at some point. @MarcoGorelli do you know/recall?

**Comment by TrevorWinstral** [comment]
@mcrumiller Do you mean deprecate the `offset` parameter? This would also solve the documentation issue, but personally it makes sense to me to be able to offset windows when truncating in them.

**Comment by mcrumiller** [comment]
Yes, sorry. Fixed.

**Comment by MarcoGorelli** [comment]
I think this predates my involvement in the project, but I'm also not sure why `truncate` needs to have a `offset` arg...you can easily do it yourself before or after truncating

**Comment by TrevorWinstral** [comment]
So this can be handled either purely on the python side by removing `offset` from the documentation and not passing the argument onto the rust function. Or additionally by removing the functionality from the rust library. I am happy to handle all of the python and doc bits in an MR, but would need some help with the Rust side of things as I am less experienced there. I would be happy to give it a shot though.

**Comment by MarcoGorelli** [comment]
This would first need a deprecation warning, it can't be removed without notice :)

Fancy opening a pull request @TrevorWinstral ?

**Comment by MarcoGorelli** [comment]
Same for upsample, right?

**Comment by TrevorWinstral** [comment]
Will do, I will have to check how you guys handle depreciations elsewhere. Got an example on hand?

**Comment by MarcoGorelli** [comment]
There's plenty of examples in the codebase, there's a decorator for this, if you use that and fixup tests it should be good to go (sorry on my phone ATM)

**Comment by TrevorWinstral** [comment]
Alright, would you prefer this be a 'will be deprecated fix' (don't change functionality, just add warning) or an 'is deprecated' fix (remove the functionality and issue the warning)?
