### ISSUE TITLE
Create stackoverflow tag for python

### ISSUE THREAD

**Issue by CloseChoice** [pola-rs/polars#1529]
Hi @ritchie46 ,
I've seen some user questions in the issues and would ask if you'd like to create a tag on stackoverflow for `polars-python`. The [polars-rust](https://stackoverflow.com/questions/tagged/rust-polars) tag already exists. Since I have tag creation privileges on SO, I would be very glad to help out. Maybe a small series of questions would be good, so that users can be refered to SO. Just let me know what you think about that.

**Comment by ritchie46** [comment]
> Hi @ritchie46 , I've seen some user questions in the issues and would ask if you'd like to create a tag on stackoverflow for `polars-python`. The [polars-rust](https://stackoverflow.com/questions/tagged/rust-polars) tag already exists. Since I have tag creation privileges on SO, I would be very glad to help out. Maybe a small series of questions would be good, so that users can be refered to SO. Just let me know what you think about that.

You mean that we create the tag and port some of the questions to SO for discoverability? That would be great! Please do. :)

**Comment by ritchie46** [comment]
> I have created one question, but saw that somebody already created the tag yesterday. Here is the [link](https://stackoverflow.com/questions/69591233/how-to-select-rows-between-a-certain-date-range-in-polars-python/69591265#69591265). Feel free to comment or add another answer.

I upvoted. ;)
