### ISSUE TITLE
Ordered Context Expressions

### ISSUE THREAD

**Issue by Olobir** [pola-rs/polars#15292]
### Description

Hey Polars team,

It's sometimes important to ensure that expressions are evaluated in a particular order to maintain data integrity.
However, there seems to be no built-in support for ordered context expressions.
Users may use for loops as workarounds to manually enforce the desired evaluation order.

For example, if expressions depend on the results of earlier computations, it becomes challenging to ensure that these dependencies are resolved correctly without a mechanism to specify the evaluation order. In such cases, users may need to iterate over the expressions in a specific order using for loops to achieve the desired behavior.

Here is an example, where symbols are calculated by formulas with potential dependencies on prior evaluated symbols.
```
import polars as pl

data = pl.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300],
}).cast(pl.Float64)

calc = pl.DataFrame([
    {'symbol': 'AB', 'formula': 'A/B', 'order': 1},
    {'symbol': 'AC', 'formula': 'A/C', 'order': 1},
    {'symbol': 'ABAC', 'formula': 'AB/AC', 'order': 2},
])

grouped = calc.filter(pl.col('order') > 0).group_by(['order'], maintain_order=True)

for name, group in grouped:
    iterator = group.select(['symbol', 'formula']).rows()
    sql_expr = [f"{formula} AS {symbol}" for symbol, formula in iterator]
    data = data.with_columns(*pl.sql_expr(sql_expr))
print(data)
# │ A   ┆ B    ┆ C     ┆ AB  ┆ AC   ┆ ABAC │
# ╞═════╪══════╪═══════╪═════╪══════╪══════╡
# │ 1.0 ┆ 10.0 ┆ 100.0 ┆ 0.1 ┆ 0.01 ┆ 10.0 │
# │ 2.0 ┆ 20.0 ┆ 200.0 ┆ 0.1 ┆ 0.01 ┆ 10.0 │
# │ 3.0 ┆ 30.0 ┆ 300.0 ┆ 0.1 ┆ 0.01 ┆ 10.0 │
```
Is it possible/practical to implement a group-wise or ordered context for expressions?

Kind regards, Oyibo

**Comment by mcrumiller** [comment]
If you have expressions that depend on prior expressions, you have two options:

1. Use iterative `with_columns`:

    ```
    data = data.with_columns(expr_set1).with_columns(expr_set2).with_columns(expr_set3)...
    ```

3. "Re-do" the computation with each successive expression. Note that due to common subexpression elimination (if you're doing this lazily), you will not pay the penalty of recomputing each time:

    ```
    expr1 = col("a") + col("b")
    expr2 = expr / 2
    expr3 = expr2 ** 2
    data = data.lazy().with_columns(
        expr1,  # no penalty for recomputing
        expr2,  # expr1 3x and 
        expr3,  # expr2 twice
    ).collect()
