### ISSUE TITLE
[Python] pytables (HDF5) reader/writer

### ISSUE THREAD

**Issue by vsisl** [pola-rs/polars#15308]
In one of my projects, we use a python stack with pandas doing all the DataFrame stuff. We're currently depending on an SQL database but want to migrate to [pytables](https://github.com/PyTables/PyTables). It would be amazing if polars offered an easy way how to load/store data from/to _pytables HDF5_ files!

_Originally posted by @vsisl in https://github.com/pola-rs/polars/issues/3520#issuecomment-2014823686_

**Comment by stinodego** [comment]
Please refrain from opening duplicate issues.

**Comment by vsisl** [comment]
Hi @stinodego 

I didn't intend to create a duplicate issue. My feeling was that #3520 was requesting a _generic_ HDF5 reader/writer with optional higher-level APIs.

Meanwhile my intention was to open a feature request for a _specific_ HDF5 reader/writer **compatible** with pytables.

Sorry for not making this more clear. My team and I would appreciate if your consider to re-open this issue. :)

Thanks for your effort making polars great!

**Comment by stinodego** [comment]
The other issue already covers this. And it's accepted, so feel free to work on it!
