### ISSUE TITLE
String operations are returning error (Polars, Rust, v0.38.3)

### ISSUE THREAD

**Issue by PritishDsouza** [pola-rs/polars#15337]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
fn main() {
    use polars::prelude::*;

    let df = df!(
        "col_1" => &[1, 2, 3],
        "col_2" => &["Pingloo", "Igloo", "Dagloo"]
    ).unwrap();

    let df_1 = df
        .clone()
        .lazy()
        .select([col("col_2").str().ends_with(lit("loo")).alias("col_3")])
        .collect();

    println!("{:?}", df_1);
}
```

### Log output

```shell
no method named `str` found for enum `Expr` in the current scope
  --> src\main.rs:16:31
   |
16 | ...select([col("col_2").str().ends_with(lit("loo")).alias("...
   |                         ^^^ help: there is a method with a similar name: `std`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `validation` (bin "validation") due to 1 previous error
```

### Issue description

Hi Team,

I am facing this error while applying all the string operations shown on this page - https://docs.pola.rs/user-guide/expressions/strings/. I have tried executing without .str() and looked across the internet for a solution, however I could not find a solve.

The other parts of the program, leaving aside .select(), execute without any errors. Besides, the programs in the `Strings` section of the documentation do not execute even when run without any modifications.

Warm Regards,
Pritish

### Expected behavior

The program is expected to mutate a column named `col_3` with Boolean values `true` and `false`

### Installed versions

<details>

[package]
name = "validation"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = {version = "0.38.3", features = ["lazy"]}

</details>

**Comment by stinodego** [comment]
You probably just need to enable the right features. Try to enable the `strings` feature, that should solve your problem.
