### ISSUE TITLE
`pl.Expr.over` lacks examples of different mapping strategies

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#15346]
### Description

The documentation should provide examples of when you would use different mapping strategies, explain the potential benefits/use-cases/drawbacks of each one, and then show how each strategy can change/affect the output (when used correctly) and some cases that show what happen when they're used with incorrect assumptions.

### Link

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.over.html

**Comment by ritchie46** [comment]
Right.. Care to open a PR?

**Comment by cmdlineluser** [comment]
I'm not sure what `explode` is used for.

`join` could be used if wanted to return a list/multiple items.


```python
import polars as pl

df = pl.from_repr("""
┌───────┬───────┐
│ group ┆ value │
│ ---   ┆ ---   │
│ i64   ┆ i64   │
╞═══════╪═══════╡
│ 3     ┆ 4     │
│ 1     ┆ 5     │
│ 2     ┆ 6     │
│ 2     ┆ 3     │
│ 1     ┆ 2     │
│ 1     ┆ 1     │
└───────┴───────┘
""")
```

e.g. this fails

```python
try:
    df.with_columns(
       pl.col("value").head(2).over("group")
    )
except pl.ComputeError as err:
    print(f"{err=}")
    # ComputeError('the length of the window expression did not match that of the group
```

But `join` gives you the whole group as a list:

```python
df.with_columns(
   pl.col("value").head(2).over("group", mapping_strategy="join")
)
# shape: (6, 2)
# ┌───────┬───────────┐
# │ group ┆ value     │
# │ ---   ┆ ---       │
# │ i64   ┆ list[i64] │
# ╞═══════╪═══════════╡
# │ 3     ┆ [4]       │
# │ 1     ┆ [5, 2]    │
# │ 2     ┆ [6, 3]    │
# │ 2     ┆ [6, 3]    │
# │ 1     ┆ [5, 2]    │
# │ 1     ┆ [5, 2]    │
# └───────┴───────────┘
```

**Comment by cmdlineluser** [comment]
Thank you for the input @thomaslin2020 

While experimenting with `explode` I did notice this:

```python
df.with_columns(
   over = pl.col("value").over("group", mapping_strategy="explode")
)

# shape: (6, 3)
# ┌───────┬───────┬──────┐
# │ group ┆ value ┆ over │
# │ ---   ┆ ---   ┆ ---  │
# │ i64   ┆ i64   ┆ i64  │
# ╞═══════╪═══════╪══════╡
# │ 3     ┆ 4     ┆ 4    │
# │ 1     ┆ 5     ┆ 5    │
# │ 2     ┆ 6     ┆ 2    │ # <- ???
# │ 2     ┆ 3     ┆ 1    │ # <- ???
# │ 1     ┆ 2     ┆ 6    │ # <- ???
# │ 1     ┆ 1     ┆ 3    │ # <- ???
# └───────┴───────┴──────┘
```

I'm not sure if this is what the sorted note is about. (assuming this is the intended behaviour?)

**Comment by thomaslin2020** [comment]
Thanks @cmdlineluser. That is definitely a case where sorting would make sense.

Taking your example:
```python
# shape: (6, 3)
# ┌───────┬───────┬──────┐
# │ group ┆ value ┆ over │
# │ ---   ┆ ---   ┆ ---  │
# │ i64   ┆ i64   ┆ i64  │
# ╞═══════╪═══════╪══════╡
# │ 3     ┆ 4     ┆ 4    │
# │ 1     ┆ 5     ┆ 5    │
# │ 2     ┆ 6     ┆ 2    │ # <- ???
# │ 2     ┆ 3     ┆ 1    │ # <- ???
# │ 1     ┆ 2     ┆ 6    │ # <- ???
# │ 1     ┆ 1     ┆ 3    │ # <- ???
# └───────┴───────┴──────┘
```

Sorting by `group` in the way according to my post above (by grouped first occurence):
```python
# shape: (6, 3)
# ┌───────┬───────┬──────┐
# │ group ┆ value ┆ over │
# │ ---   ┆ ---   ┆ ---  │
# │ i64   ┆ i64   ┆ i64  │
# ╞═══════╪═══════╪══════╡
# │ 3     ┆ 4     ┆ 4    │
# │ 1     ┆ 5     ┆ 5    │
# │ 1     ┆ 2     ┆ 6    │ # <- ???
# │ 1     ┆ 1     ┆ 3    │ # <- ???
# │ 2     ┆ 6     ┆ 2    │ # <- ???
# │ 2     ┆ 3     ┆ 1    │ # <- ???
# └───────┴───────┴──────┘
```

We see that the ordering of `over` now matches `group`, but because we are using `with_columns`, the ordering of `group` is unchanged, so simply appending `over` to the column wouldn't make sense. I think having some of these examples in the documentation would help clarify why sorting is required in certain cases.
