### ISSUE TITLE
IpcWriter with compression

### ISSUE THREAD

**Issue by elbaro** [pola-rs/polars#1539]
#### Describe your feature request

According to a benchmark https://ursalabs.org/blog/2020-feather-v2/ ,
A feather file with compression provides faster read/write than parquet.
Can we add the compression to IpcWriter?

**Comment by jorgecarleitao** [comment]
https://github.com/jorgecarleitao/arrow2/issues/545 has been fixed. 👍

**Comment by ghuls** [comment]
Closing as writing IPC files with compression is supported in polars now.
