### ISSUE TITLE
Add rank(method="random").

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1540]
#### Describe your feature request

As of https://github.com/pola-rs/polars/pull/1222 the rank function exists with `min, max, avg, dense, ordinal` as methods.
It would be nice to have `random` too to break ties (where values between min and max are chosen in a random order).

https://stat.ethz.ch/R-manual/R-patched/library/base/html/rank.html

**Comment by sa-** [comment]
Would ordinal rank suffice if we don't care about the order?

**Comment by ghuls** [comment]
@sa- In my case I don't want that for ties the first value found will always have the best rank of that batch.

**Comment by ghuls** [comment]
@ritchie46 Shouldn't `is_consecutive_same` be `is_not_consecutive_same`?

https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/ops/unique/rank.rs#L70-L87

For implementing "random" ranking for ties, I think something like this would work:
  - Create a vector `shuffle_offsets` which stores start and end of each consecutive values of `obs`.
  - Shuffle sort_idx values for each of those slices (so ties are not in order anymore).

```rust
            let obs = is_consecutive_same.downcast_iter().next().unwrap();
            let mut shuffle_offsets = AlignedVec::with_capacity(len);

            let mut shuffle_offset: u32 = 0;

            shuffle_offsets.push(shuffle_offset);
            obs.values_iter().for_each(|b| {
                if !b {
                    shuffle_offset += 1;
                } else {
                    shuffle_offsets.push(shuffle_offset)
                }
            });

            if null_count > 0 {
                obs.iter().for_each(|b| {
                    if let Some(b) = b {
                        shuffle_offset += 1;
                        if !b {
                            shuffle_offsets.push(shuffle_offset)
                        }
                    }
                });
            } else {
                obs.values_iter().for_each(|b| {
                    shuffle_offset += 1;
                    if !b {
                        shuffle_offsets.push(shuffle_offset)
                    }
                });
            }

            shuffle_offsets.push((len) as u32);


            let rng = &mut thread_rng();

           // reshulle sort indexes  for each slice (defined by 2 consecutive values in shuffle_offsets (to ties are randomized).
            sort_shuffled_idx = {
               // some pseudo code
               for i in range(0, len - 1){
                   sort_idx[.shuffle_offsets[i]..shuffle_offsets[i]].shuffle(rng);
               }
           }

           // Safety:

          // we are in bounds
          unsafe {
             sort_idx.iter().for_each(|&i| {
                *inv_values.get_unchecked_mut(i as usize) = count;
                count += 1;
             });
          }
          let inv_ca = UInt32Chunked::new_from_aligned_vec(s.name(), inv);
```

https://docs.rs/rand/0.6.4/rand/seq/trait.SliceRandom.html#tymethod.shuffle

**Comment by ritchie46** [comment]
> @ritchie46 Shouldn't is_consecutive_same be is_not_consecutive_same?

I think you're right.

On the implementation of the random part, could you give it a try? The rank algorithm, is the only one in Polars I don't understand. I copied the code from scipy, but still have to take the time to understand what we are doing.
