### ISSUE TITLE
Sink to file with streaming

### ISSUE THREAD

**Issue by ek-ex** [pola-rs/polars#15403]
### Description

I constantly have use cases where I have to process a lot of data from multiple files, and then save all that into a single file. I would like to have a mechanism where I could save the data to the new file in a streaming way, as that data becomes available from the other processed files. The alternative now is to `vstack` them, but its slow and the memory is not sufficient.

**Comment by ritchie46** [comment]
We do have `sink_<file_format>`. If we support the query streaming, it does what you request. We will expand on streaming functionality, so this will work for more file formats and operations in the future.

**Comment by ek-ex** [comment]
@ritchie46 are you saying I can achieve this in a streaming fashion without holding the total data in memory already?

```
result = None
for file in files:
      df = feature.process(file, write_csv=False) # returns a DataFrame
      r = df.select('v', 'o')
      if result is None:
          result = r
      else:
          result = res.vstack(r)

result.write_csv('all_data.csv')
```

**Comment by ritchie46** [comment]
If you have a full lazy query. E.g.

```python
scanned = []
for f in paths:
   scanned.append(pl.scan_csv(..))
   
lf = pl.concat(scanned)
lf.sink_csv(..)
```
