### ISSUE TITLE
Pre-compiled version for alpine linux / musl

### ISSUE THREAD

**Issue by woodhull** [pola-rs/polars#15409]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I'm using the "polars-df" ruby gem from @ankane for in-app data analysis that is part of our product -- a rails web application. 

The application is packaged for production using Alpine linux using Docker. While I can successfully install the `polars-df` gem and its dependencies on alpine by compiling the gem bindings and polar library from scratch, this is quite slow.

When I try to install the gem (which packages polars) using the prebuilt binary everything works normally on darwin, but I get the following error while doing so on alpine:
`__rawmemchr: symbol not found alpine`

I've tried the gcompat library which often helps with glibc compatibility vs. musl but this does not seem to resolve the issue in this case. I think that this would be solved simply by offering a precompiled version specific to alpine. 

### Issue description

I'm not familiar with rust or packaging to know how hard it would be to add a musl / alpine option to the build matrix. In other posts the maintainers have indicated that folks "shouldn't use alpine" but that is not a practical option in our situation, and all that seems to be needed is a separate build target. 

### Expected behavior

It should be possible to install a pre-compiled version of polars and polars-df gem.

### Installed versions

n/a

**Comment by ankane** [comment]
Hi @woodhull, just started testing a [musl build](https://github.com/ankane/polars-ruby/actions/runs/8503015857). Please use the Ruby project for feature requests related to Ruby.

**Comment by woodhull** [comment]
Sorry I thought this was a problem with the alpine pieces not existing in the rust package! Not clear on how it all fits together, clearly.

**Comment by ankane** [comment]
Looks like it builds and runs. Will include it in the next release.

Ref: https://github.com/ankane/polars-ruby/commit/9af3570b45fd2b2ca4503110c0726d39d82db7da

**Comment by ritchie46** [comment]
I will close this as this will resolved upstream in polars-ruby.
