### ISSUE TITLE
PanicException: no `selector` expected at this point

### ISSUE THREAD

**Issue by m00ngoose** [pola-rs/polars#15428]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import polars.selectors as cs

df = pl.DataFrame({'a': [1,2,3]})
df.filter(pl.all_horizontal((cs.by_name('^.*$') & cs.by_dtype(pl.INTEGER_DTYPES)) <= 2))
```

thread 'python' panicked at crates[/polars-plan/src/logical_plan/conversion.rs:263:30](http://localhost:8888/polars-plan/src/logical_plan/conversion.rs#line=262):
no `selector` expected at this point

### Issue description

Select works, and produces a bool column, but filter does not.

### Expected behavior

Should return pl.DataFrame({'a': [1,2]}).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Python:               3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  0.10.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.16.1
fastexcel:            0.9.1
fsspec:               2023.12.2
gevent:               24.2.1
hvplot:               0.9.2
matplotlib:           3.8.3
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             2.6.4
pyiceberg:            0.6.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.28
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0```

</details>

**Comment by hxzhao527** [comment]
# how to make it?
```python
import polars as pl
import polars.selectors as cs

df = pl.DataFrame({'a': [1,2,3]})

df.filter(
    pl.all_horizontal(
        ( cs.by_name('^.*$') <= 2 ) | ( cs.by_dtype(pl.INTEGER_DTYPES) <= 2 )
    )
)
```
# why panic
`cs.by_name('^.*$') & cs.by_dtype(pl.INTEGER_DTYPES)` will  transform `Expr::Column` to `Expr::Selector`, which can't be combined with `<= 2`.
https://github.com/pola-rs/polars/blob/c8640cb928eb14d164bc0a158398b995641d4351/py-polars/polars/selectors.py#L305-L313

# how to make the exception clearer?
maybe we could overload operator `<=` and others for `_selector_proxy_`.

**Comment by cmdlineluser** [comment]
@hxzhao527 I think the issue may be specific to `.filter`

The selector does work in a select/with_columns

```python
df.with_columns(
   keep = pl.all_horizontal((cs.by_name('^.*$') & cs.integer()) <= 2)
)

# shape: (3, 2)
# ┌─────┬───────┐
# │ a   ┆ keep  │
# │ --- ┆ ---   │
# │ i64 ┆ bool  │
# ╞═════╪═══════╡
# │ 1   ┆ true  │
# │ 2   ┆ true  │
# │ 3   ┆ false │
# └─────┴───────┘
```

**Comment by cbilot** [comment]
#15103
