### ISSUE TITLE
Multiprocessor read of CSV file got broken on version 0.10.4

### ISSUE THREAD

**Issue by jbmorgado** [pola-rs/polars#1545]
After version 0.10.4 came out, CSV files take substantially longer to read. Analysing the CPU usage show that only one core is being used while in version 0.10.3 all were being used.

This bug can be tested with a simple:
```
import polars as pl
import time

print("Reading with Polars...")
start_time = time.time()
df = pl.read_csv("mybigcsvfile.csv")
print("Polars read: %s s"% (time.time() - start_time))
```

**Comment by ritchie46** [comment]
Hi @jbmorgado, it seems to work fine here, have you got a csv-file where this problem occurs?

**Comment by jbmorgado** [comment]
Well, the CSV file is 2.1Gb (with hundreds of columns more than ten of thousand rows), I can't really share it.

But the issue is still going on on 0.10.6 (65 seconds to read the CSV). Reverting to polars 0.10.3 brings the time down to 8 seconds.

**Comment by ritchie46** [comment]
I will close this as its inactive and we could not reproduce this.
