### ISSUE TITLE
`pl.concat_list` is slow(?)

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#15466]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import time

NUM_ROWS = 200000000

data = []

ldf = pl.LazyFrame(
    {
        "a": list(range(NUM_ROWS)),
    }
)


ldf = ldf.with_columns(pl.concat_list("a"))
start = time.time()
print("starting concat")
print(ldf.collect())
print(f"{time.time() - start}s") # prints 31.588394165039062s
```

### Issue description

In my real use case, the same number of rows takes maybe 70s. I'm not sure if this issue is correct (in the sense that maybe this is as fast as it can go?).

This doesn't seem to use any parallelization either, perhaps that's the issue? Are expressions internally always serial?

### Expected behavior

Runs faster (if possible).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Linux-5.10.210-178.855.x86_64-x86_64-with-glibc2.26
Python:               3.11.7 (main, Dec  5 2023, 22:00:36) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by ritchie46** [comment]
I think it is how expensive the work is. Especially given that duckdb on all cores only is 2x faster. We can make this expression eligible to the streaming engine. That would parallelize it vertically.

**Comment by cmdlineluser** [comment]
I just remembered [`.reshape()`](https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.reshape.html#polars.Expr.reshape)

Obviously not a replacement for `concat_list` but it does produce the same result for this particular example in 1s which is interesting.

```python
ldf = ldf.with_columns(pl.col("a").reshape((-1, 1)))
```
