### ISSUE TITLE
Should `then` and `otherwise` treat strings as literals by default?

### ISSUE THREAD

**Issue by paw-lu** [pola-rs/polars#15461]
### Description

Right now when you pass strings into `then` or `otherwise`

```python
pl.DataFrame({"a": ["a", "a", "b"]}).with_columns(
    b=pl.when(pl.col("a") == "a").then("q").otherwise("r")
)
```

Polars interprets them as column names, so you get:

```pytb
ColumnNotFoundError: q

Error originated just after this operation:
DF ["a"]; PROJECT */1 COLUMNS; SELECTION: "None"
```

The current fix is to wrap the strings in `pl.lit`:

```python
pl.DataFrame({"a": ["a", "a", "b"]}).with_columns(
    b=pl.when(pl.col("a") == "a").then(pl.lit("q")).otherwise(pl.lit("r"))
)
```

This was a bit unintuitive, and a more sensible default might be to interpret strings as a literal, then if the user wants to pass a column they can explicitly use `pl.col`.

**Comment by avimallu** [comment]
This used to be the case earlier, and the change was very deliberate. I don't remember the exact PR that made the change, but you can see [this](https://github.com/pola-rs/polars/issues/13805#issuecomment-1952801860) for context.

**Comment by paw-lu** [comment]
Thanks for the context. While I'm not sure I agree here, this seems like a `won't fix` kind of issue and I totally respect that. Going to close!

Again—thanks @avimallu for the context!

**Comment by LeoArtaza** [comment]
> Thanks for the context. While I'm not sure I agree here, this seems like a `won't fix` kind of issue and I totally respect that. Going to close!
> 
> Again—thanks @avimallu for the context!
 What a cuck response. This is an abhorrent behavior from Polars. Contributors are always saying "oh this issue pops up all the time, but you're all wrong because the 3 guys in charge disagree". If this was voted, fixing this would be by a landslide. I've los all respect to the Polars team, they are a bunch of morons if they don't change this to the CORRECT behavior.
