### ISSUE TITLE
[DRAFT] semi-join on id isn't being pushed down with JIT optimizations

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#15473]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Something like this, will try to make a proper MRE:

```python
# I don't know if it's relevant that this dataset is hive partitioned on the 'id' column or not
right_ldf = right_ldf.filter(pl.col('some_col').max() == pl.col('some_col').max())    
ldf = left_ldf.join(right_ldf, on='id', how="semi")
ldf.collect()
```

### Issue description

Basically i'm grabbing a row from the right DF that corresponds with some maximum value in a column and then doing a semi join on the associated id but it seems like the left DF is being fully downloaded (as opposed to just grabbing what i need, which is a single id).

### Expected behavior

We only download a little bit of data from the left table (due to the id(s) that are found getting pushed down during the join)

### Installed versions

<details>

```
0.20.18
```

</details>

**Comment by ritchie46** [comment]
This has been fixed.
