### ISSUE TITLE
SchemaError: nonexistent column when created from sequence

### ISSUE THREAD

**Issue by RichardHaythorn** [pola-rs/polars#15471]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame([{"a": 1}], schema_overrides={"b": pl.Boolean()})
```
raises the SchemaError

### Issue description

Differing behaviour between creation from rows and creation from dictionary when using schema_overrides,

Fine:
```python
import polars as pl
pl.DataFrame({"a": [1]}, schema_overrides={"b": pl.Boolean()})
```

Raises an Error:
```python
import polars as pl
pl.DataFrame([{"a": 1}], schema_overrides={"b": pl.Boolean()})
```

The workaround is somewhat clunky:
```python
import polars as pl
schema = {"a": pl.Int32, "b": pl.Boolean}
df = pl.DataFrame([{"a": 1, "b": 1}, {"a": 2}])
df = df.cast({i: j for i, j in schema.items() if i in df.columns})
```

Looks like this was introduced in https://github.com/pola-rs/polars/pull/15290 as intended behaviour.

### Expected behavior

In 0.20.16, this was acceptable:
```python
df = pl.DataFrame([{"a": 1}], schema_overrides={"b": pl.Boolean()})` 
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Linux-6.1.0-18-amd64-x86_64-with-glibc2.36
Python:               3.11.8 (main, Mar 20 2024, 13:36:58) [GCC 12.2.0]
```

</details>

**Comment by stinodego** [comment]
The constructors are unfortunately a bit of a mess at the moment. See #14427 

So issue here is actually that the dict-example does NOT raise. This should result in a `SchemaError`:

```
import polars as pl
pl.DataFrame({"a": [1]}, schema_overrides={"b": pl.Int32()})
```

The best way to achieve what you're trying to achieve is:

```python
pl.DataFrame([{"a": 1}]).with_columns(pl.col("a").cast(pl.Boolean))
```

**Comment by RichardHaythorn** [comment]
Thanks for clarifying with #14427 the way things are moving

However, I think the example you posted doesn't quite address the problem I'm looking at. 

The general problem I'm facing is ensuring types on columns without knowing exactly what columns are present prior to construction.

**Comment by Guillermogsjc** [comment]
folks, this update on `schema_overrides` behaves as a huge  **regression** (I will call it a regression at is lost a feature that is **"type some columns at DataFrame constructor or leave them to the inference machine**)  i am sure it is breaking plenty of cases of people working from NOSQL (list of dicts) into DataFrames. 

@stinodego  is it possible to recover the classic behaviour, is this experimental or you have the direction of this change fully confirmed?

**Comment by stinodego** [comment]
Right, I can see the use case here. I was thrown off a bit by the example in the original issue. You have a generic schema and don't know which of the columns in the schema are actually in your data. So you would want something like this:

```python
import polars as pl

df = pl.DataFrame([{"a": 1}], schema_overrides={"a": pl.Int8(), "b": pl.Boolean()})
print(df)
```
```
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i8  │
╞═════╡
│ 1   │
└─────┘
```

In this case, using `schema` instead of `schema_overrides` would work, but that would give you an empty `"b"` column, which you may not want:

```python
df = pl.DataFrame([{"a": 1}], schema={"a": pl.Int8(), "b": pl.Boolean()})
print(df)
```
```
shape: (1, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i8  ┆ bool │
╞═════╪══════╡
│ 1   ┆ null │
└─────┴──────┘
```

I think this use case makes sense to allow. I didn't account for this when writing up the design here: https://github.com/pola-rs/polars/issues/11723#issuecomment-1768346275

I will revert this change.

**Comment by Guillermogsjc** [comment]
hi @stinodego 

thanks you for the quick response

> could you confirm that this is indeed what you are trying to do, and that the schema parameter is not sufficient for your use case? I'm trying to think of a situation where adding the null columns is undesirable, but honestly I cannot really think of one.

Is not only what I were trying to do, it was what I were **doing in plenty of ETL from MongoDB (list of dicts)** in our data engineering processes on `polars<0.20.17`.

`schema_overrides` behaviour on `polars<0.20.17` feels and acts as a **weak schema** (aka *type this field like this if it exists on any of the dicts of the list) == **a sequence of dictionaries is being passed, in which case a partial schema can be declared**. 

By raising the error when a field in `schema_overrides` is not present in any of the dicts of the list of dicts provided , we are losing this past weak schema behaviour, do not know exactly in favour of which advantage (the byproduct of the raise of this error is poor imho).

I know that the field could be moved into `schema` and then drop full null columns, but the lose of ergonomics from the constructor are relevant. When typing `schema_overrides`  on `polars<0.20.17`, you could obtain **disctinct final schema configurations of the DataFrame/LazyFrame from the same constructor** (weak schema definition), without any further operations after the constructor!! It was really great!
