### ISSUE TITLE
Read Options for Calamine

### ISSUE THREAD

**Issue by drskoolie** [pola-rs/polars#15486]
### Description

I cannot find the read options for calamine. I've looked through their documentation, but I couldn't find it there either.

### Link

https://docs.pola.rs/py-polars/html/reference/api/polars.read_excel.html

**Comment by cmdlineluser** [comment]
*"using the fastexcel module to bind calamine"*

It seems to be referring to:

- https://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_sheet_by_name
