### ISSUE TITLE
See the polars df in Pycharm

### ISSUE THREAD

**Issue by ravi160822** [pola-rs/polars#15490]
### Description

I get the following error when I attempt to see a polars df in Pycharm
<img width="1292" alt="Screenshot 2024-04-05 at 1 58 07 PM" src="https://github.com/pola-rs/polars/assets/114392296/bd67d8ce-24aa-49f5-a3b8-c3c9e1b50d13">

**Comment by ravi160822** [comment]
every dataframe I get the error, I use the trick mentioned here currently, https://stackoverflow.com/questions/72644013/how-to-show-polars-dataframe-in-pycharm

**Comment by ravi160822** [comment]
it does not work, I am on the latest community version of PyCharm as attached,
<img width="1294" alt="Screenshot 2024-04-06 at 7 31 11 PM" src="https://github.com/pola-rs/polars/assets/114392296/5f59bbc7-dd69-4f69-b1ea-fd13870073d8">

**Comment by stinodego** [comment]
I'm not a PyCharm guy so I don't really know what you're trying to do. Is that the debugger? In any case, please report this to the PyCharm people, this is not something we can fix.
