### ISSUE TITLE
.over() performs quite slow in given sample

### ISSUE THREAD

**Issue by Chuck321123** [pola-rs/polars#15492]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import numpy as np
import polars as pl


# Define the number of rows and groups
num_rows = 20000000
num_groups = 200

# Generate random data
data = {
    'group': np.random.randint(0, num_groups, size=num_rows),
    'random_value': np.random.rand(num_rows)
}

# Create DataFrame
df = pd.DataFrame(data)

df2 = pl.DataFrame(df)

# If-else function
%timeit np.where(df["random_value"] == 1, 2, df["random_value"])

%timeit df2.with_columns((pl.when(pl.col("random_value")==1).then(2).otherwise(pl.col("random_value"))))

%timeit df2.with_columns((pl.when(pl.col("random_value")==1).then(2).otherwise(pl.col("random_value"))).over("group"))



```

### Log output

```shell
71.2 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
41.9 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.69 s ± 496 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### Issue description

So I wanted to compare if-else speeds between polars and numpy, but threw in .over() to also see if it had any impact, and to my surprise it had a huge impact. So normally linear if-else functions doesnt need a groupby function, but when we add .over() here, the code suddely becomes 20x slower. How does .over() behave here? Does it iterate and perform the same operation 200 times? I find it strange that it doesnt try to do 1 operation across all the groups simultaneously.

### Expected behavior

That it performs equally as well as without .over() in this case.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:28:07) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Chuck321123** [comment]
Hmm, forgot to turn off battery saver. Turned everything to max  and activated all cores manually and got this 
44.2 ms ± 2.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
24.8 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
477 ms ± 15.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Idk. Maybe i just dont understand the underlying process of .over(). Feels like it still has potential to do it better

**Comment by cmdlineluser** [comment]
`.over()` performs a group_by e.g.

```python
(df2.group_by("group")
    .agg(
       pl.when(pl.col("random_value")==1)
         .then(2)
         .otherwise(pl.col("random_value"))
         .alias("result")
    )
)
```

But the lists would be exploded and the results joined back in the correct row order.
