### ISSUE TITLE
Wrong document in arguments `group_by` of `DataFrame.upsample`

### ISSUE THREAD

**Issue by j7168908jx** [pola-rs/polars#15505]
### Description

The argument `group_by` has been renamed to `by` in the code(at least in the `help(df.upsample)` in 0.20.15 stable version), but not yet in the document.

This is found for both the stable 0.20 and the dev branch of the doc.

https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.upsample.html

https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.upsample.html

### Link

https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.upsample.html

**Comment by MarcoGorelli** [comment]
hi @j7168908jx could you clarify what you mean please?

I see `group_by` in https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.upsample.html ?

**Comment by j7168908jx** [comment]
Sorry for the confusion. I mean that the actual api is `by`, but the doc is `group_by`.

You may simply copy and run the example in the doc. It will raise the error.

**Comment by MarcoGorelli** [comment]
It works for me (and is checked in CI), I think you're on an old version of Polars?

**Comment by j7168908jx** [comment]
Yes you are right, sorry to bother for this one. I will close the issue.

**Comment by MarcoGorelli** [comment]
no worries :) docs improvements are important and always welcome so please do ping if you find anything missing/wrong
