### ISSUE TITLE
Ta-lib support for Polars dataframe

### ISSUE THREAD

**Issue by teneon** [pola-rs/polars#1552]
Hi there,

i've asked the author of Ta-lib wrapper library (5.8k stars on github), if he could implement support for Polars as he had implemented it for Pandas and he is interested to support your Polars dataframe as well, but he has some questions.
Here is the opened issue: [https://github.com/mrjbq7/ta-lib/issues/471](https://github.com/mrjbq7/ta-lib/issues/471)

His answer if he would implement support for Polars:
> It's a cool idea. Is there a way to get direct access to the column data in memory, so I can pass a pointer directly to the TA-Lib C functions? Or would I need to copy the data out, into a numpy array, or something...?

What do you think Ritchie, can you point him to the right direction?
btw: Polars is amazing, it's so much faster than Pandas in every aspect. We are switching everything over from Pandas, good job :D

Best regards,
Neon

**Comment by ritchie46** [comment]
> What do you think Ritchie, can you point him to the right direction?

I will do my best. :)

>  btw: Polars is amazing, it's so much faster than Pandas in every aspect. We are switching everything over from Pandas, good job :D

That's what I like to hear! :smile:

**Comment by Yvictor** [comment]
@teneon 
You can directly use Ta-lib as polars extension now.

``` bash
pip install polars_talib
```
``` python
import polars
import polars_talib as plta

df.with_columns(
    pl.col("close").ta.ema(5).alias("ema5"),
    pl.col("close").ta.macd(12, 26, 9).struct.field("macd"),
    pl.col("close").ta.macd(12, 26, 9).struct.field("macdsignal"),
    pl.col("open").ta.cdl2crows(pl.col("high"), pl.col("low"), pl.col("close")).alias("cdl2crows"),
    pl.col("close").ta.wclprice("high", "low").alias("wclprice"),
)
```

more info at https://github.com/Yvictor/polars_ta_extension
