### ISSUE TITLE
Support `group_by` on columns of type `List(String)`

### ISSUE THREAD

**Issue by Evan-Kim2028** [pola-rs/polars#15539]
### Description

Currently `group_by` with a list only works with numerics so something like this isn't valid:

df = (
    pl.DataFrame({
      "lists": [
          ["a", "b", "c"],
          ["a", "c", "b"],
          ["a", "c", "b"],
          ["a", "c", "d"],
      ]
  })
).group_by('lists').agg(pl.len().alias('count'))

```python
ComputeError: grouping on list type is only allowed if the inner type is numeric
```

**Comment by cmdlineluser** [comment]
If it is of use, a current workaround is to cast to Categorical:

```python
.group_by(pl.col('lists').cast(pl.List(pl.Categorical)))
```

**Comment by Evan-Kim2028** [comment]
that is of use actually! Is this categorical type similar to Panda's "catch all" categorical type as well?

**Comment by stinodego** [comment]
We definitely should be able to support this.

> that is of use actually! Is this categorical type similar to Panda's "catch all" categorical type as well?

You could say so. We have `Enum` if your categories are known beforehand, and `Categorical` if they are not.
