### ISSUE TITLE
polars' maximum length reached. Consider installing 'polars-u64-idx' with a dataframe of 12K rows

### ISSUE THREAD

**Issue by daviddoji** [pola-rs/polars#15534]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import itertools
import numpy as np
import polars as pl

first = 3000
second = 4000
third = 5000
data = {
    "a": np.concatenate(
        (np.repeat(1, first), np.repeat(2, second), np.repeat(3, third))
    ),
    "b": np.concatenate(
        (
            sorted(np.random.randint(1, first, size=first)),
            sorted(np.random.randint(1, second, size=second)),
            sorted(np.random.randint(1, third, size=third)),
        )
    ),
}

d = [
    np.tile(np.random.randint(1, first * 20, size=first*100), (first, 1)).tolist(),
    np.tile(np.random.randint(1, second * 20, size=second*100), (second, 1)).tolist(),
    np.tile(np.random.randint(1, third * 20, size=third*100), (third, 1)).tolist(),
]
data["d"] = list(itertools.chain.from_iterable(d))

df = pl.DataFrame(data)
df = df.with_columns([pl.col("a").cum_count().over("a", "b").alias("c")])
df.shape, df.head()

(
    df
    .with_columns(
        pl.col("d").list.get(pl.col("b")-1).alias("res")
    )
)
```

### Issue description

With a  polars dataframe of this shape "(12000, 4)" one gets the following error:
```
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/ops/chunkops.rs:95:9:
polars' maximum length reached. Consider installing 'polars-u64-idx'.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[6], line 2
      1 (
----> 2     df
      3     .with_columns(
      4         pl.col("d").list.get(pl.col("b")-1).alias("res")
      5     )
      6 )

File ~/python_venvs/toolbox_sxp/lib/python3.9/site-packages/polars/dataframe/frame.py:8366, in DataFrame.with_columns(self, *exprs, **named_exprs)
   8220 def with_columns(
   8221     self,
   8222     *exprs: IntoExpr | Iterable[IntoExpr],
   8223     **named_exprs: IntoExpr,
   8224 ) -> DataFrame:
   8225     """
   8226     Add columns to this DataFrame.
   8227 
   (...)
   8364     └─────┴──────┴─────────────┘
   8365     """
-> 8366     return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)

File ~/python_venvs/toolbox_sxp/lib/python3.9/site-packages/polars/lazyframe/frame.py:1943, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1940 if background:
   1941     return InProcessQuery(ldf.collect_concurrently())
-> 1943 return wrap_df(ldf.collect())

PanicException: polars' maximum length reached. Consider installing 'polars-u64-idx'.
```

but the dataframe has not yet reached the limit of 2^32 (~4.2 billion) rows, as stated in PyPi for using `polars-u64-idx` version. 
```

### Expected behavior

No error thrown by polars

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-3.10.0-1160.102.1.el7.x86_64-x86_64-with-glibc2.17
Python:               3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.5.2
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

Edit: Added MRE. Needed a huge amount of RAM (376G) and a bit of time to generate the toy dataset

**Comment by stinodego** [comment]
What is the length of those lists in the list column? I think it has something to do with that.

**Comment by daviddoji** [comment]
> What is the length of those lists in the list column? I think it has something to do with that.

1000. It's printed by `len of first row of BAM[fs]`
