### ISSUE TITLE
Setup CodSpeed for PR benchmarks

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#15531]
### Description

[CodSpeed](https://codspeed.io/) allows you to benchmark on a PR basis. They have machines with very stable performance and are free for OS projects.

[pydantic](https://github.com/pydantic/pydantic/blob/main/.github/workflows/codspeed.yml) had very good experiences with this. 

We should first get this in CI and then we can incrementally add benchmarks we are interested in. Starting with the ones we already have `db-benchmark`. `TPCH` can be added and we can add core primitives, like `filter`, `hash`, `eq`, `gather`, `join` etc.

**Comment by stinodego** [comment]
See https://codspeed.io/pola-rs/polars/benchmarks :)
