### ISSUE TITLE
Ability to disable jemalloc

### ISSUE THREAD

**Issue by yurivict** [pola-rs/polars#15542]
### Description

On FreeBSD system malloc is jemalloc.
There are some conflicts between jemalloc supplied by polars and system one, and this testcase fails:
```
import polars as pl

q = (
    pl.scan_csv("docs/data/iris.csv")
    .filter(pl.col("sepal_length") > 5)
    .group_by("species")
    .agg(pl.all().sum())
)

df = q.collect()
```

```
<jemalloc>: Error in dlsym(RTLD_NEXT, "pthread_create")
Abort trap
```

Version: 0.20.18
FreeBSD 14.0

**Comment by ritchie46** [comment]
What is the reason they cannot both work?

**Comment by yurivict** [comment]
I am not sure, but perhaps there's some symbol name conflict.
Polars currently crashes on FreeBSD with jemalloc-related error.

**Comment by yurivict** [comment]
@ritchie46 

When the feature ```use_mimalloc``` is enabled, the build still looks for Jemalloc and fails.
Do you know why is that?
Enabling use_mimalloc might be a solution for our problem on FreeBSD.

**Comment by yurivict** [comment]
It looks like the memory allocator option was added and Polars now builds successfully in FreeBSD.
