### ISSUE TITLE
Regression in common subplan elimination when cached node is used

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#15548]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

ldf = pl.LazyFrame({"a": [1, 2, 3]})
ldf2 = ldf.filter(pl.col("a") == 1).cache()
ldf3 = pl.concat([ldf, ldf2])

# Disabling comm_subplan_elim is okay
assert len(ldf3.collect(comm_subplan_elim=False)) == 4

# With comm_subplan_elim, ldf2 filter appears to be eliminated and the result is incorrectly 6 rows
assert len(ldf3.collect(comm_subplan_elim=True)) == 4
```

### Issue description

The regression appears to be introduced in 0.20.17 and still present in 0.20.19. Versions 0.20.16 and earlier are okay.

It's interesting it's dependent on the node being cached. This is a minimum reproducible example.

### Expected behavior

In the example, the combined Data Frame should be 4 rows.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Linux-6.2.0-1019-azure-x86_64-with-glibc2.31
Python:               3.11.7 (main, Jan  8 2024, 20:44:44) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Right.. `cache` nodes should be deprecated. This should be left to the optimizer now. I shall deprecate it and make it a no-op.

**Comment by josh** [comment]
> Right.. `cache` nodes should be deprecated.

So.. I'm still seeing many cases where UDFs are invoked additional times unless `.cache` nodes are used. It would be nice if I could trust CSE to automatically handle those case but optimizer doesn't seem that good yet. Should I open issues for these cases?
