### ISSUE TITLE
Python Polars Import Fail on Aarch64 Linux

### ISSUE THREAD

**Issue by valemanji** [pola-rs/polars#15549]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars
```

### Log output

```shell
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 8 bytes failed
Aborted
```

### Issue description

Hi yall, I tried importing polars but it fails with a jemalloc unsupported page size issue. I also attempted using polars-lts-cpu in my requirements.txt but that failed too.

### Expected behavior

import polars throws no errors

### Installed versions

<details>

```
0.20.18
```

</details>

**Comment by valemanji** [comment]
I noticed that a past user has had jemalloc issues that were closed namely: https://github.com/pola-rs/polars/issues/5654. But using a new version has not helped me. Based on other github pages, it appears there are a lot of discussions about jemalloc on aarch64. In case you all are not already familiar, here are some links: https://github.com/facebook/buck2/issues/91 and https://github.com/swc-project/swc/issues/5967)

**Comment by messense** [comment]
Looks like `JEMALLOC_SYS_WITH_LG_PAGE=16` isn't working: https://github.com/pola-rs/polars/blob/42d36970f71044264832c404e303fcada9323807/.github/workflows/release-python.yml#L166-L180, need to pass it to `maturin-action` because of Docker, for working example, see

* https://github.com/astral-sh/ruff/blob/42d52ebbec275389ee0458a3bf373268278bd51a/.github/workflows/release.yaml#L243-L247
* https://github.com/astral-sh/ruff/blob/42d52ebbec275389ee0458a3bf373268278bd51a/.github/workflows/release.yaml#L275

**Comment by valemanji** [comment]
@messense is this change that can only at build time or is there an os environ variable that can be used to update it in the mean time.

**Comment by uuip** [comment]
> Looks like `JEMALLOC_SYS_WITH_LG_PAGE=16` isn't working:

so I compile polars by myself.

**Comment by uuip** [comment]
@stinodego Excuse me, do
 you have time verify this problem?

**Comment by stinodego** [comment]
Thanks for the fix @messense !

I'll close this issue for now as I assume it has been resolved. If you're still running into issues with Polars `0.20.22-rc.1` or later, please let me know, and I can re-open this issue.

**Comment by valemanji** [comment]
@stinodego it works for me too. Thanks for the fix @messense

**Comment by shenquanle** [comment]
I encountered this problem too，my polars version is 0.18.4, and I solved this problem by upgrading the version of Polars to 0.20.31. hope my answer would help u.
