### ISSUE TITLE
How to fill missing dates in time series

### ISSUE THREAD

**Issue by teneon** [pola-rs/polars#1555]
Hi there,

It is usually the case on large datasets that time series data (such as stock data - OHLCV) have missing values (missing rows / missing dates). If you have dataset with gaps, you have to "fix" it first, otherwise you can't apply technical indicators to it (e.g. Talib).

In Pandas, it is very simple to fill missing dates (step 1) and then interpolate or copy last known values (step 2). You can take a look [here](https://stackoverflow.com/questions/47231496/pandas-fill-missing-dates-in-time-series), there are multiple solutions for the same problem. 

How to fill missing dates with Polars? Here is a simple example Dataframe:
```
df = pl.DataFrame(
    {"mydate": ["2020-01-01", "2020-01-02", "2020-01-05"],
     "index": [1, 2, 5]})
df = df.with_column(pl.col("mydate").str.strptime(pl.Date, "%Y-%m-%d"))
```
This is how the example dataframe looks like if we print it (dates 2020-01-03 and 2020-01-04 are missing):
```
mydate (date) | index (i64)
2020-01-01 | 1
2020-01-02 | 2
2020-01-05 | 5
```

How to fill the missing dates, so it would look somewhat like this?
```
mydate (date) | index (i64)
2020-01-01 | 1
2020-01-02 | 2
2020-01-03 | NaN
2020-01-04 | NaN
2020-01-05 | 5
```

And finally how to interpolate "index" column where values are NaN, so the end result would be something like this:
```
mydate (date) | index (i64)
2020-01-01 | 1
2020-01-02 | 2
2020-01-03 | 3
2020-01-04 | 4
2020-01-05 | 5
```

...or if we wanted to use copy "last known value" Instead of interpolation, so the "index" column would look like this:
```
mydate (date) | index (i64)
2020-01-01 | 1
2020-01-02 | 2
2020-01-03 | 2
2020-01-04 | 2
2020-01-05 | 5
```

Can you please help :D
best regards,
Neon

**Comment by CloseChoice** [comment]
@teneon : Would you mind asking your question again on stackoverflow? Even though you already have your answer it would be great to have all sorts of user questions regarding polars there, since it's the first place many developers look for answers. Thanks already

**Comment by ritchie46** [comment]
> @ritchie46 , an equivalent of [resample](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html) would come in handy for that. At a minimum, such a function/expression would take a column name and a timedelta ?
> 
> I think 'resampling' is quite key as soon as dealing with timeseries.

Polars already has a downsample. The operations are fundamentally different.  One is a groupby, the other is a join on a larger date range. 

Pandas has abstracted both in the resample. For now I first want to document how to do it without hiding abstractions (would be quite some work, we don't have a date range in Rust yet).

**Comment by olivier-lacroix** [comment]
@teneon , an upsample method has been added to DataFrame, which does what you were looking for here (on datetime columns only and not on date columns for the moment).

@ritchie46 , I think this issue can be closed?
