### ISSUE TITLE
Implement window context in `df.sort(col("a").over("b"))`

### ISSUE THREAD

**Issue by Alex23rodriguez** [pola-rs/polars#15556]
### Description

Many times I find myself sorting a whole dataframe using window functions. Is there any reason we can't use `df.sort(col('a').over('b'))` and instead have to resort to `df.select(pl.all().sort_by('a').over('b'))`?

The first option seems way more straightforward to me, but it just sorts the whole dataframe according to a, without any windowing context.

This would also enable to do some things that are currently not possible when dealing with nulls, since `sort_by` places nulls first and it is not possible to specify otherwise. (Though this is being implemented. see #5420)

**Comment by orlp** [comment]
> Is there any reason we can't use `df.sort(col('a').over('b'))` and instead have to resort to `df.select(pl.all().sort_by('a').over('b'))`?

These two are not the same. Method chaining is intended intended to be the same as reverse order application:

    a.foo().bar().wee()
    wee(bar(foo(a)))

So in your example we have essentially:

    df.select(pl.all().sort_by('a').over('b')) -> over('b', sort_by('a', all()))

But in your other example we have the following:

    df.sort(col('a').over('b')) -> sort(over('b', col('a')))

This doesn't really make any sense. `over` is a context that changes what happens *inside* the window, not outside.
