### ISSUE TITLE
CSE doesn't detect self join

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#15562]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

def log_calls(df):
    print("CALL")
    return df

common_ldf = pl.LazyFrame(
    {
        "id": pl.Series([1, 2, 3]),
        "value": [1, 2, 3],
    }
).map_batches(log_calls) # Adding .cache() would fix

ldf = common_ldf.select(
    pl.col("id"),
    pl.col("value") + 1
).join(common_ldf, on="id", how="left")

print(ldf.collect())
```

### Log output

```shell
CALL
CALL
shape: (3, 3)
┌─────┬───────┬─────────────┐
│ id  ┆ value ┆ value_right │
│ --- ┆ ---   ┆ ---         │
│ i64 ┆ i64   ┆ i64         │
╞═════╪═══════╪═════════════╡
│ 1   ┆ 2     ┆ 1           │
│ 2   ┆ 3     ┆ 2           │
│ 3   ┆ 4     ┆ 3           │
└─────┴───────┴─────────────┘
```

### Issue description

On https://github.com/pola-rs/polars/issues/15548#issuecomment-2044252434, @ritchie46 has indicated that `cache` nodes are deprecated and in favor of CSE optimizer. However, here's a case with self joins where a previous cache node would avoid evaluating a UDF twice but CSE doesn't seem to catch that the self join shares this branch.

### Expected behavior

`log_calls` is invoked once.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Linux-6.2.0-1019-azure-x86_64-with-glibc2.31
Python:               3.11.7 (main, Jan  8 2024, 20:44:44) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Yes, python function will not be introspected. You can still use a cache for that. I concluded a bit too early to remove it.

**Comment by ritchie46** [comment]
This isn't a bug btw. We will not introspect python function, they can be stateful. It would be bad design, but not something we can detect.

**Comment by josh** [comment]
> You can still use a cache for that. I concluded a bit too early to remove it.

:+1:

> We will not introspect python function, they can be stateful. It would be bad design, but not something we can detect.

What you do think about a future `map_batches(pure=True)` that could be optimized?

> This isn't a bug btw.

I'll "wontfix" this particular issue at least.
