### ISSUE TITLE
docs: Add an overview of available SQL functions

### ISSUE THREAD

**Issue by r-brink** [pola-rs/polars#15575]
### Description

In the past months, @alexander-beedie and others have added many SQL functions to the SQL interface of Polars. Although the SQL interface isn't our primary focus, it will be valuable to make it (more) visible. However, it is difficult for users to find an overview and examples of what exactly is implemented. 

The only overview can be found in the `functions.rs` file in the polars-sql crate: https://github.com/pola-rs/polars/blob/86d3aa04ec8dfc523f0e7e9a30ccbcc28b78b8eb/crates/polars-sql/src/functions.rs#L25:L562 

I did some research and found three (sub optimal) approaches:

1. Simply add a link to the SQLContext docs: https://docs.pola.rs/py-polars/html/reference/sql.html referring to the overview in polars-sql crate. Not very user friendly.
2. Make the SQLFunctions publicly available. The current examples will become available in the Rust docs, which we can then refer to from other docs (i.e. user guide).
3. Manually add the functions to the SQL section in the python API reference. That way users can more easily find the available functions. Downside with this approach is, in my understanding, that it will involve manually keeping the overview up to date. This has a risk of going out of sync over time.

Does someone else see another solution to create this overview? Or should we go for one of these options?

**Comment by alexander-beedie** [comment]
I've been meaning to have a go at (3) for a while now 😅 It allows for more examples and context (what type of function is it, Parag's, etc) than exposing SQLFunctions would.

**Comment by r-brink** [comment]
What has been holding you back so far? 

Exposing SQLFunctions will indeed be pretty bare-bones, maybe not a real benefit over the first approach. Did you think of any other solutions? Otherwise, we should just go for the third option. Accept that risk of the overview getting out of sync.

**Comment by alexander-beedie** [comment]
> What has been holding you back so far? 

Time ;)

**Comment by alexander-beedie** [comment]
> Familiar issue 😄 I want to make time for it, so if that's the main bottleneck then I think I can make it happen.

How about I look to get it off the ground this weekend, and we can collaborate? I'm about to land another small SQL patch, so at least I'm kin the right headspace for it, lol...

**Comment by r-brink** [comment]
Sounds good. Let me know how it goes!

**Comment by r-brink** [comment]
@alexander-beedie I found some time and started with the overview. Curious about your opinion on this approach

**Comment by alexander-beedie** [comment]
> @alexander-beedie I found some time and started with the overview. Curious about your opinion on this approach

Nice; I'll take a look! ✌️

**Comment by stinodego** [comment]
Was this closed by https://github.com/pola-rs/polars/pull/16268?

**Comment by alexander-beedie** [comment]
> Was this closed by #16268?

Pretty much; the new overview isn't _complete_, but since we have actually added it I think this can be closed out. We can look to fill in the gaps with a new tracking issue 👍
