### ISSUE TITLE
Handle Python UUID objects as strings

### ISSUE THREAD

**Issue by jacopofar** [pola-rs/polars#15582]
### Description

When using `from_database` to read from a Postgres database I noticed UUID columns are returned as Python UUID objects and Polars cannot convert them to strings:

```
  File "/srv/venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 561, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.from_rows(
           ^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: could not append value: 461157eb-e4ea-4c5f-9aec-04c56924fd96 of type: object to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`
```
I specified in the schema that this column is supposed to have type `pl.Utf8`, but for what I can understand from the error the conversion cannot be done automatically. I solved by casting those UUIDs to `TEXT` in the query. The resolution had been made a bit tricky by #12536 since the column name is not present in the error message so I cannot know which column is causing the issue.

I don't think this is a bug by itself, only a nice thing to have in these cases.

**Comment by deanm0000** [comment]
You can convert it with `map_elements`, just ignore the warning about being inefficient.

```
from uuid import uuid4
import polars as pl
import warnings
## proxy for your database query
df=pl.DataFrame({'a':[uuid4() for _ in range(10)]})
## convert to string
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    df=df.with_columns(pl.col('a').map_elements(lambda x: str(x)))
```

**Comment by deanm0000** [comment]
Here's an easier way to deal with Object to string conversion actually and it doesn't trip the warning...

```
df.with_columns(pl.col(pl.Object).map_elements(lambda x: str(x) if hasattr(x, "__str__") else x))
```

@stinodego should something like this be implemented at the reader level or leave it to user? Instead of looking for UUID types specifically, which would be a never ending line of each custom python type being requested, just look to see if it has `__str__`. So something like if they specified string but they got an object then do the above?

**Comment by jacopofar** [comment]
I do the conversion with `map_elements`, but this happens before, during the DB read.

Sorry, I did not put an example in my message. This is a simplified version of my actual code:

```python
    # sqlalchemy and psycopg3
    engine = sqlalchemy.create_engine("postgresql://blabla")

    df = pl.read_database(
        "SELECT order_id, order_uuid FROM orders",
        engine,
        schema_overrides={
            "order_id": pl.Int64,
            "order_uuid": pl.Utf8,
        },
    ).with_columns(
        order_uuid=pl.col('order_uuid').map_elements(convert_uuid, return_dtype=str),
    )
```

if order_uuid is an UUID in Postgres then the database engine produces `UUID` objects, and polars gives an error trying to collect them, even if I pass the type explicitly. If I specify `order_uuid::TEXT` in the query then I get the UUID as text and then I can go on and convert it with `with_columns`, but that is executed after the data is read form the database.

**Comment by deanm0000** [comment]
As an aside, have you tried bypassing sqlalchemy and using the `read_database_uri` method? I'm not sure if it automatically handles UUID columns any better but it'll be better performance going through connectorx.

**Comment by jacopofar** [comment]
Interesting, `read_database_uri` uses `connectorx` and does the conversion to str automatically:

```python
# !python3 -m pip install connectorx
a = pl.read_database("""select NULL union all SELECT '1ac6b91a-0605-4459-93dc-18f210a70192'::uuid""", engine)
b = pl.read_database_uri("""select NULL union all SELECT '1ac6b91a-0605-4459-93dc-18f210a70192'::uuid""", "postgresql://john:john@localhost:5432")
a.dtypes, b.dtypes

# ([Object], [String])
````

Another workaround in this specific case it to set an [adapter in psycopg3](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html#example-postgresql-numeric-to-python-float) to convert UUIDs to str or other types.

Having the possibility of converting data on the fly or at least know the column that is generating the issue would be nice, but it's not a blocker for me.

**Comment by alexander-beedie** [comment]
> Here's an easier way to deal with Object to string conversion actually and it doesn't trip the warning...
> 
> ```
> df.with_columns(pl.col(pl.Object).map_elements(lambda x: str(x) if hasattr(x, "__str__") else x))
> ```
> 
> @stinodego should something like this be implemented at the reader level or leave it to user? Instead of looking for UUID types specifically, which would be a never ending line of each custom python type being requested, just look to see if it has `__str__`. The logic could be, if they gave a schema that specified String for a column but we got an Object from the source then do the above?

I believe this was @orlp's suggestion/intention - eg: if an `Object` is explicitly cast to `String`, the most reasonable thing to do is simply call `str(obj)` (or `obj.__str__()`) on our side in Rust. It wouldn't be great performance but it _would_ be good UX (and the performance can't be made better anyway), and it clearly matches the user's intention.

This wouldn't be specific to `read_database` either; as noted in the other comments you can handle this _most_ efficiently by casting the UUID column to string in the query itself. All other options result in multiple Python objects being created and thrown away per-value (ingested as string, then initialised to uuid, then back to string again).
