### ISSUE TITLE
Allow duckdb as an engine backend via its "relational API"

### ISSUE THREAD

**Issue by natemcintosh** [pola-rs/polars#15581]
### Description

While the polars engine and the duckdb engine have large overlaps in their areas of intended use, there are a few (though diminishing) areas which duckdb covers and polars does/will not. This feature request proposes something similar to [duckplyr](https://duckdb.org/2024/04/02/duckplyr.html) for polars: an ability to translate a polars expression to duckdb's "relational API". (See the [verbs section](https://duckdb.org/2024/04/02/duckplyr.html#verbs) the conversation about skipping over SQL.)

That said, I have no idea how much effort this would be 😅, so feel free to close and say "won't do".

**Comment by orlp** [comment]
We don't want to do this for similar reasons I outlined here: https://github.com/pola-rs/polars/issues/7404#issuecomment-2049534546.
