### ISSUE TITLE
Reconsider default for statistics in parquet writer

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#15586]
### Description

With polars on the verge of doing native dataset writing, it seems it's a good time to rethink the default statistics behavior. Datasets largely depend on having statistics so it seems the small price to pay to calculate them at write time is worth it at read time. I suppose the standalone writer could still default to False but the dataset writer would have to have statistics turned on (wouldn't it?). I think that might create more confusion for those two to be different so just another reason to turn them on by default in the standalone writer.

**Comment by ritchie46** [comment]
Yeap, agree. I think we should default to True. Can you open a PR?

**Comment by ritchie46** [comment]
I don't think this would be breaking. The files would still be read correctly.

**Comment by deanm0000** [comment]
https://github.com/pola-rs/polars/pull/15597
