### ISSUE TITLE
filter() should default to no filter if no predicate or constraint provided

### ISSUE THREAD

**Issue by tobackes** [pola-rs/polars#15591]
### Description

It would be cleaner in my opinion if `df.filter()` would return the whole `df`.

Consider a dynamically produced filter dictionary, which in some cases may be empty. Currently it is necessary to specifically check for the case that there is no constraint, i.e. the dictionary is empty and then specify the default case of returning the whole dataframe.

I think this is a matter of logical consistency.

**Comment by orlp** [comment]
Allowing `df.filter()` seems rather odd to specifically allow this. May I suggest the alternative `df.filter(True, *conds)`?
