### ISSUE TITLE
Scalar comparison of boolean series doesn't work as expected

### ISSUE THREAD

**Issue by CloseChoice** [pola-rs/polars#1559]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.5

#### What operating system are you using polars on?

Ubuntu 18.04

#### Describe your bug.
Comparison of a boolean series with a scalar bool doesn't work element-wise.
```python
>>> srs = pl.Series([True, False])
>>> srs == False
False
```
Expected:
```python
>>> (srs == False).to_list()
[False, True]
```

**Comment by zundertj** [comment]
I would have expected this to be element-wise, given that `pl.Series.series_equal` exists. Note that you can get the element-wise behavior by wrapping the scalar into a `Sequence`, such as a list, or `pl.Series`, i.e.:

```python
>>> srs = pl.Series([True, False])
>>> srs == [False]   
shape: (2,)
Series: '' [bool]
[
	false
	true
]
```

**Comment by zundertj** [comment]
To provide some more color, it seems it is specific to when the Series is of dtype boolean, not the value to compare with:

```python
>>> import polars as pl
>>> pl.Series([1, 2]) == 1
shape: (2,)
Series: '' [bool]
[
	true
	false
]
>>> pl.Series(["hello", "world"]) == "hello"
shape: (2,)
Series: '' [bool]
[
	true
	false
]
>>> pl.Series([1, 2]) == True
shape: (2,)
Series: '' [bool]
[
	true
	false
]
>>> pl.Series([True, False]) == True
False
```

**Comment by ritchie46** [comment]
This is not expected to work elementwise. You should use the `&` and `|` operators for elementwise comparissons.
