### ISSUE TITLE
read_csv() and scan_csv() usually corrupt the schema when `dtypes` contains columns not in the schema

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#15605]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> print('A', file=open('B.txt', 'w'))
>>> pl.read_csv('B.txt', dtypes={'C': pl.String}).columns
['C']
>>> pl.scan_csv('B.txt', dtypes={'C': pl.String}).columns
['C']
>>> pl.scan_csv('B.txt', dtypes={'C': pl.String}).collect().columns
['C']
>>> pl.read_csv('B.txt', has_header=False, new_columns=['C'], dtypes={'D': pl.String}).columns  # this is the only one that doesn't corrupt the schema
['C']
>>> pl.scan_csv('B.txt', has_header=False, new_columns=['C'], dtypes={'D': pl.String}).columns
['C', 'D']
>>> pl.scan_csv('B.txt', has_header=False, new_columns=['C'], dtypes={'D': pl.String}).collect().columns
['column_1']
```

### Issue description

When the `dtypes` argument to `read_csv()` or `scan_csv()` contains columns not in the schema, there is no error, and schema (usually) gets corrupted.

### Expected behavior

All of these cases should give an error.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by JulianCologne** [comment]
yes, there are currently many weird interactions and unexpected behaviour with a few parameters in `read_csv`.

I really hope this #15431 fixes it 😄

**Comment by stinodego** [comment]
I believe this is covered by https://github.com/pola-rs/polars/issues/14385, so closing in favor of that one.
