### ISSUE TITLE
DeprecationWarning: `replace` is deprecated. DataFrame.replace is deprecated and will be removed in a future version. However, replace is not deprecated according to docs

### ISSUE THREAD

**Issue by AndreaPi** [pola-rs/polars#15601]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "random": np.random.rand(5),
        "A": [True, True, False, False, False],
    }
)
import string
new_names = list(string.ascii_lowercase)[:len(df)]
df = df.replace('names', pl.Series(new_names))

```

### Issue description

Running the code above results in

```
DeprecationWarning: `replace` is deprecated. DataFrame.replace is deprecated and will be removed in a future version. Please use
    df = df.with_columns(new_column.alias(column_name))
instead.
  df = df.replace('names', pl.Series(new_names))
```

However, the current documentation doesn't make any mention of `replace` being deprecated:
https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.replace.html#polars.DataFrame.replace
Thus, either the warning or the documentation are wrong.

### Expected behavior

See above

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems the docs just need to be updated.

- https://github.com/pola-rs/polars/pull/10600

**Comment by AndreaPi** [comment]
@cmdlineluser thanks for the link. So it was an error in the docs, after all. I'm not sure if this is the right place to mention it, but I think deprecating `replace` and substituting it with `with_columns` introduces the opportunity for bugs. If one mistypes the column name, `replace` raises an error:

`df.replace('sleppa', pl.Series(new_names))
`

while `with_columns` happily creates a new column with the wrong name:

`df = df.with_columns(pl.Series('sleppa', new_names))
`

**Comment by cmdlineluser** [comment]
Yeah, the approaches do differ a bit alright.

[`.replace_column()`](https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.replace_column.html#polars.DataFrame.replace_column) appears to exist, which takes an index.

[`.get_column_index()`](https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.get_column_index.html#polars.DataFrame.get_column_index) seems to return `None` for a non-match, which causes an error but probably not an intended one.

```python
df.replace_column(df.get_column_index("name"), pl.Series('name', new_names))
# TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Using `df.columns.index["name"]` instead of `.get_column_index` would return a `NameError`.

I think the reason for pointing towards `.with_columns` instead is because the replace methods modify in-place and the desire is to remove/hide those operations from the public API.
