### ISSUE TITLE
Section of Aggregation of LazyFrame - Function count

### ISSUE THREAD

**Issue by jmcurbelo** [pola-rs/polars#15619]
### Description

Currently in the documentation exists the count function for LazyFrame but it do not exist for LazyFrame.
![1712873295454](https://github.com/pola-rs/polars/assets/52831862/ed8b1e89-5017-453f-bcf8-d7e956da85f3)

### Link

https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.count.html

**Comment by mcrumiller** [comment]
You must be on an old version, this does indeed work:

```shell
>>> import polars as pl
>>> pl.LazyFrame({"a": [1, 2, 3]}).count().collect()
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 3   │
└─────┘
```

**Comment by jmcurbelo** [comment]
You are right, I was in 0.20.0 version. I updated and it work. Thanks.

**Comment by jmcurbelo** [comment]
It work in version 0.20.19.
