### ISSUE TITLE
Section LazyFrame, subsection Descriptive - Function describe

### ISSUE THREAD

**Issue by jmcurbelo** [pola-rs/polars#15620]
### Description

The describe function in the section LazyFrame not exist for a LazyFrame.
<img width="640" alt="1712898729288-2" src="https://github.com/pola-rs/polars/assets/52831862/8a9068a4-9de9-4572-a63b-bb8f03c358be">

### Link

https://docs.pola.rs/py-polars/html/reference/lazyframe/api/polars.LazyFrame.describe.html

**Comment by mcrumiller** [comment]
`describe` shows statistics about the values in each column. Lazy frames have no values; call `lf.collect().describe()`.

**Comment by mcrumiller** [comment]
You must be on an old version, this does indeed work:

```shell
>>> import polars as pl
>>> pl.LazyFrame({"a": [1, 2, 3]}).describe()
shape: (9, 2)
┌────────────┬─────┐
│ statistic  ┆ a   │
│ ---        ┆ --- │
│ str        ┆ f64 │
╞════════════╪═════╡
│ count      ┆ 3.0 │
│ null_count ┆ 0.0 │
│ mean       ┆ 2.0 │
│ std        ┆ 1.0 │
│ min        ┆ 1.0 │
│ 25%        ┆ 2.0 │
│ 50%        ┆ 2.0 │
│ 75%        ┆ 3.0 │
│ max        ┆ 3.0 │
└────────────┴─────┘
```

**Comment by jmcurbelo** [comment]
It work in version 0.20.19. Thanks.
