### ISSUE TITLE
Groupby on integer + date column of large dataframe requests enormous memory alloc [Windows only]

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#1562]
#### Are you using Python or Rust?

**Python**

#### Which feature gates did you use?
NA

#### What version of polars are you using?
0.10.5

#### What operating system are you using polars on?

Windows10

#### Describe your bug.
Polarsa fails to execute groupby on modestly sized dataframe

#### What are the steps to reproduce the behavior?
I've used something like the below code to generate the data (it's pretty big) and then run the `polars_load` function

```python
import pandas as pd
import polars as pl

def make_some_data():
  n_ids = int(1e3)
  n_features = 10
  freq = "1H"
  year = 2000
  start = f"{year}0101"
  end = f"{year + 1}0615" # one year and a bit
  date_index = pd.date_range(start=start, end=end, freq=freq, closed="left")
  dates= np.tile(date_index, n_ids)
  n_dates = len(date_index)
  
  ids = np.repeat(np.arange(n_ids, dtype=np.int32), n_dates)
  features= np.random.randn(n_ids * n_dates, n_features).astype(np.float32)
  df = pd.DataFrame(
      {
          "ids": ids,
          "dates": dates,
      }
  )
  df[[f"feature_{i}" for i in range(n_features)]] = features
  
  print(f"\t[year={year}] n_ids={n_ids}, n_dates={n_dates}, n_rows={n_ids * n_dates}, n_cols={n_features}", flush=True)
  df.to_parquet(data_path / f"features_{year}.parquet")

def pandas_load(data_dir: Path):
    import pandas as pd

    df = pd.read_parquet(f)
    agg_df = df.groupby(["ids", "dates"]).agg("mean")
    return agg_df


def polars_load(df):
    df = pl.read_parquet(f)
    agg_df = df.groupby(["ids", "dates"]).agg(pl.col("*").mean())

    return agg_df
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?
I get the following error

```
UserWarning: Conversion of (potentially) timezone aware to naive datetimes. TZ information may be 
lost
  "Conversion of (potentially) timezone aware to naive datetimes. TZ information may be lost",
memory allocation of memory allocation of memory allocation of 191160001911600019116000 bytes failed
```

The CPU usage goes to 100, memory stays modest, and then the screen goes dark and I regain control after a minute or two with an unkillable `python.exe -System Error` window

#### What is the expected behavior?
Running the `pandas_load` function exhibits the correct behaviour.

**Comment by ritchie46** [comment]
Ok, let's break it down a bit. Its a bit hard to tell what could cause this. The dates should not matter at all, integers should have exactly the same effect.

Polars does have a fast path for grouping on two keys. This fast path does do an extra allocation of the keys itself. Then there seems to be some extra allocation in the parallelism. 

When you `pl.col("forecast_0").mean()` you allocate a new column that holds the mean values. When you run `pl.col("*").mean()` you allocate for all new columns. How much RAM do you have left in the pandas operation?

**Comment by CHDev93** [comment]
I ran `pip install -U polars` which gave me `0.10.6`. Weirdly, it does mention attempting to get polar-0.10.7.tar.gz but then goes and gets `polars-0.10.6-cp36-cp36-abi3-win_amd64.whl`.

In any case, I get a similar failure symptoms as before but without the message in stdout mentioning the attempted bytes allocated.

`pl.scan_parquet` fails in the same way as before as well if that's of interest

**Comment by CHDev93** [comment]
Still not managing to find the windows wheel when pip tries to install but this could have something to do with the pypi mirror I'm using. 

I did get ahold of a linux machine and tested with polars==0.10.5 and python 3.8 and the code does not fail. I'm convinced something is wrong with windows. Do you have any ability to verify on windows (e.g. AWS)? I have seen Windows and Linux differ when loading a parquet file (one loading int32 and the other int64) so perhaps something like that?

**Comment by ritchie46** [comment]
> I did get ahold of a linux machine and tested with polars==0.10.5 and python 3.8 and the code does not fail. I'm convinced something is wrong with windows. Do you have any ability to verify on windows (e.g. AWS)? I have seen Windows and Linux differ when loading a parquet file (one loading int32 and the other int64) so perhaps something like that?

We could check the schema? But I don't think this should be the problem if you have 100GB RAM and I can run this on my 16GB machine. 

And no, I don't have any windows mah

**Comment by CHDev93** [comment]
Checked the schemas on both windows and linux and see
```python
ids: int32
dates: timestamp[us]
...
```

I do still see the `scan_parquet` issue on both windows and linux however
```
thread '<unnamed>' panicked at 'Arrow datatype Timestamp(Nanosecond, None) not supported by Polars
```
Odd because the parquet schema seems to think it's microseconds. One other thing I can think of that differs between windows and linux is forking vs spawning of processes. I assume by the above error that you're using threading rather than multiprocessing right?
