### ISSUE TITLE
Make `.columns` a Series object?

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#15634]
### Description

Just as an experiment, I wrapped this in  `pl.Series()`

<ul>
<blockquote>

https://github.com/pola-rs/polars/blob/be29982a30dec0bed2a100e47ab4dd90483011ee/py-polars/polars/dataframe/frame.py#L654

</blockquote>
</ul>

## Example

A contrived exampled, but just an attempt to display some column manipulation / renaming.

```python
import polars as pl

df = pl.DataFrame([[1, 2, 3, 4]], schema=["A.1", "B.2", "c.3", "dd"])

(df.columns
   .str.replace(r"[.]\d+$", "")
   .str.to_lowercase()
   .replace(["dd", "ee"], ["d", "e"]) # Expr.replace to "rename" columns
)
# shape: (4,)
# Series: '' [str]
# [
# 	"a"
# 	"b"
# 	"c"
# 	"d"
# ]
```

```python
df.columns = df.columns.str.replace(r"[.]\d+$", "").str.to_lowercase().replace(["dd", "ee"], ["d", "e"])
# shape: (1, 4)
# ┌─────┬─────┬─────┬─────┐
# │ a   ┆ b   ┆ c   ┆ d   │
# │ --- ┆ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╪═════╡
# │ 1   ┆ 2   ┆ 3   ┆ 4   │
# └─────┴─────┴─────┴─────┘
```

Polars can already do this in other ways, but it seems like having direct access to the Polars API via `.columns` could allow for more interesting behaviour?

```python
>>> df.columns.filter(df.columns.is_between("b", "d"))
shape: (3,)
Series: '' [str]
[
	"b"
	"c"
	"d"
]
```

## Perhaps `Series` is not enough

Being a `Series` object - It would break this current behaviour:

```python
df.select(df.columns)
# shape: (4, 1)
# ┌─────┐
# │     │
# │ --- │
# │ str │
# ╞═════╡
# │ a   │
# │ b   │
# │ c   │
# │ d   │
# └─────┘
````

```python
df.select(*df.columns)
# shape: (1, 4)
# ┌─────┬─────┬─────┬─────┐
# │ a   ┆ b   ┆ c   ┆ d   │
# │ --- ┆ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╪═════╡
# │ 1   ┆ 2   ┆ 3   ┆ 4   │
# └─────┴─────┴─────┴─────┘
```

Perhaps it would need to be a special `pl.Columns` Series that could handle this and behave differently.

**Comment by alexander-beedie** [comment]
We can already consistently handle all of these cases through the expression `name` namespace, without needing to return "columns" as a Series ;)

For example:
```python
df = pl.DataFrame(
    data=[[1, 2, 3, 4]],
    schema=["A.1", "B.2", "c.3", "dd"],
)
df.select(pl.all().name.map(lambda x: x.lower()[0]))
# shape: (1, 4)
# ┌─────┬─────┬─────┬─────┐
# │ a   ┆ b   ┆ c   ┆ d   │
# │ --- ┆ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╪═════╡
# │ 1   ┆ 2   ┆ 3   ┆ 4   │
# └─────┴─────┴─────┴─────┘
```
We can always add a few more native options into the available `name` expressions if you think they might be useful, to avoid the need to call out to a mapping lambda.

**Comment by cmdlineluser** [comment]
Thanks @alexander-beedie 

Yeah the rename example was mainly prompted by a question from a user who was using `DataFrame.rename(lambda x: ...)` 

They were attempting to use `x.str.strip_chars()` inside assuming it ran in a Polars context as opposed to a Python one.

Perhaps not the best example use-case - but it just made me wonder about `.columns` being a Python list when it could be potentially more useful as a Polars type.

(Similar to `.columns` in pandas being a `pd.Index` object)

I didn't realize about any potential disruption - so please feel free to close.
