### ISSUE TITLE
Add link to Fastexcel docs on `pl.read_excel(...)` page for easy reference of valid options in the `read_options=...` arg

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#15640]
### Description

I would appreciate if you linked to the `load_sheet_by_name(...)` docs from the `pl.read_excel(...)` docs: https://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_sheet_by_name

It says that you can use the `read_options={...}` arg to pass arguments to the `load_sheet_by_name` function, but doesn't really give any info about what sort of options exist. A link to the docs would make this much easier to work with and look up.

### Other Justifications
* There are a lot of FastExcel libraries out there, including one in Java that's more popular. Finding the right docs in the first place is tough.
* It'd be helpful.

### Link

https://docs.pola.rs/py-polars/html/reference/api/polars.read_excel.html

**Comment by cmdlineluser** [comment]
This has also been requested in a broader issue:

- https://github.com/pola-rs/polars/issues/15596

**Comment by alexander-beedie** [comment]
Yup, agreed; I'm looking at this at the moment, along with an upgrade to `read_ods` to integrate the calamine engine there too. Will close this out in favour of https://github.com/pola-rs/polars/issues/15596 to avoid the duplicate 👌
