### ISSUE TITLE
Part 3 PyO3 0.21 upgrade: Remove usage of deprecated numpy crate APIs

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#15666]
### Description

`numpy` has switched a number of APIs to use PyO3's new `Bound<>` API. We should use `numpy`'s new replacement APIs instead of the deprecated ones.

Search for "#15215" to find places where deprecation is manually suppressed; there should be none left when this PR is merged.

**Comment by itamarst** [comment]
Ah, looks like Ritchie did most of these already.

**Comment by ritchie46** [comment]
Yes, I think it would also be worth it to use the bounded API wherever we can. This can increase perf by 25% according to their benchmarks. So we should see if we can remove all GilRef API usages (even if not deprecated yet).

**Comment by itamarst** [comment]
The other APIs are also deprecated, it's just the deprecation warnings are suppressed by the `gil-refs` feature in the `pyo3` crate to make upgrades easier.

This issue is specifically about the `numpy`. Switching to `Bound<>` for `pyo3` crate APIs is what I will start on next (i.e. next 5 minutes :grin:).
