### ISSUE TITLE
qcut gives different output when using with "over"

### ISSUE THREAD

**Issue by mishavanbeek** [pola-rs/polars#15670]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime

import polars as pl
import polars.testing
import numpy as np

assert pl.__version__ == "0.20.20"

ids = ["a", "b", "c", "d", "e"]
dates = [datetime(2021, 1, i + 1) for i in range(4)]

np.random.seed(42)
value = np.random.normal(size=len(dates) * len(ids))

df = pl.DataFrame({
    "date": [d for d in dates for _ in ids],
    "id": [i for _ in dates for i in ids],
    "value": value,
})

quantiles = [0.2, 0.4, 0.6, 0.8]
labels = [str(i) for i in range(len(quantiles) + 1)]

# testing for same output every time
for i in range(100):
    test_df = (
        df
        .with_columns(pl.col("value").qcut(quantiles, labels=labels, include_breaks=True).over("date").alias("brk"))
        .unnest("brk")
        .with_columns(pl.col("_bin").cast(pl.Int64))
    )
    if i > 0:
        pl.testing.assert_frame_equal(test_df, test_df_last)
    test_df_last = test_df
```

### Log output

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
    [... skipping hidden 2 frame]

File ~/Work/projects/bayesline/code/lib/common/.venv/lib/python3.11/site-packages/polars/testing/asserts/utils.py:12, in raise_assertion_error(objects, detail, left, right, cause)
     11 msg = f"{objects} are different ({detail})\n[left]:  {left}\n[right]: {right}"
---> 12 raise AssertionError(msg) from cause

AssertionError: Series are different (exact value mismatch)
[left]:  [0, 2, 3, 1, 4, 2, 1, 3, 4, 0, 3, 0, 1, 4, 2, 3, 2, 1, 0, 4]
[right]: [2, 1, 3, 4, 0, 1, 4, 3, 0, 2, 3, 2, 4, 0, 1, 3, 1, 4, 2, 0]
```

### Issue description

When used with the "over", qcut may give totally different (incorrect) output randomly every 10 or so times. Also (although not necessarily a bug) the output struct has "_bin" rather than <column>_bin as the name.

### Expected behavior

The example would not throw an error every 10th time or so. It seems like usually the code gives the correct output (tested against numpy.quantile).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.20
Index type:           UInt32
Platform:             macOS-14.4-arm64-arm-64bit
Python:               3.11.6 (main, Dec 20 2023, 23:16:20) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.0
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

The loss of the root name in a groupby context does appear to be another bug:

```python
pl.DataFrame({"a": [1]}).select(pl.all().qcut([1], include_breaks=True).over(1)).schema["a"]
# Struct({'brk': Float64, '_bin': Categorical(ordering='physical')})
```

```python
pl.DataFrame({"a": [1]}).select(pl.all().qcut([1], include_breaks=True)).schema["a"]
# Struct({'brk': Float64, 'a_bin': Categorical(ordering='physical')})
```

**Comment by MarcoGorelli** [comment]
thanks for the report - is it possible to make a smaller and simpler reproducible example?

**Comment by mishavanbeek** [comment]
Thanks for the quick response. The following is a smaller example. The "ID" columns can be removed by it there so you can check that the sorting order is maintained.

```python
import polars as pl
import numpy as np
import numpy.testing as tst

df = pl.DataFrame({
    "group": [1, 1, 1, 2, 2],
    "id": list("abcde"),
    "value": [1.0, 0.5, 0.2, 3.0, 4.5],
})

quantiles = [0.2, 0.4, 0.6, 0.8]
labels = [str(i) for i in range(len(quantiles) + 1)]


for i in range(1000):
    test = (
        df
        .with_columns(pl.col("value").qcut(quantiles, labels=labels, include_breaks=True).over("group"))
        .select(pl.col("value").struct.field("_bin").cast(pl.Int64))
        .to_numpy()
        .flatten()
    )
    if i > 0:
        tst.assert_array_equal(test.astype(int), test_last.astype(int))
    test_last = test
```

I was having some issues with making this smaller since removing the "labels" part that requires a few more lines of code in the loop actually makes the dataframe not render. For example, the following will break on my end:
```python
df.with_columns(pl.col("value").qcut(quantiles, include_breaks=True).over("group"))
```

Oddly enough, in the code above if you remove the ".cast(pl.Int64)" part, it will run (using the numpy casting). So that leads me to believe that the problem is not in qcut, but actually in the cast (which is surprising to me).

**Comment by orlp** [comment]
The reason this doesn't work the way you expect it to is because `.cast(pl.Int64)` doesn't cast the categorical string to an integer, but instead the underlying categorical index, which wasn't deterministic before.

I made that deterministic now if you have a fixed set of labels so this works. On the old version this would also work, which actually casts the string value of the categorical to an integer:

```
.with_columns(pl.col("value_bin").cast(pl.String).cast(pl.Int64))
```

Keep in mind that using `qcut` in an `over` uses different quantiles for each group, so the results might not be what you expect regardless of this bug.

**Comment by mishavanbeek** [comment]
> I made that deterministic now if you have a fixed set of labels so this works. On the old version this would also work, which actually casts the string value of the categorical to an integer:

Thank you I really appreciate this.
