### ISSUE TITLE
Support time travel in `read_delta`

### ISSUE THREAD

**Issue by maxzw** [pola-rs/polars#15692]
### Description

Though python polars' `read_delta` allows you to pass "version" as argument, it is not yet possible to do time travel.

Delta-rs allows time travel in the following way
```python
DeltaTable("../rust/tests/data/simple_table").load_as_version("2021-11-04 00:05:23.283+00:00")
```

I believe it's quite easy to add an argument (e.g. "datetime_as_of") to the appropriate functions and propagate it to `_get_delta_lake_table` like:
```python
dl_tbl = deltalake.DeltaTable(
    table_path,
    version=version,
    storage_options=storage_options,
    **delta_table_options,
)
dl_tbl = dl_tbl.load_as_version(datetime_as_of)
```

**Comment by stinodego** [comment]
This would be good to support, should be easy as you said.

**Comment by stinodego** [comment]
@maxzw Actually, it looks like `read_delta` and `scan_delta` already have a `version` parameter. Is this not what you're looking for?

**Comment by ion-elgreco** [comment]
@stinodego you can provide upfront the table version to read, but what @maxzw is looking for is that `read_delta` and `scan_delta` can also get a version that is represented as a datetime / string datetime. 

Should be easy to refactor that.

If the version is an `int`, use `DeltaTable(path, version=version),` else use `DeltaTable(path).load_as_version(version=version)`

**Comment by stinodego** [comment]
That sounds good. We should also support `datetime` inputs, e.g. `version: int | str | datetime | None = None`. 

And then we can just offload all version logic to `load_as_version`, no need to pass it to the `DeltaTable` constructor anymore, e.g.:

```python
if version is not None:
	dt = dt.load_as_version(version)
```

...or would passing `version` to the constructor have a performance benefit?

@ion-elgreco would you be interested in making a PR for this?

**Comment by ion-elgreco** [comment]
@stinodego if it's a numerical version you ideally do it in the DeltaTable instantiation, so that you don't read unnecessary log segments.

Sure I can look at it later this week :)
