### ISSUE TITLE
Support projection in arrow::io::ipc:read::FileReader:new

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1569]
#### Describe your feature request

Support projection (reading only specific columns) when reading an IPC file in lazy mode: 

https://github.com/pola-rs/polars/blob/1a6db2919ef312e3da959c5f74da09e6cd99ebb0/polars/polars-io/src/ipc.rs

Support for projection in lazy mode can be adapted from:
https://github.com/pola-rs/polars/blob/master/polars/polars-io/src/parquet.rs

Specifying column names to load from IPC and parquet in eager mode, would be great too:

https://github.com/pola-rs/polars/blob/1a6db2919ef312e3da959c5f74da09e6cd99ebb0/polars/polars-io/src/ipc.rs#L96

https://github.com/pola-rs/polars/blob/master/polars/polars-io/src/parquet.rs#L111-L117

**Comment by illumination-k** [comment]
May I work on this issue?

**Comment by ghuls** [comment]
@illumination-k I think @ritchie46 is working on `pl.scan_ipc`(Support projection (reading only specific columns) when reading an IPC file in lazy mode:) already. Or I misunderstood and he was planning to work on it.

If you could tackle reading specified columns in eager mode, that would be great.

**Comment by illumination-k** [comment]
@ghuls Thanks for your reply. Let me check. The tasks are implementing `with_columns`, `with_projection` in earger mode and rewriting `finish` method, right? If so, I would like to tackle this.
