### ISSUE TITLE
Rather than just deprecating `replace`, find a way to check that a column exists before replacing in the new API too

### ISSUE THREAD

**Issue by AndreaPi** [pola-rs/polars#15700]
### Description

`df.replace` is deprecated: https://github.com/pola-rs/polars/issues/15601 `df.with_columns` is proposed instead. However, `with_columns` is not really a "replacement" for `replace`, because `replace` checks that the column being replaced exists, before replacing, while  `with_columns` doesn't, creating the opportuning for bugs like this:

```
import polars as pl
import numpy as np
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "random": np.random.rand(5),
        "A": [True, True, False, False, False],
    }
)
import string
new_names = list(string.ascii_lowercase)[:len(df)]
df.with_columns(pl.Series('name', new_names))
```

https://github.com/pola-rs/polars/issues/15601#issuecomment-2058909145 suggests using replace_column in combination with `df.columns.index` or `get_column_index` in order to get around this, but then we just substitute the simple, intuitive syntax

`df.replace('names', pl.Series(new_names))`

with the way more verbose

`df.replace_column(df.get_column_index("names"), pl.Series('names', new_names))
`

Doesn't seem good progress to me. I understand that the maintainers want to hide inplace methods from the users. But rather than just deprecating `replace`, would it be possible to substitute it with some method (non necessarily inplace) which however checks for the existence of a column before replacing? After all, a good API for replacing columns in a dataframe should do that.

**Comment by ritchie46** [comment]
Don't you want to use `df.rename`?

**Comment by MarcoGorelli** [comment]
They want to do something like
```
df.with_columns(
    foo = bar
)
```
but have it error if `'foo'` isn't already the name of a column in `df`

**Comment by MarcoGorelli** [comment]
One suggestion could be to deprecate `rename_column` (which is also in-place, and probably a leftover from the more pandas-like api?) and introduce have `rename_columns`, which is just like `with_columns` but raises if you pass a new column name instead of an existing one

Or just leave it to the user to make a helper function like
```
def replace_column(df, column_name, new_column):
    if new_column not in df.columns:
        raise ValueError(f'{new_column} not found in {df.columns}')
    return df.with_columns(column_name=new_column)
```

**Comment by JulianCologne** [comment]
not an ideal solution but imo `df.replace_column` should also work using the column name

**Polars uses column names everywhere!**
It is super strange that it currently works like
- `df.replace_column(7, Series(...))` indead of
- `df.replace_column("foo", Series(...))`

imo it would be an improvement to also allow `str` to specify the column

**Comment by AndreaPi** [comment]
> One suggestion could be to deprecate `rename_column` (which is also in-place, and probably a leftover from the more pandas-like api?) and introduce `DataFrame.rename_columns`, which would be just like `with_columns` but raise if you pass a new column name instead of an existing one

I like this! But I think `DataFrame.replace_columns` (note, `columns`, not `column`) would be a better name than `DataFrame.rename_columns`.  The intent is not to replace the _name_ of one of more columns, but the `content`, without changing the name (and, as you correctly noted, raise if you pass a new column name instead of an existing one).

> Or just leave it to the user to make a helper function like

Well, that's an option, but I think a library to manipulate dataframes should allow the possibility to replace one or more column. It doesn't need to be inplace! But I think it should be there. My two cents.

**Comment by AndreaPi** [comment]
> not an ideal solution but imo `df.replace_column` should also work using the column name
> 
> **Polars uses column names everywhere!** It is super strange that it currently works like
> 
> * `df.replace_column(7, Series(...))` indead of
> * `df.replace_column("foo", Series(...))`
> 
> imo it would be an improvement to also allow `str` to specify the column

This would work too! But, as @MarcoGorelli  noted, `replace_column `is inplace, and it is my understanding that the developers want to reduce/eliminate the inplace public methods.

**Comment by cmdlineluser** [comment]
Would it make sense to expose this behaviour at the expression level?

Which would allow to depend on a `ColumnNotFoundError`

For the given example, this "works" - but I'm not sure about any wider implications.

```python
df.with_columns(
    pl.col("names")
      .map_batches(lambda x: pl.Series(new_names))
)
```

**Comment by s-banach** [comment]
If you want to assert that `set_A` of strings is a subset of `set_B` of strings, just do that on your own in python.

**Comment by ritchie46** [comment]
> but have it error if `'foo'` isn't already the name of a column in `df`

Something like this? 

```python
df = pl.DataFrame(
    {
        "bar": ["foo", "ham", "spam", "egg", None],
    }
)

print(df.pipe(lambda df: df.with_columns(foo = 1) if "foo" in df.schema else df))


print(df.pipe(lambda df: df.with_columns(foo = 1) if "bar" in df.schema else df))
```

```
shape: (5, 1)
┌──────┐
│ bar  │
│ ---  │
│ str  │
╞══════╡
│ foo  │
│ ham  │
│ spam │
│ egg  │
│ null │
└──────┘
shape: (5, 2)
┌──────┬─────┐
│ bar  ┆ foo │
│ ---  ┆ --- │
│ str  ┆ i32 │
╞══════╪═════╡
│ foo  ┆ 1   │
│ ham  ┆ 1   │
│ spam ┆ 1   │
│ egg  ┆ 1   │
│ null ┆ 1   │
└──────┴─────┘
```

**Comment by MarcoGorelli** [comment]
after some discussion, this isn't currently planned - closing for now then, but this can always be revisited in the future
