### ISSUE TITLE
value is a list (of dates in this case). Wanted to subtract another column (scalar date) from all the entries.

### ISSUE THREAD

**Issue by zbenmo** [pola-rs/polars#15706]
### Description

PanicException: `sub` operation not supported for dtype `list[date]`

**Comment by zbenmo** [comment]
May be related: https://stackoverflow.com/questions/76817818/how-can-i-perform-operations-between-a-list-and-scalar-column-in-polars

https://github.com/pola-rs/polars/issues/8006

**Comment by alexander-beedie** [comment]
I think you want list eval; subtracting a scalar value from a list value isn't a valid operation (as you have discovered ;)
```python
from datetime import date
import polars as pl

d = date.today()

df = pl.DataFrame(
  data={"dts": [[d,d],[d,d]]},
).with_columns(
  sub = pl.col("dts").list.eval(pl.element() - date(2024,1,1))
)
# shape: (2, 2)
# ┌──────────────────────────┬────────────────────┐
# │ dts                      ┆ sub                │
# │ ---                      ┆ ---                │
# │ list[date]               ┆ list[duration[ms]] │
# ╞══════════════════════════╪════════════════════╡
# │ [2024-04-17, 2024-04-17] ┆ [107d, 107d]       │
# │ [2024-04-17, 2024-04-17] ┆ [107d, 107d]       │
# └──────────────────────────┴────────────────────┘
```

**Comment by zbenmo** [comment]
.list.eval is indeed promising, it works at least at the moment with a constant scalar yet not with a scalar from another column.

For my current use case, I'll solve it by having the list column first as long format (exploded), with the needed date duplicated for all rows in another column, and only then group_by and agg.
