### ISSUE TITLE
pl.Series.append does not append!

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#1571]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

'0.10.6'

#### What operating system are you using polars on?

windows 10

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

python
import polars as pl
import numpy as np

s = pl.Series("a", [1, 2, 3])
s
r = pl.Series("b", [4, 5, 6])
r```

append = s.append(r)
append

#### What is the actual behavior?

no new pl.Series object

#### What is the expected behavior?

new pl.Series object

**Comment by ritchie46** [comment]
I believe append is in place.
