### ISSUE TITLE
Calling `to_list()` on a timezone aware datetime column causes panic on Windows

### ISSUE THREAD

**Issue by mishamsk** [pola-rs/polars#15723]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import timezone, datetime
import polars as pl

dt = pl.Datetime(time_zone="UTC")
tm = datetime.now(tz=timezone.utc)

df = pl.DataFrame({"dttm":tm}, schema={"dttm":dt})

df.head() # works and shows correct type & one row

df["dttm"].to_list()
# thread '<unnamed>' panicked at py-polars\src\conversion\chunked_array.rs:66:82:
# called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x0000020993D45500>) }
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# Traceback (most recent call last):
#   File "C:\Users\xxx\Desktop\test\polars_err_dttm.py", line 11, in <module>
#     df["dttm"].to_list()
#   File "C:\Users\xxx\Desktop\test\.venv\Lib\site-packages\polars\series\series.py", line 4196, in to_list
#     return self._s.to_list()
#            ^^^^^^^^^^^^^^^^^
# pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x0000020993D45500>) }
```

### Log output

```shell
thread '<unnamed>' panicked at py-polars\src\conversion\chunked_array.rs:66:82:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x000001C435911800>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\test\polars_err_dttm.py", line 11, in <module>
    df["dttm"].to_list()
  File "C:\Users\xxxx\Desktop\test\.venv\Lib\site-packages\polars\series\series.py", line 4196, in to_list
    return self._s.to_list()
           ^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x000001C435911800>) }
```

### Issue description

Well, apparently `to_list()` doesn't work on Windows for datetime columns at least starting from 0.20.19, although I haven't checked version other that .19 and .21. Works on MacOS.

### Expected behavior

returns the list with one value

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by orlp** [comment]
I can't reproduce:

```python
>>> df["dttm"].to_list()
[datetime.datetime(2024, 4, 17, 15, 1, 17, 492103, tzinfo=zoneinfo.ZoneInfo(key='UTC'))]
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
```

**Comment by mishamsk** [comment]
> I can't reproduce on Windows:
> 
> ```python
> >>> df["dttm"].to_list()
> [datetime.datetime(2024, 4, 17, 15, 1, 17, 492103, tzinfo=zoneinfo.ZoneInfo(key='UTC'))]
> >>> pl.show_versions()
> --------Version info---------
> Polars:               0.20.21
> Index type:           UInt32
> Platform:             Windows-10-10.0.19045-SP0
> Python:               3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
> ```

I haven't tried on py12, but I can definitely confirm that this is what happens on our Windows CI server and py3.11. I was just running this when created an issue. I can try on py3.12 or what else can help you troubleshooting this?

**Comment by mishamsk** [comment]
upd. tried on a laptop, no error. somehow this returns empty list on our CI machine 

```sh
 python -c "import zoneinfo;print([z for z in zoneinfo.available_timezones() if 'utc' in z.lower()])"
```

I guess this is Python-Windows issue, so I'll close this issue and try to figure out what's up with timezones. Sorry for false alarm.

P.S. technically, maybe changing the fact that polars relies on python for timezones instead of rust could be considered a feature request... but obviously this is up to you folks. Great work!

**Comment by mishamsk** [comment]
ok. post-mortem in case anyone lands here. The problem was that `tzdata` package wasn't installed, and since https://github.com/pola-rs/polars/pull/4809 apparently, one needs to explicitly add `timezone` extra to bring this dependency alongside Polars, which we apparently missed and haven't used any timezone related features until now

oh, I love Windows. Such an awesome operating system!!

**Comment by baggiponte** [comment]
Hey there, bumped into this just today and it was super helpful. Maybe polars should have [this](https://github.com/pola-rs/polars/blob/8928f7a5ae872c871e595569cfa0028f740d9fce/py-polars/pyproject.toml#L76) as a mandatory dependency by default?

Or maybe we can raise a more meaningful error message when this occurs. The error that was raised (for a colleague of mine) was "called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x0000022DB1A573C0>) }"
