### ISSUE TITLE
DataFrame construction from numpy arrays and  polars.datatypes.Array schema

### ISSUE THREAD

**Issue by dpinol** [pola-rs/polars#15745]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.Array(pl.Int64, 1)})
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-2a88ebee4fc0>", line 1, in <module>
    pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/dataframe/frame.py", line 367, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 137, in dict_to_pydf
    for s in _expand_dict_values(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 362, in _expand_dict_values
    updated_data[name] = pl.Series(
                         ^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/series/series.py", line 311, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 136, in sequence_to_pyseries
    pyseries = _construct_series_with_fallbacks(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 327, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unexpected value while building Series of type Array(Int64, 1)
Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Issue description

It's not possible to create columns of type Array passing using numpy arrays.

#### with polars List
```pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.List(pl.Int64)})```

#### with python array and polars Array
```pl.DataFrame([[[1]]], {"A": pl.Array(pl.Int64, 1)}, orient="row")```

#### not specifying the type
```pl.DataFrame([[np.array([1], dtype=np.int64)]]```
It assigns polars List instead of Array. Why?

#### Row orientation
```pl.DataFrame([[np.array([1], dtype=np.int64)]], {"A": pl.List(pl.Int64)}, orient="row")```
You get nulls (also with pl.Array)

```
┌───────────────┐
│ A             │
│ ---           │
│ array[i64, 1] │
╞═══════════════╡
│ null          │
└───────────────┘
```

### 1 Without schema, imho it should assign polars Array schema

```pl.DataFrame({"A": [np.array([1], dtype=np.int64)]})```

### 2 With schema, it should create the same as passing python 

``` pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)}) == pl.DataFrame({"A": [[1]]}, {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})```

### Installed versions

<details>

```
Polars:               0.20.21
Index type:           UInt32
Platform:             Linux-6.5.0-9-generic-x86_64-with-glibc2.38
Python:               3.11.5 (main, Sep 20 2023, 13:23:03) [GCC 12.2.0]
```

</details>

**Comment by deanm0000** [comment]
The Array or (in arrow terms) FixedSizeList doesn't have all the methods and functions that List does yet (the "yet" is hopefully). It was added later so between the Array dtype not having all the methods that List does and that List was already the default (and changing the default would be breaking), that is the answer to "why" List not Array.

> 1 Without schema, imho it should assign polars Array schema

I, frankly, don't think this makes sense in the context of a 1d np array. A 1d np array should become a column of whatever numeric type not a nested type. For passing 2d np arrays to the DataFrame constructor, it makes more sense, to me at least, to return a df of the same shape.

That said, you can get (nearly) what you want by passing a 2d np array to the Series constructor. For example:
```
pl.Series(np.array([[1,2],[2,3]]), dtype=pl.Array(pl.Int64,2))
```

or even
```
pl.Series(np.array([1]).reshape(1,1), dtype=pl.Array(pl.Int64,1))
```

which can then be the input to a DataFrame constructor
```
pl.DataFrame({
    "A": pl.Series(np.array([1]).reshape(1,1), dtype=pl.Array(pl.Int64,1))
})


As an aside, notice that you don't need to go through `pl.datatypes` they're all in the top level `pl`.

> 2 With schema, it should create the same as passing python

I principle, I disagree with this because the numpy analog to `[[1]]` isn't `[np.array([1])]`, it's `np.array([[1]])`

## Confirmed bug:
In practice, I think if this works

```
pl.Series("A",[np.array([1], dtype=np.int64)]).cast(pl.Array(pl.Int64,1))
```

then so should

```
pl.Series("A",[np.array([1], dtype=np.int64)], dtype=pl.Array(pl.Int64,1))
```
but it doesn't.

I think addressing that would lead to your example working.

**Comment by dpinol** [comment]
Update in polars 1.2.1
This now works
```python
df=pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})
```

But it's not possible to put again the data into a DataFrame through the exported numpy array
```python
pl.DataFrame(df.to_numpy(), {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})

ComputeError: cannot cast 'Object' type
```

unless the input is a python list
```python
pl.DataFrame(df.to_numpy().tolist(), {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})

┌───────────────┐
│ A             │
│ ---           │
│ array[i64, 1] │
╞═══════════════╡
│ [1]           │
└───────────────┘
```

**Comment by dpinol** [comment]
Update in polars 1.2.1
This now works
```python
df=pl.DataFrame({"A": [np.array([1], dtype=np.int64)]}, {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})
```

But it's not possible to put again the data into a DataFrame through the exported numpy array
```python
pl.DataFrame(df.to_numpy(), {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})

ComputeError: cannot cast 'Object' type
```

unless the input is a python list
```python
pl.DataFrame(df.to_numpy().tolist(), {"A": pl.datatypes.Array(pl.datatypes.Int64, 1)})

┌───────────────┐
│ A             │
│ ---           │
│ array[i64, 1] │
╞═══════════════╡
│ [1]           │
└───────────────┘
```

### Series from numpy

This now works
```python
pl.Series("A",[np.array([1], dtype=np.int64)], dtype=pl.Array(pl.Int64,1))
```

but this doesn't
```python
pl.Series("A",[np.array([1], dtype=np.object_)], dtype=pl.Array(pl.Int64,1))
```

It would be nice to have this working, since when I cut an np.object_ numpy by columns, I always get np.object dtype.
