### ISSUE TITLE
Using calamine does not read all values from the Excel

### ISSUE THREAD

**Issue by MarcoStrijker** [pola-rs/polars#15748]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import numpy as np
import polars as pl


data = {
    "Breakfast": [1 for _ in range(350630)],
    "Second breakfast": [np.nan for _ in range(350630 - 1)] + ["Hello world"]
}

df = pl.DataFrame(data)

df.write_excel("Reproduction.xlsx")
schema = {
    "Breakfast": pl.Int8,
    "Second breakfast": pl.Utf8,
}

df = pl.read_excel(
    rf"Reproduction.xlsx",
    engine='calamine',
    schema_overrides=schema
)

# Should only pass when bug is present
assert df["Second breakfast"].to_list()[-1] is None

```

### Log output

```shell
dataframe filtered
```

### Issue description

I may be missing something, but it seems that this is unexpected behavior. When importing Excel via calamine (this behavior does not happen when using `xlsx2csv`) it skips loading the data of certain columns that have many empty leading cells. This is while the length is correct.

In the example the 'Hello world' is not being present in the dataframe, while it should be.

However, when using `read_options={"schema_sample_rows": None}` it works as expected. However, the columns I'm talking about have a schema definition, so no schema has to be inferred. I'm not sure if the bug is in Polars itself.

### Expected behavior

The dataframe should import all the data. 

If I'm missing somehting, sorry. I really appreciate your work on Polars :)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            0.10.4
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.23.5
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.0.7
```

</details>

**Comment by cmdlineluser** [comment]
It seems in this case, fastexcel has its own schema options: http://fastexcel.toucantoco.dev/fastexcel.html#DType

```python
pl.read_excel(
    rf"Reproduction.xlsx",
    engine='calamine',
    read_options={
       "dtypes": {"Second breakfast": "string"}
    },
    schema_overrides={"Breakfast": pl.Int8}
).tail(2)

# shape: (2, 2)
# ┌───────────┬──────────────────┐
# │ Breakfast ┆ Second breakfast │
# │ ---       ┆ ---              │
# │ i8        ┆ str              │
# ╞═══════════╪══════════════════╡
# │ 1         ┆ null             │
# │ 1         ┆ Hello world      │
# └───────────┴──────────────────┘
```

Whereas `schema_overrides` happens after the data is read, and doesn't disable fastexcel's schema inference (which obeys the `schema_sample_rows` limit).

Perhaps something can be improved upon here? 

@alexander-beedie is Mr. Excel - I imagine he can provide some better feedback.

**Comment by MarcoStrijker** [comment]
Ahh, that makes sense. I had the feeling this was not directly Polars but I never really have used Polars before so I was not sure.

While this solution does the trick, I must admit this is a bit confusing. Nevertheless, thanks for the response.

**Comment by alexander-beedie** [comment]
Yup, we should align the inference behaviour between the engine and polars here - I'll have a look today or at the weekend ;)

**Comment by alexander-beedie** [comment]
Done; added two new capabilities to handle it - internally any Polars "schema_overrides" entries will now be translated to the matching `fastexcel` dtypes (where possible) and given straight to the engine. Also exposed "infer_schema_length" at the top level of the method for use with all supported engines 👌
