### ISSUE TITLE
Add a `df.to_string(max_number_of_visible_rows)` function

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#15758]
### Description

I'm aware that setting the maximum number of visible rows in a dataframe is possible via the configuration options in Python.

In Rust, it's unclear how you can achieve the same effect.

For both languages, it would be super awesome if there was a way to set the number at runtime. Sometimes, for lots of log messages with embedded dataframes, the default 5-10 rows makes a lot of sense. Sometimes though, the data I want to log is in a very tall dataframe (say, 20 rows); it would be awesome if I could easily convert that to a string when required.

**Comment by ritchie46** [comment]
`df.head(20).to_string()`

**Comment by alexander-beedie** [comment]
Or even just `df[:20].to_string()` :)

@DeflateAwning: can already achieve this cleanly - doesn't really seem to be any need (or subsequent advantage) for moving the "head" (or "slice") call inside `to_string`. I don't think we do that anywhere else, so makes sense to keep things consistent/composable here 🤔

**Comment by DeflateAwning** [comment]
Hmm I'm not sure we're talking about the same thing.

In Python:

```python
In [1]: df = pl.DataFrame([{'id': i} for i in range(30)])

In [2]: df
Out[2]: 
shape: (30, 1)
┌─────┐
│ id  │
│ --- │
│ i64 │
╞═════╡
│ 0   │
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ …   │
│ 25  │
│ 26  │
│ 27  │
│ 28  │
│ 29  │
└─────┘

# Snly 10 rows are visible. I want all 20 rows to be visible.
print(str(df.head(20)))
shape: (20, 1)
┌─────┐
│ id  │
│ --- │
│ i64 │
╞═════╡
│ 0   │
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ …   │
│ 15  │
│ 16  │
│ 17  │
│ 18  │
│ 19  │
└─────┘
```

In Rust, I assume the same thing happens.

I see now that [the config page](https://docs.pola.rs/py-polars/html/reference/api/polars.Config.set_tbl_rows.html) has this example:

```python
with pl.Config(tbl_rows=2):
    print(df)
```

This is what I was looking for in Python.

In Rust however, I don't see an equivalent `set_tbl_rows`: [search](https://docs.rs/polars/latest/polars/?search=set_tbl_rows). Any advice?

**Comment by cmdlineluser** [comment]
It looks like it sets an env variable:

https://github.com/pola-rs/polars/blob/0c37eadab7963e5d27f12ac6fb0e2ccc2a963f4d/py-polars/polars/config.py#L1186

Which I guess is done with `std::env` in Rust?

**Comment by DeflateAwning** [comment]
This seems like a bizarre way to communicate what, in my opinion, should be a simple argument.

Imagine if `.dt.strftime(...)` communicated the date format via an environment variable.

**Comment by cmdlineluser** [comment]
It's very possible I'm missing something here - this was just what I found when trying to figure out how it currently works in `py-polars`

I'm guessing that eventually the Rust API will have a `pl.Config` equivalent?
