### ISSUE TITLE
BUG: LazyFrame neglects head(0) if a sort follows

### ISSUE THREAD

**Issue by lorentzenchr** [pola-rs/polars#15779]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I'm very sorry that I did not arrive at a small reproducible example, I really tried.
See https://github.com/lorentzenchr/model-diagnostics/blob/615b131892c6ddf81b0fbdf331daf5beb8601843/src/model_diagnostics/calibration/tests/test_identification.py#L502 for a test that fails with `model-diagnostics==1.1.0` and `polars>=0.20.20` (also tested with 0.20.21).
The lines causing this are:
https://github.com/lorentzenchr/model-diagnostics/blob/615b131892c6ddf81b0fbdf331daf5beb8601843/src/model_diagnostics/calibration/identification.py#L468-L469

### Issue description

A `df.head(0)` should always produce a dataframe with zero rows and some columns. As of polars 0.20.20, a `LazyFrame` neglects the `head(0)` if followed by `sort(..)`, at least in certain (harder to reproduce) circumstances.

The fix for model-diagnostics was https://github.com/lorentzenchr/model-diagnostics/pull/148.

### Expected behavior

Return a dataframe with 0 rows.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             macOS-14.4.1-x86_64-i386-64bit
Python:               3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Minimal repro:

```python
(pl.LazyFrame({"foo": [1, 2]})
   .sort("foo")
   .head(0)
   .sort("foo")
   .collect()
)

# shape: (2, 1)
# ┌─────┐
# │ foo │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# └─────┘
```

```python
(pl.LazyFrame({"foo": [1, 2]})
   .sort("foo")
   .head(0)
   .sort("foo")
   .collect(slice_pushdown=False)
)

# shape: (0, 1)
# ┌─────┐
# │ foo │
# │ --- │
# │ i64 │
# ╞═════╡
# └─────┘
```

**Comment by lorentzenchr** [comment]
@ cmdlineluser Thank you so much.

**Comment by orlp** [comment]
Thanks for the reproduction.
