### ISSUE TITLE
`read_csv` change `decimal_float` parameter to `decimal_separator`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#15788]
### Description

Love to see that `read_csv` will be able to parse floats with comma as decimal separator soon!! ❤️ #15774

However, I think the new parameter `decimal_float` is really confusing and should be renamed to
- `decimal_separator` or
- `decimal_point`

with only 2 options `.` (default) and `,`

We have both Float and Decimal as data types in polars and then calling the parameter `decimal_float` is very unfortunate and just not very clear to the user.

**Comment by mcrumiller** [comment]
Agreed, it is called a [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator).

**Comment by ritchie46** [comment]
Seems fine to me. :+1:
