### ISSUE TITLE
`first()` and `last()` functions functinallity is not trivial (correct?)

### ISSUE THREAD

**Issue by barak1412** [pola-rs/polars#15824]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.DataFrame({"x": []}, schema={"x": pl.Int64}).select(pl.col.x.first())
shape: (1, 1)
┌──────┐
│ x    │
│ ---  │
│ i64  │
╞══════╡
│ null │
└──────┘
```

### Issue description

As stated [here](https://github.com/pola-rs/polars/issues/15727), it looks like `first()` and `last()` functions return non-empty dataframe (with a null row), on an empty dataframes.

### Expected behavior

Maybe it is intended, but it looks like it is something most of the users will not expect to get.
May you confirm it was well-thought and intended?

Thanks.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.0
connectorx:           0.3.3a1
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.5.1
nest_asyncio:         1.5.1
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              13.0.0
pydantic:             1.8.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.32
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is correct. A function returns a value. In this case there is no first value, so the result is `None`.

If we sum an empty set, the result is `0`.

```python
>>> import polars as pl
>>> pl.DataFrame({"x": []}, schema={"x": pl.Int64}).select(pl.col.x.sum())
shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 0   │
└─────┘

```

All expected.
