### ISSUE TITLE
Change default of `Config.set_fmt_str_lengths` to be more reasonable (also little display "bug")

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#15839]
### Description

In my experience the default of 14(??) seems to be super low and not very usable in almost all real life use-cases.

I propose to change this to a much bigger value like 50 (see pandas example).

# Polars

- only showing 14(?) characters
- also second line the `…` are "incorrect"! The text is finished but it is showing the `…` ⚠️ ⚠️ 
```python
pl.DataFrame(
    {
        "txt": [
            "123456789_123",
            "123456789_1234",
            "123456789_12345",
        ],
    },
)
```

![image](https://github.com/pola-rs/polars/assets/25177421/fcf2c529-af7b-46d2-9afe-b2d1481215a4)

# Pandas

- much more reasonable 50 characters by default
- typical pandas stuff: when 50 is reached trucate to 46 chars 🤣 🤣 
```
pd.DataFrame(
    {
        "txt": [
            "123456789_123456789_123456789_123456789_123456789",
            "123456789_123456789_123456789_123456789_123456789_",
        ]
    }
)
```

![image](https://github.com/pola-rs/polars/assets/25177421/5b4f2486-1388-4ba0-9c8e-8627468525e3)

**Comment by lyngc** [comment]
I find 50 to be a bit much, but 30 to be a good spot.

**Comment by deanm0000** [comment]
You can set this for yourself by setting an env variable called POLARS_FMT_STR_LEN to be whatever you want it to be.

@stinodego This feels enough like a not planned that I'm closing but just in case I'm overstepping I'm tagging you so you can reopen.

**Comment by cmdlineluser** [comment]
@deanm0000 Julian has had other defaults changed previously e.g. #14515

In this case it seems like it's `15` for Series and `32` for DataFrame?

Having them both be the same value seems reasonable?

https://github.com/pola-rs/polars/blob/9b0503a6559ffdb952b27a22b2c2eebb58ea9553/crates/polars-core/src/fmt.rs#L107

https://github.com/pola-rs/polars/blob/9b0503a6559ffdb952b27a22b2c2eebb58ea9553/crates/polars-core/src/fmt.rs#L505

```python
pl.Series(
    "txt", [
        "Play it, Sam. Play 'As Time Goes By'.",
        "This is the beginning of a beautiful friendship.",
    ]
)

# Series: 'txt' [str]
# [
# 	"Play it, Sam. …
# 	"This is the be…
# ]
```

```python
pl.DataFrame({
    "txt": [
        "Play it, Sam. Play 'As Time Goes By'.",
        "This is the beginning of a beautiful friendship.",
    ]
})

# shape: (2, 1)
# ┌───────────────────────────────────┐
# │ txt                               │
# │ ---                               │
# │ str                               │
# ╞═══════════════════════════════════╡
# │ Play it, Sam. Play 'As Time Goes… │
# │ This is the beginning of a beaut… │
# └───────────────────────────────────┘
```

The trailing `…` also appears to be an off-by-1 bug.

```python
with pl.Config(fmt_str_lengths=4): 
    pl.Series(["AB"])
    # shape: (1,)
    # Series: '' [str]
    # [
    #     "AB"
    # ]

    pl.Series(["ABC"])
    # shape: (1,)
    # Series: '' [str]
    # [
    # 	"ABC…
    # ]
    # 
```

**Comment by stinodego** [comment]
I'll re-open this as I think there's a point here. I've also ran into this annoyance, same with the number of list items displayed. This is also tunable but a bit inconvenient.
