### ISSUE TITLE
in pl.read_csv: storage_options is modified inplace (an extra param called "encoding" is added inplace)

### ISSUE THREAD

**Issue by giuliaviolatto** [pola-rs/polars#15849]
https://github.com/pola-rs/polars/blob/c0b317904196151400fed81c1eccfc1f3a40f411/py-polars/polars/io/_utils.py#L236C13-L236C51

**Comment by giuliaviolatto** [comment]
In pl.read_csv: storage_options is modified inplace (by adding an extra param "encoding"). Instead: use a deepcopy of storage_option.

Consequence: when importing a csv, an extra param called "encoding" will be added to storage_option (this is not intended behavior),  
and then you try to read a parquet, the error "ComputeError: unknown configuration key: encoding" will be generated, as encoding is not an accepted param for storage_option.

**Comment by alexander-beedie** [comment]
Thanks for the bug report :)

**Comment by giuliaviolatto** [comment]
thanks for solving it!
