### ISSUE TITLE
Don't panic for "failed to determine supertype of cat and bool"

### ISSUE THREAD

**Issue by jshinonome** [pola-rs/polars#15844]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Fast to reproduce using python

```python
import polars as pl
data = pl.DataFrame(
    [
        pl.Series("date", ["2000-01-02", "2000-01-02"]).cast(pl.Date),
        pl.Series("col1", ["a", "b"], dtype=pl.Categorical),
    ]
)
# panic
data.filter(pl.col("col1")==True)
# not panic
data.filter(pl.col("col1")==1)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/comparison.rs:109:9:
cannot coerce datatypes: ComputeError(ErrString("failed to determine supertype of cat and bool"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

Thought this issue mentioned the same error message, but I just would like polars to throw errors instead of panic.
https://github.com/pola-rs/polars/issues/12231#issue-1976908515

### Expected behavior

ComputeError: cannot compare string with bool data

### Installed versions

<details>

rust: 0.39.2
python: polars 0.20.22

</details>

**Comment by daviskirk** [comment]
The same goes for datetimes:

```python
df = pl.DataFrame({"a": pl.Series(["a", "b"], dtype=pl.Categorical("lexical")).cast(pl.Datetime), "b": pl.Series(["a", "b"], dtype=pl.Categorical)})
a.select(pl.col("a") == pl.col("b"))
```

```
PanicException: cannot coerce datatypes: ComputeError(ErrString("failed to determine supertype of datetime[μs] and cat"))
```

**Comment by jshinonome** [comment]
It would be great to throw an error for all "failed to determine supertype of {} and {}", not panic.
Hit the following panic today,
```
ComputeError(ErrString("failed to determine supertype of i64 and cat"))
```

**Comment by c-peters** [comment]
I added a check which requires the type to be string / enum or categorical otherwise the comparison will return a `ComputeError`

**Comment by jshinonome** [comment]
Thank you so much!!
