### ISSUE TITLE
to_pandas not providing expected type for dates

### ISSUE THREAD

**Issue by yuuuxt** [pola-rs/polars#15856]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import io
import polars as pl

pl_df_save_path = "<a_path_for_saving_parquet_file>"

test_tsv_str = """the_date	the_time
20240101	100000
20240201	110000
20240301	120000
20240401	130000
"""
pl_df = (
    pl.read_csv(io.StringIO(test_tsv_str), separator="\t")
    .with_columns([
        pl.col("the_date").cast(str).str.to_date("%Y%m%d"),
        pl.col("the_time").cast(str).str.to_time("%H%M%s"),
    ])
)
pl_df.write_parquet(pl_df_save_path)

# expecting this
pd_df_from_pq = pd.read_parquet(pl_df_save_path)
print(pd_df_from_pq.applymap(type))

# not expecting this
pd_df_from_pl = pl_df.to_pandas()
print(pd_df_from_pl.applymap(type))

# additional step to fix
pd_df_from_pl_fixed = pd_df_from_pl.assign(the_date = lambda df: df.the_date.dt.date)
print(pd_df_from_pl_fixed.applymap(type))
```

### Issue description

Having a date column in `polars DataFrame` (and the saved parquet file), the date column doesn't persist when turning it into a `pandas DataFrame`.

### Expected behavior

Keep the date column of type date in pandas DataFrame.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.22
Index type:           UInt32
Platform:             Windows-10-10.0.17763-SP0
Python:               3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2021.10.1
gevent:               21.8.0
hvplot:               <not installed>
matplotlib:           3.4.3
nest_asyncio:         1.5.6
numpy:                1.24.2
openpyxl:             3.0.9
pandas:               1.5.3
pyarrow:              12.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.22
xlsx2csv:             <not installed>
xlsxwriter:           3.0.1
```

</details>

**Comment by stinodego** [comment]
Looks like pandas turns dates from Date columns in parquet files into  `pandas.Timestamp` objects. We supply `datetime.date` objects.

I don't really know if this is a bug. Even if it is, we rely on `pyarrow` for this conversion, so the logic is implemented there:

```python
from datetime import date

import pyarrow as pa

arr = pa.array([date(2022, 1, 1), date(2023, 12, 31)])

s = arr.to_pandas()
print(s.map(type))
```
```
0    <class 'datetime.date'>
1    <class 'datetime.date'>
dtype: object
```

If you want to change this behavior, I recommend you open an issue in the Arrow repo:
https://github.com/apache/arrow/tree/main

**Comment by stinodego** [comment]
Ah, you're right. I mixed up the print statements.

We set `date_as_object=False` by default. I'm not exactly certain why, but it makes sense. Timestamp objects are more useful in a pandas context than date objects.

To get the behavior you're looking for, use `date_as_object=True`:

```python
from datetime import date
import polars as pl

df = pl.DataFrame({"date": [date(2022, 1, 1), date(2023, 12, 31)]})
result = df.to_pandas(date_as_object=True)
print(result.map(type))
```

**Comment by yuuuxt** [comment]
I would argue if I'm deliberately using `str.to_date` instead of `str.to_datetime`, I explicit want to get a date object, otherwise `str.to_datetime` is the default choice whose name directly matches `pd.to_datetime` in pandas, so I prefer `date_as_object=True` as default.

Anyway I can pass `True` there. Thanks!

**Comment by stinodego** [comment]
@MarcoGorelli do you think this behavior should change? Do you perhaps know why we explicitly change the default from PyArrow?

I don't have a very strong opinion myself. You could argue for either way.

**Comment by yuuuxt** [comment]
I just checked #6900, where `date_as_object=True` is described as not expected. 

As the code below shows, if pandas keeps date objects as they are, not automatically doing the transformation, polars having the different default feels inconsistent / inconvenient for me.

```python
import datetime
import pandas as pd

# it is date object, not timestamp
pd.DataFrame([datetime.date(2012,1,1), datetime.date(2013,1,1)]).applymap(type)
```

**Comment by stinodego** [comment]
Right. I seem to remember this used to result in a `datetime64` column, but now it just creates an object column. Something has changed somehwere :thinking:
