### ISSUE TITLE
When reading a csv file: storage_options is modified inplace (an extra param called "encoding" is added inplace)

### ISSUE THREAD

**Issue by giuliaviolatto** [pola-rs/polars#15850]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

storage_options = {
    "client_id": "xxx",
    "client_secret": "xxx",
    "tenant_id": "xxx",
}
path = "abfs://xxx@xxxx.dfs.core.windows.net/"

df = pl.read_csv(
    path,
    storage_options=storage_options,
)

print(storage_options)
```

### Log output

```shell
storage_options = {
    "client_id": "xxx",
    "client_secret": "xxx",
    "tenant_id": "xxx",
    "encoding": "utf-8",
}
```

### Issue description

When reading a csv file: storage_options is modified inplace (by adding an extra param "encoding"). Instead: use a deepcopy of storage_option.

Problem originates from code line: https://github.com/pola-rs/polars/blob/c0b317904196151400fed81c1eccfc1f3a40f411/py-polars/polars/io/_utils.py#L236C13-L236C51

Consequence: when importing a csv from a Cloud Storage, an extra param called "encoding" will be added to storage_option (this is not intended behavior),
and then if you try to read a parquet, the error "ComputeError: unknown configuration key: encoding" will be generated, as "encoding" is not an accepted param for storage_option.

Bug is present in version 0.20.10 but also in latest 0.20.22.

### Expected behavior

storage_options = {
    "client_id": "xxx",
    "client_secret": "xxx",
    "tenant_id": "xxx",
}

### Installed versions

<details>

```
0.20.10
```

</details>

**Comment by alexander-beedie** [comment]
(Also closed by https://github.com/pola-rs/polars/pull/15859)
