### ISSUE TITLE
Asymmetry between `is_nan` and `is_not_nan`

### ISSUE THREAD

**Issue by wence-** [pola-rs/polars#15862]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

ldf = pl.DataFrame({"a": [1.0, None, float("nan")]}).lazy()
ldf.select(pl.col("a").is_nan()).collect()
# [False, NULL, True]
ldf.select(pl.col("a").is_not_nan()).collect()
# [True, True, False]
```

### Log output

```shell
run ProjectionExec
run ProjectionExec
```

### Issue description

Where `is_nan` maintains missing values, `is_not_nan` does not: a `null` value returns `true` to the question `is_not_nan`.

This breaks the identity one might expect that `col.is_nan().not_() == col.is_not_nan()`. Is this asymmetry deliberate?

### Expected behavior

I was expecting `is_not_nan` to be the negation of `is_nan`, preserving null values.

I note that this appears to have been a deliberate change in https://github.com/pola-rs/polars/pull/4119 as a result of fixing #4101.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  0.11.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.17.1
fastexcel:            0.10.4
fsspec:               2023.12.2
gevent:               24.2.1
hvplot:               0.9.2
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             2.7.1
pyiceberg:            0.6.0
pyxlsb:               1.0.10
sqlalchemy:           2.0.29
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0

```

</details>

**Comment by ritchie46** [comment]
I think that's by accident. Should be symmetric indeed.

**Comment by wence-** [comment]
The natural change which just preserves the validity mask unfortunately has follow-on consequences. For example, it changes the behaviour of `fill_nan`. The reason is that `pl.when` treats `null` as `False` in a `pl.when().then().otherwise()` expression and `col.fill_nan(value)` is implemented as `pl.when(col.is_not_nan()).then(col).otherwise(value)`. So I guess to fix this one needs to decide on the semantics of `when` in the presence of nulls.

**Comment by ritchie46** [comment]
IMO the user must adapt the predicate for that.

**Comment by wence-** [comment]
The user in this case is `fill_nan`. I'll try pool at the loose thread in a few days and see how much of the jumper is left...

**Comment by mcrumiller** [comment]
> IMO the user must adapt the predicate for that.

Meaning that `when` will pass-through null values now? Will `filter` as well?

**Comment by ritchie46** [comment]
> Meaning that `when` will pass-through null values now? Will `filter` as well?

No, `when` doesn't change. You must ensure your predicate (the mask you pass) reflects the null behavior you'd like to see.
