### ISSUE TITLE
Pyiceberg Read S3

### ISSUE THREAD

**Issue by dhruvils414** [pola-rs/polars#15863]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
storage_options = {
    "region": "us-east-2",
    "aws_access_key_id": current_credentials.access_key,
    "aws_secret_access_key": current_credentials.secret_key,
}

table_path = "s3//dhruvil/test"

pl.scan_iceberg(
    table_path, storage_options=storage_options
).collect()  

### Log output

```shell
ll In[37], line 1
----> 1 pl.scan_iceberg(
      2     table_path, storage_options=storage_options
      3 ).collect()  

File /usr/local/lib/python3.11/site-packages/polars/io/iceberg.py:134, in scan_iceberg(source, storage_options)
    131 from pyiceberg.table import StaticTable
    133 if isinstance(source, str):
--> 134     source = StaticTable.from_metadata(
    135         metadata_location=source, properties=storage_options or {}
    136     )
    138 func = partial(_scan_pyarrow_dataset_impl, source)
    139 arrow_schema = schema_to_pyarrow(source.schema())

File /usr/local/lib/python3.11/site-packages/pyiceberg/table/__init__.py:1101, in StaticTable.from_metadata(cls, metadata_location, properties)
   1097 file = io.new_input(metadata_location)
   1099 from pyiceberg.serializers import FromInputFile
-> 1101 metadata = FromInputFile.table_metadata(file)
   1103 from pyiceberg.catalog.noop import NoopCatalog
   1105 return cls(
   1106     identifier=("static-table", metadata_location),
   1107     metadata_location=metadata_location,
   (...)
   1110     catalog=NoopCatalog("static-table"),
   1111 )

File /usr/local/lib/python3.11/site-packages/pyiceberg/serializers.py:112, in FromInputFile.table_metadata(input_file, encoding)
    100 @staticmethod
    101 def table_metadata(input_file: InputFile, encoding: str = UTF8) -> TableMetadata:
    102     """Create a TableMetadata instance from an input file.
    103 
    104     Args:
   (...)
    110 
    111     """
--> 112     with input_file.open() as input_stream:
    113         return FromByteStream.table_metadata(
    114             byte_stream=input_stream, encoding=encoding, compression=Compressor.get_compressor(location=input_file.location)
    115         )

File /usr/local/lib/python3.11/site-packages/pyiceberg/io/pyarrow.py:263, in PyArrowFile.open(self, seekable)
    261 try:
    262     if seekable:
--> 263         input_file = self._filesystem.open_input_file(self._path)
    264     else:
    265         input_file = self._filesystem.open_input_stream(self._path, buffer_size=self._buffer_size)

File /usr/local/lib/python3.11/site-packages/pyarrow/_fs.pyx:780, in pyarrow._fs.FileSystem.open_input_file()

File /usr/local/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File /usr/local/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()

FileNotFoundError: [Errno 2] Failed to open local file '/app/s3/dhruvil/test'. Detail: [errno 2] No such file or directory
```

### Issue description

Try to read local file instate of S3 

### Expected behavior

Read iceberg table in S3 

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Linux-5.10.213-201.855.amzn2.x86_64-x86_64-with-glibc2.36
Python:               3.11.9 (main, Apr 10 2024, 14:54:51) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.0
pyiceberg:            0.6.0
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

**Comment by ion-elgreco** [comment]
Your protocol prefix is incorrect, it should be S3://, now it's recognized as local path 

I think this can be closed

**Comment by alexander-beedie** [comment]
@ion-elgreco: thanks :)

@dhruvils414- if you think the issue should still be considered open, can you comment with a clarification/example? Thanks!
