### ISSUE TITLE
Improve Error Message for `ColumnNotFoundError`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#15893]
### Description

While the error "type" is very nice, the message is very bad.

## Example
```python
pl.DataFrame().select('a')
```

### Message
```
ColumnNotFoundError: 'select' failed
The reason: a:                                         # ????

This error occurred with the following context stack:  # ??? there is nothing else here. This is the end ?
```

- weird wording "The reason"; why not just "Reason"
- Reson text is also weird
- also there is no context stack. Feels wrong to have this message but nothing here

##

## "Good" Example
`read_csv` on the other hand has very nice error message like
```
ColumnNotFoundError: unable to find column "a"; valid columns: ["x", "y"]
```

**Comment by cmdlineluser** [comment]
On main it produces just `ColumnNotFoundError: a`

It was changed earlier today: https://github.com/pola-rs/polars/issues/15880
