### ISSUE TITLE
Since v0.20: `u32` to power of negative int (`i32`) fails with conversion error

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars#15897]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
data = pl.DataFrame({"u32_series": [1,2,3]})
data.select([pl.col("u32_series").pow(-1)])
```

### Log output

With version >= 0.20:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7701, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1708, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: conversion from `i32` to `u32` failed in column 'literal' for 1 out of 1 values: [-1]
```

With prior versions, e.g. 0.19.9:

```
shape: (3, 1)
┌────────────┐
│ u32_series │
│ ---        │
│ f64        │
╞════════════╡
│ 1.0        │
│ 0.5        │
│ 0.333333   │
└────────────┘
```

### Issue description

Undocumented breaking change was introduced in 0.20.0 with PR https://github.com/pola-rs/polars/pull/10446 which implemented issue #9051

It seems that the issue #9051 explicitly _wanted_ to introduce this breaking change but it got forgotten to be documented? The PR didn't mention at all that it would raise for negative integer.

So there's the following question:
1. Is the raising for negative integer power really necessary? Was it intentional or did it slip through?
2. If it's intentional, this needs to be clearly documented, it isn't right now.
3. If it's unintentional, it's a bug and should be fixed

### Expected behavior

Breaking change should have been documented. Or it's a bug.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              <not installed>
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report - I think this is a bug, re-reading the PR it seems that the intention was to preserve the base dtype only when raising to unsigned integers

**Comment by MarcoGorelli** [comment]
Barring the cryptic error message, this matches the pyarrow behaviour:
```python
In [12]: import pyarrow as pa

In [13]: import pyarrow.compute as pc

In [14]: pc.power(pa.array([1,2,3]), 2)
Out[14]:
<pyarrow.lib.Int64Array object at 0x7f2134c3e800>
[
  1,
  4,
  9
]

In [15]: pc.power(pa.array([1,2,3]), -1)
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
Cell In[15], line 1
----> 1 pc.power(pa.array([1,2,3]), -1)

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/compute.py:246, in _make_generic_wrapper.<locals>.wrapper(memory_pool, *args)
    244 if args and isinstance(args[0], Expression):
    245     return Expression._call(func_name, list(args))
--> 246 return func.call(args, None, memory_pool)

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/_compute.pyx:385, in pyarrow._compute.Function.call()

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()

ArrowInvalid: integers to negative integer powers are not allowed
```

If the goal is to have:
- predictable (not value-dependent) schema
- output dtype which does the right thing most of the time

then I think this is right - raising an integer to an integer preserves the integer dtype, and raises if the integer is negative

Agree that the error message and docs are insufficient though, so thank you for reporting this - will address

**Comment by MarcoGorelli** [comment]
> Undocumented breaking change was introduced in 0.20.0 with PR https://github.com/pola-rs/polars/pull/10446

I think it was this one actually: https://github.com/pola-rs/polars/pull/15506/files. I support the change (this one @CanglongCl !), it just needs a better error message, something like
```
Cannot raise integer to negative power - please cast exponent to float
```
plus some note about this in the docs https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.pow.html

@CanglongCl do you fancy making a PR to raise an informative error message + document the return dtype?

**Comment by deanm0000** [comment]
> Cannot raise integer to negative power - please cast exponent to float

Cast the base to float, not the exponent

**Comment by drhagen** [comment]
I completely agree with the original goal of having type stable operators (type of output depends only on type of input, not value of input). But I am not sure why preserving the base type is also a goal. Integer division is not closed on the integers, so Polars returns a `f64` for `u64 / i64`. Division does not preserve the base type. Similarly, integers raised to integers is not closed on the integers, so wouldn't it make sense for Polars to return an `f64` for `u64 ** i64` or `i64 ** i64`?

**Comment by MarcoGorelli** [comment]
> wouldn't it make sense for Polars to return an f64 for u64 ** i64 or i64 ** i64?

That's what it used to do, but people pointed out that int to int should preserve the dtype

I think the current behaviour is fine, the error message just needs improving

**Comment by drhagen** [comment]
> people pointed out that int to int should preserve the dtype

Do people feel the same way about division, which also does not preserve the dtype? Polars could raise an exception when trying to do `4 / 3` rather than returning `f64`.

**Comment by deanm0000** [comment]
> Similarly, integers raised to integers is not closed on the integers

Do you mean b/c f64 can be bigger than int64? Mathematically int ** int is int so I don't think I'd want int**int to return float just b/c the result _might_ be too big

**Comment by MarcoGorelli** [comment]
> Specifically, it is not true if the exponent is a negative intege

yup, and that raises. it needs a better error message, but I agree with raising

it's also consistent with pyarrow:
```python

In [19]: import pyarrow as pa

In [20]: import pyarrow.compute as pc

In [21]: pc.power(pa.array([1,2,3]), -1)
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
Cell In[21], line 1
----> 1 pc.power(pa.array([1,2,3]), -1)

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/compute.py:246, in _make_generic_wrapper.<locals>.wrapper(memory_pool, *args)
    244 if args and isinstance(args[0], Expression):
    245     return Expression._call(func_name, list(args))
--> 246 return func.call(args, None, memory_pool)

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/_compute.pyx:385, in pyarrow._compute.Function.call()

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File ~/scratch/.venv/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()

ArrowInvalid: integers to negative integer powers are not allowed
```

**Comment by deanm0000** [comment]
> Not with what I think of as an int, though this belief may be the source of the current behavior. Specifically, it is not true if the exponent is a negative integer. e.g 2 ** -4 == 0.0625.

good point, my bad.

**Comment by drhagen** [comment]
> it's also consistent with pyarrow

PyArrow also preserves integers during division, which Polars does not do:

```
>>> import pyarrow.compute as pc
>>> pc.divide(pa.array([1,2,3]), 2)
<pyarrow.lib.Int64Array object at 0x7f7d46861a80>
[
  0,
  1,
  1
]
```

**Comment by corneliusroemer** [comment]
I'm just an outsider so excuse the ignorance:
Is the goal to behave exactly like pyarrow? is this documented somewhere? If that's the goal, it should be applied consistently, and as @drhagen mentions, for example also for integer division.

Raising to a negative integer power is simply syntactic sugar for 1 over the number raised to a positive integer. That's the mathematical definition.

Hence to be consistent you should have identical behavior for the two operations. Otherwise it's erratic.

Now maybe pyarrow does erratic things and you want to be compliant. Sure. But then you should stick with it in all cases, not just when it feels right. Because otherwise what's the point of doing it like Pyarrow if one can't rely on it?

It seems the PR that changed this behavior was well intentioned but didn't think things through from a mathematical perspective. You don't want to force people to learn arbitrary exceptions. There should be simple rules for which type of conversions are allowed, which approximate in a lossy way and which raise.

There should ideally be consensus across the whole of polars regarding this, it shouldn't be based on a side effect of a PR that slipped it through under the radar.

Options:

1. Never convert implicitly unless explicitly requested, i.e. implement closure (in a mathematical sense: an operation on two elements of the set give you back another element of the set). This means that integer division is either forbidden, or it returns just the quotient, or a tuple of quotient and remainder.

This decision is tightly coupled to what happens to signed integer powers as the negative sign is nothing but integer division.

2. How to treat operations involving different types? Upcast to the inclusive/broader type implicitly? Or raise unless one explicitly casts?

3. How to treat complex numbers if at all?

**Comment by MarcoGorelli** [comment]
Agree on the mathematical definition 👍 

To avoid value-dependent behaviour, there's two options here:
1) int ** int => float, which is always supported even if the power is negative
2) int ** int => int, and raise if the power is negative

Outside of pure maths, we need to contend with floating point imprecision, which gets bad for large numbers.
And that's the major downside of option 1. And if people are working with powers, it seems likely that they're dealing with large-ish numbers

If this means raising for `**-1` (with a good error message), then OK, personally I think that's fine. The "good error message" part is still lacking though, will look into addressing it
