### ISSUE TITLE
ComputeError on Date parsing with `strict=False`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#15905]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
💥 
pl.DataFrame({"x": ["31.01.2024"]}).with_columns(
    date=pl.col("x").str.to_date(strict=False)
)

💥 
pl.DataFrame({"x": ["31.01.2024"]}).with_columns(
    date=pl.col("x").str.strptime(pl.Date, strict=False)
)

✅ 
pl.DataFrame({"x": ["31.01.2024"]}).with_columns(
    date=pl.col("x").str.strptime(pl.Date, format="", strict=False)
)
```

### Log output

```shell
ComputeError: could not find an appropriate format to parse dates, please define a format
```

### Issue description

Parsing a Date without specifying a format (infer date format) crashes when no appropriate format is found.

### Expected behavior

if `strict=False` I expect `null` values no matter what happens.
There could be a warning if no format is found.

Also I think the format `DD.MM.YYYY` should be added to the inference. This format is very common in the EU (https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe)

> Official documents still tend to use DD.MM.YYYY

### Installed versions

<details>

```
0.20.22
```

</details>

**Comment by stinodego** [comment]
I don't know. If a format cannot be inferred, the whole operation doesn't make any sense.

> Also I think the format DD.MM.YYYY should be added to the inference. This format is very common in the EU

That does sound like a good idea.

**Comment by JulianCologne** [comment]
yeah, you are right, this is tricky.

The only option I see is adding another parameter like `on_no_format_detected` with `raise/warn/ignore`.

Feel free to close if this is not planned.

**Comment by stinodego** [comment]
I'll go ahead and close this as not planned. Thanks for the suggestion!
