### ISSUE TITLE
Add `dd.mm.yyyy` to date inference / parsing

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#15949]
### Description

the `dd.mm.yyyy` is a very common date format which currently is not infered by polars.

https://en.wikipedia.org/wiki/List_of_date_formats_by_country

just seaching wiki for different separators I found
- `dd/mm/yyyy`: 36x ✅ 
- `dd.mm.yyyy`: 26x --> Missing currently 😞 
- `dd-mm-yyyy`: 7x ✅ 

https://github.com/pola-rs/polars/blob/95cbf3490f8786a0dc522731270a1da198ad8715/crates/polars-time/src/chunkedarray/string/patterns.rs#L4-L7

---

whoopsi just saw this is a duplicate of #14990

**Comment by alexander-beedie** [comment]
Yup; closing in favour of the earlier issue ;)
