### ISSUE TITLE
DataFrame creation with List-type columns

### ISSUE THREAD

**Issue by nzqo** [pola-rs/polars#15954]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
test = pl.DataFrame(
    {"a" : [0,1]},
    schema = {"a":  pl.List(pl.UInt8)}
)
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/nzqo/test.py", line 2, in <module>
    test = pl.DataFrame(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 367, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 139, in dict_to_pydf
    for s in _expand_dict_values(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 364, in _expand_dict_values
    updated_data[name] = pl.Series(
                         ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/series/series.py", line 312, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 269, in sequence_to_pyseries
    pyseries_list = [
                    ^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 272, in <listcomp>
    else sequence_to_pyseries(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 93, in sequence_to_pyseries
    if len(values) == 0 and dtype is None:
       ^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```

### Issue description

Creation from a list seems to try to unwrap the values into different columns even though the schema specifies that column types are expected to be a list. With for example integers, I do not need to wrap the value in the dictionary passed to the constructor into a List, but to make this example work I need to.

Is this expected behavior?

### Expected behavior

I would expect a single-row dataframe with the value `[0, 1]` to be created.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         1.5.8
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
You do need to supply the right data here, or it's very ambiguous; just make sure each element in the incoming data Series really is a list, not an integer 👌 
```python
import polars as pl
test = pl.DataFrame(
    {"a" : [[0,1]]},
    schema = {"a":  pl.List(pl.UInt8)}
)
```

**Comment by nzqo** [comment]
> You do need to supply the right data here, or it's quite problematic (we wouldn't raise an error on genuinely incorrect/mistaken dtype declarations, it would require a reshape of the incoming data, etc).
> 
> Just make sure each element in the given data really _is_ a list, not an integer 👌
> 
> ```python
> test = pl.DataFrame(
>     {"a" : [[0,1]]},  # << fix given data
>     schema = {"a":  pl.List(pl.UInt8)}
> )
> # shape: (1, 1)
> # ┌──────────┐
> # │ a        │
> # │ ---      │
> # │ list[u8] │
> # ╞══════════╡
> # │ [0, 1]   │
> # └──────────┘
> ```

I know this works (as I mentioned), but I find it a bit confusing since that seems to be exactly what I am supplying the schema for. I am not sure what is ambiguous in that context, since it works for all other dtypes, e.g.

```
test = pl.DataFrame({"a": 5}, schema = {"a": pl.UInt8})
```

Judging from the documentation though, it seems like that latter case is actually the unexpected one, since it explicitly states that generators/ranges/sequences are expected?

> Two-dimensional data in various forms; dict input must contain Sequences, Generators, or a range. Sequence may contain Series or other Sequences.

**Comment by alexander-beedie** [comment]
The single integer version isn't ambiguous in the same way; it's a scalar, it can only be a single element, and there is no confusion that the dtype matches the value, so (largely as as a nicety) we allow it.

Once you supply a _list_ of values however it becomes a problem, as then we _don't_ know that you didn't make a mistake when defining the schema. The ambiguity can't be resolved on our side.

**Comment by nzqo** [comment]
> The single integer version isn't ambiguous in the same way; it's a scalar, it can only be a single element, and there is no confusion that the dtype matches the value, so (largely as as a nicety) we allow it.
> 
> Once you supply a _list_ of values however it becomes a problem, as then we _don't_ know that you didn't make a mistake when defining the schema. The ambiguity can't be resolved on our side, so it's an error.
> 
> For instance, how would we resolve the given data `{"x": [0,1,2,3]}` if told that it's a list of ints; as an error, as a list of four 1-element lists, as a single 4-element list (or even two 2-element lists)? ;)

That last example makes a fair point. I hadn't thought that far since all of the data I am dealing with also has fields that are of primitive type, which resolves this ambiguity indirectly.

It might still help to catch that error a little earlier with some type check to announce incompliant API usage early, but I guess that would be an enhancement request :)

**Comment by alexander-beedie** [comment]
The constructors are pretty flexible/forgiving in general, but sometimes we have to draw a line in the sand, heh 😉
