### ISSUE TITLE
`group_by_dynamic` skips empty windows

### ISSUE THREAD

**Issue by TrevorWinstral** [pola-rs/polars#15967]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime
import polars as pl

df = pl.DataFrame(
    [
        (datetime.date(2020, 1, 6), 1),
        (datetime.date(2020, 1, 21), 5),
        (datetime.date(2020, 1, 30), 2),
        (datetime.date(2020, 2, 3), 7),
        (datetime.date(2020, 2, 4), 10),
        (datetime.date(2020, 2, 5), 15),
        (datetime.date(2020, 2, 6), True),
        (datetime.date(2020, 2, 14), 3),
        (datetime.date(2020, 2, 18), 2),
        (datetime.date(2020, 3, 10), 5),
    ],
    schema=["date", "num_events"],
).sort("date")

df.group_by_dynamic(
    index_column="date",
    period="7d",
    every="1d",
    label="right",
    closed="both",
).agg(active_days=pl.len())
```

### Issue description

The idea here is that even when the window of the dynamic group is empty, we should be able to perform operations. From the [documentation](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.group_by_dynamic.html#polars.DataFrame.group_by_dynamic) we only have:

>Time windows are calculated and rows are assigned to windows. Different from a normal group by is that a row can be member of multiple groups. By default, the windows look like:
> -  [start, start + period)
> -  [start + every, start + every + period)
> -  [start + 2\*every, start + 2*every + period)
> -  …
>where start is determined by start_by, offset, every, and the earliest datapoint. See the start_by argument description for details.

The issue is here is that from this descriptions, when we prescribe our aggregation operations, we also consider how to aggregate windows with no data. For instance when doing a `pl.len()` aggregation, if the window is empty we should expect `0`. For instance imagine the following dataframe, with a row for every day when an event happened with how many happened.

```python
import datetime
import polars as pl

df = pl.DataFrame(
    [
        (datetime.date(2020, 1, 6), 1),
        (datetime.date(2020, 1, 21), 5),
        (datetime.date(2020, 1, 30), 2),
        (datetime.date(2020, 2, 3), 7),
        (datetime.date(2020, 2, 4), 10),
        (datetime.date(2020, 2, 5), 15),
        (datetime.date(2020, 2, 6), True),
        (datetime.date(2020, 2, 14), 3),
        (datetime.date(2020, 2, 18), 2),
        (datetime.date(2020, 3, 10), 5),
    ],
    schema=["date", "num_events"],
).sort("date")
```
This is a very benign dataframe, but this is simply for example. Now if I want to know on a given day how many days over the past week had events, we should just create the dynamic group by as below, and count how many rows are included.
```python
df.group_by_dynamic(
    index_column="date",
    period="7d",
    every="1d",
    label="right",
    closed="both",
).agg(active_days=pl.len())
```
But this yields the following:
![image](https://github.com/pola-rs/polars/assets/31442534/a7bb1224-3c7c-4fe0-b342-3fd317c77ce0)
We can see there are jumps in the date columns from the 13th to the 21st, since on the 14th, looking back 7 days, the window is empty and therefore excluded. Instead the days from the 14th through the 20th should have 0s in the `active_days` columns. To solve this I could create a date-range and join it to `df` in an outer-coalesce fashion, and fill the nulls with 0s, and then do the dynamic group by, but in that case I could also use rolling instead.  

To summarize, I believe the docs should either be updated to reflect the actual result, i.e. including a warning that empty windows are skipped or fix the process to include the empty windows.

### Expected behavior

Days with empty windows should also have the aggregation run on them. Even if this results in nulls.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
Python:               3.10.6 (main, Jan 30 2023, 13:56:31) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
hi - I think it is documented:

> note that, unlike pandas, polars doesn’t add extra rows for empty windows. If you need index_column to be evenly spaced, then please combine with [DataFrame.upsample()](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.upsample.html#polars.DataFrame.upsample).

but maybe it should be more prominent

**Comment by TrevorWinstral** [comment]
I see, my bad, we can close this if no changes to the docs are necessary from your perspective.
