### ISSUE TITLE
Multipling a Decimal by Int returns Int type

### ISSUE THREAD

**Issue by philippspengler** [pola-rs/polars#16035]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame([0.12345678]).select(pl.col('column_0').cast(pl.Decimal(scale=6)) * 1)
```

### Log output

```shell
shape: (1, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ i32      │
╞══════════╡
│ 0        │
└──────────┘
```

### Issue description

In previous versions of polars (<0.20.23), multiplying a Decimal type column with an integer resulted in a Decimal column. Since polars 0.20.23, polars converts the column to int type.

### Expected behavior

shape: (1, 1)
┌────────────────┐
│ column_0       │
│ ---            │
│ decimal[*,12]  │
╞════════════════╡
│ 0.123456000000 │
└────────────────┘

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             Linux-5.11.0-46-generic-x86_64-with-glibc2.31
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.23.0
openpyxl:             <not installed>
pandas:               2.1.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.52
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
@ritchie46 any chance it's from https://github.com/pola-rs/polars/pull/15879?

**Comment by ritchie46** [comment]
Ah, yes.. That's related. Will take a look.
