### ISSUE TITLE
Casting float to Decimal fails silently

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16047]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([0.1]).cast(pl.Decimal(10, 5))
print(s)
```

### Log output

```shell
shape: (1,)
Series: '' [f64]
[
        0.1
]
```

### Issue description

The cast doesn't work and the dtype remains a float. No error is thrown.

### Expected behavior

This cast should work. 

### Installed versions

main

**Comment by JulianCologne** [comment]
yeah, I have a very similar issue already (#12775)

It actually works if you "activate the Decimal"

```python
pl.Config.activate_decimals(True)

pl.Series([0.1]).cast(pl.Decimal(10, 5))

shape: (1,)
Series: '' [decimal[10,5]]
[
	0.10000
]
```

However, there is still a "bug" where the precision is not correctly inferred 

```python
pl.Series([5.67]).cast(pl.Decimal)

shape: (1,)
Series: '' [decimal[38,0]]
[
	5
]
```

- `5.67` truncated to `5`
- `Decimal` documentation says that by default the precision is inferred from the data which does not work here

**Comment by stinodego** [comment]
Thanks for the link - closing this one then!
