### ISSUE TITLE
fill_null doesn't support expr 

### ISSUE THREAD

**Issue by eromoe** [pola-rs/polars#16055]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

![image](https://github.com/pola-rs/polars/assets/3938751/63a691de-f56e-44fe-85e1-184df69ba45b)

### Issue description

I find `fill_null` doesn't supoort fill by another col 
PS: `fill_nan` works,  however cost my 1 hour to dig this problem .

Here in docs https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.fill_null.html 

### Expected behavior

Type annotation is `Any` , I think it should support fill by expr 
>  value: Any | [None](https://docs.python.org/3/library/constants.html#None) = None,

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.24.4
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              15.0.2
pydantic:             2.6.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.29
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by lyngc** [comment]
You are dividing by 0, resulting in a NaN value. NaN is not a null (missing) value. Being able to differentiate between null values and NaN values is super useful.

**Comment by cmdlineluser** [comment]
Would it be worthwhile adding a note/warning to the fill_null docs?

 Or maybe linking to the user guide?

- https://docs.pola.rs/user-guide/expressions/missing-data/

The assumption that fill_null will work on NaN has popped up a few times.

**Comment by eromoe** [comment]
@ritchie46 pandas only have method `fillna` , and other functions like `notnull`  ,`isnull`  also check the value is nan of not .

**Comment by ritchie46** [comment]
That's because pandas mixes floating point `NaN` and missing values. 

We don't follow pandas. It is not correct on this matter.

**Comment by eromoe** [comment]
@ritchie46 I think it better to warn this in docs at least , because many people come from pandas would easily make mistakes .
