### ISSUE TITLE
Add ability to specify prefix for unnest

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#16068]
### Description

I find myself regularly un-nesting structures such as

```json
{
    equipment: { name=XXX, level=YYY, zone=ZZZ, ...}
    sensor: {name=ABC, level=123, ... }
}
```

i.e. the names of the exploded columns for equipment and sensor clash. This requires code like

```
.unnest("equipment").rename({"name":"equipment_name", "level":"equipment_level" ... })
.unnest("sensor").rename({"name":"sensor_name", "level":"sensor_level" ... })
```

It would be nice if `rename` had arguments to generate the names. The simplest option would be a prefix, i.e.

```
.unnest("equipment", prefix="equipment_").unnest("sensor", prefix="sensor_")
```

Another option would be to infer the prefix from the base column name, i.e.

```
.unnest("equipment", add_prefix=True).unnest("sensor", add_prefix=True)
```
'

would add the prefix based on the first argument etc.

**Comment by cmdlineluser** [comment]
Some struct methods were recently added to `.name` which could help.

- https://docs.pola.rs/docs/python/dev/reference/expressions/name.html

```python
df.with_columns(
   pl.col("equipment").name.prefix_fields("equipment_"),
   pl.col("sensor").name.prefix_fields("sensor_")
).unnest("equipment", "sensor")
```

Also related: https://github.com/pola-rs/polars/issues/12353

**Comment by david-waterworth** [comment]
Thanks @cmdlineluser that works for me
