### ISSUE TITLE
Add `enum_as_str` argument to `assert_frame_equal`

### ISSUE THREAD

**Issue by butterlyn** [pola-rs/polars#16075]
### Description

The `categorical_as_str` flag can be passed to `assert_frame_equal`, I believe the newer `polars.Enum` data type warrants the same functionality.

**Comment by stinodego** [comment]
I don't see the benefit of adding this.

The reason this was added for Categoricals is that they may have different underlying physical representations, while the string values are the same. This cannot happen for Enums.

If you can show me a code example where this would be beneficial, I may reopen this.
