### ISSUE TITLE
Ability to choose data type for Categorical storage, U8, U16, instead of only U32

### ISSUE THREAD

**Issue by Houski** [pola-rs/polars#16087]
### Description

We can significantly decrease the memory usage of our dataset by using U8s instead of U32s for categorical encoding.

In a discussion on the Rust Polars Discord, it was mentioned that while the underlying Arrow dictionary type supports specifying the index type, although Polars currently has it hardcoded to U32.

**Comment by mcrumiller** [comment]
Also duplicate of #13109.

**Comment by stinodego** [comment]
Thanks for the link, I knew there had to be an issue but I couldn't find it. I'll close this one in favor of the existing issue.
