### ISSUE TITLE
Bug report when using hive2 write_database

### ISSUE THREAD

**Issue by matysmart** [pola-rs/polars#16095]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *
import polars as pl
from pyhive import hive

### polars code
conn_url = 'hive://username:password@localhost:port/database'
engine = create_engine(conn_url)

sample_df = pd.DataFrame({"colA":[90,23,42], "colB":["kill","oks","hello"]})
### Pandas to_sql code works because of the index=False, method='multi'
sample_df.to_sql("sample_table", con=engine, index=False, method='multi')
### However polars fails when doing write_database
sample_df_pl.write_database(table_name="sample_table", connection=conn_url)

### Log output

```shell
File ~\AppData\Local\anaconda3\envs\awsenv\lib\site-packages\pyhive\hive.py:496, in Cursor._fetch_more(self)
    494 assert(self._operationHandle is not None), "Should have an op handle in _fetch_more"
    495 if not self._operationHandle.hasResultSet:
--> 496     raise ProgrammingError("No result set")
    497 req = ttypes.TFetchResultsReq(
    498     operationHandle=self._operationHandle,
    499     orientation=ttypes.TFetchOrientation.FETCH_NEXT,
    500     maxRows=self.arraysize,
    501 )
    502 response = self._connection.client.FetchResults(req)

ProgrammingError: (pyhive.exc.ProgrammingError) No result set
[SQL: INSERT INTO TABLE `sample_table` VALUES (%(colA)s, %(colB)s)]
[parameters: [{'colA': 90, 'colB': 'kill'}, {'colA': 23, 'colB': 'oks'}, {'colA': 42, 'colB': 'hello'}]]
```

### Issue description

Pandas to_sql works, but polars write_database doesn't

### Expected behavior

should be working since pandas to_sql works too

### Installed versions

--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.6
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.29
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

**Comment by alexander-beedie** [comment]
Should be fixed in the upcoming `0.20.26` - you'll be able to do the following:
```python
df.write_database(
    connection="hive://user:pass@server:port/database",
    table_name="target_table",
    engine_options={"method": "multi"},
)
```
