### ISSUE TITLE
.extend significantly outperforms concat for the same operation

### ISSUE THREAD

**Issue by Chuck321123** [pola-rs/polars#16108]
### Description

So maybe im not comparing apples to apples, but I have this code:
```py
import polars as pl
import numpy as np
from datetime import datetime, timedelta, date

length=500000

df1 = pl.DataFrame({
    "Category": pl.Series(np.random.choice(['A', 'B', 'C'], size=length)).cast(pl.String),
    "Value": pl.Series(np.random.rand(length)),
    "Value2": pl.Series(np.random.rand(length))                   
})
df2 = pl.DataFrame({
    "Category": pl.Series(np.random.choice(['D', 'E', 'F'], size=length)).cast(pl.String),
    "Value": pl.Series(np.random.rand(length)),
    "Value2": pl.Series(np.random.rand(length))  
})

lst = []

for i in range(10):
    print(i)
    t=datetime.now()
    df1.extend(df2)
    lst.append(datetime.now()-t)

print(f"Extend average where length = {length}: {np.mean(lst)}")

%timeit pl.concat([df1, df2])
```
Where i constantly get that extend is 3-4x faster than concat. (I expected only 2 times faster). These are my results:
```
Extend average where length = 500000: 0:00:00.007850
35.2 ms ± 3.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
However, if i increase the length to the double of what i had, extend increases linearly, but concat increases more than expected, like this: 
```
Extend average where length = 1000000: 0:00:00.020646
151 ms ± 7.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Even here, extend did beat concat from the previous round with double the length. Idk, maybe im doing a bad comparison, and i know that concat creates a new df while extend only modifies, but still. Just wanted to share my results. Let me know what you think

**Comment by Chuck321123** [comment]
@s-banach It was about 3000x faster. Are there any reasons this isnt set to False by default?

**Comment by s-banach** [comment]
It's optimized for the use-case where you call `df = pl.concat(...)` just once up top,
and then you do all the rest of your processing on `df`.
The idea is that most operations on `df` will be faster if `df` is contiguous in memory, rather than separate chunks.

**Comment by Chuck321123** [comment]
@s-banach I see. Unfortunately, there were no performance gains when i did ```rechunk=False``` with ```how="align"```

**Comment by ritchie46** [comment]
You are comparing apples with peaches. 

Every time you extend `df1`, you mutate the original memory. So the first `extend` is much cheaper than the later ones (that trigger a realloc) as your size of  `df1` increases every iteration.

```
for i in range(10):
    df1.extend(df2)
    print(df1.height)
```

```
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
```

So your `extend` "benchmark" has a different input every iterations, whilst your `concat` "benchmark" needs to concat the 5_500_000 case every time. Please take the time to validate your benchmarks.

On the difference, they will perform different. That's fine, they do different things.

Don't use `extend` as it mutates underlying memory which leads to these kind of bugs. As the warning of the extend docstring states.
