### ISSUE TITLE
Very high memory usage: scan_parquet().select(vec![col]).min().collect()

### ISSUE THREAD

**Issue by d33tah** [pola-rs/polars#16131]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Consider the "minmax" feature of the following program - feed it with a Parquet file that has a billion rows:

```rust
use polars::prelude::*;

use clap::{Arg, Command};

fn main() -> PolarsResult<()> {

    let matches = Command::new("pqstat")
        .arg(Arg::new("MODE")
             .long("mode")
             .required(true)
             .help("Choose mode: minmax or uniqc"))
        .arg(Arg::new("COLUMN")
             .long("column")
             .required(false)
             .help("Enter column name"))
        .arg(Arg::new("FILE")
             .required(true)
             .help("Path to the file"))
        .get_matches();

    let mode = matches.get_one::<String>("MODE").unwrap();
    let column_name = matches.get_one::<String>("COLUMN").unwrap();
    let file = matches.get_one::<String>("FILE").unwrap();

    if mode == "minmax" {
        println!("{}", LazyFrame::scan_parquet(file, ScanArgsParquet::default())?
        .select(vec![
                col(column_name).min().alias(&(column_name.to_owned() + "_min")),
                col(column_name).max().alias(&(column_name.to_owned() + "_max")),
        ])
        .collect()?);
    } else if mode == "uniqc" {
        println!("{}", LazyFrame::scan_parquet(file, ScanArgsParquet::default())?
        .select(vec![
                col(column_name).value_counts(false, true),
        ])
        .collect()?);
    }

    Ok(())
}


```
 

### Issue description

I don't understand why min/max operations require what seems to be loading an entire column to RAM.

### Expected behavior

The memory usage is much lower.

### Installed versions

<details>

name = "polars"
version = "0.39.2"
name = "polars-arrow"
version = "0.39.2"
name = "polars-arrow-format"
version = "0.1.0"
name = "polars-compute"
version = "0.39.2"
name = "polars-core"
version = "0.39.2"
name = "polars-error"
version = "0.39.2"
name = "polars-io"
version = "0.39.2"
name = "polars-lazy"
version = "0.39.2"
name = "polars-ops"
version = "0.39.2"
name = "polars-parquet"
version = "0.39.2"
name = "polars-pipe"
version = "0.39.2"
name = "polars-plan"
version = "0.39.2"
name = "polars-row"
version = "0.39.2"
name = "polars-sql"
version = "0.39.2"
name = "polars-time"
version = "0.39.2"
name = "polars-utils"
version = "0.39.2"
name = "polarstat"
version = "0.1.0"
</details>

**Comment by ritchie46** [comment]
This is because Polars doesn't yet have streaming aggregations. This is not a bug. They will come.
