### ISSUE TITLE
Add `Expr.is_min`, `Expr.is_max`

### ISSUE THREAD

**Issue by dangotbanned** [pola-rs/polars#16136]
### Description

# Background
Currently there are several `Expr` boolean mask methods:

- `is_null`
- `is_not_null`
- `is_finite`
- `is_infinite`
- `is_nan`
- `is_not_nan`
- `is_unique`
- `is_first_distinct`
- `is_last_distinct`
- `is_duplicated`
- `is_in`
- `is_between`

I find these really helpful and cover most cases.

However, I've felt that `is_min/max` were missing.
# Mock implementation

I'm new to `rust` and wanted to try implementing this there, but it looks singnificantly more complex than I'd imagined. 

Below is enough in `python` to demonstrate the behaviour:
```py
from polars import Expr

def is_max(self: Expr) -> Expr:
    return self == self.max()

def is_min(self: Expr) -> Expr:
    return self == self.min()

# monkeypatching for demo purposes
Expr.is_max = is_max
Expr.is_min = is_min
```

# Example usage
I've been using these as UDFs, but as methods I think they improve readability even with relatively short column names:

```py
import polars as pl

base = pl.DataFrame({
    "index": range(6),
    "group": [2, 1, 2, 2, 1, 1],
    "quantity QTD": [1, 1, 6, 3, 15, 26],
    "quantity YTD": [1, 4, 6, 9, 21, 50],
})

result = base.with_columns(
    # 1a: operator overloading requires extra (...) + repeat names
    (pl.col("quantity QTD") == pl.col("quantity QTD").max()).name.suffix(" max"),
    # 1b: method equivalent
    pl.col("quantity YTD").is_max().name.suffix(" max"),
    # 2a: after chaining methods, `ruff` format isn't great
    (pl.col("quantity QTD") == pl.col("quantity QTD").max().over("group")).name.suffix(
        " max(group)"
    ),
    # 2b: method equivalent
    pl.col("quantity YTD").is_max().over("group").name.suffix(" max(group)"),
)
```
```
shape: (6, 8)
┌───────┬───────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ group ┆ quantity    ┆ quantity    ┆ quantity    ┆ quantity    ┆ quantity    ┆ quantity   │
│       ┆       ┆ QTD         ┆ YTD         ┆ QTD max     ┆ YTD max     ┆ QTD         ┆ YTD        │
│       ┆       ┆             ┆             ┆             ┆             ┆ max(group)  ┆ max(group) │
╞═══════╪═══════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ 0     ┆ 2     ┆ 1           ┆ 1           ┆ false       ┆ false       ┆ true        ┆ false      │
│ 1     ┆ 1     ┆ 1           ┆ 4           ┆ false       ┆ false       ┆ true        ┆ false      │
│ 2     ┆ 2     ┆ 6           ┆ 6           ┆ false       ┆ false       ┆ true        ┆ false      │
│ 3     ┆ 2     ┆ 3           ┆ 9           ┆ false       ┆ false       ┆ true        ┆ true       │
│ 4     ┆ 1     ┆ 15          ┆ 21          ┆ false       ┆ false       ┆ true        ┆ false      │
│ 5     ┆ 1     ┆ 26          ┆ 50          ┆ true        ┆ true        ┆ true        ┆ true       │
└───────┴───────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘
```

For more of a real-world example, this came up quite a lot when modelling [SCDs](https://www.sqlshack.com/implementing-slowly-changing-dimensions-scds-in-data-warehouses/) with versioning/tracking history. 

I was suprised to see this hadn't been proposed in an issue before. Hoping that isn't a bad sign.

**Comment by dangotbanned** [comment]
> I don't think `is_max` would offer any performance benefit over calculating `max` first and then checking equality, right?

Yeah, sorry, this was asking from a convenience/readability perspective.

> I'll close this as not planned, feel free to try and change my mind.

Totally understandable. Looking into the amount of extra code this would require on the `rust` side, I can see why you guys need to be conservative with what gets added. 

Thanks for giving this a read

**Comment by DrMaphuse** [comment]
I know this is technically closed, but I wanted to chime in here with a very frequent use case that I am facing. I think this would be a fantastic syntactic sugar to have just for use in window functions. Consider these options that I currently have for filtering max/min values of subgroups:

```py3
# option 1:
df.filter((pl.col("a") == pl.col("a").max()).over("b", "c", "d"))

# option 2:
df.sort('a', descending=True).unique(["b", "c", "d"], keep='first')
```

Option 1:
* bad for readability due to the repeated use of `pl.col("a")`
* error-prone due to confusing parentheses

Option 2:
* not exactly the same, because it removes duplicates
* incurs computational overhead by sorting the entire dataframe
* using `unique()` for filtering by a value is unintuitive

This is what it would look like using `is_max()`:
```py3
df.filter(pl.col("a").is_max().over(["b", "c", "d"]))
```

My current implementation using the namespace extention api:
```py3
@pl.api.register_expr_namespace("custom")
class Custom:
    def __init__(self, expr: pl.Expr) -> None:
        self._expr = expr

    def is_max(self):
        return self._expr.eq(self._expr.max())

    def is_min(self):
        return self._expr.eq(self._expr.min())
```

I would really love to have this in polars source though.
