### ISSUE TITLE
drop_null by axis

### ISSUE THREAD

**Issue by stillmatic** [pola-rs/polars#1613]
#### Describe your feature request

Pandas [dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) supports dropping nulls by a given axis (e.g. col-wise or row-wise) as well as "how", e.g. if any values are null in a given axis or if all are null. The drop_nulls feature currently (if I am reading the docs/code correctly) drops only row-wise and if any values are null.

**Comment by YHM404** [comment]
> Thanks for the feature request. Polars aims to provide an API that allows you to customize to your specific needs. We hope to provide that by small composable expressions and not by a lot of methods and keyword arguments. Therefore I've added some examples to the `drop_null` docstrings that may help your specific request.
> 
> Below are snippets that let you drop nulls by `all` and by `axis`. The latter is possible in the release this afternoon.
> 
> ```python
> df = pl.DataFrame(
>     {
>         "a": [None, None, None, None],
>         "b": [1, 2, None, 1],
>         "c": [1, None, None, 1],
>     }
> )
> df
> ```
> 
> ```
> shape: (4, 3)
> ┌──────┬──────┬──────┐
> │ a    ┆ b    ┆ c    │
> │ ---  ┆ ---  ┆ ---  │
> │ f64  ┆ i64  ┆ i64  │
> ╞══════╪══════╪══════╡
> │ null ┆ 1    ┆ 1    │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ 2    ┆ null │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ null ┆ null │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ 1    ┆ 1    │
> └──────┴──────┴──────┘
> ```
> 
> ```python
> # filter rows where all values are null
> df.filter(~pl.fold(True, lambda acc, s: acc & s.is_null(), pl.all()))
> ```
> 
> ```
> shape: (3, 3)
> ┌──────┬─────┬──────┐
> │ a    ┆ b   ┆ c    │
> │ ---  ┆ --- ┆ ---  │
> │ f64  ┆ i64 ┆ i64  │
> ╞══════╪═════╪══════╡
> │ null ┆ 1   ┆ 1    │
> ├╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ 2   ┆ null │
> ├╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ 1   ┆ 1    │
> └──────┴─────┴──────┘
> ```
> 
> ```python
> # filter columns where all values are null
> df[:, [not (s.null_count() == df.height) for s in df]]
> ```
> 
> ```
> shape: (4, 2)
> ┌──────┬──────┐
> │ b    ┆ c    │
> │ ---  ┆ ---  │
> │ i64  ┆ i64  │
> ╞══════╪══════╡
> │ 1    ┆ 1    │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ 2    ┆ null │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ null ┆ null │
> ├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
> │ 1    ┆ 1    │
> └──────┴──────┘
> ```

Could you please show that usecase in Rust API?

**Comment by lascott** [comment]
I do not think you can filter columns as lazy.
For rows, one can determine this as you stream.
This would mean you knew the complete column was null, but you cannot until the entire stream is read.

Having said this, I suppose in two passes, one could lazyily keep track of s.null_count() and then go back and scan rows without the empty columns.

**Comment by u10000129** [comment]
Hi lascott, thanks for your response.
I posted the question on stackoverflow and obtained a similar answer to yours.
I guess this might come from the columnar nature of the lazy api.

Here is the link to the question for reference:
[https://stackoverflow.com/questions/76338261/polars-and-the-lazy-api-how-to-drop-columns-that-contain-only-null-values](https://stackoverflow.com/questions/76338261/polars-and-the-lazy-api-how-to-drop-columns-that-contain-only-null-values)
