### ISSUE TITLE
Cannot filter on decimal fields in parquet files using is_in()

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#16150]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
#create a parquet file containing decimal data type, eg:
import pandas as pd
import decimal
df = pd.DataFrame({'value': [0.0, 0.1, 0.3, 0.4, 0.5]})
df['value_decimal'] = df['value'].astype(str).map(decimal.Decimal)
df['integer'] = (df['value']*10).astype(int).map(decimal.Decimal)
df.to_parquet("test_data.parquet", index=False)
```
If you do a scan_parquet and then filter on it like:
```
import polars as pl
df = pl.scan_parquet('test_data.parquet')
df.filter(pl.col('value_decimal').is_in([0.0,0.1])).collect()
```
you'll get an error:
```InvalidOperationError: is_in cannot check for Float64 values in Decimal(Some(1), Some(1)) data```

Though you can always cast, like:
```df.filter(pl.col('value_decimal').cast(pl.Float32).is_in([0.0, 0.1])).collect() # ???```
which runs without errors, but fails to return value 0.1 !!!

Filtering on "integer" decimals does fail as well:
```df.filter(pl.col('integer').is_in([3.0,4.0])).collect()```
```InvalidOperationError: is_in cannot check for Float64 values in Decimal(Some(1), Some(0)) data```

Though casting here works well:
```df.filter(pl.col('integer').cast(pl.Float32).is_in([3.0,4.0])).collect()```

### Log output

```shell
see Reproducible example
```

### Issue description

InvalidOperationError: is_in cannot check for Float64 values in Decimal(Some(1), Some(1)) data
InvalidOperationError: is_in cannot check for Int64 values in Decimal(Some(1), Some(0)) data

### Expected behavior

Does not fail, returns the correct results

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.25
Index type:           UInt32
Platform:             Linux-4.18.0-372.76.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:               3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2022.02.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         1.5.5
numpy:                1.23.5
openpyxl:             3.0.9
pandas:               2.2.0
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.27
torch:                1.10.2
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

**Comment by lmocsi** [comment]
On polars==1.14.0 all the above filterings work fine, except for this one:
```df.filter(pl.col('value_decimal').cast(pl.Float32).is_in([0.0, 0.1])).collect()```
which runs without errors, but fails to return value 0.1 !!!

**Comment by cmdlineluser** [comment]
Is it because `.is_in([0.1])` ends up as Float64?

```python
>>> pl.select(pl.lit("0.1").cast(pl.Float32).is_in([0.1])).item()
False
>>> pl.Series([0.1]).dtype
Float64
```

**Comment by lmocsi** [comment]
Yeah, you're right.
Then all is solved, I'm closing this issue.
