### ISSUE TITLE
Switch to PyO3 0.21's native datetime support, now available with abi3

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#16158]
Per @stinodego:

PyO3 has support for the Python `datetime` module:
https://pyo3.rs/main/doc/pyo3/types/struct.pydatetime

However, this was never available under the `abi3` feature flag.

So we have a bunch of workarounds in place to materialize/read `datetime` objects. Specially, we have defined Python functions here:
https://github.com/pola-rs/polars/blob/main/py-polars/polars/_utils/convert.py

...that are called from Rust, for example here:
https://github.com/pola-rs/polars/blob/8ef2e212cf52c318e18d12d38b02c3ad0a918ab2/py-polars/src/conversion/any_value.rs#L61-L64

The 0.21 release notes mention:

> Extended chrono / datetime conversions, including support for the abi3 feature and the chrono-tz crate

So I am expecting that we can now take advantage of native PyO3 datetime support. And I expect a good performance boost + code cleanup to come from this.

_Originally posted by @stinodego in https://github.com/pola-rs/polars/issues/15215#issuecomment-2056708405_

**Comment by itamarst** [comment]
Gonna do this next.

**Comment by itamarst** [comment]
In addition to the `to_py_date()` and friends, there's also logic in the opposite direction that might also be possible to remove as part of this.

**Comment by itamarst** [comment]
https://github.com/PyO3/pyo3/issues/3266 means that timezone conversions are lossy, the string timezone is converted to a fixed offset in seconds. So might not be able to convert everything immediately.

**Comment by ritchie46** [comment]
Interesting. That saves a lot of sub-optimal back and forth.

**Comment by itamarst** [comment]
Digging further, it may be that the PyO3 limitation is tied to version of Python, and upping minimum supported version to 3.9 will fix it. Python 3.8 security EOL is October 31, 2024...

**Comment by itamarst** [comment]
(Around 5% of Polars downloads are Python 3.8, per https://pypistats.org/packages/polars).

**Comment by stinodego** [comment]
FYI, so far we have always kept support for Python versions until their end of life, and then dropped support in the next release. Which I think is a good policy.

 So if Python 3.8 support is problematic, this would be blocked until November this year.

**Comment by ritchie46** [comment]
Yes, we will follow python in this regard.

**Comment by itamarst** [comment]
Ok, will just file a ticket for second pass optimization.
