### ISSUE TITLE
Expr.fill_null(integer) corrupts Categorical data

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#16171]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.DataFrame({'A': pl.Series(['foo'], dtype=pl.Categorical)}).fill_null(1)
 A
 foo
shape: (1, 1)
>>> pl.DataFrame({'A': pl.Series(['foo'], dtype=pl.Categorical)}).select(pl.col.A.fill_null(1))
 A
 1
shape: (1, 1)
```

### Issue description

Specifying `pl.col(column).fill_null(integer)` when `column` is `Categorical` sets all values to `integer`. 

### Expected behavior

Both of the examples should probably give a TypeError, since integers aren't in general interchangeable with categoricals.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
fixed by #16182
