### ISSUE TITLE
Add pl.Inf such that it is compatible with several data types.

### ISSUE THREAD

**Issue by mkleinbort** [pola-rs/polars#16177]
### Description

I hit issues the other day trying to use placeholder "inf/-inf" on date and datetime columns.

Illustratively:

```python
valueStart = pl.date(2020,1,1)
valueEnd = np.inf

df.filter(pl.col('date').is_between(valueStart, valueEnd))
```

It'd be good to not need to rely on numpy or `float('inf')` for these use cases. 

The proposal is for `pl.Inf` to be added, such that any non null  and non nan value compares as less than `pl.Inf`.

**Comment by MarcoGorelli** [comment]
Hi - what's wrong with `float('inf')`?

**Comment by alexander-beedie** [comment]
Hmm... I don't think we currently encode the concept of an infinite date; have to check 🤔 
(which I am familiar with from PostgreSQL: https://www.npgsql.org/doc/types/datetime.html#infinity-values)

**Comment by mkleinbort** [comment]
> Hi - what's wrong with `float('inf')`?

I hit the issue when filtering on the comparison of two date columns and wanted to `.fill_null(inf)` on one of them.

Here I was using np.inf, but that is no longer supported on date columns in the current polars version.

**Comment by alexander-beedie** [comment]
> Here I was using np.inf, but that is no longer supported on date columns in the current polars version.

FYI, `np.inf` actually _is_ `float("inf")`, so would be a bit surprised if we _ever_ supported it (and, if so, what internal value it could have resolved to, given that our temporal values are internally all 64bit integers). Do you have a version when you think this worked?

```python
type(np.inf) 
# float
```

**Comment by mkleinbort** [comment]
It worked in `0.20.21`

https://github.com/pola-rs/polars/issues/16156

**Comment by stinodego** [comment]
I don't think adding something like this makes sense. Once we have scalar types, we can consider adding something like `pl.Date.max`. And infinite date doesn't make sense though.

For your use case, you can use a `when/then/otherwise` to handle the null values, or fill with a small value instead, e.g. `datetime.date.min` or `-(2**31)`.
