### ISSUE TITLE
Filter doesn't work as expected

### ISSUE THREAD

**Issue by AnatolyBuga** [pola-rs/polars#16276]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
let s1: Series = ["London", "Milan", "Amsterdam"].into_iter().collect::<Series>().with_name("city");
let s2: Series = [Some(100.0), None, Some(10.)].into_iter().collect::<Series>().with_name("population");
let s3: Series = [None, None, Some(0.)].into_iter().collect::<Series>().with_name("area");

let res: DataFrame = DataFrame::new(vec![s1, s2, s3]).unwrap();

let mut predicate = col("population").neq(lit::<f64>(0.)).and(col("population").neq(NULL.lit()));

dbg!( res.lazy().filter(predicate).collect() );
```

### Issue description

Filtering doesn't work as expected in th elatest version. In this example I want to filter out rows where _population_ column is NULL  or  0.0
 

### Expected behavior

version `0.35.4` returns, as expected:

    ┌───────────┬────────────┬──────┐
    │ city      ┆ population ┆ area │
    │ ---       ┆ ---        ┆ ---  │
    │ str       ┆ f64        ┆ f64  │
    ╞═══════════╪════════════╪══════╡
    │ London    ┆ 100.0      ┆ null │
    │ Amsterdam ┆ 10.0       ┆ 0.0  │
    └───────────┴────────────┴──────┘

version `0.39.2` returns an **empty table - that's wrong**

### Installed versions

<details>

polars = { version = "0.39.2", features = ["lazy"] }

</details>

**Comment by cmdlineluser** [comment]
If it helps, on Python it generates a warning:

```python
UserWarning: Comparisons with None always result in null. Consider using `.is_null()` or `.is_not_null()`.
```

I think the nulls will be left out by default:

```python
df.filter(
   pl.col.population != 0.
)
# shape: (2, 3)
# ┌───────────┬────────────┬──────┐
# │ city      ┆ population ┆ area │
# │ ---       ┆ ---        ┆ ---  │
# │ str       ┆ f64        ┆ f64  │
# ╞═══════════╪════════════╪══════╡
# │ London    ┆ 100.0      ┆ null │
# │ Amsterdam ┆ 10.0       ┆ 0.0  │
# └───────────┴────────────┴──────┘
```

`ne_missing()` (or `neq_missing` in Rust) are the variants which will include the nulls as equal.

I'm not sure when this changed.

**Comment by AnatolyBuga** [comment]
Ah right, thanks! I might try smth like `.is_null()` instead. Will revert

**Comment by AnatolyBuga** [comment]
Thank you, I confirm that worked!
