### ISSUE TITLE
Rust in-memory parquet I/O behaves inconsistently with c++/pyarrow

### ISSUE THREAD

**Issue by linlol** [pola-rs/polars#16319]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from io import BytesIO
import polars as pl

# serialise polars data frame to bytes via io.BytesIO

def serialise(df : pl.DataFrame, use_pyarrow = True) -> bytes:
    with BytesIO() as file:
        df.write_parquet(file, use_pyarrow=use_pyarrow)
        file.seek(0)
        return file.read()

def deserialise(data : bytes, use_pyarrow = True) -> pl.DataFrame:
    with BytesIO() as file:
        file.write(data)
        df = pl.read_parquet(file,use_pyarrow = use_pyarrow)
        return df
# create sample dataframe
import numpy as np
data = np.random.random((100, 2))
df = pl.DataFrame(data, schema=['A', 'B'])
# it works for c++ implementation
assert df.frame_equal(deserialise(serialise(df)))
# it fails for rust implementation
assert df.frame_equal(deserialise(serialise(df, False), False))

# Above issue only happen if we load/read data from an in-memory BytesIO object, 
# if we load data to file, and read the real file, polars-arrow behaves consistently with pyarrow

# parquet created by pyarrow could be deserialised via both c++ and polars arrow
df.write_parquet('pyarrow_df', use_pyarrow=True)
pyarrow_df_via_pyarrow_file = pl.read_parquet('pyarrow_df', use_pyarrow = True)
rust_arrow_df_via_pyarrow_file = pl.read_parquet('pyarrow_df', use_pyarrow = False)
assert rust_arrow_df_via_pyarrow_file.frame_equal(pyarrow_df_via_pyarrow_file)

# vice versa
df.write_parquet('rust_arrow_df', use_pyarrow=False)
cpp_arrow_df_via_rust_arrow_file = pl.read_parquet('pyarrow_df', use_pyarrow = True)
rust_arrow_df_via_rust_arrow_file = pl.read_parquet('pyarrow_df', use_pyarrow = False)
assert rust_arrow_df_via_rust_arrow_file.frame_equal(cpp_arrow_df_via_rust_arrow_file)
```

### Issue description

/tmp/ipykernel_10229/3449737049.py:20: DeprecationWarning: `frame_equal` is deprecated. It has been renamed to `equals`.
  assert df.frame_equal(deserialise(serialise(df)))
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[3], line 21
     19 df = pl.DataFrame(data, schema=['A', 'B'])
     20 assert df.frame_equal(deserialise(serialise(df)))
---> 21 assert df.frame_equal(deserialise(serialise(df, False), False))

Cell In[3], line 15, in deserialise(data, use_pyarrow)
     13 with BytesIO() as file:
     14     file.write(data)
---> 15     df = pl.read_parquet(file,use_pyarrow = use_pyarrow)
     16     return df

File [~/micromamba/envs/test/lib/python3.10/site-packages/polars/_utils/deprecation.py:135](http://127.0.0.1:8888/home/linziy/micromamba/envs/test/lib/python3.10/site-packages/polars/_utils/deprecation.py#line=134), in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    130 @wraps(function)
    131 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    132     _rename_keyword_argument(
    133         old_name, new_name, kwargs, function.__name__, version
    134     )
--> 135     return function(*args, **kwargs)

File [~/micromamba/envs/test/lib/python3.10/site-packages/polars/_utils/deprecation.py:135](http://127.0.0.1:8888/home/linziy/micromamba/envs/test/lib/python3.10/site-packages/polars/_utils/deprecation.py#line=134), in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    130 @wraps(function)
    131 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    132     _rename_keyword_argument(
    133         old_name, new_name, kwargs, function.__name__, version
    134     )
--> 135     return function(*args, **kwargs)

File [~/micromamba/envs/test/lib/python3.10/site-packages/polars/io/parquet/functions.py:167](http://127.0.0.1:8888/home/linziy/micromamba/envs/test/lib/python3.10/site-packages/polars/io/parquet/functions.py#line=166), in read_parquet(source, columns, n_rows, row_index_name, row_index_offset, parallel, use_statistics, hive_partitioning, glob, hive_schema, rechunk, low_memory, storage_options, retries, use_pyarrow, pyarrow_options, memory_map)
    165 # Read file and bytes inputs using `read_parquet`
    166 elif isinstance(source, (io.IOBase, bytes)):
--> 167     return _read_parquet_binary(
    168         source,
    169         columns=columns,
    170         n_rows=n_rows,
    171         parallel=parallel,
    172         row_index_name=row_index_name,
    173         row_index_offset=row_index_offset,
    174         low_memory=low_memory,
    175         use_statistics=use_statistics,
    176         rechunk=rechunk,
    177     )
    179 # For other inputs, defer to `scan_parquet`
    180 lf = scan_parquet(
    181     source,  # type: ignore[arg-type]
    182     n_rows=n_rows,
   (...)
    194     glob=glob,
    195 )

File [~/micromamba/envs/test/lib/python3.10/site-packages/polars/io/parquet/functions.py:250](http://127.0.0.1:8888/home/linziy/micromamba/envs/test/lib/python3.10/site-packages/polars/io/parquet/functions.py#line=249), in _read_parquet_binary(source, columns, n_rows, row_index_name, row_index_offset, parallel, use_statistics, rechunk, low_memory)
    247 row_index = parse_row_index_args(row_index_name, row_index_offset)
    249 with prepare_file_arg(source) as source_prep:
--> 250     pydf = PyDataFrame.read_parquet(
    251         source_prep,
    252         columns=columns,
    253         projection=projection,
    254         n_rows=n_rows,
    255         row_index=row_index,
    256         parallel=parallel,
    257         use_statistics=use_statistics,
    258         rechunk=rechunk,
    259         low_memory=low_memory,
    260     )
    261 return wrap_df(pydf)

ComputeError: parquet: File out of specification: A parquet file must contain a header and footer with at least 12 bytes

### Expected behavior

```python
def serialise(df : pl.DataFrame, use_pyarrow = True) -> bytes:
    with BytesIO() as file:
        df.write_parquet(file, use_pyarrow=use_pyarrow)
        file.seek(0)
        return file.read()

def deserialise(data : bytes, use_pyarrow = True) -> pl.DataFrame:
    with BytesIO() as file:
        file.write(data)
        df = pl.read_parquet(file,use_pyarrow = use_pyarrow)
        return df
```

above function does nothing but serialise data into parquets bytes in-memory,

Hence, I would expect parquets bytes serialised via rust-arrow could be at-least deserialised via polars with rust-implementation of arrow.

It is quite confusing that if I create the parquet file via polars-arrow to a real location (as the example I showed above), I can deserialise it via both pyarrow or polars-arrow...

### Installed versions

--------Version info---------
Polars:               0.20.26
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.5.8
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

This issue also happened in lower version, in our production environment, we use polars 0.18.4 and python 3.7.9

**Comment by ritchie46** [comment]
You read the file from the end. You must reset the file pointer:

```
file.seek(0)
```

**Comment by linlol** [comment]
@ritchie46 thanks a lot!

Will check why it works for pyarrow then...

**Comment by linlol** [comment]
Hello @ritchie46 , honestly I still don't understand why pyarrow and polars-arrow implementation behaves differently here...

https://github.com/pola-rs/polars/blob/d5447509278da0e1892e4ce038df0a18656dbda4/py-polars/polars/io/_utils.py#L106

Looks like before arrow parses parquet object, it would pre-handle the data-source in helping function **prepare_file_arg** and there is a specific handle for io.BytesIO object here https://github.com/pola-rs/polars/blob/main/py-polars/polars/io/_utils.py#L172

Would you think it is a good idea to add a few patch here, e.g. add a file.seek(0) operation to make the behaviour consistent?
