### ISSUE TITLE
Add circular shift

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#16322]
I found myself needing a circular shift, but there is none built in to Polars. I used the following, which works fine, but it would be nice to have this built in.

```python
df = pl.DataFrame(dict(a=range(1, 10)))

df.with_columns(
    b = pl.when(
        pl.col("a").shift(3).is_null()
    )
    .then(
        pl.col("a").shift(-1 * (pl.len() - 3))
    )
    .otherwise(
        pl.col("a").shift(3)
    )
)
```

(However, issue #16321 can lead to incorrect results.)

**Comment by CameronBieganek** [comment]
xref: https://stackoverflow.com/questions/78503523/circular-shift-a-column-in-a-polars-dataframe/78507793

**Comment by stinodego** [comment]
I don't think it's worth adding this. Since apparently it's quite easily to write a custom implementation, this would be a good candidate for a cookbook:
https://github.com/pola-rs/polars/issues/13064

**Comment by mcrumiller** [comment]
For when someone wants to add to the cookbook, here is a very simple implementation:

```python
import polars as pl

def circshift(s, period):
    """Circularly shfit a Series."""
    sp = (-period) % s.len()  # slice point
    return s.slice(sp).append(s.slice(0, sp))

s = pl.arange(1, 6, eager=True)
circshift(s, 2)
# shape: (5,)
# Series: 'literal' [i64]
# [
#         4
#         5
#         1
#         2
#         3
# ]

circshift(s, -2)
# shape: (5,)
# Series: 'literal' [i64]
# [
#         3
#         4
#         5
#         1
#         2
# ]
```
