### ISSUE TITLE
`scan_csv` skips data rows when scanning lists of CSV files with comments

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#16327]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

lst = [
    """\
# comment
a
b
c
""",
    """\
a
b
c
""",
]

get_path = ".env/data/{}.csv".format
for i, x in enumerate(lst):
    with open(get_path(i), "w") as f:
        f.write(x)

lf = pl.scan_csv(get_path("*"), comment_prefix="#")
print(f"{lf.explain() = !s}")
print(f"{lf.collect() = }")
print(f"{pl.__version__ = }")
```
Outputs
```python
lf.explain() = 
  Csv SCAN 2 files: first file: .env/data/0.csv
  PROJECT */1 COLUMNS
Traceback (most recent call last):
  File "/Users/nxs/git/polars/.env/x.py", line 81, in <module>
    print(f"{lf.collect() = }")
             ^^^^^^^^^^^^
  File "/Users/nxs/git/polars/py-polars/polars/lazyframe/frame.py", line 1816, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ShapeError: unable to vstack, column names don't match: "a" and "b"
```

### Issue description

Previously we read lists of CSV files by converting it into a `Union`, meaning that every CSV file had its own set of `CsvReadOptions`. However, after introducing a native CSV file list reader (https://github.com/pola-rs/polars/pull/16180), they now share the same set of options. This is an issue as during schema inference, the `skip_rows` parameter is modified to skip the comment rows of the first file, but this setting is then applied across all CSV files.

### Expected behavior

The files are correctly read in `0.20.25` as that was still dispatching to UnionExec:

```python
lf.explain() = UNION
  PLAN 0:

      Csv SCAN .env/data/0.csv
      PROJECT */1 COLUMNS
  PLAN 1:

      Csv SCAN .env/data/1.csv
      PROJECT */1 COLUMNS
END UNION
lf.collect() = shape: (4, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
│ b   │
│ c   │
│ b   │
│ c   │
└─────┘
pl.__version__ = '0.20.25'
```

### Installed versions

`0.20.26` and `main`

**Comment by ritchie46** [comment]
Hmm... What if we don't mutate the `skip_rows` during inference. We should still recognize comments right?
