### ISSUE TITLE
Add `read_delta_changefeed` (change data feed)

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#16338]
### Description

@stinodego with python v0.17.3, a change data feed reader got added for deltalake, are you ok with me adding a new method:

`pl.read_delta_cdf()`

Essentially it would just be a shortcut for `pl.DataFrame(dt.load_cdf(starting_version=<>, ending_version=<>)`
https://github.com/delta-io/delta-rs/blob/11ab3f68493d32c620f76c8e33671e626d8f0dde/python/deltalake/table.py#L687-L688

**Comment by alexander-beedie** [comment]
Without taking a position on whether it should be there or not, how about `read_delta_changes` as the name? "cdf" doesn't seem very descriptive 🤔

**Comment by alexander-beedie** [comment]
> True, you would need to know delta to know it. How about `read_delta_changefeed`?

Yup, that would work for me ;)

**Comment by stinodego** [comment]
I'm not a big fan of expanding our API surface for third-party integrations like this. If Delta adds 10 more features, do we add 10 more methods?

Perhaps it's sufficient to add an example to the user guide that shows how to read a changelog into Polars using the `deltalake` package directly?

**Comment by ion-elgreco** [comment]
@stinodego I get your point, but this is probably the last thing. I was thinking of adding it into read/scan_delta but it probably won't work nicely into one api

An example could work yeah!
