### ISSUE TITLE
The WoW Benchmark: Datetime Support

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1633]
I'm checking out the library by giving it the good ol' [wow benchmark](https://www.kaggle.com/mylesoneill/warcraft-avatar-history). It seems like I've hit a block though. 

When I read the data, like so:

```python
import polars as pl

df = pl.read_csv("wowah_data.csv", parse_dates=False)
df.head()
```

The dataframe reads: 

![image](https://user-images.githubusercontent.com/1019791/139557015-8e352de0-b90d-4474-97b8-871b443ca23f.png)

The date-time format is part of life ... when polars reads it though. 

```
df = pl.read_csv("wowah_data.csv", parse_dates=True)
df.head()
```

![image](https://user-images.githubusercontent.com/1019791/139557103-c113652a-5671-46ed-b502-461affab6f00.png)

The format is day-month-year, `"%d-%m-%y"` ... how do I pass that to the reader method? Or how can I cast to a date time?

**Comment by koaning** [comment]
This also does not seem to work. 

```python
df.select([
    pl.col("timestamp").str.strptime(pl.Datetime, fmt="%d-%m-%y %H:%M:%S")
])
```

![image](https://user-images.githubusercontent.com/1019791/139557212-68690118-9efe-45fc-9cb9-ee5ba29d9d6b.png)

**Comment by ritchie46** [comment]
> df.select([
    pl.col("timestamp").str.strptime(pl.Datetime, fmt="%m/%d/%y %H:%M:%S")
])

Yes! And if you use a `with_column` and keep the same name, (by either, doing nothing, using `alias("name")` or using `keep_name()` you will overwrite the column in the dataframe.
