### ISSUE TITLE
Typo in documentation: width and height are interchanged for shape()

### ISSUE THREAD

**Issue by quambene** [pola-rs/polars#1636]
See https://docs.rs/polars/0.17.0/polars/prelude/struct.DataFrame.html#method.shape and https://docs.rs/polars/0.17.0/polars/frame/struct.DataFrame.html#method.shape

Given: "Get (width x height)"

Expected: "Get (height x width)"

**Comment by ritchie46** [comment]
Thanks for the issue report. Would you have time to make a PR for this?

**Comment by quambene** [comment]
Thanks @dandxy89 for submitting PR.

**Comment by ritchie46** [comment]
Fixed in #1641
