### ISSUE TITLE
`.struct.field('*')` StructFieldNotFoundError

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#16373]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'A': [1], 'B': [2]})

df.select(
    (pl.struct('A') - pl.struct('B')).struct.field('*')
) 
# StructFieldNotFoundError: B
```

### Issue description

Just trying out the handy new `.struct.field('*')` syntax.

I may be wrong, but It seems like the above should work? 

Putting it in a new context avoids the error.

```python
(df.select(pl.struct('A') - pl.struct('B'))
   .select(pl.first().struct.field('*'))
) 

# shape: (1, 1)
# ┌─────┐
# │ A   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ -1  │
# └─────┘
```

### Expected behavior

Return just `A` without error.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.27
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by kevinli1993** [comment]
> Putting it in a new context avoids the error.

This behavior is the same as the bug I reported here:  https://github.com/pola-rs/polars/issues/16370. Apparently putting it in a new context does something extra to make this work.

**Comment by cmdlineluser** [comment]
Thanks @kevinli1993 

I think it may be a little different.

In this case it's complaining about `B` - but it shouldn't be trying to extract `B` 

In your case, `list.to_struct()` has an "Unknown" schema which can't be known until the next context. (as I understand things)

```python
>>> df.lazy().with_columns(pl.col("A").list.to_struct("max_width")).schema
OrderedDict([('A', Struct({}))])
```
