### ISSUE TITLE
Add contingency table/ frequency table functionality in .pivot method

### ISSUE THREAD

**Issue by BrandoPolistirolo** [pola-rs/polars#16372]
### Description

Hello, i have been using polars for almost a year now as a data scientist. I often find myself having to produce contingency tables of frequency tables. I always use the .pivot function but I always have to add the margins column and row with the .with_columns method. It would be nice to extend the pivot function to be able to automatically add margins and to be able to specify if the pivot table should be in absolute terms or in term of frequency. 

If this functionality is deemed useful I would gladly like to collaborate to implement it.

Thank you in advance.
Guido Pitoni

**Comment by MarcoGorelli** [comment]
hi @BrandoPolistirolo 

to expedite resolution, could you please show something like:
- i'm starting with this data: ...
- i'd like to obtain this:. ...
- here's the api I'd like to use: ...

**Comment by BrandoPolistirolo** [comment]
Here is a very basic example:

I have this table obtained through pivot operation: 
`rsi_strategy.filter(
    pl.col('Buy_Signal').is_null() == False, 
    pl.col('Sell_Signal').is_null() == False
).group_by('Buy_Signal', 'Sell_Signal').len().pivot(index = 'Buy_Signal',
                                                              columns = 'Sell_Signal', 
                                                              values = 'len').fill_null(0)`

Which gives this table:

Buy_Signal | false | true
-- | -- | --
false | 30852 | 1254
true | 1239 | 0

I would like to specify in the .pivot() function the possibility of returning a contingency table or a frequency table (with row margins and column margins) like the following:

Contingency table:

Buy_Signal | true | false | Row Sum
-- | -- | -- | --
false | 1254 | 30852 | 32106
true | 0 | 1239 | 1239
Column Sum | 1254 | 32091 | 33345


Obtained through this code: 

`# Step 1 returns a pivot table with row margins added, i.e. sum_horizontal column
step_1 = rsi_strategy.filter(
    pl.col('Buy_Signal').is_null() == False, 
    pl.col('Sell_Signal').is_null() == False
).group_by('Buy_Signal', 'Sell_Signal').len().pivot(index = 'Buy_Signal',
                                                              columns = 'Sell_Signal', 
                                                              values = 'len').fill_null(0).with_columns(
        pl.sum_horizontal(pl.all().exclude('Buy_Signal')).alias('Row Sum')
)


# Step 2 computes the column sums row from step 1 dataframe
step_2 = pl.DataFrame().with_columns(
    pl.Series(['Column Sum']).alias('Buy_Signal'),
    pl.Series([step_1['true'].sum()]).alias('true'),
    pl.Series([step_1['false'].sum()]).alias('false'),
    pl.Series([step_1['Row Sum'].sum()]).alias('Row Sum')
)

# use concat to add column sum row.
pl.concat([step_1.with_columns(
    pl.col('Buy_Signal').cast(pl.String)
), step_2.select(step_1.columns)])`

A frequency table would look like the one above but instead of quantitative values it should have the frequencies of the variables or percentages over total. 

As you can see obtaining a contingency table is quite lengthy, but i think it would be a great addition since creating such tables is often required when doing basic analytics on data. The above example can be generalized to an NxN table or an NxK table. The feature that i would like would be a parameter within the pivot funcion like add_margins or contingency = '...' that you can use to specify if you want a contingency table and how you want it (frequency, percentages, absolute values).

Thank you for your reply, i look forward to hearing some feedback.

**Comment by cmdlineluser** [comment]
I was just trying to understand your example so I just reduced it down a bit to make it easier to run:

Your initial pivot:

```python
df = pl.DataFrame({
    'Buy_Signal': [False, None, False, False, True, False, False, True],
    'Sell_Signal': [False, False, True, False, False, False, False, False]
})

(df.drop_nulls(['Buy_Signal', 'Sell_Signal'])
   .group_by('Buy_Signal', 'Sell_Signal', maintain_order=True)
   .len()
   .pivot(index = 'Buy_Signal', columns = 'Sell_Signal', values = 'len')
   .fill_null(0)
)
```

```python
shape: (2, 3)
┌────────────┬───────┬──────┐
│ Buy_Signal ┆ false ┆ true │
│ ---        ┆ ---   ┆ ---  │
│ bool       ┆ i64   ┆ i64  │
╞════════════╪═══════╪══════╡
│ false      ┆ 4     ┆ 1    │
│ true       ┆ 2     ┆ 0    │
└────────────┴───────┴──────┘
```

And you then want to an easier way to add the Row/Column summaries?

```python
(df.drop_nulls(['Buy_Signal', 'Sell_Signal'])
   .group_by('Buy_Signal', 'Sell_Signal', maintain_order=True)
   .len()
   .pivot(index = 'Buy_Signal', columns = 'Sell_Signal', values = 'len')
   .fill_null(0)
   .with_columns( pl.sum_horizontal(pl.exclude('Buy_Signal')).alias('Row Sum') ) # +
   .select(                                                                      # +
       pl.col('Buy_Signal').append(pl.lit('Column Sum')),                        # +
       pl.exclude('Buy_Signal').append(pl.exclude('Buy_Signal').sum())           # +
   )
)
```

```python
shape: (3, 4)
┌────────────┬───────┬──────┬─────────┐
│ Buy_Signal ┆ false ┆ true ┆ Row Sum │
│ ---        ┆ ---   ┆ ---  ┆ ---     │
│ str        ┆ i64   ┆ i64  ┆ i64     │
╞════════════╪═══════╪══════╪═════════╡
│ false      ┆ 4     ┆ 1    ┆ 5       │
│ true       ┆ 2     ┆ 0    ┆ 2       │
│ Column Sum ┆ 6     ┆ 1    ┆ 7       │
└────────────┴───────┴──────┴─────────┘
```

**Comment by BrandoPolistirolo** [comment]
Yes exactly, thank you for writing your code, it is much leaner than mine (i also did not know the .append() feature so thanks for showing it to me). What i would like is a functionality inside the .pivot method to expedite the procedure of generating a contingency table or a frequency table (decimal or percentages)

**Comment by earlev4** [comment]
Hi @BrandoPolistirolo and @cmdlineluser! This would be a very nice addition!  I think pandas has a similar (yet limited) functionality with `pivot_table` using the `margins` and `margins_name` parameters. I look forward to seeing the Polars implementation. Thanks so much!

**Comment by MarcoGorelli** [comment]
thanks for the request!

per some discussion, this doesn't really fit into the scope of Polars, and you probably want to use a tool built on top of Polars to display these aggregations
