### ISSUE TITLE
Ergonomic improvements to `struct.with_fields`

### ISSUE THREAD

**Issue by KDruzhkin** [pola-rs/polars#16395]
### Description

A follow-up on #16082 and #16305.

## TL;DR

Can we have `pl.field("field_name")` meaning `pl.col(<column from context>).field("field_name")`?

## Motivation

Now we have this syntax:

```python
pl.col("col_name").struct.with_fields(
    pl.col("col_name").struct.field("field_name").sqrt()
)
```

The method `.with_fields` accepts any expression. But usually people would like to access fields **from the same struct**.

The proposal simplifies the common case to:

```python
pl.col("col_name").struct.with_fields(
    pl.field("field_name").sqrt()
)
```

## Prior art

The expression `pl.element()` is context-dependent, meaning _"elements of **this** list"_.

```python
pl.col("col_name").list.eval(
    pl.element().sqrt()
)
```

**Comment by mcrumiller** [comment]
Alternatively, if someone *did* want to use fields from another struct, perhaps an issue request for `.struct.with_context()`? Although I'm not sure how far Ritchie wants to go with treating structs as miniframes.

**Comment by KDruzhkin** [comment]
Can I close it now (with #16402 merged)?

**Comment by cmdlineluser** [comment]
I think you can.

```python
df = pl.DataFrame({
    "item": [
        {"name": "John", "age": 30, "car": None},
        {"name": "Alice", "age": 65, "car": "Volvo"},
    ]
})

df.select(
    pl.col("item").struct.with_fields(
        pl.field("name").str.to_uppercase()
    )
)

# shape: (2, 1)
# ┌──────────────────────┐
# │ item                 │
# │ ---                  │
# │ struct[3]            │
# ╞══════════════════════╡
# │ {"JOHN",30,null}     │
# │ {"ALICE",65,"Volvo"} │
# └──────────────────────┘
```
