### ISSUE TITLE
Add `pl.col(...).is_not_in(<iterable>)` method

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#16419]
### Description

Feature Request: Add `pl.col(...).is_not_in(<iterable>)` method.

Using the bitwise inverter/negator (`~`) with `.is_in([...])` is a bit easier to miss, easier to screw up order-of-operations, etc. In the same way that there's a `.is_null()` and `.is_not_null()`, I think it would be awesome if there were both `is_in()` and `is_not_in()`. 

Not that this bears much weight, but GitHub Copilot expects it to exist, which suggests it's common in similar/competitor libraries.

**Comment by owenprough-sift** [comment]
Duplicate of "wontfix" #6574, but I would also appreciate having an `is_not_in()` expression.

**Comment by DeflateAwning** [comment]
Darn, well I guess I'll ask again and see if they'll reconsider

**Comment by stinodego** [comment]
We will not add this, see the linked issue.

`is_not_null` is there because it is a (free) represention of the underlying validity buffer. We may remove it when we have sufficiently improve our IR.

**Comment by DeflateAwning** [comment]
Darn, well thanks for the response anyway
