### ISSUE TITLE
Add argument to `df.to_dicts()` and `df.to_dict()` - `maintain_column_order: bool`

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#16414]
### Description

It appears that `df.to_dict()` and to_dicts don't maintain the column order of the keys in the dictionary/dictionaries. This is presumably an optimization.

It would be helpful if you could enforce maintaining the order from the dataframe with an argument.

**Comment by cmdlineluser** [comment]
Do you happen to have an example?

Anything I've tried so far results in a dict with the same order.

**Comment by alexander-beedie** [comment]
Likewise; so far I haven't been able to reproduce - and looking at the code it does look like it should always return in-order keys. Definitely need a reproducible example to see if there's an edge-case 🤔

**Comment by DeflateAwning** [comment]
Darn, thanks for checking! Sorry to waste your time.

The actual issue was in the way Pytest compares dicts by taking them out-of-order: https://stackoverflow.com/questions/70023936/pytest-dict-equality-preserving-order-and-nice-diff-output-python-3-7

That's totally my bad; sorry for not vetting the issue better before opening it here.
