### ISSUE TITLE
Rust to_ndarray does not cast Null in f64 column to NaN

### ISSUE THREAD

**Issue by abstractqqq** [pola-rs/polars#16423]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

    let vec:Vec<Option<f64>> = vec![Some(1.0), Some(2.0), None];
    let series = Float64Chunked::from_iter_options("test", vec.into_iter());
    let df = df!("test" => series).unwrap();
    let matrix = df.to_ndarray::<Float64Type>(IndexOrder::C).unwrap(); // will panic
```

### Log output

```shell
thread 'main' panicked at src/main.rs:8:62:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("creation of ndarray with null values is not supported"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

The doc says it should cast Null to NaN automatically

### Expected behavior

Should cast

### Installed versions

<details>
polars = {version="0.40.0", features=["ndarray"]}

</details>

**Comment by ritchie46** [comment]
Yes, this is a regression. It is fixed in  `main`. You can `fill_null` for now. Want to accumulate some changes before we can release agina.
