### ISSUE TITLE
.hash() return Int64 instead of UInt64

### ISSUE THREAD

**Issue by Mintactus** [pola-rs/polars#16424]
### Description

Some engine like Neo4j GDS requires Int64 for their IDs, UInt64 make it crash, I think UInt64 should stay the default return behavior but having an optional parameter to decide the format for the hash() output would make it more flexible for different engines having different IDs data types.

**Comment by nameexhaustion** [comment]
You can use [Expr.reinterpret](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.reinterpret.html) to cheaply turn it into `Int64`

```python
>>> pl.Series([1], dtype=pl.UInt64)
shape: (1,)
Series: '' [u64]
[
	1
]
>>> pl.Series([1], dtype=pl.UInt64).reinterpret()
shape: (1,)
Series: '' [i64]
[
	1
]
```

**Comment by ritchie46** [comment]
@nameexhaustion examples seems like a solid solution for this. Will close.
