### ISSUE TITLE
Opening large CSV files on some Macs is extremely slow.

### ISSUE THREAD

**Issue by maxim-uvarov** [pola-rs/polars#16438]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I'm sorry, I don't program in Rust, but I still believe that this issue should be created in this repository.

```
> curl https://www.stats.govt.nz/assets/Uploads/New-Zealand-business-demography-statistics/New-Zealand-business-demography-statistics-At-February-2020/Download-data/Geographic-units-by-industry-and-statistical-area-2000-2020-descending-order-CSV.zip -o arch.zip

> unzip arch.zip

> polars-cli -c "select year, count(*) n, sum(geo_count) s from read_csv('Data7602DescendingYearOrder.csv') group by year;"
```

### Log output

```shell
POLARS_VERBOSE=1 dply -c 'csv("./Data7602DescendingYearOrder.csv") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()'
keys/aggregates are not partitionable: running default HASH AGGREGATION
read files in parallel
avg line length: 24.201172
std. dev. line length: 3.781691
initial row estimate: 5089188
no. of chunks: 10 processed by: 10 threads.
shape: (21, 3)
```

### Issue description

Recently, I found that on my Mac (OS X 14.5), a group of Polars-based CLIs - [polars-cli](https://github.com/pola-rs/polars-cli), [dply](https://github.com/vincev/dply-rs?tab=readme-ov-file), and Nushell's [polars plugin](https://www.nushell.sh/book/dataframes.html#working-with-dataframes), aggregate a quite simple 123mb [CSV file](https://www.stats.govt.nz/assets/Uploads/New-Zealand-business-demography-statistics/New-Zealand-business-demography-statistics-At-February-2020/Download-data/Geographic-units-by-industry-and-statistical-area-2000-2020-descending-order-CSV.zip) with a simple group-by operation extremely slowly.

```
> head --lines 5 Data7602DescendingYearOrder.csv
anzsic06,Area,year,geo_count,ec_count
A,A100100,2000,96,130
A,A100200,2000,198,110
A,A100300,2000,42,25
A,A100400,2000,66,40
```

This group-by operation's timing is 13 seconds in the current run (and those timings have quite big variance).

```
> { /usr/bin/time -l dply -c 'csv("./Data7602DescendingYearOrder.csv") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()'; } 2>&1 >/dev/null
13.23 real         0.39 user        56.10 sys
521879552  maximum resident set size
39491  page reclaims
34  page faults
0  voluntary context switches
10706  involuntary context switches
40526252575  instructions retired
172262438127  cycles elapsed
350489216  peak memory footprint
```

@vincev suggested trying other formats, and it turned out that `.parquet` and `.json` files open as usual lightning fast, but only CSV files open slowly in all the listed apps.

When I converted the CSV to JSON, the file size for the whole dataset will be 4 times bigger.

```
> dply -c 'csv("./Data7602DescendingYearOrder.csv") | json("data.json")'
```

But the speed of all the aggregations will be only 0.62 seconds.

```
> { /usr/bin/time dply -c 'json("data.json") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()'; } 2>&1 >/dev/null
0.62 real         5.10 user         0.11 sys
```

@fdncred has repeated my tests on his Mac and came to similar results with very slow CSV opening.

Yet, on my machine, the Python script that uses `polars` goes with no problem lightning fast.

```python
import polars as pl

df = pl.read_csv("Data7602DescendingYearOrder.csv")
res = df.groupby("year").agg(pl.col("geo_count").sum())
print(res)
```

Moreover, in a fresh new virtual machine inside the same macOS, the listed CLI applications run quickly with no problem.

Also, other users tested Windows or other Macs (including 14.5) and found no problem.

I used [cargo instruments](https://github.com/cmyr/cargo-instruments) to make a trace of the application run, and @devyn kindly decided to take a look at my traces. I provide here his words from the Nushell chat verbatim:

> So far it looks like all of the slowness comes from growing vecs in the CSV parser. The CSV parser does not appear to be streaming; it loads everything in parallel all at once. If it's creating one huge Vec, that could be expensive as macOS has to find a way to give you all of that contiguous memory. Some of the later calls seem to take up to about a second on @maxim_uvarov's trace. That's a lot for memory mapping.

> I still have no idea why it's a problem on 14.5 and not 14.4.
> Or rather, a problem for your system but not mine.
> We don't know about the VM, I guess.
> For reference:

![image](https://github.com/pola-rs/polars/assets/4896754/b5e5f74a-e341-46c5-a24a-0c535d362e98)
![image](https://github.com/pola-rs/polars/assets/4896754/d7b4bb6b-642c-496f-9db2-bca9fe09441d)

> These are the problem; they're calls to mach_msg2_trap with the context of growing a vec, so definitely memory mapping from the kernel (allocation).
> My max is 7.81 ms, from the system with the bug is 2.25 s (!).
> & actually I noticed that the biggest one is near the beginning, not near the end.
> That's kind of interesting.
> Not what I would have expected, so idk.
> Maybe this can help the Polars folks though.

Though! If I remove the sum operation from group by timings drops on with the same datset in CSV:
```
❯ time dply -c 'csv("./data.csv") | group_by(year) | summarize(count = n()) | show()'
        0.54 real         0.30 user         0.85 sys
```

We have quite a big conversation here with various tests and other hypothesis checks. https://github.com/vincev/dply-rs/issues/65

So, dear maintainers, maybe you'll have any ideas on what is happening and if it is possible to fix it.

Please, let me know If more traces are needed 

### Expected behavior

I expect Polars to open CSV files quickly.

### Installed versions

I provide here dependencies from `dply` cargo toml:

```
default-features = false
features = ["cross_join", "csv", "dtype-full", "fmt", "is_in", "json", "lazy", "parquet", "semi_anti_join", "strings", "timezones"]
version = "0.40.0"
```

**Comment by ritchie46** [comment]
Are you comparing different tools with eachother? E.g. nushell vs python Polars?

**Comment by fdncred** [comment]
What we're really trying to figure out is why CSV loading has terribly inconsistent performance on MacOS 14.5. 

We initially noticed this on nushell. So, we wanted to rule out nushell so we went to another polars tool, dply-rs. We see the same thing there. Then we went to polars-cli, and we see the same thing there.

On Windows and Linux, the performance is at least somewhat consistent. On MacOS 14.5 specifically its inconsistent. 14.4 seems ok, 14.2 seems ok.

This is using nushell and dply to get perf numbers.
MBP M1Max 32gb ram 1TB ssd (large difference between min and max and min and median)
```nushell
❯ 1..10 | each {timeit {dply -c 'csv("./Data7602DescendingYearOrder.csv") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null}} | {max: ($in | math max), min: ($in | math min), median: ($in | math median)}
╭────────┬──────────────────────────────╮
│ max    │ 1min 16sec 684ms 528µs 250ns │
│ min    │ 553ms 545µs 500ns            │
│ median │ 1sec 784ms 562µs 375ns       │
╰────────┴──────────────────────────────╯
```
Windows 10 16GB ram 1TB ssd (clunky and old but consistent)
```nushell
❯ 1..100 | each {timeit {dply -c 'csv("./Data7602DescendingYearOrder.csv") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null}} | {max: ($in | math max), min: ($in | math min), median: ($in | math median)}
╭────────┬───────────────────╮
│ max    │ 388ms 375µs 700ns │
│ min    │ 264ms 181µs 400ns │
│ median │ 286ms 849µs 200ns │
╰────────┴───────────────────╯
```

**Comment by devyn** [comment]
To add a little more detail (I took the screenshots): it looks like polars tries to use some large `Vec`s to store the data from the CSV. On macOS, this seems to have been fine in the past, but suddenly (for some people? maybe connected to macOS 14.5?) this reallocation of huge `Vec`s is very slow, and it's not clear why.

The behaviour seems to be triggered by using a group by with an aggregation. There are some examples of this happening with `GROUP BY` in polars-cli as well:

```sql
select year, count(*) n, sum(geo_count) s from read_csv('Data7602DescendingYearOrder.csv') group by year
```

This triggers the bug when `sum()` is used.

([link to comment](https://github.com/vincev/dply-rs/issues/65#issuecomment-2126036094))

So far it appears that it has to be the combination of these factors:

- macOS 14.5 (maybe all Apple Silicon, too)
- using a group by
- using an aggregation like `sum()`
- using the CSV format (other formats don't trigger it)

**Comment by orlp** [comment]
It sounds like this is a MacOS 14.5 issue. While ideally we are creating more reasonable chunk sizes for all readers, ultimately if on one platform the memory allocator suddenly becomes hundreds of times slower from 14.4 -> 14.5 for larger sizes, that's on Apple to fix.

**Comment by maxim-uvarov** [comment]
> It sounds like this is a MacOS 14.5 issue. While ideally we are creating more reasonable chunk sizes for all readers, ultimately if on one platform the memory allocator suddenly becomes hundreds of times slower from 14.4 -> 14.5 for larger sizes while there is no regression on other systems, that's on Apple to fix.

I agree that it looks like Apple should fix the issue. I already filed an issue through `feedback assistant`. It would be good if more people affected users send their reports to Apple too

**Comment by maxim-uvarov** [comment]
To summarize the thread, I want to remind that the problem isn't reproduced on every OSX 14.5, but only on a couple of them so far. 

Additionally, I want to mention again that even on affected Macs, reading the same dataset but in JSON format is faster than reading it from CSV.

Can we leave this issue open to allow other users with the same problem to share their findings?

**Comment by ritchie46** [comment]
Can you reproduce this with the latest python polars?

**Comment by maxim-uvarov** [comment]
> Can you reproduce this with the latest python polars?

@ritchie46 Python Polars didn't have any problems before. The issue is only in CLI apps (polars-cli, dply, and the Nushell's Polars plugin).

But just in case it is important, I upgraded polars to polars-0.20.29-cp38-abi3-macosx_11_0_arm64.whl

and this script runs in 1.3sec
```python
import pandas as pd

df = pd.read_csv("Data7602DescendingYearOrder.csv")
res = df.groupby("year")["geo_count"].sum()
print(res)
```

```nu
❯ 1..50 | each {timeit {python ./load.py | complete | null}} | {median: ($in | math median), min: ($in | math min), max: ($in | math max), stddev: ($in | into int | into float | math stddev | into int | $'($in)ns' | into duration)}
╭────────┬────────────────────────╮
│ median │ 1sec 339ms 909µs 812ns │
│ min    │ 1sec 317ms 9µs 667ns   │
│ max    │ 1sec 364ms 125µs 375ns │
│ stddev │ 10ms 112µs 722ns       │
╰────────┴────────────────────────╯
```

**Comment by ritchie46** [comment]
If the problems isn't in Python Polars it is resolved in `main`. I don't know which versions are used by NuShell or Dply.

For polars-cli, I think we must update that version and activate the `jemalloc` allocator for MacOs as well.

**Comment by maxim-uvarov** [comment]
@ritchie46 this is from dply's `Cargo.lock`, that I tested and that has the performance issue

```
default-features = false
features = ["cross_join", "csv", "dtype-full", "fmt", "is_in", "json", "lazy", "parquet", "semi_anti_join", "strings", "timezones"]
version = "0.40.0"
```

**Comment by ritchie46** [comment]
Where is `dply` located?

**Comment by maxim-uvarov** [comment]
@ritchie46 https://github.com/vincev/dply-rs?tab=readme-ov-file

**Comment by ritchie46** [comment]
I see they run on the default allocator. Setting `jemalloc` on macos might resolve it. Further if performance is important they should consider activating `simd`, `performant` and maybe compiling binaries on a nightly compiler with `avx` features activated.

**Comment by maxim-uvarov** [comment]
@ritchie46 thank you so much!!! I'll report our findings here

**Comment by ritchie46** [comment]
For reference:

Here are the features we activate for MacOs:

https://github.com/pola-rs/polars/blob/019dfe87b28afa51a74fc87ebbccb354fd81b53a/.github/workflows/release-python.yml#L137

Together with the jemalloc allocator for linux and macos.

**Comment by maxim-uvarov** [comment]
@ritchie46 Thank you so much! You are truly a hero of our time and are setting an example for others!

adding [jemalloc](https://github.com/vincev/dply-rs/commit/7030cf0c76888be0c891e70fc1d6a1b02fceaba7) solved my issue.

```
> 1..100 | each {timeit {dply -c 'csv("./data.csv") | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null}} | {median: ($in | math median), min: ($in | math min), max: ($in | math max), stddev: ($in | into int | into float | math stddev | into int | $'($in).ns' | into duration --unit sec)}
╭────────┬──────────────────╮
│ median │ 75ms 471µs 521ns │
│ min    │ 71ms 384µs 250ns │
│ max    │ 85ms 949µs 625ns │
│ stddev │ 2ms 635µs 56ns   │
╰────────┴──────────────────╯
```

**Comment by fdncred** [comment]
Just to add metrics from another mac m1max system. my max is still quite a bit different but min is real close to median.
```nushell
❯ 1..100 | each {timeit {dply -c 'csv("./data.csv") | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null}} | {median: ($in | math median), min: ($in | math min), max: ($in | math max), stddev: ($in | into int | into float | math stddev | into int | $'($in).ns' | into duration --unit sec)}
╭────────┬───────────────────╮
│ median │ 76ms 910µs 958ns  │
│ min    │ 73ms 173µs 541ns  │
│ max    │ 754ms 991µs 458ns │
│ stddev │ 67ms 490µs 188ns  │
╰────────┴───────────────────╯
```
and with measuring a little different and here max isn't quite as far from mean.
```nushell
❯ bench { dply -c 'csv("./data.csv") | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null } -n 100
╭───────┬──────────────────╮
│ mean  │ 78ms 384µs 553ns │
│ min   │ 72ms 640µs 208ns │
│ max   │ 119ms 666µs 83ns │
│ std   │ 8ms 59µs 756ns   │
│ times │ [list 100 items] │
╰───────┴──────────────────╯
```
