### ISSUE TITLE
Schema of `LazyFrame.with_context` does not match result of collect

### ISSUE THREAD

**Issue by wence-** [pola-rs/polars#16444]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df1 = pl.LazyFrame({"a": [1]})
df2 = pl.LazyFrame({"b": [1]})

q = df1.with_context(df2)

assert q.schema == q.collect().schema # False
```

### Log output

```shell
run ExternalContext
```

### Issue description

If the top node in a logical plan is an `ExtContext` node, then its schema is not the same as the one obtained when collecting the equivalent expression.

### Expected behavior

AIUI, `with_context` is used for introducing new dataframes (and their columns) into an expression where one can subsequently refer to the columns in the contexts. However, if we don't refer to columns in the `contexts`, then those don't appear in the final result.

Should I just avoid `with_context` in favour of horizontal concatenation + column projection?

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.27
Index type:           UInt32
Platform:             Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  1.0.0
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.17.4
fastexcel:            0.10.4
fsspec:               2024.5.0
gevent:               24.2.1
hvplot:               0.10.0
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           2.0.30
torch:                2.3.0.post300
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by ritchie46** [comment]
> Should I just avoid with_context in favour of horizontal concatenation + column projection?

Yes! I am want to deprecate and remove `with_context`. It is hacky and buggy design.

**Comment by wence-** [comment]
Great, happy to close this as WONTFIX, and I will not implement `ExtContext` handlers in my gpu executor.
