### ISSUE TITLE
Use more appropriate error variants in various places across the API

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16440]
We often use `ComputeError` as a default, but we have a bunch of different error types available. Sometimes using a different error type is more appropriate, such as a `DuplicateError` or `SchemaError`.

On the Python side, there is also the occasional `ValueError` that should be a `TypeError` and similar.

**Please comment here with any errors that you know/feel are incorrect** (ideally include a code example that triggers the error), and I will update https://github.com/pola-rs/polars/pull/15030 accordingly. Then this can be updated in one breaking PR.

**Comment by s-banach** [comment]
Can you tell me how to import exceptions in a way the type-checker will understand?
I guess they're imported from polars.polars, but the type checker is greyed-out on polars.polars.

**Comment by stinodego** [comment]
> Can you tell me how to import exceptions in a way the type-checker will understand? I guess they're imported from polars.polars, but the type checker is greyed-out on polars.polars.

They are available on top-level, so you can use `pl.ComputeError`. Or you can `from polars.exceptions import ComputeError` and then use it.
