### ISSUE TITLE
Example of `.over()` 900x slower than group_by.agg.join (and over 50x slower than pandas)

### ISSUE THREAD

**Issue by kevinli1993** [pola-rs/polars#16457]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# This does not happen with all input dataframes.  
# I managed to produce a parquet file showcasing this behavior. 
# The file `weird2.parquet` is attached: https://github.com/pola-rs/polars/files/15424892/weird2.parquet.zip
ds = pl.read_parquet("weird2.parquet")


# This takes around 4 minutes to compute (!!)
print(ds.select(pl.col("label").n_unique().over("date", "ident")))

# The equivalent computation here takes around 0.3 seconds.
ads = ds.group_by("date", "ident").agg(pl.col("label").n_unique().alias("label"))
print(ds.join(ads, how='left', on=('date', 'ident')).select("label_right"))
```

### Log output

```shell
(no stderr)
```

### Issue description

I suspect the bug lies on the Rust side, as changing the column `ident` to something else will make the query go fast again (as in, 900x faster). 

It is not clear why this particular input dataframe is so slow.

### Expected behavior

The first call should not take around 4 minutes, something strange is going on with how polars is handling this data. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.29
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.12.3 (main, Apr 12 2024, 17:16:04) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

It seems to be specific to `n_unique()`?

If I use `.unique().len()` instead, its runs as fast as the others.

**Comment by kevinli1993** [comment]
Interesting!

This happened in the middle of my data pipeline (e.g. not reading from a parquet file).  So the pattern is 

```
ds = pl.read_parquet(....)

(
    ds
    .lazy()
    .with_columns(...)
    .join(....)
    .with_columns(...)
    .with_columns(...) # adding this line suddenly makes the collect() call slow!
    .collect()
)
```
In particular, there is no place in the pipeline to call `.rechunk()`! (e.g. LazyFrames have no `.rechunk()`)

(It seems this behavior is not particular to `n_unique()` either; other functions could trigger it as well.)

**Comment by orlp** [comment]
@kszlim  I marked your comment as spam not because it is irrelevant but because it made the issue unreadable to scroll through its pages and pages of JSON. Please post that as an attachment file or a link to a gist or similar.

Regarding this snippet:
```python
# This does not happen with all input dataframes.  
# I managed to produce a parquet file showcasing this behavior. 
# The file `weird2.parquet` is attached: https://github.com/pola-rs/polars/files/15424892/weird2.parquet.zip
ds = pl.read_parquet("weird2.parquet")

# This takes around 4 minutes to compute (!!)
print(ds.select(pl.col("label").n_unique().over("date", "ident")))
```
I can't reproduce on 0.20.28 on Apple M1 (query finishes instantly), but can on 0.20.29 so it's a very recent regression.

**Comment by PaulRudin** [comment]
Just to add - I seem to have hit this with `.over()` using one of `rolling_mean`, `len`, `shift` or `rank("ordinal")` - not sure which yet.

**Comment by orlp** [comment]
The problem is that we were rechunking the entire data for each group in the aggregation. This wasn't exposed before because in the past we always rechunked by default when reading a parquet file.
