### ISSUE TITLE
Add `Expr.list.map_elements(func)` to perform a custom function on every element in a list

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#16452]
### Description

Add `Expr.list.map_elements(func)` to perform a custom function on every element in a list

**Comment by cmdlineluser** [comment]
It is accessible via `list.eval()`

```python
s = pl.Series([[1, 2, 3]])

s.list.eval(   
    pl.element().map_elements(lambda n: 
        f"func({n + 1})", 
        return_dtype=pl.String
    )
)

# shape: (1,)
# Series: '' [list[str]]
# [
# 	["func(2)", "func(3)", "func(4)"]
# ]
```

(But probably a performance destroyer.)

**Comment by DeflateAwning** [comment]
Would you consider adding it as its own method? Would make it a bit cleaner imo

**Comment by MarcoGorelli** [comment]
thanks for the request!

per some discussion, this is rejected, you can use `eval` and `pl.element` - this is already going to be very inefficient and so doesn't warrant its own method

**Comment by dhimmel** [comment]
In python with polars 1.17.1, I'm not able to get the above approach to work when trying to do a udf on each struct element:

```py
import polars as pl

def my_simple_sum(a: int, b: int) -> int:
    # assume this function cannot be done in native polars and I don't care about efficiency
    return a + b

df = pl.DataFrame(
    {
        "list_of_struct_col": [
            [{"a": 1, "b": 2}],
            [{"a": 3, "b": 4}, {"a": 5, "b": 6}],
        ]
    }
)

df.with_columns(
    pl.col("list_of_struct_col")
    .list.eval(
        pl.element().map_elements(
            lambda x: my_simple_sum(
                a=x.struct.field("a"),
                b=x.struct.field("b"),
            ),
            return_dtype=pl.Int64,
        ),
        )
    .alias("list_of_int_col"),
)
```

**Comment by cmdlineluser** [comment]
`map_elements` has an issue with exceptions, which is why you didn't get an error:

- https://github.com/pola-rs/polars/issues/19315
