### ISSUE TITLE
dead kernel ... why?

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1646]
I have two `with_columns`-style methods. 

## Option A 

```python
.with_columns([
    pl.col("new_session_mark").cumsum().alias("session")
])
```

## Option B 

Note the `.over()` bit. 

```python
.with_columns([
    pl.col("new_session_mark").cumsum().over("char").alias("session")
])
```

This second option totally breaks. 

![image](https://user-images.githubusercontent.com/1019791/139591864-3765b857-2397-4bbe-94bd-1a6e42af61c5.png)

Would anybody happen to know of a reason why? I can share more info on the dataset if it's appreciated.

**Comment by ritchie46** [comment]
I assume this is a segfault. Have you got a minimal working example to replicate this?

**Comment by koaning** [comment]
I fear it's not minimal. The kernel does when somewhere between `1_000_000` and `10_000_000` rows in the dataset. It's the dataset found [here](https://www.kaggle.com/mylesoneill/warcraft-avatar-history) but I wonder if there's an easier way for me to share bugs with this dataset. 

Something is telling me that I'll be exploring polars a whole bunch with this dataset ... might there be a convenient way for me to host/share the dataset with the polars team?

**Comment by ritchie46** [comment]
I can download that dataset. No problem. If you have the code that produces it, that would be great!

**Comment by koaning** [comment]
Grand! 

This is the main setup. 

```python
import polars as pl

df = pl.read_csv("wowah_data.csv", parse_dates=False, n_threads=10)
df.columns = [c.replace(" ", "") for c in df.columns]
df = df.lazy()

def set_types(dataf):
    return (dataf
            .with_columns([
                 pl.col("timestamp").str.strptime(pl.Datetime, fmt="%m/%d/%y %H:%M:%S"),
                 pl.col("guild") != -1,
             ]))

def sessionize(dataf, threshold=1_000_000):
    return (dataf
             .sort(["char", "timestamp"])
             .with_columns([
                 (pl.col("timestamp").diff().cast(pl.Int64) > threshold).fill_null(True).alias("ts_diff"),
                 (pl.col("char").diff() != 0).fill_null(True).alias("char_diff"),
             ])
             .with_columns([
                 (pl.col("ts_diff") | pl.col("char_diff")).alias("new_session_mark")
             ])
             .with_columns([
                 pl.col("new_session_mark").cumsum().alias("session")
             ]))
```

This is where it breaks: 

```python
# Typically, 10_000_000 breaks on my linux machine.
(df
 .head(10_000_000)
 .pipe(set_types)
 .pipe(sessionize)
 .with_columns([
    pl.col("new_session_mark").cumsum().over("char").alias("session")
 ])
 .collect()
)
```

**Comment by ritchie46** [comment]
How much RAM do you have. I don't its a segfault related issue. I go OOM and my kernel dies. I have 16GB.

**Comment by koaning** [comment]
My Linux machine should have 32Gb. 

Any debug/logging tools that I might attach here?

**Comment by ritchie46** [comment]
Yes, I am digging ATM. I see that this expression is the culprit of the huge amounts of RAM needed: `pl.col("new_session_mark").cumsum().over("char")`. The input data type is a `boolean` and we group over `"char"`. I will do some more research.

**Comment by ritchie46** [comment]
Ah, I think I know what it is. It makes sense. We just create an enormous amount of data.

I removed: `pl.col("new_session_mark").cumsum().over("char")`, and named the resulting dataframe `out`.

If we do an aggregation on `"char"` and compute the `cumsum` and also the number of values in the result of `cumsum` (its a list), we get:

```python
a = (out.groupby('char')
    .agg([
        pl.col("new_session_mark").cumsum(),
        pl.col("new_session_mark").count().alias("list_size")
    ])
)
a
```

```
shape: (34766, 3)
┌───────┬──────────────────┬───────────┐
│ char  ┆ new_session_mark ┆ list_size │
│ ---   ┆ ---              ┆ ---       │
│ i64   ┆ list [u32]       ┆ u32       │
╞═══════╪══════════════════╪═══════════╡
│ 55904 ┆ [1, 1, 1]        ┆ 3         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 84016 ┆ [1, 1]           ┆ 2         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 67040 ┆ [1]              ┆ 1         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 78480 ┆ [1, 1, ... 15]   ┆ 78        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...   ┆ ...              ┆ ...       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 73793 ┆ [1, 1, ... 88]   ┆ 145       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 83105 ┆ [1]              ┆ 1         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 86929 ┆ [1, 2]           ┆ 2         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 30417 ┆ [1, 1, ... 17]   ┆ 164       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 68705 ┆ [1, 1, ... 6]    ┆ 39        │
└───────┴──────────────────┴───────────┘
```

If we look at the average no of values in that list and the max number we get:

```python
a.select([
    pl.col("list_size").mean().alias("mean"),
    pl.col("list_size").max().alias("max")
])
```

```
shape: (1, 2)
┌───────────────────┬───────┐
│ mean              ┆ max   │
│ ---               ┆ ---   │
│ f64               ┆ u32   │
╞═══════════════════╪═══════╡
│ 287.6373468331128 ┆ 40016 │
└───────────────────┴───────┘
```

In a window function. The result of the aggregation is left joined to the original  `DataFrame`. The ones with 10e6 rows. That means only for the data of the `cumsum` column we need ~11GB (+ what is overallocated by the OS).

And we need to create the data structures for the left join + other original data. All in all, quite some memory. If we replace the `cumsum` with something that produces a single value, e.g. a `sum` or a `mean`, then there is no issue.

As it is very easy to create large amounts of data with window functions, I will check if I can drop some data structures earlier to reduce memory pressure.

**Comment by ritchie46** [comment]
@koaning 

As a side note on above. As you already sorted by `"char"`, you can do a `pl.col("new_session_mark").cumsum().over("char").flatten().alias("session")`. This runs on my machine. And what this does is the list value of the groupby operation is flattened/ exploded. And because you groupby over `"char"` AND `"char"` is sorted, you will have the `cumsum` values per `"char"`.

```python
out = (lf
 .head(10_000_000)
 .pipe(set_types)
 .pipe(sessionize)
 .with_columns([
    pl.col("new_session_mark").cumsum().over("char").flatten().alias("session")
 ])
 .collect()
)
print(out.select(["char", "new_session_mark", "session"]))
```

```
shape: (10000000, 3)
┌───────┬──────────────────┬─────────┐
│ char  ┆ new_session_mark ┆ session │
│ ---   ┆ ---              ┆ ---     │
│ i64   ┆ bool             ┆ u32     │
╞═══════╪══════════════════╪═════════╡
│ 7     ┆ true             ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 7     ┆ false            ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 7     ┆ false            ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 7     ┆ false            ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ ...   ┆ ...              ┆ ...     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 88299 ┆ false            ┆ 2       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 88300 ┆ true             ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 88300 ┆ false            ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 88301 ┆ true             ┆ 1       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 88302 ┆ true             ┆ 1       │
└───────┴──────────────────┴─────────┘

```

**Comment by koaning** [comment]
There's a left-join after every window operation?

This is me thinking out loud. I was wondering for this dataset if it was possible to partition the dataset on "char" beforehand. That way, one might be able to prevent any "join"-step data back in later, no?

**Comment by koaning** [comment]
> As you already sorted by "char", you can do a `pl.col("new_session_mark").cumsum().over("char").flatten().alias("session")`

I think, technically, I can also just do this:

```
pl.col("new_session_mark").cumsum().alias("session")
```

This would result in a session id that is still unique per character, it just wouldn't reset at 1 every time a user appears.

**Comment by ritchie46** [comment]
> There's a left-join after every window operation?

If you `flatten` there isn't. Then we can do a cheap explode and add the column to the dataframe. 

But yes, the result of the aggregation needs to be matched back to the original DataFrame. This requires a join. Likely pandas will do the same in `transform` code.

>  I was wondering for this dataset if it was possible to partition the dataset on "char" beforehand. That way, one might be able to prevent any "join"-step data back in later, no?

That's what the grouping does, but then again. That result needs to be matched with the original dataframe somehow.

**Comment by ritchie46** [comment]
> > As you already sorted by "char", you can do a `pl.col("new_session_mark").cumsum().over("char").flatten().alias("session")`
> 
> I think, technically, I can also just do this:
> 
> ```
> pl.col("new_session_mark").cumsum().alias("session")
> ```
> 
> This would result in a session id that is still unique per character, it just wouldn't reset at 1 every time a user appears.

That would definitely be faster!

**Comment by ritchie46** [comment]
I will close this as I think its solved. #1650 also reduces some of the memory pressure.
