### ISSUE TITLE
When reading excel table data, you are advised to freely select the column name or column number to read data

### ISSUE THREAD

**Issue by zhujie110607** [pola-rs/polars#16472]
### Description

使用Polars读取excel表格数据时，只能一次性读取所有的数据，可是有些列并不需要，如果全部读取会非常损耗性能，强烈建议可以像pandas一样可以自由选择所需要的列来读取数据，谢谢

**Comment by ritchie46** [comment]
Eh.. sorry, can you try in English?

**Comment by zhujie110607** [comment]
When using Polars to read excel table data, only all data can be read at one time, but some columns are not needed, if all reading will be very performance loss, it is strongly recommended that you can freely choose the required columns to read data like pandas, thank you
