### ISSUE TITLE
When reading excel table data, allow selection of the column names/indices to read

### ISSUE THREAD

**Issue by zhujie110607** [pola-rs/polars#16473]
### Description

When using Polars to read excel table data, only all data can be read at one time, but some columns are not needed, if all reading will be very performance loss, it is strongly recommended that you can freely choose the required columns to read data like pandas, thank you

**Comment by cmdlineluser** [comment]
You can pass `use_columns` with the calamine engine:

```python
>>> pl.read_excel("random.xlsx", engine="calamine", read_options={"use_columns": "B:D"})
# shape: (3, 3)
# ┌──────────┬──────────┬──────────┐
# │ column_1 ┆ column_2 ┆ column_3 │
# │ ---      ┆ ---      ┆ ---      │
# │ f64      ┆ f64      ┆ f64      │
# ╞══════════╪══════════╪══════════╡
# │ 0.900042 ┆ 0.034829 ┆ 0.110054 │
# │ 0.498876 ┆ 0.94322  ┆ 0.203003 │
# │ 0.432077 ┆ 0.888128 ┆ 0.351812 │
# └──────────┴──────────┴──────────┘
```

- http://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_sheet

**Comment by alexander-beedie** [comment]
Yup, we should expose this as a top-level option; in the meantime you can use the engine-specific `read_options` parameter as suggested by @cmdlineluser (and the advice the use the "calamine" engine is also on-point as it's _extremely_ fast, and will eventually become our new default ;)

**Comment by alexander-beedie** [comment]
FYI: this was closed by https://github.com/pola-rs/polars/pull/17263. Note that we are using the param name "columns" for this functionality, for consistency with the rest of the API.
