### ISSUE TITLE
Add a `pl.sql` method for running SQL commands

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#16503]
### Description

I am a fan of the newly introduced df.sql method, which makes it very user-friendly to run SQL commands.
It would be nice if we could also have a `pl.sql` command.

The advantages would be:
- the command is independent of a specific dataframe
- possible to reference in SQL non-Polars dataframe (example: Pandas, Arrow Table, Arrow dataset, maybe Spark?, etc) without prior conversion to Polars -> the pl.sql method would do the conversion

The second advantage is not necessary for this, but it would be a quality of life improvement.
That would allow a use-case such as:
```python
# Example: I have some legacy code with a pandas_df

import polars as pl

pl.sql("SELECT a, b, SUM(c) AS sum_c FROM pandas_df GROUP BY ALL")
```
A negative aspect I can see is that the code is less explicit about the conversion to the Polars Arrow format, which is important to know especially if it's not a zero-copy. However:
- this could be made explicit in the docs
- there could be a parameter in pl.sql such as allow_conversion for this
- this could be limited to sources where a zero-copy is possible

**Comment by alexander-beedie** [comment]
I was literally about to add this today 😆
