### ISSUE TITLE
`df.group_by(series).agg(...)` fails if df was built using `pl.concat` (ShapeError)

### ISSUE THREAD

**Issue by Elvynzs** [pola-rs/polars#16516]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np

df1 = pl.DataFrame(np.random.randn(500,2))
df2 = pl.DataFrame(np.random.randn(500,2))
gps = pl.Series(name="oo", values=[0]*500 + [1]*500)
df = pl.concat([df1,df2])
df.group_by(gps).sum()
```

### Log output

```shell
estimated unique values: 2
run PARTITIONED HASH AGGREGATION
```

### Issue description

The code raises with message : "ShapeError: series used as keys should have the same length as the DataFrame"

This feels similar to #15354, that I had reported a while ago.

500 is the minimum dataframe length for the code to fail on my computer.

Edit : I have started to look for the version that introduced the issue. The example code starts crashing in version `0.20.26` due to the rechunk parameter being set to `False` by default (https://github.com/pola-rs/polars/pull/16128). However yet to check if it also crashed in older versions when manually setting `pl.concat(..., rechunk=False)` 

These variants do NOT crash :

```python
# Manually add column before aggregating
df1 = pl.DataFrame(np.random.randn(500,2))
df2 = pl.DataFrame(np.random.randn(500,2))
gps = pl.Series(name="oo", values=[0]*500 + [1]*500)
df = pl.concat([df1,df2])
df.with_columns(gps).group_by(pl.col("oo")).sum()
```

```python
# Avoid using pl.concat
df = pl.DataFrame(np.random.randn(1000,2))
gps = pl.Series(name="oo", values=[0]*500 + [1]*500)
df.group_by(gps).sum()
```

```python
# Concat smaller dataframes
df1 = pl.DataFrame(np.random.randn(499,2))
df2 = pl.DataFrame(np.random.randn(499,2))
gps = pl.Series(name="oo", values=[0]*499 + [1]*499).cast(pl.Int64)
df = pl.concat([df1,df2])
df.group_by(gps).sum()
```

### Expected behavior

Expected the code to not crash and to give a similar output as any of the variant that work.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Windows-10-10.0.22000-SP0
Python:               3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
If it helps: I have not been able to reproduce a crash on macOS.

I tried up to `N = 2_500_000` as the length.

**Comment by MarcoGorelli** [comment]
> If it helps: I have not been able to reproduce a crash on macOS.

curious, it reproduces for me on ubuntu (via wsl)
