### ISSUE TITLE
depr: enforce `ignore_nulls` default change in 1.0

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#16513]
I'm just opening an issue about this so it can be added to the 1.0 milestone without it being forgotten

https://github.com/pola-rs/polars/pull/14663

the default for `ignore_nulls` will change from `True` to `False`

---

reasons for enforcing this in 1.0 (as opposed to 2.0):
- as shown in https://github.com/pola-rs/polars/pull/14663/files, the docs originally documented `False` to be the default, even though it was `True`, which suggests an implementation oversight
- this function matches pandas quite closely, and the default there is `ignore_na=False`

**Comment by stinodego** [comment]
This will be closed as part of https://github.com/pola-rs/polars/issues/13525

But keeping it around as an issue just to be sure is fine I guess.
