### ISSUE TITLE
Add decorator to allow user created methods for `Expr`/`Series`/`DataFrame` objects

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1653]
There is a package called `pandas_flavor` which allows the user to extend pandas Series and DataFrames with custom methods or accessors using a decorator. Would it be possible to allow this with polars for `Expr`/`Series`/`DataFrame` objects?

https://github.com/Zsailer/pandas_flavor

I think this would be particularly useful for `Expr` objects.

**Comment by ritchie46** [comment]
@markfairbanks, this would be a python only thing right? Is this a utility that eases composition?

**Comment by markfairbanks** [comment]
> this would be a python only thing right

Yep, this would only be for python.

> Is this a utility that eases composition

pandas_flavor has two options

One option in pandas_flavor is to ease composition. The usage is outlined [here](https://github.com/Zsailer/pandas_flavor#register-accessors).

That way you can access them using

```python
df.my_flavor.do_something()
```

The other option in pandas_flavor (outlined [here](https://github.com/Zsailer/pandas_flavor#register-methods)) allows you to directly add new methods to a pandas data frame.

That way you can access them using:

```python
df.do_something()
```

There are also decorators that allow you to do this for pandas Series. So for polars it'd be useful to be able to do this for Series, Expr, and DataFrame.

**Comment by markfairbanks** [comment]
Some extra context - pandas added [their own way](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#extending-pandas) of doing this to make composition easier. However they didn't add a way to directly add methods.

**Comment by zundertj** [comment]
@markfairbanks : this is fairly easy to create yourself, although it does involve hacking some internals, i.e. might break. 

See https://gist.github.com/zundertj/7965eb260fd8e05d330c28576df744d5

Which allows you to do:

```python
@register_namespace(pl.DataFrame, "myflav")
class MyFlavor:
    def __init__(self, pl_obj):
        self._obj: pl.DataFrame = pl_obj

    def add_cols(self, col1, col2):
        return self._obj[col1] + self._obj[col2]

df = pl.DataFrame({"a": [1, 2], "b": [3, 4]})
df.myflav.add_cols("a", "b")
```

```
shape: (2,)
Series: 'a' [i64]
[
	4
	6
]
```

Registering a method:
```python
@register_method(pl.Series)
def sum_squared(s: pl.Series):
    return s.sum() ** 2

s = pl.Series([1, 2, 3])
s.sum_squared()
```
Gives 36.

You can also patch `pl.Expr`, or really any class:

```python
@register_method(pl.Expr)
def sum_squared(e: pl.Expr):
    return e.sum() ** 2

df.select(pl.col("a").sum_squared())
```
Which also returns 36.

To formalize this, we should implement `_accessors` and `__getattr__` in `Series / DataFrame / Expr`. I'm not sure we do want to support this functionality out of the box, in particular adding methods directly to a class, so without a namespace, makes for confusing code potentially. Maybe a separate package?

**Comment by markfairbanks** [comment]
@zundertj - This is really cool! Thanks for posting this.

> I'm not sure we do want to support this functionality out of the box, in particular adding methods directly to a class, so without a namespace, makes for confusing code potentially.

I agree - I think the ability to add methods is probably a bad idea and shouldn't live in polars. However the ability to add a namespace seems relatively safe and would be pretty useful. I'll use your workaround for now 👍

**Comment by alexander-beedie** [comment]
@ritchie46 let's close this one now, after #5531.
