### ISSUE TITLE
Version 0.20.30 bug

### ISSUE THREAD

**Issue by hieund2** [pola-rs/polars#16537]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I write code to compact many json files with "pl.concat([df, data], how="diagonal_relaxed")", but its got Shape error like image. This happened with polars version 0.20.30. It still work with version 0.20.26.

### Log output

```shell
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Cell In[4], line 27
     25     layer += 1
     26 # print(data)
---> 27 df = pl.concat([df, data], how="diagonal_relaxed")

File ~\AppData\Local\miniconda3\envs\py39\lib\site-packages\polars\functions\eager.py:198, in concat(items, how, rechunk, parallel)
    196     out = wrap_df(plr.concat_df_diagonal(elems))
    197 elif how == "diagonal_relaxed":
--> 198     out = wrap_ldf(
    199         plr.concat_lf_diagonal(
    200             [df.lazy() for df in elems],
    201             rechunk=rechunk,
    202             parallel=parallel,
    203             to_supertypes=True,
    204         )
    205     ).collect(no_optimization=True)
    206 elif how == "horizontal":
    207     out = wrap_df(plr.concat_df_horizontal(elems))

File ~\AppData\Local\miniconda3\envs\py39\lib\site-packages\polars\lazyframe\frame.py:1855, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, background, _eager, **_kwargs)
   1852 # Only for testing purposes atm.
   1853 callback = _kwargs.get("post_opt_callback")
-> 1855 return wrap_df(ldf.collect(callback))

ShapeError: unable to add a column of length 0 to a DataFrame of height 8979
```

### Issue description

![image](https://github.com/pola-rs/polars/assets/93583842/2ee6820f-cd22-485c-9876-361ac1d5f2d3)

### Expected behavior

expected funtion can concat 2 df

### Installed versions

<details>

0.20.30

</details>

**Comment by alexander-beedie** [comment]
Can you provide a minimal working example of the problem? 
If we can't see the data that causes the issue it isn't going to be easy to fix it.

**Comment by hieund2** [comment]
> Can you provide a minimal working example of the problem? If we can't see the data that causes the issue it isn't going to be easy to fix it.
try:
    json_files = [pos_json for pos_json in os.listdir(path_to_json) if pos_json.endswith('.json')]
except FileNotFoundError as fnf:
    print(fnf)
for json_file in json_files:
    print(json_file)
    f = open(os.path.join(path_to_json, json_file),"r", encoding="utf-8")
    jsondata = json.load(f)
    data = pl.DataFrame(jsondata)
    df_info = remove_struct_columns(data, remove_keys)
    layer = 1
    while any([x==pl.Struct for x in df_info.values()]):
        print(f"Json columns in layer {layer}: ", [col_name for col_name,dtype in df_info.items() if dtype==pl.Struct])
        try:
            data=data.unnest([col_name for col_name,dtype in df_info.items() if dtype==pl.Struct], col_suffix= True)
        except Exception as e:
            print(e)
        df_info = remove_struct_columns(data, remove_keys)
        layer += 1
    # print(data)
    df = pl.concat([df, data], how="diagonal_relaxed")

Here is my code, i read many json files to many df with different number of columns, and error catch when i tried to concat 2 df. Error catch on columns with deep nested struct

**Comment by Elvynzs** [comment]
This feels similar to https://github.com/pola-rs/polars/issues/16536 and https://github.com/pola-rs/polars/issues/16516. (ShapeError and concatenating dataframes)

**Comment by ritchie46** [comment]
Do you have `structs` in your dataframe?
