### ISSUE TITLE
ShapeError: filter's length: 155 differs from that of the series: 0

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#16536]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I'm not really sure how to describe this in a way that reproducible. Since upgrading (0.20.26 -> 0.20.30) polars keeps throwing the error 

```
ShapeError: filter's length: 155 differs from that of the series: 0
```

My data comes from postgres via connectorx. There's a json column, if I use `.str.json_decode()` on the json column before performing a filter, the filter operation raises the error above.

I've used the json_decode dtype argument and/or infer_schema_length=None.

The query is:

```
(
    tasks.with_columns(pl.col("schedule").str.json_decode())
    .filter(~pl.col("task_id").is_in(task_history["task_id"]))
)
```

Every row in "schedule" is unique (i.e. has the same schema) and it's a nested json object. 

What's odd is the issue is resolved by either converting the entire `tasks` dataframe to dictionaries and then back to a dataframe using `pl.from_dicts` or writing to parquet and reading back.

So I suspect this is an issue between connectorx 0.3.3 and polars 0.20.30 but I'm not sure what else I can do to help

### Log output

```shell
N/A
```

### Issue description

Query running on data read from postrgres fails but same query on same data that's been written to disk and read back works

### Expected behavior

Query should work

### Installed versions

<details>

```
```

</details>

**Comment by ritchie46** [comment]
Have you got a repro?

**Comment by david-waterworth** [comment]
No sorry, saving the dataframe (to parquet or json) and then reloading it "fixes" the issue otherwise I'd be happy to privately share the data. I can reproduce at will on both my Ubuntu 22.04 workstation and M3 Macbook Pro

If I have time I'll try spinning up a postgres docker image and see if I can create a simpler reproduction.

I also couldn't work our which specific version introduced the issue but it's not present in 0.20.26

**Comment by david-waterworth** [comment]
So I just discovered that

```
df = pl.read_database_uri(...)
df.with_columns(pl.col("status").str.json_decode().filter(pl.col("id")==1)
```

fails with the error above and

```
df = pl.read_database_uri(...)
df.rechunk().with_columns(pl.col("status").str.json_decode().filter(pl.col("id")==1)
```

works - I'm assuming that's why saving/loading also "fixes" it.

**Comment by ritchie46** [comment]
What is the schema? I think if you create a chunked dataframe with the same schema you should be able to create a repro.

**Comment by Elvynzs** [comment]
I think I have an issue that may share similarities with this one : After concatenating dataframes, some operations raise a ShapeError. My issue is also "fixed" by writing the dataframe to parquet and loading back, or by using rechunk.

It may help find a repro : https://github.com/pola-rs/polars/issues/16516

**Comment by david-waterworth** [comment]
@ritchie46 See attached - the dataframe from `df = pl.read_database_uri(...)` contains chunks of size 155 which matches the error message, I wrote out 2 columns using `write_parquet("tasks.parquet", row_group_size=155)` which I assume preserves the chunks.

To reproduce

```
pl.read_parquet("tasks.parquet").filter(~pl.col("task_id").is_in([1]))
```

```
ShapeError: filter's length: 155 differs from that of the series: 0
```

[tasks.parquet.zip](https://github.com/pola-rs/polars/files/15468154/tasks.parquet.zip)

**Comment by cmdlineluser** [comment]
I can reproduce the error with the attached file.

I'm not sure if it is the same issue, but I get a panic trying to rewrite it to disk:

```python
>>> pl.read_parquet("Downloads/tasks.parquet").write_parquet("1.parquet")
thread 'polars-0' panicked at crates/polars-arrow/src/array/struct_/mod.rs:117:52:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children must have an equal number of values.\n                         However, the values at index 7 have a length of 161, which is different from values at index 0, 0."))

```

**Comment by david-waterworth** [comment]
Also note `join` on chunked dataframes is also raising errors, i.e.

```
thread 'polars-9' panicked at crates/polars-ops/src/chunked_array/gather/chunked.rs:84:5:
assertion `left == right` failed: implementation error
  left: 1
 right: 12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ritchie46** [comment]
Got a complete query @david-waterworth ?

**Comment by YVin3D** [comment]
fwiw, for anyone else coming here because of this same error. My issue was that my parquet file was corrupt. I generate it using a separate script and it must have silently crash mid-write.
