### ISSUE TITLE
Allow passing a list of regex selections in `col()`

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1655]
```python
import polars as pl
from polars import col

df = pl.DataFrame({
    "x1": range(3),
    "x2": range(3),
    "y1": range(3),
    "y2": range(3),
    "z": ["a", "a", "b"]
})

# works
df.with_columns([
    col("^x.*$") * 2,
    col("^y.*$") * 2
])

# fails
df.with_columns([
    col(["^x.*$", "^y.*$"]) * 2
])
```

**Comment by ritchie46** [comment]
Regex supports OR, so that's a bit redundant IMO.

**Comment by markfairbanks** [comment]
Yeah - I guess a better example would be mixing different regex selections, or mixing non-regex with regex:

```python
df = pl.DataFrame({
    "x1": range(3),
    "x2": range(3),
    "one_y": range(3),
    "two_y": range(3),
    "z": ["a", "a", "b"]
})

# Mixing regex with non-regex selection
df.with_columns([
    col(["^x.*$", "one_y"]) * 2
])

# Mixing different regex selections
df.with_columns([
    col(["^x.*$", "^*y$"]) * 2
])
```

**Comment by ritchie46** [comment]
Yeah, I could add that. But as regex also allows for literals, this one `col(["^x.*$", "one_y"])` would be equal to `col("^(x.*|one_y)$)"`, and the `col(["^x.*$", "^*y$"])` equal to `col("^(x.*|*y)$)"`. 

We could add it, but the priority seems quite low to me, as this is exactly the power that regex offers.

**Comment by markfairbanks** [comment]
Ah gotcha - yep, that makes sense. I'm not very good at regex so I wasn't aware of this functionality 😄

**Comment by ritchie46** [comment]
I will close this, as I don't think its needed.
