### ISSUE TITLE
`check_sorted` causes error in `DataFrame.rolling`

### ISSUE THREAD

**Issue by marenwestermann** [pola-rs/polars#16583]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Using the example from the documentation (https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.rolling.html):
```python
>>> import polars as pl
>>> dates = [
...     "2020-01-01 13:45:48",
...     "2020-01-01 16:42:13",
...     "2020-01-01 16:45:09",
...     "2020-01-02 18:12:48",
...     "2020-01-03 19:45:32",
...     "2020-01-08 23:16:43",
... ]
>>> df = pl.DataFrame({"dt": dates, "a": [3, 7, 5, 9, 2, 1]}).with_columns(
...     pl.col("dt").str.strptime(pl.Datetime).set_sorted()
... )
>>> out = df.rolling(index_column="dt", period="2d").agg(
...     [
...         pl.sum("a").alias("sum_a"),
...         pl.min("a").alias("min_a"),
...         pl.max("a").alias("max_a"),
...     ]
... )
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maren/open-source/polars/py-polars/polars/dataframe/group_by.py", line 888, in agg
    .rolling(
     ^^^^^^^^
  File "/Users/maren/open-source/polars/py-polars/polars/_utils/deprecation.py", line 135, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maren/open-source/polars/py-polars/polars/lazyframe/frame.py", line 3312, in rolling
    lgb = self._ldf.rolling(index_column, period, offset, closed, pyexprs_by)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PyLazyFrame.rolling() missing 1 required positional argument: 'check_sorted'
```

### Issue description

As the stated in the log output, `rolling()` expects the positional argument `check_sorted`. However, the argument `check_sorted` 1) is not a positional argument and 2) is deprecated and should not be needed anymore (see documentation here: https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.rolling.html). 

The error seems to have been introduced yesterday with this PR: https://github.com/pola-rs/polars/pull/16494

### Expected behavior

The code above should cause no error.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  1.0.0
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.17.4
fastexcel:            0.10.4
fsspec:               2024.5.0
gevent:               24.2.1
hvplot:               0.10.0
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.1
pyiceberg:            0.6.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by cmdlineluser** [comment]
FWIW: I cannot reproduce this on main.

**Comment by MarcoGorelli** [comment]
thanks @marenwestermann for the report - I can't reproduce either, and the docstring example is checked in CI

did you run `make build` before running the example?

**Comment by marenwestermann** [comment]
Good point! I ran `make build` last night and then got the latest changes from main today but forgot to run `make build` again. Closing this issue now. Thanks for the feedback and apologies for the false alarm!
