### ISSUE TITLE
Do not change environment variables on import

### ISSUE THREAD

**Issue by adamsiwiec** [pola-rs/polars#16609]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import os
>>> print(os.getenv("POLARS_ALLOW_EXTENSION"))
None
>>> import polars
>>> print(os.getenv("POLARS_ALLOW_EXTENSION"))
true
```

### Issue description

Polars should not change environment variables set on import. This is a bad practice.

### Expected behavior

The environment variable is not changed

### Installed versions

<details>

```
>>> import polars as pl
pl>>> pl.show_versions()
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.6 (main, Nov 16 2023, 20:59:32) [Clang 15.0.0 (clang-1500.0.40.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.1.1
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.22
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is required for python polars to work. Why is this an issue for you?

**Comment by stinodego** [comment]
I do agree it's odd and it's bad practice to mess with the user's environment without their explicit permission.

Perhaps there's an alternative way to support Object types. I believe some Config options use atomics?

**Comment by ritchie46** [comment]
> I do agree it's odd and it's bad practice to mess with the user's environment without their explicit permission.

Many tools write to home folders in hidden directories and we will do as well to be able to function. For now I don't think we should put effort in this. I am open to a PR, but I don't believe this will clash with anything. I even believe it is tied to the process.

**Comment by adamsiwiec** [comment]
I can think of a few reasons why this might cause undesirable effects:
- unit tests that compare state of an environment before and after would fail
- CI tooling that utilizes polars would affect downstream processes' environment

Sure, it is probably low-pri, but as polars gets adopted by a larger community in production this will probably get red-flagged by more teams (like it was for me). Cheers!
