### ISSUE TITLE
Random encounters of `pyo3_runtime.PanicException: index out of bounds` after version 0.20.20

### ISSUE THREAD

**Issue by maxzw** [pola-rs/polars#16605]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I cannot give a reproducible example at this moment.

### Log output

```shell
...
>       return wrap_df(ldf.collect(callback))
E       pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
```

### Issue description

After version 0.20.20 we often encounter this error in our tests, preventing us from upgrading to newer polars releases.

This issue is encountered after a very long series of operations, hence it is hard to provide a minimal reproducible example. Printing the dataframe that causes the error shows that they are often very simple:

shape: (3, 3)
store_id (Int16)  item_id (Int16) value (Float64) 
1004      100002   10.0
1004      100004   8.0
1004      100010   9.0

Our pipelines then crash when calling:
```python
# many other operations...
df = df.with_columns(pl.col("value").floor().alias("__floor"))  # <- crashes here
```

The error we see is:
```
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
```

I tried saving the dataframe as parquet and applying the logic again:
```python
# many other operations...
df.write_parquet("test.parquet")  # <- crashes here
df = pl.read_parquet("test.parquet")
df = df.with_columns(pl.col("value").floor().alias("__floor"))
```

But then our pipelines crash at the `write_parquet` with:
```
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
```

It seems like the data gets corrupted somewhere along our pipeline after which further operations cannot be performed and the dataframe cannot even be saved. I was hoping to get some guidance on how to best reduce this to a reproducible example.

### Expected behavior

I expect the code to run like version 0.20.20 (and lower)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.17.4
fastexcel:            <not installed>
fsspec:               2023.9.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.2
nest_asyncio:         1.6.0
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.2
pyarrow:              14.0.1
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you get a repro? It is hard for us to do anything without. 

P.S. what is the callstack if you set `RUST_BACKTRACE=1`?

**Comment by maxzw** [comment]
I've gotten to a point where I could localise when the error happens:

```python
df_le = df.filter(pl.col("foo") <= pl.col("bar").sum().over(groupby))
df_gt = df.filter(pl.col("foo") > pl.col("bar").sum().over(groupby))
df_le.write_parquet("df_le.parquet")  # <- runs fine
df_gt.write_parquet("df_gt.parquet")  # <- line crashes
```

But when I try to save the dataframe that occurs before this operation, the line that previously crashed runs fine...

```python
df.write_parquet("df.parquet")   # <- runs fine
df_le = df.filter(pl.col("foo") <= pl.col("bar").sum().over(groupby))
df_gt = df.filter(pl.col("foo") > pl.col("bar").sum().over(groupby))
df_le.write_parquet("df_le.parquet")  # <- runs fine
df_gt.write_parquet("df_gt.parquet")  # <- runs fine
```

But when I make a copy of `df` and save that before doing the operation, the line crashes again:
```python
df_clone = df.clone()
df_clone.write_parquet("df_clone.parquet")   # <- runs fine
df_le = df.filter(pl.col("foo") <= pl.col("bar").sum().over(groupby))
df_gt = df.filter(pl.col("foo") > pl.col("bar").sum().over(groupby))
df_le.write_parquet("test.foo")  # <- runs fine
df_gt.write_parquet("test.parquet")  # <- line crashes
```

Then finally when trying to replicate the error using `df_clone.parquet`, no errors happen. Seems like the Polars variant of the observers effect 😄

**Comment by maxzw** [comment]
It seems like the exact version where this error occurs is polars-0.20.22.
It also seems like it behaves differently depending on hardware. Looking at the release notes of 0.20.22 I see a specific change on filtering in https://github.com/pola-rs/polars/pull/15686, can that be the cause?

**Comment by nordmtr** [comment]
Also running into the same issue in my tests. Found a quick fix: converting the df to pandas seems to reset all the errors, after which all the operations work correctly.

**Comment by Elvynzs** [comment]
I have also run into this issue, but it is quite hard to get a small repro code at it happens after a lot of operations and saving/loading the dataframe fixes the issue (if the saving operation does not crash)

**Comment by maxzw** [comment]
Closing this one because I specified the issue in https://github.com/pola-rs/polars/issues/16830

**Comment by maxzw** [comment]
Closing this one because I specified the issue in https://github.com/pola-rs/polars/issues/16830
