### ISSUE TITLE
DRAFT - `pl.Expr.map_batches` will fail with `fetch` but not `collect` if you output a 2d Array and mark the return_dtype as a 2d Array

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#16613]
### Checks

- [x] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
will try to produce
```

### Issue description

Draft, will fill in, don't waste time looking at this yet. Just a placeholder so i remember to fill it out

### Expected behavior

tbd

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
Can you open a new issue when you can reproduce? This is nothing we can work with and only clutters our issue stack.
