### ISSUE TITLE
Filter always exclude null values

### ISSUE THREAD

**Issue by Josh-Rob** [pola-rs/polars#16627]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

df = pl.DataFrame(
    {
        "b": [True, None],
    }
)

df.filter(pl.col("b")), df.filter(pl.col("b").not_())

```

### Issue description

Filter removes null row based on the column used to filter.

<small>shape: (1, 1)</small><table border="1" class="dataframe"><thead><tr><th>b</th></tr><tr><td>bool</td></tr></thead><tbody><tr><td>true</td></tr></tbody></table></div>

### Expected behavior

<small>shape: (2, 1)</small><table border="1" class="dataframe"><thead><tr><th>b</th></tr><tr><td>bool</td></tr></thead><tbody><tr><td>true</td></tr><tr><td>null</td></tr></tbody></table></div>

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:42:21) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by mcrumiller** [comment]
`filter` removes items that are not True, it does not exclude items that are False. A null not is not True, so it gets removed by the filter. We should probably update the documentation to clarify this, though.

**Comment by Josh-Rob** [comment]
Is it possible to update filter to include an option for null values?
