### ISSUE TITLE
The memory could not be written unhandled exception crash python.exe

### ISSUE THREAD

**Issue by EtienneT** [pola-rs/polars#16623]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I am doing hyper parameter optimization on some feature engineering that involves a lot of data.  It frequently nearly fills my 128gb of ram on my computer.  But around 40% of the trials completely crash python.exe even though I have a try except in my python code around the polars code involved.

Then windows shows this error dialog when the program crash (but not always):
<img width="316" alt="FNtPT6NVsj" src="https://github.com/pola-rs/polars/assets/265924/3f4ae1c8-70d7-4813-b5f9-6bccf0100633">

> The instruction at 0x00007FFA4E4440DC referenced memory at
> 0x0000029D68010000. The memory could not be written.

Then in Windows Event Viewer there's the following message:

> Faulting application name: python.exe, version: 3.11.6150.1013, time stamp: 0x651bed68
> Faulting module name: polars.pyd, version: 0.0.0.0, time stamp: 0x664e1cdf
> Exception code: 0xc0000005
> Fault offset: 0x00000000043040dc
> Faulting process id: 0x0x876C
> Faulting application start time: 0x0x1DAB347465591F4
> Faulting application path: C:\Users\etrem\miniforge3\python.exe
> **Faulting module path: C:\work\ML\\.venv\Lib\site-packages\polars\polars.pyd**
> Report Id: d4c540ba-83dc-4d7e-aaa6-ddbfda17e048
> Faulting package full name: 
> Faulting package-relative application ID: 

Here is the code where the bug happens, but unfortunately I can't provide the data to reproduce the problem:

```python
def _get_pdf_exp(prefix: str) -> pl.Expr:
    x = pl.col(prefix)
    mean = pl.col(f'{prefix}_rolling_mean')
    std = pl.col(f'{prefix}_rolling_std')
    
    fact = std * ((2 * np.pi)**0.5)
    expo = ((x - mean) ** 2) / (2 * (std ** 2))
    
    return ((-expo).exp() / fact).alias(f'{prefix}_pdf')

def get_pdf_df(df_merged: pl.LazyFrame, cfg: Config) -> pl.LazyFrame:
    return (
        df_merged
        .select(
            pl.col('Node'), pl.col('Date'), pl.col('Hour'), pl.col('Type'),
            *[_get_pdf_exp(f'Price_{x}') for x in range(2,cfg.bayes.shifts+2)],
            *[_get_pdf_exp(f'Spread_{x}') for x in range(2,cfg.bayes.shifts+2)],
            *[_get_pdf_exp(f'Price_TMINUS1_HOUR_{x}') for x in range(0,cfg.last_hour)],
            *[_get_pdf_exp(f'Spread_TMINUS1_HOUR_{x}') for x in range(0,cfg.last_hour)]
        )
        .drop_nulls()
        .melt(id_vars=['Node', 'Date', 'Hour', 'Type'])
        .group_by(['Node', 'Date', 'Hour', 'Type'])
        .agg(
            (pl.col('value').cast(pl.Float64).product() * 0.5).alias('Score')
        )
        .sort('Node', 'Date', 'Hour', 'Type')
        .collect()
        .pivot('Score', ['Node', 'Date', 'Hour'], 'Type')
        .lazy()
        .with_columns(
            pl.when(
                (pl.col('Buy') >= pl.col('Sell')) |
                (pl.col('Sell').is_null() & pl.col('Buy').is_not_null()) |
                (pl.col('Buy') == pl.col('Sell'))
            ).then(pl.lit('Buy'))
            .otherwise(pl.lit('Sell'))
            .alias('Decision'),
            (pl.col('Date').cast(pl.Datetime('ms')) + pl.duration(hours=pl.col('Hour'))).alias('DecisionTime'),
        )
    )
```

I tried using collect(streaming=True) to try to allow the engine to work in batch to ease memory consumption, but it didn't help.

### Log output

```shell
dataframe filtered
keys/aggregates are not partitionable: running default HASH AGGREGATION
dataframe filtered
dataframe filtered
keys/aggregates are not partitionable: running default HASH AGGREGATION
keys/aggregates are not partitionable: running default HASH AGGREGATION

Then it crashes here
```

### Issue description

Described everything in the other textarea.

### Expected behavior

python should be able to catch an error coming from polars, it should not make python crash completely even in a try except.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
torch:                2.3.0+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by EtienneT** [comment]
Ok I think I found the culprit:

```
.melt(id_vars=['Node', 'Date', 'Hour', 'Type'])
.group_by(['Node', 'Date', 'Hour', 'Type'])
.agg(
    (pl.col('value').cast(pl.Float64).product() * 0.5).alias('Score')
)
```

This part of the code was functionaly equivalent to:

```
.select(
    pl.col('Node'), pl.col('TradingDate'), pl.col('Hour'), pl.col('BidType'),
    (pl.reduce(lambda a, b: a * b, pl.col('^.*_pdf$').cast(pl.Float64)) * 0.5).alias('Score')
)
```

I just didn't know the existence of pl.reduce.

Now parameters that made my code crash don't make it crash anymore.

But...  the problem of polars making python crash completely is still there.

**Comment by ritchie46** [comment]
> But... the problem of polars making python crash completely is still there.

That's not something we can easily solve. Windows probably overcommits memory here and starts crashing when we write to it. If we couldn't allocate it we would have gotten a panic.

**Comment by ritchie46** [comment]
I will close this as this is not actionable by us. Going out of memory isn't something we claim to prevent.
