### ISSUE TITLE
diff on UInt64 polars series returns series of null instead of actual diff series

### ISSUE THREAD

**Issue by Enaunimes** [pola-rs/polars#16641]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars
polars.Series([18446743990181356215, 18446743990181366216, 18446743990181376216], dtype=polars.UInt64).diff()
```

### Log output

```shell
shape: (3,)
Series: '' [i64]
[
        null
        null
        null
]
```

### Issue description

When diffing series of UInt64 numbers, polars returns series of nulls instead of actual diffs.

### Expected behavior

>>> import pandas
>>> pandas.Series([18446743990181356215, 18446743990181366216, 18446743990181376216]).diff()
0        NaN
1    10001.0
2    10000.0
dtype: float64

### Installed versions

<details>

```
>>> polars.show_versions()
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Linux-5.15.0-111-generic-x86_64-with-glibc2.29
Python:               3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.10.0
matplotlib:           3.7.4
nest_asyncio:         1.6.0
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              16.1.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0

```
</details>

**Comment by ritchie46** [comment]
Because it doesn't fit into `i64`. Until we have support for `i128`, there isn't a good fit.

Note that the pandas strategy of converting to float is also wrong:


```python
>>> import pandas as pd
>>> s = [0, 18446743990181366216, 0]
>>> pd.Series(s).diff()
0             NaN
1    1.844674e+19
2    8.352819e+10
dtype: float64
```

Index 2 is 9 decimals off.

**Comment by Enaunimes** [comment]
> Because it doesn't fit into `i64`. Until we have support for `i128`, there isn't a good fit.
> 
> Note that the pandas strategy of converting to float is also wrong:
> 
> ```python
> >>> import pandas as pd
> >>> s = [0, 18446743990181366216, 0]
> >>> pd.Series(s).diff()
> 0             NaN
> 1    1.844674e+19
> 2    8.352819e+10
> dtype: float64
> ```
> 
> Index 2 is 9 decimals off.

I suppose specifying dtype=polars.UInt64 when creating the series should have made the data fit into u64?

**Comment by ritchie46** [comment]
Sorry, what do you mean?

**Comment by Enaunimes** [comment]
> Sorry, what do you mean?

I'm not from a CS background, so please correct me if I'm wrong.

As in the code sample of the issue, I specified the dtype=polars.UInt64 when creating the series. The number does not fit in the polars.Int64, but should have fit into the polars.Uint64, isn't it?

**Comment by d-reynol** [comment]
@Enaunimes the absolute value of the diff would fit in Uint64, but diffs can be negative & Uint64 is unsigned

**Comment by Enaunimes** [comment]
> @Enaunimes the absolute value of the diff would fit in Uint64, but diffs can be negative & Uint64 is unsigned

Got it. Thanks.
