### ISSUE TITLE
pl.from_pandas throws Arrowerror 

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1664]
I downloaded data from microsoft sql DB. When I'm trying to convert pandas to polars dataframe. Following error is thrown.

`RuntimeError: ArrowError(NotYetImplemented("Importing PhysicalType \"Null\" is not yet supported."))`

Is there any restriction for data types or null data in polars?

**Comment by ritchie46** [comment]
Hi, what version are you using?

**Comment by hakantekbas** [comment]
0.10.6

**Comment by ritchie46** [comment]
I thought, we've dealt with the null values. Could you send a the first rows as parquet? Or at least print the schema? Thanks!

**Comment by hakantekbas** [comment]
![image](https://user-images.githubusercontent.com/19631334/139833235-7853b410-16c6-4407-a87b-41d3a29c7780.png)

**Comment by jorgecarleitao** [comment]
Likely on arrow2 side: the ffi interface dos not support null datatype yet.

I can PR a fix for this soon.

Note that a null datatype is likely something wrong, as it contains no data.

**Comment by hakantekbas** [comment]
Hi;

Thanks for prompt reply.

I'm also trying to download data from postgre and mssql. Same data is loaded to these two DBs. But download speed is very different. Postgre takes 3 seconds but mssql takes nearly 24 seconds. Is there any known issue about mssql support?

**Comment by ritchie46** [comment]
> Hi;
> 
> Thanks for prompt reply.
> 
> I'm also trying to download data from postgre and mssql. Same data is loaded to these two DBs. But download speed is very different. Postgre takes 3 seconds but mssql takes nearly 24 seconds. Is there any known issue about mssql support?

I really need some more information on how you load your data. Have you got some code?

**Comment by ritchie46** [comment]
> ![image](https://user-images.githubusercontent.com/19631334/139833235-7853b410-16c6-4407-a87b-41d3a29c7780.png)

This looks like a polars dataframe. So you have succesfully loaded data? :see_no_evil:

**Comment by hakantekbas** [comment]
Hi Ritchie46,

If I download that via mssql, postgre with  pl.read_sql command, it is working. But if I convert from pandas, it is throwing error.

**Comment by hakantekbas** [comment]
> > Hi;
> > Thanks for prompt reply.
> > I'm also trying to download data from postgre and mssql. Same data is loaded to these two DBs. But download speed is very different. Postgre takes 3 seconds but mssql takes nearly 24 seconds. Is there any known issue about mssql support?
> 
> I really need some more information on how you load your data. Have you got some code?

`### mssql  ###
start = time.time()
conn = "mssql://uid:pwd@ip:1433/table"
dataSinirMssql = pl.read_sql('select * from table',conn)
print(time.time()-start)

### postgresql  ###
start = time.time()
conn = "postgres://uid:pwd@ip:5432/db"
dataSinirPostgre = pl.read_sql('select * from table',conn)
print(time.time()-start)
`

**Comment by ritchie46** [comment]
@hakantekbas. I think the null data is already resolved. Can you update to latest version (0.10.14)?

The performance differences maybe due to the drivers, Polars uses connector-x for the transformation from db to arrow, and I am not really familiar with the differences per driver source.

**Comment by ritchie46** [comment]
> Thanks. I upgrade to 0.10.14. Error changed.
> 
> code --> pl.from_pandas(data) `PanicException: called `Result::unwrap()`on an`Err` value: InvalidArgumentError("all columns in a record batch must have the same length")`
> 
> Should I ask mssql question to connector-x?

Great, I now have a fix for this. It will be released next friday.
