### ISSUE TITLE
Stack DataFrames with different columns (diagonal stacking)

### ISSUE THREAD

**Issue by FrozenPie1** [pola-rs/polars#1665]
Currently there are vstack (stacking of DataFrames with the same columns) and hstack (stacking of DataFrames with completly different columns). There is no possibility to stack DataFrames with a mixture of identical and different columns.

If you have the following three CSV files for example:

CSV1
|first    |last     |age|
|---------|---------|---|
|Aaron    |Frank    |40 |
|Mike     |Carlson  |59 |
|Herman   |McKinney |39 |
|Charlotte|Rodriquez|42 |
|Sara     |Nichols  |32 |

CSV2
|first    |last     |city|postal|
|---------|---------|----|------|
|Claudia  |Stevenson|Pokluoj|156846|
|Frances  |Smith    |Sophuca|684321|
|Ann      |Mendoza  |Gomafi|158431|
|Bernard  |Chandler |Kafalkul|543154|
|Barbara  |Montgomery|Relowosa|354849|

CSV3
|first    |last     |age|phone |postal |
|---------|---------|---|------|-------|
|Ruth     |Ray      |old|(515) 365-4913|C1O 2I2|
|Gordon   |Parker   |young|(948) 638-9433|J8Z 7S8|
|Frances  |Gibbs    |young|(824) 629-2187|N7A 5N4|
|Ivan     |Powell   |mid|(577) 715-4999|N6H 3J8|
|Kenneth  |Douglas  |old|(944) 309-1427|R0I 4V1|

In DataFrame.jl in the Julia Programming Language you can write the following command:
`df::DataFrame = reduce(vcat, dfs, cols=:union);`
where 'vcat' tells the reduce comand to vertically stack 'dfs' which is a vector of DataFrames.

Result:
|first    |last     |age|city  |postal |phone         |
|---------|---------|---|------|-------|--------------|
|Aaron    |Frank    |40 |      |       |              |
|Mike     |Carlson  |59 |      |       |              |
|Herman   |McKinney |39 |      |       |              |
|Charlotte|Rodriquez|42 |      |       |              |
|Sara     |Nichols  |32 |      |       |              |
|Claudia  |Stevenson|   |Pokluoj|156846 |              |
|Frances  |Smith    |   |Sophuca|684321 |              |
|Ann      |Mendoza  |   |Gomafi|158431 |              |
|Bernard  |Chandler |   |Kafalkul|543154 |              |
|Barbara  |Montgomery|   |Relowosa|354849 |              |
|Ruth     |Ray      |old|      |C1O 2I2|(515) 365-4913|
|Gordon   |Parker   |young|      |J8Z 7S8|(948) 638-9433|
|Frances  |Gibbs    |young|      |N7A 5N4|(824) 629-2187|
|Ivan     |Powell   |mid|      |N6H 3J8|(577) 715-4999|
|Kenneth  |Douglas  |old|      |R0I 4V1|(944) 309-1427|

The Julia code results in the following DataFrames being created and are being merged into the last one.

![grafik](https://user-images.githubusercontent.com/93589267/139847933-3bef5647-36cc-4a97-b3e5-f917dc98ec87.png)
![grafik](https://user-images.githubusercontent.com/93589267/139847686-f115388f-800c-4988-a169-bcac0a57e7bf.png)

If you're interessted, the full code in Julia looks like this:

![grafik](https://user-images.githubusercontent.com/93589267/139846724-4ee50955-0765-4413-bf53-6ff504630bc5.png)

Trying to do the same in polars throws following error:

![grafik](https://user-images.githubusercontent.com/93589267/139843972-a9aecd6c-270c-42b6-ace5-e3c72e237abc.png)

So my final question is: Would it be possible to implement this behavior for polars with a function like 'dstack' or simply 'stack' which takes a Vector of different DataFrames and merges them diagonally into one big DataFrame?
This would make it possible to work with DataFrames where you can't always guarantee that columns exist or data types are the same without introducing another programming language into the project. My rust skills are fairly minimalistic so i can't really help with the implementation :(

If this feature is already implemented and i just couldn't find it i would appreciate your help in finding it :)

**Comment by ritchie46** [comment]
Could you provide me with a code snippet that creates the first 3 DataFrames? Then I can try to wrap up an example for you. :)

**Comment by FrozenPie1** [comment]
Thanks for the fast reply. The following code generates a Vector of DataFrames and puts all three DataFrames into that Vector. As far as i know, the CsvReader doesn't support reading a Vector of files an returning a Vector of DataFrames so i have to do this manually.
```
use std::fs::File;
use polars::prelude::*;

fn main() {
	let	mut	dfs_all:	Vec<DataFrame>	= Vec::new();
	let	mut	file_paths:	Vec<&str>	= Vec::new();

	file_paths.push("./data/test1.csv");
	file_paths.push("./data/test2.csv");
	file_paths.push("./data/test3.csv");

	for file_path in &file_paths {
		dfs_all.push(get_data_frame_from_csv(&file_path).unwrap());
	}
}

fn get_data_frame_from_csv(file_path: &str) -> Result<DataFrame> {
	let file = File::open(file_path).expect("Could not open file");

	CsvReader::new(file)
		.with_delimiter(b'\t')
		.with_ignore_parser_errors(true)
		.infer_schema(None)
		.has_header(true)
		.finish()
}
```

**Comment by potter420** [comment]
Hmm, I been thinking you could do some thing like dis, written in python, although similar logic apply wherever:
```python
df1 = ... read_test1
...

# the idea here to combine the columns together to get the final fully populated columns list and associated dtypes
final_cols = {}
for i, col in enumerate(df1.columns):
   if col not in final_cols:
       final_cols[col]=df1.dtype[i]
# Do the same for df2 and 3, or put them in iterable and iterate
# Construct coerce expression:
# What this do is select the available columns, and set null value on the rest, with corresponding dtypes
select_df1_expr = [
   col if col in df1.columns else pl.lit(None, final_cols[col]).alias(col)
  for col in final_cols
]
# finally, use vstack on all of them using the select_expressions
fin_df = pl.concat([
  df1.select(select_df1_expr)
...
])
...
```

**Comment by FrozenPie1** [comment]
Tanks for the answer @potter420 but this solves only half of the problem. Your code expects that the same columns in different DataFrames have the same data type which is not always the case. So i get the following error when i try to run your code:

![grafik](https://user-images.githubusercontent.com/93589267/140295595-8d1be21c-6111-44c4-949e-76feddf5fd6c.png)

This would be solved if there was something like a "hirarchy" in the recognition of the datatypes when merging the same columns with different dataypes in different DataFrames to find the lowest common denominator.
For example: First try to cast the values to Int64 -> if unsuccessful try Float64 -> if unsuccessfull try Date -> if unsuccessful try Utf8 which should always work.

**Comment by potter420** [comment]
Hmm, that casting part can lead to some strange behaviors (And tbh, that what I hate about `pandas`, make everything an object). We may need to plot some diagram of how all the possible logical type can be casted. Ofc, UTF8 will be there at the end as final type to be casted.

**Comment by ritchie46** [comment]
> Hmm, that casting part can lead to some strange behaviors (And tbh, that what I hate about `pandas`, make everything an object). We may need to plot some diagram of how all the possible logical type can be casted. Ofc, UTF8 will be there at the end as final type to be casted.

Indeed, I was already writing something that could do this in Rust. But I am  ot entirely sure it should automatically cast the same named columns. E.g. we also don't allow this in joins and vstacks. So that would be quite inconsistent and IMO also a bit the responsibility of the user to maintain the schemas.

**Comment by potter420** [comment]
Auto-cast is source of all pains when I was working on my projects, things like, is this column datetime or int, cause we have different logic to apply and If it is an object, it'll be hell to work with. And with the backend team keep adding new columns and change some old columns data types, it became nightmares, the problem @FrozenPie1 face is similar to mine when working with file with schema evolutions. 

The way I do it is to:
- Keep the raw in some place, where it is what it is when we received it
- Define a schema for the raw to comply to (What we expect the data to be)
- Write some small modules (previously in python, using `pyarrow`, then evolved to rust using `arrow2`) to cast and comply all data types when reading the files, handling things like str -> datetime or decimal precision/scale correctness (we set it to maximum scale 10 and precision 38 that is supported in most downstream DB). Write some logs if detect schema changes.
- Append them together for further processing.

By this approach, we're don't care much about "similar" files have different columns and different data types. But we're also have to make some compromise. E.g. What to do when casting from `str` to `datetime` and we're encounter some strange format (readable by human, but not in any predefined format( Like ISO). In case like that, what worked with us may not work with everyone else since it's our own business logic (set them to null or modify our code to accommodate for that format)

**Comment by FrozenPie1** [comment]
> By this approach, we're don't care much about "similar" files have different columns and different data types. But we're also have to make some compromise. E.g. What to do when casting from `str` to `datetime` and we're encounter some strange format (readable by human, but not in any predefined format( Like ISO). In case like that, what worked with us may not work with everyone else since it's our own business logic (set them to null or modify our code to accommodate for that format)

Aren't we limited to the data types and formats which arrow is offering in this case? So if the format doesn't match arrows `datetime` format it has to be downcasted to a `str`. Even if `str` wouldn't be the optimal format, it would still be possible to work with it and it would be at the hands of the user to optimize the format in his source files to get the optimal format from the auto casting algorithm.

So effectivly there just has to exist a hirarchy in the possible data types and if there are the same column in different DataFrames the lower one is chosen for the column in the final DataFrame.

An example hirarchy (no guarantee on completeness or correctness) could look like this:
```
➨null
  ➥bool
    ➥uint8/16/32/64
      ➥int8/16/32/64
        ➥float8/16/32/64
          ➥decimal128
            ➥date32/64
              ➥duration
                ➥utf8
                  ➥large_utf8
                    ➥binary
                      ➥large_binary
```
So of the column 'colx' in 'df1' has the format uint16 and the column 'colx' in 'df2' has the format float32, the datatype of 'colx' in the final 'df_final' would be float32 because a uint16 "fits" into a float32 but not vice versa.

**Comment by ghuls** [comment]
@FrozenPie1 You can override the dtype when reading the CSV file:
```
In [20]: df2 = pl.read_csv('test2.csv', sep='\t', dtype={'postal': pl.Utf8})

In [21]: df1 = pl.read_csv('test1.csv', sep='\t', dtype={'postal': pl.Utf8})

In [22]: df2 = pl.read_csv('test2.csv', sep='\t', dtype={'postal': pl.Utf8})

In [23]: df3 = pl.read_csv('test3.csv', sep='\t', dtype={'postal': pl.Utf8})

In [24]: df1
Out[24]: 
shape: (5, 3)
┌───────────┬───────────┬─────┐
│ first     ┆ last      ┆ age │
│ ---       ┆ ---       ┆ --- │
│ str       ┆ str       ┆ i64 │
╞═══════════╪═══════════╪═════╡
│ Aaron     ┆ Frank     ┆ 40  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Mike      ┆ Carlson   ┆ 59  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Herman    ┆ McKinney  ┆ 39  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Charlotte ┆ Rodriquez ┆ 42  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Sara      ┆ Nichols   ┆ 32  │
└───────────┴───────────┴─────┘

In [25]: df2
Out[25]: 
shape: (5, 4)
┌─────────┬────────────┬──────────┬────────┐
│ first   ┆ last       ┆ city     ┆ postal │
│ ---     ┆ ---        ┆ ---      ┆ ---    │
│ str     ┆ str        ┆ str      ┆ str    │
╞═════════╪════════════╪══════════╪════════╡
│ Claudia ┆ Stevenson  ┆ Pokluoj  ┆ 156846 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Frances ┆ Smith      ┆ Sophuca  ┆ 684321 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Ann     ┆ Mendoza    ┆ Gomafi   ┆ 158431 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Bernard ┆ Chandler   ┆ Kafalkul ┆ 543154 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Barbara ┆ Montgomery ┆ Relowosa ┆ 354849 │
└─────────┴────────────┴──────────┴────────┘

In [26]: df3
Out[26]: 
shape: (5, 5)
┌─────────┬─────────┬───────┬────────────────┬─────────┐
│ first   ┆ last    ┆ age   ┆ phone          ┆ postal  │
│ ---     ┆ ---     ┆ ---   ┆ ---            ┆ ---     │
│ str     ┆ str     ┆ str   ┆ str            ┆ str     │
╞═════════╪═════════╪═══════╪════════════════╪═════════╡
│ Ruth    ┆ Ray     ┆ old   ┆ (515) 365-4913 ┆ C1O 2I2 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ Gordon  ┆ Parker  ┆ young ┆ (948) 638-9433 ┆ J8Z 7S8 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ Frances ┆ Gibbs   ┆ young ┆ (824) 629-2187 ┆ N7A 5N4 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ Ivan    ┆ Powell  ┆ mid   ┆ (577) 715-4999 ┆ N6H 3J8 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ Kenneth ┆ Douglas ┆ old   ┆ (944) 309-1427 ┆ R0I 4V1 │

```

**Comment by ghuls** [comment]
Auto casting is of identical columns with different data shouldn't exist in my opinion, as in most cases this is an error that the user wants to know about.

You can read all the CSV files as Utf8 columns, stack them, write to CSV again and then let polars infer the datatypes from the full CSV.
```python
In [65]: df1 = pl.read_csv('test1.csv', sep='\t', infer_schema_length=0)

In [66]: df2 = pl.read_csv('test1.csv', sep='\t', infer_schema_length=0)

In [67]: df3 = pl.read_csv('test1.csv', sep='\t', infer_schema_length=0)

In [68]: df1
Out[68]: 
shape: (5, 3)
┌───────────┬───────────┬─────┐
│ first     ┆ last      ┆ age │
│ ---       ┆ ---       ┆ --- │
│ str       ┆ str       ┆ str │
╞═══════════╪═══════════╪═════╡
│ Aaron     ┆ Frank     ┆ 40  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Mike      ┆ Carlson   ┆ 59  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Herman    ┆ McKinney  ┆ 39  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Charlotte ┆ Rodriquez ┆ 42  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Sara      ┆ Nichols   ┆ 32  │
└───────────┴───────────┴─────┘

In [69]: df2
Out[69]: 
shape: (5, 3)
┌───────────┬───────────┬─────┐
│ first     ┆ last      ┆ age │
│ ---       ┆ ---       ┆ --- │
│ str       ┆ str       ┆ str │
╞═══════════╪═══════════╪═════╡
│ Aaron     ┆ Frank     ┆ 40  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Mike      ┆ Carlson   ┆ 59  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Herman    ┆ McKinney  ┆ 39  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Charlotte ┆ Rodriquez ┆ 42  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Sara      ┆ Nichols   ┆ 32  │
└───────────┴───────────┴─────┘

In [70]: df3
Out[70]: 
shape: (5, 3)
┌───────────┬───────────┬─────┐
│ first     ┆ last      ┆ age │
│ ---       ┆ ---       ┆ --- │
│ str       ┆ str       ┆ str │
╞═══════════╪═══════════╪═════╡
│ Aaron     ┆ Frank     ┆ 40  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Mike      ┆ Carlson   ┆ 59  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Herman    ┆ McKinney  ┆ 39  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Charlotte ┆ Rodriquez ┆ 42  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ Sara      ┆ Nichols   ┆ 32  │
└───────────┴───────────┴─────┘
```

@ritchie46 It might be nice to have a function that allows to cast a `pl.Utf8` column to the most optimal dtype (with `parse_date` option, ... as in pl.read_csv()).

**Comment by FrozenPie1** [comment]
> Auto casting is of identical columns with different data shouldn't exist in my opinion, as in most cases this is an error that the user wants to know about.

What would speak against an argument like 'ignore_data_type_mismatches=true' or 'align_mismatching_data_types=true' or 'cast_differing_data_types=true' in a merge/concat function?

An example of a case where the same column in different CSV files has a different data type and it is not an error:
You have many different programs in your company and each one is build by a different team which implements things different. Each of these programs sends you data which you store in a CSV file. So every team sends you a JSON with differing fields but some are the same (mandatory fields and many many optional fields). Some implement these optional fields and decide that it is enough to fill these with just numbers and another team decides to fill this with something like `option=true`.

**Comment by potter420** [comment]
Like I said, it will create complication since your processing tasks downstream will have to know which type they are receiving to do the math right. `float` and `int` is safe, but date, string is an headache. 
But anyway, for auto casting, we can actually do something like this. Again in `python` but you can translate it with no hassle anw:
```python
# first to have a function that determine the best type to be casted to, according to your hierachy
def determine_dtype(current_type, target_type):
    if current_type == target_type:
         return current_type
    elif current_type == pl.Int64 and target_type == pl.Float64:
        return target_type
    ... # the rest of the hierachy goes here
    # in rust, use switch (current_type, target_type) for more clarity

# Next, use the column dictionary above, but this time, we actually gonna check for the types,
# Use the function above to determine the final type since there may be some variation,
# eg. file 1 col 1 is int, file2 col 1 is float and file3 col 1 turned in to string, final type should be string.
for df in df_list:
  for i, col in enumerate(df.columns):
     if col not in final_cols:
         final_cols[col]=df1.dtype[i]
     else:
         final_cols[col] = determine_dtype(final_cols[col], df1.dtype[i])
# same goes for df2, df3, put them in to iterable if possible
# And finally do the casting expression with the final information about columns
# Take care to modify the cast function a bit to 
# accommodate for some hard to cast value like date -> str and other things.
```

Regarding to hard casting, you don't have to modify the application code, put a schema file or use some schema management method aka data catalogs (in my case, AWS Glue catalogs). The app should query the schema file/management to know what schema the output should be. The schema stay up-to-date by using some other schema discovery method.
In most data lake implementation, data catalogs is a requirement. :D

**Comment by ritchie46** [comment]
I agree with the fact that a concat should return an error if dtypes don't match. A user can modify its programming accordingly.

If you want automatic casting for instance, you can fill a hashmap mapping column names to dtypes and cast to the required super types. The dynamic typing then becomes a part of your program.

**Comment by wseaton** [comment]
@ritchie46 I also have an example function that does something like this (had to do this the other day to merge schema of a bunch of parquet files):

```python
from orderedset import OrderedSet

def harmonic_merge(dfs: List[pl.DataFrame]) -> List[pl.DataFrame]:

    meta_set = OrderedSet()

    for dataframe in dfs:
        for col, _type in zip(dataframe.columns, dataframe.dtypes):
            meta_set.add((col, _type))

    for i, df in enumerate(dfs):
        our_set = OrderedSet(zip(df.columns, df.dtypes))
        diff_set = meta_set.difference(our_set)
        
        if diff_set:
            for (name, _dtype) in diff_set:
                print(f'Missing column found for df[{i}]! Adding:', name, '\t', _dtype)
                s = pl.Series(name, [None] * df.height, dtype=_dtype)
                dfs[i] = df.with_column(s).select([x[0] for x in meta_set])
            
    return dfs

dfs = harmonic_merge(dfs)
dfs = reduce(lambda x, y: x.vstack(y), dfs)
```

Something like this could probably be converted to pure rust code, I'd be happy to take a stab at it.

**Comment by ritchie46** [comment]
> What it currently does not do:

Thanks @wseaton, but I already implemented the lion share yesterday, so I just as well wrap it up. :)

#1676 implements diagonal stack, BUT does error when column types don't match.

**Comment by FrozenPie1** [comment]
A big thank you to everyone who commented and provided code here. With the added functionality i think i can get this thing flying for us :)
And especially thanks to you @ritchie46 for adding the diagonal stacking functionality to the polars core.

**Comment by wseaton** [comment]
> > What it currently does not do:
> 
> Thanks @wseaton, but I already implemented the lion share yesterday, so I just as well wrap it up. :)
> 
> #1676 implements diagonal stack, BUT does error when column types don't match.

No worries! With this implemented, we are pretty close to the functionality of `spark.read.parquet` with the `mergeSchema=true` option set (albeit using in memory processing), which is great to see.
