### ISSUE TITLE
Missing doc entry for new `polars.sql` top level function

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#16654]
### Description

Checked out the freshly released SQL docs, and noticed that `polars.sql` added in #16528 does not seem to be there.

While I'm here, I'll add that all the addition SQL support and new documentation is awesome!

**Comment by cmdlineluser** [comment]
I believe it just needs to be added to `functions.rst` if you are wanting to make a PR

https://github.com/pola-rs/polars/blob/318ec405632410a41f634de7aeff46e89a25eab9/py-polars/docs/source/reference/expressions/functions.rst?plain=1#L86

**Comment by henryharbeck** [comment]
Thanks for the pointer @cmdlineluser, PR incoming.
