### ISSUE TITLE
[Python] `min_periods` should be a named argument or not?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#16684]
It appears that `rolling_*` and `rolling_*_by` methods differ in whether `min_periods` can be a positional argument.
It would be better if one of them were unified.

https://github.com/pola-rs/polars/blob/9223b103887afaf7c90e676f65b6d517c184215c/py-polars/polars/expr/expr.py#L9036-L9047
https://github.com/pola-rs/polars/blob/9223b103887afaf7c90e676f65b6d517c184215c/py-polars/polars/expr/expr.py#L7312-L7321

**Comment by MarcoGorelli** [comment]
thanks for noticing - slight preference for named

**Comment by stinodego** [comment]
Let's make them keyword-only.
