### ISSUE TITLE
`pl.lit(None, dtype=pl.Struct({"a": pl.Int64()}))` gives `{'a': None}`, not `None`

### ISSUE THREAD

**Issue by NickCrews** [pola-rs/polars#16696]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
dtype = pl.Struct({"a": pl.Int64()})
e = pl.lit(None, dtype=dtype)
pl.select(e).item()
```

### Issue description

I am running into this in [this PR for ibis](https://github.com/ibis-project/ibis/pull/8666/files#diff-4b1d72810ad7e91258141d5a9995f7bfb42d6ad232f7975ea7a68406d5292a8aR72-R89).

But perhaps I am not understanding polars' data model for structs, maybe only field values can be NULL, but not the struct in its entirety? duckdb, apache arrow, and maybe others support the entire thing being NULL so thats why I'm thinking that's possible. 

### Expected behavior

I would expect this to result in a top level `NULL`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-6.1.85+-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
nest_asyncio:         1.6.0
numpy:                1.25.2
openpyxl:             3.1.3
pandas:               2.0.3
pyarrow:              14.0.2
pydantic:             2.7.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
torch:                2.3.0+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
Thanks for the report. This is a known issue:
https://github.com/pola-rs/polars/issues/3462

I'm closing this as a duplicate.
