### ISSUE TITLE
pl.Series.str.slice fails with chinese character

### ISSUE THREAD

**Issue by chuchiy** [pola-rs/polars#1669]
#### Are you using Python or Rust?

python

#### What version of polars are you using?

0.10.15

#### What operating system are you using polars on?

windows

#### Describe your bug.

pl.Series.str.slice can not substr chinese characters

#### What are the steps to reproduce the behavior?

**Example**

```python
df = pl.DataFrame(
    {
        "b": ["foo", "ham", "spam", "egg", "中文"],
    }
)
df[[pl.col('b').str.slice(1,1)]]
```

#### What is the actual behavior?

above code snippet will throw error

```
PanicException: A non-utf8 string was passed.: Utf8Error
```

#### What is the expected behavior?

slice(1, 1) should return ["o", "a", "p", "g", "文"]

**Comment by ritchie46** [comment]
Thanks, for the issue report. Forgot about UTF8, will fix it!

**Comment by ritchie46** [comment]
Fix upstream: https://github.com/jorgecarleitao/arrow2/pull/568
