### ISSUE TITLE
polars-flavor

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#1670]
We need a way to customize **Polars** - API with custom funcs beyond pipes and applys -> something like polars-flavor (pandas flavor)... :)

**Comment by ritchie46** [comment]
I am not really familiar with `pandas-flavor`. What does this do exactly? Is it simply a decorator that modifies the python classes a bit?

**Comment by ritchie46** [comment]
Is it similar to #1653?

**Comment by Arengard** [comment]
yes it is I missed that one... :)

**Comment by ritchie46** [comment]
Close in favor of #1653
