### ISSUE TITLE
Add `make test-ci` to (mostly) replicate CI tests

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#16727]
### Description

Having a single command to test PRs would help to avoid creating PRs that still have errors in them, which often aren't detected until the CI runs. This clutters the PR list and pings reviewers for items that aren't yet ready for review (I am guilty of this). While it's not reasonable to expect everyone to have multiple versions of python at their disposal, many of the checks can and should be run locally first. Here is my list of what I think would be easy to check (listed in order of CI tests):

* Build Rust documentation
* Lint Python / ruff
* Lint Rust / clippy nightly
* Lint global / main
* Test Python
* Test Rust
* Lint Python / mypy
* Lint Rust / clippy-stable
* Test Rust / integration-test
* Lint Rust / rustfmt
* Test Rust / check-features
* Lint Rust / miri
* Test Rust / check-wasm

Some of these have multiple OS-dependent components, but since Linux/WSL is what's supported here, I think we could get away with running the Ubuntu checks alone. This won't cover 100% of cases but it will at least give contributors a tool to write cleaner PRs and could take some load off of the reviewers. Thoughts?

**Comment by stinodego** [comment]
I don't really understand what this would add over `make pre-commit` and `make test-all`?

**Comment by mcrumiller** [comment]
The main pieces missing are the checks in [test-rust.yml](https://github.com/pola-rs/polars/blob/main/.github/workflows/test-rust.yml), which include the feature gate checks that can easily slip through `make test-all` and `make pre-commit`. Would you be open to a PR that adds a `make test-rust` to the makefile, if not the `test-ci` proposed in this issue?

**Comment by stinodego** [comment]
You really don't want to run `cargo-hack` locally, it's really expensive. You can already run the Rust tests locally using the Makefile in the `crates` folder, but the Rust tests are also really expensive/heavy to run.

There is nothing wrong with using GitHub's machines to run the tests/lints for you. As long as people open their PRs in draft there is no issue and we don't get pinged.

I don't see the benefit here, sorry.

**Comment by mcrumiller** [comment]
Sure, np.
