### ISSUE TITLE
Interpolate based on other Float64 column

### ISSUE THREAD

**Issue by MKDJr** [pola-rs/polars#16794]
### Description

This feature request is a follow-up to issue #9616. 

I am very grateful for the implementation of `interpolate_by`! However, I have a use case where I'd like to interpolate a `Float64` column by another `Float64` column using any of the [`scipy` methods](https://docs.scipy.org/doc/scipy/tutorial/interpolate/1D.html), but the current implementation of `interpolate_by` only accepts `Date`, `Datetime`, `Int64`, `Int32`, `UInt64`, or `UInt32` as arguments to `by`. 

Would this be possible to implement?

**Comment by MarcoGorelli** [comment]
hi @MKDJr 

i'm not sure I understand the request, as you can't currently pass a scipy method to interpolate_by? could you clarify please?

**Comment by MKDJr** [comment]
Sure! My request is to expand the accepted types for the `by` argument of `interpolate_by` to include the `Float64` type.

**Comment by MarcoGorelli** [comment]
Sure, thanks - just noting though that even if Float64 type was allowed, it wouldn't automatically unlock the linked scipy methods, as only linear interpolation is currently supported

Maybe that's an idea for a polars plugin though - `polars-interpolate`, with lots of fancy interpolation methods which might be out-of-scope for Polars itself

**Comment by agossard** [comment]
Hi All. I’ve started working on this. Will have Marco review PR when it’s done. I am also planning on adding an extrapolate option, looking to match default behavior of np.interp

**Comment by CoffeeMarten** [comment]
Just want to upvote! Was very happy to see interpolate_by but my first use I'm interpolating by floats... worked around by casting/dividing but this will greatly increase flexibility.
