### ISSUE TITLE
`read_csv` ignores the `columns` parameter when reading an empty CSV file with header

### ISSUE THREAD

**Issue by lucasnanni** [pola-rs/polars#16811]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from io import StringIO

empty_csv = StringIO(
    "a,b,c\n"
)

# should return an empty dataframe with only column "b", 
# but it returns an empty dataframe with all the columns ("a", "b", and "c")
print(pl.read_csv(empty_csv, columns=["b"]))
```
**Result:**
```
shape: (0, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
└─────┴─────┴─────┘
```
**Expected result:**
```
shape: (1, 1)
┌─────┐
│ b   │
│ --- │
│ str │
╞═════╡
└─────┘
```

### Issue description

The `columns` parameter in `read_csv` is ignored when an empty CSV file (containing only the header) is read. As a result, an empty dataframe containing all columns, not just the selected ones, is returned. This issue is particularly troublesome when multiple files are read using a glob pattern in the `source` parameter, preventing the dataframes from being concatenated at the end.

### Expected behavior

When provided with an empty CSV file with a header, the `read_csv` function should return an empty dataframe containing only the columns provided in the `columns` parameter.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-6.8.0-35-generic-x86_64-with-glibc2.39
Python:               3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
This is fixed on main: 

- https://github.com/pola-rs/polars/pull/16739
