### ISSUE TITLE
Add inline XOR  (`^`) operator for selectors

### ISSUE THREAD

**Issue by jeroenjanssens** [pola-rs/polars#16822]
### Description

Selectors support inline AND (`&`), OR (`|`), and NOT (`~`) operators, but not yet the inline XOR (`^`) operator. Might as well add it for consistency sake. The `cs.xor()` method does work, so adding the inline version shouldn't be too much work.

**Comment by ritchie46** [comment]
I will tag @alexander-beedie on this one, given this are the selectors.

**Comment by alexander-beedie** [comment]
Done ;)

**Comment by jeroenjanssens** [comment]
Thank you very much, @alexander-beedie. That was quick!
