### ISSUE TITLE
Inconsistency in constructing dataframes with timezone-aware datatypes

### ISSUE THREAD

**Issue by maxzw** [pola-rs/polars#16823]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    schema={"dt": pl.Datetime(time_zone="Europe/Amsterdam")},
    data=[
        datetime(2021, 1, 1, 12),
        datetime(2021, 1, 1, 13),
    ],
)
print(df)

df = pl.DataFrame(
    schema={"dt": pl.Datetime(time_zone="Europe/Amsterdam")},
    data=[
        [datetime(2021, 1, 1, 12)],
        [datetime(2021, 1, 1, 13)],
    ],
)
print(df)
```

### Log output

```shell
shape: (2, 1)
┌────────────────────────────────┐
│ dt                             │
│ ---                            │
│ datetime[μs, Europe/Amsterdam] │
╞════════════════════════════════╡
│ 2021-01-01 12:00:00 CET        │
│ 2021-01-01 13:00:00 CET        │
└────────────────────────────────┘
shape: (2, 1)
┌────────────────────────────────┐
│ dt                             │
│ ---                            │
│ datetime[μs, Europe/Amsterdam] │
╞════════════════════════════════╡
│ 2021-01-01 13:00:00 CET        │
│ 2021-01-01 14:00:00 CET        │
└────────────────────────────────┘
```

### Issue description

Depending on wether the dataframe is initialised as a list of lists or list of items it gives different results.

### Expected behavior

I would expect both dataframes to be the same.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.17.4
fastexcel:            <not installed>
fsspec:               2023.9.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.2
nest_asyncio:         1.6.0
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.2
pyarrow:              14.0.1
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by maxzw** [comment]
@MarcoGorelli you stated in https://github.com/pola-rs/polars/issues/16297 the following:

> "naive datetime, time zone => parse into given time zone. ✅ same"

Apparently this does not always seem to be true!

**Comment by maxzw** [comment]
Another example:
```python
df = pl.DataFrame(
    schema={"value": pl.Struct({"dt": pl.Datetime(time_zone="Europe/Amsterdam")})},
    data=[
        [{"dt": datetime(2021, 1, 1, 12)}],
        [{"dt": datetime(2021, 1, 1, 13)}],
    ],
)
print(df)
```
```shell
shape: (2, 1)
┌────────────────────────────────┐
│ dt                             │
│ ---                            │
│ datetime[μs, Europe/Amsterdam] │
╞════════════════════════════════╡
│ 2021-01-01 13:00:00 CET        │
│ 2021-01-01 14:00:00 CET        │
└────────────────────────────────┘
```

**Comment by MarcoGorelli** [comment]
thanks @maxzw for reporting

this looks quite problematic

fortunately, 1.0 is just around the corner, so it's the perfect moment to address this

**Comment by MarcoGorelli** [comment]
Some extra logic needs adding here:

https://github.com/pola-rs/polars/blob/4bbdac3cc22a51ef24b651a33dc7bde0413a3d46/crates/polars-core/src/frame/row/av_buffer.rs#L96-L102

which should be (I think, will check it carefully when I have more time) something like

```
match (tz_l, tz_r) {
   Some(tz_l), None => val.replace_time_zone(Some(tz_l)),
   None, Some(tz_r) => val.convert_time_zone(Some("UTC")),
   None, None => val,
   Some(tz_l), Some(tz_r) => val.convert_time_zone(Some(tz_l))
}
```

**Comment by MarcoGorelli** [comment]
Right, so to summarise, one constructor follows PyArrow (convert everything to the given time zone, naive datetimes get converted as if from UTC), and the other follows pandas (for naive datetimes _replace_ their time zone with the dtype's one, for tz-aware ones _convert_ to the dtype's one):
```python
In [15]: pl.DataFrame([[datetime(2020,1,1)], [datetime(2020,1,2)]], schema={'a': pl.Datetime('us', 'Europe/Amsterdam')})
Out[15]:
shape: (2, 1)
┌────────────────────────────────┐
│ a                              │
│ ---                            │
│ datetime[μs, Europe/Amsterdam] │
╞════════════════════════════════╡
│ 2020-01-01 01:00:00 CET        │
│ 2020-01-02 01:00:00 CET        │
└────────────────────────────────┘

In [16]: pa.table({'a': pa.array([datetime(2020, 1, 1)], type=pa.timestamp('us', 'Europe/Amsterdam'))})['a'][0]
Out[16]: <pyarrow.TimestampScalar: '2020-01-01T01:00:00.000000+0100'>

In [17]: pl.DataFrame({'a': [datetime(2020,1,1), datetime(2020,1,2)]}, schema={'a': pl.Datetime('us', 'Europe/Amsterdam')})
Out[17]:
shape: (2, 1)
┌────────────────────────────────┐
│ a                              │
│ ---                            │
│ datetime[μs, Europe/Amsterdam] │
╞════════════════════════════════╡
│ 2020-01-01 00:00:00 CET        │
│ 2020-01-02 00:00:00 CET        │
└────────────────────────────────┘

In [18]: pd.DataFrame([[datetime(2020, 1, 1)]], dtype='datetime64[us, Europe/Amsterdam]')
Out[18]:
                          0
0 2020-01-01 00:00:00+01:00
```

Well, this sucks. Whichever direction Polars goes in, is going to break someone's code

I think the simplest and most predictable thing to do might be to:
- consistently follow the PyArrow behaviour here, as it's simpler and easier to teach
- always raise a user warning when constructing a dataframe with naive datetimes and a tz-aware dtype. For nested dtypes this may not be possible without a performance hit, but if it can at least be done in other cases, it should save a lot of headaches

What an unfortunate situation

I'll try putting together a PR to do the above suggestion, then we'll see how bad it is

**Comment by deanm0000** [comment]
I think this is what i tried to address with https://github.com/pola-rs/polars/pull/14211 but it's just been pending ¯\_(ツ)_/¯

**Comment by MarcoGorelli** [comment]
> I think this is what i tried to address with https://github.com/pola-rs/polars/pull/14211 

I think it's not quite the same - this issue is about the `replace` vs `convert` inconsistency (even though the result dtype is the same), the linked issues in #14211 are about the resulting dtype (even though they consistently convert to UTC)

> but it's just been pending ¯_(ツ)_/¯

Sorry about that - will get to it after this, it might simplify the logic

**Comment by stinodego** [comment]
Thanks for working this one out!

> consistently follow the PyArrow behaviour here, as it's simpler and easier to teach

Agree, this seems the most intuitive to me.
