### ISSUE TITLE
Suggestion: Order modules to get better method order in docs

### ISSUE THREAD

**Issue by bluss** [pola-rs/polars#1683]
This is a suggestion. I hope it could be helpful even if I don't have a PR.

The order methods are shown in docs depends on the order the compiler sees the method, and it follows the modules depth-first from the root of the crate. Looking a big types like `DataFrame`, it could order basic methods before other methods by changing module order in other places in the crate. This is something we learned in ndarray, which also has a bunch of methods on the same type.

The suggestion is to put the most basic methods first - constructors and simple accessors (think len, number of rows, etc), also generic mutators and iterators and then more specific methods and iterators.

**Comment by ritchie46** [comment]
Thanks for the suggestion, I did not know that. I really need to take the time to look the Rust generated docs, they are in quite some debt.

**Comment by stinodego** [comment]
This is a good suggestion, but we will not be getting to this anytime soon. When we have better organized our public API, we will give some thought on ordering the methods. But for now we will close this.
