### ISSUE TITLE
update object_store version 0.9 -> 0.10.1

### ISSUE THREAD

**Issue by Itayazolay** [pola-rs/polars#16854]
### Description

Hey,
Updating the dependency solve [this issue](https://github.com/apache/arrow-rs/issues/5466) for me.
Of course, there are other bug-fixes and improvements
I don't mind taking this, if you think it's a good issue for first-time contributers to polars
Thanks!

**Comment by stinodego** [comment]
Sure, you can bump the version to `0.10` in the `Cargo.toml` in the repo root, and then fix any issues that pop up (clippy is not happy).

**Comment by ion-elgreco** [comment]
@stinodego this is completed now
