### ISSUE TITLE
Providing nightly builds ?

### ISSUE THREAD

**Issue by Thomzoy** [pola-rs/polars#16861]
### Description

Due to the (relatively) complex build process of Polars and the really frequent codebase updates, what are your thoughts about providing nightly build ?
Thanks a lot and again congrats for the lib 🎉

**Comment by cmdlineluser** [comment]
Just in case it may be useful information:

I did notice while reading the website that nightly builds do exist - but they are not public. (they are for Enterprise Support subscribers)

> Private release channel with nightly builds

https://pola.rs/our-services/

**Comment by Thomzoy** [comment]
Right good call thanks! Closing this then.
