### ISSUE TITLE
Casting to pl.Date fails

### ISSUE THREAD

**Issue by olivier-lacroix** [pola-rs/polars#1687]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.16

#### What operating system are you using polars on?

Linux

#### Describe your bug.

Casting from str to dates fails

#### What are the steps to reproduce the behavior?

```python
import polars as pl
s = pl.Series("a", ["2020-01-01", "2020-01-02", "2020-01-03"])
s.cast(pl.Date)
```

#### What is the actual behavior?

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_560/3542784108.py in <module>
----> 1 s.cast(pl.Date)

/opt/conda/lib/python3.9/site-packages/polars/eager/series.py in cast(self, dtype, strict)
   1680         elif dtype == float:
   1681             dtype = Float64
-> 1682         return wrap_s(self._s.cast(str(dtype), strict))
   1683 
   1684     def to_list(self) -> tp.List[Optional[Any]]:

RuntimeError: Any(ComputeError("strict conversion of cast from Utf8 to Date failed. consider non-strict cast."))
```

#### What is the expected behavior?

Data successfully cast

**Comment by ritchie46** [comment]
You cannot cast a `Utf8` to a `Date`, you need to run `s.str.strptime(pl.Date)` or `s.str.strptime(pl.Date, fmt="%Y-%m-%d")`

**Comment by olivier-lacroix** [comment]
@ritchie46 , OK. In that case, [the example in the documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.cast.html) should be changed, as it is a cast from string to date.

**Comment by ritchie46** [comment]
> @ritchie46 , OK. In that case, [the example in the documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.cast.html) should be changed, as it is a cast from string to date.

Yes!
