### ISSUE TITLE
Difference with pandas left join caused by new coalesce flag

### ISSUE THREAD

**Issue by maxzw** [pola-rs/polars#16879]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
left = pd.DataFrame({'a': [1,2]})
right = pd.DataFrame({'a': [2,3], 'b': [3,4]})
left.merge(right, on='a', how='left')

# Resulting in:
#   a    b
#0  1  NaN
#1  2  3.0

left = pl.DataFrame({'a': [1,2]})
right = pl.DataFrame({'a': [2,3], 'b': [3,4]})
left.join(right, on='a', how='left')

# Resulting in:
# shape: (2, 3)
# ┌─────┬─────────┬──────┐
# │ a   ┆ a_right ┆ b    │
# │ --- ┆ ---     ┆ ---  │
# │ i64 ┆ i64     ┆ i64  │
# ╞═════╪═════════╪══════╡
# │ 1   ┆ null    ┆ null │
# │ 2   ┆ 2       ┆ 3    │
# └─────┴─────────┴──────┘
```

### Issue description

In https://github.com/pola-rs/polars/issues/13441 it was stated joins should follow pandas when doing left joins, where joins with `left_on` and `right_on` were aligned between pandas and polars. However, this created a misalignment when only using `on`.

### Expected behavior

I would expect the join operation with `on` argument to coalesce columns by default.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-alpha.1
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.17.4
fastexcel:            <not installed>
fsspec:               2023.9.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.2
nest_asyncio:         1.6.0
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.2
pyarrow:              14.0.1
pydantic:             2.7.1
pyiceberg:            <not installed>
sqlalchemy:           2.0.20
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by s-banach** [comment]
Their reasoning is that left/right/full are all outer joins, and that information is lost by defaulting to `coalesce=True` for outer joins.

Personally, I practically never use `coalesce=False`, and I agree this will confuse some pandas users.
But they did it intentionally, with sound reasoning.
