### ISSUE TITLE
It is not possible to create Arrays with zero width

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#16878]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.Series([[]], dtype=pld.Array(pld.Int8, 0))
```

This gives:
```
polars.exceptions.ComputeError: not all elements have the specified width 0
```

### Issue description

It is not possible to instantiate zero-width arrays

### Expected behavior

It should be possible to create zero-width Arrays.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-6.6.32-x86_64-with-glibc2.39
Python:               3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.17.4
fastexcel:            <not installed>
fsspec:               2024.3.0
gevent:               24.2.1
hvplot:               0.9.2
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.1
pyarrow:              16.0.0
pydantic:             2.6.3
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by deanm0000** [comment]
> It should be possible to create zero-width Arrays.

buy why?

**Comment by stinodego** [comment]
I also ran into this when updating the `reshape` implementation. NumPy allows Arrays with zero dimensions. When I asked Ritchie, he said to keep this constraint of size > 0 for now. But I guess ideally we would support this.

**Comment by cjackal** [comment]
> > It should be possible to create zero-width Arrays.
> 
> buy why?

If we were to fully support the array counterpart of `.list.concat`, I guess the length 0 array (acting as the identity) makes sense and will have its virtue for many application. We can do no-op for list counterpart with length 0 lists.

**Comment by KDruzhkin** [comment]
> I also ran into this when updating the reshape implementation. NumPy allows Arrays with zero dimensions.

Cf. https://github.com/pola-rs/polars/issues/16522.
