### ISSUE TITLE
join throws error

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1688]
Hi; 

I'm using 0.10.16. when I'm joining it throws an error below

`implementation error, cannot get ref Int32 from Date`

Code:
`summarizedData.join(template, on=["monthYearTravel", "origcountry","purchase_date"], how="left")`

Data --> Template
![image](https://user-images.githubusercontent.com/19631334/140638385-a9d51174-d1aa-4d63-81f4-e2c3070aa1a9.png)

Data --> summarizedData
![image](https://user-images.githubusercontent.com/19631334/140638412-11411cad-4fe6-4a53-a09e-ec33031d62ee.png)

Thanks.

**Comment by ritchie46** [comment]
#1692 shows my tests

**Comment by hakantekbas** [comment]
Hi @ritchie46 ;

Before joining, I convert data from pandas. When it converts, no error occured.  

I checked your test, If I did not miss, you only tested groupby. groupby is running in my case

> summarizedData = pl.from_pandas(summarizedData.reset_index())
> Template = pl.from_pandas(Template.reset_index())

**Comment by ritchie46** [comment]
> I checked your test, If I did not miss, you only tested groupby. g

This is my test:

```python
    # this just flexes the dispatch a bit
    dfa = pl.DataFrame(
        {
            "a": ["a", "b", "c"],
            "b": [1, 2, 3],
            "date": ["2021-01-01", "2021-01-02", "2021-01-03"],
            "datetime": [13241324, 12341256, 12341234],
        }
    ).with_columns(
        [pl.col("date").str.strptime(pl.Date), pl.col("datetime").cast(pl.Datetime)]
    )
    dfa = pl.concat([dfa, dfa], rechunk=False)

    dfb = pl.DataFrame(
        {
            "a": ["a", "b", "c"],
            "b": [1, 2, 3],
            "date": ["2021-01-01", "2021-01-02", "2021-01-03"],
            "datetime": [13241324, 12341256, 12341234],
        }
    ).with_columns(
        [pl.col("date").str.strptime(pl.Date), pl.col("datetime").cast(pl.Datetime)]
    )

    dfa.join(dfb, on=["a", "b", "date", "datetime"], how="left")
    dfa.join(dfb, on=["a", "b", "date", "datetime"], how="inner")
    dfa.join(dfb, on=["a", "b", "date", "datetime"], how="outer")
    dfa.join(dfb, on=["date", "datetime"], how="left")
    dfa.join(dfb, on=["date", "datetime"], how="inner")
    dfa.join(dfb, on=["date", "datetime"], how="outer")
    dfa.join(dfb, on=["date", "datetime", "a"], how="left")
    dfa.join(dfb, on=["date", "datetime", "a"], how="inner")
    dfa.join(dfb, on=["date", "a"], how="outer")
    dfa.join(dfb, on=["date", "a"], how="left")
    dfa.join(dfb, on=["date", "a"], how="inner")
    dfa.join(dfb, on=["date", "a"], how="outer")
    dfa.join(dfb, on=["date"], how="outer")
    dfa.join(dfb, on=["date"], how="left")
    dfa.join(dfb, on=["date"], how="inner")
    dfa.join(dfb, on=["date"], how="outer")
```

Are you certain you are not joining an integer column with a `Date` column?

**Comment by hakantekbas** [comment]
my code is also running when I limit number of rows 10.000, but when whole data is passed, it throws error. How should I proceed?

**Comment by hakantekbas** [comment]
can you run code below in your computer. it throws same error.

`    dfa = pd.DataFrame(
            {
                "a": ["a", "b", "c"]*10000,
                "b": [1, 2, 3]*10000,
                "date": ["2021-01-01", "2021-01-02", "2021-01-03"]*10000,
                "datetime": [13241324, 12341256, 12341234]*10000,
            }
        )

    dfb = pd.DataFrame(
            {
                "a": ["a", "b", "c"] * 10000,
                "b": [1, 2, 3] * 10000,
                "date": ["2021-01-01", "2021-01-02", "2021-01-03"] * 10000,
                "datetime": [13241324, 12341256, 12341234] * 10000,
            }
        )

    dfa["date"] = pd.to_datetime(dfa.date)    
    dfb["date"] = pd.to_datetime(dfb.date)    

    aa=pl.from_pandas(dfa).join(pl.from_pandas(dfb),on=["a","date"])`

**Comment by ritchie46** [comment]
Thanks, I can now reproduce it.
