### ISSUE TITLE
Panic on SchemaMismatch

### ISSUE THREAD

**Issue by tkellogg** [pola-rs/polars#16882]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
a = pl.DataFrame({'a': [1 for _ in range(10)]})
a.extend(a.select(pl.lit(0).alias("a")))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/frame/mod.rs:980:36:
called `result::unwrap()` on an `err` value: schemamismatch(errstring("type int32 is incompatible with expected type int64"))
traceback (most recent call last):
  file "<stdin>", line 1, in <module>
  file "/users/tim/library/caches/pypoetry/virtualenvs/emopoint-ulihhobz-py3.10/lib/python3.10/site-packages/polars/dataframe/frame.py", line 6973, in extend
    self._df.extend(other._df)
pyo3_runtime.panicexception: called `result::unwrap()` on an `err` value: schemamismatch(errstring("type int32 is incompatible with expected type int64"))
```

### Issue description

It panics when `vstack`-ing a column with different data types, here `int32` & `int64`.

### Expected behavior

It shouldn't panic, it should give a real error.

Better: python literal ints should always be the same type and this shouldn't happ

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>
###

**Comment by deanm0000** [comment]
As an alternative

```
pl.concat([a, a.select(pl.lit(0).alias("a"))], how='vertical_relaxed')
```
does what you expect.

It makes sense to me that a python int would be treated the same between the different constructors. I'm not sure if there's a reason for the difference or it is just chance. @stinodego what do you think?

**Comment by tkellogg** [comment]
In addition, I wouldn't mind sending a patch for this. I would have, but I wanted to check first that it wasn't more complicated than it appeared. LMK

**Comment by stinodego** [comment]
A patch to turn the panic into a proper error is welcome!

>  It makes sense to me that a python int would be treated the same between the different constructors. I'm not sure if there's a reason for the difference or it is just chance. @stinodego what do you think?

There is a reason for the existing behavior, though off the top of my head I don't know why. Something to do with the difference between eager and lazy.

**Comment by tkellogg** [comment]
PR is ready to be reviewed. Pretty simple, I didn't try to address the inconsistent `int` handling. 

@stinodego, if I were to guess, I bet the problem is that lazy Series can't infer a `int32` without scanning it first, so it assumes `int64`. Whereas `lit` can trivially assume `int64`, and does. I'm not sure there's an easy way to fix this without breaking backward compatibility.

**Comment by ritchie46** [comment]
>  I didn't try to address the inconsistent int handling.

The `lit` int handling isn't something trivial. Literals should behave different from the constructor. They are dynamic and often need to depend on the operation to define their required type. E.g. multiply a `int8` column with `lit(1)` should not upcast the `int8` column.

If the `lit` is used in isolation, we try to fit a reasonably small dtype that fits. Currently that is `int32`. Smaller often leads to unexpected overflows. If the literal given doesn't fit `int32` it is upcast to `int64` or even `uint64` if needed.

For the constructor we need to be more conservative as we don't want to inspect the whole array up front, whereas with a literal this is cheap, so we go with `int64`. If you need other behavior, you need to specify your dtype.

In a future version it might be possible that we recognize the dynamic literal usage across contexts and recognized that you were concatting to a `i64`, but this isn't trivial and I think also not worth the compute cost.
