### ISSUE TITLE
Schema validation is deferred until an explicit schema/columns call as opposed to at definition time

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#16886]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

ldf = pl.LazyFrame({"a": [1,2,3]})
ldf = ldf.select(pl.col("b")) # this doesn't throw
ldf.schema # throws here, which seems late?
```

### Issue description

The definition of an invalid lazyframe is allowed, i thought that schema is tracked the entire time?

### Expected behavior

I'd expect it to fail when you do a select with a column that doesn't exist in the schema.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-5.10.217-183.860.x86_64-x86_64-with-glibc2.26
Python:               3.11.7 (main, Dec  5 2023, 22:00:36) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
May be relevant: https://github.com/pola-rs/polars/issues/16624#issuecomment-2142026376

> Polars will resolve queries upon collection, not upon DSL creation. This is important as we want to be able to send the query to another machine. At that point the schema will be resolved not when you write the query.

**Comment by alexander-beedie** [comment]
The call to "schema" will trigger the compute that establishes the execution plan, and that's when it finds out the column isn't present (a call to `.explain()` or `.collect()` would also raise an error for the same reason). Essentially lazy mode has become _even_ lazier, so that it can better scale across more use-cases (cloud, for instance) 😅
