### ISSUE TITLE
SQLSyntaxError: invalid 'part' for EXTRACT/DATE_PART: 'year'

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#16880]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import date
import polars as pl

pl.DataFrame({"x": date(2024, 6, 11)}).sql(
    "select date_part(x, 'year') as xy from self"
)
```

### Issue description

I believe #16767 inadvertently changed the argument order from `date_part(column, part)` to `date_part(part, column)`.

### Expected behavior

Keep working the same.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-alpha.1
Index type:           UInt32       
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            0.10.4
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             2.7.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.30
torch:                2.3.0+cpu
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
That wasn't inadvertent - it's a fix; we accidentally had the order of the DATE_PART params backwards to start with 😅 

`DATE_PART` syntax _should_ be:
```
date_part(part, column)
```
Examples:
* [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?view=sql-server-ver16)
* [PostgreSQL](https://www.geeksforgeeks.org/postgresql-date_part-function/)
* [DuckDB](https://duckdb.org/docs/sql/functions/date#date_partpart-date)
* etc...

You can use `EXTRACT` to be consistent across all versions for now.
