### ISSUE TITLE
`hist` returns extra bin when `bin_count` is specified

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#16912]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.arange(100, eager=True).hist(bin_count=5)
# shape: (6, 3)
```

### Issue description

The `bin_count` parameter should specify the number of bins in the output, but instead it specifies the edge count (one less than the number of bins). Even the [example in the docs](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.hist.html) specifies 4 bins, but returns data aggregated into 5 bins.

In addition, the description for the `bin_count` parameter states "If no bins provided, this will be used to determine the distance of the bins". This is a little vague--is the distance the size of the bins? Apparently not; if we reduce the distance between the elements by 100, we still get the same number of bins:

```python
(pl.arange(100, eager=True)/100).hist(bin_count=20) 
# shape: (21, 3)
```

### Expected behavior

Should return `bin_count` bins instead of `bin_count + 1` bins.

### Installed versions

main

**Comment by stinodego** [comment]
Good catch. Should be a simple fix.

**Comment by mcrumiller** [comment]
It looks like we always return a bin starting at (-inf, x) where x is `min(s) - 1`, and this bin always returns 0.

**Comment by mcrumiller** [comment]
Yeah. I'll take a look into this today.

**Comment by mcrumiller** [comment]
I believe the issue is resolved by the linked PR and just needs to be reviewed.
