### ISSUE TITLE
Concatenating to a list column using another column throws PanicException with empty DataFrame

### ISSUE THREAD

**Issue by bkos** [pola-rs/polars#16924]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(schema={'a': pl.Int16, 'b': pl.List(pl.String)})

# Works
df.with_columns(pl.col('b').list.concat([1]))

# Breaks
df.with_columns(pl.col('b').list.concat([pl.col('a').cast(pl.String)]))
```

### Log output

```shell
PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot reshape len 0 into shape [-1, 1]"))
```

### Issue description

Concatenating to a list column using another column throws PanicException with empty DataFrame

### Expected behavior

To return empty DataFrame

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Windows-10
Python:               3.11.7
```

</details>

**Comment by Object905** [comment]
Can reproduce. It was working on earlier versions, but after upgrading to 1.2 it's still there
