### ISSUE TITLE
`PanicException` with empty DataFrame when temporal column is used with another method and `over`

### ISSUE THREAD

**Issue by bkos** [pola-rs/polars#16927]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    schema={'Time': pl.Datetime('ms'), 'Number': pl.Int32, 'Group': pl.Int32}
)

df.with_columns(pl.col('Time').truediv(1_000).over('Group'))
```

### Log output

```shell
PanicException: not implemented for dtype Unknown(Any)
```

### Issue description

`PanicException` with empty DataFrame when temporal column is used (numerical works fine) with another method (e.g. `truediv` or `shift`) and `over`

### Expected behavior

To return empty DataFrame

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Windows-10
Python:               3.11.7
```

</details>

**Comment by ritchie46** [comment]
This should raise. Division of `Datetime` should not be allowed.

**Comment by bkos** [comment]
My use case was actually the division of `duration[ms]` to get the time in seconds, where is also panics:
```python
df.with_columns(pl.col('Time').diff().truediv(1_000).over('Group'))
```
