### ISSUE TITLE
Explode after concatenating frames silently drops null values

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#16923]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df1 = pl.DataFrame({"foo": [["hello", "world"], ["goodbye"]]})
df2 = pl.DataFrame({"foo": [None]}, schema={"foo": pl.List(pl.Utf8)})

pl.concat([df1, df2], how="diagonal", rechunk=True).explode("foo")
shape: (3, 1)
┌─────────┐
│ foo     │
│ ---     │
│ str     │
╞═════════╡
│ hello   │
│ world   │
│ goodbye │
└─────────┘

## It should return this:
df3 = pl.DataFrame({"foo": [["hello", "world"], ["goodbye"], None]})
df3.explode("foo")

shape: (4, 1)
┌─────────┐
│ foo     │
│ ---     │
│ str     │
╞═════════╡
│ hello   │
│ world   │
│ goodbye │
│ null    │
└─────────┘

## TEST
assert_frame_equal(
    pl.concat([df1, df2], how="diagonal", rechunk=True).explode("foo"),
    df3.explode("foo")
)
```

### Issue description

Concatenating two dataframes with a list column where one frame has a null value in this column. After exploding this list column it will silently drop rows with the null value. 

Setting rechunk to False or True has no impact.

### Expected behavior

Don't silently drop rows.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-alpha.1
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:               3.10.12 (main, Aug  9 2023, 14:47:34) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.18.1
fastexcel:            0.10.4
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.23.5
openpyxl:             3.1.4
pandas:               1.5.3
pyarrow:              16.1.0
pydantic:             2.7.4
pyiceberg:            <not installed>
sqlalchemy:           1.4.52
torch:                2.2.2+cpu
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by deanm0000** [comment]
I'm guessing the issue is that the length of the null is 0 and so it gets 0 new rows after the explode.

As a workaround, this works...

```
pl.concat([df1.with_columns(pl.col('foo').fill_null([None])), df2.with_columns(pl.col('foo').fill_null([None]))], how="diagonal", rechunk=True).explode("foo")
```
or
```
def fill_list(df):
    return df.with_columns(pl.col(pl.List).fill_null([None]))
pl.concat([df1.pipe(fill_list), df2.pipe(fill_list)])
```


btw, if you have tests list this handy, I'd think (although can't speak officially) that they'd be welcome in a PR. It'd help you because whatever fix caused this new bug wouldn't have got through.

**Comment by deanm0000** [comment]
Another weird thing...


```
pl.concat([df2,df1]).explode('foo')
```

works as expected but

```
pl.concat([df2,df2,df1]).explode('foo')
```

and

```
pl.concat([df2,df2]).explode('foo')
```

returns 0 rows.

**Comment by ion-elgreco** [comment]
> btw, if you have tests list this handy, I'd think (although can't speak officially) that they'd be welcome in a PR. It'd help you because whatever fix caused this new bug wouldn't have got through.

I just created this test on the fly since I noticed what the issue was but it appeared in a long test in of our algorithms

**Comment by ion-elgreco** [comment]
> Another weird thing...
> 
> ```
> pl.concat([df2,df1]).explode('foo')
> ```
> 
> works as expected but
> 
> ```
> pl.concat([df2,df2,df1]).explode('foo')
> ```
> 
> and
> 
> ```
> pl.concat([df2,df2]).explode('foo')
> ```
> 
> returns 0 rows.

That's very weird indeed..

**Comment by ritchie46** [comment]
@coastalwhite could you take a look at this one? I expect the `can_fast_explode` metatdata is set incorrectly.
