### ISSUE TITLE
"has_header" in "read_options" for `read_excel` has inconsistent behavior across engines

### ISSUE THREAD

**Issue by toan-quach** [pola-rs/polars#16944]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

**If I use the default engine option ("xlsx2csv") it returns the expected result**
Code:
```python
pl_data = pl.read_excel(
    "example.xlsx", read_options={"has_header": False}, sheet_name="Sheet1"
)
```
Result:
![image](https://github.com/pola-rs/polars/assets/93168955/079b2fe2-4d14-4987-bb77-e35e92e1dbe3)

**If I use "openpyxl" as the engine, it returns an unexpected result**
Code:
```python
pl_data = pl.read_excel(
    "example.xlsx", read_options={"has_header": False}, sheet_name="Sheet1", engine="openpyxl"
)
```
Result:
![image](https://github.com/pola-rs/polars/assets/93168955/fab52ddb-738e-4272-b126-ddc3b067a896)

File used:
[example.xlsx](https://github.com/user-attachments/files/15831251/example.xlsx)

### Issue description

When I use the default engine _xlsx2csv_ to read the Excel file **without** header, it returns the correct result, with the "supposed" header being one of the rows in the DataFrame. But when I switch to _openpyxl_ (the engine I'm using) and read the file again, also with no header, the "supposed" header is now read as the header and not one of the rows of the DataFrame. I have provided images and code to reproduce.

### Expected behavior

I want to use _openpyxl_ as my engine and read the Excel file without a header. I expect the 1st row in the example.xlsx file to be 1 of the row in the DataFrame and not as the DataFrame header. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             macOS-13.6.3-arm64-arm-64bit
Python:               3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.12.2
gevent:               23.7.0
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.5.9
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               1.3.5
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.16
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.2.0
```

</details>

**Comment by toan-quach** [comment]
After reading more into the source code, I noticed that the `read_options` is passed to the "load" excel function of the engine. In `openpyxl` case, the `load_workbook` function doesn't have any ignore header related parameter. Hence, I concluded that this is a limitation of the `openpyxl` engine itself. 

@ritchie46 Do let me know if my understanding is correct 😄

**Comment by alexander-beedie** [comment]
> After reading more into the source code, I noticed that the `read_options` is passed to the "load" excel function of the engine. In `openpyxl` case, the `load_workbook` function doesn't have any ignore header related parameter. Hence, I concluded that this is a limitation of the `openpyxl` engine itself.

You are correct ;)  With the above PR I'm moving to handling it on our side; note that the default engine is now "calamine" and it is much, _much_ faster than either of the other two engines (~10x). If you can use that one instead, I'd recommend it.
