### ISSUE TITLE
`LazyFrame.slice()` does not stream

### ISSUE THREAD

**Issue by douglas-raillard-arm** [pola-rs/polars#16955]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

path = 'large.parquet'
#  path = 'cpu_idle.parquet'
df = pl.scan_parquet(path)


def iter_batches(df, batch_size):
    def get_batch(df, offset, batch_size):
        batch = df.slice(offset, batch_size)
        batch = batch.collect()
        return batch

    batch = get_batch(df, 0, batch_size)
    # Yield once even if we got passed an empty LazyFrame
    yield batch
    offset = len(batch)
    if offset:
        while True:
            batch = get_batch(df, offset, batch_size)
            len_ = len(batch)
            if len_:
                offset += len_
                yield batch
            else:
                break


for batch in iter_batches(df, 100):
    print(batch)

```

### Log output

```shell
The first batch is printed, subsequent batches are not printed as it runs out of memory before being able to collect the 2nd batch.
```

### Issue description

The doc hints that `slice()` should work in streaming mode: https://docs.pola.rs/user-guide/concepts/streaming/#when-is-streaming-available

However, only the first `slice()` call with `offset=0` returns in constant memory. The 2nd `slice()` seems to load the entire dataset in memory and my machine crashes before being able to collect it. 

This issue was observed while trying to find a workaround for: https://github.com/pola-rs/polars/issues/10683

### Expected behavior

Each slice should be collected in constant memory regardless of the offset, or `slice` removed from the [streaming doc](https://docs.pola.rs/user-guide/concepts/streaming/#when-is-streaming-available)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-5.15.0-105-generic-x86_64-with-glibc2.31
Python:               3.12.3 (main, Apr 27 2024, 19:00:26) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Not all slices are streamable yet. This is something we work on, but isn't a bug. We don't guarantee streaming for all variants of an operation.
