### ISSUE TITLE
`Expr.replace` equivalent for looking up a value in a sequence using an integer index column

### ISSUE THREAD

**Issue by MarkRotchell** [pola-rs/polars#16961]
### Description

I've tried to find a way to map from a column of integers, representing indices, to a sequence of values which are then selected based on index. I can't find a natural way to do it, so am suggesting a new method for Expr. If I'm missing something obvious then please do point it out.

Functionality would look like the below (I suggest "choose" as the method name, but am open to suggestions).

```python

>>>df = pl.DataFrame({'idx':[4,2,-2]})
>>>df.with_columns(chosen=pl.col('idx').choose(['a','b','c','d','e']))
shape: (3, 1)
┌─────┬────────┐
│ idx ┆ chosen │
│ --- ┆ ---    │
│ i64 ┆ str    │
╞═════╪════════╡
│ 4   ┆ e      │
│ 2   ┆ c      │
│ -2  ┆ d      │
└─────┴────────┘
```

There are a few `get` or `gather` functions in the API that do the opposite, i.e. they use the column values to select from and the user provides the indices, but I can't find anything that works in this direction. 

If you have all positive indices, then you can get equivalent functionality with either of the below:

```python
>>>pl.col('idx').replace(dict(enumerate(['a','b','c','d','e'])))
>>>pl.col('idx').replace(range(5),['a','b','c','d','e'])
>>>pl.Series(['a','b','c','d','e']).gather(df.get_column('idx'))
```

However, this won't work for negative indices and they all feel a bit clunky.

Potentially this functionality could be implemented as syntactic sugar on `Expr.replace` - similar to how you can currently pass a mapping as a single argument - if you pass a sequence, and the base expression is an integer, then the above behaviour occurs.

**Comment by cmdlineluser** [comment]
I don't have anything useful to add - but just thought I'd clarify that `gather` does handle negative indices.

```python
>>> df.with_columns(chosen = pl.col.idx.map_batches(pl.Series(['a', 'b', 'c', 'd', 'e']).gather))
shape: (3, 2)
┌─────┬────────┐
│ idx ┆ chosen │
│ --- ┆ ---    │
│ i64 ┆ str    │
╞═════╪════════╡
│ 4   ┆ e      │
│ 2   ┆ c      │
│ -2  ┆ d      │
└─────┴────────┘
```

**Comment by MarkRotchell** [comment]
Ah, you're right, seems I'm a few months behind I my releases, I was working in 0.20.0 and negative indices for `gather` arrived in 0.20.3. 

Thanks for idea of using `map_batches` like that. Still, I think would be a good idea to have a first-class member of `Expr` for something that feels as simple as this.

**Comment by nameexhaustion** [comment]
This is already possible without `map_batches` - either of these 2 solutions will work

```python
df.with_columns(
    # We `explode` because `lit` creates a single row-value from python literals
    chosen=pl.lit(["a", "b", "c", "d", "e"]).explode().gather(pl.col("idx"))
)
df.with_columns(
    # Passing a `Series` to `lit` instead will directly create a column
    chosen=pl.lit(pl.Series(["a", "b", "c", "d", "e"])).gather(pl.col("idx"))
)
```

Your request isn't really asking for `replace` functionality, but rather `gather` functionality.
