### ISSUE TITLE
[Python] please add a `rechunk=False` kwarg in `read_delta()` to align it to `read_parquet()`

### ISSUE THREAD

**Issue by p3i0t** [pola-rs/polars#16982]
### Description

So far, `pl.read_delta()` does not expose a rechunk kw argument like `pl.read_parquet()`. 

I checked out the implementation of pl.read_delta(), and found that inside `read_delta()`, it loads a delta_lake_table object, and converts it to a polars dataframe by calling `from_arrow()`.
[https://github.com/pola-rs/polars/blob/b6cd77d00c8c1959795fd7a2549094ad0c059612/py-polars/polars/io/delta.py#L146](url).

The `from_arrow()` has already exposed a `rechunk=True` argument.  So `pl.read_delta()` would _**always rechunk**_ and return a continous dataframe, which is not preferable if the resulting dataframe is huge, or in cases that users would like to rechunk when they feel necessary.

I think it would be better to add  `rechunk=False` to `pl.read_parquet()`, so that it aligns to `pl.read_parquet()`, where a default `rechunk=False` kw argument is exposed.  

The modification is trivial, simply change the two lines of  current code:
```python
def read_delta(...):
    ...
    return from_arrow(dl_tbl.to_pyarrow_table(columns=columns, **pyarrow_options))  # type: ignore[return-value]
```
to:
```python
def read_delta(..., rechunk=False):
    ...
    return from_arrow(dl_tbl.to_pyarrow_table(columns=columns, **pyarrow_options), rechunk=rechunk)  # type: ignore[return-value]
```

**Comment by ritchie46** [comment]
Yes, can you make a PR?
