### ISSUE TITLE
Document that `quantile` ignores `nan` values

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#16996]
### Description

I'm not sure if this is the desired behavior, but `quantile` currently ignores `nan` values, which is different from how numpy computes quantiles:

```python
import numpy as np
import polars as pl

arr = [0.0, 1.0, float("nan")]
np.quantile(arr, 0.5)
# nan

pl.Series(arr).quantile(0.5)
# 1.0
```

We treat `inf` different from numpy so this is probably ok, but it should be documented. Maybe should add `drop_nans` parameter?

**Comment by ritchie46** [comment]
This is desired behavior. Polars has a total order for `NaN` : https://docs.pola.rs/user-guide/concepts/data-types/overview/#floating-point
Citing: 
```
Any NaN compares equal to any other NaN, and greater than any non-NaN value.
```

So the nans will be positioned at the end of the array if you sort. Which thus also influences the quantile values.

**Comment by mcrumiller** [comment]
Thanks @ritchie46, wasn't aware of this.
