### ISSUE TITLE
Support NumPy 2.0

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16998]
Polars already partially supports NumPy 2.0.

We do not support temporal types yet (e.g. `datetime64`) - using these will result in a segfault. Support must first be implemented in the PyO3 `numpy` crate:
* Relevant issue: https://github.com/PyO3/rust-numpy/issues/409
* Relevant PR: https://github.com/PyO3/rust-numpy/pull/429

When support is implemented and a new release is available, we can upgrade and that should take care of it.

For now, we will pin to `numpy<2` in our pipelines.

**Comment by ritchie46** [comment]
If blocked, it isn't `p-high` at the moment. :D

**Comment by stinodego** [comment]
> If blocked, it isn't `p-high` at the moment. :D

Indeed. We should have something to mark "high importance" though - which this certainly is.

**Comment by braaannigan** [comment]
I've encountered a seg fault where another library is converting a Polars dataframe to numpy with numpy 2.0.0 and polars 0.20.31.
Downstream issue is here: https://github.com/Nixtla/mlforecast/issues/354

```python
import polars as pl
df = pl.from_repr("""┌───────────┬─────────────────────┬────────────┐
│ unique_id ┆ ds                  ┆ y          │
│ ---       ┆ ---                 ┆ ---        │
│ cat       ┆ datetime[ns]        ┆ f64        │
╞═══════════╪═════════════════════╪════════════╡
│ id_00     ┆ 2000-01-01 00:00:00 ┆ 17.519167  │
│ id_00     ┆ 2000-01-02 00:00:00 ┆ 87.799695  │
│ id_00     ┆ 2000-01-03 00:00:00 ┆ 177.442975 │
│ id_00     ┆ 2000-01-04 00:00:00 ┆ 232.70411  │
│ id_00     ┆ 2000-01-05 00:00:00 ┆ 317.510474 │
│ id_19     ┆ 2000-03-09 00:00:00 ┆ 28.541985  │
│ id_19     ┆ 2000-03-10 00:00:00 ┆ 33.841384  │
│ id_19     ┆ 2000-03-11 00:00:00 ┆ 38.878866  │
│ id_19     ┆ 2000-03-12 00:00:00 ┆ 43.675512  │
│ id_19     ┆ 2000-03-13 00:00:00 ┆ 49.603114  │
└───────────┴─────────────────────┴────────────┘""")
df["ds"].to_numpy()
```
This gives a seg fault.

**Comment by braaannigan** [comment]
@ritchie46 
In fact this is enough to produce a seg fault:
```python
import datetime

import polars as pl

pl.Series([datetime.datetime.now()]).to_numpy()
```

**Comment by stinodego** [comment]
Yes, we are familiar. Nothing we can do about it at the moment, see the linked issue.

**Comment by jmoralez** [comment]
> Nothing we can do about it at the moment

You could also pin numpy here https://github.com/pola-rs/polars/blob/14dd2ca74d420519391fd319dd59379d5a102151/py-polars/pyproject.toml#L52

in case you're planning a release soon, that'd ensure compatibility when installing `polars[numpy]`

**Comment by ritchie46** [comment]
Yes, we must pin numpy 1.0 until then.

**Comment by lesteve** [comment]
Bumped into this in scikit-learn #173800. I have to admit this I was a bit like "sorry what?" but I guess there is not much you can since numpy is an optional dependency. You can only hope that people do `pip install polars[numpy]` and not the more naive (as I did) `pip install polars numpy`

**Comment by pavelzw** [comment]
> At least the situation will be a bit better with polars 1.0 and conda-forge.

We can also do repodata Patches to retroactively pin to numpy<2 for older polars versions
