### ISSUE TITLE
Casting from `string` to `Date` fail using example from documentation

### ISSUE THREAD

**Issue by potter420** [pola-rs/polars#1702]
#### Are you using Python or Rust?
**Python**

#### What version of polars are you using?

`0.10.16`

#### What operating system are you using polars on?

Linux

#### Describe your bug.

Example on casting string to date seem to fail. Code was taken from the documentation on cast

#### What are the steps to reproduce the behavior?
```python
import polars as pl

s = pl.Series("a", ["2020-01-01", "2020-01-02", "2020-01-03"])
s.cast(pl.datatypes.Date)
```
#### What is the actual behavior?
```
RuntimeError: Any(ComputeError("strict conversion of cast from Utf8 to Date failed. consider non-strict cast."))
```

#### What is the expected behavior?

Either remove that from documentation or we're trying to fix this. IMO, removing it from documentation seem to be the best since str -> date/datetime need some special treatment :D

**Comment by ritchie46** [comment]
See #1691 and #1687. :)

**Comment by potter420** [comment]
Oh, I see, thanks, closing this now as it is duplicate. Sorry.
