### ISSUE TITLE
Can Polars read HDF5 files

### ISSUE THREAD

**Issue by derek-zl** [pola-rs/polars#1705]
Can Polaris read HDF5 files？if yes ，how to read。。。 thanks。

**Comment by ritchie46** [comment]
Its "Polars". :)

Not directly, but if you are using python its very easy to create a DataFrame from the read HDF5 numpy arrays. Are you using python?

**Comment by derek-zl** [comment]
> Its "Polars". :)
> 
> Not directly, but if you are using python its very easy to create a DataFrame from the read HDF5 numpy arrays. Are you using python?

sorry， wrong spelling。ok，i ‘will try。thank you！I now use Python for web development and big data processing

**Comment by ritchie46** [comment]
Did you succeed?

**Comment by derek-zl** [comment]
> Did you succeed?

yes, I use other tool to read hdf5 file ,and then use python to process ！I'm not good at English，so ,thank you very much

**Comment by ashsharma96** [comment]
@derek-zl  How did you call the Hdf5 file using polar or what is the trick?
