### ISSUE TITLE
`quantile` fails on various numeric edge cases

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#17069]
### Issue description

Found these via hypothesis testing, will add more as I find them. Some can be fixed with slightly more stable indexing calcs on the rust side. Some may not be worth fixing (i.e. if `quantile` has higher precision than Series, do we ignore quantile resolution?). Found by comparison to numpy, which seems return correct result in these edge cases.

```python
import polars as pl

# Should return 1.0
# Returns 0.0 for any dtype. Succeeds if None values are removed.
pl.Series([None, 0, 1]).quantile(1e-16, interpolation="higher")  # midpoint/linear/higher

# Should return 0.9999999999999999. Succeeds if None values are removed.
# Returns 1.0.
pl.Series([0, 1]).quantile(0.9999999999999999, interpolation="linear")

# Should return 0.5.
# Returns 0.0.
pl.Series([0, 1]).quantile(1e-324, interpolation="midpoint")  # midpoint/linear/higher
```

### Installed versions

main

**Comment by ritchie46** [comment]
This feels a bit arbitrary. We are working with flaots and at one small point it will of course get unstable. Why would you want to 1-324th quantile?!?

Cannot reproduce the middle one btw.
```python
>>> pl.Series([0, 1]).quantile(0.9999999999999999, interpolation="linear")
0.9999999999999999
```

**Comment by mcrumiller** [comment]
It is a bit arbitrary, although I think the first example should work. Let me clean up the issue a bit.
