### ISSUE TITLE
Bug in merge asof

### ISSUE THREAD

**Issue by havakv** [pola-rs/polars#1707]
https://github.com/pola-rs/polars/blob/8b9c556d8a6cc3a2242de39ca01e8027a3c40730/py-polars/polars/lazy/frame.py#L538

should be 
```python
 elif isinstance(asof_by, list): 
```
Currently, the merge asof with `asof_by=['not_a_col']` will just ignore the asof_by argument and merge asof only using the 'on'. Could benefit from adding a test to make sure the asof merge works as expected

**Comment by ritchie46** [comment]
fixed in #1720 still need to add tests
