### ISSUE TITLE
Performance scaling not working (at least as expected)

### ISSUE THREAD

**Issue by HCelion** [pola-rs/polars#17096]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Don't have shareable code I am afraid

### Issue description

I am putting the question on here rather than StackExchange, as I run on version '1.0.0-beta.1' and I had to use it as the public latest version breaks the code.

For context, I am rewriting a workflow from pandas to polars.
I have a large bunch of parquet files in a folder. In the past I would use a ProcessPool to iterate over each files, load them, and then do some aggregation on the data internal to the file. The workload per file is roughly constant.
So far it is running in the cloud, if I increase the number of cores available to the machine it generally runs faster, as one would expect.
To move it to polars I had to change the direction a bit here (and please correct me if I do it wrong btw).
Since polars doesn't seem to partition the data, as dask seems to be doing it for example, I can't just pass all the filenames to `scan_parquet` to do the work. Instead I found a decent speed up on my local machine (M1 MacOs) compared to the default implementation by doing something like
```
for file_names in chunker(all_files, chunk_size):
    aggregate_data = (pl.scan_parquet(file_names)
                   [...]
                   .with_columns(
                       new_row_value = col('old_value').mean().over('group')
                    )
                   [...]
                   .group_by('other_group')
                   .aggregate(stuff)
                   [...]
                   .collect().to_pandas()
             )
```
 Some of the internal queries are slightly more complicated such as
 
 ```
agg_1 = (pl.scan_parquet(file_names). [...])
agg_2 = (pl.scan_parquet(file_names). [...])
final_agg = (agg_1.join(agg_2, on=['common_key']).groupby('group').agg(...) ).collect().to_pandas()
```

I generally find that there is a goldilocks value for my chunk size where this runs better. I do get an ok speedup on my machine, say 50% compared to the original solution, with which I am fairly happy with.

When I move now to linux with similar settings, I still see a speedup, but overall things move slower and the relative improvement is quite bit worse, say 25%.

What baffles me a bit is that the Linux machine has a much higher number of cores than my local machine (its an aws c6a.8xlarge for example).

I figured that higher number of cores could change the optimal number of chunk size, but it doesn't seem to affect it at all.
In fact, when I run the setup with different values for `POLARS_MAX_THREADS` and double check with `pl.thread_pool_size()` I can see that the number of available cores changes.  Yet, varying the `chunk_size` parameter has relatively little effect and the overall time taken is constant.  At constant chunk_size and varying number of threads, the performance also is flat.

So yeah, I am trying to find out why that is.  Is that perhaps a bug?
Is my approach of chunking not correct and there is another way to keep the calculation localised to the file (similar of how it can be set in Dask). I admit I don't have a very good intuition of what works how.

### Expected behavior

I expect that the overall runtime speeds up as I increase the number of cores, or at least that there is a strong dependence on the best chunk_size.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-beta.1
Index type:           UInt32
Platform:             Linux-4.14.322-246.539.amzn2.x86_64-x86_64-with-glibc2.36
Python:               3.12.2 (main, Mar 12 2024, 11:02:14) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.1
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              15.0.0
pydantic:             2.7.4
pyiceberg:            <not installed>
sqlalchemy:           1.4.49
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by s-banach** [comment]
Multiprocessing is most useful for single-threaded python code. (I.e. GIL-restricted python code).
Polars is natively multithreaded, so a single process could (in theory) use all your compute.

Suppose you can structure your code in the form `def f(df: LazyFrame) -> LazyFrame: ...`
where a single function `f` acting on LazyFrames does all the compute.
Then you could create the list of lazy queries `[f(df) for df in input_frames]`
and run `pl.collect_all` on the list of queries to run them all in parallel without needing multiprocessing.

**Comment by HCelion** [comment]
Interesting, so you would suggest something like
```
pl.collect_all([f(df) for df in pl.scan_parquet(file_names)])
```
?

**Comment by HCelion** [comment]
Thanks, I think I got it to work. Outstanding!

**Comment by HCelion** [comment]
So I ran some more tests, something like
```
 POLARS_MAX_THREADS=20 python
Python 3.12.2 (main, Mar 12 2024, 11:02:14) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> from lib.aggregation.aggregator import AggregatorTransformer
>>> from lib.common import paths
>>> from datetime import datetime
>>> record = pickle.load(open(paths.full_record_path, 'rb'))
>>> aggregator = AggregatorTransformer(events_path=paths.events_path, chunk_size=10000, use_chunking=False)
>>> start_time = datetime.now()
>>> record = aggregator.transform(record)

>>> end_time =  datetime.now()
>>> print(end_time-start_time)
0:17:14.741605

[...]
root@1715047166c4:/usr/src/app/pipeline/v0# POLARS_MAX_THREADS=30 python
Python 3.12.2 (main, Mar 12 2024, 11:02:14) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> from lib.aggregation.aggregator import AggregatorTransformer
>>> from lib.common import paths
>>> from datetime import datetime
>>> record = pickle.load(open(paths.full_record_path, 'rb'))
>>> start_time = datetime.now()
>>> record = aggregator.transform(record)

>>> end_time =  datetime.now()
>>> print(end_time-start_time)
0:20:07.030533
[...]
root@1715047166c4:/usr/src/app/pipeline/v0# POLARS_MAX_THREADS=10 python
Python 3.12.2 (main, Mar 12 2024, 11:02:14) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> from lib.aggregation.aggregator import AggregatorTransformer
>>> from lib.common import paths
>>> from datetime import datetime
>>> record = pickle.load(open(paths.full_record_path, 'rb'))
>>> aggregator = AggregatorTransformer(events_path=paths.events_path, chunk_size=10000, use_chunking=False)
>>> start_time = datetime.now()
>>> record = aggregator.transform(record)

	>>> end_time =  datetime.now()
>>> print(end_time-start_time)
0:22:10.055686
```
The aggregator does under the hood iterate over several of these afore mentioned workloads
```
aggregated= self.eval_aggregate(agg_functionl, files=file_names)
```
with 
```
    @staticmethod
    def eval_aggregate(func, files, **kwargs):
        results_lazy = [func([file], **kwargs) for file in files]
        results = [res for res in pl.collect_all(results_lazy)]
        full_res = pl.concat(results).to_pandas()
        return full_res
```
The functions which we apply this to are all of the form 

```
def func(file_names):
   intermediate_step = (pl.scan_parquet(file_names))
  [...]
  return complicated_result
```
What matters is that the compute is distributed. The majority of the time is spent on the 
```
results = [res for res in pl.collect_all(results_lazy)]
```
step, so it is not the to_pandas and any later index setting on the pandas frame, which might scale differently.

You can see from the outputs, the time to run seems to be fairly independent of the number of threads assigned to the session. It also seems to wobble a bit, where I got at 20 Threads trial with a  time of 17.14 minutes, which seems is lower than the speed at 30 threads 20.03 minutes, but a second try "only" got 20.12 seconds. 
Even if we take the 17.14 minute as outlier, shouldn't such an embarassingly parallel problem scale stronger with the number of threads assigned?

**Comment by s-banach** [comment]
It's very hard to know what the bottleneck is with your specific case.
It may or may not be something in your code.
You could be reading parquet files from a slow source, for example.
(I'm assuming you don't have anything really slow like `map_elements` in your code.)

If amazon says you have 32 vCPUs, it probably means you have 16 hyperthreaded cores.
So comparing 20 to 30 threads, I don't know if I would even expect a strong difference in the best case.

If you really want to optimize the number of threads for a particular AWS instance, you could probably make a "trivial" parallel query that doesn't involve `scan_parquet`. For example, make 1000 random float columns and compute the median of them all, or something.

**Comment by HCelion** [comment]
I see. Strangely enough, when I change the underlying machine type to a smaller machine, I do get a change in speed. Could there be something with the way with which the threadpol_size actually gets updated that is shows a change but maybe nothing different under the hood?
Either way I'll close the ticket, it was quite helpful to change to the collect_all()
