### ISSUE TITLE
Add formatting option to `write_excel` for dataframe values

### ISSUE THREAD

**Issue by aleewen** [pola-rs/polars#17094]
### Description

Could we potentially add `value_format` or `cell_format` argument to `write_excel` that would allow cell formatting to the values of the dataframe? For example, I can have a header_format to have bold headers, center alignment, etc. but then also have my dataframe values have a certain cell background color and border color.

It could work very similar to how cell formats are written in xlsxwriter:
```python

df.write_excel(
    ...,
    cell_format={'bg_color': '#FFCC99', 'border': 1}
)
```

**Comment by deanm0000** [comment]
If you want to format your header then use `header_format` if you want to format everything else then use `column_formats` but just assign the same format to all of your columns. It accepts a selector so you don't have to verbosely list all your columns. For example...

```
import polars as pl
import polars.selectors as cs

df.write_excel('file.xlsx', header_format={'bg_color': '#FFCC99', 'border': 2}, column_formats={cs.all():{'border':1})
```


https://docs.pola.rs/api/python/stable/reference/api/polars.DataFrame.write_excel.html#polars.DataFrame.write_excel

@alexander-beedie what do you think?

**Comment by alexander-beedie** [comment]
Took me a while to get back to this as I've been on vacation...

So, @deanm0000 is quite right, this facility _already_ exists; just use the "header_format" and "column_formats" parameters as indicated, making use of the `cs.all()` selector to apply a given cell format to all columns. There is no need for another parameter here 😉
