### ISSUE TITLE
Exclude directories from expanded glob result

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#17105]
### Description

ref https://github.com/pola-rs/polars/issues/14342#issuecomment-2100136742

> BTW `/**/*.parquet` would not work is parquet files have no extensions. Such files could be generated by AWS Athena for > > example. 
> 
> For files with no extension `/**/*` would not work either,  because it seams it is taking 0 byes folder objet into consideration > and complaining that there is `No Body`

Currently attempting to scan using the `**/*` glob pattern will generally fail:

```python
>>> pl.scan_parquet('.env/dataset/**/*').collect()
polars.exceptions.ComputeError: parquet: File out of specification: underlying IO error: Is a directory (os error 21)
```

**Comment by deanm0000** [comment]
For backward compatibility I don't think changing it outright should be on the table but, at least off the top of my head, I don't see why it couldn't detect that the input isn't using globbing and then that it is a directory (not a file) and then take up the pyarrow like behavior from there.
