### ISSUE TITLE
Change default serialization format for `serialize`/`deserialize` methods to binary

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17108]
Our serialization methods currently all work with JSON strings. This is useful as it's human readable and certain protocols will require JSON structures, but we should also have a more optimized binary serialization format.

[bincode](https://crates.io/crates/bincode) seems like a good candidate, since it's already in our dependencies.

The intended API would be to add a `format` parameter to (de)serialization methods with the options `"json"` and `"bincode"`. Other useful formats could potentially be added in the future.

**Comment by ritchie46** [comment]
All for this. Though I do think we should mark the other formats as unstable.

**Comment by stinodego** [comment]
Update: we will use the ciborium crate for binary serialization:
https://crates.io/crates/ciborium

The associated format will be named `"binary"`. And this will become the default format.
