### ISSUE TITLE
to_numpy() converts None to nan 

### ISSUE THREAD

**Issue by dpinol** [pola-rs/polars#17113]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df=pl.DataFrame({"A":["3"], "B":None})
df.to_numpy()
```

### Log output

```shell
Out[30]: array([['3', nan]], dtype=object)
```

### Issue description

In polars 0.20.27, `to_numpy` returned `None` column as `None`.
In polars 0.20.31, it returns `nan` even when the dtype is `object`.
In polars 0.20.31, with to_pandas() the return contains `None`s

```
In [31]: df.to_pandas().to_numpy()
Out[31]: array([['3', None]], dtype=object)

```

### Expected behavior

imho, `None` should not be converted into `nan`

### Installed versions
```
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-6.8.0-31-generic-x86_64-with-glibc2.39
Python:               3.12.3 (main, Apr 11 2024, 10:16:04) [GCC 13.2.0]
```

**Comment by stinodego** [comment]
Thanks for the explanation @mcrumiller . Indeed there is no bug here, this is intended behavior.

With https://github.com/pola-rs/polars/issues/16398 we can hopefully better support expectations with regards to null values.

**Comment by dpinol** [comment]
Thank you for you quick reply!

> 1. Your title is reversed, it should be "`to_numpy()` converts None to nans".

Fixed, sorry

> 2. Numpy does not support missing data in numeric arrays, and I don't think it should be expected behavior that the presence of nulls in a polars Series converts the result into a numpy array with `object` dtype. `object` performance is incredibly slow and nobody expects their `Int32` series to be converted to an object array when `to_numpy` is called. Also, note that [the documentation](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.to_numpy.html) already states what happens to null values when `to_numpy` is called (at least, for integer types):
>    > Integer Series containing nulls will be cast to a float type with nan representing a null value. This requires data to be copied.

I completely understand this behaviour for both Int and Float series, but not so much for object series.

I think many users will find confusing that the following 2 examples (with polars 0.20.31) use a different value for converting None to numpy, specially taking into account that pandas chooses to return None in both cases.
In any case, if it decided that this the best way to manage it, I'd appreciate if the documentation could be very explicit about these cases.

```python
In [8]: pl.Series(["A", None], dtype=pl.String).to_numpy()
Out[8]: array(['A', None], dtype=object)

In [11]: pl.DataFrame({"A":["3"], "B":None}).to_numpy()
Out[11]: array([['3', nan]], dtype=object)
```

thanks

**Comment by mcrumiller** [comment]
It's using a different value because you are coming from different data types.

* In your first example you are calling `Series[string].to_numpy()`. This creates an array of dtype object.
* In your second example, you are essentially calling `Series[null].to_numpy()` for column B. This creates an array of dtype float.

Dataframes are collections of columns--note that in your second example, the output is a 2D ndarray with `[['3', nan]]` (note the double brackets), indicating two columns. Your `df` contains a String column and a Null column. The String column gets converted to an object dtype, and the Null column gets converted to float dtype. Pandas has no `Null` datatype, so there isn't really a one to one correspondence here with pandas dataframes.

Polars does differ from pandas in how it treats integer series with null data. If you use a pandas nullable integer dtype, the result is cast to object in numpy:

```python
import pandas as pd
pd.Series([1, 2, None], dtype="Int32").to_numpy()  # nullable integer type
# array([1, 2, <NA>], dtype=object)

pl.Series([1, 2, None], dtype=pl.Int32).to_numpy()
array([ 1.,  2., nan])
```

Both behaviors are perfectly acceptable in my opinion, and do not need to match. I think the documentation is pretty clear in what happens here. I think your example would be better suited if you had multiple rows in your dataframe, as a one-row dataframe can easily be confused with a single Series, when they are in fact completely different objects altogether.

**Comment by dpinol** [comment]
@mcrumiller thank you again.
I'm not sure though why you mention again integer series, since my example does not include any integer.
I understand the new polars behaviour for integer and float series. My request is just to make explicit in the documentation that `to_numpy()` never returns None, but will convert it to the "empty value" of the corresponding dtype, or `nan` when the column has Null dtype. 

```
In [5]: pl.DataFrame({"A":["A","B"], "B":[None, 4.5]}).to_numpy()
Out[5]: 
array([['A', nan],
       ['B', 4.5]], dtype=object)


In [7]: pl.DataFrame({"A":["A","B"], "B":[None, ["C"]]}).to_numpy()
Out[7]: 
array([['A', array([], dtype=object)],
       ['B', array(['C'], dtype=object)]], dtype=object)

```

**Comment by mcrumiller** [comment]
>  `to_numpy()` never returns None

But it does:

```python
>>> pl.Series(["a", "b", None]).to_numpy()
array(['a', 'b', None], dtype=object)
```
In your new example, your column `B` now has dtype`List[str]` which again doesn't exist in pandas. For all dtypes that have a similar pandas dtype, everything works the same, except pandas' special nullable integer dtypes:

```python
from datetime import datetime
import polars as pl
import pandas as pd

pl.Series(["a", "b", None]).to_numpy()
# array(['a', 'b', None], dtype=object)
pd.Series(["a", "b", None]).to_numpy()
# array(['a', 'b', None], dtype=object)

pl.Series([1, 2, None]).to_numpy()
# array([ 1.,  2., nan])
pd.Series([1, 2, None], dtype="Int32").to_numpy()
# array([1, 2, <NA>], dtype=object)

pl.Series([datetime(2024, 1, 1), None]).to_numpy()
# array(['2024-01-01T00:00:00.000000', 'NaT'], dtype='datetime64[us]')
pd.Series([datetime(2024, 1, 1), None]).to_numpy()
array(['2024-01-01T00:00:00.000000000', 'NaT'], dtype='datetime64[ns]')
```
Your examples all use polars-specific dtypes that have don't have corresponding data types in Pandas, including `Null` and `List[x]` dtypes:

```python
pl.Series([None, None]).to_numpy()  # this is a pl.Null dtype
# array([nan], dtype=float32)
pd.Series([None, None]).to_numpy()  # this is pandas object dtype
# array([None, None], dtype=object)

pl.Series([None, "B"]).to_numpy()   # this is pl.List[pl.String] dtype
# array([None, 'B'], dtype=object)
pd.Series([None, "B"]).to_numpy()   # this is pandas object dtype
array([None, 'B'], dtype=object)
```

I think you may be using polars dtypes that you're not realizing in some cases, as in when you use `"B":[None, ["C"]]`, you're creating a list of lists, with the first value as null.

**Comment by dpinol** [comment]
Thanks, I do agree the `Series.to_numpy` behaviour.
My confusion is with `DataFrame.to_numpy`. My request is to update the [documentation](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.to_numpy.html) to make explicit that not only `Null` in `pl.Integer` columns are converted to `nan`, but also in `Null` columns. Should I create a new issue?

**Comment by mcrumiller** [comment]
Sure (I can't guarantee it will be accepted), although I think what you propose better belongs in the `Series.to_numpy` documentation.

However the `DataFrame.to_numpy` documentation says:

> DataFrames with mixed types will result in an array with an object dtype.

Which is not true, it looks like a common supertype is attempted, as in:

```python
pl.DataFrame({
    "u8": pl.Series([1, 2, 3], dtype=pl.UInt8),
    "f32": pl.Series([1, 2, 3], dtype=pl.Float32),
}).to_numpy()
# array([[1., 1.],
#        [2., 2.],
#        [3., 3.]], dtype=float32)
```

I'd infer from your example above that first the Series are converted to numpy, and then they are merged into a single array, at which point the supertype casting or object casting occurs:

```python
pl.DataFrame({"A":["A","B"], "B":[None, 4.5]}).to_numpy()
# array([['A', nan],
#        ['B', 4.5]], dtype=object)
```
In the above case, column A is cast to object, and column B is cast to float (hence the nan), and then upon merging the two, column B is then cast to object, which preserves the float. So perhaps a PR that clears up what's going on is warranted. @stinodego is much more familiar with the numpy conversion logic than I am and can validate or clarify what's actually happening.
