### ISSUE TITLE
calculating rowwise minimum of two series

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1711]
Hi;

Is there any function that can generate a serie by calculating rowwise minimum of two series.?

a = [1,4,2,5,2]
b= [5,1,4,2,5]

np.minimum(a,b) -> [1,1,2,2,2]

Thanks.

**Comment by ritchie46** [comment]
Can you create a stackoverflow question? Then I'll answer there. See the question issue template for more info.

**Comment by hakantekbas** [comment]
Hi @ritchie46 

https://stackoverflow.com/questions/69888178/calculating-rowwise-minimum-of-two-series

Thanks.

**Comment by ritchie46** [comment]
> Hi @ritchie46
> 
> https://stackoverflow.com/questions/69888178/calculating-rowwise-minimum-of-two-series
> 
> Thanks.

Thanks! I had surgery today and I still can't type on a keyboard. I hope I can answer tomorrow.

**Comment by hakantekbas** [comment]
@ritchie46   

No worries. Get well soon. Wishing you a speedy recovery.
