### ISSUE TITLE
polars-lazy fails to compile with `super::get_glob_start_idx` error

### ISSUE THREAD

**Issue by nk9** [pola-rs/polars#17133]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

This isn't failing in my code, the compiler is failing in `polars-lazy-0.41.0/src/scan/parquet.rs:8:5`

### Log output

```shell
🕙 03:03:22 ❯ cargo build
   Compiling polars-lazy v0.41.0
error[E0432]: unresolved import `super::get_glob_start_idx`
 --> /Users/nick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.41.0/src/scan/parquet.rs:8:5
  |
8 | use super::get_glob_start_idx;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `get_glob_start_idx` in `scan`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `polars-lazy` (lib) due to 1 previous error
```

### Issue description

polars-lazy is failing to compile. It looks like this code was just added:

https://github.com/pola-rs/polars/commit/7f5412a1f01e7ae95b98fb0a5412779ecea47c22

I've tried `cargo clean && cargo build` as well as removing `Cargo.lock`, but the error persists.

### Expected behavior

Successful compile.

### Installed versions

<details>

polars = { version = "0.*", features = ["parquet", "lazy", "dtype-categorical", "dtype-i16"] }
polars 0.41.0
rustc 1.78.0 (9b00956e5 2024-04-29)
</details>

**Comment by a-agmon** [comment]
Also have the same issue
```
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.79.0 (129f3b996 2024-06-10)`
---
cargo 1.79.0 (ffa9cf99a 2024-06-03)
```

**Comment by ritchie46** [comment]
@nameexhaustion I think there is a feature gate issue.

**Comment by ritchie46** [comment]
Fix coming up. Will release a patch.

**Comment by a-agmon** [comment]
> Fix coming up. Will release a patch.

Amazing. Thanks!
