### ISSUE TITLE
bug when trying to install polars:Is polars suitable for ubuntu18.04?

### ISSUE THREAD

**Issue by coco-99-coco** [pola-rs/polars#1714]
#### Are you using Python or Rust?

 **Python**.

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

I 'm trying to install polars

#### What operating system are you using polars on?

ubuntu 18.04

#### Describe your bug.

I entered the terminal window and tryed to install polars by using "pip3 install polars",but then I was told that the "setup.py"couldn't be found.

#### What are the steps to reproduce the behavior?

```
‘’ctrl+alt+T''
pip3 install polars

```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?

File "/usr/lib/python3.7/tokenize.py",line 447,in open 
  buffer = _builtin_open(filename,'rb')
FileNotFoundError:[Errno 2]No such file or directory:'/tmp/pip-build-oov1efy1/polars/setup/py'

#### What is the expected behavior?

Tell me how to install polars correctly

**Comment by ritchie46** [comment]
which python version?

**Comment by coco-99-coco** [comment]
> Could you run `which pip3`?

yes

**Comment by coco-99-coco** [comment]
python3.7.12




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ritchie ***@***.***&gt;; 
发送时间: 2021年11月9日(星期二) 下午3:01
收件人: ***@***.***&gt;; 
抄送: "小荷包@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pola-rs/polars] bug when trying to install polars:Is polars suitable for ubuntu18.04? (Issue #1714)





 
which python version?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghuls** [comment]
@coco-99-coco Your pip version is too old. Updating pip3 allows to install it. But probably it is better to install a recent python3 and pip in a conda environment instead of modifying the Ubuntu install.

```
root@4cfc34cc6385:/# pip3 install polars
Collecting polars
  Downloading https://files.pythonhosted.org/packages/7c/fa/5bbe5e6ee5fad2541435ac665bc120eb55c200d714aa88b1136437e7a7ae/polars-0.10.17.tar.gz (553kB)
    100% |################################| 563kB 2.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-8kzl6m24/polars/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8kzl6m24/polars/
root@4cfc34cc6385:/# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
root@4cfc34cc6385:/# python3 --version
Python 3.6.9

root@4cfc34cc6385:/# pip3 install -U pip 
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
    100% |################################| 1.7MB 787kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-21.3.1

root@4cfc34cc6385:/# pip3 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@4cfc34cc6385:/# pip3 install polars
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting polars
  Downloading polars-0.10.17-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.9 MB)
     |################################| 9.9 MB 11.9 MB/s            
Collecting numpy
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |################################| 14.8 MB 87.0 MB/s            
Installing collected packages: numpy, polars
Successfully installed numpy-1.19.5 polars-0.10.17
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

**Comment by ritchie46** [comment]
I will clise this with @ghuls answer as solution.
