### ISSUE TITLE
Mention required feature flags for plotting / convert to pandas without PyArrow if possible

### ISSUE THREAD

**Issue by eegli** [pola-rs/polars#17143]
## Current State
Currently, the [docs for plotting](https://docs.pola.rs/user-guide/misc/visualization/) do not mention that some of the [optional dependencies](https://docs.pola.rs/user-guide/installation/#feature-flags) must be installed. Even if polars is installed with the `plot` dependency that integrates hvplot, newcomers may only figure out through an error message that plotting also requires the `pyarrow` dependency.

I.e., with `pip install "polars[plot]"`:

```py
pl.DataFrame(
    {
        "x": [1, 2, 3],
        "y": [4, 5, 6],
    }
).plot.scatter("x", "y")
```
Results in `ModuleNotFoundError: No module named 'pyarrow'`.

With `pip install "polars[plot,pyarrow]"`, everything works as expected.

## Suggested Improvements
- In the docs about visualizations, mention that polars needs to be installed with the `plot` and `pyarrow` feature flags to enable plotting out of the box
- Optionally, automatically install `pyarrow` if a user installs the `plot` dependency since the former is obviously required in combination with the latter

I believe this would enable a more seamless experience for newcomers. If you agree with the change, I can draft a PR with the doc improvements.

### Link

https://docs.pola.rs/user-guide/misc/visualization/

**Comment by MarcoGorelli** [comment]
thanks for the report - to be honest I think there should probably be a separate path which allows for conversion to pandas to happen directly without going through pyarrow, just as it already happens in `from_pandas`:
```
In [6]: import pandas as pd

In [7]: pl.from_pandas(pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]}))
Out[7]:
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

In [8]: import pyarrow
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 import pyarrow

ModuleNotFoundError: No module named 'pyarrow'
```

**Comment by stinodego** [comment]
> there should probably be a separate path which allows for conversion to pandas to happen directly without going through pyarrow

Even so, there will be dataframes that require pyarrow for conversion to pandas. So it should be part of the extras. I will pick it this up as part of https://github.com/pola-rs/polars/pull/17064
