### ISSUE TITLE
Add `get()` Method for Safe Column Access in DataFrame

### ISSUE THREAD

**Issue by stanwsh** [pola-rs/polars#17170]
#### Feature Request
I propose the addition of a `get()` method to the DataFrame class in Polars, which would allow users to safely access columns by providing a default value if the specified column does not exist. This method would enhance the library's usability by providing a more forgiving way of handling missing data columns, similar to the `get()` method used in Python dictionaries and the pandas library.

#### Current Behavior
Currently, attempting to access a non-existent column in a DataFrame results in a `pl.exceptions.NotFoundError`. Users need to either handle this exception or check for the existence of the column manually before accessing it, which can lead to more verbose and less readable code.

#### Proposed Behavior
The `get()` method would allow users to specify the column they wish to access and optionally provide a default value that should be returned if the column is not present. Here is a proposed syntax and behavior:

```python
import polars as pl

# Example DataFrame
df = pl.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})

# Proposed usage of the get() method
result = df.get("C", default=pl.Series([]))  # Returns an empty Series because "C" is not a column in df
```

#### Benefits
- **Reduced Code Complexity**: Users will not have to write try-except blocks or pre-check for columns, leading to cleaner and more maintainable code.
- **Enhanced Safety and Readability**: This feature aligns with Pythonic practices of safe dictionary access, making the DataFrame type more intuitive for new users, especially those familiar with Python's dictionaries or pandas.
- **Flexible Default Handling**: Provides flexibility in specifying what should be considered as a 'missing' or 'default' value, whether it's `None`, an empty Series, or any other user-defined default.

#### Possible Challenges
- **Performance Considerations**: Implementing this feature should not impact the performance for existing functionalities but will need careful integration to maintain overall efficiency.
- **API Consistency**: Care must be taken to ensure that this addition is consistent with other similar methods and the overall design philosophy of Polars.

I believe this feature would be a valuable addition to Polars and look forward to feedback from the community and maintainers.

**Comment by s-banach** [comment]
Thank you, chatgpt.

**Comment by alexander-beedie** [comment]
Actually... we already have a `get_column()` method that could trivially be enhanced to work with an optional "default" param 🤔
