### ISSUE TITLE
Maintain support for parsing hive partitions from user provided directory paths

### ISSUE THREAD

**Issue by baycoder0** [pola-rs/polars#17183]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Before:
```
scan_parquet("data/a=1/")
shape: (5, 3)
┌─────┬───┬─────┐
│ a   ┆ … ┆ x   │
│ --- ┆   ┆ --- │
│ i64 ┆   ┆ i32 │
╞═════╪═══╪═════╡
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
└─────┴───┴─────┘
```
After:
```
scan_parquet("data/a=1/")
┌───┬─────┐
│ … ┆ x   │
│   ┆ --- │
│   ┆ i32 │
╞═══╪═════╡
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
└───┴─────
```

### Issue description

This PR (https://github.com/pola-rs/polars/pull/17055) recently removed an ability to parse hive partitions from user provided directory base paths. This feature is very useful when you have a framework that keeps track of the metadata (list of Parquet files) that you want to scan and load. 

### Expected behavior

Previously, if you had files like this:
```
date=2024-06-20/part-0.parquet
date=2024-06-21/part-1.parquet
date=2024-06-22/part-2.parquet
```

And you wanted to construct LazyFrame on part-0 and part-1, you could run `pl.scan_parquet(["date=2024-06-20/part-0.parquet", "date=2024-06-21/part-1.parquet"])` and that resulting LazyFrame would contain `date` column. However, now that's impossible to do. The only workaround is to scan `pl.scan_parquet("**/*.parquet")` and then filter on `date`, which is slower due to extra directory listing operations on cloud.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by nameexhaustion** [comment]
You can keep the existing behavior by passing `scan_parquet("data/**/*.parquet", hive_partitioning=True)`, this will parse hive partitions from the full path.

The "Before" behavior in that PR doesn't actually exist in any release versions, but rather it was referring to newly introduced behavior (i.e. being able to pass a directory `scan_parquet("data/")`).
