### ISSUE TITLE
number of core limitation

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1718]
Hi;

I did not find how to restrict number of cores. (Esp when I'm running codes in server, restriction will be necessary) I also wonder how number of cores is changing speedup.

Thanks.

**Comment by ghuls** [comment]
```bash
export POLARS_MAX_THREADS=8

python ...
```

**Comment by hakantekbas** [comment]
Is there any document that is showing speed up with respect to thread number.

**Comment by ritchie46** [comment]
> Is there any document that is showing speed up with respect to thread number.

Benchmarks heavily depend on local setup. Run a benchmark and draw your conclusions for your setup. ;)

**Comment by hakantekbas** [comment]
I applied your advice. it seems that one thread is also very fast. Increasing number of thread does not boost performance linearly but it is getting faster.

**Comment by ritchie46** [comment]
> I applied your advice. it seems that one thread is also very fast. Increasing number of thread does not boost performance linearly but it is getting faster.

Yes, it depends on the operations and proper use of expression on the `select` function, minimal use of python bytecode and maybe even `collect_all`.
