### ISSUE TITLE
Group By no longer supported in Rust WASM

### ISSUE THREAD

**Issue by brettsaunders21** [pola-rs/polars#17192]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
df.group_by(&[col("category"), col("type")]).head(1)
```
![image](https://github.com/pola-rs/polars/assets/32368716/9d04ce5a-a05a-4be7-9185-c795f9e8d048)

### Log output

```shell
only supported on 64bit arch
```

### Issue description

With the changes to Polars to make group by use row encoding, it seems that this required 64bit support which Web Assembly doesn't. It seems like it isn't possible to use group_by anymore in WASM

### Expected behavior

Carry out group_by operations when compiling polars (with default feature false, lazy true) for WASM and use it in browser with wasm-bindgen

### Installed versions

0.41.2
<details>
polars = { version = "0.41.2", default-features = false, features = [
  'fmt_no_tty',
  'lazy',
] }
</details>

**Comment by ritchie46** [comment]
Hmm... The `usize` should be changed to `u64`.

**Comment by daBlesr** [comment]
Hi @ritchie46, not sure if I understand, `usize` is architecture agnostic right? Which 'problematic' use of `usize` are you exactly referring to in the code?

**Comment by daBlesr** [comment]
I see that the `offsets` vector in `RowsEncoded` is casted later to `i64` (after checking the types) and this causes the problem. Is your suggestion to change the type of `offsets` to `Vec<u64>`, such that they take the same number of bytes on memory?

**Comment by daBlesr** [comment]
I quickly checked the impact of the above, and the code becomes a bit less appealing using `u64` as it will also require changes on `encode.rs` casting `usize` to `u64`. What do you think of the following, where `offset<usize>` (naturally)  remains as-is:
```rust
let offsets = if std::mem::size_of::<usize>() % std::mem::size_of::<i64>() == 0 {
    // We can safely convert usize to i64
    bytemuck::cast_vec::<usize, i64>(offsets)
} else {
    offsets.iter().map(|&i| i as i64).collect()
};
```
 It checks if it can simply convert, or in worst-case (for wasm) it will have some performance impact because it needs to cast the encoded rows.

**Comment by brettsaunders21** [comment]
Any update on this issue?

**Comment by daBlesr** [comment]
I created a PR which waits for a review

**Comment by daBlesr** [comment]
Hi @ritchie46, please take some time to review the PR. Let me know what you are unhappy with. Without this PR WASM does not work.

**Comment by chtotut** [comment]
Any update on this issue?
@daBlesr do you continue to work for PR or have you lost interest? (just a friendly ping)
