### ISSUE TITLE
Serializing float columns with `format="json"` turns inf/nan values into null

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17211]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import io

import polars as pl

df = pl.DataFrame({"a": [1.0, float("inf"), float("-inf"), float("nan")]})
ser = df.serialize()
print(ser)  # {"columns":[{"name":"a","datatype":"Float64","bit_settings":"","values":[1.0,null,null,null]}]}
result = pl.DataFrame.deserialize(io.StringIO(ser))
print(result)
```

### Log output

```shell
shape: (4, 1)
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ 1.0  │
│ null │
│ null │
│ null │
└──────┘
```

### Issue description

Roundtripping float columns doesn't work for nan/inf values.

### Expected behavior

original values are preserved

### Installed versions

main

**Comment by ritchie46** [comment]
Ah yes. That's because JSON doesn't support those values.
