### ISSUE TITLE
Parallel string operations

### ISSUE THREAD

**Issue by ruihe774** [pola-rs/polars#17235]
### Description

When dealing with large number of strings (e.g. 100K+ rows), current string operations (e.g. `.str.extract_groups`, `.str.strip_prefix`, etc) are somewhat slow. They iterate over the series and process the strings in a single thread. I wonder if it is possible to add the ability of parallel processing to string operations.

**Comment by ritchie46** [comment]
This will resolve itself with the new streaming engine. That will do vertical parallelism.
