### ISSUE TITLE
sort in aggregation

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1723]
Hi;

I'm trying to return one value from sorted series in aggregation. But I'm getting an error. I think I'm making an error in my assumption.

In aggregation I will find the latest data and get the cumPassenger of this date. If arg_sort returns the indices for each group, how can it be out ouf bounds? 

```
pl.from_pandas(summarizedData).groupby(["monthYearTravel", "origcountry", "purchase_date_ym"]) \
                        .agg( [pl.col("purchase_date").max().alias("purchase_date"), 
                               pl.col("monthFark").unique().alias("monthFark"),
                               pl.col("cumPassenger").take(pl.col("purchase_date").arg_sort(reverse=True).take([0])).alias("cumPassenger")
)
```

> RuntimeError: Any(OutOfBounds("take indices are out of bounds"))

**Comment by ritchie46** [comment]
what does this return? `pl.col("cumPassenger").take(pl.col("purchase_date")`

And there is a `first` expression.

**Comment by hakantekbas** [comment]
in each group, I'm finding max purchase_date and return cumPassenger (cummulative passenger) of that date.

To accomplish this, I'm finding index of maximum of purchase_date in each group then I can get the cumPassenger of that date.

**Comment by ritchie46** [comment]
Have you got a minimal example?

**Comment by hakantekbas** [comment]
data = pl.DataFrame(data={"f1":[3,5,2,4,3,2,3],"f2":[2,3,2,5,4,2,4],"f3":[4,5,7,4,5,2,6]})

### this is what I'm trying to get. It is working.
data.sort("f3",reverse=True).groupby("f1").agg([pl.col("f3").take([0]).first()])

### this is not working. 
data.groupby("f1").agg([pl.col("f3").take(pl.col("f3").arg_sort(reverse=True).take([0])).first()])](url)

**Comment by hakantekbas** [comment]
I will divide the parts of expression to explain.

I copied data below.

![image](https://user-images.githubusercontent.com/19631334/141054224-eb471384-940b-4029-9f9f-2d4671f9c2b9.png)

After  I run this code; I will get the indices of max values.
`data.groupby("f1").agg( [ pl.col("f3").arg_sort(reverse=True).take([0]) ] )
`
![image](https://user-images.githubusercontent.com/19631334/141054426-30c5333d-3c8d-4222-b065-fcb042812a74.png)


I can also get the row from grouped data;
`print( data.groupby("f1").agg( [ pl.col("f3").take([0]) ] ) )
`
![image](https://user-images.githubusercontent.com/19631334/141054545-1dda49e1-c4f2-4d9f-818a-7e04963978fa.png)

When I join these two expression it throws error.
![image](https://user-images.githubusercontent.com/19631334/141054683-d4e7c492-767a-4afa-a790-612954fe532c.png)

**Comment by ritchie46** [comment]
> I will divide the parts of expression to explain.
> 
> I copied data below.
> 
> ![image](https://user-images.githubusercontent.com/19631334/141054224-eb471384-940b-4029-9f9f-2d4671f9c2b9.png)
> 
> After I run this code; I will get the indices of max values. `data.groupby("f1").agg( [ pl.col("f3").arg_sort(reverse=True).take([0]) ] ) ` ![image](https://user-images.githubusercontent.com/19631334/141054426-30c5333d-3c8d-4222-b065-fcb042812a74.png)
> 
> I can also get the row from grouped data; `print( data.groupby("f1").agg( [ pl.col("f3").take([0]) ] ) ) ` ![image](https://user-images.githubusercontent.com/19631334/141054545-1dda49e1-c4f2-4d9f-818a-7e04963978fa.png)
> 
> When I join these two expression it throws error. ![image](https://user-images.githubusercontent.com/19631334/141054683-d4e7c492-767a-4afa-a790-612954fe532c.png)

Could you create some code,I can copy? I cannot type very well atm.

**Comment by hakantekbas** [comment]
data : 

> data = pl.DataFrame(data={"f1":[3,5,2,4,3,2,3],"f2":[2,3,2,5,4,2,4],"f3":[4,5,7,4,5,2,6]})

To get indices

> data.groupby("f1").agg( [ pl.col("f3").arg_sort(reverse=True).take([0]) ] )

I tried to get the first row from grouped data. to check take method will work.

> data.groupby("f1").agg( [ pl.col("f3").take([0]) ] ) 

I combined these two expression in agg.

> print( data.groupby("f1").agg( [ pl.col("f3").take( pl.col("f3").arg_sort(reverse=True).take([0]) ) ] ) )

Are these codes meeting your expectation? If not please give more detail.

**Comment by ritchie46** [comment]
This seems to be a bug indeed. However you can achieve what you want by combining the `sort_by` expr with the `first` expr.

**Comment by hakantekbas** [comment]
This type of calculation is very helpfull especially in R data.table. If we can correct this bug, it will ease many complex calculations. Do you have any timeline to fix the bug?  We sometimes need different calculations after applying sorting. It is mostly done in aggregation. As each sorting is applied to different columns, applying sort in advance will not make sense. 

Is it possible to show how I can do this with sort_by.

**Comment by ritchie46** [comment]
> This type of calculation is very helpfull especially in R data.table. If we can correct this bug, it will ease many complex calculations. Do you have any timeline to fix the bug? We sometimes need different calculations after applying sorting. It is mostly done in aggregation. As each sorting is applied to different columns, applying sort in advance will not make sense.
> 
> Is it possible to show how I can do this with sort_by.

sort_by takes the column you want to sort by. Give it a try and let me know how it goes. I cannot type very well atm, had surgery. I will just walk you through it. 😉

**Comment by ghuls** [comment]
@hakantekbas Here are a few ways to do what you want. The last one (with max) should be the fastest.

```python
In [57]: df = pl.DataFrame(data={"f1":[3,5,2,4,3,2,3],"f2":[2,3,2,5,4,2,4],"f3":[4,5,7,4,5,2,6]})

In [68]: df.sort("f3", reverse=True).groupby("f1").agg([pl.col("f3").first()]).sort("f1")
Out[68]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 2   ┆ 7        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5   ┆ 5        │
└─────┴──────────┘

In [69]: df.groupby("f1", maintain_order=True).agg([pl.col("f3").sort(reverse=True).first()]).sort("f1")
Out[69]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 2   ┆ 7        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5   ┆ 5        │
└─────┴──────────┘

In [70]: df.groupby("f1", maintain_order=True).agg([pl.col("f3").max()]).sort("f1")
Out[70]: 
shape: (4, 2)
┌─────┬────────┐
│ f1  ┆ f3_max │
│ --- ┆ ---    │
│ i64 ┆ i64    │
╞═════╪════════╡
│ 2   ┆ 7      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 5   ┆ 5      │
└─────┴────────┘
```

**Comment by hakantekbas** [comment]
> > This type of calculation is very helpfull especially in R data.table. If we can correct this bug, it will ease many complex calculations. Do you have any timeline to fix the bug? We sometimes need different calculations after applying sorting. It is mostly done in aggregation. As each sorting is applied to different columns, applying sort in advance will not make sense.
> > Is it possible to show how I can do this with sort_by.
> 
> sort_by takes the column you want to sort by. Give it a try and let me know how it goes. I cannot type very well atm, had surgery. I will just walk you through it. 😉

yes it works. But if you can fix bug in future releases, it will help me a lot. As I prefer this type of subqueries in R data.table, it will ease my life.

Thanks

**Comment by hakantekbas** [comment]
@ghuls I wonder why maintain_order is used.

Assuming that maintain_order is set to false and  I sort data before group by, will order of sorted field change? Sorted field is not listed in group by clause. It is only used in aggregation part.

Thanks for sharing 3 different approaches to solve my problem.

**Comment by ghuls** [comment]
@hakantekbas it is not needed here, but might be something you want for other queries.

```python
In [90]: df.groupby("f1", maintain_order=True).agg([pl.col("f3").sort(reverse=True).first()])
Out[90]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 3   ┆ 6        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5   ┆ 5        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 7        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4        │
└─────┴──────────┘

In [91]: df.groupby("f1", maintain_order=False).agg([pl.col("f3").sort(reverse=True).first()])
Out[91]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 5   ┆ 5        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 7        │
└─────┴──────────┘

In [92]: df.groupby("f1", maintain_order=False).agg([pl.col("f3").sort(reverse=True).first()])
Out[92]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 4   ┆ 4        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 7        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5   ┆ 5        │
└─────┴──────────┘

In [93]: df.groupby("f1", maintain_order=False).agg([pl.col("f3").sort(reverse=True).first()])
Out[93]: 
shape: (4, 2)
┌─────┬──────────┐
│ f1  ┆ f3_first │
│ --- ┆ ---      │
│ i64 ┆ i64      │
╞═════╪══════════╡
│ 5   ┆ 5        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 4        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 7        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 6        │
└─────┴──────────┘
```

**Comment by ritchie46** [comment]
> @ghuls I wonder why maintain_order is used.
> 
> Assuming that maintain_order is set to false and I sort data before group by, will order of sorted field change? Sorted field is not listed in group by clause. It is only used in aggregation part.
> 
> Thanks for sharing 3 different approaches to solve my problem.

Maintain order doesn't change the order the groups are perceived. It only ensures the output order of the keys is consistent with the dataframe you've started the groupby with.

**Comment by hakantekbas** [comment]
Thanks it clarified. Subject is closed for me. But if you believe that it is a bug, it is better to solve it. Thanks for fast replies.
