### ISSUE TITLE
Support No-op round() on Int columns

### ISSUE THREAD

**Issue by cianoo45** [pola-rs/polars#17240]
### Description

Is there any reason why a no-op round() can't be supported on Integer columns?

The reasoning is if you want to create a list of Expressions where the underlying columns could be float or integer, you have to cast all the columns to float before you can call .round()

```
expressions = [(pl.col(col1) / pl.col(col2)).round(2) for col1, col2 in zip(col1s, col2s)]

polars.exceptions.InvalidOperationError 'round' operation not supported for dtype i64
```

**Comment by orlp** [comment]
I see no problem with allowing this.
