### ISSUE TITLE
`pl.Expr.list.get` raises error on null values.

### ISSUE THREAD

**Issue by dalejung** [pola-rs/polars#17252]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    import polars as pl

    df = pl.DataFrame({
        'name': ['BOB-3', 'BOB', None],
    })

    split = df.with_columns(
        pl.col('name').str.split('-')
    )
    res = split.with_columns(pl.col('name').list.get(0))

```

### Issue description

Previously `pl.Expr.list.get` would propagate `null` values. Now it errors with `ComputeError: get index is out of bounds`. 

### Expected behavior

I would expect `pl.Expr.list.get` to not error on null list values.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-rc.2
Index type:           UInt32
Platform:             Linux-6.9.6-arch1-1-x86_64-with-glibc2.39
Python:               3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.9.2.post8+g4cb29ba
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               3.0.0.dev0+756.ge8e6be071c
pyarrow:              17.0.0.dev225+g72e7e4c6c
pydantic:             2.7.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by lscheilling** [comment]
Wouldn't this error be related to the new `null_on_oob` parameter in `pl.Expr.list.get`?

[Source Code](https://github.com/pola-rs/polars/blob/01a65f0a17892d5c7bc7d124b2c48925c5429c68/py-polars/polars/expr/list.py#L504)

**Comment by cmdlineluser** [comment]
Yeah, it was changed in https://github.com/pola-rs/polars/pull/16841

- https://docs.pola.rs/releases/upgrade/1/#default-to-raising-on-out-of-bounds-indices-in-all-getgather-operations

**Comment by mcrumiller** [comment]
I don't think that `null` bounds should raise on oob even when the parameter is True. If it did, the parameter would only be useful when dealing with series without nulls, otherwise it *must* be set to False. If not, all calls will fail as long as a single null value is present.

**Comment by mcrumiller** [comment]
Also, note that this is not the case for arrays:

```python
s = pl.Series([None, [1]], dtype=pl.Array(pl.Int32, 1))
s.arr.get(0, null_on_oob=False)  # returns [null, 1]
s.arr.get(0, null_on_oob=True)   # returns [null, 1]
```

**Comment by stinodego** [comment]
Thanks for the report. This is most probably a side-effect of https://github.com/pola-rs/polars/pull/16841

**Comment by stinodego** [comment]
Re-opening as this wasn't fixed completely - see https://github.com/pola-rs/polars/pull/17276
