### ISSUE TITLE
Migrate to PyO3 0.22

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#17273]
### Description

This is prerequisite for Python 3.13 support. Happy to do it if you want.

**Comment by stinodego** [comment]
Sure, go ahead!

**Comment by ritchie46** [comment]
It depends on https://github.com/PyO3/rust-numpy/pull/431

**Comment by itamarst** [comment]
rust-numpy got through their PR backlog, so I assume a release will happen real soon now.

**Comment by itamarst** [comment]
OK it's being released as we speak, so I'll take this on.

**Comment by itamarst** [comment]
Oh actually given abi3 this is _not_ a prerequisite for Python 3.13 support. However, it still needs doing just to keep up with the ecosystem.
