### ISSUE TITLE
Allow trailing comma in df! macro

### ISSUE THREAD

**Issue by dbr** [pola-rs/polars#1727]
Trivial little thing, but it would be nice if the `df!` macro allowed trailing commas

Currently the following code:

```rust
polars::df! {
    "a" => &["a one", "a two"],
    "b" => &["b one", "b two"],
    "c" => &[1, 2],
}
```
will error due to the comma after `&[1, 2]`

```rust
 --> src/main.rs:7:24
  |
7 |         "c" => &[1, 2],
  |                        ^ missing tokens in macro arguments
```

**Comment by ritchie46** [comment]
Could you make a PR? :)

**Comment by dbr** [comment]
...nope because @1aguna beat me to it! Thanks both!

**Comment by 1aguna** [comment]
@dbr didnt mean to poach, was just looking for beginner issues to work on. I'll check first next time, sorry :grimacing:

**Comment by dbr** [comment]
No worries at all, no need to apologize!
