### ISSUE TITLE
Add null/NaN placement option to sort functions.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1729]
#### Describe your feature request

Add null/NaN placement option to sort functions (like in pyarrow 6.0.0).

Allow sorting of nulls/Nan at beginning or end:
https://issues.apache.org/jira/browse/ARROW-12063
https://github.com/apache/arrow/pull/11212/commits/d30564aa3b3d1e021bf1a2aa66a161fbdba09107

```c++
enum class NullPlacement {
  /// Place nulls and NaNs before any non-null values.
  /// NaNs will come after nulls.
  AtStart,
  /// Place nulls and NaNs after any non-null values.
  /// NaNs will come before nulls.
  AtEnd,
};
```

Probably better if implemenented in arrow2, directly I guess.

**Comment by 1aguna** [comment]
I think this is already implemented in `arrow2` 
https://github.com/jorgecarleitao/arrow2/blob/9d4107ce84d729818ccef2be6bfd979fffc5630c/src/compute/sort/mod.rs#L295

```rust
pub struct SortOptions {
    /// Whether to sort in descending order
    pub descending: bool,
    /// Whether to sort nulls first
    pub nulls_first: bool,
}
```

**Comment by CloseChoice** [comment]
I guess this is already done by [this PR](https://github.com/pola-rs/polars/commit/e4a25d0c8c2f9f5fa661b35417b877293e394372)

**Comment by ritchie46** [comment]
> I guess this is already done by [this PR](https://github.com/pola-rs/polars/commit/e4a25d0c8c2f9f5fa661b35417b877293e394372)

I did the implementation. Still have to expose the API

**Comment by ritchie46** [comment]
Exposed.
