### ISSUE TITLE
cross-join should not work on any key

### ISSUE THREAD

**Issue by FBruzzesi** [pola-rs/polars#17303]
### Description

This is borderline between a bug, a documentation and a feature request.

Cross join's ignore join keys and whatever can be passed as keys.
This is not documented, and it may seem counterintuitive to a user.

Minimal reproducible example:

```py
import polars as pl

df = pl.DataFrame({
    "a": [0, 1],
    "b": ["x", "y"]
})

df.join(df, how="cross")
df.join(df, how="cross", left_on="a", right_on="b")
df.join(df, how="cross", left_on="a", right_on="c")  # c doesn't even exist
```

All 3 operations above lead to the same result.

I know we should not compare with pandas, but in this occasion, I feel like the fact that an error is raised if keys are passed is more intuitive for a user.

**Comment by ritchie46** [comment]
We should raise an error indeed.
