### ISSUE TITLE
Python releases do not (always) correctly update the user guide

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17329]
The workflow gets triggered and finishes successfully, but the user guide is not updated.

This happened with 1.0.0 release.

A manual trigger of the workflow afterwards _DOES_ update correctly.

Maybe it's an issue with the Python docs workflow trying to update GitHub Pages at the same time? Investigation needed.

**Comment by bertiewooster** [comment]
When I select dev from the version drop-down menu on the Python docs, the URL changes to dev, but the menu changes itself to 1 (stable). Is that a symptom of this issue, or should I open a separate issue?
<img width="1078" alt="Polars docs URL dev but menu 1" src="https://github.com/pola-rs/polars/assets/1335522/2d0fa69d-f553-41a1-a408-03b47c6cc8e3">

**Comment by stinodego** [comment]
> When I select dev from the version drop-down menu on the Python docs, the URL changes to dev, but the menu changes itself to 1 (stable).

Thanks for reporting this. It's unrelated but we should fix it. No need to open a separate issue.
