### ISSUE TITLE
Add `union` to lazy DF

### ISSUE THREAD

**Issue by jorgecarleitao** [pola-rs/polars#1735]
When reading multiple files, e.g. partitioned, it is useful to be able to union the dataframes so that we can operate them as a single entity. Was unable to find such operation (eager has vstack, but that disables filter pushdown optimizations).

**Comment by ritchie46** [comment]
This is under the assumption that the schema of all files is equal right?

**Comment by jorgecarleitao** [comment]
right, crash and burn if not. If column order does not align we may also crash (or keep first dfs' order).

I would prefer to not behave like spark that happily merges columns based on the column positions 🙈

**Comment by ghuls** [comment]
pyarrow has `pyarrow.dataset` for this (if you need inspiration):
```python
pyarrow.dataset.dataset(source, schema=None, format=None, filesystem=None, partitioning=None, partition_base_dir=None, exclude_invalid_files=None, ignore_prefixes=None)


source (path, list of paths, dataset, list of datasets, (list of) batchesor tables, iterable of batches, RecordBatchReader, or URI) –

Path pointing to a single file:

    Open a FileSystemDataset from a single file.
Path pointing to a directory:

    The directory gets discovered recursively according to a partitioning scheme if given.
List of file paths:

    Create a FileSystemDataset from explicitly given files. The files must be located on the same filesystem given by the filesystem parameter. Note that in contrary of construction from a single file, passing URIs as paths is not allowed.
List of datasets:

    A nested UnionDataset gets constructed, it allows arbitrary composition of other datasets. Note that additional keyword arguments are not allowed.
(List of) batches or tables, iterable of batches, or RecordBatchReader:

    Create an InMemoryDataset. If an iterable or empty list is given, a schema must also be given. If an iterable or RecordBatchReader is given, the resulting dataset can only be scanned once; further attempts will raise an error.
```
https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html#pyarrow.dataset.dataset

**Comment by ritchie46** [comment]
I am thinking of a `pl.concat` with a list of `LazyFrame`s. 

Then we can expand on that with partitioned parquet files etc.
