### ISSUE TITLE
Offer "read_parquet" over the lazy API

### ISSUE THREAD

**Issue by jorgecarleitao** [pola-rs/polars#1737]
When building a complex statement in the lazy API, it is often not clear which columns are required in the initial read (and it usually depends on the statement details). From my understanding of the lazy API, we need to write `pl.read_parquet(..., columns=)` before starting to create the statement.

I think it could be interesting to allow something like `"pl.read_lazy_parquet"` that only reads the parquet's metadata and delays the load of the data to when it is needed. The advantage is that we can apply projection and filter pushdown depending on the statement, thereby not deserializing the whole file.

**Comment by ritchie46** [comment]
I believe we offer exactly that in `pl.scan_parquet`. :)

**Comment by ghuls** [comment]
@ritchie46 A scan `pl.scan_ipc` would be great too.
Related to: https://github.com/pola-rs/polars/issues/1569

**Comment by jorgecarleitao** [comment]
Ahh, awesome!
