### ISSUE TITLE
Fix doc of GroupBy.__iter__

### ISSUE THREAD

**Issue by ruoyu0088** [pola-rs/polars#17376]
### Description

the doc of `GroupBy.__iter__` says:

> Each group is represented by a tuple of (name, data). The group names are tuples of the distinct group values that identify each group. **If a single string was passed to by, the keys are a single value instead of a tuple.**

but it always returns group identifiers as tuples after polars 1.0.0.

### Link

https://github.com/pola-rs/polars/blob/main/py-polars/polars/dataframe/group_by.py#L68

**Comment by stinodego** [comment]
Thanks for the report, will fix!
