### ISSUE TITLE
Aggregate the whole dataframe

### ISSUE THREAD

**Issue by m-legrand** [pola-rs/polars#17388]
### Description

The GroupBy context is great to create complex aggregations by groups using the expression API.
However it is only available if I have groups, but I can't easily run the same aggregations on the whole dataframe.

As a simple example, let's imagine I have a dataframe with two columns, `value (f64)` and `n (u64)`, and that I want to calculate weighted average of values for the whole frame (along with other statistics).
The best I could come up with is something like this:

```python
df = pl.DataFrame(
    {"value": [1.0, 2.0, 3.0], "n": [1, 2, 2]},
    schema={"value": pl.Float64, "n": pl.UInt64},
)

agg_df = (
    df.group_by(pl.lit(0).alias("__dummy__"))
    .agg(
        avg=pl.col("value").mean(),
        wavg=(pl.col("value") * pl.col("n")).sum() / pl.col("n").sum(),
    )
    .drop("__dummy__")
)

[aggs] = agg_df.rows(named=True)

# aggs = {'avg': 2.0, 'wavg': 2.2}
```

This works well but the whole "__dummy__" dance seems a bit flaky and superfluous.
Would it be possible to have `agg` available at the DataFrame level so that the same result could be achieved with the following code?

```python
aggs = df.agg(
    avg=pl.col("value").mean(),
    wavg=(pl.col("value") * pl.col("n")).sum() / pl.col("n").sum(),
)

# aggs = {'avg': 2.0, 'wavg': 2.2}
```

**Comment by MarcoGorelli** [comment]
hey @m-legrand - you can use `select` directly:
```python
In [5]: aggs = df.select(
   ...:     avg=pl.col("value").mean(),
   ...:     wavg=(pl.col("value") * pl.col("n")).sum() / pl.col("n").sum(),
   ...: )

In [6]: aggs
Out[6]:
shape: (1, 2)
┌─────┬──────┐
│ avg ┆ wavg │
│ --- ┆ ---  │
│ f64 ┆ f64  │
╞═════╪══════╡
│ 2.0 ┆ 2.2  │
└─────┴──────┘
```

**Comment by MarcoGorelli** [comment]
closing then, but thanks for the request!
