### ISSUE TITLE
The `pivot` user guide doc and API doc are both outdated

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#17415]
### Description

The following are outdated:
https://docs.pola.rs/user-guide/transformations/pivot/
https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

There is no `on` anymore (now: `columns`).

It looks like Polars API documentation structure doesn't follow the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle? I indeed learned this principle formally for the first time in your [doc](https://docs.pola.rs/user-guide/expressions/column-selections/#expression-expansion) ^_^!

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

**Comment by etiennebacher** [comment]
The `columns` parameter of `pivot` was renamed `on` in #17095, so the user guide and API docs are correct.

**Comment by MarcoGorelli** [comment]
hi @liufeimath - could you clarify which part is outdated please? looks fine to me but I might have missed something

**Comment by stinodego** [comment]
Thanks for the report, but it seems like you were looking at an old (cached?) version of the docs somehow.

I'll close this - can reoopen if you can show us some steps to get to an outdated version of the docs.

**Comment by liufeimath** [comment]
Oh got it. I was using an `0.20.x` version before and didn't realize that `columns` was renamed to `on` in `1.0.0`. All good now. Thanks!
