### ISSUE TITLE
Sometimes .collect().to_pandas()  may quit without error (by OOM ).

### ISSUE THREAD

**Issue by eromoe** [pola-rs/polars#17419]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

nope

### Issue description

Today my pipeline got quit without any error .
After debugging, I find `pl.scan_parquet(x).collect().to_pandas()` may quit without in some case , probably OOM . 

I test it on jupyter too, cause kernal crash( so no error message)
![image](https://github.com/pola-rs/polars/assets/3938751/1f706ea1-0d9b-4578-9539-f5043bcd434d)

Usually polars used to produce error like
```
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 5.38 GiB for an array with shape (142, 10169706) and data type float32
```
After  updating to 1.0.0 , it just quit without error.

### Expected behavior

raise OOM error

### Installed versions

<details>

```
1.0.0
```

</details>

**Comment by ritchie46** [comment]
Going out of memory is not a bug.

**Comment by eromoe** [comment]
Understand.
I wonder if polars have plan to handle this case in future, since quit without error is bad for trouble shotting.

**Comment by ritchie46** [comment]
It is hard to raise guaranteed OOM errors. We can never guarantee that.
