### ISSUE TITLE
Support casting date string in 'yyyymmdd' format to datetime/date

### ISSUE THREAD

**Issue by mingqi830** [pola-rs/polars#17437]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
df = pd.DataFrame({'a': ['Tom', 'Nick', 'Marry', 'Krish', 'Jack', None],
                   'b': ['Jane', 'John', 'Doe', 'Doe', 'Mohan', 'Jane2'],
                   'c': [5, 6, 6, 7, 8, 5],
                   'd': ['20200101', '20200102', '20200103', '20200104', '20200105', None]
                   })
pldf = pl.from_pandas(df)

res1=pldf.cast({'d':pl.Datetime('ns')})
res2=df.astype({'d':'datetime64[ns]'})

### Log output

```shell
polars.exceptions.ComputeError: could not find an appropriate format to parse dates, please define a format
```

### Issue description

I'm building a tool for the translation from pandas to polars, and find out this format is not supported by polars but pandas. 

Is there any chance to support date string in 'yyyymmdd' format? We do have this kind of data a lot, and would like to use polars to do the processing.

### Expected behavior

Can cast 'yyyymmdd' date string to date or datetime type.

### Installed versions

<details>
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Windows-10-10.0.18362-SP0
Python:               3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           0.3.3
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              16.0.0
pydantic:             1.10.2
pyiceberg:            <not installed>
sqlalchemy:           1.4.37
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
pandas dtypes=None
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Windows-10-10.0.18362-SP0
Python:               3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           0.3.3
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              16.0.0
pydantic:             1.10.2
pyiceberg:            <not installed>
sqlalchemy:           1.4.37
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

</details>

**Comment by MarcoGorelli** [comment]
hey @mingqi830 - you can use `.str.to_datetime(format='%Y%m%d')`, `cast(pl.Datetime)` doesn't support custom formats

**Comment by MarcoGorelli** [comment]
closing then, but thanks for the issue!
