### ISSUE TITLE
Allow passing Expressions into `DataFrame.get_column`

### ISSUE THREAD

**Issue by AlexanderNenninger** [pola-rs/polars#17438]
### Description

Currently `get_column` only accepts `str` in the `name` argument. This API could be made more ergonomic by allowing the user to pass an expression. Instead of

```python
if df.select(pl.col("foo").eq(0)).get_column("foo").all():
    pass # do something
```
one could simply use 
```python
if df.get_column(pl.col("foo").eq(0)).all():
    pass  # do something
```
removing one potential repetition, and thus error source. As far as I can tell, the only invariant, that needs to be upheld, is that the expression has exactly one output. But the infrastructure for this is already present with `Expr.meta.has_multiple_outputs`.

**Comment by stinodego** [comment]
We do not plan to support expressions in `get_column`.

You can use `select(...).to_series()` for when you select a single column and need it as a Series.

**Comment by AlexanderNenninger** [comment]
Sorry, I could have researched this better. Thanks for the suggestion.
