### ISSUE TITLE
immutable (aka frozen) and hashable variants of DataFrame and maybe LazyFrame

### ISSUE THREAD

**Issue by ggggggggg** [pola-rs/polars#17447]
### Description

Polars already encourages a "mutation free" style of programming, where operations return new `DataFrame`. Eg 
`df = df.filter(expr)`. It would be nice if we could benefit from that by having `DataFrame` be hashable. One benefit of this would be that functions taking `DataFrame` argument could be used with `functools.cache`. In order to do that safely, it's best if the `DataFrame` errors on any method call that would mutate it.

**Comment by alexander-beedie** [comment]
Hmm... I'm not sure that DataFrame _should_ be natively hashable; it could easily represent 10s of GBs of data (or more, on a really enormous server). To exactly hash such a frame requires hashing all of those values, which is _deeply_ undesirable.

The only reasonably performant way to hash such objects involves creating an _approximate_ hash, using key metadata (such as, for example, the schema and length) along with a standardised sample of the underlying data that ensures "sufficient" uniqueness. However, only the caller will really know what "sufficient" means for them, how to construct a suitably representative sample, and so on...

**Comment by ggggggggg** [comment]
Those are pretty good points I hadn't considered. Especially hashing such a large amount of data. 

Sometimes objects in python are hashed by their object ID. It's easy enough to wrap a dataframe in something that hashes by object ID that maybe it's not worth adding to polars even if it is worthwhile to do sometimes.

**Comment by ggggggggg** [comment]
I'm closing this as it is not a straightforward improvement, and there are workarounds for my use case.
