### ISSUE TITLE
Transaction support for write database functions

### ISSUE THREAD

**Issue by jjmarchewitz** [pola-rs/polars#17457]
### Description

Pretty much the title. As a user, I would like some kind of interface/argument/object that lets me enter a transaction before doing a db write.

**Comment by alexander-beedie** [comment]
You do that by opening the transaction on your side before passing the connection object into `write_database` ;)

**Comment by alexander-beedie** [comment]
Closing, as this can (and should) be done user-side with an existing connection/session object 👌

**Comment by jjmarchewitz** [comment]
Thank you! I didn't know that I could pass in connection objects now. Thanks :D
