### ISSUE TITLE
read_database method cannot fetch data from mariadb database

### ISSUE THREAD

**Issue by ksr-sundar-0723** [pola-rs/polars#17466]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import mariadb
import polars as prs
from collections import OrderedDict

cred = OrderedDict()
cred['host'] = "192.0.2.1"
cred['port'] = 3306
cred['user'] = "db_user"
cred['password'] = "USER_PASSWORD"

conn = mariadb.connect(**cred)
df = prs.read_database(query="SELECT * FROM my_table", connection=conn)
```

### Log output

```shell
File "/projects/dataframe_projects/.venv/lib/python3.12/site-packages/polars/io/database/functions.py", line 256, in read_database
    ).to_polars(
      ^^^^^^^^^^
  File "/projects/dataframe_projects/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 521, in to_polars
    frame = frame_init(
            ^^^^^^^^^^^
  File "/projects/dataframe_projects/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 270, in _from_rows
    schema_overrides = self._inject_type_overrides(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/dataframe_projects/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 312, in _inject_type_overrides
    dtype = _infer_dtype_from_cursor_description(self.cursor, desc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/dataframe_projects/.venv/lib/python3.12/site-packages/polars/io/database/_inference.py", line 206, in _infer_dtype_from_cursor_description
    type_code, _disp_size, internal_size, precision, scale, _null_ok = description
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 6)
```

### Issue description

Polars read_database is trying to get metadata information from cursor.description, the assumptions are that the cursor description returns 6 attributes including name type etc.  But Mariadb Cursor Description returns more than 6 attributes I think 10-11 attributes.  Since polars library is trying to unpack the tuple, it is unable to read the info returned.  

### Expected behavior

Cursor description should be read as a named tuple instead of just  unpacking, only the relevant info needs to be sourced from description. 

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```
polars 1.0.0, tried with earlier versions also..
</details>

**Comment by alexander-beedie** [comment]
It's a trivial fix, but it's also MariaDB adding extras onto the description object that do not adhere (at all) to the DBAPI2[^1] standard (note that the cursor description field is also not necessarily a `namedtuple`, it just has to be a sequence type) ;)

[^1]: https://peps.python.org/pep-0249/#cursor-attributes

**Comment by alexander-beedie** [comment]
FYI: Polars 1.1.0 was released a few hours ago, and contains the fix for this ;)
