### ISSUE TITLE
Example shown in `polars.Expr.bin.decode` shows the `encode` method instead

### ISSUE THREAD

**Issue by heshamdar** [pola-rs/polars#17469]
### Description

Very minor, the code example just needs to be changed to show the decode method instead of encode

```
colors = pl.DataFrame(
    {
        "name": ["black", "yellow", "blue"],
        "code": [b"\x00\x00\x00", b"\xff\xff\x00", b"\x00\x00\xff"],
    }
)
colors.with_columns(
    pl.col("code").bin.encode("hex").alias("encoded"),
)
```

### Link

https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bin.decode.html#polars-expr-bin-decode

**Comment by jonaylor89** [comment]
I've been looking for something low-hanging to contribute. I can send over a PR today
