### ISSUE TITLE
docs(python): Update DataFrame.partition_by docstring to match new behavior

### ISSUE THREAD

**Issue by d-laub** [pola-rs/polars#17467]
### Description

Documentation for [DataFrame.partition_by](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.partition_by.html#polars.DataFrame.partition_byddd) v1.0.0 does not reflect changes from #16793

> as_dict
> Return a dictionary instead of a list. The dictionary keys are tuples of the distinct group values that identify each group. If a single string was passed to `by`, the keys are a single value instead of a tuple.

This conflicts with the runtime behavior where the dictionary keys are tuples when `by` is a string.

```python
>>> df = pl.DataFrame({"foo": ["a", "a", "b"], "bar": [1, 2, 3]})
>>> print(df.partition_by("foo", as_dict=True).keys())
dict_keys([('a',), ('b',)])
```

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.partition_by.html#polars.DataFrame.partition_byddd

**Comment by nameexhaustion** [comment]
Fixed by https://github.com/pola-rs/polars/pull/17394
