### ISSUE TITLE
`plot` docs not displaying completely

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#17503]
### Description

The docs for `plot` are missing the first few lines.
Specifically, the fact it is a property (namespace), the link to the source, and the unstable warning.

The `style` docs are an example of what it should look like.

[`DataFrame.plot`](https://docs.pola.rs/api/python/dev/reference/dataframe/plot.html)
[`Series.plot`](https://docs.pola.rs/api/python/dev/reference/series/plot.html)
[`DataFrame.style`](https://docs.pola.rs/api/python/dev/reference/dataframe/style.html)

The issue appears in both 1 (stable) and dev version of the docs.

**Comment by MarcoGorelli** [comment]
thanks @henryharbeck for reporting, fancy making a PR?

**Comment by henryharbeck** [comment]
No worries!

I was having a look before I reported the issue, but didn't spot the problem until taking another look just now. Was looking in the wrong place, haha. PR incoming.
