### ISSUE TITLE
[DOC/QST]: inconsistency in behaviour of `Expr.sum` vs `+` with null values.

### ISSUE THREAD

**Issue by wence-** [pola-rs/polars#17527]
(This also applies, mutatis mutandis to `product` vs `*`)

If I have a column (or group) of all null values, then the `sum` aggregation produces the neutral element (0). In contrast, the `cum_sum` aggregation produces all nulls, and a binary operation between a null and non-null value produces a null:

```python
import polars as pl

df = pl.DataFrame({"a": pl.Series([None, None], dtype=pl.Int32()),
                   "b": pl.Series([1, 2], dtype=pl.Int32())})

print(df.select(pl.col("a").sum()))

print(df.select(pl.col("a").cum_sum()))

print(df.select(pl.col("a") + pl.col("b")))
```
```
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 0   │
└─────┘
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i32  │
╞══════╡
│ null │
│ null │
└──────┘
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i32  │
╞══════╡
│ null │
│ null │
└──────┘
```

Is this just a consequence of the way `sum` is implemented, or a deliberate choice? It was a bit surprising to me that `sum` treats `null` as the identity element, but `+` and `cum_sum` do not.

(I see pandas has the same behaviour, so maybe this is the status quo).

**Comment by phi-friday** [comment]
it works same in sql(without cumsum, only tested in postgresql).

**Comment by mcrumiller** [comment]
The reason is because the sum of a Series begins with 0 and accumulates as values are encountered. If no values are encountered, the sum remains 0:

```pycon
>>> pl.Series([], dtype=pl.Int32).sum()
0
>>> pl.Series([None], dtype=pl.Int32).sum()
0
>>> pl.Series([None, 1], dtype=pl.Int32).sum()
1
```

FYI the [pandas documentation for `sum`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html) says:

> By default, the sum of an empty or all-NA Series is `0`.
>
>    ```
>    pd.Series([], dtype="float64").sum()  # min_count=0 is the default
>    0.0
>    ```
>
> This can be controlled with the `min_count` parameter. For example, if you’d like the sum of an empty series to be NaN, pass `min_count=1`.

Polars doesn't have a "minimum required amount of data" and so the value is always 0, and thus the sum starts at 0.

**Comment by wence-** [comment]
> The reason is because the sum of a Series begins with 0 and accumulates as values are encountered. If no values are encountered, the sum remains 0:


Sure, but then why not the same for cumulative sum? From a maths point of view you might say the only difference is that sum is a reduction and cum_sum is a scan.

**Comment by mcrumiller** [comment]
FYI I agree that this is a bit arbitrary and that the cumulative sum could be defined as "the accumulated sum after the value at index `i`".

**Comment by wence-** [comment]
> it works same in sql(without cumsum, only tested in postgresql).

For another (two) datapoints:

Rationale for this discussion here is that for the GPU engine I use libcudf as the backend, and obviously want to match polars semantics. Where the execution engines have made diverging decisions that's obviously fine, but before jumping through too many hoops I like to check that the existing behaviour isn't just an accident of fate.

libcudf produces a null value for all these cases, as does duckdb:

```
import polars as pl
import duckdb
df = pl.DataFrame({"key": [1, 2, 2, 2], "value": pl.Series([None, None, None, None], dtype=pl.Int32())})

print(df.group_by("key").agg(pl.col("value").sum()))

print(duckdb.sql("select * from df").aggregate("key, sum(value)", group_expr="key"))

print(df.select(pl.col("value").sum().over("key")))

print(duckdb.sql("select sum(value) over (partition by key) from df"))

print(df.select(pl.col("value").sum()))

print(duckdb.sql("select sum(value) from df"))
```
```
shape: (2, 2)
┌─────┬───────┐
│ key ┆ value │
│ --- ┆ ---   │
│ i64 ┆ i32   │
╞═════╪═══════╡
│ 1   ┆ 0     │
│ 2   ┆ 0     │
└─────┴───────┘
┌───────┬──────────────┐
│  key  │ sum("value") │
│ int64 │    int128    │
├───────┼──────────────┤
│     1 │         NULL │
│     2 │         NULL │
└───────┴──────────────┘

shape: (4, 1)
┌───────┐
│ value │
│ ---   │
│ i32   │
╞═══════╡
│ 0     │
│ 0     │
│ 0     │
│ 0     │
└───────┘
┌────────────────────────────────────────┐
│ sum("value") OVER (PARTITION BY "key") │
│                 int128                 │
├────────────────────────────────────────┤
│                                   NULL │
│                                   NULL │
│                                   NULL │
│                                   NULL │
└────────────────────────────────────────┘

shape: (1, 1)
┌───────┐
│ value │
│ ---   │
│ i32   │
╞═══════╡
│ 0     │
└───────┘
┌──────────────┐
│ sum("value") │
│    int128    │
├──────────────┤
│         NULL │
shape: (2, 2)
┌─────┬───────┐
│ key ┆ value │
│ --- ┆ ---   │
│ i64 ┆ i32   │
╞═════╪═══════╡
│ 1   ┆ 0     │
│ 2   ┆ 0     │
└─────┴───────┘
┌───────┬──────────────┐
│  key  │ sum("value") │
│ int64 │    int128    │
├───────┼──────────────┤
│     1 │         NULL │
│     2 │         NULL │
└───────┴──────────────┘

shape: (4, 1)
┌───────┐
│ value │
│ ---   │
│ i32   │
╞═══════╡
│ 0     │
│ 0     │
│ 0     │
│ 0     │
└───────┘
┌────────────────────────────────────────┐
│ sum("value") OVER (PARTITION BY "key") │
│                 int128                 │
├────────────────────────────────────────┤
│                                   NULL │
│                                   NULL │
│                                   NULL │
│                                   NULL │
└────────────────────────────────────────┘

shape: (1, 1)
┌───────┐
│ value │
│ ---   │
│ i32   │
╞═══════╡
│ 0     │
└───────┘
┌──────────────┐
│ sum("value") │
│    int128    │
├──────────────┤
│         NULL │
└──────────────┘
```

**Comment by nameexhaustion** [comment]
The behavior does differ from some other libraries but it is intentional. Some aggregations have a defined identity value that is returned for empty sets -

```python
# Not an exhaustive list, but some examples
pl.Series("x", dtype=pl.Boolean).to_frame().select(
    func(pl.first()).alias(func.__name__)
    for func in [
        pl.Expr.sum,
        pl.Expr.product,
        pl.Expr.all,
        pl.Expr.any,
    ]
)
shape: (1, 4)
┌─────┬─────────┬──────┬───────┐
│ sum ┆ product ┆ all  ┆ any   │
│ --- ┆ ---     ┆ ---  ┆ ---   │
│ u32 ┆ i64     ┆ bool ┆ bool  │
╞═════╪═════════╪══════╪═══════╡
│ 0   ┆ 1       ┆ true ┆ false │
└─────┴─────────┴──────┴───────┘
```

Some refs:
* https://github.com/pola-rs/polars/issues/10016#issuecomment-1645438349
* https://github.com/pola-rs/polars/pull/9894
* https://github.com/pola-rs/polars/pull/9576

For column-wise addition, it isn't an aggregation and follows the NULL behavior of a generic binary function, which outputs NULL if either of the inputs are NULL.

**Comment by wence-** [comment]
> The behavior does differ from some other libraries but it is intentional. Some aggregations have a defined identity value that is returned for empty sets -

Thanks for those references, I obviously didn't manage to do enough searching.

One thing I would note is that this treatment means that sum isn't a linear operator in the presence of nulls and therefore doesn't distribute over addition, which might be a surprising footgun:

```
df = pl.DataFrame(
    {
        "v1": pl.Series([None, None, None, None], dtype=pl.Int32()),
        "v2": pl.Series([1, 2, 3, 4]),
    }
)

df.select(
    (pl.col("v1") + pl.col("v2")).sum().alias("(v1 + v2).sum()"),
    (pl.col("v1").sum() + pl.col("v2").sum()).alias("v1.sum() + v2.sum()"),
)
shape: (1, 2)
┌─────────────────┬─────────────────────┐
│ (v1 + v2).sum() ┆ v1.sum() + v2.sum() │
│ ---             ┆ ---                 │
│ i64             ┆ i64                 │
╞═════════════════╪═════════════════════╡
│ 0               ┆ 10                  │
└─────────────────┴─────────────────────┘
```

That said, given this has been gone over a number of times, happy to close and I will endeavour to produce matching answers in the gpu engine.

**Comment by deanm0000** [comment]
I don't think it is intentional actually or if it is, there's inconsistency.

Take a look [here](https://github.com/pola-rs/polars/blob/c8e4822ac86a9af0dd79a79c7e98def4458f18e6/crates/polars-arrow/src/compute/aggregate/sum.rs#L88-L103)

In that function, it's explicitly saying if everything is null then return null.
