### ISSUE TITLE
Got "ArrowInvalid: These dictionaries cannot be combined"  for pyarrow dictionary ChunkedArray

### ISSUE THREAD

**Issue by zqin** [pola-rs/polars#1752]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

v0.10.19

#### What operating system are you using polars on?

RHEL8

#### Describe your bug.

When the input of `from_arrow()` is a concatenated pyarrow table, while that table is constructed from multiple chunked arrays of dictionaries data and the index type overflows, polars `from_arrow()` throws

```
ArrowInvalid: These dictionaries cannot be combined.  The unified dictionary requires a larger index type.
```

This issue occurred on all versions after v0.9.5. It seems introduced by #1399. If I added code https://github.com/pola-rs/polars/blob/py-polars-v0.9.5/py-polars/polars/utils.py#L35-L43 back to v0.10.19, issue went away.

#### What are the steps to reproduce the behavior?

```ipython
In [1]: import polars as pl
   ...: import pyarrow as pa
   ...: import pandas as pd

In [2]: dfs = []

In [3]: for i in range(200):
   ...:     dfs.append(pa.table({"col_name": pa.array(["value_" + str(i)], pa.dictionary(pa.int8(), pa.string())),}))
   ...:

In [4]: df = pa.concat_tables(dfs, promote=True)

In [5]: array = df["col_name"]

In [6]: array.num_chunks
Out[6]: 200

In [7]: df_pl = pl.from_arrow(df)
```

#### What is the actual behavior?

```
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-7-7390b33d606d> in <module>
----> 1 df_pl = pl.from_arrow(df)

.../.venv/lib/python3.6/site-packages/polars/convert.py in from_arrow(a, rechunk)
    204         raise ImportError("'pyarrow' is required when using from_arrow().")
    205     if isinstance(a, pa.Table):
--> 206         return pl.DataFrame._from_arrow(a, rechunk=rechunk)
    207     elif isinstance(a, (pa.Array, pa.ChunkedArray)):
    208         return pl.Series._from_arrow("", a)

.../.venv/lib/python3.6/site-packages/polars/eager/frame.py in _from_arrow(cls, data, columns, rechunk)
    315         DataFrame
    316         """
--> 317         return cls._from_pydf(arrow_to_pydf(data, columns=columns, rechunk=rechunk))
    318
    319     @classmethod

.../.venv/lib/python3.6/site-packages/polars/internals/construction.py in arrow_to_pydf(data, columns, rechunk)
    372             name = column._name
    373
--> 374         column = coerce_arrow(column)
    375         data_dict[name] = column
    376

.../.venv/lib/python3.6/site-packages/polars/utils.py in coerce_arrow(array)
     52             array = pa.chunked_array(chunks)
     53
---> 54         array = array.combine_chunks()
     55     return array
     56

.../.venv/lib/python3.6/site-packages/pyarrow/table.pxi in pyarrow.lib.ChunkedArray.combine_chunks()

.../.venv/lib/python3.6/site-packages/pyarrow/array.pxi in pyarrow.lib.concat_arrays()

.../.venv/lib/python3.6/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

.../.venv/lib/python3.6/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: These dictionaries cannot be combined.  The unified dictionary requires a larger index type.
```

#### What is the expected behavior?

Return a polars DataFrame or Series.

#### What do you think polars should have done?

The removed piece of code (https://github.com/pola-rs/polars/blob/py-polars-v0.9.5/py-polars/polars/utils.py#L35-L43) cast dictionary type to `large_utf8()` data type so the following call on `array.combine_chunks()` will not hit the overflow issue of index types (e.g., 200 vs. int8).

```
In [8]: array_cast = pa.compute.cast(array, pa.large_utf8())

In [14]: array_cast.type
Out[14]: DataType(large_string)

In [15]: df.schema
Out[15]: col_name: dictionary<values=string, indices=int8, ordered=0>
```

**Comment by ritchie46** [comment]
Thanks for the issue report. Will take a look.

**Comment by ritchie46** [comment]
Can you tell me a bit about your use case? How do you get these number of small tables? Maybe for now the easiest fix is to coerce the dictionary type to that of a larger index?

**Comment by zqin** [comment]
> Can you tell me a bit about your use case? How do you get these number of small tables? Maybe for now the easiest fix is to coerce the dictionary type to that of a larger index?

One use case could be that a program runs on multiple resources in parallel to generate data in pyarrow table format with same schema then a centralized collector merges those data into one table. Yes. I think that is the easiest fix.
