### ISSUE TITLE
Incorrect max of two columns

### ISSUE THREAD

**Issue by olivier-lacroix** [pola-rs/polars#1753]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.19

#### What operating system are you using polars on?

Linux

#### Describe your bug.

`pl.max` expression applied to several columns returns 0

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame(
        {
            "A": [1, 2, 3, 4, 5],
            "fruits": ["banana", "banana", "apple", "apple", "banana"],
            "B": [5, 4, 3, 2, 1],
            "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
        }
    )

df.with_column(pl.max([pl.col("A"),pl.col("B")]))
```

#### What is the actual behavior?

A | fruits | B | cars | max
-- | -- | -- | -- | --
i64 | str | i64 | str | i64
1 | "banana" | 5 | "beetle" | 0
2 | "banana" | 4 | "audi" | 0
3 | "apple" | 3 | "beetle" | 0
4 | "apple" | 2 | "beetle" | 0
5 | "banana" | 1 | "beetle" |  0

#### What is the expected behavior?

A | fruits | B | cars | max
-- | -- | -- | -- | --
i64 | str | i64 | str | i64
1 | "banana" | 5 | "beetle" | 5
2 | "banana" | 4 | "audi" | 4
3 | "apple" | 3 | "beetle" | 3
4 | "apple" | 2 | "beetle" | 4
5 | "banana" | 1 | "beetle" | 5

**Comment by ritchie46** [comment]
The input is incorrect. `pl.max` expects a dingle ezpression. We should thrown an error here.

**Comment by olivier-lacroix** [comment]
@ritchie46 , based on the documentation, my understanding was that by providing a list, the row-wise maximum was returned ?

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.max.html

**Comment by ritchie46** [comment]
Ho.. you are right.. will take a look.
