### ISSUE TITLE
Public api exposes private types

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#17535]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I've been observing an annoying pylance warning about incorrect typing of `pl.read_database_uri` i.e. my code was:

```
engine="adbc"
uri="..."

pl.read_database_uri(
        query="...",
        uri=uri,
        engine=engine,
    )
```

Pylance doesn't like that I'm passing a variable of type "str" (engine) when the `engine` argument of `read_database_uri` is of type `DbReadEngine`.

I tried to shut up pylance by explicitly defining engine as DbReadEngine, i.e.

```
engine:DbReadEngine="adbc"
uri="..."

pl.read_database_uri(
        query="...",
        uri=uri,
        engine=engine,
    )
```

But I noticed that DbReadEngine is defined in a "private" module (i.e. _typing). It seems that in the code it's only imported if `TYPE_CHECKING` is true - which I believe to mean only when a linter is running, but I would have thought any types that are exposed publicly should be defined in a public module?

This may be a pylance issue, I would expect that the inferred type of `engine="adbc"` should be `Literal["adbc"]` which prevents the error

### Issue description

n/a

### Expected behavior

n/a

### Installed versions

<details>

```
DEBUG:matplotlib:matplotlib data path: [/home/david/dev/datascience-projects/.venv/lib/python3.10/site-packages/matplotlib/mpl-data](https://file+.vscode-resource.vscode-cdn.net/home/david/dev/datascience-projects/.venv/lib/python3.10/site-packages/matplotlib/mpl-data)
DEBUG:matplotlib:CONFIGDIR=/home/david/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Aug 24 2023, 15:09:27) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  1.1.0
cloudpickle:          <not installed>
connectorx:           0.3.3
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         0.10.0
hvplot:               0.10.0
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by phi-friday** [comment]
[This document](https://docs.pola.rs/releases/upgrade/1/#remove-re-export-of-type-aliases) might be helpful.

**Comment by phi-friday** [comment]
And in my environment, `pylance` doesn't throw an error.
![스크린샷 2024-07-10 오전 11 07 35](https://github.com/pola-rs/polars/assets/19867547/be8cea60-b72d-454d-95da-430f44cb9883)

**Comment by david-waterworth** [comment]
Yeah I have a feeling this is a `vscode` notebooks issues - I'm suddenly seeing all sorts of new pylance issues for simple things like `import polars as pl` showing a warning that `pl` is not used - because the import is in cell #1 and the usage is in cell #2. (and several non polars issues)

This only just started happening but it looks like it's decided that each notebook cell is unrelated.

**Comment by phi-friday** [comment]
> Yeah I have a feeling this is a `vscode` notebooks issues - I'm suddenly seeing all sorts of new pylance issues for simple things like `import polars as pl` showing a warning that `pl` is not used - because the import is in cell #1 and the usage is in cell #2. (and several non polars issues)
> 
> This only just started happening but it looks like it's decided that each notebook cell is unrelated.

i found it
![스크린샷 2024-07-10 오후 1 00 38](https://github.com/pola-rs/polars/assets/19867547/20e390ed-dfdf-41d8-bc60-f7603392e140)

**Comment by david-waterworth** [comment]
Hmm so in the last example, `# pyright: strict` seems to cause the issue - and you first examples are more or less what I'm experiencing.

I guess this isn't a polars issue, nor sure where to report it though...

**Comment by phi-friday** [comment]
> Hmm so in the last example, `# pyright: strict` seems to cause the issue - and you first examples are more or less what I'm experiencing.
> 
> I guess this isn't a polars issue, nor sure where to report it though...

There doesn't seem to be a problem either.
This is because `str` may not be `Literal["adbc", "connectorx"]`.

Even if the `polars._typing` module is exposed, the same problem may occur.
![스크린샷 2024-07-10 오후 4 18 57](https://github.com/pola-rs/polars/assets/19867547/74763b22-aed6-42e4-b432-3315932da1eb)


You can narrow type using `TypeGuard` or `TypeIs`, or ignore them with `Any`.
![스크린샷 2024-07-10 오후 4 19 47](https://github.com/pola-rs/polars/assets/19867547/a2529a8e-5a2f-4b63-8cd8-9562e9f7b978)

**Comment by david-waterworth** [comment]
OK I'll close this
