### ISSUE TITLE
Do not use unwrap for code that returns PolarsResult

### ISSUE THREAD

**Issue by evbo** [pola-rs/polars#17555]
### Description

It's simple enough to unpivot a missing column name. So maybe return an `Err` instead of unwrapping?:

https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/plans/functions/schema.rs#L187

Helps error handling greatly as panics are harder to report.

**Comment by coastalwhite** [comment]
Let's try to stay constructive.

Do you have a reproduction case of your panic. Usually, we can fix such issues very quickly.
