### ISSUE TITLE
Support reading and writing custom IPC metadata

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#17560]
### Description

The IpcReader should have a function that returns custom metadata stored in the file, and the IpcWriter should have an option to set custom metadata to be written.

**Comment by nameexhaustion** [comment]
Hi @PrettyWood 

Thanks for the offer to help! We haven't had the time to look at this yet due to how busy we've been.

For some background, it was removed from the arrow schema struct because we internally didn't want to carry custom metadata around on it. This is still the case - but we'd be happy for there to be functions on the `IpcReader` and `IpcWriter` structs themselves that allow for reading / writing custom metadata.

For the implementation, I would start with making something similar to this - 

```rust
struct IpcReader {
    fn custom_metadata(&self) -> &Arc<PlHashMap<PlSmallStr, PlSmallStr>> {}
}

struct IpcWriter {
    fn set_custom_metadata(&mut self, custom_metdata: Arc<PlHashMap<PlSmallStr, PlSmallStr>>) ->  {}
}
```

It could also be helpful to look at some of the deleted code in https://github.com/pola-rs/polars/pull/18527/files.

I believe IPC supports message-level metadata, but for the initial PR, we should restrict to only support writing file-level custom metadata

**Comment by lukapeschke** [comment]
Hi @nameexhaustion thanks for the hints! I've started working on this, and I noticed that the async IPC stream sink was gone as well since https://github.com/pola-rs/polars/pull/19223 . 

We were using it, and would like to keep using an async writer. Is this something you'd be willing to accept if we worked on it ?

**Comment by lukapeschke** [comment]
@nameexhaustion would something like https://github.com/pola-rs/polars/pull/20066 work for you ? If yes, I'll add a few tests

**Comment by nameexhaustion** [comment]
> Hi @nameexhaustion thanks for the hints! I've started working on this, and I noticed that the async IPC stream sink was gone as well since #19223 .
> 
> We were using it, and would like to keep using an async writer. Is this something you'd be willing to accept if we worked on it ?

Hello,

I won't be able to give you an answer for this one. From what I can tell, it was removed due to not being worth the maintenance burden as we were not using it. I think it would be better to consult with Ritchie for this matter.
