### ISSUE TITLE
Make `item()` more intuitive and versatile for all unambiguous `(row, column)` requests

### ISSUE THREAD

**Issue by matterhorn103** [pola-rs/polars#17573]
### Description

On the whole it seems very wise that polars didn't go down the `pandas` route and have `loc` and `iloc` or similar.

However, when it comes to obtaining a single scalar of interest from a DataFrame, `df.item()` is a bit restrictive, as the row can only be specified by index. It would be good if a predicate could be provided for the row argument instead of an integer.

This would make a look-up much more concise:

```python
import polars as pl

df = pl.DataFrame({
    "id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35]
})

# Some current possible approaches, as far as I know
bob_age = df.filter(pl.col("name") == "Bob").item(0, "age")
bob_age = df.row(by_predicate=(pl.col("name") == "Bob"), named=True)["age"]

# Proposed concise intuitive approach
bob_age = df.item((pl.col("name") == "Bob"), "age")
```

The `filter()` approach has the disadvantage that it won't error if `"Bob"` occurs in multiple rows, and the `row()` approach is verbose, non-obvious, and according to the docs for `row()` the use of `named=True` is expensive.

As for `df.row()`, any predicate passed to `item()` that returned anything other than one row would raise a `TooManyRowsReturnedError` or `NoRowsReturnedError` as appropriate.

**Comment by stinodego** [comment]
The right way to do what you're trying to do is `df.select("age").filter(pl.col("name") == "Bob").item()`.

We will not overload `item` further. I personally don't think it should take any arguments at all. `item` should be for taking the singular item out of a 1 by 1 DataFrame.

You can use square brackets (`__getitem__`) for some more 'magic' if desired, but I generally do not recommend it.

**Comment by Julian-J-S** [comment]
the following is also pretty nice:
```python
df.filter(name="Bob")["age"].item()
```

**Comment by matterhorn103** [comment]
Thanks for the response.

> We will not overload `item` further. I personally don't think it should take any arguments at all. `item` should be for taking the singular item out of a 1 by 1 DataFrame.

If that's the policy and changing the behaviour of `item()` is undesirable, would it not be possible to have a separate `lookup()` function precisely for this task?

Having to narrow it down to a 1 by 1 DataFrame first just makes it so *verbose* for such a conceptually simple task. And *still* having to call `item()` even after having done that is also very unintuitive when you're starting out with DataFrames – why using the row index and doing `df["name"][2]` returns a scalar straight away, but other methods to narrow a DataFrame to a single item give a (1,1) DataFrame, is not obvious.

I just feel like there are probably many users like me, who aren't data scientists but are just using polars to manipulate data sets, who are regularly interested in specific values, and then it seems a shame not to have a conciser syntax for a common task.

pandas has `df.at()`, after all, and Excel has XLOOKUP.

If you have e.g. a large dataset saved as a csv and all you really want to know is what the temperature was at a given weather station, then polars could be by far the quickest and easiest way to get the answer if you could just do:

```python
import polars as pl

df = pl.scan_csv("weather_data.csv")
answer = df.lookup((pl.col("location") == "Sydney"), "temperature")
print(answer)
```

and would be even more amazing if the row filter could optionally be specified as a keyword argument similar to when using `filter()` itself:

```python
answer = df.lookup(location="Sydney", column="temperature")
```

> the following is also pretty nice:
> 
> ```python
> df.filter(name="Bob")["age"].item()
> ```

I agree that it's fairly nice. I had the impression that the keyword arguments for row and the use of `df[str]` were discouraged, but maybe I got the wrong impression.

> The right way to do what you're trying to do is `df.select("age").filter(pl.col("name") == "Bob").item()`.

Well this is part of the unintuitiveness of it – that example doesn't work because after the selection the name column doesn't exist any more, so it gives `ColumnNotFoundError: unable to find column "name"; valid columns: ["age"]`. Doing the filter followed by the select works, of course.

Whereas if one is new to polars(/pandas etc.) then it doesn't feel like it ought to be a step-wise operation, so it is confusing to only have it work a certain way round. If someone is coming from Excel spreadsheets, they just want the equivalent of looking to find the intersection of a given row and a given column. They wouldn't even consider applying a filter to the spreadsheet first, and then looking in the column of interest.

**Comment by cmdlineluser** [comment]
> that example doesn't work

Perhaps `Expr.filter` was the intended example:

```python
>>> df.select(pl.col("age").filter(name="Bob")).item()
30
```
