### ISSUE TITLE
Optimize `is_null().any()` and similar operations that can be written in terms of null count

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#17605]
### Description

In Polars the null count of a series is cached, so it can be retrieved for free. Some operations can be re-written during optimization to be much more efficient using this.

### Example
```python
import polars as pl
import timeit

lf = pl.select(pl.repeat(None, 10_000_000, dtype=pl.Int8)).lazy()

q = lf.select(pl.first().is_null().any()).collect
t = timeit.timeit(q, number=10_000)
print("is_null().any() :: ", t)

q = lf.select(pl.first().null_count() > 0).collect
t = timeit.timeit(q, number=10_000)
print("null_count() > 0 :: ", t)
```

Output
```python
is_null().any() ::  1.7241754580754787
null_count() > 0 ::  0.04942204221151769
```

It's probably also quite common for users to write code like this (e.g. to a human `is_not_null().any()` is a little easier to understand than `len() > null_count()`).

Not an exhaustive list, but here's some examples that can be re-written:
* `is_null().all()` -> `null_count() == len()`
* `is_null().any()` -> `null_count() > 0`
* `is_not_null().all()` -> `null_count() == 0`
* `is_not_null().any()` -> `len() > null_count()`
* `is_null().sum()` -> `null_count()`
* `is_not_null().sum()` -> `len() - null_count()`
* `drop_nulls().len()` -> `len() - null_count()`
* `drop_nulls().count()` -> `len() - null_count()`

This might be a little advanced for a first issue, but it's a very good opportunity to learn a bit about how Polars' optimizers work. The starting point is probably here - https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/plans/optimizer/simplify_functions.rs.

**Comment by mcrumiller** [comment]
Isn't there a `has_nulls()` function already?

**Comment by manojks1999** [comment]
@mcrumiller can I work on this?

**Comment by mcrumiller** [comment]
@manojks1999 I'm just a user/contributor so I don't have any say what goes on around here, but anyone is welcome to contribute!

**Comment by nameexhaustion** [comment]
@manojks1999 feel free to

**Comment by deanm0000** [comment]
Is it in scope to suggest that the null count get picked up from parquet stats?

For example:

```
with fs.open(cloud_path, "rb") as ff:
    pqmeta = pq.ParquetFile(ff).metadata
column_num_count = [0] * pqmeta.num_columns
for rg in range(pqmeta.num_row_groups):
    for col in range(pqmeta.num_columns):
        num_values = pqmeta.row_group(rg).column(col).statistics.num_values
        null_count = pqmeta.row_group(rg).column(col).statistics.null_count
        column_num_count[col]=column_num_count[col]+num_values-null_count
column_num_count = {name:column_num_count[i] for i, name in enumerate(pqmeta.schema.names)}
```
finishes in 0.6 sec in a jupyter window whereas

```
pl.scan_parquet(cloud_path).select(pl.all().drop_nulls().len()).collect()
```
takes 6.5sec

**Comment by nameexhaustion** [comment]
> Is it in scope to suggest that the null count get picked up from parquet stats?

Sourcing the null count from Parquet statistics should be a separate issue - the current issue is purely to do with simplifying expressions.

**Comment by barak1412** [comment]
@nameexhaustion are you sure all cases above are optimizations?

For instance, I tried `is_null().all() -> null_count() == len()` and it was much slower.

So far I have implemented the first one, and it's working.
I hope I will finish other cases soon, but I want to be sure we will get more optimized code on every scenario.

**Comment by mcrumiller** [comment]
@barak1412 for speed tests please make sure you are compiling in release mode.

**Comment by barak1412** [comment]
@mcrumiller I also tried on release mode, still much slower:

![image](https://github.com/user-attachments/assets/2ce30a66-964d-4bea-aac3-f44d47b07d6f)

I will try to add only those that perform better.

**Comment by barak1412** [comment]
@mcrumiller @nameexhaustion 

Those are the final measurements in release mode:

![image](https://github.com/user-attachments/assets/0b3869ce-df91-4b9f-8f63-5cedd29ed06e)

This leaves us with only 3 optimization rules, are you all agree?

**Comment by barak1412** [comment]
@nameexhaustion 

![image](https://github.com/user-attachments/assets/64ac1acc-84ce-4426-bc77-6a6462bfad95)

Looks much better, thanks.

Any idea why `drop_nulls()` is more efficient?

**Comment by nameexhaustion** [comment]
I would guess `drop_nulls()` was a no-op as the column didn't contain NULLs, and there was some overhead evaluating `len() - null_count()` as a `BinaryExpr`, likely some multithreading overhead. I imagine `drop_nulls()` on a column containing NULLs would perform much slower.

**Comment by barak1412** [comment]
@nameexhaustion thanks, I will try tommorow add NULLS and check `drop_nulls()` again.

**Comment by barak1412** [comment]
@nameexhaustion you were right - with NULLS it's much more efficient.

Regarding implementation, it seems `len()`, `sum()` and `count()` are not regular `FunctionExpr`, and I am struggling finding the right place of the change.

For instance, for the `pl.first().drop_nulls().len()` expression, I looked at the `Arena<AExpr>` supplied to the `optimize_functions` function, which looks -
```
Arena {
    version: 4,
    items: [
        Column(
            "literal",
        ),
        Function {
            input: [
                ExprIR {
                    output_name: ColumnLhs(
                        "literal",
                    ),
                    node: Node(
                        0,
                    ),
                },
            ],
            function: DropNulls,
            options: FunctionOptions {
                collect_groups: GroupWise,
                fmt_str: "",
                cast_to_supertypes: None,
                check_lengths: UnsafeBool(
                    true,
                ),
                flags: FunctionFlags(
                    ALLOW_GROUP_AWARE | ALLOW_EMPTY_INPUTS,
                ),
            },
        },
        Agg(
            Count(
                Node(
                    1,
                ),
                true,
            ),
        ),
    ],
}
```

And it seems like the `len()` is translated to the `AExpr` of:
```
Agg(
    Count(
        Node(
            1,
        ),
        true,
    ),
)
```

But I am not sure what is the right place to modify it.

Thanks.

**Comment by nameexhaustion** [comment]
> Regarding implementation, it seems len(), sum() and count() are not regular FunctionExpr

They are aggregation exprs - you should be able to match them under `AExpr::Agg(IRAggExpr::)`

**Comment by barak1412** [comment]
@nameexhaustion thanks, sorry for the amount questions, but I learn a lot from trial to trial.

So far completed:

- is_null().all() -> null_count() == len()
- is_null().any() -> null_count() > 0
- is_not_null().all() -> null_count() == 0
- is_not_null().any() -> null_count() < len()

Regarding `AExpr::Agg(IRAggExpr::)`, its type isn't `FunctionExpr` like the global match in the `optimize_function`, should I take it from the `input` parameter directly?

Thanks.

**Comment by nameexhaustion** [comment]
It might be here -

https://github.com/pola-rs/polars/blob/9833887dd19c4bd7ef72f33f80015d5293a144b7/crates/polars-plan/src/plans/optimizer/simplify_expr.rs#L433

You can also double-check that the overwrite is successful using `LazyFrame.explain()`

**Comment by barak1412** [comment]
@nameexhaustion 

It seems all rules are working now, however afer writing tests, I noticed two problems:

- In `is_not_null().sum() -> len() - null_count()`, the former returns the original column name, wheras the later one returns 'len' . I wonder how can I reach the original name for an extra `alias()` expression I can add.

- It seems all count operations (e.g. `count`) returns unsined 32bit int. However, using `-` operation returns signed value. I can add hard-coded cast to unsigned 32bit int, but I remember polars can be compiled for 64bit sizes. Is there any place I can take the size bits representation?

Thanks.

**Comment by amitvijapur** [comment]
The null_count caching approach makes sense - would love to explore the simplify_functions.rs file to understand how this optimization could work. Is this still available to work on?
