### ISSUE TITLE
Specifying NumPy dtype in to_numpy method

### ISSUE THREAD

**Issue by Olobir** [pola-rs/polars#17620]
### Description

The "to_numpy" method in Polars currently converts a Series or DataFrame to a NumPy array, but it doesn't allow specifying the desired NumPy dtype during conversion.
Please enhance the "to_numpy" method to specify the resulting dtype.

```
# Example:
series = pl.Series(name='data', values=['A', 'B', 'C'], dtype=pl.String)
dtype = np.dtypes.StringDType(na_object=np.nan)

# present conversion
array = series.to_numpy().astype(dtype)
# array(['A', 'B', 'C'], dtype=StringDType(na_object=nan))

# desired conversion
array = series.to_numpy(dtype=dtype)
```

**Comment by s-banach** [comment]
#7283
