### ISSUE TITLE
Performance: Calculation 200x+ slower without rechunking or sorting first

### ISSUE THREAD

**Issue by Julian-J-S** [pola-rs/polars#17637]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df_sales = pl.read_parquet(PATH_SALES)
# simple df (10_000_000, 5)

df_sales.with_columns(
    time_between_sales=pl.col("created_on")
    .diff()
    .over(
        partition_by="customer_id",
        order_by="created_on",
    ),
)
```

### Issue description

I created a simple sales_df with polars that I saved as parquet.
When I read the data back in and do a simple window calculation the performance is super slow (~70 sec).

However if I
- `rechunk()` or
- `.sort("created_on", "customer_id")`

first the performance is ~200x++ faster (~0.3 sec)

possibly related: #17562

### Expected behavior

Great Performance as usual 😄 

When I read a df that I just saved using polars I expect good performance without need to explicitly rechunk myself.

### Installed versions

<details>

```
1.1.0
```

</details>

**Comment by Julian-J-S** [comment]
### Reproducable Dataset:
on my pc
- fast with `N=1_000_000`
- slow with `N=10_000_000`

```python
import numpy as np
import polars as pl

N = 10_000_000
CUSTOMER_IDS = np.random.randint(10_000, 1_000_000, N)
SALES_DATES = np.random.randint(0, 1000, N)

df = (
    pl.DataFrame({"customer_id": CUSTOMER_IDS, "sales_date": SALES_DATES})
    .sort("sales_date")
    .with_columns(pl.col("sales_date").cast(pl.Date))
)
```

### Before Parquet (fast, ~2 sec)
```python
df.with_columns(
    time_between_sales=pl.col("sales_date")
    .diff()
    .over(
        partition_by="customer_id",
        order_by="sales_date",
    ),
)
```

### Write Parquet & Read again
```python
df.write_parquet("dummy.parquet")

df_dummy = pl.read_parquet("dummy.parquet")
```

### NEW df from parquet (sloooooooow)
```python
df_dummy.with_columns(
    time_between_sales=pl.col("sales_date")
    .diff()
    .over(
        partition_by="customer_id",
        order_by="sales_date",
    ),
)
```

### NEW df from parquet with rechunk (fast again)
```python
df_dummy.rechunk().with_columns( # >>>>>> rechunk
    time_between_sales=pl.col("sales_date")
    .diff()
    .over(
        partition_by="customer_id",
        order_by="sales_date",
    ),
)
```

**Comment by deanm0000** [comment]
This is somewhat intentional since https://github.com/pola-rs/polars/pull/16427

if you `read_parquet(file, rechunk=True)` then you'll get what you want.

or `write_parquet(file, row_group_size=10_000_000)`

**Comment by ritchie46** [comment]
That we don't consolidate chunks by default is exprected. That we have such slow downs isn't. We should know where to rechunk internally. These problems have come to light lately now we don't rechunk by default anymore. Will fix it.

**Comment by ritchie46** [comment]
Got a fix. The single chunk case now also is much faster.
