### ISSUE TITLE
How to create fields dynamically in polars.

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1763]
Hi 

Is there any way to create fields dynamically?. I know there are some ways. But it will be better to know best approach in polars. For example I want to add 12 shifted columns to existing dataframe.(lag1, lag2, lag3...lagN) How to achieve this?

I also opened a question  in stackoverflow.

[https://stackoverflow.com/questions/69954438/how-to-create-fields-dynamically
](url)

Thanks.

**Comment by ritchie46** [comment]
Answered.
