### ISSUE TITLE
Plotting with different backend than bokeh

### ISSUE THREAD

**Issue by knolljo** [pola-rs/polars#17647]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import hvplot

hvplot.extension("plotly")   # Setting the backend
plt = pl.DataFrame({"x": [1, 2, 3], "y": [3, 2, 1]}).plot.bar()
hvplot.show(plt)
```

### Issue description

The integrated plotting is great! `hvplot` supports multiple backends, the default one is `bokeh`. I wanted to change this to `plotly` or `matplotlib`, but it didn't work. It seems that the default backend cannot be changed from the script, it is always `bokeh`.

### Expected behavior

I'd like to have the correct backend when set with `hvplot.extension`. 

Digging a little into the `DataFrame.plot` property, I found that when setting `hvplot.extension` after [`hvplot.post_patch()`](https://github.com/pola-rs/polars/blob/c6e1d9e85360dfa15de7612a27e8aaeb3e29fd74/py-polars/polars/dataframe/frame.py#L638) the correct backend was choosen, maybe this helps with a solution.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-6.6.35-x86_64-with-glibc2.39
Python:               3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 13.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.9.1
nest_asyncio:         <not installed>
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

can't reproduce though

![image](https://github.com/user-attachments/assets/06a79a2e-fd4c-455e-a49d-039cdbcf8133)

**Comment by knolljo** [comment]
Well thats interesting, I've tested it with jupyter==1.0.0, and it works too!
But when running it as a standalone script or in a marimo-notebook (where I originally tested it) it still uses bokeh.

**Comment by MarcoGorelli** [comment]
could you report to hvplot please? thanks 🙏
