### ISSUE TITLE
Systematic test for all `rechunk=False` regressions

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#17644]
### Description

How would one go about writing a test suite of every polars expression, timed on chunked vs rechunked data, to find any pathological cases? Otherwise they just get fixed as they come in one bug-report at a time.

**Comment by ritchie46** [comment]
I understand your sentiment, but this isn't trivial. Trust me, we have though about this.

The cases are often edge cases that occur at very specific combinations and only show at large dataset sizes (which doesn't fit in our test suite).

**Comment by deanm0000** [comment]
If you just wanted to do a one off test you could monkey patch the `__init__` method to make new dfs chunky.
