### ISSUE TITLE
Include example with function accepting multiple arguments in `Expr.map_batches`

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#17658]
### Description

It has come up a few times on SO, [here](https://stackoverflow.com/questions/75303038/how-to-write-poisson-cdf-as-python-polars-expression/75303247#75303247), [here](https://stackoverflow.com/questions/75364346/using-custom-function-with-multiple-parameters-and-partitioning-grouping-by-a-co/75364542#75364542) and [here](https://stackoverflow.com/questions/71658991/how-to-write-polars-custom-apply-function-that-does-the-processing-row-by-row/71679606#71679606).

It is also (from my understanding), the most performant way to use Numpy or Scipy functions that take multiple arguments and what calling a ufunc directly does under the hood.

### Link

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.map_batches.html

**Comment by deanm0000** [comment]
Sounds like a good idea. Just a clarification, when you use a ufunc with multiple arguments polars is converting all those arguments into a struct and calling `map_batches`. The thing that makes then universal is they check if any of their input arguments have the `__array_ufunc__` method. When they find that method, they defer their own execution and instead rim that method. `pl.Expr` has that method which converts the inputs to np arrays and runs the ufunc.

It's not that struct map_batches is some second best thing you have to settle for (from a performance perspective), that's how ufuncs work too.

https://numpy.org/doc/stable/user/basics.dispatch.html

**Comment by henryharbeck** [comment]
Thanks for that @deanm0000, I have seen you talk about this before (on the Discord, I think), but with this explanation I now fully understand it. Very much appreciated! 
Will tweak the issue description a bit to (hopefully) not give the wrong idea to anyone else reading it
