### ISSUE TITLE
Documentation issue in `normalize`/`name` parameter from `.value_counts()` method

### ISSUE THREAD

**Issue by diegoglozano** [pola-rs/polars#17660]
### Description

Small issue in the documentation (both expressions and series):
> if `normalize` is True defaults to "count", otherwise defaults to "proportion"

While it's the other way around.

Links to GH lines:
https://github.com/pola-rs/polars/blob/py-1.1.0/py-polars/polars/series/series.py#L2432
https://github.com/pola-rs/polars/blob/py-1.1.0/py-polars/polars/expr/expr.py#L9658

### Link

https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.value_counts.html

**Comment by MarcoGorelli** [comment]
thanks @diegoglozano , fancy making a PR to fix it?

**Comment by diegoglozano** [comment]
@MarcoGorelli sure! I'll try to do it today
