### ISSUE TITLE
write_database to snowflake with adbc engine spouts context canceled error log

### ISSUE THREAD

**Issue by Niivii** [pola-rs/polars#17666]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
with adbc_driver_snowflake.dbapi.connect(db_kwargs={
    "username": user,
    "adbc.snowflake.sql.account": host,
    "adbc.snowflake.sql.auth_type": "auth_ext_browser",
    "adbc.snowflake.sql.warehouse": warehouse,
    "adbc.snowflake.sql.role": role,
    "adbc.snowflake.sql.db": database,
    "adbc.snowflake.sql.schema": db_schema,
}) as connection:
    self.write_database(
        table_name=table,
        connection=connection,
        if_table_exists="replace",
        engine="adbc",
    )
```

### Log output

```shell
level=error msg="context canceled" func="gosnowflake.(*snowflakeConn).Close" file="connection.go:275" LOG_SESSION_ID=162217118069922
```

### Issue description

dataframe correctly writes to Snowflake but we get an error log

### Expected behavior

No error log

### Installed versions

<details>

```
1.1.0
```

</details>

**Comment by connelld-dpsk12** [comment]
any update? im getting the same thing

**Comment by Niivii** [comment]
Might be an upstream problem indeed. Let's see what adbc team thinks about it !

**Comment by Niivii** [comment]
Will be fixed upstream, closing:
https://github.com/snowflakedb/gosnowflake/pull/1196
https://github.com/snowflakedb/gosnowflake/issues/1186
