### ISSUE TITLE
polars.LazyFrame.head recommends using fetch()

### ISSUE THREAD

**Issue by Heiaha** [pola-rs/polars#17675]
### Description

```polars.LazyFrame.head``` still recommends using ```polars.LazyFrame.fetch```, even though fetch is deprecated.

### Link

https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.head.html

**Comment by Sherwin-14** [comment]
Hey can you give some more info about the issue?

**Comment by ntjess** [comment]
`fetch` is also still present as a dead link in [`LazyFrame.collect()`](https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.collect.html)
