### ISSUE TITLE
Conda package outdated

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#17719]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```

### Issue description

Conda package is still at 1.1.0

### Expected behavior

Conda package should be published within hours of a new release

### Installed versions

<details>

```
version
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report, there's a PR open at https://github.com/conda-forge/polars-feedstock/pull/248

> Conda package should be published within hours of a new release

May I suggest being a little more patient?😇

**Comment by pavelzw** [comment]
1.2.1 should come on conda-forge in the coming hours/latest tomorrow
