### ISSUE TITLE
[OS: Windows] Series.view() produces wrong output. Affects __ufuncs__

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#1773]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.10.19

#### What operating system are you using polars on?

Windows 10

#### Describe your bug.

Polar's `Series.abs()` does not return the expected output

#### What are the steps to reproduce the behavior?
```python
import polars as pl
s = pl.Series([1, -2, 3, -4])
s.abs()
```

#### What is the actual behavior?
```
shape: (4,)
Series: '' [i64]
[
	1
	0
	2
	1
]
```

#### What is the expected behavior?
```
shape: (4,)
Series: '' [i64]
[
	1
	2
	3
	4
]
```

**Comment by ritchie46** [comment]
Interesting. That implies that something goes wrong in the ufuncs. Does `series.sin` work for you?

**Comment by Arengard** [comment]
it works fine...

<img width="290" alt="Bildschirmfoto 2021-11-14 um 15 43 32" src="https://user-images.githubusercontent.com/52859991/141686004-1cca0688-d164-4fe3-a822-dd7b34988edf.png">

**Comment by ritchie46** [comment]
Hmm... which OS have you got @Arengard ?

**Comment by yuuuxt** [comment]
reproduced using win 10 x64, anaconda python 3.8 and polars 0.10.19:
![image](https://user-images.githubusercontent.com/3153534/141736541-f07e1c9b-ea32-4786-8cb6-752bec8ed4a3.png)

**Comment by ritchie46** [comment]
@yuuxt what does `s.view(ignore_nulls=True)` return in your case?

**Comment by yuuuxt** [comment]
> 
> 
> @yuuxt what does `s.view(ignore_nulls=True)` return in your case?

it is `array([ 1,  0, -2, -1])`

![image](https://user-images.githubusercontent.com/3153534/141740428-97ebf1f5-4959-42ba-94b9-ea8cccbf45fb.png)

**Comment by ritchie46** [comment]
> > @yuuxt what does `s.view(ignore_nulls=True)` return in your case?
> 
> it is `array([ 1, 0, -2, -1])`
> 
> ![image](https://user-images.githubusercontent.com/3153534/141740428-97ebf1f5-4959-42ba-94b9-ea8cccbf45fb.png)

Thanks a lot. Then we found the culprit.  I may ask again later.

**Comment by ritchie46** [comment]
Fixed and being released as we speak.
