### ISSUE TITLE
`write_excel`: write column formats for column, not individual cells within column

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#17756]
### Description

Right now, supplying a column format applies cell-level formatting to each individual cell within the column. It would be an improvement (in my opinion) to apply the formatting on a column level via `set_column`. This would then allow row formats to be applied via xlsxwriter, which they current are not because cell-level formats supercede row formats (which supercede column formats).

@alexander-beedie

**Comment by deanm0000** [comment]
Maybe change the parameter name and make a new one that uses set_column method
