### ISSUE TITLE
How to write a UDF for polars that run concurrently? 

### ISSUE THREAD

**Issue by langslike** [pola-rs/polars#17750]
I am writing a UDF with rust for polars, I want to know if polars will automatically run UDF concurrently or will I need to implement the concurrency myself in the rust code ? Example code is appreciated.

**Comment by alexander-beedie** [comment]
I'd suggest asking this question in our [Discord](https://discord.gg/4UfP5cfBE7), or (perhaps) on [StackOverflow](https://stackoverflow.com/questions/ask?tags=python-polars), as it isn't really an Issue (eg: a bug or feature request). 

We are lucky to have a helpful community, so I'm sure that if you ask a good question, you'll get a good answer. 
Thanks! 👍
