### ISSUE TITLE
Passing a `Series` to `DataFrame.sort` gives "literal expressions are not allowed for sorting" error

### ISSUE THREAD

**Issue by wesm** [pola-rs/polars#17769]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
s = pl.Series([3, 2, 1])
df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
    }
)
df.sort([s])
```

This yields

```
ComputeError: literal expressions are not allowed for sorting
```

### Log output

```shell
>>> import polars as pl
>>> s = pl.Series([3, 2, 1])
>>> df = pl.DataFrame(
...     {
...         "foo": [1, 2, 3],
...     }
... )
>>> df.sort([s])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wesm/miniforge3/envs/positron/lib/python3.11/site-packages/polars/dataframe/frame.py", line 4831, in sort
    self.lazy()
  File "/home/wesm/miniforge3/envs/positron/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1370, in sort
    self._ldf.sort_by_exprs(
polars.exceptions.ComputeError: literal expressions are not allowed for sorting
```
```


### Issue description

This worked in earlier versions of polars -- there doesn't seem to be reason why this should not work. The workaround is to create a DataFrame which the Series that you want to sort by as auxiliary columns (does this do redundant computation if you do not need to sort those columns?). 

### Expected behavior

In polars 0.20.x this worked as expected -- sorting by the passed Series values. 

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-6.9.9-200.fc40.x86_64-x86_64-with-glibc2.39
Python:               3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             3.1.3
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.6.3
pyiceberg:            <not installed>
sqlalchemy:           2.0.29
torch:                2.1.2+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by cmdlineluser** [comment]
I do recall it was disallowed as part of fixing: https://github.com/pola-rs/polars/issues/17539

Is it equivalent to `Expr.sort_by()`?

```python
df.select(pl.all().sort_by(s))
```

**Comment by wesm** [comment]
Thanks for the better workaround -- that's definitely more complex than `df.sort(by=[s])` but I can use that approach.

**Comment by ritchie46** [comment]
Yeah, we fixed an issue, but I think we are a bit to strict on this one. We can check on materialization if the length is as expected.
