### ISSUE TITLE
Where is indexing `__getitem__` (e.g. `df[...]`) documented for polars DataFrame and Series?

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#17772]
### Description

The [user guide](https://docs.pola.rs/) and [API reference](https://docs.pola.rs/api/python/stable/reference/index.html) don't mention anything about indexing. Yet we can still do things like `df[column_name]`. Are they just so discouraged that you don't want to mention these related usages at all, or am I missing something? As a comparison, numpy and pandas both have very detailed documentation on indexing.

I like the way polars does things in general and I prefer rigorous and explicitness. But sometimes I get frustrated when a simple `s[1::2]` (where `s` is a `pl.Series`) is what I need but I don't see the usage mentioned anywhere in the official doc, nor do I find any thing as convenient to achieve such functionality. For example, `pl.Series.slice` does something completely different yet with a "seemingly relevant" API name, while the right API is `gather_every` with a reverted arg order compared to the indexing/slicing convention, and a long function name.

Hence the question: are we just completely give up on the `[ ]` indexing, or are we plan to make indexing "better" (than the confusing pandas stuff), and to provide a comprehensive documentation in the future?

**Comment by liufeimath** [comment]
> Do you just feel we should document it more, or were you under the impression that this didn't work?

Things **mostly work** but for a good package like polars which values explicitness, I think we should clearly document the indexing APIs as they can easily lead to errors if not handled carefully. E.g. both `numpy` ([here](https://numpy.org/doc/stable/user/basics.indexing.html)) and `pandas` ([here](https://pandas.pydata.org/docs/user_guide/indexing.html)) spend numerous pages on what can or cannot be done. To continue deeper on this topic, one sell point of `polars` can be "our index is a lot simpler and less error prune than pandas as a result of the coherent design, we have the following 1 2 3 support for pl.DataFrame indexing and another 1 2 3 for pl.Series indexing blablabla". The key point is that we need to have a documentation, it can be a succinct one but there has to be one.

Let me give some examples below on why I think this is necessary:
```python
import numpy as np
import polars as pl

df = pl.from_numpy(np.random.rand(3, 2), schema=["a", "b"])

print(df)
# shape: (3, 2)
# ┌──────────┬──────────┐
# │ a        ┆ b        │
# │ ---      ┆ ---      │
# │ f64      ┆ f64      │
# ╞══════════╪══════════╡
# │ 0.825067 ┆ 0.34876  │
# │ 0.512424 ┆ 0.910972 │
# │ 0.842151 ┆ 0.75932  │
# └──────────┴──────────┘

print(df["a"])  # direct access by single column, returns a Series, good
# shape: (3,)
# Series: 'a' [f64]
# [
# 	0.825067
# 	0.512424
# 	0.842151
# ]

print(df[["a"]])  # bracket the col-name, now gives a n x 1 DataFrame, good
# shape: (3, 1)
# ┌──────────┐
# │ a        │
# │ ---      │
# │ f64      │
# ╞══════════╡
# │ 0.825067 │
# │ 0.512424 │
# │ 0.842151 │
# └──────────┘

print(df[0, "a"])  # direct access of an element
# 0.8250666396912938

print(df[0:2, ["a"]])  # slicing + column access
# shape: (2, 1)
# ┌──────────┐
# │ a        │
# │ ---      │
# │ f64      │
# ╞══════════╡
# │ 0.825067 │
# │ 0.512424 │
# └──────────┘

print(
    df[0, ["a"]]
)  # simple row element access... wait why is this a 1x1 (2D) instead of a 1D "plain row" ?
# shape: (1, 1)
# ┌──────────┐
# │ a        │
# │ ---      │
# │ f64      │
# ╞══════════╡
# │ 0.825067 │
# └──────────┘

print(
    df[[0], ["a"]]
)  # the output is the same as above but indexing syntax is different
# shape: (1, 1)
# ┌──────────┐
# │ a        │
# │ ---      │
# │ f64      │
# ╞══════════╡
# │ 0.825067 │
# └──────────┘

print(df[5, ["a"]])  # hmm, it allows out-of-bound row index
# shape: (0, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ f64 │
# ╞═════╡
# └─────┘

print(df[[5], ["a"]])  # let's try this. oops don't work
# OutOfBoundsError: gather indices are out of bounds

print(df[5])  # yet this works
# shape: (0, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ f64 ┆ f64 │
# ╞═════╪═════╡
# └─────┴─────┘

print(df[5, "a"])  # but not this
# IndexError: index 5 is out of bounds for sequence of length 3
```

These are just my toy trials which are not at all extensive. Given the complexity of the "indexing" topic itself, I think we must have one document. I expect it to be much more concise and elegant than the error-prune stuff in pandas, but again, the emphasize is that there has to be one.

**Comment by liufeimath** [comment]
Lacking documentation leaves the user (me) an impression that these syntax are "not recommended" (while in reality they can be very convenient in many use cases), then one has to find things like how to do the same with lengthy-word APIs like `gather_every` (which is not at all straightforward, and it doesn't make it "more explicit" than a simple `df[100:200:3]`, and also it doesn't support negative indexing like `df[-10::2]`). Indexing can be very **explicit** if we use them right. What we need is an **explicit** doc to educate users how to use them **explicitly**, like the other good polars APIs.

**Comment by mcrumiller** [comment]
+1 on this--while bracket notation is "not recommended" for finalized production, polars needs to have good support for exploratory command-line type analysis. Polars' expression syntax can sometimes be a little cumbsersome on the keys, and when you're just checking to see what your data looks like, it's nice to have the terser syntax available.

**Comment by cmdlineluser** [comment]
Just noticed that https://github.com/pola-rs/polars/pull/18309/ has added docs[^1][^2]

[^1]: https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.__getitem__.html#polars.DataFrame.__getitem__
[^2]: https://docs.pola.rs/api/python/dev/reference/series/api/polars.Series.__getitem__.html

**Comment by MarcoGorelli** [comment]
yup, thanks @cmdlineluser - I think this can be closed then

**Comment by liufeimath** [comment]
Super awesome! Many thanks for the work!
