### ISSUE TITLE
I got an error with RAM usage.

### ISSUE THREAD

**Issue by dazhwu** [pola-rs/polars#1777]
Hi,

I have two csv files. One (grant_grant.csv) has information about each patent. Another (grant_cite.csv) has information about which patent cited which patent. I read them to two data frames, grant and citation, respectively. Data frame "grant" has 5 million records, while "citation" has about 160 million records.

I want to join them similar to the following SQL:

SELECT citation.*, grant.*, grant_1.* FROM citation INNER JOIN grant ON citation.src = grant.patnum INNER JOIN grant grant_1 ON citation.dst=grant_1.patnum

Below is the code. A "memory allocation of 10353548800 bytes failed" error occurs when python was performing the first join. At the time RAM usage was above 99%. I also did the same thing using R.Data.Table (code attached at the end) and it took 3.6 minutes to finish it without error. In the whole running process with R.Data.Table, total RAM usage was below 70% (my computer's RAM has a capacity of 64 GB). So, what did I do wrong in the python code?

import datetime
import polars as pl
import time
from polars import *
from polars.lazy import *

start_time = time.time()

citation = pl.read_csv(
    "grant_cite.csv", ignore_errors=True, dtype={"src": pl.Int32, "dst": pl.Int32}
)

columns = [
    "patnum",
    "pubdate",
    "appnum",
    "appdate",
    "ipc",
    "city",
    "state",
    "country",
    "owner",
]

grant = pl.read_csv(
    "grant_grant.csv",
    columns=columns,
    ignore_errors=True,
    dtype={
        "patnum": pl.Int32,
        "pubdate": pl.Date,
        "appnum": pl.Int32,
        "appdate": pl.Date,
        "ipc": pl.Utf8,
        "city": pl.Utf8,
        "state": pl.Utf8,
        "country": pl.Utf8,
        "owner": pl.Utf8
    }
)

grant = grant.filter(col("pubdate") >= datetime.datetime.strptime("20020101", "%Y%m%d"))
new_columns = ["src_" + s for s in columns]
grant.columns = new_columns

########### error occurs at the following statement ##################
citation = citation.join(grant, left_on=["src"], right_on=["src_patnum"], how="inner")

new_columns = ["dst_" + s for s in columns]
grant.columns = new_columns

citation = citation.join(grant, left_on=["dst"], right_on=["dst_patnum"], how="inner")

citation.to_csv("citation_full.csv")

print("--- %s seconds ---" % (time.time() - start_time))

#########################################
library(data.table)
setDTthreads(8)

start_time = Sys.time()
citation=fread("grant_cite.csv")

cols=c("patnum", "pubdate", "appnum", "appdate","ipc", "city", "state", "country", "owner")
grant=fread("grant_grant.csv")[pubdate>='20020101', ..cols]

end_time=Sys.time()
end_time-start_time

src_cols=paste0("src_", cols)
setnames(grant, cols, src_cols)
setkeyv(grant, c("src_patnum"))
citation=merge(citation, grant, by.x="src", by.y="src_patnum")

dst_cols=paste0("dst_", cols)
setnames(grant, src_cols, dst_cols)
setkeyv(grant, c("dst_patnum"))

citation=merge(citation, grant, by.x="dst", by.y="dst_patnum" )

fwrite(citation, "citation_full_r.csv")

end_time=Sys.time()
end_time-start_time

**Comment by ritchie46** [comment]
Polars rechunks all memory after parsing csv. That requires free RAM. Try setting `rechunk=False`

To further reduce memory, use lazy. The optimizer skips rows snd columns that are not needed.

**Comment by ritchie46** [comment]
Ps, which version and OS do you run?

**Comment by dazhwu** [comment]
Thank you for your suggestion. I tried all of the three you suggested. I still got the same problem.

memory allocation of 10353548800 bytes failed
Process finished with exit code -1073740791 (0xC0000409)

> Polars rechunks all memory after parsing csv. That requires free RAM. Try setting `rechunk=False`
> 
> To further reduce memory, use lazy. The optimizer skips rows snd columns that are not needed.
> 
> Also reducing memory, is converting `Utf8` to `Categorical`.

**Comment by dazhwu** [comment]
The version of Polars is  0.10.19.

I am using Windows 11 with python 3.9.5. I also tried WSL (Windows Subsystems for Linux) and got error when joining two tables as follows:

Killed
Process finished with exit code 137 



> Ps, which version and OS do you run?

**Comment by ghuls** [comment]
@dazhwu How big are both CSV files?

```python
citation = pl.read_csv(
    "grant_cite.csv", ignore_errors=True, dtype={"src": pl.Int32, "dst": pl.Int32}
)

print("citation dataframe shape: ", citation.shape)

grant = pl.read_csv(
    "grant_grant.csv",
    columns=columns,
    ignore_errors=True,
    dtype={
        "patnum": pl.Int32,
        "pubdate": pl.Date,
        "appnum": pl.Int32,
        "appdate": pl.Date,
        "ipc": pl.Utf8,
        "city": pl.Utf8,
        "state": pl.Utf8,
        "country": pl.Utf8,
        "owner": pl.Utf8
    },
    new_columns = ["src_" + s for s in columns]
).with_columns([
    pl.col("src_ipc").cast(pl.Categorical),
    pl.col("src_city").cast(pl.Categorical),
    pl.col("src_state").cast(pl.Categorical),
    pl.col("src_country").cast(pl.Categorical),
    pl.col("src_owner").cast(pl.Categorical),
])

print("full grant dataframe shape: ", grant.shape)

grant = grant.filter(col("pubdate") >= datetime.datetime.strptime("20020101", "%Y%m%d"))

print("Grant dataframe shape after filtering: ", grant.shape)

# Try the join with only a few columns of the grant dataframe (add/remove till it fails).
citation = citation.join(
    grant.select([
           pl.col("src_patnum"),
            pl.col("src_pubdate"),
            pl.col("src_appnum"),
            pl.col("src_appdate"),
        ],
        left_on=["src"],
        right_on=["src_patnum"],
        how="inner"
)

print("Merged citation dataframe shape: ", citation.shape)
```

**Comment by dazhwu** [comment]
size：
grant_cite.csv  2.3 GB
grant_grant.csv   5.8 GB


I tried your code, and commented all columns in the last section except "src_patnum" which I cannot comment as it is involved in the join. And still cannot get through. Below is the output:

citation dataframe shape:  (161774202, 2)
full grant dataframe shape:  (4792398, 9)
Grant dataframe shape after filtering:  (4643285, 9)
memory allocation of 10353548800 bytes failed

Process finished with exit code -1073740791 (0xC0000409)



The last section is:

citation = citation.join(
    grant.select([
           pl.col("src_patnum")
            #pl.col("src_pubdate"),
            #pl.col("src_appnum"),
            #pl.col("src_appdate"),
        ]),
        left_on=["src"],
        right_on=["src_patnum"],
        how="inner"

)


> @dazhwu How big are both CSV files?
> 
> ```python
> citation = pl.read_csv(
>     "grant_cite.csv", ignore_errors=True, dtype={"src": pl.Int32, "dst": pl.Int32}
> )
> 
> print("citation dataframe shape: ", citation.shape)
> 
> columns = [
> "patnum",
> "pubdate",
> "appnum",
> "appdate",
> "ipc",
> "city",
> "state",
> "country",
> "owner",
> ]
> 
> grant = pl.read_csv(
>     "grant_grant.csv",
>     columns=columns,
>     ignore_errors=True,
>     dtype={
>         "patnum": pl.Int32,
>         "pubdate": pl.Date,
>         "appnum": pl.Int32,
>         "appdate": pl.Date,
>         "ipc": pl.Utf8,
>         "city": pl.Utf8,
>         "state": pl.Utf8,
>         "country": pl.Utf8,
>         "owner": pl.Utf8
>     },
>     new_columns = ["src_" + s for s in columns]
> ).with_columns([
>     pl.col("src_ipc").cast(pl.Categorical),
>     pl.col("src_city").cast(pl.Categorical),
>     pl.col("src_state").cast(pl.Categorical),
>     pl.col("src_country").cast(pl.Categorical),
>     pl.col("src_owner").cast(pl.Categorical),
> ])
> 
> print("full grant dataframe shape: ", grant.shape)
> 
> grant = grant.filter(col("pubdate") >= datetime.datetime.strptime("20020101", "%Y%m%d"))
> 
> print("Grant dataframe shape after filtering: ", grant.shape)
> 
> # Try the join with only a few columns of the grant dataframe (add/remove till it fails).
> citation = citation.join(
>     grant.select([
>            pl.col("src_patnum"),
>             pl.col("src_pubdate"),
>             pl.col("src_appnum"),
>             pl.col("src_appdate"),
>         ],
>         left_on=["src"],
>         right_on=["src_patnum"],
>         how="inner"
> )
> 
> print("Merged citation dataframe shape: ", citation.shape)
> ```

**Comment by ghuls** [comment]
Can you share the files?

**Comment by dazhwu** [comment]
I put the two csv files in a zip.

The link to the zip is 

https://liveudc-my.sharepoint.com/:u:/g/personal/dazhong_wu_udc_edu/ET5ufnp_ElNDvtMxpI0LUQABu_Zx-jgjfpf82VZ7sjkXVg?e=sTnGrg

Thanks,


> Can you try to limit the number of threads?
> 
> https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt/79614
> 
> ```
> # Linux/MacOS
> export POLARS_MAX_THREADS=1
> 
> # Windows (current terminal):
> set POLARS_MAX_THREADS=1
> 
> # Windows (global):
> setx POLARS_MAX_THREADS 1
> 
> python ...
> ```
> 
> Can you share the files?

**Comment by dazhwu** [comment]
I installed a Debian based distro, and entered the following commands:

export POLARS_MAX_THREADS=1
python3 Citation_Net.py

I got the same error message ("Killed") as in WSL.

**Comment by ghuls** [comment]
For the code above and with the provided files, I also ran out of memory on my laptop (after ipyton allocated 99G).

@dazhwu Your `grant_grant.csv` is a bit problematic:
  - It contains embedded comma's inside fields:
     - ipc
     - city
     - owner
     - title
     - abstract
  - It contains embedded newlines (at least in abstract).
  - Also pl.Date in `pl.read_csv(..., dtype=)` does not create a date (read_csv only supports basic dtypes, more advanced ones have to be casted too at a later stage. @ritchie46 read_csv rust code should give a warning when it detects unsupported dtypes.
  - @ritchie46 The embedded comma`s seem to mess up the parser when requesting specific columns in read_csv. Reading the full CSV file works. So probably the CSV file get split up at a wrong position when chunking it.

```python
# pl.read_csv(..., dtype={date: pl.Date} does not what you expect.

In [23]: pl.read_csv(b'date\n19760106\n', infer_schema_length=0, parse_dates=False)
Out[23]: 
shape: (1, 1)
┌──────────┐
│ date     │
│ ---      │
│ str      │
╞══════════╡
│ 19760106 │
└──────────┘

In [24]: pl.read_csv(b'date\n19760106\n', infer_schema_length=0, parse_dates=False, dtype={"date": pl.Date})
Out[24]: 
shape: (1, 1)
┌──────────────┐
│ date         │
│ ---          │
│ date         │
╞══════════════╡
│ +56071-05-02 │
└──────────────┘
```

```python
import polars as pl

# Read full grant CSV (with comma's inside fields and with embedded newlines) all as pl.Utf8.
grant_full_df = pl.read_csv(
    "grant_grant.csv",
    infer_schema_length=0,
    parse_dates=False,
)

# Write full grant dataframe as a TSV file.
grant_full_df.to_csv(
    'grant_grant.tsv',
    has_headers=True,
    sep='\t'
)
```

```python
columns = [
"patnum",
"pubdate",
"appnum",
"appdate",
"ipc",
"city",
"state",
"country",
"owner",
]

# Reading CSV file with embedded comma's and embedded newlines fails when specifying specific columns:
grant_csv = pl.read_csv(
    "grant_grant.csv",
    columns=columns,
    infer_schema_length=0,
    sep=',',
)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-107-6c500a77fe4f> in <module>
----> 1 grant_csv = pl.read_csv(
      2        "grant_grant.csv",
      3         columns=columns,
      4         infer_schema_length=0,
      5          parse_dates=False,
      6          sep=','

~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/io.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, columns, rechunk, encoding, n_threads, dtype, new_columns, use_pyarrow, low_memory, comment_char, quote_char, storage_options, null_values, parse_dates)
    369 
    370     with _prepare_file_arg(file, **storage_options) as data:
--> 371         df = pl.DataFrame.read_csv(
    372             file=data,
    373             infer_schema_length=infer_schema_length,

~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/eager/frame.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, columns, rechunk, encoding, n_threads, dtype, low_memory, comment_char, quote_char, null_values, parse_dates)
    459         processed_null_values = _process_null_values(null_values)
    460 
--> 461         self._df = PyDataFrame.read_csv(
    462             file,
    463             infer_schema_length,

RuntimeError: Any(ComputeError("invalid utf8 data in csv"))



# Reading TSV file with embedded comma's and embedded newlines works when specifying specific columns:
grant_tsv = pl.read_csv(
    "grant_grant.tsv",
    columns=columns,
    infer_schema_length=0,
    parse_dates=False,
    sep='\t',
)
```

Another issue is that you tried to convert some columns to Int32, which are not Int32 (like "src") (will convert some values to null).



```python
import polars as pl
import datetime

# Enable string cache (needed for Catergorical if they are in different dataframes).
pl.toggle_string_cache(True)

citation = pl.read_csv(
    "grant_cite.csv",
     infer_schema_length=0,
     parse_dates=False,
).with_columns([
    pl.col("src").cast(pl.Categorical),
    pl.col("dst").cast(pl.Categorical),
])

print("citation dataframe shape: ", citation.shape)

columns = [
"patnum",
"pubdate",
"appnum",
"appdate",
"ipc",
"city",
"state",
"country",
"owner",
]

# Read needed columns from TSV version of grant_grant.tsv as Utf8 and convert to the wanted datatype afterwards.
grant = pl.read_csv(
    "grant_grant.tsv",
    columns=columns,
    infer_schema_length=0,
    parse_dates=False,
    sep='\t',
    new_columns = ["src_" + s for s in columns]
).with_columns([
    pl.col("src_patnum").cast(pl.Categorical),
    pl.col("src_pubdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_appnum").cast(pl.Categorical),
    pl.col("src_appdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_ipc").cast(pl.Categorical),
    pl.col("src_city").cast(pl.Categorical),
    pl.col("src_state").cast(pl.Categorical),
    pl.col("src_country").cast(pl.Categorical),
    pl.col("src_owner").cast(pl.Categorical),
])

print("Grant dataframe shape after filtering: ", grant.shape)

grant = grant.filter(pl.col("src_pubdate") > pl.lit(datetime.datetime(2002, 1, 1)))

print("Grant dataframe shape after filtering: ", grant.shape)

# Try the join with only a few columns of the grant dataframe (add/remove till it fails).
citation_merged = citation.join(
    grant.select(
        [
           pl.col("src_patnum"),
            pl.col("src_pubdate"),
            pl.col("src_appnum"),
            pl.col("src_appdate"),
        ],
    ),
    left_on=["src"],
    right_on=["src_patnum"],
    how="inner"
)

print("Merged citation dataframe shape: ", citation_merged.shape)
```

It seems to fit in less than 20G of RAM (maybe even 15G, as I might still have had some trials in memory).
```
citation dataframe shape:  (161774202, 2)
Grant dataframe shape after filtering:  (7616434, 9)
Grant dataframe shape after filtering:  (4993850, 9)
Merged citation dataframe shape:  (139993798, 10)
```

**Comment by dazhwu** [comment]
Great! I added a second join as in my original post. It took in total 146 seconds compared with 210 seconds using R.Data.Table. Finally, there is one that is faster than data.table.

Thank you so much for the help.

**Comment by ritchie46** [comment]
> Finally, there is one that is faster than data.table.

Yeah buddy! :100:

**Comment by ritchie46** [comment]
> Also pl.Date in pl.read_csv(..., dtype=) does not create a date (read_csv only supports basic dtypes, more advanced ones have to be casted too at a later stage. @ritchie46 read_csv rust code should give a warning when it detects unsupported dtypes.

Hmm.. This is something we should fix. I think we can just do the casting implicitly.

> @ritchie46 The embedded comma`s seem to mess up the parser when requesting specific columns in read_csv. Reading the full CSV file works. So probably the CSV file get split up at a wrong position when chunking it.

So the projection did not work? Can we isolate this in an MWE? Then I hope we can make this work.

@ghuls what do you think, did the fact that originally joining on data with nulls exploded the memory? 

```python
dfa = pl.DataFrame({"a": [None, None, None]})
dfb = pl.DataFrame({"a": [None, None, None]})

assert dfa.join(dfb, on="a").height == 9
```

**Comment by ghuls** [comment]
> So the projection did not work? Can we isolate this in an MWE? Then I hope we can make this work.
I think it is mainly the field splitting (due to embedded comma's/newlines) that does not work correctly with projection. Which then generated garbage for some columns (`ignrore_errors=True`).

**Comment by ghuls** [comment]
```bash
# Create smaller CSV file (till at least 3797000 first lines didn't generate a parsing error (still might parse wrong).
head -n 3798000 grant_grant.csv > grant_grant.head3798000.csv

# Get header.
head -n 1 grant_grant.head3798000.csv > grant_grant.head3798000_tail100.csv

# Append last 100 lines.
tail -n 100 grant_grant.head3798000.csv >> grant_grant.head3798000_tail100.csv

# Change separators from comma's to TABs.
xsv fmt -t '\t' grant_grant.head3798000_tail100.csv > grant_grant.head3798000_tail100.tsv
```

Number of rows according to xsv count:
```bash
❯ xsv count grant_grant.head3798000_tail100.csv
96

❯ xsv count grant_grant.head3798000_tail100.tsv
96
```


```python
import polars as pl

columns = [
"patnum",
"pubdate",
"appnum",
"appdate",
"ipc",
"city",
"state",
"country",
"owner",
]

# Read needed columns from CSV.
grant_csv = pl.read_csv(
    "grant_grant.head3798000_tail100.csv",
    columns=columns,
    infer_schema_length=0,
    parse_dates=False,
    sep=',',
    new_columns = ["src_" + s for s in columns]
).with_columns([
    pl.col("src_patnum").cast(pl.Categorical),
    pl.col("src_pubdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_appnum").cast(pl.Categorical),
    pl.col("src_appdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_ipc").cast(pl.Categorical),
    pl.col("src_city").cast(pl.Categorical),
    pl.col("src_state").cast(pl.Categorical),
    pl.col("src_country").cast(pl.Categorical),
    pl.col("src_owner").cast(pl.Categorical),
])

print("Grant dataframe shape CSV: ", grant_csv.shape)

# Read needed columns from TSV.
grant_tsv = pl.read_csv(
    "grant_grant.head3798000_tail100.tsv",
    columns=columns,
    infer_schema_length=0,
    parse_dates=False,
    sep='\t',
    new_columns = ["src_" + s for s in columns]
).with_columns([
    pl.col("src_patnum").cast(pl.Categorical),
    pl.col("src_pubdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_appnum").cast(pl.Categorical),
    pl.col("src_appdate").str.strptime(pl.Date, "%Y%m%d"),
    pl.col("src_ipc").cast(pl.Categorical),
    pl.col("src_city").cast(pl.Categorical),
    pl.col("src_state").cast(pl.Categorical),
    pl.col("src_country").cast(pl.Categorical),
    pl.col("src_owner").cast(pl.Categorical),
])

print("Grant dataframe shape TSV: ", grant_tsv.shape)

```

```
In [67]: print("Grant dataframe shape CSV: ", grant_csv.shape)
Grant dataframe shape CSV:  (9, 9)

In [68]: print("Grant dataframe shape TSV: ", grant_tsv.shape)
Grant dataframe shape TSV:  (96, 9)


# CSV parsing goes wrong:
In [69]: grant_csv.head(5)
Out[69]: 
shape: (5, 9)
┌─────────────┬────────────┬────────────┬────────────┬─────┬────────────┬──────┬──────┬────────────┐
│ src_patnum  ┆ src_pubdat ┆ src_appnum ┆ src_appdat ┆ ... ┆ src_city   ┆ src_ ┆ src_ ┆ src_owner  │
│ ---         ┆ e          ┆ ---        ┆ e          ┆     ┆ ---        ┆ stat ┆ coun ┆ ---        │
│ cat         ┆ ---        ┆ cat        ┆ ---        ┆     ┆ cat        ┆ e    ┆ try  ┆ cat        │
│             ┆ date       ┆            ┆ date       ┆     ┆            ┆ ---  ┆ ---  ┆            │
│             ┆            ┆            ┆            ┆     ┆            ┆ cat  ┆ cat  ┆            │
╞═════════════╪════════════╪════════════╪════════════╪═════╪════════════╪══════╪══════╪════════════╡
│ "7375446"   ┆ 2008-05-20 ┆ "11135404" ┆ 2005-05-24 ┆ ... ┆ "kitasaku- ┆ ""   ┆ "jp" ┆ "minebea   │
│             ┆            ┆            ┆            ┆     ┆ gun,       ┆      ┆      ┆ co., ltd." │
│             ┆            ┆            ┆            ┆     ┆ nagano"    ┆      ┆      ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "to provide ┆ null       ┆ null       ┆ null       ┆ ... ┆ null       ┆ null ┆ null ┆ null       │
│ a surface   ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
│ acoustic    ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
│ w...        ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "[means to  ┆ null       ┆ null       ┆ null       ┆ ... ┆ null       ┆ null ┆ null ┆ null       │
│ solve the   ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
│ problems] " ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "the        ┆ null       ┆ " interdig ┆ null       ┆ ... ┆ "ipgb20080 ┆ null ┆ null ┆ null       │
│ surface     ┆            ┆ ital trans ┆            ┆     ┆ 520.xml"   ┆      ┆      ┆            │
│ acoustic    ┆            ┆ ducers  11 ┆            ┆     ┆            ┆      ┆      ┆            │
│ wave        ┆            ┆ ...        ┆            ┆     ┆            ┆      ┆      ┆            │
│ excit...    ┆            ┆            ┆            ┆     ┆            ┆      ┆      ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "l"         ┆ null       ┆ null       ┆ null       ┆ ... ┆ null       ┆ null ┆ null ┆ null       │
└─────────────┴────────────┴────────────┴────────────┴─────┴────────────┴──────┴──────┴────────────┘

In [70]: grant_tsv.head(5)
Out[70]: 
shape: (5, 9)
┌─────────────┬─────────────┬─────────────┬────────────┬─────┬────────────┬────┬──────┬────────────┐
│ src_patnum  ┆ src_pubdate ┆ src_appnum  ┆ src_appdat ┆ ... ┆ src_city   ┆ sr ┆ src_ ┆ src_owner  │
│ ---         ┆ ---         ┆ ---         ┆ e          ┆     ┆ ---        ┆ c_ ┆ coun ┆ ---        │
│ cat         ┆ date        ┆ cat         ┆ ---        ┆     ┆ cat        ┆ st ┆ try  ┆ cat        │
│             ┆             ┆             ┆ date       ┆     ┆            ┆ at ┆ ---  ┆            │
│             ┆             ┆             ┆            ┆     ┆            ┆ e  ┆ cat  ┆            │
│             ┆             ┆             ┆            ┆     ┆            ┆ -- ┆      ┆            │
│             ┆             ┆             ┆            ┆     ┆            ┆ -  ┆      ┆            │
│             ┆             ┆             ┆            ┆     ┆            ┆ ca ┆      ┆            │
│             ┆             ┆             ┆            ┆     ┆            ┆ t  ┆      ┆            │
╞═════════════╪═════════════╪═════════════╪════════════╪═════╪════════════╪════╪══════╪════════════╡
│ "7375446"   ┆ 2008-05-20  ┆ "11135404"  ┆ 2005-05-24 ┆ ... ┆ "kitasaku- ┆ "" ┆ "jp" ┆ "minebea   │
│             ┆             ┆             ┆            ┆     ┆ gun,       ┆    ┆      ┆ co., ltd." │
│             ┆             ┆             ┆            ┆     ┆ nagano"    ┆    ┆      ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "7375447"   ┆ 2008-05-20  ┆ "11073758"  ┆ 2005-03-08 ┆ ... ┆ "tokyo"    ┆ "" ┆ "jp" ┆ "hitachi   │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ koki co.,  │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ ltd."      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "7375448"   ┆ 2008-05-20  ┆ "11784467"  ┆ 2007-04-05 ┆ ... ┆ "incheon"  ┆ "" ┆ "kr" ┆ "g & w tec │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ hnologies, │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ inc."      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "7375449"   ┆ 2008-05-20  ┆ "11506636"  ┆ 2006-08-17 ┆ ... ┆ ""         ┆ "" ┆ ""   ┆ ""         │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "7375450"   ┆ 2008-05-20  ┆ "11137236"  ┆ 2005-05-25 ┆ ... ┆ "osaka"    ┆ "" ┆ "jp" ┆ "sanyo     │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ electric   │
│             ┆             ┆             ┆            ┆     ┆            ┆    ┆      ┆ co., ltd." │
└─────────────┴─────────────┴─────────────┴────────────┴─────┴────────────┴────┴──────┴────────────┘
```
[grant_grant.head3798000_tail100.zip](https://github.com/pola-rs/polars/files/7553716/grant_grant.head3798000_tail100.zip)

**Comment by ritchie46** [comment]
I think all issues are fixed now.
