### ISSUE TITLE
double select on lazyframe has performance regression

### ISSUE THREAD

**Issue by implicit-apparatus** [pola-rs/polars#17781]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os 
os.environ["POLARS_MAX_THREADS"] = "1"
import polars as pl
import numpy as np
import time
print("polars version:", pl.__version__)
print("thread pool size:", pl.thread_pool_size())

sample_size = 1e6
frame1 = pl.DataFrame(
    dict(
        index=np.arange(int(sample_size)),
        data1=np.random.randn(int(sample_size)),
        data2=np.random.randn(int(sample_size)),
    )
)
frame2 = pl.DataFrame(
    dict(
        index=np.arange(int(sample_size)),
        label1=np.random.randint(0, 2, int(sample_size)),
        label2=np.random.randint(0, 2, int(sample_size)),
        label3=np.random.randint(0, 2, int(sample_size)),
    ),
    schema=[
        ("index", pl.Int64),
        ("label1", pl.Boolean),
        ("label2", pl.Boolean),
        ("label3", pl.Boolean),
    ],
)
frame1.write_parquet("data.parquet")
frame2.write_parquet("label.parquet")

cols =  ['index', 'data1', 'label1', 'label2']

start = time.perf_counter()
lf = None
for file in ["data.parquet", "label.parquet"]:
    lfj = pl.scan_parquet(file).set_sorted("index")
    use_columns = [c for c in cols if c in lfj.collect_schema().names()]
    #lfj = lfj.select(use_columns)

    if lf is None:
        lf = lfj
    else:
        lf = lf.join(lfj,on="index", how="left")
print("single select works as expected")
print(lf.select(cols).collect().shape,"collecting takes", time.perf_counter()-start)


start = time.perf_counter()
lf = None
for file in ["data.parquet", "label.parquet"]:
    lfj = pl.scan_parquet(file).set_sorted("index")
    use_columns = [c for c in cols if c in lfj.collect_schema().names()]
    lfj = lfj.select(use_columns)
    lfj = lfj.select(use_columns)
    #lfj = lfj.drop()

    if lf is None:
        lf = lfj
    else:
        lf = lf.join(lfj,on="index", how="left")
print("double select works is slower")
print(lf.select(cols).collect().shape,"collecting takes", time.perf_counter()-start)


```

### Log output

```shell
polars version: 1.2.1
thread pool size: 1
single select works as expected
(1000000, 4) collecting takes 0.07622749102301896
double select works is slower
(1000000, 4) collecting takes 0.20397022896213457
```

### Issue description

When selecting columns before a join, selecting the same columns twice or dropping with an empty argument, does lead to an unexpected performance drop of the join. Some context why one would do that: in our code there is also a rename between the two select statements and the first select was to only select the columns needed later in the code and the second select was to make sure that columns that are in both data frames are dropped in the second frame before joining.

### Expected behavior

A empty drop or select with the same columns as the first select does not degrade the performance. 
In an older version of polars (0.19.7) this code worked as expected.

### Installed versions

<details>

--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-5.15.0-116-generic-x86_64-with-glibc2.35
Python:               3.9.19 (main, Mar 21 2024, 17:11:28) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.6.3
nest_asyncio:         1.6.0
numpy:                1.21.6
openpyxl:             3.0.10
pandas:               1.3.0
pyarrow:              15.0.2
pydantic:             2.7.1
pyiceberg:            <not installed>
sqlalchemy:           1.4.29
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.0.9

</details>

**Comment by ritchie46** [comment]
Found the culprit. Will fix it.
