### ISSUE TITLE
Join documentation is misleading or wrong.

### ISSUE THREAD

**Issue by implicit-apparatus** [pola-rs/polars#17782]
### Description

The description of 'semi' listed here: 
https://docs.pola.rs/user-guide/transformations/joins/
> semi: Returns all rows from the left frame in which the join key is also present in the right frame.

is much better than the description in the api reference:
https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join.html#polars.DataFrame.join
> semi: Filter rows that have a match in the right table.

At least I did not understand from the description reference documentation that only the left frame is taken and which rows are dropped and which rows are used (I expected the opposite). Same for 'anti'.

**Comment by ritchie46** [comment]
Misleading... :roll_eyes: 

Sure they can be improved. Do you want to make a PR?
