### ISSUE TITLE
Request for Inequality operator to handle Null values as-well

### ISSUE THREAD

**Issue by ahmadsaadat** [pola-rs/polars#17794]
### Description

Imagine we want to use the != operator to find everything but "Y"

        {
            "ID": ["1", "2", "3"],
            "FLG": ["Y", None, "N"],
        }
    
If you were to filter the above using .ne("Y") this would only yield you ID=3 "N".

        {
            "ID": ["3"],
            "FLG": ["N"],
        }
    
The problem is that ID=2 "None" has been left out, even though it is also not equal to "Y".

I was wondering if we could have an additional parameter or builder on top of .ne() to include Null values in the method expression as-well. For now I am resolving it using:

df.filter(pl.col("FLG").is_null() | pl.col("FLG").ne("Y"))

**Comment by cmdlineluser** [comment]
I think there is recent issue about improving the filter docs for these examples.

There are dedicated `*_missing()` functions[^1]

```python
>>> df.filter(pl.col("FLG").ne_missing("Y"))
shape: (2, 2)
┌─────┬──────┐
│ ID  ┆ FLG  │
│ --- ┆ ---  │
│ str ┆ str  │
╞═════╪══════╡
│ 2   ┆ null │
│ 3   ┆ N    │
└─────┴──────┘
```

[^1]: https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ne_missing.html#polars.Expr.ne_missing

**Comment by ahmadsaadat** [comment]
This works, thank you very much. 

Going to request update to your ne_missing() documentation.

**Comment by ahmadsaadat** [comment]
This works, thank you very much.

Going to request update to your ne_missing() documentation.

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/pull/17755 is where the filter docs are being worked on.

Perhaps they could also add a mention of `eq_missing` / `ne_missing`
