### ISSUE TITLE
Append scalar column to list column

### ISSUE THREAD

**Issue by matt035343** [pola-rs/polars#17808]
### Description

It would be cool to have the following feature:
```python
pl.DataFrame({'A': [4,5,6], 'B': [[1], [2], [3]]}) .select(col('B').list.append(col('A')))
```
which would result in:

```python
pl.DataFrame({'B': [[1,4], [2,5], [3,6]]})
```

Right now, my workaround is something like:
```python
pl.DataFrame({'A': [4,5,6], 'B': [[1], [2], [3]]}) .select(col('B').list.conat(col('A').map_elements(np.array)))
```

I believe native support would probably be more efficient.

**Comment by cmdlineluser** [comment]
It does exist, but is named `.list.concat()`

**Comment by matt035343** [comment]
@cmdlineluser My bad, I was not aware concat also accepts scalar values. Thank you!
