### ISSUE TITLE
"limit" optimisation not applied to LazyFrame 'scan_xyz' methods, and 'stop_after_n_rows' seems to be a no-op for scan_parquet/scan_ipc

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#1780]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.19

#### What operating system are you using polars on?

Windows 10, macOS

#### Describe your bug.

Application of 'limit' (or 'head') to a LazyFrame does not seem to propagate into the 'scan_xyz' methods for any of the various file formats (parquet, csv, ipc), This results in the entire dataset being read unnecessarily _before_ the limit is applied.

Additionally, in the case of 'scan_ipc' and 'scan_parquet', the 'stop_after_n_rows' param does not seem to work at all (it does work for csv files though, where I am using that as a temporary workaround for 'limit' not being applied).

#### What are the steps to reproduce the behavior?

```python
from codetiming import Timer  # (or equivalent module ;)
import polars as pl

## -------------------------------------------------------------------------------
## create frame of reasonable size and export
## -------------------------------------------------------------------------------
pf = pl.DataFrame(
    columns=[ 'x', 'y' ],
    data=[ [ 'abc' ] * 50_000_000,
           [ 12345 ] * 50_000_000 ]
)

f_csv = 'data.csv'
f_ipc = 'data.ipc'
f_pqt = 'data.parquet'

pf.to_csv( f_csv )
pf.to_ipc( f_ipc )
pf.to_parquet( f_pqt )

## -------------------------------------------------------------------------------
## demonstrate that 'limit' does not propagate for csv
## -------------------------------------------------------------------------------
with Timer( 'no limit' ):
    res = pl.scan_csv( f_csv ).collect()
with Timer( 'limit = 1' ):
    res = pl.scan_csv( f_csv ).limit( 1 ).collect()    
with Timer( 'stop_after_n_rows = 1' ):
    res = pl.scan_csv( f_csv,stop_after_n_rows=1 ).collect()

# Elapsed time: 1.4000 seconds (no limit)
# Elapsed time: 1.3991 seconds (limit = 1)
# Elapsed time: 0.0725 seconds (stop_after_n_rows = 1)

## ------------------------------------------------------------------------------
## demonstrate that neither 'limit' nor 'stop_after_n_rows' work for parquet/ipc
## ------------------------------------------------------------------------------
with Timer( 'no limit' ):
    res = pl.scan_parquet( f_pqt ).collect()
with Timer( 'limit = 1' ):
    res = pl.scan_parquet( f_pqt ).limit( 1 ).collect()    
with Timer( 'stop_after_n_rows = 1' ):
    res = pl.scan_parquet( f_pqt,stop_after_n_rows=1 ).collect()
   
# Elapsed time: 1.0975 seconds (no limit)
# Elapsed time: 1.0699 seconds (limit = 1)
# Elapsed time: 1.0739 seconds (stop_after_n_rows = 1)

with Timer( 'no limit' ):
    res = pl.scan_ipc( f_ipc ).collect()
with Timer( 'limit = 1' ):
    res = pl.scan_ipc( f_ipc ).limit( 1 ).collect()    
with Timer( 'stop_after_n_rows = 1' ):
    res = pl.scan_ipc( f_ipc,stop_after_n_rows=1 ).collect()
    
# Elapsed time: 0.4953 seconds (no limit)
# Elapsed time: 0.4305 seconds (limit = 1)
# Elapsed time: 0.4329 seconds (stop_after_n_rows = 1)
```

#### What is the actual behavior?

The 'limit' param is not propagated into the LazyFrame scan/load code for any format (csv/parquet/ipc).
The 'stop_after_n_rows' param only seems to work for csv files, but not for parquet/ipc.

#### What is the expected behavior?

Use of the 'limit' param (and/or the 'stop_after_n_rows' param) should result in only the first 'n' rows being loaded, instead of loading the entire dataset and _then_ applying a limit.

Thanks!

**Comment by ritchie46** [comment]
For the `limit` this is correct. I cannot estimate how many rows remain after filtering. So the limit is not pushed down. For this we have a `fetch` (instead of `collect`), a fetch is pushed down to the scan, but may yield even less rows then required due to later predicate filtering.

`stop_after_n_rows`, is known. Its on the todo list. :)

**Comment by alexander-beedie** [comment]
> stop_after_n_rows, is known. Its on the todo list. :)

Great, I'll keep an eye out for it - thanks!

In the case where there is _no_ filtering though (as above), and limit is the first (or even only) operation applied, wouldn't this be effectively identical to applying 'stop_after_n_rows'? (At least as a special-case, with no filtering/etc). I can handle this myself locally, so certainly not the end of the world if it isn't as straightforward as that under-the-hood ;)

**Comment by ghuls** [comment]
@ritchie46 The same might be happening for `pl.read_ipc`, and `pl.read_parquet`(at least if there is only one record batch in the file). I assume if you have multiple record batches it will stop reading the files earlier (once you have read enough record batches so n_rows >= stop_after_n_rows) , but didn't check it yet (don't have files with multiple record batches.

**Comment by ritchie46** [comment]
> @ritchie46 The same might be happening for `pl.read_ipc`, and `pl.read_parquet`(at least if there is only one record batch in the file). I assume if you have multiple record batches it will stop reading the files earlier (once you have read enough record batches so n_rows >= stop_after_n_rows) , but didn't check it yet (don't have files with multiple record batches).

Indeed, that's the culprit. I already knew this. I have to discuss with @jorgecarleitao, if we can control the number of recordbatches read/ iterated over.

**Comment by ritchie46** [comment]
The slices are now being pushed down. There is still however the case that we cannot read less than an entire row group before applying a slice in `parquet` and `ipc` so for those types it has less of an effect that on `csv` files.
