### ISSUE TITLE
Rename: Support for ignore_missing parameter

### ISSUE THREAD

**Issue by raayu83** [pola-rs/polars#17821]
### Description

For people who work with column name mappings it would be very useful if there was an option to ignore missing columns on df.rename().

Currently the following fails because some columns in mappings don't exist in the DataFrame:
```
import polars as pl

mappings = {
    'Hello': 'hello',
    'Goodbye': 'goodbye'
}

df = pl.DataFrame({'Hello': 'World'}).rename(mappings)

```

Currently you first have to manually remove columns that don't exist in the df from the mappings.

For such usecases, it would be much nicer if there was an `ignore_missing` Parameter to rename, which defaults to `False` (mirroring the current behaviour).

**Comment by etiennebacher** [comment]
No idea if they want to implement this, but if so it should probably be named `strict` (default to `True`) as for `.drop()` (https://github.com/pola-rs/polars/pull/17044).

**Comment by nameexhaustion** [comment]
https://github.com/pola-rs/polars/pull/19017
