### ISSUE TITLE
`pl.col(col).last()` example shows both "max" and "last" behaviour

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#17826]
### Description

The `pl.col(col).last()` example shows both "max" and "last" behaviour. In some tools (e.g., Power BI DAX), `LAST()` actually means "max non-null value" (which is insane). It would be helpful to show an example where the values are `[1, 3, 2]`, and show that `.last()` gets `2` (the final value in the list, as ordered at runtime), instead of the maximum value. 

### Link

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.last.html#polars.Expr.last

**Comment by orlp** [comment]
Feel free to make a pull request to update the docs.

The same also needs to be done to `polars.Expr.arr.last` and `polars.LazyFrame.last` from a quick scan.
