### ISSUE TITLE
Add  `mask` operations on `Expr`

### ISSUE THREAD

**Issue by Oreilles** [pola-rs/polars#17838]
### Description

It would be nice if Polars provided an equivalent to Panda's [`mask`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mask.html) operations for `Expr`.

`mask` is syntactic sugar for a common replacement pattern:

```py
pl.when(condition).then(old_expr).otherwise(new_expr)
==
old_expr.mask(condition, new_expr)
```

```py
pl.when(condition).then(expr)
==
expr.mask(condition)
```

**Comment by deanm0000** [comment]
This is probably too close to when/then/otherwise or replace/replace_strict for it to be a new feature. I'm not the decider but that's my take.

**Comment by orlp** [comment]
We've decided that we don't want this. We generally prefer to only have a single way of doing things, and `expr.mask(condition)` is unclear in whether the `True` values or `False` values are being masked out.
