### ISSUE TITLE
`write_excel(..., autofit=True)` auto-fits to source, not formatted data

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#17853]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "Text": ["Hi there", "longer sentence", "this is left aligned"],
    "Number": [1.0, 2.345, 0.398374937341998375913758438431441],
})

df.write_excel("out.xlsx", autofit=True)
```
![image](https://github.com/user-attachments/assets/d079c4b2-8f71-46c4-b0fa-7c349735c1ac)

### Issue description

When using `autofit`, it appears the column width is calculated from the original number, not from the formatted result. In the example above, the column width is as it would be had we kept many decimals in the output format, and as a result, we have unused whitespace.

### Expected behavior

Should fit to truncated, output-formatted decimal.

### Installed versions

main

**Comment by alexander-beedie** [comment]
FYI: the behaviour of `autofit` is an XlsxWriter feature rather than a Polars feature - if passed, we just call "worksheet.autofit()"  ;)
