### ISSUE TITLE
`unnest()` should have option to rename fields with separator

### ISSUE THREAD

**Issue by uditrana** [pola-rs/polars#17856]
### Description

Polars has become a pretty powerful tool at normalizing JSON into dataframes with `json_decode` and `unnest`. 

That said, here is a common workflow that is quite annoying right now:
```python
>>> df = pl.DataFrame(
    {
        "id": [1, 2],
        "response": [{"id": 1, "data": "foofoo"}, {"id": 2, "data": "barbar"}],
    }
)
>>> print(df)
shape: (2, 2)
┌─────┬──────────────┐
│ id  ┆ response     │
│ --- ┆ ---          │
│ i64 ┆ struct[2]    │
╞═════╪══════════════╡
│ 1   ┆ {1,"foofoo"} │
│ 2   ┆ {2,"barbar"} │
└─────┴──────────────┘
>>> df.unnest("response")
DuplicateError: column with name 'id' has more than one occurrences
```

My current workaround to achieve the desired response is:
```python
>>> print(df.with_columns(pl.col("response").struct.rename_fields([f"response.{field}" for field in df['response'].struct.fields])).unnest("response"))
shape: (2, 3)
┌─────┬─────────────┬───────────────┐
│ id  ┆ response.id ┆ response.data │
│ --- ┆ ---         ┆ ---           │
│ i64 ┆ i64         ┆ str           │
╞═════╪═════════════╪═══════════════╡
│ 1   ┆ 1           ┆ foofoo        │
│ 2   ┆ 2           ┆ barbar        │
└─────┴─────────────┴───────────────┘
```

Ideally the syntax would be as simple as `df.unnest("response", separator=".")`. Separator being passed in could indicate that we want the "nested" column names. Fwiw, this aligns the behavior with `json_normalize` as well.

**Comment by cmdlineluser** [comment]
[`.name.prefix_fields()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.name.prefix_fields.html)[^1] has since been added which is a bit easier.

```python
(df.with_columns(pl.col("response").name.prefix_fields("response."))
   .unnest("response")
)

# shape: (2, 3)
# ┌─────┬─────────────┬───────────────┐
# │ id  ┆ response.id ┆ response.data │
# │ --- ┆ ---         ┆ ---           │
# │ i64 ┆ i64         ┆ str           │
# ╞═════╪═════════════╪═══════════════╡
# │ 1   ┆ 1           ┆ foofoo        │
# │ 2   ┆ 2           ┆ barbar        │
# └─────┴─────────────┴───────────────┘
```

But as `prefix=` is required, it may be a bit repetitive:

```python
pl.col("a").name.prefix_fields("a.")
pl.col("b").name.prefix_fields("b.")
pl.col("c").name.prefix_fields("c.")
```

Not sure if it could allow it to be optional and use the root name with a default separator instead, meaning it could be used by multi-col selectors: pl.col(a, b) / pl.exclude, etc.
```python
pl.col("a", "b", "c").name.prefix_fields(prefix=None, separator=".")
```

[^1]: https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.name.prefix_fields.html

**Comment by deanm0000** [comment]
I'm positive this has been asked for before but now I can't find the previous issues.

**Comment by deanm0000** [comment]
I'm going to close this one as a duplicate.

**Comment by uditrana** [comment]
Thanks for finding those issues. I expected there to be an issue but was really struggling to find them for some reason
