### ISSUE TITLE
Wrong (probably Typo) word in the output

### ISSUE THREAD

**Issue by sudipto80** [pola-rs/polars#17854]
### Description

join 

For the following code, the last row's output should have 'NAN' for the column d instead of null

```rust
use rand::Rng;
let mut rng = rand::thread_rng();

let df: DataFrame = df!(
    "a" => 0..8,
    "b"=> (0..8).map(|_| rng.gen::<f64>()).collect::<Vec<f64>>(),
    "d"=> [Some(1.0), Some(2.0), None, None, Some(0.0), Some(-5.0), Some(-42.), None]
)
.unwrap();
let df2: DataFrame = df!(
    "x" => 0..8,
    "y"=> &["A", "A", "A", "B", "B", "C", "X", "X"],
)
.unwrap();
let[ join](https://docs.pola.rs/api/rust/dev/polars_core/frame/hash_join/index.html)ed = df.join(&df2, ["a"], ["x"], JoinType::Left.into())?;
println!("{}", joined);
```

shape: (8, 4)
┌─────┬──────────┬───────┬─────┐
│ a   ┆ b        ┆ d     ┆ y   │
│ --- ┆ ---      ┆ ---   ┆ --- │
│ i64 ┆ f64      ┆ f64   ┆ str │
╞═════╪══════════╪═══════╪═════╡
│ 0   ┆ 0.413096 ┆ 1.0   ┆ A   │
│ 1   ┆ 0.788608 ┆ 2.0   ┆ A   │
│ 2   ┆ 0.082807 ┆ NaN   ┆ A   │
│ 3   ┆ 0.354029 ┆ NaN   ┆ B   │
│ 4   ┆ 0.170787 ┆ 0.0   ┆ B   │
│ 5   ┆ 0.96954  ┆ -5.0  ┆ C   │
│ 6   ┆ 0.974006 ┆ -42.0 ┆ X   │
│ 7   ┆ 0.519562 ┆ null  ┆ X   │
└─────┴──────────┴───────┴─────┘

**Comment by MarcoGorelli** [comment]
hi @sudipto80 - I can't follow your link, can you check your post please?

**Comment by MarcoGorelli** [comment]
Ah it's here: https://docs.pola.rs/user-guide/getting-started/#join

To be honest I'm surprised they're not all `null` 🤔

**Comment by MarcoGorelli** [comment]
Ah, looks like the input differs between the Python and Rust examples

To make them consistent, I think the Rust example input should have:
```
    "d"=> [Some(1.0), Some(2.0), f64::NAN, f64::NAN, Some(0.0), Some(-5.0), Some(-42.), None]
```
instead

File that needs updating: `src/rust/user-guide/getting-started/joins.rs`
