### ISSUE TITLE
error[E0599]: no variant or associated item named `Struct` found for enum `polars_core::datatypes::DataType` in the current scope

### ISSUE THREAD

**Issue by joneadoerd9** [pola-rs/polars#17878]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

let out = pivot(&df, ["foo"], Some(["bar"]), Some(["N"]) ,false, None, None).unwrap();
```

### Log output

error[E0599]: no method named `struct_` found for enum `std::borrow::Cow<'_, polars_core::prelude::Series>` in the current scope
238 |         let columns_struct = StructChunked::new(&column, fields).unwrap().into_series();
    |                              ^^^^^^^^^^^^^
    |                              |
    |                              use of undeclared type `StructChunked`
    |                              help: a type alias with a similar name exists: `StringChunked`

error: aborting due to 7 previous errors

### Issue description

when start using the 
with v0.41.3  but not working

### Expected behavior

  shape: (3, 6)
┌─────┬──────┬──────┬──────┬──────┬──────┐
│ foo ┆ k    ┆ l    ┆ m    ┆ n    ┆ o    │
│ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str ┆ i64  ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
╞═════╪══════╪══════╪══════╪══════╪══════╡
│ A   ┆ 1    ┆ 2    ┆ null ┆ null ┆ null │
│ B   ┆ null ┆ null ┆ 2    ┆ 4    ┆ null │
│ C   ┆ null ┆ null ┆ null ┆ null ┆ 2    │
└─────┴──────┴──────┴──────┴──────┴──────┘

### Installed versions

<details>
polars = { version =  "0.41.3", features = ["polars-lazy","lazy","pivot"] }

</details>

**Comment by thiru-appitap** [comment]
ChunkedStruct is available with the dtype-struct feature - please add and give it a try!

**Comment by joneadoerd9** [comment]
> ChunkedStruct is available with the dtype-struct feature - please add and give it a try!

Yes , it Works
