### ISSUE TITLE
Invariant that `infer_schema_length=0` returns all utf8 in `read_csv` is not upheld?

### ISSUE THREAD

**Issue by jorgecarleitao** [pola-rs/polars#1787]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.20

#### What operating system are you using polars on?

Linux

#### Describe your bug.

When using `infer_schema_length=0` in `read_csv` of 2 separate files followed by `pl.concat`, I am getting an error whereby one of the columns is a "date" and another is "str". This seems inconsistent with the documentation of `infer_schema_length`, where we claim that all columns will be read as `utf8`.

#### What are the steps to reproduce the behaviour?

TODO/placeholder; need to find one when I get home - data is confidential.

The code used

```python
    df = pl.read_csv(
        BytesIO(data),
        sep="\x07",
        quote_char=None,
        infer_schema_length=0,
    )
```

**Comment by ghuls** [comment]
```python
df = pl.read_csv(
        BytesIO(data),
        sep="\x07",
        quote_char=None,
        infer_schema_length=0,
        parse_dates=False,
)

**Comment by ritchie46** [comment]
Ah, and I see we must set `parse_dates` to `False` in that case. The `parse_dates` is not really consistent. As in, it depends on the data how the schema will look. If we cannot find a matching pattern, its a `Utf8`, otherwise it will be a `Date/DateTime`.

Maybe its better to default to `parse_dates=False` to keep the schema predictable? :thinking:

**Comment by ghuls** [comment]
> Maybe its better to default to `parse_dates=False` to keep the schema predictable? thinking
I think it is better that it is off by default and enabled by the user if required.

**Comment by jorgecarleitao** [comment]
Yeah, I was basically trying to get the `dtype=object` behavior from Pandas, and the closest I got was to use `infer_schema_length=0`, which was not sufficient. Thanks @ghuls for the quick fix. I also agree that `parse_dates` should be False by default.

**Comment by ritchie46** [comment]
False it is: #1791
