### ISSUE TITLE
Change all columns one time

### ISSUE THREAD

**Issue by xiasijian** [pola-rs/polars#17872]
### Description

```python
def change_all_columns_at_once(new_col_list,psl_df):
    columns_dict = {col: None for col in psl_df.columns}
    updated_columns_dict = {key: psl_header[i] for i, key in enumerate(columns_dict)}
    return(psl_df.rename(updated_columns_dict))
```

**Comment by mcrumiller** [comment]
Looks like the wrong place to post this. But FYI here is a more concise version:

```python
df = df.rename({x:y for x,y in zip(df.columns, new_col_list)})
```

**Comment by markxwang** [comment]
> Looks like the wrong place to post this. But FYI here is a more concise version:
> 
> ```python
> df = df.rename({x:y for x,y in zip(df.columns, new_col_list)})
> ```

Well..you can just dict(zip(l1, ls2))

**Comment by xiasijian** [comment]
> question

I am sorry, I just mark the example for this usage. Not question. Thanks

**Comment by ritchie46** [comment]
I am closing this as this is not a forum for examples. Maybe consider StackOverflow.
