### ISSUE TITLE
Make pl.Enum(...) return type rather than instance

### ISSUE THREAD

**Issue by shenrun** [pola-rs/polars#17894]
### Description

I am using pandera to validate my data models, and it requires type, not an instance, when defining the schema. So when it comes to pl.Enum, which requires 'categories' as its argument, the schema comparison fails.

**Comment by mcrumiller** [comment]
Sorry, what's the issue?

```python
x = pl.Enum(["a", "b", "c"])
x == pl.Enum
# True
```

**Comment by stinodego** [comment]
Please open an issue with pandera. This is not something Polars can fix.
