### ISSUE TITLE
list.any() and list.all() behavior with all null list looks incorrect

### ISSUE THREAD

**Issue by cpcloud** [pola-rs/polars#17917]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
In [20]: import polars as pl

In [21]: df = pl.DataFrame({"values": [[True], [None]]})

In [22]: df.with_columns(any=pl.col("values").list.any(), all=pl.col("values").list.all())
Out[22]:
shape: (2, 3)
┌────────────┬───────┬──────┐
│ values     ┆ any   ┆ all  │
│ ---        ┆ ---   ┆ ---  │
│ list[bool] ┆ bool  ┆ bool │
╞════════════╪═══════╪══════╡
│ [true]     ┆ true  ┆ true │
│ [null]     ┆ false ┆ true │
└────────────┴───────┴──────┘
```

### Issue description

`any` and `all` don't seem to implement TVL (three-valued logic), and thus do not incorporate correct null behavior.

### Expected behavior

I would expect:

- `all([null])` is `null`
- `any([null])` is `null`
- `all([true, null])` is `null` (we don't know if `null` is `true` or `false` so the answer is also indeterminate)
- `any([false, null])` is `null` (we don't know if `null` is `true` or `false` so the answer is also indeterminate)
- `all([false, null])` is `false` (at least one `false` implies `false` regardless of what the `null` value would be)
- `any([true, null])` is `true` (at least one `true` implies `true` regardless of what the `null` value would be)

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-6.6.42-x86_64-with-glibc2.39
Python:               3.10.14 (main, Mar 19 2024, 21:46:16) [GCC 13.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.18.2
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @cpcloud for report

I think usually Polars skips nulls for Series operations, and apply kleene logic when combining columns horizontally

for example:
```
In [34]: s = pl.Series([None], dtype=pl.Boolean)

In [35]: s.any()
Out[35]: False

In [36]: s.all()
Out[36]: True

In [37]: s & s
Out[37]:
shape: (1,)
Series: '' [bool]
[
        null
]

In [38]: s | s
Out[38]:
shape: (1,)
Series: '' [bool]
[
        null
]
```

You can get Kleene logic to kick in for `Series.any` / `Expr.any` by passing `ignore_nulls=False`

It looks like `Expr.list.any` doesn't have a `ignore_nulls` arg though - perhaps it should?

**Comment by MarcoGorelli** [comment]
In fact, it looks like that was already request here: https://github.com/pola-rs/polars/issues/16764

OK to close as duplicate of that one?

**Comment by cpcloud** [comment]
SGTM!
