### ISSUE TITLE
There‘s no Right in JoinType enum

### ISSUE THREAD

**Issue by AmbitionsXXXV** [pola-rs/polars#17926]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;
use anyhow::Result;

use rand::Rng;

pub fn right_join_df() -> Result<()> {
  let mut rng = rand::thread_rng();

  let df1: DataFrame = df!(
    "a" => 0..8,
    "b" => (0..8).map(|_| rng.gen::<f64>()).collect::<Vec<f64>>()
  )?;

  let df2: DataFrame = df!(
      "x" => 0..8,
      "y" => &["A", "A", "A", "B", "B", "C", "X", "X"]
  )?;

  let joined = df1.join(&df2, ["a"], ["x"], JoinType::Right.into())?;

  println!("{:?}", joined);

  Ok(())
}
```

### Issue description

I want to use right join with Polars, when I read the docs about right join and I use the example useage in my code. I found that enum JoinType has no Right element

### Expected behavior

I want to use right join with Polars, when I read the docs about right join and I use the example useage in my code. I found that enum JoinType has no Right element

### Installed versions

Versions I use
polars = { version = "0.41.3", features = ["lazy"] }
rust stable version

**Comment by AmbitionsXXXV** [comment]
![CleanShot 2024-07-29 at 17 00 07](https://github.com/user-attachments/assets/17ac0dea-6455-4b75-b125-49925dbd677b)
here is I check the JoinType source definition

**Comment by alexander-beedie** [comment]
You can see "Right" here in the current `main`; this will be available in the next Rust release (which will be `0.42.0`):
https://github.com/pola-rs/polars/blob/6e4b48139f2b5358cae46c110d37e38bd5438772/crates/polars-ops/src/frame/join/args.rs#L112

**Comment by AmbitionsXXXV** [comment]
Yeah,I saw that.
But when I jump into the source code from VSCode like this, I cant saw the `Right` element, I'm not sure what cause this
![CleanShot 2024-07-30 at 09 23 00@2x](https://github.com/user-attachments/assets/e4a4dbf6-1382-4b80-89a2-8d41864b8f0c)
