### ISSUE TITLE
Polars 1.3.0 throws parquet errors when reading (I think) categorical columns in settings that 1.1.0 does not.

### ISSUE THREAD

**Issue by mmcdermott** [pola-rs/polars#17931]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I don't have a MWE at the moment, but wanted to post this in the interim so others can find it. 

I have a confirmed test case in a public repo I'm working on that I'll implement below where running code with polars 1.1.0 works fine and with 1.3.0 raises this error: 

`polars.exceptions.ComputeError: parquet: Not yet supported: Dictionary array without a dictionary page`

The test case is this test file in this repo: https://github.com/mmcdermott/MEDS_transforms/blob/397916bc4941c270b205e8fbf5307aa407d5b56b/tests/test_extract.py

Here is an example of the test failing due to polars 1.3.0: https://github.com/mmcdermott/MEDS_transforms/actions/runs/10146769727/job/28055619925?pr=31

### Issue description

I suspect this has to due with categorical columns but I'm not sure.

### Expected behavior

It should work the same way on 1.3.0 as 1.1.0

### Installed versions

<details>

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-117-generic-x86_64-with-glibc2.35
Python:               3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.0.1
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              17.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by ritchie46** [comment]
@coastalwhite
