### ISSUE TITLE
read_parquet() needs `binary_as_string` option

### ISSUE THREAD

**Issue by bobir01** [pola-rs/polars#17937]
### Description

I see now many db readers and packages offer reading parquet binary columns as string since some DB write to parquet string columns as binary by default (e.g: ClickHouse).

Even I saw this option available in [DuckDB cli](https://duckdb.org/docs/data/parquet/overview#:~:text=Default-,binary_as_string,-Parquet%20files%20generated) , It would be great if you could add this future.

basic interface:
```
pl.read_parquet(...,binary_as_string=True)
```

<img width="952" alt="image" src="https://github.com/user-attachments/assets/4203cc52-d636-4d28-91a0-ee884caf00c9">

**Comment by coastalwhite** [comment]
I feel like this should be the same as #17418, if it is added.

**Comment by bobir01** [comment]
@ritchie46  Thanks i never thought this way
