### ISSUE TITLE
How to read sam file by polars?

### ISSUE THREAD

**Issue by xiasijian** [pola-rs/polars#17953]
### Description

![image](https://github.com/user-attachments/assets/6ea0499c-4fa1-47a2-be9c-0a02b39ae3bc)

**Comment by xiasijian** [comment]
sam_df = pl.read_csv(n1000.sam, has_header =False,columns = [0,1] ,new_columns = ["readid","flag"],
                            comment_prefix = "@",
                            separator="\t"), it does not work.  
<img width="176" alt="58f0b9e6d8b937579ae0c19fa032321" src="https://github.com/user-attachments/assets/1a53b9ec-5e26-489e-8321-9763d0d2f537">

**Comment by mcrumiller** [comment]
Can you post either a link to the file, or copy/paste the first 10 or so lines of the file?

**Comment by xiasijian** [comment]
[probe1000.zip](https://github.com/user-attachments/files/16442572/probe1000.zip)
This is example file, thanks

**Comment by deanm0000** [comment]
This seems to work

```
df = pl.read_csv("probe1000.sam", 
                 skip_rows=3, 
                 truncate_ragged_lines=True,
                 has_header=False, separator="\t")
```

**Comment by xiasijian** [comment]
> df = pl.read_csv("probe1000.sam", 
>                  skip_rows=3, 
>                  truncate_ragged_lines=True,
>                  has_header=False, separator="\t")

Thanks!

**Comment by xiasijian** [comment]
> This seems to work
> 
> ```
> df = pl.read_csv("probe1000.sam", 
>                  skip_rows=3, 
>                  truncate_ragged_lines=True,
>                  has_header=False, separator="\t")
> ```

def get_header_nrow(input_sam):
    skip_row_n = 0
    with open(input_sam,"r") as f:
        for line in f:
            if line.startswith("@"):
                skip_row_n+=1
            else:
                break
            
    return int(skip_row_n)
## test sam read
input_sam = "probe1000.sam"
df = pl.read_csv("probe1000.sam", 
                 skip_rows=get_header_nrow(input_sam), 
                 truncate_ragged_lines=True,
                 has_header=False, separator="\t")

**Comment by xiasijian** [comment]
> This seems to work
> 
> ```
> df = pl.read_csv("probe1000.sam", 
>                  skip_rows=3, 
>                  truncate_ragged_lines=True,
>                  has_header=False, separator="\t")
> ```

```python
def get_header_nrow(input_sam):
    skip_row_n = 0
    with open(input_sam,"r") as f:
        for line in f:
            if line.startswith("@"):
                skip_row_n+=1
            else:
                break
            
    return int(skip_row_n)
## test sam read
input_sam = "probe1000.sam"
df = pl.read_csv("probe1000.sam", 
                 skip_rows=get_header_nrow(input_sam), 
                 truncate_ragged_lines=True,
                 has_header=False, separator="\t")


```
