### ISSUE TITLE
count(1) returns 1 instead of actual count

### ISSUE THREAD

**Issue by tooptoop4** [pola-rs/polars#17989]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.sql(
"""
SELECT count(1) from df
"""
).collect()

```

### Log output

```shell
1
```

### Issue description

returns 1

### Expected behavior

actual count of df rows, like count(*) does

### Installed versions

1.3.0

**Comment by ritchie46** [comment]
This is the 3rth issue without a reproduction. Please open a proper issue. I will close this.

**Comment by tooptoop4** [comment]
sql is there can try it on any df
