### ISSUE TITLE
`DeprecationWarning` in v0.20.31 about `df.join(..., how="left")` and coalesce default changing seems to be a "lie"

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#17987]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Run the following code in v0.20.31:

```python
import polars as pl

df_customers = pl.DataFrame(
    {
        "customer_id": [1, 2, 3],
        "name": ["Alice", "Bob", "Charlie"],
    }
)

df_orders = pl.DataFrame(
    {
        "order_id": ["a", "b", "c"],
        "customer_id": [1, 2, 2],
        "amount": [100, 200, 300],
    }
)

print(df_customers.join(df_orders, on="customer_id", how="left"))
```

See that the output yields the following deprecation warning:

```
DeprecationWarning: The default coalesce behavior of left join will change to `False` in the next breaking release. Pass `coalesce=True` to keep the current behavior and silence this warning.
  print(df_customers.join(df_orders, on="customer_id", how="left"))
```

However, in v1.3 (latest), the output is the exact same as it used to be, suggesting that the how=left default coalesce value remained as True. The DeprecationWarning warns of a future change that never happened.

**Solution:** I propose a `v0.20.32` or `v0.20.31.1` backport which removes this DeprecationWarning. 

**Importance:** The reason I've delayed upgrading to v1 at work is due to needing to write some crazy regex magic/migration code to update hundreds of joins across the codebase, as I thought this was a breaking change. Turns out, it's not necessary at all for these cases. This change may save others the hassle.

### Issue description

The sample code yields a DeprecationWarning, which disappears silently.

### Expected behavior

The DeprecationWarning should not appear for `df.join(df, how="left")`, as far as I can tell.

Related to docs request in #17986 

### Installed versions

v0.20.31.

Tested with v1.3.0 to observe that the coalesce default behaviour didn't change.

**Comment by ritchie46** [comment]
This was reverted. But were not making a new 0.20 release, there is enough to do already. You can silence the warning.

BTW, it wasn't a lie, we thought we were going to change it, but we changed our mind. That can happen.

**Comment by DeflateAwning** [comment]
Again, didn't mean to suggest there was ill-intent; just meant that it was incorrect information.

Do you have any insight into how many people haven't done the migration yet? Might be valuable to inform whether it's worth it to make sure the DeprecationWarnings are accurate in the final release before a breaking release (this long after the breaking release).

Judging by the community, I'm not the only one who hasn't moved to v1 yet.
