### ISSUE TITLE
Querying DuckDB using Polars' logical plan 

### ISSUE THREAD

**Issue by agupta726** [pola-rs/polars#17997]
### Description

I want to build my application logic using the Polars dataframe API - projections, join, filtering etc and then use DuckDB to actually execute the query represented by the Polars dataframe. I suppose one way to think about this would be that I want to use Polars dataframe API only for plan generation (perhaps a Substrait plan?) but not as an engine. I'd want to pass this plan to DuckDB to do the actual execution. 
Is there any way to do this? Or can this be accepted as a feature request?

**Comment by cmdlineluser** [comment]
I think this may have been previously requested:

- https://github.com/pola-rs/polars/issues/15581

Which was deemed not possible due to the reasons explained in: https://github.com/pola-rs/polars/issues/7404#issuecomment-2049534546

**Comment by alexander-beedie** [comment]
Curious why you'd want to run the Polars API on the DuckDB engine?

**Comment by agupta726** [comment]
> Curious why you'd want to run the Polars API on the DuckDB engine? I can't see that it's something we would be that interested in developing/supporting 🤔
> 
> (Depending on what is required, could be a job for a future iteration of [Narwhals](https://github.com/narwhals-dev/narwhals), @MarcoGorelli?)

Honestly I'm looking for a Spark like dataframe API for but C++. I have a need to generate complex SQL and I believe using a dataframe API is the right way to do it. 

Any recommendations are appreciated.

**Comment by cmdlineluser** [comment]
Have you seen DuckDB's spark api?

- https://duckdb.org/docs/api/python/spark_api

**Comment by agupta726** [comment]
> Have you seen DuckDB's spark api?
> 
> * https://duckdb.org/docs/api/python/spark_api

Thanks @cmdlineluser. I did see this already. I'm looking for a C++ based dataframe API though.

**Comment by ritchie46** [comment]
> I'm looking for a C++ based dataframe API though.

How is Polars going to help then? It is written in Rust.

**Comment by MarcoGorelli** [comment]
> Honestly I'm looking for a Spark like dataframe API for but C++

closing then as out-of-scope

> (Depending on what is required, could be a job for a future iteration of [Narwhals](https://github.com/narwhals-dev/narwhals), @MarcoGorelli?)

watch this space 😉
