### ISSUE TITLE
The v1 upgrade guide mentions `.replace` and `.replace_strict`. However, nothing breaks, and there's no deprecation warning. 

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#17999]
### Description

The following code, which is v0.20-era, continues to work with no warning/error in v1:

```python
# is_nullable column is pl.String datatype
df_cols = df_cols.with_columns(
			pl.col('is_nullable').replace({'YES': True, 'NO': False}, default=None, return_dtype=pl.Boolean)
		)
```

I wasn't totally sure whether the required shift to `.replace_strict` is starting its DeprecationWarning era, or whether the change was made in v1 based on the guide. Appears to be neither.

Possible solutions:
1. Remove it as a "breaking change" from the v1 guide.
2. Edit the library to add a DeprecationWarning on usage of `.replace()` where `return_dype` arg is set.

### Link

https://docs.pola.rs/releases/upgrade/1/#split-replace-functionality-into-two-separate-methods

**Comment by cmdlineluser** [comment]
I get 2 deprecation warnings.

```python
import polars as pl

df = pl.DataFrame({'is_nullable': ['YES', 'NO', 'MAYBE']})

df.with_columns(
    pl.col('is_nullable').replace({'YES': True, 'NO': False}, default=None, return_dtype=pl.Boolean)
)
```
```
# DeprecationWarning: 
# The `return_dtype` parameter for `replace` is deprecated. Use `replace_strict` instead to set a return data type while replacing values.

# DeprecationWarning: 
# The `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
```

**Comment by DeflateAwning** [comment]
Welp I do too. I bet I got venvs mixed up or something while I trying to figure it out. 

Thanks for taking the time to check it out! :)
