### ISSUE TITLE
The v1 Upgrade Guide doesn't mention the removal of `df.frame_equal(df2)`

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#17998]
### Description

The v1 Change Notes don't mention the removal of `df.frame_equal(df2)`

That was a rude awakening ;) when all our unit tests for utilities started failing. 

Seems like an easy fix: `.frame_equal` got renamed to `.equals`

### Link

https://docs.pola.rs/releases/upgrade/1/

**Comment by ritchie46** [comment]
Can you make a PR?

**Comment by DeflateAwning** [comment]
Done! Cheers :)

**Comment by DeflateAwning** [comment]
I'm disappointed my PR was closed, despite it being suggested by a maintainer here.

Polars clearly prides itself on being explicit (e.g., verbose method names, argument names, etc.). I wish the upgrade guide was as well-thought-about as the library itself is.

[My **5 (and counting) issues** about the v1 guide missing breaking changes](https://github.com/pola-rs/polars/issues?q=is%3Aissue+v1+guide+author%3ADeflateAwning) should be evidence enough that something's going wrong with the management of the upgrade guide.

**Comment by ritchie46** [comment]
Ah, @stinodego is responsible for our migration guide and I understand his reasoning. It isn't the goal of the migration guide to be a full copy of the changelogs.

Sorry for the miscommunication. I will close this as the changelog does mention it.

> Polars clearly prides itself on being explicit (e.g., verbose method names, argument names, etc.). I wish the upgrade guide was as well-thought-about as the library itself is.

Time is limited. We work as hard as we can. Making a perfect migration guide is not time spent on other issues.

**Comment by DeflateAwning** [comment]
May I add a warning to the top of the upgrade guide that explains that it's missing significant things, and that each changelog must be read in detail to avoid your production code breaking?

**Comment by DeflateAwning** [comment]
Also, "time is limited" is a shitty excuse for closing someone's pre-approved PR. I love you guys, but I'm a little offended haha
