### ISSUE TITLE
v1 Upgrade Guide: Missing `pl.read_csv(infer_schema_length=0)` -> `False`

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#18002]
### Description

It appears that the documentation for `pl.read_csv()` made a silent switch from `infer_schema_length` from 0 to False to read as strings. 

It seems that both are supported, but the docs no longer explain what `infer_schema_length=0` means. 

Proposal (pick one):
* Add a DeprecationWarning for `infer_schema_length==0`
* Add back a note about `infer_schema_length` in `pl.read_csv`

### Link

https://docs.pola.rs/releases/upgrade/1/#properly-apply-strict-parameter-in-series-constructor and https://docs.pola.rs/api/python/version/0.20/reference/api/polars.read_csv.html#:~:text=of%20your%20system.-,infer_schema_length,-The%20maximum%20number

**Comment by Julian-J-S** [comment]
Hi @DeflateAwning 

This is not entirely correct.
`infer_schema_length=0` is still there and valid 😀 

BUT there is a NEW parameter called `infer_schema` which is a bool to indicate very explicit that you do NOT want inference when set to `False` 😉 

![image](https://github.com/user-attachments/assets/b2c54474-09be-4d60-8b5b-f21a2c0727f0)

**Comment by DeflateAwning** [comment]
You're correct in that I missed the new `infer_schema` arg.

However, imagine the following scenario: You're a new member to a team with a large Polars codebase. You stumble across some code, and the git blame shows it was modified in 2024-05 last. You see the `infer_schema_length=0`, but that doesn't intuitively make sense. You check the online docs, and see that `infer_schema_length=False` and `=None` are explained, but you don't see anything about `infer_schema_length=0`. Is 0 equivalent to None, False, or something else? 

0 is closer to False than None normally, but that's still a leap of an assumption.

In any case, it's undocumented behaviour. As such, it should either be mentioned in the docs (again), or it should get a DeprecationWarning (suggesting the `infer_schema` boolean arg instead).

**Comment by DeflateAwning** [comment]
Welp, I don't know why I'm so bad at reading this one section of the docs. I've totally opened a pointless issue about this one before (#15332). 

Thanks for entertaining me :)

**Comment by yamanjain** [comment]
I had the exact same doubt so I do not think it was pointless. Thanks for the clarification. AI generated code is inferring this as ""setting infer_schema_length=0 will scan all rows". This stands corrected thanks to this thread.
