### ISSUE TITLE
`drop` on `LazyFrame` called from Python is expensive due to resolving schema (from selector expansion)

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#18008]
### Description

[The code here](https://github.com/pola-rs/polars/blob/main/py-polars/polars/lazyframe/frame.py#L4722) triggers a schema collection (which can be very expensive, in my case it's expensive due to path expansion of 10k+ files).

Ideally `drop` shouldn't trigger any io/computation. Alternatively, if something like https://github.com/pola-rs/polars/issues/17855 is implemented, where you only do a minimal expansion to get the schema is implemented, this wouldn't become as big of an issue.

**Comment by ritchie46** [comment]
Yes, it shouldn't do that. This should be resolved at IR conversion. Will take a look.

**Comment by ritchie46** [comment]
@alexander-beedie FYI, we should see if we can move most of this to IR conversion phase. This is very costly.
