### ISSUE TITLE
Describe returns wrong result for struct column

### ISSUE THREAD

**Issue by liheinz** [pola-rs/polars#18019]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a":{"b":1,"c":"a"}})
df.describe()
```
────────────┬──────┐
│ statistic  ┆ a    │
│ ---        ┆ ---  │
│ str        ┆ f64  │
╞════════════╪══════╡
│ count      ┆ 1.0  │
│ null_count ┆ 0.0  │
│ mean       ┆ null │
│ std        ┆ null │
│ min        ┆ null │
│ 25%        ┆ null │
│ 50%        ┆ null │
│ 75%        ┆ null │
│ max        ┆ null │
└────────────┴──────┘

### Issue description

Hey,
df.describe() treats struct columns as f64

### Expected behavior

Either not implemented or struct summary information 

### Installed versions

<details>
Polars:               1.4.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

</details>

**Comment by alexander-beedie** [comment]
> df.describe() treats struct columns as f64

Actually the `f64` there doesn't describe the struct column, it describes the _results_ shown. As most stats don't apply to struct (for obvious reasons - what would the mean of a struct col be? ;) you only see the count and null_count results. These are numeric, so the column dtype containing these results is also numeric.
