### ISSUE TITLE
Shrinking of `u64` series fails (`shrink_dtype`)

### ISSUE THREAD

**Issue by nwagner84** [pola-rs/polars#18029]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn main() {
    let data: Vec<u64> = vec![1, 2, 3, 4, 5, 6];
    let df = DataFrame::new(vec![Series::new("foo", data)]).unwrap();
    eprintln!("{df}");

    let df2: DataFrame = df
        .lazy()
        .select([col("foo").shrink_dtype()])
        .collect()
        .unwrap();
    eprintln!("{df2}");
}
```

### Log output

```shell
Compiling polars-shrink v0.1.0 (/home/nico/tmp/polars-shrink)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.96s
     Running `target/debug/polars-shrink`
shape: (6, 1)
┌─────┐
│ foo │
│ --- │
│ u64 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ 5   │
│ 6   │
└─────┘
run ProjectionExec
thread 'main' panicked at src/main.rs:12:10:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot create series from UInt8"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

Shrinking of the `u64` series fails, with an `ComputeError` "cannot create series from UInt8". If the maximum value of the `foo` column is greater than `u8::MAX`, I get the same `ComputeError with "cannot create series from UInt16".

### Expected behavior

As far as I understand the `shrink_dtype` the function tries to shrink to the smallest possible data type (if possible). If it's not possible, the function leaves the series as it is. But in the above mentioned example, shrinking to an `u8` series should be possible.

### Installed versions

<details>
polars = { version = "0.41.3", features = ["lazy"] }
</details>

**Comment by coastalwhite** [comment]
I am not sure of the rootcause of this, but it is quite interesting that the panic does not trigger on almost identical python code.

```python
import polars as pl

df = pl.DataFrame({ 'a': [1, 2, 3, 4, 5, 6] }, schema={'a': pl.UInt64})

print(df)
print(
    df
        .lazy()
        .select([pl.col('a').shrink_dtype()])
        .collect()
)
```

I also ran this example on the latest commit which is tagged python release v1.4.0 and it still panics.

**Comment by ritchie46** [comment]
Ah.. You must activate `dtype-u8`.

**Comment by nwagner84** [comment]
Oh, I didn't know that. Now everything works as expected. 

NB: Maybe it's worth adding a note to the documentation of `shrink_dtype`.

Thanks!
