### ISSUE TITLE
concat/vstack ignores column names

### ISSUE THREAD

**Issue by XeCycle** [pola-rs/polars#1802]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.20

#### What operating system are you using polars on?

Arch Linux

#### Describe your bug.

This has been discussed in #1801; concat and vstack in their current form does not consider column names at all, which is surprising.

#### What are the steps to reproduce the behavior?

```
In [2]: d1 = polars.DataFrame({"a": [1], "b": [2]})

In [3]: d2 = polars.DataFrame({"b": [3], "a": [4]})

In [6]: polars.concat([d1, d2])
Out[6]:
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   │
└─────┴─────┘
```

#### What is the expected behavior?

We can either change them to align by column names or, as already discussed in #1801, change them to error out to avoid hiding bugs.  Both will be a breaking change.  If we choose to error out, then a method to sort columns would be very helpful, because current ways like `d[sorted(d.columns)]` require a named variable to operate on and may be ugly in long expression chains.

**Comment by ibENPC** [comment]
Knowing that the safe and clean methodology is to use the joins, in my (debatable) opinion the `vstack` should give an error unless the 3 following conditions are met:
1. The columns names are the same
2. The columns types are the same
3. The columns are in the same order
--> The `Schema` is the same.

**Comment by ritchie46** [comment]
Agree. It should error if the schemas don't match.

**Comment by Arengard** [comment]
![Screenshot 2021-11-17 155358](https://user-images.githubusercontent.com/52859991/142224406-07255738-8197-42b9-968b-3e24ae721de6.png)

**Comment by XeCycle** [comment]
Ouch.  Thanks, I missed that diagonal one.  So do we still want to make the default error out on schema mismatch?

**Comment by ritchie46** [comment]
> Ouch. Thanks, I missed that diagonal one. So do we still want to make the default error out on schema mismatch?

Yes..

**Comment by ritchie46** [comment]
@XeCycle 

You mentioned you wanted to sort column without breaking the chainging. This can be done with `pipe` in lazy and eager:

```python
(pl.DataFrame({
    "a": [1, 2],
    "c": [1, 2],
    "b": [1, 2],
})
 .select([pl.col("b").alias("z"), pl.all()])
).pipe(lambda df: df[sorted(df.columns)])
```
