### ISSUE TITLE
FileNotFoundError not working for scan methods

### ISSUE THREAD

**Issue by DrMalvavisco** [pola-rs/polars#18025]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
try:
    pl.scan_parquet('some_inexistent_file.parquet')
except:
    print('Some exception.')
```

### Issue description

In versions 0.20.XX read and scan methods between try except block worked correctly:
![image](https://github.com/user-attachments/assets/d0fda708-b5a2-44e4-8419-1d2f09b3ddab)

But in the version 1.0, the except part isnt executed with scan methods:
![image](https://github.com/user-attachments/assets/f782ab96-135b-4f72-b8d7-786a1d88afb3)

### Expected behavior

This is an exception, so the expected behaviour is to be catched by the except block.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

</details>

**Comment by coastalwhite** [comment]
The `scan_parquet` method is lazy, it is not required to do anything until it is needed. Before the path resolution would happen when you called scan_parquet, now it gets done when you collect. If you want to collect the error, you can do it there, or you can see if the file exists using other python interfaces.

Closing.

**Comment by DrMalvavisco** [comment]
thank you!
