### ISSUE TITLE
v1 Upgrade: did `df.drop(['column_which_is_not_in_df'])` switch from doing nothing to error-ing?

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#18045]
### Description

Having an issue between v0.20.31 and v1.4.0 where I'm getting errors trying to drop columns which seem to have never been in the dataframe. 

Was this a change? 

If so, I'll add a note about it to the upgrade guide so people know to expect it.

### Link

https://docs.pola.rs/releases/upgrade/1/

**Comment by cmdlineluser** [comment]
Probably a consequence of https://github.com/pola-rs/polars/issues/11913 being fixed.

There is a `strict` parameter now:

- https://github.com/pola-rs/polars/pull/17044

**Comment by DeflateAwning** [comment]
I agree!

Did that change coincide with the v1 release? Does it make sense to add it to the upgrade guide? I can submit a quick PR for it, if it's waranted.

**Comment by cmdlineluser** [comment]
It does look that way:

> added this to the [1.0.0](https://github.com/pola-rs/polars/milestone/4) milestone [Jun 18, 2024](https://github.com/pola-rs/polars/issues/11913#event-13198614074)

**Comment by coastalwhite** [comment]
Yes, that seems like something that would be nice to put in the v1 upgrade guide.

**Comment by DeflateAwning** [comment]
Quick PR submitted

**Comment by DeflateAwning** [comment]
Well I guess that PR is never gonna get merged. Welp.
