### ISSUE TITLE
Drop columns based on position of column

### ISSUE THREAD

**Issue by Abinashbunty** [pola-rs/polars#18048]
### Description

In many cases, the exact column name to use in case of [dropping columns](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.drop.html#polars-dataframe-drop) is not available. But the position of the column is intact in source data. So an index based droppping of columns will help in handling such scenarios. 😄

**Comment by cmdlineluser** [comment]
It is already possible with [`pl.nth`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.nth.html) for example.

```python
>>> pl.DataFrame(schema=["a", "b", "c"]).drop(pl.nth(1))
shape: (0, 2)
┌──────┬──────┐
│ a    ┆ c    │
│ ---  ┆ ---  │
│ null ┆ null │
╞══════╪══════╡
└──────┴──────┘
```

**Comment by deanm0000** [comment]
> It is already possible with [`pl.nth`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.nth.html) for example.
> 
> ```python
> >>> pl.DataFrame(schema=["a", "b", "c"]).drop(pl.nth(1))
> shape: (0, 2)
> ┌──────┬──────┐
> │ a    ┆ c    │
> │ ---  ┆ ---  │
> │ null ┆ null │
> ╞══════╪══════╡
> └──────┴──────┘
> ```

whoa!! when did `pl.nth` come about?

**Comment by deanm0000** [comment]
In light of `pl.nth` I'm going to close this.

**Comment by Abinashbunty** [comment]
Thanks! I didn't realise it could be done this way. 😅
