### ISSUE TITLE
A fixed-length array type (for embeddings)

### ISSUE THREAD

**Issue by KDruzhkin** [pola-rs/polars#18055]
### Description

DuckDB has two array types:
- **fixed-length** [arrays](https://duckdb.org/docs/sql/data_types/array),
- **variable-length** [lists](https://duckdb.org/docs/sql/data_types/list).

Arrays can be used to store vectors such as [word embeddings](https://en.wikipedia.org/wiki/Word_embedding) or image embeddings.

Are there any plans to add arrays to Polars as well?

**Comment by deanm0000** [comment]
pl.Array?

**Comment by KDruzhkin** [comment]
Sorry, the Array type is just missing from the [data types overview](https://docs.pola.rs/user-guide/concepts/data-types/overview/).

**Comment by KDruzhkin** [comment]
I will open a PR to fix the docs.
