### ISSUE TITLE
v1 Upgrade Guide: seems as though `pl.NUMERIC_DTYPES` is no longer actively supported?

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#18062]
### Description

It seems as though `pl.NUMERIC_DTYPES` (and related list constants) are no longer supported? Type hinting/linting support for them is failing, although the code itself is not yet failing it seems.

### Link

https://docs.pola.rs/releases/upgrade/1/

**Comment by mcrumiller** [comment]
These are now located in `pl.datatypes.group.NUMERIC_DTYPES`. I don't believe they are re-exported anywhere so you'll have to use the full path:

```
from polars.datatypes.group impot NUMERIC_DTYPES
```

**Comment by DeflateAwning** [comment]
Any reason they're not re-exported anymore? Could they be aliased the same as before? Would you accept a PR?

They're super helpful methods when working with dynamic and user-supplied dataframes.

The craziest part is that, as of `v1.4.1`, they are still accessible by `pl.NUMERIC_DTYPES`; there's just no type hinting/linting support for them.

**Comment by DeflateAwning** [comment]
Well I guess this is the way it is now. Closing so higher priorities can be addressed.
