### ISSUE TITLE
`df.join_asof()` - give example of what `coalesce` argument does

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#18089]
### Description

In the `df.join_asof()` docs, there's no mention of what the coalesce argument does really.

Does it act on the `by` or `on` columns? Or both? If it's on the `on` column, does it carry down/fill forward the value according to `strategy`?

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join_asof.html#polars.DataFrame.join_asof

**Comment by MarcoGorelli** [comment]
thanks @DeflateAwning - want to add an extra example to the docstring (and/or clarify the `coalesce` description)?

**Comment by DeflateAwning** [comment]
I can if you can explain what the behaviour is!

**Comment by MarcoGorelli** [comment]
have you tried running it to see?

sorry, I don't mean this aggressively 😄 i just mean, figuring out what it's meant to do is often part of the contributing process

**Comment by DeflateAwning** [comment]
I have not, and honestly, I don't necessarily trust it to do what's expected/intended.

Generally, planning code out before writing it is part of the library design process.

That said, if the currently-mysterious behaviour is definitely what's intended, I can add an example (and maybe some associated tests).

**Comment by MarcoGorelli** [comment]
nice one - could you open a pull request please?
