### ISSUE TITLE
Setting a config option in a context manager does not work in a notebook

### ISSUE THREAD

**Issue by cbrnr** [pola-rs/polars#18093]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This issue only occurs when running a Jupyter notebook. For example, I often want to display more than the default of 10 rows of a data frame temporarily, so the context manager would be very handy. Here's an example that should be run in a notebook:

```python
# %%
from string import ascii_uppercase

import numpy as np
import polars as pl

rng = np.random.default_rng(seed=42)

df = pl.DataFrame({
    "a": rng.integers(low=0, high=1000, size=1000),
    "b": rng.choice(np.array(list(ascii_uppercase)), size=1000, replace=True),
    "c": rng.integers(low=0, high=1000, size=1000),
})

# %%
df  # shows the default of 10 rows

# %%
with pl.Config(tbl_rows=1000):
    df  # does not show anything!
```

I could explicitly use `IPython.display.display`, but I don't think that this is very convenient (and expected):

```python
# %%
from IPython.display import display
with pl.Config(tbl_rows=50):
    display(df)  # works (shows 50 rows)!
```

Also, globally changing the config option does work, but this is also inconvenient because I have to revert the change right after the cell:

```python
# %%
pl.Config.set_tbl_rows(50)
df  # works (shows 50 rows)!
```

### Issue description

The context manager does not seem to work for `_repr_html_()` in a Jupyter notebook. Note that it works if I `print(df)`, but then I don't get the HTML table that I'd like to see.

### Expected behavior

I think the context manager should also work for `_repr_html_()` in a Jupyter notebook.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.4 (main, Jun 19 2024, 10:24:37) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1.post1
nest_asyncio:         1.6.0
numpy:                2.0.1
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the issue; however, this isn't a Polars issue - use of _any_ context manager in a notebook will cause the same behaviour (the return from the cell appears to get eaten, because the last thing evaluated is really the context close, not what is _in_ the context). 

Your only current option here is use of `display`, as this isn't something we can influence on our side.

![image](https://github.com/user-attachments/assets/e33a21b9-34fa-446f-aad6-6ff4a040e151)
