### ISSUE TITLE
There are still methods with str_as_lit=True thereby treating strings as literal instead of column, is this intentional?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#18099]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

NA

### Issue description

I found this after digging into https://github.com/pola-rs/polars/issues/18096

In the old days polars used to treat all strings as literals but at some point there was a decision to treat strings as columns. There are some lingering methods that would still treat strings as literals:

They can be found by looking for `str_as_lit=True` inside of `parse_as_expression`.

The methods I found are:

search_sorted, replace, extend_constant, ne_missing, eq_missing, fill_nan, fill_null, __add__, __radd__, __eq__, __ge__, __gt__, __le__, __lt__, __ne__

Should these be changed or is there a reason these were grandfathered in to the old behavior?

### Expected behavior

NA

### Installed versions

NA

**Comment by cmdlineluser** [comment]
`gather` is another one that seems to have changed behaviour:

```python
df = pl.DataFrame({"foo": [1, 2, 3], "idx": [0, 0, 1]})

df.with_columns(pl.col("foo").gather("idx"))
```
```
# TypeError: 
#   unexpected value while building Series of type Int64; 
#   found value of type String: "i"

# Hint: Try setting `strict=False` to allow passing data with mixed types.
```
