### ISSUE TITLE
[python] Support `db_kwargs` and `conn_kwargs` for ADBC connection

### ISSUE THREAD

**Issue by jongbinjung** [pola-rs/polars#18113]
### Description

ADBC python drivers support `db_kwargs` and `conn_kwargs` for specifying various options (such as different authentication methods) ([example in snowflake driver](https://github.com/apache/arrow-adbc/blob/main/python/adbc_driver_snowflake/adbc_driver_snowflake/dbapi.py#L95-L127)). 

Would be very helpful if `polars.read_database_uri` supported specifying these for [ADBC](https://github.com/pola-rs/polars/blob/py-1.4.1/py-polars/polars/io/database/_utils.py#L71).

**Comment by jongbinjung** [comment]
Actually, in investigating this, I have learnt that I can just build the connection I want and use `read_database` with that connection object instead. Seems like `read_database_uri` is really intended more for the simpler cases where a URI string would mostly suffice.

**Comment by alexander-beedie** [comment]
> Actually, in investigating this, I have learnt that I can just build the connection I want and use `read_database` with that connection object instead. Seems like `read_database_uri` is really intended more for the simpler cases where a URI string would mostly suffice.

Ah, I was about to point you in _exactly_ this direction 😎👍

If you want full control over the connection object, you can now create it with the settings you need and pass it in to `read_databasae`. Glad you found the right approach.
