### ISSUE TITLE
More informative error messages for unsupported options in streaming mode

### ISSUE THREAD

**Issue by alkment** [pola-rs/polars#18121]
### Description

It would be great to have more informative error messages for operations that are not supported in streaming mode. 

Currently an `InvalidOperationError` is raised. It can be hard to figure out which operation in my graph is the one that is not supported.

Example: 

```
InvalidOperationError: sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: StatisticsOptions { min_value: true, max_value: true, distinct_count: false, null_count: true }, row_group_size: None, data_page_size: None, maintain_order: false }) not yet supported in standard engine. Use 'collect().write_parquet()'

```

If the error message could outline the first operation that was encountered that is not available in streaming mode that would be very helpful.

**Comment by ritchie46** [comment]
We are working on a whole new streaming engine and the old one will eventually be removed. I will close this issue as we will implement `sink`s for both engines and having many small issues of things we will build doesn't help us much.

Don't worry, we will work on this. ;)

**Comment by nlgranger** [comment]
Is there a workaround in the meantime to process files larger than RAM ?
