### ISSUE TITLE
Series is not an instance of Sequence

### ISSUE THREAD

**Issue by adamamer20** [pola-rs/polars#18138]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from collections.abc import Sequence

s = pl.Series("a", [1, 2, 3])

print(isinstance(s, Sequence))  # This returns False
print(hasattr(s, "__iter__"))   # True
print(hasattr(s, "__len__"))    # True
print(hasattr(s, "__getitem__"))  # True
print(hasattr(s, "__contains__"))  # True
```

### Log output

```shell
False
True
True
True
```

### Issue description

The `pl.Series `class in Polars implements the core methods required for the Sequence abstract base class: `__iter__`, `__len__`, `__getitem__`, and `__contains__`. However, `isinstance(pl.Series(), Sequence) `returns `False`.
This inconsistency can lead to unexpected behavior when working with code that expects a `Sequence `type. It may also cause confusion for users who expect `Series` to behave like other sequence types in Python.
Is there a specific reason why Series is not a Sequence?

### Expected behavior

Given that `pl.Series` implements the core methods of a Sequence (`__iter__`, `__len__`, `__getitem__`, and `__contains__`), I expect:

1. `isinstance(pl.Series(), Sequence)` to return `True`.
2. `pl.Series` to be recognized as a Sequence by type checking tools and libraries that work with Sequence types.
3. Users to be able to use `pl.Series` in contexts where a Sequence is expected without type errors or unexpected behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.0.1
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Just checked a numpy array, and that also doesn't inherit from `Sequence`, nor a pandas `Series`. I don't think we should either.

It would trigger implicit code paths that are likely meant for non-vectorized code.

**Comment by alexander-beedie** [comment]
> It would trigger implicit code paths that are likely meant for non-vectorized code.

Agreed; I tested the impact on our own codebase and one at work and the results were not pretty 😅

**Comment by adamamer20** [comment]
Thanks for the quick response! I thought that `Sequence` was just an abstract interface so there would be no impact on performance. It's not a big deal anyway, I was just trying to simplify type aliases.

**Comment by alexander-beedie** [comment]
> Thanks for the quick response! I thought that `Sequence` was just an abstract interface so there would be no impact on performance. It's not a big deal anyway, I was just trying to simplify type aliases.

It's not performance as-such, it's that Series starts to get mistaken for things like list/tuple, and it takes more effort to distinguish from those - that's the real cause of the trouble rather than any intrinsic change in performance. It just becomes more likely to get used in the wrong place ;)

**Comment by adamamer20** [comment]
Ah I get what you're saying now! I think of `Sequence` as an ordered collection of items so list/tuples/arrays/series/dataframes all fit into the description, but I get how that might get confusing real fast, and would take significant refactoring of the codebase.
Thank you for the wonderful library!
