### ISSUE TITLE
polars.when(<condition>) treats False as True

### ISSUE THREAD

**Issue by ddouglas87** [pola-rs/polars#18134]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Doesn't work:
```python
        date = (pl.when(False)
                .then(col.Date.dt.convert_time_zone("America/New_York"))
                .otherwise(col.Date.cast(pl.Date)))
```

Does work:
```python
        if False:
            date = col.Date.dt.convert_time_zone("America/New_York")
        else:
            date = col.Date.cast(pl.Date)
```

I've overly reduced it down to `False` but any kind of bool variable doesn't work as intended.  False always gets treated as true, so `.then(...)` always gets executed.

Polars does not throw any error or show any bugs, it just blindly doesn't read the bool correctly.

### Log output

```shell
No error.
```

### Issue description

It could be that I'm not using Polars in the ideal way, which causes me to hit unexpected behavior.  Here's a 102 of what I'm doing:

```
        # Checks entire dataframe if date resolution or datetime resolution.
        is_datetime = (df.filter(col.Date == col.Date.cast(pl.Date).cast(pl.Datetime))
                       .limit(1).collect().is_empty())

        date = (pl.when(id_datetime)
                .then(col.Date.dt.convert_time_zone("America/New_York"))
                .otherwise(col.Date.cast(pl.Date)))
```

I'm checking the entire dataframe to identify the type the column will eventually be.  This is inefficient.  Initially I tried to use `any` and `all` in a `when` conditional statement, but I couldn't figure out how to scan all rows that way, so I resorted to doing it this way, which is where I found the bug in `when`.

I believe this is a bug because the documentation says:

>predicates

>    Condition(s) that must be met in order to apply the subsequent statement. **Accepts one or more boolean expressions, which are implicitly combined with &.**

### Expected behavior

I don't know if it should throw an error and I'm using it incorrectly or it should accept a bool correctly.

If I had a choice I'd prefer `when` accepts standard booleans, not just polars expressions.  Alternatively throwing an error works too.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Linux-6.10.3-1-default-x86_64-with-glibc2.40
Python:               3.12.3 (main, Apr 10 2024, 14:51:56) [GCC]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.0.1
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Julian-J-S** [comment]
You are indeed using it "wrong".
my advice for you would be to spend a few days learning the basics of DataFrames. Basic conceps and how they work.
A good place to start is also the polars user guide: https://docs.pola.rs/

Your `date` "thing" is called an "Expression" that activately does aboslutely nothing until it is USED in some way

Example
```python
# does NOTHING; I do not even have data
expr = pl.when(pl.col('val') > 3).then(100).otherwise(0).alias('new_val')

# create data
df = pl.DataFrame({'val': [1, 2, 3, 4, 5]})

# USE expression
df.with_columns(expr)

shape: (5, 2)
┌─────┬─────────┐
│ val ┆ new_val │
│ --- ┆ ---     │
│ i64 ┆ i32     │
╞═════╪═════════╡
│ 1   ┆ 0       │
│ 2   ┆ 0       │
│ 3   ┆ 0       │
│ 4   ┆ 100     │
│ 5   ┆ 100     │
└─────┴─────────┘
```

**Comment by cmdlineluser** [comment]
Polars evaluates all when/then branches in parallel:

- https://github.com/pola-rs/polars/issues/17405

(The result is then "masked")

```python
df = pl.DataFrame({"foo": ["one", "two"]})

df.with_columns(
    pl.when(False).then(pl.col.foo.cast(pl.Int64)) # cast runs
)

# InvalidOperationError: 
# conversion from `str` to `i64` failed in column 'foo' for 3 out of 3 values: 
# ["one", "two"]
```

**Comment by ritchie46** [comment]
I will close this as there is no action on our side. Discussion is free to continue.

**Comment by ddouglas87** [comment]
I still think that it should throw an error on unsupported types being put in.  That's the point of this bug.  The bug isn't that it doesn't support expressions.  This is clearly stated in the documentation.  The bug is that it accepts unsupported types and doesn't throw an error.  As long as this bug persists it's going to cause lots of issues to new users all over the world.  This bug is very "C++" in that it's letting you shoot yourself in the foot.  When shooting yourself in the foot can be minimized and removed, shouldn't it be?

**Comment by cmdlineluser** [comment]
The types are supported.

It's just that Polars will always execute the `.then()` branches:

> Polars computes **all expressions** passed to when-then-otherwise in parallel and filters **afterwards**.

```python
df.with_columns(
    pl.when(pl.lit(1) == pl.lit(2))
      .then(pl.col.foo.cast(pl.Int64))
)

# InvalidOperationError: conversion from `str` to `i64` failed in column 'foo' for 3 out of 3 values: ["one", "two", "three"]
```

It is not behaviour that is specific to `False` - like in your example.

It sounds like you may be asking for:

- https://github.com/pola-rs/polars/issues/17601

**Comment by ddouglas87** [comment]
I see!  Thanks for the clarification.  #17601 is more about changing the behavior or creating a new method.  My issue I now know is that the documentation does not correctly represent what is happening and is misleading.  Without your clarification there was no way for me to know this is how `when` works.

Here's some example changes to the documentation that would explain it better:

>Expression similar to an if-else statement in Python. Always initiated by a pl.when(<condition>).then(<value if condition>)., and optionally followed by chaining one or more .when(<condition>).then(<value>) statements.

This could read something like, "Expression similar to an if-else statement in Python, except the execution order is reversed.  Always execute `.then(<value>)` first, then `.when(<condition>)` determines if result is passed, and if when is not true then `.otherwise(<value if not condition>)` is calculated and returned."

Likewise the warning:

>Polars computes all expressions passed to when-then-otherwise in parallel and filters afterwards. This means each expression must be valid on its own, regardless of the conditions in the when-then-otherwise chain.

This warning is easy to misunderstand.  E.g. in the example I gave when I created the issue `col.Date.dt.convert_time_zone("America/New_York")` is a valid expression on its own.  Instead the warning could say "Polars computes the `.then(<value>)` first before checking `.when(<condition>)`.  This is done because `.then(<value>)` is done in parallel and then filtered afterwards.  If `.then(<value>)` mutates the dataframe it will always change the dataframe even when `.when(<condition>)` is false."

I'm sure this could be worded even better than I'm suggesting here.  I never would have known how it worked from the documentation alone without the clarification from you, or looking at the source code directly.  Because of this I feel like the documentation is more than confusing, it's misleading.  The documentation implies it's an if-else statement, without immediate clarification.  It's not an if-else statement, it's order of operations is backwards from that of an if-else statement.

**Comment by cmdlineluser** [comment]
Yeah, the docs do appear to be somewhat ambiguous.

I'm not sure why it doesn't explicitly state that all `then()` branches are executed.

Having a code example for this specific behaviour also seems like a useful example to have in the docs.

The devs do welcome doc improvements if you are interested in submitting a PR.

**Comment by ddouglas87** [comment]
>The devs do welcome doc improvements if you are interested in submitting a PR.

I'm a bit nervous.  Do you think my suggested changes above are good enough?  I'm not great with English and I'm not a Software Engineer so I feel it would be better suited for someone else.

I think the idea of adding an example (or two) is a fantastic idea.  Great idea!
