### ISSUE TITLE
DataFrame rendering broken on Android

### ISSUE THREAD

**Issue by cbrnr** [pola-rs/polars#18140]
### Description

For some reason, DataFrame rendering seems to be broken on Android. I've tried this on two phones (Xiaomi 9T, Pixel 6a) and a tablet (Lenovo Tab P11 Pro) on Chrome and Brave (which presumably uses the Chromium engine), and this is how it looks like:

![Screenshot_2024-08-12-10-08-10-006](https://github.com/user-attachments/assets/5d140595-a0fa-48bc-a326-48085c964e26)

I cannot reproduce this on macOS when spoofing the user agent. I'm not sure if this is something Polars can fix, or if it's an upstream issue (Material for MkDocs?), but it sure is annoying and makes it very difficult to read the docs on mobile.

**Comment by ritchie46** [comment]
closed as duplicate
