### ISSUE TITLE
Do not cast to supertypes for `is_between`

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#18144]
### Description

This can lead to unexpected behavior:

```python
pl.select(pl.lit(2).is_between(pl.lit("11"), pl.lit("33")))
# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ bool    │
# ╞═════════╡
# │ true    │
# └─────────┘
```

Silently adding a cast step can also cause optimizations such as predicate pushdown to unexpectedly fail (e.g. https://github.com/pola-rs/polars/issues/17045)

**Comment by ritchie46** [comment]
I will fix this in a bug fix. This is never intended behavior.
