### ISSUE TITLE
Add DRY equivalent for Series

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#18150]
### Description

One thing nice about polars is the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) that it [follows](https://docs.pola.rs/user-guide/expressions/column-selections/#expression-expansion). This is unfortunately not the case for polars Series (and in general I feel that the support for Series are extremely limited). For example, if one has a `very_long_name_series: pl.Series` (of `int`), and one wants to filter the elements such that the remaining values are all within [100, 200] and is a multiple of 3, 5 or 7. One has to write:
```python
very_long_name_series.filter(
    very_long_name_series.is_between(100, 200)
    & (very_long_name_series % 3 == 0)
    & (very_long_name_series % 5 == 0)
    & (very_long_name_series % 7 == 0)
)
```

Ideally we should allow a symbolic marker to denote the "element" of the Series, like what `pl.col` does for a DataFrame, as suggested by [this issue report](https://github.com/pola-rs/polars/issues/13772) earlier. One should be able to write the following to make it elegant:
```python
very_long_name_series.filter(
    pl.element().is_between(100, 200)
    & (pl.element() % 3 == 0)
    & (pl.element() % 5 == 0)
    & (pl.element() % 7 == 0)
)
```
(call it `element` or something else, there needs to be such a thing)

I think the original [issue report](https://github.com/pola-rs/polars/issues/13772) is very valuable, but it didn't draw enough attention and no progress was updated for more than half a year. Hence I'm reiterating this item. I think this is quite essential to make `pl.Series` better and more aligned with the DataFrame usages as well as the general polars principle design philosophy.

**Comment by MarcoGorelli** [comment]
Thanks @liufeimath for the report

I was going to reply "`pipe` is your friend", but it looks like it's not implemented for Series. Because then you could just do

```python
very_long_name_series.pipe(lambda s: s.filter(s.is_between(100, 200), s%3 == 0))
```

**Comment by MarcoGorelli** [comment]
In fact, that was rejected in https://github.com/pola-rs/polars/issues/14032

**Comment by liufeimath** [comment]
Thanks for the reply and discussion! I think the lambda syntax looks a bit ugly even if we have the pipe. Same reason that you would want the native `DataFrame.filter` (which is nicely implemented today) supporting natural polars expression syntaxes, rather than some general `filter` function that takes in an arbitrary lambda that transforms each row into a boolean (let alone the performance reasons to not do it).Ideally `pl.Series.filter` can be as elegant as the `pl.DataFram.filter` which supports native polars expression syntaxes. That is unfortunately not the case to day, and this argument applies to Series v.s. DataFrame in many other aspects as well. I feel in general that Series is not the "first-class citizen" as DataFrame is in the polars ecosystem today (but it should be in my opinion).

**Comment by s-banach** [comment]
Just write `s = very_long_name_series` and then write everything in terms of `s`...

**Comment by liufeimath** [comment]
> Just write `s = very_long_name_series` and then write everything in terms of `s`...

Don't. Don't. Don't. By the same argument I could say why not just sticking to pandas and write things like `df[(df.col1 == "a") & (df.col2 == "b") & <bla bla bla>]` ? Let just admit that it's bad syntax. Repeating yourself is repeating yourself, and it's just ugly. It doesn't matter whether it's a `very_long_name_series` or a single-letter named object.

**Comment by s-banach** [comment]
I agree that my suggestion has two deficiencies:
- Python doesn't have scope blocks, so the throwaway variable `s` pollutes the scope.
- Eagerly evaluating each predicate of `s` precludes any optimization.

But I don't think DRY has anything to do with it. Repeating `s` is a lot less repetition than repeating `pl.element()`.

**Comment by MarcoGorelli** [comment]
hi @liufeimath - if you specifically want `pl.element()` in Series.filter, then how is this different from #13772? closing in favour of that one then, but thanks for your request

**Comment by liufeimath** [comment]
> hi @liufeimath - if you specifically want `pl.element()` in Series.filter, then how is this different from #13772? closing in favour of that one then, but thanks for your request

Sure, but can we give some updates on the previous ticket?
