### ISSUE TITLE
Example code for `group_by` iteration is wrong

### ISSUE THREAD

**Issue by rosstitmarsh** [pola-rs/polars#18168]
### Description

The output of the `GroupBy` iteration was changed to always return a tuple as is correctly documented here https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.dataframe.group_by.GroupBy.__iter__.html

The invalid old output is still shown in the example on the `DataFrame.group_by` page.

https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.group_by.html

It has not been picked up by the doc tests because it is told to skip this example, I presume because it would fail without `maintain_order=True`.

https://github.com/pola-rs/polars/blob/3c5b11e19c3a744a69ebba338bc3f78aa1091ae0/py-polars/polars/dataframe/frame.py#L5810-L5841

### Link

https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.group_by.html

**Comment by MarcoGorelli** [comment]
thanks @rosstitmarsh for the report - fancy submitting a fix?
