### ISSUE TITLE
Add `expr.scatter`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#18167]
### Description

This is a fairly common operation that does not lend itself well to when/then chains if the number of indexes is large. In the [docs for `Series.scatter`](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.scatter.html), it's mentioned that `scatter` is an anti-pattern, due to the inability to parallelize the operation, but this places an undue burden on the user to write a really long sequence of when/then chains.

The `scatter` expression could always be transformed under the hood. For example, the following two could be equivalent operations:

```python
import polars as pl
from polars import col, when

df = pl.DataFrame({
    "a": [1, 2, 3, 4, 5],
    "b": ["a", "b", "c", "d", "e"],
})

# Current suggested usage
df.with_columns(
    when(pl.int_range(pl.len()) == 0).then(97)
    .when(pl.int_range(pl.len()) == 1).then(98)
    .when(pl.int_range(pl.len()) == 2).then(99)
    .otherwise(col("a"))
    .alias("a")
)
# shape: (5, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ str │
# ╞═════╪═════╡
# │ 97  ┆ a   │
# │ 98  ┆ b   │
# │ 99  ┆ c   │
# │ 4   ┆ d   │
# │ 5   ┆ e   │
# └─────┴─────┘

# Proposed usage
df.select(col("a").scatter([0, 1, 2], [97, 98, 99]))
```

**Comment by etiennebacher** [comment]
Looks like a duplicate of https://github.com/pola-rs/polars/issues/13087

**Comment by mcrumiller** [comment]
Indeed, it is, thanks @etiennebacher. Although I do wish there was a way to "bump" old issues, which tend to become forgotten.
