### ISSUE TITLE
ParquetWriter<CloudWriter> hangs when uploading to S3

### ISSUE THREAD

**Issue by ByteNybbler** [pola-rs/polars#18175]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::io::cloud::CloudWriter;
use polars::prelude::*;

#[tokio::main]
async fn main() {
    let output_uri = "s3://bucket/out.parquet";
    let writer = CloudWriter::new(output_uri, None).await.unwrap();
    let writer = ParquetWriter::new(writer);
    let mut df = df![
        "ints" => [1, 2, 3]
    ].unwrap();
    tokio::task::spawn_blocking(move || {
        eprintln!("About to call writer.finish");
        writer.finish(&mut df).unwrap();
    }).await.unwrap();
    eprintln!("End of program"); // Never gets reached
}
```

### Log output

```
About to call writer.finish
```

### Issue description

When using `ParquetWriter<CloudWriter>` to upload to S3, calling the `finish` method causes the application to hang indefinitely. This didn't happen in older Polars versions, so it seems to be a regression.

This bug might be specific to S3 uploads. It does not occur when using a URI that points to the local disk.

### Expected behavior

Calling `ParquetWriter<CloudWriter>::finish` should not cause the application to freeze when an S3 URI is used.

### Installed versions

<details>

polars = { version = "0.41.3", features = ["parquet", "cloud", "aws"] }

</details>

**Comment by krasnobaev** [comment]
Hello, I just tried to reproduce problem. Can confirm that polars `ParquetWriter` in  versions v0.41.0 and v0.41.3 doesn't publish the parquet file to an S3 bucket.

However, versions v0.40.0, v0.42.0 and current `main` branch works fine.

**Comment by ByteNybbler** [comment]
Yes, it now works fine for me on v0.42.0. Thanks for testing!
