### ISSUE TITLE
SQL expression panics on invalid query

### ISSUE THREAD

**Issue by daBlesr** [pola-rs/polars#18172]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
let mut sql_context = SQLContext::new();
let df = df!(
    "a" => &["x", "x", "x", "y", "y"],
).unwrap();

sql_context.register("df", df.clone().lazy());
sql_context.execute("select from df where a = 'x'");
```

### Log output

```shell
thread 'main' panicked at polars-sql-0.41.3/src/sql_expr.rs:561:88:
called `Option::unwrap()` on a `None` value
```

### Issue description

Above simple sql code gives a panic exception from [this part of the code in sql expr](https://github.com/pola-rs/polars/blob/b5852932cd0a450676ceb3acfe636d91211b13c5/crates/polars-sql/src/sql_expr.rs#L563)

### Expected behavior

It should not panic but return why the query is invalid.

### Installed versions

<details>

polars = { version = "0.41.3", features = ["sql", "polars-sql", "lazy"]}

</details>

**Comment by alexander-beedie** [comment]
FYI: for Rust this is fixed in the upcoming `0.42.0` release (and is already fixed in the current Python release). The above query results in a "SQLInterface" parser error instead, with a suitable message (that an expression is expected) 👍 
```python
# SQLInterfaceError: sql parser error: 
#   Expected an expression, found: from at Line: 1, Column: 13
```

**Comment by alexander-beedie** [comment]
FYI: `0.42.0` just released; give it a go?

**Comment by daBlesr** [comment]
Hi @alexander-beedie , yes I verified and with version 0.42.0 it no longer panics,  but gives an error.
