### ISSUE TITLE
how can we resample in polars?

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1820]
Hi;

Probably you know. But I'm copying documentation of resample method.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html

I'm not sure whether it is possible to apply resample in polars. Probably there are some ways to do this. But it include more than one step. To this end I will ask two different approaches.

First one is how to apply python resample in groupby (by using map or apply) Probable it will be slow because it will need lamda function but it will be fast way to write.

Second one is how to do this type of calculation in polar by using polars method. (probable it is the fastest way)

If Polars does not have similar function like resample, are you planning to add a method to simplify the calculation.

Thanks.

**Comment by ritchie46** [comment]
Polars has a `downsample` and an `upsample`. Can you give a small example of what you want to achieve?

**Comment by hakantekbas** [comment]
I will copy existing example in pandas

> start, end = '2000-10-01 23:30:00', '2000-10-02 00:30:00'
> rng = pd.date_range(start, end, freq='7min')
> ts = pd.Series(np.arange(len(rng)) * 3, index=rng)
> 
> ts.resample('17min', origin='2000-01-01').sum()

> 2000-10-01 23:24:00     3
> 2000-10-01 23:41:00    15
> 2000-10-01 23:58:00    45
> 2000-10-02 00:15:00    45
> Freq: 17T, dtype: int64


Some parameters in resample can be used in some cases. You pointed two methods upsample and downsample. I did not notice these two methods beforehand. It will cover many cases but when I need to use some parameters how can I apply python method in groupby?

**Comment by koaning** [comment]
@ritchie46 can say for sure, but I think this is related to the fact that polars doesn't supply an index column. Without one, the resample method does not work "as in". An alternative would be to implement a `.pipe()`-esque method that can handle the resampling.

**Comment by ritchie46** [comment]
yes, we can do something like this:

```python
seven_minutes = 7 * 60

(pl.date_range(
    low=datetime(2000, 10, 1, 23, 30), 
    high=datetime(2000, 10, 2, 0, 30), 
    interval=timedelta(seconds=seven_minutes), 
    name="date_range")
 .to_frame()
 .downsample("date_range", rule="minute", n=17)
 .first()
)
```

```
shape: (5, 1)
┌─────────────────────┐
│ date_range          │
│ ---                 │
│ datetime            │
╞═════════════════════╡
│ 2000-10-01 23:18:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-10-01 23:35:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-10-01 23:35:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-10-01 23:52:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-10-02 00:09:00 │
```

But the output is not correct. So I think we need to change the bucketing algorithm. I also don't like that it doesn't use the expresion API. I ideally have something like `pl.col("datetime").dt.buckets(..)` which you can then use in a groupby operation or window expression. 

So to be continued...

**Comment by ritchie46** [comment]
> ... as I write this sentence I'm thinking that a utils library with .pipe()-esque functions might be a nice idea. This'd allow much of the pandas functionality without having to implement anything in the core library.

... lego? :smile:

**Comment by koaning** [comment]
Hahaha, yeah I was actually trying to avoid re-using that name for ... reasons. Anybody keen to learn, please run; 

```python
from sklego import this
```

I've actually been contemplating to call it "valve" because it's a suite of pipeline tools, unfortunately that name seems taken. 

The idea for such a toolkit is that one that might have a polars/dask/pandas implementation for each common step. The nice thing is that it'd also be able to serve as a benchmarking suite. Things like `sessionize` would fit very well there. 

Anyway. That's another thread altogether and it'd be better to start a package only when there's a real documented pain that could be addressed. Just to check though, would it make sense to host such a package here?

**Comment by hakantekbas** [comment]
pl.col("datetime").dt.buckets(..)  will be better. What kind of parameters will it support?

**Comment by ritchie46** [comment]
> pl.col("datetime").dt.buckets(..) will be better. What kind of parameters will it support?

See: #1859

You can pass a python `timedelta`. The date values will be assinged to the lower bucket value. 

> Anyway. That's another thread altogether and it'd be better to start a package only when there's a real documented pain that could be addressed. Just to check though, would it make sense to host such a package here?

Yeah, it could be under a polar-rs namespace. But then it does raise the question, when does something has to be in core and when in utils?

**Comment by ritchie46** [comment]
Ok, the buckets seem to work, but can someone explain to me what pandas actually does? I cannot make sense of the sum here.

**Comment by hakantekbas** [comment]
I'm  not a fan of pandas due to slowness. But your fast actions and speed of polars is really awesome.

**Comment by koaning** [comment]
> Yeah, it could be under a polar-rs namespace. But then it does raise the question of when does something has to be in core and when in utils?

And when is something in utils and when is it too specific even for that?

**Comment by ritchie46** [comment]
With the landing `groupby_dynamic` we can now downsample and use the whole expression API for our aggregations. Meaning we can `resample` by either.

* upsampling
* downsampling
* first upsample and then downsample

Let's go through an example:

```python
df = pl.DataFrame(
    {"time": pl.date_range(low=datetime(2021, 12, 16), high=datetime(2021, 12, 16, 3), interval="30m"),
     "groups": ["a", "a", "a", "b", "b", "a", "a"],
     "values": [1., 2., 3., 4., 5., 6., 7.]
    })

print(df)
```
```
shape: (7, 3)
┌─────────────────────┬────────┬────────┐
│ time                ┆ groups ┆ values │
│ ---                 ┆ ---    ┆ ---    │
│ datetime            ┆ str    ┆ f64    │
╞═════════════════════╪════════╪════════╡
│ 2021-12-16 00:00:00 ┆ a      ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:30:00 ┆ a      ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 01:00:00 ┆ a      ┆ 3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 01:30:00 ┆ b      ┆ 4      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:00:00 ┆ b      ┆ 5      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:30:00 ┆ a      ┆ 6      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 03:00:00 ┆ a      ┆ 7      │
└─────────────────────┴────────┴────────┘

```

# Upsampling
Upsampling can be done by defining an interval. This will yield a `DataFrame` with nulls, which can then be filled with a fill strategy or interpolation.

```python
df.upsample("time", "15m").fill_null("forward")
```

```
shape: (13, 3)
┌─────────────────────┬────────┬────────┐
│ time                ┆ groups ┆ values │
│ ---                 ┆ ---    ┆ ---    │
│ datetime            ┆ str    ┆ f64    │
╞═════════════════════╪════════╪════════╡
│ 2021-12-16 00:00:00 ┆ a      ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:15:00 ┆ a      ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:30:00 ┆ a      ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:45:00 ┆ a      ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ ...                 ┆ ...    ┆ ...    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:00:00 ┆ b      ┆ 5      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:15:00 ┆ b      ┆ 5      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:30:00 ┆ a      ┆ 6      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:45:00 ┆ a      ┆ 6      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 03:00:00 ┆ a      ┆ 7      │
└─────────────────────┴────────┴────────┘

```

```python
(df.upsample("time", "15m")
   .interpolate()
   .fill_null("forward")  # string columns cannot be interpolated
)
```

```
shape: (13, 3)
┌─────────────────────┬────────┬────────┐
│ time                ┆ groups ┆ values │
│ ---                 ┆ ---    ┆ ---    │
│ datetime            ┆ str    ┆ f64    │
╞═════════════════════╪════════╪════════╡
│ 2021-12-16 00:00:00 ┆ a      ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:15:00 ┆ a      ┆ 1.5    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:30:00 ┆ a      ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:45:00 ┆ a      ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ ...                 ┆ ...    ┆ ...    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:00:00 ┆ b      ┆ 5      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:15:00 ┆ b      ┆ 3.5    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:30:00 ┆ a      ┆ 6      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:45:00 ┆ a      ┆ 4      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 03:00:00 ┆ a      ┆ 7      │
└─────────────────────┴────────┴────────┘

```

# Downsampling

This is the powerful one, because we can also combine this with normal groupby keys. Having a virtual moving window over the time series (grouped by one or multiple keys) that can be aggregated with the expression API.

```
(df.groupby_dynamic(
    time_column="time", 
    every="1h", 
    closed="both", 
    by="groups", 
    include_boundaries=True
)
    .agg([
        pl.col('time').count(), 
        pl.col("time").max(),
        pl.sum("values"),
    ]))
```
```
shape: (4, 7)
┌────────┬────────────┬────────────┬────────────┬────────────┬─────────────────────┬────────────┐
│ groups ┆ _lower_bou ┆ _upper_bou ┆ time       ┆ time_count ┆ time_max            ┆ values_sum │
│ ---    ┆ ndary      ┆ ndary      ┆ ---        ┆ ---        ┆ ---                 ┆ ---        │
│ str    ┆ ---        ┆ ---        ┆ datetime   ┆ u32        ┆ datetime            ┆ f64        │
│        ┆ datetime   ┆ datetime   ┆            ┆            ┆                     ┆            │
╞════════╪════════════╪════════════╪════════════╪════════════╪═════════════════════╪════════════╡
│ a      ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2021-12-16 ┆ 3          ┆ 2021-12-16 01:00:00 ┆ 6          │
│        ┆ 00:00:00   ┆ 01:00:00   ┆ 00:00:00   ┆            ┆                     ┆            │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ a      ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2021-12-16 ┆ 1          ┆ 2021-12-16 00:00:00 ┆ 1          │
│        ┆ 01:00:00   ┆ 02:00:00   ┆ 00:00:00   ┆            ┆                     ┆            │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ a      ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2          ┆ 2021-12-16 03:00:00 ┆ 13         │
│        ┆ 02:00:00   ┆ 03:00:00   ┆ 00:00:00   ┆            ┆                     ┆            │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b      ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2021-12-16 ┆ 2          ┆ 2021-12-16 02:00:00 ┆ 9          │
│        ┆ 01:00:00   ┆ 02:00:00   ┆ 01:00:00   ┆            ┆                     ┆            │
└────────┴────────────┴────────────┴────────────┴────────────┴─────────────────────┴────────────┘
```

**Comment by zundertj** [comment]
Closing, as this functionality has been added now. Please open a new issue if you find something is missing.
