### ISSUE TITLE
Request to return LazyFrame for pl.from_arrow and more

### ISSUE THREAD

**Issue by jakorostami** [pola-rs/polars#18212]
### Description

Hi.

I would like to request that pl.from_* functions also returns LazyFrames so we can read larger than memory without ever reading them to DataFrames. 

An example with BigQuery in Python. It first reads into DataFrame and then into LazyFrame. But it would be great to have an option `return_lazy=True` that returns lazyframe instead of dataframe.

```
import polars as pl
from google.cloud.bigquery import Client

client = Client()

some_query = ””

df_rows = client.query(some_query).result()

df = pl.from_arrow(  df_rows.to_arrow()  ).lazy()
```

What I want:
```
import polars as pl
from google.cloud.bigquery import Client

client = Client()

some_query = ””

df_rows = client.query(some_query).result()

df = pl.from_arrow(  df_rows.to_arrow(), return_lazy=True  )

```

**Comment by moritzwilksch** [comment]
After calling `.to_arrow()` on whatever `df_rows` is here the entire data already resides in memory in the arrow format. Therefore, there would be no difference in performance or memory usage between the two options you suggest.

**Comment by deanm0000** [comment]
@moritzwilksch is 100% right here. There's no copy between arrow and polars so if it fits as an arrow Table then making it a polars DataFrame doesn't take any extra memory. From from a semantics perspective, polars aims to have a clean API that doesn't have multiple ways to do the same thing so adding a `return_lazy` parameter to `from_arrow` when chaining `lazy` already works goes against that aim.

As an aside, and I apologize in advance if this comes off rudely but, why not just do the query in bigquery which has scalable compute and memory resources?
