### ISSUE TITLE
`dt.round()` slow/fast path use different rounding

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#18239]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

@MarcoGorelli 
This is an example case produced in the hypothesis test for `test_dt_round_fast_path_vs_slow_path`:

```python
from datetime import datetime
import polars as pl

datetimes = [
    datetime(1980, 1, 1, 0, 0, 0, 0),
    datetime(1969, 1, 1, 0, 0, 0, 1),
    datetime(1969, 1, 1, 0, 0, 0, 2),
    datetime(1969, 1, 1, 0, 0, 0, 3),
    datetime(1969, 1, 1, 0, 0, 0, 4),
    datetime(1969, 1, 1, 0, 0, 0, 5),
]
every = "2us"
s = pl.Series(datetimes)

out = pl.select(
    s.dt.round(every).alias("fast"),
    s.dt.round(pl.Series([every] * len(datetimes))).alias("slow"),
)

print(out)
```
```shell
shape: (6, 2)
┌────────────────────────────┬────────────────────────────┐
│ fast                       ┆ slow                       │
│ ---                        ┆ ---                        │
│ datetime[μs]               ┆ datetime[μs]               │
╞════════════════════════════╪════════════════════════════╡
│ 1980-01-01 00:00:00        ┆ 1980-01-01 00:00:00        │
│ 1969-01-01 00:00:00        ┆ 1969-01-01 00:00:00.000002 │
│ 1969-01-01 00:00:00.000002 ┆ 1969-01-01 00:00:00.000002 │
│ 1969-01-01 00:00:00.000002 ┆ 1969-01-01 00:00:00.000004 │
│ 1969-01-01 00:00:00.000004 ┆ 1969-01-01 00:00:00.000004 │
│ 1969-01-01 00:00:00.000004 ┆ 1969-01-01 00:00:00.000006 │
└────────────────────────────┴────────────────────────────┘
```

### Issue description

The fast path rounds down and the slow path rounds up.

### Expected behavior

Both should use same rounding.

### Installed versions

main

**Comment by mcrumiller** [comment]
The different rounding routines are here:

* fast path: https://github.com/pola-rs/polars/blob/main/crates/polars-time/src/round.rs#L39-L41
* slow path: https://github.com/pola-rs/polars/blob/main/crates/polars-time/src/windows/window.rs#L85-L89

Do we want to:

1) round toward zero;
2) round away from zero;
3) round toward the even digit, as most rounding functions do?

Probably #3, right?

**Comment by MarcoGorelli** [comment]
thanks @mcrumiller for spotting this! yeah this needs fixing

in `Series.round` Polars rounds away from zero, so perpahs `.dt.round` should be consistent with that
