### ISSUE TITLE
Segmentation fault on left joining empty DataFrame Python

### ISSUE THREAD

**Issue by Andarius** [pola-rs/polars#1824]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.22

#### What operating system are you using polars on?

Docker image [python:3.9-buster](https://hub.docker.com/_/python)

#### Describe your bug.

When joining 2 dataframes, if the 2nd one is empty and has more that 2 columns, the join raises a Segmentation fault

#### What are the steps to reproduce the behavior?

Run the following
```python
import polars as pl

def main():
    df1 = pl.DataFrame({'a': [0], 'b': [1]}).lazy()
    df2 = pl.DataFrame({'a': [], 'd': [],  'e': []}).lazy()
    df2 = df2.with_column(pl.col('a').cast(int))
    res = df1.join(df2, on=['a'], how='left')
    print(res.collect())

if __name__ == '__main__':
    main()
```

To reproduce with docker:
 - Run `docker run -it --rm -v ./test.py:/test.py:ro --entrypoint /bin/bash python:3.9-buster`
 - Inside the docker image, run `pip install polars` then `python /test.py`

#### What is the actual behavior?
```
root@f087335fa7b0:/# python /test.py 
Segmentation fault (core dumped)
```

#### What is the expected behavior?

```python
root@f087335fa7b0:/# python /test.py 
shape: (1, 4)
┌─────┬─────┬──────┬──────┐
│ a   ┆ b   ┆ d    ┆ e    │
│ --- ┆ --- ┆ ---  ┆ ---  │
│ i64 ┆ i64 ┆ f32  ┆ f32  │
╞═════╪═════╪══════╪══════╡
│ 0   ┆ 1   ┆ null ┆ null │
└─────┴─────┴──────┴──────┘

```

**Comment by ritchie46** [comment]
Thanks for the issue report @Andarius. I will fix it.

**Comment by Andarius** [comment]
@ritchie46 After some digging, it seems that the error has been introduced between **0.10.15** and **0.10.16**

**Comment by ritchie46** [comment]
@Andarius Thanks, found it!

**Comment by Andarius** [comment]
@ritchie46 Thanks for the really quick fix and this awesome lib!
