### ISSUE TITLE
Inconsistent rolling results when using temporal windows

### ISSUE THREAD

**Issue by surajjamodkar** [pola-rs/polars#18248]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# create df and some rolling features with month end dates
dates = pd.date_range('2021-01-01', periods=6, freq='M')
y = list(range(6))
df = pl.DataFrame({"ds": dates, "y": y})
out_dates = df.rolling(index_column="ds", period="3mo").agg(
    [
        pl.min("ds").alias("min_ds"),
        pl.max("ds").alias("max_ds"),
    ]
)
```

```python
# create df and some rolling features with integers 
y = list(range(6))
dates = y.copy()
df = pl.DataFrame({"ds": dates, "y": y})
out_no_dates = df.rolling(index_column="ds", period="3i").agg(
    [
        pl.min("ds").alias("min_ds"),
        pl.max("ds").alias("max_ds"),
    ]
)
```
We would see that out_dates doesn't consider 2021-02-28 as window start for 2021-04-30. We can compare the behaviors with out_no_dates has correct min and max (range of values).

### Issue description

When using rolling, the window boundaries are being correctly calculated. 
With integer index columns, the window considered is as expected, while using the month end dates result in January End being start for April and March index windows. We do not see February end being start of any window.   

![image](https://github.com/user-attachments/assets/a95a32ad-e41e-4afd-9172-ef7d67feedf4)

### Expected behavior

February end should be start (min_ds) of April End (ds) window.  

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.3
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @surajjamodkar for the report

this looks correct: the window for `2020-05-31` is `(2020-02-28, 2020-05-31]`, and so the earliest point which can be considered in it is `2020-03-31`

**Comment by MarcoGorelli** [comment]
closing then as this looks expected, but please do report any issues you find, thanks 🙏

**Comment by surajjamodkar** [comment]
I am talking about the april window. Shouldn't the  the window for 2021-04-30 be (2021-01-31, 2021-04-39], and so the earliest point which should be considered is 2021-02-28?

**Comment by MarcoGorelli** [comment]
it would be `(2021-01-30, 2021-04-30]`, so the earliest point is `2021-01-31`

**Comment by surajjamodkar** [comment]
Understood. Thanks! Have a nice day!
