### ISSUE TITLE
maintain_order is a gotcha. Make it true by default?

### ISSUE THREAD

**Issue by phildawes** [pola-rs/polars#18275]
### Description

I've found having to remember 'maintain_order' is a bit of a gotcha for polars, esp when working with timeseries.

E.g. it's easy to mistakenly do something like:
`
    mytimeseries.group_by(day).first()
`
Is there any appetite for making maintain_order=True the default for group_by, unique etc?

**Comment by cmdlineluser** [comment]
Writing it in terms of `filter` may also be an option.

```python
df.filter(pl.col("day").is_first_distinct())
```

- [`.is_first_distinct()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.is_first_distinct.html#polars-expr-is-first-distinct)

**Comment by ritchie46** [comment]
No, this is a constraint that is opt-in. It has very significant performance cost as the output needs to be sorted.

**Comment by MarcoGorelli** [comment]
I'd also suggest `group_by_dynamic` here
```
In [6]: df.group_by_dynamic('t', every='1d').agg(pl.all().first())
Out[6]:
shape: (3, 2)
┌────────────┬─────┐
│ t          ┆ a   │
│ ---        ┆ --- │
│ date       ┆ i64 │
╞════════════╪═════╡
│ 2020-01-01 ┆ 1   │
│ 2020-01-02 ┆ 2   │
│ 2020-01-03 ┆ 4   │
└────────────┴─────┘
```
