### ISSUE TITLE
Regex look-ahead/behind support

### ISSUE THREAD

**Issue by ThomasMAhern** [pola-rs/polars#18286]
### Description

I get:
`ComputeError: regex error: regex parse error: error: unrecognized flag`
when trying this regex (and other variations) likely due to the look-ahead and look-behind.

Would it be possible for polars to support this?

Example: 
```python
(pl.DataFrame({'column': 'The year 2023 is expected to be a good year for technology. The average income was $50,000 in 2020 year."'})
 .with_columns(extract = pl.col('column').str.extract_all(r'\b\d{4}(?= year\b)'))
)
```

**Comment by etiennebacher** [comment]
`str.extract_all()` uses the `regex` Rust crate under the hood. From [the docs](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.extract_all.html):

> **pattern:**  A valid regular expression pattern, compatible with the [regex crate](https://docs.rs/regex/latest/regex/).

And this crate doesn't support look-ahead/behind. From [the crate's docs](https://docs.rs/regex/latest/regex/):

> The regex syntax supported by this crate is similar to other regex engines, but it lacks several features that are not known how to implement efficiently. This includes, but is not limited to, look-around and backreferences.

**Comment by ion-elgreco** [comment]
There is the fancy-regex crate which could be used. For non look Around stuff it's using the regex crate

**Comment by ThomasMAhern** [comment]
Ahh, thanks, didn't realize that. That's good to know.

**Comment by deanm0000** [comment]
This is probably a good candidate for a plugin https://marcogorelli.github.io/polars-plugins-tutorial/prerequisites/

**Comment by orlp** [comment]
Yes, we would rather see this in a plugin. Most of the time you don't even need lookahead/behind, and we prefer to be limited to efficiently executable regexes in the default API.

**Comment by deanm0000** [comment]
One last note/trick/tip. You can often get the same effect as a look around by chaining a replace. For instance just let ' year' be part of the search and then replace it with ''.

```
(pl.DataFrame({'column': 'The year 2023 is expected to be a good year for technology. The average income was $50,000 in 2020 year."'})
 .with_columns(extract = pl.col('column').str.extract_all(r'\b\d{4} year\b').list.eval(pl.element().str.replace_all(" year","")))
)
shape: (1, 2)
┌─────────────────────────────────────────────────────┬───────────┐
│ column                                              ┆ extract   │
│ ---                                                 ┆ ---       │
│ str                                                 ┆ list[str] │
╞═════════════════════════════════════════════════════╪═══════════╡
│ The year 2023 is expected to be a good year for te… ┆ ["2020"]  │
└─────────────────────────────────────────────────────┴───────────┘
```
