### ISSUE TITLE
Why do the two results differ with different sort orders before group_by?

### ISSUE THREAD

**Issue by shenrun** [pola-rs/polars#18295]
### Checks

- [X] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime as dt
import polars as pl

dates = [dt.date(2024, 1, 1) + dt.timedelta(days=i) for i in range(5)]
codes = ["a"] * 5 + ["b"] * 5
values = list(range(-2, 3)) + list(range(2, -3, -1))
df = pl.DataFrame({"date": dates * 2, "code": codes, "value": values})

result_1 = (
    df.sort(("date", "code"))
    .group_by("code", maintain_order=True)
    .agg(
        pl.col("value").ewm_mean(span=2, ignore_nulls=True)
        .tail(5)
        .filter(pl.col("value") > 0)
        .sum()
    )
)

result_2 = (
    df.sort(("code", "date"))
    .group_by("code", maintain_order=True)
    .agg(
        pl.col("value").ewm_mean(span=2, ignore_nulls=True)
        .tail(5)
        .filter(pl.col("value") > 0)
        .sum()
    )
)

print(result_1)
print(result_2)
```

### Log output

```shell
shape: (2, 2)
┌──────┬───────┐
│ code ┆ value │
│ ---  ┆ ---   │
│ str  ┆ f64   │
╞══════╪═══════╡
│ a    ┆ -0.7  │
│ b    ┆ 0.7   │
└──────┴───────┘
shape: (2, 2)
┌──────┬──────────┐
│ code ┆ value    │
│ ---  ┆ ---      │
│ str  ┆ f64      │
╞══════╪══════════╡
│ a    ┆ 2.070661 │
│ b    ┆ 3.25     │
└──────┴──────────┘
```

### Issue description

I’m encountering an issue where the two results (result_1 and result_2) differ based on the sort order before performing a group_by. In the first case, I sort by ("date", "code"), and in the second case by ("code", "date").

Both results are supposed to calculate the exponential moving average (EWM) of the value column, but with the sort order changed, the results are not the same. Could you please help me understand why this happens?

### Expected behavior

result_1.equals(result_2) is True

### Installed versions

<details>

```
--------Version info---------
Polars:               1.3.0
Index type:           UInt32
Platform:             Linux-5.3.0-28-generic-x86_64-with-glibc2.27
Python:               3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         1.5.8
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.4
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by shenrun** [comment]
Sorry, the correct version I use is listed bellow:
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-5.15.0-40-generic-x86_64-with-glibc2.35
Python:               3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.5.8
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.23
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

**Comment by ritchie46** [comment]
I don't understand your question. `ewm_mean` has different results if you have a different ordering. That makes sense right?

**Comment by shenrun** [comment]
Sure. But inside the group_by("code", maintain_order=True).agg() block, the value sequences are supposed to be sorted by date in both cases. Is my understanding correct?

**Comment by etiennebacher** [comment]
In case it helps, the discrepancy appears at the `.filter()` stage. If you remove the `filter()` and the subsequent functions, the two outputs are the same.

**Comment by wence-** [comment]
What does the `filter` phase mean? Is it meant to be "select only the positive values in the ewm_mean"? If so, that's not what it's doing. However, I think there is some kind of issue.

Consider:

```
import polars as pl
codes = ["a"] * 5 + ["b"] * 5
values = list(range(-2, 3)) + list(range(2, -3, -1))

df = pl.DataFrame({"code": codes, "value": values})

In [89]: df.group_by("code").agg(pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"), pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).filter(pl.col("value") > 0), (pl.col("value") > 0).alias("positive").tail(3))
Out[89]: 
shape: (2, 4)
┌──────┬──────────────────────────────┬────────────────────┬───────────────────────┐
│ code ┆ ewm                          ┆ value              ┆ positive              │
│ ---  ┆ ---                          ┆ ---                ┆ ---                   │
│ str  ┆ list[f64]                    ┆ list[f64]          ┆ list[bool]            │
╞══════╪══════════════════════════════╪════════════════════╪═══════════════════════╡
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ [-0.55, -1.520661] ┆ [false, false, false] │
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ []                 ┆ [false, true, true]   │
└──────┴──────────────────────────────┴────────────────────┴───────────────────────┘

In [90]: df.group_by("code").agg(pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"), pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).filter(pl.col("value") > 0), (pl.col("value") > 0).alias("positive").tail(3))
Out[90]: 
shape: (2, 4)
┌──────┬──────────────────────────────┬──────────────────┬───────────────────────┐
│ code ┆ ewm                          ┆ value            ┆ positive              │
│ ---  ┆ ---                          ┆ ---              ┆ ---                   │
│ str  ┆ list[f64]                    ┆ list[f64]        ┆ list[bool]            │
╞══════╪══════════════════════════════╪══════════════════╪═══════════════════════╡
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ [0.55, 1.520661] ┆ [false, true, true]   │
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ []               ┆ [false, false, false] │
└──────┴──────────────────────────────┴──────────────────┴───────────────────────┘
```

So it looks like the `filter` expression is not consistently applied to the constructed ewm_mean column?

**Comment by shenrun** [comment]
> What does the `filter` phase mean? Is it meant to be "select only the positive values in the ewm_mean"? If so, that's not what it's doing. However, I think there is some kind of issue.
> 
> Consider:
> 
> ```
> import polars as pl
> codes = ["a"] * 5 + ["b"] * 5
> values = list(range(-2, 3)) + list(range(2, -3, -1))
> 
> df = pl.DataFrame({"code": codes, "value": values})
> 
> In [89]: df.group_by("code").agg(pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"), pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).filter(pl.col("value") > 0), (pl.col("value") > 0).alias("positive").tail(3))
> Out[89]: 
> shape: (2, 4)
> ┌──────┬──────────────────────────────┬────────────────────┬───────────────────────┐
> │ code ┆ ewm                          ┆ value              ┆ positive              │
> │ ---  ┆ ---                          ┆ ---                ┆ ---                   │
> │ str  ┆ list[f64]                    ┆ list[f64]          ┆ list[bool]            │
> ╞══════╪══════════════════════════════╪════════════════════╪═══════════════════════╡
> │ b    ┆ [0.384615, -0.55, -1.520661] ┆ [-0.55, -1.520661] ┆ [false, false, false] │
> │ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ []                 ┆ [false, true, true]   │
> └──────┴──────────────────────────────┴────────────────────┴───────────────────────┘
> 
> In [90]: df.group_by("code").agg(pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"), pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).filter(pl.col("value") > 0), (pl.col("value") > 0).alias("positive").tail(3))
> Out[90]: 
> shape: (2, 4)
> ┌──────┬──────────────────────────────┬──────────────────┬───────────────────────┐
> │ code ┆ ewm                          ┆ value            ┆ positive              │
> │ ---  ┆ ---                          ┆ ---              ┆ ---                   │
> │ str  ┆ list[f64]                    ┆ list[f64]        ┆ list[bool]            │
> ╞══════╪══════════════════════════════╪══════════════════╪═══════════════════════╡
> │ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ [0.55, 1.520661] ┆ [false, true, true]   │
> │ b    ┆ [0.384615, -0.55, -1.520661] ┆ []               ┆ [false, false, false] │
> └──────┴──────────────────────────────┴──────────────────┴───────────────────────┘
> ```
> 
> So it looks like the `filter` expression is not consistently applied to the constructed ewm_mean column?

Sorry, is there any difference between your two inputs? And below is more detailed result after referring to your code:
``` python
import datetime as dt
import polars as pl

dates = [dt.date(2024, 1, 1) + dt.timedelta(days=i) for i in range(5)]
codes = ["a"] * 5 + ["b"] * 5
values = list(range(-2, 3)) + list(range(2, -3, -1))
df = pl.DataFrame({"date": dates * 2, "code": codes, "value": values})

result_1 = (
    df.sort(("date", "code"))
    .group_by("code", maintain_order=True)
    .agg(
        pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"),
        (pl.col("value") > 0).tail(3).alias("positive"),
        pl.col("value")
        .ewm_mean(span=2, ignore_nulls=True)
        .tail(3)
        .filter(pl.col("value") > 0)
        .alias("ewm_filtered"),
    )
)

result_2 = (
    df.sort(("code", "date"))
    .group_by("code", maintain_order=True)
    .agg(
        pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"),
        (pl.col("value") > 0).tail(3).alias("positive"),
        pl.col("value")
        .ewm_mean(span=2, ignore_nulls=True)
        .tail(3)
        .filter(pl.col("value") > 0)
        .alias("ewm_filtered"),
    )
)

print(result_1)
print(result_2)
```
outputs:
```
shape: (2, 4)
┌──────┬──────────────────────────────┬───────────────────────┬──────────────┐
│ code ┆ ewm                          ┆ positive              ┆ ewm_filtered │
│ ---  ┆ ---                          ┆ ---                   ┆ ---          │
│ str  ┆ list[f64]                    ┆ list[bool]            ┆ list[f64]    │
╞══════╪══════════════════════════════╪═══════════════════════╪══════════════╡
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ [false, true, true]   ┆ [0.55]       │
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ [false, false, false] ┆ [-0.55]      │
└──────┴──────────────────────────────┴───────────────────────┴──────────────┘
shape: (2, 4)
┌──────┬──────────────────────────────┬───────────────────────┬──────────────────┐
│ code ┆ ewm                          ┆ positive              ┆ ewm_filtered     │
│ ---  ┆ ---                          ┆ ---                   ┆ ---              │
│ str  ┆ list[f64]                    ┆ list[bool]            ┆ list[f64]        │
╞══════╪══════════════════════════════╪═══════════════════════╪══════════════════╡
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ [false, true, true]   ┆ [0.55, 1.520661] │
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ [false, false, false] ┆ []               │
└──────┴──────────────────────────────┴───────────────────────┴──────────────────┘
```

**Comment by Julian-J-S** [comment]
@ritchie46 can confirm there seems to be a BUG here. Results are non-deterministic! 😮 

### Setup
```python
codes = ["a"] * 5 + ["b"] * 5
values = list(range(-2, 3)) + list(range(2, -3, -1))

df = pl.DataFrame({"code": codes, "value": values})
```

### Problem (on polars 1.5.0)
```python
df.group_by("code").agg(
    pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).alias("ewm"),
    pl.col("value").ewm_mean(span=2, ignore_nulls=True).tail(3).filter(pl.col("value") > 0),
    pl.col("value").filter(pl.col("value") > 0).alias("data"),
    (pl.col("value") > 0).alias("positive").tail(3),
)
```

#### Output 1
```
shape: (2, 5)
┌──────┬──────────────────────────────┬──────────────────┬───────────┬───────────────────────┐
│ code ┆ ewm                          ┆ value            ┆ data      ┆ positive              │
│ ---  ┆ ---                          ┆ ---              ┆ ---       ┆ ---                   │
│ str  ┆ list[f64]                    ┆ list[f64]        ┆ list[i64] ┆ list[bool]            │
╞══════╪══════════════════════════════╪══════════════════╪═══════════╪═══════════════════════╡
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ [0.55, 1.520661] ┆ [1, 2]    ┆ [false, true, true]   │
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ []               ┆ [2, 1]    ┆ [false, false, false] │
└──────┴──────────────────────────────┴──────────────────┴───────────┴───────────────────────┘
```

#### Output 2
```
shape: (2, 5)
┌──────┬──────────────────────────────┬────────────────────┬───────────┬───────────────────────┐
│ code ┆ ewm                          ┆ value              ┆ data      ┆ positive              │
│ ---  ┆ ---                          ┆ ---                ┆ ---       ┆ ---                   │
│ str  ┆ list[f64]                    ┆ list[f64]          ┆ list[i64] ┆ list[bool]            │
╞══════╪══════════════════════════════╪════════════════════╪═══════════╪═══════════════════════╡
│ b    ┆ [0.384615, -0.55, -1.520661] ┆ [-0.55, -1.520661] ┆ [2, 1]    ┆ [false, false, false] │
│ a    ┆ [-0.384615, 0.55, 1.520661]  ┆ []                 ┆ [1, 2]    ┆ [false, true, true]   │
└──────┴──────────────────────────────┴────────────────────┴───────────┴───────────────────────┘
```
### Problem
- affected colum is ONLY `value`; (seems related to `filter`)
- interesting that not only the VALUES are different (pos/neg) but also the GROUP. Output1 values are in `a` but output2 values in `b`

**Comment by ritchie46** [comment]
Alright. Fixing it. Note that the query is invalid as the elements passed to `filter` have a length of 5, whereas the input is sliced to 3.
