### ISSUE TITLE
Uninterpretable error message from read_csv

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#1831]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.10.22

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

I'm reading a CSV (`polars.read_csv`), and I get the output

```RuntimeError: Any(ComputeError("ComputeError(\"Could not parse primitive type during csv parsing: EmptyMantissa(0).This can occur when a column was inferred as integer type but we stumbled upon a floating point valueYou could pass a predefined schema or set `with_ignore_parser_errors` to `true`\") on thread line 25; on input: NA"))```

I know that there's a parsing error when encountering an NA somewhere in the file. But it doesn't say which line or column, which I figured out was (25, 105) only after a lot debugging.

Apparently the correct solution was to pass `null_value="NA"` to `read_csv`, but that wasn't at all obvious from the error message.

A more interpretable error message here would be great, definitely containing the column and row numbers, but also maybe something about null values. I love the syntax of polars, its so much better than pandas. I'd love to see it continue to grow more clean and usable.

#### What are the steps to reproduce the behavior?

Loading two columns from a CSV where one column contains floats till any row past the hundredth where it contains the string `NA` (no quotes). (If it's before the hundredth, then the column is loaded as a str instead of a float and there's no issue)

**Comment by ritchie46** [comment]
Besides a column number what would you like the error message to be? We passed the row and the failed character.
Maybe we don't have to clutter with reason of failure (the failed mantissa).

**Comment by LiterallyUniqueLogin** [comment]
The line number was also wrong - it was line 105. Yeah, those two pieces of info mainly. Something about nulls is that makes sense. And have a docs page about what a Mantissa is (I don't know) if that's important to the error message.

**Comment by ritchie46** [comment]
Oh, yeah.. it was line nr 25 if a thread. Because we split up the data over multiple threads we don't know the line numbers. But I agree we can make try to make the info a bit more useful.

**Comment by ghuls** [comment]
@ritchie46 Maybe printing the whole line of the input (or up to x amount of characters) might be a good idea (together with the line number).

**Comment by jorgecarleitao** [comment]
Note that dumping data to stack traces or logs may constitute a data
leakeage as people authorized to read logs may not be authorized to read
data. The line number seems the one that provides the context without
leaking the content.

**Comment by ritchie46** [comment]
> Loading two columns from a CSV where one column contains floats till any row past the hundredth where it contains the string NA (no quotes). (If it's before the hundredth, then the column is loaded as a str instead of a float and there's no issue)

This is because the schema inference defaults to 100 rows. This is a parameter you can tune accordingly. You don't want to scan the whole file to infer youre schema, so you must set this to something sensible.
