### ISSUE TITLE
Reading wide parquet is 25x slower with polars than pyarrow

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#18319]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np
import time

rows = 1_000
cols = 500_000
uniform_col=pl.Series(np.random.normal(0,1,rows))
df=pl.select(uniform_col.alias(f"col{n}") for n in range(cols))

df.write_parquet('pa_wrote.parquet', use_pyarrow=True)

strt=time.time()
pl.read_parquet('pa_wrote.parquet')
print(f"polars read in {time.time()-strt}")



strt=time.time()
pl.read_parquet('pa_wrote.parquet', use_pyarrow=True)
print(f"pyarrow read in {time.time()-strt}")

```

### Log output

```python
polars read in 1056.7523128986359
pyarrow read in 41.054060220718384
```

### Issue description

Originating from here https://stackoverflow.com/questions/78902884/optimize-reading-of-a-very-wide-dataset-100k-columns-in-polars-and-pandas

The SO question says they've got data in both csv and parquet formats but when polars reads the parquet it takes 30 min but pyarrow only takes 30 sec. I managed to reproduce with the above. 

Even with just 10 rows (still 500k columns) it takes over 6 min for polars to read and during the read all my cores are maxed out so I killed it at the 6 min mark.

### Expected behavior

polars reader should be comparable with pyarrow	

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            0.18.2
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
@coastalwhite I know you've been working on the parquet reading/writing so just want to flag this. This is a niche case with so many columns and it's easy enough to fall back to pyarrow so I tagged it low priority.

**Comment by deanm0000** [comment]
@MarcoGorelli thanks for fixing my brain fart on the title.

**Comment by ritchie46** [comment]
There is something accidental quadratic here. Will take a look.

**Comment by ritchie46** [comment]
Found the culprit. We do sequential search for every column: 
![image](https://github.com/user-attachments/assets/21e7cda0-b42b-44ba-91cf-e699833455b8)

We should create a hashmap up front.
