### ISSUE TITLE
equals lacks functionality that polars.testing.assert_frame_equal has

### ISSUE THREAD

**Issue by ddouglas87** [pola-rs/polars#18311]
### Description

`polars.DataFrame.equals` doesn't check for dtypes but `polars.testing.assert_frame_equal` does check this.

Right now if I want this functionality outside of unit tests I need to use `polars.testing.assert_frame_equal` and capture a throw, or write a third party function.

The code for this functionality is already written.  It would take a very light lift to add this functionality to `polars.DataFrame.equals`.  Can we enhance `polars.DataFrame.equals` to offer the same functionality `polars.testing.assert_frame_equal` has?  It would be a great help.

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.equals.html
https://docs.pola.rs/api/python/stable/reference/api/polars.testing.assert_series_equal.html

**Comment by ritchie46** [comment]
Please use `assert_frame_equals` if you want those options. 

`equals` only answers the question with a boolean return.

**Comment by ion-elgreco** [comment]
What's the usecase? You can also use patito to validate your frame schemas

**Comment by ritchie46** [comment]
I will close this as I want to keep equals simple.

**Comment by ddouglas87** [comment]
>You can also use patito

I don't see a patito method in Polars.

>What's the usecase?

Here's my code atm:

```
        merged_df = self.merge(silver_df, df).sort(by="Date")

        # Because Polars df1.equals(df2) doesn't support exact checking, instead using
        # Polars' unit testing version
        # Original version: if silver_df is not None and merged_df.equals(silver_df):
        try:
            assert_frame_equal(merged_df, silver_df, check_exact=True)
            df_equals = True
        except AssertionError:
            df_equals = False

        if silver_df is not None and df_equals:
            work_done = True
            return work_done

        self.save_df(merged_df, silver_file)
        work_done = False
        return work_done
```

It's a bit of a mouth full to explain the use case.  I have a large db of dumped Polars files from many different apis.  I then clean this data, which takes a lot of processing time.  To keep this processing time from ever growing the cleaning is partitioned into a month of data at a time partitions.  If cleaning does not change anything (usually `equals` or atm `assert_frame_equal`) then it can short circuit -- stop cleaning, work is done.  If cleaning does change the data, then it continues to go back in time updating previous data until it's done.

**Comment by henryharbeck** [comment]
[Patito](https://github.com/JakobGM/patito) is a python package to validate DataFrames. [Pandera](https://github.com/unionai-oss/pandera) is another alternative for the same.

Would checking the DataFrames and the schema be a sufficient option?
```python
a = pl.DataFrame({"col": [1.0, 2.0]}, schema={"col": pl.Float64})
b = pl.DataFrame({"col": [1, 2]}, schema={"col": pl.Int64})

a.equals(b) # True
a.equals(b) and a.schema == b.schema # False
```
Or you could write a small helper around the try except.

**Comment by ddouglas87** [comment]
Thanks for the suggestions and help.  I think a helper function is easiest, because Polars already has this functionality.  Why it can't be extended to `equals` is bizarre.  I'd do a pull request with the updated code if the Polars devs here were for it.  It really is a light lift.

**Comment by J-Moravec** [comment]
Bitten by this and amazed by the lack of configurability of equals.

Third party module should not be required to do basic comparison of Polars structures.

Equally, `testing.assert_frame_equal` throws, which might not be desirable for basic comparison.

`equals` as it is feels like mixed bag where it is quite lenient with type conversion, but strict with floating point precision.

Extending `equals` or at least providing different tool for solving specified problems feels like no brainer to me.
