### ISSUE TITLE
In read_csv convert too long separator, quote_char, and/or eol_char to valid char

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#18320]
### Description

Motivation for request is https://stackoverflow.com/questions/78903266/seperator-should-be-a-single-byte-character-but-is-2-bytes-long-error-in-p/78903300?noredirect=1#comment139115111_78903300

I think we should do a check where if encoding isn't utf-8 and `len(separator.encode('utf-8'))>1` then, since we're running it through BytesIO anyway, we should replace their separator with something like '\x1f' so that it's valid utf-8 and since it's a control character is unlikely to be in their csv. We could issue a warning that this is happening if for some reason they have control characters in their csv.

**Comment by deanm0000** [comment]
I started to work on this when I realized that the same can be done with `quote_char`, and `eol_char`. Additionally, it doesn't seem to make sense to restrict the fix to just when the user specifies a different encoding. When they use a character that is too long, we can just treat it as though they picked a different encoding.

**Comment by ritchie46** [comment]
We don't want to support this. See https://github.com/pola-rs/polars/issues/2728
