### ISSUE TITLE
Some pl.Expr aggregations missing in the Aggregation section

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#18334]
From a quick scan, the following aggregations are missing in the Aggregation section in the API docs:

 - `Expr.all`
 - `Expr.any`
 - `Expr.n_unique`
 - `Expr.approx_n_unique`

**Comment by krasnobaev** [comment]
Hello, I'm willing to work on this. It looks like they are missing from `expressions/aggregation.rst`. I will recheck generated documentation locally and will make a PR.
