### ISSUE TITLE
How to get the row_count of a group？

### ISSUE THREAD

**Issue by houyingkun** [pola-rs/polars#1834]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.22

#### What operating system are you using polars on?

masOs Monterey 12.0.1

#### Describe your bug.

arg_sort returns only "0" but not a Series if there is no more than one row in a group. 

Here is the document
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.arg_sort.html?highlight=arg_sort#polars.Expr.arg_sort

#### What are the steps to reproduce the behavior?

`import polars as pl

good_df = pl.DataFrame([
    {"a": 1, "b": 2},
    {"a": 1, "b": 2},
    {"a": 2, "b": 2},
])

good_out_df = good_df.select(
    [
        pl.col("*"),
        pl.col("a").arg_sort().over("a").flatten().alias("suffix"),
    ]
)
print(good_out_df)

bad_df = pl.DataFrame([
    {"a": 1, "b": 2},
    {"a": 2, "b": 2},
])

bad_out_df = bad_df.select(
    [
        pl.col("*"),
        pl.col("a").arg_sort().over("a").flatten().alias("suffix"),
    ]
)
print(bad_out_df)
`

#### What is the actual behavior?

shape: (3, 3)
┌─────┬─────┬────────┐
│ a   ┆ b   ┆ suffix │
│ --- ┆ --- ┆ ---    │
│ i64 ┆ i64 ┆ u32    │
╞═════╪═════╪════════╡
│ 1   ┆ 2   ┆ 0      │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1   ┆ 2   ┆ 1      │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 0      │
└─────┴─────┴────────┘
Traceback (most recent call last):
  File "/Users/houyingkun/workspaces/lingxingGitlab/sp_financial/src/hyk_research/issue.py", line 23, in <module>
    bad_out_df = bad_df.select(
  File "/Users/houyingkun/miniforge3/envs/py38/lib/python3.8/site-packages/polars/eager/frame.py", line 2726, in select
    self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)
  File "/Users/houyingkun/miniforge3/envs/py38/lib/python3.8/site-packages/polars/lazy/frame.py", line 299, in collect
    return pl.eager.frame.wrap_df(ldf.collect())
RuntimeError: Any(InvalidOperation("explode not supported for Series with dtype UInt32"))

#### What is the expected behavior?

arg_sort() should always return a series.
Actually, I expect a cumcount api like pandas to get the row_count of the row in each group.

**Comment by ritchie46** [comment]
> Actually, I expect a cumcount api like pandas to get the row_count of the row in each group.

You can use the `count` expression.

 ```python
 bad_df.select([
    pl.col("*"),
    pl.count("a").over("a").alias("count")
])
 ```
 
 ```
 shape: (2, 3)
┌─────┬─────┬───────┐
│ a   ┆ b   ┆ count │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ u32   │
╞═════╪═════╪═══════╡
│ 1   ┆ 2   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 1     │
└─────┴─────┴───────┘
 ```
 
 I agree that `argsort` in the groupby context should return a `Series`. I will fix that.

**Comment by houyingkun** [comment]
> > Actually, I expect a cumcount api like pandas to get the row_count of the row in each group.
> 
> You can use the `count` expression.
> 
> ```python
> bad_df.select([
>    pl.col("*"),
>    pl.count("a").over("a").alias("count")
> ])
> ```
> 
>  ```
> shape: (2, 3)
> ┌─────┬─────┬───────┐
> │ a   ┆ b   ┆ count │
> │ --- ┆ --- ┆ ---   │
> │ i64 ┆ i64 ┆ u32   │
> ╞═════╪═════╪═══════╡
> │ 1   ┆ 2   ┆ 1     │
> ├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2   ┆ 2   ┆ 1     │
> └─────┴─────┴───────┘
> ```
> 
> I agree that `argsort` in the groupby context should return a `Series`. I will fix that.

Thx for reply, I tested your advice and the result is not performed as expect.

shape: (3, 3)
┌─────┬─────┬───────┐
│ a   ┆ b   ┆ count │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ u32   │
╞═════╪═════╪═══════╡
│ 1   ┆ 2   ┆ 2     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1   ┆ 2   ┆ 2     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 1     │
└─────┴─────┴───────┘
shape: (2, 3)
┌─────┬─────┬───────┐
│ a   ┆ b   ┆ count │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ u32   │
╞═════╪═════╪═══════╡
│ 1   ┆ 2   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 1     │
└─────┴─────┴───────┘

The first row of geneated column in good_df shoud be 1 in my usecase. Because I need to get the row index in a group.

**Comment by ritchie46** [comment]
Sorry, I don't understand, what do you want? It doesn't sound like you want to count.

**Comment by houyingkun** [comment]
> Sorry, I don't understand, what do you want? It doesn't sound like you want to count.

For example, if I got a report file that contains two rows with the same content, to ensure the data can load into a database table with a unique key, I need to mark them with a label to distinguish them. My solution is to group by row_hash and give a self-incrementing primary key for each group.

**Comment by houyingkun** [comment]
> > Sorry, I don't understand, what do you want? It doesn't sound like you want to count.
> 
> For example, if I got a report file that contains two rows with the same content, to ensure the data can load into a database table with a unique key, I need to mark them with a label to distinguish them. My solution is to group by row_hash and give a self-incrementing primary key for each group.

The content of the report will gradually increase over time, and there will be a small number of updates. I need to capture the changed content to update the database.
