### ISSUE TITLE
`pl.Config.set_tbl_rows` doesn't work as expected

### ISSUE THREAD

**Issue by sbushmanov** [pola-rs/polars#18348]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Config.set_tbl_rows = -1
pl.DataFrame(range(30))
```
---
```
column_0
i64
0
1
2
3
4
…
25
26
27
28
29
```

### Issue description

Out of the expected 30 rows I only see the first and last 5 rows

### Expected behavior

When specifying  `pl.Config.set_tbl_rows = -1` I'm expecting to see the full output in Jupyter notebook.

### Installed versions

```
polars                    1.5.0           py311hf29da40_0    conda-forge
```

**Comment by Julian-J-S** [comment]
Cannot test right now but shouldn't it be a function call like

`pl.Config.set_tbl_rows(-1)`

😉
