### ISSUE TITLE
Make `new_streaming` feature available on Rust Polars

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#18344]
### Description

It seems the `new_streaming` feature is not a public feature, but is only an "internal" feature used in Python Polars.

Does Rust Polars automatically use `new_streaming`?

**Comment by orlp** [comment]
Currently Rust Polars does not use `new_streaming` at all. Neither does Python Polars, for the record, the feature is only used for internal testing as we develop the engine. It is not yet ready for public consumption.
