### ISSUE TITLE
New String/Schema

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#18374]
# Schema and String type streamlining
- [ ] One small string type for all Fields in Arrow and Polars
    This will have a Polars interface. E.g. `struct PlSmallStr`.
- [ ] Polars Schema to `polars_schema` crate and generic over `(Arrow)DataType`, where key: `PlSmallStr` and value generic over `DataType`

# String type requirements:
- [ ] O(1) clone
- [ ] SmallStr optimization
- [ ] Preserving
- [ ] `Field` has constructors `new_from_str`, `new_from_owned`, `new_from_static`

**Comment by nameexhaustion** [comment]
https://github.com/pola-rs/polars/pull/18539 (..), https://github.com/pola-rs/polars/pull/18425 (..)
