### ISSUE TITLE
`ewm_mean_by` documented formula for the decay parameter is incorrect

### ISSUE THREAD

**Issue by sharky564** [pola-rs/polars#18377]
### Description

The formula supplied for $\alpha_i$ is currently incorrect. For small time intervals, it would imply that $\alpha_i$ is close to $1$, so the ewm would be very close to the current value, which is not the expected behaviour of ewms. Instead, $\alpha_i = 1 - \exp(-\lambda (t_i - t_{i-1}))$ would yield the correct behaviour (and is indeed what is shown in `ewm_mean` documentation, as well as `pandas` documentation for `ewm`).

### Link

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ewm_mean_by.html

**Comment by MarcoGorelli** [comment]
thanks @sharky564 - I think you're right, there's a missing `1-` in the docs
