### ISSUE TITLE
Does `arg_max` always return the first maximal index?

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#18390]
### Description

In my testing, it always has - but it is not stated in the docs:

> *"Get the index of the maximal value."*

Pandas `.idxmax()`[^1] for comparison:

> *"Return index of **<ins>first occurrence</ins>** of maximum over requested axis."*

Does Polars also guarantee this?

[^1]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmax.html

### Link

https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.arg_max.html#polars.Expr.arg_max

**Comment by cmdlineluser** [comment]
From Discord[^1]:

> I don't think we want to guarantee that.

[^1]: https://discord.com/channels/908022250106667068/957930511999832064/1313905364487504054

**Comment by zky706** [comment]
Hopefully the 'idxmax' function

**Comment by cmdlineluser** [comment]
[`.arg_true()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.arg_true.html#polars.Expr.arg_true) can be used.

```python
(pl.col("a") == pl.col("a").max()).arg_true().first()
```

It seems there is also a new [`.index_of()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.index_of.html#polars.Expr.index_of) which says it gives the first index.

```python
pl.col("a").index_of(pl.col("a").max())
```
