### ISSUE TITLE
Allow expressions in `insert_column`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#18406]
### Description

I often have to insert a column of literal value 

```python
df = pl.DataFrame(...)
df.insert_column(0,
    pl.Series("ID", ["label"] * len(df))
)
```

Having to construct the series is a bit of a nuisance, it would be much more elegant to supply an expression:

```python
df.insert_column(0, pl.lit("label").alias("ID"))
```

This can be done with `with_columns` but it also then requires an additional selection with reposition.

**Comment by alexander-beedie** [comment]
Yup, makes sense to me...
