### ISSUE TITLE
`assert_frame_not_equal` does not raise when input types are different

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#18401]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from polars.testing import assert_frame_not_equal

df1 = pl.DataFrame({"a": [1, 2, 3]})
df2 = pl.DataFrame({"a": [1, 5, 3]})

assert_frame_not_equal(df1, df2.lazy()) # no AssertionError raised
```

### Issue description

`assert_frame_not_equal` should raise when the types are not the same

### Expected behavior

It should raise the same way this does 

```python
from polars.testing import assert_frame_equal

df1 = pl.DataFrame({"a": [1, 2, 3]})

assert_frame_equal(df1, df1.lazy())
# AssertionError: inputs are different (unexpected input types)
# [left]:  DataFrame
# [right]: LazyFrame
```

### Installed versions

main branch

**Comment by alexander-beedie** [comment]
I see why it's happening... of course _technically_ the frames aren't equal as they are of different types, heh. But that's not what the function is testing, so I agree that it should raise here ;)

**Comment by henryharbeck** [comment]
> technically the frames aren't equal as they are of different types, heh

🤣 you are not wrong

Fix incoming!

**Comment by alexander-beedie** [comment]
> Fix incoming!

Ahh, already committed one 😅 
Spotted we had the same issue with `assert_series_equal` too.

**Comment by henryharbeck** [comment]
Very fast! Appreciate the quick turnaround!

**Comment by mcrumiller** [comment]
> Spotted we had the same issue with assert_series_equal too.

Was this possible to hit? There is no lazy Series.

**Comment by alexander-beedie** [comment]
> Was this possible to hit? There is no lazy Series.

You can hit it on _any_ mismatched type; this will currently not raise:
```python
from polars.testing import assert_series_not_equal
import polars as pl

s1 = pl.Series([1,2,3])
s2 = "I am a potato"

# would not raise ->
assert_series_not_equal(s1, s2)
```
