### ISSUE TITLE
faster sorting/filtering of DataFrames with array columns

### ISSUE THREAD

**Issue by ggggggggg** [pola-rs/polars#18412]
### Description

When sorting a DataFrame with an array column, it should be possible to be basically as fast as a scalar column by sorting an array of pointers and not copying data around. Based on my tests (pasted below) it seems that polars copies the data. I've looked for ways to opt into this behavior, but I can't find any info on the performance model of arrays and lists. The same principle should apply to filtering as well.

The code below measures the elapsed time and tries to measure the bytes allocated when sorting a DataFrame containing an array column. The allocation results vary somewhat, but this is a representative result. This result shows that sorting is very fast when the array column is not present, and much slower when the array column is present. The allocation are small when the array column is not present, and nearly equal to the size of all the data in the array column when the array column is present.
```
sort by rand, column index present 0.001 s, 0 bytes allocated
sort by rand, column a present 0.637 s, 8.00068e+08 bytes allocated
bytes in a = 8e+08
```

```python
import polars as pl
import numpy as np

a = np.arange(100000000).reshape((-1,5000))
rand_nums = np.random.rand(a.shape[0])
index = np.arange(a.shape[0]) # index is present to make sure we're sorting exaclty two columns in each call to sort, it also contains enough information to determine which array entry goes with each row after sorting
df = pl.DataFrame({"a":a,"rand":rand_nums,"index":index}, schema={"a":pl.Array(pl.Int64, 5000), "rand":pl.Float64, "index":pl.Int64})

def timeit(f, s):
    # timeit prints the elapsed time in seconds and an attempt at measuring bytes allocated when calling f(), it also prints the string s
    import time
    import psutil
    import gc
    gc.collect()
    process = psutil.Process()
    tstart = time.time()
    bytes_allocated_before = process.memory_info().rss
    result = f()
    tend = time.time()
    bytes_allocated_after = process.memory_info().rss
    bytes_increase = bytes_allocated_after-bytes_allocated_before
    elapsed = tend-tstart
    print(f"{s} {elapsed:.3f} s, {bytes_increase:g} bytes allocated")
    return elapsed, result

timeit(lambda: df.select(pl.exclude("a")).sort(by="rand"), "sort by rand, column index present")
timeit(lambda: df.select(pl.exclude("index")).sort(by="rand"), "sort by rand, column a present")
print(f"bytes in a = {8*len(a.flatten()):g}")
```

**Comment by ritchie46** [comment]
> When sorting a DataFrame with an array column, it should be possible to be basically as fast as a scalar column by sorting an array of pointers and not copying data around

No, it should not. We don't store pointers, the arrays are inlined. You will have to move the data to create a valid array type.

Moving data has a price.

**Comment by ritchie46** [comment]
I will close this as this is expected.
