### ISSUE TITLE
`.explode()` PanicException: validity must be equal to the array's length

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#18421]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"A": [[{"B": 1}], [None], []]})

df.explode("A")
# PanicException: validity must be equal to the array's length
```

### Issue description

Found while triaging https://github.com/pola-rs/polars/issues/17745#issuecomment-2244285693

Not entirely sure if it is the same problem as the original issue - so reposting separately for visibility.

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by orlp** [comment]
I think the underlying problem is that we've made the mistake to add `null` elements for empty lists in the explode, copying pandas behavior for that. I recently brought that up with @ritchie46, and it's something we want to change for polars 2.0.
