### ISSUE TITLE
If `.drop_nulls()` / `.drop_nans()` result in a length of 1, the value is "silently" broadcasted

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#18430]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": ["a", "b", "c"], "b": [1, None, None]})

df.with_columns(pl.all().drop_nulls())
# shape: (3, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ str ┆ i64 │
# ╞═════╪═════╡
# │ a   ┆ 1   │
# │ b   ┆ 1   │
# │ c   ┆ 1   │
# └─────┴─────┘
```

### Issue description

Query originally raised by a user on SO[^1]

If the drop results in a length of 1 the value is broadcasted - which seems like it may be unintentional?

Changing the example to a length of 2 raises a `ShapeError` as one would expect.

```python
df = pl.DataFrame({"a": ["a", "b", "c"], "b": [1, None, 3]})

df.with_columns(pl.all().drop_nulls())
# ShapeError: unable to add a column of length 2 to a DataFrame of height 3
```

[^1]: https://stackoverflow.com/questions/78921222/polars-unexpected-behaviour-when-using-drop-nans-on-all-columns

### Expected behavior

It seems like this should error?

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by orlp** [comment]
Yes, this should error, but this requires a massive rewrite across the entire project (at least for the general case). Currently we treat any column with length 1 as a scalar, this should test for proper scalars instead.

This isn't limited to `drop_nulls` either, anything which reduces length can trigger this, e.g.:

```python
>>> df = pl.DataFrame({"x": [1, 2, 3]})
>>> df.with_columns(y = pl.col.x.filter(pl.col.x > 2))
shape: (3, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 3   │
│ 3   ┆ 3   │
└─────┴─────┘
```

I'm closing this issue though, as this is a known defect not limited to `drop_null`s and something we'll tackle at a later stage.

**Comment by ritchie46** [comment]
Yes, I am brooding on scalars. I will get to them one day. :)
