### ISSUE TITLE
Column name not found when joining by expressions (starts_with)

### ISSUE THREAD

**Issue by 29antonioac** [pola-rs/polars#18458]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl 

prefixes = pl.DataFrame({"prefix": ["ae", "ap", "be"]})
words = pl.DataFrame({"word": ["aeiou", "app", "bee", "fly"]})

words.join(prefixes, on=pl.col("word").str.starts_with(pl.col("prefix")))
```

### Issue description

Hi, I have an example where some prefixes of varying length match with countries. I have tried to join with an expression based on `str.starts_with()` but I get a `ColumnNotFoundError` exception on the `word` column. Is this expected behaviour and I need to fix my code, or is it a bug?

Thank you!

### Expected behavior

```python
output = pl.DataFrame({"prefix": ["ae", "ap", "be"], "word": ["aeiou", "app", "bee"]})
output
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Linux-6.1.0-23-cloud-amd64-x86_64-with-glibc2.36
Python:              3.11.9 (main, Aug 14 2024, 05:07:28) [Clang 18.1.8 ]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.19.1
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

**Comment by alexander-beedie** [comment]
All columns defined in the `on` parameter are expected to be in _both_ frames, hence the error; when you want to join on columns with different names in each frame you need to define the `left_on` and `right_on` parameters instead.

For example, this works, assuming you only want to check the first two letters match:
```python
words.join(prefixes, left_on=pl.col("word").str.head(2), right_on="prefix")
# shape: (3, 2)
# ┌───────┬────────┐
# │ word  ┆ prefix │
# │ ---   ┆ ---    │
# │ str   ┆ str    │
# ╞═══════╪════════╡
# │ aeiou ┆ ae     │
# │ app   ┆ ap     │
# │ bee   ┆ be     │
# └───────┴────────┘
```
At first glance I'm actually not sure quite sure how you would do the more arbitrary form of that join (any length prefix), but this explains the error.
