### ISSUE TITLE
Error when chaining a LazyFrame `.with_row_index()` with `.sink_csv()`

### ISSUE THREAD

**Issue by vincent-octo** [pola-rs/polars#18455]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [1]: import polars as pl

In [2]: pl.scan_csv("test.csv").sink_csv("/dev/stdout")
A
zero
one
two

In [3]: pl.scan_csv("test.csv").with_row_index().sink_csv("/dev/stdout")
(...)
ComputeError: could not parse `zero` as dtype `u32` at column 'index' (column number 1)

The current offset in the file is 2 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `zero` to the `null_values` list.

Original error: ```remaining bytes non-empty```
```

### Issue description

I would like to add a column with the row number to a CSV file, since this file is quite large I would like to use the `.scan_` and `.sink_` calls to stream the input and output.

It seems that this is currently not possible, and from the error message it appears more like a bug than a known limitation.

### Expected behavior

Ideally, it would go like this:

```python
In [1]: import polars as pl

In [2]: pl.scan_csv("test.csv").with_row_index().sink_csv("/dev/stdout")
index,A
0,zero
1,one
2,two
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.1 (main, Jan  7 2024, 23:31:12) [Clang 16.0.3 ]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by bulatovv** [comment]
Also experiencing this issue with the following code:
```python
q = pl.scan_csv(
    'test.csv',
).with_row_index()

print(q.collect(streaming=True))
```
Would be great to see this fixed!

**Comment by deanm0000** [comment]
In version 1.7.1 I get InvalidOperationError and they're working on a big streaming revamp which (I'm guessing but don't have any direct knowledge of) will fix this. I'm going to close this for now since the ComputeError was already fixed to a more descriptive error. If, after the new streaming engine is released, it still doesn't work then raise another issue since this one will just get buried and go stale by then anyway.
