### ISSUE TITLE
`map_elements` incorrectly converts all output to NULL

### ISSUE THREAD

**Issue by Sakura-Luna** [pola-rs/polars#18472]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

example
```python
pl.Series([[None], ['abc']]).map_elements(
    lambda s: [i.strip() if i else None for i in s],
)
```

### Log output

```shell
Series: '' [list[null]]
[
	[null]
	[null]
]
```

### Issue description

I encountered strange empty results when migrating some samples to Polars. After some troubleshooting, I located the problem in **map_elements**. I found that it returned all empty results on some outputs.

The method is very "smart" to skip the calculation of the first result being Null. It is controlled by skip_nulls but **defaults to True**. I think it is unreasonable. At least in many of my test samples, the first result cannot be guaranteed to be true. I have to specify skip_nulls as False for all the code.

In addition, **the name and documentation of this parameter are unclear**. It seems that some people think it means ignoring null values, which is far from the actual situation. I think it should be changed to something like "skip_null_start".

### Expected behavior

```
Series: '' [list[str]]
[
	[null]
	["abc"]
]
```

### Installed versions

```
Polars:              1.6.0
Python:              3.11
```

**Comment by orlp** [comment]
This is a bug, `skip_nulls` should only apply to the input, not calling your function for those inputs. It should not convert your output into nulls.

**Comment by Sakura-Luna** [comment]
> This is a bug, `skip_nulls` should only apply to the input, not calling your function for those inputs. It should not convert your output into nulls.
> 
> I'm giving it P-high because it's pretty nonsensical and easy to trigger without doing much weird things (albeit inefficient things since `map_elements` is involved).

The problem is not with the input, but that the function skips the first query with an empty result. Try this
`pl.Series([1, None]).map_elements(lambda x: None if x else x, pl.Int64)`

**Comment by ritchie46** [comment]
@stinodego could you investigate this one?

**Comment by stinodego** [comment]
There are two issues here:

1. `skip_nulls=True` is the default. This is faster, but may lead to incorrect results when the mapping function actually maps `None` values. I think we should switch the default to `skip_nulls=False`. This would be a non-breaking change - it would make some code slower, but nothing would break/become incorrect. The scenario where a user gets correct results and then finds a flag in the docs to make their code faster is a better scenario than a user getting incorrect results and then having to figure out what is going on.

2. The implementation for nested types with `skip_nulls=True` is incorrect. The `return_dtype` parameter is disregarded, and the return dtype is instead inferred from the first non-null output value. In the example in this issue, that value is `List(Null)`, so all output values become null. So two things need to happen: we need to respect `return_dtype` always, and we need to fix the logic for dtype inference. Neither is a quick fix, I'm afraid.

**Comment by Sakura-Luna** [comment]
> 2. The implementation for nested types with `skip_nulls=True` is incorrect. The `return_dtype` parameter is disregarded, and the return dtype is instead inferred from the first non-null output value. In the example in this issue, that value is `List(Null)`, so all output values become null. So two things need to happen: we need to respect `return_dtype` always, and we need to fix the logic for dtype inference. Neither is a quick fix, I'm afraid.

But here the inferred type is i64, is map_elements doing multiple conversions?
```python
pl.Series([1, None]).map_elements(lambda x: None if x else 1)

# Series: '' [i64]
# [
# 	null
# 	null
# ]
```

**Comment by stinodego** [comment]
@Sakura-Luna that result is actually correct, because `skip_nulls=True` is the default. The function is applied to the first element, which results in null, and the second is element is skipped (existing null is preserved). If you want to apply your function to null values as well, you must set `skip_nulls=False`.

That may be undesirable (see my first point), but that's a different discussion.

**Comment by Sakura-Luna** [comment]
> That may be undesirable (see my first point), but that's a different discussion.

I mentioned above that it is not reasonable to enable `skip_nulls` by default. On the one hand, it has limited benefits, and on the other hand, Null may make sense. I suggest that `map_elements` implement `cache_result` instead of `skip_nulls`, which can circumvent the existing problem.

**Comment by stinodego** [comment]
> I mentioned above that it is not reasonable to enable `skip_nulls` by default.

After looking at this a bit more, there's no real good way to handle `skip_nulls` by default. Yes, you demonstrated that functions may check for `None` inputs, in which case you would not want to skip these. However, in many cases skipping nulls makes sense, e.g. `map_elements(json.loads)`. If `skip_nulls=False`, this will fail - I would have to explicitly handle nulls for every input function, or set `skip_nulls=True`.

Neither options feels good. I don't think there is a strong reason to change the current default.
