### ISSUE TITLE
Calculate Entropy for non-numerical columns

### ISSUE THREAD

**Issue by LeonB28** [pola-rs/polars#18480]
### Description

In my current project, I am calculating entropy for different types of columns.
Currently, Polars fails with an exception:
```
polars.exceptions.InvalidOperationError: expected numerical input for 'entropy'
```

It is supported in duckdb for example:
```
 df = duckdb.sql("""
    SELECT 
        entropy(Age),
        entropy(Employment),
        entropy(RemoteWork)
    FROM 
        read_csv("C:\\Users\\Leon\\data\\stack-overflow-developer-survey-2024\\survey_results_public.csv")                        
    """).pl()
```
It will be nice to have it supported in Polars as well

**Comment by etiennebacher** [comment]
Related to https://github.com/pola-rs/polars/issues/15350

**Comment by orlp** [comment]
`entropy` in Polars directly operates on the probabilities / weights, and this is intended behavior. To get equivalent behavior to your example query you would first count the number of unique values, and then interpret that as weights:

```python
df.select(
    pl.col.age.unique_counts().entropy(base=2),
    pl.col.employement.unique_counts().entropy(base=2),
    pl.col.remote_work.unique_counts().entropy(base=2),
)
```

This format is more flexible, in case you already have the probabilities or want to calculate them in a way different than simple occurrence counts.
