### ISSUE TITLE
serde deserialisation of AnyValue doesn't work

### ISSUE THREAD

**Issue by domw95** [pola-rs/polars#18505]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::AnyValue;

#[derive(Debug, Default, serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq)]
struct Message {
    id: u8,
    header: u16,
    size: u32,
    data: Vec<AnyValue<'static>>,
}
fn main() {
    let mut buf = [0; 20];
    let original = AnyValue::UInt32(5);

    let b_vec = bincode::serialize(&original).unwrap();
    dbg!(&b_vec);
    let b_d = bincode::deserialize(&b_vec).unwrap();
    assert_eq!(original, b_d);

    postcard::to_slice_cobs(&original, &mut buf).unwrap();
    let msg = postcard::from_bytes_cobs(&mut buf).unwrap();
    assert_eq!(original, msg);
}

```

### Log output

```shell
[src/main.rs:15:5] &b_vec = [
    7,
    0,
    0,
    0,
    5,
    0,
    0,
    0,
]
thread 'main' panicked at src/main.rs:16:44:
called `Result::unwrap()` on an `Err` value: Custom("invalid type: integer `7`, expected an integer between 0-14")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

deserialising an AnyValue from a vector of bytes that has just been serialised always fails with above error. Tried with bincode and postcard

### Expected behavior

Deserialisation without error

### Installed versions

<details>

bincode = "1.3.3"
polars = { version = "0.42.0", features = ["serde", "serde-lazy"] }
postcard = "1.0.10"
serde = { version = "1.0.209", features = ["derive"] }

</details>

**Comment by ritchie46** [comment]
You need a self describing format. Try `ciboriom`.

**Comment by domw95** [comment]
Ok thanks, I'll try find a workaround for what I'm doing. Out of interest is this a technical limitation of the AnyValue enum or just the implementation?
