### ISSUE TITLE
Support multiple columns selection for inner_join, outer_join, and left join

### ISSUE THREAD

**Issue by illumination-k** [pola-rs/polars#1854]
#### Describe your feature request

Now, polars `join` method supports multiple columns selection, but other `inner_join`, `outer_join`, and `left join` do not support it.

It seems easy to support this by treating `inner_join` etc., as a wrapper of `join` method like

```rust
pub fn inner_join<'a, J, S1: Selection<'a, J>, S2: Selection<'a, J>>(
    &self,
    other: &DataFrame,
    left_on: S1,
    right_on: S2,
) -> Result<DataFrame> {
    self.join(other, left_on, right_on, JoinType::Inner, None)
}
```

 I think it is better from the perspective of the consistency of API.

**Comment by ritchie46** [comment]
Yes, you are right, this was never extended. Could you make a PR?
