### ISSUE TITLE
`maintain_order` argument for `LazyFrame.sort` does not work correctly due to double-sort removal

### ISSUE THREAD

**Issue by finn-rudolph** [pola-rs/polars#18558]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from __future__ import annotations

import polars as pl

df = pl.DataFrame(
    {
        "col1": [1, 2, 2, 4, 5, 6],
        "col2": [2, 2, 0, 0, 2, None],
    }
)

print(df.lazy().sort("col2").sort("col1", maintain_order=True).collect())
print(df.sort("col2").sort("col1", maintain_order=True))
```

### Issue description

The output of the above code is
```
shape: (6, 2)
┌──────┬──────┐
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 1    ┆ 2    │
│ 2    ┆ 2    │
│ 2    ┆ 0    │
│ 4    ┆ 0    │
│ 5    ┆ 2    │
│ 6    ┆ null │
└──────┴──────┘
shape: (6, 2)
┌──────┬──────┐
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 1    ┆ 2    │
│ 2    ┆ 0    │
│ 2    ┆ 2    │
│ 4    ┆ 0    │
│ 5    ┆ 2    │
│ 6    ┆ null │
└──────┴──────┘
```
The order of rows comparing equally on `col1` is not maintained by `sort` on a lazy frame. On an eager frame this is the case, as the above example shows.

### Expected behavior

The two dataframes printed above should be the same, since the sorting by `col2` and then stably by `col1` defines a unique ordering. In particular, the lazy frame is wrong.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by nameexhaustion** [comment]
This is due to double-sort removal by the optimizer

ref https://github.com/pola-rs/polars/pull/15573

Note `collect(no_optimization=True)` doesn't turn it off either because it is (I believe) a fast projection

https://github.com/pola-rs/polars/blob/8b0502770d0d0129bcb4e1ac72c9d4be6712eb99/crates/polars-plan/src/plans/optimizer/mod.rs#L168-L171

**Comment by gab23r** [comment]
Relevant issue: https://github.com/pola-rs/polars/issues/8410

In the case where we have `n` stable sort in a row, the optimizer can do one sort and reverse the order of the keys.
