### ISSUE TITLE
`pl.read_lines`, `pl.scan_lines`

### ISSUE THREAD

**Issue by KDruzhkin** [pola-rs/polars#18588]
### Description

Polars has functions for reading / scanning **csv files**: `read_csv`, `read_csv_batched`, `scan_csv`. It would be nice to have functions for reading / scanning **raw text files**: `read_lines`, `read_lines_batched`, `scan_lines`.

The implementation is trivial: just pretend to read a csv file with only one column.

## Motivation

At work, I have to deal with non-standard csv dialects.

Quotation marks may have no special meaning:

```csv
1;42;"This is" the end.
```

Sometimes, only the first n separators should be used:

```csv
2;42;Some text.
3;42;Some text; more text.
```

To deal with this, I would like to scan those files as a list of lines.
Some of those lines I will later process with [Expr.str.split_exact](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.split_exact.html).

**Comment by etiennebacher** [comment]
Could this be a workaround?

```python
pl.read_csv("test.txt", columns=0, has_header=False)
```

**Comment by KDruzhkin** [comment]
@etiennebacher, not exactly. Your solution works if there are no separators (`separator=','` by default).

Yes, I can use an impossible separator (a control character or a Chinese symbol), but this doesn't smell good.

**Comment by orlp** [comment]
Closed in favor of https://github.com/pola-rs/polars/issues/19183.
