### ISSUE TITLE
Polars can't cross-compile from WSL2 to Windows. EXE created, but will not run, throws "This App will not run on your PC"

### ISSUE THREAD

**Issue by lkeating-intel** [pola-rs/polars#18596]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Cargo.toml:
```toml
[dependencies]
ndarray = "0.16.1"
plotters = "0.3.6"
polars = {version="0.42.0", features = ["lazy", "ndarray", "asof_join", "strings", "regex", "csv"]}
```
main.rs
```rust
use polars::prelude::*;
use std::path::PathBuf;

fn main() {
  let file_path: PathBuf = "C:\\temp\\SomeFile.csv".into();
  println!("File selected: {:?}", &file_path);
  let new_df: DataFrame = read_csv_to_df(file_path.into()).expect("Could not create DataFrame");
}
fn read_csv_to_df(path: Option<PathBuf>) -> Result<DataFrame, PolarsError> {
  let df = CsvReadOptions::default()
    .with_infer_schema_length(None)
    .with_has_header(true)
    .try_into_reader_with_file_path(path)?
    .finish()?;

  Ok(df)
}
```

```bash
cargo build --target x86_64-pc-windows-gnu
```

### Log output

```shell
N/A
```

### Issue description

I'm trying to build a GUI for a simple script I wrote, and it will need to run on a Windows environment. I'm trying to cross-compile from WSL2 (Ubuntu 24.04LTS) to Windows. 

The minimal code example will build fine on my machine, but it is not executable on windows.

Running:
```bash
$ file target/x86_64-pc-windows-gnu/debug/polars-testing.exe
target/x86_64-pc-windows-gnu/debug/polars-testing.exe: PE32+ executable (console) x86-64, for MS Windows
```
When I try to run this on my PC (Win 11 23H2):
```powershell
C:\temp> .\polars-testing.exe
Program 'polars-testing.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .\polars-testing.exe
+ ~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\polars-testing.exe
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Double-clicking on the exe gives the following error:
![image](https://github.com/user-attachments/assets/c0cb4af8-df06-41a0-b930-60b5fd57d2da)

I've removed as much code as I can, and this seems to always throw the error. I've tried the following as well:
```
cargo build --target x86_64-pc-windows-msvc
cross build --target x86_64-pc-windows-gnu
cross build --target x86_64-pc-windows-msvc
Polars Version = 0.41.3
```
But I cannot get this executable to run via cross compilation

### Expected behavior

Code should compile on WSL2 with:
```bash
cargo build --target x86_64-pc-windows-gnu
```
and create a .exe that is executable on Windows, or throw an error at compile time.

### Installed versions

<details>

lazy,ndarray,asof_join,strings,regex,csv

</details>

**Comment by lkeating-intel** [comment]
Yes, I can cross-compile for Hello World. I can also cross-compile for Rusty File Dialog. Incidentally, I can also cross-compile the above code, as long as I don't call the `read_csv_to_df` function in the main function. So the function can be defined, and as long as it isn't called, the executable can be cross-compiled.

**Comment by lkeating-intel** [comment]
I managed to get rustup installed on the Windows side of my machine (had to fuss with proxy settings due to enterprise environment), and I was able to compile the above code. It doesn't throw the same error when built natively.

**Comment by ritchie46** [comment]
I don't know what we should do here. We're not cross compilation experts. This seems more like something to ask on SO.

**Comment by barak1412** [comment]
I managed to complie my polars plugin on windows with [maturin](https://github.com/PyO3/maturin).
It creates, among other thing, a dll file if I recall correctly.

**Comment by lkeating-intel** [comment]
@ritchie46 I can close this issue if you think it's not the right venue. I just thought it was odd. I've never really had any issues with cross-compilation, or when I do, the compiler throws errors instead of silently creating a corrupted file.

I thought I was stuck until I finally figured out how to get `rustup` on the windows side of my machine. It's inconvenient, but I can get my work done writing on that side of my machine.

**Comment by coastalwhite** [comment]
I think this is more of a bug to discuss with the rust compiler people.
