### ISSUE TITLE
Polars Utilities ... as a Package? 

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1862]
After participating in a discussion in https://github.com/pola-rs/polars/issues/1820#issuecomment-975769103 I became inspired to think about a small package that implements common tasks as `.pipe()` functions. There are a few aspects that seem very attractive. 

- It could serve as a way to prevent feature bloat in the core polars library. If the task is common but composed out of already existing commands then one could argue that it should not go into the core library. 
- It could serve as a nice exercise in writing performant queries, which may likely lead to some nice anecdotes for the blog. 
- It could be implemented to support both polars/dask and pandas. That way, we could potentially support multiple communities while also having a nice benchmark around. There are some interesting tricks one could explore with multiple-dispatch too. 
- It could also save folks some time. It's not hard to write a query that can `sessionize` if you've done it before in SQL, but if you've never done it before it can take a while because there are multiple commands that need to be combined. 

What I'm unsure about is if there are enough examples like "sessionize" that would warrant such a library/package. I figured it best to start a thread here so folks might discuss it. As a general rule, I propose we need at least three functions like "sessionize" before the package is actually considered. 

ps. I'm the kind of person who *really* likes to discuss what a good name for such a package might be. So if people want to share some polar-bear-pipeline related puns -> go right ahead! 

<details>
  <summary><b>But let's keep it on point by keeping name suggestions hidden.</b></summary>

Maybe "valve" is a cute name because it's about controlling pipelines? Otherwise "plurals" might be fun if we ever decide to also include dask and pandas. Otherwise ... "polarized"? 
</details>

**Comment by ritchie46** [comment]
I agree on that such a package could be far more lenient in what it supports. For instance, I have got questions regarding plotting utilities, which IMO should not be in polars, but could be in such a utils package.

Another benefit is that we could use that to experiment and if something proofs to be working in the real world it can be hoisted into the core library. 

I am open to such a package. We already started https://github.com/pola-rs/examples to have more community driven examples, maybe that could also be aggregated more.

**Comment by koaning** [comment]
- I think a `sessionize` function would be good. 
- I think a `bayes_average` might be good too [idea](https://godatadriven.com/blog/reverse-engineering-boardgamegeek/). 
- Maybe just some heuristics to find bots in sessionizable weblogs?

**Comment by ritchie46** [comment]
Nothing set in stone, but I create a repo `valve` (name may change) that could host this. 

https://github.com/pola-rs/valve

I think `sessionization` and the mentioned `bayes_average` are good example of something you'd like to do in a domain, that doesn't really fit the polars library itself, its not a core/ fundamental operation like a `join`, `first` etc. is.

**Comment by koaning** [comment]
Could you add a readme? Without it, I cannot fork and it also seems like I cannot simply push to the empty repo.

**Comment by ritchie46** [comment]
> Could you add a readme? Without it, I cannot fork and it also seems like I cannot simply push to the empty repo.

Done! :+1:

**Comment by ritchie46** [comment]
See https://github.com/pola-rs/valves
