### ISSUE TITLE
What does the trailing `_` mean in `Expr.not_` and `Series.not_` ?

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#18641]
### Description

This trailing `_` looks weird and is not consistent with the other APIs. Does it have any special meanings? Shall we make a `.not` instead and deprecate the trailing `_` one?

**Comment by cmdlineluser** [comment]
`not` is a keyword[^1] in Python.

```python
>>> __import__("keyword").iskeyword("not")
# True
>>> __import__("keyword").iskeyword("not_")
# False
```

You cannot your own functions with the same name as a keyword.

[^1]: https://docs.python.org/3/reference/lexical_analysis.html#keywords

**Comment by liufeimath** [comment]
> `not` is a keyword[1](#user-content-fn-1-2686166bb7e16b5e71ac356cd2ab3b29) in Python.
> 
> ```python
> >>> __import__("keyword").iskeyword("not")
> # True
> >>> __import__("keyword").iskeyword("not_")
> # False
> ```
> 
> You cannot create your own functions with the same name as a keyword. (SyntaxError)
> 
> ## Footnotes
> 1. https://docs.python.org/3/reference/lexical_analysis.html#keywords [↩](#user-content-fnref-1-2686166bb7e16b5e71ac356cd2ab3b29)

Ah right. Thanks for the reminder and education!
