### ISSUE TITLE
Add an argument to display progress bars to `map_elements()`

### ISSUE THREAD

**Issue by joshpersi** [pola-rs/polars#18642]
### Description

Hello, 

My suggested enhancement pertains to iteration and progress bars. 

In R, the `map` family of functions from the Tidyverse package `purrr` includes an argument for printing progress bars. E.g.: 

```r
library(dplyr)
library(purrr)
library(tibble)

data <- tibble(a = 1:1000)

data <- mutate(data, b = map(a, \(x) rnorm(1e6), .progress = TRUE))
```

I am wondering if this is a feature you would consider adding to `map_elements()` or `map_rows()` in Polars? 

Thank you, 

Josh

**Comment by Teut2711** [comment]
Won't that further slow down the already slow function?

**Comment by cmdlineluser** [comment]
Just some info:

This did come up previously https://github.com/pola-rs/polars/issues/7601 and was closed with reference to the more general issue of any Polars computation.

- https://github.com/pola-rs/polars/issues/4654

There are some recipes on SO for custom UDF progress bars which may be of interest.

- https://stackoverflow.com/questions/75550124/

**Comment by joshpersi** [comment]
Thanks @cmdlineluser for the information and links. I'll close this issue.
