### ISSUE TITLE
Unpickling list-type series results in PanicException

### ISSUE THREAD

**Issue by nmandery** [pola-rs/polars#1866]
#### Are you using Python or Rust?

Python 3.8

#### What version of polars are you using?

0.10.23

#### What operating system are you using polars on?

Linux, Ubuntu 20.04

#### Describe your bug.

Unpickling a list-type series results in an error, works fine for non-list series.

#### What are the steps to reproduce the behavior?

```python
import pickle
import polars as pl
print(pl.version())

s = pl.Series("inner", [1, 2, 3, 4, 5], pl.UInt32)
s2 = pl.Series("outer", [s, s, s, s])
print(s2)

b = pickle.dumps(s2)
s3 = pickle.loads(b)
print(s3)
```

#### What is the actual behavior?

```
0.10.23
shape: (4,)
Series: 'outer' [list]
[
	[1, 2, ... 5]
	[1, 2, ... 5]
	[1, 2, ... 5]
	[1, 2, ... 5]
]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "" })', /github/workspace/polars/polars-core/src/serde/series.rs:79:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "t.py", line 10, in <module>
    s3 = pickle.loads(b)
  File "/tmp/venv/lib/python3.8/site-packages/polars/internals/series.py", line 262, in __setstate__
    self._s.__setstate__(state)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "" })
```

#### What is the expected behavior?

`s3` should be the same as `s2`

**Comment by ritchie46** [comment]
Thanks for the issue report @nmandery. We will take a look.

**Comment by ritchie46** [comment]
For anyone interested in picking this up. Its the serde code that needs to be tested on deserializing a list.

**Comment by nmandery** [comment]
I haven't had the time looking into the cause for this in detail, but I noticed some unexpected behavior when adding the following `println!` in the `getstate` method [here](https://github.com/pola-rs/polars/blob/fb57767ce042a87d3daa1b6689614569100a49e9/py-polars/src/series.rs) while trying to get an understanding of the serialized representation of the series.

```rust
println!("{}", serde_json::to_string(&self.series).unwrap())
```

The output when running the above python code was

```
{"name":"outer","datatype":"List","values":[{"name":"","datatype":"Int64","values":[1,2,3,4,5]},{"name":"","datatype":"Int64","values":[1,2,3,4,5]},{"name":"","datatype":"Int64","values":[1,2,3,4,5]},{"name":"","datatype":"Int64","values":[1,2,3,4,5]}]}
```

So the `UInt32` typed series get serialized as `Int64`. This is certainly not the cause for the panic, but seems to be an issue in the same context.

Strangely, there is already a test serializing and deserializing a nested list, which is passing fine.  I will try to find a bit of time to look into this issue.

**Comment by ritchie46** [comment]
Hmm.. Maybe it is because we use `serde_json` in testing which I believe is a self describing deserialization. We should maybe test on a binary serialization as well.
