### ISSUE TITLE
write_excel(...hidden_columns) parameter no longer working

### ISSUE THREAD

**Issue by darrylthom** [pola-rs/polars#18668]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

df.write_excel("C:/Test/Test.xlsx", hidden_columns=['Name'])
```

### Issue description

The hidden_columns parameter of the write_excel method is no longer actually hiding the column(s) listed.

### Expected behavior

Column should be hidden.

### Installed versions

<details>

```
polars 1.6.0
```

</details>

**Comment by alexander-beedie** [comment]
@KingDarule: Thanks for the bug report; just committed a fix👌
