### ISSUE TITLE
Support `to_list()`/`to_array()` on `struct` types

### ISSUE THREAD

**Issue by Crypto-Spartan** [pola-rs/polars#18704]
### Description

Currently, I'm trying to use `.str.splitn()`/`.str.split_exact()`, which both return the `struct` type. I would like to be able to convert/cast this into an array/list so I can do something like `.list.eval()` on the substrings.

I'm currently using the regular `.str.split()` function, but when I'm trying to optimize the execution within a LazyFrame, it doesn't feel great to call `.collect()` and then perform an assertion that the lengths of all the resulting lists are what I expect. It would be much better if I could easily convert the struct to a list/array, or if somehow the `str.splitn()` & `str.split_exact()` functions had a way to specify what you wanted the return type to be.

While I didn't write this, I found this stackoverflow post asking essentially the same thing: https://stackoverflow.com/questions/76772997/convert-struct-to-list

I searched through the Github issues and didn't find anything related, although I apologize if I overlooked something.

Edit: just incase it wasn't clear, I'm asking about the Python API

**Comment by cmdlineluser** [comment]
With the split functions you can now `concat_list` with struct wildcard unpacking. 

```python
df = pl.DataFrame({
    "foo": ["a/b/c", "d/e/f/g"]
})

df.with_columns(
    pl.concat_list(
        pl.col.foo.str.splitn("/", 3).struct.field("*")
    )
    .alias("fields")
)

# shape: (2, 2)
# ┌─────────┬───────────────────┐
# │ foo     ┆ fields            │
# │ ---     ┆ ---               │
# │ str     ┆ list[str]         │
# ╞═════════╪═══════════════════╡
# │ a/b/c   ┆ ["a", "b", "c"]   │
# │ d/e/f/g ┆ ["d", "e", "f/g"] │
# └─────────┴───────────────────┘
```

**Comment by cmdlineluser** [comment]
Found the previous discussion on this topic:

- https://github.com/pola-rs/polars/issues/13913

**Comment by Crypto-Spartan** [comment]
Thank you!

**Comment by deanm0000** [comment]
I'm going to close this as a duplicate
