### ISSUE TITLE
Implement polars.log and polars.exp

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#1871]
Polars currently lacks a logarithm transformation.

It's possible to use .apply(np.log), but that's very slow for large dataframes. It would be nice if this transformation was native. 

The same applies to the .exp transformation. 

Wanted functions:

- polars.log
- polars.log1p (see np.log1p)
- polars.exp
- polars.expm1 (see np.expm1)

**Comment by ritchie46** [comment]
You don't have to use `apply`. Polars expressions and polars series support numpy `ufuncs`.

You can just call `np.log` on a Series or an expression.

**Comment by ghuls** [comment]
```python
df.with_column(np.log(pl.col("a").alias("np_log"))
```

**Comment by ritchie46** [comment]
```python
df = pl.DataFrame({
    "a": [1, 2, 3],
    "b": [4, 5, 6]
})

df.select([
    np.log(pl.all()).suffix("_log")
])
```

```
shape: (3, 2)
┌────────────────────┬────────────────────┐
│ a_log              ┆ b_log              │
│ ---                ┆ ---                │
│ f64                ┆ f64                │
╞════════════════════╪════════════════════╡
│ 0.0                ┆ 1.3862943611198906 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0.6931471805599453 ┆ 1.6094379124341003 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1.0986122886681098 ┆ 1.791759469228055  │
└────────────────────┴────────────────────┘
```

**Comment by danielgafni** [comment]
Oh, that's very nice! 

Somehow I missed this from the documentation. 

I guess the issue is not so relevant anymore.

**Comment by ritchie46** [comment]
Yes, I will add this example in the user guide on a more prominent place. :)
