### ISSUE TITLE
JSONL parsing fails when line is just `{}`

### ISSUE THREAD

**Issue by geowa4** [pola-rs/polars#18726]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

https://github.com/ayax79/polars_empty_bracket/blob/ac951b2e51e4512d7d503fd44d539cf4732fedc1/src/main.rs

Input file:
```jsonl
{"foo": "bar"}
{}
```

Rust reproducer:
```rust
use std::sync::Arc;

use polars::prelude::{DataType, Field, LazyFileListReader, LazyJsonLineReader, Schema};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let file = "empty_brackets.ndjson";

    let schema = Arc::new(Schema::from_iter(vec![
        Field::new("foo", DataType::String)
    ]));

    let df = LazyJsonLineReader::new(file)
        .with_schema(Some(schema))
        .finish()?
        .collect()?;

    println!("{:?}", df);

    Ok(())
}
```

### Log output

```shell
invalid JSON: unexpected end of file
```

### Issue description

If the input is JSONL and any line contains just `{}`, then parsing the file will fail. Converting this to a JSON document will succeed.

```json
[
  {"foo": "bar"},
  {}
]
```

### Expected behavior

Empty objects are tolerated like they are in JSON arrays.

### Installed versions

<details>

polars = "0.43.1"

</details>

**Comment by cmdlineluser** [comment]
I cannot reproduce this.

```
shape: (2, 1)
┌──────┐
│ foo  │
│ ---  │
│ str  │
╞══════╡
│ bar  │
│ null │
└──────┘
```

Also works for me using `read_ndjson` / `scan_ndjson` in Python. (Polars 1.7.1)

**Comment by geowa4** [comment]
My apologies. It appears this issue was in 0.41 but not the latest 0.43.1. https://github.com/geowa4/polars_empty_bracket is working with the current latest.

![jsonl](https://github.com/user-attachments/assets/c0e0c3b5-24e5-4255-ad99-36d6d99446d0)
