### ISSUE TITLE
`pl.col('a').is_in(['val1', None])` does not return true for null cells in col

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#18728]
### Description

Please see the following code snippet depicting the behaviour I wish was described in the `col.is_in()` docstring, and my emotional reactions to such.

Please describe this functionality (that having `None` in the `is_in` argument does not select null values).

```python
def test_col_is_in_with_nulls():
	df = pl.DataFrame({
		'a': [1, 2, None, 4],
		'b': [1, 2, 3, 4],
	})
	
	df1 = df.filter(pl.col('a').is_in([2, None]))
	
	# Assert that is_in() selects the nulls row.
	# This, however, is not the case. Ugh. I wish it worked like this.
	#assert df1.height == 2

	# Assert that is_in() does not select the nulls row.
	# This is the real behaviour, which makes me sad.
	assert df1.height == 1
	
```

### Link

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_in.html#polars.Expr.is_in

**Comment by cmdlineluser** [comment]
Should it warn I wonder? 

(in)equality does:

```python
df.filter(pl.col.a == None)
# UserWarning: Comparisons with None always result in null. 
# Consider using `.is_null()` or `.is_not_null()`.
```

**Comment by DeflateAwning** [comment]
Would be a fantastic warning, yes!

**Comment by npielawski** [comment]
We should add an entry in the documentation as well.

I am working on a healthcare dataset containing diagnoses, but some patients don't have one (represented as null). I tried to remove the rare diagnoses by filtering them using a denylist:
```python
df.filter(~pl.col("diagnosis").is_in(deny_list))
```
But this removed all the null rows, that is, all patients without a diagnosis. It doesn't feel like this should be the default behavior for this specific use case.

Note that the nulls are lost no matter the condition, so:
```python
df.filter(pl.col("diagnosis").is_in(deny_list))
```
would keep only the terms in the deny list, but again the nulls are discarded.

**Comment by cmdlineluser** [comment]
Yeah, the (in)equality operations have `*_missing` null variant methods:

- [`.eq_missing()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.eq_missing.html#polars.Expr.eq_missing)
- [`.ne_missing()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.ne_missing.html#polars.Expr.ne_missing)

I'm not sure if an equivalent `is_in_missing()` would make sense?

@DeflateAwning's other feature request was to enable a param to control the behaviour.

- https://github.com/pola-rs/polars/issues/18730

**Comment by DeflateAwning** [comment]
#12591 proposes `is_in_missing`, actually. Neat!

**Comment by npielawski** [comment]
If we look at the use case I described above:
```
> df = pl.DataFrame({"A": ["a", "b", None], "B": [0, 1, 2]})
shape: (3, 2)
┌──────┬─────┐
│ A    ┆ B   │
│ ---  ┆ --- │
│ str  ┆ i64 │
╞══════╪═════╡
│ a    ┆ 0   │
│ b    ┆ 1   │
│ null ┆ 2   │
└──────┴─────┘

> df.filter(~pl.col("A").is_in(["b"])) # Same as df.filter(~pl.col("A").is_in_missing(["b"]))
shape: (1, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 0   │
└─────┴─────┘
```

The condition `is_in_missing` wouldn't solve my problem / use case because the condition is negated, so null values are still discarded. I am assuming the behaviour is nulls == nulls.

```
> df.select(~pl.col("A").is_in(["b"]))
shape: (3, 1)
┌───────┐
│ A     │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ false │
│ null  │
└───────┘

> df.select(~pl.col("A").is_in_missing(["b"]))
shape: (3, 1)
┌───────┐
│ A     │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ false │
│ false │
└───────┘
```

I think it would be better to have a flag, like `set_nulls_to` that can take three values: {None, True, False}, where:
- None: default behaviour, i.e. nulls are nulls
- True: nulls are set to True
- False: nulls are set to False

Maybe the easiest way at the moment is to `fill_null` on the condition:
```
> df.filter(~pl.col("A").is_in(["b"]).fill_null(False))
shape: (2, 2)
┌──────┬─────┐
│ A    ┆ B   │
│ ---  ┆ --- │
│ str  ┆ i64 │
╞══════╪═════╡
│ a    ┆ 0   │
│ null ┆ 2   │
└──────┴─────┘
```

In any case, there is no mention of that three-valued logic in the documentation [page of `is_in`](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_in.html).

**Comment by cmdlineluser** [comment]
Perhaps I'm mistaken, but I thought that is what the `_missing` variant did, e.g.

```python
df.filter(~pl.col("A").eq_missing("b"))
# shape: (2, 2)
# ┌──────┬─────┐
# │ A    ┆ B   │
# │ ---  ┆ --- │
# │ str  ┆ i64 │
# ╞══════╪═════╡
# │ a    ┆ 0   │
# │ null ┆ 2   │
# └──────┴─────┘
```

**Comment by mcrumiller** [comment]
We updated the documentation elsewhere to say `where None is treated as a disctinct value`, which I believe covers fully covers the definition. Only `None` is equal to `None`.

I would say `[null].is_in_missing(["b"])` should evaluate to `False` in that sense.

@stinodego do you have thoughts on this proposal (perhaps using #12591 as the main issue)? If you think it's a reasonable addition to the API I can take a crack at it.

**Comment by mcrumiller** [comment]
Oh, and @DeflateAwning regarding the original issue, the [documentation for `filter`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.filter.html) clearly states:

> Rows where the filter does not evaluate to True are discarded, including nulls.

i.e. only `True` evaluations make it through the filter.

**Comment by DeflateAwning** [comment]
As this is intended behaviour, and #12591 clearly requests the two possible solutions, I will close this issue in favour of the other.

**Comment by DeflateAwning** [comment]
Just for completeness, this issue is resolved in https://github.com/pola-rs/polars/pull/21426
