### ISSUE TITLE
Parquet read with `streaming=True` shifts/drops rows

### ISSUE THREAD

**Issue by jkc1** [pola-rs/polars#18739]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.scan_parquet("bug.parquet")

df.group_by(
    pl.col("timestamp").dt.truncate("1mo").alias("period")
).agg(
    pl.col("score").len(),
).collect(
    streaming=True
).sort(
    by="period"
)
```

### Issue description

The streaming engine produces inconsistent results on a simple operation (`pl.col(...).len()`) in v1.7.1 (and 1.7.0, although that was yanked). I confirmed that the erroneous behavior does not exist in 1.5.0 or 1.6.0.

Unfortunately I cannot share the underlying parquet that produced this error. I tried to reproduce with some generated data but was unable to come up with an example that demonstrated the bug. I will do my best to assist debugging though.

### Expected behavior

The streaming engine and the non-streaming engine should produce the same output.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.11.10 (main, Sep  9 2024, 11:18:18) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce. (Using lineitem.parquet from tpch)

```python
pl.scan_parquet('lineitem.parquet').select(pl.len()).collect(streaming=True).item()
# 6001215

pl.scan_parquet('lineitem.parquet').select(pl.len()).collect(streaming=False).item()
# 6001215
```

```python
pl.scan_parquet('lineitem.parquet').collect(streaming=True).height
# 6001204

pl.scan_parquet('lineitem.parquet').collect(streaming=False).height
# 6001215
```

**Comment by ritchie46** [comment]
Ai.. Could someone get a bisect on this one?

**Comment by coastalwhite** [comment]
My guess is that is again a Parquet issue... I will see if I can find an MRE and solve it.

**Comment by cmdlineluser** [comment]
This seems to be the commit where it changes for me:

- https://github.com/pola-rs/polars/pull/18584

**Comment by cmdlineluser** [comment]
It seems like it may have something to do with the number of row groups.

```python
pl.DataFrame({"id": range(40)}).write_parquet("18739.parquet", row_group_size=3)

print(pl.scan_parquet("18739.parquet").collect(streaming=False).height)
print(pl.scan_parquet("18739.parquet").collect(streaming=True).height)
```
```
40
39
```

**Comment by ritchie46** [comment]
> This seems to be the commit where it changes for me:
> 
> https://github.com/pola-rs/polars/pull/18584

Thanks a lot for the help here @cmdlineluser (as always :) )

@nameexhaustion can you take this regression next week?
