### ISSUE TITLE
Option to use fixed point floats

### ISSUE THREAD

**Issue by arnabanimesh** [pola-rs/polars#18741]
### Description

Floating point calculations come with its own set of problems when it comes to accuracy. Some industries (e.g. financial industry) might want accurate representation upto the last decimal even at the expense of performance.

It can be feature gated and optional. It will help mitigate edge cases when comparing numbers.

**Comment by d-reynol** [comment]
look at pl.Decimal

**Comment by arnabanimesh** [comment]
It is still WIP and unstable though. There should be a tracking issue. Keeping this issue open as I won't be able to use this data type due to all the existing open issues related to `pl.Decimal` and also since there's no tracking issue for stabilization.
