### ISSUE TITLE
Add a non-equi joins and `join_where` to `joins` section of the user guide

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#18749]
### Description

-

### Link

-

**Comment by braaannigan** [comment]
Assign to me @ritchie46, might be back in touch if I've got some questions

**Comment by rodrigogiraoserrao** [comment]
@braaannigan do you have any work done on this? Do you mind if I steal this issue from you?

**Comment by rodrigogiraoserrao** [comment]
In that case, I hope you don't mind but I'll be taking over this issue. I'm currently reworking parts of the documentation and the section on joins is one of them. It doesn't make sense for you to spend your time working on this and then me having to go over you and moving things around / changing stuff.

**Comment by rodrigogiraoserrao** [comment]
> @rodrigogiraoserrao Ah, I was just going to finish it tonight. Thanks for the work you're doing though

Sorry for the overlap.
Feel free to take a look at the linked PR and make any suggestions you might have.
