### ISSUE TITLE
`cum_max` error message for invalid datatype refers to `cum_min`

### ISSUE THREAD

**Issue by t-ded** [pola-rs/polars#18754]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({'a': ['foo', 'bar']}).with_columns(pl.col('a').cum_max())
```

### Log output

```shell
InvalidOperationError: `cum_min` operation not supported for dtype `str`
```

### Issue description

`cum_max` uses `polars_bail!(opq = cum_min, dt)`, resulting in incorrect error message when applied to invalid datatypes such as `str`

I would like to take this as my first issue if possible? :) 
Proposed very simple fix is simply changing line 207 to `polars_bail!(opq = cum_max, dt)`, please let me know if there is anything more to do in this regard

> https://github.com/pola-rs/polars/blob/4894e24d34a8388ef9155b24deab78ed29fe1ef5/crates/polars-ops/src/series/ops/cum_agg.rs#L191C1-L209C2

### Expected behavior

```shell
InvalidOperationError: `cum_max` operation not supported for dtype `str`
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            Linux-6.8.0-44-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

**Comment by stinodego** [comment]
Please feel free to open a PR!
