### ISSUE TITLE
Python - Add support to the invert operator `~` to negate expressions and columns

### ISSUE THREAD

**Issue by oryanperl** [pola-rs/polars#18793]
### Description

Add support for the pythonic syntax of `~` to check expression are false (similar to `not_()`)
This syntax support is both syntactic sugaring and code conversion from other data engineering libraries (e.g. the pythonic Apache Spark wrapper `pyspark`)

note: I could and would be happy to implement this small feature myself :)

**Comment by cmdlineluser** [comment]
Is this already supported?

```python
>>> pl.select(pl.lit(True))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ true    │
└─────────┘
```
```python
>>> pl.select(~pl.lit(True))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ false   │
└─────────┘
```

**Comment by oryanperl** [comment]
> Is this already supported?
> 
> ```python
> >>> pl.select(pl.lit(True))
> shape: (1, 1)
> ┌─────────┐
> │ literal │
> │ ---     │
> │ bool    │
> ╞═════════╡
> │ true    │
> └─────────┘
> ```
> 
> ```python
> >>> pl.select(~pl.lit(True))
> shape: (1, 1)
> ┌─────────┐
> │ literal │
> │ ---     │
> │ bool    │
> ╞═════════╡
> │ false   │
> └─────────┘
> ```

my bad, you are completely correct
