### ISSUE TITLE
Edge-case with type inference when reading small CSV files

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#1881]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.23

#### What operating system are you using polars on?

Windows/Mac

#### Describe your bug.

Found a small edge-case where EOF is not respected as EOL for type inference purposes; adding a linebreak char fixes the issue.

#### What are the steps to reproduce the behavior?

Minimal test-case:

```python
with open( 'test01.csv', 'w' ) as f1:
    f1.write( 'colx,coly\nabcdef,1234' )    # EOF _without_ trailing EOL
with open( 'test02.csv', 'w' ) as f2:
    f2.write( 'colx,coly\nabcdef,1234\n' )  # EOF _with_ trailing EOL

import polars as pl
df1 = pl.read_csv( f1.name )
df2 = pl.read_csv( f2.name )

df1.dtypes  #  integer value not inferred (loaded as string)
>> [polars.datatypes.Utf8, polars.datatypes.Utf8]

df2.dtypes  # integer value correctly inferred
>> [polars.datatypes.Utf8, polars.datatypes.Int64]

#  df1                  df2
# ┌────────┬──────┐    ┌────────┬──────┐
# │ colx   ┆ coly │    │ colx   ┆ coly │
# │ ---    ┆ ---  │    │ ---    ┆ ---  │
# │ str    ┆ str  │    │ str    ┆ i64  │   <<< dtype doesn't match
# ╞════════╪══════╡    ╞════════╪══════╡
# │ abcdef ┆ 1234 │    │ abcdef ┆ 1234 │
# └────────┴──────┘    └────────┴──────┘

```

#### What is the expected behavior?

Reading a minimal CSV that has EOF without final EOL should return the same inference result in both cases. (The CSV doesn't _have_ to be a one-liner to see this - can also occur if all prior values in the column are blank, and the last line is not). Cheers :)

**Comment by ritchie46** [comment]
Thanks for the issue report. Makes sense
