### ISSUE TITLE
High memory usage when calculating variance?

### ISSUE THREAD

**Issue by ts826848** [pola-rs/polars#18824]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
# ~7.6 GB in Task Manager
s = pl.repeat(1.5, 1_000_000_000, eager=True)
s.var() # Memory usage jumps to >15 GB before result returned
```

### Log output

```shell
No log output?
```

### Issue description

Potential culprit might be `squared` in https://github.com/pola-rs/polars/blob/938494534f66914afe2815f1d718e0024bdf224b/crates/polars-core/src/chunked_array/ops/aggregate/var.rs#L17-L32

I'm not a stats/numerical analysis expert so I'm not sure whether the extra allocation is strictly necessary for numerical stability/other reasons. It feels like it shouldn't be necessary though?

Looks like NumPy has a similar issue? https://github.com/numpy/numpy/issues/13199 (var, std memory consumption)

### Expected behavior

Expected memory usage to not jump when calculating the variance

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.11.6
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by ritchie46** [comment]
It is perfectly fine to have 2x the memory. You have an input buffer and an output buffer. That's already 2x. In this case there is an intermediate temporary, which afaic is fine.
