### ISSUE TITLE
`pl.Array` + `pl.lit` PanicException Cannot apply operation on arrays of different lengths

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#18831]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "A": [[0.1, 0.2], [0.3, 0.4]]
}).cast(pl.Array(float, 2))

df.select(pl.all() * pl.lit([3, 5], pl.Array(float, 2)))
# thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/ops/arity.rs:815:14:
# Cannot apply operation on arrays of different lengths
# PanicException: Cannot apply operation on arrays of different lengths
```

### Issue description

Adding as a column first works as expected.

```python
(df.with_columns(pl.lit([3, 5], pl.Array(float, 2)))
   .select(pl.nth(0) * pl.nth(1))
)

# shape: (2, 1)
# ┌───────────────┐
# │ A             │
# │ ---           │
# │ array[f64, 2] │
# ╞═══════════════╡
# │ [0.3, 1.0]    │
# │ [0.9, 2.0]    │
# └───────────────┘
```

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit
Python:              3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.1
pyarrow              15.0.2
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Looks like the arrays are expanded into their underlying physical arrays (e.g. f64 here), so it thinks that the literal value is length 2.

**Comment by cmdlineluser** [comment]
Thanks @ritchie46 

Just testing the new list arithmetic with the same example - it doesn't Panic, but it does raise.

Would a similar `broadcast_list()` need to be added?

```python
df = pl.DataFrame({
    "A": [[0.1, 0.2], [0.3, 0.4]]
})

df.with_columns(pl.all() * pl.lit([3, 5]))
# InvalidOperationError: can only do arithmetic operations on Series of the same size; got 2 and 1
```

```python
(df.with_columns(pl.lit([3, 5]))
   .select(pl.nth(0) * pl.nth(1))
)
# shape: (2, 1)
# ┌────────────┐
# │ A          │
# │ ---        │
# │ list[f64]  │
# ╞════════════╡
# │ [0.3, 1.0] │
# │ [0.9, 2.0] │
# └────────────┘
```

**Comment by ritchie46** [comment]
Yes, the new list arithemetic should indeed broadcast. @itamarst would you be interested in that one, as you worked on that feature?

**Comment by itamarst** [comment]
My plan once #8006 is implemented is to work on scalars next, yes.

**Comment by itamarst** [comment]
Oh, I guess this isn't quite the same as numeric scalars, which is what I was thinking of, but an extension.

**Comment by cmdlineluser** [comment]
I did make a naive copy of the `broadcast_array()` PR in https://github.com/pola-rs/polars/pull/18858 as I thought it could be in time for 1.8 to have it working for both list/array.

But it may be more appropriate to leave it to you @itamarst? 

I'm not too familiar with the list code there, so not entirely sure if that is all that was needed.

**Comment by itamarst** [comment]
Definitely not an expert on how broadcasting ought to work, but I did add a bunch of comments on additional testing that would be useful based on my experience so far.
