### ISSUE TITLE
Add an `is_not_in` expression

### ISSUE THREAD

**Issue by apcamargo** [pola-rs/polars#18877]
### Description

Right now, to check if elements of an expression are present in a Series/list, we need to combine `is_in` with `not_`. For instance:

```python
import polars as pl

to_exclude = ["b", "d"]
df = pl.DataFrame(
    {
        "A": ["a", "b", "c", "d"],
        "B": [1, 2, 3, 4],
    }
)
df.filter(pl.col("A").is_in(to_exclude).not_())
```

Some expressions, such as `is_nan` and `is_finite` have "negative" versions (`is_not_nan` and `is_infinite`), so it could make sense to also have a `is_not_in` expression that would have the same effect as `is_in + not_`.

**Comment by cmdlineluser** [comment]
This has been requested a few times:

- https://github.com/pola-rs/polars/issues/6574
- https://github.com/pola-rs/polars/issues/16419
