### ISSUE TITLE
Cargo.lock has not been updated for py-polars 1.8.1

### ISSUE THREAD

**Issue by gyscos** [pola-rs/polars#18875]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

From this repo:

```bash
cargo fetch --locked
```

### Log output

```shell
error: the lock file (...)/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
```


### Issue description

The `Cargo.lock` file has not been updated when py-polars 1.8.1 was released. As such, it cannot be used as-is.

This is a problem when packaging py-polars for distributions, as we often use "locked" builds.

### Expected behavior

Build can proceed with the `Cargo.lock` as-is.

### Installed versions

No feature gate.

**Comment by ritchie46** [comment]
Right, there must have gone something wrong. Will be fixed by a new release. Is this an issue for current release? I.e. what will break?

**Comment by coastalwhite** [comment]
This prevents packaging on a lot of platforms outside of PyPi.

**Comment by ritchie46** [comment]
1.8.2 will be released as patch tonight.
