### ISSUE TITLE
Cannot create literal for pd.Timedelta with allow_object=False

### ISSUE THREAD

**Issue by yiteng-guo** [pola-rs/polars#18906]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd

pl.select(a=pl.lit(pd.Timedelta(minutes=1)))

TypeError: cannot create expression literal for value of type Timedelta: Timedelta('0 days 00:01:00')

Hint: Pass `allow_object=True` to accept any value and create a literal of type Object.
```

### Issue description

I believe this is the same as #18447 and something like #18497 should fix it.

### Expected behavior

It should allow pd.Timedelta since it's a subclass of datetime.timedelta.

### Installed versions

Can't do this since it's on the work laptop.

**Comment by henryharbeck** [comment]
Like https://github.com/pola-rs/polars/issues/18447, this is a regression from 1.5. 
FYI @ritchie46 @MarcoGorelli @mcrumiller

**Comment by mcrumiller** [comment]
In this case it's cause a `pd.Timedelta` object has a `_s` attribute and so our convert thinks it's a list/series. I think we need a better way to detect temporal subclasses and deal with them, this has been coming up a lot.
