### ISSUE TITLE
Exporting StringView Array to Arrow C Data Interface sets wrong number of buffers

### ISSUE THREAD

**Issue by WillAyd** [pola-rs/polars#18909]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Having a hard time with the MRE - @kylebarron might have some ideas. However, through a third party library I've built that exchanges data using the Arrow C Data interface, I am starting with data like:

```python
pl.DataFrame({"str": ["foo", "bar", "baz"]})
```

When exporting, nanoarrow ends up throwing an error that:

```
Expected array with 2 buffer(s) but found 3
```

Stepping through gdb, I do see a String View type with `n_buffers` set to 3, although the third buffer looks like garbage:

```
(gdb) p array_view->storage_type
$6 = NANOARROW_TYPE_STRING_VIEW
(gdb) p array
$7 = (const struct ArrowArray *) 0x7fff81887e50
(gdb) p *array
$8 = {length = 3, null_count = 1, offset = 0, n_buffers = 3, n_children = 0, buffers = 0x7fff81858aa0, children = 0x8, dictionary = 0x0, 
release = 0x7fff82e5afa0 <polars_arrow::ffi::array::c_release_array>, private_data = 0x7fff81887e00}
(gdb) p array->buffers[0]
$9 = (const void *) 0x7fff8e4096c0
(gdb) p array->buffers[1]
$10 = (const void *) 0x7fff72e11000
(gdb) p array->buffers[2]
$11 = (const void *) 0x8
```

In spite of the error message and what is shown when debugging, I am actually expecting polars to be sending 4 buffers:

1. Validity
2. Inline/Ref Data
3. Variadic buffer holding "longer_than_prefix_size"
4. Length buffer whose first element is 23 (length of "longer_than_prefix_size")

### Issue description

Number of buffers when exporting view types seems wrong

### Expected behavior

Should be four buffers as noted above

### Installed versions

1.8.1

**Comment by kylebarron** [comment]
Hmm but pyarrow can read string view data from polars. I imagine that would fail if polars were exporting incorrect data, right?

**Comment by WillAyd** [comment]
That's a good point - let me see what else I can find

**Comment by WillAyd** [comment]
Haven't full pinpointed yet but didn't realize polars is actually exporting a LargeString array instead of a StringView

```python
(Pdb) pl.DataFrame({"str": ["foo", "longer_than_prefix_size", "baz"]}).to_arrow()
pyarrow.Table
str: large_string
----
str: [["foo","longer_than_prefix_size","baz"]]
```

Assuming that's intentional, I think something might be getting mixed up (the schema still says it should be a STRING_VIEW) but still need to troubleshoot further

**Comment by eitsupi** [comment]
Just a note: does it look like the R package has no bugs?
(In R, switches between using StringView or LargeString depending on the `compat_level` argument)

```r
> Sys.setenv(NOT_CRAN="true")
> pak::repo_add(rmv="https://community.r-multiverse.org")
> pak::pak(c("apache/arrow-nanoarrow/r", "polars"))
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Updated metadata database: 3.80 MB in 10 files.
✔ Updating metadata database ... done

→ Will install 2 packages.
→ Will download 2 packages with unknown size.
+ nanoarrow   0.5.0.9000 [bld][cmp][dl] (GitHub: 53c9f8f)
+ polars      0.19.1     [bld][cmp][dl]

ℹ Getting 2 pkgs with unknown sizes
✔ Got polars 0.19.1 (source) (2.05 MB)
✔ Got nanoarrow 0.5.0.9000 (source) (1.08 MB)
✔ Downloaded 2 packages (3.13 MB) in 4.2s
ℹ Packaging nanoarrow 0.5.0.9000
ℹ Building polars 0.19.1
✔ Packaged nanoarrow 0.5.0.9000 (3.1s)
ℹ Building nanoarrow 0.5.0.9000
✔ Built nanoarrow 0.5.0.9000 (15.6s)
✔ Installed nanoarrow 0.5.0.9000 (github::apache/arrow-nanoarrow@53c9f8f) (59ms)
✔ Built polars 0.19.1 (1m 7.2s)
✔ Installed polars 0.19.1  (1.2s)
✔ 2 pkgs + 1 dep: kept 1, added 2, dld 2 (NA B) [1m 29.2s]

> polars::pl$DataFrame(str = c("foo", "longer_than_prefix_size", "bar")) |>
      nanoarrow::as_nanoarrow_array_stream(compat_level = TRUE)
<nanoarrow_array_stream struct<str: string_view>>
 $ get_schema:function ()
 $ get_next  :function (schema = x$get_schema(), validate = TRUE)
 $ release   :function ()

> polars::pl$DataFrame(str = c("foo", "longer_than_prefix_size", "bar")) |>
      nanoarrow::as_nanoarrow_array_stream(compat_level = FALSE)
<nanoarrow_array_stream struct<str: large_string>>
 $ get_schema:function ()
 $ get_next  :function (schema = x$get_schema(), validate = TRUE)
 $ release   :function ()
```

**Comment by ritchie46** [comment]
Polars export a large string if you set `compat_level` to `oldest` compatibility. If you set it to `newest` you will get `StringView` and it will be zero copy.

**Comment by WillAyd** [comment]
After digging further I don't think this is a polars issue. It seems like the third buffer is probably being exported to hold the sizes of the variadic buffers, even though they may not exist.

Moving discussion over to https://github.com/apache/arrow-nanoarrow/issues/634 - thanks!
