### ISSUE TITLE
with_columns(pl.lit("02").alias('TEST')) is truncating leading zeroes of numeric-only strings

### ISSUE THREAD

**Issue by KingDarule** [pola-rs/polars#18902]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

test = pl.DataFrame(data = {"TEST": ["1", "2"]})
test = pl.concat([test])
test = (test.with_columns(pl.lit("00002").alias('TEST')))
print(test)
```

### Issue description

with_columns(pl.lit("02").alias('TEST')) is truncating the leading zeroes automatically even though it is a string. Even if I explicitly set the dtype parameter to pl.String.

### Expected behavior

I should still be getting "02" instead of "2"

### Installed versions

<details>

```
Polars 1.8.1
```

</details>

**Comment by barak1412** [comment]
Can't reproduce.
Can you post your full code?

**Comment by coastalwhite** [comment]
It is probably solved by #18888.

**Comment by cmdlineluser** [comment]
I can only replicate broken behaviour on 1.8.0

This prints `02` on >= 1.8.1 for me.

```python
pl.DataFrame({"foo": [1, 2]}).with_columns(pl.lit("02"))
# shape: (2, 2)
# ┌─────┬─────────┐
# │ foo ┆ literal │
# │ --- ┆ ---     │
# │ i64 ┆ str     │
# ╞═════╪═════════╡
# │ 1   ┆ 02      │
# │ 2   ┆ 02      │
# └─────┴─────────┘
 ```

**Comment by KingDarule** [comment]
I can trigger it using this code on 1.8.1:
`import polars as pl

test = pl.DataFrame(data = {"TEST": ["1", "2"]})
test = pl.concat([test])
test = (test.with_columns(pl.lit("00002").alias('TEST')))
print(test)`
