### ISSUE TITLE
Allow lf/df `rename()` to have strict argument and ignore non existing columns

### ISSUE THREAD

**Issue by atigbadr** [pola-rs/polars#18954]
### Description

I was wondering if it's possible to allow lf/df `rename()` to have strict argument and ignore non existing columns just like `drop()` have a strict argument that ignores the non existing columns in case of a drop

Thank you for the amazing work.

**Comment by alexander-beedie** [comment]
Seems reasonable/useful to me 👍

**Comment by nameexhaustion** [comment]
Also fixes https://github.com/pola-rs/polars/issues/17821

**Comment by alexander-beedie** [comment]
> Related #17821

Well-spotted, thx ;)
