### ISSUE TITLE
`eq_missing` mentions `ne` instead of `eq`

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#18976]
### Description

This should be `eq`.

### Link

https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.eq_missing.html

**Comment by gabrilito1** [comment]
![image](https://github.com/user-attachments/assets/8b80976d-dd91-4b57-90a7-94caf7b290dd) this type of fix you means?

**Comment by Plutone11011** [comment]
I would like to contribute to this, would be my first issue.
