### ISSUE TITLE
Float literal formatting outputs different things dependent on where it is used

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#18981]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame().with_columns(a=pl.lit(0.0)).with_columns(b=pl.col(“a”).cast(pl.String), c=pl.lit(0.0).cast(pl.String))
```

Outputs:

```
shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ f64 ┆ str ┆ str │
╞═════╪═════╪═════╡
│ 0.0 ┆ 0.0 ┆ 0   │
└─────┴─────┴─────┘
```

### Issue description

Inconsistency

### Expected behavior

Consistency

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
Yes, this is due to the new scalar. All the formatting of columns should ensure it goes into `polars-core/fmt`.
