### ISSUE TITLE
Feature Request: Support for DataFrame.eval()-like Expression Evaluation in Polars

### ISSUE THREAD

**Issue by akhilesh-chander** [pola-rs/polars#19014]
### Description

I would like to request a feature in Polars that allows dynamic evaluation of expressions on a DataFrame, similar to how pandas.DataFrame.eval() works in Pandas. The ability to evaluate Python-like expressions directly on DataFrames makes it extremely convenient when dealing with complex operations, especially involving multiple columns and potentially multiple DataFrames.

Currently, Polars provides a highly efficient API for manipulating DataFrames using expressions. However, it requires explicit expression syntax (e.g., pl.col('A') + pl.col('B')). While this is very powerful, it lacks the simplicity of string-based dynamic expression evaluation found in Pandas' eval() function.

For example, a feature request on StackOverflow demonstrates the need for dynamic evaluation of an expression from a formula:

[Dynamically Evaluate an Expression from a Formula in Pandas](https://stackoverflow.com/questions/53779986/dynamically-evaluate-an-expression-from-a-formula-in-pandas)

**Comment by ritchie46** [comment]
You can easily do that with `pipe`.

```python
(
    pl.DataFrame({"a": [1, 2], "b": [3, 4]})
    .pipe(lambda df: eval("df['a'] + df['b']"))
)
```

I very much dislike `eval`, so I don;t want to add it as a first class citizen. Polars has a very versatile API and I don't want to add just another way of doing things. It also doesn't promote expressions usage, which is bad as it make things impossible to optimize.

**Comment by alexander-beedie** [comment]
Yup, `eval` is not compelling; lots of downsides... If you find that writing expressions such as `pl.col("colx") + pl.col("coly")` is a little more verbose than you prefer, note that we _also_ support the following compact shorthand, which can save you quite a few keystrokes ;)

```python
from polars import col as c

(c.colx + c.coly)
# same as `pl.col("colx") + pl.col("coly")`
```
 And for any other cases where you really do want strings for some reason, you can use the standard SQL syntax instead of an `eval` hack.

**Comment by deanm0000** [comment]
In light of ritchie's and alexanders comment, I'm going to close this.
