### ISSUE TITLE
[Rust] Moving the `df` macro to the prelude module.

### ISSUE THREAD

**Issue by ibENPC** [pola-rs/polars#1903]
#### Feature request

Moving the `df` macro to the prelude module of the polars-core crate.

#### Reason
The following doesn't work:
```rust
use polars::prelude::*;

let df = df!("A" => &[1, 2, 3]);
```
![image](https://user-images.githubusercontent.com/72026000/143675791-3338630d-9918-464a-abc8-6d33ec0c90a3.png)

The current solution to manipulate for example a `DataFrame` with the common tools is to do:
```rust
use polars::df;
use polars::prelude::*;
```
The ergonomics would be better by only using one line.

**Comment by ritchie46** [comment]
I thought that macros had to be imported specifically. But I am not sure. You can try and add it to the prelude.
