### ISSUE TITLE
`.arr.explode()` fails to raise error for non-Array inputs

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#19049]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [[1, 2, 3]]})

df.select(pl.col.a.arr.explode())
# shape: (3, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# │ 3   │
# └─────┘
```

### Issue description

**Update:** Perhaps a better example is using string inputs:

```python
pl.DataFrame({"a": ["one"]}).select(pl.col.a.arr.explode())
# shape: (1, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ str │
# ╞═════╡
# │ one │
# └─────┘
```

Other methods error as expected:

```python
df.select(pl.col.a.arr.to_struct())

# InvalidOperationError: expected Array type, got: list[i64]
# 
# Resolved plan until failure:
# 
# 	---> FAILED HERE RESOLVING 'select' <---
# DF ["a"]; PROJECT */1 COLUMNS; SELECTION: None
```

### Expected behavior

`InvalidOperationError`

### Installed versions

<details>

```
main
```

</details>

**Comment by barak1412** [comment]
@orlp 
May you please clear @ritchie46 comment here https://github.com/pola-rs/polars/pull/19115?

**Comment by orlp** [comment]
@barak1412 I don't understand what you're asking.

**Comment by barak1412** [comment]
@orlp thanks, @ritchie46 answered me

**Comment by barak1412** [comment]
@orlp May you please assign me? I hope I will open PR today evening.
