### ISSUE TITLE
Docs: Lazy/Schemas/Type checking: Polars does not raise when calling `round(0)` on an `Int64` column

### ISSUE THREAD

**Issue by mlondschien** [pola-rs/polars#19058]
### Description

The example in https://docs.pola.rs/user-guide/lazy/schemas/#type-checking-in-the-lazy-api does not behave as expected. Polars does not raise when calling `round(0)` on an `Int64` column.

### Link

https://docs.pola.rs/user-guide/lazy/schemas/#type-checking-in-the-lazy-api

**Comment by orlp** [comment]
The behavior is intended (https://github.com/pola-rs/polars/pull/17241) but the user guide should be updated.

@rodrigogiraoserrao can you take a look?

**Comment by rodrigogiraoserrao** [comment]
Thanks for reporting this, @mlondschien. I've opened a PR that fixes this.
