### ISSUE TITLE
Cannot build with "dtype-categorical" enabled

### ISSUE THREAD

**Issue by besselfunct** [pola-rs/polars#19063]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```toml
[dependencies]
polars = {version = "0.43.1", features = ["dtype-categorical"]}
```

### Log output

```shell
error[E0599]: no method named `raw_table_mut` found for struct `hashbrown::HashMap` in the current scope
   --> /home/besselfunct/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.43.1/src/chunked_array/builder/list/categorical.rs:145:33
    |
145 |                 self.idx_lookup.raw_table_mut().find_or_find_insert_slot(
    |                                 ^^^^^^^^^^^^^ method not found in `HashMap<KeyWrapper, (), RandomState>`

error[E0599]: no method named `raw_table_mut` found for struct `hashbrown::HashMap` in the current scope
   --> /home/besselfunct/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.43.1/src/chunked_array/builder/list/categorical.rs:164:41
    |
164 |                         self.idx_lookup.raw_table_mut().insert_in_slot(
    |                                         ^^^^^^^^^^^^^ method not found in `HashMap<KeyWrapper, (), RandomState>`

error[E0599]: no method named `raw_table_mut` found for struct `hashbrown::HashMap` in the current scope
  --> /home/besselfunct/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.43.1/src/chunked_array/logical/categorical/builder.rs:43:32
   |
43 |             self.local_mapping.raw_table_mut().find_or_find_insert_slot(
   |                                ^^^^^^^^^^^^^ method not found in `HashMap<KeyWrapper, (), RandomState>`

error[E0599]: no method named `raw_table_mut` found for struct `hashbrown::HashMap` in the current scope
  --> /home/besselfunct/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.43.1/src/chunked_array/logical/categorical/builder.rs:63:26
   |
62 | /                     self.local_mapping
63 | |                         .raw_table_mut()
   | |                         -^^^^^^^^^^^^^ method not found in `HashMap<KeyWrapper, (), RandomState>`
   | |_________________________|
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `polars-core` (lib) due to 4 previous errors
```

### Issue description

Trying to recreate [this](https://docs.pola.rs/user-guide/expressions/aggregation/) example from the user guide when I ran into this issue.

### Expected behavior

`polars-core` should build a MWE with the `dtype-categorical` flag enabled.

### Installed versions

<details>

dtype-categorical

</details>

**Comment by Shoeboxam** [comment]
Hashbrown just updated, with the following section in the changelog:
https://github.com/rust-lang/hashbrown/blob/HEAD/CHANGELOG.md#removed

**Comment by besselfunct** [comment]
I apologize, I'm somewhat of a novice when it comes to `cargo`. I ran the command you suggested, and now I can build, but it looks like my `Cargo.toml` didn't change. Is there a way to include this information in the `Cargo.toml` so that it can be explicitly declared?

**Comment by Shoeboxam** [comment]
I'm not aware of a way to do so via the Cargo.toml.

I'm also observing that my fix above doesn't always work-- cargo somehow still pulls down hashbrown 0.15 when building on other platforms/with cibuildwheel, and I can't seem to control it.

**Comment by Bidek56** [comment]
I am having the same errors compiling `nodejs-polars`, does it mean I need to wait for the next release of `polars-rs`? Thx

**Comment by cuviper** [comment]
Polars is using `.raw_table_mut()`, so it should explicitly enable hashbrown's "raw" feature.
See also: https://github.com/pola-rs/polars/pull/19076#discussion_r1786482537

Yes, indexmap 2.6.0 updated to hashbrown 0.15, but polars will still be using its own hashbrown 0.14.

**Comment by Shoeboxam** [comment]
Thanks, to recap, the Cargo.toml fix is to add the following line to your dependencies:

```toml
hashbrown = { version = "=0.14.5", features = ["raw"] }
```

**Comment by cuviper** [comment]
The precise "=0.14.5" pinning shouldn't be necessary, but that's likely to be the last 0.14 release anyway. The important part is to add the "raw" feature.
