### ISSUE TITLE
LazyFrame PanicException instead of ColumnNotFound error

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#19062]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

(pl.LazyFrame({"foo": [1]})
   .with_row_index()
   .group_by('index')
   .agg(
       pl.col("foo").filter(pl.col("i_do_not_exist"))
   )
).collect()

# thread '<unnamed>' panicked at crates/polars-plan/src/plans/builder_ir.rs:183:18:
# called `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("i_do_not_exist"))
# PanicException: called `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("i_do_not_exist"))
```

### Issue description

It seems to be specific to `Expr.filter()` inside `agg()` and also requires a `with_row_index()` call to reproduce.

It doesn't seem to be a recent regression.

### Expected behavior

`ColumnNotFoundError`

### Installed versions

<details>

```
--------Version info---------
Polars:               1.9.0
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by moshfrid** [comment]
I'm getting a similar (same?) error starting in version 1.9.0.
`df.select(
            pl.col("id"),
            pl.exclude("id").map_elements(
                lambda x: {
                    "el": x,
                    "derived_el": derived(x),
                },
                return_dtype=pl.Struct,
            )
        )`
        
_pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("nested objects are not allowed"))_

**Comment by cmdlineluser** [comment]
@moshfrid I think you could create a new issue for that one - it seems a little different.

(This one errors on 1.0.0 - it is not a recent regression.)
