### ISSUE TITLE
Cannot construct Series with dtype Categorical

### ISSUE THREAD

**Issue by CloseChoice** [pola-rs/polars#1909]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

master

#### What operating system are you using polars on?

Ubuntu 18.04

#### Describe your bug.

```python
import polars as pl
from polars.datatypes import Categorical

pl.Series("cat_series", [None], dtype=Categorical)
```
results in 
```
ValueError: Cannot construct PySeries for type <class 'polars.datatypes.Categorical'>.
```
doesn't work

**Comment by ghuls** [comment]
Fixed in https://github.com/pola-rs/polars/pull/1913
