### ISSUE TITLE
Expose LTS_CPU in a public API

### ISSUE THREAD

**Issue by alonme** [pola-rs/polars#19109]
### Description

I think we should enable users to check if the installed version of polars is LTS_CPU or not programmatically.

I suggest adding this information to `pl.show_versions()`

Would be happy to implement this if maintainers agree to the idea

**Comment by ritchie46** [comment]
Yes, I think we can add that `show_versions`.

**Comment by alonme** [comment]
Ok so i believe i found a couple of issues while working on that

1. The `_POLARS_LTS_CPU` isn't actually set in the build process!
This means that the `check_cpu_flags` doesn't exit early - however because the `_POLARS_FEATURE_FLAGS` is changed to match the `lts-cpu` mode - everything works?

Reproduction:
```bash
> pip install polars-lts-cpu --force-reinstall --quiet
> cat .venv2/lib/python3.11/site-packages/polars/_cpu_check.py | grep "LTS_CPU = "
_POLARS_LTS_CPU = False
```

The problem is that the sed command replaces the "old" name of the variable `_LTS_CPU` and not `_POLARS_LTS_CPU` https://github.com/pola-rs/polars/blob/a0ec630b25aa847699f9c2d7389fee84749a6491/.github/workflows/release-python.yml#L178


2. Minor: 
the wheel seems to contain a redundant file called `_cpu_check.py''`
```bash
> ls .venv/lib/python3.11/site-packages/polars/_cpu_*
.venv2/lib/python3.11/site-packages/polars/_cpu_check.py   .venv2/lib/python3.11/site-packages/polars/_cpu_check.py''
```

**Comment by orlp** [comment]
I think we can remove the `_POLARS_LTS_CPU` variable. The comment justifying it is:

```
# Set to True during the build process if we are building a LTS CPU version.
# The risk of the CPU check failing is then higher than a CPU not being supported.
_POLARS_LTS_CPU = False
```

This was initially done as a conservatism when the CPU check was introduced. But now that it's been in Polars for quite a while I think we can safely say it works on `polars-lts-cpu` as well, and has actually diagnosed for people with CPUs that are too old even for LTS: <https://github.com/pola-rs/polars/issues/18956>.

However, I messed up and the code actually replaces the wrong variable as you noticed, so we were never conservative in the first place, without any issues.

So at this point I would suggest making a PR that does set `_POLARS_LTS_CPU` correctly but removes the bypass and always runs the CPU check also on `lts-cpu`.

**Comment by alonme** [comment]
@orlp sounds good - i'll do that

**Comment by alonme** [comment]
@ritchie46 any chance you can build macos wheels so i can verify that the github actions change works? (there was a miss there originally so i would like to make sure all works now)

**Comment by ritchie46** [comment]
> ally so i would like to make sure all works now)

You can test that on your fork.
