### ISSUE TITLE
native support for `digitize`

### ISSUE THREAD

**Issue by sherlyn99** [pola-rs/polars#19107]
### Description

I had to use np.histogram and np.digitize for some binning process and noticed that polars has a built-in hist function. Is there anyway that polars can provide native support for something like [np.digitize](https://numpy.org/doc/2.0/reference/generated/numpy.digitize.html)?

**Comment by cmdlineluser** [comment]
It's not something I've used, but looking at the docs - it says it uses searchsorted?

> [numpy.digitize](https://numpy.org/doc/2.0/reference/generated/numpy.digitize.html#numpy.digitize) is implemented in terms of [numpy.searchsorted](https://numpy.org/doc/2.0/reference/generated/numpy.searchsorted.html#numpy.searchsorted)

Which Polars does have[^1]:

```python
bins = pl.Series([0.0, 1.0, 2.5, 4.0, 10.0])

pl.DataFrame({
    "vals": [0.2, 6.4, 3.0, 1.6],
}).with_columns(    
    inds = pl.lit(bins).search_sorted(pl.col.vals)
)
```
```
# shape: (4, 2)
# ┌──────┬──────┐
# │ vals ┆ inds │
# │ ---  ┆ ---  │
# │ f64  ┆ u32  │
# ╞══════╪══════╡
# │ 0.2  ┆ 1    │
# │ 6.4  ┆ 4    │
# │ 3.0  ┆ 3    │
# │ 1.6  ┆ 2    │
# └──────┴──────┘
```

[^1]: ttps://docs.pola.rs/api/python/stable/search.html?q=search_sorted

**Comment by iliya-malecki** [comment]
what are the differences between this and pl.cut?

**Comment by sherlyn99** [comment]
Thank you both @iliya-malecki @cmdlineluser!

`pl.cut` is exactly what I am looking for. Both `pl.cut` and `np.digitize` assign bin number to data points provided, with one caveat. `pl.cut` returns bin labels as a list of strings where `np.digitize` can auto assign numeric bin number as labels. 

For example, given a dataframe `pos`
```
genome_id	start	stop	sample_id
str	i64	i64	str
"G000006605"	5	20	"A"
"G000006605"	10	17	"A"
"G000006605"	11	15	"A"
"G000006605"	54	59	"A"
"G000006605"	71	76	"B"
"G000006605"	95	99	"B"

```
In the case of `np.digitize`
```
pl.Series("start_bin_idx", np.digitize(pos.select(pl.col('start')).to_series(), bins=bin_edges))
```
 gives
```
start_bin_idx
--
i64
1
2
2
6
8
1
```

whereas in the case of `pl.cut`
```
pos.select(pl.col('start')).to_series().cut(bin_edges, labels=np.arange(len(bin_edges)+1), left_closed=True).alias('start_bin_idx')
```
This will raise a type error because labels have to be a list of strings. 

Currently I am converting numeric labels to strings first, run `pl.cut`, and then cast the results back to `int`.
```
pos.select(pl.col('start')).collect().to_series().cut(bin_edges, labels=np.arange(len(bin_edges)+1).astype(str), left_closed=True).cast(pl.Int64).alias('start_bin_idx')
```

This gives 
```
start_bin_idx
--
i64
1
2
2
6
8
10
```
same as the output of `np.digitize`

It would be nice to allow numeric labels or auto assign numeric bin labels when, say, `labels` are not provided. Having numeric bin labels facilitates convenient downstream operations like shifting all bin numbers by 1 to adjust for 0-indexing, or finding the range of bins covered between two bin labels. 

Thanks!

**Comment by orlp** [comment]
@Shoeboxam That was actually what I was considering after writing that, yes :)
