### ISSUE TITLE
CsvReader example in examples folder doesn't work

### ISSUE THREAD

**Issue by mmorley0395** [pola-rs/polars#19129]
### Description

Hi, 

Forgive me if there's something I'm missing here, but the read_csv piece of examples shows that you can use methods like 'has_header' or 'with_separator'. If I'm reading the docs correctly for 0.43.1, those methods are not available for CsvReader. I understand that there is also a CsvReadOptions struct, but I'm not sure how to use it or pass it into the reader (I understand that you can use it standalone and just pass in a path, as in the user guide, but I'm trying to pass in info from stdout, which as I understand requires that I use CsvReader. 

The main issue is making sure the code works in the example, and as a bonus I'm wondering if anyone can tell me how to use CsvReadOptions with CsvReader, since it seems like CsvReader has had most of it's methods pruned out and moved into the options struct. 

### Link

https://github.com/pola-rs/polars/blob/main/examples/read_csv/src/main.rs

**Comment by cmdlineluser** [comment]
Looks like there are some examples in the tests:

https://github.com/pola-rs/polars/blob/1f480361aa7986badf550baa13616621399a4583/crates/polars/tests/it/io/csv.rs#L269-L273
