### ISSUE TITLE
Consider version-specific wheels, rather than abi3 with lowest supported version

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#19145]
### Description

Some motivations:

* `vectorcall` calling convention was added to Python's Stable ABI only in 3.12, but is available starting 3.9. Supposedly it can make calls from Python into extension code much faster. This suggests that version-specific wheels would be faster in scenarios where users are passing many Python objects to/from Polars.
* The buffer API was only added to the Stable ABI in 3.11, so it can't be used until October 2026.

PyO3 documentation explicitly talks about optimizations it can't use when doing `abi3` wheels (https://pyo3.rs/v0.22.3/building-and-distribution.html#missing-features).

Given that the main motivation is performance, probably someone who have to pick a meaningful benchmark and see if the speedup is worth the extra hassle.

**Comment by ritchie46** [comment]
Pypi isn't to fond of using much space and would ask us to slow down our release cadence. It would mean a lot more wheels, a very long release pipeline (several hours), and performance critical code shouldn't callback into python. I don't think it's worth it.
