### ISSUE TITLE
Confusing warning when calling read_csv() with fsspec URL

### ISSUE THREAD

**Issue by BartSchuurmans** [pola-rs/polars#19150]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.read_csv("local:///tmp/good.csv")
```

### Log output

```shell
/home/minnozz/src/example.py:3: UserWarning: Polars found a filename. Ensure you pass a path to the file instead of a python file object when possible for best performance.
  pl.read_csv("local:///tmp/good.csv")
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
```

### Issue description

The text of the warning is confusing. What Polars received (a filename) and what would be optimal (a path to the file) sound identical to me; one of those is probably wrong.

### Expected behavior

Aside from the text of the warning, I also did not expect to receive this warning when using fsspec URLs. I believe in an earlier version you got this warning when you passed an open file to a read function, but passing an open file no longer triggers this warning.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.7 (main, Oct  1 2024, 08:52:12) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.1.2
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by benrutter** [comment]
Anyone the status of this? I haven't contributed to polars before but would love to pick it up, but looks like @ComputingVictor had a PR in place but closed it before it could merge?

**Comment by ComputingVictor** [comment]
> Anyone know the status of this? I haven't contributed to polars before but would love to pick it up, but looks like @ComputingVictor had a PR in place but closed it before it could merge?

Feel free to contribute. I closed due to incompatibilities with the new version of Polars!

**Comment by astrojuanlu** [comment]
Indeed, gh-19154 fixed this, the warning no longer appears in Polars 1.10 ✔️ 

(Gracias @ComputingVictor for giving it a try!)
