### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by acampove** [pola-rs/polars#19168]
### Description

Hi,

Thanks for writing this tool. I have been trying to understand how it works and my use case is wanting to define new columns from old ones, I see that I can do:

```python
import polars as pl

df = pl.DataFrame({
    "a": [1, 2, 3],
    "b": [4, 5, 6]
})

df = df.with_column((pl.col('a') + pl.col('b')).alias("c"))
```

However, wouldn't it be easier to do:

```python
df = df.Define('c', 'a + b')
```

Specially when the math is not `a+b` but some complex expression that I would rather write as a string. I think you would benefit greatly from:

1. Try to follow the design that pandas uses and improve it whenever posible.
2. Keep it simple.
3. Also try to check this: https://root.cern/doc/master/classROOT_1_1RDataFrame.html

that library offers a user friendly interface that you might want to also use as a starting point to improve on. Specially useful interfaces are `Filter`, `Define`, `Redefine` and `Range`.

**Comment by acampove** [comment]
Just a couple of minutes after I opened this issue, I found, thanks to chatGPT a workaround incase someone has this same problem:

```python
In [6]: import polars as pl
   ...:
   ...: # Sample DataFrame
   ...: df = pl.DataFrame({
   ...:     "a": [1, 2, 3],
   ...:     "b": [4, 5, 6]
   ...: })
   ...:
   ...: # Define a custom function to add a new column using a string expression
   ...: def define_column(df, new_column_name, expression):
   ...:     # Replace column names with pl.col references in the expression
   ...:     for col in df.columns:
   ...:         expression = expression.replace(col, f"pl.col('{col}')")
   ...:
   ...:     # Evaluate the expression and create the new column
   ...:     return df.with_columns(eval(expression).alias(new_column_name))
   ...:
   ...: # Use the function
   ...: df = define_column(df, 'c', 'a + b')
   ...:
   ...: # Display the result
   ...: print(df)
```

which I am going to add to a utilities library.

**Comment by acampove** [comment]
One final thing, in case anyone wants to implement a better interface, you can check this code:

https://github.com/acampove/dmu/blob/main/src/dmu/dataframe/dataframe.py

and you can write whatever interface you want. The upside of this is that I will only depend on MY interface and the underlying dataframe (pandas, polars, etc) can be swapped later if needed.

**Comment by coastalwhite** [comment]
Hi. We are not really planning on adjusting the API design in your proposed ways. Fundamentally, we would like to have a different kind of API. Feel welcome to make a wrapper of the Polars API that uses your API.
