### ISSUE TITLE
dataframes have a .count() but not .len() method

### ISSUE THREAD

**Issue by rmalouf** [pola-rs/polars#19167]
### Description

dataframes have a .count() method but not a .len() method. series have both, and groupbys have both but complain that .count() is deprecated. For consistency, it would be nice if dataframes also had .len() -- that way I could explain .len() to students and never have to mention .count(). Unless of course there's some deep reason dataframes don't have .len()

**Comment by stinodego** [comment]
Would you expect `len()` to return the number of rows or the number of columns?

DataFrame has `.height`, `.width`, and `.size` attributes. I'd argue these are more explicit and better to use than `len(df)` (which also works and gives you the number of rows).

**Comment by rmalouf** [comment]
I'd expect the number of rows, same as Series and GroupBy (and the len() function).

To be more concrete about why this came up: I'm a linguistics prof and I'm teaching polars for text processing to a class of non-programmers. It's helpful to be able to say that dataframes, series, and groupbys have parallel APIs (when it makes sense), so e.g.
```
df.median()
df.get_column(col).median()
df.group_by(col).median()
```
or
```
df.sum()
df.get_column(col).sum()
df.group_by(col).sum()
```
all work. 

Two values that come up a lot in linguistics are the number of words in a text and the number of unique words. We get unique words with:
```
df.n_unique()
df.get_column(col).n_unique()
df.group_by(col).n_unique()
```
and the number of words with:
```
len(df)
df.get_column(col).len()
df.group_by(col).len()
```
It's not a big deal, but it's an extra cognitive glitch for novices who already find a lot of this confusing. I can explain it to them in linguistic terms -- why is the plural of *ox* in English *oxen*? because it is, just memorize it -- but if there's no particular reason behind it, it would be easier not to.

**Comment by stinodego** [comment]
The difference is that `len` is not _really_ an aggregation like the other methods you're mentioning. The `len` of a DataFrame is known statically and it is the same for every column in a DataFrame (by definition).

`count` _is_ an aggregation (it counts non-null elements) and thus is not necessarily the same for every column:

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3], "b": [None, 5, 6]})
print(df.count())
```
```
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ u32 ┆ u32 │
╞═════╪═════╡
│ 3   ┆ 2   │
└─────┴─────┘
```

The same is true for `median`, `sum`, etc.: these all give you a result for every column.

Using `len` in the same way doesn't really make sense as we already know the length of each column is the same. And if we were to simply return a scalar for `df.len()`, a person using your API could be surprised. We supported `len(df)` for compatibility reasons - people used to pandas will expect it to work.

We already have `df.height` and I think adding `df.len()` may actually be confusing. So I'll close this as not planned for now.
