### ISSUE TITLE
Panic when applying `.group_by().agg()` on an empty dataframe.

### ISSUE THREAD

**Issue by georeth** [pola-rs/polars#19173]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({'x': [2.0, 1.0, 3.0], 'y': [1.0, 2.0, 6.0], 'g': ['a', 'a', 'b']})

x = pl.col('x')
y = pl.col('y')

# linear regression without intercept term
beta_expr = (y * x).sum() / (x * x).sum()
rsq_expr = 1. - ((y - beta_expr * x) ** 2).sum() / (y ** 2).sum()

# non-empty dataframe works
print(df.group_by('g').agg(beta_expr.alias('beta'), rsq_expr.alias('rsq')))

# panic on empty dataframe
print(df.limit(0).group_by('g').agg(beta_expr.alias('beta'), rsq_expr.alias('rsq')))

```

### Log output

```shell
keys/aggregates are not partitionable: running default HASH AGGREGATION
keys/aggregates are not partitionable: running default HASH AGGREGATION
thread 'polars-4' panicked at crates/polars-expr/src/expressions/group_iter.rs:51:37:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `f64`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/georeth/minimal_case.py", line 15, in <module>
    print(df.limit(0).group_by('g').agg(beta_expr.alias('beta'), rsq_expr.alias('rsq')))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georeth/.pyenv/versions/anaconda3-2023.09-0/lib/python3.11/site-packages/polars/dataframe/group_by.py", line 232, in agg
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georeth/.pyenv/versions/anaconda3-2023.09-0/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `f64`"))
```

### Issue description

polars crashed when I did a linear regression without intercept term on empty dataframes.

some findings:
- non-empty dataframe doesn't crash
- if beta_expr is replaced by a constant, it doesn't crash

### Expected behavior

polars should produce an empty dataframe.

### Installed versions

<details>
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          2.2.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.4.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.7.2
nest_asyncio         1.5.6
numpy                1.24.3
openpyxl             3.0.10
pandas               2.0.3
pyarrow              11.0.0
pydantic             1.10.8
pyiceberg            <not installed>
sqlalchemy           1.4.39
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

</details>

**Comment by georeth** [comment]
By the way, what's the recommended way to compute the values in polars? it seems the query plan is not optimal, `(x * x).sum()` and `(x * y).sum()` is not reused. should I split the computation into multiple stages?

**Comment by orlp** [comment]
`limit` is highly unstable and should be removed from the public interface.

However I can also reproduce with `.head(0)`, so that's besides the point.

**Comment by orlp** [comment]
More minimalized reproduction:

```python
df = pl.DataFrame({"x": [1.0], "g": [0]})
df.head(0).group_by('g').agg((x - x.sum() * x) ** 2)
```
