### ISSUE TITLE
Performance issues when using `pl.datetime_range` (compared to pandas)

### ISSUE THREAD

**Issue by marc-at-brightnight** [pola-rs/polars#19179]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime as dt
import polars as pl
import pandas as pd

start = dt.date(2017, 1, 1)
end = dt.datetime(2022, 12, 31, 23, 0)

%time pd.date_range(start, end, freq='H')
%time pl.datetime_range(start, end, interval=dt.timedelta(seconds=3600), eager=True)
```

### Log output

```shell
# pandas:
CPU times: user 181 µs, sys: 9 µs, total: 190 µs
Wall time: 193 µs

# polars:
CPU times: user 551 µs, sys: 301 µs, total: 852 µs
Wall time: 443 µs
```

### Issue description

Mostly curious if there's a reason as to why there's such a big difference in performance. Note of course the time is variable in both pandas and polars, but I noticed pandas tends to stay between 0.2-0.6ms, whereas polars can swing between 0.8 - >2ms.

### Expected behavior

Obviously, I want polars to be as fast (or even faster) than pandas (:

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            macOS-14.2-arm64-arm-64bit
Python:              3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.10.4
fsspec               2024.3.1
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.5
pandas               1.5.3
pyarrow              16.0.0
pydantic             2.6.3
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by orlp** [comment]
`datetime_range_i64` in `crates/polars-time/src/date_range.rs` is implemented rather inefficiently. It goes through a function pointer for every iteration and then dispatches to `add_impl_month_week_or_day` which is also very expensive.

**Comment by orlp** [comment]
If someone wants to tackle this, at the very least we should do a static dispatch on `TimeUnit`, and we should have a fast-path for `Duration`s which only have a `nsec` component.

**Comment by ritchie46** [comment]
@MarcoGorelli you like to take this one?

**Comment by MarcoGorelli** [comment]
Thanks for the ping - yup this should be very similar to the truncate / round perf improvements
