### ISSUE TITLE
Check Rust examples in `examples/` folder in CI

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#19186]
### Description

Currently aren't checked, so we get issues e.g. https://github.com/pola-rs/polars/issues/19129

**Comment by stinodego** [comment]
Honestly I think we should simply delete the `examples` folder. We have plenty of examples in the user guide now.

**Comment by rodrigogiraoserrao** [comment]
> Honestly I think we should simply delete the `examples` folder. We have plenty of examples in the user guide now.

I subscribe to this.
