### ISSUE TITLE
infer_schema for DataType::Null

### ISSUE THREAD

**Issue by Bidek56** [pola-rs/polars#19184]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```TS
import { DataFrame, DataType, pl } from "nodejs-polars"

console.log(
  pl.readRecords([
    { name: "John", color: "green", height: null },
    { name: "Anna", color: "green", height: null },
  ]),
)
```

### Log output

```shell
shape: (2, 2)
┌──────┬───────┐
│ name ┆ color │
│ ---  ┆ ---   │
│ str  ┆ str   │
╞══════╪═══════╡
│ John ┆ green │
│ Anna ┆ green │
└──────┴───────┘
```

### Issue description

I believe [this](https://github.com/pola-rs/polars/blob/194b31ea6a47a103f4401554755ed904a7f2838e/crates/polars-core/src/frame/row/mod.rs#L119) line is preventing proper schema inference, which then causes an issue in `nodejs-polars`.
```
    if dtype == DataType::Null {
        return;
    }
```

### Expected behavior

```
shape: (2, 3)
┌──────┬───────┬────────┐
│ name ┆ color ┆ height │
│ ---  ┆ ---   ┆ ---    │
│ str  ┆ str   ┆ null   │
╞══════╪═══════╪════════╡
│ John ┆ green ┆ null   │
│ Anna ┆ green ┆ null   │
└──────┴───────┴────────┘
```

### Installed versions

This issue has been raised in [this](https://github.com/pola-rs/nodejs-polars/issues/256) `nodejs-polars` ticket
<details>
rs-0.43.1
</details>

**Comment by ritchie46** [comment]
Can you create python examples on this Repo please? Then we can pick it up.

**Comment by Bidek56** [comment]
Python code works fine b/c it's using a different implementation and not `infer_schema`
```python
import polars as pl

df=pl.from_records([
    { "name": "John", "color": "green", "height": None },
    { "name": "Anna", "color": "green", "height": None },
  ])
```

[infer_schema](https://github.com/pola-rs/polars/blob/194b31ea6a47a103f4401554755ed904a7f2838e/crates/polars-core/src/frame/row/mod.rs#L102) is not used in `python-polars`, but we do use it in `nodejs-polars` hence the bug.

**Comment by ritchie46** [comment]
Then a rust repo? I don't maintain nodejspolars.

**Comment by Bidek56** [comment]
```Rust
use polars_core::frame::row::infer_schema;
fn main() {
    // Sample data as a vector of tuples (column name, value)
    let data: Vec<Vec<(PlSmallStr, DataType)>> = vec![
        vec![(PlSmallStr::from("name"), DataType::String)],
        vec![(PlSmallStr::from("age"), DataType::Int32)],
        vec![(PlSmallStr::from("salary"), DataType::Null)]
    ];

    // Create an iterator over the sample data
    let iter = data.into_iter();

    // Infer the schema
    let schema = infer_schema(iter, 3);

    // Print the inferred schema
    println!("{:?}", schema);
}
```

which results in incorrect schema:
```
Schema:
name: name, field: String
name: age, field: Int32
```
