### ISSUE TITLE
Joining spelled wrong

### ISSUE THREAD

**Issue by BobFrederiksen** [pola-rs/polars#19198]
### Description

<img width="254" alt="image" src="https://github.com/user-attachments/assets/b45fbbe8-5e21-4c74-ac34-d964b023e71d">

### Link

https://docs.pola.rs/user-guide/getting-started/#select

**Comment by 5AIPAVAN** [comment]
@BobFrederiksen @coastalwhite  can you please assign me this issue, i am a beginner to open source, this would help me :-).

**Comment by alexander-beedie** [comment]
> @BobFrederiksen @coastalwhite can you please assign me this issue, i am a beginner to open source, this would help me :-).

Looks like somebody already jumped on it, sorry 😅 
https://github.com/pola-rs/polars/pull/19200
