### ISSUE TITLE
Expose regex::escape in Polars Python API

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#19207]
Polars uses the Rust `regex` crate as its regex engine. When building patterns it is sometimes desired to put an untrusted/unknown string as a literal in the regex. To do this correctly you need to escape that string. However, `re.escape` in Python is not the correct function for this, it should match the engine we use, so we need to expose `regex::escape` in our interface.

I would suggest exposing it as `pl.escape_regex` which directly works on Python strings, and `pl.Expr.str.escape_regex` which applies it to a column of strings.

**Comment by orlp** [comment]
Oops, I forgot to search for duplicates 😓

**Comment by alexander-beedie** [comment]
Good plan; can then retire this utility function:
https://github.com/pola-rs/polars/blob/48f6e9dc7c62f60ee9cb2ef9313917b63c96b1f7/py-polars/polars/_utils/various.py#L626

**Comment by ritchie46** [comment]
@barak1412 would you be interested in this one? You are getting familiar with the Expressions setup.

**Comment by ritchie46** [comment]
Ai, take care. :raised_hands:

**Comment by barak1412** [comment]
@ritchie46 Thanks!

@orlp May you assign me please?
