### ISSUE TITLE
To the lead devs - If you really want adoption of polars to the level of pandas please persuade leetcode.com and stratascratch.com to incorporate polars. Hear me out

### ISSUE THREAD

**Issue by wolfdael** [pola-rs/polars#19206]
### Description

So many devs want to use polars, but it's not possible because it is not incorporated in websites like leetcode and stratascratch for practice. This is the main reason polars is not used in interviews. Even if the candidate is ready to use polars, the hiring manager is not comfortable. This is because there is no place to practice polars like leetcode or stratascartch (I am sure there maybe some obscure ones but not industry standard like these two).

Many have already expressed their interest in incorporating polars in strata scratch and the founder is happy to do it, but it may happen faster if the lead devs from polars talk to them as well. 
So many young devs are starting out, and they want to use polars, but this is exactly the reason why polars is not picking up. 

Please persuade these two companies or atleast one to include them, even if one incorporates polars then the tides are changing in the world of DS.

**Comment by orlp** [comment]
Closing this as it is not an issue with Polars.

Other general/community feedback can be sent on the [Polars Discord server](https://discord.gg/4UfP5cfBE7).
