### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#1921]
Python 3.10 has been released on Oct 4 (see https://www.python.org/downloads/release/python-3100/). I'm not an expert on the Python-Rust bindings being used, but it seems PyO3 / maturin support Python 3.10, so this seems feasible? Would be great to add 3.10 support, as most libraries support it by now.

**Comment by ritchie46** [comment]
The python ABI is stable since python 3.6. So it should work on python 3.10

**Comment by zundertj** [comment]
Ok, I was hitting an error on my local Python 3.10 venv, turns out the recent upgrade I did for pytest solved it (i.e. see https://github.com/pytest-dev/pytest/issues/8539#issuecomment-832083778)
