### ISSUE TITLE
Failed to compile polars in wasm

### ISSUE THREAD

**Issue by orest-d** [pola-rs/polars#19211]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I used a minimal trunk-based example where I have added polars as a dependency.
The crash appears during the compilation of dependencies, so rust code is not relevant,
nevertheless I simply followed https://trunkrs.dev/guide/getting-started/project.html

I am using windows (though I tried WSL too with the same result) and I have tried both nightly (1.83 ) and current stable rust.
I have tried multiple variants of dependencies,  the following is based on js-polars cargo,
commenting out features that refused to compile.

I as well fixed indexmap in order to fix issue #19063 :

cargo update indexmap@2.6.0 --precise 2.5.0

```cargo
[package]
name = "trunk-test"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"

web-sys = { version = "0.3.72", features = ["Window", "Document", "HtmlElement", "Text"] }

[dependencies.polars]
default-features = false
version = "0.43.1"
features = [
  "abs", # "diagonal_concat",
  "diff", # "dot_diagram",    # "dtype-categorical",
  "dtype-full",
  "round_series",
  #"is_first",
  "lazy", # "extract_jsonpath",  # "horizontal_concat",
  "mode", # "object",  # "performant",  # "json",
  #"csv-file", # "private",  # "fmt",
  "csv",
  "product",
  "rank",
  "reinterpret", # "rolling_window",
  "rows", # "temporal",
  "strings",
  #"string_justify",
  "string_encoding",
  "semi_anti_join",
  "unique_counts",
]
```

Then building with
trunk build

### Log output

```shell
PS C:\Work\trunk-test> trunk build
2024-10-12T18:05:04.787551Z  INFO Starting trunk 0.20.3
2024-10-12T18:05:04.788252Z  INFO starting build
   Compiling psm v0.1.23
   Compiling hashbrown v0.14.5
   Compiling rand_chacha v0.3.1
The following warnings were emitted during compilation:

warning: psm@0.1.23: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `clang` installed? (see https://docs.rs/cc/latest/cc/#compile-time-requirements for help)
warning: psm@0.1.23: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `clang` installed? (see https://docs.rs/cc/latest/cc/#compile-time-requirements for help)

error: failed to run custom build command for `psm v0.1.23`

Caused by:
  process didn't exit successfully: `C:\Work\trunk-test\target\debug\build\psm-f25ca4593b5cfb2e\build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some(0)
  TARGET = Some(wasm32-unknown-unknown)
  OUT_DIR = Some(C:\Work\trunk-test\target\wasm32-unknown-unknown\debug\build\psm-d0c6ead258b8fcd6\out)
  HOST = Some(x86_64-pc-windows-msvc)
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `clang` installed? (see https://docs.rs/cc/latest/cc/#compile-time-requirements for help)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  cargo:rerun-if-env-changed=WASI_SYSROOT
  WASI_SYSROOT = None
  DEBUG = Some(true)
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
```

### Issue description

Polars fails to compile the wasm32 target.
During the compilation, the psm dependency is used though according to https://crates.io/crates/psm, psm is not relevant and not supported in wasm.

### Expected behavior

- Polars should compile to wasm32 (with some defined set of features)
- It would be very nice to include some explanation in the documentation how to use polars in wasm.

### Installed versions

<details>

  "abs", # "diagonal_concat",
  "diff", # "dot_diagram",    # "dtype-categorical",
  "dtype-full",
  "round_series",
  #"is_first",
  "lazy", # "extract_jsonpath",  # "horizontal_concat",
  "mode", # "object",  # "performant",  # "json",
  #"csv-file", # "private",  # "fmt",
  "csv",
  "product",
  "rank",
  "reinterpret", # "rolling_window",
  "rows", # "temporal",
  "strings",
  #"string_justify",
  "string_encoding",
  "semi_anti_join",
  "unique_counts",

</details>

**Comment by orest-d** [comment]
It is worth mentioning that some time ago I was able to compile it without problems and use polars from leptos.
I used the following: https://github.com/orest-d/liquer-prototyping/blob/master/liquers-dj/Cargo.toml
This old project does not compile  any longer either.

**Comment by Bidek56** [comment]
Is `clang` installed?

**Comment by orest-d** [comment]
I used rustup to install rust on windows, I never installed clang. I think normally use of of clang is a bad sign when compiling to wasm. If I understand it correctly a) psm maybe needs clang, but b) psm is not supported in wasm and should not be used with wasm. So even if I would install clang, something is wrong....

**Comment by orlp** [comment]
@orest-d Nothing is wrong. `psm` doesn't really do anything but it still provides the API on WASM I believe. `psm` is a dependency of `stacker` which we require. Take it upstream if you think the dependency could be made optional on WASM.
