### ISSUE TITLE
read_database with sqlalchemy Selectable object does not work when duckdb is the backend database

### ISSUE THREAD

**Issue by daniel-thom** [pola-rs/polars#19221]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

The code block below fails when duckdb is the backend database.

```python
import polars as pl
from sqlalchemy import MetaData, Table, create_engine, select

df1 = pl.DataFrame({"value": range(10)})
engine = create_engine("duckdb:///:memory:")
metadata = MetaData()
table_name = "tbl"
with engine.connect() as conn:
    df1.write_database(table_name, connection=conn)
    conn.commit()
metadata.reflect(engine)
table = Table(table_name, metadata)
with engine.connect() as conn:
    stmt = select(table).where(table.c.value > 5)
    df2 = pl.read_database(str(stmt), connection=conn)
```

```python-traceback
Traceback (most recent call last):
  File "./repro.py", line 16, in <module>
    df2 = pl.read_database(stmt, connection=conn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/polars/io/database/functions.py", line 255, in read_database
    return cx.execute(
           ^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/polars/io/database/_executor.py", line 501, in execute
    result = cursor_execute(query, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Please provide either a DuckDBPyStatement or a string representing the query
```

### Log output

```shell
There was no additional output.
```

### Issue description

The example code block works with SQLite.

I can workaround the issue by converting `stmt` to a string as long as there are no query parameters.

### Expected behavior

There query result is converted to a DataFrame and printed to the console.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
'Platform:            macOS-13.7-arm64-arm-64bit
Python:              3.11.7 (main, Dec 11 2023, 15:02:03) [Clang 15.0.0 (clang-1500.0.40.1)]

----Optional dependencies----
adbc_driver_manager  1.2.0
altair               <not installed>
cloudpickle          <not installed>
connectorx           0.3.3
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             2.9.1
pyiceberg            <not installed>
sqlalchemy           2.0.34
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Hmm... while I can see why this fails (and how to make it work), note that using `Selectable` with DuckDB will come with a performance downside - you won't be taking advantage of the Arrow support that the raw connection has, as the `Selectable` will necessarily force the use of the SQLAlchemy connection (we can use the _raw_ DuckDB connection if given a SQL string - which is actually what causes the issue here). If you're returning meaningful data, or are otherwise performance-sensitive, this could (potentially) be a big hit 🤔

 I'll fix the error (probably tomorrow), but know that you'll be giving up some performance by using a `Selectable` (until/unless `duckdb_engine` adds native Arrow return methods from the cursor, such as "fetch_arrow_table" and "fetch_record_batches"). You could try making a feature request with the `duckdb_engine` project for this.
 
Note that we will _not_ automatically convert the `Selectable` to a string query inside Polars, as that is a potential vector for untrusted input. If you want to assume responsibility for the conversion in your own code though, you can do it like this:
```python
sql = str(stmt.compile(compile_kwargs={"literal_binds": True}))
```

**Comment by daniel-thom** [comment]
The whole reason that I am going down this path is that Polars provides the performance I want (in the ballpark of native duckdb). I will be making a lot of database calls that need to be converted to dataframes with low latency. I haven't found any other solution. Thanks for that, BTW.

I submitted a feature request with duckdb_engine. I might be able to get away with your string-conversion suggestion temporarily. Thanks.

**Comment by alexander-beedie** [comment]
**Update**: good news - further inspection of `duckdb_engine` shows that it has a transparent pass-through to the underlying raw connection (via `__getitem__`), which we should be able to take advantage of Arrow return in all cases. Looking at a patch on our side now.

**Comment by daniel-thom** [comment]
@alexander-beedie This is great news. However, this change seems to have broken the option where the user passes a string. It works if I pass a sqlalchemy Selectable or TextClause. A caveat is that I tested by copying the file you changed (_executor.py) into Polars 1.9.0 without taking any other changes.

Here are the steps:
```python
import polars as pl
from sqlalchemy import MetaData, Table, create_engine, select, text

df1 = pl.DataFrame({"value": range(10)})
engine = create_engine("duckdb:///:memory:")
metadata = MetaData()
table_name = "tbl"
with engine.connect() as conn:
    df1.write_database(table_name, connection=conn)
    conn.commit()
metadata.reflect(engine)
table = Table(table_name, metadata)
with engine.connect() as conn:
    stmt = select(table).where(table.c.value > 5)
    print("1. Read from Selectable")
    print(pl.read_database(stmt, connection=conn))

    print("2. Read from TextClause")
    print(pl.read_database(text(f"SELECT * FROM {table_name}"), connection=conn))

    print("3. Read from string")
    print(pl.read_database(f"SELECT * FROM {table_name}", connection=conn))
```
```
Traceback (most recent call last):
  File "./env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    meth = statement._execute_on_connection
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./scripts/repro.py", line 22, in <module>
    print(pl.read_database(f"SELECT * FROM {table_name}", connection=conn))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/polars/io/database/functions.py", line 255, in read_database
    return cx.execute(
           ^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/polars/io/database/_executor.py", line 501, in execute
    result = cursor_execute(query, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SELECT * FROM tbl'
```

**Comment by alexander-beedie** [comment]
Thanks, I'll double-check shortly 🤔
