### ISSUE TITLE
Lazyframe query not optimized for joins

### ISSUE THREAD

**Issue by skyth540** [pola-rs/polars#19228]
### Checks

- [x] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Slow:
```python
hist_fct = pl.scan_parquet('G:\PATH', low_memory = True)
hist_prd_ref = pl.scan_csv('G:\PATH', separator = '|')

hist_prd_ref \
    .unique(subset = 'Period Key') \
    .join(hist_fct, on = 'Period Key', how = 'inner').head(10000).collect()
```

Fast:
```python
hist_fct = pl.scan_parquet('G:\PATH', low_memory = True).head(10000).collect()
hist_prd_ref = pl.scan_csv('G:\PATH', separator = '|').head(10000).collect()

hist_prd_ref \
    .unique(subset = 'Period Key') \
    .join(hist_fct, on = 'Period Key', how = 'inner')
```

### Issue description

Pre-collecting a dataframe , and then joining, is significantly faster than joining a lazyframe using head

### Expected behavior

The ref file is only a few hundred rows long. 

This query should be optimized to only read the top 10,000 lines of the hist_fct, and then perform the join.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
```

</details>

**Comment by orlp** [comment]
Those two queries do not have the same result in general.
