### ISSUE TITLE
Change TypeHint on `pl.from_dicts` to `Iterator[dict[str, Any]]` from `Sequence[dict[str, Any]]`

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#19234]
### Description

The type-hint on `pl.from_dicts` is `Sequence[dict[str, Any]]` - from my understanding, a `Sequence[dict[str, Any]]` is an `Iterator[dict[str, Any]]`  that also supports `len()` and random access (https://stackoverflow.com/a/76868479/2981639). As far as I can tell polars actually requires an Iterator rather than a Sequence - i.e. 

```
from typing import Any, Iterator

def generator() -> Iterator[dict[str, Any]]:
    test = [{"a": 1}, {"a": 2}]
    yield from test

pl.from_dicts(generator())
```

appears to work fine, but my linter complains that `pl.from_dicts(generator())` is a type violation. It would be nice if the type was narrower to prevent linter false positives (if I'm correct in the that the original typing is too wide)

**Comment by alexander-beedie** [comment]
Yup, we should update this (though would be better typed as `Iterable` rather than specifically `Iterator` 🤔)

**Comment by alexander-beedie** [comment]
>  It would be nice if the type was narrower to prevent linter false positives (if I'm correct in the that the original typing is too wide)

Actually it's the other way round - the typing was too narrow heh.
Fixed now; thanks for the heads-up ;)

**Comment by david-waterworth** [comment]
Ahh yes true - thanks for fixing!
