### ISSUE TITLE
Adding `is_datetime()`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#19235]
### Description

https://github.com/pola-rs/polars/issues/12196 discussed the introduction of `DataType.is_*` functions, e.g. `is_boolean()`. However, not all types have their `is_` function, for instance there isn't `is_datetime()`. Is this something that should be added?

I thought it would be simply adding 
```rs
pub fn is_datetime(&self) -> bool {
    matches!(self, DataType::Datetime(_, _))
}
```
but some discussion in #12196 about having `is_datetime(time_unit, time_zone)`. Should those parameters be implemented as well? I could give it a try if it's a good first issue.

**Comment by orlp** [comment]
In the linked issue it was decided that we would only add these functions for groups of types: <https://github.com/pola-rs/polars/issues/12196#issuecomment-1810846295>.

So no specific type has an `is_` function, only groups like 'integers' or 'temporal types' have such a function.
