### ISSUE TITLE
`sink_ipc` never finishes and eats up memory if read csv has more than 7,293,511 rows

### ISSUE THREAD

**Issue by micouy** [pola-rs/polars#19289]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Minimal example

```python
from uuid import uuid4
import polars as pl


path = f"{uuid4()}.feather"

pl.scan_csv(
    "age-sex.csv",
    has_header=True,
    schema_overrides={"Area": pl.String},  # Needed to avoid wrong inference.
    n_rows=7_293_512,  # 7_293_511 works.
).sink_ipc(path)

print(pl.scan_ipc(path).count().collect())
```

Zipped CSV file (100 MB / 857 MB): https://drive.google.com/file/d/1T0MfimiWZmDp0bhrWUFq32iDkXBP7VeH/view?usp=sharing

Alternatively download from here: https://www.stats.govt.nz/large-datasets/csv-files-for-download/ (Age and sex by ethnic group (grouped total responses), for census usually resident population counts, 2006, 2013, and 2018 Censuses (RC, TA, SA2, DHB), the main CSV file in the ZIP)

I ran it on a macBook Air M1 with 8 GB of RAM.

Might be related to #15771.

### Log output

```shell
RUN STREAMING PIPELINE
[csv -> parquet_sink]
STREAMING CHUNK SIZE: 8333 rows
```

### Issue description

The program above never finishes and takes up much more memory (~600 MB) than with a lower number of rows. With `7_293_511` or less it takes ~0.01 MB and ~1s.

### Expected behavior

Save a feather file while taking ~0.01 MB RAM and ~1s.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            macOS-14.5-arm64-arm-64bit
Python:              3.11.9 (main, Aug  2 2024, 11:33:02) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce on 1.9.0

On main it finishes in ~1s as you suggest.

```
shape: (1, 6)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Year    ┆ Age     ┆ Ethnic  ┆ Sex     ┆ Area    ┆ count   │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ u32     ┆ u32     ┆ u32     ┆ u32     ┆ u32     ┆ u32     │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│ 7293512 ┆ 7293512 ┆ 7293512 ┆ 7293512 ┆ 7293512 ┆ 7293512 │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

Not sure what PR(s) may have resolved this.

**Comment by cmdlineluser** [comment]
It starts to work for me after this fix:

- https://github.com/pola-rs/polars/pull/19118

**Comment by ritchie46** [comment]
Fixed on main. I will close. A new release will be issued this weekend.
