### ISSUE TITLE
top_k is slow and uses a lot of memory

### ISSUE THREAD

**Issue by foldager** [pola-rs/polars#19281]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

The issue is best shown with quite large data, so I've made a dummy 500 million record dataset 
```python
import numpy as np
import polars as pl

np.random.seed(43)

TOTAL_ROWS = 500_000_000
INITIAL_ROWS = int(TOTAL_ROWS ** 0.5)

# Create the cross product of two smaller datasets
lf_a = pl.LazyFrame({'a': np.random.randint(0, 1_000_000, size=INITIAL_ROWS)})
lf_b = pl.LazyFrame({'b': np.random.randint(0, 1_000_000, size=INITIAL_ROWS)})
cross_product = lf_a.join(lf_b, how="cross")

# Sink into a parquet file
cross_product.sink_parquet("data.parquet", compression="snappy")
```

Select the top 5 `a` values

```python
import polars as pl
res = pl.scan_parquet("data.parquet").select("a").top_k(5, by='a').collect()
print(res)
```

Find mean of `a`

```python
import polars as pl
res = pl.scan_parquet("data.parquet").select("a").mean().collect()
print(res)
```

Sort `a`

```python
import polars as pl
res = pl.scan_parquet("data.parquet").select("a").sort(by="a").collect()
print(res)
```

Read `a`

```python
import polars as pl
df = pl.scan_parquet("data.parquet").select("a").collect()
print(df)
```

### Log output

> [!NOTE]
> I have not set `POLARS_VERBOSE=1` in these outputs as it does not write anything to stderr in this case and potentially interferes with performance.

The logs are edited for clarity (removed extra lines and converted memory to GB).

```shell
/usr/bin/time -lh python top_5.py
shape: (5, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
└────────┘
	20.87s real		5.22s user		11.11s sys
        28.7 GB  peak memory footprint
```

```shell
/usr/bin/time -lh python mean.py
shape: (1, 1)
┌───────────────┐
│ a             │
│ ---           │
│ f64           │
╞═══════════════╡
│ 502017.772764 │
└───────────────┘
	0.56s real		0.40s user		1.15s sys
        4.2 GB peak memory footprint
```

```shell
/usr/bin/time -lh python sort.py
shape: (499_969_600, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 19     │
│ 19     │
│ 19     │
│ 19     │
│ 19     │
│ …      │
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
└────────┘
	3.38s real		8.32s user		1.94s sys
        12.2 GB peak memory footprint
```

```shell
/usr/bin/time -lh python read_a.py
shape: (499_969_600, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 276292 │
│ 276292 │
│ 276292 │
│ 276292 │
│ 276292 │
│ …      │
│ 624089 │
│ 624089 │
│ 624089 │
│ 624089 │
│ 624089 │
└────────┘
	0.39s real		0.29s user		1.06s sys
        4.2 GB  peak memory footprint
```

Equivalent to top_5 in duckdb

```shell
/usr/bin/time -lh duckdb -c "select a from 'data.parquet' order by a desc limit 5;"
┌────────┐
│   a    │
│ int64  │
├────────┤
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
│ 999938 │
└────────┘
	0.58s real		2.04s user		1.54s sys
        0.026 GB peak memory footprint
```

### Issue description

Top k uses a lot more memory and takes much longer than expected. The large memory use means I get OOM errors and my actual queries fail to execute with polars.

### Expected behavior

According to the the [top_k docs](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.top_k.html) the time complexity is $O(n)$, so I would expect it to perform like `.mean`. To be honest, I don't see how top_k is able to perform in $O(n)$. In algorithms where you keep the top k contenders in a heap, I believe you have $O(n \cdot log(k))$ time. But as shown above, the runtime is much worse than sorting the whole `a` column, so I'm not sure what is going on.

For memory use, I was really hoping that top_k would scale with the size of k. I have a large dataset where it is not feasible to load the whole thing into memory. It would be a great addition if polars could make optimizations like that. I have tried to enable the `collect(streaming=True)` flag, but that does not seem to affect the memory use of this query.

I included the max and count stats here, as that is probably related to improving the top_k performance. I would not expect a simple max and count to load the whole dataset into memory. For those two statistics, all the information is actually available in the rowgroup metadata so there are opportunities for optimizing them much further.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            macOS-14.7-arm64-arm-64bit
Python:              3.12.3 (main, Aug  1 2024, 12:12:15) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
> To be honest, I don't see how top_k is able to perform in O(n)

Easy, here's what immediately comes to mind:

1. Read the first five values.
2. Iterate through remaining items. If the item is larger than the minimum of the 5, swap them.

There are probably tricks to speed this up. For example, if you sort your initial 5 items, then you can perform five "mindless" swaps before you need to re-sort your top 5 again, since after swapping the first, you know your new top-5-minimum is either the newly-swapped item or the first or second value. I bet someone has come up with a faster algo, but this one is O(n).

**Comment by foldager** [comment]
> 2. Iterate through remaining items. If the item is larger than the minimum of the 5, swap them.

I think you have to account for
- keeping track of what the minimum is (no impact on O)
- Finding/keeping track of which value is the minimum so that you can swap it. That should take $log(k)$ with an efficient algorithm.

For k=5 that is not a lot of book keeping... but you get the point. Also, I guess you would need to swap less frequently as you go through and already have high values in your top list. Not sure how to account for that in O. Worst case is you have to swap for every record.

**Comment by wence-** [comment]
quickselect is average case $O(n)$: given some fixed $k$, [`select_nth_unstable`](https://doc.rust-lang.org/beta/std/primitive.slice.html#method.select_nth_unstable) (which is what polars uses) I think uses an introspective version of quickselect (to defeat bad cases that would result in $O(n^2)$ behaviour).

Idea, you partition your data into `[0..k, k, k+1..N]` such that all entries in `A[i < k] < A[k]`. You can that do that with quicksort by recursing only onto one side of your pivot. This is $O(n)$. Once you've done that, you then in general must sort the `A[:k]` entries, which is $O(k \log k)$, but $k$ is constant. So in the complexity analysis, the whole algorithm is still $O(n)$: you don't do more work for a fixed $k$ as you increase $n$.

**Comment by mcrumiller** [comment]
You're right, it's O(N log k). I see now you included that in your initial post. If k is considered a constant then you can say the algorithm is O(n).

It looks like polars uses Rust's [`select_nth_unstable_by`](https://doc.rust-lang.org/beta/std/primitive.slice.html#method.select_nth_unstable) and @orlp helped identify/speed up their implementation [here](https://github.com/rust-lang/rust/issues/91644), so he probably has a lot more knowledge of what's going on here.

**Comment by barak1412** [comment]
Regarding running-time, you don't need all this code.
Look at:

```python
import numpy as np
import polars as pl
import datetime

np.random.seed(43)

TOTAL_ROWS = 500_000_000

df = pl.DataFrame({'a': np.random.randint(0, 1_000_000, size=TOTAL_ROWS)})

t1 = datetime.datetime.now()
res = df.select("a").top_k(5, by='a')
t2 = datetime.datetime.now()
print((t2 - t1).total_seconds())

t1 = datetime.datetime.now()
res = df.select("a").sort(by="a")
t2 = datetime.datetime.now()
print((t2 - t1).total_seconds())

```

Sorting is quicker, and I wonder why.

**Comment by foldager** [comment]
As @wence- mentioned, you get $O(n)$ for fixed $k$ with quickselect. However, looking through the code, It looks like a sort followed by a slice for both `DataFrame` and `LazyFrame` I'm not savvy enough to gauge if that is somehow optimized away.

https://github.com/pola-rs/polars/blob/8a76daddccfe06d789312ec6e077dd230a6722c3/crates/polars-lazy/src/frame/mod.rs#L347-L359

My other point was about space complexity. Maybe it is $O(n \cdot log(n))$ at the moment. I'm not sure why we get a lot of re-allocation during the sort, but I think we do. If the full sort is avoided, it should become $O(n)$. What I would really like to see is $O(1)$ space complexity, i.e, that the dataset size does not matter. (Considering $k$ a variable rather than a constant, the space complexity is $O(k)$ ).

However, any work to achieve that, will require the https://github.com/pola-rs/polars/labels/new-streaming engine so it is possible to iterate over larger than memory lazyframes https://github.com/pola-rs/polars/issues/10683 .

In that future, I think quickselect is not the right algorithm, because it can backtrack basically across the whole dataset, requiring the dataset to be in memory (or loaded again). I think an algorithm that keeps candidate rows around as it iterates through the dataset will perform much better – at least for $k << n$.

### Work around
For my actual use case, I have more columns and they are all loaded into memory in the current implementation, which is what tips the memory use over the edge for my system. I found that you can leverage that `quantile` has a more efficient implementation, which can be used to find the minimum value of interest and use that in a filter. Because of predicate pushdown optimization, only rowgroups of interest are then loaded into memory.

Given these columns

```python
a = pl.col("a")
b = pl.col("b")
a_plus_b = (a + b).alias('a_plus_b')
a_squared = (a**2).alias('a_squared')
```

Straight top_k

```python
res = (pl
    .scan_parquet("data.parquet")
    .select(a, b, a_plus_b, a_squared)
    .top_k(5, by='a')
    .collect()
)
```
takes 34.2 seconds, 52.7 GB memory.


Finding the quantile

```python
# Percentile for the 5th largest value given a 500 million dataset
percentile_fraction = 1 - 1e-8

res = (pl
    .scan_parquet("data.parquet")
    .select("a")
    .quantile(percentile_fraction)
    .collect()
)
```
takes 2.7 seconds, 8.2 GB memory.


Combining finding quantile and filtering before top_k

```python
percentile_fraction = 1 - 1e-8
lf = pl.scan_parquet("data.parquet")

percentile = lf.select(a).quantile(percentile_fraction).collect()
res = (lf
    .select(a, b, a_plus_b, a_squared)
    .filter( a >= percentile)
    .top_k(5, by='a')
    .collect()
)
```
takes 2.8 seconds, 8.2 GB memory.

**Comment by barak1412** [comment]
@foldager You can see in the comment in the code you pasted it is written "this will optimize to top-k".

So this will be changed in the future.

Try measure the memory consumption using this code instead:
```python
res = df.select(pl.col("a").top_k(k=5))
```

**Comment by foldager** [comment]
Thanks @barak1412. Expression `top_k` has a fast running time in both dataframe and lazy frame context. It improves my work-around as I can replace `quantile()` with the expression `top_k`.

```python
res = pl.scan_parquet("data.parquet").select(pl.col("a").top_k(k=5)).collect()
```

takes 1.6 seconds, 8.2 GB memory.

```python
a = pl.col("a")
b = pl.col("b")
a_plus_b = (a + b).alias('a_plus_b')
a_squared = (a**2).alias('a_squared')

# Base lazy frame
lf = pl.scan_parquet("data.parquet")

min_a = lf.select(a.top_k(k=5).min()).collect().item()
res = (lf
    .filter(a >= min_a)
    .select(a, b, a_plus_b, a_squared)
    .top_k(5, by=a)
    .collect()
)
```
takes 1.6 seconds, 8.2 GB memory. The same as above because the second step is fast.

A python program with the second step alone
```
lf = pl.scan_parquet("data.parquet")

res = (lf
    .filter(a >= 999938)
    .select(a, b, a_plus_b, a_squared)
    .top_k(5, by=a)
    .collect()
)
```
takes 0.12 seconds 71.9 MB memory.

**Comment by ritchie46** [comment]
Looking into it.
