### ISSUE TITLE
Converting None columns from Pandas

### ISSUE THREAD

**Issue by berkorbay** [pola-rs/polars#19329]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

dfpd = pd.DataFrame(data={"A":[None,None,None]})
dfpl = pl.DataFrame(dfpd)
print(dfpl)
dfpl2 = pl.DataFrame({"A":[None,None,None]})
print(dfpl2)
```

### Log output

```shell
shape: (3, 1)
┌──────┐
│ A    │
│ ---  │
│ str  │
╞══════╡
│ null │
│ null │
│ null │
└──────┘

shape: (3, 1)
┌──────┐
│ A    │
│ ---  │
│ null │
╞══════╡
│ null │
│ null │
│ null │
└──────┘
```

### Issue description

This is a very minor issue, but proved to be a bit of a nuisance for some tasks for me. So I thought, I may report it as well. 

Consider a Pandas dataframe with a column full of None values. If I convert it to a Polars Dataframe, it will make the column a string column with actual "None" strings in it. Though, if I feed a list with all None values, Polars will consider it a None column but not a string column.

I can just avoid the situation by converting pandas dataframe to a dictionary of lists and convert to polars dataframe. My data sets are small (but many) so this is not a pressing issue for me, either.

```python
pl.DataFrame(dfpd.to_dict(orient="list"))
```

### Expected behavior

Expected behavior is getting a null type column instead of string.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            macOS-13.0.1-arm64-arm-64bit
Python:              3.11.6 (main, Nov 23 2023, 13:24:35) [Clang 14.0.0 (clang-1400.0.29.202)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> If I convert it to a Polars Dataframe, it will make the column a string column with actual "None" strings in it.

I don't see this; from your example it creates the following frame:
```python
shape: (3, 1)
┌──────┐
│ A    │
│ ---  │
│ str  │
╞══════╡
│ null │
│ null │
│ null │
└──────┘
```
These aren't None strings, they are `null` values (eg: `None`, not `"None"`).
Can you clarfiy the example, or where exactly you see something not behaving as expected?

**Comment by berkorbay** [comment]
@alexander-beedie You are right. I think I have lost some of the reproducibility when I created the minimal working example. I will try to find the original data where I encountered this problem. The column type difference stays (str vs null), though I doubt if it will have any effect on the calculations.
