### ISSUE TITLE
Regression in 1.10.0 : Selection of rows hangs indefinitely for a frame contaning a `pl.Object` series

### ISSUE THREAD

**Issue by Elvynzs** [pola-rs/polars#19358]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.Series(["text"] * 100 + [1] * 100, dtype=pl.Object)[[0, -1]] # OK !
pl.Series(["text"] * 100 + [1] * 100, dtype=pl.Object).to_frame()[[0, -1]] # Hangs indefinitely
```

### Log output

```shell
N/A
```

### Issue description

See example. Used to work in 1.8.1.

This test comes from our unittests, where we try to be robust for different kind of inputs that may not always be well structured.

### Expected behavior

Here is what I used to get in 1.8.1 :

```
object
------
text
1
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            Windows-10-10.0.22000-SP0
Python:              3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.3.0
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.2
pandas               2.2.2
pyarrow              15.0.2
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.4.0
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by ritchie46** [comment]
Also works in 1.9.0. I think we need a bisect on this one.

**Comment by cmdlineluser** [comment]
@ritchie46 Seems to be the upgrade in PyO3 https://github.com/pola-rs/polars/pull/19199

**Comment by ritchie46** [comment]
@itamarst can you take look what happened here? Thanks for the bisect @cmdlineluser

**Comment by itamarst** [comment]
Will try to take a look, yes.

**Comment by itamarst** [comment]
The issue as explained by Ritchie is that older PyO3 would defer decrefs on Python objects (in this case `polars_python::conversion::ObjectValue`) to a pool, and then drop them later.

In latest version, there is no pool, so current code will acquire GIL... which then deadlocks with code holding GIL that is calling into Rayon. 

Ritchie's thought was to restore usage of the pool to Polars.

My proposal: anything calling Rayon should release the GIL. And in fact adding `Python::allow_threads()` to the key method in this case (`gather_with_series()` in dataframe/general.rs in polars-python) fixes the deadlock.

**Comment by itamarst** [comment]
To expand: Almost all methods of `PyDataFrame` and `PySeries` etc should plausibly be releasing the GIL, and currently aren't. E.g. all the methods that are just passthroughs that call `self.df.dosomething()`. Presumably Polars already has concurrency controls on that level so the GIL part is unnecessary.

**Comment by ritchie46** [comment]
Fixed and released.
