### ISSUE TITLE
n_unique result is not expected result when type is categorical

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1936]
Hi;

I'm working on a big dataFrame.  Although I filter the dataframe, it returns all unique values of dataframe. I think in last part it is calculating correct values. I believe this is a bug. But I need your comments to clarify this.

![image](https://user-images.githubusercontent.com/19631334/144113687-fa058000-8975-4818-8949-d4972718d1c2.png)

I'm also adding schema below.

![image](https://user-images.githubusercontent.com/19631334/144114527-f1c80464-e52c-463b-a308-605fa9602e67.png)

**Comment by ritchie46** [comment]
Right.. we have a fast path for categoricals, but that is definitely wrong in this case.

Will fix it.

Note that the groupby syntax you show in your snippet is outdated and will likely be deprecated soon.

**Comment by hakantekbas** [comment]
is this a quick fix like previous ones?

**Comment by ritchie46** [comment]
Jup..

**Comment by hakantekbas** [comment]
thanks.
