### ISSUE TITLE
Struct unnest panic

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#19378]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"foo": ["hello\nworld"]})
df.select( pl.col("foo").str.split("\n").list.to_struct(fields=['a','b']).struct.unnest())
```

### Issue description

It panics when you unnest in the same context. Unnesting with pl.all().struct.field("*") in a context aftewards works.

### Expected behavior

Don't panic

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
This should be clustered with other `to_struct` issues. `to_struct` should take a required `dtype` argument as it is unknown to the engine what the output type will be.

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/19307#issuecomment-2423742894 contains a list of all the ones I found.

**Comment by ritchie46** [comment]
Will close this as duplicate. Hope to get to this end of this week.
