### ISSUE TITLE
Add missing arguments to rolling other functions

### ISSUE THREAD

**Issue by aerjayc** [pola-rs/polars#1938]
Right now, (as far as I can tell) all the rolling transforms have `weights`, `min_periods`, and `center` as arguments, except for the following:
- `rolling_median`
- `rolling_quantile`
- `rolling_skew`
- `rolling_apply`

It would be great if those arguments also get included there.

**Comment by marcvanheerden** [comment]
I'll work this

**Comment by ritchie46** [comment]
@marcvanheerden I woudl ignore `rolling_skey` for now. It uses dynamic dispatch at the moment and is really slow and would be even slower with those args.

**Comment by marcvanheerden** [comment]
fixed in https://github.com/pola-rs/polars/pull/2001

**Comment by marcvanheerden** [comment]
working on this now

**Comment by marcvanheerden** [comment]
options added to rolling_median and rolling_quantile in https://github.com/pola-rs/polars/pull/2229, will work on rolling_apply now in a separate PR
