### ISSUE TITLE
Crashes and false values from `CategoricalSeries.unique()`

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#19409]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"x": [str(n) for n in range(50)]}).cast(pl.Categorical)
print(df.unique().null_count())

shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ u32 │
╞═════╡
│ 2   │
└─────┘
```

### Issue description

Notice that nulls appear in a series without nulls, after taking `unique()`.
Sometimes python quits without printing anything, depending on the categorical series I test with.
Bug does not seem to be present in version 1.10

### Expected behavior

Don't add nulls, don't crash.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.11.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.10.4
fsspec               2024.6.1
gevent               <not installed>
great_tables         0.9.0
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             3.1.5
pandas               2.2.2
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.35
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by cmdlineluser** [comment]
I haven't been able to get a crash, but do get a `null_count()` of `2` each time.

It seems to have changed after https://github.com/pola-rs/polars/pull/19359

**Comment by ritchie46** [comment]
@orlp can you take a look?

**Comment by orlp** [comment]
I can reproduce, but only with `POLARS_MAX_THREADS=2`.
