### ISSUE TITLE
Integer overflow issues

### ISSUE THREAD

**Issue by TomScheffers** [pola-rs/polars#1941]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.10.25

#### What operating system are you using polars on?

MacOS, 

#### Describe your bug.

Integer can easily overflow when aggregating small i8/i16 columns (which are often stored that way in parquet files).

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame({
    "foo": [1] * 100000
}).select(pl.col('foo').cast(pl.datatypes.Int8))

print(df.sum())
```

#### What is the actual behavior?

Returns value -96 (should return 100000)
shape: (1, 1)
┌─────┐
│ foo │
│ --- │
│ i8  │
╞═════╡
│ -96 │
└─────┘

#### What is the expected behavior?

Numpy does cast to int64 in the sum process:
```python
import numpy as np

a = np.ones(100000).astype(np.int8)

print(a.sum(), type(a.sum()))
```

This returns: 100000 <class 'numpy.int64'>

**Comment by ghuls** [comment]
Running `sum` on the column itself instead of the whole dataframe, gives an indication what is happening:

```python
In [9]: df.select(pl.col("foo").sum())
thread '<unnamed>' panicked at 'attempt to add with overflow', /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs:107:1thread '
<unnamed>' panicked at 'attempt to add with overflow', /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rsthread ':thread '<unnamed>107<unnamed>' panicked at 'thread 'thread ':' panicked at 'attempt to add with overflow<unnamed><unnamed>1attempt to add with overflow', ' panicked at '/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs' panicked at '
thread '', attempt to add with overflowthread ':attempt to add with overflow<unnamed>/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs', <unnamed>107', ' panicked at ':/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs107' panicked at ':/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rsattempt to add with overflow::attempt to add with overflow1:', 1071', 
107/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs:
/rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs:::11071107
:
:1thread '1
<unnamed>
' panicked at 'attempt to add with overflow', /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs:107:1
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-9-1192d723abbc> in <module>
----> 1 df.select(pl.col("foo").sum())

~/software/anaconda3/envs/polars_test/lib/python3.9/site-packages/polars/internals/frame.py in select(self, exprs)
   2825         """
   2826         return (
-> 2827             self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)  # type: ignore
   2828         )
   2829 

~/software/anaconda3/envs/polars_test/lib/python3.9/site-packages/polars/internals/lazy_frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization)
    296             string_cache,
    297         )
--> 298         return pli.wrap_df(ldf.collect())
    299 
    300     def fetch(

PanicException: attempt to add with overflow

In [10]: df.select(pl.col("foo").cast(pl.Int64).sum())
Out[10]: 
shape: (1, 1)
┌────────┐
│ foo    │
│ ---    │
│ i64    │
╞════════╡
│ 100000 │
└────────┘

```

**Comment by ritchie46** [comment]
Rust does not check overflowing in --release compilations for performance reasons. Polars also does not.

We could argue that a `sum` a `product` is very likely to overflow, so we always cast on this operation.

This is the logic numpy has chosen. Also numpy has overflow on other operations:

```python
>>> a = np.array([240, 255], dtype=np.uint8)
>>> a[0] * a[1]
16
```

**Comment by TomScheffers** [comment]
Thanks for your quick response. I agree that it is the users responsibility to make sure the typings are correct for certain aggregations which can overflow. It took me quite some time to realize what was going wrong, as I didn't realize the parquet writer downcasted all integers. 

Would it be reasonable to have user warnings appear on the df.sum() operation, in case an aggregation overflows?

**Comment by ritchie46** [comment]
> Would it be reasonable to have user warnings appear on the df.sum() operation, in case an aggregation overflows?

How would we know? Casting and checking with a larger integer would be very expensive.

**Comment by TomScheffers** [comment]
@ritchie46 from the code example @ghuls gave, you can see that the underlying thread did panic for the columnar sum(). Is this something which you can pass when performing a dataframe sum(), as a warning? 
`thread '<unnamed>' panicked at 'attempt to add with overflow', /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/ops/arith.rs:107:1thread '
`

**Comment by ritchie46** [comment]
This is only the case if you compile in `--debug` mode. Every operation is then checked for overflow, but this comes with a runtime cost.

You can turn this behavior on in `--release` mode, but that requires a recompile. 

Now I do think casting anything lower than `i32` to `i64` when doing a sum aggregation is not that bad. The likelihood of overflow is high. What do you think @ghuls?

**Comment by ghuls** [comment]
@ritchie46 that might be reasonable to do. Maybe it also should take in to account on how many values it will operate to determine if it needs to cast to i32 or i64. Casting to i64 might be "safer" as overflow should be very rare, with i32 is is still quite possible, especially if a big column gets summed.
There are also some other polars functions  that now cast to i32 (or u32) which might not be big enough to avoid overflow in some cases (I know rank has it, u32 is probably fine for this one).

**Comment by ritchie46** [comment]
If we do it I will only want to do it based on the dtypes + operations. So that you statically can reason about the schema we get.

The schema may not change if you load a bigger file IMO.

**Comment by ghuls** [comment]
I also would like for it to be deterministic. Probably best to  follow numpy here and use i64 (as overflow with i32 can be difficult to spot and in general only happen on big files.

**Comment by ritchie46** [comment]
#1947 adds automatic coercion to the small integers in the `sum, cumsum and cumprod` operation.

For `i32`, I don't want this to automatically happen. So, I think an `up` expression as @ghuls suggests can be valuable.
