### ISSUE TITLE
`max` and `min` method of numeric dtypes

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#19412]
### Description

It would be great to have something like `i64::MAX` of Rust to quickly call the minimum and maximum literals for each numeric dtype.

For example in Python:

```python
pl.Int8.max # returns `pl.lit(127, pl.Int8)`
```

**Comment by Skeletonboi** [comment]
same, is there a workaround for this

**Comment by alexander-beedie** [comment]
We have `upper_bound()` and `lower_bound()` on Series, which does much the same thing - doesn't seem unreasonable to offer it on the dtype (where arguably it's more discoverable/useful) 🤔
