### ISSUE TITLE
`rle()` does not respect leftmost-argument naming rule

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#19429]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series("foo", [1, 1, 2]).rle().dtype
# Struct({'len': UInt32, 'value': Int64})
```

### Issue description

I think the rules changed since `rle` was last updated https://github.com/pola-rs/polars/issues/15230 

And `Struct({'len': UInt32, 'foo': Int64})` would be the expected output now?

### Expected behavior

`Struct({'len': UInt32, 'foo': Int64})`

### Installed versions

<details>

```
main
```

</details>

**Comment by stinodego** [comment]
The struct fields are called `len` and `value` - the column itself is called `foo`. I think there is no bug here.

**Comment by cmdlineluser** [comment]
Thank you @stinodego
