### ISSUE TITLE
ddof parameter on pl.corr is nonsensical

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#19420]
I only realized this after implementing it recently, but the ddof parameter is not used for `pl.corr` at all. It completely cancels out of the formula. To confirm this in [`np.corrcoef`](https://numpy.org/devdocs/reference/generated/numpy.corrcoef.html) you'll see:

```
ddof: _NoValue, optional
    Has no effect, do not use.
```

We should just remove the parameter in the Rust code and on the Python side deprecate the parameter, removing it in 2.0.

**Comment by orlp** [comment]
The same holds for `pl.rolling_corr`.

**Comment by zachlefevre** [comment]
I am interested in doing this work as my first contribution to Polars.

**Comment by zachlefevre** [comment]
I'm still working on getting my local dev machine setup -- made more difficult since I use Guix.

**Comment by hshreekar** [comment]
Hi @orlp, so on the rust side we would need to remove the finalize call or do we need to change the implementation and calculate it using some other formula ? 
this is the function pearson_corr in polars/crates/polars-ops/src/chunked_array/cov.rs. I assume this is the implementation and i would need to modify it for every usage of this function and also for Spearman, and the other method in the Enum ?
<img width="700" alt="Screenshot 2024-11-24 at 2 50 31 PM" src="https://github.com/user-attachments/assets/c279b81a-b985-40f7-bdaa-235afaf00e4b">

**Comment by flowlight0** [comment]
Hello! Since other potential contributors looks inactive, let me make my first contributions to Polars :) (https://github.com/pola-rs/polars/pull/20197)
