### ISSUE TITLE
Interpolation options on `quantile`, `rolling_quantile`

### ISSUE THREAD

**Issue by aerjayc** [pola-rs/polars#1943]
It would be neat if some interpolation options are added to the quantile Exprs. For example, pandas supports the following:

> **interpolation**: `{‘linear’, ‘lower’, ‘higher’, ‘midpoint’, ‘nearest’}`
> This optional parameter specifies the interpolation method to use, when the desired quantile lies between two data points i and j:
>
> - linear: `i + (j - i) * fraction`, where `fraction` is the fractional part of the index surrounded by `i` and `j`.
> - lower: `i`.
> - higher: `j`.
> - nearest: `i` or `j` whichever is nearest.
> - midpoint: `(i + j) / 2`.

The current behavior of quantile seems to be `'nearest'`:
```python
In [2]: pl.DataFrame({'value': [1, 2, 3, 4]}).with_columns([pl.col('value').quantile(0.49).suffix('_0.49'), pl.col('value').quantile(0.5).suffix('_0.5')])
Out[2]:
shape: (4, 3)
┌───────┬────────────┬───────────┐
│ value ┆ value_0.49 ┆ value_0.5 │
│ ---   ┆ ---        ┆ ---       │
│ i64   ┆ i64        ┆ i64       │
╞═══════╪════════════╪═══════════╡
│ 1     ┆ 2          ┆ 3         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 2          ┆ 3         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3     ┆ 2          ┆ 3         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4     ┆ 2          ┆ 3         │
└───────┴────────────┴───────────┘
```

**Comment by ritchie46** [comment]
@marcvanheerden, is this something?

**Comment by marcvanheerden** [comment]
Yes, I'll work on this

**Comment by marcvanheerden** [comment]
@ritchie46 I like the current behaviour better than pandas' nearest. Polars quantile splits [1,2,3] at quantiles 0.333 and 0.666 where Pandas splits it at quantiles 0.25 and 0.75. 

You can check it with this:
```[(idx, pd.Series([1,2,3]).quantile(q/100, interpolation="nearest")) for idx, q in enumerate(range(101))]```

I think we should keep the current behaviour for nearest, let me know if you would rather be aligned to pandas.

**Comment by ritchie46** [comment]
> @ritchie46 I like the current behaviour better than pandas' nearest. Polars quantile splits [1,2,3] at quantiles 0.333 and 0.666 where Pandas splits it at quantiles 0.25 and 0.75.
> 
> You can check it with this: `[(idx, pd.Series([1,2,3]).quantile(q/100, interpolation="nearest")) for idx, q in enumerate(range(101))]`
> 
> I think we should keep the current behaviour for nearest, let me know if you would rather be aligned to pandas.

We average in the case we have two candidates for the quantile right?

**Comment by marcvanheerden** [comment]
Assuming you're referring to the case where the quantile is exactly in between two values i.e. the 0.5 quantile of [1,2,3,4]? In that case it currently take the higher value (3). The idea of the "nearest" option seems to be that it would always return an actual value, would you like it to average instead?

**Comment by marcvanheerden** [comment]
fixed in https://github.com/pola-rs/polars/pull/2001
