### ISSUE TITLE
polars.rolling_corr() introduce unexpected NaN/Inf value

### ISSUE THREAD

**Issue by ycsun666** [pola-rs/polars#19437]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({ "a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
df = df.with_columns([
    pl.rolling_corr(pl.col("a"), pl.col("a").shift(1), window_size=3, min_periods=1).alias("rolling_corr")
])
print(df)
```

### Log output

```shell
shape: (10, 2)
┌─────┬──────────────┐
│ a   ┆ rolling_corr │
│ --- ┆ ---          │
│ i64 ┆ f64          │
╞═════╪══════════════╡
│ 1   ┆ null         │
│ 2   ┆ NaN          │
│ 3   ┆ 1.0          │
│ 4   ┆ 1.0          │
│ 5   ┆ 1.0          │
│ 6   ┆ 1.0          │
│ 7   ┆ 1.0          │
│ 8   ┆ 1.0          │
│ 9   ┆ 1.0          │
│ 10  ┆ 1.0          │
└─────┴──────────────┘
```

### Issue description

Unexpected NaN apprear from rolling_corr, should be null

### Expected behavior

2, rolling_corr should be null

### Installed versions

<details>

```
--------Version info---------
Polars:              1.11.0
Index type:          UInt32
Platform:            macOS-14.3.1-arm64-arm-64bit
Python:              3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]
LTS CPU:             False
```

</details>

**Comment by orlp** [comment]
No, the current behavior is correct. `corr` never returns nulls, and for the second value there is at least 1 non-null pair in the window so `min_periods` is satisfied.
