### ISSUE TITLE
Length of window expression error from version 1.10 to 1.11

### ISSUE THREAD

**Issue by Chuck321123** [pola-rs/polars#19452]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

No reproducible example

### Log output

```shell
Traceback (most recent call last):

  Cell In[12], line 1
    df = df.with_columns(pl.col("Prices").shift(1).over("Group"))

  File ~\anaconda3\envs\py312Test\Lib\site-packages\polars\dataframe\frame.py:9194 in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)

  File ~\anaconda3\envs\py312Test\Lib\site-packages\polars\lazyframe\frame.py:2055 in collect
    return wrap_df(ldf.collect(callback))

ComputeError: the length of the window expression did not match that of the group

Error originated in expression: 'col("Prices").shift([dyn int: 1]).over([col("Group")])'
```

### Issue description

Tried to replicate example, but still unsuccessful. Ran the same code in 1.10 and it worked fine. Bonus issue is that when i run df.group_by("Group").head(5) to get a smaller df it restarts the kernel, both in Spyder and in Jupyter Notebook. Would be nice to fix the issue above. Fyi: Prices are f32, Group is a categorical dtype. There are no null values in either Prices nor Group. 

PS: Even ``df = df.with_columns((pl.col("Prices") + 1).over("Group"))`` raises the same error.

### Expected behavior

That it works

### Installed versions

<details>

```
--------Version info---------
Polars:              1.11.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.5 | packaged by Anaconda, Inc. | (main, Sep 12 2024, 18:18:29) [MSC v.1929 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you make a repro? We cannot do anything without one.

**Comment by Chuck321123** [comment]
@ritchie46 Creating a repro is difficult. However, I have made some discoveries. Writing the df to parquet and reading it back in fixes the problem. Converting to pandas and back to polars fixes the problem, and last but not least: If i remove ``df = df.with_columns(pl.col("Group").cast(pl.Categorical))`` before running the function, it works. Alternatively if i conver thte group column to string, so it must be something with the categorical dtype

**Comment by Chuck321123** [comment]
@ritchie46 Reproducible sample: 
```py
import polars as pl
import numpy as np
import pandas as pd

np.random.seed(42)
num_rows = 8000
num_columns = 250

date_range = pd.date_range(start="2023-01-01", periods=num_rows, freq='min')  # 'T' for minute frequency

random_data = np.random.rand(num_rows, num_columns)

df = pl.DataFrame({
    "Datetime": date_range,
    **{f"Random_{i+1}": random_data[:, i] for i in range(num_columns)}
})

# Flip the columns, drop nans and reset index (This is the place that produces the error afterwards)
df2 = (df.unpivot(index=["Datetime"], on=df.collect_schema().names()[1:], variable_name="Group", value_name="Prices").filter(pl.col("Prices").is_not_null()))

df2 = df2.with_columns(pl.col("Group").cast(pl.Categorical))

df2 = df2.with_columns((pl.col("Prices") + 1).over("Group"))
```

**Comment by cmdlineluser** [comment]
Does it still reproduce for you if you run with `POLARS_MAX_THREADS=1`?

For me, I had to set a different `num_cols`  to get a failure, it always succeeded with `250`.

`num_cols = 18` seemed to be the minimum in order to fail.

With `POLARS_MAX_THREADS=1` it does not reproduce.

It does not reproduce on main, which suggests it may be another form of the linked issue.

**Comment by Chuck321123** [comment]
@cmdlineluser Yes, it also worked for all number of rows and all num_cols below 243, however, a column amount over that and I got the compute error

**Comment by ritchie46** [comment]
mre:


```python
df2 = pl.DataFrame({
    "a": pl.int_range(40, eager=True).cast(pl.String).cast(pl.Categorical),
})

df2.with_columns((pl.col("a") + 1).over(pl.col("a")))
```

**Comment by orlp** [comment]
This was already fixed in https://github.com/pola-rs/polars/pull/19417. Not sure how the other PR didn't get merge conflicts with this one.
