### ISSUE TITLE
Github release for rust-polars 0.44.0?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#19484]
### Description

rust-polars 0.44.0 was released a few hours ago but the Github release (and therefore the changelog) is missing, maybe because some workflows failed. Could you add one? 

Thank you

**Comment by cmdlineluser** [comment]
Odd. It still seems to be listed first in https://github.com/pola-rs/polars/releases

https://github.com/pola-rs/polars/releases/tag/rs-0.44.0

**Comment by etiennebacher** [comment]
My bad, but I don't understand why it doesn't appear in the "Releases" tab of github.com/pola-rs/polars since it's the most recent release.
