### ISSUE TITLE
The rust documentation only mentions the `lazy` feature is required for `int_range` when `range`, too is a prerequisite.

### ISSUE THREAD

**Issue by cafce25** [pola-rs/polars#19496]
### Description

Add `range` to the required features of `int_range`

### Link

https://docs.rs/polars/latest/polars/prelude/fn.int_range.html

**Comment by orlp** [comment]
The Rust `polars` crate at the moment is just a dump of our internals. The feature requirements at this point are also completely autogenerated, and not something we can maintain manually, as it will easily go out of date.

I understand this is frustrating, I hope that sometime next year we can make some time to make a (more) stable well-documented Rust API for Polars similar to the Python API. But for now I'll close this as there are probably 500 different other subtly-incorrect feature markings that just aren't a current priority.

**Comment by noiseOnTheNet** [comment]
While I completely understand this point, I find it quite frustrating. I really am trying to move my data analysis and ml projects from python to Rust, and Polars is a cornerstone. If possible I'd like to share the "recipes" I discovered for some common but not largely documented cases.
