### ISSUE TITLE
Delimited line breaks are ignored when skipping lines in CSV read or scan

### ISSUE THREAD

**Issue by BTatlock** [pola-rs/polars#19535]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.read_csv(b'"a\nb"\n0', has_header=False, skip_rows=1)
```

### Log output

```shell
polars.exceptions.ComputeError: could not parse `b"` as dtype `i64` at column 'column_1' (column number 1)
```

### Issue description

Escaped newline characters should not be counted when skipping rows.

### Expected behavior

The result should be the same as with `pl.read_csv(b'\n0', has_header=False, skip_rows=1)`.

The same behaviour also results in unexpected/inconsistent behaviour without any exceptions occurring. The following example should not result in an `AssertionError`, but does:

```python
import polars as pl
from polars.testing import assert_frame_equal

csv = b'"0\n1"\n2\n3'
assert_frame_equal(
    pl.read_csv(csv, has_header=False, infer_schema=False).slice(2),
    pl.read_csv(csv, has_header=False, infer_schema=False, skip_rows=2),
)
```

Replacing `pl.read_csv` with `pl.scan_csv` in the above example also results in an `AssertionError`.

### Installed versions

<details>

```
Polars:              1.12.0
```

</details>

**Comment by ritchie46** [comment]
@nameexhaustion can you take this one. I think we can use the `SplitLines` to first respect `skip_rows` before we go into the `CountLines` logic.
