### ISSUE TITLE
replace fast-float with fast-float2

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#19541]
### Description

The fast-float crate has not been maintained, with the last release more than four years ago.

fast-float2 is a fork by one of the main contributors now that the maintainer has been unresponsive.

https://github.com/aldanor/fast-float-rust/issues/35#issuecomment-2446828115

Also see #13035

**Comment by Alexhuszagh** [comment]
This might be worth waiting until version `0.2.2`, which will be very soon. I'm ripping out most of the unsafe code where the safety checks can be elided by the compiler, avoiding a lot of the potential unsoundness documented in https://github.com/aldanor/fast-float-rust/issues/37.

**Comment by Alexhuszagh** [comment]
Version `0.2.2` has been published which removes most of the unsafe code and removes locally unsound "safe" methods, by either ensuring they maintain safety invariants or are marked as unsafe with the required preconditions documented to ensure the caller uses them correctly.

This addresses all of the unsoundness mentioned in https://github.com/aldanor/fast-float-rust/issues/37, as well as in other locations.
