### ISSUE TITLE
Add support for free-threaded python3.13

### ISSUE THREAD

**Issue by notron30** [pola-rs/polars#19594]
### Description

This could enable map_elements(strategy='threading') to be parallelized across CPU cores.

**Comment by alexander-beedie** [comment]
Not sure if you're aware, but that mode requires a separately compiled Python binary - it is not available in the standard release of Python 3.13. Consequently the number of people who can currently take advantage of it is approximately 0% ;)

**Comment by notron30** [comment]
Understood, thank you. Since I saw pandas added support, I figured polars might as well. [https://py-free-threading.github.io/tracking/](url)

**Comment by mescanne** [comment]
This is also very much worth experimenting with for Polars as well -- I recently was doing an experiment trying to increase performance with a full stack including polars. Polars was the only library that couldn't load with Python 3.13t. Quite happy to have experimental written everywhere, but the earlier we make it available the more we can collect issues/learn.

**Comment by cmdlineluser** [comment]
It looks like this is now being tracked in https://github.com/pola-rs/polars/issues/21889
