### ISSUE TITLE
Grab unique column selections when duplicates are detected

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1961]
Sometimes I'll try and do a regex selection which leads to duplicate column selections. Currently polars errors - would it be possible to just grab unique column names in the background?

```python
import polars as pl
from polars import col

df = pl.DataFrame(
    {'x1': range(3),
     'x_y': range(3),
     'y': range(3)}
)

df.select(['^x.*$', '^.*y$'])

RuntimeError: Any(Duplicate("Column with name: 'x_y' has more than one occurrences"))
```

**Comment by ritchie46** [comment]
I believe you can just make your regular expression non greedy.

```
df.select(['^(x.*|.*y)?$'])
```

**Comment by markfairbanks** [comment]
Thanks - that does work.

I still think this would be a good feature, but feel free to close if you don't think it's something worth implementing.

**Comment by ritchie46** [comment]
That would mean that 

```
df.select([
   pl.col("A"),
   pl.col("A"),
   pl.col("B").alias("A")
 ])
```

would only return the first column "A". I rather have an error and let people correct the query. The regex you provided selected multiples, where regex comes with a lot of power to select exactly what you need.

So I will close this as I prefer the error.
