### ISSUE TITLE
`df.rows()`  is sensibly slower than `list(df.iter_rows())`  when the dataframe is chunked

### ISSUE THREAD

**Issue by DavideCanton** [pola-rs/polars#19627]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [1]: df = pl.concat([pl.DataFrame({'a': [0]}) for _ in range(100_000)])

In [2]: %timeit df.rows()
4.66 s ± 59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit list(df.iter_rows())
47.7 ms ± 943 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: rechunked = df.rechunk()

In [5]: %timeit rechunked.rows()
4.81 ms ± 48.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [6]: %timeit list(rechunked.iter_rows())
7.49 ms ± 584 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### Issue description

Given an highly chunked dataframe, `df.rows` seems way slower than `list(df.iter_rows())`. Rechunking the dataframe reduces drastically the execution time, but still it's strange that `iter_rows` is considerably faster than `rows`, given that the first is implemented using the second.

### Expected behavior

I expect the performances of the two operations to be consistent.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by orlp** [comment]
Can reproduce, we're probably doing something quadratic, will investigate.

**Comment by orlp** [comment]
Our iterator is just rather naive and repeatedly calls `.get(idx)`, which means it has to iterate over all the chunks for each row.

I'll make sure it rechunks first if there's too many chunks. Ideally the iterator would just iterate over the chunks as they are but that's too much of an implementation effort for me right now.
