### ISSUE TITLE
Join cardinality validation shall not raise on multiple null values (that never produce matches)

### ISSUE THREAD

**Issue by sibbiii** [pola-rs/polars#19624]
### Description

According to the documentation, the validate parameter of polars.DataFrame.join checks whether 
join keys are unique in the left/right/both datasets.

Consequently,

```python
left = pl.DataFrame({'a': [1, 2, None, None]})  # unique key and some missing data
right = pl.DataFrame({'a': [1, 1, 2, 2]})  # non-unique key

_ =left.join(right, how="left", on="a", join_nulls=False, validate="1:m")  
```

fails with `polars.exceptions.ComputeError: join keys did not fulfill 1:m validation`.
but this is clearly a **one to many join**.

Note: `nulls` are not joined (join_nulls = False), 
so the left dataframe is unique (except for the nulls).

__Use case__

Real world datasets often have null values for missing data (the example above is just greatly simplified). On such datasets, no cardinality validation can be performed on a left join.

I googled a bit and tied to find similar issues but could not find one. I am also not sure if my question here makes sense (the current behaviour is as documented) but in my option the example above is clearly a `one-to-many` join with some missing data.

__Expected behaviour__

Exclude null values from the uniqueness check if join_nulls=False (null values will not produce matches)
The example above shall therefore not raise a ComputeError.

(Note: I am not sure if the current behaviour is only because of Pandas.
original issue that added join cardinality validation: https://github.com/pola-rs/polars/issues/9263)

**Comment by barak1412** [comment]
@orlp May you assign me?
