### ISSUE TITLE
Use nullable integers in .to_pandas()

### ISSUE THREAD

**Issue by el-hult** [pola-rs/polars#19640]
### Description

Calling `.to_pandas()` should return nullable integer types. Consider below snippet.

```
import pandas as pd
import polars as pl
s = pd.Series([1,pd.NA],dtype='Int64')
s2 = pl.Series(s).to_pandas()
print(s.dtype,s2.dtype)
```
It returns 
```
Int64 float64
```
where I expected the nullable integer type (`IntXX`) to round trip properly.

It seems this should be supported from pandas 1.0, released almost 5 years ago.

**Comment by alexander-beedie** [comment]
We already have this capability; however, the nullable types you mention are essentially deprecated in favour of the newer pyarrow types, which are what we support:
```python
pl.Series(s).to_pandas(use_pyarrow_extension_array=True)

# 0       1
# 1    <NA>
# Name: , dtype: int64[pyarrow]
```

**Comment by el-hult** [comment]
amazing. thanks!
