### ISSUE TITLE
Speed up .when().then().otherwise() function by only calculate the result for matching rows.

### ISSUE THREAD

**Issue by y9c** [pola-rs/polars#19670]
### Description

I tried to use `.when(...).then(...).otherwise(..)` function along with `map_elements(...) / map_batches(...)` function. The computation time of map_elements is long if all the rows are computated. However, I do not need to calculate the results for all the rows, because they are located in `otherwise(...)` function. 

Is it possible to speed up this process?

**Comment by cmdlineluser** [comment]
You may be able to use `.when().then().map_elements()` to run the UDF for the non-null rows only. (as map_elements defaults to `skip_nulls=True`)

- https://stackoverflow.com/a/79007841

**Comment by y9c** [comment]
Thank you @cmdlineluser, but is this work for map_batches which take multiple columns as input?

**Comment by cmdlineluser** [comment]
No, it wont.

I believe the recommended pattern for that is to `filter`, perform the transformation and `join` the result back?

```python
(df.with_row_index()
   .join(
        df.with_row_index().filter(...).select("index", ...),
        on = "index",
        how = "left"
   )
)
```

**Comment by y9c** [comment]
Yes. This is my current solution, but I didn't realized that with_row_index function can be used to speed up. Thank you very much.
