### ISSUE TITLE
When summing all null values, it should return null instead of zero.

### ISSUE THREAD

**Issue by im5h** [pola-rs/polars#19686]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "type": ["A", "A", "B", "B", "C", "C"],
        "year": ["2021", "2021", "2022", "2022", "2021", "2022"],
        "value": [234, None, None, None, 876, 654],
    }
)

df.group_by("type", "year").agg(pl.col("value").sum())

# output:
"""
type	year	value
str	str	i64
"B"	"2022"	0
"C"	"2021"	876
"C"	"2022"	654
"A"	"2021"	234
"""

df.group_by("type").agg(
    pl.when(pl.col("year")=="2021").then(pl.col("value")).sum().alias("value2021"),
    pl.when(pl.col("year")=="2022").then(pl.col("value")).sum().alias("value2022")
)

# output:
"""
type	value2021	value2022
str	i64	i64
"B"	0	0
"A"	234	0
"C"	876	654
"""
```

### Issue description

When summing all null values, it return zero.

### Expected behavior

it should return null instead of zero.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Python:              3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
LTS CPU:             False
```

</details>

**Comment by stinodego** [comment]
This is intentional. Zero is the identity of the sum operation.

**Comment by Julian-J-S** [comment]
@stinodego 

other very popular engines (Spark, Duckdb to name a few) result in `null`
- given column `x: [None, None]` the `sum(x)` is
- polars/pandas: 0
- spark / duckdb: `null`

Is there no general consens what the result should be? 
Thoughts? 🤔  😄

**Comment by stinodego** [comment]
This has been discussed before multiple times. I don't have a link right now.

There is no general consensus about this, as you have noticed. We choose to return the identity in this case as we think it's the most useful.

**Comment by Julian-J-S** [comment]
Thanks!

I think this is actually "enforced" by the sql standard (so might be interesting to note for polars sql).
Operations like `min/max/sum` etc. first remove all `null` rows.
If the result is zero remaining rows the sql standard requires the result to be `null` instead of 0.
Maybei weird, but interesting to know 🤣

**Comment by cmdlineluser** [comment]
I think this is where returning 0 was initially decided:

- https://github.com/pola-rs/polars/issues/8500

There is also an open discussion:

- https://github.com/pola-rs/polars/issues/17527
