### ISSUE TITLE
phi_k library does not accept DataFrame polaris

### ISSUE THREAD

**Issue by Vla495** [pola-rs/polars#19709]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

import phik

#Assigning each variable to a type. phik also automatically outputs variable types, it is not recommended to assign the type yourself

data_types = {'administrative':'ordinal'
              ,'administrative_duration':'interval'
              ,'informational':'ordinal'
              ,'informational_duration':'interval'
              ,'productrelated':'ordinal'
              ,'productrelated_duration':'interval'
              ,'bouncerates':'ordinal'
              ,'exitrates':'interval'
              ,'pagevalues':'interval'
              ,'specialday':'ordinal'
              ,'month':'ordinal'
              ,'visitortype':'categorical'
              ,'weekend':'ordinal'
              ,'revenue':'ordinal'
            }

#Since interval type variables must be added to calculate phik, a list of interval variables is created.

interval_cols_pl = [col for col, v in data_types.items() if v=='interval' and col in df_pl.columns]

#columns DataFrame

pl_all_columns = list(df_pd.columns)

#Correlation matrix

corrilations = df_pl[pl_all_columns].phik_matrix(interval_cols = interval_cols_pl)

### Log output

```shell
The phi_k library does not accept the polaris DataFrame. an error occurs when transmitting data

AttributeError                            Traceback (most recent call last)
Cell In[88], line 2
      1 # Матрица корреляции
----> 2 corrilations = df_pl[pl_all_columns].phik_matrix(interval_cols = interval_cols_pl)

AttributeError: 'DataFrame' object has no attribute 'phik_matrix'
```

### Issue description

Verbose output should display after setting POLARS_VERBOSE=1

### Expected behavior

вывод DataFrame
![the_result_from_pandas](https://github.com/user-attachments/assets/be512adf-8922-45ac-98f6-f675ca0855e4)

### Installed versions

<details>

Polars:              1.12.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
LTS CPU:             False

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report,but i think you need to report this to phi_k https://github.com/KaveIO/PhiK

**Comment by Vla495** [comment]
Hi! So, as an experiment, I converted a Polars DataFrame into a Pandas DataFrame, and phik didn’t throw an error. I’ll submit an inquiry to the phik team, but I’m concerned they might redirect me back to you, since everything works fine with a Pandas DataFrame.

**Comment by Vla495** [comment]
> thanks for the report,but i think you need to report this to phi_k https://github.com/KaveIO/PhiK

Hi! So, as an experiment, I converted a Polars DataFrame into a Pandas DataFrame, and phik didn’t throw an error. I’ll submit an inquiry to the phik team, but I’m concerned they might redirect me back to you, since everything works fine with a Pandas DataFrame.

**Comment by MarcoGorelli** [comment]
> they might redirect me back to you

Indeed, they might, but for a different reason - I've written a compatibility layer between dataframes, which they might be interested in using if they want to support multiple dataframe inputs https://github.com/narwhals-dev/narwhals
