### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#1971]
Perhaps you already know, but with what my web browser shows me, many of the code samples on [this page](https://pola-rs.github.io/polars-book/user-guide/dsl/contexts.html) are missing. This feelings like a crucial missing link that I've had to build around when trying to onboard with polars.

**Comment by zundertj** [comment]
@ritchie46 : I can pick this up. At https://github.com/pola-rs/polars-book/blob/master/user_guide/src/dsl/contexts.md, I see they are missing as they import from another file, but the wrong line. I guess the question is whether we should import from other files at all, and instead just plug in the code in the .md file, like for the code that is working?

**Comment by ritchie46** [comment]
I just fixed this. But thanks @zundertj  :)
