### ISSUE TITLE
docs: most plots no longer show

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#19718]
### Description

I recall that on https://docs.pola.rs/user-guide/misc/visualization/#plotly, the plots were visible

Instead, now, we can only see those for matplotlib and seaborn

@rodrigogiraoserrao i think you've looked at the user guide quite a bit recently, do you know what this may be due to?

### Link

https://docs.pola.rs/user-guide/misc/visualization/#plotly

**Comment by MarcoGorelli** [comment]
🤔 looks like refreshing the page makes the plots appear...but why don't they show the first time round?

**Comment by stinodego** [comment]
The plots page has been finnicky ever since it was published. They show normally for me though (even on first visit).

**Comment by rodrigogiraoserrao** [comment]
I opened the link and they also showed for me on the first visit / without refreshing ... 🤷

**Comment by braaannigan** [comment]
Closed by #19788
