### ISSUE TITLE
Bokeh Error when navigating to Visualization page for second time

### ISSUE THREAD

**Issue by LiamConnors** [pola-rs/polars#19722]
### Description

The Visualization page shows an error if you go to it for a second time when using the docs:

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/4ce13038-5691-4658-92e9-ba977b331ce1">

To reproduce:
1. Go to https://docs.pola.rs/user-guide/ 
2. From the sidebar, go to **Misc**>**Visualization**.
3. Go to any other page from the sidebar.
4. Go again to **Misc**>**Visualization**.
Shows error

Noted on Chrome and Firefox

### Link

https://docs.pola.rs/user-guide/misc/visualization/

**Comment by MarcoGorelli** [comment]
Thanks for the report, can confirm

@braaannigan I think you might have added the visualisation page originally? Any idea what this might be due to?

**Comment by braaannigan** [comment]
@MarcoGorelli I think it might happen when bokeh tries to initialise on the 2nd visit but it has already been initialised in the first visit. I've got some ideas, will have a look
