### ISSUE TITLE
Add dtypes argument to read_csv

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#1972]
#### Describe your feature request

Very small quality of life change: when working with a dataframe, the correct attribute for accessing the data types is `df.dtypes` and not `df.dtype`. So can we have the argument for `read_csv` be `dtypes`? (it's currently `dtype`, I'd be fine if they were aliases for one another, but its annoying one is plural and the other isn't, especially since `dtype` contains many types).

**Comment by ritchie46** [comment]
Sorry, but I don't think this is worth a breaking change, or two parameters.

**Comment by LiterallyUniqueLogin** [comment]
Fair enough. If it's possible to have the error message for `read_csv(dtypes='...')` be `argument 'dtypes' doesn't exist. Did you mean 'dtype'?` that'd be great, but if not that's fine too.

**Comment by ritchie46** [comment]
Sorry, but we're not going to fuzzy match against all possible keyword arguments. We have a reference guide.
