### ISSUE TITLE
Support StrEnums in Enum Construction

### ISSUE THREAD

**Issue by max-muoto** [pola-rs/polars#19724]
### Description

Right now, if you want to create Polars enum from a `StrEnum` you're required to first list convert it:

```python
import enum

class PythonEnum(enum.StrEnum):
    A = "A"
    B = "B"
    C = "C"

e = pl.Enum(list(PythonEnum))
df = pl.DataFrame({"Col 1": ["A", "B", "C"]}, schema={"Col 1": e})
```

While easy enough, I don't see any reason why direct creation of Polars Enums from Python enums shouldn't be supported:

```python
import enum

class PythonEnum(enum.StrEnum):
    A = "A"
    B = "B"
    C = "C"

e = pl.Enum(PythonEnum)
df = pl.DataFrame({"Col 1": ["A", "B", "C"]}, schema={"Col 1": e})
```

**Comment by Julian-J-S** [comment]
why not go one step further and use the python enum directly? (should be possble?) 😄 
This works for exmpale using python `str` / `int` / `float`
```python
pl.DataFrame(
    {"a": [1], "b": [1], "c": [1]},
    schema={
        "a": pl.String,
        "b": str, # <<<<<
        "c": float, # <<<<<
    },
    strict=False,
)
```
