### ISSUE TITLE
read_csv doesn't handle scientific notation

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#1973]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.10.26

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

I have a csv with the contents

```
foo,bar
10000001,1e-5
10000002,.04
```

When I use `read_csv`, the column `bar` is loaded as a string.

```
shape: (2, 2)
┌──────────┬──────┐
│ foo      ┆ bar  │
│ ---      ┆ ---  │
│ i64      ┆ str  │
╞══════════╪══════╡
│ 10000001 ┆ 1e-5 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 10000002 ┆ .04  │
└──────────┴──────┘
```

I think default csv parsing should include scientific notation and load `bar` as a float.

**Comment by zundertj** [comment]
Note that this does work if you supply `use_pyarrow` is True, but it depends on your full example whether `pyarrow` supports all the options you need.
