### ISSUE TITLE
Confusion about `&` when mixing `cs.by_name` and `pl.col`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#19740]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import polars.selectors as cs

df = pl.DataFrame({
    "a": [1],
    "b": [2]
})

df.select(cs.by_name("a") | pl.col("b"))
# shape: (1, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 1   ┆ 2   │
# └─────┴─────┘

df.select(cs.by_name("a") & pl.col("b"))
# shape: (1, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 1   ┆ 2   │
# └─────┴─────┘
```

### Issue description

I don't understand some behavior of `&` to intersect selectors and expressions. 

In the example above, `cs.by_name("a") | pl.col("b")` returns both columns, which makes sense since both match the condition that they are either "a" or "b". My issue is that `cs.by_name("a") & pl.col("b")` also returns both columns, but IMO it shouldn't since none of the columns is "a" and "b" at the same time. This comes from this `if` condition:

https://github.com/pola-rs/polars/blob/7f0b3e00845c013222ac8b1094d693af582258c2/py-polars/polars/selectors.py#L386-L392

I understand there are some issues with selectors, e.g. https://github.com/pola-rs/polars/issues/13757. Is this also an issue or am I misunderstanding?

### Expected behavior

`df.select(cs.by_name("a") & pl.col("b"))` should return 0 cols.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-6.8.0-47-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by orlp** [comment]
This seems like a bug to me.
