### ISSUE TITLE
Simpler syntax for changing some values of a column

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#1975]
#### Describe your feature request

Perhaps I misunderstand how to use `polars` expression syntax, if so, I would be happy to learn what I'm doing wrong. But from what I gather, there's no concise way of overwriting the values of part of a column.

```
>>> import polars ; df = polars.DataFrame({"a": [1, 2, 1, 1], "b": ["a", "b", "c", "c"], "c": [0, 1, 2, 3]})
>>> df
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 0   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ b   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ c   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ c   ┆ 3   │
└─────┴─────┴─────┘
```

Columns can be replaced wholesale:
```
df['a'] = df['b']
```
But pandas style replacement
```
df[df['c'] == 2, 'a'] = df[df['c'] == 2, 'b']
```
fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1252, in __setitem__
    s[row_selection] = value
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/series.py", line 538, in __setitem__
    self._s = self.set(key, value)._s
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/series.py", line 1998, in set
    return wrap_s(f(filter._s, value))
TypeError: argument 'value': 'DataFrame' object cannot be interpreted as an integer
```
The only way I can get this to work is
```
df = df.with_column(polars.when(df['c'] == 2).then(df['b']).otherwise(df['a']).alias('a'))
```

I'm happy to have a different syntax than pandas, but the current syntax seems longwinded. Two syntax suggestions (I'm not sold on either, feel free to modify):

1) Allow for directly setting a column with an expression. This allows removing the `with_column` and `alias` function calls, and mimics the wholesale column replacement syntax above.
```
df['a'] = polars.when(df['c'] == 2).then(df['b']).otherwise(df['a'])
```
Currently this errors with: 
```
Traceback (most recent call last):
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1220, in __setitem__
    self.replace(key, pli.Series(key, value))
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/series.py", line 212, in __init__
    raise ValueError("Series constructor not called properly.")
ValueError: Series constructor not called properly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1222, in __setitem__
    self.hstack([pli.Series(key, value)], in_place=True)
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/series.py", line 212, in __init__
    raise ValueError("Series constructor not called properly.")
ValueError: Series constructor not called properly.
```

2) Allow calling `when` on a series where the `otherwise` value is just the original series value:
```
df['a'] = df['a'].when(df['c'] == 2).then(df['b'])
 ```
which would be equivalent to
```
df = df.with_column(polars.when(df['c'] == 2).then(df['b']).otherwise(df['a']).alias('a'))
```

Or perhaps something like `df = df.modify('a').when(df['c'] == 2).then(df['b'])`?

Thoughts?

**Comment by ritchie46** [comment]
You should almost never access a column in polars with bracket syntax. `df["foo"]`. Especially never when you are using the expression API, and you should be using the expression API.

To replace a column based on a predicate, one should write:

```python
df.with_column(
    pl.when(pl.col("c") == 2).then(pl.col("c")).otherwise(pl.col("a")).alias("a")
)
```

Sure the, you typed a few more letters. But you can continue with chaining multiple operations, polars is able to compute the 3 given expressions in parallel (the predicate, the true value, the false value).

If you think about the pandas style

```python
df[df['c'] == 2, 'a'] = df[df['c'] == 2, 'b']
```

Pandas has to execute the mask `df['c'] == 2` twice and if you don't want this you have to set a temporal mask value. Polars does not allow for such an API, and thus you type a few more letters, so that we get more context and can optimize.

**Comment by LiterallyUniqueLogin** [comment]
Thanks for the reply!

So, if I'm understanding things correctly - `df['a']` directly retrieves the data in the interpreter thread while as `pl.col('a')` returns a query object that pushes the retrieval (and subsequent computations) off to a worker thread when exectued. So, `df['a']` is what I should use when moving data out of a polars DataFrame to be used elsewhere (e.g. to a graphing library), while `pl.col('a')` should be used inside polars operations. If that's all correct, that wasn't clear to me initially from reading the docs. I'm thinking that information should be put somewhere in the [indexing docs](https://pola-rs.github.io/polars-book/user-guide/indexing.html) perhaps?

On the topic of lazy vs eager - when reading the docs I assumed lazy was useful when I had an incoming stream of data and wanted it processed as it came in, whileas eager was useful when I had all the data at hand which was my current usecase. This seems to be not the case - eager should only really be used when extracting data from polars to another library (e.g. graphing), all polars-internal uses are better served by lazy. Is that a reasonable heuristic, or am I missing something? If that's so, then maybe that could be cleared up right in the [intro](https://pola-rs.github.io/polars-book/user-guide/introduction.html)?

As for column assignment, it's still feels to me cleaner/more pythonic to write assignments as
```
df['foo'] = pl.when(pl.col("c") == 2).then("c").otherwise("a")
```
rather than
```
df = df.with_columns(pl.when(pl.col("c") == 2).then("c").otherwise("a").alias("foo"))
```
This would be a new entry point to the API, but couldn't it work the same? You build a query object on the RHS, then the LHS assignment function has the context needed to execute it, or even store the query and defer execution till the result is needed later, so I don't think this would break the lazy paradigm. The syntax heuristic would then be something like 'indexing only for assignment, not for access'. I guess you'd need to explicitly discourage

Still learning polars, trying to feel out how this works in practice.

**Comment by ritchie46** [comment]
> On the topic of lazy vs eager - when reading the docs I assumed lazy was useful when I had an incoming stream of data and wanted it processed as it came in, whileas eager was useful when I had all the data at hand which was my current usecase. This seems to be not the case - eager should only really be used when extracting data from polars to another library (e.g. graphing), all polars-internal uses are better served by lazy. Is that a reasonable heuristic, or am I missing something? If that's so, then maybe that could be cleared up right in the intro?

Have you read the [lazy API](https://pola-rs.github.io/polars-book/user-guide/optimizations/lazy/intro.html)?


> As for column assignment, it's still feels to me cleaner/more pythonic to write assignments as

Polars wants to have one clear way to do it, and wants to keep functions pure. So don't modify original dataframes. Your suggestion does not fit that API goal. We don't want to clutter the API with 10 possible ways to do it.

> So, if I'm understanding things correctly - df['a'] directly retrieves the data in the interpreter thread while as pl.col('a') returns a query object that pushes the retrieval (and subsequent computations) off to a worker thread when exectued. So, df['a'] is what I should use when moving data out of a polars DataFrame to be used elsewhere (e.g. to a graphing library), while pl.col('a') should be used inside polars operations. If that's all correct, that wasn't clear to me initially from reading the docs. I'm thinking that information should be put somewhere in the indexing docs perhaps?

`df["a"]` returns a `Series` in the `DataFrame`. 

`pl.col("a")` is a reference to a column that can be pushed into an query context. You can think of it as the start of a computation. 

Maybe this video series can clear things up: https://calmcode.io/polars/introduction.html
