### ISSUE TITLE
Small typo in example in polars.map_groups()

### ISSUE THREAD

**Issue by sn0rkmaiden** [pola-rs/polars#19757]
### Description

In the description of example it is said that: 

The output for group `1` can be understood as follows:

*    group 1 contains Series `'a': [1, 3]` and `'b': [4, 5]`

*    applying the function to those lists of Series, one gets the output `[1 / 4 + 5, 3 / 4 + 6]`, i.e. `[5.25, 6.75]`

But correct values for `'b'` list are `[5, 6]` according to data above and the result.

### Link

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.map_groups.html

**Comment by sn0rkmaiden** [comment]
@MarcoGorelli Sure, I've opened a pull request. Could you please check?

**Comment by rodrigogiraoserrao** [comment]
Closed by #19769
