### ISSUE TITLE
polars 1.13.0 filtering by date column doesn't work in lazyframe obtained via scan_parquet

### ISSUE THREAD

**Issue by jkimcubist** [pola-rs/polars#19766]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

df=polars.scan_parquet(path)
df=df.filter(polars.col('DateColumn')>=polars.date(2020,1,1)).collect()

### Issue description

.

### Expected behavior

.

### Installed versions

--------Version info---------
Polars:              1.13.0
Index type:          UInt32
Platform:            Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Python:              3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.3.0
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.30
torch                <not installed>
xlsx2csv             0.8.2
xlsxwriter           3.2.0
None

**Comment by cmdlineluser** [comment]
Are you able to add a reproducible example?

```python
(pl.DataFrame({"DateColumn": ["2020/1/1", "2019/1/23", "2020/2/20"]})
   .with_columns(pl.all().str.to_date())
   .write_parquet("19766.parquet")
)

pl.__version__

(pl.scan_parquet("19766.parquet")
   .filter(pl.col("DateColumn") >= pl.date(2020, 1, 1))
   .collect()
)

# '1.13.0'
# 
# shape: (2, 1)
# ┌────────────┐
# │ DateColumn │
# │ ---        │
# │ date       │
# ╞════════════╡
# │ 2020-01-01 │
# │ 2020-02-20 │
# └────────────┘
```

**Comment by jkimcubist** [comment]
I am having a hard time replicating it through a toy example. I am getting the error with some large parquet file of real data that I am working with…

Scanning and collecting works if I don’t filter by dates before collecting but it fails when I filter by dates before collecting

But the message I am getting is this:

***@***.***

Do you have any clue what can be generating this message

**Comment by jkimcubist** [comment]
I was trying to copy and paste the error message in-line:


***@***.***

**Comment by alexander-beedie** [comment]
@jkimcubist: could you try posting using something other than the email gateway? I tried to clean up the messages a bit, but truthfully they still aren't that readable as all the formatting seems to get garbled (and it is injecting large blocks of boilerplate disclaimer text). Thx 😅

**Comment by jkimcubist** [comment]
Thanks for the suggestion – is this for the collect() function?

**Comment by coastalwhite** [comment]
This is for the `scan_parquet` function.

**Comment by jkimcubist** [comment]
That gives me a different error:

File ~/.conda/envs/JHK-3119/lib/python3.11/site-packages/polars/lazyframe/frame.py:2055, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2053 # Only for testing purposes
   2054 callback = _kwargs.get(\"post_opt_callback\", callback)
-> 2055 return wrap_df(ldf.collect(callback))

ShapeError: unable to vstack, column names don't match: "PointID" and "TradeDate\"
}

**Comment by jkimcubist** [comment]
actually, setting parallel='row_groups'  solved the issue.  How should I interpret this result?

**Comment by jmittelstaedt** [comment]
Hi, I think I'm having a problem similar to the one discussed here. I am using polars version 1.14.0. When trying to do a `scan_parquet` on a hive partitioned data frame where one of the partitioned columns is being filtered on. I've been able to make a small example to reproduce (using Pandas to create the frame)

```
import pandas as pd
import numpy as np
import polars as pl

df_pandas = pd.DataFrame({
    "x": np.random.randint(1, 4, 100),
    "y": np.random.randint(4, 6, 100),
    "sdt": np.random.choice(["H1", "H3"], 100),
    "data1": np.random.rand(100),
    "data2": np.random.rand(100),
})
df_pandas.to_parquet("./testdf", partition_cols=["x", "y"])


pldf = (
    pl.scan_parquet(
        "./testdf",
        hive_partitioning=True,
        hive_schema=pl.Schema(
            {
                "x": pl.Int8(),
                "y": pl.Int8(),
            }
        ),
        parallel="prefiltered"
    )
    .filter(
        pl.col("x") == 2,
        pl.col("y") == 4,
        pl.col("sdt") == "H1",
    )
)

pldf.collect()
```

I get a traceback like the below:
```
thread 'polars-1' panicked at crates/polars-io/src/parquet/read/read_impl.rs:398:58:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'polars-2' panicked at crates/polars-io/src/parquet/read/read_impl.rs:398:58:
index out of bounds: the len is 1 but the index is 2

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[1], line 34
     12 df_pandas.to_parquet("./testdf", partition_cols=["x", "y"])
     15 pldf = (
     16     pl.scan_parquet(
     17         "./testdf",
   (...)
     31     )
     32 )
---> 34 pldf.collect()

File ~/.pyenv/versions/polars-test/lib/python3.9/site-packages/polars/lazyframe/frame.py:2029, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2027 # Only for testing purposes
   2028 callback = _kwargs.get("post_opt_callback", callback)
-> 2029 return wrap_df(ldf.collect(callback))

PanicException: index out of bounds: the len is 1 but the index is 1
```

Interestingly, if I remove the "data2" column from the above example, I get a different error:
```
thread 'polars-0' panicked at crates/polars-io/src/parquet/read/read_impl.rs:359:35:
capacity overflow

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[4], line 34
     12 df_pandas.to_parquet("./testdf", partition_cols=["x", "y"])
     15 pldf = (
     16     pl.scan_parquet(
     17         "./testdf",
   (...)
     31     )
     32 )
---> 34 pldf.collect()

File ~/.pyenv/versions/polars-test/lib/python3.9/site-packages/polars/lazyframe/frame.py:2029, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2027 # Only for testing purposes
   2028 callback = _kwargs.get("post_opt_callback", callback)
-> 2029 return wrap_df(ldf.collect(callback))

PanicException: capacity overflow
```

From what I could understand of the Rust code referenced in the first traceback, I'm thinking that somewhere it is assuming that columns `"x"` and `"y"` should be in the literal parquet file, but they are not since they are partitioned upon and this is leading to an indexing error. I am able to load if I set `predicate_pushdown=False` in the call to `pldf.collect()`, and reading with `read_parquet` succeeds. However in my actual dataset, this leads to much longer loading times since I guess it does not leverage the partitioning when deciding what to load.

**Comment by cmdlineluser** [comment]
@jmittelstaedt I can replicate that panic on 1.14.0

(It also loads for me if I remove `parallel="prefiltered"` which lines up with https://github.com/pola-rs/polars/issues/19766#issuecomment-2476331320)

**Comment by cmdlineluser** [comment]
@jmittelstaedt's https://github.com/pola-rs/polars/issues/19766#issuecomment-2486388259 now gives a ShapeError after the fix.

```
ShapeError: filter's length: 15 differs from that of the series: 16
```

It only seems to happen when pandas is used to create the partitioned dataset.

**Comment by jkimcubist** [comment]
Is this considered resolved?
I am actually still having same issue with version 1.16.0
Error message is different now, though. It says "Cannot v-stack: column names don't match"

**Comment by cmdlineluser** [comment]
Does the error go away if you `.collect(predicate_pushdown=False)`?

There was a repro posted earlier for a a vstack shapeerror:

- https://github.com/pola-rs/polars/issues/19944#issuecomment-2519877545

**Comment by jkimcubist** [comment]
nope.   .collect(predicate_pushdown=False) didn't help. Still same error. Look like this is related to 

https://github.com/pola-rs/polars/issues/20174
