### ISSUE TITLE
Undocumented behavior change of `ChunkedArray::cont_slice()`

### ISSUE THREAD

**Issue by Banyc** [pola-rs/polars#19774]
### Description

The [current docs](https://github.com/pola-rs/polars/blob/420c0d99b210816e89a01c041354d322424e2137/crates/polars-core/src/chunked_array/mod.rs#L856) of `ChunkedArray::cont_slice()` describes the nature of a slice not involving any null values. However, in version `0.44`, it becomes "Returns the values of the array as a contiguous slice only if there exists only one chunk."

The semantics change is undocumented. The docs should hint users to call `ChunkedArray::rechunk()` to satisfy the additional assumption.

**Comment by ritchie46** [comment]
It is a leakage of an internal API. It is defined in Polars-core and not intended to be used publicly. I will close that as we don't have the capacity to document such changes. It is too much work.
