### ISSUE TITLE
Misleading ShapeError error message

### ISSUE THREAD

**Issue by theidecke** [pola-rs/polars#19795]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

```

### Issue description

When trying to create a DataFrame from two series with mismatching length this (rightfully) causes a `ShapeError` exception, whose error message currently reads something like:

```
polars.exceptions.ShapeError: could not create a new DataFrame: series 4321 has length 4321 while series "columnname" has length 4320
```

The issue is, that instead of the name of the first series, the length of the series is returned, but the wording implies that it's the name which is not helpful for debugging the error and can be confusing.

The relevant line in the source code is

https://github.com/pola-rs/polars/blob/5f11dd958947d7880a0c092b3c94a4c630a32f20/crates/polars-core/src/frame/mod.rs#L284

where the surrounding code currently reads:
```rust
        let height = fst.len();
        for col in &columns[1..] {
            polars_ensure!(
                col.len() == height,
                ShapeMismatch: "could not create a new DataFrame: series {:?} has length {} while series {:?} has length {}",
                columns[0].len(), height, col.name(), col.len()
            );
        }
```

My proposal is that instead it should be:
```rust
        let height = fst.len();
        for col in &columns[1..] {
            polars_ensure!(
                col.len() == height,
                ShapeMismatch: "could not create a new DataFrame: series {:?} has length {} while series {:?} has length {}",
                columns[0].name(), height, col.name(), col.len()
            );
        }
```

### Expected behavior

The expected error message should instead read

```
polars.exceptions.ShapeError: could not create a new DataFrame: series "firstcolumnname" has length 4321 while series "columnname" has length 4320
```

### Installed versions

<details>

1.13.1

</details>

**Comment by alexander-beedie** [comment]
@theidecke: Yup, that would be a good improvement - want to add a PR? (Looks like you have one ready in a local branch)
