### ISSUE TITLE
Pandas interoperability: Inconsistencies with lists

### ISSUE THREAD

**Issue by raayu83** [pola-rs/polars#19809]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from io import BytesIO, StringIO

import pandas as pd
import polars as pl

my_json = StringIO('[{ "mylist": ["a", "b", "c"] }]')

df_pl = pl.read_json(my_json).to_pandas()
df_pd = pd.read_json(my_json)

output_pl = BytesIO()
output_pd = BytesIO()

df_pl.to_csv(output_pl)
df_pd.to_csv(output_pd)

print(output_pl.getvalue())
print(output_pd.getvalue())

```

result:
´´´
b",mylist\r\n0,['a' 'b' 'c']\r\n"
b',mylist\r\n0,"[\'a\', \'b\', \'c\']"\r\n'
´´´

### Issue description

This issues can lead to errors if you switch from pandas to polars when you pass data somewhere else using df.to_polars().
df.to_polars() is in a different format than if the df was created by pandas initially.
When calling df.to_csv(), you can see that the comma separating the elements of the list is missing in the polars version.

I'm not 100% sure whether this is a bug or intentional by design.
But switching from pandas to polars would be easier if the output after to_pandas was the same as the original pandas df.

In my case, I had do write some additional logic to replicate the behavior of pandas.

### Expected behavior

df.to_polars() delivers a df identical to what would be produced if you would use pandas all along

### Installed versions

<details>

```
--------Version info---------
Polars:              1.13.1
Index type:          UInt32
Platform:            Windows-10-10.0.22631-SP0
Python:              3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
None
```

</details>

**Comment by cmdlineluser** [comment]
It may be easier to see the difference with `.to_dict()` instead of csv.

```python
my_json = StringIO('[{ "mylist": ["a", "b", "c"] }]')
pl.read_json(my_json).to_pandas().to_dict()

# {'mylist': {0: array(['a', 'b', 'c'], dtype=object)}}
```

```python 
my_json = StringIO('[{ "mylist": ["a", "b", "c"] }]')
pd.read_json(my_json).to_dict()

# {'mylist': {0: ['a', 'b', 'c']}}
```

The difference seems to be that you get a numpy array from `.to_pandas()`

**Comment by ritchie46** [comment]
I don't know if this is a bug. How can you expect us to have the same behavior across libraries. We create a valid pandas DataFrame. 

Is this because they read in as a different string type? (which is dependent of what libraries are available in pandas :/).

**Comment by ritchie46** [comment]
@MarcoGorelli got an opinion here?

**Comment by MarcoGorelli** [comment]
The difference only occurs in the classical pandas case when `'mylist'` is of dtype `object`

In which case, it's not the same dtype as there is in the Polars dataframe

If you use `pd.ArrowDtype(pa.large_list(pa.large_string()))` for the list dtype in pandas, you get the same results:
```python
In [22]: from io import BytesIO, StringIO
    ...:
    ...: import pandas as pd
    ...: import polars as pl
    ...:
    ...: my_json = StringIO('[{ "mylist": ["a", "b", "c"] }]')
    ...:
    ...: df_pl = pl.read_json(my_json).to_pandas()
    ...: df_pd = pd.read_json(my_json).astype({'mylist': pd.ArrowDtype(pa.large_list(pa.large_string()))})
    ...:
    ...: output_pl = BytesIO()
    ...: output_pd = BytesIO()
    ...:
    ...: df_pl.to_csv(output_pl)
    ...: df_pd.to_csv(output_pd)
    ...:
    ...: print(output_pl.getvalue())
    ...: print(output_pd.getvalue())
b",mylist\n0,['a' 'b' 'c']\n"
b",mylist\n0,['a' 'b' 'c']\n"
```

**Comment by MarcoGorelli** [comment]
going to go ahead and close this - thanks for the report, please do report any other issues you encounter!

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/18591#issuecomment-2336594359

> We don't allow you to put `Object` in our Polars structures (`List`, `Struct`)

(The PanicException could be replaced with a proper error.)
