### ISSUE TITLE
Rolling Expr claims to support timedelta but doesn't appear to

### ISSUE THREAD

**Issue by CatchemAL** [pola-rs/polars#19825]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    def rolling_std(
        self,
        window_size: int | timedelta,
        weights: list[float] | None = None,
        *,
        min_periods: int | None = None,
        center: bool = False,
        ddof: int = 1,
    ) -> Expr:
```

I'm aware that there are expressions such as `rolling_std_by` but many of the standard rolling expressions have type annotations suggesting they also support timedelta. Assuming they shouldn't, the following functions have type annotations that need correcting:

- `Expr.rolling_sum` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L7660)]
- `Expr.rolling_std` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L7771)]
- `Expr.rolling_var` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L7886)]
- `Expr.rolling_median` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L8001)]
- `Expr.rolling_quantile` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L8114)]
- `Expr.rolling_sum` [[src](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L7660)]

### Issue description

Type annotations appear to support timedelta but I am not convinced they do

### Expected behavior

Probably just remove timedelta from annotations.

### Installed versions

<details>

--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-6.10.11-linuxkit-aarch64-with-glibc2.31
Python:              3.12.7 (main, Oct  2 2024, 00:14:14) [GCC 10.2.1 20210110]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.5.1
xlsx2csv             <not installed>
xlsxwriter           <not installed>

</details>

**Comment by MarcoGorelli** [comment]
thanks @CatchemAL , I probably forgot to remove these when splitting things out into the `_by` variants
