### ISSUE TITLE
Suggestion - make in_place keyword-only?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#1984]
First, `polars` is seriously awesome - well done!!

One thing I really like is that you have a `py.typed` file, so types are available to users.

However, the return annotations aren't always as precise as they could be, e.g.:
```python
import polars as pl

df1: pl.DataFrame
df2: pl.DataFrame

reveal_type(df1.vstack(df2))
reveal_type(df1.vstack(df2, in_place=True))
```

If I run this, I get
```
t.py:6: note: Revealed type is "Union[polars.internals.frame.DataFrame, None]"
t.py:7: note: Revealed type is "Union[polars.internals.frame.DataFrame, None]"
```

This could be solved by using `typing.overload`.

**However**, if you have default arguments which precede the one to overload, then you need exponentially many overloads.

In pandas (where changing the API now has to be a slow process!), this has been a nightmare, resulting in constructs like

https://github.com/pandas-dev/pandas/blob/aee6b7ab8a2922606872de083f458d1646dab547/pandas/core/frame.py#L5093-L5206

So, if you'd like to overload return types, I'd strongly suggest making `in_place` (and any other keyword which changes the return type) to be keyword-only while `polars` is still young and the API can change rapidly

---

ps. just started sponsoring you, as I really want `polars` to succeed!

**Comment by MarcoGorelli** [comment]
Likewise, `to_json` would be pretty hard to overload as-is, as the return type depends on the third default argument

**Comment by zundertj** [comment]
I agree on type annotations not being completely finished yet, and we have been adding `@overload` in a couple of places already. Any examples of these are welcome.

On `in_place` specifically, we have in a couple of places broken with the Python convention of returning `None` when an op is in-place and return the object itself instead, in order to support chaining of methods, for example `DataFrame.sort` (PR that changed that is here, refers in the comments to a previous discussion, cant find that: https://github.com/pola-rs/polars/pull/1821)  I'm not yet convinced that is a valid use-case, and we should make, whatever we end up doing, a consistent choice across the Python API.

**Comment by ritchie46** [comment]
> First, polars is seriously awesome - well done!!

Thanks! We are getting there! :)

Could you help me explain a bit why changing it to key-word only fixes this? I am no expert on python typing. Would we still need an overload, but not so many?

I agree with @zundertj  that we need something consistent. But there is still time to make changes. TBH, I don't care much about `in_place` and if it has to go, its also fine. 

If polars only supports pure functions, its something you can rely on.

**Comment by MarcoGorelli** [comment]
> Would we still need an overload, but not so many?

Yes, exactly, just 3:
- when `in_place` is `Literal[False]`, the return type would be `DataFrame`
- when `in_place` is `Literal[True]`, the return type would be `None`
- when `in_place` is `bool`, the return type would be `Optional[DataFrame]`

I find it surprising that `mypy` doesn't infer the third one automatically from the top two, but that's the way it is.

> Could you help me explain a bit why changing it to key-word only fixes this?

I made a little blogpost on this if you're interested https://medium.com/analytics-vidhya/making-sense-of-typing-overload-437e6deecade

> TBH, I don't care much about in_place and if it has to go, its also fine.

Is there a benefit to using `in_place`, or that it potentially being less to type? If there's no benefit beyond syntax, it might be simpler to let it go?

**Comment by ritchie46** [comment]
Thanks for the post that cleared overloading up for me!

#1997 fixes the types for `vstack`. I still don't understand the difference if I changed the API to `vstack(self, df, *, in_place)`

**Comment by MarcoGorelli** [comment]
For `vstack`, it makes no difference, and `in_place` is the only default argument. It would make a difference if there were default arguments before `in_place`

Somewhere where it would make a difference, if with `in_place` the return type were `None`, would be `sort`, because it has a default argument (`reverse`) which precedes it

**Comment by ritchie46** [comment]
Ok, final question. ;) Could you show me the overload for `DataFrame.sort` with keyword only arguments?

I tried this:

```python
    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]],
        *,
        in_place: Literal[False] = ...,
    ) -> "DataFrame":
        ...

    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]],
        *,
        in_place: Literal[True],
    ) -> None:
        ...

    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]],
        *,
        in_place: bool,
    ) -> Optional["DataFrame"]:
        ...
```

But mypy is not happy.

```python
import polars as pl

df = pl.DataFrame

reveal_type(df.sort(by="a", reverse=False, in_place=True))
```

```
foo.py:4: error: No overload variant of "sort" of "DataFrame" matches argument types "str", "bool", "bool"
foo.py:4: note: Possible overload variants:
foo.py:4: note:     def sort(self, self: DataFrame, by: Union[str, Expr, List[str], List[Expr]], reverse: Union[bool, List[bool]], *, in_place: Literal[False] = ...) -> DataFrame
foo.py:4: note:     def sort(self, self: DataFrame, by: Union[str, Expr, List[str], List[Expr]], reverse: Union[bool, List[bool]], *, in_place: Literal[True]) -> None
foo.py:4: note:     def sort(self, self: DataFrame, by: Union[str, Expr, List[str], List[Expr]], reverse: Union[bool, List[bool]], *, in_place: bool) -> Optional[DataFrame]
foo.py:4: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by MarcoGorelli** [comment]
The following works for me, you just need to tell `mypy` that `reverse` takes defaults
```python
    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]] = ...,
        *,
        in_place: Literal[False] = ...,
    ) -> "DataFrame":
        ...

    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]] = ...,
        *,
        in_place: Literal[True],
    ) -> None:
        ...

    @tp.overload
    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]] = ...,
        *,
        in_place: bool,
    ) -> Optional["DataFrame"]:
        ...

    def sort(
        self,
        by: Union[str, "pli.Expr", tp.List[str], tp.List["pli.Expr"]],
        reverse: Union[bool, tp.List[bool]] = False,
        *,
        in_place: bool = False,
    ) -> Optional["DataFrame"]:
```

```python
import polars as pl

df: pl.DataFrame
in_place: bool

reveal_type(df.sort('foo', in_place=False))
reveal_type(df.sort('foo', in_place=True))
reveal_type(df.sort('foo', in_place=in_place))
reveal_type(df.sort(by="a", reverse=False, in_place=True))
```

```console
$ mypy t.py                    
t.py:6: note: Revealed type is "polars.internals.frame.DataFrame"
t.py:7: note: Revealed type is "None"
t.py:8: note: Revealed type is "Union[polars.internals.frame.DataFrame, None]"
t.py:9: note: Revealed type is "None"
```

---

> Ok, final question. ;)

😄  please do ask more if you do have questions, happy to help out with your awesome project!
