### ISSUE TITLE
Option to not group on nulls when using `.over()`

### ISSUE THREAD

**Issue by aerjayc** [pola-rs/polars#1985]
#### Describe your feature request

If we do an operation over a column with `null`-groups like:
```python
import polars as pl

df = pl.DataFrame({'group': [1, 1, None, None], 'value': [1.0, 2.0, 3.0, 4.0]})
shape: (4, 2)
┌───────┬───────┐
│ group ┆ value │
│ ---   ┆ ---   │
│ i64   ┆ f64   │
╞═══════╪═══════╡
│ 1     ┆ 1     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1     ┆ 2     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ null  ┆ 3     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ null  ┆ 4     │
└───────┴───────┘
```
If we take the mean of the `'value'` column over `'group'`, we get:
```python
df.with_column(pl.col('value').mean().over('group').suffix('_mean'))

shape: (4, 3)
┌───────┬───────┬────────────┐
│ group ┆ value ┆ value_mean │
│ ---   ┆ ---   ┆ ---        │
│ i64   ┆ f64   ┆ f64        │
╞═══════╪═══════╪════════════╡
│ 1     ┆ 1     ┆ 1.5        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 2     ┆ 1.5        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 3     ┆ 3.5        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 4     ┆ 3.5        │
└───────┴───────┴────────────┘
```
But sometimes, we may not want to group all those null groups together -- instead, we might want to consider them as having no groups (instead of having a single group with value `null`). So one suggestion is to have a keyword argument for treating `null` groups as non-groups:
```python
df.with_column(pl.col('value').mean().over('group', group_nulls=False))

shape: (4, 3)
┌───────┬───────┬────────────┐
│ group ┆ value ┆ value_mean │
│ ---   ┆ ---   ┆ ---        │
│ i64   ┆ f64   ┆ f64        │
╞═══════╪═══════╪════════════╡
│ 1     ┆ 1     ┆ 1.5        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 2     ┆ 1.5        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 3     ┆ 3          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 4     ┆ 4          │
└───────┴───────┴────────────┘
```
Then for standard deviation, we should have:
```python
df.with_column(pl.col('value').std().over('group').suffix('_std', group_nulls=False))

shape: (4, 3)
┌───────┬───────┬────────────────────┐
│ group ┆ value ┆ value_std          │
│ ---   ┆ ---   ┆ ---                │
│ i64   ┆ f64   ┆ f64                │
╞═══════╪═══════╪════════════════════╡
│ 1     ┆ 1     ┆ 0.7071067811865476 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 2     ┆ 0.7071067811865476 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 3     ┆ NaN                │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 4     ┆ NaN                │
└───────┴───────┴────────────────────┘
```

**Comment by zundertj** [comment]
Just a thought: if the group is undefined (`null`), one could also argue the value returned should also be `null`? I.e. there might be more than two types of behavior possible here.

**Comment by ritchie46** [comment]
This would require a whole rewriting of the grouping algorithm. Which I don't want to do for multiple reasons.

Most implementations consider null as a separate group, (only pandas and dask do not, which is considered a bug: 

https://github.com/pandas-dev/pandas/issues/36327
https://github.com/h2oai/db-benchmark/issues/171
)

If you want different behavior for nulls, you can either drop nulls (this leaves you with the pandas solution), or replace nulls with unique values, or join on multiple columns. You get the idea.
