### ISSUE TITLE
Return Dataframe.dtypes as a dict

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#1988]
#### DataFrame.dtypes as a dict, not list
Currently:
```python
>>> import polars as pl
>>> df = pl.DataFrame({"a":[ 1, 2],
                       "b": ["hello", "world"],
                       "c": [1.1, None]})
>>> df.dtypes
[<class 'polars.datatypes.Int64'>, <class 'polars.datatypes.Utf8'>, <class 'polars.datatypes.Float64'>]
```
which is inconvenient when there are many columns to check that all columns have the expected dtype. It is also inconsistent with `DataFrame.describe`, which does return column labels.

For comparison, Pandas:
```python
>>> import pandas as pd
>>> df = pd.DataFrame({"a":[ 1, 2],
                  "b": ["hello", "world"],
                  "c": [1.1, pd.NA]})
>>> df.dtypes
a     int64
b    object
c    object
dtype: object
```

Happy to implement this myself if you agree.

**Comment by ritchie46** [comment]
To keep this consistent with what we do in Rust, I'd like the idea of this, but then under the function name `def schema() -> Dict[str, DataType]`.
