### ISSUE TITLE
Outerjoin hstack error

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#1990]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.10.26

#### What operating system are you using polars on?

Windows 10

#### Describe your bug.

A dataframe outerjoin results in a duplicate column name error

#### What are the steps to reproduce the behavior?

Apologies, I only hit this on a large proprietary dataset, which I cant share. I have been trying to create a small example, but there it does not crop up, so I understand this does not have priority. I still hope that this bug report helps, maybe the error rings a bell, or someone else hits it on a small reproducible example?

```python
import polars as pl

df1 = pl.DataFrame({"a": [1, 2, 3],
                    "b": ["hello", "polars", "world"],
                    "c": [4, 5, 6]})


df2 = pl.DataFrame({"a": [1, 2, 4],
                    "b": ["hello", "polars", "world"],
                    "d": [100, 200, 300]})

df3 = df1.join(df2, on=["a", "b"], how="outer")

```
Works as expected on the small example, but gives the following on the large example:

```
File "...\venv\lib\site-packages\polars\internals\frame.py", line 2326, in join
    return wrap_df(self._df.join(df._df, left_on_, right_on_, how, suffix))
RuntimeError: Any(Duplicate("Cannot do hstack operation. Column with name: a already exists"))
```

I have tried to force it down the lazy path by calling `df3 = df1.join(df2, on=[pl.col("a"), pl.col("b")], how="outer")`, but that gives the same error. When I do a left join, it works.

**Comment by ritchie46** [comment]
Have you been able to reproduce this with a arbitrary generated dataset that meets the expected size?

**Comment by zundertj** [comment]
Apologies, I see now the issue is created before (bit hard to see when there are dozens of columns) as I renamed a column that causes duplicate column names. I.e. in the example:

```python
import polars as pl

df1 = pl.DataFrame({"a": [1, 2, 3],
                    "b": ["hello", "polars", "world"],
                    "c": [4, 5, 6]})
df1["d"] = [1,2,3]
df1 = df1.rename({"d": "a"})

df2 = pl.DataFrame({"a": [1, 2, 4],
                    "b": ["hello", "polars", "world"],
                    "d": [100, 200, 300]})

df3 = df1.join(df2, on=["a", "b"], how="outer")

```

As `df1` is now:
```
shape: (3, 4)
┌─────┬────────┬─────┬─────┐
│ a   ┆ b      ┆ c   ┆ a   │
│ --- ┆ ---    ┆ --- ┆ --- │
│ i64 ┆ str    ┆ i64 ┆ i64 │
╞═════╪════════╪═════╪═════╡
│ 1   ┆ hello  ┆ 4   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ polars ┆ 5   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ world  ┆ 6   ┆ 3   │
└─────┴────────┴─────┴─────┘
```

I did the rename by directly modifying `DataFrame.columns`, but I see the same is allowed with `DataFrame.rename()`. Should that be blocked, as this is an issue in many places I can imagine. For instance, what would `pl.col("a")` mean on `df1`?

**Comment by ritchie46** [comment]
Yes.. a DataFrame with duplicate column names should not exist. Its an implementation error. We should throw an error on the moment its created.

**Comment by zundertj** [comment]
Is this something that should be checked on the Python side, or Rust? If the first, I can have a go at it.

**Comment by ritchie46** [comment]
On the Rust side. If you can find ways you can break this invariant and list them here, I will make sure they will be fixed.  

One was overwriting the column names?

**Comment by zundertj** [comment]
The two ways I have found so far to break it:

```python
import polars as pl

# 1. set columns
df = pl.DataFrame({"a": [1, 2],
                   "b": [3, 4]})
df.columns = ["a", "a"]
assert df.columns == ["a", "a"]

# 2. rename
df = pl.DataFrame({"a": [1, 2],
                   "b": [3, 4]})
df = df.rename({"b": "a"})
assert df.columns == ["a", "a"]
```

**Comment by ritchie46** [comment]
> The two ways I have found so far to break it:
> 
> ```python
> import polars as pl
> 
> # 1. set columns
> df = pl.DataFrame({"a": [1, 2],
>                    "b": [3, 4]})
> df.columns = ["a", "a"]
> assert df.columns == ["a", "a"]
> 
> # 2. rename
> df = pl.DataFrame({"a": [1, 2],
>                    "b": [3, 4]})
> df = df.rename({"b": "a"})
> assert df.columns == ["a", "a"]
> ```

Great.. will fix those.
