### ISSUE TITLE
rolling is super slow on large dataset if not grouped first

### ISSUE THREAD

**Issue by EtienneT** [pola-rs/polars#19912]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime
import string
import numpy as np

np.random.seed(32)

times = pl.DataFrame({
    "time": pl.datetime_range(start=datetime(2023, 1, 1), end=datetime(2023,12,31,23), interval='1h', eager=True)
})

def generate_words(n=2000):
    letters = np.array(list(string.ascii_lowercase))
    words = np.random.choice(letters, (n, 10))  # Generate an (n x 10) array of random letters
    return np.char.array(words).ravel().view('U10')  # Combine each row into a single 10-letter word

nodes = pl.DataFrame({
    "node": generate_words(2000)
})

df = times.join(nodes, how="cross").sort("time")
df = df.with_columns(
    date = df["time"].dt.date(),
    hour = df["time"].dt.hour(),
    price = np.random.uniform(10, 100, len(df)),
).sort("date")

result = (
    df.rolling("date", period="30d")
    .agg(
        pl.col("price").mean(),
    )
)
```

### Issue description

Running the code above in the reproducible example, the rolling takes forever to run (after a couple minutes I killed it).

The initial df looks like this and has approximately 17 million rows:
|    | time                | node   | date                |   hour |   price |
|---:|:--------------------|:-------|:--------------------|-------:|--------:|
|  0 | 2023-01-01 00:00:00 | xlf    | 2023-01-01 |      0 | 16.3943 |
|  1 | 2023-01-01 00:00:00 | wyt    | 2023-01-01 |      0 | 66.2308 |
|  2 | 2023-01-01 00:00:00 | hzd    | 2023-01-01 |      0 | 82.1036 |
|  3 | 2023-01-01 00:00:00 | fkj    | 2023-01-01 |      0 | 69.5557 |
|  4 | 2023-01-01 00:00:00 | elr    | 2023-01-01 |      0 | 34.8895 |

I want the rolling average of the price over the past 30 days, ideally I would want other metrics like std, min, max etc.

As a work around, I did the following code which gives me what I want, but this is not ideal:

```
result = (
    df
    .rolling("date", period="30d", group_by=["node", "hour"])
    .agg(
        pl.col("price").sum(),
        pl.len().alias("count")
    )
    .group_by("date")
    .agg(
        price_mean = pl.col("price").sum() / pl.col("count").sum()
    )
    .sort("date")
)
```

It would be much more convenient to do:
```
result = (
    df.rolling("date", period="30d")
    .agg(
        price_mean = pl.col("price").mean(),
    )
)
```

### Expected behavior

This code:

```
result = (
    df.rolling("date", period="30d")
    .agg(
        price_mean = pl.col("price").mean(),
    )
)
```

should be as fast as:

```
result = (
    df
    .rolling("date", period="30d", group_by=["node", "hour"])
    .agg(
        pl.col("price").sum(),
        pl.len().alias("count")
    )
    .group_by("date")
    .agg(
        price_mean = pl.col("price").sum() / pl.col("count").sum()
    )
    .sort("date")
)
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.14.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.7 (main, Oct 16 2024, 00:21:24) [MSC v.1929 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by EtienneT** [comment]
Even this code returns in 5s and loops in python:

```
from datetime import timedelta

periods = [(x - timedelta(days=30), x) for x in pl.date_range(start=datetime(2023,1,1), end=datetime(2023, 12, 31), eager=True)]
dfs = [df.filter(pl.col('date').is_between(start, end)) for (start, end) in periods]

for i, d in enumerate(dfs):
    dfs[i] = (
        d.select(
            price_mean = pl.col('price').mean(),
            price_std = pl.col('price').std()
        )
    )

result2 = pl.concat(dfs)
result2
```

**Comment by EtienneT** [comment]
Just to make this issue clearer, I want one row per date in the date range (the result should be 365 rows in this example since we are doing a year) where each row calculate their statistics using the data from the last 30 days from the current date in the row.

|    | date                |   price_rolling_mean_last_30d |
|---:|:--------------------|--------:|
|  0 | 2023-01-01 00:00:00 | 2642.16 |
|  1 | 2023-01-02 00:00:00 | 2700.55 |
|  2 | 2023-01-03 00:00:00 | 2707.23 |
|  3 | 2023-01-04 00:00:00 | 2698.84 |
|  4 | 2023-01-05 00:00:00 | 2742.87 |

Testing rolling on a smaller dataset, it seems to return one row for each row in the initial dataset.  I thought we were aggregating since we are using agg.

This generate one row for each row initially in the dataset:
```
(
    df.rolling("date", period="30d")
    .agg(
        pl.col("price").mean(),
    )
)
```

So I thought I could just group_by("date") and just take the first from the group:
```
(
    df.rolling("date", period="30d")
    .agg(
        pl.col("price").mean(),
    )
    .group_by("date")
    .agg(
        pl.all().first()
    )
)
```
But this is also taking forever.

**Comment by ritchie46** [comment]
Fix coming up.
