### ISSUE TITLE
Lazy dataframe join with categorical data example fails

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#1993]
Reported by https://stackoverflow.com/questions/70234041/polars-categorical-feature-and-lazy-api-doesnt-work-like-expected

#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.10.26

#### What operating system are you using polars on?

Windows 10

#### Describe your bug.

The example https://pola-rs.github.io/polars-book/user-guide/performance/strings.html#lazy-join-multiple-dataframes-on-categorical-data at the bottom does not work as described. I.e., trying to collect the join fails. Full code:

```python
import polars as pl

df1 = pl.DataFrame({"a": ["foo", "bar", "ham"], "b": [1, 2, 3]}).lazy()
df2 = pl.DataFrame({"a": ["foo", "spam", "eggs"], "c": [3, 2, 2]}).lazy()

df1 = df1.with_column(pl.col("a").cast(pl.Categorical))
df2 = df2.with_column(pl.col("a").cast(pl.Categorical))

df3 = df1.join(df2, on="a", how="inner").collect()
print(df3)
```

Error message:
```
RuntimeError: Any(ValueError("joins on categorical dtypes can only happen if they are created under the same global string cache")
```

**Comment by ritchie46** [comment]
Thanks. I will react, this is not a bug. The error message gives the answer.
