### ISSUE TITLE
POLARS_SKIP_CPU_CHECK doesn't prevent illegal hardware instruction even with bare import anymore

### ISSUE THREAD

**Issue by mishamsk** [pola-rs/polars#19936]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```shell
admin@alchemist-vm-direct-python311 test-pytest % uv venv
Using CPython 3.11.10 interpreter at: /Users/admin/.asdf/installs/python/3.11.10/bin/python
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
admin@alchemist-vm-direct-python311 test-pytest % uv pip install polars
Resolved 1 package in 6ms
Installed 1 package in 8ms
 + polars==1.14.0
admin@alchemist-vm-direct-python311 test-pytest % source .venv/bin/activate     
(test-pytest) admin@alchemist-vm-direct-python311 test-pytest % export POLARS_SKIP_CPU_CHECK=1
(test-pytest) admin@alchemist-vm-direct-python311 test-pytest % export POLARS_VERBOSE=1
(test-pytest) admin@alchemist-vm-direct-python311 test-pytest % python -c "import polars"     
zsh: illegal hardware instruction  python -c "import polars"
(test-pytest) admin@alchemist-vm-direct-python311 test-pytest % 
```

### Log output

```shell
zsh: illegal hardware instruction  python -c "import polars"
```

### Issue description

We've recently upgraded from 0.20.21 to 1.12.0 and hit a regression. We are using a pretty old machine for our macos runner to build our app, which doesn't have AVX instruction, hence wouldn't pass the cpu check.

However, the app is built to be run on modern CPU's, so it was never an issue. Runner would never fail, since non of the test really hit anything that would trigger a runtime issue with instructions. So we were all good.

Now, polars seems to do something very early during import that causes an error. And setting `POLARS_SKIP_CPU_CHECK ` doesn't really help. It would only silence the warning in `_cpu_check.py`, but some code does something that would trigger a failure just from import...

Unfortunately, we can't use polars-lts-cpu, since whatever is on the runner gets bundled into the app, and I wouldn't want the lts version ending up on all Macs. 

I do understand that upgrading the runner is one solution, but was wondering if this should now be considered an expected behavior that even bare import immediately triggers illegal instruction error?

### Expected behavior

Polars doesn't try to execute some cpu-feature-dependant code just to be imported.

### Installed versions

<details>

Can't show via pl, command, but here is the closest I can get manually:
```
Package Version
------- -------
polars  1.14.0

macosx-12.6-x86_64
```

</details>

**Comment by ritchie46** [comment]
You are probably running under rosetta which emulates a very old CPU instruction set and doesn't support the instruction set Polars compiles to. Either use `polars-lts-cpu` or don't run under rosetta.

See: https://github.com/pola-rs/polars/issues/12454

**Comment by ritchie46** [comment]
> Now, just importing polars immediately runs something that causes the failure. So I am just asking if this is intended to be so or something creeped in during import accidentally? If the current behavior is as intended feel free to just close the issue.

Intended is a big word. The import fails because Polars runs some start up instructions which are not supported by that very old CPU and does you get the illegal instruction abort. The only thing we can do sometimes is detect that before importing the binary and give a nicer error. Either way, you need `polars-lts-cpu` to run on that machine.

Hopefully we can gracefully handle that in the future by installing both and picking lts if the default is not supported.

**Comment by mishamsk** [comment]
thanks for the context, really appreciate you taking the time to dive into this! And thanks a lot for all the great work. Big fan/advocate of polars!

Will close the issue now.

**Comment by mschilli87** [comment]
I just want to report that I hit this installing the latest `polars` via `conda-forge` under Debian running on bare metal. It is an older machine, admittedly, with four 16-core AMD Opteron 6386 SEs. It took me a while to figure out why a pipeline that worked fine on other hardware died when re-creating the 'same' conda environment. Replacing `polars` by `polars-lts-cpu` fixed the issue but I'd still consider it a bug if a package builds fine without any complaint and dies runtime. Should I create a new bug or just consider this out-of-scope and move on with my life? 😉
