### ISSUE TITLE
Can we create a .collect method for polars.DataFrame?

### ISSUE THREAD

**Issue by phucb2** [pola-rs/polars#19995]
### Description

Currently, polars.DataFrame and polars.LazyFrame have few different methods implementation for example .collect() Is it possible to make this method to easier switching between lazy and eager mode

**Comment by cmdlineluser** [comment]
Relevant: https://github.com/pola-rs/polars/issues/7882#issuecomment-1616683055

**Comment by nameexhaustion** [comment]
Duplicate of https://github.com/pola-rs/polars/issues/19548
