### ISSUE TITLE
Access to polars DataFrame columns is slow?

### ISSUE THREAD

**Issue by alonme** [pola-rs/polars#20018]
### Description

It seems like accessing a column in a polars DF is pretty slow?
I compared pandas vs polars vs polars but instead of accessing the df i turned it into a dict and used that

```python
import random
import timeit

import pandas as pd
import polars as pl

# Create a DataFrame with 50,000 columns and 1 row
num_cols = 50_000
data = {f"col_{i}": [random.random()] for i in range(num_cols)}

pd_df = pd.DataFrame(data)
pl_df = pl.DataFrame(data)


# Method 1: Using Pandas
def pandas_benchmark():
    result = []
    for col in pd_df.columns:
        result.append(pd_df[col][0])
    return result


# Method 2: Using Polars directly
def polars_benchmark():
    result = []
    for col in pl_df.columns:
        result.append(pl_df[col][0, 0])  # Access first row, first column
    return result


# Method 3: Using Polars with a dict conversion
def polars_dict_benchmark():
    df_dict = pl_df.to_dict(as_series=False)
    result = []
    for col in df_dict:
        result.append(df_dict[col][0])  # Access first value of the list
    return result


# Benchmark the methods
def benchmark():
    pandas_time = timeit.timeit(pandas_benchmark, number=1)
    polars_time = timeit.timeit(polars_benchmark, number=1)
    polars_dict_time = timeit.timeit(polars_dict_benchmark, number=1)

    print(f"Pandas time: {pandas_time:.4f} seconds")
    print(f"Polars time: {polars_time:.4f} seconds")
    print(f"Polars (dict) time: {polars_dict_time:.4f} seconds")


if __name__ == "__main__":
    benchmark()
 ```
 
 Results (polars-lts-cpu on my machine)
 ```
 Pandas time: 0.5997 seconds
Polars time: 9.0280 seconds
Polars (dict) time: 0.0561 seconds
 ```
 
 I tried removing the access to the actual value in the column, but that didn't change much.
 
 

 If you agree that this can be improved - I would like to try and tackle this

**Comment by cmdlineluser** [comment]
Iterating over the actual columns gave me the fastest results.

```python
for col in pl_df: # pl_df.iter_columns()
    col[0]
```

It seems `pl_df[col]` ends up calling `.get_column()` in this case.

https://github.com/pola-rs/polars/blob/85d078c066860e012f5e7e611558e6382b811b82/py-polars/polars/_utils/getitem.py#L163

Interestingly, going through `pl_df.select()` instead took ~630 seconds.

**Comment by coastalwhite** [comment]
> Interestingly, going through `pl_df.select()` instead took ~630 seconds.

Select basically creates a schema every time it is called. That is why it is so slow.

**Comment by alonme** [comment]
Love the velocity of this project!
Thanks @ritchie46 @coastalwhite
