### ISSUE TITLE
.pivot ignores seperator

### ISSUE THREAD

**Issue by alexschumann** [pola-rs/polars#20020]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "name": ["Cady", "Cady", "Karen", "Karen"],
        "subject": ["maths", "physics", "maths", "physics"],
        "test_1": [98, 99, 61, 58],
        "test_2": [100, 100, 60, 60],
    }
)

df.pivot(on=["name", "subject"], index=["name"], values="test_1", separator="_")
```

### Log output

```shell
no exception is raised
```

### Issue description

Names of the created columns of the pivoted dataframe are independent of argument 'separator' and always take the form
```
'{"Cady","maths"}', '{"Cady","physics"}', '{"Karen","maths"}', '{"Karen","physics"}'
```

### Expected behavior

Column names should be values of the pivoted cols seperated by ```separator```
e.g. with ```separator = "_" ```:
```
'Cady_maths', 'Cady_physics', 'Karen_maths', 'Karen_physics'
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            Windows-11-10.0.26100-SP0
Python:              3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
LTS CPU:             False
(none of optional dependencies installed)
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report -  separator is:

>     Used as separator/delimiter in generated column names in case of multiple values columns.

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

you passed a single column to `values`

check the examples with multiple columns in `values`

closing then
