### ISSUE TITLE
`Series.hist` with `bin_count` produces wrong result if all values are the same

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#20030]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series([1, 1]).hist(bin_count=2)
```

```console
shape: (2, 3)
┌────────────┬────────────┬───────┐
│ breakpoint ┆ category   ┆ count │
│ ---        ┆ ---        ┆ ---   │
│ f64        ┆ cat        ┆ u32   │
╞════════════╪════════════╪═══════╡
│ 1.0        ┆ (1.0, 1.0] ┆ 2     │
│ 1.0        ┆ (1.0, 1.0] ┆ 0     │
└────────────┴────────────┴───────┘
```

### Issue description

The output is incorrect.

This also causes a flaky failure of `tests/unit/operations/test_hist.py::test_hist_rand`.

### Expected behavior

Correct output.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by mcrumiller** [comment]
Thanks @coastalwhite, I updated `hist` recently so this is my fault. This is a quick fix.
