### ISSUE TITLE
WHY CANT I DELETE THIS ISSUE?

### ISSUE THREAD

**Issue by rluvaton-flarion** [pola-rs/polars#20057]
why can't i delete this issue

**Comment by cmdlineluser** [comment]
https://github.com/pola-rs/polars/issues/6360#issuecomment-1399424605

> This is as expected we only broadcast to the result selection.

You can repeat by `pl.len()` 

```python
>>> df.select(pl.lit(1).repeat_by(pl.len()).flatten())
shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 1       │
│ 1       │
│ 1       │
└─────────┘
```
