### ISSUE TITLE
Rolling statistics over fixed time window for groups

### ISSUE THREAD

**Issue by yadamonk** [pola-rs/polars#2006]
In pandas [rolling](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html) statistics can be computed over a fixed time window given a datetimelike index. This is useful for time-series data with missing observations and even works on groups.

```python
import pandas as pd

df = pd.DataFrame(
    {
        'id': ['4ce8', '4ce8', '4ce8'],
        'date': ['2020-01-01', '2020-01-10', '2020-01-11'],
        'value': [1, 1, 1],
    }
)

df.set_index('date', drop=True, inplace=True)
df.index = pd.to_datetime(df.index)

df.groupby('id')['value'].rolling('2d', min_periods=1, closed='right').sum()
```
I'm aware that [#1637](https://github.com/pola-rs/polars/pull/1637) introduced upsampling but it seems expensive to apply a custom function to every single group.

**Comment by ritchie46** [comment]
We have to think how this would fit in the polars API. 

To help you, here is a solution for your problem:

```python
df = pl.DataFrame(
    {
        'id': ['4ce8', '4ce8', '4ce8'],
        'date': ['2020-01-01', '2020-01-10', '2020-01-11'],
        'value': [1, 1, 1],
    }
).with_column(pl.col("date").str.strptime(pl.Date))

def rolling_sum_ndays(df: pl.DataFrame, n: int, date_col: str, value_col: str) -> pl.DataFrame:
    interval = pl.DataFrame({
        date_col: pl.date_range(df[date_col].dt[0], df[date_col].dt[-1], timedelta(days=1)).cast(pl.Date)
    })

    return (interval.join(df, how="left", on=date_col)
         .with_column(pl.col(value_col).fill_null(0).rolling_sum(2, min_periods=1))
         .drop_nulls()
    )


df.pipe(rolling_sum_ndays, n=2, date_col="date", value_col="value")

```

```
shape: (3, 3)
┌────────────┬──────┬───────┐
│ date       ┆ id   ┆ value │
│ ---        ┆ ---  ┆ ---   │
│ date       ┆ str  ┆ i64   │
╞════════════╪══════╪═══════╡
│ 2020-01-01 ┆ 4ce8 ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2020-01-10 ┆ 4ce8 ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2020-01-11 ┆ 4ce8 ┆ 2     │
└────────────┴──────┴───────┘

```

**Comment by yadamonk** [comment]
Thanks for your fast reply. How could we apply your custom function on groups?

**Comment by ritchie46** [comment]
Right.. Then I think you have to upsample your dataframe first and use rolling_window in the groupby context.

**Comment by yadamonk** [comment]
We would need to do the upsampling for each `id` which is why I initially thought about doing it in the groupby context. However this can quickly become expensive.

Is there an efficient way to run a function on the entire groupby object or would we need to resort to string concatenation of `date` and `value` to have a single column to run the aggregation on?

**Comment by ritchie46** [comment]
Hmm... We have to think about such an implementation. The feature you request is a variable window depending on the data. We currently have only fixed windows, so you need to upsample your data to get the same result.

**Comment by ritchie46** [comment]
I am curious how other dataframe libraries have implemented such functionality. I am not entirely convinced on the intuition of dynamic windows, but I understand it can be powerful.

@markfairbanks, does such a thing exists in dplyr?

**Comment by ritchie46** [comment]
We will implement https://docs.influxdata.com/flux/v0.x/stdlib/universe/window/.

**Comment by ritchie46** [comment]
See #2052 which will address this.
