### ISSUE TITLE
Insert/Drop Columns mess with df.columns

### ISSUE THREAD

**Issue by rmac66** [pola-rs/polars#20119]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

import polars as pl

data = {"a": [1, 2], "b": [3, 4]}
series = pl.Series("c", [5, 6])

df = pl.DataFrame(data)

print(f"{df}")

df.insert_column(2, series.alias("c"))

print(f"{df}")

df.drop_in_place("a")

print(f"{df}")

for c in df.columns:
    print(f"{df[c]}")

### Issue description

Dropping column a changes the column list but not reflected in the call to columns.  If you comment out the drop_in_place you end up with 3 entries in columns, but only 1 if you drop_in_place a

### Expected behavior

Should the df.columns in the line 19 access to the list provide both b and c?

### Installed versions

--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.3
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

**Comment by cmdlineluser** [comment]
I'm getting a PanicException 

```python
df = pl.select(a=1, b=2, c=3)
df.drop_in_place("a")
df.get_column("c")

# thread '<unnamed>' panicked at crates/polars-core/src/frame/mod.rs:1627:16:
# index out of bounds: the len is 2 but the index is 2
# PanicException: index out of bounds: the len is 2 but the index is 2
```

**Comment by ritchie46** [comment]
@coastalwhite this might be the new schema cache.
