### ISSUE TITLE
convert.py losses nanosecond precision 

### ISSUE THREAD

**Issue by JakkuSakura** [pola-rs/polars#20131]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
to_py_datetime(1731437100123456789, 'ns')
```

### Log output

```shell
datetime.datetime(2024, 11, 12, 18, 45, 0, 123456)
```

### Issue description

due to the fundamental limitation of CPython's datetime, nanosecond is not possible to represent. One promising alternative datetime type is 'whenever' https://github.com/ariebovenberg/whenever

### Expected behavior

preserve nanosecond precision somehow. or push cpython to fix https://github.com/python/cpython/issues/59648

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             False
----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.3.0
boto3                <not installed>
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.2.0
gevent               24.2.1
google.auth          2.36.0
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.7.1
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.2.1
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
what's `to_py_datetime`?

**Comment by JakkuSakura** [comment]
[polars/_utils/convert.py:164](https://github.com/pola-rs/polars/blob/d86e44b9796d57b3740cbd7e0b01901958085e2f/py-polars/polars/_utils/convert.py#L147)

**Comment by MarcoGorelli** [comment]
ok then I'd suggest starting with `DataFrame.rows` in the example 😉 

I don't think there's desire to take on extra Python dependencies as being required, but you could always just convert to integer and then parse with `whenver` (or whatever else you like) yourself outside of Polars

**Comment by JakkuSakura** [comment]
Converting each column manually is error-prone. I plan to do monkey patching with these conversion functions

**Comment by MarcoGorelli** [comment]
monkey-patching sounds even more error-prone?

anyway, thanks for your request, but i'll close as not-planned

**Comment by JakkuSakura** [comment]
monkey-patching makes sure my lib users don't need to "remember" to convert timestamps to int every time. It's an internal library, anyway. Another option is to maintain forks
