### ISSUE TITLE
`pl.read_csv` with `skip_rows` cannot deal with unbalanced double quotation in header

### ISSUE THREAD

**Issue by fbubser** [pola-rs/polars#20147]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

with open("example.csv", "w") as fh:
    fh.write('Header line "1" -> quote count 2\n')
    fh.write('Header line "2"" -> quote count 3\n')
    fh.write('Header line "3" -> quote count 2 => Total 7 quotes ERROR\n')
    fh.write('column_01, column_02, column_03\n')
    fh.write('123.12, 21, 99.9\n')
    fh.write('65.84, 75, 64.7\n')

df = pl.read_csv("example.csv",  has_header=True, skip_rows=3)

print(df)
```

### Log output

```shell
python : Traceback (most recent call last):
In Zeile:1 Zeichen:1
+ python main.py > std.txt 2> err.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Users\...\main.py", line 10, in <module>
    df = pl.read_csv("example.csv",  has_header=True, skip_rows=3)
  File "C:\Users\...\.venv\Lib\site-packages\polars\_utils\deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\...\.venv\Lib\site-packages\polars\_utils\deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\...\.venv\Lib\site-packages\polars\_utils\deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\...\.venv\Lib\site-packages\polars\io\csv\functions.py", line 527, in read_csv
    df = _read_csv_impl(
        data,
    ...<26 lines>...
        glob=glob,
    )
  File "C:\Users\...\.venv\Lib\site-packages\polars\io\csv\functions.py", line 672, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
        source,
    ...<27 lines>...
        schema=schema,
    )
polars.exceptions.NoDataError: empty CSV
```

### Issue description

The error always occurs if the total number of double quotation marks in the area of the omitted header (`skip_rows`) lines is not even. This is independent of how many double quotation marks are in which line.
For testing purposes, additional double quotation marks can be added or removed anywhere in the header lines.

### Expected behavior

The header lines omitted with `skip_rows` should not be evaluated, but should be omitted regardless of the content.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
LTS CPU:             False
----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
```

</details>

**Comment by ritchie46** [comment]
Skip rows still follows the csv semantics to determine what a row is. If you have a flawed csv file (faulty escaped), you get rows that differ from what you might expect as that `\n` was in an escaped field it must be ignored according to the csv spec.

**Comment by fbubser** [comment]
Thanks for the information. I had greatly simplified the example. Normally the extra double quotation is initiated with the escape character “\”, which leads to the same error. 

e.g. `fh.write('Header line "2\"" -> quote count 3 => Still ERROR\n')`

But as I just learned, this escape character is not valid for csv files. I have to use a secound double quotation.

`fh.write('Header line "2""" -> quote count 4 => WORKS :-) \n')`

Is there another method, independent of the content, to omit a defined number of rows?

**Comment by ritchie46** [comment]
Given the CSV is flawed, not with that quotation mark. It might work by setting a different quote character. Then you might need to post process escaped fields.

**Comment by fbubser** [comment]
That's a good idea. Unfortunately, it doesn't work in my case. I am in the paradoxical situation that there is a json object in the header of the csv file (I know, not in accordance with the csv semantics). Among other things, the csv dialect is documented in this object. This means that the 'quoteChar' specified there must correspond to the one in the actual csv part of the file. Unfortunately, the escape character convention of the csv and json semantics contradict each other.

Here is my concrete example.
```python
import polars as pl

    with open("example.csv", "w") as fh:
        fh.write('{\n')
        fh.write('  "name":"Testname",\n')
        fh.write('  "dialect":{\n')
        fh.write('    "csvddfVersion":"1.2",\n')
        fh.write('    "quoteChar":"\\""\n')
        fh.write('  }\n')
        fh.write('}\n')
        fh.write('\"column_01\",\"column_02\",\"column_03\"\n')
        fh.write('123.12,21,99.9\n')
        fh.write('65.84,75,64.7\n')

    df = pl.read_csv("example.csv", skip_rows=7)
```

**Comment by nickolay** [comment]
Since the actual CSV data only starts at line 7, it makes sense for you to skip over the non-CSV portion of the file before calling `read_csv`:
```
with open("example.csv", "rb") as f:
    for i in range(7): f.readline()
    df = pl.read_csv(f)
```

But I agree this is confusing. `skip_rows` is currently [documented](https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html) to "Start reading after skip_rows lines".

I think it should instead say something like this instead:

> Skip the first `skip_rows` rows of the CSV before reading the header. (If `has_header` is `False`, skip these rows before proceeding with `skip_rows_after_header`.)
>
> When counting the rows to skip, both `quote_char` and `eol_char` options are respected. Note that rows beginning with `comment_prefix` are included in the count of skipped rows.

But I didn't test this fully.

(Also see #12440 about the confusing "empty CSV" error.)

**Comment by cmdlineluser** [comment]
In case it is of interest, DuckDB[^1] can infer the format in that example.

```python
duckdb.sql("from 'example.csv'").pl()
# shape: (2, 3)
# ┌───────────┬───────────┬───────────┐
# │ column_01 ┆ column_02 ┆ column_03 │
# │ ---       ┆ ---       ┆ ---       │
# │ f64       ┆ i64       ┆ f64       │
# ╞═══════════╪═══════════╪═══════════╡
# │ 123.12    ┆ 21        ┆ 99.9      │
# │ 65.84     ┆ 75        ┆ 64.7      │
# └───────────┴───────────┴───────────┘
```

```python
duckdb.sql("from sniff_csv('example.csv')").pl().glimpse()
# Rows: 1
# Columns: 12
# $ Delimiter                    <str> ','
# $ Quote                        <str> '"'
# $ Escape                       <str> '"'
# $ NewLineDelimiter             <str> '\\n'
# $ Comment                      <str> '\x00'
# $ SkipRows                     <u32> 7
# $ HasHeader                   <bool> True
# $ Columns          <list[struct[2]]> [{'name': 'column_01', 'type': 'DOUBLE'}, {'name': 'column_02', 'type': 'BIGINT'}, {'name': 'column_03', 'type': 'DOUBLE'}]
# $ DateFormat                   <str> None
# $ TimestampFormat              <str> None
# $ UserArguments                <str> None
# $ Prompt                       <str> 'FROM read_csv(\'example.csv\', auto_detect=false, delim=\',\', quote=\'"\', escape=\'"\', new_line=\'\\n\', skip=7, comment=\'\', header=true, columns={\'column_01\': \'DOUBLE\', \'column_02\': \'BIGINT\', \'column_03\': \'DOUBLE\'});'
```

[^1]: https://duckdb.org/docs/data/csv/overview

**Comment by ritchie46** [comment]
Maybe we should add a `skip_lines` that ignores all csv semantics to disambiguate these cases.
