### ISSUE TITLE
Instructions for building py-polars with a subset of features

### ISSUE THREAD

**Issue by twoertwein** [pola-rs/polars#20155]
### Description

Provide an example for building py-polars with a subset of features, for example without the cloud feature (to hopefully make the resulting polars.abi3.so file smaller https://github.com/pola-rs/polars/issues/11599). I saw there is a `--exclude-features` [flag](https://github.com/pola-rs/polars/blob/c346fc2c1820131e9ccb568b0eafe0a9be5fce5d/crates/Makefile#L139) but I'm unsure how to combine that with `make build` (in py-polars).

**Comment by ritchie46** [comment]
There are none. It is not meant to compile with a subset of features. It's only for our development.
