### ISSUE TITLE
`map_elements` has high overhead even with empty dataframe

### ISSUE THREAD

**Issue by mwaddoups** [pola-rs/polars#20272]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# Empty dataframe
df = pl.DataFrame([], schema={'x': pl.Float64})

def simple_add(x):
    return x + 1

def simple_add_with_extra_locals(x):
    y = 3
    z = 4
    l = 2
    v = 5
    return x + 1

%timeit df.select(pl.col('x'))

```

### Log output

```shell
Actual evaluation
9.07 μs ± 90.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
247 μs ± 920 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
391 μs ± 2.12 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
Expression only
635 ns ± 6.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
101 μs ± 293 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
176 μs ± 545 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

### Issue description

It appears that using `.map_elements(f)` incurs a decent overhead cost that is somewhat proportional to the actual size of the function! And this overhead is introduced on expression creation, rather than on call. 

I'm guessing this is to do with how the function is called from Rust within Polars.

This has quite a significant effect for me but I appreciate my use case may be an edge case. I have a data pipeline that processes the majority (95%) of elements in a pure-polars way, but the remaining 5% in a map_elements function. It's also ran in an online setting as well as batch which means we may see many invocations with smaller datasets.

I find in this case there is a 2ms+ setup time with a fairly complex function passed to `map_elements`. There is no way for me to avoid this in a lazy setting - I have to write the whole online evaluation as eager and check length manually.

I'm fine if this is just what's expected - but I thought I'd flag as it seemed unusual to have the overhead at expression setup time, and may be worth at least documenting the behaviour?

I also appreciate my use case is unusual and 2ms is unlikely to matter for the vast majority of larger workflows.

### Expected behavior

Close to zero overhead at expression creation time (as was imagining just a reference to the function pointer), an at runtime with an empty frame.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Linux-6.1.112+-x86_64-with-glibc2.39
Python:              3.12.4 (main, Aug 20 2024, 17:14:48) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          2.36.0
great_tables         <not installed>
matplotlib           3.9.3
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

> And this overhead is introduced on expression creation, rather than on call.

my suspect would be that it's the "inefficient mapelements warning" parsing that's repsonsible for the overhead. In which case, I think it's worth it anyway

**Comment by avimallu** [comment]
This feature is not ordinary magic - probably more akin to black magic: https://github.com/pola-rs/polars/pull/9993 for details if you're interested.

**Comment by alexander-beedie** [comment]
I think we can reduce the overhead further; just spotted an opportunity for an earlier function exit on detection of incompatible bytecode ops 🤔

**Comment by ritchie46** [comment]
I think we can close this now with #20280
