### ISSUE TITLE
Improved error messages for SchemaError

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#20322]
### Description

`SchemaError`s in polars tends to come out like:
```
polars.exceptions.SchemaError: type String is incompatible with expected type Float64
```
or
```
polars.exceptions.SchemaError: invalid series dtype: expected `FixedSizeList`, got `list[f64]`
```

It would be very useful if they explained which input expressions were the cause of the failure, and then outline exactly how the underlying schema differs from what is expected and where.

**Comment by ritchie46** [comment]
Merged the proposed improvement. I will close this issue as we are working on better error diagnostics and specific issues are not needed
