### ISSUE TITLE
Support glob paths in read_excel

### ISSUE THREAD

**Issue by daviewales** [pola-rs/polars#20354]
### Description

If I have a directory of CSV files with the same structure, I can easily read them all into a single dataframe on a single line as follows:

``` python
df = pl.read_csv('*.csv')
```

However, if I try to do this with Excel files, I get a file not found error:

``` python
df = pl.read_excel('*.xlsx')
# ... FileNotFoundError: *.xlsx
```

It would be nice if `read_excel` also supported glob paths.

**Comment by pawarbi** [comment]
I agree with this. This is a very common scenario in companies and instead of iterating over the files, it would be more performant and useful if glob path could be used. 

Ideally it should work with '*.xlsx', 'filename*.xlsx' and support recursive lookup. 

Thanks

**Comment by daviewales** [comment]
Thank you!
