### ISSUE TITLE
Add a `cum_mean` function to compute the cumulative mean

### ISSUE THREAD

**Issue by FrancescoMandru** [pola-rs/polars#20353]
Currently, Polars does not support natively the `cum_mean` but users can calculate it by combining `cum_sum` and `cum_count`. However, in my opinion it would be beneficial to have a dedicated `cum_mean` function to make this operation more intuitive and improve code readability.

Writing `df["col"].cum_mean()` would be clearer and more concise compared to `df["col"].cum_sum() / df["col"].cum_count()`, especially when we want to also group by some other columns.

If this sounds a very bad idea I will be happy to understand why, I believe there is a reason why you decided to implement only `cum_max` and `cum_min`.

I will be happy to take care of this specific feature request in order to learn to contribute!

**Comment by avimallu** [comment]
As I've understood it from previous issues, Polars typically tries to encourage "composing" functions rather than accommodating a different function for each kind of operation. Unless calculating `cum_mean` by its own function improves efficiency and/or speed, I'm not sure what the benefit would be.

That said, might I ask why you're performing `df["col"]` based operations? Polars recommends (and prefers) using expressions directly. In your case, you could just as well define a function:

```py
import polars as pl
cum_mean = lambda x: pl.col(x).cum_sum().truediv(pl.col(x).cum_count())
```

and use it downstream as so:

```py
df.with_columns(cum_mean("col"))
```

If the `with_columns` usage is unintuitive or unfamiliar to you, perhaps go through the user guide section on [expressions](https://docs.pola.rs/user-guide/expressions/basic-operations/#basic-arithmetic)?

**Comment by FrancescoMandru** [comment]
@avimallu, thank you for replying!

This isn’t about whether the feature can be expressed in terms of existing functionality—I agree that your implementation is effective. The core of the discussion is whether users should be forced to repeatedly write:

```python
cum_mean = lambda x: pl.col(x).cum_sum().truediv(pl.col(x).cum_count())
```

in every script where they need the cumulative mean. This repetition increases the chance of errors and makes the code less clean and reusable.

Furthermore, if you need to compute cumulative means across different groupings or in more complex scenarios, you would end up writing a lot of repetitive code that could be encapsulated much better with a dedicated function like `cum_mean`.

**Comment by avimallu** [comment]
Note: I do not speak for the Polars dev team.

> The core of the discussion is whether users should be forced to repeatedly write:

My understanding based on previous issues (a few: [1](https://github.com/pola-rs/polars/issues/6175), [2](https://github.com/pola-rs/polars/issues/7120), [3](https://github.com/pola-rs/polars/issues/12420)), the answer is yes.

> This repetition increases the chance of errors and makes the code less clean and reusable.

I disagree. If there are expressions or code patterns you frequently use, you should ideally import them from a helper script. 
P.S. I am not an arbiter here - this is an opinion on best practices.

> if you need to compute cumulative means across different groupings or in more complex scenarios

Could you explain what these are? You can use `cum_mean` in `group_by` and in `over` statements the same way:

```
import polars as pl
cum_mean = lambda x: pl.col(x).cum_sum().truediv(pl.col(x).cum_count())
(
   pl.DataFrame({"group": [1, 1, 1, 2, 2], "val": [1, 2, 3, 4, 5]})
   .group_by("group")
   .agg(cum_mean("val"))
)
```

to get:

```
shape: (2, 2)
┌───────┬─────────────────┐
│ group ┆ val             │
│ ---   ┆ ---             │
│ i64   ┆ list[f64]       │
╞═══════╪═════════════════╡
│ 1     ┆ [1.0, 1.5, 2.0] │
│ 2     ┆ [4.0, 4.5]      │
└───────┴─────────────────┘
```

**Comment by FrancescoMandru** [comment]
> I disagree. If there are expressions or code patterns you frequently use, you should ideally import them from a helper script.

Agree
