### ISSUE TITLE
quantile always return float

### ISSUE THREAD

**Issue by marcvanheerden** [pola-rs/polars#2036]
> be useful to have another quantile function that always returns f64 like .median() does.
> 
> Happy to make any changes you want

Again, thanks a lot!

> having the output in the original types means that for integer types the "midpoint" and "linear" interpolation options essentially do the same thing as "lower". Let me know if you want to change this?

Not a blocker for this PR. But I think it makes sense to always return `f64` indeed (except if the dtype is `f32`).

_Originally posted by @ritchie46 in https://github.com/pola-rs/polars/issues/2001#issuecomment-992158630_

**Comment by marcvanheerden** [comment]
@ritchie46 just want to clarify, do you want a different quantile function that always returns float or do you want to change the existing quantile function to do this?

**Comment by ritchie46** [comment]
The existing one.

And then depending on the quantile interpolation method, we return a floats.

**Comment by ritchie46** [comment]
@marcvanheerden is this resolved lately?

**Comment by marcvanheerden** [comment]
Will finish this off today

**Comment by marcvanheerden** [comment]
the traits are a little trickier than I expected, will try finish today
