### ISSUE TITLE
docs: Is `maintain_order` description in `pivot` incorrect?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#20403]
### Description

`maintain_order` is described to say
```
    Sort the grouped keys so that the output order is predictable.
```

I don't think this is right though - the grouped keys (i.e. `index`) aren't sorted, but rather their input order is maintained

I think this just needs fixing to say
```
    Ensure that the order of values in `index` is consistent with their order in the input data.
```
(possibly split along two lines)

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

**Comment by ritchie46** [comment]
Yeah, the group discovery order is maintained. We can make it more clear.
