### ISSUE TITLE
LazyFrame auto collect() on print

### ISSUE THREAD

**Issue by ddouglas87** [pola-rs/polars#20405]
### Description

It would be quite nice if lazyframes printed the same way as dataframes print.  It's particularly useful in notebooks where you have to type `.collect()` every time you want to see some output from a cell.

This change would have a side effect of some users using lazyframes even when they don't need to.  Users might default to lazyframes as a way to keep everything consistent, instead of like it is now where dataframes are used in some parts of a project and lazyframes in used are in other parts of the same project.  Are there times when lazyframes are drastically slower and should be avoided, or is it ideal for users to default to lazyframes even for smaller sized frames?

**Comment by alexander-beedie** [comment]
A LazyFrame can represent significant computation across thousands of files (for example: a `scan_parquet` operation that queries a large directory of hive-partitioned data); printing it by default as if it represented a regular DataFrame could be a _very_ bad idea  ;)

**Comment by ritchie46** [comment]
This has been discussed before.  And as @alexander-beedie explains this is not something we will do implicitly as it can trigger ungodly amounts of work. 

We will likely land a form of `show` that will be a more cheaper print (if the query allows it).

Another reason is that the current print shows the logical plan, which is a much better default anyway considering what a LazyFrame represents, a computation graph/ plan of operations.

**Comment by ddouglas87** [comment]
>This has been discussed before.

Apologies.  I searched around quite a bit and couldn't find anything.

>which would get recomputed each time you look at the repr.

I see.  I figured it cached on `collect()`, somewhat similar to turning a lazyframe into a dataframe under the hood, so it doesn't recalculate more than it has to.

>We will likely land a form of show that will be a more cheaper print (if the query allows it).

That would be wonderful.

>Another reason is that the current print shows the logical plan, which is a much better default anyway considering what a LazyFrame represents, a computation graph/ plan of operations.

Ah, I see.

Thanks @ritchie46 and @alexander-beedie for the great explanations! 👍
