### ISSUE TITLE
filter's length: 3 differs from that of the series: 1 in chained filter

### ISSUE THREAD

**Issue by Liyixin95** [pola-rs/polars#20432]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars import col as c

df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "b": ["a", "a", "a", "b", "b", "b", "c", "c", "c", "d"],
    }
).lazy()

print(df.group_by("b").agg(a=c("a").filter(c("a") > 5).filter(c("a") < 8)).collect())
```

chained filter in groupby will get this error:

```
Traceback (most recent call last):
  File "/root/rust/sigrun-op-rs/./test.py", line 11, in <module>
    print(df.group_by("b").agg(a=c("a").filter(c("a") > 5).filter(c("a") < 8)).collect())
  File "/root/rust/polars/py-polars/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ShapeError: filter's length: 3 differs from that of the series: 1
```

if i put all the predicate to the same filter, this code works:
```
import polars as pl
from polars import col as c

df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "b": ["a", "a", "a", "b", "b", "b", "c", "c", "c", "d"],
    }
).lazy()

print(df.group_by("b").agg(a=c("a").filter(c("a") > 5, c("a") < 8)).collect())
```

### Issue description

as the example says

### Expected behavior

chain filter work fine

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Linux-5.10.0-28-amd64-x86_64-with-glibc2.31
Python:              3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
LTS CPU:             False
```

</details>

**Comment by orlp** [comment]
This is a usage error. After the first filter the lengths no longer match. `c("a")` in the second filter expression still refers to the original column `a`, not the column `a` after the first filter.

**Comment by Liyixin95** [comment]
> This is a usage error. After the first filter the lengths no longer match. `c("a")` in the second filter expression still refers to the original column `a`, not the column `a` after the first filter.

May I ask why chained filter works fine in select context? 
```
df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "b": ["a", "a", "a", "b", "b", "b", "c", "c", "c", "d"],
    }
).lazy()

print(df.filter(c("a") > 5).filter(c("a") < 8).collect())
```
