### ISSUE TITLE
v0.45.1 is not compiling error[E0658]: use of unstable library feature 'iter_repeat_n'

### ISSUE THREAD

**Issue by bill2345** [pola-rs/polars#20442]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
$ cargo build --release
   Compiling polars-row v0.45.1
error[E0658]: use of unstable library feature 'iter_repeat_n'
  --> /home/sun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-row-0.45.1/src/encode.rs:52:9
   |
52 |         std::iter::repeat_n(RowEncodingOptions::default(), columns.len())
   |         ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #104434 <https://github.com/rust-lang/rust/issues/104434> for more information

error[E0658]: use of unstable library feature 'iter_repeat_n'
   --> /home/sun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-row-0.45.1/src/encode.rs:772:45
    |
772 | ...                   .extend(std::iter::repeat_n(masked_out_write_offset, length));
    |                               ^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #104434 <https://github.com/rust-lang/rust/issues/104434> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-row` (lib) due to 2 previous errors
```

### Issue description

rust polars v0.45.1 compile issue:
rustc 1.81.0 (eeb90cda1 2024-09-04)
cargo 1.81.0 (2dbb1af80 2024-08-20)

### Expected behavior

compile should be passed

### Installed versions

<details>

polars = { version = "0.45.1", features = ["abs","diff", "json", "round_series", "strings", "regex", "lazy", "ewma","rolling_window", "pct_change", "dynamic_group_by","semi_anti_join" ] }

</details>

**Comment by coastalwhite** [comment]
Rust 1.82.0 is stable rust. You need to update your rust compiler.

**Comment by weixingsun** [comment]
thanks for helping I can compile it now !

**Comment by Antti** [comment]
@coastalwhite We need to set [`rust-version`](https://doc.rust-lang.org/cargo/reference/rust-version.html) in `Cargo.toml` to avoid these issues in the future
