### ISSUE TITLE
Columns with null dtype are ignored in `sum_horizontal`/`mean_horizontal` regardless of `ignore_nulls` parameter

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#20455]
### Issue description

If one of the columns in `sum_horizontal` or `mean_horizontal` has a null dtype then it is ignored even if `ignore_nulls = False`.

```python
import polars as pl

df = pl.DataFrame({
    "a": [None, None],
    "b": [1, 2],
})
df.select(pl.sum_horizontal("a", "b", ignore_nulls=False))
shape: (2, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# └─────┘
```

### Installed versions

main

**Comment by ritchie46** [comment]
The above example is what I would expect. We don't propagate nulls in the sum, but use the identity.
