### ISSUE TITLE
db connection  - close connection

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2047]
Hi;

In documentation; reading data from db is documented like below. I wonder that after I retrieve data, is connection closed automatically? If not we can add a feature not to leave connection open. (Probably I should ask this question to connectorx) I'm not sure how you or connectorx are handling. I'm opening this issue to understand how it is working.

> import polars as pl
> 
> conn = "postgresql://username:password@server:port/database"
> query = "SELECT * FROM foo"
> 
> pl.read_sql(query, conn)

**Comment by ritchie46** [comment]
I assume it will be closed. But this question is better fitted for connector-x indeed.

**Comment by hakantekbas** [comment]
@ritchie46  Thanks.

**Comment by hakantekbas** [comment]
https://github.com/sfu-db/connector-x/issues/195
