### ISSUE TITLE
Consider slots

### ISSUE THREAD

**Issue by v1gnesh** [pola-rs/polars#20472]
### Description

Came across this blog post today - https://dev.arie.bovenberg.net/blog/finding-broken-slots-in-popular-python-libraries/.  
It talks about [`__slots__`](https://docs.python.org/3/reference/datamodel.html#slots).  
Here's an example of SQLAlchemy benefitting from it - https://docs.sqlalchemy.org/en/20/changelog/migration_10.html#significant-improvements-in-structural-memory-use  

Don't know how feasible it is for the (python wrapper of) polars, but just thought I'd bring it up for discussion/assessment.

**Comment by stinodego** [comment]
We have actually done this before but it led to a lot of issues. The potential performance gain is marginal so we're not really planning on trying our hand on this again.

See https://github.com/pola-rs/polars/issues/13198 and linked PR for reference.
