### ISSUE TITLE
tab-complete doesn't work for pl.col(...).dt in IPython

### ISSUE THREAD

**Issue by akshayka** [pola-rs/polars#20496]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

In IPython, `pl.col('...').` gets many valid completions:

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/becafe6b-7bc3-4076-8594-735068ab19a8" />

But `pl.col('...').dt.` does not:

<img width="407" alt="image" src="https://github.com/user-attachments/assets/f564ff9a-8df2-48ad-a133-f47e6d7d75ad" />

Completion works if I assign `pl.col('...').dt` to a variable:

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/a0c56fe0-51c5-4deb-9569-1488b02db7a2" />

```python

```

### Issue description

This issue looks related to a previous issue in which `pl.col('...')` failed to generate completions in IPython: https://github.com/pola-rs/polars/issues/11433.

This could be an IPython bug. But similar to #11433, which was resolved with PR #11435 , maybe there is something polars can do to help?

In addition to affecting IPython, it also affects the marimo notebook (https://github.com/marimo-team/marimo/issues/3302). I have not checked but it may also affect Jupyter/JupyterLab.

### Expected behavior

tab-complete to help as much as possible

### Installed versions

<details>

```
In [12]: pl.show_versions()
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

**Comment by ritchie46** [comment]
Hmm... I don't really see anything special with the `dt` accessor? It is an `@propery` returning:

```python
    @property
    def dt(self) -> ExprDateTimeNameSpace:
        """Create an object namespace of all datetime related methods."""
        return ExprDateTimeNameSpace(self)

```

**Comment by MarcoGorelli** [comment]
thanks @akshayka for the report

there's an issue open about this: https://github.com/pola-rs/polars/issues/16933

from discussion, the consensus was that this is very desirable to solve, but i don't think anyone got to the bottom of what exactly it was

**Comment by akshayka** [comment]
Thanks for the context, and sorry I missed the other issue! Feel free to close this as a duplicate.

**Comment by MarcoGorelli** [comment]
no worries at all! sure, doing so
