### ISSUE TITLE
Clarify the pre-condition of `join_asof()`

### ISSUE THREAD

**Issue by georeth** [pola-rs/polars#20500]
### Description

The docs says ```Both DataFrames must be sorted by the asof_join key.```

I cannot figure out whether `asof_join key` should be sorted globally or sorted in each group if I group the data by another `by key`. If each group is processed separatedly, it should be enough to only require each group to be sorted.
Please make the docs more clear.

In my scenario, the data is already sorted by `asof_join key` in each group. Should I sort the whole DataFrame once more to guarantee the correctness?

```python
df.join_asof(df2, on='date', strategy="backward", by='group')

# or
df.sort('date', 'group').join_asof(df2, on='date', strategy='backward', by='group').sort('group', 'date')
```

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join_asof.html

**Comment by mcrumiller** [comment]
The `asof_join` key only needs to be sorted within each `by` group. If you are sorting with `by `, then you can perform a `df1.sort(*by_keys, asof_key)` (and same for df2) and it will work properly. The examples even show frames where the `on` key is sorted within the by groups.
