### ISSUE TITLE
unique in aggregation

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2051]
Hi;

I'm trying to find unique value in group by expression. As I'm sure that it will produce only one result in each group, it should work. At least this type of expression is working in R data.table. I'm not sure I'm missing some part. As you can see clearly, I added two different version of unique expression. List version is working but when I take the first element, wrong result is coming. Especially last part of result is strange.

>    pl.from_pandas(df).sort("purchase_date",reverse=False) 
                                  .groupby(["monthYearTravel", "origcountry", "purchase_date_ym"]) 
                                 .agg( [pl.col("monthFark").unique().first().alias("monthFark"),
                                           pl.col("monthFark").unique().alias("monthFarkList")  ] )

![image](https://user-images.githubusercontent.com/19631334/146323986-53a86b6d-e2f4-4d73-b9bc-e8bf390bf2fe.png)

Thanks.

**Comment by ritchie46** [comment]
I will take a look at it: :+1:

**Comment by hakantekbas** [comment]
Thanks

**Comment by ritchie46** [comment]
There is a fix. Note that the `unique` expression does not guarantee order, so you can best run `unique().sort().first()`

**Comment by hakantekbas** [comment]
In my case, only one data will return from unique, so sort will not be necessary. If you need data, I prepared.

**Comment by ritchie46** [comment]
> In my case, only one data will return from unique, so sort will not be necessary. If you need data, I prepared.

Why run unique then and not first?

**Comment by hakantekbas** [comment]
yeah this is the another option and cost effective. but indeed original version does not return one value. I'm sorting then I'm returning first values. (as in you pointed in your first message ) 

I tried to create a simple example. I shared this one.
