### ISSUE TITLE
Rolling aggregations not working for various integer types

### ISSUE THREAD

**Issue by lukemanley** [pola-rs/polars#20511]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series("a", [1, 2, 3, 4], pl.Int8)
s.rolling_sum(2)
```

### Log output

```shell
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs:218:9:
not implemented for dtype Int8
```

### Issue description

The example above panics for i8, i16, i128, u8, u16 - all of which are feature gated inside the macro below. The python example works as expected if I remove the feature gates from this macro and rebuild, though I'm not sure that is the correct fix?

https://github.com/pola-rs/polars/blob/c88911f3e4153cf9f994a39de4ed89e55c4102f9/crates/polars-core/src/utils/mod.rs#L505-L530

### Expected behavior

Works without panicking

### Installed versions

<details>

```
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.7 (main, Oct 26 2024, 21:27:43) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
I suspect the feature gates aren't propagated properly to the `polars-time` crate.

**Comment by Chuck321123** [comment]
The same problem occurs for rolling_min and rolling_max

**Comment by lukemanley** [comment]
> The same problem occurs for rolling_min and rolling_max

yep, I think https://github.com/pola-rs/polars/pull/20512 fixes (and tests) min/max/sum
