### ISSUE TITLE
Converting AnyValue to string leads to additional quotation marks

### ISSUE THREAD

**Issue by quambene** [pola-rs/polars#2055]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

None

#### What version of polars are you using?

0.17

#### What operating system are you using polars on?

Ubuntu

#### Describe your bug.

Converting `AnyValue` to string leads to additional quotation marks if `AnyValue` is a string already.

#### What are the steps to reproduce the behavior?

``` rust
let s = Series::new("my_series", &["Foo", "Bar"]);
println!("{}", s.utf8().unwrap().get(0).unwrap()); // output: Foo
println!("{}", s.get(0).to_string()); // output: "Foo"
```

#### What is the expected behavior?

In both print statements above, I would have expected a string _without_ quotation marks as output.

**Comment by ritchie46** [comment]
AnyValue is use for formatting, we use the quotation marks to make clear that its a string. If you want to convert to a string you'll have to pattern match.

**Comment by quambene** [comment]
Thanks for clarifying. Pattern matching is working fine.
