### ISSUE TITLE
Left joins followed by filters on LazyFrames returns unexpected rows

### ISSUE THREAD

**Issue by leesavoie-voltaiq** [pola-rs/polars#2057]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

polars 0.11.0

#### What operating system are you using polars on?

Ubuntu 16.04
Python 3.7.5

#### Describe your bug.

If you left join two lazy frames and then filter on a column from the right dataframe, the result will include all the rows from the original dataframe with nothing filtered out. However, the value in the column you filtered on will be null for the rows that should have been filtered out.

#### What are the steps to reproduce the behavior?

This code reproduces the issue:

```
import polars as pl

df1 = pl.DataFrame({
    "foo": ["abc", "def", "ghi"],
    "index1": [0, 0, 1]
}).lazy()
df2 = pl.DataFrame({
    "bar": [5, 6],
    "index2": [0, 1]
}).lazy()

result = (
    df1.join(df2, left_on="index1", right_on="index2", how="left")
    .filter(pl.col("bar")== 5)
    .collect()
)
print(result)
```

#### What is the actual behavior?

Actual output:

```
shape: (3, 3)
┌─────┬────────┬──────┐
│ foo ┆ index1 ┆ bar  │
│ --- ┆ ---    ┆ ---  │
│ str ┆ i64    ┆ i64  │
╞═════╪════════╪══════╡
│ abc ┆ 0      ┆ 5    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ def ┆ 0      ┆ 5    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ ghi ┆ 1      ┆ null │
└─────┴────────┴──────┘
```

Note that the last row should not be included in the output.

#### What is the expected behavior?

Expected output:

```
shape: (2, 3)
┌─────┬────────┬─────┐
│ foo ┆ index1 ┆ bar │
│ --- ┆ ---    ┆ --- │
│ str ┆ i64    ┆ i64 │
╞═════╪════════╪═════╡
│ abc ┆ 0      ┆ 5   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ def ┆ 0      ┆ 5   │
└─────┴────────┴─────┘
```

**Comment by ritchie46** [comment]
Thanks for the issue report. I will take a look.
