### ISSUE TITLE
Python Polars API website is broken

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2061]
This website https://pola-rs.github.io/polars/py-polars/html/reference/ is missing lots of content that used to be there - some referencing issue? Some parts still exist - the DataFrame portion, but some parts like the Series portion are completely missing their content. The table of contents appears to still exist though despite the missing content.

![image](https://user-images.githubusercontent.com/1317013/146609782-0dafbe18-0375-467f-aaec-8294828e3bca.png)

![image](https://user-images.githubusercontent.com/1317013/146609803-bbfa3f80-e205-4b97-bdf5-f32db3042376.png)

**Comment by ritchie46** [comment]
Thanks for the heads up. A fix is underway.
