### ISSUE TITLE
Converting from arrow table is re-chunking even when explicitly set to False.

### ISSUE THREAD

**Issue by coady** [pola-rs/polars#2073]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.0

#### What operating system are you using polars on?

macOS 11.6

#### Describe your bug.

`polars.from_arrow(a, rechunk=False)` re-chunks the table despite the False option. 

#### What are the steps to reproduce the behavior? What is the actual behavior?

```python
In []: table = pa.Table.from_pydict({'x': pa.chunked_array([list('ab'), list('cd')])})

In []: [column.num_chunks for column in table]
Out[]: [2]

In []: pl.from_arrow(table, rechunk=False).n_chunks()
Out[]: 1
```

#### What is the expected behavior?

That it wouldn't re-chunk the table, and therefore be a fast zero-copy conversion on large tables.

**Comment by ritchie46** [comment]
Hmm... Yeah, rust arrow does not have a concept of a chunked_array. Is it possible to get the individual chunks as arrow arrays zero copy? Then we could convert that to a polars chunkeda array indeed.

**Comment by jorgecarleitao** [comment]
I would expect so: a ChunkedArray is a C++-specific concept; they are basically `Vec<Box<dyn Array>>`, so we should able to convert them to `Array`. I do not know if they have all the same length (I really hope so :/).

**Comment by ritchie46** [comment]
Yes, then we could just iterate over them and put them in a polars `ChunkedArray` (which allows different sized chunks, so that's ok).

Its still not completely zero-copy, because polars does not support arrow list, only arrow large-list.
