### ISSUE TITLE
groupby_dynamic set wrong time values, when addionally grouping with normal keys

### ISSUE THREAD

**Issue by seb2704** [pola-rs/polars#2080]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.1

#### What operating system are you using polars on?

Ubuntu 20.04

#### Describe your bug.
When I'm using the groupby_dynamic method with normal groupby keys, then all time values are set to the same date(the lowerbound of the first timing window  within a group).

#### What are the steps to reproduce the behavior?

```
import polars as pl
import datetime
df = pl.DataFrame(
    {"EVENT_DATE": [datetime.datetime(2021,4,11), datetime.datetime(2021,4,29),datetime.datetime(2021,5,29)],
     "adm1_code": [1, 2,1],
     "test": ['a', 'b','a'],
    })
df = (df.sort(by='EVENT_DATE').groupby_dynamic(
            time_column="EVENT_DATE",
            every="1mo",
            include_boundaries=True,
            by='test',
        ).agg([
            pl.col('adm1_code').sum(),
        ])
        )
```

**Example**

```python
import polars as pl
import numpy as np

# Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
})
```

#### What is the actual behavior?

```
┌──────┬─────────────────────┬─────────────────────┬─────────────────────┬───────────────┐
│ test ┆ _lower_boundary     ┆ _upper_boundary     ┆ EVENT_DATE          ┆ adm1_code_sum │
│ ---  ┆ ---                 ┆ ---                 ┆ ---                 ┆ ---           │
│ str  ┆ datetime            ┆ datetime            ┆ datetime            ┆ i64           │
╞══════╪═════════════════════╪═════════════════════╪═════════════════════╪═══════════════╡
│ a    ┆ 2021-04-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ 1             │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ a    ┆ 2021-05-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ 1             │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 2021-04-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ 2             │
└──────┴─────────────────────┴─────────────────────┴─────────────────────┴───────────────┘
```

#### What is the expected behavior?

set the time value to the lower bound of the actual timing window
```
┌──────┬─────────────────────┬─────────────────────┬─────────────────────┬───────────────┐
│ test ┆ _lower_boundary     ┆ _upper_boundary     ┆ EVENT_DATE          ┆ adm1_code_sum │
│ ---  ┆ ---                 ┆ ---                 ┆ ---                 ┆ ---           │
│ str  ┆ datetime            ┆ datetime            ┆ datetime            ┆ i64           │
╞══════╪═════════════════════╪═════════════════════╪═════════════════════╪═══════════════╡
│ a    ┆ 2021-04-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ 1             │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ a    ┆ 2021-05-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ 1             │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 2021-05-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 2             │
└──────┴─────────────────────┴─────────────────────┴─────────────────────┴───────────────┘
```
It would be also nice, if you could chose a negative timing window to aggregate over the past and then set the time value to the lowerbound of the interval, like in rolling_apply

**Comment by ritchie46** [comment]
Right, I will take a look!.

> It would be also nice, if you could chose a negative timing window to aggregate over the past and then set the time value to the lowerbound of the interval, like in rolling_apply

I don't really understand what you mean here? With the `closed` keyword you can define on which side of the window membership is defined.

What is aggregate over the past? Data that is not in you dataframe?

**Comment by seb2704** [comment]
thank u for the quick fix! Maybe I got somewthing wrong, but the way i understood it is, when the time window is bigger then the interval, then the window affects the interval and the future values, in contrast a rolling window affects the current row and the previous row. For Example:
`df = pl.DataFrame(
    {"EVENT_DATE": [datetime.datetime(2021,4,11), datetime.datetime(2021,4,29),datetime.datetime(2021,5,29)],
     "adm1_code": [1, 2,1],
     "test": ['a', 'b','a'],
    })
df = (df.sort(by='EVENT_DATE').groupby_dynamic(
            time_column="EVENT_DATE",
            every="1mo",
            period="2mo",
            include_boundaries=True,
        ).agg([
            pl.col('adm1_code'),
        ])
        )`
results in
`┌─────────────────────┬─────────────────────┬─────────────────────┬────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ EVENT_DATE          ┆ adm1_code  │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---        │
│ datetime            ┆ datetime            ┆ datetime            ┆ list [i64] │
╞═════════════════════╪═════════════════════╪═════════════════════╪════════════╡
│ 2021-04-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ [1, 2, 1]  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-05-01 00:00:00 ┆ 2021-07-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ [1]        │
└─────────────────────┴─────────────────────┴─────────────────────┴────────────┘`
but I would like to have the option to get this
`┌─────────────────────┬─────────────────────┬─────────────────────┬────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ EVENT_DATE          ┆ adm1_code  │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---        │
│ datetime            ┆ datetime            ┆ datetime            ┆ list [i64] │
╞═════════════════════╪═════════════════════╪═════════════════════╪════════════╡
│ 2021-04-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ [1,2]  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-05-01 00:00:00 ┆ 2021-07-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 1, 2, 1]       │
└─────────────────────┴─────────────────────┴─────────────────────┴────────────┘`

**Comment by ritchie46** [comment]
I don't understand? The `adm1_codes` you want in your dataframe ar not a member of that window? If I look at the lower an upper boundaries, I see that it correctly includes the members of that window.

**Comment by seb2704** [comment]
sorry for the misunderstanding, i forgot to adept the lower and upper boundaries of the second example output, i corected it.  I try to be more clear. The code in my comment works as expected, it results in a Dataframe and for each month i get a list of the data for the current and the next month. But I would like to have a option to get the data foreach month and the last month like in the second example output.

**Comment by ritchie46** [comment]
You want to offset your window by `-1mo`:

```python
(df.groupby_dynamic(
            time_column="EVENT_DATE",
            every="1mo",
            period="2mo",
            offset="-1mo",
            include_boundaries=True,
    ).agg([
        pl.col('adm1_code'),
    ])
)
```

```
shape: (3, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ EVENT_DATE          ┆ adm1_code  │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---        │
│ datetime            ┆ datetime            ┆ datetime            ┆ list [i64] │
╞═════════════════════╪═════════════════════╪═════════════════════╪════════════╡
│ 2021-03-01 00:00:00 ┆ 2021-05-01 00:00:00 ┆ 2021-03-01 00:00:00 ┆ [1, 2]     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-04-01 00:00:00 ┆ 2021-06-01 00:00:00 ┆ 2021-03-01 00:00:00 ┆ [1, 2, 1]  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-05-01 00:00:00 ┆ 2021-07-01 00:00:00 ┆ 2021-04-01 00:00:00 ┆ [1]        │
└─────────────────────┴─────────────────────┴─────────────────────┴────────────┘

```

**Comment by seb2704** [comment]
thats it, shame on me i could knew that my self, big thanks. Should the date column look like that after the groupby operation?

**Comment by ritchie46** [comment]
>  Should the date column look like that after the groupby operation?

Hmm.. No it should be 2021-03-01 00:00:00. I will fix that.
