### ISSUE TITLE
Build fails with "lazy" + "ipc" features

### ISSUE THREAD

**Issue by dbr** [pola-rs/polars#2081]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

lazy and ipc seem to be the relevant ones

The full set this triggered with was:

    polars = { version = "0.18", features = ["lazy", "decompress", "dtype-date", "strings", "mode", "diagonal_concat", "ipc"] }

#### What version of polars are you using?

v0.18.0

#### What operating system are you using polars on?

Linux

#### Describe your bug.

If running with `lazy` and `ipc` the library fails to build:

```
error[E0599]: no function or associated item named `new` found for struct `polars_io::ipc::IpcReader` in the current scope
   --> /home/dbr/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.18.0/src/logical_plan/mod.rs:846:42
    |
846 |         let schema = Arc::new(IpcReader::new(file).schema()?);
    |                                          ^^^ function or associated item not found in `polars_io::ipc::IpcReader<_>`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use polars_io::SerReader;`
```

https://github.com/pola-rs/polars/blame/1606cbc4a98988a4fded0d73f661ee89d1e58af7/polars/polars-lazy/src/logical_plan/mod.rs#L848

As writing this I noticed including the `parquet` feature works around the problem due to this line:
https://github.com/pola-rs/polars/blame/1606cbc4a98988a4fded0d73f661ee89d1e58af7/polars/polars-lazy/src/logical_plan/mod.rs#L19-L20

#### What are the steps to reproduce the behavior?

`cargo new` then

```
[package]
name = "polarsipcbug"
version = "0.1.0"
edition = "2018"

[dependencies]
polars = { version = "0.18", features = ["lazy", "ipc"]}
```

Then `cargo build`

**Comment by ritchie46** [comment]
Right, could you make do a PR with that fix for IPC as well?

**Comment by dbr** [comment]
Yep done! #2099
