### ISSUE TITLE
Suggested documentation fixes (probably a Good First Issue)

### ISSUE THREAD

**Issue by ianozsvald** [pola-rs/polars#2091]
I spotted a few sentences that can be improved on the Polars documentation, maybe someone wants to pick these up as a good first bug? I'll propose the fixes below for https://pola-rs.github.io/polars-book/user-guide/optimizations/lazy/predicate-pushdown.html :

* "reducing number the number of rows on that table. -> "reducing the number of rows on that table."
* "This due to the lazyness, ... happend until" ->"This is due to lazy evaluation, nothing will happen until it is specifically requested."
* "A join is quite an expensive operation the less rows we through at a join operation, the cheaper it becomes." -> "A join is quite an expensive operation, the fewer rows we have in a join operation the cheaper it will become."

**Comment by ianozsvald** [comment]
Should I move this to the polars-book repo?

**Comment by ritchie46** [comment]
Yeap, if its from the book. :)

**Comment by ritchie46** [comment]
Fixed in https://github.com/pola-rs/polars-book/pull/102

**Comment by ianozsvald** [comment]
Sorry to be slow - thanks for fixing! i.
