### ISSUE TITLE
better docs on rank windowing function

### ISSUE THREAD

**Issue by ankopainting** [pola-rs/polars#2098]
#### Docs on rank windowing function and how to nest aggregates

Let's say I have a csv;

```csv
transaction_id,user,book
1,bob,bookA
2,bob,bookA
3,bob,bookB
4,tim,bookA
5,lucy,bookA
6,lucy,bookC
7,lucy,bookC
8,lucy,bookC
```

per user, i want to find the book they have shown the most preference towards.  For example, the output should be
```
shape: (3, 2)
┌──────┬──────────┐
│ user ┆ fav_book │
│ ---  ┆ ---      │
│ str  ┆ str      │
╞══════╪══════════╡
│ bob  ┆ bookA    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ tim  ┆ bookA    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ lucy ┆ bookC    │
└──────┴──────────┘
```

Now, i've worked out how to do it like so;

```
import polars as pl

df = pl.read_csv("book_aggs.csv")

print(df)

df2 = df.groupby(["user", "book"]).agg([
  pl.col("book").count(),
  pl.col("transaction_id") # just so we can double check where it all came from - TODO: how to output this to csv?
  ])

print(df2)

df3 = df2.sort(["user", "book_count"], reverse=True).groupby("user").agg([
  pl.col("book").first().alias("fav_book")
])

print(df3)
```

but really the normal sql way of doing it is a dense_rank sorted by book count descending where rank = 1.  I have tried for hours to get this to work but i can't find a relevant example in the docs.

the issue is that in the docs, none of the agg examples reference the output of another agg - in this case it needs to reference the count of each book per user, and then sort those counts descending and then rank based on that sort order.

Please provide an example that explains how to use rank, and also how to nest aggregations efficiently.

**Comment by ritchie46** [comment]
Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

**Comment by ankopainting** [comment]
you're a legend, will do

**Comment by ankopainting** [comment]
https://stackoverflow.com/questions/70431642/in-polars-how-could-i-use-rank-to-get-most-popular-category-per-user

**Comment by ritchie46** [comment]
Answerer. :slightly_smiling_face:
