### ISSUE TITLE
Backward_fill and forward_fill with over clause

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2108]
Hi;

I tried expression below. It can't fill the data. but When nan is converted to none, result is as it should be

> data = pl.DataFrame({"a":  ["r","r","r","r","s","s","s","s"],
              "b" : [np.nan,np.nan,3,np.nan,np.nan,np.nan,np.nan,7]})
data.select([pl.col("a"), pl.col("b").backward_fill().forward_fill().over(pl.col("a")).flatten()])

![image](https://user-images.githubusercontent.com/19631334/146968239-a09c1b49-fa16-4006-8b15-37cb924c19a4.png)

When I replace np.nan with None

`data = pl.DataFrame({"a":  ["r","r","r","r","s","s","s","s"],
              "b" : [None,None,3,None,None,None,None,7]})
data.select([pl.col("a"), pl.col("b").backward_fill().forward_fill().over(pl.col("a")).flatten()])
`
![image](https://user-images.githubusercontent.com/19631334/146968377-ced40b7c-a9fc-4243-9142-472eba623225.png)

I believe backward_fill and forward_fill should fill np.nan values. Is it possible to change the behaviour of these functions in next releases? maybe a parameter can be added to control the behaviour of this function.

Thanks.

**Comment by ritchie46** [comment]
> I believe backward_fill and forward_fill should fill np.nan values

`NaN` is a special member of the floating point number system `Not a Number`. `backward_fill` and `forward_fill` fill missing data. Not members of a number system.

So if you want `NaN`s to be replaced by `backward_fill`  you need to treat `NaN` as any other number in the floating point system.

You can replace the `NaN` with `None` to make `backward_fill` work:
`pl.when(pl.col("b").is_nan()).then(None).otherwise(pl.col("b"))`

**Comment by hakantekbas** [comment]
Thanks for explanation. I will ask another question about polars. pl_from_pandas and pl.to_pandas. Is polars creating a new object or using existing objects when these methods are called. When I check the duration of this methods, they are very fast.

**Comment by mhconradt** [comment]
@ritchie46 on a similar note it would be nice if aggregations didn't propagate `NaN` values:

```python
pl.Series([2.0, float('nan')] * 21).sum()
# nan

pl.Series([2., None] * 21).sum()
# 42.0
```

The alternative is

```python
s =  pl.Series([2.0, float('nan')] * 21)
s[s.is_nan()] = None
s.sum()
# 42.0
```

Is there a simple way to do this while preserving the distinction between `null` and `NaN` elsewhere?

**Comment by ritchie46** [comment]
> Is there a simple way to do this while preserving the distinction between null and NaN elsewhere?

Use expressions, they never mutate the original `DataFrame`.

```python
s =  pl.Series([2.0, float('nan')] * 21)
pl.select(pl.lit(s).fill_nan(None).sum()).to_series()
```

> @ritchie46 on a similar note it would be nice if aggregations didn't propagate NaN values:

I think its consistent with the `+` operation on `NaN`, e.g. `1.0 + NaN = Nan`. So if you want missing behavior, you need to convert `NaN` to `None`.

**Comment by ritchie46** [comment]
> Thanks for explanation. I will ask another question about polars. pl_from_pandas and pl.to_pandas. Is polars creating a new object or using existing objects when these methods are called. When I check the duration of this methods, they are very fast.

No, data is copied into polars. We utilize pyarrow for this and they have gone through great efforts to make the conversion fast.
