### ISSUE TITLE
Create a DataFrame with a particular schema 

### ISSUE THREAD

**Issue by a-agmon** [pola-rs/polars#2135]
Hi, 
Is there a way to create a dataframe with a certain schema, and avoid independently setting the dtype of each col?
I an required to to generate a dataframe from a 2D numpy array. I was hoping to be able to so something like this: 

```python
new_df = pl.DataFrame(
      array_2d
     ,columns=columns
    ,dtypes=dtypes #or schema=schema
)
```
To add more details - I actually have multiple 1 row polar dataframes in a list that I want to merge
Most efficient way I found to do this is to call to_numpy() on each, generate a list of rows and then creating a new polar DF using this list of list. Would be happy to hear about any better direction

Thanks much!

**Comment by zundertj** [comment]
> To add more details - I actually have multiple 1 row polar dataframes in a list that I want to merge

Have you tried `concat` yet? See https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.concat.html?highlight=concat#polars.concat

That seems easier than trying to cast to numpy. For example:


```python
import polars as pl
df1 = pl.DataFrame({"a": [1], "b": [3]})
df2 = pl.DataFrame({"a": [2], "b": [4]})
df = pl.concat([df1, df2])
```

sets df to:
```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 4   │
└─────┴─────┘
```

**Comment by a-agmon** [comment]
@zundertj  - works like magic and issue solved! 
Thanks
