### ISSUE TITLE
DataFrame getitem vs setitem with integer argument

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#2155]
I noticed an inconsistency between get and set item, where for get it refers to the row location, and for set to column location

```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [1, 2], "b": [3, 4]})
>>> df
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 4   │
└─────┴─────┘
>>> df[0]
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
└─────┴─────┘
>>> df[0] = pl.Series([5,6])
>>> df
shape: (2, 2)
┌─────┬─────┐
│     ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 5   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 4   │
└─────┴─────┘
```

To me,  the `__setitem__` behaviour is the more counter intuitive one. Usually, one would refer to a specific column using the column name. The tests also do not cover that use. So I would propose to remove the `__setitem__` behaviour. If one wants to set a specific column, we could build in support by allowing `df[:, 0]` instead, which is unambigious whether the 0 refers to the column or row. Note that this syntax is currently not supported.

**Comment by ritchie46** [comment]
I agree. The `__setitem__` behavior can be removed what I am concerned.

**Comment by universalmind303** [comment]
in node, the dataframe is only gettable and settable via the columns, either named or indexed (you have to use `df.row(0)` for row access
`df[0]` or `df['a']`

`df['a'] = pl.Series([5,6])`
`df[0] = pl.Series([5,6])`

if the column index setter (`df[0] = ...`) is removed from python, should it also be removed in node?

**Comment by ritchie46** [comment]
> if the column index setter (df[0] = ...) is removed from python, should it also be removed in node?

Yes, the setitem implementation is archaich. Now the indexing with number should always be row l, column order.

And setting is preferred as `df.with_column`.
