### ISSUE TITLE
Null values interfere with csv typing

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2175]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.11.0

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

Null values in CSVs cause those columns to be interpreted as strings even though the rest of the values are numbers.

#### What are the steps to reproduce the behavior?

`foo.csv`
```
a,b
1,2
3,NA
5,6
```

```
> pl.read_csv('foo', null_values='NA').dtypes
[<class 'polars.datatypes.Int64'>, <class 'polars.datatypes.Utf8'>]
```

#### What is the expected behavior?

The second column should be interpreted as an int

**Comment by ritchie46** [comment]
Thanks for the report, will take a look.
