### ISSUE TITLE
dsl::extend cant be implemented in JS

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#2176]
the python implementation uses some `move`s that can not be done in JS. 

however, if we were to create an `extend` method in the core rust module that accepted an Expr, it could be implemented.

**Comment by ritchie46** [comment]
Couldn't you match to number, bool, string .. etc?

And then move these types in the closure and create the AnyValue?

**Comment by universalmind303** [comment]
yeah i just realized i can do that, so i closed it out.  its a little more verbose, but ends in the same result.

**Comment by ritchie46** [comment]
> yeah i just realized i can do that, so i closed it out. its a little more verbose, but ends in the same result.

Could maybe also create an owned version if AnyValue for ergonomics.

**Comment by universalmind303** [comment]
> Could maybe also create an owned version if AnyValue for ergonomics.

yeah thats a great idea.
