### ISSUE TITLE
python requirements : typing-extensions

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2185]
typing-extensions under 4.0 version has no ```TypeGuard```

typing-extensions>=4.0.0

**Comment by zundertj** [comment]
Thank you for reporting this, `TypeGuard` is indeed a recent addition to `typing-extensions`, and we had not lower limit on the version. I can't find a changelog for the package mentioning the introduction in 4.0.0, it may be that it was added already in 3.10.0, still pushing for making v4 the lower limit: #2186.

**Comment by yutiansut** [comment]
sorry for mistaking version .....
