### ISSUE TITLE
Proposal: Drop Python 3.6 support

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#2188]
Running into problems with #2187 , where I need a more recent numpy version (at least in CI, not requiring this for end users!) than that is available for Python 3.6.

Given Python 3.6 is EOL as of end of this month (https://www.python.org/dev/peps/pep-0494/#lifespan), I think it is reasonable to drop support.

**Comment by ritchie46** [comment]
I have been googling a bit and it seems reasonable. Pandas will drop python 3.6 support end of this month as well. And I see that google colab and kaggle notebook environments have gone to python 3.7 now.

At the moment still ~15% of our downloads run on python 3.6, but these environments will likely update.
