### ISSUE TITLE
[Question]: how to  extract a DataFrame with list vec to a plain DataFrame?

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2196]
## Background

in a lazy DataFrame func, many agg func may cause a list result, so the return value may be something like:

<img width="808" alt="f41dde6ceb9e6ffb15a067c70ec9783" src="https://user-images.githubusercontent.com/11537812/147536886-3fdb724c-cb63-4d5c-b106-a7f884ff3fb9.png">

in the dataFrame we can use the Sereis as a return res so that they can be calc as a DataFrame after groupby apply

something like :

df.groupby('date').apply( x.pct_change())  --> if the return value as a same length Series type , it can still return a dataFrame

so is there any way to covert the DataFrame with a Vec<Series>  instead of Vec<Series<list>>

**Comment by ritchie46** [comment]
Sorry, I don't fully understand.

**Comment by yutiansut** [comment]
![image](https://user-images.githubusercontent.com/11537812/147538961-a3ece0b4-42a3-4ad6-bcae-f78b5d534315.png)
maybe something like this?

**Comment by ritchie46** [comment]
Nope, I  still don't. What do you want to do? Maybe you could show in pandas?

**Comment by yutiansut** [comment]
![image](https://user-images.githubusercontent.com/11537812/147571834-739c0957-2a56-42f3-8ce5-8f35eb912720.png)
```python
test = pd.DataFrame([['a', [1,2,3]], ['b', [1,2,3]], ['x', [1,2,3]]], columns=['x','y'])
test
test.set_index('x').y.apply(lambda x: pd.Series(x))
```

**Comment by yutiansut** [comment]
oh may the api is ```explode```, thanks anyway
