### ISSUE TITLE
Sort merge join

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#22]
Sort merge join can be faster than hash join when Series are sorted and maybe when they are not.

**Comment by nixar0x0** [comment]
Can take up this issue and work on it if you are not working on it .

**Comment by ritchie46** [comment]
Be my guest! :)

**Comment by ErikDeSmedt** [comment]
Just wanted to highlight that sorted-joins do not require exact matches.

There is a large benefit for timeseries analysis here. It is often useful to join two dataframes on timestamp (non-exact) matches 

A simple example would be to see which person would get on what bus from the two data-sets provided below. Here you want to join on timestamp (non-exact) and bus-stop to find out which passenger boarded on what bus.

**Bus stops**

| Timestamp | bus | stop |
|------|-------| --- |
| 14:00 | Bus A | Stop 1 |
| 14:10 | Bus B | Stop 2 |
| 14:15 | Bus A | Stop 2 |
| 14 :20 | Bus A | Stop 3 |
 
**Passenger**
| Timestamp | Passenger |  stop |
|------| ---- |
| 14:02 | John | Stop 3 |
| 14:09 | Brad | Stop 2 |

**Comment by ritchie46** [comment]
I can understand this can be useful, but has this got a name? This isn't exactly a join? Feels like a bucket search or something like that.

**Comment by ErikDeSmedt** [comment]
Such an operation is often named `as_of_join`. Existing implementations are [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html) and [flint](https://www.twosigma.com/articles/introducing-flint-a-time-series-library-for-apache-spark/) which provides an implementation on top of Spark.

**Comment by ritchie46** [comment]
out of scope.

**Comment by ritchie46** [comment]
> Such an operation is often named as_of_join.

Btw. as_of_join is implemented. :)
