### ISSUE TITLE
Polar Python Date parse issue beyond year 2300

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2208]
Hi,
If i use version 0.9.12 which i believe is the version that uses Date32/64, TimeStamp, then there is no issue using strptime to parse any date, that has years like 2300 or 9999. However, if i use version that is migrated to use Polar's Date/Datetime (which i believe is past October 8 or > 0.9.12), then parsing is an issue

import polars as pl

def date_test():
	s = pl.Series("a", ["2300-01-01"])
	s= s.str.strptime(pl.Date) or s.str.strptime(pl.Date, fmt="%Y-%m-%d")
	print(s)
	
Output: 1715-06-16
Expected: 2300-01-01

The above code works using pl.Date32

**Comment by ritchie46** [comment]
Yes, currently the `Datetime` type is only backed by nanoseconds. We are working on more time units.

If you want larger years you need to use the `Date` type for now.

**Comment by NarayanB** [comment]
Hi Ritchie,
Bit confused. The above code i have is using pl.Date which is parsed as an invalid date, Is there an example for large years ? After using latest version, there is no option for me to use Date32/64/Timestamp right ?

**Comment by ritchie46** [comment]
I wil make sure this issue is resolved in #2209

**Comment by NarayanB** [comment]
Thanks!

**Comment by ritchie46** [comment]
Fixed.

**Comment by NarayanB** [comment]
Awesome. Thanks for the quick turnaround.
