### ISSUE TITLE
how to [get single value by index]  in Series while in a loop

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2223]
the code in Series.rs
```rust
    /// Get a single value by index. Don't use this operation for loops as a runtime cast is
    /// needed for every iteration.
    fn get(&self, _index: usize) -> AnyValue {
        invalid_operation_panic!(self)
    }

    /// Get a single value by index. Don't use this operation for loops as a runtime cast is
    /// needed for every iteration.
    ///
    /// # Safety
    /// Does not do any bounds checking
    unsafe fn get_unchecked(&self, _index: usize) -> AnyValue {
        invalid_operation_panic!(self)
    }
```
and i can't find how to get a single value in a loops with a recommend way

the request is :

iter the row of data[can't using parllism], for example : a strategy backtest need a iterrow() like func to feed the data in a columlike slice

I write a Account Struct and need to get the feed data to run a backtest, so i rewrite a ```get_row``` methods 

```rust
   pub fn get_row_vec(data:&DataFrame, idx: usize) -> Vec<AnyValue> {
        let values = data.iter().map(|s| s.get(idx)).collect::<Vec<_>>();
        values
    }
```
and use this func get the columns --> vec 

```
    let mut account = Account:new();
    for i in 0..rank4.height(){
        let t = get_row_vec(&rank4, i);
        let code:String = t.get(0).unwrap().0.clone();
        let datex:String = t.get(0).unwrap().1.clone();
        println!("{}-{}", code, datex);



        Account.send_order........



    }
```
and i found out that the get methods in a Series is not sugget in a loop

**Comment by yutiansut** [comment]
maybe something like a Better api to iter_rows()  in pandas, with a optimized way in a loop[sometime things can't be analysis as a vectorize way]

**Comment by yutiansut** [comment]
@ritchie46

**Comment by ritchie46** [comment]
You must downcast to a `ChunkedArray` and then use iterators or acces using `get`

**Comment by yutiansut** [comment]
i found out a new way:

```rust

    let closes = rank4["close"].f32().unwrap();
    let codes = rank4["order_book_id"].utf8().unwrap();
    let dates = rank4["date"].utf8().unwrap();
    for (code, (close, date)) in codes.into_iter().zip((closes.into_iter().zip(dates.into_iter()))) {

        let code2: &str =code.unwrap();
        let date2 :&str= date.unwrap();
        let close2 :f32 =close.unwrap();
    }
```

in a test with 3000000 column dataframe it just cost time 454.5µs

**Comment by yutiansut** [comment]
maybe this can be add to ```row``` feature like a ```iter_row``` api?  @ritchie46

**Comment by ritchie46** [comment]
I will close this as this is perfectly doable in the current API.
