### ISSUE TITLE
Memory Issues/SegFault when using expr.is_in()

### ISSUE THREAD

**Issue by KevDAll** [pola-rs/polars#2234]
#### Are you using Python or Rust?
**Python**

#### Which feature gates did you use?

N/A

#### What version of polars are you using?
0.10.27 (and tested on 0.12.7)

#### What operating system are you using polars on?

Windows 10.0.19043 and Ubuntu 20.04.1 LTS (Docker Container hosted on CentOS)

#### Describe your bug.
When attempting to filter expression within aggregation context using expr.is_in().count() I receive several different types of errors, even when running the same code multiple times.  

The errors are either:
- memory allocation of 3885281183856 bytes failed  (This is from the code below, should not be that resource intensive
  Process finished with exit code -1073740791 (0xC0000409)
- segmentationFault(core dumped)
- py03_runtime.PanicException: called `Option::unwrap()` on a `None` value

This does not occur using the same expr.is_in([]) expression in:
- select context
- filter context outside of select/aggregation
- filter on an expression within select context

Or when implementing the same logic using "|"  

(See snippet below)

#### What are the steps to reproduce the behavior?

**Example**

```python
import polars as pl

values = [''] * 184756 + ['true'] * 341 + ['false'] * 21
id = list(range(184756 + 341 + 21))
test_df = pl.DataFrame([pl.Series('string_value', values), pl.Series('id', id)])
test_df.select(pl.col('string_value').is_in(['true', '']))
print('select succesful')
test_df.filter(pl.col('string_value').is_in(['true', ''])).select([pl.col('id').count()])
print('Filtering outside of aggregation context sucessful')
test_df.select([pl.col('id').filter(pl.col('string_value').is_in(['true', ''])).count()])
print('Filtering by column successful in SELECT context')
test_df.groupby('id').agg(pl.col('id').filter(((pl.col('string_value') == 'true') |
                                                (pl.col('string_value') == ''))).count())
print('Same Logic Using OR successful')
test_df.groupby('id').agg(pl.col('id').filter(pl.col('string_value').is_in(['true', '']))).count()
```

Note:  in this instance the groupby behavior is redundant but in the "real data" problem where I first hit this there can be multiple rows for each id. 

#### What is the actual behavior?
See Snippet above:

Possible Errors:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\git\checkouts\arrow2-8a2ad61d97265680\25a35f8\src\array\utf8\mutable.rs:608:42
stack backtrace:
   0:     0x7fffd8fc2bd4 - rust_eh_personality
   1:     0x7fffd81fec8a - BrotliDecoderVersion
   2:     0x7fffd8fc1478 - rust_eh_personality
   3:     0x7fffd8fc1c95 - rust_eh_personality
   4:     0x7fffd8fc0e9b - rust_eh_personality
   5:     0x7fffd8fd0be3 - rust_eh_personality
   6:     0x7fffd8fd0b79 - rust_eh_personality
   7:     0x7fffd8fd0b34 - rust_eh_personality
   8:     0x7fffd90a9860 - rust_eh_personality
   9:     0x7fffd90a99bc - rust_eh_personality
  10:     0x7fffd89a6fe6 - rust_eh_personality
  11:     0x7fffd8e83ab7 - rust_eh_personality
  12:     0x7fffd8f156f6 - rust_eh_personality
  13:     0x7fffd8ee0dde - rust_eh_personality
  14:     0x7fffd8e836f8 - rust_eh_personality
  15:     0x7fffd8e8172f - rust_eh_personality
  16:     0x7fffd8e80e21 - rust_eh_personality
  17:     0x7fffd8e808a2 - rust_eh_personality
  18:     0x7fffd9120215 - rust_eh_personality
  19:     0x7fffd8f41841 - rust_eh_personality
  20:     0x7fffd8f411f5 - rust_eh_personality
  21:     0x7fffd8fd15dc - rust_eh_personality
  22:     0x7ff88f207034 - BaseThreadInitThunk
  23:     0x7ff8911c2651 - RtlUserThreadStart
Traceback (most recent call last):
  File "bug_test_polars.py", line 15, in <module>
    test_df.groupby('id').agg(pl.col('id').filter(pl.col('string_value').is_in(['true', '']))).count()
  File "C:\Users\kevin.alland\Anaconda3\envs\bikeride\lib\site-packages\polars\internals\frame.py", line 4242, in agg
    wrap_df(self._df)
  File "C:\Users\kevin.alland\Anaconda3\envs\bikeride\lib\site-packages\polars\internals\lazy_frame.py", line 326, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

```
memory allocation of 140100115764088 bytes failed
```

```
SegmenationFault(core dumped)
```

#### What is the expected behavior?

Run this code successfully without memory issues.

**Comment by KevDAll** [comment]
Note we could also add to the test:

```
test_df.with_column(pl.col('string_value').is_in(['true', '']).alias('string_cond'))\
       .groupby('id').agg(pl.col('id').filter(pl.col('string_cond') == True).count())
print('Same Logic making column outside of aggregation context successful')
```

Showing that we can first create a new column on the string condition then filter on that boolean column without memory issues, which is a valid work around.  I honestly don't fully under the COW semantics, not sure if this would result in a full copy or just the memory to create a boolean column.

**Comment by zundertj** [comment]
I have been able to reproduce this, most of the time it is the `memory allocation` error popping up. Note that it is already triggered for this very small input:

```python
test_df = pl.DataFrame({"string_value": ["", "true", "false"],  "id": [0, 1, 2]})
```

**Comment by ritchie46** [comment]
In will take a look.

**Comment by ritchie46** [comment]
I know the cause of this. The fix is not easy. Will take a look tomorrow.
