### ISSUE TITLE
pivot

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2262]
Hi;

> GroupBy.pivot(pivot_column: str, values_column: str) → polars.internals.frame.PivotOps

pivot  command only accepts one field in both values and pivot columns. Passing more than one column can be make some calculations easier in some cases. After pivot command, I expect to see fields ordered( especially integer or date fields). Is there any way to arrange the order of columns in pivot function?

**Comment by hakantekbas** [comment]
If we can add it will help in some cases. I know this issue will not be a good place to ask but I have another question. Is there any known open issue with round function. First one is throwing error. Second one is working. I wonder applying round in aggregate expression like option 1 can cause a problem.

```
dataFrame.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                  .agg([ pl.col("review_count").sum().alias("comment_count"), 
                           ( (pl.col("review_count")*pl.col("average_point")).sum() / pl.col("review_count").sum()).round(2).alias("point") ])  \
                             .sort(["country","date"],reverse=[True,False])
```


```
dataFrame.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                  .agg([ pl.col("review_count").sum().alias("comment_count"), 
                           ( (pl.col("review_count")*pl.col("average_point")).sum() / pl.col("review_count").sum()).alias("point") ])  \
                             .sort(["country","date"],reverse=[True,False]).with_column(pl.col("point").round(2))
```

**Comment by ritchie46** [comment]
> I know this issue will not be a good place to ask but I have another question. Is there any known open issue with round function. First one is throwing error. Second one is working. I wonder applying round in aggregate expression like option 1 can cause a problem.

This may be a bug. Can you open a new issue with the data that produces the error?
And can you update polars and see if this still is the case?

**Comment by hakantekbas** [comment]
it is the latest version. I will try to replicate with small data.  I usually have to deal with more than 5 millions rows data. I sometimes can't replicate with small data. Is there any other way to determine causes of these bugs in large datasets?

**Comment by zundertj** [comment]
Please note that the discussion on the round function has been moved to #2264; this issue is only for the pivot on multiple columns + sorting.
