### ISSUE TITLE
In aggregate function Round produces error in some cases

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2264]
I'm using latest version, 0.12.8

First one is throwing error. Second one is working. 

```
dataFrame.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                  .agg([ pl.col("review_count").sum().alias("comment_count"), 
                           ( (pl.col("review_count")*pl.col("average_point")).sum() / pl.col("review_count").sum()).round(2).alias("point") ])  \
                             .sort(["country","date"],reverse=[True,False])
```

```
dataFrame.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                  .agg([ pl.col("review_count").sum().alias("comment_count"), 
                           ( (pl.col("review_count")*pl.col("average_point")).sum() / pl.col("review_count").sum()).alias("point") ])  \
                             .sort(["country","date"],reverse=[True,False]).with_column(pl.col("point").round(2))
```
Second one is sometimes creating this results. All denominator should be higher than 0. This expression should not produce inf. 

![image](https://user-images.githubusercontent.com/19631334/148108936-cec03ea9-2bcf-4921-ac5c-1e32a2ee0f5b.png)

**Comment by hakantekbas** [comment]
I created small test sample. I could not replicate same error. But first one is aggregated value, second one is creating list.

Sample Data

testData = pl.from_dict({"country":["France","France","France"],
                "tip":["source","source","source"],
                "segment_title":["Google","Google","Google"],
                "date":[datetime(2021,9,2),datetime(2021,9,1),datetime(2021,9,3)],
                "review_count":[1157,1106,1093],
                "ortalama_puan":[86.74157303370787,85.91320072332731,86.67886550777676 ] })  


testData.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                                          .agg([ pl.col("review_count").sum().alias("Yorum_Sayisi"), 
                                            ( (pl.col("review_count")*pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()).alias("puan") ])  \
                                          .sort(["country","date"],reverse=[True,False]).with_column(pl.col("puan").round(2))


testData.groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
                                          .agg([ pl.col("review_count").sum().alias("Yorum_Sayisi"), 
                                            ( (pl.col("review_count")*pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()).round(2).alias("puan") ])  \
                                          .sort(["country","date"],reverse=[True,False])

**Comment by zundertj** [comment]
It would still be good to have a small example that does fail. Some ideas to produce it:
1. does the error also occur if you remove the `  .sort(["country","date"],reverse=[True,False])` at the end? If so, please drop it.
2. does the error also occur if you remove the first agg expression ` pl.col("review_count").sum().alias("Yorum_Sayisi")`? If so, please drop it.
3. you report `inf` values in the column `puan` in your first post, but your code does not have that column I think? Did you mean `point`?
4. you report `inf`, for I guess `point` (see my point 3). Given the formula is `(pl.col("review_count")*pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()`, could you report `pl.col("review_count").sum()` separately? I see there is an alias `review_count`, which is exactly that expression, but it is not reported. 

General remark: please align naming of your code and the output you are showing.

**Comment by hakantekbas** [comment]
@zundertj  

I tried 1st and 2nd option. Result is same. In third item, data is coming from another dataset. As I'm dividing one column to another, I checked whether there is a zero valued cell. If there is a zero valued data, second option should also produce infinity. 

I want to ask why round is collecting data to list. Is it expected behaviour?

Thanks.

**Comment by ritchie46** [comment]
If we cannot reproduce the error its unlikely we can fix it. Can you come up with a minimal working example/

**Comment by hakantekbas** [comment]
But in minimal example, result is different. first one is returning value. Second one is returning list.  I believe list type is not expected

**Comment by ritchie46** [comment]
Ok, I will take a look.

**Comment by hakantekbas** [comment]
Thanks @ritchie46. I can replicate error now.

Sample Data
```
testData = pl.from_dict({"country":np.random.choice(['fast', 'rabbit', 'pigeon', 'Chris'],30000),
                         "tip":np.random.choice(['src', 'org', 'lan', 'ds'],30000),
                         "segment_title":np.random.choice(['pds1', 'yrow2', 'fsw2', 'tyxgs'],30000),
                         "date":np.random.choice(np.arange("2021-09-01","2021-12-21",dtype="datetime64[D]"),30000).tolist(),
                         "review_count": np.random.randint(20,10302,30000),
                         "ortalama_puan": np.random.uniform(low=0, high=1, size=(30000,))})  
```
Main code that throws error
```
testData.filter(pl.col("tip")=="src") \
        .groupby([pl.col("country"), pl.col("date").dt.strftime("%Y%m")]) \
        .agg([ pl.col("review_count").sum().alias("Yorum_Sayisi"), 
               ((pl.col("review_count")*pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()).round(2).alias("puan") ])  \
        .sort(["country","date"],reverse=[True,False])
```

If I run the code above, first it will generate this output. there are some inf values but sample data should not generate this inf values.
shape: (16, 4)
```
┌─────────┬────────┬──────────────┬───────────────────────┐
│ country ┆ date   ┆ Yorum_Sayisi ┆ puan                  │
│ ---     ┆ ---    ┆ ---          ┆ ---                   │
│ str     ┆ str    ┆ i64          ┆ list [f64]            │
╞═════════╪════════╪══════════════╪═══════════════════════╡
│ rabbit  ┆ 202109 ┆ 2813306      ┆ [0.49, inf, ... inf]  │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ rabbit  ┆ 202110 ┆ 2665884      ┆ [inf, inf, ... inf]   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ rabbit  ┆ 202111 ┆ 2531000      ┆ [0.46, inf, ... inf]  │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ rabbit  ┆ 202112 ┆ 1724935      ┆ [0.48, 0.95, ... inf] │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...     ┆ ...    ┆ ...          ┆ ...                   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Chris   ┆ 202109 ┆ 2593826      ┆ [0.5, inf, ... inf]   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Chris   ┆ 202110 ┆ 2479541      ┆ [0.47, 0.5, ... inf]  │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Chris   ┆ 202111 ┆ 2590200      ┆ [inf, inf, ... inf]   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Chris   ┆ 202112 ┆ 1715230      ┆ [0.33, inf, ... inf]  │
└─────────┴────────┴──────────────┴───────────────────────┘
```


Generally In second or third attempt (you should try up to 10 times), I see error message but I can't see beginning of error message. I'm also adding part of error message below.

> 000000000000000000000000000000, 55536302300720890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 14172422830461630000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 73462903966385770000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 10223170819282780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 10223170819282780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 73462903966385770000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 55536302300720890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 55536302300720890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 1678974171322098000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 10223170819282780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 14172422830461630000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 471283047253300900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 73462903966385770000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 6978437338817228400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 55536302300720890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 14172422830461630000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 14445476473311828000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 18656715616144170000000000000000, 22606842861523384000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 322954829279226300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 2513047825944179500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000002800864612859525, 1384977085689898700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 3162523578800728000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000044057086586111556, 99272355183028260000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035434087, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`

**Comment by zundertj** [comment]
Great, that really helps. Using your data, I applied the steps I mentioned above, and some more tinkering, and can now reliably reproduce:

```python
import polars as pl
import numpy as np

testData = pl.from_dict({"country": np.random.choice(['fast', 'rabbit', 'pigeon', 'Chris'], 30000),
                         "tip": np.random.choice(['src', 'org', 'lan', 'ds'], 30000),
                         "review_count": np.random.randint(20, 10302, 30000),
                         "ortalama_puan": np.random.uniform(low=0, high=1, size=(30000,))})

for n in range(100):
    # applying .filter(pl.col("tip")=="src") to testData first leads to stacktrace
    # But if not, it still errors (simply no stack trace)
    result = testData.filter(pl.col("tip") == "src").groupby([pl.col("country")]) \
        .agg(((pl.col("review_count") * pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()).round(2))
```
Where the `for`-loop is there to make sure it gets triggered at some point. Note that the `filter` does affect whether you get a stacktrace back or not, but does not seem to affect whether anything is wrong or not.


The error occurs because of the combination of dividing by `pl.col("review_count")` and applying `round`, because this always passes:
```python
for n in range(100):
    # no round
    result = testData.filter(pl.col("tip") == "src").groupby([pl.col("country")]) \
        .agg((pl.col("review_count") * pl.col("ortalama_puan")).sum() / pl.col("review_count").sum())
     
     # no division
     result = testData.filter(pl.col("tip") == "src").groupby([pl.col("country")]) \
      .agg((pl.col("review_count") * pl.col("ortalama_puan")).sum().round(2))

```

Hope this can help put @ritchie46  on the right track.

**Comment by ritchie46** [comment]
Thanks @zundertj!!
