### ISSUE TITLE
ValueError: Cannot construct Series from sequence of <class 'list'>.

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#2278]
#### Are you using Python or Rust?
python

#### What version of polars are you using?
0.12.8

#### What operating system are you using polars on?
ubuntu18.04

```
import pandas as pd
#
pd.DataFrame(
     {
         "letters": ["c", "c", "a", "c", "a", "b"],
        "nrs": [[[1], 2], [1, 3], [4, 3], [5, 5, 5], [6], [2, 1, 2]],
    }
 )
'''
	letters	nrs
0	c	[[1], 2]
1	c	[1, 3]
2	a	[4, 3]
3	c	[5, 5, 5]
4	a	[6]
5	b	[2, 1, 2]
'''
pl.DataFrame(
     {
         "letters": ["c", "c", "a", "c", "a", "b"],
        "nrs": [[[1], 2], [1, 3], [4, 3], [5, 5, 5], [6], [2, 1, 2]],
    }
 )
'''
ValueError: Cannot construct Series from sequence of <class 'list'>.
'''


```

**Comment by ritchie46** [comment]
A temporary workaround is install pyarrow.

**Comment by ztsweet** [comment]
Is already installed  pyarrow=6.0.1

**Comment by ritchie46** [comment]
Sorry, I meant create a listarray via pyarrow. This still is something we should fix though.

**Comment by ztsweet** [comment]
oh,thanks

**Comment by ritchie46** [comment]
You have different dimensions. Your first value in the first list is of type `list` where the second value is of `type` integer. This will never be supported by polars as an array can only have a single dtype.

**Comment by ritchie46** [comment]
Cloes by #2297
