### ISSUE TITLE
RuntimeError: Any(InvalidOperation("cannot explode dtype: Object(\"object\")"))

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#2280]
#### Are you using Python or Rust?

python

#### What version of polars are you using?
0.12.8

```
pl.DataFrame({'a':[['1','1'],['2','2']],'b':['1','2']}).explode('a')
'''
a	b
str	str
"1"	"1"
"1"	"1"
"2"	"2"
"2"	"2"
'''
```
```
pl.DataFrame({'b':['1','2']}).with_columns([pl.col('*'),pl.col('b').apply(lambda x:[x]*2).alias('a')]).explode('a')
'''
RuntimeError: Any(InvalidOperation("cannot explode dtype: Object(\"object\")"))
'''
```

**Comment by zundertj** [comment]
`explode` is not defined for dtype `Object`, as per the error message you show. This is triggered becasue

```python
>>> pl.DataFrame({'a':[['1','1'],['2','2']],'b':['1','2']})
shape: (2, 2)
┌────────────┬─────┐
│ a          ┆ b   │
│ ---        ┆ --- │
│ list [str] ┆ str │
╞════════════╪═════╡
│ ["1", "1"] ┆ 1   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ ["2", "2"] ┆ 2   │
└────────────┴─────┘
```

Whilst
```python
>>> pl.DataFrame({'b':['1','2']}).with_columns([pl.col('*'),pl.col('b').apply(lambda x:[x]*2).alias('a')])
shape: (2, 2)
┌─────┬────────────┐
│ b   ┆ a          │
│ --- ┆ ---        │
│ str ┆ object     │
╞═════╪════════════╡
│ 1   ┆ ['1', '1'] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ ['2', '2'] │
└─────┴────────────┘
```

I.e. `a` is of type Object, not List. See also the docs on explode: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.explode.html which says that `columns` should of type `LargeList` (I think this is the same as `pl.List`, but @ritchie46  can chime in if that is not the case).

The question is still how to make the apply + user-supplied function return a `pl.List`. Hope someone else can help with that.

**Comment by ritchie46** [comment]
An apply function should return a Series if we want the return type to be a list.

**Comment by zundertj** [comment]
For the sake of completeness, that means:

```python
df2.with_columns(pl.col('b').apply(lambda x: pl.Series([x] * 2)))
shape: (2, 1)
┌────────────┐
│ b          │
│ ---        │
│ list [str] │
╞════════════╡
│ ["1", "1"] │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ["2", "2"] │
└────────────┘
```

Which means you can change the final line of @ztsweet 's post into:
```python
pl.DataFrame({'b':['1','2']}).with_columns(pl.col('b').apply(lambda x:pl.Series([x]*2)).alias('a')).explode('a')
shape: (4, 2)
┌─────┬─────┐
│ b   ┆ a   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 2   │
└─────┴─────┘
```

Note that you cannot select the original column as well (`[pl.col('*'),...]`, because that causes dimensions issues.

**Comment by ztsweet** [comment]
@zundertj thanks
