### ISSUE TITLE
Improve printing of polars expressions

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#2284]
Is it possible to print unevaluated polars expressions in a way that show what the expression is?

Current

```python
col('x') * 2
# <polars.internals.expr.Expr at 0x7f8ac1059f10>
```

Proposed

```python
col('x') * 2
# col('x') * 2
```

**Comment by ritchie46** [comment]
Check `describe_plan` and `describe_optimized_plan` in `LazyFrame`

**Comment by zundertj** [comment]
The question here is about expressions stand-alone I think, i.e. before evaluation, not in the context of a dataframe/evaluation. This is a feature I have wondered myself about. It may make debugging easier to check that expressions have been constructed as intended. But I don't know if this is feasible at all, and it would be painful to print out an expression like

```python
pl.col("x").is_in(list(range(1000)))
```
Would it print out all values?

Not a major feature, but if it is easy to do, it would be helpful.

**Comment by ritchie46** [comment]
It's something that would be valuable indeed. Both for the logical plan as for the expressions. 

This has to be done in polars-lazy in rust by someone who has more patience and feel for esthetics than I do. 😅
