### ISSUE TITLE
Improve DataFrame display in Python

### ISSUE THREAD

**Issue by aeshirey** [pola-rs/polars#2288]
Within the REPL, Polars (v0.12.8) DataFrames generally display well (better in some regards than Pandas), but there are some quirks that would be great to improve upon. Opening [a sample dataset](https://www.kaggle.com/fedesoriano/heart-failure-prediction) in Python+Polars:

```
>>> heart = pl.read_csv('heart.csv')
>>> heart
shape: (918, 12)
┌─────┬─────┬─────┬───────────┬─────┬─────┬─────────┬──────────┬──────────────┐
│ Age ┆ Sex ┆ Che ┆ RestingBP ┆ ... ┆ Exe ┆ Oldpeak ┆ ST_Slope ┆ HeartDisease │
│ --- ┆ --- ┆ stP ┆ ---       ┆     ┆ rci ┆ ---     ┆ ---      ┆ ---          │
│ i64 ┆ str ┆ ain ┆ i64       ┆     ┆ seA ┆ f64     ┆ str      ┆ i64          │
│     ┆     ┆ Typ ┆           ┆     ┆ ngi ┆         ┆          ┆              │
│     ┆     ┆ e   ┆           ┆     ┆ na  ┆         ┆          ┆              │
│     ┆     ┆ --- ┆           ┆     ┆ --- ┆         ┆          ┆              │
│     ┆     ┆ str ┆           ┆     ┆ str ┆         ┆          ┆              │
╞═════╪═════╪═════╪═══════════╪═════╪═════╪═════════╪══════════╪══════════════╡
│ 40  ┆ M   ┆ ATA ┆ 140       ┆ ... ┆ N   ┆ 0.0     ┆ Up       ┆ 0            │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 49  ┆ F   ┆ NAP ┆ 160       ┆ ... ┆ N   ┆ 1       ┆ Flat     ┆ 1            │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
(some text omitted for brevity)

>>> heart[:3]
shape: (3, 12)
┌─────┬─────┬─────┬───────────┬─────┬───┬─────────┬──────────┬──────────────┐
│ Age ┆ Sex ┆ Che ┆ RestingBP ┆ ... ┆ E ┆ Oldpeak ┆ ST_Slope ┆ HeartDisease │
│ --- ┆ --- ┆ stP ┆ ---       ┆     ┆ x ┆ ---     ┆ ---      ┆ ---          │
│ i64 ┆ str ┆ ain ┆ i64       ┆     ┆ e ┆ f64     ┆ str      ┆ i64          │
│     ┆     ┆ Typ ┆           ┆     ┆ r ┆         ┆          ┆              │
│     ┆     ┆ e   ┆           ┆     ┆ c ┆         ┆          ┆              │
│     ┆     ┆ --- ┆           ┆     ┆ i ┆         ┆          ┆              │
│     ┆     ┆ str ┆           ┆     ┆ s ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ e ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ A ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ n ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ g ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ i ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ n ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ a ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ - ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ - ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ - ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ s ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ t ┆         ┆          ┆              │
│     ┆     ┆     ┆           ┆     ┆ r ┆         ┆          ┆              │
╞═════╪═════╪═════╪═══════════╪═════╪═══╪═════════╪══════════╪══════════════╡
│ 40  ┆ M   ┆ ATA ┆ 140       ┆ ... ┆ N ┆ 0.0     ┆ Up       ┆ 0            │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 49  ┆ F   ┆ NAP ┆ 160       ┆ ... ┆ N ┆ 1       ┆ Flat     ┆ 1            │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
```

It _appears_ that the display is trying to maximize vertical real estate used, which comes at the expensive of readability in column names.

At the same time, the displayed dataframe seems limited to 80 characters wide even when my terminal is wider. It could display more columns (and/or limit wrapping of column names) to maximize content and/or readability.

**Comment by ritchie46** [comment]
You can modify the default settings wuth the config or with env vars:

https://pola-rs.github.io/polars/py-polars/html/reference/config.html

Maybe this helps.

**Comment by aeshirey** [comment]
That definitely helps. By comparison, Pandas appears to detect terminal width and adjust display automatically. That'd be a nice feature for Polars, though it's just ergonomics.

**Comment by ghuls** [comment]
@aeshirey 

You can set it manually to your current terminal width:
```python
import polars as pl
from os import get_terminal_size

pl.Config.set_tbl_width_chars(get_terminal_size()[0])
```

Pandas does not seem to enable it all the time:
https://github.com/pandas-dev/pandas/blob/ffb554981558816195ae4a7ffe6d679c30da05d8/pandas/io/formats/console.py

**Comment by ritchie46** [comment]
> @aeshirey
> 
> You can set it manually to your current terminal width:
> 
> ```python
> import polars as pl
> from shutils import get_terminal_size
> 
> pl.Config.set_tbl_width_chars(get_terminal_size()[0])
> ```
> 
> Pandas does not seem to enable it all the time: https://github.com/pandas-dev/pandas/blob/ffb554981558816195ae4a7ffe6d679c30da05d8/pandas/io/formats/console.py

That's a handy snippet they've got. We could use that as well.

**Comment by aeshirey** [comment]
The distinction I'm trying to make is default, automatic behavior. Using a slightly wider dataset:

```python
>>> import pandas as pd
>>> import polars as pl
>>>
>>> nyc_pl = pl.read_csv('NYC.csv')
>>> nyc_pd = pd.read_csv('NYC.csv')
```

At the default zoom level, both Polars and Pandas do a reasonable job:

<img width="958" alt="default zoom" src="https://user-images.githubusercontent.com/1210458/148458171-6897254f-3455-4c89-9684-78ba96d29dab.png">

Zoomed out (with a wider terminal than normal), Pandas automatically makes use of this extra space, but Polars doesn't:

<img width="960" alt="zoomed out" src="https://user-images.githubusercontent.com/1210458/148458169-f4ff9957-e756-4a2c-8c9b-de508391e43b.png">


Zoomed in (with much less width than normal), Pandas scales back how much is displayed:

<img width="955" alt="zoomed in - pd" src="https://user-images.githubusercontent.com/1210458/148458163-74e57783-9839-43c4-bc36-12e561d5b199.png">

While Polars wraps and makes it difficult to read:

<img width="953" alt="zoomed in - pl" src="https://user-images.githubusercontent.com/1210458/148458166-9c87ecb9-90bd-4acc-85e9-f47443e5117f.png">

Using `pl.Config.set_tbl_width_chars` certainly works, but it does require the user manually set values. I'm proposing making this an automatic capability for ease-of-use.

**Comment by zundertj** [comment]
I could have a stab at this. I have been thinking about our `Config` class last week, that it is very ad-hoc and limited (no getters, not Pythonic with the `set_***` methods, no support for context managers for all configs, only StringCache, etc), and doing that work first to see if we can support this autoscaling feature would be a good step forward.  Would that be a good plan?

**Comment by stinodego** [comment]
This issue has been fixed.
