### ISSUE TITLE
Joining dataframes on int columns of different dtype fails

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2292]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.12.8

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

I'm not positive this isn't intended, but it was nonintuitive to me at least. When joining two dataframes on two int columns, one with type `i32` and the other with type `i64`, the join fails instead of casting the `i32` column to `i64` before attempting the join.

#### What are the steps to reproduce the behavior?

```
>>> df1 = pl.DataFrame({'first': [1,3], 'second': [2,4]}) ; df1
shape: (2, 2)
┌───────┬────────┐
│ first ┆ second │
│ ---   ┆ ---    │
│ i64   ┆ i64    │
╞═══════╪════════╡
│ 1     ┆ 2      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3     ┆ 4      │
└───────┴────────┘
>>> df2 = pl.DataFrame({'first': [1]}).with_column(pl.lit(2).alias('second')) ; df2
shape: (1, 2)
┌───────┬────────┐
│ first ┆ second │
│ ---   ┆ ---    │
│ i64   ┆ i32    │
╞═══════╪════════╡
│ 1     ┆ 2      │
└───────┴────────┘
>>> df1.join(df2, on='second')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 2715, in join
    return wrap_df(self._df.join(df._df, left_on_, right_on_, how, suffix))
RuntimeError: Any(ValueError("the dtype of the join keys don't match. first cast your columns to the correct dtype"))
>>> df2.join(df1, on='second')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 2715, in join
    return wrap_df(self._df.join(df._df, left_on_, right_on_, how, suffix))
RuntimeError: Any(ValueError("the dtype of the join keys don't match. first cast your columns to the correct dtype"))
```

**Comment by ritchie46** [comment]
This is as intended. You must cast your join columns to the same type.

**Comment by LiterallyUniqueLogin** [comment]
Then a quality of life improvement then would be to print out the columns and their types in the error message. As I was joining ints to ints which to my intuition should have worked, it wasn't clear what was going on; that would have made it more explicit.

**Comment by zundertj** [comment]
Maybe the message `Any(ValueError("the dtype of the join keys don't match. first cast your columns to the correct dtype"))` can include the dtypes detected? For instance, `Any(ValueError("the dtype of the join keys don't match (left=[i64], right=[i32]). first cast your columns to the correct dtype"))` 

But I do find the error message quite clear and helpful, it immediately points you to the dtypes of your join keys.

**Comment by austospumanto** [comment]
Additionally, I could see it being useful to point out the lowest possible upcast dtype for the two dtypes, and provide a code snippet to convert. 

For example, if left is Int64 and right is Int32 then the lowest possible upcast dtype is Int64 and the suggested snippet could be generated via the format string `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Int64)))"` or something like that. 

For left of Utf8 and right of Int64, the lowest possible upcast dtype would be Utf8 and the code would be `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Utf8)))"`. 

For Int64 and datetime[ns], the lowest possible upcast dtype would be Int64 and the code would be `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Int64)))"`.

Just a thought! :)

**Comment by ritchie46** [comment]
If anyone is willing to make a PR for this, sure. In my opinion a programmer should be a little type aware though.

**Comment by zundertj** [comment]
> Additionally, I could see it being useful to point out the lowest possible upcast dtype for the two dtypes, and provide a code snippet to convert.
> 
> For example, if left is Int64 and right is Int32 then the lowest possible upcast dtype is Int64 and the suggested snippet could be generated via the format string `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Int64)))"` or something like that.
> 
> For left of Utf8 and right of Int64, the lowest possible upcast dtype would be Utf8 and the code would be `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Utf8)))"`.
> 
> For Int64 and datetime[ns], the lowest possible upcast dtype would be Int64 and the code would be `f"left_df.join(right_df.with_column(pl.col('{right}').cast(pl.Int64)))"`.
> 
> Just a thought! :)

I think this is a bit much, and above all hard to get right. What happens when users follow the advice and cast the datetime to int64, and then find out they no longer have a datetime for the join key in the output? I can already see questions coming up about that. If we ever add suggested fixes to error messages, we better be sure they will solve the error in a transparent way in 99.9%+ of the cases.

I would much prefer the error message to be as clear as possible with what is wrong, and leave it up to the user to fix it. Hence my suggestion to output the dtypes for left and right keys detected as well, but that is a minor improvement.

**Comment by austospumanto** [comment]
Great points — I agree it's a bit much and likely not worth it / debatably desirable.

Separately, on the problem of two columns becoming one column in the join result: it would be great if polars could retain both columns in the join like pandas does (when the two columns have different names). This is useful for checking for nulls in non-inner joins to see which rows found matches, and also for situations like the one you stated. I find myself duplicating+suffixing columns before joining to get this behavior in polars.

**Comment by zundertj** [comment]
Could you create a new issue for that? To consider: it may be easier if we have `indicator` as an optional output as in Pandas https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html?highlight=merge#pandas.DataFrame.merge to do this.
