### ISSUE TITLE
Getting one element from a date series gives back the internal representation.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#2294]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.12.8

#### What operating system are you using polars on?

CentOS 7

#### Describe your bug.

Getting one element from a date series gives back the internal representation.
Same when converting whole series to arrow.

#### What are the steps to reproduce the behavior?

```python
In [164]: date_series = pl.Series("dates", ["2022-01-16", "2022-01-17"]).str.strptime(pl.Date, "%Y-%m-%d")

In [165]: date_series
Out[165]: 
shape: (2,)
Series: 'dates' [date]
[
	2022-01-16
	2022-01-17
]

In [166]: date_series[0]
Out[166]: 19008

In [167]: date_series[1]
Out[167]: 19009

In [168]: date_series[0:1]
Out[168]: 
shape: (1,)
Series: 'dates' [date]
[
	2022-01-16
]

In [169]: date_series.to_arrow()
Out[169]: 
<pyarrow.lib.Int32Array object at 0x7fb987dd2520>
[
  19008,
  19009
]

In [170]: date_series.to_numpy()
Out[170]: array(['2022-01-16', '2022-01-17'], dtype='datetime64[D]')

In [171]: date_series.to_list()
Out[171]: [datetime.date(2022, 1, 16), datetime.date(2022, 1, 17)]

In [190]: date_series.to_list(use_pyarrow=True)
Out[190]: [19008, 19009]


```

**Comment by slonik-az** [comment]
The internal representation seems to be counting days from the epoch
```python
In [48]: pl.Series("dates", ['1970-01-01', '1970-01-02',"1971-01-01"]).str.strptime(pl.Date, "%Y-%m-%d").to_arrow()
Out[48]:
<pyarrow.lib.Int32Array object at 0x103c19dc0>
[
  0,
  1,
  365
]
```

**Comment by mhconradt** [comment]
@ritchie46 this seems related to adding / subtracting `timedelta` and `datetime` literals as it involves whether to convert to an integer before passing the object over the FFI. 
One issue with this type erasure is, for example, subtracting a `datetime` from a `Datetime` series should yield a `Duration` series, whereas subtracting a `timedelta` from a `Datetime` series should yield a `Datetime` series. If you pass an integer through the FFI, the interpretation is ambiguous. It seems this part of the Python API could use some work.
One thing we might want to do is use instances of the datatypes instead of the classes, similar to Arrow and NumPy. This would allow us to pass time units through the FFI along with the data type. This doesn't precisely solve this problem, but could make it simpler to share type information across the FFI, especially since multiple data types now use time units.
```python
>>> pa.timestamp('us')
TimestampType(timestamp[us])
```
Another alternative is something like the pyarrow scalar types. This could be useful for simplifying arithmetic between scalars and series of logical types.
```python
>>> pc.subtract(pa.array([datetime(2021, 1, 1), datetime(2048, 1, 1)]), pa.scalar(datetime(2010, 1, 1)))
<pyarrow.lib.DurationArray object at 0x127174580>
[
  347155200000000,
  1199145600000000
]
```

**Comment by ritchie46** [comment]
Hmm.. Yes.. As it currently is implemented we get the internal representation if we index.

Except when we index on the special data namespaces. e.g. `date_series.dt[0]` returns a datetime/date object.

**Comment by ritchie46** [comment]
I don't know what a better solution is. We could also check for `Date/Datetime/Time` dtype in accessing normal series. This would make indexing a bit more expensive, but indexing already is an anti-pattern if it has to be performant.

**Comment by zundertj** [comment]
I raised this before (I think on Discourse, cant find a GH issue), but having to use `.dt` to access a meaningful representation is cumbersome. Of course, the internal presentation means something, but practically speaking. The interop in Python between polars and python datatypes is quite good, but this is one where I would like to see the behaviour change. But I thought this is waiting for a rewrite to make use of Arrow dates & datetimes?

**Comment by ghuls** [comment]
BTW getting the index with get_idx, gives the datatype back.
```
In [1]: import polars as pl

In [2]: date_series = pl.Series("dates", ["2022-01-16", "2022-01-17"]).str.strptime(pl.Date, "%Y-%m-%d")

In [3]: date_series[0]
Out[3]: 19008

In [4]: date_series._s.get_idx(0)
Out[4]: datetime.date(2022, 1, 16)

In [5]: date_series._s.get_idx(1)
Out[5]: datetime.date(2022, 1, 17)
```

**Comment by ritchie46** [comment]
> BTW getting the index with get_idx, gives the datatype back.
> 
> ```python
> In [1]: import polars as pl
> 
> In [2]: date_series = pl.Series("dates", ["2022-01-16", "2022-01-17"]).str.strptime(pl.Date, "%Y-%m-%d")
> 
> In [3]: date_series[0]
> Out[3]: 19008
> 
> In [4]: date_series._s.get_idx(0)
> Out[4]: datetime.date(2022, 1, 16)
> 
> In [5]: date_series._s.get_idx(1)
> Out[5]: datetime.date(2022, 1, 17)
> ```

Good observation. We now implemented `AnyValue` to `PyObject` properly, so this logic in  `__getitem__` can be removed:

```python
         if self.dtype in (PlList, Date, Datetime, Duration, Object):
                f = get_ffi_func("get_<>", self.dtype, self._s)
                if f is None:
                    return NotImplemented
                out = f(item)
                if self.dtype == PlList:
                    if out is None:
                        return None
                    return wrap_s(out)
                return out
```

Thanks!
