### ISSUE TITLE
groupby_dynamic like func to support i32 invterval index

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2316]
ask the question here
[question link](https://stackoverflow.com/questions/70630445/groupby-dynamic-like-method-to-support-the-interval-index)

currently the groupby_dynamic only support the datetime index, using the polars-time mod to support the groupby up/low boundary, maybe we could add a feature about groupby_dynamic like func to support the interval index
```rust
#[derive(Clone, Debug)]
pub struct IntervalGroupOptions {
    pub index_column: String,
    /// start a window at this interval
    pub every: i32,
    /// window duration
    pub period: i32,
    /// offset window boundaries
    pub offset: i32,
    /// truncate the time column values to the window
    pub truncate: bool,
    // add the boundaries to the dataframe
    pub include_boundaries: bool,
    pub closed_window: ClosedWindow,
}
```
```rust

impl DataFrame {
    /// Returns: time_keys, keys, grouptuples
    pub fn groupby_interval(
        &self,
        mut by: Vec<Series>,
        options: &IntervalGroupOptions,
        -> Result<(Series, Vec<Series>, GroupTuples)>
    ) {
        // 
    }
}
```

**Comment by ritchie46** [comment]
What is an interval index? What do you mean by index in this context?

**Comment by yutiansut** [comment]
> What is an interval index? What do you mean by index in this context?

yep: 

like range in python

0,1,2,3,4,5,6,7,8,9,10

-->  periods 3  every 5

**Comment by ritchie46** [comment]
Something like this is planned. I will come back to this.

**Comment by yutiansut** [comment]
@ritchie46 thanks! ~
