### ISSUE TITLE
Extends the datatypes used by polars to allow spatial operations on geometric types

### ISSUE THREAD

**Issue by roger120981** [pola-rs/polars#2322]
The main idea is to create GeoDataFrame and GeoSeries as data types that extend the basic functionalities of Polars and work with geospatial data, manipulation of basic geometries, perhaps those used in the [Georust](georust.org) project, there is a large community that works with spatial data and it would be useful. The idea comes from the [Geopandas](geopandas.org) project as mentioned [here](https://github.com/elixir-nx/explorer/issues/93).

**Comment by zundertj** [comment]
Closing in favor of #1830.
