### ISSUE TITLE
date_range with monthly period results in unexpected dates

### ISSUE THREAD

**Issue by seb2704** [pola-rs/polars#2331]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?
0.12.10

#### What operating system are you using polars on?

Ubuntu 20.04

#### Describe your bug.
date_range with a monthly period equals a period of 30 days.

#### What are the steps to reproduce the behavior?

```python

import polars as pl
from datetime import datetime
print(pl.date_range(datetime(1985, 1, 1), datetime(1985, 7, 1), "1mo"))
```

#### What is the actual behavior?

```
Series: '' [datetime[ns]]
[
	1985-01-01 00:00:00
	1985-01-31 00:00:00
	1985-03-02 00:00:00
	1985-04-01 00:00:00
	1985-05-01 00:00:00
	1985-05-31 00:00:00
	1985-06-30 00:00:00
]
```

#### What is the expected behavior?
```
Series: '' [datetime[ns]]
[
	1985-01-01 00:00:00
	1985-02-01 00:00:00
	1985-03-01 00:00:00
	1985-04-01 00:00:00
	1985-05-01 00:00:00
	1985-06-01 00:00:00
	1985-07-01 00:00:00
]
```

**Comment by ritchie46** [comment]
Thanks for the issue report. We will take a look.

**Comment by scruffs** [comment]
I'm having the same issue. It seems like this is an issue with the polars duration str intervals. The monthly interval is set to 30 days. To provide more clarity, I think this issue also affects resampling of time series data to monthly.
