### ISSUE TITLE
Add to_datetime with functionality

### ISSUE THREAD

**Issue by Guidofaassen** [pola-rs/polars#2332]
I would like to have similar functionality compared to pd.to_datetime (with pl.to_datetime), for example:

```
pd.to_datetime(
    s, format="%Y-%m-%dT%H:%M:%S", exact=False, utc=True, errors="coerce"
)
```

So far I was able to convert a string to datetime using:

`pl.col("date_published").str.strptime(pl.Datetime, fmt="%Y-%m-%dT%H:%M:%S")`

It would be nice to add features like UTC, error coerce and exact/non-exact matches as described in https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html

**Comment by ritchie46** [comment]
`strict` and `exact` are added. Utc doesn't really make sense in polars at the moment.

**Comment by ju6ge** [comment]
Hey I am looking for a way to do this in the rust implementation … So far i have been unsuccessful, to replace a series of type str to as a series with type Datetime.

**Comment by ritchie46** [comment]
`Utf8Chunked::as_datetime`

**Comment by ju6ge** [comment]
Thank you very much :+1: 
For anybody else looking to do this … 
```rust
df.apply(&col, |ser| ser.utf8().unwrap().as_datetime(Some("%Y-%m-%d %H:%M:%S")).unwrap());
```

**Comment by ju6ge** [comment]
Hey is there a way to get a series from Vec<NaiveDateTime>, that does not involve writing every value to a string an then doing a column transformation parsing the strings to arrows DateTime type again?
