### ISSUE TITLE
suffix option of LazyFrame.join not respected if join key dropped

### ISSUE THREAD

**Issue by tikkanz** [pola-rs/polars#2339]
#### Are you using Python or Rust?
Python

#### What version of polars are you using?
0.12.10

#### What operating system are you using polars on?
Ubuntu 18.04

#### Describe your bug.
When joining LazyFrames with columns named the same, the suffix specified in the join method is not respected and the error suggests it is looking for a column with the default suffix "_right"
The suffix option works fine when joining eager DataFrames.
The lazy join works fine if the suffix option is omitted.
The lazy join works fine with the suffix option if the joining column is not dropped later.

#### What are the steps to reproduce the behavior?
The following produces the error: `RuntimeError: Any(NotFound("wgt_right"))`
```
weight = pl.DataFrame({
    "id": [1, 2, 3, 4, 5, 0],
    "wgt": [4.32, 5.23, 2.33, 23.399, 392.2, 0]
}).lazy()

ped = pl.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "sireid": [0, 0, 1, 3, 3]
}).lazy()

sumry = weight.filter(pl.col("id").is_in([2,4])).join(ped, on="id")

sumry.join(
    weight, left_on="sireid", right_on="id", suffix="_sire"
    ).drop("sireid").collect()
```

#### What is the actual behavior?
Hopefully the example above illustrates clearly enough.

#### What is the expected behavior?
If I omit the `suffix="_sire"`, the result is as expected (except the column is named "wgt_right", instead of "wgt_sire".
If I omit the `.drop("sireid")`, the result is as expected (except for the extra "sireid" column).
If I use Eager DataFrames, the result is as expected.

**Comment by ritchie46** [comment]
Thanks for the report. I will pick this up.
