### ISSUE TITLE
read_csv Float64 truncation issue

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2342]
Hi,
I'm using python version (0.12.6). While using read_csv if a particular column contains precision upto 16 places or more, dataframe column is dropping the precision, even though the datatype is Float64. 

Example of csv column 1.5542566914977401
Expected Float64 with value 1.5542566914977401
Got Flaot64 with value 1.55425669149774

Precision is important while dealing with very large number and associated mathematical operations

**Comment by ritchie46** [comment]
That precision does not fit into a 64 bit floating point value:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=db74e435baf88995ef7d53d8db5aa435

**Comment by NarayanB** [comment]
So, what are my options?. I think arrow supports Decimal128. Should i change any option in read_csv to not use polars native parser ?

**Comment by ritchie46** [comment]
Polars doesn't support decimal type. 64 bit floating points is the maximum precision available in polars.

**Comment by ghuls** [comment]
You can read all columns as `pl.Utf8` if you don't need to do calculations on them.

**Comment by NarayanB** [comment]
Hmm. I can do that parsing as Utf8, but at some point i need to convert to decimal to multiply/divide with another decimal
