### ISSUE TITLE
Polars performance between Map and Expr?

### ISSUE THREAD

**Issue by selvavm** [pola-rs/polars#2356]
Can you tell me if I am using Polars correctly?

[stackoverflow](https://stackoverflow.com/questions/70682246/performance-wise-which-is-better-dataframe-map-vs-expression-in-polars)

#### Other

Also, when I created the question I realized there is no trignometric functions in Polars. Is there any plan to support it?

**Comment by ritchie46** [comment]
Thanks, I have answered.


> Also, when I created the question I realized there is no trignometric functions in Polars. Is there any plan to support it?

No, because you can really easy just do a `Float32Chunked::apply(|v| v.cos())`
