### ISSUE TITLE
I am getting an inconsistent result when using Master branch with glob * path

### ISSUE THREAD

**Issue by selvavm** [pola-rs/polars#2357]
#### Are you using Python or Rust?

**Rust**

#### Which feature gates did you use?

`features = ["lazy", "parquet", "is_in"]`

#### What version of polars are you using?

`git = "https://github.com/pola-rs/polars"`

#### What operating system are you using polars on?

Windows 10

#### Describe your bug.

LazyFrame behaving inconsistently after I updated to Master to use the glob feature. If I comment the filter it is working or If I change the `scan_format` to have the actual path of parquet file it is working (i.e) without *.

#### What are the steps to reproduce the behavior?

Create 2 or more Parquet file and place it in folder like below,

```
p
|_ file1.parquet
|_ file2.parquet
```

```
let lf =
        LazyFrame::scan_parquet(format!("{}\\p\\*.parquet", folder_path), Default::default()).unwrap();
func1(lf.clone());
func2(lf.clone());

In func1 it is panicing,
let countries: Vec<String> = .....;
let field = col("traffic");
let asia = lit(Series::new("asia", countries));
let df = lf
        .filter(col("country").is_in(asia))
        .select(&[
            field.clone().max().alias("max"),
            field.clone().mean().cast(DataType::Float32).alias("mean"),
        ])
        .collect()
        .context("Failed in this df")?;
```

#### What is the actual behavior?

```
Data types don't match: cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='country' with left.dtype=str != right.dtype=f32 with right.name='traffic'
```

#### What is the expected behavior?

Display the results

**Comment by ritchie46** [comment]
Thanks, I will take a look.

**Comment by ritchie46** [comment]
Just to be sure, all your files have the same schema?

**Comment by selvavm** [comment]
Yes. I created them from a loop without modifying the schema. I also individually loaded the files in the scan_parquet to check if there is any error but it is working as expected

**Comment by ritchie46** [comment]
> Yes. I created them from a loop without modifying the schema. I also individually loaded the files in the scan_parquet to check if there is any error but it is working as expected

Ok,you can continue working by turning off the optimization that leads to this error. I suspect projection_pushdown or predicate_pushdown.

**Comment by ritchie46** [comment]
Could you clean up your example a bit? I don't really understand what `func1` does. Please give an example I could run by copying pasting.

**Comment by selvavm** [comment]
I am trying to do the same. I know this bug will be difficult to fix without an example. I am trying to create a simple workable example but for a strange reason that is working. My original code has Legion crate in it and I removed it. Don't know if that is causing this changes. I will see if I can reproduce this in an example

**Comment by ritchie46** [comment]
Nevermind, I have been able to reproduce it.

**Comment by selvavm** [comment]
What!! you are so fast :)

I was about to say it is not Legion and something to do with the Parquet file. Because in my example, if I use the original huge file with many columns and rows it is panicing

**Comment by ritchie46** [comment]
Ok, a fix is underway. Keep sure to keep `master` updated lately. The `Union` related logical plan is quite new (that's what we get when globbing).

And there are optimizations coming that will use the parquet statistics. So that can potentially save a lot of compute and IO.

**Comment by selvavm** [comment]
Thanks @ritchie46 for the support. I see that the issue is due to using HashMap and unsorted column order. In my example, I was trying out with column names as 1,2,3…. and that is why it worked.
