### ISSUE TITLE
Reading CSV with quotes causes select/groupby operations on string column to drops middle rows silently

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2362]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.10

#### What operating system are you using polars on?

Ubuntu 20.04.2 LTS (Focal Fossa)

#### Describe your bug.

After performing Select or Groupby + Agg operations on a String column called "Name", I get the head and tail rows but lose all the middle (since the rows are presorted by name before loading into polars, I get the rows starting with a-c and v-z but nothing in between)

#### What are the steps to reproduce the behavior?

I can't share the CSV I'm working with. It's ~10k lines long with maybe ~9 lines on average per unique name.

The following works (no rows dropped):
```
result = pl.scan_csv(
    ...
).filter(
    ~pl.col('MlsServedTotal').is_null()
).with_columns([
    pl.col('MlsServedTotal').sum().over('Name').alias('AnnualMlsServed'),
    pl.col('MlsServedTotal').mean().over('Name').round(0).alias('AvgMonthlyMlsServed'),
]).collect().to_csv(
    ...
)
```

The following fail to work (middle rows dropped):

A `select` statement instead of a `with_columns` statement:
```
result = pl.scan_csv(
    ...
).filter(
    ~pl.col('MlsServedTotal').is_null()
)..select([
    'Name',
]).collect().to_csv(
    ...
)
```

A `group by` statement instead of the `with_columns` statement:
```
result = pl.scan_csv(
    ...
).filter(
    ~pl.col('MlsServedTotal').is_null()
).groupby('Name').agg([
    pl.col('MlsServedTotal').sum().alias('AnnualMlsServed'),
    pl.col('MlsServedTotal').mean().round(0).alias('AvgMonthlyMlsServed'),
]).collect().to_csv(
    ...
)
```

Each of these statements return the rows with names beginning with A-C (most of the Cs, some of the later ones are dropped) V-Z and (most of the Vs, some of the earlier ones are dropped) , even though the `select` statement returns many more rows because there is no groupby condensation. The first C row with issues has a quote in it and is the first quote in the file, so that's probably the source of the bug somehow. The format of the row is:

```
XXX,XXXXX,XXXX,"XXXX, XXXX",XXXX,XXXX,XXX
```
where the quote is in the name column. There's no quote near the first V row that's returned, and there are quotes after that V row that are properly interpreted (i.e. the name which was quoted in the original CSV because it contained a comma is written out whole in the appropriate column to the output csv)

**Comment by ritchie46** [comment]
Can you try to reproduce this in small dummy data?

**Comment by ritchie46** [comment]
I think this is an issue with csv parsing + projection. Could you send the file?

**Comment by LiterallyUniqueLogin** [comment]
I munged the CSV while leaving the structure intact. Attached below.

Reproducing the original error:
```
>>> pl.scan_csv('munged.csv').groupby('XXXX').agg(pl.col('XXXX').first()).collect().shape
(470, 2)
>>> pl.scan_csv('munged.csv').groupby('XXXX').agg(pl.col('XXXXXXXXXXXXXX').mean()).collect().shape
(141, 2)
>>>
```
(The choice of aggregation shouldn't effect the end shape)

Some (potentially unrelated?) typing errors that I stumbled on while trying to document the original bug:
```
>>> pl.scan_csv('munged.csv').filter(pl.col('XXXX').is_null()).collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoliash/miniconda3/envs/default/lib/python3.9/site-packages/polars/internals/lazy_frame.py", line 339, in collect
    return pli.wrap_df(ldf.collect())
RuntimeError: Any(SchemaMisMatch("Series dtype Int64 != utf8"))
```

```
>>> pl.scan_csv('munged.csv').filter(pl.col('XXXX') != '').collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoliash/miniconda3/envs/default/lib/python3.9/site-packages/polars/internals/lazy_frame.py", line 339, in collect
    return pli.wrap_df(ldf.collect())
RuntimeError: Any(SchemaMisMatch("Series dtype Int64 != utf8"))
```

[munged.csv](https://github.com/pola-rs/polars/files/7863869/munged.csv)

**Comment by ritchie46** [comment]
Been able to find a minimal example.

```python
csv = """
XXXXXXXXXXXXXXXX,XXXXXXXXXXXXX,XXXXXXXXXXX,XXXX,XXXXXXXXXXXXXXXX,XXXXXXXXXXXX,XXXXXXXXXXXXXX
1111,1111-1 (XXX),XXXX,"XXXXX'X XXXXX XXXXX, XXX.",XXXXXX,XXXX_XXXXX,1111
1111,1111-1 (XXX),XXXX,"XXXXX'X XXXXX XXXXX, XXX.",XXXXXX,XXXX_XXXXX,1111
1111,1111-1 (XXX),XXXX,"XXXXX'X XXXXX XXXXX, XXX.",XXXXXX,XXXX_XXXXX,1111
1111,1111-1 (XXX),XXXX,"XXXXX'X XXXXX XXXXX, XXX.",XXXXXX,XXXX_XXXXX,1111
1111,1111-1 (XXX),XXXX,"XXXXX'X XXXXX XXXXX, XXX.",XXXXXX,XXXX_XXXXX,1111
1111,1111-11 (XXX),XXXX,XXXXXXXX'X XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX,XXXXXX,XXXX_XXXXX,111
1111,1111-11 (XXX),XXXX,XXXXXXXX'X XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX,XXXXXX,XXXX_XXXXX,111
1111,1111-11 (XXX),XXXX,XXXXXXXX'X XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX,XXXXXX,XXXX_XXXXX,111
1111,1111-1 (XXX),XXXX,XXXXXXXX'X XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX,XXXXXX,XXXX_XXXXX,111
1111,1111-1 (XXX),XXXX,XXXXXXXX'X XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX,XXXXXX,XXXX_XXXXX,111"""



shape_a = pl.read_csv(csv.encode(), columns=[]).shape
shape_b = pl.read_csv(csv.encode(), columns=["XXXXXXXXXXXXXX", "XXXX"]).shape
print(shape_a, shape_b)
```
Outputs

```
(10, 7) (1, 2)
```
