### ISSUE TITLE
more documents about duration type conversion

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2370]
Hi;

When I subtract 2 dates, it creates duration type. Assuming that duration equals to n days, how can I get number of days in integer format.  I could not find detailed information about duration type. If we can add small section in documentation, it will help newcomers.

Thanks.

**Comment by ritchie46** [comment]
The duration type did not have any utility methods yet. I have added a few.

**Comment by hakantekbas** [comment]
Thanks @ritchie46
