### ISSUE TITLE
from polars.lazy import col isn't working

### ISSUE THREAD

**Issue by MrPowers** [pola-rs/polars#2374]
When I run `from polars.lazy import col` I get this error message: "ModuleNotFoundError: No module named 'polars.lazy'".

I'm trying to run the [h2o db-benchmark Polars code](https://github.com/h2oai/db-benchmark/blob/master/polars/groupby-polars.py#L9).

I am using Polars version 0.12.10.

Thanks for the help!

**Comment by ritchie46** [comment]
Oh yes its a top level import now. Thanks for the heads up. Means we need to send them a PR.

**Comment by ritchie46** [comment]
And there is a release today with improvements on csv parsing perf. Don't forget to update😁

**Comment by MrPowers** [comment]
@ritchie46 - how can I fix the import statement in a notebook I'm working on?  What should it be now so I can access `col`?

**Comment by MrPowers** [comment]
Awesome, thank you!
