### ISSUE TITLE
round() method dosen't round numbers if column is casted to Float32

### ISSUE THREAD

**Issue by teneon** [pola-rs/polars#2396]
#### Are you using Python or Rust?
Python

#### What version of polars are you using?
polars-0.12.12

#### What operating system are you using polars on?
Ubuntu 20.04

#### Describe your bug.
round() method doesn't work properly on Float32, while Float64 works as expected.

**Example**

```python
import polars as pl
import numpy as np

# generate a dataframe with column 'open', the type by default will be Float64
dataframe = pl.DataFrame({
    'open': np.random.uniform(low=0.0, high=100.0, size=5)
})

# Next line (cast to Float32) is problematic. Once you cast to Float32, round() method will not work anymore.
# Simply comment out next line (cast) and round() method will round numbers nicely to two decimal places as expected.
dataframe['open'] = (dataframe['open']).cast(pl.Float32)

# Round works on Float64, but if you cast to Float32 (above) it will not round the numbers to two decimal places.
dataframe['open'] = (dataframe['open']).round(2)

# print dataframe
print("generated dataframe:\n", dataframe)

```

#### What is the expected behavior?

Even if you cast Float64 to Float32, polars should still properly round() numbers to specified number of decimal places in the round() method. Perhaps it would be also a good idea to check other similar methods to round(), such as floor() etc. to see if they work properly after being casted to Float32.

#### Why is this important

I know, i know, we could "simply use Float64" instead. But it's not as simple as that. We are processing, analyzing huge datasets, e.g. 20GB to 100GB and more. Datasets include large number of float columns. We can easily save almost 50% of RAM by simply casting 
Float64 to Float32.

best regards,
Neon

**Comment by ritchie46** [comment]
The outputs are:

```
shape: (5, 1)
┌───────────┐
│ open      │
│ ---       │
│ f32       │
╞═══════════╡
│ 44.68     │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ 85.370003 │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ 80.139999 │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ 74.970001 │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ 34.25     │
└───────────┘

```

So they are rounded close to the requested digits. There are only floating point precision issues. 

The current algorithm is:

```
multiplier = 10.0 ^ decimals

(x * multiplier).round()  / multiplier
```

I don't know if there is an algorithm that has less precision drift.

**Comment by ritchie46** [comment]
We could do the conversion in f64 and only coerce to f32 when thebresult is computed.

**Comment by teneon** [comment]
Hi Ritche,

thank you for a quick response.

I've been playing with numpy now as well to see if i could convert floats from Polars "to_numpy()" first and then round it with numpy round method, but it seems like that numpy has the same issue with float32.

Not sure what the best solution would be, but i think it feels more natural, if it would properly round floats to the exact decimals that u have specified in the round() method. If u find a good solution for Float32, then i think it's worth implementing it, if not, it's not the end of the world i guess.

What i needed this for. Basically i am cumputing some stuff in Polars (Python backend API), then i return json response. I wanted to prepare rounded floats on the backend side. Right now as a workaround i did something like this:
`formatted = float('{:.2f}'.format(df_new['open'][0]))`

There is also `np.format_float_positional` method in numpy. It returns a string and then you have to float(that_string) again if u want a float type.

p.s. if u will be able to implement something regarding this Float32 round issue, let me know and i will test it, thanks :-)

Amazing work with Polars, we like it a lot!

Best regards,
Neon

**Comment by ritchie46** [comment]
> Not sure what the best solution would be, but i think it feels more natural, if it would properly round floats to the exact decimals that u have specified in the round() method.

That is not possible in floating points of a binary system. Some number of decimals have rounding errors.

I however improved the precision in #2398
