### ISSUE TITLE
read_ipc 'n_rows' does not limit number of rows properly

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#2403]
#### Are you using Python or Rust?

python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.12.12

#### What operating system are you using polars on?

WSL ubuntu

#### Describe your bug.

expected:
height == 4
actual:
height == 5

```py
import polars as pl
ipc_path = "./demo.ipc"

>>> pl.DataFrame({
...   "a": [1, 2, 3, 4, 5]
... }).to_ipc(ipc_path)

>>> print(pl.read_ipc(ipc_path, n_rows=4, use_pyarrow=False))
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 4   │
├╌╌╌╌╌┤
│ 5   │
└─────┘
```

**Comment by ghuls** [comment]
See: https://github.com/pola-rs/polars/issues/1780

n_rows will stop reading after it has at least enough rows (but will read the whole current record batch).
