### ISSUE TITLE
Rolling Window Functionality for Dates as in Pandas

### ISSUE THREAD

**Issue by orchardbirds** [pola-rs/polars#2407]
#### Other

In the `groupby_dynamic` documentation, it says "The time/index window could be seen as a rolling window, with a window size determined by dates/times/values instead of slots in the DataFrame."

But if we want to use the slots in the DataFrame, such as looking back 2 days before each row, how would we do this?

For example, imagine the following dataframe:

| time | number| 
|-------|-----------|
| 2020-01-01 13:45:48 | 3 |
| 2020-01-01 16:42:13 | 7 |
| 2020-01-01 16:45:09 | 5|
| 2020-01-02 18:12:48 | 9 |
| 2020-01-03 19:45:32 | 2 |
| 2020-01-08 23:16:43 | 1 |

Applying a 2-day rolling window should output the following:

| time | number |  sum(number)| 
|-------|-----------|---------|
| 2020-01-01 13:45:48 | 3 | 3|
| 2020-01-01 16:42:13 | 7 | 10| 
| 2020-01-01 16:45:09 | 5|  15|
| 2020-01-02 18:12:48 | 9 | 24|
| 2020-01-03 19:45:32 | 2 | 11 |
| 2020-01-08 23:16:43 | 1 | 1|

Note that the specific seconds are important too, and I don't want to do something like `(every="1s", period="2d")` because that will explode the memory

Pandas code would look like this:

```python
df_rolling = df.rolling("2D", on="time")
df["sum"] = df_rolling["number"].sum()
```

I couldn't find this on StackOverflow. Thanks in advance!

**Comment by seb2704** [comment]
u have to set a negative offset
'''
df = pl.DataFrame(
    {"time": [datetime.datetime(2021, 2, 1), datetime.datetime(2021, 2, 3), datetime.datetime(2021, 2, 4)],
     "number": [0, 1, 2],
     })
df = (
        df.sort(by=[pl.col('time')]).groupby_dynamic(
            time_column="time",
            every="1d",
            closed='left',
            offset= "-2d",
            period= "2d",
            include_boundaries=True,
        ).agg([
            pl.col('number').sum()
        ])
    )
'''
results in 
'''
┌─────────────────────┬─────────────────────┬─────────────────────┬────────────┐                                        │ _lower_boundary     ┆ _upper_boundary     ┆ time                ┆ number_sum │                                        │ ---                 ┆ ---                 ┆ ---                 ┆ ---        │                                        │ datetime[ns]        ┆ datetime[ns]        ┆ datetime[ns]        ┆ i64        │                                        ╞═════════════════════╪═════════════════════╪═════════════════════╪════════════╡                                        │ 2021-01-31 00:00:00 ┆ 2021-02-02 00:00:00 ┆ 2021-02-01 00:00:00 ┆ 0          │                                        ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤                                        │ 2021-02-01 00:00:00 ┆ 2021-02-03 00:00:00 ┆ 2021-02-01 00:00:00 ┆ 0          │                                        ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤                                        │ 2021-02-02 00:00:00 ┆ 2021-02-04 00:00:00 ┆ 2021-02-03 00:00:00 ┆ 1          │                                        ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤                                        │ 2021-02-03 00:00:00 ┆ 2021-02-05 00:00:00 ┆ 2021-02-03 00:00:00 ┆ 3          │                                        ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤                                        │ 2021-02-04 00:00:00 ┆ 2021-02-06 00:00:00 ┆ 2021-02-04 00:00:00 ┆ 2          │                                        └─────────────────────┴─────────────────────┴─────────────────────┴────────────┘ 
'''

**Comment by orchardbirds** [comment]
Thanks for your quick reply, but I mean the following. Imagine a dataframe:

| time | number| 
|-------|-----------|
| 2020-01-01 13:45:48 | 3 |
| 2020-01-01 16:42:13 | 7 |
| 2020-01-01 16:45:09 | 5|
| 2020-01-02 18:12:48 | 9 |
| 2020-01-03 19:45:32 | 2 |
| 2020-01-08 23:16:43 | 1 |

Applying a 2-day rolling window should output the following:

| time | number |  sum(number)| 
|-------|-----------|---------|
| 2020-01-01 13:45:48 | 3 | 3|
| 2020-01-01 16:42:13 | 7 | 10| 
| 2020-01-01 16:45:09 | 5|  15|
| 2020-01-02 18:12:48 | 9 | 24|
| 2020-01-03 19:45:32 | 2 | 11 |
| 2020-01-08 23:16:43 | 1 | 1|

**Comment by ritchie46** [comment]
The windows are currently fixed. Maybe we could add an option where we don't match slots to windows, but windows to slots.

**Comment by orchardbirds** [comment]
That would be a really nice option :)
