### ISSUE TITLE
Groupby without aggregate

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2411]
#### Describe your feature request

Just a nice bit of syntax. Sometimes I just want to perform a 'unique' operation on multiple rows simultaneously, and don't want any other aggregates. This would be nice syntax for that:

```
# get a list of unique (foo, bar) pairs
df.groupby(['foo', 'bar']).agg()
```

**Comment by zundertj** [comment]
It would be good to have an example, it is not completely clear to me what you mean by "'unique'  operation on multiple rows simultaneously". My interpretation of the comment in your code is that we cover this already with `drop_duplicates`:
```python
import polars as pl
df = pl.DataFrame({"a": [1, 1, 2],
                   "b": [2, 2, 2]})
df.drop_duplicates()
```

which returns
```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 2   │
└─────┴─────┘
```

Note that `drop_duplicates` has a `subset` keyword to define which combination of columns should be unique.

**Comment by LiterallyUniqueLogin** [comment]
I didn't know of that function! I guess what I'm looking for is 
```
df.drop_duplicates(subset=['a', 'b']).select(['a', 'b'])
```

Groupby already does most of this without needing to duplicate the column list in the selection, it just requires a non-empty args list currently. But the current way of doing this is cleaner than I thought.

**Comment by zundertj** [comment]
If you switch around the order, it is cleaner:

```python
df.select(['a', 'b']).drop_duplicates()
```

**Comment by LiterallyUniqueLogin** [comment]
That works for me. Thanks!
