### ISSUE TITLE
Count in groupby without column

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2412]
#### Describe your feature request

When you're doing a groupby, unlike all other aggregations, the count for any expression should be the same, so why force the user to specify one?

Current syntax
```
# notice here that the choice of column 'foo' is extraneous, result would be the same with 'bar'
df.groupby(['foo', 'bar']).agg(pl.count('foo').alias('count'))
```
Proposed syntax. Either:
```
df.groupby(['foo', 'bar']).agg(pl.count())
```
or:
```
df.groupby(['foo', 'bar'], with_counts=True)
```
where in either case the new column is named 'count'

**Comment by Fred-Wu** [comment]
I am trying `polars` right now. This is the issue I encounter as well. 

```
df.groupby(['foo', 'bar']).count() 
```
works, but gives every column in the data. 

The result should just be three columns， in which the first two are "foo" and "bar", the third one is count.
