### ISSUE TITLE
CSV scanning bug with `head`

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2417]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.13

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

I've got another CSV scanning bug. I'll try to produce a smaller/nonsensitive CSV to replicate

EDIT: removing this example, see comment below for correct example

**Comment by LiterallyUniqueLogin** [comment]
Here's an example that works. I kept chopping the file in half till the bug stopped appearing. It's still big, but some particular line in here (or perhaps just the sizing?) is necessary for the bug to appear.

Works :
```
>>> pl.scan_csv('munged_example.txt', sep='\t').collect().filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).head(10)
shape: (1, 27)
┌───────┬───────────┬─────────────────────┬────────────────┬─────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┐
│ XXXXX ┆ XXX       ┆ XXXeXeX             ┆ XXXXX_XXXXeXeX ┆ ... ┆ 1e-1_XXXXXXXXXXXe_XX                ┆ XeXX_XXXXe_XXXXX_XeXX_XXXXX_XeX_... ┆ 1.11_XXXXXXXXXXXe_XX                ┆ 1e-1_XXXXXXXXXXXe_XX                │
│ ---   ┆ ---       ┆ ---                 ┆ ---            ┆     ┆ ---                                 ┆ ---                                 ┆ ---                                 ┆ ---                                 │
│ i64   ┆ i64       ┆ str                 ┆ str            ┆     ┆ str                                 ┆ str                                 ┆ str                                 ┆ str                                 │
╞═══════╪═══════════╪═════════════════════╪════════════════╪═════╪═════════════════════════════════════╪═════════════════════════════════════╪═════════════════════════════════════╪═════════════════════════════════════╡
│ 1     ┆ 112111111 ┆ 11.1,11.1,11.1,11.1 ┆ XXXXe          ┆ ... ┆ {"11.1": [1.1111111111111111, 11... ┆ {"[11.1, 11.1]": 1.1111111111111... ┆ {"[11.1, 11.1]": [1.111111111111... ┆ {"[11.1, 11.1]": [-11.1111111111... │
└───────┴───────────┴─────────────────────┴────────────────┴─────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┘
```
Doesn't work:
```
>>> pl.scan_csv('munged_example.txt', sep='\t').filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).head(10).collect()
shape: (0, 27)
┌───────┬─────┬─────────┬────────────────┬─────┬──────────────────────┬─────────────────────────────────────┬──────────────────────┬──────────────────────┐
│ XXXXX ┆ XXX ┆ XXXeXeX ┆ XXXXX_XXXXeXeX ┆ ... ┆ 1e-1_XXXXXXXXXXXe_XX ┆ XeXX_XXXXe_XXXXX_XeXX_XXXXX_XeX_... ┆ 1.11_XXXXXXXXXXXe_XX ┆ 1e-1_XXXXXXXXXXXe_XX │
│ ---   ┆ --- ┆ ---     ┆ ---            ┆     ┆ ---                  ┆ ---                                 ┆ ---                  ┆ ---                  │
│ i64   ┆ i64 ┆ str     ┆ str            ┆     ┆ str                  ┆ str                                 ┆ str                  ┆ str                  │
╞═══════╪═════╪═════════╪════════════════╪═════╪══════════════════════╪═════════════════════════════════════╪══════════════════════╪══════════════════════╡
└───────┴─────┴─────────┴────────────────┴─────┴──────────────────────┴─────────────────────────────────────┴──────────────────────┴──────────────────────┘
```

Unless I'm misunderstanding how `head` is supposed to work, collecting before or after `head` should produce the same result.

[munged_example.txt](https://github.com/pola-rs/polars/files/7891413/munged_example.txt)

**Comment by LiterallyUniqueLogin** [comment]
Also, if `fetch(n)` after a sequence of filters is supposed to fetch n rows from the filtered data frame, then this is also a bug with `fetch`.
```
>>> pl.scan_csv('munged_example.txt', sep='\t').filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).fetch(10)
shape: (0, 27)
┌───────┬─────┬─────────┬────────────────┬─────┬──────────────────────┬─────────────────────────────────────┬──────────────────────┬──────────────────────┐
│ XXXXX ┆ XXX ┆ XXXeXeX ┆ XXXXX_XXXXeXeX ┆ ... ┆ 1e-1_XXXXXXXXXXXe_XX ┆ XeXX_XXXXe_XXXXX_XeXX_XXXXX_XeX_... ┆ 1.11_XXXXXXXXXXXe_XX ┆ 1e-1_XXXXXXXXXXXe_XX │
│ ---   ┆ --- ┆ ---     ┆ ---            ┆     ┆ ---                  ┆ ---                                 ┆ ---                  ┆ ---                  │
│ i64   ┆ i64 ┆ str     ┆ str            ┆     ┆ str                  ┆ str                                 ┆ str                  ┆ str                  │
╞═══════╪═════╪═════════╪════════════════╪═════╪══════════════════════╪═════════════════════════════════════╪══════════════════════╪══════════════════════╡
└───────┴─────┴─────────┴────────────────┴─────┴──────────────────────┴─────────────────────────────────────┴──────────────────────┴──────────────────────┘
```

**Comment by ritchie46** [comment]
> Also, if `fetch(n)` after a sequence of filters is supposed to fetch n rows from the filtered data frame, then this is also a bug with `fetch`.
> 
> ```
> >>> pl.scan_csv('munged_example.txt', sep='\t').filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).fetch(10)
> shape: (0, 27)
> ┌───────┬─────┬─────────┬────────────────┬─────┬──────────────────────┬─────────────────────────────────────┬──────────────────────┬──────────────────────┐
> │ XXXXX ┆ XXX ┆ XXXeXeX ┆ XXXXX_XXXXeXeX ┆ ... ┆ 1e-1_XXXXXXXXXXXe_XX ┆ XeXX_XXXXe_XXXXX_XeXX_XXXXX_XeX_... ┆ 1.11_XXXXXXXXXXXe_XX ┆ 1e-1_XXXXXXXXXXXe_XX │
> │ ---   ┆ --- ┆ ---     ┆ ---            ┆     ┆ ---                  ┆ ---                                 ┆ ---                  ┆ ---                  │
> │ i64   ┆ i64 ┆ str     ┆ str            ┆     ┆ str                  ┆ str                                 ┆ str                  ┆ str                  │
> ╞═══════╪═════╪═════════╪════════════════╪═════╪══════════════════════╪═════════════════════════════════════╪══════════════════════╪══════════════════════╡
> └───────┴─────┴─────────┴────────────────┴─────┴──────────────────────┴─────────────────────────────────────┴──────────────────────┴──────────────────────┘
> ```

The fetch fetches `n_rows` and then applies the filter. This is not a bug if you filter out all data afterwards.

**Comment by LiterallyUniqueLogin** [comment]
Okay. That's good to know! That's not intuitive to me, as that makes fetch the only operation where its position in the succession of operations isn't relevant to its function (and in fact, it acts as if its position is always towards the beginning, contradicting its current position). Could an error be thrown when you apply fetch not directly after a load operation so that other people don't make that mistake?

But regardless, there still seems to be a bug with `head` here unless I also misunderstand how that's supposed to work.

**Comment by ritchie46** [comment]
Yes.. the idea of fetch is to make it easy to test your query on small data. Your query may be very large and adding a fetch at the end is more ergonomic than scrolling and limiting the scan.

The reason we have a fetch and a head is that we cannot alwas pushdown a head and thus must run to whole query to produce a head. Which is expensive in testing the outputs. 

And I will take a look at the bug. Could you print the optimized plans for me?

**Comment by LiterallyUniqueLogin** [comment]
Happy to. How do I do so?

**Comment by universalmind303** [comment]
> Happy to. How do I do so?

`lazy_df.describe_optimized_plan()`

**Comment by LiterallyUniqueLogin** [comment]
```
>>> pl.scan_csv('munged_example.txt', sep='\t').filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).head(10).describe_optimized_plan()
'CSV SCAN munged3.tab; PROJECT */27 COLUMNS; SELECTION: Some([([(col(XXXXX)) == (1i64)]) & ([(col(XXX)) == (112111111i64)])])'
```

**Comment by ritchie46** [comment]
> ```
> >>> pl.scan_csv('munged_example.txt', sep='\t').filter((pl.col('XXXXX') == 1) & (pl.col('XXX') == 112111111)).head(10).describe_optimized_plan()
> 'CSV SCAN munged3.tab; PROJECT */27 COLUMNS; SELECTION: Some([([(col(XXXXX)) == (1i64)]) & ([(col(XXX)) == (112111111i64)])])'
> ```

Thanks.. it seems like we do the head before the filter when we shouldn't.
