### ISSUE TITLE
Feature req: gRPC client for Node

### ISSUE THREAD

**Issue by gebrits** [pola-rs/polars#2418]
#### Describe your feature request

Now that IPC-foundation is there including support for Arrow Arrow IPC v2 files, it would be nice to have a gRPC wrapper to be able to request those files from remote locations.

Python and (perhaps) Rust already have these options in other libraries, but it's not available  for NodeJS afaik. 

Personal usecase: [clickhouse](http://clickhouse.com) can output to ArrowStream format (= ipc v2). 
Being able to just do a select on clickhouse -> output as arrowstream -> make recordbaches from that stream in Polars (presumably) which can then be iterated over or combined with local data, would be great

**Comment by universalmind303** [comment]
maybe im misunderstanding the request, as im not well versed in gRPC.  But node already supports reading from arbitrary buffers.


```js

// a single buffer
const ipcBuffer = await grpcClient.getArrowStream()
const df = pl.readIPC(ipcBuffer)

// multiple useable chunks in the stream
const arrowStream = grpcClient.getArrowStream()
const dfChunks = []
let df;
arrowStream.on("data", (buffer) => dfChunks.push(pl.readIPC(buffer)))
arrowStream.on("end", () => {df = pl.concat(dfChunks)})
console.log(df)

// multiple chunks that need to be read all at once 
const arrowStream = grpcClient.getArrowStream()
const chunks= []
let df;
arrowStream.on("data", (buffer) => chunks.push(buffer))
arrowStream.on("end", () => {
  const buf = Buffer.concat(chunks)
  df = pl.readIPC(buf)
})

**Comment by gebrits** [comment]
For example 2 to work ("multiple useable chunks in the stream"), the gRPCClient needs to know how to chunk the stream into recordbatches right? This RecordBatchStreamReader isn't there yet on the NodeJS side afaik?

**Comment by universalmind303** [comment]
> multiple chunks that need to be read all at once 
this is how the csv stream reader  (`pl.readCSVStream`) works. It is MUCH slower than reading from a file, and really only serves as an interop method. 

I am planning on optimizing the `pl.read**Stream` methods. 

https://github.com/pola-rs/polars/blob/master/nodejs-polars/polars/io.ts#L426

**Comment by gebrits** [comment]
> I am planning on optimizing the pl.read**Stream methods.

Feel free to ignore if this was already clear, but: 

Are you also considering implementing read**stream methods for unbounded streams? Ie those that can’t be buffered in their entirety, but will, for instance, produce a new stream that outputs recordbatches as chunks? 

You’d end up with something in userland like:

```
for await (df of recordbatchFromCsvStream(stream)){
   // process df here. 
})

```

Thoughts?

**Comment by universalmind303** [comment]
Streaming (unbounded iterators) DF processing is out of scope for now, as the underlying rust implementation does not support it. Polars needs to consume the entire iterator to create the dataframe. This is not specific to JS. All of the polars read operations perform in a similar manner. 

The optimizations I plan on making to the read**Stream methods will be under the pretense that they have a definitive end. 

nodejs-polars wont be able to implement such a feature until polars-core supports unbounded iterators.

**Comment by gebrits** [comment]
Ah ok, didn't realize! It's eventually planned though for polars-core?

**Comment by ritchie46** [comment]
> Ah ok, didn't realize! It's eventually planned though for polars-core?

No, that would require streaming algorithms for everything. This is not in scope for the project.
