### ISSUE TITLE
Does Polars support BMS(BusinessMonthBegin) in OHLC

### ISSUE THREAD

**Issue by CHCP** [pola-rs/polars#2420]
Hi @ritchie46:

  I used rust-polars to calculate OHLC(first/high/low/last) value, for January 2022,  I got such value:
```
{"u":1640988000,"o":0.91723,"h":0.92391,"l":0.8976,"c":0.89829,"a":0.89838}
1640988000 to date string: 20220101
```

But it should be:
```
{"u":1641160800,"o":0.91723,"h":0.92391,"l":0.8976,"c":0.89829,"a":0.89838}
1641160800 to date string: 20220103
```

Because the first business day of January 2022 is 20220103, so can Polars support this function? or How to do this? 

  Thank you very much.

**Comment by ritchie46** [comment]
You can iterate polars `datetime` columns as `chrono DateTime` structs. And then use this crate: https://docs.rs/bdays/latest/bdays/

**Comment by CHCP** [comment]
Thanks for your quick reply.
There are only one u value that I got from Polars library, if this date(from u) is weekend,  will check the next day until there is a business day?  

Is the way  correct?  And there will be no a TAG "BMS" of polars date?

**Comment by ritchie46** [comment]
Sorry, I don't really understand.

**Comment by CHCP** [comment]
This is Pandas resample function:
```
pandas.DataFrame.resample(rule, axis=0, closed=None...) 
Parameters rule: DateOffset, Timedelta or str, for example:  BMS, 3T
```

Will Polars support some rule such like "BMS" or "3T"?

Thank you

**Comment by CHCP** [comment]
Only can iterate polars datetime.

**Comment by MarcoGorelli** [comment]
@rts-gordon we're taking business day logic forwards in a plugin, please see https://github.com/MarcoGorelli/polars-business

**Comment by rts-gordon** [comment]
@MarcoGorelli 
  
  Thanks for your great work. It is wonderful to implement business day logic via a plugin.
