### ISSUE TITLE
Support df.info()

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#2429]
#### Describe your feature request

Pandas offers a info function 
```df.info() ```
to see how many non-null values of each columns with data type. Is that possible polars can also provide this?

**Comment by ghuls** [comment]
You can get the number of null values instead: `df.null_count()`

**Comment by cnpryer** [comment]
Maybe we can resurface this for the memory usage component?

Related: [this users stackoverflow question](https://stackoverflow.com/q/71788877/5363883).

**Comment by Rosvend** [comment]
`info()` method in pandas also includes memory usage, does `df.schema` provide this information as well?

**Comment by fbuldur** [comment]
- For those who are searching, it is implemented and can be accessed from following link.

[Estimated Size](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.estimated_size.html)
