### ISSUE TITLE
How to use `downsample` function in 0.19?

### ISSUE THREAD

**Issue by cenwangumass** [pola-rs/polars#2430]

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

**Comment by cenwangumass** [comment]
@ritchie46 Sorry, I mean when I updated to 0.19 from 0.18, I found `downsample` feature flag is no longer available but there is no mentioning in the changelog about this change and how it will be replaced?

**Comment by ritchie46** [comment]
Ah.. it is replaced by `groupby_dynamic` available in polars lazy.

See the python docs for examples. 

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.groupby_dynamic.html?highlight=dynamic

**Comment by ritchie46** [comment]
I will close this because it seems inactive and the question is been answererd.

**Comment by semirix** [comment]
@ritchie46 I would like to mention that there is no documentation for the Rust API on how to idiomatically perform a downsample using `groupby_dynamic`. I have gotten away with doing the following with `groupby_with_series`.

```rust
let size = downsample.size.as_millis() as i64;

let mut starts: Series = self.data[NAME_TIMESTAMP]
    .i64()?
    .into_iter()
    .map(|timestamp| {
        let timestamp = timestamp.unwrap();
        timestamp - timestamp % size
    })
    .collect();

starts.rename(NAME_TIMESTAMP_START);

let grouped = self
    .data
    .groupby_with_series(vec![starts], true, true)?
    .select([NAME_VALUE]);
```

Perhaps you could advise on how to do it a better way? Additionally, this might be a good opportunity to improve the docs.

**Comment by ritchie46** [comment]
You should use the lazy API. It is almost a 1:1 copy with the python API. See:

https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/temporal_groupby.html

**Comment by semirix** [comment]
@ritchie46 Perhaps I have missed something crucial. For this python code:

```python
df.groupby_dynamic("Date", every="1y").agg(pl.col("Close").mean())
```

It is not obvious to me through reading the docs how to express `every=1y` in Rust.

**Comment by ritchie46** [comment]
`Duration::parse("1y")`
