### ISSUE TITLE
Melting with categorical id_vars generate str columns

### ISSUE THREAD

**Issue by Trollgeir** [pola-rs/polars#2442]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.12.13

#### What operating system are you using polars on?
Linux Ubuntu 20.04

#### Describe your bug.

When using `melt` on a dataframe on a categorical string, new columns based on the `id_vars` end up being `str` instead of `categorical`.

#### What are the steps to reproduce the behavior?

```import polars as pl

df = pl.DataFrame({"a": [0,2,3], 
                   "b": [4,0,6], 
                   "c": [7,8,0]})
df["label"] = pl.Series(df.columns).cast(pl.Categorical)
df_melted = df.melt("label", value_vars=df.columns[:-1])
df_melted

┌───────┬──────────┬───────┐
│ label ┆ variable ┆ value │
│ ---   ┆ ---      ┆ ---   │
│ cat   ┆ str      ┆ i64   │
╞═══════╪══════════╪═══════╡
│ a     ┆ a        ┆ 0     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ b     ┆ a        ┆ 2     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c     ┆ a        ┆ 3     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ a     ┆ b        ┆ 4     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
...
│ b     ┆ c        ┆ 8     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c     ┆ c        ┆ 0     │
└───────┴──────────┴───────┘

```

**Comment by ritchie46** [comment]
That is as intended. You can coerce this to an `categorical` type afterwards. Note that we also cannot create categoricals incrementally, so internally we would also need to create that column afterwards.

**Comment by Trollgeir** [comment]
Do you have to create in incrementally though? Scanning the columns at the start of `melt` should give you the possible set of categorical values without needing to increment.

**Comment by ritchie46** [comment]
I mean that a categorical column is created per column basis from an Utf8 column. That means we first need to make the Utf8 column before we can create categoricals.

So if you add a

```python
df.melt(..).with_column(pl.col("variable").cast(pl.Categorical))`
```

you would have the same implementation as we would built.

You could wrap that in your own `melt` if you like that one better.

A `categorical` has got some gotcha's regarding global string cache that a user must think about, that's why I don't want it as default. And building a categorical is also more expensive than building an utf8 column, as we first must build the utf8 column anyways.

**Comment by Trollgeir** [comment]
What I want to avoid is to have a massive memory allocation for a new and enormous string column. The memory allocation can be so big that I run out of resources, yet quite manageable if represented as a category or uint8.

**Comment by ritchie46** [comment]
> What I want to avoid is to have a massive memory allocation for a new and enormous string column(s). The memory allocation can be so big that I run out of resources, yet quite manageable if represented as a category or uint8.
> 
> If I cast the `label` column in this example as an `Uint8` I'm halfway there, as the resulting `id_value` will be `Uint8` too. But I cannot set a type for the generated `variable` column because they're based on the string-names of the series.

I understand, but avoiding the peak memory is not possible at the moment given how `Categoricals` are designed. As I said, they can only be created from a single column (thus the column will be the peak memory load).

If memory is tight you could rename your columns to a single byte string like "a", "b" etc.

Then the memory consumption of the strings will be quite low. E.g. 9 bytes per row.

**Comment by Trollgeir** [comment]
Thanks for the extra clarification. I totally forgot that the string columns are basically just one long string with pointers, so that makes total sense! In this case I think I should be able to manage just fine :+1: 

Feel free to close the issue.
