### ISSUE TITLE
Cannot do `.to_pandas()` with categorical columns

### ISSUE THREAD

**Issue by Trollgeir** [pola-rs/polars#2445]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.12.15

#### What operating system are you using polars on?

Linux ubuntu 20.04

#### Describe your bug.

When converting a dataframe to pandas (`.to_pandas()`) containing categorical columns, pyarrow crashes: 
`pyarrow.lib.ArrowTypeError: Converting unsigned dictionary indices to pandas not yet supported, index type: uint32`

pyarrow version: 6.0.1

#### What are the steps to reproduce the behavior?
```python
df = pl.DataFrame({"a": ["best","test"]})
df = df.with_columns(pl.all().cast(pl.Categorical))
df.to_pandas()
```
#### What is the expected behavior?

A constructed pandas dataframe with said columns of the native pandas category type.

**Comment by ritchie46** [comment]
fixed by #2456
