### ISSUE TITLE
pivot performance degrades exponentially with increased cardinality of index column

### ISSUE THREAD

**Issue by zeitgeber** [pola-rs/polars#2452]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

pivot

#### What version of polars are you using?

0.12.15

#### What operating system are you using polars on?

Ubuntu 20.04.1 LTS

#### Describe your bug.

pivot performance degrades exponentially with increase in number of unique values in index field. This behavior is different from pandas. for >10k unique values it is orders of magnitude faster to convert to pandas df, pivot and convert back to polars than it is to pivot in polars itself.

#### What are the steps to reproduce the behavior?

```
from random import randint
import pandas as pd
import polars as pl

df = pl.DataFrame({'a':[randint(1,1000) for i in range(10000)],'b':[randint(1,300) for i in range(10000)],'c':[randint(1,300) for i in range(10000)]})
print(df.shape)
%time _ = df.pivot(['c'],['a'],['b'],aggregate_fn='first')
%time _ = pl.from_pandas(pd.pivot_table(df.to_pandas(),['c'],['a'],['b'],aggfunc='first'))
```

#### What is the actual behavior?
![image](https://user-images.githubusercontent.com/5524987/150694690-772c258c-ffb2-4fdd-ac90-be053da91e69.png)

#### What is the expected behavior?

performance similar to pandas

**Comment by ritchie46** [comment]
Thanks, I will look into this. This is a regression from our earlier implementation. You could downgrade to an earlier version of polars for the mean time.

**Comment by ritchie46** [comment]
The root cause is found. I think we can have a patch soon.
