### ISSUE TITLE
horizontal min/max fails when nested with duplicate column name error

### ISSUE THREAD

**Issue by zeitgeber** [pola-rs/polars#2462]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

horizontal min/max

#### What version of polars are you using?

0.12.16

#### What operating system are you using polars on?

Ubuntu 20.04.1 LTS

#### Describe your bug.

when nesting horizontal min/max expressions, get a duplicate column error if inner expression contains two max/min expressions

#### What are the steps to reproduce the behavior?

```
import polars as pl
df = pl.DataFrame({'a':[1],'b':[2],'c':[3],'d':[4]})
df.with_column(pl.max([pl.min(['a','b']),pl.min(['c','d'])]).alias('t'))
```

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/5524987/150888769-0ca64a88-5dbb-4226-9e3b-30bf3c6612ae.png)

#### What is the expected behavior?

The example works if I alias the nested expressions. Expected behavior is for this to work without having to alias inner expressions.

**Comment by yutiansut** [comment]
```
my result

<html>
<body>
<!--StartFragment-->

a | b | c | d | t
-- | -- | -- | -- | --
i64 | i64 | i64 | i64 | i64
1 | 2 | 3 | 4 | 3

<!--EndFragment-->
</body>
</html>
```

**Comment by zeitgeber** [comment]
it works for me in v0.12.15 but not in v0.12.16

**Comment by yutiansut** [comment]
> it works for me in v0.12.15 but not in v0.12.16

yep
