### ISSUE TITLE
How to loop a groupby-dataframe by row with high performance?

### ISSUE THREAD

**Issue by longilacus** [pola-rs/polars#2471]
sample Dataframe:

`DataFrame( {
     "date": ["2010-01-01","2010-01-01","2010-01-02","2010-01-02"],
     "stock": ["AAPL", "IBM", "AAPL", "IBM"],
     "price": [100, 101, 200, 201]
    })`

In `rust` I need to do something to the two <stock> date by date, so I use `df.groupby("stock")`. I know I could use get_row("date") and turn this row into a Dataframe. But I also noticed that Polars did a lot work on Series and actions on rows couldn't achieve high performance. How could I get a Dataframe by "date" group with high performance?

**Comment by ritchie46** [comment]
Could you give a bit more context on what you want to achieve? Maybe a pandas example.

**Comment by longilacus** [comment]
|Date|Stock|Price|
|:-    |:------:|-:|
|2010-01-01|IBM|1000|
|2010-01-02|IBM|1001|
|2010-01-03|IBM|1002|
|2010-01-01|AAPL|2900|
|2010-01-02|AAPL|2901|
|2010-01-03|AAPL|2902|

With this Dataframe, each `Date` got multi `Stock`. I want to do something like calc the `Price` of `Stock` in each `Date`. So groupby -> `date`. 
In `Pandas`, I write this:

<pre>
df.groupby("date").apply(user_func)
</pre>  or like this
<pre> 
for idx , grp in df.group("date"):
    grp = grp.sort("price")
    #something etc
</pre>

As the len of df become much bigger, I want to use `Polars(Rust)` to do that. I tried some methods like: 
<pre>
df.lazy().groupby([col("date")]).agg([col("stock"),col("price")].collect();
for idx in 0..df_len:
    //then put each row into Dataframe use `from_rows_iter_and_schema`
//do something with data in this date
</pre>
or like
<pre>
let _date = df["date"].utf8().unwrap();
let _stock = df["stock"].list().unwrap();
let _price = df["price"].list().unwrap();
for (date, stock , price) in izip!(_date, _stock, _price){
     
     let mut stock = stock.unwrap();
     let mut price = price.unwrap();
     let df = DataFrame::new(vec![stock,price]);
     //do something with data in this date
}
</pre>
I need to lauch multiple mission like this, each mission with large data to groupby date and for loop the df.
How could I achieve the higest speed in this? Thank you!

**Comment by ritchie46** [comment]
If you want high performance you shouldn't generate `DataFrames` per group. It is possible but will require a lot of allocations.

That's why I asked what you want to do with your groups? Often we can do that with the polars expressions themselves. They are heavily optimized and make sure we access memory as effcient as possible.

So what is `do_something` / ;)

**Comment by longilacus** [comment]
`do_something` is for quant trading backtesting like :
(1) sort the df by some col
(2) pick the stock names by head(5) of new index
(3) exec `buy`  func which send the names and cost price into a `account dict`
(4) when the next `date` group comes, use new price minus cost price in account to calculate the profit
It's a highly personalized part, maybe can't easily achieve by expression?

**Comment by ritchie46** [comment]
Here a small part in python that shows how you maybe can prepare arguments or your function.

```python
csv = r"""2010-01-01,IBM,000
2010-01-02,IBM,001
2010-01-03,IBM,002
2010-01-01,AAP,2900
2010-01-02,AAP,2901
2010-01-03,AAP,2902""".encode()

df = pl.read_csv(csv, has_header=False, new_columns=["date", "stock", "price"])

(df.groupby("date")
 .agg([
     pl.col("price").sort().head(5).alias("lowest_price"),
     pl.col("stock").sort_by("price").head(5).alias("lowest_price_stock")
 ])
)
```

In rust you can then add a `select` and a `map_exprs` to apply a closure over the new columns.

The columns can then be downcasted into `ChunkedArrays` and iterated via `iter().zip()`.

This will likely have highest performance. 

If you really want, you can create `DataFrames` per group, but there will be a cost involved as row access is very expensive in a columnar memory format.

**Comment by longilacus** [comment]
Thanks a lot! So the key point is don't do `DataFrame` creation in the large for loop and pre-process data use expressions before the for loop.
