### ISSUE TITLE
Lazy evaluation incorrectly optimising operations

### ISSUE THREAD

**Issue by tikkanz** [pola-rs/polars#2472]
#### Are you using Python or Rust?
Python

#### What version of polars are you using?
0.12.17

#### What operating system are you using polars on?
Ubuntu 18.04

#### Describe your bug.
Depending on the order of operations, optimization a lazy pipeline fails. All orderings of the operations succeed if using eager.

#### What are the steps to reproduce the behavior?

Using this dataset:
```python
import polars as pl
df = pl.DataFrame({
    "group": ['54360-2001-0-20020312-4-1'
    ,'39444-2020-0-20210418-4-1'
    ,'68398-2020-0-20201216-4-1'
    ,'30910-2020-0-20210223-4-1'
    ,'71060-2020-0-20210315-4-1'
    ,'47959-2020-0-20210305-4-1'
    ,'63212-2018-0-20181007-2-2'
    ,'61465-2018-0-20181018-2-2']
})
```
This fails with with `RuntimeError: Any(ComputeError("Failed to determine supertype of Categorical and Int64"))`
```python
(   df.lazy()
    .with_column(
        pl.col("group").cast(pl.Categorical)
    )
    .with_column(
        pl.col("group")
        .cast(pl.Utf8)
        .str.extract(r'(\d+-){4}(\w+)-',2)
        .cast(pl.Int8)
        .alias("age")
    )
    .filter(
        pl.col("age").is_in([2])
    )
).collect()
```

This fails with with `RuntimeError: Any(SchemaMisMatch("cannot do is_in operation with left a dtype: Utf8 and right a dtype Int64"))`
```python
(   df.lazy()
    .with_column(
        pl.col("group")
        .cast(pl.Utf8)
        .str.extract(r'(\d+-){4}(\w+)-',2)
        .cast(pl.Int8)
        .alias("age")
    )
    .filter(
        pl.col("age").is_in([2])
    )
    .with_column(
        pl.col("group").cast(pl.Categorical)
    )
).collect()
```

This succeeds:
```python
(   df.lazy()
    .with_column(
        pl.col("group")
        .cast(pl.Utf8)
        .str.extract(r'(\d+-){4}(\w+)-',2)
        .cast(pl.Int8)
        .alias("age")
    )
    .with_column(
        pl.col("group").cast(pl.Categorical)
    )
    .filter(
        pl.col("age").is_in([2])
    )
).collect()
```

#### What is the expected behavior?
All of the above should work (as they do if not run with lazy).

**Comment by ritchie46** [comment]
Thanks for the report, this is fixed in #2476
