### ISSUE TITLE
Parse JSON dataframe

### ISSUE THREAD

**Issue by rhobro** [pola-rs/polars#2488]
Hi there,

I am coming from pandas in python to polars in Rust.

In pandas, I've been able to parse json data in the format of
```json
[{"k1": "v1", ... }, {"k1": "v1", ... }, ...]
```
into a dataframe with columns k1, k2 and so on.

Can this be done in polars in rust?

Thanks

**Comment by universalmind303** [comment]
currentlly the python & rust libraries only support reading from newline delimited json. 

```json
{"k1": "v1", ... },
{"k1": "v1", ... }
...
```
