### ISSUE TITLE
core dump when evaluating expression

### ISSUE THREAD

**Issue by zeitgeber** [pola-rs/polars#2494]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

filter

#### What version of polars are you using?

0.12.18/0.12.17

#### What operating system are you using polars on?

Ubuntu 20.04.1 LTS

#### Describe your bug.

when running a filter expression on a data frame with a single row with all nulls, program fails hard without error message and a core dump is produced. If there is more than 1 row with all nulls, program provides correct result. Was able to replicate issue in last couple of versions as well.

#### What are the steps to reproduce the behavior?

```
import polars as pl
df = pl.DataFrame({'a':[None,],'b':[None,]})
df.select(['a','b']).filter((pl.col('a')>0) & (pl.col('b')>0))
```

#### What is the actual behavior?

termination with core dump without error message or result.

#### What is the expected behavior?

should have provided 0 rows as result.

**Comment by ritchie46** [comment]
Thanks.I will take a look

**Comment by ritchie46** [comment]
Ok, it is a stackoverlfow. Still have to find where.
