### ISSUE TITLE
not yet implemented exception for date32 to json with row_oriented=True

### ISSUE THREAD

**Issue by zeitgeber** [pola-rs/polars#2495]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

to_json with row_oriented=True

#### What version of polars are you using?

0.12.18

#### What operating system are you using polars on?

Ubuntu 20.04.1 LTS

#### Describe your bug.

when using to_json with row_oriented=True on a df with date32 field, throws not implemented exception

#### What are the steps to reproduce the behavior?

```
import polars as pl
df = pl.DataFrame({
    "dt": ["2020-01-01"]
}).with_column(pl.col("dt").str.strptime(pl.Date))
df.to_json(row_oriented=True)
```

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/5524987/151677280-0ca64f13-bb13-43fc-a4d9-e24f7ef1b860.png)

#### What is the expected behavior?

json result with date exported

**Comment by jorgecarleitao** [comment]
arrow2 does not natively implement writing to date32 because it is unclear what the user wishes: an integer representing the number of days since epoch, a string (which format?).

It should not panic, though :/

**Comment by ritchie46** [comment]
I think formatting as a date string would be a good default as users who know enough about the internal representation could always cast to the physical type.

Casting to string before writing however is not zero copy and blows up memory. Or maybe we could do something similar to what is done in the csv writers (they accept a `fmt` option).

I could do a PR if you'd like.

**Comment by ritchie46** [comment]
Fixed
