### ISSUE TITLE
`skip_rows` in `read_csv` still reads first line as header

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2496]
#### Are you using Python or Rust?

Python 3.9.7

#### What version of polars are you using?

0.12.7

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

`read_csv` interprets the first row of a CSV file as a header when `skip_rows > 0`. It also seems to use other skipped rows for column type inference. This is in contrast to, for instance, both `pyarrow.csv.read_csv` and `pandas.read_csv`.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import io

with io.open("test.csv", "w") as f:
  f.write(
"""metadata
line
foo,bar
1,2
3,4
5,6
"""
  )

print(pl.read_csv("test.csv", skip_rows=2))
```

#### What is the actual behavior?

```
shape: (3, 1)
┌──────────┐
│ metadata │
│ ---      │
│ str      │
╞══════════╡
│ 1        │
├╌╌╌╌╌╌╌╌╌╌┤
│ 3        │
├╌╌╌╌╌╌╌╌╌╌┤
│ 5        │
└──────────┘
```

Several unexpected behaviors here: first, the first row was interpreted as the column header despite `skip_rows=2`. Consequently, the csv was assumed to only have a single column. Furthermore, the column type was inferred to be `str` despite only containing integers. Note that pyarrow performs as expected here, with `pa.csv.read_csv("test.csv", pa.csv.ReadOptions(skip_rows=2))` giving:

```
pyarrow.Table
foo: int64
bar: int64
----
foo: [[1,3,5]]
bar: [[2,4,6]]
```

However, providing `use_pyarrow=True` to `pa.read_csv` still gives the above unexpected result.

#### What is the expected behavior?

I would expect the row following the skipped rows to be interpreted as the column header, for all columns after that to be read, and for types to be inferred. Chopping off the first two rows manually gives the expected output:

```
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 6   │
└─────┴─────┘
```

**Comment by ritchie46** [comment]
Could you try settting `offset_schema_inference`

**Comment by qiemem** [comment]
Ah, thank you! Yes, setting both `skip_rows` and `offset_schema_inference` to 2 in the above example behaves as expected. Is that the intended behavior?

It looks like `pl.scan_csv`, on the other hand, has `offset_schema_inference` start from `skip_rows`.

**Comment by ritchie46** [comment]
Yes, the idea is that `skip_rows` is ambiguous. Do you want to keep the header and only read the second half of the file, or are the first rows garbage?

**Comment by qiemem** [comment]
That makes sense. I think I had expected `skip_rows` to start *all* reading after that number lines based on the behavior of other libraries. Is the `pl.scan_csv` behavior in incorrect then?

**Comment by qiemem** [comment]
I don't know how much the API is still being settled on, but I really like [pyarrow's approach here](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions). If the API is already finalized, feel free to ignore this comment. If not, perhaps the perspective of someone who has to deal with csv files with metadata preambles all the time might be useful.

PyArrow has two options, `skip_rows` (which skips *all* reading of the file for the given number of lines) and `skip_rows_after_names` (which skips which lines are read in as data for the given number of lines on top of `skip_rows`). What's nice about this is that it makes the two most common cases the easiest to express:

1. Skipping metadata at the beginning of a CSV file just uses `skip_rows`
2. Skipping the first n lines of data just uses `skip_rows_after_name`

And then only when you're in a situation that involves both wanting to skip a metadata preamble as well as skipping lines of data do you need both. Furthermore, `skip_rows_after_name` is always in terms of "data lines skipped", which feels easier to reason about.

With pypolars' `skip_rows` and `offset_schema_inference`, you have to provide both for number 1. It makes the situation where your headers are in the middle of your data easy... but I, at least, have never encountered such a case.

I hope this doesn't come across as "you should be like pyarrow" or anything, but I do think they made a smart design decision here that might be worth consideration. Also, as `skip_rows` is a very common argument name among csv readers, users might come in with preconceived notions about what it does (or, well... at least I did :P)

Anyway, this is kinda nitpicky stuff for sure. Pypolars is absolutely blowing my mind right now. Beyond the impressive performance, there are so many amazing design decisions here. The expression DSL is just phenomenal. Being able to code complex aggregations in groupby operations which then run in seconds on lazily loaded data that's too big for memory... just wonderful. And you guys had a new release with fixes to the bugs I reported in under 24 hours! Really great work.

**Comment by ritchie46** [comment]
Thanks for your feedback. It is valuable. The API of polars is not settled at all. We kinda throw features in the wild to get feedback and input, as its hard to predict how people will use it.

I think it makes sense. Will update this. :+1:
