### ISSUE TITLE
Failed join #2

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2498]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.18

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

Rows aren't joining that should. I.e. on an inner join, some rows are being omitted from the joined data frame that should be there. On a left join, some of the right columns are filled with null values when they shouldn't be.

#### What are the steps to reproduce the behavior?

Output:
```
>>> ./reproduce_error.py
--right_df--
shape: (1, 4)
┌──────────┬───────────────────┬───────────────────┬────────────────┐
│ join_col ┆ new_col_from_join ┆ table_1_indicator ┆ other_join_len │
│ ---      ┆ ---               ┆ ---               ┆ ---            │
│ i64      ┆ f64               ┆ bool              ┆ i64            │
╞══════════╪═══════════════════╪═══════════════════╪════════════════╡
│ 59546483 ┆ 6.9900e-46        ┆ true              ┆ null           │
└──────────┴───────────────────┴───────────────────┴────────────────┘
--left_df--
shape: (1, 3)
┌────────────┬──────────┬────────────────┐
│ temp       ┆ join_col ┆ other_join_len │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ i64      ┆ i64            │
╞════════════╪══════════╪════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           │
└────────────┴──────────┴────────────────┘
--join--
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ null              ┆ null              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```
Notice that the two columns being joined on ('join_col' and 'other_join_len') are the same in the right and left DFs, but the right columns don't show up in the joined DF.

Reproducing code
```
#!/usr/bin/env python3

import polars as pl

right_df_1 = pl.scan_csv(
    'repro_tsv_1.txt',
    sep='\t',
).select([
    'join_col',
    'new_col_from_join',
    pl.lit(True).alias('table_1_indicator'),
    pl.lit(None).cast(int).alias('other_join_len'),
])

right_df_2 = pl.scan_csv(
    'repro_tsv_2.txt',
    sep='\t',
).select([
    'join_col',
    'new_col_from_join',
    pl.col('other_join_col').str.lengths().cast(int).alias('other_join_len'),
]).groupby(['join_col', 'other_join_len']).agg([
    pl.col('new_col_from_join').min().alias('new_col_from_join'),
]).with_columns([
    pl.lit(False).alias('table_1_indicator')
]).select([ 'join_col', 'new_col_from_join', 'table_1_indicator', 'other_join_len'])

right_df = pl.concat([right_df_1, right_df_2])
print('--right_df--')
print(right_df.filter((pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()).collect())

rownames_fname = 'munged_rownames.txt'
with open(rownames_fname) as var_file:
    rownames = [line.strip() for line in var_file if line.strip()]

left_df = pl.DataFrame({
    'temp': rownames,
}).lazy().with_columns([
    pl.col('temp').str.extract('^[^_]*_([^_]*)', 1).cast(int).alias('join_col'),
    pl.col('temp').str.extract('^[^_]*_[^_]*_([^_]*)$', 1).str.lengths().cast(int).alias('other_join_len'),
])
print('--left_df--')
print(left_df.filter((pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()).collect())

total_df = left_df.join(
    right_df,
    how='left',
    on=['join_col', 'other_join_len']
).collect()
print('--join--')
print(total_df.filter((pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()))
```

[repro_tsv_1.txt](https://github.com/pola-rs/polars/files/7966164/repro_tsv_1.txt)
[repro_tsv_2.txt](https://github.com/pola-rs/polars/files/7966165/repro_tsv_2.txt)
[munged_rownames.txt](https://github.com/pola-rs/polars/files/7966175/munged_rownames.txt)

**Comment by ritchie46** [comment]
This is likely due to a wrong predicate pushdown. Could you run with predicate pushdown set to False?

**Comment by LiterallyUniqueLogin** [comment]
How?

A random test, but collecting the left and right data frames before the join doesn't fix the issue.

**Comment by LiterallyUniqueLogin** [comment]
Found the option  - its still an error even after setting predicate pushdown to False, or setting no_optimization to True.

**Comment by ritchie46** [comment]
Could you explain a bit what you think is wrong?

What is expected behavior? You've sent a lot of data and a script, I don't really know what I am looking at. Could you maybe break it down to the core?

**Comment by LiterallyUniqueLogin** [comment]
Look at the output from the script execution: the left and right data frames each have a record with the values (59546483, null) for the two join columns. But calling `join` doesn't join these into one record.

**Comment by ritchie46** [comment]
So the whole script could be replaced by dataframes of 1 row as an example?🙈

And what is the expected output according to you?

**Comment by LiterallyUniqueLogin** [comment]
If you simply construct those two rows and join them, the join works:
```
>>> pl.DataFrame({'a': [59546483], 'c': [6.9900e-46]}).with_column(pl.lit(None).cast(int).alias('b')).join(pl.DataFrame({'a': [59546483]}).with_column(pl.lit(None).cast(int).alias('b')), how='left', on=['a', 'b'])
shape: (1, 3)
┌──────────┬────────────┬──────┐
│ a        ┆ c          ┆ b    │
│ ---      ┆ ---        ┆ ---  │
│ i64      ┆ f64        ┆ i64  │
╞══════════╪════════════╪══════╡
│ 59546483 ┆ 6.9900e-46 ┆ null │
└──────────┴────────────┴──────┘
```

But something in the code I gave you is causing some (but not all) of the columns to fail to join. If I knew what the answer was, I would have given you a one line example. But I don't, so instead I gave you a reproducible problem.

If you don't understand the error I'm posting, please ask and I'll clarify. But don't be an ass - it's your bug.

**Comment by ritchie46** [comment]
> If you don't understand the error I'm posting, please ask and I'll clarify. But don't be an ass.  - it's your bug.

I am just trying to understand what happens and there are clear issue templates requesting for expected outputs.

I don't think you recognize how much time it costs me to handle all issues daily. By breaking your problem down to bitsize problems and following the issue templates this time can be a bit shared by the community.

>  it's your bug.

...

**Comment by LiterallyUniqueLogin** [comment]
I apologize if it wasn't clear, I can try to be more so in the future.

Just so you're aware, it took me multiple hours of work to get it to what I showed you - so time's being spent on both ends. I didn't write my code originally to make a good reproducible example, I wrote it to do what I needed! :)

Once I realized there was a polars bug, I had to pull my code apart piece by piece to find the kernel that caused the problem.

**Comment by LiterallyUniqueLogin** [comment]
And, for what it's worth, I am qutie apprerciative of the amount of effort you put into responding to issues daily. It's what's made me excited to post bugs to you - unlike any other open source project I've poked at, you actually respond and fix them quickly!

**Comment by ritchie46** [comment]
Ok, let's try again. I am really trying to understand. 

So we have these two inputs that you filter on this predicate:

```python
pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()
```

Applying this filter gives you 

# left

```
shape: (1, 3)
┌────────────┬──────────┬────────────────┐
│ temp       ┆ join_col ┆ other_join_len │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ i64      ┆ i64            │
╞════════════╪══════════╪════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           │
└────────────┴──────────┴────────────────┘
```

# right

```
shape: (1, 4)
┌──────────┬───────────────────┬───────────────────┬────────────────┐
│ join_col ┆ new_col_from_join ┆ table_1_indicator ┆ other_join_len │
│ ---      ┆ ---               ┆ ---               ┆ ---            │
│ i64      ┆ f64               ┆ bool              ┆ i64            │
╞══════════╪═══════════════════╪═══════════════════╪════════════════╡
│ 59546483 ┆ 6.9900e-46        ┆ true              ┆ null           │
└──────────┴───────────────────┴───────────────────┴────────────────┘
```

Which you left join on 2 columns: `join_col` and `other_join_len` and produces:

```
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ 6.9900e-46        ┆ true              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```

Now what should the expected output be? Do you mean that the `null` values should be matching in the join?

**Comment by LiterallyUniqueLogin** [comment]
Yes, the result I expect is that the null values match. That's what happens in my one line example above. And that's the output you just posted:

```
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ 6.9900e-46        ┆ true              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```

But when I run the code I see:

```
--join--
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ null              ┆ null              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```

where the join rows don't match (possibly because the null values aren't matching, not sure).

Do you intend null values to match?

**Comment by ritchie46** [comment]
Yes, missing values are matching in polars. 

Anyway.. When I run your code on `polars==0.12.19` I get:

```
--join--
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ 6.9900e-46        ┆ true              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```

So maybe it's already fixed? Could you try updating?

**Comment by LiterallyUniqueLogin** [comment]
I just updated and reran, I'm still getting the error

```
--right_df--
shape: (1, 4)
┌──────────┬───────────────────┬───────────────────┬────────────────┐
│ join_col ┆ new_col_from_join ┆ table_1_indicator ┆ other_join_len │
│ ---      ┆ ---               ┆ ---               ┆ ---            │
│ i64      ┆ f64               ┆ bool              ┆ i64            │
╞══════════╪═══════════════════╪═══════════════════╪════════════════╡
│ 59546483 ┆ 6.9900e-46        ┆ true              ┆ null           │
└──────────┴───────────────────┴───────────────────┴────────────────┘
--left_df--
shape: (1, 3)
┌────────────┬──────────┬────────────────┐
│ temp       ┆ join_col ┆ other_join_len │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ i64      ┆ i64            │
╞════════════╪══════════╪════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           │
└────────────┴──────────┴────────────────┘
--join--
shape: (1, 5)
┌────────────┬──────────┬────────────────┬───────────────────┬───────────────────┐
│ temp       ┆ join_col ┆ other_join_len ┆ new_col_from_join ┆ table_1_indicator │
│ ---        ┆ ---      ┆ ---            ┆ ---               ┆ ---               │
│ str        ┆ i64      ┆ i64            ┆ f64               ┆ bool              │
╞════════════╪══════════╪════════════════╪═══════════════════╪═══════════════════╡
│ 1_59546483 ┆ 59546483 ┆ null           ┆ null              ┆ null              │
└────────────┴──────────┴────────────────┴───────────────────┴───────────────────┘
```
Now I'm unclear what could be causing this. Maybe this is a difference in a dependency version?

**Comment by LiterallyUniqueLogin** [comment]
When I run it on my local computer I get the correct result you're seeing ....

**Comment by LiterallyUniqueLogin** [comment]
On my remote computer I used my ongoing environment, a scratch environment with python 3.7 (`mamba create -n <env_name> python=3.7 ; pip install polars`) and a python 3.10 environment (`mamba create -n <env_name> python ; pip install polars`). All failed to join properly. For each, I downloaded the example I sent you just to be sure it was exactly the same code that you're seeing.

Any ideas on how to debug from here?

**Comment by ritchie46** [comment]
What are differences in os on that machine and your machine?

**Comment by ritchie46** [comment]
Hmm.. hard to say. I think you should try to remove all code before the join. 

maybe you can add a `map` function right before the joins where you write the data from that point to disk (with allow optimizations).

Then from that parquet/csv try to remove rows until we can pinpoint what causes it?

**Comment by LiterallyUniqueLogin** [comment]
Removing 11 rows (not including the row with 59546483) from seemingly anywhere in the rownames file causes this to work, remove none or 10 or fewer and it still fails. 

Those rows get passed as a list to the DF
```
left_df = pl.DataFrame({
    'temp': rownames,
})
```
Are there any corner cases regarding length of string arrays in polars?

**Comment by LiterallyUniqueLogin** [comment]
Oh! Moving the row in munged_rownames.txt with `1_59546483` to the top of the file caused the join to succeed regardless of file length. Maybe that's also a clue?

**Comment by ritchie46** [comment]
And were you successful in reproducing it locally? The I could as well maybe.

Some other things that may help. Can you send the query plan? That way we can ensure that we do the same.

**Comment by LiterallyUniqueLogin** [comment]
I was not successful in reproducing the bug locally. The bug only shows up on the remote machine for me. And on the remote machine, reducing the size of munged_rownames.txt or moving the line `1_59546483` to the top caused the error to disappear.

The optimized plan (`total_df.describe_optimized_plan()`)
```
JOIN
        (DATAFRAME(in-memory): ["temp"];
        project */1 columns     |       details: None;
        selection: "None"


WITH COLUMNS [col("temp").str.extract().cast(Int64).alias("join_col"), col("temp").str.extract().str.len().cast(Int64).alias("other_join_len")])
WITH
        (SELECT 3 COLUMNS: [col("join_col"), col("new_col_from_join"), null.cast(Int64).alias("other_join_len")]
FROM
CSV SCAN repro_tsv_1.txt; PROJECT 2/27 COLUMNS; SELECTION: None)
ON (left: [col("join_col"), col("other_join_len")] right: [col("join_col"), col("other_join_len")])
```

The unoptimized plan (`total_df.describe_plan()`)
```
JOIN
        (DATAFRAME(in-memory): ["temp"];
        project */1 columns     |       details: None;
        selection: "None"


WITH COLUMNS [col("temp").str.extract().cast(Int64).alias("join_col"), col("temp").str.extract().str.len().cast(Int64).alias("other_join_len")])
WITH
        (SELECT 3 COLUMNS: [col("join_col"), col("new_col_from_join"), null.cast(Int64).alias("other_join_len")]
FROM
CSV SCAN repro_tsv_1.txt; PROJECT */27 COLUMNS; SELECTION: None)
ON (left: [col("join_col"), col("other_join_len")] right: [col("join_col"), col("other_join_len")])
```

The two plans look identical as far as I can tell

**Comment by ritchie46** [comment]
They are not similar. The optimized plan does the projection of two columns at the csv_scan:

```
CSV SCAN repro_tsv_1.txt; PROJECT 2/27 COLUMNS; SELECTION: None)
ON (left: [col("join_col"), col("other_join_len")] right: [col("join_col"), col("other_join_len")])
```

**Comment by ritchie46** [comment]
I don't know. Were you able to get the bug from only hte join code?

So you add a `map` write to disk. And then write another query that only loads and joins.

**Comment by LiterallyUniqueLogin** [comment]
There seems to be some problem with nulls. The cast below is necessary because the csv has no-nonnull entries in that column, so polars loads it as a str column, but I need to be a int column for the downstream join.  

Printing it looks good - you get an int column with all null values. But filtering on that doesn't return anything.

Script:
```
#!/usr/bin/env python3

import polars as pl

right_df = pl.scan_csv(
    'right.csv'
).with_column(pl.col('other_join_len').cast(int, strict=False).alias('other_join_len'))
print('--right--')
print(right_df.collect())
print('--filter--')
print(right_df.filter(pl.col('other_join_len').is_null()).collect())
```

Output:
```
>>> ./script.py
--right--
shape: (6, 3)
┌──────────┬───────────────────┬────────────────┐
│ join_col ┆ new_col_from_join ┆ other_join_len │
│ ---      ┆ ---               ┆ ---            │
│ i64      ┆ f64               ┆ i64            │
╞══════════╪═══════════════════╪════════════════╡
│ 48671145 ┆ 2.0600e-79        ┆ null           │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 55594626 ┆ 9.9000e-67        ┆ null           │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 19803904 ┆ 6.2700e-95        ┆ null           │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 59546483 ┆ 6.9900e-46        ┆ null           │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 23877835 ┆ 2.2800e-85        ┆ null           │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10049173 ┆ 6.0300e-35        ┆ null           │
└──────────┴───────────────────┴────────────────┘
--filter--
shape: (0, 3)
┌──────────┬───────────────────┬────────────────┐
│ join_col ┆ new_col_from_join ┆ other_join_len │
│ ---      ┆ ---               ┆ ---            │
│ i64      ┆ f64               ┆ i64            │
╞══════════╪═══════════════════╪════════════════╡
└──────────┴───────────────────┴────────────────┘
```

[right.csv](https://github.com/pola-rs/polars/files/7980010/right.csv)

**Comment by LiterallyUniqueLogin** [comment]
Hi @ritchie46 - the post above has a small issue that is reproducible on both of my machines. Can you please take a look?

**Comment by ritchie46** [comment]
Ok, I have got a fix. :) 

I hope it helps the larger case.
