### ISSUE TITLE
read_csv and scan_csv produce parsing errors when given file with quoted boolean values

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2499]
#### Are you using Python or Rust?

Python 3.9.7

#### What version of polars are you using?
0.12.17

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

If a file contains a quoted boolean value (e.g. `"true"` or `"false"`), `read_csv` and `scan_csv` produce a parsing error. Quoted integers and floats, on the other hand, are parsed and have type inferred correctly.

Apologies for multiple bug reports in 24 hours. Very excited about polars and would love to be able to start using it in my research.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

with open("test.csv", "w") as f:
  f.write(
"""foo,bar,baz
1,"4","false"
3,"5","false"
5,"6","true"
"""
  )

pl.read_csv("test.csv")
```

#### What is the actual behavior?

The following error is produced:

```
RuntimeError: Any(ComputeError("Could not parse \"false\" as dtype Boolean at column 3.\n                                            The total offset in the file is 6 bytes.\n\n                                            Consider running the parser `with_ignore_parser_errors=true`\n                                            or consider adding \"false\" to the `null_values` list."))
```

As a minor note, `with_ignore_parser_errors` does not appear to be the name of an argument to `read_csv`, nor is `true` a valid Python literal. I assume this should be `ignore_errors=True` (which results in nulling out the fields).

#### What is the expected behavior?

Ideally, I would expect the file to be imported without error and the column type inferred to be boolean. In the above case, this would produce the following dataframe. Especially given that quoted numbers are inferred to be numeric types, this would feel consistent:

```
shape: (3, 3)
┌─────┬─────┬───────┐
│ foo ┆ bar ┆ baz   │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ bool  │
╞═════╪═════╪═══════╡
│ 1   ┆ 4   ┆ false │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3   ┆ 5   ┆ false │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 5   ┆ 6   ┆ true  │
└─────┴─────┴───────┘
```

Alternatively, inferring the fields to be strings would be reasonable as well, though less ideal. For what it's worth, Pandas, pyarrow, and vaex do the former.

**Comment by slonik-az** [comment]
Would it be more logical to parse quoted strings as strings? After all, quotes are there for a reason. `"false"` is a text "false" and `"4"` is a a text that happens to be a valid digit as well.

**Comment by qiemem** [comment]
In my experience, it's not uncommon to have datasets in which all fields are quoted regardless of type. I have found it convenient in other libraries to be pretty aggressive about type inference; as I mention, other common libraries happily interpret quoted fields as non-string types.

Perhaps an option such as `treat_quoted_fields_as_strings` to allow for both behaviors would offer the best of both worlds?

**Comment by qiemem** [comment]
Wow, thanks for fast fixes!
