### ISSUE TITLE
`mean` gives the incorrect answer if `sum` would overflow for the column type

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2500]
#### Are you using Python or Rust?

Python 3.9.7

#### What version of polars are you using?

0.12.1

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

`pl.mean` and `Series.mean` give an incorrect answer in cases where the `pl.sum` would overflow for the column type, despite the answer being given given as a float64.

Again, apologies for the rapid bug reports; just filing as I run into them.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import numpy as np

print(pl.Series(np.array([255] * (1<<23)).astype('int32')).mean())
print(pl.Series(np.array([255] * (1<<24)).astype('int32')).mean())
print(pl.Series(np.array([255] * (1<<7)).astype('int16')).mean())
print(pl.Series(np.array([255] * (1<<8)).astype('int16')).mean())
print(pl.Series(np.array([255] * (1<<21)).astype('float32')).mean())
```

#### What is the actual behavior?

```
-1.0
255.0
-1.0
255.0
255.49803161621094
```

#### What is the expected behavior?

```
255.0
255.0
255.0
255.0
255.0
```

**Comment by ritchie46** [comment]
Thanks. Yes maybe we should cast the smaller integers before summing.

**Comment by qiemem** [comment]
That would be great! Thanks for the quick reply. Note that float32s are affected as well.

**Comment by ritchie46** [comment]
> That would be great! Thanks for the quick reply. Note that float32s are affected as well.

Yes.. for f32 I don't consider this as a bug. Polars/Rust numeric operations overflow. So does that of numpy. It is a gotcha that users should keep in mind.

For small integers overflow is very likely and in that case we cast

**Comment by qiemem** [comment]
That seems reasonable, especially if there's a significant performance impact. Measuring it now with a naive `Series.cast.mean`, I do see a pretty big performance hit. That said, I suppose I would expect it to not overflow because the returned value (if not the declared type) is a float64. Indeed, both numpy and pandas gives the expected value:

```
f32arr = np.array([255] * (1<<24), dtype='float32')
print(f32arr.mean())
print(pd.Series(f32arr).mean())
print(pl.Series(f32arr).mean())
```

produces:

```
255.0
255.0
255.93724060058594
```

Also, even if the return type is float32, there's the classic trick of dividing by n as you go... though again performance... I suppose `torch` actually (surprisingly) gives the right answer here as well, though the return type is float32.

**Comment by ritchie46** [comment]
It seems that we must look at numerically more stable approach than the naive `sum / n`.

**Comment by qiemem** [comment]
Oh it looks like I was mistaken about numpy's behavior... to some degree anyway:

![image](https://user-images.githubusercontent.com/28215/152200957-211f6474-ffee-48e5-89bf-c8f7a11d1a28.png)

From: https://numpy.org/doc/stable/reference/generated/numpy.mean.html

How strange. I wonder why my above example worked in numpy... it should have overflowed the mantissa...
