### ISSUE TITLE
median no longer works with floats

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#2502]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.18

#### What operating system are you using polars on?

Ubuntu

#### Describe your bug.

`series.median()` no longer works with `Float64` or `Float32`

#### 0.12.18
`pip install -U polars`
```python
import polars as pl
series = pl.Series("floats", [1, 1, 10], pl.Float64)
print(series.median())
# None
```

#### 0.12.9
`pip install polars==0.12.9`
```python
import polars as pl
series = pl.Series("floats", [1, 1, 10], pl.Float64)
print(series.median())
# 1.0
```

**Comment by universalmind303** [comment]
This actually breaks the default `median` behavior for nodejs. 
The default numeric type for JS is `Float64`, so you need to do an explicit cast to int/uint to perform median now.

**Comment by ritchie46** [comment]
Thanks, this is a simple dispatch bug. I already got a fix.
