### ISSUE TITLE
`shift` inside a `groupby` has unexpected behavior in binary operators

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2509]
#### Are you using Python or Rust?

Python 3

#### What version of polars are you using?

0.12.19

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

If you group by a column and then, in the `agg`, perform a shift on one column and then perform an element-wise operation on the shifted column with another column, you may get unexpected results. Shifting alone appears to be fine. It's only when it is combined with an element-wise operation that things get weird. Furthermore, it appears to depend on which column comes first in the operation, even for commutative operations. `shift_and_fill` shows the same behavior.

#### What are the steps to reproduce the behavior?

The example here runs the grouped-by operation and then the equivalent operation on a non-grouped-by dataframe that has been filtered to contain the same elements as a group. The operation used is `+` and the elements have been chosen to make it clear what the operands are in each case. Several alternative expressions are included to demonstrate when polars behaves as expected and when it does not.

```python
runs = pl.from_records(
    [
        {"x": x, "y": y}
        for x in range(5)
        for y in range(0, 50, 10)
    ]
)

# Fine
#exp = (pl.col("x") + pl.col("y").shift(-1)).list().alias("sums")
# Broken
#exp = (pl.col("y").shift(-1) + pl.col("x")).list().alias("sums")
# Fine
#exp = (pl.col("x").shift(-1) + pl.col("y")).list().alias("sums")
# Broken
exp = (pl.col("y") + pl.col("x").shift(-1)).list().alias("sums")

grouped = runs.groupby("x").agg(exp).sort("x")

for x in range(5):
    actual = grouped.filter(pl.col("x") == x)["sums"][0]
    expected = runs.filter(pl.col("x") == x).select(exp)["sums"][0]
    print(f"{x}: expected: {' '.join(map(str, expected.to_list()))}")
    print(  f"     actual: {' '.join(map(str, actual.to_list()))}")
```

#### What is the actual behavior?

```
0: expected: 0 10 20 30 None
     actual: 4 14 24 34 None
1: expected: 1 11 21 31 None
     actual: 1 11 21 31 None
2: expected: 2 12 22 32 None
     actual: 2 12 22 32 None
3: expected: 3 13 23 33 None
     actual: 3 13 23 33 None
4: expected: 4 14 24 34 None
     actual: 0 10 20 30 None
```

#### What is the expected behavior?

```
0: expected: 0 10 20 30 None
     actual: 0 10 20 30 None
1: expected: 1 11 21 31 None
     actual: 1 11 21 31 None
2: expected: 2 12 22 32 None
     actual: 2 12 22 32 None
3: expected: 3 13 23 33 None
     actual: 3 13 23 33 None
4: expected: 4 14 24 34 None
     actual: 4 14 24 34 None
```

#### Extra context

This might seem like a weird thing to stumble on... I work on a lot of simulation data. I discovered this while while computing the weighted mean of a value in each run, where the weight was based on another field in the previous time step. Thus, I wanted to group by the run and multiply one column by a shifted copy of another column to apply the weights.

**Comment by ritchie46** [comment]
Thanks I will pick this up. It seems like a temporary unintende fix is using `maintain_order=True`

```python
df.groupby("x", maintain_order=True).agg(expr)
```

*Note that if ordering is important it should be preferred to call on groupby, as that is cheaper than sorting afterwards*

**Comment by qiemem** [comment]
Wow, thanks again for quick reply and fix!

To be clear, `maintain_order` preserves order *between* groups, correct? From playing around it looked like order within groups is preserved even without it.

That is, in the above example, just doing `groupby("x")` will preserve the order of the y-values for each x, but not preserve the order of the x groups, yes? Whereas `groupby("x", maintain_order=True)` will maintain the order of both. In my case, ordering within groups is important, but between groups is not.

Adding `maintain_order` fixed the toy cases I had, but I'm still getting unexpected results with my (much larger) real data... I haven't tried HEAD yet, but hopefully I'll get a chance to today.

**Comment by ritchie46** [comment]
> Adding maintain_order fixed the toy cases I had, but I'm still getting unexpected results with my (much larger) real data... I haven't tried HEAD yet, but hopefully I'll get a chance to today.

Well, you always compile from source. Then it is fixed. :) I plan to release and of the week.

> To be clear, maintain_order preserves order between groups, correct? From playing around it looked like order within groups is preserved even without it.

> That is, in the above example, just doing groupby("x") will preserve the order of the y-values for each x, but not preserve the order of the x groups, yes? Whereas groupby("x", maintain_order=True) will maintain the order of both. In my case, ordering within groups is important, but between groups is not.

Yes, `maintain_order` sorts the group order. This requires extra work because we hash the groups (thus creating random orders). Most of the times it shuold not matter so polars does not make that the default because the sorting is expensive. 

Nonetheless its cheaper to sort the indicators of the groupby (which we have in memory), than the materialized dataframe after the groupby. The latter is very expensive as we materialize the table and then need to sort and materialize again.

**Comment by qiemem** [comment]
> Well, you always compile from source. Then it is fixed. :) I plan to release and of the week.

Tried HEAD, it is indeed fixed! Thank you again! Also, quite excited to start digging into the source myself :smile:
