### ISSUE TITLE
Not able to create pl.Dataframe from an empty pandas dataFrame using pl.from_pandas()

### ISSUE THREAD

**Issue by DS-Kunwar** [pola-rs/polars#2512]
439     if len(data_dict) > 0:
    440         batches = pa.table(data_dict).to_batches()
--> 441         pydf = PyDataFrame.from_arrow_record_batches(batches)
    442     else:
    443         pydf = pli.DataFrame([])._df

RuntimeError: Other("empty table")

**Comment by ritchie46** [comment]
How do you recreate this error?

I can run this

```python
import pandas as pd
import polars as pl
pl.from_pandas(pd.DataFrame())
```

**Comment by DS-Kunwar** [comment]
@ritchie46 
please check the below scenario:

`pandas_df = pd.DataFrame({
        "A": [],
        "fruits": [],
        "B": [],
        "cars": [],
        "optional": [],
    })
polars_df = pl.from_pandas(pandas_df)
`
