### ISSUE TITLE
pl.read_sql() fail for empty result set from query, it should return an empty DataFrame like Pandas

### ISSUE THREAD

**Issue by DS-Kunwar** [pola-rs/polars#2530]
#### Are you using Python or Rust?

Python==3.9.7

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.12.20

#### What operating system are you using polars on?

Windows 10

#### Describe your bug.

pl.read_sql("select name, salary from emp where 1=2", POSTGRE_URL) code should return an empty DataFrame with name and salary as columns, but it fails with error. **Other("empty table")**

#### What are the steps to reproduce the behavior?

sql_query = "select name, salary from emp where 1=2"
df = pl.read_sql(sql_query, POSTGRE_URL)

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```

sql_query = "select name, salary from emp where 1=2"
df = pl.read_sql(sql_query, POSTGRE_URL)
```

**Example**

```python
sql_query = "select name, salary from emp where 1=2"
df = pl.read_sql(sql_query, POSTGRE_URL)
```

#### What is the actual behavior?

import pandas as pd

df = pd.read_sql(query, cnxn) # works fine

What do you think polars should have done?

Should have produce the same result as Pandas, 
please note to have the same datatype of column as of SQL (Postgre)

**Comment by NekoApocalypse** [comment]
Problem still exists.

I'm using Python 3.8.10, Polars 0.13.3 on Ubuntu 20.04.

When I'm using `pl.read_sql(sql, conn_str)` and sql returns 0 rows, the following error occures:
```
RuntimeError: Any(ShapeMisMatch("Could not create a new DataFrame from Series. The Series have different lengths"))
```
