### ISSUE TITLE
Add a "starts_at" integer param for "with_row_count" method

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2539]
#### Describe your feature request

Add a `starts_at` (or equivalent) integer param to `with_row_count` (dataframe and lazyframe), so it does not have to be zero-indexed. Can easily add 1 via `with_column` (to match the behaviour of the SQL "row_number" function, for example), but this is obviously less efficient and more verbose:

```python
lazyframe.with_row_count(
    name = '_rownum_'
).with_column(
    expr = (col('_rownum_') + 1).alias( '_rownum_' )
)
```
vs (proposed)
```python
lazyframe.with_row_count( name='_rownum_', starts_at=1 )
```
#### Also
The row number generated by the above is currently hard-constrained to an 32bit uint, so fails on datasets with more than 4.295 billion rows. Wouldn't be the common case, but I can imagine operating on datasets of that size at some point; worth having a mechanism for making that 64bit if needed? (No point giving up that memory by default, obviously).

**Comment by ritchie46** [comment]
> The row number generated by the above is currently hard-constrained to an 32bit uint, so fails on datasets with more than 4.295 billion rows. Wouldn't be the common case, 

There are more design decisions made around that limit. Things are a lot more efficient if we use `u32` as the limit. If your dataset get larger than this we need to start looking at a scheduler or maybe compile a version of polars with large indices. But I haven't seen anybody reach it yet.

**Comment by alexander-beedie** [comment]
> > The row number generated by the above is currently hard-constrained to an 32bit uint, so fails on datasets with more than 4.295 billion rows. Wouldn't be the common case,
> 
> There are more design decisions made around that limit. Things are a lot more efficient if we use `u32` as the limit. If your dataset get larger than this we need to start looking at a scheduler or maybe compile a version of polars with large indices. But I haven't seen anybody reach it yet.

Indeed - totally sensible default behavior; only crossed my mind as we've got a case that is getting towards 1 billion - but even then, still 3 billion headroom... ;)

**Comment by ritchie46** [comment]
I will close this as we've added this.
