### ISSUE TITLE
Suggested improvements for User Guide

### ISSUE THREAD

**Issue by PieterKouyzer** [pola-rs/polars#2540]
Hi,

I was going through the user guide (https://pola-rs.github.io/polars-book/user-guide/index.html) to get a feel for the library and ran into some discrepancies I thought you might want to know about. I wasn't sure how to provide this information otherwise, so here is just an overview of the things I noticed:

- Some snippets have "print(df)", while they should have "print(out)". In the Expressions page (3.1) + Contexts page (3.2) + Time-series page (8).
- Expressions page (3.1) arrow right to go to next page, returns you to the Expressions page again.
- Getting the US congress dataset code sample on GroupBy page (3.3) is very unclear about how to replicate ("from .dataset import dataset" doesn't work and is rather unclear how to execute other than that snippet)
- Gotcha's link in Numpy universal functions page (3.6) gives a 404 error.
- Performance- Strings page (10.1), final lazy join on categorical data snippet results in error: "Any(ValueError("joins on categorical dtypes can only happen if they are created under the same global string cache"))"

Cheers,
Pieter

**Comment by ritchie46** [comment]
Thanks.. I have copied the issue to the repo that backs the user guide.
