### ISSUE TITLE
groupby apply join

### ISSUE THREAD

**Issue by alex-coch** [pola-rs/polars#2541]
Hello!

I try to do the code from Pandas like:
df.groupby(['str1']).apply(lambda x:";".join(x[1'str1'].values))
where df['str1'][0] equals '357125861,434189844,534941491'

When I start the code:
df.select([
  "*",
  pl.col("str1").apply(lambda x:";".join(x['str1'])).alias("bnew")
 ])['bnew']

I get the error:
Feb 4, 2022, 4:41:04 PM	WARNING	WARNING:root:kernel a6e0e984-e119-40bd-a7cd-c8ad7fefdace restarted
Feb 4, 2022, 4:41:04 PM	INFO	KernelRestarter: restarting kernel (1/5), keep random ports
Feb 4, 2022, 4:41:03 PM	WARNING	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Feb 4, 2022, 4:41:03 PM	WARNING	thread '<unnamed>' panicked at 'python apply failed: string indices must be integers', src/lazy/apply.rs:59:19

Where can I find the explanantion of this error, how can I fix it, and how can I use groupby apply join together?

**Comment by zundertj** [comment]
Thank you for reporting this. I am trying to reproduce this, but I am unable to. This is as far as I got based on your description:

```python
import polars as pl

df = pl.DataFrame({
    "str1": ['357125861,434189844,534941491']
})

df.select(["*", pl.col("str1").apply(lambda x:";".join(x)).alias("bnew")])['bnew']
```
which outputs:
```
shape: (1,)
Series: 'bnew' [str]
[
        "3;5;7;1;2;5;8;...
]
```

To help us fixing the bug, it would be useful if you could:
1. post a complete code example, including dataframe set up and exact code, like I did in the snippet above. You can use three backticks and python to have highlighting: \```python <code here>
2. post the exact expected output
3. list the version and type of Operating System, Polars version and Python version

**Comment by alex-coch** [comment]
Tthe solution from https://github.com/pola-rs/polars/issues/2549#issuecomment-1031836689 helps me, thanks a lot!
