### ISSUE TITLE
Add a "row_number" window function

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2542]
#### Describe your feature request

There is a frame-level `with_row_count` method, but I haven't spotted an easy way to assign a row number within a partition; `rank(method='ordinal')` is somewhat along those lines (but obviously not quite), and there are various inefficient things you can do with `apply` and a python-side lambda, but a native `row_number` expression would be great.

(In-line with #2539, a `starts_at` param would be useful here too, so the resulting values don't have to be zero-indexed).

**Comment by ritchie46** [comment]
Something like this?

```python
print((pl.DataFrame({
    "groups": ["A", "B", "C", "C", "B", "B"]
})
 .groupby("groups")
 .agg(pl.lit(0).cumcount())
))

```

```
shape: (3, 2)
┌────────┬────────────┐
│ groups ┆ literal    │
│ ---    ┆ ---        │
│ str    ┆ list [u32] │
╞════════╪════════════╡
│ B      ┆ [0, 1, 2]  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C      ┆ [0, 1]     │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A      ┆ [0]        │
└────────┴────────────┘

```

**Comment by markfairbanks** [comment]
@ritchie46 Any reason why one of these works and one of these doesn't when I use `.with_columns()`? It seems like they should work the same:

```python
import polars as pl
from polars import col

df = pl.DataFrame(dict(x = range(3)))

# Works
(
    df.with_columns(pl.lit(0).alias('row_num'))
    .with_columns(col('row_num').cumcount())
)
```

```
┌─────┬─────────┐
│ x   ┆ row_num │
│ --- ┆ ---     │
│ i64 ┆ u32     │
╞═════╪═════════╡
│ 0   ┆ 0       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 1       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2       │
└─────┴─────────┘
```

```python
# Fails
df.with_columns(pl.lit(0).cumcount().alias('row_num'))
```

```
shape: (3, 2)
┌─────┬─────────┐
│ x   ┆ row_num │
│ --- ┆ ---     │
│ i64 ┆ u32     │
╞═════╪═════════╡
│ 0   ┆ 0       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 0       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 0       │
└─────┴─────────┘
```

**Comment by ritchie46** [comment]
Yeah.. I am not yet sure if it is a quirk of the expression engine or not. 

In the select context we are allowed to add `literals` that are broadcasted afterwards. The size of the table is also not known beforehand, as you might write:

```python
df.select([
    pl.all().head(4)
])

# or
df.select([
    pl.all().filter(pl.col("foo") == 10)
])
```

In the **groupby** context literals are first expanded and then aggregated so that we can use them in the aggregation context predictably. 

Now we could do that in the select context as well (first expand). But I think that breaks other expressions like `take(pl.lit(0)` for instance.

**Comment by alexander-beedie** [comment]
Ahhh, further reading of the [window function docs](https://pola-rs.github.io/polars-book/user-guide/dsl/window_functions.html) showed me the missing piece of the puzzle; both `lit(0).cumcount()` (nice one) and `rank('ordinal')` will work _but_, if I understand correctly, it is necessary to pre-sort the entire frame if I wanted to reproduce the equivalent of a SQL `ROW_NUMBER() OVER (PARTITION BY "x" ORDER BY "y")`. It's not possible to supply inline ordering logic to the window functions. In which case `row_number` does become just a special-case of `rank('ordinal')`, which can (probably more efficiently) also be represented by `lit(0).cumcount()`. 

Might be worth aliasing `row_number` to whichever of those two is more efficient, for discoverability? Cheers... :)

**Comment by ritchie46** [comment]
With the landing of #2587 we can do it consistenly in the `select` and `groupby` context:

```python
df = pl.DataFrame({
    "groups": ["A", "A", "A", "C", "C"]
})

print(df.with_column(pl.first().cumcount().alias("row_number")))

print(df.with_column(pl.first().cumcount().alias("row_number").over("groups").flatten()))
```

```
shape: (5, 2)
┌────────┬────────────┐
│ groups ┆ row_number │
│ ---    ┆ ---        │
│ str    ┆ u32        │
╞════════╪════════════╡
│ A      ┆ 0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A      ┆ 1          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A      ┆ 2          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C      ┆ 3          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C      ┆ 4          │
└────────┴────────────┘
shape: (5, 2)
┌────────┬────────────┐
│ groups ┆ row_number │
│ ---    ┆ ---        │
│ str    ┆ u32        │
╞════════╪════════════╡
│ A      ┆ 0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A      ┆ 1          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A      ┆ 2          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C      ┆ 0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C      ┆ 1          │
└────────┴────────────┘

```

**Comment by alexander-beedie** [comment]
Perfect; being able to use the same trick in both contexts will significantly simplify a number of use-cases  :)

**Comment by ritchie46** [comment]
Yep.. The `lit(0)` variant will still be fastest as we don't have to drag an extra column around in joins, filters, and groupby's etc.
