### ISSUE TITLE
How to use join  with Series ?

### ISSUE THREAD

**Issue by arita37** [pola-rs/polars#2549]
In Pandas I can use the code:
df['new1'] = df.apply(lambda x :    ",".join( x['col_list'] ) , axis=1)

Is there any equivalent in Polars,
or should we use the lambda ?

**Comment by ritchie46** [comment]
Have you got an example. How does your data look?

**Comment by arita37** [comment]
Thanks.

Have data stored like this:

userid : 
itemlist : “3344,4445,5546,4444”

Often, need to process it under list form….

  x[“col”].split(“,”)

and store it back in

“,”.join(mylist)

much easier for parquet to manage long string

**Comment by ritchie46** [comment]
Does this help you? https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.expr.ExprListNameSpace.join.html#polars.internals.expr.ExprListNameSpace.join

**Comment by arita37** [comment]
Thanks, sounds good.

Just wondering, is there a way to do this in polars

df.groupby(“col1”).apply(lambda dfi : “,”.join(dfi[“col2”].values ) )
