### ISSUE TITLE
`scan_csv` with `skip_rows > 0` followed by a `slice` starts reading values from the first row of the file

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2555]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.21 (48ea1ed03)

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

Thank you again for the new `skip_rows` options! It looks like there's a bug when mixed with slices though. If you use `pl.scan_csv` with `skip_rows` greater than 0 to read a file, call `slice` (or `head`), and then `collect`, the `slice` offset will be calculated from the first row of the *file*, not after `skip_rows`. In cases where the first few lines are metadata, this will result in an error.

#### What are the steps to reproduce the behavior?

Here are some tests to add to `test_csv_schema_offset` in `test_io.py` that show the problem. The first one passes but not the second.

```python
    df = pl.scan_csv(foods_csv, skip_rows=4).collect()
    assert df[0,0] == "seafood"
    assert df.shape == (23, 4)

    df = pl.scan_csv(foods_csv, skip_rows=4).head(1).collect()
    assert df[0,0] == "seafood"
    assert df.shape == (1, 4)
```

#### What is the actual behavior?

```
        df = pl.scan_csv(foods_csv, skip_rows=4).head(1).collect()
>       assert df[0,0] == "seafood"
E       AssertionError: assert 'vegetables' == 'seafood'
E         - seafood
E         + vegetables

tests/test_io.py:585: AssertionError
```

#### What is the expected behavior?

The tests should pass.

**Comment by ritchie46** [comment]
Thanks for the tests!
