### ISSUE TITLE
Add optional lexical ordering of dtype `Categorical`

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#2562]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.20

#### What operating system are you using polars on?

macOS Monterey

#### Describe your bug.

DataFrame.sort() on Categorical type behave incorrectly.

#### What are the steps to reproduce the behavior?

```python
df = pl.DataFrame(
    [
        pl.Series("col1", [1, 1], dtype=pl.UInt8),
        pl.Series("col2", ["foo", "bar"], dtype=pl.Categorical),
        pl.Series("col3", [3.3, 1.1], dtype=pl.Float64),
    ]
)
df.sort(['col1', 'col2'])
```

#### What is the actual behavior?

```
shape: (2, 3)
┌──────┬──────┬──────┐
│ col1 ┆ col2 ┆ col3 │
│ ---  ┆ ---  ┆ ---  │
│ u8   ┆ cat  ┆ f64  │
╞══════╪══════╪══════╡
│ 1    ┆ foo  ┆ 3.3  │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1    ┆ bar  ┆ 1.1  │
└──────┴──────┴──────┘
```

#### What is the expected behavior?

```
shape: (2, 3)
┌──────┬──────┬──────┐
│ col1 ┆ col2 ┆ col3 │
│ ---  ┆ ---  ┆ ---  │
│ u8   ┆ cat  ┆ f64  │
╞══════╪══════╪══════╡
│ 1    ┆ bar  ┆ 1.1  │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1    ┆ foo  ┆ 3.3  │
└──────┴──────┴──────┘
```

I think polars should sort correctly on categorical type, like the following:

```python
df.sort('col2')
shape: (2, 3)
┌──────┬──────┬──────┐
│ col1 ┆ col2 ┆ col3 │
│ ---  ┆ ---  ┆ ---  │
│ u8   ┆ cat  ┆ f64  │
╞══════╪══════╪══════╡
│ 1    ┆ bar  ┆ 1.1  │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1    ┆ foo  ┆ 3.3  │
└──────┴──────┴──────┘
```

**Comment by Arengard** [comment]
df.sort(['col1', 'col2'], reverse=[True,True])

**Comment by mutecamel** [comment]
> df.sort(['col1', 'col2'], reverse=[True,True])

Thanks for your suggestion. But I don't mean descending sort. The BUG is, alphabetically, 'bar' should be prior to 'foo', but `df.sort(['col1', 'col2'])` returns a dataframe having 'foo' prior to 'bar'. Whereas `df.sort('col2')` gives the correct ordering.

**Comment by ritchie46** [comment]
I have to think about this one. I am not yet convinced that categorical dtypes should have the same ordering as string values.

**Comment by slonik-az** [comment]
In Statistics categorical variables are assumed of having no ordering (hence popular one-hot encoding is often used to reflect this fact). The "nominal" ordering of categoricals can follow the integer value that polars assigns to newly added category value. This order coincides with the order of categorical values being discovered by polars while reading data.  String (lexicographical) ordering is unnatural for categoricals. If you absolutely need such ordering, please, keep it as a string column.

**Comment by mutecamel** [comment]
As suggested in [user's guide](https://pola-rs.github.io/polars-book/user-guide/performance/strings.html),

> Reordering a DataFrame embedding a large number of Utf8 Series due to an operation (filtering, joining, grouping, etc.) can quickly become quite expensive.
> ...
> For this reason Polars has a CategoricalType. A Categorical Series is an array filled with u32 values that each represent a unique string value. Thereby maintaining cache efficiency, whilst keeping cheap to move values around.

Utf8 dtype is suggested to be casted into Categorical for more efficiency. But intuitively I still consider the casted Categorical be the same as the original Utf8, so I expect it behaves (sorting, filtering, joining, grouping, etc.) exactly like string values. IMHO.

**Comment by ritchie46** [comment]
The user guide did not anticipate sorting by this column. We must update the guide to reiterate that.

Maybe we can explore adding a flag to keep lexical ordering optionally.

**Comment by mutecamel** [comment]
> Maybe we can explore adding a flag to keep lexical ordering optionally.

> In Statistics categorical variables are assumed of having no ordering...

Categorical type exists mainly for reason that it is common for string columns to only have relatively few enumerable values. Such kind of string column is commonly used as field label for rows, NOT exactly the same as the "categorical variable" in statistical sense. In statistics, when dealing with "categorical variables", such labels usually need to be manually encoded into UInt (or Int) to reflect the ordering, or be used to generate several dummy variables.

In the polars dataframe, however, maybe we don't need a column of "categorical variable", but we DO frequently need such "label" columns. Such column usually have a very low cardinality, and thus more suitable to be stored as Categorical dtype rather than Utf8 dtype. And in this sense, I think a flag is unnecessary, because the Categorical dtype is still supposed to be TEXT, but stored in a more efficient/suitable way.

> It would require maintaining string cache in lexical order and updating u32 values accordingly when a new string is inserted somewhere in the middle.

When sorting on Categorical, I think we can implicitly cast any Categorical back into Utf8 and sort. That is, explicitly I can use

```python
In [1]: df = pl.DataFrame(
   ...:     [
   ...:         pl.Series("col1", [1, 1], dtype=pl.UInt8),
   ...:         pl.Series("col2", ["foo", "bar"], dtype=pl.Categorical),
   ...:         pl.Series("col3", [3.3, 1.1], dtype=pl.Float64),
   ...:     ]
   ...: )
   ...: df.sort(["col1", pl.col("col2").cast(pl.Utf8)])
Out[1]:
shape: (2, 3)
┌──────┬──────┬──────┐
│ col1 ┆ col2 ┆ col3 │
│ ---  ┆ ---  ┆ ---  │
│ u8   ┆ cat  ┆ f64  │
╞══════╪══════╪══════╡
│ 1    ┆ bar  ┆ 1.1  │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1    ┆ foo  ┆ 3.3  │
└──────┴──────┴──────┘
```

to get my desired result. But I hope `df.sort(["col1", "col2"])` could bring me the same result. Because in the API level, I'd rather consider Categorical values as texts (which is explicit and obvious), not as its underlying u32 values.

**Comment by ritchie46** [comment]
> It would require maintaining string cache in lexical order and updating u32 values accordingly when a new string is inserted somewhere in the middle. Is it really worth it? Polars strives for performance, consistency and generality. A very special corner case of lexical ordering of categoricals is a pain for a little gain. Properly updating the documentation seems the way to go.

No, we could just check use the stored strings in this case.

When there is no global string cache. The categorical are just indices in a local buffer with string values. In case of a global string cache, we have to do a hash table lookup to convert the global indices to indices in our local string buffer.

The latter is a bit more expensive, but at least it works. I think this behavior should be opt-in. The default should be as is IMO.

**Comment by ghuls** [comment]
@ritchie46 would it be not more efficient to sort the categorical string cache itself instead of the associated string values for the categorical for each value found in the dataframe (as categorical data implies that the same strings should be found often).

```python

# Representation of the catergorical string cache.
In [162]: cat_backend = pl.DataFrame(
     ...:     [
     ...:         pl.Series("id", [0, 1, 2, 3, 4, 5]),
     ...:         pl.Series("string", ["ZZZ", "DDD", "BBB", "FFF", "AAA", "EEE"]),
     ...:     ]
     ...: )

# Sort string cache. Value for each position determines the sort order in the string cache.
In [163]: cat_backend_argsort_argsort = cat_backend.string.argsort().argsort()

In [168]: cat_backend_argsort_argsort
Out[168]:
shape: (6,)
Series: 'string' [u32]
[
        5
        2
        1
        4
        0
        3
]


# Create dataframe with catergorical
In [164]: df_with_cat = pl.DataFrame(
     ...:     [
     ...:         pl.Series("row_idx", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
     ...:         pl.Series("cat", ["ZZZ", "DDD", "BBB", "FFF", "AAA", "EEE", "BBB", "DDD", "AAA", "ZZZ", "AAA"]).cast(pl.Categorical),
     ...:     ]
     ...: )

# Convert catergical to undelying UInt32 value.
In [165]: cat_uint32 = df_with_cat.cat.cast(pl.UInt32).alias('cat_uint32')

# Show sorting order.
In [166]: df_with_cat.with_columns([pl.col("cat").cast(pl.UInt32).alias("cat_uint32"), cat_backend_argsort_argsort.take(cat_uint32).alias('cat_sort')])
Out[166]:
shape: (11, 4)
┌─────────┬─────┬────────────┬──────────┐
│ row_idx ┆ cat ┆ cat_uint32 ┆ cat_sort │
│ ---     ┆ --- ┆ ---        ┆ ---      │
│ i64     ┆ cat ┆ u32        ┆ u32      │
╞═════════╪═════╪════════════╪══════════╡
│ 0       ┆ ZZZ ┆ 0          ┆ 5        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 1       ┆ DDD ┆ 1          ┆ 2        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2       ┆ BBB ┆ 2          ┆ 1        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3       ┆ FFF ┆ 3          ┆ 4        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4       ┆ AAA ┆ 4          ┆ 0        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5       ┆ EEE ┆ 5          ┆ 3        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 6       ┆ BBB ┆ 2          ┆ 1        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 7       ┆ DDD ┆ 1          ┆ 2        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 8       ┆ AAA ┆ 4          ┆ 0        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 9       ┆ ZZZ ┆ 0          ┆ 5        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 10      ┆ AAA ┆ 4          ┆ 0        │
└─────────┴─────┴────────────┴──────────┘

# Do the actual sorting.
In [167]: df_with_cat.with_columns([pl.col("cat").cast(pl.UInt32).alias("cat_uint32"), cat_backend_argsort_argsort.take(cat_uint32).alias('cat_sort')]).sort(by=["cat_sort", "row_idx"])
Out[167]:
shape: (11, 4)
┌─────────┬─────┬────────────┬──────────┐
│ row_idx ┆ cat ┆ cat_uint32 ┆ cat_sort │
│ ---     ┆ --- ┆ ---        ┆ ---      │
│ i64     ┆ cat ┆ u32        ┆ u32      │
╞═════════╪═════╪════════════╪══════════╡
│ 4       ┆ AAA ┆ 4          ┆ 0        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 8       ┆ AAA ┆ 4          ┆ 0        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 10      ┆ AAA ┆ 4          ┆ 0        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2       ┆ BBB ┆ 2          ┆ 1        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 6       ┆ BBB ┆ 2          ┆ 1        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 1       ┆ DDD ┆ 1          ┆ 2        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 7       ┆ DDD ┆ 1          ┆ 2        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5       ┆ EEE ┆ 5          ┆ 3        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3       ┆ FFF ┆ 3          ┆ 4        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 0       ┆ ZZZ ┆ 0          ┆ 5        │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 9       ┆ ZZZ ┆ 0          ┆ 5        │
└─────────┴─────┴────────────┴──────────┘

# Take does not seem to support expressions.

In [169]: df_with_cat.with_columns([pl.col("cat").cast(pl.UInt32).alias("cat_uint32"), cat_backend_argsort_argsort.take(pl.col("cat").cast(pl.UInt32).alias("cat_uint32"),).alias('cat_sort')]).sort(by=["cat_sort", "row_idx"])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-169-99b89e57583b> in <module>
----> 1 df_with_cat.with_columns([pl.col("cat").cast(pl.UInt32).alias("cat_uint32"), cat_backend_argsort_argsort.take(pl.col("cat").cast(pl.UInt32).alias("cat_uint32"),).alias('cat_sort')]).sort(by=["cat_sort", "row_idx"])

~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/internals/series.py in take(self, indices)
   1391         if isinstance(indices, list):
   1392             indices = np.array(indices)
-> 1393         return wrap_s(self._s.take(indices))
   1394
   1395     def null_count(self) -> int:

TypeError: argument 'indices': 'Expr' object cannot be converted to 'Sequence'

**Comment by ritchie46** [comment]
I am still trying to understand it exactly. But `cat_backend_argsort_argsort.take` is on a `Series` so `pl.col("cat")` has not` `DataFrame` to select from.

**Comment by ghuls** [comment]
is there then a way to get all values of the `pl.col("cat")` without running it outside of a with_columns statement, so take works?

**Comment by ritchie46** [comment]
I don't know where column `cat` resides? But you can create a literal from the series you want to access. `pl.lit(cat_series)...`

**Comment by ghuls** [comment]
column `cat` is lcoated in `df_with_cat`.

**Comment by ritchie46** [comment]
Yes but the expression is passed to a Series. It is impossible to retreive that from a language perspective.

**Comment by ghuls** [comment]
ah, ok. I didn't know that.

**Comment by ritchie46** [comment]
Does anybody happen to know how categorical are done in other libraries? I don't recall pandas having a global cache. How does it resolve equality in joins? And R's factor?

**Comment by ghuls** [comment]
dplyr seems to convert back to a string if the levels don't match (or at least in 2018). https://stackoverflow.com/questions/30468412/dplyr-join-warning-joining-factors-with-different-levels

**Comment by ghuls** [comment]
Pandas also seem to support unordered and ordered categoricals: https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html

Pandas seems to to the same that dplyr as far as  I can see from this post:
https://towardsdatascience.com/staying-sane-while-adopting-pandas-categorical-datatypes-78dbd19dcd8a

**Comment by slonik-az** [comment]
> (@ritchie46 ) Does anybody happen to know how categorical are done in other libraries? I don't recall pandas having a global cache. How does it resolve equality in joins? And R's factor?

From the pandas documention https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html
> All values of categorical data are either in `categories` or `np.nan`. Order is defined by the order of categories, not lexical order of the values. Internally, the data structure consists of a categories array and an integer array of codes which point to the real value in the categories array.

**Comment by alexander-beedie** [comment]
Pandas has support for ordered/sorted categories; ordering string categories lexically is quite straightforward. Doing it after initial category creation is typically efficient, as you can reasonably expect low cardinality (otherwise why would it have been made categorical in the first place? ;) 

It is an _opt-in_ feature; string (or other) categories are not sorted by default - it is, however, often useful in practice, as wanting to save memory (while otherwise behaving exactly like a string, including sorting) is a common use-case.

```python
original_categorical = pd.Categorical( df["string_values"] )
ordered_categorical = cat.reorder_categories( sorted(cat.categories), ordered=True )
```

For pandas, each categorical is considered a distinct type, and there is no global categorical/string cache, so merge/join across different categorical columns typically fails. Quoting [the docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#sorting-and-order): _"...comparisons of two categoricals with different categories or a categorical with any list-like object, will raise a TypeError..."_ In other words, it is up to the caller to ensure that the _same_ categorical type is applied to all frames involved in a merge.

Polars' global string cache adds an extra wrinkle here, but unless the number of category values becomes _very_ high, I wouldn't think it's a blocker to allow opt-in ordered categoricals in a similar way to the above, and maintain ordering within the global cache (note: lexical ordering is not the only useful defined ordering; financial tenors would be another common case that a user might want to supply, eg: "1D" < "1W" < "1M" < "1Y", etc). But, as it's clearly an overhead, opt-in and a note in the docs would definitely be the way to go.

(FYI: pandas ordered categories also gain `min` and `max` methods, which can sometimes be useful).

**Comment by alexander-beedie** [comment]
Thinking a bit more about use-cases and a reasonable API... As a common case, could have a `pl.SortedCategorical` type that maintains a separate string cache and orders by value by default (once following initial frame/category creation, and then on any subsequent addition of new values). Would allow for a cleaner segregation of a SortedCategorical string cache from the cheaper non-ordering global cache, for instance, and not require the user to supply categories explicitly. 

That would cover plenty of use cases already. As an extension, coould then have one that allows for a custom ordering (like the pandas example above) - something like `pl.CustomCategorical( categories=..., name=... )`, perhaps? Might be useful to have a name in addition to the categories; could allow for cache-segregation by name, as well as provide semantic information about what the category represents.

`CategoricalTenor = pl.CustomCategorical( categories=["1D","1W","1M","1Y", ...], name='Tenors' )`

**Comment by mutecamel** [comment]
When categories are predetermined, its is easy to encode custom ordered categories into numbers. But when categories are not known (or not specified, or laborious to specify), it seems very difficult to deal with the encoding (or `StringCache` or sth?), because when a new category is encountered, it may need to be inserted into the middle to preserve the (lexical) ordering, forcing the `u32`s completely re-encoded, lowering the efficiency.

I'm wondering if it is possible to encode the categories into `f32` (`Float32`) instead of `u32` (`UInt32`). Because this way it may be much easier to find a middle value to allocate to the new category.

**Comment by ghuls** [comment]
> I'm wondering if it is possible to encode the categories into `f32` (`Float32`) instead of `u32` (`UInt32`). Because this way it may be much easier to find a middle value to allocate to the new category.
I doubt it is. As far as understand the u32 value associated with a categorical value referes to the nth element in the StringCache. It would be possible to have empty slots in the string cache so less strings have to be moved around, but it results is a quite a bit of waisted memory.
