### ISSUE TITLE
`with_row_count` on a `LazyFrame` before a `slice` or `filter` causes row numbers to be counted after filtering, not before

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2565]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

622bfb2de90d

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

`LazyFrame.with_row_count().tail(...)` or `.filter` results in the row count column starting from the beginning of the post-filtered dataframe. This is both undesirable as well as different than `DataFrame`, which will respect the order of `with_row_count` and `slice`/`tail`/`filter`.

Disabling `predicate_pushdown` optimization for `with_row_count` fixes the issue, but I figured there was likely a more optimized way of doing it, so figured I'd just open a bug report. LMK if that is the best way to fix it, and I can open PR.

#### What are the steps to reproduce the behavior (+ actual behavior)?

```python
In [2]: pl.DataFrame({"a": range(10)}).lazy().with_row_count().tail(5).collect()
Out[2]: 
shape: (5, 2)
┌────────┬─────┐
│ row_nr ┆ a   │
│ ---    ┆ --- │
│ u32    ┆ i64 │
╞════════╪═════╡
│ 0      ┆ 5   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 1      ┆ 6   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2      ┆ 7   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 3      ┆ 8   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 4      ┆ 9   │
└────────┴─────┘
```

This test to `test_row_count` in `test_df.py` also shows the problem:

```python
    out = df.lazy().with_row_count().slice(1, 2).collect()
    assert out["row_nr"].to_list() == [1, 2]
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the expected behavior?

```python
In [7]: pl.DataFrame({"a": range(10)}).with_row_count().tail(5)
Out[7]: 
shape: (5, 2)
┌────────┬─────┐
│ row_nr ┆ a   │
│ ---    ┆ --- │
│ u32    ┆ i64 │
╞════════╪═════╡
│ 5      ┆ 5   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 6      ┆ 6   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 7      ┆ 7   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 8      ┆ 8   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 9      ┆ 9   │
└────────┴─────┘
```

**Comment by ritchie46** [comment]
Yes, you are right. With row count should block the slice pushdown. Or even better update the row count.

**Comment by qiemem** [comment]
So I had to disable `predicate_pushdown` to get it to actual work, even for just the `tail`/`slice` case. ie:

```diff
   --- a/polars/polars-lazy/src/frame/mod.rs
+++ b/polars/polars-lazy/src/frame/mod.rs
@@ -1002,7 +1002,10 @@ impl LazyFrame {
 
         self.map(
             move |df: DataFrame| df.with_row_count(&name),
-            Some(AllowedOptimizations::default()),
+            Some(AllowedOptimizations {
+                predicate_pushdown: false,
+                ..Default::default()
+            }),
             Some(new_schema),
             Some("WITH ROW COUNT"),
         )
```

Does that disabling just mean the pushdown can't pass that node or does it disable it for the whole query? What does that cost performance wise? Would the row count arrays for the ultimately skipped rows actually be allocated and written to, or would does just make a row count iterator that would be iterated through for the skipped rows, but not actually written to allocated arrays?

> Or even better update the row count.

What would this involve? And if it's easier for you to just do it than to explain it, no worries :)

Also, here's an expanded test list, with `filter` examples and ensuring that both order of operations work so we know nothing breaks as a result of the fix:

```python
    out = df.lazy().with_row_count().slice(1, 2).collect()
    assert out["row_nr"].to_list() == [1, 2]

    out = df.lazy().with_row_count().filter(pl.col("a") == 3).collect()
    assert out["row_nr"].to_list() == [2]

    out = df.lazy().slice(1, 2).with_row_count().collect()
    assert out["row_nr"].to_list() == [0, 1]

    out = df.lazy().filter(pl.col("a") == 3).with_row_count().collect()
    assert out["row_nr"].to_list() == [0]
```

**Comment by ritchie46** [comment]
> Does that disabling just mean the pushdown can't pass that node or does it disable it for the whole query? What does that cost performance wise? Would the row count arrays for the ultimately skipped rows actually be allocated and written to, or would does just make a row count iterator that would be iterated through for the skipped rows, but not actually written to allocated arrays?

Predicate pushdown should not pass a `with_row_count` no. It would influence the `with_row_count` operation. This means we cannot filter at scan level if you add that node (unless you write your filters before `with_row_count`).

> What would this involve? And if it's easier for you to just do it than to explain it, no worries :)

It is not so easy at the moment, because we have implemented `with_row_count` with a `map` internally it is not visible to the query optimizer. I think I will just block the slice for now.

**Comment by ritchie46** [comment]
And again thanks for the tests! That really saves me a lot of work! :)
