### ISSUE TITLE
Read multiple csv files with lazy evaluation

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2574]
Hi;

I wonder whether you're planning to add following features. Or is there any way to do this with existing functionality.

- reading multiple csv files located in a folder. (reading with lazy evaluation) 
- support of file extension is csv.gz (reading with lazy evaluation) 

I know gz file can be read with read_csv. but overall data size is big and  I had no option except lazy evaluation.  

Thanks.

**Comment by ritchie46** [comment]
Do you want to read them seperately (e.g. into different parallelizable queries?). Or do you want to read them and concat them into a single `DataFrame`?

**Comment by hakantekbas** [comment]
As data size  is over 1 billion rows, reading seperately and combining can consume all memory.

We have two version  of same data. In option 1, data is combined to one csv. (It is coming from data vendor) We can run aggregation script, consuming 40 gb ram. In option 2, data is processed with spark and company is splitting data to many zipped (gz) csv files. But if we read all csv seperately and combine them to a one dataframe, it will run out of memory.

@ritchie46  you can ask why you're not prefering spark. In option 1, performance of polars is really good. It can complete task within 2 minutes. (and I also restricted to 4 threads) I did not see the benefit of running this type of task in spark.

Thanks.

**Comment by ritchie46** [comment]
> @ritchie46 you can ask why you're not prefering spark. In option 1, performance of polars is really good. It can complete task within 2 minutes. (and I also restricted to 4 threads) I did not see the benefit of running this type of task in spark.

That is great to hear. Good that we are pushing boundaries. :smile: 

I took your question as an opportunity to update the user guide: https://pola-rs.github.io/polars-book/user-guide/multiple_files/intro.html

**Comment by hakantekbas** [comment]
Great!
Is it possible to support csv.gz file in lazy evaluation.?

**Comment by ritchie46** [comment]
> Great! Is it possible to support csv.gz file in lazy evaluation.?

I think it is. Give it a try.

**Comment by ghuls** [comment]
> 



> > @ritchie46 you can ask why you're not prefering spark. In option 1, performance of polars is really good. It can complete task within 2 minutes. (and I also restricted to 4 threads) I did not see the benefit of running this type of task in spark.
> 
> That is great to hear. Good that we are pushing boundaries. smile
> 
> I took your question as an opportunity to update the user guide: https://pola-rs.github.io/polars-book/user-guide/multiple_files/intro.html

Instead of just globbing, a list of filenames passed to read_csv, scan_csv, read_parquet, ... would be great to have (didn't test if it is already supported or not).

**Comment by ritchie46** [comment]
No, but this could be easily added in python source. We have to map the list with `pl.scan_` and wrap that in a `pl.concat`.

**Comment by hakantekbas** [comment]
> > Great! Is it possible to support csv.gz file in lazy evaluation.?
> 
> I think it is. Give it a try.

it seems it does not support. I tried it in 0.12.22

> RuntimeError: Any(ComputeError("cannot scan compressed csv; use read_csv for compressed data"))

**Comment by ritchie46** [comment]
Ah.. yeah I forgot. We can only decompress the whole bytes stream in memory. So scanning does not make any sense (we'd need to decompress first to get the schema, which is expensive).

So in that case you can best do `pl.read_csv(..).lazy()`

**Comment by ritchie46** [comment]
Ah, yes. It may be consumed directly by the computation graph if you don't have any reference to it in python.

I think you'd have to do this chunked. E.g. keep a list with file names. And load something like 4/8 of them in memory and call with `pl.collect_all()`

**Comment by hakantekbas** [comment]
@ritchie46  if 4 or 8 files are loaded into memory why do we need to call pl.collect_all? It is in memory and will lazy evaluation optimize the memory consumption?

Following code is the example you gave in documentation. does your advise point to this example in documentation.

If you can give small code snippet, it will help a lot.

```
import polars as pl
import glob

queries = []
for file in glob.glob("my_many_files_*.csv"):
    q = pl.scan_csv(file).groupby("bar").agg([pl.count(), pl.sum("foo")])
    queries.append(q)

dataframes = pl.collect_all(queries)
print(dataframes)
```

**Comment by ritchie46** [comment]
> @ritchie46 if 4 or 8 files are loaded into memory why do we need to call pl.collect_all? It is in memory and will lazy evaluation optimize the memory consumption?

`pl.collect_all()` will run all in parallel. So it might be faster.

Regarding memory. In a lazy computation graph, the `DataFrames` flow into nodes and with every new node (e.g. join, groupby, in-memory-table, filter, etc.). The old nodes memory is dropped. 

Furthermore will lazy optimizations try to remove columns and rows as early as possible, reducing memory pressure. So yes, once you read 4 dataframes in memory they will be all in memory. But the next node maybe a projection (selecting columns) and thus freeing memory, which could be used for a groupby's internal memory structures for instance.


Something like this?

```python
import polars as pl
import glob

queries = []
for file in glob.glob("my_many_files_*.csv"):
    q = pl.scan_csv(file).groupby("bar").agg([pl.count(), pl.sum("foo")])
    queries.append(q)

offset = 4
for i in range(0, queries.len(), offset):
    subset = queries[i: i + offset]
    
    results = pl.collect_all(queries)
    
    for df in results:
        df.to_parquet(..)

```

**Comment by hakantekbas** [comment]
@ritchie46  Thanks for articulating your point. I can close the issue.
