### ISSUE TITLE
Error with "projection_pushdown" optimisation and "with_row_count" frame-level op

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2576]
Got a new/related one...  ;)

#### Are you using Python or Rust?

Python, Windows 10, Polars 0.12.22 _(contains earlier pushdown fix)_

#### Describe/reproduce your bug.

Looks like projection pushdown can't see the 'virtual' column injected by the `with_row_count` op (order of application issue, or query node not frozen?)

```python
import polars as pl

# setup test data
df = pl.from_records( 
    data = [[0,'a'],[1,'b'],[2,'c'],[3,'d']], 
    columns = ['colx','coly'],
).lazy()

# apply rowcount
df = df.with_row_count( 
    name = '_rowcount_',
)
# ╭────────────┬──────┬──────╮
# │ _rowcount_ │ colx │ coly │
# ╞────────────╪──────╪──────╡
# │          0 │    0 │ a    │
# │          1 │    1 │ b    │
# │          2 │    2 │ c    │
# │          3 │    3 │ d    │
# ╰────────────┴──────┴──────╯

```
So far so good. However...
```python
df.select(
    exprs = [pl.col('_rowcount_'),
            (pl.col('colx') * 2).alias('x2')],
).fetch()

>> pyo3_runtime.PanicException: projection pushdown failed: 
..   NotFound("Unable to get field named \"_rowcount_\". Valid fields: [\"colx\", \"coly\"]")
```

#### What is the expected behavior?

Disabling `projection_pushdown` results in the expected frame:
```python
df.select(
    exprs = [pl.col('_rowcount_'),
            (pl.col('colx') * 2).alias('x2')],
).fetch(
    projection_pushdown = False,
)
# ╭────────────┬────╮
# │ _rowcount_ │ x2 │
# ╞────────────╪────╡
# │          0 │  0 │
# │          1 │  2 │
# │          2 │  4 │
# │          3 │  6 │
# ╰────────────┴────╯
```

**Comment by ritchie46** [comment]
Ok, my naive implementation of a `row_count` has proven to be more difficult than I anticipated. As it is currently it blocks 

* predicate pushdown (because it removes rows)
* projection pushdown (because of implemenation)
* slice pushdown (because of implementation)

This is a waste of opportunities. I think we have to pushdown the row_count to the readers so that it won't block any future optimizations.

This is a bit more work.

**Comment by alexander-beedie** [comment]
As someone who has written a backend-independent query optimiser (alongside a query metalanguage) in the past, I feel your pain - because if I know one thing, it is that there are _always_ more edge-cases, heh (it's not a coincidence that I try to provide clean/minimal test-cases that actually run, because I have been on the other side of this ;)

In the meantime is there a way of freezing the query node from python-space, to temporarily prevent the predicate pushdown through `with_row_count` in this situation? (As a workaround, pending a larger fix). Thanks, as always!

**Comment by ritchie46** [comment]
> As someone who has written a backend-independent query optimiser (alongside a query metalanguage) in the past, I feel your pain - because if I know one thing, it is that there are always more edge-cases, heh (it's not a coincidence that I try to provide clean/minimal test-cases that actually run, because I have been on the other side of this ;)

Yes, thanks for the test and mwe's. That save a lot of mental load. :raised_hands: 
What did you build? Also related to query engines, or more in the field of programming langs?

> In the meantime is there a way of freezing the query node from python-space, to temporarily prevent the predicate pushdown through with_row_count in this situation? (As a workaround, pending a larger fix). Thanks, as always!

Yes, I could simply block projection pushdown as well, and then work on the proper implementation.

**Comment by alexander-beedie** [comment]
> What did you build? Also related to query engines, or more in the field of programming langs?

Also related to query engines. I probably can't go into all that much detail as it was at my old shop, before they became more open-source friendly, but at the high level it could be described more-or-less as a python-based lazy/fluent DSL that could target arbitrary tabular or pseudo-tabular data sources (most flavours of database, tickdata stores, dataframes, streaming sources, some graph structures, iterators, etc). Essentially "write once, query -and export- everywhere" (target iterators, it compiles accelerated python code under the hood; target Oracle, it internally generates dialect-specific SQL, and so on).

Would be nice to clean-room it one day and unleash upon an unsuspecting world :)

> Yes, I could simply block projection pushdown as well, and then work on the proper implementation.

Yup, that makes more sense.
