### ISSUE TITLE
extreme difference in speed of execution of sort on two equal dfs, one produced using polars fns and one produced using pandas fns

### ISSUE THREAD

**Issue by chenrocky** [pola-rs/polars#2579]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.17

#### What operating system are you using polars on?

reproduced issue on `rhel8` and `macOS Big Sur 11.6.1`

#### Describe your bug.

`frame_equal` shows two dfs as equal, but the time it takes to sort each df is very different. One df was created using pandas fns/methods before converting to a polars df at the end, and the other df is created using polars fns/methods

Sorting the df that was generated using pandas fns/methods is fast and only takes a few seconds.

Sorting the df that was generated using polars fns/methods is slower and takes a few minutes.

Is there a bug with `frame_equal`?

Why isn't the sort just as fast on the df that was generated using polars fns/methods? (I'd rather use polars fns/methods to generate the df because generating the unsorted df is faster using polars fns/methods rather than pandas.)

#### What are the steps to reproduce the behavior?

The code snippet below demonstrates the behavior with toy data:

```
import polars as pl
import pandas as pd
import numpy as np

# raw data
raw_data = np.random.random((3300, 2300))

# pandas
pd_df = pd.DataFrame(raw_data)
pd_df = pd_df.stack().reset_index(drop=False)
pd_df.columns = ["user", "item", "score"]
pd_df = pl.from_pandas(pd_df)
pd_df = pd_df.sort(["user", "score"], reverse=[False, True]) # this takes a couple seconds

# polars
pl_df = pl.from_pandas(pd.DataFrame(raw_data.T))
pl_df = pl_df.with_columns([
    pl.Series("item", [i for i in range(0, pl_df.shape[0])], dtype=pl.Int64)
])
pl_df = pl_df.melt(id_vars=["item"], value_vars=[col for col in pl_df.columns[:-1]])
pl_df = pl_df.rename({"variable": "user", "value": "score"})
pl_df["user"] = pl_df["user"].cast(pl.Int64)
pl_df = pl_df[["user", "item", "score"]]
pl_df = pl_df.sort(["user", "score"], reverse=[False, True]) # this takes a couple mins


# frames are equal according to frame_equal
pl_df.frame_equal(pd_df)

```

#### What is the actual behavior?

```pd_df.sort(["user", "score"], reverse=[False, True])``` this takes a couple seconds

```pl_df.sort(["user", "score"], reverse=[False, True])``` this takes a couple mins

#### What is the expected behavior?

I expected both snippets of code to take the same amount of time to execute (a couple seconds with this toy data)

**Comment by ritchie46** [comment]
The `DataFrame` has a large number of chunks which create a lot of indirection in the sort.

`df = df.rechunk` should solve it. 

I will see that we do this by default on sort.
