### ISSUE TITLE
RuntimeError when reading bad characters from CSV, despite using 'utf8-lossy' encoding

### ISSUE THREAD

**Issue by davidwales** [pola-rs/polars#2580]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.22

#### What operating system are you using polars on?

Windows 10: 1909

#### Describe your bug.

I'm trying to read a CSV with some bad characters in it.
I was hoping that using `encoding='utf8-lossy' would allow me to load the CSV, but I still get an error.
Is this expected for 'utf8-lossy'?

#### What are the steps to reproduce the behavior?

**Example**

[Australian Public Holidays 2019.csv](https://github.com/pola-rs/polars/files/8029602/Australian.Public.Holidays.2019.csv)

```python
>>> pl.read_csv("https://github.com/pola-rs/polars/files/8029602/Australian.Public.Holidays.2019.csv", encoding="utf8-lossy")
...
RuntimeError: Any(ComputeError("invalid utf8 data in csv"))
```

#### What is the expected behavior?

My understanding was that 'utf8-lossy would skip the invalid characters.

**Comment by ritchie46** [comment]
This has been fixed a few days ago. I will update tonight.

**Comment by davidwales** [comment]
That did the trick! Thank you! (I only discovered Polars a a couple of days ago, but so far I'm really liking it!)
