### ISSUE TITLE
Error with Projection pushdown

### ISSUE THREAD

**Issue by tikkanz** [pola-rs/polars#2608]
#### Are you using Python or Rust?
Python

#### What version of polars are you using?
0.12.23

#### What operating system are you using polars on?
Ubuntu 18.04

#### Describe your bug.
When collecting a scanned csv file, the null values are not being correctly handled if the column are selected prior to collection.
Selecting the column after collection results in a correct result, as does specifying `projection_pushdown` to be False

#### What are the steps to reproduce the behavior?

```python
import polars as pl

# Create test CSV file
test_file = "test.csv"

pl.DataFrame({
    "ID": [1,2,3,4,5],
    "Name1": ["Bill", "Jim", "Jeremy", ".", "Brian"],
    "Name2": [".", ".", "Smith", ".", "Brown"],
    "Value": [4,33,14,64,24]
}).to_csv(test_file)

df = pl.scan_csv(test_file, null_values={"Name2":"."})    .select(["ID","Name2"])

df.select(["ID","Name2"]).collect().filter(pl.col("Name2").is_null())  # shape is (0, 2)
df.collect().select(["ID","Name2"]).filter(pl.col("Name2").is_null())  # shape is (3, 2)
df.select(["ID","Name2"]).collect(projection_pushdown=False).filter(pl.col("Name2").is_null()).shape  # shape is (3, 2)
```

#### What is the actual behavior?
```python
df.select(["ID","Name2"]).collect().filter(pl.col("Name2").is_null())
```
```
shape: (0, 2)
┌─────┬───────┐
│ ID  ┆ Name2 │
│ --- ┆ ---   │
│ i64 ┆ str   │
╞═════╪═══════╡
└─────┴───────┘
```

#### What is the expected behavior?

Behavior should be as for the following query:
```python
df.collect().select(["ID","Name2"]).filter(pl.col("Name2").is_null())
```
```
shape: (3, 2)
┌─────┬───────┐
│ ID  ┆ Name2 │
│ --- ┆ ---   │
│ i64 ┆ str   │
╞═════╪═══════╡
│ 1   ┆ null  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ null  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 4   ┆ null  │
└─────┴───────┘
```

**Comment by ritchie46** [comment]
Thanks for the report. I will fix this. This one will go to the `0.13.x` releases.
