### ISSUE TITLE
Various precision mismatches with python-native (and arrow) datetimes

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2616]
#### Are you using Python or Rust?

Python, Windows 10, polars 0.12.24

#### Describe your bug:

Python-native datetimes have microsecond precision (1e6); polars seems to have a preference for either milliseconds (1e3: loss of precision) or nanoseconds (1e9: too much precision). This can make it a bit tricky to properly interop with py-native datetimes, or datetimes from other sources that explicitly specify microsecond ('us') precision (including Arrow, Numpy, and Pandas) .

#### Some examples:

1) Incorrect upcast on init from Arrow ('us' => 'ns'):
```python
import polars as pl
import pyarrow as pa
from datetime import datetime, date
 
# create a typed arrow table, and use to init a polars frame
a = pa.Table.from_arrays( 
    arrays = [[datetime.now()],[date.today()],[128]],
    schema = pa.schema([
        ('timestamp',pa.timestamp('us')),
        ('date',pa.date32()),
        ('value',pa.int16()),
    ]),
)
df = pl.from_arrow( a )

# expect 'us' (not 'ns') precision in "dtm" column
# ┌────────────────────────────┬────────────┬───────┐
# │ timestamp                  ┆ date       ┆ value │
# │ ---                        ┆ ---        ┆ ---   │
# │ datetime[ns] <<<           ┆ date       ┆ i16   │
# ╞════════════════════════════╪════════════╪═══════╡
# │ 2022-02-11 15:42:26.840178 ┆ 2022-02-11 ┆ 128   │
# └────────────────────────────┴────────────┴───────┘
```
2) Cannot create date_range with py-native ('us') precision
```python
import polars as pl
from datetime import datetime
res = pl.date_range( datetime(2022,1,1,0,0,0,123456), datetime(2022,1,31,0,0,0,999999), "1d", time_unit='us' )

ValueError: expected on of {'ns', 'ms'}
```
3) Default Series precision appears to be millisecs (potential loss of precision or forced upcasting later). 
Not sure how to specify an explicit time unit on Series init?
```python
import polars as pl
pl.Series( name='dtm', dtype=pl.datatypes.Datetime )

shape: (0,)
Series: 'dtm' [datetime[ms]]  <<<
[
]

# (same behaviour with/without values)
pl.Series( name='dtm', values=[1_674_560_040_080], dtype=pl.datatypes.Datetime )

shape: (1,)
Series: 'dtm' [datetime[ms]]  <<<
[
	2023-01-24 11:34:00.080
]
```
4) Series init with python datetime values fails (not a precision issue, but would be nice if it could be done)
```python
import polars as pl
from datetime import datetime
pl.Series( name='dtm', values=[datetime(2022,1,1,10,30,45)], dtype=pl.datatypes.Datetime )

TypeError: 'datetime.datetime' object cannot be interpreted as an integer
```

(There are more, but all pretty much come down to microsecs not being readily useable, while also being the standard py-native precision, so will not go overboard with examples... ;)

#### What is the expected behavior?

Arrow has native microsecond time unit ('us') support; would be great if polars took advantage of this to expose microseconds as a first-class time_unit value, as this is the native precision of python datetimes, and a common unit in other libraries (numpy/pandas/arrow).

**Comment by ritchie46** [comment]
IMO the two units are sufficient. We can model the utmost precision and with milliseconds we are also save for years to come :see_no_evil:)
Have more only puts more strain on compiler times and complexity of the project. Regarding going from `us` to `ns`, we could modulo the `precision` so that the extra digits are always `0`, not leading to misleading precision assumptions.

We could expose a `time_unit` to the `Series` as well. :+1:

**Comment by alexander-beedie** [comment]
Heh. I'm not sure that the extra span available with `ms` vs `us` is worth losing py-native precision over though? Could still cover ~292,000 years without dropping microsecond precision (depending on the exact implementation details, given uint64)  ;)

Perhaps a more convincing argument; I can't use the following trivial Arrow table in polars _at all_, without `us` precision - instead, the forced upcast to `ns` silently misinterprets the input data, resulting in some peculiar values that are off by several hundred years:

```python
import polars as pl
import pyarrow as pa
from datetime import datetime, date

a = pa.Table.from_arrays(
    arrays=[ [datetime(2600,1,1,0,0,0,123456),datetime(2800,1,1,0,0,0,456789)],[128,256] ],
    schema=pa.schema( [
        ('timestamp', pa.timestamp('us')),
        ('value', pa.int16()),
    ] ),
)
# pyarrow.Table
# timestamp: timestamp[us]
# value: int16
# ----
# timestamp: [[2600-01-01 00:00:00.123456,2800-01-01 00:00:00.456789]]
# value: [[128,256]]

df = pl.from_arrow( a )
# ┌───────────────────────────────┬───────┐
# │ timestamp                     ┆ value │
# │ ---                           ┆ ---   │
# │ datetime[ns]                  ┆ i16   │
# ╞═══════════════════════════════╪═══════╡
# │ 2015-06-13 00:25:26.413904384 ┆ 128   │    <<< errrrr...
# ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
# │ 2215-06-13 00:25:26.747237384 ┆ 256   │    <<<
# └───────────────────────────────┴───────┘
```


> We could expose a time_unit to the Series as well. 👍

A `time_unit` for Series (and some extra '0's) would be nice, thx  :)

**Comment by ritchie46** [comment]
What do you mean you cannot use it? The values are internally always `int64`? We only convert `* 1000`. All operations should still work. I understand that you don't want to see precision that is not there. So we should truncate that on conversion.

IMO the `ns` is a superset of `us`. They can show the precision needed. 

> A time_unit for Series (and some extra '0's) would be nice, thx :)

There already is :):

```python
pl.Series("a", [int(1e12)], dtype=pl.Datetime).dt.and_time_unit("ns")
```

**Comment by alexander-beedie** [comment]
> What do you mean you cannot use it? 

The above example shows that there is a silent conversion error during the upcast, leaving the date values wildly off (by hundreds of years). Also (assuming a similar min/max within Arrow as pandas Timestamp[ns]), the max year that can be represented with `ns` precision may only be 2262 -- so nothing beyond that can be loaded with `ns` (the example above uses the years 2600 and 2800; my expectation is that if the upcast bug is fixed, an out-of-range error will be raised instead).

```python
import pandas as pd
pd.Timestamp.max
Timestamp('2262-04-11 23:47:16.854775807')
pd.Timestamp.min
Timestamp('1677-09-21 00:12:43.145224193')
```


> IMO the ns is a superset of us.

Given the above, use of `ns` can _significantly_ truncate the available time domain; I'm not sure what the min/max in Arrow are (trying to dig it up now) but 2262 is rather close, given that `us` gets you ~585,000 years further into the future (just realised my previous estimate used int64, not uint64, so extending that claim accordingly) ;)

Roughly speaking (with some variations based on implementation), `ns` precision limits you to about a 585 year window, `us` to ~585,000, and `ms` to ~585,000,000.


> pl.Series("a", [int(1e12)], dtype=pl.Datetime).dt.and_time_unit("ns")

Wizardry :)

**Comment by ritchie46** [comment]
> Given the above, use of ns can significantly truncate the available time domain; I'm not sure what the min/max in Arrow are (trying to dig it up now) but 2262 is rather close, given that us gets you ~585,000 years further into the future (just realised my previous estimate used int64, not uint64, so extending that claim accordingly) ;) Not that I'm saying ns isn't good - for time series and/or high frequency data it can be very useful! But the more common us precision isn't range-bound in the same way.

Agreed. But who needs `us` precision that far in the future? :P I think `ms` is more than enough precision for that case. Now I agree we could change `ms` to `us` and all is still fine. Maybe we should do that if it really is a problem that we cannot have `us` precision above `2262`. I just don't want to support all arrow precisions, because I don't think the complexity is needed.

> The above example shows that there is a silent conversion error during the upcast

Then that is a bug we must fix nonetheless. Regardless of this discussion, could you open issues for every case you find? Then I will fix them and make sure they are included in tests.

**Comment by alexander-beedie** [comment]
> Agreed. But who needs us precision that far in the future? :P

Lol... Well, I'd lean towards choosing the py-native precision as the default, given the much-expanded time domain, but I won't storm the castle if that doesn't happen... ;)

> Then that is a bug we must fix nonetheless. Regardless of this discussion, could you open issues for every case you find? Then I will fix them and make sure they are included in tests.

Done: https://github.com/pola-rs/polars/issues/2618 👍

**Comment by slonik-az** [comment]
I think that current design with `ms` as default and `ns` for extra precision (at the cost of reduced time span) makes a lot of sense. Polars is a Rust library first with bindings to Python and Javascript and possibly more languages in the future. Rust `std::time` has `ns` resolution, Python - `us` and Javascript `ms`. Any hard choice will make someone unhappy. Milliseconds provide reasonable time resolution for most of datasets and nanoseconds are there for special cases when enchanted precision is needed.
