### ISSUE TITLE
Parquet file read error

### ISSUE THREAD

**Issue by peterchap** [pola-rs/polars#2621]
I am trying read an parquet file as a test and getting the following error

Traceback (most recent call last):
  File "c:\Code\Sonardata\polars_A_group.py", line 6, in <module>
    df = (pl.read_parquet(directory + file)
  File "C:\ProgramData\Anaconda3\envs\env01\lib\site-packages\polars\io.py", line 866, in read_parquet
    return DataFrame._read_parquet(
  File "C:\ProgramData\Anaconda3\envs\env01\lib\site-packages\polars\internals\frame.py", line 537, in _read_parquet
    self._df = PyDataFrame.read_parquet(
RuntimeError: Any(ArrowError(NotYetImplemented("Decoding \"Plain\"-encoded optional any pages is not yet implemented for Binary")))

The code I am running is:

import polars as pl

directory = "D:/rapid7/"
file = "Av2.parquet"

df = (pl.read_parquet(directory + file)
      .groupby('value')
      .agg(pl.count('value'))
      .sort('value_count', reverse=True)
      )
df.to_parquet(directory + 'polartest.parquet')
The parquet file is 3GB with 2 columns.  There are 255,008,536 rows.

The versions I am running are:

# Name                    Version                   Build  Channel    
blas                      1.0                         mkl
bottleneck                1.3.2            py39h7cc1a96_1
ca-certificates           2021.10.26           haa95532_4
certifi                   2021.10.8        py39haa95532_2
intel-openmp              2021.4.0          haa95532_3556
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
numexpr                   2.8.1            py39hb80d3ca_0
numpy                     1.22.2                   pypi_0    pypi     
numpy-base                1.21.5           py39hc2deb75_0
openssl                   1.1.1m               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.0                    pypi_0    pypi     
pip                       21.2.4           py39haa95532_0
polars                    0.13.0                   pypi_0    pypi     
pyarrow                   7.0.0                    pypi_0    pypi     
pyparsing                 3.0.4              pyhd3eb1b0_0
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
pytz                      2021.3                   pypi_0    pypi     
setuptools                58.0.4           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.37.2               h2bbff1b_0
typing-extensions         4.0.1                    pypi_0    pypi     
tzdata                    2021e                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2

Any ideas?

**Comment by jorgecarleitao** [comment]
Thanks for the report and sorry for it - this is a regression in main. Fixing it here: https://github.com/jorgecarleitao/arrow2/pull/831
