### ISSUE TITLE
Support for Converters

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2627]
#### Describe your feature request
Pandas read_csv accepts converters to pre-process each field. This is very useful especially for int64 validation or mixed dateformats etc. Does Polar has it or having plans to support ?

**Comment by ritchie46** [comment]
The pandas csv parser is also horribly slow. I think adding this complexity will not do the csv-parsing any good, nor is needed.

If you want to modify a column, you can always read that column as `pl.Utf8` and then  modify it and cast it;

```python
csv = """a,b,c
#12,1,2,
#1,3,4
1,45,5""".encode()

(pl.read_csv(csv, dtypes={"a": pl.Utf8})
     .with_column(pl.col("a").str.replace("#", "").cast(pl.Int64))
)
```

Reads as:

```
shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 12  ┆ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 3   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 45  ┆ 5   │
└─────┴─────┴─────┘
```

**Comment by NarayanB** [comment]
Agree, it works. Is there a way, i can specify multiple columns in one short ?  Maybe nested calls will work but from a timing perspective, it is an extra call after df is created. Any thoughts ?

**Comment by NarayanB** [comment]
type - one shot

**Comment by alexander-beedie** [comment]
> Is there a way, i can specify multiple columns in one shot 

Like so? (Converting both "a" and "b" in one call to `with_columns`)

```python
csv = """a,b,c
#12,1%,2,
#1,3%,4
1,45%,5""".encode()

df = pl.read_csv(
    file = csv,
).with_columns([
    pl.col("a").str.replace("#", "").cast(pl.Int64),
    (pl.col("b").str.replace("%","").cast(pl.Float32)/100),
]).rename(
    {"a":"a_int","b":"b_pct"}
)

# ┌───────┬───────┬─────┐
# │ a_int ┆ b_pct ┆ c   │
# │ ---   ┆ ---   ┆ --- │
# │ i64   ┆ f32   ┆ i64 │
# ╞═══════╪═══════╪═════╡
# │ 12    ┆ 0.01  ┆ 2   │
# ├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
# │ 1     ┆ 0.03  ┆ 4   │
# ├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
# │ 1     ┆ 0.45  ┆ 5   │
# └───────┴───────┴─────┘
```

**Comment by ritchie46** [comment]
@alexander-beedie is excellent. I want to add that if you want to add the same rule to all columns of `Utf8` you can write this and the expression will automatically expand to all columns of that `dtype`

```python
csv = """a,b,c
#12,1#,2,
#1,3#,4
1,45#,5""".encode()

pl.read_csv(
    file = csv,
).with_columns([
    pl.col(pl.Utf8).str.replace("#","").cast(pl.Int64),
])

```

**Comment by ritchie46** [comment]
@NarayanB could you ask this on StackOverflow as well? Then we can provide these answers there as other people will likely find this useful as well.

**Comment by NarayanB** [comment]
Sure - https://stackoverflow.com/questions/71119197/polar-converters-like-pandas

**Comment by ritchie46** [comment]
Thanks! Sorry for the harsh reception.
