### ISSUE TITLE
Group and Join on float column with `NaN` values creates duplicate groups.

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#2643]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

"lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "rows", "round_series"

#### What version of polars are you using?

0.19.1

#### What operating system are you using polars on?

macOs Monterey 12.1

#### Describe your bug.

Grouping and joining lazy frames with Float64 columns with NaN and Null produces duplicate groups.

#### What are the steps to reproduce the behavior?

I've been able to reproduce the issue with `NaN` values in a float group and join leading to duplicate groups.

```rust
#[test]
fn join_numeric_null() {
    use polars::prelude::*;
    let df1 = df! {
             "w" => [Some(2.5), None, Some(f64::NAN), None, Some(2.5), Some(f64::NAN), None, Some(3.0)],
             "t" => [Some("xl"), Some("xl"), Some("xl"), Some("xl"), Some("xl"), Some("xl"), Some("xl"), Some("l")],
            "c" => [Some(10), Some(5), Some(3), Some(2), Some(9), Some(4), Some(11), Some(3)],
        }.unwrap()
        .lazy();
    let a1 = df1
        .clone()
        .groupby(vec![col("w").alias("w"), col("t").alias("t")])
        .agg(vec![col("c").sum().alias("c_sum")]);
    let a2 = df1
        .groupby(vec![col("w").alias("w"), col("t").alias("t")])
        .agg(vec![col("c").max().alias("c_max")]);
    let res = a1
        .join_builder()
        .with(a2)
        .left_on(vec![col("w").alias("w"), col("t").alias("t")])
        .right_on(vec![col("w").alias("w"), col("t").alias("t")])
        .how(JoinType::Outer)
        .finish()
        .collect()
        .unwrap();
    dbg!(res);
}
```

#### What is the actual behavior?

```
+-------+------+-----+-------+
| c_sum | w    | t   | c_max |
| ---   | ---  | --- | ---   |
| i32   | f64  | str | i32   |
+=======+======+=====+=======+
| null  | NaN  | xl  | 4     |
+-------+------+-----+-------+
| 3     | 3.0  | l   | 3     |
+-------+------+-----+-------+
| 18    | null | xl  | 11    |
+-------+------+-----+-------+
| 19    | 2.5  | xl  | 10    |
+-------+------+-----+-------+
| 7     | NaN  | xl  | null  |
+-------+------+-----+-------+
```
Notice the duplicate group `w: NaN - t: xl`

#### What is the expected behavior?

Only a single row of `NaN - xl` should exist when joining.

#### Note

I've not been able to reproduce this yet, but I'm seeing similar issues when grouping
on float columns with `Null` not just the `NaN` case shown above. However, this is 
on real data and with more advanced queries and I've not found a minimal example.
However, they are conceptually similar as the example above. 
I'll create a new issue if I'm able to reproduce that, but it may be good to be aware and maybe
be on the lookout for that as well, even though I've not been able to
reproduce it in a test.

**Comment by SimonSchneider** [comment]
Thank you!

I would agree with you on not comparing floats, however, the particular domain has quite a lot of decimal values being used for comparison rather than arithmetics. I do hear your warning though.

I've tried the larger test that also showed issues for `null` values on master and it seems that it has indeed been fixed.

**Comment by ritchie46** [comment]
Great :)
