### ISSUE TITLE
Request - support for `series.alias` inside `expr.map`.

### ISSUE THREAD

**Issue by akdor1154** [pola-rs/polars#2649]
#### Describe your feature request
I'm trying to map an operation over multiple columns, but assign the result to new columns and keep the old.
I thought this should work:
```py
pl.DataFrame([pl.Series(name='A', values=[1,2,3])])
.with_columns(
  pl.col('A').map(
    lambda c: (c*2).alias(c.name+'_bigger')
  )
)
```

Expected:
|A|A_bigger|
|--|--|
|1|2|
|2|4|
|3|6|

Actual:
|A|
|--|
|2|
|4|
|6|

**Comment by ritchie46** [comment]
Why not alias the map? An alias should qlways be on the outer expression for consistency.

**Comment by akdor1154** [comment]
Ah maybe i reduced the example too much haha. I'm mapping/aliasing multiple columns. `pl.col(['A', 'B', 'C']).map(lambda c: (c*2*pi).alias(c.name + '_rad'))`

**Comment by ritchie46** [comment]
Use a suffix?

```python
a = [1,2,3]
pi = 3.14

out = pl.DataFrame({
    "A": a,
    "B": a,
    "C": a,
}).with_columns(
    pl.col(['A', 'B', 'C']).map(lambda c: (c*2*pi)).suffix("_rad")
)

print(out)
```

```
shape: (3, 6)
┌─────┬─────┬─────┬───────┬───────┬───────┐
│ A   ┆ B   ┆ C   ┆ A_rad ┆ B_rad ┆ C_rad │
│ --- ┆ --- ┆ --- ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ i64 ┆ i64 ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═════╪═════╪═══════╪═══════╪═══════╡
│ 1   ┆ 1   ┆ 1   ┆ 6     ┆ 6     ┆ 6     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 2   ┆ 12    ┆ 12    ┆ 12    │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3   ┆ 3   ┆ 3   ┆ 18    ┆ 18    ┆ 18    │
└─────┴─────┴─────┴───────┴───────┴───────┘
```

There is also `keep_name` that gives you access to the root name of the expression.

**Comment by akdor1154** [comment]
I was trying to replace part of the name actually. But i guess this is more of a corner case than I realised, suffix is 90% of the way.
I really appreciate your efforts to keep the API small btw.

**Comment by ritchie46** [comment]
> EDIT from pc: still interested in .alias inside .map though - it means the user gets complete generality of renaming logic, just from the existing building blocks of polars api. They can just use whatever py/rust string ops they are used to. .suffix then just becomes a special case.
I really appreciate your efforts to keep the API small btw.


I think we should add an expression that allows you to rename the column. Something like `alias(lambda x: x.replace("foo", "bar")`. 

Still an alias in a `map` expression should never bubble up. It will become an inconsistent mess. People generate complicated expression trees and we need to have consistent rules. That is that the outer expression determines the output name.

**Comment by ritchie46** [comment]
Maybe this would help: #2678

**Comment by ritchie46** [comment]
I have been thinking about if we could make an exception for `map` because it may be useful to create a name determined by the data in the column. But this is not possible sadly, as we must know the schema of a polars computation statically (before running any data) so we will have to do with predetermined column names based on schema values instead of data values.

I am closing this because I think with #2678 we have given all flexibility there is.

**Comment by akdor1154** [comment]
Makes sense, and still a general-as-possible solution. Thanks!
