### ISSUE TITLE
filter selection giving wrong counts?

### ISSUE THREAD

**Issue by peterchap** [pola-rs/polars#2651]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.13.1

#### What operating system are you using polars on?

Windows 11

#### Describe your bug.

I  amd trying to a groupby count and found I got a different count compared with alternative methods.  I narrowed the problem down to a simple selection seen here.  I am running the following code on a parquet file with 255m rows and 2 columns called domain and value.  The value columns contains IP addresses. For a specific IP address shown below I get a count of 18,886,485 using Polars. If I run the same query using Arrows 7 directly or using DuckDB, I get a count of 25,692,343. I can provide a copy of the file if needed.

#### What are the steps to reproduce the behavior?
```python
import polars as pl

directory = "D:/domains/"
file = "Av2.parquet"

df = (pl.read_parquet(directory + file)
      .lazy()
      .filter(pl.col('value') == '34.102.136.180')
      .collect()
      )
print(df.shape)
```
```python
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd
import numpy as np

file = "Av2.parquet"
directory = "D:domains/"
key = "34.102.136.180"

dataset = pq.ParquetDataset(
    directory + file, use_legacy_dataset=False, filters=[("value", "=", key)]
)
df = dataset.read().to_pandas()
print(df.shape)
```

If possible, please include a minimal example on a dataset that is create through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```
your
code
goes
here
```

**Example**

```python
import polars as pl
import numpy as np

# Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
})
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think polars should have done?

**Comment by ritchie46** [comment]
Could you try to remove some some rows from the parquet file to pin down the problem. And does this work in if you use polars eager?

**Comment by peterchap** [comment]
I have run it with Lazy and eager and there is no difference.  

I cut file down from 255M to a 50M sample and the results were much closer but not the same.

5,125,200 on Polars vs. 5,126,207 on Arrow direct.

On a 25M sample the results are
2,559,199  On Polars  vs 2,559,337 on Arrow Direct

My PC hardware is 32GB Ram, AMD Ryzen 9 5900X 12-Core Processor  3.70 GHz and GeForce RTX 3060 graphics card

**Comment by jorgecarleitao** [comment]
this may be in the parquet reader in arrow2 :/

**Comment by ritchie46** [comment]
@peterchap could you verify that reading the files without filter gives the same result as in pyarrow.

And could you pherhaps share the cut down file?

**Comment by peterchap** [comment]
I tried the smaller sample with fastparquet into pandas and got the same result as with arrow.

The count without the filter is 25,449,000 with Polars and 24,451,679 with arrow or pandas/fastparquet.

The sample file is 400MB which I can upload

**Comment by peterchap** [comment]
Pressed the wrong button - didnt mean to close

**Comment by ritchie46** [comment]
> The sample file is 400MB which I can upload

Please. :)

**Comment by peterchap** [comment]
Where shouild I post the file?

**Comment by peterchap** [comment]
I tried that but its too big.  Btw I also checked the the parquet meta data which matches the count ig ot from arrow and fastparquet

**Comment by ritchie46** [comment]
Maybe with wetransfer?

**Comment by peterchap** [comment]
Wetransfer is fine just need an email address to give you access

**Comment by ritchie46** [comment]
ritchie46@gmail.com

**Comment by peterchap** [comment]
Just sent it across

**Comment by ritchie46** [comment]
We are now pushing a release. Could you check if it is fixed by `polars==0.13.2`?

**Comment by peterchap** [comment]
Just tried it with 0.13.2 and I am getting the same results as 0.13.1.

**Comment by peterchap** [comment]
Just to confirm, it is now working correctly

**Comment by ritchie46** [comment]
Thanks for the heads up:-)

**Comment by peterchap** [comment]
Many thanks for sorting it.  I am scaling it up to bigger stuff so will probably be back :-)
