### ISSUE TITLE
datetime.fromtimestamp in polars

### ISSUE THREAD

**Issue by kootenpv** [pola-rs/polars#2652]
Hi, I'm wondering if I am overlooking a fast way to transform seconds since epoch into a datetime object in polars?

In pandas:

```python
times = pd.Series([1638665995, 1638665996])
pd.to_datetime(times)
```

Or pure python:

```python
from datetime import datetime
times = [1638665995, 1638665996]
[datetime.fromtimestamp(x) for x in times]
```

**Comment by ritchie46** [comment]
Given that polars `Datetime` is implemented as units since the unix epoch we could do:

```python
(pl.Series([1638665995, 1638665996]) * 1000).cast(pl.Datetime).dt.and_time_unit("ms")
```

Available units are `["ns", "us", "ms"]`


The pure python variant would already have worked:

```python
times = [1638665995, 1638665996]
pl.Series([datetime.fromtimestamp(x) for x in times])
```
