### ISSUE TITLE
is_in fails when comparing strings to empty list

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2672]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.13.1

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

`is_in` throws an error if you're trying to see if a string column is in an empty list

#### What are the steps to reproduce the behavior?

```
>>> pl.DataFrame({'foo': ['a', 'b', 'c', 'd']}).filter(pl.col('foo').is_in([]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1635, in filter
    .collect(no_optimization=True, string_cache=False)
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_frame.py", line 398, in collect
    return pli.wrap_df(ldf.collect())
RuntimeError: Any(SchemaMisMatch("cannot do is_in operation with left a dtype: Utf8 and right a dtype Float32"))
```

#### What is the expected behavior?

```
shape: (0, 1)
┌─────┐
│ foo │
│ --- │
│ str │
╞═════╡
└─────┘
```

#### Notes:

* `is_in` works for strings if the list is nonempty.
* This comparison works if the column being compared is an int column

**Comment by ritchie46** [comment]
Is in creates a `Series` from the list. In the case of the empty list we cannot infer the type so you have to pass a Series yourself.


Why compare with an empty list?

**Comment by ritchie46** [comment]
But i guess for an empty list comparison we could always return false

**Comment by LiterallyUniqueLogin** [comment]
Yeah, that empty check seems right.

If the list is generated from data and is only sometimes empty, then it shouldn't crash on those corner cases.
