### ISSUE TITLE
Control the ordering of the output of Series.unique()

### ISSUE THREAD

**Issue by gc1o1** [pola-rs/polars#2674]
I think currently the output of `unique()` is random.  For example, 
```
s = pl.Series("a", [1, 2, 2, 3])
s.unique()
```
returns a different series each time I run `s.unique()`.
I could do `s.unique().sort()` to avoid that, but that isn't always what I need.  

There are two well-established approaches to this:

* One is Pandas's, where the output preserves the order of values in the input.  In this case, it would be `[1,2,3]`, but if the input series was `[3,2,2,1]`, then the Pandas's `unique()` would give me `[3,2,1]`.   If I want I can sort that myself.
* The other is NumPy's, where the output is always sorted.  If I want to preserve the order of the input, NumPy gives me the option to request certain indices from `unique()`, which can then be used to rearrange the sorted output appropriately.

The problem with Polars is that its `unique()` is unpredictable.  It's neither sorted nor order-preserving.
I understand this is worth it, if it is necessary for a faster execution.
After all, I can sort it myself, if I want to make it like NumPy and I'm willing to pay the time penalty.

But it doesn't offer me an easy way to make it order-preserving, like Pandas.  (I guess I could convert it to Pandas and then call Pandas's `unique()` on it, but that's a much bigger overhead than staying within Polars the whole time.)

Ideally, I would like to pass an optional argument to Polars's `unique()`, like `preserve=True`, to make it preserve the order like Pandas does.  Its default behavior should remain as is, if that's optimal for speed.  And, if I want it sorted, I can easily add `.sort()`, so the only thing missing is a way to behave like Pandas, through an optional argument like the above.

Thank you for considering this.  
Or for telling me why it's a bad idea.  
Or for showing me an easy way to do what I need without converting to Pandas.
Thanks!

**Comment by ritchie46** [comment]
You definitely don't need to go to pandas for this:

```python
s = pl.Series("a", [1, 1, 1, 2, 2, 2, 3])

# on series
print(s.to_frame().groupby("a", maintain_order=True).first().to_series())

# on expression
print(pl.select(pl.lit(s).map(lambda s: s.to_frame().groupby("a", maintain_order=True).first().to_series())))
```

```
shape: (3,)
Series: 'a' [i64]
[
	1
	2
	3
]
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
└─────┘

```


But I shall see if we can add a `maintain_order` argument as well.

**Comment by ritchie46** [comment]
I totally forgot we have got `arg_unique` + `take`. 

```python
s = pl.Series("a", [1, 1, 1, 2, 2, 2, 3])

print(s.take(s.arg_unique()))

print(s.to_frame()
    .select(pl.col("a").take(pl.col("a").arg_unique())))
```

**Comment by gc1o1** [comment]
These are great solutions, @ritchie46 .  
I hadn't seen arg_unique() was even there.
Thank you very much.
