### ISSUE TITLE
read_csv with 0 data rows

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2686]
calling pl.read_csv on a csv file with just header and no data rows results in PanicException - no lines in the file. Dont think it can be caught in Python. Any other options to catch gracefully and not proceed ?

**Comment by universalmind303** [comment]
I think this is related to #2685

**Comment by Maxyme** [comment]
@NarayanB I noticed the same issue when reading IPC's with header information but no rows. I think https://github.com/pola-rs/polars/pull/2685 should fix the issue.

**Comment by ritchie46** [comment]
This has been fixed.
