### ISSUE TITLE
Cannot write to Avro file (path); only to buffer

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2689]
#### What language are you using?

Python 3.9, Window 10, polars 0.13.3

#### Describe your bug.

* Providing a target filepath (to a file that doesn't exist yet) and calling `df.to_avro(...)` results in -
  `FileNotFoundError: The system cannot find the file specified. (os error 2)`.

* Creating an empty file at the target path and calling `df.to_avro(...)` results in - 
   `RuntimeError: Any(ArrowError(Io(Os { code: 5, kind: PermissionDenied, message: "Access is denied." })))`.

* Writing to a buffer (eg:`BytesIO`) instead of a filepath succeeds.

#### What are the steps to reproduce the behavior?

```python
from pathlib import Path 
import polars as pl

# setup test data
df = pl.from_dict({
    'colx':['a','b','c'],
    'coly':[123,456,789],
})
# declare export filepath
target_file = 'test_data.avro'

# try export; raises an error
df.to_avro( target_file )

>>> FileNotFoundError: The system cannot find the file specified. (os error 2)

# create the file with read/write permissions and try export again; raises a different error
Path( target_file ).touch( mode=666 )
df.to_avro( target_file )

>>> RuntimeError: Any(ArrowError(Io(Os { code: 5, kind: PermissionDenied, message: "Access is denied." })))
```

#### What is the expected behavior?

Should succeed in writing the output file when given a filepath (whether it initially exists, or otherwise), consistent with the other export functions (eg: `to_ipc`,`to_parquet`,etc). Writing the same data to a buffer succeeds, like so:

```python
from io import BytesIO
target_buffer = BytesIO()

df.to_avro( target_buffer )

target_buffer.seek(0)
print( target_buffer.getvalue()[:20] )

>>> b'Obj\x01\x02\x16avro.schema\xec\x01{' ...
```
The following approach also works:
```python
with open( target_file,'wb' ) as output:
    df.to_avro( output )
```

**Comment by ghuls** [comment]
Till it is fixed, you can write an avro file with:
```python
with open(target_file, 'wb') as avro_fh:
    df.to_avro(avro_fh)
```

**Comment by ghuls** [comment]
https://github.com/pola-rs/polars/pull/2692

@ritchie46 It might be good to improve get_either_file as when not using truncate it opens a file for reading only, so it would be better that read, write, append is passed to get_either_file.().
