### ISSUE TITLE
"read_csv" can close input buffers, resulting in subsequent errors if those buffers are still needed

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2696]
#### What language are you using?

Python 3.9, Windows 10, polars 0.13.3

#### Describe your bug.

Calling `read_csv` on a BytesIO object can close it.

#### What are the steps to reproduce the behavior?

```python
from io import BytesIO
import polars as pl

# create binary test data and initialise a frame (works fine)
buf = BytesIO( b'\xf0\x9f\x98\x80,5.55,333\n\xf0\x9f\x98\x86,-5.0,666' )
df = pl.read_csv( buf, has_header=False, new_columns=['smile','float','integer'] )

# ┌───────┬───────┬─────────┐
# │ smile ┆ float ┆ integer │
# │ ---   ┆ ---   ┆ ---     │
# │ str   ┆ f64   ┆ i64     │
# ╞═══════╪═══════╪═════════╡
# │ 😀    ┆ 5.55  ┆ 333     │
# ├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
# │ 😆    ┆ -5.0  ┆ 666     │
# └───────┴───────┴─────────┘

# however... any further operations on the initialising buffer now throw errors
data = buf.getvalue()
>>> ValueError: I/O operation on closed file.

buf.closed
>>> True
```

#### What is the expected behavior?

Calling `read_csv` should not result in closed input buffers - they may still be needed by the calling code. 

(Note: the same problem does not occur with `StringIO`).

**Comment by ghuls** [comment]
Use `buf.getvalue()` if you need the BytesIO object later.
```python
df = pl.read_csv(buf.getvalue(), has_header=False, new_columns=['smile','float','integer'] )
```

**Comment by alexander-beedie** [comment]
Thanks; I had a dig around and found the bug - got a simple fix (and a new unit test) here: pull request #2703.

**Comment by alexander-beedie** [comment]
@ghuls: Thanks; found the bug and made a simple fix (plus added a unit test) - pull request #2704 (updated).
