### ISSUE TITLE
Splitting io test in `py-polars`

### ISSUE THREAD

**Issue by illumination-k** [pola-rs/polars#2708]
All of io test in `py-polars` in one file now, it is difficult to what tests are implemented in each format.

I think we should split the tests into `csv`, `ipc`, `json`, `parquet`, and `avro` like lazy_io tests.

**Comment by ritchie46** [comment]
I think we should rename `lazy_io` tests to `io_tests` and add `test_csv`, `test_ipc` etc. Files can write to that directory and created files will be ignored by `.gitignore` there.

**Comment by illumination-k** [comment]
Lazy api should test not only io logic but also dataframe operation logic, so IMO splitting them from only io test is better. What do you think put `test_lazy_csv` etc., and `test_csv` etc., in `io_tests`?

**Comment by ritchie46** [comment]
Lazy code is already tested in `test_lazy` and `test_expr` and actually in more places because it is interweaved in polars eager.

But, yeah we could split in `test_lazy_filetype` and `test_filetype`. :+1:

**Comment by illumination-k** [comment]
I'll try to split like that.
