### ISSUE TITLE
Filter dates with "2020-01-01"

### ISSUE THREAD

**Issue by keiv-fly** [pola-rs/polars#2710]
Current behavior:
df.filter(pl.col("MyDate") >= pl.datetime(2020,1,1))

Want the way pandas allows it:
df.filter(pl.col("MyDate") >= "2020-01-01")

"2020-01-01" is an international standard for writing dates.

**Comment by ritchie46** [comment]
Yes, but it is a `string` not a `datetime`. In my opinion we should stay true to `datatypes`.

**Comment by keiv-fly** [comment]
pl.datetime("2020-01-01") does not work

**Comment by ritchie46** [comment]
No the function does not take a string. It takes a `year, month, day, ... etc`.

**Comment by keiv-fly** [comment]
So what is the inverse function to polars.internals.series.DateTimeNameSpace.strftime that works for scalars? Like pd.to_datetime("2020-01-01") in pandas?

**Comment by ritchie46** [comment]
The `str` namespace has a `strptime` function. Expression literals also accept python `datetetime.datetime` and `datetime.date` objects. 

These are all questions I need to answer a lot. Can you open them on stackoverflow? I will answer the questions there, but it will serve as a repository of quality answers that will help users find answers to the same questions you have.

**Comment by keiv-fly** [comment]
I opened an original question. But strptime probably needs another question.

**Comment by ritchie46** [comment]
https://stackoverflow.com/questions/71196737/how-to-filter-a-polars-dataframe-by-date
