### ISSUE TITLE
add .drop_duplicates()

### ISSUE THREAD

**Issue by keiv-fly** [pola-rs/polars#2713]
There is no .drop_duplicates() function in python polars like in pandas, but there is a workaround:
```
df.groupby(["a", "b", "c"]).first()
```

Could we add `df.drop_duplicates(subset=None, keep='first')`?

**Comment by ritchie46** [comment]
There is `.distinct()`.

**Comment by keiv-fly** [comment]
That works. Is it ok if I write the question on stackoverflow and create an answer for it?

And we can close the issue.

**Comment by keiv-fly** [comment]
The main problem is that I cannot find it using google.

**Comment by ritchie46** [comment]
> Is it ok if I write the question on stackoverflow and create an answer for it?

Yes, Thanks for that! :)
