### ISSUE TITLE
Confusing error message when calling scan_csv on an empty file

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2714]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.1

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### What language version are you using

python 3.7.9

#### Describe your bug.

When calling `scan_csv` on an empty file, a confusing message about buffers appears instead of simply saying the file was empty.

#### What are the steps to reproduce the behavior?

```
import polars as pl
pl.scan_csv('empty_file.csv').collect()
```
#### What is the actual behavior?

```
>>> import polars as pl
>>> pl.scan_csv('foo.csv').collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/io.py", line 579, in scan_csv
    row_count_offset=row_count_offset,
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_frame.py", line 109, in scan_csv
    _prepare_row_count_args(row_count_name, row_count_offset),
RuntimeError: Any(Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }))
```
#### What is the expected behavior?

The same as when calling read_csv - say the file is empty

```
>>> import polars as pl
>>> pl.read_csv('foo.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/io.py", line 417, in read_csv
    row_count_offset=row_count_offset,
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 487, in _read_csv
    _prepare_row_count_args(row_count_name, row_count_offset),
RuntimeError: Any(NoData("empty csv"))
```

**Comment by LuisCardosoOliveira** [comment]
Hey there! I'd like to take this issue 😃

**Comment by ritchie46** [comment]
Please. :)

**Comment by LuisCardosoOliveira** [comment]
Thanks @ritchie46! I'll take a look ASAP 😃

Do you have any advice to give me about this particular issue? It's my first time contributing to Polars 😄

**Comment by LuisCardosoOliveira** [comment]
I'm having some troubles trying to run `make test` at `py-polars` 😵

It seems an issue with `arrow2` and I believe it is linked to this [issue](https://github.com/jorgecarleitao/arrow2/pull/912)

**Comment by ritchie46** [comment]
Oh yes. We need a very specific nightly compiled. 3 march 2022 is the one.

**Comment by ritchie46** [comment]
Try setting `rustup override set nightly-2022-03-16` in `polars/polars`. We are quite bleeding edge with regard to `std::simd`. :sweat_smile:

**Comment by LuisCardosoOliveira** [comment]
> Try setting `rustup override set nightly-2022-03-16` in `polars/polars`. We are quite bleeding edge with regard to `std::simd`. 😅

Thanks :) 

Just opened a PR 💪

**Comment by phillyphil91** [comment]
This is done as well, right @ritchie46  ?

**Comment by ritchie46** [comment]
Yes!
