### ISSUE TITLE
"is_not_nan()" does work for null values

### ISSUE THREAD

**Issue by keiv-fly** [pola-rs/polars#2715]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.4

#### What operating system are you using polars on?

Windows 10

#### What language version are you using
Python 3.9

#### Describe your bug.

pl.col("a").is_not_nan() does work for null values

#### What are the steps to reproduce the behavior?

```
import polars as pl
df = pl.DataFrame({"a":[1,2,None], "b":[2,3,4]})
df.select(pl.col("a").is_not_nan())
```
outputs
```
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ bool │
╞══════╡
│ true │
├╌╌╌╌╌╌┤
│ true │
├╌╌╌╌╌╌┤
│ true │
└──────┘
```
But the last line should be False.
Expressions do not have .is_not_null() like Series do, so no way to check for null values with Expressions.

**Comment by ritchie46** [comment]
`is_nan` check for floating point `NaN` values, not missing values.

>  Expressions do not have .is_not_null() like Series do, so no way to check for null values with Expressions.

They do? https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.is_not_null.html

**Comment by keiv-fly** [comment]
```
>>> df.select(pl.col("a").is_not_null())
shape: (3, 1)
┌─────────────┐
│ is_not_null │
│ ---         │
│ bool        │
╞═════════════╡
│ true        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true        │
└─────────────┘
```

**Comment by keiv-fly** [comment]
Still does not work.

**Comment by keiv-fly** [comment]
Sorry, I probably forgot to write "is" in front of "not_null". Yes it does work now with "is_not_null"
