### ISSUE TITLE
rust pivot method not found in `polars::prelude::GroupBy<'_>`

### ISSUE THREAD

**Issue by ray-5050** [pola-rs/polars#2724]
#### What language are you using?

Rust

#### Which feature gates did you use?

None

#### What version of polars are you using?

polars = "0.19.1".

#### What operating system are you using polars on?

Linux Mint 20.3  base: Ubuntu 20.04

#### What language version are you using
rust version 1.58.1

#### Describe your bug.
I'm fairly new to rust and have used other functions in polars with no problem but when I tried to use the pivot function, I get an error saying module doesn't exist.  If I comment out the pivot line, groupby works.

     .pivot(["bar"], ["N"])
         ^^^^^ method not found in `polars::prelude::GroupBy<'_>`

#### What are the steps to reproduce the behavior?
see code below.

```
use polars::prelude::*;
use polars::df;

fn example() -> Result<DataFrame> {
    let df = df!["foo" => ["A", "A", "B", "B", "C"],
        "N" => [1, 2, 2, 4, 2],
        "bar" => ["k", "l", "m", "n", "0"]
        ]?;

    df.groupby(["foo"])?
    .pivot(["bar"], ["N"])
    .first()

}

fn main() {

    let df = example().unwrap();
    println!("{:?}", df);

}
```
#### What is the expected behavior? 
pivot is available for use

#### What do you think polars should have done?
pivot table

**Comment by ritchie46** [comment]
You need to opt-in to several features: See: https://pola-rs.github.io/polars/polars/index.html#compile-times

**Comment by ray-5050** [comment]
I used "use polars::df;" and the dataframe includes pivot.  I don't see any other specific import for pivot.  Thanks for your help.

**Comment by ritchie46** [comment]
Have you activated the `pivot` feature?

**Comment by ray-5050** [comment]
i"m a bit new to rust but I tried in the toml file like I've seen before 
polars = { version = "0.19.1", features = ["pivot"] }
I get an error saying no feature for pivot.

**Comment by ritchie46** [comment]
Sorry. This is what the docs say:

```
rows - Create DataFrame from rows and extract rows from DataFrames. And activates pivot and transpose operations
```

**Comment by ray-5050** [comment]
Sorry but I'm not following you on how this works.  I'm using an example from the docs on how to use pivot.  My expectation was that I could use the example using the imports shown.  However, I get "pivot" not found on compiling.  When I look in the crate under Dataframe, impl, the first function is pivot, so I'm at a loss on why its not found.  I've not had this issue on the other functions.  Again sorry for not following you but I'm at a total loss here on getting this to work.  Would you be able to supply me with an example on how this is done like in the docs?  Thanks.

**Comment by ritchie46** [comment]
Add this to your `Cargo.toml`

```toml
polars = { version: "0.19", features = ["rows"] }
```

**Comment by ray-5050** [comment]
Thanks a lot for your help on this, I didn't pick on the fact that the feature was row.  The problem when you a new at learning something, what seems obvious to the developers is not to others.  Maybe placing the word feature in front of row would help or just listing all of the features someplace.  Again, thanks for your help and i'll make a donation to the team.

**Comment by ritchie46** [comment]
Yes.. that's why we have the features listed here. 

https://pola-rs.github.io/polars/polars/index.html#compile-times

We have a lotbof features to reduce the compile times so you only pay for what you need.

And thanks for the donation. 🙂
