### ISSUE TITLE
Creation of df with `List` data type doesn't work in new conda envs

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#2725]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.4

#### What operating system are you using polars on?

Linux Ubuntu-2004-focal-64-minimal

#### What language version are you using
python 3.9.10

#### Describe your bug.

Creation of data frame with `list` data type is broken under python 3.9.10 in a completely fresh conda environment (only install: `pip install --no-cache-dir polars`). It seems to work in an old conda env on python 3.9.7 (in both cases: running polars 0.13.4)

#### What are the steps to reproduce the behavior?

```
df = pl.DataFrame({"a": [[1, 2], [3, 4], [5, 6]], "b": [[10, 20], [30, 40], [50, 60]]})
```
yields (under python 3.9.10):
```
┌────────┬──────────┐
│ a      ┆ b        │
│ ---    ┆ ---      │
│ object ┆ object   │
╞════════╪══════════╡
│ [1, 2] ┆ [10, 20] │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ [3, 4] ┆ [30, 40] │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ [5, 6] ┆ [50, 60] │
└────────┴──────────┘
```

but **the same code** running in an old conda env on python 3.9.7 yields:

```
┌────────────┬────────────┐
│ a          ┆ b          │
│ ---        ┆ ---        │
│ list [i64] ┆ list [i64] │
╞════════════╪════════════╡
│ [1, 2]     ┆ [10, 20]   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [3, 4]     ┆ [30, 40]   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [5, 6]     ┆ [50, 60]   │
└────────────┴────────────┘
```

Interestingly, when I create a *fresh* conda env with python3.9.7, the same issue occurs! In other words, the issue only occurs when I create a new conda env and clean install polars. Does this maybe have something to do with dependencies that I randomly installed in my old env that are not available in the fresh envs? 

#### What is the actual behavior?

The columns have dtype `object`

#### What is the expected behavior?
The columns have dtype `list`

**Comment by ritchie46** [comment]
I believe this due to an optional `pyarrow` dependency. Could you try installing `polars[pyarrow]`?

**Comment by moritzwilksch** [comment]
Ahh, indeed, after `pip install pyarrow` the columns always have dtype list.

**Comment by ritchie46** [comment]
Though this ought to work without pyarrow as well. So it is somethin we must fix and add to our tests. We can leave this issue open.
