### ISSUE TITLE
scan_csv(, parse_dates=True) behaves different from read_csv(, parse_dates=True)

### ISSUE THREAD

**Issue by TeXiCiTy** [pola-rs/polars#2734]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.4

#### What operating system are you using polars on?

Windows 10

#### What language version are you using

Python 3.9.2 amd64

#### Describe your bug.

scan_csv() parse_dates behaves different from read_csv()
read_csv(filename, parse_dates=True) returns a Datetime[ms] column
scan_csv(filename, parse_dates=True) returns a string column

#### What are the steps to reproduce the behavior?

```python
data_read = pl.read_csv('mini.csv',parse_dates=True)

query = (
        pl.scan_csv('mini.csv', parse_dates=True)
        )  
data_scan = query.collect()

assert(data_read.dtypes[0] == data_scan.dtypes[0])
```

mini.csv:
```
Date_and_time,Uur
2011-01-01T01:00:00.000000000,1
2011-01-01T02:00:00.000000000,2
2011-01-01T03:00:00.000000000,3
2011-01-01T04:00:00.000000000,4
2011-01-01T05:00:00.000000000,5
```
#### What is the expected behavior?

Expected behaviour is a 'Date_and_time' column parsed to Datetime format when using scan_csv(, parse_dates=True)

#### Additional comments

A function like .to_datetime() would be nice

**Comment by ritchie46** [comment]
> A function like .to_datetime() would be nice

We have got `strptime`

**Comment by TeXiCiTy** [comment]
> We have got `strptime`

Thanks, that [function name](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.series.StringNameSpace.strptime.html) was a little bit to cryptic for me to be found using search. The workaround for now:
```
query = (
    pl.scan_csv('mini.csv')
    .with_column(pl.col('Date_and_time').str.strptime(pl.Datetime,'%F %T', strict=True))
    )  
data_scan = query.collect()
```

**Comment by ritchie46** [comment]
> Thanks, that [function name](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.series.StringNameSpace.strptime.html) was a little bit too

Haha.. yes, I understand. We have chosen it because it has become a standard name in many languages. I believe it stands for STRingParseTIME.

**Comment by ritchie46** [comment]
Scan csv has no `parse_date`s argument. Parsing dates is atm done after we do schema inference. That means we do not yet know which columns will be dates. This cannot be combined with lazy because we need to know the schema at every computation node.

This can be added IFF we add date parsing directly to the csv parser.

**Comment by ritchie46** [comment]
This has been added now in #2923
