### ISSUE TITLE
COnverting pandas DataFrame to polars DataFrame.

### ISSUE THREAD

**Issue by jesusestevez** [pola-rs/polars#2747]
#### What language are you using?
Python

#### What version of polars are you using?

0.13.5

#### What operating system are you using polars on?

W10

#### What language version are you using
python 3.10.2

#### Describe your bug.

ImportError: 'pyarrow' is required for converting a pandas DataFrame to a polars DataFrame.
However, pyarrow has been installed and imported.

#### What are the steps to reproduce the behavior?

```
import pandas as pd
import polars as pl
# import pyarrow as pa

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df_pl = pl.DataFrame(df)
```

#### What is the actual behavior?

```
ImportError: 'pyarrow' is required for converting a pandas DataFrame to a polars DataFrame.
```

#### What is the expected behavior?

Polars should have produced a pl DataFrame.

**Comment by ghuls** [comment]
Restart your python interpreter after install pyarrow.

**Comment by ritchie46** [comment]
I will close this as I don't think this is something on our side. Likely just needs to update pyarrow and restart interpreter.
