### ISSUE TITLE
Wrong conversion of NaN-only pandas.DataFrame with object dtype

### ISSUE THREAD

**Issue by JakobGM** [pola-rs/polars#2749]
#### What language are you using?

**Python**.

#### What version of polars are you using?

`0.13.5`

#### What operating system are you using polars on?

MacOS Monterey 12.1

#### What language version are you using

`python 3.9.10` 

#### Describe your bug.

Conversion of `pandas.Series` and `pandas.DataFrame` to `polars.Series` and `polars.DataFrame` breaks when a series contains only null-like values, truncating the resulting series to shape `(1, 1)`.

#### What are the steps to reproduce the behavior?

**Example 1:**

```py
import pandas as pd
import polars as pl

print(pl.DataFrame(pd.DataFrame(data=[pd.NA, pd.NA])).shape)
```

_Expected output:_ `(2, 1)`
_Actual output:_ `(1, 1)`

**Example 2:**

```py
import pandas as pd
import polars as pl

print(pl.DataFrame(pd.DataFrame(data=[np.nan, np.nan], dtype=object)).shape)
```

_Expected output:_ `(2, 1)`
_Actual output:_ `(1, 1)`

The same goes for `polars.from_pandas()` as an alternative constructor method.

It seems that if polars is provided a null-only representation of an object column it will truncate the result to a `f64` series of length 1.

**Comment by ritchie46** [comment]
I think this is related: https://issues.apache.org/jira/browse/ARROW-8442

**Comment by JakobGM** [comment]
The issue still persists on `0.13.6` unfortunately 🤔
