### ISSUE TITLE
String columns are dropped when converting empty dataframe from PyArrow

### ISSUE THREAD

**Issue by smolcoder** [pola-rs/polars#2751]
#### What language are you using?
**Python**

#### What version of polars are you using?
0.13.5

#### What operating system are you using polars on?
Fedora 28

#### What language version are you using
python 3.7

#### Describe your bug.

String columns are dropped when converting empty dataframe from PyArrow.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame(
    [
        pl.Series("str", [], dtype=pl.Utf8),
    ]
)

print(df)
print(pl.from_arrow(df.to_arrow()))

```

#### What is the actual behavior?

```
shape: (0, 1)
┌─────┐
│ str │
│ --- │
│ str │
╞═════╡
└─────┘
shape: (0, 0)
┌┐
╞╡
└┘
```

#### What is the expected behavior?

```
shape: (0, 1)
┌─────┐
│ str │
│ --- │
│ str │
╞═════╡
└─────┘
shape: (0, 1)
┌─────┐
│ str │
│ --- │
│ str │
╞═════╡
└─────┘
```

**Comment by ritchie46** [comment]
fixed by #2757
