### ISSUE TITLE
Polars is failing to import after OS upgrade

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2764]
Hi there,

My supercomputer upgraded its OS over the last few days, and now I see
```
$ python
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
Segmentation fault (core dumped)
$
```
I tried upgrading polars, and when that didn't work, I uninstalled it with pip and reinstalled it. But I'm still getting this error.

Any advice on how to fix this? Are there cached files that need to be recompiled that I can clear somewhere? Or other dependencies that I might need to reinstall as well?

**Comment by ritchie46** [comment]
> Are there cached files that need to be recompiled that I can clear somewhere?

Not really.

Could you give a bit more information? What is your OS? Does this also occur with polars 0.12? We activated some more cpu targets lately. Maybe that is related. Bit if it is a supercomputer, it should not be.

**Comment by LiterallyUniqueLogin** [comment]
```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

I've installed the latest python update, polars 0.13.5

**Comment by ritchie46** [comment]
Does this also occur with polars 0.12?

**Comment by ghuls** [comment]
I assume it is due to the added instructions when compiling 0.13.5:
https://github.com/pola-rs/polars/commit/fc413ac9300c0d9e8807994a20c268016823d181

What does `grep -m 1 flags /proc/cpuinfo` say?

**Comment by LiterallyUniqueLogin** [comment]
```
$ grep -m 1 flags /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
```
It also crashes on polars 0.12.0

**Comment by ghuls** [comment]
@LiterallyUniqueLogin Could you try in a different python version that you can load on the cluster?

**Comment by LiterallyUniqueLogin** [comment]
Thanks for the help you two. I just tried to run some other code, and learned that `numpy` is failing to import. So this is a wider issue than anything polars related. Closing this out.
