### ISSUE TITLE
some questions about groupby.agg

### ISSUE THREAD

**Issue by longilacus** [pola-rs/polars#2778]
- Q1:  In a `gourpby.agg` view, we can use `head(10)` to get the first 10 elements in a col. But if the groups have different length and I need to get the first `20%` elements like 0-24 in a 120 elements group. how to make it work?

- Q2:  with a dataframe below, my goal is to loop the dataframe. But if I downcasted it into ChunkedArrays and iterated via iter().zip() is faster than the same action after goupby(col("date")). In my opinion, the length of data is shorter after groupby, which means for loop is shorter.  but why the time of loop is slower than without groupby?

<html>
<body>

Date | Stock | Price
-- | -- | --
2010-01-01 | IBM | 1000
2010-01-02 | IBM | 1001
2010-01-03 | IBM | 1002
2010-01-01 | AAPL | 2900
2010-01-02 | AAPL | 2901
2010-01-03 | AAPL | 2902

</body>
</html>

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)

**Comment by ritchie46** [comment]
closed by: https://stackoverflow.com/questions/71273072/questions-about-polars-groupby
