### ISSUE TITLE
Cannot select col from df.apply

### ISSUE THREAD

**Issue by tiphaineruy** [pola-rs/polars#2780]
#### What language are you using?

python

#### Which feature gates did you use?

n/a

#### What version of polars are you using?

❯ pip show polars
Name: polars
Version: 0.13.0

#### What operating system are you using polars on?

MacOs

#### What language version are you using

Python 3.9.2

#### Describe your bug.

The dataframe generated from a dataframe.apply cannot have it's columns selected

#### What are the steps to reproduce the behavior?

Apply a function over a dataframe
And then try to select a col of the generated Dataframe

Here is my code:
( If there is a cleaner way to do It i'm all ears)

```
pldef h3togeo(s):
    test = h3.geo_to_h3(s[0], s[1], 3)
    return test


df_ap = df.select(["lat", "lon"]).apply(h3togeo)
print(df_ap)
print(df_ap.columns)
print(df_ap.schema)
df = df.with_column(df_ap.select(pl.col("apply")))
```

which can be reproduced minimally with:

```
import polars as pl


def func(s):
    return s[0] + s[1]


df = pl.DataFrame({"ham": [1, 2, 3], "hamburger": [11, 22, 33], "foo": [3, 2, 1],})
tmp = df.select(["ham", "hamburger"]).apply(func)
print(tmp.columns)
# This panic raise AttributeError(f"{item} not found")
df = df.with_column(tmp.select("apply").alias("newname"))

# This works
# df = df.with_column(tmp.select_at_idx(0).alias("newname"))

print(df)

```

Which logs:

```
❯ python plop.py
['apply']
Traceback (most recent call last):
  File "xxx/polars/internals/frame.py", line 1212, in __getattr__
    return pli.wrap_s(self._df.column(item))
RuntimeError: Any(NotFound("alias"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/xxx.py", line 11, in <module>
    df = df.with_column(tmp.select("apply").alias("newname"))
  File "xxx/polars/internals/frame.py", line 1214, in __getattr__
    raise AttributeError(f"{item} not found")
AttributeError: alias not found
```

Dataframe columns are: `['apply']`
But you can't select it by name.

#### What is the expected behavior?

Allow selection by name

**Comment by alexander-beedie** [comment]
The errors are actually correct ;)

The result of a `select` op is a DataFrame containing the selected columns, which is not suitable as input to `with_columns`, which expects column _expressions_, not columns in the form of a DataFrame. 

Note also that you call `tmp.select("apply").alias("newname")` in the example - as above, the return from the `select` is a DataFrame, not a column expression, so you can't alias it (and hence the error).

If you are looking to assign a column from one DataFrame into another, you can just do this (using your example above):

```python
df["newname"] = tmp["apply"]
# ┌─────┬───────────┬─────┬─────────┐
# │ ham ┆ hamburger ┆ foo ┆ newname │
# │ --- ┆ ---       ┆ --- ┆ ---     │
# │ i64 ┆ i64       ┆ i64 ┆ i64     │
# ╞═════╪═══════════╪═════╪═════════╡
# │ 1   ┆ 11        ┆ 3   ┆ 12      │
# ├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
# │ 2   ┆ 22        ┆ 2   ┆ 24      │
# ├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
# │ 3   ┆ 33        ┆ 1   ┆ 36      │
# └─────┴───────────┴─────┴─────────┘

However, you may also be better off using `map` in this case:
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.map.html

**Comment by tiphaineruy** [comment]
Right about the select. Thanks
Got confused by the naming. 

I tried the map approach. The thing is map returns series to the function. Not rows.
Hence the .apply at the datafrae level.

I was wondering if there was a more polars idiomatic way of applying a function to "rows"

**Comment by alexander-beedie** [comment]
If you need raw access to the mapped Series values as rows, you could always just iterate over `zip( s[0],s[1] )` inside your function. As long as you return a Series that matches the return_dtype, you can do pretty much anything you like in there.

```python
def func( s ):
    return pl.Series(
        name   = "geo",
        values = [h3_geo_func(x,y) for x,y in zip(s[0],s[1])],
        dtype  = pl.Int64,
    )
```

**Comment by tiphaineruy** [comment]
That's it ! Thanks a lot for the input.
