### ISSUE TITLE
CI: Windows runner fail because we are out of disk space.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#2783]
I haven't found a solution yet by googling. I don't know if the disk space stays within runs and it is accumulated by our `./target` for instance? If so we can remove it.

Or if it is by the amount of files we create during the build/linking?

https://github.com/pola-rs/polars/runs/5343474942?check_suite_focus=true

**Comment by cnpryer** [comment]
I could give this a try soon https://github.com/actions/virtual-environments/issues/1341
