### ISSUE TITLE
read_parquet from multiple files

### ISSUE THREAD

**Issue by Gabriel-ROBIN** [pola-rs/polars#2794]
#### What language are you using?

**Python 3.8**, 

#### What version of polars are you using?

0.13.4

#### What operating system are you using polars on?

Redhat 7.5

#### Describe your bug.

Form the doc, we can see that it is possible to read a list of parquet files. I did not make it work.

#### What are the steps to reproduce the behavior?

**Example**

```python
import polars as pl

df1 = pl.DataFrame({"bar": [1, 2, 3], "foo": [3, 2, 1]})
df2 = pl.DataFrame({"bar": [4, 5, 6], "foo": [3, 2, 1]})
df1.to_parquet('./abc.parquet')
df2.to_parquet('./def.parquet')

pl.read_parquet([
    './abc.parquet',
    './def.parquet'
])

```

#### What is the actual behavior?

Fails with 
TypeError: Object does not have a .read() method.

#### What is the expected behavior?

abc.parquet and def.parquet are concatenate

**Comment by ritchie46** [comment]
You can only read multiple files at once using `glob` patters. E.g.

```python
pl.read_parquet(
    './*.parquet',
)
```

If you want to read without glob patters, you need to call `read_parquet` separately and concat the `DataFrames`.

**Comment by Gabriel-ROBIN** [comment]
Ok, that's what I understood, but in this case there is a typo in the doc string right ? It is said that `source` could be a List[str]

```python
pl.read_parquet(
    source: Union[str, List[str], pathlib.Path, BinaryIO, _io.BytesIO, bytes],
    columns: Union[List[int], List[str], NoneType] = None,
    ...
) -> polars.internals.frame.DataFrame
```

**Comment by ritchie46** [comment]
Fixed

**Comment by alf239** [comment]
Just for the next one bumping into this ticket: it's now added with https://github.com/pola-rs/polars/pull/13044
