### ISSUE TITLE
Column not found when using lazy groupBy agg and joins after upgrading to recent commit

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#2804]
#### What language are you using?

Rust

#### Which feature gates did you use?

`["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"]`

#### What version of polars are you using?

commit: `7ddc947aa5a83ffcd86a96acc03c0836b1f80423` [link](https://github.com/pola-rs/polars/pull/2795) 
the commit before `708a641a9e0d74ad489503c4892b90705a4c6b95` [link](https://github.com/pola-rs/polars/pull/2785) works

#### What operating system are you using polars on?

macOS Monterey 12.1

#### What language version are you using

`rustc 1.59.0 (9d1b2106e 2022-02-23)`

#### Describe your bug.

When upgrading polars to the commit mentioned above my test suite starts failing on tests using groupBy, agg and Joins and being flaky for some other tests. All of the tests make heavy use of lazy but all of them worked with the commit before this one.
The common theme seems to be that a column is not found. Given that the commit in question improved projections I'm guessing there is was some bug being introduced rather than our existing test suite being incorrect.

Sadly I've not been able to reproduce this in a minimal test but am currently investigating if I'm able to reproduce it. Given that some of the tests are flaky also makes me unsure if I'm able to reproduce it minimally or if it depends on size of dataset and or query size. 

#### What are the steps to reproduce the behavior?

None yet sadly 

#### What is the actual behavior?

Common error is: `Error: Not found: {columnName}`

#### What is the expected behavior?

N/A

**Comment by ritchie46** [comment]
Temporary fix in #2807. This is not ideal as it is slower than it has to be, so an example to reproduce the error is still most welcome. :)

**Comment by SimonSchneider** [comment]
Thanks, I've tried out that commit and it seems that it's mostly solved but I'm still getting some flakiness on some tests. I'm going to prioritize getting a proper example.
In the flaky test I have it looks like the columns get shuffled, a unique aggregation on a `utf8` column sometimes results in a aggregation of another `f64` column.
Basically (pseudo just to explain):
```
"a" => ["a", "a", "a"],
"b" => ["1", "1", "3"],
"c" => [5., 10., 15.]

groupBy(col("a")).agg(col("b").unique().alias("bs"), ...)

results in:
"a" => ["a"],
"bs" => [[5., 10., 15.]]

instead of:
"a" => ["a"],
"bs" => [["1", "3"]]
```
It seems like the column order or column resolution is problematic. 

Maybe this was already obvious to you but I thought I'd just let you know until I've gotten a proper example

**Comment by SimonSchneider** [comment]
bear with me:

Given this test:
```rust
#[test]
fn simple_query_manual_stripped() -> Result<()> {
    let in_data = df! {
        "groupcol" =>   ["27.F", "42.DC", "57.B", "27.F", "27.F", "42.DC", "27.F"],
        "id" =>         ["1", "1", "2", "1", "3", "4", "5"],
        "id_amount" => [12.3, 12.3, 4., 12.3, 5.5, 9.3, 100.0],
        "kpi_col_a" =>  [12.0, 15.3, 22.0, 21.5, 12.3, 53.5, 200.0],
        "kpi_col_2" =>  [120., 153., 220., 215., 123., 535., 2000.],
        "tag_col" =>    ["", "", "", "", "", "", "excluded"]
    }?;

    let expected = df! {
        "group_col_alias" => ["42.DC", "27.F", "57.B"],
        "kpi_col_1_sum" =>   [15.3+53.5, 12.0+21.5+12.3, 22.0],
        "kpi_col_2" =>       [688., 458., 220.],
        "id_count" =>        [2_u32, 2, 1],
        "count" =>           [12.3+9.3, 12.3+5.5, 4.],
        "id_amount" =>      [12.3+9.3, 12.3+5.5, 4.],
    }?;

    let filtered = in_data
        .lazy()
        .filter(not(col("tag_col").eq(lit("excluded"))));

    let groupa = filtered
        .clone()
        .groupby(vec![col("groupcol").alias("group_col_alias")])
        .agg(vec![
            col("kpi_col_a").sum().alias("kpi_col_1_sum"),
            col("kpi_col_2").sum().alias("kpi_col_2"),
            col("id").n_unique().alias("id_count"),
            col("id").unique().alias("ids"),
        ]);

    let groupb = filtered
        .groupby(vec![col("groupcol").alias("group_col_alias"), col("id")])
        .agg(vec![
            col("id_amount").max().alias("id_amount"),
            col("id_amount").max().alias("count"),
        ])
        .groupby(vec![col("group_col_alias")])
        .agg(vec![
            col("count").sum().alias("count"),
            col("id_amount").sum().alias("id_amount"),
        ]);

    let result = groupa
        .join_builder()
        .with(groupb)
        .left_on(vec![col("group_col_alias")])
        .right_on(vec![col("group_col_alias")])
        .how(JoinType::Outer)
        .finish()
        .sort_by_exprs(
            vec![col("kpi_col_1_sum"), col("kpi_col_2"), col("id_count")],
            vec![true, true, true],
        )
        .collect()?;

    dbg!("result", &result);
    dbg!("expected", &expected);

    assert!(&result.drop("ids")?.frame_equal_missing(&expected));
    Ok(())
}
```

Running this test without the `--release` flag panics.

Running this test with the `--release` flag set will occasionally fail and produce a bad result:
```
while true; do cargo test --release --package <pkg> --test <test> simple_query_manual_stripped ; if [ $? -ne 0 ]; then break; fi; done
```

```
failures:

---- simple_query_manual_stripped_2 stdout ----
[tests/query.rs:161] "result" = "result"
[tests/query.rs:161] &result = shape: (3, 7)
+-----------------+---------------+-----------+----------+-----------------------+-------+-----------+
| group_col_alias | kpi_col_1_sum | kpi_col_2 | id_count | ids                   | count | id_amount |
| ---             | ---           | ---       | ---      | ---                   | ---   | ---       |
| str             | f64           | f64       | u32      | list [f64]            | f64   | f64       |
+=================+===============+===========+==========+=======================+=======+===========+
| 42.DC           | 68.8          | 688.0     | 2        | [535.0, 153.0]        | 21.6  | 21.6      |
+-----------------+---------------+-----------+----------+-----------------------+-------+-----------+
| 27.F            | 45.8          | 458.0     | 3        | [120.0, 215.0, 123.0] | 17.8  | 17.8      |
+-----------------+---------------+-----------+----------+-----------------------+-------+-----------+
| 57.B            | 22.0          | 220.0     | 1        | [220.0]               | 4.0   | 4.0       |
+-----------------+---------------+-----------+----------+-----------------------+-------+-----------+
```
Notice the ids column contains floats instead of strings.

**Comment by ritchie46** [comment]
> bear with me:

Thanks for the report. I will take a look at this. Maybe I have some questions later. :)

**Comment by alexander-beedie** [comment]
I'll try and extract a minimal repro from our unit/integration test pipeline, but it looks like 13.8 may have exposed a (potentially non-deterministic) error related to this issue, in trying to fix/fallback  :)

A call to collect() after a union of two constrained frames can now panic (for this specific test) with `pyo3_runtime.PanicException: index out of bounds: the len is 2 but the index is 3`. So far the error has appeared only on linux; the same test failure has not occurred -yet- under mac/win. I'll extract the test operations with some sample data and follow-up with that here; might help triangulate.

**Comment by ritchie46** [comment]
Can you set `RUST_BACKTRACE=1`? That would give me a backtrace.

**Comment by alexander-beedie** [comment]
> Can you set `RUST_BACKTRACE=1`? That would give me a backtrace.

Yup. Will try to extract the relevant ops from the failing test and see if I can repro with that.

**Comment by alexander-beedie** [comment]
Can now reliably cause the error using our test pipeline (on an AWS linux box); it is indeed not entirely deterministic, as I have to loop the test to trigger it, but typically the error will show up within the first 5-10 iterations.

**Trace**

```python
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 3', 
  /github/workspace/polars/polars-lazy/src/physical_plan/expressions/column.rs:28:36

stack backtrace:
   0:     0x7fdb077f8533 - <unknown>
   1:     0x7fdb06bc5a0c - <unknown>
   2:     0x7fdb077cea37 - <unknown>
   3:     0x7fdb077f95e2 - <unknown>
   4:     0x7fdb077fa5fd - <unknown>
   5:     0x7fdb077fa082 - <unknown>
   6:     0x7fdb077f9ff6 - <unknown>
   7:     0x7fdb077f9fb2 - <unknown>
   8:     0x7fdb0611aa42 - <unknown>
   9:     0x7fdb0611aa01 - <unknown>
  10:     0x7fdb076a51dd - <unknown>
  11:     0x7fdb07679a19 - <unknown>
  12:     0x7fdb0767a1e0 - <unknown>
  13:     0x7fdb07679d84 - <unknown>
  14:     0x7fdb0767a5a2 - <unknown>
  15:     0x7fdb061bc09e - <unknown>
  16:     0x7fdb07759def - <unknown>
  17:     0x7fdb0775999f - <unknown>
  18:     0x7fdb077fb795 - <unknown>
  19:     0x7fdb34f9a609 - start_thread
  20:     0x7fdb350d4163 - clone
  21:                0x0 - <unknown>
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
//
File ~/.../lib/python3.9/site-packages/polars/internals/lazy_frame.py:423, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown)
    413     slice_pushdown = False
    415 ldf = self._ldf.optimization_toggle(
    416     type_coercion,
    417     predicate_pushdown,
   (...)
    421     slice_pushdown,
    422 )
--> 423 return pli.wrap_df(ldf.collect())

PanicException: index out of bounds: the len is 2 but the index is 3
```
Separating-out our code/data from the test and still triggering the error is proving tricky, but hopefully can put something together.

**Comment by alexander-beedie** [comment]
@ritchie46: Finally... managed to strip it down to the bare minimum; looks a little weird as a result, but there you go ;)

Does _not_ crash on windows; required running under linux to reproduce (I tested on an EC2 box). Looped the test 100,000 times on windows with no issue, but on linux it typically panics in the first few iterations, with the stack trace above.

**Reproducible test-case**

Setup...

```python
import polars as pl

df1 = pl.from_records( [('abc',1,5),('xyz',2,6)], columns=['colx','tmp','coly'], orient='row' ).lazy()
df2 = pl.from_records( [('abc',5,2),('xyz',6,3)], columns=['colx','tmp','coly'], orient='row' ).lazy()

def repro():
    return pl.concat([
        df1.select(
            [pl.col('colx'),pl.col('coly'),pl.lit('frame1').alias('tag')]
        ),
        df2.select(
            [pl.col('colx'),pl.col('tmp'),pl.col('coly')]
        ).select(
            [pl.col('colx'),pl.col('coly'),pl.lit('frame2').alias('tag')]
        )
    ]).collect()
```

...then just loop until failure:

```python
for n in range( 100 ):
    try:
        df = repro()
    except:
        print( f"Failed: loop {n}" )
        raise
```

**Comment by ritchie46** [comment]
Thanks a lot! I will fix this!

**Comment by ritchie46** [comment]
Have a workaround fix in #2892 (the PR is unrelated).

**Comment by alexander-beedie** [comment]
> Have a workaround fix in #2892 (the PR is unrelated).

Can confirm that 0.13.9 fixes the issue we saw with 0.13.8; I leave it to @SimonSchneider to confirm impact on the the original issue, after shamelessly semi-hijacking the thread!  ;)

**Comment by ritchie46** [comment]
> Can confirm that 0.13.9 fixes 

Please update to 0.3.10, I had to yank that release because we accidentally introduced a bug in aggregations.

**Comment by alexander-beedie** [comment]
> Please update to 0.3.10, I had to yank that release because we accidentally introduced a bug in aggregations.

Thx for the heads-up  ;)

**Comment by SimonSchneider** [comment]
Thanks,
I've been having a look and testing with the latest master build and the release build is working as expected 🎉 
However the debug build still panics on the debug assertion, @ritchie46 did you ever get around to adding a flag to toggle this behaviour until the root cause has been fixed?

Also I've assumed I should leave the closing of the issue up to you @ritchie46 ?

**Comment by SimonSchneider** [comment]
I saw that the feature flag was added yesterday, with the default being not to panic, thank you! 
I can confirm that debug builds also pass all tests now.

I'll leave the closing up to you as I guess there could be value on keeping this issue until root cause has been fixed.

**Comment by ritchie46** [comment]
> I saw that the feature flag was added yesterday, with the default being not to panic, thank you! I can confirm that debug builds also pass all tests now.
> 
> I'll leave the closing up to you as I guess there could be value on keeping this issue until root cause has been fixed.

Yes, I saw that I forgot a `debug_assertion`. I will keep this open so that I can fix the root issue.

**Comment by ritchie46** [comment]
I will close
