### ISSUE TITLE
`list` namespace add `square` and `extend_constant`

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#2810]
Where 

* `square` determines the maximum width and fills the smaller sublist with a value until they have the same width.
* `extend_constant` takes a constant and a `length` and extends the sublists.

**Comment by reswqa** [comment]
Hi @ritchie46, do we currently still plan to support these two operations? If so, I will start preparing for PR. 

> extend_constant takes a constant and a length

Does `constant` and `length` here refer to individual `AnyValue` and `usize` or both `Expr` (for example, based on two specific columns, this allows us to extend different values and sizes for each row, but the implementation can also become more complex).

**Comment by orlp** [comment]
`square` is handled by `pad` and `extend_constant` could be implemented automatically on the engine backend as a more efficient broadcasting implementation of `Expr.list.concat`.
