### ISSUE TITLE
Join even if type doesn't match

### ISSUE THREAD

**Issue by Gabriel-ROBIN** [pola-rs/polars#2815]
#### Describe your feature request

if I try to join two dataframes on a column with 2 differents types, for example left is Int32 and right is Int64, it fails. Which is understandable, but I was wondering if it was possible/desirable to upcast in this case the Int32 to Int64 on the fly. We can imagine to extend this behavior to other types like Float.

```
df32 = pl.DataFrame([
    pl.Series("col1", [1, 2], dtype=pl.Int32)
])

df64 = pl.DataFrame([
    pl.Series("col1", [1, 2, 3, 4], dtype=pl.Int64)
])
df32.join(df64, on = ['col1']) 
# fails with RuntimeError
```

**Comment by ritchie46** [comment]
I am not convinced of this one. To me it feels like a good safeguard against unexpected things. Now we do already some automatic coercions, so we could also include joins on this.

**Comment by ritchie46** [comment]
After some thought I also don't want to include this behavior. I consider it a good practice to be aware of your data types and this will help with that. Besides that you will now get an error if you made a mistake somewhere in your query.
