### ISSUE TITLE
Interacts with the HDFS file system 

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#2818]
#### Describe your feature request

Please describe the behavior you want and the motivation. Please also provide
examples of how polars would be used if your feature request were added.

If you're not sure what to write here, then try imagining what the ideal
documentation of your new feature would look like Then try to write it.

**Comment by alexander-beedie** [comment]
> Describe your feature request

@ztsweet: I think you might want to provide a little more information here... ;)

**Comment by ztsweet** [comment]
`pl.read_parquet()` will directly interacts with HDFS like
```
val result = spark.read.parquet('hdfs://name-node:8020/a/b')
```

**Comment by ghuls** [comment]
Install [ffspec](https://filesystem-spec.readthedocs.io/en/latest/). You can pass additional arguments to `pl.read_parquet` that will be passed to [fsspec.open](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=hdfs#fsspec.open):

```python
df = pl.read_parquet('hdfs://name-node:8020/a/b')
```

Or you could install pyarrow and ffspec and read the data with pyarrow in a pyarrow table and convert that one to a polars dataframe:
https://arrow.apache.org/docs/python/filesystems.html

**Comment by zundertj** [comment]
Closing this issue, as @ghuls 's answer is spot on. 

@ztsweet : if this does not sufficiently answer your request, please open a new issue..
