### ISSUE TITLE
Panic when select non-existing column

### ISSUE THREAD

**Issue by illumination-k** [pola-rs/polars#2828]
#### What language are you using?

**Python**

#### What version of polars are you using?

'0.13.8'

#### What operating system are you using polars on?

WSL2

#### What language version are you using

python 3.8

#### Describe your bug.

When selecting non-existing columns, panic occurs.

#### What are the steps to reproduce the behavior?

**Example**

```python
>>> import io
>>> import polars as pl
>>> csv = "a,b,c\n1,1,1"
>>> df = pl.read_csv(io.StringIO(csv))
>>> df
shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   │
└─────┴─────┴─────┘

>>> df.select("d")
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /github/workspace/polars/polars-lazy/src/logical_plan/aexpr.rs:157:52
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/illumination-k/.pyenv/versions/3.8.3/lib/python3.8/site-packages/polars/internals/frame.py", line 3994, in select
    self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)  # type: ignore
  File "/home/illumination-k/.pyenv/versions/3.8.3/lib/python3.8/site-packages/polars/internals/lazy_frame.py", line 608, in select
    return wrap_ldf(self._ldf.select(exprs))
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

#### What is the expected behavior?

Should return `PolarsError::NotFound`

**Comment by cbilot** [comment]
lol, I ran into this **exact** same problem yesterday, and it sent me on an hour-long goose chase looking for a `None`/`null` value somewhere in my data ... or an `unwrap` method.  (While refactoring code, I referred to a column that was dropped in a previous step.)

Thanks for submitting this.
