### ISSUE TITLE
No speedup from caching

### ISSUE THREAD

**Issue by NilsBarlaug** [pola-rs/polars#2842]
Hi, thank you for the great library. I really appreciate your work!

I might be misunderstanding this feature - so this is half bug report and half question :sweat_smile: 

#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.9

#### What operating system are you using polars on?

Ubuntu 20.04

#### What language version are you using
Python 3.8.10

#### Describe your bug.

`cache()` does not actually cache?

#### What are the steps to reproduce the behavior?

```python
import polars as pl
from time import time

df = pl.DataFrame({"foo": pl.repeat("bar", 10_000_000)})
cached = df.lazy().with_column(pl.col("foo").str.replace("a", "e")).cache()

start_time = time()
cached.collect()
print(time() - start_time)

start_time = time()
cached.collect()
print(time() - start_time)
```

This is only a minimal example, but I discovered it when using `scan_csv()`. I was not able to get any speedup on repeated computations regardless of setting `cache = True` or appending a `.cache()`.

#### What is the actual behavior?

```
0.3939228057861328
0.39186859130859375
```

#### What is the expected behavior?

I expect the second `collect()` to run significantly faster than the first. Or do I misunderstand what `cache()` is supposed to do?

**Comment by ritchie46** [comment]
The cache only is used within a single execution graph. This is for instance valuable when you do self joins. In that case a single execution is done until the cache node. In the cache node it is stored and then the right hand side of the join can just get the result from that cache node.

Here we see an example where the caching saves some work:
```python
not_cached = df.lazy().with_columns([pl.col("foo").str.replace("a", "e"), pl.arange(0, pl.count()).alias("idx")])
start_time = time()
not_cached.join(not_cached, how="left", on="idx").collect()
print(time() - start_time)


cached = not_cached.cache()
start_time = time()
cached.join(cached, how="left", on="idx").collect()
print(time() - start_time)

```
```
1.9622998237609863
1.3729286193847656
```


So basically if you do complicated queries, where parts of the subtree are reused you can throw in a few cache nodes.

**Comment by NilsBarlaug** [comment]
Aha, that makes sense! Thanks for explaining 🙂
