### ISSUE TITLE
pl.Series.hash does not work for list-columns

### ISSUE THREAD

**Issue by johanbog** [pola-rs/polars#2869]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.10

#### What operating system are you using polars on?

MacOS

#### What language version are you using

Python 3.9.10

#### Describe your bug.

Hashing a polars series does not work if the series is of type list.

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

```
import polars as pl

pl.Series("a", [[1,2]]).hash()
```

#### What is the actual behavior?

Does not give any output

#### What is the expected behavior?

Either gives a hash value for each row, or raises an error that it's not supported.

**Comment by ritchie46** [comment]
That's correct, `Series` cannot be hashed.

```
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: List(Int64)'
```

**Comment by thobai** [comment]
What's the best way to work around this? What I've done so far is

```
df.with_column(
    pl.col('listCol').map(lambda x: hash(str(x))).alias('ListHash')
)
```

Unfortunately, this is very slow. Is there any better way to achieve this?

**Comment by ritchie46** [comment]
From mobile, but something like this?

`pl.col(..).arr.sum().hash() + pl.col(..).arr.lengths().hash()` 

You can add more aggregates to reduce collision probability and maybe a smarter combination function.

**Comment by thobai** [comment]
Thanks for the very fast reply, @ritchie46! That's definitely much faster (1.5s vs ~10s on about 8 million rows). I'll have to check whether I get collision problems. Nevertheless, I was actually hoping for something that brings me into millisecond speed for this operation. Let me know, if you have any other idea for speeding this up. Doing stuff in Rust is certainly also an option, if that would help.

**Comment by ritchie46** [comment]
How large are your lists? It could be reasonable performance if your lists are large.

Another option is parralellizing it

`pl.col(..).arr.eval(pl.element().sum(), parallel=True)).hash() + pl.col(..).arr.lengths().hash()`

**Comment by ritchie46** [comment]
Or take the sum of hashes.

```python
pl.col(..).arr.eval(pl.element().hash().sum(), parallel=True))
```

**Comment by thobai** [comment]
Thanks for the additional ideas. For the 8 million rows, the parallel sum of hashes is slower. I couldn't get the has of the sum working as I'm getting the following compute error: `Appending categorical data can only be done if they are made under the same global string cache. Consider using a global string cache.` I could imagine that this runs faster as there is less to hash. In case you want to reproduce the error, here's a simplified version:

```
df = pl.DataFrame(
    {
        'str': ['A', 'B', 'A', 'B', 'C'],
        'group': [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col('str').cast(pl.Categorical))

dfGroups = df.groupby('group').agg([pl.col('str').list().alias('strList')])

dfGroups.with_column(
    (
        (pl.col('strList').arr.eval(pl.element().sum(), parallel=True)).hash()
    ).alias('strHash')
)

dfGroups.collect()
```

**Comment by thobai** [comment]
Ah, I see. Tried casting the column before but that didn't work as it's list type. Changed to cast every element and it works to get the sum. I can't hash that as it again produces a list, but the sum shouldn't need any hashing. Nonetheless, already on my small example I get a "hashing" conflict with that approach and it's the same speed as the other parallelization, so still slower than the first approach. So I'll stick to the first version.

For those stumbling over this thread, the "working" (with hash conflict) version of the code above is:
```
df = pl.DataFrame(
    {
        'str': ['A', 'B', 'A', 'B', 'C'],
        'group': [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col('str').cast(pl.Categorical))

dfGroups = df.groupby('group').agg([pl.col('str').list().alias('strList')])

dfGroups = dfGroups.with_column(
    (
        (pl.col('strList').arr.eval(pl.element().cast(pl.UInt32).sum(), parallel=True))
    ).alias('strHash')
)

dfGroups.collect()
```

**Comment by thobai** [comment]
Just came back to this to recognize that the proposed hashing cannot encompass the ordering of the elements in the list, which is essential for my use case. Do you have an idea how we could work around this? I switched to use `apply` for hashing, but performance penalty is too big to use that in production.

**Comment by cnpryer** [comment]
> Just came back to this to recognize that the proposed hashing cannot encompass the ordering of the elements in the list

Your use case seems really strange, but out of curiosity what if you just encode this? So encoding your lists as hashable data that embeds their order in their encoding?

**Comment by cbilot** [comment]
Would the following algorithm work for you?
```python3
df.groupby("group").agg(
    pl.col("str").cast(pl.Utf8).alias("strList")
).with_column(
        pl.col("strList")
        .arr.join("")
        .alias('joined')
).with_column(
    pl.col('joined').hash().alias('hashed')
).collect()
```
```
shape: (2, 4)
┌───────┬─────────────────┬────────┬──────────────────────┐
│ group ┆ strList         ┆ joined ┆ hashed               │
│ ---   ┆ ---             ┆ ---    ┆ ---                  │
│ i64   ┆ list[str]       ┆ str    ┆ u64                  │
╞═══════╪═════════════════╪════════╪══════════════════════╡
│ 1     ┆ ["A", "B", "B"] ┆ ABB    ┆ 3129781560150065787  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ ["A", "C"]      ┆ AC     ┆ 17194279383258192517 │
└───────┴─────────────────┴────────┴──────────────────────┘
```
This would recognize the ordering of the elements.  Not sure about the performance aspects, but probably better than anything involving an `apply` and Python bytecode.

**Comment by thobai** [comment]
@cbilot Thanks a lot. That works and seems to be equally fast as the previous approach. I think it's not yet ideal from the performance perspective, but good enough for now. Probably will need to revisit that at some time again.

One big drawback though is that I need to have the list column with elements of type String for other operations. I need to do computations on that list column that for example include checking the order of two elements or simply the presence of a specific element. Is there a way to get and save the categorical mapping before I cast them to `UInt64`? Then I could manually convert values that I'm searching for to `UInt64`?

I see that one way would be to do my own encoding - probably similar to what @cnpryer suggested, but it would be great if I could work with the out-of-the-box categoricals.

PS: The use case might be a bit niche, but not too strange. The list of Strings in my use case are essentially actions ordered by the time of their occurrence. I need to group cases with the same sequence of actions and for example filter for cases where one activity follows another.

**Comment by cnpryer** [comment]
Strange was a terrible word. Niche is better.

Where does the hashing become relevant?

**Comment by cnpryer** [comment]
Tbh I like cbilot's approach.

**Comment by cbilot** [comment]
> One big drawback though is that I need to have the list column with elements of type String for other operations.

I would test the performance both ways.  That is, benchmark the first algorithm (that creates the List[str] and hashes that column) versus the second one (that creates the list of equivalent categorical values as strings and then hashes that).  The first one has the side effect of creating a column that you need.

That said, if the second algorithm performs significantly faster, you can still create a strList column, independent of the hashing algorithm.  The casting of the Categorical str column to create the catList column doesn’t change the str column itself. It remains a column of type Categorical.

Indeed, the catList column is simply an intermediate column that can be dropped after the hashing is complete.  It’s purpose is merely to create a good/quick hash for each unique run of the str column.
