### ISSUE TITLE
Adding support `trim` in `str` namespace

### ISSUE THREAD

**Issue by illumination-k** [pola-rs/polars#2874]
#### Describe your feature request

In noisy data, we often do trimming of str. It would be nice to have functionality equivalent to or part of that implemented in [Rust's `String`](https://doc.rust-lang.org/std/string/struct.String.htm) (see following). `pandas` supports `trim (strip)`, `trim_start (lstrip)` and `trim_end (strip)`. Maybe we can do this by using `replace`, but constructing a sufficient regexp is pretty troublesome.

- trim
- trim_start
- trim_end
- trim_matches
- trim_start_matches
- trim_end_matches

**Comment by ritchie46** [comment]
Polars has them under a different name:

* strip
* rstrip
* lstrip

We don't have a  `trim_matches`. What does this do?

**Comment by illumination-k** [comment]
Oh, great! I missed it. In `Utf8Chunked`, do you recommend to use apply directly?

`trim_matches` supports trimming all prefixes and suffixes that match a pattern repeatedly.

Citing [rust document examples](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_right_matches),

```rust
assert_eq!("11foo1bar11".trim_matches('1'), "foo1bar");
assert_eq!("123foo1bar123".trim_matches(char::is_numeric), "foo1bar");

let x: &[_] = &['1', '2'];
assert_eq!("12foo1bar12".trim_matches(x), "foo1bar");
assert_eq!("1foo1barXX".trim_matches(|c| c == '1' || c == 'X'), "foo1bar");
```

**Comment by ghuls** [comment]
BTW, `strip` in python does not strip exact strings, but removes each character it finds from start and end.
```python
In [11]: s = "AA_BB_CC_DD"

In [12]: s.strip("D")
Out[12]: 'AA_BB_CC_'

In [13]: s.strip("DC")
Out[13]: 'AA_BB_CC_'

In [14]: s.strip("DC_")
Out[14]: 'AA_BB'
```

**Comment by ghuls** [comment]
Polars *strip functions don't support providing a user defined string it seems.

**Comment by ritchie46** [comment]
> Oh, great! I missed it. In Utf8Chunked, do you recommend to use apply directly?

Normally I would. Only now you know you already have an upper bound on the needed heap allocation. So you can use `get_values_size` (this gives you the size to allocate in bytes). Then you can use `Utf8Array::with_capacities` to allocate the upper bound.

I don't think this logic should be in `polars-core`. The compile times on core are to straining, so for now it can be  in the `dsl::string` namespace in `polars-lazy`.

Eventually I want to create a `polars-string` crate to split this logic up.

**Comment by illumination-k** [comment]
> Eventually I want to create a polars-string crate to split this logic up.
I agree. It is rational because there is much string-specific logic. 

I will use custom rust functions just for me until splitting string-logic of `polars-core` into `polars-string`.

**Comment by stinodego** [comment]
As Ritchie mentioned, all the string functions mentioned in this issue are available through `strip_chars`.
