### ISSUE TITLE
n_unique includes nulls and NaNs

### ISSUE THREAD

**Issue by johanbog** [pola-rs/polars#2876]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.10

#### What operating system are you using polars on?

MacOS

#### What language version are you using
python 3.9

#### Describe your bug.

pl.Series.n_unique includes both nulls and Nans in the count. I think it's more intuitive that it only includes unique **values**, whereas nans and nulls can be argued to not be values at all.

I understand that this behavior might be intentional, as `.unique()` and `.n_unique` should give equivalent results, which pandas does not (pandas includes nans in .unique, but not in n_unique). In this case though, it would be great if the documentation on n_unique could reflect this.

#### What are the steps to reproduce the behavior?

```
import polars as pl
import numpy as np

pl.Series([1., np.NaN, np.NaN, None, None]).n_unique()
```

#### What is the expected behavior?

Output is 3, expected behaviour (and pandas' behavior) is 1.

**Comment by ritchie46** [comment]
If anything, I think that pandas is incorrect here. 

IMO `.unique()` and `.n_unique` should never return a different count. That doesn't make sense.

If you don't want to include them in your count, you can, but you just have to be explicit:

```python
a = pl.Series([1., np.NaN, np.NaN, None, None])
a.filter(a.is_not_null() & a.is_not_nan()).n_unique()
```
