### ISSUE TITLE
Selecting no columns loses height information

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#2885]
After all kinds of column operations (`select`, `drop`, `with_column`, etc.), the `height` of the table is _typically_ unchanged. I say typically because the one time that the height can be changed from such operations is if any step happens to result in a table with no columns. At that point, all the rows are lost. For example, consider the following code:

```python
import polars as pl

df = pl.DataFrame(dict(x=[1,2,3], y=["a","b","c"], z=[True,False,True]))

select_columns = []

df2 = df.select(select_columns).with_column(pl.arange(0, pl.count()).alias('index'))

len(df2['index'])  # This is always 3 except when selecting no columns, and then it is 0
```

This operation always results in a table with the same number of rows as when it started, unless `select_columns` is empty, and then it is empty.

I am not entirely sure if qualifies as a bug report or a feature request. I am guessing it is an edge case that is undesirable, but intentionally not handled at the moment.

**Comment by ritchie46** [comment]
Well when you `df.select([])` you create a new `DataFrame` without any columns. No columns is no rows.

**Comment by drhagen** [comment]
> No columns is no rows.

Ok, so this is the desirable behavior? You wouldn't want a PR that made it possible to create a `DataFrame` with shape `(n,0)`?

**Comment by ritchie46** [comment]
> You wouldn't want a PR that made it possible to create a DataFrame with shape (n,0)?

I don't know what you are proposing. A DataFrame is `Vec<Series>`. If you select no columns you end up with an empty `Vec<>`? The shape reflects the physical memory layout. In polars it is impossible to have rows without any columns.

**Comment by drhagen** [comment]
Implementing this at the Rust level would require storing a `height` attribute on the `DataFrame` object. This would be the canonical height of the data frame instead of `columns[0].len()`. Column operations pass the height through unchanged, but row operations would have to be updated to properly update the height when there were no columns.

**Comment by ritchie46** [comment]
> This may be more a bigger change than you want to make.

Besides that,  I also don't want it for a semantic reason. As polars should be thought of as columnar memory. When you select no columns you create an empty DataFrame. IMO there should only be one sort of emtpy DataFrame.

There is of course the other case where you have `n` columns and no rows. But that is different as we still have a schema. A schema could have no rows. But selecting `[]` is really selecting nothing, there is no schema, no data, empty.

**Comment by ritchie46** [comment]
You're welcome! :)
