### ISSUE TITLE
String strip or any Lambda on multiple columns

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2886]
Is it possible to apply string strip to multiple columns at one shot ? We have huge dataframe with 250mil rows and 100 columns. Applying lambda on each column takes around 2 minutes. Or better, if we can apply during read_csv

**Comment by ritchie46** [comment]
This applies strip to all `Utf8` columns in parallel.

```python
df.select(pl.col(pl.Utf8).str.strip())
```

Any reason why you used a lambda?

**Comment by NarayanB** [comment]
Nice, is it in place or returns a new df ?

**Comment by ritchie46** [comment]
It returns a new `DataFrame`.

**Comment by NarayanB** [comment]
it took less than a minute to do trim on 250 million rows and 70 columns. Amazing stuff
