### ISSUE TITLE
to_csv not escaping strings properly

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#2892]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.10

#### What operating system are you using polars on?

mac 12.1 (apple chip)

#### What language version are you using
3.8.9

#### Describe your bug.

```py
df = pl.Dataframe({
  "company_name": ['Acme co., Ltd.'],
  "company_id": [1]
}).to_csv("out.csv")
```

#### Actual
```csv
company_name,company_id
"Acme Co., Ltd.,1
```

#### Expected

```csv
company_name,company_id
"Acme Co., Ltd.",1
```

#### Additional Detail

Using `to_pandas` first gives the desired output

```py
df = pl.Dataframe({
  "company_name": ['Acme co., Ltd.'],
  "company_id": [1]
}).to_pandas().to_csv("out.csv")
```

**Comment by ritchie46** [comment]
See: https://github.com/jorgecarleitao/arrow2/pull/916
