### ISSUE TITLE
window expression throw error in version 0.13.11

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2896]
Hi;

When I upgrade polars from 0.12 to 0.13.11, existing code threw error. I'm sharing my code below. Error is coming from window expression. 

```
self.genelStatsPuanUlke.filter(pl.col("tip")=="source")
                           .groupby([pl.col("country"),pl.col("segment_title")]) \
                           .agg([ pl.col("review_count").sum().alias("Yorum_Sayisi"), 
                                      ( (pl.col("review_count")*pl.col("ortalama_puan")).sum() / pl.col("review_count").sum()).alias("puan") ])  \
                           .sort(["country","Yorum_Sayisi"],reverse=[True,True]).with_column(pl.col("puan").round(2)) \
                          .with_column( pl.col("Yorum_Sayisi").cumcount().over(pl.col("country")).flatten().alias("siraNo") )
```
I copied error message coming from expression above.

> Traceback (most recent call last):
>   File "<string>", line 5, in <module>
>   File "/home/hakan/.conda/envs/opencv/lib/python3.7/site-packages/polars/internals/frame.py", line 3390, in with_column
>     return self.with_columns([column])
>   File "/home/hakan/.conda/envs/opencv/lib/python3.7/site-packages/polars/internals/frame.py", line 4132, in with_columns
>     .collect(no_optimization=True, string_cache=False)
>   File "/home/hakan/.conda/envs/opencv/lib/python3.7/site-packages/polars/internals/lazy_frame.py", line 472, in collect
>     return self._dataframe_class._from_pydf(ldf.collect())
> exceptions.ComputeError: This operation is likely not what you want (you may need '.list()'). Please open an issue if you really want to do this

If I change the last part of code (with_column expression) like below, both of them are working.

`.with_column( pl.col("Yorum_Sayisi").cumcount().over(pl.col("country")).alias("siraNo") )`

`.with_column( pl.col("Yorum_Sayisi").cumcount().list().over(pl.col("country")).flatten().alias("siraNo") )`

I wonder whether this behaviour intentionally changed or  it is a bug. I call on your help to clarify this before I start to change my existing codes.

Thanks.

**Comment by ritchie46** [comment]
That's correct. The rules for windows expressions have changed. They work now without the need for a flatten. Unless you specifically aggregate to a list.

**Comment by hakantekbas** [comment]
Thanks @ritchie46 . I'm closing issue.
