### ISSUE TITLE
Random behaviour when running `.unique().drop_nulls()`

### ISSUE THREAD

**Issue by johanbog** [pola-rs/polars#2898]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.11

#### What operating system are you using polars on?

macOS

#### What language version are you using

python 3.9

#### Describe your bug.

Running `df.with_column(pl.col("a").unique().drop_nulls()` when the column "a" contains null values has random behavior.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame({"a": [1, None]})
df.with_column(pl.col("a").unique().drop_nulls().alias("new_column"))[
    "new_column"
]
```

#### What is the actual behavior?

The output alternates and gives on average 50/50 either [1, 1] or [null, null]

```python
In [41]: df.with_column(pl.col('a').unique().drop_nulls().alias('new_column'))['new_column']
Out[41]:
shape: (2,)
Series: 'new_column' [i64]
[
	1
	1
]

In [42]: df.with_column(pl.col('a').unique().drop_nulls().alias('new_column'))['new_column']
Out[42]:
shape: (2,)
Series: 'new_column' [i64]
[
	null
	null
]
```

#### What is the expected behavior?

`.unique()` should not change anything, as the values are unique already, in which case `.drop_nulls()` should drop the null value and just be left with `1`, i.e. giving a result of [1, 1], as far as I understand it.

For reference, both

```python
df.with_column(pl.col('a').drop_nulls().alias('new_column'))['new_column']
```
and 

```python
df['a'].drop_nulls().alias('new_column')['new_column']
```
gives correct ([1, 1]) results.

**Comment by ritchie46** [comment]
Thanks, I will look into it.
