### ISSUE TITLE
Seg fault when exploding empty lists

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#2903]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.11

#### What operating system are you using polars on?

Linux

#### What language version are you using

3.10.2

#### Describe your bug.

Using `explode` on empty lists causes seg fault when other columns contain strings.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame(dict(x=['a','a','b','b'], y=[1,1,2,2])).groupby('x').agg(pl.col('y').take([]))

# shape: (2, 2)
# ┌─────┬────────────┐
# │ x   ┆ y          │
# │ --- ┆ ---        │
# │ str ┆ list [i64] │
# ╞═════╪════════════╡
# │ a   ┆ []         │
# ├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ b   ┆ []         │
# └─────┴────────────┘

df.explode('y')
# memory allocation of 18446744073709551614 bytes failed
# Aborted (core dumped)
```

It appears to be important that `x` is `str`.

#### What is the expected behavior?

I expected it to explode, but not quite like that.

**Comment by ritchie46** [comment]
Thanks, I will fix it.
