### ISSUE TITLE
`Series::series_equal` behavior changed between polars 0.19 & polars 0.20

### ISSUE THREAD

**Issue by zirconium-n** [pola-rs/polars#2906]
#### What language are you using?

**Rust**

#### Which feature gates did you use?

`default-features = false`

#### What version of polars are you using?

0.19 => 0.20

#### What operating system are you using polars on?

WSL Ubuntu 20.04

#### What language version are you using

rustc 1.60.0-nightly (bd3cb5256 2022-01-16)
binary: rustc
commit-hash: bd3cb52565faab2755ff1bdb54d88bc91f47b4b9
commit-date: 2022-01-16
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0

#### Describe your bug.

`Series::series_equal` behavior changed between polars 0.19 & polars 0.20.

#### What are the steps to reproduce the behavior?

**Example**
```
# Cargo.toml

[dependencies]
polars19 = { package = "polars", version = "0.19", default-features = false }
polars20 = { package = "polars", version = "0.20", default-features = false }
```

```rust
fn main() {
    test_v19();
    test_v20();
}

fn test_v19() {
    use polars19::prelude::*;
    let int_ser = Series::new("", [0u64, 1u64]);
    let float_ser = Series::new("", [0f64, 1f64]);
    // true
    println!("polars19: {}", int_ser.series_equal(&float_ser));
}

fn test_v20() {
    use polars20::prelude::*;
    let int_ser = Series::new("", [0u64, 1u64]);
    let float_ser = Series::new("", [0f64, 1f64]);
    // false
    println!("polars20: {}", int_ser.series_equal(&float_ser));
}
```

Output:
```
polars19: true
polars20: false
```

#### What is the expected behavior?

What do you think polars should have done?

Confirm whether it's an expected behavior or an accidental break.

**Comment by ritchie46** [comment]
Yep, that is expected.
