### ISSUE TITLE
faster slice for a DataFrame

### ISSUE THREAD

**Issue by longilacus** [pola-rs/polars#2911]
In a realtime scenario, I create a DataFrame to store incoming data. When I need to get serveral rows into calculation in realtime, I use `DataFrame.slice()` to get a slice of the original DataFrame.Could we have a faster slice like `get_unckecked()` in `ChunkedArray`?

**Comment by ritchie46** [comment]
Do you have any benchmarks/comparisons? Is the slice operation slow at the moment?

**Comment by longilacus** [comment]
With a DataFrame which size is 41000000 x 12,  I did about 1800000 times slice (it seems length of slice is no matter), it cost 4500ms. It's very fast really. Just get the thought when I use `get_unckecked()` beats `get()`, so wondering if there is some way to make faster like that.

By the way,what exactly does `amortized` mean in Polars, I see many method has this name.

Thanks!

**Comment by ritchie46** [comment]
I don't really think there is much to win by reducing a bound check on a slice call. The majority of the time goes to indirection of the `Vec<Arc<Arc<>>` and the null count.

**Comment by longilacus** [comment]
Understand, thanks for reply.
