### ISSUE TITLE
how to filter  and calc growth over the same period and 

### ISSUE THREAD

**Issue by hengaini2055** [pola-rs/polars#2917]
I have a dataframe such as follows:
```
import polars as pl
df = pl.DataFrame(
    {
        "Period": ["2021-1-1", "2021-1-1", "2021-2-1", "2021-2-1","2021-2-1"],
        "deptname": ["one", "two", "one", "two", "three"],
        "value": [100, 200, 110, 230, 1000],
    }
)
```
I want to get the dataset that group by deptname and filtered (Period = "2021-2-1"): sum(Value) as thisPeriod, Growth over the same Period(Month), growth rate over the same period(Month). The dataframe should be：

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)
