### ISSUE TITLE
Have `SerWriter::new` take the writer by mutable reference instead of by value

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#2921]
#### Describe your feature request

`SerWriter::new`, as used by e.g., `CsvWriter` and `JsonWriter`, takes the buffer by value. This means that once you construct the `SerWriter` you can no longer use the writer. This is problematic if you want to write to an in-memory buffer and then read the values back out, as the buffer will have been consumed.

Ideally `SerWriter::new` would take a `&mut Writer`, which would allow you to continue to use the writer after writing the CSV/JSON/whatever data to it.

**Comment by ritchie46** [comment]
Makes sense. Could you make a PR for that change?

**Comment by rben01** [comment]
Thanks, didn't realize &mut W was Write whenever W was
