### ISSUE TITLE
set_tbl_cols not working

### ISSUE THREAD

**Issue by keiv-fly** [pola-rs/polars#2929]
#### What language are you using?

Python
#### What version of polars are you using?
0.13.12

#### What operating system are you using polars on?
Windows 10

#### What language version are you using
python 3.9.4

#### Describe your bug.

set_tbl_cols is ignored and the columns are truncated.

#### What are the steps to reproduce the behavior?

```
>>> import polars as pl
>>> pl.cfg.Config.set_tbl_cols = 1000
>>> temp_df = pl.DataFrame({str(i):[i] for i in range(100)})
>>> temp_df
shape: (1, 100)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ 0   ┆ 1   ┆ 2   ┆ 3   ┆ ... ┆ 96  ┆ 97  ┆ 98  ┆ 99  │
│ --- ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆     ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 1   ┆ 2   ┆ 3   ┆ ... ┆ 96  ┆ 97  ┆ 98  ┆ 99  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘
>>>
```
#### What is the actual behavior?

Columns between 3 and 96 are cut.

#### What is the expected behavior?

See all 100 columns in the text output

**Comment by ghuls** [comment]
You overwrote the method `pl.cfg.Config.set_tbl_cols` with `1000`.

```python
pl.cfg.Config.set_tbl_cols(1000)
```

**Comment by keiv-fly** [comment]
It works. I was stupid. I will add the example to the documentation.

**Comment by ritchie46** [comment]
👍
