### ISSUE TITLE
Error parsing Int64

### ISSUE THREAD

**Issue by tonyabracadabra** [pola-rs/polars#2951]
I am getting the following error when reading a csv file that works fine in pandas

```
exceptions.ComputeError: Could not parse  77516 as dtype Int64 at column 3.
                                            The total offset in the file is 14 bytes.

                                            Consider running the parser `with_ignore_parser_errors=true`
                                            or consider adding  77516 to the `null_values` list.
```

I am not getting why it is raising the error because 77516 looks perfectly fine to be parsed into int64

This is what I got using pandas

```
>>> df['fnlwgt']
0         77516
1         83311
2        215646
3        234721
4        338409
          ...
32556    257302
32557    154374
32558    151910
32559    201490
32560    287927
Name: fnlwgt, Length: 32561, dtype: int64
```

This is the link for the data I used https://datahub.io/machine-learning/adult

**Comment by ritchie46** [comment]
Can it been that the number has leading whitespace?

**Comment by tonyabracadabra** [comment]
> Can it been that the number has leading whitespace?

ha I further checked looks like this is the case, will this be handled by polars? How did it correctly infer the type if white space were the issue

**Comment by ritchie46** [comment]
> ha I further checked looks like this is the case, will this be handled by polars? How did it correctly infer the type if white space were the issue

I believe I have removed that a while a go. I will reintroduce it.
