### ISSUE TITLE
Option to specify the quote charater in write_csv()

### ISSUE THREAD

**Issue by Joonhwi** [pola-rs/polars#2955]
Hi, I was trying to write a csv file using to_csv() or write_csv() method. My data contains character columns with lots of commas, and I would like to still use the comma separator. Would you please consider including an option to turn on/off quoting and specifying the quote characters in to_csv() method?

Many thanks!

**Comment by ritchie46** [comment]
You can still use comma's right? It should be quoted automatically.

**Comment by Joonhwi** [comment]
Specifying separators is not an issue here and separators work perfectly. The issue here is to manually specify the character for quotes as "\"". And it does not quote automatically by the way.
