### ISSUE TITLE
Unexpected behavior after combine Expr.unique_counts() and Expr.sum()

### ISSUE THREAD

**Issue by sergii-batishchev** [pola-rs/polars#2961]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.14

#### What operating system are you using polars on?

Ubuntu 20.04

#### What language version are you using
python 3.8

#### Describe your bug.

If combine .unique_counts() or .unique() expressions with len() sum() or others, there are unexpected results.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': ['1', '1', '2', '3', '4', '3', '5'],
             })

df.groupby(['group']).agg(
    [
        pl.col('id').list().alias('list_agg'),
        (pl.col('id').unique_counts() / pl.col('id').len()).alias('unique_counts_share'),
        (pl.col('id').unique_counts() / pl.col('id').len()).sum().alias('unique_counts_sum'),
        pl.col('id').unique().alias('unique'),
        pl.col('id').unique().len().alias('unique_len')
    ]
    
)
```

#### What is the actual behavior?

group | list_agg | unique_counts_share | unique_counts_sum | unique | unique_len
-- | -- | -- | -- | -- | --
str | list | list | f64 | list | u32
"A" | ["1", "1", "2"] | [0.666667, 0.333333] | **1.5** | ["1", "2"] | **3**
"B" | ["3", "4", ... "5"] | [0.5, 0.25, 0.25] | **0.5** | ["3", "5", "4"] | **4**

#### What is the expected behavior?

group | list_agg | unique_counts_share | unique_counts_sum | unique | unique_len
-- | -- | -- | -- | -- | --
str | list | list | f64 | list | u32
"A" | ["1", "1", "2"] | [0.666667, 0.333333] | **1** | ["1", "2"] | **2**
"B" | ["3", "4", ... "5"] | [0.5, 0.25, 0.25] | **1** | ["3", "5", "4"] | **3**

**Comment by ritchie46** [comment]
Thanks, I will fix this. :+1:

**Comment by sergii-batishchev** [comment]
@ritchie46, thanks for quick fix! But seems there are still problems with unique and log() in 0.13.15.
```python
import polars as pl
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 1, 2, 3, 4, 3, 5],
             })

df.groupby(['group']).agg(
    [
        pl.col('id').list().alias('list_agg'),
        pl.col('id').log().alias('log'),
        (pl.col('id').unique_counts() / pl.col('id').len()).log().alias('unique_counts_log')
    ]
    
)
PanicException: range end index 7 out of range for slice of length 5

**Comment by ritchie46** [comment]
Thanks. Can you make a new issue for this one?
