### ISSUE TITLE
(Feature Request) Ability to iterate through groups, similar to pandas

### ISSUE THREAD

**Issue by vstolin** [pola-rs/polars#2965]
I couldn’t find a way to iterate through groups, the way one can in pandas (https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#iterating-through-groups ). While LazyGroupBy.apply does let you apply some function to each frame in the group that returns another frame, in some cases one needs the ability just to iterate over the materialized frames (and their keys). This is useful when using polars to do data pre-processing and splitting logic, before sending the frames outside of the polars ecosystem to custom logic (such as model training) that expects arrow tables or numpy arrays.

**Comment by ritchie46** [comment]
This is already supported:

```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': ['1', '1', '2', '3', '4', '3', '5'],
})

for g in df.groupby("group"):
    print(g)
```

```
shape: (4, 2)
┌───────┬─────┐
│ group ┆ id  │
│ ---   ┆ --- │
│ str   ┆ str │
╞═══════╪═════╡
│ B     ┆ 3   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ B     ┆ 4   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ B     ┆ 3   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ B     ┆ 5   │
└───────┴─────┘
shape: (3, 2)
┌───────┬─────┐
│ group ┆ id  │
│ ---   ┆ --- │
│ str   ┆ str │
╞═══════╪═════╡
│ A     ┆ 1   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ A     ┆ 1   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ A     ┆ 2   │
└───────┴─────┘

```

**Comment by vstolin** [comment]
Thank you for the response, sorry for the delay in getting back to you, but I have three follow up questions:
 
1. I get message "UserWarning: accessing GroupBy by index is deprecated, consider using the `.agg` method"
2. The return order of groups is not guaranteed, is it possible to get groups in the original order of the frame?
3. Is it possible to get the value for each group in addition to the group?
 
Thank you!

**Comment by ritchie46** [comment]
> I get message "UserWarning: accessing GroupBy by index is deprecated, consider using the .agg method"

You asked for an `iterator` not something you can take by index. An `__iter__` works by calling `next()` iteratively. That's what is supported.

> The return order of groups is not guaranteed, is it possible to get groups in the original order of the frame?

A groupby has a `maintain_order` kwargs. It is well documented.

> Is it possible to get the value for each group in addition to the group?

Of course? Can you elaborate a bit on your question?

Regarding this. Can you use stackoverflow to ask your questions. This saves me from repeating my answers and makes the questions discoverable by other users with the same question?
Thanks!
