### ISSUE TITLE
 (Performance Improvement) join_asof by 2 columns is very slow

### ISSUE THREAD

**Issue by vstolin** [pola-rs/polars#2966]
Python
0.13.14
Cento OS 7
python 3.8

I have found much better performance when using join_asof on two columns by manually splitting the dataframe into sub-frames based on the lower-cardinality column, doing an asof_join on the remaining column for each pair of sub-frames, and then re-assembling everything (i.e. 1.7 seconds vs 2 minutes in my benchmark). Here is the sample code that generates the data for this example:

Please see the example below:

import random
import string
 
import polars as ps
 
from datetime import datetime
from polars import DataFrame, Series
 
key2 = ('A', 'B', 'C', 'D', 'E', 'F', 'G')
 
ts1 = ps.date_range(name='dt', low=datetime(2022, 3, 7, 0, 0, 0), high=datetime(2022, 3, 8, 0, 0, 0), interval='20000us')
ts2 = ps.date_range(name='dt', low=datetime(2022, 3, 7, 0, 0, 0), high=datetime(2022, 3, 8, 0, 0, 0), interval='4000us')
df1 = DataFrame([
    ts1,
    Series(name='key1', values=[random.choice(string.ascii_uppercase) for i in range (ts1.len())]),
    Series(name='key2', values=[random.choice(key2) for i in range (ts1.len())])
]).sort('dt')
df2 = DataFrame([
    ts2,
    Series(name='key1', values=[random.choice(string.ascii_uppercase) for i in range (ts2.len())]),
    Series(name='key2', values=[random.choice(key2) for i in range (ts2.len())]),
    Series(name='val', values=[random.randint(1, 1000) for i in range (ts2.len())])
]).sort('dt')
 
df1.join_asof(df2, on='dt', strategy='backward', by=['key1', 'key2'])

**Comment by ritchie46** [comment]
This is not a bug. This is known. We will improve the performance of multiple column grouped asof joins. 
It is still work in progress.
