### ISSUE TITLE
(Question) Groupby_rolling within groups

### ISSUE THREAD

**Issue by vstolin** [pola-rs/polars#2967]
Python
0.13.14
Cento OS 7
python 3.8

I want to do groupby_rolling within groups (by key) and while this doesn’t seem explicitly possible from the API, I have confirmed that the following workaround works: sort by the key(s) and then dates, and then take advantage of the fact that groupby_rolling will start new groups when the keys change. I want to understand if this is the intended way to solve this problem (i.e. a feature vs a side effect), or if it may break going forward. Please advise.

**Comment by ritchie46** [comment]
No, that is intended behavior. You might also be interested in `groupby_dynamic`.
