### ISSUE TITLE
Low Speed and High Memory Usage with Pivot

### ISSUE THREAD

**Issue by LVG77** [pola-rs/polars#2968]
#### What language are you using?

Python

#### What version of polars are you using?

polars-0.13.14

#### What operating system are you using polars on?

Linux

#### What language version are you using
Python 3.7.12

#### Describe your bug.

I noticed a very high memory usage while running the `pivot` method on a moderate size dataframe (10m rows).
I constructed this example to try to illustrate the issue. I ran the same code snipped with both polars and pandas. Pandas' run was faster and consumed 8x less memory. 

**Polars**
![image](https://user-images.githubusercontent.com/16968156/160010579-97121ffe-8a74-4c61-b91f-1825e7989312.png)
![image](https://user-images.githubusercontent.com/16968156/160010633-9f1dd6e2-1d7f-42ad-9cba-df839d1af9bc.png)

**Pandas**
![image](https://user-images.githubusercontent.com/16968156/160010678-4164fc1f-d529-4b64-91d7-45a270c8225e.png)
![image](https://user-images.githubusercontent.com/16968156/160010694-ede3de2e-f8c9-4016-ac43-a338f14dccc6.png)

#### What are the steps to reproduce the behavior?
Here is the code to reproduce the examplesI

```python
from itertools import product
import random
import polars as pl

row_id = range(3_000_000)
types =  product(['t1', 't2', 't3'], row_id)
types = list(zip(*types))
pl_df = pl.DataFrame({'row_id': range(len(types[0])), 'types': types[0], 'values':[random.randint(0, 1_000_000) for _ in range(len(types[0]))]})
pl_df_long = pl_df.pivot(values='values', index='row_id', columns='types')
```

```python
from itertools import product
import random
import pandas as pd

row_id = range(3_000_000)
types =  product(['t1', 't2', 't3'], row_id)
types = list(zip(*types))
pd_df = pd.DataFrame({'row_id': range(len(types[0])), 'types': types[0], 'values':[random.randint(0, 1_000_000) for _ in range(len(types[0]))]})
pd_df_long = pd_df.pivot(values='values', index='row_id', columns='types')
```

Thank you for building and maintaining this great library!
Best regards,
LG

**Comment by ritchie46** [comment]
Thanks, I will investigate this a bit later. The pivot operation is one of the hardest for our memory layout and we expect to be slower here than pandas on a certain size.

However, I know we did better than this in the past, so we need to redesign
