### ISSUE TITLE
sign method for polars.Series

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2975]
#### Describe your feature request

Please describe the behavior you want and the motivation. Please also provide
examples of how polars would be used if your feature request were added.

If you're not sure what to write here, then try imagining what the ideal
documentation of your new feature would look like Then try to write it.
```
like np.sign ufunc

series.sign()
```

**Comment by ritchie46** [comment]
`np.sign` is a ufunc, so we support it:

```python
np.sign(pl.Series([10, -1, None]))
```
