### ISSUE TITLE
Add `pl.duration` similar to `pl.datetime` that can create from different temporal expressions

### ISSUE THREAD

**Issue by dafardevloper** [pola-rs/polars#2976]
I recently needed to add days to date, but could not find a way to do so, 

converted dataframe to pandas did .timedelta and returned back to polars,

Please make a native method for the same.

**Comment by ritchie46** [comment]
This is supported:

```python
import polars as pl
from datetime import date, timedelta

df = pl.DataFrame({
    "date": [date(2021, 1, 1), date(2021, 1, 2)]
})

df.with_columns([
    (pl.col("date") + timedelta(days=5)).alias("date + 5 days")
])
```

```
shape: (2, 2)
┌────────────┬─────────────────────┐
│ date       ┆ date + 5 days       │
│ ---        ┆ ---                 │
│ date       ┆ datetime[ns]        │
╞════════════╪═════════════════════╡
│ 2021-01-01 ┆ 2021-01-06 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-01-02 ┆ 2021-01-07 00:00:00 │
└────────────┴─────────────────────┘

```

**Comment by dafardevloper** [comment]
import polars as pl
from polars import col
from datetime import datetime, date, timedelta

incoming_stock = (
    incoming_stock.with_columns(
        [
            datetime.today() + timedelta(days=(col("Lead_days"))).alias("incoming_date")
        ])

Error:[unsupported type for timedelta days component: Expr]

**Comment by ritchie46** [comment]
You cannot pass a polars expression to `pythons timedelta` function? Python does not know anything about polars.


You can create a duration in one of the following time units: `ms, us, ns`.

```python
import polars as pl
from polars import col
from datetime import datetime, date, timedelta

df = pl.DataFrame({
    "days": [1, 2]
})

df.with_columns(
    [
        (datetime.today() + (pl.col("days") * 3600 * 1000 * 24).cast(pl.Duration).dt.and_time_unit("ms")).alias("incoming_date")
    ]
)
```

**Comment by dafardevloper** [comment]
Thanks for the solution,

But my friend, do you really think this is a natural way of thinking and solving this problem?

Please consider putting these calculations in the backend and exposing cleaner API.

It is the little things that make the difference. 

Please keep this request open and update at your own pace no hurry mate
