### ISSUE TITLE
Allow serialization of `LazyFrame`

### ISSUE THREAD

**Issue by mainrs** [pola-rs/polars#2979]
https://stackoverflow.com/questions/71590513/how-can-i-share-a-lazy-dataframe-between-different-runtimes

__tl;dr:__ Is it possible to share a `LazyFrame` between Rust and Python without unnecessary serialization? For example do some renames on the Rust side, pass it along to Python so that one can further do calculations there and finally collect the result on the Rust side?

```
Rust: agg -> Rust: calculate new column -> Python: groupby -> Rust: count results
```

**Comment by ritchie46** [comment]
I saw the question, I did not answer it because I didn't have a clear answer yet. Need some more info. 

Do you mean sharing the lazy computation graph, or sharing the `DataFrame` memory?

Dataframes can be shared within the same process using arrow's C ffi. In this example we go for instance from `python polars` to `rust polars` via the arrow c ffi. 

This is mostly zero copy.

**Comment by mainrs** [comment]
I am only using  `LazyFrame` for now. So in my case, it would be actually sharing the computation graph. So the graph can be manipulated in both runtimes, Rust and Python. And at the end, the result gets calculated in Rust. 

To give more context: It is a node-based editor for working with data. And I was hoping that I could embed some kind of scripting language to make it easier to write custom nodes if necessary. But I do provide nodes that are implemented in Rust.

**Comment by ritchie46** [comment]
Hmm.. we would need to serde the graph. Which can be problematic as we use quite some generics.

I don't know how serializable that is.

> 

Offtopic for this question: If using LazyFrame and for example scan_parquet, does it then only scan for columns and data types to make it possible to write transformations?

Yes every scan only gets the schema from disk and the delays reading upon collection. At that time we can also push down filters and projections to the scan level.

**Comment by universalmind303** [comment]
been thinking about this...

> we would need to serde the graph. Which can be problematic as we use quite some generics.

is that to say that it would be _impossible_ to serde the logical plan, or just difficult?

**Comment by mainrs** [comment]
> Hmm.. we would need to serde the graph. Which can be problematic as we use quite some generics.

I've taken a look at the logical plan module inside of `polars-lazy` and couldn't find generic usage. Maybe I am missing something or looking at the wrong place.

**Comment by ritchie46** [comment]
> > we would need to serde the graph. Which can be problematic as we use quite some generics.
> 
> is that to say that it would be _impossible_ to serde the logical plan, or just difficult?

I would no say impossible. But yeah definitely difficult. We, for instance push python lambda functions into the logical plan. 
And most expressions are also create by an `Arc<dyn Fn(Series) -> Series>`.

If we try this, I think we should add a `try_serde` that is fallible. And incrementally see which expression could be serialized or not.

**Comment by ritchie46** [comment]
FYI we are working on making most of Polars logical plan serializable.

**Comment by mainrs** [comment]
> FYI we are working on making most of Polars logical plan serializable.

Thanks for letting me know! Are there plans to support lambda functions in some form? For example defining the lambda in Python and using it inside the logical plan? 

I think the only way to make this work would be to have some way to pass around already computed data between existing runtimes. And have the appropiate runtime evaluate and compute the lambda on its side. The result could then be passed back to other runtimes.

At least the data passing part should be fairly "lightweight" since the arrow ffi API could be used. However, this sounds like it would introduce tight coupling between runtimes, which isn't really present today.

**Comment by stinodego** [comment]
This has been implemented. See:
https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.serialize.html
