### ISSUE TITLE
[META]: introduce labels/issue templates for different `polars` versions.

### ISSUE THREAD

**Issue by mainrs** [pola-rs/polars#2980]
I only really use the `Rust` version of polars and skimming through already asked questions and issues would be easier if I could filter by a label. For example `python`, `js`, `rust`.

What do you think about it? If you want I can put the time in and re-label old issues as well. I won't do it in one session. But watching some Netflix series alongside relabeling shouldn't be that boring :) 

Some questions apply to any runtime really. But having a label that marks an issue that is really about that specific runtime is the goal :)

**Comment by ritchie46** [comment]
Haha.. Sure.. :) 

Is there a way we can automate this in the future?

**Comment by mainrs** [comment]
> Haha.. Sure.. :)
> 
> Is there a way we can automate this in the future?

I think the best would be to introduce specific templates. Or have a checkbox that a user needs to click if it applies to a specific version of `polars`. Maybe there is a GA that can be used. I can investigate! :)

**Comment by alexanderpils** [comment]
@stinodego I would say you can close this issue since you guys have implemented it 🙂
