### ISSUE TITLE
Series apply func over another Series

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#2981]
#### Describe your feature request

Please describe the behavior you want and the motivation. Please also provide
examples of how polars would be used if your feature request were added.

If you're not sure what to write here, then try imagining what the ideal
documentation of your new feature would look like Then try to write it.

maybe some way to make a Series apply func over the another Series, such as 

```
A. B : polars Series

A.rolling_apply( lambda x: pl.cov(x, B), n)

```

**Comment by ritchie46** [comment]
I don't really understand your question. Can you elaborate a bit more with data?

I believe this is already possible, but you need to groom your dataframe a bit. Create a column with `groupby_dynamic`, `groupby_rolling` and apply `pl.cov`.

Or use numpy functions in the apply function. 

You cannot use expressions in `rolling_apply` that is impossible and will not be possible in polars.

**Comment by yutiansut** [comment]
really make a dataframe with [A, B] and then make a same u32 index to df can get the groupby_rolling(index, n).apply

however it not seems a elegant way for this condition,

dataframe doesn't have a simple ```rolling``` method

**Comment by ritchie46** [comment]
> dataframe doesn't have a simple rolling method

We must use `groupby_rolling` for that.

**Comment by yutiansut** [comment]
all right, and thanks a lot ~
