### ISSUE TITLE
Lazy repeat cannot be used to create columns

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#2983]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.15

#### What operating system are you using polars on?

Linux

#### What language version are you using

Python 3.10.2

#### Describe your bug.

In Polars 0.13.14, I could create a DataFrame using `repeat` for the columns. Now in 0.13.15, this only works if I set `eager=True`. This is probably related to #2958. This is easy to work around, but I am reporting it in case this was an unintentional regression.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

pl.DataFrame(dict(x=pl.repeat(1, 5)))
# ValueError: Series constructor not called properly.
```

#### What is the expected behavior?

Lazy `repeat` is evaluated and assigned.

**Comment by ritchie46** [comment]
Ah yes.. this was intended. I forgot this was breaking. Sorry.
