### ISSUE TITLE
Where as alias for filter

### ISSUE THREAD

**Issue by quartox** [pola-rs/polars#2985]
I would like to use `where` as an alias for `filter` on a dataframe. Our team has adopted usage of `where` in dataframes to prevent  confusion if the function is filtering in (i.e. leaving rows in that match the predicate) or filtering out (i.e. removing rows that match the predicate).

**Comment by ritchie46** [comment]
Why not add a where as an alias to the polars data structures for your team?

**Comment by zundertj** [comment]
@quartox : If needed, some additional inspiration for adding custom methods to Python Polars: https://github.com/pola-rs/polars/issues/1653

**Comment by ritchie46** [comment]
I am closing this as this is not something we will be working on.
