### ISSUE TITLE
Bug Report: Joining multiple DataFrames is causing the joined DataFrame to grow exponentially

### ISSUE THREAD

**Issue by robinhaecker** [pola-rs/polars#2986]
#### What language are you using?
Rust

#### Which feature gates did you use?
none

#### What version of polars are you using?
0.20.0

#### What operating system are you using polars on?
Ubuntu 20.04.4 LTS

#### What language version are you using
Rust 2021 Edition
rustc 1.58.1 (db9d1b20b 2022-01-20)

#### Describe your bug.
When joining DataFrames repeatedly, columns seem to get duplicated and the DataFrame's height is growing exponentially.

#### What are the steps to reproduce the behavior?
Minimal Example can be found in this Gist:
https://gist.github.com/robinhaecker/f962f678f2f21da143f576afaff92585

DataFrames are loaded from a fixed csv-file and joined into an aggregated DataFrame repeatedly. As the data itself (and hence the "timestamp" column which is used for the join) is identical, I would expect the DataFrame's height to stay the same. However, the DataFrame is growing after each iteration.

#### What is the actual behavior?
Minimal Example can be found in this Gist:
https://gist.github.com/robinhaecker/f962f678f2f21da143f576afaff92585

DataFrame is growing with each iteration exponentially.

Actual Output:
```
A) (39091, 2)
B) (40713, 3)
C) (82717, 4)
D) (1411941, 5)
```

#### What is the expected behavior?
Expected Output:
```
A) (39091, 2)
B) (39091, 3)
C) (39091, 4)
D) (39091, 5)
```

What do you think polars should have done?
When joining two DataFrames on identical columns, the columns should be appended and the number of rows should stay the same.

PS: I really like Polars, it's a great library. :-)

**Comment by ritchie46** [comment]
What kind of join do you do? Only a left join guarantees same number of rows. An inner join creates more rows for every match?

**Comment by robinhaecker** [comment]
The code snippet is here: https://gist.githubusercontent.com/robinhaecker/f962f678f2f21da143f576afaff92585/raw/c438b0e43012c1dda089fb306983ec3e946c001e/main.rs

In this example I've used an outer join, but have also tried a left join and experienced the same issue.

**Comment by ritchie46** [comment]
Now that I think of it, a left join also returns more rows if it has multiple matches.

**Comment by robinhaecker** [comment]
Ok, thanks for the info. I just double checked - it seems that this is in fact caused by duplicated values - when I remove those, the problem is gone. :-)

Still, I'm wondering if this is expected behaviour? As someone not too familiar with the internals of Polars, it was certainly unexpected for me. In case that this behaviour is in fact expected and intended, I would suggest to document this on the DataFrame left_join and outer_join functions to avoid people getting equally confused as I did in the future.

Additional note: Out of curiosity I just tried with an inner join as well, and experienced the exact same DataFrame growth behaviour in case of duplicated values in the join_on columns.

**Comment by zundertj** [comment]
This is also the behaviour in Pandas and SQL. The reason is that a join always returns all combinations of keys that match left with right, aka the cartesian product. So if a key exists twice in the right dataframe, every record on the left dataframe with that same key will be returned twice. Pandas has a good write up on this: https://pandas.pydata.org/docs/user_guide/merging.html#brief-primer-on-merge-methods-relational-algebra.

Inner join means that only rows which have a match in the other dataframe are being returned; a left (right) join also returns entries in the left (right) dataframe which do not have a match in the right (left) dataframe. See also https://www.codeproject.com/Articles/33052/Visual-Representation-of-SQL-Joins for a visual.
