### ISSUE TITLE
agg errors on literals

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#2987]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.15

#### What operating system are you using polars on?

Linux

#### What language version are you using

Python 3.10.2

#### Describe your bug.

The expressions in an aggregation context evaluate to a scalar. However, direct literals raise an exception when used.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

pl.DataFrame(dict(x=[1,2,3])).groupby('x').agg(pl.lit(1).alias('y'))
# exceptions.ComputeError: returned aggregation is a different length: 1 than the group lengths: 3
```

#### What is the expected behavior?
```
shape: (3, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 1   │
└─────┴─────┘
```

Note that you can work around it this with this code:

```python
pl.DataFrame(dict(x=[1,2,3])).groupby('x').agg((pl.col('x').take(0)*0 + pl.lit(1)).alias('y'))
```

**Comment by ritchie46** [comment]
Yes. The previous behaviour was a bug. You now need to use `pl.repeat(1, pl.count())`. To expand the literal to the group size.

**Comment by drhagen** [comment]
For future reference: As of 0.13.51, literals can be used in an aggregation context. The code in the original post now works as expected.
