### ISSUE TITLE
`arg_sort()` method after `groupby` gives weird results

### ISSUE THREAD

**Issue by LVG77** [pola-rs/polars#2989]
Hello,

First let me thank you for building and maintaining this great library.
I am not sure whether this is a bug or a feature that I don't really understand  that is why I am posting it as a question.

Let's say we have the following DataFrame:
```python
from itertools import product
import random
import polars as pl

row_id = range(3)
types =  product(['t1', 't2', 't3'], ['d1', 'd2'], row_id)
types = list(zip(*types))
pl_df = pl.DataFrame({'row_id': types[2], 'dim': types[1], 'types': types[0], 'values':[random.randint(0, 10) for _ in range(len(types[0]))]})
pl_df.head()
```

<img width="247" alt="image" src="https://user-images.githubusercontent.com/16968156/160246007-faf72902-188a-43f4-a6dc-d91efcfb2ae7.png">

Then we do `groupby` and aggregate `values` over `row_id` and `dim`. After that I want to do `arg_sort()` on the `row_id` column over `dim`. However, the results I get for the `arg_sort` column are not what I expect. For example I would think that the `arg_sort` column should have 0 for (0, "d1") and (0, "d2") combinations of the `row_id` and `dim` as well as 1 for (1, "d1") and (1, "d2") combinations of the `row_id` and `dim`. As you can see those are not the results. Is this a bug or I am missing something?

```python
(
    pl_df
    .groupby(['row_id', 'dim'])
    .agg(pl.col('values').sum())
    .with_columns(pl.col('row_id').arg_sort().over('dim').alias('arg_sort'))
)
```
<img width="232" alt="image" src="https://user-images.githubusercontent.com/16968156/160246185-3fda565e-7caa-4310-a895-537b02af5fd9.png">

Thank you for your help!
Best regards,
LG

**Comment by ritchie46** [comment]
Hi, which version are you using? I recently fixed a bug in this?

**Comment by LVG77** [comment]
I am using version 0.13.15 under Linux.

**Comment by LVG77** [comment]
I am sorry for the confusion. I misunderstood the way `sort_arg` method works. As far as I can see `sort_arg()` is working correctly and there is nothing weird about it.
