### ISSUE TITLE
Result of expression is unstable and changes after several executions

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#3002]
#### What language are you using?

Python

#### What version of polars are you using?

Build from source 29.03.2022

#### What operating system are you using polars on?

Ubuntu 20.04
#### Describe your bug.

I tried to test fix of this [issue](https://github.com/pola-rs/polars/issues/2984#issue-1180852246), there is no exception on empty list anymore, but the result of the example below is still unstable and changes after several executions.

```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 2, 1, 4, 5, 4, 6],
             })

df.groupby(['group']).agg(
    [
        pl.col('id').where(pl.col('id') < 3).sort().diff().sum().alias('low_id'),
        pl.col('id').where(pl.col('id') >= 3).sort().diff().sum().alias('high_id'),
    ]
).sort('group')
```

**Comment by s-b90** [comment]
@ritchie46 I compiled polars from source and seems that bug is still present. Did you test this example?
```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 2, 1, 4, 5, 4, 6],
             })

df.groupby(['group']).agg(
    [
        pl.col('id').where(pl.col('id') < 3).sort().diff().max().alias('low_id'),
        pl.col('id').where(pl.col('id') >= 3).sort().diff().max().alias('high_id'),        
        pl.col('id').where(pl.col('id') < 3).unique_counts().sum().alias('test_fltr'),
    ]
).sort('group')
```

**Comment by ritchie46** [comment]
Ah, probably two bugs in one issue. I will pick it up.
