### ISSUE TITLE
unresolved import `polars_io::ipc` could not find `ipc` in `polars_io`

### ISSUE THREAD

**Issue by DmitrySorda** [pola-rs/polars#3037]
#### What language are you using?

Replace this text with the **Rust**, **Python**, or **Node.js**.

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### What version of polars are you using?

Replace this text with the version.

#### What operating system are you using polars on?

Replace this text with your operating system and version.

#### What language version are you using
ex: python 3.8, node 16, etc.. 

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```
your
code
goes
here
```

**Example**

```python
import polars as pl
import numpy as np

# Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
})
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

Please remove clutter from your examples. Only include the bare minimum to produce the result.
So please:

* strip unused columns
* use short distinguishable names
* don't include unneeded computations

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think polars should have done?

**Comment by ritchie46** [comment]
Can you fill in the template?

**Comment by DmitrySorda** [comment]
Rust;
`[package]
name = "ipc_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars-io="0.20.0"
polars-core="0.20.0"`
`use polars_core::prelude::*;
use polars_io::ipc::IpcWriter;
use std::fs::File;
use polars_io::SerWriter;

fn example(df: &mut DataFrame) -> Result<()> {
    let mut file = File::create("file.ipc").expect("could not create file");

    IpcWriter::new(&mut file)
        .finish(df)
}
fn main(){
    let s0 = Series::new("days", &[0, 1, 2, 3, 4]);
let s1 = Series::new("temp", &[22.1, 19.9, 7., 2., 3.]);
let mut df = DataFrame::new(vec![s0, s1]).unwrap();
   example(&mut df);
}`
`error[E0432]: unresolved import `polars_io::ipc`
 --> src/main.rs:2:16
  |
2 | use polars_io::ipc::IpcWriter;
  |                ^^^ could not find `ipc` in `polars_io`

warning: unused import: `polars_io::SerWriter`
 --> src/main.rs:4:5
  |
4 | use polars_io::SerWriter;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default`

can't compile example from here https://pola-rs.github.io/polars/polars_io/ipc/struct.IpcWriter.html

**Comment by DmitrySorda** [comment]
My bad. Did not specify dependencies future 
polars-io={version="0.20.0", features = ["ipc"] }
