### ISSUE TITLE
Empty list of `groupby` columns causes error in `agg`

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#3041]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.7

#### What operating system are you using polars on?

Linux

#### What language version are you using

3.10.2

#### Describe your bug.

If the list of `by` columns provided to `groupby` is empty, aggregation errors.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

pl.DataFrame(dict(x=[0,0,1,1])).groupby([]).agg(pl.count())
# exceptions.ShapeError: the Series used as keys should have the same length as the DataFrame

pl.DataFrame(dict(x=[0,0,1,1])).groupby([]).agg(pl.arange(0, pl.count()))
# exceptions.ShapeError: the Series used as keys should have the same length as the DataFrame

pl.DataFrame(dict(x=[0,0,1,1])).groupby([]).agg(pl.sum('x').alias('y'))
# exceptions.ShapeError: the Series used as keys should have the same length as the DataFrame
```

#### What is the expected behavior?

The entire data frame is aggregated to a single row.

**Comment by ritchie46** [comment]
Right.. We should throw an error earlier and not allowing grouping by nothing. All downstream code assumes we have keys.
