### ISSUE TITLE
col wildcard expansion by datatype does not work for Datetime

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3042]
polars 0.3.17+ (including commit  40815b0 for #3039 / #3035)
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
When the `col` expression is used with a `Datetime` datatype wildcard, no action is taken on the applicable columns of type `Datetime`, nor do I receive an error.

#### What are the steps to reproduce the behavior?
```python3
from datetime import date, datetime
import polars as pl

df2 = pl.DataFrame(
    {
        "Datetime1": pl.date_range(
            low=datetime(2020, 1, 1), high=datetime(2020, 2, 1), interval="1w"
        ),
        "Datetime2": pl.date_range(
            low=datetime(2021, 1, 1), high=datetime(2021, 2, 1), interval="1w"
        ),
    }
)
df2.with_column(pl.col(pl.Datetime).dt.strftime("%m/%d/%Y"))
```
```
shape: (5, 2)
┌─────────────────────┬─────────────────────┐
│ Datetime1           ┆ Datetime2           │
│ ---                 ┆ ---                 │
│ datetime[ns]        ┆ datetime[ns]        │
╞═════════════════════╪═════════════════════╡
│ 2020-01-01 00:00:00 ┆ 2021-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2020-01-08 00:00:00 ┆ 2021-01-08 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2020-01-15 00:00:00 ┆ 2021-01-15 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2020-01-22 00:00:00 ┆ 2021-01-22 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2020-01-29 00:00:00 ┆ 2021-01-29 00:00:00 │
└─────────────────────┴─────────────────────┘
```

However, when I explicitly name the column, the action is taken on the named column.
```python3
df2.with_column(pl.col("Datetime1").dt.strftime("%m/%d/%Y"))
```
```
shape: (5, 2)
┌────────────┬─────────────────────┐
│ Datetime1  ┆ Datetime2           │
│ ---        ┆ ---                 │
│ str        ┆ datetime[ns]        │
╞════════════╪═════════════════════╡
│ 01/01/2020 ┆ 2021-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 01/08/2020 ┆ 2021-01-08 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 01/15/2020 ┆ 2021-01-15 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 01/22/2020 ┆ 2021-01-22 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 01/29/2020 ┆ 2021-01-29 00:00:00 │
└────────────┴─────────────────────┘
```

Oddly enough, the datatype wildcard expansion *does* work with `Date`:
```python3
df = pl.DataFrame(
    {
        "Date1": [date(2021,1,1,)],
        "Date2": [date(2022,1,1,)],
    }
)
df.with_column(pl.col(pl.Date).dt.strftime("%m/%d/%Y"))
```
```
shape: (1, 2)
┌────────────┬────────────┐
│ Date1      ┆ Date2      │
│ ---        ┆ ---        │
│ str        ┆ str        │
╞════════════╪════════════╡
│ 01/01/2021 ┆ 01/01/2022 │
└────────────┴────────────┘
```

#### Other Notes
Before logging this issue, I first checked to see if there was an outstanding issue regarding wildcard-type expressions in the `col` expression.  I noticed Issue #3035, but I wasn't sure if that fix addressed this issue.  So I followed the instructions for compiling polars from source (great instructions, BTW) and installed it in a virtual environment, using commits through 83fbda3f (which includes 40815b0).

This is the first time I've done this.  I double-checked that the sample code in #3035 produces the correct output in my virtual environment, so I think I did this correctly.  (If I goofed this up, I apologize.)

**Comment by ritchie46** [comment]
> polars 0.3.17+ (including commit https://github.com/pola-rs/polars/commit/40815b0ec3d0f470bc955e8fe40288b9c38430cb for https://github.com/pola-rs/polars/pull/3039 / https://github.com/pola-rs/polars/issues/3035)

You are sharp!
