### ISSUE TITLE
`trapz` function

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#3043]
#### Describe your feature request

A common operation in science is to compute the area under the curve defined by two columns. This is often called [`trapz`](https://numpy.org/doc/stable/reference/generated/numpy.trapz.html) because the easiest way to compute it is using the trapezoidal rule. The formula to compute the integral for two columns `x` and `y` is:

`0.5 * sum((x[1:] - x[:-1]) * (y[1:] + y[:-1]))`

#### Sample documentation

```
def trapz(x: Expr, y: Expr) -> Expr:
    """
    Integrate with trapezoidal rule.

    Reduces two expressions of an independent and an dependent variable
    to a scalar equal to the area the curve using the trapezoidal rule.

    Parameters
    ----------
    x
        Independent variable. Must be weakly monotonically increasing.
    y
        Dependent variable.
    """
    return pl.lit(0.5) * ((x.slice(1, x.count() - 1) - x.slice(0, x.count() - 1)) * (y.slice(1, y.count() - 1) + y.slice(0, y.count() - 1))).sum()
```

Note: this does not actually work in `agg` because it gives this error that I don't have enough experience to understand:

```
ValueError: cannot combine this binary expression, the groups do not match
```

**Comment by cbilot** [comment]
As an aside, the use of `shift` (rather than `slice`) would avoid the error you are receiving:
```python3
import polars as pl

def trapz(x: pl.Expr, y: pl.Expr) -> pl.Expr:
    """
    Integrate with trapezoidal rule.

    Reduces two expressions of an independent and an dependent variable
    to a scalar equal to the area the curve using the trapezoidal rule.

    Parameters
    ----------
    x
        Independent variable. Must be weakly monotonically increasing.
    y
        Dependent variable.
    """
    return 0.5 * ((x - x.shift()) * (y + y.shift())).sum()

pl.trapz = trapz
```
So that ...
```python3
df = pl.DataFrame(
    {
        "group": ["a", "a", "a", "b", "b", "b"],
        "x": [1, 2, 3, 1, 2, 3],
        "y": [5, 4, 3, 0, 1, 2],
    }
)


df.groupby('group').agg(pl.trapz(pl.col('x'),pl.col('y')))
```
```
shape: (2, 2)
┌───────┬─────────┐
│ group ┆ literal │
│ ---   ┆ ---     │
│ str   ┆ f64     │
╞═══════╪═════════╡
│ b     ┆ 2.0     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ a     ┆ 8.0     │
└───────┴─────────┘
```

**Comment by drhagen** [comment]
I don't understand how that works, but I have verified that it does, in fact, give the right answer.

**Comment by MarcoGorelli** [comment]
As discussed today - it's fairly easy to implement this as
```
0.5 * ((x - x.shift()) * (y + y.shift())).sum()
```
so it's not necessary to add a dedicated method for this to the Polars API. But, it may be a good candidate for a "cookbook" https://github.com/pola-rs/polars/issues/13064
