### ISSUE TITLE
The dot expression does not yield the right result in a `groupby` context.

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3047]
polars 0.13.17
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
The `dot` expression does not yield the right result in a `groupby` context.
#### What are the steps to reproduce the behavior?
```python3
import polars as pl

df = pl.DataFrame(
    {
        "group": ["a", "a", "a", "b", "b", "b"],
        "x": [1, 1, 1, 1, 1, 1],
        "y": [1, 2, 3, 4, 5, 6],
    }
)

df.groupby("group").agg(pl.col("x").dot("y").alias("dot"))
```
```
shape: (2, 2)
┌───────┬────────────┐
│ group ┆ dot        │
│ ---   ┆ ---        │
│ str   ┆ list [i64] │
╞═══════╪════════════╡
│ a     ┆ [21, 0, 0] │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b     ┆ [0, 0, 3]  │
└───────┴────────────┘
```

However, the `dot` expression does give the correct result in a select context:
```python3
df.select([pl.col("x").dot("y").alias("dot")])
```
```
shape: (1, 1)
┌─────┐
│ dot │
│ --- │
│ i64 │
╞═════╡
│ 21  │
└─────┘
```
As an aside, I discovered this while looking at #3043.  My first solution was:
```python3
pl.col('x').diff().dot(pl.col('y') + pl.col('y').shift()) * 0.5
```
But this hit a snag with the `groupby` context.

**Comment by ritchie46** [comment]
Yeap, turned out we called `map` instead of `apply` :/.

BTW.. Thanks for all the help on SO on here. Your issues are excellent and really make it a lot easier to track down the culprits. Saves me a lot of time. :raised_hands:

**Comment by cbilot** [comment]
Glad to help!  Especially if it frees you up to focus on more strategic-type stuff.
