### ISSUE TITLE
read_avro call fails if no columns are passed in as an argument

### ISSUE THREAD

**Issue by gmax0** [pola-rs/polars#3061]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.18

#### What operating system are you using polars on?

Ubuntu 18.04.6 LTS

#### What language version are you using

Python 3.8

#### Describe your bug.

Calling polars.read_avro without the columns argument errors out.

#### What is the actual behavior?

```
Traceback (most recent call last):
File "polars-test-2.py", line 6, in <module>
  df = pl.read_avro(sys.argv[1], n_rows=5)
  File "/home/.local/lib/python3.8/site-packages/polars/io.py", line 733, in read_avro
    return DataFrame._read_avro(file, n_rows=n_rows, columns=columns)
  File "/home/.local/lib/python3.8/site-packages/polars/internals/frame.py", line 666, in _read_avro
    self._df = PyDataFrame.read_avro(file, columns, projection, n_rows)
exceptions.ArrowErrorException: InvalidArgumentError("Chunk require all its arrays to have an equal number of rows")

```

#### What is the expected behavior?

I'd guess the default behavior would be to include all the columns defined by the avro schema into a dataframe.
Not a huge deal as I can allocate an array to pass in, but just thought I'd point it out.

**Comment by ritchie46** [comment]
Can you add a minimal example?

I cannot reproduce this.

**Comment by gmax0** [comment]
Might be specific to a large dataset's schema that I'm using. I likewise tried to recreate the issue with a smaller, dummy dataset and it didn't surface. Closing until I figure out the root cause.
