### ISSUE TITLE
Entropy does not work properly

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#3065]
Ubuntu 20.04
polars 0.13.16
python 3.8

Seems that `entropy` works only with numeric data and even with numeric shows strange result of type list.

```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 2, 1, 4, 5, 4, 6],
             })
```
**incorrect**
```python
df.groupby(['group']).agg(pl.col('id').entropy())
```
group | id
-- | --
str | list
"B" | [-29.888101]
"A" | [-1.386294]

**correct should be: (for 0.13.16)**
And this will work with str columns as well. 
**Important note:** in 0.13.18 using expression below throw an exception:
PanicException: impl error, should be a list at this point: SchemaMisMatch("Series dtype Float64 != list")
```python
df.groupby(['group']).agg([((pl.col('id').unique_counts() / pl.col('id').len()).log() * -1 *
            (pl.col('id').unique_counts() / pl.col('id').len())).sum()])
```

group | id
-- | --
str | f64
"B" | 1.039721
"A" | 0.636514

PS: Please check entropy formula if you are using *base* argument, it should be like that:
  entropy =  -(vc * np.log(vc)/np.log(base)).sum()
In case if base == e, it can be just:
 entropy =  -(vc * np.log(vc)).sum()
where vc is .unique_counts() / .len()

**Comment by s-b90** [comment]
@ritchie46 Found that stil something goes wrong:
in polars 0.13.31:

group | id
-- | --
str | f64
"A" | 1.039721
"B" | 1.371381


while it should be:


group | id
-- | --
str | f64
"A" | 0.636514
"B" | 1.039721

**Comment by ritchie46** [comment]
It does the same as scipy, we also have a normalization step.

**Comment by s-b90** [comment]
Thanks for clarification. Is there any chance to get classic entropy without normalization? Or maybe make normalization optional, like in scipy?

**Comment by ritchie46** [comment]
Can you make a feature request of that option? Then I can take a look later.

**Comment by s-b90** [comment]
Thank you, #3345.
