### ISSUE TITLE
Using escape_char from pandas along with quote_char

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#3074]
Python, - 0.12.6 version

Hi @ritchie46 
When the csv has comma as separator and if one of the csv field is like "firstname, lastname", then pandas comes very handy with the use of escape_character as '\\'. I couldn't make read_csv of polars work with such csv using comma as separator by using quote_char as None or '' or '"'

Any suggestions ?

**Comment by ritchie46** [comment]
Have you tried updating? Escaped values should be read by polars.

**Comment by NarayanB** [comment]
i tried with 0.13.18 too i guess. Could you please provide an example if you have it handy?

**Comment by ritchie46** [comment]
Can you make an example of your data? See: 

#### What language are you using?

Replace this text with the **Rust**, **Python**, or **Node.js**.

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### What version of polars are you using?

Replace this text with the version.

#### What operating system are you using polars on?

Replace this text with your operating system and version.

#### What language version are you using
ex: python 3.8, node 16, etc.. 

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```
your
code
goes
here
```

**Example**

```python
import polars as pl
import numpy as np

# Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
})
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

Please remove clutter from your examples. Only include the bare minimum to produce the result.
So please:

* strip unused columns
* use short distinguishable names
* don't include unneeded computations

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think polars should have done?

**Comment by JCMorente94** [comment]
I don't see any problem with both quote_char.

import pandas as pd
import polars as pl
from io import StringIO

----------------------------------------------------------------

data = '''username,identifier,name
booker12,9012,"Rachel, Booker"
grey07,2070,"Laura, Grey"
johnson81,4081,""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, Smith"'''

pd.read_csv(StringIO(data), quotechar=r'"')

username | identifier | name
| -- | -- | --
booker12 | 9012 | Rachel, Booker
grey07 | 2070 | Laura, Grey
johnson81 | 4081 | NaN
jenkins46 | 9346 | Mary, Jenkins
smith79 | 5079 | Jamie, Smith

pl.read_csv(StringIO(data), quote_char= r'"')

username | identifier | name
-- | -- | --
str | i64 | str
"booker12" | 9012 | "Rachel, Booker"
"grey07" | 2070 | "Laura, Grey"
"johnson81" | 4081 | ""
"jenkins46" | 9346 | "Mary, Jenkins"
"smith79" | 5079 | "Jamie, Smith"

-------------------------------------------------------------

data = """username,identifier,name
booker12,9012,'Rachel, Booker'
grey07,2070,'Laura, Grey'
johnson81,4081,''
jenkins46,9346,'Mary, Jenkins'
smith79,5079,'Jamie, Smith'"""

pd.read_csv(StringIO(data), quotechar =r"'")

username | identifier | name
| -- | -- | --
booker12 | 9012 | Rachel, Booker
grey07 | 2070 | Laura, Grey
johnson81 | 4081 | NaN
jenkins46 | 9346 | Mary, Jenkins
smith79 | 5079 | Jamie, Smith

pl.read_csv(StringIO(data), quote_char=r"'")

username | identifier | name
-- | -- | --
str | i64 | str
"booker12" | 9012 | "Rachel, Booker"
"grey07" | 2070 | "Laura, Grey"
"johnson81" | 4081 | ""
"jenkins46" | 9346 | "Mary, Jenkins"
"smith79" | 5079 | "Jamie, Smith"

**Comment by NarayanB** [comment]
This seem to happen when consuming from a file. I think irrespective, when you have quotes within quotes, polars may have issue. Please run the program like below.  Polars when it has issue treats the remaining rows as 1 row or something like that

Polars: 0.12.6, Pandas 1.3.3
-------------------------------------------------------------
import pandas as pd
import polars as pl

def df_from_pd():
    df = pd.read_csv('../csv/csv_quote_char.csv', sep=',',escapechar='\\')
    print('Pandas df\n')
    print(df.head(5))

def df_from_pl():
    df = pl.read_csv('../csv/csv_quote_char.csv', quote_char=r'"', ignore_errors=False)
    print('Polars df\n', df.head(5))

df_from_pl()
df_from_pd()
-------------------------------------------------------------
Create a csv file like below.

username,identifier,name
booker12,9012,"sean,\"Jeff"
grey07,2070,"Laura, Grey"
johnson81,4081,"\"Chill\""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, \"Smith\""

-------------------------------------------------------------

Output:
Polars df
 shape: (1, 3)
┌──────────┬────────────┬───────────────────┐
│ username ┆ identifier ┆ name              │
│ ---      ┆ ---        ┆ ---               │
│ str      ┆ str        ┆ str               │
╞══════════╪════════════╪═══════════════════╡
│ booker12 ┆ 9012       ┆ sean,\Jeff        │
│          ┆            ┆ grey07,2070,Laura │
└──────────┴────────────┴───────────────────┘
Pandas df

    username  identifier            name
0   booker12        9012      sean,"Jeff
1     grey07        2070     Laura, Grey
2  johnson81        4081         "Chill"
3  jenkins46        9346   Mary, Jenkins
4    smith79        5079  Jamie, "Smith"

**Comment by NarayanB** [comment]
username,identifier,name
booker12,9012,"sean,\"Jeff"
grey07,2070,"Laura, Grey"
johnson81,4081,"\"Chill\""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, \"Smith\""

**Comment by NarayanB** [comment]
username,identifier,name
booker12,9012,"sean,\"Jeff"
grey07,2070,"Laura, Grey"
johnson81,4081,"\"Chill\""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, \"Smith\""

**Comment by NarayanB** [comment]
![csv_escape](https://user-images.githubusercontent.com/2303637/162585681-a0470d41-bf43-4706-9408-d8b52be52105.PNG)

**Comment by NarayanB** [comment]
Had issue with copy paste of csv file and uploaded an image. As you could see quotes with quotes are escaped with \

**Comment by NarayanB** [comment]
Hi @ritchie46, @JCMorente94,
Could you please suggest any workaround ? Was my explanation of the issue clear?

**Comment by cbilot** [comment]
This may not be the solution you are looking for, but one great (and permanent) workaround for headaches with csv files (and I've experienced **endless** headaches with csv files) is to sanitize your csv files using utilities such as [xsv](https://github.com/BurntSushi/xsv) or [qsv](https://github.com/jqnatividad/qsv) before reading them into Polars.  (I myself use qsv.)  These tools are amazing, and they are now part of my standard workflows with any csv file.

For example, let's take your csv file, which looks like this:
```
username,identifier,name
booker12,9012,"sean,\"Jeff"
grey07,2070,"Laura, Grey"
johnson81,4081,"\"Chill\""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, \"Smith\""
```
Note that the escaping of quotes is non-standard.  (Many parsers expect escaped quotes to be doubled, not prefixed with a backslash character.)

And when I run `read_csv` on the unsanitized csv file:
```python
pl.read_csv('csv_quote_char.csv', quote_char='"', ignore_errors=False)
```
The output is exactly as you describe:
```
shape: (1, 3)
┌──────────┬────────────┬──────────────────┐
│ username ┆ identifier ┆ name             │
│ ---      ┆ ---        ┆ ---              │
│ str      ┆ str        ┆ str              │
╞══════════╪════════════╪══════════════════╡
│ booker12 ┆ 9012       ┆ sean,\Jeff       │
│          ┆            ┆ grey07,2070,Laur │
└──────────┴────────────┴──────────────────┘
```
#### Fixing the escaped quotes
Fixing the escaping problem using the qsv utility is quick and easy:
```sh
qsv input --escape='\' csv_quote_char.csv --output=fixed.csv
```
The creates the following sanitized file:
```
username,identifier,name
booker12,9012,"sean,""Jeff"
grey07,2070,"Laura, Grey"
johnson81,4081,"""Chill"""
jenkins46,9346,"Mary, Jenkins"
smith79,5079,"Jamie, ""Smith"""
```
Notice that the qsv utility has transformed the escaped double-quotes into a format more readily recognized by most parsers.

Now when I run `read_csv` on the sanitized file, I get:
```python3
pl.read_csv('fixed.csv', quote_char='"', ignore_errors=False)
```
```
shape: (5, 3)
┌───────────┬────────────┬────────────────┐
│ username  ┆ identifier ┆ name           │
│ ---       ┆ ---        ┆ ---            │
│ str       ┆ i64        ┆ str            │
╞═══════════╪════════════╪════════════════╡
│ booker12  ┆ 9012       ┆ sean,"Jeff     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ grey07    ┆ 2070       ┆ Laura, Grey    │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ johnson81 ┆ 4081       ┆ "Chill"        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ jenkins46 ┆ 9346       ┆ Mary, Jenkins  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ smith79   ┆ 5079       ┆ Jamie, "Smith" │
└───────────┴────────────┴────────────────┘
```

The things these csv utilities can do is simply amazing.  They have saved me endless headaches.  Now, when I read a sanitized csv file into Polars, I don't spend hours chasing down problems.

I realize this is probably not the solution you were looking for.  But these tools are designed to fix the very sort of headaches that csv files create.

**Comment by NarayanB** [comment]
Hi @ghuls, 
that was one of the options i thought of using, but i was thinking that it should be possible to use use_pyarrow=True and then pass **kwargs for escape etc, in pl.read_csv. Another question is I guess parsing will be bit slow compared to pl.read_csv

**Comment by NarayanB** [comment]
> This may not be the solution you are looking for, but one great (and permanent) workaround for headaches with csv files (and I've experienced **endless** headaches with csv files) is to sanitize your csv files using utilities such as [xsv](https://github.com/BurntSushi/xsv) or [qsv](https://github.com/jqnatividad/qsv) before reading them into Polars. (I myself use qsv.) These tools are amazing, and they are now part of my standard workflows with any csv file.
> 
> For example, let's take your csv file, which looks like this:
> 
> ```
> username,identifier,name
> booker12,9012,"sean,\"Jeff"
> grey07,2070,"Laura, Grey"
> johnson81,4081,"\"Chill\""
> jenkins46,9346,"Mary, Jenkins"
> smith79,5079,"Jamie, \"Smith\""
> ```
> 
> Note that the escaping of quotes is non-standard. (Many parsers expect escaped quotes to be doubled, not prefixed with a backslash character.)
> 
> And when I run `read_csv` on the unsanitized csv file:
> 
> ```python
> pl.read_csv('csv_quote_char.csv', quote_char='"', ignore_errors=False)
> ```
> 
> The output is exactly as you describe:
> 
> ```
> shape: (1, 3)
> ┌──────────┬────────────┬──────────────────┐
> │ username ┆ identifier ┆ name             │
> │ ---      ┆ ---        ┆ ---              │
> │ str      ┆ str        ┆ str              │
> ╞══════════╪════════════╪══════════════════╡
> │ booker12 ┆ 9012       ┆ sean,\Jeff       │
> │          ┆            ┆ grey07,2070,Laur │
> └──────────┴────────────┴──────────────────┘
> ```
> 
> #### Fixing the escaped quotes
> 
> Fixing the escaping problem using the qsv utility is quick and easy:
> 
> ```shell
> qsv input --escape='\' csv_quote_char.csv --output=fixed.csv
> ```
> 
> This creates the following sanitized file:
> 
> ```
> username,identifier,name
> booker12,9012,"sean,""Jeff"
> grey07,2070,"Laura, Grey"
> johnson81,4081,"""Chill"""
> jenkins46,9346,"Mary, Jenkins"
> smith79,5079,"Jamie, ""Smith"""
> ```
> 
> Notice that the qsv utility has transformed the escaped double-quotes into a format more readily recognized by most parsers.
> 
> Now when I run `read_csv` on the sanitized file, I get:
> 
> ```python
> pl.read_csv('fixed.csv', quote_char='"', ignore_errors=False)
> ```
> 
> ```
> shape: (5, 3)
> ┌───────────┬────────────┬────────────────┐
> │ username  ┆ identifier ┆ name           │
> │ ---       ┆ ---        ┆ ---            │
> │ str       ┆ i64        ┆ str            │
> ╞═══════════╪════════════╪════════════════╡
> │ booker12  ┆ 9012       ┆ sean,"Jeff     │
> ├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ grey07    ┆ 2070       ┆ Laura, Grey    │
> ├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ johnson81 ┆ 4081       ┆ "Chill"        │
> ├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ jenkins46 ┆ 9346       ┆ Mary, Jenkins  │
> ├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ smith79   ┆ 5079       ┆ Jamie, "Smith" │
> └───────────┴────────────┴────────────────┘
> ```
> 
> The things these csv utilities can do is simply amazing. They have saved me endless headaches. Now, when I read a sanitized csv file into Polars, I don't spend hours chasing down problems.
> 
> I realize this is probably not the solution you were looking for. But these tools are designed to fix the very sort of headaches that csv files create.

Hi @cbilot 
Thanks for your cool suggestion. As you mentioned, it doesn't fit in our workflow for dealing with huge gz files

**Comment by ghuls** [comment]
> Hi @ghuls, that was one of the options i thought of using, but i was thinking that it should be possible to use use_pyarrow=True and then pass **kwargs for escape etc, in pl.read_csv. Another question is I guess parsing will be bit slow compared to pl.read_csv

I will see if I can expose those options to read_csv.

PyArrows CSV reader is also multithreaded as far as I know, so it shouldn't be 10 times slower.

**Comment by NarayanB** [comment]
Hi @ghuls, 
Any update on escape char support ?

**Comment by ritchie46** [comment]
I don't want to support this. Polars aims to support [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) as csv standard. csv files that deviate from this standard need to be sanitized first.
