### ISSUE TITLE
`frac` has no impact on sample function if passed with `n`

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars#3075]
Didn't think this would be classified as a *Bug Report*. Maybe it should have been.

https://github.com/pola-rs/polars/blob/7e085cdad07cb7308f6a69451bebf269c39e8b51/py-polars/polars/internals/frame.py#L4766-L4768

This snippet is an example of where this can occur in `polars`.

If you pass `n=1` and `frac=0.4` (or any values really) `frac` will have no effect on something like `.sample()`. Not sure if this is intended, but it seems like something that can become confusing to newer users.

The docstring is pretty clear on usage, so this is mainly just a callout.

Example
```py
import polars as pl
import numpy as np

n = 1000
df = pl.DataFrame(
    {
        "a": np.random.randint(0, 100, (n,)),
        "b": np.random.randint(0, 1000, (n,)),
    }
)

df.sample(n=1, frac=0.4)
```

**Comment by ritchie46** [comment]
Hmm.. yeah, we should raise a `ValueError` when both are passed.
