### ISSUE TITLE
handy functions to convert dtypes for columns between int/float and str

### ISSUE THREAD

**Issue by momentlost** [pola-rs/polars#3089]
Maybe it's already there but I am not locating it, in which case I apologize for raising this request.

I was looking for the documentation pretty thoroughly to see whether there would be a way to change the dtypes for the strings with numbers easily. For example, the problem I face is as follows:

df = pl.Dataframe({"foo": ["100CT pen", "pencils 250CT", "what "125CT soever", "this is a thing"]})

I could extract and create a new column named {"bar": ["100", "250", "125", ""]}. But then I couldn't find a handy function that converts this column to Int64 or float dtypes so that the result is [100, 250, 125, null]. 

Also, vice versa. Sometimes it would be useful to have a handy function that converts the column of [100, 250, 125, 0] to ["100", "250", "125", "0"]. Is it something that already exists?

Thank you.

**Comment by ritchie46** [comment]
Could you ask a stackoverflow question? I will answer it there. This will help other people having the same question.

**Comment by ritchie46** [comment]
See: https://stackoverflow.com/questions/71790235/polars-switching-between-dtypes-within-a-dataframe
