### ISSUE TITLE
include Cargo.lock in the py-polars pypi source release

### ISSUE THREAD

**Issue by happysalada** [pola-rs/polars#3092]
#### Describe your feature request

Would it be possible to include a Cargo.lock file with the py-polars pypi source release ?
Having the lock would enable packaging for different os (in particular nixos).
Not having the lock means it needs to be generated manually on every release, which makes maintenance less likely.

There is already a local-dependency folder in the source release, maybe it's much more work to add a lock, but thought I would ask.

**Comment by ritchie46** [comment]
You can take the lock file from the source code in the tagged releases. https://github.com/pola-rs/polars/tags

**Comment by happysalada** [comment]
The source is indeed included, thank you!
