### ISSUE TITLE
group.head.sum incorrect 

### ISSUE THREAD

**Issue by oliveagle** [pola-rs/polars#3097]
#### What language are you using?

**Python**

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### What version of polars are you using?

polars==0.13.18

#### What operating system are you using polars on?

linux 
PRETTY_NAME="Ubuntu 20.04.3 LTS"

#### What language version are you using

Python 3.8.13

#### Describe your bug.

DataFrame group by  head then sum get incorrect result

#### What are the steps to reproduce the behavior?

```
import polars as pl
import numpy as np

a = [1,1,1,2,2,3,3,3,3]
    
df = pl.DataFrame({
    'a': a,
    'b': np.arange(1,len(a)+1)
})

print(df)

shape: (9, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ ... ┆ ... │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 6   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 8   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 9   │
└─────┴─────┘



print(df.groupby('a').agg([
    pl.col("b").head(3).sum()
]))

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 9   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 30  │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 6   │
└─────┴─────┘

print(6 + 7 + 8)
21


df.to_pandas().groupby("a").head(3).groupby("a").sum()

    b
a    
1   6
2   9
3  21
```

#### What is the expected behavior?

6 + 7 + 8 = 21

**Comment by ritchie46** [comment]
I cannot reproduce it?

```python
a = [1,1,1,2,2,3,3,3,3]
    
df = pl.DataFrame({
    'a': a,
    'b': np.arange(1,len(a)+1)
})
print(df.groupby('a').agg([
    pl.col("b").head(3).sum()
]))

```

```
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 9   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 21  │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 6   │
└─────┴─────┘

```

Does this still occur if you update to latest polars version?

**Comment by cjermain** [comment]
I am seeing this error pop up on the latest master branch (c47e275baa57e720c9d93a8120a464006f8ef05c) for the `tests/test_queries.py` file.

Running the example above I get:
```
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 6   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 9   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 30  │
└─────┴─────┘
```
I'm running this test on Ubuntu 20.04 with Python 3.8.10 and rustc 1.62.0-nightly.

**Comment by cjermain** [comment]
Independent of the reproducibility, I think the test has an issue in that it does not actually use the `maintain_order` variable that is looped over.
https://github.com/pola-rs/polars/blob/01701550cbc00d63fcc3cebc60b06bed3fa6b1c4/py-polars/tests/test_queries.py#L60-L61

**Comment by cjermain** [comment]
This can be reproduced in a docker container:
```
docker run -it ubuntu:20.04
$ apt update
$ apt install git curl cmake build-essential python3 python3-venv
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ source $HOME/.cargo/env
$ git clone https://github.com/pola-rs/polars.git
$ cd polars/py-polars
$ sed -i 's/@python -m/@python3 -m/' Makefile
$ make venv
$ source venv/bin/activate
$ make test
```
I confirmed this is also reproducible on Ubuntu 21.04 using the same approach.

**Comment by ritchie46** [comment]
Ah, I can reproduce it if I run it with `POLARS_MAX_THREADS=3`. Will look into it.
