### ISSUE TITLE
Panic when using Expr::Columns in filter

### ISSUE THREAD

**Issue by elferherrera** [pola-rs/polars#3104]
#### What language are you using?

Rust

#### Which feature gates did you use?
	"default", "parquet", "json", "serde", "object",
	"checked_arithmetic", "strings", "cum_agg", "is_in",
	"rolling_window", "strings", "rows", "random",
        "dtype-datetime", "dtype-struct", "lazy"

#### What version of polars are you using?
0.20.0

#### What operating system are you using polars on?

windows

#### What language version are you using
ex: python 3.8, node 16, etc.. 

#### Describe your bug.

When using `Expr::Columns` the filter command in a lazy frame panics

**Comment by ritchie46** [comment]
Have you got an example?

**Comment by elferherrera** [comment]
Sure
```
let df = df![
    "a" => [1, 2, 3],
    "b" => [None, Some("a"), Some("b")]
]?;

let filtered = df.lazy()
    .filter(cols(vec!["a".to_string(), "b".to_string()]).gt(lit(2)))
    .collect()?;
```

I  know that it has to be `col` instead of `cols`. But `cols` generates a valid Expr, but it causes a panic. 

Can the panics [here](https://github.com/pola-rs/polars/blob/master/polars/polars-lazy/src/logical_plan/conversion.rs#L139) be an error instead?

**Comment by ritchie46** [comment]
Yes, it is a bit involved, because we only should error on the `collect` call. But if you find such a case, please open an issue, then we fix it.
