### ISSUE TITLE
Calculate Monday of week error in version v0.19.1

### ISSUE THREAD

**Issue by CHCP** [pola-rs/polars#3112]
Hi @ritchie46 
Calculate Monday of week error in version v0.19.1

Are you using Python or Rust?
Rust

Which feature gates did you use?
"lazy", "temporal", "dynamic_groupby", "simd", "dtype-datetime", "csv-file"

What version of polars are you using?
0.19.1

What operating system are you using polars on?
Ubuntu 20

Describe your bug.
Monday of week calculation error

What are the steps to reproduce the behavior?
Calculate week data from csv file, the dataset:
```
-----s------u--------------------c------a-----v----
AUDCAD,20210319 00:00:00.000,0.86277,0.87381,42
AUDCAD,20210319 00:00:01.000,0.87441,0.87381,0
AUDCAD,20210319 00:00:02.000,0.85982,0.87381,0
AUDCAD,20210319 00:00:03.000,0.87381,0.87381,0
AUDCAD,20210320 00:00:00.000,0.84996,0.86254,40
AUDCAD,20210320 00:00:01.000,0.86616,0.86254,0
AUDCAD,20210320 00:00:02.000,0.84738,0.86254,0
AUDCAD,20210320 00:00:03.000,0.86254,0.86254,0
AUDCAD,20210321 00:00:00.000,0.86151,0.84549,46
AUDCAD,20210321 00:00:01.000,0.86885,0.84549,0
AUDCAD,20210321 00:00:02.000,0.84498,0.84549,0
AUDCAD,20210321 00:00:03.000,0.84549,0.84549,0
AUDCAD,20220110 00:00:00.000,0.84561,0.84986,44
AUDCAD,20220110 00:00:01.000,0.85453,0.84986,0
AUDCAD,20220110 00:00:02.000,0.83658,0.84986,0
AUDCAD,20220110 00:00:03.000,0.89986,0.84986,0
```

My code is:
```
    let df_ohlc = df
        .lazy()
        .groupby_dynamic(
            vec![],
            DynamicGroupOptions {
                index_column: "u".into(),
                every: Duration::parse("1w"),
                period: Duration::parse("1w"),
                offset: Duration::parse("0w"),
                truncate: true,                     
                include_boundaries: false,         
                closed_window: ClosedWindow::Left,  
        })
        .agg([col("c").first()])
        .collect()
        .unwrap();
```

The result:
```
┌─────────────────────┬────────┐
│ u                   ┆ c      │
│ ---                 ┆ ---    │
│ datetime[ms]        ┆ f32    │
╞═════════════════════╪════════╡
│ 2022-03-18 00:00:00 ┆ 0.8627 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-01-06 00:00:00 ┆ 0.8456 │
└─────────────────────┴────────┘
```

But the correct result should be:
2021-03-15   //2021-03-15 is Monday, 2021-03-18 is Thursday
2022-01-10   //2021-01-10 is Monday, 2021-01-06 is Thursday

Am I setting the DynamicGroupOptions wrong somewhere?  Thanks for your help.

**Comment by ritchie46** [comment]
We don't guarantee a monday. Only a duration of `"1w"` e.g. 7 days. The first data point determines the start of this interval. If you want that the interval starts on another day, use the `offset`.

P.S. I would update, we had some bug fixes on the backing algorithms of groupby dynamic.

**Comment by CHCP** [comment]
Thanks a lot, I will test the ```offset```.

When I use Polars old version 0.13.0, the first day of week is Monday, so I think it would be better if the first day of week is Monday in latest version.

**Comment by CHCP** [comment]
@ritchie46 
  I tested with several `offset`, but I still can't get the Monday of week. 
```
DynamicGroupOptions {
                index_column: "u".into(),
                every: Duration::parse("1w"),
                period: Duration::parse("1w"),
                offset: Duration::parse("1d"), 
                //offset: Duration::parse("2d"),
                //offset: Duration::parse("3d"), 
                //offset: Duration::parse("4d"),
                //offset: Duration::parse("5d"), 
                //offset: Duration::parse("6d"),
```

May I know which revision had fixed "the backing algorithms of groupby dynamic"?  or is there a plan to fix it? Thank you.

**Comment by ritchie46** [comment]
Polars does not compute the day of the week. This is responsibility of the user. I will close this as this is never guaranteed by polars to be part of groupby dynamic.

**Comment by CHCP** [comment]
Hi @ritchie46 
 Thanks for reply.

 I will implement the Monday of week with Polars as end-user, I tested with many ways but failed, would you like to show how to implement this as end-user. Great Appreciated.
