### ISSUE TITLE
Support how='anti' and how='semi' in table joins.

### ISSUE THREAD

**Issue by bmschmidt** [pola-rs/polars#3131]
Thanks again for this library. Apologies if this feature exists and I am not seeing it.

An anti-join is a join between two tables that preserves only rows from the left table that are *not* matched in the right one. It is supported in [arquero](https://uwdata.github.io/arquero/api/verbs.html#antijoin) and [dplyr](https://dplyr.tidyverse.org/reference/filter-joins.html), though not in most SQLs where it's easy to write as a left join. A semi join is a filter on the left table by the columns of the right; neither can ever duplicate rows from the left table, making the semi-join slightly distinct from an INNER JOIN.

Anti-joins are especially useful, but a bit awkward in polars right now. 

For example, if I want to identify the domains in the left table here that are *not* matched in the right table, the way this is usually done in sql involves a lot of futzing with a dummy column name.

```py
import polars as pl
left = pl.DataFrame({'domain': ['foo.com', 'bar.com'], 'ip': ['255.100.100.102', '255.101.101.2']})
right = pl.DataFrame({'domain': ['foo.com']})
left.join(
   right.with_column(
     pl.col('domain').alias('dummy')
   ), on='domain', how='left')\
   .filter(pl.col('dummy').is_null())\
   .drop('dummy')
```

(Something like `left.filter(!pl.col('domain').is_in(right['domain']))` only works if the anijoin is on a single column.)

It would be nice to simply write this:

```py
import polars as pl
left = pl.DataFrame({'domain': ['foo.com', 'bar.com'], 'ip': ['255.100.100.102', '255.101.101.2']})
right = pl.DataFrame({'domain': ['foo.com']})
left.join(right, on='domain', how='anti')
```

**Comment by cnpryer** [comment]
Is this the same thing as a left/right outer join?

**Comment by bmschmidt** [comment]
Yeah in sql it would usually be something like:

```SQL
SELECT * FROM t1 LEFT JOIN t2 ON (t1.id=t2.id) WHERE t2.id IS NULL
```

but I don't know how to do anything that short in polars because you can't write the equivalent of `t2.id IS NULL.`, since the column is just called '`id`' by the time you can filter it.

**Comment by cbilot** [comment]
R’s venerable data.table package had the same concept, which was termed a “not” join

from the pdf for the [data.table](https://cran.r-project.org/web/packages/data.table/)   documentation
```R
DT[X, on="x"]  # right join
X[DT, on="x"]  # left join
DT[X, on="x", nomatch=NULL]  # inner join
DT[!X, on="x"]  # not join
```

I miss this feature.  I too have been using the “dummy null” workaround.

**Comment by cnpryer** [comment]
As for the filtering method, maybe something like this works for now
```py
left.filter(
    (~pl.col("domain").is_in(right["domain"])) & (~pl.col("other_col").is_in(right["other_col"]))
)
```

**Comment by cbilot** [comment]
> As for the filtering method, maybe something like this works for now
> 
> ```python
> left.filter(
>     (~pl.col("domain").is_in(right["domain"])) & (~pl.col("other_col").is_in(right["other_col"]))
> )
> ```

Actually, this logic will not work.  It may be helpful to look at an example.  Let's say we have this data:
```python3
import polars as pl

trials = pl.DataFrame(
    {
        "trial_nbr": ["a", "a", "b", "b", "c", "c", "d", "d"],
        "placebo": [0, 1] * 4,
    }
)
print(trials)
```
```
shape: (8, 2)
┌───────────┬─────────┐
│ trial_nbr ┆ placebo │
│ ---       ┆ ---     │
│ str       ┆ i64     │
╞═══════════╪═════════╡
│ a         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ a         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ b         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ b         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ c         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ c         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ d         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ d         ┆ 1       │
└───────────┴─────────┘
```

And let's say we want to exclude the following two rows:
```python3
exclusions = trials[[3, 4], :]
print(exclusions)
```
```
┌───────────┬─────────┐
│ trial_nbr ┆ placebo │
│ ---       ┆ ---     │
│ str       ┆ i64     │
╞═══════════╪═════════╡
│ b         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ c         ┆ 0       │
└───────────┴─────────┘
```

The "dummy null" method (for lack of a better term) correctly excludes these two rows:
```python3
rials.join(
    exclusions.with_column(pl.lit(True).alias("dummy")),
    on=["trial_nbr", "placebo"],
    how="left",
).filter(pl.col("dummy").is_null()).drop("dummy")
```
```
shape: (6, 2)
┌───────────┬─────────┐
│ trial_nbr ┆ placebo │
│ ---       ┆ ---     │
│ str       ┆ i64     │
╞═══════════╪═════════╡
│ a         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ a         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ b         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ c         ┆ 1       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ d         ┆ 0       │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ d         ┆ 1       │
└───────────┴─────────┘
```

However, the `is_in` filtering you're proposing produces the following:
```python3
trials.filter(
    (~pl.col("trial_nbr").is_in(exclusions["trial_nbr"]))
    & (~pl.col("placebo").is_in(exclusions["placebo"]))
)
```
```
shape: (0, 2)
┌───────────┬─────────┐
│ trial_nbr ┆ placebo │
│ ---       ┆ ---     │
│ str       ┆ i64     │
╞═══════════╪═════════╡
└───────────┴─────────┘
```
Of course, I've purposely constructed the example to show a stark difference.  But depending on the scenario, the result might seem reasonable without careful inspection.

**Comment by cnpryer** [comment]
hmm maybe there's something I'm misunderstanding. this seems to work
```py
# %%
import polars as pl
import numpy as np


left = pl.DataFrame({"a": [1, 2, 3], "b": [1, 2, 3]})
right = pl.DataFrame({"a": [1], "b": [1]})

# %%
left.filter(
    (~pl.col("a").is_in(right["a"])) & (~pl.col("b").is_in(right["b"]))
)
```
<html>
<body>


a | b
-- | --
i64 | i64
2 | 2
3 | 3


</body>
</html>

**Comment by cbilot** [comment]
Try this (which isn't a row):
```python3
right = pl.DataFrame({"a": [1], "b": [2]})

left.filter(
    (~pl.col("a").is_in(right["a"])) & (~pl.col("b").is_in(right["b"]))
)
```
```
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 3   ┆ 3   │
└─────┴─────┘
```

**Comment by cnpryer** [comment]
Ah duh. Makes sense.

**Comment by cbilot** [comment]
Looking at code (and thinking back through past work assignments), I have seen this pattern a lot:
```python3
key_fields = ['key1', 'key2', ...]
header_records.join(
    transactions.filter(<<something>>).select(key_fields).unique(),
    on = key_fields,
    how = 'inner'
)
```
... whether I expressed this in Polars or in R's data.table or SAS.  I just never knew there was a name for this pattern.

And how **elegant** a `semi` join would be to express succintly: "Which car warranties had one or more repairs?"  "Which voter records represent someone who voted at any time in the last four years?".  "Which insurance policies had one or more claims over $1 million?"

I've always just coded these constructs manually: filtering transactions, then selecting only key fields, then de-dup'ing, then joining.

I don't think R's data.table package has an explicit option.  And I'm pretty sure SAS didn't.  Perhaps that's why I never knew there was a name for it.

**Comment by bmschmidt** [comment]
Beside the R and JS libraries I mentioned above, it seems like the core Apache Arrow C++ libraries do now support both [right and left semijoins and antijoins](https://arrow.apache.org/docs/cpp/api/compute.html?highlight=join#_CPPv4N5arrow7compute8JoinTypeE). Pyarrow hasn't yet wrapped the operations, though--I assume that will come with Arrow 8.0.

**Comment by Dandandan** [comment]
FYI, DataFusion also supports anti/semi joins.

**Comment by ritchie46** [comment]
Seems like a good addition. I expect to take a look in the coming weeks.

**Comment by ritchie46** [comment]
Al right. #3149 adds SEMI and ANTI joins. They should be faster than existing joins because we have to do far less work. I did not know about them either, but now that I do, they seem very nice for filtering operations indeed. Thanks for the tip!

**Comment by bmschmidt** [comment]
Thank you!
