### ISSUE TITLE
How to use Schema in latest version 0.20.0

### ISSUE THREAD

**Issue by CHCP** [pola-rs/polars#3132]
Hi @ritchie46
How to use Schema in latest version 0.20.0

Are you using Python or Rust?
Rust

Which feature gates did you use?
"lazy", "temporal", "dynamic_groupby", "simd", "dtype-datetime", "csv-file"

What version of polars are you using?
0.20.0

What operating system are you using polars on?
Ubuntu 20

Describe your bug.
I use Schema in version 0.19.1 like this: 
```
pub fn get_schema() -> Schema {
    Schema::new(vec![
        Field::new("s", DataType::Utf8),
        Field::new("u", DataType::Utf8),
        Field::new("c", DataType::Float32),
        Field::new("a", DataType::Float32),
        Field::new("v", DataType::Int64),
    ])
}
```

When I upgrade to 0.20.0, the Schema api changed, I use it like this:
```
pub fn get_schema() -> Schema {
    let schema = Schema::with_capacity(5);
    schema.insert_index(0, "s".to_string(), DataType::Utf8);
    schema.insert_index(1, "u".to_string(), DataType::Utf8);
    schema.insert_index(2, "c".to_string(), DataType::Float32);
    schema.insert_index(3, "a".to_string(), DataType::Float32);
    schema.insert_index(4, "v".to_string(), DataType::Int64);

    schema
}
```

But it didn't work, I think the api usage maybe be wrong.  I didn't find any examples, Can you please give some examples for Schema 0.20.0, thank you very much.

**Comment by ritchie46** [comment]
`From` is implemented for `Schema`. So replace `new` with `from` and your good to go.

**Comment by CHCP** [comment]
Yes, it is works, thank a lot.
