### ISSUE TITLE
Map function over column has inconsistent result

### ISSUE THREAD

**Issue by peascod206** [pola-rs/polars#3140]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.11

#### What version of talib are you using?

0.4.24 (https://github.com/mrjbq7/ta-lib)

#### What operating system are you using polars on?

Windows 10

#### What language version are you using
python 3.9.7

#### Describe your bug.

I am trying to call the ta-lib KAMA moving average function to each stock's price by using Polars' map method together with the over statement.  The moving average result is different from call the moving average function to each of the stock price seperately. 

#### What are the steps to reproduce the behavior?

Here is the sample code to reproduce the issue

```
import polars as pl
import tallib

# Construct the sample polars dataframe
bb = pl.DataFrame({
    "ticker":["a"]*8 + ["b"]*8,
    "price":list(range(1, 17))
})

# Method 1: use map together with over to apply the KAMA moving average to each ticker
bb1 = bb.select([
    pl.col("ticker"),
    pl.col("price"),
    pl.col("price").map(lambda x: talib.KAMA(x, 5)).over("ticker").alias("MAvg")
])

# Method 2: Use filter to apply the KAMA moving average to the b group only.
bb2 = bb.filter(pl.col("ticker")=="b").select([
    pl.col("ticker"),
    pl.col("price"),
    pl.col("price").map(lambda x: talib.KAMA(x, 5)).alias("MAvg")
])
```
bb1 and bb2 have different KAMA moving average result for the ticker b group.
bb1 has the result of 
```
bb1.filter(pl.col("ticker")=="b")

ticker	price	MAvg
str	i64	f64
"b"	9	7.869075
"b"	10	8.816153
"b"	11	9.786751
"b"	12	10.770417
"b"	13	11.761343
"b"	14	12.756302
"b"	15	13.753501
"b"	16	14.751945
```
bb2 has the result of
```
ticker	price	MAvg
str	i64	f64
"b"	9	NaN
"b"	10	NaN
"b"	11	NaN
"b"	12	NaN
"b"	13	NaN
"b"	14	13.444444
"b"	15	14.135802
"b"	16	14.964335
```
#### What is the expected behavior?
bb2 looks like a normal moving average behavior, where the first 5 elements have been skipped to give the correct moving average result.  bb1's result is actually a continuous KAMA moving average mixing all the price of ticker a and ticker b.  This can be seen by checking the content of bb1.
```
ticker	price	MAvg
str	i64	f64
"a"	1	NaN
"a"	2	NaN
"a"	3	NaN
"a"	4	NaN
"a"	5	NaN
"a"	6	5.444444
"a"	7	6.135802
"a"	8	6.964335
"b"	9	7.869075
"b"	10	8.816153
"b"	11	9.786751
"b"	12	10.770417
"b"	13	11.761343
"b"	14	12.756302
"b"	15	13.753501
"b"	16	14.751945
```

#### What do you think polars should have done?
The moving average function calling through map method with over statement, should give consistent result as applying the moving average function to a single group.

**Comment by ritchie46** [comment]
Can you first update polars and see if the bug persist?

**Comment by peascod206** [comment]
Thank you @ritchie46 .

I understand the latest version should be 0.20.0 but I could only see 0.13.22 using pip.
```
C:\Windows\system32> pip3 install polars==0.20.0
ERROR: Could not find a version that satisfies the requirement polars==0.30 (from versions: 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6b1, 0.7.6b2, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10b1, 0.7.11, 0.7.12, 0.7.13, 0.7.14, 0.7.15, 0.7.16, 0.7.17, 0.7.18, 0.7.19, 0.8.0b1, 0.8.0b2, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.8, 0.8.9, 0.8.10, 0.8.11b1, 0.8.11, 0.8.12, 0.8.13b1, 0.8.14, 0.8.15b1, 0.8.15, 0.8.16, 0.8.17, 0.8.18, 0.8.19, 0.8.20, 0.8.21b1, 0.8.21b2, 0.8.21, 0.8.22b1, 0.8.22, 0.8.23, 0.8.24, 0.8.25, 0.8.26, 0.8.27b1, 0.8.27b2, 0.8.27, 0.8.28, 0.8.29, 0.9.0b1, 0.9.0b2, 0.9.0, 0.9.1, 0.9.2, 0.9.3b1, 0.9.3, 0.9.4, 0.9.5b1, 0.9.5, 0.9.6b1, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.12, 0.10.13, 0.10.14, 0.10.15, 0.10.16, 0.10.17, 0.10.18, 0.10.19, 0.10.20, 0.10.21, 0.10.22, 0.10.23, 0.10.24, 0.10.25, 0.10.26, 0.10.27, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.12.12, 0.12.13, 0.12.14, 0.12.15, 0.12.16, 0.12.17, 0.12.18, 0.12.19, 0.12.20, 0.12.21, 0.12.22, 0.12.23, 0.12.24, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.10, 0.13.11, 0.13.12, 0.13.13, 0.13.14, 0.13.15, 0.13.16, 0.13.17, 0.13.18, 0.13.19, 0.13.20, 0.13.21, 0.13.22)
```
I then upgraded my polars to 0.13.22.  This version however still has the same behavior.  

Should I upgrade to 0.20.0 to solve this problem?  If this is the case, appreciate if you could advise how I could get this version. 

Thanks

**Comment by ritchie46** [comment]
Over is a window function which aggregates over groups. If you do an operation that needs context within a group, not elementwise, you must use `apply` and not `map`.

**Comment by peascod206** [comment]
Thanks @ritchie46 .  ```apply``` does work like a charm. 
Two more related questions regarding this one:
1.  Is it possible to define KAMA function like a Polars expression and then call this expression within select?  Something like this:
```
def kama() -> pl.Expr:
    return talib.KAMA(pl.col("price"), 5)

bb1 = bb.select([
    pl.col("ticker"),
    pl.col("price"),
    kama().over("ticker").alias("MAvg")
])
```
I tried this method but couldn't get this work. 

2.  How to deal with talib function that returns a tuple?
Some talib functions return a tuple.  For now, I used the following method to wrap this tuple into a two series.
```
bb3 = bb.filter(pl.col("ticker")=="b").select([
    pl.col("ticker"),
    pl.col("price").map(lambda x: (talib.MAMA(x))[0]).alias("mama"),
    pl.col("price").map(lambda x: (talib.MAMA(x))[1]).alias("fama")
])
```
Just wonder if there is other way to call this kind of function once but return two series. 

Thanks again for your help.

**Comment by ritchie46** [comment]
You can use wrap the `Series` in a struct type.

```python
pl.select(pl.struct([pl.Series([1, 2, 3]), pl.Series(["a", "b", "c"])])).to_series()
```

```
shape: (3,)
Series: '' [struct[2]{'': i64, '': str}]
[
	{1,"a"}
	{2,"b"}
	{3,"c"}
]
```

I am closing this for now, because there are no action points we have to take.

Note that I will come with an additional PR to create a struct eagerly.

**Comment by ritchie46** [comment]
See: #3161

**Comment by peascod206** [comment]
@ritchie46 Many thanks for your help!
