### ISSUE TITLE
Python sub-process gets stucked when parent uses reading funcs

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#3144]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.22

#### What operating system are you using polars on?

Ubuntu 20.04

#### What language version are you using

python 3.10.04

#### Describe your bug.

Sub-process gets stucked when parent process uses reading feature of polars (e.g. read_parquet, scan_parquet)

#### What are the steps to reproduce the behavior?

```python
import multiprocessing

import polars as pl


def test_sub_process(data: pl.DataFrame):
    xdata = data.lazy().filter(pl.col('a') > 0).collect()
    print("Filtered")


test_df = pl.DataFrame(
    {
        "a": [0, 2, 3, 4, 5],
        "b": [0, 4, 5, 56, 4]
    }
)
test_df.write_parquet("/tmp/test.parquet")
test_df = pl.scan_parquet(
    "/tmp/test.parquet",
).collect()
proc = multiprocessing.Process(target=test_sub_process,
                               args=(
                                   test_df,
                               ))
proc.start()
proc.join()
print("Executed sub process")
```

#### What is the actual behavior?

Sub-process gets stucked and never return to python code

#### What is the expected behavior?

Printed out messages

**Comment by ghuls** [comment]
It might be a general python problem releated to forking:
https://pythonspeed.com/articles/python-multiprocessing/

**Comment by ghuls** [comment]
With Process `spawn` it works:

https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

```python
import multiprocessing

import polars as pl


def test_sub_process(df: pl.DataFrame, job_id):
    df_filtered = df.lazy().filter(pl.col('a') > 0).collect()
    print(f"Filtered (job_id: {job_id})", df_filtered, sep="\n")


def create_dataset():
    print("Create dataset")

    test_df = pl.DataFrame(
        {
            "a": [0, 2, 3, 4, 5],
            "b": [0, 4, 5, 56, 4]
        }
    )
    test_df.write_parquet("/tmp/test.parquet")


def main():
    create_dataset()

    print("Read dataset")
    test_df = pl.scan_parquet(
        "/tmp/test.parquet",
    ).collect()

    for i in range(0, 5):
        proc = multiprocessing.get_context('spawn').Process(
            target=test_sub_process,
            args=(test_df, i)
        )
        proc.start()
        proc.join()

        print(f"Executed sub process {i}")


if __name__ == '__main__':
    main()
```

**Comment by zundertj** [comment]
Closing as this is a Python (documentation) issue, as explained in the PythonSpeed article, not a Polars issue.

**Comment by ritchie46** [comment]
May I ask why you want to do this in the first place? Polars is very good in thread utilization.

**Comment by ritchie46** [comment]
If you load the data with polars, then there is not much benefit as polars already uses all threads. You can also use `pl.collect_all()` which executes all lazy plans in parallel.

**Comment by ritchie46** [comment]
Multiprocessing is only possible in `spawned` processes. As @ghuls referred blog post shows: https://pythonspeed.com/articles/python-multiprocessing/.

This can only be solved by stopping polars from multi-threading, which is entirely out of the scope of polars. 
So to any readers of this thread that want to do multi-processing in python AND multi-threading in polars, spawn your processes.

**Comment by ghuls** [comment]
Quoting the relevant part from the article I linked before: https://pythonspeed.com/articles/python-multiprocessing/
> ### The real solution: stop plain fork()ing
> 
> In Python 3 the multiprocessing library added new ways of starting subprocesses. One of these does a fork() followed by an execve() of a completely new Python process. That solves our problem, because module state isn’t inherited by child processes: it starts from scratch.
> 
> Enabling this alternate configuration requires changing just two lines of code in your program before any other import or usage of multiprocessing; basically, the very first thing your application does should be:
> 
> ```
> from multiprocessing import set_start_method
> set_start_method("spawn")
> ```
> 
> That changes things globally for all code in your program, so if you’re maintaining a library the polite thing to do is use the “spawn” method just for your own pools, like this:
> 
> ```
> from multiprocessing import get_context
> 
> def your_func():
>     with get_context("spawn").Pool() as pool:
>         # ... everything else is unchanged
> ```

**Comment by ritchie46** [comment]
> @ritchie46, thanks for the response. Understood -- but for my own edification, how do `numpy` and `pandas` avoid deadlocking when using `fork` for spawning subprocesses in python?

They almost don't use multi-threading.

Note this comment in the python documentation on fork:

 >The parent process uses [os.fork()](https://docs.python.org/3/library/os.html#os.fork) to fork the Python interpreter. The child process, when it begins, is effectively identical to the parent process. All resources of the parent are inherited by the child process. Note that safely forking a multithreaded process is problematic.
 
 *Note that safely forking a multithreaded process is problematic.*

**Comment by zundertj** [comment]
I think it would be useful to put this in the user guide, so I have, with the input in this thread and several other resources, compiled a page https://github.com/pola-rs/polars-book/pull/197. Once merged, we can point refer to that page. In case something is off in my explanation, please comment on that PR.

**Comment by ritchie46** [comment]
I will close this as I think we have provided info on the topic and #5237 will check for proper multiprocessing settings.
