### ISSUE TITLE
Construct `DataFrame` with struct column from python dictionary

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3145]
`pl.from_dict` and `pl.from_dicts` currently do not support creating a `DataFrame` with a struct column when provided with a python object consisting of nested dictionaries. In fact, the behavior appears to be different between the two. `from_dict` creates an `object`-type column whereas `from_dicts` throws an error:
```
>>> pl.from_dict({"a": [{"b": 1}]})
shape: (1, 1)
┌──────────┐
│ a        │
│ ---      │
│ object   │
╞══════════╡
│ {'b': 1} │
└──────────┘
>>> pl.from_dicts([{"a": {"b": 1}}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vadmin/.venv-dev/lib/python3.10/site-packages/polars/convert.py", line 144, in from_dicts
    return DataFrame._from_dicts(dicts)
  File "/home/vadmin/.venv-dev/lib/python3.10/site-packages/polars/internals/frame.py", line 356, in _from_dicts
    pydf = PyDataFrame.read_dicts(data)
RuntimeError: BindingsError: "row type not supported {'b': 1}"
```
It would be convenient for both of the above to produce a DataFrame equivalent to the following, containing a struct column:
```
>>> pl.from_dict({"a": pl.from_dict({"b": [1]}).to_struct("b")})
shape: (1, 1)
┌────────────────┐
│ a              │
│ ---            │
│ struct{b: i64} │
╞════════════════╡
│ {1}            │
└────────────────┘
```
I've found that using pandas as an intermediary makes this convenience possible at the present:
```
>>> pl.from_pandas(pd.DataFrame([{"a": {"b": 1}}]))
```
Would it be possible to support this behavior, either by default or via a configurable parameter in `from_dict`/`from_dicts`?

**Comment by zundertj** [comment]
I mocked up a Python-only implementation at https://github.com/pola-rs/polars/pull/3162 for `pl.from_dict`. `pl.from_dicts` would be more difficult.

Please note that your first input `data` is confusing, as it mixes syntax for `pl.from_dict` and `pl.from_dicts`: the outer value is a dict of sequences, the inner a sequence of dicts. If we support this, lets at least support a sane structruce: either both are dict of sequences (`pl.from_dict`), or sequence of dicts (`pl.from_dicts`). See the PR with a test for how I think the syntax should be.

Not sure we should merge this, the performance hit could be large when there are many columns to check.

**Comment by physinet** [comment]
Thanks @zundertj for diving in and raising the issue with my example for `pl.from_dict`. Initially I wanted to try to keep the outermost values as sequences, but I see that would require switching to `pl.from_dicts` when walking recursively through the object. Having all values as dicts of sequences makes sense to me now: `pl.from_dict({"a": {"b": [1]}})`.

I see #3162 was merged already. Looks great! Hope the performance doesn't become a concern.

As for `pl.from_dicts`, also agreed that it seems more difficult. One clumsy option might be to translate the data into the dict of sequence format and use `pl.from_dict`.

Is it necessary to implement this all on the Python side? Are there any opportunities to support this on the Rust side?
