### ISSUE TITLE
CsvReader failed when read a csv file that include space separators.

### ISSUE THREAD

**Issue by CHCP** [pola-rs/polars#3147]
Hi @ritchie46 

Are you using Python or Rust?
Rust

Which feature gates did you use?
"lazy", "temporal", "dynamic_groupby", "simd", "dtype-datetime", "fmt", "csv-file"

What version of polars are you using?
0.20.0

What operating system are you using polars on?
Ubuntu 20

Describe your bug.
CsvReader failed when read a csv file that include space separator.

What are the steps to reproduce the behavior?
My code:
```
pub fn get_schema() -> Schema {
    Schema::from(vec![
        Field::new("s", DataType::Utf8),
        Field::new("u", DataType::Utf8),
        Field::new("c", DataType::Float32),
        Field::new("a", DataType::Float32),
        Field::new("v", DataType::Int64),
    ])
}

pub fn main() {
...
                df_result = CsvReader::new(df_file)
                    .with_schema(&Arc::new(get_schema()))
                    .has_header(false)
                    .finish();
...
```

Csv file without space separators, the csv file can be read by CsvReader:
```
AUDCAD,20220111 07:04:20.746,0.95212,0.95551,2
AUDCAD,20220111 07:04:40.746,0.96212,0.94552,2
AUDCAD,20220111 07:06:20.746,0.94212,0.93553,2
AUDCAD,20220111 07:07:20.746,0.93212,0.92554,2
```

But if there are space separators in csv file like follows(a csv file can include space separators), the CsvReader will failed:
```
AUDCAD, 20220111 07:04:20.746, 0.95212, 0.95551, 2
AUDCAD, 20220111 07:04:40.746, 0.96212, 0.94552, 2
AUDCAD, 20220111 07:06:20.746, 0.94212, 0.93553, 2
AUDCAD, 20220111 07:07:20.746, 0.93212, 0.92554, 2
```

error message:
```
2022-04-15T15:23:37.064442400+10:00 ERROR Generate data frame from tick_date csv file failed:  error= Could not parse  0.95212 as dtype Float32 at column 3.
                                            The total offset in the file is 30 bytes.

                                            Consider running the parser `with_ignore_parser_errors=true`
                                            or consider adding  0.95212 to the `null_values` list.
```

How to support space separator in csv files? Can you please have a look at this? Thank you.

**Comment by ritchie46** [comment]
You must specify the delimiter. Polars cannot know that you have a csv file with a space delemiter.

**Comment by CHCP** [comment]
But the old version 0.13.3 can process a csv file that with or without a space delimiter both, I think maybe something changed in new version 0.20.0?

**Comment by ghuls** [comment]
The python wrapper works fine with that file:
```python
In [9]: pl.read_csv("comma_and_space.csv", has_header=False, sep=",")
Out[9]:
shape: (4, 5)
┌──────────┬────────────────────────┬──────────┬──────────┬──────────┐
│ column_1 ┆ column_2               ┆ column_3 ┆ column_4 ┆ column_5 │
│ ---      ┆ ---                    ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ str                    ┆ f64      ┆ f64      ┆ i64      │
╞══════════╪════════════════════════╪══════════╪══════════╪══════════╡
│ AUDCAD   ┆  20220111 07:04:20.746 ┆ 0.95212  ┆ 0.95551  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:04:40.746 ┆ 0.96212  ┆ 0.94552  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:06:20.746 ┆ 0.94212  ┆ 0.93553  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:07:20.746 ┆ 0.93212  ┆ 0.92554  ┆ 2        │
└──────────┴────────────────────────┴──────────┴──────────┴──────────┘
```

Which calls `read_csv` in `py-polars/src/dataframe.rs`

**Comment by CHCP** [comment]
Thanks  @ghuls 
 There is a space delimiter after `,`,   like this `, `,    I am not sure if python wrapper still works?

**Comment by ghuls** [comment]
It does for me:
```python
In [11]: ! cat comma_and_space.csv
AUDCAD, 20220111 07:04:20.746, 0.95212, 0.95551, 2
AUDCAD, 20220111 07:04:40.746, 0.96212, 0.94552, 2
AUDCAD, 20220111 07:06:20.746, 0.94212, 0.93553, 2
AUDCAD, 20220111 07:07:20.746, 0.93212, 0.92554, 2

In [12]: pl.read_csv("comma_and_space.csv", has_header=False, sep=",")
Out[12]:
shape: (4, 5)
┌──────────┬────────────────────────┬──────────┬──────────┬──────────┐
│ column_1 ┆ column_2               ┆ column_3 ┆ column_4 ┆ column_5 │
│ ---      ┆ ---                    ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ str                    ┆ f64      ┆ f64      ┆ i64      │
╞══════════╪════════════════════════╪══════════╪══════════╪══════════╡
│ AUDCAD   ┆  20220111 07:04:20.746 ┆ 0.95212  ┆ 0.95551  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:04:40.746 ┆ 0.96212  ┆ 0.94552  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:06:20.746 ┆ 0.94212  ┆ 0.93553  ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ AUDCAD   ┆  20220111 07:07:20.746 ┆ 0.93212  ┆ 0.92554  ┆ 2        │
└──────────┴────────────────────────┴──────────┴──────────┴──────────┘
```

**Comment by CHCP** [comment]
Cool.
 But it does not work in Rust Polars v0.20.0.

**Comment by CHCP** [comment]
Hi @ritchie46  
  Is there any plan to support csv file with or without 'Space Separator'?  There both are legal csv file format. Thank you.

Without Space Separator:
```
AUDCAD,20220111 07:04:20.746,0.95212,0.95551,2
AUDCAD,20220111 07:04:40.746,0.96212,0.94552,2
```

With Space Separator:
```
AUDCAD, 20220111 07:04:20.746, 0.95212, 0.95551, 2
AUDCAD, 20220111 07:04:40.746, 0.96212, 0.94552, 2
```

**Comment by cnpryer** [comment]
Did you try [this](https://github.com/pola-rs/polars/issues/3147#issuecomment-1099915225)?

**Comment by CHCP** [comment]
yes, I try with:
```
df_result = CsvReader::new(df_file)
                    .with_schema(&Arc::new(get_schema()))
                    .with_delimiter(b',')
                    .has_header(false)
                    .finish();
```

But it does not work.

**Comment by cnpryer** [comment]
What about `, `?

**Comment by CHCP** [comment]
In fun with_delimiter(delimiter: u8), the argument delimiter is u8, can't set  ```,  ```, so it does not work.

**Comment by ritchie46** [comment]
That's not a space delimited file. That's a comma AND space delimited file.

Polars will never support delimiters more than a single byte.

You can use a sanitizer to clean your csv files to a standard format.

**Comment by CHCP** [comment]
@ritchie46  
Yes, you are right, it is a comma and space delimit in my csv files.

I will clean csv files to a standard format. Thanks for your help.

**Comment by ghuls** [comment]
I think polars supports parsing those fields as it will retry if the fields starts with a space.
https://github.com/pola-rs/polars/blob/master/polars/polars-io/src/csv_core/buffer.rs#L65-L107

Added on March 23: https://github.com/pola-rs/polars/commit/af61de0563390d12a211480655f93d2abe4454a0

But it will not be the the rust crate yet.

So use the git version, if you need support for this, till the crate is updated.

**Comment by CHCP** [comment]
Thanks @ghuls 
I tested github revision after [`af61de0`](https://github.com/pola-rs/polars/commit/af61de0563390d12a211480655f93d2abe4454a0),  it is allows a comma and space delimit in csv files, but in crates version [`0.20.0`](https://crates.io/crates/polars/0.20.0), it does not.

So I am waiting for new crates version that Polars will support a comma and space delimit in csv files, and no need to clean csv files to a standard format.

Thanks for your reminder.

**Comment by ritchie46** [comment]
I will close this, as this has been fixed. The new polars release will be able to parse the file. You could use master if you need the functionality earlier.
