### ISSUE TITLE
discrepancy between `pl.col()` and `df.select()`when using multiple columns

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#3150]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.21

#### Describe your bug.

When attempting to use `pl.col()` to perform operations on multiple columns (i.e. dataframe operations), it does not work as expected, whereas the same thing works when using `df.select()`

#### What are the steps to reproduce the behavior?

```python
import polars as pl

iris = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
)  # download sample data

print(
    iris.with_column(
        iris.select(["sepal_length", "sepal_width"]).max(axis=1).alias("max")
    )
) # works
print(
    iris.with_column(pl.col(["sepal_length", "sepal_width"]).max(axis=1).alias("max"))
) # fails
```

**Comment by ritchie46** [comment]
You are comparing operations on different data structures/concepts. One being a `DataFrame` and the other on expressions. 

Expression rules don't apply to any arbitrary method on a DataFrame or vice versa. 

If you want to determine the maximum on expressions, you can use the `max` expression or use the `fold` expression.

```python
iris.select([
    pl.max(["sepal_length", "sepal_width"]).alias("max_1"),
    pl.fold(int(-1e9), lambda a, b: pl.max([a, b]), ["sepal_length", "sepal_width"]).alias("max_2"),
])
```

**Comment by cbilot** [comment]
These links might help: 
* The max method that applies to a DataFrame:  [`polars.DataFrame.max`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.max.html#polars.DataFrame.max).   This method has an `axis=` keyword.

* The max function that starts an expression: [`polars.max`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.max.html)

* The max function that can be chained to an existing expression: [`polars.Expr.max`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.max.html)

**Comment by DrMaphuse** [comment]
I didn't  expect them to be the same, honestly, but I was unclear on how to get the maximum across a subset of columns.
`pl.max()` seems to be what I was looking for - thanks.

**Comment by cbilot** [comment]
FYI, like `polars.max`, `sum`,`any`, `all`, and `min` can be used to sum across columns (or even arbitrary expressions).  These are really handy.
