### ISSUE TITLE
pl.read_csv(..., n_rows=10) with a large gzipped file is 1000x slower than pandas

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#3166]
I tried reading the first 10 rows of [this 720 MB gzipped CSV](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90027001-GCST90028000/GCST90027158/GCST90027158_buildGRCh38.tsv.gz) with polars and pandas. Polars is over 1000x slower than pandas:

```
>>> from timeit import timeit
>>> timeit(lambda: pl.read_csv('sumstats/GCST90027158_buildGRCh38.tsv.gz', sep='\t', n_rows=10), number=1)
17.688312217593193
>>> timeit(lambda: pd.read_table('sumstats/GCST90027158_buildGRCh38.tsv.gz', nrows=10), number=1)
0.015716226771473885
```
Reading the entire file with polars is only marginally slower (and several times faster than pandas; this is on a machine with 12 cores):
```
>>> timeit(lambda: pl.read_csv('GCST90027158_buildGRCh38.tsv.gz', sep='\t'), number=1)
21.39413799531758
>>> timeit(lambda: pd.read_table('sumstats/GCST90027158_buildGRCh38.tsv.gz'), number=1)
77.72320617455989
```
I'm guessing polars is decompressing the entire file before reading the first 10 rows?

**Comment by ritchie46** [comment]
Yeah, we decompress the whole file in-memory. Current design is not really suitable to chunk this. Might rethink this later.

**Comment by jorgecarleitao** [comment]
I am always amazed how CSV is (ab)used to store Gb-worth of data. I haven't tested, but I would expect the file to be much faster to load if it was written in a arrow/feather file, and likely smaller.

**Comment by ghuls** [comment]
@jorgecarleitao In bioinformatics this is common (CSV/TSV/BED/VCF) files (last 3 are all TAB separated.

**Comment by Wainberg** [comment]
Yes, this is extremely standard in the genetics/bioinformatics field, for better or worse.

**Comment by fzyzcjy** [comment]
Hi, I wonder how to write a *compressed* csv? Thanks!

**Comment by ritchie46** [comment]
> Hi, I wonder how to write a _compressed_ csv? Thanks!

Use a compression library when the file is written.

**Comment by tzeitim** [comment]
> > Hi, I wonder how to write a _compressed_ csv? Thanks!


One option using pandas:
```
pl.DataFrame().to_pandas().to_csv('out_file.csv.gz', compression='gzip')
```

**Comment by balwierz** [comment]
I am facing the same problem 3 years later.
I need to read a 81GB (when gzipped!) txt file. Yes, it is bioinformatics and it is ridiculous.
