### ISSUE TITLE
Filtering on date differences - time unit issue

### ISSUE THREAD

**Issue by marcvanheerden** [pola-rs/polars#3171]
#### What language are you using?

Python

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### What version of polars are you using?
Python 0.13.23 

#### What operating system are you using polars on?
debian 11.3

#### What language version are you using
Python 3.9.7

#### Describe your bug.

Trying to filter rows by the difference between two dates but get unexpected comparisons due to different time units

#### What are the steps to reproduce the behavior?

My first attempt that errors out:
```
(pl.DataFrame({"year1": [2015, 2016],
              "month1": [1, 2],
              "day1": [1,2],
              "year2": [2015, 2016],
              "month2": [1, 3],
              "day2": [10,15]})
    .with_columns([pl.date("year1", "month1", "day1").alias("date1"),
                   pl.date("year2", "month2", "day2").alias("date2")])
    .with_column((pl.col("date2") - pl.col("date1")).alias("time_passed"))
    .filter(pl.col("time_passed") < pl.duration(days=pl.lit(30)))
)
```
Error:
```
SchemaMisMatch("Series dtype Duration(Milliseconds) != datetime")
```

My second attempt was this:
```
(pl.DataFrame({"year1": [2015, 2016],
              "month1": [1, 2],
              "day1": [1,2],
              "year2": [2015, 2016],
              "month2": [1, 3],
              "day2": [10,15]})
    .with_columns([pl.date("year1", "month1", "day1").alias("date1"),
                   pl.date("year2", "month2", "day2").alias("date2")])
    .with_column((pl.col("date2") - pl.col("date1")).alias("time_passed"))
    .with_column(pl.lit(30).alias("thirty"))
    .with_column(pl.duration(days="thirty").alias("gap"))
    .filter(pl.col("time_passed") < pl.col("gap"))
)
```
It doesn't throw any errors but incorrectly keeps the second row which should be filtered out.

My third attempt was this:
```
from datetime import date, timedelta

(pl.DataFrame({"year1": [2015, 2016],
              "month1": [1, 2],
              "day1": [1,2],
              "year2": [2015, 2016],
              "month2": [1, 3],
              "day2": [10,15]})
    .with_columns([pl.date("year1", "month1", "day1").alias("date1"),
                   pl.date("year2", "month2", "day2").alias("date2")])
    .with_column((pl.col("date2") - pl.col("date1")).alias("time_passed"))
    .filter(pl.col("time_passed") < timedelta(days=30))
)
```

which gives the same output as the second attempt.

#### What is the actual behavior?

in attempts 2 and 3 it looks like the 30 day period is made into duration[ns] while the time_passed column is made into duration[ms] which is causing the filtering to keep the second row which should be filtered out. 

#### What is the expected behavior?

I don't think attempts 2 and 3 should pass quietly as is, I think it should either
- coerce both sides to the same time unit
- error out and suggest the user align the time units
- give a warning that you are comparing two different time units

I would like to work on this unless you prefer to fix it yourself. 
Let me know if I can open a PR and which solution above you prefer

**Comment by ritchie46** [comment]
I agree we should coerce to the right time unit to fulfil the operation.

> I would like to work on this unless you prefer to fix it yourself.

Please :)
