### ISSUE TITLE
mean() produce wrong result for column less than Int32

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#3175]
Python 3.8, Ubuntu 20.04, polars 0.13.16

#### Describe your bug.
When subgroup in group by has more than 1024 rows, and type of grouped column less than Int32 (Int16, Int8), mean() produce wrong result. Maybe there are some other variants of this bug, but I faced just this one.

**Example**
```python
pl.DataFrame({
    'col1': ['A' for i in range(1025)],
    'col3': [64 for i in range(1025)],
}).select([
    pl.col('col1').cast(pl.Utf8),
    pl.col('col3').cast(pl.UInt16),
]).groupby(['col1']).agg(pl.col('col3').mean())
```

#### What is the actual behavior?

col1 | col3
-- | --
str | f64
"A" | 0.062439

#### What is the expected behavior?

col1 | col3
-- | --
str | f64
"A" | 64

**Comment by slonik-az** [comment]
I  might guess that `mean()` function computes the `sum` using the same type as the column (`UInt16`) and it overflows. Would be better to use rust `fold` and accumulate in `f64`. Might by the code already does it, I cannot check right now.

**Comment by s-b90** [comment]
It is not overflow in example below:
```python
pl.DataFrame({
    'col1': ['A' for i in range(1025)],
    'col3': [64 for i in range(1025)],
}).select([
    pl.col('col1').cast(pl.Utf8),
    pl.col('col3').cast(pl.UInt16),
]).groupby(['col1']).agg(pl.col('col3').sum())
```
it convers to int64


col1 | col3
-- | --
str | i64
"A" | 65600

But it is, when using UInt32. It keeps u32 and don't raise an error.
```python
pl.DataFrame({
    'col1': ['A' for i in range(1025)],
    'col3': [64 * 10 ** 6 for i in range(1025)],
}).select([
    pl.col('col1').cast(pl.Utf8),
    pl.col('col3').cast(pl.UInt32),
]).groupby(['col1']).agg(pl.col('col3').sum())
```


col1 | col3
-- | --
str | u32
"A" | 1175490560

So, sum() overflow it is possible issue but not for the provided example.

**Comment by ritchie46** [comment]
It is overflow. I will make sure we cast to floats for any of the smaller integers eg, 16 bits and downwards.
