### ISSUE TITLE
how to replace pandas df.rank(axis=1) with polars

### ISSUE THREAD

**Issue by davylaker** [pola-rs/polars#3184]
Alpha factors need section rank sometimes, like this:

import pandas as pd

df = pd.Dataframe(some_data)

df.rank(axis=1, pct=True)

how to implement this with polars efficiently?

[https://stackoverflow.com/questions/71920714/how-to-replace-pandas-df-rankaxis-1-with-polars](url)

**Comment by ritchie46** [comment]
Thanks.. I will come up with some changes to better facilitate this.

**Comment by ritchie46** [comment]
See #3185 

I will add an answer to the SO question, once we have released this.

**Comment by davylaker** [comment]
very nice ! I'll try wrapping rank funciton with the sample code

**Comment by ritchie46** [comment]
Answered.
