### ISSUE TITLE
`DataFrame.to_dict` and `DataFrame.to_dicts` should convert `Struct`/`List` to python dict/list

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3187]
When converting `DataFrame` objects to python, it would provide considerable convenience to have the returned objects consist only of python types. Furthermore, `to_dict` and `to_dicts` should be consistent with how they convert `Struct` types.

For instance, `to_dict` converts a `Struct` into a `Series` object, whereas `to_dicts` results in a tuple. Both convert `List` types into a `Series`:
```
>>> import polars as pl
>>> s = pl.DataFrame([{"b": 1}]).to_struct("a")
>>> l = pl.Series("c", [[1,2]])
>>> df = pl.DataFrame([s, l])
>>> df.to_dict()
{'a': shape: (1,)
Series: 'a' [struct{b: i64}]
[
	{1}
], 'c': shape: (1,)
Series: 'c' [list]
[
	[1, 2]
]}
>>> df.to_dicts()
[{'a': (1,), 'c': shape: (2,)
Series: '' [i64]
[
	1
	2
]}]
```
Both approaches are somewhat inconvenient if the user needs to further manipulate the python objects. These would be more convenient:
```
>>> df.to_dict()
{'a': {'b': [1]}, "c": [[1,2]]}
>>> df.to_dicts()
[{'a': {'b': 1}, "c": [1,2]}]
```
These outputs can be used to reconstruct the original DataFrame via pandas (and hopefully directly using polars after #3145 ):
```
>>> import pandas as pd
>>> pl.from_pandas(pd.DataFrame({'a': [{'b': 1}], "c": [[1,2]]}))  # note, slightly different format than expected from to_dict
>>> pl.from_pandas(pd.DataFrame([{'a': {'b': 1}, "c": [1,2]}]))
```
This could be a configurable parameter in `to_dict`/`to_dicts`, and I'd argue that it should be the default. Are there any common use cases for keeping polars types in the output to consider here?

**Comment by ritchie46** [comment]
Polars `to_dict` already has an argument that forces polars to materialize python objects.

I agree that `for_dicts` we still have to check the list/struct type.

**Comment by physinet** [comment]
Thanks for pointing out the argument in `to_dict`, sorry I missed it. For the example above,
```python
>>> df.to_dict(as_series=False)
{'a': [(1,)], 'c': [[1, 2]]}
```
This still returns a tuple for the struct rather than a dictionary. This could be configured via an additional argument:
```python
>>> df.to_dict(struct_as_dict=True)
{'a': [{'b': 1}], "c": [[1,2]]}
```
