### ISSUE TITLE
max() on a Series of datetimes returns float

### ISSUE THREAD

**Issue by tsh56** [pola-rs/polars#3188]
#### What language are you using?

**Python**

#### Which feature gates did you use?
NA

#### What version of polars are you using?
numpy==1.22.3
polars==0.13.23
pyarrow==7.0.0
typing_extensions==4.2.0

#### What operating system are you using polars on?
Ubuntu 20.04 using Python 3.10 from pyenv

#### What language version are you using
Python 3.10

#### Describe your bug.

I have a case where I have a dataframe which contains a column with a timestamp. When I compute the max timestamp against the series by accessing the column directly I get a numerical result. If I perform a max operation on the dataframe, the result is a datetime value. In both cases I would expect a datetime to be returned.

#### What are the steps to reproduce the behavior?
```
import datetime
import polars
data = {"timestamp": [datetime.datetime.utcnow(), datetime.datetime.utcnow() -
    datetime.timedelta(hours=1)]}

df = polars.DataFrame(data)

print(df.max()) # dataframe with a single row that contains a datetime
print(df.max()["timestamp"][0]) # this is a datetime
print(df["timestamp"].max()) # this is a float
```

#### What is the actual behavior?
Calling max on a series of type datetime returns a float.

#### What is the expected behavior?

I believe a datetime should be returned.

**Comment by ritchie46** [comment]
You are right @physinet. However, I think we can revisit this behavior as we currently have the backend code in place to do so elegantly.

Likeley nobody wants the physical representation when calling max. I will follow up on this.
