### ISSUE TITLE
Cannot create struct from timestamp field

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3189]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.23

#### What operating system are you using polars on?

macOS 12.2.1

#### What language version are you using
Python 3.10.3

#### Describe your bug.

Structs are not apparently able to be created from timestamp fields, either via `pl.struct` or `DataFrame.to_struct`.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import datetime
df = pl.DataFrame([{"timestamp": datetime.datetime(2022,1,1)}])
df.to_struct("struct")
```

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("The children DataTypes of a StructArray must equal the children data types. \n                         However, the field 0 has data type Timestamp(Millisecond, None) but the value has data type Int64")', /Users/brianschaefer/.cargo/git/checkouts/arrow2-945af624853845da/da703ae/src/array/struct_/mod.rs:123:52
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianschaefer/repos/polars/py-polars/polars/internals/frame.py", line 5176, in to_struct
    return pli.wrap_s(self._df.to_struct(name))
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("The children DataTypes of a StructArray must equal the children data types. \n                         However, the field 0 has data type Timestamp(Millisecond, None) but the value has data type Int64")
```

#### What is the expected behavior?

I would have expected a struct with inner field as a timestamp type. I had to convert to integer before I could put the column into a struct. Is it possible to cast the inner field to timestamp at this point?
```python
struct = pl.struct(pl.col("timestamp").cast(int)).alias("struct")
df.with_column(struct)
```

**Comment by cjermain** [comment]
There appears to be a mismatch in the values provided to `StructArray::new` in `fields_to_struct_array`.

https://github.com/pola-rs/polars/blob/8b2db30ac18d219f4c3d02e2d501d2966cf58930/polars/polars-core/src/chunked_array/logical/struct_/mod.rs#L38

The arrow2 field passed to `new_fields` has `data_type: Timestamp(Millisecond, None)`, while the `field_arrays` is an `Int64`. Although the logical-type of [`TimeStamp`](https://docs.rs/arrow2/0.10.1/arrow2/datatypes/enum.DataType.html#variant.Timestamp) is represented as an `Int64` physical-type, the mismatch appears to be causing the error. So I think the array reference needs to keep the Timestamp type, or arrow2 needs to be more forgiving about the logical type being passed.

@jorgecarleitao, @ritchie46, is this a bug in arrow2 or polars?

**Comment by ritchie46** [comment]
This is a bug in polars. In polars we only keep the physical types. But when we convert to arrow we must ensure we coerce to the right logical types. We forgot to do that in the snippet you shared.

**Comment by cjermain** [comment]
Thanks for fixing this. I woke up with realization of how to fix it and was glad to see your PR already did. :smile:

**Comment by cjermain** [comment]
Will there be a new Python release this week?

**Comment by ritchie46** [comment]
Yes!
