### ISSUE TITLE
Default Datetime parsing does not match common formats

### ISSUE THREAD

**Issue by lannybroo** [pola-rs/polars#3195]
#### What language are you using?

Python

#### What version of polars are you using?

Polars 0.13.19

#### What operating system are you using polars on?

macOS Monterey 12.3.1

#### What language version are you using

Python 3.9

#### Describe your bug.

A few common (close to ISO 8601) date/time string formats are not tried by `date_pattern` in `utf8.rs`: 
1. Times with fewer than 6 fractional second digits
2. Datetimes that match the ISO 8601 standard exactly

#### What are the steps to reproduce the behavior?

```
import polars as pl

df = pl.Series('date', 
                ['2018-09-05', 
                 '2018-09-05T04:05:01', 
                 '2018-09-05T04:24:01.9',
                 '2018-09-05T04:24:02.11',
                 '2018-09-05T14:24:02.123',
                 '2018-09-05T14:24:02.123Z',
                 '2019-04-18T02:45:55.555000000',
                 '2019-04-18T22:45:55.555123']).to_frame()
df.with_columns([
    col('date').str.strptime(pl.Datetime, fmt=None, strict=False).alias('parsed'),
])
```

#### What is the actual behavior?

```
date | parsed
-- | --
str | datetime
"2018-09-05" | 2018-09-05 00:00:00
"2018-09-05T04:05:01" | 2018-09-05 04:05:01
"2018-09-05T04:24:01.9" | null
"2018-09-05T04:24:02.11" | null
"2018-09-05T14:24:02.123" | null
"2018-09-05T14:24:02.123Z" | null
"2019-04-18T02:45:55.555000000" | 2019-04-18 02:45:55.555
"2019-04-18T22:45:55.555123" | 2019-04-18 22:45:55.555123
```

#### What is the expected behavior?

All of these cases should parse successfully as they are pretty common.

The 4 cases that did not parse can be parsed successfully by including `fmt='+'` (for the case ending in an ISO 8601 time zone like `Z`) and including `fmt='%FT%H:%M:%S%.f'` (for the three cases with fewer than 6 fractional digits). The fractional change is nice because it is more flexible than the current implementation in `date_pattern` which has `.%6f`.

Corrected outputs include:
```
df.with_columns([
    col('date').str.strptime(pl.Datetime, fmt='%+', strict=False).alias('parsed'),
])

date | parsed
-- | --
str | datetime
"2018-09-05T14:24:02.123Z" | 2018-09-05 14:24:02.123
```

and

```
df2.with_columns([
    col('date').str.strptime(pl.Datetime, fmt='%FT%H:%M:%S%.f', strict=False).alias('parsed'),
])


date | parsed
-- | --
str | datetime
"2018-09-05T04:05:01" | 2018-09-05 04:05:01
"2018-09-05T04:24:01.9" | 2018-09-05 04:24:01.900
"2018-09-05T04:24:02.11" | 2018-09-05 04:24:02.110
"2018-09-05T14:24:02.123" | 2018-09-05 14:24:02.123
```

**Comment by ritchie46** [comment]
Can you provide met the format strings you want added? I will add them.

**Comment by lannybroo** [comment]
I would suggest replacing the last format string in `date_pattern()` with `'%FT%H:%M:%S%.f'`. And then I would suggest adding format string `%+` as well.

**Comment by ritchie46** [comment]
Yeah, we won't be replacing it. We come with a native parser that does not support default strings formats but is stupid much faster than the one shipped in `chrono`.

If we cannot parse it natively we use `chrono's` so `"%FT%H:%M:%S%.f"` will be an addition as well ass `"%+"`.

**Comment by lannybroo** [comment]
That sounds great. I did not realize there was a native Polars parser also.
