### ISSUE TITLE
`pivot` returns wrong results

### ISSUE THREAD

**Issue by LVG77** [pola-rs/polars#3197]
#### What language are you using?

 **Python**

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### What version of polars are you using?

0.13.23

#### What operating system are you using polars on?

Linux

#### What language version are you using
python 3.9 

#### Describe your bug.

The `pivot` method returns wrong results. Please see the results from the following example:

```python
import pandas as pd
import polars as pl
import numpy as np

df_test = pl.DataFrame({'name': ['avg', 'avg', 'act', 'test', 'test'],
                        'err' : ['name1', 'name2', None, 'name1', 'name2'],
                        'wght': [0.0, 0.1, 1, 0.4, 0.2]})
df_test.pivot('wght', 'err', 'name', sort_columns=True)
```
![image](https://user-images.githubusercontent.com/16968156/164250115-2343f6e4-3911-4edc-86a6-91964de8b195.png)

The correct result should be:
```python
df_test_pd = df_test.to_pandas()
df_test_pd.pivot(values='wght', index='err', columns='name')
```
![image](https://user-images.githubusercontent.com/16968156/164250529-217e4f96-0921-4238-9176-8f79db3770fc.png)

Thank you again for building this wonderful library!

**Comment by ritchie46** [comment]
Thanks.. will fix this!
