### ISSUE TITLE
Confusing error with duplicate CSV columns

### ISSUE THREAD

**Issue by lannybroo** [pola-rs/polars#3201]
#### What language are you using?

Python

#### What version of polars are you using?

Polars 0.13.19

#### What operating system are you using polars on?

macOS Monterey 12.3.1

#### What language version are you using

Python 3.9

#### Describe your bug.

When using `pl.read_csv()` to parse an ill-formed CSV file with duplicate column names in the first row, a confusing error is shown. I think the parser silently reads the duplicate column and then is off by one with the data types so eventually fails on a later column when the data types don't match.

#### What are the steps to reproduce the behavior?

Here is a minimal example where the duplicate columns X1 and X1 end up creating an error about column G, which is 3 columns away from the duplicate. 

In real situations trying to use polars on a 1000+ column data set, it was difficult for me to realize that the actual trouble was a duplicate columns because the error referred to a column hundreds away from the actual problem.

```
import pandas as pd
import polars as pl
from io import StringIO  # to make a buffer instead of a temp file
csv_str = (
    'A,B,X1,X1,E,F,G,H\n'
    '2019,20.8,1,1,7,11,463.1070251,0\n'
    '2019,20.8,0,0,7,11,463.04422,-1\n'
    '2019,20.83,3,3,7,11,463.202301,7\n'
    '2019,20.83,0,0,7,11,463.202301,0\n'
    '2019,20.86,0,0,7,11,463.0957336,122\n'
    '2019,20.86,4,4,7,11,463.1209106,0\n'
    '2019,20.9,0,0,7,11,462.796936,0\n'
    '2019,20.9,0,0,7,11,463.1161804,0\n'
    '2019,20.93,5,5,7,11,463.4169006,-200\n'
)

pd.read_csv(StringIO(csv_str))  
# pandas works fine, renames 2nd X1 column to X1.1

pl.read_csv(StringIO(csv_str))
# polars crashes with a ComputeError parsing 463.107 as an Int64
```

#### What is the actual behavior?

Polars crashes with an error like so:
```
ComputeError: Could not parse 463.1070251 as dtype Int64 at column 7.
    The total offset in the file is 19 bytes.
    Consider running the parser `with_ignore_parser_errors=true`
    or consider adding 463.1070251 to the `null_values` list.
```

#### What is the expected behavior?

I think it would be ok if the polars implemented one or more of these behaviors:
1. Had handling of duplicate columns (like pandas `read_csv()`'s `mangle_dupe_cols=True`)
2. Had an error and/or warning about the duplicate column
3. If dropping the duplicate column, kept the data types in sync with the drop

**Comment by lannybroo** [comment]
Note that I get the same error if I set `use_pyarrow=True`, in `pl.read_csv()` so perhaps this is a pyarrow issue?

**Comment by cnpryer** [comment]
Just sliding in to provide an alternative perspective. This smells like one of those philosophical topics related to _who's accountable for correctness: Polars or the user_.

Given that the format of memory data is read to is different than Pandas, I'm not entirely sure it makes sense to align with Pandas for this. And it makes less sense, IMO, if the trade-off here would be sacrificing a little performance for that preprocessing step and implementing the correction(s).

Even with that said, like I mentioned, who should be responsible for the faulty file? IMO Polars' standards shouldn't start adopting selective hand-holding. It's either one-off assistance is baked into the library based on cohesive rationale supporting it, or it's not handled by the library altogether for consistency.

> 2. Had an error and/or warning about the duplicate column

If it makes sense, this is where I'd land.

Again, this is only my personal opinion though. Maybe others will disagree. 🤷‍♂️

**Comment by lannybroo** [comment]
@cnpryer I was weighing similar thoughts as I wrote this up. Having Polars be more strict about trying to help with poorly formed data could be good because it forces people to deal with messy data. 

In fact on the actual data I was working with (not the test data I made up for the example), this duplicate column has likely been in the software that produces the data for years and this helped me catch that bug.

The use case I was experimenting with was parsing years worth of existing 3-5 GB CSV files with ~1000 columns x ~300k rows, cleaning/munging, and then saving off nicer parquet files. I've done this in the past with Pandas but sometimes run into memory issues if not being careful. The thought is this might be a good real world test of using Polars. Of course, if I can't even read the file with Polars, then I have to resort to some other method of to clean out bad data once I figure out I have a duplicate column or whatever.

Open to ideas and discussion ... I appreciate the conversation and am just hoping to help.

**Comment by cnpryer** [comment]
Maybe [xsv](https://github.com/BurntSushi/xsv)? I haven't used it, but I've seen it mentioned a few times.

**Comment by ritchie46** [comment]
I think we can be more helpful here without degrading performance. I will see if we can default with an error with some hints to fix it.

I think for now you can set `header=False`, skip the first row and provide your own header columns.

**Comment by lannybroo** [comment]
I can confirm it is possible to work-around by skipping and supplying my own header. Like so, for reference:

    # example work-around
    pl.read_csv(
        StringIO(csv_str), has_header=False, skip_rows=1, 
        new_columns='A,B,C,D,E,F,G,H'.split(','))

**Comment by lannybroo** [comment]
Confirmed the latest release version 0.13.26 provides a nice error message: 
`ComputeError: CSV header contains duplicate column names`
