### ISSUE TITLE
Add support for vector (gdal) geometries

### ISSUE THREAD

**Issue by geohardtke** [pola-rs/polars#3208]
Hi there,
Would be nice to have the ability to create Series of Geometry types, and then build functionality similar to geopandas (which I miss in rust) like opening a geopackage or shape file as a DataFrame.

For example:
```rust
use gdal::{vector};
use polars::series::Series;
use polars::prelude::NamedFrom;


fn main() {
    let mut geoms: Vec<vector::Geometry> = Vec::new();
    let mut geoms = vector::Geometry::empty(vector::OGRwkbGeometryType::wkbPoint).unwrap();
    geoms.add_point((0., 0., 0.));
    geoms.add_point((0., 1.,1.));
    let s = Series::new("geometry", geoms);
}
```
which of course returns:

 ```rust
  --> src/main.rs:10:17
   |
10 |         let s = Series::new("geometry", geoms);
   |                 ^^^^^^^^^^^ the trait `NamedFrom<Geometry, _>` is not implemented for `Series`
   |
```

If there is some interest in having this functionality added, I'm willing to (with a bit of help) try to implement it.

Cheers

**Comment by program--** [comment]
To add to this, it should be easier to add support for this once the [GeoArrow](https://github.com/geopandas/geo-arrow-spec) format specification is stable (and similarly, OGC's [GeoParquet](https://github.com/opengeospatial/geoparquet/) specification). This would be great to have!

**Comment by nmandery** [comment]
There also has been some related previous discussion in #1830

**Comment by kylebarron** [comment]
Should we close this to keep discussion in #1830?

**Comment by zundertj** [comment]
Closing; the discussion can continue in #1830.

**Comment by phayes** [comment]
@geohardtke , I've implemented a GDAL <-> Polars connector cate: https://github.com/phayes/polars_gdal

**Comment by geohardtke** [comment]
brilliant work! I'll check it out @phayes
