### ISSUE TITLE
API Usage Introduction Chinese Document

### ISSUE THREAD

**Issue by linjing-lab** [pola-rs/polars#3211]
Why not issue a Chinese API reference document for such a fast data frame library for the Chinese market.

**Comment by ritchie46** [comment]
Would you be able/willing to maintain it? I don't speak any Chinese.

**Comment by linjing-lab** [comment]
Of course, I'm learning your API usage document and data frame library. I hope to make a Chinese usage document for the Chinese market as soon as possible. If I can, I'll attract more sponsors from China. But how can I cooperate with your community to get the recognition and support of official developers?

**Comment by SuperSupeng** [comment]
This looks interesting, and we might be able to choose a way to collaborate. By the way, does the polars community have plans for translation?

**Comment by ritchie46** [comment]
> But how can I cooperate with your community to get the recognition and support of official developers?

I think our discord is th best place for this. It has lowest latency.

> By the way, does the polars community have plans for translation?

No plans. This is something that should really be picked up by the community as I don't think our Chinese is sufficient.

**Comment by SuperSupeng** [comment]
> > But how can I cooperate with your community to get the recognition and support of official developers?
> 
> I think our discord is th best place for this. It has lowest latency.
> 
> > By the way, does the polars community have plans for translation?
> 
> No plans. This is something that should really be picked up by the community as I don't think our Chinese is sufficient.

Yes, the discord is a good place. Do we need to create a repository named polars-book-cn, like pingcap([docs](https://github.com/pingcap/docs), [docs-cn](https://github.com/pingcap/docs-cn)).

**Comment by ritchie46** [comment]
I think that is a good idea. Maybe do it all in one repo. E.g. the polars-book and the python API. Or is the latter not needed?

**Comment by SuperSupeng** [comment]
I think the API documentation does not need to be translated. The user guide needs a Chinese version, which will help Chinese developers understand polars more quickly.

**Comment by ritchie46** [comment]
All right. Here it is: https://github.com/pola-rs/polars-book-cn

**Comment by SuperSupeng** [comment]
We will collaborate using pr, but first, you have to add some files to this repository, an empty repo cannot be forked.

**Comment by ritchie46** [comment]
Check. :+1:
