### ISSUE TITLE
Series `min`/`max`/etc type hints should be updated

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3214]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.24

#### What operating system are you using polars on?

macOS 12.2.1

#### What language version are you using
Python 3.10.4

#### Describe your bug.

Type hints for `Series.max` and the like should be updated to include datetime types, following the update in #3191 .

#### What are the steps to reproduce the behavior?

`test.py`:
```python
import polars as pl
import datetime
s = pl.Series([datetime.datetime(2022,1,1)])
val: datetime.datetime = s.max()
```
```
>>> mypy test.py
test.py:4: error: Incompatible types in assignment (expression has type "float", variable has type "datetime")  [assignment]
```

#### What is the actual behavior?
The return type of `Series.max` and related functions does not include datetime types.

#### What is the expected behavior?

Mypy should have not raised an error.

**Comment by ritchie46** [comment]
Yep.. can you make a PR?
