### ISSUE TITLE
PanicException index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by FarahAmirahJ** [pola-rs/polars#3221]
Hi, i try to install polars library in jupyter notebook
!pip install polars
And load some data .csv

So when i import polars as pl
Df1= pl.read_csv('filename.csv', ignore_errors=True)

it raise an issue PanicException: index out of bounds: the len is 0 but the index is 0

 there is data that is large than this file, but this file cannot load., May i know why?

**Comment by ritchie46** [comment]
That is a bug. Can you show the backtrace? You get it if you set `RUST_BACKTRACE=1`

**Comment by ishbooisland** [comment]
I'm having the same issue, full error I get:

--------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
d:\---\---\file.py in 
     11 
     12 start = time.time()
---> 13 df_o = pd.read_csv(base_folder + source + '_Offenses.txt', sep='|')
     14 print(f"Done Reading Offenses {time.time() - start}")
     15 

C:\ProgramData\Miniconda3\lib\site-packages\polars\io.py in read_csv(file, has_header, columns, new_columns, sep, comment_char, quote_char, skip_rows, dtypes, null_values, ignore_errors, parse_dates, n_threads, infer_schema_length, batch_size, n_rows, encoding, low_memory, rechunk, use_pyarrow, storage_options, skip_rows_after_header, row_count_name, row_count_offset, sample_size, **kwargs)
    400 
    401     with _prepare_file_arg(file, **storage_options) as data:
--> 402         df = DataFrame._read_csv(
    403             file=data,
    404             has_header=has_header,

C:\ProgramData\Miniconda3\lib\site-packages\polars\internals\frame.py in _read_csv(cls, file, has_header, columns, sep, comment_char, quote_char, skip_rows, dtypes, null_values, ignore_errors, parse_dates, n_threads, infer_schema_length, batch_size, n_rows, encoding, low_memory, rechunk, skip_rows_after_header, row_count_name, row_count_offset, sample_size)
    584         projection, columns = handle_projection_columns(columns)
    585 
--> 586         self._df = PyDataFrame.read_csv(
    587             file,
    588             infer_schema_length,

PanicException: index out of bounds: the len is 0 but the index is 0

**Comment by ishbooisland** [comment]
Full Backtrace, also FYI, I've tried each version back to 13.25.

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', D:\a\polars\polars\polars\polars-
io\src\csv_core\buffer.rs:93:38
stack backtrace:
   0:     0x7ffacc9aa1ab - rust_eh_personality
   1:     0x7ffacbb8c89a - BrotliDecoderVersion
   2:     0x7ffacc99c2ca - rust_eh_personality
   3:     0x7ffacc9ab3a0 - rust_eh_personality
   4:     0x7ffacc9ac1f7 - rust_eh_personality
   5:     0x7ffacc9abd73 - rust_eh_personality
   6:     0x7ffacc9abcd9 - rust_eh_personality
   7:     0x7ffacc9abc94 - rust_eh_personality
   8:     0x7ffacca58615 - rust_eh_personality
   9:     0x7ffacca585d7 - rust_eh_personality
  10:     0x7ffacc6823d6 - rust_eh_personality
  11:     0x7ffacc67c990 - rust_eh_personality
  12:     0x7ffacc67f168 - rust_eh_personality
  13:     0x7ffacc67d618 - rust_eh_personality
  14:     0x7ffacc67f168 - rust_eh_personality
  15:     0x7ffacc67d618 - rust_eh_personality
  16:     0x7ffacc67f168 - rust_eh_personality
  17:     0x7ffacc67d618 - rust_eh_personality
  18:     0x7ffacc66d6e8 - rust_eh_personality
  19:     0x7ffacc68643e - rust_eh_personality
  20:     0x7ffaccae056b - rust_eh_personality
  21:     0x7ffacc91923e - rust_eh_personality
  22:     0x7ffacc918c2b - rust_eh_personality
  23:     0x7ffacc9ad14c - rust_eh_personality
  24:     0x7ffb367384d4 - BaseThreadInitThunk
  25:     0x7ffb368d1791 - RtlUserThreadStart
Traceback (most recent call last):
  File ".\createflat.py", line 13, in <module>
    df_o = pd.read_csv(base_folder + source + '_Offenses.txt', sep='|')
  File "C:\ProgramData\Miniconda3\lib\site-packages\polars\io.py", line 398, in read_csv
    df = DataFrame._read_csv(
  File "C:\ProgramData\Miniconda3\lib\site-packages\polars\internals\frame.py", line 585, in _read_csv
    self._df = PyDataFrame.read_csv(
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0

**Comment by ishbooisland** [comment]
Sorry to post again, I downgraded to 0.12.24 and the error message was different. Something along the lines of an issue with int64. I was going to set all dtypes manually, but also found "infer_schema_length=0". Setting this allowed it to work past this issue. I upgraded back to 13.31 and all is good.
