### ISSUE TITLE
Inappropriate result of expr `skew` and `kurtosis`

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3225]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.25

#### What operating system are you using polars on?

macOS Monterey

#### What language version are you using

Python 3.10

#### Describe your bug.

Inappropriate result of expr `skew` and `kurtosis`

#### What are the steps to reproduce the behavior?

```python
In [1]: pl.__version__
Out[1]: '0.13.25'

In [2]: df = pl.DataFrame([pl.Series("key", ["n1", "n2", "n2", "n3", "n3", "n3", "n4", "n4", "n4", "n4"]), pl.Series("val", [1, 1, 2, 1, 2, 3, 1, 2, 3, 4])])

In [3]: df
Out[3]:
shape: (10, 2)
┌─────┬─────┐
│ key ┆ val │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ n1  ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n2  ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n2  ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n3  ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ ... ┆ ... │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n4  ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n4  ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n4  ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ n4  ┆ 4   │
└─────┴─────┘

In [4]: df.groupby("key").agg([pl.col("val").mean().alias("vmean"), pl.col("val").std().alias("vstd"), pl.col("val").skew().alias("vskew"), pl.col("val").kurtosis().alias("vkurt")]).sort("key")
Out[4]:
shape: (4, 5)
┌─────┬───────┬──────────┬────────────┬───────┐
│ key ┆ vmean ┆ vstd     ┆ vskew      ┆ vkurt │
│ --- ┆ ---   ┆ ---      ┆ ---        ┆ ---   │
│ str ┆ f64   ┆ f64      ┆ list [f64] ┆ f64   │
╞═════╪═══════╪══════════╪════════════╪═══════╡
│ n1  ┆ 1.0   ┆ NaN      ┆ [NaN]      ┆ NaN   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ n2  ┆ 1.5   ┆ 0.707107 ┆ [0.0]      ┆ -2.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ n3  ┆ 2.0   ┆ 1.0      ┆ [0.0]      ┆ -1.5  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ n4  ┆ 2.5   ┆ 1.290994 ┆ [0.0]      ┆ -1.36 │
└─────┴───────┴──────────┴────────────┴───────┘
```

#### What is the expected behavior?

1. column `vskew` should be of type `f64`, not `list [f64]`
2. the value in (row `n2`, col `vskew`) should be `NaN`
3. the value in (row `n2`, row `n3`, col `vkurt`) should be `NaN`

**Comment by marcvanheerdenbain** [comment]
@ritchie46 can I pick this up?

**Comment by ritchie46** [comment]
Yes! A few hints. In in lazy we must use `apply` instead of `map` and set `auto_explode=true`

**Comment by marcvanheerden** [comment]
hi @mutecamel, can you elaborate points 2 and 3 in the expected behaviour?
I'm not sure why these outputs should be NaN and I don't get that outcome in scipy.stats or in R's moments package.

**Comment by mutecamel** [comment]
Hi @marcvanheerden, thank you for your effort. I didn't check in scipy.stats or R moments. The reason I expect them to be NaN is on minimum number of observations in sample estimation.

Because standard deviation is about the second moment, its sample estimation needs at least two observations, no matter the estimator is biased or unbiased. Similarly, skewness (or kurtosis) is about the third (or fourth) moment, its sample estimation needs at least three (or four) observations, no matter the estimator is biased or unbiased ([ref1](https://en.wikipedia.org/wiki/Skewness#Sample_skewness), [ref2](https://en.wikipedia.org/wiki/Kurtosis#Standard_unbiased_estimator)). This is why I expect them to be NaN.

I checked in scipy.stats, it won't produce NaN indeed. But when there are too few observations, skewness and kurtosis estimation are nonsense, no matter we use biased or unbiased estimator.

**Comment by ritchie46** [comment]
I don't want to divert from scipy and R here. I want to follow them unless it is uniformly accepted as a bug.

@marcvanheerden then this can be fixed with the auto explode strategy.

**Comment by marcvanheerden** [comment]
Will open a PR shortly
