### ISSUE TITLE
Connection to spss like pandas.read_spss

### ISSUE THREAD

**Issue by jccguma** [pola-rs/polars#3233]
The idea would be to replicate the functionality of pandas.read_spss for spss.

**Comment by ritchie46** [comment]
Polars is so fast that we make up for the initial copy from pandas:

`pl.from_pandas(pd.read_spss(..))`.

**Comment by jccguma** [comment]
Thanks @ritchie46, but I am wondering if this will produce a limitation in the file size. Pandas sometimes struggles when opening high volume files (i.e. 8GB DataFrames).

**Comment by ritchie46** [comment]
I see that pandas uses https://github.com/Roche/pyreadstat for spss reading. They support conversion to pandas.

Best place is to request arrow/polars support in that repo. As another binary format is not in scope in polars.

**Comment by jccguma** [comment]
Thanks @ritchie46. I will follow your advice and get in touch with pyreadstat.
