### ISSUE TITLE
concat() to upcast int columns to float if necessary, like pandas does.

### ISSUE THREAD

**Issue by gc1o1** [pola-rs/polars#3237]
Example:
```
df1 = pl.DataFrame({'a':['abc','def'],'b':[1,2]})
df2 = pl.DataFrame({'a':['abc','def'],'b':[1.,2.]})
pl.concat([df1,df2])
```
This breaks with error:
```
RuntimeError: Any(SchemaMisMatch("cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='b' with left.dtype=i64 != right.dtype=f64 with right.name='b'"))
```

If I did that in pandas, it would work fine, assuming correctly that column `b` is all floats:
```
df1 = pd.DataFrame({'a':['abc','def'],'b':[1,2]})
df2 = pd.DataFrame({'a':['abc','def'],'b':[1.,2.]})
pd.concat([df1,df2])
```

Maybe this should be a bug instead of a feature.  I think the library should be a little forgiving to the user for assuming that ints and floats can mix together, since ints are indeed a subset of floats.

Thank you for considering this.

**Comment by cbilot** [comment]
#2815
