### ISSUE TITLE
Does groupby_dynamic have a parameter similar to "label" in pandas.Grouper? 

### ISSUE THREAD

**Issue by singdoo** [pola-rs/polars#3240]
Does groupby_dynamic have a parameter similar to "label" in pandas.Grouper? 
The current result is this.

`df.groupby_dynamic("time", every="5m", closed="left").agg([pl.sum('flow')]`

time | flow
-- | --
2022/4/25   4:00:00 | 414741783798
2022/4/25 4:05:00 | 414012858125
2022/4/25 4:10:00 | 415846256848
2022/4/25 4:15:00 | 415086651284
2022/4/25 4:20:00 | 414376929744
2022/4/25 4:25:00 | 413121392033
2022/4/25 4:30:00 | 413908142193
2022/4/25 4:35:00 | 412756070685
2022/4/25 4:40:00 | 414911972457
2022/4/25 4:45:00 | 412120914964
2022/4/25 4:50:00 | 413316189825
2022/4/25 4:55:00 | 418341143154
2022/4/25 5:00:00 | 2188888170

**But I want the sum result to be marked on "right", that is, the 04:00:00-04:05:00 sum mark at 04:05:00 instead of 04:00:00.**

For example：

time | flow
-- | --
2022/4/25 4:05:00 | 414741783798
2022/4/25 4:10:00 | 414012858125
2022/4/25 4:15:00 | 415846256848
2022/4/25 4:20:00 | 415086651284
2022/4/25 4:25:00 | 414376929744
2022/4/25 4:30:00 | 413121392033
2022/4/25 4:35:00 | 413908142193
2022/4/25 4:40:00 | 412756070685
2022/4/25 4:45:00 | 414911972457
2022/4/25 4:50:00 | 412120914964
2022/4/25 4:55:00 | 413316189825
2022/4/25 5:00:00 | 418341143154
2022/4/25 5:05:00 | 2188888170

**Comment by cbilot** [comment]
Would the `include_boundaries=True` option help?

```python3
df.groupby_dynamic("time", every="5m", closed="left", include_boundaries=True).agg([pl.sum('flow')])
```
```
shape: (13, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬──────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ time                ┆ flow         │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---          │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ i64          │
╞═════════════════════╪═════════════════════╪═════════════════════╪══════════════╡
│ 2022-04-25 04:00:00 ┆ 2022-04-25 04:05:00 ┆ 2022-04-25 04:00:00 ┆ 414741783798 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:05:00 ┆ 2022-04-25 04:10:00 ┆ 2022-04-25 04:05:00 ┆ 414012858125 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:10:00 ┆ 2022-04-25 04:15:00 ┆ 2022-04-25 04:10:00 ┆ 415846256848 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:15:00 ┆ 2022-04-25 04:20:00 ┆ 2022-04-25 04:15:00 ┆ 415086651284 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 ┆ ...                 ┆ ...                 ┆ ...          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:45:00 ┆ 2022-04-25 04:50:00 ┆ 2022-04-25 04:45:00 ┆ 412120914964 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:50:00 ┆ 2022-04-25 04:55:00 ┆ 2022-04-25 04:50:00 ┆ 413316189825 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 04:55:00 ┆ 2022-04-25 05:00:00 ┆ 2022-04-25 04:55:00 ┆ 418341143154 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-25 05:00:00 ┆ 2022-04-25 05:05:00 ┆ 2022-04-25 05:00:00 ┆ 2188888170   │
└─────────────────────┴─────────────────────┴─────────────────────┴──────────────┘
```
You could then use the `_upper_boundary` column as you need.

**Comment by zundertj** [comment]
Closing this as the question has been answered.
