### ISSUE TITLE
Make `str.replace()` replace all occurrences of the string instead of just the first match

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#3245]
#### Describe your feature request

I believe that by far the most common use case for `str.replace()` is probably the replacement of every matched substring in a Series. This is the way that search/replace in a text editor works, so it is intuitive. For people coming from pandas, this is certainly the behavior they would expect. From the pandas docs:

> Series.str.replace(pat, repl, n=- 1, case=None, flags=0, regex=None)[[source]](https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/core/strings/accessor.py#L1290-L1465)
>> Replace each occurrence of pattern/regex in the Series/Index.

However, the current polars implementation appears to replace only the first instance:

> StringNameSpace.replace(pattern: str, value: str) → [polars.internals.series.Series](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.html#polars.Series)
> 
>> Replace first regex match with a string value.

At the moment, the only way I can see to achieve the desired functionality is `re.sub()` with `Series.apply()`, which takes really long. My workaround at the moment is simply to call `str.replace()` an arbitrary number of times until I assume that there are no more replacements left - this is obviously not ideal.

It would be fantastic to have the ability to easily replace all occurrences. Or maybe there's a better way already, and I'm not seeing it?

**Comment by ritchie46** [comment]
Have you seen `replace_all`?

**Comment by DrMaphuse** [comment]
Awesome, I guess that solves that!

In that case I would like to suggest to also allow this as an argument to `str.replace()`, since that would make it impossible to miss. Or cross-link the two in the API reference.

**Comment by ritchie46** [comment]
Could you make a PR for what you'd like to see documented?

**Comment by DrMaphuse** [comment]
I added the `See Also` sections and submitted a PR.
I also took the liberty of adding examples to `.replace_all()`

Let me know if it went through - it's my first time submitting a PR on the web.
