### ISSUE TITLE
Quantile does not always return the correct result when applied to a filtered column in a groupby agg

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#3249]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.13.25

#### What operating system are you using polars on?

Linux

#### What language version are you using

3.9.12

#### Describe your bug.

Quantile can return incorrect (as well as nondeterministic) results when used on a filtered column inside of an agg.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

pl.DataFrame({
    "group": [0, 0, 0, 0, 1, 1, 1, 1],
    "value": [1, 2, 3, 4, 1, 2, 3, 4],
}).groupby("group").agg(
    pl.col("value").filter(pl.col("value") < 2).quantile(0.5)
)
```

#### What is the actual behavior?

The exact values returned seem to be non-deterministic, but here is an example output:

```
group	value
i64	f64
1	1.3971e14
0	1.3966e14
```

#### What is the expected behavior?

``
group	value
i64	f64
1	1
0	1
```

**Comment by marcvanheerden** [comment]
@ritchie46 I can pick this up if that's okay?

**Comment by slonik-az** [comment]
> What is the expected behavior?
> ```
> group value
> i64 f64
> 1 1
> 0 1
> ```

The median (quantile 0.5) of the sequence [1,2,3,4] should be a number between 2 and 3 but not the value of 1 as you mention in "expected behavior".

**Comment by ritchie46** [comment]
> @ritchie46 I can pick this up if that's okay?

I already know what the fix is. So I wouldn't want to waste your time on this. It's silly. :)

**Comment by slonik-az** [comment]
> The filter(pl.col("value") < 2 filters the series down to just [1] before calculating the median. Thus, any quantile should be 1 in this case.

Somehow I missed the `filter` part, bummer 🥲
