### ISSUE TITLE
Passing a `Series` of strings to `np.array` errors

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#3253]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.13.25

#### What operating system are you using polars on?

Linux

#### What language version are you using

Python 3.9

#### Describe your bug.

Passing a `Series` of strings to `np.array` results in `ValueError: could not convert string to float`. Using `to_numpy` is fine workaround, but having this work would make interoperation with some other libraries more convenient.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import numpy as np

np.array(pl.Series(["one", "two"]))
```

#### What is the actual behavior?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-92-88bfa8374381> in <module>
----> 1 np.array(pl.Series(["one", "two"]))

/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/polars/internals/series.py in __array__(self, dtype)
   2050 
   2051     def __array__(self, dtype: Any = None) -> np.ndarray:
-> 2052         return self.to_numpy().__array__(dtype)
   2053 
   2054     def __array_ufunc__(

ValueError: could not convert string to float: 'one'
```

#### What is the expected behavior?

```
array(['one', 'two'], dtype='<U3')
```

or

```
 array(['one', 'two'], dtype=object)
```

**Comment by ritchie46** [comment]
Have you got an idea how we might solve this?

**Comment by qiemem** [comment]
Hmm. Possibly. Looking at it further this almost seems like a bug in numpy in that it treats `__array__(None)` differently than `__array__()`:

```python
In [116]: np.array(["one", "two"]).__array__()
Out[116]: array(['one', 'two'], dtype='<U3')

In [117]: np.array(["one", "two"]).__array__(None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-117-d6e8f6586de8> in <module>
----> 1 np.array(["one", "two"]).__array__(None)

ValueError: could not convert string to float: 'one'
```

That said, it's (arguably) a bug that could be worked around by only passing the arg if you actually get it:

```python
def __array__(self, *args) -> np.ndarray:
    return self.to_numpy().__array__(*args)
```

to reproduce numpy's behavior exactly, or maybe:

```python
def __array__(self, dtype: Any = None) -> np.ndarray:
    arr = self.to_numpy()
    return arr.__array__(arr.dtype if dtype is None else dtype)
```

to behave how numpy probably should be behaving here.

bleh

**Comment by ghuls** [comment]
Polars series with ints/floats of a specific dtype were also not preserved before:

```python
In [4]: pl.Series([1, 3, 2], dtype=pl.Int8).to_numpy()
Out[4]: array([1, 3, 2], dtype=int8)

# Before patch
In [5]: np.array(pl.Series([1, 3, 2], dtype=pl.Int8))
Out[5]: array([1., 3., 2.])

In [6]: np.array(pl.Series([1, 3, 2], dtype=pl.Int8)).dtype
Out[6]: dtype('float64')

# After
In [38]: np.array(pl.Series([1, 3, 2], dtype=pl.Int8))
Out[38]: array([1, 3, 2], dtype=int8)
```
