### ISSUE TITLE
pl.DataFrame.with_columns functionality akin to pandas.DataFrame.assign

### ISSUE THREAD

**Issue by vale46** [pola-rs/polars#3255]
Hello - thanks for your work on this library, which I started using recently (coming from pandas) and love the performance benefits and syntax that's more intuitive.

Feature Request:
My preferred style of writing Python code involves lots of methods chaining. In that context, `pandas.DataFrame.assign` comes in handy, when adding/overwriting columns. One feature of `assign` is it allows immediate access to newly created column(s), in effect allowing chaining within `assign`. As a minimal pandas example,
```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
print(df)
:    a   b
: 0  1   3
: 1  2   4
new_df = df.assign(c=lambda x: x['a'] + x['b'], d=lambda x: x['b'] + x['c'])
print(new_df)
:    a   b   c   d
: 0  1   3   4   7
: 1  2   4   6  10
```
Equivalent idea in `polars`, using `with_columns`, returns `NotFoundError: c` error when adding column `d`.

Just realized that `polars with_columns` execution is inherently parallel - hence the error, while `pandas assign` executes sequentially. So this enhancement will definitely change existing functionality for `with_columns`.

Thoughts?

**Comment by cbilot** [comment]
In Polars, we would express this as:
```python3
(
    df
    .with_column((pl.col('a')+pl.col('b')).alias('c'))
    .with_column((pl.col('b')+pl.col('c')).alias('d'))
)
```
```
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 4   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 4   ┆ 6   ┆ 10  │
└─────┴─────┴─────┴─────┘
```

Basically, the `with_columns` command allows you to parallelize *independent* operations (for example, parsing multiple string columns).

When operations are dependent, place them in chained `with_column` (or `with_columns`) expressions.

**Comment by vale46** [comment]
thx, I realized that soon after my initial query and edited last part of original question.

**Comment by ritchie46** [comment]
Yeah.. you just need to stack multiple `with_columns` calls for dependent data.

Context run expressions in parallel and we like that. ;)

**Comment by vale46** [comment]
Agree 👍 . Closing this.
