### ISSUE TITLE
name 'pa' is not defined

### ISSUE THREAD

**Issue by KeremAslan** [pola-rs/polars#3266]
#### What language are you using?
Python 

#### Have you tried latest version of polars?

yes 

#### What version of polars are you using?
I am on polars 0.13.25 and pyarrow 7.0.0

#### What operating system are you using polars on?
MacOS 12.3

#### What language version are you using
Python 3.10.0

#### Describe your bug.
converting a polars dataframe to a pandas dataframe via `df.to_pandas()` results in the following error

```python
File ~/opt/anaconda3/envs/syrup/lib/python3.10/site-packages/polars/internals/frame.py:1070, in DataFrame.to_pandas(self, date_as_object, *args, **kwargs)
   1040 """
   1041 Cast to a Pandas DataFrame. This requires that Pandas is installed.
   1042 This operation clones data.
   (...)
   1067 
   1068 """
   1069 record_batches = self._df.to_pandas()
-> 1070 tbl = pa.Table.from_batches(record_batches)
   1071 return tbl.to_pandas(*args, date_as_object=date_as_object, **kwargs)

NameError: name 'pa' is not defined
```

#### What are the steps to reproduce the behavior?
1. Set up a conda virtual environment with python 3.10.0
2. install polars using `pip install polars`
3. create a dataframe using `df = pl.read_csv()`
4. convert dataframe to a pandas dataframe using `df.to_pandas()`

If possible, please include a **minimal simple** example on a dataset that is created through code:

```python
import polars as pl

df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "groups": ["A", "A", "B", "C", "B"],
    }
)
df.to_pandas()
```

#### What is the expected behavior?
polars should have returned a pandas dataframe

**Comment by ritchie46** [comment]
You should install pyarrow for conversion to pandas. We should include that in the error message.

**Comment by KeremAslan** [comment]
I had installed it, but I didn't reimport the library after I did so. Reimporting polars after installation solved the issue. We can close this.l
