### ISSUE TITLE
DataFrame.rename() with function as argument

### ISSUE THREAD

**Issue by vale46** [pola-rs/polars#3267]
Hello - 
looking for `DataFrame.rename()` functionality which would allow inline method chaining to rename columns using a function. This allows renaming columns using regex with `re.sub`.

For sure, current functionality is implemented as standalone code such as `df.columns = list(map(lambda x: (....,), df.columns))` as outlined in [https://stackoverflow.com/questions/71351393/polars-search-and-replace-in-column-names](url); while `rename` only takes `dict` as argument.

**Comment by cbilot** [comment]
>while rename only takes dict as argument.

Would a dictionary comprehension help here?
```python3
df.rename({old_nm: re.sub("_dt", "_date", old_nm) for old_nm in df.columns})
```

This would allow you to chain substitutions as you wish:
```python3
def expand_names(col_nm: str) -> str:
    col_nm = re.sub("_dt", "_date", col_nm)
    col_nm = re.sub("_nm", "_name", col_nm)
    col_nm = re.sub("_addr", "_address", col_nm)
    return col_nm

df.rename({old_nm: expand_names(old_nm)
          for old_nm in df.columns if "_" in old_nm})
```

**Comment by vale46** [comment]
good idea, but that won't work in cases when columns are added/removed before `rename`, as in this example, where  the newly added column is not renamed:

```python
import polars as pl
import re

df = pl.DataFrame({"first_nm": ["A", "B", "C"], "last_nm": ["xx", "yy", "zz"]})
df = (
    df
    .with_column(pl.concat_str(["first_nm", "last_nm"], sep=' ').alias("full_nm"))
    .rename({old_nm: re.sub("_nm", "_name", old_nm) for old_nm in df.columns})
)
print(df)
shape: (3, 3)
┌────────────┬───────────┬─────────┐
│ first_name ┆ last_name ┆ full_nm │
│ ---        ┆ ---       ┆ ---     │
│ str        ┆ str       ┆ str     │
╞════════════╪═══════════╪═════════╡
│ A          ┆ xx        ┆ A xx    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ B          ┆ yy        ┆ B yy    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ C          ┆ zz        ┆ C zz    │
└────────────┴───────────┴─────────┘
```
It's worse when original columns are dropped prior to the `rename`, since iterating over missing columns leads to run-time error.

**Comment by ritchie46** [comment]
> good idea, but that won't work in cases when columns are added/removed before rename, as in this example, where the newly added column is not renamed:

You can use `pipe` to get a hold of the current state of the `DataFrame`.

```python
df = pl.DataFrame({"first_nm": ["A", "B", "C"], "last_nm": ["xx", "yy", "zz"]})
(
    df
    .with_column(pl.concat_str(["first_nm", "last_nm"], sep=' ').alias("full_nm"))
    .pipe(lambda df: df.rename({old_nm: re.sub("_nm", "_name", old_nm) for old_nm in df.columns}))
)
```

```
shape: (3, 3)
┌────────────┬───────────┬───────────┐
│ first_name ┆ last_name ┆ full_name │
│ ---        ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╡
│ A          ┆ xx        ┆ A xx      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ B          ┆ yy        ┆ B yy      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ C          ┆ zz        ┆ C zz      │
└────────────┴───────────┴───────────┘

```

**Comment by vale46** [comment]
thanks for pointing to the versatility of `pipe`, and given it works is `lazy` context is great with no performance give up.

**Comment by cbilot** [comment]
FYI, this was an amazing post that introduced me to pipes: https://www.pola.rs/posts/the-expressions-api-in-polars-is-amazing/

It changed my coding style so that now much of my code is a chain of pipe expressions.
