### ISSUE TITLE
polars-u64-idx: groupby/agg/count error (1,000+ records)

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3275]
#### What language are you using?
polars-u64-idx 0.13.26
python 3.10.4 
Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

#### Describe your bug.
`groupby/agg/count` gives the wrong results for datasets with 1,000+ records, but correct results for datasets of 999 records of less.  While developing a MWE, I discovered that the threshold of this error is 1,000 records.
#### What are the steps to reproduce the behavior?
```python3
import polars as pl

nbr_recs = 1000
(pl.DataFrame({"col1": pl.repeat(0, nbr_recs, eager=True)})
    .groupby(["col1"])
    .agg([
        pl.count().alias("nbr_records")
    ])
 )
```
```
shape: (1, 2)
┌──────┬─────────────┐
│ col1 ┆ nbr_records │
│ ---  ┆ ---         │
│ i64  ┆ u32         │
╞══════╪═════════════╡
│ 0    ┆ 64          │
└──────┴─────────────┘
```

If we change `nbr_recs` to 999, we get:
```
shape: (1, 2)
┌──────┬─────────────┐
│ col1 ┆ nbr_records │
│ ---  ┆ ---         │
│ i64  ┆ u32         │
╞══════╪═════════════╡
│ 0    ┆ 999         │
└──────┴─────────────┘
```
#### Other Notes:
* This error does **not** occur with regular polars 0.13.25.

**Comment by ritchie46** [comment]
Yes, I already yanked `0.13.26`. Can you try `0.13.27`?

**Comment by cbilot** [comment]
```
shape: (1, 2)
┌──────┬─────────────┐
│ col1 ┆ nbr_records │
│ ---  ┆ ---         │
│ i64  ┆ u32         │
╞══════╪═════════════╡
│ 0    ┆ 64          │
└──────┴─────────────┘
>>> 
>>> pl.__version__
'0.13.27'
```

**Comment by ritchie46** [comment]
Thanks! I will fix and release it immediately.

**Comment by cbilot** [comment]
Testing now with regular polars 0.13.27, the bug is also present there:
```
shape: (1, 2)
┌──────┬─────────────┐
│ col1 ┆ nbr_records │
│ ---  ┆ ---         │
│ i64  ┆ u32         │
╞══════╪═════════════╡
│ 0    ┆ 64          │
└──────┴─────────────┘
>>> 
>>> pl.__version__
'0.13.27'
```

**Comment by ritchie46** [comment]
> Testing now with regular polars 0.13.27, the bug is also present there:
> 
> ```
> shape: (1, 2)
> ┌──────┬─────────────┐
> │ col1 ┆ nbr_records │
> │ ---  ┆ ---         │
> │ i64  ┆ u32         │
> ╞══════╪═════════════╡
> │ 0    ┆ 64          │
> └──────┴─────────────┘
> >>> 
> >>> pl.__version__
> '0.13.27'
> ```
> 
> ```
> (tmp-6bebe60defc4c29) corey@threadripperpro:~/.virtualenvs/tmp-6bebe60defc4c29$ pip list
> Package    Version
> ---------- -------
> numpy      1.22.3
> pip        22.0.4
> polars     0.13.27
> pyarrow    7.0.0
> setuptools 61.3.1
> wheel      0.37.1
> ```

Yes, it has nothing to do with the polars indices. It is because I did wrong implementation of partitioned groupby. I am reverting the logic and will come with a better implemenation. 

And add your test. ;)

**Comment by cbilot** [comment]
This works now in 0.13.28.
