### ISSUE TITLE
how do i get rid of this?

### ISSUE THREAD

**Issue by wookidooki8** [pola-rs/polars#3289]
i've been learning python since a month ago and i figured polars is way faster than pandas (massive thanx to the developer :DD!!) but im having a problem with switching pandas to polars. i believe this is easy for almost everyone but not for me.  so i changed pd.dataframe to pl.dataframe (which is polars) in yolov5 to get results fast. it seems like its working well except im getting weird strings such as f64, i65 on the top of the table. 
![image](https://user-images.githubusercontent.com/104318789/166395527-00a256bd-5123-40fe-a976-a5b0790ecfff.png)

heres the code im using

    def polars(self):
        # return detections as pandas DataFrames, i.e. print(results.pandas().xyxy[0])
        new = copy(self)  # return copy
        ca = 'xmin', 'ymin', 'xmax', 'ymax', 'confidence', 'class', 'name'  # xyxy columns
        cb = 'xcenter', 'ycenter', 'width', 'height', 'confidence', 'class', 'name'  # xywh columns
        for k, c in zip(['xyxy', 'xyxyn', 'xywh', 'xywhn'], [ca, ca, cb, cb]):
            a = [[x[:5] + [int(x[5]), self.names[int(x[5])]] for x in x.tolist()] for x in getattr(self, k)]  # update
            setattr(new, k, [pl.DataFrame(x, columns=c) for x in a])
        return new

i'd appreciate it if someone could help me with this :)! have a nice day

**Comment by cbilot** [comment]
> its working well except im getting weird strings such as f64, i65 on the top of the table

You'll want to see those strings.  Those strings tell you the datatype that Polars has assigned to each column.  For example, "f64" means `Float64` (i.e., 64-bit floating point), "i64" means `Int64` (64-bit integer), and "str" is a string (`Utf8`). 

There's a handy list of the datatypes in the [Polars User Guide](https://pola-rs.github.io/polars-book/user-guide/datatypes.html).

**Comment by cbilot** [comment]
As an aside, the User Guide also has a handy section for those [coming from Pandas](https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html#coming-from-pandas).

**Comment by zundertj** [comment]
I am closing this issue as this is about basic usage of the polars library. These types of questions are better posted on StackOverflow. @cbilot  answers are good starting points in learning more about polars and the specific issues you are running into.


#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)
