### ISSUE TITLE
Error when divide expr (arr) by expr (lit)

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#3290]
#### What language are you using?
 **Python**
#### Have you tried latest version of polars?
yes

python 3.8, Ubuntu 22.04, polars 0.13.16

#### Describe your bug.
When divide or product expr (arr) by expr (single value) throw an exception:
*PanicException: impl error, should be a list at this point: SchemaMisMatch("Series dtype Float64 != list")*
in  polars 0.13.28 errors changed to
*ValueError: explode not supported for Series with dtype UInt32*

#### What are the steps to reproduce the behavior?

```python
import polars as pl
df = pl.DataFrame({'col1': ['A', 'B'],  'col2': [1, 1],})
df.groupby('col1').agg(pl.col('col2').unique_counts() / pl.col('col2').len())

PanicException: impl error, should be a list at this point: SchemaMisMatch("Series dtype Float64 != list")
```
#### expected behavior?

col1 | col2
-- | --
str | list
"A" | [1.0]
"B" | [1.0]

PS: If replace df with **df = pl.DataFrame({'col1': ['A', 'A'],  'col2': [1, 1],})**  
          or **df.groupby('col1').agg(pl.col('col2').unique_counts() / 1 )** - all works just fine

**Comment by s-b90** [comment]
Yes, exactly `unique_counts`.
And just for understanding, this kind of operations expr (arr) / expr (lit) are they allowed?
Because sometimes they works and sometimes not.

If replace df with df = pl.DataFrame({'col1': ['A', 'A'], 'col2': [1, 1],})
or df.groupby('col1').agg(pl.col('col2').unique_counts() / 1 ) - all works just fine

**Comment by ritchie46** [comment]
I think we will. Not fully developed yet. I will see if we can add tests for this.
