### ISSUE TITLE
Can't compile rust Polars version 0.21.0 from crates.io.

### ISSUE THREAD

**Issue by CHCP** [pola-rs/polars#3299]
In my cargo.toml file, It  can't be compiled normally: 
```
[dependencies]
polars = { version = "0.21.0", default_features = false, features = ["lazy", "temporal", "dynamic_groupby", "simd", "dtype-datetime", "fmt", "csv-file"]} 
```

The version 0.21.0 in crates.io, it shows:
```
This crate has been yanked, but it is still available for download for other crates that may be depending on it.
```

Is version 0.21.0  officially released?

**Comment by trago** [comment]
Same issue here, it was compiling before but sudenly today I got this

**Comment by cnpryer** [comment]
From what I understand 0.21.0 introduced performance loss for groupby operations.

Tests weren't able to cover unique cases that performed a lot worse than what is covered.

This information is from the discord server https://discord.gg/d3Hen5Hjak

**Comment by ritchie46** [comment]
The version was yanked because it had a serious correctness bug. I will issue a new release soon.
