### ISSUE TITLE
include quarter() method in ExprDateTimeNameSpace and DateTimeNameSpace class

### ISSUE THREAD

**Issue by bruppfab** [pola-rs/polars#3304]
#### Describe your feature request

Can you add a method that returns the quarter number? Something like that: 

`    def quarter(self) -> Series:
        """
        Extract the quarter from the underlying date representation.
        Can be performed on Date and Datetime
        Returns the quarter number starting from 1.
        The return value ranges from 1 to 4.
        Returns
        -------
        Quarter as UInt32
        """
        return wrap_s(self._s.quarter())`

**Comment by ritchie46** [comment]
```python
df = pl.DataFrame({
    "dates": [date(2021, 1, 1), date(2021, 4, 1), date(2021, 7, 1), date(2021, 11, 1)]
})

df.select([
    (pl.col("dates").dt.month() / 3.0).ceil().alias("quarter")
])
shape: (4, 1)
┌─────────┐
│ quarter │
│ ---     │
│ f64     │
╞═════════╡
│ 1.0     │
├╌╌╌╌╌╌╌╌╌┤
│ 2.0     │
├╌╌╌╌╌╌╌╌╌┤
│ 3.0     │
├╌╌╌╌╌╌╌╌╌┤
│ 4.0     │
└─────────┘

```

**Comment by bruppfab** [comment]
Thank you very much for the swift reply. That works as well of course.
