### ISSUE TITLE
Incompatibility from polars.write_parquet() using LZ4

### ISSUE THREAD

**Issue by oholoko** [pola-rs/polars#3322]
#### What language are you using?

Python.

#### Have you tried latest version of polars?

Yes.

#### What version of polars are you using?

polars = 0.13.23
pyarrow = 7.0.0

#### What operating system are you using polars on?

Manjaro linux.

#### What language version are you using

Python 3.10

#### What are the steps to reproduce the behavior?

```
import polars as pl
import pyarrow.parquet as pq

df = pl.DataFrame({'a':['1','2','3','4'],'b':['2','3','4','5']})
df.write_parquet('teste_file.parquet')
arrow_parquet = pq.ParquetFile('teste_1.parquet.gzip')
print(arrow_parquet.read())
```

#### What is the actual behavior?

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-42-092dd18ab014> in <module>
----> 1 aux.read()

~/.local/lib/python3.10/site-packages/pyarrow/parquet.py in read(self, columns, use_threads, use_pandas_metadata)
    399         column_indices = self._get_column_indices(
    400             columns, use_pandas_metadata=use_pandas_metadata)
--> 401         return self.reader.read_all(column_indices=column_indices,
    402                                     use_threads=use_threads)
    403 

~/.local/lib/python3.10/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetReader.read_all()

~/.local/lib/python3.10/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

OSError: Corrupt Lz4 compressed data.
```

#### What is the expected behavior?

```
pyarrow.Table
a: large_string
b: large_string
----
a: [["1","2","3","4"]]
b: [["2","3","4","5"]]

```

#### Solution

I've solved my issue by using the argument (compression='gzip') and reading that.

#### Problems

I am not sure what is happening but i think the format LZ4 from arrow2 is being incompatible with the one read by pyarrow. But i would like to know if this is a error from arrow2,polars,pyarrow or an oversight on my part. Specially since there's several pipelines on my job depending on the compatibility between parquet files.

When i tried reading the resulting parquet with datafusion it worked fine.

**Comment by ghuls** [comment]
Update to the lastest polars version `0.13.29`

**Comment by oholoko** [comment]
Yeah that solved it. Thank you for the help.
