### ISSUE TITLE
`TimeUnit` add support with `Second` format

### ISSUE THREAD

**Issue by attila-lin** [pola-rs/polars#3325]
#### Describe your feature request

Amazing work!

I use this library in Rust. I found the datetime display is quite strange nowadays when I use a i64 to display a timestamp which is second format.

I think we should just add support with `TimeUnit::Second`.

**Comment by ritchie46** [comment]
I don't want an extra time unit. Its not worth the complexity and extra compile times. We can model any timestamp you ever need with current timestamps.

**Comment by attila-lin** [comment]
But the arrow and Parquet support it and display bad. 😂
