### ISSUE TITLE
Timezone Support

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#3326]
I saw in this https://github.com/pola-rs/polars/issues/2723#issuecomment-1046992113 that timezone is yet to be supported. Are there plans to support timezone?

```python
import datetime
import polars as pl

now = datetime.datetime.now(datetime.timezone.utc)
pl.Series([now])
```
```
Conversion of timezone aware to naive datetimes. TZ information may be lost.
```

**Comment by ritchie46** [comment]
They are not a high priority by me.

**Comment by ritchie46** [comment]
Al right. Gave it some priority. This PR #3357 makes polars `Datetime` timezone aware.
