### ISSUE TITLE
User guider has some tiny errors

### ISSUE THREAD

**Issue by yanyu2015** [pola-rs/polars#3332]
some tiny errors as follows:
![image](https://user-images.githubusercontent.com/11142054/167280656-4555b1f9-75a5-42e8-a721-bc7b8f1a5ea3.png)

![image](https://user-images.githubusercontent.com/11142054/167280668-7834c8bb-4554-4320-8914-5bb1e395b0d6.png)
you should specify which data you have used.

![image](https://user-images.githubusercontent.com/11142054/167280629-34942f33-b633-4b21-8800-e6f8865605eb.png)

**Comment by slonik-az** [comment]
Thanks for reporting. The user-guide has its own git repository at https://github.com/pola-rs/polars-book . Reporting the issue there would be more appropriate.

**Comment by yanyu2015** [comment]
Thanks for the information, I'm sorry I wasn't aware of this before, I'll take care of it next time. Do I need to go to that repository and do it again?

**Comment by ritchie46** [comment]
Thanks, Can you make an issue in https://github.com/pola-rs/polars-book?
