### ISSUE TITLE
dataframe.to_pandas is not work

### ISSUE THREAD

**Issue by hengaini2055** [pola-rs/polars#3338]
#### What language are you using?

**Python*

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.13.31

#### What operating system are you using polars on?

Ubuntu 2204 desktop

#### What language version are you using
python 3.9.12

#### Describe your bug.

I learn polars in jupyter lab, and import some library. When I run df.to_pandas(), get the follow errors:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [86], in <cell line: 2>()
      1 cl_names.sort()
----> 2 df.to_pandas()

File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/polars/internals/frame.py:1072, in DataFrame.to_pandas(self, date_as_object, *args, **kwargs)
   1042 """
   1043 Cast to a Pandas DataFrame. This requires that Pandas is installed.
   1044 This operation clones data.
   (...)
   1069 
   1070 """
   1071 record_batches = self._df.to_pandas()
-> 1072 tbl = pa.Table.from_batches(record_batches)
   1073 return tbl.to_pandas(*args, date_as_object=date_as_object, **kwargs)

NameError: name 'pa' is not defined
```

#### What are the steps to reproduce the behavior?
**Cells** jupyter lab
```
import pandas as pd
import polars as pl
import pyarrow as pa
df = pl.read_parquet("./data/out.par1")
df.to_pandas()
```

**Errors**

```
NameError                                 Traceback (most recent call last)
Input In [86], in <cell line: 2>()
      1 cl_names.sort()
----> 2 df.to_pandas()

File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/polars/internals/frame.py:1072, in DataFrame.to_pandas(self, date_as_object, *args, **kwargs)
   1042 """
   1043 Cast to a Pandas DataFrame. This requires that Pandas is installed.
   1044 This operation clones data.
   (...)
   1069 
   1070 """
   1071 record_batches = self._df.to_pandas()
-> 1072 tbl = pa.Table.from_batches(record_batches)
   1073 return tbl.to_pandas(*args, date_as_object=date_as_object, **kwargs)

NameError: name 'pa' is not defined
```
#### What is the actual behavior?

df.to_pandas() does not work, and *NameError: name 'pa' is not defined*.

#### What is the expected behavior?

polars.DataFrame.to_pandas should work

**Comment by ritchie46** [comment]
It seems that there is something wrong with your pyarrow installation. Did you restart python after you installed pyarrow?

**Comment by hengaini2055** [comment]
Yes, Thanks! I restart python, the problem is gone!

**Comment by ghuls** [comment]
https://github.com/pola-rs/polars/pull/3348
