### ISSUE TITLE
Allocation error in DataFrame.pivot(..., index=[])

### ISSUE THREAD

**Issue by adamgreg** [pola-rs/polars#3343]
#### What language are you using?

Python

#### Have you tried latest version of polars?

Yes

#### What version of polars are you using?

0.13.31

#### What operating system are you using polars on?

Windows 10 x64

#### What language version are you using

Python 3.8

#### Describe your bug.

If `DataFrame.pivot()` is called with an empty list of index columns, there is a memory allocation error.

In my application the list of index columns is not known in advance, and may or may not be empty.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
df = pl.DataFrame({'a': ['one', 'two', 'one', 'two'], 'b': [1, 2, 3, 4]})
df.pivot(columns='a', values='b', index=[], aggregate_fn='mean')
```

#### What is the actual behavior?

```python
df.pivot(columns='a', values='b', index=[], aggregate_fn='mean')

memory allocation of 17179869184 bytes failed
```

#### What is the expected behavior?

I would expect the call to succeed, grouping the original rows only by the columns specified in the "columns" argument. The result would be the same as the below:

```python
df.with_column(pl.lit(0).alias('dummy')).pivot(columns='a', values='b', index='dummy', aggregate_fn='mean').drop('dummy')

┌─────┬─────┐
│ one ┆ two │
│ --- ┆ --- │
│ f64 ┆ f64 │
╞═════╪═════╡
│ 2.0 ┆ 3.0 │
└─────┴─────┘
```

**Comment by hengaini2055** [comment]
I think you get nvarchar(max) column. When you import csv data to sql server, the str column type will be nvarchar(max) that you will get the same error info. I am sure!

**Comment by hengaini2055** [comment]
Sorry! yours are another question.

**Comment by adamgreg** [comment]
Thanks for fixing the bug so quickly. Should I open a separate feature request to support `index=[]`?

**Comment by ritchie46** [comment]
Yes, please do
