### ISSUE TITLE
Make normalization in entropy() optional

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#3345]
Now entropy() calculates as [scipy.stats.entropy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html) with normalization.
It would be great to have an option to turn on/off *normalization*, or to make normalization=False by default.
Because with normalization=True it is not an entropy as it is, but Kullback-Leibler divergence.

**Comment by ritchie46** [comment]
So scipy is acutally wrong on this? I am a bit reluctant to deviate from scipy implementation on these things.

**Comment by s-b90** [comment]
No, scipy is definitely right. They have a qk parameter for normalization, which is None by default.
From [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html):
```
If only probabilities pk are given, the entropy is calculated as S = -sum(pk * log(pk), axis=axis).
If qk is not None, then compute the Kullback-Leibler divergence S = sum(pk * log(pk / qk), axis=axis).
```
And I'm asking for this computation -sum(pk * log(pk)). Without qk and normalization.

**Comment by s-b90** [comment]
@ritchie46 I think I finally got why entropy() result is unexpected for me.
```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 2, 1, 4, 5, 4, 6],
             })
df.groupby(['group']).agg(pl.col('id').entropy())
```
In this computation, you expected that `pl.col('id')` is already pk (discrete probabilities)?
I thought, that this formula will firstly calculate pk for given series/expr and after that `-sum(pk * log(pk))`. 
So entropy() will do all job by itself.
And 
 ```python
 df.groupby(['group']).agg(pl.col('id').entropy())
 ```
 is equal to 
 ```python
 df.groupby(['group']).agg([((pl.col('id').unique_counts() / pl.col('id').len()).log() * -1 *
            (pl.col('id').unique_counts() / pl.col('id').len())).sum()])
```
So in this case normalization will be unnecessary because `sum(pk)` is always 1.


If I'm right and entropy() expected pk as input, then how to calculate this `pk` in agg? Because `(pl.col('id').unique_counts() / pl.col('id').len()` is not allowed.

**Comment by ritchie46** [comment]
Note that I've added a normalization keword argument already. Does that help you?

**Comment by ritchie46** [comment]
> Because (pl.col('id').unique_counts() / pl.col('id').len() is not allowed.

Why not?

**Comment by s-b90** [comment]
```python
df = pl.DataFrame({
    'group': ['A' ,'A', 'A', 'B', 'B', 'B', 'B'],
    'id': [1, 2, 1, 4, 5, 4, 6],
             })

 df.groupby(['group']).agg(pl.col('id').entropy(normalize=False))
 ```   
 

group | id
-- | --
str | f64
"B" | -29.888101
"A" | -1.386294
```python
df.groupby(['group']).agg(pl.col('id').entropy(normalize=True))
```


group | id
-- | --
str | f64
"B" | 1.371381
"A" | 1.039721

While expected:

group | id
-- | --
str | f64
"B" | 1.039721
"A" | 0.636514

Manually calculation raise an exception because of this #3290 
```python
df.groupby(['group']).agg([((pl.col('id').unique_counts() / pl.col('id').len()).log() * -1 *
            (pl.col('id').unique_counts() / pl.col('id').len())).sum()])
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 df.groupby(['group']).agg([((pl.col('id').unique_counts() / pl.col('id').len()).log() * -1 *
      2             (pl.col('id').unique_counts() / pl.col('id').len())).sum()])

File ~/work/data-generation/venv/lib/python3.8/site-packages/polars/internals/frame.py:5684, in GroupBy.agg(self, column_to_agg)
   5680     column_to_agg = _wrangle(column_to_agg)
   5682 elif isinstance(column_to_agg[0], pli.Expr):
   5683     return (
-> 5684         self._dataframe_class._from_pydf(self._df)
   5685         .lazy()
   5686         .groupby(self.by, maintain_order=self.maintain_order)
   5687         .agg(column_to_agg)  # type: ignore[arg-type]
   5688         .collect(no_optimization=True, string_cache=False)
   5689     )
   5691     pass
   5692 else:

File ~/work/data-generation/venv/lib/python3.8/site-packages/polars/internals/lazy_frame.py:586, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown)
    576     projection_pushdown = False
    578 ldf = self._ldf.optimization_toggle(
    579     type_coercion,
    580     predicate_pushdown,
   (...)
    584     slice_pushdown,
    585 )
--> 586 return self._dataframe_class._from_pydf(ldf.collect())

PanicException: impl error, should be a list at this point: SchemaMisMatch("Series dtype Float64 != list")
```

**Comment by ritchie46** [comment]
@s-b90 #3401 runs your query

**Comment by s-b90** [comment]
Seems that everything works fine.
Thank you!
