### ISSUE TITLE
Bug with asof_join in PyPolars

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#3362]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.25

#### What operating system are you using polars on?

Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-1022-aws x86_64)

#### What language version are you using

Python 3.8.10

#### Describe your bug.

polars as of join sometimes returns an off error:   File "/home/ubuntu/.local/lib/python3.8/site-packages/polars/internals/frame.py", line 3342, in join_asof
    self.lazy()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polars/internals/lazy_frame.py", line 475, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError("cannot take slice")

This doesn't happen when you just load some dataframes from csvs and operate on them, but happens after some sequence of other operations on those dataframes. A self contained example is given in this zip file.

[test.zip](https://github.com/pola-rs/polars/files/8666799/test.zip)

You can run test.py in this zip file. It is basically a streaming asof join implementation where the asof join is incrementally computed on streams of data from each side.

**Comment by ritchie46** [comment]
Could you try make a minimal example? Reduce all unneeded code and unneeded rows. That will help me a lot.

**Comment by ritchie46** [comment]
Can you run the query with `RUST_BACKTRACE=1` and show me the backtrace?

**Comment by marsupialtail** [comment]
It is difficult for me to produce the minimal example. I can try. But in the meantime here is the backtrace with RUST_BACKTRACE=full

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError("cannot take slice")', /github/workspace/polars/polars-core/src/frame/asof_join/mod.rs:80:91
stack backtrace:
   0:     0x7f32ee550844 - <unknown>
   1:     0x7f32ed97e29c - <unknown>
   2:     0x7f32ee5279fe - <unknown>
   3:     0x7f32ee551705 - <unknown>
   4:     0x7f32ee552509 - <unknown>
   5:     0x7f32ee552082 - <unknown>
   6:     0x7f32ee551ff6 - <unknown>
   7:     0x7f32ee551fb2 - <unknown>
   8:     0x7f32ece0d182 - <unknown>
   9:     0x7f32ece0d382 - <unknown>
  10:     0x7f32ee0b736d - <unknown>
  11:     0x7f32ee0b3eb1 - <unknown>
  12:     0x7f32ee123ad9 - <unknown>
  13:     0x7f32ee122a89 - <unknown>
  14:     0x7f32ee3f914d - <unknown>
  15:     0x7f32ee380e13 - <unknown>
  16:     0x7f32ed405513 - <unknown>
  17:           0x503b99 - <unknown>
  18:           0x56b1da - _PyEval_EvalFrameDefault
  19:           0x56939a - _PyEval_EvalCodeWithName
  20:           0x50aaa0 - <unknown>
  21:           0x56c28c - _PyEval_EvalFrameDefault
  22:           0x56939a - _PyEval_EvalCodeWithName
  23:           0x50aaa0 - <unknown>
  24:           0x56c28c - _PyEval_EvalFrameDefault
  25:           0x5f6836 - _PyFunction_Vectorcall
  26:           0x56b1da - _PyEval_EvalFrameDefault
  27:           0x56939a - _PyEval_EvalCodeWithName
  28:           0x68d047 - PyEval_EvalCode
  29:           0x67e351 - <unknown>
  30:           0x67e3cf - <unknown>
  31:           0x67e471 - <unknown>
  32:           0x67e817 - PyRun_SimpleFileExFlags
  33:           0x6b6fe2 - Py_RunMain
  34:           0x6b736d - Py_BytesMain
  35:     0x7f32ef7900b3 - __libc_start_main
  36:           0x5fa5ce - _start
  37:                0x0 - <unknown>
Traceback (most recent call last):
  File "test.py", line 137, in <module>
    results.append(executor.execute([quotes[2000:3000]], 1, 0))
  File "test.py", line 99, in execute
    ret_vals.append(joinable_trades.join_asof(joinable_quotes.drop(self.group_right_on), left_on = self.left_on, right_on = self.right_on))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polars/internals/frame.py", line 3342, in join_asof
    self.lazy()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polars/internals/lazy_frame.py", line 475, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError("cannot take slice")

**Comment by marsupialtail** [comment]
You should also be able to just run the example. It has no dependencies other than polars
