### ISSUE TITLE
Support unicode as delimiter when reading the CSV file. For example a CSV delimiter could be §

### ISSUE THREAD

**Issue by ForrestFeng** [pola-rs/polars#3374]
#### Describe your feature request

I have a CSV file with a delimiter of § 

The reason to choose a § as the delimiter in our project is that, the log message itself could have lots of "," in the log fields. To avoid this collision we have chosen a §, a rarely used Unicode char as the delimiter.

I use the following code to read it with python.

```
import polars as pl 
df = pl.read_csv(r"path/to/test.log", sep="§")
```

 It is expected to read the CSV file successfully. But, it reports errors

```
~\Anaconda3\lib\site-packages\polars\functions.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, columns, rechunk, encoding, n_threads, dtype, new_columns, use_pyarrow, low_memory, comment_char, storage_options, null_values)
    257                     skip_rows=skip_rows, autogenerate_column_names=not has_headers
    258                 ),
--> 259                 pa.csv.ParseOptions(delimiter=sep),
    260                 pa.csv.ConvertOptions(
    261                     column_types=None,

~\Anaconda3\lib\site-packages\pyarrow\_csv.pyx in pyarrow._csv.ParseOptions.__init__()

~\Anaconda3\lib\site-packages\pyarrow\_csv.pyx in pyarrow._csv.ParseOptions.delimiter.__set__()

~\Anaconda3\lib\site-packages\pyarrow\_csv.pyx in pyarrow._csv._single_char()

ValueError: Expecting an ASCII character
```

With the same file, the pandas can open it successfully. 
```
import pandas as pd
df = pd.read_csv(r"path/to/test.log", sep="§", encoding='utf8', engine='python')
```

Suggest supporting the Unicode delimiters.

The test.log content is listed below with one header and one log entry.
```
sequenceid§time§logger§level§processid§processname§threadid§threadname§machinename§message§properties
104880§2018-10-01 00:00:12.6162§Services.Monitoring.SystemPerformanceMonitor§Debug§11752§Services.Logging§27§§DESKTOP-D5NFLAJ§"Total CPU usage = 46.85375%, Free RAM = 8.352539 GB, Page File Usage = 0%  Pages swapped/disk: 0.6660985 [Pages/sec]
process use in properties."§chrome 13332∈CPU:   0%   RAM:     21 MB  Threads:   13⊙chrome 13352∈CPU:   0%   RAM:      8 MB  Threads:    2

```

**Comment by ritchie46** [comment]
This has been discussed before (see #2728) and is something we will not add. There are plenty of single byte characters to choose from likely not occur in your data. Here is some inspiration: https://github.com/pola-rs/polars/issues/2728#issuecomment-1047789511

Having a unicode char as delimiter that consists of multiple bytes, means we have to search for this byte boundary every time. This is expensive.
