### ISSUE TITLE
Polars serialize and deserialize error 

### ISSUE THREAD

**Issue by RDWimmers** [pola-rs/polars#3375]
#### What language are you using?

Python

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.13.31

#### What operating system are you using polars on?

Linux

#### What language version are you using
python 3.9

#### Describe your bug.

Serialize and deserialize like below, not possible in polars >= "0.13.6"

```
import polars as pl

pl.read_json(
    pl.DataFrame({"A": [1, 2, 3, 4], "B": [5, 6, 7, 8]}).to_json()
)
```

Result in `FileNotFoundError: No such file or directory (os error 2)`

#### What are the steps to reproduce the behavior?

see codeblock above.

#### What is the actual behavior?

see codeblock above.

#### What is the expected behavior?

in  polars <= "0.13.5" the JSON object is read as a polars DataFrame.

**Comment by ritchie46** [comment]
Right, the json is seen as a file path. The function accepts a `str` as file path or file like object.

Try:

```python
import io
pl.read_json(
    io.StringIO(pl.DataFrame({"A": [1, 2, 3, 4], "B": [5, 6, 7, 8]}).to_json())
)
```

**Comment by ritchie46** [comment]
No it is because it was inconsistent with the rest of our API. All `pl.read_<>` accept a file path or a file object.

The `io.StringIO` wrap should not matter much for performance.
