### ISSUE TITLE
Strange behaviour for specific type of datetime string

### ISSUE THREAD

**Issue by bbuman** [pola-rs/polars#3380]
#### What language are you using?

**Rust**

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

polars = "0.21.1"

#### What operating system are you using polars on?

MacOS Monterey 12.3.1 

#### What language version are you using
rustc 1.60.0

#### Describe your bug.

I'm reading a CSV using the ```with_parse_dates(true)``` option. The column name for the timestamps is called "validdate". The format looks like this: "2022-05-10T07:07:12Z". The column data type is correctly represented as datetime[μs] (see below). But only the first entry is converted, while all other rows have "null". 
However, if I remove the "Z" character from the first line of the CSV, everything is parsed correctly to datetime[μs] (see further below).

```text
shape: (6, 5)
┌────────┬───────┬─────────────────────┬────────┬──────────────┐
│ lat    ┆ lon   ┆ validdate           ┆ t_2m:C ┆ precip_1h:mm │
│ ---    ┆ ---   ┆ ---                 ┆ ---    ┆ ---          │
│ f64    ┆ f64   ┆ datetime[μs]        ┆ f64    ┆ f64          │
╞════════╪═══════╪═════════════════════╪════════╪══════════════╡
│ 46.685 ┆ 7.953 ┆ 2022-05-10 07:07:12 ┆ 6.1    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ null                ┆ 8.8    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ null                ┆ 9.5    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ null                ┆ 10.3   ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ null                ┆ 11.2   ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ null                ┆ 11.7   ┆ 0.0          │
└────────┴───────┴─────────────────────┴────────┴──────────────┘
```
```text
shape: (6, 5)
┌────────┬───────┬─────────────────────┬────────┬──────────────┐
│ lat    ┆ lon   ┆ validdate           ┆ t_2m:C ┆ precip_1h:mm │
│ ---    ┆ ---   ┆ ---                 ┆ ---    ┆ ---          │
│ f64    ┆ f64   ┆ datetime[μs]        ┆ f64    ┆ f64          │
╞════════╪═══════╪═════════════════════╪════════╪══════════════╡
│ 46.685 ┆ 7.953 ┆ 2022-05-10 07:07:12 ┆ 6.1    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ 2022-05-10 08:07:12 ┆ 8.8    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ 2022-05-10 09:07:12 ┆ 9.5    ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ 2022-05-10 10:07:12 ┆ 10.3   ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ 2022-05-10 11:07:12 ┆ 11.2   ┆ 0.0          │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 46.685 ┆ 7.953 ┆ 2022-05-10 12:07:12 ┆ 11.7   ┆ 0.0          │
└────────┴───────┴─────────────────────┴────────┴──────────────┘
```
#### What are the steps to reproduce the behavior?

```rust
use polars::prelude::*;

fn main() {
    let df = example().unwrap();
    println!("{:?}", df);
}

fn example() -> Result<DataFrame> {
    CsvReader::from_path("sample.csv")?
        .has_header(true)
        .with_delimiter(b';')
        .with_parse_dates(true)
        .finish()
}
```

**Example**

**sample.csv**
-> Please note that you can just set the timestamp in the first row to "2022-05-10T07:07:12" and it will work.
```text
lat;lon;validdate;t_2m:C;precip_1h:mm
46.685;7.953;2022-05-10T07:07:12Z;6.1;0.00
46.685;7.953;2022-05-10T08:07:12Z;8.8;0.00
46.685;7.953;2022-05-10T09:07:12Z;9.5;0.00
46.685;7.953;2022-05-10T10:07:12Z;10.3;0.00
46.685;7.953;2022-05-10T11:07:12Z;11.2;0.00
46.685;7.953;2022-05-10T12:07:12Z;11.7;0.00
```

#### What is the expected behavior?

I would like rust to be consistent. If it cannot parse it correctly, then it should tell me so. I find it quite strange that rust can convert the first row correctly and then sets the others to null. The crate 'chrono' (chrono = "0.4.19") is able to read these strings easily like shown below. So in theory it should be possible to define a working solution for polars.

```rust
    let my_str = String::from("2022-05-10T07:07:12Z")
    let res = my_str.parse::<DateTime<Utc>>().unwrap();
    println!("{}", res);
```

**Comment by ritchie46** [comment]
Thanks, I will fix it.

> he crate 'chrono' (chrono = "0.4.19") is able to read these strings easily like shown below. So in theory it should be possible to define a working solution for polars.

Polars does not use chrono for parsing in csv. We have our own more opinionated parser for performance reasons.

**Comment by bbuman** [comment]
Thank you!

Looking forward to the fix!

chrono -> then I must have misunderstood something in the documentation, sorry about that.
