### ISSUE TITLE
get_group is slow

### ISSUE THREAD

**Issue by yanyu2015** [pola-rs/polars#3383]
When the number of group is large ( for example 1M), `get_group` is slow in `pandas`, so I try to use `polars`.
But it seems `get_group` is also slow in `polars`. 
```python
# in pandas
%timeit fgi = fg.get_group(7776113736362340)
140 µs ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# in polars
%timeit fgpl.get_group(7776113736362340)
1.47 s ± 41.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
is it normal or Is there a faster way

**Comment by ritchie46** [comment]
We should deprecate that method.

I would go for `partition_by`

**Comment by ghuls** [comment]
@ritchie46 The groups() method is the slow part.

```python
In [23]: df = pl.DataFrame(pl.Series("a", pl.arange(0, 1000000, eager=True).shuffle()))

In [24]: df
Out[24]: 
shape: (1000000, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 184709 │
├╌╌╌╌╌╌╌╌┤
│ 925917 │
├╌╌╌╌╌╌╌╌┤
│ 795542 │
├╌╌╌╌╌╌╌╌┤
│ 59722  │
├╌╌╌╌╌╌╌╌┤
│ ...    │
├╌╌╌╌╌╌╌╌┤
│ 462165 │
├╌╌╌╌╌╌╌╌┤
│ 979878 │
├╌╌╌╌╌╌╌╌┤
│ 439139 │
├╌╌╌╌╌╌╌╌┤
│ 447325 │
└────────┘

In [25]: %time df.filter(pl.col("a") == 888888)
CPU times: user 3.83 ms, sys: 0 ns, total: 3.83 ms
Wall time: 2.51 ms
Out[25]: 
shape: (1, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 888888 │
└────────┘

In [26]: %time df.filter(pl.col("a") == 888888).groupby("a").get_group(888888)
CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 952 µs
Out[26]: 
shape: (1, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 888888 │
└────────┘

In [27]: %time df.filter(pl.col("a") == 888888)
CPU times: user 2.52 ms, sys: 194 µs, total: 2.71 ms
Wall time: 1.85 ms
Out[27]: 
shape: (1, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 888888 │
└────────┘

In [28]: %time df.filter(pl.col("a") == 888888).groupby("a").get_group(888888)
CPU times: user 5.76 ms, sys: 137 µs, total: 5.9 ms
Wall time: 3.73 ms
Out[28]: 
shape: (1, 1)
┌────────┐
│ a      │
│ ---    │
│ i64    │
╞════════╡
│ 888888 │
└────────┘

In [29]: g = df.groupby("a")

In [30]: %time gs = g.groups()
CPU times: user 4.8 s, sys: 68.6 ms, total: 4.87 s
Wall time: 4.65 s

```

**Comment by ritchie46** [comment]
Yes, this `groups()` is basically the group by operation. That's why I want to deprecate this method. Every access will trigger a new groupby and intermediate calls are not cached.

This is a relic from when we still tried to adhere to pandas API. A long long time ago. It should go. :)

**Comment by yanyu2015** [comment]
> We should deprecate that method.
> 
> I would go for `partition_by`

is `partition_by` available in current version? It don't work in ` 0.13.22`

**Comment by yanyu2015** [comment]
@ghuls I have tried to use `filter`
```
%timeit -r5 -n1000 fdfpl.filter(pl.col("id") == 7776113736362340)
1.06 ms ± 33.8 µs per loop (mean ± std. dev. of 5 runs, 1000 loops each)
```
It's faster while still slower than `get_group` in `pandas`

**Comment by ritchie46** [comment]
> > We should deprecate that method.
> > I would go for `partition_by`
> 
> is `partition_by` available in current version? It don't work in ` 0.13.22`

What do you mean by "it don't work"?

**Comment by yanyu2015** [comment]
```python
df1 = pl.DataFrame(
    {
        "foo": ["A", "A", "B", "B", "C"],
        "N": [1, 2, 2, 4, 2],
        "bar": ["k", "l", "m", "m", "l"],
    }
)
df1.partition_by(groups="foo", maintain_order=True)
```
returns `AttributeError: partition_by`

**Comment by ritchie46** [comment]
I just tried and can confirm your snippet runs on `0.13.22`. Are you entirely sure you are running latest version?

**Comment by yanyu2015** [comment]
```
pl.__version__
'0.13.22'
```

**Comment by ritchie46** [comment]
Sorry I meant `0.13.32`. In any case, update.

**Comment by yanyu2015** [comment]
I updated to `0.13.32` and when process I DataFrame with a shape of `(1812889, 4)` the kernel restart again and again (about 8G memory is free).

**Comment by ritchie46** [comment]
Update again and it should work. :)

**Comment by ritchie46** [comment]
> Update again and it should work. :)

To `0.13.34`

**Comment by yanyu2015** [comment]
great! in  it works well and speed is so fast
```
%timeit followdfplg['7776113736362340']
64.8 ns ± 3.34 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
and it seems memory expensive，how much multiples is the memory usage of the dataset size？

**Comment by ritchie46** [comment]
If you `partition_by` you create a new `DataFrame` per group. So you will be doubling memory at least.

**Comment by yanyu2015** [comment]
thank you so much! Now this issue can be closed.
