### ISSUE TITLE
partition_by produces segmentation fault

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3390]
polars 0.13.32
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
`partition_by` seems to have a limit as to the number of partitioned groups that it can create.  When I pass this limit, the result is a segmentation fault.

#### What are the steps to reproduce the behavior?
In this example, when there are 5,330 distinct combination of groupby keys, the code runs normally.
```python3
import polars as pl

nbr_comb = 5330
df = pl.DataFrame(
    {
        "col1": pl.arange(0, nbr_comb, eager=True),
    }
)

len(df.partition_by(groups=["col1"], as_dict=True))
```
```
>>> len(df.partition_by(groups=["col1"], as_dict=True))
5330
```
Increasing `nbr_comb` to 5,331 produces a seg fault:
```
>>> nbr_comb = 5331
>>> df = pl.DataFrame(
...     {
...         "col1": pl.arange(0, nbr_comb, eager=True),
...     }
... 
... )
>>> len(df.partition_by(groups=["col1"], as_dict=True))
Segmentation fault (core dumped)

```
#### Setting `as_dict=False`
If I set `as_dict` to False, then 5,331 combinations produces no error:
```
>>> len(df.partition_by(groups=["col1"], as_dict=False))
5331
```
However, raising `nbr_comb` to 5,332 raises a seg fault:
```
>>> nbr_comb = 5332
>>> df = pl.DataFrame(
...     {
...         "col1": pl.arange(0, nbr_comb, eager=True),
...     }
... 
... )
>>> len(df.partition_by(groups=["col1"], as_dict=False))
Segmentation fault (core dumped)
```

#### Other Notes:
* Watching RAM usage in `top` on my machine shows that memory usage is not a problem.
* `[pl.DataFrame({'col1':[itr_nbr]}) for itr_nbr in range(10_000)]` creates a list of 10,000 small DataFrames without an error, suggesting that the seg fault is not due to Python itself.

**Comment by cbilot** [comment]
Another oddity of this bug: the seg fault may not be directly related to the number of groups.  For example, on my machine, this runs normally in a fresh session of the Python interpreter:
```python3
import polars as pl

nbr_comb = 6001
df = pl.DataFrame(
    {
        "col1": pl.arange(0, nbr_comb, eager=True),
    }
)

len(df.partition_by(groups=["col1"], as_dict=True))
```
```
>>> len(df.partition_by(groups=["col1"], as_dict=True))
6001
```
However, if I run just the `partition_by` code a second time (without restarting the interpreter):
```
>>> len(df.partition_by(groups=["col1"], as_dict=True))
Segmentation fault (core dumped)
```
Thus, the MWE from my previous comment may be more about running the `partition_by` a second time during the same Python session, and not the actual values used.

**Comment by cbilot** [comment]
One other note: the appearance of the seg fault seems non-deterministic.  But I've noticed that raising `nbr_comb` to a sufficiently high value gives a near-certain chance of producing a seg fault.
```python3
import polars as pl

nbr_comb = 2**16
df = pl.DataFrame(
    {
        "col1": pl.arange(0, nbr_comb, eager=True),
    }
)

len(df.partition_by(groups=["col1"], as_dict=False))
```
```
>>> import polars as pl
>>> nbr_comb = 2**16
>>> df = pl.DataFrame(
...     {
...         "col1": pl.arange(0, nbr_comb, eager=True),
...     }
... 
... )
>>> len(df.partition_by(groups=["col1"], as_dict=False))
Segmentation fault (core dumped)
```

**Comment by cbilot** [comment]
One final note: the seg faults do not occur with polars 0.13.31
```
>>> import polars as pl
>>> nbr_comb = 2**16
>>> df = pl.DataFrame(
...         {
...                     "col1": pl.arange(0, nbr_comb, eager=True),
...                 }
... 
... )
>>> len(df.partition_by(groups=["col1"]))
65536
>>> pl.__version__
'0.13.31'
```

**Comment by ritchie46** [comment]
Thanks @cbilot investigating it now.

**Comment by ritchie46** [comment]
Its a stackoverflow.
