### ISSUE TITLE
pa (pyarrow) not defined when running to_pandas

### ISSUE THREAD

**Issue by reidaruss** [pola-rs/polars#3398]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

polars==0.13.29

#### What operating system are you using polars on?
Windows 11 Home
Version	10.0.22000 Build 22000

#### What language version are you using
python 3.7

#### Describe your bug.

When reading in a csv file then doing to_pandas, an error is thrown saying that 'pa' is not defined in frame.py (pyarrow is installed).

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```
import polars as pl
import pandas as pd

q = (
    pl.scan_csv("my_file.csv",ignore_errors=True)
)
df = q.collect()
df1 = df.to_pandas()
```

**Example**

```python
import polars as pl
import numpy as np

# Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
})
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

Please remove clutter from your examples. Only include the bare minimum to produce the result.
So please:

* strip unused columns
* use short distinguishable names
* don't include unneeded computations

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9568\2252843403.py in <module>
     10 )
     11 df = q.collect()
---> 12 df1 = df.to_pandas()

c:\Users\reida\.conda\envs\navigator_primary_37\lib\site-packages\polars\internals\frame.py in to_pandas(self, date_as_object, *args, **kwargs)
   1070         """
   1071         record_batches = self._df.to_pandas()
-> 1072         tbl = pa.Table.from_batches(record_batches)
   1073         return tbl.to_pandas(*args, date_as_object=date_as_object, **kwargs)
   1074 

NameError: name 'pa' is not defined
```

#### What is the expected behavior?

Return a pandas dataframe

**Comment by slonik-az** [comment]
> Install pyarrow and run again

Missing `pyarrow` is popping up in the issues almost every week. Should it be added to polars' `pip` dependency list so that it is automatically installed?

**Comment by ritchie46** [comment]
pyarrow is an optional dependency. Polars works for many operations without pyarrow. This saves a large dependency.

If you want to install optional dependencies this can be done.

`pip install polars[pyarrow]`

We've improved the error message saying that pyarrow should be intstalled and we mention it in many of the docstrings that require pyarrow.

**Comment by ritchie46** [comment]
Maybe we should mention that pip install in the readme?

**Comment by reidaruss** [comment]
Ah I am stupid. Before this error there was another saying that I was missing the pyarrow dependency, so I installed pyarrow. After installing pyarrow the above was the error I was getting. Because I had just installed it I assumed it was not my installation but it seems that I merely needed to restart my runtime to source the new installation. Very sorry for the unneeded bug report, it can be closed. Thanks for responding so quickly.

**Comment by reidaruss** [comment]
The weird thing is this is usually not the case for other libraries that I have pip installed in the past. For example if I didnt have numpy installed I can pip install it and immediately use it without restarting anything. Maybe something specific with Rust or pyarrow.
