### ISSUE TITLE
`explode()` ignores empty columns

### ISSUE THREAD

**Issue by NilsBarlaug** [pola-rs/polars#3402]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.34

#### What operating system are you using polars on?

Ubuntu 20.04

#### What language version are you using

Python 3.8

#### Describe your bug.

`explode()` does nothing when there are no rows.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import pyarrow

df = pl.DataFrame({"a": pyarrow.array([], type=pyarrow.large_list(pyarrow.int32()))})

print(df.dtypes)
print(df.explode("a").dtypes)

print()

df = pl.DataFrame({"a": pyarrow.array([[3]], type=pyarrow.large_list(pyarrow.int32()))})

print(df.dtypes)
print(df.explode("a").dtypes)
```

#### What is the actual behavior?

Output:
```
[<polars.datatypes.List object at 0x7ffaac196e20>]
[<polars.datatypes.List object at 0x7ffaac15f550>]

[<polars.datatypes.List object at 0x7ffa2809d1f0>]
[<class 'polars.datatypes.Int32'>]
```

#### What is the expected behavior?

I expect the type of the column to change regardless of whether there are rows or not.

**Comment by ritchie46** [comment]
Thanks.. That should be the case indeed. Will fix it.
