### ISSUE TITLE
Panic on compression when writing large parquet files.

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#3407]
#### What language are you using?

Rust

#### Which feature gates did you use?

latest:
`polars = { git = "https://github.com/pola-rs/polars", rev = "91e089b920b0928eb1dbfa0c1bd7ba0935e92f8f", features = ["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"] }`

#### Describe your bug.

Writing "large" parquet files fails

#### What are the steps to reproduce the behavior?

```rust
    #[test]
    fn write_large_parquet() -> Result<()> {
        let n = 1000;
        let vec: Vec<i32> = (0..n).collect();
        let mut df = DataFrame::new(vec![Series::new("num", vec)])?;
        let mut buf = Cursor::new(Vec::new());
        ParquetWriter::new(&mut buf).finish(&mut df)?;
        Ok(())
    }
```

#### What is the actual behavior?

Running with `n = 100` the test passes but for `n=1000` it panics with:
```
running 1 test
Error: External format error: underlying IO error: Compression failed
```

I believe this to be fixed in https://github.com/jorgecarleitao/parquet2/pull/140 but Arrow and Polars would have to be updated but I'm not sure if this is actually the cause.

Feel free to close this issue if you don't think it gives value to track this on the Polars repo.

**Comment by ritchie46** [comment]
Yes, this should already been fixed. @jorgecarleitao issued a new parquet2 release a few days ago. It should be automatically used if you remove your lockfile.

**Comment by SimonSchneider** [comment]
I'll give it a try, must have missed that

**Comment by ritchie46** [comment]
> Was not aware that the lockfile could cause issues like that.

No worries. A lockfile fixes the versions and does not automatically take latest patch releases. I believe `cargo update` can also help.
