### ISSUE TITLE
Using apply in eval context causes Python interpreter to hang

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3409]
python 3.10.4
polars 0.13.34
Linux Mint 20.3
#### Describe your bug.
When using the `apply` function in an eval context (`cumulative_eval` or `arr.eval`), the python interpreter becomes non-responsive.  

#### Warning: the code below may cause the interpreter to become non-responsive.  Save any work before attempting this.
```python3
import polars as pl
pl.DataFrame(
    {
        "col1": [[1, 2, 3]],
    }
).with_column(pl.col("col1").arr.eval(pl.col("").apply(lambda x: x)))
```
When I run this code in interactive mode in Linux, the interpreter simply stops responding.  Not even a keyboard interrupt will work.  `top` in Linux shows no CPU activity associated with the Python interpreter.  The only solution seems to be to terminate the process from Linux.

#### Whether it is valid to use `apply` in this context
Using `apply` in an `eval` context may or may not be valid.  My concern is the result - an interpreter that simply hangs.  This is particularly confusing when running a python program from the command line -- the program appears to be running, but never returns.

This results is a slow debug process because there is no stack trace or error message that leads to the offending statement.

#### Other Notes
* I'm not sure if this is a Linux-only phenomenon.  (I don't have a copy of Windows.)
* This also happens with the new `cumulative_eval` context.  (`cumulative_eval` is not available in polars 0.13.34, but I compiled the source code to check)
* The Python interpreter becomes non-responsive whether I run the `apply` statement in interactive mode, as part of a program run from the command line, or as code imported from a module.
* I don't know whether this affects IPython.  (I don't use IPython.)

**Comment by ritchie46** [comment]
Right.. That's probably a deadlock on the GIL. I will fix it.
