### ISSUE TITLE
cumulative_eval in windowed expressions

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3414]
polars 0.13.36
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
When `cumulative_eval` is used in a windowed expression, the `cumulative_eval` is executed on the entire series backed by the expression, rather than on the windowed groups.
#### What are the steps to reproduce the behavior?
If we attempt to use `cumulative_eval` to simulate a windowed `cummax`, we get ...  
```python3
import polars as pl
df = pl.DataFrame(
    {
        "group": [0, 0, 0, 1, 1, 1],
        "val": [20, 40, 30, 2, 4, 3],
    }
)

df.with_column(
    pl.col("val")
    .cumulative_eval(pl.element().max())
    .over("group")
    .alias("cumulative_eval_max")
)
```
```
shape: (6, 3)
┌───────┬─────┬─────────────────────┐
│ group ┆ val ┆ cumulative_eval_max │
│ ---   ┆ --- ┆ ---                 │
│ i64   ┆ i64 ┆ i64                 │
╞═══════╪═════╪═════════════════════╡
│ 0     ┆ 20  ┆ 20                  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 40  ┆ 40                  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 30  ┆ 40                  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 2   ┆ 40                  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 4   ┆ 40                  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 3   ┆ 40                  │
└───────┴─────┴─────────────────────┘
```
Clearly, `cumulative_eval` is operating on the entire series backed by the expression - before any aggregation by the `over` expression.
#### What is the expected behavior?
I expected that this would match the `cummax` function when windowed.
```python3
df.with_column(
    pl.col("val")
    .cummax()
    .over("group")
    .alias("cummax")
)
```
```
shape: (6, 3)
┌───────┬─────┬────────┐
│ group ┆ val ┆ cummax │
│ ---   ┆ --- ┆ ---    │
│ i64   ┆ i64 ┆ i64    │
╞═══════╪═════╪════════╡
│ 0     ┆ 20  ┆ 20     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 0     ┆ 40  ┆ 40     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 0     ┆ 30  ┆ 40     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1     ┆ 2   ┆ 2      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1     ┆ 4   ┆ 4      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1     ┆ 3   ┆ 4      │
└───────┴─────┴────────┘
```
If `cumulative_eval` is intended to act like `map` in a windowed expression, will there be a `cumulative_apply` for windowed expressions?

**Comment by ritchie46** [comment]
Good question. I will have to investigate this. The `eval` and `window` expressions are both special cases which might not work together nicely. Thanks for the issue report. I shall take a look.
