### ISSUE TITLE
struct: arr.head and arr.tail give incorrect results for list of structs

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3415]
polars 0.13.36
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
`arr.head` and `arr.tail` give the wrong answers with a column that is a list of structs.
#### What are the steps to reproduce the behavior?
Apologies up front for the awkward code -- I don't know an elegant pattern for creating a column of list of structs.
```python3
import polars as pl
pl.DataFrame(
    data=[
        [
            pl.struct(
                exprs=[
                    pl.Series(name="x", values=[1, 3]),
                    pl.Series(name="y", values=[4, 6]),
                ],
                eager=True,
            ),
        ],
        [
            pl.struct(
                exprs=[
                    pl.Series(name="x", values=[10, 20, 30]),
                    pl.Series(name="y", values=[40, 50, 60]),
                ],
                eager=True,
            ),
        ],
    ],
    columns=["list_of_struct"],
    orient="row",
).with_columns([
    pl.col("list_of_struct").arr.head(1).alias("head"),
    pl.col("list_of_struct").arr.tail(1).alias("tail")
])
```
```
shape: (2, 3)
┌─────────────────────────────┬──────────────────┬──────────────────┐
│ list_of_struct              ┆ head             ┆ tail             │
│ ---                         ┆ ---              ┆ ---              │
│ list [struct[2]]            ┆ list [struct[2]] ┆ list [struct[2]] │
╞═════════════════════════════╪══════════════════╪══════════════════╡
│ [{1,4}, {3,6}]              ┆ [{1,4}]          ┆ [{30,60}]        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [{10,40}, {20,50}, {30,60}] ┆ [{1,4}]          ┆ [{30,60}]        │
└─────────────────────────────┴──────────────────┴──────────────────┘
```
#### What is the expected behavior?
In the `head` column, the first row is correct, but not the second row.  In the `tail` column, the second row is correct, but not the first row.
#### Comparison: a list of ints
As a comparison, the `arr.head` and `arr.tail` expressions work correctly for lists of integers.
```python3
pl.DataFrame(
    data=[
        pl.Series(name="x", values=[[1, 2], [10, 20, 30]]),
    ],
    columns=["list_of_int"],
).with_columns([
    pl.col("list_of_int").arr.head(1).alias("head"),
    pl.col("list_of_int").arr.tail(1).alias("tail")
])
```
```
shape: (2, 3)
┌──────────────┬────────────┬────────────┐
│ list_of_int  ┆ head       ┆ tail       │
│ ---          ┆ ---        ┆ ---        │
│ list [i64]   ┆ list [i64] ┆ list [i64] │
╞══════════════╪════════════╪════════════╡
│ [1, 2]       ┆ [1]        ┆ [2]        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [10, 20, 30] ┆ [10]       ┆ [30]       │
└──────────────┴────────────┴────────────┘
```
#### Other Notes:
In some sense, this is a follow-up to #3404.  The fix for #3404 yields a column whose dtype is a list of structs.  Currently, however, most of the List context expressions raises exceptions when used with a list of structs.  And some that do not raise exceptions yield the wrong results (e.g., `arr.head` and `arr.tail`).

If list context expressions do not support lists of structs at this time, perhaps `arr.head` and `arr.tail` should raise an exception (rather than yield an incorrect result).

On the other hand, if the intention is to support lists of structs, I can create separate issue reports for expressions that probably should support lists of structs, as well as issue reports for expressions that currently produce incorrect results.  This may lead to several issue reports.

**Comment by ritchie46** [comment]
> On the other hand, if the intention is to support lists of structs, I can create separate issue reports for expressions that probably should support lists of structs, as well as issue reports for expressions that currently produce incorrect results. This may lead to several issue reports

Please do. These are all bugs that have to be flattened out. The struct support is fairly new and these issue really help stabilize it.

**Comment by ritchie46** [comment]
> I don't know an elegant pattern for creating a column of list of structs.

I think we should support this in `pl.DataFrame` now. We have all rust code in place.
