### ISSUE TITLE
ParquetReader missed `with_compression` method

### ISSUE THREAD

**Issue by attila-lin** [pola-rs/polars#3417]
#### What language are you using?

Rust

#### Which feature gates did you use?

["lazy", "parquet"]

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

polars = { version = "0.21.1", features = ["lazy", "parquet"] }

#### What operating system are you using polars on?

I want to read parquet file wich compressed with `snap`

#### What language version are you using

Rust v1.63.0-nightly

#### Describe your bug.

gets the following error
```
Polars(ArrowError(ExternalFormat("underlying thrift error: bad data")))
```

#### What is the expected behavior?

I think the `ParquetReader` should have the same method with [ParquetWriter](https://docs.rs/polars/latest/polars/prelude/struct.ParquetWriter.html#method.with_compression) too.

**Comment by ritchie46** [comment]
The compression type is detected automatically. It might be that you are reading an invalid parquet file or that there is a bug upstream in parquet2/arrow2.

If you think the file is correct can you open an issue upstream?
