### ISSUE TITLE
Rolling quantile speed up

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#3434]
Big fan of the library, very much appreciate the work. 

I think it would be nice to improve rolling quantile speed, Currently it's much slower than pandas. 

```python
%%timeit 
pd.Series(np.random.rand(1000000)).rolling(100).quantile(0.9)
```

    301 ms ± 523 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

```python
%%timeit 
pl.Series(np.random.rand(1000000)).rolling_quantile(0.9, window_size = 100)
```

    3.37 s ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by ritchie46** [comment]
Alright I will take a look in a few days. I already know  a good optimization. Currently we sort every window where we should actually only insert a single value at every window slide.

**Comment by kdcd** [comment]
Big thanks for the blazingly fast response and fix !

**Comment by ritchie46** [comment]
No worries. Improvements for `rolling_sum/min/max/mean` also comping up.

**Comment by AhmedThahir** [comment]
> No worries. Improvements for `rolling_sum/min/max/mean` also comping up.

Were these implemented?

**Comment by cmdlineluser** [comment]
@AhmedThahir I'm assuming this is the relevant PR (2 days after the last comment)

- https://github.com/pola-rs/polars/pull/3466
