### ISSUE TITLE
Support "Between Join" feature in core layer

### ISSUE THREAD

**Issue by higumachan** [pola-rs/polars#3438]
We rarely want to specify a range when joining dataframes.
In pandas, we used this library for that case.
https://github.com/archiba/pandas_bj

I think that for "polars" it would be better to implement this in polars_core like asof_join, but what do you think?

Also, I would like to implement this feature myself.

**Comment by zundertj** [comment]
Closing in favor of #4206, as it has more context.

@higumachan : There seems to be demand for this feature, so I am sure a PR is welcome.
