### ISSUE TITLE
struct: filter produces inconsistent results

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3440]
polars 0.13.37+ (compiled up to commit 2d3727e)
python 3.10.4
Linux Mint 20.3
#### Describe your bug.
When working with a DataFrame with two columns of dtype struct, the `filter` method produces inconsistent results.

The behavior of the filter also raises the question: **Two instances of a struct are equal if-and-only-if ...** ?

#### What are the steps to reproduce the behavior?
Let's start with this example, and break things into cases.
#### Case 1: Everything matches
```python3
import polars as pl

df = pl.DataFrame(
    {
        "col1": [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
        "col2": [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
    }
)
print(df)
df.filter(pl.col('col1') == pl.col('col2'))
```
```
>>> print(df)
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {1,2}     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3,4}     │
└───────────┴───────────┘
>>> df.filter(pl.col('col1') == pl.col('col2'))
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {1,2}     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3,4}     │
└───────────┴───────────┘
```
The filter produces the result I expected.  And perhaps I should be explicit as to how I arrived at that conclusion:
* The structs in `col1` and `col2` have the same number of fields (two).
* The field names of the structs match: 'a' and 'b'.  (Though these are not shown in the display.)
* The corresponding values associated with each field name are compatible for comparison (according to polars' rules) and are determined to be equal.  That is, in the first row, `col1.a` = 1 and `col2.a` = 1; likewise, `col1.b` = 2 and `col2.b` = 2.

#### Case 2: likely a bug
Let's start with Case 1, but change a single value in one of the structs: in the first row, we'll change `col2.a` to 2.
```python3
df = pl.DataFrame(
    {
        "col1": [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
        "col2": [{"a": 2, "b": 2}, {"a": 3, "b": 4}],
    }
)
df
df.filter(pl.col('col1') == pl.col('col2'))
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {2,2}     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3,4}     │
└───────────┴───────────┘
>>> df.filter(pl.col('col1') == pl.col('col2'))
shape: (0, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
└───────────┴───────────┘
```
This result is clearly a bug.  Changes to the structs in row 1 should have no impact on the filter's result for row 2.
#### Case 3: inner dtypes that are compatible for comparison
Starting with Case 1, we'll change the dtype of `col2.a` to floats.
```python3
 df = pl.DataFrame(
    {
        "col1": [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
        "col2": [{"a": 1.0, "b": 2}, {"a": 3.0, "b": 4}],
    }
)
print(df)
df.filter(pl.col('col1') == pl.col('col2'))
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {1.0,2}   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3.0,4}   │
└───────────┴───────────┘
>>> df.filter(pl.col('col1') == pl.col('col2'))
shape: (0, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
└───────────┴───────────┘
```
I did not expect this result.  According to comparison rules in Polars for numeric types, the integers from `col1.a` would be cast to floats, and then compared to `col2.a`.  If so, then the filter should have selected both rows.
#### Case 4: re-ordering the field names
We'll start with Case 1, but we'll simply re-order the field names (by changing the order of the items in the dictionaries in the constructor).
```python3
df = pl.DataFrame(
    {
        "col1": [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
        "col2": [{"b": 2, "a": 1}, {"b": 4, "a": 3}],
    }
)
df
df.filter(pl.col('col1') == pl.col('col2'))
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {2,1}     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {4,3}     │
└───────────┴───────────┘
>>> df.filter(pl.col('col1') == pl.col('col2'))
shape: (0, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
└───────────┴───────────┘
```
Edit: My confusion stemmed from a bug in the constructor.  I filed #3441 about that.

If both field names and field order matters, we may have implementation issues to sort out, as many Python users view dictionaries as collections of key-value pairs, where order of the keys is not necessarily a concern.

### Discussion
I'll stop here.  (There are more issues to discuss, and this post is getting long.)

Before we proceed further, we should probably nail down what equality means for a struct.  What types of structs are compatible for comparison purposes?

And what is the definition of the dtype for a struct?  I think this matters, particularly when we place structs into a list in Polars.  For example, must the field names be in the same order for each struct in the list?  Must field name match for each struct in the list?

**Comment by cbilot** [comment]
I had another thought.  Would one way to look at this be: Two structs are equal **iff** their corresponding DataFrames would be equal using `frame_equal`?

For example, comparing two columns of structs for equality, a filter test would look like:
```python3
# s_list is a list of two series/columns passed by `polars.map`
def struct_equal_filter(s_list: List) -> pl.Boolean:
    s1, s2 = s_list
    return pl.Series(
        values=[
            s1.slice(i, 1)
            .struct.to_frame()
            .frame_equal(s2.slice(i, 1).struct.to_frame())
            for i in range(s1.len())
        ]
    )
```
Running this filter on the cases would yield:
#### Case 1:
```python3
df.filter(pl.map([pl.col("col1"), pl.col("col2")], struct_equal_filter))
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {1,2}     │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3,4}     │
└───────────┴───────────┘
```

#### Case 2:
```
shape: (1, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {3,4}     ┆ {3,4}     │
└───────────┴───────────┘
```
(The results of the filter for row 1 don't affect the results for row 2)
#### Case 3:
```
shape: (2, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {1,2}     ┆ {1.0,2}   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {3,4}     ┆ {3.0,4}   │
└───────────┴───────────┘
```
(`frame_equal` is automatically casting the integers to floats for testing equality)
#### Case 4:
```
shape: (0, 2)
┌───────────┬───────────┐
│ col1      ┆ col2      │
│ ---       ┆ ---       │
│ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╡
└───────────┴───────────┘
```
(because the order of the struct fields differs, and thus the order of the columns in their corresponding DataFrames differs)

Sorry if I'm making a mess of this.  But this presents a stumbling block to my further testing of structs.

**Comment by ritchie46** [comment]
The implementation of struct equality was completely flawed. It did not make any sense. I have fixed it now.

For structs the order of the fields is important. If they are not equal, we will return `false`. This does not really fit onto the python dictionaries, but its the closest datatype in python that fits the struct.
