### ISSUE TITLE
struct: field values are not assigned correctly in constructor

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3441]
polars 0.13.37+ (compiled up to commit 2d3727e)
python 3.10.4
Linux Mint 20.3
#### Describe your bug.
When using a collection of dictionaries to create a column of structs, the constructor assigns the wrong values to fields if the keys in the dictionary are not in the same order.
#### What are the steps to reproduce the behavior?
We'll use a list of dictionaries to create a column of struct.  In the dictionaries, we will purposely not maintain the order of the keys.
```python3
import polars as pl
df = pl.DataFrame(
    {
        "col1": [{"a": 1, "b": 2}, {"b": 4, "a": 3}],
    }
)
df
```
```
shape: (2, 1)
┌───────────┐
│ col1      │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {1,2}     │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ {4,3}     │
└───────────┘
```
Taking a closer look at the values in the series:
```
>>> s = df.get_column('col1')
>>> s[0]
{'a': 1, 'b': 2}
>>> s[1]
{'a': 4, 'b': 3}
```
We see that in the second struct of the series, `a` is 4, instead of 3.  Likewise, `b` is 3, instead of 4.  It seems that the order of the dictionary keys is being used to assign values, rather than the value of the keys themselves.

**Comment by ritchie46** [comment]
Good observation. I think I will decide to error if the order of dictionaries changes. The complexity is getting too high otherwise and it will slow down other code.
