### ISSUE TITLE
Support specifying schema when read/write a Parquet file

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#3442]
#### Describe your feature request

When reading a CSV file using polars, users can specify an optional schema for some columns. It would useful if users can also specify a schema when read/write Parquet files. 

This might sounds odd but it does have some use cases. For example, I have some Parquet files generated from Spark and want to load them in to Rust. The Rust code requires u64 while Spark does not have signed integers and have outputed i64 types into Parquet files. I'd like to manually convert types of columns in Parquet files using polars. Of course, I know that I can manually cast each column and then update the original column, but I don't it's the most efficient way.

**Comment by ritchie46** [comment]
Maybe it was your question but here is the same topic answered on SO: https://stackoverflow.com/a/72337373/6717054
