### ISSUE TITLE
struct: missing field names in constructor

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3451]
polars 0.13.37+ (compiled through 3484245d)
python 3.10.4
Linux Mint 20.3
#### Describe your bug.
Somewhat like a DataFrame, a struct can be created without specifying field names.  In the case of a struct, this currently leads to field names of ''.  This then creates further trouble.

#### What are the steps to reproduce the behavior?
```python3
import polars as pl

s1 = pl.Series(values=[1, 2, 3])
s2 = pl.Series(values=["a", "b", "c"])
s = pl.struct(
    exprs=[s1, s2],
    eager=True,
)
print(s)
```
```
shape: (3,)
Series: '' [struct[2]]
[
        {1,"a"}
        {2,"b"}
        {3,"c"}
]
```
This looks normal, until one begins working with this series.
```
>>> s.struct.fields
['', '']

>>> s[0]
{'': 'a'}

>>> s.struct.field('')
shape: (3,)
Series: '' [i64]
[
        1
        2
        3
]
```
This even allows us to create a DataFrame with multiple columns named ''.
```
>>> s.struct.to_frame()
shape: (3, 2)
┌─────┬─────┐
│     ┆     │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ b   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ c   │
└─────┴─────┘

>>> s.struct.to_frame().columns
['', '']
```
#### Suggestion
Currently, the DataFrame constructor provides default names for columns if no column names are supplied.
```python3
pl.DataFrame([s1, s2])
```
```
shape: (3, 2)
┌──────────┬──────────┐
│ column_0 ┆ column_1 │
│ ---      ┆ ---      │
│ i64      ┆ str      │
╞══════════╪══════════╡
│ 1        ┆ a        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2        ┆ b        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3        ┆ c        │
└──────────┴──────────┘
```
For consistency, it seems reasonable to supply default field names for structs.  Perhaps `field_0`, `field_1`, ...

**Comment by ritchie46** [comment]
We should throw an error here. The same as we do with `DataFrames` a struct my not have duplicate fields/column names.
