### ISSUE TITLE
struct: lists and series - compatible structs

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3452]
polars 0.13.37+ (compiled through 3484245)
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
The Polars API currently allows structs of incompatible types to be included in the same list or same Series.

Here's my guiding principle for "compatibility":
> A collection of structs is compatible for inclusion in the same list or same Series **iff** their corresponding (one-row) DataFrames are vstack-able.

#### What are the steps to reproduce the behavior?
Let's start with some data that motivates why this is important.  In the two lists of dictionaries below, note that I'm purposely changing the order of keys.  This will lead to a change in order of the fields in the structs in a later step.
```python3
import polars as pl

housing1_data = [
    {
        "city": "Chicago",
        "address": "100 Main St",
        "price": 250000,
        "nbr_bedrooms": 3,
    },
    {
        "city": "New York",
        "address": "100 First Ave",
        "price": 450000,
        "nbr_bedrooms": 2,
    },
]

housing2_data = [
    {
        "address": "303 Mockingbird Lane",
        "city": "Los Angeles",
        "nbr_bedrooms": 2,
        "price": 450000,
    },
    {
        "address": "404 Moldave Dr",
        "city": "Miami Beach",
        "nbr_bedrooms": 1,
        "price": 250000,
    },
]
```
#### Appending a Series when structs are incompatible
Now let's create two Series of structs that are incompatible for inclusion into a single Series.
```python3
housing1, housing2 = pl.Series(housing1_data), pl.Series(housing2_data)
housing1.append(housing2)
print(housing1)
```
```
Series: '' [struct[4]]
[
        {"Chicago","100 Main St",250000,3}
        {"New York","100 First Ave",450000,2}
        {"303 Mockingbird Lane","Los Angeles",2,450000}
        {"404 Moldave Dr","Miami Beach",1,250000}
]
```
The problem is a bit clearer if we `unnest` the series.
```
>>> print(housing1.to_frame().unnest(""))
shape: (4, 4)
┌──────────────────────┬───────────────┬────────┬──────────────┐
│ city                 ┆ address       ┆ price  ┆ nbr_bedrooms │
│ ---                  ┆ ---           ┆ ---    ┆ ---          │
│ str                  ┆ str           ┆ i64    ┆ i64          │
╞══════════════════════╪═══════════════╪════════╪══════════════╡
│ Chicago              ┆ 100 Main St   ┆ 250000 ┆ 3            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ New York             ┆ 100 First Ave ┆ 450000 ┆ 2            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 303 Mockingbird Lane ┆ Los Angeles   ┆ 2      ┆ 450000       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 404 Moldave Dr       ┆ Miami Beach   ┆ 1      ┆ 250000       │
└──────────────────────┴───────────────┴────────┴──────────────┘
```

I would argue that the above result is incorrect.  Instead, an exception should be raised.

If we were to create equivalent DataFrames from the structs (by using `unnest`) and then attempt to `vstack` them, this raises an exception.
```python3
housing1, housing2 = pl.Series(housing1_data), pl.Series(housing2_data)
housing1.to_frame().unnest("").vstack(housing2.to_frame().unnest(""))
```
```
>>> housing1.to_frame().unnest("").vstack(housing2.to_frame().unnest(""))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/projects/polars/py-polars/polars/internals/frame.py", line 3745, in vstack
    return self._from_pydf(self._df.vstack(df._df))
exceptions.SchemaError: cannot vstack: because column names in the two DataFrames do not match for left.name='city' != right.name='address'
```
The columns of the two DataFrames do not align, so an exception is raised.

I would argue that an exception is the correct result when attempting to include structs of incompatible types in the same Series (by whatever means).  The Polars API readily allows conversions between structs and columns in a DataFrame (e.g., `unnest`, `to_struct`).  As such, it would seem consistent to enforce the same rules for adding structs to a Series as for concatenating DataFrames.

#### Concatenating two lists when structs are incompatible
The current API also allows concatenating lists when structs are incompatible.  (Note: the use of an additional `[]` around the list of housing data creates a Series of List.)
```python3
housing1, housing2 = pl.Series([housing1_data]), pl.Series([housing2_data])
print(housing1)
print(housing2)
print(housing1.arr.concat(housing2))
```
```
>>> print(housing1)
shape: (1,)
Series: '' [list]
[
        [{"Chicago","100 Main St",250000,3}, {"New York","100 First Ave",450000,2}]
]

>>> print(housing2)
shape: (1,)
Series: '' [list]
[
        [{"303 Mockingbird Lane","Los Angeles",2,450000}, {"404 Moldave Dr","Miami Beach",1,250000}]
]

>>> print(housing1.arr.concat(housing2))
shape: (1,)
Series: '' [list]
[
        [{"Chicago","100 Main St",250000,3}, {"New York","100 First Ave",450000,2}, ... {"404 Moldave Dr","Miami Beach",1,250000}]
]
```
I would argue that the `arr.concat` step should raise an exception in this case because the two lists contain structs that are incompatible for including in a single list.

#### Discussion
My reasoning for wanting to enforce "compatibility" of structs for Series and lists is to help users catch errors or mismatched data, particularly in highly recursive data sources that Polars may be importing.  Without it, there may be some very long debugging sessions, recursing through imported data structures, trying to find what went wrong.

Another reason is the view of many Python programmers that dictionaries are not "ordered".  For example, if a JSON document does not maintain consistent ordering of key-value pairs in each dictionary, this could lead to undetected problems when imported into Polars.  Raising an error might alert a user to this issue.

**Comment by ritchie46** [comment]
Right. I agree. We should check the field names. I had to look twicw before I understood the bug. 🙈
