### ISSUE TITLE
~Polars failing to auto-infer common datetime format "%m/%d/%Y %H:%M:%S"~ Parquet schema

### ISSUE THREAD

**Issue by birane-voltaiq** [pola-rs/polars#3453]
#### What language are you using?

Python

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?

No

#### What version of polars are you using?

0.13.25

#### What operating system are you using polars on?

Ubuntu 18.04

#### What language version are you using
python 3.7.5. 

#### Describe your bug.

I have a parquet file that I reading in using polars.read_parquet, one of the columns available is a datetime column called "date_time" in the format "%m/%d/%Y %H:%M:%S" which is a common date time format, however, it appears polars cannot autoinfer this format. Since the auto inference fails, the following line of code also fails:

df = df.with_column(
                polars.col("date_time")
                .diff()
                .dt.milliseconds()
                .alias("time_delta")
            )

I have to explicitly convert the column to a datetime column before running the code above in order to calculate time_delta like so:
df = df.with_column(polars.col("date_time").str.strptime(polars.Datetime, "%m/%d/%Y %H:%M:%S"))

#### What are the steps to reproduce the behavior?

df = polars.DataFrame(["08/17/2021 03:48:38", "08/17/2021 03:48:39", "08/17/2021 03:48:40"])
df["column_0"].diff().dt.milliseconds()

#### What is the actual behavior?

PanicException: data types don't match: InvalidOperation("subtraction operation not supported for shape: (3,)\nChunkedArray: 'column_0' [str]\n[\n\t\"08/17/2021 03:...\n\t\"08/17/2021 03:...\n\t\"08/17/2021 03:...\n] and shape: (3,)\nSeries: 'column_0' [str]\n[\n\tnull\n\t\"08/17/2021 03:...\n\t\"08/17/2021 03:...\n]")

#### What is the expected behavior?

Return a series that lists the difference between adjacent datetime values in milliseconds. It would be useful if polars could identify the common datetime formats and read the column in as Datetime datatype instead of string.

**Comment by ritchie46** [comment]
A parquet file has a schema. That means we must not try to infer datetimes on any columns. If the schema says the column is a string column, it is a string column.

You as a user of that file with a schema may have other needs and try to cast that column to a date/time column via `strptime`.
