### ISSUE TITLE
[Question] Any way to control the compression level when writing Parquet files?

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#3473]
https://stackoverflow.com/questions/72340767/control-the-compression-level-when-write-parquet-files-using-polars-in-rust

**Comment by cnpryer** [comment]
It makes things easier on the maintainers to try to keep issue content contained and accessible. It may be confusing to others to have two separate issues here. I posted your link on the original issue.

**Comment by ritchie46** [comment]
This is not possible in `rust polars`. You could make a feature request for this upstream in `arrow2`.

If you want that functionality in `python polars` you can leverage `pyarrow` for this purpose. `polars` has zero copy interop with `pyarrow`.

**Comment by jorgecarleitao** [comment]
We have this already in latest parquet2 main, it will soon be available in arrow2 - needs a backward incompatible release

**Comment by coastalwhite** [comment]
It is supported now.
