### ISSUE TITLE
Merge sorted array implementation

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#3474]
For my work (and probably other people), it is extremely helpful to have an operator that implements the merge step of merge-sort. Basically what you already know: https://github.com/pola-rs/polars/issues/22

i.e. you have two sorted tables on a column, and you want to make a bigger table sorted on the same column. I wonder if it's too much trouble to ask for. 

Is there any plan to implement sort merge join?

**Comment by ritchie46** [comment]
I am considering this. I first want to implement a sorted groupby and then look at this.
