### ISSUE TITLE
`df.describe` with any categorical columns raises a PanicException

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#3487]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes (0.13.38)

#### What version of polars are you using?

0.13.38
#### What operating system are you using polars on?

MacOS

#### What language version are you using
3.10.1
#### Describe your bug.

Calling  `describe` on a df with any categorical variables gives rise to a PanicException
#### What are the steps to reproduce the behavior?

This works (no categorical column) with all null results
```python
import polars as pl
df = pl.DataFrame({'cats':['a','b']})
df.describe()
```
This doesn't
```python
df = df.with_column(pl.col('cats').cast(pl.Categorical))
df.describe()
```
gives
```
thread '<unnamed>' panicked at 'should not fail: ComputeError("Appending categorical data can only be done if they are made under the same global string cache. Consider using a global string cache.")', /github/workspace/polars/polars-core/src/frame/mod.rs:882:36
```
#### What is the expected behavior?

Give null output like with string column

**Comment by cnpryer** [comment]
Maybe this is the important part of that error message

> if they are made under the same global string cache

**Comment by cnpryer** [comment]
If I can get to it I'll check if it's just that you need to use the same cache for the categorical data.

If you want to try, wrap it with

```py
with pl.StringCache():
    # ...
```

**Comment by braaannigan** [comment]
@cnpryer 
Thanks, I'll give that a try, but it might be a couple of days

**Comment by ritchie46** [comment]
I think we can lift the string cache restriction for this operation though. We should be certain that all categoricals come from the same source. I shall take a look.
