### ISSUE TITLE
sorted `min/max` fast paths

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#3492]

**Comment by matteosantama** [comment]
What would the fastpath be? I can envision

- calling `df.sort()` sets a `is_sorted = True` flag on the instance
- calling `df.min()` or `df.max()` checks the flag
- any operation that "unsorts" the DataFrame resets the flag to `is_sorted = False`

Is this what your were thinking? 

But note that in practice we might want to use 

```python
is_sorted: Literal["increasing"] | Literal["decreasing"] | None
```
instead.

**Comment by ritchie46** [comment]
We actually have this information on the rust side. Thanks for the reminded :)
