### ISSUE TITLE
time_to_time64ns does not support hour/minute data

### ISSUE THREAD

**Issue by fsimkovic** [pola-rs/polars#3497]
#### What language are you using?

Rust, Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

94b40f204836084e001d4754bbd8b81c3ac68719

#### Describe your bug.

Lines https://github.com/pola-rs/polars/blob/master/polars/polars-time/src/chunkedarray/time.rs#L8 and https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/temporal/time.rs#L7 skip the `time.minute()` and `time.hour()` components of `NaiveTime`.

#### What is the actual behavior?

Converting a `time` via `time_to_time64ns` and then back via `time64ns_to_time` drops the hour/minute components.

#### What is the expected behavior?

Converting a `time` via `time_to_time64ns` and then back via `time64ns_to_time` yields gives the original `time`.

What do you think polars should have done?

```rust
const SECONDS_IN_MINUTE: i64 = 60;
const SECONDS_IN_HOUR: i64 = 3_600;

pub(crate) fn time_to_time64ns(time: &NaiveTime) -> i64 {
    (time.hour() as i64 * SECONDS_IN_HOUR
        + time.minute() as i64 * SECONDS_IN_MINUTE
        + time.second() as i64)
        * NANOSECONDS
        + time.nanosecond() as i64
}
```

**Comment by ritchie46** [comment]
Thanks for the issue report. Would you be willing to make a PR?

**Comment by fsimkovic** [comment]
#3496 has the fix included. If preferred, I can raise it as a separate RP.
