### ISSUE TITLE
Way to *extract* all matches similar to `replace_all()`?

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#3498]
#### `.str.extract_all()`?

Is there any way to extract *all* occurences of a regex match from a string? 
Example:
```python
df = pl.DataFrame({"foo": ["123 bla 45 asd", "xyz 678 910t"]})
df.select(pl.col("foo").str.extract(r"(\d+)", 0))
```
only returns

```python
┌─────┐
│ foo │
│ --- │
│ str │
╞═════╡
│ 123 │
├╌╌╌╌╌┤
│ 678 │
└─────┘
```

but I'm looking for a way to extract

```python
┌────────────┐
│            │
│ ---        │
│ list [i64] │
╞════════════╡
│ [123, 45]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [678, 910] │
└────────────┘
```

maybe this is similar in nature to the `replace()` and `replace_all()` methods?

**Comment by moritzwilksch** [comment]
Addendum: My original use case was *counting* the number of matches. There is no specific method for this but extracting all matches like described above and calling `.arr.lengths()` would perfectly do this job.

**Comment by cbilot** [comment]
@ritchie46 have you added the `extract_all` and `count_match` to the API Ref?  I wanted to link to it for a [SO question](https://stackoverflow.com/questions/72468433/use-str-extract-to-extract-multiple-matches-in-polars) today, but could not find it.

**Comment by ritchie46** [comment]
I did. Looking at the PR, I forgot the docs links.

**Comment by cbilot** [comment]
👍🏼 Thanks, I’ve updated the SO answer with the link.
