### ISSUE TITLE
Polars does not accept arrow dictionary arrays with unsigned integer keys

### ISSUE THREAD

**Issue by JakobGM** [pola-rs/polars#3500]
#### What language are you using?

**Python**.

#### Have you tried latest version of polars?

Yes, version `0.13.38`.

#### What version of polars are you using?

Version `0.13.38`.

#### What operating system are you using polars on?

A Ubuntu docker container running on a MacOS ARM host machine.

#### What language version are you using

Python 3.9

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

The following piece of code will run fine until the last line is executed.

```py
import polars as pl
import pyarrow as pa
import pandas as pd

# Create an enum / categorical / dictionary typed pyarrow array
# Most simply done by creating a pandas categorical series first
categorical_df = pd.Series(["a", "a", "b"], dtype="category")
pyarrow_array = pa.Array.from_pandas(categorical_df)

# The in-memory representation of each category can either be a signed or unsigned 8-bit integer
# Pandas uses Int8...
int_dict_type = pa.dictionary(index_type=pa.int8(), value_type=pa.utf8())
# ... while DuckDB uses UInt8
uint_dict_type = pa.dictionary(index_type=pa.uint8(), value_type=pa.utf8())

# The integer encoded categories are easily converted to a polars Series
# This cast is actually a no-op, but is done here to show consistency
pl.from_arrow(pyarrow_array.cast(int_dict_type))  # OK
# But the unsigned integer encoded categories fail on conversion
pl.from_arrow(pyarrow_array.cast(uint_dict_type))  # Fail!
```

#### What is the actual behavior?

The following exception is raised:

```
ValueError: Cannot create polars series dictionary type of key:  UInt8 value: Utf8
```

The exception is raised [here](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/construction.py#L99).

#### What is the expected behavior?

Not to raise, but rather let categories be encoded as unsigned integers. This would allow polars to accept data coming directly from DuckDB where the data is encoded in enum-typed columns.

**Comment by ritchie46** [comment]
Thanks for the issue report. Yea we should coerce to our index type indeed.
