### ISSUE TITLE
[Question] Why does LazyFrame::scan_parquet takes a String for the `path` parameter?

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#3501]
I believe this question belongs here as it is more regarding design of the library. 

I'm curious why does the function `LazyFrame::scan_parquet` takes a `String` for the `path` parameter? Isn't it more flexible to make `scan_parquet` take a `AsRef<Path>` for the `path` parameter? Also,  isn't `&str` recommended over `String` for passing parameters?

**Comment by ritchie46** [comment]
Because we need to clone it anyway. We need an owned string, so we ask for an owned string.

**Comment by ritchie46** [comment]
I agree that a `Path` is better and that a reference is a quality of life improvement. But I don't see as a prio for me.

Would be willing to accept a PR.

**Comment by isaacthefallenapple** [comment]
This would be backwards incompatible. If you have something like
```rust
LazyFrame::scan_parquet("myfile_1.parquet".into(), Default::default())
```
that `.into()` call on the path argument won't work anymore when the expected type is `impl AsRef<Path>` instead of `String`. 

If that's not a concern, I'd be happy to implement it.

**Comment by ritchie46** [comment]
Yep, that's fine. 👍 We could also make a trait that does the conversion.

**Comment by isaacthefallenapple** [comment]
What conversion do you mean?
