### ISSUE TITLE
Is there a writeable flag like in Numpy?

### ISSUE THREAD

**Issue by rachtsingh** [pola-rs/polars#3506]
Numpy has a flag system for unintended mutations:

```python
arr = np.array([0, 1, 2])
arr.setflags(write=False)
arr[1] = 7

ValueError: assignment destination is read-only
```

Pandas has a similar flag system, but only has one flag (`allows_duplicate_labels`) which is used to detect duplicate records in the index. Oddly enough setting the underlying arrays in Pandas to be read-only doesn't seem to work... (I must misunderstand where a copy is happening somehow):

```python
df = pd.DataFrame({'foo': [0, 0, 1], 'bar': [2, 3, 5]})
df.bar.array._ndarray.setflags(write=False)
df.iloc[0, 1] = 7
df.bar

0    7
1    3
2    5
Name: bar, dtype: int64
```

But I couldn't find any such flags in Polars. If I understand correctly, the underlying `PyDataFrame` object wraps (through DataFrame -> Series -> ChunkedArray) an immutable Arrow-format memory location, but I don't really understand where new allocations are happening during assignment. Would it be possible to expose a user-facing API that restricts a DataFrame or Series to be immutable?

I couldn't find any discussion of this, so this is question/feature request (apologies if I missed a discussion somewhere!).

**Comment by ritchie46** [comment]
Polars memory is already immutable in most cases because we share it. In fact the only operation that allows to mutate (only on special conditions) is `extend` and maybe `set` in the future.

However, you are very unlikely to use these, as polars has a functional API. We tend to return a new series/expression and make it pretty hard to do anything in place.

In idiomatic polars you express your intend via the expression API and you don't deal with with arrays yourself. Every expression produces a pure result and does not modify the initial state of the computation.

In the following query for instance, polars will create a new `Series` for `"b"` in `df2`, but will keep `df` intact. Column `"a"` will be shared between both DataFrames and so reduces memory pressure.

```python
df = pl.DataFrame({
    "a": pl.arange(0, 10, eager=True).shuffle(),
    "b": pl.arange(0, 10, eager=True).shuffle(),
    
})

df2 = df.with_columns([
    pl.when(pl.col("b") < pl.col("a").rolling_mean(3))
        .then(pl.col("a").sum())
        .otherwise(pl.col("b")).alias("b")
])


print(df, df2)
```

**Comment by rachtsingh** [comment]
Sorry about the slow response!

This is great, I appreciate that a lot. So essentially the following code:

```python
df = pl.DataFrame({'foo': [0, 0, 1], 'bar': ["b", "b", "a"]})
df[0, 1] = "c"
```

allocates a new Series and set the reference of the "bar" column to that new Series. Series is immutable because `__setitem__/set_at_index` returns a new Series object. That makes sense, and I have no further requests.

Overall I'm pretty happy with this (and the library, great work!), but for the sake of discussion I should point out that I think this achieves one of the goals of immutability (i.e., no silent mutation of shared references), but doesn't achieve one possible other goal: preventing user error via mutation. I can see that it's a design decision to pick where to enforce that boundary:
- Polars picks that at the memory level, i.e. a write to a Series/DataFrame returns a reference to a new instance (in the case of the DataFrame, the DataFrame reference is the same but the Series is new)
- another library (or setting in Polars) could choose that at the Series level, i.e. __setitem__ on Series raises an error but setting a new column in DataFrame (i.e. via `df["foobar"] = new_series`) is allowed
- another library (or setting in Polars) could choose that at the DataFrame level, i.e. __setitem__ on DataFrame raises an error.

For comparison, the [static-frame](https://github.com/InvestmentSystems/static-frame) library makes some of these choices explicit via Frame and FrameGO. For some context for why this is useful, it's sometimes helpful in Python to loudly complain instead of silently fail, e.g. in this contrived example:

```python
def bad_cumsum(s: pl.Series):
    s[0] = ""
bad_cumsum(df.bar)
```

but like I said, I'm happy with the design decision Polars makes in this case. I think the functional API is nice! I appreciate that the initial state isn't corrupted, it is great.
