### ISSUE TITLE
Better document features required by each API

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#3512]
Currently, features required to enable some APIs are not clearly documented. It can be confusing and frustrating for users who are not familiar with polars.

**Comment by ritchie46** [comment]
We have an attribute on every method on the specific crates. See: https://docs.rs/polars-core/0.21.1/polars_core/series/struct.Series.html#method.floor

I don't know how to get it activated on the `polars` global crate. If anybody can point that out. Currently we use this tactic: https://stackoverflow.com/a/61417700/6717054

Next to that we list all the features on the front page of the doc. See here: https://docs.rs/polars/latest/polars/#compile-times-and-opt-in-features

If you think it should be better, maybe submit a PR?

**Comment by alexander-beedie** [comment]
Closed by https://github.com/pola-rs/polars/pull/6201; required features are now integrated into the Rust/crate docs.

<img width="390" src="https://user-images.githubusercontent.com/1234956/212881340-d575f86b-5788-4136-9171-08cc2bf329d3.jpeg">
