### ISSUE TITLE
A left join with nulls in join column panicks after distinct count

### ISSUE THREAD

**Issue by JakobGM** [pola-rs/polars#3521]
#### What language are you using?

**Python**

#### What version of polars are you using?

Bug first appeared on version `0.13.38` and persisted to version `0.13.39`, the latest version as of this writing.

#### What operating system are you using polars on?

MacOS ARM and Ubuntu ARM, it fails on both. Have not tested on x86, but I believe it will appear there as well.

#### What language version are you using

Python 3.9. 

#### Describe your bug.

When the following conditions are met, a panic occurs:

1. A left data frame with a Null value in its join column.
2. A left join towards another data frame.
3. A group-by aggregation where a column on the right data frame is distinctly counted after having dropped null values.

This is much simpler to explain with a minimal code example, see below.

#### What are the steps to reproduce the behavior?

```py
import polars as pl

# Create a left relation where the join column contains a null value
left = pl.DataFrame().with_columns(
    [
        pl.lit(1).alias("groupby_column"),
        pl.lit(None).cast(pl.Int32).alias("join_column"),
    ]
)

# Create a right relation where there is a column to count distinct on
right = pl.DataFrame().with_columns(
    [
        pl.lit(1).alias("join_column"),
        pl.lit(1).alias("n_unique_column"),
    ]
)

# Calculate n_unique after dropping nulls
# This will panic on polars version 0.13.38 and 0.13.39
joined = (
    left.join(right, on="join_column", how="left")
    .groupby("groupby_column")
    .agg(pl.col("n_unique_column").drop_nulls().n_unique())
)
```

#### What is the actual behavior?

The following exception is raised:

```
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `0`,
 right: `1`
```

#### What is the expected behavior?

Not raise, but rather perform the join correctly.

Thanks in advance, as always!

**Comment by ritchie46** [comment]
Thanks for the issue report. I will fix it.
