### ISSUE TITLE
`.median()` and `.quantile()` fail after `.drop_nulls()`

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#3522]
Consider the following example (applies to `.median()` as well as to `.quantile(...)`):
```python
from datetime import datetime

df = pl.DataFrame(
    {
        "foo": [
            datetime(2022, 5, 5, 12, 31, 34),
            datetime(2022, 5, 5, 12, 47, 1),
            datetime(2022, 5, 6, 8, 59, 11),
        ]
    }
)
diffs = df.select(pl.col("foo").diff().dt.seconds().drop_nulls())  # type: Int64

# shape: (2, 1)
# ┌───────┐
# │ foo   │
# │ ---   │
# │ i64   │
# ╞═══════╡
# │ 927   │
# ├╌╌╌╌╌╌╌┤
# │ 72730 │
# └───────┘

# diffs.median()  # fails: called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")
diffs.select(pl.col("foo").cast(pl.Float32).median())  # works
```

Calculating the median of the diffs fails with an error referencing non-matching mask lengths, probably because of the null value at position 0 introduced by the `.diff()` command?
Now I wonder: is this expected behavior? I would expect the median to work after I manually drop the nulls with `.drop_nulls()`. Also it's weird that a cast to Float fixes the problem.

[polars version 0.13.39 on python3.9.12]

**Comment by ritchie46** [comment]
Thanks for the report. I will fix it.
