### ISSUE TITLE
df.write_json("cache.json") silently terminates program for big data files in v0.13.39

### ISSUE THREAD

**Issue by TimJentzsch** [pola-rs/polars#3524]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

The latest version available with Poetry.

#### What version of polars are you using?

`0.13.39`

#### What operating system are you using polars on?

Windows 10

#### What language version are you using

Python 3.10.4

#### Describe your bug.

When writing a large DataFrame to a JSON file, the program silently terminates.
No error of any kind is emitted.

The data has a size of over 700 MB. The program terminated after writing about 400 MB to the JSON file.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df: DataFrame = # Large data frame

df.write_json("cache.json")
```

#### What is the expected behavior?

The whole DataFrame is written to the JSON file.

If not possible, an error message should be generated, explaining what went wrong (e.g. out of memory error).

**Comment by ritchie46** [comment]
Can you confirm it is an OOM? Is it the same df that lead to #3523?

**Comment by TimJentzsch** [comment]
I was unable to definitively confirm the cause yet. It's the same `df` as #3523, but it must be a different error as this one didn't panic and wrote about 400 MB, while the other one only wrote the CSV header.

**Comment by ritchie46** [comment]
I think its likely that those two are related. Can you share your file, or pherhaps your schema?

Related to the OOM, we cannot do anything about that. rust aborts on OOM.

**Comment by ritchie46** [comment]
You have not uploaded the csv? Have you got any code that can create such a file?

**Comment by universalmind303** [comment]
@Tsai002 is this still an issue with the latest version?
