### ISSUE TITLE
Add argument to `pl.concat_str()` to treat `Null` as empty string

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#3534]
When I concatenate columns with `Null` values in them using `concat_str`, then the entire row is returned as `Null`:

```py3
df = pl.DataFrame([["a", "b", "c"], [None, "d", "e"]])

shape: (3, 2)
┌──────────┬──────────┐
│ column_0 ┆ column_1 │
│ ---      ┆ ---      │
│ str      ┆ str      │
╞══════════╪══════════╡
│ a        ┆ null     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ b        ┆ d        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ c        ┆ e        │
└──────────┴──────────┘

df.select(pl.concat_str(col("*")))

shape: (3, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ str      │
╞══════════╡
│ null     │
├╌╌╌╌╌╌╌╌╌╌┤
│ bd       │
├╌╌╌╌╌╌╌╌╌╌┤
│ ce       │
└──────────┘
```

It would be nice to be able to keep those strings (or actually keep them by default to avoid accidental data loss) without first having to replace the `Null` values, and return `Null` only when *all* the columns in a row are `Null`.

**Comment by JakobGM** [comment]
This is rather simple to do by using `polars.Expr.fill_null()` ☺️ 

```py
df = pl.DataFrame([["a", "b", "c"], [None, "d", "e"]])
df.select(pl.concat_str(pl.col("*").fill_null("")))
```

It is better that the user has to explicitly tell polars how to handle Null values rather than implicitly casting them to empty strings.

**Comment by ritchie46** [comment]
I agree with @JakobGM here. The expression API is flexible enough to facilitate this:

```python
df = pl.DataFrame([["a", "b", "c", None], [None, "d", "e", None]])

all_null = pl.fold(0, lambda a, b: a + b, pl.all().is_null()) == df.width
df.select([
    pl.when(all_null)
      .then(None)
      .otherwise(
          pl.concat_str(pl.all().fill_null(""))
      )
])
```

**Comment by DrMaphuse** [comment]
@ritchie46 
Thanks, that is perfect. 

The original motivation for opening this issue was that I feel that implicitly omitting values based on the values of other columns is not ideal. For most purposes, `None` is reserved for data points that we know nothing about, whereas we try to retain the information that we have for all others. To put it differently, The "a" in `column_0` is not at fault for the shortcomings of `column_1`, so it would be "unfair" to just omit it. The two should be allowed to become part of the concatenation independently of each other.

From a practical standpoint, this is probably close to what the user wants in 90% of use cases, which in itself can be an argument for building it into the function - even just as a convenience wrapper.

On a side note, `df.select(pl.format('{}{}', 'column_0', 'column_1'))` similarly returns `None`, whereas vanilla Python (`'{}{}'.format(None, 'a')` or `f"{None}{'a'}"`) actually converts `None` into a string (`'Nonea'`), which is yet another variant of handling the same scenario. This might be another argument for adding convenience wrappers that reflect the different ways of interpreting `Null`s (all of which are considered "standard" in one way or another).

**Comment by ghuls** [comment]
To only change None to "" for String columns (and not for e.g integer columns), you can use:
```python
In [23]: df = pl.DataFrame([["a", "b", "c"], [8, 6, None], [None, "d", "e"]])

In [24]: df
Out[24]: 
shape: (3, 3)
┌──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ i64      ┆ str      │
╞══════════╪══════════╪══════════╡
│ a        ┆ 8        ┆ null     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ b        ┆ 6        ┆ d        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ c        ┆ null     ┆ e        │
└──────────┴──────────┴──────────┘

In [25]: df.with_columns(pl.col(pl.Utf8).fill_null(""))
Out[25]: 
shape: (3, 3)
┌──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ i64      ┆ str      │
╞══════════╪══════════╪══════════╡
│ a        ┆ 8        ┆          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ b        ┆ 6        ┆ d        │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ c        ┆ null     ┆ e        │
└──────────┴──────────┴──────────┘

In [26]: df.with_columns(pl.col(pl.Utf8).fill_null("")).with_column(pl.concat_str(pl.col(pl.Utf8)).alias("concat_str"))
Out[26]: 
shape: (3, 4)
┌──────────┬──────────┬──────────┬────────────┐
│ column_0 ┆ column_1 ┆ column_2 ┆ concat_str │
│ ---      ┆ ---      ┆ ---      ┆ ---        │
│ str      ┆ i64      ┆ str      ┆ str        │
╞══════════╪══════════╪══════════╪════════════╡
│ a        ┆ 8        ┆          ┆ a          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b        ┆ 6        ┆ d        ┆ bd         │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ c        ┆ null     ┆ e        ┆ ce         │
└──────────┴──────────┴──────────┴────────────┘
```

**Comment by ion-elgreco** [comment]
@reswqa I saw your comment on join for Array dtype, just wanted to point out perhaps good to make concat_str same as str.concat to allow ignore_nulls

**Comment by stinodego** [comment]
`concat_str` now has the `ignore_nulls` parameter.
