### ISSUE TITLE
Simple group_by op can sum to "null" instead of zero

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#3535]
#### What language/versions are you using?

Python 3.9, Polars 0.13.39, macOS (M1)

#### Describe your bug.

Some simple sums in a `group_by` op are returning `null` instead of `0`. The issue was spotted performing delta operations between large frames, with unions and various other ops, but I've managed to minimize it to a single `group_by` on a handful of rows.

(Originally found the bug when upgrading from 0.13.31 to 0.13.39; it seems to be quite dependent on the specific underlying data, so we didn't observe it before - however, the values chosen below appear to successfully manifest the issue back to at _least_ 0.13.31, and quite possibly further):

#### Example

```python
import polars as pl

# setup test frame
df = pl.DataFrame( 
    data = [
        # note: the 'bb'-keyed values should clearly sum to 0 
        ('aa',  10, None),
        ('bb', -10,  0.5),
        ('bb',  10, -0.5),
        ('cc', -99, 10.5),
        ('cc',None,  0.0),
    ], 
    columns = [
        # note: tried different numeric types (int 16/32/64, float 32/64)
        # but the issue remained consistent across all of them
        ('key' ,pl.Utf8),
        ('val1',pl.Int16),
        ('val2',pl.Float32),
    ],
)
# group by the key, aggregating the two numeric cols
df.groupby( 
    pl.col('key')
).agg( 
    [pl.col('val1').sum(),
     pl.col('val2').sum()] 
)
# ┌─────┬──────┬──────┐
# │ key ┆ val1 ┆ val2 │
# │ --- ┆ ---  ┆ ---  │
# │ str ┆ i64  ┆ f64  │
# ╞═════╪══════╪══════╡
# │ aa  ┆ 10   ┆ null │
# ├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
# │ bb  ┆ null ┆ null │   <<< val1 and val2 sums should both be 0, not null
# ├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
# │ cc  ┆ -99  ┆ 10.5 │
# └─────┴──────┴──────┘
```

#### Additional note

An unexpected -but clearly related- observation is that if you replace the `None` values in the input `aa` and `cc` rows of the test frame with numeric values instead, the `bb` column values then sum correctly to `0` and `0.0` - even though no `bb` row values changed.

#### What is the expected behavior?

The column values with group-key `bb` should sum to `0`, not `null`.
(The respective sums are just `-10 + 10` and `0.5 + (-0.5)`).

**Comment by ritchie46** [comment]
Oof, I found the culprit. Was a dumb check from me. I initialized the aggregate with zero and if it was unchanged at the end of aggregation, I assumed all was null. Will fix and patch this immediately. Thanks for the report.

**Comment by alexander-beedie** [comment]
I have done the python equivalent (conflating 0/None as False in an "if" clause) more than once! As always, thanks for the fantastic speed of support - it's top-tier  :)
