### ISSUE TITLE
Mean/Sum aggregation not working on durations

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#3544]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

polars-0.13.40

#### What operating system are you using polars on?

macOS Big Sur, 11.6.5

#### What language version are you using
python 3.9

#### Describe your bug.

When doing a mean or sum aggregation over a duration column inside a groupby, the results of the aggregation are always `null`.

#### What are the steps to reproduce the behavior?

```
from datetime import datetime
import polars as pl
df = pl.DataFrame(
    {
        'group': ['A', 'B', 'A', 'B'],
        'start': [datetime(2022, 1, 1), datetime(2022, 1, 2), datetime(2022, 1, 3), datetime(2022, 1, 4)],
        'end': [datetime(2022, 1, 2), datetime(2022, 1, 4), datetime(2022, 1, 6), datetime(2022, 1, 6)],
    }
)
df = df.with_column(
    (pl.col('end') - pl.col('start')).alias('duration')
)
df.groupby('group').agg(pl.col('duration').mean())
```

#### What is the actual behavior?

```
group	duration
str	duration[μs]
"B"	null
"A"	null
```

#### What is the expected behavior?

```
group	duration
str	duration[μs]
"B"	2 days
"A"	2 days
```

**Comment by thobai** [comment]
A potential workaround for now is to cast the duration to `Int64`. That gives microseconds. So dividing by 1000000 gives us seconds and
`df.groupby('group').agg(pl.col('duration').cast(pl.Int64).mean()/1000000/60/60/24)`
outputs
```
group	duration
str	f64
"A"	2.0
"B"	2.0
```
with the duration in days

**Comment by namiyousef** [comment]
The same issue exists with datetime, are there any plans to extend the fix to datetime columns?
