### ISSUE TITLE
`make build-no-venv` does not work out of the box from pip sdist tarballe

### ISSUE THREAD

**Issue by gyscos** [pola-rs/polars#3575]
#### What language are you using?

Python.

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

Tried with 0.13.40 and 0.13.41 from pip.

#### What operating system are you using polars on?

ArchLinux

#### What language version are you using

python 3.10.4

#### Description of the issue

When downloading and extracting a source distribution from pip (for example https://files.pythonhosted.org/packages/5d/77/46b94306683cec3a94b1323b7324cf6795fc6e131d7d8d7db894a1c7ec50/polars-0.13.41.tar.gz), running `make build-no-venv` inside fails with the following error:

```
% make build-no-venv
maturin build -o wheels
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Attempting to include the sdist output tarball wheels/polars-0.13.41.tar.gz into itself! Check 'cargo package --list' output.
make: *** [Makefile:44: build-no-venv] Error 1
```

Note that running the same command from the `py-polars` subfolder of the git directory _does work_. Only when running from an extracted source distribution does it fail, _even though running `diff -r` shows no difference between the extracted folder and the git subfolder_. Weird.

#### Analysis

This is because:
* When building `wheels/polars-${version}.tar.gz`, `maturin` includes all files in the `wheels` directory. Why is it not skipping the wheels file?
* `maturin` tries to include everything listed by `cargo package --list --allow-dirty`.
* `cargo` in turn has its own rules for what to include/exclude, which is seeded by the `.gitignore` _if in a git directory_.
  * That `.gitignore` file does include `wheels`, which is why it all works fine from the git subdirectory.
* The source distribution archive does not include a `.git` subfolder. As a result, `cargo` will not follow the `.gitignore`, will include the `wheels/*` files, and `maturin` will fail.

#### Proposed solutions

* Add `wheels/` explicitly in the `exclude` field from `Cargo.toml` to not rely on its `.gitignore` parsing.
* Do not override the maturin output folder (right now `make build-no-venv` triggers `maturin build -o wheels`). Running `maturin build` works fine, since it outputs the wheels in `target/wheels`, which is already skipped by `cargo`, even without a git repository.

#### What are the steps to reproduce the behavior?

```
$ curl -L https://files.pythonhosted.org/packages/5d/77/46b94306683cec3a94b1323b7324cf6795fc6e131d7d8d7db894a1c7ec50/polars-0.13.41.tar.gz | tar xzf -
$ cd polars-0.13.41
$ make build-no-venv
```

#### What is the actual behavior?

See above, in issue description.

#### What is the expected behavior?

Properly build the wheel (like it does when run from the git subdirectory).

**Comment by ritchie46** [comment]
It is mot really meant for that. If you compile from source I'd recommend using maturin and not our makefile we use for testing.

**Comment by gyscos** [comment]
I see - did not realize the Makefile was meant for testing. Using `maturin build` directly works fine too.
Thanks!
