### ISSUE TITLE
Polars `groupby` error message

### ISSUE THREAD

**Issue by LVG77** [pola-rs/polars#3594]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.13.42

#### What operating system are you using polars on?

Linux

#### What language version are you using
python 3.8

#### Describe your bug.

Polars `groupby("x").agg(pl.col("y").sum())` produces an unexpected warning/error message.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame({
    'a': [2020, 2020, 2021, 2021, 2022, 2022],
    'b': [None, None, 10.5, None, None, None]
})
```
Now if I do a sigmple aggregation, I get the following message:

```python
# output with polars=0.13.42
df.groupby('a').agg(pl.col('b').sum())
```
![image](https://user-images.githubusercontent.com/16968156/172212219-255a87ec-5b3a-45e2-a445-71bb0c95c206.png)

Is this intended. If yes, what is its meaning?

As a reference, when running the same aggreagation with polars=0.13.39, I don't get this message.

```python
# output with polars=0.13.39
df.groupby('a').agg(pl.col('b').sum())
```
![image](https://user-images.githubusercontent.com/16968156/172212450-0be13b05-3823-405f-bb80-7e74d56db1ba.png)

Thank you for your help and thank you for developing this wonderful library. It is of enormous help for my work.

Best regards,
LG

**Comment by ritchie46** [comment]
Woops.. That's a rogue print statement. Will remove it and issue a patch release.

**Comment by LVG77** [comment]
Thank you for the quick response. That sure fix it.
