### ISSUE TITLE
Cannot create polars DataFrame from python list of dicts including an empty array value

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3608]
#### What language are you using?
**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.43

#### What operating system are you using polars on?

macOS 12.3.1

#### What language version are you using
Python 3.9.12

#### Describe your bug.

Creating a polars dataframe from python (in the "list of dicts" format) fails for empty array columns.

#### What are the steps to reproduce the behavior?
```python
>>> pl.DataFrame([{"array": [], "not_array": 1234}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/polars/internals/frame.py", line 311, in __init__
    self._df = sequence_to_pydf(data, columns=columns, orient=orient)
  File "/usr/local/lib/python3.9/site-packages/polars/internals/construction.py", line 492, in sequence_to_pydf
    pydf = PyDataFrame.read_dicts(data)
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths
```

#### What is the actual behavior?

```
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths
```

#### What is the expected behavior?

**EDIT: this is an incorrect example; see my next comment below**

Create an empty array value with column type `list[null]`. This actually succeeds if the empty array is the only column:

```python
>>> pl.DataFrame([{"array": []}])
shape: (0, 1)
┌────────────┐
│ array      │
│ ---        │
│ list[null] │
╞════════════╡
└────────────┘
```

**Comment by Vitotian** [comment]
or maybe you mean:
```
>>> pl.DataFrame({"array": [None], "not_array": [1234]})
shape: (1, 2)
┌───────┬───────────┐
│ array ┆ not_array │
│ ---   ┆ ---       │
│ f64   ┆ i64       │
╞═══════╪═══════════╡
│ null  ┆ 1234      │
└───────┴───────────┘
```

**Comment by Vitotian** [comment]
this also acceptable:
```
>>> pl.DataFrame([{"array": [None], "not_array": 1234}])
shape: (1, 2)
┌───────────┬───────────┐
│ array     ┆ not_array │
│ ---       ┆ ---       │
│ list[i32] ┆ i64       │
╞═══════════╪═══════════╡
│ [null]    ┆ 1234      │
└───────────┴───────────┘
```

**Comment by ritchie46** [comment]
We should not accept `1234` as input. 

The input in the dictionary is columnar. That means you always need to provide a sequence.

If you want an empty list, you'd need to provide `[[]]`. And instead of `1234`, you'd need to pass `[1234]`.

**Comment by physinet** [comment]
@ritchie46 my input data is in the "list of dicts" format (i.e. `pl.from_dicts`), and the syntax works in cases where the array is not empty (e.g. `pl.from_dicts([{"array": [1], "notarray": 1234}])`). 

I get the same error when using the "dict of lists" format as your comment suggests:
```python
>>> df = pl.DataFrame({"array": [[]], "notarray": [1234]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/polars/internals/frame.py", line 302, in __init__
    self._df = dict_to_pydf(data, columns=columns)
  File "/usr/local/lib/python3.9/site-packages/polars/internals/construction.py", line 402, in dict_to_pydf
    return PyDataFrame.read_dict(data)
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths
```

**Comment by slonik-az** [comment]
> The input in the dictionary is columnar. That means you always need to provide a sequence.

Is the spirit of `polars` that a scalar can be broadcast to an array of any dimension from zero onwards?

**Comment by alexander-beedie** [comment]
As per @ritchie46 & co., you need to supply a list containing the empty list like so... 

```python
pl.DataFrame([{"array": [[]], "not_array": [1234]}])
```
..._but_, there is also a small bug in this case (a list containing an empty list) for which I just made a tiny patch; the associated [pull request](https://github.com/pola-rs/polars/pull/3619) is currently running through linting/tests.
