### ISSUE TITLE
[Python] How to optimize applying hash function to polars dataframes?

### ISSUE THREAD

**Issue by jordan-carson** [pola-rs/polars#3643]
Hello - 

I have asked a question in StackOverflow on how to apply fast-function to polars dataframes. What is the fastest way to do this in Polars?

I am trying to apply a function called hash_row see below. However to do this we need to run the following command

```python
import hashlib

def hash_row(row):
    os.environ['PYTHONHASHSEED'] = "0"
    row = str(row).encode('utf-8')
    return hashlib.sha256(row).hexdigest()

def hash_concat(df):
    return (
        df
        .with_columns([
            pl.col("concatstr").apply(hash_row).alias('sha256hash')  # .exclude("factset_person_id")
        ])
    )
```

The pl.col("concatstr").apply() takes the longest time to execute, especially on a large frame. Lazy or Eager.

```python
cfactset_query = (
     cfactset_query.pipe(hash_concat)
 )
```

This takes about 20 mins to run with 25 million rows. How can we optimize this solution?

https://stackoverflow.com/questions/72563617/fast-apply-of-a-function-to-polars-dataframe

Best,
J

**Comment by ritchie46** [comment]
You know that we have functionality to hash rows right?

**Comment by jordan-carson** [comment]
Was unaware of this - what algorithm is being used under the hood and is this the same underlying functionality across `pl.Expr.hash` and `pl.hash_rows`?

Noticed we can set seed parameters. Does this use `PYTHONHASHSEED` environment variable? Setting this allows one to get reproducible results, including after closing a terminal / session etc.

**Comment by ritchie46** [comment]
No it does not, but you can use pythons seed to feed our seed.

We use ahash: https://docs.rs/ahash/latest/ahash/

**Comment by jordan-carson** [comment]
> No it does not, but you can use pythons seed to feed our seed.
> 
> We use ahash: https://docs.rs/ahash/latest/ahash/

Thanks @ritchie46
