### ISSUE TITLE
pl.concat_list does not get supertype, but casts everything to the dtype of the first column.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#3646]
#### What language are you using?

**Python**.

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

latest git.

#### What operating system are you using polars on?

CentOS 7

#### What language version are you using

python 3.9

#### Describe your bug.

`pl.concat_list` does not get supertype, but casts everything to the dtype of the first column.

#### What are the steps to reproduce the behavior?

```python
In [26]: df = pl.DataFrame([pl.Series("a", [1, 2], pl.UInt8), pl.Series("b", [10000, 20000], pl.UInt16)])

In [27]: df
Out[27]: 
shape: (2, 2)
┌─────┬───────┐
│ a   ┆ b     │
│ --- ┆ ---   │
│ u8  ┆ u16   │
╞═════╪═══════╡
│ 1   ┆ 10000 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 20000 │
└─────┴───────┘

In [28]: df.with_column(pl.concat_list(pl.col(["a", "b"])).alias("concat_list"))
Out[28]: 
shape: (2, 3)
┌─────┬───────┬─────────────┐
│ a   ┆ b     ┆ concat_list │
│ --- ┆ ---   ┆ ---         │
│ u8  ┆ u16   ┆ list[u8]    │
╞═════╪═══════╪═════════════╡
│ 1   ┆ 10000 ┆ [1, null]   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 20000 ┆ [2, null]   │
└─────┴───────┴─────────────┘

In [29]: df.with_column(pl.concat_list(pl.col(["b", "a"])).alias("concat_list"))
Out[29]: 
shape: (2, 3)
┌─────┬───────┬─────────────┐
│ a   ┆ b     ┆ concat_list │
│ --- ┆ ---   ┆ ---         │
│ u8  ┆ u16   ┆ list[u16]   │
╞═════╪═══════╪═════════════╡
│ 1   ┆ 10000 ┆ [10000, 1]  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 20000 ┆ [20000, 2]  │
└─────┴───────┴─────────────┘
```

**Comment by cbilot** [comment]
I have a somewhat philosophical question: should the correct behavior be an error?  Something along the lines of "cannot concatenate lists; data types don't match"?

If two Series were similarly situated, attempting to append the two series raises an error:
```python3
a, b = pl.Series("a", [1], pl.UInt8),pl.Series("b", [10000], pl.UInt16)
a.append(b)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/series.py", line 1299, in append
    self._s.append(other._s)
exceptions.SchemaError: cannot append Series; data types don't match
```
#### lists/structs in highly recursive data structures
My reason for asking concerns highly recursive data structures.  As I was debugging lists/structs, I formed two guidelines in my mind:
1. structs can be included in the same Series/list iff their corresponding one-row DataFrames are vstack-able.
2. lists are concatenate-able iff their corresponding Series are append-able. 

The first guideline resulted in #3452.  (and we saw issues related to this while importing JSON in #3602)

Is the second guideline above useful/desirable?  Should we be treating lists analogously to Series in this regard?  

Sorry to log this to your issue @ghuls .  But when I saw the idea of concatenating lists of different dtypes, I thought I should seek clarification.
