### ISSUE TITLE
compile error with 0.22.5

### ISSUE THREAD

**Issue by langzime** [pola-rs/polars#3648]
#### What language are you using?

Replace this text with the **Rust**.

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.22.5

#### What operating system are you using polars on?

mac os

#### What language version are you using
ex: python 3.8, node 16, etc.. 

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

<img width="1073" alt="图片" src="https://user-images.githubusercontent.com/3364128/173006455-9d12fc6a-bdbb-4b59-8d91-c8470438d423.png">

**Comment by ritchie46** [comment]
Don't include the `extract_jsonpath` feature.

**Comment by ghuls** [comment]
Removing Cargo.lock might help: `rm Cargo.lock`

**Comment by ritchie46** [comment]
Fixed in `0.22.8`
