### ISSUE TITLE
polars read mongoDB

### ISSUE THREAD

**Issue by prokie** [pola-rs/polars#3651]
Hello!

I would like to have a function, similar to read_sql, but for mongoDB. 
Is that possible? 
If not, how should I today create a data frame from a pymongo cursor?

In pandas, to create a dataframe from a cursor. I convert the cursor to a list and then use the list to create the data frame.
```
client = MongoClient('mongodb://localhost:27017/')
db = client.test_database
collection = db.test_collection
df = pd.dataframe(list(collection.find()))
```

**Comment by universalmind303** [comment]
I am working on a [polars-mongo](https://github.com/universalmind303/polars-mongo) extension. 

```py
pl.read_mongo(connection_uri='mongodb://localhost:27017/', db='test_database',  collection='test_collection')
```

but in the meantime you should be able to do something similar with polars via [from_dicts](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_dicts.html?highlight=from_dicts)

```py
client = MongoClient('mongodb://localhost:27017/')
db = client.test_database
collection = db.test_collection
df = pl.from_dicts(list(collection.find()))

**Comment by alexander-beedie** [comment]
> I am working on a [polars-mongo](https://github.com/universalmind303/polars-mongo) extension.

Very nice! Will look forward to it :)

**Comment by moritzwilksch** [comment]
Heyho, just wanna point you guys at https://pypi.org/project/pymongoarrow/ for larger datasets. Had the problem myself where materializing everything as dicts was too slow. `pymongoarrow` (which is officially maintained by MongoDB afaik) can load mongo queries into arrow tables which can be processed by polars.

**Comment by prokie** [comment]
> Heyho, just wanna point you guys at https://pypi.org/project/pymongoarrow/ for larger datasets. Had the problem myself where materializing everything as dicts was too slow. `pymongoarrow` (which is officially maintained by MongoDB afaik) can load mongo queries into arrow tables which can be processed by polars.
> 
> Looks like this:
> 
> ```python
> from pymongoarrow.api import Schema, find_arrow_all
> 
> schema = Schema({"created_at": pyarrow.string(), "text": pyarrow.string()})
> data = find_arrow_all(
>     MyMongoClient.my_db.my_collection,
>     query={},
>     projection={"_id": False, "created_at": True, "text": True},
>     schema=schema,
> )
> 
> df = pl.from_arrow(data)
> ```

Thanks for the tip!
And then another question for you. :) 

After looking at the documentation for pymongoarrow, it seems like it is not possible to read entire documents, without needing to know the schema for the documents?

**Comment by moritzwilksch** [comment]
Yes true, I think because arrow needs the type for each column you always need to specify a schema. I guess you could hack something together by assigning every column the type `pyarrow.string()` and then cast them correctly in polars but that doesn't seem wise 😅

**Comment by prokie** [comment]
@universalmind303 
How is it going with the extension?

**Comment by zundertj** [comment]
Hello all, I am closing this issue. 

https://github.com/pola-rs/polars/issues/3651#issuecomment-1156117698 is an excellent way to load data as an Arrow table by the official Mongo maintainers; `pl.from_arrow` is all you need to obtain a Polars dataframe from this efficiently. We could in theory add `pl.from_mongo` to wrap around this pattern, but I do not think there is much value add. It saves a minimal amount of typing for end-users, and does add more code paths in the Polars code base, with no computational benefit.

There is also https://github.com/pola-rs/polars/issues/3651#issuecomment-1152349984, and I suggest any requests for status updates to be posted in the linked repository.

Feel free to re-open this issue or create a new issue if you think there is something missing between these two solutions that would add value in your use case of Polars.

**Comment by CoderJoshDK** [comment]
This thread comes up pretty high when searching for mongoDB & polars so I wanted to add an update for any other wandering eyes.
<sub>sorry for messaging in a long dead issue</sub>

pymongoarrow has a [find_polars_all](https://mongo-arrow.readthedocs.io/en/latest/api/api.html#pymongoarrow.api.find_polars_all) function that is capable of inferring the schema type. It is a thin layer over the arrow logic (meaning that yea, the base find_arrow_all can now infer schema without any strange string casting)

This is all you need:
```py
from pymongoarrow.api import find_polars_all

df = find_polars_all(MyMongoClient.my_db.my_collection, {})
```
