### ISSUE TITLE
Regex in filter context

### ISSUE THREAD

**Issue by afg1** [pola-rs/polars#3654]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes - compiled from source today with full optimisation

#### What version of polars are you using?

'0.13.44'

#### What operating system are you using polars on?

Mac OS Monterey 12.04

#### What language version are you using

Python 3.10.4

#### Describe your bug.

Regexes don't work in a filter context. This may be as intended, but I kind of thought this would work like it does in select context

#### What are the steps to reproduce the behavior?

My use case is a dataframe where I have an unknown number of columns, which I can match with a regex, that I want to filter on.

An example of actual data comes from here: http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-MTAB-3726/E-MTAB-3726-tpms.tsv

I want to parse ~4500 of these, each of which has a varying number of columns that would match the regex `"^g.*$`

Here's an example that produces the error I see:

```
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "random": np.random.rand(5),
        "random2": np.random.rand(5),
    }
)

df.filter(pl.col("^r.*$").apply(lambda cols: any([x < 0.5 for x in cols]))
```
The same thing happens if the regex only matches one column as well, and if I try making the frame lazy.

#### What is the actual behavior?

Running the above gets me a `NotFoundError`

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Input In [10], in <cell line: 10>()
      1 df = pl.DataFrame(
      2     {
      3         "nrs": [1, 2, 3, None, 5],
   (...)
      7     }
      8 )
---> 10 df.filter(pl.col("^r.*$").apply(lambda x: x < 0.5))

File ~/code/polars/py-polars/polars/internals/frame.py:1994, in DataFrame.filter(self, predicate)
   1946 def filter(self: DF, predicate: "pli.Expr") -> DF:
   1947     """
   1948     Filter the rows in the DataFrame based on a predicate expression.
   1949 
   (...)
   1991 
   1992     """
   1993     return (
-> 1994         self.lazy()
   1995         .filter(predicate)
   1996         .collect(no_optimization=True, string_cache=False)
   1997     )

File ~/code/polars/py-polars/polars/internals/lazy_frame.py:600, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown)
    590     projection_pushdown = False
    592 ldf = self._ldf.optimization_toggle(
    593     type_coercion,
    594     predicate_pushdown,
   (...)
    598     slice_pushdown,
    599 )
--> 600 return self._dataframe_class._from_pydf(ldf.collect())

NotFoundError: ^r.*$
```

#### What is the expected behavior?

I thought this would work like the regex does in the select context. If this is just not the way to do this, how should I go about it?

**Comment by ritchie46** [comment]
There is a fix for that in #3666.

Note that your snippet still would not work. A regex expression expands your exression to a list of expressions.

It is not clear what a `filter` operation should do with a list of expressions. You need to reduce them to a `boolean` expression.

Here is a snippet to show you how you can do that. Note that there no need to run custom slow python code via apply.

```python
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "flt": [1.0, None, 3.0, 1.0, None],
    }
)

df.filter(pl.fold(acc=False, 
                  f=lambda acc, s: acc | s,
                  exprs=(pl.col("^nrs|flt*$") < 3)
))

```

```
shape: (1, 3)
┌─────┬───────┬─────┐
│ nrs ┆ names ┆ flt │
│ --- ┆ ---   ┆ --- │
│ i64 ┆ str   ┆ f64 │
╞═════╪═══════╪═════╡
│ 1   ┆ foo   ┆ 1.0 │
└─────┴───────┴─────┘

```
