### ISSUE TITLE
Polars dataframe print format in Jupyter has changed

### ISSUE THREAD

**Issue by LVG77** [pola-rs/polars#3658]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.13.44

#### What operating system are you using polars on?

Linux

#### What language version are you using
python 3.8

#### Describe your bug.

Polars dataframe print format in Jupyter Notebooks (and JupyterLab) has changed.
Here is an example of the printed dataframe in Polars 0.13.43
```python
import polars as pl

df = pl.DataFrame({
    'a': [2020, 2020, 2021, 2021, 2022, 2022],
    'b': [12.554, None, 10.5, None, None, 0.45],
    'c': ['cat', 'dog', 'mouse', 'cat', 'mouse', 'lion']
})
```
![image](https://user-images.githubusercontent.com/16968156/173131939-8347c6b0-ff4d-4eb2-bfbb-0b468d9d12d7.png)

... and here is an example of the same dataframe in Polars 0.13.44
![image](https://user-images.githubusercontent.com/16968156/173132018-cb7bf012-9ef2-4159-8b05-f2514baae802.png)

I am not sure whether this is a bug or an intended change. However, I much prefer the old formatting. 
And while we are on this subject, would it be possible to include a print out of the dataframe's shape (ex. num of rows and num. of columns) to the print method in Jupyter? This would be extremely helpful in cases of interactive analysis.

As usual, thank you very much for your help for for developing Polars. I highly appreciate your effors.

Best regards,
LG

**Comment by ritchie46** [comment]
I have added a html `<pre>` to be able to print meaningful whitespace characters in strings. If anybody knows any other way to do that?

I did not know it would turn our font into comic sans. :smile:

**Comment by Arengard** [comment]
dataspell & pycharm cant render the dataframe at all

**Comment by ritchie46** [comment]
> dataspell & pycharm cant render the dataframe at all

Could it before?

**Comment by Arengard** [comment]
> > dataspell & pycharm cant render the dataframe at all
> 
> Could it before?

yes

**Comment by ritchie46** [comment]
Could you try if #3667 fixed it?

**Comment by ghuls** [comment]
The output could be rendered in a monospace font. so each character has the same width.

**Comment by ankopainting** [comment]
I've also noticed that the column widths aren't as long as before :( It would be fine if I could work out how to set a new width, but even the table width does not seem to work.

`polars.Config.set_tbl_width_chars(400)` nor `polars.cfg.Config.set_tbl_width_chars(400)` seem to work

I am using vscode's jupyter plugin :)

**Comment by LVG77** [comment]
Thank you for the quick turnourd!
