### ISSUE TITLE
py polars pl.from_dicts bug

### ISSUE THREAD

**Issue by gunjunlee** [pola-rs/polars#3668]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

polars==0.13.44

#### What operating system are you using polars on?

x86_64 x86_64 x86_64 GNU/Linux

#### What language version are you using

python 3.9

#### Describe your bug.

pl.from_dicts cannot convert specific form  & size of a dict

#### What are the steps to reproduce the behavior?

```
import polars as pl

tmp = [
    {
        'b': None,
    }
    for _ in range(50) # bug not occurs if 49
]
tmp_row = {
    'b': "some string",
}
tmp.append(tmp_row)
pl.from_dicts(tmp)
```

#### What is the actual behavior?

```
exceptions.ComputeError: Could not append Utf8("str") to builder; make sure that all rows have the same schema.
```

#### What is the expected behavior?

No error

**Comment by ritchie46** [comment]
With #3669 you can define the length of the number of rows we use to infer the schema.
