### ISSUE TITLE
groupie_rolling produces 'segmentation fault' error

### ISSUE THREAD

**Issue by vstolin** [pola-rs/polars#3699]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.39 - 0.13.46

#### What operating system are you using polars on?

CentoOS 7

#### What language version are you using

python 3.9 

#### Describe your bug.

Starting version 0.13.39 and up to the latest available version 0.13.46 the code below produces ‘Segmentation fault’ error for anything over ~20k rows. The same code works on versions 0.13.38 and earlier

#### What are the steps to reproduce the behavior?

**Example**

```python

import polars as ps
import random
import string
 
from datetime import datetime, timedelta
from polars import DataFrame, Series
 
print(ps.__version__)
 
ts = ps.date_range(name='dt', low=datetime(2022, 3, 7, 0, 0, 0), high=datetime(2022, 3, 8, 0, 0, 0), interval='1s')
df = DataFrame([
    ts,
    Series(name='key', values=[random.choice(string.ascii_uppercase) for i in range (ts.len())]),
    Series(name='val', values=[random.randint(1, 1000) for i in range (ts.len())])
])
 
rolling_df: DataFrame = df.sort([
    'key',
    'dt'
]).groupby_rolling(
    index_column='dt',
    period='2m',
    closed = 'both',
    offset = '-1m'
).agg([
    ps.col('val').max().alias('max val')
])
```

#### What is the actual behavior?

script dies with 'segmentation fault' error

#### What is the expected behavior?

Produce rolling aggregation as in 0.13.38

**Comment by ritchie46** [comment]
Thanks for the report. This is something we should fix in the sense that we should throw an error.

Your query is incorrect. The index column must be sorted in ascending order. Quoting the docs here:

```
            This column must be sorted in ascending order. If not the output will not make sense.
```

You sort by keys first, that makes `dt` not ordered. You can combine it with a `by` argument to first groupby the keys like so:

```python
groupby_rolling(
    index_column='dt',
    period='2m',
    closed = 'both',
    offset = '-1m',
    by="key"   # note this line
)
```

**Comment by vstolin** [comment]
Thanks for your speedy reply! I tried to make a suggested modification, but the script still dies with ‘Killed’ message in 0.13.46 with larger dataset on 256G RAM machine.
Previously I used this feature https://github.com/pola-rs/polars/issues/2967

import polars as ps
import random
import string
 
from datetime import datetime, timedelta
from polars import DataFrame, Series
 
print(ps.__version__)
 
ts = ps.date_range(name='dt', low=datetime(2022, 3, 7, 0, 0, 0), high=datetime(2022, 3, 8, 0, 0, 0), interval='2ms')
df = DataFrame([
    ts,
    Series(name='key', values=[random.choice(string.ascii_uppercase) for i in range (ts.len())]),
    Series(name='val', values=[random.randint(1, 1000) for i in range (ts.len())])
])
 
rolling_df: DataFrame = df.sort([
    'dt'
]).groupby_rolling(
    index_column='dt',
    period='2m',
    closed='both',
    offset='-1m',
    by='key'
).agg([
    ps.col('val').max().alias('max val')
])
