### ISSUE TITLE
Better docstrings for map/apply expressions

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#3707]
#### What language are you using?

Python

The docstrings for some key expressions e.g. map/apply are minimal, we need to add some examples here

**Comment by ritchie46** [comment]
Yes, that is definitely welcome! We especially should mention what output types map to which polars type. And have examples with multiple columns and the struct dtype.

Would you want to make a PR for this?

**Comment by braaannigan** [comment]
I've started on a PR.

I'm got a question about how it works: in the docstrings there is code and example output e.g. 
```python
       >>> (
        ...     df.lazy()
        ...     .groupby("b", maintain_order=True)
        ...     .agg(
        ...         [
        ...             pl.col("a").apply(lambda x: x.sum()),
        ...         ]
        ...     )
        ...     .collect()
        ... )
        shape: (3, 2)
        ┌─────┬─────┐
        │ b   ┆ a   │
        │ --- ┆ --- │
        │ str ┆ i64 │
        ╞═════╪═════╡
        │ a   ┆ 1   │
        ├╌╌╌╌╌┼╌╌╌╌╌┤
        │ b   ┆ 2   │
        ├╌╌╌╌╌┼╌╌╌╌╌┤
        │ c   ┆ 2   │
        └─────┴─────┘
```
Do I just add that code and output within the docstring, or is it like the book where I add the code to a python script and the output is generated from that?

**Comment by ritchie46** [comment]
Nope, all in the docstring. :(

**Comment by ritchie46** [comment]
Can we close this?

**Comment by zundertj** [comment]
Closing in favor of #4079, as that is more general.
