### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by logankilpatrick** [pola-rs/polars#3710]
Hey folks! It would be really awesome to add a code of conduct for the Pola-rs community. You can create a ".github" repo at the org level and have it apply to all repos via: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

A commonly used code of conduct template: https://www.contributor-covenant.org/version/1/4/code-of-conduct/ The key thing is that there should be a reporting structure.

Thank you!

**Comment by alexander-beedie** [comment]
In summary... ;)

<img src="https://thewriteplaceforme.files.wordpress.com/2016/07/be-excellent.jpg" width="40%">

**Comment by logankilpatrick** [comment]
Thank you!! Can't wait to see the community grow 🚀
