### ISSUE TITLE
Escaped `str.contains` regex pattern (to search for string literal) raises ComputeError

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#3711]
#### What language/platform are you using?

Polars 0.13.46, Python 3.9, macOS 12.4

#### Describe your bug.

Currently the `str.contains` method expects a regular expression. If you want to search for a string _literal_, there appears to be no equivalent method/option (I think ?), so the given string needs to be escaped. 

Usually it would be sufficient to use `re.escape(search_string)`, and pass that. However, python escaping and the current version of the underlying rust regex crate don't currently see eye-to-eye when it comes to escaping spaces.

**Example**

```python
# setup a test dataframe and try various ways to
# check for the presence of the "* *" string literal
import polars as pl
import re

df = pl.DataFrame({
    'id': [1,2,3],
    'text': ['some * * text','with special * chars','etc']
})
# ┌─────┬──────────────────────┐
# │ id  ┆ text                 │
# │ --- ┆ ---                  │
# │ i64 ┆ str                  │
# ╞═════╪══════════════════════╡
# │ 1   ┆ some * * text        │
# │ 2   ┆ with special * chars │
# │ 3   ┆ etc                  │
# └─────┴──────────────────────┘

# naive: check for literal "* *" - expect an error (because of '*')
df.filter( pl.col('text').str.contains(r'* *') )   
# >> ComputeError("regex error: ...

# use re.escape (escapes special chars and spaces)
df.filter( pl.col('text').str.contains(re.escape(r'* *')) )  
# >> ComputeError("regex error: ...
```

#### Rust regex space docs

From the most recent [regex crate docs](url), `\ ` _should_ be valid: 

> If you wish to match against whitespace in this mode, you can still use `\s`, `\n`, `\t`, etc. For escaping a single space character, you can escape it directly with `\ `, use its hex character code `\x20` or temporarily disable the x flag, e.g., (?-x: ).

...though in versions earlier than 1.2.0 (for example 1.19), `\ ` is _not_ mentioned:

> If you wish to match against whitespace in this mode, you can still use `\s`, `\n`, `\t`, etc. For escaping a single space character, you can use its hex character code `\x20` or temporarily disable the x flag, e.g., (?-x: ).

The polars version of the regex crate appears to be 1.5, so the backslash space `\ ` _should_ be a valid escape, hmm...

#### Suggestion

There should be some way to allow the underlying regex engine to recognize the input as a literal (perhaps a flag that can be set on `str.contains`) - then either the regex engine invocation can be skipped entirely, or the required escaping can be applied by that engine (down in rust) to its satisfaction, as it doesn't seem to agree with the escaping being done on the python side.

```python
# something like this?
df.filter( pl.col('text').str.contains('* *',literal=True) ) 
```
Alternatively, maybe it's just a question of updating the regex lib? Though as it seems to be 1.5 already, that should be sufficient, so something else may be going on.

**Comment by ritchie46** [comment]
It seems to work here?

```python

df = pl.DataFrame({
    'id': [1,2,3],
    'text': ['some * * text','with special * chars','etc']
})

df.filter( pl.col('text').str.contains(r'\* \*') )   
```

```
shape: (1, 2)
┌─────┬───────────────┐
│ id  ┆ text          │
│ --- ┆ ---           │
│ i64 ┆ str           │
╞═════╪═══════════════╡
│ 1   ┆ some * * text │
└─────┴───────────────┘

```

**Comment by alexander-beedie** [comment]
> It seems to work here?

Yes; in that case the space is not being escaped (I originally included that example erroneously ;)

**Comment by ritchie46** [comment]
Maybe a space doesn't have to be escaped?

**Comment by ritchie46** [comment]
Seems to be the case:

```python
df["text"].str.count_match(" ")
```

```
shape: (3,)
Series: 'text' [u32]
[
	3
	3
	0
]
```

**Comment by alexander-beedie** [comment]
> Maybe a space doesn't have to be escaped?

Indeed - you don't have to, but it should be valid to do so - and because it currently fails, you can't use `re.escape` to sanitize the input when looking for arbitrary literals.

**Comment by alexander-beedie** [comment]
If you like, I could implement a literal flag to `str.contains` on the python-side that calls `re.escape` and then backs-out the escaped spaces before passing the pattern down - should work. I'm just not quite sure why the rust crate docs indicate `\ ` should work, but it's actually raising an error... Might be something going on at a lower level.

**Comment by ritchie46** [comment]
> Aha - it does: https://docs.rs/regex/1.5.6/regex/fn.escape.html Definitely the better solution - or just skip the regex engine entirely?

I think we should do both.

**Comment by ritchie46** [comment]
Closed by #3711

**Comment by ritchie46** [comment]
I think we should do the same for other string functions that work on regexes. 

- replace
- replace_all
- extract
- extrace_all

**Comment by alexander-beedie** [comment]
> I think we should do the same for other string functions that work on regexes.

Yup; already started ;)
