### ISSUE TITLE
Add `in_place` op in `pl.DataFrame.rename` ?

### ISSUE THREAD

**Issue by crazydogen** [pola-rs/polars#3714]
As shown in [API](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.rename.html), `pl.Series.rename` has a `in_place` param. But `pl.DataFrame.rename` hasn't.

Any plan about adding `in_place` in `pl.DataFrame.rename` for consistency?

**Comment by crazydogen** [comment]
Btw, `float16` is lacking. Will polars-py add all data types defined in NumPy?

**Comment by ritchie46** [comment]
Nope. The `in_place` operations are discouraged in polars and might even be removed.

```python
df = df.rename(..)
```

> Btw, float16 is lacking. Will polars-py add all data types defined in NumPy?

No, Numpy compliancy is not a goal of polars.
