### ISSUE TITLE
read_parquet fails on directories created with pyarrow.parquet.write_dataset if no partitioning is used

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#3723]
#### What language are you using?

**Python**
#### Have you tried latest version of polars?

Yes

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.13.46

#### What operating system are you using polars on?

Arch Linux

#### What language version are you using
Python 3.8.12

#### Describe your bug.
Try to run this:
```python
import polars as pl
import pyarrow.parquet as pq
import numpy as np

def test_save_load_pyarrow():
    path = "/tmp/sample.parquet"
    df = pl.DataFrame({"a": np.random.rand(100), "b": np.random.randint(0, 3, 100)})
    table = df.to_arrow()
    pq.write_to_dataset(table, root_path=path)
    df = pl.read_parquet(path)
```

This raises
```
E       exceptions.ArrowErrorException: ExternalFormat("underlying IO error: Invalid argument (os error 22)")
```

because the `path` variable points to a directory with a single `.parquet` file.

However using `pq.read_table(path)` works just fine. So does `pandas.read_parquet(path)`.

#### What are the steps to reproduce the behavior?

Described above

#### What is the actual behavior?

This raises
```
E       exceptions.ArrowErrorException: ExternalFormat("underlying IO error: Invalid argument (os error 22)")
```

#### What is the expected behavior?

The read should happen successfully.

**Comment by ritchie46** [comment]
Polars does not allow reading from directories. It does allow globbing pattens, so 

```python
pl.read_parquet("my_dir/*")
```

Should work.

**Comment by danielgafni** [comment]
But `polars` does allow reading from directories if they contain partitioned `parquet` datasets? 

Don't you think this behavior is a little inconsistent? 

Also, there is no problem when reading from a remote `S3` filesystem (using the snippet above which doesn't work for the local filesystem).

**Comment by ritchie46** [comment]
> But polars does allow reading from directories if they contain partitioned parquet datasets?

Does it? I believe this might be because `fsspec` supports that. When we cannot find the file internally in python we dispatch to `fsspec` to see if it can return a file handle.

**Comment by danielgafni** [comment]
I think this is because `pyarrow` supports it.

**Comment by danielgafni** [comment]
@ritchie46 so what do you think? maybe `polars` should support reading from directories like the other tools do? Or is it a bad design?

**Comment by ritchie46** [comment]
Sorry for the delay.  I don't really know. The fact that it succeeds with partitioned datasets is because `fsspec` handles that. 

The only support within polars itself is globbing. Which IMO gives you control to read from directories as well. In the future we want to support parittioning within polars itself, but we are not yet working on that. So until that time, I don't think this a bug. Simply something that is not supported by polars and not advertised as such.

**Comment by danielgafni** [comment]
Ok, sounds reasonable.
