### ISSUE TITLE
Found a wrong expr result after upgraded to v0.13.47

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3739]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.47

#### What operating system are you using polars on?

macOS

#### What language version are you using

Python 3.10

#### Describe your bug.

Found a wrong expr result after upgraded to v0.13.47

#### What are the steps to reproduce the behavior?

The following code calculates demeaned inner product of two columns, in two equivalent ways:

```python
import polars as pl


print("Version:", pl.__version__)


def demean_dot1(x: str, y: str) -> pl.Expr:
    x = pl.col("x")
    y = pl.col("y")
    x1 = x - x.mean()
    y1 = y - y.mean()
    return (x1 * y1).sum().alias("demean_dot1")


def demean_dot2(x: str, y: str) -> pl.Expr:
    x = pl.col("x")
    y = pl.col("y")
    x1 = x - x.mean()
    y1 = y - y.mean()
    return x1.dot(y1).alias("demean_dot2")


df = (
    pl.DataFrame(
        [
            pl.Series("key", ["a", "a", "a", "a"], dtype=pl.Categorical),
            pl.Series("x", [4, 2, 2, 4]),
            pl.Series("y", [2, 0, 2, 0]),
        ]
    )
    .groupby("key")
    .agg(
        [
            demean_dot1("x", "y"),
            demean_dot2("x", "y"),
        ]
    )
)
print(df)
```

`demean_dot2` works well in all polars versions, but `demean_dot1` would produce wrong result after upgrade polars to v0.13.47.

In polars 0.13.46, both expr ways are OK.
```
Version: 0.13.46
shape: (1, 3)
┌─────┬─────────────┬─────────────┐
│ key ┆ demean_dot1 ┆ demean_dot2 │
│ --- ┆ ---         ┆ ---         │
│ cat ┆ f64         ┆ f64         │
╞═════╪═════════════╪═════════════╡
│ a   ┆ 0.0         ┆ 0.0         │
└─────┴─────────────┴─────────────┘
```

But in polars 0.13.47, `demean_dot1` go wrong.

```
Version: 0.13.47
shape: (1, 3)
┌─────┬─────────────┬─────────────┐
│ key ┆ demean_dot1 ┆ demean_dot2 │
│ --- ┆ ---         ┆ ---         │
│ cat ┆ f64         ┆ f64         │
╞═════╪═════════════╪═════════════╡
│ a   ┆ 4.0         ┆ 0.0         │  # <- notice 4.0 here
└─────┴─────────────┴─────────────┘
```

#### What is the expected behavior?

Consistent results please. This might be a regression due to #3709.

**Comment by ritchie46** [comment]
Thanks a lot for reporting this. This was a stupid, but critical bug. I will patch a release today.
