### ISSUE TITLE
Read from HDFS recursively

### ISSUE THREAD

**Issue by kennyishihara** [pola-rs/polars#3751]
Related to issue https://github.com/pola-rs/polars/issues/2818.

I was hoping polars can read from HDFS using a glob pattern like 
```
pl.read_parquet("hdfs:///path/to/directory/*.parquet")
```
to union all of the parquet data into one table, but it seems like it only reads the first file in the directory and returns just a few rows.

One reply in the issue mentioned that Polars uses [fsspec.open](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=hdfs#fsspec.open) to read from HDFS or elsewhere. But this specific function does not read from a directory recursively using glob string. Seems like [fsspec.open_files](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=hdfs#fsspec.open_files) is something I am looking for.

**Comment by kennyishihara** [comment]
Reading as arrow table and converting it to polars works perfectly okay as suggested in the same issue. Is there much overhead converting arrow to polars (knowing that polars utilizes arrow structure)?

```python
import pyarrow.parquet as pq
from pyarrow import fs
import polars as pl

hdfs = fs.HadoopFileSystem("default")
pyarrow_table = pq.read_table("/path/to/parquet/directory/", filesystem=hdfs)

polar_df = pl.from_arrow(pyarrow_table)
```

**Comment by ritchie46** [comment]
Nope, it as fast as reading parquet from polars.
