### ISSUE TITLE
Multicolumn arithmetics gives unexpected column names, works poorly with suffix() and map_alias()

### ISSUE THREAD

**Issue by sm-Fifteen** [pola-rs/polars#3773]
#### What language are you using?

Python

#### What version of polars are you using?

Polars 0.13.49

#### What operating system are you using polars on?

Windows 10 (21H1)

#### What language version are you using

Python 3.8

#### Describe your bug.

Multicolumn expressions seem to have inconsistent behavior regarding what column name will be used for each, in  a way that's affected by binary operations and map_alias/suffix in strange ways.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

test_df = pl.DataFrame({"a":[1, 2, 3, 4], "b":[5, 6, 7, 8], "c":[9, 10, 11, 12], "foo": [13, 14, 15, 16]})

test_df.select(pl.col(["a","b","c"]).suffix("_test")) # Ok (columns a_test, b_test, c_test)
test_df.select(pl.col(["a","b","c"]) * pl.col("foo")) # Ok (columns a, b, c)
test_df.select((pl.col(["a","b","c"]) * pl.col("foo")).suffix("_test")) # DuplicateError (three columns "foo_test"
test_df.select((pl.col("foo") * pl.col(["a","b","c"])).suffix("_test")) # Reversed (a_test, b_test, c_test)

test_df.select(pl.col(["a","b"]) * pl.col(["c", "foo"])) # Reversed? (columns c and foo)
test_df.select((pl.col(["a","b"]) * pl.col(["c", "foo"])).suffix("_test")) # Reversed (columns c_test and foo_test)
```

#### What is the actual behavior?

* When multiplying `MultiCol * OneCol`, the resulting column names come from the leftmost argument (which is as I would expect given how everything else seems to works), but `.suffix` and `.map_alias` appear to recieve the name of `OneCol`.
* When multiplying `MultiCol * MultiCol`, the resulting column names come from the **rightmost** argument (which is unexpected, but lines up with the strange suffix behavior)

#### What is the expected behavior?

The `suffix` issue is definitely unintended behavior, as it should work using the same names as what would be output by the unmodified expression. Regarding which side to use for the output multi-column names, the leftmost side seems like it would be consistent with everything else, although I could see issues and exceptions crop up with non-commutative operations where using the left size may be undesirable, like `pl.lit(10) / pl.col(["a","b", "c"])`, which currently gives a duplicate error as it tries to use "literal" as the name for all columns.

In the longer term, there may be a need for a better mechanism to pick the output names of multicolumn expressions.

**Comment by sm-Fifteen** [comment]
> Thanks for the issue report. This can get complicated very quickly. That's why I want to use the left hand side only for the naming. That has some unwanted behavior such as `pl.lit() * ..` having the name literal, as you said.

I understand. It does becomes really tricky when you're dealing with non-commutative operations, where you can't just swap the left-hand side to avoid the problem. It might be interesting to have something like `keep_name()` here, so users can override that behavior if Polars can't figure it out. Something like `pl.lit(10) / pl.col(["a","b", "c"]).use_names()`, for instance. A variant of `alias()` that takes an array of names, like `(pl.lit(10) / pl.col(["a","b", "c"])).alias(["a","b", "c"])` or re-recieve the initial col selector like `(pl.lit(10) / pl.col(pl.all().except("foo")).alias(pl.all().except("foo"))` (which looks silly but I tend to keep my selectors as constants so I can re-use them) would also be convenient.

Multi-column operations is kind of a killer feature of Polars for me, as that one feature suddenly makes a number of things that were very inconvenient to do in Pandas a breeze.

**Comment by zundertj** [comment]
We have [keep_name](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.keep_name.html#polars.Expr.keep_name) now available, which allows you to do:

```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [1, 2], "b": [3, 4]})
>>> df.select((pl.lit(10)/pl.all()).keep_name())
shape: (2, 2)
┌──────┬──────────┐
│ a    ┆ b        │
│ ---  ┆ ---      │
│ f64  ┆ f64      │
╞══════╪══════════╡
│ 10.0 ┆ 3.333333 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5.0  ┆ 2.5      │
└──────┴──────────┘
```
