### ISSUE TITLE
Support Arrow IPC streaming files

### ISSUE THREAD

**Issue by joshuataylor** [pola-rs/polars#3778]
**This is crossposted from https://github.com/pola-rs/polars/issues/2424 , to track the feature of reading and writing Arrow streaming files.**

For context about Arrow Streams, please read https://jorgecarleitao.github.io/arrow2/io/ipc_stream_read.html .
Here is a quick primer about the streaming files from Arrow: https://arrow.apache.org/docs/python/ipc.html

The initial version should only support reading the entire file, then future work can be done on the actual *streaming* of data if there is enough demand.

I'm keen to get this into polars, as Snowflake uses this for their response format and would be awesome to get it in for reading data straight from SF into Polars (with minimal massaging of data).

I've started looking into this, and the major blocker I can see is projections.

In arrow2, projections are not supported here: https://github.com/jorgecarleitao/arrow2/blob/main/src/io/ipc/read/stream.rs#L185

So we will need to build the projection from the chunks.

Thoughts?

**Comment by jorgecarleitao** [comment]
Added tracking issue on arrow2: https://github.com/jorgecarleitao/arrow2/issues/1095
