### ISSUE TITLE
add `dt.quarter` expression

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#3780]

**Comment by ritchie46** [comment]
>  Curious what the scope is expected to be. In my world fiscal quarters are preferred over regular quarters. Not everyone has the same fiscal quarter.

Let's start with regular quarters. ^^

**Comment by cnpryer** [comment]
I might tinker with the idea. Not sure if it really needs to be part of the API, but if I'm not oversimplifying it it'd basically just be "create quarters from this date". Fiscal years start at a specific date so maybe that's an option for .fquarter or some kind of .quarter_from.
