### ISSUE TITLE
Can not use describe method for a DataFrame in Rust

### ISSUE THREAD

**Issue by DataPsycho** [pola-rs/polars#3785]
#### What language are you using?

**Rust**, 

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

polars = "0.22.8"

#### What operating system are you using polars on?

MacOs

#### What language version are you using
rustc 1.61.0

#### Describe your bug.
I was trying out the feature according to API documentation and was trying to use the `describe` method but could not run the API documentation example in Describe

#### What are the steps to reproduce the behavior?

```rust
use polars::prelude::*;

fn describe_top_features(){
    let df1: DataFrame = df!("categorical" => &["d","e","f"],
                         "numeric" => &[1, 2, 3],
                         "object" => &["a", "b", "c"]).unwrap();
    assert_eq!(df1.shape(), (3, 3));

    let df2: DataFrame = df1.describe();
    assert_eq!(df2.shape(), (8, 4));
    println!("{}", df2);
}

fn main() {
    describe_top_features()
}
```

But following error is thrown:
```
error[E0599]: no method named `describe` found for struct `polars::prelude::DataFrame` in the current scope
  --> src/main.rs:43:30
   |
43 |     let df2: DataFrame = df1.describe();
   |                              ^^^^^^^^ method not found in `polars::prelude::DataFrame`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `wine_pipeline` due to previous error
```
The api doc [link](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.describe)

**Comment by ritchie46** [comment]
```
    #[cfg(feature = "describe")]
    pub fn describe(&self, percentiles: Option<&[f64]>) -> Self
```

**Comment by DataPsycho** [comment]
Now I understand the problem. Can you write how can I add that info into cargo.toml file to enable that feature. Thanks

**Comment by DataPsycho** [comment]
Finally got it. I have added the features into the toml file. `polars = {version = "0.22.8", features = ["describe", "lazy"]}` now its working.
