### ISSUE TITLE
Add a normalisation option to dynamic/rolling group bys

### ISSUE THREAD

**Issue by savente93** [pola-rs/polars#3800]
Adding the option to have a group by also perform a normalization automatically would be a super nice QoL feature imo. My motivation is this: image I have three lamps, and a column `perc_lights_on` that measures what percentage of them are on at a 5 min interval. if I want to group by that column but at a daily resolution I need to sum them, and divide by the frequency ratio to make sure the range is still within `[0,100]`. If there are overlapping periods I'd need to take that into account as well. If I need to the total amount of light, that needs to take both the current and original time scale into account. When polars is doing the up/down sampling it's already taking these things into account so it seems like a really convinent time to do that. 

API proposal: 
Currently it should go something like this: 
```Python
import polars as pl
from polars import lit, col, all
from datetime import datetime
df = pl.date_range(datetime(2022,1,1),datetime(2022,1,2),interval='5m',name="ts").to_frame().with_column(lit(0.3).alias('perc_light_on'))
df_hourly = df.groupby_dynamic(index_column="ts", every='1h').agg([
    ((col('perc_light_on').sum()) * (60/5)).alias("perc_light_on_hourly_rescaled"),
    (col('perc_light_on').sum() / (60/5)).alias("perc_light_on_hourly_total"),
    col('perc_light_on').mean().alias("perc_light_on_hourly_mean")])
df_hourly.head()
``` 
(Sorry if the maths is off somehow, I always get so confused whether I have to divide or multiply, which is in part why I'm making this request) 

Here is how I imagine it
```Python
import polars as pl
from polars import lit, col, all
from datetime import datetime
df = pl.date_range(datetime(2022,1,1),datetime(2022,1,2),interval='5m',name="ts").to_frame().with_column(lit(0.3).alias('perc_light_on'))
df_hourly = df.groupby_dynamic(index_column="ts", every='1h').agg([
    ((col('perc_light_on').sum(normalize='area'))).alias("perc_light_on_hourly_rescaled"),
    (col('perc_light_on').sum(normalize='rate')).alias("perc_light_on_hourly_total"),
    col('perc_light_on').mean(normalize='none').alias("perc_light_on_hourly_mean")])
df_hourly.head()
``` 
Originally I thought that we could have the normalize argument be living in the groupby part, but now I realize that his offers far more flexibility and accounts for the fact that in a group by statement not all of the expressions need it, or need the same. The names of the that get passed to the normalize I'm not married to, they can be whatever. I chose these because you have to do different things if you're resealing and caring about the rate at which your variable changes or whether you're keeping track of the total amount (i.e. the area under your "curve")  For this toy example it's not too bad but for more complex situations this could be such a life saver. 

What do you think? Feedback on the idea is of course welcome.

**Comment by datenzauberai** [comment]
I'm not sure about the use-case here. The factor 60/5 is the number of observations in the 1h interval for a measurement every 5 minutes. This is pl.col('A').count() if there is no data missing.

pl.col('A').sum(normalize='area') = pl.col('A').sum() * pl.col('A').count()
pl.col('A').sum(normalize='rate') = pl.col('A').sum() / pl.col('A').count() = pl.col('A').mean()

**Comment by ritchie46** [comment]
As @datenzauberai points out there is no need for that. You can make an expression that does ehat you want.

```python

def normalized_sum(name: str):
    return pl.col(name).sum() / pl.count()

```

You are free to make whatever aggregate you want from compositie expressions.
