### ISSUE TITLE
`join_asof` not returning expected result

### ISSUE THREAD

**Issue by thatlittleboy** [pola-rs/polars#3809]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.5

#### What operating system are you using polars on?

MacOS 12.2

#### What language version are you using
python 3.9.10

#### Describe your bug.

The [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.join_asof.html) describes the `join_asof` method (with `strategy=backward`) as

> For each row in the left DataFrame:
> A “backward” search selects the last row in the right DataFrame whose ‘on’ key is less than or equal to the left’s key.

But this doesn't seem to be the case. See MWE.

#### What are the steps to reproduce the behavior?

**Example**

```python
import polars as pl
import pandas as pd

df1 = pl.DataFrame({"a": [1., 2., 3.], "b": ["lrow1", "lrow2", "lrow3"]})
df2 = pl.DataFrame({"a": [0.59, 1.49, 2.89], "b": ["rrow1", "rrow2", "rrow3"]})

df1.join_asof(df2, on="a", strategy="backward")
```

Each df's `a` column is sorted, and for corresponding rows, `df1.a < df2.a`.  
Thus, I am expecting an output for `b_right` to be `["rrow1", "rrow2", "rrow3"]`.

#### What is the actual behavior?

```
shape: (3, 3)
┌─────┬───────┬─────────┐
│ a   ┆ b     ┆ b_right │
│ --- ┆ ---   ┆ ---     │
│ f64 ┆ str   ┆ str     │
╞═════╪═══════╪═════════╡
│ 1.0 ┆ lrow1 ┆ rrow2   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.0 ┆ lrow2 ┆ rrow3   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3.0 ┆ lrow3 ┆ rrow3   │
└─────┴───────┴─────────┘
```

#### What is the expected behavior?

Expected `b_right` to be `["rrow1", "rrow2", "rrow3"]`.

Consider the analogous function in `pandas` (I'm assuming polars' `join_asof` is emulating pandas' `merge_asof`)...

```python
[ins] In [4]: import pandas as pd
         ...: df1 = pd.DataFrame({"a": [1., 2., 3.], "b": ["lrow1", "lrow2", "lrow3"]})
         ...: df2 = pd.DataFrame({"a": [0.59, 1.49, 2.89], "b": ["rrow1", "rrow2", "rrow3"]})
         ...:
         ...: pd.merge_asof(df1, df2, on="a", direction="backward")
Out[4]:
     a    b_x    b_y
0  1.0  lrow1  rrow1
1  2.0  lrow2  rrow2
2  3.0  lrow3  rrow3
```

**Comment by ritchie46** [comment]
Right, we internally cast the join key to integers, this should not be done for floats and is fixed in #3812. We release next week. Until then you could multiply your keys to the amount of digits you want for accuracy.

E.g. if you want correct float asof join for 6 digits, multiply with a million before joining.
