### ISSUE TITLE
Difference polars[arrow] and polars

### ISSUE THREAD

**Issue by TheBubblePopped** [pola-rs/polars#3814]
The title basically says it all. What is the difference between saying polars[arrow] or polars? I can't feel any difference.

I actually noticed that my program is running a little bit faster when [pyarrow] is not selected

The Author wrote:

`pyarrow is an optional dependency. Polars works for many operations without pyarrow. This saves a large dependency.`

But which operations won't work? Any critical functions that need pyarrow?

**Comment by ritchie46** [comment]
> I actually noticed that my program is running a little bit faster when [pyarrow] is not selected

What of operations do you do? It should not really matter.

> But which operations won't work? Any critical functions that need pyarrow?

Converting to pandas, pyarrow readers and some constructors.

**Comment by TheBubblePopped** [comment]
The strange thing is. If i don't have pyarrow and it try to do a df.select('col').unique().to_numpy() it causes a NotImplementedError.

As soon as i install pyarrow it's gone.

**Comment by ritchie46** [comment]
We use pyarrow for that conversion.
