### ISSUE TITLE
pyo3_runtime.PanicException: assertion failed: index < self.len() when using when.then expression

### ISSUE THREAD

**Issue by TheBubblePopped** [pola-rs/polars#3817]
The error only occurs if the DataFrame is empty. It only happens when interval is 3mo and works when it's 1y.

Steps to reproduce:
```

df = pl.DataFrame({"A": []}).with_column(pl.col('A').cast(pl.Date))

def is_leap_year(name: str):
    year = pl.col(name).dt.year()
    return (year % 4 == 0) & (year % 100 != 0) | (year % 400 == 0)


def convert(df, column: str, interval: str = "3mo"):
    col = pl.col(column).dt

    if interval == "3mo":
        df = df.with_column(
            pl.when(col.month() < 4)
            .then(pl.date(col.year(), 4, 1))
            .when(col.month() < 7)
            .then(pl.date(col.year(), 7, 1))
            .when(col.month() < 10)
            .then(pl.date(col.year(), 10, 1))
            .otherwise(pl.date(col.year() + 1, 1, 1))
            .alias(column)
        )
    elif interval == "1y":
        df = df.with_column(
            pl.when(is_leap_year(column))  # type: ignore
            .then(pl.col(column) + timedelta(days=366))
            .otherwise(pl.col(column) + timedelta(days=365))
            .alias(column),
        )

    return df

convert(df, 'A', interval='3mo')

```

Output:

> thread '<unnamed>' panicked at 'assertion failed: index < self.len()', /github/workspace/polars/polars-core/src/chunked_array/ops/take/take_single.rs:59:18
> Traceback (most recent call last):
>   File "/opt/bitnami/python/lib/python3.10/code.py", line 90, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "<input>", line 10, in convert_to_quarter_end
>   File "/opt/bitnami/python/lib/python3.10/site-packages/polars/internals/frame.py", line 3788, in with_column
>     return self.with_columns([column])
>   File "/opt/bitnami/python/lib/python3.10/site-packages/polars/internals/frame.py", line 4744, in with_columns
>     self.lazy()
>   File "/opt/bitnami/python/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 622, in collect
>     return self._dataframe_class._from_pydf(ldf.collect())
> pyo3_runtime.PanicException: assertion failed: index < self.len()

When i try to catch the error i just get an output like this:

> A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.

**Comment by datenzauberai** [comment]
The problem is the expression `pl.date` with an empty column. This works:

```python
df = pl.DataFrame(pl.Series(name='date', values=[date(2022, 12, 31)]))
df.select(pl.date(pl.col('date').dt.year(), 1, 1))
```

This does not:

```python
df = pl.DataFrame(pl.Series(name='date', dtype=pl.Date))
df.select(pl.date(pl.col('date').dt.year(), 1, 1))
```

An additional remark: You could check the code handling leap years (this was discussed on another issue around here). I think it might not behave as intended:

2019-02-01 + 365 days = 2020-02-01
2019-03-01 + 365 days = 2020-02-29 (should be 2020-03-01?)
2020-02-01 + 366 days = 2021-02-01
2020-02-29 + 366 days = 2021-03-01 (should be 2021-02-28?)
2020-03-01 + 366 days = 2021-03-02 (should be 2021-03-01?)
