### ISSUE TITLE
Provide Anaconda package

### ISSUE THREAD

**Issue by impredicative** [pola-rs/polars#383]
Noting that pandas is available as a conda package in the [conda-forge](https://anaconda.org/conda-forge/pandas) and [anaconda](https://anaconda.org/anaconda/pandas) channels, I request that `py-polars` also be available similarly. If provided, it would have to consistently be released at about the same time as the PyPI package. This is a low priority request as I can currently install and use the PyPI package.

**Comment by ritchie46** [comment]
To my knowledge compiling for anaconda isn't trivial. It assumes pure python code, or [a not-Rust compiler](https://conda-forge.org/docs/maintainer/knowledge_base.html#dep-compilers). 

I shall tag it help-wanted. Maybe someone with more knowledge on anaconda/ cross-compiling could pick that up.

**Comment by alippai** [comment]
I can try creating a conda package in 1-2 weeks if others don't succeed.

**Comment by ritchie46** [comment]
@alippai That would be great!

**Comment by sugatoray** [comment]
@alippai @ritchie46 Any update on creating a conda package?

**Comment by sugatoray** [comment]
cc: @alippai @ritchie46 

I started a PR on conda-forge for `polars`. But am getting errors for the following experimental feature (`SIMD`). How do I disable `SIMD` while compiling it?

[Link to code: SIMD](https://github.com/pola-rs/polars/blob/f70d21955a49a4059538571ca7a8f62a7e50d0cc/polars/src/lib.rs#L56-L58)

conda-forge polars branch: https://github.com/sugatoray/staged-recipes/tree/polars
PR: https://github.com/conda-forge/staged-recipes/pull/16717
Latest job run failure (at build stage): https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=401212&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823

**Comment by Maxyme** [comment]
@sugatoray the issue is that simd is a nightly-only experimental API and therefore Polars needs rust-nightly to compile.
I created a PR here (https://github.com/conda-forge/staged-recipes/pull/18906) and got most of my inspiration from ORJSON's feedstock (https://github.com/conda-forge/orjson-feedstock) to download and install rust-nightly from linux and windows.

**Comment by timkpaine** [comment]
abandoned attempts:
https://github.com/conda-forge/staged-recipes/pull/17379
https://github.com/conda-forge/staged-recipes/pull/18079

Open attempts:
https://github.com/conda-forge/staged-recipes/pull/16717
https://github.com/conda-forge/staged-recipes/pull/18244

**Comment by timkpaine** [comment]
@Maxyme hopefully yours works, mine was working but it takes >6 hours to run and times out conda's build limit

**Comment by Maxyme** [comment]
@timkpaine Thanks for the information, I was able to have a succesful macos build yesterday, and it looks like linux works too, just having some issues still with the windows build, either I can fix it, or will disable it for now.

**Comment by timkpaine** [comment]
@Maxyme if you skip windows and add me on the feedstock I can look at windows. I would also add @ritchie46 and @sugatoray to the feedstock list (you can add folks after the feedstock is made with a simple command that skips CI as well)

**Comment by Maxyme** [comment]
@timkpaine I updated the pr to add suggested maintainers and skipping windows builds for now. Thanks for looking into this, I think it's quite close to building successfully, I linked the issue as a comment in the meta.yaml to help for the subsequent builds.
I'm excited to see this project on conda as it will open it up to more users.

**Comment by timkpaine** [comment]
Awesome this is good, im glad this will finally get across the line after 5 attempts! It will be good for other rust-based python projects down the line as well as this is likely the most popular/visible one onboarding to conda forge

**Comment by sugatoray** [comment]
@Maxyme Thank you, for putting time into this and making it work. 🚀

**Comment by Maxyme** [comment]
Update: polars is now an anaconda package on channel conda-forge: https://anaconda.org/conda-forge/polars/files.
