### ISSUE TITLE
Groupby_dynamic returns wrong results

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#3832]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.50

#### What operating system are you using polars on?

MacOS 11.6.7

#### What language version are you using
python 3.10

#### Describe your bug.

`groupby_dynamic` returns incorrect results.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame(
    {
        "date": [
            "2022-06-27", "2022-06-28", "2022-06-01",
            "2022-05-27","2022-05-29", "2022-05-01"]
    }
).with_column(col("date").str.strptime(pl.Date, "%Y-%m-%d")).lazy()

(
    df
    .sort("date")
    .groupby_dynamic("date", every="1mo")
    .agg(pl.count())
    .collect()
)
```

#### What is the actual behavior?

```
shape: (3, 2)
┌────────────┬───────┐
│ date       ┆ count │
│ ---        ┆ ---   │
│ date       ┆ u32   │
╞════════════╪═══════╡
│ 2022-05-01 ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2022-05-01 ┆ 3     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2022-06-01 ┆ 2     │
└────────────┴───────┘
```

#### What is the expected behavior?

```
shape: (2, 2)
┌────────┬───────┐
│ month  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ 2022-6 ┆ 3     │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2022-5 ┆ 3     │
└────────┴───────┘
```

**Comment by ritchie46** [comment]
Can you show the boundaries and aggregate as list? This might be correct.

**Comment by thobai** [comment]
Here comes the code with boundaries and list aggregation:

```
import polars as pl
from polars import col

df = pl.DataFrame(
    {
        "row": [1,2,3,4,5,6],
        "date": [
            "2022-05-01","2022-05-27","2022-05-29",
            "2022-06-01","2022-06-27", "2022-06-28"
        ]
    }
).with_column(col("date").str.strptime(pl.Date, "%Y-%m-%d")).lazy()

print(
    df
    .groupby_dynamic("date", every="1mo", include_boundaries=True)
    .agg([
        pl.count(),
        col("row").list()
    ])
    .collect()
)
```

The result is
```
┌─────────────────────┬─────────────────────┬────────────┬───────┬───────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ date       ┆ count ┆ row       │
│ ---                 ┆ ---                 ┆ ---        ┆ ---   ┆ ---       │
│ datetime[ms]        ┆ datetime[ms]        ┆ date       ┆ u32   ┆ list[i64] │
╞═════════════════════╪═════════════════════╪════════════╪═══════╪═══════════╡
│ 2022-04-01 00:00:00 ┆ 2022-05-01 00:00:00 ┆ 2022-05-01 ┆ 1     ┆ [1]       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-05-01 00:00:00 ┆ 2022-06-01 00:00:00 ┆ 2022-05-01 ┆ 3     ┆ [2, 3, 4] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-06-01 00:00:00 ┆ 2022-07-01 00:00:00 ┆ 2022-06-01 ┆ 2     ┆ [5, 6]    │
└─────────────────────┴─────────────────────┴────────────┴───────┴───────────┘
```

I find this confusing. The first day of each month is assigned to group of the previous month. While here the group with the boundary from 1st April to 1st May is assigned the date of May which then occurs twice...

**Comment by ritchie46** [comment]
```python
(df
    .groupby_dynamic("date", every="1mo",  include_boundaries=True)
    .agg([
        pl.col("date").list().alias("list")
    ]))
```

```
shape: (3, 4)
┌─────────────────────┬─────────────────────┬────────────┬─────────────────────────────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ date       ┆ list                                │
│ ---                 ┆ ---                 ┆ ---        ┆ ---                                 │
│ datetime[ms]        ┆ datetime[ms]        ┆ date       ┆ list[date]                          │
╞═════════════════════╪═════════════════════╪════════════╪═════════════════════════════════════╡
│ 2022-04-01 00:00:00 ┆ 2022-05-01 00:00:00 ┆ 2022-05-01 ┆ [2022-05-01]                        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-05-01 00:00:00 ┆ 2022-06-01 00:00:00 ┆ 2022-05-01 ┆ [2022-05-27, 2022-05-29, 2022-06... │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-06-01 00:00:00 ┆ 2022-07-01 00:00:00 ┆ 2022-06-01 ┆ [2022-06-27, 2022-06-28]            │
└─────────────────────┴─────────────────────┴────────────┴─────────────────────────────────────┘


```

This shows the boundaries and the data points. If we combined that with the default `closed` argument, which is `"right"`, this means that data points on the right side of the boundary are included in that window. It seems correct to me.

I believe you want to have a `"left"` closed window:

```python
(df
    .groupby_dynamic("date", every="1mo", closed="left", include_boundaries=True)
    .agg([
        pl.col("date").list().alias("list")
    ])
)
```

```
shape: (2, 4)
┌─────────────────────┬─────────────────────┬────────────┬─────────────────────────────────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ date       ┆ list                                │
│ ---                 ┆ ---                 ┆ ---        ┆ ---                                 │
│ datetime[ms]        ┆ datetime[ms]        ┆ date       ┆ list[date]                          │
╞═════════════════════╪═════════════════════╪════════════╪═════════════════════════════════════╡
│ 2022-05-01 00:00:00 ┆ 2022-06-01 00:00:00 ┆ 2022-05-01 ┆ [2022-05-01, 2022-05-27, 2022-05... │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-06-01 00:00:00 ┆ 2022-07-01 00:00:00 ┆ 2022-06-01 ┆ [2022-06-01, 2022-06-27, 2022-06... │
└─────────────────────┴─────────────────────┴────────────┴─────────────────────────────────────┘

```

**Comment by thobai** [comment]
Ah nice, I was missing that option. Is there a specific reason why you made `closed=right` the default? I could imagine that those time aggregations are a major use case for the `groupby_dynamic` function and to my mind `closed=left` would be the better default for those use cases. What do you think?

**Comment by ritchie46** [comment]
Closed right is default in pandas in most window operations so we copied that.

**Comment by cbilot** [comment]
> I could imagine that those time aggregations are a major use case for the groupby_dynamic function and to my mind closed=left would be the better default for those use cases.

Respectfully, changing defaults after people begin using code is a tricky business.

Consider the impact to users who have code currently in production that rely on the current default.

They will be expected to search through their code base and make changes where needed. (Presumably, most users won’t be thrilled with that, and will want a good reason for the change.)

Worse still, what if some users are unaware of the change in defaults?  The change might not result in an error, allowing wrong values to go unnoticed, until it is detected in other ways.

Unless there is a strong, defensible reason for a change in defaults, I would argue against changing any defaults.  And in the event that we do change defaults, we need a good communication strategy and time to allow people to make their necessary changes.

**Comment by thobai** [comment]
@cbilot and @ritchie46: You both have very valid points. I'll close this issue.

**Comment by braaannigan** [comment]
> > I could imagine that those time aggregations are a major use case for the groupby_dynamic function and to my mind closed=left would be the better default for those use cases.
> 
> Respectfully, changing defaults after people begin using code is a tricky business.
> 
> Consider the impact to users who have code currently in production that rely on the current default.
> 
> They will be expected to search through their code base and make changes where needed. (Presumably, most users won’t be thrilled with that, and will want a good reason for the change.)
> 
> Worse still, what if some users are unaware of the change in defaults? The change might not result in an error, allowing wrong values to go unnoticed, until it is detected in other ways.
> 
> Unless there is a strong, defensible reason for a change in defaults, I would argue against changing any defaults. And in the event that we do change defaults, we need a good communication strategy and time to allow people to make their necessary changes.

The great majority of Polars users are still in the future. This was a poor default chosen by an honest mistake and maintaining it will cause many more analysis errors in the future than will be caused by nipping it in the bud now. 

Best to change it now with appropriate change messages in place for a suitable period

**Comment by befowler** [comment]
I agree. Polars is a new library gaining adoption. Much less painless to make this change now than in the future. Just because a default setting has been in place for a long time shouldn’t be the justification for keeping it; particularly if the majority of use cases for these aggregations is a left closure. 

For me I don’t see any time a right closure would be correct. If this groupby is used in feature engineering you never would want data from the future leaking into the current date’s value as that’s the definition of target leakage. By using a right closure that is exactly what is going to happen.
