### ISSUE TITLE
[python-polars] Is there a way to read from stdin?

### ISSUE THREAD

**Issue by mrvollger** [pola-rs/polars#3834]
https://stackoverflow.com/questions/72781530/is-there-a-way-to-read-from-stdin-with-polars

**Comment by mutecamel** [comment]
According to the [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv.html#polars.read_csv), the following code should work,

```
$ printf "a,b,c\n1,2,3\n" | python3 -c 'import polars as pl; import sys; print(pl.read_csv(sys.stdin))'
```

because the type of `sys.stdin` is `TextIO`. But in fact, presently polars raises a `FileNotFoundError`.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/io.py", line 333, in read_csv
    df = DataFrame._read_csv(
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/frame.py", line 587, in _read_csv
    self._df = PyDataFrame.read_csv(
FileNotFoundError: No such file or directory (os error 2)
```

This might be a workaround, before polars fixes this problem.

```
$ printf "a,b,c\n1,2,3\n" | python3 -c 'import polars as pl; import sys; import io; print(pl.read_csv(io.StringIO(sys.stdin.read())))'
shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 2   ┆ 3   │
└─────┴─────┴─────┘
```

**Comment by mrvollger** [comment]
Thanks for the workaround, working well for me so far!

I also started with `sys.stdin` but got the same error. So I think I will leave open since it seems like `sys.stdin` should work but doesn't.

**Comment by ritchie46** [comment]
It should not work. If `read_csv` gets a string as first argument it will interpet it as a file path, not the files content. If you want to pass the content you need to use StringIO

**Comment by mrvollger** [comment]
Got it, thanks :)
