### ISSUE TITLE
Naming differences between lazy and eager apis?

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#3846]
#### What language are you using?

Python

#### Have you tried latest version of polars?
 yes

#### What version of polars are you using?

0.13.50

#### What operating system are you using polars on?

Mac OS 12.3.1

#### What language version are you using
Python 3.10

#### Describe your bug.

The eager and lazy apis have at least one difference in their variable naming: `.join()`:

```python
# Note the df vs ldf
pl.DataFrame().join(df: DataFrame = )
pl.LazyFrame().join(ldf: LazyFrame = )
```

I'd argue that these should both be `df` to make debugging easier when moving from the eager to lazy apis. That it has to be of `LazyFrame` type comes clearly from the type hint.

Today I was using the lazy api and was getting a `NotFoundError: some_column_name`, with no hint as to where the error was occuring, since the traceback just points to the line containing`.collect()`. (see minimum example below)

I had several joins in the code, and had to replace all entries of `ldf` with `df`.

This wasn't a major pain point, but I think it's worth using `df` unless there are any good reasons against it. 

### Minimum example:

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6.0, 7.0, 8.0],
    }
)

df_other = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "ham": ["a", "b", "c"],
    }
)

df2 = df.lazy().join(ldf=df_other.lazy(), on="foo2")
df2.collect()

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb Cell 10' in <cell line: 18>()
     [10](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=9) df_other = pl.DataFrame(
     [11](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=10)     {
     [12](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=11)         "foo": [1, 2, 3],
     [13](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=12)         "ham": ["a", "b", "c"],
     [14](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=13)     }
     [15](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=14) )
     [17](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=16) df2 = df.lazy().join(ldf=df_other.lazy(), on="foo2")
---> [18](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/explore.ipynb#ch0000008?line=17) df2.collect()

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/polars/internals/lazy_frame.py:622, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown)
    612     projection_pushdown = False
    614 ldf = self._ldf.optimization_toggle(
    615     type_coercion,
    616     predicate_pushdown,
   (...)
    620     slice_pushdown,
    621 )
--> 622 return self._dataframe_class._from_pydf(ldf.collect())

NotFoundError: foo2
```

**Comment by ritchie46** [comment]
You request we change the keyword argument name or the type?

**Comment by thomasaarholt** [comment]
Oh, sorry if that wasn't clear. 

The argument name.

**Comment by ritchie46** [comment]
Check.. i guess we coul name it `other` 👍

**Comment by thomasaarholt** [comment]
If you'd like to keep `"df"` strictly referring to non-lazy frames, then I agree :)

**Comment by ritchie46** [comment]
Could you make a PR for this one? We could get the old name from the `**kwargs` to preserve backwards compatibility.

**Comment by ghuls** [comment]
Fixed in https://github.com/pola-rs/polars/pull/3855
