### ISSUE TITLE
Overflow with `abs` on integer size boundaries

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#3847]
#### What language/platform are you using?

Python 3.9, macOS 12.4, Polars 0.13.50

#### Describe your bug.

An `abs` operation on the smallest integer of a given size (eg: min(8 bit), min(32 bit)) will cause a `PanicException` via overflow, as the absolute value of the smallest integer of a given size type implies an upcast to the next integer size up that doesn't happen.

eg: signed int8 range is `-128 => 127`, so `abs(-128)` fails without an implicit upcast, as `128` is out of range.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

s = pl.Series( [-128], dtype=pl.Int8 )
print( s )

# shape: (1,)
# Series: '' [i8]
# [
#     -128
# ]

print( s.abs() )

# thread '<unnamed>' panicked at 'attempt to negate with overflow', 
#     .cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.15/src/sign.rs:75:1
PanicException: attempt to negate with overflow
```

(Discovered with the following test, using the new hypothesis strategies, as `assert_frame_equals` has an internal call to `abs` when checking for diffs/equality):

```python
@given(df=dataframes())
def test_df_equals_itself(df: pl.DataFrame) -> None:
    assert_frame_equal(df, df)
    assert_frame_equal(df, df.clone())
```

#### What is the expected behavior?

Return a series containing 128 (probably as an int16, which is the next size up).

```python
# shape: (1,)
# Series: '' [i16]
# [
#     128
# ]
```

**Comment by ritchie46** [comment]
I am not convinced of this yet. As checking the minimum size is very expensive. We could use `unsize_abs` but that means you will always get a `UInt8` type as return type.

**Comment by alexander-beedie** [comment]
> I am not convinced of this yet. As checking the minimum size is very expensive. We could use `unsize_abs` but that means you will always get a `UInt8` type as return type.

That could work; depends on whether it's thought more reasonable to just throw the error (as happens now), or implicitly upcast for the caller - I don't have a strong opinion here, as either is a legitimate thing to do, and compromising performance isn't ideal. But in either case I'll patch `assert_frame_equal` so that that check can succeed  ;)

**Comment by alexander-beedie** [comment]
Thinking about it more, the overflow is consistent with other ops (127 + 1), (127 * 2), so maybe a fix for `assert_frame_equal` is actually all that's needed. Let's go with that?

**Comment by ritchie46** [comment]
Yes, I think that's best.

**Comment by alexander-beedie** [comment]
> Yes, I think that's best.

Done; PR incoming one I've added a test...
