### ISSUE TITLE
Expression-level expansion for multiple `struct.field` names, as exists for `pl.col`

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#3859]
#### Describe your feature request

Struct-field equivalents to the super-handy `pl.col("a","b","c","d")` and `pl.col("*")` expansions would be a _really_ nice option as, once the struct name and/or number of desired fields to break-out gets large, the amount of boilerplate and number of separate calls/expressions goes up significantly.

```python
# currently (all explicit):
df.select([
    pl.col("id"),
    pl.col("struct_name").struct.field("a"),
    pl.col("struct_name").struct.field("b"),
    pl.col("struct_name").struct.field("c"),
    pl.col("struct_name").struct.field("d"),
    pl.col("struct_name").struct.field("e"),
    pl.col("struct_name").struct.field("f"),
    pl.col("struct_name").struct.field("g"),
    pl.col("struct_name").struct.field("h"),
]

# ideally (expanded for the given fields):
df.select([
    pl.col("id"),
    pl.col("struct_name").struct.field("a","b","c","d","e","f","g","h"),
])

# and (expanded for all fields):
df.select([
    pl.col("id"),
    pl.col("struct_name").struct.field("*"),
])
```

**Comment by braaannigan** [comment]
This would be great. For one example you could do `value_counts` in lazy mode and get a Lazy/DataFrame:
```python
(
df
.lazy()
.select(pl.col("values").value_counts())
.select(pl.col("values").struct.field("*")
)
```
At present to do value_counts in lazy mode you need to do an extraction of the struct fields that's a bit tedious.

**Comment by braaannigan** [comment]
Also: there is a struct.fields method to get field names in Series but not in Expressions. It would be good to have this in expressions as well

**Comment by sm-Fifteen** [comment]
#10179, the PR for extract_groups, has now been merged, but extracting the fields from the resulting struct still involves either struct unnesting or selecting each field one by one in a second pass. While this is mainly an ergonomics enhancement, it's likely to start seeing more demand in the coming releases.

**Comment by cmdlineluser** [comment]
I did also notice an initial `pl.unnest()` implementation https://github.com/pola-rs/polars/pull/3164

spawned from https://github.com/pola-rs/polars/issues/3123
