### ISSUE TITLE
Silent casting to the same categorical space in concat 

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#3865]
Very nice library, enjoying using it every day very much. 

Without pl.Config.set_global_string_cache() in concat polars silently cast second dataframe categorical namespace to the first. 
If it's possible it would be nice to have warning like in case of join. 

```python
import polars as pl
frames = [
    pl.DataFrame([{"s": "1"}]),
    pl.DataFrame([{"s": "2"}]),
]
pl.concat([
    df.with_column(pl.col("s").cast(pl.Categorical))
    for df in frames
])

```

<div>

<table border="1" class="dataframe" >
<small>shape: (2, 1)</small>
<thead>
<tr>
<th>
s
</th>
</tr>
<tr>
<td>
cat
</td>
</tr>
</thead>
<tbody>
<tr>
<td>
"1"
</td>
</tr>
<tr>
<td>
"1"
</td>
</tr>
</tbody>
</table>
</div>

**Comment by ghuls** [comment]
You need to concat them under the same string cache: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.StringCache.html#polars-stringcache
```python
In [3]: import polars as pl
   ...: frames = [
   ...:     pl.DataFrame([{"s": "1"}]),
   ...:     pl.DataFrame([{"s": "2"}]),
   ...: ]
   ...: with pl.StringCache():
   ...:     df_concat = pl.concat([
   ...:         df.with_column(pl.col("s").cast(pl.Categorical))
   ...:         for df in frames
   ...:     ])
   ...: df_concat
Out[3]: 
shape: (2, 1)
┌─────┐
│ s   │
│ --- │
│ cat │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
└─────┘
```
