### ISSUE TITLE
Syntactic sugar 

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#3866]
Big thanks for the work you are doing maintaining this very nice library! 

In the code below two helpers that can improve readability of the code. This helpers make:
1. Names of new columns columns will be on the same level. It makes more easier to understand what was added to dataframe.  
2. Access to the columns three letters shorter. Also removes redundant brackets witch improves readability especially in complex expression with a lot of brackets. 

And it seems this improvements can be added without much harm done. 
```python
import polars as pl
import numpy as np

class ColHelper:
    def __call__(self, key):
        return pl.col(key)
    def __getattr__(self, key):
        return pl.col(key)
col = ColHelper()

def with_sugar(self, *args, **kwargs):
    expr_list = list(args)
    for key, expr in kwargs.items():
        expr_list.append(expr.alias(key))
    return self.with_columns(expr_list) 
pl.DataFrame.with_sugar = with_sugar

pl.DataFrame([
    pl.Series("a", np.arange(100)),
    pl.Series("b", np.arange(100, 200)),
    pl.Series("c", np.arange(200, 300)),
]).with_sugar( # Suggestion 
    d = col.a + col.b,
    e = ((col.a + col.b) / col.c) + col.a,
).with_columns([ # Current approach 
    (col("a") + col("b")).alias("d"),
    (((col("a") + col("b")) / col("c")) + col("a")).alias("e"),
]).head(5)
```

<div>

<table border="1" class="dataframe" >
<small>shape: (5, 5)</small>
<thead>
<tr>
<th>
a
</th>
<th>
b
</th>
<th>
c
</th>
<th>
d
</th>
<th>
e
</th>
</tr>
<tr>
<td>
i64
</td>
<td>
i64
</td>
<td>
i64
</td>
<td>
i64
</td>
<td>
f64
</td>
</tr>
</thead>
<tbody>
<tr>
<td>
0
</td>
<td>
100
</td>
<td>
200
</td>
<td>
100
</td>
<td>
0.5
</td>
</tr>
<tr>
<td>
1
</td>
<td>
101
</td>
<td>
201
</td>
<td>
102
</td>
<td>
1.507463
</td>
</tr>
<tr>
<td>
2
</td>
<td>
102
</td>
<td>
202
</td>
<td>
104
</td>
<td>
2.514851
</td>
</tr>
<tr>
<td>
3
</td>
<td>
103
</td>
<td>
203
</td>
<td>
106
</td>
<td>
3.522167
</td>
</tr>
<tr>
<td>
4
</td>
<td>
104
</td>
<td>
204
</td>
<td>
108
</td>
<td>
4.529412
</td>
</tr>
</tbody>
</table>
</div>

**Comment by stinodego** [comment]
This was implemented in https://github.com/pola-rs/polars/pull/10874
