### ISSUE TITLE
unable to collect from deserialized lazyframes

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#3877]
| Description    | Value                                                                                                       |
| -------------- | ----------------------------------------------------------------------------------------------------------- |
| Runtime        | python 3.7.3, node 18+|
| Polars version |  0.13.51 |
| OS             |Ubuntu 20.04.2 LTS |

#### Have you tried latest version of polars?

- [yes]

#### Describe your bug.
unable to round trip from lf -> json -> lf, then perform a collect. 
This is present in py & js, and likely rust. 
I was trying to reproduce the issue in rust when i ran into issue #3875 

#### What are the steps to reproduce the behavior?

**Python** 
```py
import polars as pl

lf_original = pl.scan_csv('/path/to/file.csv')
json = lf_original.write_json(to_string=True)
lf = pl.LazyFrame.from_json(json)
print(lf_original.collect()) # this works
print(lf.collect()) # this does not
```
**Node.js**
```js
const lfOriginal = pl.scanCSV("/path/to/file.csv");
const json = lfOriginal.serialize("json");
const lf = pl.LazyDataFrame.deserialize(json, "json");
console.log(lfOriginal.collectSync()); // success
console.log(lf.collectSync()); // error
```
#### What is the actual behavior?

errors out at `lf.collect()`

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /github/workspace/polars/polars-lazy/src/physical_plan/file_cache.rs:43:55
```

#### What is the expected behavior?
```py
assert lf.collect().frameEquals(lf_original.collect())
```
This worked on older versions & seems to be directly related to the new file cache logic.

**Comment by universalmind303** [comment]
so on further investigation, it seems to be a result of how the optimization state is initialized when deserializing. 

lazyframe will use the default opt_state for file_caching

```
            // will be toggled by a scan operation such as csv scan or parquet scan
            file_caching: false,
```
so even if it was previously set via a `scan*` operation, it is lost during serialization. 

So we could either add in some logic to detect this from the nodes, or we can serialize the state as well.

**Comment by universalmind303** [comment]
I have tested & confirmed that serializing the entire `LazyFrame` instead of just `LogicalPlan` works as expected.

**Comment by universalmind303** [comment]
@ritchie46, some more discovery shows this isn't limited to serde. You can't use `LazyFrame::from` at all without manually setting the `file_cache` state. 

I would expect `LazyFrame::from` to return a collectable Lazyframe if I have a valid LogicalPlan. It shouldn't be able produce a lazyframe that can not be collected.

### Steps to reproduce
```rust
let lf = LazyCsvReader::new(path).finish();
let lp = lf.logical_plan;
let lf_from_lp = LazyFrame::from(lp);

// panicked at 'called `Option::unwrap()  /polars/polars-lazy/src/physical_plan/file_cache.rs:43:55
let df = lf_from_lp.collect()?; 
```

**Comment by ritchie46** [comment]
Check. I think it makes sense to turn the optimization on in the `From` implementation then. 

Can you make a PR for that one?

**Comment by odedroze** [comment]
so how can I fix this bug ???
