### ISSUE TITLE
hypothesis driven test to separate module

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#3880]
The hypothesis tests can really increase testing time.

This is good as it tests all edge cases, but in my workflow I'd like to have tests that are quick and test for the hand written things we have defined and more thorough tests ran in CI or just before committing.

**Comment by alexander-beedie** [comment]
Makes sense - they are doing 100x more work than a typical test  :)  

Got a preferred parallel module name in mind? I can prep a PR moving them into a dedicated spot - maybe something like `tests_hypothesis` (very clear), or `tests_ci` (functional, but perhaps not as obvious), for instance?

**Comment by cnpryer** [comment]
wb `test_edge`

**Comment by alexander-beedie** [comment]
> wb `test_edge`

Maybe; however, that makes it sound like it's _only_ about edge-cases; really, it's about getting much better coverage in general, a side-effect of which happens to be the increased likelihood of finding edge-cases  ;)

**Comment by cnpryer** [comment]
test_more

**Comment by alexander-beedie** [comment]
> test_more

A good philosophy in general... ;)
`tests_extra` ?

**Comment by cnpryer** [comment]
Either way I like the idea of opting in. Especially in CI :)

**Comment by alexander-beedie** [comment]
Done. Also, Makefile tweaked accordingly -

* `make test`: runs ONLY the quick tests (so this stays fast).
* `make test-all`: runs quick tests AND parametric tests (new option; thorough).
* `make test-with-cov`: runs quick AND parametric AND combines coverage (this runs for CI).
