### ISSUE TITLE
Add support to load a specific collection of files

### ISSUE THREAD

**Issue by andrei-ionescu** [pola-rs/polars#3893]
#### Describe your feature request

It would be great to have the possibility to load a collection of files.

```
let files = vec![
    "f1.parquet".to_string(), 
    "f2.parquet".to_string(),
];
let df = LazyFrame::scan_parquet_files(files, ScanArgsParquet::default())
    .select([all()])
    .collect()
...
```

This will help in the following use cases:
- Loading a subset of files from a folder with lots of parquet files. This subset can be a result of a pre-filtering (ie: file skipping, mechanisms, indexes, bloom filters, etc.) and by having this API it will leverage loading less files.
- Support for complex table formats like Iceberg, Delta and Audi which can offer file list based on input predicates.

**Comment by ritchie46** [comment]
We already support this with globbing. E.g.

```rust
LazyFrame::scan_parquet("my_dir/*.parquet)`
```

**Comment by andrei-ionescu** [comment]
@ritchie46 I know that there is the wildcard glob functionality but my PR is addressing another use case. Is for the case where you have `dir/f1.parquet, dir/f2.parquet, dir/f3.parquet, ..., dir/f1000.parquet` but because of a pre-filtering process you need to load only a specific list like: `dir/f2.parquet, dir/f13.parquet, dir/f57.parquet`.

As I said, this smaller list can be a result of a pre-filtering mechanism. Some good examples are Iceberg, Delta Lake and Hudi. All of them have metadata that can lead to to specific files that you need to load.

**Comment by andrei-ionescu** [comment]
@ritchie46 I added a test for the newly added method. Could you let the git workflows run once more to see how we stand? Thank you!

**Comment by sm-Fifteen** [comment]
#3894 only implements this in Rust, and only for Parquet files. I'm facing a similar issue with CSV files (a few thousands of timestamped file names generated every hour, where most of them can be skipped based on time range) and globs are insufficent to apply this file-based filter.

**Comment by ritchie46** [comment]
> #3894 only implements this in Rust, and only for Parquet files. I'm facing a similar issue with CSV files (a few thousands of timestamped file names generated every hour, where most of them can be skipped based on time range) and globs are insufficent to apply this file-based filter.

Write a loop and concatenate the final list.

The function above is deprecated for the same reason. This is something that perfectly can be done in the host language.

**Comment by sm-Fifteen** [comment]
> Write a loop and concatenate the final list.
> 
> The function above is deprecated for the same reason. This is something that perfectly can be done in the host language.

https://github.com/pola-rs/polars/blob/798882dec21c6311c6e35a54349b26f302d59f5c/polars/polars-lazy/src/frame/parquet.rs#L77-L78

Ah, I see. I didn't realize the function was deprecated and [the User Guide](https://pola-rs.github.io/polars-book/user-guide/multiple_files/intro.html) didn't mention how this was basically equivalent.
