### ISSUE TITLE
Header with leading space is not stripped when reading from CSV.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#3903]
#### What language are you using?

**Python**.

#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?
0.13.51

#### What operating system are you using polars on?
CentOs 7

#### What language version are you using
python 3.10

#### Describe your bug.

Give a high level description of the bug.
Header with leading space is not stripped when reading from CSV.

#### What are the steps to reproduce the behavior?

```python
import io

csv = """
    a,b,c
    1,2,3
    1,2,3
    """

f = io.StringIO(csv)
df = pl.read_csv(f)

In [22]: df.columns
Out[22]: ['    a', 'b', 'c']
```

#### What is the expected behavior?

Not sure if this should necessary be supported.
But at least tests in `py-polars/tests/io/test_csv.py` contain this kind of CSV files (and make it impossible to select column "a" without the leading spaces.

**Comment by thatlittleboy** [comment]
> But at least tests in py-polars/tests/io/test_csv.py contain this kind of CSV files (and make it impossible to select column "a" without the leading spaces.

Just to chime in on the canonical way to deal with this problem, is to use [`textwrap.dedent` from the stdlib](https://docs.python.org/3/library/textwrap.html#textwrap.dedent).

```python
import polars as pl
import io
import textwrap

csv = textwrap.dedent(
    """\
    a,b,c
    1,2,3
    1,2,3
    """
)
df = pl.read_csv(io.StringIO(csv))
print(df.columns)
df
```
gives
```python
['a', 'b', 'c']
shape: (2, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 2   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 2   ┆ 3   │
└─────┴─────┴─────┘
```

**Comment by ghuls** [comment]
Dedent is now used in the csv tests.
