### ISSUE TITLE
Appending `Series` to itself results in "Already mutably borrowed" error

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#3915]
#### What language/platform are you using?

Python 3.9, Polars 0.13.51. macOS 12.4

#### Describe your bug.

Appending a Series to itself results in a RuntimeError.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
s = pl.Series("s",[1,2,3])
s.append(s)

# RuntimeError: Already mutably borrowed
```

#### What is the expected behavior?

Successful append of the data, equivalent to `s.append(s.clone())`.

**Comment by ritchie46** [comment]
I think we should wrap this into a `try, catch`. If we fail on `Already mutably borrowed` we can instead call `s.append(s.clone())`.
