### ISSUE TITLE
Request for `pl.factorize` method

### ISSUE THREAD

**Issue by tianfudhe** [pola-rs/polars#3922]
Pandas provides a Series method `pd.factorize` that encode the object series to a series of numbers, which is useful when the only thing we care is to distinguish the objects, such as assigning the categorical labels in machine learning scenarios. `pd.factorize` runs like:
```python3
>>> codes, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'])
>>> codes
array([0, 0, 1, 2, 0]...)
>>> uniques
array(['b', 'a', 'c'], dtype=object)
```
Note that it generates integer encodings, differnet from the current `pl.get_dummies` which provides one-hot encodings.
Is is possible/appropriate to implement this method in polars?

Full pandas API is in this page: https://pandas.pydata.org/docs/reference/api/pandas.factorize.html

**Comment by ritchie46** [comment]
Try this:

```python
>>> s = pl.Series("values", ["a", "b", "c"])
>>> s.cast(pl.Categorical).to_physical()
```
```
shape: (3,)
Series: 'values' [u32]
[
	0
	1
	2
]
```

**Comment by tianfudhe** [comment]
> Try this:
> 
> ```python
> >>> s = pl.Series("values", ["a", "b", "c"])
> >>> s.cast(pl.Categorical).to_physical()
> ```
> 
> ```
> shape: (3,)
> Series: 'values' [u32]
> [
> 	0
> 	1
> 	2
> ]
> ```

Thanks! It works very well

**Comment by Wainberg** [comment]
This works if you don't mind the codes being ordered based on the sorted order of the original values, instead of the order of first appearance:

```python
>>> pl.Series(['b', 'b', 'a', 'c', 'b']).rank('dense')
shape: (5,)
Series: '' [u32]
[
        2
        2
        1
        3
        2
]
```
