### ISSUE TITLE
python: print nested datatypes.

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#3925]
I really like the printSchema() function in PySpark as it massively simplifies working with (large) tables:
![grafik](https://user-images.githubusercontent.com/1200058/177741475-1f4be76b-b987-4b06-b507-bff9328091a4.png)
Having this function in polars as well would aid its usage comfort :)

**Comment by ritchie46** [comment]
Something like this?:

```python
from pprint import pprint

pprint(df.schema)
```
```
{'dropoff_datetime': <class 'polars.datatypes.Utf8'>,
 'dropoff_latitude': <class 'polars.datatypes.Float64'>,
 'dropoff_longitude': <class 'polars.datatypes.Float64'>,
 'fare_amount': <class 'polars.datatypes.Float64'>,
 'mta_tax': <class 'polars.datatypes.Float64'>,
 'passenger_count': <class 'polars.datatypes.Int64'>,
 'payment_type': <class 'polars.datatypes.Utf8'>,
 'pickup_datetime': <class 'polars.datatypes.Utf8'>,
 'pickup_latitude': <class 'polars.datatypes.Float64'>,
 'pickup_longitude': <class 'polars.datatypes.Float64'>,
 'rate_code': <class 'polars.datatypes.Int64'>,
 'store_and_fwd_flag': <class 'polars.datatypes.Int64'>,
 'surcharge': <class 'polars.datatypes.Float64'>,
 'tip_amount': <class 'polars.datatypes.Float64'>,
 'tolls_amount': <class 'polars.datatypes.Float64'>,
 'total_amount': <class 'polars.datatypes.Float64'>,
 'trip_distance': <class 'polars.datatypes.Float64'>,
 'vendor_id': <class 'polars.datatypes.Utf8'>}

```

**Comment by Hoeze** [comment]
Yes, but the difference is that this one does not show nested structures:
![grafik](https://user-images.githubusercontent.com/1200058/177745037-47f7e593-eb16-4c1a-98b5-4efd71be8355.png)

**Comment by ghuls** [comment]
> Right, so we should improve the print of our nested structures!

The doctest that I fixed recently had the name of the fields for struts in the old output. So it seems that at least for struts it was once implemented.

**Comment by mslapek** [comment]
I think this issue can be **closed**.

<br/>

When we run `df.schema` on recent polars, we get a description of the struct fields:

```python
{'name': Utf8, 'car': Struct([Field('color', Utf8), Field('year', Int64)])}
```

(It was noticed by @phillyphil91 in https://github.com/pola-rs/polars/pull/4213#issuecomment-1367542011)
