### ISSUE TITLE
truncating long strings

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#3928]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

polars: 0.13.51

#### What operating system are you using polars on?

Windows10

#### What language version are you using
python 3.10.5

#### Describe your bug.

dataframe truncates string columns

#### What are the steps to reproduce the behavior?

I

```
import polars as pl
import string

f"polars: {pl.__version__}"

letters = [string.ascii_lowercase]*3
sr = pl.Series('series', letters)
df = pl.DataFrame({'dataframe': letters})


df

print(df)
```

**Comment by ritchie46** [comment]
It is configurable now. See #3911
