### ISSUE TITLE
Allow arbitrary column expressions in JOIN ON clause

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#3935]
### Arbitrary column expressions

Typically in SQL one can express JOINs on arbitrary expressions. In polar's case, the JOIN must be an equality:

```
lf1.join(lf2, how="left", left_on=lf1.col("x"), right_on=lf2.col("y"))
```

is implicitly equivalent to:

```
SELECT * FROM lf1 LEFT JOIN lf2 ON lf1.x = lf2.y
```

There are two things (with varying degrees of difficulty to implement) which polars cannot currently do:

### Allow arbitrary expressions on the LHS/RHS of the equality

```
SELECT * FROM lf1 LEFT JOIN lf2 ON lf1.x = lf2.y / 2
```

If we have lazy frames with the following content:

```
tbl1.fetch(n_rows=2)

x | y
-- | --
i64 | str
1 | "a"
2 | "b"
```

and:

```
tbl2.fetch(n_rows=2)

w | z
-- | --
i64 | str
2 | "c"
4 | "d"
```

and we try to join:

```
tbl1.join(tbl2, how="left", left_on=pl.col("x"), right_on=(pl.col("w") // 2)).fetch(n_rows=2)

x | y | z
-- | -- | --
i64 | str | str
1 | "a" | null
2 | "b" | "c"
```

it raises a `PanicException: could not determine join column names`. If I were to _alias_ the second one the result is even worse (this should be considered a bug):

```
tbl1.join(tbl2, how="left", left_on=pl.col("x"), right_on=(pl.col("w") // 2).alias("w")).fetch(n_rows=2)

x | y | z
-- | -- | --
i64 | str | str
1 | "a" | null
2 | "b" | "c"
```

Here it seems like polars interpreted that expression as the field from the table! Uh oh. We expect `z == ["c", "d"]` not `[null, "c"]` along the column.

### Allow arbitrary predicate functions for `on`

JOINs can get complicated:

```
SELECT * FROM lf1 LEFT JOIN lf2 ON lf1.x <= lf2.y AND lf2.x >= lf2.z
```

I don't think these non-equality predicate expressions can currently be expressed by `pl.LazyFrame.join`. AFAICT this can't be captured by `join_asof` either. I would like the ability to say something like:

```
tbl1.join(tbl2, how="left", on=(pl.col("x").bind(tbl1) <= pl.col("y").bind(tbl2)) & (pl.col("x").bind(tbl1) >= pl.col("z").bind(tbl2)))
```

to mean the same thing as the above SQL expression. Let me know what you think.

PS: Sorry for the barrage of tickets! I think polars is awesome and I'm currently scoping it out to see whether it fits my use case :)

**Comment by universalmind303** [comment]
closed via #4029

**Comment by bfeif** [comment]
I agree, @Bonnevie . Not sure why this issue was closed, just enabling joins by `pl.Expr` objects doesn't really fix the problem

**Comment by solomonpapathoti** [comment]
Hi, so can I do this?
```python
tbl1.join(tbl2, how="inner", left_on=[pl.col("art_no"), pl.col("var_tu_key") // 1000], right_on=[(pl.col("art_no"), pl.col("var_no")])
```

for 

```sql
SELECT * 
FROM lf1 AS il
INNER JOIN lf2 AS pdim
ON il.art_no = pdim.art_no
    AND DIV(il.var_tu_key, 1000) = pdim.var_no
```

Is there any feature added now?
