### ISSUE TITLE
Explode chained to groupby raises error

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#3950]
#### What language are you using?

Python

#### Have you tried latest version of polars?
yes

#### What version of polars are you using?

master

#### What operating system are you using polars on?

Mac OS 12.4

#### What language version are you using
Python 3.10

#### Describe your bug.

I was writing an expression to get the difference between rows of a column after a groupby operation, but was surprised to find that I could not explode() directly within the groupby. Is this intentional?

```python
df = pl.DataFrame(
    {
        "a": ["a", "b", "a", "b", "b", "c"],
        "b": [1, 2, 3, 4, 5, 6],
        "c": [6.0, 5.0, 4.0, 3.0, 2.0, 1.0],
    }
)

# works
(
    df
    .groupby("a")
    .agg(pl.col("b").diff())
    .explode("b") # explode chained to df
)

# doesn't work
(
    df
    .groupby("a")
    .agg(
        (pl.col("b").diff())
        .explode()) # explode chained to groupby series
)
# ValueError: explode not supported for Series with dtype Int64
# (same targetting "c", which is Float64)
```

**Comment by ritchie46** [comment]
That's not a bug. Your group values are a `Series` type `Int64. Those cannot be exploded. Try the `inspect` expression to print the group values and you might better understand why.

After the aggregation it's type is `List<Int64>` which can be exploded.

**Comment by thomasaarholt** [comment]
Oh man, _it's right there in the error message_ 🤦 

Thanks!
