### ISSUE TITLE
PanicException: 'groups are slices not index' in unique on sorted categorical column

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#3958]
PanicException: 'groups are slices not index' in unique on sorted categorical column

polars==0.13.50

```python
import polars as pl

df = pl.DataFrame([
    pl.Series("a", ["a", "a", "b", "c"]),
]).with_column(
    col.a.cast(pl.Categorical)
).sort("a").unique(subset = ["a"])
df
```

    thread '<unnamed>' panicked at 'groups are slices not index', /github/workspace/polars/polars-core/src/frame/groupby/proxy.rs:

    ---------------------------------------------------------------------------

    PanicException                            Traceback (most recent call last)

    /tmp/ipykernel_348425/2699434389.py in <cell line: 3>()
          1 import polars as pl
          2 
    ----> 3 df = pl.DataFrame([
          4     pl.Series("a", ["a", "a", "b", "c"]),
          5 ]).with_column(

    ~/src/genome/kd/env/lib/python3.10/site-packages/polars/internals/frame.py in unique(self, maintain_order, subset, keep)
       5196         if subset is not None and not isinstance(subset, list):
       5197             subset = [subset]
    -> 5198         return self._from_pydf(self._df.unique(maintain_order, subset, keep))
       5199 
       5200     def rechunk(self: DF) -> DF:

    PanicException: groups are slices not index

    277:42

**Comment by ritchie46** [comment]
Please fill in the form. Have you tried updating?

**Comment by kdcd** [comment]
Big apologies for the disturbance. In polars-0.13.52 everything is working.

**Comment by ritchie46** [comment]
No worries. :)
