### ISSUE TITLE
Datetime[ns] to date comparison is incorrect

### ISSUE THREAD

**Issue by david-cortes** [pola-rs/polars#3965]
If I compare a timestamp against a date with `<=` operator, the results are incorrect:
```python
import pandas as pd, polars as pl
df = pd.DataFrame({
    "cl" : pd.to_datetime(["2020-06-07", "2020-06-08", "2020-06-08 10:00:00"])
})
(
    pl
    .DataFrame(df)
    .with_columns([
        pl.col("cl").dt.truncate("1d").alias("truncated"),
        (pl.col("cl").dt.truncate("1d") <= "2020-06-08").alias("is_leq")
    ])
)
```
<small style="color: rgb(212, 212, 212); font-family: system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (3, 3)</small>

cl | truncated | is_leq
-- | -- | --
datetime[ns] | datetime[ns] | bool
2020-06-07 00:00:00 | 2020-06-07 00:00:00 | true
2020-06-08 00:00:00 | 2020-06-08 00:00:00 | false
2020-06-08 10:00:00 | 2020-06-08 00:00:00 | false

**Comment by ritchie46** [comment]
You should compare with datetime/date objects. If you compare with a str, the date column will be coerced to Utf8 type and the comparison is likely not what you wanted.

**Comment by david-cortes** [comment]
This is contrary to what every other software does and extremely unintuitive.

* Pandas:
```python
df["cl"].dt.normalize() <= "2020-06-08"
```
```
0    True
1    True
2    True
Name: cl, dtype: bool
```

* R:
```r
as.POSIXct("2020-06-08 00:00:00") <= "2020-06-08"
```
```
[1] TRUE
```

* SQL:
```python
duckdb.query("select cl <= '2020-06-08' from df").to_df()
```
  | cl <= '2020-06-08'
-- | --
True
True
False

**Comment by ritchie46** [comment]
It is different true. But I'd argue that strings should not be used for date/datetime values if we have types for that. The type `string` is very ambiguous and therefore it must be explicit in polars.

I agree that we should make clear that you do something that is probably not intended. I think we should print a warning when we find these comparisons.
