### ISSUE TITLE
hash does not reproduce with same seed between sessions

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#3966]
#### What language are you using?
python

#### Have you tried latest version of polars?
yes

#### What version of polars are you using?

master

#### What operating system are you using polars on?

Mac OS 12.4

#### What language version are you using
python 3.10

#### Describe your bug.

The `seed` parameter to `pl.col().hash(seed = some_int)` led me to believe that a hash with the same seed on the same string should lead to reproducible results.

```python
# it does if you call it in the same session
>>> import polars as pl
>>> pl.DataFrame({"id": ["my_fair_lady"]}).with_column(pl.col("id").hash(seed=0))
shape: (1, 1)
┌──────────────────────┐
│ id                   │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 2073642609457554451 │
└──────────────────────┘
>>> pl.DataFrame({"id": ["my_fair_lady"]}).with_column(pl.col("id").hash(seed=0))
shape: (1, 1)
┌──────────────────────┐
│ id                   │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 2073642609457554451 │
└──────────────────────┘

# but if you restart the python kernel:
>>> import polars as pl
>>> pl.DataFrame({"id": ["my_fair_lady"]}).with_column(pl.col("id").hash(seed=0))
shape: (1, 1)
┌──────────────────────┐
│ id                   │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 16459767268729391334 │
└──────────────────────┘
```

I would have expected the hash to return the same result between restarts. If this is not the case, I would expect that to be mentioned in the docstring :)

**Comment by ritchie46** [comment]
Good catch. I did not realize this. Now that I think of this, I assume this is because of the dos resistant properties of [ahash](https://github.com/tkaitchuck/aHash). I shall see if we can circumvent this, or at the very least add it to the docs.

**Comment by thatlittleboy** [comment]
I think if we instantiate the ahash RandomState using [`with_seeds`](https://docs.rs/ahash/0.7.6/ahash/struct.RandomState.html#method.with_seeds) (as used by [`pl.Series.hash`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.hash.html)) instead of [`with_seed`](https://docs.rs/ahash/0.7.6/ahash/struct.RandomState.html#method.with_seed), it should persist across sessions (?).

At least it seems that way from my naive testing.

1. Same test as @thomasaarholt except with `pl.Series.hash`:
```python
>>> import polars as pl
>>> pl.Series("s", [1234, None, 5678]).hash(42, 24, 16, 61)
```
```python
# session 1
shape: (3,)
Series: 's' [u64]
[
	8597439350682386722
	14461028103114354274
	16292620088676341138
]

# session 2
shape: (3,)
Series: 's' [u64]
[
	8597439350682386722
	14461028103114354274
	16292620088676341138
]
```
i.e., got same result in different sessions. (quit and restarted ipython session)

2. In rust, using `ahash`
```rust
use std::hash::{Hasher, BuildHasher};

fn main() {
    let rs1 = ahash::RandomState::with_seeds(42, 24, 16, 61);
    let mut hasher_1 = rs1.build_hasher();
    let rs2 = ahash::RandomState::with_seed(42);
    let mut hasher_2 = rs2.build_hasher();

    hasher_1.write_u32(1234);
    println!("Using with_seeds: {}", hasher_1.finish());
    hasher_2.write_u32(1234);
    println!("Using with_seed: {}", hasher_2.finish());
}

```
output with `cargo run`
```
# session 1
Using with_seeds: 9402648887230950237
Using with_seed: 16390682336103744129

# session 2
Using with_seeds: 9402648887230950237
Using with_seed: 15458084876942061712
```

---

FWIW, I'ld also prefer if both polars hashes (expr and Series) are deterministic (up to the seed set by the user) as far as possible.

**Comment by thomasaarholt** [comment]
@thatlittleboy I'd very much enjoy it if you could make a PR with your solution :)

**Comment by thatlittleboy** [comment]
Yea, I think it should be a relatively straightforward fix if we intend to go down the route of unifying the APIs. (using `with_seeds` for all the hash functions in polars).

I'm just curious if there was any special reason for choosing to use one way or the other for the respective Expr/DataFrame/Series hash functions.
