### ISSUE TITLE
join panics in certain lazy cases

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#3979]
#### What language are you using?
Python

#### Have you tried latest version of polars?
yes

#### What version of polars are you using?

master as of three days ago

#### What operating system are you using polars on?
Mac OS

#### What language version are you using
Python 3.10

#### Describe your bug.
After #3977 I swapped the order of the cross join in my own code. When running eagerly, it's much faster. Ran lazily, it panics! 
EDIT: It also crashes with all other join types, see below:

I've really struggled to debug this, since I can only make it crash on a LazyFrame scanned from a parquet file. Creating the LazyFrame out of a manually copied DataFrame runs fine. 

Hence it is possibly related to the parquet lazy reader (`pl.scan_parquet`).

Attached is a one-entry parquet file, containing a single UTF-8 string. Column title is "customer_ID" because it stems from a kaggle dataset: [bug.parquet.zip](https://github.com/pola-rs/polars/files/9083263/bug.parquet.zip)

The following code panics when I reverse the order of the cross join:

```python
import polars as pl
a = pl.scan_parquet("bug.parquet")
b = pl.DataFrame({"a":[1]}).lazy()

a.join(b, how="cross").collect() # works
b.join(a, how="cross").collect() # panics
```

However, if I add `.collect().lazy()` on `a` before joining, it doesn't panic:

```python
a = pl.scan_parquet("bug.parquet")
b = pl.DataFrame({"a":[1]}).lazy()

a.join(b, how="cross").collect() # works
b.join(a.collect().lazy(), how="cross").collect() # also now works
```

Constructing the same frame manually also runs fine:

```python
a = pl.DataFrame({"customer_ID":["0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a"]}).lazy()
b = pl.DataFrame({"a":[1]}).lazy()

a.join(b, how="cross").collect() # works
b.join(a, how="cross").collect() # also now works
```

### Also crashes with other join types:

```python
a = pl.scan_parquet("bug.parquet")
b = pl.DataFrame({"a":[1], "customer_ID":["abc"]}).lazy()

a = pl.scan_parquet("bug.parquet")
b = pl.DataFrame({"a":[1], "customer_ID":["abc"]}).lazy()

a.join(b, how="left", on="customer_ID").collect() # runs fine
a.join(b, how="inner", on="customer_ID").collect() # runs fine
a.join(b, how="outer", on="customer_ID").collect() # runs fine

b.join(a, how="left", on="customer_ID").collect() # panic
b.join(a, how="inner", on="customer_ID").collect() # panic
b.join(a, how="outer", on="customer_ID").collect() # panic
```

**Comment by ritchie46** [comment]
Thanks, found the culprit.
