### ISSUE TITLE
Add way to skip calculating expression if the column already exists

### ISSUE THREAD

**Issue by vultix** [pola-rs/polars#3990]
#### Describe your feature request
First off, thank you for this wonderful library!

It would be great if we could create an expression that represented the idea "If this column already exists, use it, otherwise calculate it."  My use case is to prevent re-calculating expensive columns if they already exist.

#### Example
Here's a simple example.  Say that you are calculating the simple moving average on a few stock price columns:

```python
simple_moving_avg = pl.col(["open", "close", "high", "low"]).rolling_mean(100).suffix("_sma")
```

Each of these columns, such as `open_sma`, may have already been calculated.  I'd like some mechanism to tell polars to use the existing columns if they already exist, only calculating them if they don't.

Potentially:
```python
dataframe.select(simpl_moving_avg.if_not_exists())
```

**Comment by mutecamel** [comment]
Following code could simply work it out, though in a pythonic way, not polars-expression way

```python
for c in ["open", "close", "high", "low"]:
    if (c1 := f"{c}_sma") not in df.columns:
        df = df.with_column(pl.col(c).rolling_mean(100).suffix(c1))
```

This works both for `DataFrame` and `LazyFrame`.

**Comment by cbilot** [comment]
Building on @mutecamel solution ..

Since calling `with_columns` with an empty list (`df.with_columns([])`) is a no-op, you can generate the list inside the `with_columns` and also achieve parallel execution.
```python3
ohlc_col_nms = ['open', 'high', 'low', 'close']
df = (
    df
    .with_columns(
        [pl.col(col_nm).rolling_mean(100).suffix("_sma")
         for col_nm in ohlc_col_nms
         if col_nm + '_sma' not in df.columns]
    )
)
```
If the list comprehension returns an empty list, the `with_columns` does nothing.

**Comment by ritchie46** [comment]
I will close this as this is something that should be done by the callee and is not a responsibility of polars IMO. I assume that the examples given by @mutecamel  and @cbilot are sufficiently helpful. If not, feel free to make a SO question and post the link here, we are happy to help further.
