### ISSUE TITLE
Allow using `.exclude` with `pl.col(datatype)` 

### ISSUE THREAD

**Issue by cccs31** [pola-rs/polars#3991]
#### Describe your feature request

`.exclude` currently only works with a wildcard/regex selection. It would also be nice if `.exclude` could be used when selecting columns by datatype. For example:

```py
# current behavior:
df.with_column(
    pl.col(pl.Utf8).exclude('name')
)
# PanicException: no exclude expected at this point
```

**Comment by ritchie46** [comment]
I agree, we should make that work.
