### ISSUE TITLE
top k for max() and min() aggregations

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#3997]
#### Describe your feature request

It would be nice to have a function like `pl.Expr.max` that allows top k results to be returned:

```
# Returns top 10 elements as a single array of length 10.
pl.col("x").max(num_elements=10)
```

Similarly for `pl.Expr.min`. I'm impartial to the above API, perhaps it should be `pl.Expr.top_k()` and `pl.Expr.bottom_k()` or something else completely

**Comment by ritchie46** [comment]
Thanks for the request. I will close this one and refer to #3767
