### ISSUE TITLE
Support for nulls_last on arbitrary pl.Expr in LazyFrame sort

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#3998]
#### Describe your feature request

As documented [here](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.sort.html), the `nulls_last` behavior can only be used when sorting on a specific column. Would it be prohibitively difficult to add support for `nulls_last` on arbitrary expressions in the lazyframe?

```
# Expectedly errors, with: `ValueError: nulls_last can only be combined with 'by' argument of type str`
pl.DataFrame({"x": [1, 2, None], "y": ["a", "b", "c"]}).lazy().sort(pl.col("x") * 2, nulls_last=True)
```

I would really like this feature because I'm building a SQL query layer over polars and the dialect it supports (Trino SQL) [says](https://trino.io/docs/current/sql/select.html#order-by-clause):

> The default null ordering is NULLS LAST, regardless of the ordering direction.

Which unfortunately doesn't work with pola.rs. For other SQL dialects I've seen default null ordering dependent on whether the orderby is ASC or DESC (first and last respectively), and in general it would be nice to control for this behavior.

**Comment by ritchie46** [comment]
We already have this functionality. It seems it is not exposed to python yet. I shall add it.

**Comment by ritchie46** [comment]
> I would really like this feature because I'm building a SQL query layer over polars and the dialect it supports (Trino SQL) 

That's very cool btw. Is that work open source?

**Comment by OneRaynyDay** [comment]
I plan for it to be. I currently have a(n almost) full trino SQL compliant parser for querying [here](https://github.com/OneRaynyDay/treeno). I would simply build over the visitor pattern here on `pl.LazyFrame` and `pl.Expr`s to make the query engine layer :) I can discuss more of it in detail with you over Discord if you'd like

**Comment by ritchie46** [comment]
> As documented [here](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.sort.html), the nulls_last behavior can only be used when sorting on a specific column. Would it be prohibitively difficult to add support for nulls_last on arbitrary expressions in the lazyframe?

Sorry, I read wrong. This should already work I believe. We only don't support multiple columns combined with nulls last.

**Comment by OneRaynyDay** [comment]
Oh I see - should I build polars from source and try the same `.sort()` command above? IIRC I'm using the latest polars release:

```
>>> import polars as pl
>>> pl.__version__
'0.13.51'
>>> pl.DataFrame({"x": [1, 2, None], "y": ["a", "b", "c"]}).lazy().sort(pl.col("x") * 2, nulls_last=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rzhang/anaconda/envs/treeno/lib/python3.9/site-packages/polars/internals/lazy_frame.py", line 555, in sort
    raise ValueError(
ValueError: nulls_last can only be combined with 'by' argument of type str
```

Here, I believe the expression only involves 1 column but is a `pl.Expr`, not a `str` type denoting the name of the column, and that's what the `ValueError` was complaining about :(

**Comment by ritchie46** [comment]
I see. I think we should be able to allow that for an expression as well. I shall take a look.
