### ISSUE TITLE
Datetime unique is 10x slower than sort and filter

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#3999]
Datetime unique is 10x slower than sort and filter

```python
from datetime import datetime
import polars as pl
s = pl.date_range(datetime(1985, 1, 1), datetime(2015, 7, 1), "30s").shuffle()
```

```python
%%timeit
r = s.sort().rename("datetime").to_frame().filter(pl.col("datetime") != pl.col("datetime").shift(1))
```

    335 ms ± 3.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```python
%%time
r = s.unique()
```

    CPU times: user 3.27 s, sys: 229 ms, total: 3.5 s
    Wall time: 3.48 s

**Comment by ritchie46** [comment]
I think you should compare this with a case where you have many duplicates. Let's say you only have 4 unique values on millions of rows.

**Comment by ritchie46** [comment]
The sort is also parallel, whereas the unique is not. I have to think if that is wanted. As it can interfere with other expressions that run and is not embarassingly parallel if we parallelize it).

**Comment by kdcd** [comment]
It's very crude but something like this. Performance start to diverge 2x on 10 000 unique values in 10 000 000 array

```python
from datetime import datetime, timedelta
import random 
import time
import polars as pl
from tqdm import tqdm

rows = []
for unique_values in tqdm([10, 100, 1000, 10000, 100000]):
    df = pl.Series([datetime(2015, 7, 1) + timedelta(days = random.randint(1, unique_values)) for i in range(10000000)]).rename("datetime").to_frame()
    row = {"unique_values": unique_values}
    
    b = time.time()
    df.sort("datetime").filter(pl.col("datetime") != pl.col("datetime").shift(1))
    row["sort_filter"] = time.time() - b
    
    b = time.time()
    df.datetime.unique()
    row["unique"] = time.time() - b
    
    rows.append(row)
pl.DataFrame(rows)
```



<div>

<table border="1" class="dataframe" >
<small>shape: (5, 3)</small>
<thead>
<tr>
<th>
unique_values
</th>
<th>
sort_filter
</th>
<th>
unique
</th>
</tr>
<tr>
<td>
i64
</td>
<td>
f64
</td>
<td>
f64
</td>
</tr>
</thead>
<tbody>
<tr>
<td>
10
</td>
<td>
0.0955
</td>
<td>
0.079364
</td>
</tr>
<tr>
<td>
100
</td>
<td>
0.110074
</td>
<td>
0.085423
</td>
</tr>
<tr>
<td>
1000
</td>
<td>
0.112409
</td>
<td>
0.111864
</td>
</tr>
<tr>
<td>
10000
</td>
<td>
0.107944
</td>
<td>
0.212399
</td>
</tr>
<tr>
<td>
100000
</td>
<td>
0.118542
</td>
<td>
0.586735
</td>
</tr>
</tbody>
</table>
</div>

**Comment by ritchie46** [comment]
Thanks for the timings. I will think about this one.
