### ISSUE TITLE
Explode of List of Struct may lead to wrong result

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#4003]
Python3.10 Ubuntu 22.04 
polars latest 0.13.52

#### Describe your bug.

When using df.explode() on series with List of Struct with empty values, other series are incorrect.

#### What are the steps to reproduce the behavior?
```python
import polars as pl
df = pl.DataFrame([
    {'id': 6659480058, 'nested': []},
    {'id': 6659468000, 'nested': [{'_id': 21314, 'level': 1}]},
    {'id': 6659474359, 'nested': [{'_id': 0, 'level': 0}]},
])
df.explode('nested')
```

#### What is the actual behavior?

id | nested
-- | --
i64 | struct[2]
6659480058 | {null,null}
6659468000 | {21314,1}
**6659468000** | {0,0}

#### What is the expected behavior?

id | nested
-- | --
i64 | struct[2]
6659480058 | {null,null}
6659468000 | {21314,1}
**6659474359** | {0,0}

**Comment by s-b90** [comment]
Seems that in 0.13.46 all works as expected.

**Comment by ritchie46** [comment]
It is not related to struct. 

```python
df = pl.DataFrame([
    {'id': 1, 'nested': []},
    {'id': 2, 'nested': [1]},
    {'id': 3, 'nested': [2]},
])
df.explode('nested')
```

```
shape: (3, 2)
┌─────┬────────┐
│ id  ┆ nested │
│ --- ┆ ---    │
│ i64 ┆ i64    │
╞═════╪════════╡
│ 1   ┆ null   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ 1      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2      │
└─────┴────────┘

```
