### ISSUE TITLE
pl.read_sql with postgresql raises 'not implemented' exception

### ISSUE THREAD

**Issue by valxv** [pola-rs/polars#4009]
```python
import polars as pl

df = pl.read_sql(
    "SELECT * FROM variables", 
    "postgresql://postgres:password@localhost:5432/test")
```
Getting error:
```
thread '<unnamed>' panicked at 'not implemented', /__w/connector-x/connector-x/connectorx/src/destinations/arrow/arrow_assoc.rs:170:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/v/projects/ABB/ExtendedApps.AugmentedOperator.KnowledgeExtractor/src/search_api/services/polar_test.py", line 6, in <module>
    df = pl.read_sql("SELECT * FROM variables", "postgresql://postgres:password@localhost:5432/test")
  File "/home/v/projects/ABB/ExtendedApps.AugmentedOperator.KnowledgeExtractor/polars-test-env/lib/python3.8/site-packages/polars/io.py", line 935, in read_sql
    tbl = cx.read_sql(
  File "/home/v/projects/ABB/ExtendedApps.AugmentedOperator.KnowledgeExtractor/polars-test-env/lib/python3.8/site-packages/connectorx/__init__.py", line 257, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: not implemented
```

Ubuntu 20.04
Python 3.8.10
Packages:
```
Package           Version
----------------- -------
connectorx        0.3.0
numpy             1.23.1
pip               22.1.2
pkg_resources     0.0.0
polars            0.13.52
pyarrow           8.0.0
setuptools        44.0.0
typing_extensions 4.3.0
```
```

**Comment by valxv** [comment]
Using `connectorx` directly works:
```python
import connectorx as cx

cx.read_sql("postgresql://postgres:password@localhost:5432/test", "SELECT * FROM variables")
```

**Comment by ritchie46** [comment]
Probably not if you set the target to arrow. I assume the default target is pandas

**Comment by valxv** [comment]
@ritchie46 You're right! Will open an issue with them. Should I reference it here?

**Comment by jorgecarleitao** [comment]
@valxv , yes, and describe the schema of `variables` (so that we know what is missing ^^)

**Comment by ritchie46** [comment]
> @ritchie46 You're right! Will open an issue with them. Should I reference it here?

Please, then we can keep an eye out and maybe provide some help upstream.

**Comment by valxv** [comment]
I traversed through `connector-x` issues and looks like they have switched to `arrow2`. And setting up `return_type="arrow2"` works. I'm quite new to this topic and don't know if `arrow2` backward compatible, so does it make sense to ask them to support "older" `arrow` or we can just add `2` in `polars`? :blush:

**Comment by ritchie46** [comment]
That's great! A bit strange that they make the distinction in python as arrow is just a spec as for as we are concerned on the FFI side.

Anyhow, can you make a PR that updates our connector-x code?

**Comment by valxv** [comment]
@ritchie46 unfortunately, I'm not familiar with Rust yet 😊

**Comment by ritchie46** [comment]
This is all python. We use the `connector-x` library to read an arrow table and then convert that arrow table to polars with `pl.from_arrow`.

I could take in on as well, but the help would be great. :)

**Comment by valxv** [comment]
OK, will try. :)
