### ISSUE TITLE
Equivalent of SQL "SELECT AS"

### ISSUE THREAD

**Issue by dylanhmorris** [pola-rs/polars#4022]
It might be nice to have an equivalent of SQL's SELECT AS in the API (i.e. a way simultaneously to select column(s) and change column name(s)). 

As best I can tell, the most idiomatic way to do this is:

``df.rename({"foo": "bar"}).select(["bar", "baz"])``

I wonder whether it might be worth defining 

``df.select({"foo": "bar", "baz":"baz"})``

as an alias for the above

**Comment by universalmind303** [comment]
You can use the `alias` method to rename columns within the select. 

```py
df.select([
  pl.col("foo").alias("bar"), 
  pl.col("baz")
})
```

**Comment by ritchie46** [comment]
I will close this as we have this functionality
