### ISSUE TITLE
Misleading behavior using Python `in` operator

### ISSUE THREAD

**Issue by aidanalphafund** [pola-rs/polars#4032]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- [x] yes
- [ ] no

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.13.52

#### What operating system are you using polars on?

Mac OS

#### What language version are you using
python 3.8.12

#### Describe your bug.

Coming from pandas, I expected `"column" in df` to check if the column exists in the DataFrame.  When using polars, the response always seems to be `True`, and the behavior is undocumented.

#### What are the steps to reproduce the behavior?
**Example**

```python
import polars as pl
df = pl.DataFrame({
    "name": ["Jane", "John"],
    "age": [20, 30]
})
print("phone" in df) # True
```

#### What is the actual behavior?

The `value in df` line always returns `True` given any string or numeric `value`

#### What is the expected behavior?
There should be a well-documented behavior for this operator.  It could simply error out and tell the user to use `in df.columns` to check if a column exists. 
The current behavior is misleading, as I mistakenly thought the True response meant the behavior was similar to pandas.

**Comment by thatlittleboy** [comment]
@ritchie46 Can I take this? It should be a fairly simple fix, just need to add an explicit `__contains__` dunder method for `DataFrame` instead of relying on the fallback `__iter__` (which returns a list of Series, which are almost always truthy.)
