### ISSUE TITLE
Filter column by multiple values

### ISSUE THREAD

**Issue by IgorDenisenko** [pola-rs/polars#4042]
Hello.

How I can filter column by multiple values?
For example, pandas has:  
list_of_values = [1, ..., 10]
df[df.colname.isin(list_of_values)]

How I can do with  polars?
Thanks!

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)
