### ISSUE TITLE
LazyGroupBy.rank

### ISSUE THREAD

**Issue by pyjamafish** [pola-rs/polars#4066]
#### Describe your feature request
Polars `LazyGroupBy` should have a `rank` method that works similarly to [pandas.core.groupby.DataFrameGroupBy.rank](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.rank.html).

For consistency, it should have the same parameters as [polars.Expr.rank](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.rank.html).

**Comment by ritchie46** [comment]
We do have this feature. Maybe a stackoverflow question on how you translate some pandas code to polars would be a better fit?

**Comment by ritchie46** [comment]
I'd recommend reading the expression guide: https://pola-rs.github.io/polars-book/user-guide/dsl/intro.html

**Comment by pyjamafish** [comment]
Thanks! I had skimmed it when I first started, but reading again more thoroughly was helpful.

Would you say this translation of pandas to polars is accurate?
```python
# pandas
df["rank"] = (
    df.groupby(groups_list)
    [column_to_rank]
    .rank()
)
```
```python
# polars
lf = lf.with_column(
    pl.col(column_to_rank)
    .rank()
    .over(groups_list)
    .alias("rank")
)
```
