### ISSUE TITLE
Python equality operator == not as expected

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4069]
#### What language are you using?
Python

#### Have you tried latest version of polars?
yes

#### What version of polars are you using?
0.13.54

#### What operating system are you using polars on?
Mac

#### What language version are you using
Python 3.10

#### Describe your bug.
In Python, the equality operator `==` is used to check if two objects are the same, by some measure implemented via the `__eq__` method.
Lists check if the object is the same:
```python
[1,2,3] == [1,2,3] # True
[1,2,3] == [3,2,1] # False
```

Numpy arrays and pandas frames / series compare elementwise:
```python
import numpy as np, pandas as pd

np.array([1,2,3]) == np.array([1,2,4]) # array([ True,  True, False])

pd.DataFrame([1,2,3]) == pd.DataFrame([1,2,3])
#       0
# 0  True
# 1  True
# 2  True
```

In Polars, some variation of the first kind is currently implemented, although it seems to always return False:

```python
pl.DataFrame([1,2,3]) == pl.DataFrame([1,2,3]) # False
```

I would expect similar behaviour to numpy/pandas.

**Comment by stinodego** [comment]
Interestingly, there doesn't seem to be an `__eq__` implemented for `DataFrame`. Seems like something we should add?

When you comparing `Series`, you do get the expected result:

```
>>> s = pl.Series([1,2,3])
>>> s == s
shape: (3,)
Series: '' [bool]
[
        true
        true
        true
]
```

**Comment by ritchie46** [comment]
Yes, it should dispatch to `DataFrame.frame_equal(missing=True)`.

**Comment by stinodego** [comment]
Wouldn't it make more sense to handle this more like `Series` equality?

```
>>> df1 = pl.DataFrame({'a': [1, 2], 'b': [3,4]})
>>> df2 = pl.DataFrame({'b': [1, 2], 'c': [3,4]})
>>> df1 == df1
shape: (2, 2)
┌──────┬──────┐
│ a    ┆ b    │
│ ---  ┆ ---  │
│ bool ┆ bool │
╞══════╪══════╡
│ true ┆ true │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ true ┆ true │
└──────┴──────┘
>>> df1 == df2
SomeError: columns do not match
```

So first check for matching columns, then dispatch each column to `Series.__eq__`.

That would match the functionality requested, and also makes sense to me.
