### ISSUE TITLE
`value_counts` inconsistent results

### ISSUE THREAD

**Issue by M-Salti** [pola-rs/polars#4092]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.55

#### What operating system are you using polars on?

Windows 11 21H2 (22000.795)

#### What language version are you using

Python 3.9.7

#### Describe your bug.

The `value_counts` function returns inconsistent results when there are values with the same count

#### What are the steps to reproduce the behavior?

```python
import polars as pl

print(
    pl.DataFrame(data={"A": [1, 1, 1, 2, 2, 2]}).select(
        pl.col("A").value_counts()
    )
)
```

#### What is the actual behavior?

The above code will sometime give this output:

```
shape: (2, 1)
┌───────────┐
│ A         │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {1,3}     │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ {2,3}     │
└───────────┘
```

and sometimes this:

```
shape: (2, 1)
┌───────────┐
│ A         │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {2,3}     │
├╌╌╌╌╌╌╌╌╌╌╌┤
│ {1,3}     │
└───────────┘
```

seemingly at random.

#### What is the expected behavior?

It would be nice if the same result would be returned all the time by default.

**Comment by ritchie46** [comment]
That is not a bug. This is because we use hash tables to compute the unique values. Similar as in groupby. The counts given are correct for the values.

I do think we can add an argument `maintain_order` or `sort` that makes the output predictable when you need it.
