### ISSUE TITLE
pl.from_arrow takes very long

### ISSUE THREAD

**Issue by MichalChromcak** [pola-rs/polars#4093]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- yes (latest available from PyPI)

#### What version of polars are you using?

0.13.55

#### What operating system are you using polars on?

linux

#### What language version are you using
python 3.9

#### Describe your bug.

I am having very long time (haven't finished yet) of execution using `pl.from_arrow()` with pa.Table input and not sure if it is expected or I am doing something wrong.

##### Setup
```python
# imports
import polars as pl
import connectorx as cx
import os
from google.cloud import bigquery
```

##### Using `pl.from_arrow`
```python
query = """SELECT * FROM `table_i_cannot_provide_name_with`"""

job_config = bigquery.QueryJobConfig(allow_large_results=True)
bigquery_client = bigquery.Client(os.environ['GOOGLE_CLOUD_PROJECT'])

# fast
query_job = bigquery_client.query(query, job_config=job_config)
# Query complete after 0.50s

# fast
as_arrow = query_job.to_arrow(progress_bar_type='tqdm_notebook', create_bqstorage_client=True)
# Downloading: 100% 141673204/141673204 [01:18<00:00, 1873892.37rows/s]
type(as_arrow)
# pyarrow.lib.Table
print(f"{as_arrow.nbytes=}", f"{as_arrow.shape=}")
# as_arrow.nbytes=26_329_223_163 as_arrow.shape=(141_673_204, 24)

set(as_arrow.schema.types)
# {DataType(date32[day]),
# DataType(double),
# DataType(int64),
# DataType(string),
# TimestampType(timestamp[us, tz=UTC])}
```
###### Problematic part
```python
# slow
pl_arrow = pl.from_arrow(as_arrow)
```

```python
# also slow
pl_arrow = pl.from_arrow(as_arrow, rechunk=False)
```

##### Using alternative approach with `pl.read_sql` or `cx.read_sql`

```python
bq_conn = f"bigquery://{os.environ['GOOGLE_APPLICATION_CREDENTIALS']}"

df = pl.read_sql(query, bq_conn)
# ValueError: Empty result

df = cx.read_sql(conn=bq_conn, query=query, return_type="polars")
# ValueError: Empty result

df = cx.read_sql(conn=bq_conn, query=query, return_type="polars", partition_on="date", partition_num=365)
# PanicException: expecting a valid key: InvalidServiceAccountKey(Custom { kind: InvalidData, error: "Bad service account key: missing field `private_key` at line 1 column 468" })
```

#### What is the actual behavior?

Takes long to execute / fails with empty result.

#### What is the expected behavior?

Takes less time to execute / does not fail with empty result

Any ideas on how to get this work would be highly appreciated. 

Thank you for your time.

**Comment by ritchie46** [comment]
It could be you have many `String` columns. Polars needs to convert those to large string and also needs to rechunk, because arrow divides the sting data in many smaller chunks. 

Could you share a smaller slice of your data as parquet, then we could take a look.

**Comment by MichalChromcak** [comment]
I am afraid I cannot share the data (company internal). 

But if you think the string is the issue I might find a way to store it encoded. The other dtypes should be OKish?

When I try to skip (4) string columns, I am though still in a part, which takes very long to execute. 
Do you think there is a potential in speed up in general? e.g. I see, that the function uses only 1 core for most of the time?

```python
Counter(as_arrow.schema.types)
# Counter({DataType(int64): 8,
#         DataType(date32[day]): 1,
#         DataType(double): 10,
#         DataType(string): 4,
#         TimestampType(timestamp[us, tz=UTC]): 1})
```

**Comment by ghuls** [comment]
Are those operations slow in pyarrow too?
```python
def string_to_large_string(dtype):
    if dtype == pa.string():
        return pa.large_string()
    return dtype

%%time
as_arrow_with_large_string = as_arrow.cast(
   pa.schema(
        [
           (col, string_to_large_string(dtype))
            for col, dtype in zip(df_pal.schema.names, as_arrow.schema.types)
       ]

%%time
as_arrow_with_large_string_combine_chunks = as_arrow_with_large_string.combine_chunks()

%%time
pl_arrow = pl.from_arrow(as_arrow_with_large_string_combine_chunks, rechunk=False)
```

Are you using the version from pip or did you compile polars yourself?

**Comment by ritchie46** [comment]
> But if you think the string is the issue I might find a way to store it encoded. The other dtypes should be OKish?

The other should be zero copy. But we might be forced to rechunk because of the string data. Could you maybe recreate the same schema and chunk lengths with gibberish data?

**Comment by MichalChromcak** [comment]
> Are those operations slow in pyarrow too?
> 
> ```python
> def string_to_large_string(dtype):
>     if dtype == pa.string():
>         return pa.large_string()
>     return dtype
> 
> %%time
> as_arrow_with_large_string = as_arrow.cast(
>    pa.schema(
>         [
>            (col, string_to_large_string(dtype))
>             for col, dtype in zip(df_pal.schema.names, as_arrow.schema.types)
>        ]
> 
> %%time
> as_arrow_with_large_string_combine_chunks = as_arrow_with_large_string.combine_chunks()
> 
> %%time
> pl_arrow = pl.from_arrow(as_arrow_with_large_string_combine_chunks, rechunk=False)
> ```
> 
> Are you using the version from pip or did you compile polars yourself?

It is version from `pip`

I will give it a shot, but I am afraid I am having problems even without string columns in the dataset. 

I'll try removal of the date and timestamps if it helps.

Is there any profiling code, I could re-use to see, where is the bottleneck?

**Comment by MichalChromcak** [comment]
Thank you! 

It seems the `.combine_chunks()` saved me :) (executed with all the columns - string ones, timestamps, date32[day], ints and doubles)

![image](https://user-images.githubusercontent.com/12393430/179992156-fb65e0ee-e475-42ea-bf04-df3f0126d217.png)

**Comment by ghuls** [comment]
I assume you have miliions of chunks. Can you check?
```python
for col in as_arrow.schema.names:
    print(col, as_arrow.column(col).num_chunks
```

**Comment by MichalChromcak** [comment]
each column has `138404` chunks

**Comment by ritchie46** [comment]
Good catch @ghuls. This is something we should check and default to as well. Maybe we if `rechunk=True` we should do the rechunking on pyarrows side with `combine_chunks`?

**Comment by MichalChromcak** [comment]
I see. 

From my side I would consider the issue closed - I have a way how to deal with my problem efficiently. 

If it becomes a default behaviour somewhere, even nicer, but I can already continue and I am thankful for all your quick help. 🚀

**Comment by MichalChromcak** [comment]
@ghuls sorry, I already had to leave yesterday. These are the numbers, that apply for each column using
```python
def print_chunks(data):
    for col in data.schema.names:
        print(col, data.column(col).num_chunks)
```

`as_arrow = 138_404`
`as_arrow_combine_chunks = 1`
`as_arrow_with_large_string = 138_404`
`as_arrow_with_large_string_combine_chunks = 1`

**Comment by ghuls** [comment]
I am kind of surprised that the pyarrow `pa.string()` to `pa.large_string()` step didn't rechunk at least to slightly larger chunks as that step took 5 seconds, plus rechunking afterways took 4 seconds.

```
%%time
as_arrow_with_large_string = as_arrow.cast(
   pa.schema(
        [
           (col, string_to_large_string(dtype))
            for col, dtype in zip(df_pal.schema.names, as_arrow.schema.types)
       ]

%%time
as_arrow_with_large_string_combine_chunks = as_arrow_with_large_string.combine_chunks()
```

While the following took 22.6 seconds (maybe due the fact it has to calculate how big each chunk can be to fit the pa.string() columns in 2G chunks for all string columns):
```
as_arrow_combine_chunks = as_arrow.combine_chunks()
```

**Comment by ritchie46** [comment]
I found the culprit. We recompute the lenght every append. This has quadratic complexity. I am refactoring now to make the lenght cached.

**Comment by ritchie46** [comment]
Improved by #4105
