### ISSUE TITLE
Can't scroll downwards in VSCode notebook when mouse hover on df output

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4102]
#### What language are you using?
Python

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?
0.13.54

#### What operating system are you using polars on?

Mac OS

#### What language version are you using
Python 3.10

#### Describe your bug.
[This css](https://github.com/pola-rs/polars/blob/753fd1254272d122d4108a36c85476c40c65239c/py-polars/polars/_html.py#L156) line causes it to not be possible to scroll in the downwards direction when hovering the mouse on top of dataframe display output in VSCode notebook. I tracked it down to the above line, but have no idea why VSCode struggles with it. 

I recorded a video to show the issue and temporary fix:

https://user-images.githubusercontent.com/2721423/180145076-2e2f499c-e09c-4e5b-9dca-99029b3a13da.mov

**Comment by thomasaarholt** [comment]
This seems to be a VSCode issue with `line-height`. I can reproduce it with the <p> tag using non-polars/table html.

**Comment by ritchie46** [comment]
I've heard this more. Maybe open an issue upstream @vscode as well? I mean we produce valid css.

**Comment by thomasaarholt** [comment]
Already done :), see reference above

**Comment by thomasaarholt** [comment]
I couldn't find a dedicated function, but we can check for the `VSCODE_CWD` environment variable to see if we are in a vscode instance. The `get_ipython` is a [standard way of checking if we're in a notebook](https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook).
```python
import os

def check_vscode_notebook():
    try:
        get_ipython() # autoimported by notebooks
        os.environ["VSCODE_CWD"]
    except NameError:
        return False # not in notebook
    except KeyError:
        return False # not in VSCode
    return True
```

### In VSCode:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2721423/180308053-10ee91db-15db-4012-802f-cc5ccdc6441c.png">

### In Jupyter Notebook
<img width="466" alt="image" src="https://user-images.githubusercontent.com/2721423/180308515-467e6dda-e0df-4650-bbcc-51acfa0fb7aa.png">


### In iPython
<img width="809" alt="image" src="https://user-images.githubusercontent.com/2721423/180308415-f25030b4-647a-4b82-98c0-b2331ab6b7d2.png">

### In a python script
<img width="205" alt="image" src="https://user-images.githubusercontent.com/2721423/180308576-1b0fa2e7-fb4c-4f42-8dbf-b281a48866ce.png">

**Comment by ritchie46** [comment]
> ```python
> ron["VSCODE_CWD"]
> ```

Thanks, then we will use that for the time being. :+1:
