### ISSUE TITLE
rank() + groupby will kill your kermel if you have a  single null value

### ISSUE THREAD

**Issue by subpath** [pola-rs/polars#4109]
#### What language are you using?
 **Python**

#### Have you tried latest version of polars?
- [yes]

#### What version of polars are you using?

`0.13.55`

#### What operating system are you using polars on?

`macOs Monterey 12.2.1`

#### What language version are you using
`3.8.10`

#### Describe your bug.

When you try to use groupby and rank() on a column with `null` value it will restart the kernel

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.from_dict({
        "id": [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
        "rank": [None, 3, 2, 4, 1, 4, 3, 2, 1, None, 3, 4, 4, 1, None, 3],
    }).sort(by=["id", "rank"])

# this will kill your kernel
df.groupby("id").agg(pl.col("rank").rank())

```

#### What is the actual behavior?

<img width="595" alt="image" src="https://user-images.githubusercontent.com/11722602/180299710-1b304c5f-9059-43a9-83e7-d2bb0ed9e9f3.png">

#### What is the expected behavior?

What do you think polars should have done?
Would be nice to return an error saying that I can not use rank() with null, but don't kill the kernel 🙏

**Comment by ritchie46** [comment]
Thanks a lot for the report. I shall fix it.
