### ISSUE TITLE
Optionally leave nulls as null when hashing column

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4110]
I'm currently using hashing in order to int-encode categorical variables (strings) in my dataframe to use in gradient boosting models. These models are able to take into account null (or nan) values.

Currently, `null` gets hashed into an int. It would be nice if it could optionally be left out of the hashing:

```python
df = pl.DataFrame({"a":["a","b",None]})
df.with_column(pl.col("a").hash().alias("hash"))
shape: (3, 2)
┌──────┬─────────────────────┐
│ a    ┆ hash                │
│ ---  ┆ ---                 │
│ str  ┆ u64                 │
╞══════╪═════════════════════╡
│ a    ┆ 4040084588809488253 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 797887308973518190  │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null ┆ 4941890461364743684 │
└──────┴─────────────────────┘
```

**Comment by ghuls** [comment]
```python
df.with_column(pl.when(pl.col("a").is_null().then(None).otherwise(pl.col("a").hash()).alias("hash"))
```

**Comment by ritchie46** [comment]
I agree with @ghuls here. This is not worth the extra code on the rust side as this can be perfectly handled explicitly.

**Comment by thomasaarholt** [comment]
Nice! Thanks! :)
