### ISSUE TITLE
Keyboardinterrupt can take long time to interrupt polars code

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4120]
#### What language are you using?
Python

Keyboardinterrupts (either ctrl + C in python/ipython) or using the Interrupt functionality in notebooks are often useful to stop a running script without killing the whole python kernel. I can provide an example if desirable, but any long-running join should do.

With polars, keyboardinterrupts often take a very long time to complete - I suspect they wait until some stage of the rust code is finished before checking for an interrupt signal. 

I found this [stackoverflow thread](https://stackoverflow.com/questions/62364030/keyboard-interrupt-from-python-does-not-abort-rust-function-pyo3), where one of the comments for the [second answer](https://stackoverflow.com/a/62380364/1018861) mentions the [ctrlc crate](https://docs.rs/ctrlc/3.1.1/ctrlc/index.html). Is this something polars could rely on to make interruptions smoother?

**Comment by ghuls** [comment]
Duplicate of https://github.com/pola-rs/polars/issues/2687. As far as I know, nothing can be done about it, unless Python changes.

**Comment by thomasaarholt** [comment]
Thanks!
