### ISSUE TITLE
timedelta.sum gives null in select (works as expected in groupby)

### ISSUE THREAD

**Issue by jeremychone** [pola-rs/polars#4123]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

```
> pip show polars
Name: polars
Version: 0.13.55
```

#### What operating system are you using polars on?

Mac M1, MacOS 12.1

#### What language version are you using

Python 3.10.4

#### Describe your bug.

For `timedelta` columns, when using `.sum()` in a groupby, it works as expected; when using it in a select, get null back.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
from datetime import datetime, timedelta


df = pl.DataFrame([
    {"name": "Jen", "duration": timedelta(seconds=60)},
    {"name": "Mike", "duration": timedelta(seconds=30)},
    {"name": "Jen", "duration": timedelta(seconds=60)},
])

print("\nSimple select duration.sum is null:\n")
print(df.select([
    pl.col("duration").sum(), # <-- issue, somehow gives 'null' back
    pl.col("duration").dt.seconds().alias("sec").sum() # works as expected
]))

print("\nIn groupby, works as expected:\n")
print(df.groupby("name").agg([pl.col("duration").sum()])) # works as expected

```

Give the following output: 

```
Simple select duration.sum is null:

shape: (1, 2)
┌──────────────┬─────┐
│ duration     ┆ sec │
│ ---          ┆ --- │
│ duration[μs] ┆ i64 │
╞══════════════╪═════╡
│ null         ┆ 150 │
└──────────────┴─────┘

In groupby, works as expected:

shape: (2, 2)
┌──────┬──────────────┐
│ name ┆ duration     │
│ ---  ┆ ---          │
│ str  ┆ duration[μs] │
╞══════╪══════════════╡
│ Mike ┆ 30 seconds   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Jen  ┆ 2 minutes    │
└──────┴──────────────┘
```

#### What is the expected behavior?

I might be missing something obvious here, and since I can get the sum in seconds and work for there, this is not a blocker. 

However, if this does not impact the soundness of the model, it would be great to be able to do a simple `pl.col("duration").sum()` in select as with other data types and in groupby.

**Comment by ritchie46** [comment]
Yep, there is no reason that should not be enabled for `select` as well. Thanks, I will fix it.

**Comment by jeremychone** [comment]
wow. That was impressive. 
_You guys are putting the bar way too high for the rest of us!_
