### ISSUE TITLE
Newlines are not handled by read_csv or write_csv

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#4130]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.13.56

#### What operating system are you using polars on?

Linux

#### What language version are you using

Python 3.10

#### Describe your bug.

If the table contains strings with newlines, `write_csv` produces an invalid CSV file. At least, not one that `read_csv` can read in. Now, there is no official CSV standard, so it is ambiguous what the right thing to do here is. Some programs use `\n` and others simply allow newlines between quotes. Because Polars uses `""` for a literal double quote instead of `\"` or `\q` and uses `\` for slash rather than `\\`, the latter solution is probably more appropriate for Polars.

It would also be reasonable to raise an error when trying to write a newline.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

filename = "temp.csv"
table = pl.DataFrame(dict(escape=["n\nn"]))
table.write_csv(filename)
pl.read_csv(filename)
```

#### What is the actual behavior?

```
shape: (2, 1)
┌────────┐
│ escape │
│ ---    │
│ str    │
╞════════╡
│ n      │
├╌╌╌╌╌╌╌╌┤
│ n      │
└────────┘

```

#### What is the expected behavior?

```
shape: (1, 1)
┌────────┐
│ escape │
│ ---    │
│ str    │
╞════════╡
│ n      │
│ n      │
└────────┘
```

**Comment by ritchie46** [comment]
Thanks for the report. This is something we need to escape indeed. Polars follow [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) as closest document to a csv standard. That means we need to quote those fields.
