### ISSUE TITLE
pl.from_dicts() Schema mismatch

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#4143]
Python 3.10, Ubuntu 22.04, polars 0.13.57 (latest)
Describe your bug.
Two issues with schema.
 1.
```python
pl.from_dicts([
    {
        'id': 1, 'hint': [
        {'some_text_here': 'text', 'list_': [1,2,4]},
        {'some_text_here': 'text', 'list_': [1,2,4]}
        ]
    },
    {
        'id': 2, 'hint': [
            {'some_text_here': None, 'list_': [1]},
            {'some_text_here': None, 'list_': [2]}
        ]
    }
])
ShapeMisMatch("expected all fields to have equal length")
```
2.
```python
pl.from_dicts([
    {
        'id': 1, 'hint': [
        {'some_text_here': 'text', 'list_': [1,2,4]},
        {'some_text_here': 'text', 'list_': [1,2,4]}
        ]
    },
    {
        'id': 2, 'hint': [
            {'some_text_here': 'text', 'list_': []},
            {'some_text_here': 'text', 'list_': []}
        ]
    }
])
ShapeMisMatch("expected all fields to have equal length")
```
And that is ok:

```python
pl.from_dicts([
    {
        'id': 1, 'hint': [
        {'some_text_here': 'text', 'list_': [1,2,4]},
        {'some_text_here': 'text', 'list_': [1,2,4]}
        ]
    },
    {
        'id': 2, 'hint': [
            {'some_text_here': 'text', 'list_': [1]},
            {'some_text_here': None, 'list_': []}
        ]
    }
])
```

**Comment by s-b90** [comment]
Hi @ritchie46, any updates here?

**Comment by zundertj** [comment]
@s-b90 : I can reproduce this, but I have to say, this is quite a deep nested structure you have. The output of the code snippet that works is 
```
shape: (2, 2)
┌─────┬─────────────────────────────────────┐
│ id  ┆ hint                                │
│ --- ┆ ---                                 │
│ i64 ┆ list[struct[2]]                     │
╞═════╪═════════════════════════════════════╡
│ 1   ┆ [{"text",[1, 2, 4]}, {"text",[1,... │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ [{"text",[1]}, {null,[]}]           │
└─────┴─────────────────────────────────────┘
```
I.e., each entry in `hint` becomes a list of a struct of 2 elements, where the second element of the struct is a list.

If you can provide us with more context on what you are trying to achieve, we may be able to provide you with a workaround until there is time to fix this problem.

**Comment by s-b90** [comment]
@zundertj Thanks for your answer. I'm getting this data as an API response in JSON format. My goal is to transform it into a tabular view and after some calculations put the result into database. I was converting data into tabular with `.explode()` and `.struct.field()` and this covered all my needs before `null` data comes.

So, now, as a workaround, I load data into pandas DataFrame as it is, make some fine-tuning and put data into polars for calculations and further processing. It causes some additional problems, in some cases `.from_pandas` also raise an error, and it is not an efficient way to run it through pandas I think.

Another option is to fill `null` with `zeros` manually, before loading DataFrame, but it is also not efficient on python and `null` not always mean `zero`.

**Comment by s-b90** [comment]
Hi guys, I've noticed that in the current version of polars (0.14.19) the error has gone.
But the output df is filled with `null` in examples 1 and 2.

hint | id
-- | --
list[struct[2]] | i64
[{"text",[1, 2, 4]}, {"text",[1, 2, 4]}] | 1
[{null,null}, {null,null}] | 2

Is there any chance to fix the issue in near feature?

**Comment by s-b90** [comment]
@ritchie46 I've tried on version 0.14.23. The first example runs ok, but the second raises an error:
```python
pl.from_dicts([
    {
        'id': 1, 'hint': [
        {'some_text_here': 'text', 'list_': [1,2,4]},
        {'some_text_here': 'text', 'list_': [1,2,4]}
        ]
    },
    {
        'id': 2, 'hint': [
            {'some_text_here': 'text', 'list_': []},
            {'some_text_here': 'text', 'list_': []}
        ]
    }
])
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray<i64> expects DataType::LargeList")', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.14.2/src/array/list/mod.rs:93:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/sb/work/data-generation/src/ch/ch.py", line 240, in <module>
    df = pl.from_dicts([
  File "/home/sb/work/data-generation/venv/lib/python3.10/site-packages/polars/convert.py", line 131, in from_dicts
    return DataFrame._from_dicts(dicts, infer_schema_length, schema)
  File "/home/sb/work/data-generation/venv/lib/python3.10/site-packages/polars/internals/dataframe/frame.py", line 317, in _from_dicts
    pydf = PyDataFrame.read_dicts(data, infer_schema_length, schema)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray<i64> expects DataType::LargeList")
```
