### ISSUE TITLE
Should `nodejs-polars` remain in `polars`? 

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#4148]
Just wondering if `nodejs-polars` should remain in the main polars project, or if it should be moved to it's own repo. 

99% of the PR's are for python or rust, and a lot of these add breaking changes that need to be updated in JS too. Most people don't use the JS bindings, so it makes sense that it isnt being updated, but this causes the JS bindings to regularly fall out of sync with the other two. Being the primary contributor, it is becoming more difficult to keep the JS bindings up to date. 

After nearly 8 months, the JS bindings are still rarely used:  `~500` downloads a month.

**Comment by ritchie46** [comment]
I can understand it puts a strain on your time and makes it harder to work in your ideal pace. I think it could be transferred to a separate repository. 

If we then rely on the released crates.io version, the pace will be a lot lower.

**Comment by slonik-az** [comment]
> If we then rely on the released crates.io version, the pace will be a lot lower.

Since we are at this topics, would it be possible to keep the polars releases consistent across `crates.io` and `github` ?

Currently, the `polars` versions are as follows:
- on `crates.io` it is version `0.22.8`, 
- `polars/Cargo.toml` on master branch says `"0.22.6"`
- `github`'s latest release `0.22.1`

Unnecessary inconsistent 😄

**Comment by universalmind303** [comment]
> I think it could be transferred to a separate repository.

makes sense to me. 
@ritchie46 if it's okay with you, i'd like to still keep it in the `pola-rs` org. `pola-rs/nodejs-polars`. 
If you prefer not to though, I can just as easily move it into my own repo.

**Comment by universalmind303** [comment]
I'm wondering, should we keep the two linked via a git submodule?
