### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#416]
Sticky note of todo's

## Rust
- [ ] Temporal docs: These are heavily outdated.
- [ ] add example to [apply](https://ritchie46.github.io/polars/polars/prelude/struct.LazyGroupBy.html#method.apply)
- [ ] add example to [map](https://ritchie46.github.io/polars/polars_lazy/dsl/enum.Expr.html#method.map)

## Python
- [ ] Add examples to all functions
- [ ] Show connection examples with databases, with an optional third party lib like [smart-open](https://pypi.org/project/smart-open/)

## Book
- [ ] Getting started
- [ ] Data types

**Comment by koaning** [comment]
Would the repository be open to having python docs being hosted via `mkdocs`?

**Comment by ritchie46** [comment]
Yes, I am looking for a more professional setup for the python docs. Currently they only point to master without any versioning, which is not desirable to say the least. I want something that's markdown friendly, automatically makes docs from all my code and just isn't sphinx. :)

**Comment by koaning** [comment]
I might be able to whip up an example that's similar to [this](https://rasahq.github.io/whatlies/). One thing though, this style of docs does assume that the docstrings are written in markdown as well. Would that be feasible?

**Comment by koaning** [comment]
My approach thus far has always been to push manually, but I haven't got any experience, or considered even, hosting docs supporting multiple versions of a project.

**Comment by ritchie46** [comment]
> I might be able to whip up an example that's similar to this. One thing though, this style of docs does assume that the docstrings are written in markdown as well. Would that be feasible?

Looks fancy :). Would appreciate that. I believe the current state of the docstrings is completely markdown.

**Comment by koaning** [comment]
Here's a preview of what it currently looks like on my machine. Building from source took *way* too long so I just did `pip install py-polars` to generate this small preview.

![image](https://user-images.githubusercontent.com/1019791/111208425-009bd500-85cb-11eb-8d65-8d6404a021fc.png)

There's some settings that allow for code inspection and such but there are a few things you need to change to all docstrings. In particular: 

- `Parameters` should be change to "Arguments" 
- The `---` line under segments should be removed
- I think the types cannot be strings if you want the pretty tables with argument information to render. 

Still, you already get some of this interaction for free.

![image](https://user-images.githubusercontent.com/1019791/111208610-45277080-85cb-11eb-8a98-f302684772e0.png)

Something is telling me that my preview here is cute, but that there is a lot of consider here. Are you sure this feels right for your project?

**Comment by ritchie46** [comment]
Wow that looks a lot better already! The left side bar could be used to add a ToC and a more guided walkthrough right? 

> Are you sure this feels right for your project? It feels like there's a list of stuff that ought to be checked. 

I think that this can already be a major step forward. What especially is missing at the moment is some structure IMO. Maybe

>Things like; do you intend to host two docs? One for python and one for rust?

I do want to keep them separate. The Rust documentation is embedded with the tooling (and included in unit tests) and is automatically generated when you publish a package (called crate in Rust). I found it a lot easier to keep code examples up to date that way.

For Python I hope to have a clear reference guide with a lot of examples that help you find the right snippet easily. I really think that if the tooling is good that I can make the docs better incrementally.

> Here's a preview of what it currently looks like on my machine. Building from source took way too long so 

Haha, did you run `$ maturin develop --release` ? That indeed takes forever:see_no_evil: (40 minutes or so). Without the `--release` flag, you'll get a slow development build, with more acceptable build times.

There is a fresh pre-release as well: `$ pip install polars==0.7.0-beta.1`

> I think the types cannot be strings if you want the pretty tables with argument information to render.

What do you mean?

**Comment by koaning** [comment]
If you have a look at [this page](https://rasahq.github.io/whatlies/api/embedding/#whatlies.embedding.Embedding.plot) you'll see a function being documented. Note how there's a pretty table for the function with types being added. Your code lists strings as types sometimes. My impression that this kind of type declaration isn't supported by `mkdocstrings`.

**Comment by ritchie46** [comment]
Oh right.. the string types like `def foo(a: "Expr"):..`.

Yes, thats unfortunately due to the fact that python 3.6 doesn't support typing. I first didn't want to support that version, but kaggle notebooks and colab were still on 3.6.

**Comment by pawamoy** [comment]
But it does! I thinkg the typing module was introduced in Python 3.5, while the annotations themselves (`a: int = 0`) were introduced in Python 3.6 🙂

**Comment by jcmkk3** [comment]
I think that they’re actually referencing the use of types before they’re declared. Before [PEP563](https://www.python.org/dev/peps/pep-0563/), you would have to do that by just using a string in the signature.

**Comment by pawamoy** [comment]
Ah, I see, you're right. It's only possible starting at 3.7 indeed (https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7)
