### ISSUE TITLE
Different result of the example code.

### ISSUE THREAD

**Issue by liudonghua123** [pola-rs/polars#4169]
#### What language are you using?

Python and Node.js

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

polars-0.13.58-cp37-abi3-win_amd64.whl
"nodejs-polars": "^0.5.4"

#### What operating system are you using polars on?

Microsoft Windows [Version 10.0.22000.795]

#### What language version are you using

Python 3.10.2, Node.js v16.13.1

#### Describe your bug.

I tried to run the following example code both in Python and Nodejs in REPL. But the result of the last column is different.

```python
import polars as pl
df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "fruits": ["banana", "banana", "apple", "apple", "banana"],
        "B": [5, 4, 3, 2, 1],
        "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
    }
)
df.sort("fruits").select(
    [
        "fruits",
        "cars",
        pl.lit("fruits").alias("literal_string_fruits"),
        pl.col("B").filter(pl.col("cars") == "beetle").sum(),
        pl.col("A").filter(pl.col("B") > 2).sum().over("cars").alias("sum_A_by_cars"),
        pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
        pl.col("A").reverse().over("fruits").alias("rev_A_by_fruits"),
        pl.col("A").sort_by("B").over("fruits").alias("sort_A_by_B_by_fruits"),
    ]
)
```

```js
const pl = require('nodejs-polars'); 
const df = pl.DataFrame(
   {
     A: [1, 2, 3, 4, 5],
     fruits: ["banana", "banana", "apple", "apple", "banana"],
     B: [5, 4, 3, 2, 1],
     cars: ["beetle", "audi", "beetle", "beetle", "beetle"],
   }
)
df.sort("fruits").select(
    "fruits",
    "cars",
    pl.lit("fruits").alias("literal_string_fruits"),
    pl.col("B").filter(pl.col("cars").eq(pl.lit("beetle"))).sum(),
    pl.col("A").filter(pl.col("B").gt(2)).sum().over("cars").alias("sum_A_by_cars"),
    pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
    pl.col("A").reverse().over("fruits").alias("rev_A_by_fruits"),
    pl.col("A").sort("B").over("fruits").alias("sort_A_by_B_by_fruits"),
)
```

![image](https://user-images.githubusercontent.com/2276718/181303091-eed131e1-19cf-4c93-93ab-1d9d92a96584.png)

![image](https://user-images.githubusercontent.com/2276718/181302850-0d3d1baa-38bf-4d33-a353-043fdaabf6a3.png)

**Comment by cbilot** [comment]
> pl.col("A").sort("B").over("fruits").alias("sort_A_by_B_by_fruits"),

did you mean `sort_by` in the last row of the second code block?

**Comment by liudonghua123** [comment]
If I use `sort_by`, I got `Uncaught TypeError: pl.col(...).sort_by is not a function`.

![image](https://user-images.githubusercontent.com/2276718/181306040-d6324099-015d-483b-9ec3-3fe43d47a41c.png)

I list the keys of `pl.col("A")`, the correct is `sortBy`, not `sort_by`. Maybe a spell mistake?

![image](https://user-images.githubusercontent.com/2276718/181306993-5e953b70-d31c-493f-a22c-2891a679fa76.png)

![image](https://user-images.githubusercontent.com/2276718/181307148-5300d619-7bbd-43e1-ab1a-b0b7af9b69e0.png)

And I also found the result of `rev_A_by_fruits` column always changes. Did I miss something?

![image](https://user-images.githubusercontent.com/2276718/181307784-7bdfec12-c35e-4192-bbdf-f7a8282b5dd1.png)

**Comment by liudonghua123** [comment]
The result of python version stays the same. But the Node.js version is not. 

I expected they should be the same result.

Here are the testing code.

```python
import polars as pl
df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "fruits": ["banana", "banana", "apple", "apple", "banana"],
        "B": [5, 4, 3, 2, 1],
        "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
    }
)
df.sort("fruits").select(
    [
        "fruits",
        "cars",
        pl.lit("fruits").alias("literal_string_fruits"),
        pl.col("B").filter(pl.col("cars") == "beetle").sum(),
        pl.col("A").filter(pl.col("B") > 2).sum().over("cars").alias("sum_A_by_cars"),
        pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
        pl.col("A").reverse().over("fruits").alias("rev_A"),
        pl.col("A").sort_by("B").over("fruits").alias("sort_A_by_B_by_fruits"),
    ]
)
```

```js
const pl = require('nodejs-polars'); 
const df = pl.DataFrame(
   {
     A: [1, 2, 3, 4, 5],
     fruits: ["banana", "banana", "apple", "apple", "banana"],
     B: [5, 4, 3, 2, 1],
     cars: ["beetle", "audi", "beetle", "beetle", "beetle"],
   }
)
df.sort("fruits").select(
    "fruits",
    "cars",
    pl.lit("fruits").alias("literal_string_fruits"),
    pl.col("B").filter(pl.col("cars").eq(pl.lit("beetle"))).sum(),
    pl.col("A").filter(pl.col("B").gt(2)).sum().over("cars").alias("sum_A_by_cars"),
    pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
    pl.col("A").reverse().over("fruits").alias("rev_A_by_fruits"),
    pl.col("A").sortBy("B").over("fruits").alias("sort_A_by_B_by_fruits"),
)
```

**Comment by universalmind303** [comment]
trying to replicate, and I am seeing the same indeterministic values for `rev_A` in python if you run the example enough times. 
![image](https://user-images.githubusercontent.com/21327470/182043584-75d0cd07-ea72-4059-910c-b3a7f50e25fe.png)

![image](https://user-images.githubusercontent.com/21327470/182043597-13b18488-c26c-402f-850b-c0b4a4cd0b0c.png)

**Comment by ritchie46** [comment]
Can you confirm this still occurs in 0.13.59?

**Comment by universalmind303** [comment]
yeah that does fix it. 
```python
import polars as pl
assert pl.version() == '0.13.59'
df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "fruits": ["banana", "banana", "apple", "apple", "banana"],
        "B": [5, 4, 3, 2, 1],
        "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
    }
)
df.sort("fruits").select(
    [
        "fruits",
        "cars",
        pl.lit("fruits").alias("literal_string_fruits"),
        pl.col("B").filter(pl.col("cars") == "beetle").sum(),
        pl.col("A").filter(pl.col("B") > 2).sum().over("cars").alias("sum_A_by_cars"),
        pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
        pl.col("A").reverse().over("fruits").alias("rev_A"),
        pl.col("A").sort_by("B").over("fruits").alias("sort_A_by_B_by_fruits"),
    ]
)
```
as soon as I have write access to the new nodejs-polars repo, ill push up a release with latest code.

**Comment by ritchie46** [comment]
I have invited you as maintainer. Can you also do a `git-filter-brach`?

**Comment by ritchie46** [comment]
This is fixed on master. I will close this here.
