### ISSUE TITLE
missing_data.html link is dead in docs

### ISSUE THREAD

**Issue by dvreed77** [pola-rs/polars#4170]
In Coming From Pandas [documentation](https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html), the [missing_data](https://pola-rs.github.io/polars-book/user-guide/missing_data.html) link is dead.

**Comment by ritchie46** [comment]
Thanks. Opened in the appropriate repo: https://github.com/pola-rs/polars-book/issues/177
