### ISSUE TITLE
[python] show_graph() file encoding error on Windows

### ISSUE THREAD

**Issue by laundmo** [pola-rs/polars#4222]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.13.59

#### What operating system are you using polars on?

Widnows 10 Pro 10.0.190.43

#### What language version are you using
Python 3.9

#### Describe your bug.

When using LazyFrame.show_graph() polars tries to write a file with the default encoding, cp1252 on windows, which does not support all characters used. This causes a `UnicodeEncodeError: 'charmap' codec can't encode character '\u03c0' in position 31: character maps to <undefined>`

#### What are the steps to reproduce the behavior?

```py
import polars as pl

df = pl.DataFrame({"a": [1]})
df.lazy().show_graph()
```

#### What is the actual behavior?
 ```
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    df.lazy().show_graph()
  File "C:\Program Files\Python39\lib\site-packages\polars\internals\lazy_frame.py", line 516, in show_graph
    f.write(dot)
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03c0' in position 31: character maps to <undefined>
```

#### What is the expected behavior?

The codec for the file is set correctly. Which I assume would be utf-8.

**Comment by ritchie46** [comment]
The `\u03c0` is unicode for small letter pi. Does windows open files in ascii? 

As what we do is not that exotic:

```python
# dot is a str so is guaranteed to be unicode
    with open(dot_path, "w") as f:
                f.write(dot)
```
