### ISSUE TITLE
[Python] Add `.date` functionality to datetimes

### ISSUE THREAD

**Issue by alexthe2** [pola-rs/polars#4227]
Currently to get only the date from a datetime one must write sth. similar to:
```python
df = df.select([
    pl.col("*"),
    pl.col("time_start").apply(lambda x: x.date()).alias("date")
])
```

Would it be possible to add datetimes `.date` functionality natively to `.dt`, so ExprDateTime

Then one should be able to write sth. like:
```python
df = df.select([
    pl.col("*"),
    pl.col("time_start").dt.date().alias("date")
])
```

**Comment by ritchie46** [comment]
You can cast to a `pl.Date`.

Can you make a stackoverflow question with an MWE? Then I will answer it there and more people can discorer it.

**Comment by alexthe2** [comment]
sure

**Comment by alexthe2** [comment]
https://stackoverflow.com/questions/73212628/retrieve-date-from-datetime-column-in-polars

**Comment by alexthe2** [comment]
> You can cast to a `pl.Date`.
> 
> Can you make a stackoverflow question with an MWE? Then I will answer it there and more people can discorer it.

This makes sense, but it still feels a little bit like a workaround to me, it's propably not high priority, but it'd be still amazing if you could keep it somewhere on the backlog 🙃 .

**Comment by ritchie46** [comment]
> This makes sense, but it still feels a little bit like a workaround to me, it's propably not high priority, but it'd be still amazing if you could keep it somewhere on the backlog upside_down_face .

What do you mean? It seems pretty straightforward to me?

```python
import datetime
import polars as pl

df = pl.DataFrame({
    'time': [datetime.datetime.now()]
})

df.with_column(
    pl.col("time").cast(pl.Date)
)
```

**Comment by alexthe2** [comment]
> > This makes sense, but it still feels a little bit like a workaround to me, it's propably not high priority, but it'd be still amazing if you could keep it somewhere on the backlog upside_down_face .
> 
> What do you mean? It seems pretty straightforward to me?
> 
> ```python
> import datetime
> import polars as pl
> 
> df = pl.DataFrame({
>     'time': [datetime.datetime.now()]
> })
> 
> df.with_column(
>     pl.col("time").cast(pl.Date)
> )
> ```

nono, it's absolutely straightforward, I just try to avoid casting where possible, it might be a personal preference though

**Comment by ritchie46** [comment]
> nono, it's absolutely straightforward, I just try to avoid casting where possible, it might be a personal preference though

So a function that would return a date would be better? Seems like a cast to me 😜

**Comment by alexthe2** [comment]
> > nono, it's absolutely straightforward, I just try to avoid casting where possible, it might be a personal preference though
> 
> So a function that would return a date would be better? Seems like a cast to me 😜

Technically 🙃 , yeah doesn't matter. I will close the issue
