### ISSUE TITLE
Issues when supplying `dtypes` as `dict` to `read_csv`

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#4239]
#### What language are you using?

**Python**

#### What version of polars are you using?

0.13.58

#### What operating system are you using polars on?

Ubuntu 21.08

#### What language version are you using
python 3.9

#### 
Polars' (and pyarro'ws, for that matter) CSV reader seems to be having some problems with `Boolean` columns when supplying dtypes as a dictionary.

When passing boolean columns, it seems to be sometimes unable to locate the second column:
```python3
from io import StringIO

import polars as pl

csv = "a, b\n" + "true,false\n" + ",false\n" + ",false"
df = pl.read_csv(
    StringIO(csv),
    dtypes={"a": pl.Boolean, "b": pl.Boolean},
)
print(df)
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
...
NotFoundError: b
```

In other cases, an `ArrowErrorException` is raised:
```python3
from io import StringIO

import polars as pl

csv = "a,b\n" + "true,\n" + "false,\n" + ",\n"
df = pl.read_csv(
    StringIO(csv),
    dtypes={"a": pl.Boolean, "b":pl.Boolean},
)
print(df)
---------------------------------------------------------------------------
ArrowErrorException                       Traceback (most recent call last)
...
ArrowErrorException: NotYetImplemented("Casting from LargeUtf8 to Boolean not supported")
```

Although I am unable to reconstruct the logic or even the source of these exceptions, the above exceptions should be reproducible for everyone using a recent polars version.

**Comment by ritchie46** [comment]
> When passing boolean columns, it seems to be sometimes unable to locate the second column:

The second column is `" b"`, not `"b"`.

Fix for boolean is coming up.

**Comment by DrMaphuse** [comment]
> The second column is `" b"`, not `"b"`.

Good eye - should've taken a break before writing a bug report.

The boolean issue was what threw me off originally, though.

Thanks
