### ISSUE TITLE
Histogram of a series

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#4240]
#### Describe your feature request
A method on a series to return the histogram of that series. I've put together an idea of how it could work on Discord:

Define our data df with a temperature data column
```python
df1 = pl.DataFrame({"temp": [1.1,1.5, 3.1, 10.0]})
```
Define a new DataFrame with bin start and ends (I've done something simple here with 10 unit bins)
```python
df2 = pl.DataFrame({'bin_s':[float(i) for i in range(10+1)]}).with_column((pl.col('bin_s')+1).alias('bin_e'))
```
We then (from inside to outside in terms of the code):
- do a value counts on the original data and sort the output
- do a join_asof to map these to the nearest bin_start in df2['bin_s]
- do a groupby on the bin_s and count to aggregate
- do a left join of df2 with the groupby output to get the count for all the bins
```python 
df2.join(
df1['temp'].value_counts().sort('temp').join_asof(df2,left_on='temp',right_on='bin_s').groupby('bin_s').agg(pl.col('counts').sum()),on='bin_s')
```
I haven't given much thought to the detail of checking what happens at bin edges etc, but I think this is broadly how it works. It's worth breaking down the code inside the join to understand what's happening.

I've timed it with a large f64 series with respect to np.histogram and it's 10x slower. The problem in this case is that the value_counts in this case is basically just all the unique values. If you know the bin edges you really want to add a new column that quickly maps the value in the series to its group and then do groupby on that

**Comment by zundertj** [comment]
What about using [pl.cut](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.cut.html) on the Series (no expressions interface yet it seems unfortunately), and doing a value counts? Maybe I am missing the point.

(sorry, can't test this myself at the moment, as as my nightly install is broken)

**Comment by cbilot** [comment]
@zundertj is on the right track.  I found one tiny hiccup: `value_counts` won't maintain Categorical values.

Picking a million samples from a standard random normal distribution ....
```python3
import numpy as np
import polars as pl
import math

s_norm = pl.Series(
    name="normal", values=np.random.default_rng(2).normal(0, 1, 1_000_000))

breaks = list(
    range(
        math.ceil(s_norm.min()),
        math.floor(s_norm.max()) + 1,
    )
)

(
    pl.cut(s_norm, breaks)
    .groupby('category')
    .count()
    .sort('category')
)
```
```
shape: (12, 2)
┌──────────────┬────────┐
│ category     ┆ count  │
│ ---          ┆ ---    │
│ cat          ┆ u32    │
╞══════════════╪════════╡
│ (-inf, -5.0] ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (-5.0, -4.0] ┆ 33     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (-4.0, -3.0] ┆ 1286   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (-3.0, -2.0] ┆ 21497  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (-2.0, -1.0] ┆ 135559 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (-1.0, 0.0]  ┆ 341009 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (0.0, 1.0]   ┆ 341604 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (1.0, 2.0]   ┆ 136337 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (2.0, 3.0]   ┆ 21333  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (3.0, 4.0]   ┆ 1303   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (4.0, 5.0]   ┆ 37     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ (5.0, inf]   ┆ 1      │
└──────────────┴────────┘
```
`value_counts` gives us:
```python
(
    pl.cut(s_norm, breaks)
    .get_column('category')
    .value_counts()
    .sort('category')
)
```
```
shape: (12, 2)
┌──────────┬────────┐
│ category ┆ counts │
│ ---      ┆ ---    │
│ u32      ┆ u32    │
╞══════════╪════════╡
│ 0        ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1        ┆ 33     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2        ┆ 1286   │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3        ┆ 21497  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4        ┆ 135559 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 5        ┆ 341009 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 6        ┆ 341604 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 7        ┆ 136337 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 8        ┆ 21333  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 9        ┆ 1303   │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 10       ┆ 37     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 11       ┆ 1      │
└──────────┴────────┘
```

**Comment by braaannigan** [comment]
Nice - On my MBP the 1 billion dataset (without the breaks calculation) takes 82 seconds versus 72 seconds for the np.histogram which is fine as a starting point imo.

For Polars the time output is:
```
CPU times: user 4min 39s, sys: 53 s, total: 5min 32s
Wall time: 1min 22s
```
So very parallel for Polars. The numpy implementation isn't parallel despite being fast:
```
CPU times: user 1min 4s, sys: 4.01 s, total: 1min 8s
Wall time: 1min 10s
```

**Comment by hpux735** [comment]
@cbilot this seems like a very straight-forward way to implement this.  Thanks for that!  I'm looking forward to experimenting with it.

**Comment by hpux735** [comment]
After reading this carefully again, I thought I should mention that I'm not using Python, so `np` isn't useful to me anyhow :)

**Comment by hpux735** [comment]
Oh no!!  `pl.cut` is implemented in Python, not Rust 😭

**Comment by hpux735** [comment]
As of https://github.com/pola-rs/polars/pull/4693 `cut()` is implemented in Rust, and I think I'm good to go.  Thanks for the advice all!
