### ISSUE TITLE
`is_duplicated` bug

### ISSUE THREAD

**Issue by oscar6echo** [pola-rs/polars#4257]
#### What language are you using?

**Python**.

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.13.60

#### What operating system are you using polars on?

Linux, Windows.

#### What language version are you using

Python 3.8

#### Describe your bug.

In some cases `.is_duplicated()` does not work.

#### What are the steps to reproduce the behavior?

```
your
code
goes
here
```

**Example**

```python
import polars as pl

df = pl.DataFrame({
    '_id': [1, 2, 3],
    'a': [99, 54612, 546121],
    'b': [1, 14484, 4484],
}).with_columns(pl.all().cast(pl.Utf8))
print(df)

# cell 1
keys = ['a', 'b']
dups = df[keys].is_duplicated()
df_dup = df.filter(pl.lit(dups))
print(df_dup)
# not working
shape: (2, 3)
┌─────┬────────┬───────┐
│ _id ┆ a      ┆ b     │
│ --- ┆ ---    ┆ ---   │
│ str ┆ str    ┆ str   │
╞═════╪════════╪═══════╡
│ 2   ┆ 54612  ┆ 14484 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3   ┆ 546121 ┆ 4484  │
└─────┴────────┴───────┘

# cell 2
sep = '|'
df2 = df.with_column(pl.concat_str(keys, sep).alias('_id'))
dups = df2['_id'].is_duplicated()
df_dup = df.filter(pl.lit(dups))
df_dup
# working
shape: (0, 3)
┌─────┬─────┬─────┐
│ _id ┆ a   ┆ b   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
└─────┴─────┴─────┘
```

#### What is the expected behavior?

The expected behavior is that of cell 2.  
It is probable that `is_duplicated` is implemented by concatenating columns.  
But in some cases this leads so false duplicates.  
At least, a `separator` param could be added to `is_duplicated`.  
And probably a warning in the documentation about the edge case given above.

**Comment by ritchie46** [comment]
Thanks for finding this! It turns out we were too smart for our own good. A fix is coming up.
