### ISSUE TITLE
Reading an empty CSV will panic

### ISSUE THREAD

**Issue by ydarma** [pola-rs/polars#4260]
#### What language are you using?

**Rust**.

#### Which feature gates did you use?

None.

#### Have you tried latest version of polars?

Yes.

#### What version of polars are you using?

0.22.8

#### What operating system are you using polars on?

Ubuntu 22.04

#### What language version are you using
`rustc 1.62.1 (e092d0b6b 2022-07-16)`

#### Describe your bug.

A csv file with no row causes panic when trying to load into a dataframe

#### What are the steps to reproduce the behavior?

```rust
#[cfg(test)]
mod tests {
    use polars::prelude::{CsvReader, PolarsError, SerReader};

    #[test]
    fn it_works() -> Result<(), PolarsError> {
        let data_frame = CsvReader::from_path("./test.csv")?
            .has_header(true)
            .finish()?;
        if data_frame.is_empty() {
            Ok(())
        } else {
            Err(PolarsError::ShapeMisMatch("expected empty df".into()))
        }
    }
}
```

`test.csv` file:
```
A,B
```

#### What is the expected behavior?

Create an empty dataframe with 2 columns.

If this is actually a bug I can try to fix and make a PR.

**Comment by ritchie46** [comment]
Does this still occur in polars 0.23.0?

**Comment by ydarma** [comment]
Yes, I upgraded just after filling the form.

**Comment by ritchie46** [comment]
That's strange. I can run this:

```python
csv = "A,B\n"

pl.read_csv(csv.encode())
```

```
shape: (0, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
└─────┴─────┘

```

**Comment by ydarma** [comment]
Ok, I think that I understand what happens: the panic is `attempt to subtract with overflow` at line 340 of [read_impl.rs](https://github.com/pola-rs/polars/blob/master/polars/polars-io/src/csv/read_impl.rs) ; it won't panic in release mode. But I think this is not the way it should be done.

Something like this would be safer:
```rust
        let starting_point_offset = if bytes.len() == 0 {
            0
        } else {
            bytes.as_ptr() as usize - starting_point_offset;
        }
```
This can certainly be improved by understanding why `bytes.as_ptr()` is greater than `starting_point_offset`. I'll investigate further.

**Comment by ydarma** [comment]
The problem comes from here, line 116 of `csv/parser.csv` :

```rust
pub(crate) fn skip_header(input: &[u8], eol_char: u8) -> (&[u8], usize) {
    match next_line_position_naive(input, eol_char) {
        Some(mut pos) => {
            if input[pos] == eol_char {
                pos += 1;
            }
            (&input[pos..], pos)
        }
        // no lines in the file, so skipping the header is skipping all.
        None => (&[], input.len()), // <----------- This mess up the pointer, it is not related to input anymore
    }
}
```

It should be replaced by:

```
        None => (&input[input.len()..], input.len()), 
```

**Comment by ydarma** [comment]
Actually the first solution would also work because when there is no rows the `starting_point_offset` value is never used by the calling method `parse_csv` in `csv/read_impl.csv`: it leads to an empty `file_chunks` vec to iter on and `starting_point_offset` is used in the iteration. Thus, the value can be anything, it will work in release mode. But in some situation it will overflow in debug mode and panic. We must be able to work in debug mode, thus one of the solutions above should be applied.

**Comment by ydarma** [comment]
Or even

```rust
        let starting_point_offset = (bytes.as_ptr() as usize).overflowing_sub(starting_point_offset);
```

**Comment by ydarma** [comment]
The `starting_point_offset` value is meaningless when `bytes` is empty. Thus, I'll make a PR with a more "Rustic" solution:

```rust
let starting_point_offset = if bytes.len() > 0 {
    Some(starting_point_offset)
} else {
    None
};
```

and later:

```rust
let offset = read + starting_point_offset.unwrap();
```
