### ISSUE TITLE
group-by consistency issues

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4267]
`polars` supports three types of group-by aggregation functions for both `DataFrame` and `LazyFrame`, for a total of **6** distinct methods. 

- `DataFrame.groupby(...).agg(x)`
- `DataFrame.groupby_rolling(...).agg(x)`
- `DataFrame.groupby_dynamic(...).agg(x)`
- `LazyFrame.groupby(...).agg(x)`
- `LazyFrame.groupby_rolling(...).agg(x)`
- `LazyFrame.groupby_dynamic(...).agg(x)`

 These functions should be consistent in both the semantics of `x`, as well as the resulting output.

Consider the following (equivalent!) aggregation specifications

1. `x = [("b", "sum")]`
2. `x = [("b", ["sum"])]`
3. `x = {"b": "sum"}`
4. `x = {"b": ["sum"]}`
5. `x = [pl.col("b").sum()]`
6. `x = pl.col("b").sum()`

A user would reasonably expect all of these specifications to be valid inputs to all **6** group-bys. As of `polars==0.13.60`, this is not the case. In the following section, I will use "valid" to mean no error was thrown and "invalid" to indicate an error was thrown. "Correct" and "incorrect" will refer to the validity of the output. 

### `DataFrame.groupby`

- [ ] (1) **not annotated**, valid, correct
- [x] (2) annotated, valid, correct
- [x] (3) annotated, valid, correct
- [x] (4) annotated, valid, correct
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

This function is basically complete, although we can add `list[tuple[str, str]]` to the type annotation.

### `LazyFrame.groupby`

- [ ] (1) annotated, **invalid**, **incorrect**
- [ ] (2) annotated, **invalid**, **incorrect**
- [ ] (3) annotated, valid, **incorrect**
- [ ] (4) annotated, valid, **incorrect**
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

There is some work to be done here.

### `DataFrame.groupby_rolling`

- [ ] (1) **not annotated**, **invalid**, **incorrect**
- [ ] (2) annotated, **invalid**, **incorrect**
- [ ] (3) annotated, valid, **incorrect**
- [ ] (4) annotated, valid, **incorrect**
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

### `LazyFrame.groupby_rolling`

- [ ] (1) **not annotated**, **invalid**, **incorrect**
- [ ] (2) annotated, **invalid**, **incorrect**
- [ ] (3) annotated, valid, **incorrect**
- [ ] (4) annotated, valid, **incorrect**
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

These are the same issues as `DataFrame.groupby_rolling`

### `DataFrame.groupby_dynamic`

- [ ] (1) **not annotated**, **invalid**, **incorrect**
- [ ] (2) annotated, **invalid**, **incorrect**
- [ ] (3) annotated, valid, **incorrect**
- [ ] (4) annotated, valid, **incorrect**
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

Same problems as above

### `LazyFrame.groupby_dynamic`

- [ ] (1) **not annotated**, **invalid**, **incorrect**
- [ ] (2) annotated, **invalid**, **incorrect**
- [ ] (3) annotated, valid, **incorrect**
- [ ] (4) annotated, valid, **incorrect**
- [x] (5) annotated, valid, correct
- [x] (6) annotated, valid, correct

Same problems as above

**Comment by ritchie46** [comment]
This is very simple to fix. 1-4 should be deprecated. 

Those are remnants from before the expression API

**Comment by matteosantama** [comment]
Nice, that _is_ easy! I'll open an MR. Should I remove support for 1-4 entirely? Or do we need to follow a multi-release deprecation cycle?

**Comment by ritchie46** [comment]
We can remove it entirely. I want to push a 0.14 release anyway.
