### ISSUE TITLE
Int16 groupby doesn't operate expectedly

### ISSUE THREAD

**Issue by neeldug** [pola-rs/polars#4284]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

polars-0.13.61

#### What operating system are you using polars on?

MacOS 12.4 & Ubuntu 20.04

#### What language version are you using

Python 3.9.13

#### Describe your bug.

Unexpected grouping when performing groupby on `Int16` column.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [-1, -2, -3, -4, -5],
        "bar": [500, 600, 700, 800, 900]
    }
).lazy()

df = df.with_columns(
        [
            pl.col('foo').cast(pl.Int16),
            pl.col('bar')
        ]).groupby('foo').agg(pl.col('bar').median())

print(df.collect())
```

#### What is the actual behavior?

```
shape: (1, 2)
┌─────┬───────┐
│ foo ┆ bar   │
│ --- ┆ ---   │
│ i16 ┆ f64   │
╞═════╪═══════╡
│ -1  ┆ 700.0 │
└─────┴───────┘
```

#### What is the expected behavior?
Grouped across separate i16 values, i.e. provide 5 resultant rows.

**Comment by neeldug** [comment]
This bug also occurs with Int8 types too, but not Int32's/

**Comment by ritchie46** [comment]
Thanks. On it.
