### ISSUE TITLE
Able to add list of percentiles to df.describe()

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#4285]
It would be nice to add a list of percentile to report in df.describe()

for example, df.describe([0.25, 0.75]) reports

describe
str |
"mean" 
"std" 
"min"
"25%"
"median" 
"75%"
"max" 

If this is the df.describe default would be great.

**Comment by zundertj** [comment]
Hello, thank you for this request.

Please note that `describe` is just a short-hand iterating over the aggregation functions: https://github.com/pola-rs/polars/blob/093d55c6b4bed6b76f3d814e7e66030dac3c4f87/py-polars/polars/internals/frame.py#L2484 

You could thus simply create your own (note: not tested!):

```python
def describe(self, qs: list[float} | None = None):
  def describe_cast(self: DF) -> DF:
              ...
  
  stats = [self.mean(), self.std() ...]
  labels = ["mean", "std", ...]
  if qs:
     stats += [self.quantile(q) for q in qs]
     labels += [f"quantile{q}" for q in qs]

  summary = self._from_pydf(
              pli.concat([describe_cast(st) for st in stats]
              )._df
          )
  summary.insert_at_idx(
              0, pli.Series("describe", labels)
          )
  return summary
```

**Comment by leoliu0** [comment]
Thanks! This works great as temporary fix.

**Comment by MariusMerkleQC** [comment]
Are there any plans to add the `percentiles` argument to the `.describe()` function? This would be super helpful!

**Comment by zundertj** [comment]
See the `qs` input argument, that is the percentiles as fractions:

```python
df = pl.DataFrame(...)
describe(df, qs=[0.1, 0.25, 0.5, 0.75, 0.9])
```
