### ISSUE TITLE
Nicer handling of string literal arguments

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4288]
String literal arguments can be a source of bugs and friction. Consider the following behaviour currently in Polars:

```python
df = pl.read_csv('iris.csv', encoding='Utf8')
# RuntimeError: BindingsError: "encoding not Utf8 not implemented."
```

A few remarks:
* The user clearly meant to indicate `utf8`, but the call fails.
* The error type is a RuntimeError, which is not helpful (ValueError is a better indicator).
* The error doesn't help the user find the correct input value.
* A type checker won't help the user catch this, since the type is defined as a `str`

So I propose that we do the following for all user-facing string literal arguments:
* Use Literal types to facilitate type checking
  * Helps people catch these errors before running their code.
* Raise a `ValueError` when an unsupported value is supplied. Error message should include:
  * The literals accepted by the function
  * The value supplied by the user
* ~Use `.lower()` in the function body to reduce friction~ Will not be implemented. See Ritchie's comment below.

**Comment by ritchie46** [comment]
I agree with most points except for calling `.lower`

There should be only one correct argument and fuzzy matching is a slippery slope IMO. We could give an error that informs the user what the correct arguments are.

**Comment by stinodego** [comment]
Fair enough! I'll throw together a few PRs.

**Comment by stinodego** [comment]
Another thing I noticed here: some inputs get cast to a string on the Rust side, resulting in bad error messages.

```python
# BAD
pl.read_parquet('iris.parquet', parallel=pl.DataFrame)  # Throwing in a random non-string object
# ValueError: parallel must be one of {'auto', 'columns', 'row_groups', 'none'}, got <class 'polars.internals.frame.DataFrame'>
```
We should get a TypeError here, which we do get for some other string literals:

```python
# GOOD
pl.DataFrame({'a': [1,2,1]}).unique(maintain_order=True, keep=pl.DataFrame)
# TypeError: argument 'keep': 'type' object cannot be converted to 'PyString'
```

It's a simple fix; I will address this in the PR I am working on.
