### ISSUE TITLE
`DataFrame.select` should drop support for `Sequence[bool | int | float]`

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4291]
`DataFrame.select` is currently annotated by

```python
    def select(
        self: DF,
        exprs: (
            str
            | pli.Expr
            | Sequence[str | pli.Expr | bool | int | float | pli.Series]
            | pli.Series
        ),
    ) -> DF:
```

but it's unclear to me why we would want to support `Sequence[bool | int | float]`. The current behavior is

```python
df = pl.DataFrame({"a": range(5), "b": range(5)})

df.select([True])
>>> shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ true    │
└─────────┘

df.select([True, False])
>>> DuplicateError: Column with name: 'literal' has more than one occurrences
```

`int` and `float` have identical behavior. It seems we only support `Sequence[bool | int | float]` when the sequence is exactly one long. I think we should remove that annotation and require people to use the `Expr` API instead. 

We could even go so far as to require

```python
def select(self, exprs: pli.Expr | Sequence[pli.Expr]) -> DF:
```

as we did in #4283

**Comment by matteosantama** [comment]
For ergonomics, I could also see an argument for allowing raw strings too

```python
def select(self, exprs: str | pli.Expr | Sequence[str] | Sequence[pli.Expr]) -> DF:
```

**Comment by matteosantama** [comment]
For ergonomics, I could see an argument for supporting

```python
def select(self, exprs: str | pli.Expr | Sequence[str | pli.Expr]) -> DF:
```

**Comment by stinodego** [comment]
Feels more like we're not properly handling the default naming of newly created literal columns. Following logic, we should also not support `Sequence[pli.Expr]` because the following doesn't work:

```python
pl.select([pl.lit(True), pl.lit(False)])
# DuplicateError: Column with name: 'literal' has more than one occurrences
```


If we can manage to name these columns `literal_1`, `literal_2`, etc. this should work fine.

**Comment by matteosantama** [comment]
That's a good point, `select` is indeed broken with `Sequence[Expr]` as well. I think your suggestion of automatically creating `literal_1`, `literal_2`, etc. is a good one. 


I still think the function signature could use a clean-up though. Consider that for an argument `x` in `[str, Expr, Series]`,

```python
df.select(x) == df.select([x])
```

This is a very nice symmetry. It is not the case for `x` in `[int, bool, float]` though, ie.

```python
df.select(True) != df.select([True])
```

I think the best signature is

```python
def select(self, exps: str | Expr | Series | Sequence[str | Expr | Series]) -> DF:
```

(note that the sequence can be a mix of the three).

**Comment by ritchie46** [comment]
> Feels more like we're not properly handling the default naming of newly created literal columns. Following your logic, we should also not support `Sequence[pli.Expr]` because the following doesn't work:
> 
> ```python
> pl.select([pl.lit(True), pl.lit(False)])
> # DuplicateError: Column with name: 'literal' has more than one occurrences
> ```
> 
> If we can manage to name these columns `literal_1`, `literal_2`, etc. this should work fine.

But this does work:

```python
pl.select([pl.lit(True).alias("foo"), pl.lit(False).alias("bar")])
```

Not every expression combination is valid. But many are.

**Comment by matteosantama** [comment]
Right, both `Expr` and `Series` provide the user a way to set the column name. And you shouldn't need to set a column name if you pass a `str` (since you are already selecting a column). I stand by `str | Expr | Series | Sequence[str | Expr | Series]` as the appropriate type.

For a little context, this change is motivated by the fact that the `select` signature for [`DataFrame`](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/frame.py#L5180-L5188) and [`LazyFrame`](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/lazy_frame.py#L914-L917) are different. I'd like to unify them if we can agree on the correct annotation.

**Comment by ritchie46** [comment]
Right.. IMO it should still succeed with a value that is a valid argument to `pl.lit()`, but I don't think it should be in the type notation as I don't see it as idiomatic behavior. It breaks quite easily as you don't set the column names with `alias` that way.

So I agree. :)
