### ISSUE TITLE
Improve bug & issue report templates + add show_versions for bug reporting

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#4297]
### Summary

Steps to be taken:
- [x] add `show_versions` => #4367 
- [ ] release and wait for 2/3 weeks so hopefully a majority of users have it
- [ ] update issue template on GitHub

### Background / original post
(note: willing to do this myself for Python, but happy for others step in and do the work)

Background: we are currently seeing many new people reporting bugs and requesting features. To make the bug reports useful, we are requesting reporters to fill out a template. This does not always happen, for various reasons.

I think we can improve the templates in two ways that hopefully improves the quality of bug reports and feature requests.

First, by making the template a bit more rigid on stuff to be checked first, and use the new interactivity features of GitHub. Probably best way to demonstrate is to see the Pandas template: https://github.com/pandas-dev/pandas/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml 

Second,  by providing an additional function to cover the following and maybe more in the existing bug report template:

```
What version of polars are you using?
Replace this text with the version.

What operating system are you using polars on?
Replace this text with your operating system and version.

What language version are you using
ex: python 3.8, node 16, etc..
```

This can be done quite easily for Python by combining:
1. `pl.__version__`
2. `platform.platform`
3. `sys.version_info`
This saves reporters time, and it is easier to ask as maintainer for which information to be provided.

Obviously, this is not a new idea, Pandas has [show_versions](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.show_versions.html), and my proposal would be to have a similar `show_versions` function, and require the output of that to be provided in the bug report.

**Comment by ritchie46** [comment]
Yes, that would be great. Accumulated this can save a lot of time for all of us.

**Comment by alexander-beedie** [comment]
Good idea; one (tiny) suggestion - `sys.version` instead of `sys.version_info` (more compact, more info)  :)
```
> 0.14.0                                    # pl.__version__
> macOS-12.5-arm64-arm-64bit                # platform.platform()
> 3.9.7 (default, Mar  8 2022, 12:56:28)    # sys.version
  [Clang 13.0.0 (clang-1300.0.29.30)]
```
vs
```
> 0.14.0
> macOS-12.5-arm64-arm-64bit
> sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)    # sys.version_info
```
