### ISSUE TITLE
alternative to pandas iterrows

### ISSUE THREAD

**Issue by easella** [pola-rs/polars#4302]
Hello, I am using the python programming language. I was wondering if there is a polars alternative to the pandas iterrows function?

**Comment by leoliu0** [comment]
df.rows()

**Comment by zundertj** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

**Comment by easella** [comment]
thanks
