### ISSUE TITLE
Type hint for shift_and_fill doesn't include lists for fill_value

### ISSUE THREAD

**Issue by dgilman** [pola-rs/polars#4306]
#### What language are you using?

Python

#### What version of polars are you using?

polars==0.13.62

#### What operating system are you using polars on?

macos x 10.15.7

#### What language version are you using
python 3.9

#### Describe your bug.

shift_and_fill can be used with List columns and passed a Python list literal, e.g. `pl.col('a_list_col').shift_and_fill(1, [])` would replace gaps with an empty list object. However, the type hint is currently `fill_value: int | float | bool | str | Expr`.

Note that there are probably more places in the codebase where this behavior should be standardized, I just happened to run into this one.

**Comment by ritchie46** [comment]
Thanks. Could you make a PR?

**Comment by ritchie46** [comment]
fixed #4314
