### ISSUE TITLE
Improve `fill_null` usability

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4307]
The `strategy` argument for `fill_null` (or equivalently the `fill_value` argument for `Expr.fill_null`) tries to do too many things. We should have separate arguments for fill value and fill strategy.

Consider the following example:

```python
df = pl.DataFrame({'count': ['one', None, 'three']})
df.fill_null('two')
# ValueError: Strategy two not supported
```

We are currently trying to parse the `strategy` argument to try and detect certain strings. That means you cannot use those strings as a fill value. Which is strange. And most of all, it just doesn't make sense that the same argument is used to specify the fill value or a fill strategy.

I propose a function signature like this:

```python
    def fill_null(
        self,
        value: int | float | etc | None = None,
        strategy: Literal["backward", "forward", "etc"] | None = None,
        limit: int | None = None,
    ):
```

We would have to prohibit the user from specifying both value and strategy, which is easily done.

For reference, [pandas does this in the same way](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

I think we can do this in a non-breaking way, but I'd have to figure that out.

**Comment by ritchie46** [comment]
If we do this quickly we can include that in the next breaking release.

We could dispatch this entirely from the python side first and implement it better later.

A value can always be filled like this:

```python
pl.select([
   pl.lit(series).when(pl.col(..).is_null()).then(pl.col(..)).otherwise(value)
])
```

**Comment by stinodego** [comment]
I'll try to come up with a PR towards the end of today!
