### ISSUE TITLE
Remove deprecated functionality

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4308]
Since there is a new breaking release coming soon, that would be a good opportunity to get rid of some old code.

Here's a list of some deprecated stuff:

### Deprecated functions/methods

* `select_at_idx` (since version 0.10.20)
* `epoch_days`, etc deprecated in favor of `epoch` (since version 0.13.9)
* `and_time_zone`/`and_time_unit` in favor of `with_time_zone`/`with_time_unit`
* `DataFrame.to_csv`/`to_parquet`/etc deprecated in favor of `DataFrame.write_csv`/etc. _(since Mar 16, 2022, version 0.13.12)_
* `DataFrame.join` with `how=asof` deprecated in favor of `join_asof` _(since Feb 23, 2022)_

### Deprecated argument aliases
* `join/join_asof` have deprecated `df` in favor of `other` _(since June 30, 2022)_
* `hash_rows` have deprecated `k0`, `k1` etc in favor of `seed`, etc. _(since July 17, 2022)_

### Deprecated inner functionality
...

I can finish this later if desired. What is your stance on removing deprecated functionality?

**Comment by ritchie46** [comment]
> I can finish this later if desired. What is your stance on removing deprecated functionality?

Yes, I am for removing that. Everything can be removed except for `select_at_idx` that should be private.

**Comment by stinodego** [comment]
Okay, I'll set up a PR for this 👍

**Comment by ritchie46** [comment]
Great. I have merged the first breaking changes so we can do everything that hurts us now.

**Comment by stinodego** [comment]
The following still need to be removed:

* `DataFrame.select_at_idx`: You say this should become private, but actually there is nothing using this. Can't we just remove it?
* `Series.dt.to_python_datetime`: Deprecation message says to use `Series.to_list` instead, but I fail to see the relationship between these. How am I supposed to fix the breaking tests? There is also an `Expr` equivalent that is not deprecated.
* `DataFrame.__getitem__` should no longer support boolean masks: Deprecation message suggests to use `.filter` instead, but I don't see how I get equivalent results by using filter?
* `DataFrame.__setitem__`

**Comment by ritchie46** [comment]
> DataFrame.select_at_idx: You say this should become private, but actually there is nothing using this. Can't we just remove it?

Oh, right. Yes let's remove it.

> Series.dt.to_python_datetime: Deprecation message says to use Series.to_list instead, but I fail to see the relationship between these. How am I supposed to fix the breaking tests? There is also an Expr equivalent that is not deprecated.

This returns a `Series` with python datetime objects. This is really bad as we should not have python objects in polars. That's why a `to_list` call is better as that returns a python list with python objects.

Anyway. We should just remove it. :)

> DataFrame.__getitem__ should no longer support boolean masks: Deprecation message suggests to use .filter instead, but I don't see how I get equivalent results by using filter?

With #4335

```python
df = pl.DataFrame({
    "a": [1, 2, 3]
})
assert df.filter([True, False, True]).frame_equal(df[[True, False, True]])
```

**Comment by stinodego** [comment]
Great! I'll try to finish these later today, maybe tomorrow.
