### ISSUE TITLE
Get the difference sets of two dataframes

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#4313]
- with  pandas
```
pd.concat([df1, df2], axis=0).drop_duplicates(suset=['name1','name2'],keep=False)
```
- How to achieve the same function through polars?

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)

**Comment by ztsweet** [comment]
@ritchie46 I have posted the issue to stackoverfow.

**Comment by ritchie46** [comment]
Thanks.. can you post the link here?

**Comment by ztsweet** [comment]
@ritchie46 [how to get the difference sets of two polars dataframes](https://stackoverflow.com/questions/73273844/how-to-get-the-difference-sets-of-two-polars-dataframes)

**Comment by ztsweet** [comment]
@cbilot thanks!    :)
