### ISSUE TITLE
groupby_dynamic should default to closed = "left"

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#4319]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

'0.13.59'
#### What operating system are you using polars on?

MacOS

#### What language version are you using
python 3.8
#### Describe your bug.
For groupby_dynamic on time series the default should be `closed = 'left'` which is in line with Pandas and what you would expect.
#### What are the steps to reproduce the behavior?

```python
import polars as pl
import pandas as pd
df = pl.DataFrame(
         {"date": ["01-01-2021 00:00:00", "01-01-2021 23:58:00"], "values": [0.0, 1.0]}
    ).with_column(pl.col("date").str.strptime(pl.Datetime, fmt="%d-%m-%Y %H:%M:%S"))
dfPandas = df.to_pandas()
```
Then Polars default (closed = 'right') is:
```python
df.groupby_dynamic("date", every="1d").agg(
        [pl.col("values").sum().alias('sum'), pl.col("values").count().alias("ct")]
    )
shape: (2, 3)
┌─────────────────────┬─────┬─────┐
│ date                ┆ sum ┆ ct  │
│ ---                 ┆ --- ┆ --- │
│ datetime[μs]        ┆ f64 ┆ u32 │
╞═════════════════════╪═════╪═════╡
│ 2021-01-01 00:00:00 ┆ 0.0 ┆ 1   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2021-01-01 00:00:00 ┆ 1.0 ┆ 1   │
└─────────────────────┴─────┴─────┘
```
and Pandas default is:
```python

dfPandas.groupby(pd.Grouper(key="date", freq="1d")).count()
            values
date
2021-01-01       2
```
and you have to specify closed = 'right' to get the same as Polars
```python
dfPandas.groupby(pd.Grouper(key="date", freq="1d", closed="right")).count()
            values
date
2020-12-31       1
2021-01-01       1
```

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

Default should be `closed = "left"`

**Comment by cbilot** [comment]
The discussion in #3832 might be of interest.
