### ISSUE TITLE
Can't serialized a LazyFrame with fill_null, fill_nan, and apply

### ISSUE THREAD

**Issue by xdssio** [pola-rs/polars#4336]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?
yes

#### What version of polars are you using?

 polars-0.13.62

#### What operating system are you using polars on?

M1 mac

#### What language version are you using
python 3.7

#### Describe your bug.

When creating a lazy graph with the functions *fill_null*, *fill_nan*, or *apply*, and bring to serialise to json, we get **the enum variant Expr::AnonymousFunction cannot be serialized** error.

#### What are the steps to reproduce the behavior?
```
import polars as pl

l = pl.from_dict({'a':[1,None,3]}).lazy()

l.with_columns([pl.col('a').fill_null(0)]).write_json('test.json')

l.with_columns([pl.col('a').fill_nan(0)]).write_json('test.json')

l.with_columns([pl.col('a').apply(lambda x: x+1)]).write_json('test.json')
```

#### What is the actual behavior?

```
    self._ldf.to_json(file)
ValueError: Error("the enum variant Expr::AnonymousFunction cannot be serialized", line: 0, column: 0)
```

#### What is the expected behavior?

Just write it to json (:

**Comment by universalmind303** [comment]
This is not necessarily a bug, as some operations are not yet de/serializable. 

I would like to see more functions serializable as well. I'll take a look into serializing more exprs.

**Comment by ritchie46** [comment]
Yes me too. @universalmind303 it is transforming `AnonymousFunction` to `Function`.

An `apply` is something that's not yet possible and needs more work to figure out.

**Comment by universalmind303** [comment]
Just wondering, would it make sense to add operations to the plan & executors, or is converting to `Expr:: Function` enough?

**Comment by ritchie46** [comment]
> Just wondering, would it make sense to add operations to the plan & executors, or is converting to `Expr:: Function` enough?

`Exp:: Function` is enough. It let's us reuse a lot of code.

**Comment by ritchie46** [comment]
I will close this as this is known to use and under construction. Opening an issue for that is extra clutter on the board.
