### ISSUE TITLE
Over groups yields different result size for sorted and unsorted column

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#4345]
#### What language are you using?

 **Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.62

#### What operating system are you using polars on?

Description:    Ubuntu 20.04.3 LTS

#### What language version are you using
python 3.10

#### What are the steps to reproduce the behavior?

```python
import numpy as np
import polars as pl

size = 10000
df = pl.DataFrame({"a": np.random.randint(100, size = size), "b": np.random.randint(100, size = size)})
df = df.sort("b")
len(df.select(
    (pl.col("a") / pl.col("b")).over("b")
))
```

    100

#### What is the expected behavior?

```python
import numpy as np
import polars as pl

size = 10000
df = pl.DataFrame({"a": np.random.randint(100, size = size), "b": np.random.randint(100, size = size)})
# df = df.sort("b")
len(df.select(
    (pl.col("a") / pl.col("b")).over("b")
))
```

    10000

**Comment by mcrumiller** [comment]
I got the correct result polars 0.13.59, then upgraded to 0.13.62 and now I'm getting the same error, so there appears to be a regression.

**Comment by kdcd** [comment]
Thank you !
