### ISSUE TITLE
Issues when `offset_by` a negative year

### ISSUE THREAD

**Issue by Teamon9161** [pola-rs/polars#4353]
#### What language are you using?

**Python**.

#### What version of polars are you using?

0.14.0

#### What language version are you using
 python 3.8

#### What are the steps to reproduce the behavior?

```python
import polars as pl
from datetime import datetime
df = pl.DataFrame({'time': [datetime(2016, 6, 6, 6, 6, 6)]})
df
```

```python
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2016-06-06 06:06:06 │
└─────────────────────┘
```
```python
df.select(pl.col('time').dt.offset_by('-1y-1mo-1d-1h-1m-1s'))
```

#### What is the actual behavior?

```
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2015-07-05 05:05:05 │
└─────────────────────┘
```

#### What is the expected behavior?

2015-05-05 05:05:05

**Comment by matteosantama** [comment]
There's definitely something funky going on in `Duration::parse` which is responsible for turning the `by` string into a proper duration.

```python
In [3]: df.select(pl.col('time').dt.offset_by('-1y1mo1d1h1m1s'))
Out[3]: 
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2015-05-05 05:05:05 │
└─────────────────────┘

In [5]: df.select(pl.col('time').dt.offset_by('-1y1mo1d1h1m-1s'))
Out[5]: 
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2015-05-05 05:05:07 │
└─────────────────────┘
```

Its *almost* like the first negative sign is applied to the rest of the string, `"-1y1mo1d1h1m-1s" == "-(1y1mo1d1h1m-1s)"`. But this logic breaks down with 

```python
In [10]: df.select(pl.col('time').dt.offset_by('-1y1mo-1d1h1m-1s'))
Out[10]: 
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2015-05-05 07:07:05 │
└─────────────────────┘
```

I do wonder though, what is the rationale of introducing a custom string language here? Wouldn't it be cleaner to use proper parameters? On the Python side we'd have

```python
def offset_by(
    ns: int | None = None,
    us: int | None = None,
    ms: int | None = None,
    ...
):
```
and on the Rust side the `Duration` struct could be modified 

```rust
struct Duration {
    ns: i64,
    us: i64,
    ms: i64,
    ....
} 
```

I also would argue that having `Duration` accept an index count makes little sense, it is making the `Duration` struct do too much (it's a bit fishy that we re-use the `nsecs` field to hold the index count). `offset_by("2i")` should instead be expressed by `shift(2)`.

This issue could present a good opportunity to make deeper improvements to our handling of `Duration` arguments.

**Comment by ritchie46** [comment]
We should throw an error for that string. There should only be a single minus sign before the station. A duration as a whole can be negative, not it's sub-units.

> I do wonder though, what is the rationale of introducing a custom string language here? 

We use this string language on more places in the code bases and it provides an ergonomic/readable way to deal with many unit variants.

> Duration struct do too much (it's a bit fishy that we re-use the nsecs field to hold the index count). offset_by("2i") should instead be expressed by shift(2).

The duration is used by dynamic groupbys where it can make sense to define groups by integers. That we internally assign that to nsecs is an implementation detail that should not matter.

**Comment by matteosantama** [comment]
Ok, fair enough. Sounds like the only problem going on here is that we accepted an invalid string. I'll open an MR to disallow such strings.
