### ISSUE TITLE
Expose `date_format`, `time_format`, and `datetime_format` parameters to `DataFrame.write_csv`

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4362]
I notice that `CsvWriter` has a field of type `SerializeOptions`. `SerializeOptions` in turn supports

- `date_format`
- `time_format`
- `datetime_format`

I'd like to expose these parameters on the Python side in `DataFrame.write_csv`. We could additionally add support for `float_format` as requested in #4279 

@ritchie46 any objections?

**Comment by ritchie46** [comment]
> @ritchie46 any objections?

Nope, that would be great!

**Comment by alexander-beedie** [comment]
> I'd like to expose these parameters on the Python side in `DataFrame.write_csv`.
> We could additionally add support for `float_format` as requested in #4279

Spooky, I was thinking about doing something very similar, with one small addition:

Default datetime_format (on the Rust side) should really be per-timeunit (currently _always_ output `ns`):
* `ns >> "%S.%9f"`
* `us >> "%S.%6f"`
* `ms >> "%S.%3f"`

Then the python-side `datetime_format` param could EITHER be a single format string (in which case all datetime cols get that format) OR a {timeunit:format} dict (so you can override each individually if you want).

**Comment by matteosantama** [comment]
@alexander-beedie I think that's an awesome idea. 

Sounds like there's a few things we want to do, which should each have its own MR

- [ ] Expose pre-existing `datetime_format`, `date_format`, and `time_format` functionality on the Python side #4364 
- [ ] Enable more sophisticated `datetime_format` specifications
- [ ] Create a new `float_format` parameter
- [ ] Options for `null_value` and `empty_string` output.

I've just opened up an MR for (1), so you can build off that for (2). And then (3) and (4) can come when those are complete.

**Comment by alexander-beedie** [comment]
> I've just opened up an MR for (1)

Nice one; I'm off to Istanbul tomorrow for a few days (for the first time), so will dive-in properly once I get back :)

**Comment by alexander-beedie** [comment]
@matteosantama: well, got the [custom null_value](https://github.com/pola-rs/polars/pull/4714) in, and now [most](https://github.com/pola-rs/polars/pull/4724) of the way towards true per-unit datetime formats (will have see about refining that further some time).

Glad I could build off your work :)
