### ISSUE TITLE
Break up long modules

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4377]
Some of our modules are becoming extremely long. It's great that we are getting more functionality and more extensive docstrings, but my scrollwheel is just about to give out.

Some of the worst offenders are:
* `polars.internals.frame`: 6929 lines
* `polars.internals.series`: 5943 lines
* `polars.internals.lazy_frame`: 2606 lines
* `polars.internals.expr`: 7198 lines

I propose we split these up in modules, to give the various classes their own module. It would look something like:

```
polars
├── internals
│   ├── dataframe
│   │   ├── frame.py
│   │   ├── groupby.py
│   │   └── pivot.py
│   └── expr
│   │   ├── namespace
│   │   │   ├── categorical.py
│   │   │   ├── datetime.py
│   │   │   ├── list.py
│   │   │   ├── string.py
│   │   │   └── struct.py
│   │   └── expr.py
│   └── lazyframe
│   │   ├── frame.py
│   │   └── groupby.py
│   └── series
│   │   ├── namespace
│   │   │   ├── categorical.py
│   │   │   ├── datetime.py
│   │   │   ├── list.py
│   │   │   ├── string.py
│   │   │   └── struct.py
│   │   └── series.py
│   ...
...
```

Some of the benefits here:
* Fewer merge conflicts!
* Easier to find where you need to be, especially if you're less familiar with the code base.

As long as people import their stuff idiomatically (`from polars import pl`), this will not be a breaking change. If people were doing `from polars.internals.frame import DataFrame` then this will break their current flow, but I think in previous patches we were OK with that.

I haven't given much thought to the other modules, but we can probably improve there as well. I figured we could start here, if you guys agree!

**Comment by universalmind303** [comment]
💯 agree. I did a similar approach with the typescript bindings. _(which could probably even use some cleanup.)_
```
polars
├── cfg.ts
├── dataframe.ts
├── datatypes
│   ├── datatype.ts
│   ├── field.ts
│   └── index.ts
├── error.ts
├── functions.ts
├── groupby.ts
├── index.ts
├── internals
│   ├── construction.ts
│   └── polars_internal.ts
├── io.ts
├── lazy
│   ├── dataframe.ts
│   ├── expr
│   │   ├── datetime.ts
│   │   ├── index.ts
│   │   ├── list.ts
│   │   ├── string.ts
│   │   └── struct.ts
│   ├── expr.ts
│   ├── functions.ts
│   ├── groupby.ts
│   ├── index.ts
│   └── whenthen.ts
├── series
│   ├── datetime.ts
│   ├── list.ts
│   ├── series.ts
│   ├── string.ts
│   └── struct.ts
└── utils.ts
```

**Comment by ritchie46** [comment]
I agree that a separate module per logical class/groups is much better.

I also like flattened trees more as they are far more easily searchable. Shall we flatten the proposed `namespace` folders?

**Comment by stinodego** [comment]
> Shall we flatten the proposed `namespace` folders?

Sure, we could do that! I'll try to come up with a PR for this.
