### ISSUE TITLE
[>=0.14.0] .fill_null() in arr.eval causes internal error

### ISSUE THREAD

**Issue by MichalChromcak** [pola-rs/polars#4378]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.14.0

#### What operating system are you using polars on?

macOS Monterey 12.5

#### What language version are you using
python 3.9

#### Describe your bug.

since the `0.14.0` version, `.fill_null()` part of the `.arr.eval` function causes `internal error`

#### What are the steps to reproduce the behavior?

Installed polars with version 0.14.0 and run the code below.

#### What is the actual behavior?

```python
import polars as pl

last_non_null_value = pl.col("").fill_null("forward").last()

# create the dataframe
df = pl.DataFrame(
  {
    "array_cols":[[1, None]], 
  }
)

# get latest value from relevant columns
print(
  df.select(
    [
      pl.col("array_cols").arr.eval(last_non_null_value, parallel=True).alias("col_last")
    ]
  )
)
```
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /Users/runner/work/polars/polars/polars/polars-core/src/datatypes/mod.rs:871:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "~/bla.py", line 14, in <module>
    df.select([pl.col("array_cols").arr.eval(last_non_null_value, parallel=True).alias("col_last")])
  File "~/.venv/lib/python3.9/site-packages/polars/internals/frame.py", line 4801, in select
    self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)
  File "~/.venv/lib/python3.9/site-packages/polars/internals/lazy_frame.py", line 642, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: internal error: entered unreachable code
```

#### What is the expected behavior?

```
shape: (1, 1)
┌───────────┐
│ col_last  │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1]       │
└───────────┘
```

What do you think polars should have done?

**Comment by stinodego** [comment]
The `fill_null` function signature has changed in 0.14.0. See the docs https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.fill_null.html?highlight=fill_null#polars.Expr.fill_null.

You are trying to fill a column of type list[i64] with a string, which apparently results in the error you posted. Use the following instead:

```
last_non_null_value = pl.col("").fill_null(strategy="forward").last()
```

**Comment by stinodego** [comment]
After looking into this, it's more than just an uninformative error message. There is actually a bug going on here with using `fill_null` in the list namespace.

I worked it down to the following minimal example:
```python
df = pl.DataFrame({"a": [[1, None]]})
df.select(pl.col("a").arr.eval(pl.element().fill_null(3)).alias("result"))
# pyo3_runtime.PanicException: internal error: entered unreachable code
```

It works fine when specifying `fill_null(strategy="forward")`.
