### ISSUE TITLE
Combination of `drop_nulls` and `unique` causes segmentation faults in certain aggregations

### ISSUE THREAD

**Issue by JakobGM** [pola-rs/polars#4379]
#### What language are you using?

Python.

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

Version `0.14.0` and the current pre-release on PyPI.

#### What operating system are you using polars on?

MacOS ARM M1 / Ubuntu container.

#### What language version are you using

Python 3.9.

#### Describe your bug.

The following minimum code example causes a segfault:

```py
pl.DataFrame({"a": [None]}).groupby(["a"]).agg(pl.col("a").drop_nulls().unique().alias("b"))
```

In earlier versions of Polars this would result in:

```
>>> pl.DataFrame({"a": [None]}).groupby(["a"]).agg(pl.col("a").drop_nulls().unique().alias("b"))
shape: (1, 2)
┌──────┬────────────┐
│ a    ┆ b          │
│ ---  ┆ ---        │
│ f64  ┆ list [f64] │
╞══════╪════════════╡
│ null ┆ []         │
└──────┴────────────┘
```

**Comment by zundertj** [comment]
I can reproduce on

```
---Version info---
Polars: 0.14.0
Index type: UInt32
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.5 (main, Jul  8 2022, 14:32:56) [GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.0
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: 0.8

```
