### ISSUE TITLE
`test_scan_parquet_files` failing on `master`

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4381]
I see that `test_scan_parquet_files` is failing on one of my PRs. It seems to be failing on `master` as well. 

```
❯ git pull upstream master
From github.com:pola-rs/polars
 * branch                master     -> FETCH_HEAD
Already up to date.
❯ cargo t --all-features --test it
...
failures:
    io::parquet::test_scan_parquet_files

test result: FAILED. 135 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.10s
```

I will investigate the root cause, but in the meantime this issue can serve as a tracker.

**Comment by matteosantama** [comment]
Is anyone able to replicate this failure on their machine too?

**Comment by stinodego** [comment]
I can't even compile Polars when running that command 😅 

```
error: linking with `cc` failed: exit status: 1
```

**Comment by matteosantama** [comment]
@stinodego you get that error even if you're running it from `polars/polars`?

**Comment by stinodego** [comment]
> @stinodego you get that error even if you're running it from `polars/polars`?

Ah no, was running from root. Now I get the same test fail as you, on master.

**Comment by matteosantama** [comment]
Ah ok, I've made some progress. Notice that the test loads two files:

```rust
let files_to_load_set = vec![
    "../examples/datasets/foods1.parquet".to_string(),
    "../examples/datasets/foods2.parquet".to_string(),
];
```

On my machine, I only have that first parquet file in `polars/examples/datasets`. 

If I comment out the `foods2.parquet` line, the test fails when it hits the `assert_eq!` statement (whereas before it was erroring when constructing `df`).

**Comment by matteosantama** [comment]
The code that is responsible for generating `foods1.parquet` is [here](https://github.com/pola-rs/polars/blob/master/examples/read_csv/src/main.rs#L20-L32). I am unable to find any code that generates `foods2.parquet`. It's safe to say`test_scan_parquet_files` has a couple of issues:
1. It tries to read a file that doesn't exist
2. It is testing functionality of a deprecated function.

**Comment by ritchie46** [comment]
Am I correct we can close this @matteosantama?

**Comment by matteosantama** [comment]
Yes, I believe so. There's still a "problem" in that `test_scan_parquet_files` relies on files that may or may not exist (they are generated by a different set of tests). 

But the CI is passing, and at some point we will remove the deprecated functionality from the Rust side, which will include removing this test.
