### ISSUE TITLE
[BUG, already fixed?] `BooleanArray.all()` returns `false` if any of the underlying arrow chunks are empty.

### ISSUE THREAD

**Issue by jmrgibson** [pola-rs/polars#4383]
Bug report below, but it appears to have been fixed in more recent versions. I'm posting this here for posterity, because I just wasted half a day trying to figure out what was going wrong, hopefully others can find the issue and not waste as much time as me.

Is it worth yanking 0.20.0?  Or even just updating the rust changelog to note that 0.20.0 has a correctness bug?

Side note: The MSRV for versions after 0.20.0 is incorrect, and the lack of a rust-specific changelog beyond 0.16.0 made me waste much more time on this than I would have otherwise.

#### What language are you using?

**Rust**

#### Which feature gates did you use?

`features = ["abs", "dtype-i8"]`

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.20.0

#### What operating system are you using polars on?

Linux, x64

#### What language version are you using

Rust stable 1.59.0

#### Describe your bug.

`.all()` returns `False` even if all the values of `BooleanChunked` are `true`, if there are empty chunks in the `BooleanChunked`.

#### What are the steps to reproduce the behavior?

```rust
let arr: Float64Chunked = {
    let d = &[1.0, 1.0, 1.0];
    let d: Vec<_> = d.iter().map(|x| Some(*x as f64)).collect();
    d.iter().copied().collect()
};
let shifted = arr.shift(1);
let diff = shifted - arr;
let diff = diff.filter(&diff.is_not_null()).unwrap();
let changed = diff.equal(0i64);
// if you add `let changed = changed.rechunk()` here, the assertion passes
assert!(changed.all());  // should be true, but assertion fails without rechunking

```

#### What is the expected behavior?

`BooleanChunked.all()` should skip over empty chunks, and only return `false` if _all_ chunks are empty.

**Comment by ritchie46** [comment]
Sorry to hear you wasted time on this.

I don't think we should yank it
 Software has bugs and I'd recommend updating as we are improving rapidly. The amount of changes we make is a lot and I cannot keep up with the administrative burden of changelogs and update guides. I hope this changes in the future, but atm I spend most of my time on this and cannot keep up. I will close this as this is fixed.
