### ISSUE TITLE
Rows to schema DataFrame construction fails to infer fully `None` `List`

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars#4385]
#### What language are you using?

Python

#### Have you tried latest version of polars?

Yes (0.14.0)

#### What operating system are you using polars on?

macOS Monterey 12.5

#### What language version are you using

Python 3.10.4

#### Describe your bug.

Creating a `DataFrame` with a `list[dict[str, list]]` where the first row contains a `list` with only `None` values will result in what looks like failed inference for the remaining rows.

#### What are the steps to reproduce the behavior?

From kaster#9772 on Discord:

```py
df = pl.DataFrame([{'a': [None, None]}, {'a': [1, 2]}])
print(df)
# shape: (2, 1)
# ┌──────────────┐
# │ a            │
# │ ---          │
# │ list[i32]    │
# ╞══════════════╡
# │ [null, null] │
# ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ [null, null] │
# └──────────────┘
```

I've been able to spend some more time learning rust, so grokking the related code is much easier for me, but I'm still raw so I apologize if I'm missing something. Doing so I noticed that `Schema` is grabbed from the first row.

https://github.com/pola-rs/polars/blob/e8cb134ce686e2aa55645bbaa30203ea2802afec/polars/polars-core/src/frame/row.rs#L247

I also would think `rows_to_schema` never gets a chance to coerce the correct types for the remaining inference length since it's only matching on `DataType::Null` directly.

https://github.com/pola-rs/polars/blob/e8cb134ce686e2aa55645bbaa30203ea2802afec/polars/polars-core/src/frame/row.rs#L244-L274

Allowing for `List` to contain an integer seems to give it enough to infer the correct type.

```py
df = pl.DataFrame([{"a": [None, 1]}, {"a": [1, 2]}])
print(df)
# shape: (2, 1)
# ┌───────────┐
# │ a         │
# │ ---       │
# │ list[i64] │
# ╞═══════════╡
# │ [null, 1] │
# ├╌╌╌╌╌╌╌╌╌╌╌┤
# │ [1, 2]    │
# └───────────┘
```

#### What is the expected behavior?

Construct `DataFrame` without failure.

**Comment by cnpryer** [comment]
Curious if this would be useful here:

```py
df = pl.DataFrame(
    [{"a": [None, None]}, {"a": [1, 2]}], columns=[("a", pl.List(pl.Int32))]
)
```

Unfortunately it doesn't seem to have an effect.

**Comment by kastermight** [comment]
I believe types are inferred correctly. So though first row contains Nones only, type is still i32. Problem is non-None values are disregarded.

**Comment by kastermight** [comment]
@ritchie46 I don't think #4440 fixed this issue. I'm still getting `null` values after updating to 0.14.1.

**Comment by cnpryer** [comment]
You might need to wait for 0.14.2 or target `master` directly.
