### ISSUE TITLE
How can I join a groupby.agg dataframe into the source df

### ISSUE THREAD

**Issue by xiaolei-neu** [pola-rs/polars#4398]
just like the code

import polars as pl
df = pl.DataFrame(data={'column': ['a', 'a', 'b'], 'more': [1, 2, 3]}, columns=[('column', pl.Categorical), ('more', pl.Int32)])

q = (
    df
    .groupby("column").agg([
        (pl.col("more") +1).alias("new"),
    ])
)

df.join(q, on='column')

I got
column | more | new
-- | -- | --
cat | i32 | list[i32]
"a" | 1 | [2, 3]
"a" | 2 | [2, 3]
"b" | 3 | [4]

but I want get the data like this
column | more | new
-- | -- | --
cat | i32 | i32
"a" | 1 | 2
"a" | 2 | 3
"b" | 3 | 4

what's the reason?

**Comment by ritchie46** [comment]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Please use [stackoverflow](https://stackoverflow.com/) and one of the following tags:

* [python-polars](https://stackoverflow.com/questions/tagged/python-polars)
* [rust-polars](https://stackoverflow.com/questions/tagged/rust-polars)
* [nodejs-polars](https://stackoverflow.com/questions/tagged/nodejs-polars)

This allows us to create high quality answers that remain updated and will save us from
answering the same questions over and over again.

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.

#### Other

If your question doesn't fit stackoverflow, feel fry to ask here. :)
