### ISSUE TITLE
Use `rustfmt.toml` to improve Rust formatting

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4402]
I was looking into a way to better organize the Rust imports (they seem very messy to me), and apparently you can configure Rustfmt to organize imports just like `isort` would do for Python imports. See [here](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#group_imports).

```toml
# rustfmt.toml
group_imports = "StdExternalCrate"
```

I'm sure there are other nice improvements we can configure using the `rustfmt.toml` file. Any thoughts?

**Comment by ritchie46** [comment]
I think we should just keep the defaults. Then there is also nothing to discuss which is the entire goal of a formatterer as far as i am concerned. ^^

**Comment by stinodego** [comment]
> Then there is also nothing to discuss which is the entire goal of a formatter

I would say, that's the goal of an _opinionated_ formatter. In this case, the default formatter is not very opinionated on how to organize your imports. By default, it only sorts without the groups you create yourself. But that's a personal/stylistic _choice_, which can lead to discussion in code review. I could do something like this and it would be accepted by the formatter:

```rust
use crate::dataframe::PyDataFrame;

use crate::error::PyPolarsErr;

use crate::lazy::dataframe::PyLazyFrame;

use crate::prelude::*;

use crate::py_modules::POLARS;

use crate::series::PySeries;

// ...more imports separated by a blank line...
```

When this clearly isn't what we want. So we should use an opinionated formatter to help Rust noobs like myself properly organize their imports 😄

**Comment by ritchie46** [comment]
> When this clearly isn't what we want. So we should use an opinionated formatter to help Rust noobs like myself properly organize their imports smile

Al right, that's a good point. :thinking: I am just a bit scared that we will be discussing line lengths down the road. :see_no_evil: 

I agree that the imports may be more opinionated and are subjective to individual preferences, so let's go for your proposal.

**Comment by stinodego** [comment]
> I am just a bit scared that we will be discussing line lengths down the road. 🙈

Haha, don't worry. I actually really like the handling of line lengths for the Rust side. I read yesterday that we can mimic the same behaviour on the Python side by using [flake8-length](https://github.com/orsinium-labs/flake8-length). But that's a topic for a different time 😸 

Let's agree we keep the Rust formatter as default as possible, unless we run into specific issues where the formatter can help us.

I'll set up a PR with this grouped import sorting, you can take a look yourself if you like the results!
