### ISSUE TITLE
Dispatch everything to expressions

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4422]
A lot of DataFrame/LazyFrame/Series methods have an equivalent Expression. I believe we can leverage this to greatly reduce the 'footprint' of the Python bindings.

Instead of this:

```python
class DataFrame:
    def foo():
        return self._from_pydf(self._df.foo())

class LazyFrame:
    def foo():
        return self._from_pyldf(self._ldf.foo())

class Series:
    def foo():
        return wrap_s(self._s.foo())

class Expr:
    def foo():
        return wrap_expr(self._pyexpr.foo())
```

We should write this:

```python
class DataFrame:
    def foo():
        return self.select(pli.all().foo())

class LazyFrame:
    def foo():
        return self.select(pli.all().foo())

class Series:
    def foo():
        return self.to_frame().select(pli.col(self.name).foo()).to_series()

class Expr:
    def foo():
        return wrap_expr(self._pyexpr.foo())
```

Benefits:
* We only need to define the method once in the Rust bindings, instead of four times. This is the main benefit: smaller footprint, easier to maintain, fewer bugs.
* Our Python bindings can become very skinny, especially when using decorators, as showcased in #4423 
* ... that's it, really 😄 I'll add more if I think of them.

We're already doing this to a certain extent for many methods. I'm sure there's some quirks to work out for some of the other methods, but I think it would be good progress if we could better standardize this.

**Comment by ghuls** [comment]
This is done, no?

**Comment by stinodego** [comment]
I think it's mostly done. I'll probably take a look at this at some point again. For now let's close the issue.
