### ISSUE TITLE
Support for other encodings

### ISSUE THREAD

**Issue by sfanghaenel** [pola-rs/polars#4425]
Hello Polars Team,
first thanx for your nice Dataframe Libary.
How can i read a csv file with an other encoding (latin-1) into a Dataframe and work with such Data using polars? There is only support for utf8 and uft8-lossy (replace all non utf characters with the same symbol). 
Thanx and greatings Sven

**Comment by ritchie46** [comment]
This  is not something we will add in polars. We will only handle `utf8` complient encodings. However you can use the guest language to decode the bytes first into `utf8`. I am pretty sure this is what pandas does internally as well.

Here is an example in python: https://github.com/pola-rs/polars/issues/4363#issuecomment-1213086723

**Comment by ritchie46** [comment]
Maybe we could add this snippet to the `read_csv` implementation and document that if you choose a non-supported encoding we fallback to an in-memory decoding provided by python?

**Comment by ghuls** [comment]
> Maybe we could add this snippet to the `read_csv` implementation and document that if you choose a non-supported encoding we fallback to an in-memory decoding provided by python?

Working on it.

**Comment by sfanghaenel** [comment]
That sounds nice. Thanx

**Comment by ghuls** [comment]
https://github.com/pola-rs/polars/pull/4464

**Comment by ghuls** [comment]
Fixed in https://github.com/pola-rs/polars/pull/4464
