### ISSUE TITLE
 Big performance gap between `shift` and `shift_and_fill`

### ISSUE THREAD

**Issue by liaoliaopro** [pola-rs/polars#4431]
#### What language are you using?

Python

#### Have you tried latest version of polars?

- [yes]. 

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

v0.14.0

#### What operating system are you using polars on?

ubuntu20.04

#### What language version are you using

Python3.8

#### Describe your bug.

function `shift_and_fill` is slower  almost 100 times than `shift` for PySeries. 3 times for PyDataFrame.

#### What are the steps to reproduce the behavior?

Reproduce steps.

```python

In [49]: df = pl.DataFrame({'a':[1,2,3,4,5]})

In [50]: timeit df.shift(1)
53.8 µs ± 3.31 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [51]: timeit df.shift_and_fill(1,0)
172 µs ± 2.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [52]: timeit df.get_column('a').shift(1)
2 µs ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [53]: timeit df.get_column('a').shift_and_fill(1,0)
186 µs ± 2.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

#### What is the actual behavior?

see above

#### What is the expected behavior?

For the above 4 calls, I thought the speed of `shift` and `shift_and_fill` should be basically same. the DataFrame has only one Series.

**Comment by ritchie46** [comment]
We are comparing microseconds. Shift and fill has to do more work, it is expected to be slower. A shift is extremely cheap.

**Comment by ritchie46** [comment]
I did some local benchmarking on larger data so that the virtual function call overhead is not so much. The shift_and_fill is approx 20x slower. This is mainly because the filling is more expensive. We can speed that up a bit, but there is nothing out of the ordinary happening.

**Comment by liaoliaopro** [comment]
Great thanks for replying.  But I still have some questions:

1. `df.shift(1)` costs 53.8us, but `df.get_column('a').shift(1)` only costs 2us. The `df` has the only one column 'a' so they are basically same.  The `shift ` call from Series is much faster than from `DataFrame`.

2. I've roughtly checked the related underling Rust code in `shift.rs` and found function `shift` internally calls to `shift_and_fill` with argument `None`, i.e. `self.shift_and_fill(periods, None)`. In marcro `impl_shift_fill`, either with argument fill_value as `Some` or `None`, there is always a slice append operation. It seems the cost should be approximately equqal, I am not sure my understanding is correct.

Polars is really amazing and super fast. I'm thinking to use `Series` and function `shift` to implement an efficient ring buffer, and then the ring buffer can benefit for the compute kernel of Polars. Is this an appropriate way to do it?

Thanks for your time. 

------

ref https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/ops/shift.rs

``` rust
macro_rules! impl_shift_fill {
    ($self:ident, $periods:expr, $fill_value:expr) => {{
        let periods = clamp($periods, -($self.len() as i64), $self.len() as i64);
        let slice_offset = (-periods).max(0) as i64;
        let length = $self.len() - abs(periods) as usize;
        let mut slice = $self.slice(slice_offset, length);

        let fill_length = abs(periods) as usize;
        let mut fill = match $fill_value {
            Some(val) => Self::full($self.name(), val, fill_length),
            None => Self::full_null($self.name(), fill_length),
        };

        if periods < 0 {
            slice.append(&fill);
            slice
        } else {
            fill.append(&slice);
            fill
        }
    }};
}

impl<T> ChunkShiftFill<T, Option<T::Native>> for ChunkedArray<T>
where
    T: PolarsNumericType,
{
    fn shift_and_fill(&self, periods: i64, fill_value: Option<T::Native>) -> ChunkedArray<T> {
        impl_shift_fill!(self, periods, fill_value)
    }
}
impl<T> ChunkShift<T> for ChunkedArray<T>
where
    T: PolarsNumericType,
{
    fn shift(&self, periods: i64) -> ChunkedArray<T> {
        self.shift_and_fill(periods, None)
    }
}
```
