### ISSUE TITLE
Clarification in documentation on whether polars-rust can be used directly in async or not

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#4432]
I'm unsure myself but think it would be beneficial to include a small note in the documentation somewhere whether polars can be used directly in async contexts in rust or if it should be wrapped in `tokio::task::spawn_blocking` (when using tokio).

I think it could be beneficial to include something similar as `arrow2` in the readme or rust docs if it is possible to use in an async context, or to mention that it is not suitable to be used in an async context.
https://github.com/jorgecarleitao/arrow2/blob/9066298b531054ad7c0253827dd421797bf5684c/README.md
> Fully-decoupled IO between CPU-bounded and IO-bounded tasks, allowing this crate to both be used in async contexts without blocking and leverage parallelism

**Comment by ritchie46** [comment]
Arrow2 has both sync and an async API, so I understand that note in the docs.

We don't have an async API. Could you make a PR and add a section where you think this should be mentioned?

**Comment by SimonSchneider** [comment]
That's true, perhaps this is rather obvious, I was not aware that arrow2 had an async API. perhaps this is not needed.

**Comment by ritchie46** [comment]
Could you make a PR? I have no strong opinion here.
