### ISSUE TITLE
'pyarrow' is required when using from_arrow().

### ISSUE THREAD

**Issue by KeremAslan** [pola-rs/polars#4443]
#### What language are you using?

Python

#### Which feature gates did you use?

This can be ignored by Python & JS users.

#### Have you tried latest version of polars?
Yes, 0.14.1

#### What operating system are you using polars on?

MacOS M1 12.4

#### What language version are you using
Python 3.9.12

#### Describe your bug.

I want to read a large-ish table from Postgres RDS as per the examples in the docs:
```python
query = """
    SELECT *
    FROM <MY_TABLE>
"""
uri = "postgresql://username:password@server:port/database"

pl.read_sql(query, uri)  
```

I have installed polars via 

`pip3 install polars`

and  pyarrow via 

`pip3 install pyarrow`

The pyarrow version I have is `9.0.0`

#### What is the expected behavior?

Not raise this exception as PyArrow is installed.

**Comment by ritchie46** [comment]
Did you restart python/kernel?

**Comment by KeremAslan** [comment]
🤦  I re-imported a dozen times, but it didn't occur to me to restart the kernel. Much appreciated!
