### ISSUE TITLE
Integration with duckdb for SQL capabilities?

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#4452]
Hi Polars Team, 

Since Polars uses arrow as underlying, it should be easy to integrate with duckdb for extensive SQL capabilities.

Currently, one can do

```python
import duckdb
arrow_df = polars_df.to_arrow()
arrow_df2 = duckdb.query('''select * from arrow_df''').arrow()
polars_df2 = polars.from_arrow(arrow_df2)
```
Ideally one can do
```python
polars_df2 = polars.sql('''select * from polars_df''')
```

**Comment by alexander-beedie** [comment]
If you want to use duckdb/SQL on a polars frame, you just expose the frame data via `to_arrow()` and do pretty-much exactly what you demonstrate above. 

However, at that point you aren't actually _using_ polars - you're using duckdb and _its_ query engine, so it doesn't really make sense to make it _look_ like it's native to polars (which it isn't) via a dedicated method. And if you're really just using duckdb/SQL for your querying, I don't see that you gain anything by going back and forward between polars frames that you have to keep moving in/out of duckdb via arrow?

There have been some previous experiments in implementing a [polars-native](https://github.com/pola-rs/polars/tree/master/polars-sql) SQL interface, but I'm not sure how far along it is or whether it's going to end up production-ready anytime soon.

**Comment by leoliu0** [comment]
I see. Thank you.
