### ISSUE TITLE
polars v0.14.1 - TypeError: 'DataFrame' object does not support item assignment

### ISSUE THREAD

**Issue by irahorecka** [pola-rs/polars#4467]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

`polars==v0.14.1` does not support item assignment to a polars data frame. This assignment could be accomplished without exception in `polars==v0.13.62`. Please see example below.

### Reproducible Example

```python
import polars as pl

data = {"a": [1, 2], "b": [3, 4]}
df = pl.DataFrame(data)
# Works in polars==v0.13.62 and fails in polars==v0.14.1
df['index'] = range(2)
```

### Expected Behavior

I expect column 'index' to be introduced to `df` with row values 0 and 1, respectively.

### Installed Versions

<details>
---Version info---
Polars: 0.14.1
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:38)
[Clang 11.1.0 ]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.2
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
</details>

**Comment by ritchie46** [comment]
That is not a bug. That is intended. This is how you should assign:

```python
import polars as pl

data = {"a": [1, 2], "b": [3, 4]}
df = pl.DataFrame(data)

df.with_column(pl.arange(0, 2).alias("index"))
```

**Comment by irahorecka** [comment]
Got it - thanks for the clarification. Will close issue.

**Comment by ztsweet** [comment]
@ritchie46 
-  How can I correct this error
-  `polars==0.14.0`
```
df = pl.DataFrame({'n':[1,2,3,4]})
df[1,'n'] +=1
```
- TypeError: 'DataFrame' object does not support item assignment

**Comment by ritchie46** [comment]
> @ritchie46
> 
>     * How can I correct this error
> 
>     * `polars==0.14.0`
> 
> 
> ```
> df = pl.DataFrame({'n':[1,2,3,4]})
> df[1,'n'] +=1
> ```
> 
>     * TypeError: 'DataFrame' object does not support item assignment

See #4544. Will release today.
