### ISSUE TITLE
Cheap zip join

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#4471]
### Problem Description

Suppose I have two `pl.LazyFrame` with the same shape. Typically the way we merge them is by `frame1.join(frame2, on=[cols])`. This guarantees correctness join semantics, but there is another way of merging together these two frames by means of a [zip join](https://stackoverflow.com/questions/17581414/whats-a-zip-join-have-you-ever-heard-of-that-or-a-pairwise-join). If the user has put the time into sorting their data to the correct shape already, it's cheap to zip join (or horizontally concatenate, or hstack in `pl.DataFrame` land) two frames together. This would be great for prohibitively large datasets in which performing a hash join is both heavy on memory and compute, but the data is already aligned.

**Comment by matteosantama** [comment]
I would vote for adding a `LazyFrame.hstack` over `LazyFrame.join(..., how="zip")`. As you mentioned, that preserves symmetry with `DataFrame`.

**Comment by cbilot** [comment]
You can try the new [`with_context`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.with_context.html) function:
```python3
import polars as pl

df1 = pl.DataFrame({
    'col1': [1, 2, 3],
    'col2': [10, 20, 30],
}).lazy()

df2 = pl.DataFrame({
    'cola': ['a','b','c'],
    'colz': ['x','y','z'],
}).lazy()


(
    df1
    .with_context(df2)
    .select([
        pl.all()
    ])
    .collect()
)
```
```
shape: (3, 4)
┌──────┬──────┬──────┬──────┐
│ col1 ┆ col2 ┆ cola ┆ colz │
│ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64  ┆ i64  ┆ str  ┆ str  │
╞══════╪══════╪══════╪══════╡
│ 1    ┆ 10   ┆ a    ┆ x    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2    ┆ 20   ┆ b    ┆ y    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3    ┆ 30   ┆ c    ┆ z    │
└──────┴──────┴──────┴──────┘
```

**Comment by OneRaynyDay** [comment]
woah cool! `with_context` solves my problems :)
