### ISSUE TITLE
Is there setting to automatically cast a inf to nan option in polars?

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#4475]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73396321/is-there-setting-to-automatically-cast-a-inf-to-nan-option-in-polars

### Question about polars

We know in pandas, we can set
```python
pd.set_option('use_inf_as_na', True) 
```
to make sure inf is automatically cast to nan. Is there a similar option in polars?

**Comment by ritchie46** [comment]
Answered :+1:
