### ISSUE TITLE
Where can I find the release note of python-polars 0.14.2?

### ISSUE THREAD

**Issue by jheok318** [pola-rs/polars#4476]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Question about polars

Hello, polars team 😃 

I want to know what changed when it was updated from 0.14.1 to 0.14.2 version

The release note of rust can be found, but the release note of python cannot be found

**Comment by ritchie46** [comment]
Sadly we don't have any. We do (multiple) weekly release and I cannot keep up with the administrative load. We recently converted to conventional commits. So if I have more time, or somebody wants to pick it up, I want to write a tool that can create that automatically from our commit history.

**Comment by jheok318** [comment]
Thank you  for reply 😢
