### ISSUE TITLE
Deprecate `Python:acquire_gil` and use `Python::with_gil`.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#4478]
### Problem Description

Deprecate `Python:acquire_gil` and use `Python::with_gil` instead as PyO3 recommends this now:

https://github.com/PyO3/pyo3/pull/2549

**Comment by ghuls** [comment]
Working on it.

**Comment by ritchie46** [comment]
Awesome. I recall that we could not make all work without `Python::acquire_gil` when I tried that earlier. I wonder what the recommended approach for those cases is.

Let's first find out on which snippets that is the case, then we can ask a more useful question.

**Comment by ghuls** [comment]
The only issue I found is in `pub fn get_mmap_bytes_reader<'a>(py_f: &'a PyAny) -> PyResult<Box<dyn MmapBytesReader + 'a>> {
` as it returns multiple types.
