### ISSUE TITLE
Allow unbounded window in groupby_rolling and groupby_dynamic

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#4485]
### Problem Description

`groupby_rolling` and `groupby_dynamic` both require `period` and `every` is needed for `dynamic`. I was wondering if there were any performance concerns with allowing `period="all"` which means the window start bound never moves? If we run things like:

```
df.groupby_dynamic(ts, period="all").agg([pl.col("a").last().ewm_mean().alias("a")])
```

In addition, I think if we only get the `last()` value for example every ewm mean only needs to read the last element to update itself and we can make an additional optimization to not store the whole window in memory. If the window left bound is moving then we need to perform an adjustment on the ewm mean due to the first row being popped out, which means we can't perform said optimization.

**Comment by ritchie46** [comment]
Isn't that what ewm mean on the whole column already is?

**Comment by OneRaynyDay** [comment]
Discussed offline - `groupby_rolling` can be implemented largely by ewm_mean'ing on the whole column, but groupby_dynamic sliding windows can also move by uniform time windows. I think this could also be written by composing some groupbys and transformations of the timestamps to groups though, so I'm in favor of just closing this ticket for now. Sorry for the noise!
