### ISSUE TITLE
Groupby non-existent columns results in very strange/unexpected behavior

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#4488]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When aggregating a lazy dataframe with groupby on non-existent columns, polars just returns the original non-grouped dataframe.
The same operation would fail on an eager dataframe.

### Reproducible Example

```python
import polars as pl
import numpy as np
# Create a simple dataset on which we can reproduce the bug.
test_df = pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
}).lazy()
print(test_df.schema)
# {'foo': <class 'polars.datatypes.Int64'>, 'bar': <class 'polars.datatypes.Int64'>}
print(test_df.groupby("foo").agg(pl.col("bar").max().alias("max_bar")).schema)
# {'foo': <class 'polars.datatypes.Int64'>, 'max_bar': <class 'polars.datatypes.Int64'>}
print(test_df.groupby("asdf").agg(pl.col("bar").max().alias("max_bar")).schema)
# {'foo': <class 'polars.datatypes.Int64'>, 'bar': <class 'polars.datatypes.Int64'>}
```

### Expected Behavior

`test_df.groupby("asdf")` should fail since the column `"asdf"` does not exist.

### Installed Versions

<details>
polars v0.13.57 installed via conda
`pl.show_versions()` does not exist...
</details>

**Comment by ghuls** [comment]
Can you check the latest version first?

**Comment by Hoeze** [comment]
@ghuls Sorry my bad, I did run `mamba update polars` beforehand but I did not check whether it actually worked.
Turns out, 0.13.57 is the latest one I can install via conda:
https://github.com/conda-forge/polars-feedstock/issues/35

**Comment by ritchie46** [comment]
Those builds failed and are not directly maintained by us. The latest version is on pypi.

**Comment by Hoeze** [comment]
OK, I ran `PIP_NO_DEPS=1 pip install --upgrade polars` and I got `polars-0.14.2-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl` now:

```python
In [2]: pl.show_versions()
---Version info---
Polars: 0.14.2
Index type: UInt32
Platform: Linux-4.18.0-372.19.1.el8_6.x86_64-x86_64-with-glibc2.28
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.4.0
numpy: 1.22.2
fsspec: 2022.01.0
connectorx: <not installed>
xlsx2csv: <not installed>
```

Still, the above outlined behavior is the same.
=> The bug stays valid

PS:
@ritchie46 I saw you in the list of feedstock maintainers. Would it be possible for you to fix these build errors?
It's nearly impossible to use pip packages without destroying the whole environment...

**Comment by ritchie46** [comment]
> @ritchie46 I saw you in the list of feedstock maintainers. Would it be possible for you to fix these build errors?

Yes, but I don't know anything about that. I wish I had more time.

> It's nearly impossible to use pip packages without destroying the whole environment...

It should be fine. We have no required dependencies. ;)

Thanks for the issue report

**Comment by ghuls** [comment]
I think the build failure is caused by an non-nightly rust: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=547004&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1900

**Comment by ghuls** [comment]
With a bit of luck it might be fixed: https://github.com/conda-forge/polars-feedstock/pull/36
