### ISSUE TITLE
Make `pl.format(...)` consistent with python's `.format(...)` to use full f-string capabilities

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#4503]
### Problem Description

In plain python, one can use `0`, `1`, ... etc. in a strings formatting placeholder to use the usual formatting directives:

```python 
"{0:03d} - {1:.2f}".format(42, 99.123456)
# '042 - 99.12'
```

When I try replicating this in polars, it does not work as polars only seems to recognize un-formatted placeholders:
```python
df = pl.DataFrame({"a": [42], "b": [99.123456]})
df.select(pl.format("{0:03d}-{1:.2f}", "a", "b"))
# ValueError: number of placeholders should equal the number of arguments

# this works:
df.select(pl.format("{}-{}", "a", "b"))

# ┌──────────────┐
# │ a            │
# │ ---          │
# │ str          │
# ╞══════════════╡
# │ 42-99.123456 │
# └──────────────┘
```

If possible, I think it would be valuable to support the usual python formatting capabilities

**Comment by ghuls** [comment]
The formatting part happens in rust, not in python.

**Comment by ritchie46** [comment]
And the rust formatting engine only runs at compile time, meaning we should ship our own runtime f-string engine, which seems a bit much to me atm. Might reconsider this later if we are looking for things to do.

**Comment by moritzwilksch** [comment]
Ahh, I see, hadn't considered that. Thanks!

**Comment by vnijs** [comment]
+1 would be a great feature
