### ISSUE TITLE
Discussion: More ergonomic `DataFrame` type-casting?

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4505]
### Problem Description

I think `polars` could improve the way `DataFrame` columns are transformed to different types. In `pandas` one would use the `.astype` method

```python
pd.DataFrame({"a": [1.0]}).astype({"a": "float32"})
```

but accomplishing the same in `polars` requires many more keystrokes.

```python
pl.DataFrame({"a": [1.0]}).with_columns([pl.col("a").cast(pl.Float32)])
```

I propose adding a syntactic sugar `.cast` method

```python
def cast(self, **kwargs: dict[str, DataType]) -> DataFrame:
    columns = []
    for col in self.columns:
        if col in kwargs:
            dtype = kwargs[col]
            selection = pl.col(col).astype(dtype)
        else:
            selection = pl.col(col)
        columns.append(selection)
    return self.with_columns(columns)


pl.DataFrame({"a": [1.0]}).cast(a=pl.Float32)
```

Would such a function be well-received?

**Comment by matteosantama** [comment]
Or perhaps we allow a user to specify the `schema` when initializing the `DataFrame`

```python
pl.DataFrame({"a": [1.0]}, schema={"a": pl.Float32})
```

**Comment by ghuls** [comment]
Or just create your dataframes from Series and specify the dtype there:
```python
pl.DataFrame(
    [
        pl.Series("a", [1.0], dtype=pl.Float32),
    ]
)
```

**Comment by matteosantama** [comment]
Right, there are at least a few ways of assigning data types to columns. But my point is this is a common enough operation that it should be streamlined as much as possible. 

When I'm working with `pandas`, I frequently test out code snippets in the interpreter. The first step is almost always creating a toy `DataFrame` with appropriate types. In `polars`, this is a painfully verbose sequence of steps. 

You may think "Oh, we're only saving a few keystrokes", but we really shouldn't underestimate the usefulness/importance of an ergonomic API.

**Comment by ritchie46** [comment]
> ```python
> pl.DataFrame({"a": [1.0]}, schema={"a": pl.Float32})
> ```

We have exactly this, but it is called columns. 

```python
pl.DataFrame({"a": [1.0]}, columns={"a": pl.Float32})
```

> You may think "Oh, we're only saving a few keystrokes", but we really shouldn't underestimate the usefulness/importance of an ergonomic API.

I don't agree with saving keystrokes argument. I like code to be readable and explicit. I also don't want too many different ways to do something. If we would have a `cast` schema, you will likely not combine that with other expressions, meaning you miss out on parallelization possibilities.

**Comment by alexander-beedie** [comment]
I added types support to `columns` a few months back for most (all?) of the frame init methods - can pass either a  sequence or dict of `name:type` pairs (which also means you can pass a `df.schema` from a different frame straight in if you have one as a template).

Both forms are valid:
```python
df1 = pl.DataFrame({"a":[1.0]}, columns=[("a",pl.Float32)] )
df2 = pl.DataFrame({"a":[1.0]}, columns={"a":pl.Float64} )
```
Post-init, use of `with_columns` should be sufficient/clean.

**Comment by matteosantama** [comment]
> We have exactly this, but it is called columns.

Good enough for me!
