### ISSUE TITLE
Unexpected cast from date to int

### ISSUE THREAD

**Issue by abalkin** [pola-rs/polars#4518]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

`shift_and_fill` with `over` casts dates to integers

### Reproducible Example

```python
from datetime import date

import polars as pl

pf = pl.from_records(
        [ (date( 2001, 1, 2 ), 'A'),
          (date( 2001, 1, 3 ), 'A'),
          (date( 2001, 1, 4 ), 'A'),
          (date( 2001, 1, 3 ), 'B'),
          (date( 2001, 1, 4 ), 'B') ],
        columns = [ 'd', 's' ]
)
x = pf.select(
        pl.col( 'd' )
        .shift_and_fill( -1, pl.col( 'd' ).max() )
        .over( 's' )
)
print(x)
```

### Expected Behavior

Expected output of the program is

```
shape: (5, 1)
┌────────────┐
│ d          │
│ ---        │
│ date       │
╞════════════╡
│ 2001-01-03 │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2001-01-04 │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2001-01-04 │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2001-01-04 │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2001-01-04 │
└────────────┘
```

### Actual output

```text
shape: (5, 1)
┌───────┐
│ d     │
│ ---   │
│ i32   │
╞═══════╡
│ 11325 │
├╌╌╌╌╌╌╌┤
│ 11326 │
├╌╌╌╌╌╌╌┤
│ 11326 │
├╌╌╌╌╌╌╌┤
│ 11326 │
├╌╌╌╌╌╌╌┤
│ 11326 │
└───────┘
```

### Installed Versions

<details>
---Version info---
Polars: 0.14.2
Index type: UInt32
Platform: macOS-12.5-arm64-arm-64bit
Python: 3.9.7 (default, Aug 12 2022, 09:02:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.22.4
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: <not installed>
</details>

**Comment by ritchie46** [comment]
Thanks, fix coming up.
