### ISSUE TITLE
Housekeeping: Issues that can be closed

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4519]
### Problem Description

In the ever-waging battle to keep the number of issues low, I've compiled a list of issues that we might consider complete.

- https://github.com/pola-rs/polars/issues/1424
  - we recently did this, right?
- https://github.com/pola-rs/polars/issues/1010
  - `fast-float` is out, and until the stdlib supports fast float writing we will need to rely on `lexical`
- https://github.com/pola-rs/polars/issues/2956
  - question was answered, no follow-up for several months
- https://github.com/pola-rs/polars/issues/1621
  - question was answered, no follow-up for several months
- https://github.com/pola-rs/polars/issues/2288
  - mostly, if not totally, resolved in #2299
- https://github.com/pola-rs/polars/issues/2687
  - labeled `wontfix`
- https://github.com/pola-rs/polars/issues/3513
  - labeled `wontfix`

**Comment by ghuls** [comment]
Closed them all except https://github.com/pola-rs/polars/issues/2288

**Comment by matteosantama** [comment]
Great, thanks! I'll consider this closed then too
