### ISSUE TITLE
Wrong comparison method names in documentation

### ISSUE THREAD

**Issue by isaacthefallenapple** [pola-rs/polars#4521]
I don't use Polars but this came up on [SO](https://stackoverflow.com/questions/73434994/rust-polars-series-compare-to-scalar-not-working): The [docs for eager comparisons](https://github.com/pola-rs/polars/blob/91538f59a7f82a55af5d2eed96f4109e60a87744/polars/src/docs/eager.rs#L154) seem to be outdated, using `eq` and `neq` methods. I think the comparison operations are implemented in the `ChunkCompare` trait where they are called `equal` and `not_equal` respectively.

If someone who knows the crate better can confirm this, I'd be happy to look if anything else is out of date and submit a PR adjusting the docs.

**Comment by ritchie46** [comment]
> I'd be happy to look if anything else is out of date and submit a PR adjusting the docs.

That'd be great!
