### ISSUE TITLE
Printing a DataFrame containing Chinese shows an exception

### ISSUE THREAD

**Issue by SuperDaniel-cn** [pola-rs/polars#4529]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When my DataFrame contains Chinese characters, the result of calling the print function to print the DataFrame will display an exception

![Snipaste_2022-08-22_20-10-44](https://user-images.githubusercontent.com/27357588/185918125-07ed0b45-112b-4c31-af6b-806b9aac1bd7.jpg)

### Reproducible Example

```python
import polars as pl
data = {
    "company": ["蓝捷航空", "联合航空", "美国航空"],
    "on_time": [0.3 * 0.768, 0.32 * 0.715, 0.38 * 0.822],
    "later": [0.3 - 0.3 * 0.768, 0.32 - 0.32 * 0.715, 0.38 - 0.38 * 0.822],
}
data = pl.DataFrame(data)
result = data.with_column(
    data.select(
        pl.all().exclude("company")
    )
    .sum(axis=1)
    .alias("合计")
)
result.extend(
    result.select(
        [
            pl.lit("合计").alias("company"),
            (pl.all().exclude("company")).sum()
        ]
    )
)
print(result)
```

### Expected Behavior

I can also align grid lines when encountering Chinese, thanks

![Snipaste_2022-08-22_20-15-07](https://user-images.githubusercontent.com/27357588/185918841-bbf17201-494f-4911-94cb-fdb883cb14c1.jpg)

### Installed Versions

<details>
---Version info---
Polars: 0.14.4
Index type: UInt32
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 5.0.0
pandas: 1.4.3
numpy: 1.22.4
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: 0.8
</details>

**Comment by ghuls** [comment]
It works fine here (Linux, Gnome terminal). Unicode characters can have different widths and not all terminal emulators use the same. Probably there is an issue with Windows terminal font spacing for Unicode characters.
![image](https://user-images.githubusercontent.com/1299177/185922475-376148f8-8594-4068-a4a9-e24c742677c5.png)

Added an ascii first row to show that the chinese characters are wider than 1 ascii character (Linux
, wezterm):
![image](https://user-images.githubusercontent.com/1299177/185923087-c63de072-1779-4d3f-b3c1-dc38bb2cd346.png)

**Comment by SuperDaniel-cn** [comment]
> It works fine here (Linux, Gnome terminal). Unicode characters can have different widths and not all terminal emulators use the same. Probably there is an issue with Windows terminal font spacing for Unicode characters. ![image](https://user-images.githubusercontent.com/1299177/185922475-376148f8-8594-4068-a4a9-e24c742677c5.png)
> 
> Added an ascii first row to show that the chinese characters are wider than 1 ascii character (Linux, wezterm): ![image](https://user-images.githubusercontent.com/1299177/185923087-c63de072-1779-4d3f-b3c1-dc38bb2cd346.png)

@ghuls Thanks for the reply, I tried adding a line of ascii characters on Windows and it displayed fine. However, the Chinese characters are still displayed abnormally. I look forward to the development team to fix this problem, thank you again.


![Snipaste_2022-08-23_09-27-30](https://user-images.githubusercontent.com/27357588/186048101-c7b337a3-55c7-47dd-87ff-e0eca1d84fb7.jpg)

**Comment by ghuls** [comment]
It is not displaying fine. Your Chinese characters are not twice the size of an ascii char (extra `h` in my picture). Which application are you using?  Vscode or Windows terminal?

https://github.com/Microsoft/vscode/issues/14589

**Comment by SuperDaniel-cn** [comment]
> ‎它没有显示正常。你的中文字符不是ascii char的两倍（在我的图片中是额外的）。您使用的是哪个应用程序？Vscode还是Windows终端？‎`h`
> 
> [microsoft/vscode#14589](https://github.com/microsoft/vscode/issues/14589)

@ghuls I tested it on VSCODE, DataSpell, and Windows Terminal respectively. Only Windows Terminal is displayed normally, as shown in the following figure.

![vscode](https://user-images.githubusercontent.com/27357588/186066158-f678bb50-3f5d-4cdc-b0ba-1135c4f96cc4.jpg)

![DataSpell](https://user-images.githubusercontent.com/27357588/186066165-78b6d605-54f0-40ca-8742-143fd3b4af00.jpg)

![windowsterminal](https://user-images.githubusercontent.com/27357588/186066164-8c8f814d-60c4-449b-b9d6-4e5f54b5e201.jpg)

**Comment by ghuls** [comment]
Try to use a mono spaced font where the Chinese characters have a width of 2. Seems like Vscode does not want to solve the bug. It is a bug that needs to be solved in the terminal emulator, not in applications running in it. You can try this font as suggested in the Vscode bug report: http://levien.com/type/myfonts/inconsolata.html

**Comment by ghuls** [comment]
https://plugins.jetbrains.com/plugin/19665-pangu might help for dataspell, if I understand the description correctly.

**Comment by SuperDaniel-cn** [comment]
> Try to use a mono spaced font where the Chinese characters have a width of 2. Seems like Vscode does not want to solve the bug. It is a bug that needs to be solved in the terminal emulator, not in applications running in it. You can try this font as suggested in the Vscode bug report: http://levien.com/type/myfonts/inconsolata.html

@ghuls Thanks a lot, I finally solved the problem by installing the Inconsolata font. After installing the Inconsolata font under Windows, you need to restart DataSpell for normal display. I didn't restart DataSpell the first time I tried this solution, so I thought it didn't work, it actually solved the problem perfectly.
Thanks again~
![dataspellfont](https://user-images.githubusercontent.com/27357588/186102751-329c535d-7653-4bcf-ab8e-79b157d42444.jpg)

**Comment by SuperDaniel-cn** [comment]
> Try to use a mono spaced font where the Chinese characters have a width of 2. Seems like Vscode does not want to solve the bug. It is a bug that needs to be solved in the terminal emulator, not in applications running in it. You can try this font as suggested in the Vscode bug report: http://levien.com/type/myfonts/inconsolata.html

And It worked on VScode equally
![vscodefont](https://user-images.githubusercontent.com/27357588/186104448-e8570647-264c-45a9-958c-cbdfe4b6c960.jpg)

**Comment by ritchie46** [comment]
I will close this as the issue seems to be resolved and not something we can/should fix on our side.
