### ISSUE TITLE
Source package is missing on PyPi for 0.14.4

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#4536]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Source package is missing on PyPi for 0.14.4.
https://pypi.org/project/polars/0.14.4/#files

The source package is needed for the polars-feedstock build.

### Reproducible Example

```python
not applicable
```

### Expected Behavior

Source package available

### Installed Versions

0.14.4

**Comment by ritchie46** [comment]
Right.. there were problems with the build. I will see if I can do a new release with source.
