### ISSUE TITLE
Is Polars expected to be faster than Pandas on single core & relatively small data frames (<10k rows)?

### ISSUE THREAD

**Issue by jukiewiczm** [pola-rs/polars#4537]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Question about polars

Hello there,
Thank you for creating this high-potential very interesting library!

The question is already described in the title. I haven't found any direct answers to it, hence asking here.
I'm generally looking for a Pandas replacement that will be faster to use in a production setting, where I have to do many DataFrame-related transformations on the fly with relatively small DataFrames. Given the production server might require running several request simultaneously using a single machine, I'm generally interested in a single-core execution time, where the actual client requests will be parallelised and not the DataFrame processing itself (I can imagine parallelising both could end up in performance degradation).

Given Polars is written in Rust with just a Python package on top (speaking only from a Python's user perspective here, of course), and Pandas is generally Cython + Python (I think), I believe Polar might actually be faster in that setting.

I can obviously do some experiments and tests myself, and I will, but I was just curious about the contributors/experienced users opinion about the matter.

Thanks

**Comment by ritchie46** [comment]
For most operations, yes.

Polars has less RAM requirements, better string data structures, better hasher tables. 

Pandas makes a lot of internal copies, polars almost none. Polars has query optimization, pandas not. Polars has native IO readers that do not require external copies and we can MMAP arrow files.

**Comment by SimonSchneider** [comment]
We are using Polars in production and one of the usecases is to serve a dataAPI. Our request queries are of low-medium complexity (joins, groups, aggregations, filters) and are running on various size DFs (between 100s of rows and 50 columns to 100ks of rows and 1000s of columns). 

The server is built completely in Rust and we are seeing great performance without doing anything special to the parallelization of Polars. We are not serving very high load though, maybe a couple of requests per second and our response times are between about 5ms - 1s (p50~20ms, p95~700ms), this is however very query dependent so large grains of salt are implied…
I’m not sure what you’d see using Python but this is our experience using it in rust on 8core 32gb machines.

**Comment by ritchie46** [comment]
On thing to consider is setting polars thread pool size to something reasonable. Polars will only use the number of theads available in its thread pool. Multiple requests can share the same thread pool and help with load balancing the dataframe work.

**Comment by jukiewiczm** [comment]
Good news :)

Thank you! I guess I can close this one now as it's been answered, but if anyone has more feedback, feel free to keep posting!
