### ISSUE TITLE
Support for multi-byte quote_char

### ISSUE THREAD

**Issue by Indy2222** [pola-rs/polars#4546]
### Problem Description

We need to read a CSV which uses `⠿` (a braille character encoded with [3 bytes in UTF-8](https://util.unicode.org/UnicodeJsps/character.jsp?a=283F)) as `quote_char`.

**Comment by ghuls** [comment]
Multibyte quote characters are not supported.

Convert all your double quotes to escaped double quotes (`""`) and change ` ⠿` to `"`.
```
cat file.csv | sd '"' '""' | sd  '⠿' '"'
```
sd :https://github.com/chmln/sd

**Comment by Indy2222** [comment]
> Multibyte quote characters are not supported.
> 
> Convert all your double quotes to escaped double quotes (`""`) and change ` ⠿` to `"`.
> 
> ```
> cat file.csv | sd '"' '""' | sd  '⠿' '"'
> ```
> 
> sd :https://github.com/chmln/sd

The conversion is a bit more tricky in our case, since we are reading the content of a blob from Azure Blob Storage via its SDK. Obviously, it is still possible to "requote" the whole string but it increases the complexity on our side (especially due to speed requirements) and is tricky to do right (not all strings are necessarily quoted, etc.). Thus support for this in Polars would be greatly appreciated.

**Comment by ritchie46** [comment]
See discussion here #2728

**Comment by Indy2222** [comment]
> See discussion here #2728

Thanks.
