### ISSUE TITLE
ValueError: cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#4563]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

- When I use polars.series to convert to numpy array, the array elements cannot be modified, and the attributes cannot be modified

### Reproducible Example

```python
import polars as pl
import numpy as np
#
df = pl.DataFrame({'x':[1,2,3,4]})
x_array = df['x'].to_numpy()
x_array[1] += 1
# ValueError: assignment destination is read-only
x_array.flags.writeable = True
# ValueError: cannot set WRITEABLE flag to True of this array
y_array = np.array([1,2,3,4])
y_array[1] += 1
y_array.flags.writeable = True
# no errors occur
```

### Expected Behavior

-

### Installed Versions

<details>
polars == 0.14.5
numpy == 1.22.3
</details>

**Comment by ritchie46** [comment]
That's because numpy does not own the memory. It is a zero copy view of the arrow memory.

You can make a true copy if you want to own the memory:

```python
x_array = np.array(x_array)
```

**Comment by ghuls** [comment]
```python
In [47]: x = df.get_column("x").to_numpy(writable=True)

In [48]: x[1] +=1

In [49]: x
Out[49]: array([1, 3, 3, 4])
```
