### ISSUE TITLE
Incorrect type inference from csv file

### ISSUE THREAD

**Issue by luk-f-a** [pola-rs/polars#4567]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When importing a csv file, the types are inferred by the content. In this case, a column of float numbers, is being inferred as string.

Test file is attached: [float_csv_example.csv](https://github.com/pola-rs/polars/files/9424157/float_csv_example.csv)

### Reproducible Example

```python
import polars as pl
pl.read_csv("float_csv_example.csv").dtypes[-1]
```

### Expected Behavior

it should return `polars.datatypes.Float64`. Instead, it returns ` polars.datatypes.Utf8`
For reference, pandas.read_csv returns `dtype('float64')`

### Installed Versions

Test file: [float_csv_example.csv](https://github.com/pola-rs/polars/files/9424157/float_csv_example.csv)
 ```
---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---


pyarrow: 5.0.0
pandas: 1.3.4
numpy: 1.20.3
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>
```

**Comment by ritchie46** [comment]
The column has a trailing whitespace character. Which makes for an invalid float, thus the next supertype is a string. 

```python
shape: (1451,)
Series: '2058' [str]
[
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	...
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00 "
	"0.00"
]
```

**Comment by luk-f-a** [comment]
thanks for the explanation! I hadn't noticed the trailing whitespace. I guess pandas is following python `float` function, which allows `float("0.0 ")==0.0`, but that's of course a choice, not a bug.
