### ISSUE TITLE
from empty arrow converts list to string

### ISSUE THREAD

**Issue by c-meier** [pola-rs/polars#4568]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When creating a polars dataframe from an empty pyarrow table, columns with list type are converted to string type.

### Reproducible Example

```python
import pyarrow as pa
import polars as pl

# Create empty arrow table with a list column
arrow_df = pa.table(
    {"l": []}, 
    schema=pa.schema([
        ('l', pa.large_list(pa.uint8()))  # same thing with pa.list_
    ])
)

polars_df = pl.from_arrow(arrow_df)
assert isinstance(polars_df.schema['l'], pl.List), 'column is not converted to list'
```

### Expected Behavior

The type of the column should be the same whever the arrow table is empty or not.

Print of pyarrow table (with content) and it's polars dataframe:
```
pyarrow.Table
l: large_list<item: uint8>
  child 0, item: uint8
----
l: [[[3,5]]]
shape: (1, 1)
┌──────────┐
│ l        │
│ ---      │
│ list[u8] │
╞══════════╡
│ [3, 5]   │
└──────────┘
```

Print of pyarrow table (empty) and it's polars dataframe:
```
pyarrow.Table
l: large_list<item: uint8>
  child 0, item: uint8
----
l: [[]]
shape: (0, 1)
┌─────┐
│ l   │
│ --- │
│ str │
╞═════╡
└─────┘
```

Expected print of pyarrow table (empty) and it's polars dataframe:
```
pyarrow.Table
l: large_list<item: uint8>
  child 0, item: uint8
----
l: [[]]
shape: (0, 1)
┌──────────┐
│ l        │
│ ---      │
│ list[u8] │
╞══════════╡
└──────────┘
```

### Installed Versions

<details>

---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: Linux-5.19.3-arch1-1-x86_64-with-glibc2.36
Python: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>

</details>

**Comment by Ron-Ldn** [comment]
Hi, 
Please note that this also happens with dates (date type in pandas, pa.date32 in pyarrow).
Another way to produce the issue is by loading a parquet file using the "filters" option from pyarrow, when the filters actually return no data.
Thanks
