### ISSUE TITLE
Documentation uses "col" without mentioning how to get the function

### ISSUE THREAD

**Issue by lfrancke** [pola-rs/polars#4576]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

The documentation nowhere mentions the feature flags needed to actually get started using polars. It jumps straight into using "col" which is not available.

One seems to at least need the "lazy" flag but I'm not sure.
The docs also switch between polars::prelude and polars_core::prelude which is also something that's never mentioned anywhere.

### Reproducible Example

n/a

### Expected Behavior

n/a

### Installed Versions

n/a

**Comment by ritchie46** [comment]
Which part of the docs do you mean?

**Comment by lfrancke** [comment]
I can't find a reference _anywhere_.
The Getting Started guide for example: https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html
It mentions `cargo add polars` and then jumps right into something called `lazy polars` without ever explaining what that is and it uses the `col` function as well. None of that works without enabling at least one feature.

**Comment by lfrancke** [comment]
Sorry, I see now that I should have probably opened this in the other repository.

**Comment by lfrancke** [comment]
In favor of https://github.com/pola-rs/polars-book/issues/193
