### ISSUE TITLE
Multi-frame joins

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#4580]
### Problem Description

Currently `lazyframe.join()` allows us to join between two tables. It would be nice to allow the input to be a list of `pl.LazyFrame` which all share the same join columns (if there's multiple frames then `left_on` and `right_on` wouldn't make sense, but `on` would need to be specified).

This is useful when I distribute the query work by sharding across columns (while preserving some common index columns like timestamp) and I want to recombine the dataframe using a join. By allowing multiple frames to join simultaneously we can apply some optimizations i.e. hierarchical joining or simply keeping/updating the hash table around for sequential joins

**Comment by avimallu** [comment]
@stinodego, does https://github.com/pola-rs/polars/pull/8835 close this?

**Comment by stinodego** [comment]
I think so. If `concat(how="align")` does not solve the issue, please open a new issue with more details of what you are trying to achieve.

Thanks @avimallu for helping me keep up with all these issues!
