### ISSUE TITLE
scan_csv with n_rows and filter applies the filter before the n_rows check

### ISSUE THREAD

**Issue by indigoviolet** [pola-rs/polars#4608]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Perhaps related to #2417

If I do a `scan_{csv,ipc}` with `n_rows`, my expectation, backed by the documentation (`n_rows:: Stop reading from CSV file after reading n_rows.`) is that any filtering etc will happen after a "| head n_rows | " operation. But it seems that the filter happens during the scan, and so we can read n_rows matching the filter.

This leads to weird gotchas with `height` answers, for example, if you have an `n_rows` flag set and then try to estimate how many rows in the top N match some criterion.

### Reproducible Example

```python
import polars as pr
pr.Series("a", [0,1,2,3]).to_frame().write_csv("test.csv", )
pr.scan_csv("test.csv", n_rows=2).describe_optimized_plan()
'CSV SCAN test.csv; PROJECT 1/1 COLUMNS; SELECTION: None'

pr.scan_csv("test.csv", n_rows=2).collect()
shape: (2, 1)
+-----+
| a   |
| --- |
| i64 |
+=====+
| 0   |
|-----|
| 1   |
+-----+


pr.scan_csv("test.csv", n_rows=2).filter(pr.col("a") >= 2).describe_optimized_plan()
'CSV SCAN test.csv; PROJECT 1/1 COLUMNS; SELECTION: Some([(col("a")) >= (2i64)])'

pr.scan_csv("test.csv", n_rows=2).filter(pr.col("a") >= 2).collect()
shape: (2, 1)
+-----+
| a   |
| --- |
| i64 |
+=====+
| 2   |
|-----|
| 3   |
+-----+
```

### Expected Behavior

I expect

`pr.scan_csv("test.csv", n_rows=2).filter(pr.col("a") >= 2).collect()`

to return an empty data frame.

### Installed Versions

<details>

pr.show_versions()
---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.28
Python: 3.9.9 (main, Aug 25 2022, 19:32:03) 
[GCC 12.1.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.2
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>

</details>

**Comment by ghuls** [comment]
> Right.. I think we should block predicate pushdown if `n_rows` is set. There is not a way for us to have the information of the n-rows processed as we divide the work to several threads and don't want communication.

Could you not add a `.head(n)` node automatically after scan_csv when you detect a `n_rows` arg?

**Comment by ritchie46** [comment]
> Could you not add a `.head(n)` node automatically after scan_csv when you detect a `n_rows` arg?

Yep, but that would also block it right?

**Comment by ghuls** [comment]
Ah, true. If there is a way to keep track of the current row number for each filtered value (like an implicit `pl.row_nr` while doing the filter and running head afterwards to trim the results if necessary)?

**Comment by ritchie46** [comment]
> Ah, true. If there is a way to keep track of the current row number for each filtered value (like an implicit `pl.row_nr` while doing the filter and running head afterwards to trim the results if necessary)?

The hard pard is splitting up the bytes to the threads. We collect statistics to determine the no. of bytes per row. Take an upper boundary of that so that we take enough bytes.

Then we split the bytes per thread and finally collect the dataframes into a single one. That single one will have too many rows, so we slice it.

We could keep a counter per thread that keeps track of the rows before applying predicates. But then it still will be hard to know where to slice the final dataframe.

**Comment by indigoviolet** [comment]
Thanks. @ritchie46 this bug affects scan_ipc, and perhaps the other scans as well, I should have called it out more explicitly. Should this be renamed and left open?
