### ISSUE TITLE
df.frame_equal compares nans as unequal

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4610]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

See example below. nulls are equal, but nans are not.

### Reproducible Example

```python
import polars as pl, numpy as np

df = pl.DataFrame({"a": [1, 2, None]})
assert df.frame_equal(df, null_equal=True) # passes

df = pl.DataFrame({"a": [1, 2, np.inf]})
assert df.frame_equal(df, null_equal=True)  # fails
```

### Expected Behavior

I'd suggest adding an equivalent argument to `null_equal=True` of `nan_equal=True`.
I also checked `np.inf`, and it passes the assertion.

I ran into this while changing my code from an [inefficient pivot code to a much faster slice code](https://stackoverflow.com/questions/73522017/replacing-a-pivot-with-a-lazy-groupby-operation), when comparing the results using the old and new codes.

### Installed Versions

<details>
---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
</details>

**Comment by ritchie46** [comment]
We have `pl.testing.assert_frame_equal()` that has that option. I don't think it is a bug. A `NaN != Nan`.

**Comment by thomasaarholt** [comment]
Ok. There being two ways to check for this is a bit clunky, but I can see the argument.

I'm filling my nans with nulls before the comparison instead. :)
