### ISSUE TITLE
Allow fixed length windowed groupby operations

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#4622]
### Problem Description

Suppose we have the following timestamps with datapoints:

```
------t1 --------------- t2 ----- t3 --t4

Groupby dynamic:
| ----- |
        | ----- |
                | ----- |
                        | ----- |
                                | ----- |

Groupby rolling:
| ----- | 
                 | ----- |
                          | ----- |
                                | ----- |

Groupby row-wise fixed length:
...---- |                                                   
        | --------------- |
                          | ------ |
                                   | ---- |
```

The last one would be useful for things that involve a known window length beforehand. I could always convert the timestamp to a sequence of integers and groupby rolling on the integer instead with a window like `2i`, but it seems inefficient to have to create a new column just to do this (and also load the entire column into a list struct during the initial groupby). To do something like this currently, I have to:

```
# df has schema t = timestamp, b = grouping, a = numerical value.
exploded_df = (
    df.groupby("b")
    .agg(
        [
            pl.col("t"),
            pl.arange(0, pl.count()).alias("count"),
            pl.col("a"),
        ]
    )
    .explode(["t", "count", "a"])
)

# Example aggregation: shift every numerical value back 1 window
exploded_df.sort("count").groupby_rolling("count", by=["b"], period="2i").agg(
    [
        pl.col("t").last(),
        pl.col("a").shift(1).last(),
    ]
).drop("count")
```

Let me know if I misunderstood the existing groupby functionalities and whether I can do what I requested in the current framework easily :)

**Comment by cbilot** [comment]
Let me see if I can help.  There's a more elegant way to accomplish what you need, without the `explode`, `sort`, and `groupby` steps.
```python3
(
    df
    .with_column(pl.arange(0, pl.count()).over('b').alias('count'))
    .groupby_rolling('count', '2i', by='b')
    .agg([
        pl.col("t").last(),
        pl.col("a").shift(1).last(),
    ])
    .drop("count")
)
```

It does still require the creation of a temporary column, but it's less invasive to your code.

**Comment by cbilot** [comment]
I should note: `groupby_rolling` requires the data be sorted by the `index_column`, `count` in this case.  The algorithm above does not result in a DataFrame sorted by `count`, but rather sorted by `count` **within `b`**.  

That said, I think it's sufficient that `count` be sorted within the grouping variable `b`.

**Comment by OneRaynyDay** [comment]
Yup this works, thank you so much! I'll close the thread :)
