### ISSUE TITLE
Expression optimizer confused by `apply()´

### ISSUE THREAD

**Issue by MerlinDE** [pola-rs/polars#4627]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Executing an expression that does an `apply()` on a column and then does a calculation of that column with another one, results in an `Invalid Operation`.

### Reproducible Example

```python
bug = pl.DataFrame({
    "Amount": [10, 1, 1, 5],
    "Flour": ["1000g", "100g", "50g", "75g"]
})

### super simple version ###

# It fails with just a basic `apply()´
data = bug.lazy().select([
    pl.col("Amount"),
    pl.col("Flour").apply(lambda x: 100.0)/pl.col("Amount"),
]).collect()
print(data)

# and works with separated approach
data = bug.lazy().select([
    pl.col("Amount"),
    pl.col("Flour").apply(lambda x: 100.0),
]).collect()

data = data.lazy().select([
    pl.col("Flour")/pl.col("Amount")
]).collect()

### more complex real-life example ###

import polars as pl
import pint
from pint import UnitRegistry

ureg = UnitRegistry()
U = Unit = ureg.Unit
Q = Quantity = ureg.Quantity

c = pint.Context('dry_bulk', defaults={'density': 1.0})
c.add_transformation('[volume]', '[mass]', lambda ureg, x, density: x*density*ureg.kilogram/ureg.liter)
c.add_transformation('[mass]', '[volume]',
                     lambda ureg, x, density: x/(density*ureg.kilogram/ureg.liter))
c.add_transformation('[]', '[mass]', lambda ureg, x, density: ureg.Quantity("0 gram"))
c.add_transformation('[]', '[volume]', lambda ureg, x, density: ureg.Quantity("0 liter"))
ureg.add_context(c)

from unit_parse import parser


# This crashes with
# `data types don't match: InvalidOperation("division operation not supported for shape: (4,)\nChunkedArray: 'Flour' [str]\n[\n\t\"1000.0\"\n\t\"100.0\"\n\t\"50.0\"\n\t\"75.0\"\n] and shape: (4,)\nSeries: 'Amount' [str]\n[\n\t\"10\"\n\t\"1\"\n\t\"1\"\n\t\"5\"\n]")', /Users/runner/work/polars/polars/polars/polars-core/src/series/arithmetic/borrowed.rs:446:34`
#
data = bug.lazy().select([
    pl.col("Amount"),
    pl.col("Flour").apply(lambda x: parser(x).to("gram", 'dry_bulk', density=0.8).magnitude*1.0)/pl.col("Amount"),
]).collect()
print(data)

# Splitting the operation into two separate steps, makes it work.
data = bug.lazy().select([
    pl.col("Amount"),
    pl.col("Flour").apply(lambda x: parser(x).to("gram", 'dry_bulk', density=0.8).magnitude*1.0),
]).collect()

data = data.lazy().select([
    pl.col("Flour")/pl.col("Amount")
]).collect()
print(data)
```

### Expected Behavior

It shouldn't make any difference if I combine operations within a single `select()`. The expression optimizer should be able to handle even complex expressions including `apply()` and other re-arrangements of the source `DataFrame`.

### Installed Versions

<details>

Polars: 0.14.2
Index type: UInt32
Platform: macOS-12.5.1-x86_64-i386-64bit
Python: 3.10.5 (main, Jul 27 2022, 09:32:24) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
None

</details>

**Comment by zundertj** [comment]
Something seems to be off with the type inference. For the sake of completeness, the error message I get on the first example:

```
thread '<unnamed>' panicked at 'data types don't match: InvalidOperation("division operation not supported for shape: (4,)\nChunkedArray: 'Flour' [str]\n[\n\t\"100.0\"\n\t\"100.0\"\n\t\"100.0\"\n\t\"100.0\"\n] and shape: (4,)\nSeries: 'Amount' [str]\n[\n\t\"10\"\n\t\"1\"\n\t\"1\"\n\t\"5\"\n]")', <...>/polars/polars/polars-core/src/series/arithmetic/borrowed.rs:446:34
```

This can be easily solved by specyfing the `return_dtype` parameter in `apply`:
```python
bug.select(pl.col("Flour").apply(lambda x: 100.0, pl.Float64)/pl.col("Amount"))
```
What puzzles me is that the dtype is also Float64 on the following:
```python
>>> bug.select(pl.col("Flour").apply(lambda x: 100.0))
```

```
shape: (4, 1)
┌───────┐
│ Flour │
│ ---   │
│ f64   │
╞═══════╡
│ 100.0 │
├╌╌╌╌╌╌╌┤
│ 100.0 │
├╌╌╌╌╌╌╌┤
│ 100.0 │
├╌╌╌╌╌╌╌┤
│ 100.0 │
└───────┘

```

**Comment by cbilot** [comment]
Another observation that may help with debugging: there's no error if `apply` is used in the divisor:
```python3
bug.select(pl.col("Amount") / pl.col("Flour").apply(lambda x: 100.0))
```
```
shape: (4, 1)
┌────────┐
│ Amount │
│ ---    │
│ f64    │
╞════════╡
│ 0.1    │
├╌╌╌╌╌╌╌╌┤
│ 0.01   │
├╌╌╌╌╌╌╌╌┤
│ 0.01   │
├╌╌╌╌╌╌╌╌┤
│ 0.05   │
└────────┘
```

**Comment by ritchie46** [comment]
This is a result of increased polars strictness. Polars must know all data types statically. E.g. before running the code. This information will be used to optimize queries and cast dtypes so that operations can be performed. 

In this cases, the caller applies a custom function over a column of dtype `Utf8` and converts that column to dtype `Float64` without notifying polars of this change. This is a bug in the callers code. 

I shall ensure we check the dtype on and throw a more informative error.
