### ISSUE TITLE
read_excel(..., sheet_name=None) should return a dict of dataframes keyed by sheet name

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4631]
### Problem Description

Pandas allows the `sheet_name=None` argument, with the result returning a dictionary of dataframes, keyed by sheet:

```python
df = pd.read_excel("test_sheets.xlsx", sheet_name=None)
print(type(df))
print(df)
```
Output:
```text
<class 'dict'>
{'first':   Last_Name    First_Name    Birth_day   Age
0       Doe          Jane   1980-01-01    40
1     Smith          John   1970-01-01    50
2   Stevens   Christopher   1960-01-01    70,
'second':   Last_Name  First_Name  Birth_day   Age
0     Bluth     Jessica 1941-01-31    80
1     Bluth     Michael 1969-01-14    53
2     Funke      Tobias 1964-04-04    58}
```

Polars currently returns only the first sheet:
```python
df = pl.read_excel("test_sheets.xlsx", sheet_name=None)
print(type(df))
print(df)
```
Output:
```text
<class 'polars.internals.dataframe.frame.DataFrame'>
┌───────────┬──────────────┬─────────────┬──────┐
│ Last_Name ┆  First_Name  ┆  Birth_day  ┆  Age │
│ ---       ┆ ---          ┆ ---         ┆ ---  │
│ str       ┆ str          ┆ str         ┆ i64  │
╞═══════════╪══════════════╪═════════════╪══════╡
│ Doe       ┆  Jane        ┆  1980-01-01 ┆ 40   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ Smith     ┆  John        ┆  1970-01-01 ┆ 50   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ Stevens   ┆  Christopher ┆  1960-01-01 ┆ 70   │
└───────────┴──────────────┴─────────────┴──────┘
```

**Comment by zundertj** [comment]
I have created a PR, #4634, that adds support for this. Please note that it will require passing in `sheet_id=None` to make it work, as the default is 1, following `xlsx2csv`, the underlying library we use.

**Comment by mcrumiller** [comment]
It looks like, based on the logic in your PR, passing `sheet_id=0` would still return a dict of all sheets. Is that intended behavior?

**Comment by zundertj** [comment]
Yes, I am following the logic of the underlying library [xlsx2csv.convert](https://github.com/dilshod/xlsx2csv/blob/d0e7c8fd36cffc332ab8046d4d79895004051a29/xlsx2csv.py#L228)

**Comment by mcrumiller** [comment]
How would one request only the first sheet using `sheet_id`? Is this not possible?

**Comment by mcrumiller** [comment]
Ahh I see, I believe sheets are 1-indexed. This makes sense now.

**Comment by zundertj** [comment]
It has been a long time since I have been working on parsing the xml inside the .xlsx files, but if I recall correctly, there is no guarantee sheet_id's start at 1. If you create a new sheet, and delete others, applications do not have to re-index the sheets. I would recommend against using sheet id's for that reason, and always use names instead. We may want to tighten up the api on `read_excel` by dropping the `sheet_id` param, it would make things a bit cleaner.
