### ISSUE TITLE
ERROR: Could not build wheels for polars, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#4635]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/q/73549598/19715593

### Question about polars

- linux version

**

CentOS Linux release 7.9.2009 (Core)
Linux izbp12g7kz0m12ku1bqt45z 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**

- rust version

**
rustc 1.63.0 (4b91a6ea7 2022-08-08)

**

- python version 3.8 3.9 3.10

**Comment by ztsweet** [comment]
- Some errors have detailed explanations: E0432, E0554, E0599.

**Comment by ritchie46** [comment]
Could you try again? It should be resolved in latest release.

**Comment by ztsweet** [comment]
@ritchie46 thanks, Polars = = 0.14.7 has been installed normally
