### ISSUE TITLE
Shortcut for generating pl.Series with dtype pl.Date or pl.Datetime

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4651]
### Problem Description

Currently, to create a date-like series, you must do the following:

```python
dates = ["2022-01-01", "2022-01-02", "2022-01-03"]
date_series = pl.Series(dates).str.strptime(pl.Date, "%Y-%m-%d")
datetime_series = pl.Series(dates).str.strptime(pl.Datetime, "%Y-%m-%d")
```

It's a little verbose, and involves creating a string series, followed by conversion. Would it be possible to allow direct construction of a date or datetime series? Allowing `pl.Date` and `pl.Datetime` as the dtype during construction would be nice, as in:

```python
dates = ["2022-01-01", "2022-01-02", "2022-01-03"]
date_series = pl.Series(dates, dtype=pl.Date)
datetime_series = pl.Series(dates, dtype=pl.Datetime)
```

**Comment by alexander-beedie** [comment]
> Currently, to create a date-like series, you must do the following:

No, you can just instantiate directly from dates/datetimes  ;)

Either python-native...
```python
from datetime import datetime, date
import polars as pl
import numpy as np

pl.Series('dt',[date.today(),date.today(),date.today()])

# shape: (3,)
# Series: 'dt' [date]
# [
#     2022-09-02
#     2022-09-02
#     2022-09-02
# ]

pl.Series('dtm',[datetime.now(),datetime.now(),datetime.now()])

# shape: (3,)
# Series: 'dtm' [datetime[μs]]
# [
#     2022-09-02 07:43:31.091614
#     2022-09-02 07:43:31.091619
#     2022-09-02 07:43:31.091620
# ]
```
...or numpy-native:
```python
d = np.datetime64( datetime.today() )
pl.Series( np.array([d,d,d]) )

# shape: (3,)
# Series: '' [datetime[μs]]
# [
#     2022-09-02 07:52:19.776044
#     2022-09-02 07:52:19.776044
#     2022-09-02 07:52:19.776044
# ]
```

**Comment by mcrumiller** [comment]
Thanks Alex--was still hoping for a direct function from a list of ISO 8601-compliant strings, but I suppose numpy is the easiest way to go here, although a bit indirect.

**Comment by alexander-beedie** [comment]
I'm still a bit curious why you're having to deal with strings at all?
There might be a better option if I can see the use-case a bit more clearly.

**Comment by mcrumiller** [comment]
I can't quite say exactly why, I just notice that I often find myself creating Date series from arrays. If this isn't a common requirement I'm happy dealing with it on my own--no need to invest development effort to cater to one person.

**Comment by alexander-beedie** [comment]
> I can't quite say exactly why, I just notice that I often find myself creating Date series from arrays. If this isn't a common requirement I'm happy dealing with it on my own--no need to invest development effort to cater to one person.

No problem; the most common way to find yourself with date strings is via CSV data, but there are options to parse that when loading. Otherwise, taking advantage of numpy isn't a bad idea; `Series` was [recently updated](https://github.com/pola-rs/polars/pull/4473) to better-handle init from `np.datetime64`, so that should work well.
