### ISSUE TITLE
Panic/Error on sum_exprs

### ISSUE THREAD

**Issue by AnatolyBug** [pola-rs/polars#4659]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

Hello Polars Team,

When I sum two f64 expressions(of the same length, I am sure) with **sum_exprs** I get:

`ComputeError(
        "A 'map' functions output length must be equal to that of the input length. Consider using 'apply' in favor of 'map'.",
    ),`

When I add them using "+" operator, it panics:
`thread '<unnamed>' panicked at 'Cannot apply operation on arrays of different lengths', C:\Users\Anato\.cargo\registry\src\github.com-1ecc6299db9ec823\polars-core-0.23.2\src\chunked_array\arithmetic.rs:140:14
stack backtrace:`

### Reproducible Example

I could only reproduce the first Compute Error. (couldn't reproduce the panic). 

```
let df = df![
            "rf" => ["App", "App", "Gg"],
            "rft" => ["Spot", "Repo", "Spot"],
            "var" => [None, Some("Hello"), Some("World")],
            "dw" => [Some(1.), Some(2.), None],
            "rd" => [Some(4.), Some(5.), Some(6.)]
        ].unwrap();

let lf = df.clone().lazy()
    .groupby(&[col("rf")])
    .agg(&[sum_exprs(&[test1(), test2()]).first()] );
    let res = lf.collect();  
    dbg!(res) ;

fn test1() -> Expr {
    apply_multiple(
        move |columns| {
// Some heavy compute logic here
            Ok(Series::from_vec(
                "res",
                vec![10.; columns[0].len()] as Vec<f64>,
            ))
        },
        &[
            col("dw")
        ],
        GetOutput::from_type(DataType::Float64),
    )
}

fn test2() -> Expr {
    apply_multiple(
        move |columns| {
            Ok(Series::from_vec(
                "res",
                vec![100.; columns[0].len()] as Vec<f64>,
            ))
        },
        &[
            col("rd"),
        ],
        GetOutput::from_type(DataType::Float64),
    )
}
```

In my case, if I use an equivallent of  ` .agg(&[(test1()+test1()).first() ])` instead of ` .agg(&[sum_exprs(&[test1(), test2()]).first()] )` it panics. But it works in this simplified example. I couldn't figure out why. 

### Expected Behavior

I don't think we expect an error or panic on that example. I might be missing something though. 

A work around which seem to give expected result which I am using is:
```
fn test3() -> Expr {
    apply_multiple(
        move |columns| {
            let a = unsafe{columns.get_unchecked(0)};
            let b =  unsafe{columns.get_unchecked(1)};
            a.add_to(b)
        },
        &[
            test1(),
            test2()
        ],
        GetOutput::from_type(DataType::Float64),
    )
}
```
### Installed Versions

<details>
polars = {version = "0.23.2", features=["strings", "ndarray", "lazy", "is_in", "list", "dtype-categorical", "performant", "partition_by"]}
</details>

**Comment by ritchie46** [comment]
This seems to be fixed in master. Could you point to latest commit until we issue a new release?

**Comment by AnatolyBug** [comment]
> This seems to be fixed in master. Could you point to latest commit until we issue a new release?

Thanks @ritchie46 , will do!
