### ISSUE TITLE
Implement `.get_column()` for LazyFrames (i.e. Lazy Series)

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#4670]
### Problem Description

Sometimes there are situations in which a Series is needed rather than a DataFrame, such as when using `.is_in()` to compare columns in two different DataFrames.

In Lazy mode, this currently requires me to `.collect()` the desired column into a DataFrame and then use `.get_column()`.

It would be nice to have lazy access to individual columns as well, i.e. to have something like `LazySeries`.

**Comment by OneRaynyDay** [comment]
I'm not sure if this answers your question:

> when using .is_in() to compare columns in two different DataFrames.

I don't know what use case you're describing here, but a generic way to compare columns across multiple dataframes is by performing a join and then using `pl.col()` to select the columns from the left and right tables.

> It would be nice to have lazy access to individual columns as well, i.e. to have something like LazySeries.

`pl.col()` is a lazy expression representing a columnar series with homogenous type?

**Comment by ritchie46** [comment]
You must add a [context](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.with_context.html?highlight=with_context) if you want to access columns from another `LazyFrame`. 

There might be valid use cases, but for filtering this definitely is an antipattern. semi/anitjoins are highly performant and optimized for this purpose.

**Comment by YuRiTan** [comment]
I've tried to create an example on how to do the `.is_in()` lookup on two separate lazyframes. Does this help you?

```python
df = pl.DataFrame(
    {
        "a": [0, 1, 2, 3, 4],
        "b": [5, 6, 7, 8, 9],
        "c": [10, 11, 12, 13, 14],
    }
).lazy()
lookup = pl.DataFrame({"lookup": [1, 4]}).lazy()

(
    ldf
    .with_context(lookup)
    .with_column(
        pl.when(pl.col('a').is_in(pl.col("lookup"))).then("yeah").otherwise("boo").alias('is_in')
    )
).collect()
```

If not, can you maybe give an example?

**Comment by E-WebbV** [comment]
@YuRiTan 
Your example is close to something I'm trying to do. However, I want to return another column's value in the `.then` clause from the `lookup` table (let's call this column 'price'). In this way, I want to use the `lookup` column to match on records from the `a` column, then return the corresponding price. 

I've tried this by putting `pl.col('price')` in the `.then` clause, but I receive this error:
`ShapeError: shapes of `mask` and `other` are not suitable for `zip_with` operation`

Any help appreciated. Thanks.

**Comment by YuRiTan** [comment]
Hi @E-WebbV , 

The error means that the data frame column and lookup column do not have the same length. This is necessary when you want to fill the vale from the `pl.col('price')` in the `.then()` clause.

with equal lengths, it works:

```python
df = pl.DataFrame(
    {
        "a": [0, 1, 2, 3, 4],
        "b": [5, 6, 7, 8, 9],
        "c": [10, 11, 12, 13, 14],
    }
).lazy()
lookup = pl.DataFrame({"lookup": [1, 4, 5, 6, 7]}).lazy()

(
    df
    .with_context(lookup)
    .with_columns(
        pl.when(pl.col('a').is_in(pl.col("lookup"))).then(pl.col("lookup")).otherwise("boo").alias('is_in')
    )
).collect()
```
```
shape: (5, 4)
┌─────┬─────┬─────┬───────┐
│ a   ┆ b   ┆ c   ┆ is_in │
│ --- ┆ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ i64 ┆ str   │
╞═════╪═════╪═════╪═══════╡
│ 0   ┆ 5   ┆ 10  ┆ boo   │
│ 1   ┆ 6   ┆ 11  ┆ 4     │
│ 2   ┆ 7   ┆ 12  ┆ boo   │
│ 3   ┆ 8   ┆ 13  ┆ boo   │
│ 4   ┆ 9   ┆ 14  ┆ 7     │
└─────┴─────┴─────┴───────┘
```

But looking at what you're trying to do, is a join not what you're looking for? If not, could you please provide a minimal working example to show what you mean?

**Comment by stinodego** [comment]
Closing this as `Expr` is equivalent to a lazy Series and `LazyFrame.select` exists.
