### ISSUE TITLE
assert_series_equal() returns True when comparing null to non-null

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4671]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When comparing two series with the same dtype, `pl.testing.assert_series_equal()` returns True when one array contains a null value and the other does not.

### Reproducible Example

```python
import polars as pl

pl.testing.assert_series_equal(pl.Series([1,2,3]), pl.Series([1,None,None]))
```

Result: assertion passes

### Expected Behavior

AssertionError

### Installed Versions

<details>

---Version info---
Polars: 0.14.8
Index type: UInt32
Platform: Windows-10-10.0.22000-SP0
Python: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.4.1
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
pytz: 2022.1

</details>

**Comment by alexander-beedie** [comment]
Thanks; I'm taking a look
