### ISSUE TITLE
Implement method for retrieving a single row by predicate

### ISSUE THREAD

**Issue by JakobGM** [pola-rs/polars#4675]
### Problem Description

It is not uncommon that I see code along the lines of...

```py
important_row = df.filter(pl.col("table_id") == 42).row(0)
```

... that is, code that applies a filter to a dataframe which is supposed to yield one single row. If the given filter does _not_ result in a single row, something bad has happened and we want to interrupt the regular control flow. During code review I will often suggest the following guard logic...

```py
important_row = df.filter(pl.col("table_id") == 42).row(0)
if important_row.height != 1:
    raise RuntimeError("...")
```

... or something along those lines. But this quickly gets tedious and introduces a lot of generic boilerplate. It would be nice to have a method that allows users of polars to apply a filter predicate that should _always_ yield _exactly_ one row. If either zero or multiple rows match the given predicate, then the method should raise an exception.

This is in fact not a problem exclusive to the DataFrame domain, Django for instance has a `QuerySet.get()` method which does exactly this, just for a database query. It is documented [here](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#get). I have played around with the idea of implementing something similar for polars DataFrames. You can see the result of that [here](https://patito.readthedocs.io/en/latest/api/patito/DataFrame/get.html).

Another alternative implementation would be to allow `pl.Expr` as the input argument to `pl.DataFrame.row`. That would look like this:

```py
# This raises if some exception if no row has table_id == 42
important_row = df.row(pl.col("table_id") == 42)
```

You could either expand the function signature to `DataFrame.row(index: int | pl.Expr)` in order to not break backwards compatibility, or you could break compatibility and change the signature to the somewhat simpler `DataFrame.row(predicate: pl.Expr)` like `DataFrame.filter()`. The third option, as already mentioned, is to create an entirely new method.

Sorry in advance if this has already been implemented or discussed! Looking forward to hearing your thoughts ☺️

**Comment by dafardevloper** [comment]
A very simple workaround, see if it suits your requirement

```python
import polars as pl

df = pl.DataFrame(
    {
        "a": [1, 3, 5],
        "b": [2, 4, 6],
    }
)

print(df)

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 6   │
└─────┴─────┘

df = df.with_row_count()

print(df)

shape: (3, 3)
┌────────┬─────┬─────┐
│ row_nr ┆ a   ┆ b   │
│ ---    ┆ --- ┆ --- │
│ u32    ┆ i64 ┆ i64 │
╞════════╪═════╪═════╡
│ 0      ┆ 1   ┆ 2   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1      ┆ 3   ┆ 4   │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2      ┆ 5   ┆ 6   │
└────────┴─────┴─────┘

important_row = df.filter(pl.col("row_nr") == 1)

print(important_row)

shape: (1, 3)
┌────────┬─────┬─────┐
│ row_nr ┆ a   ┆ b   │
│ ---    ┆ --- ┆ --- │
│ u32    ┆ i64 ┆ i64 │
╞════════╪═════╪═════╡
│ 1      ┆ 3   ┆ 4   │
└────────┴─────┴─────┘

important_row = important_row.drop("row_nr")

print(important_row)

shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 3   ┆ 4   │
└─────┴─────┘
```

**Comment by JakobGM** [comment]
> A very simple workaround, see if it suits your requirement [...]

Hmmm, I think I'm having some trouble understanding how your proposed solution is solving the problem at hand 🤔 What I'm proposing is a single method that raises if the provided filter does not match one and exactly one row. Your code simply selects a single row by its row number, but what I propose is a method that accepts an arbitrary logical predicate in the form of `pl.Expr` 😅

**Comment by thomasaarholt** [comment]
I like this, and would use it too.

Numpy has something similar, for extracting scalar values as a Python type from n-dimensional arrays with a single entry:
```python
In [1]: import numpy as np

In [2]: arr = np.array([[42]]); arr.item()
Out[2]: 42

In [3]: arr = np.array([42, 43]); arr.item()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 arr = np.array([42, 43]); arr.item()

ValueError: can only convert an array of size 1 to a Python scalar
```

For your suggestion involving `df.row(pl.col("table_id") == 42)`, this should also raise an exception if there are two or more rows that satisfy that condition, right? I quite like both your solutions, to be honest.

What about letting `df.row()` (no argument passed) return the row (raising an error unless there is exactly one row)?

**Comment by JakobGM** [comment]
> For your suggestion involving df.row(pl.col("table_id") == 42), this should also raise an exception if there are two or more rows that satisfy that condition, right?

Yes, correct :relaxed: A predicate that yields zero rows should raise one exception, let's say `ZeroRowsException`, and a predicate that yields _multiple_ rows should raise another exeption, let's say `MultipleRowsException`. Both `ZeroRowsException` and `MultipleRowsException` should inherit from the same base exception, for example `GetException`, such that a user that doesn't need to distinguish between the two cases can catch both with a single exception class.

It could be used like this:

```py
try:
	row = df.row(predicate)
except pl.MultipleRowsException:
	print("Multiple rows yielded from predicate filter")
except pl.ZeroRowsException:
	print("Zero rows yielded from predicate filter")
```

Or this:
```py
try:
	row = df.row(predicate)
except pl.MultipleRowsException:
	print("Not exactly one row yielded from predicate filter")
```

> What about letting df.row() (no argument passed) return the row (raising an error unless there is exactly one row)?

Yes, that is actually how Django's `QuerySet.get()` method handles it (and `patito.DataFrame.get()`) as well! The following...

```py
df.filter(predicate).get()
```

... is equivalent with...

```py
df.get(predicate)
```

**Comment by dafardevloper** [comment]
Just use polars.DataFrame.height

if height is > 1, break your code, why should there be an error raised? 
in case the filter returns an empty dataframe there can be an error implemented as operating on an empty dataframe is a waste that can be avoided but why implement an error for more than 1 result?

well, the dev team will decide.

**Comment by universalmind303** [comment]
would something like this work?

```py
df = pl.DataFrame({
  'a': [1,2,3,4],
  'b': [True, False, True, False],
  'c': ['foo', 'bar', 'foo', 'bar'],
})

df.filter((pl.col('a') <= 2)).select([
    pl.all().first(), 
    (pl.count() == 1).alias('count_eq_1'),
])

shape: (1, 4)
┌─────┬──────┬─────┬────────────┐
│ a   ┆ b    ┆ c   ┆ count_eq_1 │
│ --- ┆ ---  ┆ --- ┆ ---        │
│ i64 ┆ bool ┆ str ┆ bool       │
╞═════╪══════╪═════╪════════════╡
│ 1   ┆ true ┆ foo ┆ false      │
└─────┴──────┴─────┴────────────┘
```

then you can handle the case where `count_eq_1` is false

you could even build a reusable utility function for this use case. 

```py
def get_or_throw(df: pl.DataFrame, predicate): 
    df = df.filter(predicate).select([
        pl.all().first(), 
        (pl.count() == 1).alias('predicate'),
    ])
    if df.get_column('predicate').n_unique() != 1:
        raise Exception('Predicate not unique')
        
    else: 
        return df.drop('predicate')

get_or_throw(df, pl.col('a') == 1)
```

**Comment by JakobGM** [comment]
> @universalmind303 would something like this work? [...]

Just to make my intent here a bit clearer, I'm already well aware how to implement this functionality, I have done so [here](https://github.com/kolonialno/patito/blob/8fcccae863f4488b75306550a238ad88990071e3/src/patito/polars.py#L501-L581) :relaxed:  This issue is mainly intended as a proposed feature request, since the pattern I have explained in the original issue description is so useful that I want to argue for it being "pushed upstream" into polars itself.

That aside, your implementation does more work than it needs to, it can be simply formulated as:

```py
def get_or_throw(df: pl.DataFrame, predicate): 
    df = df.filter(predicate)
    if df.height != 1:
        raise Exception('Predicate not unique')
    return df
```

The main difference with your implementation is that it returns a dataframe of height 1 rather than a row tuple (which we might consider as the final API, but is not what I originally proposed). There are other differences as well, you can take a look at my proposed reference implementation [here](https://github.com/kolonialno/patito/blob/8fcccae863f4488b75306550a238ad88990071e3/src/patito/polars.py#L501-L581) if you are interested.

**Comment by alexander-beedie** [comment]
@JakobGM; makes sense to me; created a PR for it: #4785. Took the least-intrusive approach for integrating into the API by overloading the `row()` signature, and also segregated the potential exceptions, as suggested. Should be good?

**Comment by JakobGM** [comment]
> @JakobGM; makes sense to me; created a PR for it: #4785. Took the least-intrusive approach for integrating into the API by updating `row`, and segregated the potential exceptions as suggested. Should be good?
> 
> ```python
> df.row( by_predicate=(pl.col("id") == 999) )
> ```

Thanks a lot, @alexander-beedie, much appreciated :bow:
