### ISSUE TITLE
Timestamp with timezone doesn't work properly with to_pandas

### ISSUE THREAD

**Issue by jingfeijia-tsy** [pola-rs/polars#4679]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

to_pandas function doesn't convert the timestamp with timezone correctly.

### Reproducible Example

```python
import polars as pl
import pandas as pd
df = pl.from_pandas(pd.DataFrame(data={"t": pd.to_datetime(["2020-01-01 00:00:00"])}))
df = df.with_column(df["t"].dt.with_time_zone("America/New_York"))
print(df)
print(df.to_pandas())

========================================
shape: (1, 1)
┌────────────────────────────────┐
│ t                              │
│ ---                            │
│ datetime[ns, America/New_York] │
╞════════════════════════════════╡
│ 2020-01-01 00:00:00 EST        │
└────────────────────────────────┘
========================================
                          t
0 2019-12-31 19:00:00-05:00
```

### Expected Behavior

We expect the output to be
```
========================================
shape: (1, 1)
┌────────────────────────────────┐
│ t                              │
│ ---                            │
│ datetime[ns, America/New_York] │
╞════════════════════════════════╡
│ 2020-01-01 00:00:00 EST        │
└────────────────────────────────┘
========================================
                          t
0  2020-01-01 00:00:00-05:00
```

### Installed Versions

<details>

---Version info---
Polars: 0.14.8
Index type: UInt32
Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>
pytz: 2022.2.1
</details>

**Comment by ritchie46** [comment]
This seems to be a bug in `pyarrow`.

```python
>>> tbl = df.to_arrow()
pyarrow.Table
t: timestamp[ns, tz=America/New_York]
----
t: [[2020-01-01 00:00:00.000000000]]
>>> tbl.to_pandas()["t"]
0   2019-12-31 19:00:00-05:00
Name: t, dtype: datetime64[ns, America/New_York]
```

**Comment by erinov1** [comment]
I think this is a bug if the user expects this particular usage of `with_time_zone` to behave like pandas `tz_localize("America/New_York")` (which is what I would expect). Arrow stores a timezone attribute, but always displays the corresponding UTC time. The usage of `with_time_zone` appears to be behaving like Arrow when casting a timestamp object without a timezone attribute to one with a timezone attribute (but this is not very useful for correct conversions between tz-aware and tz-naive datetimes or between timezones).

**Comment by sm-Fifteen** [comment]
So using `with_time_zone` or `cast_time_zone` on naïve timestamps will yield different results (assume naïve is UTC vs assume naïve is target TZ, respectively, *I think*), do I understand this right? The doc isn't super clear on which is which, and the API reference doesn't seem to have an entry for `with_time_zone` at the moment.

**Comment by ritchie46** [comment]
The stored time in polars is UTC time. If a timezone is given, that timezone offset will be applied relative to UTC. 

With `cast_time_zone` we can modify the underlying values by the difference of `current_time_zone - given_time_zone` or vice versa.

**Comment by ritchie46** [comment]
I have added a `tz_localize` expression. I think this should feel more intuitive to most people (myself included).

**Comment by sm-Fifteen** [comment]
> I have added a `tz_localize` expression. I think this should feel more intuitive to most people (myself included).

@ritchie46: It's definitely an improvement in terms of "least surprising behavior", looking at [what it does](https://github.com/pola-rs/polars/blob/e76d5d9f266a5ae7ea8a95611131b71beaa00ff4/polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs#L144-L154).

Now might be a good time to mention how Pandas has [a method of the same name](https://pandas.pydata.org/docs/reference/api/pandas.Series.tz_localize.html) that helpfully allows the user to specify [what to do when encountering the DST fold or DST gap](https://github.com/pandas-dev/pandas/blob/91111fd99898d9dcaa6bf6bedb662db4108da6e6/pandas/_libs/tslibs/tzconversion.pyx#L187-L193) (including inferring which side of the fold the timestamp is on when timestamps can be assumed to be monotonic; or allowing the user to pass a boolean series to inform whether each timestamp is before or after DST). That's certainly a lot of extra logic for something that only occurs twice a year and that [various countries are starting to get rid of](https://www.reuters.com/world/us/us-senate-approves-bill-that-would-make-daylight-savings-time-permanent-2023-2022-03-15/), but it's something that often needs to be accounted for when handling naive datetimes.

The current behavior of just setting the timezone on the unmodified data before casting it to UTC means Polars [will panic](https://github.com/pola-rs/polars/blob/d192e3f8c8bfeba9802c2f4ce9f75f500a8bd3b4/polars/polars-time/src/chunkedarray/kernels.rs#L243) when fed data that falls in the DST gap for that timezone (matching `nonexistent='raise'`, in a way), and assumes all ambiguous timestamps fall before the fold.

**Comment by ritchie46** [comment]
Could you give me an example? I am not familiar with DST, so I need some guidance here. :)

**Comment by sm-Fifteen** [comment]
> Could you give me an example? I am not familiar with DST, so I need some guidance here. :)

Well, if we go with the Pandas example data:

```py
import polars as pl

time_df = pl.DataFrame({"time": [
	'2018-10-28 01:30:00',
	'2018-10-28 02:00:00', # 02:00 before DST fold
	'2018-10-28 02:30:00', # 02:30 before DST fold
	'2018-10-28 02:00:00', # 02:00 after DST fold, would be 03:00
	'2018-10-28 02:30:00', # 02:30 after DST fold, would be 03:30
	'2018-10-28 03:00:00', # Would be 04:00
	'2018-10-28 03:30:00', # Would be 04:30
]})

time_df = time_df.with_column(pl.col("time").str.strptime(pl.Datetime, fmt="%Y-%m-%d %H:%M:%S").dt.with_time_zone('Europe/Berlin').dt.cast_time_zone("UTC"))

time_df
```

```PanicException: Ambiguous local time, ranging from 2018-10-28T02:00:00CEST to 2018-10-28T02:00:00CET```

Here, Polars (0.14.20, no `tz_localize`) panics when I try to do the same kind of operation as what localize does because 2:30 on October 28th 2018 falls [on the DST fold](https://peps.python.org/pep-0495/#in-the-fold) (official Python doc, good read) in the Berlin timezone, so chrono_tz cannot determine whether "02:00:00" is actually two hours after midnight or three hours after midnight, and Polars doesn't seem to handle the error case.

Likewise, if I do the same thing with date-times that fall on the DST gap, on the hour that was skipped to move the clocks forward, this one also cannot be resolved into a specific timestamp.

```py
import polars as pl

time_df = pl.DataFrame({"time": [
	'2019-03-31 12:30:00',
	# Skips from 12:59 to 02:00
	'2019-03-31 01:00:00',
	'2019-03-31 01:30:00',
	# The two timestamps above don't exist
	'2019-03-31 02:00:00',
	'2019-03-31 02:30:00',
]})

time_df = time_df.with_column(pl.col("time").str.strptime(pl.Datetime, fmt="%Y-%m-%d %H:%M:%S").dt.with_time_zone('Europe/Berlin').dt.cast_time_zone("UTC"))

time_df
```

```PanicException: No such local time```

Pandas allows you to set various behaviors in these cases, and that might be a good thing to have in Polars as well.

**Comment by MarcoGorelli** [comment]
This works fine now:

```python

In [4]: df = df.with_columns(df["t"].dt.cast_time_zone('UTC').dt.with_time_zone("America/New_York"))
   ...: print(df)
   ...: print(df.to_pandas())
shape: (1, 1)
┌────────────────────────────────┐
│ t                              │
│ ---                            │
│ datetime[ns, America/New_York] │
╞════════════════════════════════╡
│ 2019-12-31 14:00:00 EST        │
└────────────────────────────────┘
                          t
0 2019-12-31 14:00:00-05:00
```

@sm-Fifteen ambiguous times are still an issue though:
```python
In [11]: pl.Series(["2018-10-28 02:36:00"]).str.strptime(pl.Datetime).dt.cast_time_zone('Europe/Brussels')
thread '<unnamed>' panicked at 'Ambiguous local time, ranging from 2018-10-28T02:36:00CEST to 2018-10-28T02:36:00CET', /home/marcogorelli/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.23/src/offset/mod.rs:189:17
---------------------------------------------------------------------------
PanicException: Ambiguous local time, ranging from 2018-10-28T02:36:00CEST to 2018-10-28T02:36:00CET
```
Perhaps this could/should be closed, and a separate issue opened for `'ambiguous'`?

**Comment by sm-Fifteen** [comment]
@MarcoGorelli: Fair enough, let's just discuss the DST problems in the new issue. I've already replied to you there.

This issue can probably be considered solved as far as the original post is considered.
