### ISSUE TITLE
Contributing guide needs to be improved

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4695]
### Problem Description

The project setup isn't trivial, combining Rust and Python. We should make it easy for people to start contributing.

Here's a number of issues with the current contributing guide:
* The guide states that you should ensure the test suite passes with `make test`, but this will immediately fail. You must first create a virtual environment on the Python side.  The steps for this are all the way on the bottom of the guide, and aren't clear on how to actually set up your environment.
* Code formatting section is oudated/not comprehensive.
* ...

Overall, I think we can do a better job of taking our potential contributors by the hand and help them set up everything. I'll make an attempt.

Suggestions are very welcome.

**Comment by ritchie46** [comment]
I think we should take a good look at our `Makefile` such that `make test` is bounded on a `venv`. 

Next should the order of `Make test` be correct, so that all files are available.

**Comment by cjermain** [comment]
For `make venv`, on my machine I have to change to `python3 -m venv venv` to get the right version.
