### ISSUE TITLE
Drop `pytz` in favor of built-in `zoneinfo`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#4699]
### Problem Description

I just found out that Python now has built-in timezone support in the module [`zoneinfo`](https://docs.python.org/3/library/zoneinfo.html).

This module is available in Python>=3.9. There is a [package](https://github.com/pganssle/zoneinfo) available that backports this to Python >= 3.6. Not sure how actively maintained that backport is, however.

Using this module could future-proof our code, while saving a dependency for people on modern Python versions.

What do you think; worth checking out?

**Comment by matteosantama** [comment]
I think it would be a worthwhile change. The [differences](https://peps.python.org/pep-0431/#differences-from-the-pytz-api) between `pytz` and `zoneinfo` seem pretty minimal.

Searching through the codebase there are definitely changes to make, but I don't see any major obstacles.

**Comment by zundertj** [comment]
In favor of this change. For the sake of completeness,`pytz` was added here: https://github.com/pola-rs/polars/pull/3357

**Comment by stinodego** [comment]
Resolved by #4809
