### ISSUE TITLE
Cannot assign a value of type pl.Datatype in an expression

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4702]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When attempting to manipulate a dataframe with an `object` column, we cannot assign a value whose type is `pl.datatypes.*`:

### Reproducible Example

```python
import polars as pl
from polars import col, when

x = pl.DataFrame({
    "Row": [1, 2],
   "Type": [pl.Date, pl.UInt8]
})

x.with_column(
    when(col("Row")==1).then(pl.UInt16)   # these two assigments fail
   .otherwise(pl.lit(pl.UInt8))           # even when pl.lit() is used
   .alias("New_Type")
)
```

### Expected Behavior

First row is assigned `pl.UInt16`.

### Installed Versions

<details>

---Version info---
Polars: 0.14.8
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 6.0.0
pandas: 1.4.3
numpy: 1.22.2
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
pytz: 2021.3

</details>

**Comment by ritchie46** [comment]
You can now add a `allow_object` argument to `lit`.

```python

x = pl.DataFrame({
    "Row": [1, 2],
   "Type": [pl.Date, pl.UInt8]
})

assert x.with_column(
    pl.when(pl.col("Row")==1).then(pl.lit(pl.UInt16, allow_object=True))   
   .otherwise(pl.lit(pl.UInt8, allow_object=True))           
   .alias("New_Type")
).to_dict(False) == {'Row': [1, 2],
 'Type': [pl.Date, pl.UInt8],
 'New_Type': [pl.UInt16, pl.UInt8]}
``` 

But please, don't do this. A string or categorical representing your types is a much better idea.
