### ISSUE TITLE
cast from string to int/float fail report the failed string

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#4706]
### Problem Description

Currenly, the error message of failed conversion from string to int 

ComputeError: strict conversion of cast from Utf8 to Int64 failed. consider non-strict cast.

It is useful (like in Pandas) to report which string caused the failure. like 

ComputeError: strict conversion of cast from Utf8 to Int64 failed with "foobar", consider non-strict cast.

**Comment by matteosantama** [comment]
Hi @leoliu0 could you provide a small example that triggers this error? 

Generally if you try to cast a string column to an integer, I don't think it's too helpful to print which value actually failed -- if anything it would be more helpful to show which **column** caused the error.

**Comment by leoliu0** [comment]
For example,
```python
df = pl.DataFrame(['1','2','3','4','foobar']).select(pl.col('column_0').cast(int))
```
It is helpful to print out the value(s) because then the user does not have to check which string caused the the failure, like
```
pl.DataFrame(['1','2','3','4','foobar']
           ).select(
    [pl.col('column_0'),
    pl.col('column_0').cast(int,strict=False).alias('casted')
]
)
```python

**Comment by matteosantama** [comment]
Ah, ok I see the purpose -- yes I agree this would be a helpful change
