### ISSUE TITLE
frame_equal and series_equal use different rules for null comparisons

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4716]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When comparing dataframes/series that have null values, it appears that `assert_series_equal()` returns False for null comparisons and `assert_frame_equal()` returns True.

### Reproducible Example

```python
import polars as pl

df1 = pl.DataFrame({'A': [1, 2, None, 3, 4]})
df2 = pl.DataFrame({'A': [1, 2, None, 3, 4]}) # if we use df1.clone() then assert_frame_equal() passes

print(f"Series equal: {df1['A'].series_equal(df2['A'])}")  # prints False
print(f"Frame equal: {df1.frame_equal(df2)}")              # prints True
print(df1 == df2)
```

#### Output
```text
Series equal: False
Frame equal: True
shape: (5, 1)
┌──────┐
│ A    │
│ ---  │
│ bool │
╞══════╡
│ true │
├╌╌╌╌╌╌┤
│ true │
├╌╌╌╌╌╌┤
│ true │
├╌╌╌╌╌╌┤
│ true │
├╌╌╌╌╌╌┤
│ true │
└──────┘
```

### Expected Behavior

Both `series_equal()` and `frame_equal()` should return same True.

### Installed Versions

<details>

Polars: 0.14.8
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 6.0.0
pandas: 1.4.3
numpy: 1.22.2
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
pytz: 2021.3

</details>

**Comment by matteosantama** [comment]
This stems from the default values of the `null_equal` parameter. `frame_equal` defaults to `True` but `series_equal` defaults to `False`.

Changing defaults is technically a breaking change, so we may want to wait until 0.15.0

**Comment by alexander-beedie** [comment]
> Changing defaults is technically a breaking change, so we may want to wait until 0.15.0

But when it does change, lets make `null_equal=True` for both?
After all, if we need more equality-related headaches there's always `NaN` :)

**Comment by ritchie46** [comment]
> > Changing defaults is technically a breaking change, so we may want to wait until 0.15.0
> 
> But when it does change, lets make `null_equal=True` for both? After all, if we need more equality-related headaches there's always `NaN` :)

Yep.. 👍

**Comment by mcrumiller** [comment]
@matteosantama I don't see a `null_equal` parameter in either assertion. Is this a parameter on the rust side but not on the python side?

* [assert_series_equal](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.testing.assert_series_equal.html)
* [assert_frame_equal](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.testing.assert_frame_equal.html)

both have a `nans_compare_equal` but that's obviously unrelated.

**Comment by alexander-beedie** [comment]
> @matteosantama I don't see a `null_equal` parameter in either assertion. Is this a parameter on the rust side but not on the python side?

They don't have explicit parameters, but the behaviour is that null/None always compares equal. Truth be told, it wouldn't be a crazy idea to just drop it from the frame/series methods entirely, and do the same thing?

**Comment by matteosantama** [comment]
I think you're conflating `assert_X_equal` and `X_equal`. The example you provided uses `DataFrame.equal` and `Series.equal` which do have a `null_equal` parameter.

**Comment by mcrumiller** [comment]
You're right. I should refrain from looking at this on weekends...thanks for the response.
