### ISSUE TITLE
exponential performance drop-off with nested operations against increasing number of columns 

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#4736]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description
The test-case below appears to show an exponential gremlin lurking somewhere in expression construction/evaluation (looks like `O(2^n)`). Was able to minimize the example down to just adding a few float columns together on an empty DataFrame; by the time it gets to ~35 columns it's taking nearly ¾ of an hour, and the shape of the curve is "exciting" :)

<img width="522" alt="image" src="https://user-images.githubusercontent.com/2613171/188549316-a953ffc8-f3b7-422d-bc0a-6d11a22b4b3e.png">

Each time you add another column, it doubles the time taken to construct/evaluate the expression.

The form of the expression being evaluated is just a simple (implicitly-nested) series of additions:
`((((((col("a")) + (col("b"))) + (col("c"))) + (col("d"))) + (col("e"))) + (col("f"))) + (col("g"))) ...`

### Reproducible Example

```python
from string import ascii_letters
from codetiming import Timer
from functools import reduce
from operator import add
import polars as pl

# evaluate against empty dataframe
for n in range( 10,28 ):
    df = pl.DataFrame( columns = list(ascii_letters[:n]) )
    with Timer():
        df.select( reduce(add,(pl.col(fld) for fld in df.columns)) )
```

### Raw Timing Data 

Note: tested with latest polars lib, compiled from source using: 
`maturin develop --release -- -C target-cpu=native`

<table>
<tr><th>16-25 cols... </th><th>26-35 cols...</th></tr>
<tr><td>

n.cols | secs | mins
-- | -- | --
16 | 0.00 | 0.00
17 | 0.01 | 0.00
18 | 0.02 | 0.00
19 | 0.04 | 0.00
20 | 0.08 | 0.00
21 | 0.16 | 0.00
22 | 0.31 | 0.01
23 | 0.61 | 0.01
24 | 1.23 | 0.02
25 | 2.45 | 0.04

</td><td>

n.cols | secs | mins
-- | -- | --
26 | 4.92 | 0.08
27 | 9.84 | 0.16
28 | 20.10 | 0.33
29 | 40.64 | 0.68
30 | 83.66 | 1.39
31 | 169.21 | 2.82
32 | 329.52 | 5.49
33 | 715.85 | 11.93
34 | 1,356.31 | 22.61
35 | 2,587.86 | 43.13

</td></tr> </table>

### Expected Behaviour

Evaluate the expression without an exponential growth curve in time-taken as additional columns participate. 

### Installed Versions

<details>

---Version info---
Polars: 0.14.9
Index type: UInt32
Platform: macOS-12.5.1-arm64-arm-64bit
Python: 3.9.7 (default, Aug 12 2022, 09:02:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.2
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: <not installed>
pytz: 2022.1

</details>

**Comment by ritchie46** [comment]
Interesting. We had that earlier and was hard to debug. We get an expression tree that can be very wide I believe. We probably traverse that naively during the optimization steps. A good excuse to also improve the `dot-graph` customization.

**Comment by ritchie46** [comment]
![image](https://user-images.githubusercontent.com/3023000/189151578-73314f51-7e9f-447b-80c9-00413d226b03.png)

**Comment by ritchie46** [comment]
Fixed :)

![image](https://user-images.githubusercontent.com/3023000/189154088-f3471c40-2010-49d1-ad15-0cb9c0878b6b.png)

**Comment by alexander-beedie** [comment]
Now that's how you put out a fire... :)
