### ISSUE TITLE
set_with_columns_kwargs() does not exist, but recommended

### ISSUE THREAD

**Issue by indigoviolet** [pola-rs/polars#4740]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

`.with_columns(**named_kwargs)` throws an error 

```
RuntimeError: **kwargs support is experimental; requires opt-in via `pl.Config.set_with_columns_kwargs(True)`
```

But the above function does not exist

### Reproducible Example

```python
import polars as pl
df = pl.DataFrame({"a": [1,2,3]})
ab = df.with_columns([df.get_column("a").alias("b")])
ab2 = df.with_columns(b=df.get_column("a").alias("b"))

Truncated Traceback (Use C-c C-$ to view full TB):
File /.venv/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py:1563, in LazyFrame.with_columns(self, exprs, **named_exprs)
   1496 """
   1497 Add or overwrite multiple columns in a DataFrame.
   1498 
   (...)
   1560 
   1561 """
   1562 if named_exprs and not Config.with_columns_kwargs:
-> 1563     raise RuntimeError(
   1564         "**kwargs support is experimental; requires opt-in via"
   1565         " `pl.Config.set_with_columns_kwargs(True)`"
   1566     )
   1567 elif exprs is None and not named_exprs:
   1568     raise ValueError("Expected at least one of 'exprs' or **named_exprs")

RuntimeError: **kwargs support is experimental; requires opt-in via `pl.Config.set_with_columns_kwargs(True)`


In [54]:
pl.Config.set_with_columns_kwargs(True)

Truncated Traceback (Use C-c C-$ to view full TB):
Input In [54], in <cell line: 1>()
----> 1 pl.Config.set_with_columns_kwargs(True)

AttributeError: type object 'Config' has no attribute 'set_with_columns_kwargs'


In [53]:
pl.Config.with_columns_kwargs = True
df.with_columns(b=df.get_column("a").alias("b")).frame_equal(ab)
Out [53]:
True
```

### Expected Behavior

The function should exist.

Workaround is `pl.Config.with_columns_kwargs = True`

### Installed Versions

<details>

pr.show_versions()
---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.28
Python: 3.9.9 (main, Aug 25 2022, 19:32:03) 
[GCC 12.1.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.2
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>

</details>

**Comment by alexander-beedie** [comment]
Thanks for reporting; your workaround is in fact the correct setting - @ghuls is kindly updating the docs to reflect that!
