### ISSUE TITLE
series.cast with strict = True turns bool into date

### ISSUE THREAD

**Issue by josefinb** [pola-rs/polars#4757]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Booleans turn into dates when using cast(pl.Date, strict=True), instead of raising an error. If this is intended behaviour, please clarify in documentation.

### Reproducible Example

```python
import polars as pl

df = pl.DataFrame([[True, False]], columns=["A", "B"])
df1 = df.with_columns([
    pl.col("A").cast(pl.Date, strict=True),
    pl.col("B").cast(pl.Date, strict=True)
])

### 
Output (as a dataframe):
A: date(1970, 1, 1)
B: date(1970, 1, 2)
```

### Expected Behavior

I would expect an error to be raised, since strict = True. 
From documentation it is unclear what would happen if strict = False, but I would probably expect the True and False values to stay as they are, and not for them to be set as dates.

### Installed Versions

---Version---
Polars: 0.14.9
Index Type: UInt32
Platform: Windows-10-10.0.19043-SPO
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 6.0.0
pandas: 1.4.0
numpy: 1.21.2
fsspec: 2022.02.0
connectorx: <not installed>
xlsx2csv: <not installed>

**Comment by ritchie46** [comment]
A strict cast checks if the cast can be done without overflowing. You can for instance not cast every `u64` to an `u8` so some would become null because of that cast. A `strict` cast checks if a cast does not lead to extra null values.

Casting a boolean (single byte) to a physical date (backed by `i32`) does not loose any information thus can be done strictly.

**Comment by josefinb** [comment]
ok thanks for clarifying.
