### ISSUE TITLE
Add `.dt.millisecond` 

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#4760]
### Problem Description

For extracting date features we have `.dt.second` and `.dt.nanosecond`.

For extracting duration features we have `.dt.seconds`, `dt.milliseconds` and `.dt.nanosecond`

We should add `dt.millisecond`. Obviously you can compute it but it's confusing when you can see it there for durations and then can't find it for dates

**Comment by alexander-beedie** [comment]
I'll have a PR for this (along with a fix for some `str.strptime` issues) tomorrow; got everything working locally already (along with `dt.microsecond`, which was also missing). Just looking to extend test coverage first...

**Comment by braaannigan** [comment]
@alexander-beedie You've probably got this but if we do .dt.microsecond then we'd also need .dt.microseconds for duration

**Comment by alexander-beedie** [comment]
> @alexander-beedie You've probably got this but if we do .dt.microsecond then we'd also need .dt.microseconds for duration

Already exists  ;)
