### ISSUE TITLE
Add getter for expression alias

### ISSUE THREAD

**Issue by MichalLebeda** [pola-rs/polars#4812]
### Problem Description

For programmatically added expressions, it is sometimes beneficial to be able to determine which column given expression results to.

```
max_value_expr = pl.col("values").max().alias("max_value_col_name")
print(max_value_expr.get_alias())
```

prints: `max_value_col_name`

**Comment by ritchie46** [comment]
Could you elaborate a bit more? I don't understand the feature request?

**Comment by MichalLebeda** [comment]
> Could you elaborate a bit more? I don't understand the feature request?

edited the original comment

**Comment by ritchie46** [comment]
See: `expr.meta.output_name`

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.expr.meta.ExprMetaNameSpace.output_name.html#polars.internals.expr.meta.ExprMetaNameSpace.output_name

**Comment by MichalLebeda** [comment]
Thanks, completely overlooked the ```meta``` field
