### ISSUE TITLE
Add series.with_values()

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4830]
### Problem Description

 Currently if I want to expression-ify `pl.Series` object, I have to use the following:

```python
s = pl.Series([1, 2, 3, 4, 5])

s = pl.Dataframe({A': s).with_column(
    pl.col('A').do_expr_stuff(...)
)['A']
```

It would be nice to avoid the Dataframe construction/deconstruction and operate directly on the series:

```python
s = pl.Series([1, 2, 3, 4, 5])

s = s.with_values(do_expr_stuf(...))
```

This seems a bit roundabout. Is there a way to operate directly on the series?

**Comment by ritchie46** [comment]
Yes,  `pl.select` allows you to run expression on a `DataFrame` generated on the fly.

**Comment by mcrumiller** [comment]
Let me clarify--I want to run an expression on a `Series` directly, without having to compose an intermediate dataframe, which is later discarded.

In other words, this:

```python
s = pl.Series(...).with_values(...)
```

Intead of this:

```python
s = pl.DataFrame({'S': [...]}).with_column(pl.col('S').(expr...))['S']
```

**Comment by matteosantama** [comment]
What is the expression you are trying to use? Many expressions are implemented as methods on the `Series` as well

**Comment by mcrumiller** [comment]
How about the equivalent of `pd.map()`? I find myself doing this quite often, i.e. map a series of values to another. Let's say we have:

```python
import polars as pl
from polars import when, col

my_map = {'a': 'm', 'b': 'n', 'c':  'o'}

s = pl.Series("chars", ['a', 'b', 'c'])
```

We could build up a series of branches via [Ritchie's answer on SO](https://stackoverflow.com/a/70974264/3681427):

```python
def replace(column, my_map):
    from_ = list(my_map.keys())
    to_ = list(my_map.values())
    branch = when(col(column) == from_[0]).then(to_[0])
    for from_val, to_val in from_[1:], to_[1:]:
        branch = branch.when(col(column) == from_val).then(to_val)
    return branch.otherwise(col(column))
```

If I wanted to apply this expression to the series (or any custom expression), is there a way to do it other than creating a dataframe, using `with_column`, and then extracting the column? As in:

```python
s = pl.DataFrame([s]).with_column(replace("chars", my_map))["chars"]
```

**Comment by ghuls** [comment]
Not shorter, but you could do the following:
```python
In [138]: pl.select([s]).select(remap("chars", my_map)).get_column("chars")
Out[138]: 
shape: (3,)
Series: 'chars' [str]
[
	"m"
	"n"
	"o"
]

```

Or you can write your function to accept a `pl.col("name")` as input expression and call the generic `apply_expr_on_series` function to call "any" expression on a series and return a series.

```python
In [186]: def remap(col_series_expr: pl.Expr, mapping: dict) -> pl.Expr:
     ...:     if not mapping:
     ...:         raise Exception("Mapping can't be empty")
     ...:     elif not isinstance(mapping, dict):
     ...:         TypeError(f"mapping must be of type dict, but is type: {type(mapping)}")
     ...:     if not isinstance(col_series_expr, pl.Expr):
     ...:         raise TypeError(f"column must be of type str, but is type: {type(col_series_expr)}")
     ...: 
     ...:     branch = pl.when(col_series_expr == list(mapping.keys())[0]).then(
     ...:         list(mapping.values())[0]
     ...:     )
     ...: 
     ...:     for from_value, to_value in mapping.items():
     ...:         branch = branch.when(col_series_expr == from_value).then(to_value)
     ...: 
     ...:     return branch.otherwise(col_series_expr).alias(col_series_expr.meta.output_name())
     ...: 

In [188]: def apply_expr_on_series(s: pl.Series, expr, *args, **kwargs) -> pl.Series:
     ...:     column = s.name
     ...:     return pl.select([s]).select(
     ...:         [expr(pl.lit(s), *args, **kwargs)]
     ...:     ).get_column(column)
     ...: 



In [188]: apply_expr_on_series(s, remap, mapping=my_map)
Out[188]: 
shape: (3,)
Series: 'chars' [str]
[
	"m"
	"n"
	"o"
]

In [189]: apply_expr_on_series(s, remap, my_map)
Out[189]: 
shape: (3,)
Series: 'chars' [str]
[
	"m"
	"n"
	"o"
]

In [190]: apply_expr_on_series(s, pl.Expr.last)
Out[190]: 
shape: (1,)
Series: 'chars' [str]
[
	"c"
]

In [191]: apply_expr_on_series(s, pl.Expr.count)
Out[191]: 
shape: (1,)
Series: 'chars' [u32]
[
	3
]


In [198]: apply_expr_on_series(s, pl.Expr.is_in, ["c", "a"])
Out[198]: 
shape: (3,)
Series: 'chars' [bool]
[
	true
	false
	true
]
```

**Comment by ritchie46** [comment]
> Let me clarify--I want to run an expression on a `Series` directly, without having to compose an intermediate dataframe, which is later discarded.
> 
> In other words, this:
> 
> ```python
> s = pl.Series(...).with_values(...)
> ```
> 
> Intead of this:
> 
> ```python
> s = pl.DataFrame({'S': [...]}).with_column(pl.col('S').(expr...))['S']
> ```

Yes, that is what `pl.select` allows you to do.
