### ISSUE TITLE
Allow sort on multiple columns

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4831]
### Problem Description

Currently, `pl.DataFrame.sort()` only accepts a single column. It would be nice to be able to sort via multiple columns:

```python
df = pl.DataFrame({
    'A': [2, 1, 1, 1, 3],
    'B': [1, 3, 1, 2, 4]
})

df.sort(by=['A', 'B'])

df = pl.DataFrame({
    'A': [2, 1, 1, 1, 3],
    'B': [1, 3, 1, 2, 4]
})
```

Output:
```
shape: (5, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   │
└─────┴─────┘
```

Along with this would be `arg_sort()` which would additionally accept multiple columns.

**Comment by zundertj** [comment]
The second example in https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.sort.html?highlight=sort#polars.DataFrame.sort shows how to sort on multiple columns?

Are you referring to `Expr.arg_sort()`? Not sure how you would envision using multiple columns, it is a single expression. Maybe a code example helps us to understand what behavior you would like to use.

**Comment by mcrumiller** [comment]
Hey, sorry I just searched through the API and found `pl.argsort_by` and `pl.sort_by` for use in expressions:

```
df = pl.DataFrame({
    'A': [2, 1, 1, 1, 3],
    'B': [1, 3, 1, 2, 4]
})

df.with_column(pl.argsort_by(['A', 'B']).alias("idx"))
```

output:

```
shape: (5, 3)
┌─────┬─────┬─────┐
│ A   ┆ B   ┆ idx │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ u32 │
╞═════╪═════╪═════╡
│ 2   ┆ 1   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 3   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 2   ┆ 0   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   ┆ 4   │
└─────┴─────┴─────┘
```

However, using `pl.all()` fails. I'll write up an issue.

**Comment by zundertj** [comment]
Closing this in favor of the new issue.
