### ISSUE TITLE
Don't raise `ComputeError` for duplicate columns in csv header names when `new_names` is provided (`pl.read_csv`)

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#4839]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

One of the go-to solutions for duplicate column names in csv files should be the argument `new_columns` in `pl.read_csv`. Unfortunately, this still raises a `ComputeError`.

### Reproducible Example

```py3
from io import StringIO
csv = """a,a
1,2
"""
pl.read_csv(StringIO(csv), new_columns=['c', 'd'])
```

```py3
ComputeError: 'CSV header contains duplicate column names'
```

### Expected Behavior

I would expect the reader to ignore all column headers up to and including `len(new_columns)`.

### Installed Versions

<details>
```
---Version info---
Polars: 0.14.9
Index type: UInt32
Platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
pytz: 2022.2.1
```
</details>

**Comment by ghuls** [comment]
You can use:
```
In [3]: from io import StringIO
   ...: csv = """a,a
   ...: 1,2
   ...: """
   ...: pl.read_csv(StringIO(csv), has_header=False, skip_rows=1, new_columns=['c', 'd'])
Out[3]: 
shape: (1, 2)
┌─────┬─────┐
│ c   ┆ d   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
└─────┴─────┘
```

**Comment by ghuls** [comment]
It might at a certain point. At the moment CSV parsing happens in Rust and column renaming in python.
