### ISSUE TITLE
Datatype inference for null is inconsistent

### ISSUE THREAD

**Issue by indigoviolet** [pola-rs/polars#4854]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Putting a null-valued column through some transformations leads to some inconsistencies. This affected me because I had done a `partition_by` into "batches", followed by some (identical) transformations,	but then I could no longer vstack the resulting dataframes.

### Reproducible Example

```python
import polars as pr

df = pr.DataFrame({"a": [None]}, columns=[("a", pr.Utf8)])
df.schema

# {'a': polars.datatypes.Utf8}

df2 = df.with_column(df.to_struct('b'))
df2.get_column('b').struct.field('a').dtype

# polars.datatypes.Utf8


df3 = pr.from_dicts(df2.to_struct('_').to_list()).select('b').unnest('b')
df3.schema

# {'a': polars.datatypes.Int32}


df4 = pr.from_dicts(df2.to_struct('_').to_list()).select('a')
df4.schema

# {'a': polars.datatypes.Boolean}
```

### Expected Behavior

Ideally, they will stick to the original dtype, but that's probably not possible through the `to_list` transformation. 

- It would be nice to be consistent between the `unnest` and `from_dicts` inference

- Perhaps `from_dicts` should allow specifying the dtypes, and throw a warning if it only sees nulls during inference. 

- Perhaps we should have a  `.with_schema_like()` function, analogous to `CREATE TABLE LIKE` from sql. 

### Installed Versions

<details>
```---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.28
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>

 ```
</details>

**Comment by indigoviolet** [comment]
One more thing: `scan_ipc` etc with globs does a vstack - which will break like this. Perhaps we should have a way of forcing the first file's schema on the rest.

**Comment by indigoviolet** [comment]
Here's a workaround for the vstack (I think):
```
dfs = [pr.read_ipc(f) for f in (data_dir/"generated").glob("*.arrow")]
dfs = [pr.DataFrame(d.to_arrow(), columns=dfs[0].schema.items()) for d in dfs]
pr.concat(dfs, how='vertical')
```

**Comment by zundertj** [comment]
> Ideally, they will stick to the original dtype, but that's probably not possible through the to_list transformation.

This won't be possible, the `to_list()` call drops you into plain Python lists, and that list will have a single `None` value. So there is no chance we can infer it is coming from a dataframe with type `Utf8`.


> It would be nice to be consistent between the unnest and from_dicts inference

That would only be possible if we could carry over the type per the above point, so that wont be possible.

> Perhaps from_dicts should allow specifying the dtypes, and throw a warning if it only sees nulls during inference.

This has been introduced in the mean time: [docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_dicts.html#polars-from-dicts).

> Perhaps we should have a .with_schema_like() function, analogous to CREATE TABLE LIKE from sql.

Solved per the above point.

Im closing this. Feel free to open a new issue if think it has not been solved adequately.
