### ISSUE TITLE
Series.arg_min and Series.arg_max does not take into account (to disregard) null values

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/polars#4855]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Both in Rust(0.23.2) and Python(0.14.11) api it seems arg_min and arg_max do not have the intended behaviour in respect to null values.

### Reproducible Example

```python
import polars as pl
print(pl.Series([None,1,2]).arg_min()) #returns 0, not 1 the idx of min non-null value
print(pl.Series([None,None]).arg_min()) #returns 0, not None as not any non-null values
print(pl.Series([None,None]).arg_max()) #returns 0, not None as not any non-null values
```

### Expected Behavior

arg_min and arg_max should disregard any null values. If only non-null values they should return None.

### Installed Versions

---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.3.3
numpy: 1.21.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>

**Comment by ritchie46** [comment]
Nulls are included in the ordering: 

```
>>> print(pl.Series([1, 2, None]).arg_min()) 
2
```

**Comment by sorhawell** [comment]
Alright if that is the intended behavior.

I just had in my own head differently.
In R (which.min, which.max) or in [pandas](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.Series.argmin.html) Nulls are typically disregarded.

I see [numpy](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) has a similar behavoir as polars but not completely for arg_max

```
In [24]: pl.Series([None, 1]).arg_max()
Out[24]: 1

In [25]: np.array([np.nan, 1]).argmax() #granted Null and NaN entirely the same
Out[25]: 0
```

What in generel is the behavoir of methods/functions that polars seek to match?

**Comment by ritchie46** [comment]
Note that the comparison with numpy/pandas nans don't make total sense as a floating point `NaN` is not the same a `None/Null` in polars/arrow. We have decided on `None` being lower than any `Some(value)`. For `NaN` floating point numbers we have different rules.

**Comment by sorhawell** [comment]
That settles everything for me. Many thanks.

**Comment by sorhawell** [comment]
sry for being a stickler on this one but `arg_min()` points to the Null value on index `2` and `min()` extracts the minimal non Null/None value being `0.0`.

The documentation of `arg_min()` and `min()`  states resepctively
arg_min():  " Get the index of the minimal value."
min(): "Get minimum value."

I appears to me, that either it is a bug or there are two undocumented definitions of "minimal value".


```
pl.DataFrame({'a': [0,1,None,float("NaN")]}).select([
    pl.col("a").min().alias("min_a"),
    pl.col("a").arg_min().alias("arg_min_a"),
])
Out[10]: 
shape: (1, 2)
┌───────┬───────────┐
│ min_a ┆ arg_min_a │
│ ---   ┆ ---       │
│ f64   ┆ u32       │
╞═══════╪═══════════╡
│ 0.0   ┆ 2         │
└───────┴───────────┘
```

**Comment by sorhawell** [comment]
Expression arg_min points to different value depending on initial ordering

```
In [10]: pl.DataFrame({"a":[1.0,float("NaN")]}).select(pl.col("a").reverse().arg_min())
Out[10]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 0   │
└─────┘

In [11]: pl.DataFrame({"a":[1.0,float("NaN")]}).select(pl.col("a").reverse().arg_min())
Out[11]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 0   │
└─────┘```

**Comment by sorhawell** [comment]
`arg_sort().head(1)` is not the same as `arg_min()` if the column/Series contains NaN's

```
In [30]: pl.DataFrame({"a":[float("NaN"),1.0]}).select(pl.col("a").arg_sort().head(1))
Out[30]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 1   │
└─────┘

In [31]: pl.DataFrame({"a":[float("NaN"),1.0]}).select(pl.col("a").arg_min())
Out[31]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 0   │
└─────┘
```

**Comment by sorhawell** [comment]
top_k and sort have different behaviors in respect to NaNs

```
In [45]: pl.DataFrame({"a":[float("NaN"),1.0,float("Inf"),float("-inf"),None]}).select(
    ...: [pl.col("a").top_k(5).alias("top_k5"),
    ...: pl.col("a").sort(reverse=True).alias("sort top first"),
    ...: pl.col("a").sort(reverse=True, nulls_last=True).alias("sort top first null_last"),
    ...: pl.col("a").top_k(5,True).alias("bottom_k5"),
    ...: pl.col("a").sort().alias("sort bottom first"),
    ...: pl.col("a").sort(nulls_last=True).alias("sort bottom first  nulls_last")
    ...: ])
Out[45]: 
shape: (5, 6)
┌────────┬────────────────┬──────┬───────────┬───────────────────┬──────┐
│ top_k5 ┆ sort top first ┆ sort ┆ bottom_k5 ┆ sort bottom first ┆ sort │
│ ---    ┆ ---            ┆ top  ┆ ---       ┆ ---               ┆ bott │
│ f64    ┆ f64            ┆ firs ┆ f64       ┆ f64               ┆ om   │
│        ┆                ┆ t    ┆           ┆                   ┆ firs │
│        ┆                ┆ null ┆           ┆                   ┆ t    │
│        ┆                ┆ _las ┆           ┆                   ┆ null │
│        ┆                ┆ t    ┆           ┆                   ┆ s_la │
│        ┆                ┆ ---  ┆           ┆                   ┆ st   │
│        ┆                ┆ f64  ┆           ┆                   ┆ ---  │
│        ┆                ┆      ┆           ┆                   ┆ f64  │
╞════════╪════════════════╪══════╪═══════════╪═══════════════════╪══════╡
│ NaN    ┆ null           ┆ NaN  ┆ NaN       ┆ null              ┆ -inf │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ inf    ┆ NaN            ┆ inf  ┆ -inf      ┆ -inf              ┆ 1.0  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1.0    ┆ inf            ┆ 1.0  ┆ 1.0       ┆ 1.0               ┆ inf  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ -inf   ┆ 1.0            ┆ -inf ┆ inf       ┆ inf               ┆ NaN  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ null   ┆ -inf           ┆ null ┆ null      ┆ NaN               ┆ null │
└────────┴────────────────┴──────┴───────────┴───────────────────┴──────┘

```

**Comment by sorhawell** [comment]
@ritchie46 

I'm currently writing tests for all R versions of polars expression, and it just seems to simple me, that any sorting behavior in respect to NaN values are implemented randomly in rust-polars.

you mentioned that
`For NaN floating point numbers we have different rules.`
where can I find these rules?

**Comment by sorhawell** [comment]
could one solution be to include NaN's all sorting related examples to illustrate the behavoirs and perhaps some tests to flag if the behavoirs ever were to change?

**Comment by sorhawell** [comment]
Superceded by #5359
