### ISSUE TITLE
Use object_store to implement remote storage for parquet files

### ISSUE THREAD

**Issue by ozgrakkurt** [pola-rs/polars#4865]
### Problem Description

Right now polars reads parquet files using memmap. Can move to using [object_store](https://crates.io/crates/object_store) to read remote files and maybe keep memmap for local files if it is more performant. I can work on implementing this if it makes sense

related issues: #800 #3906

**Comment by ritchie46** [comment]
Yes, definitely interested in that.

**Comment by andrei-ionescu** [comment]
I'm interested too.

One thing to note is that the support for Azure Data Lake Storage Gen2 is not implemented in `object_store` library. I added this ticket — https://github.com/apache/arrow-rs/issues/3283 — for it.

**Comment by andrei-ionescu** [comment]
The previous issue has been sorted out. `object_store` library works and it can be used to read from Azure Data Lake Store Gen2 — I tested the `abfss` protocol and I can successfully access the storage.

So, the [object_store](https://crates.io/crates/object_store) library can be used to access remote storages.
