### ISSUE TITLE
Implement Byte Vector Values

### ISSUE THREAD

**Issue by ozgrakkurt** [pola-rs/polars#4877]
### Problem Description

Currently only string is supported but it would be nice to have support for byte vectors

**Comment by ritchie46** [comment]
I think you can use `List<u8>` for that. Physically it is exact the same as our string type.

**Comment by ozgrakkurt** [comment]
How would I do something like `binary_col.is_in(list_of_binary_literals)` ?
I can create a single binary literal like this: `binary_vec.iter().collect::<polars::series::Series>().lit()` but not sure how to create a List<List<u8>> literal

Also maybe `Literal` trait should be implemented for `Vec<u8>` and `&[u8]` ?

**Comment by ozgrakkurt** [comment]
@ritchie46 currently arrow binary datatype isn't supported not implemented here: https://github.com/pola-rs/polars/blob/4beb08eba86bfcf8924d1d484fccb78b94c0e48e/polars/polars-core/src/datatypes/field.rs#L113

also here: https://github.com/pola-rs/polars/blob/4beb08eba86bfcf8924d1d484fccb78b94c0e48e/polars/polars-core/src/datatypes/dtype.rs#L6
