### ISSUE TITLE
`set_at_idx` only uses first value if values is str

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4880]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

When using `set_at_idx`, only the first value in a list of values is used, and is applied to all index locations.

### Reproducible Example

```python
import polars as pl

s = pl.Series(['z', z', 'z', 'z', 'z'])
s.set_at_idx([0, 1], ['a', 'b'])
```

#### Output

```
shape: (5,)
Series: '' [str]
[
        "a"
        "a" <---this should be 'b'
        "z"
        "z"
        "z"
]
```

Note that for integers it works as expected:

```python
s = pl.Series([9, 9, 9, 9, 9])
s.set_at_idx([0, 1], [0, 1])
```

#### Output

```
shape: (5,)
Series: '' [i64]
[
        0
        1
        9
        9
        9
]
```

### Installed Versions

<details>

```
---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
```

</details>

**Comment by zundertj** [comment]
Can reproduce, and the problem seems to be inside the Rust part, as the Python code ends up calling:
```python
self._s.set_at_idx(idx._s, value._s)
```

with `idx` 
```
shape: (2,)
Series: '' [i64]
[
	0
	1
]
```

and `value`:
```
shape: (2,)
Series: '' [str]
[
	"a"
	"b"
]
```
correctly.

( I first thought this may have been a case where we check for value being a sequence, and a string evaluates to a sequence, but that is not true).
