### ISSUE TITLE
Add empty expression for building expressions

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4881]
### Problem Description

When building a long series of expressions, it's common to the see following:

```python
# create first branch
condition, value = calculate_stuff(items[0])
expr = pl.when(condition).then(value)

# add additional branches
for item in items[1:]:
    condition, value = calculate_stuff(item)
    expr = expr.when(condition).then(value)
expr = expr.otherwise(default)

df = df.with_column(expr)
```

It would be nice to be able to initialize an empty expression, so that we could avoid the awkwardness of creating the first branch, especially in the event that `calculate_stuff()` is long-winded:

```python
conditions = [...]
values = [...]

expr = pl.Expr.empty()
for item in items:
    condition, value = calculate_stuff(item)
    expr = expr.when(condition).then(value)
expr = expr.otherwise(default)

df = df.with_column(expr)
```

**Comment by mcrumiller** [comment]
Something to go along with this might also be an efficient expression concatenator. Suppose we build a long list of when/then expressions:

```python
from polars import col, when

exprs = [
    when(col('a') == 1).then(2),
    when(col('a') == 2).then(5),
    ...
    when(col('a') == 15).then(36)
]
```

It would be nice to be able to apply these in succession:

```python
exprs = pl.Expr.chain(exprs)

# this could be the equivalent of:
expr = when(col('a') == 1).then(2).when(col('a') == 2).then(5) ....     .when(col('a') == 15).then(36)
```

**Comment by zundertj** [comment]
You could make your first example a bit nicer by wrapping it in an iterator, that avoids the `items[1:]` indexing and thus wont break when your list is just one item:

```python
from typing import Iterable
import polars as pl

def chain_when_then(chain: Iterable[tuple]) -> pl.Expr:
    it = iter(chain)
    condition, value = next(it)
    expr = pl.when(condition).then(value)

    for condition, value in it:
        expr = expr.when(condition).then(value)

    expr = expr.otherwise(None)
    return expr
```

In your example, you could then call:
```python
expr = chain_when_then(map(calculate_stuff, items))
```

To avoid the first "special case", we could use a `when` that evaluates to False:

```python
def chain_when_then2(chain: Iterable[tuple]) -> pl.Expr:
    expr = pl.when(pl.lit(False)).then(None)

    for condition, value in iter(chain):
        expr = expr.when(condition).then(value)

    expr = expr.otherwise(None)
    return expr
```

For the sake of completeness, a small example:
```python
df = pl.DataFrame({"a": [1,2,3]})
e1 = chain_when_then([(pl.col("a")==1, pl.lit(2)), (pl.col("a")==3, pl.lit(3))])
e2 = chain_when_then2([(pl.col("a")==1, pl.lit(2)), (pl.col("a")==3, pl.lit(3))])
df.select([pl.col("a"), e1.alias("e1"), e2.alias("e2")])
```
yields
```
shape: (3, 3)
┌─────┬──────┬──────┐
│ a   ┆ e1   ┆ e2   │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ i32  ┆ i32  │
╞═════╪══════╪══════╡
│ 1   ┆ 2    ┆ 2    │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2   ┆ null ┆ null │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3   ┆ 3    ┆ 3    │
└─────┴──────┴──────┘
```


Both these implementations are very similar to [functools.reduce](https://docs.python.org/3/library/functools.html#functools.reduce), except that the input is not a list of expressions but a tuple of expressions. I think that is what you are after in your second post, pass in a list of expressions, and chain them, but I don't see a way to make that work.

**Comment by YuRiTan** [comment]
I assume these long chained expressions, are almost always `.when().then().when().then()....otherwise()`. Then, you could also do something like this:

```python
df = pl.DataFrame(
    {
        "a": [0, 1, 2, 3, 4],
        "b": [5, 6, 7, 8, 9],
        "c": [10, 11, 12, 13, 14],
    }
)  

exprs = [
    pl.when(pl.col('a') > 0).then('>0').otherwise(None),
    pl.when(pl.col('a') > 1).then('>1').otherwise(None),
    pl.when(pl.col('a') > 2).then('>2').otherwise(None),
    pl.when(pl.col('a') > 3).then('>3').otherwise(None),
    pl.when(pl.col('a') > 4).then('>4').otherwise('other'),
    # or some list comprehension
]

df.select(pl.coalesce(exprs).alias('test'))
```

This wouldn't require an empty expression or a separate chain method.

**Comment by stinodego** [comment]
I don't think an empty expression is warranted here. As pointed out by YuRi, you can just use a coalesce in this case. The resulting syntax is much clearer.

I'll close this as not planned, unless I see a more compelling example where this would result in much more efficient code or clearer syntax.

**Comment by mcrumiller** [comment]
I think I had created this before `map_dict`/`replace` even existed and was often using `when/then` chains to address that case. I haven't felt any use for it since.

**Comment by PaulRudin** [comment]
I have (for example):
```
expr = pl
    for e, b in enumerate(badge_boundaries):
        expr = expr.when(pl.col("elo") < b).then(pl.lit(e))
    return df.with_columns(elo_badge=expr)
```
which works fine but mypy (understandably) doesn't like it. I tend to think that the alternative with `coalesce` looks clunky, because of the need for all the essentially redundant `otherwise()`. Presumably the `coalesce` alternative is marginally slower, since it has a little more work to do in testing for null.

**Comment by stinodego** [comment]
> because of the need for all the essentially redundant otherwise().

You can simply leave those out. `otherwise(None)` is the default behavior for when/then expressions.

**Comment by mcrumiller** [comment]
@PaulRudin that's a pretty clever syntactic solution to set `expr = pl`.
