### ISSUE TITLE
Custom python style and extension arrays

### ISSUE THREAD

**Issue by achapkowski** [pola-rs/polars#4882]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Question about polars

https://pandas.pydata.org/docs/development/extending.html

The pandas ecosystem has the ability to extend into custom data types, will polars honor these data types?

**Comment by zundertj** [comment]
As Polars uses Arrow data types, your best bet may be to look at [extending data types in Arrow](https://arrow.apache.org/docs/python/extending_types.html#defining-extension-types-user-defined-types), but I'm not aware of support for this.

**Comment by achapkowski** [comment]
Ok thanks!
