### ISSUE TITLE
Website rust polars example no longer runs

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#4891]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

After #4861, the Rust example on https://www.pola.rs/ no longer works.

`Result` is replaced by `PolarsResult`, but I still wasn't able to get the example to run. Could someone suggest a fix?

### Reproducible Example

```rust
// in Cargo.toml:
// polars = { git = "https://github.com/pola-rs/polars", features = ["lazy", "parquet"]}

use polars::prelude::*;

fn example() -> Result<DataFrame> {
    LazyCsvReader::new("foo.csv".into())
        .finish()
        .filter(col("bar").gt(lit(100)))
        .groupby(vec![col("ham")])
        .agg(vec![col("spam").sum(), col("ham").sort(false).first()])
        .collect()
}
```

### Expected Behavior

No errors :)

### Installed Versions

<details>
Replace this line with a list of feature gates
</details>

**Comment by andrewpollack** [comment]
Hey @thomasaarholt -- I've looked into this, and I believe I have a fix. I've created a PR at https://github.com/pola-rs/polars-web/pull/58, but without access to the original `foo.csv` I can't fully confirm

```
// in Cargo.toml:
// polars = { git = "https://github.com/pola-rs/polars", features = ["lazy", "parquet"]}

use polars::prelude::*;

fn example() -> Result<DataFrame, PolarsError> {
    LazyCsvReader::new("foo.csv".into())
        .has_header(true)
        .finish()?
        .filter(col("bar").gt(lit(100)))
        .groupby(vec![col("ham")])
        .agg(vec![col("spam").sum(), col("ham").sort(false).first()])
        .collect()
}
```

**Comment by andrewpollack** [comment]
This can be closed now with the merge of https://github.com/pola-rs/polars-web/pull/58
