### ISSUE TITLE
add more flexible renaming options to JoinBuilder

### ISSUE THREAD

**Issue by ozgrakkurt** [pola-rs/polars#4893]
### Problem Description

Right now it only takes `suffix` and applies it only if there are duplicate column names.

It would be more useful if it had also `prefix` option and another setting which would make it apply the renaming even when there aren't any duplicate column names

**Comment by ritchie46** [comment]
You can select and add suffixes/prefixes just before joining. I don't think that logic needs to be in the join operation.

**Comment by ritchie46** [comment]
I will close this as I don't want this extra complexity in the join builders as this complicates the optimization passes.
