### ISSUE TITLE
df.select(<boolean list>) fails with error

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4896]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

The documentation states that a boolean list the same length as the number of columns is a valid input for `pl.DataFrame.select`:

>### [Selecting columns with the select method](https://pola-rs.github.io/polars-book/user-guide/howcani/selecting_data/selecting_data_expressions.html#selecting-columns-with-the-select-method)
>We select columns using the select method. In the select method we can specify the columns with:
>* a (string) column name
>* a list of (string) column names
>* **a boolean list of the same length as the number of columns**
>* an expression such as a condition on the column name
>* a Series

However, using a boolean list raises an error.

### Reproducible Example

```python
import polars as pl

df = pl.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6]
})
df.select([True, False])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\502002823\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\dataframe\frame.py", line 5198, in select
    self.lazy()
  File "C:\Users\502002823\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazyframe\frame.py", line 806, in collect
    return pli.wrap_df(ldf.collect())
exceptions.DuplicateError: Column with name: 'literal' has more than one occurrences
```

### Expected Behavior

```
shape: (2, 1)
┌───────┐
│       │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
├╌╌╌╌╌╌╌┤
│ false │
└───────┘
```

### Installed Versions

<details>

```
---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 6.0.0
pandas: 1.4.3
numpy: 1.22.2
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
```
</details>

**Comment by ritchie46** [comment]
It is an invalid query. You select the literal `True` and the literal `False`, but you don't provide an `alias` for them, so they are both named `"literal"`, resulting in that error.

**Comment by mcrumiller** [comment]
Ok, I understand that. How might one select columns using a boolean list?

**Comment by ritchie46** [comment]
`df[:, [True, False]]`
