### ISSUE TITLE
Implement arrow json writer

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#492]
Similar to CsvWriter, dispatch Polars DataFrame to arrows writer.

Source code to get started:

* [arrow json writer](https://ritchie46.github.io/polars/arrow/json/writer/index.html)
* [polars csv writer](https://ritchie46.github.io/polars/polars_io/csv/struct.CsvWriter.html)

**Comment by oren0e** [comment]
Is this a good issue that can fit a beginner rust programmer? (read the first 13 chapters in the rust book and did some minor coding stuff in rust)
If so, I'm in.

**Comment by ritchie46** [comment]
Yes, this one should be doable. I believe it is very similar to the above mentioned polars csv writer.

**Comment by marcvanheerden** [comment]
can I pick this up? @oren0e

**Comment by oren0e** [comment]
Sure, unfortunately I didn't get to this.
