### ISSUE TITLE
Duration calculation fails when first operand is series

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#4920]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Subtracting from a date-like series raises an error if the 2nd operand is a scalar or column. I've tried many combinations of values, `pl.lit` scalars, `pl.series`, and `pl.col` below. All failure cases (except `val - ser`) involve the first operand being a `pl.Series`.

### Reproducible Example

```python
import polars as pl
from datetime import date
from polars import col

df = pl.DataFrame({
    "t1": [date(2022,6,30)],
    "t2": [date(2022,1,1)]
})
t3 = date(2022,1,1)

# all cases succeed unless labeled as fails
df.with_columns([
    (   col("t1")  -  col("t2")   ).alias("col - col"),
    (   col("t1")  -  t3          ).alias("col - val"),
    (   t3         -  col("t2")   ).alias("val - col"),
    (   col("t1")  -  pl.lit(t3)  ).alias("col - lit"),
    (   pl.lit(t3) -  col("t2")   ).alias("lit - col"),
    (   pl.lit(t3) -  pl.lit(t3)  ).alias("lit - lit"),
    (   pl.lit(t3) -  t3          ).alias("lit - val"),
    (   t3         -  pl.lit(t3)  ).alias("val - lit"),
    (   df["t1"]   -  df["t2"]    ).alias("ser - ser"),
#   (   df["t1"]   -  t3          ).alias("ser - val"),   # fails
#   (   t3         -  df["t2"]    ).alias("val - ser"),   # fails
#   (   df["t1"]   -  pl.lit(t3)  ).alias("ser - lit"),   # fails
    (   pl.lit(t3) -  df["t2"]    ).alias("lit - ser"),
#   (   df["t1"]   -  col("t2")   ).alias("ser - col"),   # fails
    (   col("t1")  -  df["t2"]    ).alias("col - ser"),
])
```

### Expected Behavior

All should succeed.

### Installed Versions

<details>

```
---Version info---
Polars: 0.14.12
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
```
</details>

**Comment by mcrumiller** [comment]
Here's a table view of the success/failure matrix. Types are "col" (`pl.col`), "date" (`datetime.date`), "lit" (`pl.lit`), and "ser" (`pl.Series`)

| 1st type | second type | Fail
|---|---|---|
| col | col | |
| col | val | |
| val | col | |
| col | lit  |  |
| lit | col |  |
| lit | lit |  |
| lit | val |  |
| val | lit |  |
| val | val | X |
| ser | ser | |
| ser | val | X |
| val | ser | X |
| ser | lit | X |
| lit | ser |  |
| ser | col | X |
| col | ser |  |

**Comment by ritchie46** [comment]
Note that `val - val` should fail. This is executed completely in python.

**Comment by mcrumiller** [comment]
Yes, I I labeled that as such above. Probably should have not included it.

**Comment by mcrumiller** [comment]
Hey @ritchie46 , I think this issue needs to be reopened. For series `s` and date/datetime `t`, (s-t) and (t-s) evaluate to the same duration (they should have roughly opposite sign):

```python
s = pl.Series([date(2022, 1 ,1)])
t = date(2022, 1, 2)
print(s-t)
print(t-s)
```

### Output:
```
shape: (1,)
Series: '' [duration[ms]]
[
	-1d
]

shape: (1,)
Series: '' [duration[ms]]
[
	-1d
]
```

`t-s` should evaluate to +1d, not -1d.
