### ISSUE TITLE
.var() method in 24.0 ddof parameter?

### ISSUE THREAD

**Issue by AnatolyBug** [pola-rs/polars#4936]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Question about polars

In **Polars 24.0** version, `.var()` method under `Expr` take `ddof` as an argument. But as far as I know it's not documented _what this parameter actually does_? I am also not able to find the source code where the logic is actually being executed(would be interesting to see how this variable is used)? 

As far as I remember :) there is a well defined formula for unbiased sample variance, hence an additional parameter is rather surprising.

**Comment by mcrumiller** [comment]
It's called the delta degrees of freedom. The usual variance statistic is calculated as `sum(x-m)^2/(n-1)`, where `n-1` is the degrees of freedom. The 1 comes from subtraction of the mean. The more general formula for the degrees of freedom is `n - ddof`, where `ddof` is the number of parameters used to arrive at the calculation. For the normal variance it's 1, hence `ddof=1` is the default value.

**Comment by mcrumiller** [comment]
Also it's documented right in the polars book: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Series.var.html

![image](https://user-images.githubusercontent.com/1896992/191790421-52ce7ffa-4d82-4594-a73d-cfda45d3730d.png)

**Comment by AnatolyBug** [comment]
@mcrumiller I actually thought about degrees of freedom , but didn't realise it applies to sample statistic in that way. Will revise my statistic module notes. Thank you so much!

**Comment by mcrumiller** [comment]
No problem. Want to close this issue?

**Comment by AnatolyBug** [comment]
Indeed, thank!
