### ISSUE TITLE
Sorting a DF results in wrong aggregations

### ISSUE THREAD

**Issue by philss** [pola-rs/polars#4937]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

A strange behavior is happening when we try to sort a dataframe, and then group and summarize it
with the `min` or `max` aggregations - I only tested with these. It is calculating it wrong. 

If we try the same operation with a DF that was not sorted, then everything works fine.

---

This issue was originally found by an user of `Explorer`: https://github.com/elixir-nx/explorer/issues/358
I confirmed that is happening with Polars in the latest release - `0.24.0` and GitHub, from the master branch.

### Reproducible Example

```rust
use polars::prelude::*;

fn main() {
    let df = df! [
        "ts" => [1, 1, 1, 0, 1],
        "price" => [3.3, 3.0, 3.5, 3.6, 3.7],
        "mask" => [1, 1, 1, 1, 0]
    ]
    .unwrap();

    println!("{}", &df);

    let df1 = df.sort(["price"], false).unwrap();

    println!("{}", &df1);

    let groupby = df1.lazy().groupby(["ts"]);

    let df2 = groupby
        .agg([
            (col("price") * col("mask")).max().alias("pmax"),
            (col("price") * col("mask")).min().alias("pmin"),
        ])
        .collect()
        .unwrap();

    println!("{}", &df2);
}
```

### Expected Behavior

I think sorting shouldn't affect these aggregations.
The result should be something like this:

```
shape: (2, 3)
┌─────┬──────┬──────┐
│ ts  ┆ pmax ┆ pmin │
│ --- ┆ ---  ┆ ---  │
│ i32 ┆ f64  ┆ f64  │
╞═════╪══════╪══════╡
│ 1   ┆ 3.5  ┆ 0.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 0   ┆ 3.6  ┆ 3.6  │
└─────┴──────┴──────┘
```

But instead it returns this:

```
shape: (2, 3)
┌─────┬──────┬──────┐
│ ts  ┆ pmax ┆ pmin │
│ --- ┆ ---  ┆ ---  │
│ i32 ┆ f64  ┆ f64  │
╞═════╪══════╪══════╡
│ 1   ┆ 0.0  ┆ 3.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 0   ┆ 3.6  ┆ 3.6  │
└─────┴──────┴──────┘
```

### Installed Versions

<details>
features = [ "fmt", "lazy", "parquet", "performant", "rows", "simd", ]

polars = "0.24.0" # (or from git, ref `c468ab94fcc799d173651d8159264037ddbbc97a` - the problem is present in `0.23` as well)
</details>

**Comment by mcrumiller** [comment]
The issue here is that `df.sort()` is not sorting all columns, only column `price`. In python:

```python
import polars as pl

df = pl.DataFrame({
    "ts": [1, 1, 1, 0, 1],
    "price": [3.3, 3.0, 3.5, 3.6, 3.7],
    "mask": [1, 1, 1, 1, 0]
})

print(df)
print(df.sort(by="price"))
```

```
shape: (5, 3)
┌─────┬───────┬──────┐
│ ts  ┆ price ┆ mask │
│ --- ┆ ---   ┆ ---  │
│ i64 ┆ f64   ┆ i64  │
╞═════╪═══════╪══════╡
│ 1   ┆ 3.3   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.0   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.5   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 0   ┆ 3.6   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.7   ┆ 0    │
└─────┴───────┴──────┘

shape: (5, 3)
┌─────┬───────┬──────┐
│ ts  ┆ price ┆ mask │
│ --- ┆ ---   ┆ ---  │
│ i64 ┆ f64   ┆ i64  │
╞═════╪═══════╪══════╡
│ 1   ┆ 3.0   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.3   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.5   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 0   ┆ 3.6   ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1   ┆ 3.7   ┆ 0    │
└─────┴───────┴──────┘
```

**Comment by mcrumiller** [comment]
I'll open a new issue.

**Comment by mcrumiller** [comment]
I wrote a comment that the `sort()` results were incorrect, but I was being stupid so I deleted it. Sorry for the confusion.

**Comment by philss** [comment]
@mcrumiller no problem!
