### ISSUE TITLE
`df.to_pandas()` gives error, but `df.head(df.shape[0]).to_pandas` works

### ISSUE THREAD

**Issue by Tim-K-DFW** [pola-rs/polars#4938]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

![image](https://user-images.githubusercontent.com/8753831/191800210-1cf4c13b-e13a-4f79-ab33-d9b461813f88.png)

![image](https://user-images.githubusercontent.com/8753831/191800409-83e971da-f6a2-4652-9590-6e36d781c2a0.png)

This only happened on this particular df. The longest element of the `list[f64]` column is a list of ~783,000 floats. I feel this is the reason.

### Reproducible Example

```python
# did not reproduce on this synthetic df, despite same-length list

import numpy as np
import pandas as pd
import polars as pl

df = pd.DataFrame(dict(id = [1, 2]))
df['freq'] = [np.random.rand(784000).tolist(), np.random.rand(10).tolist()]
dfp = pl.DataFrame(df)
dfp.to_pandas()
```

### Expected Behavior

`df.to_pandas()` works as expected (as it has been, except this one case).

### Installed Versions

<details>
``` ---Version info---
Polars: 0.14.12
Index type: UInt32
Platform: Linux-5.4.0-1029-aws-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 4.0.1
pandas: 1.4.3
numpy: 1.21.1
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed> ```
</details>

**Comment by ritchie46** [comment]
Could you check if calling `rechunk` first works?

What is the output of `df.n_chunks("all")`?

**Comment by Tim-K-DFW** [comment]
Really appreciate the quick response.

That context is already gone, cannot reproduce it to check. Next time this happens, will try `rechunk`, if it fixes that, probably will make sense to include it in the exception message.

Thank you for the amazing package.

**Comment by ritchie46** [comment]
It is still a bug 😅
