### ISSUE TITLE
Add BytesIO support to `scan_csv`

### ISSUE THREAD

**Issue by nebfield** [pola-rs/polars#4950]
### Problem Description

Firstly, thank you for making this fantastic library 😀 

I have the following use case:

```
import zstandard
import polars as pl

with open(path, 'rb') as f:
    dctx = zstandard.ZstdDecompressor()
        with dctx.stream_reader(f) as reader:
            df = pl.read_csv(reader, sep='\t')
```

Where `path` is the path of a Zstandard compressed TSV file. I'm working with bioinformatics data, and bioinformaticians love to generate massive CSVs/TSVs and then compress them.

I would like to use `scan_csv` to read the decompressed BytesIO stream instead and take advantage of all the cool lazy evaluation features to reduce memory usage. Alternatively, it would be great if `scan_csv` supported Zstandard compressed file paths directly. 

Thanks for your time!

**Comment by ghuls** [comment]
Out of curiosity, is this Zstandard compressed TSV file public data or is it from an internal pipeline? Never saw any Zstandard compressed TSV files in the wild myself unfortunately.

**Comment by nebfield** [comment]
The file I'm trying to work with is a variant information file from [plink2](https://www.cog-genomics.org/plink/2.0/) (`.pvar.zst` or `.bim.zst`). plink is a popular toolkit used in genome wide association studies and related areas. 

Some public data [are available here](https://www.cog-genomics.org/plink/2.0/resources#phase3_1kg).

**Comment by indigoviolet** [comment]
+1 to this feature request; in the meantime, you can use `pandas.read_csv` or `pyarrow.csv.open_csv` to get some of this behavior.

**Comment by ritchie46** [comment]
Why go via pandas? `pl.read_csv` accepts a `BytesIO`?

**Comment by AroneyS** [comment]
This would also help with https://github.com/pola-rs/polars/issues/7514

**Comment by corneliusroemer** [comment]
I managed to get `read_csv` to work with `with xopen("data.csv.zst", "rb") as f`, see #7287 

@ghuls at Nextstrain we've started to `zst` compress everything, so yeah, there are now `metadata.tsv.zst`'s in the wild :)

**Comment by corneliusroemer** [comment]
> @ritchie46: Why go via pandas? pl.read_csv accepts a BytesIO?

See #9266 why `pl.read_csv` doesn't work in this case, unless I'm doing something wrong, read_csv reads the whole file into memory. I haven't found a way to emulate pandas `usecol` behaviour for `zstd` compressed csvs with polars.

**Comment by ghuls** [comment]
You can use `parquet-fromcsv` in the meantime to convert compressed CSV/TSV files to parquet and use `pl.scan_parquet` on them:
https://github.com/pola-rs/polars/issues/9283#issuecomment-1594512827

**Comment by itamarst** [comment]
Looking through the code, it seems like the limitation eventually devolves to `LazyScanBuilder::scan_csv()`, which accepts a `Into<std::path::PathBuf>`. It then opens that and converts it into a `File`. After a bit of back and forth this gets turned into a `ReaderBytes`.

For a `BytesIO` specifically providing file-like behavior or exposing the underlying bytes as a `ReaderBytes` is easy enough, if `scan_csv()` becomes more lenient in what it accepts (or a new, lower-level method is exposed.)

For the general case... that'd be a more significant refactor.

**Comment by itamarst** [comment]
My first thought for implementation based on above is replacing all `PathBuf` in the various classes (`LogicalPlan::Scan` etc) with:

```rust
enum FileSource {
    Path(PathBuf),
    Reader(Box<dyn MmapBytesReader>),
}
```

**Comment by itamarst** [comment]
But... that's sort of limiting. The more general solution is making the CsvStreamer not assuming the CSV fits in memory. In particular, if csv CoreReader could bee modified to take a GetReaderBytes trait implementor as an input instead of ReaderBytes, which lets you get ReaderBytes at some position and ReaderBytes can implement GetReaderBytes for itself, and much of the code would stay the same.

```rust
trait GetReaderBytes {
    fn read(&self, offset: usize, length: usize) -> ReaderBytes
}
```

**Comment by MaxPowerWasTaken** [comment]
> You can use `parquet-fromcsv` in the meantime to convert compressed CSV/TSV files to parquet and use `pl.scan_parquet` on them: [#9283 (comment)](https://github.com/pola-rs/polars/issues/9283#issuecomment-1594512827)

I think I'm understanding correctly that this is a recommendation to use a rust library. Any advice for the less-cool among us who are still working pretty exclusively from a python environment?

**Comment by ghuls** [comment]
> > You can use `parquet-fromcsv` in the meantime to convert compressed CSV/TSV files to parquet and use `pl.scan_parquet` on them: [#9283 (comment)](https://github.com/pola-rs/polars/issues/9283#issuecomment-1594512827)
> 
> I think I'm understanding correctly that this is a recommendation to use a rust library. Any advice for the less-cool among us who are still working pretty exclusively from a python environment?

It is a command line tool, but part of the rust `arrow` library.

**Comment by MaxPowerWasTaken** [comment]
> > > You can use `parquet-fromcsv` in the meantime to convert compressed CSV/TSV files to parquet and use `pl.scan_parquet` on them: [#9283 (comment)](https://github.com/pola-rs/polars/issues/9283#issuecomment-1594512827)
> > 
> > 
> > I think I'm understanding correctly that this is a recommendation to use a rust library. Any advice for the less-cool among us who are still working pretty exclusively from a python environment?
> 
> It is a command line tool, but part of the rust `arrow` library.

awesome, thanks for the correction, yeah cli tools work for my use case.
