### ISSUE TITLE
DataFrame constructor takes ListOf<dtype> as 'object'

### ISSUE THREAD

**Issue by david-cortes** [pola-rs/polars#4952]
### Problem Description

If I use the DataFrame constructor and have a column that could be represented as `ListOf<type>`, polars will treat it as containing a generic object, as opposed to using the DataFrame constructor on a pandas DataFrame that had the same contents. Would be good if `pl.DataFrame` could also recognize these types of columns.
![polars_list_of_ints](https://user-images.githubusercontent.com/11860098/192012394-500c511a-3fcf-47b9-bc01-989e93ff76a5.png)

**Comment by ritchie46** [comment]
A list of numpy object is exactly that. A list of numpy objects. 

You should pass a list lists, or a 2D numpy array, but not a combination of a python list and numpy.

**Comment by david-cortes** [comment]
But it somehow does the check and converts it when the input is a pandas DataFrame.

Also, when passing a list of lists, it might get the dtype wrong:
![polars_float_arr](https://user-images.githubusercontent.com/11860098/192015494-8db31679-6335-4c79-9b75-145dcdfe655f.png)

**Comment by matteosantama** [comment]
The conversion happens on the `pandas` side.

```python
>>> pd.DataFrame({"a": [np.arange(5)]})
                 a
0  [0, 1, 2, 3, 4]
```

I don't see a good reason to automatically unpack the `numpy` array in `polars`. If you need it unpacked, there are plenty of ways to do it.

```python
pl.DataFrame({"a": np.arange(5)})

pl.DataFrame({"a": [*np.arange(5)]})
```

to list a few

**Comment by ritchie46** [comment]
This pointed out one thing we did not yet do, but we should. Thanks for that.

With #4961 we are also able to take a 2D numpy array and convert that to a list type.

This works:

```python
df = pl.DataFrame({"a": np.arange(5).reshape(1, -1)})
assert df.dtypes == [pl.List(pl.Int64)]
assert df.shape == (1, 1)
df = pl.DataFrame({"a": np.arange(10).reshape(2, -1)})
assert df.dtypes == [pl.List(pl.Int64)]
assert df.shape == (2, 1)
```

What does not work, as pointed out by @matteosantama is combining different container types: (python list, numpy array, polars series, pyarrow array, 1D pandas series) and expecting us to infer the common dtype amongs those nested structures.

This is a whole can of worms, will be slow and is bad type hygiene in my opinion.
