### ISSUE TITLE
CI: Ubuntu (3.10) job failing at linting

### ISSUE THREAD

**Issue by matteosantama** [pola-rs/polars#4957]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of polars.

### Issue Description

You can see the failure [here](https://github.com/pola-rs/polars/actions/runs/3116557703/jobs/5054500608#step:6:12). I don't think the failure is related to the changes in the MR since the Python changes were pretty minimal.

I was able to find a `mypy` [issue](https://github.com/python/mypy/issues/13627) describing the problem. I not sure why I'm only seeing this error now and the original issue is 16 days old, but it seems to be related to an upgrade to Python 3.10.7.

Potential solutions include 1) disabling the job until `mypy` makes a release or 2) trying to pin the Python version <3.10.7. @stinodego I know you've done a lot of recent work on the CI so I wanted to bring this to your attention.

### Reproducible Example

```javascript
NA
```

### Expected Behavior

NA

**Comment by matteosantama** [comment]
There's a second failing job too (see [here](https://github.com/pola-rs/polars/actions/runs/3116557702/jobs/5054500559)). 

I think this one is directly caused by #4946.

**Comment by ritchie46** [comment]
I believe the mypy issue is a bug in mypy: https://github.com/python/mypy/issues/13627.

**Comment by stinodego** [comment]
We can probably pin our linter to Python 3.10.6 for now, until a new mypy version is released. That should solve the issue, right?

**Comment by alexander-beedie** [comment]
>  Or is this one of those lovely kinds of issues that fail only 'sometimes'? 😞

Seems to be "this" - I ran into the same error yesterday, but the force-push of a minor update then caused it to pass...

**Comment by stinodego** [comment]
Ok, let me play around with this a bit!
