### ISSUE TITLE
Time zone conversion

### ISSUE THREAD

**Issue by marchinidavide** [pola-rs/polars#4972]
### Problem Description

Is there a way to convert a `pl.Series` of type `pl.Datetime` from one timezone to another?

**Comment by ritchie46** [comment]
Could you ask this question on stackoverflow? I will answer it there and then other people can learn from it.

**Comment by marchinidavide** [comment]
Sure, will do! Thank you :)

**Comment by ritchie46** [comment]
Sorry, I have to look a bit longer. Currently we only set the timezone but don't modify the timestamp underneath.

**Comment by marchinidavide** [comment]
Thank you!
Having a function `cast_time_zone` (behaviour similar to pandas `tz_convert`) for columns of type `datetime` would be awesome!
