### ISSUE TITLE
Unsigned integers should be avoided in the User API

### ISSUE THREAD

**Issue by has2k1** [pola-rs/polars#4990]
### Problem Description

I have had an issue where a polars operation created a `uint` column, I then passed that column to another library and got a surprising (overflow) result. As a user I can cast the `uint` to `int`, but this is most likely after some debugging.

Here is some exploration showing how easy it can be to err when working with a `uint` but expecting `int` behaviour.

```python
>>> import polars as pl
>>> n = 3
>>> s = pl.Series(range(n))
>>> ranks = s.rank(method='min')  # creates a uint32 series
>>> ranks
shape: (3,)
Series: '' [u32]
[
        1
        2
        3
]
>>> ranks[0] - ranks[-1]  # good, because indexing into a pl.Series[uint32] returns an int
-2
>>> -ranks  # bad
shape: (3,)
Series: '' [u32]
[
        4294967295
        4294967294
        4294967293
]
>>> ranks[::-1].diff()  # bad
shape: (3,)
Series: '' [u32]
[
        null
        4294967295
        4294967295
]
>>> [r - n for r in ranks] # good, because iterating over a pl.Series[uint32] yields ints
[-2, -1, 0]
>>> ranks - n  # bad, and inconsistent with above
shape: (3,)
Series: '' [u32]
[
        4294967294
        4294967295
        0
]

```

I think in the userspace `uint` dtypes should be strictly opt-in.

Elsewhere on unsigned integers:

1. https://wesmckinney.com/blog/avoid-unsigned-integers/
2. https://google.github.io/styleguide/cppguide.html#Integer_Types
3. https://hamstergene.github.io/posts/2021-10-30-do-not-use-unsigned-for-nonnegativity/

**Comment by mcrumiller** [comment]
I've run into a similar issue, whereby for example, when working with `*.dt.days()`, I consistently have to convert to signed integers, as arithmetic fails between them.

I understand both side of the argument. The number of days in a month cannot be negative. But, another common rule is: when the value is something that may be used in arithmetic, i.e. if `a.dt.days() - b.d.days()` is a valid expression, then signed integers should be used.

**Comment by has2k1** [comment]
> I think that many systems do not support unsigned because c++ makes it hard to handle them (and this perculates to downstream systems).

Unsigneds can and should be used under the hood as that a conscious choice, also in the user API to minimise surprises they should be a conscious choice.

```python
ranks = s.rank('min')  # should return ints
ranks_u = s.rank('min').cast(pl.UInt32) # opt-in to uints
```

**Comment by ritchie46** [comment]
In Rust unsigned integers are commonly used, and we mimic the return types of the rust chrono library. Chrono uses unsigned integers to represent the invariants if a certain attribute.

Polars is written in Rust and will adhere more to Rusts type customs than those of C++.

I do agree on the sentiment that it can lead to unexpected results in arithmetic, however I am not sure always returning integers is the answer for that.

**Comment by has2k1** [comment]
> In Rust unsigned integers are commonly used ...

I figured Rust was a safer environment for unsigneds.

This is what I have.

```
1. signed - unsigned   -> signed 
2. unsigned - signed   -> signed
3. unsigned - unsigned -> (un)signed (whatever makes sense)
4. -unsigned           -> signed
5. df.to_pandas()      -> any unsigned columns to signed!
6. s.to_pandas()       -> signed
7. np.ufuncs           -> operate on signed
...
```

Case 5 is what bit me and I realised that since in pandas & numpy you create `uints` explicitly, the packages are not burdened to support operations with them. That means _maybe_ all packages in the "scikit" ecosystem cannot handle them well!

**Comment by slonik-az** [comment]
> ```
> 3. unsigned - unsigned -> (un)signed (whatever makes sense)
> ```

It should be `unsigned - unsigned -> signed` in all cases.
Rational: even if `X-Y` happens to be strictly `>= 0` then `Y-X` will be strictly `<=0` and wrapping around if `unsigned`. For consistency sake, if arithmetic is allowed the result must be `signed`.

**Comment by zundertj** [comment]
> > I think that many systems do not support unsigned because c++ makes it hard to handle them (and this perculates to downstream systems).
> 
> Unsigneds can and should be used under the hood as that is a conscious choice, also in the user API to minimise surprises they should be a conscious choice.
> 
> ```python
> ranks = s.rank('min')  # should return ints
> ranks_u = s.rank('min').cast(pl.UInt32) # opt-in to uints
> ```

There is undeniably a convenience in minimizing the usage of unsigned integers in the api, as arithmetic is easier, but there are also clear downsides. For instance, in your example, there would first be an allocation of an array of type `pl.Int32`, with twice the memory usage of `pl.UInt32`, and then the conversion has to be done. So users looking for unsigned pay double on memory and also pay the conversion cost in your proposal. I don't know if this could potentially be optimized, that polars sees it should not allocate signed ints but unsigned ints on the rank, but my guess is that beyond trivial examples it would be very hard to reason through expressions that it is actually safe to use unsigned integers on all operations. Vice versa, in the current setup with unsigned being the return type, users looking for signed would have the memory allocation anyways, and only pay the conversion cost.

On:

> [...] if arithmetic is allowed the result must be signed

Maybe I am missing the point, but arithmetic is always allowed on unsigned integers. So not sure this rule brings us anything, except abolishing unsigned integers from the api altogether?

**Comment by mcrumiller** [comment]
> there would first be an allocation of an array of type `pl.Int32`, with twice the memory usage of `pl.UInt32`

Not that I'm taking sides here, but why would it have twice the memory usage?

**Comment by zundertj** [comment]
Sorry, that is incorrect indeed. I got triggered by the code example which casts to `Int32` to `UInt32`. I meant to say, assuming you have (positive) values from 0 to X, where X can be represented by `Int32`, you can represent the same by using `UInt16`. I.e. if `rank` would emit `Int32`, the unsigned alternative would be to use `UInt16`, which uses 50% less memory vs `Int32`.

**Comment by stinodego** [comment]
I think it's safe to say that we are going to keep using unsigned integers where appropriate. I'll close this for now.
