### ISSUE TITLE
Issue with Categorical converter in read_csv

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#4991]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Something wrong happens if large chunks of the csv file have the same value repeated.

### Reproducible Example

```python
import polars as pl

N = 5000
pl.DataFrame({"x": ["A"] * N + ["B"] * N}).write_csv("df1.csv")
print(pl.read_csv("df1.csv", dtypes={"x": pl.Categorical}).unique())

shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ cat │
╞═════╡
│ A   │
├╌╌╌╌╌┤
│ A   │
└─────┘
```

### Expected Behavior

```
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ cat│
╞═════╡
│ A   │
├╌╌╌╌╌┤
│ B   │
└─────┘
```

### Installed Versions

<details>
``` Replace this line with the output of pl.show_versions(), leave the backticks in place ```
</details>

**Comment by ritchie46** [comment]
Thanks for the issue report. I will fix it. You can explicitly cast after reading to make it work in the meantime.

**Comment by mcrumiller** [comment]
FYI you can fix this by using the `sample_size` parameter. In your particular case, anything up to `sample_size=4997` produces only `A`, whereas using `sample_size=4998) produces the correct result.

Seeing as the the first 5,000 values are `A`, I'm not sure why the cutoff happens at 4997/4998-- @ritchie46 any insight?

**Comment by ritchie46** [comment]
> FYI you can fix this by using the `sample_size` parameter. In your particular case, anything up to `sample_size=4997` produces only `A`, whereas using `sample_size=4998`) produces the correct result.
> 
> Seeing as the the first 5,000 values are `A`, I'm not sure why the cutoff happens at 4997/4998-- @ritchie46 any insight?

Thanks, it does help debugging. :+1:
