### ISSUE TITLE
groupby transform lambda ewm using polars

### ISSUE THREAD

**Issue by wiamadaya** [pola-rs/polars#4998]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73867715/groupby-transform-lambda-ewm-using-polars

### Question about polars

Hi,

I'm trying to find faster alternative for the following code using polars

`df['ewm'] = df.groupby(['outlet', 'product'])['sales'].transform(lambda x: x.shift(shift).ewm(com=10).mean())`

**Comment by ritchie46** [comment]
Could you ask this question on stackoverflow? I will answer it there, then more people can learn from this.

**Comment by ritchie46** [comment]
Answered!
