### ISSUE TITLE
New join type with expressions and speed up for unique join

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pola-rs/polars#5004]
### Problem Description

Thank you for a great package!

I have the following use-case where I want to calculate distances during voyages. I have 2 datasets. One containing when each vessel started and ended it's voyages (`df_voyages`) and one where I have coordinate data for each hour for each vessel (`df_coor`).

I have created a small example below on how I currently would do it (I think this is the best right now?). However, this doesn't take use of **the fact that I know that the voyages within a vessel never overlaps**, and that **each row in `df_coor` maps to only one or no rows in `df_voyages`.** 

What I'm suggesting is a join type which can be based on expressions (leq/geq) and where you can say that it should just join on the first match so it doesn't have to scan through and look for all possible matches. The problem grows a lot if each vessel has done a lot of voyages.

```python
import polars as pl
from datetime import datetime, timedelta
n = 5000
start_time = datetime(2021, 9, 30)
```

```python
df_coor = pl.DataFrame(
    {
        "vessel_id": [1] * n + [2] * n,
        "timestamp": [start_time + timedelta(hours=h) for h in range(n)]
        + [start_time + timedelta(hours=h) for h in range(n)],
        "x_coor": [1.0 * h for h in range(n)] + [1.0 * h for h in range(n)],
        "y_coor": [1.0 * h for h in range(n)] + [1.0 * h for h in range(n)],
    }
).lazy()
df_coor.head(5).collect()
```
<html>
<body>
<small style="color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (5, 4)</small>

vessel_id | timestamp | x_coor | y_coor
-- | -- | -- | --
i64 | datetime[μs] | f64 | f64
1 | 2021-09-30 00:00:00 | 0.0 | 0.0
1 | 2021-09-30 01:00:00 | 1.0 | 1.0
1 | 2021-09-30 02:00:00 | 2.0 | 2.0
1 | 2021-09-30 03:00:00 | 3.0 | 3.0
1 | 2021-09-30 04:00:00 | 4.0 | 4.0

</body>
</html>

```python
df_voyages = pl.DataFrame(
    {
        "vessel_id": [1, 1, 1, 2, 2],
        "voyage_id": [1, 2, 3, 1, 2],
        "voyage_start": [
            datetime(2022, 1, 1),
            datetime(2022, 1, 20),
            datetime(2022, 3, 5),
            datetime(2022, 1, 5),
            datetime(2022, 2, 18),
        ],
        "voyage_end": [
            datetime(2022, 1, 20),
            datetime(2022, 2, 5),
            datetime(2022, 3, 30),
            datetime(2022, 2, 15),
            datetime(2022, 3, 1),
        ],
    }
).lazy()
df_voyages .head(5).collect()
```
<html>
<body>
<br class="Apple-interchange-newline">

vessel_id | voyage_id | voyage_start | voyage_end
-- | -- | -- | --
i64 | i64 | datetime[μs] | datetime[μs]
1 | 1 | 2022-01-01 00:00:00 | 2022-01-20 00:00:00
1 | 2 | 2022-01-20 00:00:00 | 2022-02-05 00:00:00
1 | 3 | 2022-03-05 00:00:00 | 2022-03-30 00:00:00
2 | 1 | 2022-01-05 00:00:00 | 2022-02-15 00:00:00
2 | 2 | 2022-02-18 00:00:00 | 2022-03-01 00:00:00

</body>
</html>

```python
q = (
    df_voyages.join(df_coor, on="vessel_id")
    .filter(
        (pl.col("timestamp") > pl.col("voyage_start"))
        & (pl.col("timestamp") < pl.col("voyage_end"))
    )
    .groupby(["vessel_id", "voyage_id"])
    .agg(
        [
            (
                (
                    (pl.col("x_coor") - pl.col("x_coor").shift(1)) ** 2
                    + (pl.col("y_coor") - pl.col("y_coor").shift(1)) ** 2
                )
                ** 0.5
            )
            .sum()
            .alias("distance")
        ]
    )
)
q.collect()
```
<html>
<body>
<small style="color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (5, 3)</small>

vessel_id | voyage_id | distance
-- | -- | --
i64 | i64 | f64
1 | 3 | 845.69971
1 | 1 | 642.052957
1 | 2 | 540.229581
2 | 2 | 370.523953
2 | 1 | 1388.757718

</body>
</html>

**Comment by thomasfrederikhoeck** [comment]
An initial take could be something like the following: 

```python
q = (
    df_voyages.join_first_match(
        df_coor,
        on="vessel_id",
        expr_cond=[
            (pl.col("timestamp") > pl.col("voyage_start"))
            & (pl.col("timestamp") < pl.col("voyage_end"))
        ],
    )
    .groupby(["vessel_id", "voyage_id"])
    .agg(
        [
            (
                (
                    (pl.col("x_coor") - pl.col("x_coor").shift(1)) ** 2
                    + (pl.col("y_coor") - pl.col("y_coor").shift(1)) ** 2
                )
                ** 0.5
            )
            .sum()
            .alias("distance")
        ]
    )
)
q.collect()
```

**Comment by mcrumiller** [comment]
I think you're underestimating the amount of effort people have spent developing efficient join algorithms. Modern join algorithms rarely do exhaustive searches on data, unless the data is inherently unsortable. A typical join on data that you're describing involves the following steps:

1. Sort the left dataframe
2. Sort the right dataframe.
3. Perform a merge join (i.e. zipper merge).

If your data is sorted, this join is almost linear with the number of records. No need to worry about efficiency here. Are you seeing massive slowdowns on big data sets?

**Comment by cbilot** [comment]
Let's see if I can help.  Polars has a [`join_asof`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.join_asof.html#polars.LazyFrame.join_asof) designed to speed up exactly this type of situation.

For this problem, we can use `join_asof` to find the latest `voyage_start` that is on or before each `timestamp`.  Note that to use a `join_asof`, the temporal join columns of both datasets must be pre-sorted.  For example:
```python3
(
    df_coor
    .sort('timestamp')
    .join_asof(
        df_voyages
        .with_column(pl.col('voyage_start').alias('voyage_start_dup'))
        .sort('voyage_start'),
        right_on='voyage_start',
        left_on='timestamp',
        by='vessel_id',
        strategy='backward',
    )
    .filter(pl.col('timestamp') <= pl.col('voyage_end'))
    .collect()
)
```
```
shape: (2692, 7)
┌───────────┬─────────────────────┬────────┬────────┬───────────┬─────────────────────┬─────────────────────┐
│ vessel_id ┆ timestamp           ┆ x_coor ┆ y_coor ┆ voyage_id ┆ voyage_end          ┆ voyage_start_dup    │
│ ---       ┆ ---                 ┆ ---    ┆ ---    ┆ ---       ┆ ---                 ┆ ---                 │
│ i64       ┆ datetime[μs]        ┆ f64    ┆ f64    ┆ i64       ┆ datetime[μs]        ┆ datetime[μs]        │
╞═══════════╪═════════════════════╪════════╪════════╪═══════════╪═════════════════════╪═════════════════════╡
│ 1         ┆ 2022-01-01 00:00:00 ┆ 2232.0 ┆ 2232.0 ┆ 1         ┆ 2022-01-20 00:00:00 ┆ 2022-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-01-01 01:00:00 ┆ 2233.0 ┆ 2233.0 ┆ 1         ┆ 2022-01-20 00:00:00 ┆ 2022-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-01-01 02:00:00 ┆ 2234.0 ┆ 2234.0 ┆ 1         ┆ 2022-01-20 00:00:00 ┆ 2022-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-01-01 03:00:00 ┆ 2235.0 ┆ 2235.0 ┆ 1         ┆ 2022-01-20 00:00:00 ┆ 2022-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...       ┆ ...                 ┆ ...    ┆ ...    ┆ ...       ┆ ...                 ┆ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-03-29 21:00:00 ┆ 4341.0 ┆ 4341.0 ┆ 3         ┆ 2022-03-30 00:00:00 ┆ 2022-03-05 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-03-29 22:00:00 ┆ 4342.0 ┆ 4342.0 ┆ 3         ┆ 2022-03-30 00:00:00 ┆ 2022-03-05 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-03-29 23:00:00 ┆ 4343.0 ┆ 4343.0 ┆ 3         ┆ 2022-03-30 00:00:00 ┆ 2022-03-05 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 2022-03-30 00:00:00 ┆ 4344.0 ┆ 4344.0 ┆ 3         ┆ 2022-03-30 00:00:00 ┆ 2022-03-05 00:00:00 │
└───────────┴─────────────────────┴────────┴────────┴───────────┴─────────────────────┴─────────────────────┘
```
Notice how the `timestamp` column falls between the `voyage_end` and the `voyage_start_dup`.  (I created a duplicate column for discussion because `join_asof` will not maintain the temporal column of the dataset on the right in a `join_asof`.)  The result slightly differs from your output in that I used `>=` and `<=` as my conditions.  (I think that's what you'd want.)

The full algorithm would be (eliminating the need for duplicating the `voyage_start`):
```python3
(
    df_coor
    .sort('timestamp')
    .join_asof(
        df_voyages
        .sort('voyage_start'),
        right_on='voyage_start',
        left_on='timestamp',
        by='vessel_id',
        strategy='backward',
    )
    .filter(pl.col('timestamp') <= pl.col('voyage_end'))
    .groupby(["vessel_id", "voyage_id"])
    .agg(
            (
                pl.sum([
                    pl.col('x_coor').diff() ** 2,
                    pl.col('y_coor').diff() ** 2,
                ]) ** 0.5
            )
            .sum()
            .alias("distance")
    )
    .collect()
)
```
```
shape: (5, 3)
┌───────────┬───────────┬─────────────┐
│ vessel_id ┆ voyage_id ┆ distance    │
│ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ f64         │
╞═══════════╪═══════════╪═════════════╡
│ 1         ┆ 2         ┆ 543.058008  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 1         ┆ 643.467171  │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2         ┆ 1         ┆ 1391.586145 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2         ┆ 2         ┆ 373.35238   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1         ┆ 3         ┆ 848.528137  │
└───────────┴───────────┴─────────────┘
```
(Again, I included the voyage endpoints, so my results may differ from yours.)

Would this help your use case?  It should speed things up rather nicely.

**Comment by thomasfrederikhoeck** [comment]
@mcrumiller I most definitely do :-D

@cbilot Thank you! That does the trick. Using the following assumptions (and if my math is correct) the join in my original query would result in 657,000,000,000 rows ( :-O ) before the filter happens, while yours is only 1,314,000,000 - nice!

- There is 10 years of hourly data so 87,600 per vessel
- There is 15,000 vessels
- Each vessel has performed 500 voyages evenly spread

I wills close this.
