### ISSUE TITLE
Leading EWM value when `min_periods < 2` (should be `null`, not zero?)

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#5006]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

There's a difference/discontinuity when setting `min_periods < 2` between the polars and pandas results. Would like to confirm the expected behaviour; comes down to the first value being `0.0` (polars), instead of `null` (pandas).

My sense is that it should be `null`, as we can't actually have calculated the first value?
(Possibly one for @matteosantama ... :)

### Reproducible Example

```python
import polars as pl
s = pl.Series([0,1,2,3,4,5])

s.ewm_std(com=0.5,min_periods=1)
# Series: '' [f64]
# [
#     0.0        << numeric zero; should be null?
#     0.707107
#     0.919866
#     1.059753
#     1.141624
#     1.185252
# ]

s.to_pandas().ewm(com=0.5,min_periods=1).std()
# 0         NaN    << pandas null-equivalent value
# 1    0.707107
# 2    0.919866
# 3    1.059753
# 4    1.141624
# 5    1.185252
# dtype: float64
```

### Expected Behavior

Suspect the first value when `min_periods < 2` should actually be `null`? 

Note that once `min_periods >= 2`, the leading `null` values match:

```python
pl.Series([0,1,2,3]).ewm_std(com=0.5,min_periods=3)
# Series: '' [f64]
# [
#     null
#     null
#     0.919866
#     1.059753
# ]

pl.Series([0,1,2,3]).to_pandas().ewm(com=0.5,min_periods=3).std()
# 0         NaN
# 1         NaN
# 2    0.919866
# 3    1.059753
# dtype: float64
``` 

### Installed Versions

<details>
---Version info---

Polars: 0.14.14
Index type: UInt32
Platform: macOS-12.6-arm64-64bit
Python: 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)]

---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
</details>

**Comment by matteosantama** [comment]
This is actually intentional. `pandas` is inconsistent with respect to whether `bias` is `True` or `False`

```python
>>> pd.Series([1, 2, 3]).ewm(min_periods=1, alpha=0.5).std(bias=False)
0         NaN
1    0.707107
2    0.963624
dtype: float64

>>> pd.Series([1, 2, 3]).ewm(min_periods=1, alpha=0.5).std(bias=True)
0    0.000000
1    0.471405
2    0.728431
dtype: float64
```

`min_periods=2` should certainly have the first value be null

```python
>>> pd.Series([1, 2, 3]).ewm(min_periods=2, alpha=0.5).std(bias=True)
0         NaN
1    0.471405
2    0.728431
dtype: float64

>>> pd.Series([1, 2, 3]).ewm(min_periods=2, alpha=0.5).std(bias=False)
0         NaN
1    0.707107
2    0.963624
dtype: float64
```

**Comment by alexander-beedie** [comment]
Interesting... perhaps my understanding of the `min_periods` param is off-by-one (I'd previously been thinking that `min_periods=0` might be required to avoid a leading null ;)

_`Minimum number of observations in window required to have a value (otherwise result is null).`_

If the above is indeed expected/correct, happy to close.

**Comment by matteosantama** [comment]
Yes, that statement is accurate. With `min_periods=1` we only need 1 value to compute a value, ie. we can compute a valid std at the first position. 

 In general for a non-null series `min_periods=n` should yield `n-1` nulls. `min_periods=1` and `min_periods=0` are equivalent.

**Comment by alexander-beedie** [comment]
> `min_periods=1` and `min_periods=0` are equivalent.

Got it, thanks -  this is likely the source of my misunderstanding; will close.
