### ISSUE TITLE
Implement bitwise aggregation

### ISSUE THREAD

**Issue by jg2562** [pola-rs/polars#5009]
### Problem Description

Implement "bitwise and" and "bitwise or" aggregation for expressions and series. This would be similar to the bitwise reduction in [numpy](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_or.html) with `np.bitwise_or.reduce(arr)`. This is very helpful for any data measured about bits themselves or packed into bits. "bitwise xor" might also be something to consider.

Potentially also allowing for bit shifts with expressions would be very helpful as well.

**Comment by Gigioliva** [comment]
👍🏼 this feature would be really useful 🙏🏼

**Comment by jg2562** [comment]
Another potentially helpful function would be `bit_count` where it sums the number of set bits within a number. I could also try to implement this, but im not sure where to begin if someone could point me in the right direction

**Comment by stinodego** [comment]
This feature is welcome. We can start with `bit_and`, `bit_or`, and `bit_xor`. Other bit aggregations can be considered at a later point.

**Comment by coastalwhite** [comment]
This was implemented by #18994.
