### ISSUE TITLE
Numpy `ufunc` type-inference (for Expr) can't distinguish between Float32 / Float64 (raising SchemaError)

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#5012]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Applying numpy `ufunc` against Float32 columns fails, as the type inference inside `Expr.__array_ufunc__` forces `return_dtype` to Float64. 

Setting `return_dtype` to None or Float32 (while debugging the issue) causes the calculation to succeed, so it's just the forcing to Float64 at issue, rather than Float32 ops not working.

### Reproducible Example

```python
import numpy as np
import polars as pl

# create some 32bit test data
df = pl.DataFrame(
    data = {"nvals": [1,2,3,4,5]},
    columns = [("nvals",pl.Float32)]
)

# apply numpy ufunc
df.select( np.log1p(pl.col("nvals")) )

# SchemaError: Expected output type: 'Float64', but got 'Float32'.
#  Set 'return_dtype' to the proper datatype.
```

### Expected Behavior

Numpy `ufunc` calculations should succeed against Float64 _and_ Float32 columns.

### Installed Versions

<details>
 ---Version info---

Polars: 0.14.14
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---

pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
</details>

**Comment by ghuls** [comment]
It works with Series, but not with expressions:

```pyhon
In [6]: np.log1p(df.get_column("nvals"))
Out[6]: 
shape: (5,)
Series: 'nvals' [f32]
[
	0.693147
	1.098612
	1.386294
	1.609438
	1.791759
]
```

https://github.com/pola-rs/polars/issues/3228

**Comment by ghuls** [comment]
@ritchie46 Is there a way to get the dtype of an expression?

**Comment by alexander-beedie** [comment]
I'm curious what the advantages are of explicitly setting `result_type` to Float64 vs leaving as None (given that it succeeds if None), eg: certain classes of `ufunc` need it, some don't. If so, maybe we can characterize those, and set/don't set accordingly?

Not sure how one would go about inferring the dtype from a bare Expr, as it won't _know_ its own dtype until bound to the Frame/Series, hmm.

**Comment by ritchie46** [comment]
> @ritchie46 Is there a way to get the dtype of an expression so we can detect it in `__array_ufunc__` of `py-polars/polars/internals/expr/expr.py`?

If you put the expression in a context then you can get the schema.

```python
df = # some dataframe

context = df.lazy()
dtype context.select(expression).schema.values()[0]
```

**Comment by ghuls** [comment]
> I'm curious what the advantages are of explicitly setting `result_type` to Float64 vs leaving as None (given that it succeeds if None), eg: certain classes of `ufunc` need it, some don't? If so, maybe we can characterize those, and set/don't set accordingly?
> 

Indeed it seems to work with None now.

Now that I look at it closer, it seems that we call the eager implementation in the end (which I fixed), so it makes sense.

Will work on this.

**Comment by ghuls** [comment]
Fixed in master.
