### ISSUE TITLE
Float parsing errors in the JSON parser after 0.24.0

### ISSUE THREAD

**Issue by philss** [pola-rs/polars#5021]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

While updating Polars from `0.23.2` to `0.24.2` (PR here: https://github.com/elixir-nx/explorer/pull/360) I found a small regression in the (ND)JSON parser: some float numbers started to be parsed wrongly. For example, a value that should be `0.6` started to be parsed as `0.6000000000000001`.

### Reproducible Example

```rust
use polars::prelude::*;
use std::io::Cursor;

fn main() {
    let basic_json = r#"{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":-10, "b":-3.5, "c":true, "d":"4"}
{"a":2, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":7, "b":-3.5, "c":true, "d":"4"}
{"a":1, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":5, "b":-3.5, "c":true, "d":"4"}
{"a":1, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":1, "b":-3.5, "c":true, "d":"4"}
{"a":100000000000000, "b":0.6, "c":false, "d":"text"}
"#;

    let file = Cursor::new(basic_json);
    let df = JsonReader::new(file)
        .infer_schema_len(Some(3))
        .with_json_format(JsonFormat::JsonLines)
        .with_batch_size(3)
        .finish()
        .unwrap();

    let b = &df.get_columns()[1];
    let b_vec: Vec<f64> = b.f64().unwrap().into_iter().map(|v| v.unwrap()).collect();

    assert_eq!(
        vec![2.0, -3.5, 0.6, 2.0, -3.5, 0.6, 2.0, -3.5, 0.6, 2.0, -3.5, 0.6],
        b_vec
    );
}
```

### Expected Behavior

It should respect the float precision of the number in the file (if that precision is under the float 64 size).

### Installed Versions

<details>
features = [
  "fmt",
  "lazy",
  "json",
  "rows",
  "simd",
]

PS: I think the problem started after https://github.com/pola-rs/polars/pull/4424
PS2: After that PR introducing `simd_json`, compiling to `arm` (32 bits) is not possible due to https://github.com/simd-lite/value-trait/issues/26 that is a dependency of that crate.
</details>

**Comment by philss** [comment]
> This is due to the use of simd_json having checked the commits. It was pulled https://github.com/pola-rs/polars/pull/4424

Yeah, I think it was introduced there. Would be nice if we could have the `simd_json` under a feature.

**Comment by ritchie46** [comment]
> > This is due to the use of simd_json having checked the commits. It was pulled #4424
> 
> Yeah, I think it was introduced there. Would be nice if we could have the `simd_json` under a feature.

Could we take this upstream and see if we can fix the root cause?

**Comment by philss** [comment]
> Could we take this upstream and see if we can fix the root cause?

Sure! I'm going to prepare a bug report there.

**Comment by philss** [comment]
@ritchie46 the problem with floats was fixed upstream, with a slight penalty in performance in some cases - see https://github.com/simd-lite/simd-json/pull/253#issuecomment-1281181853. I'm waiting a new release to send a PR.

However we are facing a different problem related to the `simd-json` dependency: it is not compiling against ARM (32 bits) targets.
This issue should be more complicated to fix (https://github.com/simd-lite/simd-json/issues/255), so I'm planning to disable the `json` feature if the target arch is arm.

I would like to know if this is an issue for Polars. And if so, do you consider to have the usage of `simd-json` under a feature flag? I can open another issue to discuss if you prefer. Thanks!

**Comment by philss** [comment]
The problem was fixed on master, so I'm closing this.
