### ISSUE TITLE
Create struct from namedtuple and dataclass

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5022]
### Problem Description

The closest python analogues of the `pl.Struct` dtype are the `namedtuple` and `dataclass` types.

It would be good if Polars supported creating a Series from sequences of `namedtuple`/`dataclass`.

As well as supporting this conversion it would also help us to explain what the `pl.Struct` dtype is as it has more in common with these types than a python dict.

This is how it would look for a `dataclass`:
```python
from dataclasses import dataclass

@dataclass
class TradeRecord:
    exporter: str
    importer: str
    quantity: float

trade0 = TradeRecord(exporter="India",importer="USA",quantity=0.5)
trade1 = TradeRecord(exporter="India",importer="USA",quantity=1.5)

trades = [trade0,trade1]
df = pl.DataFrame({'trades':trades})
df
shape: (2, 3)
┌──────────┬──────────┬──────────┐
│ exporter ┆ importer ┆ quantity │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ str      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ India    ┆ USA      ┆ 0.5      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ India    ┆ USA      ┆ 1.5      │
└──────────┴──────────┴──────────┘
```
or for a `nampedtuple`:
```python
from typing import NamedTuple

tradeNT = NamedTuple("TradeRecord", [('exporter', str), ('importer', str),("quantity",float)])
trade0 = tradeNT(exporter="India",importer="USA",quantity=0.5)
trade1 = tradeNT(exporter="India",importer="USA",quantity=1.5)

trades = [trade0,trade1]
df = pl.DataFrame({'trades':trades})
df
shape: (2, 3)
┌──────────┬──────────┬──────────┐
│ exporter ┆ importer ┆ quantity │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ str      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ India    ┆ USA      ┆ 0.5      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ India    ┆ USA      ┆ 1.5      │
└──────────┴──────────┴──────────┘
```

We could also consider these as export options for a `pl.Struct` series

**Comment by cbilot** [comment]
#4807

**Comment by matteosantama** [comment]
If I understand what you're asking for, we already support this

```python
import polars as pl
from dataclasses import dataclass

@dataclass
class TradeRecord:
    exporter: str
    importer: str
    quantity: float

trade0 = TradeRecord(exporter="India",importer="USA",quantity=0.5)
trade1 = TradeRecord(exporter="India",importer="USA",quantity=1.5)

trades = [trade0,trade1]

>>> pl.DataFrame(trades)
shape: (2, 3)
┌──────────┬──────────┬──────────┐
│ exporter ┆ importer ┆ quantity │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ str      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ India    ┆ USA      ┆ 0.5      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ India    ┆ USA      ┆ 1.5      │
└──────────┴──────────┴──────────┘
```

**Comment by braaannigan** [comment]
@matteosantama @cbilot 
We support e.g. dataclass -> DataFrame, I'm proposing dataclass -> Series as a Struct dtype

**Comment by matteosantama** [comment]
Ah I see. Yes, I agree that would be a nice addition. Currently for a `Series` we construct an `object` dtype

```python
>>> pl.Series(trades)
shape: (2,)
Series: '' [o][object]
[
	TradeRecord(exporter='India', importer='USA', quantity=0.5)
	TradeRecord(exporter='India', importer='USA', quantity=1.5)
]
```

**Comment by cbilot** [comment]
Oh, I see.  So in some sense
```python3
pl.DataFrame({
    "trades": trades,
    "other_col": [1, 2]
})
```
would be syntactic sugar for
```python3
pl.DataFrame({
    'trades': pl.DataFrame(trades).to_struct('trades'),
    'other_col': [1, 2],
})
```
```
shape: (2, 2)
┌─────────────────────┬───────────┐
│ trades              ┆ other_col │
│ ---                 ┆ ---       │
│ struct[3]           ┆ i64       │
╞═════════════════════╪═══════════╡
│ {"India","USA",0.5} ┆ 1         │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ {"India","USA",1.5} ┆ 2         │
└─────────────────────┴───────────┘
```

And
```python3
pl.struct(trades).alias('trades')
```
would be syntactic sugar for:
```python3
pl.DataFrame(trades).to_struct('trades')
```
```
shape: (2,)
Series: 'trades' [struct[3]]
[
        {"India","USA",0.5}
        {"India","USA",1.5}
]
```
Is that the general idea?

**Comment by braaannigan** [comment]
> Ah I see. Yes, I agree that would be a nice addition. Currently for a `Series` we construct an `object` dtype
> 
> ```python
> >>> pl.Series(trades)
> shape: (2,)
> Series: '' [o][object]
> [
> 	TradeRecord(exporter='India', importer='USA', quantity=0.5)
> 	TradeRecord(exporter='India', importer='USA', quantity=1.5)
> ]
> ```
> 
> Only consideration I can think of is what if the `dataclass` has associated methods? Does a `Struct` preserve those?

No, don't see any need for that

**Comment by braaannigan** [comment]
> Is that the general idea?

That could work though it might be less efficient to turn a dataclass/namedtuple to a dataframe and a dataframe to a struct instead of just iterating through the dataclass/namedtuple directly to be a Series

**Comment by alexander-beedie** [comment]
> That could work though it might be less efficient to turn a dataclass/namedtuple to a dataframe and a dataframe to a struct instead of just iterating through the dataclass/namedtuple directly to be a Series

I believe the `DataFrame -> struct -> Series` chain is essentially free (no copies).

I can look at adding this, unless anyone else has already jumped on it?
(I added `dataclass/namedtuple -> DataFrame` a couple of weeks back in https://github.com/pola-rs/polars/pull/4807, so no objection to completing the set ;)

**Comment by alexander-beedie** [comment]
@braaannigan: Done (#5057)  ;)

It's a nice/clean idea, and pairs well with the earlier patch; thanks for the suggestion!
