### ISSUE TITLE
Polars docs site returns 404?

### ISSUE THREAD

**Issue by neilfrndes** [pola-rs/polars#5027]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Question about polars

I get a 404 while trying to visit the official docs website https://pola-rs.github.io/polars/py-polars/html/reference/index.html

Same 404 error when checking via a down detector site: https://www.isitdownrightnow.com/pola-rs.github.io.html

**Comment by timkpaine** [comment]
https://www.pola.rs/

**Comment by ritchie46** [comment]
Thanks for pointing that out. #5028 should fix it.
