### ISSUE TITLE
printing any Series is limited to 25 elements maximum

### ISSUE THREAD

**Issue by slonik-az** [pola-rs/polars#5046]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Currently, `polars` limits the printed output of any Series to 25 elements maximum. If a series is larger than 25 elements the first 12 and the last 12 elements are printed for a total of 24. The limit of 25 is hard-coded (see `const LIMIT` in `polars/polars-core/src/fmt.rs`). On the other hand for a `DataFrame` the maximum number of rows printed can be controlled with `polars.Config.set_tbl_rows` function. Following the Principle of Least Surprise I would expect prining `Series` to behave similar to printing a `DataFrame` with the same degree of user controls.

### Reproducible Example

```python
import polars as pl
import numpy as np
ser = pl.Series('ser', np.arange(1, 1+32))
print(ser)
```

### Expected Behavior

I would expect `polars.Config.set_tbl_rows` to control maximum number of rows when printing a `Series` the same way it does it in the case of a `DataFrame`.

### Installed Versions

<details>
```

---Version info---
Polars: 0.14.14
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8

```
</details>

**Comment by slonik-az** [comment]
I think I know how to fix it. I will create a PR shortly.

**Comment by mcrumiller** [comment]
On a similar note, is there an option such as supplying `-1` or `0` to indicate "print all, regardless of how many"?

**Comment by slonik-az** [comment]
Actually my PR #5047 does that too. If you set `Config.set_tbl_rows(0)` then all the rows of DatFrame and Series will be printed. The same is true for DataFrame columns with `Config.set_tbl_cols(0)`.
