### ISSUE TITLE
Benchmark Python performance with pyo3 `abi3` turned off

### ISSUE THREAD

**Issue by kylebarron** [pola-rs/polars#5049]
Polars is able to distribute only a few wheels because it uses [pyo3's `abi3` support](https://pyo3.rs/latest/building_and_distribution.html#py_limited_apiabi3), but those docs also say:

> The downside of this is that PyO3 can't use optimizations which rely on being compiled against a known exact Python version.

Since polars is very performance focused, maybe it would make sense to remove the `abi3` support defined here:
https://github.com/pola-rs/polars/blob/527ae86f7996bea60b7ae1bb4be48229d515e115/py-polars/Cargo.toml#L34
and distribute Python-version-specific wheels? I'm curious if that could lead to a perf improvement for newer versions of Python.

_Originally posted by @kylebarron in https://github.com/pola-rs/polars/issues/4850#issuecomment-1247296288_

**Comment by stinodego** [comment]
Thanks for making a separate issue for this. I discussed this with Ritchie today. By far most of the performance comes from the Rust implementation, which should not be affected by the Python version. So the gain from compiling separate wheels for each Python version is expected to minimal.

Still, I think it's worth verifying this and doing a benchmark.
