### ISSUE TITLE
tag py-polars-v0.14.14 moved to a wrong commit

### ISSUE THREAD

**Issue by slonik-az** [pola-rs/polars#5052]
The `py-polars-v0.14.14` tag was pointing to `1d955b80` (`python polars 0.14.14`).
Today it moved to `bf8d3922` (`python polars 0.14.15`) in the `dev` branch.
Looks like a confusing typo.

Also, `py-polars-v0.14.14` seems to be closer to the `HEAD` than `py-polars-v0.14.15` which does not make sense. Is `py-polars-v0.14.15` in a wrong position?

**Comment by slonik-az** [comment]
Even better 😄 : Tag is named `py-polars-v0.14.14` but `Cargo.toml` says `version = "0.14.15"`. 

Please, whoever has write access to the repo move `py-polars-v0.14.14` tag to its previous position `1d955b806e3fdda03ff9e5492d7796de5b930147`

**Comment by stinodego** [comment]
We are working on this right now!

**Comment by stinodego** [comment]
Should be fixed now.
