### ISSUE TITLE
Bug Report - Python needs newlines in the Installed versions section

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5068]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The `Installed Versions` section of the bug report form has the following instructions:

```
<details>
``` Replace this line with the output of pl.show_versions(), leave the backticks in place ```
</details>
```

If you replace that line and leave the backticks in place, the details section shows up like this:

<details>
``` ---Version info---
Polars: 0.14.15
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8 ```
</details>

Almost every issue in which the OP includes version information looks like the above unformatted result. Instead, the instructions should be:

    <details>
    
    ```
    Replace this line with the output of pl.show_versions(), leave the backticks in place
    ```
    </details>

which results in the much nicer:

<details>

```
---Version info---
Polars: 0.14.15
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
```
</details>

**Comment by mcrumiller** [comment]
I realize this is a sort of silly issue, don't kill me.

**Comment by zundertj** [comment]
Yes, there should be a newline, but in the template, there are newlines before and after already: https://raw.githubusercontent.com/pola-rs/polars/master/.github/ISSUE_TEMPLATE/bug_report_python.yml. So it seems GH does some funny parsing here, dropping newlines.

**Comment by mcrumiller** [comment]
So the [YAML specification] specifies this:

> ## 2.3. Scalars
> [Scalar content](https://yaml.org/spec/1.2.2/#scalar) can be written in [block](https://yaml.org/spec/1.2.2/#scalars) notation, using a [literal style](https://yaml.org/spec/1.2.2/#literal-style) (indicated by “|”) where all [line breaks](https://yaml.org/spec/1.2.2/#line-break-characters) are significant. Alternatively, they can be written with the [folded style](https://yaml.org/spec/1.2.2/#folded-style) (denoted by “>”) where each [line break](https://yaml.org/spec/1.2.2/#line-break-characters) is [folded](https://yaml.org/spec/1.2.2/#line-folding) to a [space](https://yaml.org/spec/1.2.2/#white-space-characters) unless it ends an [empty](https://yaml.org/spec/1.2.2/#empty-lines) or a [more-indented](https://yaml.org/spec/1.2.2/#example-more-indented-lines) line.

Your template shows the following relevant section:

```yaml
  - type: textarea
    id: version
    attributes:
      label: Installed versions
      description: >
        Please paste the output of ``pl.show_versions()``
      value: >
        <details>

        ```
        Replace this line with the output of pl.show_versions(), leave the backticks in place
        ```

        </details>
    validations:
      required: true
```

I believe that we can simply replace the `value: >` with `value: |` and it fixes the problem. I've created a PR.
