### ISSUE TITLE
Kernel panic during cast

### ISSUE THREAD

**Issue by momentlost** [pola-rs/polars#5078]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When trying to convert some numpy arrays into polars Series, polars make the kernel to panic and gets to restart the python kernel.

### Reproducible example

```python
import numpy as np
import polars as pl

N = 3000

### Sketch of the FWL theorem
# DGP
Dj = np.random.binomial(1, 0.3, size = N)
post = np.random.binomial(1, 0.5, size = N)
y = -2 + 3 * Dj + 1 * post + 2 * Dj * post + np.random.normal(0, 1, size = N)

# Form the orthogonal projection matrix
X_mat = np.matrix([np.ones((N,)),Dj,post]).T
XtX_mat = X_mat.T @ X_mat

# Project onto the orthogonal space
P_mat = X_mat @ np.linalg.inv(XtX_mat) @ X_mat.T
M_mat = np.eye(N) - P_mat

Mint = M_mat @ (Dj * post)
Mconst = (M_mat @ (np.ones((N,1)))).T
My = M_mat @ y



### The following line causes python kernel panic and leads to the restart of the kernel
pl.Series("My", My, dtype = pl.Float64)
```

### Expected behavior

It should simply convert the numpy array "My" to a polars series.

### Installed versions

---Version info---
Polars: 0.14.15
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>

**Comment by matteosantama** [comment]
`My` is a `np.matrix`, if you do `pl.Series(np.array(My))` it works (although you will probably want to reshape too). I see no reason to support construction via `np.matrix`, since the [docs](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html) basically say "don't use this".

**Comment by momentlost** [comment]
The same does not work for below as well:

# Generate data
data_matrix = np.vstack((y, Dj, post, Dj*post, My, Mconst, Mint)).T
did_data = pl.DataFrame(data_matrix,
                        columns = ["y", "Dj", "post", "int", "My", "Mconst", "Mint"])

But if the package buiders' intention was NOT to make this work (i.e., it should not be possible to convert from numpy matrix to polars DataFrame), I would understand and this might be moved to "features suggestion". But I am still disturbed that this causes a kernel panic.

**Comment by matteosantama** [comment]
I'm not sure I understand, passing a `np.matrix` to both `Series` and `DataFrame` constructors fails. Are you suggesting that they should both work?

```python
>>> pl.Series(np.matrix("1, 2"))
RecursionError: maximum recursion depth exceeded in comparison

>>> pl.DataFrame(np.matrix("1, 2"))
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by momentlost** [comment]
When things are converted into ndarray, it works fine. Didn't know that numpy matrix would be soon deprecated. 

Your first line still gives me a kernel panic by the way. Not sure what's the problem but see below:
![image](https://user-images.githubusercontent.com/42916642/193462854-215b793c-bf6a-4d59-add8-5145a2ffe0ac.png)

**Comment by matteosantama** [comment]
This looks like a problem with `IPython` https://github.com/ipython/ipython/issues/12197

**Comment by matteosantama** [comment]
Can you try my example with regular `$ python` instead of `$ ipython`?

**Comment by momentlost** [comment]
You're right -- it gives only the recursion error in python.

**Comment by matteosantama** [comment]
Great! Than may we consider this resolved from the `polars` perspective?

**Comment by momentlost** [comment]
Yup. I'll close the issue from here. Thank you.
