### ISSUE TITLE
`pl.concat(how='diagonal')` doesn't work with `LazyFrame`s

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#5082]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Concatenation of LazyFrames with different column width raises a `ShapeError`, even when `how='diagonal'` is set.

### Reproducible example

```python
import tempfile
import polars as pl

with tempfile.NamedTemporaryFile() as a:
    with tempfile.NamedTemporaryFile() as b:
        pl.DataFrame({"A": [1]}).write_csv(a.name),
        pl.DataFrame({"A": [1], "B": [1]}).write_csv(b.name)

        df = pl.concat([pl.scan_csv(x) for x in [a.name, b.name]], how='diagonal')
        df = df.collect()
```
```
ShapeError: Could not vertically stack DataFrame. The DataFrames appended width 1 differs from the parent DataFrames width 2
```

### Expected behavior

The concatenation should find a union between the column schemas and fills missing column values with null.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.17
Index type: UInt32
Platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>

```

</details>

**Comment by DrMaphuse** [comment]
Thanks @mcrumiller, you are correct. I somehow thought that it only fails when creating a lazyframe straight from a file, but it seems to fail with your example as well.

**Comment by gr-alecz** [comment]
closely related:

```
df1 = pl.DataFrame(
    {
        "foo": [1, 2],
        "bar": [6, 7],
        "ham": ["a", "b"],
    }
)
df2 = pl.DataFrame(
    {
        "foo": [3, 4],
        "ham": ["c", "d"],
        "bar": [8, 9],
        
    }
)

pl.concat([df1, df2], how="diagonal") # works
pl.concat([df1.lazy(), df2.lazy()], how="diagonal").collect() # SchemaError: cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='bar' with left.dtype=i64 != right.dtype=str with right.name='ham'
```

**Comment by mcrumiller** [comment]
Yeah, it almost looks like `pl.concat(..., how="diagonal")` for lazy frames runs the `how="vertical"` code.

**Comment by ritchie46** [comment]
That's correct. Lazy only supports vertical concat. We must throw an error on the other arguments and add this int he docs.
