### ISSUE TITLE
Method to drill down through JSON hierachy to table data

### ISSUE THREAD

**Issue by daviewales** [pola-rs/polars#5091]
### Problem description

Suppose I have some JSON in a file that looks like this:

``` json
{
    "messages": {
        "data": [
            {
                "col1": "A",
                "col2": "B"
            },
            {
                "col1": "C",
                "col2": "D"
            }
        ]
    }
}
```

I'd like to be able to tell Polars to [read_json](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_json.html#polars.read_json), but also indicate that the table data I'm looking for is a few levels down, as a list of dicts in `messages.data`.

My current workaround is:

``` python
import json
import polars as pl

with open(json_file) as file:
    json_data = json.load(file)
return pl.from_dicts(json_data["messages"]["data"], infer_schema_length=None)
```

However, this loads the whole JSON file in Python before passing it to Polars, rather than allowing Polars to read it directly.

**Comment by daviewales** [comment]
I think I'm looking for something similar to [pandas.json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html), which has a `record_path` argument to specify the JSON path to the list of dicts.

**Comment by evbo** [comment]
Can/should this be closed now? There's `unnest` and `json_extract` helpers now. See for examples:
https://github.com/pola-rs/polars/issues/7078#issuecomment-1441905809
https://github.com/pola-rs/polars/issues/7222

**Comment by ritchie46** [comment]
Yes, thanks for the reminder.
