### ISSUE TITLE
Rank Expression

### ISSUE THREAD

**Issue by McNickSisto** [pola-rs/polars#5108]
### Problem description

Hello! I was wondering if you could potentially add a rank() expression so that we can use it with the groupby. Basically, I would like to groupby a unique ID and rank on dates.

**Comment by ritchie46** [comment]
We have a rank expression? Have you searched the docs?

**Comment by McNickSisto** [comment]
Apologies, I did something wrong ! Definitely a rank expression https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.rank.html
