### ISSUE TITLE
Cannot install source version in aarch64

### ISSUE THREAD

**Issue by david-cortes** [pola-rs/polars#5114]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When trying to build the latest source version of polars (0.14.18) from pip in an aarch64 machine (macOS), I get some errors about missing simd functions. I unfortunately cannot paste the error log here, but some of the errors read like this:
```
error[E0432]: unresolved import `std::simd::SimdPartialEq`
```

There's also more complaints about e.g. `SimdFloat`, `SimdInt`, etc.

### Reproducible example

```python
pip install https://files.pythonhosted.org/packages/92/c5/b85939e098a5bb76be036cdea316ed1050a4a66973baaa31b0a4b4ce9578/polars-0.14.18.tar.gz
```

### Expected behavior

Should install.

### Installed versions

None

**Comment by ritchie46** [comment]
You don't have the right rust compiler. Why do you want to build from source?

**Comment by david-cortes** [comment]
Thanks for the info. I was trying to work in an environment with limited connectivity. Does building it from source in aarch64 require some specific version of rust? At least in amd64-linux, it works with the default rust packages from the main distro repositories.

**Comment by ritchie46** [comment]
You need the nightly compiler version we use: https://github.com/pola-rs/polars/blob/master/rust-toolchain.toml
