### ISSUE TITLE
DataFrame.pivot documentation issue (maybe not a bug)

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#5116]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As in the example below, I am using `DataFrame.pivot()` with the following argument types:
```
values: list[str]  
index: str  
columns: str
```
It is currently working the way I want it to. However, the documentation seems to suggest that `values` may only be a list if `columns` is also a list.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "x1": [1, 2, 3, 4, 5, 6, 7, 8],
    "x2": [8, 7, 6, 5, 4, 3, 2, 1],
    "c1": ["A", "B"] * 4,
    "c2": ["C", "C", "D", "D"] * 2,
})
df.pivot(values=["x1", "x2"], index="c1", columns="c2")

shape: (2, 5)
┌─────┬─────┬─────┬─────┬─────┐
│ c1  ┆ C   ┆ D   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╡
│ A   ┆ 1   ┆ 3   ┆ 8   ┆ 6   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ B   ┆ 2   ┆ 4   ┆ 7   ┆ 5   │
└─────┴─────┴─────┴─────┴─────┘
```

### Expected behavior

Either raise an error if I am passing invalid arguments, or indicate in the documentation that my arguments are valid.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.14
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.0
numpy: 1.22.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
```

</details>

**Comment by s-banach** [comment]
I mean that it gives the values I expect, but on the other hand it results in duplicate column names.

**Comment by YuRiTan** [comment]
In '0.14.18' all argument types are `'list[str] | str'` for `values`, `index` and `columns` for the`DataFrame.pivot()` method. So according to these docstrings, your input is valid.

The output however makes a certain assumption. If the index contains duplicates, it seems to choose the first match. Looking at your input df for example:

```
┌─────┬─────┬─────┬─────┐
│ x1  ┆ x2  ┆ c1  ┆ c2  │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 8   ┆ A   ┆ C   │  <---
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 7   ┆ B   ┆ C   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 6   ┆ A   ┆ D   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 4   ┆ 5   ┆ B   ┆ D   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 4   ┆ A   ┆ C   │  <---
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 3   ┆ B   ┆ C   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 7   ┆ 2   ┆ A   ┆ D   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 8   ┆ 1   ┆ B   ┆ D   │
└─────┴─────┴─────┴─────┘
```
The combination `A` and `C` has values `1` and `8` for `x1` and `x2` respectively, but also values `5` and `4`. The output only shows the first one. If this is intended behavior, an extra note in the doc string might be nice.

**Comment by s-banach** [comment]
It shows the first value, because the default value of `aggregate_fn` is `"first"`.

Actually, I believe that `aggregate_fn` should not have a default value.
In the past, I've had a sneaky bug in some pandas code due to the default value here:
I assumed the default aggregate function would be `"sum"`, but in pandas it is `"mean"`.

**Comment by zundertj** [comment]
The docstring could be improved here, as it certainly suggests that the example in the OP should error.

I think having `first` as the default makes sense if you know that your index-column combinations are unique (which is how I would usually use pivot, not to do actual aggregations) but it can mask subtle bugs as well. What aggregate function would work, would you basically want a function that errors on there being more than one value? Because that is currently not available in the string values, so there is not an easy way to opt-in into that behaviour. You can still create an expression to error, but that seems far from user friendly.

`aggregate_fn` can be both a string and an expression. The string is not very polars to start with imo. Maybe something we should consider as well. Not sure what the performance implications would be if we would have:
1. pivot does not take an aggregate function, and will either set value to the single value available, or null. If multiple values, error
2. if users want the aggregation, have them do a `groupby().agg()` first, and then do the pivot.

**Comment by s-banach** [comment]
I think if aggregation and pivoting were separate, it would teach users like me to write better code.
Sometimes I try to do stupid things with dataframes because I learned everything I know through trial-and-error with pandas, and pandas lets users do too many stupid things.

**Comment by YuRiTan** [comment]
There might be a bug in the pivot. In the example from the OP, the pivot generates a `DataFrame` with duplicate column names. This is something that should not be possible in Polars; normally you get an error when trying to create a column with an existing name. (You can select column `C` without an error, it will just always return the first match)

I would personally not mind having an aggregate function in the pivot. It's something that I think people often use, and a separate `groupby().agg()` would add some boiler plate. Maybe not setting a default `aggregate_fn`, and raising an exception when multiple values occur, with the message that you might want to set an `aggregate_fn`, is also an option? This way no automagic aggregations are done, and the end-user needs to set it explicitly.

And defining the `aggregate_fn` only using Polars Expressions would be nice indeed.
