### ISSUE TITLE
add postgresql style encode/decode functions

### ISSUE THREAD

**Issue by ozgrakkurt** [pola-rs/polars#5119]
### Problem description

for transforming binary data to string and string to binary. It would be very useful in cli to see binary columns and maybe useful when doing something like sql queries because it would provide `decode(<hex string>)` for queries.

**Comment by universalmind303** [comment]
There are the `str.encode` and `str.decode` operations that support `hex` and `base64` encoding.

**Comment by ritchie46** [comment]
I will close this as we have the functionality.

**Comment by ozgrakkurt** [comment]
I can't find it anywhere. Can you point to where it is on rust docs? @ritchie46 @universalmind303

**Comment by ozgrakkurt** [comment]
> I will close this as we have the functionality.

Even if they are implemented on string, they should be implemented on expr so they can both work on string and binary. Can you re-open the issue this way maybe? I'll work on this tomorrow I think

**Comment by ritchie46** [comment]
> > I will close this as we have the functionality.
> 
> Even if they are implemented on string, they should be implemented on expr so they can both work on string and binary. Can you re-open the issue this way maybe? I'll work on this tomorrow I think

We have a str namespace. We should add a bin namespace for this one.
