### ISSUE TITLE
Multiprocessing.Process freezes upon `pl.scan_parquet`

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#5133]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Below I have a repro that generates parquet files and prints them out. When printing the contents of the parquet file in the current process it works fine, but in the subprocess it seems to be frozen for me:

### Reproducible example

```python
import polars as pl
from multiprocess import Process


def print_scanned_parquet(path):
    print("Scanning...")
    print(f"Path: {path}, df: {pl.scan_parquet(path).collect()}")


parquet_path = "/tmp/test_string_cache.parq"
df = pl.DataFrame({"a": ["foo", "bar"], "b": ["x", "y"]}).select(
    [pl.col("a").cast(pl.Categorical).alias("a"), pl.col("b").cast(pl.Categorical).alias("b")]
)
df.write_parquet(parquet_path)
print_scanned_parquet(parquet_path)
p = Process(target=print_scanned_parquet, args=(parquet_path,))
p.start()
p.join()
```

### Expected behavior

Expected the output for the `Process` to be the same. Got this instead:

```
Scanning...
Path: /tmp/test_string_cache.parq, df: shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ cat ┆ cat │
╞═════╪═════╡
│ foo ┆ x   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ bar ┆ y   │
└─────┴─────┘
Scanning...
<stuck here>
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.18
Index type: UInt32
Platform: Linux-5.4.117
Python: 3.8.7 (default, Dec 22 2020, 16:05:35) 
[GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.1.5
numpy: 1.18.5
fsspec: 0.8.5
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.3.4+1.g5571742a4
```

</details>

**Comment by zundertj** [comment]
I think this is the same as #3144, so please add your feedback to that thread. If not, please comment here.
