### ISSUE TITLE
Add df.update()

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5134]
### Problem description

Pandas has a [`df.update(a)`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.update.html) which modifies a dataframe, filling NA values with the values found in `a`. Obviously, pandas works by index, so a polars implementation would require an argument specifying the "index" columns (i.e. the columns used for alignment).

This is basically a `join` followed by a `when/then` expression. Right now, it can be implemented with some column renaming:

```python
import polars as pl
from polars import col, when

df = pl.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['a', 'b', None, 'c', 'd']
})
updater = pl.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['s', 's', 'x', 's', 's']
})

print(
    df.lazy()
    .join(updater.lazy().rename({'b': "b_"}), on='a')
    .with_column(
        when(col('b').is_null()).then(col("b_"))
        .otherwise(col('b'))
        .alias('b')
    )
    .drop("b_")
    .collect()
)
```
```
shape: (5, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ b   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ x   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 4   ┆ c   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ d   │
└─────┴─────┘
```

**Comment by mcrumiller** [comment]
In the meanwhile, here's a function to do just that:

import polars as pl
from polars import col, when

```python
def update(df, updater, idx_cols):
    other_cols = list(set(updater.columns).difference(idx_cols))
    other_cols_ = [f"{col}_" for col in other_cols]
    renaming = dict(zip(other_cols, other_cols_))

    # build expressions
    exprs = [
        when(col(x).is_null()).then(col(y))
        .otherwise(col(x))
        .alias(x)
        for (x, y) in zip(other_cols, other_cols_)
    ]

    return (
        df.lazy()
        .join(updater.lazy().rename(renaming), on=idx_cols, how="left")
        .with_columns(exprs)
        .drop(list(renaming.values()))
        .collect()
    )

df = pl.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['a', 'b', None, 'd', 'e'],
    'c': [None, '2', '3', '4', '5'],
})
updater = pl.DataFrame({
    'a': [1, 2, 3],
    'b': ['a', 'b', 'c'],
    'c': ['1', '2', '3']
})

print(update(df, updater, idx_cols=['a']))
```
```
shape: (5, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ str │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ b   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ c   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 4   ┆ d   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ e   ┆ 5   │
└─────┴─────┴─────┘
```

**Comment by zundertj** [comment]
You can avoid the when-then by using `fill_null`, and the renaming by use the auto generated suffix:
```python
df.lazy().join(updater.lazy(), on="a", how="left").with_column(pl.col("b").fill_null(pl.col("b_right"))).drop("b_right").collect()
```
Not sure this is worth a separate function. Do you want it in polars becausse you end up using it a lot (i.e. convenience to you and presumably other users), because you think there is room for a faster implementation versus your own utility function, or because Pandas does it and therefore polars should add it? Note that mimicking the pandas api is not a goal of the polars project.

**Comment by mcrumiller** [comment]
@zundertj thanks for the suggested improvements. I do use this quite often, but upon considering, yes I was thinking "pandas does it therefore polars should add it."

I'll remove it as it's a pretty low priority and there are more than enough outstanding issues.

/close
