### ISSUE TITLE
Add `is_sorted`

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5138]
### Problem description

We can tell Polars that a column is sorted with `set_sorted`.

It would be good if we can check on the current status with an `is_sorted` method for a Series/DataFrame. This example is trivial but would be handy for checking whether a more complicated operation has changed `set_sorted` or not.

```py
df = pl.DataFrame({'id':[0,1],'values':[3,2]})
df = df.set_sorted("id")
df.is_sorted()
{'id':True,'values':False}
```

**Comment by ritchie46** [comment]
We already have that. A `Series` has a `flags` attribute.
