### ISSUE TITLE
Node Webpack "Module not found" error

### ISSUE THREAD

**Issue by caerbannogwhite** [pola-rs/polars#5148]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

The compilation with npm produces the following log
[log.txt](https://github.com/pola-rs/polars/files/9741949/log.txt)

Errors
```
WARNING in ./node_modules/nodejs-polars/bin/native-polars.js 226:40-84
Module not found: Error: Can't resolve 'nodejs-polars-linux-arm-gnueabihf' in 'C:\Users\massi\source\repos\prqlvs\node_modules\nodejs-polars\bin'
 @ ./node_modules/nodejs-polars/bin/cfg.js 7:40-66
 @ ./node_modules/nodejs-polars/bin/index.js 29:25-41
 @ ./src/prql2sas/env.js 1:0-50
```

### Reproducible example

```javascript
Install polars with `npm i -s nodejs-polars` in a project with webpack and run it
```

### Expected behavior

The compilation runs smoothly

**Comment by universalmind303** [comment]
can you reopen this in the [nodejs-polars](https://github.com/pola-rs/nodejs-polars/issues) repo

**Comment by caerbannogwhite** [comment]
https://github.com/pola-rs/nodejs-polars/issues/13
