### ISSUE TITLE
Sort by column names

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5154]
### Problem description

After calling .suffix you have columns with the same root column at different points in the dataframe. It would be nice to be able to sort these into alphabetical order.

This could be either:
```python
import polars as pl
df = pl.DataFrame({"A":[0,1],"B":[2,3]})
df.with_columns(pl.all().min().suffix("_min")).sort_columns()
```

**Comment by ritchie46** [comment]
IMO this is something that should be done in the host language.

```python
df = pl.DataFrame({"A":[0,1],"B":[2,3]})
df.with_columns(pl.all().min().suffix("_min")).pipe(lambda df: df.select(sorted(df.columns)))
```

**Comment by braaannigan** [comment]
> ```python
> df = pl.DataFrame({"A":[0,1],"B":[2,3]})
> df.with_columns(pl.all().min().suffix("_min")).pipe(lambda df: df.select(sorted(df.columns)))
> ```

Nice, I'll add a docstring example around this

**Comment by ritchie46** [comment]
Cool. Will close this now.
