### ISSUE TITLE
fill_null should not affect/depend on columns without nulls

### ISSUE THREAD

**Issue by datenzauberai** [pola-rs/polars#5158]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When calling `fill_null(0)` on a data frame it will cast date columns to integer and crash when categorical columns are present, even when these columns do not contain null values.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "string/cat": ["a", "b"],
    "int": [0, 2],
    "float": [1.4, None],
    "time": [date(2000, 1, 1), date(2000, 2, 1)]
})

# converts time column from date to i64
df.fill_null(0)

# crashes when string/cat column is a categorical
df.with_column(pl.col("string/cat").cast(pl.Categorical)).fill_null(0)

# works fine without crashes or conversions
df.with_column(pl.col("string").cast(pl.Categorical)).fill_null(strategy="zero")
```

### Expected behavior

`fill_null(0)` should only affect columns with null values (and maybe matching data types as well). It should not silently convert date columns or crash when categorical columns are present.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.10
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
pytz: 2022.2.1
```

</details>

**Comment by ghuls** [comment]
You are not using the latest version of Polars (0.14.18 atm) as this was fixed in 0.14.16: https://github.com/pola-rs/polars/commit/ea149104b67b2f7bfc46c119abe317f59b32c61f

**Comment by datenzauberai** [comment]
Oh my, I installed the latest one but did not restart the kernel...

**Comment by datenzauberai** [comment]
Oh my, I installed the latest one but did not restart the kernel...
