### ISSUE TITLE
Missing expression: get timezone

### ISSUE THREAD

**Issue by Kuhlwein** [pola-rs/polars#5168]
### Problem description

Hello!

Looks like polars is missing an expression for getting the timezone of a column. I'd like to be able to do something like this:

`col("A").dt.cast_time_zone(col("B").dt.tz())`, with dt.tz() returning the timezone of the column.

Also, it is kinda weird that cast_time_zone only accepts a string and not an actual datetime.tzinfo object. Ideally, dt.tz() would return a tzinfo object, and cast_time_zone would then accept that.

**Comment by alexander-beedie** [comment]
The timezone is a column-level attribute (not a  per-value attribute), so you can retrieve the `tu` from the schema like this: `df.schema["datetimecol"].tz`.

**Comment by Kuhlwein** [comment]
Well, that works I guess.

I don't see why we can't have it as an expression though? Many other expressions are abstractly column-level, such as sum, std and max.
I think one of the great things about polars is the expression system. If I want to create a function to normalize a column/expression i could create a function like

```
def normalize(col):
    return col/col.sum()
```

and reuse that over and over.
Now let's say that I want to truncate a datetime in some particular time zone, then convert it back to its original time zone. I think this would be great:

```
def truncate_tz(col, tz):
    return (col.dt.cast_time_zone(tz)
        .dt.truncate("1h")
        .dt.cast_time_zone(col.dt.tz))
```

With your solution I'd have to do something like:
```
def truncate_tz(col, df, tz):
    return (col.dt.cast_time_zone(tz)
        .dt.truncate("1h")
        .dt.cast_time_zone(df.schema[col.meta.output_name()].tz))
```

In this case I need to access the dataframe/schema, which feels dirty to me, although I might just be picky.
This also prevents chaining of function calls, I won't be able to do something like
```

a.with_column(pl.col("datetime").alias("later") + timedelta(hours=1)).select(truncate_tz(pl.col("later"), a, "US/Central"))

```

since "a" does not contain the newly defined column "later" in its schema. My proposal would also make this possible.

The way I see it, the current way to do it basically corresponds to doing the normalize example like this:

```
def normalize(df, col):
    return col/df[col.meta.output_name()].sum()
```
which is obviously wrong.

**Comment by alexander-beedie** [comment]
Perhaps as `meta` facilities expand that might be a reasonable home for it? (Expressions don't give you access to any other dtype attributes at the moment either, so `tz` isn't an outlier here ;) But at the moment I think you're likely limited to retrieving from the schema if you want to be able to do it now.

**Comment by Kuhlwein** [comment]
From a user-perspective I think it makes the most sense to put it in the `dt` namespace for sure. It would only work on datetime columns after all.
Unless you're talking about a generalized expression for accessing dtype attributes? That'd make sense to put in meta, yeah. But even then, I'd love a separate dt.tz expression.

**Comment by ritchie46** [comment]
> I think it makes the most sense to put it in the `dt` namespace for sure

It does not. Expression operate on data, not on datatypes. The only place where this fits is in the schema or in the `meta` namespace.

**Comment by ritchie46** [comment]
I will close this as timezones are part of dtypes not expressions.
