### ISSUE TITLE
Implement `is_numeric` and other Series-only type checking functions for expressions and/or dataframes

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#5187]
### Problem description

Currently, `is_numeric` only works on Series, with means it is cannot be used in expressions or in lazy computations. It would be neat to have this functionality more broadly available.

**Comment by ritchie46** [comment]
Could you elaborate a bit on how you think this should look/work?

**Comment by mcrumiller** [comment]
This relates to #4982, which is still open--`is_numeric` could simply a check for whether the current dtype is float or int. But I could also see this being useful for object arrays perhaps, where the type of each element is unknown.

**Comment by mcrumiller** [comment]
I see what you're saying. I can only think of a use case for this issue on `pl.Object` columns.

**Comment by ritchie46** [comment]
> I see what you're saying. I can only think of a use case for this issue on `pl.Object` columns.

This would also not work as an object is opaque to polars. It means anything that we don't understand, so we would also not know if it is numeric/ what would that mean?

**Comment by mcrumiller** [comment]
well, `apply` doesn't work on `pl.Object` columns:

```python
pl.Series([1, 2, 'a', 4, 5], dtype=pl.Object).apply(lambda x: x)
```
```
thread '<unnamed>' panicked at 'dtype Object("object") not supported', src\series.rs:971:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\series\series.py", line 3315, in apply
    return wrap_s(self._s.apply_lambda(func, pl_return_dtype, skip_nulls))
pyo3_runtime.PanicException: dtype Object("object") not supported
```
Anyway, we'll have to wait for OP to chime in. I don't see much of a use case for `is_numeric`.

**Comment by ritchie46** [comment]
> well, `apply` doesn't work on `pl.Object` columns:
> 
> ```python
> pl.Series([1, 2, 'a', 4, 5], dtype=pl.Object).apply(lambda x: x)
> ```
> 
> ```
> thread '<unnamed>' panicked at 'dtype Object("object") not supported', src\series.rs:971:28
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\series\series.py", line 3315, in apply
>     return wrap_s(self._s.apply_lambda(func, pl_return_dtype, skip_nulls))
> pyo3_runtime.PanicException: dtype Object("object") not supported
> ```
> 
> Anyway, we'll have to wait for OP to chime in. I don't see much of a use case for `is_numeric`.

Ai.. that doesn't seem right.

**Comment by mcrumiller** [comment]
I've opened #5196

**Comment by alexander-beedie** [comment]
Closing, as fixing https://github.com/pola-rs/polars/issues/5196 should enable the suggested solution on object dtype cols.
