### ISSUE TITLE
Docstring for LazyGroupBy.apply is for the wrong .apply function

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5188]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The docstring for LazyGroupBy.apply actually shows an example for the .apply **expression**

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.lazyframe.groupby.LazyGroupBy.apply.html#polars.internals.lazyframe.groupby.LazyGroupBy.apply

### Reproducible example

```python
N/A
```

### Expected behavior

Can probably replace with a lazy version of this:

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.dataframe.groupby.GroupBy.apply.html

### Installed versions

N/A

**Comment by ritchie46** [comment]
Can you take this one?

**Comment by braaannigan** [comment]
> Can you take this one?

Yes
