### ISSUE TITLE
Polars panics if unexpected wildcard in exprs

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#5199]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Some invalid queries panic instead of returning an error.

> thread '<unnamed>' panicked at 'should be no wildcard at this point'

### Reproducible example

```rust
use polars::prelude::IntoLazy;
use polars::prelude::*;

fn main() {
    let df = df! {
        "id" =>  [1,2],
        "a" =>  ["foo", "bar"],
    }
    .unwrap()
    .lazy();

    df.groupby([col("*")]).agg([col("*").list()]);
}

```

### Expected behavior

Should return an error instead of panicking 

### Installed versions

<details>
polars = { version = "0.24.3", features = ["lazy"] }
</details>

**Comment by ritchie46** [comment]
We should expand the wildcard in the groupby clause, similar to what we do in select.

**Comment by universalmind303** [comment]
ahh, so it is functionality that is not yet implemented?

**Comment by ritchie46** [comment]
Yeap.. never occurred to me that people would write wildcards there.

**Comment by andrewpollack** [comment]
It'll take me a bit to get acquainted with the project, but I'd be interested in taking a crack at wildcard expansion in the groupby clause @ritchie46

**Comment by ritchie46** [comment]
> It'll take me a bit to get acquainted with the project, but I'd be interested in taking a crack at wildcard expansion in the groupby clause @ritchie46

Thanks for your interest. However this is not the best feature to start as it is an too easy fix.

**Comment by andrewpollack** [comment]
No problem @ritchie46 , I'll keep my eyes out for other rust bugs to jump on 😊
