### ISSUE TITLE
Printing the shape below the DataFrame is more usable than printing on top

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#5202]
### Problem description

Quite a silly suggestion but I think printing the shape below the DataFrame could be a slight improvement when using pl.DataFrame. Obviously, we could also simply use df.shape but my point is this: if the shape is being printed at all, why not at the bottom? Quite annoying to keep scrolling up to check the shape from time to time. 

By the way, polars is awesome. Keep it up!

Instead of this:

```
df

shape: (4420, 2)
┌─────────────────┬───────┐
│ id              ┆ open  │
│ ---             ┆ ---   │
│ str             ┆ f64   │
╞═════════════════╪═══════╡
│ 2007-04-27_STAR ┆ 48.75 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-01_FOXA ┆ 44.8  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-14_CTIC ┆ 5.44  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-15_FONR ┆ 4.5   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
```

Do this:

```
df
┌─────────────────┬───────┐
│ id              ┆ open  │
│ ---             ┆ ---   │
│ str             ┆ f64   │
╞═════════════════╪═══════╡
│ 2007-04-27_STAR ┆ 48.75 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-01_FOXA ┆ 44.8  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-14_CTIC ┆ 5.44  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-15_FONR ┆ 4.5   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤

shape: (4420, 2)
```

**Comment by mcrumiller** [comment]
This is not silly; I fully agree with this change.

**Comment by alexander-beedie** [comment]
You'd need a compelling reason to change default behaviour, and given that all of the other meta information displayed (column names, column types) is at the top, I don't see one here (the mention about having to scroll up to check the shape could equally be made about the column names or types, but I don't think anybody would want them on the bottom).

However... a _lot_ of flexibility is available for customising table formatting to your personal taste is already available via `pl.Config` options (well worth checking this out if you haven't seen it, as you may also like some of the other non-default formatting). 

So, adding an extra option to support "shape below frame" output doesn't seem like a problem, and would let you set things up how it feels best to you - but changing the default for everybody seems a bit much  ;)

I'll take a look.

**Comment by arturdaraujo** [comment]
Appreciate that
