### ISSUE TITLE
jsonpath_lib::PathCompiled  invalid

### ISSUE THREAD

**Issue by liu-hanwen** [pola-rs/polars#5203]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When build rust project, compiler report a bug about use jsonpath_lib::PathCompiled. I have searched for crate 'jsonpath_lib', the module name seems to be changed to 'Compiled'. I changed the import code (polars-core-0.24.3\src\chunked_array\strings\json_path.rs) to jsonpath_lib::Compiled, it works. 

### Reproducible example

-

### Expected behavior

-

### Installed versions

<details>
registry: mirrors.ustc.edu.cn-b63e9dae659fc205
crate: polars-core-0.24.3
</details>

**Comment by ritchie46** [comment]
Can you make a PR?

**Comment by ritchie46** [comment]
I will close this as it seems stale.
