### ISSUE TITLE
There should be a way to identify to original source when using pl.scan_csv

### ISSUE THREAD

**Issue by IsmailM** [pola-rs/polars#5209]
### Problem description

When running `pl.scan_csv("files*.csv")`, it would be nice to know the source of the row in the output df (i.e. which file did this row come from) - even if it's just the index number.

**Comment by ritchie46** [comment]
There is. You can glob the files yourself, create a list of `LazyFrames` and concat the final list. That's what we do internally. So if you want to add some meta-info, you can add that explicitly.
