### ISSUE TITLE
Sum with AggregateFunction is done with different data type

### ISSUE THREAD

**Issue by cannero** [pola-rs/polars#5217]
With PR #5170 the data types were swapped in one part of `convert_to_hash_agg`:

![image](https://user-images.githubusercontent.com/11857491/195989556-9b803808-fe24-4e0c-8b4f-b3c1c47dd6d2.png)

Unsigned to signed and vice versa. To me that seems to be wrong or is there  are reason for it?

https://github.com/pola-rs/polars/blob/926b5a2939eaf3a6de60b9371310931a0724c208/polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/aggregates/convert.rs#L81

**Comment by ritchie46** [comment]
Yeap.. that's wrong. Can you make PR?

**Comment by cannero** [comment]
Yes, I will open a PR.
