### ISSUE TITLE
add set_columns(names)

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5218]
### Problem description

It would be very nice to be able to assign column names during a long stream of piped operations. An alternative is to stop the piping stream and do a `df.columns = ...` but that breaks up the code.

```python
df = (
    df.with_columns(....)
    .operation2()
    .operation3()
    .rename(dict(zip(df.columns, new_names))) # a bit messy, and tough if the operations have changed the column names
    .operation4()
    ...
)
```

A simple `set_columns(names)` would make things much more simple:

```python
df = (
    df.with_columns(....)
    .operation2()
    .operation3()
    .set_columns(new_names) # much nicer
    .operation4()
    ...
)
```

**Comment by mcrumiller** [comment]
Alternatively, `rename` could optionally take a list for direct assignment.

**Comment by ghuls** [comment]
You can assign proper names during the previous queries with adding `.alias("new_name")`

**Comment by mcrumiller** [comment]
Not if they're expressions generated by a different library that doesn't know what names I want.

**Comment by YuRiTan** [comment]
Overwriting the column names might introduce some errors, unless you're really certain of the columns you have and in which order.  For now, you could create a utility function like this:

```
from typing import List
import polars as pl

def set_columns(cols: List[str]) -> pl.DataFrame:
    def do_set_columns(df: pl.DataFrame):
        if len(cols) == len(df.columns):
            return df.rename(dict(zip(df.columns, cols)))
        else:
            raise ValueError(
                "Number of column names specified does not correspond "
                "with the number of columns in the DataFrame. Check "
                "your input, or use `.rename()` instead."
            )
    return do_set_columns

df = pl.DataFrame(
    {
        "id": [0, 1, 2, 3, 4],
        "color": ["red", "green", "green", "red", "red"],
        "shape": ["square", "triangle", "square", "triangle", "square"],
    }
)    
df.pipe(set_columns(["a", "b", "c"]))
```

**Comment by zundertj** [comment]
> Not if they're expressions generated by a different library that doesn't know what names I want.

How do you even know what the differences between the expressions are in that case? Because you want to assign them a name, so you know what they represent? I am struggling to see the use case here. 

The suggestion by YuRiTan is a nice workaround, but I would (again, without understanding the struggle in your use case) rethink the architecture and rely on `.alias()` instead. One concern is that, I'm not sure whether the proposed `set_columns` works in case you refer to the expressions both before and after the call to `.set_columns()` on a `LazyFrame`.

**Comment by mcrumiller** [comment]
My use case is in the event of a sequence of operations, as I described above. Perhaps I have some system of operations that I apply in succession, and at some point I want to set all of the columns to a pre-specified set of names. Currently, I'd have to do a `.rename` with a dictionary--not awful, but providing a list would be nice and a little more obvious IMO.  But it's not hard for me to workaround.
