### ISSUE TITLE
Cannot access struct fields after calling expr.arr.to_struct

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5220]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a struct is created during an expression sequence, `struct.field(name)` fails.

### Reproducible example

```python
import polars as pl

pl.DataFrame({'a': [[1,2]]}).select(
    pl.col('a').arr.to_struct().struct.field("field_0") # fails
)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Projects\project-brr\venv_brr\lib\site-packages\polars\internals\dataframe\frame.py", line 5243, in select
    self.lazy()
  File "c:\Projects\project-brr\venv_brr\lib\site-packages\polars\internals\lazyframe\frame.py", line 906, in collect
    return pli.wrap_df(ldf.collect())
exceptions.NotFoundError: field_0
```

### Expected behavior

Result should return the same as the following:

```python
pl.DataFrame({'a': [[1,2]]}).select(
    pl.col('a').arr.to_struct()
).select(
    pl.col('a').struct.field("field_0")
)
```
```
shape: (1, 1)
┌─────────┐
│ field_0 │
│ ---     │
│ i64     │
╞═════════╡
│ 1       │
└─────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.18
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: 3.6.1
```

</details>

**Comment by ritchie46** [comment]
Hmm... This  is a tricky one. Polars needs to know the schema at all times. But here we cannot know the schema as wel determine the amount of fields at runtime, depending on the lists data.

**Comment by ritchie46** [comment]
>  I know that struct fields aren't in theory ordered

They are ordered. :)

> @ritchie46 could this be resolved by accessing the fields by index?

It could by the user, but not by us. We don't 'know' that the given `field_0` belongs to index 0, because we don't know the schema.

**Comment by mcrumiller** [comment]
Should I close this as not planned? I'm not sure if that's a bug or something unimplementable--so perhaps an improved error message?

**Comment by voberoi** [comment]
I filed #5711, which looks related.

In my particular use case l will know how many elements the list has/how many fields it will create.

Just wanted to share in case exposing an API to provide that info is palatable and solving it for this use case, but not the general case, is worthwhile.
