### ISSUE TITLE
Allow expressions for date_range parameters

### ISSUE THREAD

**Issue by datenzauberai** [pola-rs/polars#5231]
### Problem description

Currently `date_range` does not accept expressions. This means that we always have to use `apply` when calculating various date ranges for different rows/groups.

We could speed up typical data wrangling operations like filling missing dates with this enhancement. Example:

```{python}
def complete_missing_months(df, by, time_column, every):
    return (df
        .groupby(by)
        .agg(
            pl.struct([pl.col(time_column).min().alias("_start"), pl.col(time_column).max().alias("_end")])
            .apply(lambda row: pl.date_range(row["_start"], row["_end"], interval=every)).alias(time_column)
        )
        .explode("date")
        .join(df, how="left", on=by + [time_column])
    )
```

**Comment by datenzauberai** [comment]
#5159

**Comment by ritchie46** [comment]
I have setup a PR for that in #5267.

Now I am stuck on the @overload types, so any help with that would be great.
