### ISSUE TITLE
[BUG] polars==0.14.20 cannot be imported

### ISSUE THREAD

**Issue by AlexanderVanEck** [pola-rs/polars#5244]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi, The latest version (0.14.20) cannot be imported and is broken. It's probably a missed import statement?

### Reproducible example

```python
$ pip install -U 'polars[pyarrow]==0.14.20'
$ python -c "import polars"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aicompute/env/lib/python3.8/site-packages/polars/__init__.py", line 13, in <module>
    from polars import testing
  File "/home/aicompute/env/lib/python3.8/site-packages/polars/testing.py", line 38, in <module>
    import polars.internals as pli
  File "/home/aicompute/env/lib/python3.8/site-packages/polars/internals/__init__.py", line 14, in <module>
    from polars.internals.batched import BatchedCsvReader
  File "/home/aicompute/env/lib/python3.8/site-packages/polars/internals/batched.py", line 9, in <module>
    from polars.utils import (
  File "/home/aicompute/env/lib/python3.8/site-packages/polars/utils.py", line 200, in <module>
    UTC = zoneinfo.ZoneInfo("UTC")
NameError: name 'zoneinfo' is not defined
```

### Expected behavior

```
$ pip install -U 'polars[pyarrow]<0.14.20'
$ python -c "import polars" # no output
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.19
Index type: UInt32
Platform: Linux-5.15.0-1021-aws-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
---Optional dependencies---
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-u_36bu8o because the default path (/home/aicompute/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
pyarrow: 7.0.0
pandas: 1.5.0
numpy: 1.23.4
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by dhirschfeld** [comment]
Looks like the use of `zoneinfo` isn't guarded by checking `_ZONEINFO_AVAILABLE` 

https://github.com/pola-rs/polars/blob/95c8a77db81535e85a7854c985655f64f4011dd4/py-polars/polars/utils.py#L200

`backports.zoneinfo` should probably just be made a required dep for `py<39`:
https://github.com/pola-rs/polars/blob/95c8a77db81535e85a7854c985655f64f4011dd4/py-polars/pyproject.toml#L7-L9

...and then you could remove some complex branching code that will only result in a delayed `ImportError` in any case:
https://github.com/pola-rs/polars/blob/95c8a77db81535e85a7854c985655f64f4011dd4/py-polars/polars/utils.py#L29-L39
