### ISSUE TITLE
New string chars count api for string expr

### ISSUE THREAD

**Issue by fangyinc** [pola-rs/polars#5249]
## Description

I want to get the length of each field ( the chars count of each field), but ```str.lengths()```  return the number of bytes composing the string(rust use utf8 encoding string).  

**Example**

```python
import polars as pl
df = pl.DataFrame(
    {
        "data": ["a", "b", "中"],
    }
)
df.select(
    [
        pl.col('data').str.lengths()
    ]
)

```
The output is:
```bash
shape: (3, 1)
┌─────┐
│ data│
│ --- │
│ u32 │
╞═════╡
│  1  │
├╌╌╌╌╌┤
│  1  │
├╌╌╌╌╌┤
│  3  │
└─────┘
```

In my view,  most people want it`s outpu is: 
```bash
shape: (3, 1)
┌─────┐
│ data│
│ --- │
│ u32 │
╞═════╡
│  1  │
├╌╌╌╌╌┤
│  1  │
├╌╌╌╌╌┤
│  1  │
└─────┘
```

## Temporary solution

Now, i implement it by ```str.split``` and ```arr.lengths```, but it it ugly.

```python
df.select(
    [
        pl.col('data').str.split(by="").arr.lengths().apply(lambda l: l - 2 if l >=2 else l)
    ]
)
```

## New api to return the chars count

It may be like this: ```str.chars_count()``` .

So , we could write:

```
df.select(
    [
        pl.col('data').str.chars_count()
    ]
)
```

**Comment by alexander-beedie** [comment]
Ahh, you are right; `str.lengths()` isn't returning the string length, it's returning the number of bytes, which isn't quite right for utf8...

Same thing with simple accented chars too:
```python
df = pl.DataFrame( {"str": ["café","中"]} )
df.select( pl.col("*").str.lengths() )

# ┌──────┐
# │ strs │
# │ ---  │
# │ u32  │
# ╞══════╡
# │ 5    │  # << should be 4
# ├╌╌╌╌╌╌┤
# │ 3    │  # << should be 1
# └──────┘
```
vs python:
```python
for s in ("café","中"):
    print( len(s) )
4
1
```
