### ISSUE TITLE
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/tljh/user/lib/python3.7/site-packages/typing_extensions.py)

### ISSUE THREAD

**Issue by bearberror** [pola-rs/polars#5250]
I found this error on import polars

ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/tljh/user/lib/python3.7/site-packages/typing_extensions.py)

I try to install typing_extension but It's not working

I also try to import ParamSpec directly but encounter the same error.

setting:
Python 3.7
typing_extension 4.4.0
Polars 0.14.21
On jupyterHub server

**Comment by ritchie46** [comment]
Did you restart your kernel after installing?

**Comment by bearberror** [comment]
> Did you restart your kernel after installing?

It works, Thank for your assistance
