### ISSUE TITLE
Unsound API in Dataframe::new

### ISSUE THREAD

**Issue by Plecra** [pola-rs/polars#5257]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

~~This user code~~ The code below creates a segfault.

This is because this transmute is invalid:

https://github.com/pola-rs/polars/blob/f8d60ee4e5130e3c4d662cdb14ae31488f268f68/polars/polars-core/src/frame/mod.rs#L242

For soundness, the `IntoSeries` trait must be sealed and/or unsafe to implement. Ideally we could use specialization for this :) but sadly that's still unstable.

### Reproducible example

```rs
fn main() {
    use polars::prelude::*;
    struct Evil(u64, u64, u64);
    impl polars::series::IntoSeries for Evil {
        fn into_series(self) -> Series where Self: Sized {
            polars::series::Series::new("", &[false])
        }
        fn is_series() -> bool {
            true
        }
    }
    let _ = DataFrame::new(vec![Evil(0, 0, 0)]);
}
```

### Expected behavior

A safe API needs to be sound :3

### Installed versions

<details>
I tested with the default latest version. Afaict this is applicable to all configurations.
</details>

**Comment by ritchie46** [comment]
Good observation. Thanks. I shall seal the trait.
