### ISSUE TITLE
Weird behavior of subtract two take expression

### ISSUE THREAD

**Issue by fecet** [pola-rs/polars#5269]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As I'm very new to polars, I still not quite sure if it's a bug. Anyway, when I was trying to migrate my expressions used in `select` to `groupby`, I found the following code does not work. While 
```
exp=pl.col("value").take(2)-pl.col("value").take(0)
```
or 
```
df.select(exp)
```
works well

### Reproducible example

```python
df=pl.DataFrame({"group": list("aaabbb"), "value": list(range(6))})
exp=pl.col("value").take(2)-pl.col("value").take(1)
df.groupby("group").agg(exp)
# df.select(exp)
```

### Expected behavior

Output as I expected

### Installed versions

---Version info---
Polars: 0.14.19
Index type: UInt32
Platform: Linux-6.0.1-arch1-1-x86_64-with-glibc2.36
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.0

**Comment by mcrumiller** [comment]
Performing a groupby without the `maintain_order` argument doesn't guarantee ordering of the resulting set, so calling `groupby(...).take(...)` is a bit nonsensical unless you also call `.sort()` over `b`. However...this still fails with `maintain_order=True`.
 
Ignoring maintain ordering and sorting, this only works when at least one side of your equal has `take(0)`:

```python
import polars as pl

df = pl.DataFrame({
    'a': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
    'b': [1, 2, 3, 4 ,5, 6, 7, 8, 9, 10],
})

for idx1 in range(5):
    for idx2 in range(5):
        print(f"({idx1}, {idx2}): ", end='')
        try:
            df.groupby('a').agg(pl.col('b').take(idx1) - pl.col('b').take(idx2))
            print("passed")
        except Exception:
            print("failed")
```
```
(0, 0): passed
(0, 1): passed
(0, 2): passed
(0, 3): passed
(0, 4): passed
(1, 0): passed
(1, 1): failed
(1, 2): failed
(1, 3): failed
(1, 4): failed
(2, 0): passed
(2, 1): failed
(2, 2): failed
(2, 3): failed
(2, 4): failed
(3, 0): passed
(3, 1): failed
(3, 2): failed
(3, 3): failed
(3, 4): failed
(4, 0): passed
(4, 1): failed
(4, 2): failed
(4, 3): failed
(4, 4): failed
```

When `maintain_order=True`, we get the same results.

When we use `.sort()` instead of maintain_order, all fail completely:
```python
...
        try:
            df.groupby('a').agg(pl.col('b').take(idx1) - pl.col('b').take(idx2))
            print("passed")
        except Exception:
            print("failed")
```
```
(0, 0): failed
(0, 1): failed
(0, 2): failed
(0, 3): failed
(0, 4): failed
(1, 0): failed
(1, 1): failed
(1, 2): failed
(1, 3): failed
(1, 4): failed
(2, 0): failed
(2, 1): failed
(2, 2): failed
(2, 3): failed
(2, 4): failed
(3, 0): failed
(3, 1): failed
(3, 2): failed
(3, 3): failed
(3, 4): failed
(4, 0): failed
(4, 1): failed
(4, 2): failed
(4, 3): failed
(4, 4): failed
```

**Comment by mcrumiller** [comment]
Hey, so I probably wasn't clear enough, but I think this should be reopened. There is still a problem here.

**Comment by ritchie46** [comment]
I want to take a look just in case. Because within groups the order should be maintained.

**Comment by mcrumiller** [comment]
@ritchie46 I don't think this is an ordering issue, I was just pointing that out so the OP realized they didn't have a guaranteed ordering. The issue here is that `col(x).take(a) - col(x).take(b)` only works when either a or b is 0, and fails otherwise.
