### ISSUE TITLE
strptime is unable to parse dates without leading zeros using valid format and panics with “attempt to subtract with overflow”

### ISSUE THREAD

**Issue by bernardo-sb** [pola-rs/polars#5279]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When parsing a string without leading zeros to date the program crashes or is unable to parse the data, resulting in `null`.
The dates are in month/day/year format, thus the correct formats are: `%m/%d/%Y`, `%-m/%-d/%Y`  and `%D`.

Dates without leading zeros: 1/1/2022, 10/5/2022, etc.

Issues in parsing dates without leading zeros:
- Using `%D` works fine
- Using `%m/%d/%Y`:  `1/1/2022` maps to `null`
- Using `%-m/%-d/%Y` does not work even though it is equivalent to `"%D"` :  `1/1/2022` program crashes unless `--release` is used, but even with that option `"10/10/2022"` maps to `null`

### Reproducible example

```rust
use polars::prelude::*;
use polars_lazy::prelude::*;
use polars_core::datatypes::DataType::Date;

fn main() {
    // "%D"  works
    let format = "%D"; // formats that do not work "-%m/%-d/%Y", "%m/%d/%Y"

    let df = df!("dates" => &["1/1/2022", "1/10/2022", "10/1/2022", "10/10/2022"]).unwrap();
    let df_parsed = df.lazy().with_column(
                                    col("dates").str().strptime(StrpTimeOptions{
                                                date_dtype: Date,
                                                fmt: Some(format.into()),
                                                strict: false,
                                                exact: false,
                                                }).suffix("parsed"))
                                                .collect()
                                                .unwrap();

    println!("{}", df_parsed);
    }
```

### Expected behavior

Using "%-m/%-d/%Y"
```
 panicked at 'attempt to subtract with overflow'
```

with `--release`
```
┌────────────┬─────────────┐
│ dates      ┆ datesparsed │
│ ---        ┆ ---         │
│ str        ┆ date        │
╞════════════╪═════════════╡
│ 1/1/2022   ┆ 2022-01-01  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1/10/2022  ┆ 2022-01-10  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/1/2022  ┆ 2022-10-01  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/10/2022 ┆ null        │
└────────────┴─────────────┘
(base) bernardo@MBP-de-Joana
```

Using `%D"

```
┌────────────┬─────────────┐
│ dates      ┆ datesparsed │
│ ---        ┆ ---         │
│ str        ┆ date        │
╞════════════╪═════════════╡
│ 1/1/2022   ┆ 2020-01-01  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1/10/2022  ┆ 2020-01-10  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/1/2022  ┆ 2020-10-01  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/10/2022 ┆ 2020-10-10  │
└────────────┴─────────────┘
```

Using `"%m/%d/%Y"`

```
┌────────────┬─────────────┐
│ dates      ┆ datesparsed │
│ ---        ┆ ---         │
│ str        ┆ date        │
╞════════════╪═════════════╡
│ 1/1/2022   ┆ null        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1/10/2022  ┆ null        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/1/2022  ┆ null        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10/10/2022 ┆ 2022-10-10  │
└────────────┴─────────────┘
```

### Installed versions

<details>
cargo 1.63.0
polars = "0.24.3"
polars-lazy = {version="0.24.3", features=["diff", "strings"]}
polars-core = {version="0.24.3", features=["ndarray", "strings"]}
</details>

**Comment by mcrumiller** [comment]
The [documentation for strptime](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.internals.expr.string.ExprStringNameSpace.strptime.html#polars.internals.expr.string.ExprStringNameSpace.strptime) states:

> ### fmt
> Format to use, refer to the [chrono strftime documentation](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) for specification. Example: "%y-%m-%d".

If you follow the link, you'll see the following definitions for `%m` and `%d`:
![image](https://user-images.githubusercontent.com/1896992/197041744-3b67e439-e467-410d-b55b-87a97dbcc3f2.png)
![image](https://user-images.githubusercontent.com/1896992/197041806-86ac64b7-b951-48f1-8d67-1bbf2ab4fb91.png)

In ohter words, leading zeros are required. If you need to get around this, you could use the `re` module to convert:

```python
import re

def conv_date(t):
    return re.sub(r"^(\d)/(\d)/(\d{4})$", r"0\1/0\2/\3", t)

print(conv_date("01/02/2022"))
print(conv_date("1/2/2022"))
```
```
01/02/2022
01/02/2022
```

**Comment by ritchie46** [comment]
This has already been fixed on master. You can point your repo to the master branch until a new release is issued. I will close as it is already fixed.
