### ISSUE TITLE
Methods for common arithmetic operations and comparisons.

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#5283]
### Problem description

This may be a matter of style, but I think the following methods would be could be implemented and offer slightly more readable code:

```
.add()
.sub()
.mul()
.div()
.mod()
.le()
.gt()
.eq()
```

This are the equivalent of +, -, *, /, <, >, =

Their usage would be as follows (to illustrate)
```
df.with_columns([
    pl.col('Units Sold').mul(pl.col('Price')).alias('Revenue'), 
    pl.col('Revenue').sub(pl.col('Cost')).div(pl.col('Revenue')).alias('Gross Margin'), 
    pl.col('Gross Margin').gt(0).alias('Is Profitable'), 
])
```

As I said, I think this is a matter of style, but I find the above more readable than:

```
df.with_columns([
    (pl.col('Units Sold') * pl.col('Price')).alias('Revenue'), 
    ((pl.col('Revenue') - pl.col('Cost')) / pl.col('Revenue')).alias('Gross Margin'), 
    (pl.col('Gross Margin') > 0 ).alias('Is Profitable'), 
])
```

Mainly because of the need for parenthesis in the second option.

**Comment by mkleinbort-ic** [comment]
What are you proposing? This?

```
df.with_columns([
    pl.col('Units Sold').__mul__(pl.col('Price')).alias('Revenue'), 
    pl.col('Revenue').__sub__(pl.col('Cost')).__div__(pl.col('Revenue')).alias('Gross Margin'), 
    pl.col('Gross Margin').__gt__(0).alias('Is Profitable'), 
])
```

**Comment by ritchie46** [comment]
Yes.

This has already been discussed earlier. See: https://github.com/pola-rs/polars/issues/4224

**Comment by mkleinbort-ic** [comment]
I see, thank you

**Comment by alexander-beedie** [comment]
> Mainly because of the need for parenthesis in the second option.

On the plus side, this actually makes expressions of this type immediately unambiguous in a way that chained method calls against a lazy-executing engine are not (visually)  ;)

**Comment by alexander-beedie** [comment]
> Any interest in supporting this?

@mkleinbort-ic : already supported - you just need to enable the feature (as it is/was considered experimental) and splat the dictionary with `**`, like so... ;)

```pl.Config.with_columns_kwargs = True
df.with_columns( **{
    'Revenue': pl.col('Units Sold') * pl.col('Price'),  
    'Gross Margin': (pl.col('Revenue') - pl.col('Cost')) / pl.col('Revenue'), 
    'Is Profitable': pl.col('Gross Margin') > 0, 
})
```
@ritchie46: shall we remove the requirement for the `with_columns_kwarg` opt-in now? We have a few "in the wild" requests for the feature, and it has proven quite popular here (at work). Time to go mainstream? :)

**Comment by mkleinbort-ic** [comment]
Love it ❤️; supper happy with the project.

**Comment by alexander-beedie** [comment]
> Also, FYI, I added the config change `with_columns_kwargs` to my `__init__.py` file; I'm not living without it (any reason not to use it?)

@mkleinbort-ic: FYI, as of >= polars `0.16.0` the kwargs-form is an [official part](https://github.com/pola-rs/polars/pull/6497) of the API, enabled by default, and no longer considered experimental. Once you update, you can freely remove your config change 👍

**Comment by mkleinbort-ic** [comment]
Thank you, I'm up to date with Polars - love the kwargs-form API
