### ISSUE TITLE
polar ingestion proxy

### ISSUE THREAD

**Issue by commandline-be** [pola-rs/polars#5285]
### Problem description

Forgive me is i misunderstand the typical intended use for Polars. Reading thru polars user guide i notice it has no listeners and typically reads from files and databases depending on query based information availability.

Looking at potential use case it seems desirable to have a distinct process which may serve to receive messages continuously such as json or syslog without passing the filesystem/disk overhead. The idea here is to use polars as part of a pre-processor before sending to SQL and/or Elastic data-stores and or files for the supported formats.

Thinking here of using log forwarding agents such as Elastic beats and also NXLog to collect data then process or pre-process it with polars to have optimized data at hand fast at near-real-time.

Thank you for your consideration,

Joris

**Comment by zundertj** [comment]
Hello, thank you for your suggestion. 

May I ask that you could be more specific? It seems as if Polars is just one part of the puzzle, and that Polars may or may not be the right tool for the job. For example, how would listeners work, and why should this be in Polars, rather than outside? What is wrong with a listener presenting data (as json, arrow, something else Polars is able to parse) do your thing in Polars, and return the parsed result?

**Comment by commandline-be** [comment]
Hey, thanks for the open approach. 

At this point i've kind of made up my mind Polars is the way to go due to the neat API which makes perfect sense to me reading thru. No code's been started with at this point.

Extending on my original request, this morning i realised what would make most sense is to be able to continuously read from a pipe such as for example /dev/jsonlog instead or a network socket. Assumed advantage is to have near-real-time data available. This mostly to work with log files filling rapidly. Polars seems to have everything i need to work with such data.

My intended use for polars is two-fold, to have it as the in-memory datastore where specific datasets are queried for representation to the user, to have it as a pre-processing in-memory datastore where raw data is cleaned up and then logged in a different datastore which may be sql or elastic or elastic-like. The latter use case because i don't need all data for my purposes but all data needs to be archived.

Reading thru the documentation I've looked into connectorX which does offer some options but not the ability to ingest a stream of data such as reading from a pipe or socket.

**Comment by zundertj** [comment]
Please note that ConnectorX is just a way to get data from a SQL database into Polars. We have added a (really small) utility to get users going quickly, but other than that, it is not special in any way, not for ingesting data in general, nor for SQL databases specifically. Anything that can return Arrow format will play well with Polars, as Polars is built on top of Arrow. So if there is a tool that turns a stream of data into Arrow record batches, that will work for Polars.

**Comment by commandline-be** [comment]
What is most aligned with what i have in mind appears to be Arrow-Flight which does offer gRPC 

https://arrow.apache.org/blog/2019/10/13/introducing-arrow-flight/

**Comment by commandline-be** [comment]
> Please note that ConnectorX is just a way to get data from a SQL database into Polars. We have added a (really small) utility to get users going quickly, but other than that, it is not special in any way, not for ingesting data in general, nor for SQL databases specifically. Anything that can return Arrow format will play well with Polars, as Polars is built on top of Arrow. So if there is a tool that turns a stream of data into Arrow record batches, that will work for Polars.

My request pivots on the ability to ingest data continuously, not about getting it into Arrow/Polars.

**Comment by zundertj** [comment]
I may be misunderstanding your request, but ingesting data into Polars means the data has to be transformed to Arrow/Polars format. That does not hinge on continuously or not.

Note that Arrow Flight has a stream reader that returns Arrow tables and Arrow record batches, both of which should play well with Polars: https://arrow.apache.org/docs/python/generated/pyarrow.flight.FlightStreamReader.html. You could use that open a stream, and pull batches. See also the cookbook: https://arrow.apache.org/cookbook/py/flight.html#arrow-flight.

Maybe it helps if you can provide a small code example of what you want to achieve.

**Comment by alexander-beedie** [comment]
This appears to be something that would be written outside of polars that manages a continuous data pipeline, and polars would be a component of this pipeline. (Note that we are not providing a continuously ticking engine, so data loads are typically "one and done", hence no listeners, etc).
