### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#53]

**Comment by Tseyang** [comment]
I think this would be useful. The existing examples are nice but somehow when I tried the following blocks of code to read a csv:

```
pub fn polars_read_csv(file: File) -> Result<DataFrame> {
    CsvReader::new(file)
        .infer_schema(None)
        .has_header(true)
        .finish()
}

#[tokio::main]
async fn main() -> InsiderTradingResult<()> {
    let file = std::fs::File::open("file.csv")?;
    let df = polars_read_csv(file)?;
    println!("{:#?}", df);  // ---> this only prints the first 10 rows, I assume to do with some sort of laziness
    println!("{}", df.height());  // ---> this prints the 10k+ height correctly
    Ok(())
}
```

How do I do something simple like iterate through the rows of the DataFrame, performing an operation on each row?

I've tried doing `select_series()` on the columns and trying to iterate through that but it only yields the first 10 rows. From testing functions, it appears like index 0 maps to the 0-th column and index 1 to the 1st and 2 onward yield errors. I don't know if I'm missing something blatant but I think examples of such use cases could be super helpful. I like the simplicity and style of the crate so far from what I can see so I'm really hoping I can use this! Thank you!

**Comment by ritchie46** [comment]
Hi, when you print a DataFrame or a Series the output is sliced at 10 rows. Trust me,  you don't want to print 10k rows ;).

What do you want to do? `select_series` expects column names like `&["foo", "bar"]`. You can select a Series by index with the `select_at_idx` method. See the [DataFrame](https://ritchie46.github.io/polars/polars/frame/struct.DataFrame.html) documentation. And take a look at this [notebook](https://github.com/ritchie46/polars/blob/master/examples/10_minutes_to_polars.ipynb). This explains all the basic operations from the `eager` API

**Comment by Tseyang** [comment]
Hi @ritchie46  thank you for responding. So suppose I have 2 columns: `foo` and `bar`. If I want to iterate through the entire DataFrame and access `foo` and `bar` of each row, How would I do so? I have tried doing it with `select_at_idx` but that I'm not sure if I'm doing it wrong.

```
for i in 0..20 {
        let s = df.select_at_idx(i).ok_or_else(|| {
            CustomError(format!("Invalid index: {}", i))
        })?;
        println!("{:#}", s);
    }
```

and this outputs:

```
Series: 'foo' [str]
[
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
]
Series: 'bar' [i64]
[
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
]
CustomError:("Invalid index: 2")
```

I'm suspect I have a conceptual misunderstanding of how this works but my expectation was that the output should have been something like

```
a, 1
b, 2
c, 3
d, 4
e, 5
f, 6
g, 7
h, 8
i, 9
j, 10
k, 11
l, 12
...
```

I have also tried an example from that notebook

```
let s = df.select_at_idx(i).ok_or_else(|| {
            CustomError(format!("Invalid index: {}", i))
        })?;
        s.i64().iter().for_each(|r| {
            println!("{:#?}", r);
        })
```

This yields something like 

```
ChunkedArray: 'CIK' [Int64]
[
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
]
```

All the way through the DataFame. What is my mistake here? How should I go about iterating through everything row by row in the whole DataFrame or Series?

**Comment by ritchie46** [comment]
Let's continue this chat on [gitter](https://gitter.im/polars-rs/community). That's more intended for these kind of questions. I'll put my answer there. ;)
