### ISSUE TITLE
Can't exclude datetime[ns] by targeting pl.DateTime

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5300]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I was trying to drop a datetime[ns] column today, so I did `pl.all().exclude(pl.Datetime)`, but this does not drop it. It does drop datetime[us] columns

### Reproducible example

```python
import pandas as pd
import polars as pl
(
    pl.from_pandas(pd.date_range("2021-01-01", "2021-01-02"))
    .to_frame()
    .with_column(pl.lit(1))
    .select(pl.all().exclude(pl.Datetime))
)
# leaves both datetime and literal columns
```

### Expected behavior

Works for the regular polars-created type
```python
(
    pl.Series(name="foo", values=[], dtype=pl.Datetime)
    .to_frame()
    .with_column(pl.lit(1))
    .select(pl.all().exclude(pl.Datetime))
)
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.22
Index type: UInt32
Platform: Linux-5.10.124-linuxkit-aarch64-with-glibc2.28
Python: 3.9.15 (main, Oct 14 2022, 00:47:57) 
[GCC 8.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.4
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by thomasaarholt** [comment]
Selecting has the same issue:
```python
import pandas as pd
import polars as pl
(
    pl.from_pandas(pd.date_range("2021-01-01", "2021-01-02"))
    .to_frame()
    .with_column(pl.lit(1))
    .select(pl.col(pl.Datetime))
)
# Empty dataframe
```

**Comment by zundertj** [comment]
`pl.Datetime` takes in a `tu` (time unit) argument: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.datatypes.Datetime.html

The default is `us`. When you do
```python
>>> pl.Series(name="foo", values=[], dtype=pl.Datetime)
shape: (0,)
Series: 'foo' [datetime[μs]]
[
]
```
a `us`. So the exclude takes it out.

However, converting from Pandas results in a different time unit `ns`
```python
>>> pl.from_pandas(pd.date_range("2021-01-01", "2021-01-02"))
shape: (2,)
Series: '' [datetime[ns]]
[
        2021-01-01 00:00:00
        2021-01-02 00:00:00
]
```
and hence the exclude does not pick up this type.

**Comment by thomasaarholt** [comment]
Ah! That's interesting! Hm. I think I need to sleep on whether I'm fine with this the way it is 😅

**Comment by thomasaarholt** [comment]
Having slept on this, I think that it is currently quite difficult to exclude *all* datetime columns. Given a situation where you don't know the incoming datetime, I have to either exhaustively drop *all* combinations of `time_unit` and `time_zone`, which comes out as 1833 combinations. 

The alternative is to target all _other_ dtypes, and `df.select(all_other_dtypes)`.

`pl.DateTimeAllDtype` or something similar, would be a useful dtype in this case.

**Comment by thomasaarholt** [comment]
The motivation is that I have several `pl.DateTime` columns with `time_unit="ns"` and `time_zone="UTC` that I needed to drop before calling `pl.Categorical` for all non-number columns for later input straight into xgboost as an arrow dataset. In this case, I can

**Comment by zundertj** [comment]
You can provide a list of data types, so for the three time units, you could easily check:
```python
select(pl.all().exclude([pl.Datetime("ms"), pl.Datetime("ns"), pl.Datetime("us")]))
```
That would be unwieldly with all possible timezones, although I guess in practice you won't have a mixture of timezones (or at least I hope so).

Alternatively, if you are ok with determining this in eager mode:

```python
non_datetimes = [c for c, tp in df.schema.items() if not isinstance(tp, pl.Datetime)]
```

**Comment by mcrumiller** [comment]
I feel excluding all `pl.Datetime`s makes the most sense here. The call `.exclude(pl.Datetime)` doesn't specify which type of datetime, and you might not know what the type is at compile time (where, again #4982 would help a lot), and when the a type has multiple subtypes, and you reference the base type, it feels it should apply to all subtypes as well.

**Comment by alexander-beedie** [comment]
I have some ideas here... should have some time in the evening over the next few days to take a look (and certainly at the weekend if things get a bit busy during the rest of the week). Agree that there needs to be a simple way to match _"all Datetimes"_ - or, equally, _"all Durations"_.

**Comment by ritchie46** [comment]
I was also thinking about accepting a wildcard `"*"` as timezone that evaluates to always true in comparison.

**Comment by zundertj** [comment]
> I feel excluding all `pl.Datetime`s makes the most sense here. The call `.exclude(pl.Datetime)` doesn't specify which type of datetime, and you might not know what the type is at compile time (where #4982 would help a lot), and when the base type has multiple subtypes, and you reference the base type, it feels it should apply to all subtypes as well.

I agree, but then we have to change `pl.Datetime` to not default to a particular time unit, which may have implications elsewhere. But there is hopefully a way to make that work.

**Comment by ritchie46** [comment]
> Edit: just seen the response by @ritchie46 : would be even better if we can not have the wildcard, it is additional syntax and thing to remember. But not sure if it is feasible.

We would only set that wildcard in the exclude logic if no timezone is given. A user does not have to know.

**Comment by arturdaraujo** [comment]
I think this issue should be closed due to inactivity

**Comment by alexander-beedie** [comment]
FYI: following https://github.com/pola-rs/polars/pull/6425 you can now exclude all Datetime cols like so...
```python
from polars.datatypes import DATETIME_DTYPES
df.select( pl.exclude(DATETIME_DTYPES) )
```
...though wildcard support for timezones is still outstanding.

The various "official" dtype groups are:
```
DATETIME_DTYPES
DURATION_DTYPES
FLOAT_DTYPES
INTEGER_DTYPES
NUMERIC_DTYPES
TEMPORAL_DTYPES
```

**Comment by zundertj** [comment]
Leaving this open for the time being with the suggestion being to be able to replace this:

```python
from polars.datatypes import DATETIME_DTYPES
df.select( pl.exclude(DATETIME_DTYPES) )
```

with
```python
df.select(pl.exclude(pl.Datetime("*"))
```
