### ISSUE TITLE
extra empty s3 prefixes and extra new-lines to the `partition_cols` s3 prefixes

### ISSUE THREAD

**Issue by clayms** [pola-rs/polars#5301]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When writing a polars dataframe to s3 with `pyarrow.parquet` and `s3fs`, although it works, it adds extra empty prefixes to the s3 path and the resulting `partition_cols` s3 prefixes have multiple new line characters in the prefix (path).

What is the preferred way to write polars dataframes to S3?

Is this caused by the `to_arrow()` polars method, or the `s3fs`, `pyarrow`  libraries; or some combination?

### Reproducible example

```python
## Where `df` is a large polars dataframe.

import pyarrow.parquet as pq
import s3fs

fs = s3fs.core.S3FileSystem(key=KEY_ID, secret=SECRET_KEY_ID)

pq.write_to_dataset(df.to_arrow(), root_path="s3://my-bucket/parquet/myfilename.parquet",
                    partition_cols=["state"],
                    filesystem=fs)
```

### Expected behavior

When inspecting the resulting files in s3 from the cli, I have to add extra `/` after the bucket name, where it should not be needed; and the prefix for the `partition_cols` has extra `\n` characters that are not present in the polars dataframe `df`. 
```bash
$ aws s3 ls s3://my-bucket//parquet/myfilename.parquet

                           PRE state=[
  "AK"
]/
                           PRE state=[
  "AL"
]/
...
...
                           PRE state=[
  "WA"
]/
                           PRE state=[
  "WI"
]/
$
```
This is what I would expect:
```bash
$ aws s3 ls s3://my-bucket/parquet/myfilename.parquet

                           PRE state=["AK"]/
                           PRE state=["AL"]/
...
...
                           PRE state=["WA"]/
                           PRE state=["WI"]/

```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.15
Index type: UInt32
Platform: Linux-5.4.209-116.367.amzn2.x86_64-x86_64-with-glibc2.17
Python: 3.9.10 (main, Aug 30 2022, 02:19:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.3.5
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
```

```
> s3fs.__version__
'2022.8.2'
```

</details>

**Comment by zundertj** [comment]
> When inspecting the resulting files in s3 from the cli, I have to add extra / after the bucket name, where it should not be needed; 

This problem is not related to Polars, seems most likely something with `s3fs`.

> ... and the prefix for the partition_cols has extra \n characters that are not present in the polars dataframe df.

Have you inspected the PyArrow table you create with `df.to_arrow()`; does that contain the `\n` characters? At least that will narrow it down to either Polars on the one hand or PyArrow/s3fs on the other hand.

It could also be that the newlines are s due to the CLI printing it this way, but that there is no actual newline in the file name. Just a guess.

**Comment by clayms** [comment]
@zundertj 
Below is the output of a test dataframe `df_test` in a notebook.

![image](https://user-images.githubusercontent.com/12793783/197593288-6d07ef66-2e22-439b-b8fa-9c2a70bf4ee2.png)

Below is the output of the `State` column polars series, which has the same format as each S3 prefix when I use the `"State"` column to partition on. 
```python
df_test["State"]
```
![image](https://user-images.githubusercontent.com/12793783/197593637-e011a0e0-212f-41c9-8807-048523e67564.png)



Below is the output of `.to_arrow()` 
```python
df_test.to_arrow()
```
![image](https://user-images.githubusercontent.com/12793783/197593981-7529e387-953f-4f7a-ac57-95069bd336ba.png)

**Comment by zundertj** [comment]
Ok, that shows `to_arrow` works as advertised. Thus that is also not a Polars problem, but with PyArrow and/or s3fs. I would suggest checking with those projects what is going on, and/or post it on StackOverflow. Closing here.
