### ISSUE TITLE
Cannot use Expr.exp() in  groupby

### ISSUE THREAD

**Issue by fecet** [pola-rs/polars#5308]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Cannot use `Expr.exp()` in `groupby.agg` while that works in `select`

### Reproducible example

```python
import polars as pl
import numpy as np
df=pl.DataFrame({"group": list("aaabbb"), "value": list(range(6))})
exp=pl.col("value").take(2)-pl.col("value").take(1)
# exp=exp.exp()
exp=np.exp(exp) # Both cases not work
df.groupby("group").agg(exp) # not work
df.select(exp) # work
```

### Expected behavior

Expr.exp() work fine in groupby

### Installed versions

---Version info---
Polars: 0.14.21
Index type: UInt32
Platform: Linux-6.0.1-arch1-1-x86_64-with-glibc2.36
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.0

**Comment by ritchie46** [comment]
You already opened this issue and it has been fixed. https://github.com/pola-rs/polars/issues/5269

**Comment by fecet** [comment]
> You already opened this issue and it has been fixed. #5269

They are not exactly the same, I'm trying to take exponential after the subtraction

**Comment by ritchie46** [comment]
> > You already opened this issue and it has been fixed. #5269
> 
> They are not exactly the same, I'm trying to take exponential after the subtraction

Have you tried polars 0.14.22?
