### ISSUE TITLE
Out of memory for `drop_nulls` even if the DataFrame is loaded.

### ISSUE THREAD

**Issue by PierreSnell** [pola-rs/polars#5323]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When loading a feather dataset (with `read_ipc`) the dataframe (not lazy, full dataframe) is loaded without problems and take some memory. 

When calling `drop_nulls` it seems that it recreates internally some objects and I run in a out of memory (process killed).

Is there anyway to do a `drop_nulls` in place ? As I don't care of the rows with nulls values and that would also reduce my memory footprint. 

Note that I have ~150 000 columns and ~3000 rows. 

### Reproducible example

```python
import polars as pl

pdf = pl.read_ipc(path, row_count_name="idx")
assert "index" in pdf.columns, "There is no index column in this dataframe"
assert pdf.select("index").dtypes[0] == Utf8, "The index is not a string"
assert len(pdf.select("index")[0, 0].split("_")) == 9

pdf = pdf.with_columns(
        [
            pl.col("index").str.split("_").arr.get(0).alias("date"),
            .... # some more
        ]
    )
# Until here everything fits in memory no problem. 
pdf = pdf.drop_nulls("MY_COLUMN_LABEL") # Out Of Memory
print(pdf.head())
```

### Expected behavior

Do it in place, do not recreate some object and do not run out of memory

### Installed versions

<details>

```
---Version info---
Polars: 0.14.21
Index type: UInt32
Platform: Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Python: 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.3
```

</details>

**Comment by ritchie46** [comment]
This is not a bug. The non-null values are copied to a new memory buffer. We need some memory to work with.

You should try lazy, then the filter can be done ar scan and we don't have to keep intermediate dataframes around.

**Comment by PierreSnell** [comment]
Hello @ritchie46, 

Thanks a lot for the fast reply! 

I also tried :

```python
pdf = pl.scan_ipc(path, row_count_name="idx").drop_nulls("MY_COLUMN").collect()
```

But I got the same problem... 

However, with your comment, I did :

```python
pdf = pl.scan_ipc(path, row_count_name="idx").filter(pl.col("MY_COLUMN").is_null()).collect()
```

and it worked perfectly! 

I don't know if it is worth adding some documentation for beginners like me... I'm closing it as the problem is solved but feel free to reopen. 

Thanks.

**Comment by ritchie46** [comment]
Then you need more memory.

**Comment by PierreSnell** [comment]
Thanks, I managed to increase the filtering (like `is_not_null` & >0 & `other` & `other`) which made it possible to load. 

I was surprised that I could `read_ipc` the entire data frame but not `scan` it with filtering. 
In my mind it was kind of  `inplace deletion / drop rows that don't match (only free/reduce memory)`
But I guess that what's streaming will do and I will then be able to load a subset of a huge dataset. 

Thanks again for your time and help, have a great day.
