### ISSUE TITLE
Merge two sorted dataframes into new sorted dataframe

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#5324]
### Problem description

Imagine there are two dataframes both already sorted by key column, i.e. a and b sorted by column k.

I would like to speedup the following polars.concat([a,b]).sort(k).

I believe a lot of code from the sort-merge join recently added to Polars can be directly used here.

This is kinda like a sorted outer-join, but not exactly.

**Comment by mcrumiller** [comment]
You can temporarily get around this using [`polars.Expr.take`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.take.html):

```python
import polars as pl

df1 = pl.DataFrame({'a': [1, 3, 5, 7, 9]})
df2 = pl.DataFrame({'a': [2, 4, 5, 8, 10]})

idx1 = pl.arange(low=0, high=len(df1)*2-1, step=2)
idx2 = pl.arange(low=1, high=len(df1)*2, step=2)

pl.concat((df1.lazy(), df2.lazy())).select(pl.col('a').take(idx1.append(idx2))).collect()
```
```
shape: (10, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 5   │
├╌╌╌╌╌┤
│ 9   │
├╌╌╌╌╌┤
│ 4   │
├╌╌╌╌╌┤
│ ... │
├╌╌╌╌╌┤
│ 7   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 5   │
├╌╌╌╌╌┤
│ 10  │
└─────┘
```

**Comment by marsupialtail** [comment]
@ritchie46 I will upgrade my sponsor level if you implement this :1st_place_medal:

**Comment by ritchie46** [comment]
This will be added by #5817

**Comment by marsupialtail** [comment]
Seems like I have to upgrade my sponsor level then

**Comment by marsupialtail** [comment]
Wait where is the Python API?

**Comment by ritchie46** [comment]
> Wait where is the Python API?

Still working on it ;)

**Comment by marsupialtail** [comment]
I have updated my sponsorship level as promised.

**Comment by george-qi** [comment]
Hi @marsupialtail, I'm wondering if you have any insight on how this function performs if the goal is to do the analogous problem with `n` sorted DataFrames instead of just the two. Is the most efficient way to do this just `df1.merge_sorted(df2).merge_sorted(df3)` and so on?

**Comment by george-qi** [comment]
Hi @ritchie46, thanks for the implementation -- super helpful feature!

I have a quick question if you don't mind. I'm wondering if you have any insight on how this function performs if the goal is to do the analogous problem with `n` sorted DataFrames instead of just the two.

Is the most efficient way to do this just `df1.merge_sorted(df2).merge_sorted(df3).merge_sorted(df4)` and so on, or perhaps some sort of divide and conquer approach, like

```
x = df1.merge_sorted(df2);
y = df3.merge_sorted(df4);
x.merge_sorted(y)
```

to minimize the maximum DataFrame size?
