### ISSUE TITLE
Order of operations matters in expression involving DataFrame

### ISSUE THREAD

**Issue by eskilan** [pola-rs/polars#5327]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Adding or multiplying a number and a polars dataframe results in error if the number comes before the dataframe. I'm not sure if this is a feature or a bug but it looks like the latter.

### Reproducible example
this outputs a DataFrame
```python
import polars as pl
pl.DataFrame([1]) + 1
```

this results in TypeError
```python
import polars as pl
1 + pl.DataFrame([1])
```
TypeError: unsupported operand type(s) for +: 'int' and 'DataFrame'

### Expected behavior

Expected both expressions to be valid

### Installed versions

<details>

```
---Version info---
Polars: 0.14.23
Index type: UInt32
Platform: Linux-4.15.0-194-generic-x86_64-with-glibc2.27
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: <not installed>
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by ghuls** [comment]
Will take a look.
