### ISSUE TITLE
Json Serialization Speed Comparable to Pandas

### ISSUE THREAD

**Issue by colin99d** [pola-rs/polars#5334]
I have been testing pandas.to_json against polars JsonWriter. I have found that for identical data (50,000 rows and 20 columns of 20 character strings) pandas.to_json takes about 0.18 seconds on average while JsonWriter takes about 1.85 seconds. The function below is what I have been using:

```
pub fn df_to_json(df: &DataFrame) -> String {
    let mut buffer = Vec::new();

    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::Json)
        .finish(&mut df.clone())
        .unwrap();

    **the part above takes 1.84 seconds and the part below takes 0.01 seconds**

    String::from_utf8(buffer).unwrap();
}
```
If you would like to see all of the (poorly organized so far) code you can check out the github repo here: https://github.com/colin99d/benchmark-backends.

Digging into pandas it looks like it just calls the cpython json.to_json function, which is documented [here.](https://github.com/python/cpython/blob/main/Lib/json/encoder.py) I would be curious at whether Pandas is so much faster because:
1. My code is poorly optimized
2. Polars currently is not optimized here, but it will be optimized
3. Polars does not look to compete here, so it will not be optimizing further

**Comment by ritchie46** [comment]
Did you run in release mode?

**Comment by colin99d** [comment]
Did not realize using `--release` made the code that much more efficient. Thank you for your help and have a great day.
