### ISSUE TITLE
Implement SQL connections with TurboDBC

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#535]
TurboDBC is probably the fastest method to communicate to a db with arrow data. We can implement utility functions for this in Python.

If `turbodbc` isn't installed we raise an exception. It probably has to be installed with conda, so we cannot add it as optional dependency.

All required arrow interop functions are already available to make this work.

**Comment by DD5HT** [comment]
So pretty much implementing a function:
`def from_db(dsn) -> DataFrame`
should we include a retry mechanism?
I can take care of it :)

**Comment by ritchie46** [comment]
> should we include a retry mechanism?

Don't think that necessary. 

> So pretty much implementing a function:
def from_db(dsn) -> DataFrame

Indeed. :)

**Comment by ptomecek** [comment]
Do you plan to implement predicate and projection pushdown as part of this solution? See also
https://github.com/dask/dask/issues/1957
https://github.com/vaexio/vaex/issues/864

**Comment by ritchie46** [comment]
> Do you plan to implement predicate and projection pushdown as part of this solution? See also
> [dask/dask#1957](https://github.com/dask/dask/issues/1957)
> [vaexio/vaex#864](https://github.com/vaexio/vaex/issues/864)

Eventually I hope to write a crate that allows querying to a database into arrow memory. Once that is in place, pushing down projection and predicates seems logical addition.

**Comment by FlorianWilhelm** [comment]
CC @xhochy, @MathMagique

**Comment by xhochy** [comment]
👋 Happy to support here but `turbodbc` exports `pyarrow.Table` instances; this should suffice, no? (Hint: I haven't yet used `polars`, so I have no idea whether this works flawlessly).

**Comment by ritchie46** [comment]
> wave Happy to support here but turbodbc exports pyarrow.Table instances; this should suffice, no? (Hint: I haven't yet used polars, so I have no idea whether this works flawlessly).

Yes, this should work. We can can use `pl.from_arrow`, which is zero copy in most cases. I know @YuRiTan tried this earlier, but there were some problems which I don't remember.

I think I should just give this another try. :)

**Comment by ritchie46** [comment]
Has first class support from connector-x

**Comment by saolof** [comment]
Connector-x has the major downside of only accepting string queries though. It is not suitable for many uses, including when your database has french place names with quotes in them
