### ISSUE TITLE
Rolling covariances

### ISSUE THREAD

**Issue by mvanaltvorst** [pola-rs/polars#5354]
### Problem description

Big fan of the library, very much appreciate the work.

I think it would be nice to be able to calculate rolling covariances, similarly to [`Rolling.cov` in Pandas.](https://pandas.pydata.org/docs/reference/api/pandas.core.window.rolling.Rolling.cov.html)

**Comment by ritchie46** [comment]
You should be able to that with a groupby rolling.

**Comment by erinov1** [comment]
Having a utility function for rolling covariance/correlation (of a selection of columns) based on the fast `rolling_mean` and `rolling_var` codepaths (instead of rolling groupby) would be very useful. The pandas implementation just uses pandas rolling `mean` and `var` on pairs of columns: https://github.com/pandas-dev/pandas/blob/v1.5.1/pandas/core/window/rolling.py#L1780-L1804

**Comment by zundertj** [comment]
I recently posted the groupby solution on StackOverflow on a similar question: https://stackoverflow.com/questions/74418401/how-to-use-polars-to-get-the-rolling-values-for-two-dataframes-col-by-col. Using `rolling_mean` and `rolling_var` would probably be faster though as mentioned.

**Comment by ritchie46** [comment]
Is this method slower than in pandas? : https://stackoverflow.com/questions/76153441/how-to-get-rolling-correlation-on-python-polars

**Comment by ChristianCoenen** [comment]
Yes. At least when using it on a large enough data frame.

Here is the logic I am using (it's a small extension of the example you provided):

```python
res = (
    pct_changes_1_w_idx.groupby_rolling(index_column="close_timestamp", period=f"1000i")
    .agg(
        [
            pl.corr(c1, c2).alias(c1 + "_" + c2)
            for c1, c2 in itertools.product(
                pct_changes_1.columns, pct_changes_1.columns
            )
        ]
    )
    .collect()
)
```

If I run this on a 3000x60 data frame, it takes:
- 720 ms in polars
- 729 ms in pandas

If I run this on a 250_000x60 data frame, it takes:
- 58.1 s in polars
- 22.7 s in pandas

**Comment by erinov1** [comment]
@ChristianCoenen did you try imitating what pandas does [here](https://github.com/pandas-dev/pandas/blob/v1.5.1/pandas/core/window/rolling.py#L1780-L1804)? Pandas handles null counts a little more carefully when` ddof > 0` (also easily implemented), but for `ddof=0` it is just

```python
pairs = itertools.combinations(pct_changes_1.columns, 2)

def corr(x: pl.Expr, y: pl.Expr, window: int = 1000) -> pl.Expr:
    mean_x_y = (x * y).rolling_mean(window)
    
    mean_x = x.rolling_mean(window)
    mean_y = y.rolling_mean(window)
    
    x_std = x.rolling_std(window)
    y_std = y.rolling_std(window)

    return (mean_x_y - mean_x * mean_y) / (x_std * y_std)

res = pct_changes_1.select(corr(pl.col(p[0]), pl.col(p[1])).alias("_".join(p)) for p in pairs).collect()
```
On my machine this is 20 times faster than pandas `rolling(1000).corr(ddof=0, pairwise=True)`. I think polars should implement this as a utility function.

**Comment by ritchie46** [comment]
@erinov1 can we do something like this for all ddofs and null_counts? Then we should definitely add this.

**Comment by erinov1** [comment]
@ritchie46 yes, I updated my response above to reflect how pandas handles other ddofs.

**Comment by ritchie46** [comment]
Awesome! Could you make a PR for this and maybe rolling_corr as well.

I really like that this reuses our already fast rolling methods

**Comment by erinov1** [comment]
Sure, I can give it a crack next week.
