### ISSUE TITLE
Add AM/PM options for parse_dates

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5365]
### Problem description

It would be good if Polars could automatically parse datetimes from a CSV like 

9/03/2043 12:35 AM 

with 

%d/%m/%Y %I:%M %p

as these are fairly common.

**Comment by RandomFractals** [comment]
Related issue in Arrow repo: https://github.com/RandomFractals/chicago-crimes/issues/23

@braaannigan thanks for opening this request.

**Comment by RandomFractals** [comment]
Wow, that was fast and all you had to do was add new data parsing patterns? Nice.

Thank @YuRiTan & @ritchie46 for looking into this.
