### ISSUE TITLE
Regression bug: Cannot concat Categoricals from different sources

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#5367]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When concatenating rows from the same DataFrame that include a categorical column, Polars 0.14.24 results in the error 
```
PanicException: should not fail: ComputeError(Borrowed("Cannot concat Categoricals coming from a different source. Consider setting a global StringCache."))
```

This bug didn't exist in version 0.14.18

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "str": ["A", "B", "A", "B", "C"],
        "group": [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col("str").cast(pl.Categorical))

df.collect().write_parquet("test.parquet")
df_import = pl.scan_parquet("test.parquet")

df_1 = df_import.filter(pl.col('group') == 1)
df_2 = df_import.filter(pl.col('group') == 2)

pl.concat([df_1, df_2]).collect()
```

### Expected behavior

```
shape: (5, 2)
┌─────┬───────┐
│ str ┆ group │
│ --- ┆ ---   │
│ cat ┆ i64   │
╞═════╪═══════╡
│ A   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ B   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ B   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ A   ┆ 2     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ C   ┆ 2     │
└─────┴───────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.18
Index type: UInt32
Platform: macOS-12.6-x86_64-i386-64bit
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:54) [Clang 13.0.1 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by mcrumiller** [comment]
If the bug didn't exist in version 0.14.18, it should have. As [per the user guide](https://pola-rs.github.io/polars-book/user-guide/performance/strings.html#categorical-type):

> When two `DataFrames` need to be joined based on string data the `Categorical` data needs to be synchronized (data in column `A` of `df1` needs to point to the same underlying string data as column `B` in `df2`). One can do so by casting data in the `StringCache` context manager. This will synchronize all discoverable string values for the duration of that context manager. If you want the global string cache to exist during the whole run, you can set `toggle_string_cache` to `True`.

In other words, you need to enable the string cache for this:

```python
import polars as pl

# turn on String Cache
pl.toggle_string_cache(True)

df = pl.DataFrame(
    {
        "str": ["A", "B", "A", "B", "C"],
        "group": [1,1,2,1,2]
    }
).lazy()

df = df.with_column(pl.col("str").cast(pl.Categorical))

df.collect().write_parquet("test.parquet")
df_import = pl.scan_parquet("test.parquet")

df_1 = df_import.filter(pl.col('group') == 1)
df_2 = df_import.filter(pl.col('group') == 2)

print(pl.concat([df_1, df_2]).collect())
```
```
shape: (5, 2)
┌─────┬───────┐
│ str ┆ group │
│ --- ┆ ---   │
│ cat ┆ i64   │
╞═════╪═══════╡
│ A   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ B   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ B   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ A   ┆ 2     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ C   ┆ 2     │
└─────┴───────┘
```

**Comment by ritchie46** [comment]
> @mcrumiller Thanks for your response and sorry that I didn't get back earlier. I still got an open question on this: From the documentation that you linked it says that this is not necessary for LazyFrames (which my example uses). Essentially, I'm concatenating two parts of the same LazyFrame and still I need a global string cache?

Hmm... That is incorrect of the user guide. We need to update that information.
