### ISSUE TITLE
read_ndjson and scan_ndjson stop randomly after part of file

### ISSUE THREAD

**Issue by j-adamczyk** [pola-rs/polars#5371]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I tried reading `yelp_academic_dataset_review.json` file from a [Yelp dataset](https://www.yelp.com/dataset) with `read_ndjson` and `scan_ndjson` functions. This file is too big to fit in my memory with Pandas. I wanted to remove a few columns. However, both functions read only a quite random number of rows (3534) and then stop. This is very weird, as `read_ndjson` should not even work at all due to memory constraints.

### Reproducible example

```python
import polars as pl

df_filtered = (
    pl
    .scan_ndjson("yelp_academic_dataset_review.json")
    .drop(["useful", "funny", "cool", "text", "date"])
    .collect()
)

print(df_filtered.shape)
```

This prints `(3534, 4)`.

### Expected behavior

1. `read_ndjson` should probably fail due to lack of memory, like Pandas
2. `scan_ndjson` should read all lines lazily, drop columns and return filtered DataFrame

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Python: 3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: None
pandas: <version not detected>
numpy: 1.21.5
fsspec: None
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2

```

</details>

**Comment by ritchie46** [comment]
@universalmind303 could you take a look at this one?

**Comment by universalmind303** [comment]
So it looks like it has something to do with the escaped quotes in the utf8 fields. Still trying to pinpoint the root cause though.

**Comment by universalmind303** [comment]
Until this is resolved, you can read using pyarrow as a workaround. 

```py
import polars as pl
from pyarrow import json as pa_json

tbl = pa_json.read_json("~/Downloads/yelp_dataset/yelp_academic_dataset_review.json")
df = pl.from_arrow(tbl)
```

**Comment by universalmind303** [comment]
@ritchie46 this seems like it's actually a bug with the custom `SplitLines` implementation. _(which we are using in the ndjson reader too)_. I am able to replicate the issue in CSV format. 

If a field has a single double quote `"`, it won't properly parse the CSV. 

```rust
#[test]
fn test_escape_quote() {
    let csv = r#"text,date
"an unescaped quote,2013-08-03 15:17:23
a normal column,2009-05-19 21:07:53
"#;
    let file = Cursor::new(csv);
    let df = CsvReader::new(file).finish().unwrap();
    println!("df: {:?}", df);
    println!("text: {}", df.column("text").unwrap().get(0));
    assert_eq!(df.shape(), (2, 2));
}

**Comment by ritchie46** [comment]
That's not a bug from a csv parsing perspective. According to https://www.rfc-editor.org/rfc/rfc4180 csv quotes need to be escaped.

We follow the rfc for csv files. For json files we need another splitfields implementation as json doesn't have the same escaping rules as csv.
