### ISSUE TITLE
Min of column with NaN returns wrong value

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#5375]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Extracted from `test_nan_aggregations`, which fails for me on master, but CI clearly passes:

```python
import polars as pl
df = pl.DataFrame({"a": [1.0, float("nan"), 2.0, 3.0]})

```

Check:
```
shape: (4, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
├╌╌╌╌╌┤
│ NaN │
├╌╌╌╌╌┤
│ 2.0 │
├╌╌╌╌╌┤
│ 3.0 │
└─────┘
```

This is not good:
```python
>>> df.select(pl.col("a").min())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 2.0 │
└─────┘
```

I played around a bit to see what drives it, and it seems that when there is a `NaN`, min takes the value appearing after the `NaN`:

```python
>>> df = pl.DataFrame({"a": [1.0, 2., float("nan"), 3.0]})
>>> df.select(pl.col("a").min())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 3.0 │
└─────┘
```
or NaN if there is no value after:

```python
>>> df = pl.DataFrame({"a": [1.0, 2., 3., float("nan")]})
>>> df.select(pl.col("a").min())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ NaN │
└─────┘
```
But that is speculation, haven't looked into the Rust code. Note that `max` works properly.

### Reproducible example

```python
See above.
```

### Expected behavior

Return the lowest non-NaN value.

I understand this is a case of "works (not) on my machine", but hopefully we can trace this back to something.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.5 (main, Jul  8 2022, 14:32:56) [GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: None
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: 3.6.0
```

</details>

**Comment by mcrumiller** [comment]
This is very odd; it works fine for me:

```
>>> df.select(pl.col('a').min())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘
>>> df = pl.DataFrame({"a": [1.0, 2., 3., float("nan")]})
>>> df.select(pl.col("a").min())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘
```

**Comment by ritchie46** [comment]
It might be that the simd implementation is different. @zundertj does the development build also give you those results if you turn simd off in Cargo.toml?

**Comment by taozuoqiao** [comment]
It also works fine for me on Centos 7.
```
In [46]: >>> df = pl.DataFrame({"a": [1.0, 2., float("nan"), 3.0]})
    ...: >>> df.select(pl.col("a").min())
Out[46]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘

In [47]: >>> df = pl.DataFrame({"a": [1.0, 2., 3., float("nan")]})
    ...: >>> df.select(pl.col("a").min())
Out[47]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘
```

**Comment by zundertj** [comment]
* I turned off `simd` (I think), by commenting the two lines with `nightly` out in `cargo.toml`, and run a new `make test` to go through the compilation step. Issue persists.
* I double checked in a clean venv the latest wheel on PyPi, and also there the issue exists. 
* The problem does not exist on the Python install directly on my Windows (Python 3.10.4)

There has to be something about my setup (WSL, compilers) that drives this.

**Comment by zundertj** [comment]
@ritchie46 : well done sir, can confirm that #5403 fixes the issue. Test suite passes again.
