### ISSUE TITLE
 Code example in keep_name does not show functionality

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5378]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In the [documentation for `keep_name`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.keep_name.html), the output of the example is the same in the case where `keep_name` is not used and when it's used:

<blockquote>

### Examples

A groupby aggregation often changes the name of a column. With *keep_name* we can keep the original name of the column

```python
>>> df = pl.DataFrame(
...     {
...         "a": [1, 2, 3],
...         "b": ["a", "b", None],
...     }
... )
>>> df.groupby("a").agg(pl.col("b").list()).sort(by="a")
shape: (3, 2)
┌─────┬───────────┐
│ a   ┆ b         │
│ --- ┆ ---       │
│ i64 ┆ list[str] │
╞═════╪═══════════╡
│ 1   ┆ ["a"]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ ["b"]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ [null]    │
└─────┴───────────┘
```
Keep the original column name:
```python
>>> df.groupby("a").agg(pl.col("b").list().keep_name()).sort(by="a")
shape: (3, 2)
┌─────┬───────────┐
│ a   ┆ b         │
│ --- ┆ ---       │
│ i64 ┆ list[str] │
╞═════╪═══════════╡
│ 1   ┆ ["a"]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ ["b"]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ [null]    │
└─────┴───────────┘
```

</blockquote>

### Reproducible example

```python
n/a
```

### Expected behavior

The example should show a change in behavior when `keep_name` is used. The first example needs to be a case whereby the column name changes.

I can't seem to find such an instance, but if someone wants to point me to an example where the column name changes, I can create a PR.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment]
Right! Can you think of one? Maybe one where we do multicolumn arithmetic. `(6 * pl.all()).keep_name()`

**Comment by mcrumiller** [comment]
Multi-column arithmetic doesn't seem to change the name either. A simple example would be something like:
 
```python
df = pl.DataFrame({
    'a': [1, 2, 3, 4, 5]
})
df.select(pl.col('a').alias('b'))
```
shape: (5, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 4   │
├╌╌╌╌╌┤
│ 5   │
└─────┘
```

With `keep_name`:

```python
df.select(pl.col('a').alias('b').keep_name())
```
```
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 4   │
├╌╌╌╌╌┤
│ 5   │
└─────┘
```

However, it's not the greatest example.

**Comment by ritchie46** [comment]
See: https://github.com/pola-rs/polars/issues/3773#issuecomment-1295792884
