### ISSUE TITLE
Importing polars before pandas breaks pandas imports

### ISSUE THREAD

**Issue by mbelak-dtml** [pola-rs/polars#5389]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See title.

Addtional info: The issue is not present in versions `0.14.21` or `0.14.23`. 

### Reproducible example

```python
import polars as pl
import pandas as pd
pd.Series
```

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pandas' has no attribute 'Series'
```

### Expected behavior

Pandas should work even when being imported after polars.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: Linux-6.0.2-2-MANJARO-x86_64-with-glibc2.36
Python: 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.4.4
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
@alexander-beedie could you take a look at this one?

**Comment by alexander-beedie** [comment]
> @alexander-beedie could you take a look at this one? 

On it.

**Comment by mcrumiller** [comment]
This doesn't happen to me at all on 0.14.24. Is there any chance you accidentally screwed up your imports?

**Comment by mbelak-dtml** [comment]
@mcrumiller Still happens. List of installed packages (using Poetry venv, output of `poetry show`):
```
numpy           1.23.4  NumPy is the fundamental package for array computing with Python.
pandas          1.5.1   Powerful data structures for data analysis, time series, and statistics
polars          0.14.24 Blazingly fast DataFrame library
python-dateutil 2.8.2   Extensions to the standard Python datetime module
pytz            2022.6  World timezone definitions, modern and historical
six             1.16.0  Python 2 and 3 compatibility utilities
``

**Comment by mbelak-dtml** [comment]
With `pyarrow` added to the environment above (version `10.0.0`) it doesn't happen.

**Comment by mcrumiller** [comment]
The first thing I would do is open up `__init__.py` in the pandas library and set a breakpoint at line 48, where `Series` gets imported:

```python
48 from pandas.core.api import (
49      # dtype
50      ArrowDtype,
51      Int8Dtype,
    ....
109     Series,
110     DataFrame,
111 )
```

Find out where your import gets clobbered after that.

**Comment by alexander-beedie** [comment]
Can confirm it's a real issue as I was (finally!) able to reproduce - took me a while, until I realised that the IDE itself was triggering "proper" load via implicit watch variables in the console ;)

Not obvious to me why the module loader isn't triggered yet, but at least I can now reproduce so I should be able to work it out.

**Comment by alexander-beedie** [comment]
> With `pyarrow` added to the environment above (version `10.0.0`) it doesn't happen.

Interesting... every bit of information helps, thanks.

**Comment by alexander-beedie** [comment]
Just got home, setup a completely clean environment, and am now able to _consistently_ reproduce again... @mbelak-dtml, thanks again for the clue about `pyarrow` being available or not - I suspect this is the key to resolving things.

**Comment by ritchie46** [comment]
Thanks for looking into this @alexander-beedie. I would need to get accustomed to what do first.

**Comment by alexander-beedie** [comment]
Got it. PR incoming ✌️

**Comment by mbelak-dtml** [comment]
@alexander-beedie Thanks for the fix!
I am sticking with the previous patch version `0.14.23` as a workaround.
