### ISSUE TITLE
`DataFrame` disappears from pandas if polars gets imported first

### ISSUE THREAD

**Issue by astrojuanlu** [pola-rs/polars#5392]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

```
In [1]: import polars as pl

In [2]: import pandas as pd

In [3]: pd.DataFrame
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [3], line 1
----> 1 pd.DataFrame

AttributeError: module 'pandas' has no attribute 'DataFrame'
```

On the other hand:

```
In [1]: import pandas as pd

In [2]: pd.DataFrame
Out[2]: pandas.core.frame.DataFrame

In [3]: import polars as pl

In [4]: pd.DataFrame
Out[4]: pandas.core.frame.DataFrame
```

### Reproducible example

```python
import polars as pl
import pandas as pd
pd.DataFrame
```

### Expected behavior

Importing Polars has no side effects on pandas.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
---Optional dependencies---
pyarrow: None
pandas: 1.5.1
numpy: 1.23.4
fsspec: None
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by mcrumiller** [comment]
See #5389, this is the same issue and it was resolved in [0349059](https://github.com/pola-rs/polars/commit/03490597bf168fe42f5060865966d4ea648b97a4).

**Comment by alexander-beedie** [comment]
@astrojuanlu apologies for that one; as @mcrumiller says it has been fixed in the upcoming version - in the meantime you can work around it by having `pyarrow` in your environment (just needs to exist, you don't need to actively import it) and/or importing `pandas` first.

**Comment by astrojuanlu** [comment]
Woops, sorry, I promised I checked but I was too fast it seems. Thanks for the quick response!
