### ISSUE TITLE
Create DataFrame with Python Generator (ValueError: Series constructor not called properly.)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#5395]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Creating a DataFrame using a python generator produces `ValueError: Series constructor not called properly.`

Background:
I am working with a JSON file with 100k+ nested objects and want to create a DataFrame from it.
As far as I can see the `read_json` function is not sufficient, because only top-level elements are supported and no deep nested construct like in pandas `json_normalize`.
To avoid overhead I have created generators for my data and want to create a DataFrame with them (which works fine in pandas).

### Reproducible example

```python
import polars as pl
import pandas as pd

seq = range(3)
gen = (x for x in seq)

# ValueError with polars
df = pl.DataFrame({"a": seq, "b": gen})

# works in pandas without problem
df = pd.DataFrame({"a": seq, "b": gen})
```

### Expected behavior

I expected that this works just like it works in pandas without the overhead of first converting the generators into a list.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: macOS-13.0-x86_64-i386-64bit
Python: 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
---Optional dependencies---
pyarrow: None
pandas: 1.5.1
numpy: 1.23.4
fsspec: None
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
I'll have this working shortly (already have it working locally, but needs some tests; will finish tomorrow). 

(As an FYI, pandas actually appears to [fully materialise](https://github.com/pandas-dev/pandas/blob/7ccac683c074aaf5abaedd64f8aa5da4d9fe08ee/pandas/core/common.py#L292) generators before loading the data, so memory-efficiency is debatable there ;)

**Comment by JulianCologne** [comment]
oh wow, that was super fast, thanks a lot!

yes, I already thought that it is not super efficient in pandas. One of the reasons why I'm super interested in polars (+ rust is awesome!).
