### ISSUE TITLE
`count` should ignore nulls while `len` should keep nulls

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pola-rs/polars#5396]
### Problem description

There is a good an lengthy discussion on `null`and `nan `in this issue: https://github.com/pola-rs/polars/issues/5359 . 

The issue was closed but I still think that one point stand which is that `.count `should ignore `nulls` such that `.mean()` and `.sum()/.count()` are equal (see comment https://github.com/pola-rs/polars/issues/5359#issuecomment-1296952056), and have `.len()` keep nulls.  `count` relates to the content of the dataframe/series while `len` describes the dimension/shape.

**Comment by ritchie46** [comment]
I agree. If someone could pick this up, I would merge this.

**Comment by alexander-beedie** [comment]
Just had a related report from one of our users here (literally a few minutes ago :). The `rank` function should also not consider `nulls` by default, eg:

```python
df = pl.DataFrame( {"x":[4,None,8,None]} )
df.with_column( pl.col('x').rank(method='dense') )
# ┌─────┐
# │ x   │
# │ --- │
# │ u32 │
# ╞═════╡
# │ 2   │
# │ 1   │
# │ 3   │
# │ 1   │
# └─────┘

df.to_pandas().rank( method='dense' )
#      x
# 0  1.0
# 1  NaN
# 2  2.0
# 3  NaN

**Comment by zundertj** [comment]
This would be a breaking change, but despite that, I'm in favor of `count` skipping `null` and `nan`.

**Comment by cannero** [comment]
Is anybody working on this feature? I would like to give it a try.

Is it correct that only the  `count` expression for values in a series should be changed, not the `count` in a group by context? And as `count`, similar to for example MySql, does not ignore `nulls` in an aggregation there is also no need for a `len` function in a group by context?

**Comment by ritchie46** [comment]
I was, but I bounced because it is a bit more complicated than I had anticipated. 

For instance `pl.count()` does not have a column origin, so it does not know how it can subtract a null count. I think we should maintain a full count on `pl.count` and for `pl.col(..).count()` we could consider accepting a `include_nulls` argument.

**Comment by cannero** [comment]
To me it makes sense to maintain a full count on `pl.count()`, it is not related to any columns. And with a new argument on count the user can skip nulls even in the group by context.

Do you mean that only for `pl.col(..).count()` the `include_nulls` argument should be added and not for `pl.count('col_name')`? I think this is also fine, if nulls should be skipped a `col` expression can be used.

**Comment by thomasfrederikhoeck** [comment]
Isn't `pl.count("col_a")` just a shorthening of `pl.col("col_a").count()` so the `include_nulls` would work here too?

**Comment by ritchie46** [comment]
> Isn't `pl.count("col_a")` just a shorthening of `pl.col("col_a").count()` so the `include_nulls` would work here too?

No, `pl.count()` does not refer to any column. 

> Do you mean that only for pl.col(..).count() the include_nulls argument should be added and not for 

Yes, we could do that. Or we could accept that a `count` always is including nulls and let users write `pl.count() - pl.col("a").null_count()` if needed.

**Comment by Db-pckr** [comment]
Just came in to report this bug when I noted this open issue.
@ritchie46 please do not accept count() always including nulls, this is completely non standard and opposite to any other software doing the same calculation (e.g. even in the most basic excel pivot table, nulls are disregarded).

**Comment by vegarped** [comment]
Very much agree here. With the new release (0.19) where all/any ignore null values it would be more consistent for count() to ignore null values too.

**Comment by owenprough-sift** [comment]
See also: #10016

**Comment by ritchie46** [comment]
> The workaround I've found is to do
> 
> pl.col("col").is_not_null().sum()

This issue is already resolved. Count ignores nulls
