### ISSUE TITLE
Sort method of DataFrame affects join results when joining filtered DataFrame results to itself

### ISSUE THREAD

**Issue by mlbennett** [pola-rs/polars#5406]
**Polars Version Checks**
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars (0.14.25)

**Issue Description**
Sort method of DataFrame affects join results when joining filtered DataFrame results to itself (this issue is not present is 0.13.55)

**Example**
In this example, I want to find the max value for each Group and Datetime.  I do this by creating a DataFrame which selects the first occurring value of the defined group, and then joining it back to the original DataFrame.  The filtered result produces 4 rows which should join back to the original, however it only joins 3 results when sorting by 'Datetime' and 'RowId', while it joins the expected 4 results when sorting only by 'Datetime'.  This behavior does not occur when using 0.13.55 (I haven't tested other prior versions).
```
df = (
        pl.DataFrame
        (
            {
                "Datetime": ['2022-11-02 08:00:00', '2022-11-02 08:00:00', '2022-11-02 08:01:00', '2022-11-02 07:59:00', '2022-11-02 08:02:00', '2022-11-02 08:02:00'],
                "Group": ['A','A','A','B','B','B'],
                "Value": [1,2,1,1,2,1]
            }
        ).with_column(pl.col('Datetime').str.strptime(pl.Datetime, '%Y-%m-%d %H:%M:%S'))
         .with_row_count('RowId')
    )

df1 = df.sort(by=['Datetime', 'RowId'])
df2 = df.sort(by=['Datetime'])

print(df1.frame_equal(df2)) #result is 'True'

filter1 = (df1
           .groupby(['Datetime','Group'])
           .agg([
               pl.all().sort_by('Value', reverse = True).first()
           ])
           .sort(['Datetime','RowId'])
          )

filter2 = (df2
           .groupby(['Datetime','Group'])
           .agg([
               pl.all().sort_by('Value', reverse = True).first()
           ])
           .sort(['Datetime','RowId'])
          )

print(filter1.frame_equal(filter2)) #result is 'True'

final1 = df1.join(filter1, on = 'RowId', how='left').select(pl.exclude(['Datetime_right','Group_right']))
final2 = df2.join(filter2, on = 'RowId', how='left').select(pl.exclude(['Datetime_right','Group_right']))
```

Result of 'final1' (incorrect result):
<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">     <th></th>     <th>RowId</th>      <th>Date</th>     <th>Group</th>      <th>Value</th>      <th>Value_right</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>3</td>      <td>2022-11-02 07:59:00</td>      <td>B</td>     <td>1</td>      <td>NaN</td>    </tr>    <tr>      <th>1</th>      <td>0</td>      <td>2022-11-02 08:00:00</td>      <td>A</td>      <td>1</td>      <td>NaN</td>    </tr>    <tr>      <th>2</th>      <td>1</td>      <td>2022-11-02 08:00:00</td>      <td>A</td>     <td>2</td>      <td>2.0</td>    </tr>    <tr>      <th>3</th>     <td>2</td>      <td>2022-11-02 08:01:00</td>      <td>A</td>      <td>1</td>      <td>1.0</td>    </tr>    <tr>      <th>4</th>      <td>4</td>      <td>2022-11-02 08:02:00</td>      <td>B</td>      <td>2</td>      <td>2.0</td>    </tr>    <tr>      <th>5</th>      <td>5</td>      <td>2022-11-02 08:02:00</td>      <td>B</td>      <td>1</td>      <td>NaN</td>    </tr>  </tbody></table>

Result of 'final2' (expected result):
<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>RowId</th>      <th>Date</th>      <th>Group</th>      <th>Value</th>      <th>Value_right</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>3</td>      <td>2022-11-02 07:59:00</td>      <td>B</td>      <td>1</td>      <td>1.0</td>    </tr>    <tr>      <th>1</th>      <td>0</td>      <td>2022-11-02 08:00:00</td>      <td>A</td>      <td>1</td>      <td>NaN</td>    </tr>    <tr>      <th>2</th>      <td>1</td>      <td>2022-11-02 08:00:00</td>      <td>A</td>      <td>2</td>      <td>2.0</td>    </tr>    <tr>      <th>3</th>      <td>2</td>      <td>2022-11-02 08:01:00</td>      <td>A</td>      <td>1</td>      <td>1.0</td>    </tr>    <tr>      <th>4</th>      <td>4</td>      <td>2022-11-02 08:02:00</td>      <td>B</td>      <td>2</td>      <td>2.0</td>    </tr>    <tr>      <th>5</th>      <td>5</td>      <td>2022-11-02 08:02:00</td>      <td>B</td>      <td>1</td>      <td>NaN</td>    </tr>  </tbody></table>

**Comment by mcrumiller** [comment]
The usual [`sort`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.sort.html) method has a `nulls_last` parameter which determines where nulls go. I'm not sure if that's related to this, but that would be a useful parameter in the `sort_by` method.

**Comment by mlbennett** [comment]
Shouldn’t be related, the two data frames I’m joining have no nulls - the null values are an after-product of the left join.
