### ISSUE TITLE
Move regex-based column selection to a different method, or put it behind a keyword

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#5418]
### Problem description

I think the ability to select columns based on regex is excellent, but I don't think it's "in the right place"

This is for two reasons:

1. It can be a surprise. I appreciate it is unlikely anyone will have a column named `'^.*$'` but it is still a corner case. 
2. It is terse to read in a "wtf" kind of way

I propose the regex functionality be refactored as:

`pl.col(like=pattern)` where `pattern` does not require `^`, `$`, `.`, or `*`

for example:

```
df.select(pl.col('^flag_.*$'))
```

becomes:
```
df.select(pl.col(like='flag_*'))
```

or an entirely separate expression similar to `pl.all()`

A name could be

`pl.regex(pattern)`

**Comment by ritchie46** [comment]
I don't think I want to remove the `col` functionality. There are two type of column names that are not allowed in polars, one being the wildcard: `"*"` and the other column names that start with `"^"` and end with `"$"`. 

I do think we could add a `pl.regex` that automatically inserts the "^{my_pattern}$"` for you. I agree with you that the explicitly is nice.

**Comment by alexander-beedie** [comment]
> I propose the regex functionality be refactored as:
> pl.col(like=pattern) where pattern does not require ^, $, ., or *

Sounds like you actually want `glob` wildcards, rather than `regex`. Maybe something along the lines of `pl.matching(<pattern>, using=<regex|glob>)` that default to glob matches? (glob patterns are trivial to turn into regex under the hood.

**Comment by mkleinbort-ic** [comment]
Either one is fine. I don't know the difference between glob and regex, but either is fine by me.

It's also roughly trivial to implement. I added this to my codebase for now:

```
import polars as pl 
def _regex(pattern):
    return pl.col(f'^{pattern}$')

pl.regex = _regex

df.select(pl.regex('user_.*'))
>>> {Works}
```

Also, just to clarify... why do I have to add a `.` before the wildcard? Is that a bug?

This works

`pl.col('^user_.*$')`

This does not:

`pl.col('^user_*$')`

**Comment by mkleinbort-ic** [comment]
This is ugly, but addresses my ask:

```
import polars as pl 
def _regex(pattern):
    pattern_fix = pattern.replace('.*', '*').replace('*', '.*')
    return pl.col(f'^{pattern_fix}$')

pl.regex = _regex
```

**Comment by mkleinbort-ic** [comment]
You are right. Thanks.

**Comment by zundertj** [comment]
We could add a `regex` keyword argument to `pl.col`, and ignore parsing the arg as a regex but only this new kwarg, but I am not sure we should have a separate method for this. `pl.regex` is very non-descriptive of what it does/presents, as it only describes its input. We could pick another name, like `col_regex`, but it still is another method to the API and creates another way to refer to a (set of) columns.

**Comment by mkleinbort-ic** [comment]
Tbh, my soludion of 

```
import polars as pl 
def _regex(pattern:str)->pl.Expr:
    '''Wrapper around pl.col(pattern) that adds a leading '^', trailing '$' and replaces '*' with '.*' '''
    pattern_fix = pattern.replace('.*', '*').replace('*', '.*')
    return pl.col(f'^{pattern_fix}$')

pl.regex = _regex
```

100% solves my problem. I'd argue that if anyone wants to use pl.col_regex or pl.regex or any such... they can register this themselves. 

Also, on a side note - I'm very happy with how easy it is to add functionality like this to polars. I've added the following to make my porting some of the pandas codebase to Polars "easier":

```
    def _pipe(col:pl.Expr, func:Callable, *args, **kwargs)->pl.Expr:
        '''Equivalent to pd.Series.pipe'''
        return func(col, *args, **kwargs)

    def _regex(pattern:str)->pl.Expr:
        '''Similar to pd.DataFrame.filter(like=pattern)'''
        pattern_fix = pattern.replace('.*', '*').replace('*', '.*')
        return pl.col(f'^{pattern_fix}$')

    def _transform(df:pl.DataFrame, transformations:dict[str, pl.Expr]={})->pl.DataFrame:
        '''Similar to pd.DataFrame.transform'''
        return df.with_columns(**{col: func(pl.col(col)) for col, func in transformations.items()})
        
    def _percentile(col:pl.Expr, over=None):
        '''Equivalent to my to_percentile function.
        
        The max value gets mapped to 1
        The min value gets mapped to 1/len(col) - which should be close to 0 for most groups
        '''
        if over is None:
            return col.rank() / col.count()
        else:
            return col.rank().over(over) / col.count().over(over)
    
    pl.regex     = _regex
    pl.transform = _transform
    pl.Expr.pipe = _pipe
    pl.Expr.percentile = _percentile
```

**Comment by zundertj** [comment]
It is very easy to extend indeed, and I find myself writing a lot of code that takes in a `pl.Expr` and outputs another `pl.Expr`. The one thing I would be careful though is to add it to the `pl` namespace, that may give clashes with future Polars versions potentially (suppose `percentile` is added to Polars), and readers won't be able to find the method in the Polars docs. The benefit in syntax is there, but not very large imo:

```python
my_expr = pl.col("bla")
my_expr.percentile()  # added to pl namespace
percentile(my_expr)  # not added to pl namespace
```

Probably makes more sense if you end up chaining a lot of transformations, the nesting of function calls becomes clunky.

Back on topic: the key argument to make a change here is to be explicit that for `pl.col`, a passed in string represents a regex or glob pattern rather than a literal column name. That could either be done by adding separate methods, or adding keyword arguments to `pl.col`. I would be in favor of the latter solution:

```python
pl.col("col1")
pl.col(regex='^user_.*$')
pl.col(glob="*")  
pl.col("*")  # currently reserved, we should probably nudge users to `pl.all()`?
```
But the question is whether the current way of `pl.col` accepting all of these is confusing/unclear to users at all, i.e., to me it doesn't seem a major issue, except that we do not support `glob` right now.

**Comment by alexander-beedie** [comment]
Use of a kwarg would make thing unambiguous, and in many cases simplify the pattern - at the moment you _have_ to set both anchors (`^`,`$`) for it to be recognised as a regex, eg:`pl.col("^x.*$")` vs `pl.col(regex="^x.")`.

**Comment by zundertj** [comment]
Regex does not require both anchors, right? I mean, you could always rewrite your regex to have both by using wildcards, but it is a limitation of the current implementation that you need to have both start and end anchors.

**Comment by alexander-beedie** [comment]
> but it is a limitation of the current implementation that you need to have both start and end anchors.

Exactly - if we were to make it an explicit kwarg we can drop that limitation (added examples above).

**Comment by alexander-beedie** [comment]
Could extend the idea by making dtype match a param too actually - and could then mix & match them in a way that we can't really do straightforwardly at the moment, eg:

_"Convert cols ending in 'date' that are also strings"_
`pl.col( glob="*date", dtype=pl.Utf8 ).dt.strptime( ... )`

**Comment by zundertj** [comment]
That reminds me of #5419, where the ask is to add `Expr.include()` as the mirror of `Expr.exclude()`. Your proposal would lead to a slightly nicer syntax, and can achieve the same, assuming each arg can be a list.

**Comment by owenprough-sift** [comment]
Is this issue obsoleted by the introduction of selectors in [0.18.1](https://github.com/pola-rs/polars/releases/tag/py-0.18.1)?

**Comment by mkleinbort-ic** [comment]
I agree.
