### ISSUE TITLE
A .include() for the column selection; a mirror of .exclude

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#5419]
### Problem description

Very simple in theory:

We have the pattern `.exclude()` method:

```
df.select(pl.col('*').exclude(['usr_name']))
```
I propose we add 
```
df.select(pl.col('^user_.*$').include(['usr_name']))
```

It does exactly what it seems it does.

**Comment by mlbennett** [comment]
I'm not sure if this answers your use case, but from my understanding the 'select' function handles what you would expect of 'include'.  Using the documentation example for 'exclude' ([https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.exclude.html#polars-exclude](url)), they run the following code to exclude any column ending in 'a':
`df.select(pl.exclude("^.*a$"))`
Conversely, if you wanted to select (or include) all columns ending in a, you could run the following:
`df.select(("^.*a$"))`, or `df.select(pl.col("^.*a$"))` if you like using pl.col.

**Comment by mkleinbort-ic** [comment]
It's not a blocker to my work, I can always do a more complex regex.

It's more about being able to select columns by name and by a regex. 

This does not work:
```
df.select(pl.col(['user_id', 'date']) + pl.col('^data_.*$))
```
nor does this:
```
df.select(pl.col(['user_id', 'date']) | pl.col('^data_.*$))
```

So it's more about having a way to select multiple columns without building complex regex.
