### ISSUE TITLE
add nulls_last argument to all sort methods

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5420]
### Problem description

The input arguments to the various `sort`, `sort_by`, and `argsort` methods are the following, ignoring the `in_place` parameters in `pl.Series.sort`:

|                 | reverse | nulls_last |
|-----------------|---------|------------|
| pl.argsort_by   |    X    |            |
| pl.arg_sort     |    X    |     X      |
| DataFrame.sort  |    X    |     X      |
| LazyFrame.sort  |    X    |     X      |
| Series.arr.sort |    X    |            |
| Series.sort     |    X    |            |
| Series.arg_sort |    X    |     X      |
| Expr.sort       |    X    |     X      |
| Expr.arg_sort   |    X    |     X      |
| Expr.sort_by    |    X    |            |
| Expr.arr.sort   |    X    |            |

It would be nice to have `nulls_last` in all sort methods for both consistency and functionality.

**Comment by zundertj** [comment]
Two questions:

1. Should we consider having a flag for `nan` as well, or do we always follow the floating point standard on `nan`? 

2. I am slightly worried we end up with lots of flags across many methods, but I guess that is inevitable if we want to support this. So just double checking, there is a valid use case for having `null` to show up first? I.e. why not put nulls always last?

**Comment by miXwui** [comment]
@zundertj 
>  So just double checking, there is a valid use case for having null to show up first? I.e. why not put nulls always last?

I just ran across a case where I need to have the primary record at the top of a group, and then `backward_fill` some column values.

The primary record is a row where the `another_id` column (integer) is null.

That primary record is then `backward_fiil`ed by rows after it, and these rows need to be sorted by `another_id` in descending order. Because the greatest `another_id` has the latest value.

Thus I need numerical ID nulls at the top, and then the rest of the numerical IDs sorted in descending order.

Currently both `reverse=True, nulls_last=False` and `reverse=True, nulls_last=True` return the same value:
```python
>>> df = pl.DataFrame(
...     {   "id": [1, 2, 3],
...         "another_id": [6, None, 8],
...         "phone": [111, None, 333],
...         "mobilephone": ["111", "222", "333"],
...     }
... )
>>> df
shape: (3, 4)
┌─────┬────────────┬───────┬─────────────┐
│ id  ┆ another_id ┆ phone ┆ mobilephone │
│ --- ┆ ---        ┆ ---   ┆ ---         │
│ i64 ┆ i64        ┆ i64   ┆ str         │
╞═════╪════════════╪═══════╪═════════════╡
│ 1   ┆ 6          ┆ 111   ┆ 111         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ null       ┆ null  ┆ 222         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 8          ┆ 333   ┆ 333         │
└─────┴────────────┴───────┴─────────────┘
>>> df.sort("another_id", reverse=True, nulls_last=False)
shape: (3, 4)
┌─────┬────────────┬───────┬─────────────┐
│ id  ┆ another_id ┆ phone ┆ mobilephone │
│ --- ┆ ---        ┆ ---   ┆ ---         │
│ i64 ┆ i64        ┆ i64   ┆ str         │
╞═════╪════════════╪═══════╪═════════════╡
│ 3   ┆ 8          ┆ 333   ┆ 333         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 6          ┆ 111   ┆ 111         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ null       ┆ null  ┆ 222         │
└─────┴────────────┴───────┴─────────────┘
>>> df.sort("another_id", reverse=True, nulls_last=True)
shape: (3, 4)
┌─────┬────────────┬───────┬─────────────┐
│ id  ┆ another_id ┆ phone ┆ mobilephone │
│ --- ┆ ---        ┆ ---   ┆ ---         │
│ i64 ┆ i64        ┆ i64   ┆ str         │
╞═════╪════════════╪═══════╪═════════════╡
│ 3   ┆ 8          ┆ 333   ┆ 333         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 6          ┆ 111   ┆ 111         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ null       ┆ null  ┆ 222         │
└─────┴────────────┴───────┴─────────────┘
```

Whereas I'd like this returned:
```python
>>> df.sort("another_id", reverse=True, nulls_last=False)
shape: (3, 4)
┌─────┬────────────┬───────┬─────────────┐
│ id  ┆ another_id ┆ phone ┆ mobilephone │
│ --- ┆ ---        ┆ ---   ┆ ---         │
│ i64 ┆ i64        ┆ i64   ┆ str         │
╞═════╪════════════╪═══════╪═════════════╡
│ 2   ┆ null       ┆ null  ┆ 222         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 8          ┆ 333   ┆ 333         │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 6          ┆ 111   ┆ 111         │
└─────┴────────────┴───────┴─────────────┘
```
So that row `id == 2` has the `phone` value `backward_fill`ed by `id == 3`'s `333` phone value.

**Comment by stinodego** [comment]
This has been completed.
