### ISSUE TITLE
Provide detailed build information in the installed polars

### ISSUE THREAD

**Issue by slonik-az** [pola-rs/polars#5422]
### Problem description

When troubleshooting polars deployments it is quit useful to be able to access detailed informaiton about how this instance of `polars` was build. What features were enabled, what versions of dependencies used, what optimization debug flags, exact git commit hash, rustc version, etc.

A possible implementation calls for a function `polars.build_info()` that returns such information as a tree (a dict).

**Comment by slonik-az** [comment]
I will provide a PR shortly.

**Comment by slonik-az** [comment]
PR #5423 submitted.

**Comment by zundertj** [comment]
Left a couple of comments on the PR, and as said on the PR, why not integrate in `show_versions`?
