### ISSUE TITLE
Rename keyword argument reverse to ascending for sorting methods

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#5429]
### Summary
In Polars, the sorting methods (on expressions/series/dataframes) have a keyword argument named `reverse`. I propose to change this name to `ascending`.

### Rationale
The issue I have with `reverse` is that it does not tell me what "non reverse" / "normal" is. The docstring on for example  [DataFrame.sort](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.sort.html) also acknowledges this, because it says:

```
    reverse

        Reverse/descending sort.
```
I.e., reverse=descending, so non-reverse=ascending. You wouldn't know from the parameter name itself. Docs are good, but proper argument naming is better.

Pandas does use [ascending](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html). Pandas consistency is not a goal, but I feel Pandas has the better naming here. 

PyArrow opts for the name `order`, and asks for a string to be passed in (ascending or descending). See for example [array_sort_indices](https://arrow.apache.org/docs/python/generated/pyarrow.compute.array_sort_indices.html#pyarrow.compute.array_sort_indices). As long as we can imagine having only two orderings, a bool is easier than a string imo, so I like the Pandas approach more.

Moreover, I don't see a drawback in adopting this terminology, other than that we have to do a one-time breaking release.

**Comment by zundertj** [comment]
(not knowing the Rust code that well) We could set the default for `ascending` to `True`, or if we go with `descending` to `False`, both will achieve ascending by default. Reason I picked `ascending` and not `descending` is that is what Pandas does. Probably a matter of taste.

**Comment by ritchie46** [comment]
Yes, I have been thinking about this one as well. I think we should name it to `descending` so that the default in rust remains in ascending order.

If we do this we need to do both rust and python at once.
