### ISSUE TITLE
`write_csv` fails with `TextIO` target

### ISSUE THREAD

**Issue by terrorfisch** [pola-rs/polars#5438]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The type annotation of `DataFrame.write_csv` includes `TextIO` but raises `OSError: string argument expected, got 'bytes'` when called with `io.StringIO` or a file handle with text encoding on windows.

This is apparently because `PyFileLikeObject` assumes that it wraps `BytesIO`.

One possible solution is to check if `inner` has the `encoding` attribute which is part of [`TextIOBase`](https://docs.python.org/3/library/io.html#io.TextIOBase) and handle this case differently. This will introduce some overhead because it requires all calls to `PyFileLikeObject::write` to write valid UTF-8.

The other solution would be to remove `TextIO` from the supported write targets.

### Reproducible example

```python
import io
import polars as pl

target = io.StringIO()
df = pl.DataFrame([[1, 2, 3]])
df.write_csv(file=target)
```
raises `OSError: string argument expected, got 'bytes'`

```python
import tempfile
import polars as pl

df = pl.DataFrame([[1, 2, 3]])
with tempfile.TemporaryFile(mode="w") as target:
    df.write_csv(file=target)
```
raises `OSError: write() argument must be str, not bytes`

### Expected behavior

Output gets written to `StringIO` or python created text file.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Windows-10-10.0.19043-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.6.2
```

</details>

**Comment by terrorfisch** [comment]
I created failing unittest here: https://github.com/terrorfisch/polars/tree/write_csv_textio

**Comment by ritchie46** [comment]
I think we should  update our type signature. We write bytes, not strings.
