### ISSUE TITLE
Faster multi column sort.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#5443]
### Problem description

Faster multi column sorting by sorting encoded forms of each column. 
https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/

https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-1/

https://github.com/apache/arrow-rs/pull/2929

**Comment by ritchie46** [comment]
Yeah, I read the duckdb post a while ago already. I think we first need to do some comparisons. How are we doing against duckdb and arrow on this?

**Comment by ghuls** [comment]
Not sure how fast we are compared with duckdb and arrow-rs, but it seems that compared with their old implementation, they get a big speedup.

> Using this format for lexicographic sorting is more than [3x](https://github.com/apache/arrow-rs/pull/2929) faster than the comparator based approach, with the benefits especially pronounced for strings, dictionaries and sorts with large numbers of columns.
> 
> We have also already used it to more than [double](https://github.com/apache/arrow-datafusion/pull/3386) the performance of sort preserving merge in the [DataFusion project](https://arrow.apache.org/datafusion/), and expect similar or greater performance uplift as we apply it to sort, grouping, join, and window function operators as well.

**Comment by ritchie46** [comment]
I think we still first need to check before we can conclude that ours would speed up from this. We have a different sort implementation.

**Comment by ritchie46** [comment]
We have proper row encoding now.
