### ISSUE TITLE
Coalesce should document use of pl.lit for non-numeric types

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5446]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

According to the docstring, coalesce can take string arguments to target column names. Numeric types are taken as literals. Since I targeted my columns via `pl.col("col_name")`, and replaced numeric nulls via the the literal `5`, I instinctively tried to do the same to replace nulls with empty strings: `pl.coalesce([pl.col("string"), ""])`. 

It would be nice if the docstring explained clearly what to do.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"number":[1, 2, None], "string":["foo", "bar", None]})

df.with_columns([
    pl.coalesce([pl.col("number"), 5]),
    pl.coalesce([pl.col("string"), ""]) # "" is wrong, correct is pl.lit("")
    ])
```

### Expected behavior

Docstring should specify that strings target column names, and `pl.lit` should be used to specify a literal value to replace nulls by.

### Installed versions

<details>

```
I checked github master's docstring
```

</details>

**Comment by alexander-beedie** [comment]
Hmm... truthfully it would probably be less confusing in this context if literals were _always_ literals, rather than "sometimes" literals? More consistent 🤔

**Comment by thomasaarholt** [comment]
Much agreed :)

**Comment by ritchie46** [comment]
Could you make a PR?

**Comment by stinodego** [comment]
> It would be nice if the docstring explained clearly what to do.

It already does state this very explicitly:

```
    Parameters
    ----------
    exprs
        Columns to coalesce. Accepts expression input. Strings are parsed as column
        names, other non-expression inputs are parsed as literals.
```

> Hmm... truthfully it would probably be less confusing in this context if literals were always literals, rather than "sometimes" literals? More consistent at least 🤔

This discussion has been had many times before. We don't want to lose the ergonomics of `df.select("a", "b")`, and thus strings refer to column names.
