### ISSUE TITLE
list[int32] multiplication crashes Jupiter kernel

### ISSUE THREAD

**Issue by franz101** [pola-rs/polars#5452]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Multi-dimension list multiplication leads to a crash.
If I have an n-dim numpy array and convert it to a list to save into polars.
Multiplication fails.

### Reproducible example

```python
import numpy as np
import polars as pl
x = np.array([[2, 2, 4], [4, 5, 100]], np.int32)
y = np.array([[2, 2, 4], [4, 5, 10]], np.int32)
df = pl.DataFrame({"x":x,"y":y})
df.with_column(pl.col("x") * pl.col("y"))
```

### Expected behavior

x*y

array([[   4,    4,   16],
       [  16,   25, 1000]], dtype=int32)

### Installed versions

---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2022.10.0
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.2.2

**Comment by slonik-az** [comment]
The reproducible example above makes no sense, for does not even import `polars`. Please correct.

**Comment by franz101** [comment]
Hey @slonik-az, yeah the example missed the import. Corrected it.
```python
import numpy as np
import polars as pl
x = np.array([[2, 2, 4], [4, 5, 100]], np.int32)
y = np.array([[2, 2, 4], [4, 5, 10]], np.int32)
df = pl.DataFrame({"x":x,"y":y"})
df.with_column(pl.col("x") * pl.col("y"))
```

any thoughts on it?

**Comment by franz101** [comment]
or do I need to solve it in this context?

https://pola-rs.github.io/polars-book/user-guide/dsl/list_context.html

**Comment by ritchie46** [comment]
Does it really crash you kernel? I observe only a panic?

**Comment by stinodego** [comment]
This panics, it does not crash the Jupyter kernel.

You could argue it should show a nice error instead of a panic. That can be a separate issue. I will close this one.
