### ISSUE TITLE
Setting column-type to category crashes when instantiating dataframe

### ISSUE THREAD

**Issue by Trollgeir** [pola-rs/polars#5457]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following code crashes in newest version (0.14.26). Works in 0.14.17 (unsure when it was introduced).

Output is:
`thread '<unnamed>' panicked at 'Categorical(None) not supported', /home/runner/work/polars/polars/polars/polars-core/src/series/any_value.rs:202:19`

### Reproducible example

** EDITED **

```python
import polars as pl

pl.DataFrame(
    [["test1",8], ["test2", 8]],
    columns=[("cat", pl.Categorical), ("int", pl.UInt8)],
    orient="row",
)
```

### Expected behavior

```
shape: (2, 2)
┌───────┬─────┐
│ cat   ┆ int │
│ ---   ┆ --- │
│ cat   ┆ u8  │
╞═══════╪═════╡
│ test1 ┆ 8   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ test2 ┆ 8   │
└───────┴─────┘
>>> 

```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.4
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ghuls** [comment]
It works with `col` orientation (recommended initialization method).

```python
In [7]: import polars as pl
   ...: 
   ...: pl.DataFrame(
   ...:         [['test1', 'test2']],
   ...:         columns=[("cat", pl.Categorical)],
   ...:         orient="col",
   ...:     )
Out[7]: 
shape: (2, 1)
┌───────┐
│ cat   │
│ ---   │
│ cat   │
╞═══════╡
│ test1 │
├╌╌╌╌╌╌╌┤
│ test2 │
└───────┘
```

**Comment by Trollgeir** [comment]
So would you consider this to be a bug before when `row` worked?

**Comment by Trollgeir** [comment]
@alexander-beedie that was impressively fast! Bear in mind I just updated my example.

**Comment by alexander-beedie** [comment]
> @alexander-beedie that was impressively fast! Bear in mind I just updated my example.

Yup; the fix also works fine with the updated example.

```python
# shape: (2, 2)
# ┌───────┬─────┐
# │ cat   ┆ int │
# │ ---   ┆ --- │
# │ cat   ┆ u8  │
# ╞═══════╪═════╡
# │ test1 ┆ 8   │
# │ test2 ┆ 8   │
# └───────┴─────┘
```
