### ISSUE TITLE
Methods of pl.col().dt and .str are no longer recognised by autocomplete

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5460]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The methods of .dt and .str are no longer autocompleted or showing docstrings, making them very hard to use:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/2721423/200924674-10c2efad-0e4d-4306-836e-6883fa7e0281.png">

### Reproducible example

```python
import polars as pl
pl.col("asd").dt.week
```

### Expected behavior

Show a docstring and autocomplete

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.28
Python: 3.10.8 (main, Oct 13 2022, 23:54:57) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by alexander-beedie** [comment]
Seems fine to me; this is more likely to be something in your IDE, given that polars doesn't control autocomplete. Try returning to default settings, cleaning any caches/etc? 

<img title="Polars autocomplete" src="https://user-images.githubusercontent.com/2613171/201012101-fd8d0ceb-aa97-42f7-8ddb-360639465579.png" width="400" />

**Comment by thomasaarholt** [comment]
Odd. This is in vscode, and it’s in a docker container that gets rebuilt every day. Let me check with my colleagues.

**Comment by JakobGM** [comment]
I can reproduce this issue. The problem seems to be [this commit](https://github.com/pola-rs/polars/commit/7def610f786b50dc007c8e3d89f93bf142bb525d).

Reproducible example code sample which you can analyze with either `mypy` or `pyright`.

```py
# test.py
import polars as pl

reveal_type(pl.col("").dt)
```

Script to reproduce:

```
cd <REPO_ROOT>/py-polars
echo 'import polars as pl' > test.py
echo 'reveal_type(pl.col("").dt)' >> test.py
mypy test.py
```

This yields:

```
...
test.py:3: note: Revealed type is "Any" 
```

Replacing [this](https://github.com/pola-rs/polars/blob/2b81197d6b7c0c82640d125b48142604b890d717/py-polars/polars/internals/expr/expr.py#L6206) `@accessor` with `@property` yields the following:

```
...
test.py:2: note: Revealed type is "def () -> polars.internals.expr.datetime.ExprDateTimeNameSpace"
```

**Comment by M-Salti** [comment]
I've also had this issue for the past week. Using vscode with polars 0.14.26

**Comment by JakobGM** [comment]
The solution probably involves using `ParamSpec` and/or `Protocol` in the typing of `accessor`.

**Comment by alexander-beedie** [comment]
> I can reproduce this issue. The problem seems to be [this commit](https://github.com/pola-rs/polars/commit/7def610f786b50dc007c8e3d89f93bf142bb525d).
> 
> Reproducible example code sample which you can analyze with either `mypy` or `pyright`.

Interesting! Ok, I take back everything I said before, hah :) 

Looks like something that should be actionable on our side; strange that it doesn't seem to affect PyCharm at all -- I'll see what I can do.

**Comment by alexander-beedie** [comment]
Getting there...

![Screenshot 2022-11-10 at 18 31 55](https://user-images.githubusercontent.com/2613171/201118691-a1593f67-60b0-4b00-be67-e7995954d56c.png)

**Comment by physinet** [comment]
I think this is also manifesting as a pylint error. Ran into this for example: "E1101: Method 'str' has no 'json_path_match' member"

**Comment by alexander-beedie** [comment]
Cracked the case, and installed VSCode to properly validate it - this must be one of those classic Vim/Emacs or Canon/Nikon divides, because I truly don't get VSCode, heh. (Though the actual editor looks really nice and responsive). Anyway, should be good once the above patch makes it in.

@JakobGM: I got quite far with `Generic`, but keeping all three legs of the tripod happy was a real uphill battle (Sphinx, PyCharm, VSCode) so I ended up re-framing things ;)

**Comment by alexander-beedie** [comment]
@thomasaarholt: normal service should be restored from 0.14.27; give it a go and let me know if you see anything untoward? Thanks for the heads-up ;)

**Comment by mcrumiller** [comment]
I know this was closed, but I noticed that I can no longer call `pl.testing....()`, as I get the following:

```
>>> pl.testing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'polars' has no attribute 'testing'
```

But I can still call `from polars import testing` and then use those methods. Is this related, or should I open a separate ticket?

**Comment by mcrumiller** [comment]
Nevermind, looks like it was yanked from `__init__.__all__` in #4493 during the import optimization PR.

**Comment by alexander-beedie** [comment]
> Nevermind, looks like it was yanked from `__init__.__all__` in #5284 during the import optimization PR.

Indeed - that one is by design, to avoid loading testing modules (and their associated imports) implicitly. Use of `testing` needs to be explicit now.
