### ISSUE TITLE
Some polars expressions cannot be pickled

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#5461]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Heh I'm back again :^) I found that when trying to pickle a closure of a python function I ended up pickling a polars expression which failed:

### Reproducible example

```
import pickle
import polars as pl
pickle.loads(pickle.dumps((pl.col("a").sqrt() / pl.col("b")).alias("c")))

Exception:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "" })', src/lazy/dsl.rs:97:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/scratch/rzhang/venvs/algovenv10-polars/lib/python3.8/site-packages/polars/internals/expr/expr.py", line 265, in __setstate__
    self._pyexpr.__setstate__(state)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "" })
```

### Expected behavior

I'd expect this expression to pickle successfully, since a plain `pl.col("b")` can be pickled successfully. Is this an edge case or am I using polars incorrectly?

### Installed versions

<details>
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux
Python: 3.8.7 (default, Dec 22 2020, 16:05:35)
[GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.1.5
numpy: 1.18.5
fsspec: 0.8.5
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.3.4+1.g5571742a4
</details>

**Comment by ritchie46** [comment]
This is correct, we are transitioning all our expressions to another architecture internally which also allows pickling.

So when you need a specific expression to be serializable, open an issue and we can transition that one. For most it is trivial work, but work nonetheless that's why we are a little in debt here. I shall add the `sqrt` expression.

**Comment by OneRaynyDay** [comment]
Gotcha, thanks for the context! I can also help contribute to serialization of other expressions once I see an example I can work off of.

**Comment by ritchie46** [comment]
Hmm.. the culprit was our serialization method, not a non-supported expression. I will have to investigate this further. For now I use json as fallback. Which should be fine as expressions don't contain any data, so it will remain small in practice.
