### ISSUE TITLE
sort_by causes `capacity overflow` error

### ISSUE THREAD

**Issue by rockpunk** [pola-rs/polars#5463]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi!  I was trying to run a simple `select a where b order by c desc` type of query, but polars decided to freak out and die pretty spectacularly (made python segfault trying to allocate a huuuuuuge amount of memory). 

I've distilled the dataset down to a tiny dataset that reproduces the rust panic though the python process doesn't completely die with this example.

Interestingly, using `.sort_by("c")` instead of reverse ordering causes a hang followed by an eventual python interpreter getting killed.

Also worth noting, _removing_ the `filter` clause works fine.

### Reproducible example

```python
import os
import polars as pl

os.environ["RUST_BACKTRACE"]="full"

df = pl.DataFrame({"a":["bill","bob","jen","allie","george"],"b":["M","M","F","F","M"],"c":[32,40,20,19,39]})

# `select a where b order by c desc`
df.select(pl.col("a").filter(pl.col("b")=="M").sort_by("c",True))

thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0:        0x10a3fcc88 - _ffi_select_with_compiled_path
   1:        0x1096774c8 - _BrotliDecoderVersion
   2:        0x10a3db934 - _ffi_select_with_compiled_path
   3:        0x10a3fd974 - _ffi_select_with_compiled_path
   4:        0x10a3fd5d4 - _ffi_select_with_compiled_path
   5:        0x10a3fe4a8 - _ffi_select_with_compiled_path
   6:        0x10a3fe00c - _ffi_select_with_compiled_path
   7:        0x10a3fdfa0 - _ffi_select_with_compiled_path
   8:        0x10a3fdf7c - _ffi_select_with_compiled_path
   9:        0x10a4e76ec - _ffi_select_with_compiled_path
  10:        0x1092d5b68 - _PyInit_polars
  11:        0x10a5785c0 - _ffi_select_with_compiled_path
  12:        0x10974bdac - _ffi_select_with_compiled_path
  13:        0x109b9faec - _ffi_select_with_compiled_path
  14:        0x109b7f884 - _ffi_select_with_compiled_path
  15:        0x10a01e510 - _ffi_select_with_compiled_path
  16:        0x10a0bfaac - _ffi_select_with_compiled_path
  17:        0x10a0bb290 - _ffi_select_with_compiled_path
  18:        0x10a0c0454 - _ffi_select_with_compiled_path
  19:        0x10a576cbc - _ffi_select_with_compiled_path
  20:        0x10a32a3ac - _ffi_select_with_compiled_path
  21:        0x10a329fc4 - _ffi_select_with_compiled_path
  22:        0x10a3ff564 - _ffi_select_with_compiled_path
  23:        0x18aac426c - __pthread_deallocate
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In [1], line 8
      5 df = pl.DataFrame({"a":["bill","bob","jen","allie","george"],"b":["M","M","F","F","M"],"c":[32,40,20,19,39]})
      7 # `select a where b order by c desc`
----> 8 df.select(pl.col("a").filter(pl.col("b")=="M").sort_by("c",True))

File ~/.pyenv/versions/3.10.7/envs/polars/lib/python3.10/site-packages/polars/internals/dataframe/frame.py:5396, in DataFrame.select(self, exprs)
   5300 def select(
   5301     self: DF,
   5302     exprs: str
   (...)
   5305     | Sequence[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen],
   5306 ) -> DF:
   5307     """
   5308     Select columns from this DataFrame.
   5309
   (...)
   5393
   5394     """
   5395     return self._from_pydf(
-> 5396         self.lazy()
   5397         .select(exprs)
   5398         .collect(no_optimization=True, string_cache=False)
   5399         ._df
   5400     )

File ~/.pyenv/versions/3.10.7/envs/polars/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py:937, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown, common_subplan_elimination, allow_streaming)
    926     common_subplan_elimination = False
    928 ldf = self._ldf.optimization_toggle(
    929     type_coercion,
    930     predicate_pushdown,
   (...)
    935     allow_streaming,
    936 )
--> 937 return pli.wrap_df(ldf.collect())

PanicException: capacity overflow
```

### Expected behavior
Should NOT crash

Should return an error message pertaining to why this is not possible OR return a dataframe of male names sorted by descending age:

```python
pl.DataFrame({"a":["bob","george","bill"]})
```

### Installed versions

<details>
Tested on python 3.9, 3.10 and 3.11rc2 on arm64 mac

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.10.7 (main, Nov  9 2022, 23:18:21) [Clang 14.0.0 (clang-1400.0.29.102)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.6.2
```

</details>

**Comment by mcrumiller** [comment]
My first suspicion was because you're sorting a filtered column by a full column. If you sort by on filtered `c` it works just fine:

```python
import polars as pl

df = pl.DataFrame({
    "a":["bill","bob","jen","allie","george"],
    "b":["M","M","F","F","M"],
    "c":[32,40,20,19,39]
})

df.select(
    pl.col("a").filter(pl.col("b")=="M")
    .sort_by(
        pl.col('c').filter(pl.col('b')=='M'),
        reverse=True
    )
)
```
```
shape: (3, 1)
┌────────┐
│ a      │
│ ---    │
│ str    │
╞════════╡
│ bob    │
├╌╌╌╌╌╌╌╌┤
│ george │
├╌╌╌╌╌╌╌╌┤
│ bill   │
└────────┘
```
I'm not sure if this is a bug, as `sort_by` needs to have a bit more info of how you want to use column `c` for sorting. Are you expecting that all of the operations performed on `a` should also be performed on `c` prior to the filter? Is that a typically reasonable explanation?

**Comment by rockpunk** [comment]
I'm of the opinion that segfaults and panics based on user input, even if the input seems unreasonable, are ALWAYS bugs.  At the very least, some defensive programming and an error message allows programs to gracefully recover.

That said, I agree that what I am asking polars to do in this case is difficult and can better be tackled on the dataframe level.  This came about because I was testing the boundaries of what polars could reasonably do in parallel when asking polars to select different columns based on different orderings and filters in one select, rather than doing multiple selects. Apparently, we shouldn't do that =) 

Thinking more holistically about expression operations, however, currently Pola.rs supports the following:

   - [sorting an expression](https://docs.rs/polars/latest/polars/prelude/enum.Expr.html#method.sort_by) based on another expression
   - [filtering an expression](https://docs.rs/polars/latest/polars/prelude/enum.Expr.html#method.filter) based on another expression

Since both of these return an expression, it would seem perfectly reasonable from an API standpoint for someone (particularly someone new) to compose the two in different ways. This is obviously not intended and results in the rust application aborting.  Here's the same thing in straight rust which reproduces the SIGABRT failure

```rust
fn example() -> Result<DataFrame, PolarsError> {
    let df = df!("a" => &["Jim","Bill","Annie","Jen","George"],
                 "b" => &["M", "M", "F", "F", "M"],
                 "c" => &[32,40,59,19,24]);

   df.unwrap()
        .lazy()
        .select(&[
            col("a")
                .filter(col("b").eq(lit("M")))
                .sort_by(vec![col("c")], vec![true]),
        ])
        .collect()}

fn main() {
    println!("{:?}", example())
}
```

**Comment by ritchie46** [comment]
This is indeed a bug. I will look into it.

**Comment by rockpunk** [comment]
Thanks @ritchie46 .  BTW, not sure if you **want** to support composed filtered expressions like this, but I was thinking that if the result of `pl.col("a").filter(...)` is technically different from a normal `Expr`, it might make sense to model this as a `FilteredExpr` or something.  

That way it would be clear that composed expressions would not work unless there's a reasonable `FilteredExpr::filter` or `FilteredExpr::sort_by` method implemented.  If you don't implement one, it won't compile in rust and python would get a no such method error to avoid cases like this (or `df.select(col("a").filter(...).filter(...))`, etc).  Conversely, if you _do_ implement one, you could handle column ordering scopes / filtered lengths in an immutable way and not impact the overall dataframe column.

Just a thought.
