### ISSUE TITLE
Add _ipython_key_completions_ method to DataFrame

### ISSUE THREAD

**Issue by machow** [pola-rs/polars#5468]
### Problem description

Currently, IPython uses [special logic](https://github.com/ipython/ipython/blob/dc08a337f568ce179a88b83fdcf6ebb4158dfdb5/IPython/core/completer.py#L2133) to generate autocomplete suggestions for `pandas.DataFrame.__getitem__`.

Essentially, it just lists out the columns (along with other stuff):

```python
import pandas as pd

df = pd.DataFrame({"aaabbb": [1,2]})
df["a<tab>
```

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2574498/201198338-796f2854-5fe7-491a-8ec4-487ff6d0a432.png">

If polars added a [`_ipython_key_completions_`](https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion) method that returned a list of column names, it would be able to get similar completions..!

**Comment by alexander-beedie** [comment]
Interesting - thanks for the suggestion; looks like that could be a cheap win ;)
