### ISSUE TITLE
pl.col(...).is_between is missing typing for date

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5489]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`df.filter(pl.col("dates").is_between(first_date, last_date))` shows a typing error for `date` types:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2721423/201485186-ce2efe65-a69a-4e24-b646-26c083386942.png">

The code does run, however, so I think all that is missing is a type annotation, and perhaps a similar `pl.lit` code like already is for datetime. Not certain why that is necessary though?

### Reproducible example

```python
import polars as pl
from datetime import date
first_date = date(2020, 1, 1)
last_date = date(2020, 1, 5)

df = pl.date_range(first_date, last_date, interval="1d", name="dates").to_frame()

df.filter(pl.col("dates").is_between(first_date, last_date))
```

### Expected behavior

No error :)

### Installed versions

<details>

```
---Version info---
Polars: 0.14.27
Index type: UInt32
Platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.28
Python: 3.10.8 (main, Oct 13 2022, 23:54:57) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by zundertj** [comment]
Fixed by #5491 (+ some additional fixes).
