### ISSUE TITLE
Number of lines in `read_csv_batched` doesn't match `batch_size`

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5505]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When setting `batch_size` on `read_csv_batched` the batch size matches up with the size of each `DataFrame` for some datasets but the size of the `DataFrames` are very different from the batch size for others. 

In the example with the attached (small) CSV with `batch_size = 10` the `DataFrame` has 77 rows. If I set `batch_size` = 5 it has 41 rows

 
[private_housing_temp_units.csv](https://github.com/pola-rs/polars/files/10004122/private_housing_temp_units.csv)

### Reproducible example

```python
import polars as pl
reader = pl.read_csv_batched(
    "private_housing_temp_units.csv",
    batch_size=10)
reader.next_batches(1)[0]
```

### Expected behavior

I expect to get the same number of rows as the `batch_size`

### Installed versions

```
---Version info---
Polars: 0.14.28
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.4.1
numpy: 1.19.2
fsspec: 2021.10.1
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: 3.3.2
```

**Comment by ritchie46** [comment]
That's not a bug. It tries to adhere to batch size but it cannot guarantee them. It serves as a hint of the chunk size you'd like to have.

**Comment by ghuls** [comment]
Does batch_size try to get that many lines or is it the number of bytes it gets?

**Comment by ritchie46** [comment]
> Does batch_size try to get that many lines or is it the number of bytes it gets?

It tries to get that many lines. During the statistics gathering it estimates the amount of bytes per line. Then it tries to make chunks of `n_bytes_per_line * batch_size` and for those chunks it searches the line endings. 

It will collect a `Vec` of staring point and ending points per batch up front.

So I'd advice to choose a batch size that is reasonably large. If the batch size is very small, we will have to do a lot of work up front.
