### ISSUE TITLE
PyCharm docstring Example formatting issue (and proposed fix)

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#5513]
Problem
---

Not actually a polars bug, but rather a continual annoyance caused by a _PyCharm_ bug which leads (incorrectly) to three consecutive "-" chars being condensed to [emdash](https://en.wikipedia.org/wiki/Dash#Em_dash) "—", even in docstring code blocks. This leads to all docstring examples showing polars table output being awkwardly mis-formatted (ouch).

Impact
---
All PyCharm users looking at docstrings :)

I've raised this as a [bug report](https://youtrack.jetbrains.com/issue/PY-57395) with JetBrains and they're looking at it - but, even if fixed in the next release, older versions of PyCharm will still have the issue).

Example
---

<img width="350" src="https://user-images.githubusercontent.com/2613171/201901589-bc34f263-5249-4490-b87b-911fe9765737.png" />

Solution
---

So, as a proposed fix, how about changing the (utf8) dtype divider from "---" to "╌╌╌"? The standard row-divider character makes sense, and looks visually consistent. (Note that the dtype divider is _not_ added by comfy-table, it is something [we add ourselves](https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/fmt.rs#L389)). 

In use / comparison:

```python
# ┌─────┬─────┐      ┌─────┬─────┐
# │ abc ┆ xyz │      │ abc ┆ xyz │
# │ --- ┆ --- │      │ ╌╌╌ ┆ ╌╌╌ │   << suggested/updated dtype divider
# │ i32 ┆ str │      │ i32 ┆ str │
# ╞═════╪═════╡  vs  ╞═════╪═════╡
# │ 1   ┆ x1  │      │ 1   ┆ x1  │
# ├╌╌╌╌╌┼╌╌╌╌╌┤      ├╌╌╌╌╌┼╌╌╌╌╌┤   << (note: same char as row divider)
# │ 2   ┆ x2  │      │ 2   ┆ x2  │
# ├╌╌╌╌╌┼╌╌╌╌╌┤      ├╌╌╌╌╌┼╌╌╌╌╌┤
# │ 3   ┆ x3  │      │ 3   ┆ x3  │
# └─────┴─────┘      └─────┴─────┘
```

Implementation
---
It's a trivial change in `fmt.rs` (literally a 1-2 liner). Just need to ensure that it is _only_ applied to utf8 table output; no change for ascii formats.

The bigger headache is updating all of the docstrings - however, if this formatting update is thought to be reasonable, I would take care of all of this and submit a suitable PR...

**Comment by ritchie46** [comment]
Is it possible that we write/use some tooling that overwrite the docstring outputs? We already on a point that we are very hesitant to change anything here.

**Comment by stinodego** [comment]
PyCharm making our lives difficult again 😅

Personally, I think the Polars print style could be a lot better. I am not too fond of the current default. The 'condensed' format is already a lot better.

Regarding this specific issue: I don't really like the suggested divider. It looks uneven to me - the narrow characters close to the wider characters make me feel like something is wrong with my eyes. I feel really nitpicky saying this, but it just feels off.

I'm sure we can come up with a representation that doesn't break PyCharm but is a bit easier on the eyes?

**Comment by alexander-beedie** [comment]
> PyCharm making our lives difficult again 😅

Lol... I tried VSCode a few weeks back to investigate a different bug and I was hilariously, hopelessly lost - was like that scene at the beginning of 2001: A Space Odyssey where a monkey starts hitting things with a stick, except I didn't have the subsequent breakthrough 🤣 

> I feel really nitpicky saying this, but it just feels off.

I suspect using the row-divider char is actually a mistake; interestingly it doesn't look as bad in conjunction with the proposed "condensed" change, as then it stands alone:

```python
# ┌─────┬─────┐
# │ abc ┆ xyz │
# │ ╌╌╌ ┆ ╌╌╌ │
# │ i32 ┆ str │
# ╞═════╪═════╡
# │ 1   ┆ x1  │
# │ 2   ┆ x2  │
# │ 3   ┆ x3  │
# └─────┴─────┘╌
```
... though something less "grainy" is probably better... 
```python
# ┌─────┬─────┐
# │ abc ┆ xyz │
# │ ┈┈┈ ┆ ┈┈┈ │
# │ i32 ┆ str │
# ╞═════╪═════╡
# │ 1   ┆ x1  │
# │ 2   ┆ x2  │
# │ 3   ┆ x3  │
# └─────┴─────┘
```
...though rounded corners are clearly where it's at ;)
```python
# ╭─────┬─────╮
# │ abc ┆ xyz │
# │ ┈┈┈ ┆ ┈┈┈ │
# │ i32 ┆ str │
# ╞═════╪═════╡
# │ 1   ┆ x1  │
# │ 2   ┆ x2  │
# │ 3   ┆ x3  │
# ╰─────┴─────╯
```
If you're feeling artistic, have a look at the box-drawing chars [[here](https://en.wikipedia.org/wiki/Box-drawing_character)] and see if you can come-up with something? Then we could perhaps add to comfy-table and migrate later.

Let's update in two/three passes; move to `UTF8_FULL_CONDENSED` first (I'll do that now), which is easy and not especially controversial, and then consider other formatting updates (like this name/type divider) separately.

**Comment by stinodego** [comment]
I'll fiddle around with it a bit, will come back to this!

**Comment by alexander-beedie** [comment]
Just submitted a corresponding `ASCII_FULL_CONDENSED` [to comfy-table](https://github.com/Nukesor/comfy-table/pull/97); bit of an oversight on my part not doing that when I added `UTF8_FULL_CONDENSED`.

**Comment by stinodego** [comment]
What about simply the top left character? Just a solid line seems the simplest / most minimalist / easiest to look at.

```
╭─────┬─────╮
│ abc ┆ xyz │
│ ─── ┆ ─── │
│ i32 ┆ str │
╞═════╪═════╡
│ 1   ┆ x1  │
│ 2   ┆ x2  │
│ 3   ┆ x3  │
╰─────┴─────╯
```

**Comment by alexander-beedie** [comment]
> What about simply the top left character (─)? Just a solid line seems the simplest / most minimalist / easiest to look at. An 'em dash' (—) looks the same.

Sure, why not - simple and clean :)
(I can do another pass later with comfy-table and rounded corners, heh).

**Comment by stinodego** [comment]
Just commenting to point out this is still relevant in the latest version of PyCharm.

**Comment by alexander-beedie** [comment]
Yup. I live in hope that they will _eventually_ fix it, but it has been two years already 😞 I'll close this out only because I don't see us changing our table format at this point and we have enough open Issues as it is. All up to JetBrains now...
