### ISSUE TITLE
Standardise on ISO or non-ISO formats

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5524]
### Problem description

`pl.col("date_column").dt.week` refers to the ISO week -> `1-52`, while `pl.col("date_column").dt.weekday` is a non-ISO weekday 0-6 (ISO would be 1-7).

The question is whether to start counting on 0 or 1 in these cases.

Pandas solves this by providing both methods, isoweekday and weekday as methods, and a isocalendar, returning year, week and weekday in ISO format.

I'd rather it got standardised sooner rather than later :)

I'd also like to encourage the date format `%Y-%m-%d` as a default argument to the pl.Date in python-polars, but that's low priority compared to the above.

**Comment by braaannigan** [comment]
<I'd also like to encourage the date format %Y-%m-%d as a default argument to the pl.Date in python-polars, but that's low priority compared to the above>
+1 from me

**Comment by ritchie46** [comment]
So which one should we use do you think? ISO?

**Comment by thomasaarholt** [comment]
Absolutely! :)
