### ISSUE TITLE
Correlation matrix, similar to Pandas' corr()

### ISSUE THREAD

**Issue by StijnKas** [pola-rs/polars#5530]
### Problem description

One commonly used feature in pandas for me is the correlation matrix (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html) - but I've not been able to recreate this very well in Polars. 

I suppose to do pairwise correlation this technically works:
```python
import itertools
df.select([pl.pearson_corr(col1, col2).alias(f'corr_{col1}/{col2}') for col1, col2 in itertools.combinations(df.columns, r=2)]) 
```
But it does not produce a matrix, and I'm certainly not sure if this is the most efficient method. Is this something to consider in the future? Thanks!

**Comment by radugrosu** [comment]
you can get that trivially using numpy: `pl.DataFrame(np.corrcoef(df), columns=df.columns)`

**Comment by ritchie46** [comment]
> you can get that trivially using numpy: `pl.DataFrame(np.corrcoef(df), columns=df.columns)`

Nice one! I think I will add that as a utility method.
