### ISSUE TITLE
Expression namespace fails on pylint checker in newer versions

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#5536]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Here's an example of accessing an expr's namespace in `v0.14.26` failing with pylint:

### Reproducible example

```python
❯ cat hmm.py
import polars as pl
pl.col("x").dt.truncate("1d")
```

Ignore the C0114:
```
❯ /venv_with_0_14_26/bin/pylint hmm.py
************* Module hmm
hmm.py:1:0: C0114: Missing module docstring (missing-module-docstring)
hmm.py:2:0: E1101: Method 'dt' has no 'truncate' member (no-member)

-----------------------------------
Your code has been rated at 0.00/10
```

If we try to run pylint with `v0.14.21` it works fine:

```
❯ /venv_with_0_14_21/bin/pylint hmm.py
************* Module hmm
hmm.py:1:0: C0114: Missing module docstring (missing-module-docstring)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 5.00/10, +0.00)
```

### Expected behavior

Expected the `dt` accessor for example to not break on pylint.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.4.117
Python: 3.10.8 (main, Oct 17 2022, 08:09:04) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.1
numpy: 1.23.2
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2
```

pylint version:
```
pylint 2.15.2
astroid 2.12.9
Python 3.10.8 (main, Oct 17 2022, 08:09:04) [GCC 8.3.0]
```

</details>

**Comment by ritchie46** [comment]
I believe this was fixed by @alexander-beedie in version 0.14.27 or 0.14.28.

**Comment by alexander-beedie** [comment]
Yes, can confirm that good from `0.14.27` (double-checked with pylon too).
(The specific commit that fixed accessor autocomplete -and lint- was https://github.com/pola-rs/polars/pull/5469)

**Comment by OneRaynyDay** [comment]
Ah sorry about that! I swear 0.14.26 came out a couple days ago ;)
