### ISSUE TITLE
Arithmetic and Comparison Operators as Methods

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#5549]
### Problem description

I use the filter function a lot and I would like to be able to replace many of the brackets for the operators (+, -, %, //, <, >, !=, ==, ...) with methods like in pandas. here is an example:

```python
import polars as pl

df = pl.DataFrame({
    "age": [20, 45, 33, 21, 55],
    "height": [1.80, 1.90, 1.70, 1.65, 1.80],
    "weight": [80, 90, 70, 65, 80],

})

# polars
(
    df
    .filter(
        ((pl.col("age") % 10) != 0) &
        (pl.col("height") > 1.75) &
        (
            ((pl.col("weight") + 10) > 80) |
            (pl.col("weight") < 70)
        )
    )
)

# pandas
(
    df[
        df["age"].mod(10).ne(0) &
        df["height"].gt(1.75) &
        (
            df["weight"].add(10).gt(80) |
            df["weight"].lt(70)
        )
    ]
)
```

In my opinion this is easier to read when you have multiple conditions which is often the case.

**Comment by zundertj** [comment]
This is the same request as #4224, please upvote and/or comment on that issue. Closing this to keep the discussion in a single place.
