### ISSUE TITLE
Glimpse wide dataframes

### ISSUE THREAD

**Issue by robertdj** [pola-rs/polars#5550]
### Problem description

Hi

I am long time R user trying out Polars and really enjoying it!

For wide dataframes (with too many columns to fit in a terminal) I like the `glimpse` function in R's tibble package that gives a "transposed head" of **all** columns:
![Screenshot from 2022-11-19 09-54-30](https://user-images.githubusercontent.com/5703657/202843224-448c60f6-8232-400b-b9c5-73d720b5bac9.png)

As trivial as it may sound, I use this feature *a lot* when inspecting data.
Could a similar functionality be considered in Polars?

**Comment by zundertj** [comment]
To be sure, one can currently do `df.head().transpose(True)` to have similar output. Is the request for a separate method, or for a more condensed output, as `head().transpose()` uses the default cell-based layout?

**Comment by robertdj** [comment]
I had missed the `transpose` method 😳

Perhaps I have overlooked a way to print more columns, but by default some columns are suppressed/replaced with `...` when printing wide dataframes. Adding a `transpose` does not expand the `...`.
(I can attach a screenshot to elaborate if you want -- I just need different computer.)

**Comment by ghuls** [comment]
You can increase the number of columns that are printed: `pl.Config.set_tbl_cols(50)`

**Comment by zundertj** [comment]
I guess that still doesnt give you the dense output. You could write a small utility (sorry, here I added it as a method, but should be easy to turn into stand-alone function):


```python
    def glimpse(self: DF) -> None:
        print(f"Rows: {self.height}")
        print(f"Columns: {self.width}")

        max_col_length_name = max(map(len, self.columns))
        for s in self.columns:
            val = self[:min(10, self.height),:][s].to_list()
            print(f"$ {s: <{max_col_length_name}} {self[s].dtype.__name__: >10}: {', '.join(map(str, val))}")
```

```
>>> import polars as pl
>>> df = pl.DataFrame({"a": [True, False, True, False],
... "flt": [1.2, 5.6, 10, 9]})
>>> df.glimpse()
Rows: 4
Columns: 2
$ a      Boolean: True, False, True, False
$ flt    Float64: 1.2, 5.6, 10.0, 9.0
```

**Comment by ritchie46** [comment]
@zundertj would you like to add this method to the `DataFrame` class?

**Comment by zundertj** [comment]
@ritchie46 : see https://github.com/pola-rs/polars/pull/5622

**Comment by vankesteren** [comment]
Just want to say I really appreciate this feature 💪

**Comment by nick-ulle** [comment]
In R, the leading `$` on each line is meant to be suggestive of how to access each column (e.g., `iris$Species` to get the `Species` column in R). Since Polars doesn't use `$` for column access, it seems like visual noise here.

**Comment by zundertj** [comment]
Probably better to open a new issue/PR with a proposal.

I wouldn't be in favor of just starting out with the column name though, as we also have the labels "Rows" and "Columns" before, it would need to differentiate that those are not column names.
