### ISSUE TITLE
dt.truncate does not work correctly for weeks

### ISSUE THREAD

**Issue by mjkanji** [pola-rs/polars#5557]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The `dt.truncate` function is incorrectly pegging the start of the week to Thursday, instead of Monday. This may be related #5507 but that's focused on timezone issues, whereas here I have a standard date.

### Reproducible example

```python
import polars as pl
from datetime import date, timedelta

start = date(2022,11, 14)
end = date(2022,11, 20)
print(
    pl.date_range(start, end, timedelta(days=1), name="dates")
    .to_frame()
    .select([
        pl.col("dates"),
        pl.col("dates").dt.strftime("%A").alias("day_of_week"),
        pl.col("dates").dt.truncate("1w").alias("truncated"),
        pl.col("dates").dt.week().alias("week")
    ])
)

shape: (7, 4)
┌────────────┬─────────────┬────────────┬──────┐
│ dates      ┆ day_of_week ┆ truncated  ┆ week │
│ ---        ┆ ---         ┆ ---        ┆ ---  │
│ date       ┆ str         ┆ date       ┆ u32  │
╞════════════╪═════════════╪════════════╪══════╡
│ 2022-11-14 ┆ Monday      ┆ 2022-11-10 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-15 ┆ Tuesday     ┆ 2022-11-10 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-16 ┆ Wednesday   ┆ 2022-11-10 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-17 ┆ Thursday    ┆ 2022-11-17 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-18 ┆ Friday      ┆ 2022-11-17 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-19 ┆ Saturday    ┆ 2022-11-17 ┆ 46   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2022-11-20 ┆ Sunday      ┆ 2022-11-17 ┆ 46   │
└────────────┴─────────────┴────────────┴──────┘
```

### Expected behavior

Expected behaviour is for truncating by a week to peg the start of the week to Monday (i.e., all the days with the same value for the `week` column above should have the same truncated value). In the example above, the week starts on the 14th and ends on the 20th, so the whole `truncated` column should have only one unique value.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.29
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by cannero** [comment]
As I see it, `truncate` is just not implemented for calendar weeks. Of the different parameter strings for `every`, only month and year respect the calendar. All the other parameters just subtract the mod of timestamp by the duration. (This is also the reason why they cannot be mixed)
And as the 1.1.1970 was a Thursday, truncating by one week will give a Thursday.
I'm just not sure if anybody needs to truncate by 7 days or it should always be calendar weeks.

**Comment by mjkanji** [comment]
> I'm just not sure if anybody needs to truncate by 7 days or it should always be calendar weeks.

I think that if someone wants to just subtract 7 days, then they can do `pl.col('dates') - timedelta(days=7)`. Though, in this case, we're not even subtracting a week -- we're just arbitrarily going to the last Thursday, because 1970-01-01 happened to be a Thursday. I don't think this is intuitive behaviour.

Moreover, truncate/date_trunc in traditional RDBMs also respects calendar weeks. For example, if I run the following in Redshift/Postgres

```
select date_trunc('week', DATE '2022-11-17')
```

I'll get `2022-11-14 00:00:00`, which is Monday.

Similarly, in Pandas, I can get the right answer as follows (though, Pandas is a bit verbose in how it shows the week):

```
import pandas as pd
pd.Series(pd.date_range("2022-11-14", "2022-11-22")).dt.to_period("W")

#Returns
PeriodIndex(['2022-11-14/2022-11-20', '2022-11-14/2022-11-20',
             '2022-11-14/2022-11-20', '2022-11-14/2022-11-20',
             '2022-11-14/2022-11-20', '2022-11-14/2022-11-20',
             '2022-11-14/2022-11-20', '2022-11-21/2022-11-27',
             '2022-11-21/2022-11-27'],
            dtype='period[W-SUN]')
```

**Comment by cannero** [comment]
I want take a look at this and create a draft pull request. Also, it looks like numbers other than `1` in the truncate string are not correctly handled.
