### ISSUE TITLE
Add `drop_keys` argument to `DataFrame.partition_by`

### ISSUE THREAD

**Issue by mjkanji** [pola-rs/polars#5560]
### Problem description

It would be great to have an option to drop the group keys when doing `DataFrame.partition_by`. From the partition_by example in the docs:

```
df = pl.DataFrame(
    {
        "foo": ["A", "A", "B", "B", "C"],
        "N": [1, 2, 2, 4, 2],
        "bar": ["k", "l", "m", "m", "l"],
    }
)
df.partition_by(groups="foo", maintain_order=True)
[shape: (2, 3)
 ┌─────┬─────┬─────┐
 │ foo ┆ N   ┆ bar │
 │ --- ┆ --- ┆ --- │
 │ str ┆ i64 ┆ str │
 ╞═════╪═════╪═════╡
 │ A   ┆ 1   ┆ k   │
 ├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
 │ A   ┆ 2   ┆ l   │
 └─────┴─────┴─────┘,
...]
```

This would mean the the `foo` column is dropped from the output data frames.

**Comment by zundertj** [comment]
Hello, thank you for your request.

Could you explain why it would be great, is there a usability concern, is it about memory usage?

For further discussion: in `groupby` we also maintain the `by` column(s), it makes sense to me have `partition_by` and `groupby` behave the same in this respect.

**Comment by mjkanji** [comment]
> Hello, thank you for your request.
> 
> Could you explain why it would be great, is there a usability concern, is it about memory usage, something else? The way I see it, it doesnt do any harm to have it?
> 
> For further discussion: in `groupby` we also maintain the `by` column(s), it makes sense to me have `partition_by` and `groupby` behave the same in this respect.

Hi there! There's definitely no harm in having it. It's more of a convenience.

I suppose it depends on why someone is partitioning the data frame, but in my case, I want to partition so I can write different rows to different files and that's the only utility the grouping column has. I'm sure there are other use cases where the grouping column loses its utility after it's been used to partition.

I was thinking along the lines of how Arrow handles writing partitioned datasets:
```
import pyarrow as pa
import pyarrow.dataset as ds
import polars as pl

table = pa.table({"a": range(10), "b": np.random.randn(10), "c": [1, 2] * 5})
part = ds.partitioning(
    pa.schema([("c", pa.int16())]), flavor="hive"
)

ds.write_dataset(table, "partitioned_dataset", format="parquet", partitioning=part)

pl.read_parquet("partitioned_dataset/c=1/part-0.parquet")
```

If you look at the output, the `c` column has been removed.

**Comment by zundertj** [comment]
The column `c` is in the directory structure, and on reading, you will get it back (when you include it in the `columns` arg). See the note at https://arrow.apache.org/docs/python/parquet.html#reading-from-partitioned-datasets.  So it is not really dropped?

**Comment by mjkanji** [comment]
> The column `c` is in the directory structure, and on reading, you will get it back (when you include it in the `columns` arg). See the note at https://arrow.apache.org/docs/python/parquet.html#reading-from-partitioned-datasets. So it is not really dropped?

Yes, you can get it back (I believe you can also choose not to), but that's not really what I was focused on. The Arrow example was just an example.

The core of the request is this: 
> I'm sure there are other use cases where the grouping column loses its utility after it's been used to partition (and so having the option to drop it would be nice).

Maybe it's too trivial of a request to implement. One can always just do

```
dfs = df.partition_by("key")
map(lambda x: x.drop("key"), dfs)
```

**Comment by zundertj** [comment]
There are definitely cases where the utility is lost, I fully agree. However, I think the criteria for a new feature/parameter should be  higher, namely that it enables something or makes Polars much easier to use than without the feature. And that is the bit that is missing in this request in my opinion. Just because utility is lost in some (but not all!) scenarios, what does a user lose by having the column around?

**Comment by stinodego** [comment]
`DataFrame.partition_by` now has an `include_key` argument:
https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.partition_by.html#polars.DataFrame.partition_by
