### ISSUE TITLE
Execute 

### ISSUE THREAD

**Issue by cjstudioz** [pola-rs/polars#5561]
### Problem description

my understanding is we currently need to split selecting new aliased cols in a separate select to hint to query optimizer which cols can be evaluated in parallel. e.g.:

```
df.select([
        pl.col("names").unique().count().alias("count_unique"),
]).select([
        pl.col("count_unique").sum(),alias("sum_unique").
]) 
```

would it be possible to pass an entire list of dependent selects and "pre-compile" a graph e.g. using rustworkx and pass every "ready" node into a queue for parallel evaluation?

**Comment by ghuls** [comment]
You can chain multiple expressions:
```python
df.select([
        pl.col("names").unique().count().sum(),alias("sum_unique").
])
```

**Comment by MarcoGorelli** [comment]
I think @ghuls 's comment addresses the issue, so closing, but thanks for the report!
