### ISSUE TITLE
Top suggestion during google searches for polars docs lead to a 404

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#5566]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

[https://www.google.com/search?q=polars+with_column](https://www.google.com/search?q=polars+with_column) -> First suggestion -> [404 error](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.LazyFrame.with_column.html).
![image](https://user-images.githubusercontent.com/2721423/202997153-0c018bb0-9c74-406f-92ff-53fea584abae.png)

It would be very good to fix this, as its a bit of a pain in the ass that one can't just do a google search. It's been this way for several weeks-.

**Comment by thomasaarholt** [comment]
Had to tag Python since there was no way to raise a general bug

**Comment by ritchie46** [comment]
Hmm.. Any idea how?

**Comment by ghuls** [comment]
Probably we need a robots.txt file to tell search engines to reindex the pages e.g. every 3  days. The cached page is from 3 November.

**Comment by ghuls** [comment]
You can also ask for a recrawl. Creating a sitemap might be useful too: https://developers.google.com/search/docs/crawling-indexing/ask-google-to-recrawl

**Comment by universalmind303** [comment]
related to #3716

**Comment by ritchie46** [comment]
I think the pages are crawled by the powers of latency.
