### ISSUE TITLE
Python-polars release 0.14.29 seems to use py-0.14.28 git tag.

### ISSUE THREAD

**Issue by gyscos** [pola-rs/polars#5578]
Note: this ticket is about the _releases_ of python polars, not about the library itself.

### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This release (with 0.14.29 as title) actually uses the 0.14.28 tag:

https://github.com/pola-rs/polars/releases/tag/py-0.14.28

### Reproducible example

```python
* Observe existence of version 0.14.29 in https://pypi.org/project/polars/#history
* Observe absence of `py-0.14.29` tag in https://github.com/pola-rs/polars.
  * Instead, the 0.14.29 release appears to be written on the `py-0.14.28` tag.
```

### Expected behavior

I would expect there to be a `py-*` tag for each version released on pypi.

### Installed versions

0.14.28

**Comment by stinodego** [comment]
Thank you for reporting this. I just fixed it!

**Comment by stinodego** [comment]
@ritchie46 FYI

**Comment by ritchie46** [comment]
Yup, thanks for the fix @stinodego. I messed up.
