### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [pola-rs/polars#5593]
Hi, thanks for this great library! Just wanted to let you know there’s now a [Ruby version](https://github.com/ankane/polars-ruby) of it 🎉 

The Python code was really easy to follow. It currently supports [many examples](https://github.com/ankane/polars-ruby/blob/master/test/guide_test.rb) from the user guide, and I’m working to add the rest of the methods and options (and planning to precompile it on different platforms for fast installation).

Thanks again for creating this!

**Comment by ritchie46** [comment]
Awesome, polars is becoming quite a polyglot! :)

**Comment by ritchie46** [comment]
Hi @ankane. Would you be interested in moving your work in a repository under the official polars namespace? 

That way we hopefully can get more community involvement in and hopefully a long lasting project.

Currently we are doing the same with nodejs-polars and r-polars. I think an official ruby-polars would be nice as well.

**Comment by ankane** [comment]
Hi @ritchie46, I'd like to keep things as-is for now, but will keep that in mind. Most of the API is now implemented, and anyone is welcome to contribute.
