### ISSUE TITLE
Series name is empty in apply

### ISSUE THREAD

**Issue by selvavm** [pola-rs/polars#5608]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Not able to get the column name in the lambda function when using apply

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6, 7, 8],
        "ham": ["a", "b", "c"],
    }
)
df.groupby('foo').agg(
    [
        pl.col('*').apply(lambda s: print(s))
    ]
)
```

### Expected behavior

Expected to print bar and ham as name but got an empty string

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by selvavm** [comment]
Thanks @ritchie46 for the response. Yes, I can explain. 

I am trying to do a complex function which takes 2 arguments - the series and a metadata of the series stored in dictionary.

for example,
```python

def myfun(s, country_code):
    if country_code == 'us':
        # Do something
    elif  country_code == 'uk':
        # Do something else
   .........

mapper = {'usa':'us', 'unitedkingdom':'uk',.....}

df.groupby('year').agg(
    [
        pl.col('*').apply(lambda s: myfun(s, country_code = mapper[s.name]))
    ]
)
```

Since I don't know the column name in lambda, I am not able to retreive necessary data from the mapper

**Comment by selvavm** [comment]
Hi @ritchie46 - Could you support on this?

**Comment by cmdlineluser** [comment]
@selvavm - It looks like from your example - your dataframe is like so?

```
>>> import polars as pl
...
... df = pl.DataFrame(
...     {
...         "year": ["2011", "2010", "2011"],
...         "usa": [1, 2, 3],
...         "unitedkingdom": [6, 7, 8]
...     }
... )
...
... mapper = {'usa':'us', 'unitedkingdom':'uk'}
```
Could you reshape and  add the metadata as a column?

```
>>> (
...    df
...    .melt("year", variable_name="country")
...    .with_column(
...       pl.col("country").apply(mapper.get)
...         .alias("country_code"))
... )
shape: (6, 4)
┌──────┬───────────────┬───────┬──────────────┐
│ year | country       | value | country_code │
│ ---  | ---           | ---   | ---          │
│ str  | str           | i64   | str          │
╞══════╪═══════════════╪═══════╪══════════════╡
│ 2011 | usa           | 1     | us           │
├──────┼───────────────┼───────┼──────────────┤
│ 2010 | usa           | 2     | us           │
├──────┼───────────────┼───────┼──────────────┤
│ 2011 | usa           | 3     | us           │
├──────┼───────────────┼───────┼──────────────┤
│ 2011 | unitedkingdom | 6     | uk           │
├──────┼───────────────┼───────┼──────────────┤
│ 2010 | unitedkingdom | 7     | uk           │
├──────┼───────────────┼───────┼──────────────┤
│ 2011 | unitedkingdom | 8     | uk           │
└─//───┴─//────────────┴─//────┴─//───────────┘
```

You could then `.groupby(["year", "country"])` - or depending on what exactly `myfun` is doing - there may be a better approach.

**Comment by selvavm** [comment]
Thanks @cmdlineluser and sorry for delayed response. I had to try this which took some time. 

Although this work, I can see this is x3 times slower. I think this is because of an additional groupby

**Comment by cmdlineluser** [comment]
The `.apply(mapper.get)` appears to be rather slow.

Creating an actual dataframe and using ` .join()` would make more sense.

    >>> codes = pl.DataFrame(dict(country_code=list(mapper.values()), country=list(mapper.keys())))
    >>> df.join(codes, on="country")
