### ISSUE TITLE
`build_info` feature causes caching problems during Python Polars development

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#5612]
Following up on the discussion in #5472

Currently, ANY change in the `py-polars` folder will make `cargo build` have to re-build the `py-polars` package. So even if I update the `py-polars/.gitignore` file, the package needs to be rebuilt.

This is a problem because it interferes with quick prototyping / testing of changes.

After looking into this, it seems that this issue is caused by the `build_info` feature that was added recently. If I remove this feature from the repo, everything works normally. This code was introduced in #5423

I don't know what the intended purpose of this feature is, but we should either get rid of it, or implement in a way not to cause these caching issues.

@slonik-az You introduced the feature, do you have an idea how to address this issue?
@ritchie46 FYI. Let me know which way you want to go here.

**Comment by ritchie46** [comment]
Good observation. I think we can easily have both. We can make the `build_info` an optional feature which we only activate during a release in CI.

The only minor downside is that we cannot test the `build_info` functionality, but I think that is worth it.

**Comment by slonik-az** [comment]
`build_info` is behind the rust feature gate. For now, disable the feature in development and only enable it in production build. In meanwhile, I will look into finding a permanent solution.

**Comment by slonik-az** [comment]
> @ritchie46: The only minor downside is that we cannot test the build_info functionality, but I think that is worth it.

I think we are back to discussing of how to test production builds after this functionality has been removed from the Makefile. Any ideas?

**Comment by stinodego** [comment]
> > @ritchie46: The only minor downside is that we cannot test the build_info functionality, but I think that is worth it.
> 
> I think we are back to discussing how to test production builds after this functionality has been recently removed from the Makefile. Any ideas?

Anything that we build into a Makefile can also just be a bash script. I suggest you set up a bash script that fits your deployment criteria and run it as part of your deployment pipeline.

If that is somehow not sufficient, please help me understand why so that we can find a solution.

**Comment by slonik-az** [comment]
@stinodego:  For now, I am maintaining my own  out-of-tree `deploy.mk` makefile (it is better than a shell script) to build, test, install deployment targets. My question is whether polars will ever provide any official mechanism for building/testing deployment targets (e.g. wheels)? Currently the only installation option is from pypi which is a non-starter in many deployments.

For example, such  mechanism can be a separate makefile like mine but maintained in the official tree for everyone to use.

**Comment by stinodego** [comment]
I think there are currently no plans for this. PyPI is there for the run-of-the-mill precompiled wheels. Users with more advanced needs can set up their own custom workflow where they clone the repo, compile it using some of the commands mentioned in the README, and do whatever they need for their deployment.

Definitely not saying we will never have more advanced deployment pipeline support, but I don't think it's on any of our to do lists right now.

**Comment by ritchie46** [comment]
>  Currently the only installation option is from pypi which is a non-starter in many deployments.

Note that there also is a conda-forge feedstock.

**Comment by slonik-az** [comment]
We need to build ourselves from source. Therefore neither pypi nor conda-forge would do.

**Comment by slonik-az** [comment]
> @stinodego: If you feel this is an important addition to the Polars space then it might be a good idea to start a separate repository for it. We could link to it in our README. If it picks up speed we can integrate it into the Polars organization at some point.

This seems to be a reasonable path forward. Need to think more about maintaining a fork.
