### ISSUE TITLE
Selecting columns by type (dtype) fails for filter

### ISSUE THREAD

**Issue by datenzauberai** [pola-rs/polars#5625]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It seems to me that selecting columns to be used in a filter by dtype is not possible right now and panics with

```PanicException: no `dtype-columns` expected at this point.```

I think it should work.

### Reproducible example

```python
import polars as pl
import numpy as np

DTYPES_FLOAT = [pl.Float32, pl.Float64]

df = pl.DataFrame({
    "id": [1,2],
    "value1": [2.0, 3.0],
    "value2": [4.0, np.nan]
})

float_columns = [col for col, dtype in zip(df.columns, df.dtypes) if dtype in DTYPES_FLOAT]
filter_colnames_ok = df.filter(pl.col(float_columns).is_not_nan())
select_dtypes_ok = df.select(pl.col(DTYPES_FLOAT))
filter_dtypes_fails = df.filter(pl.col(DTYPES_FLOAT).is_not_nan())
```

### Expected behavior

Filter should work like when filtering by column name or selecting by dtype.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.31
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Not really. How should the boolean expression be combined? OR, AND, XOR? That is not something we should decide for the programmer.

**Comment by datenzauberai** [comment]
I would say the same way as it works with column names! Isn’t the type just another way of referring to columns instead of the name?

**Comment by zundertj** [comment]
@ritchie46 : I would expect this to work:

```python
df.filter(pl.all(pl.col(DTYPES_FLOAT).is_not_nan()))
```
but it doesn't:
```
pyo3_runtime.PanicException: no `dtype-columns` expected at this point
```
I think that is unexpected, no? Because the `all` is the `AND` that you are referring to.

Creating a list works:
```
df.filter(pl.all([pl.col("value1").is_not_nan(), pl.col("value2").is_not_nan()]))
```

**Comment by datenzauberai** [comment]
This is now consistently failing with column names as well and works when wrapping with `pl.all`:

```python
select_dtypes_ok = df.select(pl.col(DTYPES_FLOAT))
#filter_colnames_fails = df.filter(pl.col(float_columns).is_not_nan())
filter_colnames_all_ok = df.filter(pl.all(pl.col(float_columns).is_not_nan()))
#filter_dtypes_fails = df.filter(pl.col(DTYPES_FLOAT).is_not_nan())
filter_dtypes_all_ok = df.filter(pl.all(pl.col(DTYPES_FLOAT).is_not_nan()))
```
