### ISSUE TITLE
Clarify situations where `streaming` is appropriate

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#5631]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm trying to perform some transformations with the new `streaming` functionality. My machine doesn't have enough RAM to perform the computations without it. I tried using `streaming` to solve this problem, but it didn't work.

Here is what I'm doing: 

1. `scan_parquet` 
2. perform `rolling_groupby`s with different `period` values
3. Aggregate a lot of columns (like 150) by summing
4. Concatenate all the resulting LazyFrames
5. Writing the result to disk with `df.collect(streaming=True).write_parquet()`

I'm running this in Jupyter Lab.

### Reproducible example

```python
import polars as pl

df = pl.scan_parquet("df.parquet").sort(["timestamp", "id"])

# column name to agg
names = ...

periods = [1, 3, 7, 30, 90, 180]

aggs = []
for days in periods:
    agg = df.groupby_rolling(
        "timestamp",
        period=f"{days}d",
        by=["id"]
    ).agg(
        [pl.col(name).sum().alias(f"w{days}_{name}") for name in names]
    ).sort(["timestamp", "id"]).drop(["timestamp", "id"])
    aggs.append(agg)

pl.concat(
    [df.select(["timestamp", "talent_id"])] + aggs
).collect(streaming=True).write_parquet("features.parquet")
```

In fact, even just the very last (the largest) `rolling_groupby` with a single column OOMs. 

It's unclear ti me if `streaming` can solve this problem. 

In what cases is this useful? Maybe this should be added to the documentation? 

### Expected behavior

The code (maybe) should not OOM. There has to be an explanation for appropriate streaming usage.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.0
Index type: UInt32
Platform: Linux-6.0.7-arch1-1-x86_64-with-glibc2.36
Python: 3.10.8 (main, Oct 14 2022, 17:54:34) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Hi @danielgafni, You can use `show_graph` to inspect the query plan. This will show the parts of the query that will be executed streaming.

This is something that is subject to change, so we cannot add it to the documentation as it just depends on the optimizations, and you'll have to check it programmatically.

tip: install graphviz as that renders nice looking dot diagrams.

**Comment by ritchie46** [comment]
I will close this as I feel this has been answered.
