### ISSUE TITLE
Regression with aggregates on string columns: The Series have different lengths

### ISSUE THREAD

**Issue by dgilman** [pola-rs/polars#5634]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Window functions on string columns are crashing in polars 0.14.31+ and were fine in 0.14.30 and before.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    data=[
        [1, 1995, 'bob'],
        [1, 1996, 'bob'],
    ],
    columns=["person_id", "year", "person_name"]
)

df.groupby("person_id").agg([pl.col("person_name").last()])
```

### Expected behavior

This blows up with a

```
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths.Got [shape: (1,)
Series: 'person_id' [i64]
[
	1
], shape: (0,)
Series: 'person_name' [str]
[
]]
```

Minor nit but there should probably be a space before "Got"

### Installed versions

<details>

```
---Version info---
Polars: 0.15.0
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.9.15 (main, Oct 12 2022, 03:01:28)
[Clang 11.0.3 (clang-1103.0.32.62)]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks. I will issue a patch release shortly.
