### ISSUE TITLE
read_csv with a file object tricks the developer by using the .name attribute

### ISSUE THREAD

**Issue by Crazytieguy** [pola-rs/polars#5648]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When passing a file-like object to read_csv, I expect that it will use the `read` method to get data. It turns out that if the object I pass has a `name` property, polars will assume that the name is a valid file path that points to a file with the same data.

This assumption is sometimes incorrect - in my case I was trying to read csvs from a .tar.gz archive one by one, using [tarfile](https://docs.python.org/3/library/tarfile.html). But the object returned from [extractfile](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractfile) has a name property that points to the original .tar.gz archive, causing polars to read it as if it were a csv.gz file.

I had to trick polars back by creating an object with just the read and seek methods from the original file - and this worked wonderfully and gave me all the performance I needed.

### Reproducible example

```python
import tarfile

import polars as pl

with tarfile.open("somearchive.tar.gz") as tf:
    df = pl.read_csv(tf.extractfile(tf.next()))
```

### Expected behavior

use the .read and .seek methods, as the API docs mention.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.29
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.0 (default, Nov 23 2021, 23:55:26) [GCC 9.3.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by Crazytieguy** [comment]
Will implement a fix shortly

**Comment by ritchie46** [comment]
Polars will try to get the original file name so that we can memory map the file. If we cannot, we first read the whole file in memory which has a large memory overhead.

I think we must investigate a more through/additional check to get the file name.

**Comment by Crazytieguy** [comment]
Thanks for the response, I already feel a bit better (in case you couldn't tell, I got really mad about this).

I think that no one has a reason to pass a file-like object if they could have passed a file name or Path. And if they did - it's their problem. Doing this sneaky stuff is bad api design - it tricks the user.

If a certain way of using the api has performance implications - then they should be documented properly so the developers know to avoid them.

**Comment by Crazytieguy** [comment]
I just realized - this same behavior is what stopped me from passing sys.stdin to read_csv - sys.stdin.name is '<stdin>'.

**Comment by ritchie46** [comment]
> Thanks for the response, I already feel a bit better (in case you couldn't tell, I got really mad about this).

Don't get mad, it's free software ;)

**Comment by ritchie46** [comment]
> I think that no one has a reason to pass a file-like object if they could have passed a file name or Path. And if they did - it's their problem. Doing this sneaky stuff is bad api design - it tricks the user.

We trick the user a lot. Do you really think we run the query in the order you specify? ;) 

All jokes aside, I think you are right and we must be conservative here. But it still would be great if we can determine if the user did an"

```python
with open("file.file") as f:
   pl.read_csv(f)
```

and recognize they are sending file handles.

**Comment by Crazytieguy** [comment]
oh I know - maybe if you see a .name property you can issue a warning, saying "hey, it's better if you just give us the file name" - but then use the .read method anyway
