### ISSUE TITLE
jemalloc panic on linux arm64 when page size is 64K

### ISSUE THREAD

**Issue by chuchiy** [pola-rs/polars#5654]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

when improt polars on centos 8 aarch64, jmalloc panic due to system page size of centos 8 aarch is 64k but look like the python wheel is build with 4k page size.

Maybe we need define JEMALLOC_SYS_WITH_LG_PAGE  or --with-lg-page to 16 for 64k page size support. Just as https://github.com/apache/arrow/pull/10940

### Reproducible example

```python
$ getconf PAGE_SIZE
65536

>>> import polars
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 2048 bytes failed
```

### Expected behavior

should not panic

### Installed versions

Python Polars 0.15.1

**Comment by ghuls** [comment]
@chuchiy Can you check if it is fixed in the latest (0.15.2) release?

**Comment by chuchiy** [comment]
Thanks for the fast release. But I just test the 0.15.2 release.  But polars 0.15.2 still core dump at 64k page size kernel, which works at my 4k page size arm vm. Maybe the env config in github actions did not take effect.

If I build polars wheel using maturin from source at 64k page size kernel machine, it works as expected.

The sha256 checksum of local polars.abi3.so is 2c14a1e4707f414cb5e750b64ecfd506792948c64d803b713e04cb940ed1aee8

$ getconf PAGE_SIZE
65536
$ poetry run python3
Python 3.9.15 (main, Dec 5 2022, 09:55:16)
Type "help", "copyright", "credits" or "license" for more information.
>>>  import polars
: Unsupported system page size
: Unsupported system page size
memory allocation of 2048 bytes failed
Aborted (core dumped)

**Comment by uuip** [comment]
as https://github.com/pola-rs/polars/issues/15549 point out:
> Looks like `JEMALLOC_SYS_WITH_LG_PAGE=16` isn't working:
> 
> https://github.com/pola-rs/polars/blob/42d36970f71044264832c404e303fcada9323807/.github/workflows/release-python.yml#L166-L180
> , need to pass it to `maturin-action` because of Docker, for working example, see
> 
>     * https://github.com/astral-sh/ruff/blob/42d52ebbec275389ee0458a3bf373268278bd51a/.github/workflows/release.yaml#L243-L247
> 
>     * https://github.com/astral-sh/ruff/blob/42d52ebbec275389ee0458a3bf373268278bd51a/.github/workflows/release.yaml#L275
