### ISSUE TITLE
Max-aggregation of boolean column gets converted to `u32` after `collect()`

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#5667]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Max-aggregation of boolean column gets converted to `u32` after `collect()`

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "x": [1,1,1],
    "y": [False, True, False],
}).lazy()

print(df.schema)
# {'x': polars.datatypes.Int64, 'y': polars.datatypes.Boolean}

agg_df = df.groupby("x").agg(pl.col("y").max().alias("max_y"))
agg_df.schema
# {'x': polars.datatypes.Int64, 'max_y': polars.datatypes.Boolean}

agg_df.collect().schema
# {'x': polars.datatypes.Int64, 'max_y': polars.datatypes.UInt32}
```

### Expected behavior

The output type after calling `collect()` should always equal the schema of the lazy frame.
`agg_df.collect().schema["max_y"] == agg_df.schema["max_y"]` should be True!

### Installed versions

<details>

```
---Version info---
Polars: 0.15.1
Index type: UInt32
Platform: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.0
numpy: 1.23.2
fsspec: 2022.01.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.1

```

</details>

**Comment by ritchie46** [comment]
Right, we must update schema accordingly. Will fix it.

**Comment by Hoeze** [comment]
@ritchie46 Is the `max()` of a boolean dtype expected to be an integer?
If yes, why?

It might be desirable to create some unit test for this kind of bugs :)

**Comment by ritchie46** [comment]
Oh, sorry, nope it is not. I thought it was a sum.
