### ISSUE TITLE
Converting datetime value between time units, with read_sql and to_pandas()

### ISSUE THREAD

**Issue by hagsted** [pola-rs/polars#5679]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading Datetime2 columns in MSSQL, the time unit is not set correct. It seems to be a problem when reading values, which is actually a duration, so the datetime is given as 01-01-0001-00:10:00.000000.

The MSSQL is set up with a precision of 6, meaning the unit is µs, while polars gives the values as ns. To me it seems that polars convert the µs to ns even through this results in in an overflow.

Using connectorx in the same virtual environment results in a polars dataframe with the unit in ms, this is not the unit in MSSQL but it can accommodate the correct date.

In the same go, I can see that I cannot do to_pandas on the connectorx polars dataframe, with the unit in ms, as it gives the following error: 
`ArrowInvalid: Casting from timestamp[ms] to timestamp[ns] would result in out of bounds timestamp: -62135596200000`

### Reproducible example

```python
df_test = pl.DataFrame(
    {"Time": [dt.datetime(1,1,1,0,0,0)]}
).with_columns([
    pl.col("Time").cast(pl.Datetime("ms")).alias("msTime"),
    pl.col("Time").cast(pl.Datetime("ns")).alias("nsTime")
])

print(df_test.dtypes)
> [datetime[μs], datetime[ms], datetime[ns]]

print(df_test.columns)
> ['Time', 'msTime', 'nsTime']

print(df_test)
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
c:\Users\khr\Documents\Python\accelink_sql\test.py in line 11
      61 print(df_test.dtypes)
     62 print(df_test.columns)
---> 63 print(df_test)
     64 # print(df_test.to_pandas())

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\polars\internals\dataframe\frame.py:1125, in DataFrame.__str__(self)
   1124 def __str__(self) -> str:
-> 1125     return self._df.as_str()

PanicException: invalid or out-of-range datetime


print(df_test.to_pandas())

Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
c:\Users\khr\Documents\Python\accelink_sql\test.py in line 12
     62 print(df_test.columns)
     63 # print(df_test)
---> 64 print(df_test.to_pandas())

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\polars\internals\dataframe\frame.py:1718, in DataFrame.to_pandas(self, date_as_object, *args, **kwargs)
   1716 record_batches = self._df.to_pandas()
   1717 tbl = pa.Table.from_batches(record_batches)
-> 1718 return tbl.to_pandas(*args, date_as_object=date_as_object, **kwargs)

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\array.pxi:830, in pyarrow.lib._PandasConvertible.to_pandas()

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\table.pxi:3908, in pyarrow.lib.Table._to_pandas()

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\pandas_compat.py:820, in table_to_blockmanager(options, table, categories, ignore_metadata, types_mapper)
    818 _check_data_column_metadata_consistency(all_columns)
    819 columns = _deserialize_column_index(table, all_columns, column_indexes)
--> 820 blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
    822 axes = [columns, index]
    823 return BlockManager(blocks, axes)

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\pandas_compat.py:1170, in _table_to_blocks(options, block_table, categories, extension_columns)
   1165 def _table_to_blocks(options, block_table, categories, extension_columns):
...
File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\table.pxi:2594, in pyarrow.lib.table_to_blocks()

File c:\Users\khr\Documents\Python\accelink_sql\.venv\lib\site-packages\pyarrow\error.pxi:100, in pyarrow.lib.check_status()

ArrowInvalid: Casting from timestamp[us] to timestamp[ns] would result in out of bounds timestamp: -62135596800000000
```

### Expected behavior

print(df_test)

shape: (1, 3)
┌─────────────────────┬─────────────────────┬─────────────────────┐
│ Time                ┆ msTime              ┆ nsTime              │
│ ---                 ┆ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[ms]        ┆ datetime[ns]        │
╞═════════════════════╪═════════════════════╪═════════════════════╡
│ 0001-01-01 00:00:00 ┆ 0001-01-01 00:00:00 ┆ 0001-01-01 00:00:00 │
└─────────────────────┴─────────────────────┴─────────────────────┘
└─────────────────────┴─────────────────────┘

print(df_test.to_pandas())

                           Time                            msTime                                             nsTime  
0   0001-01-01 00:00:00.000000    0001-01-01 00:00:00.000   0001-01-01 00:00:00.000000000  

### Installed versions

<details>

```
---Version info---
Polars: 0.15.1
Index type: UInt32
Platform: Windows-10-10.0.22000-SP0
Python: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by hagsted** [comment]
Sorry I wasn't clear. I think there is something going wrong in polars as my MSSQL entry is 0001-01-01 00:10:00, and when fetched with pd.read_sql results in an "invalid or out-of-range datetime" error when trying to print value. But it converts happily to pandas, however, it gives a wrong output: 1754-08-30 22:53:41.128654848. 

My point was that using connector-x I do get the correct datetime value, however it also seems to be a different unit than the one on the server. And then I can't do to_pandas on the df from connector-x due to ms to ns conversion. So maybe in reality to different bugs.

**Comment by ritchie46** [comment]
I think you need to open an issue upstream in connector-x first then. If you can show a bug without connector-x on our side, we are happy to take that on.

**Comment by hagsted** [comment]
Okay, I will try that.
