### ISSUE TITLE
`then` gets called, even if `when` is False

### ISSUE THREAD

**Issue by ds-evo** [pola-rs/polars#5692]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If i `apply` a function inside a then block, it get's called, for each row. 

Looks like the `when` block is ignored

### Reproducible example

```python
(
            pl.DataFrame([1,2,3], columns='A')
            .with_column(
                pl
                .when(pl.col('A') == 0)
                .then(
                    pl.col(['A']).apply(lambda df: print('# >', df) or 2.)
                )
                .alias('test')
            )
        )

# ---------------
# output is this:
# > 1
# > 2
# > 3
```

### Expected behavior

`then` should only be called, if `when` evals to `True` 

(Same, issue with `map` instead of `apply`...)

I only noticed this, because my custom `apply` function, runs into an error

### Installed versions

<details>

```
pl.show_versions()
---Version info---
Polars: 0.15.1
Index type: UInt32
Platform: Linux-5.15.74.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.21.6
fsspec: 2022.3.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ds-evo** [comment]
> Yes. All branches run in parallel. You must write pure functions in a when then branch.

Is there some better workaround, then using `filter` plus `vstack` ?

Something like this (didn't work) ?:

``` 
df.select([
            pl.col('A').filter(pl.col('A') == 0).apply(somefun).alias('B'),
            pl.lit(1.).filter(pl.col('A') != 0).alias('B')
        ])
```

**Comment by ds-evo** [comment]
> Yes. All branches run in parallel. You must write pure functions in a when then branch.

I thought about it. Yes, makes more sense. Thank you

**Comment by ritchie46** [comment]
I will close this as this expected behavior.
