### ISSUE TITLE
Business date/calendar logic

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#5713]
### Problem description

It would nice to natively support certain business date operations. In particular, I envision polars expression counterparts versions of the vectorized numpy [busday_offset](https://numpy.org/doc/stable/reference/generated/numpy.busday_offset.html#numpy.busday_offset), [is_busday](https://numpy.org/doc/stable/reference/generated/numpy.is_busday.html#numpy.is_busday), [busday_count](https://numpy.org/doc/stable/reference/generated/numpy.busday_count.html#numpy.busday_count) functions. The numpy versions of these functions accept `weekmask` and `holidays` arguments (or a `busdaycalendar` object, which just stores a weekmask and list of holidays).

Given a dataframe with a date column, you could do something like

```python
weekmask = "1111100"
holidays = [datetime.date(2000, 1, 1)]

df.with_columns(
    [
        pl("date").busday_offset(3, weekmask=weekmask, holidays=holidays),
        pl("date").is_busday(weekmask=weekmask, holidays=holidays),
        pl.busday_count(
            pl.col("date"), 
            datetime.date(2000, 1, 2), 
            weekmask=weekmask, 
            holidays=holidays
        )
    ]
)
```

It would also be nice to have a `bdate_range` function/expression so you could get all business dates between two columns by

```python
df.select(
    pl.bdate_range(pl.col("start_date"), pl.col("end_date"), weekmask=weekmask, holidays=holidays)
)
```

**Comment by zundertj** [comment]
Related issue, but specific for upsampling: #5516.

**Comment by zundertj** [comment]
The error you are seeing is a Numpy limitation, `busday_count` is not a ufunc, see the [ufunc list of functions](https://numpy.org/doc/stable/reference/ufuncs.html).

Note that right now we do not support ufunc's with more than one expression. The recommendation is to use `pl.reduce` instead, although the naive way generates a single row list[i64] dataframe (despite the docs claiming it works horizontally):

```python
>>> df.select(pl.reduce(lambda dt1, dt2: np.busday_count(dt1, dt2, weekmask="1110000"), [pl.col('Day1'), pl.col('Day2')]))
shape: (1, 1)
┌───────────┐
│ Day1      │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [0, 1, 1] │
└───────────┘
```

Wrapping in a `Series` solves this:

```python
>>> df.select(pl.reduce(lambda dt1, dt2: pl.Series(np.busday_count(dt1, dt2, weekmask="1110000")), [pl.col('Day1'), pl.col('Day2')]))
shape: (3, 1)
┌──────┐
│ Day1 │
│ ---  │
│ i64  │
╞══════╡
│ 0    │
│ 1    │
│ 1    │
└──────┘
```

**Comment by ion-elgreco** [comment]
I would also expect some support with aliases

In `Expr.dt.offset_by` we could then use `1b` for 1 business day offset or `1bh` for a business hour. Such as in pandas. https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

**Comment by MarcoGorelli** [comment]
Starting with adding `'1bd'` and `'1bh'` as offset aliases sounds good! Anyone here interested in giving this one a go?

**Comment by MarcoGorelli** [comment]
taking this forwards in https://github.com/MarcoGorelli/polars-business , let's take requests and ideas over there

**Comment by MarcoGorelli** [comment]
@erinov1 just FYI, all the requests from your example are now available:
```python
import polars as pl
import polars_business as plb
from datetime import date

weekend = ["Sat", "Sun"]
holidays = [date(2000, 1, 1)]

df = pl.DataFrame(
    {
        "start_date": [date(2000, 3, 1), date(2000, 4, 3)],
        "end_date": [date(2000, 3, 3), date(2000, 4, 19)],
    }
)

print(
    df.with_columns(
        start_plus_3bd=plb.col("start_date").bdt.offset_by(
            "3bd", weekend=weekend, holidays=holidays
        ),
        start_is_workday=plb.col("start_date").bdt.is_workday(
            weekend=weekend, holidays=holidays
        ),
        workday_count=plb.workday_count(
            "start_date",
            "end_date",
            weekend=weekend,
            holidays=holidays,
        ),
    )
)
```
```
shape: (2, 5)
┌────────────┬────────────┬────────────────┬──────────────────┬───────────────┐
│ start_date ┆ end_date   ┆ start_plus_3bd ┆ start_is_workday ┆ workday_count │
│ ---        ┆ ---        ┆ ---            ┆ ---              ┆ ---           │
│ date       ┆ date       ┆ date           ┆ bool             ┆ i32           │
╞════════════╪════════════╪════════════════╪══════════════════╪═══════════════╡
│ 2000-03-01 ┆ 2000-03-03 ┆ 2000-03-06     ┆ true             ┆ 2             │
│ 2000-04-03 ┆ 2000-04-19 ┆ 2000-04-06     ┆ true             ┆ 12            │
└────────────┴────────────┴────────────────┴──────────────────┴───────────────┘
```
