### ISSUE TITLE
Restore `df.attr` and `df[df.attr > 0]` filter method and undo it

### ISSUE THREAD

**Issue by longilacus** [pola-rs/polars#5717]
### Problem description

With polars we do save a lot time than pandas in processing panel data. But since 0.15, my friends and I found we can not use `df.attr` and `df[df.attr > 0]` as before, this really makes a lot more code to write. `df['attr']` and `df.filter(pl.col('attr') > 0)` slow down the type speed a lot.

After some digging, we found class method `__getattr__` is gone, maybe `df.attr` would casue conflict with mehtod built in polars, but this actually  can be avoid. Also the `Boolean` Series now couldn't be use as filter series.

Here are some code for restore and undo these `__getattr__` and filter functions with not influence for polars.

```
POLARS_ORIGIN_GETITEM_FUNC = copy.deepcopy(pl.DataFrame.__getitem__)

class Config:

    @classmethod
    def mod_polars(cls):
       
        def getitem(self, item: pl.Series) -> pl.DataFrame:
            if isinstance(item, pl.Series) and item.dtype == pl.Boolean:
                return self.filter(item)
            else:
                return POLARS_ORIGIN_GETITEM_FUNC(self,item)

        def getattr(self, item: str) -> pl.Series:

            if isinstance(item, str):
                if item.startswith('_') and item.endswith('_'):
                    raise AttributeError(item)
                return self[item]
            else:
                raise AttributeError(f"DataFrame has no attribute {item}")

        setattr(pl.DataFrame, '__getitem__', getitem)
        setattr(pl.DataFrame, '__getattr__', getattr)

    @classmethod
    def recover_polars(cls):
       
        setattr(pl.DataFrame, '__getattr__', None)
        setattr(pl.DataFrame, '__getitem__', POLARS_ORIGIN_GETITEM_FUNC)
````

**Comment by zundertj** [comment]
The behaviour you are describing has been intentionally deprecated and later on removed, as you have found out. I can't find the relevant issue threads here now, but in short:
1. The getattr override is very risky, as you can and will have conflicts between Dataframe methods and column names. I.e. what if you call your column "head", you do not know what `df.head` returns anymore.
2. The indexing `df[df.attr > 0]` encourages slow code, as everything has to be eagerly evaluated. We encourage our users to write fast code by default. If we still want to support your index proposal, there would be more than one way to do the same operation; we try to keep the number of different ways how to do something down on purpose as to encourage a single consistent API.
3. We know that Pandas allows both of these features, but Polars does not have the goal to be a drop-in replacement for Pandas.

You are always free to patch Polars yourself, as you do here. I do encourage you to use the namespace feature we have (https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.api.register_dataframe_namespace.html), to avoid conflicts on future package upgrades. Yes, I do know, it adds a bit of typing.
