### ISSUE TITLE
Implement writing Categorical values to json

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#5723]
### Problem description

Polars has a great support of Categorical values. But writing to json is not yet implemented for this kind of values.

Example:

````python
import polars as pl

with pl.StringCache():
    data = {
        "column": ['test1', "test2", "test3", "test4"]
    }
    df = pl.DataFrame(data)

    test = df.write_json(row_oriented=True, file=None)
    print(test)
````

Outputs

````json
[{"column":"test1"},{"column":"test2"},{"column":"test3"},{"column":"test4"}]
````

But with converting to categorical as:
````python
import polars as pl

with pl.StringCache():
    data = {
        "column": ['test1', "test2", "test3", "test4"]
    }
    df = pl.DataFrame(data).with_columns([
        pl.col('column').cast(pl.Categorical).keep_name()
    ])
    test = df.write_json(row_oriented=True, file=None)
    print(test)
````

leads to exception:
````python
pyo3_runtime.PanicException: not yet implemented: Writing Dictionary(UInt32, LargeUtf8, false) to JSON
````

So, it will awesome to "render" Categorical values to json as simple strings.

P.S. Thanks a lot for such a great tool

**Comment by ritchie46** [comment]
Yeap, we should be able to do that. I can work on that once https://github.com/jorgecarleitao/arrow2/pull/1320 is merged.

**Comment by jgmartin** [comment]
I'm also running into this issue.  It seems that casting anything to categorical that ends up in the serialized result triggers the bug.

**Comment by jgmartin** [comment]
I've made an attempt to address this here https://github.com/ritchie46/arrow2/pull/6.  Not sure if I'm missing any major concerns, so your review is much appreciated.

**Comment by ritchie46** [comment]
I was working towards this in arrow2. That's why I need https://github.com/jorgecarleitao/arrow2/pull/1320. I shall pick it up.

**Comment by ritchie46** [comment]
This has been added
