### ISSUE TITLE
[Error] no method named `describe` found for struct `polars::prelude::DataFrame` in the current scope

### ISSUE THREAD

**Issue by zhouhaoan** [pola-rs/polars#5726]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I try to run a simple example. But it says method `describe` not found.
![image](https://user-images.githubusercontent.com/55027252/205804815-f5f19b61-5254-419d-9220-d4e40bc47a6a.png)

### Reproducible example

```
use std::{io, fs};
use polars::prelude::*;

fn clean_df_core(csv_path: &str) -> Result<usize, PolarsError> {
    let df = CsvReader::from_path(csv_path).finish().unwrap();
    
    let info_df: DataFrame = df.describe(None);

    println!("{}", &df);
    println!("{}", &info_df);

    Ok(0);
}

fn main() {
    let csv_path = "my csv path";
    clean_df_core(csv_path);
}
```

### Expected behavior

When running `cargo build`, raise this error.

### Installed versions

<details>
polars = { version = "0.25.1", features = ["lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "list_eval", "rank", "lazy_regex"]}

rustc : 1.67.0-nightly (e1d819583 2022-12-05)
cargo : 1.67.0-nightly (f6e737b1e 2022-12-02)
rustup : 1.25.1 (bb60b1e89 2022-02-12)

This code is running on a offline machine. I write it on a online machine and copy project directory and `
~/.cargo` directory to target machine. They are both x64 arch and Ubuntu 20.04 OS. 
</details>

**Comment by ritchie46** [comment]
Activate `describe` feature.
