### ISSUE TITLE
assert_series_equal considers Nan is not different from real value

### ISSUE THREAD

**Issue by mingi3314** [pola-rs/polars#5731]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

assert_series_equal considers both Nan and real value as same.

I think this is because `testing.asserts._assert_series_inner` only check both left and right are null or not.
https://github.com/pola-rs/polars/blob/b311405b80b2a086d58450c64e7e7c2d2cbcb51d/py-polars/polars/testing/asserts.py#L188

For example, let left is a series filled with nan values, and right is a series filled with a real values. 
Then `left.is_null()` returns a series filled with False, and `right.is_null()` returns a series filled with False. 
So both series are considered as same when checking missing values.

### Suggestion
So, how about change https://github.com/pola-rs/polars/blob/b311405b80b2a086d58450c64e7e7c2d2cbcb51d/py-polars/polars/testing/asserts.py#L188 like as follows?

```
(left.fill_nan(None).is_null() != right.fill_nan(None).is_null()).any() 
```

If it's okay, can I work on it and submit a pull request?

### Reproducible example

```python
import polars as pl
from polars.testing import assert_series_equal

arr1 = pl.Series("a", [1.0, 2.0, 3.0, 4.0, 5.0])
arr2 = pl.Series("b", [1.0, 2.0, 3.0, 4.0, float("nan")])
arr3 = pl.Series("c", [1.0, 2.0, 3.0, 4.0, None])

assert_series_equal(arr1, arr2, check_names=False) # case 1
assert_series_equal(arr1, arr3, check_names=False) # case 2
```

### Expected behavior

both case 1 and case 2 must raise `AssertionError: Series are different`
however, only case 2 raise AssertionError, whereas case 1 is considered as equal series

### Installed versions

<details>

```
---Version info---
Polars: 0.15.2
Index type: UInt32
Platform: Linux-5.15.74.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.9.12 (main, Apr 26 2022, 13:27:20) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.2
numpy: 1.22.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2
```

</details>

**Comment by alexander-beedie** [comment]
@mingi3314; many thanks for the bug report - I found another edge-case while investigating your report, so ended-up extending the assert test coverage and fixing them both 😅
