### ISSUE TITLE
fetch and optimization_toggle still have allow_streaming

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5745]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

In python fetch still has `allow_streaming` as its argument. In Rust `optimization_toggle` still has allow_streaming.

A search shows where it occurs:
- fetch in Python (needs deprecated alias)
- `cross_join_dfs` in an error message
- README.md
- collect_all in Python (needs deprecated alias)
- profile in Python (needs deprecated alias)
- test_joins and test_predicates.py

You can assign to me if its just a matter of tidying things up

### Reproducible example

N/A

### Expected behavior

N/A

### Installed versions

<details>
---Version info---
Polars: 0.15.2
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
Python: 3.10.1 (main, Dec 21 2021, 09:50:13) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.6.2
</details>

**Comment by ritchie46** [comment]
Right.. Could you make a PR?

**Comment by braaannigan** [comment]
> Right.. Could you make a PR?

Sure

**Comment by braaannigan** [comment]
@ritchie46 can we remove this line from the readme "(This might be a little slower, but
it is still very fast!)"

as the streaming engine is fast?
