### ISSUE TITLE
select columns in scan_csv()

### ISSUE THREAD

**Issue by silvewheat** [pola-rs/polars#5755]
### Problem description

It doesn't look like there is a direct way of selecting columns in scan_csv().
Maybe it's worth adding 'columns' option in this function, like in read_csv().
For now, I select columns in this way:
```python
cols_used = ['foo', 'bar']
# in scan_csv()
df = pl.scan_csv(file).select(pl.col(cols_used))

# in read_csv()
df = pl.read_csv(file, columns=cols_used)
```

Add 'columns' option in scan_csv() could make the code more clear and more easy to transfer code from read_csv() to scan_csv().
```python
df = pl.scan_csv(file, columns=cols_used)
```

**Comment by ritchie46** [comment]
This is not needed in `scan_csv` because the query optimizer will automatically select the columns you use. No need to clutter the api with that.

```python
pl.scan_csv(file).select(["foo" , "bar"])
```
is the way to select columns.
