### ISSUE TITLE
Make columns names available in expression or allow pl.col to have a default type to autofill as null

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#5757]
### Problem description

Let's say you start with a list of dataframs such as

```Ldfs=[
     pl.DataFrame({'a':[1.0,2.0,3.1], 'b':[2,3,4]}), 
     pl.DataFrame({'b':[1,2,3], 'c':[2,3,4]}), 
     pl.DataFrame({'a':[1,2,3], 'c':[2,3,4]})
    ]
```

We can't concat this into one because the DataFrames don't have the same columns.  We also, seemingly, can't use expressions to make them match.  We can inspect the columns before building expressions but I'd like to be able to resolve the discrepancy in one of two ways (depending on practicality and ease of implementation):

1.  Make the existence of columns available in expressions.  Something like this: ```Ldfs[0].select(pl.when(pl.col('c')).then(pl.col('c').cast(pl.Float64()).otherwise(pl.lit(None).cast(pl.Float64()).alias('c')))```
2. or allow select to ignore columns that aren't in the df like ```Ldfs[0].select([pl.col(abc, if_not_exist=pl.Float64()) for abc in ['a','b','c']])```

where the if_not_exist is to set the datatype that would just be filled in with nulls.  

With more thought, I think I prefer the second.

**Comment by zundertj** [comment]
You can use `pl.concat([<list of dataframes>]), how="diagonal")` for this. See also https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.concat.html.
