### ISSUE TITLE
A DataFrame.astype method to cast columns

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#5758]
### Problem description

I found this feature very helpful in Pandas; here is how I see it working in polars:

```python
def _astype(df:pl.DataFrame, dtype_dict:dict[str,pl.DataType])->pl.DataFrame:      
    
    current_types = df.select(pl.col(list(dtype_dict.keys()))).schema
    
    type_tuples = {k: (current_types[k], dtype_dict[k]) for k in dtype_dict.keys()}
    
    conversion_dict = {col: pl.col(col).cast(dtype) 
                       
                            if (dtype not in [pl.Date, pl.Datetime] or (cdtype != pl.Utf8())) else 
                       
                            pl.col(col).str.strptime(dtype)     
                                         
                       for col, (cdtype, dtype) in type_tuples.items()}
    
    return df.with_columns(**conversion_dict)

pl.DataFrame.astype = _astype
```

The idea is that you can convert the types of multiple columns. 

```python
# Usage

df = pl.DataFrame({'A': [1,2,3],'B': ['2020-01-01','2020-01-02','2020-01-03']})

df.astype({'A':pl.Datetime(), 'B':pl.Date()})

# Or 

df.astype({'A':pl.Int8()})
```

**Comment by zundertj** [comment]
This seems really two things. 

1. a relatively marginal syntax improvement over
```python
df.with_columns([pl.col("A").cast(pl.Datetime)), pl.col("B").cast(pl.Date))])
```
by using a dict. The downside of the dict is that naturally you would refer to columns using strings, as the column names are the keys, and thus `pl.all().exclude()` and regex versions are maybe possible (if Polars expressions are hashable), but would not occur as very natural to write.


2. a more flexible `cast` that automatically parses strings to datetimes if requested (with all pros and cons that come with it):

```python
def cast_flex(col_in, dtype):
   if (dtype not in [pl.Date, pl.Datetime] or (col_in.dtype != pl.Utf8())):
         return col_in.cast(dtype) 
  else:
         pl.col(col).str.strptime(dtype)  

```
(note: bit naive implementation, only works on a single `pl.col()` now). It would be limited to a single timestamp format in this setup.

For both, I could see it being useful, but both are pretty marginal gains to be honest, and come with downsides. Is it both that you think are useful?

**Comment by cmdlineluser** [comment]
`DataFrame.cast` has since been added which I think closes this. #10504

#10517 for casting strings to datetimes.

**Comment by mkleinbort-ic** [comment]
Agreed
