### ISSUE TITLE
Support for HDF files (.h5 or .hdf)

### ISSUE THREAD

**Issue by Mouradost** [pola-rs/polars#5776]
### Problem description

Hi,
I was hoping that Polars could support HDF files out of the box to be in part with Pandas, since it is widely used in scientific research.
The feature should be similar to the Pandas library, such as this python example:

```python
import pandas as pd

data = pd.read_hdf("file.h5")

data.to_hdf("file_new.h5", key="MyData")
```
The key should be optional, since I see it rarely used when there is only one Data Frame stored in the HDF file.
The Polars version could follow the same schema as the read_csv and write_csv function already implemented in Polars.

**Comment by zundertj** [comment]
Thank you for suggesting this. I will close this issue, as it has been suggested before, see #3520. Please comment and/or upvote that issue. Thank you.
