### ISSUE TITLE
Slice syntax for column selection failed

### ISSUE THREAD

**Issue by yinzuojie** [pola-rs/polars#5779]
For a certain df with header, the following selection expressions are all ok:
df[1:3, [1,2]]
df[1:3, 1]
df[1:3, 'ci']
df[1:3, ['ci','rrc']]
df[[1,8], :]

but only this one failed.
df[[1,8], 1:3] #██  
is it a bug or defined behavior? why df[[1,8], :] is ok?

error messages listed here:
d:\soft\prog\python\lib\site-packages\polars\internals\dataframe\frame.py in __getitem__(self, item)
   1336 
   1337             df = self.__getitem__(col_selection)
-> 1338             return df.__getitem__(row_selection)
   1339 
   1340         # select single column

d:\soft\prog\python\lib\site-packages\polars\internals\dataframe\frame.py in __getitem__(self, item)
   1384             if dtype in {UInt8, UInt16, UInt64, Int8, Int16, Int32, Int64}:
   1385                 return self._from_pydf(
-> 1386                     self._df.take_with_series(self._pos_idxs(item, dim=0)._s)
   1387                 )
   1388 

ComputeError: take indices are out of bounds

thanks~

**Comment by ritchie46** [comment]
Can you fill in the issue template please?
