### ISSUE TITLE
Support dataframe selection based on boolean mask

### ISSUE THREAD

**Issue by baarkerlounger** [pola-rs/polars#5782]
### Problem description

If I have: 

```rust
let df = df!("A" => &[0, 1, 3], "B" => &[0, 1, 4]).unwrap();
let boolean_mask = df!("A" => &[true, true, false], "B" => &[false, true, false]).unwrap();

shape: (3, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
│ 0   ┆ 0   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 4   │
└─────┴─────┘
shape: (3, 2)
┌───────┬───────┐
│ A     ┆ B     │
│ ---   ┆ ---   │
│ bool  ┆ bool  │
╞═══════╪═══════╡
│ true  ┆ false │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ true  ┆ true  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ false ┆ false │
```

It would be great to have an API that lets me select elements based on index comparison to the boolean mask such that I could do something like:

```rust
df.filter(&boolean_mask).sum()

shape: (1, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 1   │
└─────┴─────┘
```

**Comment by mcrumiller** [comment]
You already can do this, it's right in the documentation for `filter`:

```python
import polars as pl

df =  pl.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': [True, False, True, False, True]
})

df.filter(pl.col('b'))
```
```
shape: (3, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ bool │
╞═════╪══════╡
│ 1   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5   ┆ true │
└─────┴──────┘
```

**Comment by cmdlineluser** [comment]
> Masking out values by columns in another DataFrame is a potential for errors caused by different lengths. 
>For this reason polars does not encourage such operations and therefore you must first create a single DataFrame

Source: https://stackoverflow.com/a/72899438

[`.with_context()`](https://pola-rs.github.io/polars/polars_lazy/frame/struct.LazyFrame.html#method.with_context) can be used to access columns from both dataframes - same for #5767

Python example:

    (df.lazy()
       .with_context(
          boolean_mask.lazy()
             .select(pl.all().suffix("_right")))
       .select([
          pl.when(pl.col(f"{name}_right"))
            .then(pl.col(name)) 
          for name in boolean_mask.columns
        ])
       .collect()
    )

    shape: (3, 2)
    ┌──────┬──────┐
    │ A    | B    │
    │ ---  | ---  │
    │ i64  | i64  │
    ╞══════╪══════╡
    │ 0    | null │
    ├──────┼──────┤
    │ 1    | 1    │
    ├──────┼──────┤
    │ null | null │
    └─//───┴─//───┘

**Comment by baarkerlounger** [comment]
@cmdlineluser you could have the method check for equal shapes before attempting anything else? The restriction makes the API very verbose, especially when combining multiple boolean mask dataframes in this way.

**Comment by mcrumiller** [comment]
Is something like this not implemented in Rust? In Python it's trivial to use a pl.Series or column to mask:

```python
import polars as pl

df = pl.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['a', 'b', 'c', 'd,' 'e'],
    "mask": [True, False, True, False, True]
})
mask = pl.Series([True, False, True, False, True]
```
```
>>>print(df.filter(mask))
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ mask │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ str ┆ bool │
╞═════╪═════╪══════╡
│ 1   ┆ a   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3   ┆ c   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5   ┆ e   ┆ true │
└─────┴─────┴──────┘

>>>print(df.filter(pl.col("mask")))
shape: (3, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ mask │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ str ┆ bool │
╞═════╪═════╪══════╡
│ 1   ┆ a   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3   ┆ c   ┆ true │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5   ┆ e   ┆ true │
└─────┴─────┴──────┘

```

**Comment by zundertj** [comment]
The "Polars way" would be to join dataframes, and then use the filtering & expression machinery. Coming myself from a Matlab background ("everything is a matrix!"), this needs some time to get used to, but more often than not, it turns out that you should not really split your data in separate dataframes if it belongs together.

In your example, you would not have `boolean_mask` come from a completely separate source of `df`. This because you assume here that the rows match up, so there must be a relationship between the two dataframes. Instead, you would probably have derived `boolean_mask` from `df`. Polars basically tells you to not have the mask separate, but in the same dataframe. Or even better, have the mask just live as an expression, and not allocate memory at all. I do realize your actual use case has more to it then the example shows, but maybe this helps.

**Comment by MarcoGorelli** [comment]
this step
```
df.filter(&boolean_mask)
```
would already not be supported, as the columns would have different lengths

You can do
```
In [10]: df.select(pl.col(col).filter(mask[col]).sum() for col in df.columns)
Out[10]:
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
└─────┴─────┘
```

closing then, but thanks for the request!
