### ISSUE TITLE
Iterable `groupby_rolling` and `groupby_dynamic`

### ISSUE THREAD

**Issue by StijnKas** [pola-rs/polars#5786]
### Problem description

`groupby` has an `__iter__` method defined, making it quite easy to iteratively work through the groups for debugging. Although for production of course you'd just use `.agg`, it would be nice if `groupby_rolling` and `groupby_dynamic` also had an `__iter__` method.

**Comment by stinodego** [comment]
I have just revised the iterator for the regular `GroupBy` - if that gets merged we can probably implement something similar for `RollingGroupBy` and `DynamicGroupBy`.
