### ISSUE TITLE
 pl.concat not working when column order differs

### ISSUE THREAD

**Issue by legout** [pola-rs/polars#5789]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Concatenation of DataFrames is only possible for dataframes with identical order of columns. 

### Reproducible example

```python
import polars as pl

df1 = pl.DataFrame({"A":[1,2,3], "B":[1,2,3]})
df2 = pl.DataFrame({"B":[1,2,3], "A":[1,2,3]})

df = pl.concat([df1, df2])
```

### Expected behavior

Order of columns should not matter.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.2
Index type: UInt32
Platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.31
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:18:27) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by zundertj** [comment]
The ordering mostly does not matter, although it does when using numeric indexing (`df[:,0]` vs `df[:,1]`), so not sure this is "wrong". Also, note that you can use `how="diagonal"`:

```python
>>> df = pl.concat([df1, df2], how="diagonal")
>>> df
shape: (6, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 3   │
└─────┴─────┘
```

**Comment by legout** [comment]
I understands.

Unfortunately, this doesn´t allow me to load many files from a folder, when the column order is not identical.
So, this will fail:
```python
pl.read_parquet("path/to/parquet/dataset/*")
```

**Comment by zundertj** [comment]
Got it, that is more tricky. You could try passing in a list of columns using the `columns` arg? That assumes you know those up front of course. I am also curious, which software produces a partitioned parquet file with mixed column ordering?

**Comment by ritchie46** [comment]
You can use python glob to read the lazyframes separately and then concatenate them sorted by the columns. This is similar to what we do internally save for the sorting.

**Comment by ritchie46** [comment]
I will close this as this is expected behavior. If the schemas of different files differ, they have to be handled accordingly by the user as I think it is a reasonable default to error on these cases. 

We see schema's as ordered and not as an unordered set.

**Comment by legout** [comment]
> 

Makes sense. Thanks for the reply. :-)
