### ISSUE TITLE
data duplication when combining scan_ds + nested columns

### ISSUE THREAD

**Issue by edavisau** [pola-rs/polars#5796]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am running into issues working with pyarrow datasets in combination with parquet files with nested columns. 

When the number of rows of the dataset reaches a threshold, selecting the nested column returns duplicates. This problem does not exist when scanning the Parquet file directly though, so this seems like an issue with polars or pyarrow, rather than arrow2.

In the example below I produce parquet files of specific length, and then read the nested column back in. The pattern I observed was:
- num_rows <= 2^17:   normal
- 2^17 < num_rows <= 2^18:   2x duplication
- 2^18 < num_rows <= 2^19:   3x duplication
- 2^19 < num_rows <= 2^20:  5x duplication
- 2^20 < num_rows <= 2^21:  9x duplication

Another observation: if I select a non-nested column, there is no duplication. Also, if I select both columns `select(["id", "nested"])`, I receive `PanicException: The column lengths in the DataFrame are not equal.`, which makes sense due to the error above.

### Reproducible example

```python
import polars as pl
import pyarrow.dataset as ds

def test_row_size(num_rows: int, use_pyarrow_dataset: bool) -> int:
    pl.from_records([
        dict(
            id=i, 
            nested=dict(
                a=i,
            )
        )
        for i in range(num_rows)
    ]).write_parquet("/tmp/out.parquet", use_pyarrow=True)
    
    scanner = pl.scan_ds(ds.dataset("/tmp/out.parquet")) if use_pyarrow_dataset else pl.scan_parquet("/tmp/out.parquet")
    return (
        scanner
        .select("nested")
        .collect()
        .shape[0]
    )

print("Using scan_ds")
print(test_row_size(num_rows=2**17, use_pyarrow_dataset=True))  # Returns 131072 rows (correct) 
print(test_row_size(num_rows=2**17 + 1, use_pyarrow_dataset=True))  # Returns 262146 rows  -  expected 131073 rows (result is 2x larger)
print(test_row_size(num_rows=2**18 + 1, use_pyarrow_dataset=True))  # Returns 786435 rows  -  expected 262145 rows (result is 3x larger)
print(test_row_size(num_rows=2**19 + 1, use_pyarrow_dataset=True))  # Returns 2621445 rows  -  expected 524289 rows (result is 5x larger)
print(test_row_size(num_rows=2**20 + 1, use_pyarrow_dataset=True))  # Returns 9437193 rows  -  expected 1048577 rows (result is 9x larger)


print("Using scan_parquet")
print(test_row_size(num_rows=2**17, use_pyarrow_dataset=False))  # Returns 131072 rows (correct)
print(test_row_size(num_rows=2**17 + 1, use_pyarrow_dataset=False))  # Returns 131073 rows (correct)
print(test_row_size(num_rows=2**18 + 1, use_pyarrow_dataset=False))  # Returns 262145 rows (correct)
print(test_row_size(num_rows=2**19 + 1, use_pyarrow_dataset=False))  # Returns 524289 rows (correct)
print(test_row_size(num_rows=2**20 + 1, use_pyarrow_dataset=False))  # Returns 1048577 rows (correct)
```

### Expected behavior

scan_ds should match scan_parquet behaviour

### Installed versions

<details>

```
---Version info---
Polars: 0.15.5
Index type: UInt32
Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by ritchie46** [comment]
`scan_ds` uses `pyarrow` dataset. Can you confirm creating arrow table from pyarrow dataset works as expected?

**Comment by edavisau** [comment]
Hi @ritchie46 , I tried `ds.dataset("/tmp/out.parquet").to_table()` as well as `to_table(columns=["nested"])` and `to_table(columns=["id"])`. They all return the correct data and cardinality. Is this what you were after?

**Comment by edavisau** [comment]
`pl.from_arrow(ds.dataset("/tmp/out.parquet").to_table())` fails with `pyo3_runtime.PanicException: The column lengths in the DataFrame are not equal.`

**Comment by ritchie46** [comment]
Ok, for some reason pyarrows FFI returns the same chunk in ffi even though it is a diffferent one. I think I need to raise an issue upstream. Currently there is a workaround.

**Comment by edavisau** [comment]
Thank you for implementing the workaround! It now makes sense why I was having similar issues using arrow tables with struct columns in DuckDB. The issue very much looks upstream as that 2^17 threshold causes issues in DuckDB also.
