### ISSUE TITLE
fill_null casts the type of a DataFrame to Float64

### ISSUE THREAD

**Issue by david-wintergerst** [pola-rs/polars#5811]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using fill_null on a DataFrame with column type Float32, the type is cast to Float64. The expected behavior would be that the datatype of the column remains unchanged.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1.1, 1.2]}, columns=[("a", pl.Float32)])
print(df.dtypes)
# [<class 'polars.datatypes.Float32'>]
df2 = df.fill_null(value=0)
print(df2.dtypes)
# [<class 'polars.datatypes.Float64'>]
```

### Expected behavior

import polars as pl

df = pl.DataFrame({"a": [1.1, 1.2]}, columns=[("a", pl.Float32)])
print(df.dtypes)
# [<class 'polars.datatypes.Float32'>]
df2 = df.fill_null(value=0)
print(df2.dtypes)
# [<class 'polars.datatypes.Float32'>]

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2```

</details>

**Comment by ghuls** [comment]
It does it you provide your fill value in the same type (float instead of int), else the series get casted to the supertype float64.
```python
df2 = df.fill_null(value=0.0)
df2.dtypes
Out[6]: [polars.datatypes.Float32]
```

**Comment by david-wintergerst** [comment]
Thank you,
that is very helpful to know. 
I still think the behavior is not obvious and should at least be documented.

**Comment by ritchie46** [comment]
> Thank you, that is very helpful to know. I still think the behavior is not obvious and should at least be documented.

Yep, I think we should try to take the minimal literal here.
