### ISSUE TITLE
unexpected behaviour of .arr() when value is NULL

### ISSUE THREAD

**Issue by AnatolyBuga** [pola-rs/polars#5812]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Hello team Polars,

On the example below I got this error:
```
ShapeMisMatch(
        Borrowed(
            "Shape of parameter `mask` and `other` could not be used in zip_with operation",
        ),
    ),
```

It doesn't look like expected behaviour to me, but I might be missing something?

### Reproducible example

```rust
use polars::prelude::*;

pub fn issue(){
// Just creating a List Column
let s0 = Series::new("a", &[1i64, 2, 3]);
let s1 = Series::new("b", &[1i64, 1, 1]);
let s2 = Series::new("c", &[2i64, 2, 2]);
let list = Series::new("foo", &[None, Some(s1), Some(s2), Some(s0)]);
let o: Option<&str> = None;
let s3 = Series::new("B", [o, o, Some("A"), Some("C")]);
let s4 = Series::new("C", [o, Some("B"), o, Some("H")]);
// This is the Frame Hamza has in the UI
let df = df!(
    "foo" => list,
    "b" => s3,
    "c" => s4,
).unwrap();
dbg!(&df);

let res = df.clone().lazy().with_column(
    when(
        col("b")
            .is_not_null()
            .or(col("c").is_not_null()),
    )
    .then(col("foo").arr().max().alias("foo1"))
    .otherwise(NULL.lit()),
);
dbg!(res.collect());
}
```

### Expected behavior

I would expect the new column to be i64 `[null, 1, 2]`

### Installed versions

<details>
0.25.1
</details>

**Comment by AnatolyBuga** [comment]
Also, if I do
```
let res = df.lazy().with_column(
    col("foo").arr().max().alias("foo1")
);

dbg!(res.collect());
```

I get:
```
ShapeMisMatch(
        Owned(
            "Could not add column. The Series length 3 differs from the DataFrame height: 4",
        ),
    ),
```

must be something wrong with arr()?

**Comment by thirumaranA** [comment]
let res = df.clone().lazy().with_column(
    when(
        col("b").is_not_null() || col("c").is_not_null()
    )
    .then(col("foo").arr().max().alias("foo1"))
    .otherwise(NULL.lit()),
);
Try this

**Comment by AnatolyBuga** [comment]
> let res = df.clone().lazy().with_column( when( col("b").is_not_null() || col("c").is_not_null() ) .then(col("foo").arr().max().alias("foo1")) .otherwise(NULL.lit()), ); Try this

As far as I can see col("b").is_not_null() is of type Expr. Expr doesn't implement BitAnd<Expr> and BirOr<Expr> traits. So this code won't compile. 

Working alternative to what you are suggesting I think would be:
```rust
let res = df.clone().lazy().with_column(
    when( apply_multiple(|srss|{
        let a = srss[0].is_not_null() | srss[1].is_not_null();
        Ok(a.into_series())
    }, 
        [col("b"), col("c")], GetOutput::from_type(DataType::Boolean), false)
    )
    
    .then(col("foo").arr().max().alias("foo1"))
    .otherwise(NULL.lit()),
);
```
But this results in the same error. 

The problem is with arr() behaviour on a NULL value it seems.
