### ISSUE TITLE
expressions everywhere 

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#5813]
### Problem description

'''
df.with_columns([
   pl.col("a").str.split("\d{3}").alias("z_a"),
   pl.col("a").str.replace(pl.col("b"),"").alias("z_b"),
pl.col("a")str.extract_all_except(pl.col("b").alias("c_c"),
pl.col("a").str.split_exact(pl.col("b").alias("c_d"),
pl.col("a")str.replacel(pl.col("b", "").alias("c_c"),
  ]
  )
'''

**Comment by ritchie46** [comment]
What is your suggestion?

If you don't want to type `pl.col`, you are free to rename it. It is your program.

```python
import polars.col as c
```

**Comment by mcrumiller** [comment]
I typically use this preamble:

```python
import polars as pl
from polars import col, when
```

This cleans up syntax a lot:

```python
df.select([
    when(col('a').is_in(col('b')).then(1)
    .otherwise(2)
])
```
...etc.

**Comment by Arengard** [comment]
we as of now cant do ny of the operation from obove

**Comment by mcrumiller** [comment]
Can you spend a little more effort describing what your issue is?

**Comment by ritchie46** [comment]
I will close this issue as I don't see anything constructive here. If there is a better definition of the problem, a suggestion how to fix it and more effort to fill in our issue templates feel free to open a new issue.
