### ISSUE TITLE
Modify str.replace_all to also take a dictionary as argument

### ISSUE THREAD

**Issue by maiiabocharova** [pola-rs/polars#5815]
### Problem description

First of all, thank you for the awesome library!

One feature which would be very helpful for me:

When I have multiple replaces which I want to carry out and have a dictionary of such replacements it would be very nice to be able to pass it to `str.replace_all` directly and not stack one-by-one.

**Comment by stinodego** [comment]
Actually I am not sure we should modify `str.replace` / `str.replace_all`. We don't seem to have a 'normal' `replace` for replacing integers or other values. I wonder what we use for this, and if that could be used for your use case.

**Comment by maiiabocharova** [comment]
Maybe than to add support for using a list of lists to pass to `str.replace_all`? Probably I do not understand something, but I do not see why it can't work

**Comment by ritchie46** [comment]
> We don't seem to have a 'normal' replace for replacing integers or other values

We could add this trivially on the python side in an expression that utilizes the existing join architecture. This is highly parallelized and optimized.

In this SO answer I have an example how we could implement this.

https://stackoverflow.com/a/74782121/6717054

**Comment by niklarz** [comment]
The current workaround that I use to [replace_all from a dict]( https://stackoverflow.com/questions/75212019/replace-substring-in-string-using-list-or-dict-in-polars-pythons
). This replaces all occurrences in all strings/rows in a series by simply looping thought all patterns.

**Comment by ghuls** [comment]
For replacing whole values of columns by using a dict for mapping, you can use `map_dict`

Closed by: https://github.com/pola-rs/polars/pull/5899
