### ISSUE TITLE
.dt.epoch("s") on a pl.Time col returns microseconds since midnight

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/polars#5818]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Equivalently, the values of `.dt.epoch` for `pl.Time` columns are one million times what I would expect.

I'm not sure what the correct behaviour of `.dt.epoch` is for a `pl.Time` column, but I imagine at the very least that currently the scale is wrong.

### Reproducible example

```python
from datetime import time
import polars as pl
assert pl.Series([time(0, 0, 1)]).dt.epoch("s")[0] == 1_000_000
assert pl.Series([time(0, 0, 2)]).dt.epoch("s")[0] == 2_000_000
assert pl.Series([time(0, 1, 0)]).dt.epoch("s")[0] == 60 * 1_000_000
assert pl.Series([time(0, 0, 1)]).dt.epoch("ms")[0] == 1_000_000_000
```

### Expected behavior

```python
from datetime import time
import polars as pl
assert pl.Series([time(0, 0, 1)]).dt.epoch("s")[0] == 1
assert pl.Series([time(0, 0, 2)]).dt.epoch("s")[0] == 2
assert pl.Series([time(0, 1, 0)]).dt.epoch("s")[0] == 60
assert pl.Series([time(0, 0, 1)]).dt.epoch("ms")[0] == 1_000
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-5.15.57-2-MANJARO-x86_64-with-glibc2.35
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
I think it should error. It does not make sense to compute the time since the unix epoch with a `time` dtype.
