### ISSUE TITLE
`read_csv()` does not correctly handle certain numbers in scientific notation

### ISSUE THREAD

**Issue by jakobhansen-blai** [pola-rs/polars#5819]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Floating point numbers in scientific notation are incorrectly parsed as strings by `read_csv()` in the following situation:
- the mantissa is negative, and
- the exponent is positive but does not have a "+", and
- there is not a decimal point in the mantissa.

That is, strings like "-1e1" are not recognized as representing floating point values.

Strings like "0e1" or "0e0" are also parsed as strings, while, e.g., "0e-1" is parsed as the float 0.0. This seems like a reasonable situation in which to expect undefined behavior, though.

### Reproducible example

```python
import polars as pl
from io import StringIO
csv = StringIO("a,b\n-1e1,-10.0\n")
pl.read_csv(csv)
```
Output:

```
shape: (1, 2)
┌──────┬───────┐
│ a    ┆ b     │
│ ---  ┆ ---   │
│ str  ┆ f64   │
╞══════╪═══════╡
│ -1e1 ┆ -10.0 │
└──────┴───────┘
```

### Expected behavior

Column "a" of the result should have type `f64` and have the same value as column "b".

### Installed versions

<details>

```
---Version info---
Polars: 0.15.5
Index type: UInt32
Platform: macOS-11.7-arm64-arm-64bit
Python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:48:25)
[Clang 14.0.6 ]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ghuls** [comment]
Closed by #5824.
