### ISSUE TITLE
Map DataFrame Column using Python Dicts

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#5822]
### Problem description

similar to here (#5815) but much more general it would be great if you could map column values of any type to any type with simple python dicts.

A simple but unfortunately rather slow solution is using `apply`.

A much faster but also more verbose solution is creating another DataFrame and using `join`. ([link](https://stackoverflow.com/questions/74779644/mapping-a-python-dict-to-a-polars-series/74782121#74782121))

Some examples:
```python
COUNTRY_CODE_MAPPING = {
    "DE": "Germany",
    "FR": "France",
    "US": "United States",
}

STOCK_CODE_MAPPING = {
    -1: "On Request",
    0: "Out of Stock",
    1: "In Stock",
}

df = pl.DataFrame({
    "country_code": ["DE", "FR", "US", "FR"],
    "stock_code": [1, 0, -1, 1],
})

# using apply (works but not efficient/fast)
df.with_columns([
    pl.col("country_code").apply(COUNTRY_CODE_MAPPING.get).alias("country"),
    pl.col("stock_code").apply(STOCK_CODE_MAPPING.get).alias("stock"),
])

# using pandas
df.assign(
    country=df["country_code"].map(COUNTRY_CODE_MAPPING),
    stock=df["stock_code"].map(STOCK_CODE_MAPPING),
)
```

I would love to see a `map` function in polars similar to pandas `map` function. I think this is a very useful and common operation. Maybe also add a `default_value` if the key is not found in the dict (although this can be fixed with an additional `fill_null`).

What do you think? =)

**Comment by thomasfrederikhoeck** [comment]
To weigh in I use the `.map` heavily in pandas with a `dict` so this would be nice to have in polars.

**Comment by mcrumiller** [comment]
This is a super-often requested feature, and there are many such questions Stackoverfllow. [here](https://stackoverflow.com/a/74782121/3681427) is Ritchie's canonical answer. One problem is that [`pl.Expr.map`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.map.html) is already defined.

I think having this as a shortcut to a left join would be super useful; it's probably one of my most commonly-used operations, and including a default value for missing values in the map would be even better.

```python
df = pl.DataFrame({
    'a': ['1', '1', '2', '2', '3', '3', '4', '5']
})

df.select([
    pl.col('a').map(
        {
            '1': "one",
            '2': "two",
            '3': "three"
        },
        keep=True          # some parameter to say "leave unchanged if not in map"
        default="unmapped" # an alternative parameter to specify value for all other values
    )
])
```
shape: (8, 1)
┌───────┐    
│ a     │    
│ ---   │    
│ str   │    
╞═══════╡    
│ one   │    
├╌╌╌╌╌╌╌┤    
│ one   │    
├╌╌╌╌╌╌╌┤    
│ two   │    
├╌╌╌╌╌╌╌┤    
│ two   │    
├╌╌╌╌╌╌╌┤    
│ three │    
├╌╌╌╌╌╌╌┤    
│ three │    
├╌╌╌╌╌╌╌┤
│ 4     │
├╌╌╌╌╌╌╌┤
│ 5     │
└───────┘
```

```

**Comment by ghuls** [comment]
A WIP implementation: https://github.com/pola-rs/polars/pull/5899

**Comment by ghuls** [comment]
Closed by https://github.com/pola-rs/polars/pull/5899.
