### ISSUE TITLE
casting nulls of any data type

### ISSUE THREAD

**Issue by Guillermogsjc** [pola-rs/polars#5826]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi, 

errors found on `pl.cast` when casting pl.Series with only null values, not really a bug, Looks like Arrow limitation

### Reproducible example

```python
df = pl.DataFrame(data=[pl.Series("a", [None],  dtype=pl.Utf8)])
df.with_column(pl.col("a").cast(pl.Boolean))
```

### Expected behavior

runs into:

```python
ArrowErrorException: NotYetImplemented("Casting from LargeUtf8 to Boolean not supported")
```

Any cast from a `pl.Series([None], dtype=#ANY#)` into any data type would be better if it is supported consistently. This case looks like an Arrow limitation, but maybe it is possible to fix at Rust (would be best as propagates into  higher level wrapper libs) or Python level.

For this case an easy workaround is to go by `pl.Uint8`  (in case nunique is 0, meaning only nulls on the Series):

```python
df.with_column(pl.col("a").cast(pl.UInt8).cast(pl.Boolean))
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-5.10.0-19-amd64-x86_64-with-glibc2.31
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.7.1
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2
```

</details>

**Comment by Guillermogsjc** [comment]
here is a gist with the full scope of the issue https://gist.github.com/Guillermogsjc/9078e7a832f336d657202088a41633f7, there are two main points :

- create a pl.Series of nulls in any datatype
- cast a pl.Series of nulls of any datatype into any datatype

This is an important requirement to have to allow the use of polars in data engineering ETL (specifically on outputs), **as you can have tables that have columns full of null and need to cast them into a constant schema before writing into parquet**.

**Comment by ritchie46** [comment]
I don't think a cast should succeed if all values are null. We don't know how to cast a utf8 to boolean so we fail the cast. This should not be influenced by missing values.

**Comment by Guillermogsjc** [comment]
This library is exceptional, there is no doubt about the performance goals achieved, and congratulations @ritchie46 for what you are building here, it is astonishing.

To cast columns full of nulls into any data type, is a trivial and fundamental need in data engineering processes, where you have constant output schemes for the tables, and need to type them for the consumer of those tables (for example a BigQuery or Athena crawler from a parquet in a bucket), regardless of being all null columns or not.

One of the needs to become perfect in the typing/casting system, is the capacity of casting a series of any type consisting about nulls into any datatype, despite being possible in arrow, or not. In a Rustacean mind also it fits with the Option<MY_TYPE, None> idea, and the idea to allow any mapping between None variants of the series datatype enum.

It would be possible to put a layer on top of casting functions for those cases where the origin series verifies `.nunique() == 0`, to unlock this full-of-nulls casting cases.

**Comment by ritchie46** [comment]
Alright. It is added in #5933

**Comment by Guillermogsjc** [comment]
thank you @ritchie46 for the merge, saw the particular case fix. It would be really nice to have the general behaviour, satisfying for every existing dtype those two very simple and basic casting tests:

```python
import polars as pl

# example struct dtype
struct_dtype = pl.Struct([
    pl.Field("n", dtype=pl.Int64),
    pl.Field("o", dtype=pl.Float64),
    pl.Field("l", dtype=pl.Utf8)
])

DTYPE_LIST = [    
    pl.Unknown,
    pl.Float32,
    pl.Float64,
    pl.Int8,
    pl.Int16,
    pl.Int32,
    pl.Int64,
    pl.UInt8,
    pl.UInt16,
    pl.UInt32,
    pl.UInt64,
    pl.Date,
    pl.Datetime,
    pl.Duration,
    pl.Time,
    pl.Boolean,
    pl.Binary,
    pl.Categorical,
    pl.Object,
    pl.Utf8,    
    pl.List(pl.Utf8),
    pl.List(pl.Boolean),
    pl.List(pl.Float64),
    struct_dtype    
]

def test_null_series_generation():
    for dtype in DTYPE_LIST:   
        pl.Series("a", [None],  dtype=dtype)

def test_cast_null_series_into_any_type():    
    for dtype_origin in DTYPE_LIST:
        for dtype_destiny in DTYPE_LIST:
            a = pl.Series("a", [None],  dtype=dtype_origin)
            a.cast(dtype_destiny)
```

I know it is a major change, this is why maybe this would be nice to be dealed as a layer not specific solutions as the first example I sent.

Kind regards.

**Comment by ritchie46** [comment]
Isn't it general at the moment?

**Comment by Guillermogsjc** [comment]
Oh, sorry, focused on test part and missed the code on polars/polars-core/src/series/mod.rs . Great, thanks very much, it is rounding casting system very nicely.
