### ISSUE TITLE
Python says that polars has no to_pandas() function

### ISSUE THREAD

**Issue by kgguliev** [pola-rs/polars#5828]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I started learning ```polars``` because I can not make it anymore with ```pandas``` (it feels so bad after ```dplyr``` and ```data.table``` pipelines in R). Trying to convert ```polars``` dataframe object to ```pandas``` dataframe object to plot something in ```seaborn```. Python says that I cannot do such thing referring to PyArrow or even telling me that there is no such attribute in polars. 

### Reproducible example

```python
import polars as pl
import numpy as np
import pandas as pd
import pyarrow as pa

np.random.seed(123)
sample = pl.DataFrame({
 'country'   : ['NZ', 'JPN', 'DEU', 'ITA', 'ESP'],
 'price'     : [120, 21, 23, 456, 2102],
 'rand_index': np.random.rand(5)
}
)

sample.to_pandas()
# ModuleNotFoundError: pa.Table requires 'pyarrow' module to be installed

pl.to_pandas(sample)
# AttributeError: module 'polars' has no attribute 'to_pandas'
```

### Expected behavior

converting object's type to pandas

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Windows-10-10.0.18362-SP0
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.21.5
fsspec: 2022.02.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by ritchie46** [comment]
As the first error says you need to install `pyarrow` to use `to_pandas`.

Try `pip install polars[pyarrow]`

**Comment by zundertj** [comment]
I cannot reproduce this error.

@kgguliev : your details suggest pyarrow is installed in the same session, so it is odd that pyarrow is not loaded properly according to the message. What happens when you do `import pyarrow`?

**Comment by kgguliev** [comment]
> I cannot reproduce this error.
> 
> @kgguliev : your details suggest pyarrow is installed in the same session, so it is odd that pyarrow is not loaded properly according to the message. What happens when you do `import pyarrow`?

@zundertj actually nothing happens, module imports and I can work with him.

**Comment by kgguliev** [comment]
> As the first error says you need to install `pyarrow` to use `to_pandas`.
> 
> Try `pip install polars[pyarrow]`

@ritchie46 ```Requirement already satisfied: polars[pyarrow] in c:\users\{user_name}\anaconda3\lib\site-packages (0.15.6)```

**Comment by kgguliev** [comment]
Hmmm, I have updated ipykernel and installed ```pathlib``` module. I do not which one of these actions but they worked for me and now I am able to turn polars table to pandas table. Anyway, thanks everyone for help, closing the issue.
