### ISSUE TITLE
pl.col("bool_col").mean() returns null

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/polars#5839]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When you have a bool col and you try to get the mean of it in a select context, you get null.

#833 fixes this for Series but apparently not for expressions.

### Reproducible example

```python
import polars as pl
x = pl.DataFrame(
    {
        "a": [True, False],
    }
)
print(x.select(pl.col("a").mean()))
```
output:
```
shape: (1, 1)
┌──────┐
│ a    │
│ ---  │
│ bool │
╞══════╡
│ null │
└──────┘
pl.UInt8

```

### Expected behavior

```
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 0.5 │
└─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-5.15.57-2-MANJARO-x86_64-with-glibc2.35
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
This was added 4 days ago: #5806
