### ISSUE TITLE
Support for Decimal Types

### ISSUE THREAD

**Issue by sa-** [pola-rs/polars#5853]
### Problem description

I was trying out polar's new delta reader and ran into this error using `pl.scan_delta(...)`

`Arrow datatype Decimal(18, 5) not supported by Polars. You probably need to activate that data-type feature`

I've installed polars with `pip install polars[all]` so it's unlikely that the feature is missing. It would be nice if polars could support this. 

Related issue: https://github.com/pola-rs/polars/issues/4104

**Comment by zundertj** [comment]
Closing in favor of #4104 . Please comment and/or upvote there if you want to add your support for `Decimal` data type.
