### ISSUE TITLE
Wrong results pushing down formula with parquet files when statistics are used

### ISSUE THREAD

**Issue by gfmartins** [pola-rs/polars#5855]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Bad behavior when pushing down an formula using parquet files when the file is created with statistics.

In the example bellow I use pyarrow to write the files, however, the behavior is the same if not using it.

If the predicate isn't pushed down, everything works has expected, regardless of how the file was created.

Strangely, if I change one value in the dataframe that i first use in the example bellow, it suddenly works. So it's not an "consistent" error.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    data = [
        ('a', 2),
        ('b', 2),
        ('c', 3.1),
        ('d', 4),
        ('3', 5),
    ],
    columns = ['a','b'],)

df.write_parquet('no_stats.parquet', use_pyarrow=True, statistics=False)
df.write_parquet('with_stats.parquet', use_pyarrow=True, statistics=True)

e = ((pl.col('b')/2.0)<=1.9)

x1 = pl.scan_parquet('no_stats.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

x2 = pl.scan_parquet('with_stats.parquet')
y = x2.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

#this does work - if we change the first dataframe row to 1.9 instead of 2:
df = pl.DataFrame(
    data = [
        ('a', 1.9), #<-------
        ('b', 2),
        ('c', 3.1),
        ('d', 4),
        ('3', 5),
    ],
    columns = ['a','b'],)

df.write_parquet('no_stats_19.parquet', use_pyarrow=True, statistics=False)
df.write_parquet('with_stats_19.parquet', use_pyarrow=True, statistics=True)

e = ((pl.col('b')/2.0)<=1.9)

x1 = pl.scan_parquet('no_stats_19.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

x2 = pl.scan_parquet('with_stats_19.parquet')
y = x2.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)
```

### Expected behavior

.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
None
```

</details>

**Comment by gr-alecz** [comment]
This appears to occur with `use_pyarrow=False` as well

**Comment by gfmartins** [comment]
I think that I have an idea on what is going on.

given the expression: 
`e = ((pl.col('b')/2.0)<=1.9)`

when the predicate is pushed down, I think that it filters out each row group by the min max values. Based on the right side of the equation. **In this case every row group with a min greater than 1.9 is excluded.** This isn't the expected behavior, because we are not doing a comparison to the base column but to something that is built from that column values.

One possible solution is to apply the same formula to the min max value of each row group, and compare those. However I'm not sure that:

given any function F (using sqrt, power, exp, combinations, etc..., and only one column in the expression), 
we have that F(min row group) is always less or equal to F(value), given that "min row group" <= "value"

this example better reproduces it:
(sorry for using pandas, but it was the fastest way for me to create a parquet file with small row group size for testing)

`import polars as pl
import pandas as pd

data = pd.DataFrame(data={'a': ["a", "b", "c", "d", "e"], 
                            "b":[1.9,2,2, 2,5]                           
                           })

data.to_parquet("filename.parquet", row_group_size=2, engine="pyarrow") #it creates stats

e = ((pl.col('b')/2.0)<=1.9)

x1 = pl.scan_parquet('filename.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

x1 = pl.scan_parquet('filename.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=False)
print(z)`
