### ISSUE TITLE
Creating DataFrame from list of dictionaries when first 50 values of dictionary field are null

### ISSUE THREAD

**Issue by MAlbergaria** [pola-rs/polars#5857]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi,

When creating a DataFrame from a list of dictionaries, it seems like the columns data types are defined based on the first 50 dictionaries. 

As such, when a field of the dictionaries is null in the first 50 dictionaries, polars sets the column datatype to boolean, which leads to the following error if any of the following dictionaries has a value different of null or boolean.

`PanicException: dtype Utf8("Teste obs") not implemented`

This issue is happening when creating the DataFrame using, both, the constructor and `pl.from_dicts()`.

A workaround as been added to the Expected behavior section, consisting in changing the list of dictionaries to a dictionary where each value is a list.

### Reproducible example

```python
import polars as pl

for i in range(1, 100):
    row = {"A": None}

    dicts = [row for _ in range(i)]
    dicts.append({"A": "Teste obs"})
    
    content_df = pl.DataFrame(dicts)
```

### Expected behavior

```python
import polars as pl

for i in range(1, 100):
    row = {"A": None}
    
    dicts = [row for _ in range(i)]
    dicts.append({"A": "Teste obs"})
    
    # Line added to convert list of dictionaries to dictionary where each key has a list
    dicts = {k: [dic[k] for dic in dicts] for k in dicts[0]} 
    content_df = pl.DataFrame(dicts)
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
That's why `pl.from_dicts` has an `infer_schema_length`.

**Comment by ghuls** [comment]
```python
# Set infer_schema_length to None to scan all dicts (or to e.g. 1000, to scan the first thousand only)
content_df = pl.from_dicts(dicts, infer_schema_length=None)
```

**Comment by ritchie46** [comment]
I will close this as we have logic in place to deal with this accordingly.
