### ISSUE TITLE
Grouping over an ID column whose values are all null causes a PanicException

### ISSUE THREAD

**Issue by ML-BCB** [pola-rs/polars#5868]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The below error message occurs when you try and group & aggregate over a group whose subset only contains null / None values.

It does not error in polars version 0.15.2.

PanicException: called Result::unwrap() on an Err value: OutOfSpec("validity mask length must match the number of values") 

### Reproducible example

```python
ids = np.random.randint(0,10,100)
values = np.random.random_sample(100)
df = pl.DataFrame({'id':ids,'value':values})
df = df.with_column(
    pl.when(pl.col('id')==7).then(None).otherwise(pl.col('value')).alias('value'))

df.with_column(
  pl.col('value').max().over('id')
)
```

### Expected behavior

Dataframe shold be returned with nulls in the relevant columns where the group is all null, along with the relevant values in all other groupings, and not error. This is what happens in 0.15.2.

### Installed versions

<details>

---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
Python: 3.9.13 (main, May 23 2022, 22:01:06) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2

</details>

**Comment by ritchie46** [comment]
Even simpler:

```python

df = pl.DataFrame({
    "value": [None, 2],
    "id": [None, 1]
})

df.with_column(
  pl.col('value').max().over('id')
)
```
