### ISSUE TITLE
Join "quality control"

### ISSUE THREAD

**Issue by eutwt** [pola-rs/polars#5883]
### Problem description

It would be great if you could optionally prevent (throw an error for) a join "expand"ing your data. For me personally, 90% of that time that happens it's a mistake. Actually, right now my code just has a "check_unique" function call after each join for this purpose, which obviously involves much more computation than what you'd need if it was part of the join process.

As inspiration, here's a description of the interface used in the dev version of the R package dplyr:

> `multiple` is a new argument [to the join functions] for controlling what happens when a row in x matches multiple rows in y. It allows `c("all", "first", "last", "warning", "error")`. The default is `NULL`, which uses "warning" for equi and rolling joins, where multiple matches are surprising, and "all" for cross joins and when there is at least 1 non-equi join condition, where multiple matches are expected. This is a change from the current CRAN dplyr behavior, which never warns.

https://github.com/tidyverse/dplyr/pull/5910

**Comment by thomasfrederikhoeck** [comment]
Another way to go about is like pandas which have saved me befoe using `validate`:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

> validate: str, optional
If specified, checks if merge is of specified type.
>
>“one_to_one” or “1:1”: check if merge keys are unique in both left and right datasets.
>
>“one_to_many” or “1:m”: check if merge keys are unique in left dataset.
>
>“many_to_one” or “m:1”: check if merge keys are unique in right dataset.
>
>“many_to_many” or “m:m”: allowed, but does not result in checks.

**Comment by zundertj** [comment]
Hello, this is an excellent suggestion, but has been made before, see #2377. Please continue the conversation in that thread.
