### ISSUE TITLE
Dataframe printing is weird on WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#5894]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Linux's Polars DataFrame on the console is weird. On windows works just fine.

Sorry for reporting this small bug, my intentions is not really to solve this issue but just to make polars team aware of it.

### Reproducible example

```python
df_stock = pl.DataFrame(
    {
        "date_time": pl.date_range(
            low=datetime(2000, 1, 1, 0, 0),
            high=datetime(2023, 1, 1, 0, 0),
            interval="1d",
        )
    }
)
print(df_stock)
```

### Expected behavior

Out[2]: 
shape: (8402, 1)
┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2000-01-01 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-01-02 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-01-03 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-01-04 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-12-29 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-12-30 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-12-31 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-01-01 00:00:00 │
└─────────────────────┘

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) 
[GCC 10.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>```

</details>

**Comment by zundertj** [comment]
Could you also show the erroneous output? You have only the expected behaviour now in your post.

Which console are you referring to? I tried, on WSL, to reproduce in the terminal (MobaXTerm) and in the VSCode terminal (not sure if this is a sort emulator), and it looks fine to me.

**Comment by arturdaraujo** [comment]
There is nothing wrong with the output, just the dataset format horizontal lines were weird. I got an explanation on https://github.com/pola-rs/polars/issues/5896. I will close this because, it is already solved. Thanks for the reply.
