### ISSUE TITLE
New DataFrame design format

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#5896]
### Problem description

@alexander-beedie recently made the feature of printing the shape below the DataFrame optional like this: `pl.Config.set_tbl_dataframe_shape_below(True)`.  This was great.

I would suggest a similar solution for HOW the DataFrame is printed. The DataFrame columns are weird in Linux and this would make it cleaner and less verbose for users that prefer a practical, simpler look in general.

```
import time
import polars as pl
from datetime import datetime

df_stock = pl.DataFrame(
    {
        "date_time": pl.date_range(
            low=datetime(2000, 1, 1, 0, 0),
            high=datetime(2023, 1, 1, 0, 0),
            interval="1d",
        ).shuffle(seed=0)
    }
)
print(df_stock)

shape: (8402, 1)
┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2008-05-13 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-11-24 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2005-08-09 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2009-09-04 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-06-30 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-08-18 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-02-06 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-04-16 00:00:00 │
└─────────────────────┘

```
This table above uses 24 lines.

I suggest something like this:

```
`pl.Config.set_tbl_dataframe_shape_lean(True)`

print(df_stock)

shape: (8402, 1)
┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2008-05-13 00:00:00 │
│ 2000-11-24 00:00:00 │
│ 2005-08-09 00:00:00 │
│ 2009-09-04 00:00:00 │
│ ...                 │
│ 2010-06-30 00:00:00 │
│ 2010-08-18 00:00:00 │
│ 2010-02-06 00:00:00 │
│ 2010-04-16 00:00:00 │
└─────────────────────┘
```
This table uses 15 lines, ~40% less.

(Discussion for default)
Once again, sorry for being picky about this feature but in general this can improve the usability of the package. I strongly advocate that being the default (as well as the shape being printed below).  Once again, I suggest this because printing the table is problematic on Linux and because I think this format serves the user better. I hope I did contribute somehow.

So my suggestion for the default table would be something like this but I'm aware that more discussion is needed:

```
print(df_stock)

┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2008-05-13 00:00:00 │
│ 2000-11-24 00:00:00 │
│ 2005-08-09 00:00:00 │
│ 2009-09-04 00:00:00 │
│ ...                 │
│ 2010-06-30 00:00:00 │
│ 2010-08-18 00:00:00 │
│ 2010-02-06 00:00:00 │
│ 2010-04-16 00:00:00 │
└─────────────────────┘
shape: (8402, 1)

```

**Comment by alexander-beedie** [comment]
@arturdaraujo actually I have already added this to polars (via the underlying comfy_table library), as I also prefer a more compact representation... ;)

See: https://github.com/Nukesor/comfy-table/pull/94.

You can enable it in polars like so:
```python
pl.Config.set_tbl_formatting("UTF8_FULL_CONDENSED")
```

**Comment by arturdaraujo** [comment]
Thanks for the feedback, that's awesome!

**Comment by alexander-beedie** [comment]
FYI: there are a range of available formats (listed in the `pl.Config.set_tbl_formatting` docstring):

* `ASCII_FULL`: ASCII, borders / lines.
* `ASCII_NO_BORDERS`: ASCII, no borders.
* `ASCII_BORDERS_ONLY`: ASCII, borders only.
* `ASCII_BORDERS_ONLY_CONDENSED`: ASCII, borders only, dense row spacing.
* `ASCII_HORIZONTAL_ONLY`: ASCII, horizontal lines only.
* `ASCII_MARKDOWN`: ASCII, Markdown compatible.
* `UTF8_FULL`: UTF8, with all borders and lines (default).
* `UTF8_FULL_CONDENSED`: Same as UTF8_FULL, with dense row spacing.
* `UTF8_NO_BORDERS`: UTF8, no borders.
* `UTF8_BORDERS_ONLY`: UTF8, borders only.
* `UTF8_HORIZONTAL_ONLY`: UTF8, horizontal lines only.
* `NOTHING`: No borders or other lines.

**Comment by arturdaraujo** [comment]
This level of customization is great, I was not aware

**Comment by alexander-beedie** [comment]
> This level of customization is great, I was not aware

You're welcome! `pl.Config` is full of interesting options now, as everyone has different expectations/preferences... Have a look at the docs for some more options/inspiration ;)

https://pola-rs.github.io/polars/py-polars/html/reference/config.html

**Comment by arturdaraujo** [comment]
Just to give feedback, UTF8_FULL_CONDENSED works fine on Linux env.
