### ISSUE TITLE
An oddly specific set of instructions to cause a panic when globbing, aggregating and streaming

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/polars#5900]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I promise all of the steps below seem to be necessary:

1. **Scan a glob of files.** It needs to be a glob and not a single file. (I have tried this with both parquet and csv).
2. **Select a subset of the columns and aggregate at least one of them.** By "aggregate" I mean use a method like `.sum` or `.max` that reduces the column to a single value. If you select all the columns from the file (with or without aggregation) or if you don't aggregate any columns then there is no panic
3. **Call** `.collect(streaming=True)`
4. **Panic!**
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/polars/polars/polars/polars-utils/src/arena.rs:80:9
```

Note: while these steps are oddly specific, this exact workflow is  pretty common if you think about.

### Reproducible example

```python
import polars as pl
# my_tmp_dir can just be a new empty directory
dest = "my_tmp_dir/tmp.pq"
pl.DataFrame({"a": [1,2,3], "b": [3, 4, 5], "c": [4,5,6]}).write_parquet(dest)
pl.scan_parquet("my_tmp_dir/*.pq").select(pl.col("a").sum()).collect(streaming=True)
# you can play around with selecting and aggregating all the columns, not doing any aggregation etc
```

### Expected behavior

No panic

### Installed versions

<details>

```
---Version info---
Polars: 0.15.8
Index type: UInt32
Platform: Linux-5.15.57-2-MANJARO-x86_64-with-glibc2.35
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by kevinheavey** [comment]
The panic happens at `lp_arena.get` here https://github.com/pola-rs/polars/blob/8e0d8131f68f1800a77ebe6eb51de988c8bb40a0/polars/polars-lazy/src/physical_plan/streaming/convert.rs#L367

**Comment by ritchie46** [comment]
Thanks, Will investigate.
