### ISSUE TITLE
Incorret read of CSV files when all values are quoted

### ISSUE THREAD

**Issue by rantos9** [pola-rs/polars#5906]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If a CSV file has all fields surrounded with the quotechar then missing values of numerical columns are misinterpreted as an empty string instead of a NaN.

### Reproducible example

```python
import pandas as pd
import polars as pl

csv = '''"col1"|"col2"|"col3"|"col4"
"0"|"Free text with a line
break"|"123"|"456"
"1"|"Free text without a linebreak"|""|"789"
"0"|"Free text with 
two 
linebreaks"|"101112"|"131415"'''

with open('example.csv','w') as f:
    f.write(csv)

df = pd.read_csv('example.csv', sep='|')

df

df.dtypes

pl_df = pl.read_csv('example.csv', sep='|')

pl_df

pl_df.dtypes
```

### Expected behavior

Expected the same behavior as pandas. Col3 should be parsed as integers and the second value should be a NaN instead of an empty string

### Installed versions

<details>

```
---Version info---
Polars: 0.15.8
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.9.16 (main, Dec  9 2022, 12:10:07) 
[Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.2
numpy: 1.24.0
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ghuls** [comment]
As far as I know, quoted field should be interpreted as strings.

**Comment by ritchie46** [comment]
Yeah, the inferred schema is up for debate. Polars defaults to string if it encounters quotes. However, fields may be quoted, so we need to escape properly. 

With the fix coming up, this runs as expected:

```python
pl.read_csv(..., sep="|", dtypes={"col3": pl.Int32})
```
