### ISSUE TITLE
`diff()` does not cast unsigned int to int

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#5923]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using `diff()` on a column of unsigned ints causes wrap-around when the difference between two rows is negative. I guess there are cases where this is what you would want to compute, but it is not intuitive. For example:

```python
df = pl.DataFrame(
    {
        "a": [20, 10, 30],
    }
)

df.select(pl.col("a").cast(pl.UInt64).diff())

shape: (3, 1)
┌──────────────────────┐
│ a                    │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ null                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 18446744073709551606 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 20                   │
└──────────────────────┘
```

This is also confusing because `pct_change` correctly compute a negative percent change on this example:

```python
df.select(pl.col("a").cast(pl.UInt64).pct_change())

shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ null │
├╌╌╌╌╌╌┤
│ -0.5 │
├╌╌╌╌╌╌┤
│ 2.0  │
└──────┘
```

This seems dangerous, since it is easy to be unknowingly handed data that stores an integer column as unsigned.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [20, 10, 30],
    }
)

df.select(pl.col("a").cast(pl.UInt64).diff())
```

### Expected behavior

 I think that the result should be the intuitive one, namely
```python
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ null │
├╌╌╌╌╌╌┤
│ -10  │
├╌╌╌╌╌╌┤
│ 20   │
└──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.8
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.8.12 (default, Oct 18 2021, 20:31:01) 
[Clang 10.0.1 (clang-1001.0.46.4)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.01.0
connectorx: 0.3.0
xlsx2csv: <not installed>
matplotlib: 3.6.2

```

</details>

**Comment by zundertj** [comment]
Closing in favor of the more generic discussion about using unsigned integers in the Polars api in #4990. Please comment and/or upvote there.

**Comment by ritchie46** [comment]
I think for diff it make sense to change output type to signed. I will take this one.
