### ISSUE TITLE
Iterate over rows of dataframe as namedtuples

### ISSUE THREAD

**Issue by pstorozenko** [pola-rs/polars#5935]
### Problem description

In particular cases it's useful to iterate with for loop over rows of dataframe and do something based on rows.
Right now it's possible to do with `df.rows()` but it requires programmer to remember which column has which index:

```python
for fname, target, split in df.rows():
  ...
```

It's also possible with `df.to_struct()` but it requires programmer to provide a dummy name for column, and I don't know how (in)efficient it is, i.e.

```python
for row in df.to_struct("_"):
  fname, target, split = row["file_name"], row["target"], row["split"]
  ...
```

I thought it might be useful to have some function that will yield named tuples so we can do:
```python
for row in df.rows_as_namedtuples():
  fname, target, split = row["file_name"], row["target"], row["split"]
  ...
```

What do you think?

**Comment by stinodego** [comment]
I think this would be a nice addition. There is no namedtuple in PyO3, but we can probably define a `namedtuple` in the Python function. Should be easy enough to implement.

**Comment by pstorozenko** [comment]
With a tiny hints I'm happy to code it in python.

I guess function should be located close to here: 

https://github.com/pstorozenko/polars/blob/8e335cffb30809346b941361ba690ec1cd0f98e0/py-polars/polars/internals/dataframe/frame.py#L6601-L6618

I'd have to know how the function should be named to follow your naming convention. 
Or maybe you prefer to add parameter `as_named_tuples: bool` to `rows` function?

**Comment by stinodego** [comment]
Eventually I'd like the existing `DataFrame.rows()` method to be replaced by something like `iterrows()` which returns an iterable of namedtuples. I'd need to do some research though on the Rust side if we can return an iterable instead of a list.

For now I'd propose to create a new `iterrows()` method that calls the same underlying Rust function as `rows()`, but defines a namedtuple `Row` based on the DataFrame column names, and then yields each row.

**Comment by ritchie46** [comment]
The distinction between `rows` and `iterrows` is something that is good to have IMO. It is easier to optimize the `rows` variant as the (currently) the `iterrows` goes to many layers of indirection (e.g. slow).

With regard to namedtuples, I was thinking we should have a separate method pair for that. `namedtuples` are twice as expensive as what we return at the moment as they need to heap allocate the name of the column for every element. Which is fine, if you need it, but I don't want to pay that when someone only wants the rows without a name.

**Comment by stinodego** [comment]
> The distinction between `rows` and `iterrows` is something that is good to have IMO. It is easier to optimize the `rows` variant as the (currently) the `iterrows` goes to many layers of indirection (e.g. slow).

Fair enough!

> With regard to namedtuples, I was thinking we should have a separate method pair for that. `namedtuples` are twice as expensive as what we return at the moment as they need to heap allocate the name of the column for every element. Which is fine, if you need it, but I don't want to pay that when someone only wants the rows without a name.

We could just add a `named` parameter to the existing pair of methods; then the API (and speed) stays the same for the existing functionality, but people can pass `iterrows(named=True)` to get the extra functionality at the cost of some performance. I think that's best from a usability standpoint.

**Comment by ritchie46** [comment]
> We could just add a named parameter to the existing pair of methods; then the API (and speed) stays the same for the existing functionality, but people can pass iterrows(named=True) to get the extra functionality at the cost of some performance. I think that's best from a usability standpoint.

Sounds good. I was thinking of a different set of methods as we change the return type, but a `named` argument and an overload seems also fine.
