### ISSUE TITLE
Add filesystem parameter to read_*

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#5939]
### Problem description

I would like it if there were a filesystem option in the read functions.  This is to be consistent with how pyarrow's read_table function works but also to make reading and writing have the same address.

For example, say I have a file system

`abfs = fsspec.filesystem('abfss', connection_string=os.environ['abfs_creds'])`

I can write a file like this:

```
filepath="rootdir/dir1/somefile.parquet"
with abfs.open(filepath, "wb") as ff:
    df.write_parquet(ff)
```

but then if I want to reopen the file I have to do:

`pl.read_parquet(f"abfss://{filepath}", storage_options=abfs.storage_options)`

It'd be nice if I could do `pl.read_parquet(filepath, filesystem=abfs)`

Obviously I can make my own helper function to do this but it might be helpful for it to be consistent with pyarrow's fsspec syntax.

**Comment by zundertj** [comment]
Wouldn't it make more sense to have a single argument?

```python
with abfs.open(filepath, "rb") as ff:
    df = pl.read_parquet(ff)
```
That is cleaner to me.

Digging in the source, it seems we should be able to support something like this quite easily as most (all?) IO methods parse the file argument using `_prepare_file_arg`, and that can return amongst others the output of `fsspec.open(...)`. So it would be a matter of detecting an fsspec object being passed in, and simply returning that (I hope).

**Comment by deanm0000** [comment]
What if, in read_parquet (and others), you allow for a filesystem parameter that then gets passed to `_prepare_file_arg` as a kwarg.  Then you can do

```
if "filesystem" in kwargs.keys():
    fs=kwargs['filesystem']
else:
    fs=fsspec
```

Then replace `fsspec.open` with `fs.open`
