### ISSUE TITLE
Solution for checking system OS to accurately printing polars DataFrame format.

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#5941]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description
The wrong default table format for Linux. Set pl.Config.set_tbl_formatting when importing.

# Solution:
A general solution for differentiating the os systems is here:
```
if sys.platform.startswith("linux"):  # could be "linux", "linux2", "linux3", ...
    # linux
elif sys.platform == "darwin":
    # MAC OS X
elif os.name == "nt":
    # Windows, Cygwin, etc. (either 32-bit or 64-bit)
```
I suggest the code below be implemented every time when printing a data frame or just one time when importing Polars (which would be ideal, it would run only once. But any solution is okay since the runtime is minimal). I'm also reproducing the time to run this code to prove that the time is negligible. The packages are all from Python Standard Library (built-in packages).

Here is what I suggest:
```
if sys.platform.startswith("linux"):  # could be "linux", "linux2", "linux3", ...
    pl.Config.set_ascii_tables(True)  
```
I also mention similar problem in https://github.com/pola-rs/polars/issues/5942 for changing the default format.

References:
- https://stackoverflow.com/questions/1854/how-to-identify-which-os-python-is-running-on
- https://docs.python.org/3/library/
-   ```
    %timeit os.name
    32 ns ± 0.285 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
    
    %timeit platform.system()
    124 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
    
    %timeit sys.platform
    33.1 ns ± 0.542 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
    ```


### Reproducible example

```python
import polars as pl
from datetime import datetime

df_stock = pl.DataFrame(
    {
        "date_time": pl.date_range(
            low=datetime(2000, 1, 1, 0, 0),
            high=datetime(2023, 1, 1, 0, 0),
            interval="1d",
        ).shuffle(seed=0)
    }
)
print(df_stock)

shape: (8402, 1)
┌─────────────────────╌╌╌╌┐
│ date_time           │
│ ---                     │
│ datetime[μs]        │
╞═════════════════════╌╌╌╌╡
│ 2008-05-13 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-11-24 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2005-08-09 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2009-09-04 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-06-30 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-08-18 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-02-06 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-04-16 00:00:00 │
└─────────────────────╌╌╌╌┘
```

### Expected behavior

```
print(df_stock)
shape: (8402, 1)
+---------------------+
| date_time           |
| ---                 |
| datetime[μs]        |
+=====================+
| 2008-05-13 00:00:00 |
|---------------------|
| 2000-11-24 00:00:00 |
|---------------------|
| 2005-08-09 00:00:00 |
|---------------------|
| 2009-09-04 00:00:00 |
|---------------------|
| ...                 |
|---------------------|
| 2010-06-30 00:00:00 |
|---------------------|
| 2010-08-18 00:00:00 |
|---------------------|
| 2010-02-06 00:00:00 |
|---------------------|
| 2010-04-16 00:00:00 |
+---------------------+
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by alexander-beedie** [comment]
@arturdaraujo: FYI - can close this now #5942 is merged (and you noticed that it was WSL causing font-spacing issues).

Happy New Year :)

**Comment by arturdaraujo** [comment]
Thanks! Happy New Year :)
