### ISSUE TITLE
pl.Config.set_tbl_formatting("UTF8_FULL_CONDENSED") as default for printing Dataframes

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#5942]
### Problem description

The dataframe printing format should be densed. It does not make sense to make the full verbose format. 

Here is an implementation suggestion using only built-in packages and their respective processing times below:
```
if sys.platform.startswith("linux"):  # could be "linux", "linux2", "linux3", ...
    pl.Config.set_tbl_formatting("ASCII_BORDERS_ONLY_CONDENSED")
elif sys.platform == "darwin":
     pl.Config.set_tbl_formatting("UTF8_FULL_CONDENSED")
elif os.name == "not":
    pl.Config.set_tbl_formatting("UTF8_FULL_CONDENSED")
    # Windows, Cygwin, etc. (either 32-bit or 64-bit)

%timeit os.name
32 ns ± 0.285 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

%timeit platform.system()
124 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

%timeit sys.platform
33.1 ns ± 0.542 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
I also created an issue for differentiating systems OS on https://github.com/pola-rs/polars/issues/5941

The current default prints like this:
```
import polars as pl
from datetime import datetime

df_stock = pl.DataFrame(
    {
        "date_time": pl.date_range(
            low=datetime(2000, 1, 1, 0, 0),
            high=datetime(2023, 1, 1, 0, 0),
            interval="1d",
        ).shuffle(seed=0)
    }
)

shape: (8402, 1)
┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2008-05-13 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2000-11-24 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2005-08-09 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2009-09-04 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-06-30 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-08-18 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-02-06 00:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2010-04-16 00:00:00 │
└─────────────────────┘
```
But the default should be this:
```
pl.Config.set_tbl_formatting("UTF8_FULL_CONDENSED")

print(df_stock)
shape: (8402, 1)
┌─────────────────────┐
│ date_time           │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2008-05-13 00:00:00 │
│ 2000-11-24 00:00:00 │
│ 2005-08-09 00:00:00 │
│ 2009-09-04 00:00:00 │
│ ...                 │
│ 2010-06-30 00:00:00 │
│ 2010-08-18 00:00:00 │
│ 2010-02-06 00:00:00 │
│ 2010-04-16 00:00:00 │
└─────────────────────┘

```

**Comment by arturdaraujo** [comment]
Thanks for the try @dandxy89.  I don't know what went wrong with your PR

**Comment by alexander-beedie** [comment]
This seems like it could be an issue with your specific distribution/terminal - I don't have any problems with the UTF8 formats on Linux (but you seem to want ASCII for Linux, above?).

Can you provide a screenshot and/or some distro/terminal details for your Linux machine, so we can at least see what's happening for you? (We're not going to want to change the default to ASCII there, given that there are no other reports of problems).

**Comment by arturdaraujo** [comment]
If you change the default to UTF8_FULL_CONDENSED the problems will appear on bigger dataframes (more columns). However, it is often only small mismatches. UTF8_FULL_CONDENSED is certainly good enough but the ideal would be to check the system for appropriate formatting.

![image](https://user-images.githubusercontent.com/36160235/210079994-765a57c0-3441-4684-bd79-029b493f90fb.png)
```
---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) 
[GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.22.4
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

**Comment by arturdaraujo** [comment]
I just tested it on my Linux Mint 21.1 and it's working fine with utf8 formatting, the problem only occurs on WSL (Windows Subsystem for Linux). Still, I believe that the condensed utf8 formatting should be the default.

**Comment by stinodego** [comment]
Personally, I also prefer the look of the condensed formatting. I am not familiar with the intricacies of the various operating systems, but to me it just looks better.

**Comment by dandxy89** [comment]
Will update my branch this evening once I'm back from the bouldering gym. 

Why did I close it? I realised that the Python test suite wasn't running locally.

**Comment by arturdaraujo** [comment]
@stinodego is not only the looks, it is around 40% less lines and it makes it Polars DataFrame much easier to work with. Pandas, which is the "default" library for DataFrame is even more minimal.

**Comment by stinodego** [comment]
It will probably be a bit of a chore to update all the docstring examples, although I'm sure that's doable with some regex magic. Should probably get sign-off from @ritchie46 before going ahead with that.

**Comment by ritchie46** [comment]
> It will probably be a bit of a chore to update all the docstring examples, although I'm sure that's doable with some regex magic. Should probably get sign-off from @ritchie46 before going ahead with that.

Do you think we can automate such a change? This would be beneficial many times down the road probably.

I have no strong opinions on the format, so a tight format is fine by me. Only on changing the docstrings.

**Comment by alexander-beedie** [comment]
The line-contraction is definitely a font/kerning issue, rather than a polars issue (@arturdaraujo: try switching your font to something like JetBrains Mono, or one of the Menlo Powerline fonts?)

As for a change in default format, I'm definitely biased towards the `UTF8_FULL_CONDENSED`, as I introduced it to comfy-table in the first place, heh. It's a big win space-wise, and I don't think readability suffers.

@ritchie46 / @stinodego: if you want to go ahead, I'll volunteer for the mass docstrings update - how about in conjunction with https://github.com/pola-rs/polars/issues/5513, which would also require a global docstring update? (It's a different issue, but could kill two birds with one stone...)

![regular_expressions](https://user-images.githubusercontent.com/2613171/210088848-16166815-c4cc-4b69-8b05-9290e3d3d1a4.png)

**Comment by stinodego** [comment]
Let's do it! Regarding #5513, I'll leave a comment in that issue.

**Comment by cmdlineluser** [comment]
If it's for the python files - the [ast module](https://docs.python.org/3/library/ast.html#ast.get_docstring) can be used to isolate the docstrings which can be helpful for performing modifications.

```
import ast
import re

def remove_row_sep_from_docstring(
    text,  
    col_sep = "┼",
    dash = "╌",
    row_start = "├",
    row_end = "┤",
    node_types = (ast.ClassDef, ast.FunctionDef)
):

    examples_re = r"(?s)\s*Examples\n\s*-+.+"
    dataframe_re = r"(?s)shape: [(]\d+, \d+[)].+?(?=\n\n|\Z)"
    row_sep_re = rf"\n{row_start}{dash}+(?:{col_sep}{dash}+)*{row_end}(?=\n)"
    
    tree = ast.parse(text)

    for node in ast.walk(tree):
        if isinstance(node, node_types):
            doc = ast.get_docstring(node) or ""
            examples_block = re.search(examples_re, doc)
            if examples_block:
                examples = examples_block.group()
                new_examples = examples
                for df in re.findall(dataframe_re, examples):
                    new_examples = re.sub(
                        re.escape(df),
                        re.sub(row_sep_re, "", df),
                        new_examples
                    )
                doc = re.sub(re.escape(examples), new_examples, doc, count=1)
            # https://github.com/python/cpython/blob/3.11/Lib/ast.py#L294
            node.body[0].value.value = doc
        
    return ast.unparse(tree)
```

The result could then be passed to `black` to fix any lost formatting.

**Comment by ritchie46** [comment]
Does unparse do what I think it does?! 👀 That would be amazing.

**Comment by alexander-beedie** [comment]
Just submitted a corresponding `ASCII_FULL_CONDENSED` [to comfy-table](https://github.com/Nukesor/comfy-table/pull/97); bit of an oversight on my part not doing that when I added `UTF8_FULL_CONDENSED` ... (Don't think we'll need to wait for it though).

**Comment by zundertj** [comment]
FYI, I have looked into alternatives before to auto-update the docstring output, and could only find https://github.com/max-sixty/pytest-accept, but does not seem maintained, and relies on pytest, which does not pick up our custom output checker (which we need for `IGNORE_RESULT`.

The suggestion by @cmdlineluser  to use the ast module is a good one. Note that Python's built-in doctest does not use the ast module, although a popular alternative [xdoctest](https://pypi.org/project/xdoctest/) (insofar doctests are popular) does. Not sure if that has any consequences. I have been tempted before to wrap what we have in our script as a separate package, maybe it becomes worth it if we have auto-update as well. Although I realize that is far off from the very targeted use case here.

**Comment by cmdlineluser** [comment]
`ast.parse` doesn't retain the original formatting:
```
print(ast.unparse(ast.parse("""
def func(
    foo=1,
    bar=2
) -> DataFrame:
    ...
""")))
```
Output:
```
def func(foo=1, bar=2) -> DataFrame:
    ...
```
Also, I just realized it doesn't retain comments either - which makes it a non-solution - d'oh.

**Comment by cmdlineluser** [comment]
Looks like [Parso](https://parso.readthedocs.io/) or [LibCST](https://libcst.readthedocs.io/) are the recommended tools that retain formatting/comments.

```
import itertools
import parso
import re

def remove_row_sep_from_docstring(
    text,
    col_sep = "┼",
    dash = "╌",
    df_start = "┌",
    df_end = "┘",
    row_start = "├",
    row_end = "┤"
):

    examples_re = r"(?s)\s*Examples\n\s*-+.+"
    dataframe_re = (
        rf"(?s)\s*shape: [(]\d+, \d+[)]\s*"
        rf"{df_start}.+?{df_end}"
        rf"(?=\n)"
    )
    row_sep_re = (
        rf"\n\s*{row_start}{dash}+"
        rf"(?:{col_sep}{dash}+)*{row_end}"
        rf"(?=\n)"
    )
    
    tree = parso.parse(text)
    nodes = itertools.chain.from_iterable(
        [tree.iter_classdefs(), tree.iter_funcdefs()])

    for node in nodes:
        docnode = node.get_doc_node()
        if not docnode: 
            continue
        docstring = docnode.value
        examples = re.search(examples_re, docstring)
        if examples:
            old_examples = examples.group()
            new_examples = old_examples
            for df in re.findall(dataframe_re, old_examples):
                new_examples = re.sub(
                    re.escape(df),
                    re.sub(row_sep_re, "", df),
                    new_examples,
                    count=1
                )
            docnode.value = re.sub(
                re.escape(old_examples), 
                new_examples, 
                docstring, 
                count=1
            )

    return tree.get_code()
```

**Comment by alexander-beedie** [comment]
It's a New Year's gift! `comfy-table` made a [release](https://github.com/Nukesor/comfy-table/blob/main/CHANGELOG.md) just for the `ASCII_FULL_CONDENSED` preset I submitted last night. Will pull the latest code, brew a _large_ cup of tea,  and make the update; with a little luck it should be quite painless...

**Comment by alexander-beedie** [comment]
Have done everything now except for reformulating the more involved docstring of [pl.align_frames](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.align_frames.html#polars.align_frames). The tea is finished now, so this one probably calls for a coffee - but then it's all done ;)

**Comment by ritchie46** [comment]
> Have finished updating everything now except for the rather involved docstring of [pl.align_frames](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.align_frames.html#polars.align_frames). The tea is finished, and this one probably calls for a coffee - but then it's all done ;)

Wow, that's fast!

**Comment by alexander-beedie** [comment]
Done - unit/doctests all passed locally, so let's see how it does through CI ... ;)
