### ISSUE TITLE
Add a row iterator

### ISSUE THREAD

**Issue by apcamargo** [pola-rs/polars#5944]
### Problem description

In `pandas` you can iterate over rows using `itertuples` or `iterrows`. I couldn't find a similar functionality in `polars`. It would be really useful to have it implemented.

**Comment by stinodego** [comment]
I think you are looking for [`DataFrame.rows()`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.rows.html#polars.DataFrame.rows).

```python
df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
for row in df.rows():
    print(row)

# Prints:
# (1, 4)
# (2, 5)
# (3, 6)
```

**Comment by apcamargo** [comment]
Oh, that's quite obvious. I think I searched for "iterate" in the docs and didn't find anything. Thanks!

**Comment by stinodego** [comment]
That functionality has been suggested in #5935, we'll look into that. I'll close this for now!
