### ISSUE TITLE
Make some function arguments positional-only

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#5960]
### Problem description

I propose we apply [PEP 570](https://peps.python.org/pep-0570/) in several places in our Python API to make methods take positional-only arguments. 

The PEP does a good job of describing the advantages, but here's the main ones I have in mind:
* Further unifies the way Polars is used. Everyone will use `df.select(['a'])` and not `df.select(exprs=['a'])`.
* Allows renaming arguments without it being a breaking change. I think a lot of methods can have more descriptive argument names, but changing this is a chore due to the possibility of users using it as a keyword argument.

Some examples where I'd like to use this:
* `col`
* `DataFrame.select`
* `DataFrame.filter`
* `DataFrame.str.strip`
* ...

Implementing this would be a one-time breaking change, after which we get some more freedom to manage our public API.

I propose we pick up this issue as part of the release where we drop Python 3.7 support later in 2023.

**Comment by ritchie46** [comment]
Yep, Totally agree. I have done the same the other way around for some methods (keywords only arguments). 

And I am really happy we can remove python 3.7 support in a few months! :tada:

**Comment by deanm0000** [comment]
Are pivot and melt on the table for this change?  Of the examples listed, I use positional only already.

**Comment by stinodego** [comment]
I'm going to close this as I no longer think this is a good idea. It has partly been superseded by allowing star args in `select`, `with_columns`, etc. We can reconsider if a specific problem pops up where this may be helpful.
