### ISSUE TITLE
Optional ability for std() and var() to return NaN on size<=1 groups

### ISSUE THREAD

**Issue by JohnMount** [pola-rs/polars#5963]
### Problem description

I like that the Polars .std() and .var() are, in most cases, computing sample variance and sample standard deviation. I also understand the utility of returning zero for size 1 groups, as it doesn't start ugly NaN propagation. However, it would be really nice if .std() and .var() took an additional optional argument such as "return_nan: bool = False" that if set to True returned NaN on the size 1 groups instead of 0. This would allow Polars behavior be altered to match other systems. It is worth doing, as it saves having to repeat the same .over() condition in trying to apply such a correction at the user side.

**Comment by ljluestc** [comment]
import polars as pl
from polars import DataFrame

def custom_std(self, return_nan=False):
    group_expr = self

    if not return_nan:
        # If return_nan is False, add a condition to replace 0 with NaN for size 1 groups
        group_expr = group_expr.agg(pl.when(group_expr.count() > 1).then(group_expr.std()).otherwise(pl.col(0).cast(float)))

    return group_expr

# Extend the DataFrame class with the custom std function
DataFrame.std = custom_std

# Example usage:
data = {'Group': ['A', 'A', 'B', 'B', 'C'],
        'Value': [1, 2, 3, 4, 5]}

df = DataFrame(data)

# Compute standard deviation with optional return_nan argument
result_df = df.groupby('Group').agg(df['Value'].std(return_nan=True).alias('CustomStd'))

print(result_df)

**Comment by orlp** [comment]
`std()` and `var()` return nulls now when the number of samples is `<=` the degrees of freedom. If you insist you want `NaN` instead of null you can use `fill_null` afterward.
