### ISSUE TITLE
StringCache + scan_parquet + (groupby Categorical col) = Panic

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/polars#5968]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If you turn on the string cache, scan a parquet file with a categorical column, then group by this col and do an aggregation, you get this error message:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(Borrowed("Cannot cast numeric types to 'Categorical'"))', /home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/mod.rs:34:40
```

This behaviour was introduced in 0.15.9. I haven't checked if other file formats have this issue, but if you just initialize a DataFrame from two series and call .lazy this issue does not occur.

### Reproducible example

```python
import polars as pl
pl.DataFrame([
    pl.Series("name", ["Bob", "Alice", "Bob"], pl.Categorical),
    pl.Series("amount", [100, 200, 300]),
]).write_parquet("tmp.pq")
with pl.StringCache():
    pl.scan_parquet("tmp.pq").groupby("name").agg(pl.col("amount").sum()).collect()
```

### Expected behavior

This should work fine

### Installed versions

<details>

```
---Version info---
Polars: 0.15.9
Index type: UInt32
Platform: Linux-5.15.85-1-MANJARO-x86_64-with-glibc2.36
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Thanks. Streaming data and a temporary stringcache have some challenges. I think I have a better fix.
