### ISSUE TITLE
Support for Pandas Period

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#5982]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars is having issues converting a pandas dataframe that has dtype as Period

### Reproducible example

```python
import polars as pl
import pandas as pd

def pandas_df():
    data = (['2020-10-30 12:13:14.000000',
             '2021-11-30 23:59:59.123450',
             '2022-12-30 00:00:00.000000'])
    df = pd.DataFrame(data, columns=['Date'])
    df['Period_col'] = (df['Date'].str.split()
                            .str[0]
                            .apply(lambda x: pd.Period(x, freq='D')))

    return df

def read_from_pandas():
    pl_df = pl.from_pandas(pandas_df())
    print('Polar df types', pl_df.dtypes)
    print('Polar df ', pl_df.head())
```

### Expected behavior

Expecting a Polar df like below

df                           Date             Period_col
0  2020-10-30 12:13:14.000000  2020-10-30
1  2021-11-30 23:59:59.123450  2021-11-30
2  2022-12-30 00:00:00.000000  2022-12-30

Got error as - __exceptions.InvalidOperationError: Cannot create polars series from Extension("pandas.period", Int64, Some("{\"freq\": \"D\"}")) type__

### Installed versions

<details>

```
polars             0.15.10

```

</details>

**Comment by ritchie46** [comment]
This is not a bug. We don't support pandas period datatype.
