### ISSUE TITLE
Add indicator, validate option in dataframe join

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#5983]
### Problem description

In the Pandas merge function, 
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

they provide an indicator and validate option, which is quite useful.

Indicator is useful when one needs to inspect those matched rows vs. unmatched rows after the joining

validate is useful when enforcing one-to-one join and etc. (make sure no duplicates after the join), and one does not have to check beforehand.

Wondering if Polars can implement these?

**Comment by zundertj** [comment]
Hello, thank you for your suggestion. However, it has been made before several times, and we track this issue in #2377. Could you please upvote and/or comment there? This keeps our issue tracker organized. Closing this one.
