### ISSUE TITLE
Implement Pandas Relational Function Names

### ISSUE THREAD

**Issue by BSalita** [pola-rs/polars#5992]
### Problem description

Please implement the commonly used Pandas relational functions e.g `df['Qty'].ge(100)`. I've warmed up to Pandas relational functions syntax especially since operator priority bugs become a non-issue, parenthesis matching errors are reduced and they provide more syntactic compatibility/familiarity when porting Pandas code to Polars.

**Comment by mkleinbort-ic** [comment]
Thank you, I wanted this too
