### ISSUE TITLE
Plotting in the ```polars``` library for Rust

### ISSUE THREAD

**Issue by v-danh** [pola-rs/polars#5998]
### Problem description

I'm new to the Rust programing language. I wonder if the ```polars``` library can be plotted in the Rust programming language?

**Comment by zundertj** [comment]
Could you be more specific what you mean by "plotted", making plots based on the data in a dataframe? With which plotting library would you want to do this, and what issues are you running into them?

I have relabeled your issue as a question; it would be greatly appreciated if you could go more into the specifics.

**Comment by ritchie46** [comment]
It is very unlikely that a plotting library will take a dependency on data structures like polars. You'll have to convert your data to vectors, or pass iterators.
