### ISSUE TITLE
Illegal instruction when trying to create a dataframe on an old CPU with polars-lts-cpu

### ISSUE THREAD

**Issue by mgunyho** [pola-rs/polars#5999]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm just starting out with Polars with an ancient CPU from 2010. I first installed it normally via pip, and `import polars as pl` caused an illegal instruction error. Then I found #2922, so I installed `polars-lts-cpu`. The import now works, but then I get an illegal instruction error when trying to create a simple dataframe with `pl.DataFrame`.

Here's the output of `grep "flags" /proc/cpuinfo`:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb
rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid
extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic
cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr
cpb hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter
```

### Reproducible example

```shell
$ python3 -m venv env
$ source env/bin/activate
(env) $ pip install polars-lts-cpu
Collecting polars-lts-cpu
  Using cached polars_lts_cpu-0.15.11-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
Installing collected packages: polars-lts-cpu
Successfully installed polars-lts-cpu-0.15.11
(env) $ python3
Python 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl  # this would crash with non-lts-cpu, but succeeds
>>> pl.DataFrame([{"foo": 123}])
Illegal instruction (core dumped)
```

The same also happens with `pl.DataFrame()` with an empty argument.

### Expected behavior

No crash.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-6.1.1-1-default-x86_64-with-glibc2.36
Python: 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Sorry, you will have to compile from source.

**Comment by mgunyho** [comment]
Fair enough.

**Comment by robambalu** [comment]
@ritchie46 Seeing as this has come up a few times ( I just hit it as well ), what do you think about checking for CPU capabilities up front.  If required instructions arent available maybe you can raise an import error ( to avoid just crashing ) and then users could opt to import the non-performant version https://pypi.org/project/polars-lts-cpu/ if they like on the import except:

**Comment by mgunyho** [comment]
Note that in my case even `non-lts-cpu` didn't work, not sure what CPU capability I am missing.
