### ISSUE TITLE
categorical dtypes with explicit value->label mappings

### ISSUE THREAD

**Issue by khusmann** [pola-rs/polars#6003]
### Problem description

First, thank you for this fantastic project! I really appreciate the lazy evaluation, strict typing in the python bindings & how much you avoid bloat.

Right now the api around categorical vars is great for unordered categories, where they basically act as cheap stand-ins for string values. In this situation it makes sense to build new categories as new strings are discovered. The main concern in this use case is to ensure non-clashing mappings when combining columns, which is solved with the StringCache context.

However, in many of my applications (in education and social science), the codes of a categorical (or ordinal) variable are just as important to the variable type as the labels. Right now, working with categorical vars with meaningful value->label mappings is a bit cumbersome  For example, a column representing values from responses to a likert scale (e.g. 1 = "Strongly disagree", 2 = "Disagree", 3 = "Neutral", 4 = "Agree, 5 = "Strongly agree"). Unless I'm missing something, I think the best way to work with data like this in polars is to just use a u32 dtype and track the mapping in separate structures I pass along with my main DataFrame, and then run joins as needed.

In the special case where values are positive, start at zero, and have unity increments, I could also also [pre-fill the StringCache with mappings](https://stackoverflow.com/questions/70934789/in-polars-can-i-create-a-categorical-type-with-levels-myself), but in general I might want to map to an arbitrary scale, say -100 = "Strongly agree", -1 = "Disagree", 0 = "Neutral", 1 = "Agree", 100 = "Strongly agree", so I'm stuck with managing separate lookup tables for each column I want to map like this, rather than having this info embedded in the column type itself & considered in expressions.

What would be ideal, I think, would be if the map/lookup table was an explicit attribute of the column dtype.

Here's some things I'd want to be able to do with a dtype like this:

1) Support mappings to signed integers, not only unsigned (for scales with negative values).

2) Specify the label->value mappings up front when I cast the column from string & raise errors on unexpected levels:

```
likert_scale = {
    1: "Strongly disagree",
    2: "Disagree",
    3: "Neutral",
    4: "Agree",
    5: "Strongly agree"
 }

likert_scale2 = {
    -1: "Disagree",
    0: "Neutral",
    1: "Agree",
 }

df = pl.DataFrame({
    "Question1": ["Strongly agree", "Neutral", "Strongly disagree"],
    "Question2": ["Neutral", "Strongly disagree", "Agree"],
    "Question3": ["Neutral", "Disagree", "Agree"],
})

df_cat = df.select([
    pl.col("Question1").cast(pl.Categorical(likert_scale)),
    pl.col("Question2").cast(pl.Categorical(likert_scale)),
    pl.col("Question3").cast(pl.Categorical(likert_scale2)),
])

df_error = df.select([
   pl.col("Question2").cast(pl.Categorical(likert_scale2)), # error: Strongly disagree is not in the map
])
```

This would also make it easy to specify value->label mappings for values that might not (yet) be in present in the column.

3) Error when concatting columns with different value->label mappings (like #3865)

```
pl.concat([df_cat["Question1"], df_cat["Question2"]]) # ok
pl.concat([df_cat["Question1"], df_cat["Question3"]]) # error, different scales
```

4) Easily change the labels, without touching the underlying physical values:

```
df_cat.with_columns([
    pl.col("Question1").cat.relabel({
        1: "No way",
        2: "No",
        3: "Meh",
        4: "Ok",
        5: "Of course!",
    })
])
```

Other common tasks are already easily done with the existing api, like remapping the physical values (a join) or aggregations (again using .physical to operate on the underlying values).

I think having a categorical dtype with an explicit mapping like this would be useful in a lot of situations (e.g. #2956, #5671, #3036, #2508). I could see it being an extension of the existing categorical type, or even as a completely separate dtype to reflect the different behavior/usage (e.g. "pl.StrictCategorical" or "pl.Lookup"). That said, I totally understand if you see this kind of functionality as bloat or beyond the scope of polars, I respect & appreciate that you're trying to keep things minimal.

Anyway, thanks again for all your work on this project! I'm sure you hear this a lot, but it's a game-changer for a bunch of things I'm working on.

**Comment by alexander-beedie** [comment]
Interesting; sounds like you're essentially after `Enum` support (almost -but not quite- the same thing).

**Comment by khusmann** [comment]
@alexander-beedie ah! I was too deep in my application to see it. yes, an `Enum` type would do it, I think. (when you say "almost", are you seeing an aspect an `Enum` wouldn't cover in my use case?)

Another point of friction I'm finding is in column lists of categorical / enums. I can cast lists of numeric types easily, like this:

```
(
   pl.DataFrame({"foo": [[1, 2], [1], []]})
   .select(pl.col("foo").cast(pl.List(pl.Float32)))
)
```

```
shape: (3, 1)
┌────────────┐
│ foo        │
│ ---        │
│ list[f32]  │
╞════════════╡
│ [1.0, 2.0] │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [1.0]      │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ []         │
└────────────┘
```

I'd like to be able to do the same with categorical / enums:

```
(
   pl.DataFrame({"bar": [["a", "b"], ["a"], []]})
   .select(pl.col("bar").cast(pl.List(pl.Categorical)))
)
```

What I get instead is a column of null lists in the same shape as my input... (is this a bug?)

```
shape: (3, 1)
┌──────────────┐
│ bar          │
│ ---          │
│ list[cat]    │
╞══════════════╡
│ [null, null] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [null]       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ []           │
└──────────────┘
```

(To get it to work properly I have to use .arr.eval and cast each item to categorical individually, which I didn't expect)

In the enum case, I'd expect it to work something like this:

```
baz = (
   pl.DataFrame({"baz": [["a", "b"], ["a"], []]})
   .select(pl.col("baz").cast(pl.List(pl.Enum({ 1: "a", 2: "b", 3: "c" })))
)
```

As I'm thinking more about it, I'm seeing the mapping to be a part of the type itself, so "relabeling" should just be a cast to a different Enum:

```
baz.select(pl.col("baz").cast(pl.List(pl.Enum({ 1: "new_a", 2: "new_b", 3: "new_c" })))
```

So instead of instead of a cat.relabel or enum.relabel (like I suggested in my first comment):

```
df_cat.with_columns([
    pl.col("Question1").cat.relabel({
        1: "No way",
        2: "No",
        3: "Meh",
        4: "Ok",
        5: "Of course!",
    })
])
```

It'd be:

```
df_cat.with_columns([
    pl.col("Question1").cast(pl.Enum({
        1: "No way",
        2: "No",
        3: "Meh",
        4: "Ok",
        5: "Of course!",
    }))
])
```

**Comment by alexander-beedie** [comment]
> What I get instead is a column of null lists in the same shape as my input... (is this a bug?)

Yes - and one that is now fixed; I see you raised it as a separate issue and it was closed ~2 weeks ago ;)

I've been considering an `Enum` type more, and think it would be a great addition; I'm not sure how easy it is to implement though. I only dabble in the Rust side of things (where the `Categorical` implementation lives that this would likely build on). Still, might have a look as I'm intrigued by the possibilities now... ;)

**Comment by khusmann** [comment]
@lorentzenchr 

Good question. From the docs, it looks like DictionaryArray uses indices into a value array as keys, rather than an arbitrary key->value map. So it's closer to pl.Categorical, where the keys don't have substantive meaning and are just used to more efficiently store a column with many duplicate values.

An "Enum" type, by contrast, would have meaningful keys and ways to easily remap keys if needed. For example, say you had a column like this:

"RED", "BLUE", "GREEN", "RED", "BLUE", "BLUE"

And you wanted their keys to correspond to their wavelengths:

700 = RED
500 = GREEN
450 = BLUE

An Enum column would store the data as their int wavelengths, along with the int->string mapping.

**Comment by stinodego** [comment]
Thanks for the input. I'm closing this in favor of #10705
