### ISSUE TITLE
Panic when writing a dataframe that contains `datetime` columns with IANA time zones to a CSV file

### ISSUE THREAD

**Issue by doomlaur** [pola-rs/polars#6004]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

According to the [Apache Arrow specification for time stamps](https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow13TimestampTypeE):
> If supplied, the timezone string should take either the form (i) “Area/Location”, with values drawn from the names in the IANA Time Zone Database (such as “Europe/Zurich”); or (ii) “(+|-)HH:MM” indicating an absolute offset from GMT (such as “-08:00”). To indicate a native UTC timestamp, one of the strings “UTC”, “Etc/UTC” or “+00:00” should be used.

This works correctly when printing a dataframe with `println!("{}", data_frame);`. In that case, for a time zone like `Europe/Vienna`, I see dates like `2021-01-01 01:30:00 CET` with a column type `datetime[ms, Europe/Vienna]`. However, when writing the dataframe to a CSV file, [the following code](https://github.com/pola-rs/polars/blob/14f47364e2c3fd209d971cd3e42d765020dc3f45/polars/polars-io/src/csv/write_impl.rs#L98) in `polars/polars-io/src/csv/write_impl.rs` expects UTC offsets instead of IANA time zone names:
```rust
Some(tz) => {
    let tz = temporal_conversions::parse_offset(tz).unwrap();
    ...
}
```
This causes my program to panic with the following error:
```
panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("timezone offset must be of the form [-]00:00")
```

[Taking a look](https://github.com/pola-rs/polars/blob/14f47364e2c3fd209d971cd3e42d765020dc3f45/polars/polars-core/src/fmt.rs#L715) at `polars/polars-core/src/fmt.rs` it seems that it first tries to parse a IANA time zone name, and if that fails, it tries to parse a UTC offset instead. I think the CSV writer would greatly benefit from such an improvement.

Last but not least, I'm not sure why UTC offsets are accepted by the Apache Arrow specification, because it's very easy to use them wrong. For it to work correctly I need to consider:
1. When the Daylight Saving Time (DST) begins and ends each year
2. Whether a country uses DST or not, and whether it stopped using it. Example: Brazil observed DST in the years of 1931–1933, 1949–1953, 1963–1968 and 1985–2019 ([source](https://en.wikipedia.org/wiki/Daylight_saving_time_in_Brazil)). So, for example, I need to consider it before 2019, but not after 2019.

As you can see, this is something that ***must be done per timestamp and not per column***, with information from a time zone database. As such, it's actually impossible to correctly set a UTC offset for a whole column, unless you can ensure that all time stamps have the same UTC offset (which can be done for short time periods that don't go over DST borders). UTC offsets can only be used correctly for single time stamps (and even in that case it can be error-prone), but not for whole columns. Of course, I know that this is not something that Polars can change since it's part of the Apache Arrow specification, but I'm trying to find the reason behind supporting UTC offsets, as I don't think it's a good idea for Apache Arrow to support them at all.

EDIT: Maybe specifying a UTC offset is great for situations where you want to ignore DST on purpose. However, I think this is a very special case. Maybe the best solution is to properly document the risk of setting a UTC offset instead of a time zone, while allowing both.

### Reproducible example

```rust
use std::borrow::BorrowMut;
use polars::prelude::*;

fn main() {
    let dt_winter = chrono::NaiveDate::from_ymd_opt(2021, 1, 1).unwrap().and_hms_opt(0, 30, 0).unwrap();
    let dt_summer = chrono::NaiveDate::from_ymd_opt(2021, 7, 1).unwrap().and_hms_opt(0, 30, 0).unwrap();
    let mut datetime_chunked = DatetimeChunked::new("DateTime", &[dt_winter, dt_summer]);
    
    // This works correctly when printing, but panics then writing to CSV file when IANA time zone names are used (instead of UTC offsets).
    datetime_chunked.set_time_zone(Option::from("Europe/Vienna".to_string()));
    
    let datetime_series = Series::from(datetime_chunked);
    let mut data_frame = DataFrame::new(vec![datetime_series]).unwrap();
    
    // This always works correctly.
    println!("{}", data_frame);
    
    let output_csv_file = std::fs::File::create("output.csv").unwrap();
    
    // This currently panics when IANA time zone names are used (instead of UTC offsets) with InvalidArgumentError("timezone offset must be of the form [-]00:00")
    let csv_writer_result = CsvWriter::new(output_csv_file).with_datetime_format(Option::from("%F %T".to_string())).finish(data_frame.borrow_mut());

    if let Err(error) = csv_writer_result {
        eprintln!("ERROR: could not write dataframe to file: {}", error);
    }
}

```

### Expected behavior

The CSV writer should accept IANA time zone names.

### Installed versions

[dependencies]
chrono = { version = "0.4" }
polars = { version = "0.26.1", features = ["timezones"] }

Rust 1.66.0
Windows 10 22H2

**Comment by ritchie46** [comment]
Yw! :)
