### ISSUE TITLE
`Cannot find reference '...' in 'accessor | property'` in PyCharm

### ISSUE THREAD

**Issue by fzyzcjy** [pola-rs/polars#6007]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Pycharm becomes yellow for this:

![image](https://user-images.githubusercontent.com/5236035/210343482-5953a9ca-cf56-468d-8508-64f0f96aabc9.png)

### Reproducible example

```python
df = pl.DataFrame()
df['a'].str.starts_with('b')
```

### Expected behavior

pycharm understands the content

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.21.5
fsspec: 2022.02.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.4.3
```

</details>

**Comment by alexander-beedie** [comment]
Hi; can you update your issue with the requested info for "Installed versions"? (Putting "latest version" isn't very useful for us ;)
```python
pl.show_versions()
```
Thanks.

**Comment by fzyzcjy** [comment]
```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.21.5
fsspec: 2022.02.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.4.3

**Comment by alexander-beedie** [comment]
Thanks for the additional info; I think I have a working fix almost ready to go.

**Comment by fzyzcjy** [comment]
Thanks for the fast fix!
