### ISSUE TITLE
Issue with DataFrame initialization from dictionary

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6008]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When providing a schema for the `columns` argument, and the data is specified as a dictionary, the column names in the data dictionary are overwritten.

I would expect the original names to be respected, and being checked against the schema, and finally be reordered according to the schema.

### Reproducible example

```python
import polars as pl

schema = {"a": pl.UInt32, "b": pl.UInt32}
df = pl.DataFrame({"b": [3, 4], "a": [1, 2]}, columns=schema)

print(df)
```

### Expected behavior

Actual output:

```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ u32 ┆ u32 │
╞═════╪═════╡
│ 3   ┆ 1   │
│ 4   ┆ 2   │
└─────┴─────┘
```

Expected output:

```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ u32 ┆ u32 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.9
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by mcrumiller** [comment]
The current API is confusing in this respect, but here is what the document says about the `columns` parameter:

> **columns** : ***Sequence of str or (str,DataType) pairs, default None***
Column labels to use for resulting DataFrame. If specified, overrides any labels already present in the data. Must match data dimensions.

Note the "If specified, overrides any labels already present in the data." By using `columns=`, you're overriding the column names. The data remains ordered the same way.

In my opinion, this usage is confusing: the point of dictionaries is to assign values to keys, but here they're used as tuple assignments.

**Comment by ritchie46** [comment]
That is definitely confusing. It seems that we dispatch to the wrong constructor?

I also don't like the name `columns`. We use `schema` throughout the library and to me that name is much more clear, what do you think?

**Comment by stinodego** [comment]
I'll brood on this for a little bit. As @mcrumiller pointed out, this is technically not a bug and documented properly in the docstring. But I would say it's definitely confusing/unexpected behaviour.

I agree that `schema` fits better than `columns` in this case. Maybe we can have both... I'll come up with a proposal.

**Comment by alexander-beedie** [comment]
I suspect the least-intrusive thing to do here would be to align the dict passed to columns to the dict given in data; having two params (columns/schema) is bad ergonomics. 

We can document dict-as-schema behaviour in the docstring (it doesn't actually note that it can take a dict, so in some sense the behaviour is currently undefined), and obey the principle of least surprise ;)
