### ISSUE TITLE
Can we set up some time to chat? (nushell and polars)

### ISSUE THREAD

**Issue by jonathandturner** [pola-rs/polars#601]
#### Describe your feature request

Hi, I work with the Nushell project and recently we had someone working on a PR to merge data frame support in Nushell. As part of that, I wanted to reach out and see if you'd be interested in chatting. It'd be good to get a more complete understanding of the current status and direction of polars and to also share our ideas for Nushell, to see where potentially collaboration could happen.

Cheers!

**Comment by ritchie46** [comment]
Hi @jonathandturner, that's an interesting development. I am available for a chat. We could chat privately on [gitter](https://gitter.im/polars-rs/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), or any other medium as well.
