### ISSUE TITLE
Enropy in groupby failed when no discrete probabilities provided

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#6011]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When filtering a colum in agg expression and after filtering we have 0 values. Entropy calculation fails.
**Note**  if we do that without groupby, just for series, everything will be ok.

### Reproducible example

```python
import polars as pl

pl.DataFrame({'col_to_groupby': [2], 'time': [1672740910.967138],  'col3': [1]}).groupby('col_to_groupby').agg(
    (
        (pl.col('time').filter(pl.col('col3') == 0).unique_counts() /
         pl.col('time').filter(pl.col('col3') == 0).len()).entropy()

    ).alias('calc')
)
exceptions.ComputeError: returned aggregation is a different length: 0 than the group lengths: 1
```

### Expected behavior

This computation should returns
<br class="Apple-interchange-newline">

col_to_groupby | calc 
-- | -- 
i64 | f32
2 | null 

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06) 
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: <not installed>
numpy: 1.22.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
None
```

</details>

**Comment by ritchie46** [comment]
I can run this snippet in master after 0.15.15. It returns this:

```
shape: (1, 2)
┌────────────────┬──────┐
│ col_to_groupby ┆ calc │
│ ---            ┆ ---  │
│ i64            ┆ f64  │
╞════════════════╪══════╡
│ 2              ┆ -0.0 │
└────────────────┴──────┘

```

I only don't understand what you'd expect from `entropy(len)`.

**Comment by s-b90** [comment]
Seems that it was fixed by https://github.com/pola-rs/polars/pull/6036, thank you. I will close this.

> I only don't understand what you'd expect from entropy(len).

It was `entropy(unique_counts / len)` where `unique_counts / len` are `pk` -  discrete probabilities.
For some reasons, entropy calculates correctly only if values in series are prepared discrete probabilities. So we need to calculate `pk` before entropy.
