### ISSUE TITLE
estimated_size accepts nonsense arguments

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/polars#6015]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`df.estimated_size` just checks the first letter of the `unit` argument. The below should probably not be allowed:

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1]})
df.estimated_size("milkshake") # interpreted as "mb"
```

### Expected behavior

Raise an error

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.15.85-1-MANJARO-x86_64-with-glibc2.36
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by stinodego** [comment]
Thanks for the report. We'll fix this!
