### ISSUE TITLE
from_epoch is undocumented

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6022]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There is no mention of `from_epoch` in the Python/Rust documentation, I only found out about it from StackOverflow.

https://pola-rs.github.io/polars/py-polars/html/search.html?q=from_epoch
https://docs.rs/polars/latest/polars/?search=from_epoch

### Reproducible example

```python
NA
```

### Expected behavior

NA

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Windows-10
Python: 3.10.8
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.22.4
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by stinodego** [comment]
Will be fixed!

**Comment by clouds56** [comment]
Can I use it from rust? If so, how?
I couldn't find the api from docs.rs

**Comment by stinodego** [comment]
> Can I use it from rust? If so, how? I couldn't find the api from docs.rs

No, this one is implemented completely in Python. You can get the same behavior by casting to integer and correcting for time units.
