### ISSUE TITLE
Error filtering `Categorical` values with `is_in`

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#6030]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

An unexpected cast gets injected when filtering `Categorical` column values using `is_in`, resulting in a `ComputeError`. 

The same values can, however, be successfully (but less-efficiently) filtered by chaining `==` expressions with `or`.

### Reproducible example

*Setup:*
```python
import polars as pl

df = pl.DataFrame({
    'key':['bbb','aaa','ccc']
}).with_column(
    pl.col('key').cast( pl.Categorical )
)
```
*Filter using `==` with `or` (succeeds):*
```python
df.filter( (pl.col('key') == 'aaa') | (pl.col('key') == 'ccc') )
# ┌─────┐
# │ key │
# │ --- │
# │ cat │
# ╞═════╡
# │ aaa │
# │ ccc │
# └─────┘
```
*Filter for the same values using `is_in` (fails):*
```python
df.filter( pl.col('key').is_in(['aaa','ccc']) )

# ComputeError: Joins/or comparisons on categorical dtypes can only 
#   happen if they are created under the same global string cache. 
#   Hint: set a global StringCache
```

### Expected behavior

Filtering for the given values should succeed in both cases.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Should it? The error states already that a global string cache should be used. The `is_in` converts the payload to `Series` and when we start comparing series of categoricals we require a global string cache.

**Comment by alexander-beedie** [comment]
Ideally yes; it should probably establish the mapping in this case. If it can work with a single comparison (`==`), and it can work with a _chain_ of such comparisons (`==` + `or`) , then it should really work with `is_in` too, or that's pushing quite a bit of the internals up onto the caller.

This repro above actually came out of a more complex case (also involving `is_in`) where we _do_ have a global string cache active, but it the mapped values seems to be (somehow) getting _changed_ by the cast, resulting in incorrect/no matches. I haven't been able to minimise that one yet, but I suspect it's somehow related (we've pinned our dev pipelines to `0.15.9` for now to avoid the issue)  :(

**Comment by ritchie46** [comment]
The reason for this lack of ergonomics is that we want to make users aware of the cost of comparing categorical that don't come from the same source. They need to be remapped. That remapping is cheap if one of the arrays is short, so we might only allow it up to a certain number of data points.

Currently we just don't allow it. Which is easy to explain. :) If you want to compare two categorical series use a string cache. We can also make an exception for `is_in` only, as that is likely to be used with a small number of data points, but it adds complexity.

**Comment by ritchie46** [comment]
@alexander-beedie could you describe the issue you are experiencing on the new polars version? Maybe it rings a bell.

**Comment by alexander-beedie** [comment]
The issue is manifesting like so (the below was pulled directly from a colleague's console, then mildly redacted ;)

Can filter for a single ID:
```python
df.filter( pl.col('id') == 'ABCDEF-X' ).collect()
# ┌────────────┬──────────┬──────────┬────────
# │ date       ┆ id       ┆ currency ┆ fx2usd
# │ ---        ┆ ---      ┆ ---      ┆ ---
# │ date       ┆ cat      ┆ str      ┆ f64
# │            ┆          ┆          ┆
# ╞════════════╪══════════╪══════════╪ ...
# │ 2019-05-13 ┆ ABCDEF-X ┆ EUR      ┆
# │ 2020-01-13 ┆ ABCDEF-X ┆ EUR      ┆
# │ 2020-02-13 ┆ ABCDEF-X ┆ EUR      ┆ 
# │ 2020-06-01 ┆ ABCDEF-X ┆ EUR      ┆ 
# │ ...        ┆ ...      ┆ ...      ┆ ... 
# │ 2019-01-17 ┆ ABCDEF-X ┆ EUR      ┆
# │ 2017-10-24 ┆ ABCDEF-X ┆ EUR      ┆
# │ 2016-11-04 ┆ ABCDEF-X ┆ EUR      ┆ 
# │ 2018-11-12 ┆ ABCDEF-X ┆ EUR      ┆ 
# └────────────┴──────────┴──────────┴ ...
```
However: attempting to filter for that ID (which we know is there) _and one more_ returns no results, and also doesn't raise an error (as the global cache was toggled on):
```
python
df.filter( pl.col('id').is_in(['ABCDEF-X','ABCDEF-Z']) ).collect()
# ┌──────┬─────┬──────────┬────────┬
# │ date ┆ id  ┆ currency ┆ fx2usd ┆ ... 
# │ ---  ┆ --- ┆ ---      ┆ ---    ┆ 
# │ date ┆ cat ┆ str      ┆ f64    ┆
# ╞══════╪═════╪══════════╪════════╪ ... 
# └──────┴─────┴──────────┴────────┴ 
```
Has a very simple plan that includes the mildly-suspect cast:
```python
df.filter( pl.col('id').is_in(['ABCDEF-X','ABCDEF-Z']) ).describe_optimized_plan()
#  DF ["date", "id", "currency", "fx2usd"]; 
#    PROJECT */9 COLUMNS; SELECTION: "col(\\"id\\").is_in([Series.cast(Categorical(None))])"
```

**Comment by alexander-beedie** [comment]
I took a copy of that frame (~227MB) and see the same behaviour on my own machine; filtering with `0.15.9` returns results, filtering with `0.15.10` does not - will start bisecting it to see if I can reduce the frame to something more manageable.

**Comment by ritchie46** [comment]
> I took a copy of that frame via `write_ipc` (~227MB uncompressed) and can reproduce the same behaviour on my own machine; filtering with `0.15.9` returns results, filtering with `0.15.10` does not - will start bisecting it to see if I can reduce the frame to something more manageable while still replicating the issue.

Awesome!

**Comment by alexander-beedie** [comment]
> Awesome!

Got it down to two columns, one date, and only 27 KB now, and still shrinking ;)

**Comment by alexander-beedie** [comment]
Even better - was able to hash the only remotely-sensitive identifier, set the string-value of that hash as Categorical, and still largely reproduce; is now suitable for attaching here. Hopefully you will see the same behaviour:

Unzip the attached frame ([df.ipc.zip](https://github.com/pola-rs/polars/files/10345140/df.ipc.zip)) and try the following:

```python
import polars as pl

# prove that the given ids exist -
with pl.StringCache():
    df = pl.read_ipc( "df.ipc" )
    print( df.filter( pl.col('id') == '954743624916052757') )
    print( df.filter( pl.col('id') == '2450670604184026471') )

# ┌────────────┬────────────────────┐
# │ date       ┆ id                 │
# │ ---        ┆ ---                │
# │ date       ┆ cat                │
# ╞════════════╪════════════════════╡
# │ 2018-11-12 ┆ 954743624916052757 │
# └────────────┴────────────────────┘
# ┌────────────┬─────────────────────┐
# │ date       ┆ id                  │
# │ ---        ┆ ---                 │
# │ date       ┆ cat                 │
# ╞════════════╪═════════════════════╡
# │ 2018-11-12 ┆ 2450670604184026471 │
# └────────────┴─────────────────────┘

# but... filtering against both -
with pl.StringCache():
    df = pl.read_ipc( "df.ipc" )
    print( df.filter( pl.col('id').is_in(['954743624916052757','2450670604184026471']) ) )

# ┌──────┬─────┐
# │ date ┆ id  │
# │ ---  ┆ --- │
# │ date ┆ cat │
# ╞══════╪═════╡
# └──────┴─────┘
```
