### ISSUE TITLE
No example of SQLContext use in documentation

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6053]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There is no example on how to use `SQLContext`. Luckily I found one in the PR which added it.

https://pola-rs.github.io/polars/py-polars/html/reference/sql.html

In particular, I think it would be useful to show how it can replicate `pandas.DataFrame.query`, when using polar expressions is difficult (for example JSON serialized filter conditions):

```python
# pandas
df.query("level > 2")

# polars
ctx = pl.SQLContext()
ctx.register("df", df.lazy())
ctx.query("SELECT * FROM df WHERE level > 2")
```

Is `SQLContext` relatively supported or is it at risk of being removed in the future?

### Reproducible example

```python
NA
```

### Expected behavior

NA

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment]
Hey @2-5 would you be willing to open a PR with some docstring examples?

**Comment by ritchie46** [comment]
I will close this as it is not  a bug on our side. PR's improving docstrings are always welcome.
