### ISSUE TITLE
cannot install polars-lts-cpu in CentOS 7

### ISSUE THREAD

**Issue by LulinS** [pola-rs/polars#6055]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I tried to install polars on CentOS 7 with an old CPU which does not support avx. 
`$pip install polars-lts-cpu`
It says:
`ERROR: Failed building wheel for maturin`

### Reproducible example

```python
$pip install polars-lts-cpu
```

### Expected behavior

$pip install polars-lts-cpu

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ghuls** [comment]
Your pip installation is probably too old, so it does not install binary wheels by default and tries to compile Polars from scratch/ Upgrade pip to the latest version and install `polars-lts-cpu` again.

**Comment by LulinS** [comment]
> 

I checked that my pip is up to date.

**Comment by ghuls** [comment]
Which version is it?

**Comment by LulinS** [comment]
> 

22.3.1

**Comment by ghuls** [comment]
That should indeed be more than recent enough.

Is your platform `x86_64`?
```python
import platform
import sys

print(f"Platform: {platform.platform()}")
print(f"Python: {sys.version}")
```

What is the output of:
```bash
python -m pip install -U polars-lts-cpu
```

**Comment by LulinS** [comment]
> 

Platform: Linux-3.10.0-1160.21.1.el7.x86_64-x86_64-with-glibc2.17
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]

The output:
❯ python3 -m pip install -U polars-lts-cpu
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/sse3, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/sse3, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
      Collecting maturin<0.14,>=0.13
        Using cached maturin-0.13.7.tar.gz (154 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: maturin
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-311
            creating build/lib.linux-x86_64-cpython-311/maturin
            copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-311/maturin
            copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-311/maturin
            copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-311/maturin
            running egg_info
            creating maturin.egg-info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
            error: can't find Rust compiler

            If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

            To update pip, run:

                pip install --upgrade pip

            and then retry package installation.

            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by stinodego** [comment]
Apparently your system does not install the wheel and tries to build from scratch. You will need a rust compiler.

I will close this as it is not a Polars issue. Please ask in our Discord if you need help with installation issues.
