### ISSUE TITLE
add categorical equality fast paths

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6057]
A few easy perf/memory wins.

- `cat == str` should first check the rev map.
- `cat.is_in` should first check the rev_map if `is_in` is reasonable sized.
- First global rev map doesn't need a map from global to local.

**Comment by alexander-beedie** [comment]
We've been moving a lot of data into Categorical cols recently, so this would be great  :)

**Comment by ritchie46** [comment]
Tried the smaller rev-map, but that seems more trouble than it is worth. We cannot determine fast uniques in such a case and get regressions in string comparisons. I will go with equality fast paths.

**Comment by ritchie46** [comment]
> Wouldn't a bloom filter be a good alternative for a fast in set reduction approach?

Yes, but we also need to map from global idx to local one. Don't want to do a linear search once the bloom filter says yes.

**Comment by ritchie46** [comment]
Will go for a btree. They are much more condensed and likely to be much faster on `u32`.
