### ISSUE TITLE
Cannot create empty structs

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6075]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Cannot create a struct with empty fields

### Reproducible example

```python
import polars as pl
from dataclasses import dataclass

@dataclass
class TestClass:
    int_field: int
    dict_field: dict

t = TestClass(int_field=10, dict_field={})

df = pl.DataFrame([t,t])
```

### Expected behavior

Create struct

### Installed versions

---Version info---
Polars: 0.15.12
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Python: 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.4
numpy: 1.23.2
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.3

**Comment by ritchie46** [comment]
@alexander-beedie could you take a look at this one? This seems like an error in the `dataclass` wrappers we added.

**Comment by alexander-beedie** [comment]
Looks like use of `@dataclass` is a red herring; it's more about the lack of a struct definition, due to each dict being empty - can further minimise the error like so:
```python
df = pl.DataFrame({
    "x": [10,20],
    "y": [{},{}],
})
# ShapeError: Could not create a new DataFrame from Series. 
#  The Series have different lengths. Got [shape: (2,)
```

**Comment by ritchie46** [comment]
Thanks. I'll take it again. ^^

**Comment by pebble2050** [comment]
@ritchie46 
The code below maybe need change to work . Because dtype_fields.iter() is empty, and the series_fields is end with empty.
polars/polars-core/src/series/any_value.rs
```
            #[cfg(feature = "dtype-struct")]
            DataType::Struct(dtype_fields) => {
                // the physical series fields of the struct
                let mut series_fields = Vec::with_capacity(dtype_fields.len());
                for (i, field) in dtype_fields.iter().enumerate() {
```

**Comment by zhcy2050** [comment]
Same error but with ndjson, there is no type parameter you can pass for struct yet.
```
import polars as pl
from io import BytesIO

nj = "{\"a\":1,\"b\":{}}\n{\"a\":2,\"b\":{}}\n"

buf = BytesIO(bytes(nj,'ascii'))

df = pl.read_ndjson(buf)
print(df)

```

**Comment by blepabyte** [comment]
In the current version of polars, constructing the dataframes in the examples above works without error, but seems to segfault when trying to perform any operations:
```python
import polars as pl
pl.DataFrame([{"a": {}}]).describe()
# fish: Job 1, 'python' terminated by signal SIGSEGV (Address boundary error)
```

```
---Version info---
Polars: 0.16.4
Index type: UInt32
Platform: Linux-6.1.9-arch1-2-x86_64-with-glibc2.37
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.0
fsspec: <not installed>
connectorx: 0.3.2_alpha.2
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.2
```

**Comment by ritchie46** [comment]
fixed in main/master
