### ISSUE TITLE
Error message in `read_csv` does not match Python implementation

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6078]
If I specify an incorrect schema to `dtypes`, the error message tells me:

```
Consider specifying the correct dtype, increasing
the number of records used to infer the schema,
running the parser with `ignore_parser_errors=true`
or  adding `Maandag` to the `null_values` list.
```

However, `ignore_parser_errors` is not a valid parameter for `read_csv`. The argument is called `ignore_errors`.

The error messages are generated in Rust, and the parameters there apparently do not completely match the Python side. This is confusing for Python users.

I think the best solution is to update the Rust/Python side so that the parameters match as closely as possible.

**Comment by ritchie46** [comment]
Can you adapt the error message and the rust builder pattern to match the python arg?

**Comment by stinodego** [comment]
Sure, will do. And I'll check the other error messages.
