### ISSUE TITLE
Documentation how to filter?

### ISSUE THREAD

**Issue by gitboy16** [pola-rs/polars#608]
Hi,

1/I couldn't find any documentation on how to filter a DataFrame column. Is there a page which explain how to do basic operations on DataFrames?

2/ I manage to load a csv file `shape(150000,60)` which takes about 25 seconds where `data.table::fread` from R takes 2 seconds. Is there a way to speed up `CsvReader::from_path` ? I tried with `with_n_threads(Some(1))` or 2 but it doea not seem to improve it. I found that code while I was googling but not sure it is correct as it is not documented.

Thank you
Kind regards

**Comment by ritchie46** [comment]
> 1/I couldn't find any documentation on how to filter a DataFrame column. Is there a page which explain how to do basic operations on DataFrames?

Have you checked the docs? [Eager API](https://pola-rs.github.io/polars/polars_core/frame/struct.DataFrame.html#method.filter), [Lazy API](https://pola-rs.github.io/polars/polars/prelude/struct.LazyFrame.html#method.filter)

> 2/ I manage to load a csv file shape(150000,60) which takes about 25 seconds where data.table::fread from R takes 2 seconds. Is there a way to speed up CsvReader::from_path ? I tried with with_n_threads(Some(1)) or 2 but it doea not seem to improve it. I found that code while I was googling but not sure it is correct as it is not documented.

Which Polars version are you using? And did you compile with `--release`?

**Comment by gitboy16** [comment]
1/Yes I saw those links but did not manage to filter on a small DataFrame I loaded. The first link does not have any example. Do you have a example on small DataFrame?
2/ Using 0.13.3. Wow, indeed with --release it is super fast. Sorry about that I just started using Rust yesterday.
Thank you

**Comment by gitboy16** [comment]
I just run `CsvReader::from_path` on a 1GB csv file and got the following error:
```
memory allocation of 72483008 bytes failed
error: process didn't exit successfully: `target\release\hello-rust.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by ritchie46** [comment]
> I just run `CsvReader::from_path` on a 1GB csv file and got the following error:
> 
> ```
> memory allocation of 72483008 bytes failed
> error: process didn't exit successfully: `target\release\hello-rust.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
> ```

Could you show me an example of your code, and send me the CSV file you are parsing?

**Comment by gitboy16** [comment]
Data are private but I will try to build a similar csv file and come bqck to you.

**Comment by ritchie46** [comment]
I added a docstring example: https://pola-rs.github.io/polars/polars_core/frame/struct.DataFrame.html#method.filter

**Comment by gitboy16** [comment]
Thanks for the example. I manage to filter on a dataframe using the function `eq` and creating an function based on your example but did not manage to filter on a dataframe directly...I don't find the rust syntax very friendly compare to R and Python...or maybe it is just me who does not know how to use it...

Otherwise I manage to create a csv file for you.
Here is the R code to create a dummy csv file.

```R
x=stringi::stri_rand_strings(6e3,9187L)
y=c(rep("a",6e6-6e3),x)
df=data.frame(
  V1=rep(c("a","b","c"),2e6),
  V2=rep(c("a","b","c"),2e6),
  V3=rep(c(TRUE,FALSE,NA),2e6),  
  V4=rep(c("a","b","c"),2e6),
  V5=rep(c("a","b","c"),2e6),
  V6=rep(c("a","b","c"),2e6),
  V7=rep(c("a","b","c"),2e6),
  V8=rep(c("a","b","c"),2e6),
  V9=y,
  V10=rep(c(0.987,0.643,0.232),2e6),
  V11=rep(c("a","b","c"),2e6),
  V12=rep(c("a","b","c"),2e6),
  V13=rep(c(737.8,62626.9,6266.5),2e6),
  V14=rep(c(837.8,637.0,526.2),2e6),
  V15=rep(c(NA,2.737,7.7377),2e6),
  stringAsFactors=FALSE
)
data.table::fwrite(df, "data.csv",row.names=FALSE)
```
Hope I did not do any typo in the code above as I can't copy paste or post to github, so I had to write everything from my phone. Hope it helps.

**Comment by ritchie46** [comment]
> e is the R code to create a dummy csv file.

Sorry, I don't have an R environent, could you make a Python script, or send met the file?


> Thanks for the example. I manage to filter on a dataframe using the function eq and creating an function based on your example but did not manage to filter on a dataframe directly...I don't find the rust syntax very friendly compare to R and Python...or maybe it is just me who does not know how to use it...

If you create a MWE, I could help you.

**Comment by gitboy16** [comment]
I am at work now but as soon as as can I will try to create the file and send it to you. Basically the csv file contains 15 columns (str, f64..etc) 6 millions rows, and one column is special (column 9) which contains about 6000 rows with very long strings (i.e. 9187 characters long)...

**Comment by gitboy16** [comment]
It worked! I add `.low_memory(true)` following a example of CsvReader that I found at: https://able.bio/haixuanTao/data-manipulation-polars-vs-rust--3def44c8

Thank you. By the way the above link is super useful to learn how rust polar works. I think if you consider writing a blog post or doc explaining how to do various data manipulation task it could help people who are new to the language like me. Here is the type of blog post which I believe is easy for people to switch from one language to the other:
https://datascience-enthusiast.com/R/pandas_datatable.html

**Comment by ritchie46** [comment]
> I just tried the Python bindings version 0.7.12 by building it from the master branch. What works is the lazy evaluation
> 
> ```
> df = pl.read_csv("./star2002-full.csv", has_headers=False, )
> df.filter(...)
> ```
> 
> What does **not** work because the method just doesn't exist is the eager evaluation
> 
> ```
> df = pl.read_csv("./star2002-full.csv", has_headers=False, )
> df.filter(...)
> > AttributeError: filter not found
> ```

That's correct, in eager you filter with syntac similar to pandas/numpy.

```python
mask = df["foo"] > 10
df[mask]
```

**Comment by ritchie46** [comment]
I added an example for python eager + lazy in the [user guide](https://pola-rs.github.io/polars-book/howcani/df/filter.html).

For Rust, those examples are in the docs. I am going to close this now.

> Thank you. By the way the above link is super useful to learn how rust polar works. I think if you consider writing a blog post or doc explaining how to do various data manipulation task it could help people who are new to the language like me. Here is the type of blog post which I believe is easy for people to switch from one language to the other:
https://datascience-enthusiast.com/R/pandas_datatable.html

There are a few examples in the examples folder. With regard to documentation, any help/ blog post is welcome. :wink:

**Comment by FlorianWilhelm** [comment]
@ritchie46 thanks for the explanation :-) BTW, what I really like about Polars so far is that it is quite close to the Spark API, which I find much superior to the complex and inconsistent Pandas API. 

May I ask why you decided to make the lazy and eager APIs so different though? Wouldn't it be just nice to replace maybe in a long transformation chain just the first `read_csv` with `scan_csv` or vice versa to switch from eager to lazy? Is there a technical reason for this?

**Comment by ritchie46** [comment]
> May I ask why you decided to make the lazy and eager APIs so different though? Wouldn't it be just nice to replace maybe in a long transformation chain just the first read_csv with scan_csv or vice versa to switch from eager to lazy? Is there a technical reason for this?

When I started with the eager API, lazy didn't exist yet. I am slowly transitioning supporting all the expressions in `eager`, because I believe they are really superior than imperative `mask` temp values etc.

But, you have a point, it would be helpful the have a UNION between `eager` and `lazy`. This is very doable, I only need to dispatch `filter`, `select` and `with_column(s)` on a `DataFrame`, so I will add that for next release. :+1:

**Comment by FlorianWilhelm** [comment]
Thanks for explaining the details. I also think that `filter` is mich better than temporary `mask` values. Really nice to see a library that dares to be different than Pandas. Thanks for your great work.
