### ISSUE TITLE
string_repr returns always `list[bool]`.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#6084]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

string_repr returns always `list[bool]` for any kind of pl.List.

### Reproducible example

```python
import polars as pl


In [30]: pl.List(pl.Utf8).string_repr()
Out[30]: 'list[bool]'

In [31]: pl.List(pl.Int32).string_repr()
Out[31]: 'list[bool]'
```

### Expected behavior

Return dtype string representation as shown when printing a dataframe:

```python
In [30]: pl.List(pl.Utf8).string_repr()
Out[30]: 'list[str]'

In [31]: pl.List(pl.Int32).string_repr()
Out[31]: 'list[i32]'
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.10
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.0
numpy: 1.23.5
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ghuls** [comment]
Discovered while trying to fix: https://github.com/pola-rs/polars/issues/6080

**Comment by mcrumiller** [comment]
More specifically, `pl.List(__).string_repr()` always returns `list[bool]`:

```
>>> pl.List(pl.UInt32).string_repr()
'list[bool]'
>>> pl.List(str).string_repr()
'list[bool]'
>>> pl.List(pl.Date)
'list[bool]'
```

**Comment by ghuls** [comment]
Fixed by: https://github.com/pola-rs/polars/pull/6298
