### ISSUE TITLE
df.sort() should use default argument by=df.columns

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#6086]
### Problem description

To sort an entire dataframe you must supply `by=df.columns`:

```python
df.sort()              # fails, requires argument 'by'
df.sort(by=df.columns) # succeeds
```

Being able to simply call `.sort()` looks a lot cleaner without losing any clarity about what's going on.

**Comment by ritchie46** [comment]
Having this explicit doesn't make this a blocker for projection pushdown.

**Comment by zundertj** [comment]
Added this in https://github.com/pola-rs/polars/pull/6092.

**Comment by stinodego** [comment]
For now we have decided not to implement this.

According to Ritchie:
> I don't think we should do it. Sorting by all columns is expensive and I don't want to nudge the api towards expensive operations. You probably should figure out by which columns you want to sort.
