### ISSUE TITLE
Invalid formatting of annotations (type hints)

### ISSUE THREAD

**Issue by NikolayXHD** [pola-rs/polars#6090]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Sometimes multiline type hints are missing braces, or line continuation, which leads to invalid Python, which in turn breaks type hinting in IDE.

I am ready to provide a PR to fix it, if the issue is acknowleged.

Btw, I have tried Polars first time a couple of days ago, and it's just amazing, extremely fast, very elegant API. I take my hat off, huge respect and gratitude to the authors.

### Reproducible example

https://github.com/pola-rs/polars/blob/5f3e332fb2a653064f083b02949c527e0ec0afda/py-polars/polars/internals/dataframe/frame.py#L5364

```python

def select(
        self: DF,
        exprs: str  # <- this line break is invalid
        | pli.Expr
        | pli.Series
        | Iterable[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen],
    ) -> DF:
    ...
```

### Expected behavior

To make that valid Python, either line-continuation or braces must be added:
```
    exprs: str \
        | pli.Expr \
        | pli.Series \
        | Iterable[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen],
```

```
    exprs: (
        str
        | pli.Expr
        | pli.Series
        | Iterable[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen]
    ),
```

Notice, that in other such places, the braces are there already, whcih is good:

https://github.com/pola-rs/polars/blob/5f3e332fb2a653064f083b02949c527e0ec0afda/py-polars/polars/internals/dataframe/frame.py#L257

```python
        data: (
            dict[str, Sequence[Any]]
            | Sequence[Any]
            | np.ndarray[Any, Any]
            | pa.Table
            | pd.DataFrame
            | pli.Series
            | None
        ) = None,
```

### Installed versions

0.15.10

**Comment by zundertj** [comment]
In what way is this invalid Python? PEP8 has an example on binary operators across multiple lines: [should-a-line-break-before-or-after-a-binary-operator](https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator).

Do you get a Python error? Or is there an IDE problem?

**Comment by NikolayXHD** [comment]
> In what way is this invalid Python?

It is invalid Python in the way that it violates [2.1.5 explicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining) and [2.1.6 implicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining) of Python language specification.

The example [should-a-line-break-before-or-after-a-binary-operator](https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) is *not invalid* Python because it does have parenthesis around the multiline expression with binary operators.

If we remove the parenthesis, then it's no longer valid Python:

```python
# valid, because there is implicit line joining due to parenthesis ()
income = (gross_wages
          + taxable_interest
          + (dividends - qualified_dividends)
          - ira_deduction
          - student_loan_interest)

# invalid
income = gross_wages +
         taxable_interest +
         (dividends - qualified_dividends) -
         ira_deduction -
         student_loan_interest

# also invalid
income = gross_wages
         + taxable_interest
         + (dividends - qualified_dividends)
         - ira_deduction
         - student_loan_interest
```

> Do you get a Python error?

No, the issue does not break the code, it is executed "as expected", but this is still not valid Python

> Or is there an IDE problem?

And yes, there is IDE problem, the type hinting does not work "as expected".

**Comment by alexander-beedie** [comment]
There's nothing wrong with it in terms of _"is it valid python"_ (because it is - these are type hints, _not_ runtime code). As a practical example you can trivially observe this; for instance here's a trivial source file:

*demo.py*
```python
def fn( param: str
    | float
    | None
) -> bool:
    return True

print( fn('whatever') )
```
You'll have no errors executing it and `mypy` will happily parse the full type (just add `reveal_type(fn)`).
```
❯ mypy demo.py
demo.py:7: note: Revealed type is 
  "def (param: Union[builtins.str, builtins.float, None]) -> builtins.bool"
```

**However...** ;)

If there is a problem in your IDE (which one is it, and what issue do you actually observe?) and you have found that adding parentheses to the type hints fixes your problem, then I don't see any problem with a PR that would improve things for the largest range of users (have you made the update locally and proved it works to address whatever issue it is that you're seeing?)

**Comment by NikolayXHD** [comment]
> which one is it, and what issue do you actually observe?

Pycharm, apparently recognizes the part of type which comes before the line break. In case of

```python
    def select(
        self: DF,
        exprs: str    # <- Pycharm only sees this part annotation
        | pli.Expr    # <- ignored
        | pli.Series  # ...
        | Iterable[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen],
    ) -> DF:
    ...
```
![image](https://user-images.githubusercontent.com/12046452/211144764-d7367598-2ec4-42b2-894d-12161e894e7d.png)

> Have you made the update locally and confirmed that it addresses whatever issue it is that you're seeing?

Yes, adding parenthesis fixes the problem, also the issue does not happen to `DataFrame.__init__` where there are already parenthesis.

```python
        data: (
            dict[str, Sequence[Any]]
            | Sequence[Any]
            | np.ndarray[Any, Any]
            | pa.Table
            | pd.DataFrame  # <- not ignored
            | pli.Series
            | None
        ) = None,
```

![image](https://user-images.githubusercontent.com/12046452/211144873-5228b485-f814-457d-bc2a-c3550e25a047.png)

Locally modified type hint:

![image](https://user-images.githubusercontent.com/12046452/211145067-f13a572f-180a-4479-ab42-b7a2b25e0a10.png)

Type hinting works fine:

![image](https://user-images.githubusercontent.com/12046452/211145136-21fb7246-ada8-46d6-aa0b-24cd5fc53916.png)

**Comment by alexander-beedie** [comment]
> Yes, adding parenthesis fixes the problem, also the issue does not happen to DataFrame.__init__ where there are already parenthesis.

I'm convinced ;)
I don't mind taking this on unless you already have a PR ready to go?

**Comment by NikolayXHD** [comment]
I don't have it, I guess today's night I can do it. If you feel like reviewing is no less work vs doing it yourself, then I am fine washing my hands as well :)

**Comment by zundertj** [comment]
I missed that there were no round brackets around the type annotation, it is only round brackets around the function indeed. Interesting difference between run time code and type annotations.

Ideally we have a linting (ruff?) check for this, because we can fix this one case now, but there may be more, and we may inadvertently introduce this again.

**Comment by alexander-beedie** [comment]
> Ideally we have a linting (ruff?) check for this, because we can fix this one case now, but there may be more, and we may inadvertently introduce this again.

#truestory ;)

**Comment by alexander-beedie** [comment]
> I don't have it, I guess today's night I can do it. If you feel like reviewing is no less work vs doing it yourself, then I am fine washing my hands as well :)

Lol... I can take care of it; as @zundertj says, ideally we would lint for it. Not sure if there's something "off the shelf" for this kind of check, but I'll have a search.

**Comment by NikolayXHD** [comment]
I was wrong claiming that missing parenthesis is invalid Python. It is valid, not only in type annotations, but in runtime expression as well:

```
print(
    1 + 2,
    3
    + 4
)
```
the code above runs fine, I guess function args parenthesis is a valid enabler of "implicit line joining" syntax.
