### ISSUE TITLE
Cannot bypass the warning "could not mmap compressed IPC file, defaulting to normal read"

### ISSUE THREAD

**Issue by Feiyang** [pola-rs/polars#6095]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When polars reads compressed IPC files, it prints "could not mmap compressed IPC file, defaulting to normal read". As it cannot be bypassed, it is very disturbing when I read thousands of files.

### Reproducible example

```python
import pandas as pd
df = pd.DataFrame({"x": [1,2,3]})
df.to_feather("/tmp/example.feather")

import polars as pl
pl.read_ipc("/tmp/example.feather")
```

### Expected behavior

There should be no warning.

Or, it would be good if the warning can be ignored with `warnings.simplefilter(action="ignore")`.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.3
numpy: 1.20.3
fsspec: 2021.10.1
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.0
```

</details>

**Comment by zundertj** [comment]
Thank you for reporting this, I have hidden the message in the non-verbose mode in https://github.com/pola-rs/polars/pull/6098.

**Comment by gam-phon** [comment]
I wanted to report this, but found it here before 20 hours and solved in 3 hours! Great I love you guys
