### ISSUE TITLE
inconsistency using with_columns_kwargs

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#6104]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When working with `pl.Config.with_columns_kwargs = True`, `with_columns` accepts only `Expr` and `str` as kwargs argument

### Reproducible example

```python
import polars as pl
import datetime

pl.Config.with_columns_kwargs = True

df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4],
        "b": [0.5, 4, 10, 13],
    }
)

df.with_columns(
    c='str', # passes
    d=0, # AttributeError: 'int' object has no attribute 'alias'
    # e=0.1, # AttributeError: 'float' object has no attribute 'alias'
    # f=None, # AttributeError: 'NoneType' object has no attribute 'alias'
    # g=datetime.datetime.now(), # AttributeError: 'datetime.datetime' object has no attribute 'alias'
    
)
```

### Expected behavior

IMO, we could accept all the data types that are allowed in `expr_to_lit_or_expr`, and then use this fonction internally to transform whatever was given into an `Expr`

If this make sens, I would be happy to propose a PR.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> If this make sens, I would be happy to propose a PR.

Makes sense to me ;)
