### ISSUE TITLE
gracefully handle conversion of object dtype with nans

### ISSUE THREAD

**Issue by strangemonad** [pola-rs/polars#6107]
### Problem description

First of all, let me say thank you for this amazing library and work. I do a lot of work with data driven UIs in the ML space. 
1. I often find myself with object dtype columns
2. interoperating with existing pandas code as we gradually adopt polars.

There's a bunch of rough edges I've run into that I think might hamper broader adoption. I appreciate that a lot of these might actually be better solved in either py03 or pyarrow. I'd actually love to figure out how I can help contribute with some of these issues in my spare time.

It's very likely this particular issue should be split up into a handful of issues.

# Proposal
1. (strict mode) Fail early in from_dict if the resulting table would violate post-conditions (i.e. a dtype=object column that contains nans)
2. (permissive mode) Support something like the `nan_to_none` option in `from_pandas` in methods like from_dict

# The problem
The gist is that it's possible to create columns with dtype object that contain nan and then you can't easily filter them out.

```python
import numpy as np
import polars as pl
import polars as pl
def test_no_nans_in_object_series():
    # maybe I created this manually or got it from somewhere else
    # e.g. the result a pandas df.to_dict(orient="list")
    manual_frame = {
        "my_object": [type("s"), np.NAN],
    }

    pl_df = pl.from_dict(manual_frame)
    # This df is created, pl.col("my_object") is of type object but it contains a NAN.
    # This breaks all sorts of other assumptions
    # e.g. the following fails (as expected) with
    # `exceptions.InvalidOperationError: 'is_nan' not supported for series with dtype Object("object")`
    pl_df.filter(pl.col("my_object").is_nan())

    # There's no efficient way to filter out the NAN at this point.
```

Granted, `pl.from_pandas` has a `nan_to_none` but you currently can't convert a pandas series of dtype object. It's also unclear to me if you always blindly want to convert nans to none across a dataframe (e.g. you probably want to leave nans for float columns but expunge them elsewhere?)

Here's the unrelated `pl.from_pandas` error that prevents using that method
```python
    pd_df = pd.DataFrame(
        {
            "my_object": [MyObject(), MyObject()],
        },
    )

    # even though polars detects this as dtype object, py arrow fails to create a series
    # construction.py._pandas_series_to_arrow() calls pa.array(values, from_pandas=nan_to_none)
    # which fails with an obscure error"
    # `pyarrow.lib.ArrowInvalid: Could not convert ... did not recognize Python value type when inferring an Arrow data type`
    pl_df = pl.from_pandas(pd_df)
```

**Comment by ritchie46** [comment]
Hmm.. I think we can check `objects` for `nan`. Currently we don't inspect objects as they are opaque to use.


```python
   # There's no efficient way to filter out the NAN at this point.
```
As we are dealing with python objects here. The fastest way to filter them is something like this:

```python
# maybe this fails as nan comparison probably doesn't work
na = float("nan")
df.filter(pl.col("my_object").apply(lambda x: x == na)
```

We cannot do this any faster, as we need to run python to be able to determine the type of an object.

**Comment by strangemonad** [comment]
sorry "performant" was a bad choice of terminology. What I meant to say is that you have a column that now contains nans but you can't run an expr like `pl.col("my_object").is_nan())` because the column type isn't float.

I'm not suggesting that you should be able to, I like that it's strict. But it is confusing from a usability perspective given how we created the table.

I appreciate that handling objects is cumbersome. I'm still brainstorming a bunch of ways that the experience might be made smoother to be honest

**Comment by stinodego** [comment]
> Is there an inherent reason why an object col with value None couldn't become an arrow null?

This is now what we do:

```python
import polars as pl

s = pl.Series([object(), None])
print(s)
```
```
shape: (2,)
Series: '' [o][object]
[
        <object object at 0x7f1ccffb4eb0>
        null
]
```

We will not support any operations on columns like `is_nan` on Object columns. If you end up with object columns, you'll have to `map_elements` to work with them or do some preprocessing before it ends up with Polars.

I think I'll close this for now. If you have a clear use case in mind, please open a new issue and explain with an example of how you would ideally use Polars to solve it.
