### ISSUE TITLE
Unpythonic Expr.str method names

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6120]
### Problem description

Some `Expr.str` methods have gratuitous name differences to corresponding Python `str` methods:

| Polars | Python |
| --- | --- |
| concat | join |
| ends_with | endswith |
| starts_with | startswith |
| to_lowercase | lower |
| to_uppercase | upper |
| n_chars | len (global func) |

I don't know the reason, maybe it's because this is how they are named in the Rust underlying library, but it would be nice if Polars used the same method names as Python.

Also `pl.Series.bin.starts_with` and `pl.Series.bin.ends_with`

### split, splitn, split_exact

I think `split` and `splitn` should be merged, just like in regular Python. Unclear if `split_exact` could be merged too.

### lengths

> **Warning**
> It actually returns a byte count, not character count. Easy to confuse with `len`, I think `size` (as in `pl.Series.estimated_size`), `n_bytes` or `nbytes` (as in Numpy) would be a better name.

Also `Series.arr.lengths` - returns item count, but I think `len` would be a more Pythonic name.

### methods taking regular expressions arguments

> **Warning**
> A number of methods have names similar to Python `str` methods, but they take regular expression arguments instead of string literals. I think this is dangerous because it's unexpected. In Python regular exceptions are only used in the `re` module, they are not common anywhere else (unlike JavaScript for example).

- `contains`
- `replace`
- `replace_all`

I'm not sure what better names these could have. Maybe add `_match` suffix like in `count_match`? Or add `re_` prefix to all methods?

Also `pl.Expr.str.contains` (regexp) is inconsistent with `pl.Series.bin.contains` (literal)

**Comment by alexander-beedie** [comment]
@stinodego: I saw that you're looking at some other breaking changes for a 0.16 - how about adding `startswith`,`endswith`,`lower`, and `upper` into the mix? (I'm not as convinced by the other two) ;)

**Comment by ritchie46** [comment]
We expose to different languages. Names must make sense for polars dsl, not the host language.

> I think split and splitn should be merged, 

They have different return types, therefore different methods names.

I just don't think that arguments of the std library operating on single objects should be copied in a dsl for a query language. It makes sense to use regex in string replacement. We are dealing with a DSL here and one could argue that not vectorization itself is un-pythonic.

If you have a suggestion for a method/argument we are receptive to those, but unpythonic is vague to me and doesn't really help us in achieving the goals of this library.

**Comment by ritchie46** [comment]
> @stinodego: I saw that you're looking at some other breaking changes for an eventual `0.16` release - how about adding `startswith`,`endswith`,`lower`, and `upper` into the mix? (I think those four make sense - I'm not as convinced by the other two) ;)

We already discussed `lower` which could be `is_lowercase` and `to_lowercase`, so I favoured explicitness.

**Comment by alexander-beedie** [comment]
> `is_lowercase` and `to_lowercase`

Ahh, right - given the two different contexts, I agree with that - immediately clear.

**Comment by 2-5** [comment]
> It makes sense to use regex in string replacement.

I've seen many times security bugs being introduced because of unexpected regular expressions. In particular because of `.` matching anything. Dots are used a lot (`filename.ext`, `www.site.com`, `team.1`). That is most likely not a concern in data science. But it could introduce subtle data correctness bugs, where you try to replace a literal `.` and you match unexpectedly something else. `replace(".gz", ".txt")` will match `filename.tgz`. People don't read the docs, they see `replace` and imagine it's the same as plain Python `replace`.

> We are dealing with a DSL here and one could argue that not vectorization itself is un-pythonic.

I completely agree with that. If I said something against vectorization, I was just not clear enough.

> unpythonic is vague to me

I think I understand now. There is a clear tension between Polars - a generic dataframe library usable from many languages (Rust, Python, JavaScript) and Polars - a Python dataframe library, Polars - a Rust dataframe library.

| Language | ends with |
| --- | --- |
| Rust | ends_with |
| Python | endswith |
| JavaScript | endsWith |

So you either must pick the same method name in all libraries (DSL approach), or you pick the method name used in the host language (Pythonic approach).

Personally I think making the library match more closely the host language is the best approach (it's just name aliases after all), but obviously you can argue the DSL case too.

**Comment by ritchie46** [comment]
Another big reason is that python's std library is inconsistent and we aim to provide a consistent API. We mostly use underscores where new words start (unless it is super common not to). 

In Python's std library it all depends: https://stackoverflow.com/questions/46003384/can-you-explain-the-weird-and-inconsistent-naming-of-functions-in-python-base-li

I want to be free of those restraints and define an API based on rationale, not on "python does it".

Regarding the regex arguments
 Maybe we should make regex opt-in by adding a regex keyword argument? I am open to a discussion on this.

**Comment by zundertj** [comment]
The regex point reminds me of #5418. Different methods, but same concern, that the regex parsing is not explicit.

**Comment by stinodego** [comment]
> Another big reason is that python's std library is inconsistent and we aim to provide a consistent API. 

This argument is most convincing to me. We want our API to be familiar to Python users, but no need to parrot the Python standard library with everything. There are definitely improvements to be made there and we can make them within Polars.

**Comment by ritchie46** [comment]
> That being said, I like `len` better than `n_chars`.

Again rust's default: https://doc.rust-lang.org/std/string/struct.String.html#method.len

A length is a O(1) attribute read. Computing the number of chars is 0(n). Maybe we should make `len` explicit as `bytes_len`?

I am in favor of the rust defaults here.

**Comment by 2-5** [comment]
> but no need to parrot the Python standard library 

But what about parroting the Rust standard library? I checked a few Polar names and they seem to match exactly the Rust library names. Don't get me wrong, that's perfectly fine and I have absolutely nothing against. It can also be the case that Rust names are more consistent, having only a few years and people behind them as opposed to the 30 years of random Python name evolution.

The point I'm making is that for a Python programmer typing `str.to_lowercase` feels weird, in the same way typing `str.lower` would feel weird for a Rust programmer (I think?). If naming is based on what feels right for a Rust programmer, that's perfectly fine, maybe it could be mentioned as a design feature.

It's possible that Python will be by far be the largest user of Polars. Which in my view could be an argument for minimizing Python surprises. There is a lot of muscle-memory in names like `startswith`, `lower` or `len`, and this naming issue will be mentioned again and again.

**Comment by stinodego** [comment]
I don't think the Python API and the Rust API need to match exactly. We could have `n_chars` in Rust, and have the same method be called `len` in Python. Each language API should be tuned to the needs of the users of that specific language. If we don't do that, we will lose out to other libraries that do.

There will probably still be a lot of overlap between the APIs even if we do diverge here and there. I don't think this is problematic at all. 

But I also don't mind breaking with Python 'defaults' if it improves the consistency within our own naming conventions. Multiple words should be separated by an underscore, for example. So I am not really in favor of changing `ends_with` to `endswith`.

**Comment by ritchie46** [comment]
Yes, rusts library is more consistent and no, we don't parrot it. We use `strip` in favor of `trim`.

I think this discussion is becoming a bit unproductive. Methods should define what they do and `str.to_lowercase` does this better than `str.lower` so we chose that.

We have API front-ends in rust, python, nodejs, js and soon R. 

Let's focus on making an API that makes sense for polars, not in which muscle memory you are accustomed to. 

Maybe I should aim my goals of that API.

- readability over saving keystrokes
- explicit over implicit
- aim for a single return dtype per expression
- API should nudge to fast code (slow code should be tedious to write)
- pure over in-place
- underscore over concattenated words
- minimize ambiguity

IMO `lower` is more ambigious that `to_lowercase`. This also leaves room for `is_lowercase` without anyone wondering how they differ.

If we have a discussion I think we should look at the points above and we may take inspiration from rust, python, numpy, pandas etc. But in the end we make a choice that aims to make a consistent API. Muscle memory is fluid.

**Comment by cmdlineluser** [comment]
> Regarding the regex arguments
Maybe we should make regex opt-in by adding a regex keyword argument? I am open to a discussion on this.

I think this makes sense - `regex: bool` is more explanatory than `literal: bool`

Would be nice for `str.split()` to have the same functionality. https://github.com/pola-rs/polars/issues/4819
