### ISSUE TITLE
`fill_null` affects dtype of columns without null values

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6144]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`DataFrame.fill_null` affects columns that do not even contain null values. This feels like a bug.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "id": [1,2],
        "int_val": [3, None],
        "float_val": [None, 6.0],
    }
)

result = df.fill_null(0.0)
print(result)
```

This will cast the `id` column to a float:

```
shape: (2, 3)
┌─────┬─────────┬───────────┐
│ id  ┆ int_val ┆ float_val │
│ --- ┆ ---     ┆ ---       │
│ f64 ┆ f64     ┆ f64       │
╞═════╪═════════╪═══════════╡
│ 1.0 ┆ 3.0     ┆ 0.0       │
│ 2.0 ┆ 0.0     ┆ 6.0       │
└─────┴─────────┴───────────┘
```

### Expected behavior

Expected result is to cast the `int_val` column to a float, since it contains a `null` value, but leave the `id` column alone:

```
shape: (2, 3)
┌─────┬─────────┬───────────┐
│ id  ┆ int_val ┆ float_val │
│ --- ┆ ---     ┆ ---       │
│ i64 ┆ f64     ┆ f64       │
╞═════╪═════════╪═══════════╡
│ 1   ┆ 3.0     ┆ 0.0       │
│ 2   ┆ 0.0     ┆ 6.0       │
└─────┴─────────┴───────────┘
```

Sidenote: an extra argument `columns` with which columns to fill would probably be a nice addition. It could be a mapping with column to fill value.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
This has already been discussed once. Polars needs to know the schema statically. The schema should be defined by the operation, not by the existence of missing values.

**Comment by stinodego** [comment]
Ah, I could not find an issue for this. I'll close this!
