### ISSUE TITLE
polars-sql 

### ISSUE THREAD

**Issue by wch001** [pola-rs/polars#6147]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

let df_sql =  context
            .execute(
                r#"
            SELECT category, avg(fats_g)over(PARTITION by category order by category) 
            FROM df
            
        "#,
            )?; 
返回的是 col(fats_g).over(category).sum() 正确的应该是 col(fats_g).sum() .over(category)

### Reproducible example

parse_sql_function

### Expected behavior

if let [FunctionArgExpr::Expr(sql_expr)] = args.as_slice() {
        //let e = apply_window_spec(parse_sql_expr(sql_expr)?, &sql_function.over)?;
        let e=parse_sql_expr(sql_expr)?;
        
        let f_expr=match (function_name.as_str(), sql_function.distinct) {
            ("sum", false) => e.sum(),
            ("first", false) => e.first(),
            ("last", false) => e.last(),
            ("avg", false) => e.mean(),
            ("max", false) => e.max(),
            ("min", false) => e.min(),
            ("stddev" | "stddev_samp", false) => e.std(1),
            ("variance" | "var_samp", false) => e.var(1),
            ("array_agg", false) => e.list(),
            // Special case for wildcard args to count function.
            ("count", false) if matches!(args.as_slice(), [FunctionArgExpr::Wildcard]) => {
                lit(1i32).count()
            }
            ("count", false) => e.count(),
            ("count", true) => e.n_unique(),
            _ => {
                return Err(PolarsError::ComputeError(
                    format!(
                        "Function {:?} with args {:?} was not supported in polars-sql yet!",
                        function_name, args
                    )
                    .into(),
                ))
            }
        };

        Ok(apply_window_spec(f_expr, &sql_function.over)?)
    } else {
        Err(PolarsError::ComputeError(
            format!(
                "Function {:?} with args {:?} was not supported in polars-sql yet!",
                function_name, args
            )
            .into(),
        ))
    }

### Installed versions

<details>
Replace this line with a list of feature gates
</details>
0.26.1

**Comment by ritchie46** [comment]
SQL is still in the works. You could make a PR and try to improve it.

For now I will close this issue, as we know it is not complete yet, having an issue for every function that is not supported bloats our issue board.
