### ISSUE TITLE
polars.Expr.str.strptime cannot parse "%b/%Y" format

### ISSUE THREAD

**Issue by cogitoxin** [pola-rs/polars#6151]
### Polars version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars will raise ComputeError: strict conversion to dates failed in following example but pandas works fine.

### Reproducible example

```python
import polars as pl
import pandas as pd

test = pl.DataFrame({
    'date_str': ["Jul/2020", "Dec/2020"]
})
test.with_column(pl.col("date_str").str.strptime(pl.Date, fmt="%b/%Y"))
```

### Expected behavior

```python
test = test.to_pandas()
pd.to_datetime(test['date_str'], format='%b/%Y')
```

This prints
0   2020-07-01
1   2020-12-01
Name: date_str, dtype: datetime64[ns]

### Installed versions

<details>

```
0.15.13
```

</details>

**Comment by mcrumiller** [comment]
It looks like `%b` requires a day, although this isn't documented. I tried a few cases:

```python
import polars as pl

formats = [
    ("2025", "%Y"),
    ("2025/12", "%Y/%m"),
    ("2025/12/05", "%Y/%m/%d"),
    ("2025/Dec", "%Y/%b"),
    ("2025/Dec/05", "%Y/%b/%d"),
]

for format in formats:
    try:
        s = pl.Series([format[0]]).str.strptime(pl.Date, fmt=format[1])
    except:
        print(f"{format} failed")
```
```
('2025/Dec', '%Y/%b') failed
```

**Comment by stinodego** [comment]
I don't think Polars does any parsing here; I believe this issue should be reported to the [`chrono`](https://github.com/chronotope/chrono) project.

**Comment by cogitoxin** [comment]
@mcrumiller 
Right, a workaround is manually add the day to the string and do the conversion:
```python
df.with_column(
        pl.concat_str([pl.lit('1/'), pl.col("date")]).keep_name()
    ).with_columns([
        pl.col("date").str.strptime(pl.Date, fmt="%d/%B/%Y"),
    ])
```

@stinodego 
Yes you are right, this gives ParseError(NotEnough)
```Rust
use chrono::{NaiveDate, ParseError};

fn main() -> Result<(), ParseError> {
    let date_only = NaiveDate::parse_from_str("2015/Sep", "%Y/%b")?;
    println!("{}", date_only);

    Ok(())
}
```

**Comment by ritchie46** [comment]
Polars also has implemented native parsers for performance reasons. I can explore adding this one to those.

**Comment by MarcoGorelli** [comment]
This would be useful, I'll give it a go (though if anyone else has already started work on this, please do let me know and I'll stop)

**Comment by mswastik** [comment]
Thanks for this, but similar fix is needed for `%B` as well.

**Comment by MarcoGorelli** [comment]
that's not a fixed-length format, you're currently required to specify the day as well
```python
In [5]: import polars as pl
   ...: import pandas as pd
   ...:
   ...: test = pl.DataFrame({
   ...:     'date_str': ["01/July/2020"]
   ...: })
   ...: test.with_columns(pl.col("date_str").str.strptime(pl.Date, format="%d/%B/%Y"))
Out[5]:
shape: (1, 1)
┌────────────┐
│ date_str   │
│ ---        │
│ date       │
╞════════════╡
│ 2020-07-01 │
└────────────┘
```

**Comment by mswastik** [comment]
Thanks I manually added the day `01` to the column then it got parsed correctly.
