### ISSUE TITLE
Bad rendering in VSCode Jupyter Data Viewer

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pola-rs/polars#6152]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have created the issue upstream (https://github.com/microsoft/vscode-jupyter/issues/12519) but I wanted to cross-link here for completeness.

The issue is that the following DataFrame:

```python
import polars as pl

df_pl = pl.DataFrame({
    "int_col": [1,2,3],
    "str_col": ["abc","def","ghi"],
    "list_col": [[1],[1,2],[1,2,3]],
    "struct_col" : [
        {"x":1, "y":2},
        {"x":3, "y":4},
        {"x":5, "y":6}]
    })
```

gets the following rendering in the Data Viewer in the Jupyter extension in VS Code:

![image](https://user-images.githubusercontent.com/44194839/211516785-b720245e-56f5-4594-ab72-64a0765824de.png)

### Reproducible example

```python
import polars as pl

df_pl = pl.DataFrame({
    "int_col": [1,2,3],
    "str_col": ["abc","def","ghi"],
    "list_col": [[1],[1,2],[1,2,3]],
    "struct_col" : [
        {"x":1, "y":2},
        {"x":3, "y":4},
        {"x":5, "y":6}]
    })
```

### Expected behavior

That the DataFrame is showed correctly.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.3.5
numpy: 1.21.5
fsspec: 2021.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.4.3```

</details>

**Comment by rk-exxec** [comment]
I am also experiencing this issue.
https://stackoverflow.com/questions/75070559/how-to-properly-display-a-polars-dataframe-in-vscode-jupyter-notebook-variables

**Comment by datenzauberai** [comment]
This happens because VSCode does not check the fully qualified name and tries to handle the `polars.DataFrame` just like a `pandas.DataFrame`. A workaround is to alias the `to_pandas` method with `toPandas` on the `polars.DataFrame`. See https://stackoverflow.com/a/76432740/11064332

**Comment by ion-elgreco** [comment]
@thomasfrederikhoeck the issue has been closed upstream with the merge of @datenzauberai 's PR, maybe close it here as well?
