### ISSUE TITLE
`Expr.when()`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#6161]
### Problem description

Reading [the current top comment](https://news.ycombinator.com/item?id=34296589) from the [recent polars related thread on HN](https://news.ycombinator.com/item?id=34275818) got me wondering:

The issue being that OP feels it is not clear `b` is being modified in the example:
```
df.with_column(
    pl.when(pl.col("a") <= 3)
      .then(pl.col("b") // 10)
      .otherwise(pl.col("b"))
)
```
If `Expr.when()` existed - could it be written as:
```
df.with_column(
    (pl.col("b") // 10)
       .when(pl.col("a") <= 3)
)
```
With `.otherwise()` defaulting to "root expression" - `pl.col("b")` in this case.

A couple of examples from the python tests:
```
pl.when(pl.col("foo") > 1).then(9).otherwise(pl.col("foo")).alias("foo")
```
could possibly be written as:
```
pl.col("foo").when(pl.col("foo") < 1).otherwise(9)
```
Which reads like Python's "ternary operator": `value if condition else other` 

Finally:
```
.with_column(
    pl.when(pl.col("type").arr.lengths() == 0)
      .then(pl.lit(None))
      .otherwise(pl.col("type"))
      .keep_name()
)
```
could possibly be written as:
```
.with_column(
    pl.col("type")
      .when(pl.col("type").arr.lengths() != 0)
      .otherwise(None)
)
```

It couldn't replace `pl.when().then()` because you can't really chain multiple conditions like you can with `.when().then().when().then().otherwise()`

It also seems like it would probably be quite complex to implement.

Just thought I would document it incase anybody else found it interesting.

Thank you.

**Comment by mcrumiller** [comment]
The issue here is with default aliasing, which I don't recall being well-documented in the user guide. In your `with_column` statement, you're getting a fresh new column, regardless of what you alias it with. I believe the first column in the `then` clause is what defaults as the output alias, but I'm not sure what the rules are. @ritchie46 could you clarify?

Here are some examples to show what the alias of the output column is by default:
```
import polars as pl
from polars import col, when

df = pl.DataFrame({
    'a': [0, 1, 2, 3, 4],
    'b': [5, 6, 7, 8, 9]
})

# returns column a
df.with_column(
    when(col('a') < 3).then(col('a'))
    .otherwise(col('b'))
)

# logical identical but includes column b in logic. Returns column a.
df.with_column(
    when((col('a') < 3) & (col('b') > 0)).then(col('a'))
    .otherwise(col('b'))
)

# still returns column a
df.with_column(
    when((col('b') > 0) & (col('a') < 3)).then(col('a'))
    .otherwise(col('b'))
)

# returns column b
df.with_column(
    when((col('b') > 0) & (col('a') >= 3)).then(col('b'))
    .otherwise(col('a'))
)
```

**Comment by zundertj** [comment]
NOTE: I'm probably overlooking some important things here, which could fall apart in more complex examples, so just a thought...

I think there is potential to make this type of operations a bit less cumbersome, it seems quite common to say "set column A to expression 1 if expression 2":

A quick and dirty way to implement:
```python
# define on expr

def when(self, predicate, value, *args):
    if args:
        value_if_false = args[0]
    else:
        value_if_false = self
    return pli.when(predicate).then(value).otherwise(value_if_false).alias(self._pyexpr.meta_output_name())
```

Usage:

```python
>>> df = pl.DataFrame({"a":[1,2,3], "b":[4,5,6]})
>>> df.with_column(pl.col("a").when(pl.col("b")==6, pl.lit(9)))
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 9   ┆ 6   │
└─────┴─────┘
>>> df.with_column(pl.col("a").when(pl.col("b")==6, pl.lit(9), pl.lit(10)))
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i32 ┆ i64 │
╞═════╪═════╡
│ 10  ┆ 4   │
│ 10  ┆ 5   │
│ 9   ┆ 6   │
└─────┴─────┘
```

This comes with the caveat of `Expr.meta.output_name()` (where I took the output_name call from):
 ```
It might not always be possible to determine the output name
as it might depend on the schema of the context. In that case
this will raise a ``pl.ComputeError``.
```
But I guess that in most cases, users will directly refer to a column name, or something else where this is defined (haven't come across this error myself).


Allowing `when` to take in also the values for True (and possibly) False is also something we could do in the current method, less verbose, but maybe also less clear?

```python
# currently
pl.when(pl.col("a") < 2).then( pl.lit(9)).otherwise(pl.lit(10))

# if when could take in values:
pl.when(pl.col("a") < 2, pl.lit(9), pl.lit(10))
```
