### ISSUE TITLE
Polars datatypes should be instantiated

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6163]
### Problem description

In Python, we have some advanced magic going on behind the scenes when it comes to handling Polars datatypes. This has some drawbacks that may lead to confusing behaviour for users:

```python
import polars as pl
from datetime import datetime

df = pl.DataFrame({'a': [1], 'b': [datetime(2023, 1, 1)]})

isinstance(df['a'].dtype, pl.Int64)  # False?
assert df['a'].dtype == pl.Int64  # Okay this works

isinstance(df['b'].dtype, pl.Datetime)  # True
assert df['b'].dtype == pl.Datetime  # This also works

map = {
    pl.Int64: 'x',
    pl.Datetime: 'y',
}

map[df['a'].dtype]  # Returns 'x'
map[df['b'].dtype]  # KeyError!
map[pl.Datetime]  # Returns 'y'
map[pl.Datetime(time_unit='us')]  # KeyError!

```

This behaviour stems from the fact that some dtypes are instantiated objects (mostly the ones that take arguments like `Datetime` and `List`), while others are uninstantiated (like `Int64`).

I think this is actually quite easy to fix: we should always work with instantiated DataType objects. If users specify a dtype input for e.g. a `Series`, we will instantiate it. `Series.dtype` will always return an instantiated object. `isinstance` will always work.

I only see benefits of this approach. But I'm sure the current setup is in place for a reason. Happy to get some feedback on this proposal!

**Comment by alexander-beedie** [comment]
I was thinking along the same lines, but I'd go even further :)

Have all of the individual (consistently instantiated as suggested) dtypes live off a single `DType` class, essentially as properties (so you could refer to them as `DType.Utf8`, `DType.Datetime`, etc ). This gives you autocomplete for types (which we don't have now), and can also easily support references to _groups_ of types such as `DType.NUMERIC`, `DType.TEMPORAL`. Can also have type-related methods live here as well.

This is a model I have developed in two shops now to great effect. (To give you an idea of the scope, I currently have a single master Type that can act as a superset of SQL, Polars, Pandas, Numpy, SQLAchemy, Arrow, and Python types _and_ allow ad-hoc translation between them, along with utility functions for classifying supertypes, etc). I'd be more than happy to build out something similar in Polars.

Can also maintain simple references in the `datatypes` module for backwards compatibility, eg: `Utf8 >> DType.Utf8`, and so on, to make such a transition pretty seamless.

**Comment by stinodego** [comment]
I discussed this with Ritchie, and he's on board with this idea!

> Have all of the individual dtypes (consistently instantiated, as suggested) live off a single `DType` (or other name ;) class, essentially as properties (so you could refer to them as `DType.Utf8`, `DType.Datetime`, etc ).

I think this is a layer of complexity that is not really necessary. I wouldn't want Polars users to type `pl.DType.Utf8`; yes, it will offer autocompletion, but it's also very verbose.

I think we can achieve everything we would want to by having a `DataType` hierarchy with superclasses/subclasses, and actually instantiating the classes. We actually already have such a hierarchy, but it doesn't really work well due to the instantiating issue.

I'm going to take a stab at a PR sometime during the coming weeks, and then we can take it from there.

**Comment by alexander-beedie** [comment]
> I think this is a layer of complexity that is not really necessary. I wouldn't want Polars users to type `pl.DType.Utf8`; yes, it will offer autocompletion, but it's also very verbose.

Agreed; I think our case at work is a little different - more of a _"one ring to rule them all"_ scenario, given the multiplicity of supported backends - which we don't need here :)
