### ISSUE TITLE
Errors in cloned LazyFrame result in "Logical plan already failed", when, technically, it hasn't already failed in the clone

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#6166]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When cloning a `LazyFrame` whose logical plan will fail, the failure is propagated to the clone, making it not fully “clone-ish”. So whereas the first instance of the df might print a useful error message when `collect()`ed, the clone will simply print `LogicalPlan already failed`.

### Reproducible example

```rust
fn main() -> WssResult<()> {
	use polars::prelude::*;
	let df = df!("a" => [1,2,3]).unwrap().lazy().select(&[col("b")]);
	println!("{:?}", df.clone().collect());
	println!("{:?}", df.clone().collect());
}
```

Output:
```
Err(NotFound(Owned("b")))
Err(ComputeError(Borrowed("LogicalPlan already failed")))
```

### Expected behavior

This is problematic because if you reuse `LazyFrame`s (via cloning) and then encounter an error, the error does not contain a description of the problem. Above, only the first error gives the user information they can use to solve the problem; the second does not. Ideally, clones of `LazyFrame`s would not share their "error already encountered" state, or, if sharing, clones’ error message would include the original error message in their own "already failed" message, e.g., `"LogicalPlan already failed with 'NotFound(Owned("b"))'"`.

### Installed versions

```toml
polars = { version = "0.26.1", features = [
	"csv-file",
	"dtype-struct",
	"json",
	"lazy",
	"strings",
	"temporal",
] }
```

**Comment by ritchie46** [comment]
Thanks for the issue report. Could you make a PR for a fix?

**Comment by rben01** [comment]
Sure. One question: in which situations will the “logical plan already failed” message fire? Since collecting a LazyFrame consumes it, am I correct that the only way for the plan to already have failed is for the LazyFrame to have been cloned? Or is there another avenue by which a LazyFrame’s logical plan can be executed twice?

**Comment by rben01** [comment]
Ok, I think I understand the underlying difficulty. `PolarsError` can't be `Clone`, so in order to return the `LogicalPlan`’s underlying error from functions returning a `PolarsResult` while having ownership work out, one basically has two choices:
1. You can change `PolarsResult` to have its error type be some sort of `Cow`-like thing that can make the borrowed-or-owned decision at runtime (but not *the* `Cow`, because `PolarsError` can't be cloned). Something like `type PolarsResult<T> = Result<T, NoCloneCow<PolarsError>>;` where `NoCloneCow` is a `Cow` without an `into_owned()`.
2. Or, you can do what polars currently does, which is to move the underlying error out.

The current solution is to move the error out of a `Some`, leaving a `None` in its place, which leads to an error message with little info possible other than, essentially, “you already took the error out”. I just submitted a PR that modifies this behavior to leave behind not a `None`, but the debug-string of the error we're moving out so we can continue to read it in the future.

**Comment by rben01** [comment]
> Sure. One question: in which situations will the “logical plan already failed” message fire? Since collecting a LazyFrame consumes it, am I correct that the only way for the plan to already have failed is for the LazyFrame to have been cloned? Or is there another avenue by which a LazyFrame’s logical plan can be executed twice?

I'll just clarify this point to any future readers before closing this out. I had though that a LogicalPlan was itself lazy, building up just the list of commands to run with no error checking, until `collect()` was called, at which point they were all sequenced and run. So I was confused that one plan would know a clone of it had already read off its error message.

However the reality is that each operation on a LazyFrame immediately updates the LogicalPlan (and thus the schema) of the LazyFrame, and if that fails then you immediately get a LogicalPlan::Error. In other words, operations on a LazyFrame sequence, but don't run, the operations. If any operation on a LazyFrame would encounter an error (due to e.g., a missing column), then its logical plan will immediately be an error and the clone will also have that erroneous logical plan. But because the error is behind an `Arc<Mutex<_>>`, the error isn't really cloned (and indeed, `PolarsError` cannot be cloned), it just has its ref count incremented. And so when one LazyFrame reports its error and has to move the error out of the `Arc<Mutex<_>>`, its clones no longer contain the error to report to the user — it's really gone.
