### ISSUE TITLE
Broken API documentation links.

### ISSUE THREAD

**Issue by Carbocarde** [pola-rs/polars#6167]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

 #5433 was a breaking change for API documentation links.

This can be addressed in polars-owned sites like https://github.com/pola-rs/polars-book/pull/222, but leaves a bunch of broken sites over the internet ([Example](https://stackoverflow.com/a/73359338/20969178)).

I'm not sure what the resolution is (if it's possible to forward traffic from the old links to new ones), but I wanted to make you aware of the root cause of issues like https://github.com/pola-rs/polars-book/pull/222.

### Reproducible example

Broken link: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.unique.html?highlight=unique

### Expected behavior

Content at broken link or redirected to: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.unique.html

### Installed versions

N/A

**Comment by alexander-beedie** [comment]
@ritchie46 / @stinodego: any experience with Frontmatter redirects? I did some reading around and it might be possible to fix this, given that the API docs are living on GitHub?  https://github.com/github/docs/blob/main/contributing/redirects.md#redirects-across-files

**Comment by stinodego** [comment]
No experience with that, unfortunately.

Thanks for the report, @Carbocarde ! I'm sure we'll figure something out.

**Comment by Carbocarde** [comment]
[sphinx-redirects](https://documatt.gitlab.io/sphinx-reredirects/#) may be helpful since it seems to be built for this.

**Comment by ritchie46** [comment]
I think we can close this now.
