### ISSUE TITLE
Allow negative values of `n` when calling `.head` and `.tail`

### ISSUE THREAD

**Issue by thomascamminady** [pola-rs/polars#6171]
### Problem description

It is currently not possible to call `.head` and `.tail` with negative inputs. In `pandas`, however, that is possible and equivalent to returning [" all rows except the last |n| rows"](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html) or ["all rows except the first |n| rows"](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html), respectively. 

Here is a minimal working example illustrating the situation
```python
import polars as pl 
import pandas as pd

polars_df = pl.DataFrame({"A":[1,2,3,4,5,6,7,8,9,10]})
pandas_df = pd.DataFrame({"A":[1,2,3,4,5,6,7,8,9,10]})

print(polars_df.head(3))
print(pandas_df.head(3))
```
This behaves as expected and returns the same components of the dataframe.
However, in `pandas`, 
```python
print(pandas_df.head(-3))
```
prints
```python
   A
0  1
1  2
2  3
3  4
4  5
5  6
6  7
```
and this feature is currently not available in `polars`. 

Since this is a reasonable use case, I think some functionality that allows for returning all rows except the last/first |n| rows would enrich the library. 

(*Remark: This is my first time contributing to an open source project.)*

**Comment by ritchie46** [comment]
For eager we can support them and immediately translate them to an absolute integer. For lazy this is not possible or wanted as we don't know the length of the `DataFrame`.

**Comment by thomascamminady** [comment]
Thanks for implementing this!

**Comment by alexander-beedie** [comment]
> Thanks for implementing this!

@thomascamminady: Thanks for taking the time to request the feature, along with a nice clear rationale/explanation and some helpful examples! That always helps.

> (Remark: This is my first time contributing to an open source project.)

Good start ;)
