### ISSUE TITLE
Support for ParquetDatasetV2

### ISSUE THREAD

**Issue by dominikpeter** [pola-rs/polars#6172]
### Problem description

Seems like ParquetDatassetV2 is not supported. I got the following error when using it with pl.scan_ds:

exceptions.ComputeError: PyErr { type: <class 'AttributeError'>, value: AttributeError("'_ParquetDatasetV2' object has no attribute 'to_table'"), traceback: Some(<traceback object at 0x0000024D2D913A40>) }

I also had better performance when using it in combination with Delta tables when I filtered the table:

dt = DeltaTable(file_url)
dataset = pq.ParquetDataset(
    dt.file_uris(), use_legacy_dataset=False, memory_map=False, filters=[("orderDate", ">", "2022-12-01")]
)
df1 = pl.from_arrow(dataset.read())

faster than:

df2 = (
    pl.scan_delta(path)
    .filter(pl.col("orderDate") > "2022-12-01")
    .collect()
)

Would be nice to support it and take advantage of the filtering.

**Comment by inigohidalgo** [comment]
Hi @dominikpeter where was this resolved? I am currently getting the same error using `_ParquetDatasetV2`

**Comment by ziadmoubayed** [comment]
Hi @dominikpeter was this resolved?
