### ISSUE TITLE
Weird behavior of `pl.sum(REGEX)`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#6176]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Actually I dont know if it has been done on purpose, but `pl.sum(REGEX)` will aggregate the sum value **vertically**.
I would not expect something like that. 

The doc explains that depending of the data type of `column`, you get a different type of aggregation: 
  Column(s) to be used in aggregation.
  This can be:

  - a column name, or Series -> aggregate the sum value of that column/Series.
  - a List[Expr] -> aggregate the sum value horizontally across the Expr result.
 
Maybe a regex should follow the same behavior as `List[Expr]`
Otherwise the documentation could explains the behavior when column name is in fact a regex.

What do you think ?

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'A1' : [1,2], 'A2': [0, 1]})

df.select(pl.sum('^A[0-9]+$')).columns # ['A1', 'A2']

df.select(pl.sum(['^A[0-9]+$'])).columns # ['sum']
```

### Expected behavior

`['sum']` is both cases

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment]
This behavior is correct. A regex expansion always expand that expression as if it was a single expression.

You would need a fold or pass columns by liat.

**Comment by gab23r** [comment]
I understand, we can close then
