### ISSUE TITLE
`PanicException` in `write_csv` when directory with same name exists

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6181]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When passing a path to `DataFrame.write_csv`, and there already exists a directory with that same name, a `PanicException` occurs.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3]})
path = "somedir"  # this path already exists and is not a file but a directory
df.write_csv(path)
# PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }
```

### Expected behavior

I expect a neat error message that tells me a directory already exists at the specified path.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Hah! Just discovered that Python has a dedicated `IsADirectoryError` exception... one sec ;)
