### ISSUE TITLE
change DataFrame.schema function for less copy

### ISSUE THREAD

**Issue by yutiansut** [pola-rs/polars#6186]
### Problem description

here is the first function in DataFrame
```rust
    pub fn schema(&self) -> Schema {
        Schema::from(self.iter().map(|s| s.field().to_owned()))
    }
```
the ```Cow``` .to_owned will move the dataframe itself, so we should have the df.clone().lazy() to get a lazyframe

however, when we use
```rust
    pub fn schema2(&self) -> Schema {
        Schema::from(self.iter().map(|s| s.field().to_mut().clone()))
    }
```

and also change the plan builder:
```rust
    pub fn from_existing_df2(df: Arc<DataFrame>) -> Self {
        let schema = Arc::new(df.schema2());
        LogicalPlan::DataFrameScan {
            df: df,
            schema,
            output_schema: None,
            projection: None,
            selection: None,
        }
        .into()
    }
```

then, we can use the ```Arc<DataFrame>``` to create a ```LazyFrame```

```rust
fn to_lazy(df: Arc<DataFrame>) -> LazyFrame {
    let lp = LogicalPlanBuilder::from_existing_df2(df).build();
    LazyFrame {
        logical_plan: lp,
        opt_state: Default::default(),
    }
}
```

this will reduce the ```clone``` when we try to create large number of ```lazy function```, espcially in py-polars or polars itself

**Comment by yutiansut** [comment]
@ritchie46  when we use <Arc> on a huge-sized dataframe, this will reduce lots of memory on copy

**Comment by stinodego** [comment]
The implementation has greatly changed since this issue was opened. I'll close this as completed for now. If this is still a problem, please open a new issue!
