### ISSUE TITLE
DataFusion integration

### ISSUE THREAD

**Issue by oersted** [pola-rs/polars#6197]
### Problem description

It seems like some solid progress was done during 2021 but was deleted in 2022 without clear explanation.

DataFusion seems to have some critical features that Polars lacks and are often requested:
* Proper support for larger-than-RAM datasets
* Support for stream processing
* Distribution via Ballista
* SQL support

Most of these features are partially implemented at present, but progress is committed and rapid.

In my opinion Polars has the better API and seems to have better performance for in-memory workloads. Polars is quickly becoming the de-facto data engineering framework in Rust, and is being praised as the next-gen in Python.

But the great work being done over at the Arrow team to support larger datasets shouldn't be dismissed. If properly integrated as a backed execution engine, Polars could become the first legitimate alternative and upgrade to Spark, as it already is to Pandas.

**Comment by ritchie46** [comment]
We are working on these:

 *    Proper support for larger-than-RAM datasets
 *   SQL support

I don't want polars to depend on on the datafusion crate, that is a complexity that is not needed. We are both dependent on arrow, so we could swap memory.

I just discussed with the datafusion maintainers yesterday and we are going to see if we can bridge the gap between the two arrow crates a bit.

Integration via arrow is very much  possible, but transpiling logicalplans has been removed from the repository as it is too much complexity for the project and not fits our roadmap.

**Comment by oersted** [comment]
That makes sense, thank you. It's great to hear you are working closely with the DataFusion team.

Is there anywhere where progress for larger-than-RAM support is tracked?
We'd like to integrate Polars into our data engineering workflows, mostly replacing Spark. We do not need the distributed compute, but our data rarely fits memory.

**Comment by surister** [comment]
@oersted Mind tell me the rationale of replacing spark? I'd love to have a chat about this if you dont mind.
