### ISSUE TITLE
Schema inference using default constructor

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6207]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The code only returns `ShapeError` if `right_values` < 50 which is the default `infer_schema_length` set in `DataFrame.__init__`. 

### Reproducible example

```python
right_values = 50
data = [
    {'label': 'l', 'tag': 't', 'ref': i, 'parent': [{'ref': j +2, 'tag': 't', 'ratio': j + 12 % 100} for j in range(20)]} 
for i in range(right_values)]

data.extend([{'tag': 't', 'ref': 99, 'state': 'UNPROCESSED', 'state_c': 'PENDING'} for i in range(10)])
df = pl.DataFrame(data, columns={
    'label': pl.Utf8,
    'tag': pl.Utf8,
    'ref': pl.Int64,
    'parents': pl.List(pl.Struct({'ref': pl.Int64, 'tag': pl.Utf8, 'ratio': pl.Float64})),
})
```

### Expected behavior

Returns `ShapeError` since the data doesn't match `columns`.

Since I specified columns, I assumed there would be more intensive check to insure df validity if the data has some inconsistencies. Furthermore it does not seem like there is any way to insure further check using constructor parameters if needed

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 5.0.0
pandas: 1.4.0
numpy: 1.21.1
fsspec: 2021.10.0
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> Since I specified columns, I assumed there would be more intensive check to insure df validity if the data has some inconsistencies.

Typically you provide a schema to ensure that the types and/or columns given in the schema are used by the DataFrame exactly - not to _validate_ incoming data.

I do think there is a problem here though - I would expect the constructor to _ignore_ the additional columns, given that an explicit schema has been provided. I'll take a look and see what we can do about this, as I don't think raising a `ShapeError` is ideal.

**Comment by PieReissyet** [comment]
> I do think there is a problem here though - I would expect the constructor to ignore the additional columns, given that an explicit schema has been provided. I'll take a look and see what we can do about this, as I don't think raising a ShapeError is ideal.

Yes that's exactly what I meant. I am not a fan of the ShapeError either, only mentioned it since it's the default behavior when you are still in the `infer_schema_length` range

**Comment by alexander-beedie** [comment]
Gotcha; I'm looking at it now and I think it will be a straightforward fix. 
Thanks for the bug report  :)
