### ISSUE TITLE
Memory Issue when exploding null columns

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6208]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Script consume all my memory (16Gb) while exploding `List` column with null values.

### Reproducible example

```python
import polars as pl


data = [
    {'label': 'l', 'tag': 't', 'ref': 1, 'parent': [{'ref': 1, 'tag': 't', 'ratio':  62.3}]},
    {'label': 'l', 'tag': 't', 'ref': 1, 'parent': None}
]

df = pl.DataFrame(data, columns={
    'label': pl.Utf8,
    'tag': pl.Utf8,
    'ref': pl.Int64,
    'parents': pl.List(pl.Struct({'ref': pl.Int64, 'tag': pl.Utf8, 'ratio': pl.Float64})),
})
df.explode('parents')
```

### Expected behavior

Not to consume my entire RAM

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 5.0.0
pandas: 1.4.0
numpy: 1.21.1
fsspec: 2021.10.0
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: <not installed>

```

</details>

**Comment by TommyNeeld** [comment]
This is an issue specific to exploding a list containing dictionaries. Exploding lists with empty values is covered by unit test [test_explode_empty_df_3902()](https://github.com/pola-rs/polars/blob/5b310e2e3382078274f689441782a3c698eac5c2/py-polars/tests/unit/test_explode.py#L19).

The error induced in debug mode when running:
```
df = pl.DataFrame(
        [
            {"id": 1, "nested": [{"g": 23 }]},
            {"id": 2, "nested": [{"g": 23}]},
            {"id": 3, "nested": None},
        ]
    )
df.explode("nested")
```
Is:
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', .../polars/polars/polars-core/src/chunked_array/ops/explode.rs:365:17
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/using-polars/polars/py-polars/polars/internals/dataframe/frame.py", line 4796, in explode
    return self.lazy().explode(columns).collect(no_optimization=True)
  File ".../polars/py-polars/polars/utils.py", line 394, in wrapper
    return fn(*args, **kwargs)
  File ".../polars/using-polars/polars/py-polars/polars/internals/lazyframe/frame.py", line 1167, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: attempt to subtract with overflow
```
Which is pointing at line 365 in [polars/polars-core/src/chunked_array/ops/explode.rs](https://github.com/pola-rs/polars/blob/5b310e2e3382078274f689441782a3c698eac5c2/polars/polars-core/src/chunked_array/ops/explode.rs#L365) where a subtraction `for _ in 0..(capacity - (value_count - offsets[0]) as usize - empty_count)` is occurring which I assume is causing the overflow.


Regardless of the error, the behaviour for dictionaries is in general unexpected:
```
df = pl.DataFrame(
        [
            {"id": 1, "nested": [{"foo": "bar" }]},
            {"id": 1, "nested": [{"foo": "bar"}, {"bar": "foo" }]},
        ]
    )
df.explode("nested")
```
gives:
```
┌─────┬──────────────┐
│ id  ┆ nested       │
│ --- ┆ ---          │
│ i64 ┆ struct[2]    │
╞═════╪══════════════╡
│ 1   ┆ {null,"bar"} │
│ 1   ┆ {null,"bar"} │
│ 1   ┆ {"foo",null} │
└─────┴──────────────┘
```
when the following output is expected (like Pandas):
```
┌─────┬───────────────┐
│ id  ┆ nested        │
│ --- ┆ ---           │
│ i64 ┆ struct[2]     │
╞═════╪═══════════════╡
│ 1   ┆{"foo": "bar"} │
│ 1   ┆{"foo": "bar"} │
│ 1   ┆{"bar": "foo"} │
└─────┴───────────────┘
```

Maybe the explode functionality cannot currently handle dictionaries.

**Comment by PieReissyet** [comment]
I would not say that the behavior while exploding list of struct is unexpected since you have keys mismatch in your column, if you unnest that:
```python
df = pl.DataFrame(
        [
            {"id": 1, "nested": [{"foo": "bar" }]},
            {"id": 1, "nested": [{"foo": "bar"}, {"bar": "foo" }]},
        ]
    )
df.explode("nested").unnest('nested')
```
it returns

```
shape: (3, 3)
┌─────┬──────┬──────┐
│ id  ┆ bar  ┆ foo  │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ str  ┆ str  │
╞═════╪══════╪══════╡
│ 1   ┆ null ┆ bar  │
│ 1   ┆ null ┆ bar  │
│ 1   ┆ foo  ┆ null │
└─────┴──────┴──────┘
```
which is what you can expect since you convert a `List` of `Struct` to a `Struct` and both lines have different keys that are converted to columns.

It's the output of a Struct column type that can be a bit confusing and that does make a lot of sense before unnesting it.

However I do agree that's it pretty unhandy compared to what pandas returns since most of the time each rows have dicts whose keys do not always match and it can leads to pretty heavy dataframe column wise.

It would be really great not to have this kind of behavior where all the different keys are filled with null values before actually unnesting the column.
