### ISSUE TITLE
When using `scan_parquet` for S3 files, the scan succeeds but the `collect` doesn't

### ISSUE THREAD

**Issue by MarceColl** [pola-rs/polars#6212]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm interested in streaming parquet files directly from S3 by using the Lazy interface. However it seems to me like this is currently broken. I have a simple minio instance locally and a bucket created.

The initial creation of the lazy dataframe works without a problem, however when doing a `collect()` on this ldf I get an error.

```
ComputeError: PyErr { type: <class 'PermissionError'>, value: PermissionError('Forbidden'), traceback: Some(<traceback object at 0x7faaf2d21000>) }
```

So it seems to me like whatever connection/creds/session we are using for the scan is not being properly propagated at `collect()` time. 

### Reproducible example

```python
Install polars and s3fs.

Setup a local minio

docker run -p 9000:9000 -p 9001:9001 \
  quay.io/minio/minio server /data --console-address ":9001"
```

Go to `http://localhost:9001/buckets` and create a bucket named `testbucket` and then run:

```
import polars as pl
import s3fs

conn_data = { 'key': 'minioadmin', 'secret': 'minioadmin', 'client_kwargs': { 'endpoint_url': 'http://localhost:9000' }}

fs = s3fs.S3FileSystem(**conn_data)
df = pl.DataFrame({'data': list(range(500))})

s3_path = "s3://testbucket/file.parquet"

with fs.open(s3_path, "wb") as f:
    df.write_parquet(f)

dfl = pl.scan_parquet(s3_path, storage_options=conn_data)
print("SCHEMA", dfl.schema)
dfl.collect()
```

```
SCHEMA {'data': Int64}
Traceback (most recent call last):
  File "/home/mcoll/capchase/code/client-monorepo/apps/metrics-api/test.py", line 16, in <module>
    dfl.collect()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/polars/utils.py", line 391, in wrapper
    return fn(*args, **kwargs)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 1165, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: PyErr { type: <class 'PermissionError'>, value: PermissionError('Forbidden'), traceback: Some(<traceback object at 0x7fc444f03040>) }
```

As you can see, it reads the file correctly when getting the schema, but then it doesn't propagate properly.

I don't know much about the codebase, but it seems to me like the initial schema scan is done with the given `storage_options` but that is then discarded here:

https://github.com/pola-rs/polars/blob/359b02692ef840d34040d937933fd0b5d34102be/py-polars/polars/internals/anonymous_scan.py#L139-L150

### Expected behavior

The rest of the lazy dataframe operations should use the same `storage_options` that were passed to `scan_parquet`.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-6.1.4-arch1-1-x86_64-with-glibc2.36
Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.24.1
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by MarceColl** [comment]
If you guys think this is the problem I may be able to dedicate some time to fix it. But I'd love some feedback on if this is the way to move forward :)

**Comment by ritchie46** [comment]
That Indeed seems to be the problem. I think the function we pickle also must be capturing the storage options in its environment.

I'd more than welcome your contribution on this.

**Comment by MarceColl** [comment]
@ritchie46 if you could check the PR, the fix does solve the problem in my test file but I'm unsure if there is something else I should do/check. I also left a question about the tests.
