### ISSUE TITLE
Add Read support for Apache Iceberg

### ISSUE THREAD

**Issue by nazq** [pola-rs/polars#6227]
### Problem description

Would like to see read support for Apache Iceberg similar to the support for delta. Cc @asheeshgarg

**Comment by nazq** [comment]
Discussion on Rust iceberg sdk https://github.com/apache/iceberg/issues/5122

**Comment by Guillem96** [comment]
Is this feature already in the Polars team roadmap?

**Comment by luancaarvalho** [comment]
Could someone please advise where we can access the roadmap and verify if iceberg has been included in the Polars roadmap?

**Comment by tomaszdudek7** [comment]
I'd love to have it!

**Comment by alexander-beedie** [comment]
> Would like to see read support for Apache Iceberg similar to the support for delta.

FYI: I'm looking at further generalising our database support in Python (ref: https://github.com/pola-rs/polars/issues/10121). Are you intending to use directly from Rust, or the usual Python API? (If the latter, which driver do you usually use?)

**Comment by bitsondatadev** [comment]
@alexander-beedie, I noticed Delta is implemented in Python + Arrow.

Iceberg comitters are working on improving Arrow compatibility, but I wonder if you all prefer Rust support? This is [also almost complete as well](https://github.com/apache/iceberg-rust). What's the best way forward in your opinion as both options are available?

- Brian (DevRel Iceberg)

**Comment by bitsondatadev** [comment]
Also related: apache/iceberg#7067

**Comment by luancaarvalho** [comment]
In my case, python @alexander-beedie

**Comment by chitralverma** [comment]
My 2 cents on the topic, we can mimic the way we implemented things for delta and keep this on the python side of things via the `scan_ds`

**Comment by universalmind303** [comment]
a datafusion based project [glardb](https://github.com/GlareDB/glaredb) recently added iceberg support. Looks like it may be easy to port their [datafusion logic](https://github.com/GlareDB/glaredb/pull/1382/files#diff-bad171d1c866bf306008c03e85840223b096d394c3f7ae61d2001e190026cf20) over to polars. The dependencies also seem pretty lightweight, only `iceberg` which only depends on `apache-avro`. _(no dependencies on `apache-arrow`!)_

**Comment by Fokko** [comment]
I got a working version of Python.

> a datafusion based project [glardb](https://github.com/GlareDB/glaredb) recently added iceberg support. Looks like it may be easy to port their [datafusion logic](https://github.com/GlareDB/glaredb/pull/1382/files#diff-bad171d1c866bf306008c03e85840223b096d394c3f7ae61d2001e190026cf20) over to polars.

Unfortunately, a lot of the Rust implementations out there are far from complete. Looking at the implementation at GlareDB, a couple of things are missing:

- No field-id schema resolution, and therefore it cannot read tables with evolved schemas (or it causes correctness issues!) 
- Pruning of partitions
- Pruning of files, by using the metrics stored in the manifest files

The implementation only does file discovery, which is a pity since Iceberg has so much to offer.

**Comment by alexander-beedie** [comment]
> Iceberg comitters are working on improving Arrow compatibility, but I wonder if you all prefer Rust support? 

Apologies, and thanks for reaching out to us! This seemed to slip my radar; looks like @Fokko is well underway building a `scan_` based approach in the Rust layer already, which looks exciting. For my own part I was looking at generalising our SQL connectivity (so we can better interop with user-instantiated connections), so I'll be looking mostly at the Python/relational side (I understand there is also a SQL interface).

**Comment by Fokko** [comment]
Hey @alexander-beedie, thanks for jumping in here. What kind of SQL interface are you thinking of?

We're supporting SQL-like syntax for the expressions:

```python
large_rides_in_march = tbl.scan().filter("dt >= '2023-01-01' and dt < '2023-04-01' and passenger_count > 4").to_arrow()
```

We could also accept this kind of expression Polars. Also, DuckDB has recently opened up [their Iceberg support](https://github.com/duckdblabs/duckdb_iceberg), however, this is also still in an experimental state and many of the features that make Iceberg shine are still missing.

**Comment by alexander-beedie** [comment]
> Hey @alexander-beedie, thanks for jumping in here. What kind of SQL interface are you thinking of?  // ...

Great, I see it now - thanks for the clarification. I think I was conflating a quickly scanned article involving DuckDB & Iceberg with there actually being a fully-fledged SQL query interface (and associated python-side DBAPI -or equivalent- drivers), in which case things would "just work" once we start accepting user-created connection objects and their associated queries.

Looks to me like the `scan_` PR you're working on is the way to go here as it'll be able to take advantage of a fuller range of features; I will defer on the implementation details review/comments to those with more Rust expertise than myself (@ritchie46, @orlp, @universalmind303), as I am merely a casual dilettante in that arena ;)
