### ISSUE TITLE
.str.strptime(pl.Datetime('ns')) loses nanoseconds

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6228]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`.str.strptime` loses nanoseconds, even if I put `Datetime('ns')`

### Reproducible example

```python
>>> pl.Series(['2020-01-01 00:00:00.123456789']).str.strptime(pl.Datetime('ns'))
shape: (1,)

datetime[μs]

2020-01-01 00:00:00.123456
```

### Expected behavior

```
shape: (1,)

datetime[ns]

2020-01-01 00:00:00.123456789
```

If you agree that this would be the expected behaviour, mind if I try making a PR?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by alexander-beedie** [comment]
Looks like a bug to me - if you think you can make a PR to fix it that would be great... :)
