### ISSUE TITLE
Negative dates can't be parsed

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6238]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Negative dates are supported, e.g.:
```python
ser = pl.Series(['0001-01-01']).str.strptime(pl.Datetime('ms'), fmt='%Y-%m-%d')
td = pl.Series([1_000_000_000_000], dtype=pl.Duration('ms'))
diff = ser - td
print(diff)
```
outputs
```
shape: (1,)
Series: '' [datetime[ms]]
[
        -0031-04-24 22:13:20
]
```

However, it can't be read back in:

### Reproducible example

```python
pl.Series(['-0031-04-24 22:13:20']).str.strptime(pl.Datetime('ms'), fmt='%Y-%m-%d %H:%M:%S')  # works
pl.Series(['-0031-04-24']).str.strptime(pl.Datetime('ms'), fmt='%Y-%m-%d')  # fails
```

### Expected behavior

```
shape: (1,)
Series: '' [datetime[ms]]
[
        -0031-04-24 00:00:00
]
```

Would you be open to supporting negative dates, if the leading character is `-`?

I'm not asking for, e.g. `04--0031-24`, where the negative number is in the middle of the string. But if it's just at the beginning of the string, the format starts with `%Y`, then could this be supported?

### Installed versions

<details>

```
In [1]: pl.show_versions()
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8.1
matplotlib: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Thanks for the issue report. Is this supported in rust `chrono`? If it isn't we might need to take this upstream.

**Comment by MarcoGorelli** [comment]
I think so because it does work in some cases

Narrowing it down a bit further:
```python
pl.Series(['-0031-04-24 22:13:20']).str.strptime(pl.Datetime('ms'), fmt='%Y-%m-%d %H:%M:%S')  # works
pl.Series(['-0031-04-24']).str.strptime(pl.Datetime('ms'), fmt='%Y-%m-%d')  # fails
```

Taking a closer look

**Comment by ritchie46** [comment]
Right. Then it is our own parsers. They were added because the chrono ones are quite slow.

**Comment by MarcoGorelli** [comment]
OK - I _might_ have this figured out, will open a PR soon-ish
