### ISSUE TITLE
use arithmetric dunders for series of Objects

### ISSUE THREAD

**Issue by sslivkoff** [pola-rs/polars#6252]
### Problem description

Hi. I'm converting some pandas code to polars. I ran into some issues with large int representation.

When numpy is creating an array containing large ints (larger than int64), it uses a dtype of `object`. The resulting array can use standard arithmetic operations via the dunder methods for those inner int objects.

```python
large_ints = [
    1111112222222333333444444,
    1111112222222333333444444,
]
array = np.array(large_ints)

print('dtype:', array.dtype)
print()
print('+ 2:', array + 2)
print('- 2:', array - 2)
print('* 2:', array * 2)
print('// 2:', array // 2)
print('% 2:', array % 2)
```

```bash
dtype: object

+ 2: [1111112222222333333444446 1111112222222333333444446]
- 2: [1111112222222333333444442 1111112222222333333444442]
* 2: [2222224444444666666888888 2222224444444666666888888]
// 2: [555556111111166666722222 555556111111166666722222]
% 2: [0 0]
```

This behavior is desirable in contexts where you need to avoid lossy float conversion.

Polars can create a series of large ints by using the `pl.Object` dtype. But it does not support arithmetric operators on these series.

```python
large_ints = [
    1111112222222333333444444,
    1111112222222333333444444,
]

large_series = pl.Series(large_ints, dtype=pl.Object)

# each of these gives
# NotImplementedError: Conversion of polars data type Object to Python type not implemented.
large_series + 2
large_series - 2
large_series * 2
large_series // 2
large_series % 2
```

Polars supports these operations for other dtypes.

```python
small_ints = [
    1234,
    1234,
]
small_series = pl.Series(small_ints)

# these operations work fine
small_series + 2
small_series - 2
small_series * 2
small_series // 2
small_series % 2
```

What do you think of supporting `+ - * // %` for `pl.Object` series when the appropriate dunder methods are present on those inner objects?

Thanks

**Comment by taylorfturner** [comment]
Have the same question / issue here -- @sslivkoff any word on this through other channels potentially? Thanks!

**Comment by sslivkoff** [comment]
> The issue has nothing to do with dunders and everything to do with Objects. Anything that is an object doesn't fit into polars memory model and so none of its native methods can operate on it. If you want to do anything with Objects then (possibly with a few exceptions that I'm not aware of) the only way to do it is through `map_elements`.

this is related to dunders because the objects' arithmetic dunders would the way for polars to support arithmetic operations on columns of type `pl.Object`. if the contained objects do not implement arithmetic dunders, then support is not possible

a major usecase for this would be supporting expressions on large integers that do not fit in polars' native `dtype`s. python's native `int` object type does not have an upper bound. the `int.__add__()` dunder could be used to reduce expression sums programmatically
