### ISSUE TITLE
The result of the filter is incorrect

### ISSUE THREAD

**Issue by LinZuan** [pola-rs/polars#6259]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

The result of the filter is incorrect

get lazyframe by LazyFrame::scan_parquet, and filter it I found lack of some data.
when I use ParquetReader::new(file).read_parallel(ParallelStrategy::Auto).finish().unwrap().lazy(), filter it too, the result is correct

### Reproducible example

```
fn main() {
    let path = "data.snappy.parquet";

    let lf = LazyFrame::scan_parquet(path, Default::default()).unwrap();
    filter(lf);

    let file = std::fs::File::open(path).unwrap();
    let lf = ParquetReader::new(file)
        .read_parallel(ParallelStrategy::Auto)
        .finish()
        .unwrap()
        .lazy();
    filter(lf);
}

fn filter(lf: LazyFrame) {
    let start: u64 = 376951;

    let df = lf
        .clone()
        .filter(col("name").eq(lit("n[player][3087900324][bag][]")))
        .filter(col("version_no").gt(lit(start)))
        .collect()
        .unwrap();
    println!("{:?}", df);
}
````
data in this zip
[data.snappy.zip](https://github.com/pola-rs/polars/files/10422990/data.snappy.zip)

### Expected behavior

![image](https://user-images.githubusercontent.com/103313295/212609483-1764786d-4c5f-4760-8060-0aff905b0475.png)
The result of the above code，the first filter, can't find the data, the second is correct
Oddly enough, when I convert start from u64 to i64, can get data is the first filter

### Installed versions

<details>
polars = { version = "0.26.1", features = [
    "lazy",
    "parquet",
    "is_in",
    "dtype-categorical",
    "simd",
    "performant",
] }
</details>

**Comment by ritchie46** [comment]
Could you try in python if the problem persists?

**Comment by LinZuan** [comment]
```
import polars as pl

start = 376951

df = pl.read_parquet("data.snappy.parquet")
lf = df.lazy()
result = lf.filter(pl.col("name") == "n[player][3087900324][bag][]").filter(pl.col("version_no") > start).collect()
print(result)


df = pl.scan_parquet("data.snappy.parquet")
result = lf.filter(pl.col("name") == "n[player][3087900324][bag][]").filter(pl.col("version_no") > start).collect()
print(result)
```
![image](https://user-images.githubusercontent.com/103313295/212618836-ce1c6585-0736-4c1e-a872-a88650f79cee.png)

Either way you can get the right answer. I'm not familiar with python and can't seem to specify the type of arguments. When I used i64 in rust's test cases or just filled in the numbers, I got the correct results

**Comment by ritchie46** [comment]
@LinZuan I believe this is already solved on master since the python code works as expected. I also tried a python snippet where we used `UInt64` for start and that also seemed to work.

```python
start = pl.lit(376951).cast(pl.UInt64)

df = pl.read_parquet("data.snappy.parquet")
lf = df.lazy()
result = lf.filter(pl.col("name") == "n[player][3087900324][bag][]").filter(pl.col("version_no") > start).collect()
print(result)


df = pl.scan_parquet("data.snappy.parquet")
result = lf.filter(pl.col("name") == "n[player][3087900324][bag][]").filter(pl.col("version_no") > start).collect()
print(result)
```

Could you try if pointing into our master repo solves your problem?

**Comment by cannero** [comment]
@ritchie46, with the master from yesterday, `LazyFrame::scan_parquet` in the example from @LinZuan does not work with `u64`, only with `i64`.

One difference is that the filter expression for `u64` is `[(col("version_no")) > (376951u64)]` and for `i64` is `[(col("version_no")) > (376951i64.cast(UInt64))]`. Because of the cast in the latter expression `impl_should_read` in `BinaryExpr` returns `true`, the `u64` expression returns `false` and therefore in `rg_to_dfs` a row group is skipped.
I may be here totally of but I believe that the difference in the expressions is the reason that no row is found. The check for the expressions was introduced in #5864.

**Comment by ritchie46** [comment]
Right, Thanks for the breakdown @cannero. Would you like to take a stab at this one? I can also do it if you want.

**Comment by cannero** [comment]
Yes, I would like to take a stab at this one. Do you have time to give me some hints @ritchie46? I don't understand the root cause of the problem. In the pull request which introduced the comparison, it is mentioned that the minimum and maximum values are taken. Where is this done?

**Comment by ritchie46** [comment]
Found the culprit. The reported statistics int he parquet file are incorrect. I have added an option to turn off statstics when reading in #7087.

**Comment by LinZuan** [comment]
Unfortunately, I tried again today but the problem is still not fixed.  I was able to reproduce it using the test cases I originally provided.  I am using version 0.28.0.

**Comment by ritchie46** [comment]
Did you turn off statistics?

**Comment by ritchie46** [comment]
Because the statistics reported in the file is incorrect. We use that statistics to optimize. 

That is not a bug on our side, but in your file
