### ISSUE TITLE
Use Min/Max/other? Statistics from Delta Files

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#6260]
### Problem description

Hi there!

Thanks for this very awesome library! It's so fast! 

We use it to read delta files which include statistics. I saw there is some statistics support but it doesn't look like statistics from delta files are beeing used. Is that correct? If it's not too hard to implement I can give it a try, however I'm new to Rust - you would have to review a lot

**Comment by ritchie46** [comment]
For delta files we use pyarrow. So this should be taken upstream.

We support statistics on our native supported file readers.

**Comment by aersam** [comment]
Seems you're using delta-rs and then the to pyarrow method there. meaning might be something for delta-rs repo, no?

**Comment by ritchie46** [comment]
That might be where this should be implemented indeed.

**Comment by aersam** [comment]
Closing because it's in the wrong repo. delta-rs states it should be working
