### ISSUE TITLE
Performance regression due to CSE

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#6261]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When upgrading Polars from a commit in Nov-22 to the latest one it seems our benchmarks caught a performance regression, I was unsure how to file this but I opted for `bug` change it if you think it's more appropriate as something else.

After some binary search it seems that the performance regression was introduced in PR #6087 . The regression is between 20% - 500% slower depending on dataset size. However it seems to have been getting better since then as the performance in the latest commit is between 20% - 150% slower but that might be other things that have improved.

The benchmarks are the same as the ones discussed in #4844 .

### Reproducible example

I don't have a reproducable example sadly but just like in the previous issue the benchmarks are including a lazy frame that is joined with itself:
```
let inp = DF;
let cached = inp.lazy().filter(..).group(..);
let b = cached.clone().filter(..).group(..);
let output = cached.join(b).with_common_subplan_elimination(true).collect()
```

### Expected behavior

Performance should not change that much. I'm guessing there is a missing cache node?

### Installed versions

<details>
["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series", "dtype-categorical", "performant", "serde", "concat_str", "row_hash"]
</details>

**Comment by ritchie46** [comment]
Right, we probably don't set a cache. I think I have a fix. Could you confirm once merged?

**Comment by SimonSchneider** [comment]
I can confirm that it's back to "normal" now, seems the missed cache was the issue, thanks @ritchie46! 🎉
