### ISSUE TITLE
Struct order must remain the same on nested non struct column

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6263]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Code returns `value: ComputeError(Borrowed("struct orders must remain the same"))` even if the column type is `pl.Object` and only if the column is nested inside an other Struct.

### Reproducible example

```python
import polars as pl

# This works just fine even if wrongly ordered
pl.DataFrame([
    {'d': {'a': 2,'b': 3}},
    {'d': {'b':4, 'a': 3}}
], columns={'d':pl.Object})

# This returns error
pl.DataFrame([
    {'d': {'d2': {'a': 2,'b': 3}}},
    {'d': {'d2': {'b': 3, 'a': 3}}}
], columns={'d': pl.Struct({'d2': pl.Object})})
```

### Expected behavior

Create the df even tho d2 keys are wrongly ordered

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.0
numpy: 1.21.1
fsspec: 2021.10.0
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
You run an older version of polars. Have you tried `0.15.15`?

**Comment by PieReissyet** [comment]
Just did, same issue unfortunately

**Comment by ritchie46** [comment]
This is not a bug, but a constraint we currently have on creating structs. We could look into removing that constraint.

**Comment by PieReissyet** [comment]
Thank you for you response, I must say it's pretty blocking when you are using document oriented Databases.

I am not sure key order is much of a thing in those DB and the most straight forward work around I see is being able to cast as object to break that constraint.

By the way why are we having this type of constraint when dealing with Struct column type / key: value documents ?
