### ISSUE TITLE
`DataFrame.row` does not recognize numpy integers for `index` parameter

### ISSUE THREAD

**Issue by Gattocrucco** [pola-rs/polars#6265]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`DataFrame.row` expects an `int` as first argument, indicating the row index. It is often the case that the row index has been computed with a numpy function, which returns a `numpy.int64` object instead of a plain Python `int`. `DataFrame.row` is strict and refuses such an object, with an obscure error message.

### Reproducible example

```python
import polars as pl
import numpy as np
df = pl.DataFrame(dict(a=[1,2,3]))
i = np.int64(0)
row = df.row(i) # ValueError: One of 'index' or 'by_predicate' must be set
```

### Expected behavior

```python
import polars as pl
import numpy as np
df = pl.DataFrame(dict(a=[1,2,3]))
row = df.row(0) # (1,)
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.0
```

</details>

**Comment by ritchie46** [comment]
I don't think it should. I think we can expect type hygiëne from users right?

**Comment by alexander-beedie** [comment]
Interestingly the call _does_ actually succeed if we don't block it from getting passed further down (as we very explicitly check on `int`, hmm... As the params have already been checked to see if they are mutually exclusive we can change the `isinstance(..., int)` to `is not None` and let the param through - if it works, it works, and if it doesn't it'll raise a better error.
