### ISSUE TITLE
date_range doesn't accept str for low/high (contradicting type hints)

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6267]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Looks like `str` is allowed here:

https://github.com/pola-rs/polars/blob/ccc4b2ed938fc8b43e4dc69b8e955c0a46da6f1c/py-polars/polars/internals/functions.py#L334-L336

but it doesn't seem to be covered by tests, and if I try passing a string it fails:

### Reproducible example

```python
In [6]: pl.DataFrame({'a': pl.date_range(low=datetime(2021, 12, 16), high='2021-12-16 03:00:00', interval="30m")})
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 pl.DataFrame({'a': pl.date_range(low=datetime(2021, 12, 16), high='2021-12-16 03:00:00', interval="30m")})

File ~/polars-dev/py-polars/polars/internals/functions.py:445, in date_range(low, high, interval, lazy, closed, name, time_unit, time_zone)
    440     return pli.wrap_expr(
    441         _py_date_range_lazy(low, high, interval, closed, name, time_zone)
    442     )
    444 low, low_is_date = _ensure_datetime(low)
--> 445 high, high_is_date = _ensure_datetime(high)
    447 if low.tzinfo is not None or time_zone is not None:
    448     if low.tzinfo != high.tzinfo:

File ~/polars-dev/py-polars/polars/internals/functions.py:263, in _ensure_datetime(value)
    261 is_date_type = False
    262 if not isinstance(value, datetime):
--> 263     value = datetime(value.year, value.month, value.day)
    264     is_date_type = True
    265 return value, is_date_type

AttributeError: 'str' object has no attribute 'year'
```

### Expected behavior

Not sure - is `str` argument really supported somehow, or should the type annotation be amended?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8.1
matplotlib: <not installed>
None

```

</details>

**Comment by stinodego** [comment]
I think that's an error in the type hints.

**Comment by MarcoGorelli** [comment]
wouldn't `pl.col('x')` already be covered  by the `pli.Expr` type?

**Comment by alexander-beedie** [comment]
> wouldn't `pl.col('x')` already be covered by the `pli.Expr` type?

Yes; but there are a number of other places where a bare string is automatically converted to `pl.col(str)` - I'm wondering if this was meant to be one of them; that or date-string parsing, hmm.

**Comment by ritchie46** [comment]
Polars never infers strings as dates/datetimes. Python date/datetime should be used in those cases. 

Atringa might refer to columns for ergonomic purposes.
