### ISSUE TITLE
Casting that might surprise R and Pandas users (division of pl.Series vs pl.DataFrame)

### ISSUE THREAD

**Issue by vnijs** [pola-rs/polars#6274]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am a long time R (and Pandas) user and am new polars. Amazing package!

I posted a question to StackOverflow about a seeming inconsistency between casting requirements for `pl.col` vs `[]` indexing. See example (and reproducible example) below for categorical variables. Then a seemingly related issue came up around division, which user https://stackoverflow.com/users/19355181/jqurious on SO helped me see was a difference in how division works for DataFrames and Series , which would likely be surprising to users with experience in R and/or Pandas. This issue focuses on division of `pl.Series` and `pl.DataFrame` objects.

```
# returns 0
pl.DataFrame([1]) / 3

# returns 0.3333
pl.Series[1]) / 3
```

https://stackoverflow.com/questions/75120942/need-to-explicitly-use-cast-when-using-pl-col-versus-indexing-seems-inconsis

### Reproducible example

```python

# returns 0 but R and Pandas users would expect 0.333
pl.DataFrame([1]) / 3

# returns 0.3333
pl.Series([1]) / 3
```

### Expected behavior

* Division of integers in a DataFrame produces floats

### Installed versions

<details>

```
>>> pl.show_versions()
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: macOS-13.0-arm64-arm-64bit
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.4
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8.1
matplotlib: 3.5.3
```

</details>

**Comment by alexander-beedie** [comment]
Quite right about the float division - we already handle this correctly for `Series` and `Expr`; I'll fix for `DataFrame` - we just need to properly distinguish between floordiv  (`//`) and truediv (`/`) here, as we are doing elsewhere.

**Comment by alexander-beedie** [comment]
@vnijs: Do you think you can add the consistency of Categorical behaviour as a separate issue? Would help us to keep things focused, as I'm about to close the truediv/floordiv inconsistency for DataFrames. Thx! 👍

**Comment by vnijs** [comment]
Thanks @alexander-beedie! I edited this issue and will post a separate one about categorical variables
