### ISSUE TITLE
Consume output of streaming query as iterator of record batches

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#6279]
### Problem description

I am working with some existing code that uses pyarrow for batched I/O. In particular, it constructs a [Scanner](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Scanner.html) from an iterator of `RecordBatch`es, which are then written to disk using pyarrow. I'm not sure if the need to rechunk makes this impossible, but I'm imagining something that would allow you to construct record batches from a streaming query, e.g.,

```python

def my_streaming_query(ldf: LazyFrame) -> LazyFrame:
    # Some streaming query

# an iterator of RecordBatches
batches = my_ldf.pipe(my_streaming_query).to_arrow_batches(min_batch_size, max_batch_size)

# a pyarrow RecordBatch
next(batches)

# use pyarrow to write the batches to disk
pyarrow.dataset.write_dataset(batches, "my_dataset", schema=schema, format="ipc")
```

This would improve interoperability when incorporating polars with existing pyarrow code. Duckdb also has a `fetch_record_batch` method, which would improve feature parity: https://duckdb.org/2021/12/03/duck-arrow.html#streaming

**Comment by ritchie46** [comment]
You can use `df.to_arrow().to_batches()`. 

See: https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.to_batches

The conversion to arrow is free.

**Comment by erinov1** [comment]
@ritchie46 I was actually thinking along the lines of an alternative to `sink_parquet/ipc` when the `collect`ed output does not fit into memory. In other words, I'm proposing being able to iterate over slices of a streaming _`LazyFrame`_, rather than the collected _`DataFrame`_ (I guess iterating over slices of `DataFrame` is being proposed in https://github.com/pola-rs/polars/pull/6414). That would improve interoperability with code that already uses pyarrow for the I/O layer.

**Comment by ritchie46** [comment]
This is actually something that is out of scope for now. This is touching streaming functionality (and not in the way we use it in polars).

**Comment by erinov1** [comment]
Thanks for taking a look — this project is incredible!
