### ISSUE TITLE
Inconsistent results with nested `whenthen` and `pl.any()`

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#6284]
When nesting `whenthen`-expressions containing `pl.any()`, it appears that the order of the nested operations is not respected.

If this is somehow intended behavior, I'd be happy for any ideas to achieve a properly nested evaluation without writing completely separate expressions (and thereby having to read the same columns multiple times).

Example:

```py3
df = pl.DataFrame({"1": ["a", "b"], "2": ["c", "d"],})

df.with_column(
    # check if 'a' is in any of the columns
    pl.when(pl.any(pl.col('*') == "a"))
    .then("a")
    .otherwise(
        # check if 'd' is in any of the columns
        pl.when(pl.any(pl.col('*') == "d")).then("d").otherwise(None))
    .alias("result")
)

print(df)

shape: (2, 3)
┌─────┬─────┬────────┐
│ 1   ┆ 2   ┆ result │
│ --- ┆ --- ┆ ---    │
│ str ┆ str ┆ str    │
╞═════╪═════╪════════╡
│ a   ┆ c   ┆ null   │ # <- contains 'a', so it should be caught by the first `when` and `otherwise` should not even be evaluated
│ b   ┆ d   ┆ d      │
└─────┴─────┴────────┘


```

**Comment by cmdlineluser** [comment]
[branches run in parallel.](https://github.com/pola-rs/polars/issues/5692#issuecomment-1334028730)

It looks like you may be trying to do:
```
df = pl.DataFrame({"1": ["a", "b"], "2": ["c", "d"],})
df.with_column(
   pl.coalesce(
      pl.when(pl.all().is_in(["a", "d"]))
        .then(pl.all())
        .alias("result")
   )
)
```
```
shape: (2, 3)
┌─────┬─────┬────────┐
│ 1   | 2   | result │
│ --- | --- | ---    │
│ str | str | str    │
╞═════╪═════╪════════╡
│ a   | c   | a      │
├─────┼─────┼────────┤
│ b   | d   | d      │
└─────┴─────┴────────┘
```
It first generates a boolean mask
```
df.select(pl.all().is_in(["a", "d"]))
shape: (2, 2)
┌───────┬──────┐
│ 1     | 2    │
│ ---   | ---  │
│ bool  | bool │
╞═══════╪══════╡
│ true  | true │
├───────┼──────┤
│ false | true │
└───────┴──────┘
```
`.when().then()` filters out the true values and [`.coalesce()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.coalesce.html#polars-coalesce) selects the first non-null from each row.

Are you trying to implement order rules? If both values can appear in the same row - the first one seen will be chosen - which may not be what you want.

```
df = pl.DataFrame({"1": ["d", "b"], "2": ["a", "d"],})
df.with_column(
   pl.coalesce(
      pl.when(pl.all().is_in(["a", "d"]))
        .then(pl.all())
        .alias("result")
   )
)
```
```
shape: (2, 3)
┌─────┬─────┬────────┐
│ 1   | 2   | result │
│ --- | --- | ---    │
│ str | str | str    │
╞═════╪═════╪════════╡
│ d   | a   | d      │
├─────┼─────┼────────┤
│ b   | d   | d      │
└─────┴─────┴────────┘
```

**Comment by DrMaphuse** [comment]
Thanks for the suggestions everyone.

I would like to address this on a more general level: I wanted to use nested `if`-`else`-logic to calculate new columns, and Polars provides no obvious way to do this.

On the surface, `whenthen` appears to be an `if`-`else`, but under the hood, it is not.

This is such a massively common use case that such a big source of potential errors is not ideal. 

I addressed this pitfall in my team, and each of my 4 team members was surprised to learn about this, and some of them had actually experienced problems in the past because of this and could not figure out what they were doing wrong. The abovementioned (closed) bug report also indicates that more people may be having problems with this.

Python is supposed to be a readable language. Polars mostly follows this principle with its intuitive API. But in this case, I believe that the API is misleading, almost to the point of advising against the use of `whenthen` altogether, because people new to polars are extremely likely to run into this misunderstanding at some point unless explicitly told about it.

I am not a SWE, but it appears that it should be possible to parallelize such a function while respecting the causal order of conditions. R's `data.table` has `fifelse`, which [does exactly this](https://www.rdocumentation.org/packages/data.table/versions/1.14.6/topics/fifelse).

Maybe a separate `if`-`else`-function could be a solution?

**Comment by ritchie46** [comment]
There was a bug in wildcard expansion. The given query of @DrMaphuse and this one (a bit more ideomatic):

```python
(df.with_column(
    pl.when(pl.any(pl.all() == "a"))
    .then("a")
    .when(pl.any(pl.all() == "d"))
    .then("d")
    .otherwise(None)
    .alias("result")
)
```

Now run as expected.
