### ISSUE TITLE
date_range is no longer in prelude, instead it is in `prelude::prelude` (v0.26.1)

### ISSUE THREAD

**Issue by SirVer** [pola-rs/polars#6290]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

This code

```
use polars::prelude::*;

... unrelated

    let idx = date_range(
        "x_axis",
        query.first_day.and_hms(0, 0, 0),
        query.last_day.and_hms(0, 0, 0),
        Duration::parse("1d"),
        ClosedWindow::Both,
        TimeUnit::Milliseconds,
        None,
    )
    .cast(&DataType::Date)
    .unwrap();

```

I see the following error:

```
error[E0425]: cannot find function `date_range` in this scope
   --> backend/src/main.rs:359:15
    |
359 |     let idx = date_range(
    |               ^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
11  | use crate::prelude::date_range;
    |
11  | use polars::prelude::prelude::date_range;
    |
```

Indeed either of these imports work (after adding the new timezone argument as None). I can confirm that `v0.24.3` did still have it correctly in `prelude`. The latest version `0.26.1` and `0.25.1` have it in `polars::prelude::prelude`. 

### Reproducible example

provided

### Expected behavior

I doubt this was an intentional change, it feels like a copy & pasto. It certainly is backwards incompatible.

### Installed versions

<details>
polars = { version = "0.26.1", features = ["lazy", "cum_agg", "temporal", "ipc", "ipc_streaming", "dtype-full", "is_in" ] }
</details>

**Comment by ritchie46** [comment]
Could you make a PR?

**Comment by ritchie46** [comment]
Fixed on master

**Comment by SirVer** [comment]
@ritchie46 Thanks! I would not have time to look into this before end of February, so much appreciated that you could fix it. 

a tiny nit: It would be great to have the PRs linked here - I would not have known where to start with this one and it would be educational. I was not able to find the commit on master that fixed this.
