### ISSUE TITLE
Enable starts_with in the string namespace to work with expressions

### ISSUE THREAD

**Issue by syaffers** [pola-rs/polars#6293]
### Problem description

In reference to a [StackOverflow issue](
https://stackoverflow.com/questions/75133458/polars-str-starts-with-with-values-from-another-column), I was wondering if this functionality could be implemented in Polars.

What I would like to do is optimize the what I accomplished in the SO issue with Polars expressions as I'm sure I'm not leveraging the full potential of the library with my solution. However, currently, I'm not able to do something like

```python
df.with_columns(pl.col('B').str.starts_with(pl.col('A')).alias('C'))
```

I would be met with the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[26], line 1
----> 1 pl.col('A').str.starts_with(pl.col('B'))

File ~/Projects/spo-ingestors/.venv/lib/python3.10/site-packages/polars/internals/expr/string.py:624, in ExprStringNameSpace.starts_with(self, sub)
    580 def starts_with(self, sub: str) -> pli.Expr:
    581     """
    582     Check if string values start with a substring.
    583
   (...)
    622
    623     """
--> 624     return pli.wrap_expr(self._pyexpr.str_starts_with(sub))

TypeError: argument 'sub': 'Expr' object cannot be converted to 'PyString'
```

I'm quite new to Polars (and have almost no experience with Rust) but I think it would be pretty exciting to work on a PR for this if I could get some pointers on how to.

EDIT: included full traceback.

**Comment by ritchie46** [comment]
A PR on this is very welcome. 

Most of the steps involved can be found in this previous PR where we also added an expression argument.: https://github.com/pola-rs/polars/pull/5337

**Comment by gab23r** [comment]
I am working on it, will propose a PR soon !
