### ISSUE TITLE
Allow specifying datatype of single scalar values.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#630]
#### Describe your feature request

Allow specifying datatype of single scalar values for arguments that accept a pyton int, float, ...:
  - Create a float32 value: pl.Float32(0.0)
  - Accept also numpy types: e.g. np.float32
  - Accept also pyarrow types: e.g.: pa.scalar(0.0, type=pa.float32())

**Comment by ritchie46** [comment]
The expression `lit` now accepts a `dtype` argument. This can be used to create single scalar value. Numpy arrays are also accepted.

**Comment by ritchie46** [comment]
@ghuls, I am closing this one. We don't support `pa.scalar`, but that concept doesn't really exists in Polars, so I skipped that one. The rest works with the new `lit` expression.
