### ISSUE TITLE
`expr.str.decode("base64")` fail from 0.15.9

### ISSUE THREAD

**Issue by SysuJayce** [pola-rs/polars#6301]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Before 0.15.9, I can decode base64 with `pl.col("column_name").str.decode("base64")`, but from 0.15.9, I get `ComputeError` with the same code.

What I want is to decode base64 with strict mode(return null if the input string is invalid).

Below is how to reproduce:
1. Before 0.15.9
```python
df = pl.DataFrame({"strings": ["0IbQvTc3", "0J%2FQldCf0JA%3D", "0J%2FRgNC%2B0YHRgtC%2B"]})
df.select(pl.col("strings").str.decode("base64"))
```
Produce:
```
shape: (3, 1)
**strings**
str
"Ін77"
null
null
```
2. After 0.15.9
```python
df = pl.DataFrame({"strings": ["0IbQvTc3", "0J%2FQldCf0JA%3D", "0J%2FRgNC%2B0YHRgtC%2B"]})
df.select(pl.col("strings").str.decode("base64"))
```
Produce:
```
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[3], line 2
      1 df = pl.DataFrame({"strings": ["0IbQvTc3", "0J%2FQldCf0JA%3D", "0J%2FRgNC%2B0YHRgtC%2B"]})
----> 2 df.select(pl.col("strings").str.decode("base64"))

File /opt/conda/lib/python3.8/site-packages/polars/internals/dataframe/frame.py:5446, in DataFrame.select(self, exprs)
   5360 def select(
   5361     self: DF,
   5362     exprs: str
   (...)
   5365     | Sequence[str | pli.Expr | pli.Series | pli.WhenThen | pli.WhenThenThen],
   5366 ) -> DF:
   5367     """
   5368     Select columns from this DataFrame.
   5369 
   (...)
   5443 
   5444     """
   5445     return self._from_pydf(
-> 5446         self.lazy().select(exprs).collect(no_optimization=True)._df
   5447     )

File /opt/conda/lib/python3.8/site-packages/polars/utils.py:337, in deprecated_alias.<locals>.deco.<locals>.wrapper(*args, **kwargs)
    334 @functools.wraps(fn)
    335 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    336     _rename_kwargs(fn.__name__, kwargs, aliases)
--> 337     return fn(*args, **kwargs)

File /opt/conda/lib/python3.8/site-packages/polars/internals/lazyframe/frame.py:1154, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1143     common_subplan_elimination = False
   1145 ldf = self._ldf.optimization_toggle(
   1146     type_coercion,
   1147     predicate_pushdown,
   (...)
   1152     streaming,
   1153 )
-> 1154 return pli.wrap_df(ldf.collect())

ComputeError: Invalid byte 37, offset 2.
```

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"strings": ["0IbQvTc3", "0J%2FQldCf0JA%3D", "0J%2FRgNC%2B0YHRgtC%2B"]})
df.select(pl.col("strings").str.decode("base64"))
```

### Expected behavior

shape: (3, 1)
**strings**
str
"Ін77"
null
null

### Installed versions

<details>

```
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: Linux-4.14.105-1-tlinux3-0021-x86_64-with-glibc2.10
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.2.2
```

</details>

**Comment by stinodego** [comment]
I confirmed that this behaviour also happens on the master branch, after the upgrade of the `base64` crate.

**Comment by ritchie46** [comment]
Does it fail because the encoded value is wrong?

**Comment by ritchie46** [comment]
Thanks @alexander-beedie. I think we must add an keyword argument indicating what to do in such a case. Either return an error or return null for the failing values.

**Comment by SysuJayce** [comment]
> You can tell at a glance that the input strings are not valid Base64 because `%` is not a valid Base64 target encoding character. I'm 99% certain that the input _actually_ represents a URL-encoded Base64 string. In other words it has been double-encoded ;p
> 
> The giveaway is the presence of:
> 
> * `%2B` (which is a URL-encoded `+`)
> * `%2F` (which is a URL-encoded `/`)
> * `%3D` (which is a URL-encoded `=`)
> 
> So the error is correct - these strings are not actually valid Base64. The only difference appears to be that invalid strings were previously assigned as `null`, and now a proper error is raised instead.
> 
> An `ignore_errors` param would allow for opt-in to the previous behaviour? But by default raising on invalid input is the right thing to do.

Thanks @alexander-beedie @ritchie46 . Actually, I want to ignore such invalid input, the previous version has a `strict` param and I think it should be kept so that we can control what to do
