### ISSUE TITLE
bitwise or on integer series gives invalid result

### ISSUE THREAD

**Issue by FObersteiner** [pola-rs/polars#6311]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

**Task: implement a binary flag column in a polars dataframe**
- use an integer series to hold the binary flag value
- flags are combined by a bitwise `or`
- this gives invalid results when combining multiple flags, see MRE below
- see also [How to properly set binary flags in a Python polars dataframe](https://stackoverflow.com/questions/75160757/how-to-properly-set-binary-flags-in-a-python-polars-dataframe)

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
        "col1": [0,1,2,3],
        "flag": [0,0,0,0]
    })

df = df.with_columns(
        pl.when((pl.col("col1") < 1) | (pl.col("col1") >= 3))
        .then(pl.col("flag") | 2) # set flag b0010
        .otherwise(pl.col("flag"))
    )
print(df)
shape: (4, 2)
┌──────┬──────┐
│ col1 ┆ flag │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 0    ┆ 2    │
│ 1    ┆ 0    │
│ 2    ┆ 0    │
│ 3    ┆ 2    │
└──────┴──────┘

df = df.with_columns(
        pl.when(pl.col("col1") > -1)
        .then(pl.col("flag") | 4) # set/combine with flag b0100
        .otherwise(pl.col("flag"))
    )
print(df)
shape: (4, 2)
┌──────┬──────┐
│ col1 ┆ flag │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 0    ┆ 6    │
│ 1    ┆ 6    │
│ 2    ┆ 6    │
│ 3    ┆ 6    │
└──────┴──────┘
```

### Expected behavior

After combining flag 2 and 4, result should still be 4 for indices 1 and 2 as flag 2 condition does not apply here. Expected:
```py
┌──────┬──────┐
│ col1 ┆ flag │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 0    ┆ 6    │
│ 1    ┆ 4    │
│ 2    ┆ 4    │
│ 3    ┆ 6    │
└──────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Python: 3.10.9 (main, Dec 21 2022, 10:46:02) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by FObersteiner** [comment]
> Bitwise is currently an OR operation, not a bitwise operation.

sorry, I don't understand. Do you mean `|` does not do bitwise OR as in Python, pandas, numpy etc.?

**Comment by alexander-beedie** [comment]
`|` for expressions is (and has to be) _logical_ OR, not _bitwise_ OR. For bitwise ops at the expression level we should probably open up a `bit` namespace and put the functionality there; I could probably look into that, as I think we do actually have the underlying functionality already (exposed on `Series`, but not `Expr`).

**Comment by FObersteiner** [comment]
@alexander-beedie thanks a lot for your reply. In general, I think it would good to have a separate namespace for bitwise operations, to clearly separate them from logical ones. So +1 for that!

However, I'm still having some trouble to understand what's going on in the example I posted. Assuming that logical or returns the first truthy value from the expression, `0 | 2` gives 2 in the first part, good. But in the second part, we have `0 | 4` for indices 1 and 2 of the series. So that should be 4 in my understanding, not 6 ?

**Comment by alexander-beedie** [comment]
Hmm. I'm going to slightly modify what I just said above; because expressions on columns behave as Series, you actually _do_ get bitwise behaviour **if** you don't specify a literal... I'm not entirely sure what behaviour I'm seeing with a literal value, but it does seem odd. I'll need to look at that a bit harder to see if we can/should normalise this.

**Comment by qrilka** [comment]
I saw unexpected results with `.and` and rustdocs don't give any definitive information what opertion it implements, are there any plans to fix bitwise operations? I could try doing that myself but I'm not familiar with polars internals

**Comment by qrilka** [comment]
It seems to me that the implementation is at https://github.com/pola-rs/polars/blob/32705e3a829b8f5bbd5bfc58cdc4a9c2ad0b7748/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs#L541-L543 but [eval_bitwise](https://github.com/pola-rs/polars/blob/32705e3a829b8f5bbd5bfc58cdc4a9c2ad0b7748/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs#L284) looks qute confusing: contrary to its name it works on booleans and not on bits :-\

**Comment by FObersteiner** [comment]
> but [eval_bitwise](https://github.com/pola-rs/polars/blob/32705e3a829b8f5bbd5bfc58cdc4a9c2ad0b7748/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs#L284) looks qute confusing: contrary to its name it works on booleans and not on bits :-\

Working on booleans (anything evaluates to true except zero) could give the unexpected behaviour described in the OP. That's not how I'd understand "bitwise" though ...

**Comment by qrilka** [comment]
@FObersteiner probably it explains wrong results but I'm not quite show how casting to booleans could produce basically constant results, e.g. in my Rust example
```rust
    let df = df![
        "a" => [8,1,2,4,208,36]
    ]?;
    let result = df
        .lazy()
        .select([col("a"), col("a").and(lit(0b11111)).alias("lower_bits")])
        .collect()?;
    println!("Result: {result}");
```

I get
```
Result: shape: (6, 2)
┌─────┬────────────┐
│ a   ┆ lower_bits │
│ --- ┆ ---        │
│ i32 ┆ i32        │
╞═════╪════════════╡
│ 8   ┆ 8          │
│ 1   ┆ 8          │
│ 2   ┆ 8          │
│ 4   ┆ 8          │
│ 208 ┆ 8          │
│ 36  ┆ 8          │
└─────┴────────────┘
```

**Comment by ritchie46** [comment]
I think something went wrong in broadcasting. Fix coming up.
