### ISSUE TITLE
`pl.DataFrame.tail(None)` returns last 10 rows

### ISSUE THREAD

**Issue by lorenzwalthert** [pola-rs/polars#6323]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am not sure it's a clear bug, but at least unexpected.

### Reproducible example

```python
import polars as pl 
df = pl.DataFrame(
    {
        "foo": range(100),
    }
)

df.tail(None) # seems to keep last 10 rows only
```

### Expected behavior

`tail(None)` is either not allowed or returns the input, instead of returning the last 10 rows.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
I agree, there is no reason we should accept `None` here on the Python side.

**Comment by lorenzwalthert** [comment]
I'd actually vote for keeping `None` so we can avoid an `if` statement in code flow to handle the case where I don't want to do anything to my data. I'd interpret `None` as *there is no limit to the tail* (note that if the data frame has fewer rows than `n`, all it's rows are returned, and not `n` rows). 
```pyton
data.tail(n_max)

# if `None` is not allowed
if n_max is not None:
    data.tail(n_max)
else: 
    data
```

**Comment by stinodego** [comment]
I don't agree with your interpretation. Makes no sense to me for `tail(None)` to mean 'all rows'. If anything, it would mean 'default' tail, which it currently does. This is also how it works on the Rust side. There it makes sense, as there is no 'default' value available. On the Python side, we have a default available, so passing `None` makes no sense.

**Comment by lorenzwalthert** [comment]
Ok, consistency across the API is certainly an argument. Also, the consequence is that one has to handle `None` explicitly, which ms maybe even desired since it's an exception.

**Comment by stinodego** [comment]
Maybe the most convincing argument for removing `None` is that the meaning is up for interpretation. We want to be consistent and predictable. I implemented the fix.

**Comment by lorenzwalthert** [comment]
Thanks for the quick fix.
