### ISSUE TITLE
Deprecate dt.cast_time_zone in favour of dt.tz_localize

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#6338]
### Problem description

The `dt.tz_localize` function takes a tz-naive datetime and adds a timezone. It keeps the datetime constant and changes the integer timestamp.

The `dt.cast_time_zone` function takes a tz-aware datetime and changes timezone. It keeps the datetime constant and changes the integer timestamp.

I propose deprecating `dt.cast_time_zone` by allowing `tz_localize` to accept tz-aware datetimes.

As well as reducing our footprint it will make it easier to explain the difference between tz_localize abd with_time_zone

**Comment by MarcoGorelli** [comment]
+1 for deprecating, but why is

> allowing tz_localize to accept tz-aware datetimes.

necessary? Why not just instruct users to replace `.cast_time_zone` with `.with_time_zone(None).dt.tz_localize` and keep the existing methods as they are?

**Comment by FObersteiner** [comment]
Based on my experience with datetime handling in Python and especially pandas, I'd oppose this as well. `tz_localize` should not accept aware datetime.

I think the term `localize` covers pretty well what is intended: take a datetime and make it local in a certain time zone. For me, that implies that the input must be naive (not aware of any time zone). Otherwise, it is a conversion.

As a side note, I think pandas devs came up with a very good counter part function name, `tz_convert` (again, concise name imho). From a Python dev's perspective with a "pandas-background", it is confusing why `polars` has adopted `tz_localize` but not `tz_convert`. So to be consistent, I'd propose for polars to use either `tz_localize` and `tz_convert` ***or*** `with_time_zone` and `cast_time_zone`. Or, if all four methods should exist, just make them an alias of the other.

**Comment by ritchie46** [comment]
Is one of the 3 redundant with another one?

**Comment by MarcoGorelli** [comment]
Let's see - starting with:

```python
In [116]: naive
Out[116]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 03:00:00
]

In [117]: aware
Out[117]:
shape: (1,)
Series: '' [datetime[μs, Europe/Brussels]]
[
        2020-01-01 04:00:00 CET
]
```

one might want to:
- convert tz-naive to `tz` from UTC:
```python
In [118]: naive.dt.with_time_zone('Europe/Brussels')
Out[118]:
shape: (1,)
Series: '' [datetime[μs, Europe/Brussels]]
[
        2020-01-01 04:00:00 CET
]
```
- set `tz` without converting:
```python
In [124]: naive.dt.with_time_zone('UTC').dt.cast_time_zone('Europe/Brussels')
Out[124]:
shape: (1,)
Series: '' [datetime[μs, Europe/Brussels]]
[
        2020-01-01 03:00:00 CET
]
```

- convert one `tz` to another:
```python
In [127]: aware.dt.with_time_zone('US/Pacific')
Out[127]:
shape: (1,)
Series: '' [datetime[μs, US/Pacific]]
[
        2019-12-31 19:00:00 PST
]
```

- change the `tz`:
```python
In [126]: aware.dt.cast_time_zone('US/Pacific')
Out[126]:
shape: (1,)
Series: '' [datetime[μs, US/Pacific]]
[
        2020-01-01 04:00:00 PST
]
```

- make naive
```python
In [131]: aware.dt.cast_time_zone('UTC').dt.with_time_zone(None)
Out[131]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 04:00:00
]
```

---

Have I missed anything? If not, then it looks like everything can be done with 1 or 2 combinations of `cast_time_zone` and `with_time_zone`, which (along with avoiding equivalence with pandas tz_localize, which isn't quite the same as it can also accepts `None` as argument) may make a case for deprecating `tz_localize`

Perhaps the above "recipes" could just be a section in the time series chapter in the polars book, `tz_localize` deprecated, and then the size of the API can be kept down?

**Comment by ritchie46** [comment]
Yes, I want `with_time_zone` and `cast_time_zone` above `tz_localize` as that one is implemented using the former. I believe all we need is a bit better documentation.

The `tz_localize` was introduced when I still had bugs in the `cast_*` and `with_*`, those have been resolved and the conversion now is predictable (AFAICT).

**Comment by FObersteiner** [comment]
> I believe all we need is a bit better documentation.

+1

I think the fact that naive datetime is implicitly treated as UTC deserves to be pointed out as well. Although `pandas` does this the same way, vanilla Python does not.

**Comment by MarcoGorelli** [comment]
After trying to write out a page on time zones in the polars-book, I'm no longer sure that deprecating tz_localize is the way to go

Starting with
```
tz_naive = pl.Series(["2020-01-01 03:00:00"]).str.strptime(pl.Datetime)
tz_aware = tz_naive.dt.with_time_zone("Europe/Brussels")
```
then if you have `cast_time_zone`, `with_time_zone`, and `tz_localize`, then you can do virtually any timezone operation you want with a single call:
```
# convert from UTC
out_1 = tz_naive.dt.with_time_zone("Europe/Brussels")
# set timezone
out_2 = tz_naive.dt.tz_localize("Europe/Brussels")
# convert timezone
out_3 = tz_aware.dt.with_time_zone("US/Pacific")
# change timezone
out_4 = tz_aware.dt.cast_time_zone("US/Pacific")
# unset timezone
out_5 = tz_aware.dt.cast_time_zone("UTC").dt.with_time_zone(None)
```

The only one that requires two calls is the last one (and maybe there's a way around that - looking into that)

**Comment by FObersteiner** [comment]
If `cast_time_zone` could operate on naive datetime, could that be an option for #2?

Also, if it would accept `None` for converting aware to naive, could that be an option for simplifying #5?

**Comment by MarcoGorelli** [comment]
The alternatives I can think of would be:
1) let `tz_localize` take `None`, like pandas does (though TBH this feels like a misnomer to me, because you're not actually localizing...)
2) introduce `tz_unlocalize`, which just removes timezones (though this expands the API...)
3) let `cast_time_zone` take `None`

I _think_ my favourite would be 3:
```python
In [3]: tz_aware.dt.cast_time_zone(None)
Out[3]: 
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 04:00:00
]

In [4]: tz_aware.dt.cast_time_zone('America/Barbados')
Out[4]: 
shape: (1,)
Series: '' [datetime[μs, America/Barbados]]
[
        2020-01-01 04:00:00 AST
]
```

**Comment by alexander-beedie** [comment]
> 3) let `cast_time_zone` take `None`

This one feels clean.

**Comment by MarcoGorelli** [comment]
Thanks all for sharing your thoughts! I've given this a go https://github.com/pola-rs/polars/pull/6539
