### ISSUE TITLE
`explode`/`unnest` should be under `arr`/`struct` namespaces

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6340]
### Problem description

I was surprised I could not find these methods under the namespaces. Is there a reason for this?

For `explode`, I would expect:
* `DataFrame/LazyFrame.explode` - useful to auto-expand the other columns along with the chosen columns
* `Series/Expr.arr.explode` - explode a single column / subset of lists (currently under `Series/Expr.explode`)
* `Series/Expr.str.explode` - explode a single column / subset of strings (currently under `Series/Expr.explode`)

`explode` has an alias `flatten`, which is currently only available on Expr. I would suggest to either remove it, or introduce it on Series and Data/LazyFrame as well.

For `unnest`, I would expect:
* `DataFrame/LazyFrame.unnest` - makes sense
* `Series.struct.unnest` - explode a single column to multiple columns. Currently named `to_frame`, but that feels inconsistent. It's not clear if the struct will be unnested or that I will get a DataFrame with a single column (like `Series.to_frame`).
* _`Expr.struct.unnest` - expressions cannot evaluate to multiple columns, so this doesn't make sense)_

If you agree, the TO DO list would be:
- [x] Add `explode` to namespaces. Deprecate 'naked' `Series/Expr.explode`.
- [x] Either deprecate or add `flatten` alias everywhere.
- [x] Rename `Series.struct.to_frame` to `Series.struct.unnest`.

**Comment by ritchie46** [comment]
Agree. They should be on the frames, but on the `Series` they should be moved to namespaces indeed.

**Comment by stinodego** [comment]
> I think we can just go through with this and jam a deprecation warning on the direct series methods?

Yes, that's exactly what I was thinking.

**Comment by ritchie46** [comment]
A late realization on my part. `flatten` is used pretty often in groupbys and window functions. I think we should keep that alias on the normal series. 

A `flatten` on a flat array is a no-op, so that is consistent with expectations. A flatten on a `list` flattens that list. I think the ergonomics of this alias is worth it keeping it in main namespace.

**Comment by stinodego** [comment]
Right - I'll revert that part.

Maybe we should have a small wait period before doing API changes like this 😄 to ponder the implications.

**Comment by stinodego** [comment]
What would be a typical use of `flatten` then? Because the current docstring examples are just regular explode examples.

**Comment by ritchie46** [comment]
I saw it used in an answer on SO. https://stackoverflow.com/a/75197396/6717054

And I used it also quite a lot on answers. The flatten imo just reada very smoothly and together with the rationale that it has a valid identity for already flattened series, I think it's deserves its place in the main namespace.

**Comment by stinodego** [comment]
Good think we haven't released those changes yet - I'll come up with a nice PR & nice doc examples 😸
