### ISSUE TITLE
read excel files to dataframe

### ISSUE THREAD

**Issue by kawori** [pola-rs/polars#635]
Sometimes our data is excel files, it's boring to transform excel to csv files.
Pandas provides ability to read data from much more file types.
I think it's important for polars to compelet this feature so that more users can use polars to do data analysis.

**Comment by ritchie46** [comment]
I don't think I will ever support that from the `Rust` side. For python coercing from a `pandas` `DataFrame` to a `polars` one is really fast. So you could just use:

```python
import pandas as pd
import polars as pl

pl.from_pandas(pd.read_excel(".."))
```

We could wrap this in an utility function.

**Comment by romanovacca** [comment]
@ritchie46 I can pick this up?

**Comment by ritchie46** [comment]
I am heavily doubting if we should add this to the API.

As users very easily can use `pl.from_pandas(pd.read_excel(".."))` and I don't want to support this from Rust.

**Comment by ghuls** [comment]
A `read_excel()` function using https://github.com/dilshod/xlsx2csv/, will be merged soon:
https://github.com/pola-rs/polars/pull/3567
