### ISSUE TITLE
Infer ISO8601 datetimes

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6356]
### Problem description

The following errors:
```python
pl.Series(['2018-10-28 02:30']).str.strptime(pl.Datetime)
---------------------------------------------------------------------------
ComputeError: Could not find an appropriate format to parse dates, please define a fmt
```
even though the input is ISO8601

Would you be open to polars inferring formats for all supported ISO8601 datetime?

Note: inferring any format would be a never-ending task, I'm not suggesting that - only ISO8601

**Comment by ritchie46** [comment]
Right. Should be pretty trivial. I believe we have a list with formats we try by default.
