### ISSUE TITLE
expected broadcasting when selecting a single literal from a dataframe context

### ISSUE THREAD

**Issue by khusmann** [pola-rs/polars#6360]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is a little thing -- sorry if this is the expected behavior and I'm missing something, but it caught me off guard and felt inconsistent with the documentation saying "A Series of a length of 1 will be broadcasted to match the height of the DataFrame."

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1,2,3], "b": [5,6,7]})

df.select(["a", pl.lit(10).alias("c")]) # a: 1, 2, 3; c: 10, 10, 10

df.select(pl.lit(10).alias("c")) # c: 10
```

### Expected behavior

I expected my literal to be broadcast to the height of the dataframe of my *selection context*, which would have resulted in `c: 10, 10, 10`

In the situation when I have a LazyFrame and want to create a single column with a broadcasted literal, I have to do:

```
df.with_column(pl.lit(10).alias("c").select("c")
```

instead of a single select. (Or maybe I'm missing an alternative approach not requiring collect() and .height?)

Thanks!

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.31
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.0
numpy: 1.23.4
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by ritchie46** [comment]
This is as expected we only broadcast to the result selection.

So if you write:

```
df.select([
   pl.lit(10).alias("foo"),
   pl.col("foo").head(10)
])
```

We will broadcast to 10, even though the dataframe may have another size.

**Comment by khusmann** [comment]
Ah, I see, that makes sense. Sorry for bothering ya!
