### ISSUE TITLE
Makefile task "publish" not necessary anymore

### ISSUE THREAD

**Issue by matthiasbeyer** [pola-rs/polars#6367]
https://github.com/pola-rs/polars/blob/f2e54b1ade61f270601330beb04b7c6516d13df4/polars/Makefile#L90-L113

I found this while browsing the codebase. I think this is not necessary anymore, because `cargo` can now publish workspaces (relevant issue: https://github.com/rust-lang/cargo/issues/1169).

May be worth a try.

**Comment by ritchie46** [comment]
Thanks! That looks interesting. I shall keep this in mind on next releases. :+1:
