### ISSUE TITLE
Creating dataframe throws error: pyarrow.lib.ArrowTypeError: "object of type <class 'str'> cannot be converted to int"

### ISSUE THREAD

**Issue by jicart** [pola-rs/polars#6368]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have been trying polars to handle some web scraped data and I've run into this odd issue. I was able to minimize the code to reproduce the error. Of > 8000 dataframes with the same format, only 2 had this issue.

If  line 1 of 'table' is duplicated or commented out, the error doesn't appear.

### Reproducible example

```python
import polars as pl
from datetime import date
# Throws exception
table = [['Mercadoria', 'Vencimento', 'Preço de ajuste anterior', 'Preço de ajuste Atual', 'Variação', 'Valor do ajuste por contrato (R$)'], 
[date(1990, 1, 4), 'BTN   - Bônus do tesouro nacional', 'FEV0', '18,10', '17,30', '-0,79', '3.999,00'], 
[date(1990, 1, 4), 'BTN   - Bônus do tesouro nacional', 'MAR0', '32,10', '30,00', '-2,10', '10.500,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'FEV0', '20,6400', '19,1200', '-1,5200', '7.600,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'MAR0', '40,1000', '35,4900', '-4,6100', '23.050,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'ABR0', '60,0000', '55,0000', '-5,0000', '25.000,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'JUL0', '90,0000', '90,0000', '0,0000', '0,00'], 
[date(1990, 1, 4), 'IND   - Ibovespa', 'JAN0', '97.000', '97.500', '500', '0,00']]

df = pl.DataFrame(table[1:], columns=['Data',] + table[0])
```

### Expected behavior

If  line 1 is duplicated, it works fine
```
import polars as pl
from datetime import date
table = [['Mercadoria', 'Vencimento', 'Preço de ajuste anterior', 'Preço de ajuste Atual', 'Variação', 'Valor do ajuste por contrato (R$)'], 
[date(1990, 1, 4), 'BTN   - Bônus do tesouro nacional', 'FEV0', '18,10', '17,30', '-0,79', '3.999,00'], 
[date(1990, 1, 4), 'BTN   - Bônus do tesouro nacional', 'FEV0', '18,10', '17,30', '-0,79', '3.999,00'], 
[date(1990, 1, 4), 'BTN   - Bônus do tesouro nacional', 'MAR0', '32,10', '30,00', '-2,10', '10.500,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'FEV0', '20,6400', '19,1200', '-1,5200', '7.600,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'MAR0', '40,1000', '35,4900', '-4,6100', '23.050,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'ABR0', '60,0000', '55,0000', '-5,0000', '25.000,00'], 
[date(1990, 1, 4), 'DOL   - Dólar comercial', 'JUL0', '90,0000', '90,0000', '0,0000', '0,00'], 
[date(1990, 1, 4), 'IND   - Ibovespa', 'JAN0', '97.000', '97.500', '500', '0,00']]

df = pl.DataFrame(table[1:], columns=['Data',] + table[0])

```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3```

</details>

**Comment by alexander-beedie** [comment]
Ahh, this isn't really a bug - you just happen to have the same number of rows as cols , causing the `orient` param to default to `col` orientation; duplicating the extra row helps it decide on "row" orientation instead. So, as you _know_ you have row-oriented data, just set `orient="row"` for your data ingest and everything will work fine  ;)

I'll have a look to see if we can make some cheap improvements to the auto-determination too.

**Comment by jicart** [comment]
Oh, I tried a bunch of stuff, but I did not think of that. 
Makes sense since it's a list of lists, so I need to tell polars the inner lists are rows and not columns.
Adding "orient='row'" argument fixed the problem.
Thank you.

Should I close the issue?

**Comment by alexander-beedie** [comment]
> Oh, I tried a bunch of stuff, but I did not think of that. Makes sense since it's a list of lists, so I need to tell polars the inner lists are rows and not columns. Adding "orient='row'" argument fixed the problem. Thank you.

No problem ;)

> Should I close the issue?

I have actually already got a smarter orientation auto-inference up and running locally, so I'll make a commit that will close this out - thanks for taking the time to make an issue ;)
