### ISSUE TITLE
'ExprListNameSpace' object has no attribute 'explode'.

### ISSUE THREAD

**Issue by bfeif** [pola-rs/polars#6371]
See https://github.com/pola-rs/polars/blob/f2e54b1ade61f270601330beb04b7c6516d13df4/py-polars/polars/internals/expr/list.py#L601-L628

Running the [documentation example](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.explode.html#polars.Expr.arr.explode) for `polars.Expr.arr.explode` returns an error:

```python
>>> df = pl.DataFrame({"a": [[1, 2, 3], [4, 5, 6]]})
>>> df.select(pl.col("a").arr.explode())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 2
      1 df = pl.DataFrame({"a": [[1, 2, 3], [4, 5, 6]]})
----> 2 df.select(pl.col("a").arr.explode())

AttributeError: 'ExprListNameSpace' object has no attribute 'explode'
```

For reference, my version is `pl.__version__ = '0.15.16'`.

**Comment by ritchie46** [comment]
Yeah, you are an early adapter. :yum: 

We just made a change in master that set it in `.arr`, but that change is not yet released. The docs however are generated from master so that are in the future. You can find `explode` simply on `pl.col("a").explode`.

**Comment by stinodego** [comment]
This is something we should fix (build versioned docs). I'll make an issue for that.

**Comment by bfeif** [comment]
> We just made a change in master that set it in `.arr`, but that change is not yet released. The docs however are generated from master so that are in the future. You can find `explode` simply on `pl.col("a").explode`.

Got it, yep that works; thanks. I'll leave it to you guys on whether or not to close the issue 👍

**Comment by stinodego** [comment]
Closing in favor of #6373
