### ISSUE TITLE
The argument `skip_rows` of `scan_csv` are only valid for the first csv file

### ISSUE THREAD

**Issue by Teamon9161** [pola-rs/polars#6388]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Suppose that there are three csv files in my current folder:

1.csv
```
wrong1,
a, b,
1, 2,
```
2.csv
```
wrong2,
a, b,
1, 2,
```
3.csv
```
wrong3,
a, b,
1, 2,
```
The first line is invalid data, the second line is header and the third line is valid data. So I should skip the first row of each file. 
However, if I use 
```python
df = pl.scan_csv('*.csv', skip_rows=1, has_header=True, ignore_errors=True).collect()
``` 
the output is 
```python
SchemaError: cannot vstack: because column names in the two DataFrames do not match for left.name='wrong1' != right.name='wrong2'
```
So I try to skip the header too
```python
df = pl.scan_csv('*.csv', skip_rows=2, has_header=False, ignore_errors=True).collect()
df
```
```
shape: (7, 2)
┌──────────┬──────────┐
│ column_1 ┆ column_2 │
│ ---      ┆ ---      │
│ str      ┆ str      │
╞══════════╪══════════╡
│ 1        ┆  2       │
│ wrong2   ┆ null     │
│ a        ┆  b       │
│ 1        ┆  2       │
│ wrong3   ┆ null     │
│ a        ┆  b       │
│ 1        ┆  2       │
└──────────┴──────────┘
```
It seems that only the first two lines of the first csv file are skipped, I hope that `skip_rows` can work for all csv files. If this is not a bug, is there any other efficient way to handle this situation?

### Reproducible example

```python
see above
```

### Expected behavior

shape: (3, 2)
```
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
│ 1   ┆ 2   │
│ 1   ┆ 2   │
└─────┴─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.3.4
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.7.8
deltalake: <not installed>
matplotlib: 3.4.3
```

</details>

**Comment by ritchie46** [comment]
This is quite ambiguous. Do you want to skip rows of the total read file, or union of the file. Polars chooses the union of the file.

If you want to have more control you scan the individual file yourself using python glob library and finish with a `concat`. This is exactly what polars does.
