### ISSUE TITLE
NaN returned by mean aggregation of empty set

### ISSUE THREAD

**Issue by FlorianWilhelm** [pola-rs/polars#640]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

'0.7.15'

#### What operating system are you using polars on?

MacOS Big Sur

#### Describe your bug.

Using column expressions in groupby functions, I would expect to get "Null" if the filtering in the column expressions returns an empty set regardless of the actual aggregation function.

#### What are the steps to reproduce the behavior?

```
import polars as pl

df = pl.read_csv("https://theunitedstates.io/congress-legislators/legislators-current.csv")
df.groupby(["state"]).agg([col("birthday").filter(col("gender") == "ALIEN").mean()]).sort(col("state"))
```

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/3184072/118274872-f7918c00-b4c5-11eb-8788-8f7b4d3f4f10.png)

#### What is the expected behavior?

I would have expected to see `Null` there.

 Even stranger is when `mean` is replaced by `first`
```
df.groupby(["state"]).agg([col("birthday").filter(col("gender") == "ALIEN").first()]).sort(col("state"))
```

Then we have:
![image](https://user-images.githubusercontent.com/3184072/118275004-23ad0d00-b4c6-11eb-8309-06ea5be882f0.png)

I would have expected to see `Null` too but here the same results are shown as if we would not have filtered for ALIENs.

**Comment by ritchie46** [comment]
Thanks for the issue report, I will look into this.

**Comment by ritchie46** [comment]
@FlorianWilhelm You'll have to compile from source (or wait a week), but it's fixed now.

**Comment by FlorianWilhelm** [comment]
That was fast! Thanks!
