### ISSUE TITLE
Serde for struct/list column

### ISSUE THREAD

**Issue by therealhieu** [pola-rs/polars#6405]
### Problem description

Hi, I want to cast/convert a struct/list column into a json string
From:
```json
{"struct": {"int": 1}, "int_list": [1, 2, 3]}
{"struct": {"int": 2}, "int_list": [4, 5, 6]}
```

To:
```json
{"struct": "{\"int\": 1}", "int_list": "[1, 2, 3]"}
{"struct": "{\"int\": 2}", "int_list": "[4, 5, 6]"}
```

How could I do this in Rust, I found that serde is not implemented for AnyValue::Struct/List yet.

**Comment by ritchie46** [comment]
I don't really understand? What is your data looking like? What is the first snippet you show.

**Comment by therealhieu** [comment]
The first snippet is Jsonline data where "struct" and "int_list" is 2 column. Column "struct" has struct datatype, column "int_list" has list datatype.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/38937534/214263626-523c0512-aad5-42ba-9a7f-bff1874c5cf0.png">

In the second snippet, I want to convert "struct" and "int_list" column into json strings

**Comment by ritchie46** [comment]
You can call `to_json`. If you fill in the template we can help you better.

**Comment by therealhieu** [comment]
Polars version checks
[ x ] I have checked that this issue has not already been reported. *
 [ x ] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars. *

# Issue description

I want to convert struct/list column into json string.

**Input**:

| struct     | int_list  |
|------------|-----------|
| {"int": 1} | [1, 2, 3] |
| {"int": 2} | [4, 5, 6] |

where

```rust
println!("{:?}", df);
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ struct    ┆ int_list  │
│ ---       ┆ ---       │
│ struct[1] ┆ list[i64] │
╞═══════════╪═══════════╡
│ {1}       ┆ [1, 2, 3] │
│ {2}       ┆ [4, 5, 6] │
└───────────┴───────────┘
```


**Expected output**:
| struct         | int_list    |
|----------------|-------------|
| "{"int": 1}" | "[1, 2, 3]" |
| "{"int": 2}" | "[4, 5, 6]" |

```rust
println!("{:?}", df);
```

```
shape: (2, 2)
┌────────────┬───────────┐
│ struct     ┆ int_list  │
│ ---        ┆ ---       │
│ str        ┆ str       │
╞════════════╪═══════════╡
│ {"int": 1} ┆ [1, 2, 3] │
│ {"int": 2} ┆ [4, 5, 6] │
└────────────┴───────────┘
```
```rust
println!("{:?}", df.schema());
```
```
Schema:
name: struct, data type: Utf8
name: int_list, data type: Utf8
```

**Comment by ritchie46** [comment]
This functionality is supported. Can you please open an stackoverflow question with a MWE? If you have done that you can post the link here and we can answer it.
