### ISSUE TITLE
Skew calculation is non-deterministic

### ISSUE THREAD

**Issue by Q-c7** [pola-rs/polars#6406]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As we can see below, the same operation applied twice produces different (albeit very close) results.
Looks like that the difference in dataframes is caused due to floating point errors. However, the problem here is that these floating point errors are non-deterministic - maybe parallelism messes up with order of operations, thus floating point errors may change randomly.

I'm not providing the full traceback because  `assert_frame_equal` function works as intended, these dataframes are indeed different.

NB: sometimes the assert gets passed - you might need to run the code below several times to catch an `AssertionError`.

### Reproducible example

```python
import polars as pl 
import numpy as np 
import pandas as pd 
from datetime import datetime, timedelta

from polars.testing import assert_frame_equal

np.random.seed(1337)
data = np.random.rand(10)
timestamps = datetime.now() + np.arange(10) * timedelta(seconds=1)
df = pl.DataFrame(columns=['ts', 'data'],
                  data=[pl.from_pandas(pd.Series(timestamps)).cast(pl.Datetime), pl.Series(data)])

df0 = df.groupby_dynamic(index_column='ts',
                         every='1s',
                         period='5s').agg(pl.col('data').skew().alias('skew'))

df1 = df.groupby_dynamic(index_column='ts',
                         every='1s',
                         period='5s').agg(pl.col('data').skew().alias('skew'))

assert_frame_equal(df0, df1, check_exact=True, nans_compare_equal=True)

"""
AssertionError: DataFrames are different

Exact value mismatch
[left]:  [0.3790179321154025, -0.05593396641795975, 0.4051143649613012, 1.0222350695578273, 0.3751771338335452, 0.1310870464216259, 0.11183908379683984, -0.4756582377446793, 0.0, nan]
[right]: [0.3790179321154025, -0.05593396641795967, 0.4051143649613012, 1.0222350695578273, 0.37517713383354534, 0.13108704642162594, 0.11183908379683984, -0.4756582377446793, 0.0, nan]
"""
```

### Expected behavior

`df0` and `df1` should have the exact same values.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Python: 3.10.8 (main, Oct 20 2022, 02:23:58) [GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Thanks for the report. Found the culprit. Simd correctness is dependent if memory alignment
