### ISSUE TITLE
Inconsistent parameter for output type

### ISSUE THREAD

**Issue by FlorianWilhelm** [pola-rs/polars#641]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

'0.7.15'

#### What operating system are you using polars on?

MacOS Big Sur

#### Describe your bug.

The parameter to define the output datatype is inconsistent in at least `apply` for `groupby` ([it's not even defined](https://pola-rs.github.io/polars/python/polars/frame.html#polars.frame.GroupBy.apply)), `Dataframe` ([it's called `output_type`](https://pola-rs.github.io/polars/python/polars/frame.html#polars.frame.DataFrame.apply)) and `Series` & `Expr` ([it's called `dtype_out`](https://pola-rs.github.io/polars/python/polars/series.html#polars.series.Series.apply))

**Comment by ritchie46** [comment]
Right, Could you make a PR to rename them consistently?

**Comment by FlorianWilhelm** [comment]
Yes, will do. 

One more thing related to that. Regarding `map` and `apply`, I find their meaning and what they actually do mixed up. For me `map` coming from mapping should be 1 to 1, i.e. scalar in scalar out, while `apply` is more general and thus works on a vector. With `map` you can create a custom aggregation function with the help of `groupby` which surely is not what you expect when you read `map`.

**Comment by ritchie46** [comment]
Sort of out of synonyms there. My idea is that you can map over anything, as long as it returns the same type. So we `map` over a `Series`, but you must return a `Series`. (That is similar to 1 to 1 mapping)

For the `apply`, you `apply` a function over `Series`, but you don't return a `Series`, instead you return single values that will be used to recreate a `Series`.

**Comment by FlorianWilhelm** [comment]
I think a lot of people still have the Map & Reduce in mind. There the map step means that you define a function that has access only to a single element or some atomic entity. BTW, in your definition, you map `Series` to `Series` but the shape of input and output `Series` might change, in this case, it's no longer a 1 to 1 mapping for me.

I am preparing a little Tech Session where I want to present Polars (stealing from your docs, I hope that's fine ;-). Check out the [Aggregration Operation (last example of my notebook)](https://github.com/FlorianWilhelm/polars_vs_pandas/blob/master/polars.ipynb). It looks not natural to me but maybe you have a better solution to it? I would rather want to read `apply` and not `map` there.

**Comment by ritchie46** [comment]
> I think a lot of people still have the Map & Reduce in mind. There the map step means that you define a function that has access only to a single element or some atomic entity. BTW, in your definition, you map Series to Series but the shape of input and output Series might change, in this case, it's no longer a 1 to 1 mapping for me.

Yes, That is not a perfect fit (regarding dtype and length). However, coming from `pandas`, a lot of users expect `apply` to `apply` over the elements, so that's what I want to keep using. If you have a better naming for the `map` I will think about an alias.

I am preparing a little Tech Session where I want to present Polars (stealing from your docs, I hope that's fine ;-). Check out the Aggregration Operation (last example of my notebook). It looks not natural to me but maybe you have a better solution to it? I would rather want to read apply and not map there.

I think you can use a `.apply`. In the `groupby` context this gets a `Series` of the values per group:

```python
df.groupby("groups").agg(col("values").apply(lambda a: a.sum()* 3))
```

> I am preparing a little Tech Session where I want to present Polars (stealing from your docs, I hope that's fine ;-).

Definitly. Nice that the word gets out. :)

**Comment by FlorianWilhelm** [comment]
> I think you can use a .apply. In the groupby context this gets a Series of the values per group:
```python
df.groupby("groups").agg(col("values").apply(lambda a: a.sum()* 3))
```
Okay, thanks, that's actually much nicer than my solution. So if `map` kind of always gets the whole data of the column and I thus need to define a function that takes a `pl.Series` and returns a `pl.Series`, why do I have to define the return type with the help of a `pl.udf` sometimes as you show in one of your examples? The output `Series` has a type anyway right? So if I return it I define the overall return type with it.

So my understanding is now:
* `map` is `Series` to `Series` mapping,
* `apply` maps an atomic entity within the context, i.e. element like float/int in column expression or `Series` in case of `groupby`, to a scalar.

**Comment by ritchie46** [comment]
> Okay, thanks, that's actually much nicer than my solution. So if map kind of always gets the whole data of the column and I thus need to define a function that takes a pl.Series and returns a pl.Series, why do I have to define the return type with the help of a pl.udf sometimes as you show in one of your examples? The output Series has a type anyway right? So if I return it I define the overall return type with it.

Yes, The UDF, is not needed anymore. I think I can better remove it, as it may be confusing. Anyhow, you may add a return `dtype`. This may slightly speed up things. If you don't specify a return type, polars tries to infer one. If it fails (because all values are `null`), it may panic.

> So my understanding is now:
    * map is Series to Series mapping,
    * apply maps an atomic entity within the context, i.e. element like float/int in column expression or Series in case of groupby, to a scalar.
    
That's correct. A `map` is `Series` to `Series`, and an `apply` is context dependent, as you described.

I shall update this part of the user guide: https://pola-rs.github.io/polars-book/user-guide/howcani/apply/udfs.html to make it more clear.

**Comment by FlorianWilhelm** [comment]
Thanks for pointing this out, I think it's great that `udf` is not needed, makes it much easier to define the return type directly as parameter. BTW, I renamed everything to `dtype_out` but am not sure if the name is so good. PySpark uses `returnType` which would be `return_type` in Python-style. It's somewhat more lengthy than `dtype_out` but might be easier for users to understand.

**Comment by ritchie46** [comment]
`return_dtype` is also fine by me. :+1:
