### ISSUE TITLE
Passing nonsense timezone to `with_time_zone` doesn't error, just sets elements to `'invalid timezone'`

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6416]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`.dt.with_time_zone('foo')` doesn't raise, it just sets everything to `'invalid timezone'`

### Reproducible example

```python
In [3]: pl.Series(['2020-01-01']*3).str.strptime(pl.Datetime).dt.with_time_zone('foo')
Out[3]:
shape: (3,)
Series: '' [datetime[μs, foo]]
[
        invalid timezone
        invalid timezone
        invalid timezone
]
```

### Expected behavior

I think it should probably raise?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
That would be a good addition!

**Comment by MarcoGorelli** [comment]
@stinodego do you think it should go further and `pl.Datetime('ns', 'foo')` should raise?

**Comment by stinodego** [comment]
From a user standpoint, that would be preferable. But in our code base this doesn't make a lot of sense at the moment, as there is no real logic going on in our DataType constructors.

I want to work on the DataType objects first (see #6163), before making a change like that.
