### ISSUE TITLE
`assert_frame_equal` should raise an informative error when input are `Series`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6418]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I accidentally passed in two Series, it just says "DataFrames are different".

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

s = pl.Series([1, 2, 3])

assert_frame_equal(s, s)
```

Results in:

```
AssertionError: DataFrames are different

Type mismatch
[left]:  <class 'polars.internals.series.series.Series'>
[right]: <class 'polars.internals.series.series.Series'>
```

### Expected behavior

There is no type mismatch, and the input aren't dataframes. It should raise an error with something like "input must be a dataframe".

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Might be as easy as recursing with an `s.to_frame()` call.
