### ISSUE TITLE
`#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by PoorRican** [pola-rs/polars#6420]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I am trying to compile a simple program to begin experimenting with the `polars` crate however I am getting the error "`#![feature]` may not be used on the stable release channel". I researched and think that somehow the `nightly` featured is enabled by default.

### main.rs
```
use polars::prelude::*;

fn main() {
    let df = df![{'A' => &[1, 2, 3]}];
}
```

### Cargo.toml
```
[package]
name = "learning_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.26.1" }
```

### Expected behavior

I'd expect this code to compile.

### Installed versions

`rustc 1.66.1 (90743e729 2023-01-10)`

**Comment by ritchie46** [comment]
Which feature cannot be used?

**Comment by marcelbischoff** [comment]
Getting the same error when `pip install --upgrade polars`

**Comment by ritchie46** [comment]
> Getting the same error when `pip install --upgrade polars` and it happens during compiling `hashbrown` `rustc 1.66.1 (90743e729 2023-01-10)`
> 
> `polars==0.15.16` works, but `polars==0.15.17` doesn't.
> 
> _edit_ just saw the `0.15.17` wheel for MacOS is still building that is why it is building from source, I suppose.

Yeap, that's the case. Unlucky timing. ;)

**Comment by marcelbischoff** [comment]
> Yeap, that's the case. Unlucky timing. ;)
Yes 🤣
