### ISSUE TITLE
Initializing empty `DataFrame` with list-of-structs dtype gives incorrect results

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6429]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See examples.

### Reproducible example

```python
import polars as pl

schema = {
    "id": pl.Int64,
    "items": pl.List(pl.Struct({"a": pl.Int64, "b": pl.Int64})),
}

# Incorrectly results in dtype Int32 for the "items" column
df = pl.DataFrame(columns=schema)
print(df)

# shape: (0, 2)
# ┌─────┬───────┐
# │ id  ┆ items │
# │ --- ┆ ---   │
# │ i64 ┆ i32   │
# ╞═════╪═══════╡
# └─────┴───────┘

# Correct output when specifying some data
data = [{"id": 1, "items": [{"a": 1, "b": 2}]}]
df = pl.DataFrame(data, columns=schema, orient="row")
print(df)

# shape: (1, 2)
# ┌─────┬─────────────────┐
# │ id  ┆ items           │
# │ --- ┆ ---             │
# │ i64 ┆ list[struct[2]] │
# ╞═════╪═════════════════╡
# │ 1   ┆ [{1,2}]         │
# └─────┴─────────────────┘
```

### Expected behavior

I expect an empty struct of the correct dtype:

```
┌─────┬─────────────────┐
│ id  ┆ items           │
│ --- ┆ ---             │
│ i64 ┆ list[struct[2]] │
╞═════╪═════════════════╡
└─────┴─────────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is python only right?

**Comment by stinodego** [comment]
Not sure where the issue is; haven't tried to recreate this in Rust.

**Comment by ritchie46** [comment]
> Not sure where the issue is; haven't tried to recreate this in Rust. But this could very well be in the Python constructor magic.

I am pretty sure it is. In rust we don't have such a constructor and we can only pass columnar series which are typed.

**Comment by alexander-beedie** [comment]
You know if you look in a mirror and say "constructors" three times I'll appear? 🤣 I'll have a few hours of "coffee shop development time" tomorrow afternoon to take a look. I improved the situation with empty-frame initialisation and Stuct dtypes recently; it might be that nested List dtypes can be similarly improved.

**Comment by alexander-beedie** [comment]
Later than planned, but got to it in the end...😅
