### ISSUE TITLE
Indexing is really confusing

### ISSUE THREAD

**Issue by FlorianWilhelm** [pola-rs/polars#644]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.7.15

#### What operating system are you using polars on?

MacOS Big Sur

#### Describe your bug.

Indexing for rows and columns works differently if a scalar or list is passed.

#### What are the steps to reproduce the behavior?

```
df[1,3] # index by (row, column)
```

vs.

```
edf[1,[3]]  # index by (column, row)
```

**Example**
![image](https://user-images.githubusercontent.com/3184072/118356327-084d0b00-b575-11eb-98c2-5ef7622b6532.png)

#### What is the actual behavior and expected?

`df[1,3]` returns a scalar from the second row and fourth column as expected. `edf[1,[3]]` returns the fourth row from the second column as a series which is quite unexpected. I would have expected to get the same value as with `df[1,3]` but in a series.

**Comment by ritchie46** [comment]
Hmm.. that's an accidental side effect. I don't know if I even intended support for this kind of indexing. But its a trivial addition, so I will look into it.
