### ISSUE TITLE
Filtered dataframe cannot be written to `JsonWriter`

### ISSUE THREAD

**Issue by seongs1024** [pola-rs/polars#6449]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Cannot write dataframe obtained from `ParquetReader` to `JsonWriter`.

Found the error in the step of writing dataframe to the buffer.
Dataframe was imported by `ParquetReader` and the converted json string was going to be written to the buffer.
But there is nothing in the buffer. (There were only '`[`' and '`]`' and the bytecodes were `91` and `93`, respectivly.)

```rust
fn get_data() -> DataFrame {
    return LazyFrame::scan_parquet("data/btcusdt-15m-2020-01-01-2022-12-31.parquet", ScanArgsParquet::default())
        .expect("Cannot open parquet file")
        .select([
            cols(["openTime", "open", "high", "low", "close", "volume"]),
        ])
        .collect()
        .expect("Cannot open parquet file")
}

fn convert_df_to_json_data(df: &DataFrame) -> String {
    let mut buffer = Vec::new();

    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::Json)
        .finish(&mut df.clone())
        .unwrap();

    return String::from_utf8(buffer).unwrap()
}
```

### Reproducible example

1. `get_data()`
2. `convert_df_to_json_data()`

### Expected behavior

the dataframe is written to the buffer.

### Installed versions

```toml
polars = { version = "0.26.1", features = ["json", "parquet", "lazy"] }
```

**Comment by universalmind303** [comment]
Are you able to share minimal `.parquet` file that produces this error?

**Comment by seongs1024** [comment]
[btcusdt-15m-2020-01-01-2022-12-31.zip](https://github.com/pola-rs/polars/files/10506605/btcusdt-15m-2020-01-01-2022-12-31.zip)

It is the file!

**Comment by seongs1024** [comment]
I'm sorry the error occurs when the data filtered.
```rust
 let df = get_data();
 let df = df
        .lazy()
        .filter(col("openTime").gt_eq(lit(1671840000000i64)).and(col("openTime").lt(lit(1671926400000i64))))
        .collect()
        .unwrap();
  let json = convert_df_to_json_data(&df);
```

**Comment by universalmind303** [comment]
@ritchie46 This seems like a bug in`df.rechunk()`

I'm not familiar with the logic that determines when it `should_rechunk`, but for this specific dataset, `should_rechunk` returns `false` so the `rechunk` doesn't happen. If i manually rechunk via `as_single_chunk_par` the output is fine. So it makes me think there is potentially a bug in the `should_rechunk` logic. 

for example, if i get the head off of this df
```rust
let mut df = df.head(Some(10));
```
```rust
df.n_chunks(); // -> 210
df.rechunk();
df.n_chunks(); // -> 210
```
 It seems unsound that a df of height 10 would have 210 chunks **after** rechunking.

**Comment by universalmind303** [comment]
@seongs1024 as a workaround, you can use `as_single_chunk_par` or `as_single_chunk` before writing to json.

```rust
fn convert_df_to_json_data(df: &mut DataFrame) -> String {
    df.as_single_chunk_par();
    let mut buffer = Vec::new();

    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::Json)
        .finish(df)
        .unwrap();

    return String::from_utf8(buffer).unwrap()
}

**Comment by seongs1024** [comment]
Thank you @universalmind303 it works when `as_single_chunk_par()` is added!
