### ISSUE TITLE
Integer division not flooring negative numbers

### ISSUE THREAD

**Issue by MichalLebeda** [pola-rs/polars#6450]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Integer divison ceils negative numbers, which is inconsistent with Python.

### Reproducible example

```python
import polars as pl

print("Python: ", -5 // 10,",", 5 // 10)
df = pl.DataFrame({
    "a": [-5, 5]
}).select(pl.col("a") // 10)
print("Polars: ", df)
```

Output:
```
Python:  -1 , 0
Polars: shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 0   │
│ 0   │
└─────┘
```

### Expected behavior
```
Python:  -1 , 0
Polars: shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ -1  │
│ 0   │
└─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.17
Index type: UInt32
Platform: Linux-5.15.86-1-lts-x86_64-with-glibc2.36
Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: 0.8


```

</details>

**Comment by ghuls** [comment]
Might be related to : https://github.com/pola-rs/polars/issues/3824

**Comment by ritchie46** [comment]
On floating points we do floor division, while on integers we use integer division. I think we should use floor division for all as floats currently do give the expected result.

**Comment by s-banach** [comment]
Just for fun, I parameterized `test_floor_division_float_int_consistency()` with different polars dtypes, and found what seems to be an error.

```python
import polars as pl

q = pl.Series(values=[1], dtype=pl.UInt64) // 2
print(q.dtype)  # Float64
```

**Comment by ritchie46** [comment]
What's strange is that it is correct when the series has a name?
