### ISSUE TITLE
Semi-join issue introduced in `0.15.17`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6455]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This issue was introduced with `0.15.17`.

### Reproducible example

```python
from datetime import datetime

import polars as pl

df = pl.DataFrame(
    {
        "id": [1, 1, 2],
        "timestamp": [datetime(2022, 12, 11), datetime(2022, 12, 12), datetime(2022, 1, 1)],
        "value": [1, 2, 4],
    }
).lazy()

latest = df.groupby("id").agg(pl.col("timestamp").max())
df = df.join(latest, on=["id", "timestamp"], how="semi")
result = df.select(["id", "value"]).collect()

print(result)
# pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NotFound(Owned("id"))
```

### Expected behavior

I expect the code to execute normally.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.17
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
Random semi-related question to help my Polars knowledge:

Would the code outlined in this example (`groupby` -> `semi-join`) be faster, slower, or similar in performance when compared to `window` -> `filter`?

**Comment by ritchie46** [comment]
So there will be a 0.15.18 :see_no_evil:

**Comment by ritchie46** [comment]
> 

I think the filter as well. But it will likely depend.
