### ISSUE TITLE
polars-core fails to build for target wasm32-wasi

### ISSUE THREAD

**Issue by huxi** [pola-rs/polars#6463]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

polars-core 0.26.1 fails to build with `--target wasm32-wasi`.

This is caused by the dependency comfy-table 6.1.4 that introduces crossterm 0.25.0 as an optional but default dependency.

This seems to be the only thing preventing a `wasm32-wasi` build right now.

Related issues:
- https://github.com/crossterm-rs/crossterm/issues/654
- https://github.com/WebAssembly/WASI/issues/161

### Reproducible example

Build any polar project with `cargo build --target wasm32-wasi`

### Expected behavior

Build shouldn't fail.

### Installed versions

<details>
polars = { version = "0.26", features = ["lazy", "polars-algo"] }
</details>

**Comment by ritchie46** [comment]
You can turn off feature `fmt`.

**Comment by huxi** [comment]
That helped, thanks! Also for the fast response!

Building works now but executing the resulting wasm file using `wasmtime` now fails with the following error:
```
The application panicked (crashed).
Message:  could not mmap file: Io(Custom { kind: Other, error: "platform not supported" })
Location: /Users/huxi/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-plan-0.26.1/src/logical_plan/builder.rs:199
```

I guess `wasm32-wasi` target just isn't a supported platform at this point. I was mainly curious and wanted to give it a shot.

**Comment by ritchie46** [comment]
I think you should turn off csv as well. This support is also not formal by polars. I believe there is a special wasm issue. You could follow and respond to that issue to push that support further. 

I will close this for now.
