### ISSUE TITLE
Support ADBC database connector.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6465]
### Problem description

We should investigate how we can support ADBC. This might also allow us to write back to a database.

## python example
https://arrow.apache.org/adbc/0.1.0/python/quickstart.html

## api
https://arrow.apache.org/docs/format/ADBC.html

**Comment by gam-phon** [comment]
I see that ADBC will be the standard database interfaces with Arrow. Good
Maybe in the long run it will support more database types like below issue
- #6436

**Comment by alexander-beedie** [comment]
Was closed by https://github.com/pola-rs/polars/pull/7318.
