### ISSUE TITLE
utc parameter in strptime

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6466]
### Problem description

When processing multiple fixed offsets / timezones, pandas has a `utc` parameter which allows you to still parse the elements, and then set whatever timezone you want.

For example:
```python
In [73]: ts = ['2021-03-27T23:59:59+01:00', '2021-03-28T23:59:59+02:00']

In [74]: pd.to_datetime(ts, utc=True).tz_convert('Europe/Vienna')
Out[74]: DatetimeIndex(['2021-03-27 23:59:59+01:00', '2021-03-28 23:59:59+02:00'], dtype='datetime64[ns, Europe/Vienna]', freq=None)
```

I don't think there's a way to do this in polars, other than
```python
In [76]: pl.Series(ts).str.split('+').arr.get(0).str.strptime(pl.Datetime).dt.with_time_zone('UTC').dt.cast_time_zone('Europe/Vienna')
Out[76]:
shape: (2,)
Series: '' [datetime[μs, Europe/Vienna]]
[
        2021-03-27 23:59:59 CET
        2021-03-28 23:59:59 CEST
]
```

I'll include this as a recipe in https://github.com/pola-rs/polars-book/pull/234, but longer-term, would you be open to a UTC parameter?

- `utc=True` would convert each element to UTC and set that as the timezone (like pandas does)
- `utc=False` with mixed timezones would error (unlike pandas - but [my hope is that this is what pandas will do too](https://github.com/pandas-dev/pandas/issues/50887))

---

[SO question for reference](https://stackoverflow.com/questions/75243040/conversion-of-iso-datetime-string-to-pl-datetime-failure/75246248#75246248)

**Comment by ritchie46** [comment]
So if I understand correctly, the `utc=True` will simply ignore the given time zone?

If we default to `utc=False` and error, I think this would be a great addition.

**Comment by MarcoGorelli** [comment]
It will convert everything to UTC, so everything will be in the same timezone - it's then up to the caller to cast back to whatever time zone they want, such as one that crosses DST:
```python
In [3]: ts = ['2021-03-27T00:00:00+01:00', '2021-03-28T00:00:00+02:00']

In [4]: pd.to_datetime(ts, utc=True)
Out[4]: DatetimeIndex(['2021-03-26 23:00:00+00:00', '2021-03-27 22:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None)
```

**Comment by ritchie46** [comment]
RIght, I understand. Would you be interested in exploring this one?

**Comment by MarcoGorelli** [comment]
sure, I'll give it a go!

**Comment by ritchie46** [comment]
Awesome, I appreciate this doubly as I really disliket thinking about timezones. :see_no_evil:

**Comment by FObersteiner** [comment]
> Awesome, I appreciate this extra as I really disliket thinking about timezones. see_no_evil

it's just a UTC offset here, so straight-forward calculation, no timezone rules, no politics ;-)

**Comment by MarcoGorelli** [comment]
I think there might be a simpler solution, actually - `tz_aware` can be `None` or `bool`, instead of just `bool`. Then:
- if it's `None`, then tz-awareness would be auto-detected by `fmt`
- otherwise, `tz_aware` is simply whatever the user passed

So in this example,
```python
In [1]: ts = ['2021-03-27T23:59:59+01:00', '2021-03-28T23:59:59+02:00']

In [2]: pl.Series(ts).str.strptime(pl.Datetime, '%+', tz_aware=False)
Out[2]: 
shape: (2,)
Series: '' [datetime[μs]]
[
        2021-03-27 23:59:59
        2021-03-28 23:59:59
]
```
would work, and then if the user wants to set `'Europe/Vienna'` or whatever time zone their data's in, then they're free to do that

**Comment by FObersteiner** [comment]
> I think there might be a simpler solution, actually - `tz_aware` could be allowed to be `bool | None`, instead of just `bool`. 

How would this allow to unambiguously parse mixed-UTCoffset input to aware datetime? That just provides an override to the auto-detection, no?

IIUC, 
- if `tz_aware = False` but fmt contains `%z` (or equivalent), UTC offset is ignored
- if `tz_aware = True` and fmt contains `%z` (or equivalent), that should result in aware datetime

**Comment by MarcoGorelli** [comment]
You could do what I demonstrated above:
```python
In [1]: ts = ['2021-03-27T23:59:59+01:00', '2021-03-28T23:59:59+02:00']

In [2]: pl.Series(ts).str.strptime(pl.Datetime, '%+', tz_aware=False)
Out[2]: 
shape: (2,)
Series: '' [datetime[μs]]
[
        2021-03-27 23:59:59
        2021-03-28 23:59:59
]
```
and then cast to your timezone:
```python
In [3]: ts = ['2021-03-27T23:59:59+01:00', '2021-03-28T23:59:59+02:00']

In [4]: pl.Series(ts).str.strptime(pl.Datetime, '%+', tz_aware=False).dt.with_time_zone('UTC').dt.cast_time_zone('Europe/Vienna')
Out[4]: 
shape: (2,)
Series: '' [datetime[μs, Europe/Vienna]]
[
        2021-03-27 23:59:59 CET
        2021-03-28 23:59:59 CEST
]
```

Do you have an example of where this would not be sufficient?

**Comment by FObersteiner** [comment]
As I commented on Stackoverflow, this requires prior knowledge of the actual time zone. If that is not the case, you must have an option to *parse* the UTC offset. A full featured-library that allows time series handling should provide that. This is independent of the question if the output should be UTC (`utc` keyword) or a mixed UTC offset time series. I'd be fine with the "pandas-version" (UTC-only), but that's personal preference.

I'm not happy with the auto-infer behavior of `tz_aware`. Why not make the default `tz_aware = True`? If `%z` or equivalent is ***not*** supplied, this keyword can simply be ignored. Introducing *another* state ("None") on the other hand does not solve the general problem IMHO.

**Comment by MarcoGorelli** [comment]
> this requires prior knowledge of the actual time zone

🤔 ok, true, thanks. This doesn't strike me as a common use-case, but you're right that `tz_aware=False` wouldn't address that

**Comment by MarcoGorelli** [comment]
@FObersteiner I've given this a go in https://github.com/pola-rs/polars/pull/6496, if you have any feedback I'd love to hear it
