### ISSUE TITLE
Cell operation in dataframe like pandas's at function

### ISSUE THREAD

**Issue by kkonghao** [pola-rs/polars#647]
Hi,do polars have plan to support at method to get or change cell value in dataframe with index and column like pandas ? https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html?highlight=#pandas.DataFrame.at

**Comment by ritchie46** [comment]
Due to the memory layout being immutable, I don't want to make it too easy to modify single values, as they are bad practice and will yield very bad performance. If you need to modify values its best to do this on a whole column based on a `mask`/ `predicate`.

**Comment by ritchie46** [comment]
The polars `DataFrame.__getitem__` now works the same as pandas at. 

`df[0, 1]` yields row 0 and column 1.
