### ISSUE TITLE
Support more datatypes in .clip(), .clip_max() and .clip_min()

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#6470]
### Problem description

The current API is very explicit that the `.clip` methods only support `int` & `float` values. 

I propose this be extended to any in-built, naturally ordered data type - ie. `pl.Date`, `pl.Datetime`, `pl.Duration`.

The following code would be a good example of what I envision:

```python
import polars as pl 
from datetime import datetime

pl.DataFrame({
    'eventBegin': [datetime(2020, 1, 1)], 
    'eventEnd': [datetime(2099, 1, 1)]
}).with_columns(
    # Clip the event duration to the 0-7 day range
    eventDuration = (pl.col('eventEnd') - pl.col('eventBegin')).clip(pl.duration(days=0), pl.duration(days=7))
)

```

The benefits are not major, they just allow for a little more consistency across project codebases.

**Comment by gab23r** [comment]
@ritchie46, we could even accept Expr for min and max argument, In this case we could maybe use when().then().otherwise() internally ? Or it will lose too much in performance compare to the basic case where we clip from int | float ?

**Comment by ritchie46** [comment]
We could accept an expression indeed. This should not be done with when then otherwise. Underneath we could use the physical types (which are integers) and the cast back.

I would accept a PR on this.

**Comment by gab23r** [comment]
I am on it !

**Comment by gab23r** [comment]
@reswqa, You've done an amazing job with the great expressification 😄 Thanks !  Would you have the time to look at this one ?

**Comment by ritchie46** [comment]
No, I think we should cast the arguments to the base type.
