### ISSUE TITLE
'Connection' object has no attribute 'split'`

### ISSUE THREAD

**Issue by mfernandes3** [pola-rs/polars#6484]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`AttributeError: 'Connection' object has no attribute 'split'`

with pl.read_sql(query, conn). PostgreSQL database. I believe this is coming from ConnectorX, but not sure. 

Version of polars: `0.15.18`
Version of ConnectorX: `0.3.1`

### Reproducible example

```python
import polars as pl
pl.read_sql(query, conn)
```

### Expected behavior

Should load table into dataframe. Same connection and Query works with Pandas (pd_read_sql)

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.17
Python: 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.20.3
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Can you please make a reproducable example?

**Comment by mfernandes3** [comment]
Thanks for the fast reply. I found out why. Please close the issue.

I was used to psycopg and the way the connection and query is made is slightly different. It now works as described here:https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_sql.html

The connection needs to be like: `postgresql://username:password@server:port/database`

And for the query:
If you use `SELECT * FROM table;` it does not work but `SELECT * FROM table` it does. The ";" gives also an error: `RuntimeError: db error: ERROR: syntax error at or near ";"`

Perhaps this can be written somewhere to avoid further issues?

Thanks, polars is awesome!

**Comment by mcrumiller** [comment]
@mfernandes3 the reason for the run-time error is because connectorx doesn't support multiple queries, which are  separated by semicolons. It's not documented and everybody figures this out the first time they use it :D

**Comment by mfernandes3** [comment]
Thanks for the clarification @mcrumiller
