### ISSUE TITLE
Confusing behavior when using list in pl.col()

### ISSUE THREAD

**Issue by trinebrockhoff** [pola-rs/polars#6485]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using list as selection in the pl.col([]) the result is unexpected. 

I'll rather expect an error or the correct result. 

When using list as selection in pl.col, I get: `result_wrong` which seems to be `LongitudeNext * 2` 
When using string (col-name) as selection in pl.col, I get: `result_right` which is expected result.

I get same kind of error for all arithmetic operators: `(+,-,/,*)`.

![image](https://user-images.githubusercontent.com/61736696/215052737-2909df8b-3b0c-4568-bdfe-2de2d78182d7.png)

### Reproducible example

```python
pl_coordinates = pl.DataFrame({"Longitude":[4.,5.,6.,7.,8.], "LongitudeNext":[3.,87.,43.,63.,34.]})

result_wrong = pl.col(["LongitudeNext"]) + pl.col(["Longitude"])
result_right = pl.col("LongitudeNext") + pl.col("Longitude")

pl_coordinates.with_columns(
    [
        result_wrong.alias("result_wrong"),
        result_right.alias("result_right"),
    ]
)
```

### Expected behavior

Raise error or give correct result.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.3.5
numpy: 1.21.5
fsspec: 2021.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.3```

</details>

**Comment by cmdlineluser** [comment]
Just thought I'd add an example with strings as it helped visualize the problem for me:
```
>>> df = pl.DataFrame({"a": ["foo", "bar"], "b": ["hello", "hi"]})
>>> df.select(pl.col("a") + pl.col("b"))
shape: (2, 1)
┌──────────┐
│ a        │
│ ---      │
│ str      │
╞══════════╡
│ foohello │
├──────────┤
│ barhi    │
└──────────┘
```
```
>>> df.select(pl.col(["a"]) + pl.col(["b"]))
shape: (2, 1)
┌────────┐
│ a      │
│ ---    │
│ str    │
╞════════╡
│ foofoo │
├────────┤
│ barbar │
└────────┘
```
Which seems to confirm that when multiple `pl.col([...])` expressions are used - they all "point" to the first one.
