### ISSUE TITLE
infer_schema_length does not work properly with generators

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6489]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Schema inference does not work with generators even if `infer_schema_length` is equal to the size of the data. 

It must come from `construction.iterable_to_pydf` default `values` value (line 1168) used inside the `DataFrame.__init__`:
```
values = list(islice(data, adaptive_chunk_size or 1000))
```
If a whole chunk of the generator has different columns type than other chunks it will return an error.

### Reproducible example

```python
import polars as pl


for limit_size in range(5000):
    data = [{'col': None} for i in range(limit_size)]
    data.append({'col': ['a', 'b', 'c']})

    pl.DataFrame(iter(data), infer_schema_length=limit_size + 1)
    print(f'Works fine for {limit_size = }')
```

### Expected behavior

Not to return error for any `limit_size` value.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.0
numpy: 1.21.1
fsspec: 2021.10.0
connectorx: 0.3.0
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
@PieReissyet: forgot to say - thanks for the bug report and (most of all) the nice clean test case ;)
