### ISSUE TITLE
inconsistent behavoir in row selection with boolean mask 

### ISSUE THREAD

**Issue by zhangyingmath** [pola-rs/polars#649]
version 0.7.16.
```python
df = pl.DataFrame({'f': [1,2,3,None], 'g': list('abcd')})
df['f'] == df['f']
Out[28]: 
Series: '' [bool]
[
	true
	true
	true
	null
]

df[df['f'] == df['f']]
Out[29]: 
shape: (4, 2)
╭──────┬─────╮
│ f    ┆ g   │
│ ---  ┆ --- │
│ i64  ┆ str │
╞══════╪═════╡
│ 1    ┆ "a" │
├╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2    ┆ "b" │
├╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 3    ┆ "c" │
├╌╌╌╌╌╌┼╌╌╌╌╌┤
│ null ┆ "d" │
╰──────┴─────╯
```

I am surprised that the fourth row is selected. 
 Compare:
 
```python 
df[[True, True, True, None]]
Out[51]: 
shape: (3, 2)
╭─────┬─────╮
│ f   ┆ g   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ "a" │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ "b" │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ "c" │
╰─────┴─────╯
```

Now the fourth row is not selected. What is going on here?

**Comment by ritchie46** [comment]
Thanks for reporting this issue, I will look into this.

**Comment by ritchie46** [comment]
https://github.com/apache/arrow-rs/issues/295

https://github.com/apache/arrow-rs/pull/296

**Comment by zhangyingmath** [comment]
Thanks @ritchie46! As an aside, when I have a column of booleans, True is represented as "true", False is "false", is there a reason for this?

**Comment by ritchie46** [comment]
Python is one of the few languages that uses boolean that start with a capital letter. Polars is written in rust, where booleans are all low caps.

**Comment by zhangyingmath** [comment]
I see, thanks! So you are saying the lower case representation comes from Rust.
