### ISSUE TITLE
parquet io with structs-of-lists panics or imports garbage

### ISSUE THREAD

**Issue by khusmann** [pola-rs/polars#6501]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Parquet IO with structs-of-lists appears to be broken. I think it's on the reading side? I tried inspecting the resulting files with parquet-tools and it looks ok (at least the # rows / columns looked alright), but don't know enough about the format & Polars to verify beyond that.

### Reproducible example

```python
import polars as pl

pl.DataFrame({"foo": [{"bar": [], "baz": [1, 2]}]}).write_parquet("bug.parquet")
pl.read_parquet("bug.parquet")

# Result: PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("The children must have an equal number of values. However, the values at index 1 have a length of 1, which is different from values at index 0, 0.")

pl.DataFrame({"foo": [{"bar": [100], "baz": [1, 2]}]}).write_parquet("bug.parquet")
pl.read_parquet("bug.parquet")

# Result: (missing a 2)
# shape: (1, 1)
#┌─────────────┐
#│ foo         │
#│ ---         │
#│ struct[2]   │
#╞═════════════╡
#│ {[100],[1]} │
#└─────────────┘

pl.DataFrame({"foo": [{"bar": [100, 200], "baz": [1, 2]}]}).write_parquet("bug.parquet")
pl.read_parquet("bug.parquet")

# Result: New row? 
# shape: (2, 1)
#┌─────────────┐
#│ foo         │
#│ ---         │
#│ struct[2]   │
#╞═════════════╡
#│ {[100],[1]} │
#│ {[200],[2]} │
#└─────────────┘

pl.DataFrame({"foo": [{"bar": [100, 200, 300], "baz": [1, 2]}]}).write_parquet("bug.parquet")
pl.read_parquet("bug.parquet")

# Result: missing 300 & has new row
# shape: (2, 1)
#┌─────────────┐
#│ foo         │
#│ ---         │
#│ struct[2]   │
#╞═════════════╡
#│ {[100],[1]} │
#│ {[200],[2]} │
#└─────────────┘
```

### Expected behavior

Ideally, the nested structures should save/load without being corrupted :)

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.31
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.0
numpy: 1.23.4
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by ritchie46** [comment]
Yes, this is known. Please update to latest version. It defaults to pyarrow.

**Comment by khusmann** [comment]
Wow, y'all move quick! Sorry for the dupe. Looks like the polars packages in conda-forge have been falling behind due to a build error. I'll see if I can take care of that, that's something I know a thing or two about & can contribute.

**Comment by ritchie46** [comment]
> Wow, y'all move quick! Sorry for the dupe. Looks like the polars packages in conda-forge have been falling behind due to a build error. I'll see if I can take care of that, that's something I know a thing or two about & can contribute.

That'd would be great. There is often something going wrong there and I don't have the capacity to include conda.
