### ISSUE TITLE
`join` fails if column with same suffix already exists

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#6503]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When joining, we should check is the resulting columns names (including with suffix) already exists.
While the resulting column name exists, we keep adding the suffix  

### Reproducible example

```python
df = pl.DataFrame({'A' : range(2), 'B' : range(2)})
(
    df
    .join(df, on = ['A'])
    .join(df, on = ['A'])
)
# exceptions.DuplicateError: Cannot do hstack operation. Column with name: B_right already exists
```

### Expected behavior

I should have a `B_right_right` column and no exception

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by mcrumiller** [comment]
I don't know if I agree with this. Consider this ridiculous case:

```python
df = pl.DataFrame({'A': [1, 2, 3], "A_right": [1, 2, 3]}, "A_right_right": [1, 2, 3])
df2 = df.join(df, on=['A'], suffix="_right")
```

What should happen here? Should the final list of columns be `A`, `A_right`, `A_right_right`, `A_right_right_right`, `A_right_right_right_right`, and `A_right_right_right_right_right`? Polars would have to first figure out how many suffixes are needed before beginning, and in doing so it's not returning what the user requested.

**Comment by ritchie46** [comment]
I don't know about this one. I think raising this error is valid. Maybe we could document this and advice users to change suffixes on multiple joins. E.g `r1`, `r2` etc.

**Comment by gab23r** [comment]
Ok, I admit that it is more tricky than I though...

**Comment by ritchie46** [comment]
I will close this issue as explicitly choosing suffixes seems most clear to me.
