### ISSUE TITLE
`DataFrame` creation with datetime needs `pyarrow`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#6505]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It feels like a bug because I don"t get why we need pyarrow here, but maybe not 

### Reproducible example

```python
import polars as pl
import datetime

df = pl.DataFrame({
    'data': [datetime.datetime.now()],
})

# ModuleNotFoundError: pa.int8 requires 'pyarrow' module to be installed
```

### Expected behavior

No error

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>

```

</details>

**Comment by zundertj** [comment]
Thank you for reporting this. However, it has been reported before, see #5552, so I will close this issue. Please upvote and/or comment on #5552.
