### ISSUE TITLE
Exposing str -> int map for categorical columns

### ISSUE THREAD

**Issue by esadler-hbo** [pola-rs/polars#6512]
### Problem description

I am switching from using pyspark / sklearn to polars for encoding categorical data from 0 to n because it is really really fast. On a large instance we got 100m rows in like 15 seconds. 

I imagine somewhere in polars there is a mapping that I could access. It would be nice to use it to decode future samples without querying the data a second time. 
 
 In pandas I can do something like this:
```
 list(zip(df_labels.col2.cat.codes, df_labels.col2.cat.categories))
```

Maybe it is possible now, but I couldn't find it. Mostly curious if there is a quick way to expose similar functionality.

**Comment by stinodego** [comment]
I am actually working on implementing this right now. See issue https://github.com/pola-rs/polars/issues/5671.

In the meantime, you can do the following:

```python
s = pl.Series(["a", "c", "b", "a", "c"], dtype=pl.Categorical)
categories = s.unique().cat.set_ordering("physical").sort()
```

This resulting `Series` will have each category, with the index being the underlying integer representation.
