### ISSUE TITLE
Support for polymorphism in df! macro or df constructor

### ISSUE THREAD

**Issue by daryllimyt** [pola-rs/polars#6514]
### Problem description

Hi, are there any plans to support polymorphism in the df! macro or the dataframe constructor for conversion from other data structures?

My intended use case would be to convert Rust ndarrays into datafames, but if I'm not mistaken there currently isn't a direct API to do just that. I've seen these other issues that have relevant workarounds that I'm using right now: #1104 #213.

e.g.

```
// Some ndarray
let ndarray = ... ; 
let df = df!(ndarray);
```

**Comment by ritchie46** [comment]
Nope, no plans. You need to be explicit in this case. It also heavily depends of feature flags.
