### ISSUE TITLE
Binary type data disappears when pickled

### ISSUE THREAD

**Issue by nrlugg** [pola-rs/polars#6515]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a `pl.Binary` type Series is pickled and unpickled, the data is lost (all becomes `null`) and the type is changed to `pl.Int32`.

This is a particular problem when using `multiprocessing` (or similar) since when I multiprocess over data with `pl.Binary` columns, that data is lost when sent to the other processes (via pickle).

This also happens for `dill`.

### Reproducible example

```python
import pickle
import numpy as np
import polars as pl

data = pl.Series(
    "binary_data",
    [np.random.bytes(l) for l in np.random.randint(4, 16, (8,))]
)

print(data)
"""
shape: (8,)
Series: 'binary_data' [binary]
[
	[binary data]
	[binary data]
	[binary data]
	[binary data]
	[binary data]
	[binary data]
	[binary data]
	[binary data]
]
"""

print(pickle.loads(pickle.dumps(data)))
"""
shape: (8,)
Series: 'binary_data' [i32]
[
	null
	null
	null
	null
	null
	null
	null
	null
]
"""
```

### Expected behavior

There Series data should not change.

### Installed versions

<details>

```
--Version info---
Polars: 0.15.18
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.10.9 (main, Jan 17 2023, 15:47:44) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
This requires serde to implemented for `dtype-binary`. This is a good first issue. One can look at the serde for the other data types for inspiration.

**Comment by papparapa** [comment]
May I work on it?

**Comment by ritchie46** [comment]
> May I work on it?

Please 🙂

**Comment by nrlugg** [comment]
Omg this is already in the latest release; thank you both!!
