### ISSUE TITLE
GroupBy.all documentation example doesn't work

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6528]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`GroupBy.all()` example from this documentation page doesn't work:

https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.internals.dataframe.groupby.GroupBy.all.html

### Reproducible example

```python
df = pl.DataFrame({"a": ["one", "two", "one", "two"], "b": [1, 2, 3, 4]})

df.groupby("a", maintain_order=True).all()
```

Output:

```python
AttributeError                            Traceback (most recent call last)
Cell In[22], line 3
      1 df = pl.DataFrame({"a": ["one", "two", "one", "two"], "b": [1, 2, 3, 4]})
----> 3 df.groupby("a", maintain_order=True).all()

AttributeError: 'GroupBy' object has no attribute 'all'
```

### Expected behavior

works or documentation updated

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
The docs show the code in the master branch, not the latest release. We hope to have versioned docs in the future, but we don't have it yet.

You can use `agg_list` for the old behavior.
