### ISSUE TITLE
df.groupby(): way to iterate (group_key, data)

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6529]
### Problem description

This warning is raised when iterating `for sub_df in df.groupby("a")`:

```python
FutureWarning: Return type of groupby iteration will change in the next breaking release.
               Iteration will return tuples of (group_key, data) instead of just data.
```

But there is no way to opt-in that behavior today. and I couldn't find another way to iterate groups together with their keys - `(group_key, data)`

**Comment by ritchie46** [comment]
You just have to wait a bit. We will release soon.
