### ISSUE TITLE
Enhance elementwise missing value support

### ISSUE THREAD

**Issue by zhangyingmath** [pola-rs/polars#653]
#### Describe your feature request

So, a vague way to describe what I want is "sth should behave the same way whether as part of a structure or as a standalone element". Here is what I meant:

I like the fact that in polars, you can put python None as part of an int/str/float column, and it is represented as Null. (of course, you can also have np.nan in a float column.) Column comparison/arithmetic operation gives the correct result:

```
df = pl.DataFrame({'f': [1,2,3,None]})

In [107]: df
Out[107]: 
shape: (4, 1)
╭──────╮
│ f    │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
├╌╌╌╌╌╌┤
│ 2    │
├╌╌╌╌╌╌┤
│ 3    │
├╌╌╌╌╌╌┤
│ null │
╰──────╯

In [108]: df['f'] == df['f']
Out[108]: 
Series: '' [bool]
[
	true
	true
	true
	null
]

In [109]: df['f'] + 1
Out[109]: 
Series: 'f' [i64]
[
	2
	3
	4
	null
]
```

However, if I loop over the column, then I got python None back:
```
for i in df['f']:
     ...:     print(i)
     ...: 
1
2
3
None
```

This doesn't seem ideal, because (at least when I use pandas), sometimes I need to write my own window function that loops over a column (e.g. a customed ema function). Checking for None in the loop seems cumbersome. Are such use cases still encouraged in polars?

In my personal opinion, python None and pyarrow.NA are not good ways to represent missing values because you can't do arithmetic operations and equals itself in comparison, 

```
None == None
Out[111]: True

 import pyarrow as pa

In [114]: pa.NA == pa.NA
Out[114]: True
```

In comparison, pandas.NA is much more reasonable in my opinion (although if you put it in a pandas int column, it changes the entire column to object mode. That's a pandas specific problem.)

```
import pandas as pd

In [116]: (pd.NA == pd.NA) is pd.NA
Out[116]: True

(pd.NA + 1) is pd.NA
Out[118]: True
```

Thus I wonder, is it possible to define a new object pl.NA that behaves similar to pd.NA, and when I loop over a pl column, instead of giving python None, I got pl.NA back? 

Additional comment: 

1. If python has such a native element, and numpy chooses to adopt it, pandas would have a much easier time. 
2. In polars, it doesn't concern me what happens under the hood, i.e. it may be a bitmask or Arrow that is holding the underlying data (I am very ignorant here). As long as it appears coherent to user-level functionalities, it is good. 

Is it acceptable/doable?

**Comment by ritchie46** [comment]
I don't understand problem with checking of a `None` value to be honest. If I would create a dummy type `pl.None`, the object creation and the dynamic dispatch of the arithmetic methods would be much more expensive than checking for `None`. 

If you want to ignore the Null/None values, you can use a `Series.apply(lambda x; ..)`. An `apply` skips the null values and then you don't have to do any checks.

**Comment by ritchie46** [comment]
I am closing this as it seems inactive and missing values are properly indicated with `None`.
