### ISSUE TITLE
User Guide groupby examples are incomplete and don't run

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6530]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There are several missing pieces in the GroupBy user guide examples:
https://pola-rs.github.io/polars-book/user-guide/dsl/groupby.html

First, there is no mention that you are supposed to put this code into a `dataset.py` file:

```python
dtypes = {
    "first_name": pl.Categorical,
    "gender": pl.Categorical,
    "type": pl.Categorical,
    "state": pl.Categorical,
    "party": pl.Categorical,
}

dataset = pl.read_csv(url, dtype=dtypes).with_column(pl.col("birthday").str.strptime(pl.Date, strict=False))
```

The code itself is incomplete, the `polars` import is missing and notice how `url` is undefined and there is no mention on the page of what is the correct URL.

Then, the examples use `from .dataset import dataset` - a relative import. This only works if the code is put inside a package, most importantly, if you put the code in something like `test.py` and run `python test.py` it will not work: 

```python
ImportError: attempted relative import with no known parent package
```

### Reproducible example

```python
-
```

### Expected behavior

Documentation updated

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment]
Can you make this issue in the polars-book repo and perhaps open a PR?

**Comment by 2-5** [comment]
Sure: https://github.com/pola-rs/polars-book/issues/238
