### ISSUE TITLE
Min/Max clamp methods that take an expr

### ISSUE THREAD

**Issue by TheDan64** [pola-rs/polars#6535]
### Problem description

I would like to clamp values in a column to a max or min value. Like https://doc.rust-lang.org/std/primitive.f32.html#method.max

You can kinda do something like this with clip but it doesn't allow you to run it on whole columns: 
```rust
df.with_columns(pl.col("foo").clip_max(AnyValue::Float64(10.)).alias("foo_clipped"))
```

When what I really want is more like: 
```rust
fn max(e: Expr, other: Expr) -> Expr {
    when(e.clone().lt(other.clone())).then(other).otherwise(e)
}
```

Maybe Expr.apply would work too...

This seems a little error prone to write yourself and I ended up making a helper function to reuse it - so it seems like the sort of nice to have in polars

**Comment by ritchie46** [comment]
First clip min and then clip max?

**Comment by TheDan64** [comment]
Well I want to do one or the other, not both. Plus clip doesn't take a full column?
