### ISSUE TITLE
Series.view(): pl.Boolean support

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6536]
### Problem description

`Series.view()` throws `NotImplementedError` when used with a `pl.Boolean` dtype.

It would be nice if `Series.view()` was implemented for `pl.Boolean`, to avoid the `to_numpy()` copy, boolean arrays are used a lot in `scikit-learn` binary classification scoring functions.

**Comment by ritchie46** [comment]
You can't. Booleans are not stored in memory in a way numpy does.

**Comment by 2-5** [comment]
I see. `arrow` packs the bits together, that's an interesting choice giving the C++ experience with `std::vector<bool>` which did the same.
