### ISSUE TITLE
Program hangs during termination

### ISSUE THREAD

**Issue by Gigioliva** [pola-rs/polars#6538]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I use Polars to read several parquet files. I also put it in an async loop to use it with asyncio. More or less the code is this:
```py
def _parquet_file_to_df(file_path: str, columns: tuple[str, ...]) -> polars.DataFrame:
    return polars.read_parquet(
        file_path, columns=list(columns) if columns else None, use_pyarrow=True
    )

async def main() -> None:
    loop = asyncio.get_running_loop()
    for file in [...]:
        await loop.run_in_executor(None, func)

if __name__ == "__main__":
    asyncio.run(main())
    print("done")
```

Sometimes my program does not terminate even after printing `done`. Here some pieces of the stack trace:
 
<img width="715" alt="Screenshot 2023-01-28 alle 19 05 30" src="https://user-images.githubusercontent.com/26747867/215293413-1ec56e9d-f9d3-4e8f-869c-944ad48c4e58.png">
<img width="1753" alt="Screenshot 2023-01-28 alle 19 06 18" src="https://user-images.githubusercontent.com/26747867/215293415-a0416aee-e342-4e71-b89c-0ea3389969af.png">
<img width="1753" alt="Screenshot 2023-01-28 alle 19 07 35" src="https://user-images.githubusercontent.com/26747867/215293418-4bb6f08d-cf2a-4bea-80d4-8cd3490fd473.png">
<img width="1740" alt="Screenshot 2023-01-28 alle 19 09 52" src="https://user-images.githubusercontent.com/26747867/215293421-39d46fe4-4e26-475c-8fea-7c4ac5fb610f.png">

I am not sure the problem is 100% related to Polars. Can you help me understand the bug?

### Reproducible example

```python
def _parquet_file_to_df(file_path: str, columns: tuple[str, ...]) -> polars.DataFrame:
    return polars.read_parquet(
        file_path, columns=list(columns) if columns else None, use_pyarrow=True
    )

async def main() -> None:
    loop = asyncio.get_running_loop()
    for file in [...]:
        await loop.run_in_executor(None, func)

if __name__ == "__main__":
    asyncio.run(main())
    print("done")
```

### Expected behavior

The program terminates execution

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by ritchie46** [comment]
Does your event loop run in threads or process pools?

**Comment by Gigioliva** [comment]
> Does your event loop run in threads or process pools?

@ritchie46  the default one that is a ThreadPool

**Comment by Gigioliva** [comment]
@ritchie46 it seems that my issue is [this](https://github.com/python/cpython/issues/91414). So not related to Polars 🙏🏼
