### ISSUE TITLE
Polars 0.16.0 release

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6540]
Any things to consider? I was wondering if releasing tonight was feasible. Any things we should wait for?

@stinodego @alexander-beedie @ghuls @MarcoGorelli ?

**Comment by alexander-beedie** [comment]
> Any things we should wait for?

Would be nice to get the select/with_columns "kwargs + struct" behaviour in, but aside from that nothing else blocking/pending from me 👍

In the meantime I've got a 12½ hour (!) flight to fill with a bit of debugging/dev - if there's wifi I'll get it done, and if not then expect it first-thing tomorrow :)

**Comment by stinodego** [comment]
I think I got most of the stuff I wanted to break out of my system 😄 I don't think there's anything else we really need to get in right now.

**Comment by alexander-beedie** [comment]
_Brutally_ slow connectivity up here (< 2kb/s if it even connects), but I was able to commit the `select` update for kwargs, so that is good to go for `0.16.0` after all (see #6497).

**Comment by ritchie46** [comment]
> _Brutally_ slow connectivity up here (< 2kb/s if it even connects), but I was able to commit the `select` update for kwargs, so that is good to go for `0.16.0` after all (#6497).

We should keep a records file. ✈️😁

**Comment by alexander-beedie** [comment]
Lol... we could have all kinds of amusing records stashed somewhere; I will submit claims for "fastest land-speed commit" (207km/h, on the bullet train back to Tokyo), and "highest-altitude commit" (according to the in-flight info screen, we are currently at 10,972m) 🤣

**Comment by jjerphan** [comment]
Polars developers breaking all records. :tada: 🫳 :microphone:

**Comment by MarcoGorelli** [comment]
😄 cheers for the ping!

No objections, looks like releases are quite frequent anyway, and it'd be good to see the effects of #6487

**Comment by jjerphan** [comment]
Should https://github.com/pola-rs/polars/pull/6531 be considered for inclusion? Or should it be considered for 0.17.0?

**Comment by stinodego** [comment]
That's a build update - it won't be breaking for anyone. So we can include it in 0.16.x whenever it's ready.

**Comment by ritchie46** [comment]
> Should #6531 be considered for inclusion? Or should it be considered for 0.17.0?

This doesn't really matter. It should have no end-user impact.

**Comment by cmdlineluser** [comment]
Just trying out #6497 (very nice!) and noticed some extra output:

```
>>> df.with_columns(x3 = pl.col("x1") + pl.col("x2"))
[/Users/user/git/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs:456] 
   eval_binary_same_type!(left_aexpr, +, right_aexpr) = None
shape: (3, 4)
┌─────┬─────┬─────────────┬─────┐
│ x1  | x2  | pct_change  | x3  │
│ --- | --- | ---         | --- │
│ i64 | i64 | struct[2]   | i64 │
╞═════╪═════╪═════════════╪═════╡
│ 1   | 1   | {null,null} | 2   │
│ 2   | 2   | {1.0,1.0}   | 4   │
│ 6   | 3   | {2.0,0.5}   | 9   │
└─────┴─────┴─────────────┴─────┘
```

I guess it's from `dbg!`

https://github.com/pola-rs/polars/blob/master/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs#L456

**Comment by ritchie46** [comment]
Auch. :disappointed:
