### ISSUE TITLE
pl.cut returns right-closed intervals (a, b], add support for left-closed ones [a, b)

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6547]
### Problem description

Currently `pl.cut` only support returning right closed intervals (a, b], just like the `pandas.cut` default.

However pandas allows you to call `pd.cut(right=False)` to return left closed intervals [a, b).

It would be nice if polars added support for `pl.cut(right=False)` or something equivalent.

**Comment by ritchie46** [comment]
Cut is completely implemented in python. Can you  make a PR?

**Comment by 2-5** [comment]
I looked at the `cut` implementation and it uses `join_asof`. From what I see `join_asof` doesn't support NOT matching the right boundary.

`pandas.merge_asof` has a `allow_exact_matches` to control if the boundary is included or not:

>allow_exact_matches : boolean, default True
> - If True, allow matching with the same ‘on’ value (i.e. less-than-or-equal-to / greater-than-or-equal-to)
> - If False, don’t match the same ‘on’ value (i.e., strictly less-than / strictly greater-than)

`cut` calls `join_asof(strategy="forward")`. Maybe it's possible to use `strategy="backward"` to implement left-closed intervals, but I think that would shift the labels.

BTW, `pl.cut` bins the start/end differently than `pd.cut`, you can't just replace one with the other. This should be mentioned in the docs, through it will be obvious if you port code and check the results. Hopefully this difference is not accidental and it is by design, personally I can't tell which version is better/more-intuitive.

**Comment by stinodego** [comment]
There is a `closed_left` toggle now, so I believe this issue can be closed.
