### ISSUE TITLE
Add arrow struct type support

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#655]
This is mostly a mechanical copying of other trait implementations. 

* [ ] Add struct datatype
* [ ] Make `ChunkedArray<StructType>` an iterator
* [ ] Implement `dyn SeriesTrait` and required subtraits

**Comment by Hoeze** [comment]
That would be awesome!

**Comment by Greatness7** [comment]
I need this too.

Is there an alternative with the current api that allows one to have something like nested dataframes?

**Comment by thda** [comment]
Just to highlight a use case, clickhouse uses arrow structs to represent it's internal tuple format ([docs](https://clickhouse.com/docs/en/interfaces/formats/#data-format-arrow))

**Comment by phillyphil91** [comment]
Is this still needed/wanted? I would like to take a look at this, but would probably need some help/guidance as this would be my first issue.

**Comment by ritchie46** [comment]
Oh, we already have this. :)
