### ISSUE TITLE
“Where” as “filter” alias

### ISSUE THREAD

**Issue by shaharluftig** [pola-rs/polars#6554]
### Problem description

Hey guys, as user of polars, I suggest adding “where” as alias to “filter”.
This behavior is common in other libraries and frameworks, such as [Pyspark](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.where.html) 

For example:
df.where(pl.col(“name”)==“alex”))
Will be same as 
df.filter(pl.col(“name”)==“alex”))

The reason I believe this feature is necessary, is because it is more natural to use where instead of filter when coming from sql background.

**Comment by ritchie46** [comment]
`where` is a keyword in Rust. I want the polars libraries to have the same DSL.

**Comment by alexander-beedie** [comment]
FYI: `where` also behaves quite differently in pandas (it's more of a conditional `replace`) - to alias it as `filter` would also be confusing for those users. In the end it's hard to keep everyone coming from every library/paradigm happy, but thanks for the request! ;)
