### ISSUE TITLE
groupby sorted optimization does not work

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6556]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

We have the test below in the code. However, the assert statement was missing. After adding the assert, it now fails. So the sorted optimization must not be working correctly.

### Reproducible example

```python
    df = pl.DataFrame({"a": np.random.randint(0, 5, 20)})

    # the sorted optimization should not randomize the
    # groups, so this is tests that we hit the sorted optimization
    for reverse in [True, False]:
        sorted_implicit = (
            df.with_columns(pl.col("a").sort(reverse=reverse))
            .groupby("a")
            .agg(pl.count())
        )
        sorted_explicit = df.groupby("a").agg(pl.count()).sort("a", reverse=reverse)
        assert_frame_equal(sorted_explicit, sorted_implicit)
```

### Expected behavior

I expect the test to pass.

### Installed versions

master branch

**Comment by ritchie46** [comment]
We should set `"POLARS_NO_STREAMING_GROUPBY=1"` for this test.

**Comment by stinodego** [comment]
Indeed that fixes it - will incorporate it in my mega test-PR. Closing this now.
