### ISSUE TITLE
Deprecate tz_localize, let cast_timezone work on naive

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6561]
~the two behaviours I'm suggesting to deprecate are:~
    ~calling with_time_zone on tz-naive;~
    ~calling with_time_zone(None)~

**EDIT**: this issue was originally about making `with_time_zone` stricter The scope then evolved into `cast_time_zone` and `tz_localize`. To keep the scope down, I've changed the scope of this suggestion to be only about `cast_time_zone` and `tz_localize`. I'll make a separate issue about `with_time_zone`

**EDIT 2** I've broken the `with_time_zone` part of the suggestion off into https://github.com/pola-rs/polars/issues/6658

**Comment by MarcoGorelli** [comment]
Right, having spent some more time on this, I think it could go further:
- `cast_time_zone` would work on `tz-naive`, and do the same thing `tz_localize` currently does;
- `tz_localize` would be deprecated (following @braaannigan's suggestion from a few weeks ago)
- `with_time_zone` would only be used to convert from one tz-aware to another tz-aware

@ritchie46 @alexander-beedie @stinodego sorry for the ping, just wanted to check if you'd be on board with this

**Comment by FObersteiner** [comment]
uh I think @braaannigan in #6338 wanted to deprecate cast_time_zone, in favour of tz_localize ;-)

**Comment by MarcoGorelli** [comment]
Update: I've opened a PR to let `cast_time_zone` work on tz-naive and thus deprecate `tz_localize` https://github.com/pola-rs/polars/pull/6649

---

Regarding making `with_time_zone` stricter: I tried this, and came across

https://github.com/pola-rs/polars/blob/9a7fb6c2bc0555b693a52ff543e9e81e17a73b7c/polars/polars-time/src/upsample.rs#L154-L163

where letting `with_time_zone` accept `None` is convenient, and if it didn't it would require a refactor. Not saying it can't be done, but it does suggest it might be similarly inconvenient for users, so it's probably not worth it.

---

Letting `cast_time_zone` work on tz-naive and deprecating `tz_localize`, on the other hand, does feel quite natural. And users would just need to switch `tz_localize` with `cast_time_zone` and it would do the same thing, so it wouldn't be too breaking for them. So I went ahead with the PR - no hard feelings if you disagree with this suggestion of course!

**Comment by FObersteiner** [comment]
> letting with_time_zone accept None

what would be the result? does it revert to the internal representation / naive "UTC-like" ?

**Comment by MarcoGorelli** [comment]
that's right - it would keep doing what it currently does, there would be no change to `with_time_zone`

**Comment by FObersteiner** [comment]
@MarcoGorelli I really like the new function names as in **0.16.3** ! I'm still in favour of deprecating `tz_localize`.
