### ISSUE TITLE
Map/Apply lose track of struct field names after passed to custom function.

### ISSUE THREAD

**Issue by gfmartins** [pola-rs/polars#6567]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

expr.MAP and expr.APPLY lose track of struct "column"/field names after being passed to an custom function and "unnested" / or direct select into the struct fields after . Regardless if the function **returns exactly the same structure of data**. 

from the apply documentation:
**return_dtype :   Dtype of the output Series. If not set, polars will assume that the dtype remains unchanged.**

So I'm guessing that it's an bug?

it works if we manually pass the dtype.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "col_1": ["x", "y", "z"],
        "col_2": ["a", "b", "d"],
    }
).lazy()

def f1(data):
    return data

dtype = None #pl.Struct([pl.Field("col_1", pl.Utf8), pl.Field("col_2", pl.Utf8)])

df = df.select([
  pl.struct(["col_1","col_2"]).map(f1, return_dtype= dtype).alias("xx")
  #pl.struct(["col_1","col_2"]).apply(f1, return_dtype= dtype).alias("xx")
])

#df = df.select([pl.col("xx").struct.field("col_1")])

df = df.unnest("xx")
print(df.columns)

print(df.collect())
```

### Expected behavior

print column names (col_1, col_2) after "unnest" 

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2

```

</details>

**Comment by ritchie46** [comment]
The documentation is wrong. A user must provide an ouput schema in polars-lazy, otherwise it is considered a bug in your query.
