### ISSUE TITLE
Implement is_not_in

### ISSUE THREAD

**Issue by M-Salti** [pola-rs/polars#6574]
### Problem description

Currently to achieve `is_not_in` behavior we have to use `is_in` followed by an `is_not`, which is a bit clunky.
I think it would be nicer if we had a dedicated method just like `is_not_null` and `is_not_nan`, because it's a common use-case.

**Comment by ritchie46** [comment]
Put a negate `~` in front if the expression.

**Comment by M-Salti** [comment]
Oh, didn't know about this. Thanks!

I'm okay with this solution but I'll keep the issue open for a while in case someone else wants this feature or if you want to implement it anyways.

**Comment by ritchie46** [comment]
Nope, I don't want to implement this :wink: . This would double the boolean API surface. Booleans should be negated if the outcome should be inverted.
