### ISSUE TITLE
Portability to other scripting languages?

### ISSUE THREAD

**Issue by tavurth** [pola-rs/polars#6575]
### Problem description

Wow I just found this, nice work guys 👍

So I do most of my data visualisation work in Godot & GDScript because I love their UI builder.

What sort of workload do you estimate currently to move towards a scripting language-agnostic approach?

Alternately, what sort of complexity do you estimate would be required to write a GDScript frontend for your cool library?

The way I see it you have what will probably replace Pandas, and you have Godot sitting there waiting as a visualiser (Godot 4.x & GDExtension easy rust code). Why not allow combination and set a possible path for the future of data science.

**Comment by MarcoGorelli** [comment]
thanks @tavurth for the request - closing as out-of-scope
