### ISSUE TITLE
Groupby .list aggregation broken - returns doubly nested lists

### ISSUE THREAD

**Issue by jaychia** [pola-rs/polars#6584]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

List aggregations in the latest version of polars is returning a doubly-nested list instead of a singly-nested list.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3, 3], "b": ["a", "b", "c", "d"]})

df.groupby("a").agg(pl.list("b").alias("list_b"))
```

### Expected behavior

```
shape: (3, 2)
┌─────┬────────────┐
│ a   ┆ list_b     │
│ --- ┆ ---        │
│ i64 ┆ list[str]  │
╞═════╪════════════╡
│ 1   ┆ ["a"]      │
│ 2   ┆ ["b"]      │
│ 3   ┆ ["c", "d"] │
└─────┴────────────┘
```

But received instead:

```
shape: (3, 2)
┌─────┬─────────────────┐
│ a   ┆ list_b          │
│ --- ┆ ---             │
│ i64 ┆ list[list[str]] │
╞═════╪═════════════════╡
│ 1   ┆ [["a"]]         │
│ 3   ┆ [["c", "d"]]    │
│ 2   ┆ [["b"]]         │
└─────┴─────────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.4 (main, Jan 11 2023, 00:15:55) [Clang 13.0.0 (clang-1300.0.27.3)]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by jaychia** [comment]
Ah - just read https://github.com/pola-rs/polars/pull/6487 seems like this was intentional

**Comment by ritchie46** [comment]
You hust need to write `col()` to get the old behavior. The groupby itself already turns them in a list of groups.
