### ISSUE TITLE
groupby_dynamic Had to reallocate groups, missed an optimization opportunity.

### ISSUE THREAD

**Issue by swpease** [pola-rs/polars#6586]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I got the message:
> Had to reallocate groups, missed an optimization opportunity. Please open an issue.

So, I am opening an issue.

The code I called was:
```
(
df.groupby_dynamic(
    "MainEventStartDate", 
    every="1d", 
    period="2y",
    closed="right",
    by="PlayerID"
    )
.agg(pl.sum("Frames"))
)
```
On a dataframe that looks like this:
```
df = pl.DataFrame({"PlayerID": [1, 1], 
                   "MainEventStartDate": [
                        "2015-06-29", 
                        "2015-09-14", 
                    ], 
                   "Frames":[0, 11]}).with_column(pl.col("MainEventStartDate").str.strptime(pl.Date))
```

### Reproducible example

I don't know. The above `df = [...]` doesn't reproduce the message. I checked for equality with a dataframe that *does* produce the message and got back `True`. The dataframe that produces the message is the result of some prior processing (joins, selects, etc.). I'm not sure how to do some sort of deep copy at prior points in the process to narrow down which of the prior processing steps are to blame.

### Expected behavior

I don't know.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: macOS-12.5-arm64-arm-64bit
Python: 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by ritchie46** [comment]
Are you able to make an MWE? This messages was intended to find cases where we can optimize. You are the lucky finder^^

**Comment by cmdlineluser** [comment]
I also ran into this:
```
df = pl.DataFrame({
   "class": [2, 1, 1, 1],
   "day": [1, 1, 2, 2],
   "id": [1, 2, 3, 2],
   "value": [5, 6, 7, 8]
})
```
```
(df.sort("class")
   .groupby_dynamic(by="class", index_column="day", every="1i")
   .agg(pl.exclude("day")))
```
```
Had to reallocate groups, missed an optimization opportunity. Please open an issue.
shape: (3, 4)
┌───────┬─────┬───────────┬───────────┐
│ class | day | id        | value     │
│ ---   | --- | ---       | ---       │
│ i64   | i64 | list[i64] | list[i64] │
╞═══════╪═════╪═══════════╪═══════════╡
│ 1     | 1   | [2]       | [6]       │
│ 1     | 2   | [3, 2]    | [7, 8]    │
│ 2     | 1   | [1]       | [5]       │
└───────┴─────┴───────────┴───────────┘
```

**Comment by ritchie46** [comment]
Thanks @cmdlineluser. Found it.
