### ISSUE TITLE
comparison operators on boolean series are NotImplemented

### ISSUE THREAD

**Issue by mingi3314** [pola-rs/polars#6587]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It is not able to compare a boolean Series and a scalar value. 

For example, `pl.Series(values=[True, False]).__eq__(True)` returns a NotImplemented, whereas `pl.Series(values=[True, False]).__eq__([True])` returns a boolean series.

I think we need to broadcast a scalar value to the vector.

### Reproducible example

```python
import polars as pl

s = pl.Series("boolean_series", [True, True, True, False])
print(s == True)
```

### Expected
```
shape: (4,)
Series: 'boolean_series' [bool]
[
	true
	true
	true
	false
]
```

### Actual
```
False
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.9.12 (main, Apr 26 2022, 13:27:20) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for raising an issue about this edge-case ;)
