### ISSUE TITLE
polars 0.16.1: using `to_dicts` datetime with timezone change type to pandas `Timestamp` instead of `datetime`

### ISSUE THREAD

**Issue by gam-phon** [pola-rs/polars#6591]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

in polars 0.15.18 the type of datetime after using `to_dicts` always datetime. but in 1.16.1 sometimes it is using the pandas Timestamp strange!

### Reproducible example

```python
from datetime import datetime

import polars as pl

df = pl.DataFrame([{"time": datetime.fromisoformat("2022-04-21T10:18:12-05:00")}])

# No Issues
print(df.to_dicts()[0])
# 0.16.1 -> {'time': datetime.datetime(2022, 4, 21, 10, 18, 12)}
# 0.15.18 -> {'time': datetime.datetime(2022, 4, 21, 10, 18, 12)}
print(type(df.to_dicts()[0]["time"]))
# 0.16.1 -> <class 'datetime.datetime'>
# 0.15.18 -> <class 'datetime.datetime'>

df = (
    df.lazy()
    .select(pl.col("time").cast(pl.Datetime(time_unit="ns", time_zone="EST")))
    .collect()
)
# Here is the issue
print(df.to_dicts()[0])
# 0.16.1 -> {'time': Timestamp('2022-04-21 05:18:12-0500', tz='EST')}
# 0.15.18 -> {'time': datetime.datetime(2022, 4, 21, 5, 18, 12, tzinfo=zoneinfo.ZoneInfo(key='EST'))}
print(type(df.to_dicts()[0]["time"]))
# 0.16.1 -> <class 'pandas._libs.tslibs.timestamps.Timestamp'>
# 0.15.18 -> <class 'datetime.datetime'>
```

### Expected behavior

Always use python datetime

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>

---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
That's strange. Could someone get a bisect on this one?

**Comment by FObersteiner** [comment]
two remarks, IMHO
- "2022-04-21T10:18:12-05:00" should give aware datetime, with -5 hours UTC offset
- time_zone="EST" should fail, EST describes a UTC offset and just works for backwards compatibility of [IANA tz names](https://github.com/eggert/tz/blob/d0cbdfa640c6f283c0793db94be04d856bb7264f/northamerica#L189). I think in pandas this at least raises a warning.

**Comment by alexander-beedie** [comment]
Argh... found it - it's the (optional) pyarrow-based speedup/optimisation. I can fix this.

**Comment by gam-phon** [comment]
using `.select(pl.col("time").dt.with_time_zone(tz="EST")).collect()` instead of `.select(pl.col("time").cast(pl.Datetime(time_unit="ns", time_zone="EST")))` does not cause the issue

**Comment by gam-phon** [comment]
Also, which syntax is the best option to transfer between timezone? are they all the same?
Timezone is an important topic maybe we could add a page in the user guide under time-series `dealing with timezone`

**Comment by alexander-beedie** [comment]
FYI: the issue is not actually connected to timezones, it's specifically related to temporal dtypes with `ns` precision (only).
