### ISSUE TITLE
append mode in csv writer

### ISSUE THREAD

**Issue by alisterburt** [pola-rs/polars#6597]
### Problem description

Thanks for the amazing work on polars. It would be great if I could use the polars csv writer to append to an existing file. From [the docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_csv.html), this doesn't seem to be possible. This is supported in pandas with a [`mode` keyword argument](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas-dataframe-to-csv).

I'm aware this is niche 🙂 I'm forced to write a domain specific file format containing multiple (potentially very large) tables which are basically tsv with a specific header structure. The pandas csv writer is incredibly slow under certain conditions and this issue is the only thing stopping me from switching over to polars

**Comment by ritchie46** [comment]
We can write to python file handles. Did you try something like this?

```python
with open("my_file", mode="a"`) as f:
   df.write_csv(f)
```
