### ISSUE TITLE
Multiple when/then statements in one call

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#660]
Would it be possible to extend `pl.when().then().otherwise()` to allow multiple `when().then()` statements?

Something like this:
```python
import polars as pl
from polars import col

df = pl.DataFrame({'x': ['a', 'a', 'b', 'b'],
                   'y': [1, 2, 3, 4]})

# proposed syntax
(
    df
    .with_column(
        pl.when((col('x') == 'a') & (col('y') == 1)).then(1)
        .when(col('x') == 'a').then(2)
        .when(col('x') == 'b').then(3)
        .otherwise(4)
    )
)

# current syntax
(
    df
    .with_column(
        pl.when((col('x') == 'a') & (col('y') == 1)).then(1)
        .otherwise(
            pl.when(col('x') == 'a').then(2)
            .otherwise(
                pl.when(col('x') == 'b').then(3)
                .otherwise(4)
            )
        )
    )
)
```

**Comment by ritchie46** [comment]
Hmm.. The current syntax maps to the nesting that actually happens in the query engine. I think we should see if we can write some Python that translates the first into the second.

**Comment by silvewheat** [comment]
This new syntax is very helpful!
Maybe it's worth adding it to the documentation to let more people know.

**Comment by ritchie46** [comment]
It is.

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.when.html#polars.when
