### ISSUE TITLE
Limit the size of Exception strings

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#6604]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When running longer polars scripts in lazy mode, it appears that the exception strings can grow to unlimited size. 

For example, my jupyter notebook grew to 200MB in size after one exception and immediately crashed the notebook server. 

This would obviously also cause issues when running anything with logging, since log files could grow infinitely large.

Looking at the length of the tracebacks in the notebook reveals that the offending string has around 50M characters (see below). I looked at the last 1000 characters of the string to find the source of the error, and that actually gave me all the information I needed, so maybe that could be a reasonable cutoff.

```python
for cell in nb['cells']:
    if cell['cell_type']=='code':
        if 'outputs' in cell.keys():
            for output in cell['outputs']:
                if 'traceback' in output.keys():
                    for row in output['traceback']:
                        print(len(row))

86
86
1568
1168
860
811
49938358
```
### Reproducible example
```py3
df1 = pl.DataFrame().lazy().select("a").select("a").select("a").select('a')
df1.collect()
```
Output:
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Input In [23], in <cell line: 3>()
      1 df1 = pl.DataFrame().lazy().select("a").select("a").select("a").select('a')
----> 3 df1.collect()

File ~/.local/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py:1143, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1132     common_subplan_elimination = False
   1134 ldf = self._ldf.optimization_toggle(
   1135     type_coercion,
   1136     predicate_pushdown,
   (...)
   1141     streaming,
   1142 )
-> 1143 return pli.wrap_df(ldf.collect())

NotFoundError: a

> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
'
This operation could not be added to the plan.

> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
'
This operation could not be added to the plan.

> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\\n\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\"NotFound(Owned(\\\\\\\"a\\\\\\\\n\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\"))\\\" }, poisoned: false, .. })\\n  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
'
This operation could not be added to the plan.

> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\\n\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\"NotFound(Owned(\\\\\\\"a\\\\\\\\n\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\"))\\\" }, poisoned: false, .. })\\n  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\\n\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\"NotFound(Owned(\\\\\\\"a\\\\\\\\n\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\\n\\\\\\\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\\\\\\\\\\\\\"NotFound(Owned(\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"a\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n'\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\nThis operation could not be added to the plan.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"))\\\\\\\\\\\\\\\" }, poisoned: false, .. })\\\\\\\\n  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\"))\\\" }, poisoned: false, .. })\\nErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\"NotFound(Owned(\\\\\\\"a\\\\\\\\n\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\"))\\\" }, poisoned: false, .. })\\n  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\\n\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\"NotFound(Owned(\\\\\\\"a\\\\\\\\n\\\\\\\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\"\\\\\\\\n'\\\\\\\\nThis operation could not be added to the plan.\\\\\\\"))\\\" }, poisoned: false, .. })\\n  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: "NotFound(Owned(\"a\\n\\n> Error originated just after operation: '  DF []; PROJECT */0 COLUMNS; SELECTION: \\\"None\\\"\\n'\\nThis operation could not be added to the plan.\"))" }, poisoned: false, .. })
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
'
This operation could not be added to the plan.
```

### Expected behavior

Exception strings should have a maximum length.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by ritchie46** [comment]
Any idea where this originated?

**Comment by DrMaphuse** [comment]
There was a join / select with a missing column somewhere in the middle of the script and it appears that this caused a chain of subsequent errors to pile up in the traceback. Most of it looks like this:

> This operation could not be added to the plan.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n> Error originated just after operation: 'ErrorStateSync(Mutex { data: AlreadyEncountered { prev_err_msg: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"NotFound(Owned(\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"Column_A\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n> Error originated just after operation: '  PARQUET SCAN /mnt/Input/2022-12-31.parquet\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  PROJECT */2 COLUMNS\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n

It would seem that part of the problem is the way that these recurring exception strings are escaped over and over.

**Comment by stinodego** [comment]
This has been fixed.
