### ISSUE TITLE
Allow single expressions in `.with_columns()`

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#661]
It seems like `.with_columns()` is the only method that requires a list of expressions. `.agg()` and `.sort()` both allow single expressions.

```python
df.with_columns(col('a') * 2))
```

This can currently be accomplished with `.with_column()`, but it seems like it would simplify the API if `.with_columns()` allowed this as well.

**Comment by ritchie46** [comment]
Sure. Could you make a PR with that behavior?

**Comment by markfairbanks** [comment]
I don't think I can unfortunately. Python isn't my strong suit - I typically code and develop packages in R. My python coding skills don't extend much past using packages like pandas/polars/numpy.

**Comment by ritchie46** [comment]
No worries. I'll pick it up!
