### ISSUE TITLE
create expression for factorial

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#6620]
### Problem description

Inspired by this question https://stackoverflow.com/questions/75303038/how-to-write-poisson-cdf-as-python-polars-expression
With respect to that question, I was thinking it'd be relatively easy to manually calc Poisson cdf in expressions until I realized there isn't a factorial method.

In the process of trying to come up with a work around for factorial I tried to do

`df.with_columns(pl.arange(pl.lit(1), pl.col('count')+1).arr.product())` and got 

`AttributeError: 'ExprListNameSpace' object has no attribute 'product'`

so I guess product isn't implemented for arr and had to do this:

`df.with_columns(pl.arange(pl.lit(1), pl.col('count')+1).arr.eval(pl.element().product()).arr.first().alias('factorial'))`

So please also, add product to ExprListNameSpace.

**Comment by abalkin** [comment]
For the purposes of computing Poisson distribution, it is best to do all calculations with float dtype:

```python
>>> import polars as pl
>>> from scipy.special import gamma
>>> df = pl.select(pl.arange(0, 10, dtype=float).alias('n'))
>>> df.with_columns(fact=gamma(pl.col('n') + 1))
shape: (10, 2)
┌─────┬──────────┐
│ n   ┆ fact     │
│ --- ┆ ---      │
│ f64 ┆ f64      │
╞═════╪══════════╡
│ 0.0 ┆ 1.0      │
│ 1.0 ┆ 1.0      │
│ 2.0 ┆ 2.0      │
│ 3.0 ┆ 6.0      │
│ ... ┆ ...      │
│ 6.0 ┆ 720.0    │
│ 7.0 ┆ 5040.0   │
│ 8.0 ┆ 40320.0  │
│ 9.0 ┆ 362880.0 │
└─────┴──────────┘
````

**Comment by deanm0000** [comment]
@ [mkleinbort-ic](https://github.com/mkleinbort-ic)

Thanks.

I ended up doing this:
`@pl.api.register_expr_namespace('zz')
class Factorial:
    def __init__(self, expr: pl.Expr):
        self._expr = expr
    def fact(self) -> pl.Expr:
        return(
            pl.when(self._expr==0)
                .then(1)
                .otherwise(
                    pl.arange(pl.lit(1), self._expr+1).arr.eval(
                        pl.element().product()).arr.first()).alias('factorial'))`

so then we can just do

`df.with_columns(pl.col('n').zz.fact())`

@abalkin I'm not sure if that's true since Poisson is for discrete finite observations aka integers.  That being said, thanks to your comment I did find that scipy.special.factorial is a numpy ufunc which is good to go.

**Comment by deanm0000** [comment]
Of course that begs the question of how to use the `scipy.special.pdtr` ufunc since it takes 2 positional arguments.  I found [this](https://stackoverflow.com/questions/71731348/how-can-i-call-a-numpy-ufunc-with-two-positional-arguments-in-polars) but I'm not sure if it's correct in using apply for a ufunc since [ufuncs are fully supported](https://pola-rs.github.io/polars-book/user-guide/dsl/numpy.html) and, if I'm not mistaken, by using apply it no longer gets the benefit of being in an expression.

**Comment by abalkin** [comment]
@deanm0000 - I posted [a simple solution](https://stackoverflow.com/a/75311287/5403209) for computing Poisson CDF with a Polars expression.

> Poisson is for discrete finite observations aka integers

That's right, but the CDF returns floating point values.  For larger (> 10) values of k, integer calculations will be wasteful and for k > 20 will overflow.

**Comment by abalkin** [comment]
> `scipy.special.factorial` is a numpy ufunc which is good to go.

Thanks, @deanm0000 - I did not know about it!  Note that `scipy.special.factorial` will only work on Polars expressions with the default value of the `exact` argument and in this case, according to the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.factorial.html), it uses approximation by $\Gamma$:

> With `exact=False` the factorial is approximated using the gamma
> 
> ```math
>  n! = \Gamma(n+1)
> ```
