### ISSUE TITLE
Typing: pl.Series().min(), max(), probably others can also return None

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6623]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Some `Series` methods can return None, but this is not declared in the return type:

```python
class Series:
    def min(self) -> int | float | date | datetime | timedelta | str:
```

### Reproducible example

```python
import polars as pl

s = pl.Series([None, None])
print(s, s.dtype)
print(s.min())
print(s.max())
```

### Expected behavior

`None` declared in method return type

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by MatveyF** [comment]
Experimented with other `Series` methods and found that the same behaviour can be observed when using `min()`, `max()`, `mean()`, `median()`, `sum()`, `product()`, and `quantile()`.

**Comment by ritchie46** [comment]
Could you make a PR updating the type hints?

**Comment by MatveyF** [comment]
Ok I'll do it. @ritchie46

**Comment by stinodego** [comment]
When should these methods return `None`? This seems a bit counterintuitive to me:

```python
pl.Series([]).sum()  # Returns 0.0
pl.Series([None]).sum()  # Returns None

```
