### ISSUE TITLE
Polars is stuck on version 0.15.14 on conda-forge channel.

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#6624]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I think most of the updates are done "automatically" by conda-forge bots, but I just saw Polars feedstock and I don't get why it wasn't able to update to the recent versions. 

I'm not very familiar with solving conda-forge recipes but I know a few people that are if help is needed there.

### Reproducible example

```python
-
```

### Expected behavior

-

### Installed versions

<details>

```
-
```

</details>

**Comment by ritchie46** [comment]
Can you open this issue on conda forge? I am not family with conda-forge myself. Though I am added to the recipe, I don't know how to fix it.

**Comment by arturdaraujo** [comment]
@giswqs sorry for pin you like that but maybe you could look what went wrong on polars feedstock?

**Comment by giswqs** [comment]
Rerun the failed CI to see if it can pass.

**Comment by arturdaraujo** [comment]
Thanks 🙏
