### ISSUE TITLE
Expr.is_between() not implemented for str

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6625]
### Problem description

`Expr.is_between()` is not implemented for `str`, only `<` and `>`:

```python
import polars as pl

df = pl.DataFrame({
    "text": ["a", "b", "c", "d"],
})
print(df)

df2 = df.filter(
    pl.col("text") < "c",
)
print(df2)

df3 = df.filter(
    pl.col("text").is_between("b", "d"),
)
print(df3)
```

Output:

```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    df3 = df.filter(
  File ".venv\lib\site-packages\polars\internals\dataframe\frame.py", line 2702, in filter
    self.lazy()
  File ".venv\lib\site-packages\polars\internals\lazyframe\frame.py", line 1143, in collect
    return pli.wrap_df(ldf.collect())
exceptions.NotFoundError: b
```

**Comment by stinodego** [comment]
It is implemented, but you should write this like:

```python
df3 = df.filter(
    pl.col("text").is_between(pl.lit("b"), pl.lit("d")),
)
```

It interprets `"b"` as `pl.col("b")`. That happens in many places throughout Polars for ease of use, e.g. `df.select(["a", "b"])`.

So this is by design, although it may be poor design. It can definitely be confusing.

**Comment by 2-5** [comment]
Interesting, sounds like a useful feature.

Maybe an example could be added in the docs:

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.is_between.html

The error message could be improved, by mentioning that a column was not found, something like this:

`exceptions.NotFoundError: b` -> `exceptions.ColumnNotFoundError: b`

Or better `exceptions.NotFoundError: No "b" column. Maybe you mean pl.lit("b")?`

**Comment by alexander-beedie** [comment]
> Maybe an example could be added in the docs:

[Done](https://github.com/pola-rs/polars/pull/6627); will also (separately) see if we can slightly enrich the `NotFoundError` to better-indicate _what_ has not been found 👍

**Comment by stinodego** [comment]
> Maybe an example could be added in the docs:

While this is nice, it's a broader thing that affects many Polars functions. Every function should clearly state how it handles string inputs. We should do that, but it's quite cumbersome 😞 

Better error messaging is really the best solution here.

**Comment by alexander-beedie** [comment]
@2-5: FYI ,have just done a sweep through the `NotFound` exception classes, improving context as suggested... (https://github.com/pola-rs/polars/pull/6670)
