### ISSUE TITLE
slower DataFrame creation from long numpy array than pandas

### ISSUE THREAD

**Issue by daviddoji** [pola-rs/polars#6632]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I might be doing something silly while creating a DataFrame from a very long (1 thousand million rows) numpy ndarray because I'm getting much slower times by creating DataFrames using Pandas than using Polars.

![image](https://user-images.githubusercontent.com/4411314/216324462-084762b7-6876-4b2c-be75-ce66d56081fd.png)

### Reproducible example

```python
import pandas as pd
import polars as pl

raw_hdf_keys = ["X", "Y", "t", "ADC"]
outp = np.random.randint(70000, size=(4, 1_000_000_000), dtype=np.uint32)  # beware of memory
pasha_df = pd.DataFrame(outp.T, columns=raw_hdf_keys)
pasha_pdf = pl.DataFrame(outp, schema=raw_hdf_keys, orient="col")
polars_df = pl.DataFrame(pasha_df)
```

### Expected behavior

Surprisingly for me, creating a DataFrame in Pandas and transforming it later to Polars, is way faster than creating the DataFrame directly in Polars (see screnshot above)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.10
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.3
fsspec: 2021.07.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.2
```

</details>

**Comment by ghuls** [comment]
Pandas uses the numpy array directly, while Polars will copy the array, column by column.

You can time `outp.copy()` to see how long it takes to make a copy with just numpy.

```python
# Pandas uses original numpy array.
pasha_df = pd.DataFrame(outp.T, columns=raw_hdf_keys)

# Polars copies numpy arrays
pasha_pdf = pl.DataFrame(outp, schema=raw_hdf_keys, orient="col")

# Polars uses original pandas data without copy, which is the original numpy array data.
polars_df = pl.DataFrame(pasha_df)
```

@ritchie46 It seems like Polars dataframes from Pandas input are not always immutable:
```python
In [90]: x = np.array([[1, 2], [3, 4], [5, 6]])

In [91]: pandas_df = pd.DataFrame(x.T, columns=["X", "Y", "Z"])

In [92]: polars_from_numpy_df = pl.DataFrame(x, schema=["X", "Y", "Z"])

In [93]: polars_from_pandas_df = pl.DataFrame(pandas_df)

In [94]: x
Out[94]: 
array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]: pandas_df
Out[95]: 
   X  Y  Z
0  1  3  5
1  2  4  6

In [96]: polars_from_numpy_df
Out[96]: 
shape: (2, 3)
┌─────┬─────┬─────┐
│ X   ┆ Y   ┆ Z   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   │
│ 2   ┆ 4   ┆ 6   │
└─────┴─────┴─────┘

In [97]: polars_from_pandas_df
Out[97]: 
shape: (2, 3)
┌─────┬─────┬─────┐
│ X   ┆ Y   ┆ Z   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   │
│ 2   ┆ 4   ┆ 6   │
└─────┴─────┴─────┘

# Modifying numpy array will affect pandas_df and polars_from_pandas_df.
In [98]: x[0, 1] = 333

In [99]: x
Out[99]: 
array([[  1, 333],
       [  3,   4],
       [  5,   6]])

In [100]: pandas_df
Out[100]: 
     X  Y  Z
0    1  3  5
1  333  4  6

In [101]: polars_from_numpy_df
Out[101]: 
shape: (2, 3)
┌─────┬─────┬─────┐
│ X   ┆ Y   ┆ Z   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   │
│ 2   ┆ 4   ┆ 6   │
└─────┴─────┴─────┘

In [102]: polars_from_pandas_df
Out[102]: 
shape: (2, 3)
┌─────┬─────┬─────┐
│ X   ┆ Y   ┆ Z   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   │
│ 333 ┆ 4   ┆ 6   │
└─────┴─────┴─────┘
```

**Comment by daviddoji** [comment]
Thx @ghuls for the explanation. Now it makes total sense.
Is it an implementation decision? If so, what is the benefit?

**Comment by aptr322** [comment]
you convert from numpy to array, basicly. but if you use arrow all way thru there will be no drawback

**Comment by ghuls** [comment]
> Thx @ghuls for the explanation. Now it makes total sense. Is it an implementation decision? If so, what is the benefit?

I think it should be considered a bug, as arrow memory should be considered read only and thus shouldn't change, but copying the data in all cases will make creation of polars dataframes from pandas dataframes backed by numpy dataframes much slower.

**Comment by ritchie46** [comment]
I believe this bug is upstream. Pyarrow converts the pandas dataframes.
