### ISSUE TITLE
Should unify parameter names `nan_to_none` and `nan_to_null`, and their default value

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#6634]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

* A swift grep through the python code shows 28 matches for `nan_to_none` vs 25 matches for `nan_to_null`. 

* We are also not consistent with the default value; when converting from pandas we set it to `True`, but when converting from numpy we set it to `False`. Given that pandas is (broadly speaking) just a collection of numpy arrays there doesn't seem to be an obvious reason for the difference?

### Expected behavior

* We should pick _one_ of `nan_to_null` or `nan_to_none` and deprecate the other.
* We should (probably?) have a consistent default value.

@stinodego, @ritchie46: I can take care of the unification once we have decided what the standard should be; I'd vote for `nan_to_null = True`, but maybe there is/was some reason for the differences that I'm not aware of?

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <version not detected>
matplotlib: 3.6.3```

</details>

**Comment by stinodego** [comment]
`nan_to_null` makes more sense to me.

For Pandas, default True makes sense as there is no real equivalent to `null` values. Not sure about other cases.

**Comment by ritchie46** [comment]
> We are also not consistent with the default value; when converting from pandas we set it to True, but when converting from numpy we set it to False. Given that pandas is (broadly speaking) just a collection of numpy arrays there doesn't seem to be an obvious reason for the difference?

I disagree on this one. Numpy should be considered a numerical data processing library. It doesn't have a notion of missing data in a way a relation data processing library should. So in numpy I think a `NaN` should be considered as part of the floating point number system, whereas in pandas it is ambiguous and I think it more often than not means missing data, instead of "whoops I divided by zero".

We should be calling it `null` IMO.

**Comment by alexander-beedie** [comment]
Ok, sounds good - the difference in default does seem reasonable after all ;)
Will move everything to `nan_to_null` deprecate appropriately.

**Comment by ghuls** [comment]
> So in numpy I think a `NaN` should be considered as part of the floating point number system, whereas in pandas it is ambiguous and I think it more often than not means missing data, instead of "whoops I divided by zero".
> 
> We should be calling it `null` IMO.

FYI

In recent Pandas versions it is possible to have proper null values.
https://pandas.pydata.org/docs/user_guide/integer_na.html

It seems like they are implemented as extension arrays, backed by pyarrow:
https://pandas.pydata.org/docs/development/extending.html#compatibility-with-apache-arrow
