### ISSUE TITLE
Dealing with multiple JSON files

### ISSUE THREAD

**Issue by Uinelj** [pola-rs/polars#6638]
### Problem description

The Polars book has a page about [scanning multiple CSV files into a single DataFrame](https://pola-rs.github.io/polars-book/user-guide/multiple_files/intro.html). 
I'd like to to the same by using `polars.scan_ndjson`, but it seems that this feature is not available when dealing with JSON files: Polars/Python returns an `OSError`: `OSError: No such file or directory (os error 2)`.

Is such a feature planned? It would be really useful when dealing with large sets of data split among several files.

Also, in the meantime, is there a way of easily replicating this behaviour? I feel like I could instantiate several `LazyFrame`, but then the merging would have to be done, right?

Thanks :)

**Comment by mslapek** [comment]
Hello, may I **do this task?** 😀

My plan:

1. Add `test_ndjson_globbing` to `polars/polars-lazy/src/test/io.rs`
2. Add glob support to `polars/polars-lazy/src/frame/ndjson.rs`

The task seems to be similar to a0aec94: add globbing to ipc and csv

**Comment by mslapek** [comment]
Btw. I was thinking about a more systematic way to add multi-file support
to readers (CSV, IPC, JSON, ...).

*I could draft PR* with a trait `FileListReader`:

* blank implemented `finish` with glob support (shared logic among writers)
* `finish_impl` and `clone_with_filename` used in the `finish` method

(ex. `LazyCsvReader` would have this trait)

Apache DataFusion does something similar...

@ritchie46 What do you think?

**Comment by mslapek** [comment]
I have almost ready PR for this feature.

It requires the fix from PR #6969 to be merged.
