### ISSUE TITLE
Improve the behavior of groupby/apply of the Python API

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#6644]
### Problem description

The pandas DataFrame's groupby/apply allows taking a lambda function which returns things other than a DataFrame. This can makes groupby/apply more convenient to use.

**Comment by ritchie46** [comment]
Polars does support lambdas in groupby? What is it you want to do?

**Comment by dclong** [comment]
Polar's groupby/apply Python API requires the lambda function to return a DataFrame, which is inconvenient in many situations. So basically, I'm asking Polar's groupby/apply Python API to support lambda functions with more flexible return types.

**Comment by ritchie46** [comment]
Then you must use groupby + apply over struct. This is supported. Please make a stackoverflow question with a MWE of you want to achieve. We will answer it there.
