### ISSUE TITLE
Enhance/extend `NotFound` exception to indicate _what_ was not found

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#6647]
### Problem description

Checking through the code it seems that there are three distinct classes of error that are bundled under a single `NotFound` exception:  

* `column` not found
* `struct field` not found
* `schema field` not found

It would be helpful to be able to better distinguish between the three cases when they are raised.

### Potential solutions

Two straightforward ways to improve the situation come to mind:

1) Have a distinct error type for each:
  * `ColumnNotFound`
  * `StructFieldNotFound`
  * `SchemaFieldNotFound`

2) Put some extra context into the existing `NotFound` error string in all cases, eg:
  * `NotFound: xyz (column)`
  * `NotFound: xyz (struct field)`
  * `NotFound: xyz (schema field)`

(The latter is done sometimes, but not always).

I have a preference for the first, which is cleaner programatically and embeds the meaning directly in the exception type, rather than requiring examination of the string. It also means that the author of the underlying code doesn't have to remember to add extra text into their error.

@ritchie46: I can easily implement one of these if you agree?

**Comment by ritchie46** [comment]
Yes, seems like a great addition! :+1:
