### ISSUE TITLE
Confusion between `pl.list` and `pl.List`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#6648]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not sure if bug is the correct label for this - but I thought it may warrant some discussion.

I noticed a [recent question on stackoverflow](https://stackoverflow.com/questions/75317815/polars-convert-list-of-strings-to-list-of-categoricals) where a user was trying to cast to a list of categoricals.

They were using `pl.list()` and getting a `ValueError`
```
df = pl.DataFrame({"words": [["hello", "hi"], ["polars", "bears"]]})
df.select(pl.col("words").cast(pl.list(pl.Categorical)))
```
```
ValueError: could not convert value 'Unknown' as a Literal
```
Instead of using `pl.List()`
```
df.select(pl.col("words").cast(pl.List(pl.Categorical)))
```
```
shape: (2, 1)
┌─────────────────────┐
│ words               │
│ ---                 │
│ list[cat]           │
╞═════════════════════╡
│ ["hello", "hi"]     │
│ ["polars", "bears"] │
└─────────────────────┘
```
Just out of interest I tried passing `pl.list` to the `schema` to see what error it would generate:
```
pl.DataFrame({"words": [["hello", "hi"], ["polars", "bears"]]}, schema={"words": pl.list(pl.Categorical)})
```
```
ValueError: Since Expr are lazy, the truthiness of an Expr is ambiguous. 
Hint: use '&' or '|' to logically combine Expr, not 'and'/'or', and use
'x.is_in([y,z])' instead of 'x in [y,z]' to check membership.
```

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"words": [["hello", "hi"], ["polars", "bears"]]})
df.select(pl.col("words").cast(pl.list(pl.Categorical)))
```

### Expected behavior

I'm not sure what can be improved here - perhaps a more descriptive error is possible.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Python: 3.10.9
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by ritchie46** [comment]
I think we can raise more informative errors. Other than that I think users can be expected to learn that dtypes are starting with capitals.

**Comment by alexander-beedie** [comment]
> I think we can raise more informative errors. Other than that I think users can be expected to learn that dtypes are starting with capitals.

Yup. I can centralise a simple validation method for schema params (eg: `schema` and `schema_overrides`) that raises a sensible exception on bogus input.
