### ISSUE TITLE
str argument interpretation confusing/inconsistent (e.g. in `is_between`)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#6651]
## Problem
I think it is confusing/inconsistent that str are often interpreted as `pl.col(str)` while other data types are interpreted as `pl.lit(str)`.

```python
df = pl.DataFrame({
    "num": [1, 2, 3, 4, 5],
    "str": ["a", "b", "c", "d", "e"],
})

df.with_columns([
    # works as expected
    pl.col("num").is_between(2, 4).alias("num_between"),

    # does NOT work as expected: "b" and "d" are interpreted as column names
    pl.col("str").is_between("b", "d"),

    # workaround: use pl.lit explicitly
    pl.col("str").is_between(pl.lit("b"), pl.lit("d")).alias("str_between"),
])
```

This example is especially confusing because I would expect this to check if the row values are in between the two SCALAR bounds that I pass in. Are there actually any cases where I want to have a column as lower and upper bound? How should this even work?

Back to the example, I would expect that if
- `pl.col("num").is_between(2, 4)` is interpreted as `pl.col("num").is_between(pl.lit(2), pl.lit(4))` then
- `pl.col("str").is_between("b", "d")` is interpreted as `pl.col("str").is_between(pl.lit("b"), pl.lit("d"))` as well.

**Generally, I personally much favor explicitness and clarity over convenience where in this case the library makes different assumptions for different data types leading to unexpected behavior.**

## Solution / Idea
- interpret ALL arguments as literals
- make users be explicit if they want to use a column!

## Consequences
- selection of columns has to be explicit: `pl.col("str")` instead of `"str"`

```python
# instead of df.select("str")
df.select(pl.col("str"))

# instead of df.select(["str", "num"])
df.select(pl.col(["str", "num"]))
```

**Advantages**
- consistent interpretation of all arguments across the API (no special cases)
- no unexpected behavior
- expliticness (selecting columns)

**Disadvantages**
- more verbose (few more characters)

**In my opinion this is much clearer and less error prone and would allow for a consistent interpretation of all arguments and a more consistent API overall! =)**

**Comment by stinodego** [comment]
Thank you for making this topic! We should definitely make a decision here and make sure we're consistent across our API. I'll ponder this for a bit.

**Comment by ritchie46** [comment]
There is nothing in the library preventing you from being explicit. If you like that explicit style of writing it should be done.

I do think that reasonable defaults are fine. Our API also should be nice to use in EDA. I think we should properly document the defaults we use in each argument.

We could start a discussion on some functions which expression type should be inferred.

**Comment by stinodego** [comment]
I agree with Ritchie. I think we are quite consistent overall, although the logic might not be intuitive/obvious to everyone. Generally, the following should hold:

* Parameters that accept expressions will parse string input as `pl.col(input)` and other non-expression input as `pl.lit(input)`
* You can 'override' this logic by passing an expression, e.g. `pl.lit("abc")`

I agree that this can lead to confusion if you do not expect a method to take expression input, like in your example. I think we should address this with better documentation and error messages.

I am making an effort to verify this for all methods and document this in the parameter descriptions. Please make a separate issue if you encounter a method where the logic described above does not hold. I'll close this for now.
