### ISSUE TITLE
`is_between` provides new column name while other expressions do not

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#6654]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Not sure what the reason is or if it is a bug but `is_between` is providing a new column name while (all/most?) other expressions are not.

### Reproducible example

```python
df = pl.DataFrame({
    "a": [1, 2, 3, 4, 5]
})

# why is this creating a `is_between` column?
df.with_columns(pl.col("a").is_between(2, 4))
┌─────┬────────────┐
│ a   ┆ is_between │
│ --- ┆ ---        │
│ i64 ┆ bool       │
╞═════╪════════════╡
│ 1   ┆ false      │
│ 2   ┆ true       │
│ 3   ┆ true       │
│ 4   ┆ true       │
│ 5   ┆ false      │
└─────┴────────────┘

df.with_columns(pl.col("a").max())
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 5   │
│ 5   │
│ 5   │
│ 5   │
│ 5   │
└─────┘

df.with_columns(pl.col("a").is_unique())
┌──────┐
│ a    │
│ ---  │
│ bool │
╞══════╡
│ true │
│ true │
│ true │
│ true │
│ true │
└──────┘
```

### Expected behavior

I expect the `is_between` column NOT to change the column name by default (consistency with other expressions)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.2
numpy: 1.21.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by stinodego** [comment]
Hm, that does seem inconsistent. It's a super easy fix though as this is pure Python.
