### ISSUE TITLE
rust-polars stated as compatible with rust 1.58 in readme seems no longer true

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/polars#6655]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

[readme state rust-polars is compatible with 1.58](https://github.com/pola-rs/polars/blame/master/README.md#L167)

[I fail to compile a minimal use of rust-polars crate before rust 1.62.](https://github.com/sorhawell/minimal_rust_polars/actions/runs/4083499785/jobs/7039102579) due to compfy-table crate requires that.

I propose to increase minimal version to 1.62

### Reproducible example

https://github.com/sorhawell/minimal_rust_polars

### Expected behavior

compile polars with 1.58 succeeds

### Installed versions

polars = '*'
as of today see install logs likely 26.1

**Comment by ritchie46** [comment]
Right, that seems old. Can you make a PR?
