### ISSUE TITLE
from_arrow conversion ignores array slicing

### ISSUE THREAD

**Issue by bmschmidt** [pola-rs/polars#668]
Thank you for your work on this excellent project.

#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.7.16

#### What operating system are you using polars on?

OS X 10.14.3

#### Describe your bug.

When using `pl.from_arrow` on python tables with utf8() columns, something is happening that doesn't respect existing slices of arrays.

#### What are the steps to reproduce the behavior?

```python
import pyarrow as pa
import polars as pl

letters = pa.array(["A", "B", "C"])
tab = pa.table({
    'leading': letters[:-1],
    'lagging': letters[1:]
})
pl.from_arrow(tab)
```
Gives:
```
leading	lagging
str	str
"A"	"A"
"B"	"B"
```

While  `tab.to_pandas()` gives, correctly

leading | lagging
-- | -- | --
A | B
B | C

#### What is the expected behavior?

The to_pandas() output is correct.

Note: this behavior does not appear if the pyarrow column is an integer rather a string, i.e. the following code works as expected. 

```python
import pyarrow as pa
import numpy as np
import polars as pl

numbers = pa.array(np.arange(3))
tab = pa.table({
    'lagging': numbers[1:],
    'leading': numbers[:-1]
})
tab.to_pandas()
pl.from_arrow(tab)
```

**Comment by ritchie46** [comment]
Thanks for your issue report. I will look into it.

**Comment by ritchie46** [comment]
Is merged upstream
