### ISSUE TITLE
Python Polars consuming high memory and taking longer time

### ISSUE THREAD

**Issue by p1xel007** [pola-rs/polars#6684]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is what I'm trying to do.

1. Scan the csv using Polars lazy dataframe
2. Format the phone number using a function
3. Remove nulls and duplicates
4. Write the csv in a new file

I tested a file with 800k rows and 23 columns (150mb) and it takes around 20 seconds and more than 500mb ram then it completes the task.

Is this normal? Can I optimize the performance (the memory usage at least)?

### Here is my code

```python
import sys
import json
import polars as pl
import phonenumbers

#define the variable and parse the encoded json
args = json.loads(sys.argv[1])

#format phone number as E164
def parse_phone_number(phone_number):
    try:
        return phonenumbers.format_number(phonenumbers.parse(phone_number, "US"), phonenumbers.PhoneNumberFormat.E164)
    except phonenumbers.NumberParseException:
        pass
    return None

#scan the csv file do some filter and modify the data and then write the output to a new csv file
pl.scan_csv(args['path'], sep=args['delimiter']).select(
    [args['column']]
).with_columns(
    #convert the int phne number as string and apply the parse_phone_number function
    [pl.col(args['column']).cast(pl.Utf8).apply(parse_phone_number).alias(args['column']),
    #add another column list_id with value 100
    pl.lit(args['list_id']).alias("list_id")
    ]
).filter(
    #filter nulls
    pl.col(args['column']).is_not_null()
).unique(keep="last").collect().write_csv(args['to_save_target_path'], sep=",")
```

### Expected behavior

Low memory usage 

### Installed versions

<details>

```
0.16.2
```

</details>

**Comment by s-banach** [comment]
If you call `parse_phone_number()` on 800k strings in a for-loop, is that much faster than 20 seconds?

**Comment by ritchie46** [comment]
Don't use `apply` it is slow.

**Comment by zundertj** [comment]
Removed bug label as there is nothing obviously wrong here (including the performance).

**Comment by p1xel007** [comment]
> Don't use `apply` it is slow.

what could be alternative to achieve the same goal?

**Comment by ritchie46** [comment]
Can you make a stackoverflow question with a minimal example?
