### ISSUE TITLE
pl.read_sql not working even though connectorx is working on same data connection

### ISSUE THREAD

**Issue by 0sumeetmalik** [pola-rs/polars#6685]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When I am using same query and same connection string on ConnectorX it is working where as in Polar it is not working. Example below and screenshot attached

### Reproducible example

```python
"""
First code written with Connectorx and it is producing output of table as expected

"""
df_pd.tail()
#%%
import connectorx as cx
query1 ="""
SELECT *
FROM testing_data.age_gender_enthnicity_facedata
"""
conn3 = "postgresql://sumeetmalik:@localhost:5432/sumeetmalik"
connectorx_df = cx.read_sql(conn3, query1)
connectorx_df


"""
Second us written as per instruction on website using polars
but output has Error
ValueError: not enough values to unpack (expected2, got 1)
"""

import polars as pl
query1 ="""
SELECT *
FROM testing_data.age_gender_enthnicity_facedata
"""
conn3 = "postgresql://sumeetmalik:@localhost:5432/sumeetmalik"
polar_df = pl.read_sql(conn3, query1)
polar_df
```

### Expected behavior

![image](https://user-images.githubusercontent.com/64479357/216800825-25b2c627-78d7-449e-a92d-0ccd7de608a6.png)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.2
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by 0sumeetmalik** [comment]
[age_gender.csv](https://github.com/pola-rs/polars/files/10610199/age_gender.csv)

Sample file uploaded which was on SQL server of Postgres, local server

**Comment by alexander-beedie** [comment]
If you look at the method signature and/or the docstring, you'll see that the polars `read_sql` parameter order isn't the same as connectorx. Change `pl.read_sql(conn3, query1)` to `pl.read_sql(query1, conn3)` ;)

**Comment by 0sumeetmalik** [comment]
Ohh, sorry for silly miss. However, Even I change it to correct . Output is coming out NIL. There is no error but data is also not coming out

attaching screenshot of it 

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/64479357/216816794-720587f9-51a8-4ed7-8592-878441692641.png">
