### ISSUE TITLE
Rolling functions handle non-unique temporal values in by-column incorrectly

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#6691]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Temporal rolling functions do not seem to handle non-unique values in the by-column correctly. They seem to fall back on positional index based behavior in certain circumstances, depending on the values of `close`:

- `both`: Correctly includes all values with the left-hand key, but incorrectly stops at the index of the current value even if values after the current value share the same key.
- `left`: Seems okay with non-unique by-keys on the left hand side, but doesn't seem to always pick the correct starting row. The right hand side seems to always go to the row before the current row rather than the by-key before the current by-key.
- `right`: Exclusive left-boundary looks correct, but 

### Reproducible example

```python
Input:

pl.DataFrame(
  {
    "date": [datetime(2022, 2, d) for d in range(1, 5) for _ in range(3)],
    "y": range(12),
  }
).with_columns(
  min_both=pl.col("y").rolling_min("2d", by="date", closed="both"),
  max_both=pl.col("y").rolling_max("2d", by="date", closed="both"),

  min_left=pl.col("y").rolling_min("2d", by="date", closed="left"),
  max_left=pl.col("y").rolling_max("2d", by="date", closed="left"),

  min_right=pl.col("y").rolling_min("2d", by="date", closed="right"),
  max_right=pl.col("y").rolling_max("2d", by="date", closed="right"),

  min_none=pl.col("y").rolling_min("2d", by="date", closed="none"),
  max_none=pl.col("y").rolling_max("2d", by="date", closed="none"),
)
```

Output:

| date                |   y |   min_both |   max_both |   min_left |   max_left |   min_right |   max_right |   min_none |   max_none |
|---------------------|-----|------------|------------|------------|------------|-------------|-------------|------------|------------|
| 2022-02-01 00:00:00 |   0 |          0 |          0 |        nan |        nan |           0 |           0 |        nan |        nan |
| 2022-02-01 00:00:00 |   1 |          0 |          1 |        nan |        nan |           0 |           1 |        nan |        nan |
| 2022-02-01 00:00:00 |   2 |          0 |          2 |        nan |        nan |           0 |           2 |        nan |        nan |
| 2022-02-02 00:00:00 |   3 |          0 |          3 |          1 |          2 |           0 |           3 |          1 |          2 |
| 2022-02-02 00:00:00 |   4 |          0 |          4 |          1 |          3 |           0 |           4 |          1 |          3 |
| 2022-02-02 00:00:00 |   5 |          0 |          5 |          1 |          4 |           0 |           5 |          1 |          4 |
| 2022-02-03 00:00:00 |   6 |          0 |          6 |          1 |          5 |           3 |           6 |          3 |          5 |
| 2022-02-03 00:00:00 |   7 |          0 |          7 |          1 |          6 |           3 |           7 |          3 |          6 |
| 2022-02-03 00:00:00 |   8 |          0 |          8 |          1 |          7 |           3 |           8 |          3 |          7 |
| 2022-02-04 00:00:00 |   9 |          3 |          9 |          3 |          8 |           6 |           9 |          6 |          8 |
| 2022-02-04 00:00:00 |  10 |          3 |         10 |          3 |          9 |           6 |          10 |          6 |          9 |
| 2022-02-04 00:00:00 |  11 |          3 |         11 |          3 |         10 |           6 |          11 |          6 |         10 |

### Expected behavior

| date                |   y |   min_both |   max_both |   min_left |   max_left |   min_right |   max_right |   min_none |   max_none |
|---------------------|-----|------------|------------|------------|------------|-------------|-------------|------------|------------|
| 2022-02-01 00:00:00 |   0 |          0 |          2 |        nan |        nan |           0 |           2 |        nan |        nan |
| 2022-02-01 00:00:00 |   1 |          0 |          2 |        nan |        nan |           0 |           2 |        nan |        nan |
| 2022-02-01 00:00:00 |   2 |          0 |          2 |        nan |        nan |           0 |           2 |        nan |        nan |
| 2022-02-02 00:00:00 |   3 |          0 |          5 |          0 |          2 |           0 |           5 |          1 |          2 |
| 2022-02-02 00:00:00 |   4 |          0 |          5 |          0 |          2 |           0 |           5 |          1 |          2 |
| 2022-02-02 00:00:00 |   5 |          0 |          5 |          0 |          2 |           0 |           5 |          1 |          2 |
| 2022-02-03 00:00:00 |   6 |          0 |          8 |          0 |          5 |           3 |           8 |          3 |          5 |
| 2022-02-03 00:00:00 |   7 |          0 |          8 |          0 |          5 |           3 |           8 |          3 |          5 |
| 2022-02-03 00:00:00 |   8 |          0 |          8 |          0 |          5 |           3 |           8 |          3 |          5 |
| 2022-02-04 00:00:00 |   9 |          3 |         11 |          3 |          8 |           6 |          11 |          6 |          8 |
| 2022-02-04 00:00:00 |  10 |          3 |         11 |          3 |          8 |           6 |          11 |          6 |          8 |
| 2022-02-04 00:00:00 |  11 |          3 |         11 |          3 |          8 |           6 |          11 |          6 |          8 |

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-6.0.16-300.fc37.x86_64-x86_64-with-glibc2.36
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.4.0
numpy: 1.22.2
fsspec: 2022.01.0
connectorx: 0.2.4
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by ritchie46** [comment]
I don't think hte expected values are correct with current implementation. Currently the `rolling_min` completely looks behind current value `i`. So the `max` can never be in the future.

**Comment by qiemem** [comment]
That's what I gathered from the results. But that behavior seems incorrect to me. If someone supplies a `by` column, they're saying that the value of that column is what's important, not the index of the row. Furthermore, the current behavior prevents certain applications (such as the one mentioned in #6676, even if that issue misidentified the solution... also tbh I'm not actually familiar with that application, just ran across this while answering a related question on SO...).

Also, note that the `closed="left"` behavior looks like it's inconsistent with the others.

**Comment by ritchie46** [comment]
> If someone supplies a by column, they're saying that the value of that column is what's important, not the index of the row. 

It could be both right? It looks "2d" behind from that index position in the "by" column. I think you want to add a "forward" looking feature. Which is something we could add. I just want to make sure we agree that current behavior is correct given the original intent of the function.

**Comment by ritchie46** [comment]
I think easiest would be to expose the `offset` parameter as well. Currently it is automatically set to `-every`, which makes the function lookbehind, whereas you expected lookahead. Exposing the `offset` let's you as a user control that.

**Comment by qiemem** [comment]
Hmm, wait I think there might be some confusion here. I'm saying that the order of the elements that have the same `by` value shouldn't matter (as long as the `by` values themselves are monotonic for obvious performance reasons), not saying that it should have looked ahead by a fixed value. So the expected output for:

```python
pl.DataFrame(
    {
        "date": [
            datetime(2023, 2, 1),

            datetime(2023, 2, 2),
            datetime(2023, 2, 2),

            datetime(2023, 2, 3),
            datetime(2023, 2, 3),
            datetime(2023, 2, 3),

            datetime(2023, 2, 4),
            datetime(2023, 2, 4),
            datetime(2023, 2, 4),
            datetime(2023, 2, 4),
        ],
        "x": range(10),
    }
).with_columns(
    both_min=pl.col("x").rolling_min("0d", by="date", closed="both"),
    both_max=pl.col("x").rolling_max("0d", by="date", closed="both"),
)
```

would be:


|                date 	|   x 	| both_min 	| both_max 	|
|--------------------:	|----:	|---------:	|---------:	|
|        datetime[μs] 	| i64 	|      i64 	|      i64 	|
| 2023-02-01 00:00:00 	|   0 	|        0 	|        0 	|
| 2023-02-02 00:00:00 	|   1 	|        1 	|        2 	|
| 2023-02-02 00:00:00 	|   2 	|        1 	|        2 	|
| 2023-02-03 00:00:00 	|   3 	|        3 	|        5 	|
| 2023-02-03 00:00:00 	|   4 	|        3 	|        5 	|
| 2023-02-03 00:00:00 	|   5 	|        3 	|        5 	|
| 2023-02-04 00:00:00 	|   6 	|        6 	|        9 	|
| 2023-02-04 00:00:00 	|   7 	|        6 	|        9 	|
| 2023-02-04 00:00:00 	|   8 	|        6 	|        9 	|
| 2023-02-04 00:00:00 	|   9 	|        6 	|        9 	|

Furthermore, calling `.with_columns(pl.col("x").shuffle().over("date"))` should change the results of the rolling operations.

Apologies if I'm missing how exposing `offset` would accomplish this.

**Comment by stinodego** [comment]
The reproducible example now gives the expected result.

**Comment by fachra** [comment]
Is there a way to achieve the previous behavior in the latest version of Polars (0.20.31)? 
In my case, the positional index indicates the order of arrival of the value `y`. I want `rolling_*_by` to completely look behind current value `i`, so that no future value is used before its arrival.
I can open a new issue if needed.

**Reproducible example**
```python
import polars as pl
from datetime import date
pl.DataFrame(
  {
    "date": [date(2022, 2, d) for d in range(1, 5) for _ in range(2)],
    "y": range(8),
  }
).with_columns(
  max_left=pl.col("y").rolling_max_by(window_size="2d", by="date", closed="left"),
  max_right=pl.col("y").rolling_max_by(window_size="2d", by="date", closed="right"),
  max_both=pl.col("y").rolling_max_by(window_size="2d", by="date", closed="both"),

  sum_left=pl.col("y").rolling_sum_by(window_size="2d", by="date", closed="left"),
  sum_right=pl.col("y").rolling_sum_by(window_size="2d", by="date", closed="right"),
  sum_both=pl.col("y").rolling_sum_by(window_size="2d", by="date", closed="both"),
).with_row_index(name='order_of_arrival')
```
**Current behavior**
```
┌────────────┬───────────┬─────┬──────────┬───────────┬──────────┬──────────┬───────────┬──────────┐
│ order_of_a ┆ date      ┆ y   ┆ max_left ┆ max_right ┆ max_both ┆ sum_left ┆ sum_right ┆ sum_both │
│ rrival     ┆ ---       ┆ --- ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ ---        ┆ date      ┆ i64 ┆ i64      ┆ i64       ┆ i64      ┆ i64      ┆ i64       ┆ i64      │
│ u32        ┆           ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
╞════════════╪═══════════╪═════╪══════════╪═══════════╪══════════╪══════════╪═══════════╪══════════╡
│ 0          ┆ 2022-02-0 ┆ 0   ┆ null     ┆ 1         ┆ 1        ┆ null     ┆ 1         ┆ 1        │
│            ┆ 1         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 1          ┆ 2022-02-0 ┆ 1   ┆ null     ┆ 1         ┆ 1        ┆ null     ┆ 1         ┆ 1        │
│            ┆ 1         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 2          ┆ 2022-02-0 ┆ 2   ┆ 1        ┆ 3         ┆ 3        ┆ 1        ┆ 6         ┆ 6        │
│            ┆ 2         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 3          ┆ 2022-02-0 ┆ 3   ┆ 1        ┆ 3         ┆ 3        ┆ 1        ┆ 6         ┆ 6        │
│            ┆ 2         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 4          ┆ 2022-02-0 ┆ 4   ┆ 3        ┆ 5         ┆ 5        ┆ 6        ┆ 14        ┆ 15       │
│            ┆ 3         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 5          ┆ 2022-02-0 ┆ 5   ┆ 3        ┆ 5         ┆ 5        ┆ 6        ┆ 14        ┆ 15       │
│            ┆ 3         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 6          ┆ 2022-02-0 ┆ 6   ┆ 5        ┆ 7         ┆ 7        ┆ 14       ┆ 22        ┆ 27       │
│            ┆ 4         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 7          ┆ 2022-02-0 ┆ 7   ┆ 5        ┆ 7         ┆ 7        ┆ 14       ┆ 22        ┆ 27       │
│            ┆ 4         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
└────────────┴───────────┴─────┴──────────┴───────────┴──────────┴──────────┴───────────┴──────────┘
```
**Expected behavior**
```
┌────────────┬───────────┬─────┬──────────┬───────────┬──────────┬──────────┬───────────┬──────────┐
│ order_of_a ┆ date      ┆ y   ┆ max_left ┆ max_right ┆ max_both ┆ sum_left ┆ sum_right ┆ sum_both │
│ rrival     ┆ ---       ┆ --- ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ ---        ┆ date      ┆ i64 ┆ i64      ┆ i64       ┆ i64      ┆ i64      ┆ i64       ┆ i64      │
│ u32        ┆           ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
╞════════════╪═══════════╪═════╪══════════╪═══════════╪══════════╪══════════╪═══════════╪══════════╡
│ 0          ┆ 2022-02-0 ┆ 0   ┆ null     ┆ 0         ┆ 0        ┆ null     ┆ 0         ┆ 0        │
│            ┆ 1         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 1          ┆ 2022-02-0 ┆ 1   ┆ null     ┆ 1         ┆ 1        ┆ null     ┆ 1         ┆ 1        │
│            ┆ 1         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 2          ┆ 2022-02-0 ┆ 2   ┆ 1        ┆ 2         ┆ 2        ┆ 1        ┆ 3         ┆ 3        │
│            ┆ 2         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 3          ┆ 2022-02-0 ┆ 3   ┆ 1        ┆ 3         ┆ 3        ┆ 1        ┆ 6         ┆ 6        │
│            ┆ 2         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 4          ┆ 2022-02-0 ┆ 4   ┆ 3        ┆ 4         ┆ 4        ┆ 6        ┆ 9         ┆ 10       │
│            ┆ 3         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 5          ┆ 2022-02-0 ┆ 5   ┆ 3        ┆ 5         ┆ 5        ┆ 6        ┆ 14        ┆ 15       │
│            ┆ 3         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 6          ┆ 2022-02-0 ┆ 6   ┆ 5        ┆ 6         ┆ 6        ┆ 14       ┆ 15        ┆ 20       │
│            ┆ 4         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
│ 7          ┆ 2022-02-0 ┆ 7   ┆ 5        ┆ 7         ┆ 7        ┆ 14       ┆ 22        ┆ 27       │
│            ┆ 4         ┆     ┆          ┆           ┆          ┆          ┆           ┆          │
└────────────┴───────────┴─────┴──────────┴───────────┴──────────┴──────────┴───────────┴──────────┘
```
