### ISSUE TITLE
Passing skip_rows into scan_csv and read_csv with glob patterns doesn't skip rows before header in first file and doesn't skip rows at all in subsequent files

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#6692]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Passing `skip_rows` into `scan_csv`/`read_csv` with glob patterns results in the first line still being used as the header instead of skipping rows the specified number before the header. Also, rows are not skipped at all in any files but the first (whereas the main application of  `skip_rows` is to skip metadata headers that are presumably the same across all files).

For anyone else that runs into this, a workaround is to just do with this manually with the built-in `glob` library:

```python
pl.concat([pl.read_csv(fn, skip_rows=6) for fn in glob("data_*.csv")])
```

### Reproducible example

Input:

```python
for i in range(3):
    with open(f"test_{i}.csv", "w") as f:
        f.write(
            f"""
metadata goes here
file number {i}
foo,bar,baz
1,2,3
4,5,6
7,8,9
"""
        )

print("With glob")
print(
    pl.read_csv("test_*.csv", skip_rows=2)
    .to_pandas()
    .to_markdown(tablefmt="github", index=False)
)
print("\nSingle file without glob")
print(
    pl.read_csv("test_0.csv", skip_rows=2)
    .to_pandas()
    .to_markdown(tablefmt="github", index=False)
)
```

Output:

With glob
| metadata goes here   |
|----------------------|
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 1        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 2        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 3        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 4        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 5        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 6        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 7        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 8        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |
| metadata goes here   |
| file number 9        |
| foo                  |
| 1                    |
| 4                    |
| 7                    |

Single file without glob
|   foo |   bar |   baz |
|-------|-------|-------|
|     1 |     2 |     3 |
|     4 |     5 |     6 |
|     7 |     8 |     9 |

### Expected behavior

With glob
|   foo |   bar |   baz |
|-------|-------|-------|
|     1 |     2 |     3 |
|     4 |     5 |     6 |
|     7 |     8 |     9 |
|     1 |     2 |     3 |
|     4 |     5 |     6 |
|     7 |     8 |     9 |
|     1 |     2 |     3 |
|     4 |     5 |     6 |
|     7 |     8 |     9 |

Single file without glob
|   foo |   bar |   baz |
|-------|-------|-------|
|     1 |     2 |     3 |
|     4 |     5 |     6 |
|     7 |     8 |     9 |

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-6.0.16-300.fc37.x86_64-x86_64-with-glibc2.36
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.4.0
numpy: 1.22.2
fsspec: 2022.01.0
connectorx: 0.2.4
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by cmdlineluser** [comment]
It looks like it's happening here:

https://github.com/pola-rs/polars/blob/master/polars/polars-lazy/src/frame/csv.rs#L305
