### ISSUE TITLE
pandas groupby + transform alternative

### ISSUE THREAD

**Issue by Scitator** [pola-rs/polars#6696]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi guys, nice project!

Moving a project from pandas to polars, I found a strange behavior with custom window-based function results on top of groupby. Please check an example. 
Long story short, I want to group my data by some "column1" and transform some "column2" within each group. As far I understand pandas->polars guidelines, I can use `over` for this. However,  I found that polars produce correct results with internal functions like `ewm_mean`/`ewm_std` but not with `map`.

Is it a bug? Or could you please drive me to the correct implementation?

### Reproducible example

```python
import pandas as pd
import polars as pl


df = pl.DataFrame(
    {
        "g": ["a", "a", "a", "b", "b", "b", "c", "c", "c",],
        "v": [1, 1, 1, 2, 2, 2, 3, 3, 3],
    }
)


# pandas works okay with custom window-based functions + groupby
df_pd = df.to_pandas()
df_pd["r"] = df_pd.groupby("g")["v"].transform(lambda x: x.ewm(span=2).mean())
df_pd.head(10)
```
 g | v | r
 -- | -- | --
a | 1 | 1.0
a | 1 | 1.0
a | 1 | 1.0
b | 2 | 2.0
b | 2 | 2.0
b | 2 | 2.0
c | 3 | 3.0
c | 3 | 3.0
c | 3 | 3.0

```python
# polars works okay with integrated window-based functions + groupby, but cu
df = df.with_columns([
    pl.col("v").map(lambda x: x.ewm_mean(span=2)).over("g").alias("r"),
    pl.col("v").ewm_mean(span=2).over("g").alias("c"),
])
df.head(10)
```

g | v | r | c
-- | -- | -- | --
str | i64 | f64 | f64
"a" | 1 | 1.0 | 1.0
"a" | 1 | 1.0 | 1.0
"a" | 1 | 1.0 | 1.0
"b" | 2 | 1.675 | 2.0
"b" | 2 | 1.892562 | 2.0
"b" | 2 | 1.964286 | 2.0
"c" | 3 | 2.655078 | 3.0
"c" | 3 | 2.885061 | 3.0
"c" | 3 | 2.961691 | 3.0

### Expected behavior

column "r" should have the same values as column "c"

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.13 (default, Mar 28 2022, 06:16:26) 
[Clang 12.0.0 ]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.4.2
numpy: 1.21.6
fsspec: 2022.3.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by cmdlineluser** [comment]
Using [`.apply()` instead of `.map()`](https://pola-rs.github.io/polars-book/user-guide/dsl/custom_functions.html#to-map-or-to-apply)  generates the same values for `r` and `c`.

Note: [avoiding `.apply()`](https://stackoverflow.com/a/75351869/19355181) and using expressions is encouraged if possible.

`.map()` passes the whole column at once - so I guess using `.over()` with it is a "no-op"?
```
df.with_columns([
   pl.col("v").map(lambda x: [print(x), x][1]).over("g").alias("r"),
])
```
```
shape: (9,)
Series: 'v' [i64]
[
	1
	1
	1
	2
	2
	2
	3
	3
	3
]
```
Whereas `.apply()` gets you each "group"
```
df.with_columns([
   pl.col("v").apply(lambda x: [print(x), x][1]).over("g").alias("r"),
])
```
```
shape: (3,)
Series: '' [i64]
[
	2
	2
	2
]
shape: (3,)
Series: '' [i64]
[
	3
	3
	3
]
shape: (3,)
Series: '' [i64]
[
	1
	1
	1
]
```

**Comment by ritchie46** [comment]
`map` should not be used in the groupby context. It is not group aware.

**Comment by Scitator** [comment]
@ritchie46 maybe we could write something like "_attention: inconsistent work with groupby_" under map docs? or somehow prepare users for this feature?
or have I missed this doc? 😄

**Comment by graceyangfan** [comment]
@ritchie46 Is there any possile to apply complex udf functions to over operator similar to groupby apply ,I know you would suggest for polars original operator,but current some complex logical cannot be wrote into original operators
