### ISSUE TITLE
When add List column and List column , panic happened

### ISSUE THREAD

**Issue by lilium513** [pola-rs/polars#6700]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hello, thanks for polars. I love this useful and really convenient software !
I'd like to report some bug? in polars.
If more information is needed, I'll be pleased to give.

# What I tried 
- attach list  col and list col on polars dataframe.
# What happened
panic happend.
The below is log on Google Colaboratory
<html>
<body>

Feb 6, 2023, 11:15:00 PM | WARNING | thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: List(Utf8)', /home/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:163:13
-- | -- | --

</body>
</html>

And  code I ran is ↓ 

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"ids_1" : ["a b c"],
                           "ids_2" : ["e f g"]})
df = df.with_columns([pl.col("ids_1").str.split(" "),pl.col("ids_2").str.split(" ")])

# add "ids_1" col and "ids_2" col
# When  I executed ↓ code , then panick happened.
df.with_column( (pl.col("ids_1") + pl.col("ids_2")).alias("col3"))
```

### Expected behavior

I want to get concat list column like ↓

<html>
<body>
<br class="Apple-interchange-newline">

ids_1 | ids_2  | ids_3
-- | -- | --
list[str] | list[str] | list[str]
["a", "b", "c"] | ["e", "f", "g"] | ["a", "b", "c","e", "f", "g"]

</body>
</html>

### Installed versions

<details>

---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-5.10.147+-x86_64-with-glibc2.29
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.2.2
</details>

**Comment by cmdlineluser** [comment]
You can use [`.arr.concat()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.concat.html#polars.Expr.arr.concat)
```
df.with_columns(ids_3 = pl.col("ids_1").arr.concat("ids_2"))
```
```
shape: (1, 3)
┌─────────────────┬─────────────────┬─────────────────────┐
│ ids_1           | ids_2           | ids_3               │
│ ---             | ---             | ---                 │
│ list[str]       | list[str]       | list[str]           │
╞═════════════════╪═════════════════╪═════════════════════╡
│ ["a", "b", "c"] | ["e", "f", "g"] | ["a", "b", ... "g"] │
└─────────────────┴─────────────────┴─────────────────────┘
```

**Comment by lilium513** [comment]
Thank you very much your quick and perfect answer !!

**Comment by cmdlineluser** [comment]
The `PanicException` part is still an issue I think.

As polars seems to know the types - perhaps it could suggest `.arr.concat()` in an error message?
