### ISSUE TITLE
A dynamic pattern length in the 'str.replace' expressions are not yet supported. Consider open a feature request for this.

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#6704]
### Problem description

A dynamic pattern length in the 'str.replace' expressions are not yet supported. Consider open a feature request for this.

**Comment by alexander-beedie** [comment]
Could you provide an example of what you mean by a dynamic pattern length?

**Comment by mcrumiller** [comment]
@alexander-beedie this is the ["Expressions everywhere"](https://github.com/pola-rs/polars/issues/5813) guy, don't expect a response or any sort of meaningful information.

**Comment by ritchie46** [comment]
Thanks for the heads-up @mcrumiller. I will close this.
