### ISSUE TITLE
from_pandas error

### ISSUE THREAD

**Issue by fehtemam** [pola-rs/polars#671]
Trying to convert from pandas dataframe that has a dtype of object and getting a traceback that goes to:

File "/venv/lib/python3.7/site-packages/polars/functions.py", line 400, in from_pandas
    if dtype == "object" and isinstance(df[name][0], str):

df[name][0] does not work for getting the first element of a column. It should be df[name].iloc[0].

**Comment by ritchie46** [comment]
Good catch. I will fix that.
