### ISSUE TITLE
Diagonal concat on read/scan parquet glob

### ISSUE THREAD

**Issue by M-Salti** [pola-rs/polars#6710]
### Problem description

I'd like to be able to do something like: `pl.read_parquet("*.parquet", merge_schema=True)` to achieve schema evolution.

I've noticed that  `pl.scan_parquet("*.parquet")` and  `pl.concat([...])` on multiple lazy reads generate the same execution plan, so I suppose `scan_parquet` calls `concat` under the hood? If that's the case would it be possible to call `concat` with `how="diagonal"`?

**Comment by zundertj** [comment]
I am not sure we should add more flags to handle such situations, it leads to a very large and complex api. The glob pattern is designed as far as I know for partitioned parquet files, which should have the same schema. In the situations where the schemas differ but you want them to be the same, you probably 1) have bigger issues, i.e. with the parquet generating process, and 2) you can call `scan_parquet` on the individual files and `concat` diagonally yourself?
