### ISSUE TITLE
Badly formatted error message when invalid data passed to `DataFrame` constructor

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6714]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See example.

### Reproducible example

```python
import polars as pl

data = {"a": [100, 101], "b": [102], "c": [103, 104, 105]}

df = pl.DataFrame(data)
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/utils.py", line 393, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/dataframe/frame.py", line 329, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/construction.py", line 697, in dict_to_pydf
    return PyDataFrame(data_series)
           ^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths. Got [shape: (2,)
Series: 'a' [i64]
[
        100
        101
], shape: (1,)
Series: 'b' [i64]
[
        102
], shape: (3,)
Series: 'c' [i64]
[
        103
        104
        105
]]
```

It prints all the data! Now imagine you actually pass some larger dataframe, it will consume your whole logs.

### Expected behavior

The error message shouldn't print all the data. It should probably only print the fact that the Series have different lengths.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
I considered that, but let's say you have a 100 columns of length 10, and there's one mistake in there, then you still get a hundred lines looking like:

```
10
10
10
10
11
10
...
10
10
10
```

And you have to find the one shape that's different.

I just don't think the size of our error messages should scale with input data in any way.

**Comment by MarcoGorelli** [comment]
Thanks for explaining - how about just printing the first one, and the first one which differs?

Something like
```
The Series have different lengths: found length 2 at index 0, and length 1 and index 1
```
Then it wouldn't scale with the size of the input, but would still give more info about what's wrong

**Comment by stinodego** [comment]
I think that would be a great solution!

**Comment by ritchie46** [comment]
> Thanks for explaining - how about just printing the first one, and the first one which differs?
> 
> Something like
> 
> ```
> The Series have different lengths: found length 2 at index 0, and length 1 and index 1
> ```
> 
> Then it wouldn't scale with the size of the input, but would still give more info about what's wrong

Shall we call it `column` instead of `index`.

**Comment by ritchie46** [comment]
> Thanks for explaining - how about just printing the first one, and the first one which differs?
> 
> Something like
> 
> ```
> The Series have different lengths: found length 2 at index 0, and length 1 and index 1
> ```
> 
> Then it wouldn't scale with the size of the input, but would still give more info about what's wrong

Shall we call it `column` instead of `index`.

**Comment by stinodego** [comment]
I was planning to use the Series name, actually.

**Comment by ritchie46** [comment]
Noe that's smart!
