### ISSUE TITLE
null filling when using flatten on empty lists

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6723]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Empty `lists` are being automatically filled with `null` before being concatenated on calling `flatten()`.

### Reproducible example

```python
import polars as pl

(pl.DataFrame({'ind': [1, 1], 'tab': [["a"], []]})
 .groupby('ind')
 .agg(pl.col('tab').flatten()))
```

### Expected behavior

Not to fill empty list with `null` and to return :
```
shape: (1, 2)
┌─────┬─────────────┐
│ ind ┆ tab         │
│ --- ┆ ---         │
│ i64 ┆ list[str]   │
╞═════╪═════════════╡
│ 1   ┆ ["a"]       │
└─────┴─────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is as expected. You can first filter out empty lists if you don't want this behavior.

**Comment by PieReissyet** [comment]
Not sure to understand how null filling can be expected when using this function.

Also, filtering out empty lists before using `flatten` is not a proper solution since I do not want to lose `ind` values that can be linked to empty lists only.

The only actual workaround would be to use :
```
.with_columns(pl.col('tab').arr.eval(pl.element().filter(pl.element().is_not_null()))
```
but it requires extra computation for no apparent reason.

**Comment by ritchie46** [comment]
> Also, filtering out empty lists before using flatten is not a proper solution since I do not want to lose ind values that can be linked to empty lists only.

You can `filter` within the groupby aggregation. 

> Not sure to understand how null filling can be expected when using this function.

You can read it as "we cannot flatten an empty list". This behavior is needed to make `flatten` consistent with exploding `DataFrame`s. See the same behavior in pandas: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html 

In this case we don't look at the operation in isolation, and getting your desired output is easy as we can use expression to explain our intent:

```python
(
    pl.DataFrame({'ind': [1, 1], 'tab': [["a"], []]})
     .groupby('ind')
     .agg(pl.col('tab').filter(
         pl.col("tab").arr.lengths() > 0
     ).flatten())
)
```

**Comment by PieReissyet** [comment]
Brilliant ! Did not think about that.

Thanks a lot for the detailed explanation.
