### ISSUE TITLE
Documentation for `groupby_dynamic()` for Rust

### ISSUE THREAD

**Issue by seongs1024** [pola-rs/polars#6724]
### Problem description

[In the user guide](https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/temporal_groupby.html), there are documentations for `groupby_dynamic()` for python but not for Rust...

[From the Rust API docs](https://docs.rs/polars/latest/polars/prelude/trait.PolarsTemporalGroupby.html#tymethod.groupby_dynamic), the return type of the function differs that makes inferring from python codes difficult.

Can someone help me out?

**Comment by seongs1024** [comment]
And in the test code, the `DataFrame` is converted to `LazyFrame` and apply `goupby_dynamics()` and `agg()`.

Does it work?

https://github.com/pola-rs/polars/blob/5df0ce27492df12d79a92ab444a39a05341d2f6d/polars/tests/it/lazy/groupby_dynamic.rs#L41-L57

**Comment by ritchie46** [comment]
Yes, you should use `LazyFrame`. I have added #6725 to ensure it is in the docs.

**Comment by seongs1024** [comment]
Thanks!
