### ISSUE TITLE
Binary Type polar series

### ISSUE THREAD

**Issue by abuckenheimer** [pola-rs/polars#673]
#### Describe your feature request

Hi, awesome library, I was trying to use polars to extend some of the work I was doing with arrow today in python and noticed that polars errors out trying to create binary series:
```
>>> polars.DataFrame.from_arrow(pa.table([pa.array([b'hi'])], pa.schema([('hi', pa.binary())])))
Traceback (most recent call last):
  File "<pudb command line>", line 1, in <module>
  File "/home/buck/.cache/pypoetry/virtualenvs/carnegie-TTBep1lp-py3.9/lib/python3.9/site-packages/polars/frame.py", line 271, in from_arrow
    self._df = PyDataFrame.from_arrow_record_batches(batches)
RuntimeError: Any(InvalidOperation("Cannot create polars series from Binary type"))
```
Is this expected? If so I would love to see binary types supported.

Thanks!

**Comment by ritchie46** [comment]
This is not supported indeed. Does a type `LargeList[UInt8]]` make sense for binary data?

**Comment by abuckenheimer** [comment]
hmm I suppose both of those could work, is there an easy way to cast the `pa.Table` / `pa.Array` types? Would be nice if I didn't have to convert my `pa.Table` into a pandas dataframe to do this.

**Comment by ritchie46** [comment]
Yes, pyarrow has a `cast` kernel in `pyarrow.compute.cast`. Here are some examples on how those can be used: https://github.com/pola-rs/polars/blob/d93cc409fc1e389c6d6f29cd2c04de86b1a3820d/py-polars/polars/utils.py#L4

**Comment by abuckenheimer** [comment]
sorry I'm a bit of an arrow noob and have not been able to figure out how to do the conversion. Would you like me to close this issue as an unsupported? or keep it around?

**Comment by ritchie46** [comment]
> sorry I'm a bit of an arrow noob and have not been able to figure out how to do the conversion. Would you like me to close this issue as an unsupported? or keep it around?

No worries. I'll close it. :)
