### ISSUE TITLE
SQLContext: SELECT with chained comparison match everything

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6731]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Chained comparisons seem to match everything in `SQLContext` .

PostgreSQL raises a syntax error on similar constructs - `SQL Error [42601]: ERROR: syntax error at or near "<"`

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "value": list(range(7)),
})

sql_ctx = pl.SQLContext()
sql_ctx.register("df", df.lazy())

df2 = sql_ctx.query("SELECT * FROM df WHERE 2 < value < 5")
print(df2)
```

Outputs:

```
shape: (7, 1)
┌───────┐
│ value │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
│ 1     │
│ 2     │
│ 3     │
│ 4     │
│ 5     │
│ 6     │
└───────┘
```

### Expected behavior

Not sure, I think this is an SQL syntax error.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by alexander-beedie** [comment]
This does indeed raise a syntax error in most dialects...
```python
query = """
WITH data("value") AS (
  VALUES (0),(1),(2),(3),(4),(5),(6),(7)
) 
SELECT data."value", (2 < data."value" < 5) FROM data
"""

# exec against a postgres connection
list( pgconn.execute(query) )

psycopg2.errors.SyntaxError: syntax error at or near "<"
```
...though interestingly it _does_ actually execute in SQLite, which returns the same answer as the polars (eg: returns everything). The standard desugaring of an `x < y < z` expression is `(x < y) & (y < z)` though, so I'm really not sure what SQLite is doing there 💭

**Comment by 2-5** [comment]
I think SQLite (and probably Polars too) parses it as `(x < y) < z` and treats the boolean result of `(x < y)` numerically - `0 < z`, or `1 < z` which is `true` for any `z >= 1`
