### ISSUE TITLE
Log offending expression(s) when select / with_column() panic errors out

### ISSUE THREAD

**Issue by cjstudioz** [pola-rs/polars#6736]
### Problem description

when I encounter a panic error in a select query, I'd like a way to narrow down which is / are the offending expressions simply by looking at the logs. Without having to alter the code into a sequential binary search or for loop and rerunning.

```
pl.select([
  expr1, expr2, expr3 .... 
])
```
https://stackoverflow.com/questions/75373284/how-to-debug-large-polars-pl-select-narrow-down-offending-row/75373359?noredirect=1#comment133003799_75373359

**Comment by ritchie46** [comment]
Set `RUST_BACKTRACE=1`

**Comment by cjstudioz** [comment]
Apologies for being daft, I've set RUST_BACKTRACE in both spyder and pycharm but cannot see any info that leads me to the offending expression

e.g.
```
import os
import polars as pl
#os.environ['RUST_BACKTRACE'] = '1' # already set in user env vars
c = pl.col


df = pl.DataFrame({
    's1': [1, 2, 3, 4, 5],
    's2': [2, 3, 4, 5, 6],
    's3': [2, 3, 4, 5, 6],
    's4': [pl.col] * 5
})

res = df.select([
    (c('s1') + 1).alias('a1'),
    (c('s5') + 1).alias('a2'), # missing input col
    (c('s2').map(lambda x: pl.from_pandas(x.to_numpy()))).alias('a3'), # exception in lambda
    (c('s2') + c('s4')).alias('a4'), # type coercion error
])

could you show me what I'd expect to see to identify the offending rows?

P.S. Huge fan of polars! thank you for building this!

```

**Comment by alexander-beedie** [comment]
When I try, it tells me the directly now? (Without requiring backtrace)
`exceptions.ColumnNotFoundError: s5`
