### ISSUE TITLE
Rust analyzer fails to provide code completion for Expr

### ISSUE THREAD

**Issue by jvliwanag** [pola-rs/polars#6739]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

It would be of great assist to users if rust analyzer is able to provide proper auto complete hints for `Expr`. Currently, a prelude import fails to:

* determine the type of `col("foo")`
* Provide any completions for variables known as `Expr`

A fix for this one might also help docs generated. Example - [this](https://docs.rs/polars/0.26.1/polars/prelude/enum.Expr.html) does not have a source code link.

### Reproducible example

```rust
use polars::prelude::*;

let a: Expr = col("foo");
a. // no auto complete
```

### Expected behavior

Autocomplete to show up.

### Installed versions

polars = { version = "0.26.1", features = ["json", "dtype-struct", "parquet", "strings", "lazy", "partition_by"] }

rust-analyzer 1.67.0 (fc594f15 2023-01-24)

rustc 1.67.0 (fc594f156 2023-01-24)

**Comment by ritchie46** [comment]
That's something you should take up to rust-analyzer.

**Comment by jvliwanag** [comment]
Understood that this is better brought up with rust-analyzer. Leaving a workaround for now. Wildcard importing dsl module leads to better completions.

```rust
use polars::lazy::dsl::*;
use polars::prelude::*;
```
