### ISSUE TITLE
groupby works in MacOS but not in Linux

### ISSUE THREAD

**Issue by nickbien** [pola-rs/polars#6741]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have this line of code.

`DF.groupby('Col2').agg([pl.col('Col3').list().unique()]).sort('Col2').to_dicts()`

This works well when ran in MacOS but when I run using Linux, it comes back with error below.

`File ".venv38/lib/python3.8/site-packages/polars/internals/dataframe/groupby.py", line 248, in agg
    pli.wrap_df(self._df)
  File ".venv38/lib/python3.8/site-packages/polars/internals/lazyframe/frame.py", line 1146, in collect
    return pli.wrap_df(ldf.collect())
exceptions.InvalidOperationError: this operation is not implemented/valid for this dtype: List(Utf8)`

Versions of python used during tests:
3.8, 3.9, 3.10

Polars version: 0.16.2

OS: Arch Linux x86_64
Kernel: 6.1.9-arch1-2

### Reproducible example

```python
from hashlib import md5
import pickle
import polars as pl


def hash_key(key):
    return md5(pickle.dumps(key)).hexdigest()


CSV_FILE = './FILE.csv'
DF = pl.read_csv(CSV_FILE)
DF = DF.with_column(pl.struct(['Col1', 'Col2', 'Col3', 'Col4', 'Col5']).apply(lambda x: hash_key(tuple((x['Col1'], x['Col2'], x['Col3'], x['Col5'], x['Col4'])))).alias('hash'))
DATA = {
    i.get('Col2'): i.get('Col3') if isinstance(i.get('Col3'), list) else [i.get('Col3')] for i in DF.groupby('Col2').agg([pl.col('Col3').list().unique()]).sort('Col2').to_dicts()
}
```

### Expected behavior

DATA should not have any issue at all since this works in MacOS.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-6.1.9-arch1-2-x86_64-with-glibc2.34
Python: 3.8.16 (default, Jan 12 2023, 12:57:47) 
[GCC 12.2.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: 3.6.3
```

</details>

**Comment by stinodego** [comment]
I suspect that you haven't upgraded to the latest version on Linux. Python Polars 0.16.0 changed the behaviour of calling `.list()` in a groupby aggregation context. See https://github.com/pola-rs/polars/pull/6487

You should probably upgrade to the latest version and remove the `.list()` call, and you will see the results you expect.

**Comment by nickbien** [comment]
Wow, thanks @stinodego !! that was actually the right call, removing `.list()`.

**Comment by stinodego** [comment]
Great! Happy to help 😸
