### ISSUE TITLE
Upgrade to mypy `1.0.0` and use `Self` type

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6743]
I've been waiting for this release for a while. See:
https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html

`mypy` now includes the `Self` type which should allow us to get rid of those ugly `DF` / `LDF` TypeVars.

I'll be working on this! Could be a quick change.

**Comment by ghuls** [comment]
> Mypy 1.0 is up to 40% faster than mypy 0.991 when type checking the Dropbox internal codebase.
Seems interesting too!

**Comment by stinodego** [comment]
Yes that sounds great indeed - `mypy` is much slower than `ruff` and `black` put together.

Having some trouble getting this to work on Python 3.7 though, something about `backports.zoneinfo` messing this up 😞
