### ISSUE TITLE
Reading Json File with object in it

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#6745]
### Problem description

Hi there!
I have a Json like this:

```json
{
    "value": [
        { "col1": 1, "col2": true },
        { "col1": 3, "col2": false}
   ]
}
```

Reading gives:
`RuntimeError: BindingsError: "ArrowError(NotYetImplemented(\"read an Array from a non-Array JSON\"))"`

Any chance to implement that?

**Comment by ritchie46** [comment]
Hi @aersam. Can you open this request upstream in arrow2? We can take it up there.

**Comment by cmdlineluser** [comment]
Whilst running into this - I discovered the newly added [`.json_extract()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.json_extract.html#polars.Expr.str.json_extract) which seems to be another way to parse json.
```
import io
import polars as pl

json = """
{
   "value": [
      { "col1": 1, "col2": true },
      { "col1": 3, "col2": false}
   ]
}
"""

df = pl.DataFrame({"json": [json]}).with_columns(pl.col("json").str.json_extract())
```
```
shape: (1, 1)
┌─────────────────────────┐
│ json                    │
│ ---                     │
│ struct[1]               │
╞═════════════════════════╡
│ {[{1,true}, {3,false}]} │
└─────────────────────────┘
```
It looks like [it uses a different parser](https://github.com/pola-rs/polars/blob/master/polars/polars-ops/src/chunked_array/strings/json_path.rs#L10) to `.read_json()` (serde vs. arrow2?)
```
pl.read_json(io.StringIO(json))
```
```
RuntimeError: 
  BindingsError: 
     "ArrowError(NotYetImplemented(\"read an Array from a non-Array JSON\"))"
```
