### ISSUE TITLE
New polars release with arrow2 0.16

### ISSUE THREAD

**Issue by emilk** [pola-rs/polars#6747]
### Problem description

@jorgecarleitao just released arrow2 0.16, and so it would be super-nice with a new polars release compatible with that.

I notice the current `master` is currently using [a branch](https://github.com/ritchie46/arrow2/tree/mmap_slice2) of a @ritchie46 fork of `arrow2`, so maybe this is non-trivial?

**Comment by ritchie46** [comment]
We will, arrow2 is just released this morning. Give me some time. ;)

**Comment by emilk** [comment]
Haha, sorry to stress you out :) Have a nice relaxing day ❤️
