### ISSUE TITLE
Predicate pushdown not working when using strings

### ISSUE THREAD

**Issue by pascalschwahn** [pola-rs/polars#6750]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When filtering a parquet dataset on a partition represented by a string the predicate does not get pushed down to scan level. Which leads to OOM on larger than RAM datasets.

### Reproducible example

```python
import pyarrow as pa
import pyarrow.dataset as ds
import polars as pl

# Create example dataset
df = pl.DataFrame(
    {
        'some_column': ['a', 'b', 'c', 'd'],
        'some_partition_column':['partition_1', 'partition_2', 'partition_1', 'partition_2']
    }
)
partitioning = ds.partitioning(schema=pa.schema([
    ('some_partition_column', pa.string())
]), flavor='hive')
ds.write_dataset(
    data=df.to_arrow(),
    base_dir='./test',
    format='parquet',
    partitioning=partitioning,
    existing_data_behavior='overwrite_or_ignore'
)

# Scan dataset
dataset = ds.dataset('./test', format='parquet', partitioning='hive')
df = pl.scan_ds(dataset).filter(pl.col('some_partition_column') == 'partition_1')
print(df.describe_optimized_plan())

"""
Outputs:
FILTER [(col("some_partition_column")) == (Utf8(partition_1))] FROM
    PYTHON SCAN 
    PROJECT */2 COLUMNS
"""
```

### Expected behavior

Expected Output:
PYTHON SCAN 
  PROJECT */2 COLUMNS
  SELECTION: (pa.dataset.field('some_partition_column') == 'partition_1')

### Installed versions

---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: 3.6.3

**Comment by ritchie46** [comment]
This has been fixed on master. Release will be tomorrow.
