### ISSUE TITLE
`str.replace` and `str.replace_all` cannot replace with the literal string "$0" when `literal=True`. (but only in some cases)

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#6755]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Replacing some strings with `$0` will replace it with itself, even when `literal=True`. When replacing with `$1` it will replace with empty string.

It's obviously taking the match groups.

### Reproducible example

```python
import polars as pl

# . is replaced with itself
print(pl.Series(["."]).str.replace(".", "$0", literal=True)[0])  # -> "."

# . is replaced with literal $0
print(pl.Series(["1"]).str.replace("1", "$0", literal=True)[0])  # -> "$0"

# replace_all always replaces with itself
print(pl.Series(["."]).str.replace_all(".", "$0", literal=True)[0])  # -> "."
print(pl.Series([".."]).str.replace_all(".", "$0", literal=True)[0])  # -> ".."
print(pl.Series(["a"]).str.replace_all("a", "$0", literal=True)[0])  # -> "a"
print(pl.Series(["aa"]).str.replace_all("a", "$0", literal=True)[0])  # -> "aa"
print(pl.Series(["aa"]).str.replace_all("a", "$1", literal=True)[0])  # -> ""


def replace(pattern, replace):
    return pl.Series([pattern]).str.replace(pattern, replace, literal=True)[0]


# Happens with single chars that are symbols
replace(".", "$0")  # "."
replace(";", "$0")  # ";"
replace("[", "$0")  # "["
replace("]", "$0")  # "]"
replace("(", "$0")  # "("
replace(")", "$0")  # ")"
replace("^", "$0")  # "^"
replace("$", "$0")  # "$"

# Happens when just a single symbol is present in string
replace("a#b", "$0")  # "a#b"

# Empty string when using $1
replace(".", "$1")  # ""
replace(";", "$1")  # ""

# Other chars works fine
replace("1", "$0")  # "$0"
replace("ab", "$0")  # "$0"
replace("aa", "$0")  # "$0"
replace("1", "$1")  # "$1"
replace("a", "$1")  # "$1"
replace(" ", "$0")  # "$0"
```

### Expected behavior

When `literal=True` I would expect it to also replace with the literal string `$0`. I guess the documentation does actually say that the _pattern_ is taken as literal, but if the pattern is literal you have no reason to use match groups in `replace` (Since you know that `$0 == pattern` and `$n == ""`)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.9.14 (main, Sep  7 2022, 23:43:48) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.3.5
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.0
```

</details>

**Comment by cmdlineluser** [comment]
Looks like `val` needs to be wrapped with [regex::NoExpand](https://docs.rs/regex/latest/regex/struct.Regex.html#examples-2) in `replace_literal` and `replace_literal_all`.

https://github.com/pola-rs/polars/blob/master/polars/polars-ops/src/chunked_array/strings/namespace.rs#L224

https://github.com/pola-rs/polars/blob/master/polars/polars-ops/src/chunked_array/strings/namespace.rs#L237

**Comment by alexander-beedie** [comment]
> Looks like `val` needs to be wrapped with [regex::NoExpand]

Yup; escaping `$ => $$` works too, but `NoExpand` is preferable as it will be slightly more performant (I'm literally making that update now ;)

**Comment by alexander-beedie** [comment]
@StefanBRas: nice find - thanks for the report ;)

**Comment by StefanBRas** [comment]
@alexander-beedie You're welcome and thanks for the quick fix!

I doubt I'd ever find it myself manually - it was only because I was trying out hypothesis for testing some expressions and `hypothesis.strategies.text()` produced the `$0`.

**Comment by alexander-beedie** [comment]
> it was only because I was trying out hypothesis for testing some expressions...

Good stuff; I'm a big fan of `hypothesis` - actively probing for edge-cases can really help strengthen the codebase.
