### ISSUE TITLE
Writing a DataFrame containing a Struct column to Parquet fails when number of rows reach a certain amount

### ISSUE THREAD

**Issue by ahmedriza** [pola-rs/polars#6760]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I am trying to transform a DataFrame containing a few columns to a new one where all but one of the columns are converted to a Struct.  That all works fine.  

When I write the resulting DataFrame to Parquet it fails from Rust, but work from Python.  

I think I'm doing the same thing in both languages, but perhaps there is something wrong with my Rust version.  I can't figure out what I'm doing wrong though.

The Python version, by default uses the `pyarrow` Parquet writer, so I think there's an issue in the `arrow2` Parquet writer.

Interestingly, the Rust version works upto 95,000 rows, but fails on the Parquet write when the number of rows exceed that.

### Reproducible example

The Rust version that fails when writing to Parquet
```rust
        use polars::{lazy::dsl::as_struct, prelude::*};
        
        // works up to 95_000 
        let rows = 100_000;

        let ids = Series::new("ID", vec![1; rows]);
        let col_a = Series::new("A", vec!["foo"; rows]);
        let col_b = Series::new("C", vec![2.71; rows]);
        let df = DataFrame::new(vec![
            ids,
            col_a,
            col_b
        ]).unwrap().lazy();

        let join_column_name = "ID";
        let struct_columns = df.schema().unwrap()
            .iter_names()
            .filter(|s| *s != join_column_name)
            .map(|s| col(s))
            .collect::<Vec<_>>();
        
        let mut df_v = df
            .select([
                col(join_column_name),
                as_struct(&struct_columns).alias("Data"),
            ])
            .collect().unwrap();
        // write to parquet, fails on Parquet write 
        let mut file = std::fs::File::create("/tmp/df_v.parquet").unwrap();
        ParquetWriter::new(&mut file).finish(&mut df_v).unwrap();           
```
Error is as follows:
```
thread '<unnamed>' panicked at 'the offset of the new Buffer cannot exceed the existing length', /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.16.0/src/array/utf8/mod.rs:205:9
```

### Expected behavior

Expect the Rust code to work just as the following Python version.

```python
    import polars as pl
    
    rows = 100000

    ids = pl.Series("ID", [1 for i in range(rows)])
    col_a = pl.Series("A", ["foo" for i in range(rows)])
    col_b = pl.Series("C", [2.71 for i in range(rows)])
    df = pl.DataFrame([
        ids,
        col_a,
        col_b
    ])

    join_column_name = "ID"
    schema = df.schema
    columns = [k for k in schema.keys() if k != join_column_name]
    struct_columns = list(map(lambda c: pl.col(c), columns))
    
    df_v = df.select(
        (
            pl.col(join_column_name),
            pl.struct(struct_columns).alias("Data")
        )
    )
    df_v.write_parquet("/tmp/df_v.parquet")
```

### Installed versions

For Rust, I've used both Git master and "0.26.1" from crates.io.  The Python version is the latest release, i.e. "0.16.2".

The Rust version used these features:
<details>
features = ["lazy", "parquet", "docs",
       "dtype-date", "dtype-datetime", "dtype-duration", "dtype-slim", "dtype-struct",
       "fmt", "polars-io", "polars-time", "temporal", "zip_with", "json", "is_in",
       "diagonal_concat"]
```
</details>

**Comment by ritchie46** [comment]
I tune @jorgecarleitao in. He is working on this upstream.
