### ISSUE TITLE
pl.from_pandas() ignores index

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#6763]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`pl.from_pandas(df)` should probably read in the index of a DataFrame if it's not a `pd.RangeIndex` and treat these as regular columns.

### Reproducible example

```python
import pandas as pd
import polars as pl

df = pd.DataFrame([1, 2, 3, 4, 5], columns=['b'], index=['a', 'b' ,'c', 'd', 'e']).rename_axis('a')
print(df)
   b
a
a  1
b  2
c  3
d  4
e  5

print(pl.from_pandas(df))
shape: (5, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
│ 4   │
│ 5   │
└─────┘
```

### Expected behavior

```
print(pl.from_pandas(df))
shape: (5, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 1   │
│ b   ┆ 2   │
│ c   ┆ 3   │
│ d   ┆ 4   │
│ e   ┆ 5   │
└─────┴─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.24.0
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by mcrumiller** [comment]
The current behavior might be intended, but I ran into this in the wild and it seemed like a reasonable approach to include the index if it's column-like and not your standard 0-indexed numbering.

**Comment by ritchie46** [comment]
@alexander-beedie shall we default to ignoring it and add a `include_index` option?

**Comment by mcrumiller** [comment]
P.S. this is why I hate pandas indexes: there's no real way to distinguish between a purposefully created index and a default-created `pd.RangeIndex`.

**Comment by alexander-beedie** [comment]
> @alexander-beedie shall we default to ignoring it and add a `include_index` option?

That would be the most backward-compatible option, so we could start there. However, having the ability to automatically load _non-default_ indexes as columns would be more streamlined in the long run, as they frequently contain "real" column data. 

I already have some code at work that I could trivially repurpose for us that does _exactly_ this kind of pandas non-default index detection; what do you think? Then we could set `include_index = True` while still avoiding the trivial/annoying default index (there is slightly more to it than just "is not a RangeIndex"). What do you think?

**Comment by alexander-beedie** [comment]
> P.S. this is another reason why I hate pandas indexes: there's no real way to distinguish between a purposefully created index and a default-created `pd.RangeIndex`.

Heh. It's do-able, but you do indeed have to cover more cases than you'd think :)

**Comment by mcrumiller** [comment]
Hey @alexander-beedie, any chance you could quickly summarize those cases? This actually might be useful to me in another project.

**Comment by alexander-beedie** [comment]
> Hey @alexander-beedie, any chance you could quickly summarize those cases? This actually might be useful to me in another project.

@mcrumiller  Here you go; take a look at `pandas_has_default_index` in #6847.
