### ISSUE TITLE
Include "quarter" as an option for `groupby_dynamic`.

### ISSUE THREAD

**Issue by bfeif** [pola-rs/polars#6764]
### Problem description

I'd like to do `groupby_dynamic()` with business quarters, e.g. 
```python
df.groupby_dynamic("datetime_column_name", every="1q")  # every="1q" represents 'every business quarter', i.e. Jan-Mar, Apr-Jun, etc.
```

When I try this, I get the error `pyo3_runtime.PanicException: unit: 'q' not supported`. Either I can't figure out the correct code for "quarter", or the functionality isn't supported in polars.

For reference, [this use-case is supported by pandas](https://stackoverflow.com/questions/49949300/pandas-groupby-dates-within-a-quarter).

**Comment by ritchie46** [comment]
It is not supported. I would accept a PR for this. Our `week` support could give a hint of what to do.

Here is a diff on that:

https://github.com/pola-rs/polars/pull/5759/files

**Comment by mhattingpete** [comment]
I can give this a try

**Comment by josemasar** [comment]
I´d like to give it a try as well. From all good first issues, it´s the most affordable for me.
