### ISSUE TITLE
API: rename with_time_zone to convert_time_zone

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6767]
### Problem description

The current methods for working with time zones are:
- `with_time_zone`: convert from one time zone to another
- `cast_time_zone`: set/unset/change time zone

The second one is clear enough, but the first one seems to regularly cause confusion.

As the next release will already see some changes to the API (deprecating tz_localize), why not go all the way and rename `with_time_zone` to `convert_time_zone`?

**Comment by alexander-beedie** [comment]
Maybe one of them should be called `replace_time_zone`? Even staring right at `cast` or `convert` (or `with`) I'm still not _completely_ sure I know what's going to happen when I call them. 

The word "replace" would clarify it? You're taking any datetime (tz-aware or not) and _replacing_ the current timezone with a new value, eg:

```python
# replace naive (None) timezone with GMT
2023-01-01 12:30:45      => `2023-01-01 12:30:45 GMT

# replace existing timezone with GMT
2023-01-01 12:30:45 CET` => `2023-01-01 12:30:45 GMT
```

**Comment by ritchie46** [comment]
I agree with @alexander-beedie on this one. I had the same question, how do `cast` and `convert` differ.

If we go for `replace`/ `convert` I also think we should specifically state in the docs that the old time zone is ignored.

**Comment by stinodego** [comment]
I don't think `replace` is correct, because it implies that there is already a timezone present. But it also works when there is no timezone.

`set_time_zone` makes more sense to me.

**Comment by MarcoGorelli** [comment]
that's a good point, although even `set_time_zone` might not be 100% accurate, as it works to unset a timezone too. I think replace might be accurate enough

> I am reading the current docs and doc examples and honestly I can't make out what is happening for either method.

😆 does this help https://github.com/pola-rs/polars-book/pull/234 ?

**Comment by alexander-beedie** [comment]
> I don't think `replace` is correct, because it implies that there is already a timezone present. But it also works when there is no timezone?

Yup; and it would be completely consistent with Python behaviour, where a naive datetime can be considered equivalent to a datetime with `tzinfo=None`, and you can replace that None with a real timezone - this consistency is one of the reasons I thought `replace_` might be good (though I also like `set_` - both would work for me) ;)

```python
from datetime import datetime
from zoneinfo import ZoneInfo

d = datetime(2021,1,1,12,30,45)
dtz = d.replace( tzinfo=ZoneInfo('Asia/Tokyo') )

d
# datetime.datetime(2021, 1, 1, 12, 30, 45)
dtz
# datetime.datetime(2021, 1, 1, 12, 30, 45, tzinfo=ZoneInfo('Asia/Tokyo'))
```

**Comment by stinodego** [comment]
> it would be completely consistent with Python behaviour, where a naive datetime can be considered equivalent to a datetime with `tzinfo=None`, and you can replace that None with a real timezone (this consistency is one of the reasons I thought `replace_` might be good

Sounds good enough to me, thanks for the explanation!

**Comment by deanm0000** [comment]
I like with_time_zone as it is consistent R's lubridate::with_tz.  If that's not compelling enough then how about doing `as_timezone` to be consistent with python datatime's native astimezone.  Of course there's also a reason why with_time_zone was chosen in the first place.

**Comment by sorhawell** [comment]
I also like the renaming, because cast/with meant the opposite for x_time_zone than for x_time_unit which was confusing.
