### ISSUE TITLE
Consider using master of phsym/prettytable-rs

### ISSUE THREAD

**Issue by roee88** [pola-rs/polars#677]
polars depends on the last release of prettytable-rs (v0.8.0). However, this version does not compile to wasm-wasi target while the master version does.

## Details

The reason is that 0.8.0 depends on `term 0.5` which itself depends on `dirs 1.x` that is incompatible with webassembly. However, the master version of `prettytable-rs` depends on `term 0.6` which uses `dirs 2.x` that actually works with wasm-wasi. 

## Proposed change

I changed https://github.com/pola-rs/polars/blob/ecaccc6564fc0499a687eb66623d79d9d390a86a/polars/polars-core/Cargo.toml#L68 to:

```toml
prettytable-rs = { version="0.8.0", optional = true, git = "https://github.com/phsym/prettytable-rs", branch = "master"}
```

I then compiled a sample application to the wasm32-wasi target. Running it with wasmer printed the formatted table. 

## Alternatives 

1. Unfortunately prettytable-rs seems unmaintained so if it has an important role in polars then it might be worth to fork it and update its dependencies
2. Don't do anything and let users figure it out and patch (or maybe add some note in the documentation)
    ```toml
    [patch.crates-io]
    prettytable-rs = { git = "https://github.com/phsym/prettytable-rs", branch = "master"}
    ```

**Comment by ritchie46** [comment]
I believe that if we point to the github branch that I cannot push to `crates.io` anymore. For this reason I am more inclined to adding a `patch` example to the documentation. What do you think?

**Comment by roee88** [comment]
That would be very useful

**Comment by roee88** [comment]
I would be more explicit in the docs about the target. 
Printing doesn't work on `wasm32-unknown-unknown`, it only applies to `wasm32-wasi`.

**Comment by ritchie46** [comment]
Sorry, I am not that familiar with wasm targets, is `wasm32-unknown-unknown` the same as `wasm32-wasi`?

**Comment by roee88** [comment]
Rust supports different wasm targets*:
* `wasm32-unknown-emscripten` generates wasm and js to be used in a browser.
* `wasm32-wasi` generates standalone wasm with system interface support (so things like print works). This is what is usually used for running wasm outside the browser (with tools such as wasmer, wasmtime, wavm, ...) although it can also be used from within the browser. See https://docs.wasmer.io/integrations/js/wasi and https://wasi.dev/.
* `wasm32-unknown-unknown` generates standalone wasm but without support for the system interface. 


\* disclaimer: I'm no expect in wasm and the above reflects my current knowledge (i.e., I could be wrong).

**Comment by roee88** [comment]
BTW excluding avx512 all features of polars-core can be enabled and it would still compile to wasm32-wasi. It requires https://github.com/apache/arrow-rs/pull/324 and the patching of prettytable-rs though. 

For polars-lazy the csv-file feature must be changed to optional before it compiles. I did a quick compile check by adding `#[cfg(feature = "csv-file")]` where it's used (similar to parquet) and removing Default trait for LogicalPlan because it used CsvScan. I didn't try to run anything though.

**Comment by ritchie46** [comment]
> Rust supports different wasm targets*:
    wasm32-unknown-emscripten generates wasm and js to be used in a browser.
    wasm32-wasi generates standalone wasm with system interface support (so things like print works). This is what is usually used for running wasm outside the browser (with tools such as wasmer, wasmtime, wavm, ...) although it can also be used from within the browser. See https://docs.wasmer.io/integrations/js/wasi, https://wasi.dev/, https://nodejs.org/api/wasi.html, etc..
    wasm32-unknown-unknown generates standalone wasm but without support for the system interface.

> * disclaimer: I'm no expect in wasm and the above reflects my current knowledge (i.e., I could be wrong).

Right, Thanks for the braindump! 

> For polars-lazy the csv-file feature must be changed to optional before it compiles. I did a quick compile check by adding #[cfg(feature = "csv-file")] where it's used (similar to parquet) and removing Default trait for LogicalPlan because it used CsvScan. I didn't try to run anything though.

I will make sure that's wasm compatible as well.
