### ISSUE TITLE
Unable to use numpy ufunc with multiple `pl.col()` expressions 

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#6770]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not entirely sure if this is supposed to work or not but:

After seeing ["How do I use numpy.arctan2 within a polars dataframe?"](https://stackoverflow.com/questions/75392946/how-do-i-use-numpy-arctan2-within-polars-dataframe) on stackoverflow, I initially thought this would work:
```
df.select(np.arctan2(pl.col("v"), pl.col("u")))
```
However what this appears to execute is:
```
np.arctan2(pl.col("v"), pl.col("v"))
```
i.e. it seems to pass column `v` twice to the function instead of `v` and `u`

### Reproducible example

```python
import numpy as np
import polars as pl

df = pl.DataFrame({
   "v": [-4.293,-2.4659,-1.8378,-0.2821,-4.5649,-3.8128,-7.4274,3.3443,3.8604,-4.2200],
   "u": [-11.2268,6.3478,7.1681,3.4986,2.7320,-1.0695,-10.1408,11.2327,6.6623,-8.1412]
})

np.arctan2(df.get_column("v"), df.get_column("u"))

"""
shape: (10,)
Series: 'v' [f64]
[
	-2.77636
	-0.370523
	-0.25098
	-0.080458
	-1.031495
	-1.844271
	-2.509433
	0.289372
	0.525164
	-2.663372
]
"""

# Differs
df.select(np.arctan2(pl.col("v"), pl.col("u")))

"""
shape: (10, 1)
┌───────────┐
│ v         │
│ ---       │
│ f64       │
╞═══════════╡
│ -2.356194 │
│ -2.356194 │
│ -2.356194 │
│ -2.356194 │
│ -2.356194 │
│ -2.356194 │
│ -2.356194 │
│ 0.785398  │
│ 0.785398  │
│ -2.356194 │
└───────────┘
"""

# It appears the above is passing `v` as both arguments:
np.arctan2(df.get_column("v"), df.get_column("v"))

"""
shape: (10,)
Series: 'v' [f64]
[
	-2.356194
	-2.356194
	-2.356194
	-2.356194
	-2.356194
	-2.356194
	-2.356194
	0.785398
	0.785398
	-2.356194
]
"""
```

### Expected behavior

From the docs - it seems like it should work and produce the same output as `np.arctan2(df.get_column("v"), df.get_column("u"))` - but perhaps I'm mistaken.

Thank you.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Python: 3.10.9 (main, Jan 14 2023, 16:56:26)
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by deanm0000** [comment]
It might be technically a bug that it isn't giving you an error but it is "normal" behavior that you can't just do `np.arctan2(pl.col("v"), pl.col("v"))`

The documented way to do it is with a `reduce` like this: `df.select(pl.reduce(np.arctan2, [pl.col('v'), pl.col('u')]))`

**Comment by cmdlineluser** [comment]
@deanm0000 Ah - first time seeing `pl.reduce` being used.
 
So you could also use `["v", "u"]` as the exprs `df.select(pl.reduce(np.arctan2, ["v", "u"]))` - really interesting stuff.

Thank you for the example.

**Comment by zundertj** [comment]
Passing in multiple expressions into numpy ufunc is not supported indeed. I recently fixed the case where the expression comes in as the second argument, rather than first, but I agree it is not clear. So we can either raise an error, or try to see if we can do the reduce trick behind the scenes. Let me have a think.

**Comment by cmdlineluser** [comment]
Thank you for the clarification @zundertj

**Comment by cmdlineluser** [comment]
completed in https://github.com/pola-rs/polars/pull/6821

**Comment by zundertj** [comment]
I have added support for this in #7924.

**Comment by cmdlineluser** [comment]
Thanks for the update @zundertj - a very useful addition.
