### ISSUE TITLE
polars.Series.str.starts_with to support multiple inputs

### ISSUE THREAD

**Issue by eerhil** [pola-rs/polars#6778]
### Problem description

It would be nice if we could pass a tuple to polars.Series.str.starts_with the same way that it is possible [in Pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.startswith.html).

Consider the following scenario, where you want to filter a dataframe based on whether the values in a column start with either "abc" or "cde":

`df.filter((pl.col("col_name").str.starts_with("abc")) | (pl.col("col_name").str.starts_with("cde")))`

With tuple support, the query could be simplified as follows:

`df.filter(pl.col("col_name").str.starts_with(("abc", "cde")))`

Would this make sense to you?

**Comment by alexander-beedie** [comment]
Not a bad idea...
FYI: you can also get the same effect by using `contains` with a suitable pattern:
```python
import polars as pl

df = pl.DataFrame({
    "x": ["aaa","bbb","ccc","ddd","eeee"]
})
df.filter( pl.col("x").str.contains("^(a|d)") )
# ┌─────┐
# │ x   │
# │ --- │
# │ str │
# ╞═════╡
# │ aaa │
# │ ddd │
# └─────┘
```

**Comment by eerhil** [comment]
Yeah, thanks! I'll try which syntax suits my use case the best.

**Comment by henryharbeck** [comment]
A few thoughts to add.

As well as pandas, python itself also supporting passing a tuple to `str.startswith` and `str.endswith`

I think it would be worth completing this on `str.starts_with`, `str.ends_with` and `str.contains` as a minimum.
Implementing this would remove the need to defer to `contains` when you really want a `starts_with` or `ends_with`.

Perhaps it would also be worthwhile for other methods with string pattern matching like `str.replace` and `str.replace_all` (and others I may be missing). For example, if you wanted to replace more than one pattern with a single value (without needing to put pipes in your regex).

I've come up against this today where I have a sequence of patterns to match
```python
# simple for the sake of example, could be quite large and/or externally defined
patterns_to_match = ("A", "B", "C")
```
and I chose `pl.col("col_name").str.contains("|".join(patterns_to_match))` as the nicest solution
when I would have rathered `pl.col("col_name").str.contains(patterns_to_match)` and not used a python string method to construct a regex

**Comment by avimallu** [comment]
Not a feature add, but a potential solution to avoid using a Python method to evaluate your regex using Polars:

```py
df = pl.DataFrame({
    "G": ["A", "B", "C", "B", "B", "A", "D"]
})
patterns_to_match = ("A", "B", "C")
(
    df
    .with_columns(
        pl.any([pl.col("G").str.contains(x) for x in patterns_to_match]))
)
```

creates expressions using Python methods, so the actual heavy evaluations are done using just Polars.

**Comment by stinodego** [comment]
It's easy enough to write a utility function to do this and use `pipe`, or use `contains` with a suitable regex. I do not think this is worth supporting.

**Comment by Wainberg** [comment]
@stinodego it just occurred to me that the corresponding selectors - [cs.starts_with()](https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html#polars.selectors.starts_with), [cs.ends_with()](https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html#polars.selectors.ends_with) and [cs.contains()](https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html#polars.selectors.contains) - already support multiple inputs. Do you think the inconsistency is problematic?
