### ISSUE TITLE
Cant create DataFrame when empty list in dict

### ISSUE THREAD

**Issue by PieReissyet** [pola-rs/polars#6783]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Cant create `DataFrame` when one of the `dict` value is an empty `list` even if casted as `pl.Object`.

It seems to be working fine when using `pl.Struct` datatype but `dict` keys are not consistant across all rows so I need to cast this as Object and process everything after once it's loaded.

### Reproducible example

```python
import polars as pl
for empty_val in [None, '', {}, []]:
    test = [{"field":{ "sub_field": empty_val, "sub_field_2": 2}}]
    df = pl.DataFrame(test, schema={"field": pl.Object})
    print(f'works for {empty_val}')
```

### Expected behavior

To successfully load the data in a `DataFrame` for all `empty_val` values.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by romanovacca** [comment]
Just to add to this, the error produced by the example provided is:
`thread '<unnamed>' panicked at 'to_list not implemented for null/unknown'`

Which comes from
`src/series.rs:708:25`

Where we have:
```
DataType::Null | DataType::Unknown => {
                        panic!("to_list not implemented for null/unknown")
                    }
```

Is this a nice first first good issue for me to pick up @ritchie46 ?
