### ISSUE TITLE
Performance regression in `polars.PySeries.new_opt_f64`

### ISSUE THREAD

**Issue by jakob-keller** [pola-rs/polars#6791]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

We run an internal benchmark to flag possible performance regressions as part of testing new polars releases. Starting with 0.16.2, I noticed a significant performance regression that affects calls to low-level `polars.PySeries.new_opt_f64`.

I prepared a minimal, synthetic benchmark for your reference. On my machine (Apple M2 Pro) performance degrades by ~50%.

It appears as if `new_opt_f64` is implemented in Rust, which I am not familiar with.

### Reproducible example

```python
polars==0.16.2 or polars==0.16.3


python3 -m timeit -n 500000 -s "import polars as pl; values = tuple(i / 0.123 for i in range(100))" "pl.polars.PySeries.new_opt_f64('test', values, True)"

500000 loops, best of 5: 1.21 usec per loop
```

`Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin`
```


### Expected behavior

polars==0.16.1

```
python3 -m timeit -n 500000 -s "import polars as pl; values = tuple(i / 0.123 for i in range(100))" "pl.polars.PySeries.new_opt_f64('test', values, True)"

500000 loops, best of 5: 821 nsec per loop
```

`Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin`

### Installed versions

<details>

```
---Version info---
Polars: 0.16.3
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
That's strange. I don't believe we changed code that relates to that.

**Comment by jakob-keller** [comment]
> You already experienced this in our `0.16.2` upgrade? We updated pyo3 in that release.

Correct, the regression occurred in 0.16.2.

**Comment by ritchie46** [comment]
I have opened an issue upstream: https://github.com/PyO3/pyo3/issues/2943

Though the regression is likely only in very short function calls. I expect the code that fills the buffers not to be slower.

**Comment by jakob-keller** [comment]
Thank you for such a quick response: `polars 0.16.4` is definitely an improvement:

```
python3 -m timeit -n 500000 -s "import polars as pl; values = tuple(i / 0.123 for i in range(100))" "pl.polars.PySeries.new_opt_f64('test', values, True)"

500000 loops, best of 5: 1.01 usec per loop
```

That measurement falls right in the middle between 0.16.1 and 0.16.2/0.16.3.

Is there any more room for speed ups, restoring performance to the level of 0.16.1? I know this is a very specific edge case, but we call this function at a rate of ~10k per second per CPU core in production and it's pretty latency sensitive.

**Comment by ritchie46** [comment]
We only updated pyo3 and didn't change code, so I cannot tell if this can be expected or not.

I tune in @adamreichold maybe he knows if this can be expected.

**Comment by adamreichold** [comment]
I am not aware of any specific change which would affect this code, however the update in question bumped two major PyO3 versions so there are a lot of changes and the magnitude of the difference (200 ns if I understand this issue correctly) means that even unfortunate machine code generation decisions by the compiler or distributed fat from fixing soundness issues like https://github.com/PyO3/pyo3/pull/2687 in PyO3 might be involved.

@ritchie46 Could you point at the Rust implementation of the `new_opt_f64` method so that I could have a look at the specific code in question?

@jakob-keller If you are really really really limited by this, it might make sense look into a custom build of py-polars which for example does not use the limited CPython API which _can_ be faster but is also bound to a specific CPython version.

**Comment by jakob-keller** [comment]
> @jakob-keller If you are really really really limited by this, it might make sense look into a custom build of py-polars which for example does not use the limited CPython API which _can_ be faster but is also bound to a specific CPython version.

Thanks for looking into this. I may have overstated the importance: This is only one of numerous latency sensitive code paths in our use case. Going down the road of a custom built is not something I am open to, but thanks for the suggestion.

In general, I have learned the hard way that polars performance **in our use case** varies strongly between releases, hence the need for regression testing on our end. Oftentimes, I am able to work around what I perceive as low-level regressions by refactoring our code. This time, that was impossible, which lead to this issue.

**Comment by adamreichold** [comment]
> Could you point at the Rust implementation of the new_opt_f64 method so that I could have a look at the specific code in question?

If we are talking about https://github.com/pola-rs/polars/blob/c060befa1365d886710b0e04bdec36dafd77c764/py-polars/src/series.rs#L157 with `T == f64`, then I don't think this has any obvious issues related to its usage of PyO3's API. One would have to profile this in detail to figure out where the time is spent.

It could most likely be made faster for specific types, e.g. trying to downcast to `PyTuple` and then using `PyTuple::as_slice` as a fast path if one wants to make exactly tuples as inputs faster. But this comes with an increased maintenance cost and carries the danger of the resulting code bloat actually decreasing performance in the general case.

Taking a step back, I wonder whether fine-grained calls from Python into a Rust library which actually has an idiomatic Rust API are the best approach when 200 ns overhead per call are unpalatable. For example, more coarse-grained interop between domain-specific Rust code using Polars' Rust API exposed as extension module might be able to side step a lot of inefficiencies imposed by the language boundary.

**Comment by ritchie46** [comment]
> with T == f64, then I don't think this has any obvious issues related to its usage of PyO3's API. One would have to profile this in detail to figure out where the time is spent.

Yeap, that's what we are talking about. 

If we're writing relative idiomatic performant code, I think 200 ns is acceptable for crossing the language boundary. If there was something obvious we could have fixed it, but there isn't, so I think this is fine.

Thanks for the help @adamreichold
