### ISSUE TITLE
Performance regression from 0.16.2 to 0.16.3

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#6794]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Running the same program with version 0.16.2 is at least 5x faster than with version 0.16.3.

### Reproducible example

```python
# variant1: install latest
mamba create -y -n test_slow python=3.9
conda activate test_slow
pip install polars[numpy,pandas,pyarrow] numpy

# variant2: performant version
mamba create -y -n test_fast python=3.9
conda activate test_fast
pip install polars[numpy,pandas,pyarrow]==0.16.2 numpy
```

example.py:
```python
import numpy
import polars

numpy.random.seed(42)


df_size = 10**5

df = polars.DataFrame({"idx": range(0, df_size), "col1": numpy.random.randint(1, 1_000, df_size)})

def get_idx_where_first_value_greater(df):
    for row in df.iter_rows():
        idx = row[0]
        (df[idx, 1] < df[idx:, 1]).arg_max()

get_idx_where_first_value_greater(df)
```
Run the example to get timings: 
`time python example.py`

### Expected behavior

The above example takes about 6s with 0.16.2 and 31s with 0.16.3

### Installed versions

<details>
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.21.4
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
</details>

**Comment by ghuls** [comment]
py-spy seems to indicate that is is due arg_max

```
Total Samples 7500
GIL: 0.00%, Active: 0.00%, Threads: 3

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)                                                          
  0.00%   0.00%   29.46s    29.46s   arg_max (polars/internals/series/series.py:2048)
  0.00%   0.00%    1.46s     1.53s   collect (polars/internals/lazyframe/frame.py:1145)
  0.00%   0.00%    1.29s     1.35s   _comp (polars/internals/series/series.py:462)
  0.00%   0.00%   0.210s    0.230s   select (polars/internals/lazyframe/frame.py:1687)
  0.00%   0.00%   0.200s    36.72s   get_idx_where_first_value_greater (<ipython-input-1-ec7f3782b293>:14)
  0.00%   0.00%   0.150s    0.150s   dtype (polars/internals/series/series.py:337)
  0.00%   0.00%   0.140s     3.71s   wrapper (polars/internals/series/utils.py:98)
  0.00%   0.00%   0.140s     2.89s   select (polars/internals/dataframe/frame.py:5732)
  0.00%   0.00%   0.140s    0.180s   __subclasscheck__ (typing.py:774)
  0.00%   0.00%   0.130s    0.210s   selection_to_pyexpr_list (polars/internals/expr/expr.py:68)
  0.00%   0.00%   0.120s    0.120s   maybe_cast (polars/datatypes.py:801)
  0.00%   0.00%   0.120s    0.130s   _check_for_numpy (polars/dependencies.py:179)
  0.00%   0.00%   0.110s    0.110s   to_frame (polars/internals/series/series.py:1110)
  0.00%   0.00%   0.110s    0.110s   select (polars/internals/lazyframe/frame.py:1681)
  0.00%   0.00%   0.100s    0.150s   to_series (polars/internals/dataframe/frame.py:2069)
  0.00%   0.00%   0.100s    0.100s   _slice_setup (polars/internals/slice.py:52)
  0.00%   0.00%   0.090s    0.090s   collect (polars/internals/lazyframe/frame.py:1136)
  0.00%   0.00%   0.090s    0.150s   lit (polars/internals/lazy_functions.py:1177)
```

**Comment by cmdlineluser** [comment]
On `0.16.3` htop is reporting `115%` cpu usage.

Running under a previous version reports `385%` cpu usage.

Something seems to have changed which affects cpu cores utilization?

**Comment by jmakov** [comment]
> On `0.16.3` htop is reporting `115%` cpu usage.
> 
> Running under a previous version reports `385%` cpu usage.
> 
> Something seems to have changed which affects cpu cores utilization?

Running like this, the 0.16.2 version is still at about 5.5s:
`export POLARS_MAX_THREADS=1 && time python test.py`

**Comment by ritchie46** [comment]
Thanks for the breakdown! Was an easy fix now. I accidentally removed `arg_min/max` specializations for boolean values. I will also optimize a bit, now I am there.

**Comment by jmakov** [comment]
When I run the above example with ` export POLARS_MAX_THREADS=1 && time python test.py` I get about 5s for 0.16.2 and 6.3s for 0.16.4. Close enough, tnx!

**Comment by jmakov** [comment]
To leave it here, this seems to have an optimized version for `.arg_max/min`. Would be interesting to compare the two implementations: https://github.com/jvdd/argminmax
