### ISSUE TITLE
YYYY week into a date

### ISSUE THREAD

**Issue by Bidek56** [pola-rs/polars#6796]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Attempting to parse YYYY week into date results in an error: `ComputeError: strict conversion to dates failed, maybe set strict=False`

```
import polars as pl
pl.DataFrame(
{
 "week": [201901, 201902, 201903, 201942, 201943, 201944]
}).with_columns(pl.col('week').cast(pl.Utf8).str.strptime(pl.Date, fmt='%Y%U').alias("date"))
```

According to the Rust [Chrono](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) specifiers, %U is supported.

Pandas can read it: `df['date'] = pd.to_datetime(df.week.astype(str) + '0', format='%Y%W%w')`

Thanks to [SO](https://stackoverflow.com/questions/75416108/polars-yyyy-week-into-a-date#75416513), I have found a workaround but I think it's a bug.

### Reproducible example

```python
import polars as pl
pl.DataFrame(
{
 "week": [201901, 201902, 201903, 201942, 201943, 201944]
}).with_columns(pl.col('week').cast(pl.Utf8).str.strptime(pl.Date, fmt='%Y%U').alias("date"))
```

### Expected behavior

<html>
<body>

date
--
2019-01-01
2019-01-08
2019-01-15
2019-10-15
2019-10-22
2019-10-29

</body>
</html>

### Installed versions

<details>

```
---Version info---
Polars: 0.16.3
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by MarcoGorelli** [comment]
Hi @Bidek56 

Looks like this doesn't quite work in chrono:
```rust
use chrono::{NaiveDate};

fn main() {
    let date_str = "201901";
    let naive_date = NaiveDate::parse_from_str(date_str, "%Y%U").unwrap();
    println!("{:?}", naive_date);
}
```

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NotEnough)', src/main.rs:5:66
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021#)
```

I think it also requires you to pass the day of the week, e.g.
```rust
    let date_str = "201901Mon";
    let naive_date = NaiveDate::parse_from_str(date_str, "%Y%U%a").unwrap();
```
compiles fine

**Comment by Bidek56** [comment]
Does the code below work for you? b/c "%Y%U%a" works but not "%Y%W%a" but the [docs ](https://docs.rs/chrono/latest/chrono/format/strftime/index.html)says that it should.
```
    let date_str = "201901Mon";
    let naive_date = NaiveDate::parse_from_str(date_str, "%Y%W%a").unwrap();
```

**Comment by FObersteiner** [comment]
I think YYYY-WW is just not a precise date, for example if you look at the [ISO week date definition](https://en.wikipedia.org/wiki/ISO_week_date). That's why you need to specify the day of the week. Although one might think that with the week number only, it should default to a certain date.

So I'd conclude this is not a bug but a feature to avoid ambiguity. Only the chrono docs could be a bit more specific here.

**Comment by FObersteiner** [comment]
> Does the code below work for you? b/c "%Y%U%a" works but not "%Y%W%a" but the [docs ](https://docs.rs/chrono/latest/chrono/format/strftime/index.html)says that it should.
> 
> ```
>     let date_str = "201901Mon";
>     let naive_date = NaiveDate::parse_from_str(date_str, "%Y%W%a").unwrap();
> ```

now this actually *does* look like a bug to me. Speculation: because week 1 of 2019 starts in 2018? `NaiveDate::parse_from_str("2019-01-1", "%G-%V-%u")` also works fine btw. (ISO week date specifiers).

**Comment by FObersteiner** [comment]
> Does the code below work for you? b/c "%Y%U%a" works but not "%Y%W%a" but the [docs ](https://docs.rs/chrono/latest/chrono/format/strftime/index.html)says that it should.
> 
> ```
>     let date_str = "201901Mon";
>     let naive_date = NaiveDate::parse_from_str(date_str, "%Y%W%a").unwrap();
> ```

I first thought this actually was a bug, but... if you have a look at the [calendar](https://www.timeanddate.com/calendar/?year=2019&country=9), you can observe that the first Monday (`%W`) is ambiguous if you have naive date(time), i.e. without a time zone. Depending on the time zone, it could fall into 2018... On the other hand no such issue with the first Sunday ( `%U`). So I'd say again, not a bug but a feature.

**Comment by Bidek56** [comment]
Hmmm, I wonder why` "%Y%W%a"` works for you in Rust but it does not work in Python.

**Comment by FObersteiner** [comment]
@Bidek56 sorry, that was a bit unclear. `%W` doesn't work for me either. Here's a [playground example]().

In Python, both `%U` and `%W` work, but give the same result if you set the weekday to 1 ?!
```py
from datetime import datetime

print(datetime.strptime("2019-01-0", "%Y-%U-%w"))
# 2019-01-06 00:00:00
print(datetime.strptime("2019-01-0", "%Y-%W-%w"))
# 2019-01-13 00:00:00

print(datetime.strptime("2019-01-1", "%Y-%U-%w"))
# 2019-01-07 00:00:00
print(datetime.strptime("2019-01-1", "%Y-%W-%w"))
# 2019-01-07 00:00:00
```

It seem something strange is going on here; chrono errors out, and Python gives results that are unexpected for me. ISO week date parsing directives (`"%G-%V-%u"`) give consistent results though.

**Comment by Bidek56** [comment]
```
 let date = NaiveDate::parse_from_str("2019-01-0", "%Y-%W-%w")?;
```
Returns: Error: ParseError(Impossible)

But
```
let date = NaiveDate::parse_from_str("2020-01-0", "%Y-%W-%w")?;
```
Returns: 2020-01-12

**Comment by FObersteiner** [comment]
> ```
>  let date = NaiveDate::parse_from_str("2019-01-0", "%Y-%W-%w")?;
> ```
> Returns: Error: ParseError(Impossible)
> 
> But
> ```
> let date = NaiveDate::parse_from_str("2020-01-0", "%Y-%W-%w")?;
> ```
> Returns: 2020-01-12

Exactly. This seems somehow related to year 2019. But this polars issue is the wrong place to discuss I think. We should open an issue at chrono or a question on stackoverflow.

**Comment by Bidek56** [comment]
@FObersteiner I will close this ticket and look into Chrono instead. Thanks for your help.
