### ISSUE TITLE
Python async

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#6800]
### Problem description

Would be great if polars supported async everywhere. We use it in a web app with fastapi and I think we could increase throughput

**Comment by ritchie46** [comment]
Yeah, you know what you are asking? :wink: We are not going to do that. Polars does not have an async event loop as driver of parallelism/concurrency.

**Comment by aersam** [comment]
No I don‘t, honestly 😊 I only know that async is often an invasive thing in the code…
Ok, close it then, fine for me
