### ISSUE TITLE
.read_ndjson() gives error when reading formatted json

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#6804]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When reading a json file that is formatted it returns a PanicException:

`thread '<unnamed>' panicked at 'called ``Result::unwrap()`` on an ``Err`` value: ExternalFormat("InvalidEOF")', polars-io/src/ndjson_core/ndjson.rs:161:90`

So reading this works:

`{"Event":"org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart"}
`

but this doesnt:
```
{
   "Event":"org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart"
}

```

[formatted.json.zip](https://github.com/pola-rs/polars/files/10713122/formatted.json.zip)
[unformatted.json.zip](https://github.com/pola-rs/polars/files/10713123/unformatted.json.zip)

### Reproducible example

#doesn't work
pl.read_ndjson("formatted.json")

#works
pl.read_ndjson("unformatted.json") 

### Expected behavior

I would expect the formatting to not produce this error, and the function able to read in the data

### Installed versions

0.16.3

**Comment by ritchie46** [comment]
I don't think it is valid ndjson if it is formatted like that. After all it is nd.

**Comment by romanovacca** [comment]
You are right. Can we give back a custom error message here stating the file does not contain valid ndjson then?

**Comment by ritchie46** [comment]
Right, we should not unwrap the error, but bubble up. :+1:
