### ISSUE TITLE
Incorrect type when dividing literal series of `UInt64` with `Int64`.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6805]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

Floor division results to a float type, where Uint was expected.

### Reproducible example

```javascript
s = pl.Series(values=[1], dtype=pl.UInt64) 
pl.select(pl.lit(s) // 2)


```
shape: (1, 1)
┌─────┐
│     │
│ --- │
│ f64 │
╞═════╡
│ 0.0 │
└─────┘

```
```

### Expected behavior

```
shape: (1, 1)
┌─────┐
│     │
│ --- │
│ u64 │
╞═════╡
│ 0 │
└─────┘

```

**Comment by ghuls** [comment]
It is not limited to just `//`:

```python
In [11]: pl.select(pl.lit(s) + 0)
Out[11]: 
shape: (1, 1)
┌─────┐
│     │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘

In [12]: pl.select(pl.lit(s) * 0)
Out[12]: 
shape: (1, 1)
┌─────┐
│     │
│ --- │
│ f64 │
╞═════╡
│ 0.0 │
└─────┘

In [13]: pl.select(pl.lit(s) - 0)
Out[13]: 
shape: (1, 1)
┌─────┐
│     │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘
```

**Comment by ghuls** [comment]
Somehow the python integer is not cast to same dtype than the series, resulting in a `pl.UInt64 and pl.Int64 -> pl.Float64` conversion as which needs to happen when you would try to get the supertype of a `pl.UInt64` and `pl.Int64` series:
```python
In [21]: s1 = pl.Series(values=[1], dtype=pl.UInt64)

In [22]: s2 = pl.Series(values=[1], dtype=pl.Int64)

In [23]: s2 + 1
Out[23]: 
shape: (1,)
Series: '' [i64]
[
	2
]

In [24]: s1 + 1
Out[24]: 
shape: (1,)
Series: '' [u64]
[
	2
]

In [25]: s1 + s2
Out[25]: 
shape: (1,)
Series: '' [f64]
[
	2.0
]
```

**Comment by ritchie46** [comment]
Yes, I think I need to check the `type_coercion` optimizer to see if the literal fits into the `columns` dtype.
