### ISSUE TITLE
OutOfSpec("ListArray's child's DataType must match) when reading spark log file

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#6807]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When reading a auto generated spark log file, the above error is given when trying to read the file using .read_ndjson()

`PanicException: called ``Result::unwrap()`` on an ``Err`` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"nodeName\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"simpleString\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"metadata\", data_type: Struct([Field { name: \"\", data_type: Null, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]) while it got Struct([Field { name: \"nodeName\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"simpleString\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"metadata\", data_type: Struct([Field { name: \"\", data_type: Int8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]).")`

### Reproducible example

Below I added a MRE.

Note: the error occurs because of `{}` as value for `metadata`. However, this is how spark creates them in their logs.

`pl.DataFrame({"sparkPlanInfo":{"children":[{"children":[{"nodeName":"Filter","simpleString":"Filter (length(trim(value#0, None)) > 0)","metadata":{}  }]}]}} ) `

### Expected behavior

Question is if we want to be able to handle this, or if this is something that should be raised at spark.

### Installed versions

0.16.3

**Comment by cmdlineluser** [comment]
Just to add - it seems this exception is coming from `arrow2`
```
import io
import polars as pl

ndjson = """{"foo":{"bar":[{}]}}"""
pl.read_ndjson(io.StringIO(ndjson))
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec(...
```
```
/Users/user/.cargo
/registry/src/github.com-1ecc6299db9ec823
/arrow2-0.16.0/src/array/list/mod.rs:87:61
```
https://github.com/jorgecarleitao/arrow2/blob/main/src/array/list/mod.rs#L87

**Comment by s-b90** [comment]
Not sure if it is same behavior, so here is another example of this error:
```python
import polars as pl

pl.DataFrame([
    {'nested_structure': []},
    {'nested_structure': [{"value": 1, "value2": 2}]},
])

PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"value\", data_type: Int64, is_nullable: true, metadata: {} }]) while it got Struct([Field { name: \"value\", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: \"value2\", data_type: Int64, is_nullable: true, metadata: {} }]).")
```

**Comment by sorhawell** [comment]
uhh nice one, r-polars is happy :)

before a NULL(like python None) became aliased with a polars Null returning as an R NA
pl$lit(NULL)$to_r()
> NA

now all conversions are 1 to 1
pl$lit(NULL)$to_r()
> NULL
