### ISSUE TITLE
Addition of np.ndarray + pl.Series

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#6812]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I guess this is kind of a stupid issue, because why would you ever mix numpy arrays with polars Series? But I guess if it’s allowed, then it should be done right..

I give a few examples of strange behavior in the code below.

Example 1:
Pylance reports that `result_1` will have type `NDArray[bool_]`, but it is actually a Series.

Example 2:
Dtype depends on order of summands.

Example 3:
In this example, the array has length > 1.  
Now `array + Series` works, but `Series + array` raises ValueError.

### Reproducible example

```python
import numpy as np
import polars as pl

# Example 1
sx = pl.Series(values=[1, 1])
y = np.array([1.0])
result_1 = y + sx
print("Example 1:", type(result_1))

# Example 2
sx = pl.Series(values=[1, 1])
y = np.array([1.0])
left = sx + y
right = y + sx
print("Example 2:", left.dtype, right.dtype)

# Example 3
sx = pl.Series(values=[1, 1])
y = np.array([1, 1])
result_3 = y + sx
print("Example 3: sx + y works")
try:
    result_3 = sx + y
except ValueError as e:
    print("Example 3: sx + y gives this error.", e)

"""
Example 1: <class 'polars.internals.series.series.Series'>
Example 2: Int64 Float64
Example 3: sx + y works
Example 3: sx + y gives this error. Cannot convert Python type <class 'numpy.ndarray'> to Int64
"""
```

### Expected behavior

I'm not 100% confident about the intended behavior, but this is what I think.

Example 1:  
Ideally, the type checker would know the result is a Series.

Example 2:  
The result should have dtype `Float64` in either case.

Example 3:  
If `array + Series` is allowed, then `Series + array` should be allowed.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.4
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.2
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
@zundertj could you take a look at this one? It is all numpy on the pythgon side a I believe.

**Comment by zundertj** [comment]
The typing issue in example 1 we cannot do anything about, as it is the typing of the Numpy array, see for example https://github.com/numpy/numpy/issues/22064 .

For examples 2 & 3, what I have done in #6983 is to cast the Numpy array to a `pl.Series` for the common arithmetic operations. As you said, these operations are not commonly done, so expect some rough edges. But do keep reporting those, happy to cover more if it is reasonable.
