### ISSUE TITLE
scan_ipc with n_rows and filter applies the filter before the n_rows check

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#6831]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I ran into the same error as https://github.com/pola-rs/polars/issues/4608, which was fixed for `scan_csv`, but not `scan_ipc` (`scan_parquet` also works correctly). Since that issue is closed and I can't find another reference, I am opening this one.

The following code produces an empty dataframe when using `scan_csv/scan_parquet`, but with `scan_ipc` it returns two rows:

```python
import polars as pl

pl.Series("a", [0, 1, 2, 3]).to_frame().write_ipc(
    "test.ipc",
)

pl.scan_ipc("test.ipc", n_rows=2).filter(pl.col("a") >= 2).collect()

shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
│ 3   │
└─────┘
```

### Reproducible example

```python
import polars as pl

pl.Series("a", [0, 1, 2, 3]).to_frame().write_ipc(
    "test.ipc",
)

pl.scan_ipc("test.ipc", n_rows=2).filter(pl.col("a") >= 2).collect()
```

### Expected behavior

The output should be empty.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.4
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.8.12 (default, Oct 18 2021, 20:31:01) 
[Clang 10.0.1 (clang-1001.0.46.4)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.01.0
connectorx: 0.3.0
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2

```

</details>

**Comment by orlp** [comment]
I can't reproduce this anymore on the latest Polars so I think it got fixed along the way. Feel free to re-open with more detailed reproduction instructions / context if it's not fixed for you in the latest version.
