### ISSUE TITLE
Error converting `Series.to_numpy` with datetimes/nulls (regression from `0.16.2`)

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#6832]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Conversion of a Series of datetimes with some null values succeeds in `0.16.2`, but fails in `0.16.3` and `0.16.4` (without the null values the conversion succeeds as before).

### Reproducible example

```python
from datetime import datetime
import polars as pl

s = pl.Series("dt", [
    datetime(2022,7,5,10,30,45,123456),
    None,
    datetime(2023,2,5,15,22,30,987654),
])
s.to_numpy()

# ComputeError: 'to_numpy' not supported for dtype: 
#  Datetime(Microseconds, None)
```

### Expected behavior

Export to numpy array should succeed, as per `0.16.2`:
```python
array(['2022-07-05T10:30:45.123456','NaT',
       '2023-02-05T15:22:30.987654'], dtype='datetime64[us]')
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <version not detected>
matplotlib: 3.6.3```

</details>

**Comment by ritchie46** [comment]
I believe we accidentally don't dispatch via pyarrow anymore. For temporal logical types we need pyarrow for the conversion.

**Comment by alexander-beedie** [comment]
> I believe we accidentally don't dispatch via pyarrow anymore. For temporal logical types we need pyarrow for the conversion.

I think it's actually down to this change:

In 0.16.2:
```python
np_array = convert_to_date(self._s.to_numpy())
```
In 0.16.2:
```python
np_array = convert_to_date(self.view(ignore_nulls=True))
```

**Comment by ritchie46** [comment]
> ...so something inside `self._s.to_numpy()` appears to have changed thought_balloon

Yeap, I changed that. But we never converted datatimes to numpy datetimes there. I believe I changed in `self.to_numpy`.

**Comment by alexander-beedie** [comment]
> Yeap, I changed that. But we never converted datatimes to numpy datetimes there. I believe I changed in `self.to_numpy`.

Pretty sure we did; I can watch the code passing datetimes into that function and get the right values back (in `0.16.2`) or raise an error (in `0.16.4`) when debugging - the pyarrow check explicitly _omits_ datetimes from pyarrow conversion:
```python
if use_pyarrow and _PYARROW_AVAILABLE and not self.is_datelike():
```

It looks like the conversion is mediated via a floating point conversion:

v `0.16.2`
```python
a = s._s.to_numpy()
# array([1.65701705e+15, nan, 1.54938015e+15])

a.astype("datetime64[us]")
# array(['2022-07-05T10:30:45.123000','NaT',
#         '2019-02-05T15:22:30.121314'], dtype='datetime64[us]')
```
v `0.16.4`
```python
s._s.to_numpy()
# ComputeError: 'to_numpy' not supported for dtype...
```

**Comment by ritchie46** [comment]
So it automagically was just correct by using float types?

**Comment by ritchie46** [comment]
Got a fix!

**Comment by alexander-beedie** [comment]
> So it automagically was just correct by using float types?

Yup; which does seem suspect to me, as I'd be surprised if floating point was going to be completely accurate at nanosecond-level precision having been converted from i64, but this is definitely what was happening (I think we should probably first fix and then revisit this - I can assess the accuracy of the floating point conversion later by setting up some some parametric testing to go hunting for deviation).
