### ISSUE TITLE
`date_range` produces column `"literal"` instead of the `name` param

### ISSUE THREAD

**Issue by aguspdana** [pola-rs/polars#6843]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

`date_range` accepts `name` param but produces a column with name "literal".
```rust
use chrono::NaiveDate;
use polars::lazy::dsl::functions::date_range;
use polars::prelude::*;

fn main() {
    let df = LazyFrame::default()
        .with_column(date_range(
            String::from("timestamp"),
            lit(NaiveDate::from_ymd_opt(2022, 2, 1).unwrap().and_hms_opt(1, 0, 0).unwrap()),
            lit(NaiveDate::from_ymd_opt(2022, 12, 1).unwrap().and_hms_opt(0, 0, 0).unwrap()),
            Duration::parse("1mo"),
            ClosedWindow::Left,
            None
        ))
        .collect()
        .unwrap();
    
    println!("{}", df);
}
```

```
shape: (10, 1)
┌─────────────────────┐
│ literal             │
│ ---                 │
│ datetime[ns]        │
╞═════════════════════╡
│ 2022-02-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-03-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-04-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-05-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-09-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-10-01 01:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-11-01 01:00:00 │
└─────────────────────┘
```

### Reproducible example

[Rust Explorer](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Achrono%20%3D%20%22*%22%0Apolars%20%3D%20%7B%20version%20%3D%20%22*%22%2C%20features%20%3D%20%5B%22lazy%22%2C%20%22temporal%22%5D%20%7D%0A*%2F%0A%0Ause%20chrono%3A%3ANaiveDate%3B%0Ause%20polars%3A%3Alazy%3A%3Adsl%3A%3Afunctions%3A%3Adate_range%3B%0Ause%20polars%3A%3Aprelude%3A%3A*%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20df%20%3D%20LazyFrame%3A%3Adefault()%0A%20%20%20%20%20%20%20%20.with_column(date_range(%0A%20%20%20%20%20%20%20%20%20%20%20%20String%3A%3Afrom(%22timestamp%22)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20lit(NaiveDate%3A%3Afrom_ymd_opt(2022%2C%202%2C%201).unwrap().and_hms_opt(1%2C%200%2C%200).unwrap())%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20lit(NaiveDate%3A%3Afrom_ymd_opt(2022%2C%2012%2C%201).unwrap().and_hms_opt(0%2C%200%2C%200).unwrap())%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20Duration%3A%3Aparse(%221mo%22)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20ClosedWindow%3A%3ALeft%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20None%0A%20%20%20%20%20%20%20%20))%0A%20%20%20%20%20%20%20%20.collect()%0A%20%20%20%20%20%20%20%20.unwrap()%3B%0A%20%20%20%20%0A%20%20%20%20println!(%22%7B%7D%22%2C%20df)%3B%0A%7D)

### Expected behavior

It should produce a column with the name as given in the function params.

### Installed versions

<details>
lazy, temporal
</details>

**Comment by MarcoGorelli** [comment]
thanks @aguspdana for the report

`date_range` doesn't have a `name` argument anymore, so I don't think this needs addressing anymore https://pola-rs.github.io/polars/polars_lazy/dsl/functions/fn.date_range.html

closing then, but thanks for the issue
