### ISSUE TITLE
No SchemaError in lazy mode

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#6858]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following raises a SchemaError in eager mode as we are trying to round a pl.Utf8 column.

However, no SchemaError is raised in lazy mode until we execute.  

Similarly, if I try to call a .str namespace function on an integer column.

### Reproducible example

```python
import polars as pl

pl.DataFrame({'Name':['a','b']}).lazy().with_columns(pl.col('Name').round(2))

pl.DataFrame({'ints':[0,1]}).lazy().with_columns(pl.col('ints').str.to_lowercase())
```

### Expected behavior

I expected to get a SchemaError in lazy mode to avoid discovering this late in a pipeline run

### Installed versions

<details>

```
---Version info---
Polars: 0.16.4
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
Python: 3.10.1 (main, Dec 21 2021, 09:50:13) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.3```

</details>

**Comment by ritchie46** [comment]
LazyFrames will validate the logical plan upon collect, not earlier. This is still early in the pipeline run in compute time as nothing has been materialized yet.

**Comment by braaannigan** [comment]
Cheers @ritchie46, I'll add that to the docs
