### ISSUE TITLE
Indexing is still quite inconsistent

### ISSUE THREAD

**Issue by FlorianWilhelm** [pola-rs/polars#686]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

'0.7.17'

#### What operating system are you using polars on?

MacOS Big Sur

#### Describe your bug.

Similar to the solved issue #644, the indexing is still really confusing, i.e. it's not really clear when and where a column or a row is selected.

#### What are the steps to reproduce the behavior?

Column selection vs slice row selection:
```
  s = pl.Series("a", [1, 2, 3])
  df = pl.DataFrame({"a": [1, 2, 3], "b": [1.0, 2.0, 3.0]})
  # index by column
  assert df[0] == s
  assert df["a"] == s
  # but the following selects the first row! One would have expected to see the first column.
  assert df[:1] == pl.DataFrame({"a": [1], "b": [1.0]})
```

Also since version '0.7.17' `df[0, 1]` doesn't work any more and fails with
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-7654da449e6b> in <module>
----> 1 df[0, 1]

~/.miniconda3/envs/polars2/lib/python3.8/site-packages/polars/frame.py in __getitem__(self, item)
    529             # df[:, [1, 2]]
    530             # select by column indexes
--> 531             if isinstance(col_selection[0], int):
    532                 series = [self.select_at_idx(i) for i in col_selection]
    533                 df = DataFrame(series)

TypeError: 'int' object is not subscriptable
```
This worked in '0.7.16'.

These are only some of the inconsistencies I noticed using the indexing.

#### What is the expected behavior?

I think that if no tuple is provided, e.g. `df[0]`, `df[[0, 1]]` and `df[:1]`, one should always return rows. This is the same as Pandas' `iloc` would do if provided a single scalar, a list, or a slice. If a tuple is provided like `df[0,1]` a single element should be returned from the 0th row and 1st column. Since column have string names one should also be able to write `df[0,  "b"]` and of course also use lists as well as slices for making combinations possible like `df[[0,1], "b"]`, `df[0:, "b":]`, etc. possible. 

This would mean that one has to type `df[:, "a"]` to select a single column. I think this is fine as already Pandas showed that being inconsistent made it necessary to provide accessors like `iloc`, `loc`, `iat`, `at`, etc. to resolve ambiguities. Also to select a column one can already just use `select`. What do you think?

If you agree I can provide a PR implementing the described logic, also including a unit test as indexing doesn't really seem to have one right now. 

By experimenting around a bit with this I also noticed that there is a bug in the comparison operator, i.e. 
```
pl.DataFrame({"a": [1], "b": [1.0]}) == pl.DataFrame({"a": [1], "b": [1.0]})
```
returns False. I could also fix this.

**Comment by ritchie46** [comment]
> I think that if no tuple is provided, e.g. df[0], df[[0, 1]] and df[:1], one should always return rows. This is the same as Pandas' iloc would do if provided a single scalar, a list, or a slice. If a tuple is provided like df[0,1] a single element should be returned from the 0th row and 1st column. Since column have string names one should also be able to write df[0, "b"] and of course also use lists as well as slices for making combinations possible like df[[0,1], "b"], df[0:, "b":], etc. possible.

I agree with most of what you are proposing. If you can make a PR that would be great! 

There are already some indexing tests [here](https://github.com/pola-rs/polars/blob/2b05f35d6c09eb53b8280f49e262f96a3c082647/py-polars/tests/test_df.py#L33)

The only inconsistincy that I'd like to keep is being able to select columns on the first axis with strings; `df["foo"]` and `df[["foo", "bar"]]`. I believe that that in Polars still can make sense as Polars has no index, (and thus no named index).

So the indexing behavior should be:

* **numeric**
   - axis 0: row
   - axis 1: column
* **numeric + strings**
   - axis 0: row
   - axis 1: column
* **only strings**
   - axis 0: column
   - axis 1: error

**Comment by FlorianWilhelm** [comment]
Thanks for the fast reply. So the only difference is in:

* **only strings**
       * axis 0: column
       * axis 1: error

I agree that this would be possible as Polars only allows strings as column names (as opposed to Pandas) and the index is always an integer. Consequently, there should be no ambiguity. 

One more thing that came to my mind when I was thinking about all this. Why is there a `Series` datatype as a series basically is a dataframe with only a single column? This may sound like a stupid question but I never missed series in Spark and I have been using it for years in many projects. Am I missing a point?

Regarding the erroneous equality checks, can you give me pointer to what might be wrong there? I guess the equality of the objects is checked instead of the values compared. BTW, is the following behaviour wanted:
![image](https://user-images.githubusercontent.com/3184072/119240431-c3663d00-bb4f-11eb-8915-635a386c6065.png)
In the last command, I would have expected to get a dataframe returned with True/False values just like Numpy & Pandas would do it.

**Comment by ritchie46** [comment]
> One more thing that came to my mind when I was thinking about all this. Why is there a Series datatype as a series basically is a dataframe with only a single column? This may sound like a stupid question but I never missed series in Spark and I have been using it for years in many projects. Am I missing a point?

Series are the `Column` representation of a DataFrame. I believe spark is row based and does have a `Row` type. Polars memory is columnar and typed. The columns are represented by `ChunkedArray<T>` where `T` is generic over the available polars datatypes. A `Series` is a thin wrapper around a `ChunkedArrray<T>`, needed to be able to put them in a `DataFrame`.

> In the last command, I would have expected to get a dataframe returned with True/False values just like Numpy & Pandas would do it.

This is a side effect of the flawed indexing. Instead of `df[[0, 1]]` producing a `Series`, it produces a `value`, which is then the left hand side operand of the equality operation. This will be solved by indexing behavior as we discussed above.

**Comment by ritchie46** [comment]
@FlorianWilhelm I already fixed it, it bugged me too. I will push in a few minutes and patch a new release.

**Comment by FlorianWilhelm** [comment]
Ok, thanks. Maybe next time I am faster 😉

**Comment by FlorianWilhelm** [comment]
Regarding my serious, äh, series question (pardon my pun), I understand that internally a column-based structure like a series, i.e. `ChunkedArray<T>` is needed but isn't this just an implementation detail? I wonder if it should be exposed to the high-level user interface as for instance SQL returns a table even if you select a single column. Also R's `data.frame` seems to return a new `data.frame` when selecting a single column:
```
> emp.data <- data.frame(
+    emp_id = c (1:5),
+    emp_name = c("Rick","Dan","Michelle","Ryan","Gary"),
+    salary = c(623.3,515.2,611.0,729.0,843.25),
+
+    start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11",
+       "2015-03-27")),
+    stringsAsFactors = FALSE
+ )
> class(emp.data)
[1] "data.frame"
> class(emp.data["emp_name"])
[1] "data.frame"
```
While Spark has a `Row` data structure, they switched to a column-based memory layout for all I know and you really rarely use `Row` anymore and most likely shouldn't for the same reason you don't do `iter_rows` or `iter_typles` in Pandas. If you select a single column in Spark you also get a data frame with a single column, not some different data structure like a series.

So in total many libraries decided not to expose the implementation details of a series-like column-type to the end-user as there is not much benefit from it and only introduces extra complexity in the user interface. For me, Pandas was the first framework that had series and I always wondered in what sense it is better compared to a data frame with a single column. 

I would be interested in your reasons for having series as user-exposed data structures in Polars.

**Comment by ritchie46** [comment]
I believe spark is a bit more abstract. You can only communicate with the query engine and column you select may be row oriented, or column oriented somewhere on disk. I believe that Polars lazy or in expression context is already as you describe. A projection returns another `DataFrame`. 

I believe that it makes sense to have a `Series`/ `Column` abstraction. For instance you could check dynamically the type of a column and choose to do an operation accordingly. It also provides a great abstraction for user defined functions as you can use the API of Series in UDF contexts, being in projections, selections or aggregations.

**Comment by FlorianWilhelm** [comment]
Thanks for the explanation. I see the point that it is easier to define the datatype for a UDF working on a series.

I just checked version '0.7.17'. I think it's still inconsistent, in my notebook I have:

![image](https://user-images.githubusercontent.com/3184072/119358079-8c576f00-bca8-11eb-8bd9-3e527bce3a69.png)

Shouldn't `edf[1]` show the same as `edf[[1]]`?

**Comment by ritchie46** [comment]
Ah, I see I forgot about that one. The second behavior is as it should be. Are you still up for the PR? ;)

**Comment by FlorianWilhelm** [comment]
Yes :-) but it will take a couple of days if that's fine.

**Comment by FlorianWilhelm** [comment]
BTW, I also updated my [polars_vs_pandas notebook](https://github.com/FlorianWilhelm/polars_vs_pandas/blob/master/pl_vs_pd.ipynb). Removed the now unnecessary definition of the `udf` and extending the indexing section a bit more. Let me know if you have comments.
