### ISSUE TITLE
Add cartesian product

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#6863]
### Problem description

When finding a hacky solution for #6856 I realized there is no cartesian product method between two dataframes, which I can see would be quite useful in many circumstances, e.g. if you're building up a set of parameters to join a table against.

My hacky solution is the following is to add an extra column of all 0's to both dataframes, perform a full outer join (which matches all rows in left to all rows in right) then remove the extra column:

```python
def cartesian_product(df1, df2):
    """
    Create a fake column "tmp" on both dataframes and perform a full outer join in order to get the cartesian product
    of the two dataframes.
    """
    df1 = df1.lazy().with_columns(pl.lit(0, dtype=pl.UInt8).alias("tmp"))
    df2 = df2.lazy().with_columns(pl.lit(0, dtype=pl.UInt8).alias("tmp"))

    return df1.join(df2, on="tmp", how="outer").drop("tmp").collect()
```

...but this is a hacky workaround. What would be nice would be:

```python
df_prod = pl.cartesian_product([df1, df2, ..., dfn])
```

**Comment by gab23r** [comment]
`how='cross'` is what you are looking for

**Comment by mcrumiller** [comment]
Aha, there we go, thanks @gab23r.
