### ISSUE TITLE
write_parquet doesn't make row_groups based on chunks anymore.

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#6871]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is related to this feature request https://github.com/pola-rs/polars/issues/6859 but just wanted to point out what might be a bug separately.  I'm not sure what version was the first to have this behavior but at least in 0.16.2 write_parquet doesn't write row_groups corresponding to the chunks of the underlying dataframe.

### Reproducible example

```python
import polars as pl
import pyarrow.parquet as pq
```

Let's make a DataFrame and check n_chunks like this:

```
df=pl.DataFrame({'a':[1,2,3],'b':[2,3,4]}).vstack(pl.DataFrame({'a':[5,6,7],'b':[6,7,8]}))
df.n_chunks()
```

we get 2.

Now let's save it and check the row_groups with pyarrow.parquet

```
df.write_parquet("blah.parquet") 
pq.ParquetFile("blah.parquet").metadata.num_row_groups
```
On 0.16.2 we get 1 but on 0.15.11 we get 2 as expected.

Is this a feature or a bug?  If feature then need to update the docs.

### Expected behavior

I expected 0.16.2 to behave like 0.15.11 as described in the write_parquet docs.

> If None (default), the chunks of the DataFrame are used.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.9.15 (main, Nov 15 2022, 21:37:24) 
[GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>
```

and 

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by ritchie46** [comment]
Unset the `row_group_size` arg:

```python
df.write_parquet(f, row_group_size=None)
```
