### ISSUE TITLE
I suggest a html reading feature

### ISSUE THREAD

**Issue by elone240** [pola-rs/polars#6883]
### Problem description

I believe it would be useful if polars had a `.read_html` function similar to the function in pandas. This could make polars more used in different fields such as web scraping.

**Comment by zundertj** [comment]
Thank you for your suggestion. I think, though, that html parsing is out-of-scope for Polars, and best left to dedicated libraries like beatifulsoup and lxml, which is what Pandas is using internally anyways. What benefits would an integration have over calling a html parser separately? Also, please note that although Polars is similar to Pandas, both are DataFrame librariers after all, it is in no way meant to be a drop-in replacement for Pandas, so suggestions for new features will be judged based on their own merit.

**Comment by elone240** [comment]
Thanks! I’ll keep that in mind in the future.
