### ISSUE TITLE
`read_csv(parse_dates=True)` fails to parse datetimes with timezone offset

### ISSUE THREAD

**Issue by plaflamme** [pola-rs/polars#6886]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`pl.read_csv(..., parse_dates=True)` fails to parse timestamps with zone offset, but `pl.read_csv(..., use_pyarrow=True)` succeeds

### Reproducible example

```python
import polars as pl

csv = b"""datetimes
2023-01-15T08:00:00-05:00
2023-01-15T08:00:00+05
2023-01-15T08:00:00Z
"""

pl.read_csv(csv, parse_dates=True)
#shape: (3, 1)
#┌───────────────────────────┐
#│ datetimes                 │
#│ ---                       │
#│ str                       │
#╞═══════════════════════════╡
#│ 2023-01-15T08:00:00-05:00 │
#│ 2023-01-15T08:00:00+05    │
#│ 2023-01-15T08:00:00Z      │
#└───────────────────────────┘

pl.read_csv(csv,use_pyarrow=True)
#shape: (3, 1)
#┌─────────────────────────┐
#│ datetimes               │
#│ ---                     │
#│ datetime[ms, UTC]       │
#╞═════════════════════════╡
#│ 2023-01-15 13:00:00 UTC │
#│ 2023-01-15 03:00:00 UTC │
#│ 2023-01-15 08:00:00 UTC │
#└─────────────────────────┘
```

### Expected behavior

As with the `use_pyarrow` setting, I would expect `parse_dates=True` to properly parse the correctly formatted timestamps and harmonize the timezone to a common one (presumably `UTC`).

### Installed versions

<details>

```
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: Linux-5.19.0-31-generic-x86_64-with-glibc2.35
Python: 3.10.9 (main, Dec  6 2022, 18:44:57) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>

```

</details>

**Comment by MarcoGorelli** [comment]
Hey @plaflamme 

So, there's a few things going on here:

1. there's no common format with which to parse all your strings. `'%+'` would parse the first and third one, but not the second one

2. polars doesn't (yet!) auto-infer timezone-aware strings, so you'd need to specify a format

3. `read_csv` doesn't take any arguments for parsing dates - perhaps `datetime_format` would be added [like there will (hopefully) soon be in pandas](https://github.com/pandas-dev/pandas/pull/51019)?

4. "harmonize the timezone to a common one (presumably UTC)." would also require a `utc` parameter in `read_csv`

Bit concerned about feature creep here and not sure where to draw the line, will have a look at how much complexity these add.

For now, I'd suggest reading in as Utf-8 and then using a solution such as [this one](https://github.com/pola-rs/polars/issues/2716#issuecomment-1046311564) (or indeed, looks like pyarrow gives you what you want?)

**Comment by cmdlineluser** [comment]
@MarcoGorelli Does `%#z` help in this case?
```
pl.read_csv(csv).with_columns(
   pl.col("datetimes").str.strptime(
       pl.Datetime,
       fmt="%Y-%m-%dT%H:%M:%S%.f%#z",
       utc=True
))
```
```
shape: (3, 1)
┌─────────────────────────┐
│ datetimes               │
│ ---                     │
│ datetime[ns, UTC]       │
╞═════════════════════════╡
│ 2023-01-15 13:00:00 UTC │
│ 2023-01-15 03:00:00 UTC │
│ 2023-01-15 08:00:00 UTC │
└─────────────────────────┘
```

**Comment by plaflamme** [comment]
@MarcoGorelli Agreed, there are a few things to consider here:

1. IMO that's not a very important use-case. Files with this kind of structure are probably rare and would require special attention anyway. So not handling this is fine, but it probably merits being documented
2. this is the issue I'm having
3. the timestamps I have are actually ISO compliant, so I wouldn't need this, but I agree that this would be useful. IMO it should be `str | Dict[str, str] | None` so you could optionally specify a different format per column (say you have a `timestamp` column and a `date` column)
4. harmonizing to UTC is as good a timezone as any, and changing timezones is supported on `Series`; IMO it doesn't seem necessary to support this use case.

I'm using `use_pyarrow=True` for now which is fine, but my main concern is that `parse_dates=True` failed and there's really no way to know in code. Personally, I would have preferred a failure, so something like `parse_dates=["column_a", "column_b"]` (like pandas) would provide the ability to fail if it doesn't find a format. This is somewhat related to `3.` above where you could provide a format per column, it would fail if the format can't parse one of the values.

The API might be something like this:

* `date_format: str`: use this format to try to parse dates, if the format fails to parse a date, the value is left intact as a string
* `date_format: list[str]`: use these formats to try to parse dates, if all the formats fail to parse a date, the value is left intact as a string
* `date_format: Dict[str, str]`: specify a date format per column, if the format fails to parse a date, an error is raised
* `date_format: Dict[str, list[str]]`: specify multiple date formats to use to parse dates from specific columns, if all the formats fail to parse a date, an error is raised (IMO: this is pretty niche, but it fits in the API)

I couldn't come up with a way to replace `parse_dates=True`. `date_format=True` seems weird, maybe using a different name could help. In any case, ideally, this new argument would subsume `parse_dates` so that there's only one argument to use to do everything.

The only thing this ^ doesn't support is harmonizing to a timezone, which, as mentioned, doesn't seem particularly important to support as a first-class thing when parsing CSV.

**Comment by MarcoGorelli** [comment]
Been thinking about this more. Maybe `parse_dates` could be renamed to `try_parse_dates`, so then:
1. it would avoid being confused with `pandas`, where `pd.read_csv(..., parse_dates=True)` parses the index as datetime
2. it would prevent users from being surprised when their column isn't parsed as a date, as the name makes it clear that it only _tries_ to
