### ISSUE TITLE
cum_sum example request

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#689]
Hi;

I'm trying to calculate cum_sum in aggregation. But it throws error. Can you share an example showing how cumsum should be used in aggregation. I think that I'm missing something. Thanks for a fast package like this. It is as fast as data.table in R

`ozetData.with_column( pl.when(pl.col("passenger").is_null()).then(0.0).otherwise(pl.col("passenger")).cast(pl.Float32).alias("passenger") ) \
            .sort(["monthYearTravel","origcountry","purchase_date","monthFark"]) \
            .groupby(["monthYearTravel","origcountry"]).agg( pl.col("passenger").cum_sum() )`

> PanicException: operation cum_sum not supported for this dtype

**Comment by ritchie46** [comment]
What you are doing is correct. There was an implementation error. That is fixed in #691. 

I plan to release next week, but you could already compile from source if you need this.

> Thanks for a fast package like this. It is as fast as data.table in R

And you are welcome. :)

**Comment by ritchie46** [comment]
> I have another question. over method can take only one field. I can't manage to run an example having more than one field. Is it expected behaviour?

This is indeed not yet supported, but can trivially be added. Could you open a feature request for this? Then I will look into it.

**Comment by ritchie46** [comment]
Added in #691
