### ISSUE TITLE
InvalidArgumentError("It is not possible to concatenate arrays of different data types.") while creating DF with nested structure. 

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#6891]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Can not create DataFrame with column **List(Struct(List(Structure)))** when one of **List(Struct)** is empty

### Reproducible example

```python
import polars as pl
pl.DataFrame({'node_groups':
    [
        [{'nodes': [{'id': 1, 'is_started': True}]}],
        [{'nodes': []}],
    ]
})
PanicException: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("It is not possible to concatenate arrays of different data types.")
```

### Expected behavior
node_groups |
-- | 
list[struct[1]]| 
[{[{1,true}]}] | 
[{[]}] |

### Installed versions

<details>

```
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by alexander-beedie** [comment]
The two rows do technically resolve to slightly different schema (the inner type of one row is a `List[?]`, and the other is `List[Struct[...]]`), hence the error. Would be nice to resolve in favour of the schema supertype, but currently that isn't happening.

You can currently work around this by explicitly declaring your schema:
```python
import polars as pl
df = pl.DataFrame(
    {'node_groups':
        [
            [{'nodes': [{'id': 1, 'is_started': True}]}],
            [{'nodes': []}],
        ]
    },
    schema={'node_groups': 
        pl.List(
            pl.Struct([
                pl.Field('nodes', 
                    pl.List(
                        pl.Struct([
                            pl.Field('id', pl.Int64),
                            pl.Field('is_started', pl.Boolean)
                        ])
                    )
                )
            ])
        )
    }
)
```

**Comment by s-b90** [comment]
Didn't know that now we can declare the full schema.
Thank you!

**Comment by alexander-beedie** [comment]
> Didn't know that now we can declare the full schema.
> Thank you!

It's only been possible for about a month ;)
Ref: https://github.com/pola-rs/polars/pull/6145
