### ISSUE TITLE
Conditional selection of columns

### ISSUE THREAD

**Issue by pietz** [pola-rs/polars#6895]
### Problem description

I'm new to polars, so chances are high that I'm simply missing something. The application I'm building processes many different datasets and applies specific transformations based on "stuff" it finds in the data. This can be missing data, outliers, inconsistencies, whatever. It means that I want to conditionally select and modify columns without knowing their column names beforehand.

The docs state to use `select()` for selecting columns and `filter()` for selecting rows. However, it seems to me that these two have very different behaviors. `filter()` is mostly used for selecting rows conditionally, whereas `select()` is mostly used for indexing by name.

`df.select(pl.all().n_unique() < 100)`

This for example returns a DataFrame with n columns and 1 boolean row indicating if the column meets the condition. To actually select the columns we need to do some further `melt()` and `filter()` stuff that's not really nice to handle.

Polars does include a way of easily selecting columns that follow a certain regex pattern or have the same data type, but to my knowledge these are the only two examples for selecting columns conditionally. Why is that? How can I write my own condition?

**Something I'm missing from the API is a simple way to conditionally select columns.**

Am I overlooking something? This is easily and nicely done in the Pandas API.

**Comment by pietz** [comment]
I have a suggestion, which is probably stupid because I have been using polars for less than 3 days, but here it goes:

Introduce a `pl.cols()` function which represents an expression for selecting all available columns. The example from above would then look like this:

`df.select(pl.cols().n_unique() < 100)`

and actually return a DataFrame with all columns that are met by the condition.

**Comment by MarcoGorelli** [comment]
Hey - I don't know if there's an easier way, but I'd have done `df.select([col for col in df if col.n_unique()<100])`

**Comment by ritchie46** [comment]
> Polars does include a way of easily selecting columns that follow a certain regex pattern or have the same data type, but to my knowledge these are the only two examples for selecting columns conditionally. Why is that? How can I write my own condition?

Because these can be determined statically, e.g. they derive from the schema. What you want to to do derives from the data. That means there is no way to unify the lazy and eager API on this. You need to materialize the query plan to determine which columns are selected.

This is fine in eager. And can easily be done with a list comprehension, like @MarcoGorelli. 

If you want to ensure it runs in parallel you can do something like this:

```python
df.select([col.name for col in df.select(pl.all().n_unique() < 100) if col.item])
```

However in lazy this would be a shotgun to the foot as materializing just to determine which columns to select is very expensive. By not exposing a method for this, you might rethink your problem a bit, and if you don't the above list comprehensions are what you need.

**Comment by pietz** [comment]
@ritchie46  Yeah, I initially posted about my problem on [StackOverflow](https://stackoverflow.com/questions/75446886/selecting-columns-based-on-a-condition-in-polars/75447207). Another comment suggests this solution:

`df.select(pl.all().n_unique() < 100).melt().filter(pl.col("value"))["variable"]]`

Looks like this would work lazy correct? I still believe what I'm trying to do is a very "standard" use case that should have a nice and simple syntax. I would love for someone more experienced to rethink a possible API for my request. Maybe it's not half bad to set up an alias for `.melt().filter(pl.col("value"))["variable"]]`. What do you think? Does this translate to a performant expression?

**Comment by pietz** [comment]
I mean the more I think about it, the more I want to challenge the current behavior.

` df.select(pl.col(pl.Utf8))` selects all columns of type string. So the `pl.col(pl.Utf8)` bit basically translates to _all columns of dtype utf8_. `df.select(pl.col("x*"))` selects all columns that start with an "x". Same logic here. Now, suddenly when I write a condition it translates to a 1 row DataFrame of booleans. That's really not the behavior I would expect, honestly.

I would expect to receive a DataFrame filtered to those columns that meat the condition

**Comment by ritchie46** [comment]
You are conflating two things. Expression computation and expansion.

1. Computation

This is how you should primarily think about expressions. They are a computation over a column. So `pl.col("foo").unique()` gives you the unique values over column `"foo"`.

2. Expansion
`pl.col()` and `pl.all()` expressions can expand to multiple expressions. If your schema is `"a": Utf8, "b": Utf8, "c": Int32`, 

`pl.col(pl.Utf8).sum()` will expand to multiple separate expressions:

```python
pl.col("a").sum(),
pl.col("b").sum(),
```

After this expansion the **Computation** reasoning of **1.** applies again. This is in line with expectation as a computation **never** leads to expansion. Given schema, `a, b, c`, the expression `pl.all().n_unique() == 1` will expand on `pl.all()` to 

```python
pl.col("a").n_unique() == 1,
pl.col("b").n_unique() == 1,
pl.col("c").n_unique() == 1
```

But it will not expand on `n_unique() == 1` as that is a computation on a column, not a schema selection in the `col()` expression.

**Comment by pietz** [comment]
Thanks for your explanation. This actually helps me to put a little more structure into my line of thought. Now that we're here:

Wouldn't it be nice to give users access to expansions based on custom conditions? There must be some logic in place that evaluates which columns to expand to using `pl.col(pl.Utf8)` or `pl.col("x*")`. It would be awesome if I could do something similar like `df.select(pl.col(condition_thats_evaulated_for_each_col))`.

This goes a bit further than just looking at condition based on the schema but it would be really helpful none the less.

**Comment by ritchie46** [comment]
> Wouldn't it be nice to give users access to expansions based on custom conditions? There must be some logic in place that evaluates which columns to expand to using pl.col(pl.Utf8) or pl.col("x*"). It would be awesome if I could do something similar like df.select(pl.col(condition_thats_evaulated_for_each_col)).

This is not possible without materializing the data and it would break the whole lazyness of expressions. You are asking for a complete overhaul of the expression engine that would throw away all lazy benefits we have, whilst what you want is easily achievable by an eager list comprehension.

**Comment by pietz** [comment]
ok, understood. i didnt realize the magnitude of this. thanks for your time.

**Comment by mkleinbort-ic** [comment]
Note that this can be hacked together with `.pipe` (as can most things):

```python

from typing import Callable

def select_columns_on_condition(df:pl.DataFrame|pl.LazyFrame, condition: Callable):
    '''condition must be applicable "per-column" and return a single True/False value per column'''
    
    evaluated_conditions_raw = df.select(pl.all().pipe(condition)).pipe(lambda x: x.collect() if isinstance(x, pl.LazyFrame) else x).to_dicts()
    
    assert len(evaluated_conditions_raw)==1, 'Your condition did not evaluate into a 1-row DataFrame'
    
    evaluated_conditions = evaluated_conditions_raw[0]
    
    return df.select([col_name for col_name, condition_outcome in evaluated_conditions.items() if condition_outcome is True])

import polars as pl 
import numpy as np

df = pl.DataFrame({
    'x': np.random.rand(500),
    'y': np.random.randint(500),
})

# This works
df.pipe(select_columns_on_condition, lambda col: col.n_unique()<100).collect()

# This also works
df.lazy().pipe(select_columns_on_condition, lambda col: col.n_unique()<100).collect()
```
