### ISSUE TITLE
polars.Date converts to object dtype in pandas instead of datetime64[ns]

### ISSUE THREAD

**Issue by legout** [pola-rs/polars#6900]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When converting a polars dataframe to a pandas dataframe, columns of type `Date` are converted to  type `object`. 

### Reproducible example

```python
import datetime as dt
import polars as pl

df = pl.DataFrame(
    {
        "date":[dt.date(2022,1,1), dt.date(2022,1,2)],
        "a":[1,2]
    }
)
print("polars dtypes:", df.dtypes)

print("pandas dtypes:", df.to_pandas().dtypes)
```

### Expected behavior

polars columns of type `Date`  should be of type `datetime64[ns]` in pandas.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.4
Index type: UInt32
Platform: Linux-5.15.0-1028-aws-x86_64-with-glibc2.31
Python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by alexander-beedie** [comment]
I've got a proper [fix](https://github.com/pola-rs/polars/pull/6902) coming; in the meantime you can change `df.to_pandas()` to `df.to_pandas(date_as_object=False)` to get the expected behaviour.
