### ISSUE TITLE
GroupBy with aggregation list produces nested lists

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#6913]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

In the latest builds `groupBy().agg(col(x).list())` produces nested lists of type `list[list[dtx]]` instead of `list[dtx]`

### Reproducible example

```rust

    #[test]
    fn agg_list() -> Result<()> {
        let df = df! {
            "a" => ["1", "1", "1", "2", "2", "2"],
            "b" => ["a", "b", "c", "d", "e", "f"],
        }?;
        let res = df
            .lazy()
            .groupby(vec![col("a")])
            .agg(vec![col("b").list()])
            .collect()?;
        assert_eq!(
            res,
            df! {
                "a" => ["1", "2"],
                "b" => [
                    Series::new("b", &[Some("a"), Some("b"), Some("c")]),
                    Series::new("b", &[Some("d"), Some("e"), Some("f")])
                ]
            }?
        );
        Ok(())
    }

```
```
thread 'abc::tests::agg_list' panicked at 'assertion failed: `(left == right)`
  left: `shape: (2, 2)
┌─────┬───────────────────┐
│ a   ┆ b                 │
│ --- ┆ ---               │
│ str ┆ list[list[str]]   │
╞═════╪═══════════════════╡
│ 2   ┆ [["d", "e", "f"]] │
│ 1   ┆ [["a", "b", "c"]] │
└─────┴───────────────────┘`,
 right: `shape: (2, 2)
┌─────┬─────────────────┐
│ a   ┆ b               │
│ --- ┆ ---             │
│ str ┆ list[str]       │
╞═════╪═════════════════╡
│ 1   ┆ ["a", "b", "c"] │
│ 2   ┆ ["d", "e", "f"] │
└─────┴─────────────────┘`'
```

### Expected behavior

an aggregation of `list()` should produce a single `list` instead of a nested one.

### Installed versions

<details>
polars = { git = "https://github.com/pola-rs/polars", rev = "a507e1ba44fd6da52d8126363ed20780b93aab25", features = ["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series", "dtype-categorical", "performant", "serde", "concat_str", "row_hash", "lazy_regex"] }
</details>

**Comment by ritchie46** [comment]
See #6487

**Comment by SimonSchneider** [comment]
Thanks for the quick reply, seems I didn't RTFM my bad. 😀
