### ISSUE TITLE
Expose `is_between` on Series

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#6929]
### Problem description

I have an existing Series and i'd like to create a new series where which is a boolean mask of whether the original Series values are between certain values. This is currently possible to do using polars expressions but `with_columns` isn't defined on Series. Right now I just convert my series to a frame and do `series.to_frame().with_columns([pl.col("col").is_between(a, b)])`

**Comment by ritchie46** [comment]
Willing to make a PR?

`pl.select(pl.lit(self).is_between(a, b))`

**Comment by mcrumiller** [comment]
FYI @CHDev93 for the time being, you can use `pl.select(pl.lit(s), ...)` on a series and `s` is treated like an expression:

```python
import polars as pl

s = pl.Series(range(10))
print(pl.select(pl.lit(s).is_between(2, 8)))
```
```
shape: (10, 1)
┌───────┐     
│       │     
│ ---   │     
│ bool  │     
╞═══════╡     
│ false │     
│ false │     
│ true  │     
│ true  │     
│ true  │     
│ true  │     
│ true  │     
│ true  │     
│ true  │     
│ false │     
└───────┘  
```

**Comment by CHDev93** [comment]
@ritchie46 + @mcrumiller This is actually pretty clean. Working in an air gapped environment at the minute but I can try to make a PR later in the week if @alexander-beedie doesn't beat me to it!

**Comment by alexander-beedie** [comment]
>  I can try to make a PR later in the week if @alexander-beedie doesn't beat me to it!

Sorry...🤣
