### ISSUE TITLE
Let unnest have option to keep Duplicate column in common between parent df and child struct

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#6948]
### Problem description

Inspired by this [question](https://stackoverflow.com/questions/75471704/masking-a-polars-dataframe-for-complex-operations/75477135#75471704)

Let's say you have:

```
df=pl.DataFrame({'a':[1,2,3], 'b':[2,3,4]}).with_columns(pl.when(pl.col('a')==2).then(pl.struct(['a','b'])).alias('MyStruct'))
```

and then you do

```
df.unnest('MyStruct')
```

Now, we get a DuplicateError

It'd be nice if there was a way to ignore the error and take the struct value or original value, for instance:

```
df.unnest('MyStruct', keep_duplicates_from='struct')
```

or

```
df.unnest('MyStruct', keep_duplicates_from='df')
```

**Comment by shahankhatch** [comment]
I think the trick here is to alias the struct members using expressions rather than adding a keyword to do this separately

**Comment by deanm0000** [comment]
@shahankhatch sure that's possible, it just gets very cumbersome as you can see in the linked SO answer by me.  The point is to make it less cumbersome.  To be honest, it should be the default.  If you do a `with_columns`, it replaces any same named columns, it's not expected that the old columns get removed or renamed before each successive invocation of `with_columns`

**Comment by shahankhatch** [comment]
> To be honest, it should be the default

I agree with this point when used within with_columns (seems like with_columns semantics is lost, which might be a bug?), and if does become the default then no parameter is needed if I understand your point correctly.

I've been using the struct, unnest, exclude approach too and your suggestion would make expressions more concise.

**Comment by deanm0000** [comment]
I posted a unnest definition that does this over on this issue

https://github.com/pola-rs/polars/issues/9613
