### ISSUE TITLE
Re-instantiating a SQL Context raises an error

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#6949]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Re-instantiating a Polars SQL context raises an error.

Example: launching the code below for the first time works well.
```
sql = pl.SQLContext()
sql.register('df', df)
```

If I relaunch `sql = pl.SQLContext()` then it raises the error 
`ComputeError: only one sql-context per thread allowed`
This happens for example if I re-run cells in a Python notebook.

Should re-running the cell re-create the SQL context instead of raising the error? 
what are your thoughts?

btw- Congratulations for the outstanding library! 

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "answer": ["yes","no"],
        "value": [1,2],
    }
)

# this works well
sql = pl.SQLContext()
sql.register('df', df)

# this raises the error
sql = pl.SQLContext()
```

### Expected behavior

Not raising the error

### Installed versions

<details>

```
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.11.1 (main, Dec  7 2022, 01:11:44) [GCC 9.4.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.2
numpy: 1.24.0
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Yes, currently it is limited to only a single context per thread. But I think this is too limited. We should remove this constraint.

**Comment by zundertj** [comment]
Changing to enhancement as this is not unexpected, but merely a limitation of the current implementation.

**Comment by lucazanna** [comment]
Hi @2-5 ,

for my use case, this error prevented me from re-running all cells of the notebook.
So it would be enough to dispose and recreate the SQL context if SQLContext() is run a second time.

I checked duckDB, and they seem to not require instantiating a SQL context:
```
import duckdb
duckdb.query("SELECT * FROM df LIMIT 10")
```
Is this something that could also be done for Polars?

Awesome work to everybody for the Polars library. I keep recommending it to friends and colleagues

**Comment by 2-5** [comment]
For re-running all cells you could use this hack:

```python
if "sql_context" not in globals():
    sql_context = pl.SQLContext()

sql_context.register(...)
```
