### ISSUE TITLE
Add selective zero-copy DataFrame interchange

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars#6951]
I thought I'd open this issue to surface the interest and serve as a place to coordinate if necessary.

The ask is to start opening up the protocol usage for any use-cases that are zero-copy compatible.

As it stands, if I understand, the state of converting between Pandas and Polars is:
- Convert to Pandas zero-copy with #6756
- Convert from or to Pandas with copy from #6581

> Cannot utilize from_dataframe in a zero-copy manner. This will throw a NotImplementedError. We can refine this later by detecting which dtypes are present in the dataframe and determining if those can be handled in a zero-copy manner.
> *- #6581*

I looked at this stuff a while ago because this feature specifically interests me. So I generally understand the level of effort for this ask. I'm in a spot where I'd like to migrate most of our Pandas usage to Polars. I've visited this topic a few times in the past year. The conversation is much easier with zero-copy options both ways. So I'd be very excited to see this feature implemented wherever it can be.

**Comment by stinodego** [comment]
I think @ghuls added this recently in https://github.com/pola-rs/polars/pull/6844

We can probably still improve!

**Comment by cnpryer** [comment]
Of course @ghuls did lol. Such a machine. That's awesome.

I plan to migrate a lot of stuff to polars over the next month, so I'll give it a spin.

**Comment by stinodego** [comment]
I am re-opening this as I don't think the current `from_dataframe` implementation guarantees zero copy in the right way. See my comment [here](https://github.com/pola-rs/polars/pull/6844#issuecomment-1435273154).

Let's see how this turns out - I think adding the proper safeguards to guarantee zero-copy is actually not too big a hurdle.
