### ISSUE TITLE
Unexpected behavior when pivoting with datetime before 1970 as index

### ISSUE THREAD

**Issue by cogitoxin** [pola-rs/polars#6953]
### Polars version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When pivoting a dataframe with datetime before 1970 as index column, all dates before 1970 will return as null. Is this because rust [chrono](https://strawlab.org/strand-braid-api-docs/latest/chrono/index.html)::[DateTime](https://strawlab.org/strand-braid-api-docs/latest/chrono/struct.DateTime.html#) is dependent on Unix time?

### Reproducible example

```python
import polars as pl
from datetime import datetime

date_lst = [datetime(_, 1, 1) for _ in range(1960, 1980)]

tdf = pl.DataFrame(
    {"idx": date_lst[-3:]+date_lst[0:5], 
     "foo": ['a']*3+['b']*5,
    "value": [0] * 8}
)

tdf.pivot(index='idx',columns='foo',values='value')
```

### Expected behavior

pandas will return results as expected

```python
tdf.to_pandas().pivot(index='idx',columns='foo',values='value')
```
### Installed versions

<details>

```
0.16.2
```

</details>

**Comment by ritchie46** [comment]
I think we make a unix time error here by casting to unsized.
