### ISSUE TITLE
 `DataFrame.is_empty` ergonomic change

### ISSUE THREAD

**Issue by RichardHaythorn** [pola-rs/polars#6955]
### Problem description

Currently pl.DataFrame.is_empty() is a function call, I propose changing the function to use the property decorator like pandas does for pd.DataFrame.empty.

The reason is you can get unexpected behaviour if you forget to write brackets for pl.DataFrame.is_empty(), where it will return True and not throw an error

```
empty_df = pl.DataFrame()

if empty_df.is_empty(): #True
    print(empty_df.is_empty()) 

if empty_df.is_empty: #True
    print(bool(empty_df.is_empty)) 

not_empty_df = pl.DataFrame({"a":1})

if not_empty_df.is_empty(): #False
    print(not_empty_df.is_empty()) 

if not_empty_df.is_empty: #True
    print(bool(not_empty_df.is_empty)) 
```

If changed to used the property decorator then .is_empty would be the correct usage, and trying .is_empty() will throw a TypeError. This might be considered a breaking change but I think its worth it for clarity

**Comment by mcrumiller** [comment]
I don't see the upside of this. `is_empty` is a function, if you don't use it properly you shouldn't get the correct the result. 

> The reason is you can get unexpected behaviour if you forget to write brackets for pl.DataFrame.is_empty()

Calling `df.is_empty` without parentheses returns a bound function, just like any other function, which evaluates to True like any non-Falsy python object. if you say `if df.sum` you get something that evaluates to True as well:

```
>>>not not df.is_empty
True

>>>not not df.sum
True
```

**Comment by zundertj** [comment]
I agree with @mcrumiller here. We have a few [attributed on DataFrame](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/attributes.html), and all the others are methods. I don't think we should start migrating methods to attributes, unless we really think it is more consistent. The name `is_empty`, however trivial, suggests that something has to be computed, rather than information being readily stored, and I would prefer to have those as methods.

**Comment by s-banach** [comment]
@RichardHaythorn 
If you use vscode (and probably other code editors as well) methods and attributes have different colors. So if you’re not colorblind, you never need to worry about this.

**Comment by stinodego** [comment]
I have given this some thought, but I don't see a convincing reason to add `empty` as a property at this point.

I'll close this for now.
