### ISSUE TITLE
Fast way to count number of occurences in list

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#6964]
### Problem description

I would be great to have a concise way to count the number of occurences of an element in a List column (similar to what `Expr.str.count_match()` does for regexes). Of course one could use `.arr.eval(...)` to achieve the same thing, but it does not seem to be very fast:

```python
import polars as pl

df = pl.DataFrame({"listcol": [[], [1], [1, 2, 3, 2], [1, 2, 1], [4, 4]] * 1_000_000})  # caution: 5M rows, this is slow
df.select(
    pl.col("listcol")
    .arr.eval((pl.element() == 2).cast(pl.UInt8()))
    .arr.sum()
    .alias("number_of_twos")
)
```

**Comment by lucazanna** [comment]
Hi @moritzwilksch ,

did you already try with the argument `parallel = True` for `arr.eval()` ?
https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.eval.html#polars.Expr.arr.eval

that might help with speeding it up

**Comment by moritzwilksch** [comment]
Yes I did and it does indeed speed up the operation by ~4x on an `r5.4xlarge` instance. 
I was just wondering whether there is a more efficient way of counting occurences, potentially by implementing a dedicated expression. `duckdb`, for example, is another 10x faster for this specific task (which is usually not the case for other problems)

**Comment by ritchie46** [comment]
Sid you try an explode -> groupby idx -> aggregate approach?

I think we can add an arr.count(value)

**Comment by moritzwilksch** [comment]
Thanks, that's actually the fastest version! API-wise `arr.count(value)` seems to be the nicest way tho.
