### ISSUE TITLE
ColumnNotFoundError when series is used first in expression

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#6971]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In an expression, if a `pl.Series` comes first in an arithmetic or boolean expression, the second operand is not detected as a column.

### Reproducible example

```python
import polars as pl

s = pl.Series([1, 2, 3])
df = pl.DataFrame({'a': [1, 2, 3]})

df.select(pl.col('a') + s) # works
df.select(s + pl.col('a')) # fails
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Projects\project-brr\.venv_brr\lib\site-packages\polars\internals\series\series.py", line 554, in __add__
    return self._arithmetic(other, "add", "add_<>")
  File "c:\Projects\project-brr\.venv_brr\lib\site-packages\polars\internals\series\series.py", line 517, in _arithmetic
    other = self.to_frame().select(other).to_series()
  File "c:\Projects\project-brr\.venv_brr\lib\site-packages\polars\internals\dataframe\frame.py", line 5782, in select
    self.lazy()
  File "c:\Projects\project-brr\.venv_brr\lib\site-packages\polars\internals\lazyframe\frame.py", line 1146, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: a
```

### Expected behavior

Both should output same result

### Installed versions

<details>

```
---Version info---
Polars: 0.16.6
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.24.0
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by mcrumiller** [comment]
FYI, this works with `pl.lit(s)`:

```python
import polars as pl

s = pl.Series([1, 2, 3])
df = pl.DataFrame({'a': [1, 2, 3]})

df.select(pl.col('a') + s) # works
df.select(pl.lit(s) + pl.col('a')) # fails
```

I'm not sure whether my original issue is intended behavior or not but it's reminiscent of #6929.

**Comment by mcrumiller** [comment]
@ritchie46 can we reopen this? My sample code in the OP still fails on latest release (0.6.11), and it looks like the referenced #7015 issue only updates the test to avoid creating the error by explicitly using `pl.lit`.

**Comment by StevenLi-DS** [comment]
@mcrumiller I'm getting a `ColumnNotFoundError` on Polars: 0.16.18 with the following code:

```python
df = pl.DataFrame(
    {'a': ['a', 'a', 'b', 'b', 'b'],
     'b': [1, 2, 3, 5, 4]}
)

df.with_columns(
    pl.col('b').max().over('a').alias('b_max')
).with_columns(
    b_max_cat=df['b_max'].cut(bins=[0, 1])['category']
)
```
Is it related to this issue?

**Comment by mcrumiller** [comment]
No--this is an expected error. When you chain together statements like that, you refer to the original `df` because it hasn't actually been reassigned yet. I'll try to explain here:

```python
x = 1

x = (x + 3) + x
```
This is NOT equal to 4 + 4, it's equal to 4 + 1. `x` doesn't get reassigned until the entire expression finishes. Despite the fact that `x+3` is evaluated first, the result of `x+3` isn't reassigned to `x` until after the `+ x`. Similarly, you call `df.with_columns(...).something(df)`. The `something(df)` uses the original `df` before it's been modified, i.e. before it has a `b_max` column. Make sense?

Looks like `pl.cut` isn't implemented for expressions yet, so for now you're going to have to just separate into two statements:

```python
df = df.with_columns(pl.col('b').max().over('a').alias('b_max'))
df = df.with_columns(b_max_cat=df['b_max'].cut(bins=[0, 1])['category'])
```

**Comment by StevenLi-DS** [comment]
@mcrumiller Thanks for the explanation. This indeed makes sense to me. I always assumed that once you chain them like `.with_columns().with_columns()`. The first one will be evaluated and then the second one... I know that the exprs in a `.with_columns(expr, expr)` will not be evaluate in an order...but this is unexpected to me. This is very important and should be included in the doc somewhere.

**Comment by mcrumiller** [comment]
They are evaluated in order. It's the binding of the result to the name `df` that doesn't happen until the end. See my example with `x` above, but replace it with this:

```python
x = 1
x = x.add(3).add(x)
```

What would you expect the result to be here?

**Comment by StevenLi-DS** [comment]
I would say x = 4

**Comment by mcrumiller** [comment]
Correct--`x.add(3)` doesn't get assigned to `x` prior to `.add(x)`. So, do you see why `x.with_columns(stuff.alias("blah")).select(x["blah"])` returns the error that `x` doesn't have a column `blah`?

**Comment by StevenLi-DS** [comment]
@mcrumiller indeed. I got it, man. Should be `x.with_columns(stuff.alias("blah")).select("blah")`... `x["blah"]` was trying to access the original `x`. Thanks a lot for walking me through this!
