### ISSUE TITLE
read_csv Failing to read a CSV file

### ISSUE THREAD

**Issue by maufdez** [pola-rs/polars#6973]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am working in Windows with Python Polars 0.12.5.

I have a very simple script which reads a csv which I can't share due to confidentiality issues, however I was able to determine the cause. It seems that while read_csv is executing it tries to conver the contents of cells, we have a cell that contains a string represenataion of a binary number (example "00001110111111000101100000010101"), when it tries to decode the value it does crash. The crash can be avoided with `ignore_errors=True`. However I don't know what happens in that case, is the column read as a srting from then on or are the values which could not be parsed kept empty (the column where this appears is always a string but some time it may contains different representations of the data. I was going to try with dtypes, but my problem is that the csvs may come with the columns in different order, or with different number of columns, basically right now we are only requesting that some columns exist and the users don't need to maintain column order.

### Reproducible example

```python
import polars as pl
df = pl.read_csv("file.csv")
```

### Expected behavior

If a column can't be parsed into a number type keep it as a string.

### Installed versions

<details>

```
0.12.5
```

</details>

**Comment by cmdlineluser** [comment]
You don't need to share your actual data.

This seems to be an MRE:
```
import io
import polars as pl

pl.read_csv(io.StringIO("""
column
00001110111111000101100000010101
"""))
```
```
ComputeError: Could not parse `column` as dtype Int64 at column 1.
The current offset in the file is 1 bytes.
```
Leading zeros don't seem to matter and polars tries to parse them as integers.
```
import io
import polars as pl

pl.read_csv(io.StringIO("""
id,name
00023213,polars
00012323,pythons
00091823,crustaceans
"""))
```
```
shape: (3, 2)
┌───────┬─────────────┐
│ id    | name        │
│ ---   | ---         │
│ i64   | str         │
╞═══════╪═════════════╡
│ 23213 | polars      │
│ 12323 | pythons     │
│ 91823 | crustaceans │
└───────┴─────────────┘
```

**Comment by abubelinha** [comment]
> This seems to be an MRE

@cmdlineuser what is an MRE?
