### ISSUE TITLE
IsADirectory error when reading Parquet files from a directory, Python v0.16.x

### ISSUE THREAD

**Issue by gwerbin** [pola-rs/polars#6974]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It looks like reading Parquet data from directories is no longer directly supported by `polars.read_parquet`, throwing an `IsDirectoryError` inside from the filename-normalization logic.

Apologies if I missed this in the changelog, but I didn't see it there.

As a workaround, I can use a glob with `use_pyarrow=False`. But my data was exported by Snowflake, and it contains data types that the Rust engine does not support, so I need `use_pyarrow=True` to read these files. I've had to set `polars < 0.16.0` in my Conda environment in the meantime.

Note that I am using Polars 0.16.5 because 0.16.6 does not yet appear available for Intel Mac. I got the same results when using both the Conda-Forge and Pip packages.

### Reproducible example

```python
import pandas as pd
import polars as pl

data = pd.DataFrame({
  'key': ['a', 'a', 'b', 'b'],
  'val': [1, 2, 3, 4]
})
data.to_parquet('data', partition_cols=['key'])

# v0.15.14: ArrowErrorException
data2 = pl.read_parquet('data', use_pyarrow=False)

# v0.15.14: OK, as expected
data2 = pl.read_parquet('data', use_pyarrow=True)

# v0.16.5: IsADirectoryError
data2 = pl.read_parquet('data', use_pyarrow=False)

# v0.16.5: IsADirectoryError
data2 = pl.read_parquet('data', use_pyarrow=True)
```

### Expected behavior

I expected `pl.read_parquet('data')` to work regardless of `use_pyarrow`, as per the [docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_parquet.html):

> If the path is a directory, that directory will be used as partition aware scan.

As a side note, this mode of operation never worked when `use_pyarrow=False`, even with versions 0.15.x.

### Installed versions

Working:

<details>

```text
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.7.0
```

</details>

Non-working:

<details>

```text
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by zundertj** [comment]
Ok, so there are multiple things going on here:

1. As you say, you cannot read partitioned datasets with Polars directly (`use_pyarrow=False`), per #426. 

You can work around it by using a glob, and that works:
```python
 data2 = pl.read_parquet('data/**/*.parquet', use_pyarrow=False)
```
Although you do lose the partition key.

2. PyArrow can read partitioned datasets, but passing in the directory no longer works from 0.15.14 to 0.16.5.

We have quite a bit of logic in file parameter handling (strings, paths, bytes, bytesio, stringio, url's and I see that right now the assumption, per `_prepare_file_arg`  is that the file can be read, which obviously does not work when trying to pass in a directory. It seems @alexander-beedie  was assuming in #6187  `read_parquet` always takes in a file and not a directory, if I understand it correctly. Let me know if not @alexander-beedie . Possible fix here: #6994.

In the mean time, it is good to know that `use_pyarrow=True` is mostly a thin wrapper around the PyArrow api, to you can do `pa.parquet.read_table` and use `pl.from_arrow`. That should give you the same performance.

**Comment by zundertj** [comment]
#6994 fixes this.

**Comment by gwerbin** [comment]
@zundertj thank you for the quick fix! Do you know when we can expect this in a release?
