### ISSUE TITLE
Groupby aggregation with list yields `list[list[f32]]`

### ISSUE THREAD

**Issue by kurtszen** [pola-rs/polars#6975]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When doing a groupby `list()` aggregation on a column, the result has an extra level of nesting, yielding `list[list[f32]]`, rather than just `list[f32]`.

### Reproducible example

```python
import polars as pl
pl.DataFrame({'a': [1, 1], 'b': [2, 2]}).groupby('a').agg([pl.col('b').list()])
# shape: (1, 2)
# ┌─────┬─────────────────┐
# │ a   ┆ b               │
# │ --- ┆ ---             │
# │ i64 ┆ list[list[i64]] │
# ╞═════╪═════════════════╡
# │ 1   ┆ [[2, 2]]        │
# └─────┴─────────────────┘
```

### Expected behavior

```python
# ┌─────┬─────────────────┐
# │ a   ┆ b               │
# │ --- ┆ ---             │
# │ i64 ┆ list[i64] │
# ╞═════╪═════════════════╡
# │ 1   ┆ [2, 2]        │
# └─────┴─────────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.6
Index type: UInt32
Platform: macOS-13.2.1-arm64-arm-64bit
Python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by cmdlineluser** [comment]
You can remove the `.list()` - https://github.com/pola-rs/polars/issues/6913

**Comment by kurtszen** [comment]
This is intentional as documented in #6913
