### ISSUE TITLE
Custom format number exhibition (f-string dialect or something like this)

### ISSUE THREAD

**Issue by igmriegel** [pola-rs/polars#7006]
### Problem description

Hello,

I was wondering if it would be difficult to implement some sort of "mask" for formatting the number exhibition, sometimes we use smaller DataFrames on logs or even use them on reporting, it would be nice to be able to format float number of decimals and thousand separators.

The issue:
_Regular Polars DataFrame_
```python
In []: pl.DataFrame({
    ...:     "floats":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     "integers":[1, 12, 123, 1234, 12345, 123456, 1234567, 12345678, 123456789],
    ...:     "percent":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     "currency":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     })
Out[]: 
shape: (9, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ floats    ┆ integers  ┆ percent   ┆ currency  │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ i64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.1       ┆ 1         ┆ 1.1       ┆ 1.1       │
│ 2.12      ┆ 12        ┆ 2.12      ┆ 2.12      │
│ 3.123     ┆ 123       ┆ 3.123     ┆ 3.123     │
│ 4.1234    ┆ 1234      ┆ 4.1234    ┆ 4.1234    │
│ 5.12345   ┆ 12345     ┆ 5.12345   ┆ 5.12345   │
│ 6.123456  ┆ 123456    ┆ 6.123456  ┆ 6.123456  │
│ 7.1234567 ┆ 1234567   ┆ 7.1234567 ┆ 7.1234567 │
│ 8.123457  ┆ 12345678  ┆ 8.123457  ┆ 8.123457  │
│ 9.123457  ┆ 123456789 ┆ 9.123457  ┆ 9.123457  │
└───────────┴───────────┴───────────┴───────────┘
```

The proposed solution:
_Polars DataFrame with proposed enhancement_
```python
In []: pl.DataFrame({
    ...:     "floats":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     "integers":[1, 12, 123, 1234, 12345, 123456, 1234567, 12345678, 123456789],
    ...:     "percent":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     "currency":[1.1, 2.12, 3.123, 4.1234, 5.12345, 6.123456, 7.1234567, 8.12345678, 9.123456789],
    ...:     })
Out[]: 
┌───────────┬─────────────┬───────────────┬───────────────┐
│    floats ┆    integers ┆       percent ┆      currency │
╞═══════════╪═════════════╪═══════════════╪═══════════════╡
│     1.100 ┆           1 ┆           1 % ┆        $ 1.10 │
│     2.120 ┆          12 ┆           2 % ┆        $ 2.12 │
│     3.123 ┆         123 ┆           3 % ┆        $ 3.12 │
│     4.123 ┆       1_234 ┆           4 % ┆        $ 4.12 │
│     5.123 ┆      12_345 ┆           5 % ┆        $ 5.12 │
│     6.123 ┆     12_3456 ┆           6 % ┆        $ 6.12 │
│     7.123 ┆   1_234_567 ┆           7 % ┆        $ 7.12 │
│     8.123 ┆  12_345_678 ┆           8 % ┆        $ 8.12 │
│     9.123 ┆ 123_456_789 ┆           9 % ┆        $ 9.12 │
└───────────┴─────────────┴───────────────┴───────────────┘
```
Some sort of format where we could pass a text pattern. Would be nice if the text dialect could be something close to what we can do is not too much far from what we do on fstrings (https://fstring.help/) if I'm not mistaken, this dialect of formatting options are not too much different of what Rust parses for formatting (https://doc.rust-lang.org/std/fmt/)

I know we have some of the esthetic options above can be achieved thought the `pl.formatting()` method, but this will cast the data to string, my proposed feature is to maybe hide this conversion and work on the `__str__` or `__repr__` of the classes in some dynamic way.

(edit 1)
Now I'm aware that what I asked for is exactly what Pandas do on the link bellow.
https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.format.html

(edit 2)
After some research about the pandas utilities on the styler it looks like some of this functionalities of formatting only work with the `display()` function used by Jupyter notebooks whereas what I'm asking for is formatting options to enhance our (already awesome and beautiful) string tables.

**Comment by Wainberg** [comment]
Aspects of this should be addressed by https://github.com/pola-rs/polars/issues/7133, which has been accepted
