### ISSUE TITLE
General question: Convert a vec of Bson/Struct to a polars dataframe

### ISSUE THREAD

**Issue by Nimpruda** [pola-rs/polars#701]
Hello,

I have a use case where I need to request data from a Mongo database (I use the mongodb package), it gives me back an Array of Structures. I cannot do my operations in database so I'd like to use a polars dataframe to compute kpis.
The only problem is I cannot find out how to create a dataframe from an AoS. How would you do this ?

Great job by the way!

**Comment by ritchie46** [comment]
You need to unpack the structs and add the values with one of the [builders](https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/builder/mod.rs). Another option is to create a vec of values and convert that to `Series`
