### ISSUE TITLE
Remove several top-level functions

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#7016]
### Problem description

Most of our api is behind `DataFrame`, `Series`, and `Expr`. For the functions that are not, that is mostly ok, but I think the below list is better placed elsewhere, so I think they can be removed? Unless I am missing something here. See also https://pola-rs.github.io/polars/py-polars/html/reference/functions.html for all top-level functions (except utils).

* `pl.arg_where`: operates on `Series` and `Expressions`, returns index where condition is True. Usage of this should probably be discouraged, and we could, if we want to continue supporting this, move to `Series.arg_where` and `Expr.arg_where`? I.e. I dont see why this needs to be special vs all other methods.
* `pl.cut`: should be on Series & Expr
* `pl.get_dummies`: what exactly is the difference with `DataFrame.to_dummies()`? The docstrings are unable to make that clear. The docstring here: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.get_dummies.html even suggests it is broken, why is `"ham"` not different from the other two columns, although it is not in the parameter list?
* `pl.ones` & `pl.zeros`: we have broadcasting now, so how useful is this? I.e. `pl.lit(1, pl.Int64)`.

**Comment by ritchie46** [comment]
> pl.ones & pl.zeros: we have broadcasting now, so how useful is this? I.e. pl.lit(1, pl.Int64).

It only broadcast if it is selected with multiple expression, not if it is the only selection. It also has no `eager` option.

**Comment by stinodego** [comment]
About `pl.get_dummies`: it's not broken but the docstring example is wrong, it calls `to_dummies` twice.

I agree that I don't see the point of having it as a separate function, over just a DataFrame method (which it already is).

**Comment by stinodego** [comment]
I believe this issue has been resolved. Please open a new issue for any unresolved leftover issues.
