### ISSUE TITLE
arg_where performance / utility

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#7034]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Sorry if this isn't actually a bug, I just wanted to share it since #7016 was discussing removing this function.

(1) In the most basic case (calling `arg_where` on a whole column), it seems faster to use `with_row_count` and select row numbers satisfying the condition.

(2) If people want to use `arg_where` is some fancier context (a groupby, etc), maybe they would also want to use `with_row_count` in that context. It just seems like the more general function.

### Reproducible example

```python
import numpy as np
import polars as pl

n_rows = 1_000_000
df = pl.DataFrame({"x": np.linspace(0, 1, n_rows)})
condition = pl.col("x") > 0.4

%%timeit -r 20
df.select(pl.arg_where(condition))
"1.07 ms ± 28 µs per loop (mean ± std. dev. of 20 runs, 1,000 loops each)"

%%timeit -r 20
df.with_row_count().select(pl.col("row_nr").where(condition))
"829 µs ± 31.3 µs per loop (mean ± std. dev. of 20 runs, 1,000 loops each)"
```

### Expected behavior

If `arg_where` is slower than calling `with_row_count` and filtering it, maybe `arg_where` doesn't need to exist.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.2
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>

```

</details>

**Comment by ritchie46** [comment]
This is not a bug right? Different code paths have different execution times?
