### ISSUE TITLE
Consider allowing groupby empty columns

### ISSUE THREAD

**Issue by jr200** [pola-rs/polars#7042]
### Problem description

If you try and groupby an empty list of column names you get this error:

```python
ComputeError: expected keys in groupby operation, got nothing
```

Is it reasonable to suggest that a groupby-nothing operation means there is only one 'group' in the dataframe, i.e., the group that contains all the rows? 

Currently (to write generic code), I end up adding an artificial group, grouping by that, then removing the group. It would be great if this could be pushed down a layer, and I wondered what others though of this behavior.

Thanks!

**Comment by zundertj** [comment]
You can pass in a constant:

```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [1, 1, 2, 2, 3,]})
>>> df
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
│ 2   │
│ 2   │
│ 3   │
└─────┘
>>> df.groupby(pl.lit(True)).count()
shape: (1, 2)
┌─────────┬───────┐
│ literal ┆ count │
│ ---     ┆ ---   │
│ bool    ┆ u32   │
╞═════════╪═══════╡
│ true    ┆ 5     │
└─────────┴───────┘
```

**Comment by jr200** [comment]
Interesting. ...thats much better than what I currently have, but I still wonder if theres any appetite to add the semantics I suggested to groupby-style functions. 

The issue I have is theres a lot of repeated boiler-plate in any function that whats to apply custom-calculations across some configurable set of categories.

An typical function I might have looks like this:

```python
def someCalc(x: pl.DataFrame, by: list) -> pl.DataFrame:
    if len(by) == 0: by = pl.lit(True).alias('some-unique-col-name')
    return (x
        .groupby(by)
        .agg([ ....some-calc... ])
        .drop(pl.col('some-unique-col-name'))
   )

```
If we allowed the semantics I propose, I could instead be writing:

```python
def someCalc(x: pl.DataFrame, by: list) -> pl.DataFrame:
    return (x
        .groupby(by)
        .agg([ ....some-calc... ])
   )

```

To me (apologies I realise I can't have the broad view of the community), it seems like a 'reasonably harmless' modification that might add value to others who write similar kinds of helper functions.

What do you think?

**Comment by ritchie46** [comment]
> it seems like a 'reasonably harmless' modification that might add value to others who write similar kinds of helper functions.

We have a lot of code depending on current behavior. It isn't a harmless change. The optimizer and the engine are written for current behavior. It isn't a method that stands on its own.

**Comment by jr200** [comment]
Understood - and makes sense. I was thinking about it from the user's point of view, where previously a `ComputeError` would no longer result in that being thrown.

Thanks for looking into it, and I appreciate your time and efforts on this library!
