### ISSUE TITLE
Get the first n rows with the largest values in columns

### ISSUE THREAD

**Issue by pikaflufftuft** [pola-rs/polars#7043]
### Problem description

Basically the Polars counterpart of pandas.DataFrame.nlargest
According to https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html ,
> `DataFrame.nlargest(n, columns, keep='first')`
> 
> Return the first n rows ordered by columns in descending order.
> Return the first n rows with the largest values in columns, in descending order. The columns that are not specified are returned as well, but not used for ordering.
> 
> This method is equivalent to `df.sort_values(columns, ascending=False).head(n)`, but more performant.
> 
> Parameters: n : int
>     Number of rows to return.
> 
> columns : label or list of labels
>     Column label(s) to order by.
> 
> keep : {‘first’, ‘last’, ‘all’}, default ‘first’
>     Where there are duplicate values:
> - `first` : prioritize the first occurrence(s)
> - `last` : prioritize the last occurrence(s)
> - `all` : do not drop any duplicates, even it means selecting more than n items.
> 
> Returns: DataFrame
>     The first n rows ordered by the given columns in descending order.

In Polars, this is achievable by
`df.sort(column, reverse=True).head(n)`
or (for one column, there is a problem with this method)
`df.filter(pl.col(column) >= pl.col(column).top_k(n).last()).head(n)`

According to my benchmark on a 440MB parquet file, with `df = pl.scan_parquet(file)`
```
df.sort('score', reverse=True).head(5).collect()
6.89 s ± 2.28 s per loop (mean ± std. dev. of 16 runs, 4 loops each)
```
```
df.filter(pl.col('score') >= pl.col('score').top_k(5).last()).head(5).collect()
5.64 s ± 628 ms per loop (mean ± std. dev. of 16 runs, 4 loops each)
```

Besides the difference in performance, the second method maintains order in the dataframe.
However,

1. it only works for a single column
2. it does not guarantee that it will return the correct rows with the largest values in the specified column when there are multiple rows having the same value in the specified column

We can solve the second problem by applying `sort()` before applying `head()`.

According to my benchmark on a 440MB parquet file, with `df = pl.read_parquet(file)`
```
df.sort('score', reverse=True).head(5)
3.25 s ± 539 ms per loop (mean ± std. dev. of 16 runs, 4 loops each)
```
```
df.filter(pl.col('score') >= pl.col('score').top_k(5).last()).head(5)
75.8 ms ± 6.84 ms per loop (mean ± std. dev. of 16 runs, 4 loops each)
```
```
df.filter(pl.col('score') >= pl.col('score').top_k(5).last()).sort('score', reverse=True).head(5)
168 ms ± 40.4 ms per loop (mean ± std. dev. of 16 runs, 4 loops each)
```

The third method is slower than the second but it now returns the correct rows.

Comparing the output of the first and third methods,
```
(df.sort('score', reverse=True).head(5000)['score'] == df.filter(pl.col('score') >= pl.col('score').top_k(5000).last()).sort('score', reverse=True).head(5000)['score']).all()
True
```

This is good when sorting is based on only one column and duplicates are allowed.

Comparing the output of the first and second methods,
```
(df.sort('score', reverse=True).head(5000)['score'] == df.filter(pl.col('score') >= pl.col('score').top_k(5000).last()).head(5000)['score']).all()
False
```

The third method is quite performant but it has its limits. Having a Polars counterpart of `pandas.DataFrame.nlargest` would be great especially when you need to specify more than one column and have to deal with duplicate values.
So I would suggest two new methods:

1. the third method `df.filter(pl.col(column) >= pl.col(column).top_k(n).last()).sort('score', reverse=True).head(n)` 
2. the Polars counterpart of `pandas.DataFrame.nlargest`

**Comment by s-banach** [comment]
Just out of curiosity, did you ever try benchmarking the obvious thing?
`df.lazy().sort("score", reverse=True).limit(5).collect()`

**Comment by s-banach** [comment]
Just out of curiosity, in the second set of benchmarks where you're looking at `df = pl.read_parquet(file)`,
how does `df.lazy().sort('score', reverse=True).head(5).collect()` compare to the other fancier methods you're testing?

P.S. There is this method to test if two series are equal without using numpy:
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.series_equal.html#polars.Series.series_equal

P.P.S. In the first set of benchmarks where you're using `df = pl._scan_parquet(file)`, sometimes people will write `dfl` instead of `df` since you're working with a LazyFrame rather than a DataFrame.

**Comment by s-banach** [comment]
(I don't know anything about writing good code, sorry for asking you to benchmark something slow. I'm always making a fool of myself on here.)

**Comment by zundertj** [comment]
> > Just out of curiosity, did you ever try benchmarking the obvious thing? `df.lazy().sort("score", reverse=True).limit(5).collect()`
> 
> No, I have not. No one suggested that when I asked in the discord server. Benchmarking it,

FYI, `limit` and `head` do the same, so this is the same as what I posted on Discord [here](https://discord.com/channels/908022250106667068/911186243465904178/1076505095379882065) yesterday.

> Having a Polars counterpart of pandas.DataFrame.nlargest would be great especially when you need to specify more than one column and have to deal with duplicate values.
So I would suggest two new methods:

    1. the third method df.filter(pl.col(column) >= pl.col(column).top_k(n).last()).sort('score', reverse=True).head(n)
    2. the Polars counterpart of pandas.DataFrame.nlargest


Could you clarify what you would like to see in Polars with the first suggestion? It is the fastest, and it nicely shows that the obvious solution `f.lazy().sort("score", reverse=True).limit(5).collect()` could be made more performant (as far as I can see), so we could focus on optimizing that, rather than introducing a new method? And when that is performant, one can debate whether is worth having syntactic sugar to wrap it in a `nlargest` method, i.e. your second suggestion.

**Comment by mwiebusch78** [comment]
I have the same use case and ran a speed comparison with pandas.nlargest. Here are the results:

```python
import numpy as np
import polars as pl
import pandas as pd

rng = np.random.default_rng(1234)
a = rng.uniform(size=50000)

def nlargest_pd(a):
    return a.nlargest(20)

def nlargest_pl(a):
    return a.lazy().sort('a').head(20).collect()

a_pd = pd.Series(a)
a_pl = pl.DataFrame(pl.Series('a', a)).with_row_count()

%timeit -n 100 -r 7 nlargest_pl(a_pl)
%timeit -n 100 -r 7 nlargest_pd(a_pd)
```

```
2.35 ms ± 351 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.24 ms ± 122 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
So it seems polars currently takes nearly twice as long as pandas on this particular problem.

**Comment by ritchie46** [comment]
Yeap, we can translate that in a top-k now we have the row format.

**Comment by orlp** [comment]
We now have `DataFrame.top_k` and such, so this can be closed.
