### ISSUE TITLE
Numba interoperability - writable=True support for view()

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#7046]
### Problem description

`Series.view()` doesn't support returning writable `numpy` array views like `to_numpy(writable=True)`

It's more difficult to use read-only arrays with Numba, you need a more complex type declaration: https://github.com/numba/numba/issues/4511, instead of `nb.int32[:]` you need something like `nb.types.Array(nb.int32, 1, 'C', readonly=True)`

It would be nice if `Series.view` also supported `writable=True` like `to_numpy`

```python
import numba as nb
import polars as pl

@nb.njit(nb.int32(nb.int32[:]))
def func(arr):
    return arr[0] + arr[1] + arr[2]

s1 = pl.Series("a", range(10), dtype=pl.Int32).to_numpy(writable=True)
print(func(s1))

s2 = pl.Series("a", range(10), dtype=pl.Int32).view()
print(func(s2))
# TypeError: No matching definition for argument type(s) readonly array(int32, 1d, C)
```

**Comment by zundertj** [comment]
I see that the implementation in `Series.to_numpy` is quite straightforward: https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/series/series.py#L2941

```python
if writable and not np_array.flags.writeable:
    return np_array.copy()
else:
    return np_array
```

Is it sufficient to return a copy if it is not writeable yet?

**Comment by 2-5** [comment]
I don't think a copy is ok, the whole point of `view` is to return the underlying buffer and not copy it. An error is probably more appropriate if an inplace buffer can't be returned.

**Comment by ghuls** [comment]
> I don't think a copy is ok, the whole point of `view` is to return the underlying buffer and not copy it. An error is probably more appropriate if an inplace buffer can't be returned.

Because it is not a copy, the returned numpy array is a read only view. Arrow arrays are immutable and external code should not be able to mess with the memory owned by the Arrow arrays.

**Comment by s-banach** [comment]
Sometimes I use “df.select(…).get_column(…).to_numpy(writable=True)” in a way where it’s clear that I’m duplicating the original array and then throwing it in the garbage, and I wish I could just tell the dataframe “release this column, make it mutable”. But I guess that’s pretty niche and incurs a pretty small overhead all things considered.

**Comment by zundertj** [comment]
Basically you want to release the column from the dataframe / take ownership. And have it as writable view, which I don't think is possible given it is Arrow vs Numpy format? But I will let @ritchie46  comment on that.

**Comment by ritchie46** [comment]
> But I guess that’s pretty niche and incurs a pretty small overhead all things considered.

This.

**Comment by deanm0000** [comment]
@stinodego this looks closable.
