### ISSUE TITLE
DOC: arg descending in .sort() has changed to reverse

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7062]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.sort.html#polars.DataFrame.sort

![CS-cceb4wNs@2x](https://user-images.githubusercontent.com/33796896/220203689-8cc8bdf0-2e28-4f2f-952e-d1ac3570e11d.png)

### Reproducible example

```python
Help on method sort in module polars.internals.dataframe.frame:

sort(by: 'IntoExpr | Iterable[IntoExpr]', *more_by: 'IntoExpr', reverse: 'bool | Sequence[bool]' = False, nulls_last: 'bool' = False) -> 'Self' method of polars.internals.dataframe.frame.DataFrame instance
    Sort the dataframe by the given columns.
    
    Parameters
    ----------
    by
        Column(s) to sort by. Accepts expression input. Strings are parsed as column
        names.
    *more_by
        Additional columns to sort by, specified as positional arguments.
    reverse
        Sort in descending order. When sorting by multiple columns, can be specified
        per column by passing a sequence of booleans.
    nulls_last
        Place null values last. Can only be used when sorting by a single column.
```
```


### Expected behavior

-

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by stinodego** [comment]
This is intentional, and a known issue with our docs.

See:
#5429
#6373

**Comment by alexfromapex** [comment]
Got stuck for a while with this, glad I found this thread
