### ISSUE TITLE
Probable dead lock with scan_csv().sink_parquet()

### ISSUE THREAD

**Issue by hombit** [pola-rs/polars#7074]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`pl.scan_csv().sink_parquet()` freezes after a while when `POLARS_MAX_THREADS` is not 1. Tested on aarch64 Linux, aarch64 macOS and x86_64 Linux.

### Reproducible example

Create CSV file
```python
import numpy as np
import polars as pl

rng = np.random.default_rng(0)
n_cols = 304
n_rows = 4053955

df = pl.DataFrame({f'c{i:03d}': np.asarray(rng.normal(size=n_rows), dtype=np.float32) for i in range(n_cols)})
df.write_csv('test.csv')
```

Convert it to Parquet:

```python
import polars
polars.scan_csv('test.csv', rechunk=False).sink_parquet('test.parquet', row_group_size=1<<12, maintain_order=False)
```

### Expected behavior

When `POLARS_MAX_THREADS ` is set to 1 everything works as expected: a CPU core load is close to 100%, I see IO on disk. When this env variable is not set (or set to a larger value) a small chunk of data is written to a parquet file utilizing ~100% of each CPU core, and then the process is sleeping with no CPU or IO utilization

### Installed versions

<details>

```
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Linux-5.10.110-37-rockchip-g74457be0716d-aarch64-with-glibc2.31
Python: 3.11.1 (main, Dec 21 2022, 09:36:17) [GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
None
```

</details>

**Comment by ritchie46** [comment]
Thanks for the report. Have you go the file with which we can reproduce this?

**Comment by hombit** [comment]
After some more experiments I've found that I can reproduce it even with a randomly generated file:
```python
import numpy as np
import polars as pl

rng = np.random.default_rng(0)
n_cols = 304
n_rows = 4053955

df = pl.DataFrame({f'c{i:03d}': np.asarray(rng.normal(size=n_rows), dtype=np.float32) for i in range(n_cols)})
df.write_csv('test.csv')
```

**Comment by hombit** [comment]
Sorry, I deleted last message because didn't debug it properly.

I can reproduce the problem using a CSV file generated this way:
```python
import numpy as np
import polars as pl

rng = np.random.default_rng(0)
n_cols = 304
n_rows = 4053955

df = df = pl.DataFrame({f'c{i:03d}': np.asarray(rng.normal(size=n_rows), dtype=np.float32) for i in range(n_cols)})
df.write_csv('test.csv')
```

Tested on aarch64 Linux only this time. It freezes after writing 676 MB when `POLARS_MAX_THREADS` is unset. When it is set to `1` everything goes smoothly and the whole parquet file of 13GB is written down successfully.

**Comment by hombit** [comment]
I can reproduce it on x86_64 Linux, it freezes after first 85MB written down.

**Comment by ritchie46** [comment]
How many threads do you have? I can write the whole file.

**Comment by hombit** [comment]
8 cores on ARM machine, 48 cores on Intel

**Comment by hombit** [comment]
Just tested on Intel Linux again, it doesn't work with `POLARS_MAX_THREADS=2` for me.

**Comment by ritchie46** [comment]
Can anyone else reproduce this?

**Comment by hombit** [comment]
I've updated the original message to include data generation part

**Comment by thomasfrederikhoeck** [comment]
I can't reproduce on Intel Windows .

**Comment by hombit** [comment]
Since I'm starting to feel a bit crazy I reproduced it in Github actions.

Commit: https://github.com/hombit/polars-issue-7074/tree/daf7590c04d01e0eb704704c4427cf2004b90b7d
Workflow run: https://github.com/hombit/polars-issue-7074/actions/runs/4246811828

The first job is single-thread, the second is two threads. The first ended in 4 mins, the second is still running when I type it and showing no CPU utilization

**Comment by thomasfrederikhoeck** [comment]
> I can't reproduce on Intel Windows .

My apologizes - I CAN replicate it on Windows! Also freezes around 676 MB when `POLARS_MAX_THREADS` is unset.

**Comment by hombit** [comment]
Thank you @thomasfrederikhoeck, I really started to think that it was me

**Comment by ritchie46** [comment]
Can reproduce. :)
