### ISSUE TITLE
Add link to Twitter Profile

### ISSUE THREAD

**Issue by tycrimm** [pola-rs/polars#7075]
Trivial but just discovered Polars from a mention on Twitter and would love to be able to click as soon as I get to the page vs having to Google. Example below. Thanks! 🙏  

<img width="517" alt="image" src="https://user-images.githubusercontent.com/3053339/220429040-42d3cae3-d42a-417f-bcdf-fd9911e7149a.png">

vs. 

<img width="351" alt="image" src="https://user-images.githubusercontent.com/3053339/220429277-effe86eb-e967-43b1-8ae0-3876c7a56521.png">

**Comment by ritchie46** [comment]
Done. :+1:
