### ISSUE TITLE
Expr.map_dict doesn't work on categorical columns

### ISSUE THREAD

**Issue by coinflip112** [pola-rs/polars#7077]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi there, 

I've been using polars for a while and find it amazingly useful :) However, I found some weird behavior I expect is not intended. 
More specifically, `polars.Expr.map_dict` doesn't work for Categorical type columns. I suspect this is because the series which is created in [it's definition](https://github.com/pola-rs/polars/blob/e703ac2ef11547fa701ffa2755f8dbbba2e8ba8b/py-polars/polars/internals/expr/expr.py#L6333) doesn't check for the input type of the column to which the mapping is applied. 

### Reproducible example

```python
# Lazy without string cache
df = pl.DataFrame(
    {
        "country_code": ["FR", None, "ES", "DE"],
    }, 
    schema = {"country_code": pl.Categorical}
).lazy()

df.with_columns(
    pl.col("country_code").map_dict(country_code_dict).alias("remapped")
).collect()


# Eager with string cache
with pl.StringCache():
    df = pl.DataFrame(
        {
            "country_code": ["FR", None, "ES", "DE"],
        }, 
        schema = {"country_code": pl.Categorical}
    )

    df.with_columns(
        pl.col("country_code").map_dict(country_code_dict).alias("remapped")
    )
```

Both fail with 🔽 
```python-traceback
ComputeError                              Traceback (most recent call last)
Cell In[43], line 15
      7 with pl.StringCache():
      8     df = pl.DataFrame(
      9         {
     10             "country_code": ["FR", None, "ES", "DE"],
     11         }, 
     12         schema = {"country_code": pl.Categorical}
     13     )
---> 15     df.with_columns(
     16         pl.col("country_code").map_dict(country_code_dict).alias("remapped")
     17     )

File /usr/local/lib/python3.10/site-packages/polars/internals/dataframe/frame.py:6022, in DataFrame.with_columns(self, exprs, *more_exprs, **named_exprs)
   5871 def with_columns(
   5872     self,
   5873     exprs: IntoExpr | Iterable[IntoExpr] = None,
   5874     *more_exprs: IntoExpr,
   5875     **named_exprs: IntoExpr,
   5876 ) -> Self:
   5877     """
   5878     Add columns to this DataFrame.
   5879 
   (...)
...
   1146     streaming,
   1147 )
-> 1148 return pli.wrap_df(ldf.collect())

ComputeError: ComputeError: the dtype of the join keys don't match. first cast your columns to the correct dtype
```

### Expected behavior

country_code | remapped
-- | --
str | str
"FR" | "France"
null | "Not specified"
"ES" | null
"DE" | "Germany"

### Installed versions

<details>

```
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.28
Python: 3.10.10 (main, Feb  9 2023, 07:44:20) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Looks like the dtype needs to be copied from the input column and assign in both [6297-6298](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/expr/expr.py#L6297-L6298) and 
[6332-6334](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/expr/expr.py#L6333-L6334)

Testing out that change locally makes the second example work.

Without the StringCache is raises an error:
```
ComputeError: ComputeError: Joins/or comparisons on categorical dtypes can only happen 
if they are created under the same global string cache.

Hint: set a global StringCache
```
I guess it's not possible to do without a StringCache?

**Comment by coinflip112** [comment]
Yeah I came to the same conclusion, however I'd say this is not intended behavior. Based on [this](https://pola-rs.github.io/polars-book/user-guide/performance/strings.html?highlight=stringcache#lazy-join-multiple-dataframes-on-categorical-data) I'd assume lazy queries should always have a global string cache, right? 

Obviously this is related to the fact that the we're creating a new df based on the dict mapping and passing it in a map to the expression, but I'm not sure how. I tried wrapping the body of `map_dict` in a string cache but that didn't help as well.

**Comment by ritchie46** [comment]
> 

You must set a global string cache for the whole query up until map_dict for this.

**Comment by coinflip112** [comment]
So something along the lines of https://github.com/pola-rs/polars/pull/7097 could work to handle the categorical dtype issue? Not sure if the phrasing I made in the docstring is correct.

**Comment by ghuls** [comment]
After https://github.com/pola-rs/polars/pull/7797, the remapped column will have pl.Categorical instead of pl.Utf8 as dtype:

```python
In [11]: # Eager with string cache
    ...: with pl.StringCache():
    ...:     df = pl.DataFrame(
    ...:         {
    ...:             "country_code": ["FR", None, "ES", "DE"],
    ...:         },
    ...:         schema = {"country_code": pl.Categorical}
    ...:     )
    ...: 
    ...:     print(
    ...:         df.with_columns(
    ...:             pl.col("country_code").map_dict(country_code_dict).alias("remapped")
    ...:         )
    ...:     )
    ...: 
shape: (4, 2)
┌──────────────┬───────────────┐
│ country_code ┆ remapped      │
│ ---          ┆ ---           │
│ cat          ┆ cat           │
╞══════════════╪═══════════════╡
│ FR           ┆ France        │
│ null         ┆ Not specified │
│ ES           ┆ null          │
│ DE           ┆ Germany       │
└──────────────┴───────────────
```
