### ISSUE TITLE
`Expr.exclude` should work on all multi-column expressions

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7081]
### Problem description

Currently, `exclude` only works after `pl.all()`, after `pl.col("*")`, or after `pl.col` with a regex input.
But I don't see why it shouldn't work on other multi-column expressions, like for example `pl.col(["a", "b"])`.

**Comment by alexanderpils** [comment]
@stinodego  I think you can close it, since it seems to work now if you meant something like this

```
import polars as pl

pl.DataFrame({"a": [1], "b": [5]}).with_columns(
    pl.col(["a", "b"]).exclude("b").cast(pl.Utf8)
)

shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 5   │
└─────┴─────┘
```
