### ISSUE TITLE
groupby ColumnA[str] to aggregate columnB[str] to list, get Wrong type ’list[list[str]]‘ not the Right type 'list[str]' on version 0.16.7

### ISSUE THREAD

**Issue by huacheng** [pola-rs/polars#7090]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

groupby ColumnA[str] to aggregate columnB[str] to list, get Wrong type ’list[list[str]]‘ not the Right type 'list[str]' on version 0.16.7, while the Right type could be get on version 0.14.29.

**1. The Right Result:**

0.14.29
shape: (3, 2)
┌──────┬──────┐
│ aa   ┆ bb   │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ code ┆ 0001 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ code ┆ 0002 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ code ┆ 0003 │
└──────┴──────┘
shape: (1, 2)
┌──────┬──────────────────────────┐
...
│ str  ┆ list[str]                │
╞══════╪══════════════════════════╡
│ code ┆ ["0001", "0002", "0003"] │
└──────┴──────────────────────────┘

**2. The Wrong Result:**

0.16.7
shape: (3, 2)
┌──────┬──────┐
│ aa   ┆ bb   │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ code ┆ 0001 │
│ code ┆ 0002 │
│ code ┆ 0003 │
└──────┴──────┘
shape: (1, 2)
┌──────┬────────────────────────────┐
│ aa   ┆ bb                         │
│ ---  ┆ ---                        │
│ str  ┆ list[list[str]]            │
╞══════╪════════════════════════════╡
│ code ┆ [["0001", "0002", "0003"]] │
└──────┴────────────────────────────┘

### Reproducible example

```python
import polars as pl
print(pl.__version__)
raw_pldf = pl.DataFrame({
    'aa': ['code', 'code', 'code'],
    'bb': ['0001', '0002', '0003']
})
print(raw_pldf)
agg_pldf = (raw_pldf.lazy()
    .groupby(['aa'])
    .agg([
        pl.col('bb').unique(maintain_order=True).list()
    ])).collect()
print(agg_pldf)
```

### Expected behavior

0.14.29
raw_pldf:
shape: (3, 2)
┌──────┬──────┐
│ aa   ┆ bb   │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ code ┆ 0001 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ code ┆ 0002 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ code ┆ 0003 │
└──────┴──────┘

agg_pldf:
shape: (1, 2)
┌──────┬──────────────────────────┐
│ aa   ┆ bb                       │
│ ---  ┆ ---                      │
│ str  ┆ list[str]                │
╞══════╪══════════════════════════╡
│ code ┆ ["0001", "0002", "0003"] │
└──────┴──────────────────────────┘

### Installed versions

<details>
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Windows-10-10.0.17763-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.4.1
numpy: 1.22.2
fsspec: 2022.8.2
connectorx: 0.3.0
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.5.1
</details>

**Comment by cmdlineluser** [comment]
You can remove the `.list()` - https://github.com/pola-rs/polars/issues/6975

**Comment by huacheng** [comment]
Thank you @ritchie46
