### ISSUE TITLE
async api

### ISSUE THREAD

**Issue by ozgrakkurt** [pola-rs/polars#7093]
### Problem description

Currently polars doesn't have an async API. Would be nice to have an async API like datafusion.

Is this feasible to implement?

**Comment by ritchie46** [comment]
There is no added benefit. Polars doesn't have an async event loop.

**Comment by ozgrakkurt** [comment]
It will be useful since it can be used from async context and the entire query is opaque to the client process. If async is implemented internally io can be executed in tokio and compute ops can be executed in rayon threadpool for example. It is not possible to implement this outside of the library

**Comment by ritchie46** [comment]
It is not that trivial. Polars has an execution engine that does not benefit from adding async API methods to the end user. We are exploring async internally but they will not be exposed to the user. We will not have an async API exposed to the end user on our lazy DSL. That will not be useful, not for end users and definitely not for us as code maintainers.
