### ISSUE TITLE
CI: Add `sql` to PR labeler

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#7103]
### Problem description

currently rust & python code is automatically labelled when submitting PR's. 
Ideally anything under `polars-sql` should be labelled with the `sql` label.

**Comment by stinodego** [comment]
The `rust` and `python` labels correspond to those scopes and are used to populate the corresponding changelogs.

There is no dedicated SQL package / release in this repo, so it should not be a scope. You will probably want to use `feat(rust,python)`.

That being said, I don't mind creating a SQL label if that helps you discern SQL issues/PRs.

**Comment by ritchie46** [comment]
I think sql related changes should end up in both the rust and python changelog. Maybe we can pick that up as well?

**Comment by universalmind303** [comment]
so i guess this raises a larger question of the sql roadmap. 

currently we have a minimal cli application for `polars-sql`. Is the long term vision to have this as a standalone application that could be installed via some package manager (brew, apt, pip, ...) similar to `psql` or `duckdb` 

If that is the case, It's likely that we would have independent releases for it as well.

**Comment by stinodego** [comment]
I have recently updated the autolabeler.

`sql` is not available as a type or scope, which means it won't be autolabeled. It's just another 'topic' in our code base. However, there is a tag available, so feel free to tag related issues or PRs with the `sql` label yourself. Marco does this with the `timeseries` label, for example.

I did add `cli` as a scope. So you could do something like `build(cli): Update dependencies` and it will get tagged as `cli`.

Long term vision of the role of the CLI within the Polars space can be discussed in a separate issue.
