### ISSUE TITLE
Make cumfold/cumreduce available for Expression to use them vertical calculation

### ISSUE THREAD

**Issue by alexanderpils** [pola-rs/polars#7108]
### Problem description

Most of the cum* function are available for horizontal/row wise calculation (e.g. polars.cumsum) and also to use on expression for vertical calculation (e.g. polars.expr.cumsum), but the functions cumfold and cumreduce are missing for expression. It would be great if it is possible to add them for vertical calculation.

**Comment by ritchie46** [comment]
And then pass a python function? That would be super slow.

**Comment by alexanderpils** [comment]
Yes I expected that it wouldn't be fast 😄  
I mean my use case would go into that direction for example


```

import polars as pl
import numpy as np

df = pl.DataFrame({"a": [2,3,4,5]})

df.with_columns(
    pl.col("a").cumreduce(lambda acc, x: acc^2 + x).alias("a1"),
    pl.col("a").cumreduce(lambda acc, x: np.exp(acc * (-1)) + x).alias("a2")
)
```

**Comment by alexanderpils** [comment]
I think the proper way if someone needs a functionality is to create an expression plugin
