### ISSUE TITLE
Add pl.cumcount()

### ISSUE THREAD

**Issue by TheWizier** [pola-rs/polars#7120]
### Problem description

Why is cumcount only tied to expression? Would it not usually make more sense as pl.cumcount?
From my understanding cumcount does not actually use the values in the column it is tied to. For instance i would like to do this:
```
>>> df = pl.DataFrame({"a":[1,2,3], "b":[[1,2],[1,2,3],[7,8,9]]})
>>> df
shape: (3, 2)
┌─────┬───────────┐
│ a   ┆ b         │
│ --- ┆ ---       │
│ i64 ┆ list[i64] │
╞═════╪═══════════╡
│ 1   ┆ [1, 2]    │
│ 2   ┆ [1, 2, 3] │
│ 3   ┆ [7, 8, 9] │
└─────┴───────────┘
df.explode("b").with_columns(pl.col("a").cumcount().over("a").alias("c"))
shape: (8, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ u32 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 0   │
│ 1   ┆ 2   ┆ 1   │
│ 2   ┆ 1   ┆ 0   │
│ 2   ┆ 2   ┆ 1   │
│ 2   ┆ 3   ┆ 2   │
│ 3   ┆ 7   ┆ 0   │
│ 3   ┆ 8   ┆ 1   │
│ 3   ┆ 9   ┆ 2   │
└─────┴─────┴─────┘
```

And specifying the column "a" doesnt do anything in this case. So I would rather like to do:

```
df.explode("b").with_columns(pl.cumcount().over("a").alias("c"))
```

**Comment by thomasfrederikhoeck** [comment]
If it had the option to ignore `nulls` I guess it would make sense on column.

**Comment by cmdlineluser** [comment]
I had been using `pl.arange(0, pl.count())` for this.
```
pl.cumcount = lambda: pl.arange(0, pl.count())

df.explode("b").with_columns(pl.cumcount().over("a").alias("c"))
```
```
shape: (8, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 0   │
│ 1   ┆ 2   ┆ 1   │
│ 2   ┆ 1   ┆ 0   │
│ 2   ┆ 2   ┆ 1   │
│ 2   ┆ 3   ┆ 2   │
│ 3   ┆ 7   ┆ 0   │
│ 3   ┆ 8   ┆ 1   │
│ 3   ┆ 9   ┆ 2   │
└─────┴─────┴─────┘
```

**Comment by TheWizier** [comment]
As mentioned by cmdlineluser in #9328  an argument "offset" would also make sense. Would make it more in line with ".with_row_count" as well.

**Comment by TheWizier** [comment]
In case it is of use to someone my current workaround is this:
```
def pl_cumcount(reverse: bool = False) -> pl.Expr:
    return pl.first().cumcount(reverse=reverse)
```

**Comment by stinodego** [comment]
You can use `int_range` in combination with `len` to achieve this.

```
df = pl.DataFrame({"a": [1, 3, 5], "b": [2, 4, 6]})
df.select(
    pl.int_range(pl.len(), dtype=pl.UInt32).alias("index"),
    pl.all(),
)
```
```
shape: (3, 3)
┌───────┬─────┬─────┐
│ index ┆ a   ┆ b   │
│ ---   ┆ --- ┆ --- │
│ u32   ┆ i64 ┆ i64 │
╞═══════╪═════╪═════╡
│ 0     ┆ 1   ┆ 2   │
│ 1     ┆ 3   ┆ 4   │
│ 2     ┆ 5   ┆ 6   │
└───────┴─────┴─────┘
```

We do not plan to add a standalone `cum_count` function at this time. See discussion in https://github.com/pola-rs/polars/issues/12420

**Comment by TheWizier** [comment]
Reading the conclusion to that thread leads me to ask: Should you not also remove expression.cum_count() following this logic as you can just use int ranges instead? I feel this conclusion fails to address the core of this issue which is that there makes no difference what column you call cum_count on.

**Comment by stinodego** [comment]
These are not the same, because `cum_count` ignores nulls.

**Comment by TheWizier** [comment]
I see, that was not the case before. I was not aware that the behavior was changed.
