### ISSUE TITLE
melt vs concat_list...melt is much faster, is that expected?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#7124]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I've got a big df in both dimensions.  I want to do a row-wise quantile of all the (specified) columns.

There are two ways (that I can think of) to do it, one is to melt,groupby,agg

The other is to concat_list,arr.eval

To my surprise, the melt method is 3x faster.

Two questions:
1. Is there a bug in concat_list making it O(n^2) or something like that?
2. Is there a better way to do what I'm trying to do irrespective of whether or not this is a bug

### Reproducible example

```python
#scale the size of your toy df as you see fit (obviously)
num_rows=100
num_rand_cols=1000
df = (
    pl.DataFrame({'a':range(num_rows)})
    .with_columns(pl.Series(np.random.normal(0,1,size=num_rows))
                      .alias(f"col{x}") for x in range(num_rand_cols))
)

## Melt method
(
    df.lazy()
    .melt('a')
    .groupby('a',maintain_order=True)
    .agg(pl.col('value')
         .quantile(round(x*.1,1)).alias(str(round(x*.1,1)))
         for x in range(10))
    .profile()[1]
)

###
    # shape: (4, 3)
    # ┌──────────────────────────┬───────┬───────┐
    # │ node                     ┆ start ┆ end   │
    # │ ---                      ┆ ---   ┆ ---   │
    # │ str                      ┆ u64   ┆ u64   │
    # ╞══════════════════════════╪═══════╪═══════╡
    # │ optimization             ┆ 0     ┆ 28    │
    # │ melt()                   ┆ 28    ┆ 5098  │
    # │ FAST_PROJECT: [value, a] ┆ 5134  ┆ 5141  │
    # │ groupby(a)               ┆ 5147  ┆ 15782 │
    # └──────────────────────────┴───────┴───────┘


## concat method
(
    df.lazy().select(['a', pl.concat_list(pl.exclude('a')).alias('bigL')]) 
    .select(['a'] +  [
             pl.col('bigL').arr.eval(
                 pl.element().quantile(round(x*.1,1)), parallel=True
                ).arr.first().alias(str(round(x*.1,1))) for x in range(10)])
    .profile()[1]
)


# shape: (3, 3)
# ┌─────────────────────────────────────┬───────┬───────┐
# │ node                                ┆ start ┆ end   │
# │ ---                                 ┆ ---   ┆ ---   │
# │ str                                 ┆ u64   ┆ u64   │
# ╞═════════════════════════════════════╪═══════╪═══════╡
# │ optimization                        ┆ 0     ┆ 1378  │
# │ projection(a, bigL)                 ┆ 1378  ┆ 70298 │
# │ projection(a, 0.0, 0.1, 0.2, 0.3... ┆ 72870 ┆ 90289 │
# └─────────────────────────────────────┴───────┴───────┘
```

### Expected behavior

I'd expect the concat_list method to be faster than melt or, at the very least, about the same, not multiples worse.

Is my intuition wrong in thinking that or is there a bug?

### Installed versions

<details>

```
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by ritchie46** [comment]
You are using `arr.eval` in one example. That is expected to be much slower as it is opaque to us what you are doing. `arr.eval` should be seen as last resort.

**Comment by lucazanna** [comment]
Hi @ritchie46 ,

is it possible to share a bit more on why the arr.eval is opaque to the Polars engine?

i have also been trying to find the best way for building transformations in Polars, and curious to understand this part better
