### ISSUE TITLE
write_parquet store struct instead of array 

### ISSUE THREAD

**Issue by dridk** [pola-rs/polars#7130]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

- I save a parquet file from polars DataFrame containing an array type for one column.
- I load the same parquet file from duckdb and it displays the following structure instead.
 ```struct(list usmallint[])```

### Reproducible example

```python
import polars as pl
import duckdb 


df = pl.DataFrame({"a": [[1,1], [2,2], [3,3]]})  
df.write_parquet("a.parquet")   

duckdb.sql("SELECT * FROM 'a.parquet'")  

#┌───────────────────────┐
#│           a           │
#│ struct(list bigint[]) │
#├───────────────────────┤
#│ {'list': [1, 1]}      │
#│ {'list': [2, 2]}      │
#│ {'list': [3, 3]}      │
#└───────────────────────┘

duckdb.sql("SELECT * FROM df")  

#┌─────────┐
#│    a    │
#│ int64[] │
#├─────────┤
#│ [1, 1]  │
#│ [2, 2]  │
#│ [3, 3]  │
#└─────────┘
```

### Expected behavior

Reading parquet file from duckdb should return array type and not structure. 
By the way.. It works if I use pyarrow=True . 

### Installed versions

<details>

```
Polars: 0.16.8
Index type: UInt32
Platform: Linux-5.15.94-1-MANJARO-x86_64-with-glibc2.37
Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.22.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <version not detected>
matplotlib: 3.5.1

```

</details>

**Comment by ritchie46** [comment]
Though this works as expected:

```python
import polars as pl

df = pl.DataFrame({"a": [[1,1], [2,2], [3,3]]})  
df.write_parquet("/tmp/a.parquet")   

assert pl.read_parquet("/tmp/a.parquet", use_pyarrow=True).frame_equal(df)
```

**Comment by universalmind303** [comment]
no longer an issue as of `0.19.19`
