### ISSUE TITLE
from_pandas fails for all nan categorical when the category values have float type

### ISSUE THREAD

**Issue by ChristopherRussell** [pola-rs/polars#7145]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars only supports dictionaries with string-like values. However in the case that all values are null, I don not think the type of the dictionary values is matters.

If you agree I'd like to try doing this as my first contribution. I think a solution would be to add:

```
elif len(array) == array.null_count:
    pli.Series(name,
               array.cast(pa.dictionary(array.type.index_type, pa.utf8())),
               dtype=Categorical)
```

in `arrow_to_pyseries` [here](https://github.com/pola-rs/polars/blob/1bb682d8846a73f35435778f6e7a4dab07d806ed/py-polars/polars/internals/construction.py#L126).

### Reproducible example

```python
import pandas as pd
import polars as pl
all_nan_cat_series = pd.Series([np.nan, np.nan], dtype='category')
pl.from_pandas(all_nan_cat_series)
```
```


### Expected behavior

I'd like to see the result be:

`pl.Series([None, None], dtype=pl.Categorical)`

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: macOS-12.3.1-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by CloseChoice** [comment]
@ChristopherRussell please go ahead and fix this if you feel comfortable. Contributions are always welcome.

**Comment by stinodego** [comment]
This is not a bug. Non-string categoricals are a valid type in pandas and arrow, and that is the type that is passed into Polars. We do not support it. We can then interpret it as a string categorical, but that could lead to confusion by users. It's better to raise an error and force users to sanitize their inputs.
