### ISSUE TITLE
(correctly) process 0 row parquet files

### ISSUE THREAD

**Issue by yuuuxt** [pola-rs/polars#7149]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a 0-row parquet file is loaded using scan_parquet, users can easily get `PanicException: this operation is not implemented/valid for this dtype: Null`, e.g.
- to check the row number (to see if it's 0);
- to sum a certain column (expecting 0 if no row present)

### Reproducible example

```python
import polars as pl

data = pl.scan_parquet("zero_row.parquet") # load successfully

data.select(pl.count()).collect() # PanicException
data.select(pl.col("to_sum").sum()).collect() # PanicException
```

### Expected behavior

```python
import polars as pl

data = pl.scan_parquet("zero_row.parquet") # load successfully

data.select(pl.count()).collect() # better return 0
data.select(pl.col("to_sum").sum()).collect() # better return 0
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Windows-10-10.0.17763-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2021.10.1
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.3
```

</details>

**Comment by stinodego** [comment]
This doesn't really have to do with Parquet, but it does have to do with the Null data type.

`count` will now work correctly. `sum` on a null column does not work yet.
