### ISSUE TITLE
arr functions on pl.List(pl.Float32()) results in SchemaError

### ISSUE THREAD

**Issue by wongjingping** [pola-rs/polars#7165]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi there, 

I was trying to create a nested array in a sequence from #6814 and it seems to be failing to parse the list of floats - wanted to check if this issue is expected?
Not too sure what the issue here is, and would appreciate some guidance debugging this! Also happy to help to fix if pointed in the right direction :)

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({
    "x": pl.Series(values=[[1.0, 2.0, 3.0]], dtype=pl.List(pl.Float32()))
})
result_eager = df.select(pl.col("x").arr.arg_max())
print(result_eager)

$ /Users/jp/miniconda3/bin/python /Users/jp/workspace/polars_py/repro.py
Traceback (most recent call last):
  File "/Users/jp/workspace/polars_py/repro.py", line 5, in <module>
    result_eager = df.select(pl.col("x").arr.arg_max())
  File "/Users/jp/miniconda3/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 5965, in select
    self.lazy()
  File "/Users/jp/miniconda3/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py", line 1160, in collect
    return pli.wrap_df(ldf.collect())
exceptions.SchemaError: Series of dtype: Object("object") != List
```

### Expected behavior

There should not be any errors thrown and result_eager should return something like:
```
shape: (1, 1)
╭─────╮
│ x_0 │
│ --- │
│ i32 │
╞═════╡
│   2 │
╰─────╯
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.9.15 (main, Nov 24 2022, 08:28:41) 
[Clang 14.0.6 ]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
I believe you accidentally made an `Object` type.

I can run your example:

```python
df = pl.DataFrame({
    "x": pl.Series(values=[[1.0, 2.0, 3.0]], dtype=pl.List(pl.Float32()))
})
df.select(pl.col("x").arr.arg_max())
```
```
shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ u32 │
╞═════╡
│ 2   │
└─────┘
```

**Comment by ghuls** [comment]
It gives the reported error in `0.16.8`, but is already fixed in the current master branch.

**Comment by wongjingping** [comment]
Cool thanks for the very fast reply!
