### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by eneszv** [pola-rs/polars#7168]
https://github.com/pola-rs/polars/blob/8d7b8173daa7cfc0c823d0d58d18d5ec6a31e0b5/py-polars/polars/datatypes.py#L45-L46

ImportError: cannot import name 'UnionType' from 'types' (C:\python\lib\types.py)

Python version: 3.10.0b4

**Comment by alexander-beedie** [comment]
Is there a reason that you're using a beta version of Python 3.10? Because I can't see us going out of our way to support that without a good reason, given that it's a beta of a version that released in October 2021 - with support for UnionType ;)

**Comment by eneszv** [comment]
No good reason, someone of my admins had installed this beta version on the machine and I haven't even figured it out until importing Polars. I tried to put 11 instead of 10 but another error appeared with `UnionType = type(Union[int, float])`

AttributeError: module 'types' has no attribute 'UnionType'. Did you mean: 'FunctionType'?

Most likely, the easiest solution for me is to install a stable Python version.

**Comment by alexander-beedie** [comment]
> Most likely, the easiest solution for me is to install a stable Python version.

Sounds like the way to go ;)
I'll close this out.
