### ISSUE TITLE
pl.concat no longer coerces pl.Null columns to a concat-able dtype

### ISSUE THREAD

**Issue by jkc1** [pola-rs/polars#7170]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have some code that ends up creating multiple `pl.DataFrame` objects that I then pass to `pl.concat`. The dataframes have the same schema, and one of the columns is a `struct` with a `field` that happened to have all `null` values. In `polars==0.15.16`, the dataframes get concatenated and the schema for the struct's field with nulls is inferred to be `pl.Int32`, but in `polars>=0.15.17` a panic is triggered.

The traceback changes a bit from 0.15.17 to 0.16.8, but the traceback in 0.16.8 is as follows:
```
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Null', /home/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:507:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[2], line 13
      3 df0 = pl.DataFrame(
      4     {"a": [{"a1": None}, {"a1": None}]},
      5     schema=schema
      6 )
      8 df1 = pl.DataFrame(
      9     {"a": [{"a1": None}, {"a1": None}]},
     10     schema=schema
     11 )
---> 13 pl.concat([df0, df1])

File /opt/conda/envs/…/lib/python3.9/site-packages/polars/utils.py:498, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    496 if len(args) > num_allowed_args:
    497     warnings.warn(msg, DeprecationWarning, stacklevel=2)
--> 498 return function(*args, **kwargs)

File /opt/conda/envs/…/lib/python3.9/site-packages/polars/internals/functions.py:239, in concat(items, rechunk, how, parallel)
    237 if isinstance(first, pli.DataFrame):
    238     if how == "vertical":
--> 239         out = pli.wrap_df(_concat_df(elems))
    240     elif how == "diagonal":
    241         out = pli.wrap_df(_diag_concat_df(elems))

PanicException: this operation is not implemented/valid for this dtype: Null
```

It's a bit ambiguous whether this is a bug or an intended change in behavior, but I figured I'd report it since I didn't see anything in the [release notes](https://github.com/pola-rs/polars/releases/tag/py-0.15.17) for `0.15.17` to indicate that a change in behavior was intended.

This may also be vaguely related to #4854, but is not quite the same.

### Reproducible example

```python
import polars as pl


schema = {"a": pl.Struct([pl.Field("a1", pl.Null)])}

df0 = pl.DataFrame(
    {"a": [{"a1": None}, {"a1": None}]},
    columns=schema
)

df1 = pl.DataFrame(
    {"a": [{"a1": None}, {"a1": None}]},
    columns=schema
)

print(pl.concat([df0, df1]))  # panics in polars>=0.15.17, but runs in 0.15.16
print("schema:", pl.concat([df0, df1]).schema)
```

### Expected behavior

Either of the following would be preferred to the `panic`:
  - schema remains the same i.e. `{"a": pl.Struct([pl.Field("a1", pl.Null)])}`
  - the old behavior (cast to `pl.Int32`)
  

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Linux-5.10.165-143.735.amzn2.x86_64-x86_64-with-glibc2.27
Python: 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by nanthony007** [comment]
Not sure if this is intended behavior but I came here with the same issue.

**Comment by astrowonk** [comment]
Yes, specifically reading in parquet data some files a column may be all null, others it may have floats, and I want to successfully concatenate these together. When data is broken across many files (i.e. by date) the column types may appear different even under the same name. So we we need to be able to concat null columns in one file with float columns in another.

**Comment by Wainberg** [comment]
I'm also running into this on polars 0.18.15.

`pl.Series('col1', [None])` has dtype `pl.Float32` (which is strange in and of itself; isn't this the point of having a `pl.Null` dtype?), so concatenating with a non-float32 column gives an error:

```python
>>> pl.concat([pl.DataFrame({'col1': ['foo']}), pl.DataFrame({'col1': [None]})])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/functions/eager.py", line 168, in concat
    out = wrap_df(plr.concat_df(elems))
                  ^^^^^^^^^^^^^^^^^^^^
exceptions.ShapeError: unable to vstack, dtypes for column "col1" don't match: `str` and `f32`
```

Even if you explicitly force the all-null column to have the `pl.Null` dtype, the concatenation still fails:

```python
>>> pl.concat([pl.DataFrame({'col1': ['foo']}), pl.DataFrame({'col1': [None]}, schema={'col1': pl.Null})])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/functions/eager.py", line 168, in concat
    out = wrap_df(plr.concat_df(elems))
                  ^^^^^^^^^^^^^^^^^^^^
exceptions.ShapeError: unable to vstack, dtypes for column "col1" don't match: `str` and `null`
```

To fix this:

1. `pl.Series('col1', [None])` should have the dtype `pl.Null`, not `pl.Float32`.
2. `pl.Null` columns should be automatically coerced to the type of the same-named column in the other dataframe when concatenating.

**Comment by romanovacca** [comment]
I reran the MRE on 0.19.8

```
import polars as pl

schema = {"a": pl.Struct([pl.Field("a1", pl.Null)])}

# note: in the original example, the argument was called `columns` instead of `schema`

df0 = pl.DataFrame(
    {"a": [{"a1": None}, {"a1": None}]},
    schema=schema
)

df1 = pl.DataFrame(
    {"a": [{"a1": None}, {"a1": None}]},
    schema=schema
)


```

in 0.16.8, 
`print(pl.concat([df0, df1])) `
 raised 
`PanicException: this operation is not implemented/valid for this dtype: Null`

But in the latest (0.19.8) it does not produce a panic anymore.
```
>>> print(pl.concat([df0, df1])) 
shape: (4, 1)
┌───────────┐
│ a         │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {null}    │
│ {null}    │
│ {null}    │
│ {null}    │
└───────────┘
```

Can this be closed @stinodego ?

**Comment by stinodego** [comment]
Yes, thanks @romanovacca !

**Comment by jkc1** [comment]
Thank you all for fixing this!
