### ISSUE TITLE
Improve `Duration => Utf8` cast; currently returns stringified physical (Int64) representation 

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#7174]
### Problem description

At the moment casting `Duration` data to `Utf8` (string) isn't very useful; it gets converted to physical (i64) and is stringified from there; ideally we should probably re-use the same string conversion/formatting done on frame display, like so:

```python
from datetime import timedelta
import polars as pl

df = pl.DataFrame(
    {'dur': [timedelta(days=1,seconds=123, microseconds=987654)]}
)
print(df)
# ┌───────────────────┐
# │ dur               │
# │ ---               │
# │ duration[μs]      │
# ╞═══════════════════╡
# │ 1d 2m 3s 987654µs │  << cast to string should produce this format?
# └───────────────────┘
```
**Current behaviour:** _(stringified i64; not useful)_
```python
df.select( pl.col('dur').cast(pl.Utf8) ).item()
# '86523987654'
```
**Preferred behaviour:** _(reuse display string-formatting for consistency)_
```python
df.select( pl.col('dur').cast(pl.Utf8) ).item()
# '1d 2m 3s 987654µ'
```
**Partial workaround:** _(requires inefficient call into python, and not quite the same format)_
```python
df.select( pl.col('dur').apply(str) ).item()
# '1 day, 0:02:03.987654'
```

**Comment by cmdlineluser** [comment]
Someone did ask about this on StackOverflow recently, they had issues when converting to Excel:

https://stackoverflow.com/a/78322388/
