### ISSUE TITLE
The polars.DataFrame.shuffle parameter is misleading

### ISSUE THREAD

**Issue by foxcroftjn** [pola-rs/polars#7176]
### Polars version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

[polars.DataFrame.sample](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.sample.html) contains a parameter named `shuffle`. The documentation for this parameter reads:

> Shuffle the order of sampled data points.

My interpretation for this is that setting `shuffle` to `False` would result in the resulting sampled rows being returned in their original order. Instead, the `shuffle` parameter controls whether shuffling is performed as an additional step after the sample is extracted.

Sampling is performed by the [choose_multiple_fill](https://docs.rs/rand/latest/rand/seq/trait.IteratorRandom.html#method.choose_multiple_fill) method in the rand crate. The documentation for this method states:

> Although the elements are selected randomly, the order of elements in the buffer is neither stable nor fully random. If random ordering is desired, shuffle the result.

I assume this is the reason that the shuffle parameter exists for `polars.DataFrame.sample`.

### Reproducible example

```python
import polars as pl
pl.DataFrame([1, 2, 3, 4]).sample(n=3, shuffle=False, seed=1)
```

### Expected behavior

I expect the sampled points to be in the original sorted order. This particular example actually returns:
```
shape: (3, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ i64      │
╞══════════╡
│ 4        │
│ 2        │
│ 3        │
└──────────┘
```

I believe that this issue is most easily addressed by updating the documentation to make it clear that when `shuffle=False`, "the order of the returned rows will be deterministic, but neither stable nor fully random". Alternatively, the sample function could be re-implemented to behave more intuitively based upon the current documentation.

I would be interested in submitting a pull request to address this issue, but I would like some feedback first on which direction makes the most sense.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: 1.23.0
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by ritchie46** [comment]
Could you please make a PR where you add additional information to the docstrings about the sampling methods?
