### ISSUE TITLE
`series.argsort()` silently returns `None`

### ISSUE THREAD

**Issue by NikolayXHD** [pola-rs/polars#7182]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I can see that `series.argsort()` is deprecated since polars v0.16.5
https://github.com/pola-rs/polars/pull/6829/files#diff-3a08830abd195ca97f7bac2440ab91ca3cca23e817931a43385d8ba1c3dc4a09R2001

> `Series.argsort` will be removed in favour of **`Series.arg_sort`.**

However with polars v0.16.8  `series.argsort()` silently returns `None`, instead of reporting a call to missing Python method.

### Reproducible example

```
kolia@kde ~/g/sandbox-nb (master)> python                                                                                                                                                                                                       (/home/kolia/git/sandbox-nb/envs)
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> pl.__version__
'0.16.8'
>>>
>>> ds = pl.Series([3, 4, 5, 1])
>>> ds.arg_sort()
shape: (4,)
Series: '' [u32]
[
        3
        0
        1
        2
]
>>> ds.argsort()                                                                                                                         
>>>
>>> type(ds.argsort())
<class 'NoneType'>
>>>
```

### Expected behavior

Failing with something like "missing attribute error"

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Linux-6.1.12-arch1-1-x86_64-with-glibc2.37
Python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by zundertj** [comment]
Fixed in #7183.
