### ISSUE TITLE
polars.Series.str.strptime parse PM

### ISSUE THREAD

**Issue by rkrueck** [pola-rs/polars#7187]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Parsing US locale time string with `.str.strptime(pl.Datetime)` fails when time is PM (evening). It works when time is AM (morning). With `strict=False` the result is Null.
Currently using .apply with user defined python function for time parsing instead.

### Reproducible example

```python
pl.DataFrame({'date':["02/21/23 09:02 PM"]}).select(pl.col('date').str.strptime(pl.Datetime, "%m/%d/%y %H:%M %P")


ComputeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 print(pl.DataFrame({'date':["02/21/23 09:02 PM"]}).select(pl.col('date').str.strptime(pl.Datetime, "%m/%d/%y %H:%M %P", strict=True)))

File .conda\envs\311\Lib\site-packages\polars\internals\dataframe\frame.py:5967, in DataFrame.select(self, exprs, *more_exprs, **named_exprs)
   5856 def select(
   5857     self,
   5858     exprs: IntoExpr | Iterable[IntoExpr] | None = None,
   5859     *more_exprs: IntoExpr,
   5860     **named_exprs: IntoExpr,
   5861 ) -> Self:
   5862     """
   5863     Select columns from this DataFrame.
   5864 
   (...)
   5962 
   5963     """
   5964     return self._from_pydf(
   5965         self.lazy()
   5966         .select(exprs, *more_exprs, **named_exprs)
-> 5967         .collect(no_optimization=True)
   5968         ._df
   5969     )
...
   1158     streaming,
   1159 )
-> 1160 return pli.wrap_df(ldf.collect())

ComputeError: strict conversion to dates failed, maybe set strict=False
```
```


### Expected behavior

```
shape: (1, 1)
╭─────────────────────╮
│ date (datetime[μs]) │
╞═════════════════════╡
│ 2023-02-21 21:02:00 │
╰─────────────────────╯
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by cmdlineluser** [comment]
You can use `%I` (which is the 12-hour specifier) instead of `%H`

Related: https://github.com/chronotope/chrono/issues/256

**Comment by rkrueck** [comment]
Perfect. Thank you
