### ISSUE TITLE
Add Discussions to polars github

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#7189]
### Problem description

GitHub has a [Discussions feature](https://docs.github.com/en/discussions/quickstart) that needs to be enabled on a per-repository basis. I think it would be nice to have this for posts such as #7178 which aren't an issue per se.

Not a big deal if people don't want this, but it helps separate out general discussion from actual issues which contribute to the devs' burnup/down charts.

**Comment by aldanor** [comment]
(OP of the referenced issue here) to be fair, I did reach out first to see if there's discussions section available and didn't find any :)

Sounds like a good place to discuss design/implementation problems on one side, and for folks to discuss usage of the library and benchmarks on the other.

// In some big repos (not to name any) the discussions section also ends up serving as a dumpster for downgraded issues (eg "not really an issue or we're not sure what to do with it, so your issue has been moved to discussions, discuss it there") which may sometimes have a negative effect if it happens too often.

**Comment by ritchie46** [comment]
I didn't like the indirection. When we had discussions, people used it as issues and this for lost. I also believe we have enough channels already. More than I can cope at least. 😅

We have issues, our discord and Stackoverflow.

**Comment by mcrumiller** [comment]
@ritchie46 sounds good, no complaints here.

/close
