### ISSUE TITLE
Support selecting columns from `other` table before `join` method

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#7190]
### Problem description

Polars seems to have a design philosophy of mimicking SQL as closely as possible, which I think is great. Polars uses declarative queries, but it's not clear to what extent the order of application of `DataFrame` \ `LazyFrame` methods matters. Based on my (limited) SQL experience, I expect to be able to specify the columns that I am selecting before I specify the join. But this doesn't work:

```python
In [14]: df1 = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

In [15]: df2 = pl.DataFrame({"a": [1, 2, 3], "c": [7, 8, 9]})

In [16]: df1.select("a", "c").join(df2, how="left", on="a")
# Traceback elided for clarity.
ColumnNotFoundError: c
```

It does work if I put the `select` method after the `join` method:

```python
In [17]: df1.join(df2, how="left", on="a").select("a", "c")
Out[17]: 
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ c   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 7   │
│ 2   ┆ 8   │
│ 3   ┆ 9   │
└─────┴─────┘
```

Of course, SQL requires prefixing each column by the table name (or table alias) in order to disambiguate columns. I'm not aware of a similar feature in Polars. So, this leads to two questions:

1. Can support for `select` before `join` be added to Polars?
2. If not, can the current behavior be better documented?

**Comment by alexander-beedie** [comment]
Ahh... this is a bit of an illusion on the SQL side; you _aren't_ really specifying the columns before the join ;)

You're actually saying _"from this operation that already happened, I'd like to further pick out these columns"_ (in other words, you are SELECTing FROM something - where the "something" has already been constructed; it's the same behaviour in SQL and Polars).

The actual order of execution in SQL is: 

1) `JOIN`
2) `WHERE`
3) `GROUP BY`
4) `HAVING`
5) `SELECT`  << happens almost last ;)
6) `ORDER BY`
7) `LIMIT/OFFSET`

**Comment by mcrumiller** [comment]
@CameronBieganek the confusion you're having is cleared up if you require using mandatory prefixes to your fields:

```sql
SELECT
  df1.a,
  df2.c
FROM
  df1
LEFT
  JOIN df2
ON
  df1.a = df2.a;
```

Aas @alexander-beedie said, the `SELECT` statement in SQL filters the columns from the *result* of the join.

**Comment by CameronBieganek** [comment]
> the confusion you're having is cleared up if you require using mandatory prefixes to your fields:

Yep, I mentioned prefixes in my OP.

> This is the logical order in which the SQL query parser (or, indeed, anything similar) will operate; it's also the order in which you need to declare operations/expressions in polars

It would probably be good to mention that somewhere in the manual. I don't recall reading that when I studied the docs. :)
