### ISSUE TITLE
Auto-infer tz-aware date strings

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7198]
### Problem description

I'm working on a PR to allow for auto-inferring time zone-aware strings, i.e.:
```python
In [2]: pl.Series(['2020-01-01T00:00:00Z']).str.strptime(pl.Datetime)
Out[2]: 
shape: (1,)
Series: '' [datetime[μs, +00:00]]
[
        2020-01-01 00:00:00 +00:00
]
```
just like how
```python
In [3]: pl.Series(['2020-01-01T00:00:00']).str.strptime(pl.Datetime)
Out[3]: 
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 00:00:00
]
```
currently works for naive ones.

I'm opening an issue to say - if this would not be welcome, I'd appreciate it if someone could please stop me before I spend too long on it

**Comment by ritchie46** [comment]
I think this would be a nice feature to have. Given performance, I think we should sniff the format in the first n rows and then determine if we parse timezone aware or not.

Already had some ideas on this?

**Comment by MarcoGorelli** [comment]
I was thinking it would involve:

1. adding a pattern to 

   https://github.com/pola-rs/polars/blob/3ed3c5846212aa3a7388123a8258d1aea55080b8/polars/polars-time/src/chunkedarray/utf8/patterns.rs#L145-L150

2. adding a timezone-aware version of

   https://github.com/pola-rs/polars/blob/1fe6430600a1dd2b085c7201833059066a1092c1/polars/polars-time/src/chunkedarray/utf8/infer.rs#L169-L178

   and similarly for other resolutions. This would need to depend on the `utc` parameter. It would also need to take a `time_zone` argument, based on the time zone inferred from the first row. The time zone for each parsed row would need to be matched against it, unless `utc=True`, just like is done here

https://github.com/pola-rs/polars/blob/1fe6430600a1dd2b085c7201833059066a1092c1/polars/polars-time/src/chunkedarray/utf8/mod.rs#L423-L437

(but instead of erroring, it would return `None`)

> I think we should sniff the format in the first n rows

I may have missed something, but I don't see why `n` rows should be used in this case, as opposed to just the first one as is normally done. If the format is detected to be `pattern::DatetimeYMDZ` then all rows would be parsed with the latest pattern found to be working from the `DatetimeYMDZ` list, which wouldn't get mixed with the non-aware patterns lists
