### ISSUE TITLE
Read and write back of a feather file to same filename raises 'Bus error'

### ISSUE THREAD

**Issue by collinsethans** [pola-rs/polars#7199]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

While porting my app from pandas to polars, I find that writing back a polars df read from feather to the same file name raises Bus error.

I am attaching the code snippets and the respective feather file, DY_1.fea. More comments embedded in the snippets.

Thanks to 'thomasaarholt' (on discord) for testing out a few more cases and providing more data points. His initial testing on Mac OS didn't reproduce the failures though.

Note: In my testing, changing the file format to paraquet or csv didn't crash, with the same test cases.

### Reproducible example

```python
import polars as pl

df = pl.read_ipc('/tmp/fea_pl/dy/DY_1.fea')

df.write_ipc('/tmp/fea_pl/dy/temp.fea')   # temporary, leaving DY_1.fea unchanged
df = pl.read_ipc('/tmp/fea_pl/dy/temp.fea')
df.write_ipc('/tmp/fea_pl/dy/temp.fea')   # <- Bus error


# Other examples where the read/write sequence _Fails_.
# #2
df = pl.read_ipc('temp.fea')
df = df.select(df.columns[::-1]) # reverse order columns
df.write_ipc('temp.fea')

# #3
df = pl.read_ipc('temp.fea')
df = df.select(["open", "dy_dt", "low", "high", "vol", "close", "dvol"]) # Choose random order
df.write_ipc('temp.fea')

# #4
df = pl.read_ipc('temp.fea')
df = df.vstack(kf)    # kf: a legit dataframe
df.write_ipc('temp.fea')


# Some examples where the read/write sequence _doesn't fail_.
# #1
df = pl.read_ipc('temp.fea')
df = kf.vstack(df)    # kf prepend, ie at the top
df.write_ipc('temp.fea')

# #2
df = pl.read_ipc('temp.fea')
df = df.select(["dy_dt", "open", "high", "low", "close", "vol", "dvol"]) # column order unchanged
df.write_ipc('temp.fea')
```

### Expected behavior

No exception.

### Installed versions

pl.__version__
'0.16.3'
-> Also tested to fail on: 0.16.8, 0.16.9

Debian:
Linux quant 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

```
>>> pl.show_versions()
---Version info---
Polars: 0.16.3
Index type: UInt32
Platform: Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3

```
[DY_1.fea.gz](https://github.com/pola-rs/polars/files/10834195/DY_1.fea.gz)
</details>

**Comment by ritchie46** [comment]
The file is memory mapped. So writing to the same file is UB. I think we should keep a file handle open.

We should better implicate consequences of memory mapping in the docstrings.

You can set `memory_map=False` to resolve this.

**Comment by collinsethans** [comment]
@ritchie46 

Thanks for your response. Does having memory map cause this code to fail as well?

df = pl.read_ipc('temp.fea')
df = df.vstock(kf)    # kf: a legit dataframe
df.write_ipc('temp.fea')

**Comment by ritchie46** [comment]
Yes, you still write to a memory mapped region. You must turn memory mapping off.

**Comment by collinsethans** [comment]
@ritchie46 

Thanks much, that works (memory_map=False).

However, the same kind of failure should manifest with read/write parquet to same file, but it doesn't. I tried with compression='uncompressed', use_pyarrow=True, memory_map=True. (I cross-checked the SHA256 of the file before and after the write and it's unchanged as well).

**Comment by ritchie46** [comment]
> @ritchie46
> 
> Thanks much, that works (memory_map=False).
> 
> However, the same kind of failure should manifest with read/write parquet to same file, but it doesn't. I tried with compression='uncompressed', use_pyarrow=True, memory_map=True. (I cross-checked the SHA256 of the file before and after the write and it's unchanged as well).

We cannot memory map parquet files 1:1 so eventually we read data to memory. 
IPC is arrow on disk so we can mmap 1:1.
