### ISSUE TITLE
Series dtype inference based on the type of the first anyvalue

### ISSUE THREAD

**Issue by aldanor** [pola-rs/polars#7212]
Currently, it seems like when `Series` is constructed from any-values, it simply grabs the first non-null value and uses that to convert all other values to it? This may lead to some weird examples like:

```python
>>> pl.Series([datetime.now(), 3.1415])  # swap these to get an error
shape: (2,)
Series: '' [datetime[μs]]
[
	2023-02-27 02:30:28.538807
	1970-01-01 00:00:00.000003   # uh, well...
]
```
(pandas would simply cast both to 'object')

Should it just always raise an error in cases like this? Is there are a better way to handle this kind of cases?

**Comment by ritchie46** [comment]
We should error. For `pl.Series([datetime.now(), "foo"]) ` it errors. Somewhere an conversion should be more strict in your expample.

**Comment by aldanor** [comment]
I think it works because the primitive type for datetimes is int64 and extracting ints out of floats does work somewhere along the way.

Plus, conversion logic is (at least one branch of it) based on the type of the first non-null element, that's pretty unobvious for the user - swap the order and get different result.

**Comment by lars-reimann** [comment]
I also find the conversion logic quite confusing: In `polars` v0.17.6, the following code

```py
import polars as pl
from datetime import datetime

series = pl.Series([1, True, "a", datetime.now(), None])

print(list(series))
```

prints `[None, None, 'a', None, None]`. Here it doesn't seem to be based on the type of the first element anymore but keep only the strings.

**Comment by stinodego** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/11156
