### ISSUE TITLE
The enum variant LiteralValue::Series cannot be serialized

### ISSUE THREAD

**Issue by DSAureli** [pola-rs/polars#7230]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Adding literal columns to a LazyFrame makes it fail to serialize to json, while it doesn't affect the collection to DataFrame.

### Reproducible example

```python
import polars as pl
import numpy as np
ldf_series_lit = pl.LazyFrame().with_columns([
	pl.Series("col_1", np.array([1,1]), pl.Int16),
	pl.lit(2, pl.Int16).alias("col_2")
	])
ldf_series_lit.collect()  # no problem
ldf_series_lit.write_json()

#Traceback (most recent call last):
#  File "...", line 8, in <module>
#    ldf_series_lit.write_json()
#  File "C:\Users\...\miniconda3\envs\...\lib\site-packages\polars\internals\lazyframe\frame.py", line 723, in write_json
#    self._ldf.write_json(buf)
#ValueError: Error("the enum variant LiteralValue::Series cannot be serialized", line: 0, column: 0)
```

### Expected behavior

The LazyFrame gets serialized to json without errors.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by YellowFoxH4XOR** [comment]
The issue here is collect() returns ` return pli.wrap_df(ldf.collect())` and as per your code you are not storing it.

You can try this
```
import polars as pl
import numpy as np
ldf_series_lit = pl.LazyFrame().with_columns([
	pl.Series("col_1", np.array([1,1]), pl.Int16),
	pl.lit(2, pl.Int16).alias("col_2")
	]).collect()
ldf_series_lit.write_json()
```
OR
```
import polars as pl
import numpy as np
ldf_series_lit = pl.LazyFrame().with_columns([
	pl.Series("col_1", np.array([1,1]), pl.Int16),
	pl.lit(2, pl.Int16).alias("col_2")
	])
ldf_series_lit = ldf_series_lit.collect()
ldf_series_lit.write_json()
```

**Comment by DSAureli** [comment]
@YellowFoxH4XOR 

Thank you for your comment, but I think you didn't get the issue here. I'm aware I'm not storing the return of the collection, that line is included in the example just to show that collecting the LazyFrame does not raise exceptions (and indeed, if you print it you can see that the result is correct). The issue here is that the LazyFrame (and not the DataFrame resulting from the collection) should be serializable to json, and consequently restorable from that json. However, when adding a column with a literal, this is not possible. I hope it is clearer now.

**Comment by YellowFoxH4XOR** [comment]
In Polars, LazyFrame is a delayed computation that does not execute until you explicitly trigger it, either by calling the collect().

Calling write_json() on a LazyFrame does not trigger the computation plan to execute. Instead, it tries to serialize the plan itself (DAG if I am not wrong), which results in an error because the plan is not a valid JSON object.
