### ISSUE TITLE
PySeries.new_from_anyvalues loses microsecond precision

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7232]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In the below example, notice how the microseconds in the result match for the tz-naive case, but not for the tz-aware one

### Reproducible example

```python
In [62]: pl.Series([datetime(2514, 5, 30, 1, 53, 4, 986754)])
Out[62]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2514-05-30 01:53:04.986754
]

In [63]: pl.Series([datetime(2514, 5, 30, 1, 53, 4, 986754, tzinfo=dt.timezone.utc)])
Out[63]:
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2514-05-30 01:53:04.986756 UTC
]
```

### Expected behavior

In the second case
```python
In [63]: pl.Series([datetime(2514, 5, 30, 1, 53, 4, 986754, tzinfo=dt.timezone.utc)])
Out[63]:
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2514-05-30 01:53:04.986754 UTC
]
```

The issue is that in the tz-aware case,

https://github.com/pola-rs/polars/blob/8d5585d59d4ae039275aecbf7ffa7f7f9dbaed20/py-polars/polars/internals/construction.py#L329-L332

`PySeries.new_from_anyvalues` is used.

And in that one, in 

https://github.com/pola-rs/polars/blob/9cfc987fd18025a410f1028ccac6c9bcdc99c900/py-polars/src/series.rs#L227-L232

`avs` will already have incorrectly converted to `int`:
```
[Datetime(17179869184986756, Microseconds, None)]
```

But that number is incorrect:
```
In [7]: dt.datetime(1970, 1, 1, tzinfo=dt.timezone.utc) + dt.timedelta(microseconds=17179869184986756)
Out[7]: datetime.datetime(2514, 5, 30, 1, 53, 4, 986756, tzinfo=datetime.timezone.utc)
```

It should be `17179869184986754`:
```python
In [8]: dt.datetime(1970, 1, 1, tzinfo=dt.timezone.utc) + dt.timedelta(microseconds=17179869184986754)
Out[8]: datetime.datetime(2514, 5, 30, 1, 53, 4, 986754, tzinfo=datetime.timezone.utc)
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.6
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by aldanor** [comment]
Just to link it here, perhaps somewhat related or same code branches: https://github.com/pola-rs/polars/issues/7212
