### ISSUE TITLE
Something like `DataFrame.item()` to select the unique column in a dataframe

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#7249]
### Problem description

Sometimes I have queries that only return one column.
For example, I often end up with code that looks like this:
`df.lazy().filter(...).select("column_name").unique().collect().get_column("column_name")`.
Since LazyFrames don't have a `.get_column()` method, this feels unavoidable.

I was thinking it would be nice to have something like `DataFrame.get_only_column()`.

I realize that writing `"column_name"` twice isn't all that burdensome, and typing out `get_only_column()` isn't much easier...
So maybe this is a dumb idea. I just thought it couldn't hurt too much to ask.

**Comment by ritchie46** [comment]
I think you want `df.to_series()`.

**Comment by alexander-beedie** [comment]
You can use the column selector `df[:,0]`, which maps to `df.to_series(0)` ;)

**Comment by s-banach** [comment]
Someday I will say something intelligent.
It hasn't happened yet, but give it a few years.
