### ISSUE TITLE
Inconsistent behavior for `is_duplicated` on multiple columns.

### ISSUE THREAD

**Issue by rob-superty** [pola-rs/polars#7254]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The `is_duplicated` method seems to behave inconsistently when applied to multiple columns in an expression.

**First inconsistency**
Within `filter`, the expression `pl.col("foo", "bar").is_duplicated()` returns all rows where the value in `foo` is not unique and the value in `bar` is not unique.  That is, it returns rows where **both** columns have a non-unique value, the equivalent of: 
```
(pl.col("foo").is_duplicated()) & (pl.col("bar").is_duplicated())
```
*Side note, and **not** why I'm raising this issue: I intuitively expected the expression to return rows where the values in `foo` and `bar` were duplicated **as a pair**, similar to the `subset` parameter in `pandas`.  Potentially something that can be clarified in the documentation.*

When this expression is **negated**, it behaves differently.  The expression `~pl.col("foo", "bar").is_duplicated()` is true when **neither** `foo` **nor** `bar` are duplicated.  That is, it's equivalent to:

```python
~((pl.col("foo").is_duplicated()) | (pl.col("bar").is_duplicated()))
```

Notice the `|` rather than the `&` here.   

The result is for `expr = pl.col("foo", "bar").is_duplicated()`, `df.filter(expr)` and `df.filter(~expr)` are not complementary -- there are rows that are not returned in either statement.  If the positive version returns rows where both columns are duplicated, then the negation should return rows where either column is not duplicated, rather than requiring that they both be unique. From a logical standpoint, a row should always either satisfy `expr` or `~expr`.

**Second inconsistency**

That same expression, `pl.col("foo", "bar").is_duplicated()` behaves completely differently in the statement

```python
df.with_columns(pl.col("foo", "bar").is_duplicated()).alias("test_column")
```

In this case, the value in `foo` is completely ignored, and the mask returns true if and only if `bar` is duplicated.  Reversing the order of the two parameters means that `foo` is the only column considered.  So in a `with_columns` statement, only the last column is used, which is different from the `filter`.

### Reproducible example

```python
**Test 1: expr and ~expr not complementary**


>>> import polars as pl
>>> df = pl.DataFrame(
...     {
...         "foo": ["A", "A", "A", "A", "X", "Y"],
...         "bar": ["B", "B", "C", "Q", "C", "Z"],
...     }
... )
>>> df
shape: (6, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
│ A   ┆ Q   │
│ X   ┆ C   │
│ Y   ┆ Z   │
└─────┴─────┘
>>> expr = pl.col("foo", "bar").is_duplicated()
>>> # rows (A, B), (A, B), and (A, C) are returned
>>> df.filter(expr)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
└─────┴─────┘
>>> # row (Y, Z) returned
>>> df.filter(~expr)
shape: (1, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ Y   ┆ Z   │
└─────┴─────┘
>>> # rows (A, Q) and (X, C) do not satisfy either expr or ~expr


**Test 2: with_columns behavior different and order dependent**

```python
>>> import polars as pl
>>> df = pl.DataFrame(
...     {
...         "foo": ["A", "A", "A", "A", "X", "Y"],
...         "bar": ["B", "B", "C", "Q", "C", "Z"],
...     }
... )
>>> # same dataframe
>>> df
shape: (6, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
│ A   ┆ Q   │
│ X   ┆ C   │
│ Y   ┆ Z   │
└─────┴─────┘
>>> expr = pl.col("foo", "bar").is_duplicated()
>>> df.filter(expr)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
└─────┴─────┘
>>> # with_columns returns all rows where bar duped, including (X, C)
>>> df.with_columns(expr.alias("test_result"))
shape: (6, 3)
┌─────┬─────┬─────────────┐
│ foo ┆ bar ┆ test_result │
│ --- ┆ --- ┆ ---         │
│ str ┆ str ┆ bool        │
╞═════╪═════╪═════════════╡
│ A   ┆ B   ┆ true        │
│ A   ┆ B   ┆ true        │
│ A   ┆ C   ┆ true        │
│ A   ┆ Q   ┆ false       │
│ X   ┆ C   ┆ true        │
│ Y   ┆ Z   ┆ false       │
└─────┴─────┴─────────────┘
>>> # reverse the column names
>>> expr2 = pl.col("bar", "foo").is_duplicated()
>>> # filter is the same
>>> df.filter(expr2)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
└─────┴─────┘
>>> # now with_columns returns rows where foo duped, including (A, Q)
>>> df.with_columns(expr2.alias("test_result"))
shape: (6, 3)
┌─────┬─────┬─────────────┐
│ foo ┆ bar ┆ test_result │
│ --- ┆ --- ┆ ---         │
│ str ┆ str ┆ bool        │
╞═════╪═════╪═════════════╡
│ A   ┆ B   ┆ true        │
│ A   ┆ B   ┆ true        │
│ A   ┆ C   ┆ true        │
│ A   ┆ Q   ┆ true        │
│ X   ┆ C   ┆ false       │
│ Y   ┆ Z   ┆ false       │
└─────┴─────┴─────────────┘
```
```


### Expected behavior

**Test 1**

```python
>>> import polars as pl
>>> df = pl.DataFrame(
...     {
...         "foo": ["A", "A", "A", "A", "X", "Y"],
...         "bar": ["B", "B", "C", "Q", "C", "Z"],
...     }
... )
>>> df
shape: (6, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
│ A   ┆ Q   │
│ X   ┆ C   │
│ Y   ┆ Z   │
└─────┴─────┘
>>> expr = pl.col("foo", "bar").is_duplicated()
>>> df.filter(expr)
>>> # intuitively I expected only rows where the pair was duplicated
shape: (6, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
└─────┴─────┘
>>> # but at least this would be consistent
>>> df.filter(expr)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
└─────┴─────┘
>>> df.filter(~expr)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ Q   │
│ X   ┆ C   │
│ Y   ┆ Z   │
└─────┴─────┘
```

*** Test 2***
```python
>>> import polars as pl
>>> df = pl.DataFrame(
...     {
...         "foo": ["A", "A", "A", "A", "X", "Y"],
...         "bar": ["B", "B", "C", "Q", "C", "Z"],
...     }
... )
>>> # same dataframe
>>> df
shape: (6, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
│ A   ┆ Q   │
│ X   ┆ C   │
│ Y   ┆ Z   │
└─────┴─────┘
>>> expr = pl.col("foo", "bar").is_duplicated()
>>> df.filter(expr)
shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ str ┆ str │
╞═════╪═════╡
│ A   ┆ B   │
│ A   ┆ B   │
│ A   ┆ C   │
└─────┴─────┘
>>> # result should be consistent with filter
>>> df.with_columns(expr.alias("test_result"))
shape: (6, 3)
┌─────┬─────┬─────────────┐
│ foo ┆ bar ┆ test_result │
│ --- ┆ --- ┆ ---         │
│ str ┆ str ┆ bool        │
╞═════╪═════╪═════════════╡
│ A   ┆ B   ┆ true        │
│ A   ┆ B   ┆ true        │
│ A   ┆ C   ┆ true        │
│ A   ┆ Q   ┆ false       │
│ X   ┆ C   ┆ false       │
│ Y   ┆ Z   ┆ false       │
└─────┴─────┴─────────────┘
>>> # reverse the column names
>>> expr2 = pl.col("bar", "foo").is_duplicated()
>>> # result should not depend on column ordering
>>> df.with_columns(expr2.alias("test_result"))
shape: (6, 3)
┌─────┬─────┬─────────────┐
│ foo ┆ bar ┆ test_result │
│ --- ┆ --- ┆ ---         │
│ str ┆ str ┆ bool        │
╞═════╪═════╪═════════════╡
│ A   ┆ B   ┆ true        │
│ A   ┆ B   ┆ true        │
│ A   ┆ C   ┆ true        │
│ A   ┆ Q   ┆ false       │
│ X   ┆ C   ┆ false       │
│ Y   ┆ Z   ┆ false       │
└─────┴─────┴─────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: macOS-12.5.1-arm64-arm-64bit
Python: 3.9.10 (main, Nov  9 2022, 15:38:08) 
[Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by lucazanna** [comment]
Hi @rob-superty ,

I believe this might be similar to a ticket a couple of weeks ago: https://github.com/pola-rs/polars/issues/6808

The solution I found in the meanwhile was to always specify pl.any() or pl.all() when filtering based on multiple columns

**Comment by rob-superty** [comment]
@lucazanna definitely similar and probably the same underlying root cause, so thanks for pointing that out!

I think the main point is that it should never be possible to have filters on `expr` and `~expr` that don't end up with 100% of the rows -- in my particular case I am passing an `expr` around into a more general utility function that needs to negate it for some of the behavior. The function shouldn't have to know how `expr` was constructed, but it should be able to rely on the fact that every row should either satisfy `expr` or `~expr`, with nothing "falling between the cracks" (which in my case is a major issue leading to important data being lost).

The difference between `filter` and `with_columns` is also a bit strange here, and maybe related?  But it could be a different issue altogether -- wasn't sure if I should keep them in the same ticket tbh!

**Comment by rob-superty** [comment]
FWIW this statement does I was trying to achieve when I came across the bug:

`df.with_columns(pl.struct(["foo", "bar"]).alias("combined")).filter(pl.col("combined").is_duplicated())`

**Comment by cmdlineluser** [comment]
With regards to `.with_columns` - it's actually `.alias` that is the reason for the output.

If you use `.suffix()` for example, you can see both columns:
```
df.with_columns(pl.col("foo", "bar").is_duplicated().suffix("_bool"))
```
```
shape: (6, 4)
┌─────┬─────┬──────────┬──────────┐
│ foo | bar | foo_bool | bar_bool │
│ --- | --- | ---      | ---      │
│ str | str | bool     | bool     │
╞═════╪═════╪══════════╪══════════╡
│ A   | B   | true     | true     │
│ A   | B   | true     | true     │
│ A   | C   | true     | true     │
│ A   | Q   | true     | false    │
│ X   | C   | false    | true     │
│ Y   | Z   | false    | false    │
└─────┴─────┴──────────┴──────────┘
```

With `.alias()` it's essentially doing:

```
df.with_columns(
   pl.col("foo").is_duplicated().alias("bool"),
   pl.col("bar").is_duplicated().alias("bool")
)
```
```
shape: (6, 3)
┌─────┬─────┬───────┐
│ foo | bar | bool  │
│ --- | --- | ---   │
│ str | str | bool  │
╞═════╪═════╪═══════╡
│ A   | B   | true  │
│ A   | B   | true  │
│ A   | C   | true  │
│ A   | Q   | false │
│ X   | C   | true  │
│ Y   | Z   | false │
└─────┴─────┴───────┘
```
So both expressions end up with the same name and the "last one wins".

There was a recent issue questioning this behaviour: https://github.com/pola-rs/polars/issues/7045

**Comment by rob-superty** [comment]
@cmdlineluser Ahh, that makes a lot of sense re: `alias`. I do agree it's unintuitive.  I didn't even realize that the `pl.col("foo", "bar").is_duplicated()` expression was returning two values to begin with. Especially tricky as I mentioned when passing the expression object.  It looks like the truthiness of (true, false) is determined to be neither, but maybe there should be at least an ambiguity warning like there is for an entire series?
