### ISSUE TITLE
`Expr.str.to_titlecase` to transform string to title case

### ISSUE THREAD

**Issue by ajhynes7** [pola-rs/polars#7255]
### Problem description

It would be helpful if polars had an expression to transform a string into title case. It would have the same behaviour as the `title` string method in Python.

The name could be `to_titlecase` since there's already `to_lowercase` and `to_uppercase`.

Example:

```py
>>> df = pl.DataFrame({"foo": ["hello world"]})

>>> df.select(pl.col("foo").str.to_titlecase())["foo"][0]
'Hello World'
```

**Comment by stinodego** [comment]
Current `to_lowercase` and `to_uppercase` implementations rely on Rust's native `str` methods:
https://doc.rust-lang.org/std/primitive.str.html#method.to_lowercase

Rust does not offer native support for other formats such as title case. If we want to implement this, we'd have to write those functions ourselves, or possibly rely on a dependency like [inflections](https://docs.rs/inflections/latest/inflections/case/fn.is_title_case.html) (which seems to be outdated).

I would like these additional string methods to be available in Polars. @ritchie46 do you have an opinion on how this should be implemented? I'd like to take a crack at this.

**Comment by ritchie46** [comment]
This functionality doesn't justify an extra dependency. We can simply add a small `to_title_case` function:

In psuedo code:
```rust
fn to_title_case(value: &str) -> Cow<str> {

loop {
// search space
// if not return

// otherwise uppercase element before and repeat 
}
}
```

Then we can apply that function over our `Utf8Chunked`.

**Comment by ghuls** [comment]
FYI. The last maintained inflecitons version, seems to be: https://github.com/chrislearn/cruet
