### ISSUE TITLE
pl.read_sql(bigquery) takes very long

### ISSUE THREAD

**Issue by Sonycyberbiz** [pola-rs/polars#7267]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I would greatly appreciate some insight on the benefits of using `polars.read_sql()` instead of my current approach. Currently, I'm using the BigQuery client to retrieve query results with the arrow type and then converting the result to a polars dataframe, which seems to be faster. However, I'm curious about when one might choose to use `polars.read_sql()` instead. Would anyone be able to offer some guidance?
<img width="1055" alt="Screenshot 2023-03-01 at 5 15 05 PM" src="https://user-images.githubusercontent.com/88647236/222096307-b907ae51-eecc-4d1c-9ebd-ebf6498e0ab6.png">
<img width="1015" alt="Screenshot 2023-03-01 at 5 16 34 PM" src="https://user-images.githubusercontent.com/88647236/222096314-0a5a8d5b-e2dd-4cdf-89f0-4be9470c431d.png">

### Reproducible example

```python
from google.cloud import bigquery
import polars as pl
query_string = f'SELECT * except(event_params) FROM `{project_name}.{dataset}.{table}`' 
bigquery_client = bigquery.Client()
try:
    result = bigquery_client.query(query_string)
except ValueError as error:
        raise error

%%time
arrow_result = result.to_arrow()

%%time
df = pl.from_arrow(arrow_result)

%%time
conn = 'bigquery://' + authentication_file_path
query = f'SELECT * FROM `{project_name}.{dataset}.{table}`'
df = pl.read_sql(query, conn)
```

### Expected behavior

I thought that using `pl.read_sql()` would be a better approach.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: Darwin-22.2.0-x86_64-i386-64bit
Python: 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.3.5
numpy: 1.20.3
fsspec: 2021.11.1
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by alexander-beedie** [comment]
This is probably a better question for the `connectorx` folks, as we just pass-through to that. However, if there is consistently this sort of dramatic difference (6-7 secs vs nearly 3 mins!), it would be good to get an explanation, as we might want to change how we handle this when the caller has the BigQuery module available...

**Comment by Sonycyberbiz** [comment]
I've been experiencing long load times when test to use connector-x.
Additionally, I encountered an issue when using `connectorx.read_sql(conn=conn, query=query, return_type="polars")`,
which appears to produce incorrect results compared to `connectorx.read_sql(conn=conn, query=query, return_type="arrow2")`.
I'm planning to post this two question on the connector-x issue board. 
Thank you for your help.
<img width="975" alt="Screenshot 2023-03-02 at 11 23 58 AM" src="https://user-images.githubusercontent.com/88647236/222324680-56fe3be7-abd4-4bb0-9f9c-c4c0f9f15b51.png">
<img width="967" alt="Screenshot 2023-03-02 at 11 24 21 AM" src="https://user-images.githubusercontent.com/88647236/222324689-e24e1afd-636b-402f-a031-27e90f89a450.png">

**Comment by zundertj** [comment]
Closing here, as this is really an upstream issue.

**Comment by set92** [comment]
I am uncertain if this should be closed, connectorx hasn't responded in 2 weeks, so I think is also a problem of polars.

Keeping this as the exclusive way to interact with bigquery I think is risky, for example in my case I don't have a service account, since I use `gcloud auth application-default login` and seems that doesn't work because connectorx is searching for private-code inside my auth.json, which doesn't exist. 

So, I think it would be better to have a flag to use the bigquery client or connectorx, and not depend exclusively on them.

**Comment by ritchie46** [comment]
It is not exclusive. BigQuery also exports to arrow. If you think we should extend support, feel free to open a PR.

In any case. The issue regarding connectorx is upstream and should be handled there.
