### ISSUE TITLE
implementation error, cannot get ref Utf8 from Struct

### ISSUE THREAD

**Issue by wKollendorf** [pola-rs/polars#7281]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When trying to create a struct from a Utf8 column, where all values are None, the operation fails. In contrast to that, everything is fine with dtype Float64 e.g.

### Reproducible example

```python
def fn(x):
    if x:
        return {"value": str(x), "type":"bar"}
    else:
        return {"value": "", "type":"bar"}

df = pl.DataFrame({
   "foo": [None, None]
}, schema={"foo": pl.Utf8})

df = df.with_columns([
    pl.when(
        pl.col('foo').is_not_null() 
    ).then(
        pl.col('foo').apply(lambda x: fn(x))
    ).otherwise(
        pl.lit('None').apply(lambda x: fn(None))
    ).alias('foo')
])
```

### Expected behavior

return Dataframe with foo (dtype struct[2]).

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: Windows-10-10.0.17763-SP0
Python: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.3.5
numpy: 1.21.6
fsspec: <not installed>
connectorx: 0.3.1_alpha.9
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
You must set `skipp_null=False`. I have opened a PR to raise an error in this case.
