### ISSUE TITLE
Set pl.Config.set_tbl_cols(5) as the default

### ISSUE THREAD

**Issue by arturdaraujo** [pola-rs/polars#7282]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The datasets with more than 5 columns are often messy on the terminal, I think that pl.Config.set_tbl_cols(8) may be too much. Would it be okay to make the number of columns between 4 and 6 the new default? 
I believe that most of the datasets (or at least a lot of them) have more than 8 columns, I believe this would be beneficial to most of the people that read the datarame out of the terminal. 

If not set to 5, at least 6. This would be a really nice marginal gain. 
I believe that this makes sense for a wider audience with normal-sized computer screens. At least while we don't find a way to automatically set the number of columns.

- https://github.com/pola-rs/polars/issues/6447
- https://github.com/pola-rs/polars/issues/6105

### Reproducible example

```python
-
```

### Expected behavior

-

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.3```

</details>

**Comment by stinodego** [comment]
With 8 columns, I would get a DataFrame of 90 characters wide if I create it like this:

```python
import polars as pl
data = [[123456] for i in range(8)]
df = pl.DataFrame(data)
print(df)
```
```
shape: (1, 8)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ column_5 ┆ column_6 ┆ column_7 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆ i64      ┆ i64      ┆ i64      ┆ i64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ 123456   ┆ 123456   ┆ 123456   ┆ 123456   ┆ 123456   ┆ 123456   ┆ 123456   ┆ 123456   │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```

I would think most people will be able to display that just fine. Of course the width may be different depending on the column names / content, but I think lowering the default number of columns would be detrimental.

We should really address https://github.com/pola-rs/polars/issues/6105 instead.

Closing this as not planned.
