### ISSUE TITLE
Support compressed csv in `scan_csv`

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars#7287]
### Problem description

It would be nice if polars could load compressed csvs out of the box, e.g.  a `zstd` compressed csv.

I'm not sure what the best workaround is. `xopen` doesn't seem to work:

```python
import polars as pl
import xopen 

#%%
with xopen.xopen("metadata_germany.tsv.zst", "rt") as f:
    pl.scan_csv(f, has_header=True, sep="\t").head(10).collect()
```
raises: 
```
TypeError: argument 'path': 'TextIOWrapper' object cannot be converted to 'PyString'
```

Related: https://github.com/pola-rs/polars/issues/3166

**Comment by corneliusroemer** [comment]
Now I'd also like `zstd` support for `ndjson` - would be great to be able to read from compressed files.

**Comment by natir** [comment]
A rust xopen alternative is [niffler](https://github.com/luizirber/niffler/).

Sorry for self promoting, but I'm also need this feature, maybe niffler could help polars.

**Comment by ghuls** [comment]
You can use `parquet-fromcsv` in the meantime to convert compressed CSV/TSV files to parquet and use `pl.scan_parquet` on them:
https://github.com/pola-rs/polars/issues/9283#issuecomment-1594512827

**Comment by nameexhaustion** [comment]
Closed as completed via https://github.com/pola-rs/polars/pull/17841
