### ISSUE TITLE
expanding_apply function

### ISSUE THREAD

**Issue by yanxiu0614** [pola-rs/polars#7292]
### Problem description

I tried polars and its performance is amazing, thanks for this awesome project

I am going to  turn more work to  use polars, but in my work, the expanding function is very important. I read the documentation, I found that polar has some functions that can support this work, but when it comes to some more complicated work, polars Seemed powerless. For example,  z-score

So, I was hoping to provide a function like expanding_apply. Thank you so much.

**Comment by s-banach** [comment]
What does expanding_apply do, and why do you need it to calculate z scores?

**Comment by yanxiu0614** [comment]
> What does expanding_apply do, and why do you need it to calculate z scores?

same as rolling_apply

**Comment by s-banach** [comment]
Your code works for me, although I don't exactly understand what it does.
```python
import numpy as np
import polars as pl

df = pl.DataFrame({"value": np.random.standard_normal(7)})

def zscore(series, n=3):
    mean = series.mean()
    std = series.std()
    high = mean + n * std
    low = mean - n * std
    series = series.clip(low, high)
    minval = series.min()
    return (series[-1] - minval) / (series.max() - minval)

print(df.with_columns(df["value"].rolling_apply(zscore, 3).alias("zscore")))
"""
shape: (7, 2)
┌───────────┬──────────┐
│ value     ┆ zscore   │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ -0.998595 ┆ null     │
│ -1.209972 ┆ null     │
│ 0.764033  ┆ 1.0      │
│ -0.349515 ┆ 0.435894 │
│ -2.182496 ┆ 0.0      │
│ 0.953167  ┆ 1.0      │
│ -0.909635 ┆ 0.40593  │
└───────────┴──────────┘
"""
```
How do you want it to work differently?

**Comment by yanxiu0614** [comment]
> Your code works for me, although I don't exactly understand what it does.
> 
> ```python
> 
> import numpy as np
> 
> import polars as pl
> 
> 
> 
> df = pl.DataFrame({"value": np.random.standard_normal(7)})
> 
> 
> 
> def zscore(series, n=3):
> 
>     mean = series.mean()
> 
>     std = series.std()
> 
>     high = mean + n * std
> 
>     low = mean - n * std
> 
>     series = series.clip(low, high)
> 
>     minval = series.min()
> 
>     return (series[-1] - minval) / (series.max() - minval)
> 
> 
> 
> print(df.with_columns(df["value"].rolling_apply(zscore, 3).alias("zscore")))
> 
> """
> 
> shape: (7, 2)
> 
> ┌───────────┬──────────┐
> 
> │ value     ┆ zscore   │
> 
> │ ---       ┆ ---      │
> 
> │ f64       ┆ f64      │
> 
> ╞═══════════╪══════════╡
> 
> │ -0.998595 ┆ null     │
> 
> │ -1.209972 ┆ null     │
> 
> │ 0.764033  ┆ 1.0      │
> 
> │ -0.349515 ┆ 0.435894 │
> 
> │ -2.182496 ┆ 0.0      │
> 
> │ 0.953167  ┆ 1.0      │
> 
> │ -0.909635 ┆ 0.40593  │
> 
> └───────────┴──────────┘
> 
> """
> 
> ```
> 
> How do you want it to work differently?


Thank you for your patience.

This code is used to calculate the zscore of time series data

Maybe I didn't describe my needs clearly ，I hope polars can provide a function expanding_apply, which functions like rolling_apply.

in this way,I can call like this.
print(df.with_columns(df["value"].expanding_apply(zscore, 3).alias("zscore")))

**Comment by cmdlineluser** [comment]
If the term `expanding` is from pandas as in [pandas.DataFrame.expanding](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.expanding.html):

With size `N = 2`
```
import polars as pl

N = 2
df = pl.DataFrame(dict(A=[0, 1, 2, 3, 4]))
df.to_pandas().expanding(N).apply(lambda x: [print("*" * 10), print(x), 1][-1])
```
```
**********
0    0.0
1    1.0
dtype: float64
**********
0    0.0
1    1.0
2    2.0
dtype: float64
**********
0    0.0
1    1.0
2    2.0
3    3.0
dtype: float64
**********
0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
```
It looks like that is the same as passing `df.height - 1` as the `window_size` and setting `min_periods=N` 
```
df.select(pl.col("A").rolling_apply(lambda x: [print("*" * 10), print(x), x][-1], window_size=df.height - 1, min_periods=N))
```
```
**********
shape: (2,)
Series: '' [i64]
[
	0
	1
]
**********
shape: (3,)
Series: '' [i64]
[
	0
	1
	2
]
**********
shape: (4,)
Series: '' [i64]
[
	0
	1
	2
	3
]
**********
shape: (4,)
Series: '' [i64]
[
	1
	2
	3
	4
]
```
Compared to using `window_size=N`
```
df.select(pl.col("A").rolling_apply(lambda x: [print("*" * 10), print(x), x][-1], window_size=N))
**********
shape: (2,)
Series: '' [i64]
[
	0
	1
]
**********
shape: (2,)
Series: '' [i64]
[
	1
	2
]
**********
shape: (2,)
Series: '' [i64]
[
	2
	3
]
**********
shape: (2,)
Series: '' [i64]
[
	3
	4
]
```
Or perhaps I'm mistaken?

**Comment by cmdlineluser** [comment]
I was curious and tried changing the `>=` check on https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/ops/rolling_window.rs#L86
```
if options.window_size >= self.len() {
```
To just `>`
```
if options.window_size > self.len() {
```
Which allows the `df.height` example to run.
```
window_size=df.height, min_periods=N
```
Not sure if that change affects anything else - but it seems to fully enable the "expanding" behaviour?
