### ISSUE TITLE
LazyFrame.join doesn't respect LazyFrame.cache() nodes

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#7293]
### Polars version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Stumbled upon this issue seeing some UDFs were being called multiple times on the same data. I thought I had used `LazyFrame.cache()` correctly throughout the graph, but it seems like there's some cases where it's not respected. Narrowed things down to an isolated example using joins.

### Reproducible example

In this example, `map_df1` and `map_df2` will each be called twice. If you added another type of join to `collect_all`, they'd all be called 3 times.

```python
def map_df1(df):
  print("map df1")
  return df

def map_df2(df):
  print("map df2")
  return df

df1 = pl.LazyFrame({"a": [1]}).map(map_df1).cache()
df2 = pl.LazyFrame({"a": [2]}).map(map_df2).cache()
pl.collect_all([df1.join(df2, on="a"), df2.join(df1, on="a")])
# map df1
# map df2
# map df1
# map df2
```

WIP test case:  https://github.com/pola-rs/polars/compare/pola-rs:a979252...josh:402d148

### Expected behavior

If I'm understanding `cache()` correctly. The UDF should only be evaluated once per DF and the cache result should be passed to each join.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: Linux-5.4.0-1103-azure-x86_64-with-glibc2.31
Python: 3.11.2 (main, Feb 25 2023, 04:31:29) [GCC 9.4.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: <not installed>
numpy: 1.24.2
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by josh** [comment]
I started investigating this myself. But I couldn't quite figure out where in the executor cache nodes were supposed to be retrieved. Any pointers and I'll jump back in to see if I can figure it out and come up with a PR. Thanks!

**Comment by josh** [comment]
Thinking about this some more.... it might have more do to with the parallelization query planning than specific to joins. The issue surfaces itself with `pl.concat` as well. But with `pl.concat` you can disable parallelization with a flag. That appears to fix the issue.

Should cache node computation be wrapped in a lock so they are only computed once per entire plan? Or is this just a caveat of cached node that maybe just gets documented better?

**Comment by ritchie46** [comment]
This is not how caches work. They are not remained between query plans and evey `cache`call creates a new cache independent of another equal graph.

Caches are also not really meant to be set by end users, as we set them internally already.

**Comment by gab23r** [comment]
I think this would be resolved if pl.collect_all could make commun subplan elimination which is not currently the case. But this would definitely be a killer feature !

**Comment by josh** [comment]
The `join` was kinda a red herring to discovering the root issue, which is that cache nodes often hit a race condition during parallel execution. See #7313.
