### ISSUE TITLE
Casting `Time` to `Datetime` gives unexpected results

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7302]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I believe the cast simply keeps the underlying integer value the same. But this results in behaviour that may be strange to the user.

### Reproducible example

```python
import polars as pl
from datetime import time

s = pl.Series([time(10,0,0), time(11,30,59)])

# Nanosecond precision makes sense
s.cast(pl.Datetime(time_unit='ns'))

# shape: (2,)
# Series: '' [datetime[ns]]
# [
#         1970-01-01 10:00:00
#         1970-01-01 11:30:59
# ]

# Other precision gives unexpected results
s.cast(pl.Datetime(time_unit='us'))

# shape: (2,)
# Series: '' [datetime[μs]]
# [
#         1971-02-21 16:00:00
#         1971-04-25 20:23:20
# ]

# This works though...
s.cast(pl.Datetime(time_unit='ns')).cast(pl.Datetime(time_unit='us'))

# shape: (2,)
# Series: '' [datetime[μs]]
# [
#         1970-01-01 10:00:00
#         1970-01-01 11:30:59
# ]


```

### Expected behavior

I would expect the time to remain the same regardless of time unit, with the 'date' component at some fixed value (e.g. 1970-01-01).

### Installed versions

master branch

**Comment by alexander-beedie** [comment]
Definitely wrong/weird ;) Combining a time with a date is really what `combine` is for, though I guess the unix epoch is the "least unexpected" option if we allow this - the other option is to raise an exception (that could suggest use of "combine").

**Comment by ritchie46** [comment]
Yes, we should raise an error and suggest `combine`.

**Comment by stinodego** [comment]
The reason I suggested using a "default" date is that it is consistent with how casting `Date` to `Datetime` adds a default time (`00:00`).

Pandas uses a default date of `1900-01-01` when casting from time to datetime. We could do something similar, or use epoch (`1970-01-01`).

**Comment by ritchie46** [comment]
Why makes that more sense than `combine`. It is really implicit behavior. I don't think there is any reason I'd want to cast to 1900.

People will the write `col(..).cast(..) + duration(year=100)` to cast to the year 2000. And reading this, this would not be clear to me.

A `combine` on the other hand would be readable and explicit.

**Comment by stinodego** [comment]
> A Date to Datetime feels to me much more natural that that is a time of 0:00.

That's definitely true. Using combine would therefore be preferred. I'm fine with raising an exception on this cast.

For reference, I ran into this because I'm implementing `DataFrame.write_delta`, and Delta does not support time types. I decided to just raise an error on time columns as casting to Datetime is just iffy.

**Comment by ritchie46** [comment]
>  I decided to just raise an error on time columns as casting to Datetime is just iffy.

Yeap, sounds good 👍
