### ISSUE TITLE
Error interpreting some f64 values using scientific notation in JSON data

### ISSUE THREAD

**Issue by DeliciousHair** [pola-rs/polars#7312]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Apologies up front for the verbosity, but even getting this issue to appear takes some doing.

TLDR version: if JSON data contains values like `2e-06`  (or other "small" values) then the `e` character (or something) is causing a panic at a rather low level.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidDigit(0)'
```

### Reproducible example

```rust
use polars_io::prelude::*;
use polars_lazy::prelude::*;
use std::error::Error;
use std::io::Cursor;

fn main() -> Result<(), Box<dyn Error>> {
    let sample = r#"
        [
            {
                "date": "ts_00",
                "comments": "abc 123",
                "val": 2e-06
            }
        ]"#;
    let json = Cursor::new(sample);
    let df = JsonReader::new(json).finish()?.lazy();

    println!("df: {:?}", &df.collect()?);

    Ok(())
}
```

### Expected behavior
Using `python-polars`, we get the expected result:
```python
pl.DataFrame(json.loads(sample))

 
shape: (1, 3)
┌───────┬──────────┬──────────┐
│ date  ┆ comments ┆ val      │
│ ---   ┆ ---      ┆ ---      │
│ str   ┆ str      ┆ f64      │
╞═══════╪══════════╪══════════╡
│ ts_00 ┆ abc 123  ┆ 0.000002 │
└───────┴──────────┴──────────┘
```

### Installed versions

```toml
[dependencies]
polars-io = { version = "0.27.2", features = [
        "json",
        "dtype-struct",
        "fmt",
    ] }
polars-lazy = { version = "0.27.2", features = [
        "json",
        "dtype-struct",
    ] }
```

**Comment by DeliciousHair** [comment]
UPDATE:

I have tracked the error down to this line:

https://github.com/pola-rs/polars/blob/d5ca27e6a71fadd2af819637ecc1af9628c49681/polars/polars-io/src/json.rs#L172-L173

```rust
                let json_value = json::read::json_deserializer::parse(bytes)
                    .map_err(|err| PolarsError::ComputeError(format!("{err:?}").into()))?;
```

I have no idea how one might go about fixing this, nor why the error is happening though.

**Comment by DeliciousHair** [comment]
fixed via https://github.com/jorgecarleitao/json-deserializer/issues/20

**Comment by DeliciousHair** [comment]
It would seem that I was using a local hack that I did to make this work and the fix referenced has not made it into the 0.29 release (had not done a `cargo clean` in a while). Problem is still present in `arrow2` and `polars` as a result.

**Comment by ritchie46** [comment]
We use `simd-json` now for all json parsing, so can you check on main if this is still a valid issue.

**Comment by DeliciousHair** [comment]
Thanks, I'll try that now. But FWIW, with version 0.29 owing to values like `-2e-6` in the response data I am getting the error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidDigit(0)', /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.17.0/src/io/json/read/deserialize.rs:88:67
```

since the release is using the un-patched version of `json-deserializer`

**Comment by ritchie46** [comment]
Yeap, that crate is unmaintained and we don't use it anymore. We will release a new rust release after #9022 is merged

**Comment by DeliciousHair** [comment]
That does the trick, thanks so much! Re-closing this issue.
