### ISSUE TITLE
`DataFrame.write_database` rounds floats

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7328]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There is already a test for this - just delete a single line in the tests to reproduce this.

### Reproducible example

```python
import os
import sqlite3
import tempfile

import polars as pl

df = pl.DataFrame(
    {
        "id": [1, 2],
        "name": ["misc", "other"],
        "value": [100.0, -99.5],
        "date": ["2020-01-01", "2021-12-31"],
    }
)

with tempfile.TemporaryDirectory() as tmpdir_name:
    test_db = os.path.join(tmpdir_name, "test.db")
    df.write_database(
        table_name="test_data",
        connection_uri=f"sqlite:///{test_db}",
        if_exists="replace",
        engine="adbc",
    )
    result = pl.read_database("SELECT * FROM test_data", f"sqlite:///{test_db}")

print(result)
```

Results in:

```
shape: (2, 4)
┌─────┬───────┬───────┬────────────┐
│ id  ┆ name  ┆ value ┆ date       │
│ --- ┆ ---   ┆ ---   ┆ ---        │
│ i64 ┆ str   ┆ f64   ┆ str        │
╞═════╪═══════╪═══════╪════════════╡
│ 1   ┆ misc  ┆ 100.0 ┆ 2020-01-01 │
│ 2   ┆ other ┆ -99.0 ┆ 2021-12-31 │
└─────┴───────┴───────┴────────────┘
```

### Expected behavior

Original values should be retained. Note the float value changed from `-99.5` to `-99.0`!

It would be nice if the dates were also parsed correctly as a `Date` type, but I guess that's less critical.

### Installed versions

master branch

**Comment by ritchie46** [comment]
Hmm... I think this is a bug upstream in `adbc`.

**Comment by stinodego** [comment]
Yep, I should open an issue there. Will get to that later.

**Comment by stinodego** [comment]
Issue opened at arrow adbc repo:
https://github.com/apache/arrow-adbc/issues/578

**Comment by stinodego** [comment]
This has now been fixed upstream. Once they issue a new release, one of our `write_database` tests will fail. I propose we close this ticket once that happens and we have fixed that test.
