### ISSUE TITLE
pl.Series.sort callable support

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#7332]
### Problem description

I want to know if there is an existing way to perform an operation identical to what `functools.cmp_to_key` offers. [Stackoverflow for a quick reference](https://stackoverflow.com/questions/32752739/how-does-the-functools-cmp-to-key-function-work).

If there isn't, may I please request support for _custom_ comparison functions to be included in `polars`, perhaps as an argument to `pl.Series.sort` and related sorting functions? My very basic understanding is that this function will likely run in Python, so it cannot likely be parallelized. If it can't be added, may I at least know how to implement a custom sorting function similar to `functools.cmp_to_key`?

**Comment by ritchie46** [comment]
>  If it can't be added, may I at least know how to implement a custom sorting function similar to functools.cmp_to_key?

Create an auxiliary column that will serve as the sorting key. You really don't want to call a python function on every compare. That will 100x slower than my proposed approach.

**Comment by avimallu** [comment]
Okay, so in either event (using `polars` or not) I'll need to sort it outside of `polars` to be efficient. Thanks!

I'll close this in a while!

**Comment by ritchie46** [comment]
> Okay, so in either event (using `polars` or not) I'll need to sort it outside of `polars` to be efficient. Thanks!
> 
> I'll close this in a while!

No, I think you should create an extra column with keys that are sortable by us. The sort is parallel here.

**Comment by avimallu** [comment]
Oh, I don't think I was clear. I do understand that the key should be sortable inside `polars`.

To *create* that column though, I'd need my custom comparison performed *anyway*, so I would need to create those keys either inside `polars` (via an `apply`) or outside it.

**Comment by ritchie46** [comment]
> Oh, I don't think I was clear. I do understand that the key column should be sortable inside `polars`.
> 
> To _create_ that column though, I'd need my custom comparison performed _anyway_, so I would need to create those keys either inside `polars` (via an `apply`) or outside it.

Yes, but that key generation would only execute n times, not nlogn times. Nor would it interfere with parallelism in our sort.

**Comment by avimallu** [comment]
Okay, got it. Thank you!
