### ISSUE TITLE
Add streaming explode

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#7334]
### Problem description

See: https://stackoverflow.com/questions/75630121/optimize-polars-csv-load-to-prevent-oom-crash

**Comment by ThomasMAhern** [comment]
Thank you for the expedient help!

**Comment by hristo-mavrodiev** [comment]
It's going Out of Memory on large datasets, when using `explode` and `unnest` .
Please also add the `streaming` for `unnest` function
![image](https://user-images.githubusercontent.com/61916767/222904817-d980a4be-bde3-4f0d-bcde-1953b60dc067.png)

**Comment by hristo-mavrodiev** [comment]
Just compile from sources from commit ` af2a1247f0af5b` , but still goes out of memory.

**Comment by ritchie46** [comment]
What is your query? Can you show a `show_graph`?

**Comment by hristo-mavrodiev** [comment]
![image](https://user-images.githubusercontent.com/61916767/222978960-616c1843-fa2f-4182-8f07-ef38244e047a.png)
![image](https://user-images.githubusercontent.com/61916767/222979113-2ad73a20-b7e2-4540-94c6-652554e08014.png)

**Comment by ritchie46** [comment]
Don't collect into memory befoee sinking to parquet. A collect always loads into memory.

**Comment by hristo-mavrodiev** [comment]
Yes, but the there is `not supported error`. So even we use `collect(streaming=True)` will populate the memory and need to avoid it?
![image](https://user-images.githubusercontent.com/61916767/222979841-86a1e460-24e6-4d84-aebb-35cd36281871.png)

**Comment by ritchie46** [comment]
Right. Scan delta is not yet supported in streaming.

**Comment by hristo-mavrodiev** [comment]
Got `Dead Kernel` with `scan_parquet` and `sink_parquet` also: 
![image](https://user-images.githubusercontent.com/61916767/222983321-66fffece-9be7-4c36-a19d-54fb6d1a0c63.png)
Also increased the virtual RAM to 45 GB in ` pagefile.sys`, but got OOM again.

**Comment by hristo-mavrodiev** [comment]
![image](https://user-images.githubusercontent.com/61916767/222983677-7790bccf-4e31-4f9c-9d7c-6c699be570ca.png)

**Comment by ritchie46** [comment]
Right. Could you share your file perhaps?

**Comment by ritchie46** [comment]
Does explode increase the number of rows much?

**Comment by hristo-mavrodiev** [comment]
Yes, I need to ask for permissions to share it tomorrow. 
The input data is approx 1GB with 22milion rows, but highly nested. The rows are expanded exponentially.
Just tested 200rows are creating ~18 000 rows exploded

**Comment by ritchie46** [comment]
> Yes, I need to ask for permissions to share it tomorrow. The input data is approx 1GB with 22milion rows, but highly nested. The rows are expanded exponentially. Just tested 200rows are creating ~18 000 rows exploded

Right. That explains it. We must give users the possibility to control the batch size.

**Comment by hristo-mavrodiev** [comment]
I have permissions to disclose the schema of the data.
```
{'DayOfMonth': Int32,
 'HourOfDay': Int32,
 'Key': Utf8,
 'Month': Int32,
 'Offset': Int64,
 'Partition': Int32,
 'RunId': Int32,
 'Timestamp': Datetime(tu='ns', tz=None),
 'Topic': Utf8,
 'Value': Struct([Field('contracts', List(Struct([Field('contractId', Int64), Field('product', Utf8), Field('shortName', Utf8), Field('longName', Utf8), Field('deliveryStartMsUtc', Int64), Field('deliveryEndMsUtc', Int64), Field('revision', Utf8), Field('state', Utf8), Field('npsContractId', Int64), Field('orderBooks', List(Struct([Field('deliveryAreaId', Utf8), Field('revision', Int64), Field('state', Utf8), Field('tradingPhase', Utf8), Field('tradingStartMsUtc', Int64), Field('tradingEndMsUtc', Int64), Field('offers', List(Struct([Field('orderId', Int64), Field('npsOrderId', Int64), Field('quantity', Int64), Field('price', Int64), Field('entryMsUtc', Int64), Field('executionRestriction', Utf8), Field('orderType', Utf8)]))), Field('bids', List(Struct([Field('orderId', Int64), Field('npsOrderId', Int64), Field('quantity', Int64), Field('price', Int64), Field('entryMsUtc', Int64), Field('executionRestriction', Utf8), Field('orderType', Utf8)])))])))])))]),
 'Year': Int32}```

**Comment by hristo-mavrodiev** [comment]
[test1_sampledata.zip](https://github.com/pola-rs/polars/files/10914424/test1_sampledata.zip)
Added 1 row of data that could be sampled 22mililion rows
```test_data.sample(n=22_000_000, seed=1,with_replacement=True) ```
