### ISSUE TITLE
Review experimental functionality

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#7349]
### Issue description

Currently, we have quite some functionality marked as experimental (grepping code base for "experimental"):

Series:
* `cumulative_eval`
* `qcut`
* `hist`
* `dt.round`
* `cat.uses_lexical_ordering`

Expr:
* `rolling_min`
* `rolling_max`
* `rolling_mean`
* `rolling_sum`
* `rolling_std`
* `rolling_var`
* `rolling_median`
* `rolling_quantile`
* `dt.round`
* `cumulative_eval`
* `map_elements(strategy="threading")`

DataFrame:
* `unstack`
* `update`

LazyFrame:
* `collect_async`

Other:
* `collect_all_async`
* `scan_pyarrow_dataset()`
* `SQLContext`
* `Decimal` data type
* `LazyFrame.collect(streaming=True)` and other streaming functionality

Some of this functionality exists for some time (rolling stats) or is unlikely to be meaningfully changed (`unstack` & `map_dict`), so I think it would be good to clean up this list and decide on whether at least some of these can be deemed no experimental going into Polars 1.0.

**Comment by s-banach** [comment]
As `Series.cut()` is finalized, I wonder whether anyone can comment why it returns a DataFrame rather than a Series.
I suppose a typical user is likely to want just one of the `break_point` or `category` outputs, rather than both.
To me personally, it feels nicer to write
```python
df.with_columns(x_cut=df["x"].cut(bins=[a,b,c], output="category"))
```
rather than
```python
df.with_columns(x_cut=df["x"].cut(bins=[a,b,c])["category"])
```
especially because I know the latter is creating an unused column.

**Comment by stinodego** [comment]
I updated the list in the original issue with all functionality that is _currently_ experimental, as indicated in the docstrings.

**Comment by temeddix** [comment]
Our project called [Solie](https://github.com/cunarist/solie) would like to adapt polars, but we're a bit hesitant because `collect_async` is considered experimental. When would this be stabilized? Our codebase is async-oriented and would definitely benefit from `collect_async` or `collect_all_async` being switched to stable.

**Comment by stinodego** [comment]
> Our project called [Solie](https://github.com/cunarist/solie) would like to migrate from pandas to polars, but we're a bit hesitant because `collect_async` is considered experimental. When would this be stabilized? Our codebase is async-oriented and would definitely benefit from `collect_async` or `collect_all_async` being switched to stable.

I don't think it will be stabilized anytime soon. It was added by a contributor who is no longer active on the project, and we haven't really received any feedback on the functionality. So we don't have a good feel for how solid it is.

Regarding the rest, I believe we have marked all functionality we're unsure about as unstable, so I'm closing this.

**Comment by s-banach** [comment]
Any chance of stabilizing ‘cut’ before 1.0? Very important for people fitting old fashioned linear models.

**Comment by stinodego** [comment]
> Any chance of stabilizing ‘cut’ before 1.0? Very important for people fitting old fashioned linear models.

The current `cut` and `qcut` will not be stabilized. We have planned to change their API: https://github.com/pola-rs/polars/issues/10468 

It can be stabilized once that issue is resolved. I don't think we will get to it before the 1.0.0 release, but we'll see.

**Comment by winstxnhdw** [comment]
`collect_async` still blocks the event loop on sufficiently complex queries. My guess is that, although `polars` is trying to run the computation within a thread loop, there's still lots of computation being done in Python before the GIL is dropped.
