### ISSUE TITLE
Optimize counting on LazyFrame

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#7356]
### Problem description

The following code counts the number of records in a LazyFrame. It encounters an out of memory issues (terminated by the non user friendly SIGKILL) when the total size of Parquet files is large even if each Parquet file has a limited size. It would be nice if counting on a LazyFrame is optimize to avoid loading everything into memory. 
```
 LazyFrame::scan_parquet(
                "data/**/*.parquet",
                ScanArgsParquet::default())
  .select(&[count().cast(DataType::UInt64).alias("n")])
  .collect()
  .unwrap()["n"]
  .u64()
  .unwrap()
  .get(0)
  .unwrap()
```

**Comment by dclong** [comment]
Related to https://github.com/pola-rs/polars/issues/7049.

**Comment by stinodego** [comment]
Closing in favor of #13521
