### ISSUE TITLE
pl.col on multi columns stopped working after 0.16.0

### ISSUE THREAD

**Issue by shaharluftig** [pola-rs/polars#7359]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have polars code that I have used for a long time, and after version 0.16.0 It stopped working
I've tried to debug it, and what I saw is when I use pl.col on multi columns, and then run any function and give the result an alias,
I get the following error

exceptions.ComputeError: The name: 'hello' passed to `LazyFrame.with_columns` is duplicate
Error originated just after operation: '  DF ["company", "url", "year", "from"]; PROJECT */5 COLUMNS; SELECTION: "None"

I Have tried different public data sets with different column types and with different functions (such as concat) and the program still panics. 

### Reproducible example

```python
# Works in polars<0.16.0 and does not work in polars>=0.16.0
df.with_columns(pl.col(["year","from"]).hash().alias("hello"))

# Works in both versions
df.with_columns(pl.col(["year"]).hash().alias("hello"))
```

### Expected behavior

Hashed column on multi fields with "hello" alias

### Installed versions

---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: 0.3.2_alpha.2
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0

**Comment by lucazanna** [comment]
Hi @shaharluftig ,

The error message should be linked to this PR: https://github.com/pola-rs/polars/issues/7045.
I believe that in the past you were hashing only your first column.

Here is an example:

```
import polars as pl

df = pl.DataFrame({
    'year': [2021,2022,2023],
    'from':['a','b','c']
})

# Here is the transformation without alias.
df.with_columns(pl.col(["year","from"]).hash())

shape: (3, 2)
┌──────────────────────┬──────────────────────┐
│ year                 ┆ from                 │
│ ---                  ┆ ---                  │
│ u64                  ┆ u64                  │
╞══════════════════════╪══════════════════════╡
│ 8951328859461086077  ┆ 11340877456901151001 │
│ 3826084504901310262  ┆ 784724579488328509   │
│ 17147584224051086063 ┆ 7063481090252254406  │
└──────────────────────┴──────────────────────┘

# And here is the result if I add alias in a previous version of Polars.
df.with_columns(pl.col(["year","from"]).hash().alias("hello"))

shape: (3, 3)
┌──────┬──────┬──────────────────────┐
│ year ┆ from ┆ hello                │
│ ---  ┆ ---  ┆ ---                  │
│ i64  ┆ str  ┆ u64                  │
╞══════╪══════╪══════════════════════╡
│ 2021 ┆ a    ┆ 11340877456901151001 │
│ 2022 ┆ b    ┆ 784724579488328509   │
│ 2023 ┆ c    ┆ 7063481090252254406  │
└──────┴──────┴──────────────────────┘

# The newly created column 'hello' corresponds only to the column 'from' and not to the column year.

# If I understand correctly what you are trying to do, you can do the following
df.with_columns(pl.concat_str(["year","from"]).hash().alias("hello"))

shape: (3, 3)
┌──────┬──────┬──────────────────────┐
│ year ┆ from ┆ hello                │
│ ---  ┆ ---  ┆ ---                  │
│ i64  ┆ str  ┆ u64                  │
╞══════╪══════╪══════════════════════╡
│ 2021 ┆ a    ┆ 9170948584249009148  │
│ 2022 ┆ b    ┆ 18048213807542313138 │
│ 2023 ┆ c    ┆ 16730134275453232121 │
└──────┴──────┴──────────────────────┘

```

Using concat_str will ensure that both of your columns are taken into account when creating the hash
