### ISSUE TITLE
Cannot use "i" rolling/dynamic groupby with uint

### ISSUE THREAD

**Issue by gwerbin** [pola-rs/polars#7360]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

With `DataFrame.groupby_dynamic()`, using "i" units on a `uint`-type column produces an error:

```
ComputeError: expected any of the following dtypes {Date, Datetime, Int32, Int64}, got u32
```

### Reproducible example

```python
import numpy as np
import pandas as pd
import polars as pl

t = pd.date_range('2022-01-01', '2022-06-01', freq='1D'),
y = np.random.normal(size=len(t))
data = pl.DataFrame(pd.DataFrame({'t': t, 'y': y}))

result = (
    data
    .lazy()
    .with_row_count('n')
    .groupby_dynamic('n', every='2i')
    .agg(pl.count())
    .collect()
)
```

### Expected behavior

I expected this to work just as well on int and uint columns.

However it would make sense if a negative offset were prohibited on uint columns.

### Installed versions

<details>

```none
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.10 (main, Feb 18 2023, 16:09:16) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by mcrumiller** [comment]
The [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.groupby_rolling.html) is fairly explicit in its requirements:

> ### index_column
> Column used to group based on the time window. Often to type Date/Datetime This column must be sorted in ascending order. If not the output will not make sense.
>
> In case of a rolling groupby on indices, dtype needs to be one of {Int32, Int64}. Note that Int32 gets temporarily cast to Int64, so if performance matters use an Int64 column.

However, since `Int32` gets upcasted to `Int64` anyway, I don't see the point of this requirement. Why not just require `Int64` in the first place,  or allow any integer types and have them always casted to `Int64`?

**Comment by zundertj** [comment]
Removing bug label, as this is well documented per mcrumiller's comment.

**Comment by 2-5** [comment]
I have encountered the exact same issue.

Why is `with_row_count` generating a `dtype` which is not accepted by `groupby_dynamic`, giving that grouping on index is an exact use case for `groupby_dynamic`? Why not make `groupby_dynamic` generate an `Int64` if that is the correct usage?

**Comment by zundertj** [comment]
There may be a consistency issue here, but it is not the case what `with_row_count` and `groupby_dynamic` (on integers) are mostly used together, is it? You make the link between the two, but I fail to see why exactly. 

Also, if you use this combination, aren't you better off using `groupby_rolling`? Still, the same argument holds, so I see this may not be optimal. I guess one could argue `with_row_count` should take an optional `dtype` parameter, if that happens to be any more efficient than doing `with_row_count().with_columns(pl.col("row_nr").cast(pl.Int64))`.

**Comment by mcrumiller** [comment]
Chiming in again, it makes zero sense to *require* a dtype that immediately gets cast to something else. Either:

1. `with_row_count()` should allow a `dtype` parameter (ideal); or
2. `groupby_rolling` should be able to use `u32`.

**Comment by 2-5** [comment]
> You make the link between the two, but I fail to see why exactly.

`with_row_count` creates a row index, `groupby_dynamic` can group on "or index value" as described in docs.

> Also, if you use this combination, aren't you better off using `groupby_rolling`?
I just followed the docs. Here is what they say:

I have a constant interval, exactly 20 rows, so I used `groupby_dynamic` as advised:

> Different from a dynamic_groupby the windows are now determined by the individual values and are not of constant intervals. For constant intervals use groupby_dynamic.

Later down the page there is this block:

> In case of a groupby_rolling on an integer column, the windows are defined by:
>    “1i” # length 1
>    “10i” # length 10

But the exact same block appears on the `groupby_dynamic` page:

> In case of a groupby_dynamic on an integer column, the windows are defined by:
>    “1i” # length 1
>    “10i” # length 10

So I'm thoroughly confused on which is the proper way to do a window of fixed "20 rows".

**Comment by zundertj** [comment]
I agree, it seems `groupby_rolling` does too much?

**Comment by dalejung** [comment]
Shouldn't this be closed when `'groupby_dynamic` accepts uints and not just `rolling`?

**Comment by mcrumiller** [comment]
Well, the OP example no longer works as it cannot convert a pandas date range to a polars date range (is this a new bug?) But this issue still exists, `group_by_dynamic` does not accept uints:

```python
from datetime import date
import numpy as np
import polars as pl

t = pl.date_range(date(2022, 1, 1), date(2022, 6, 1), interval="1d", eager=True)
y = np.random.normal(size=len(t))
data = pl.DataFrame({"t": t, "y": y})

result = (
    data.lazy()
    .with_row_count("n")
    .group_by_dynamic("n", every="2i")
    .agg(pl.count())
    .collect()
)
```
```
polars.exceptions.ComputeError: expected any of the following dtypes: { Date, Datetime, Int32, Int64 }, got u32
```

**Comment by MarcoGorelli** [comment]
I'm not sure about UInt32 for dynamic tbh, because they wouldn't be preserved by the operation (the dynamic part can create negative numbers). I'd suggest opening a separate issue about that
