### ISSUE TITLE
Add kwargs to pl.write_database

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#7367]
### Problem description

to get rid off the index column

```
return (
    self
    .to_pandas(use_pyarrow_extension_array=True)
   .to_sql( name=table_name, con=engine, if_exists=if_exists, **index=False** )
)
```

**Comment by romiof** [comment]
This will be very useful !

**Comment by klaerik** [comment]
This would also be helpful for the `schema` and `dtype` arguments.

**Comment by romiof** [comment]
Related to:
https://github.com/pola-rs/polars/pull/7596

**Comment by anmarco** [comment]
Any progress on this issue? 

It would be useful to be able to pass kwargs to the .to_sql() function. Then one could set other kwargs used by pandas as @klaerik mentioned (in my case I need to set chunksize and method). 

I'm willing to open a pull request implementing this change.

**Comment by alexander-beedie** [comment]
> Any progress on this issue?

Yes - this was actually closed by https://github.com/pola-rs/polars/pull/16099, but I forgot to tag this issue as being related 😅 Can now pass instantiated connections (eg: not just URIs), and _also_ pass kwargs via the new `engine_options` parameter.
