### ISSUE TITLE
Polars arrow dataset date filtering much slower than arrow

### ISSUE THREAD

**Issue by dannyfriar** [pola-rs/polars#7375]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm experimenting with the new `scan_pyarrow_dataset` API and have generally found performance to be quite similar to using `pyarrow.dataset` directly (with the `allow_pyarrow_filter=True` flag turned on).

I've noticed that performance seems to be much slower than arrow for the specific case of filtering on a date column. See the example code below.

### Reproducible example

```python
from datetime import datetime, timedelta

import polars as pl
import pyarrow as pa
import pyarrow.dataset as ds
import numpy as np

# Create some data and write to a partitioned dataset
directory = "test"
n_rows = 1_000_000
date_list = [datetime(2000, 1, 1) + timedelta(days=x) for x in range(n_rows)]

df = pl.DataFrame({
    "date": date_list,
    "col1": np.random.randn(n_rows),
})

df = df.with_column(
    pl.col("date").dt.month().alias("month")
)
table = df.to_arrow()

ds.write_dataset(
    table,
    directory,
    format="parquet",
    partitioning=ds.partitioning(pa.schema([("month", pa.int32())]), flavor="hive"),
)

# Read the date with arrow, this took 4.8ms on my machine
dataset = ds.dataset(directory, format="parquet", partitioning="hive")

table = dataset.to_table(
    filter=((ds.field("month") <= 6) & (ds.field("date") <= datetime(2020, 1, 1))),
)

# Read the date with polars, this took 78ms on my machine
df = pl.scan_pyarrow_dataset(
    dataset,
    allow_pyarrow_filter=True
).filter(
    (pl.col("month") <= 6) & (pl.col("date").is_between(pl.datetime(2000, 1, 1), pl.datetime(2020, 1, 1)))
)
df = df.collect()
```

### Expected behavior

`pyarrow` and `polars` perform similarly when filtering the date column.

Note, filtering on the month column only seems to be more similar between the two (22ms for arrow vs 38ms for polars on my machine).

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Dates are not yet pushed down in pyarrow filters.

**Comment by dannyfriar** [comment]
Thanks @ritchie46, I thought this may be the case

**Comment by dannyfriar** [comment]
@ritchie46 is the example above expected to be similarly performant between arrow and polars now?

I tried with 0.16.13 but Arrow still seemed to be ~5x faster for this example.

**Comment by ritchie46** [comment]
`is_between` is not pushed down. Can you open a feature request for that one? 

If you rewrite your `is_between` to literals it can be pushed down.

**Comment by dannyfriar** [comment]
Sure - https://github.com/pola-rs/polars/issues/7553

**Comment by dannyfriar** [comment]
There's a colab notebook here illustrating the timings: https://colab.research.google.com/drive/1HT_TtQPsn-H-OxANWtPfOyTG7qB-GAag#scrollTo=nVkmkIuxAWgT

This still seems to take more time (copy the [test code](https://github.com/pola-rs/polars/blob/3e682709ec4b728a5febc4ec4864b26622f642c5/py-polars/tests/unit/io/test_pyarrow_dataset.py#L92) from your PR above):

```
df = pl.scan_pyarrow_dataset(
    dataset,
    allow_pyarrow_filter=True
).filter(
    (pl.col("month") <= 6) & (pl.col("date") <=  datetime(2020, 1, 1))
)
df = df.collect()
```

**Comment by ritchie46** [comment]
What is your schema?

**Comment by dannyfriar** [comment]
The dataset schema is

```
date: timestamp[us]
col1: double
month: int32
```

**Comment by CharlesFauman** [comment]
the effect of this is pretty serious - it means when i scan over a partitioned dataset, if a filter by any date column anywhere in my lazyframe computation, I silently fall back to reading the all partitions of dataset into memory (even if I otherwise explicitly filter on the partition)

**Comment by uch-energinet** [comment]
It would be a great help if somebody could fix this. This prevents me from really using Polars with Delta Lake tables. Unfortunately, I don't have any Rust skills...

**Comment by wence-** [comment]
If you write your dates as polars `Literal`s directly:

```
from datetime import datetime

df.filter(pl.col("date") <= pl.lit(datetime(2000, 1, 1)))
```

Then the translation from polars filters to pyarrow filters works and the expression is pushed down.

In contrast, `pl.datetime(2000, 1, 1)` generates a different expression node that is not handled.

**Comment by uch-energinet** [comment]
@wence-. This seems to work for **timezone-unaware** times:

```
import polars as pl
from datetime import datetime

time = datetime(2024,7,23)

(
    pl.scan_delta(f"abfs://table", storage_options=storage_options)
    .filter(pl.col("time_utc") >= pl.lit(time))
    .explain()
)

[Output]:
'PYTHON SCAN []\nPROJECT */6 COLUMNS\nSELECTION: [(col("time_utc")) >= (2024-07-23 00:00:00)]'
```

but **not** with **timezone-aware** times:

```
import polars as pl
from datetime import datetime
import pytz

time = datetime(2024,7,23, tzinfo=pytz.UTC)

(
    pl.scan_delta(f"abfs://table", storage_options=storage_options)
    .filter(pl.col("time_utc") >= pl.lit(time))
    .explain()
)

[Output]:
'FILTER [(col("time_utc")) >= (2024-07-23 00:00:00.dt.replace_time_zone([String(earliest)]))] FROM\n  PYTHON SCAN []\n  PROJECT */6 COLUMNS'
```

**Comment by wence-** [comment]
> @wence-. This seems to work for timezone-unaware times:

Thanks, I think this indeed the same issue, this produces an expression that the conversion from polars into a pyarrow predicate does not support. See also #16300 and #16248. There has been some work to address this in #16500, but that is not yet ready.
