### ISSUE TITLE
Parametrized SQL queries in read_database

### ISSUE THREAD

**Issue by matquant14** [pola-rs/polars#7376]
### Problem description

Can you add the ability to run parameterized SQL queries to avoid SQL injection?  I don't see that available in the current documentation.  Something like 

query="""
Select ID, A,B,C,D WHERE ID = '?'
"""
param=['A123']

pl.read_database(query, cnxn_uri, params=param)

**Comment by eerhil** [comment]
Has this been adressed? 

Pandas has [this](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html) feature implemented already so I see it very relevant.

**Comment by alexander-beedie** [comment]
@eerhil: FYI, landed the relevant PR today; should be in the next release.
Can see some examples of it in use here: https://github.com/pola-rs/polars/pull/11562
