### ISSUE TITLE
`cov()` should have `ddof` parameter just like `var()`

### ISSUE THREAD

**Issue by ddanieltan** [pola-rs/polars#7386]
### Problem description

`var()`([source](https://github.com/pola-rs/polars/blob/4b3eb3a42e55c0bd999c592ea655b2af69c7565d/py-polars/polars/internals/lazy_functions.py#L412-L434)) sets degrees of freedom `ddof=1` as a default and leaves `ddof` as a parameter for the user to amend when necessary. 

I'd argue we should have the same `ddof` parameter for`cov()` ([source](https://github.com/pola-rs/polars/blob/4b3eb3a42e55c0bd999c592ea655b2af69c7565d/py-polars/polars/internals/lazy_functions.py#L1483-L1512)). Here's a quick check to show that the current calculation for covariance also uses`ddof=1` as a default.

```python
import random
import numpy as np
import polars as pl

random.seed(390247823904)
rand1 = [random.random() for _ in range(100)]
rand2 = [random.random() for _ in range(100)]

np.cov(rand1, rand2, ddof=1)[0][1]
# 0.0027327136884957863

np.cov(rand1, rand2, ddof=0)[0][1]
# 0.0027053865516108284

# Polars cov() matches ddof=1 result
df = pl.DataFrame([rand1, rand2])
df.select(pl.cov("column_0","column_1")).item()
# 0.0027327136884957868
```

But unlike `var()`, users are missing the option to amend `ddof` when calling `cov()`.

**Comment by Wainberg** [comment]
This can be closed since cov() now has a ddof parameter: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.cov.html
