### ISSUE TITLE
`map_dict` add rows if dtype and dict keys mismatch

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#7389]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`map_dict` has some odd behaviour for `null`s when the dtype of the column and the type of the dictionary keys does not match.

In some cases, it will map a `null` to every value in the dictionary.

### Reproducible example

```python
import polars as pl

s = pl.Series(values = [None, '0'], dtype=pl.Utf8)

int_map = {0: 'a', 1: 'b'}
bool_map = {True: 'a', False: 'b'}
str_map = {'0': 'a', '1': 'b'}

# Adds row when dtype of keys does not match dtype of column
print(
    s.map_dict(int_map),  # shape: (3,) Series: '' [str] [ "a" "b" null ]
    s.map_dict(bool_map), # shape: (3,) Series: '' [str] [ "a" "b" null ]
)

# For each null in s, adds all keys of dict
larger_int_map = {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
print(
    s.map_dict(larger_int_map),  # shape: (5,) Series: '' [str] [ "a" "b" "c" "d" null ] 
)
s_more_nulls = pl.Series(values = [None, None, '0'], dtype=pl.Utf8)

print(
    s_more_nulls.map_dict(int_map), # shape: (5,) Series: '' [str] [ "a" "b" "a" "b" null ] 
)

# Integer series does differently, it will match bool to 0-1 and crash on str
s_int = pl.Series(values = [None, 0], dtype=pl.Int32)

print(
    s_int.map_dict(bool_map), # shape: (2,) Series: '' [str] [ null "b" ]
    # s_int.map_dict(str_map) - This breaks with:
    # exceptions.ComputeError: TypeError: 'str' object cannot be interpreted as an integer
)

# Works as expected when types match
print(
    s.map_dict(str_map),  # shape: (2,) Series: '' [str] [ null "a" ]
    s_int.map_dict(int_map),  # shape: (2,) Series: '' [str] [ null "a" ]
)
```

### Expected behavior

I expected `null` to be mapped to `null` unless I had the key `None` in my dictionary.
I guess technically it can make sense that `null` matches anything in the same way that the empty string matches everything, but I would always expect `map_dict` to keep the amount of rows stable.

I'm not exactly sure what to expect or what the best solution is, but I would at least expect it to behave consistently no matter the type.

Thanks!

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.9.14 (main, Sep  7 2022, 23:43:48) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.3.5
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.0
```

</details>

**Comment by ghuls** [comment]
If the dtype of your keys doesn't match with your  column dtype, that is a bug in your query.

**Comment by StefanBRas** [comment]
Indeed, but I would probably expect it to give an error or just ignore them. It think matching the boolean keys to the integers 0 and 1 are okay, but creating new rows is something I would never assume a mapping action would do. There's also the case of dictionary with mixed types. 

At least from the documentation there is nothing saying that the types. So this might be undefined behaviour and it doesn't really matter what it does, but then I think it would make sense to have it documented.

I know that it's not optimal that the types doesn't match, but whenever I use `map_dict` with a dynamically created dict I will have to validate the dictionary anyway so maybe it should be part of the function?

**Comment by mcrumiller** [comment]
Agree that `map_dict` should never change the size of the series and, while I agree that using the wrong dtype in your key is a bug, there is still a problem here.

**Comment by ghuls** [comment]
It will return an error in: https://github.com/pola-rs/polars/pull/7393

```
s.map_dict(larger_int_map)
...
ComputeError: ValueError: Remapping keys could not be converted to Utf8 without losing values in the conversion.
```

**Comment by ritchie46** [comment]
Can this now be closed @ghuls?

**Comment by StefanBRas** [comment]
I just tested against the master branch and it not throws an error.

Thanks again!
