### ISSUE TITLE
groupby_dynamic unclear documentation

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#7406]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The docstring for `groupby_dynamic` states

``` console
index_column
    Column used to group based on the time window. Often to type Date/Datetime This column must be sorted in ascending order. If not the output will not make sense.
```

This isn't mentioned in the examples (https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/temporal_groupby.html) and it's also unclear what the sort order should be if `by` is also used - i.e.

``` python
table.groupby_dynamic("ts_local", every="1d", by="id").agg([pl.col("value").mean().alias("value__mean")])
```

Should table be sorted by `ts_local` or `ts_local, id` or  `id, ts_local` ?

In general it might help if all the examples explicitly sort the input even if they're already sorted in order to be clear what the requirements are (otherwise "If not the output will not make sense.")

### Reproducible example

```python
N/A
```

### Expected behavior

N/A

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report, have opened a PR to clarify
