### ISSUE TITLE
Daframe to_pandas crash with strings data type in pyarrow (large_string)

### ISSUE THREAD

**Issue by romiof** [pola-rs/polars#7431]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When we have strings in our dataframe columns, isn't possible to convert it to a Pandas DF with PyArrow backend. 

`to_pandas(use_pyarrow_extension_array=True)`

### Reproducible example

```python
import polars as pl
from datetime import datetime

dataframe = pl.DataFrame({"integer": [1, 2, 3], 
                          "date": [
                              (datetime(2022, 1, 1)), 
                              (datetime(2022, 1, 2)), 
                              (datetime(2022, 1, 3))
                          ], 
                          "float":[4.0, 5.0, 6.0],
                          "strings": ["first", "second", "third"]
                        })

df_pd_pyarrow = dataframe.to_pandas(use_pyarrow_extension_array=True)



#ERROR *** NotImplementedError: large_string ***
```

### Expected behavior

It's supposed to work, as its works when are just columns with Integers / Floats

### Installed versions

- WSL2 
- Ubuntu 22.04.2 LTS
- Python 3.10.6
- Polars 0.16.11

**Comment by ritchie46** [comment]
Pandas arrow support is still in development. I think they will fix this later.

**Comment by romiof** [comment]
This error also occurs when using the method **dataframe.write_database()**, as it uses the same function related above.

![image](https://user-images.githubusercontent.com/54966010/223793452-d2f67b6b-3757-42c8-b49f-544c7e2c7486.png)

**Comment by romiof** [comment]
@ghuls 

```
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.>>> import polars>>> polars.show_versions()
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 2.0.0rc0
numpy: 1.24.2
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>>>>
```

**Comment by ghuls** [comment]
With `pip install 'pandas>=2.0.0rc0'` I also get the error. Downgrading to 1.5.3, solves it.
Can you report to pandas?

**Comment by romiof** [comment]
@ghuls I can confirm that it worked with pandas 1.5.3.

**Comment by romiof** [comment]
Closed because it was a Pandas bug.
