### ISSUE TITLE
Cant Create new Column From Existing Column if it is a string

### ISSUE THREAD

**Issue by jayceslesar** [pola-rs/polars#7432]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Cant concatenate strings into new column names and no examples of this exist in the documentation.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({
    "foo": ["asdf"],
    "bar": ["asdf"],
})

df = df.with_columns([
    ((pl.col("foo").str + "_" + pl.col("bar").str).alias("foo_bar"))
])
```

### Expected behavior

The new column exists with no errors.  Instead I get 
```
(pl.col("foo").str + "_" + pl.col("bar").str.alias("foo_bar"))
TypeError: unsupported operand type(s) for +: 'ExprStringNameSpace' and 'str'
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: macOS-13.2.1-arm64-arm-64bit
Python: 3.10.6 (main, Oct  3 2022, 19:34:55) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.3.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by jayceslesar** [comment]
so looks like https://stackoverflow.com/questions/72400218/how-to-use-polars-concat-str-to-combine-multiple-columns-selected-by-regex but nowhere in the docs can I find this?

**Comment by jayceslesar** [comment]
```py
df = df.with_columns([
        (pl.concat_str(['foo', '_', 'bad']).alias('field'))
    ])
```
doesnt work I would need to make a new column which is fine I suppose but clunky

**Comment by ritchie46** [comment]
Your query is wrong. Use `col() + ...` instead of `col().str + ...`
