### ISSUE TITLE
ArrowErrorException when reading Decimal type from parquet file.

### ISSUE THREAD

**Issue by Nozzch** [pola-rs/polars#7444]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hello, i have been following polars' recent work on adding decimal support closely as it is the only thing holding me back from switching to polars.

I am running polars 0.16.11 and have enabled decimal support. When attempting to read a parquet file containing a arrow decimal256 type i get the following error:
```
ArrowErrorException: NotYetImplemented("Reading parquet type FixedLenByteArray(28) to Decimal256(67, 63) still not implemented")
```

### Reproducible example

```python
pl.config.Config.activate_decimals()
df = pl.read_parquet(pq_file)
```
```


### Expected behavior

Load the parquet file into a polars data frame.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-6.1.12-200.fc37.x86_64-x86_64-with-glibc2.36
Python: 3.9.16 (main, Dec  7 2022, 00:00:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by zundertj** [comment]
I think only Decimal128 is implemented for the time being.
