### ISSUE TITLE
How about add a grouby_rolling expression?

### ISSUE THREAD

**Issue by wuzhe1234** [pola-rs/polars#7452]
### Problem description

Right now we can use `groupby_rolling()` to generate a Dataframe with the same length of the orginal dataframe. If there is a `groupby_rolling` expression. I could wirte following codes:

```
df.select(
    pl.col("date"), 
    pl.col("a"),  
    pl.groupby_rolling("date", "10d").agg(pl.col("a").mean()),  
    pl.groupby_rolling("date", "10d").agg(pl.col("a").std()),
)
```
Which means I could combine the `select` part and the `groupby_rolling` part together.

**Comment by ritchie46** [comment]
Just write it after the select. There should be one obvious way to do things and this doesn't help with that.

**Comment by wuzhe1234** [comment]
> Just write it after the select. There should be one obvious way to do things and this doesn't help with that.

Thanks for your response, right now if I want to do some work with `select`, then do some work with `groupby_rolling`, then do some work with another `groupby_rolling` with diffrent window size, finally combine the result together. I should write following code:

```
df1 = df.select(...)
df2 = df.groupby_rolling("date", period="10d").agg(...)
df3 = df.groupby_rolling("date", period="15d").agg(...)

result = pl.concat(
    [
        df1, 
        df2.select(pl.all().exclude("date")),  # must exclude "date", otherwise there will be name conflicts.
        df3.select(pl.all().exclude("date")),
    ],
    how="horizontal",
)

```

Which is already neat. But I was wondering if I could just use `pl.Expr` to achieve it, not only I could collect all the columns I want in just one list, but also the polars backend could optimize the plans together(might be good for the perfomance?).

**Comment by alexanderpils** [comment]
@wuzhe1234 I think your request is since version v0.19 possible [see](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.rolling.html)

@stinodego I think you can close this issue

**Comment by stinodego** [comment]
I don't think `rolling` is exactly the same as the request here, but since Ritchie also expressed that this is not desirable to add, I will close this.
