### ISSUE TITLE
Failure to upcast during aggregation

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#7453]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Various reductions do not upcast to a larger size to avoid overflow.

### Reproducible example

```python
import polars as pl

foo = pl.DataFrame({"foo": [1,1,1,1,1]})
foo.with_columns(pl.col("foo").cast(pl.UInt32) * (1<<31)).sum()
```

### Expected behavior

I would have expected this summation to upcast automatically (like numpy). My actual use case was I had a dataframe with numbers of bytes of various data (each being many GB) and I wanted to groupby a column and sum the bytes. This initially escaped my test suite since I was just writing tests with manageable sizes of data but noticed something was off when running on real data.

The unsigned int came from calling `pl.count` elsewhere when deriving the number of bytes per piece of data. I did read [this thread](https://github.com/pola-rs/polars/issues/4990) about why UInt32s are exposed in the user API. But given that they are exposed, does it still make sense to try and save the user from these overflow errors?

### Installed versions

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.1
```

**Comment by slonik-az** [comment]
Polars philosophy is to be explicit and do as little as possible behind your back. In your case using 64-bit integers from get go is the way to go.

**Comment by CHDev93** [comment]
Yeah ideally I'd have just used 64-bit ints to start but I guess I didn't even realise that uint32's were being introduced by `pl.count`. This felt a bit "behind your back" but if that's the philosophy then I can live with that. Just wanted to check it was a conscious decision rather than an edge case that hadn't been considered. I wasn't expecting to have the result of `pl.count` multiplied with a python integer result in a `uint32`.

**Comment by slonik-az** [comment]
Everythong seems to work OK if you remove explicit `cast(pl.UInt32)`

```python
import polars as pl
foo = pl.DataFrame({"foo": [1,1,1,1,1]})
print(foo)
┌─────┐
│ foo │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
│ 1   │
│ 1   │
│ 1   │
└─────┘

foo.with_columns(pl.col("foo") * (1<<31)).sum()
shape: (1, 1)
┌─────────────┐
│ foo         │
│ ---         │
│ i64         │
╞═════════════╡
│ 10737418240 │
└─────────────┘


10737418240 / (1<<31) # =>  5.0

```

Polars chooses `i64` type throughout and no overflow is observed. Am I missing something?

**Comment by CHDev93** [comment]
My original reproducer isn't actually the use case. It's more like the following

```python
foo = pl.DataFrame({"is_present": [1,0,1,1,0], "data_id": [1,1,2,2,2]})
shape: (5, 2)
┌────────────┬─────────┐
│ is_present ┆ data_id │
│ ---        ┆ ---     │
│ i64        ┆ i64     │
╞════════════╪═════════╡
│ 1          ┆ 1       │
│ 0          ┆ 1       │
│ 1          ┆ 2       │
│ 1          ┆ 2       │
│ 0          ┆ 2       │
└────────────┴─────────┘
nbytes_per_elem=1000
foo.filter(pl.col("is_present") == 1).groupby("data_id").agg(pl.count().alias("npresent")*nbytes_per_elem)
┌─────────┬──────────┐
│ data_id ┆ npresent │
│ ---     ┆ ---      │
│ i64     ┆ u32      │
╞═════════╪══════════╡
│ 2       ┆ 2000     │
│ 1       ┆ 1000     │
└─────────┴──────────┘
```

These numbers obviously fit in a u32 and in my actual case they do as well. The problem was that I didn't realise these were u32 and a downstream function did an aggregation over many data_ids and that overflowed (since these are representing bytes of data on disk and I have many GB of data).

I just wasn't sure if the `pl.count().alias("npresent")*nbytes_per_elem` was meant to maintain the dtype of u32. Thought it might be a bug but I'm content if that's the expected/desired behaviour

**Comment by avimallu** [comment]
I was surprised by this behavior as well today, and it is very hard to even identify when you have a few thousand rows of data unless you're expecting this:

```
(
    pl.DataFrame(
        {"num_1": (3, 4, 5, 5), "num_2": (4, 8, 12, 13)},
        schema= {"num_1": pl.UInt32, "num_2": pl.UInt32})
    .with_columns(
        (pl.col("num_1") - pl.col("num_2")).alias("diff"),
        (pl.col("num_1").n_unique() - pl.col("num_2").n_unique()).alias("n_unique_diff"))
)
```

provides me:
```
shape: (4, 4)
┌───────┬───────┬────────────┬───────────────┐
│ num_1 ┆ num_2 ┆ diff       ┆ n_unique_diff │
│ ---   ┆ ---   ┆ ---        ┆ ---           │
│ u32   ┆ u32   ┆ u32        ┆ u32           │
╞═══════╪═══════╪════════════╪═══════════════╡
│ 3     ┆ 4     ┆ 4294967295 ┆ 4294967295    │
│ 4     ┆ 8     ┆ 4294967292 ┆ 4294967295    │
│ 5     ┆ 12    ┆ 4294967289 ┆ 4294967295    │
│ 5     ┆ 13    ┆ 4294967288 ┆ 4294967295    │
└───────┴───────┴────────────┴───────────────┘
```

This upcasting would be absolutely necessary for the case where I'm using `n_unique` because getting that correct would be more of `polars` responsibility than mine. I fully understand from the linked thread in OP that it is "natural" for `n_unique` to be only positive, but this is a geniune use-case that I had in an aggregation today that I wouldn't have caught easily.

**Comment by slonik-az** [comment]
> I just wasn't sure if the pl.count().alias("npresent")*nbytes_per_elem was meant to maintain the dtype of u32. 

It is not a bug per se, but quite counter-intuitive for sure.
If you replace `nbytes_per_elem=1000` with `nbytes_per_elem = pl.lit(1000, pl.Int64)` in your code then the product of `u32` and `i64` is properly promoted to 'i64'

```python
nbytes_per_elem = pl.lit(1000, pl.Int64)
foo.filter(pl.col("is_present") == 1).groupby("data_id").agg(pl.count().alias("npresent")*nbytes_per_elem)
Out[49]:
shape: (2, 2)
┌─────────┬──────────┐
│ data_id ┆ npresent │
│ ---     ┆ ---      │
│ i64     ┆ i64      │
╞═════════╪══════════╡
│ 2       ┆ 2000     │
│ 1       ┆ 1000     │
└─────────┴──────────┘
```
When one sets `nbytes_per_elem=1000` python uses its `int` type that is variable width and for small integers can be `i32` and, thus, no promotion is performed when multiplied by `u32`.

**Comment by CHDev93** [comment]
Thanks @slonik-az ! The `pl.lit` work around seems like the most appropriate solution for what I'm doing
