### ISSUE TITLE
Weird behavior for expression is_in

### ISSUE THREAD

**Issue by McNickSisto** [pola-rs/polars#7477]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The **is_in** expression is allowing me to filter a polars column of **i64** if the value in **is_in** is either:

- int
- list of strings

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"COLUMNX" : [1,2,3,4,5,5]})

df.filter(pl.col("COLUMNX").is_in(2)) 
df.filter(pl.col("COLUMNX").is_in(["2"]))
```

### Expected behavior

Would have expected the second filtering to fail given we are comparing int with string.

### Installed versions

<details>

```
Polars: 0.16.8
```

</details>

**Comment by ritchie46** [comment]
I casts `COLUMNX` to string to do the comparison. I think we should error here though.

**Comment by McNickSisto** [comment]
Would seem more intuitive.

**Comment by McNickSisto** [comment]
Thank you :)
