### ISSUE TITLE
[Create A New DataFrame Only With Columns' Name But No Need of Value]

### ISSUE THREAD

**Issue by jacklanda** [pola-rs/polars#749]
As usually known that, it's common to create a new dataframe in `Pandas` in this way:
    `pd.DataFrame(columns=("col1", "col2", "col2"))`
It's a statement to create a dataframe only with columns' name but actually not with any values, the image below shows this way.
<img width="612" alt="图片" src="https://user-images.githubusercontent.com/54089835/120927831-d151bb80-c714-11eb-9743-a7ab735a31e2.png">

This question is how can we create a empty dataframe only with specific column names, based on polars' api ?

**Comment by ritchie46** [comment]
A polars dataframe must have a schema. Therefore you must provide the types when creating an empty `Series` (as there is no data to infer the dtype from).

You could create an empty frame like so:

```python
df = pl.DataFrame([
    pl.Series("a", [], dtype=pl.Int32),
    pl.Series("b", [], dtype=pl.Int64),
])
print(df)
```

```
shape: (0, 2)
╭─────┬─────╮
│ a   ┆ b   │
│ --- ┆ --- │
│ i32 ┆ i64 │
╞═════╪═════╡
╰─────┴─────╯

```

May I ask, why you want this?

**Comment by jacklanda** [comment]
> A polars dataframe must have a schema. Therefore you must provide the types when creating an empty `Series` (as there is no data to infer the dtype from).
> 
> You could create an empty frame like so:
> 
> ```python
> df = pl.DataFrame([
>     pl.Series("a", [], dtype=pl.Int32),
>     pl.Series("b", [], dtype=pl.Int64),
> ])
> print(df)
> ```
> 
> ```
> shape: (0, 2)
> ╭─────┬─────╮
> │ a   ┆ b   │
> │ --- ┆ --- │
> │ i32 ┆ i64 │
> ╞═════╪═════╡
> ╰─────┴─────╯
> ```
> 
> May I ask, why you want this?

Under my scene, I usually create a empty dataframe only with specific comlumn names, after that, it' s common for to append a new `Series` instance to the empty dataframe by pandas' way `df.append(*, ignore_index=True)`. It truly works for me. But I wonder how can I reproduce this using polars' api (?)

**Comment by ritchie46** [comment]
When you add rows to a DataFrame like this `df.append({"a": 955, "b": 996}, ignore_index=True).`

You append a row to a columnar data store. This is very slow from a performance perspective. To make things worse, `Polars` uses chunks of columns. Ideally these chunks are big, but if you append a single value add a time. Under the hood you will get a vector of chunks of 1 size: `Vec<SingletonArray>`. This will be crawlingly slow. You can do this, but then you must be sure to `df.rechunk()` at the end of the operations.

However, what I'd recommend is buffering the columnar data and creating a `DataFrame` at the end.

Something like:

```python
column_a = []
column_b = []
columns = [column_a, column_b]

for row in row_iter:
    index = 0
    for value in row:
        columns[index].append(value)
        index += 1

pl.DataFrame({
    "a": column_a,
    "b": column_b
})
        
```

Even better would be not fetching and iteratoring rows, but fetching columns ;)

**Comment by jacklanda** [comment]
> When you add rows to a DataFrame like this `df.append({"a": 955, "b": 996}, ignore_index=True).`
> 
> You append a row to a columnar data store. This is very slow from a performance perspective. To make things worse, `Polars` uses chunks of columns. Ideally these chunks are big, but if you append a single value at a time. Under the hood you will get a vector of chunks of 1 size: `Vec<SingletonArray>`. This will be crawlingly slow. You can do this, but then you must be sure to `df.rechunk()` at the end of the operations.
> 
> However, what I'd recommend is buffering the columnar data and creating a `DataFrame` at the end.
> 
> Something like:
> 
> ```python
> column_a = []
> column_b = []
> columns = [column_a, column_b]
> 
> for row in row_iter:
>     index = 0
>     for value in row:
>         columns[index].append(value)
>         index += 1
> 
> pl.DataFrame({
>     "a": column_a,
>     "b": column_b
> })
>         
> ```
> 
> Even better would be not fetching and iteratoring rows, but fetching columns ;)
> 
> *edit: typo

It's really inspired me, it helps me to rethink how to handle dataframe while appending a row to a columnar data store , Thank you very much !
