### ISSUE TITLE
Regression: timezone-aware date_range throws wrong results

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7496]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`'1d'` is treated as a fixed-duration interval, which isn't necessarily the case for timezone-aware (e.g. during DST)

### Reproducible example

```python
In [3]: pl.date_range(datetime(2021,11,7), datetime(2021,11,9), "1d", time_zone="US/Central")
Out[3]:
shape: (3,)
Series: '' [datetime[μs, US/Central]]
[
        2021-11-07 00:00:00 CDT
        2021-11-07 23:00:00 CST
        2021-11-08 23:00:00 CST
]
```

### Expected behavior

```python
shape: (3,)
Series: '' [datetime[μs, US/Central]]
[
        2021-11-07 00:00:00 CDT
        2021-11-08 00:00:00 CST
        2021-11-09 00:00:00 CST
]
```

This is due to https://github.com/pola-rs/polars/pull/7430 (my bad, apologies!)

I'd suggest just reverting #7430 for now, perhaps with a clearer error message - better to error loud and clear on ambiguous dates than to deliver incorrect results. I'll put a PR together tomorrow

### Installed versions

<details>

```
---Version info---
Polars: 0.16.12
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 2.0.0rc0
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2

```

</details>

**Comment by ritchie46** [comment]
> This is due to https://github.com/pola-rs/polars/pull/7430 (my bad, apologies!)

Alright, reversed. No worries about it. :+1:  Shall we leave this issue open?

**Comment by MarcoGorelli** [comment]
thanks!

how about reopening https://github.com/pola-rs/polars/issues/7418 ?
