### ISSUE TITLE
How to create a empty dataframe only with columns' name ?

### ISSUE THREAD

**Issue by jacklanda** [pola-rs/polars#750]
In Pandas, we can create a empty dataframe only with columns' name like this 'pd.DataFrame(columns=("col1", "col2", "col3"))', the image below shows this statement↓
 
<img width="553" alt="图片" src="https://user-images.githubusercontent.com/54089835/120928812-e9c3d500-c718-11eb-915d-bfd188bd1eda.png">

How can we implement it in polars' way ?

**Comment by ritchie46** [comment]
Close this as this is similar to #749
