### ISSUE TITLE
Unexpected behavior: replace_or_add does not honor the column name

### ISSUE THREAD

**Issue by chmp** [pola-rs/polars#751]
#### Infos
<details>

- Lang: **Rust**
- Features: `["ipc", "temporal", "lazy"]`
- version = `0.14.0`
- OS = `Windows`

</details>

#### Description

When using `DataFrame.replace_or_add` an non existing column is added with the name of the new series, not the column argument. 

#### What are the steps to reproduce the behavior?

Example:

```
res.replace_or_add("weekday", res.column("date")?.weekday()?)?;
```

This example will overwrite the "date" column, whereas I would have expected to find a new "weekday" column. Reading [the implementation](https://github.com/pola-rs/polars/blob/2b92bc585410d2126862a94cda14d7c058ac0c89/polars/polars-core/src/frame/mod.rs#L919), I would guess adding a rename of the new series to the implementaiton would fix this issue. 

I am happy to submit a fix by

- either adding the rename with a corresponding test
- Or updating the documentation for the `replace_or_add` method, if this behavior is expected and desired

**Comment by ritchie46** [comment]
Thanks for the issue report. You are right. We should rename the new `Series` added.

**Comment by ritchie46** [comment]
This fix has also been released :+1:
