### ISSUE TITLE
Explicitly use dateutil.relativedelta to report errors

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#7516]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When adding or subtracting the time range of datetime or date-type data, polars' own api dt.offset_ By can perform effective calculations, but when

An error will be reported when the dateutil.relativedelta is explicitly used and the data contains null values,

When performing some customized complex time logic calculations, explicit time calculations may be better able to build udf functions

### Reproducible example

```python
'''
import polars as pl
from dateutil.relativedelta import relativedelta
from datetime import datetime, date
#
test = pl.DataFrame({
 'dt':[None, date(2022,2,2),date(2022,3,1)]
})
# with  `dt.offset_by` effective work
test.with_columns([
   pl.col("dt").dt.offset_by('1d').alias('_dt')
])
# report errors1
test.with_columns([
    pl.col('dt').apply(lambda x:x+relativedelta(days=1)).alias('_dt')
])
# report errors2
def f(dt):
    if dt:
        return dt + relativedelta(days=1)
    else:
        return None
test.with_columns([
    pl.col('dt').apply(lambda x:f(x))
])

'''
```

### Expected behavior

...

### Installed versions

<details>

```
---Version info---
Polars: 0.16.12
Index type: UInt32
Platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.31
Python: 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 2.0.0rc0
numpy: 1.24.1
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: 3.6.2
```

</details>

**Comment by zundertj** [comment]
You left me a bit confused by saying there are errors in both approaches, the second one works fine? 

The first one not, and I think this has to do with `apply`, not with dateutils. Probably best illustrated as follows:

```python
import polars as pl
from datetime import datetime, date

test = pl.DataFrame({ 'dt':[None, date(2022,2,2),date(2022,3,1)]})
test.select(pl.col("dt").apply(lambda x: x is not None, skip_nulls=True))
shape: (3, 1)
┌───────┐
│ dt    │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ true  │
│ true  │
└───────┘
```

The [docs](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.apply.html#polars.Expr.apply) state that `skip_nulls` (default is `True`, made it explicit in the code example) will mean the UDF is not applied on `null` values. The first entry is a null value, yet the UDF is applied, otherwise it would `null`, not `false`.

**Comment by ztsweet** [comment]
```
pl.show_versions()
`
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.31
Python: 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]
---Optional dependencies---
numpy: 1.24.1
pandas: 2.0.0rc0
pyarrow: 7.0.0
connectorx: 0.3.1
deltalake: <version not detected>
fsspec: 2022.11.0
matplotlib: 3.6.2
xlsx2csv: 0.8.1
xlsxwriter: <not installed>
`
test.with_columns([
    pl.col('dt').apply(lambda x:x+relativedelta(days=1),skip_nulls=True).alias('_dt')
])
```
thread '<unnamed>' panicked at 'python function failed TypeError: unsupported operand type(s) for +: 'NoneType' and 'relativedelta'', src/apply/series.rs:219:19
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/internals/expr/expr.py:3368, in wrap_f(x)

File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/utils/decorators.py:35, in deprecated_alias.<locals>.deco.<locals>.wrapper(*args, **kwargs)
     32 @functools.wraps(function)
     33 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     34     _rename_kwargs(function.__name__, kwargs, aliases)
---> 35     return function(*args, **kwargs)

File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/utils/decorators.py:126, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    124 if len(args) > num_allowed_args:
    125     warnings.warn(msg, DeprecationWarning, stacklevel=2)
--> 126 return function(*args, **kwargs)

File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/internals/series/series.py:3838, in apply(self, function, return_dtype, skip_nulls)

PanicException: python function failed TypeError: unsupported operand type(s) for +: 'NoneType' and 'relativedelta'
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 test.with_columns([
      2     pl.col('dt').apply(lambda x:x+relativedelta(days=1),skip_nulls=True).alias('_dt')
      3 ])

File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/internals/dataframe/frame.py:6602, in DataFrame.with_columns(self, exprs, *more_exprs, **named_exprs)
   6451 def with_columns(
   6452     self,
   6453     exprs: IntoExpr | Iterable[IntoExpr] = None,
   6454     *more_exprs: IntoExpr,
   6455     **named_exprs: IntoExpr,
   6456 ) -> Self:
   6457     """
   6458     Add columns to this DataFrame.
   6459 
   (...)
   6599 
   6600     """
   6601     return self._from_pydf(
-> 6602         self.lazy()
   6603         .with_columns(exprs, *more_exprs, **named_exprs)
   6604         .collect(no_optimization=True)
   6605         ._df
   6606     )

File ~/miniconda3/envs/test/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py:1438, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1427     common_subplan_elimination = False
   1429 ldf = self._ldf.optimization_toggle(
   1430     type_coercion,
   1431     predicate_pushdown,
   (...)
   1436     streaming,
   1437 )
-> 1438 return pli.wrap_df(ldf.collect())

PanicException: Unwrapped panic from Python code

**Comment by zundertj** [comment]
Sorry, I don't understand what you are trying to say in this post, could you be more specific about what is the issue with dateutils here?

So far, we have established there is a bug where the `skip_nulls` arg for `Expr.apply` is not respected, per my code example above; hopefully that is an easy fix for @ritchie46 .
