### ISSUE TITLE
Add a way to add formulas to the write_excel polars function

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#7521]
### Problem description

I'd love to be able to write excel formulas in the `write_excel` method. **This is super relevant when working with excel plugins**.

I'm not sure what the syntax should be - it's non-trivial given one can "move" the table using the `position` argument.

However, here's an idea:

```python
df = pl.DataFrame({
 'col1': [1,2,3],
 'col2': [5,6,7],
}).with_columns(col3 = pl.lit('={col1} * {col2}')

# The formula above is trivial, but it's super relevant to integrate with third party plugins.

df.write_excel(..., formula_columns=['col3'])

```

The `.write_excel` method would have to do some magic to ensure the formula is referencing the right columns & row numbers.

**Comment by alexander-beedie** [comment]
Yep, this will be a great feature - I have it on the TODO list. 

I'm fairly sure now (after a little experimentation) that the "right" way to do this is for the caller to use Excel's structured references syntax in the formulae, as they are guaranteed to be table-relative (and the way I wrote the exporter means we always produce a real/named table object).

When I implement it (quite soon) I'll make sure to add some examples to demonstrate... ;)

**Comment by mkleinbort-ic** [comment]
Amazing!

**Comment by alexander-beedie** [comment]
FYI, just finished a new `row_totals` capability that is also acting as a test-run for formula support based on structured references (as you can see from the screenshot). Will add a general `formulas` param next, then add some tests. Should be good to go soon. 

<img width="543" alt="row_totals" src="https://user-images.githubusercontent.com/2613171/227354850-185d302a-9fe8-4c55-9fb7-b42bb2e56d44.png">

↑ Generated by...

```python
cols = tuple( df.columns )

df.write_excel(
    conditional_formats = {
        cols: [
            {"type":"3_color_scale"},
            {"type":"unique", "format":{"font_color":"#ffffff"}},
            {"type":"cell", "criteria":"between", "minimum":30, "maximum":55, "format":{"bold":True}},
        ],
    },
    column_formats = {"tot": {"fg_color":"white", "align":"center", "bold":True}},
    column_widths = {cols: 45},
    row_totals = True,  # << generates a SUM formula using structured references
    hide_gridlines = True,
)
```

**Comment by mkleinbort-ic** [comment]
QQ: Does your code support row-wise formats? Thinking of configuring headers mainly.

**Comment by alexander-beedie** [comment]
> QQ: Does your code support row-wise formats? Thinking of configuring headers mainly.

Only via xlsxwriter integration at the moment, but I could add a parameter dedicated to header formatting. If you'd like that, feel free to make it a separate Issue, so I can track it more easily 👍 

FYI: just finished `formulas` support - will write some test coverage and push tomorrow.

Here's an example, demonstrating some structured reference syntax; calculates a z-score.
(Will include the full example in the docstring/help).
```python
df.write_excel(
    column_totals="average",
    formulas={
        "z-score": {
            "formula": "=STANDARDIZE([@points],[[#Totals],[points]],STDEV([points]))",
            "insert_after": "points",
            "return_dtype": pl.Float64,
        }
    },
)
```
