### ISSUE TITLE
Change the List namespace accessor to `.list`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7529]
The current naming is confusing to me:

Datatype: `List`
Class name: `ListNameSpace`
API reference header: ~Array~ `List`
Accessor: `.arr`

I was looking for the List namespace in the docs, and it took me a while to find that I should look under Array.
And I have also typed `pl.col(...).list.` waiting for autocomplete to pop up, only to realize I should type `.arr`.

I think the accessor should be renamed to `.list`.

**Comment by stinodego** [comment]
Eh, I guess this clashes with the existing `Expr.list` - maybe a bad suggestion; is there maybe a better solution to this minor problem?

**Comment by ghuls** [comment]
`.lst` would be a better name to use for List namespace than `list` and avoid renaming `Expr.list()` to `to_list` (as the latter is used already on Series for converting to a python list (while current Expr.list` is used to create arrow lists.

**Comment by ritchie46** [comment]
Right, `implode` is a good opposite name. Then we can go for the `list` namespace if we change both. :+1:

**Comment by stinodego** [comment]
I'll whip up a PR 🤓

**Comment by stinodego** [comment]
Closed by https://github.com/pola-rs/polars/pull/8999
