### ISSUE TITLE
IPython CLI tab completion for Namespaces

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#7540]
### Problem description

Not sure if it is possible, but it would be nice if IPython TAB completion would work for Namespaces when running the cli version of `ipython`.

So it would be possible to easily display help in `ipython` then needing to look in the webbrowser.

```python
❯ ipython
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import polars as pl

In [2]: pl.Expr.str.
                     deleter() fset     
                     fdel      getter() 
                     fget()    setter()

In [3]: ?pl.Expr.str.concat
Object `pl.Expr.str.concat` not found.
```

**Comment by MarcoGorelli** [comment]
totally agree - closing in favour of https://github.com/pola-rs/polars/issues/16933 which has some more details
