### ISSUE TITLE
Error when using head/tail with a negative number on an empty data frame

### ISSUE THREAD

**Issue by gwerbin** [pola-rs/polars#7550]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using `DataFrame.head` or `DataFrame.tail` methods with a negative input on an empty data frame, I get an exception about casting and unsigned ints:

```none
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[2], line 1
----> 1 pl.DataFrame(schema=[('x', float), ('y', float)]).tail(-1)

File <...>/lib/python3.10/site-packages/polars/internals/dataframe/frame.py:3867, in DataFrame.tail(self, n)
   3865 if n < 0:
   3866     n = len(self) + n
-> 3867 return self._from_pydf(self._df.tail(n))

OverflowError: can't convert negative int to unsigned
```

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(schema=[('x', float), ('y', float)])
df.tail(-1)
df.head(-1)
```

### Expected behavior

I expected a 0-row data frame and no error, as you would get with any non-negative integer input on an empty data frame.

### Installed versions

I am using 0.16.12 instead of 0.6.13, as this is the latest available in Conda Forge.

<details>

```none
---Version info---
Polars: 0.16.12
Index type: UInt32
Platform: macOS-12.4-arm64-arm-64bit
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.3.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.1
```

</details>

**Comment by Arengard** [comment]
why?

**Comment by stinodego** [comment]
Yep, our handling of negative inputs is flawed. I'll pick this up.
