### ISSUE TITLE
support for pyarrow.dataset

### ISSUE THREAD

**Issue by cboettig** [pola-rs/polars#7552]
### Problem description

Documentation shows working with pyarrow and a single parquet file with ParquetDataset, but not arrow's more flexible `dataset` mechanism which works with streaming large and potentially partitioned datasets (other than by attempting to read the whole thing into memory with `.to_table()`.  

Consider this example with a widely used public parquet database:

```
import polars as pl
from pyarrow import fs         # note we don't need s3fs, Arrow's native S3 support seems to be faster...
import pyarrow.dataset as ds

# public data, anonymous access ok
bucket = "gbif-open-data-us-east-1"
path = "occurrence/2023-02-01/occurrence.parquet/"
dataset = ds.dataset(f"s3://{bucket}/{path}")

# reads everything into RAM and crashes
# df = pl.from_arrow(dataset.to_table()) 

# we can read the first few rows, no problem
df = pl.from_arrow(dataset.head(10)) 

# now we have full polars power on `df`, but not over the lazy + S3-remote arrow interface
```

It would be wonderful if we could use polars syntax to lazily query the whole `df` object without attempting to coerce it into a table.  We can kinda do such operations via pyarrow 'dataset' module (e.g. the `filter` argument to `to_table()`), but the syntax involved is far more cumbersome.  (R users can already use a polars-like piped syntax with arrow to do lazy queries with filter, select, join, aggregations, etc).  Maybe this is already possible in polars but I'm not understanding the syntax?

**Comment by ritchie46** [comment]
Are you familiar with `scan_pyarrow_dataset`?

**Comment by cboettig** [comment]
:exploding_head: amazing, thanks!

(didn't see this in the very nice https://pola-rs.github.io/polars-book/user-guide/lazy-api/streaming.html but I found https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_pyarrow_dataset.html#polars-scan-pyarrow-dataset.  Is there a handy list of what polars operations are supported here?

**Comment by ritchie46** [comment]
What's you polars version?

**Comment by cboettig** [comment]
`pl.__version__` 

0.16.13

**Comment by ritchie46** [comment]
Right. I think we must explicitly call `head` internally then. Pyarrow does not seems to allow calling a combination of head, columns and filters. 

Does anybody know how we can send all these 3 optimizations into pyarrow datasets?

**Comment by ghuls** [comment]
@ritchie46 All PyArrow datasets methods have a kwargs argument to specify the column selection and filters:

The list of kwargs that can be passed: https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Scanner.html#pyarrow.dataset.Scanner.from_dataset

```
In [15]: %time pl.from_arrow(dset.head(10, columns=["kingdom", "phylum", "family"]))
CPU times: user 1.16 s, sys: 198 ms, total: 1.35 s
Wall time: 2.07 s
Out[15]: 
shape: (10, 3)
┌──────────┬──────────────┬──────────────────┐
│ kingdom  ┆ phylum       ┆ family           │
│ ---      ┆ ---          ┆ ---              │
│ str      ┆ str          ┆ str              │
╞══════════╪══════════════╪══════════════════╡
│ Animalia ┆ Arthropoda   ┆ Libellulidae     │
│ Plantae  ┆ Tracheophyta ┆ Orobanchaceae    │
│ Animalia ┆ Arthropoda   ┆ Lycaenidae       │
│ Plantae  ┆ Tracheophyta ┆ Solanaceae       │
│ Animalia ┆ Arthropoda   ┆ Nymphalidae      │
│ Animalia ┆ Chordata     ┆ Recurvirostridae │
│ Plantae  ┆ Tracheophyta ┆ Caryophyllaceae  │
│ Animalia ┆ Chordata     ┆ Chelydridae      │
│ Animalia ┆ Arthropoda   ┆ Coenagrionidae   │
│ Animalia ┆ Arthropoda   ┆ Geometridae      │
└──────────┴──────────────┴──────────────────┘

In [16]: %time pl.from_arrow(dset.head(10, columns=["kingdom", "phylum", "family"], filter=pc.field("family").isin(["Solanaceae", "Caryophyllaceae", "Orobanchaceae"])))
CPU times: user 801 ms, sys: 53.8 ms, total: 855 ms
Wall time: 1.43 s
Out[16]: 
shape: (10, 3)
┌─────────┬──────────────┬─────────────────┐
│ kingdom ┆ phylum       ┆ family          │
│ ---     ┆ ---          ┆ ---             │
│ str     ┆ str          ┆ str             │
╞═════════╪══════════════╪═════════════════╡
│ Plantae ┆ Tracheophyta ┆ Orobanchaceae   │
│ Plantae ┆ Tracheophyta ┆ Solanaceae      │
│ Plantae ┆ Tracheophyta ┆ Caryophyllaceae │
│ Plantae ┆ Tracheophyta ┆ Solanaceae      │
│ Plantae ┆ Tracheophyta ┆ Orobanchaceae   │
│ Plantae ┆ Tracheophyta ┆ Solanaceae      │
│ Plantae ┆ Tracheophyta ┆ Caryophyllaceae │
│ Plantae ┆ Tracheophyta ┆ Caryophyllaceae │
│ Plantae ┆ Tracheophyta ┆ Solanaceae      │
│ Plantae ┆ Tracheophyta ┆ Caryophyllaceae │
└─────────┴──────────────┴─────────────────┘
```

**Comment by ritchie46** [comment]
Right. Thanks @ghuls that's what we needed.
