### ISSUE TITLE
how to Convert Series  to Vec<Int64> ????

### ISSUE THREAD

**Issue by yhnu** [pola-rs/polars#756]
Are you using Python or Rust?
Rust

What version of polars are you using?
0.14.1

What operating system are you using polars on?
windows

```rust
let df = CsvReader::from_path(p.to_str().unwrap()).unwrap();
let df = read_csv(p)?;
let s = &df["Frames"];
//how to Convert Series  to Vec<Int64> ????
```

**Comment by ritchie46** [comment]
I added an example for you in the [cookbook](https://pola-rs.github.io/polars/polars/docs/eager/index.html#extracting-data)

**Comment by yhnu** [comment]
thanks a lot
