### ISSUE TITLE
InvalidOperationError: cannot cast decimal[0] to f32

### ISSUE THREAD

**Issue by arachnegl** [pola-rs/polars#7566]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I don't seem able to cast Decimals to other types such as Integer or Float.

Specifically when I read an avro file where the schema tells me the Decimal has scale 0, I want to cast to Integer.

This worked till the recent support for `Decimal`s in polars (eg release 0.16.9) Now it fails.

Is this a bug or am I missing something?

Cheers

### Reproducible example

```python
from decimal import Decimal
import polars as pl

df = pl.DataFrame({"decimals": [Decimal('2'), Decimal('2'),],})

df.with_column(pl.col('decimals').cast(pl.Float32).alias('b2'))

# throws: InvalidOperationError: cannot cast decimal[0] to f32
```

### Expected behavior

In 0.16.9 you get this from the above:

```
shape: (2, 2)
┌──────────┬─────┐
│ decimals ┆ b2  │
│ ---      ┆ --- │
│ f64      ┆ f32 │
### ╞══════════╪═════╡
│ 2.0      ┆ 2.0 │
│ 2.0      ┆ 2.0 │
└──────────┴─────┘
```

### Installed versions

Working:

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: macOS-13.0.1-arm64-arm-64bit
Python: 3.10.7 (main, Sep 12 2022, 18:44:24) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.1
```

Not Working:

```
---Version info---
Polars: 0.16.13
Index type: UInt32
Platform: macOS-13.0.1-arm64-arm-64bit
Python: 3.10.7 (main, Sep 12 2022, 18:44:24) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
numpy: 1.23.3
pandas: 1.5.1
pyarrow: 10.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

**Comment by arachnegl** [comment]
@plaflamme would you have an insight to share here please?

**Comment by plaflamme** [comment]
@aldanor did most of the important work on decimal support ultimately

If you're willing to get your hands dirty, I believe you need to add the casting logic [here](https://github.com/pola-rs/polars/blob/ed29fdc91ca3e5db839f1af955f39104de62f91e/polars/polars-core/src/chunked_array/logical/decimal.rs#L73)
