### ISSUE TITLE
give groupby objects an ngroups attribute like in pandas

### ISSUE THREAD

**Issue by alan-isaac** [pola-rs/polars#7571]
### Problem description

Currently, finding the number of groups in a groupby object is hackish. Pandas addressed this with an `ngroups` attribute. I request that pola-rs do so as well. Thanks!

**Comment by zundertj** [comment]
Do you have a code example on the "hackish" approach?  Best I could come up with:

```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [1, 2, 2, 3, 3, 3]})
>>> len(list(df))
3
```

**Comment by ritchie46** [comment]
Seems like another way of asking the number of unique elements:

```python
pl.DataFrame({
    "a": [1, 2, 2, 3, 3, 3],
    "b": [1, 2, 2, 3, 3, 3]
}).select(
    pl.struct(["a", "b"]).n_unique()
).item()
```

**Comment by alan-isaac** [comment]
Effectively, yes. See the discussion [here](https://stackoverflow.com/questions/75739362/number-of-groups-in-a-polars-groupby).

**Comment by alan-isaac** [comment]
> >>> len(list(gb))

@zundertj Does [this pandas discussion](https://stackoverflow.com/a/46512052/2913864) apply?

**Comment by zundertj** [comment]
Yes it does, my solution is not very performant as it will enforce iterating through all groups. If you only use `groupby` to compute the number of groups, but dont need the groupby object, I recommend Ritchies solution.

**Comment by ritchie46** [comment]
If you do need the `groupby` the number of groups is equal to the DataFrame height after aggregation. Getting that is free.

If we would add this to the grouper object we would need to group twice.

**Comment by alan-isaac** [comment]
> If you do need the `groupby` the number of groups is equal to the DataFrame height after aggregation. Getting that is free.
> 
> If we would add this to the grouper object we would need to group twice.


Can you say why? Why couldn't the `ngroups` attribute be added "for free" (using the df height) when the groupby object is created?

**Comment by ritchie46** [comment]
Because there is no aggregated dataframe yet at that point?

**Comment by alan-isaac** [comment]
@ritchie46 I'm not getting it. Maybe its a Rust thing. I cannot come up with a way for it to be "free" but not "attachable for free". In Python, a situation like this would be addressed by creating a property.

**Comment by cmdlineluser** [comment]
@alan-isaac It's like trying to get the length of a generator in Python.
```
>>> evens = (n for n in (1, 2, 3, 4, 5) if n % 2 == 0)
>>> len(evens)
TypeError: object of type 'generator' has no len()
```
It has no length because no "work" has been performed at this point.

This is sometimes referred to as *"lazy evaluation"*.

You have to "run" or "consume" the generator in order for it to produce all its values - which you can get the length of.
```
>>> len(list(evens))
2
```
It's the same with a polars groupby object - it is "lazy", so the length cannot be known until after the fact.

This is why it is up to the user to get the number in a separate step.

**Comment by MarcoGorelli** [comment]
thanks for the request

the suggested solutions seem fine, there doesn't seem to be any need for this to be a groupby attribute - closing for now then

**Comment by alan-isaac** [comment]
@cmdlineluser So if I understand then, the claim that getting the number of groups is "free" was misleading, because asking for the height forces the evaluation.

**Comment by MarcoGorelli** [comment]
I think the claim is that, once you've already done `result = df.group_by(...).agg(...).collect()`, then `result.height` is a (practically) free operation
