### ISSUE TITLE
Implement `DataFrame.write_delta`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7574]
### Problem description

I've been working on this.

Main challenge is that Delta only supports a subset of Polars' types:
* No unsigned integers
* Only microsecond precision Datetime (no TimeZone support)
* No large string/binary/list (only small variant)
* No Time/Duration types
* No Null type

Implementation steps:
- [ ] Implement logic to cast Polars types to closest supported type
- [ ] Raise error on unsupported types.
- [ ] Implement casting from large string/binary/list to small variant in Arrow (ideally implemented in Rust and set as parameter in `to_arrow`)

**Comment by universalmind303** [comment]
>  Implement casting from large string/binary/list to small variant in Arrow (ideally implemented in Rust and set as parameter in to_arrow)

This would be very beneficial in the JS ecosystem too. arrow-js doesn't support large strings, so interop with arrow is currently difficult.

**Comment by stinodego** [comment]
Ritchie offered to implement that part, it's on his backlog 😸 so this will probably be coming soon!

**Comment by stinodego** [comment]
Closed by #7616
