### ISSUE TITLE
Expose PlHashMap to Python

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#7590]
### Problem description

If you are doing joins against a table many many times, is it possible for me to maybe build the probe hash table only once, save that data structure somewhere, and then just join against that?

**Comment by marsupialtail** [comment]
Hmm... if you have ten tables T1 ... T10 to join against Q, I'd imagine that building hash table on Q and joining T1 ... T10 against that hash table is faster than sorting everything and doing a sort merge join for each? I don't know. What do you think?

**Comment by ritchie46** [comment]
No, I mean only sort Q. We use reverse sort the join keys of the other tables. We don't sort the tables.

**Comment by marsupialtail** [comment]
Like is this: https://twitter.com/RitchieVink/status/1533022700003856385 required?

**Comment by ritchie46** [comment]
> Like is this: https://twitter.com/RitchieVink/status/1533022700003856385 required?

Yes, but a sort sets that flag already.

**Comment by marsupialtail** [comment]
Thanks! FWIW, the biggest problem with joins I've found is just that the cost of joins is the cost of joining the key columns + looking up all the other columns. The cost of the second part in that equation quickly dominates the first when you have many columns. The same story with sorts and take. In memory columnar data structure actually makes this much worse when you have random access pattern that needs entire rows. I know there were plans to use row major format in joins in Arrow, but I'm not sure if that PR is actually ever gonna happen.
