### ISSUE TITLE
Option to indicate no limits in POLARS_FMT_MAX_COLS

### ISSUE THREAD

**Issue by pedroangelini** [pola-rs/polars#7591]
### Problem description

I'm new to using Polars, and found myself looking for a way to display **all** the columns in a datafram when using Jupyter (although I think it would be the same in any REPL).
It would be nice to have an option to pass None, or 0, or any other flag to Config.set_tbl_cols, and get all the columns, instead of having to hard code some arbitrary number.

as it is right now, if you set the number to Zero, you get exactly what you asked for, which is correct, but kind of silly

```
with pl.Config() as cfg:
    cfg.set_tbl_cols(0)
    display(latest_properties.collect())
```
Result:
```
shape: (131, 46)
┌─────┐
│ ... │
╞═════╡
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
│ ... │
└─────┘
```

**Comment by alexander-beedie** [comment]
You were just one away... you want `cfg.set_tbl_cols(-1)` ;)

From the relevant docstring:
```
    @classmethod
    def set_tbl_cols(cls, n: int) -> type[Config]:
        """
        Set the number of columns used to print tables.

        Parameters
        ----------
        n : int
            number of columns to print. If n<0 print all the columns.    <<<<<<<<
```

**Comment by pedroangelini** [comment]
Thank you so much @alexander-beedie, I should have read the docs a bit better. Appreciate the quick response.

**Comment by alexander-beedie** [comment]
> Thank you so much @alexander-beedie, I should have read the docs a bit better. Appreciate the quick response.

No problem; I've clarified the docs a little to make it a bit more obvious ;)
