### ISSUE TITLE
Cannot convert `int` to `PyBool` with Series/DataFrame schema

### ISSUE THREAD

**Issue by ElDifinitivo** [pola-rs/polars#7615]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a data structure is passed along with a schema in the creation of a DataFrame or Series, where the dtype conversions are attempting to convert `list[int]` (or even just a list of 0 or 1) to `pl.Boolean`, the code will raise `TypeError: 'int' object cannot be converted to 'PyBool'`.

SQL queries pulling columns set as `BOOLEAN` (I believe at least MySQL/MariaDB and SQLite) will return 0 or 1 as its representation, which means the `int` values must be converted either before or after the DataFrame is created.

While Polars will raise a TypeError at initialization, converting the column after from a Polars Int dtype to `pl.Boolean` will work.

### Reproducible example

```python
import polars as pl

data = {"bool": [1, 1, 0, 1, 0]}
schema = {"bool": pl.Boolean}

try:
    df = pl.DataFrame(data, schema)  # will raise TypeError
except TypeError as e:
    print(e)

# Casting after DataFrame creation works, however
df = pl.DataFrame(data)
df = df.with_columns(pl.col("bool").cast(pl.Boolean))
assert df.dtypes == [pl.Boolean]
```

### Expected behavior

```python
import polars as pl

data = {"bool": [1, 1, 0, 1, 0]}
schema = {"bool": pl.Boolean}

df = pl.DataFrame(data, schema)
assert df.dtypes == [pl.Boolean]
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-6.1.19_1-x86_64-with-glibc2.36
Python: 3.9.2 (default, Feb  8 2023, 09:39:22)
[GCC 12.2.0]
---Optional dependencies---
numpy: <not installed>
pandas: <not installed>
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Ahh, I can see that we should already be handling this, but one of the branches doesn't trigger the necessary fallback; will have a fix ready shortly.
