### ISSUE TITLE
Trimming of whitespace while display()-ing Polars DataFrame in Jupyter Lab

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#7629]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Printing strings that have extra whitespaces in them results in it getting trimmed to just one. See below the output from the reproducible example in Jupyter-Lab.

<img width="318" alt="Screenshot 2023-03-18 at 9 53 18 AM" src="https://user-images.githubusercontent.com/66530011/226113483-484a03ef-2206-48ce-9873-459971595c17.png">

`print`ing the table shows the string correctly.

<img width="321" alt="Screenshot 2023-03-18 at 9 55 25 AM" src="https://user-images.githubusercontent.com/66530011/226113578-437b8b0e-8efa-4fea-a439-09acb98f50cf.png">

A lot of Polars users on Python will find themselves on JupyterNotebooks or Jupyter-Lab, so I think it's important to address this correctly.

Note: this does not work with Pandas DataFrames either, so please let me know if it's not an issue that Polars can fix.

### Reproducible example

```python
import polars as pl
pl.config.Config.set_fmt_str_lengths(25)
pl.DataFrame({
    "String 1": "PewPew",
    "String 2": " PewPew ",
    "String 3": "    PewPew    "})
```

### Expected behavior

The output should not trim whitespaces to a single whitespace in strings.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-13.2.1-arm64-arm-64bit
Python: 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ]
---Optional dependencies---
```

</details>

**Comment by ghuls** [comment]
Can check right now, but I assume all spaces are in the html. Multiple consecutive spaces are just not rendered by browser engines, unless `&nbsp;` is used for the second and next spaces.

**Comment by avimallu** [comment]
Okay, thank you.
