### ISSUE TITLE
Add math/binary operator functions

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7633]
### Problem description

https://github.com/pola-rs/polars/issues/4224

Currently, for a math operator:

```python
df.select(
    [
        pl.sum("nrs"),
        pl.col("names").sort(),
        pl.col("names").first().alias("first name"),
        (pl.mean("nrs") * 10).alias("10xnrs"),
    ]
)

```
I found the code could be more clear if we can keep the pattern and do this:
```python
df.select(
    [
        pl.sum("nrs"),
        pl.col("names").sort(),
        pl.col("names").first().alias("first name"),
        pl.mean("nrs").mul(10).alias("10xnrs"),
    ]
)
```
<del> Or maybe have a method `.do()` to take any math operations. For example, `.do(+5)`, `do(*8)`, so:</del>
```python
df.select(
    [
        pl.sum("nrs"),
        pl.col("names").sort(),
        pl.col("names").first().alias("first name"),
        pl.mean("nrs").do(*10).alias("10xnrs"),
    ]
)
```

I would also argue that the code could also be a bit messy under the current implementation for a complex calculation since the only way to define order of operations is via `()`, for example:
```python
df.select(
    [
        pl.sum("nrs"),
        pl.col("names").sort(),
        pl.col("names").first().alias("first name"),
        (((pl.mean("nrs") - pl.col("nrs"))*10 + 10) / (pl.col('nrs')*100)).alias("10xnrs"),
    ]
)
```
If we could have a `div()` method, we can at least break it into two parts I guess. I really hope you could please give it a consideration to add some [math methods](https://pandas.pydata.org/docs/reference/series.html#binary-operator-functions).

**Comment by cmdlineluser** [comment]
I only briefly read through the linked issue - but incase you are not aware - the dunder methods are available:
```
df.select(
   pl.sum("nrs"),
   pl.col("names").sort(),
   pl.col("names").first().alias("first name"),
   (pl.mean("nrs").__sub__(pl.col("nrs")).__mul__(10).__add__(10))
   .__truediv__(pl.col("nrs").__mul__(100))
   .alias("10xnrs")
)
```
```
shape: (5, 4)
┌─────┬───────┬────────────┬────────┐
│ nrs ┆ names ┆ first name ┆ 10xnrs │
│ --- ┆ ---   ┆ ---        ┆ ---    │
│ i64 ┆ str   ┆ str        ┆ f64    │
╞═════╪═══════╪════════════╪════════╡
│ 11  ┆ null  ┆ foo        ┆ 0.275  │
│ 11  ┆ egg   ┆ foo        ┆ 0.0875 │
│ 11  ┆ foo   ┆ foo        ┆ 0.025  │
│ 11  ┆ ham   ┆ foo        ┆ null   │
│ 11  ┆ spam  ┆ foo        ┆ -0.025 │
└─────┴───────┴────────────┴────────┘
```
If you instead wanted to be able to write:
```
(pl.mean("nrs").sub(pl.col("nrs")).mul(10).add(10))
   .div(pl.col("nrs").mul(100))
```
I believe the PR would be to define functions with the "regular" names: https://github.com/pola-rs/polars/blob/master/py-polars/polars/expr/expr.py#L226

**Comment by StevenLi-DS** [comment]
@cmdlineluser Thank you for your reply. I didn't realize there are dunder methods already, but I do think "regular" names are better and easier to read and write.

**Comment by alexander-beedie** [comment]
Closing this in favour of the linked issue, as it seems to be the same thing?
I'll take care of it in the next few days 👍
