### ISSUE TITLE
Honor null values for binary operators

### ISSUE THREAD

**Issue by borchero** [pola-rs/polars#7635]
# Motivation

Suppose I have a series defined as follows:

```python
>> s = Series([1, 2, None, 3])
```

I now want to obtain a mask whether the values in my series are equal to 3. I can easily do that as follows:

```python
>> s == 3

shape: (4,)
Series: '' [bool]
[
	false
	false
	false
	true
]
```

Unfortunately, this operation removes the "validity" information: the third item in the series is not `null` anymore but got assigned a value.

**While I think the current behavior of binary operators (such as for `==` as outlined above) makes sense, it would be nice to preserve nulls.**

# How to solve this?

My first idea would be to introduce binary operators as methods. For the equality operator, the result would be something like the following:

```python
>> s.eq(3)

shape: (4,)
Series: '' [bool]
[
	false
	false
	null
	true
]
```

One could also think of _not_ ignoring `null` values by default but enabling this option by an additional argument, i.e.:

```python
>> s.eq(3, keep_nulls=True)
```

# Implications

If we were to implement methods for the binary operators, we would need to implement them for all of the following in my opinion: `==`, `>=`, `>`, `<=`, `<`, `~`. In general, I'm not sure how intuitive the usage of these functions would be, considering that no equivalent exists e.g. in pandas.

# Alternatives

The behavior described above can be achieved by using `apply` already:

```
>> s.apply(lambda x: x == 3)

shape: (4,)
Series: '' [bool]
[
	false
	false
	null
	true
]
```

However, this implementation is arguably suboptimal due to the runtime implications of the Python function...

_Note: I might well have missed another way of achieve what I describe here with the current version of polars. I did search for it a fair bit of time though._

**Comment by borchero** [comment]
... UPDATE: I actually found out that this already exists, whoops 👀

HOWEVER, I feel like the current implementation is inconsistent when using operators other than `==`, `null` values are actually preserved (I realized that this does not only apply to the methods though).

**Comment by avimallu** [comment]
This is also mentioned in #7595.

**Comment by borchero** [comment]
@avimallu thanks for the hint! Closing this in favor of #7595.
