### ISSUE TITLE
Parallell Series.apply

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#767]
Is it possible to do Series.apply with multiple cores, in python?

Also, I request `na_action`, in particular `na_action='ignore'` to Series.apply or to a new Series.map

**Comment by ritchie46** [comment]
It is. Slicing is free. So you could slice the `Series` in chunks and process them over multiple cores and concat them back to a single `Series`.

What do you mean by you request `na_action`?, what is the current behavior you don't like?

**Comment by tsoernes** [comment]
With Pandas, you do `Series.map(func, na_action='ignore')`. Then `func`
will not be applied to nulls. It avoid having to rewrite functions for
dealing with nulls. E.g. `pd.Series([[], pd.NA]).map(lambda s: s + ['x'],
na_action='ignore')`.

**Comment by tsoernes** [comment]
Very good. It is not the default behavior in pandas but I much appreciate the change. Never any need to map any nulls. Cheers
