### ISSUE TITLE
Error when using the `pyarrow_options` parameter for writing to Azure

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7677]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I can write a parquet to Azure using

```
import polars as pl
import pyarrow.parquet as pq
from adlfs import AzureBlobFileSystem

abfs = AzureBlobFileSystem(account_name='account_name',account_key='account_key')

pq.write_table(polars_dataframe.to_arrow(), 'container/file_name.parquet', filesystem=abfs)
``` 

I'd like to keep everything inside Polars by using the `pyarrow_options` parameter:

```
polars_dataframe.write_parquet('container/file_name.parquet', pyarrow_options={'filesystem':abfs})
```
Using write_parquet with the pyarrow_options however gives an error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### Reproducible example

```python
# See above
```

### Expected behavior

Same result with the file written to Azure, whether using `pq.write_table` or `pl.write_parquet`

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.2 (main, Feb  8 2023, 14:49:25) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <version not detected>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by cannero** [comment]
Hi @lucazanna, did you set the `use_pyarrow` flag to `True` in the `write_parquet` call?

**Comment by lucazanna** [comment]
thank you @cannero ! that was exactly the problem.
