### ISSUE TITLE
Add support for Expr in clip, clip_min, clip_max

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7679]
### Problem description

Sometimes you may want to clip dynamically based on its numerical distribution, such as quantile, but Expr is not supported in clip, clip_min and clip_max:
```python
import polars as pl

df = pl.DataFrame({'a': [1, 2, 3, 4, 5]})
df.with_columns(
    pl.col('a').clip_max(pl.col('a').quantile(0.5))
)
```
The current workaround seems a little bit tedious:
```
# workaround
df.with_columns(
    pl.when(pl.col('a') >= pl.col('a').quantile(0.5))
    .then(pl.col('a').quantile(0.8))
    .otherwise(pl.col('a'))
)
```

```
shape: (5, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ 2.0 │
│ 5.0 │
│ 5.0 │
│ 5.0 │
└─────┘
```
This is like you want to use, say, a mean to fill_null, which supports expr in polars now. It would be great if we could add such support for clip methods as well.

**Comment by cmdlineluser** [comment]
There are a few open issues about this e.g. https://github.com/pola-rs/polars/issues/6470

From the linked issue: @gab23r has a pull request for this https://github.com/pola-rs/polars/pull/6862/files 

It seems they were waiting on some advice regarding its implementation.

**Comment by StevenLi-DS** [comment]
@cmdlineluser sorry I didn't realize that.

**Comment by cmdlineluser** [comment]
@StevenLi-DS No need to apologize - I was just trying to inform you.

Sometimes a fresh reminder can be useful in bringing attention to a particular issue once again - e.g. if progression has stalled for whatever reason.

Searching the issues can be worthwhile as there is a lot of valuable information contained in them.

**Comment by ihopethiswillfi** [comment]
+1 
Pity that the PR didn't get merged.  I'm trying to winsorize several columns, that means I use both `clip_max()` and `clip_min()` on each column.

```
                winsor = 0.99
                col = 'column1'
                df = df.with_columns(
                                        pl.when(pl.col(col) > pl.col(col).quantile(winsor))
                                        .then(pl.col(col).quantile(winsor))
                                        .when(pl.col(col) < pl.col(col).quantile(1-winsor))
                                        .then(pl.col(col).quantile(1-winsor))
                            )
```

It's quite messy.

**Comment by stevenlis** [comment]
@ihopethiswillfi This might be a work around: https://github.com/pola-rs/polars/issues/10263#issuecomment-1664852553
