### ISSUE TITLE
Inconsistent result from .over operation in python polars

### ISSUE THREAD

**Issue by petchpanu** [pola-rs/polars#7681]
### Polars version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I applied the .over method into larger table (more than 1000+ rows) as shown below:

df.select(pl.col('date').min().over('id'))['date'].is_null().sum()

Here, I execute the code above multiple times consecutively, the missing data show incorrect results. The results show an inconsistent number of missing data in each run as shown in the image.
[https://i.stack.imgur.com/60Ueo.png]()

I tried to convert the data to pandas and use .transform method the result was correct. According to pandas, the number of missing data in the date column is 29,436 rows.

Thank you.

The sample data that can reproduce the result is here:
[https://drive.google.com/file/d/1N7cPUq_AgGehMGL-0BuijkOTh6l2D4x5/view?usp=share_link]()

Oneperson in StackOverflow also can reproduce the error.
[https://stackoverflow.com/questions/75796732/inconsistent-result-from-over-operation-in-python-polars?noredirect=1#comment133708855_75796732]()

### Reproducible example

```python
import polars as pl

df = pl.DataFrame('sample.csv')
(pl.read_csv('sample.csv').with_columns(pl.col('date').str.strptime(pl.Date, fmt = '%Y-%m-%dT%H:%M:%S.%f').cast(pl.Date).min().over('id'))['date'].is_null().sum())
```

### Expected behavior

All the id with date should have their minimum date and other without date should be None.

### Installed versions

<details>

```
Polars: 0.15.16
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by cmdlineluser** [comment]
I can also reproduce this.
```
set(
     df.with_columns(pl.col('date').str.strptime(pl.Date, fmt = '%Y-%m-%dT%H:%M:%S.%f').cast(pl.Date).min().over('id'))['date'].is_null().sum() 
     for n in range(1_000)
)
```
```
{1237, 1239, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251}
```
I wonder if it's related to #6650
