### ISSUE TITLE
auto cast dtype when pl.concat

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7688]
### Problem description

Currently `0.16.14`, polars would raise a `ShapeError` when dtype is not the same in the same column of two dataframes.

```python
import polars as pl

df1 = pl.DataFrame({'a': [1, 2], 'b': [1, 4]})
df2 = pl.DataFrame({'a': [1.0, 0.2], 'b': [0.1, 0.1]})
pl.concat([df1, df2])
```
```
ShapeError: unable to vstack, dtypes for column "a" don't match: `i64` and `f64`
```
If you read a set of csv file or something, this could happen very often. It seems like the only way to avoid this is to pass a schemadict. However, the error msg will throw you one column at a time, and it could really take a while to find all problematic columns. So I wonder if we could add a param or something to let polars cast dtype automatically.

**Comment by ysq151944** [comment]
I agree with you.

Or df2's dtypes could be casted into df1's like:
`df2.cast(df1.dtypes)`

**Comment by Jhsmit** [comment]
`pl.DataFrame.cast` does not exist, despite copilot recommending it. 

I wound up doing something like this:
```python
df2.with_columns([pl.col(n).cast(t) for n, t in zip(df1.columns, df1.dtypes)])
```

See also here: https://github.com/pola-rs/polars/issues/4505

**Comment by StevenLi-DS** [comment]
@Jhsmit I'm still on 0.18.2, but your code should work... what did you see on your end?

You are actually using `cast` as an expr here :https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.cast.html

Btw, you can also use schema to return a dict directly https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.schema.html

**Comment by Jhsmit** [comment]
yes, my code worked, just wanted to point out that `df1.cast` does not. 

Thanks for the tip on using `.schema`

**Comment by stevenlis** [comment]
@ritchie46 I just found a weird bug that if you put a f64 before i64, you will still get a ShapeError:

```python
import polars as pl

df1 = pl.DataFrame({'a': [1, 2], 'b': [2, 1]})
df2 = pl.DataFrame({'a': [1.0, 0.2], 'b': [None, 0.1]})

# works fine
pl.concat([df1, df2], how='vertical_relaxed')

# return ShapeError
pl.concat([df2, df1], how='vertical_relaxed')

```
