### ISSUE TITLE
`np.asarray(series, dtype="object")` should return null values as None

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#7690]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See below.

NB: Maybe it makes sense to add a `dtype` argument to `.to_numpy()`.

### Reproducible example

```python
# Converting to np.ndarray[float64] turns null into nan.
# I guess this is fine since np.ndarray[float64] doesn't support null values.
np.asarray(pd.Series([1, float('nan'), None]))
# => array([1.0, nan, nan])

# However, for np.ndarray[object], we may use None values. But Polars doesn't do so.
np.asarray(pd.Series([1, float('nan'), None]), dtype="object")
# => array([1.0, nan, nan], dtype=object)

# Using None values would be consistent with .to_list():
pl.Series([1, float('nan'), None]).to_list()
# => [1.0, nan, None]

# And also Pandas:
np.asarray(pd.Series([1, float('nan'), None], dtype="object"), dtype="object")
# => array([1, nan, None], dtype=object)
```

### Expected behavior

IMO converting to an `np.ndarray[object]` should turn null values into None.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-12.6.3-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by jonashaag** [comment]
@ritchie46 @stinodego @alexander-beedie if you agree with my opinion I'll take a stab at this

**Comment by alexander-beedie** [comment]
FYI: all of your examples are using pandas, not polars ;)
Fixing that does give the same results though, eg:
```python
np.asarray( pl.Series([1,float('nan'),None]), dtype=pl.Object )
# array([1.0, nan, nan], dtype=object)
```
I think returning `None` where able does make sense though; any potential downsides? 
(Performance, compatibility, etc...)

**Comment by jonashaag** [comment]
Hmm, this is incompatible with `np.asarray(pyarrow.array(...), dtype="object")`. Maybe this is something that should be discussed with PyArrow and/or the array interchange protocol first.

**Comment by stinodego** [comment]
This should be an issue in the NumPy repo or in the pyarrow repo.

We already offer the desired conversion:

```python
import polars as pl

s = pl.Series([1, float("nan"), None], dtype=pl.Object)
out = s.to_numpy(use_pyarrow=False)
print(out)  # [1 nan None]
```

Note that you cannot cast an existing Float Series to `Object` as this is not supported- that could be its own issue (feel free to open an issue for this).

With `use_pyarrow=True`, you get the `nan/nan` behavior as you noted. If you want that behavior changed, you should report to pyarrow.

```python
import polars as pl

s = pl.Series([1, float("nan"), None])
out = s.to_numpy(use_pyarrow=True)
print(out)  # [1 nan nan]
```

If you want `np.asarray` to behave a certain way, you should report to NumPy.
