### ISSUE TITLE
"Already mutably borrowed" when using `.set_at_idx`

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#7691]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See below. The example I'm giving probably doesn't make too much sense but it is derived from a real world example that makes a little bit more sense

### Reproducible example

```python
s = pl.Series([42])
s.set_at_idx(~s.is_null(), s)
# => RuntimeError: Already mutably borrowed

s.set_at_idx(~s.is_null(), s.clone())  # ok
```

### Expected behavior

Should not raise

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-12.6.3-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by cannero** [comment]
Does it even work as expected with the null check?
`is_null` returns a bool which is then cast to 0 or 1, so only the first two rows will be affected.

```python
>>> s = pl.Series([0, None, 2, 3, None])
>>> s
shape: (5,)
Series: '' [i64]
[
        0
        null
        2
        3
        null
]
>>> s.set_at_idx(~s.is_null(), 999)
shape: (5,)
Series: '' [i64]
[
        999
        999
        2
        3
        null
]
```

Or do you see some solution to use the same object as Series and as `value`? Currently the implementation needs a mutable access to the replacement values parameter and `set_at_idx` already mutates the series, so rust does not allow this function call.

**Comment by jonashaag** [comment]
Whoops. I wanted to do replace null values with other values from the same series (but not a single value like with `.set()`). But using `set_at_idx` this way doesn't make sense and probably there is a more idiomatic way to achieve what I wanted to do in the first place.

**Comment by cannero** [comment]
I'm not sure if this is the best way, but one possibility to get a list of all null indices would be

```python
s = pl.Series("a", [0, None, 2, 3, None])

s_index = (
    pl.Series("index", list(range(len(s))))
    .filter(s.is_null())
)

Series: 'index' [i64]
[
        1
        4
]
```

Like you said maybe there is a more idiomatic way. With which values should the `nulls` be replaced? Is it possible with the [When-Then](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.when.html#polars.when) expression or with interpolation?

**Comment by cannero** [comment]
Yes, it looks like `when` with a series is not possible. I would have used a `LazyFrame` and computed the new column without nulls with a `with_columns` if `fill_null` on a series is not possible.

**Comment by ghuls** [comment]
> How do you use `when` with a series?

convert the series to a dataframe with `s.to_frame.()`, do the when then operation and convert back to a series with `.to_series()`.

**Comment by ritchie46** [comment]
Yeap, or a `pl.select` to create a context on the fly.

`pl.select(pl.when(pl.Series([True, False])).then(1).otherwise(2)))`
