### ISSUE TITLE
Make `map_dict` infer output dtype (python)

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#7700]
### Problem description

Right now `map_dict` has the output dtype `Unknown` which makes it difficult to use in some queries, for example if you do a `pl.col(<DTYPE>)` after `map_dict`. This can be solved by always manually casting, but I think it could be added into the function itself.

### Example:
```python
import polars as pl

df = pl.LazyFrame({'x': [1,2]})
print(
    df.with_columns(pl.col('x').map_dict({1:1})).schema # {'x': Unknown}
)
# Workaround
print(
    df.with_columns(pl.col('x').map_dict({1:1}).cast(pl.Int64)).schema # {'x': Int64}
)
```

It would require a more strict check on the mapping dictionaries values, in the same way as a check on the mapping dictionaries keys were added in #7393. I think this is preferable too, as now it will silently drop mistyped values. Example:
```python
import polars as pl
df = pl.LazyFrame({'x': [1,2]})

print(
df.with_columns(pl.col('x').map_dict({1: 1, 2: '2'})).collect()
)
# shape: (2, 1)
# ┌──────┐
# │ x    │
# │ ---  │
# │ str  │
# ╞══════╡
# │ null │
# │ 2    │
# └──────┘
# Not obvious beforehand what values will be dropped
``` 

In #7389 it was noted that it is a problem with the query if there is a type mismatch in the mapping dict and while I agree with that I can't see the issue with explicitly enforcing it, with the added benefit of having the dtype in the schema later on.

**Comment by ghuls** [comment]
In https://github.com/pola-rs/polars/pull/7797, you can specify the output dtype.

At the moment it doesn't really help for the `LazyFrame` `pl.Unknown` problem:

```python
In [22]: df = pl.LazyFrame({'x': [1,2]})
    ...: print(
    ...:     df.with_columns(pl.col('x').map_dict({1:1}, dtype=pl.Int32)).schema # {'x': Unknown}
    ...: )
{'x': Unknown}

# Here it seems that the dtype supposedly could be set in the schema, but as seen below, the output dtype is not necessary stable.
In [23]: df = pl.LazyFrame({'x': [1,2]})
    ...: print(
    ...:     df.with_columns(pl.col('x').map_dict({1:1}, dtype=pl.Int8)).collect() # {'x': Unknown}
    ...: )
shape: (2, 1)
┌──────┐
│ x    │
│ ---  │
│ i8  │
╞══════╡
│ 1    │
│ null │
└──────┘


In [24]: df = pl.LazyFrame({'x': [1,2]})
    ...: print(
    ...:     df.with_columns(pl.col('x').map_dict({1:1}, default=8, dtype=pl.Int8)).collect() # {'x': Unknown}
    ...: )
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ i8  │
╞═════╡
│ 1   │
│ 8   │
└─────┘

In [25]: df = pl.LazyFrame({'x': [1,2]})
    ...: print(
    ...:     df.with_columns(pl.col('x').map_dict({1:1}, default=888, dtype=pl.Int8)).collect() # {'x': Unknown}
    ...: )
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
│ 888 │
└─────┘
```

**Comment by StefanBRas** [comment]
Thanks, I see that it's not trivial to solve the general case.

In my own code I'll probably add a `map_dict_strict` that enforces all dict values to be of same type and then do a `map_dict(...).cast(...)`.

Maybe the docstring for `map_dict` should note that the schema dtype will be `unknown` and/or that it will cast dict values to other types if they are not all the same?

**Comment by stinodego** [comment]
This is outdated since the re-implementation of this function as `replace`.
