### ISSUE TITLE
Using `.from_pandas` with empty series raises

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#7708]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See example below.

### Reproducible example

```python
pl.from_pandas(pd.Series([]))
# => TypeError: an integer is required
```

### Expected behavior

Should not raise.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-12.6.3-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Interesting; I couldn't reproduce with pandas 1.5.x - this errors appears to be specific to pandas 2.0rc+. I'll see what we can do about it.
