### ISSUE TITLE
Ommission in user guide of floating point data types?

### ISSUE THREAD

**Issue by hhoeflin** [pola-rs/polars#771]
On the user guide here:

https://pola-rs.github.io/polars-book/user-guide/datatypes.html

You list the data types. They are supposed to be the "Arrow" data types https://arrow.apache.org/docs/python/api/datatypes.html
but all floating point data types are missing.

Is this an error or deliberate?

**Comment by ritchie46** [comment]
They are missing in the user guide. Sorry, I will add them.

**Comment by ritchie46** [comment]
Done. :+1:

**Comment by hhoeflin** [comment]
Quick follow-up. Arrow has float16, which is not on the list?

**Comment by ritchie46** [comment]
No, float16 is not supported. Also the rust implementation of arrow has almost no float16 support.

**Comment by hhoeflin** [comment]
Great, thanks. As the other exceptions to support are listed, maybe this could be added to the list as well. Is good to know, as I use float16 from time to time.

**Comment by benjaminrwilson** [comment]
@ritchie46, how difficult do you think adding `float16` support would be?
