### ISSUE TITLE
Add custom style for _repr_html_

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#7726]
### Problem description

Inspired by [this](https://stackoverflow.com/questions/75823274/polars-rendering-a-dataframe-in-the-densest-way-possible) question.

It'd be nice if there were a feature to change the stylesheet of the _repr_html_ without monkey patching and preloading internals to monkey patch

Maybe we can introduce an os variable POLARS_CUSTOM_STYLE_STRING and then the `write_style` method in the `NotebookFormatter` could check if that exists and, if so, use that as style instead of the default.  I'm not sure if that introduces concerns about overloading the length of os variables.

**Comment by deanm0000** [comment]
The issue with that approach is that it's global and retroactive to previous cells so if someone's making a report where one table should have one format and the next another, this doesn't help with that. I think that's where the asker of the SO question is coming from anyway.

**Comment by 2-5** [comment]
But `POLARS_CUSTOM_STYLE_STRING` would have the exact same problem. CSS style is global, is not scoped. To fix that, you would also need to overwrite the CSS class (`POLARS_CUSTOM_CLASS_NAME=".my-dataframe"`)

**Comment by deanm0000** [comment]
You're right. I didn't articulate the intention very well. I'm not good at CSS and HTML styling so that doesn't help. 

I guess the only thing that makes sense is to ask for then is a full styler like pandas has. Asking for little things piecemeal doesn't make much sense. I don't know if that's the best priority right now though.
