### ISSUE TITLE
`Expr.pipe` missing from the API reference

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7730]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have been using Expr.pipe from https://github.com/pola-rs/polars/pull/7134, and I just noticed that it is not listed in the API reference.

The API reference has entries for DataFrame.pipe, LazyFrame.pipe but not Expr.pipe
https://pola-rs.github.io/polars/py-polars/html/search.html?q=pipe

If someone can point me in the right direction, I would also be happy to submit a PR for it

### Reproducible example

```python
# not applicable
```

### Expected behavior

Expr.pipe in the API reference

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by alexander-beedie** [comment]
(Closed by #7734)
