### ISSUE TITLE
pivot may introduce duplicate column names

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7731]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I can't find this in the docs right now, but I remember having read that in polars the column names should be unique. The fact `DataFrame.schema` returns a dict certainly suggests it.

However, the code below outputs
```python
shape: (2, 7)
┌─────┬─────┬─────┬──────┬──────┬──────┬──────┐
│ b   ┆ a_x ┆ d_x ┆ a_x  ┆ a_y  ┆ d_x  ┆ d_y  │
│ --- ┆ --- ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64 ┆ i64 ┆ i64 ┆ i64  ┆ i64  ┆ i64  ┆ i64  │
╞═════╪═════╪═════╪══════╪══════╪══════╪══════╡
│ 1   ┆ 1   ┆ 7   ┆ 1    ┆ null ┆ 7    ┆ null │
│ 2   ┆ 4   ┆ 8   ┆ null ┆ 4    ┆ null ┆ 8    │
└─────┴─────┴─────┴──────┴──────┴──────┴──────┘
```

Note how `a_x` and `d_x` both appear twice

### Reproducible example

```python
df = pl.DataFrame({'a':[1,4],'b':[1,2],'c':['x','x'],'d':[7,8], 'e':['x', 'y']})
df.pivot(values=['a', 'd'], index='b', columns=['c', 'e'])
```

### Expected behavior

Perhaps if there are multiple columns and multiple values, then the columns should be named as

`f'{value_name}_{column_name}_{column_value}'`

which in this case would give:
```python
shape: (2, 7)
┌─────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ b   ┆ a_c_x ┆ d_c_x ┆ a_e_x ┆ a_e_y ┆ d_e_x ┆ d_e_y │
│ --- ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ i64   ┆ i64   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 1   ┆ 1     ┆ 7     ┆ 1     ┆ null  ┆ 7     ┆ null  │
│ 2   ┆ 4     ┆ 8     ┆ null  ┆ 4     ┆ null  ┆ 8     │
└─────┴───────┴───────┴───────┴───────┴───────┴───────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
Simpler reproducer:
```python
In [85]: df = pl.DataFrame({'a': [1,2], 'b': [1,2], 'c': ['x','x'], 'd': ['x', 'y']})

In [86]: df
Out[86]:
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 1   ┆ x   ┆ x   │
│ 2   ┆ 2   ┆ x   ┆ y   │
└─────┴─────┴─────┴─────┘

In [87]: df.pivot(values='a', index='b', columns=['c', 'd'])
Out[87]:
shape: (2, 4)
┌─────┬─────┬──────┬──────┐
│ b   ┆ x   ┆ x    ┆ y    │
│ --- ┆ --- ┆ ---  ┆ ---  │
│ i64 ┆ i64 ┆ i64  ┆ i64  │
╞═════╪═════╪══════╪══════╡
│ 1   ┆ 1   ┆ 1    ┆ null │
│ 2   ┆ 2   ┆ null ┆ 2    │
└─────┴─────┴──────┴──────┘
```

**Comment by ritchie46** [comment]
Thanks. Will fix it

**Comment by MarcoGorelli** [comment]
> Perhaps if there are multiple columns and multiple values, then the columns should be named as
> f'{value_name}_{column_name}_{column_value}'

might be better to just have a column for each unique combination of `columns`, which here would be:

```python
shape: (2, 3)
┌─────┬──────┬──────┐
│ b   ┆ x_x  ┆ x_y  │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ i64  ┆ i64  │
╞═════╪══════╪══════╡
│ 1   ┆ 1    ┆ null │
│ 2   ┆ null ┆ 2    │
└─────┴──────┴──────┘
```

This would more closely align with pandas' output (if the multiindex columns were squashed into a single index)
```python
c    x
d    x    y
b
1  1.0  NaN
2  NaN  2.0
```

For context, I came across this whilst looking into https://github.com/data-apis/dataframe-api/pull/119

**Comment by alonme** [comment]
@ritchie46 Are you taking this one?
If not - any decision regarding what would the desired solution be?

**Comment by ritchie46** [comment]
@MarcoGorelli suggestion is what we want to add. This is breaking so we want this added in next 0.17 release.

**Comment by bernardodionisi** [comment]
@ritchie46 In the above example, when `values` has only one column the output produces a dataframe with duplicate column names 


```python
df = pl.DataFrame({
    'a':[1,4],
    'b':[1,2],
    'c':['x','x'],
    'd':[7,8], 
    'e':['x', 'y']
})
df.pivot(values=['a'], index='b', columns=['c', 'e'])
```

output:

```
shape: (2, 4)
┌─────┬─────┬──────┬──────┐
│ b   ┆ x   ┆ x    ┆ y    │
│ --- ┆ --- ┆ ---  ┆ ---  │
│ i64 ┆ i64 ┆ i64  ┆ i64  │
╞═════╪═════╪══════╪══════╡
│ 1   ┆ 1   ┆ 1    ┆ null │
│ 2   ┆ 4   ┆ null ┆ 4    │
└─────┴─────┴──────┴──────┘
```

the case with two columns works fine

```python
df = pl.DataFrame({
    'a':[1,4],
    'b':[1,2],
    'c':['x','x'],
    'd':[7,8], 
    'e':['x', 'y']
})
df.pivot(values=['a', 'd'], index='b', columns=['c', 'e'])
```


```
shape: (2, 7)
┌─────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ b   ┆ a_c_x ┆ d_c_x ┆ a_e_x ┆ a_e_y ┆ d_e_x ┆ d_e_y │
│ --- ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ i64   ┆ i64   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 1   ┆ 1     ┆ 7     ┆ 1     ┆ null  ┆ 7     ┆ null  │
│ 2   ┆ 4     ┆ 8     ┆ null  ┆ 4     ┆ null  ┆ 8     │
└─────┴───────┴───────┴───────┴───────┴───────┴───────┘
```
<details>

```
--------Version info---------
Polars:              0.19.0
Index type:          UInt32
Platform:            Linux-5.15.109+-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             9.0.0
pydantic:            2.2.1
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by henryharbeck** [comment]
@MarcoGorelli, @ritchie46 - In line with the above comment, I think this issue is not fully resolved.


This example from above still produces duplicate column names.
> Simpler reproducer:
> 
> ```python
> In [85]: df = pl.DataFrame({'a': [1,2], 'b': [1,2], 'c': ['x','x'], 'd': ['x', 'y']})
> 
> In [86]: df
> Out[86]:
> shape: (2, 4)
> ┌─────┬─────┬─────┬─────┐
> │ a   ┆ b   ┆ c   ┆ d   │
> │ --- ┆ --- ┆ --- ┆ --- │
> │ i64 ┆ i64 ┆ str ┆ str │
> ╞═════╪═════╪═════╪═════╡
> │ 1   ┆ 1   ┆ x   ┆ x   │
> │ 2   ┆ 2   ┆ x   ┆ y   │
> └─────┴─────┴─────┴─────┘
> 
> In [87]: df.pivot(values='a', index='b', columns=['c', 'd'])
> Out[87]:
> shape: (2, 4)
> ┌─────┬─────┬──────┬──────┐
> │ b   ┆ x   ┆ x    ┆ y    │
> │ --- ┆ --- ┆ ---  ┆ ---  │
> │ i64 ┆ i64 ┆ i64  ┆ i64  │
> ╞═════╪═════╪══════╪══════╡
> │ 1   ┆ 1   ┆ 1    ┆ null │
> │ 2   ┆ 2   ┆ null ┆ 2    │
> └─────┴─────┴──────┴──────┘
> ```

I'm happy to raise this as a new issue if you'd prefer that over re-opening this one.

Thanks

**Comment by MarcoGorelli** [comment]
thanks @henryharbeck for the report! yes I think a new issue would be easier to deal with, thanks 🙏

**Comment by henryharbeck** [comment]
Done, cheers for the quick response @MarcoGorelli
