### ISSUE TITLE
Segmentation fault encountered in calculation involving large polars dataframe

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#7733]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Encountered 'Segmentation fault' in large dataframe calculation. The same calculation runs fine on smaller dataframes.

### Reproducible example

```python
import numpy as np
import polars as pl

nbr_groups = 1000
nbr_obs_per_group = 10000

rng = np.random.default_rng(1)

df = pl.DataFrame(
    {
        "g": list(range(0, nbr_groups)) * nbr_obs_per_group,
        "a": rng.normal(0, 1, nbr_obs_per_group * nbr_groups),
        "b": rng.normal(0, 1, nbr_obs_per_group * nbr_groups),
        "c": 0,
    }
)

df.groupby("g").agg(
    [
        (
            pl.col("a")
            * (pl.col("b") - pl.col("b").filter(pl.col("c") > 0).mean())
            * (pl.col("c") == i)
        )
        .sum()
        .alias(f"{i}")
        for i in range(3)
    ]
)
```

### Expected behavior

All ```0``` or ```null```.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.17
Python: 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by MichalLebeda** [comment]
Have similar issue with groupby_dynamic/rolling

**Comment by ritchie46** [comment]
> Have similar issue with groupby_dynamic/rolling

Do you use different expressions? If so, can you make a separate issue for that?

**Comment by MichalLebeda** [comment]
@ritchie46 I am not able to reliably reproduce the issue. I use `min()\` on datetime column with ```groupby_rolling```. When i swap it to first, it seems ok. Will open a new issue if I manage to reproduce it.
