### ISSUE TITLE
Implement pl.Series strict mode for pl.Utf8

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#7738]
### Problem description

It would be great if pl.Series would have a `strict=True` mode for pl.Utf8 like we have for numbers, so if you give it a python list with non-strings it would fail.

Now the following happens:

```python
In [10]: pl.Series("a", [0, "e"], dtype=pl.UInt8, strict=True)
Out[10]: 
shape: (2,)
Series: 'a' [str]
[
	null
	"e"
]

In [11]: pl.Series("a", [0, "e"], dtype=pl.Utf8, strict=True)
Out[11]: 
shape: (2,)
Series: 'a' [str]
[
	null
	"e"
]
```

This would solve the second part of https://github.com/pola-rs/polars/issues/7700 automatically:

```python
import polars as pl
df = pl.LazyFrame({'x': [1,2]})

print(
    df.with_columns(pl.col('x').map_dict({1: 1, 2: '2'})).collect()
)
# shape: (2, 1)
# ┌──────┐
# │ x    │
# │ ---  │
# │ str  │
# ╞══════╡
# │ null │
# │ 2    │
# └──────┘
# Not obvious beforehand what values will be dropped
```

**Comment by stinodego** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/14427
