### ISSUE TITLE
Lazyframe and query chain results in the wrong output

### ISSUE THREAD

**Issue by ddutt** [pola-rs/polars#7741]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

With lazyframes, the two pieces of code listed result in different outputs. That seems wrong.

### Reproducible example

```python
import polars as pl

lf = pl.scan_parquet('/tmp/testdata.parquet')
keys = ['ipAddress', 'oif']

df1 = (
   lf.sort('timestamp')
     .unique(subset=keys, keep='last')
     .filter(pl.col('active'))
     .collect()
     .filter(pl.col('ipAddress') == "172.16.3.110")
)

df2 = (
   lf.sort('timestamp')
     .unique(subset=keys, keep='last')
     .collect()
     .filter(pl.col('active'))
     .filter(pl.col('ipAddress') == "172.16.3.110")
)
```

### Expected behavior

df1 and df2 in the snippet above should be identical.

### Installed versions

<details>

```
In [20]: pl.show_versions()
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
Python: 3.8.13 (default, May  1 2022, 04:34:39) 
[GCC 11.2.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
[testdata.parquet.gz](https://github.com/pola-rs/polars/files/11056478/testdata.parquet.gz)

```

</details>

**Comment by ddutt** [comment]
FYI, its not obvious for a non-maintainer, but i've attached the testdata.parquet file

**Comment by cmdlineluser** [comment]
The link to the file is inside the `<details>` which make it hard to see - you may want to edit the formatting:

https://github.com/pola-rs/polars/files/11056478/testdata.parquet.gz

**Comment by Firaenix** [comment]
I believe I have also run into this issue, as some of my previously working code in production seems to have completely broken based on where a .select(count()) is placed in the query chain.
If this is due to a change in how the query planner executes or optimises, this should be a major version bump. The change is very subtle.

I was forced to change
```rust
let df = match data
            .clone()
            .lazy()
            .select([count()])
            .filter(col("node_id").eq(lit(node_id.clone())))
            .collect()
        {
            Ok(v) => v,
            Err(e) => {
                error!(
                    "Error getting node_id {node_id} in does_node_exist: {}\n{data:#?}",
                    e
                );
                return Err(DataShardErrors::DataFrameError(e.to_string()));
            }
        };
```
to the following
```rust
```rust
let df = match data
            .clone()
            .lazy()
            .filter(col("node_id").eq(lit(node_id.clone())))
            .select([count()])
            .collect()
        {
            Ok(v) => v,
            Err(e) => {
                error!(
                    "Error getting node_id {node_id} in does_node_exist: {}\n{data:#?}",
                    e
                );
                return Err(DataShardErrors::DataFrameError(e.to_string()));
            }
        };
```
```

**Comment by alexander-beedie** [comment]
@ritchie46: minimal repro - the `filter` shouldn't be pushed down past the `unique` subset.
```python
lf = pl.LazyFrame({
    "x": ["abc", "abc"],
    "y": ["xxx", "xxx"],
    "z": [ True, False],
})

lf.unique(subset=["x","y"], maintain_order=True, keep="last").filter(pl.col("z")).collect()
# ┌─────┬─────┬──────┐
# │ x   ┆ y   ┆ z    │
# │ --- ┆ --- ┆ ---  │
# │ str ┆ str ┆ bool │
# ╞═════╪═════╪══════╡
# │ abc ┆ xxx ┆ true │  
# └─────┴─────┴──────┘

lf.unique(subset=["x","y"], maintain_order=True, keep="last").collect().filter(pl.col("z"))
# ┌─────┬─────┬──────┐
# │ x   ┆ y   ┆ z    │
# │ --- ┆ --- ┆ ---  │
# │ str ┆ str ┆ bool │
# ╞═════╪═════╪══════╡  << expected
# └─────┴─────┴──────┘
```
The expected value is the second (empty) frame, as the unique subset results in one row (with z=False) which the filter then knocks out. If the filter is pushed down through the unique subset, we knock out what _would_ have been the "last" row in the group, changing the result.

**Comment by ritchie46** [comment]
Thanks for finding the cause @alexander-beedie. Will fix it.

@ddut thank for the issue report.

@Firaenix the optimizer is not allowed to change the query result. If you encounter such a thing please open an issue. :)
