### ISSUE TITLE
Fails to read JSON while Pandas succeeds

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#775]
#### Are you using Python or Rust?
Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

'0.8.3'

#### What operating system are you using polars on?
Fedora

#### Describe your bug.
Cannot read JSON: 
[locations.txt](https://github.com/pola-rs/polars/files/6631650/locations.txt)
```

 loc_path = Path('/home/torstein/code/fintechdb/Jobs/glassdoor/locations.json')
polars.read_json(loc_path)
AttributeError: 'Path' object has no attribute 'read'
polars.read_json(str(loc_path))
RuntimeError: Other("Error(\"expected value\", line: 1, column: 1)")

```

Works with pandas. json is attached

**Comment by ritchie46** [comment]
Polars has a very opinionated json dialect. For the time being you could use pandas'

`pl.from_pandas(pd.read_json("locations.txt"))`
