### ISSUE TITLE
Allow use of regex in `df.drop()`

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#7753]
### Problem description

We can use regex in df.select() to select columns by regular expressions. This doesn't work in in drop.

```
import polars as pl
df = pl.DataFrame({"a":[1,2,3,], "column__1":None})
df.select(r"^col\w+$") # works
df.drop(r"^col\w+$") # error
```

**Comment by tikkanz** [comment]
I think this is a regression as it used to work, at least back in version 0.14.11 from memory.

**Comment by stinodego** [comment]
I'll look into this - if it's a regression it's probably my fault.

**Comment by cmdlineluser** [comment]
This doesn't seem to error anymore but the string appears to be parsed as a literal:
```python
df.drop("^col\w+$")

# shape: (3, 2)
# ┌─────┬───────────┐
# │ a   ┆ column__1 │
# │ --- ┆ ---       │
# │ i64 ┆ f32       │
# ╞═════╪═══════════╡
# │ 1   ┆ null      │
# │ 2   ┆ null      │
# │ 3   ┆ null      │
# └─────┴───────────┘
```
Passing a selector works:
```python
df.drop(cs.matches("^col\w+$"))

# shape: (3, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# │ 3   │
# └─────┘
```

**Comment by tzeitim** [comment]
Just commenting that the support for regular expressions is missed here, are there plans to get them back? I find it a bit cumbersome so add an additional import for the selectors. 

Thanks for the suggestion, @avimallu

**Comment by JRoper18** [comment]
damn, is this still a bug? Documentation says we can use regex but I also am still experiencing this on v1.0.0

**Comment by thomasaarholt** [comment]
@JRoper18 i believe you can use the `matches` selector: https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.matches

Can you confirm? If so, I'll close this.

**Comment by cmdlineluser** [comment]
`pl.col` also works.

```python
>>> df.drop(pl.col(r"^col\w+$"))
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
└─────
```

**Comment by deanm0000** [comment]
@cmdlineluser what version are you on? I'm on 1.4.0 and that doesn't work for me.

I can do 

```
df.select(cs.matches(r"^col\w+$"))
df.select(pl.col(r"^col\w+$"))
```

but neither
```
df.drop(cs.matches("^col\w+$"))
df.drop(pl.col(r"^col\w+$"))
```
work for me.

**Comment by cmdlineluser** [comment]
@deanm0000 1.4.1 

Although it seems `df.drop(r"^col\w+$")` also works again in 1.4.1 - not sure what changed exactly.

**Comment by deanm0000** [comment]
alright I just upgraded to 1.4.1 and I confirm it works.
