### ISSUE TITLE
Conditional aggregate with when-then over an empty dataframe fails with dtype expectation error

### ISSUE THREAD

**Issue by vdksoda** [pola-rs/polars#7755]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Seems `pl.col('m_id').count() > 3` section of code in the aggregate is not working as expected when the dataframe is empty. It fails with an error. This issue exists in versions 0.16.9+

```
exceptions.SchemaError: invalid series dtype: expected `Boolean`, got `u32`
```

However on Polars version 0.16.8 this works fine. See the "Expected behavior" section

### Reproducible example

```python
import polars as pl

print(pl.show_versions())

schema_1 = {'id': pl.Int64, 'p_id': pl.Int32, 'm_id': pl.Int32}

ldf_1 = pl.DataFrame(
    {"id": [1,1,2,2,3,3], "p_id": [4,4,5,5,6,6], "m_id": [7,7, 8,8,9,9]},
    schema={'id': pl.Int64, 'p_id': pl.Int32, 'm_id': pl.Float64}
)

print(
    ldf_1
    .filter((pl.col('id') > 4))
    .groupby(pl.col("id"))
    .agg([
        pl.when(pl.col('m_id').count() > 3).then(pl.col("m_id").median()).otherwise(None)
    ])
)

# Error Output (full file paths are masked) #
"""
Traceback (most recent call last):
  File ".../random_polars_issue.py", line 11, in <module>
    ldf_1
  File ".../python3.9/site-packages/polars/dataframe/groupby.py", line 232, in agg
    self.df.lazy()
  File ".../python3.9/site-packages/polars/lazyframe/frame.py", line 1443, in collect
    return pli.wrap_df(ldf.collect())
exceptions.SchemaError: invalid series dtype: expected `Boolean`, got `u32`

Process finished with exit code 1

"""
```

### Expected behavior

Running the same code as in "Reproducible example" on version 0.16.8 results in 

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: macOS-13.2.1-arm64-arm-64bit
Python: 3.9.13 (main, Oct 13 2022, 16:12:19) 
[Clang 12.0.0 ]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: 2023.3.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
None
shape: (0, 2)
┌─────┬──────┐
│ id  ┆ m_id │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
└─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-13.2.1-arm64-arm-64bit
Python: 3.9.13 (main, Oct 13 2022, 16:12:19) 
[Clang 12.0.0 ]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 8.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by mcrumiller** [comment]
A potential problem is that both `count` and `median` return a row, even when called on any empty column:

```python
df = pl.DataFrame({'a': []})
df.select([
    pl.count('a').alias("count"),
    pl.median('a').alias("median")
])
```
```
shape: (1, 2)
┌───────┬────────┐
│ count ┆ median │
│ ---   ┆ ---    │
│ u32   ┆ f32    │
╞═══════╪════════╡
│ 0     ┆ null   │
└───────┴────────┘
```
I'm not familiar with conditional aggregation (is this new?).

**Comment by vdksoda** [comment]
> A potential problem is that both `count` and `median` return a row, even when called on any empty column:
> 
> ```python
> df = pl.DataFrame({'a': []})
> df.select([
>     pl.count('a').alias("count"),
>     pl.median('a').alias("median")
> ])
> ```
> 
> ```
> shape: (1, 2)
> ┌───────┬────────┐
> │ count ┆ median │
> │ ---   ┆ ---    │
> │ u32   ┆ f32    │
> ╞═══════╪════════╡
> │ 0     ┆ null   │
> └───────┴────────┘
> ```
> 
> I'm not familiar with conditional aggregation (is this new?).

I do not see this as an issue. In my sample code I'm relying on the (your) highlighted behaviour for the when-then to work. However there seems to be some issue which is preventing the expression to evaluate per below steps in this particular group-by formulation.
```
pl.col('m_id').count() > 3
evaluates(1) => 0 > 3
evaluates => false
``` 

Referencing 1, at this stage it is not producing 0 but producing *some value* (most likely None) who's comparison operator fails and produces a non boolean value. If I had to guess it would be the null value with dtype UInt32.

> I'm not familiar with conditional aggregation (is this new?).

Its just a name I gave the use of the when-then within the `agg` expression. I think it is standard in SQL (Postgres for example), for example
```
select 
   date,
   sum(case when value > 3 then value else null end) as sum_values_gt_3
from some_table
group by date
```
However where it deviates from Polars, in my view, is SQL forces the user to write code within the `sum` in the context of what is available in the table *then*. If I had to craft the Polars from my code in SQL it would look like

```
with base as (
    select 
       date,
       count(*) as number_of_entries,
       sum(values) as _sum_values
    from some_table
    group by date
)
select
    case when number_of_entries > 3 then _sum_values else null end as sum_values
from base
```
While Polars it seems to understanding the compute context and compacting these two distinct query steps into one step of user code. Or else I have the wrong expectation from Polars here.

**Comment by henryharbeck** [comment]
@vdksoda, running your example does not produce an error in the current version of polars.

To hopefully help out a bit with what you are doing, you can use `pl.col(...).filter()` in `agg` to control which values get passed to the aggregate functions. Some examples with data similar to your example below.

```python
df = pl.DataFrame(
    {
        "id": [1, 2, 2, 2, 3, 3],
        "m_id": [7, 10, 12, 14, 8, 9],
    },
    schema={"id": pl.Int64, "m_id": pl.Float64},
)

(
    df.group_by(pl.col("id"), maintain_order=True).agg(
        pl.len().alias("elements_in_group"),
        pl.col("m_id").alias("m_ids"),
        pl.col("m_id").filter(pl.len() > 1).median().alias("median_groups_gt_1"),
        pl.col("m_id").filter(pl.len() > 2).sum().alias("sum_groups_gt_2"),
        pl.col("m_id").filter(pl.col("m_id") > 8).sum().alias("sum_values_gt_8"),
    )
)
# shape: (3, 6)
# ┌─────┬───────────────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┐
# │ id  ┆ elements_in_group ┆ m_ids              ┆ median_groups_gt_1 ┆ sum_groups_gt_2 ┆ sum_values_gt_8 │
# │ --- ┆ ---               ┆ ---                ┆ ---                ┆ ---             ┆ ---             │
# │ i64 ┆ u32               ┆ list[f64]          ┆ f64                ┆ f64             ┆ f64             │
# ╞═════╪═══════════════════╪════════════════════╪════════════════════╪═════════════════╪═════════════════╡
# │ 1   ┆ 1                 ┆ [7.0]              ┆ null               ┆ 0.0             ┆ 0.0             │
# │ 2   ┆ 3                 ┆ [10.0, 12.0, 14.0] ┆ 12.0               ┆ 36.0            ┆ 36.0            │
# │ 3   ┆ 2                 ┆ [8.0, 9.0]         ┆ 8.5                ┆ 0.0             ┆ 9.0             │
# └─────┴───────────────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┘
```

I think this issue can now be closed.

**Comment by stinodego** [comment]
@henryharbeck feel free to tag me if you find an issue that can be closed, and I'll close it!
