### ISSUE TITLE
Groupby aggregation with struct column fails

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#7763]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Aggregating a struct column fails if the struct contains multiple `search_sorted` expressions:

```python
import polars as pl

struct_expr = pl.struct(
    [
        pl.col("A").search_sorted(pl.Series([1, 2])),
        pl.col("B").search_sorted(pl.Series([3, 4])),
    ]
).alias("index")

pl.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C": [1, 2, 2]}).groupby(
    "C"
).agg(struct_expr)
```
raises
```python
DuplicateError: multiple fields with name '' found
```

This seems specific to having multiple `search_sorted` expressions; I haven't been able to replicate the error for other expressions.

### Reproducible example

```python
import polars as pl

struct_expr = pl.struct(
    [
        pl.col("A").search_sorted(pl.Series([1, 2])),
        pl.col("B").search_sorted(pl.Series([3, 4])),
    ]
).alias("index")

pl.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C": [1, 2, 2]}).groupby(
    "C"
).agg(struct_expr)
```

### Expected behavior

The aggregation should function with `search_sorted` expressions.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.10.9 (main, Feb 12 2023, 18:51:31) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
The fix may be similar to #7286

`.arg_sort()` was the only other one I could get to raise the same error.
