### ISSUE TITLE
mode() on categorical series returns null instead of mode

### ISSUE THREAD

**Issue by pietz** [pola-rs/polars#7772]
### Polars version checks

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

- [X] I have checked that this issue has not already been reported.

### Issue description

Calling `Series.mode()` on a series of dtype `pl.Categorical` returns `null` when I would expect it to return the actual mode.

### Reproducible example

```python
import polars as pl
pl.Series(["foo", "bar", "buz", "bar"], dtype=pl.Categorical).mode()
```

### Expected behavior

Return a one element series containing "bar".

### Installed versions

<details>
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.9.9 (main, Jan  3 2022, 01:07:08) 
[Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2021.11.1
matplotlib: 3.5.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
</details>

**Comment by zundertj** [comment]
Note that it now returns a series, you would expect a string:

```python
>>> pl.Series(["foo", "bar", "buz", "bar"], dtype=pl.Categorical).mode()
shape: (1,)
Series: '' [cat]
[
        null
]
```

Other statistical aggregations:

```python
pl.Series(["foo", "bar", "buz", "bar"], dtype=pl.Categorical).min()
```
returns None.


Relevant issue here: #1401

**Comment by ritchie46** [comment]
We don't support mode on categoricals as the order is undefined. Now that we have added lexical ordering, we could explore supporting it.

**Comment by pietz** [comment]
I don't understand how the order is related to the mode() operation. That's said, it's not a bug that's holding me back at the moment. I just wanted to document it here since the current behavior looks broken to me.

Treat the issue as you like :)
