### ISSUE TITLE
Loading via picke module not working since 0.16.14+

### ISSUE THREAD

**Issue by julio-34727** [pola-rs/polars#7773]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Loads dataframe via pickle module raise ModuleNotFoundError (polars 0.16.14+).

### Reproducible example

```python
import pickle
import polars as pl
pickle.load(open("df_likers_pl.pkl", "rb"))


ModuleNotFoundError: No module named 'polars.internals.dataframe'; 'polars.internals' is not a package
```

### Expected behavior

It works.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.15
Index type: UInt32
Platform: macOS-13.2.1-x86_64-i386-64bit
Python: 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: 3.0.9
```

</details>

**Comment by ghuls** [comment]
If you create a new pickle file on the new version it will likely work. The polars module internal organisation changed, so old pickle files will not work with the latest versions. This also happens if you have a class that you pickle and try to open it later with a newer version of your class.

**Comment by marsupialtail** [comment]
I encounter same problem :-) It might be worth pinning down some APIs since I think Polars should be considered quite stable now. Just my 2 cents

**Comment by ritchie46** [comment]
Pickle stability is something we can never guarantee between versions. Pickle is dependent of module structure. Even of private modules.

**Comment by alexander-beedie** [comment]
> Pickle stability is something we can never guarantee between versions. Pickle is dependent of module structure. Even of private modules.

How about we override DataFrame pickling to just store/load binary IPC data? (Which isn't difficult to do). Then we're insulated against misuse of pickle to store data (and we get waaaaaay better performance).

**Comment by ritchie46** [comment]
> > Pickle stability is something we can never guarantee between versions. Pickle is dependent of module structure. Even of private modules.
> 
> How about we override DataFrame pickling and have it store/load binary IPC data instead? (Which shouldn't be difficult to do). Then we're insulated against misuse of pickle to store data (and we get waaaaaay better performance.

Right! That's a good idea. One question. Do we currently support objects in pickle? If not, let's go for IPC immediately.

**Comment by ghuls** [comment]
> > > Pickle stability is something we can never guarantee between versions. Pickle is dependent of module structure. Even of private modules.
> > 
> > 
> > How about we override DataFrame pickling and have it store/load binary IPC data instead? (Which shouldn't be difficult to do). Then we're insulated against misuse of pickle to store data (and we get waaaaaay better performance.
> 
> Right! That's a good idea. One question. Do we currently support objects in pickle? If not, let's go for IPC immediately.

Objects are currently not supported.

I think, currently we also don't make use of PickleBuffer support in the Pickle version 5 protocol:
https://peps.python.org/pep-0574/
