### ISSUE TITLE
Dataframe.describe reports incorrect column dtype

### ISSUE THREAD

**Issue by Timur-P** [pola-rs/polars#7778]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Create a new Dataframe out of an existing Dataframe using with_columns and cast expression. Calling Dataframe.describe reports 'old' dtype. At the same time, Dataframe.head reports correct dtype.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "a": [1.0, 2.8, 3.0]
    })
print(df.describe())
    
mdf = df.with_columns(pl.col("a").cast(pl.Float32))
print(mdf.describe())
print(mdf.head(1))
```

### Expected behavior

Describe should report f32, not f64

### Installed versions

<details>

```
---Version info---
Polars: 0.16.15
Index type: UInt32
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
@zundertj could you take this one?

**Comment by zundertj** [comment]
`descripe` does not return the dtype, the `f64` you are seeing is the data types of the description:

```python
>>> print(mdf.describe())
shape: (7, 2)
┌────────────┬──────────┐
│ describe   ┆ a        │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 3.0      │
│ null_count ┆ 0.0      │
│ mean       ┆ 2.266667 │
│ std        ┆ 1.101514 │
│ min        ┆ 1.0      │
│ max        ┆ 3.0      │
│ median     ┆ 2.8      │
└────────────┴──────────┘
```

The columns will always be either float64 or string. For example, for dates, it returns everything as string (including the count), as columns can be just a single type.

So I consider this not a bug.
