### ISSUE TITLE
Convenience for mapping with dictionaries

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#778]
In pandas, we can do `pd.Series(['a', 'b']).map({'a':1, 'c':2})` which equals a Series of `['1', pd.NA]`. It is convenient instead of writing lambdas with dict.get(s, pd.NA). Very often, Series are remapped with a dictionary

**Comment by YuRiTan** [comment]
Hi tsoernes, 

I think it would be nice to make your use case more generic, something like:

```
def replace_values(s: pl.Series, mapping: Dict[Any, Any]) -> pl.Series:
    return s.apply(lambda x: mapping.get(x, None))

s = pl.Series(['a', 'b'])
s.apply(replace_values, mapping={'a':1, 'c':2})
```

For now, this is not possible since the current `.apply()` method doesn't allow `kwargs` to be passed to the function you want to apply on the series. Maybe a nice feature to add?

**Comment by ritchie46** [comment]
I am closing this, as it seems that python provides enough flexibility to deal with this.
