### ISSUE TITLE
Stricter pivot - no aggregation by default?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7780]
### Problem description

Currently, [DataFrame.pivot](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.pivot.html) defaults to aggregating by 'first'. This could come as a surprise:
- coming from Excel, which defaults to aggregating by 'sum'
- coming from `pandas.pivot`, which errors if there are multiple values with the same (index, columns)
- coming from `pandas.pivot_table`, which aggregates by `'mean'` by default
- coming from R, which aggregates into a list

To minimises surprises, I'd suggest that the default `aggregate_function` be `None`, which would error if there are multiple values with the same (index, columns)

This could be done either as:
- a breaking change
- with a deprecation cycle, by setting the default `aggregation_function` to some internal class `NoDefault` and emitting a `DeprecationWarning` if the user doesn't explicitly pass a value, telling them the default will change from `'first'` to `None`

Happy to submit a PR if this would be welcome

**Comment by ritchie46** [comment]
Seems reasonable to make it a required argument. Let's make it a deprecation next release. I want to go to 0.17 soon (in a week or two) so then we can break it.
