### ISSUE TITLE
Polars Python not able to read multiple files on azure datalake/storage account

### ISSUE THREAD

**Issue by kamakay** [pola-rs/polars#7785]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading multiple parquet files from Azure Datalake using "wildchar" character I am onlye able to read the first parquet file.

I have uploaded 5 parquet files with 3 rows for dataframe
my_many_files_1.parquet
...
my_many_files_5.parquet
to my datalake account with name "XXX" and container/namespace "YYY" in a folder called "TEST"

### Reproducible example

```python
import polars as pl

# Create sample data
df = pl.DataFrame({"foo": [1, 2, 3], "bar": [None, "ham", "spam"]})
for i in range(5):
    df.write_parquet(f"/mnt/c/Temp/my_many_files_{i}.parquet")

# Copy 5 above parquet data to account XXX into YYY/test folder
az cli something ....

# Try to read 
import polars as pl

path = "abfs://YYY/test/my_many_files_*.parquet"
storage_options = {'account_name': 'XXX', 'anon': False }
df = pl.scan_parquet(path, storage_options=storage_options)

df.collect().head(100)

# Result
shape: (3, 2)
┌─────┬──────┐
│ foo ┆ bar  │
│ --- ┆ ---  │
│ i64 ┆ str  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ ham  │
│ 3   ┆ spam │
└─────┴──────┘
```

### Expected behavior

I would like to obtain a data frame that contains the union of 5 dataframe .

```python
shape: (15, 2)
┌─────┬──────┐
│ foo ┆ bar  │
│ --- ┆ ---  │
│ i64 ┆ str  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ ham  │
│ 3   ┆ spam │
│ 1   ┆ null │
│ …   ┆ …    │
│ 3   ┆ spam │
│ 1   ┆ null │
│ 2   ┆ ham  │
│ 3   ┆ spam │
└─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: <version not detected>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ritchie46** [comment]
Could you run with `RUST_BACKTRACE=1` and show the panic backtrace? This is hard for met to reproduce as I don't have azure.

**Comment by kamakay** [comment]
Ihi @ritchie46 python does not hangs but provide me the wrong number of lines, it seems it is able to read only the first file found within azure datalake. Are you able to process if using S3 for instance ?

**Comment by kamakay** [comment]
any suggestion or feedback/experience on this topic ?

**Comment by kamakay** [comment]
After many tentative I am still in the same situation, any suggestion ?

**Comment by ritchie46** [comment]
This isn't yet supported like this. You can use scan_pyarrow_dataset in the meantime

**Comment by kamakay** [comment]
mm I think something is broken also on this path... any suggestion ?

`Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?ddbad295-6cc9-415e-8485-defa08b1f078)---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[36], line 2
      1 import polars as pl
----> 2 pl.scan_pyarrow_dataset(dataset_public)

File [~/miniconda3/envs/polarsazure/lib/python3.10/site-packages/polars/io/pyarrow_dataset/functions.py:56](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Code/~/miniconda3/envs/polarsazure/lib/python3.10/site-packages/polars/io/pyarrow_dataset/functions.py:56), in scan_pyarrow_dataset(source, allow_pyarrow_filter)
     14 def scan_pyarrow_dataset(
     15     source: pa.dataset.Dataset, *, allow_pyarrow_filter: bool = True
     16 ) -> LazyFrame:
     17     """
     18     Scan a pyarrow dataset.
     19 
   (...)
     54 
     55     """
---> 56     return _scan_pyarrow_dataset(source, allow_pyarrow_filter=allow_pyarrow_filter)

File [~/miniconda3/envs/polarsazure/lib/python3.10/site-packages/polars/io/pyarrow_dataset/anonymous_scan.py:36](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Code/~/miniconda3/envs/polarsazure/lib/python3.10/site-packages/polars/io/pyarrow_dataset/anonymous_scan.py:36), in _scan_pyarrow_dataset(ds, allow_pyarrow_filter)
     19 """
     20 Pickle the partially applied function `_scan_pyarrow_dataset_impl`.
     21 
   (...)
     33 
     34 """
...
     37 return pli.LazyFrame._scan_python_function(
     38     ds.schema, func_serialized, allow_pyarrow_filter
     39 )

TypeError: cannot pickle '_thread.RLock' object`

**Comment by kamakay** [comment]
hi @ritchie46 any suggestion on the topic ? 

It wuold be really helpfull if we can read many different parquet files specifyng wildcard chars.

**Comment by aaravind100** [comment]
I'm having a similar problem when reading 1000's of small parquet files in nested directories from azure datalake gen2 (the directories are nested like yyyy/mm/dd/xxx.parquet). I was using dask earlier to read them with `dd.read_parquet("abfs://mycontainer/some_path/*/*/*/*.parquet)`. 

Polars behaves quite strange when using `pl.scan_parquet("abfs://mycontainer/some_path/*/*/*/*.parquet)`, it waits a substantial amount of time and return the data for the first file.

Narrowed the problem to this section in [py-polars.polars.io._utils._prepare_file_arg](https://github.com/pola-rs/polars/blob/51111752066b4ef34e117e9d63a409e530fd347e/py-polars/polars/io/_utils.py#L148C29-L148C29). 
[fsspec.open](https://github.com/fsspec/filesystem_spec/blob/348d4ab5794de3b06d9899c1fc2fd2b418fe9109/fsspec/core.py#L452C18-L452C18) seem to return the output for the first item, this may not be the right method to use when the url path contains glob pattern.

A workaround would be do something like this,
```py
import adlfs  # <-- azure data lake fs (https://github.com/fsspec/adlfs)
import polars as pl

storage_options = {
    "account_name": "<account_name>",
    # ...
}
az_fpath = "mycontainer/some_path/*/*/*/*.parquet"

fs = adlfs.AzureBlobFileSystem(**storage_options)

files = [f"abfs://{f}" for f in fs.glob(az_fpath)]

df = pl.concat([pl.scan_parquet(f, storage_options=storage_options) for f in files])

print(df.collect().shape)
```

There can be quite a bit of speed up when there are 100s or 1000s of files with this pattern instead of the for loop,
```py
from concurrent.futures import ThreadPoolExecutor as Executor
from functools import partial

with Executor() as executor:
    df = pl.concat(
        list(
            executor.map(
                partial(pl.scan_parquet, storage_options=storage_options), files
            )
        )
    )
```

**Comment by ritchie46** [comment]
This is fixed now.

**Comment by kamakay** [comment]
thanks!
