### ISSUE TITLE
Series.map_dict changes dtype Int32->Int64 and Float32->Float64

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#7788]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`map_dict` changes `dtype` even if the new value is in range of the existing `dtype`.

### Reproducible example

```python
import polars as pl

print(pl.Series([1], dtype=pl.Int32)  .map_dict({1: 2}, default=pl.first()).dtype)
print(pl.Series([1], dtype=pl.Float32).map_dict({1: 2}, default=pl.first()).dtype)
```

Outputs:

```
Int64
Float64
```

### Expected behavior

Existing `dtype` is kept if possible

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by zundertj** [comment]
I think this is not possible to support properly. For example:

```python
print(pl.Series([1], dtype=pl.Int32)  .map_dict({1: 2}, default=pl.first()).dtype)
```
Right now returns Int64. You suggest it to return Int32. But what if we have:

```python
print(pl.Series([1], dtype=pl.Int32)  .map_dict({1: <integer out of range for Int32>}, default=pl.first()).dtype)
```
Then you would want Int64.

This would mean that the value, not the type, of the dict would determine whether there would be a cast. As far as I know we do not support, or want to support, that.  @ritchie46  can probably confirm.

**Comment by 2-5** [comment]
But why can't polars first scan the dict to determine the required `dtype`? It's not on the critical path, there should be minimal speed impact.

As a suggestion, I'm only using `map_dict` because Polars is lacking a `replace(value, replace_with)` call.

**Comment by zundertj** [comment]
If it is on a Dataframe, I would use [pl.when](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.when.html#polars.when) for that. For a Series, I don't think there is a better alternative, if you happen to have the indices, `Series.set_at_idx`?

**Comment by ghuls** [comment]
I am working on it, so that it will work at least in most cases.

**Comment by ritchie46** [comment]
> 

That should be done with a when then otherwise.

**Comment by ritchie46** [comment]
> As far as I know we do not support, or want to support, that. @ritchie46 can probably confirm.

Indeed. Dtypes are determined by operations, not by the data.

**Comment by 2-5** [comment]
> Dtypes are determined by operations, not by the data.

There seem to be a few exceptions:

```python
df = pl.DataFrame({"a": [1, 2, 3]})  # i64
df.with_columns(pl.col("a") + 1)     # i64
df.with_columns(pl.col("a") + 1.0)   # f64
```

Or maybe it can be interpreted as "+1=add_int_op" and "+1.0->add_float_op"

**Comment by 2-5** [comment]
> > s a suggestion, I'm only using map_dict because Polars is lacking a replace(value, replace_with) call.
> 
> That should be done with a when then otherwise.

Ok, I'll do that. `pl.when` is just so verbose. Allowing a default `otherwise` which just keeps the existing value would be such a DX improvement, 75% of my usage of `pl.when` does that. The same with `keep_name`:

```python
pl.when(pl.col("a") == -1).then(None).otherwise(pl.col("a")).keep_name()
# WOULD BECOME
pl.when(pl.col("a") == -1).then(None)
```

**Comment by cmdlineluser** [comment]
You can invert the condition:
```
pl.when(pl.col("a") != -1).then(pl.col("a"))
```

**Comment by 2-5** [comment]
That doesn't work, set's to `None` the `otherwise`, and loses the name (creates new column):

```python
pl.DataFrame({
    "a": range(5),
}).with_columns([
    pl.when(pl.col("a") > 2).then(0),
])
```

Output:

```
shape: (5, 2)
┌─────┬─────────┐
│ a   ┆ literal │
│ --- ┆ ---     │
│ i64 ┆ i32     │
╞═════╪═════════╡
│ 0   ┆ null    │
│ 1   ┆ null    │
│ 2   ┆ null    │
│ 3   ┆ 0       │
│ 4   ┆ 0       │
└─────┴─────────┘
```

**Comment by ghuls** [comment]
It is fixed now in https://github.com/pola-rs/polars/pull/7797 :

```python
In [21]: print(pl.Series([1], dtype=pl.Int32)  .map_dict({1: 2}, default=pl.first()).dtype)
    ...: print(pl.Series([1], dtype=pl.Float32).map_dict({1: 2}, default=pl.first()).dtype)
Int32
Float32
```

**Comment by 2-5** [comment]
@zundertj Interesting, I wasn't aware extending the API is supported for users, I thought it was for internal use. There should be a chapter about this in the Polars Book.

Regarding `replace`, it's still too verbose. I would modify it like below, to just allow literals and not expressions:

```python
df.with_columns(pl.col("a").rep.replace(6, 9))
```

**Comment by zundertj** [comment]
It is in the reference guide: [https://pola-rs.github.io/polars/py-polars/html/reference/api.html](https://pola-rs.github.io/polars/py-polars/html/reference/api.html)

You can modify my code easily to get what you want? That is the beauty of being able to define your methods.
