### ISSUE TITLE
[Feature Request] equivalent to pandas' `duplicated`

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#780]
.. which returns a boolean series indicating whether the row is duplicated or not

**Comment by ritchie46** [comment]
Have you checked the reference guide?

https://pola-rs.github.io/polars-book/api-python/polars/series/Series.html#polarsseriesseriesis_duplicated

**Comment by tsoernes** [comment]
That only works on Series, not on DataFrames, where you check multiple columns at once

**Comment by ritchie46** [comment]
> Note the change from duplicated to is_duplicated

Yes. We are not pandas😉
