### ISSUE TITLE
Polars calculation involving max is slower than expected in groupby_rolling context

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#7805]
### Problem description

Below are some of my benchmarking results.

Setting up
```
import time
import numpy as np
import polars as pl

n_index = 100
n_group1 = 10
n_group2 = 1000
n_obs = 10000000

df = pl.DataFrame(
    {
        "index": np.random.randint(0, n_index, size=n_obs),
        "group1": np.random.randint(0, n_group1, size=n_obs),
        "group2": np.random.randint(0, n_group2, size=n_obs),
        "value": np.random.normal(0, 1, n_obs),
    }
).sort("index")
```

Experiment 1: takes around 2s
```
start = time.perf_counter()
df.groupby_rolling(
    index_column="index", period="10i", closed="right", by=["group1", "group2"]
).agg((pl.col("value") * pl.col("index")).sum())
time.perf_counter() - start
```

Experiment 2: takes around 100s
```
start = time.perf_counter()
df.groupby_rolling(
    index_column="index", period="10i", closed="right", by=["group1", "group2"]
).agg((pl.col("value") * (pl.max("index") - pl.col("index"))).sum())
time.perf_counter() - start
```

Introducing max() in the calculation causes very slow calculation by comparing the time spent between experiment 1 with 2.

However, experiment 3 (which is equivalent to experiment 2 result-wise) below runs fast in the same level as experiment 1.

Experiment 3: takes around 3s
```
start = time.perf_counter()
df.groupby_rolling(
    index_column="index", period="10i", closed="right", by=["group1", "group2"]
).agg(pl.col("value").sum() * pl.max("index") - (pl.col("value") * pl.col("index")).sum())
time.perf_counter() - start
```

Is this behavior (slowness) expected?

In this case, experiment 2 can be converted to experiment 3 with fast speed. But what if ```pl.max("index") - pl.col("index")``` cannot be spitted and distributed over, for example, calculating something like ```(pl.col("value") * 2 ** (pl.max("index") - pl.col("index"))).sum()```? I agree it is a more expansive operation than just multiply and sum, but is 30-50x slower as expected?

**Comment by paladin158** [comment]
> This title is a bit misleading. You do a `(value * (max(index) - index)).sum()`. Which is much more complicated than `value * sum(index)`.
> 
> In fact, I can run `value * max(index)` in around the same speed as `value * sum(index)`.
> 
> Though we can explore if we can vectorize the more complicated expression as well.

Got it. Thanks! Updated original post. Basically, is there any room to optimize something like ```(pl.col("value") * 2 ** (pl.max("index") - pl.col("index"))).sum()``` in groupby context? Because in this case, we cannot really apply distribution rule as it may be subject to overflow.

**Comment by stinodego** [comment]
There seems to be some room for further optimizations here, but without a very clear path forward I don't think this warrants an open issue currently. 

I'll close this as 'not planned' for now.
