### ISSUE TITLE
GroupBy.count does not return any counts

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#781]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

Replace this text with the version.

#### What operating system are you using polars on?

Replace this text with your operating system and version.

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

Given a dataframe with duplicates:
```
In [175]: len(df)
Out[175]: 251835

In [163]: len(df.drop_duplicates())
Out[174]: 62242
```
I want to know the number of duplicate entries, for each unique row.

I'm trying this:
```
counts = df.groupby(df.columns).count()
```
But `counts` is just a deduplicated version of `df`. It has no extra column, with the count:
```

In [202]: len(counts)
Out[204]: 62242

In [183]: counts.columns == df.columns
Out[193]: True


In [196]: polars.__version__
Out[201]: '0.8.3'

```

I'm attempting to mimick this pandas behaviour:
```
counts = df.groupby(
    df.columns.tolist(), as_index=False
).size()

```

**Comment by ritchie46** [comment]
Count should be marked as deprecated.

You should use the expression syntax:

```

 df
    .groupby("first_name")
    .agg([pl.count("party"), pl.col("gender").list(), pl.first("last_name")])
   
```

I'd suggest reading the expression chapter of the user guide.

The idiomatic polars API is quite different from pandas.

https://pola-rs.github.io/polars-book/user-guide/dsl/intro.html

**Comment by tsoernes** [comment]
@ritchie46 I suppose I can make this into a Feature Request for `DataFrame.value_counts`, which is what I have attempted to do above

**Comment by ritchie46** [comment]
Again, have you tried the reference guide?

https://pola-rs.github.io/polars-book/api-python/polars/series/Series.html?highlight=value_counts#polarsseriesseriesvalue_counts

**Comment by tsoernes** [comment]
That does not apply to DataFrames. I want the duplicate count for every unique row across all columns

**Comment by tsoernes** [comment]
Since I have only string columns, I can do `counts = df.apply('|'.join).value_counts()`, but there is no way to separate the strings back into individual columns again

**Comment by ritchie46** [comment]
> That does not apply to DataFrames. I want the duplicate count for every unique row across all columns

Every column potentially has a different number of unique values, so you cannot store the result into one dataframe. How would you do that in pandas?

**Comment by tsoernes** [comment]
> > That does not apply to DataFrames. I want the duplicate count for every unique row across all columns
> 
> Every column potentially has a different number of unique values, so you cannot store the result into one dataframe. How would you do that in pandas?

Simply `counts = df.groupby(df.columns.tolist(), as_index=False).size()`

**Comment by ritchie46** [comment]
Then you can do the same:

```python
df = pl.DataFrame({
    "a": [1, 2, 3, 1],
    "b": [1, 2, 1, 1]
})

(df.groupby(df.columns)
    .agg(pl.count("a").alias("count")))

```

```
shape: (3, 3)
╭─────┬─────┬───────╮
│ a   ┆ b   ┆ count │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ u32   │
╞═════╪═════╪═══════╡
│ 1   ┆ 1   ┆ 2     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3   ┆ 1   ┆ 1     │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2   ┆ 2   ┆ 1     │
╰─────┴─────┴───────╯


```
