### ISSUE TITLE
Series behaviour with `pl.concat`

### ISSUE THREAD

**Issue by RichardHaythorn** [pola-rs/polars#7816]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not sure this is intended behaviour or not, but from the docs for `pl.concat` it says horizontal stack will stack pl.Series. But both "vertical" and "horizontal" seem to vertically stack the Series. 

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(
    {
        "r1": [5, 6],
        "r2": [7, 8],
        "r3": [9, 10],
    }
)

pl.concat(df.get_columns(),how='horizontal')

shape: (6,)
 Series: 'r1' [i64]
 [
 	5
 	6
 	7
 	8
 	9
 	10
 ]
```

### Expected behavior

#Casting the series to dataframes seems to get back to the original dataframe

import polars as pl
df = pl.DataFrame(
    {
        "r1": [5, 6],
        "r2": [7, 8],
        "r3": [9, 10],
    }
)

pl.concat([s.to_frame() for s in df.get_columns()],how='horizontal')

[shape: (2, 3)
 ┌─────┬─────┬─────┐
 │ r1  ┆ r2  ┆ r3  │
 │ --- ┆ --- ┆ --- │
 │ i64 ┆ i64 ┆ i64 │
 ╞═════╪═════╪═════╡
 │ 5   ┆ 7   ┆ 9   │
 │ 6   ┆ 8   ┆ 10  │
 └─────┴─────┴─────┘]

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Python: 3.10.7 (main, Oct  7 2022, 11:25:04) [GCC 11.2.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 9.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ghuls** [comment]
For stacking Series horizontal, you can use ` pl.DataFrame(df.get_columns())`.

I am not sure if `pl.concat`was ever intented to concat Series horizontal, or that it is just a documentation issue.

The main usage is to concat DataFrames (with the different `how` options).

**Comment by ritchie46** [comment]
Series cannot be stacked horizontally. That would be a `DataFrame` as @ghuls said. I think we should raise an error in such a case.
