### ISSUE TITLE
Feature request: Series.eq (equals), gt (greater than), etc

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#782]
As in pandas: `Series.eq('some_value)` or `Series.gt(2)`. It allows for more convenient syntax with dot notation when creating composite masks.

**Comment by ritchie46** [comment]
I dont want to clutter the API with everything under the sun in Pandas. You can use the available python dunder methods if you want to use dot notation.

`Series.__eq__(..)` etc.
