### ISSUE TITLE
`.map_dict` not replacing certain NaN values

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#7831]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Dividing by a NumPy `0.0` seems to produce a special NaN value that's not recognized by `.map_dict`.

### Reproducible example

```python
nan_series = pl.Series([0.]) / np.asarray([0.])

nan_series.is_nan()
# =>
# shape: (1,)
# Series: '' [bool]
# [
#         true
# ]

nan_series.map_dict({None: 42, np.nan: 42, float("nan"): 42}, default=pl.first())
# =>
# shape: (1,)
# Series: '' [f64]
# [
#         NaN
# ]
```

### Expected behavior

Either the NumPy array division should error out, or `.map_dict` should understand this NaN value.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Linux-5.4.0-1097-aws-x86_64-with-glibc2.31
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 2.0.0rc1
pyarrow: 7.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ghuls** [comment]
That is because `NaN != NaN`: https://datatest.readthedocs.io/en/latest/how-to/nan-values.html#a-deeper-understanding

```python
In [115]: nan_series == nan_series
Out[115]: 
shape: (1,)
Series: '' [bool]
[
        false
]
```

**Comment by jonashaag** [comment]
Thanks for the reply! I'm aware of that, but it wasn't obvious to me that this means you can't use it in `.map_dict`. Also note that this behaviour shows only when going through a NumPy zero division:

```py
pl.Series([float('nan')]).map_dict({float("nan"): 42}).item()
# => 42
```

**Comment by alexander-beedie** [comment]
As @ghuls says, this is expected due to the nature of `NaN` values (they don't compare equal to anything, including themselves). If you want to account for them, you might consider using `map_dict` in conjunction with a `when-then-otherwise` construct, like so:
```python
df = pl.DataFrame(
    {"x": [float('nan'), 42.0, 666]}
)
df.with_columns(
    mapped = (
        pl.when(pl.col("x").is_nan())
        .then("!!")  # << mapped NaN value
        .otherwise(pl.col("x").map_dict(
            remapping = {42.0: "forty_two"}, 
            default = "##"),
        )
    )
)
# ┌───────┬───────────┐
# │ x     ┆ mapped    │
# │ ---   ┆ ---       │
# │ f64   ┆ str       │
# ╞═══════╪═══════════╡
# │ NaN   ┆ !!        │
# │ 42.0  ┆ forty_two │
# │ 666.0 ┆ ##        │
# └───────┴───────────┘
```

**Comment by ritchie46** [comment]
We could use the bit representation of the floats as uint. And then convert back later. That's much cheaper.

**Comment by jonashaag** [comment]
@alexander-beedie I wonder why it works with a "normal" NaN then, see [this comment of mine](https://github.com/pola-rs/polars/issues/7831#issuecomment-1486557903).

**Comment by jonashaag** [comment]
NB. if you also have `inf` values in the series, in Pandas you can do

```py
nan_series.fillna(42).replace(np.inf, 42)  # or float("inf")
```

which is not exactly beautiful, but IMO a little less involved than this:

```py
# Is there a more elegant way to write this?
pl.select(pl.when(nan_series.is_finite()).then(nan_series).otherwise(42)).to_series()
```

**Comment by alexander-beedie** [comment]
> @alexander-beedie I wonder why it works with a "normal" NaN then, see [this comment of mine](https://github.com/pola-rs/polars/issues/7831#issuecomment-1486557903).

It's a bit low-level, but that succeeds because python container types implement `in` (via `__contains__`) as `any((x is elem or x == elem) for elem in container)`, so it is always covered by the identity check:

* np.nan == np.nan → False (equality check)
* np.nan is np.nan → True (identity check)

**Comment by jonashaag** [comment]
@alexander-beedie ok, this exactly what I was hypothesizing as well!

**Comment by zundertj** [comment]
> NB. if you also have `inf` values in the series, in Pandas you can do
> 
> ```python
> nan_series.fillna(42).replace(np.inf, 42)  # or float("inf")
> ```
> 
> which is not exactly beautiful, but IMO a little less involved than this:
> 
> ```python
> # Is there a more elegant way to write this?
> pl.select(pl.when(nan_series.is_finite()).then(nan_series).otherwise(42)).to_series()
> ```

you can use `map_dict` for inf values

>>> s = pl.Series([1,2,float("inf"), float("nan")])
>>> s.fill_nan(42).map_dict({float("inf"): 42},default=pl.first())
shape: (4,)
Series: '' [f64]
[
        1.0
        2.0
        42.0
        42.0
]

**Comment by jonashaag** [comment]
For whatever reason this is fixed in the latest release
