### ISSUE TITLE
`DataFrame.write_parquet(..., statistics=True)` is computing incorrect max_value

### ISSUE THREAD

**Issue by wannesghielens** [pola-rs/polars#7842]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I've been using your benchmarking repo -> https://github.com/pola-rs/tpch to check the performance of `duckdb`, this repository uses polars to generate parquet files that are used by the different benchmarked libraries.

Some of the generated parquet files contain incorrect `max_value` statistics. An example can be seen below:

```
>>> duckdb.sql("SELECT path_in_schema, row_group_id, stats_min_value, stats_max_value FROM parquet_metadata('tables_scale_1/customer.parquet') WHERE path_in_schema = 'c_custkey'")
┌────────────────┬──────────────┬─────────────────┬─────────────────┐
│ path_in_schema │ row_group_id │ stats_min_value │ stats_max_value │
│    varchar     │    int64     │     varchar     │     varchar     │
├────────────────┼──────────────┼─────────────────┼─────────────────┤
│ c_custkey      │            0 │ 1               │ 116508          │
└────────────────┴──────────────┴─────────────────┴─────────────────┘

>>> duckdb.sql("SELECT min(c_custkey), max(c_custkey) FROM 'tables_scale_1/customer.parquet'")
┌────────────────┬────────────────┐
│ min(c_custkey) │ max(c_custkey) │
│     int64      │     int64      │
├────────────────┼────────────────┤
│              1 │        1500000 │
└────────────────┴────────────────┘
```

The stats_max_value of 116508 is therefor incorrect as it should be reporting the 1500000 value. The generated corrupted file by polars in this case also only contains 1 rowgroup in case that is of importances.

I'll attach the CSV file that is used to generate this parquet file, and I'll also include the snippet of the other polars repo that does the conversion to parquet. -> [customer.tbl.zip](https://github.com/pola-rs/polars/files/11093415/customer.tbl.zip)

CC https://github.com/duckdb/duckdb/issues/6854#issuecomment-1483514754

### Reproducible example

```python
import polars as pl

h_customer = """c_custkey
c_name
c_address
c_nationkey
c_phone
c_acctbal
c_mktsegment
c_comment""".split(
    "\n"
)

name = "customer"
df = pl.read_csv(
    f"{name}.tbl",
    has_header=False,
    sep="|",
    parse_dates=True,
    new_columns=h_customer,
)
df = df.with_columns([pl.col(pl.Date).cast(pl.Datetime)])
df.write_parquet(f"{name}.parquet", statistics=True)
```

### Expected behavior

The produced row group statistic's max value is correct.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: macOS-12.3.1-x86_64-i386-64bit
Python: 3.8.15 (default, Oct 11 2022, 21:52:37) 
[Clang 14.0.0 (clang-1400.0.29.102)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Thanks for the report. Fix coming up.
