### ISSUE TITLE
Segfault when running in Docker on M1 Mac

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7847]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Simply importing Polars gives a segfault. Probably something to do with Docker / M1 processors.

### Reproducible example

Start the Docker container:

```sh
docker run -it python:3.11.2-slim-bullseye bash
```

Install Polars:

```
pip install polars
```

Importing polars gives an error:

```
root@5e159e5a047e:/# python -c "import polars"
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

### Expected behavior

It should work.

### Installed versions

Latest Docker Desktop version, Apple M1 Max chip, macOS 13.2.1

**Comment by ritchie46** [comment]
Seems similar to this: https://github.com/docker/for-mac/issues/5123

**Comment by stinodego** [comment]
I don't think so, this started happening this week. Not sure it's a Polars thing, could be a Docker thing or a Mac thing.

The same happens when importing older Polars versions. `polars-lts-cpu` seems to work correctly.

**Comment by ritchie46** [comment]
Then the virtualizations in docker for m1 is only supporting relatively old hardware accelerations. We compile for instance targetting `avx` instructions, which probably is not emulated.

This means that `polars-lts-cpu` should be used for `m1` docker.

**Comment by stinodego** [comment]
All right, thanks Ritchie. I'll mark this issue as resolved 👍
