### ISSUE TITLE
Invalid results when creating lazyframe from an optimized LogicalPlan

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#7853]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

If I create a lazyframe with a simple predicate, optimize it, extract the logical plan, then create a new lazyframe with the same logical plan, the predicate is not applied. 

It seems that it has something to do with the `file_counter` when optimizing. If after optimizing, i set the `file_counter` in `CsvParserOptions` back to `0`, it works. I also suspect it may have something to do with the `OptState`. But currently `LazyFrame` has no public method to extract the `OptState`. 

### Reproducible example

```rust
use polars::prelude::{LazyCsvReader, LazyFileListReader, LazyFrame, LogicalPlan};
use polars_plan::logical_plan::node_to_lp;
use polars_plan::prelude::{col,lit, Arena};

fn main() {
    let lf = LazyCsvReader::new("./examples/datasets/foods1.csv")
    .finish()
    .unwrap()
    .filter(col("category").eq(lit("meat")));

    with_optimization(&lf);
    without_optimization(&lf);
}

fn with_optimization(lf: &LazyFrame) {
    let mut expr_arena = Arena::with_capacity(256);
    let mut lp_arena = Arena::with_capacity(128);
    let lp_top = lf.clone().optimize(&mut lp_arena, &mut expr_arena).unwrap();
    let lp = node_to_lp(lp_top, &expr_arena, &mut lp_arena);
    println!("optimized lp {lp:?}");
    let df = LazyFrame::from(lp).collect().unwrap();
    println!("from optimized lp {df}");
}

fn without_optimization(lf: &LazyFrame) { 
    println!("unoptimized lp {:?}", lf.logical_plan);
    let df = lf.clone().collect().unwrap();
    println!("without optimized lp {df}");
}
```

### Expected behavior

The filter should be correctly applied, and you should be able to re-constitute a lazyframe from a logical plan (optimized or not). 

### Installed versions

<details>
[dependencies]
polars = {git = "https://github.com/pola-rs/polars.git", features = ["lazy"] }
polars-plan = {git = "https://github.com/pola-rs/polars.git"}
</details>

**Comment by ritchie46** [comment]
Well... If you reconstruct the `LazyFrame` it is your responsibility that it is not optimized a second time. There are optimization passes that are not meant to be run more than once. So all optimizations must be set to `false` if you reconstruct the `LazyFrame`.

**Comment by universalmind303** [comment]
That makes sense. Not sure why I didn't think of that. thanks @ritchie46
