### ISSUE TITLE
Error `object has no attribute '_s'` when appending a Series and an expression

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7862]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

There is an error when appending a Series and an expression:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[114], line 2
      1 df_check.select(
----> 2     result = pl.Series([1, 0]).append(pl.col('a'))
      3 )

File [~/.local/lib/python3.11/site-packages/polars/series/series.py:1980], in Series.append(self, other, append_chunks)
   1978 try:
   1979     if append_chunks:
-> 1980         self._s.append(other._s)
   1981     else:
   1982         self._s.extend(other._s)

AttributeError: 'Expr' object has no attribute '_s'
```

### Reproducible example

```python
df_check = pl.DataFrame({'a':[0,1]})

df_check.select(
    result = pl.Series([1, 0]).append(pl.col('a'))
)
```

### Expected behavior

A dataframe with column 'result' with values : 1, 0, 0, 1

### Installed versions

<details>

```
---Version info---
Polars: 0.16.15
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Mar 24 2023, 22:06:26) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: <not installed>
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by alexander-beedie** [comment]
I'm not sure what you're expecting to happen here? The expression doesn't have any independent life outside of the context of an operation, so I'd definitely expect an error. Is it that the error isn't clear enough?

**Comment by lucazanna** [comment]
hi @alexander-beedie ,

that's exactly it. now I understand.

would it make sense to have some syntactic sugar so that it's possible to pass lists as arguments to pl.lit ?

For example, if I want to append one value at the beginning of the column I can do:
```
pl.lit( 0 ).append( pl.col('a') )
```
It would be easy if I could append multiple values with: 
```
pl.lit( [0, 0] ).append( pl.col('a') )
```
This was what I tried at first.

What are your thoughts? 

If you disagree on the syntactic sugar (or if it's not priority), and think modifying the guide is better I would happy to submit a PR with an example of this. (for example here https://pola-rs.github.io/polars-book/user-guide/notebooks/introduction_polars-py.html?highlight=lit#selection-context)
