### ISSUE TITLE
pl.concat() => match by names

### ISSUE THREAD

**Issue by nick-youngblut** [pola-rs/polars#7866]
### Problem description

Works:

```
df1 = pl.DataFrame({"a": [1], "b": [3]})
df2 = pl.DataFrame({"a": [2], "b": [4]})
```

Throws an error:

```
df1 = pl.DataFrame({"a": [1], "b": [3]})
df2 = pl.DataFrame({"b": [2], "a": [4]})
```

The error: `exceptions.ShapeError: unable to vstack, column names don't match: "a" and "b"`

It would be helpful to include a `match_names` parameter so that the columns are matched by names, instead of requiring the user to reorder the DataFrame prior to the `concat` operation.

I'm using polars v0.16.12

**Comment by ritchie46** [comment]
Just be explicit:

```python
pl.concat([df.select(df1.columns) for df in [df1, df2, df3, ..., dfn])
```

**Comment by nick-youngblut** [comment]
Thanks @ritchie46 for the suggestion! It might help to clarify in the [polars docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.concat.html) that the column ordering must match for vertical concat operations, and providing your example in the docs would be quite helpful.

**Comment by ritchie46** [comment]
This is added with `how="diagonal"`
