### ISSUE TITLE
[Rust] [Performance] Polars v0.28.0 makes CsvReader 4 times slower

### ISSUE THREAD

**Issue by sarthak-sehgal** [pola-rs/polars#7880]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Same code used for both

0.28.0 code -
```
let now = Instant::now();
let reader = std::io::Cursor::new(&data); // data is a Vec<u8>
let df = CsvReader::new(reader).has_header(false).with_schema(schema.clone()).finish().unwrap(); // schema is an Arc<Schema>
log::info!("Created df in time = {}ms", now.elapsed().as_millis());
```
Logs - 
```
[2023-03-30T13:17:29Z INFO  pq_writer::gzip_reader] Read gzip offset = 9103575695, chunk size = 10000000, time taken = 1s
[2023-03-30T13:17:31Z INFO  pq_writer::pq_writer] Created df in time = 2230ms
```

0.27.2 code -
```
let reader = std::io::Cursor::new(&data); // data is a Vec<u8>
let df = CsvReader::new(reader).has_header(false).with_schema(&schema).finish().unwrap(); // schema is a Schema
```

Logs -
```
[2023-03-30T13:10:08Z INFO  pq_writer::gzip_reader] Read gzip offset = 9193575695, chunk size = 10000000, time taken = 1s
[2023-03-30T13:10:09Z INFO  pq_writer::pq_writer] Created df in time = 568ms
```

**Note: Has not been tested on Python**

### Reproducible example

Can't share CSV. Should be reproducible when reading any huge blob of data in memory (`Vec<u8>`) via CsvReader. In my code, I am reading 10 million lines.

### Expected behavior

Should be more optimised

### Installed versions

<details>
Replace this line with a list of feature gates
</details>

**Comment by alexander-beedie** [comment]
Can you provide the dtypes/schema you're reading? Doesn't have to be the real column headers, but at least we'd be able to construct some synthetic data to test with.

**Comment by ritchie46** [comment]
It actually had large speedups for many csv files. It is very much dependent on the data. 

Cab you anonimize your data and share that and the schema? Did you have any specifics, like large fields?

**Comment by sarthak-sehgal** [comment]
I am trying to reproduce the issue with some fake data. Give me till tomorrow.

**Comment by ritchie46** [comment]
Any update @sarthak-sehgal

**Comment by zundertj** [comment]
Changing bug label to performance.

**Comment by sarthak-sehgal** [comment]
Sorry for the delay. Going to reopen this issue when I can reproduce this with fake data. For reference, this is the schema of my data -
```
DTYPES = {
    "ric": "str",
    "domain": "str",
    "datetime": "datetime64[ns]",
    "offset": "float64",
    "type": "str",
    "msg_class": "str",
    "update_type": "str",
    "fid_name": "str",
    "fid_value": "str",
    "fid_enum": "str",
    "pe_code": "UInt64",
    "template_num": "UInt64",
    "seq_num": "UInt64",
    "num_fids": "UInt64"
}
```
