### ISSUE TITLE
fix(Python): Unable to import polars after v0.16.16 install on Windows

### ISSUE THREAD

**Issue by RNKuhns** [pola-rs/polars#7881]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When I try to import polars after installing version 0.16.16 from conda-forge or pip, I receive an import error.

Specifically PolarsDataType is not able to be imported from datatypes module. Looking at underlying code that was installed on my machine, the imports of this into __init__ doesn’t appear to be present.

Downgrading to 0.16.15 fixed the problem.

### Reproducible example

```python
import polars as pl
```

### Expected behavior

Should be able to import

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>
This is version 0.16.16 on Windows.

**Comment by RNKuhns** [comment]
Note that looking at code in the repo, this seems like it might have been fixed by commit 61474b5 that occurred 2 days ago.

mix this is an issue for anyone installing latest version, maybe worth an updated release?

**Comment by MarcoGorelli** [comment]
works for me on Windows:
```
(base) C:\Users\User>pip install polars
Collecting polars
  Downloading polars-0.16.16-cp37-abi3-win_amd64.whl (17.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 8.8 MB/s eta 0:00:00
Collecting typing_extensions>=4.0.1
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing_extensions, polars
Successfully installed polars-0.16.16 typing_extensions-4.5.0

(base) C:\Users\User>python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
```

Could you show your full traceback please?

**Comment by ghuls** [comment]
@RNKuhns can you try with the latest version (0.16.18)?

**Comment by stinodego** [comment]
Closing as stale.
