### ISSUE TITLE
.to_dummies: Had to reallocate groups, missed an optimization opportunity. Please open an issue.

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#7884]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Seems to happen here: https://github.com/pola-rs/polars/blob/d350f5ecea39dbedffbf7d9252eb4902a5de17eb/polars/polars-ops/src/series/ops/to_dummies.rs#LL26C18-L26C35

### Reproducible example

```python
import polars as pl

(
    pl.DataFrame({"x": pl.arange(0, 3, eager=True)})
    .lazy()
    .filter(pl.col("x") % 2 == 0)
    .with_columns(lit=pl.lit("a").cast(pl.Categorical))
    .collect()
    .to_dummies("lit")
)
```

### Expected behavior

Don't raise warning.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.1
pandas: 1.5.2
pyarrow: 10.0.1
connectorx: 0.3.1
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: 0.8
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Alright. Let's make it faster then. :)
