### ISSUE TITLE
compiling on apple m1 failes with feature "dtype-categorical"

### ISSUE THREAD

**Issue by EdmundsEcho** [pola-rs/polars#7888]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When I add the features entry "dtype-categorical" the code fails to compile.  Here is the error:

```fish
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/var/folders/vr/kgm9vp2x32qfctcmq7sy5f280000gn/T/rustcPpIya1/symbols.o" "/Users/edmund/Programming-Local/tnc-analysis/lib/target/debug/deps/tnc_analysis_lib-19cc4d07585598ef.18uvr36i4bwjrosc.rcgu.o" ....
...
"/Users/edmund/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/edmund/Programming-Local/tnc-analysis/lib/target/debug/deps/tnc_analysis_lib-19cc4d07585598ef" "-Wl,-dead_strip" "-nodefaultlibs" "-undefined" "dynamic_lookup"
  = note: ld: warning: -undefined dynamic_lookup may not work with chained fixups
          ld: in /Users/edmund/Programming-Local/tnc-analysis/lib/target/debug/deps/libpolars_io-c22ce3a209f45a1e.rlib(polars_io-c22ce3a209f45a1e.polars_io.d88edeeb-cgu.0.rcgu.o), archive member 'polars_io-c22ce3a209f45a1e.polars_io.d88edeeb-cgu.0.rcgu.o' with length 0 is not mach-o or llvm bitcode file '/Users/edmund/Programming-Local/tnc-analysis/lib/target/debug/deps/libpolars_io-c22ce3a209f45a1e.rlib' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here is the features entry in my Cargo.toml:

```toml
[dependencies.polars]
version = "0.28"
features = ["describe", "dtype-categorical", "to_dummies", "parquet", "lazy", "csv-file", "object"]
```

### Reproducible example

see above

### Expected behavior

it compile

### Installed versions

<details>
 ["describe", "dtype-categorical", "to_dummies", "parquet", "lazy", "csv-file", "object"]
</details>

**Comment by ritchie46** [comment]
That's strange. Seems to be something in your linker. I am not sure this is polars related. Are you latest compiler?

**Comment by EdmundsEcho** [comment]
Thank you for the follow-up.  I updated everything recently....

```fish
> rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

To the degree there is a dependency on Xcode, I'm using v14.2 (v14.3 was released yesterday).

The only reason I suspect it is something that Polars might want to consider is given how much of the code depends on the specifics of the platform and activated features.  Perhaps some mix and match related requirement fell through the cracks.  In my case, it just won't compile with the "dtype-categorical" feature.  Everything else, aok.  

All said, of course this could still be a rustc issue.  I'm happy to forward the issue on.  Is there any more information we might provide to help inform the issue?

**Comment by EdmundsEcho** [comment]
... I updated rustc to v1.68.2.  The code now compiles.  Is there a check that can be put in place because there is a dependency on using a version of rustc?

**Comment by jakob-keller** [comment]
Not sure if this is related, but I am having trouble running the test suite since ef2ab8af98eb154dc2f924105d787ad0328a5944: #7952

**Comment by ritchie46** [comment]
If you want to compile the polars crate that is not published on crates.io, you must always use the rustc compiler we have set in https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml

**Comment by ritchie46** [comment]
I am closing this. If there is another issue feel free to open a new issue.
