### ISSUE TITLE
DOC: truediv division by zero behaviors

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7889]
https://github.com/pola-rs/polars/blob/4fe801bbb9372d3ac3512c05a6148ba49f25dc2f/py-polars/polars/expr/expr.py#L262

```python
pl.DataFrame(
    {'a': [0, 1, -1, 0],
     'b': [0, 0, 0, 1]}
).with_columns(
    pl.col('a').truediv(pl.col('b')).alias('a_truediv_b'),
    (pl.col('a') / pl.col('b')).alias('a/b'),
)
```

```
shape: (4, 4)
┌─────┬─────┬─────────────┬──────┐
│ a   ┆ b   ┆ a_truediv_b ┆ a/b  │
│ --- ┆ --- ┆ ---         ┆ ---  │
│ i64 ┆ i64 ┆ f64         ┆ f64  │
╞═════╪═════╪═════════════╪══════╡
│ 0   ┆ 0   ┆ NaN         ┆ NaN  │
│ 1   ┆ 0   ┆ inf         ┆ inf  │
│ -1  ┆ 0   ┆ -inf        ┆ -inf │
│ 0   ┆ 1   ┆ 0.0         ┆ 0.0  │
└─────┴─────┴─────────────┴──────┘
```
See also:

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.is_infinite.html#polars.Expr.is_infinite

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.fill_nan.html#polars.Expr.fill_nan

**Comment by s-banach** [comment]
https://en.wikipedia.org/wiki/IEEE_754

**Comment by s-banach** [comment]
https://docs.python.org/3/reference/datamodel.html

**Comment by alexander-beedie** [comment]
@StevenLi-DS: Not quite sure what this issue is about as the results (as given) look correct to me; you're doing float division (truediv) and getting the expected float values for the various div0 outcomes.

Could you clarify if I'm missing something? 😅

**Comment by StevenLi-DS** [comment]
Hi, @alexander-beedie sorry about that. Indeed, I think maybe add the example to the docstring would be helpful, so someone would know what to expect. Indeed the results are expected. One thing that surprised me is you get a NaN for 0/0 instead of a null.

**Comment by StevenLi-DS** [comment]
@alexander-beedie Thanks for adding this. I'm curious why 0/0 return np.nan instead of null in polars? It seems a truediv always return a f64 right?

**Comment by alexander-beedie** [comment]
> @alexander-beedie Thanks for adding this. I'm curious why 0/0 return np.nan instead of null in polars? It seems a truediv always return a f64 right?

@StevenLi-DS: Yes - and `NaN` is indeed a valid floating point value, with a very different meaning from `null` (you definitely don't want to unintentionally conflate the two values) ;) 

For example, you would typically interpret `null` as "missing value" or "unknown", whereas `nan` is "invalid or indeterminate floating point result" (such as `0/0`). There's plenty of literature on the subject, but this is a nice/concise summary: https://mathworld.wolfram.com/NaN.html 

You'll find 0/0 returning NaN in essentially all math libraries/functions; for example...
```python
import numpy as np
np.array([0,1]) / np.array([0,2])

# array([nan, 0.5])
```
```python
import pandas as pd
df = pd.DataFrame({"x":[0,1], "y":[0,2]})
df["x"] / df["y"]

# 0    NaN
# 1    0.5
# dtype: float64
```

**Comment by StevenLi-DS** [comment]
@alexander-beedie Thanks for the link and explanation. I've using pandas and numpy for years but didn't realize NaN is a more universal and standard concept. I guess it could be useful to keep them separate so that you can tell the existing nulls from resulting invalid values...

**Comment by alexander-beedie** [comment]
> @alexander-beedie Thanks for the link and explanation. I've using pandas and numpy for years but didn't realize NaN is a more universal and standard concept. I guess it could be useful to keep them separate so that you can tell the existing nulls from resulting invalid values...

Pandas and Numpy have long used NaN for both the right reason (invalid/indeterminate floating point math) AND for the wrong reason (missing values). The latter is -finally!- being fixed with Pandas 2.0 and the new arrows dtypes, where they'll have real null (NA) values at long last, and can stop abusing NaN ;)

**Comment by StevenLi-DS** [comment]
@alexander-beedie indeed.. I very often import numpy to just use np.nan. I will switch to arrows dtypes backend as soon as the official 2.0 comes out.

**Comment by alexander-beedie** [comment]
> @alexander-beedie indeed.. I very often import numpy to just use np.nan. 

No need to import numpy for that as `np.nan` is just a regular python `float('nan')`; you could set it up the same way by assigning `nan = float('nan')` 👍

**Comment by StevenLi-DS** [comment]
@alexander-beedie Didn't realize that either...lol.😅
