### ISSUE TITLE
Implement qcut as expression to improve performance

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#7891]
### Problem description

I have a task on hand where I would like to do ```qcut``` in a ```over``` context on a large dataframe.

Sample dataframe:
```
import time
import numpy as np
import polars as pl

n_group1 = 10
n_group2 = 1000
n_obs = 10000000

df = pl.DataFrame(
    {
        "group1": np.random.randint(0, n_group1, size=n_obs),
        "group2": np.random.randint(0, n_group2, size=n_obs),
        "value1": np.random.normal(0, 1, n_obs),
        "value2": np.random.normal(0, 1, n_obs),
        "value3": np.random.normal(0, 1, n_obs),
    }
)
```

For a single column, the speed of the following is acceptable. (The following section takes ~4-5s).
```
start = time.perf_counter()
res = df.with_columns(
    pl.col("value1")
    .apply(
        lambda s: s.qcut(
            [0.2, 0.4, 0.6, 0.8], labels=["1", "2", "3", "4", "5"], maintain_order=True
        )["category"]
    )
    .over(["group1", "group2"])
)
time.perf_counter() - start
```

However, when I have multiple columns over which I want to iterate for doing ```qcut```, the speed is linearly proportionally to the number of columns in the loop. (The following section takes ~12-14s).
```
start = time.perf_counter()
res = df.with_columns(
    pl.col(f"value{i}")
    .apply(
        lambda s: s.qcut(
            [0.2, 0.4, 0.6, 0.8], labels=["1", "2", "3", "4", "5"], maintain_order=True
        )["category"]
    )
    .over(["group1", "group2"])
    for i in range(1, 4)
)
time.perf_counter() - start
```

So, my question/suggestions is: if ```qcut``` is implemented as an expression, would my second example run much faster?

**Comment by cmdlineluser** [comment]
I don't know the answer to your actual question (I'd imagine it's yes) - but you may be interested in timing an approach using [pl.apply](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.apply.html#polars.apply) 
```
def qcuts(columns):
   quantiles = [0.2, 0.4, 0.6, 0.8]
   labels = ["1", "2", "3", "4", "5"]
   cats = (
       col.qcut(quantiles, labels, maintain_order=True)
          .get_column("category")
       for col in columns
   )
   return pl.DataFrame(cats).to_series()

start = time.perf_counter()

res = df.with_columns(
    pl.apply(pl.col("^value\d+$"), qcuts).over(["group1", "group2"])
)

time.perf_counter() - start
```

**Comment by paladin158** [comment]
> I don't know the answer to your actual question (I'd imagine it's yes) - but you may be interested in timing an approach using [pl.apply](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.apply.html#polars.apply)
> 
> ```
> def qcuts(columns):
>    quantiles = [0.2, 0.4, 0.6, 0.8]
>    labels = ["1", "2", "3", "4", "5"]
>    cats = (
>        col.qcut(quantiles, labels, maintain_order=True)
>           .get_column("category")
>        for col in columns
>    )
>    return pl.DataFrame(cats).to_series()
> 
> start = time.perf_counter()
> 
> res = df.with_columns(
>     pl.apply(pl.col("^value\d+$"), qcuts).over(["group1", "group2"])
> )
> 
> time.perf_counter() - start
> ```

Thanks for your suggestion. Not sure about the difference but looks like the time taken are roughly the same as in my original post.

**Comment by cmdlineluser** [comment]
Interesting, thanks for the results. It runs the benchmark ~50% faster on my machine and the CPU utilization differs.

There must be something "platform specific" going on.

**Comment by paladin158** [comment]
> Interesting, thanks for the results. It runs the benchmark ~50% faster on my machine and the CPU utilization differs.
> 
> There must be something "platform specific" going on.

It is indeed faster though, but not significant. For my current example, it is about 20% faster, but as I add more ```value\d+``` columns in ```df```, speedup is less and less. Seems like your approach is only constant-time faster than the approach outlined in my post (always ~3-4s faster on my machine, no matter the base cost).

**Comment by magarick** [comment]
This can be closed.
