### ISSUE TITLE
CsvReader reading files with columns of unix millisecond timestamps got null values

### ISSUE THREAD

**Issue by thinkphoebe** [pola-rs/polars#7899]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Using CsvReader reading files with columns of millisecond timestamps, set dtype to `DataType::Datetime(TimeUnit::Milliseconds, None)`, the readed polars DataFrame column values are all null.  This problem existing since version 0.23, and existing in the latest version 0.28. The last working version is 0.22.8.

### Reproducible example

fn main() {
    let content = r#"DatetimeMs
1680094799999
1680094859999
1680094919999
1680094979999
1680095039999
1680095099999
1680095159999
1680095219999
1680095279999
"#;

    let mut s = Schema::new();
    s.with_column(smartstring::SmartString::from("DatetimeMs"), DataType::Datetime(TimeUnit::Milliseconds, None));
    let file = Cursor::new(content);
    let df = CsvReader::new(file)
            .with_columns(Some(vec!["DatetimeMs".to_string()]))
            .with_dtypes(Some(Arc::new(s)))
            .with_null_values(Some(NullValues::AllColumns(vec!["NaN".to_string()])))
            .has_header(true)
            .finish().unwrap();
    eprintln!("df:\n{:?}", df);
}

======== Output ========
df:
shape: (9, 1)
┌──────────────┐
│ DatetimeMs   │
│ ---          │
│ datetime[ms] │
╞══════════════╡
│ null         │
│ null         │
│ null         │
│ null         │
│ …            │
│ null         │
│ null         │
│ null         │
│ null         │
└──────────────┘

### Expected behavior

The last working version is 0.22.8, the following code can parse millisecond timestamps successful.

fn main() {
    let content = r#"DatetimeMs
1680094799999
1680094859999
1680094919999
1680094979999
1680095039999
1680095099999
1680095159999
1680095219999
1680095279999
"#;

    let mut s = Schema::new();
    s.with_column("DatetimeMs".to_string(), DataType::Datetime(TimeUnit::Milliseconds, None));
    let file = Cursor::new(content);
    let df = CsvReader::new(file)
            .with_columns(Some(vec!["DatetimeMs".to_string()]))
            .with_dtypes(Some(&s))
            .with_null_values(Some(NullValues::AllColumns("NaN".to_string())))
            .has_header(true)
            .finish().unwrap();
    eprintln!("df:\n{:?}", df);
}

======== Output ========
df:
shape: (9, 1)
┌─────────────────────────┐
│ DatetimeMs              │
│ ---                     │
│ datetime[ms]            │
╞═════════════════════════╡
│ 2023-03-29 12:59:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:00:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:01:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:02:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:04:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:05:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:06:59.999 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2023-03-29 13:07:59.999 │
└─────────────────────────┘

### Installed versions

<details>
0.22.8
0.28
</details>

**Comment by stinodego** [comment]
When reading the provided data now from Python, I get an error:

```python
df = pl.read_csv("ms.csv", schema={"DatetimeMs": pl.Datetime("ms")})
```
```
polars.exceptions.ComputeError: could not parse `1680094799999` as dtype `datetime[μs]` at column 'DatetimeMs' (column number 1)

The current offset in the file is 11 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `1680094799999` to the `null_values` list.

Original error: ```could not find a 'date/datetime' pattern for '1680094799999'```
```

This seems correct to me, as it's an integer, not a datetime. You can do the following to get the result you're looking for:

```python
df = pl.read_csv("ms.csv").with_columns(pl.col("DatetimeMs").cast(pl.Datetime("ms")))
```
