### ISSUE TITLE
df.lazy().filter(lit(true)).collect() results in ShapeMisMatch

### ISSUE THREAD

**Issue by H-M-H** [pola-rs/polars#790]
#### Are you using Python or Rust?
Rust

#### Which feature gates did you use?
`features = ["temporal", "lazy", "dtype-full", "ipc", "strings"]`

#### What version of polars are you using?
v0.14.1

#### Describe your bug.
Filtering a `LazyFrame` using `filter` with `lit(true)` as argument results in a `ShapeMisMatch` with the message `Filter's length differs from that of the ChunkedArray/ Series. Length Self: 3526 Length mask: 0 ...` after calling `collect`.

#### What is the expected behavior?
I'd expect polars to return the unfiltered DataFrame if `lit(true)` is passed to `filter`, especially considering that the expression:
`[(Boolean(true)) And ([([(bitrate) Eq (Float64(0.0))]) Or ([(bitrate) NotEq (Float64(0.0))])])]` (<-- `fmt::Debug` output of the `Expr`) does just that.

**Comment by ritchie46** [comment]
I tried to reproduce the described bug with:


```rust
    #[test]
    fn test_filter_lit() -> Result<()> {
        let df = df![
            "a" => [0, 1, 2, 0, 2],
            "b" => ["a", "b", "c", "d", "e"]
        ]?;

        let out = df
            .lazy()
            .filter(lit(true))
            .collect()?;
        dbg!(out);

        Ok(())
    }
```

But that snippet works. Have you got a small example to reproduce the error?

**Comment by H-M-H** [comment]
I am sorry, I should have included a snippet from the start:
```rust
    for &n in [5, 100].iter() {
        let a: Vec<_> = (0..n)
            .map(|i| ('A'..='Z').nth(i % 26).unwrap().to_string())
            .collect();
        let a = Series::new("a", a);
        let df = DataFrame::new([a].into()).unwrap();

        let out = df
            .lazy()
            .filter(lit(true))
            .collect();
        println!("{:#?}", out);
    }
```
The first iteration runs fine, the second does not:
```
Ok(
    shape: (5, 1)
    +-----+
    | a   |
    | --- |
    | str |
    +=====+
    | "A" |
    +-----+
    | "B" |
    +-----+
    | "C" |
    +-----+
    | "D" |
    +-----+
    | "E" |
    +-----+
    ,
)
Err(
    ShapeMisMatch(
        "Filter\'s length differs from that of the ChunkedArray/ Series. Length Self: 12 Length mask: 0Self: shape: (12,)\nChunkedArray: \'a\' [str]\n[\n\t\"M\"\n\t\"N\"\n\t\"O\"\n\t\"P\"\n\t\"Q\"\n\t\"R\"\n\t\"S\"\n\t\"T\"\n\t\"U\"\n\t\"V\"\n\t\"W\"\n\t\"X\"\n]; mask: shape: (0,)\nChunkedArray: \'literal\' [bool]\n[\n]",
    ),
)
```
I did not notice it at first but this only seems to happen if the series is not too short as in the test case above and if it contains Utf8.
