### ISSUE TITLE
[Feature Request] Series.is_in(Set)

### ISSUE THREAD

**Issue by tsoernes** [pola-rs/polars#791]
For now, `Series.is_in` works with Lists and other Series. Would it be possible, and more efficient to allow sets?

**Comment by ritchie46** [comment]
It probably will not be more efficient. I use hashsets in Rust. They are typed and thus likely much more efficient than python's sets. Besides that, I then also need to use python hash functions to use the set, which would be another slowdown.

**Comment by ritchie46** [comment]
I will close this as I don't think any action is required. Users can can pass in a list, and we will create the needed data structures from the Rust side.
