### ISSUE TITLE
map_dict fails to cast f64 to bool

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#7917]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

After upgrading to 0.16.17 from 0.16.16..I can an unexpected error and realize that map_dict is no longer able to cast f64 to bool

### Reproducible example

```python
pl.DataFrame(
    {'a': [1.0, None]}
).with_columns(
    pl.col('a').map_dict({1.0: True})
)
```
```
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ 1.0  │
│ null │
└──────┘
```

### Expected behavior

What it's used to be in 0.16.16
```
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ true │
│ null │
└──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.17
Index type: UInt32
Platform: macOS-13.3-arm64-arm-64bit
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) 
[Clang 12.0.1 ]
---Optional dependencies---
numpy: 1.22.3
pandas: 1.4.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.0
xlsx2csv: 0.8.1
xlsxwriter: <not installed>```

</details>

**Comment by alonme** [comment]
I assume this has something to do with the fact that in python `1` and `True` are "related", See the following 

```
>>> [hash(i) for i in [0, False, 1, True]]
[0, 0, 1, 1]
>>> 1 == True
True
>>> isinstance(True, int)
True
```

One reason to think that is that the same happens with mapping to False
```
>>> pl.DataFrame(
    {'a': [1, 2]}
).with_columns(
    pl.col('a').map_dict({2: False})
)
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ null │
│ 0    │
└──────┘
```

**Comment by ghuls** [comment]
There is a `dtype` argument in `map_dict` to override the output dtype fir cases like this.

**Comment by StevenLi-DS** [comment]
Is this inconsistency still a bug?

**Comment by ghuls** [comment]
I don't consider it a bug as in most cases a dtype change is unwanted: see https://github.com/pola-rs/polars/issues/7788

**Comment by StevenLi-DS** [comment]
@ghuls so basically I should use .when.then instead right? if I don't want to always think about dtype.. I assume when then will always cast to the dtype you changed

**Comment by StevenLi-DS** [comment]
If the finial dtype is different that the dtype given in the remapping dict in map_dict... I think there should be a warning msg.

**Comment by StevenLi-DS** [comment]
@ghuls I saw https://github.com/pola-rs/polars/pull/7797 
If this is not a bug, feel free to close it but I still think there should a warning msg to warn users

**Comment by ritchie46** [comment]
I think we should error here, unless dtype is set.

**Comment by ghuls** [comment]
> I think we should error here, unless dtype is set.

I will see if I can add some additional checks.

**Comment by StevenLi-DS** [comment]
I often have hundreds line of code before df.collect(). If there is any issue with the code, it will raise an exception, but the error msg basically not informative and helpful at all. I really take a while to find this issue, but re-execute the code block by block..

Is there any plan to improve error msg in this case so that it can help me trace back to the line of code that cause the issue? This has happened so many times.

**Comment by StevenLi-DS** [comment]
For example: 
```python
import polars as pl

pl.LazyFrame(
    {'a': [1.0, None]}
).with_columns(
    pl.col('a').map_dict({1: True})  # assume dtype has changed to bool
).with_columns(
    pl.when(pl.col('a')).then(None)
).collect()
```
```
SchemaError: invalid series dtype: expected `Boolean`, got `f64`
```
Maybe this would be more helpful for debugging:
```
SchemaError: invalid series dtype in column `a`: expected `Boolean`, got `f64`
```

**Comment by StevenLi-DS** [comment]
Here's another example. It just throws me a PanicException without tell me which line is the problem, expect df.collect()
<img width="833" alt="CS-xWFUjrCL@2x" src="https://user-images.githubusercontent.com/33796896/229377053-e55cfd67-b930-48e3-ac3f-3b542f6f05f7.png">

**Comment by StevenLi-DS** [comment]
This only tells me a join issue... but I have lots of join in the code...
<img width="757" alt="CS-C1wW1Db9@2x" src="https://user-images.githubusercontent.com/33796896/229399908-ea074176-3350-4410-8e29-33f2c7de2fa3.png">
