### ISSUE TITLE
Performance regression in `pl.from_records(orient="row")`

### ISSUE THREAD

**Issue by jakob-keller** [pola-rs/polars#7926]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Since `polars==0.16.17` there appears to be a significant (~50%) performance regression somewhere in the codepath used by `pl.from_records()` when called with argument `orient="row"`.

I am just guessing here, but I believe the regression is not actually happening in the Python wrapper, but on the Rust side or in the bindings.

### Reproducible example

```python
python -m timeit -s "import polars as pl; columns = 50; rows = 1000; data = tuple([float(i) for i in range(columns)] for _ in range(rows)); schema=[(f'col_{c}', pl.Float64) for c in range(columns)]" "pl.from_records(data=data, schema=schema, orient='row', infer_schema_length=None)"
```

Output:
polars==0.16.16: `20 loops, best of 5: 10.5 msec per loop`
polars==0.16.17: `20 loops, best of 5: 15.2 msec per loop`

### Expected behavior

Performance should be roughly the same or better

### Installed versions

<details>

```
---Version info---
Polars: 0.16.17
Index type: UInt32
Platform: macOS-13.3-arm64-arm-64bit
Python: 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Could someone get a bisect on this?

**Comment by jakob-keller** [comment]
The performance regression apparently persists in `polars==0.16.18`.

**Comment by ritchie46** [comment]
Yes, we first need to find which commit introduced the regression. Any help on this would be appreciated.

**Comment by jakob-keller** [comment]
> Yes, we first need to find which commit introduced the regression. Any help on this would be appreciated.

Seems like it's time for me to set up a local Rust toolchain for the first time... Wish me look ;-)

**Comment by ritchie46** [comment]
Good luck! Once setup, compile with:

 ```
 $ cd py-polars && maturin develop --release -- -C codegen-units=16 -C lto=thin -C target-cpu=native
 ```

**Comment by jakob-keller** [comment]
Well, setup appeared to go smooth, but 4 tests are failing due to `pyo3_runtime.PanicException: misaligned pointer dereference: address must be a multiple of 0x10 but is 0xxxx`

Will open a separate issue, I guess...

**Comment by jakob-keller** [comment]
> Well, setup appeared to go smoothly, but 4 tests are failing due to `pyo3_runtime.PanicException: misaligned pointer dereference: address must be a multiple of 0x10 but is 0xxxx`

Hm, tests are successful for git commits that bump to `0.16.16` and `0.16.17` respectively. Will do the bisect first then look at the other issue...

**Comment by jakob-keller** [comment]
> Could someone get a bisect on this?

I think, I found the commit that introduced the performance regression: 628e476e1877d05641a8e9ff4d70b45078c2ec27

**Comment by ritchie46** [comment]
Right, Thanks will take this one.
