### ISSUE TITLE
Is there a plan to support Ballista

### ISSUE THREAD

**Issue by selvavm** [pola-rs/polars#7927]
### Problem description

Hi,

I have 30k parquet file placed in cloud in hive partition format (say folder names look like `colname==xyz`). 

I want to do group by and aggregation by each file and/or multiple files. 

Polars is fast, but my data is too high volume (15000 rows per file). Hence, I need distribution to speed things up. I tried spark but it is not fast due to overheads. Hence, I was looking into other options. 

In https://github.com/apache/arrow-ballista/pull/685 I came to know that Ballista supports custom dataframes and is it possible to integrate that with Polars?

Maybe, each file is a partition and distributed in kubernete pods. Then the partitions are polars dataframe executed in each pods. This is similar to dask. 

If this is available, Ballista + Polars can easily overthrow spark. 

Please let me know if you need more details.

Note: I like your out of core calculations but here I am expecting distributing the workloads with other machines to reduce time.

**Comment by alexander-beedie** [comment]
Your workload might be a good candidate for the newly announced Fugue/Spark Polars integrations: https://fugue-tutorials.readthedocs.io/tutorials/integrations/backends/polars.html. There's another blog post coming later with additional details and benchmarks, but if your data can be coarsely partitioned this approach might be of interest - can get very real speedups over native Spark.

**Comment by selvavm** [comment]
One of the reason for slower performance I encountered is because of python udf (some complex data transformation) in spark. So we thought of going with rust. Is Fugue available in Rust?

**Comment by alexander-beedie** [comment]
> Is Fugue available in Rust?

No, Python only. FYI: while it seems you're after a Rust-based option, there is another interesting "distributed polars" project (also Python) that was recently brought to our attention in the polars' Discord channel: https://github.com/marsupialtail/quokka/blob/master/blog/release.md. Perhaps the benefits of one or the other will outweigh the costs in terms of your UDFs?

**Comment by stinodego** [comment]
We have no plans to integrate with Apache Ballista at this time.
