### ISSUE TITLE
`pl.concat` with `pl.Object`

### ISSUE THREAD

**Issue by sslivkoff** [pola-rs/polars#7928]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`pl.concat()` does not work for columns of type `pl.Object`

Instead it panics: `PanicException: not implemented for dtype Object("object")`

### Reproducible example

```python
df1 = pl.DataFrame(
    {'a': [1,2,3], 'b': [4,5,6]},
    schema={'a': pl.Int32, 'b': pl.Object},
)

df2 = pl.DataFrame(
    {'a': [1,2,3], 'b': [4,5,6]},
    schema={'a': pl.Int32, 'b': pl.Object},
)

pl.concat([df1, df2])
```

### Expected behavior

```
def concat(dfs, **kwargs):
    """like pl.concat, with support for objects

    does not support all edge cases
    """

    # find object columns
    object_columns = []
    non_object_columns = []
    for column, datatype in dfs[0].schema.items():
        if datatype == pl.Object:
            object_columns.append(column)
        else:
            non_object_columns.append(column)
    
    # build object columns
    object_series = []
    for object_column in object_columns:
        values = []
        for df in dfs:
            values.extend(df[object_column].to_list())
        series = pl.Series(object_column, values, dtype=pl.Object)
        object_series.append(series)

    # concat non-object columns
    without_objects = [df[non_object_columns] for df in dfs]
    concated = pl.concat(without_objects)
    return concated.with_columns(object_series)
```

### Installed versions

<details>

```
Polars: 0.16.16
```

</details>

**Comment by alexander-beedie** [comment]
I doubt that we should try to support this; "Object" means that it is an opaque Python-native type. As such, we don't know if it supports any of the requested operations and, even if we get lucky and it does, all of those operations will run in Python-space and kill performance (GIL, etc). If you *have* no choice but to operate on Python objects you should be able to do so via `apply` and `map`.

**Comment by ritchie46** [comment]
I think the append/concat should work. Can take a look later.

**Comment by alexander-beedie** [comment]
Ahh... I misread; this is concat of the *columns* (which should indeed work!), not the objects *in* the columns - that's what happens when you read too fast on the phone 😅

**Comment by sslivkoff** [comment]
ha agreed that `concat`ing the objects themselves seems too specific to reasonably support

although dunder method support for `pl.Object` columns could be nice to have https://github.com/pola-rs/polars/issues/6252 😁😁
