### ISSUE TITLE
`unique` not working with `list` and `struct` columns

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7929]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`DataFrame.unique()` is not working when one column is either a `struct` or a `list`

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "numerical": [1, 2, 1],
    "struct": [{"x": 1, "y": 2}, {"x": 3, "y": 4}, {"x": 1, "y": 2}],
    "list": [[1, 2], [3, 4], [1, 2]]
})

# Works
df.select('struct').unique()

# Works
df.select('list').unique()

# Does not work
df.select('numerical','list').unique()
# InvalidOperationError: `vec_hash_combine` operation not supported for dtype `list[i64]`

# Does not work
df.select('numerical','struct').unique()
# InvalidOperationError: `vec_hash_combine` operation not supported for dtype `struct[2]`
```

### Expected behavior

I wish Polars could support the unique operation also with lists and structs

I can think of another way to do this but it would be longer:
* Lists
change the list to a struct with `arr.to_struct`
`unnest`
calculate `unique`
use `concat_list` to change back to a list

* Structs
`unnest`
calculate `unique`
use `pl.struct` to change back to a struct

### Installed versions

<details>

```
---Version info---
Polars: 0.16.17
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Mar 24 2023, 22:06:26) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: <not installed>
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by stinodego** [comment]
This works on the latest version.
