### ISSUE TITLE
Add PyLazyFrame in pyo3-polars

### ISSUE THREAD

**Issue by Marlin-Na** [pola-rs/polars#7933]
### Problem description

I am trying to implement an anonymous scan method (with the `AnonymousScan` trait) reading data from custom sources. I am also hoping to make the resulting `LazyFrame` available in python.

Using the [pyo3-polars crate](https://github.com/pola-rs/pyo3-polars), I am able to convert between DataFrame in Python and Rust. However, for LazyFrame, it seems that we don't have an easy option to pass it to Python. 

Would it be a reasonable feature to implement?

**Comment by ritchie46** [comment]
Can you open this issue in that repo? This is not something we can fix here.

**Comment by aleewen** [comment]
I'm curious as to what happened here? Is there no way to be able to pass LazyFrames between Python and Rust?
