### ISSUE TITLE
Increase readability by making `col` a callable object supporting attribute and item access

### ISSUE THREAD

**Issue by char101** [pola-rs/polars#7950]
### Problem description

`pl.col` is probably the most used function in an expression. Since polars expression uses a functional style, more parantheses increases code reading and writing complexity since we need to match the brackets. Making `pl.col` supports attribute and item access might make the code more readable and faster to type.

For example:

```python
import polars as pl

class Column:
    pl_col = pl.col

    def __call__(self, *names):
        return Column.pl_col(*names)

    def __getattr__(self, name):
        return Column.pl_col(name)

    def __getitem__(self, name):
        if isinstance(name, (tuple, list)):
            return Column.pl_col(*name)
        return Column.pl_col(name)


pl.col = Column()

df = pl.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
})
df = df.select(pl.col.a * pl.col.b)
```

As a comparison, this is one example from the user guide

```python
df.select([
    pl.col("A").filter(pl.col("fruits").str.contains("^b.*")).sum(),
    (pl.col("B").filter(pl.col("cars").str.contains("^b.*")).sum() * pl.col("B").sum()).alias("some_compute()"),
])

# less parantheses
df.select([
    pl.col.A.filter(pl.col.fruits.str.contains("^b.*")).sum(),
    (pl.col.B.filter(pl.col.cars.str.contains("^b.*")).sum() * pl.col.B.sum()).alias("some_compute()"),
])

# although there are still more brackets, we can quickly find column names due to the use of []
df.select([
    pl.col["A"].filter(pl.col["fruits"].str.contains("^b.*")).sum(),
    (pl.col["B"].filter(pl.col["cars"].str.contains("^b.*")).sum() * pl.col["B"].sum()).alias("some_compute()"),
])
```

**Comment by ritchie46** [comment]
Quite sure this is a duplicate. TLDR, we don't want this as this only supports a subset of our column names. Spaces for instance break this.

There is nothing stopping you to use this in your codebase ofcourse.

**Comment by char101** [comment]
The space argument is valid if most column names have space. I believe that most column names don't contain space. So this is a 20% improvement for 80% use case.

Besides attribute access is not the only way to access the column. Attribute access is simply a convenience.

**Comment by char101** [comment]
Thanks, closing since this is a duplicate.
