### ISSUE TITLE
Allow multiple capture groups in str.extract_all()

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#7990]
### Problem description

Pandas supports multiple capture groups in a single regex, as follows:

```python
s = pd.Series(["one_1", "two_2", "three_3"])
s.str.extract("(\w+)_(\d+)")

       0  1
0    one  1
1    two  2
2  three  3
```

i.e. the different capture groups each form a new column. Polars does not support this:

```python
s = pl.Series(["one_1", "two_2", "three_3"])
s.str.extract(r"(\w+)_(\d+)")       # returns "one" "two" "three"
s.str.extract_all(r"(\w+)_(\d+)")   # returns full string as list item
```

**Comment by avimallu** [comment]
Is similar to: #3775?

**Comment by ghuls** [comment]
Your regex is wrong, you capture white spaces instead of words:

```python
In [123]: s.str.extract(r"(\w+)_(\d+)", 0)
Out[123]: 
shape: (3,)
Series: '' [str]
[
	"one_1"
	"two_2"
	"three_3"
]

In [124]: s.str.extract(r"(\w+)_(\d+)", 1)
Out[124]: 
shape: (3,)
Series: '' [str]
[
	"one"
	"two"
	"three"
]

In [125]: s.str.extract(r"(\w+)_(\d+)", 2)
Out[125]: 
shape: (3,)
Series: '' [str]
[
	"1"
	"2"
	"3"
]
```

**Comment by mcrumiller** [comment]
@ghuls sorry, you're right; I made a typo when writing up the issue. Fixed, and thank you.

@avimallu it's exactly the same. Has there been any progress on that issue since October?

**Comment by sm-Fifteen** [comment]
I'm still interested in seeing Pandas get that feature as well. I'm guessing the function would need a different name, though, so that the Rust and Python APIs can share the same names (as Rust doesn't have method overloading), which is why I suggested `extract_groups` in #3775, working in a similar way to `split_exact`.

The ergonomics of making those groups into columns might also still be wonky until #3859 is addressed.

@mcrumiller: As far as I'm aware, there hasn't been any work on this so far, no.

**Comment by mcrumiller** [comment]
@sm-Fifteen It is already part of pandas via `str.extract`. See my OP.

**Comment by ion-elgreco** [comment]
This is definitely a proper feature that Pandas has. Would be nice to have this in Polars as well.

**Comment by avimallu** [comment]
For those coming across this later, this is what I use now that I'm more familiar with Polars (in typical Polars's style):

```py
(
    pl.DataFrame({"foo": ["one_1", "two_2", "three_3"]})
    .with_columns([pl.col("foo").str.replace("(\w+)_(\d+)", f"${x}").alias(f"foo{x}") for x in (1, 2)])
)
```

to get

```py
shape: (3, 3)
┌─────────┬───────┬──────┐
│ foo     ┆ foo1  ┆ foo2 │
│ ---     ┆ ---   ┆ ---  │
│ str     ┆ str   ┆ str  │
╞═════════╪═══════╪══════╡
│ one_1   ┆ one   ┆ 1    │
│ two_2   ┆ two   ┆ 2    │
│ three_3 ┆ three ┆ 3    │
└─────────┴───────┴──────┘
```

Can even make it a function with some effort.

**Comment by ion-elgreco** [comment]
> For those coming across this later, this is what I use now that I'm more familiar with Polars (in typical Polars's style):
> 
> ```python
> (
>     pl.DataFrame({"foo": ["one_1", "two_2", "three_3"]})
>     .with_columns([pl.col("foo").str.replace("(\w+)_(\d+)", f"${x}").alias(f"foo{x}") for x in (1, 2)])
> )
> ```




Any reason you're using `str.replace` instead of 
```python
.with_columns([pl.col("foo").str.extract("(\w+)_(\d+)", x).alias(f"foo{x}") for x in (1, 2)])
```

**Comment by avimallu** [comment]
str.extract can be used too!
