### ISSUE TITLE
Fatal Python error: Illegal instruction

### ISSUE THREAD

**Issue by cisaacson** [pola-rs/polars#8000]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I start started using polars and am getting the illegal instruction above. I have seen this reported elsewhere but they don't fit my use case.

I am running on a new AMD5 7900 CPU with `Ubuntu 20.04.5 LTS` running on a `QEMU Virtual CPU version 2.5+` virtual machine. The virtualization is `AMD-V`.

As soon as I create a pl.DataFrame it crashes.

Since this is a very new CPU the earlier reports all talked about the version for older CPUs.

### Reproducible example

```python
import polars as pl
import numpy as np

def test():
  df = pl.DataFrame({'c1': [1,2,3], 'c2': ['a', 'b', 'c']})

test()
```

### Expected behavior

It should not crash and should create a dataframe.

### Installed versions

<details>

```
polars==0.16.18
```

</details>

**Comment by ghuls** [comment]
You might need a newer version of QEMU:
https://www.qemu.org/2022/12/14/qemu-7-2-0/

And make sure you have QEMU KVM installed.

**Comment by ritchie46** [comment]
QEMU probably does not virtualize all cpu instruction sets we compiled for (avx, sse, etc).

Try installing `polars-lts-cpu`, that should work.

**Comment by cisaacson** [comment]
Thanks very much for the quick response, we found the issue. The complete CPU instruction sets were not configured on the VM, we fixed that and the latest version runs perfectly. 

Great library, very fast.
