### ISSUE TITLE
Simple arithmetic operations on the "list" type columns 

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#8006]
### Problem description

It'd be nice for this code to work:

```python
df = pl.DataFrame({
    'x1': [[1,2],[3,4]],
    'x2': [10,20]
})

df.with_columns(scaled_x1 = pl.col('x1')/pl.col('x2'))

# Desired output: 

shape: (2, 3)
┌───────────┬─────┬─────────────┐
│ x1        ┆ x2  ┆ scaled_x1   │
│ ---       ┆ --- ┆ ---         │
│ list[i64] ┆ i64 ┆ list[f64]   │
╞═══════════╪═════╪═════════════╡
│ [1, 2]    ┆ 10  ┆ [0.1, 0.2]  │
│ [3, 4]    ┆ 20  ┆ [0.15, 0.2] │
└───────────┴─────┴─────────────┘
```

The idea here is that `x1` is column of arrays, and I want to divide each element in by the value in `pl.col('x2')`.

I'd be nice to support the basic arithmetic operations from numpy: `+`, `-`, `*`, `/`, `%`

**Comment by lunarspectrum** [comment]
This is a much needed feature. 

It seems that the expected syntax would be 
```python
df.with_columns(pl.col("x1").arr.eval(pl.element() / pl.col("x2")).alias("scaled_x1"))
```


A clunky way to get to the desired result can currently be accomplished by  
```python
pl.concat(
        [
            _df.with_columns(
                pl.col("x1").arr.eval(pl.element() / x2).alias("scaled_x1")
            )
            for x2, _df in df.groupby("x2")
        ]
    )
```

**Comment by itamarst** [comment]
I have implemented a working prototype (see branch `8006-list-arithmetic-part-2` in my fork), based on the work in #17823.

**Comment by itamarst** [comment]
Remaining work:

* [x] Existing list arithmetic still works
* [x] Support all numeric dtypes and all 5 arithmetic operations
* [ ] Test basic operations
* [ ] Test nested lists
* [ ] Test nulls (in the primitive numeric series)
* [ ] Test nulls (list items)
* [ ] RHS is primitive numeric, LHS is list (addition, subtraction, and multiplication only, division and remainder should fail)
* [ ] File follow-up issue for dates
* [ ] File follow-up issue for scalars

**Comment by itamarst** [comment]
Have made decent progress on making this work.
