### ISSUE TITLE
Native support for `pyarrow.RecordBatch`

### ISSUE THREAD

**Issue by cjackal** [pola-rs/polars#8007]
### Problem description

One of the loveliest design choice of polars I think is the seamless integration with / transition from many pyarrow-based codes. A project that I/O pyarrow Table can simply be wrapped with `pl.from_arrow` and you are ready to do polars. Same for pyarrow Array, but not RecordBatch. I request native support for `pyarrow.RecordBatch`, mostly on the pyarrow -> polars side.

- As a pyarrow RecordBatch is trivially pyarrow Table, (zero-copy) creation of polars DataFrame from a RecordBatch is trivial.
- From the viewpoint of API consistency: `pl.from_arrow` accepts both pyarrow Array and ChunkedArray, so it is natural for newcomers to expect the same for 'chunkless' Table (=RecordBatch) and Table.
- One example where this feature request makes some convenience gain: when we query from ODBC, the query result most likely have a memory layout similar to a iterator of RecordBatch (Many ODBC to arrow-compatible format tools provide the query result that way) so to convert it to polars one must import pyarrow and do RecordBatch -> Table -> DataFrame -> concat. The concatenation part is somewhat unavoidable but one may shorten the composition chain above if RecordBatch becomes a first class like pyarrow Table.

**Comment by alexander-beedie** [comment]
Done; will be available in the next release: 
* `df = pl.from_arrow( single_record_batch )`
* `df = pl.from_arrow( sequence_of_record_batches )`
