### ISSUE TITLE
Add map_frame as analog to map_dict in expression context

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8014]
### Problem description

`map_dict` allows a mapping of a dictionary in an expression context. It would be nice to be able to perform this mapping using a 2-column polars dataframe.

```python
import polars as pl
from polars import col

df = pl.DataFrame({
    "key": [1, 2, 3, 4, 5]
})
mapper = pl.DataFrame({
    "key": [1, 2, 3, 4, 5],
    "value": ['a', 'b', 'c', 'd', 'e']
})

```

We can do this with with `join` fairly easily:

```python
df.join(mapper, on="key", how="left").select("value")
```

but it would be nice if we could do this in an expression context in which `df` is not referenced at all, as in:

```python
df.select(
    col("key").map_frame(mapper, key="key") # not valid polars
)
```
The requirement being that `mapper` be a dataframe with a column named `key` (in that example).

I have several functions that use a mapper-frame and I currently have to join the dataframe on it, when I'd like to add the mapping into an expression array.

**Comment by cmdlineluser** [comment]
Regarding `dict(zip(...))` - `dict(mapper.iter_rows())` seems to perform better in my local testing.

**Comment by ritchie46** [comment]
This is too much magic to me. This should be a join. And joins are great because the optimizer understands those.

**Comment by mcrumiller** [comment]
@cmdlineluser thanks for that tip!
