### ISSUE TITLE
`None` converted to `[]` in series constructor

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#8027]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See below.

### Reproducible example

```python
# OK:
type(pl.Series([None, [42]])[0])
# => NoneType

# First element converted to Series:
type(pl.Series([None, []])[0])
# => polars.series.series.Series
```

### Expected behavior

First element should be None.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ghuls** [comment]
I think this wrong conversion is caused by some code in `any_values_to_list` in `polars/polars-core/src/series/any_value.rs`.

**Comment by jonashaag** [comment]
No, the bug seems to be here: https://github.com/pola-rs/polars/blob/afccc722fa7414af48952ecf117625a946b6df55/polars/polars-core/src/chunked_array/builder/list.rs#L665-L667

It doesn't distinguish null and `[]` values. Should we be passing `validity`? `.append_null()` and `.append_empty()` are correctly called by `impl FromIterator<Option<Series>> for ListChunked`.

```
[../chunked_array/builder/list.rs:666] &array = Int32[None, None]
[.../chunked_array/builder/list.rs:669] &array = LargeListArray[[], []]
```

**Comment by jonashaag** [comment]
OK I have a patch that fixes this, will need to clean it up a bit though. It correctly passes `validity` which fixes the issue
