### ISSUE TITLE
Deadlock with joblib/multiprocessing

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#8032]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Under specific circumstances, Polars enters a deadlock (?) and some operations are not possible anymore.

It happens when using joblib with `joblib.parallel_backend("multiprocessing")` and `n_jobs>1` and using sklearn transformers with Polars series. The default `joblib` backend or `n_jobs=1` (which disables multiprocessing) works fine.

I'm very sorry that so far I was unsuccessful in coming up with a minimal reproducer or any other reproducer that I can share.

I will share the `py-spy` stack traces in a comment below. The deadlocks are in processes 27146 and 27147: 27146 has already deadlocked, and 27147 will deadlock as soon as you run a specific operation on any `pl.Series`. Note that in here the 27147 contains a remote pdb waiting for a client.

In this situation, constructing a new series works fine, but performing `.is_null()` on any series hangs. 27146 is attempting to execute `.is_null()` (doesn't show in the stack).

### Reproducible example

```python
# Sorry, no reproducer :(
```

### Expected behavior

Should not deadlock.

### Installed versions

<details>

```
Polars: 0.16.17
Index type: UInt32
Platform: Linux-5.4.0-1099-aws-x86_64-with-glibc2.31
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 2.0.0
pyarrow: 7.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by jonashaag** [comment]
[stack.txt](https://github.com/pola-rs/polars/files/11171547/stack.txt)

**Comment by ritchie46** [comment]
https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html

**Comment by jonashaag** [comment]
Thanks for the pointer, I actually wasn't aware of this piece of documentation. It turns out that joblib will default to `fork` multiprocessing, exactly what's documented there.

FWIW, for the Mamba package manager I added a checkbox that requires people to read the [troubleshooting guide](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html) with some of the most common problems.

In my particular situation I'm trying to use Polars in a legacy codebase that already uses multiprocessing on a higher level. I'm not using multiprocessing to add more parallelization to the piece of code that uses Polars.

**Comment by ritchie46** [comment]
> In my particular situation I'm trying to use Polars in a legacy codebase that already uses multiprocessing on a higher level. I'm not using multiprocessing to add more parallelization to the piece of code that uses Polars.

Yeah, the only thing you could do is inform the authors there that `fork` is actually very, very risky to use and has huge assumptions about the libraries it uses.  I think it belongs in the 90s. In this day and age, you shouldn't assume that libraries run single threaded.

**Comment by sunmy2019** [comment]
> https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html

Link has gone

**Comment by ritchie46** [comment]
Updatte link: https://pola-rs.github.io/polars-book/user-guide/misc/multiprocessing/
