### ISSUE TITLE
Inconsistent inference of inner List types

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8038]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Lists are sometimes initialized as Int32, other tiimes they are Boolean.

### Reproducible example

```python
import polars as pl

pl.Series([[]]).dtype  # List(Int32)

pl.Series([[]], dtype=pl.List).dtype  # List(Boolean)

pl.DataFrame({'a': [[]]}).dtypes[0]  # List(Int32)

pl.DataFrame(schema={'a': pl.List}).dtypes[0]  # List(Boolean)
```

### Expected behavior

Consistent behaviour across initialization methods.

### Installed versions

master

**Comment by ghuls** [comment]
https://github.com/pola-rs/polars/issues/8027 is a similar report, but with a None and List value.
