### ISSUE TITLE
Panicked at 'attempt to divide by zero' error on 307MB parquet file

### ISSUE THREAD

**Issue by ThomasMAhern** [pola-rs/polars#8040]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have a 307MB parquet file and getting an error I didn't have before on smaller datasets. I'm getting an error:

```
thread '<unnamed>' panicked at 'attempt to divide by zero', .../polars-pip/src/executors/operations/function.rs:68:25

df_.lazy().collect(streaming=True)

wrap_df(ldf.collect()) PanicException: attempt to divide by zero
```
It usually happens right after an `.explode()` but then also other times when I try without it. 

When I filter down the results a bit, `.collect()` works, but `.collect(streaming=True)` doesn't. 

### Reproducible example

```python
import polars as pl

df = pl.scan_parquet('file.parquet')
(df.with_columns(pl.col('col1').str.split(' '))
   .explode(pl.col('col1')
   #10-15 more operations
   .collect(streaming=True)
   .fetch(5)
)
```
```


### Expected behavior

On smaller datasets, this code works fine, on larger datasets it chokes unless I filter it down a bit, and then only works if I don't use `streaming=True`.

### Installed versions

I'll have to fill this out once back at work

```

```

</details>

**Comment by alonme** [comment]
Are you sure this has to do with the size of the file?
Can you try removing columns / rows from the file and checking fi you can find what triggers the issue?

**Comment by ThomasMAhern** [comment]
Loading it is fine. `.fetch()` works without any operations. It also works when I filter it down. 
I do have a `.pipe(get_size)` function:
```
def get_size(df_):
  print(df_.collect(streaming=True))
  return df_
```
interspersed 4-5 times throughout. On the full dataset, the first one returns no problem, but it never makes it to the others. All of them work fine on smaller datasets, or when I've filtered the df down to a smaller size. The amount of rows affects it for sure, haven't tried limiting the columns yet, there are only 10. 

When it's filtered down to results from a single day (using `.is_between()`) instead of the full 30 days, it's large enough that `.collect(streaming=True)` causes it to panic error, but `.collect()` allows it to process fully without issue.
