### ISSUE TITLE
Inconsistent defaults for inferring integral types

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8041]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using `lit` gives different results than when initializing a Series.

`lit` has some built-in optimization that it will use `Int32` for small integers, and use `Int64` for integers that do not fit. We should do the same for inferring dtypes in the Series constructor, or use the same dtype everywhere (`Int64`?).

### Reproducible example

```python
import polars as pl

pl.select(pl.lit(1)).to_series().dtype  # Int32

pl.Series([1,1,1]).dtype  # Int64
```

### Expected behavior

Consistent behaviour across the two examples.

### Installed versions

master

**Comment by ritchie46** [comment]
Though a bit strange. This is acceptable. The `Series` creates an eager materialization.

The `select` runs on our query engine and there is an optimization that fits the minimal required dtype size for literals.

**Comment by stinodego** [comment]
Makes sense that functionality is different, as there is a difference between eager and lazy here.

However...  I don't know how the eager materialization works, but checking if the maximum value fits within `Int32` shouldn't be prohibitively expensive, right? And such a check can be skipped if the dtype is provided as input to the constructor.

**Comment by ritchie46** [comment]
> Makes sense that functionality is different, as there is a difference between eager and lazy here.
> 
> However... I don't know how the eager materialization works, but checking if the maximum value fits within `Int32` shouldn't be prohibitively expensive, right? And such a check can be skipped if the dtype is provided as input to the constructor.

It is much more expensive that what we do now. Or you have a double scan, or you must flush you whole materialization and start over. And because of the branch we don't have a memcopy aymore. Another thing is that suddenly the output schema changes depending on the data. In large `Series` this will be unexpected. 

The literal is fluent, it will adapt to the column dtypes, so that we never do an expensive cast if the literal would have fitted the columns dtype.

**Comment by stinodego** [comment]
Interesting! Thanks for the insight 😄
