### ISSUE TITLE
`polars.Expr.apply(..., return_dtype=None)` has dtype `Unknown` but docs says it assumes unchanged dtype

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#8042]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The docs for [`polars.Expr.apply`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.apply.html) states that the `return_dtype` parameter is "Dtype of the output Series. **If not set, polars will assume that the dtype remains unchanged.**".

However the dtype in the schema will be `Unknown`. 

The docstring was updated in [this commit](https://github.com/pola-rs/polars/commit/803dd5b9b43b33cacccb9e72dc643290dfdeb0f8#diff-ef10367537c7d109fbc7e36f7932120da961f51d828d5f6754f3f6336d365539).

It looks like it changed behavior somewhere between version 0.14.5 and 0.14.8. In 0.14.5 I get the type in the schema, in 0.14.8 I get `Unknown`. (0.14.6 gives an unrelated error and 0.14.7 was yanked so I couldn't test those).

`polars.Expr.map` has same behavior, but the docstring does not claim to keep the dtype if `return_dtype` is not given.

### Reproducible example

```python
import polars as pl

print(
pl.DataFrame({'x': [1,2,3]})
.lazy()
.with_columns([
  pl.col('x').apply(lambda e:e).alias('apply'),
  pl.col('x').map(lambda s:s).alias('map')
])
.schema
)
# Version 0.16.18: {'x': Int64, 'apply': Unknown, 'map': Unknown}
# Version 0.14.8:  {'x': <class 'polars.datatypes.Int64'>, 'apply': <class 'polars.datatypes.Unknown'>, 'map': <class 'polars.datatypes.Unknown'>}
# Version 0.14.5:  {'x': <class 'polars.datatypes.Int64'>, 'apply': <class 'polars.datatypes.Int64'>, 'map': <class 'polars.datatypes.Int64'>}
```

### Expected behavior

In above example, I would expect `apply` to have dtype `pl.Int64`. And it would be nice if `map` also had it.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.18
Index type: UInt32
Platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
---Optional dependencies---
numpy: <not installed>
pandas: <not installed>
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Can you make a PR?

**Comment by StefanBRas** [comment]
To remove the line from the docs? - Sure.
To change the behavior to what the docs say?  - Probably not, unfortunately.

My actual issue is that I wanted to use `Expr.map` to inject reporting of intermediate results into long query chains (similar to `Expr.inspect`, but it will change the schema even if it doesn't actually change the series.

**Comment by ritchie46** [comment]
The docs. :)

**Comment by ritchie46** [comment]
You can pass the dtype. Polars must know the dtype at all times. During an apply we cannot know the output type and a user must provide it.

**Comment by StefanBRas** [comment]
Made the PR now :)

> You can pass the dtype. Polars must know the dtype at all times. During an apply we cannot know the output type and a user must provide it.

I don't know the specific dtype, but I know it to be "the same as it was before". `Expr.inspect` is an example of a function using `Expr.map` that is custom python but where you always know the dtype. I think it would be valuable to have `return_dtype` optionally be a callable that takes the current dtype and returns a new one. I will make a feature request for this, but just wanted to hear if it's not possible.
