### ISSUE TITLE
Use `main` branch instead of `master`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8049]
This isn't really important, but I'll throw it out there anyway.

Some time ago, GitHub caused a stir by [changing](https://github.com/github/renaming/) their official standard branch name to `main`. Soon the other major git platforms followed suit ([GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/), [BitBucket](https://bitbucket.org/blog/moving-away-from-master-as-the-default-name-for-branches-in-git)).

Regardless of my personal feelings on this change, the result is that the previous standard is no longer a standard. About 80% of the projects I work on now use `main` as the standard branch, and about 20% still use `master`.

I think standardization is important. I regularly type `git rebase main` only to find out there is a different standard branch. This irks me.  `main` is now the standard, it's short and more descriptive than `master`. So I suggest switching.

Switching should be easy enough, adjust some settings in the repo, and maybe update some references here or there. I can look into that.

**Comment by ritchie46** [comment]
No opinion here. :+1:

**Comment by alexander-beedie** [comment]
Sure, go for it; makes sense :)

**Comment by stinodego** [comment]
All right - if there are no objections, I'll go ahead with this a few days after `0.17.0` has landed.

**Comment by zundertj** [comment]
No objection here, running into the same thing actually versus other projects.

**Comment by ghuls** [comment]
Probably it is a good idea to add an extra commit (e.g. to the `README.md`) to the old `master` branch after the switch to `main` to clearly indicate that `main` will be the new master for people that already have  a clone of the repo.

**Comment by stinodego** [comment]
GitHub actually provides a [rename branch](https://github.com/github/renaming/#rename-existing) option that takes care of pretty much everything! So I don't think that will be needed.
