### ISSUE TITLE
Python 3.11 support for connectorx

### ISSUE THREAD

**Issue by Roymprog** [pola-rs/polars#8054]
### Problem description

I'm trying to use `polars[connectorx]` in Python 3.11.2. Unfortunately, I cannot install it because the latest version of `connectorx` (0.3.1) is not release for python3.11. 
I opened an [issue ](https://github.com/sfu-db/connector-x/issues/483) on the repo to release a new version, as the latest prerelease versions do support python3.11.

A (temporary) solution could be to depend on `connectorx==0.3.2a2`, but I guess this is a bit of a risk.

**Comment by ghuls** [comment]
The Polars test enviroment already uses that version: https://github.com/pola-rs/polars/blob/master/py-polars/requirements-dev.txt
The default polars pip install process, probably installs the last full release by default, but you can install the alpha version yourself anyway.

**Comment by stinodego** [comment]
I'll close this as there is not much we can do about it.

We are hoping for a new release of `connectorx` soon, though the support for that project seems to be a little shaky at the moment.

As @ghuls mentioned, the best thing to do is to just define `connectorx` as a separate dependency and pin it to `connectorx==0.3.2a7`.

**Comment by stinodego** [comment]
@Roymprog `connectorx` has just released version `0.3.2` with Python 3.11 support, so you're good to go!
