### ISSUE TITLE
`json_extract` with string timestamps returns null

### ISSUE THREAD

**Issue by ayemjay** [pola-rs/polars#8060]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Extracting JSON values with timestamp in string format returns null

Due to upstream `arrow2` not implementing deserialization for string timestamps - proposed fix https://github.com/jorgecarleitao/arrow2/pull/1457

https://github.com/pola-rs/polars/blob/53d1abde81984f8813029f3a15946ec3caf188c9/polars/polars-ops/src/chunked_array/strings/json_path.rs#L76

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'json': ['"2023-04-07T12:23:34.000000001Z"']
})

dtype = pl.Datetime
out = df.with_columns(
    pl.col('json').str.json_extract(dtype)
)

print(out)
```

### Expected behavior

```
┌─────────────────────┐
│ json                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2023-04-07 12:23:34 │
└─────────────────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.18
Index type: UInt32
Platform: macOS-12.5-arm64-arm-64bit
Python: 3.11.2 (main, Feb 16 2023, 02:51:42) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: <not installed>
pandas: <not installed>
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Fixed upstream and merged here. Thanks @ayemjay
