### ISSUE TITLE
Inconsistent behavior in `pl.Expr` when using `over`

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#8064]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not sure if this is a "bug" per se, but it is inconsistent with expectations. It seems that expressions have different behavior after `over`. Specifically, after an over operation, I expect to be operating on the grouped series, which is the case in expressions like `sum` or `mean`, but not the case with expressions like `cumsum` or `exp_*`.

### Reproducible example

```python
import polars as pl
import datetime

t = pl.date_range(datetime.date(2023, 1, 1), datetime.date(2023, 1, 3))
df = pl.DataFrame({"t": t, "a": range(3), "b": "a"}).vstack(
    pl.DataFrame({"t": t, "a": range(5, 8), "b": "b"})
)

# these both result in mean of 7, i.e. over.mean is on the grouped series
df.with_columns(pl.col("a").sum().over("t").mean())
df.groupby("t").agg(pl.col("a").sum()).select(pl.col("a")).mean()

# cumsum is on the re-expanded series
df.with_columns(pl.col("a").sum().over("t").cumsum())

# would expect the following behavior
df.groupby("t").agg(pl.col("a").sum()).select(cumsum=pl.col("a").cumsum())
```

### Expected behavior

In the first example, the `over.mean` operation is on the grouped series, which is expected. In the second example, the `over.cumsum` is on the original "index" of the dataframe, not the "grouped" index.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.17
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.8 (default, Apr  8 2021, 19:39:59) 
[Clang 7.1.0 (tags/RELEASE_710/final)]
---Optional dependencies---
numpy: 1.22.3
pandas: 1.4.2
pyarrow: 8.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by zundertj** [comment]
The reason you see is that [`groupby` has by default `maintain_order=False`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.groupby.html#polars.DataFrame.groupby). That is, you might see this:

```
>>> df.groupby("t").agg(pl.col("a").sum())
shape: (3, 2)
┌────────────┬─────┐
│ t          ┆ a   │
│ ---        ┆ --- │
│ date       ┆ i64 │
╞════════════╪═════╡
│ 2023-01-03 ┆ 9   │
│ 2023-01-01 ┆ 5   │
│ 2023-01-02 ┆ 7   │
└────────────┴─────┘

```

or this:

```python
>>> df.groupby("t").agg(pl.col("a").sum())
shape: (3, 2)
┌────────────┬─────┐
│ t          ┆ a   │
│ ---        ┆ --- │
│ date       ┆ i64 │
╞════════════╪═════╡
│ 2023-01-02 ┆ 7   │
│ 2023-01-01 ┆ 5   │
│ 2023-01-03 ┆ 9   │
└────────────┴─────┘
```
or any other ordering possible.

`cumsum` depends on the ordering, so you will want `maintain_order=True`.

The `over` expression does not change the ordering, as that would not make any sense. But for groupby, most of the time, the ordering of the output does not matter, and it is faster to not do the sorting.

**Comment by zundertj** [comment]
The `cumsum` here:

```python
df.with_columns(
    s=(pl.col("a").sum().over("t")), 
    cs=(pl.col("a").sum().over("t")).cumsum(),
)
```
comes after the `over`, not before, what makes you think it should be part of the window expression? Column `cs` is the `cumsum` of column `s`, that makes sense given that is the only difference in how you defined those two expressions.

**Comment by zundertj** [comment]
>  After over, I would have expected to be operating on the grouped series.

`over` does the grouping on everything before, not on anything after. It would be very confusing if it would do both, and that would also kill the possibility to chain additional expressions as all expressions would be contaminated by a single `over`. I have to disagree here with you that it is not intuitive.

I don't think you can create your query in a single expression, as multiple `over` statements in expressions are not allowed. So you will need to create an in-between result:

```python
df.with_columns(s=pl.col("a").sum().over("t")).with_columns(cs=pl.col("s").cumsum().over("b"))
```

I agree it is not ideal.
