### ISSUE TITLE
Add groupby key when using `groupby.apply`

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#8067]
### Problem description

Can we add the groupby key to `groupby.apply`? In the below example, even if `func` knew that it is in a groupby, it is unable to use `agg_groups`.

```
import polars as pl


def func(df):
    return df.select(pl.col("a").sum())


df = pl.DataFrame({"a": range(3), "b": ["a", "a", "b"]})
df.groupby("b").apply(func)

┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
│ 1   │
└─────┘
```

**Comment by ghuls** [comment]
You can add it youself in the custom apply function:

```python
In [43]: def func(df):
    ...:     return df.select(pl.col("b"), pl.col("a").sum())
    ...: 
    ...: 
    ...: df = pl.DataFrame({"a": range(3), "b": ["a", "a", "b"]})
    ...: df.groupby("b").apply(func)
Out[43]: 
shape: (3, 2)
┌─────┬─────┐
│ b   ┆ a   │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 1   │
│ a   ┆ 1   │
│ b   ┆ 2   │
└─────┴─────┘
```

**Comment by ritchie46** [comment]
> Also the current behavior is inconsistent with groupby.agg, which includes the key.

It is not? It returns the whole group as a `DataFrame` this includes all columns thus the key as well. It is upon the caller to add it in that point. You should be able to write a function that is aware of the keys. 

Though in general I would definitely advise to not use `apply` at all. Materializing the groups is super expensive.

**Comment by ritchie46** [comment]
I will close this, as we will not do this.
