### ISSUE TITLE
Support window expressions in aggregations

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#8068]
### Problem description

Would it be possible to support window expressions in aggregations? In the below example, I want to first group the data by `b`, then take the sum of `a` within each `c`. This would especially be helpful to reuse expressions (e.g if `pl.col("a").sum().over(pl.col("c"))` is in a library function, the `groupby` or `over` somehow needs to know that the function uses an `over` already.

```
import polars as pl
from polars.exceptions import InvalidOperationError

df = pl.DataFrame({"a": range(3), "b": ["a", "a", "b"], "c": ["a", "b", "c"]})
print(df)
# groupby with over
try:
    print(df.groupby("b").agg(pl.col("a").sum().over(pl.col("c"))))
except InvalidOperationError:
    print("failed")
# over with over
try:
    print(df.select(pl.col("a").sum().over(pl.col("b")).mean().over(pl.col("c"))))
except InvalidOperationError:
    print("failed")

# this works, but does not support code reuse (and use of last is not ideal).
print(
    df.groupby("b")
    .agg(pl.col("c").last(), pl.col("a").sum())
    .groupby("c")
    .agg(pl.col("b").last(), pl.col("a").mean())
)
```

**Comment by zundertj** [comment]
This is the same ask as in #6676. Please comment there and/or upvote. Closing this issue as duplicate.
