### ISSUE TITLE
Add `drop_nans` for DataFrames/LazyFrames like `drop_nulls`

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8077]
### Problem description

Currently `drop_nans` exist for expressions. I would `drop_nans` could also exist for DataFrames and LazyFrames, like `drop_nulls`.

Here is an example for it:

```python
import numpy as np
import polars as pl

df = pl.DataFrame({
    "a": np.array([1, 2, np.nan, 4, 5]), 
    "b": np.array([1, np.nan, 3, 4, np.nan])})

df.drop_nans() # new
```

what are your thoughts? were there reasons to make `drop_nans` available only for expressions?

There is the possibility to filter out these rows using `is_nans()`, so this is not a blocking point.

**Comment by ritchie46** [comment]
Polars doesn't regard `NaN` as anything more special than `inf`, `-inf`, `0.0` etc. We regard it as just a member of the floating point system. `Nulls` on the other hand are the missing data representation of polars, that's why they are allowed to be more prevalent in the API.

Dropping `NaNs` is still easy:

```python
df.filter(pl.col(pl.Float64).is_not_nan())
```

**Comment by lucazanna** [comment]
I understand about not adding methods for something that does not have a special role in Polars.

I did a quick comparison for the methods available for null, nan, and inf. (in table below, E= exist, M=missing).

A couple of thoughts:
- does it make sense to add `null_count` for Lazyframes?
- nan has more methods than inf, but that makes sense. dropping nans or filling nan will be more common than doing those operations with infs


```
+---------------------+------+-----+------+
| method              | null | nan | inf  |
+---------------------+------+-----+------+
| drop_ in DataFrame  | E    | M   | M    |
| drop_ in LazyFrame  | E    | M   | M    |
| drop_ in Expr       | E    | E   | M    |
| drop_ in Series     | E    | E   | M    |
| is_ in Expr         | E    | E   | E    |
| is_ in Series       | E    | E   | E    |
| is_not_ in Expr     | E    | E   | M    |
| is_not_ in Series   | E    | E   | M    |
| fill_ in DataFrame  | E    | E   | M    |
| fill_ in LazyFrame  | E    | E   | M    |
| fill_ in Expr       | E    | E   | M    |
| fill_ in Series     | E    | E   | M    |
| _count in DataFrame | E    | M   | M    |
| _count in LazyFrame | M    | M   | M    |
| _count in Expr      | E    | M   | M    |
| _count in Series    | E    | M   | M    |
+---------------------+------+-----+------+
```
