### ISSUE TITLE
Unexpected behavior in clip

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#8090]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Clip doesn't seem to work across data types.

### Reproducible example

```python
a = polars.from_dict({"a":[1,1,2,2], "b":['{"my_field": "quack"}','{"my_field": "quack"}','{"my_field": "quack"}','{"my_field": "quack"}']})
a.with_columns([polars.col("a").clip(1.5, 1.6)])

This will return 1,1,1,1 for the a column.
```

### Expected behavior

The a column should maybe be 1.5, 1.5, 1.6, 1.6?

### Installed versions

<details>

```
0.16.15
```

</details>

**Comment by ritchie46** [comment]
Yeah.. should the argument type cast the whole column? What if the column is a float and users pass integers as clip args? I am not sure about this one.

**Comment by marsupialtail** [comment]
I think maybe you can raise an error or warning and say the types are incongruent when this happens

**Comment by stinodego** [comment]
Closing in favor of #11385
