### ISSUE TITLE
str.contains (probably other things too) doesn't work when starting from `pl.lit`

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#8120]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Let's say I have a df with strings in a column called `a`. I have a new string and I want to see if the strings in my df are a subset of the new string so I use `pl.lit("newstring").str.contains(pl.col('a'))` but then it gives back either too many results or no results.  I can't figure out how to make a repr that returns nothing but in my real data I'm seeing that. I'm guessing fixing the former fixes the latter so it probably isn't helpful to figure that out.

### Reproducible example

```python
df=pl.DataFrame({'a':['abc', 'xyz']})

df.filter(pl.col("a").str.contains('ab')) ##This works

df.filter(pl.lit('abcd').str.contains(pl.col('a'))) ## This returns all rows
```

If we make a new column first then it'll work like this:

```
df.with_columns(strsearch=pl.lit('abcd')).filter(pl.col('strsearch').str.contains(pl.col('a')))
```

### Expected behavior

Should get same results between leading with `pl.lit` and creating a column in advance

### Installed versions

<details>

```
---Version info---
Polars: 0.16.13
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Perhaps of relevance: https://github.com/pola-rs/polars/issues/6360

```
>>> df
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
│ abc │
│ xyz │
└─────┘
```
```
>>> df.select(pl.lit('abcd'))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ abcd    │
└─────────┘
```
```
>>> df.select(pl.lit('abcd').str.contains(pl.col('a')))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ true    │
└─────────┘
```
As it has a height of `1` - it looks like it's comparing against the first row in `a` e.g.
```
>>> df.select(pl.lit('abcd').str.contains('abc'))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ true    │
└─────────┘
```
```
>>> df.select(pl.lit('wxyz').str.contains(pl.col('a')))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ false   │
└─────────┘
```
```
>>> df.select(pl.lit('wxyz').str.contains(pl.col('a').tail(1)))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ bool    │
╞═════════╡
│ true    │
└─────────┘
```

**Comment by deanm0000** [comment]
@cmdlineluser  that makes a lot of sense so I guess the fix is to make pl.lit broadcast to full height in filter context unless that breaks something else.

**Comment by deanm0000** [comment]
Forget when but this got fixed at some point.
