### ISSUE TITLE
```return_dtype``` does not work in group context

### ISSUE THREAD

**Issue by qqlearn123** [pola-rs/polars#8127]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

For the code below, the a_2 column in the result contains all null.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3, 1], "b": ["a", "b", "c", "c"]})

df.with_columns(pl.col("a").apply(lambda x: x * 2 + x.sum(), return_dtype=pl.Int64).over("b").alias("a_2"))
```

### Expected behavior

If ```return_dtype``` is not specified, the result is correct.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ghuls** [comment]
A `over` operation is actually a grouby operation, so the expected return dtype is `pl.List(pl.Int64))`:

```python
In [199]: import polars as pl
     ...: 
     ...: df = pl.DataFrame({"a": [1, 2, 3, 1], "b": ["a", "b", "c", "c"]})
     ...: 
     ...: df.with_columns(pl.col("a").apply(lambda x: x * 2 + x.sum(), return_dtype=pl.List(pl.Int64)).over("b").alias("a_2"))
Out[199]: 
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ a_2 │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ a   ┆ 3   │
│ 2   ┆ b   ┆ 6   │
│ 3   ┆ c   ┆ 10  │
│ 1   ┆ c   ┆ 6   │
└─────┴─────┴─────┘
```
