### ISSUE TITLE
Proper testing for `DataFrame/Series` initialization and AnyValue conversion

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8136]
I'm going to create a whole bunch of standard test series/dataframe fixtures and throw those through our conversion logic.

Simple bugs like #8135 should really not get through our tests ever.

**Comment by alexander-beedie** [comment]
We should extend the parametric tests; I've just enhanced the `dataframes` generation function locally such that they randomly flip between initialising data column-wise (the current behaviour) _or_ row-wise (new). This _immediately_ found the #8135 bug, without even having to write any new tests (and possibly another one that I'm about to double-check)  :-\

**Comment by alexander-beedie** [comment]
@stinodego I think the update to parametric testing could probably be considered to close this, but I'll leave it open in case you have some additional plans  ;)

**Comment by stinodego** [comment]
Thanks for that update - I'll leave this open for a moment. I had some more concrete ideas - I'm looking into parametric tests tomorrow and then I'll see if I still want to go ahead with that.

**Comment by stinodego** [comment]
I'll close this for now.
