### ISSUE TITLE
Wrong schema in lazy mode when unnesting struct columns

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#8141]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Wrong schema in lazy mode when unnesting struct columns.

)Originally reported on Discord.)

### Reproducible example

```python
In [24]: pl.DataFrame({"a": [1, 2, 3], "b": ["4-4", "5-5", "6-6"]}).lazy().with_columns(
    ...:     pl.col("b").str.split("-").arr.to_struct().struct.rename_fields(["c", "d"])
    ...: ).unnest("b").schema
Out[24]: {'a': Int64}

In [25]: pl.DataFrame({"a": [1, 2, 3], "b": ["4-4", "5-5", "6-6"]}).lazy().with_columns(
    ...:     pl.col("b").str.split("-").arr.to_struct().struct.rename_fields(["c", "d"])
    ...: ).unnest("b").collect().schema
Out[25]: {'a': Int64, 'c': Utf8, 'd': Utf8}
```

### Expected behavior

Output schema should be `{'a': Int64, 'c': Utf8, 'd': Utf8}` on lazy dataframe.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.1
Index type: UInt32
Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.10
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Yes, we don't know the schema as it depends on the data. I think we should accept an optional schema here so the user can provide it to continue with the lazy API.

**Comment by ritchie46** [comment]
Ah, I see we already have this. You must set the `upper_bound` to the number of fields you expect.

**Comment by ghuls** [comment]
In the `.struct.rename_fields(["c", "d"])` case you could argue that there are 2 fields in the struct, as if less rename fields are specified, they are not outputted (although if you specify more of them than there are, no extra null columns are added):

```python
In [141]: pl.DataFrame({"a": [1, 2, 3], "b": ["4-4", "5-5", "6-6"]}).lazy().collect().with_columns(
     ...:     pl.col("b").str.split("-").arr.to_struct().struct.rename_fields(["c",])
     ...: ).unnest("b").schema
Out[141]: {'a': Int64, 'c': Utf8}

In [142]: pl.DataFrame({"a": [1, 2, 3], "b": ["4-4", "5-5", "6-6"]}).lazy().collect().with_columns(
     ...:     pl.col("b").str.split("-").arr.to_struct().struct.rename_fields(["c", "d"])
     ...: ).unnest("b").schema
Out[142]: {'a': Int64, 'c': Utf8, 'd': Utf8}

In [143]: pl.DataFrame({"a": [1, 2, 3], "b": ["4-4", "5-5", "6-6"]}).lazy().collect().with_columns(
     ...:     pl.col("b").str.split("-").arr.to_struct().struct.rename_fields(["c", "d", "e"])
     ...: ).unnest("b").schema
Out[143]: {'a': Int64, 'c': Utf8, 'd': Utf8}
```

**Comment by ritchie46** [comment]
I think we can close this right? It is upon the user to set the `upper_bound`.

**Comment by sclamons** [comment]
I don't think this is solved. You can get this same bug through paths that don't `use to_struct()` and therefore don't give you a chance (as far as I can tell) to set an `upper_bound`. For example, with `map_elements()`:

```
In [30]: df = pl.LazyFrame({"X": [1,10]})

In [31]: unnested_df = df.with_columns(some_stats = pl.col("X").map_elements(lambda x: {"foo": x*x}, return_dtype=pl.Struct).struct.rename_field
    ...: s(["squared"])).unnest("some_stats")

In [32]: unnested_df = df.with_columns(
    ...:     some_stats = pl.col("X")
    ...:     .map_elements(lambda x: {"foo": x*x}, return_dtype=pl.Struct)
    ...:     .struct.rename_fields(["squared"])
    ...: ).unnest("some_stats")

In [33]: unnested_df.collect()
Out[33]: 
shape: (2, 2)
┌─────┬─────────┐
│ X   ┆ squared │
│ --- ┆ ---     │
│ i64 ┆ i64     │
╞═════╪═════════╡
│ 1   ┆ 1       │
│ 10  ┆ 100     │
└─────┴─────────┘

In [34]: unnested_df.collect_schema()
Out[34]: Schema([('X', Int64)])
```

This one especially surprised me because I'm explicitly setting struct field names! Polars should in principle know the unnested columns' names.

I wouldn't be surprised if there are other ways to make structs with this same problem.

**Comment by sclamons** [comment]
For now, I've found a bit of a hack to get around this. In the code above, if I instead instantiate `df` with 

```
df = pl.LazyFrame({"X": [1,10]}).with_columns(squared=0)
```

then `collect_schema()` returns the expected schema. This works, but seems pretty fragile, and requires knowing the column names ahead of time.

**Comment by cmdlineluser** [comment]
@sclamons I did stumble into some similar issues recently: https://github.com/pola-rs/polars/issues/17181 https://github.com/pola-rs/polars/issues/16460

It made me wonder if an empty `pl.Struct` should actually be allowed as a valid dtype in that case?
