### ISSUE TITLE
Cannot create series from Int16

### ISSUE THREAD

**Issue by morganhiggin2** [pola-rs/polars#8164]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When using ParquetReader to read parquet file, read works on every other type in the file except Int16, when executing the following code:

'''
let mut file = std::fs::File::open("./src/data.snappy.parquet").unwrap();
let args = ScanArgsParquet::default();
let ldf = LazyFrame::scan_parquet("./src/data.snappy.parquet", args).unwrap();
ldf.limit(10).collect().unwrap()
```

with the attached parquet [
[part-00000-dddc89a7-a797-4208-9c5a-a07de271865c.c000.snappy.parquet.zip](https://github.com/pola-rs/polars/files/11203873/part-00000-dddc89a7-a797-4208-9c5a-a07de271865c.c000.snappy.parquet.zip)
](url)

looking into the polars code, in the function
    pub(crate) unsafe fn try_from_arrow_unchecked
located in read.rs,
it seems that it reaches the end of the match statement, not sure if this case is being handles or some other error is occurring. I have avoid the issue at the moment by casting each field to a utf8, but this seems to be an internal issue.


### Reproducible example

'''
let mut file = std::fs::File::open("./src/data.snappy.parquet").unwrap();
let args = ScanArgsParquet::default();
let ldf = LazyFrame::scan_parquet("./src/data.snappy.parquet", args).unwrap();
ldf.limit(10).collect().unwrap()
```

with the attached parquet [
[part-00000-dddc89a7-a797-4208-9c5a-a07de271865c.c000.snappy.parquet.zip](https://github.com/pola-rs/polars/files/11203873/part-00000-dddc89a7-a797-4208-9c5a-a07de271865c.c000.snappy.parquet.zip)
](url)

### Expected behavior

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot create series from Int16"))'

### Installed versions

<details>
polars = {version="0.28.0", features = ["parquet", "lazy", "horizontal_concat", "dtype-full"]}
tokio = {version = "1.27.0", features = ["macros", "rt", "rt-multi-thread"]}
parquet = "35.0.0"
polars-io = "0.28.0"
arrow-array = "35.0.0"
</details>

**Comment by ritchie46** [comment]
Did you activate `dtype-i16` feature?

**Comment by morganhiggin2** [comment]
Thanks, that solved it. May I ask why this is a separate feature instead of being included like the other types, such as i32 are?
