### ISSUE TITLE
`polars.Expr.take` returns `null` if `ComputeError: index out of bounds`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#8171]
### Problem description

Sometimes you may have groups with different numbers of rows. It would be nice if `polars.Expr.take` could just return a `null` when `index out of bounds`.

```python
df = pl.DataFrame(
{
        "group": [
            "one",
            "one",
            "one",
            "two",
            "two",
        ],
        "value": [1, 98, 2, 3, 99],
    }
)
df.groupby("group", maintain_order=True).agg(pl.col("value").take(2))

shape: (2, 2)
┌───────┬───────┐
│ group ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ one   ┆ 2     │
│ two   ┆ null  │
└───────┴───────┘
```

For now:
```
df.groupby("group", maintain_order=True).agg(pl.col("value").shift(-2).first())
```

**Comment by cmdlineluser** [comment]
[`.arr.get`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.get.html#polars.Expr.arr.get) returns `null` instead of raising, which may be another option:
```
>>> df.groupby("group", maintain_order=True).agg(pl.col("value").list().arr.get(2))
shape: (2, 2)
┌───────┬───────┐
│ group ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ one   ┆ 2     │
│ two   ┆ null  │
└───────┴───────┘
```

**Comment by uditrana** [comment]
I would love for take to have this as a flag though... I think its a pretty reasonable and common use case! `take` syntactically is more canonical for operating on columns instead of treating it as an array imo
