### ISSUE TITLE
`fill_null` a `pl.Categorical` will insert a new category even if the cat is the same

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#8174]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When using `fill_null` on a `pl.Categorical`, the filled values will be a new cat even if the cat already exists. 

### Reproducible example

```python
pl.DataFrame(
    {'col': ['a', None, 'a']}, schema={'col': pl.Categorical}
).fill_null('a').with_columns(
    pl.col('col').to_physical().alias('code')
)

shape: (3, 2)
┌─────┬──────┐
│ col ┆ code │
│ --- ┆  --- │
│ cat ┆  u32 │
╞═════╪══════╡
│   a ┆    0 │
│   a ┆    1 │
│   a ┆    0 │
└─────┴──────┘
```

```python
pl.DataFrame(
    {'col': ['a', None, 'a']}, schema={'col': pl.Categorical}
).fill_null('a').get_column('col').value_counts()

shape: (2, 2)
┌─────┬────────┐
│ col ┆ counts │
│ --- ┆    --- │
│ cat ┆    u32 │
╞═════╪════════╡
│   a ┆      2 │
│   a ┆      1 │
└─────┴────────┘
```

### Expected behavior

There should be only one `a` or all `a` should have the same physical 

### Installed versions

<details>
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3-arm64-arm-64bit
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) 
[Clang 12.0.1 ]
---Optional dependencies---
numpy: 1.22.3
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.0
xlsx2csv: 0.8.1
xlsxwriter: <not installed>
</details>

**Comment by alexander-beedie** [comment]
(It's probably both, but I've updated the tags for you ;)
