### ISSUE TITLE
Regression: groupby operations fails when crossing DST

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#8176]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

TLDR: there's an ambiguous time bug in some groupby operations. Only appears when period is passed with "days", not with hours only. 

Issue when using `timedelta` in groupby operations where the period is > 24h. Both `groupby_rolling` and `groupby_dynamic` are affected. 
It seems that passing the number of hours directly makes it works. However, passing the period as "1d" breaks things.
A gut feeling is that it may be due to `timedelta` converting to a day when hours > 24. 

Seems that the regression has been introduced after `0.16.14`.  i.e it works on `0.16.14`

Very similar to https://github.com/pola-rs/polars/issues/7434 i believe. 

@MarcoGorelli (Sorry i'm back with another time zone bug 🙃) i think you did make the fix for the previous one so perhaps you have a better understanding of what could have gone wrong!

The exception:
```bash
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("datetime '2021-11-07 01:00:00' is ambiguous in time zone 'US/Central'. Ambiguous datetimes are not yet supported"))
```

### Reproducible example

```python
import polars as pl
from datetime import datetime, timedelta

t2 =pl.date_range(datetime(2021,11,1), datetime(2021,11,30), "1m", time_zone="US/Central")
df = pl.DataFrame({"time":t2, "value": range(len(t2))})
df.groupby_rolling("time", period="24h", offset="0h").agg(pl.col("value").quantile(0.25))  # works
df.groupby_rolling("time", period=timedelta(hours=24), offset="0h").agg(pl.col("value").quantile(0.25))  # doesn't work
df.groupby_rolling("time", period="1d", offset="0h").agg(pl.col("value").quantile(0.25))  # doesn't work
```

### Expected behavior

that we can pass "days" (or more) in the period and it works.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.2.1-x86_64-i386-64bit
Python: 3.10.11 (main, Apr  7 2023, 07:31:31) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---

numpy: 1.23.3
pandas: 1.5.3
pyarrow: 10.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

so, `period="24h"` works, but `period=timedelta(hours=24)` doesn't? I'll take a look

**Comment by tim-habitat** [comment]
>so, period="24h" works, but period=timedelta(hours=24) doesn't? I'll take a look

exactly, bu i think it doesn't because `timedelta(hours=24)` is equivalent to `period="1d"` which doesn't work

**Comment by MarcoGorelli** [comment]
>  timedelta(hours=24) is equivalent to period="1d"

not quite - `'1d'` is one calendar day, which could be 25 hours or 23 hours. `'1d'` is tz-aware, whereas `timedelta(hours=24)` isn't

**Comment by MarcoGorelli** [comment]
OK, got it: this is what happens in Python if you make `timedelta(hours=24)`:
```python
In [1]: timedelta(hours=24)
Out[1]: datetime.timedelta(days=1)
```

So this is equivalent to doing
```python
df.groupby_rolling("time", period="1d").agg(pl.col("value").quantile(0.25))
```

So in fact, `timedelta(hours=24)` is indistinguishable from `timedelta(days=1)`. Not sure much can be done here

As for why `'1d'` raises: if you start on `2021-11-08 01:00:00 CST` and go back 1 day, does that mean going back to
- `2021-11-07 01:00:00 CDT`, or
- `2021-11-07 01:00:00 CST`
?

Until there's a way to deal with ambiguous datetimes, I don't think much can be done here (related, would appreciate your thoughts on https://github.com/pola-rs/polars/pull/8087 @tim-habitat , thanks 🙏)

**Comment by tim-habitat** [comment]
Ah that makes a lot of sense! agreed - might be tricky to make a decision for the user. 
I think from now on, on my side i'll be using only `hours` to reduce ambiguity in those rolling ops (if they are dst shifting at least) and as it's easy enough to do something like `hours = int(timedelta(days=1) / timedelta(hours=1))`

re https://github.com/pola-rs/polars/pull/8087 : Love it - i think it's a super elegant way to open the possibility of using `infer` for ambiguous times! (would almost be tempted to keep your example https://github.com/pola-rs/polars/issues/6672#issuecomment-1501147838 somewhere in the docs - i'm sure i'm gonna need it someday and will be looking for it 😅 )

Thanks again for looking into and your contribution - appreciate it 🙏

**Comment by MarcoGorelli** [comment]
thanks again for the issue - closing then as it seems resolved

**Comment by felixp72** [comment]
Hello, stumbled upon the same hours vs days problem for `group_by_dynamic` function. Using period in hours does not take into account DST, while using period in days does. 

Wanted to raise this since the doc-string does not specify this implicit behaviour, and was quite a headache to figure out. I would advocate for making the DST behaviour uniform, meaning by default all periods are either DST aware or not DST aware. Whichever that default may be I see it better than having hidden implicit behaviour. What is the stance of the team on this, are there any plans to address this?

Snipeet showcasing what I am referring to:

```python
    from datetime import datetime

    import polars as pl

    df = pl.DataFrame(
        {
            "ts": pl.datetime_range(
                datetime(2024, 3, 30),
                datetime(2024, 4, 2),
                "1h",
                time_zone="Europe/London",
                eager=True,
            ),
            "value": 1,
        }
    )

    def counts(every):
        return df.group_by_dynamic("ts", every=every).agg(pl.col("value").sum()).sort("ts")

    print(counts("1d"))  # dst day has 23
    print(counts("24h"))  # dst day has 24

```
