### ISSUE TITLE
`pl.row_nr()`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#8179]
### Problem description

If we want to do something for a particular row number:
```
df = pl.DataFrame({"val": ["a", "b", "c"]})
```
We can use `.with_row_count` and `.drop`
```
df.with_row_count().with_columns(
   pl.when(pl.col("row_nr") == 1).then(10).otherwise(20)
).drop("row_nr")
```
```
shape: (3, 2)
┌─────┬─────────┐
│ val ┆ literal │
│ --- ┆ ---     │
│ str ┆ i32     │
╞═════╪═════════╡
│ a   ┆ 20      │
│ b   ┆ 10      │
│ c   ┆ 20      │
└─────┴─────────┘
```
To avoid the need for a `.drop` we can use `pl.arange`
```
df.with_columns(
   pl.when(pl.arange(0, pl.count()) == 1).then(10).otherwise(20)
)
```
Or `pl.first().cumcount`
```
df.with_columns(
   pl.when(pl.first().cumcount() == 1).then(10).otherwise(20)
)
```
It seems like a `pl.row_nr()` would be more understandable:
```
df.with_columns(
   pl.when(pl.row_nr() == 1).then(10).otherwise(20)
)
```
~~Also, if the name defaulted to `row_nr` perhaps there would be no need for a separate `.with_row_count` method?~~

~~It's not much more typing.~~

**Comment by gab23r** [comment]
`with_row_count` inserts the column in the begining of the dataframe, I found that super useful. This is linked to #6270

**Comment by cmdlineluser** [comment]
@gab23r Ah! That's why it exists as a method - thank you for pointing that out. 

`.select(pl.row_nr(), pl.all())` would definitely be less appealing for that particular use-case.

**Comment by mcrumiller** [comment]
The issue with using it in an expression is if multiple columns require access to the row count, you end up doing a `pl.arange()` multiple times, which seems wasteful to me--unless of course this is somehow optimized away and only generated once. Can anyone answer this one?
