### ISSUE TITLE
NULL inconsistency: (in)equality propogation

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#8182]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Follow up from discussion on #7595 to split issues on `null` value related inconsistencies into their own threads. I am going to show comparisons across `polars`, R (`data.table` and `dplyr`, which essentially uses R's built-in logic under the hood) and SQL (via `duckdb`, simply because that is the easiest). Extensive discussions on `NULL` values across different systems and their concepts are there [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1474114725) and [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1475680370). 

This one is associated with propagating `null` values across equality and inequality comparisons.

### Reproducible example

```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> print(
...     df.with_columns(
...         a_b_equal     = pl.col("a") == pl.col("b"),
...         a_b_not_equal = pl.col("a") != pl.col("b")))
shape: (1, 4)
┌─────┬──────┬───────────┬───────────────┐
│ a   ┆ b    ┆ a_b_equal ┆ a_b_not_equal │
│ --- ┆ ---  ┆ ---       ┆ ---           │
│ i64 ┆ f32  ┆ bool      ┆ bool          │
╞═════╪══════╪═══════════╪═══════════════╡
│ 42  ┆ null ┆ false     ┆ true          │
└─────┴──────┴───────────┴───────────────┘
```

### Expected behavior

This differs from behavior in R and SQL where the presence of NA/NULL (as defined in those languages) is propogated:

```
> library(data.table)
> options(datatable.print.class = TRUE)
> DT = data.table(
+   a = 42,
+   b = NA_integer_
+ )
> DT[, .(a, b, a_b_equal = a==b, a_b_not_equal = a!=b)]
       a     b a_b_equal a_b_not_equal
   <num> <int>    <lgcl>        <lgcl>
1:    42    NA        NA            NA
> 
> library(dplyr)
> DT |>
+   as_tibble() |>
+   mutate(a_b_equal = a==b,
+          a_b_not_equal = a!=b)
# A tibble: 1 × 4
      a     b a_b_equal a_b_not_equal
  <dbl> <int> <lgl>     <lgl>        
1    42    NA NA        NA   
```

In SQL, I use DuckDB on the Polars DataFrame created in the example:

```
>>> import polars as pl
>>> import duckdb as db
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> db.query("""
...     SELECT a, b, a=b AS a_b_equal, a!=b AS a_b_not_equal
...     FROM df""")
┌───────┬───────┬───────────┬───────────────┐
│   a   │   b   │ a_b_equal │ a_b_not_equal │
│ int64 │ float │  boolean  │    boolean    │
├───────┼───────┼───────────┼───────────────┤
│    42 │  NULL │ NULL      │ NULL          │
└───────┴───────┴───────────┴───────────────┘
```

Pandas also seems to behave the exact same way (by default, surprisingly, contrary to comments in the related issue):

```
>>> import pandas as pd
>>> df = pd.DataFrame({"a": [42], "b": [None]}, dtype="Int64")
>>> df.assign(
...     a_b_equal=lambda x: x.a==x.b,
...     a_b_not_equal=lambda x: x.a!=x.b)
    a     b  a_b_equal  a_b_not_equal
0  42  <NA>       <NA>           <NA>
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by CameronBieganek** [comment]
I definitely agree that `42 == null` and `42 != null` should propagate `null`. Quoting @ritchie46:

> Missing data is not a number and any operation on it remains missing.

...from [this comment](https://github.com/pola-rs/polars/issues/8186#issuecomment-1509888316).

**Comment by CameronBieganek** [comment]
Regarding the Pandas example, it depends on how you create the dataframe. Apparently the constructor you used used the experimental `NA` type in Pandas. But most of the time you get `np.nan` instead of `NA`:

```python
>>> df = pd.DataFrame({"a": [1, 2], "b": [1, None]})
>>> df
   a    b
0  1  1.0
1  2  NaN
>>> df.assign(
...     a_b_equal = lambda x: x.a == x.b,
...     a_b_not_equal = lambda x: x.a != x.b
... )
   a    b  a_b_equal  a_b_not_equal
0  1  1.0       True          False
1  2  NaN      False           True
```
