### ISSUE TITLE
NULL inconsistency: empty product should be 1, not `null`

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#8184]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Follow up from discussion on #7595 to split issues on `null` value related inconsistencies into their own threads. I am going to show comparisons across `polars`, R (`data.table` and `dplyr`, which essentially uses R's built-in logic under the hood) and SQL (via `duckdb`, simply because that is the easiest). Extensive discussions on `NULL` values across different systems and their concepts are there [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1474114725) and [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1475680370). 

This one is associated with making sure that an empty product is 1 (the multiplicative identity), [matching convention](https://en.wikipedia.org/wiki/Empty_product).

### Reproducible example

```python
>>> import polars as pl
>>> pl.Config.set_tbl_cols(42)
<class 'polars.config.Config'>
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> print(
...     df.with_columns(
...         prod = pl.col("b").product()
...     ))
shape: (1, 3)
┌─────┬──────┬──────┐
│ a   ┆ b    ┆ prod │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ f32  ┆ f32  │
╞═════╪══════╪══════╡
│ 42  ┆ null ┆ null │
└─────┴──────┴──────┘
```

### Expected behavior

This differs from behavior in R and pandas, but matches behavior in SQL (duckdb). In this case, I think a design decision needs to be made to whether Polars should match SQL behavior, or R/pandas.

In R:
**Note: R by default does not remove `NA` values when applying a numerical aggregation, and that is why `na.rm=TRUE` must be specified.** My understanding is that SQL, Pandas and Polars does this by default.

```
> library(data.table)
> options(datatable.print.class = TRUE)
> DT = data.table(
+   a = 42,
+   b = NA_integer_
+ )
> DT[, .(a, b, prod = prod(b, na.rm=TRUE))]
       a     b  prod
   <num> <int> <num>
1:    42    NA     1
> 
> library(dplyr)
> DT |>
+   as_tibble() |>
+   mutate(
+     prod = prod(b, na.rm=TRUE))
# A tibble: 1 × 3
      a     b  prod
  <dbl> <int> <dbl>
1    42    NA     1
```

**SQL matches Polar's behavior:**
```
>>> import polars as pl
>>> import duckdb as db
>>> pl.Config.set_tbl_cols(42)
<class 'polars.config.Config'>
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> db.query("""
...     SELECT 
...          a
...         ,b
...         ,PRODUCT(b) AS prod
...     FROM df
...     GROUP BY a, b""")
┌───────┬───────┬────────┐
│   a   │   b   │  prod  │
│ int64 │ float │ double │
├───────┼───────┼────────┤
│    42 │  NULL │   NULL │
└───────┴───────┴────────┘
```

Pandas matches R's behavior:
```
>>> import pandas as pd
>>> df = pd.DataFrame({"a": [42], "b": [None]}, dtype="Int64")
>>> df.assign(
...     prod = lambda x: x.b.prod()
... )
    a     b  prod
0  42  <NA>     1
```

### Installed versions

<details>

```
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by StevenLi-DS** [comment]
@avimallu Thanks for sharing the [link](https://en.wikipedia.org/wiki/Empty_product). I think this empty product situation perhaps only applies to Series.

```python
import polars as pl

print(pl.Series([float('nan')]).product())
print(pl.Series([]).product())
print(pl.Series([None]).product())

nan
None
None
```
I'm not quite familiar with this math concept, but it mentioned that it's related to x^0=1. If any math operations on a missing value should return a missing value, I guess `pl.Series([None]).product()` should return `None`. But for the other two cases, perhaps they should be 1 instead. The current polars `0.17.3` behaviors look similar to Julia.

```julia
julia> prod([2, 3])
6

julia> prod([missing])
missing

julia> prod([NaN])
NaN

julia> prod([])
ERROR: MethodError: no method matching one(::Type{Any})

```

However, since [polars.Expr.product](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.product.html#polars.Expr.product) and [DataFrame.product](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.product.html#polars.DataFrame.product) are column operations, it might be more important to think about if we should some params to deal with `null` and `NaN` like [pandas.DataFrame.prod](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.prod.html#pandas-dataframe-prod). 

Right now:
```python
pl.DataFrame(
    {'a': [None, 1],
     'b': [float('nan'), 1.0]}
).product()

shape: (1, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ f64 │
╞══════╪═════╡
│ null ┆ NaN │
└──────┴─────┘
```

**Comment by ritchie46** [comment]
I am not convinced that missing data is the same as an empty set.

**Comment by avimallu** [comment]
@ritchie46, my reason for filing this bug is in line with the discussions in #8500. Since polars removes `null` values by default, `pl.Series([None]).product()` must be the same as `pd.Series([]).prod()`, so it should return `1`. If it's being tracked there, I can close this issue.

**Comment by stinodego** [comment]
Apologies, I missed this issue.

**Comment by CameronBieganek** [comment]
> In Julia however, `prod([])`, from the code you've pasted above, seems to throw an error.

In Julia, `prod` on an empty array will return the multiplicative identity as long as you give the empty array a type:

```julia
julia> prod(Int[])
1

julia> prod(String[])
""
```
