### ISSUE TITLE
NULL inconsistency: pow(`null`, 0) must be 1, not `null`

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#8186]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Follow up from discussion on #7595 to split issues on `null` value related inconsistencies into their own threads. I am going to show comparisons across `polars`, R (`data.table` and `dplyr`, which essentially uses R's built-in logic under the hood) and SQL (via `duckdb`, simply because that is the easiest). Extensive discussions on `NULL` values across different systems and their concepts are there [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1474114725) and [here](https://github.com/pola-rs/polars/issues/7595#issuecomment-1475680370). 

This one is associated with making sure that *any number raised to 0 is 1* stands true in Polars as well. See a lengthy discussion on this (for NaN, but similar principles apply) for R [here](https://stackoverflow.com/questions/17863619/why-does-nan0-1).

### Reproducible example

```python
>>> import polars as pl
>>> pl.Config.set_tbl_cols(42)
<class 'polars.config.Config'>
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> print(
...     df.with_columns(
...         prod = pl.col("b").pow(0)
...     ))
shape: (1, 3)
┌─────┬──────┬──────┐
│ a   ┆ b    ┆ prod │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ f32  ┆ f32  │
╞═════╪══════╪══════╡
│ 42  ┆ null ┆ null │
└─────┴──────┴──────┘
```

### Expected behavior

In this case similar to #8184, I think a design decision needs to be made to whether Polars should match SQL behavior, or R/pandas.
In R, this is:

```
> library(data.table)
> options(datatable.print.class = TRUE)
> DT = data.table(
+   a = 42,
+   b = NA_integer_
+ )
> DT[, .(a, b, power = b^0)]
       a     b power
   <num> <int> <num>
1:    42    NA     1
> 
> library(dplyr)
> DT |>
+   as_tibble() |>
+   mutate(
+     power = b^0)
# A tibble: 1 × 3
      a     b power
  <dbl> <int> <dbl>
1    42    NA     1
```

SQL matches Polars behavior:
```
>>> import polars as pl
>>> import duckdb as db
>>> pl.Config.set_tbl_cols(42)
<class 'polars.config.Config'>
>>> df = pl.DataFrame({"a": [42], "b": [None]})
>>> db.query("""
...     SELECT 
...          a
...         ,b
...         ,POW(b, 0) as pow
...     FROM df""")
┌───────┬───────┬────────┐
│   a   │   b   │  pow   │
│ int64 │ float │ double │
├───────┼───────┼────────┤
│    42 │  NULL │   NULL │
└───────┴───────┴────────┘
```

Pandas matches R's behavior:
```
>>> import pandas as pd
>>> df = pd.DataFrame({"a": [42], "b": [None]}, dtype="Int64")
>>> df.assign(
...     power = lambda x: x.b.pow(0)
... )
    a     b  power
0  42  <NA>      1
```

### Installed versions

<details>

```
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by avimallu** [comment]
I don't really want to put in my thoughts to answer your question @StevenLi-DS , because it is a philosophical one, and I'm not really qualified to give you an informed opinion.

What I can say, however, is that R and Pandas treats `NA` (which in Polars is `None`) as a missing value, but definitely a part of the data type that it represents. R even has separate NA values for each of its data types - `NA_real_`, `NA_integer_`, `NA_char` and `NA_complex_`. I would prefer that Polars follows R's behavior, because they're the statistics people, and they've probably put a ton of thought into this core behavior.

**Comment by StevenLi-DS** [comment]
I actually never used `NA` in pandas, but always `NaN`. Based on the example I give above, polars does "follow" since `nan`^0 = 1.  Polars actaully use null for missing value and nan for not a number:
> NaN values are considered to be a type of floating point data and are not considered to be missing data in Polars

https://pola-rs.github.io/polars-book/user-guide/howcani/missing_data.html

**Comment by avimallu** [comment]
Ah, pandas has a bad history with NaN values. See that @alexander-beedie mentioned in #7889:

> Yes - and `NaN` is indeed a valid floating point value, with a very different meaning from `null` (you definitely don't want to unintentionally conflate the two values)

Unfortunately, it looks like Pandas chose to do exactly that many years ago (which probably made sense at that time since they were very reliant on `numpy` - see a rather large note about it [here](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html#Missing-Data-in-Pandas)).

Pandas now a new `pd.NA` datatype that *actually* is for missing values. It even supports the Python `NoneType`, `None` as a **nearly** identical replacement for its missing value. It used to employ `np.nan` (denoted as `NaN` in Pandas DataFrames) for *both* missing **and** Not a Number cases (the "valid floating point value" that is mentioned in the quote above), it still maintains backward compatibility for them:

```python
>>> import pandas as pd
>>> import numpy  as np
>>> df = pd.DataFrame({"a": [pd.NA], "b": [None], "c":[np.nan], "d": [np.array(0)/np.array(0)]})
<stdin>:1: RuntimeWarning: invalid value encountered in divide
>>> df.assign(
...     **{x + "_pow^0": df[x].pow(0) for x in df.columns})
      a     b   c   d a_pow^0 b_pow^0  c_pow^0  d_pow^0
0  <NA>  None NaN NaN       1     NaN      1.0      1.0
```
As you can see, Pandas treats all three - `pd.NA`, `None`, and `np.nan` (which also results from division by 0) as raising it to 0 results in an `int` 1, an `np.nan` (different from `pd.NA`) and `float` `1.0`.

On what Polars does:

1. Polars consideres `nan^0` as `0`. I agree, no doubt about it.
2. Polars does not consider `null^0` as `0`, which I think it should follow convention with R/Pandas on.

Remember, when `pl.DataFrame({"a": [None]})`, Polars **converts** Python `None` to `null`.
However, `pd.DataFrame({"a": [None]})` **does not convert** Python `None` to its equivalent `null`. 

**The brader point**: I am not here to debate what's right and not - just following the directions in the OP thread to separate different issues with consistency on `null` values into separate threads so that they can be resolved. I hope Polars is able to evade the problems Pandas has had with its various representaions of missing values :)

Also - please feel free to correct me if I'm wrong in my understanding of NA values somewhere.

**Comment by StevenLi-DS** [comment]
I think you're right and pandas perhaps just want to make it consistent with NumPy and NumPy doesn't have null but only NaN https://pandas.pydata.org/docs/whatsnew/v0.22.0.html#backwards-incompatible-api-changes.

In fact, in pandas 2.0.0, when you use pyarrow dtype, it's consistent with polars behavior.

```python
import pandas as pd
import pyarrow as pa

df = pd.DataFrame(
    {'a': [pd.NA], 'b': [None]},
    dtype='int32[pyarrow]'
)
df.assign(**{x + "_pow^0": df[x].pow(0) for x in df.columns})


      a     b  a_pow^0  b_pow^0
0  <NA>  <NA>     <NA>     <NA>
```
Lots of things in R don't make sense to me, but if you look at Julia, another language made by "statistics people", it treats missing value and `NaN` differently https://docs.julialang.org/en/v1/manual/missing/
```julia
julia> NaN^0
1.0

julia> missing^0
missing
```

**Comment by ritchie46** [comment]
I think we can close this one. Missing data is not a number and any operation on it remains missing.

**Comment by avimallu** [comment]
@StevenLi-DS, not glad to know that the contention on missing values continues with Julia 😅. Thanks - I didn't look at Julia for my comparisons; might be worth to look into for the other issues. 

@ritchie46, okay, will close this issue. 

I think it might help to expand on the Polars book with information on how it handles missing values as a source of reference on what to expect.

**Comment by StevenLi-DS** [comment]
@avimallu maybe this one should be closed as well? https://github.com/pola-rs/polars/issues/8184

**Comment by avimallu** [comment]
That is a different problem with a well defined [mathematical convention](https://en.wikipedia.org/wiki/Empty_product), so I think it's still fine to leave it open until a discussion is made.
