### ISSUE TITLE
Datetime parsing yields not same result as standard library

### ISSUE THREAD

**Issue by lorenzwalthert** [pola-rs/polars#8203]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Datetime parsing seems not not work correctly for some formats. Note the `74000` vs `74` in the microseconds digit.

### Reproducible example

```python
>>> import datetime 
>>> import polars as pl
>>> fmt = "%Y-%m-%dT%H:%M:%S.%f"
>>> dt = '2023-02-05T05:10:10.074000'



>>> datetime.datetime.strptime(dt, fmt)
datetime.datetime(2023, 2, 5, 5, 10, 10, 74000)
>>> set([pl.Series([dt]).str.strptime(target, fmt).item() for target in pl.DATETIME_DTYPES])
{datetime.datetime(2023, 2, 5, 5, 10, 10),
 datetime.datetime(2023, 2, 5, 5, 10, 10, 74)}
```

You can also add a time zone and it does not work:
```python
>>> import datetime 
>>> import polars as pl
>>> fmt = "%Y-%m-%dT%H:%M:%S.%f%z"
>>> dt = '2023-02-05T05:10:10.074000+0000'



>>> datetime.datetime.strptime(dt, fmt)
datetime.datetime(2023, 2, 5, 5, 10, 10, 74000, tzinfo=datetime.timezone.utc)
>>> set([pl.Series([dt]).str.strptime(target, fmt, utc=True).item() for target in pl.DATETIME_DTYPES])
{datetime.datetime(2023, 2, 5, 5, 10, 10, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
 datetime.datetime(2023, 2, 5, 5, 10, 10, 74, tzinfo=zoneinfo.ZoneInfo(key='UTC'))}
```

### Expected behavior

I expect that at least for one of the specified formats from `pl.DATETIME_DTYPES`, the result of polars and the standard library would be identical.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Let's at least start with a note in our doctrings.

**Comment by lorenzwalthert** [comment]
Thanks guys for the explanation and the quick fix. Should have just read the chrono docs, but I guess it's good anyways to fail loudly here as one does not always check if the date is parsed as expected.
