### ISSUE TITLE
Rename `str.strptime`/`dt.strftime` methods

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8215]
These names are well-established historically, but definitely do not follow our naming conventions.

I would suggest:
* `str.strptime` -> `str.to_timestamp`
* `dt.strftime` -> `dt.to_string`

There might be better names - suggestions?

**Comment by mcrumiller** [comment]
If we went this route, I think `strptime` should be split into two functions:

* `str.strptime(pl.Date, fmt)` -> `.str.to_date()`
* `str.strptime(pl.Datetime, fmt)` -> `.str.to_datetime()`.

I always forget to put in the dtype.

**Comment by stinodego** [comment]
Not a bad idea. If we do keep it as one method, we should probably try to infer the dtype from the given format.

**Comment by ritchie46** [comment]
Because of there historical significance, I'd like to keep them, but I'd be ok with adding aliases for them that are better in line with our naming conventions.

**Comment by JulianCologne** [comment]
in this context I would also very much welcome a
- `str.to_duration`

as suggested here #7397.

I occasionally work with durations (call data, experiments, ...) which are usually in the format H:MM:SS where the hours can also be >24 (or negative) (123:45:00; -1:23:00).

Unfortunately, I currently always switch to pandas for this because of the very practical `pd.to_timedelta` method (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_timedelta.html).

**Comment by stinodego** [comment]
Agreed @JulianCologne. All right, so then we'll keep the existing methods, and add the following aliases:

* `str.to_date`
* `str.to_time`
* `str.to_datetime`
* `str.to_duration` _(requires expanding current_ `strptime` _functionality)_
* `dt.to_string`

@ritchie46 Do you want these aliases under Rust too? Or only for Python users?

**Comment by ritchie46** [comment]
> @ritchie46 Do you want these aliases under Rust too? Or only for Python users?

On rust on the expressions. let's try to keep that 1:1. :)

**Comment by MarcoGorelli** [comment]
> Also pinging datetime-overlord @MarcoGorelli to see if he has an opinion 😄

😄 cheers - well, thinking with my "coming from pandas" hat on, I think `str.to_datetime` would be a nice and clear addition! Likewise for the others

**Comment by stinodego** [comment]
This issue is now completed - for the implementation of `dt.to_duration`, please refer to issue https://github.com/pola-rs/polars/issues/7397.
