### ISSUE TITLE
Regression: dt.offset_by month panics if starting day is too large for target month

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8217]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This regression was introduced in 0.17.1 and still exists in 0.17.2. If calling `.dt.offset_by("1mo")` from, say, January 31st, polars panics because Feb 31st doesn't exist.

### Reproducible example

```python
import polars as pl
from datetime import date

pl.Series([date(2018, 1, 31)]).dt.offset_by("1mo")
```
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot advance '2018-01-31 00:00:00' by 1 month(s)"))
```

### Expected behavior

Moving by month should limit you to the end of the month. In the above case, it should return Feb 28 (or Feb 29 if leap year).

### Installed versions

<details>

```
Polars: 0.17.1
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.2_alpha.2
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ritchie46** [comment]
@MarcoGorelli I think we should have a `saturating` option, what do you think? 

If `saturating=True` we then would return `2018, 2, 28`.

**Comment by MarcoGorelli** [comment]
Not sure - what would the expected output be if you did
```
pl.Series([date(2018, 1, 31)]).dt.offset_by("2mo", saturating=True)
```
?

How about
```
pl.Series([date(2018, 1, 31)]).dt.offset_by("1mo", saturating=True).dt.offset_by("1mo", saturating=True)
```
?


For the first one, you could say it should be `2018-03-31`, but for the second one, I think it would have to be `2018-03-28`. Having them not be the same would be confusing. But having the first one also be `2018-03-28` would be confusing, and not very useful if the user is trying to get the last day of the month.

My suggestion would be to just document how to get the previous behaviour by using `offset_by`, as in https://github.com/pola-rs/polars/issues/8161#issuecomment-1503617347 (and sure, maybe add `dt.month_start` and `dt.month_end`)

**Comment by mcrumiller** [comment]
If anyone is familiar with Matlab, I believe they have the best treatment of time I've come across. They separate durations into two two types: `duration` and `calendarDuration`. `duration`s represent fixed-length units of time. Taken from their [documentation](https://www.mathworks.com/help/matlab/matlab_prog/represent-date-and-times-in-MATLAB.html):

* Represent a point in time, using the `datetime` data type.
    Example: Wednesday, June 18, 2014 10:00:00

* Represent a length of time, or a duration in units of fixed length, using the `duration` data type. When using the `duration` data type, 1 day is always equal to 24 hours, and 1 year is always equal to 365.2425 days.
    Example: 72 hours and 10 minutes

* Represent a length of time, or a duration in units of variable length, using the `calendarDuration` data type.
    Example: 1 month, which can be 28, 29, 30, or 31 days long.
    The `calendarDuration` data type also accounts for daylight saving time changes and leap years, so that 1 day might be more or less than 24 hours, and 1 year can have 365 or 366 days.

![image](https://user-images.githubusercontent.com/1896992/232035734-79985feb-4a2b-4e42-bc4f-96e63633657f.png)

https://www.mathworks.com/help/matlab/matlab_prog/represent-date-and-times-in-MATLAB.html

For the above example, they specifically address this in their documentation, and IMO it makes sense. For adding an array of  `calmonths` starting at Jan 31, they say "Since February has fewer days than January, it is unambiguous that adding a calendar month to January 31st results in a date of February 28th (since 2021 is not a leap year)."

```matlab
datetime('2021-01-31') + calmonths(0:2)
```
```
1x3 datetime
   31-Jan-2021   28-Feb-2021   31-Mar-2021
```
Starting from February 28, however:

```matlab
datetime('2021-02-28') + calmonths(0:2)
```
```
1x3 datetime
   28-Feb-2021   28-Mar-2021   28-Apr-2021
```

...and to get end-of-month, use `dateshift(t, 'end', 'month')`.

---

I don't think it would be a great idea for polars to adopt the same API, but the clash between calendar durations and fixed durations is something that *constantly* comes up and maybe warrants discussion.

I think using "1mo" or "2mo" should perhaps always truncate, but remember the initial day. So we'd have;

* 2018-01-31 offset by `1mo` -> 2018-02-31, gets truncated to 2018-02-28
* 2018-01-31 offset by `2mo` -> 2018-03-31
* 2018-01-31 offset by `3mo` -> 2018-04-31, gets truncated to 2018-04-30
...etc.

This almost means that 2018-01-31 offset by `1mo` then offset again by `1mo` doesn't have the same expected behavior as an initial offsetting of `2mo`.

I have a fork implementing `month_end` and `month_begin` but I'm still working on getting myself set up to compile, as I'm on Windows.

**Comment by chaaland** [comment]
Ran into this same issue last night upgrading from 0.16.8 to 0.17.2. @mcrumiller Really like this suggestion of treating calendar duration as distinct from time duration. It's a subtle (but important) distinction I'd never really put much time into thinking about.

**Comment by MarcoGorelli** [comment]
thanks @chaaland for the context - could you show what code you're working on please?

I'm ready to admit that I'm wrong, but I'd really like to think that `.offset_by` combined with the helper functions `.dt.month_start` and `.dt.month_end` would be:
- enough to accomplish anything
- more explicit
- more predictable
- simpler from a maintenance perspective, as the saturating option would likely also need to be there in rolling/groupby/date_range/upsample and other functions which use offsets

@mcrumiller feel free to reach out on Discord re-setting up an environment, I'm also on Windows (but I use the WSL2 for anything development-related)

**Comment by mcrumiller** [comment]
Coming back to this--I really think the default implementation should be the same as described above for Matlab's implementation: truncate to end-of-month if the day is too big for that month, otherwise keep the same day of the month. Currently, `pl.date_range()` is broken if you want to start on January 31st, for example:

```python
import polars as pl
from datetime import date

pl.date_range(date(2023, 1, 31), date(2023, 6, 30), interval="1mo")
```
```
exceptions.ComputeError: cannot advance '2023-01-31 00:00:00' by 1 month(s)
```

**Comment by MarcoGorelli** [comment]
What used to happen there was
```python
In [3]:
   ...: pl.date_range(date(2023, 1, 31), date(2023, 6, 30), interval="1mo")
Out[3]:
shape: (6,)
Series: '' [date]
[
        2023-01-31
        2023-02-28
        2023-03-28
        2023-04-28
        2023-05-28
        2023-06-28
]
```
which would break expectations, see https://github.com/pola-rs/polars/issues/5441

I understand it's annoying to get an error, but spending an extra minute today adding
```python
    .dt.offset_by("1mo")
    .dt.offset_by("-1d")
```
can potentially save hours of debugging tomorrow. See the example in
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.date_range.html

Regarding mirroring matlab: to be honest I find the ambiguity of `pl.date_range(date(2023, 2, 28), date(2023, 6, 30), interval="1mo")` particularly concerning

**Comment by mcrumiller** [comment]
Yeah, that behavior just seems flat out bad to me. I won't die on this hill, but I will argue that behavior of either `date_range` or `offset_by("xmo")` should not be to raise an exception for any dates.

The analogy here is that you're at the back of a room, and someone says "move down one room." Nobody would say "well that room is shorter than this one so I can't, that's an error." Our idea of a "month" is a pre-defined chunk of time during the year, which is essentially one of the twelve rooms of the year, and they're all 28/29/30/31 feet long, so when you add a "month" to January, it means taking into account the fact that January and February are different lengths.

Regardless, I'm still working on the other PR. I'm powering through the rust book in the next few days so hopefully I can get `month_end` and `month_start` added to the rust side as well, although I'll probably need you for guidance along the way.

**Comment by MarcoGorelli** [comment]
Sure, thanks for explaining. I'm also not willing to die on this hill, and may change my mind. I just want to be very careful here - in pandas there's `MonthBegin`, `MonthEnd`, and `DateOffset(month=...)`, and there's no end to the confusion it all causes both to users and to maintainers. polars has a chance to do things differently and better

> Nobody would say "well that room is shorter than this one so I can't, that's an error."

Sure, but if you told everyone to move forward one room, then you'd probably expect someone to say "I can't, the new room's smaller and all the places are taken"

Re the month_end PR - awesome! I think you'll only need the first few chapters of the book to be able to work on that PR - feel free to ping anyway

**Comment by chaaland** [comment]
Reading the above discussion, this time/calendar stuff is _even_ more subtle than I had originally grasped. In my use case, I had some price data and I wanted to get the year over year return so I was offsetting by `"1y"` and doing a self join. One of these dates was 29th Feb which caused the break. 

Originally I was thinking a year prior should just be 28th Feb of the previous year. But then I don't know what I would expect 28th Feb a year ago to be? The same thing? I was doing a join on the data with itself lagged by one year so that would create multiple entries with the same key which I definitely would not want.

Even with a notion of calendar duration vs time duration, I think the ambiguity in my case would still exist. Anyway, don't have a solution but can appreciate the complexity of the problem.

**Comment by mcrumiller** [comment]
@chaaland yeah, calendar offsets are not guaranteed to be commutative operations, i.e. `A + B - B != A`. As a result, somewhat arbitrary rules need to be decided, although they can follow some logical strategies.

**Comment by bennullgraham** [comment]
One of the things I've loved the most coming from Pandas is that Polars doesn't make assumptions. You have to tell it unambiguously how to behave, or it blows up.

The two meanings of duration — calendar versus fixed — are very much one of these ambiguous situations. I feel like it would be internally consistent if Polars required that you specify which you mean. In my head this is as simple as e.g. `.offset_by("1cy")` vs `.offset_by("1y")`. 

I think when people currently use `"1mo"` they _expect_ calendar month. In fact I don't think there is any reasonable interpretation of "1mo" as a fixed duration. It may therefore be worth warning/raising when these are used. For example:

> "1mo" is ambiguous. Use "cmo" to specify calendar months, or e.g. "30d" for a fixed number of days.

Just some user feedback. Appreciate this great project however this pans out :+1:

**Comment by MarcoGorelli** [comment]
Thanks everyone for commenting!

https://github.com/pola-rs/polars/pull/8435 adds `.dt.month_end`, so for anything where you want the last day of each month (for example, `date_range`), you should use that. For the majority of use-cases, I'd expect this to be sufficient

But it certainly sounds like there are cases where it isn't. @chaaland 's case, and [this one](https://github.com/pola-rs/polars/pull/8435#issuecomment-1519452878) for example. A solution could be:

- `'1mo'`: advances to the same day in the next month, errors if it can't. E.g. `pl.Series([datetime(2022, 1, 30)]).dt.offset_by('1mo')` would error, just like it does now
- `'1mo_truncated'`: advances to the same day in the next month, but goes back to the last day of the month if that's not possible. E.g. `pl.Series([datetime(2022, 1, 30)]).dt.offset_by('1mo_')` goes to `2022-02-28`, just like `'1mo'` used to

---

> I think when people currently use "1mo" they expect calendar month

It's already a calendar month (adding `'1mo'` to `2022-01-15` adds 31 days, whereas adding `'1mo'` to `2022-02-15` adds 28 days. It just errors when the next month doesn't exist, e.g. `2022-01-31` + 1 month. Note that even `'30d'` isn't a fixed duration in the timezone-aware case
