### ISSUE TITLE
Add `explode` as top level expression.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#8218]
Now we have `implode` as top level expression, I would like to `explode` as top level expression as well. We recently moved it under the `arr` and `str` namespace, but I think it should be top-level.

I think this is semantically correct as an `explode` removes one level of nesting. If the array is already completely flattened, there is not nesting to remove and an `explode` on such an array would return itself. 

Any objections?

**Comment by stinodego** [comment]
The only issue I see is that `explode` for strings seems odd to me.

I would expect calling explode on any non-list column to be a no-op, following your logic. With that in mind, indeed it should be moved back to top-level as it does not only work on lists anymore. But then suddenly, my column with strings (which feel 'immutable' to me) gets turned into single characters!

So if we go ahead with this, maybe we should have `explode` keep strings intact, and have a different name for `str.explode`?

**Comment by ritchie46** [comment]
Yes good point. I agree on that one. The utility of the string explode is also far less and might be considered more an implementation detail (that strings are the same way encoded as lists) that should not be exposed to the user.

**Comment by gab23r** [comment]
why not, It has some impacts though, for exemple this should/would become legit:
```pl.DataFrame({'A': [[0,1,2]], 'B': [0]}).select(pl.all().explode())```

**Comment by gab23r** [comment]
Btw, in the case, `.select(pl.all().explode().implode()` would not be a no-op which is maybe not expected or a cool feature ...
