### ISSUE TITLE
Combining `Expr.drop_nulls` and `Expr.filter()` in `arr.eval` gives different result depending on order.

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#8226]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Combining `Expr.drop_nulls` and `Expr.filter` in `arr.eval` gives different result, depending on order. See example below

I know that I can use `pl.element().is_not_null()`, but I'm having performance issues with `filter` in `arr.eval` so I wanted to limit the amount of calls in there.

### Reproducible example

```python
import polars as pl

series = pl.Series([["1", "", None]])

# I want to filter out nulls and empty strings

# Only drop_nulls:
print( 
    series.arr.eval(pl.element().drop_nulls())
) # ✅ [["1", ""]] 
# Only filter empty string:
print(
    series.arr.eval(pl.element().filter(pl.element() != ""))
)  # ✅ [["1", null]] 
# Filter empty string then drop nulls:
print(
    series.arr.eval(pl.element().filter(pl.element() != "").drop_nulls())
)  # ✅ [["1"]] 
# Drop nulls then filter empty string:
print(
    series.arr.eval(pl.element().drop_nulls().filter(pl.element() != ""))
) # ❌ [null]
```

### Expected behavior

I expected the result to be consistent, no matter the order.

Full context:

I have list of strings, that I want to join together with a delimiter. Before doing that, I want to filter out empty strings and nulls.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.9.14 (main, Sep  7 2022, 23:43:48) 
[GCC 11.2.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.3.5
pyarrow: 10.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
> performance issues with filter in arr.eval

Have you tried using eval's `parallel=True`?

**Comment by cjackal** [comment]
It seems `.filter(pl.element)` trick in `.arr.eval` context does not work after you've made any operation that changes the length of the element list.

e.g.)
```python
print(
    series.arr.eval(pl.element().filter(pl.element() != "").filter(pl.element() != ""))
) # ❌ [null]
print(
    series.arr.eval(pl.element().reverse().filter(pl.element() != ""))
)  # ✅ [[null, "1"]] 
print(
    series.arr.eval(pl.element().filter(pl.element() != "2").filter(pl.element() != ""))
)  # ✅ [["1", null]]
```

Other filtering ops do not suffer this kind of misbehavior in `.arr.eval` context:
```python
series = pl.Series([[1., float("nan"), None]])

print(
    series.arr.eval(pl.element().drop_nans().drop_nulls())
) # ✅ [[1.0]]
print(
    series.arr.eval(pl.element().drop_nulls().drop_nans())
) # ✅ [[1.0]]
print(
    series.arr.eval(pl.element().filter(pl.element().is_not_null()).drop_nans())
) # ✅ [[1.0]]
# Filter after length change:
print( 
    series.arr.eval(pl.element().drop_nans().filter(pl.element().is_not_null()))
) # ❌ [null]
print( 
    series.arr.eval(pl.element().filter(pl.element().is_not_nan()).filter(pl.element().is_not_null()))
) # ❌ [null]
```

Other troublesome behaviors - it is not only the length change that disrupts `.filter(pl.element)` trick:
```python
# Filter without reverse - OK
print( 
    series.arr.eval(pl.element().filter(pl.element().is_not_null() & pl.element().is_not_nan()))
) # ✅ [[1.0]]
# Filter with reverse - Fail (Note that reverse does not make trouble in above situation)
print( 
    series.arr.eval(pl.element().reverse().filter(pl.element().is_not_null() & pl.element().is_not_nan()))
) # ❌ [[null]]
```

I guess `.filter` in `.arr.eval` confuses which list its input pl.element lies in - in last example, filter correctly checks that only the first element is not null and nan, but it is the original list, not the reversed one.

**Comment by StefanBRas** [comment]
> > performance issues with filter in arr.eval
> 
> Have you tried using eval's `parallel=True`?

I found it after and it makes it much faster, but I was still a bit surprised that it's still the same magnitude as using apply.
It's a bit of a bottleneck in my use case, which Is why I'm trying to optimize it.
A quick performance code snippet:

```python
import polars as pl

n = 100_000

df = pl.LazyFrame({'x': [["a", None, ''] for _ in range(n)]})

def remove_empty_string(lst):
    return [elem for elem in lst if (elem != "") and (elem is not None)]

res_arr_drop_nulls = df.with_columns(
    pl.col('x').arr.eval(pl.element().drop_nulls(), True)
).profile()[1].get_column('end').max()

res_apply = df.with_columns(
    pl.col('x').apply(remove_empty_string)
).profile()[1].get_column('end').max()

res_arr_filter = df.with_columns(
        pl.col('x').arr.eval(pl.element().filter(pl.element().is_not_null() & (pl.element() != "")), True)
).profile()[1].get_column('end').max()


print(f"{res_arr_drop_nulls=}") # 66330
print(f"{res_arr_filter=}")     # 220825
print(f"{res_apply=}")          # 814480
```


> ~I don't know if it can easily be fixed, but `.filter(pl.element)` really hurts readability, I suggest one should avoid it whenever possible.~
> 
> EDIT. It is clearly stated in [the documentation](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.element.html#polars-element) that `polas.element` is the element evaluated in `eval` expression, not the others, meaning:
> 
>     * In `series.arr.eval(pl.element().drop_nulls().filter(pl.element() != ""))` example, both `pl.element()` refer to the same list, `["1", "", None]`, thus `.filter` selects the 0th and 2nd indices from `pl.element().drop_nulls()` = `["1", ""]`, which is out-of-index, so return `null`.
> 
>     * In `series.arr.eval(pl.element().filter(pl.element() != "").filter(pl.element() != ""))` example, all three `pl.element()` refer to the same list, `["1", "", None]`, thus both `.filter` select the 0th and 2nd indices. Applied to the first `pl.element()`: `["1", "", None] -> ["1", None] ->` out-of-index, thus return null.
>       Other examples can be analyzed similarly.
> 
> 
> So it is the implementation detail, not bug, I think.

I see that it's actually consistent with the behaviour of `pl.col`, which will also refer to the column as it was at the start of the context, and not at "this point":
```python
import polars as pl
(
    pl.LazyFrame({
        "g": [1, 1,1, 1],
        "x": [1, 2,3, None],
    }).groupby("g").agg(
    [
        pl.col("x").drop_nulls().filter(pl.col("x") < 2).sum(),
    ]
).collect()
) # Throws exceptions.ShapeError: filter's length: 4 differs from that of the series: 3
```

Maybe it's fine then? I think I threw myself off by having everything in a chained call, which made me think that the lists would be accessed in the same order.

**Comment by ritchie46** [comment]
It likely is much faster in latest release. We can now automatically convert to a groupby + aggregation in most cases.

**Comment by ritchie46** [comment]
The latest expression was invalid because the filter was longer than the input expression (which dropped nulls), this has been fixed now and raises an error.
