### ISSUE TITLE
Panic when creating Series object from numpy float32 in 0.17.2 but not in 0.17.1

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#8232]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This seems like a regression. The code below works in 0.17.1, but does not work in 0.17.2, and is likely related to #8155 (although I'm not sure - not very good at programming to figure out).

### Reproducible example

```python
import polars as pl
import numpy as np

class foo():
    def __init__(self):
        pass
    
    def lens(self, str_1, str_2):
        return np.array((len(str_1) + len(str_2)) * 0.001, dtype=np.float32)
    
    def bar(self, strings: pl.Series) -> pl.Series:
        return pl.Series("len", [self.lens(x, y) for x,y in strings.to_list()])

K = foo()
K.bar(pl.Series("word", [["foo", "bar"]]))
```

### Expected behavior

The last line gives:

```
shape: (1,)
Series: 'len' [o][object]
[
	0.006
]
```

in 0.17.0 and 0.17.1., but throws the following error in 0.17.2:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/work/polars/polars/polars/polars-core/src/chunked_array/object/registry.rs:80:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am fine with the existing behavior of error-ing out, but I don't see a breaking change being called out in the release, so I thought I should raise this an an issue.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by cmdlineluser** [comment]
Here's a reduced example:
```
# PanicException: called `Option::unwrap()` on a `None` value

pl.Series([np.array(1, dtype=np.float32)])
```
```
pl.Series([np.array(1)])
```
```
shape: (1,)
Series: '' [i64]
[
	1
]
```

**Comment by avimallu** [comment]
Thank you! For some reason I wasn't able to get a simpler example to work for me, and my problem was occuring within a class that returned a list of np.float32 values.

**Comment by cmdlineluser** [comment]
If you use `np.array([...])` - polars does not complain.
```
>>> pl.Series(np.array([1.0]))
shape: (1,)
Series: '' [f64]
[
	1.0
]
```
This is the first time I've seen the syntax of `np.array(single_value)` - so I'm not entirely sure what's going on with it.

**Comment by cjackal** [comment]
Seems this bug is specific to `np.float32` scalar?

```python
class foo():
    def __init__(self):
        pass
    
    def lens(self, str_1, str_2):
        return np.array((len(str_1) + len(str_2)) * 0.001, dtype=np.float64)
    
    def bar(self, strings: pl.Series) -> pl.Series:
        return pl.Series("len", [self.lens(x, y) for x,y in strings.to_list()])

K = foo()
K.bar(pl.Series("word", [["foo", "bar"]]))  # OK

class foo():
    def __init__(self):
        pass
    
    def lens(self, str_1, str_2):
        return np.array((len(str_1) + len(str_2)) * 0.001, dtype=np.int64)
    
    def bar(self, strings: pl.Series) -> pl.Series:
        return pl.Series("len", [self.lens(x, y) for x,y in strings.to_list()])

K = foo()
K.bar(pl.Series("word", [["foo", "bar"]]))  # OK

class foo():
    def __init__(self):
        pass
    
    def lens(self, str_1, str_2):
        return np.array((len(str_1) + len(str_2)) * 0.001, dtype=np.uint64)
    
    def bar(self, strings: pl.Series) -> pl.Series:
        return pl.Series("len", [self.lens(x, y) for x,y in strings.to_list()])

K = foo()
K.bar(pl.Series("word", [["foo", "bar"]]))  # OK
```

**Comment by avimallu** [comment]
> Incase it's useful information - you can use polars to perform those calculations:
Oh, I have a custom function call that performs some additional work on the two strings, that's why I had to go outside Polars for this. Thanks!

**Comment by avimallu** [comment]
Thank you - although I don't think it's really a feasible workaround entirely as `np.float32` is much better suited to `pl.Float32` than `pl.Object`, so there is an underlying issue that requires some looking into.
