### ISSUE TITLE
Panic when applying custom python function that returns a custom class object

### ISSUE THREAD

**Issue by HugoPerrier** [pola-rs/polars#8233]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I get a panic error when applying a custom function that returns an instance of a custom python class object.

Error:
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/polars/polars/polars/polars-core/src/chunked_array/object/registry.rs:80:28

### Reproducible example

```python
import polars as pl

class Foo:
    pass 

def create_foo(s):
    return Foo()

df = (
    pl.DataFrame({
        "data": ["foo", "bar"],
    })
    .with_columns(
        pl.col("data")
            .apply(create_foo)
            .alias("result")
    )
)
```

### Expected behavior

I expect a new column "result" to be created containing (on each row) an instance of the Foo class

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.10
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by avimallu** [comment]
Can you try what @cjackal mentioned [here](https://github.com/pola-rs/polars/issues/8232#issuecomment-1508935641), and specifying dtype=Foo?

**Comment by ritchie46** [comment]
This is fixed on master.
