### ISSUE TITLE
When use lazy()，sort() does not work

### ISSUE THREAD

**Issue by teraStars** [pola-rs/polars#8234]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

My code runs well for long time,but when i updated polars to 0.17.0  or 0.17.2, I found sort() does not work.
I delete lazy(),then sort works well.

### Reproducible example

```python
tmp=iblist.lazy().filter(
    (pl.col("Symbol").str.to_lowercase()=="1133")&
    (pl.col("DateTime")>pl.datetime(2015,1,1))
).select(collist).sort("DateTime", descending=True).head(999).collect()
```

### Expected behavior

Lazy() can also sort() as  in the previous version.

### Installed versions

<details>

```
'0.17.2'

</details>

**Comment by ritchie46** [comment]
Have you got any reproducable example?

**Comment by teraStars** [comment]
> Have you got any reproducable example?

df = pl.DataFrame(
    {
        "a": [1, 2, None],
        "b": [6.0, 5.0, 4.0],
        "c": ["a", "c", "b"],
    }
)
df.lazy().sort("b").head(3).collect()

It works fine  when versions  before 0.17. 
and the code below works find after 0.17.
    df.sort("b").head(3)
