### ISSUE TITLE
Panic on `Series` init with List of List dtype if empty list is the first element 

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#8243]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Initialising a Series with a nested `List` dtype panics if first element is the empty list.

(Discovered while developing a new _"list of lists"_ hypothesis/parametric strategy for us).

### Reproducible example

**Panics:** _(first element is the empty list)_
```python
s = pl.Series(
    name = "colx",
    values = [
        [],
        [[], []],
        [[33, 112]],
    ],
    dtype = pl.List(pl.List(pl.Int8)),
)

# pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: 
#   InvalidArgumentError("It is not possible to concatenate arrays of different data types.")
```
**Succeeds:** _(same elements, different order)_
```python
s = pl.Series(
    name = "colx",
    values = [
        [[], []],
        [],
        [[33, 112]],
    ],
    dtype = pl.List(pl.List(pl.Int8)),
)

# shape: (3,)
# Series: 'colx' [list[list[i8]]]
# [
# 	[[], []]
# 	[]
# 	[[33, 112]]
# ]

```

### Expected behavior

The given Series should initialise, irrespective of the element order.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0
pyarrow: 11.0.0
connectorx: 0.3.2_alpha.2
deltalake: 0.8.1
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ritchie46** [comment]
Will have to extend the `concat` functionality upstream. I will hoist this one to next weeks release.

**Comment by alexander-beedie** [comment]
> Will have to extend the `concat` functionality upstream. I will hoist this one to next weeks release.

Good stuff; I'll get the full "list of lists" strategy ready in the meantime, and start thinking about structs...🤔

**Comment by ritchie46** [comment]
Hmm... Seems to work already. I shall add the test in our suite.
