### ISSUE TITLE
Accept custom aggregation functions in DataFrame.pivot

### ISSUE THREAD

**Issue by artnaz** [pola-rs/polars#8250]
I would have liked to use custom aggregation functions in DataFrame.pivot. For example:

```
df = pl.DataFrame({
    'col1': ['a', 'a', 'a', 'b', 'b', 'b'],
    'col2': ['x', 'x', 'x', 'x', 'y', 'y'],
    'col3': [6, 7, 3, 2, 5, 7]
    })
```

Here I want to have 'col1' as index and 'col2' as columns, while 'col3' should be the values with a custom aggregation. As a workaround, I groupby with the custom aggregation and then do the pivot:

```
df.groupby('col1', 'col2').agg(
    col3_agg = pl.col('col3').apply(lambda x: pl.mean(np.tanh(x)))
).pivot(
    index='col1', columns='col2', values='col3_agg', aggregate_function=None
)
```

I think something like this would be a pleasant functionality:
```
df.pivot(
  index='col1', columns='col2', values='col3',
  aggregate_function=lambda x: pl.mean(np.tanh(x))
)
```

**Comment by ritchie46** [comment]
Please don't use `lambdas` if you can run this with an expression. 

We support expression, so this is already possible: 

```python
df = pl.DataFrame({
    'col1': ['a', 'a', 'a', 'b', 'b', 'b'],
    'col2': ['x', 'x', 'x', 'x', 'y', 'y'],
    'col3': [6, 7, 3, 2, 5, 7]
    })

df.pivot(
  index='col1', columns='col2', values='col3',
  aggregate_function=pl.element().tanh().mean()
)
```

**Comment by artnaz** [comment]
Ok great! But what if it's a more complex function?

**Comment by ritchie46** [comment]
Make a more complex expression or use `expr().apply` (only as a last resort).

**Comment by artnaz** [comment]
Ok thank you.
