### ISSUE TITLE
`SQL`: error with CTEs

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8265]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have been looking forward to CTEs so I tried them out.

I have an error:
ComputeError: no table name provided in query

### Reproducible example

```python
import polars as pl

df = pl.LazyFrame({
    'Year': [2018, 2018, 2019, 2019, 2020, 2020],
    'Country': ['US', 'UK', 'US', 'UK', 'US', 'UK'],
    'Quantity': [100, 200, 300, 400, 500, 600],
    'Sales': [1000, 2000, 3000, 4000, 5000, 6000]
})

sql = pl.SQLContext()
sql.register('df', df)

sql.query("""
WITH grouped_sales AS (
    SELECT Year, Country, SUM(Quantity) AS Quantity, SUM(Sales) AS Sales, 
    FROM df
    GROUP BY Year, Country
    )
SELECT
    *
FROM
    grouped_sales
""")
# ComputeError: no table name provided in query

# It works with duckdb
import duckdb

duckdb.query("""
WITH grouped_sales AS (
    SELECT Year, Country, SUM(Quantity) AS Quantity, SUM(Sales) AS Sales, 
    FROM df
    GROUP BY Year, Country
    )
SELECT
    *
FROM
    grouped_sales
""")

┌───────┬─────────┬──────────┬────────┐
│ Year  │ Country │ Quantity │ Sales  │
│ int64 │ varchar │  int128  │ int128 │
├───────┼─────────┼──────────┼────────┤
│  2018 │ US      │      100 │   1000 │
│  2018 │ UK      │      200 │   2000 │
│  2019 │ US      │      300 │   3000 │
│  2019 │ UK      │      400 │   4000 │
│  2020 │ US      │      500 │   5000 │
│  2020 │ UK      │      600 │   6000 │
└───────┴─────────┴──────────┴────────┘
```

### Expected behavior

returning the result

### Installed versions

<details>

```
---Version info---
Polars: 0.17.3
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: 3.1.0
```

</details>

**Comment by alexander-beedie** [comment]
Do you have a small `df` for the example above?

**Comment by universalmind303** [comment]
@lucazanna I don't think the CTE changes are part of 0.17.3. You will have to wait until 0.17.4.

**Comment by lucazanna** [comment]
@alexander-beedie : I modified the reproducible example above, and I include creating a small Lazyframe

@universalmind303 : I saw the SQL CTE on the Polars release on GitHub: https://github.com/pola-rs/polars/releases

This means that the https://github.com/pola-rs/polars/pull/8208 is preparing for the CTEs but they are not available yet?

**Comment by universalmind303** [comment]
Sorry, ignore my comment, I didn't see the release from earlier.

**Comment by universalmind303** [comment]
so it actually appears to be an issue with the trailing comma in your select statement (which is not valid in all sql dialects). 

removing the trailing comma should result in a valid query. The error message is definitely misleading, and should be updated to better handle invalid syntax. 

This should work!
```sql
WITH grouped_sales AS (
    SELECT Year, Country, SUM(Quantity) AS Quantity, SUM(Sales) AS Sales
    FROM df
    GROUP BY Year, Country
    )
SELECT
    *
FROM
    grouped_sales
```

**Comment by universalmind303** [comment]
I opened up https://github.com/pola-rs/polars/issues/8267 which is specific to SQL error handling.

**Comment by lucazanna** [comment]
Clear. Thanks @universalmind303
