### ISSUE TITLE
SQL: better error handling for invalid queries. 

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#8267]
### Problem description

The errors for invalid sql queries are quite misleading. 

Ideally, The error should give some feedback as to why the query failed. 

For example. Given this sql with 2 trailing commas in the select statement: 

```sql
    SELECT Year, Country, SUM(Quantity) AS Quantity, SUM(Sales) AS Sales,,
    FROM df
    GROUP BY Year, Country
```
## polars
```
# ComputeError: no table name provided in query
```

## duckdb
```
duckdb.ParserException: Parser Error: syntax error at or near ","
LINE 2: ...ntity) AS Quantity, SUM(Sales) AS Sales,,
```

**Comment by alexander-beedie** [comment]
FYI: looks like we get a more detailed error from `sqlparser-rs` now.
Can probably close?
```
ComputeError: sql parser error: Expected an expression:, found: , at Line: ..., Column ...
```
