### ISSUE TITLE
Join on sorted column with Null -> "chunked array is not contiguous"

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#8269]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following code yields the following error:
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("chunked array is not contiguous"))
```

### Reproducible example

```python
import polars as pl

x = [0, 1, 0]
y = [0, None]

df1 = pl.DataFrame({"x": pl.Series(x)}).sort("x")
df2 = pl.DataFrame({"x": pl.Series(y)})
df1.join(df2, on="x")
```

### Expected behavior

No error.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---numpy: 1.24.1
pandas: 2.0.0
pyarrow: 10.0.1
connectorx: 0.3.1
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: 0.8
xlsxwriter: <not installed>
```

</details>

**Comment by s-banach** [comment]
[    // we can unwrap because we should not have nulls](https://github.com/pola-rs/polars/blob/4dcbde9025e05d1ab21b10a9b7d03293ebb3a822/polars/polars-core/src/frame/hash_join/sort_merge.rs#L95) 🤔

**Comment by ritchie46** [comment]
Ouch, willl fix that and patch a release soon!
