### ISSUE TITLE
Implicit Date to i32 Conversion in GroupBy on Struct

### ISSUE THREAD

**Issue by harrymconner** [pola-rs/polars#8271]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm using Polars to calculate [IRRs](https://en.wikipedia.org/wiki/Internal_rate_of_return) from financial data, which requires a column of dates and a column of floats. I bring the date and float columns into a struct then I pass the struct to a custom IRR function that is applied in a group by context.

Starting with version 0.17.3, my calculation is breaking because my custom IRR function expects dates, but the dates have been implicitly converted to i32. Reverting to 0.17.2 resolves the issue.

In the reproducible example below, I am simply printing out the dtypes after creating the LazyFrame then from within the custom function to show the date to i32 conversion. Interestingly, if I pass a single date series (not one contained within a struct) to the same custom function, the series does not get converted to i32.

### Reproducible example

```python
import datetime as dt

import polars as pl

df = pl.LazyFrame(
    {
        "date": [dt.date(2022, 12, 31), dt.date(2023, 3, 31)],
        "amount": [100.0, -110.0],
        "portfolio": ["A", "A"],
    }
).with_columns(dates_amounts=pl.struct("date", "amount"))

print(df.dtypes)


def irr_func(irr_struct: pl.Series) -> None:
    print(irr_struct.struct.field("date").dtype)
    ...


df.groupby(pl.col("portfolio")).agg(pl.col("dates_amounts").apply(irr_func)).collect()

# Unexpected Output
# [Date, Float64, Utf8, Struct([Field('date', Date), Field('amount', Float64)])]
# Int32
```

### Expected behavior

[Date, Float64, Utf8, Struct([Field('date', Date), Field('amount', Float64)])]
Date

### Installed versions

<details>

```
---Version info---
Polars: 0.17.3
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
This has been fixed in any of latest struct related fixes: #8334, #8346, #8348, #8349
