### ISSUE TITLE
glimpse() fails for lengthy column names

### ISSUE THREAD

**Issue by CodeCox** [pola-rs/polars#8273]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

glimpse() fails for **_lengthy_** column names

The error msg `ValueError: Sign not allowed in string format specifier` suggests that a number in the justifiy format string may be negative?

This line of code in `frame.py` might be the cause of the negative number?
```
 # limit the amount of data printed such that total width is fixed
        max_col_values = 100 - max_col_name - max_col_dtype
```

### Reproducible example

```python
colc = 'a' * 96
df = pl.DataFrame({colc: [11,22,33]})
df.glimpse()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[97], line 3
      1 colc = 'a' * 96
      2 df = pl.DataFrame({colc: [11,22,33]})
----> 3 df.glimpse()

File ~\mambaforge\envs\bears\Lib\site-packages\polars\dataframe\frame.py:3577, in DataFrame.glimpse(self, return_as_string)
   3574 # print individual columns: one row per column
   3575 for col_name, dtype_str, val_str in data:
   3576     output.write(
-> 3577         f"$ {col_name:<{max_col_name}}"
   3578         f" {dtype_str:>{max_col_dtype}}"
   3579         f" {val_str:<{min(len(val_str), max_col_values)}}\n"
   3580     )
   3582 s = output.getvalue()
   3584 if not return_as_string:

ValueError: Sign not allowed in string format specifier
```

### Expected behavior

same as this but with len() > 95, and of course use of the "..." in the column name as a 'truncation' to cater for width limit would be preferred to a failure! 

```
colc = 'a' * 95
df = pl.DataFrame({colc: [11,22,33]})
df.glimpse()
```
```
Rows: 3
Columns: 1
$ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa <i64> 11, 22, 33
```

### Installed versions

<details>

```
Polars: 0.17.3
```

</details>

**Comment by zundertj** [comment]
Thank you for reporting, I have fixed this in #8281.
