### ISSUE TITLE
Improve `read_excel` signature to avoid linting errors

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#8296]
### Problem description

I came across some linting issues recently with `read_excel` which could be improven imo

# Problems:

## Ugly linter errors:
- linting errors if you do not specify redundant `None` values
- documentation examples also have linting errors
![image](https://user-images.githubusercontent.com/25177421/232438036-f01fb442-15a8-4ac5-aee6-188529608363.png)
![image](https://user-images.githubusercontent.com/25177421/232438136-46275c68-e1e9-4072-bc0d-607c22add6c4.png)

## Avoid linter errors by specifying redundant `None` values:
- this should not be required to avoid linting errors
```python
pl.read_excel(
    source='sample.xlsx',
    sheet_id=0,
    sheet_name=None,  # <<<
)

pl.read_excel(
    source='sample.xlsx',
    sheet_id=None,  # <<<
    sheet_name='test',
)
```

## Bloated Documentation
- hard to read signature in documentation because of overloads
- only to make sure `sheet_id` and `sheet_name` are not both specified?
- This is very common and should only have a reminder in the docs to speficy only one of them
- also the very first method signature in the documentation is acutally unusable and not needed at all, or?
![image](https://user-images.githubusercontent.com/25177421/232438469-f45d05ed-35c9-4a9b-a35c-5e1fbb0c60b6.png)

# Suggestion:
- only 1 method! remove overloads and document that either `sheet_id` or `sheet_name` must be provided

### Sidenote
- replace `convert` in `sheet_id` ("Sheet number to convert") and `sheet_name` ("Sheet name to convert") documentation with `read`. I understand that the excel file is first converted into csv and then read but this is an implementation detail and confuses the user. From the user perspective I want to specify the name/id of the sheet I want to **read**

**Comment by MarcoGorelli** [comment]
thanks @JulianCologne for the report, looks like the overloads aren't quite right

**Comment by stinodego** [comment]
@JulianCologne could you open a separate issue for improving API docs of overloaded functions?
