### ISSUE TITLE
pl.Series + pl.duration should return pl.Series

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8301]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When adding a duration to a series, an expression is returned, whereas a Series should be returned.

### Reproducible example

```python
import polars as pl
from datetime import date

s = pl.Series([date(2023, 1, 1)])
s + pl.duration(days=1)
```
```
<polars.expr.expr.Expr object at 0x0000021D2D8206D0>
```

### Expected behavior

```
shape: (1,)
Series: 's' [date]
[
        2023-01-01
]
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.3
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.2_alpha.2
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ritchie46** [comment]
No `pl.duration` is an expression. If you add an expression to a `Series`, you get `pl.lit(Series) + Expr`. 

We shouldn't do any magic here, we cannot enforce it consistently,
