### ISSUE TITLE
In Rust when importing 0.28.0 with sql feature, 0.27.2 is automatically brought in as a dependency

### ISSUE THREAD

**Issue by osawyerr** [pola-rs/polars#8310]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When importing 0.28.0 with sql feature, 0.27.2 is automatically brought in as a dependency. This causes a conflict when using LazyFrame.

### Reproducible example

Add the below to the cargo.toml file
``polars = { version = "0.28.0", features = ["lazy", "parquet", "dtype-decimal", "sql"] }``

### Expected behavior

polars version 0.28.0 should be brought in as dependency. However, 0.27.2 seems to be brought in as well.

### Installed versions

<details>
"lazy", "parquet", "dtype-decimal", "sql"
</details>

**Comment by osawyerr** [comment]
using ``polars = { git = "https://github.com/pola-rs/polars", features = ["lazy", "sql", "parquet", "dtype-decimal"] }`` seemed to work.

**Comment by universalmind303** [comment]
Chances are you have 0.27.2 also installed in your cargo cache, and cargo is getting confused. 

i'd nuke your cargo.locks, then nuke your cache. 

When in doubt, I like using [cargo-cache](https://crates.io/crates/cargo-cache) to just hard nuke all cargo dependencies

**Comment by ritchie46** [comment]
Yes, you must remove all your lockfiles. I will close this as this is not something on our side.

**Comment by therealhieu** [comment]
I found that polars 0.28.0 still depends on polars-sql ^0.2. @ritchie46 @universalmind303 

https://crates.io/crates/polars/0.28.0/dependencies

<img width="966" alt="image" src="https://user-images.githubusercontent.com/38937534/233765794-df925287-65f0-4ef7-aaca-b76d1d58e5a0.png">

**Comment by universalmind303** [comment]
@ritchie46 this does seem to be valid issue. Maybe we could publish a new rust version? 

steps to reproduce

from a completely empty VM. 
```bash
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> rustup override set nightly
> cargo new pl_8310
> cd pl_8310
> cargo add polars --features sql,lazy
```

```rust
// src/main.rs

use polars::{prelude::*, sql::SQLContext};

fn main() {
    let df = df! {
      "a" => [],
    }
    .unwrap()
    .lazy();
    let mut ctx = SQLContext::try_new().unwrap();
    ctx.register("df", df).unwrap();
    let query = r#"
    SELECT * from df
    "#;
    ctx.execute(query).unwrap();
}
```

```bash
> cargo run 
```

```
  --> src/main.rs:10:24
   |
10 |     ctx.register("df", df).unwrap();
   |         --------       ^^ expected `polars_lazy::frame::LazyFrame`, found `LazyFrame`
   ```

**Comment by ritchie46** [comment]
> @ritchie46 this does seem to be valid issue. Maybe we could publish a new rust version?

Yes, this needs an updated arrow2. I have asked for a release. Is this fixed in main?
