### ISSUE TITLE
count(*) returns incorrect result when querying from parquet file

### ISSUE THREAD

**Issue by osawyerr** [pola-rs/polars#8316]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When you query from a parquet file, ``count(*)`` always returns the incorrect result of 1. However it works when you use the ``count(*)`` in a group by or you explicitly specify a column e.g. ``count(col_name)``

This was tried with multiple parquet files from different sources.

### Reproducible example

```
〉select count(*) from read_parquet('/Users/olo/Documents/customer_1681590885.0.parquet');
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ u32     │
╞═════════╡
│ 1       │
└─────────┘
〉select count(c_name) from read_parquet('/Users/olo/Documents/customer_1681590885.0.parquet');
shape: (1, 1)
┌─────────┐
│ c_name  │
│ ---     │
│ u32     │
╞═════════╡
│ 1040384 │
└─────────┘
〉select count(*), c_mktsegment from read_parquet('/Users/olo/Documents/customer_1681590885.0.parquet') group by c_mktsegment;
shape: (1, 2)
┌─────────┬──────────────┐
│ literal ┆ c_mktsegment │
│ ---     ┆ ---          │
│ u32     ┆ str          │
╞═════════╪══════════════╡
│ 1040384 ┆ AUTOMOBILE   │
└─────────┴──────────────┘

```

### Expected behavior

Should return the correct count. In the above example, it should be 1040384.

### Installed versions

<details>
cli,parquet,csv,ipc,highlight
</details>

**Comment by ritchie46** [comment]
Can you make a minimal example that creates the parquet file and shows the wrong result?

**Comment by osawyerr** [comment]
This issue exists for any parquet file. Steps to reproduce:
1. Download any sample parquet file
2. Run polars-sql ``polars-sql % cargo run --release --features=cli,parquet,csv,ipc,highlight
``
3. Run the command ``select count(*) from read_parquet('/path/to/file.parquet')``
4. Incorrect ``count(*)`` results are observed.

**Comment by ritchie46** [comment]
Does this also occur in python if you use the lazy frame api?

**Comment by osawyerr** [comment]
I haven’t tried it in python. Have you been able to reproduce the issue using the rust cli as I described?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by osawyerr** [comment]
Oh. For a mature project it's surprising that's not supported yet. Seems like the first query anyone would run when they get a dataset.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by s-banach** [comment]
The SQL interface is not mature, but you can easily count distinct with the regular interface.

**Comment by osawyerr** [comment]
How is this closed…? It’s still a bug.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by osawyerr** [comment]
Ah I see. It's fixed in another ticket. Makes sense.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
