### ISSUE TITLE
ldf.limit returning no rows with scan_parquet

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#8328]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description
(I've updated this issue based on my comment below)

With the following lazy code, my 3-length parquet file shows 0 rows. Using non-lazy it works as expected.

I am observing this behaviour only in a Debian aarch64 docker container on my mac. Not in a python venv on regular MacOS.
I run `pip install --force-reinstall 'polars[all]'` before running the script below. 

I'm able to reproduce it with a minimal example (don't need to download the above .zip):

```python
# run.py
import polars as pl
print(pl.__version__)

pl.DataFrame({"a": [1, 2, 3]}).write_parquet("test2.parquet")
print(pl.scan_parquet("test2.parquet").limit(10).collect().shape)
print(pl.read_parquet("test2.parquet").limit(10).shape)
print(pl.scan_parquet("test2.parquet").head(10).collect().shape)
print(pl.read_parquet("test2.parquet").head(10).shape)
```

On MacOS:
```
python run.py
0.17.5
(3, 1)
(3, 1)
(3, 1)
(3, 1)
```
In debian:
```
python run.py
0.17.5
(0, 1)
(3, 1)
(0, 1)
(3, 1)
```

### Expected behavior

The length should be the same.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.5
Index type: UInt32
Platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
Python: 3.10.11 (main, Apr  6 2023, 00:10:13) [GCC 10.2.1 20210110]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 8.0.0
connectorx: <not installed>
deltalake: 0.8.1
fsspec: 2023.4.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by stijndegooijer** [comment]
Quick question: what happens if you use `.head(10)` instead of `limit`?

**Comment by ritchie46** [comment]
I cannot reproduce this?

**Comment by thomasaarholt** [comment]
I am observing this behaviour only in a Debian aarch64 docker container on my mac. Not in a python venv on regular MacOS.
I run `pip install --force-reinstall 'polars[all]'` before running the script below. 

I'm able to reproduce it with a minimal example (don't need to download the above .zip):

```python
# run.py
import polars as pl
print(pl.__version__)

pl.DataFrame({"a": [1, 2, 3]}).write_parquet("test2.parquet")
print(pl.scan_parquet("test2.parquet").limit(10).collect().shape)
print(pl.read_parquet("test2.parquet").limit(10).shape)
print(pl.scan_parquet("test2.parquet").head(10).collect().shape)
print(pl.read_parquet("test2.parquet").head(10).shape)
```

On MacOS:
```
python run.py
0.17.5
(3, 1)
(3, 1)
(3, 1)
(3, 1)
```
In debian:
```
python run.py
0.17.5
(0, 1)
(3, 1)
(0, 1)
(3, 1)
```

**Comment by stinodego** [comment]
I do not have the right system to reproduce this. As it's an old issue and we have made many changes to the parquet reader, I am closing this. If you still experience this issue on the latest Polars, please open a new issue!
