### ISSUE TITLE
pl.Series.mean and pl.Series.median return None for type Boolean

### ISSUE THREAD

**Issue by etiennekintzler** [pola-rs/polars#833]
I am using **Python**, **polars version 0.8.5**.

Have this issue on **both Windows** (W10) and **Linux** (Ubuntu 20.04.1 LTS focal x86_64)

### Description of the bug

The methods `pl.Series.mean` and `pl.Series.median` return  `None` for a Series of type `Boolean`.

```python
import polars as pl

lst_bool = [True, True, False]
s = pl.Series(lst_bool)

print(s.mean() is None) # True
print(s.median() is None) # True
```

### Expected behavior 

I didn't expect a `None` return. What was expected : 
- implicit cast of boolean to int and returns `0.666666` in the case of `pl.Series.mean`
- return `True` in the case of `pl.Series.median`

These two expected returns is what is returned by the function `mean` and `median` from the `statistics` module (from stdlib):

```python
from statistics import mean, median

print(mean(lst_bool)) # 0.6666666666666666
print(median(lst_bool)) # True
```

or from `numpy` (median is 1.0 however)

```python
import numpy as np
arr = np.array(lst_bool)
print(np.mean(arr)) # 0.6666666666666666
print(np.median(arr)) # 1.0
```

### Returns type for min/max
Semi-related with this issue but `pl.Series.min` and `pl.Series.max` returns `0` and `1` (respectively) when you expect `False` and `True` (as in numpy or base python):

```python
print(min(lst_bool) == np.min(arr) == False) # True
print(max(lst_bool) == np.max(arr) == True) # True
print(s.min()) # 0
print(s.max()) # 1
```

**Comment by ritchie46** [comment]
It was sort of by design. But I'll see if I can add some implicit casts.

**Comment by ritchie46** [comment]
This has been added and released👍
