### ISSUE TITLE
Give sort ability to accept dictionary in the by parameter where keys are columns and values are bool of descending or not

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#8360]
### Problem description

for instance...

instead of `df.sort(['a','b','c'], descending=[True, False, True])`

we could do `df.sort({'a':True,'b':False,'c':True})`

This could be implemented by checking if the `by` parameter is a `dict` and then reverting to this behavior.

Alternatively, it could be its own method like `df.dsort` or something.

**Comment by mcrumiller** [comment]
I don't think the dict should be the first parameter, but rather enable the `descending` parameter to optionally be a dictionary, as in:

```python
df.sort(['a', 'b', 'c'], descending = {'c': True, 'b': False, 'a': True})
```

**Comment by avimallu** [comment]
If you're looking for a way to do that right now, something like this should work:

```
import polars as pl
d = {'a':True,'b':False,'c':True}

(
    pl.DataFrame({
        "a": np.random.randint(0, 10, 100),
        "b": np.random.randint(0, 10, 100),
        "c": np.random.randint(0, 10, 100)})
    .sort(list(d.keys()), descending=list(d.values()))
)
```

and if you're looking for a shorter version than `list(d.keys())`, you should be able to create a rather trivial function to do that:

```
def _c(d):
    return list(d.keys())

def _o(d):
    return list(d.values())
    
d = {'a':True,'b':False,'c':True}

(
    pl.DataFrame({
        "a": np.random.randint(0, 10, 100),
        "b": np.random.randint(0, 10, 100),
        "c": np.random.randint(0, 10, 100)})
    .sort(_c(d), descending=_o(d))
)
```

I'm not quite sure why `d.values()` is not recognized as a Sequence:

```
d = {'a':True,'b':False,'c':True}

(
    pl.DataFrame({
        "a": np.random.randint(0, 10, 100),
        "b": np.random.randint(0, 10, 100),
        "c": np.random.randint(0, 10, 100)})
    .sort(d.keys(), descending=d.values())
)
```

Errors as:  `argument 'descending': 'dict_values' object cannot be converted to 'Sequence'`.

**Comment by deanm0000** [comment]
@mcrumiller but that's both redundant and more typing.

@avimallu I don't really like having to write the sort dict to a variable first both because it interrupts the chaining and because it's extra typing

Here's the monkey patched version:

```
def sortD(self, sortdict, **kwargs):
    return self.sort(list(sortdict.keys()), descending=list(sortdict.values()), **kwargs)
pl.DataFrame.sortD=sortD
del sortD
```

then we can do

```
df.sortD({'a':True, 'b':False, 'c':True})
```
