### ISSUE TITLE
Deprecate `groupby.agg({"foo": "sum"})`

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#8368]
This is just another way to do things and to is really unneeded given the power of the expression API.

Any objections to deprecating this? IMO `.agg` should only accept expressions.

**Comment by mcrumiller** [comment]
Sounds good to me, I always hated supplying functions as strings.

**Comment by ritchie46** [comment]
Even better it wasn't even supported it just didn't error out yet. Currently passing this will always lead to a `col("foo")` expression which is highly unexpected. Will ensure we raise an hard error.
