### ISSUE TITLE
Series.to_numpy(zero_copy_only=False) errors for dtype Boolean only when pyarrow is missing

### ISSUE THREAD

**Issue by hexane360** [pola-rs/polars#8393]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`Series.to_numpy` raises an error for Boolean series, but only when `pyarrow` is not installed. I would expect that this behavior works regardless. As an aside, I would also expect that a time Series would raise when zero_copy_only=True, which also doesn't seem to be the case.

I'm not quite sure if this is a feature request or bug report (based on what the expected behavior is). However, the error is new in version 0.17.5 vs version 0.15.

`to_numpy` gives the following output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/colin/Documents/code/python/structlib/venv2/lib/python3.11/site-packages/polars/series/series.py", line 3256, in to_numpy
    np_array = self._s.to_numpy()
               ^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: 'to_numpy' not supported for dtype: Boolean
```

I believe the relevant code is [here](https://github.com/pola-rs/polars/blob/0c7088b7651f5c1e7ac2ed989ec52e0278e4dd1b/py-polars/polars/series/series.py#L3255).

### Reproducible example

```python
import polars as pl

try:
    import pyarrow
    raise RuntimeError("Behavior only appears without pyarrow installed")
except ImportError:
    pass

s = pl.Series([1, 0, 0, 1], dtype=pl.Boolean)
s.to_numpy(zero_copy_only=False)
```

### Expected behavior

```python
>>> s = pl.Series([1, 0, 0, 1], dtype=pl.Boolean)
>>> s.to_numpy(zero_copy_only=False)
array([ True, False, False,  True])
```

This is also the current behavior when `pyarrow` is installed.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.5
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.11.3 (main, Apr  8 2023, 02:16:51) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.24.2
pandas: <not installed>
pyarrow: <not installed>
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by jonashaag** [comment]
I‘m working on a fix for this (and some related tickets)
