### ISSUE TITLE
Add `at` or  `scalar_one` to access single value

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pola-rs/polars#8406]
### Problem description

I often have queries where the outcome a single row where I want one number as a native python type to use further on. Today the I have to do something like:

```python 
x = df.to_dicts()[0]["my_column"]
```

I suggest adding something like `at` in pandas (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html) to have

```python 
x = df.at[0,"my_column"]
```
Another (maybe better) alternative could be to add something similar to `scalar_one` in SQLAlchechmy (https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.scalar_one). This would also give the added benefit of a check which ensures there is on and only one row as it raises an error if this is not the case. That would look something like:

```python 
x = df.scalar_one("my_column")
```

I know this is not a major gain but I definitely see it as a quality of life improving feature :-)

**Comment by cmdlineluser** [comment]
Is this what `.item` is for? [`df["my_column"].item()`](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.item.html#polars.Series.item)

**Comment by alexander-beedie** [comment]
Already exists as a selector; not sure we really need a new method for it, though could probably add an optional "column" param to `row`, which would probably be more discoverable 🤔 
```python
df[ 0,"my_column" ]
```

**Comment by alexander-beedie** [comment]
> Is this what `.item` is for? [`df["my_column"].item()`](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.item.html#polars.Series.item)

Almost, but not quite; `item` is for unpacking a 1x1 frame (equivalent to `df[0,0]`).

**Comment by ritchie46** [comment]
I don't think we need a new method for this. I don't want a loc, iloc, at, ... Situation.

**Comment by alexander-beedie** [comment]
Indeed; I'm going to allow `item` to take optional row/col params. If not supplied, we will preserve _identical_ behaviour - if given, we get a more discoverable form of `df[row,col]`.

**Comment by alexander-beedie** [comment]
@thomasfrederikhoeck: done... just made it into 0.17.6: `df.item(0,"colname")`
