### ISSUE TITLE
[rust] Extra closing parenthesis returned by the `DataFrame.describe` method.

### ISSUE THREAD

**Issue by wiseaidev** [pola-rs/polars#8407]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

This issue is not that important. But, [while doing EDA on the Iris Dataset](https://github.com/wiseaidev/rust-data-analysis/blob/main/1-iris-data-analysis-rust.ipynb#describe) in a Rust Kernel,  I found that this method adds a redundant closing parenthesis at the end of the table.

### Reproducible example

You can refer to [this rusty kernel](https://github.com/wiseaidev/rust-data-analysis/blob/main/1-iris-data-analysis-rust.ipynb#describe) for more info. Notice a redundant closing parenthesis at the end of the table.
![Screenshot from 2023-04-21 11-06-53](https://user-images.githubusercontent.com/62179149/233579915-598dffa2-5c90-4c2a-ad2e-5feddc972223.png)

### Expected behavior

Just return a clean and dandy table like the other methods.

### Installed versions

Any.

**Comment by uchiiii** [comment]
As far as I guess, you forget to add `?` at the end of `iris_df.describe(None)`. Could you try it again?
reference: https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.describe

**Comment by wiseaidev** [comment]
Thanks for the response @uchiiii, That's right! I forgot to unwrap the `PolarsResult` object into a `DataFrame`.
