### ISSUE TITLE
SQL: error on window function 

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8419]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The SQL window function returns `ComputeError: at least one key is required in a groupby operation`

### Reproducible example

```python
import polars as pl

df = pl.LazyFrame({
    'Year': [2018, 2018, 2019, 2019, 2020, 2020],
    'Country': ['US', 'UK', 'US', 'UK', 'US', 'UK'],
    'Sales': [1000, 2000, 3000, 4000, 5000, 6000]
})

sql = pl.SQLContext()
sql.register('df', df)

sql.query("""
SELECT
    Country,
    Sales,
    SUM(Sales) OVER (ORDER BY Sales DESC) AS SalesCumulative
FROM
    df
ORDER BY
    SalesCumulative
""")
# This returns the error ComputeError: at least one key is required in a groupby operation

# It works ok with duckdb
import duckdb

duckdb.query("""
SELECT
    Country,
    Sales,
    SUM(Sales) OVER (ORDER BY Sales DESC) AS SalesCumulative
FROM
    df
ORDER BY
    SalesCumulative
""")

┌─────────┬───────┬─────────────────┐
│ Country │ Sales │ SalesCumulative │
│ varchar │ int64 │     int128      │
├─────────┼───────┼─────────────────┤
│ UK      │  6000 │            6000 │
│ US      │  5000 │           11000 │
│ UK      │  4000 │           15000 │
│ US      │  3000 │           18000 │
│ UK      │  2000 │           20000 │
│ US      │  1000 │           21000 │
└─────────┴───────┴─────────────────┘
```

### Expected behavior

No error

### Installed versions

<details>

```
---Version info---
Polars: 0.17.6
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: 3.1.0
```

</details>

**Comment by lucazanna** [comment]
copying @universalmind303.
Maybe there is something wrong with my query?

**Comment by mcrumiller** [comment]
I think your issue is this line:

```sql
SUM(Sales) OVER (ORDER BY Sales DESC) AS SalesCumulative
```

You don't specify what the sum is over, you only specify how to order. I think you meant:

```sql
SUM(Sales) OVER (Country) ORDER BY (Sales DESC) AS SalesCumulative
```

**Comment by universalmind303** [comment]
we don't yet support cumulative functions via SQL, or anything without `PARTITION BY` in window functions. 

There is a native `cumsum` function in polars, So I'm wondering if it'd be more intuitive to expose that directly instead of _(or in addition to)_ window functions. 

## Via window function. 
```sql
SELECT
    Country,
    Sales,
    SUM(Sales) OVER (ORDER BY Sales DESC) AS SalesCumulative
FROM
    df
```

## Proposed `CUMSUM` function
```sql
SELECT
    Country,
    Sales,
    CUMSUM(Sales DESC) as SalesCumulative
FROM
    df
```

**Comment by lucazanna** [comment]
hi @universalmind303 ,

thank you for your reply! your proposed solution with CUMSUM would take care of my use case.

As Polars gets more widely adopted, I would think that having full support for windows functions would be beneficial.
One of the reasons for using SQL (at least for me) is to be able to reuse synthax from other tools / be already familiar with the syntax. So keeping the syntax would be a plus.

What do you think?

A counterpoint can be made that SQL has lots of dialects so inevitably each tool will work differently. However these options for the window function seem accepted and implemented by different tools: Postgres, Spark SQL, SQL Server,
