### ISSUE TITLE
`Decimal` values in `Series` off by factor of a quadrillion when read out using `to_list()`

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#8423]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Decimal values can be scaled by enormous multipliers when read out using `to_list`.

### Reproducible example

**Setup:**

```python
from decimal import Decimal
import polars as pl

with pl.Config( activate_decimals=True ):
    s = pl.Series(
        name = "dec", 
        values = [Decimal('-1.3492'),Decimal('0.00058910')], 
    )

# Series: 'dec' [decimal[8]]
# [
#   -1.3492
#   0.0005891
# ]
```

**Succeeds:** _(indexing, list init, pyarrow 'to_list')_

```python
s[0]
# Decimal('-1.34920000')

list(s)
# [Decimal('-1.34920000'), Decimal('0.00058910')]

s.to_list( use_pyarrow=True )
# [Decimal('-1.34920000'), Decimal('0.00058910')]
```

**Fails:** _(native 'to_list' causes scaling)_

```python
s.to_list()
# [Decimal('-1.34920000E+16'), Decimal('5.8910E+12')]    << scale-factor (one quadrillion :) applied
```

### Expected behavior

Scaling should not occur in `to_list`.

### Installed versions

<details>
Replace this line with a list of feature gates
</details>

**Comment by cgevans** [comment]
This is a sign error in the scale when converting to a Python Decimal.  I'm working on a pull request.
