### ISSUE TITLE
Create `DataFrame` from json have garbled code

### ISSUE THREAD

**Issue by zemelLeong** [pola-rs/polars#8424]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

As the title indicates. If the json string exists `\n` and `Chinese characters`. DataFrame create result will be garbled code

### Reproducible example

```rust
use serde_json::json;
use std::io::Cursor;

use polars::prelude::*;

fn main() {
    let json_data = json!([{
        "id": 8,
        "name": "小P",
        "exception": "你好，polars。\n",
        "normal": "你好，polars。",
        "姓\n名": "小P",
    }]);
    let json_data_str = json_data.to_string();
    let json_cursor = Cursor::new(json_data_str);
    let df = JsonReader::new(json_cursor).finish().unwrap();
    println!("{:?}", df);
}
```

### Run result
```
shape: (1, 5)
┌─────────────────┬─────┬──────┬────────────────┬────────────┐
│ exception       ┆ id  ┆ name ┆ normal         ┆ å§         │
│ ---             ┆ --- ┆ ---  ┆ ---            ┆ å          │
│ str             ┆ i64 ┆ str  ┆ str            ┆ ---        │
│                 ┆     ┆      ┆                ┆ str        │
╞═════════════════╪═════╪══════╪════════════════╪════════════╡
│ ä½ å¥½ï¼polarsã ┆ 8   ┆ 小P  ┆ 你好，polars。 ┆ 小P        │
│                 ┆     ┆      ┆                ┆            │
└─────────────────┴─────┴──────┴────────────────┴────────────┘
```

![image](https://user-images.githubusercontent.com/26835087/233765296-e2947e01-68a5-484c-9201-9bd202488483.png)

### Expected behavior

Expect the result be normal.

### Installed versions

<details>
serde = { version = "1.0", features = ["derive"] }  <br />
serde_json = "1.0.68"  <br />
polars = { version = "0.28.0", features = ["json", "lazy", "serde"] }  <br />
polars-sql = "0.28.0"
</details>

**Comment by universalmind303** [comment]
this seems to be a bug in the upstream parser. I opened up an issue in that repo with a minimum example
https://github.com/jorgecarleitao/json-deserializer/issues/22

**Comment by zemelLeong** [comment]
When can it be released? is any plan?
