### ISSUE TITLE
Polars should handle datetime arithmetic better

### ISSUE THREAD

**Issue by olivier-lacroix** [pola-rs/polars#843]
#### Are you using Python or Rust?
**Python**

#### Which feature gates did you use?

NA

#### What version of polars are you using?

0.8.6

#### What operating system are you using polars on?

Linux

#### Describe your bug.

Polars does not guard against unsupported arithmetic operations on Dates, and does not cast differences to a Duration type

#### What are the steps to reproduce the behavior?

Perform arithmetic operations on Date32 or Date64 colums (*, -, +, etc.)

#### What is the actual behavior?

```python
import polars as pl
from polars import col

df = pl.DataFrame({"a":["2021-03-01","2020-03-01"],"b":["2021-03-02","2021-04-01"]}).select([col(c).cast(pl.datatypes.Date32) for c in ["a","b"]])

# Returns dates
df["b"]-df["a"] 

# Returns dates
df["b"]+df["a"] 

# Panics with PanicException: invalid or out-of-range datetime 
df["b"]*df["a"] 
```

#### What is the expected behavior?

```python
import polars as pl
from polars import col

df = pl.DataFrame({"a":["2021-03-01","2020-03-01"],"b":["2021-03-02","2021-04-01"]}).select([col(c).cast(pl.datatypes.Date32) for c in ["a","b"]])

# Returns durations
df["b"]-df["a"] 

# Panics, stating Dates can't be added together
df["b"]+df["a"] 

# Panics, stating Dates can't be multiplied together
df["b"]*df["a"] 
```

**Comment by ritchie46** [comment]
This is addressed in #857 .

On subtraction the numeric values are returned. E.g. `Int32` and `Int64` for `Date32` and `Date64` respectively. Not duration, as I think I am going to drop support of that datatype.

**Comment by olivier-lacroix** [comment]
@ritchie46, great!

On a side note, I do think that handling duration and datetime arithmetic, frequencies, etc. is an important feature of a dataframe library (and one where pandas is pretty good), but I understand that this is quite dependent of use cases and may not be a high priority for polars.

**Comment by ritchie46** [comment]
Fixed and released
