### ISSUE TITLE
Unable to use sink_parquet() for LazyFrame created from repeat/concat Expression

### ISSUE THREAD

**Issue by talawahtech** [pola-rs/polars#8443]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When I attempt to sink a parquet file created with a repeat/concat expression I get the following error" `sink_parquet not yet supported in standard engine`. The use-case is that I have a list of values and counts and I want to expand that to a column of repeating values without running out of memory.

Is there another way to get sink_parquet() to work with a LazyFrame created from this expression?

### Reproducible example

```python
import polars as pl

dummy_ldf = pl.DataFrame().lazy()

ldf = dummy_ldf.select(pl.concat([pl.repeat(x, n=1000) for x in range(250, 350)]))
ldf.sink_parquet("test.parq")

Output: thread '<unnamed>' panicked at 'sink_parquet not yet supported in standard engine. Use 'collect().write_parquet()''
```

### Expected behavior

sink_parquet() should work with LazyFrames created from repeat/concat Expressions.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.7
Index type: UInt32
Platform: Linux-5.4.238-155.347.amzn2int.x86_64-x86_64-with-glibc2.10
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]
---Optional dependencies---
numpy: 1.21.6
pandas: 1.3.4
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
We know. We are still working on the streaming API. I will close this as it doesn't have much value yet to open issues until we claim streaming to be in beta.

**Comment by talawahtech** [comment]
@ritchie46 just checking if steaming is now considered beta and this can be reopened? I just confirmed that the issue still happens with the following minimal test cases:

```
lf = pl.LazyFrame().select(pl.repeat(250, n=1000))
lf.sink_parquet("sink-repeat.parq")
```

```
lf = pl.LazyFrame().select(pl.int_range(0, 100))
lf.sink_parquet("sink-range.parq")
```

**Comment by cmdlineluser** [comment]
I did just read on Discord that there is a new and improved streaming engine currently in the works:

> We have started a complete rewrite. One that can do push and pull based morsel drive paralellism and therefor can execute dags, where a node can push into multiple parents.  

(I'm guessing that may delay the beta status somewhat.)

<sub>1. https://discord.com/channels/908022250106667068/908022461751234570/1241655449917591583</sub>

**Comment by talawahtech** [comment]
@cmdlineluser interesting! Thanks for the link.
