### ISSUE TITLE
Performance slower than numpy(+numba) when doing column standardization

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#8455]
### Problem description

Please see below for the benchmarking results for performing single column standardization comparing ```Polars``` and ```Numpy```.
```
import timeit
import numpy as np
import polars as pl

a = np.random.normal(size=1000)
s = pl.Series(a)

>>> timeit.timeit(lambda: (a - a.mean()) / a.std(), number=100000)
3.01329
>>> timeit.timeit(lambda: (s - s.mean()) / s.std(ddof=0), number=100000)
6.05679
```

Basically, it can be seen that ```Polars``` is roughly 2x slower than ```Numpy``` for getting the same results (although the data structure of the outputs are different - one is ```Polars Series``` and one is ```Numpy 1D Array```).

What's more, if I use ```Numba``` to speed up the ```Numpy``` code above, I can get much faster performance (~10x) even including ```Numba``` jit compilation overhead as shown below.
```
from numba import jit

@jit(nopython=True, fastmath=True)
def standardize(x):
    return (x - x.mean()) / x.std()

>>> timeit.timeit(lambda: standardize(a), number=100000)
0.64746
```

And, if we run the benchmark for the ```Numba``` function again (basically without considering jit compilation overhead this time), I can get even faster performance (another ~2.5x).
```
>>> timeit.timeit(lambda: standardize(a), number=100000)
0.25074
```

To sum up, for performing standardization of a single array/column,
- ```Numpy``` native version is ~2x faster than ```Polars``` version.
- When using ```Numba``` accelerated jit function, the performance is nearly ~12x faster then ```Polars``` after considering jit compilation overhead, and ~25x without considering the overhead.

I think it should be fair to assume/expect ```Polars``` version should have similar performance as ```Numba``` accelerated version without considering compilation overhead, because what ```Numba``` basically does is to do just-in-time compilation to machine code and ```Rust``` should have the same capability (or maybe even better?) and it can pre-compile the code (so no need to do jit compilation).

**EDIT**
Add benchmarking retults without using ```fastmath=True``` in ```Numba```.
```
@jit(nopython=True)
def standardize2(x):
    return (x - x.mean()) / x.std()

>>> timeit.timeit(lambda: standardize2(a), number=100000)
1.92395
>>> timeit.timeit(lambda: standardize2(a), number=100000)
0.64522
```

**Comment by ritchie46** [comment]
Why? You are using fast math and you compile the whole numba expression. The compiler has much more information in that case, and fast math doesn't have to provide results with the same accuracy.

Polars doesn't have the same information during compilation. You can give it that information by using pyo3-polars.

**Comment by paladin158** [comment]
> 

How to give the compile information by using pyo3-polars?

I don't know much about ```Numba```, but in this case, it seems like there are not so much more information the compiler have?

Also, the ```Numba``` section is for more illustration about what I can do in python. But even comparing with barebone ```Numpy``` version, we still have ~2x slower performance.

**Comment by paladin158** [comment]
To me, for such a simple example, I think ```Rust``` can achieve similar performance as ```Numba```?

**Comment by ritchie46** [comment]
> To me, for such a simple example, I think Rust can achieve similar performance as Numba?

You are not comparing rust with numba. You are comparing polars expression interpreter against a compiled function. It is not a fair comparison, as polars has not precompiled `(x - x.mean()) / x.std())` so it must interpret that.

**Comment by MarcoGorelli** [comment]
> Basically, it can be seen that Polars is roughly 2x slower than Numpy for getting the same results

Is this always the case? Growing your example from 1000 to 1_000_000 observations, it doesn't seem to hold:
```python
import numpy as np
import polars as pl

a = np.random.normal(size=1_000_000)
s = pl.Series(a)

%timeit (a - a.mean()) / a.std()
# 5.13 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit (s - s.mean()) / s.std(ddof=0)
# 4.89 ms ± 305 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by deanm0000** [comment]
@stinodego I think closable.
