### ISSUE TITLE
No exception on Float64 out of range cast to Float32

### ISSUE THREAD

**Issue by lukeshingles** [pola-rs/polars#8456]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When casting an Float64 inf to Int64, there is an exceptions.ComputeError. When casting Float64 to Float32 for an unrepresentable number, there is no exception.

### Reproducible example

```python
import polars as pl
s = pl.Series([float("inf"), 1e39], dtype=pl.Float64)
s.cast(pl.Float32)
s.cast(pl.Int64)
```

### Expected behavior

exceptions.ComputeError: strict conversion from `f64` to `f32` failed for value(s) [1.0000e39]

### Installed versions

<details>

```
---Version info---
Polars: 0.17.7
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.24.3
pandas: 2.0.0
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by cjackal** [comment]
Polars' casting behavior is inherited from pyarrow(or arrow2, though both should coincide):

```python
s.to_arrow().cast("float32")  # no error, no warning
s.to_arrow().cast("int64")  # ArrowInvalid
```

Though I wonder if polars can provide an equivalent of `pyarrow.compute.CastOptions`.

**Comment by Wainberg** [comment]
This gives a warning in NumPy and pandas:

```python
>>> np.array([1e39]).astype('float32')
<stdin>:1: RuntimeWarning: overflow encountered in cast
array([inf], dtype=float32)
```

```python
>>> pd.Series([1e39]).astype('float32')
.../python3.12/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)
0    inf
dtype: float32
```

@stinodego thoughts on giving a warning here by default? Seems useful for preventing bugs.

**Comment by stinodego** [comment]
Seems like currently the big number is converted into a `float("inf")`. That is definitely undesirable in a strict cast.

**Comment by orlp** [comment]
Actually, a strict cast throws an exception when the cast *couldn't* be done, but in the case of floats this can always be done since both `f64` and `f32` have range `(-inf, inf)`.

This isn't just limited to casting, in general IEEE-754 floats are completely closed. For example addition or multiplication automatically convert to infinity when the result becomes too large, and this is the expected behavior:

```python
>>> x = 1e308
>>> x
1e+308
>>> x + x
inf
>>> 1e309
inf
```

I'd love to add a custom warning/error mechanic at some point so you could add a check yourself, but I don't think this should warn/error by default.
