### ISSUE TITLE
Segmentation fault calling pl.concat/pl.select with a certain number of Expressions

### ISSUE THREAD

**Issue by talawahtech** [pola-rs/polars#8459]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Python Polars segfaults if I try to pl.concat/pl.select an array of 1347+ expressions. I am not sure if that is a general limit or if that number is specific to my machine.

### Reproducible example

```python
import polars as pl

# Works
df = pl.select(pl.concat([pl.lit(x) for x in range(0, 1346)]))

# Segfaults
df = pl.select(pl.concat([pl.lit(x) for x in range(0, 1347)]))
```

### Expected behavior

The dataframe should be created, or a user friendly error message should be emitted if there is a hard limit.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.7
Index type: UInt32
Platform: Linux-5.4.238-155.347.amzn2int.x86_64-x86_64-with-glibc2.10
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]
---Optional dependencies---
numpy: 1.21.6
pandas: 1.3.4
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by avimallu** [comment]
I don't think this is consistent across platforms. For me, this varies (some runs it is 1239, some others I got 1249):

```py
import polars as pl
for i in range(1000, 20000):
    df = pl.select(pl.concat([pl.lit(x) for x in range(0, i)]))
    print(i, end="\r") # to avoid littering the console
```

Version:

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2022.11.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

**Comment by ritchie46** [comment]
It is a stackoverflow during recursion on our side. We cannot know the limit as it depends on your stack size.
