### ISSUE TITLE
```polars.Expr.dt.offset_by``` not working with the last day of February in a leap year

### ISSUE THREAD

**Issue by denis-zahariev** [pola-rs/polars#8474]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a dataframe contains a date, which is the last day of February in a leap year, the offset_by method throws an error when offsetting with 12 months. In earlier versions of polars (e.g. ```0.17.0```) this did not result in an error.

### Reproducible example

```python
from datetime import date
import polars as pl


df = pl.DataFrame({"date": [date(2024, 2, 29)]})
df.with_columns(pl.col("date").dt.offset_by("1y"))
```

### Expected behavior

The offset_by call should return a date without throwing an error. Whether the returned date is 2025-02-28 or 2025-03-1 is open to debate, but at least something should be returned. 

### Installed versions

<details>

```
---Version info---
Polars: 0.17.7
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.1
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by MarcoGorelli** [comment]
Thanks @denis-zahariev for the report

In the latest version, you can use `12mo_saturating`:
```python
In [2]: from datetime import date
   ...: import polars as pl
   ...:
   ...:
   ...: df = pl.DataFrame({"date": [date(2024, 2, 29)]})
   ...: df.with_columns(pl.col("date").dt.offset_by("12mo_saturating"))
Out[2]:
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2025-02-28 │
└────────────┘
```

Having a `y_saturating` option sounds like a reasonable request

**Comment by ritchie46** [comment]
> Having a y_saturating option sounds like a reasonable request

Yes! :)

**Comment by mcrumiller** [comment]
Can I suggest that we change that to an extra `saturating` argument (and rename it)? "12mo_saturating" feels weird. The word "saturate" isn't a great one: it typically means to *increase* until full, but in this case we want to *truncate*. The word *saturate* implies that Feb 28 + "1mo_saturating" means March 31st, when I don't think it does.

I would suggest `clip=True` or `clip_monthend=True`, but I'm sure there are better keywords. IMO that's a bit more obvious.

**Comment by MarcoGorelli** [comment]
the issue with extra keywords is that then they need to be added to all places which accept durations, and there's quite a lot

**Comment by mcrumiller** [comment]
Ahh ok. Yeah I agree that would be a pain. And if the word is used elsewhere than I'm not as against it; I still think it's not a great word but I can live with that.

**Comment by ritchie46** [comment]
Yes, and I really want to minimize arguments controlling the behavior of other arguments. That's iffy IMO.
