### ISSUE TITLE
ComputeError with window function on empty frame

### ISSUE THREAD

**Issue by connor-elliott** [pola-rs/polars#8477]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In 0.17.5 and prior the below select statement would return a 0x1 df whereas now it throws a `exceptions.ComputeError: the length of the window expression did not match that of the group` and wanted to clarify if the <=0.17.5 behavior or the current behavior is intended.

### Reproducible example

```python
import polars as pl
from polars import col

expr = (col("VAL") / col("VAL").sum()).over("KEY")

df = pl.DataFrame(schema={"KEY": pl.Utf8, "VAL": pl.Float64})
df.select(expr) # ComputeError

lf = pl.DataFrame(schema={"KEY": pl.Utf8, "VAL": pl.Float64}).lazy()
lf.select(expr).collect() # ComputeError
```

### Expected behavior

<=0.17.5 behaviour

### Installed versions

<details>

```
---Version info---
Polars: 0.17.8
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.11.0 (main, Jan 16 2023, 08:17:56) [Clang 14.0.6 ]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 10.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by stinodego** [comment]
Another minimal repro (I was just working on this):

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame(
    schema={
        "group": pl.Int16,
        "cost_price": pl.Float64,
    }
)

result = df.with_columns((pl.col("cost_price") / pl.col("cost_price").sum()).over("group"))
assert_frame_equal(result, df)
```
