### ISSUE TITLE
[Feature request] Add a null_values argument to read_csv and scan_csv

### ISSUE THREAD

**Issue by olivier-lacroix** [pola-rs/polars#848]
Hello,

Having an equivalent of pandas read_csv `na_values` argument for polars `read_csv` and `scan_csv` could prove useful, to transform a set of values to nulls.

In particular, it can avoid type issues / casting (e.g. for a float column containing non-float to represent nulls), and is quite a common argument to use in my experience.

For polars, read_csv and scan_csv could have an additional optional argument `null_values` with the following docstring (directly adapted from pandas):

> **null_values: _scalar, str, list-like, or dict, optional_**
> Additional strings to recognize as null. If dict passed, specific per-column null values. By default the following values are interpreted as null: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.

Note: not sure of what values are interpreted as null by polars at this stage

**Comment by ritchie46** [comment]
One thing to note is that `NaN` is not the same as missing. Is this most used in floating point data?

**Comment by olivier-lacroix** [comment]
@ritchie46, good point.

It could be any type really. From float, integer, strings or dates. I would say that most NaNs in pandas are, in fact, nulls. At least in my use cases.

**Comment by olivier-lacroix** [comment]
> 
> 
> One thing to note is that `NaN` is not the same as missing. Is this most used in floating point data?

Maybe best to have two arguments then ? `na_values` , and `null_values` ?

**Comment by tikkanz** [comment]
I'm working with some CSVs that use `.` to signify missing values. The data is otherwise integer. Something like `null_values` would work well for this use case.
At the moment I think the only option I have is to specify the `dtype` of the columns is `str`, remove the '.' and cast to `int`?

(Release py-polars-v8.8 on Ubuntu.)

**Comment by ritchie46** [comment]
> At the moment I think the only option I have is to specify the dtype of the columns is str, remove the '.' and cast to int?

Or you can set the `dtype` to int and set `ignore_errors=True`, then parsing errors will be missing.

**Comment by tikkanz** [comment]
Thanks, yes that works and solves my issue for now.
It might be nicer in the future to be able to declare known missings, and still have any unknown errors being picked up.

**Comment by olivier-lacroix** [comment]
Thanks @ritchie46 ! Any chance to consider a list of several null values for all / per column ? This is quite a common scenario

ie replace argument processing so that we have:

```
null_values
        Values to interpret as null values. You can provide a:
        - str -> all values encountered equal to this string will be null
        - List[str] -> all values encountered equal to these strings will be null
        - Dict[str, List[str]] -> A dictionary that maps column name to a list of null value strings.
```

**Comment by ritchie46** [comment]
Yes, this can be done. Can you make a new feature request for that?
