### ISSUE TITLE
Introduce a Cartesian Product feature in the Join merger

### ISSUE THREAD

**Issue by stordopoulos** [pola-rs/polars#849]
#### Introduce a Cartesian Product call in polars.frame.DataFrame.join

I've been testing various Panda and Panda-like APIs, and it appears that Polars doesn't have an out-of-the-box way to generate a [Cartesian Product](https://en.wikipedia.org/wiki/Cartesian_product) method. From [pandas v1.2 on, you can use how=cross](https://pandas.pydata.org/docs/reference/api/pandas.merge.html) on a merge call to: "creates the Cartesian Product from both frames, preserves the order of the left keys.".

Why:
Cartesian Products have a huge  application variety, and it's an especially important feature when you are trying to match elements between two Dataframes.

Examples of how polars would be used if your feature request were added.:
`dataframe.join(other_dataframe, on='merge_column_name', how='cross')`

**Comment by Rohith295** [comment]
Can i work on this issue?

**Comment by ritchie46** [comment]
Sure.. if we can make the implementation similar to what already exists and feature flag it.

**Comment by ritchie46** [comment]
@stordopoulos I am picking this up. I think it will be in next weeks release.

**Comment by stordopoulos** [comment]
@ritchie46, thank you for letting me know. I look forward to testing it.

**Comment by ritchie46** [comment]
fixed and released :+1:

**Comment by stordopoulos** [comment]
@ritchie46, is there a link to the documentation?

**Comment by ritchie46** [comment]
Ref guide:

https://pola-rs.github.io/polars-book/api-python/polars/eager/frame/DataFrame.html#polarseagerframedataframejoin

Syntax:

```python
out = left.join(right, how="cross")

left.lazy().join(right.lazy(), how="cross").collect()
```
