### ISSUE TITLE
`max`/`sum`/etc. always return `None` for Decimal Series

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8497]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Looks like these just haven't been implemented yet?

### Reproducible example

```python
from decimal import Decimal
import polars as pl

s = pl.Series([Decimal('10.12'), Decimal('20.35')])

result = s.sum()
assert result == Decimal('30.47')
```

### Expected behavior

Example above should work, however, result is None.

Same happens for `min`, `max`, etc.

### Installed versions

master

**Comment by scur-iolus** [comment]
Same issue as #8201 😉

**Comment by stinodego** [comment]
You're right - closing in favor of that issue.
