### ISSUE TITLE
Empty array `sum` should return `0`, `prod` should return `1`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8500]
Currently, both return `None`. This is inconsistent with some other libraries I could find:

```python
from math import prod
import numpy as np
import pandas as pd

sum([])  # 0
prod([])  # 1

np.array([]).sum()  # 0
np.array([]).prod()  # 1

pd.Series([]).sum()  # 0
pd.Series([]).prod()  # 1
```

pyarrow does return None, interestingly enough...

```python
import pyarrow as pa

pa.compute.sum([])  # <pyarrow.Int64Scalar: None>
pa.compute.product([])  # <pyarrow.Int64Scalar: None>
```

I propose we follow these defaults. This makes sense, and helps avoid handling special cases for empty frames.

**Comment by ritchie46** [comment]
We do already for sum:

```
>>> pl.Series([]).sum()
0.0
```

I agree product should return 1 after reader about this lately.

**Comment by stinodego** [comment]
And what about arrays containing only null values? Those do return `None` - shouldn't these also return 0?

```python
pl.Series([None], dtype=pl.Int32).sum()  # None
```

**Comment by ritchie46** [comment]
I am not sure. For the empty containers we can fall back on empty sets and set theory. However missing data is not the same as an empty set.

In the `sum` we ignore the missing and perhaps we should return the identity 0 as well in such a case. In case of functions with a clear identity this might be the cleanest solution.

**Comment by stinodego** [comment]
I think so - as long as a `sum` can return None, I have to handle special cases. I should be able to trust that it returns a value I would expect based on the Series dtype.

This is how I have to write my code now:

```python
a_sum = df.get_column('a').sum()
if a_sum is None:
    ...  # handle special case
elif a_sum > 0:
    ...  # do something
```

What I really want is just this:

```python
if df.get_column('a').sum() > 0:
    ...  # do something
```

**Comment by stinodego** [comment]
The case with missing values is definitely not as clear cut though, as you say. Some examples from other libs.

```python
from math import prod
import numpy as np
import pandas as pd

sum([None])  # TypeError
math.prod([None])  # TypeError

np.array([np.nan]).sum()  # nan
np.array([np.nan]).prod()  # nan

np.array([np.nan]).sum()  # nan
np.array([np.nan]).prod()  # nan

pd.Series([np.nan]).sum()  # 0.0
pd.Series([np.nan]).prod()  # 1.0
```

**Comment by avimallu** [comment]
I'm not trying to make things complex and confusing here, but `np.nan` is not a missing value in numpy - it doesn't have one AFAIK. In pandas, wouldn't it be `pd.NA` (it also used `np.nan` in earlier versions, confusingly, to show missing values)?

I've made an attempt to clarify this [here](https://github.com/pola-rs/polars/issues/8186#issuecomment-1509486412). Hope that helps what I'm trying to convey.

**Comment by avimallu** [comment]
Overall, I think what we need to identify to define the "right" way of calculating it is:

Do we calculate `pl.Series([None]).sum()` similar to `pl.Series([None, 3, 1]).sum()`, **where `null` values are removed before running `sum`.** If we do remove `null` values, then `pl.Series([None]).sum()` will become equivalent to `pl.Series([]).sum()`, removing ambiguity.

**Comment by ritchie46** [comment]
@avimallu is right, we should not take a look at `np.nan` for missing data in numpy. They treat `np.nan` the same as we do, a part of the floating point number system. This is fundamentally different than missing data.

@stinodego after thinking about this a bit, I think it is best to use the IDENTITY for all methods where there is a clear defined identity. We should do this for empty sets and for sets where all data is missing, as adding the a single value that represents the identity would also produce the idenity. E.g. `sum([None, None, 0])` would evaluate `0`.

I think this is a clear rule that we can apply on many methods and gives us some guidance on the consistency of this.
