### ISSUE TITLE
Boolean filter behaves differently on scanned pyarrow dataset and normal dataframe

### ISSUE THREAD

**Issue by pascalschwahn** [pola-rs/polars#8516]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using 'scan_pyarrow_dataset' in combination with a boolean filter behaves differently than using the filter on a normal DataFrame. It seems that the predicate pushdown to pyarrow is the problem.

### Reproducible example

```python
import polars as pl
import pyarrow.dataset as ds
import pyarrow as pa

df1 = pl.DataFrame({
    'c':[None, False, True],
    'p':[1,1,1]
})

ds.write_dataset(
    data=df1.to_arrow(),
    base_dir='example',
    format='parquet',
    partitioning=['p'],
    partitioning_flavor='hive',
    file_options=ds.ParquetFileFormat().make_write_options(compression='snappy'),
)

dataset = ds.dataset(
    source=f'example',
    partitioning='hive',
    format='parquet'
)

df2 = pl.scan_pyarrow_dataset(dataset).filter(
    pl.col('c') != True
).collect()

df1.filter(
    pl.col('c') != True
)

"""
df1:
c	p
bool	i64
null	1
false	1

df2:
c	p
bool	i32
false	1
"""
```

### Expected behavior

df1 and df2 should be equal.
Using .collect(predicate_pushdown=False) or changing the filter to (pl.col('c').is_not() | pl.col('c').is_null()) fixes the dismatch but does not seem to be intuitive.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: Linux-5.10.177-158.645.amzn2.x86_64-x86_64-with-glibc2.2.5
Python: 3.8.16 (default, Jan 24 2023, 00:12:41) 
[GCC 10.2.1 20210110]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: 0.8.1
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ritchie46** [comment]
We have documented this: https://github.com/pola-rs/polars/blob/c98334ff73457f38e7d6cc2af0b352c332f2dce0/py-polars/polars/io/pyarrow_dataset/functions.py#L26
