### ISSUE TITLE
Sorted flag not stored in DataFrame

### ISSUE THREAD

**Issue by marton78** [pola-rs/polars#8524]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When calling `set_sorted()` on a Series, the sorted flag is correctly set. On a DataFrame, it doesn't work though. See the example below:

### Reproducible example

Calling `set_sorted()` on a `Series` works:

```python
pl.DataFrame([1,2,3]).to_series().set_sorted().flags

{'SORTED_ASC': True, 'SORTED_DESC': False}
```

Calling `set_sorted()` on a `DataFrame` doesn't work:

```python
pl.DataFrame([1,2,3]).set_sorted(0).to_series().flags

{'SORTED_ASC': False, 'SORTED_DESC': False}
```

### Expected behavior

```python
pl.DataFrame([1,2,3]).set_sorted(0).to_series().flags

{'SORTED_ASC': True, 'SORTED_DESC': False}
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: Linux-5.15.82-0-virt-x86_64-with-glibc2.35
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.4.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
You must provide the column name.

**Comment by marton78** [comment]
Indeed, this works:

```python
pl.DataFrame([1,2,3], 'a').set_sorted('a').to_series().flags

{'SORTED_ASC': True, 'SORTED_DESC': False}
```

What's the reason that `set_sorted(0)` doesn't throw an error but silently ignores the `sorted` flag?
