### ISSUE TITLE
Logical comparison of pl.Series() to pl.Expr fails

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8534]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is essentially the same issue as #6971. While arithemetic operations now work, logical comparisons fail.

### Reproducible example

```python
import polars as pl

pl.Series([1]) < pl.col('a')
```
```
ValueError: Cannot convert Python type <class 'polars.expr.expr.Expr'> to Int64
```

### Expected behavior

Should return an expression identical to:

```python
pl.lit(pl.Series([1])) < pl.col('a')
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by alonme** [comment]
taking a look
