### ISSUE TITLE
Polars take a long time when apply function is used

### ISSUE THREAD

**Issue by divya-uc** [pola-rs/polars#8539]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I did the following operation in polars but it took me 5 hours to complete the task

```
df = df.with_column(pl.struct(['col_1','col_2']) \
       .apply(lambda x: func(x['col_1'], x['col_2'])).alias('col_3'))
```

is there any faster alternative to apply using polars?

### Reproducible example

```python
import polars as pl

df = df.with_column(pl.struct(['col_1','col_2']) \
       .apply(lambda x: func(x['col_1'], x['col_2'])).alias('col_3'))
```

### Expected behavior

It should run the code in atleast 10 minutes

### Installed versions

<details>

```
polars 0.17.9
```

</details>

**Comment by ritchie46** [comment]
> It should run the code in atleast 10 minutes

How do you know that?

Can you give some more information? Using `apply` is the worst thing you can do. It is super expensive as you are running python only and we need to materialize to python.

**Comment by divya-uc** [comment]
I was using the discounted levenstein algorithm to find the name similarity between two names 

```import abydos.distance as abd
   
  df = df.with_columns([pl.struct(["Name1", "Name2"]).apply(
            lambda t: abd.DiscountedLevenshtein().sim(t["Name1"], t["Name2"])).alias("match")])```

**Comment by ritchie46** [comment]
You can precompile your own UDF with [pyo3-polars](https://github.com/pola-rs/pyo3-polars). There is also a crate for levensteihn distance: https://docs.rs/distance/latest/distance/fn.levenshtein.html

**Comment by divya-uc** [comment]
My data frame had only 11 million rows.

**Comment by ritchie46** [comment]
And if you make a list of strings and loop that function. How long does it take then?

**Comment by alexander-beedie** [comment]
As Ritchie says, all you're really doing here is executing python, rather than polars - you're also initialising the `DiscountedLevenshtein` class _every time_ that you access new values inside your lambda; this is very suboptimal, and may be quite expensive.

You haven't really given us enough to reproduce (no data, function details, etc) but based on your import abbreviation and the class name I'm guessing you're using the `abydos.distance` package?

_If_ your data has a lot of repeated string pairs you might get a large speedup from an LRU cache, which you could add like so:

```python
from functools import lru_cache
import abydos.distance as abd

# initialise the class *outside* of your applied function
sim = abd.DiscountedLevenshtein().sim

# this cache will only help if you have repeated string pairs.
# adjust the size up or down depending how frequently your values repeat.
@lru_cache( 8192 )
def caching_similarity( name1, name2 ):
    return sim( name1, name2 )

# (load your real data here)
df = pl.DataFrame( {"Name1":["xyz","abc"], "Name2":["xxx","axc"]} )

# apply caching function 
df.with_columns(
    match = pl.struct( ["Name1", "Name2"] ).apply( 
        lambda t: caching_similarity( t["Name1"], t["Name2"] )
    )
)
```

**Comment by divya-uc** [comment]
My code is exactly same as what @alexander-beedie has mentioned. I was using the abydos package. I have tried initalising the function outside and caching it . still it takes the exact same amount of time. I just want an optimal solution so that the code runs faster.

**Comment by divya-uc** [comment]
I was able to reduce the time by using multiprocessing.
https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html#combining-polars-with-pythons-multiprocessing

**Comment by hkpeaks** [comment]
I enjoy testing Polars by using billion rows dataset for publishing benchmark reports. It always runs very fast except in some cases where it triggers termination. In such cases, I report it immediately. @qqlearn123

**Comment by alexander-beedie** [comment]
@divya-uc: I think we are still puzzled why you said the _expected_ behaviour is 10 minutes; at the moment it just sounds like you are calling a slow python function, which doesn't really seem to be anything to do with polars... Can you clarify _why_ you think your operation should take 10 minutes, and if you think polars is somehow slowing it down?

**Comment by divya-uc** [comment]
@alexander-beedie I apologize for mentioning the expected run time as 10 minutes. I did because it was just 10 million records I was dealing with. Yes, the python function i was calling is slow and have nothing to do with polars.

**Comment by alexander-beedie** [comment]
Ok; I'll re-tag this as a question rather than a bug then. It seems like you're just looking for a way to speed-up your python function; maybe StackOverflow would be a good place to repost this question (and you can use the [python-polars](https://stackoverflow.com/questions/tagged/python-polars) tag to target it)👍

**Comment by qqlearn123** [comment]
That's exactly what I was keeping asking about the expected behavior. If using pandas takes 10 mins, then polars are really doomed...

**Comment by ritchie46** [comment]
> That's exactly what I was keeping asking about the expected behavior. If using pandas takes 10 mins, then polars are really doomed...

But that doesn't seem to be the case. 

I think we should spending our time on this. OP is doing essentially a python for loop over millions of python strings. This has nothing to do with polars. 

OP can ask a question on stackoverflow how to deal with this problem better. This would encouraged him to clarify what he did, explain his expectations and make a reproducable example.

I will close this so we can focus on one few other remaining issues.

**Comment by hkpeaks** [comment]
This lesson helped me understand the benefits of using gRPC instead of direct bindings with Python when binding high performance programming languages with slow performance programming languages.

**Comment by hkpeaks** [comment]
The version 0.17.11 of Polars is impressive! It can run 4 concurrent jobs using GroupBy billion rows scenario and complete the task in less than 10 minutes. My testing script with 14 columns and a data file size of 67.2GB was completed in less than 10 minutes using 32GB Memory and 8-Core. This is a strong evidence the Polars team committe continuing improvement of the software.

Script
import polars as pl
import time
import pathlib
s = time.time()

q = (
   pl.scan_csv("Input/1000MillionRows.csv")    
   .groupby(by=["Ledger", "Account", "PartNo", "Contact","Project","Unit Code", "D/C","Currency"])
  .agg([  
    pl.count('Quantity').alias('Quantity(Count)'),
    pl.max('Quantity').alias('Quantity(Max)'),
    pl.min('Quantity').alias('Quantity(Min)'),
    pl.sum('Quantity').alias('Quantity(Sum)'),     
    pl.sum('Base Amount').alias('Base Amount(Sum)'),     
  ]))

a = q.collect(streaming=True)
path: pathlib.Path = "Output/Polars-GroupBy.csv"
a.write_csv(path)

e = time.time()
print("Polars GroupBy 1000 Million Rows Time = {}".format(e-s))

Demo video in 10X fast forward: https://youtu.be/odDOlU9KNqY

Without fast forward: https://youtu.be/Ze0jNmtUn0Y
