### ISSUE TITLE
Multi index and date time index support

### ISSUE THREAD

**Issue by feribg** [pola-rs/polars#854]
I was wondering if multi indexing and date time indexing support is on the near term roadmap. Unfortunately none of the "fast" data frames out there have any support for those and most people dealing with irregular sensor data or stock market data are still stuck with pandas. Probably area of decent opportunity.

**Comment by ritchie46** [comment]
Could you describe to me what kind of problems you wnat to solve and how a date index helps you with that? 

Polars does not have indexes, but pherhaps we can expose an intermediate data structure to suit your needs.

**Comment by feribg** [comment]
There are a few that come to mind:

### Reindexing with date based indexes to account for business days and resampling (daily, business day, custom calendar).
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

### Hierarchical indexes having time as the second dimension

For example imagine the following common structure:
sensor_id, timestamp -> value

If those are sampled irregularly I would like to a) resample them to a common step based on the level 2 index within each sensor_id bucket and b) back/forward fill within each

### Merge as of (in both directions forward and back to find the closes match)
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html

So i think resampling based on a calendar, merging and reindexing to a common time step take care of 99% of the use cases I haven't seen anything but Pandas support and they are all pretty common when dealing with time series.

**Comment by YuRiTan** [comment]
Hi @feribg,You dont need reindexing / hierarchical indexing to do the things you want. I've tried to create a MWE based on your description:

```python
import polars as pl
import numpy as np
import pandas as pd
import pyarrow as pa

np.random.seed(42)

# Maybe a date_range like function in Polars could also be nice. Now using pandas for this
date_times = pd.date_range('2021-06-24 00:00:00', '2021-06-24 2:30:00', freq='30min', closed='left')
dts = pl.from_pandas(date_times).apply(lambda x: x + np.random.randint(1_000*60, 60_000*60)).cast(pl.Date64)

# some df with sensor id, (randomish) datetime and some value
df = pl.DataFrame(
    {
        'sensor': ['a', 'b', 'a', 'b', 'b'],
        'datetime': dts,
        'value': [2, 3, 1, 2, 3]
    }
)
print("Original DataFrame -", df)

# The downsample (resample) is already there:
print(
    "Downsample, take first per sensor per hour -",
    df.groupby('sensor').apply(lambda df: df.downsample(by='datetime', rule='hour', n=1).first())
)

# let's say you want to reindex to whole hours, you can:    
hour_ms = 3_600_000
df['datetime'] = df['datetime'].apply(lambda x: x // hour_ms * hour_ms).cast(pl.Date64)

# the "index" you want to "reindex" with, since we want both senors for all hourly intervals
all_hours = pl.DataFrame({'datetime': pa.array(date_times.tolist()*2), 'sensor':['a']*len(date_times) + ['b']*len(date_times)})

df_per_hour = all_hours.join(df, on=['sensor', 'datetime'], how='left')
print("Both sensors have all (30 min) intervals -", df_per_hour)

# Make sure
df_per_hour = (
    df_per_hour.sort(['datetime', 'sensor'])[[
        pl.col('datetime'),
        pl.col('sensor'),
        pl.col("value").backward_fill().over(pl.col("sensor")).take(pl.col("sensor").arg_unique()).explode()
    ]]
)
print("Both sensors have all (30 min) intervals, backfilled -", df_per_hour)
```
You can also create a function to resample using a custom calendar. I agree that some util functions can be nice, but the concept of indexes might not be necessary in this case.

The `merge_asof` could indeed be a nice feature to add. 

Hope this helps!

**Comment by ritchie46** [comment]
@feribg the `asof` join is just merged in. As @YuRiTan mentioned, a resample is already possible with a `downsample` operation. And I believe that what is obtained with indexes can also be obtained with joins, groupby combinations.

**Comment by feribg** [comment]
Thanks @ritchie46 that's amazing turnaroud. I will port some of my code over and try it out. Just out of curiosity I see the PR adds support for python DT but i dont see anywhere in the tests a timezone variant, are tz's supported just not added in the PR or they are WIP.

**Comment by ritchie46** [comment]
> Just out of curiosity I see the PR adds support for python DT but i dont see anywhere in the tests a timezone variant, are tz's supported just not added in the PR or they are WIP.

No timezones are not yet supported. I always considered these a 'nice to have'. Eventually I maybe want to change the `Date64` datatype to a type that may include a timezone.

**Comment by austospumanto** [comment]
> Hi @feribg,You dont need reindexing / hierarchical indexing to do the things you want. I've tried to create a MWE based on your description:
> 
> ```python
> import polars as pl
> import numpy as np
> import pandas as pd
> import pyarrow as pa
> 
> np.random.seed(42)
> 
> # Maybe a date_range like function in Polars could also be nice. Now using pandas for this
> date_times = pd.date_range('2021-06-24 00:00:00', '2021-06-24 2:30:00', freq='30min', closed='left')
> # you can convert the pandas to polars using the `pl.from_pandas()` function. Also trying to create random datetimes here.
> dts = pl.from_pandas(date_times).apply(lambda x: x + np.random.randint(1_000*60, 60_000*60)).cast(pl.Date64)
> 
> # some df with sensor id, (randomish) datetime and some value
> df = pl.DataFrame(
>     {
>         'sensor': ['a', 'b', 'a', 'b', 'b'],
>         'datetime': dts,
>         'value': [2, 3, 1, 2, 3]
>     }
> )
> print("Original DataFrame -", df)
> 
> # The downsample (resample) is already there:
> print(
>     "Downsample, take first per sensor per hour -",
>     df.groupby('sensor').apply(lambda df: df.downsample(by='datetime', rule='hour', n=1).first())
> )
> 
> # let's say you want to reindex to whole hours, you can:    
> hour_ms = 3_600_000
> df['datetime'] = df['datetime'].apply(lambda x: x // hour_ms * hour_ms).cast(pl.Date64)
> 
> # the "index" you want to "reindex" with, since we want both senors for all 30 min intervals
> index = pl.DataFrame({'datetime': pa.array(date_times.tolist()*2), 'sensor':['a']*len(date_times) + ['b']*len(date_times)})
> 
> df_per_hour = index.join(df, on=['sensor', 'datetime'], how='left')
> print("Both sensors have all (30 min) intervals -", df_per_hour)
> 
> # Make sure the values are backfilled
> df_per_hour = (
>     df_per_hour.sort(['datetime', 'sensor'])[[
>         pl.col('datetime'),
>         pl.col('sensor'),
>         pl.col("value").backward_fill().over(pl.col("sensor")).explode()
>     ]]
> )
> print("Both sensors have all (30 min) intervals, backfilled -", df_per_hour)
> ```
> 
> ```
> Original DataFrame - shape: (5, 3)
> ╭────────┬─────────────────────────┬───────╮
> │ sensor ┆ datetime                ┆ value │
> │ ---    ┆ ---                     ┆ ---   │
> │ str    ┆ date64(ms)              ┆ i64   │
> ╞════════╪═════════════════════════╪═══════╡
> │ "a"    ┆ 2021-06-24 00:37:59.110 ┆ 2     │
> ├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ "b"    ┆ 2021-06-24 01:17:08.307 ┆ 3     │
> ├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ "a"    ┆ 2021-06-24 01:38:09.084 ┆ 1     │
> ├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ "b"    ┆ 2021-06-24 02:29:31.566 ┆ 2     │
> ├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ "b"    ┆ 2021-06-24 02:40:16.330 ┆ 3     │
> ╰────────┴─────────────────────────┴───────╯
> Downsample, take first per sensor per hour - shape: (4, 3)
> ╭─────────────────────┬──────────────┬─────────────╮
> │ datetime            ┆ sensor_first ┆ value_first │
> │ ---                 ┆ ---          ┆ ---         │
> │ date64(ms)          ┆ str          ┆ i64         │
> ╞═════════════════════╪══════════════╪═════════════╡
> │ 2021-06-24 00:00:00 ┆ "a"          ┆ 2           │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "a"          ┆ 1           │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "b"          ┆ 3           │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ 2021-06-24 02:00:00 ┆ "b"          ┆ 2           │
> ╰─────────────────────┴──────────────┴─────────────╯
> Both sensors have all (30 min) intervals - shape: (11, 3)
> ╭─────────────────────┬────────┬───────╮
> │ datetime            ┆ sensor ┆ value │
> │ ---                 ┆ ---    ┆ ---   │
> │ date64(ms)          ┆ str    ┆ i64   │
> ╞═════════════════════╪════════╪═══════╡
> │ 2021-06-24 00:00:00 ┆ "a"    ┆ 2     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 00:30:00 ┆ "a"    ┆ null  │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "a"    ┆ 1     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:30:00 ┆ "a"    ┆ null  │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ ...                 ┆ ...    ┆ ...   │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 00:30:00 ┆ "b"    ┆ null  │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "b"    ┆ 3     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:30:00 ┆ "b"    ┆ null  │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 02:00:00 ┆ "b"    ┆ 2     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 02:00:00 ┆ "b"    ┆ 3     │
> ╰─────────────────────┴────────┴───────╯
> Both sensors have all (30 min) intervals, backfilled - shape: (11, 3)
> ╭─────────────────────┬────────┬───────╮
> │ datetime            ┆ sensor ┆ value │
> │ ---                 ┆ ---    ┆ ---   │
> │ date64(ms)          ┆ str    ┆ i64   │
> ╞═════════════════════╪════════╪═══════╡
> │ 2021-06-24 00:00:00 ┆ "a"    ┆ 2     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 00:30:00 ┆ "a"    ┆ 1     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "a"    ┆ 1     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:30:00 ┆ "a"    ┆ null  │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ ...                 ┆ ...    ┆ ...   │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 00:30:00 ┆ "b"    ┆ 3     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:00:00 ┆ "b"    ┆ 3     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 01:30:00 ┆ "b"    ┆ 2     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 02:00:00 ┆ "b"    ┆ 2     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
> │ 2021-06-24 02:00:00 ┆ "b"    ┆ 3     │
> ╰─────────────────────┴────────┴───────╯
> ```
> 
> You can also create a function to resample using a custom calendar. I agree that some util functions can be nice, but the concept of indexes might not be necessary in this case.
> 
> The `merge_asof` could indeed be a nice feature to add.
> 
> Hope this helps!

After attempting to do something similar, I only got it to work by flipping the "datetime" and "sensor" columns in the sort prior to the select. In other words:

```
# Make sure the values are backfilled
df_per_hour = (
    df_per_hour.sort(['sensor', 'datetime'])[[
        pl.col('datetime'),
        pl.col('sensor'),
        pl.col("value").backward_fill().over(pl.col("sensor")).explode()
    ]]
)
print("Both sensors have all (30 min) intervals, backfilled -", df_per_hour)
```

Swapping the sort priority of the two columns definitely changes the results I get, so it does seem to matter. Try the following w/ the sort columns swapped to see what I'm talking about:

```
import pandas as pd
import polars as pl

T = pd.Timestamp
PF = pl.DataFrame

(
    PF(
        {
            "val": [None, None, "true", None, None, "false", None],
            "id": [1, 1, 1, 2, 1, 2, 2],
            "ord": [
                T(v).to_pydatetime()
                for v in (
                    "2021-01-23",
                    "2021-01-21",
                    "2021-01-22",
                    "2021-01-21",
                    "2021-01-20",
                    "2021-01-22",
                    "2021-01-23",
                )
            ],
        }
    )
    .pipe(
        lambda cf: (
            cf.join(
                cf
                .sort(["id", "ord"]).select(
                    [
                        pl.col("id"),
                        pl.col("ord"),
                        pl.col("val")
                        .backward_fill()
                        .over(pl.col("id"))
                        .explode()
                        .alias("val_bfill"),
                    ]
                ),
                on=["id", "ord"],
                how="left",
            )
        )
    )
)
```
