### ISSUE TITLE
Incorrect `write_ndjson` behaviour

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#8542]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The behaviour of `write_json` and `write_ndjson` diverge when using a subset of rows of a dataframe.

### Reproducible example

```python
import polars as pl
from io import BytesIO

data = {"col1": [0, 2], "col2": [[3, 4, 5], [6, 7, 8]]}
df = pl.DataFrame(data)

byte_buffer = BytesIO()
subset_df = df[1, :]
print(subset_df)

subset_df.write_ndjson(byte_buffer)
print(byte_buffer.getvalue())

# shape: (1, 2)
# ┌──────┬───────────┐
# │ col1 ┆ col2      │
# │ ---  ┆ ---       │
# │ i64  ┆ list[i64] │
# ╞══════╪═══════════╡
# │ 2    ┆ [6, 7, 8] │
# └──────┴───────────┘
# b'{"col1":2,"col2":[3,4,5]}\n'
```

### Expected behavior
```python
import polars as pl
from io import BytesIO

data = {"col1": [0, 2], "col2": [[3, 4, 5], [6, 7, 8]]}
df = pl.DataFrame(data)

byte_buffer = BytesIO()
subset_df = df[1, :]

subset_df.write_json(byte_buffer)
print(byte_buffer.getvalue())
# b'{"columns":[{"name":"col1","datatype":"Int64","values":[2]},{"name":"col2","datatype":"List","values":[{"name":"","datatype":"Int64","values":[6,7,8]}]}]}'
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2022.7.1
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>```

</details>

> 

>

**Comment by ritchie46** [comment]
What do you mean? Seems correct to me?

**Comment by CHDev93** [comment]
Why in the first case is writing out `b'{"col1":2,"col2":[3,4,5]}\n'`. This row has been filtered from the dataframe

**Comment by CHDev93** [comment]
Thanks! Tried to look myself but quickly dropped into the Rust layer and I got lost (long standing TODO item for me, learn Rust). Anyway, since the `write_json` has the correct behaviour, I'd imagine there's just some small discrepancy between it and `write_ndjson`.

**Comment by universalmind303** [comment]
@ritchie46 I can take a look at this one as well.

**Comment by ritchie46** [comment]
@universalmind303 Sure, let me know if you need any help. This likely is an offset not taken into account.

**Comment by ritchie46** [comment]
Thanks for the breakdown. Will take a look
