### ISSUE TITLE
Function to create a new column which is a binned version of another column

### ISSUE THREAD

**Issue by paulf81** [pola-rs/polars#8551]
### Problem description

Sorry if I've simply missed this functionality, but an enhancement I would really value is a function which returns a column, which is a binned version of another column.  I'm aware of the series.cut method, and perhaps I'm missing how to apply it here, but in my mind this function would:

- Accept one column, or series, as well as the bin edges and labels
- -If the labels are unspecified perhaps they could default to the left or right edge, or center point
- Return a column which is of the same type of the original column

**Comment by mcrumiller** [comment]
Yeah, there's no `.cut()` on expressions. For now, you can do something like this:

```python
import polars as pl
from polars import col, when

def cut(col_name, edges, labels):
    """
    Assume edges are left-inclusive, right-exclusive, i.e. each bin = [x_min, x_max), except for first and last bin,
    which include everything to the left or everything to the right.

    Inputs:
      * edges - list of edges. With N bins, we have N-1 edges and N labels. You can adjust this to deal with exclusions.
    """
    c = col(col_name)
    labels = [pl.lit(x, pl.Categorical) for x in labels]
    expr = when(c < edges[0]).then(labels[0])
    for edge, label in zip(edges[1:], labels[1:-1]):
        expr = expr.when(c < edge).then(label)
    expr = expr.otherwise(labels[-1])

    return expr


df = pl.DataFrame({
    'a': range(10)
})

pl.Config.set_tbl_rows(99)
print(
    df.select(
        'a',
        cut(
            col_name='a',
            edges = [4, 6, 8],
            labels = ["< 4", "4-5.99", "6-7.99", ">= 8"]
        ).alias("binned")
    )
)
```
```
shape: (10, 2)
┌─────┬────────┐
│ a   ┆ binned │
│ --- ┆ ---    │
│ i64 ┆ cat    │
╞═════╪════════╡
│ 0   ┆ < 4    │
│ 1   ┆ < 4    │
│ 2   ┆ < 4    │
│ 3   ┆ < 4    │
│ 4   ┆ 4-5.99 │
│ 5   ┆ 4-5.99 │
│ 6   ┆ 6-7.99 │
│ 7   ┆ 6-7.99 │
│ 8   ┆ >= 8   │
│ 9   ┆ >= 8   │
└─────┴────────┘
```

**Comment by paulf81** [comment]
@mcrumiller this was very helpful and is what I was looking for.  Thank you!

**Comment by Guillermogsjc** [comment]
+1000, please `Expr.cut` even `Expr.qcut` (quantile cut variant), would be very handy

**Comment by lucazanna** [comment]
I also used it today and ended up using hstack as I wanted to have access both to the bin and to the threshold. Having it as an expression would make for a better API syntax

The PR https://github.com/pola-rs/polars/pull/7724 mentions the possibility to add it for expressions, but I'm not sure if it's easy add or not. And the Polars team has their plate full for sure

**Comment by magarick** [comment]
This can be closed.
