### ISSUE TITLE
`.to_dummies()` should return `Boolean` type rather than `UInt8`

### ISSUE THREAD

**Issue by wany-oh** [pola-rs/polars#8555]
### Problem description

It makes more sense for the function to return True/False.

**Comment by ritchie46** [comment]
As `to_dummies` will almost always be used in a machine learning algorithm which cannot deal with bitpacked data, this would lead to a redundant copy. Whereas `uint8` matches the binary representation of all numerical libraries.

**Comment by deanm0000** [comment]
@wany-oh You can convert the 0/1 uint8 to bool with

```
df.to_dummies('somevar').select(pl.col(pl.UInt8())==1)
```

this, of course, assumes you don't have other UInt8 columns.

Alternatively you could use regex

```
df.to_dummies('somevar').with_columns(pl.col("^somevar.*$")==1)
```
