### ISSUE TITLE
How to do conditional assign on ChunkedArray

### ISSUE THREAD

**Issue by qqlearn123** [pola-rs/polars#8556]
On the rust side, do we have some convenient methods or syntactic sugar for doing something like the following as in `numpy`:

```
ca[p] = ca2;
```

Assuming `p` is a boolean ChunkedArray with the same length as `ca` and the length of `ca2` is the same with the number of `true` in `p`.

**Comment by ritchie46** [comment]
It is adviced to use the expression API. `when -> then -> otherwise`. The chunkedarrays are lower level and immutable.
