### ISSUE TITLE
Don't always print "unstable pivot not yet supported, using stable pivot"

### ISSUE THREAD

**Issue by glennpierce** [pola-rs/polars#8559]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When calling pivot in 
polars/polars-ops/src/frame/pivot/mod.rs

the text "unstable pivot not yet supported, using stable pivot"

is always printed with println! an so pollutes the journald log.

Can this message be printed when compiled as a debug build ?

### Reproducible example

Just call the pivot function

ie

df = polars_ops::pivot::pivot(&df, ["value"], ["ts"], ["sensor_id"], false, Some(polars_ops::pivot::PivotAgg::Mean), None).unwrap();

### Expected behavior

Doesn't print message about implementation I have no control over.

### Installed versions

<details>
full
</details>

**Comment by ritchie46** [comment]
Don't select `stable = true` then. :)

**Comment by glennpierce** [comment]
Ah polars_ops::pivot::pivot_stable Thanks :)
