### ISSUE TITLE
Streaming engine creating a large amount of files

### ISSUE THREAD

**Issue by djfrancesco** [pola-rs/polars#8568]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Well maybe I am missing something with the Python API but I am trying to load a table from a Parquet file, sort it and write the result into another Parquet file, with Polars' **streaming engine**.  

The table corresponds to the `lineitem` table from the TPC-H benchmark, with scale factor 10. The Parquet file has been generated using DuckDB. The Polars commands are the following ones:

```Python
pl.scan_parquet(input_file_path).sort("l_shipdate").sink_parquet(output_file_path)
```
where `input_file_path` is the input Parquet file (`lineitem.parquet`) and `output_file_path` the sorted output Parquet file.

The Python scripts runs for a long time, without success. Also it writes a large amount of files into the `.polars/sort/1682684914868106473` folder in my home directory. This last part of the folder path `1682684914868106473` changes at each run. These files have an `.ipc` extension.

```bash
~/.polars/sort/1682684914868106473  ls -r | head -n 10
9.ipc
_9.ipc
99.ipc
_99.ipc
999.ipc
_999.ipc
_9999.ipc
_9998.ipc
_9997.ipc
_9996.ipc
```

Also, note that it works fine with scale factor 1. And, it works fine without the streaming engine (scale factor 1 and 10):
```python
pl.read_parquet(input_file_path).sort("l_shipdate").write_parquet(output_file_path)
```
I tried to change the config: `pl.Config.activate_decimals()`, did not change the strange behaviour on my laptop.
The files  are created until there is no more free inodes (74000000 files)... Then the disk appears to be full.

My OS is Linux mint 21.1, based on Ubuntu 22.04 .

### Reproducible example

```python
import os

import duckdb
import polars as pl

input_parquet_file_path = "lineitem.parquet"
output_parquet_file_path = "lineitem_sorted.parquet"

if not os.path.exists(input_parquet_file_path):
	with duckdb.connect() as conn:
	    conn.sql("INSTALL tpch")
	    conn.sql("LOAD tpch")
	    conn.sql("CALL dbgen(sf=10)")
	    query = f"COPY (SELECT * FROM lineitem) TO '{input_parquet_file_path}' (FORMAT PARQUET)"
	    conn.sql(query)
if os.path.exists(output_parquet_file_path):
    os.remove(output_parquet_file_path)
pl.scan_parquet(input_parquet_file_path).sort("l_shipdate").sink_parquet(output_parquet_file_path)
```

### Expected behavior

Well the code runs a very long time and stops with a *no more space on device* message

### Installed versions

<details>

```
---Version info---
Polars: 0.17.6
Index type: UInt32
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.35
Python: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.3
pandas: 2.0.1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.4.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by djfrancesco** [comment]
I have 32 GB of RAM

**Comment by ritchie46** [comment]
Hmm.. I think this may be related to the chunk size being too low. Could you read such a file with polars' ipc reader and see how much rows is in there?

**Comment by ritchie46** [comment]
Thanks for the report, I think something goes wrong, it should not produce that many files. I will look into it.

**Comment by djfrancesco** [comment]
OK thanks, I can reproduce the behaviour on my laptop, if ever you need more information
