### ISSUE TITLE
Wrong .groupby().sum() results for certain dtypes

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#8570]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Sorry I don't know how to make a simpler reproducible example.
The example below seems to fail for sufficiently large values of `m,n` and succeed otherwise.

(With large `m,n`, I've also seen an issue where I sum different columns `z1, z2, ...` in the `agg`, but get the same incorrect answer for all of them).

### Reproducible example

```python
import numpy as np
import polars as pl

rng = np.random.default_rng(seed=0)
m = 1000
n = 1000

dfa = pl.DataFrame({"x": pl.arange(start=0, end=n, eager=True)})
dfb = pl.DataFrame(
    {
        "y": rng.integers(low=0, high=10, size=m),
        "z": rng.integers(low=0, high=2, size=m),
    }
)
dfc = dfa.join(dfb, how="cross")

for dtype in [pl.Boolean, *pl.INTEGER_DTYPES]:
    dfd = dfc.with_columns(pl.col("z").cast(dtype)).groupby("x", "y").sum()
    if dfd["z"].sum() != dfc["z"].sum():
        print("Falied for", dtype)
```

```
Falied for Boolean
Falied for Int16
Falied for UInt8
Falied for Int8
Falied for UInt16
```

### Expected behavior

It works e.g. for `Int64`, so I sort of hope it will work in general.
Sorry if I'm missing something obvious, I haven't gotten much sleep lately.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.1
pandas: 2.0.0
pyarrow: 10.0.1
connectorx: 0.3.1
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: 0.8
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
On it, found it.
