### ISSUE TITLE
Can't Create DataFrame from NamedTuples that Contain Dictionary Values

### ISSUE THREAD

**Issue by ngriffiths13** [pola-rs/polars#8576]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Just upgraded to `polars==0.17.9` and started hitting an error that wasn't throwing before when creating a DataFrame out of NamedTuple objects. If I run the same code without the NamedTuple and just use either a regular tuple or dataclass this works. When using NamedTuple  it raises `TypeError: unhashable type: 'dict'`

### Reproducible example

```python
import polars as pl
from typing import NamedTuple
from datetime import datetime

class Test(NamedTuple):
    dt: datetime
    info: dict[str, int]

data = [Test(datetime(2017, 1, 1), {"a": 1, "b": 2}), Test(datetime(2017, 1, 2), {"a": 2, "b": 2})]
pl.DataFrame(data)
```

### Expected behavior

I expect no error to be thrown, and for a DataFrame to be created that has a column named `dt` with a datetime type and a column named `info` with a struct type.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.10.8 (main, Dec 28 2022, 10:21:17) [Clang 13.0.0 (clang-1300.0.29.3)]
---Optional dependencies---
numpy: 1.24.3
pandas: 1.5.3
pyarrow: 8.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2022.11.0
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Fix incoming...

**Comment by alexander-beedie** [comment]
Thanks for the issue/test-case 👍
