### ISSUE TITLE
pl.struct().n_unique().over() has very low memory limit

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8603]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When a dataframe has many unique items, calling `pl.struct().n_unique().over()` issues a memory error even with very few rows. In the example below, I build a dataframe with three columns and 1M rows, and on my 48GB machine I hit a memory limit with an odd message.

### Reproducible example

```python
from datetime import date

import numpy as np
import polars as pl

rng = np.random.default_rng(0)

N_rows = 1_000_000
rints = rng.integers(low=-1_000_000, high=1_000_000, size=N_rows)
df = pl.DataFrame({
    "ID": pl.arange(0, N_rows, eager=True).cast(str).str.zfill(10),
    "Birth_Date": date(2000, 1, 1),
    "Gender": rints < 0
}).with_columns(
    pl.col("Birth_Date") + pl.duration(days=pl.lit(rints)),
    pl.when(pl.col("Gender")).then('M').otherwise('F').alias("Gender"),
)

print(df)

# the following fails when N_rows ~ 1_000_000
df.select(pl.struct(["Gender", "Birth_Date"]).n_unique().over("ID"))
```
```
shape: (1_000_000, 3)
┌────────────┬────────────┬────────┐
│ ID         ┆ Birth_Date ┆ Gender │
│ ---        ┆ ---        ┆ ---    │
│ str        ┆ date       ┆ str    │
╞════════════╪════════════╪════════╡
│ 0000000000 ┆ 2166-04-16 ┆ F      │
│ 0000000001 ┆ 2165-06-03 ┆ F      │
│ 0000000002 ┆ 2060-12-23 ┆ F      │
│ 0000000003 ┆ 1908-07-03 ┆ M      │
│ …          ┆ …          ┆ …      │
│ 0000999996 ┆ 2207-08-23 ┆ F      │
│ 0000999997 ┆ 1863-01-08 ┆ F      │
│ 0000999998 ┆ 1792-12-08 ┆ M      │
│ 0000999999 ┆ 1993-01-09 ┆ F      │
└────────────┴────────────┴────────┘
memory allocation of 12288 bytes failed
```

Sometimes the error looks like this:

```
memory allocation of memory allocation of 1228812288 bytes failed
 bytes failed
```
which looks like two threads printing `memory allocation of 12288 bytes failed`.

### Expected behavior

This should not cause a memory issue.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.10
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.3
pandas: 2.0.1
pyarrow: 11.0.0
connectorx: 0.3.2a3
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.1.0
```

</details>

**Comment by ritchie46** [comment]
Yeap, we overflow somewhere. Looking into it.

**Comment by ritchie46** [comment]
`pl.duration(days=pl.lit(rints))` overflows. We cannot hold 1 million days as a duration as we have a nanoseconds unit encode it as an `i64`.

Does this still happen with a duration range within our bounds?

**Comment by mcrumiller** [comment]
Hi @ritchie46 yes it definitely does--I ran into this issue at work with real birth dates in the wild, I just used the `pl.Duration` adding step to generate fake data. Since our `ID` column is all unique anyway, we can remove the `pl.duration` step entirely and just give everyone the same birth day, and we still get the error:

```
shape: (1_000_000, 3)
┌────────────┬────────────┬─────────┐
│ ID         ┆ Birth_Date ┆ Num     │
│ ---        ┆ ---        ┆ ---     │
│ str        ┆ date       ┆ str     │
╞════════════╪════════════╪═════════╡
│ 0000000000 ┆ 2000-01-01 ┆ 701248  │
│ 0000000001 ┆ 2000-01-01 ┆ 273923  │
│ 0000000002 ┆ 2000-01-01 ┆ 22272   │
│ 0000000003 ┆ 2000-01-01 ┆ -460427 │
│ …          ┆ …          ┆ …       │
│ 0000999996 ┆ 2000-01-01 ┆ 502847  │
│ 0000999997 ┆ 2000-01-01 ┆ 590480  │
│ 0000999998 ┆ 2000-01-01 ┆ -502636 │
│ 0000999999 ┆ 2000-01-01 ┆ 210956  │
└────────────┴────────────┴─────────┘
memory allocation of memory allocation of 1228812288 bytes failed
 bytes failed
```

I see you added a PR that may fix the issue, let me boot up my personal PC and see if it fixed it.

**Comment by mcrumiller** [comment]
Works with 10M rows now in just a few seconds. Cheers, thanks @ritchie46.

**Comment by ritchie46** [comment]
Nice!
