### ISSUE TITLE
In the README, is the timezone support condition and "and" or an "or" issue?

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#8605]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In the optional dependencies section, it mentions that timezone is required if you are "on Python<3.9 and/or you are on Windows". Is this an "and" or an "or". It can't be both. 

```
Timezone support, only needed if 1. you are on Python < 3.9 and/or 2. you are on Windows, otherwise no dependencies will be installed
```

### Reproducible example

```python
Read README. Be confused.
```

### Expected behavior

Understand README.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by MarcoGorelli** [comment]
technically it's "or", but in common parlance "and/or" means "either or both"

**Comment by alexander-beedie** [comment]
* Definition/explanation: [and/or](https://en.wikipedia.org/wiki/And/or) :)

**Comment by mcrumiller** [comment]
Regardless, the `1.` and `2.` could be removed to improve the sentence, but it's probably not worth a whole PR just for that.

**Comment by stinodego** [comment]
The grammar is correct, as was pointed out. If you feel the wording needs to be improved, feel free to open a PR.

**Comment by zundertj** [comment]
I think I added that, tried the "either or both" but doesn't make it much nicer to be honest.

Also important to realize, but too much detail for the README, that if neither condition applies, installing Polars with `pip install polars[timezone]` will actually be the same as `pip install polars`, i.e. the filtering automatically happens as we have set this up in `pyproject.toml`.

**Comment by DeflateAwning** [comment]
"either"/"or" includes the situation where it's both though. "either" and "or" or inclusive in English.

**Comment by zundertj** [comment]
@DeflateAwning : As stinodego said, a PR is welcome if you think it can be worded in a better way. I tried the "either or both" suggested above, and wasn't convinced that is a better wording.

**Comment by DeflateAwning** [comment]
Great point. Done!

**Comment by alexander-beedie** [comment]
Merged - thanks ;)

(But if you think "and/or" is bad, I strongly advise not thinking too hard about English [spelling](https://www.bbc.com/culture/article/20150605-your-language-is-sinful)...🤣)
