### ISSUE TITLE
Python: add trigonometry functions

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#861]
sin, cos, etc.

In rust this is not needed as we can easily call `apply(_cast)`

**Comment by ritchie46** [comment]
@romanovacca This might be a good one to pick up.

**Comment by alpeshjamgade** [comment]
hi, can i do this?

**Comment by ritchie46** [comment]
Yes, if you want any help let me know. :)

**Comment by gmcrocetti** [comment]
> Yes, if you want any help let me know. :)

Hi @ritchie46 , would you be willing to give more context to a rookie ?

**Comment by ritchie46** [comment]
@gmcrocetti. Polars `Series` and `Expr` both support numpy ufunc. So this can be completely dispatched to numpy. You will need to add those methods to the `Series` and `Expr` class, and run some tests to see if all work out with the output data types. Let me know if you need more info!

**Comment by ritchie46** [comment]
closed by #1631
