### ISSUE TITLE
ArrowInvalid: offset overflow while concatenating arrays

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#862]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.8.6

#### What operating system are you using polars on?

CentOS 7

#### Describe your bug.

`combine_chunks()` on a pyarrow array can fail with `ArrowInvalid: offset overflow while concatenating arrays`

`combine_chunks()` on the pyarrow table itself works and creates 3 chunks for that pyarrrow array column.

For more information:
https://issues.apache.org/jira/browse/ARROW-13150#

#### What are the steps to reproduce the behavior?

```python
In [63]: t2 = pl.functions.DataFrame.from_arrow(pa_table, True)
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-63-fcaaeb84cf42> in <module>
----> 1 t2 = pl.functions.DataFrame.from_arrow(t, True)
/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/frame.py in from_arrow(table, rechunk)
    343                 name = column._name
    344 
--> 345             column = coerce_arrow(column)
    346             data[name] = column
    347 
/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/utils.py in coerce_arrow(array)
     30 
     31     if hasattr(array, "num_chunks") and array.num_chunks > 1:
---> 32         array = array.combine_chunks()
     33     return array
     34 

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/pyarrow/table.pxi in pyarrow.lib.ChunkedArray.combine_chunks()

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.concat_arrays()

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: offset overflow while concatenating arrays
```

#### What is the expected behavior?

Not sure what is expected. Depending if all chunks indeed need to be combined or if a reduction of the number of chunks is already good enough.

If a reduction of chunks would already improve the situation, the chunked array could be put in a temp table and then combine_chunks can be run on the table itself.

**Comment by ritchie46** [comment]
The chunks need to be combined to a single array. Do you know what the data type is of the array that overflows?

**Comment by ghuls** [comment]
It was a string column (from parsing a CSV file that is tab delimitted, but in this test I forgot to set the separator to tab, so all 5 column were read as 1 column).

**Comment by ritchie46** [comment]
Right, then I think we can fix this by first casting to large-utf8. The utf8 type only uses signed 32 bit integers as the offsets for the strings. So if you have got more than 2GB of string bytes in an array you're overflowing already.

**Comment by ghuls** [comment]
Probably best to only convert it, if if fails with the `ArrowInvalid: offset overflow while concatenating arrays` exception, no?

As far as I can see, the following pyarrow datatypes have a `Large*` variant.
```
                   LargeBinaryArray  LargeListArray    LargeListValue    LargeStringValue 
                   LargeBinaryScalar LargeListScalar   LargeStringArray                   
                   LargeBinaryValue  LargeListType     LargeStringScalar
```



```
     if hasattr(array, "num_chunks") and array.num_chunks > 1:
         if is_instance(array, pa.StringArray):
             try:
                  array = array.combine_chunks()
     return array

**Comment by ritchie46** [comment]
Polars does not support `StringArrray`, only `LargeStringArray`. So converting has to be done anyway. Better do it early, then we don't do the work twice.

**Comment by ghuls** [comment]
Ah, in that case yes.
So I assume reading the file with polars itself instead of with `read_csv(..., use_pyarrow=True)` should work for those files?

**Comment by ritchie46** [comment]
> Ah, in that case yes.
> So I assume reading the file with polars itself instead of with `read_csv(..., use_pyarrow=True)` should work for those files?

Yes.. That would should work without problems.

It's still good to fix the issue in the conversion though.

**Comment by ghuls** [comment]
> It's still good to fix the issue in the conversion though.

Yes, as for gzipped files at least pyarrow's reading code is much faster.

**Comment by ghuls** [comment]
With a bit of luck it might also be solved in the future in pyarrow itself:
https://issues.apache.org/jira/projects/ARROW/issues/ARROW-13150
