### ISSUE TITLE
enable_string_cache(False) feels awkward, rename again?

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8631]
### Problem description

I know that this was *just* renamed from `toggle_string_cache` in #7970, but I find the new usage a bit awkward still. `enable_string_cache(False)` is a weird positive-negative cancellation going on. I propose one of the following two options:

#### 1. Enable/disable string cache as separate functions

```python
pl.enable_string_cache()   # enables the string cache
pl.disable_string_cache()  # disables the string cache
```

Downside: awkward to have two functions that do the same thing that one can with a boolean arg.
Upside: super explicit what's happpening.

#### 2. Set the string cache with an argument, but not in a confusing way

```python
pl.set_string_cache("on")   # enables the string cache
pl.set_string_cache("off")  # disables the string cache
```
Downside: requires passing a str arg, bool wouldn't really make sense unless someone can think of a better name;
Upside: pretty explicit, and also only uses one function.

**Comment by cmdlineluser** [comment]
perhaps `active` could be used similar to [`Config.activate_decimals`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Config.activate_decimals.html#polars.Config.activate_decimals)
```
pl.string_cache(active=True)
pl.string_cache(active=False)
```

**Comment by stinodego** [comment]
Closing in favor of https://github.com/pola-rs/polars/issues/10425
