### ISSUE TITLE
streaming doesn't work with scan_parquet with multiple parquet folders

### ISSUE THREAD

**Issue by ddutt** [pola-rs/polars#8633]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If we use `pl.scan_parquet('parquet-folder/**/*.parquet)` followed by any streamable operation such as unique(), streaming doesn't work if there are multiple parquet folders and/or nested folders with parquet files a couple of levels deep. 

### Reproducible example

```python
Not working example:

for folder in [folder1, folder2]:
    lf = (
       pl.scan_parquet(f'{folder}/**/*.parquet')
       .select(['timestamp'])
       .unique()
    )
    print(lf.explain(streaming=True))


Working example:

for folder in [folder1, folder2]:
    lf = (
       pl.scan_parquet(f'{folder}/*.parquet')
       .select(['timestamp'])
       .unique()
    )
    print(lf.explain(streaming=True))
```

### Expected behavior

Seeing explain produce output that shows streaming is being done. Further looking at memory consumed (via memory_profiler package) by running with and without streaming in the non-working example above showed no difference., while in the working example, clearly showed the memory benefits of streaming.

### Installed versions

<details>

0.16.15
0.17.9

</details>

**Comment by ritchie46** [comment]
Yeap, we don't have generic unions yet. I will see if I can pick that up again.

**Comment by ddutt** [comment]
Thanks for the workaround suggestion @sslivkoff. I instead decided to os.walk the directories and do the operation that way. I've too many files to do it the way you suggested, plus these are streaming files and more come in all the time.

**Comment by ritchie46** [comment]
I am working on this, but it needs some large refactors first to decrease the complexity.

**Comment by deanm0000** [comment]
Does it work with `pl.scan_pyarrow_dataset(ds.dataset(folder))` instead of `scan_parquet`?

**Comment by ddutt** [comment]
@deanm0000 No. See this https://github.com/pola-rs/polars/issues/7750
