### ISSUE TITLE
Allow `pl.from_repr` to parse output when `pl.Config(tbl_hide_column_data_types=True)`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#8638]
### Problem description

While testing different `Config` settings that customize dataframe output - I was passing the results back to `.from_repr`

With `tbl_hide_column_data_types=True`:
```
pl.from_repr("""
┌────────────┬─────────────────┐
│ package    ┆ version         │
╞════════════╪═════════════════╡
│ numpy      ┆ 1.24.2          │
│ pandas     ┆ 2.0.0           │
│ pyarrow    ┆ 11.0.0          │
│ connectorx ┆ <not installed> │
│ deltalake  ┆ 0.8.1           │
│ fsspec     ┆ 2023.4.0        │
│ matplotlib ┆ 3.7.1           │
│ xlsx2csv   ┆ 0.8.1           │
│ xlsxwriter ┆ 3.1.0           │
└────────────┴─────────────────┘
""")
```
```
/usr/local/lib/python3.10/site-packages/polars/convert.py in _from_dataframe_repr(m)
    272     # handle headers with wrapped column names and determine headers/dtypes
    273     header_block = ["".join(h).split("---") for h in zip(*rows[:table_body_start])]
--> 274     headers, dtypes = (list(h) for h in zip_longest(*header_block))
    275     body = rows[table_body_start + 1 :]
    276 

ValueError: not enough values to unpack (expected 2, got 1)
```
Would it make sense to default to `str` dtypes if no `---` is present in the header_block and allow this to be parsed?

**Comment by alexander-beedie** [comment]
Probably better to default to the same behaviour as generic CSV parsing in this case.

Note though that I don't think we want to try and allow every single possible permutation of reprs, as that will get complicated. The current "officially-supported" `repr` formats (for parsing) are UTF8_FULL and UTF8_FULL_CONDENSED, with/without row-separators an/or rounded-corners). Allowing parsing of reprs that have hidden the dtypes doesn't sound too burdensome though; I'll take a look.

**Comment by cmdlineluser** [comment]
@alexander-beedie Yeah, I wasn't too sure if this was worthwhile posting or not as it is related to custom config settings.

Thank you for the feedback.

**Comment by alexander-beedie** [comment]
> Thank you for the feedback.

No problem; wasn't hard to add this one, so... done ;)
