### ISSUE TITLE
Issue with nested expressions

### ISSUE THREAD

**Issue by chitralverma** [pola-rs/polars#8646]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Not sure if this affects only `sum` but seems like it is not able to work on derived values when nested.

With an extra column, it works fine.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"nums": pl.Series(values=[1, 2, 3, 4])})

# The resultant col is renamed to sum, but the summation doesn't happen.
incorrect = df.select(pl.sum(pl.col("nums") * 2))

print(df)

print(incorrect)
```

### Expected behavior

```
import polars as pl

# with an extra column, the summation works fine
correct_1 = df.with_columns((pl.col("nums") * 2).alias("nums")).select(pl.sum("nums"))

# calling .sum() in df works fine as well
correct_2 = df.with_columns((pl.col("nums") * 2)).sum()

print(correct_1)
print(correct_2)

```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: macOS-13.3.1-arm64-arm-64bit
Python: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.24.3
pandas: 2.0.1
pyarrow: 12.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.4.0
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>```

</details>

**Comment by ritchie46** [comment]
I think we should error. `pl.sum()` is syntactic sugar of `pl.col(..).sum()`. So what would the desugared experssion look like? Does that still work?

**Comment by chitralverma** [comment]
> I think we should error. `pl.sum()` is syntactic sugar of `pl.col(..).sum()`. So what would the desugared experssion look like? Does that still work?

desugared will be 
```
correct_3 = df.select((pl.col("nums") * 2).sum())
```

and it works

**Comment by stinodego** [comment]
I think the output is correct, but your expectations are wrong. If you input expressions, you get a horizontal sum. Read the docstring carefully.

Now I agree that this behaviour might be confusing. The only real solution is to have separate expressions for row-wise and column-wise aggregations.

**Comment by mcrumiller** [comment]
> I think we should error. pl.sum() is syntactic sugar of pl.col(..).sum().

@ritchie46 but that's not entirely correct, is it? The documentation explicitly states that that's the case only when the input argument is either a single string or a `pl.Series`, and in all other cases it sums horizontally:

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.sum.html
> If a single string is passed, this is an alias for `pl.col(name).sum()`. If a single Series is passed, this is an alias for `Series.sum()`.

**Comment by deanm0000** [comment]
On some level, it's tempting to say OP is doing it wrong so just move on.

On another level, it can't (or shouldn't) be that you get the same result (except column names) from

```
df.select(pl.col("nums") * 2)
```

and 

```
df.select(pl.sum(pl.col("nums") * 2))
```

I would think the result should be an error or have it give the answer OP is expecting but not the same thing as if they didn't put in the `pl.sum(...)`.

**Comment by stinodego** [comment]
The current behaviour is correct and properly documented. But I am not happy with the status quo as it can be confusing. And it will be confusing as long as we have one function doing multiple things.

I propose either:
* Add an argument to existing aggregation functions that controls whether aggregation happens horizontally or vertically. It defaults to vertical. If people want to aggregate horizontally, they specify `how="horizontal"`, `axis=1`, or something similar.
* Add separate functions for horizontal aggregations. For example, `row_sum`, `row_max`, etc.

**Comment by alexander-beedie** [comment]
> I propose either: ...

All would be good clarifications! (Although lets avoid `axis=<int>` terminology, which is not very descriptive - indeed, it is probably one of my most-hated "pandas-isms", as  I have to constantly look up what they think "1" means, whether it's zero-indexed or not, etc 🤣)

**Comment by stinodego** [comment]
> lets avoid `axis=<int>` terminology, which is not very descriptive - indeed, it is probably one of my most-hated "pandas-isms", as I have to constantly look up what they think "1" means, whether it's zero-indexed or not, etc 🤣)

Couldn't agree more - I just put that in there to show what others are doing to solve the same problem :)

If we go with the 'extra argument' approach, I would propose `how="vertical"/"horizontal"` like we have for `concat` already.

But I think having separate functions for these would actually be more in line with the Polars philosophy. In fact, on the Rust side some of these are already separate functions (`sum_exprs`, `min_exprs`, `max_exprs`). I'm not 100% sure about the naming, maybe `sum_rows`, `min_rows` would be best? That way, people can type `sum` and see the autocompletion for `sum_rows` and be reasonably sure what they're getting.

**Comment by ritchie46** [comment]
> That way, people can type sum and see the autocompletion for sum_rows and be reasonably sure what they're getting.

This rationale is applied in rust std a lot and I really like that. E.g. you have `get` and `get_unchecked` and they land in the same autocomplete areas. 

So `sum_rows` or `sum_horizontal` would be good names IMO.

**Comment by stinodego** [comment]
Right, I think I'll go for `sum_rows`. I'll take care of the addition/deprecation - I've been messing around with this parsing logic recently anyway.

**Comment by JulianCologne** [comment]
I like the intuitive naming with `horizontal` / `vertical`.
Personally I would prefer the extra argument approach but separate functions are also fine.

However, I do not like the name `sum_rows` which is ambiguous and confusion. It could mean:
- take the sum of individual rows over the columns (`horizontal`) or
- take the sum of all rows for each column (`vertical`)

**Comment by alexander-beedie** [comment]
> the name `sum_rows` is ambiguous

That not a bad point - `sum_horizontal` is longer, but there's no doubt what it means, and tab-complete will take care of the extra typing for you  ;)

**Comment by mcrumiller** [comment]
We have `hstack` and `vstack`, why not `hsum` and `vsum`?

**Comment by mcrumiller** [comment]
We have `hstack` and `vstack`, why not `hsum` and `vsum`?

**Comment by alexander-beedie** [comment]
> We have `hstack` and `vstack`, why not `hsum` and `vsum`?

Too non-standard; I've never seen those used in another system, and depending on your IDE/autocomplete you may type `sum` and find nothing, which wouldn't be good...

**Comment by mcrumiller** [comment]
@alexander-beedie yeah that might be an issue. To avoid verbosity, in the same way that we have `pl.concat(how=...)` in tandem with `hstack` and `vstack`, we could have `.sum(how="horizontal/vertical")` and *also* have `hsum` and `vsum` for brevity.

**Comment by stinodego** [comment]
Yep. `sum_horizontal` is the best one so far I think.

Considering nesting levels, having an extra argument is not very readable:

```python
df = df.with_columns(
    pl.sum(
        pl.col(...),
        pl.col(...),
        pl.col(...),
        how="horizontal"
    )
)
```

This looks much better and is more readable (the actual operation is defined at the start):

```python
df = df.with_columns(
    pl.sum_horizontal(
        pl.col(...),
        pl.col(...),
        pl.col(...),
    )
)
```

**Comment by mcrumiller** [comment]
Are we also considering implementing this in the `Expr` namespace, i.e.:

```python
df = df.with_columns(
    pl.col(['a', 'b', ...]).sum_horizontal()
)
```

Using `pl.horizontal_sum()` often requires you to move some operations to the left of the column selection and some to the right, which ends up being awkward. It's nice when your code looks like this:

```python
df.select(
    <selection>
    .op1()
    .op2()
    .op3()
    ...
)
```
whereas using `pl.sum_horizontal` requires this:

```python
df.select(
    pl.lop1(
        <selection>
    )
    .op2()
    .op3()
    ...
)
```

IMO it's a little harder to follow, sort of like changing `a + b + c` to be `sum(c, sum(a, b))`.

**Comment by mcrumiller** [comment]
@stinodego ahh right, my bad.

**Comment by chitralverma** [comment]
Thanks, everyone for the long constructive discussion on this.

What I described came while I was converting tpc-h SQL to py-polars DSL.

Here's what I think about this topic,

- it's correct that the horizontal sum of 1 expr/ col is the same as the input. 
- If as a user I was trying to do a horizontal sum of `n` cols won't it be better write it as `pl.col(x) + pl.col(y) ...` or even `pl.all().sum()` instead?
- Coming from a SQL/ Spark and a non-pandas background, for me at least `sum(expr)` always means vertical sum. Since SQL can be written as nested `expr(expr(....))` so naturally `pl.sum("x")` should also mean a sum of all the values in column `x`

So my suggestion here would be to neither have a kwarg `how` nor have a separate `sum_horizontal` because even though the IDE autocompletes works and it's an ok name, they are not standards.

Not sure if I was able to explain myself, but if the above note makes sense to you all, I would actually suggest changing the behaviour for `sum` and for other functions if this applies to them.

_side note:_ thinking about 2 random math functions `sum` and `mean` if their behaviours are non-SQL-like or are not consistent pulls in the additional point of function associativity/ commutativity. So for `sum`, we can have a horizontal and vertical operation but not for `mean`.

**Comment by ghuls** [comment]
I think `pl.all()` also has some column or row wise behavior depending on the invocation.

**Comment by cmdlineluser** [comment]
Would a `pl.row` helper make sense?

Something like:
```
def row(*exprs):
   if not exprs:
      exprs = ["*"] # pl.all()
   return pl.concat_list(*exprs).arr

pl.row = row
```
You could use that for any horizontal/row-based operations:
```
df = pl.from_repr("""
┌─────┬─────┬─────┐
│ A   ┆ B   ┆ C   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 5   ┆ 9   │
│ 2   ┆ 6   ┆ 10  │
│ 3   ┆ 7   ┆ 11  │
│ 4   ┆ 8   ┆ 12  │
└─────┴─────┴─────┘
""")
```
```
>>> df.with_columns(horizontal_sum = pl.row().sum())
shape: (4, 4)
┌─────┬─────┬─────┬────────────────┐
│ A   ┆ B   ┆ C   ┆ horizontal_sum │
│ --- ┆ --- ┆ --- ┆ ---            │
│ i64 ┆ i64 ┆ i64 ┆ i64            │
╞═════╪═════╪═════╪════════════════╡
│ 1   ┆ 5   ┆ 9   ┆ 15             │
│ 2   ┆ 6   ┆ 10  ┆ 18             │
│ 3   ┆ 7   ┆ 11  ┆ 21             │
│ 4   ┆ 8   ┆ 12  ┆ 24             │
└─────┴─────┴─────┴────────────────┘
```
```
>>> df.with_columns(horizontal_sum = pl.row("A", "C").sum())
shape: (4, 4)
┌─────┬─────┬─────┬────────────────┐
│ A   ┆ B   ┆ C   ┆ horizontal_sum │
│ --- ┆ --- ┆ --- ┆ ---            │
│ i64 ┆ i64 ┆ i64 ┆ i64            │
╞═════╪═════╪═════╪════════════════╡
│ 1   ┆ 5   ┆ 9   ┆ 10             │
│ 2   ┆ 6   ┆ 10  ┆ 12             │
│ 3   ┆ 7   ┆ 11  ┆ 14             │
│ 4   ┆ 8   ┆ 12  ┆ 16             │
└─────┴─────┴─────┴────────────────┘
```

**Comment by stinodego** [comment]
> * it's correct that the horizontal sum of 1 expr/ col is the same as the input -- so this is an un-necessary, confusing no-op anyways

Yes, but since users might be passing in a list of columns of unknown length, it should also produce the correct results when the number of columns is 1.

> * If as a user I was trying to do a horizontal sum of `n` cols won't it be better write it as `pl.col(x) + pl.col(y) ...` or even `pl.all().sum()` instead?

If you do not know which columns to sum beforehand, you cannot write it as a long summation, it has to be an operation on a list of columns. `pl.all().sum()` produces the vertical sum of each column, due to the way expressions work (explained earlier in this thread). So neither of these will suffice.

> * Coming from a SQL/ Spark and a non-pandas background, for me at least `sum(expr)` always means vertical sum. Since SQL can be written as nested `expr(expr(....))` so naturally `pl.sum("x")` should also mean a sum of all the values in column `x`

I don't fully understand, but in the end we want to provide users with an ergonomic way of doing horizontal aggregations. So we need both a vertical sum and a horizontal sum. We can discuss details of how these should be named, but the functionality needs to exist. The alternatives in your proposal are not sufficient.

**Comment by stinodego** [comment]
This has been resolved.
