### ISSUE TITLE
`search_sorted` gives wrong results with nulls and is generally inconsistent with numpy

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8647]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`search_sorted`'s handling of nulls does not seem correct. For example, the following does not appear correct.

```python
source = pl.DataFrame({"s": [None, 2, None, 6]})
target = pl.Series("t", [0, 2, 5])
source.select(pl.col("s").search_sorted(target, side="left"))

shape: (3, 1)
┌─────┐
│ s   │
│ --- │
│ u32 │
╞═════╡
│ 3   │
│ 3   │
│ 3   │
└─────┘

```

Based on how polars `search_sorted` seems to handle nulls I would have expected this to return

```python
shape: (3, 1)
┌─────┐
│ s   │
│ --- │
│ u32 │
╞═════╡
│ 1   │
│ 1   │
│ 3   │
└─────┘
```

On the other hand, if I shuffle the position of the null in the source to the end, it does something consistent.
```python
source = pl.DataFrame({"s": [None, 2, 6, None]})
target = pl.Series("t", [0, 2, 5])
source.select(pl.col("s").search_sorted(target, side="left"))

shape: (3, 1)
┌─────┐
│ s   │
│ --- │
│ u32 │
╞═════╡
│ 1   │
│ 1   │
│ 2   │
└─────┘

```

In general, even the "correct" handling of nulls in `search_sorted` is quite different than numpy's `np.searchsorted` so this may be worth documenting (or reconciling)? For example, numpy returns the same answer for the two queries above:

```python
np.searchsorted([np.nan, 2, np.nan, 6], [0, 2, 5], side="left")

array([0, 0, 2])


np.searchsorted([np.nan, 2, 6, np.nan], [0, 2, 5], side="left")

array([0, 0, 2])

```

As another example, in numpy searching for `np.nan` always returns the largest index, whereas polars returns zero:

```python
# Numpy
np.searchsorted([2, 6], [np.nan], side="left")

array([2])

# Polars
source = pl.DataFrame({"s": [2, 6]})
target = pl.Series("t", [None])
source.select(pl.col("s").search_sorted(target, side="left"))

shape: (1, 1)
┌─────┐
│ s   │
│ --- │
│ u32 │
╞═════╡
│ 0   │
└─────┘

```

### Reproducible example

```python
import polars as pl

source = pl.DataFrame({"s": [None, 2, None, 6]})
target = pl.Series("t", [0, 2, 5])
source.select(pl.col("s").search_sorted(target, side="left"))
```

### Expected behavior

Polars should handle nulls in `search_sorted` at least in an internally consistent way. Ideally it would also agree with how numpy handles `np.nan`.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Your column `s` is not sorted. We regard `Null` as lowest ordering value.

**Comment by erinov1** [comment]
Yikes, thanks for the quick pointer!
