### ISSUE TITLE
make groupby_dynamic and groupby_rolling accept UInt and/or implicit row_numbers

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#8650]
### Problem description

inspired by [this question](https://stackoverflow.com/questions/76153441/how-to-get-rolling-correlation-on-python-polars/76154525?noredirect=1#comment134306832_76154525)

Allow for the index parameter of groupby_* to accept a UInt column in addition to what it already accepts. If practical, also, a means to accept row indices without explicitly making them similar to the pandas syntax that OP of that question mentions.

**Comment by 2-5** [comment]
Known issue: https://github.com/pola-rs/polars/issues/7360

**Comment by deanm0000** [comment]
duplicate
