### ISSUE TITLE
`maintain_order` does not work in groupby?

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8652]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm a bit puzzled by this one — it feels like I'm missing something? I will be happy for someone to point out that I'm doing something stupid.

```python

df = pl.DataFrame({"A": ["a"] * 1_000 + ["b"] * 1_000, "B": [1] * 2_000})

df.groupby("A", maintain_order=True).agg(pl.col("B").mean())

# sometimes I get 
shape: (2, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ a   ┆ 1.0 │
│ b   ┆ 1.0 │
└─────┴─────┘

# other times I get
shape: (2, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ b   ┆ 1.0 │
│ a   ┆ 1.0 │
└─────┴─────┘
```

This is true in all of the version `0.17.*` versions I tried. I can't get the order to switch unless the height of the DataFrame is sufficiently large. For example, reducing the height by an order of magnitude,

```python
df = pl.DataFrame({"A": ["a"] * 100 + ["b"] * 100, "B": [1] * 200})

expected = pl.DataFrame({"A": ["a", "b"], "B": [1.0, 1.0]})

for _ in range(10_000):
    out = df.groupby("A", maintain_order=True).agg(pl.col("B").mean())
    testing.assert_frame_equal(expected, out)
```
never fails.

I didn't do a precise bisection, but going way back to 0.16.4 the ordering seems to be preserved correctly.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"A": ["a"] * 1_000 + ["b"] * 1_000, "B": [1] * 2_000})

df.groupby("A", maintain_order=True).agg(pl.col("B").mean())
```

### Expected behavior

`maintain_order` should work correctly.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
I don't think you're doing anything stupid - something seems to have changed.

From a quick test - `0.16.16` is the last working version for me which suggests `0.16.17` introduced it.

https://github.com/pola-rs/polars/releases/tag/py-0.16.17
