### ISSUE TITLE
fix(python): empty list or Series selections

### ISSUE THREAD

**Issue by mgperry** [pola-rs/polars#8659]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Select rows with an empty list (and column selector) returns an empty data frame with no columns. I don't think this is expected behaviour since a zero-length slice or an empty series returns the same dataframe but with no rows (ie same colnames + schema). `getitem` filters columns first and then passes the row selector to another `getitem` call, where it is interpreted as an empty list of columns. The fix for this is a simple sentinel that converts an empty list into `slice(0)`.

Selections with empty Series fail because the conversion calls `.max()` which returns `None` on an empty series (also numpy array). Using an empty list fails on this conversion as well.

This could be fixed using sentinel values in `_pos_idxs`, but I had a crack at refactoring `_pos_idxs` since there's a lot of logic shared between the DataFrame and Series implementation (see PR).

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1.0, 2.0, 3.0, 4.0], "b": [3, 4, 5, 6]})

df[:0, :] # returns data frame with columns ["a", "b"] and no rows

df[[], :] # returns data frame with no columns or rows

idxs = pl.Series("idx", [], dtype=pl.Int32)

df[idxs] # fails due to max() comparison inside _pos_idxs()

s = pl.Series("", range(10), dtype=pl.Int32)

s[[]] # error due to implicit conversion of series
```

### Expected behavior

```
df[[], :] # returns data frame with columns ["a", "b"] and no rows

s[idxs] # returns empty series of same type
s[[]] # returns empty series of same type
```

### Installed versions

<details>

```
Polars:      0.17.11
Index type:  UInt32
Platform:    Linux-5.15.0-71-generic-x86_64-with-glibc2.31
Python:      3.11.3 (main, May  3 2023, 11:24:38) [GCC 9.4.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  0.3.2a5
deltalake:   0.8.1
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0

```

</details>

**Comment by stinodego** [comment]
All these examples now work correctly.
