### ISSUE TITLE
Method to collect `count` of a LazyFrame as a python integer

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8664]
### Problem description

Sometimes I want to check that a LazyFrame is non-empty before piping a chain of operations whose behavior on an empty frame is difficult to test. Of course for a DataFrame I can look at `df.height`, but for LazyFrames I keep writing

```python
if ldf.select(pl.count()).collect().row(0)[0] > 0
    ...
```

Is there a less verbose way of writing `ldf.select(pl.count()).collect().row(0)[0]`? Should polars expose a method for this? I can write my own namespace but this seems like it would be widely used functionality.

**Comment by mcrumiller** [comment]
`len(ldf.collect())` is much shorter

Just write a quick function/lambda to do that. This is a specific request that I don't think belongs in the API.

```python
def lazycount(ldf):
    return ldf.select(pl.count()).collect().row(0)[0]
```

**Comment by ritchie46** [comment]
Another big reason is that a `LazyFrame` doesn't have length. It is a promise on future computations. If we would do those computations implicitly, we would trigger a lot of work silently.

IMO when the length is needed, you should materialize into a `DataFrame` and cache that `DataFrame` so that that work isn't done twice.

**Comment by erinov1** [comment]
I know there were previous discussions that rejected having a height property for LazyFrames, but it feels like this has similarities to the `sorted` flag on an expression and how it is propagated through the computation graph. For example, if I do
```python
ldf = ldf.collect().lazy()
```
then at that point we know the height of `ldf`. Certainly some complex computations `ldf.pipe(my_complex_operations)` could invalidate the height. On the other hand, something like `ldf.with_columns(new_col=pl.lit(1))` would preserve the height.

Another example would be if the `scan_ipc/parquet` functions are able to read the length from metadata (e.g., https://github.com/pola-rs/polars/pull/8473, https://github.com/pola-rs/polars/issues/6915, https://github.com/pola-rs/polars/issues/6870). In that case
```python
ldf = pl.scan_parquet("my_file.parquet")
```
would have its height known.

So LazyFrame could have a `height` property that is known at certain points and is `None` (or however else it makes sense to indicate that the height is unmaterialized) once additional operations are added to the computation graph. 

This could also be expanded to an option to collect/cache just the height, something like `ldf  = ldf.collect/cache(height_only=True)` which would compute and set the height property at that point in the graph.

**Comment by mcrumiller** [comment]
This is simply way too complex a request. How are you going to compute the height of a lazy frame that gets joined to another lazy frame when you don't even know the values? You'll now have to propagate the count and number of distinct values. At a certain point we just lose all of our laziness.

**Comment by erinov1** [comment]
> This is simply way too complex a request. How are you going to compute the height of a lazy frame that gets joined to another lazy frame when you don't even know the values? You'll now have to propagate the count and number of distinct values. At a certain point we just lose all of our laziness.

You wouldn't — a join would invalidate the height. 

```python
# height is automatically set
ldf = ldf.lazy().collect() 

# height is invalidated, returns None
ldf = ldf.join(other) 
assert ldf.height is None

# height is collected and set, but I acknowledge that I am implicitly collecting ldf.select(pl.count())
# which may trigger a large amount of work.
ldf = ldf.collect_height() 

# height would ideally be set from metadata
ldf_from_parquet = pl.scan_parquet("my_file.parquet").collect_height() 
```

That way I could access the height when piping operations,
```python
def my_operation(ldf: pl.LazyFrame) -> pl.LazyFrame:
    # short circuit if ldf has a known height and is empty
    if ldf.height == 0:
        return ldf
    # The height is unmaterialized, decide what to do
    if ldf.height is None:
         ... 

ldf.pipe(my_operation)
```

**Comment by icfly2** [comment]
This would actually be really useful in another context that I'm facing.

Get a "random" sample of data to estimate some property of it, the maths is too slow to do it for all the data / its not needed.

So I now go and get the `count`, then work out the number for `take_every`, which seems to be a bit convoluted.

But maybe there is a better way to get a random sample (aka `df.sample`) that I'm missing and this is of topic?

**Comment by abstractqqq** [comment]
@icfly2 

I think a more realistic change would be to allow Expr in take_every. This might change the underlying code for take_every a little bit but I think this is easier than implementing height.

**Comment by detrin** [comment]
I would like to have one method to estimate the length of `Lazyframe`. I think it is practical to have even when used for debugging.

**Comment by stinodego** [comment]
We will not add any methods to `LazyFrame` that implicitly do a `collect`.

A slightly shorter syntax for your current workaround is `lf.select(pl.count()).collect().item()`. However, this will execute the logical plan, and it will have to be executed again when you collect your final result. If the frame fits in memory, it's better to build in a 'checkpoint' like so:

```python
df = lf.collect()  # Do all computation up to this point
lf = df.lazy()
if not df.is_empty():
    lf = lf.select(...)  # Conditionally add new computation
lf = lf.select(...)  # Add new computation
result = lf.collect()  # Do all computation added after the checkpoint
```

The proposal by @erinov1 to track a height property throughout computation sounds interesting. Though the property will be invalidated by very common operations like a filter or a join. So it would not be reliable. But there are definitely cases where it could save some computation if you absolutely must know the length.

With the limited usefulness, combined with the fact that it's probably not simple to implement, I don't see this being added anytime soon. Though I would welcome a feature request.
