### ISSUE TITLE
Support user-defined order in `Expr.cat.set_ordering`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#8678]
### Problem description

Polars alreday has an api to set the order of a Categorical dtype with `Expr.cat.set_ordering`. It would be great to extend its support for user-defined order so that you could pass a list in `set_ordering` to define the cat order:
```python
import polars as pl

df = pl.DataFrame(
    {"cats": ["low", "high", "medium"]}
).with_columns(
    pl.col("cats").cast(pl.Categorical)
    .cat.set_ordering(["low", "medium", "high"]),
)
```

Right now, you must pre-fill a string cache to set the order of a cat dtype
```python
with pl.StringCache():
    pl.Series(["low", "medium", "high"]).cast(pl.Categorical)

    df = df.with_columns(
        pl.col("cats").cast(pl.Categorical)
    )
```

Or https://github.com/pola-rs/polars/issues/7632#issuecomment-1475025691

**Comment by mcrumiller** [comment]
Similar shoutout to #7162. Choice of lexical/physical ordering should be an input argument to `pl.Categorical`.

**Comment by stinodego** [comment]
There is now the `Enum` type where you can specify an ordering.
