### ISSUE TITLE
groupby_rolling to include null values

### ISSUE THREAD

**Issue by yusufuyanik1** [pola-rs/polars#8679]
### Problem description

I am trying to calculate money spent by each customer untill that point in time, without including the current row.
DataFrame looks like this:

```
dates = [datetime.date(2023, 5, 1), datetime.date(2023, 5, 2), datetime.date(2023, 5, 3)]
customer_ids = [1, 2, 1]
money_spent = [10.0, 20.0, 30.0]

df = pl.DataFrame({
    'date': pl.Series(dates),
    'customer_id': pl.Series(customer_ids),
    'money_spent': pl.Series(money_spent)
})
```

date	                    |  customer_id          |  money_spent

2023-05-01	    |   1	                          |  10.0
2023-05-02	    |   2	                          |  20.0
2023-05-03        |   1	                          |  30.0

when run this code:
`
df.groupby_rolling(index_column="date", period="1d", by="customer_id").agg(
    pl.sum("money_spent").alias("money_spent_untill_that_day")
)
`
It returns this:
customer_id	|  date 				|  money_spent_untill_that_day	

1			|  2023-05-01			|  10.0
1			|  2023-05-03			|  30.0
2			|  2023-05-02			|  20.0

Notice that the rolling groupby is inclusive of the row it applies to, I would expect the money spent untill 2023-05-01 for customer 1 to be null. I couldn't manage to achieve it by using "closed" or "offset" parameters of groupby_rolling function.
I think a new parameter like "inclusive" would be nice.

**Comment by cmdlineluser** [comment]
What should be the output for the other rows?

In your example the period of `1d` means each row is treated on its own:
```
df.groupby_rolling(index_column="date", period="1d", by="customer_id").agg(
   pl.col("money_spent")
)

# shape: (3, 3)
# ┌─────────────┬────────────┬─────────────┐
# │ customer_id ┆ date       ┆ money_spent │
# │ ---         ┆ ---        ┆ ---         │
# │ i64         ┆ date       ┆ list[f64]   │
# ╞═════════════╪════════════╪═════════════╡
# │ 1           ┆ 2023-05-01 ┆ [10.0]      │
# │ 1           ┆ 2023-05-03 ┆ [30.0]      │
# │ 2           ┆ 2023-05-02 ┆ [20.0]      │
# └─────────────┴────────────┴─────────────┘
```
Perhaps you're looking for `.shift().sum()`?
```
df.groupby_rolling(index_column="date", period="3d", by="customer_id").agg(
   pl.col("money_spent")
)

# shape: (3, 3)
# ┌─────────────┬────────────┬──────────────┐
# │ customer_id ┆ date       ┆ money_spent  │
# │ ---         ┆ ---        ┆ ---          │
# │ i64         ┆ date       ┆ list[f64]    │
# ╞═════════════╪════════════╪══════════════╡
# │ 1           ┆ 2023-05-01 ┆ [10.0]       │
# │ 1           ┆ 2023-05-03 ┆ [10.0, 30.0] │
# │ 2           ┆ 2023-05-02 ┆ [20.0]       │
# └─────────────┴────────────┴──────────────┘
```
```
df.groupby_rolling(index_column="date", period="3d", by="customer_id").agg(
   pl.col("money_spent").shift()
)

# shape: (3, 3)
# ┌─────────────┬────────────┬──────────────┐
# │ customer_id ┆ date       ┆ money_spent  │
# │ ---         ┆ ---        ┆ ---          │
# │ i64         ┆ date       ┆ list[f64]    │
# ╞═════════════╪════════════╪══════════════╡
# │ 1           ┆ 2023-05-01 ┆ [null]       │
# │ 1           ┆ 2023-05-03 ┆ [null, 10.0] │
# │ 2           ┆ 2023-05-02 ┆ [null]       │
# └─────────────┴────────────┴──────────────┘
```
Although your description sounds like a `.cumsum`?
```
df.with_columns(
   pl.col("money_spent").shift().cumsum().over("customer_id")
)

# shape: (3, 3)
# ┌────────────┬─────────────┬─────────────┐
# │ date       ┆ customer_id ┆ money_spent │
# │ ---        ┆ ---         ┆ ---         │
# │ date       ┆ i64         ┆ f64         │
# ╞════════════╪═════════════╪═════════════╡
# │ 2023-05-01 ┆ 1           ┆ null        │
# │ 2023-05-02 ┆ 2           ┆ null        │
# │ 2023-05-03 ┆ 1           ┆ 10.0        │
# └────────────┴─────────────┴─────────────┘
```

**Comment by yusufuyanik1** [comment]
`shift().sum()` gives me the output I expect as you mentioned. Thank you for the instant help
```
df.groupby_rolling(index_column="date", period="3d", by="customer_id").agg(
    [pl.col("money_spent").shift(),
     pl.col("money_spent").shift().sum().alias("cumsum_3days")]
)

```

|    |   customer_id | date                | money_spent   |   cumsum_3days |
|---:|--------------:|:--------------------|:--------------|---------------:|
|  0 |             1 | 2023-05-01 00:00:00 | [nan]         |            nan |
|  1 |             1 | 2023-05-03 00:00:00 | [nan 10.]     |             10 |
|  2 |             2 | 2023-05-02 00:00:00 | [nan]         |            nan |
