### ISSUE TITLE
Reconsider independent columns semantics

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#8680]
There are a number of column-oriented databases that provide a SQL (row-based) interface, for example ClickHouse, DuckDB, and AWS Redshift. The column-orientation is an implementation detail. Polars, on the other hand, is column-oriented and exposes an independent columns semantics. I find this design to be rather confusing for a table/dataframe library. In typical databases or dataframe libraries, a row represents a single data point in a higher-dimensional space. Thus, it normally makes no sense to, for example, sort the values of one column while keeping the other columns fixed. This would break the atomicity of the data points that are represented by rows.

The independent columns interface provides the user with many opportunities to shoot themselves in the foot. Here are some examples. In each example, the data represented by the rows of the input dataframe gets scrambled in non-sensical ways.

## Input data

```python
df = pl.DataFrame(dict(
    name = ["Charlie", "Alice", "Doug", "Bob", "Gertrude", "Erin"],
    age = [38, 42, 77, 21, 26, 32],
    job = ["Carpenter", "Banker", "Accountant", "Teacher", "Physicist", "Doctor"]
))
```

```python
In [17]: df
Out[17]:
shape: (6, 3)
┌──────────┬─────┬────────────┐
│ name     ┆ age ┆ job        │
│ ---      ┆ --- ┆ ---        │
│ str      ┆ i64 ┆ str        │
╞══════════╪═════╪════════════╡
│ Charlie  ┆ 38  ┆ Carpenter  │
│ Alice    ┆ 42  ┆ Banker     │
│ Doug     ┆ 77  ┆ Accountant │
│ Bob      ┆ 21  ┆ Teacher    │
│ Gertrude ┆ 26  ┆ Physicist  │
│ Erin     ┆ 32  ┆ Doctor     │
└──────────┴─────┴────────────┘
```

## Example 1

```python
df.with_columns(
    pl.col("name", "age", "job").sort()
)
```

```python
shape: (6, 3)
┌──────────┬─────┬────────────┐
│ name     ┆ age ┆ job        │
│ ---      ┆ --- ┆ ---        │
│ str      ┆ i64 ┆ str        │
╞══════════╪═════╪════════════╡
│ Alice    ┆ 21  ┆ Accountant │
│ Bob      ┆ 26  ┆ Banker     │
│ Charlie  ┆ 32  ┆ Carpenter  │
│ Doug     ┆ 38  ┆ Doctor     │
│ Erin     ┆ 42  ┆ Physicist  │
│ Gertrude ┆ 77  ┆ Teacher    │
└──────────┴─────┴────────────┘
```

## Example 2

```python
df.select(
    pl.col("name").sort(),
    pl.col("age").sort(),
    pl.col("job").sort()
)
```

```python
shape: (6, 3)
┌──────────┬─────┬────────────┐
│ name     ┆ age ┆ job        │
│ ---      ┆ --- ┆ ---        │
│ str      ┆ i64 ┆ str        │
╞══════════╪═════╪════════════╡
│ Alice    ┆ 21  ┆ Accountant │
│ Bob      ┆ 26  ┆ Banker     │
│ Charlie  ┆ 32  ┆ Carpenter  │
│ Doug     ┆ 38  ┆ Doctor     │
│ Erin     ┆ 42  ┆ Physicist  │
│ Gertrude ┆ 77  ┆ Teacher    │
└──────────┴─────┴────────────┘
```

## Example 3

```python
df.select(
    pl.col("name").sort().head(3),
    pl.col("age").filter(pl.col("age") > 35)
)
```

```python
shape: (3, 2)
┌─────────┬─────┐
│ name    ┆ age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ Alice   ┆ 38  │
│ Bob     ┆ 42  │
│ Charlie ┆ 77  │
└─────────┴─────┘
```

## Example 4

```python
df.select(
    pl.col("age").filter(pl.col("age") > 35),
    pl.col("job").filter(pl.col("job").is_in(["Teacher", "Physicist", "Doctor"]))
)
```

```python
shape: (3, 2)
┌─────┬───────────┐
│ age ┆ job       │
│ --- ┆ ---       │
│ i64 ┆ str       │
╞═════╪═══════════╡
│ 38  ┆ Teacher   │
│ 42  ┆ Physicist │
│ 77  ┆ Doctor    │
└─────┴───────────┘
```

## Example 5

```python
df.select(
    pl.col("name").head(3),
    pl.col("age").filter(pl.col("age") < 35),
    pl.col("job").filter(pl.col("job").is_in(["Teacher", "Physicist", "Doctor"]))
)
```

```python
shape: (3, 3)
┌─────────┬─────┬───────────┐
│ name    ┆ age ┆ job       │
│ ---     ┆ --- ┆ ---       │
│ str     ┆ i64 ┆ str       │
╞═════════╪═════╪═══════════╡
│ Charlie ┆ 21  ┆ Teacher   │
│ Alice   ┆ 26  ┆ Physicist │
│ Doug    ┆ 32  ┆ Doctor    │
└─────────┴─────┴───────────┘
```

## Example 6

```python
df.select(
    pl.col("name").head(3),
    pl.col("age").slice(1, 3),
    pl.col("job").tail(3)
)
```

```python
shape: (3, 3)
┌─────────┬─────┬───────────┐
│ name    ┆ age ┆ job       │
│ ---     ┆ --- ┆ ---       │
│ str     ┆ i64 ┆ str       │
╞═════════╪═════╪═══════════╡
│ Charlie ┆ 42  ┆ Teacher   │
│ Alice   ┆ 77  ┆ Physicist │
│ Doug    ┆ 21  ┆ Doctor    │
└─────────┴─────┴───────────┘
```

## Discussion

If you examine the output of each example, you can see that the data in each row is scrambled. For example, in the input dataframe, Alice is 42 and a banker. However, in the output of Example 1, she is 21 and an accountant, and in the output of Example 5, she is 26 and a physicist. This kind of data scrambling generally makes no sense. So we can see that the independent-columns approach in Polars allows a wide-range of non-sensical queries. In other words, Polars provides users with many ways to shoot themselves in the foot, since in practice almost nobody wants data scrambling of the sort that is seen in these examples.

In my opinion, filtering and sorting a table/dataframe only make sense when applied to rows. (I mean semantically. Implementation is another story.) It doesn't normally make sense to sort or filter columns independently of the other columns in the table/dataframe.

**Comment by ritchie46** [comment]
> In my opinion, filtering and sorting a table/dataframe only make sense when applied to rows. (I mean semantically. Implementation is another story.) It doesn't normally make sense to sort or filter columns independently of the other columns in the table/dataframe.

For those operations we have a `sort` and `filter` on the `DataFrame` level. We have this distinction very clear defined. Expression work on columnar units of work.

Your examples are similar to this pandas query. Which is allowed, but yeah, you shouldn't do very often.

```python
df["name"] = df["name"].sort_values()
df["age"] = df["age"].sort_values()
df["job"] = df["job"].sort_values()
```

There are many algorithms where I want to filter some elements, take the minimum value, sort 
The set of queries that don't make sense is large. Those queries you should not write. 

> In my opinion, filtering and sorting a table/dataframe only make sense when applied to rows.

Yes, I agree. But sorting and filtering columns also has merit. Here is one silly example.:

```python

def median_by_job(column: str, job: str) -> pl.Expr:
    subset = pl.col(column).where(pl.col("job") == job)
    return subset.sort().take(subset.count() / 2)
    
    
df.select(
    median_by_job("age", "Carpenter").alias("age_carpenter"),
    median_by_job("height", "Carpenter").alias("h_caprenter"),
)
```

There are many. This is a different paradigm than row based.

**Comment by mcrumiller** [comment]
Also, there is a someone not-obvious-to-new-users way to work in a multi-column context: `pl.struct`. I still think that `pl.struct` should instead be called `pl.multicol` and have an auto-unnest feature. This solves many of the problems. Here is are your examples using `pl.struct`:

# Example 1
```python
df.select(
    pl.struct("name", "age", "job").sort().alias("struct")
).unnest("struct")
```
we keep the tuples:
```
shape: (6, 3)
┌──────────┬─────┬────────────┐
│ name     ┆ age ┆ job        │
│ ---      ┆ --- ┆ ---        │
│ str      ┆ i64 ┆ str        │
╞══════════╪═════╪════════════╡
│ Alice    ┆ 42  ┆ Banker     │
│ Bob      ┆ 21  ┆ Teacher    │
│ Charlie  ┆ 38  ┆ Carpenter  │
│ Doug     ┆ 77  ┆ Accountant │
│ Erin     ┆ 32  ┆ Doctor     │
│ Gertrude ┆ 26  ┆ Physicist  │
└──────────┴─────┴────────────┘
```

# Example 3
```python
df.select(pl.struct("name", "age").filter(col("age") > 35).sort().head(3).alias("struct")).unnest("struct")
```
```
shape: (3, 2)
┌─────────┬─────┐
│ name    ┆ age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ Alice   ┆ 42  │
│ Charlie ┆ 38  │
│ Doug    ┆ 77  │
└─────────┴─────┘
```

I left out 2 and 6 because I think those were just to show that each expression operates on columns individually.
# Example 4
```python
df.select(
    pl.struct("age", "job").filter(
        (col("age") > 35) & col("job").is_in(["Teacher", "Physicist", "Doctor"])
    ).alias("struct")
).unnest("struct")
```
```
shape: (0, 2)
┌─────┬─────┐
│ age ┆ job │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
└─────┴─────┘
```

# Example 5
```python
df.select(
    pl.struct("name", "age", "job").filter(
        (col("age") < 35) & col("job").is_in(["Teacher", "Physicist", "Doctor"])
    ).head(3).alias("struct")
).unnest("struct")
```
```
shape: (3, 3)
┌──────────┬─────┬───────────┐
│ name     ┆ age ┆ job       │
│ ---      ┆ --- ┆ ---       │
│ str      ┆ i64 ┆ str       │
╞══════════╪═════╪═══════════╡
│ Bob      ┆ 21  ┆ Teacher   │
│ Gertrude ┆ 26  ┆ Physicist │
│ Erin     ┆ 32  ┆ Doctor    │
└──────────┴─────┴───────────┘
```

**Comment by CameronBieganek** [comment]
> Your examples are similar to this pandas query.

I guess I was hoping that bad things you can do in Pandas would be disallowed in Polars. :)

----------------------

Thanks for the examples. However, in my opinion, each example is more naturally expressed using table operations (as opposed to independent column operations). Here is how I would treat those examples.

## Median age and height of carpenters

### Data

```python
employees = pl.DataFrame(dict(
    id = [1, 2, 3, 4, 5, 6],
    age = [23, 40, 51, 25, 31, 60],
    height = [150, 160, 170, 145, 155, 165],
    job = ["Plumber", "Plumber", "Plumber", "Carpenter", "Carpenter", "Carpenter"]
))
```

```python
┌─────┬─────┬────────┬───────────┐
│ id  ┆ age ┆ height ┆ job       │
│ --- ┆ --- ┆ ---    ┆ ---       │
│ i64 ┆ i64 ┆ i64    ┆ str       │
╞═════╪═════╪════════╪═══════════╡
│ 1   ┆ 23  ┆ 150    ┆ Plumber   │
│ 2   ┆ 40  ┆ 160    ┆ Plumber   │
│ 3   ┆ 51  ┆ 170    ┆ Plumber   │
│ 4   ┆ 25  ┆ 145    ┆ Carpenter │
│ 5   ┆ 31  ┆ 155    ┆ Carpenter │
│ 6   ┆ 60  ┆ 165    ┆ Carpenter │
└─────┴─────┴────────┴───────────┘
```

### Query

```python
(
     employees
     .groupby("job")
     .agg(
         median_age = pl.col("age").median(),
         median_height = pl.col("height").median()
      )
     .filter(pl.col("job") == "Carpenter")
)
```

```
┌───────────┬────────────┬───────────────┐
│ job       ┆ median_age ┆ median_height │
│ ---       ┆ ---        ┆ ---           │
│ str       ┆ f64        ┆ f64           │
╞═══════════╪════════════╪═══════════════╡
│ Carpenter ┆ 31.0       ┆ 155.0         │
└───────────┴────────────┴───────────────┘
```

## Bowling Scores

This is a case where an R programmer from the "tidyverse" would say that your initial data is not "tidy". If we take the tidy data approach, we can apply normal table operations, and then at the end we can do a `pivot` if we wish.

### Data

```python
import numpy as np
import polars as pl

bowling_scores = pl.DataFrame(dict(
    game = np.repeat([1, 2, 3, 4], 4),
    person = np.tile(["alice", "james", "mihoko", "kendall"], 4),
    score = [201, 120, 160, 155, 156, 124, 158, 120, 170, 99,
             184, 130, 162, 115, 170, 160]
))
```

```python
┌──────┬─────────┬───────┐
│ game ┆ person  ┆ score │
│ ---  ┆ ---     ┆ ---   │
│ i32  ┆ str     ┆ i64   │
╞══════╪═════════╪═══════╡
│ 1    ┆ alice   ┆ 201   │
│ 1    ┆ james   ┆ 120   │
│ 1    ┆ mihoko  ┆ 160   │
│ 1    ┆ kendall ┆ 155   │
│ 2    ┆ alice   ┆ 156   │
│ 2    ┆ james   ┆ 124   │
│ 2    ┆ mihoko  ┆ 158   │
│ 2    ┆ kendall ┆ 120   │
│ 3    ┆ alice   ┆ 170   │
│ 3    ┆ james   ┆ 99    │
│ 3    ┆ mihoko  ┆ 184   │
│ 3    ┆ kendall ┆ 130   │
│ 4    ┆ alice   ┆ 162   │
│ 4    ┆ james   ┆ 115   │
│ 4    ┆ mihoko  ┆ 170   │
│ 4    ┆ kendall ┆ 160   │
└──────┴─────────┴───────┘
```

### Query

```python
(
    bowling_scores
    .sort(["person", "score"], descending=[False, True])
)
```

```
┌──────┬─────────┬───────┐
│ game ┆ person  ┆ score │
│ ---  ┆ ---     ┆ ---   │
│ i32  ┆ str     ┆ i64   │
╞══════╪═════════╪═══════╡
│ 1    ┆ alice   ┆ 201   │
│ 3    ┆ alice   ┆ 170   │
│ 4    ┆ alice   ┆ 162   │
│ 2    ┆ alice   ┆ 156   │
│ 2    ┆ james   ┆ 124   │
│ 1    ┆ james   ┆ 120   │
│ 4    ┆ james   ┆ 115   │
│ 3    ┆ james   ┆ 99    │
│ 4    ┆ kendall ┆ 160   │
│ 1    ┆ kendall ┆ 155   │
│ 3    ┆ kendall ┆ 130   │
│ 2    ┆ kendall ┆ 120   │
│ 3    ┆ mihoko  ┆ 184   │
│ 4    ┆ mihoko  ┆ 170   │
│ 1    ┆ mihoko  ┆ 160   │
│ 2    ┆ mihoko  ┆ 158   │
└──────┴─────────┴───────┘
```

Then we can pivot that table... except I can't actually get `pivot` to output the right thing. That might indicate a missing method, or a missing keyword argument to `pivot`. Or maybe I'm using `pivot` wrong. It seems like there ought to be a natural way to pivot the output above and retain the sorting of the scores.

## pl.struct

I haven't played around with `pl.struct` yet. It looks interesting, but of course those examples can all be done with regular table operations. Your version of Example 3 can be written as

```python
(
    df
    .select("name", "age")
    .filter(pl.col("age") > 35)
    .sort("name", "age")
    .head(3)
)
```

**Comment by CameronBieganek** [comment]
Anyhow, I didn't really expect that this design would be changed at this point. I just thought it would be good to open an issue to discuss the pros and cons of the design. If nothing else, you can point users to this issue if they have similar questions/concerns.

**Comment by ritchie46** [comment]
> Thanks for the examples. However, in my opinion, each example is more naturally expressed using table operations (as opposed to independent column operations). Here is how I would treat those examples.

Sure, and that's fine. I think I agree also. The point is, expressions still have merit. You can make complicated expressions and run them for instance in a groupby aggregation in an efficient matter.

> I guess I was hoping that bad things you can do in Pandas would be disallowed in Polars. :)

I believe every dataframe allows setting an independent column? There are subsets of queries that don't make sense. 

We provide the tools and the logical rules, but we cannot statically know if every combination of them makes sense to your business logic. The queries you added in your example are silly once you have grokked the rules polars query engine adheres by.

I agree with you on full table operations. You should use regular table operations for sorting, grouping, joining and filtering in most cases. That doesn't mean we shouldn't provide a column sort as well.

**Comment by alexander-beedie** [comment]
Will close, leaving it as a good reference for any future queries along the same line, with the final summary:

* If you want to operate at the frame-level, use the frame-level methods.
* If you want to operate at the series-level, use the series-level methods.

**Comment by soerenwolfers** [comment]
Claiming the bowling games are represented more naturally in long(er) format is a bit of a stretch, and seems to be a conclusion speaking for it's arguments: of course if all you have is row operations you want as many rows as possible. 

What if you want to you add the length of the game? The cost of the game? The time of the game? In the original format, those are all perfectly natural columns. In your "tidy" version, I guess that would need to be two new tables? Doable, but hardly convincingly superior for all users and use cases.
