### ISSUE TITLE
fill_null for str column cause the data type being changed to 'object'

### ISSUE THREAD

**Issue by xshen8888** [pola-rs/polars#8681]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

after fill_null() on str / Utf8 columns, datatype should remain unchanged.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/64864908/236300365-aa97dd74-f2af-4191-81eb-03bf2872a3fb.png">

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "A": [1, 2, 3],
    "B": [10, 20, 30],
    "C": ["foo", "bar", None]
})
print(df) # datatype for column 'C' is str
df[['C']] = df[['C']].fill_null('hi')
print(df) # after fill_null(), datatype for column 'C' has been changed to object
```

### Expected behavior

after fill_null() on str / Utf8 columns, datatype should remain unchanged.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.7 (default, Nov 22 2022, 21:31:31)
[Clang 12.0.0 (clang-1200.0.32.29)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.0
pyarrow: 6.0.1
connectorx: <not installed>
deltalake: 0.5.8
fsspec: 2022.11.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Your polars syntax is wrong. Not at a laptop atm, but this doesn't seem right.

**Comment by avimallu** [comment]
This doesn't happen as ritchie mentioned for Polars syntax:

```py
>>> import polars as pl
>>> 
>>> df = pl.DataFrame({
...     "A": [1, 2, 3],
...     "B": [10, 20, 30],
...     "C": ["foo", "bar", None]
... })
>>> df.fill_null("hi")
shape: (3, 3)
┌─────┬─────┬─────┐
│ A   ┆ B   ┆ C   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ str │
╞═════╪═════╪═════╡
│ 1   ┆ 10  ┆ foo │
│ 2   ┆ 20  ┆ bar │
│ 3   ┆ 30  ┆ hi  │
└─────┴─────┴─────┘
```

**Comment by xshen8888** [comment]
@avimallu @ritchie46 , thanks.
What is the syntax for fill_null() on specific column names provided as a list?
E.g. I have columns C & D that are str type that I want to fill_null with value 'missing', what will the syntax be? 
str_cols = ['C', 'D']
df = df.with_columns(?) <- how can it take the list str_cols ?
I could do a for loop but is there a more efficient way?
Also what is the syntax of applying fill_null to all the str columns to a Dataframe?
Thanks a lot!

**Comment by avimallu** [comment]
Here's how:

```
>>> import polars as pl
>>> df = pl.DataFrame({
...     "a": ["1", "2", "a", "c"],
...     "b": ["b", "c", "d", "3"],
...     "c": [1, 2, 3, 4],
...     "d": ["9", "c", "e", "fff"]})
>>> df.with_columns(
...     pl.col("a", "b").str.lengths())
shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ u32 ┆ u32 ┆ i64 ┆ str │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   ┆ 9   │
│ 1   ┆ 1   ┆ 2   ┆ c   │
│ 1   ┆ 1   ┆ 3   ┆ e   │
│ 1   ┆ 1   ┆ 4   ┆ fff │
└─────┴─────┴─────┴─────┘
>>> df.with_columns(
...     pl.col(["a", "b"]).str.lengths())
shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ u32 ┆ u32 ┆ i64 ┆ str │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   ┆ 9   │
│ 1   ┆ 1   ┆ 2   ┆ c   │
│ 1   ┆ 1   ┆ 3   ┆ e   │
│ 1   ┆ 1   ┆ 4   ┆ fff │
└─────┴─────┴─────┴─────┘
>>> df.with_columns(
...     pl.col(pl.Utf8).str.lengths())
shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ u32 ┆ u32 ┆ i64 ┆ u32 │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   ┆ 1   │
│ 1   ┆ 1   ┆ 2   ┆ 1   │
│ 1   ┆ 1   ┆ 3   ┆ 1   │
│ 1   ┆ 1   ┆ 4   ┆ 3   │
└─────┴─────┴─────┴─────┘
```

**Comment by xshen8888** [comment]
@avimallu , thanks!
May I ask another question?
I need to read all parquet files in AWS S3 to a single pl.DataFrame. Right now I am reading them in in a loop and vstack() them like below. Although it works, is there a more efficient way to do this?
    import s3fs

    INPUT_PATH = f's3a://path/*.parquet'
    s3 = s3fs.S3FileSystem(anon=False)
    all_files = s3.glob(INPUT_PATH)   
    logging.info(all_files)
    afs = ['s3://' + f for f in all_files]
    print(afs)
    df = pl.DataFrame()
    for file in afs:
        df_temp = pl.read_parquet(file)
        df = df.vstack(df_temp)

**Comment by cmdlineluser** [comment]
> I need to read all parquet files in AWS S3 to a single pl.DataFrame

Perhaps https://stackoverflow.com/a/76126718 helps.

**Comment by xshen8888** [comment]
@avimallu , thanks.
I follow the self doc in pyarrow.dataset.py for def dataset():
    Opening a dataset for a single directory:

    >>> dataset("path/to/nyc-taxi/", format="parquet")
    >>> dataset("s3://mybucket/nyc-taxi/", format="parquet")
My code below:
    INPUT_PATH = f's3://bucket/path/' #with / at the end to indicate it's a directory
    # load multiple parquet files
    s3 = s3fs.S3FileSystem()
    pyarrow_dataset = dataset(
        source = INPUT_PATH,
        filesystem = s3,
        format = 'parquet',
        exclude_invalid_files=True
    )
    df = pl.scan_pyarrow_dataset( pyarrow_dataset ).collect()
Got: 
 File "pyarrow/_dataset.pyx", line 2647, in pyarrow._dataset.FileSystemDatasetFactory.__init__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'hbomax-datascience-deployment-dev/flyte-workflows/team=dai-mlp/project=test/version=1.0/inference/latest/input/raw/data9.parquet', which is outside base dir 's3://hbomax-datascience-deployment-dev/flyte-workflows/team=dai-mlp/project=test/version=1.0/inference/latest/input/raw/' (data9.parquet is the last file in the directory)
The above code works if I specify a file name in the INPUT_PATH. But I need it to work in directory.

**Comment by avimallu** [comment]
This seems more suited as a separate issue or a Stackoverflow question, rather than a continuation of an issue raised that was addressed.
