### ISSUE TITLE
Incorrect dtypes when aggregating `take` and `search_sorted`.

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8683]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Consider the following example:
```python
ldf = pl.LazyFrame({"A": [1, 2, 3, 4], "B": [1, 1, 2, 2]})

for indices in [[], [0], [0, 1]]:
    ldf.groupby("B").agg(pl.col("A").take(indices).schema

{'B': Int64, 'A': List(Int64)}
{'B': Int64, 'A': List(Int64)} <--- Lazy mode thinks this will be of list type
{'B': Int64, 'A': List(Int64)}


for indices in [[], [0], [0, 1]]:
    ldf.groupby("B").agg(pl.col("A").take(indices)).collect().schema

{'B': Int64, 'A': List(Int64)}
{'B': Int64, 'A': Int64}        <--- When materialized it is actually of scalar type
{'B': Int64, 'A': List(Int64)}
```

This is common to many of the expressions that can return any nonnegative number of outputs (like `search_sorted`). It means one can't write lazy queries like 

```python
ldf.groupby("B").agg(pl.col("A").take(indices)).explode().collect()
```

without a priori knowing the length of `indices` (or more generally when `indices` is an expression) since the explode raises an error in the `indices = [0]` case (despite the lazy schema thinking that the result will be of list type). It seems like the current result

```python
ldf.groupby("B").agg(pl.col("A").take([0]).collect()

shape: (2, 2)
┌─────┬─────┐
│ B   ┆ A   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 2   ┆ 3   │
│ 1   ┆ 1   │
└─────┴─────┘
```

should always be forced to return a list type, e.g., 

```python
shape: (2, 2)
┌─────┬───────────┐
│ B   ┆ A         │
│ --- ┆ ---       │
│ i64 ┆ list[i64] │
╞═════╪═══════════╡
│ 2   ┆ [3]       │
│ 1   ┆ [1]       │
└─────┴───────────┘
```
in case the aggregated expression happens to only returns a single element.

### Reproducible example

```python
import polars as pl

ldf = pl.LazyFrame({"A": [1, 2, 3, 4], "B": [1, 1, 2, 2]})

for indices in [[], [0], [0, 1]]:
    ldf.groupby("B").agg(pl.col("A").take(indices)).collect()
```

### Expected behavior

Schema and results should be consistent when aggregating an expression with an unknown number of outputs.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: macOS-13.2-arm64-arm-64bit
Python: 3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by erinov1** [comment]
@stinodego what do you think about adding this to the [0.18.0 milestones](https://github.com/pola-rs/polars/milestone/5)? This is another example of inconsistently returning lists vs. scalars (similar in spirit to https://github.com/pola-rs/polars/pull/8513) but a fix would be a breaking change. I'm not sure if @ritchie46 has seen this issue.

**Comment by stinodego** [comment]
I can confirm this behaviour and it's something we should change.

Behaviour should probably be:
* if you pass an iterable, you get the original List type.
* if you pass a single integer, you get the inner type of the List.

Not sure it should be part of 0.18.0. It should be fixed, obviously, but our time is limited, and I don't think it's a trivial fix. But feel free to issue a fix - if it's in time for 0.18.0, we'll include it.

**Comment by erinov1** [comment]
Thanks! I just wanted to raise some visibility since I think fixing this is important for API consistency but is also breaking. 

Fixing this definitely exceeds my understanding of the rust code, especially since I am not sure a single fix would apply to all affected operations (e.g., `take` vs. `search_sorted` and likely other operations).

**Comment by erinov1** [comment]
I went through all of the existing expressions, and it seems like its actually only `take` and `search_sorted` that are affected. In other words:

```python
ldf = pl.LazyFrame({"A": [1, 2, 3, 4], "B": [1, 1, 2, 2]})

indices = pl.Series([0])

# Should return list type for consistency
ldf.groupby("B").agg(pl.col("A").take(indices)).collect()

# Should return list type for consistency
ldf.groupby("B").agg(pl.col("A").search_sorted(indices)).collect()
```

**Comment by stinodego** [comment]
On main, this seems to have been fixed to always return a list type.
