### ISSUE TITLE
Using .over() with .when() produces unexpected results

### ISSUE THREAD

**Issue by supermarin** [pola-rs/polars#8692]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using .over()  with .when().then().otherwise() in subsequent .with_columns() computation produces unexpected results.
In the example below, the computation should have no difference if .over() is used or not, since `strike` is single-row based.

### Reproducible example

```python
import polars as pl


df = pl.DataFrame({
    "ticker": ["AAPL", "AAPL", "GOOG", "AAPL", "AAPL", "GOOG", ],
    "close": [10, 11, 9, 11, 15, 10],
}).with_columns(
    pl.col("close").pct_change().alias("returns").over("ticker")
).with_columns(
    pl
    .when(pl.col('returns') > 0.3)
    .then(True)
    .otherwise(False)
    .alias('strike')
    .over('ticker') # This line produces incorrect results while it shouldn't change anything
)
```

### Expected behavior

With .over() commented out:
```
┌────────┬───────┬──────────┬────────┐
│ ticker ┆ close ┆ returns  ┆ strike │
│ ---    ┆ ---   ┆ ---      ┆ ---    │
│ str    ┆ i64   ┆ f64      ┆ bool   │
╞════════╪═══════╪══════════╪════════╡
│ AAPL   ┆ 10    ┆ null     ┆ false  │
│ AAPL   ┆ 11    ┆ 0.1      ┆ false  │
│ GOOG   ┆ 9     ┆ null     ┆ false  │
│ AAPL   ┆ 11    ┆ 0.0      ┆ false  │
│ AAPL   ┆ 15    ┆ 0.363636 ┆ true   │
│ GOOG   ┆ 10    ┆ 0.111111 ┆ false  │
└────────┴───────┴──────────┴────────┘
```

With .over():
```
┌────────┬───────┬──────────┬────────┐
│ ticker ┆ close ┆ returns  ┆ strike │
│ ---    ┆ ---   ┆ ---      ┆ ---    │
│ str    ┆ i64   ┆ f64      ┆ bool   │
╞════════╪═══════╪══════════╪════════╡
│ AAPL   ┆ 10    ┆ null     ┆ false  │
│ AAPL   ┆ 11    ┆ 0.1      ┆ false  │
│ GOOG   ┆ 9     ┆ null     ┆ false  │
│ AAPL   ┆ 11    ┆ 0.0      ┆ false  │
│ AAPL   ┆ 15    ┆ 0.363636 ┆ false  │
│ GOOG   ┆ 10    ┆ 0.111111 ┆ true   │
└────────┴───────┴──────────┴────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: Linux-6.3.1-x86_64-with-glibc2.35
Python: 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
---Optional dependencies---
numpy: 1.24.3
pandas: 2.0.1
pyarrow: 12.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>

```

</details>

**Comment by supermarin** [comment]
Side note: using `.gt(0.3)` instead of `.when().then().otherwise()` works ok, no change in behavior with .over().

**Comment by mcrumiller** [comment]
I'm not really sure what to expect here because you just a randomly orphaned `.over()` with no associated window function. Can you find a situation in which `.over` fails for a window function?

Maybe we should raise an exception when `.over` is used without a window?

**Comment by ritchie46** [comment]
> Maybe we should raise an exception when `.over` is used without a window?

Yes!

**Comment by stinodego** [comment]
Both  queries now correctly produce the same result.
