### ISSUE TITLE
Error: duplicate: column with name '...' has more than one occurrences when using groupby_dynamic

### ISSUE THREAD

**Issue by vitordhers** [pola-rs/polars#8695]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Hello, folks, first of all, thanks to all contributors for this amazing tool.

I've been trying to use **Polars Rust** in order to make some investing analysis. Previously, I was using **Polars Python**, and, as expected it's the right tool for the job. Since I'd like to improve the performance of my analysis, and know a thing or two in Rust (_**Rust** evangelism strikeforce ftw, btw_), I'm implementing some back-testing I've done in **Python**, but using the **Rust** this time.

Basically, I'm trying to add a [stochastic oscillator](https://www.investopedia.com/terms/s/stochasticoscillator.asp) to my code, so that I can have signals of when take positions in bitcoin trading. Thing is, I'd like to add more than one indicator in order to take more educate guesses of when to take or leave a certain position. For the being, please consider that this indicator uses stochastic data in its calculation, so that, **rolling** resamples are in order to achieve them.

Not all indicators take the same windows of time to be calculated. In my effort to try to consolidate them in a `1-minute-basis` `Datetime` `Dataframe`, I've found an issue that I consider to be a **bug** (even though I'm a rustling, I'll explain soon why I've considered so).

First, I grab some historical data of bitcoin prices in a minute-basis from Binance `websocket`/`http` APIs. Then, after receiving the data from the past day, and start listening to the `websocket`, and proceed to calculate the indicators.
In order to do so, since stochastic oscillator uses rolling windows, I calculate the indicator for a separate window of time, downsampling the original minute-basis `start_time` from `1-minute-basis` to a `3-minute-basis`. After that, I want to consolidate these columns, upsampling the new `DataFrame` (with stochastic oscillator data) back from `3-minute-basis` back to `1-minute-basis`. 

It seems pretty straight forward, right? I'm getting this error in that upsampling part:
`Polars Error = "duplicate: column with name 'start_time' has more than one occurrences"`

I was able to do that in Polars Python, but not in Polars Rust.
In Python, my code for upsampling goes about this:

```
data = data.upsample(time_column='start_time',
                             every="1m").fill_null(strategy="forward")
```
and, like in a magic trick, the `3-minute-basis` data becomes a `DataFrame` with 1 minute granularity, forward filled.
Now, see the part below for the issue in Rust

### Reproducible example

Currently, my code goes about this (naturally it needs improvement, but that's not its final version. Any suggestions are welcome, _btw_).

```
pub fn resample_lf_to_mins(lf: &LazyFrame, mins: i64) -> LazyFrame {
    println!("COLUMNS NAMES {:?}", lf.clone().collect().unwrap().get_column_names());
    let period = mins * NANOS_IN_SECOND * SECONDS_IN_MIN;
    // Ok(lf
    //     .clone()
    //     .collect()?
    //     .upsample(["start_time"], "start_time", Duration::new(period), Duration::new(0))? // might as well use equivalent ::parse() 
    //     .fill_null(FillNullStrategy::Forward(None))?
    //     .lazy()
    // )
    let gb = lf.clone()
        .groupby_dynamic(
            vec![],
            DynamicGroupOptions {
                start_by: StartBy::DataPoint,
                index_column: "start_time".into(),
                every: Duration::new(period),
                period: Duration::new(period),
                offset: Duration::parse("0s"),
                truncate: true,
                include_boundaries: false,
                closed_window: ClosedWindow::Right,
            },
        );

        gb.agg([col("*")])
}
```
That throws the error mentioned:
`Polars Error = "duplicate: column with name 'start_time' has more than one occurrences"`
Except that there aren't. I've purposely printed `DataFrame` columns names, getting this result:
`COLUMNS NAMES ["start_time", "BTCUSDT_3_open", "BTCUSDT_3_high", "BTCUSDT_3_close", "BTCUSDT_3_low", "BTCUSDT_K%_3", "BTCUSDT_D%_3"]`
That's why I believe that's a **bug**, in my humble rustling opinion. I've also printed `LazyFrame`'s `LogicalPlan` in order to see if I was missing anything. I get the same result when it comes to `LazyFrame` columns names.

Not only that, I've speculated that maybe the error was at `.agg([col("*")])`, so I've tried replacing it with `head()` method, which is less convoluted to the eyes of my feeble skills in Rust. I've also set the `truncate` field on `DynamicGroupOptions` to false. In both cases, same error persists. Also, I've tried to add `vec![col("start_time")]` to `DynamicGroupOptions`'s `by` parameter. Again, same error.

As you can see, I've also tried to use `DataFrame`'s regular `upsample` / `upsample_stable` method, also to no avail. Even though I didn't get any errors this time, I also didn't get any resampling. It yielded the same `DataFrame` shown below:
```
┌─────────────────────┬────────────────┬────────────────┬─────────────────┬───────────────┬──────────────┬──────────────┐
│ start_time          ┆ BTCUSDT_3_open ┆ BTCUSDT_3_high ┆ BTCUSDT_3_close ┆ BTCUSDT_3_low ┆ BTCUSDT_K%_3 ┆ BTCUSDT_D%_3 │
│ ---                 ┆ ---            ┆ ---            ┆ ---             ┆ ---           ┆ ---          ┆ ---          │
│ datetime[ms]        ┆ f64            ┆ f64            ┆ f64             ┆ f64           ┆ f64          ┆ f64          │
╞═════════════════════╪════════════════╪════════════════╪═════════════════╪═══════════════╪══════════════╪══════════════╡
│ 2023-05-04 23:08:00 ┆ 28819.07       ┆ 28824.98       ┆ 28814.75        ┆ 28808.52      ┆ 37.849332    ┆ 37.849332    │
│ 2023-05-04 23:11:00 ┆ 28814.76       ┆ 28826.61       ┆ 28824.02        ┆ 28814.75      ┆ 85.682698    ┆ 61.766015    │
│ 2023-05-04 23:14:00 ┆ 28824.02       ┆ 28846.17       ┆ 28840.64        ┆ 28816.69      ┆ 85.312085    ┆ 69.614705    │
│ 2023-05-04 23:17:00 ┆ 28840.65       ┆ 28840.65       ┆ 28834.75        ┆ 28834.74      ┆ 69.667995    ┆ 69.628027    │
```
As you can see, no resampling has been done.

So, after several hours of trying to make this budge, I've collected myself in my poor skills and decided to ask for help, specially because I consider that the error that's being thrown is not accurate. 
A few questions emerged (**please, anybody feel free to enlight me in my ignorance, any insights will be severely appreciated**):

1. What's the difference between `upsample` and `upsample_stable` `DataFrame` methods? The official Rust [documentation](https://docs.rs/polars/latest/polars/prelude/trait.PolarsUpsample.html) doesn't make a very clear distinction between them;
2. What method does the Python version uses under the hood, when running `DataFrame`s `upsample` method? Does it use `upsample`, `upsample_stable`, or it proceeds to convert the `DataFrame` into a `LazyFrame` and then run `groupby_dynamic`?
3. What exactly does `DynamicGroupOptions`'s `truncate` field does? And what the `by` parameter does?
4. If `groupby_dynamic` method can yield an `PolarsError`, shouldn't its `fn` signature consider to be a `Result` instead?

Could anybody, please, provide a helping hand here? Is there anything too evident I've being oblivious to? If not, and there is a bug, as I suspect, please let me know, so I can gladly put this repository here. So that you can reproduce the error. It will be easy since Binance API doesn't require any authentication for querying market data nor connecting to `websockets`. I'd be more than happy in contributing with this great library (aside my poor Rust skills).

### Expected behavior

My expected behavior is to have the `DataFrame` resampled back from a `3-minute-basis` back to a `1-minute-basis`, with the resampled (before missing) fields filled by `FillNullStrategy::Forward` strategy, either by using `groupby_dynamic` or `upsample` / `upsample_stable`

Thanks in advance for your time and interest on this matter.

### Installed versions

<details>

`rustc --version:`
rustc 1.68.2 (9eb3afe9e 2023-03-27)

From `Cargo.toml`:
```
polars = { version = "0.28.0", features = [
    "lazy",
    "dtype-datetime",
    "diagonal_concat",
    "dynamic_groupby",
    "temporal",
    "rolling_window",
] }

```
</details>

**Comment by vitordhers** [comment]
Folks, good news first - I was able to reach the desired behavior using `upsample` method. What was wrong was that I was passing ["start_time"] in `by` parameter. After trying to reproduce what I had done in Python, I've noticed that that field was missing there (thanks, named variables), also, I've checked Polars code and noticed that when running `upsample_impl`, the second match arm checks if by is empty, so that it can run `upsample_single_impl` that does the _de facto_ upsampling (it's not clear for me though why the third arm condition `apply` `closure` won't do the job as I intended).

I've also understood that the difference between `upsample` and `upsample_stable`  comes  to maintaining the order order of `DataFrame`. If this understanding is correct, please let me know so I can gladly provide a PR updating the documentation comment on [PolarsUpsample](https://docs.rs/polars/latest/polars/prelude/trait.PolarsUpsample.html), following the same pattern found in [LazyFrame.groupby_stable](https://docs.rs/polars/latest/polars/prelude/struct.LazyFrame.html#method.groupby_stable), stating clearer their difference.

Now, even though my goal was achieved, I still would like to better understand why I got that error on `groupby_dynamic`, and, if possible, contribute more with this awesome library.
Thanks again!

**Comment by stinodego** [comment]
I think it was just an issue with your query - see #9565. If not, please open a new issue with a reproducible example.
