### ISSUE TITLE
Series.round() got incorrect results on some f32 values

### ISSUE THREAD

**Issue by thinkphoebe** [pola-rs/polars#8699]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Series.round() got incorrect results on some f32 values，it works well for f64 values

### Reproducible example

```python
import polars as pl
pl.Series("a", [100.23999]).cast('f32').round(2)

shape: (1,)
Series: 'a' [f32]
[
	100.239998
]
```

### Expected behavior

shape: (1,)
Series: 'a' [f64]
[
	100.24
]

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
Python:      3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.21.4
pandas:      1.3.4
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.5.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by Walnut356** [comment]
Looking at the source code for the Series [round function](https://github.com/pola-rs/polars/blob/ca96327d4b1b59ba2f8f0c05cf9fd70940b2dc58/polars/polars-core/src/series/ops/round.rs#L8), it casts f32's to f64's for extra precision before running the calculation. In effect, your code casts an f64 to an f32, which gets casted back to an f64, then back again to an f32. My first guess is that the inaccuracy is coming from losing precision on the extra typecast. Are the results as expected if you reverse the order of the function calls (e.g. `pl.Series("a", [100.23999]).round(2).cast('f32')`)?

**Comment by mcrumiller** [comment]
This should have a path for immediate round when decimals = 0 without the cast to `f64`.

**Comment by thinkphoebe** [comment]
At first I occure this problem, the Series was come from other source which data are already f32, the cast in my example is just to demo the problem, I think this problem is not caused by cast.

Some more example with strange results:

```
In [70]: pl.Series("a", [449.23999, 449.220001, 449.179993, 449.160004, 449.119995, 449.100006, 449.179993, 449.140015]).cast('f32').round(1)
Out[70]: 
shape: (8,)
Series: 'a' [f32]
[
	449.200012
	449.200012
	449.200012
	449.200012
	449.100006
	449.100006
	449.200012
	449.100006
]


In [76]: pl.Series("a", [100.23999, 100.220001, 100.179993, 100.160004, 100.119995, 100.100006, 100.179993, 100.140015]).cast('f32').round(1)
Out[76]: 
shape: (8,)
Series: 'a' [f32]
[
	100.199997
	100.199997
	100.199997
	100.199997
	100.099998
	100.099998
	100.199997
	100.099998
]
```

**Comment by thinkphoebe** [comment]
@Walnut356 Cast after round can not achieve the purpose of round, the result keeps more decimals than expect.  In real use, my Series data is come from other source which is already f32, it also have the problem, and can not be resolved by add additional cast to f32.

```
In [82]: pl.Series("a", [100.23999]).round(2).cast('f32')
Out[82]: 
shape: (1,)
Series: 'a' [f32]
[
	100.239998
]
```

**Comment by Walnut356** [comment]
This is probably because 32 bit floating point values cannot exactly represent the number 100.24. Based on a quick online check, closest they can get is 100.23999786376953125 or 100.2400054931640625 (in hexadecimal: 0x42c87ae1 or  0x42c87ae2). The first value is ever so slightly closer to 100.24 so it ends up using that one. I think the output string applies some of its own rounding, but at the end of the day the value that's actually being stored is 0x42c87ae1.

Rounding a float can't force it to have more precision than it already has, so the only real fix is to use a float with greater precision (f64) or an alternate datatype that's built to handle exact decimal values.

**Comment by ritchie46** [comment]
fixed by https://github.com/pola-rs/polars/issues/8705

**Comment by mcrumiller** [comment]
Hey @ritchie46 that PR actually doesn't affect this issue, as it only applies when `decimal` is 0.

Regardless, this should be closed anyway: OP wants an impossible value (needs to learn about binary representation and precision).
