### ISSUE TITLE
In `df.join(other,...)` cast other to appropriate frame type instead of raising TypeError (Python)

### ISSUE THREAD

**Issue by StefanBRas** [pola-rs/polars#8700]
### Problem description

Right now a TypeError will be raised if you try to join two dataframes that are a mix of lazy/eager.

I think you'd almost always want to just cast them to lazy and then do the join.

```python
ldf = pl.LazyFrame({'x': [1,2,3]})
df = ldf.collect()

ldf.join(df, on='x') # TypeError: Expected 'other' join table to be a LazyFrame, not a DataFrame

df.join(ldf, on='x') # TypeError: Expected 'other' join table to be a DataFrame, not a LazyFrame

```

I can make the PR if you agree 😊

**Comment by mcrumiller** [comment]
I disagree on the first one: I don't want my dataframes to be quietly casted to lazy without me knowing. You can just add a `.lazy()` to the joining frame.

I'm less opposed to a case where `eager.join(lazy)` auto-collects the lazy first, but again, it's not hard for the user.

**Comment by StefanBRas** [comment]
> I disagree on the first one: I don't want my dataframes to be quietly casted to lazy without me knowing. You can just add a `.lazy()` to the joining frame.
> 
> I'm less opposed to a case where `eager.join(lazy)` auto-collects the lazy first, but again, it's not hard for the user.

I'm not sure why that would be a problem? I think it's pretty common for polars to internally cast eager frames to lazy. ` eager.df` will for example cast to lazy and then collect before returning.

**Comment by alexander-beedie** [comment]
Amusingly my sentiment here is exactly opposite @mcrumiller 😅 The reason being, you _never_ want to collect somebody's LazyFrame without them having explicitly opted-in to it, as that LazyFrame could be representing a phenomenally expensive series of operations. However, making a LazyFrame out of a DataFrame carries essentially zero cost (it doesn't change the input DataFrame, and doesn't copy any data).

Nevertheless, we are currently raising the error in this case because we want the caller to indicate that they know what they're doing, and are not _accidentally_ mixing lazy/eager modes...

**Comment by mcrumiller** [comment]
@alexander-beedie that makes sense. I was opposed to a secret-lazy because lazy frames can't be used, so having polars quietly make my dataframe *unusable* is bad in my opinion. On the other hand, having polars unexpected do a phenomenally expensive series of operations is also bad.

**Comment by alexander-beedie** [comment]
> @alexander-beedie that makes sense. I was opposed to a secret-lazy because lazy frames can't be used, so having polars quietly make my dataframe _unusable_ is bad in my opinion. On the other hand, having polars unexpected do a phenomenally expensive series of operations is also bad.

I think I'm missing something here; your input DataFrame would remain untouched - making it lazy doesn't mutate it in place, if that's what you were concerned about?

**Comment by mcrumiller** [comment]
I was thinking more along the lines of:

```python
df = pl.DataFrame(...)
df = df.join(get_table_from_other_source())
df.to_csv(...)
```
or something--basically, something turns my `df` into a LazyFrame without telling me, and I need to do a collect but I don't expect to have to.

**Comment by StefanBRas** [comment]
> @StefanBRas: We are raising the error in this case because we want the caller to indicate that they know what they're doing, and are not accidentally mixing lazy/eager modes. There aren't _that_ many places in the API where lazy/eager modes collide, so it's not a significant burden to be explicit, and it may save you from unexpected issues elsewhere.
> 
> I could _almost_ be persuaded for `ldf.join(df, on='x')`, but the other way around would be a hard "no", due to the possibility of triggering large amounts of unexpected compute (and then eating a performance penalty without necessarily realising).
> 
> However, if we allowed it one way round but not the other (and didn't also then extend the concept to other methods like `concat`, where it can be more ambiguous as to what the "expected" thing to do is), we would have an inconsistent API.
> 
> So, I can see the initial appeal here, but I don't think the end result would be clean. (But thanks for offering to make a PR ;)

@alexander-beedie: I see what you mean and that it's maybe not worth it, but (bikesheding incoming) I think `df.join` is much different from `pl.concat` because it's a method on the class and I would always expect `Frame` class methods to operate in the same mode as the class. 

If you have an eager frame and want to join with another frame, you expect it to be done in eager mode. The frame you're joining with could accidently be a large lazy query, but it could also just be an unexpectedly big eager frame. If it then is a large lazy query, you probably still want to do the join so in these cases you want to collect it. The only real issue is if collecting the lazy frame for an eager join makes the user collect he lazy frame twice, but that's an problem everywhere lazy frames are used and not just when combining eager and lazy frames.

But I understand the counter arguments and I'm okay with closing this unless someone else are in favour. 😊

> I was thinking more along the lines of:
> 
> ```python
> df = pl.DataFrame(...)
> df = df.join(get_table_from_other_source())
> df.to_csv(...)
> ```
> 
> or something--basically, something turns my `df` into a LazyFrame without telling me, and I need to do a collect but I don't expect to have to.

@mcrumiller Maybe I'm missing something here, but in my proposal the class of the "left" frame of the join would always be class of the output frame.

It would basically just turn `lazy.join(eager)` to `lazy.join(eager.lazy())` and `eager.join(lazy)` to `eager.lazy().join(lazy).collect()`

**Comment by alexander-beedie** [comment]
> But I understand the counter arguments and I'm okay with closing this unless someone else are in favour. 😊

Thanks; I think we should keep it strict for now, as it ensures that everything is more predictable for the caller ;)

**Comment by StefanBRas** [comment]
I'm closing this BUT! Let it be known that I still think it's a good idea and if it's ever changed I will go back and change this from "closed as not planned" to "closed as completed" 😎
