### ISSUE TITLE
HAVING clause not working as expected

### ISSUE THREAD

**Issue by csubhodeep** [pola-rs/polars#8702]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The `HAVING` clause of SQL is not giving expected results. Ideally it should help filter the rows _after_ calculating the value of the aggregating function on each group.

### Reproducible example

```python
import polars as pl

df_test = pl.DataFrame(
    {
        "group": ['a', 'b', 'c', 'c', 'b'],
        "attr": ['x', 'y', 'x', 'y', 'y']
    }
)

sql_ctx = pl.SQLContext()
sql_ctx.register("test", df_test.lazy())
result = sql_ctx.execute("""
SELECT
    group,
    COUNT(DISTINCT attr) AS n_dist_attr
FROM test
GROUP BY group
HAVING n_dist_attr > 1
""")
print(result.collect())

# Output
shape: (3, 2)
┌───────┬─────────────┐
│ group ┆ n_dist_attr │
│ ---   ┆ ---         │
│ str   ┆ u32         │
╞═══════╪═════════════╡
│ a     ┆ 1           │
│ b     ┆ 1           │
│ c     ┆ 2           │
└───────┴─────────────┘
```

### Expected behavior

Ideally it should only give one row as output

```shell
shape: (1, 2)
┌───────┬─────────────┐
│ group ┆ n_dist_attr │
│ ---   ┆ ---         │
│ str   ┆ u32         │
╞═══════╪═════════════╡
│ c     ┆ 2           │
└───────┴─────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.3.1-x86_64-i386-64bit
Python:      3.9.15 (main, Apr 14 2023, 14:20:58) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Turns out we haven't actually implemented support for `HAVING` yet, so it's currently ignored - I'm adding it now...😅

**Comment by csubhodeep** [comment]
Not sure whether this is the right thread to bring this up but would be really nice to have the following:
1. A quick query validation when the `execute` method is called. Currently that doesn't happen and it seems that query validation only happens with the `query` method.
2. A reference to the SQL dialect in the documentation expected by Polars as it throws an error if one tries to use certain common clauses like `USING` in the `JOIN` conditions or table name aliasing which are otherwise readily interpreted by other similar packages that also work with SQL such as `pyspark`, `duckdb` etc.

Thanks ! 😄
