### ISSUE TITLE
STD (of sample, not population) of one number equal to -1

### ISSUE THREAD

**Issue by morbitt** [pola-rs/polars#8718]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The function that calculates STD returns 0 when given only one number, and should return ״nan״ (since std must accept at least two numbers)

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1], "b": [4]})
df["a"].std()
```

### Expected behavior

Should return ״nan״

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.10.130-x86_64-with-glibc2.27
Python:      3.9.11 (main, Oct 19 2022, 08:58:27) 
[GCC 7.5.0]

----Optional dependencies----
numpy:       1.22.3
pandas:      1.4.2
pyarrow:     6.0.0
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      2022.3.0
matplotlib:  3.5.2
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
We follow numpy here:

```python
>>> import numpy as np
>>> np.std([1])
0.0
```

**Comment by morbitt** [comment]
This is a population std. How can I calculate sample std (like Pandas)?

**Comment by MarcoGorelli** [comment]
wouldn't numpy also give `nan` with ddof=1 (the polars default)?
```python
In [28]: np.std([1], ddof=1)
/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Out[28]: nan
```

**Comment by MarcoGorelli** [comment]
thanks for the report, solved by #8730 (I put the wrong issue number in the PR description)

**Comment by morbitt** [comment]
df = pl.DataFrame({"a": [1], "b": [4]})
df["a"].std(ddof=1)

Still returns 0. Why?

**Comment by ritchie46** [comment]
> df = pl.DataFrame({"a": [1], "b": [4]}) df["a"].std(ddof=1)
> 
> Still returns 0. Why?

Did you compile from source?

**Comment by morbitt** [comment]
![image](https://user-images.githubusercontent.com/85172734/236760949-6c0ac135-ed0c-4a28-82a7-8f6bc02742e0.png)

So, NumPy is now correct, but Polars still returns 0.

**Comment by ritchie46** [comment]
Did you compile from source on latest main?

**Comment by morbitt** [comment]
What does that mean?
I uninstalled and reinstalled the latest version of polars. Do I need to do anything else?

**Comment by morbitt** [comment]
What do I need to do to use it now?

**Comment by ritchie46** [comment]
https://github.com/pola-rs/polars#python-compile-polars-from-source
