### ISSUE TITLE
Division operation not working as expected in the `SQLContext`

### ISSUE THREAD

**Issue by csubhodeep** [pola-rs/polars#8723]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The division operator with integers is not returning correct results inside the `SQLContext`. In the below example the `attr` column is by default cast to `i64` data type which is logical. However, it's not intuitive why the division operation forcefully rounds down and downcasts the results (in the `prob` & `prob2` column) to `i64`.

While if we change our constant divisor to **3.0** (instead of **3**) we get the expected output.

Also if we change one of the values in the `attr` column, let's say **1** to **1.0** then we get the expected output. But in that case the column is cast to `f64` (also logical). So the problem seems to be only with integers.

### Reproducible example

```python
df_test = pl.DataFrame(
    {
        "attr": [1,2]
    }
)

sql_ctx = pl.SQLContext()
sql_ctx.register("test", df_test.lazy())
result = sql_ctx.execute("""
SELECT
    attr,
    3 / attr AS prob,
    attr / 3 AS prob2
FROM test
""")

# Output
shape: (2, 3)
┌──────┬──────┬───────┐
│ attr ┆ prob ┆ prob2 │
│ ---  ┆ ---  ┆ ---   │
│ i64  ┆ i64  ┆ i64   │
╞══════╪══════╪═══════╡
│ 1    ┆ 3    ┆ 0     │
│ 2    ┆ 1    ┆ 0     │
└──────┴──────┴───────┘
```

### Expected behavior

```shell
shape: (2, 3)
┌──────┬──────┬──────────┐
│ attr ┆ prob ┆ prob2    │
│ ---  ┆ ---  ┆ ---      │
│ i64  ┆ f64  ┆ f64      │
╞══════╪══════╪══════════╡
│ 1    ┆ 3.0  ┆ 0.333333 │
│ 2    ┆ 1.5  ┆ 0.666667 │
└──────┴──────┴──────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.3.1-x86_64-i386-64bit
Python:      3.9.15 (main, Apr 14 2023, 14:20:58) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
This looks correct to me - SQL (typically) obeys integer division rules if both the numerator and divisor are themselves integers, which leaves you with just the quotient - the remainder is dropped; your results above are consistent with this. (I think Oracle is an outlier here, as it will return a float in this case; a handful of other databases might do the same).

(Note that if you try `df_test // 3` you'll get the same `0` results in polars).

**Comment by csubhodeep** [comment]
I see thanks a lot for the clarification ! :)
