### ISSUE TITLE
extend method behavior error

### ISSUE THREAD

**Issue by ColorFuzzy** [pola-rs/polars#8745]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

extend value error: expect [1, 2, 8], actual [1, 2, 3, 8]

### Reproducible example

```python
import polars as pl

df = pl.DataFrame([{"age": 1}, {"age": 2}, {"age": 3}])
df = df[:-1]  # ok: expect [1, 2]
print(df)
tail = pl.DataFrame([{"age": 8}])
df = df.extend(tail) # failed: expect [1, 2, 8], actual [1, 2, 3, 8]
print(df)
```

### Expected behavior

expect [1, 2, 8], actual [1, 2, 3, 8]

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.11.2 (main, Mar 27 2023, 18:38:21) [Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by uchiiii** [comment]
I feel the current output is expected because you overwrote `df` here `df = df[:-1]  # ok: expect [1, 2]`. If you remove this line, you would get what you expected.

**Comment by ColorFuzzy** [comment]
> 

I want to remove the last number `3`, but after I remove it from variable `df` with `df = df[:-1]`, the number `3` magically appears after I `extend` the newly created variable `df`.
