### ISSUE TITLE
`DISTINCT` clause does not work as expected in `SQLContext`

### ISSUE THREAD

**Issue by csubhodeep** [pola-rs/polars#8746]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I see that the `DISTINCT` clause does not have any effect in the below query snippet. Ideally the output should be similar to the [`unique`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.unique.html#polars-dataframe-unique) method.

It would be really nice if its supported in the next release. Thanks ! :)

### Reproducible example

```python
import polars as pl

test_df = pl.DataFrame({"a": [1,1,2]})
sql_ctx = pl.SQLContext()
sql_ctx.register("test", test_df.lazy())
sql_ctx.query("SELECT DISTINCT a FROM test")

# Output
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
│ 2   │
└─────┘
```

### Expected behavior

```shell
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.3.1-x86_64-i386-64bit
Python:      3.9.15 (main, Apr 14 2023, 14:20:58) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
I fixed this last night; will be available in the upcoming `0.17.13` ;)
(See https://github.com/pola-rs/polars/pull/8740 for details).
