### ISSUE TITLE
Arithmetic bug related to integer casting in `py-0.17.12`

### ISSUE THREAD

**Issue by NikolayXHD** [pola-rs/polars#8752]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Since version `py-0.17.12` arithmetic expression involving integer and floating point produces unexpected result. In `py-0.17.11` example below works as expected, assertion passes.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'x': pl.Series(values=[0, 0])})
df2 = df.with_columns((0 + 2.5 * (0.5 + pl.col('x'))).alias('compute'))
v_compute = df2[:, 'compute'].to_series()[0]
assert v_compute == 1.25, v_compute
```

### Actual behavior

v_compute == 1.0, assertion fails

### Expected behavior

assertion passes

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-6.2.10-arch1-1-x86_64-with-glibc2.37
Python:      3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by NikolayXHD** [comment]
If I update code so that 'x' contains 1 value instead of 2, code fails with Rust panic.

```python
import polars as pl

df = pl.DataFrame({'x': pl.Series(values=[0])})  # <- 1 value [0] instead of 2 [0, 0]
df2 = df.with_columns((0 + 2.5 * (0.5 + pl.col('x'))).alias('compute'))
v_compute = df2[:, 'compute'].to_series()[0]
assert v_compute == 1.25
```
result:
```
thread '<unnamed>' panicked at 'implementation error, cannot get ref Int64 from Float64', /home/conda/feedstock_root/build_artifacts/polars_1683321510212/work/local_dependencies/polars-core/src/series/mod.rs:1023:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ritchie46** [comment]
Thanks for the report. Will take a look. Could you open a seperate issue for the second one?

**Comment by ritchie46** [comment]
Nevermind on the second issue. Was both the same underlying bug.
