### ISSUE TITLE
Add `keys` and `names` arguments and accept dict inputs to `pl.concat`

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8753]
### Problem description

A common pattern is concatenating a sequence of dataframes with keys and adding the keys as columns (undoing `partition_by` essentially). For example, if keyed by `id` and `date`, I would currently do

```python
pl.concat(
    [
        df1.with_columns(id=pl.lit("a"), date=pl.lit(date(2023, 1, 1))),
        df2.with_columns(id=pl.lit("b"), date=pl.lit(date(2023, 1, 2))),
    ]
)
```

In pandas `pd.concat` has `keys`/`names` arguments for this, which would be nice to have in polars as well. Then I could just write something like
```python
pl.concat([df1, df2], names=["id", "date"], keys=[("a", date(2023, 1, 1)), ("b", date(2023, 1, 2))])
```

Another ergonomic improvement would be to support keyed dicts like in pandas:

```python
pl.concat({("a", date(2023, 1, 1)): df1, ("b", date(2023, 1, 2)): df2}, names=["id", "date"])
```

**Comment by mcrumiller** [comment]
I like the names and keys, but dislike the keyed dict approach, as this starts creeping into pandas' "too many ways to do the same thing" problem.

**Comment by mcrumiller** [comment]
I might also prefer a single argument as a dictionary, of the form:

```python
{
    "column_1": [value1, value2, value3, ...],
    "column_2": [value1, value2, value3, ...]
}
```
Where dict keys are the new column names, and the the values are the keys for each column.

**Comment by mcrumiller** [comment]
Can we get some more input from others on what the desired syntax for this should be, and if we want to include it? Right now, we have the following three proposed syntaxes:

### 1. List of dfs, separate keys dict, and names array

```python
out = pl.concat(
    dfs,
    names=["key_a", "key_b"],   # column names
    keys = [
        ("df1a", "df2b"),       # values used for rows from df 1
        ("df2a", "df2b"),       # values used for rows from df2
        ...
    ]
)
```

### 2. Keyed dictionary containing the dfs and a names array

```python
out = pl.concat(
    keyed_dict = {
        ("df1a", "df2b"): df1,  # values used for rows from df1, keyed by df1
        ("df2a", "df2b"): df2,  # values used for rows from df1, keyed by df1
        ...,
    },
    names = ["key_a", "key_b"]  # column names
)
```

### 3. List of ds, names/keys dict

```python
out = pl.concat(
    dfs,
    keys = {
        "key_a": ["df1a", "df2a", ...],  # first key name and values used for each df
        "key_b": ["df1b", "df2b", ...],  # second key name and values used for each df
    }
)
```

**Comment by stinodego** [comment]
I don't think it makes sense to add this functionality to `concat`. You're just looking to add similar columns to multiple dataframes at the same time. That has nothing to do with the core idea of concatenating dataframes.

I actually think the initial example using `with_columns` is more clear than the others. If you don't like writing `with_columns` so many times, you can use a list comprehension like so:

```python
dfs = [df1, df2, ...]
dfs = [df.with_columns(date=d + timedelta(days=i)) for i, df in enumerate(dfs)]
```

It might even be worth to add some function that specifically does this nicely. But as I said, it should not be part of `concat`.

**Comment by mcrumiller** [comment]
@stinodego I think of it more as "concatenate dataframes, and identify which rows came from which dataframe." This is a very useful feature that I use quite often.

I'm happy to add this as as separate functionality. One option might be `tag_frames` (or something along those lines) where one would do:

```python
dfs = tag_frames(dfs, keys = {key1: [value1, value2, ...], key2: [value1, value2, ...]})
```

...although I do think this is a nice feature in the concatenation function.

**Comment by stinodego** [comment]
If that's the goal, then it makes sense to add an `add_id_column` flag that adds an unsigned int `id` column. But that's really easy to do with a list comprehension as I showed, so I'm not too sure about the added value.

**Comment by mcrumiller** [comment]
@stinodego sure, I'm coming around to the other side a bit.

@erinov1 it looks like there probably isn't enough interest in this feature, unfortunately, if you want to close as unplanned. For now, I'd recommend making a utility tool to do this.

**Comment by erinov1** [comment]
Thanks for the comments everyone!

**Comment by stinodego** [comment]
I'll close this as unplanned for now. Though I can see me changing my mind on this sometime in the future.
