### ISSUE TITLE
Implicit cast from `bool` to `int` is not performed anymore for `pl.sum()`

### ISSUE THREAD

**Issue by DrMaphuse** [pola-rs/polars#8759]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As the title says - horizontal sums of boolean columns using `pl.sum()` do not work in 0.17.11.

Related to #8489, but even the examples that are marked as working there do not work as of now.

### Reproducible example

```python
import polars as pl

pl.DataFrame(
    {"a": [True], "b": [False]},
).select(pl.sum(pl.col(["a", "b"])))

> PanicException: `add` operation not supported for dtype `bool`
```

### Expected behavior

I expect an implicit cast from `bool` to `int` dtype.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.35
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
---Optional dependencies---
numpy: 1.23.2
pandas: 1.5.2
pyarrow: 9.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: 3.6.3
xlsx2csv: 0.8
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Did we support this?

**Comment by mcrumiller** [comment]
I fully support doing this. It's pretty comment for counting items, for example:

```python
(df['field'] == 0).sum()
```

Having to pepper in casts every time this happened would be quite a nuisance. Or we could implement `nnzero` in its place, which can probably be faster, no?
