### ISSUE TITLE
`df.update` adds `__POLARS_ROW_COUNT` column

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#8761]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When `df` and `other` in `df.update(other)` do not have any matching column names, `__POLARS_ROW_COUNT` appears in the output.

(I accidentally passed the wrong thing to `.update`)

### Reproducible example

```python
import polars as pl

a = pl.DataFrame({"a": [1, 2, 3]})
b = pl.DataFrame({"b": [4, 5, 6]})

a.update(b)

# shape: (3, 2)
# ┌────────────────────┬─────┐
# │ __POLARS_ROW_COUNT ┆ a   │
# │ ---                ┆ --- │
# │ u32                ┆ i64 │
# ╞════════════════════╪═════╡
# │ 0                  ┆ 1   │
# │ 1                  ┆ 2   │
# │ 2                  ┆ 3   │
# └────────────────────┴─────┘
```

### Expected behavior

`__POLARS_ROW_COUNT` should not be added.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Python:      3.10.9 (main, Jan 14 2023, 16:56:26)

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.0
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.8.2
matplotlib:  3.5.1
xlsx2csv:    0.8
xlsxwriter:  3.0.8
```

</details>

**Comment by mcrumiller** [comment]
I see the issue, we have an early return that precedes the drop.
