### ISSUE TITLE
Add support for sparse Series

### ISSUE THREAD

**Issue by david-256** [pola-rs/polars#8777]
**What**

I want a `Series`, which values are mostly zero, to require less main memory. 

<br />

**Why**

Most columns of the dataset for my machine learning project are categorical (e.g.: customer id for an order).

I turn each of these categorical columns into many columns using one-hot-encoding (via the `to_dummies` method).

This causes the DataFrame to be much bigger than it should be.

<br />

**Example API**

This
```py
data.to_dummies(columns=categorical_columns, sparse=True)
```
should create a `DataFrame` with a sparse `Series` for each distinct value in `categorical_columns`.

---

**Similar implementations**

Pandas supports [sparse data structures](https://pandas.pydata.org/docs/user_guide/sparse.html).

The above example is inspired from the Pandas [get_dummies](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html?highlight=get_dummies#pandas.get_dummies) method.

**Comment by lucazanna** [comment]
A comment on this: considering Polars and Arrow efficient processing of null values, would replacing zeros with nulls bring a reduction in dataset size ?

In that case, the `sparse = True` for `.to_dummies` could write nulls instead of zeroes

**Comment by lucazanna** [comment]
> @lucazanna see #8555. To quote @ritchie46:
> 
> > As `to_dummies` will almost always be used in a machine learning algorithm which cannot deal with bitpacked data, this would lead to a redundant copy. Whereas `uint8` matches the binary representation of all numerical libraries.

got it. I had missed that one. Thanks for sharing @mcrumiller.

I looked up Arrow support for Sparse tensors and only the C++ implementation seems to have it, and it's experimental for now https://arrow.apache.org/docs/cpp/api/tensor.html

**Comment by michelkluger** [comment]
> Yes, a lot of added complexity and bloat. All operations would need be added for this specific array and all numeric datatypes.
> 
> Polars is not a tensor library, nor does it aim to be.

any way to operate like in pandas?
https://pandas.pydata.org/docs/user_guide/sparse.html

for us there is value in having numpy like data, but having the Metadata in indexes and columns, 
can we adopt polars, and if yes, how?
