### ISSUE TITLE
.groupby_rolling bug with .sum() and potentially more functions

### ISSUE THREAD

**Issue by supermarin** [pola-rs/polars#8784]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using .sum() inside a .groupby_rolling().agg() function with more elements than the rolling window produces wrong values.
Below is a well commented out, fully runnable example that implements `rsq()` function by folowing [this video](https://www.youtube.com/watch?v=LfDxpwmon8U) verbatim, including input and output values.

**Test Data:**
df and df2.tail(20) are identical.

**Summary:**
- using .rsq() on a dataset with exactly 20 values works OK
- using .rsq() inside of a .groupby_rolling.agg() with exactly 20 values works OK
- using the new builtin .rolling_corr(20).pow(2) works OK
- using .groupby_rolling().agg() with **more than 20 values and rolling_window=20** reproduces the bug
- rsq_with_hack() works inside .groupby_rolling(). It "fixes the problem" using .rolling_sum(20).last() instead of .sum(), demonstrating that x and y values are correct in the groupby_rolling example.

I've tested all values by hand, and `xDemMinusYDem.sum()` is the first line that produces an incorrect value. Previous computations including .mean() and multiplications between two pl.Expr are correct and correspond to the table linked in the video.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "exam": [41, 60, 37, 51, 52, 39, 40, 50, 41, 45, 40, 56, 40, 47, 35, 47, 47, 58, 57, 52,],
    "gpa": [3.94, 2.78, 2.09, 3.1, 3.17, 1.72, 3.04, 3.3, 3.15, 3.06, 2.88, 2.93, 2.52, 2.64, 1.88, 3.17, 3.02, 3.28, 3.24, 3.19,],
})

df2 = pl.DataFrame({
    "exam": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 30, 30, 30, 41, 60, 37, 51, 52, 39, 40, 50, 41, 45, 40, 56, 40, 47, 35, 47, 47, 58, 57, 52,],
    "gpa": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 30, 30, 30, 3.94, 2.78, 2.09, 3.1, 3.17, 1.72, 3.04, 3.3, 3.15, 3.06, 2.88, 2.93, 2.52, 2.64, 1.88, 3.17, 3.02, 3.28, 3.24, 3.19,],
})


def rsq(self, x: pl.Expr) -> pl.Expr:
    meanX = x.mean()
    meanY = self.mean()
    xMinusMeanX = x - meanX
    yMinusMeanY = self - meanY
    xDemMinusYDem = (xMinusMeanX * yMinusMeanY)
    numerator = xDemMinusYDem.sum()  # BUG on this line (see below)
    xMinusMeanXSquared = xMinusMeanX.pow(2)
    yMinusMeanYSquared = yMinusMeanY.pow(2)
    denominator = (xMinusMeanXSquared.sum() * yMinusMeanYSquared.sum()).sqrt()
    r = numerator / denominator
    return r.pow(2)


def rsq_with_hack(self, x: pl.Expr) -> pl.Expr:
    meanX = x.mean()  # OK
    meanY = self.mean()  # OK
    xMinusMeanX = x - meanX  # OK
    yMinusMeanY = self - meanY  # OK
    xDemMinusYDem = (xMinusMeanX * yMinusMeanY)  # OK
    # BUG: using .sum() after vector multiplication
    # Expected: 34.655
    # .sum(): 92.0
    # .rolling_sum(20).last(): 34.655
    # The only difference between this function and the one above is that
    # this one forces a .rolling_sum(20) instead of using .sum()
    numerator = xDemMinusYDem.rolling_sum(20).last()
    xMinusMeanXSquared = xMinusMeanX.pow(2)
    yMinusMeanYSquared = yMinusMeanY.pow(2)
    denominator = (xMinusMeanXSquared.sum() * yMinusMeanYSquared.sum()).sqrt()
    r = numerator / denominator
    return r.pow(2)


# Different variant of the function that uses no self
def rsq2(x: pl.Expr, y: pl.Expr) -> pl.Expr:
    meanX = x.mean()
    meanY = y.mean()
    xMinusMeanX = x - meanX
    yMinusMeanY = y - meanY
    xDemMinusYDem = (xMinusMeanX * yMinusMeanY)
    numerator = xDemMinusYDem.sum()  # BUG on this line (see below)
    xMinusMeanXSquared = xMinusMeanX.pow(2)
    yMinusMeanYSquared = yMinusMeanY.pow(2)
    denominator = (xMinusMeanXSquared.sum() * yMinusMeanYSquared.sum()).sqrt()
    r = numerator / denominator
    return r.pow(2)


pl.Expr.rsq = rsq
pl.Expr.rsq_with_hack = rsq_with_hack

print("First, a couple of correctly working examples:")
print("Running the function without groupby_rolling on exactly 20 elements:")
print(
    df.with_columns(
        pl.col('gpa').rsq(pl.col('exam')).alias('rsq'),
    )
)
print("Running the function with groupby_rolling on exactly 20 elements:")
print(
    df
    .with_row_count()
    .with_columns(pl.col('row_nr').cast(pl.Int32))
    .groupby_rolling(
        index_column='row_nr',
        period='20i',
    )
    .agg(
        pl.col('gpa').rsq(pl.col('exam')).alias('rsq'),
    )
)

print("A rolling implementation using pl.rolling_corr")
print(
    df.with_columns(
        pl.col('gpa').rsq(pl.col('exam')).alias('rsq'),
        pl.rolling_corr('gpa', 'exam', window_size=20).pow(
            2).alias('rsq-rollingcorr'),
    )
)

print("BUG: rolling implementation using groupby_rolling and more than 20 elements:")
print(
    df2
    .with_row_count()
    .with_columns(pl.col('row_nr').cast(pl.Int32))
    .groupby_rolling(
        index_column='row_nr',
        period='20i',
    )
    .agg(
        pl.col('gpa').alias('gpa'),  # proves the correct values are rolling
        pl.col('gpa').len().alias('gpalen'),  # proves there's 20 values
        pl.col('exam').alias('exam'),  # proves the correct values are rolling
        pl.col('exam').len().alias('examlen'),  # proves there's 20 values
        pl.col('gpa').rsq(pl.col('exam')).alias('rsq(bug)'),
        rsq2(pl.col('gpa'), pl.col('exam')).alias('rsq2(bug)'),
        pl.col('gpa').rsq_with_hack(pl.col('exam')).alias('rsq(sum hack)')
    )
)
```

### Expected behavior
numerator = 34.655
rsq = 0.214293

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-6.3.1-x86_64-with-glibc2.35
Python:      3.11.2 (main, Feb  7 2023, 13:52:42) [GCC 12.2.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by supermarin** [comment]
> When you use groupby_rolling, it will return output for each window, so you would expect a different output when you the input is 20 rows vs more than 20 rows?

The last 20 rows between `df` and `df2` are identical, so one would expect that the last value of `rsq(window_size=20)` is the same between `df` and `df2.groupby_rolling` with window_size=20. Agreed?

> I think it would help if you could make a small example (i.e. max 10 lines of code, not 110+), on a small example dataframe (couple rows).

I've purposely made a larger code sample to make it easier for maintainers to isolate and drill down the issue.
You can reproduce the bug in the first 25 lines (first rsq() function) and with the last print() statement. Everything else is eliminating parameter expansion, proving that the rolling windows and data are correct (look at the .rolling_sum(20) line).

**Comment by mcrumiller** [comment]
@supermarin if you reduce your "20" to "5" or even "3" do you still get the issue? 

One of the main reasons for a minimal working example is that, when confronted with an example like yours, it's rather intimidating to look at, even if conceptually it's simple. There are multiple functions with 10 lines of code each, most of which probably have nothing to do with the error, and presumably if the error is somewhere in the `groupby` or `agg`, it'll be easier to find with a simpler window function. I'm not really a developer but I do try my best to help out with issues around here, and it's much easier to diagnose when the issue-submitters do a little bit of work themselves to narrow down exactly what the problem is. It's hard when we have to go through hundreds of lines of code. I'm not trying to dissuade you, and this is obvious a legitimate issue. I'll spend a bit more time looking at it tomorrow.

**Comment by ritchie46** [comment]
@mcrumiller is absolutely right. Luckily we hit a debug assertion and could get it quickly fixed, but otherwise I would have asked for a minimal example. 

Thanks both @mcrumiller  and @supermarin
