### ISSUE TITLE
Docs improvement - explain what addition with a null does

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#8787]
### Problem description

In the [docs for the addition operator](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L3934-L3976), it would be great if it explained what addition with "null" does.

**Comment by ritchie46** [comment]
Maybe you can open a PR suggesting what you'd like to see?

**Comment by zundertj** [comment]
Closing this on the same basis as #8806.
