### ISSUE TITLE
Docs Request: how is `df.clear(5)` different than `df.head(5)`?

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#8788]
### Problem description

[Relevant docs section](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.clear.html)

It would be super helpful to add docs that explain how `df.clear(5)` is different than `df.head(5)`. Or are they the same thing with different names?

**Comment by zundertj** [comment]
`df.clear` returns all values as `null`, `df.head` returns the actual values in `df`.

**Comment by DeflateAwning** [comment]
I think it would be awesome if an explanation of that was added to the docs, or made more clear!

**Comment by ritchie46** [comment]
Maybe you can open a PR suggesting what you'd like to see?

**Comment by alexander-beedie** [comment]
> I think it would be awesome if an explanation of that was added to the docs, or made more clear!

The docs already seem pretty clear...

> _"Create an **empty copy** of the current Series, with zero to 'n' elements // The copy has an identical name/dtype, **but no data**."_

...but if you can see a way to improve them further, then please go ahead :)

```python

def clear(self, n: int = 0) -> Series:
    """
    Create an empty copy of the current Series, with zero to 'n' elements.

    The copy has an identical name/dtype, but no data.

    Parameters
    ----------
    n
        Number of (empty) elements to return in the cleared frame.
    """
```

**Comment by stinodego** [comment]
I agree that the docs are clear enough. Feel free to open a PR if you think you can improve the wording.
