### ISSUE TITLE
write_csv keeps re-writing file

### ISSUE THREAD

**Issue by pop134** [pola-rs/polars#8789]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

My environment:
- OS: Ubuntu 16.04.
- Specs: 128GB RAM, CPU XEON E5 v3 20core 40 Thread.
- Jupyter notebook.

I'm trying to save a data frame with ~18 million rows and ~242 columns with the write_csv function and it took about 15 to 30 min to run. I also have other processes running on the machine at that time.
After I checked the file during the writing process, I observed that the file was being written/re-written continuously. For example, the file reached 30Gb in size and than it rolled back to 0 and started to do it again.
I don't know if the cause of this behavior is the environment or the package itself.
I appreciate some insights on this problem.

### Reproducible example

```python
import polars as pl

data.write_csv("polars_numerical_data.csv")  ## data with shape (18518514, 200)
```

### Expected behavior

Data only written once

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-4.15.0-142-generic-x86_64-with-glibc2.23
Python:      3.9.16 (main, Jan 11 2023, 16:05:54)
[GCC 11.2.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.6.3
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
Sounds strange to me. Can this be flawed reporting from the os?

**Comment by pop134** [comment]
I restarted the PC and everything's OK now, couldn't find the cause. So I guess this will be closed?

**Comment by ritchie46** [comment]
Yes, I don't think this is something on our side. We have this write csv for a long time unchanged now and had never seen any reports like this.
