### ISSUE TITLE
polars.concat for large number of rows [bug]

### ISSUE THREAD

**Issue by wuboyu88** [pola-rs/polars#8790]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

polars.concat doesn't return expected result for large number of rows 

### Reproducible example

```python
import polars as pl
import numpy as np

df1 = pl.DataFrame({'a': np.random.randint(1, size=3500000000)})
df = pl.concat([df1, df1])

# it returns 2705032704 instead of 7000000000
print(len(df))
```

### Expected behavior

7000000000

### Installed versions

0.16.2

**Comment by ritchie46** [comment]
https://github.com/pola-rs/polars#going-big

**Comment by wuboyu88** [comment]
> https://github.com/pola-rs/polars#going-big

Thank you， it helps.

**Comment by wuboyu88** [comment]
solved
