### ISSUE TITLE
kwarg missing from arange typing overload

### ISSUE THREAD

**Issue by edavisau** [pola-rs/polars#8791]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The function signature / overload for the lazy version of `pl.arange` is missing the `dtype` kwarg. This causes the return type to be `Expr | Series` when both `eager=False` and `dtype=....` are provided.

Current implementation shown below. Hardly a "bug", but it doesn't seem like the intended behavior in any case.

### Reproducible example

```python
@overload
def arange(
    start: int | Expr | Series,
    end: int | Expr | Series,
    step: int = ...,
    *,
    eager: Literal[False],
) -> Expr:
    ...


@overload
def arange(
    start: int | Expr | Series,
    end: int | Expr | Series,
    step: int = ...,
    *,
    eager: bool = ...,
    dtype: PolarsDataType | None = ...,
) -> Expr | Series:
    ...
```

### Expected behavior

`pl.arange(1, 10, eager=False, dtype=pl.Int8)` should give me an `Expr`, not an `Expr | Series`.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by stinodego** [comment]
Thanks for the report, I issued a fix!
