### ISSUE TITLE
Feature request: provide a better error message on common typo (uncallable expression)

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#8793]
### Problem description

Full disclosure - I made a stupid typo. Fill disclosure - I spent >20 minutes debugging my embarrassing typo. I wish the following was how Polars (Python, VS Code debugger, Windows) behaved from the start:

```python
# I wrote:

import polars as pl
df = pl.DataFrame(
    {
        "a": [1, 2],
        "b": [3, 4],
        "c": [5, 6],
    }
)
```

```
df:
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   │
│ 2   ┆ 4   ┆ 6   │
└─────┴─────┴─────┘
```

```python
df_i_wanted = df.select(
    (
        pl.col('a') + pl.col('b')
    ).alias('sum_of_a_and_b') # TODO: I need to fix this implementation later.
    (
        pl.col('a') + pl.col('b') * pl.col('c')
    ).alias('complex_output_col')
)
```

See if you can find the mistake in the previous example. 

It's obvious once you see it, but the error message involves messages that aren't immediately obvious. 

I missed a period. My second column definition was executed as a function call of the first column definition (in the select statement.

Anytime this happens, can you suggest ("maybe a comma is missing?"). This also applies to `df.with_columns(...)`.

**Comment by ritchie46** [comment]
I think you must make this suggestion to the python project. But I give you little chance as they are already pretty clear. 

```
TypeError: 'Expr' object is not callable
```

Which I read as you trying to call an expression, eg. you have calling brackets written `()` just after a type that evaluates to `Expr`.

**Comment by DeflateAwning** [comment]
Yes, that's the problem. When you're brand new to these sorts of vectorized calls though, it's easy to overlook still

**Comment by ritchie46** [comment]
Yes, but there is nothing we can do. The error originates in the python interpreter.
