### ISSUE TITLE
Polars CLI panicks when saving current state of database

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8795]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The Polars CLI panicks when I try to save the current state of the database, as mentioned in the help function.

### Reproducible example

```python
polars
Polars CLI v0.1.0
Type .help for help.
〉.help
 .exit       Exit this program                              
 .quit       Exit this program (alias for .exit)            
 .save FILE  Save the current state of the database to FILE 
 .open FILE  Open a database from FILE                      
 .help       Display this help.                             
〉CREATE TABLE orders AS SELECT * FROM read_parquet('data_clean.parquet');
┌──────────────┐
│ Response     │
│ ---          │
│ str          │
╞══════════════╡
│ Create Table │
└──────────────┘
〉.save db_polars
thread 'main' panicked at 'not yet implemented', /home/luca/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.29.0/src/datatypes/_serde.rs:90:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

### Expected behavior

I would expect the command to not result into a panick. 

Also- what does the 'current status of the database' mean? 
Is it a file with pointers to the files used as source for the tables?
Or is it an Arrow file with all of the data?

copying @universalmind303 

### Installed versions

<details>

```
N/A
```

</details>

**Comment by lucazanna** [comment]
One cool extension that could be built based on this is a right-click on file => add to Polars database => choose amongst the available Polars databases.

then querying the files directly on the CLI

**Comment by lucazanna** [comment]
thank you @universalmind303 ! is this something I can help with for debugging?

being able to save / load databases would be a useful functionality

**Comment by lucazanna** [comment]
hi @universalmind303 ,

I just checked and indeed the `write_json` fails with the data_clean.parquet file.
The problem seems to be with Categorical columns because cast them to UTF8 the save_database works, and also the write_json.
I will open a separate issue for serializing a Categorical dtype.

I also tried loading a separate file: `product_details.json`. Here is the file content:
```json
{"product_sku": "ABC123", "product_name": "Example Product 1", "price": 19.99}
{"product_sku": "DEF456", "product_name": "Example Product 2", "price": 29.99}
```
And here is the schema for `product_details.json` using `scan_ndjson`:
```
{'product_sku': Utf8, 'product_name': Utf8, 'price': Float64}
```
I get a different error for the JSON file: 
Error: Serialization error: Value("the enum variant LogicalPlan::AnonymousScan cannot be serialized")

Should I open a separate issue for this one? Or the 2 might be related?

**Comment by lucazanna** [comment]
I added both issues in 8819. I will close this ticket as the problem does not seem to be related to the Polars CLI

**Comment by universalmind303** [comment]
> Should I open a separate issue for this one? Or the 2 might be related?

this is a separate issue that involves a bit more work & design. 

there are already numerous issues around this topic. 
- #4569
- https://github.com/pola-rs/polars/issues/4557
- https://github.com/pola-rs/polars/issues/2979

But i don't think it'd hurt to create a new one for this one specific case.
