### ISSUE TITLE
groupby_rolling fails to use months for month end dates

### ISSUE THREAD

**Issue by josefinb** [pola-rs/polars#8800]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am applying groupby_rolling over an index of dates and with a period of 3 months and I get the following error:

`exceptions.ComputeError: cannot advance '2021-05-31 00:00:00' by -3 month(s). If you were trying to get the last day of each month, you may want to try .dt.month_end`

What I think is happening is that 2021-02-31 does not exist so it fails.

However, if I apply a period in terms of weeks or days, equivalent to 3 months, then it works. Or, if I remove all days >  28 (across all months), then it also works (supposedly because day 28 and below exists in all months).

Note: in the example below, I have only included month ends for simplicity -> my real dataset includes all days of all months.

### Reproducible example

```python
from datetime import date
import polars as pl


df = pl.DataFrame([
    ["a", 4.54, date(2021, 6, 30)],
    ["a", 4.64, date(2021, 5, 31)],
    ["a", 6.34, date(2021, 4, 30)],
    ["a", 4.33, date(2021, 3, 31)],
    ["a", 1.32, date(2021, 2, 28)],
    ["a", 3.52, date(2021, 1, 31)]
], schema={"identifier": str, "value": pl.Float64, "date": pl.Date})

grp = df.sort("date", descending=False).groupby_rolling(
    index_column="date",
    by="identifier",
    period="3mo",
    closed="both"
).agg([
    pl.min("date").alias("min_date"),
    pl.max("date").alias("max_date")
])


>> exceptions.ComputeError: cannot advance '2021-05-31 00:00:00' by -3 month(s). If you were trying to get the last day of each month, you may want to try `.dt.month_end`
```

### Expected behavior

I would expect that 2021-05-31 - 3 months would produce 2021-02-28.

```
┌────────────┬────────────┬────────────┬────────────┐
│ identifier ┆ date       ┆ min_date   ┆ max_date   │
│ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str        ┆ date       ┆ date       ┆ date       │
╞════════════╪════════════╪════════════╪════════════╡
│ a          ┆ 2021-01-31 ┆ 2021-01-31 ┆ 2021-01-31 │
│ a          ┆ 2021-02-28 ┆ 2021-01-31 ┆ 2021-02-28 │
│ a          ┆ 2021-03-31 ┆ 2021-01-31 ┆ 2021-03-31 │
│ a          ┆ 2021-04-30 ┆ 2021-01-31 ┆ 2021-04-30 │
│ a          ┆ 2021-05-31 ┆ 2021-02-28 ┆ 2021-05-31 │
│ a          ┆ 2021-06-30 ┆ 2021-03-31 ┆ 2021-06-30 │
└────────────┴────────────┴────────────┴────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-10.16-x86_64-i386-64bit
Python:      3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.2
pandas:      1.5.3
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by mcrumiller** [comment]
As per #8479, you have to use `3mo_saturating` instead of `3mo`. This isn't a bug.

**Comment by ritchie46** [comment]
Maybe we should add a hint that the user could use a saturating window.
