### ISSUE TITLE
Doc Request: Add a note that a Struct is an associative array (basically a dict)

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#8806]
### Problem description

[Add here in the docs](https://github.com/pola-rs/polars/blob/main/py-polars/polars/datatypes/classes.py#L474-L517) that a struct is analogous to a dict in python.

**Comment by zundertj** [comment]
As with #8787, probably best to simply open the PR with the text you like to see? It is unclear now whether you expect someone else to do this, or by yourself.

**Comment by DeflateAwning** [comment]
Sure, I can PR! Just wanted to have the issue tracked in case anyone else got to it first, or in case anyone disagreed :) 

Way easier to open an issues quickly than to write the solution

**Comment by zundertj** [comment]
Opening a PR which is a one-line doc addition is not more effort than opening a proper issue ticket. For example, what is missing from your first post:
* what wording would you like to see?
* what input do you expect from others on this issue, agreement on the wording? 
* are you going to work on it? You seem to have a wording in mind, but you didn't put it out there.
You can address all of this by opening a PR.

I don't think individual small doc improvements are a topic for discussion beyond what we do in the normal PR review process. So please create a PR (and if you can, bundle a number of doc improvements together, not every line needs a separate PR!), and leave the issue tracker for bugs & discussions.
