### ISSUE TITLE
Add align_on parameter to pl.concat when horizontal is used

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8807]
### Problem description

Possibly an addition to #8753. A relatively common operation is to align multiple dataframes and combine them. We already have an [`align_frames`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.align_frames.html) function, but has this note:

> Note that this does not result in a joined frame - you receive the same number of frames back that you passed in, but each is now aligned by key and has the same number of rows.

After aligning, you have to go through frames 2-N and drop the key columns. A nice feature would be either to have `pl.concat(dfs, how="horizontal", align_on=keys)`, or a separate `pl.align_and_join`. Something like this:

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1, 2, 3],
    'a': [4, 5, 6],
})

df2 = pl.DataFrame({
    "key": [1, 3, 4],
    'b': [7, 8, 9],
})

df3 = pl.concat([df1, df2], how="horizontal", align_on="key")

     df1                   df2                       df3
┌─────┬──────┐        ┌─────┬──────┐        ┌─────┬──────┬──────┐
│ key ┆ a    │        │ key ┆ b    │        │ key ┆ a    ┆ b    │
╞═════╪══════╡        ╞═════╪══════╡        ╞═════╪══════╪══════╡
│ 1   ┆ 4    │        │ 1   ┆ 7    │        │ 1   ┆ 4    ┆ 7    │
│ 2   ┆ 5    │        │ 3   ┆ 8    │  --->  │ 2   ┆ 5    ┆ null │
│ 3   ┆ 6    │        │ 4   ┆ 9    │        │ 3   ┆ 6    ┆ 8    │
└─────┴──────┘        └─────┴──────┘        │ 4   ┆ null ┆ 9    │
                                            └─────┴──────┴──────┘
```

**Comment by alexander-beedie** [comment]
Perhaps cleaner to have a `how = "align"` option, which is essentially `horizontal` with the common-column join-alignment you describe (follows `pl.align_frames`, but produced one output). Can definitely see the value.

**Comment by mcrumiller** [comment]
@alexander-beedie I was considering using a `how` variable. This feature is identical to `how="diagonal"` except that it's applied horizontally, with the specified columns as the key (whereas in `diagonal` the column names are the key). I've never liked the term `diagonal`, as it's not really diagonal, it's still a vertical concat with alignment. Should we call this `how="horzizontal_diagonal"`? That's super long.

Another option is having `how` options `horizontal`/`vertical`/`align_horizontal`/`align_vertical`. Issue is, we need a way to specify the horizontal keys still.

**Comment by s-banach** [comment]
I’m obviously missing something, but how is this different than a join?

**Comment by mcrumiller** [comment]
@s-banach functionally it's identical, but it allows you to perform it immediately on many dataframes without having to do:

```python
df = dfs[0]
for df in dfs[2:]
    df = df.join(df, on=key, how="outer")
```
Which isn't that bad I suppose, but it's a bit messy and is a pretty common operation.

If there are enough people against it I will remove it from the PR. I'll wait for a few others to chime in, we're kind of 2 and 2 right now.

**Comment by s-banach** [comment]
Oh! Yeah, it should just be called pl.join rather than concat_align or whatever.

**Comment by mcrumiller** [comment]
How about an alternative, allowing `join` to take a list of dfs, or have a `join_multi`?

**Comment by s-banach** [comment]
I always thought `concat` was just `vertical join`, so it never seemed consistent to me that we do the prefix `concat([a, b])` but the infix `a.join(b)`. It seems like a prefix `join([a, b])` would be a logical extension of the API.

**Comment by mcrumiller** [comment]
Well, `concat` has a `how` argument that specifies if the concatenation occurs horizontally or vertically. We're talking about horizontal joins here: if we have multiple dataframes that we want to align-then-concatenate (which is the same as doing multiple outer joins, but is probably more efficient as each dataframe only gets modified one), it's nice to be able to do that in one step.

**Comment by alexander-beedie** [comment]
@mcrumiller: done/merged ;)
