### ISSUE TITLE
SQL: BETWEEN beginning and end values should be inclusive

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8817]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I just tested the BETWEEN operator in SQL, and it looks like it's not including the beginning and end values.
It seems that beginning and end values should be included per SQL standards: https://www.w3schools.com/sql/sql_between.asp

### Reproducible example

```python
import polars as pl
import duckdb

df = pl.DataFrame({
    'col1' : ['A','B','C','D']
})

query = """
SELECT *
FROM df 
WHERE col1 BETWEEN 'A' AND 'C'
"""

pl.SQLContext(register_globals=True, eager_execution=True).execute(query)
shape: (1, 1)
┌──────┐
│ col1 │
│ ---  │
│ str  │
╞══════╡
│ B    │
└──────┘

# duckDB includes them
duckdb.query(query)
┌─────────┐
│  col1   │
│ varchar │
├─────────┤
│ A       │
│ B       │
│ C       │
└─────────┘
```

### Expected behavior

I would expect BETWEEN to include beginning and end values

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.13
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.1.0
```

</details>

**Comment by alexander-beedie** [comment]
Ahhh, I see it; will have a fix out in a few minutes.
