### ISSUE TITLE
Polars panicks when serializing LazyFrames

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8819]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I have noticed 2 cases where Polars panicks when serializing LazyFrames (i.e. using write_json).
This causes Polars to panick when saving a database with the Polars CLI (see https://github.com/pola-rs/polars/issues/8795)

Case 1: when the data type is Categorical.
```python
lf = pl.LazyFrame({'col': ['A', 'A', 'B', 'B']},
    schema = [('col', pl.Categorical)])

lf.write_json()
# thread '<unnamed>' panicked at 'not yet implemented', /home/runner/work/polars/polars/polars/polars-core/src/datatypes/_serde.rs:90:18
```

Case 2: when a JSON is read from disk:
```python
lf2 = pl.LazyFrame([
    {"product_sku": "ABC123", "product_name": "Example Product 1", "price": 19.99},
    {"product_sku": "DEF456", "product_name": "Example Product 2", "price": 29.99}])

lf2.write_json()
# this works

lf2.collect().write_ndjson('lf2.json')
lf2_scan_from_disk = pl.scan_ndjson('lf2.json')

lf2_scan_from_disk.write_json()
# ValueError: Error("the enum variant LogicalPlan::AnonymousScan cannot be serialized", line: 0, column: 0)
```

### Reproducible example

see above

### Expected behavior

no panick when writing a JSON file, or when saving a database with Polars CLI

### Installed versions

<details>
--------Version info---------
Polars:      0.17.13
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.1.0
</details>

**Comment by ritchie46** [comment]
Yes, we should create an `AnonymousScanPrivate` similar to what we have done with `FunctionPrivate` that way we can serialize the function.

**Comment by lucazanna** [comment]
@ritchie46 is there anything I can do to help with this?

for example: testing different data types or file types?

**Comment by stinodego** [comment]
The first example (categorical) has been fixed. Serializing the scan is still an issue.

**Comment by stinodego** [comment]
This has been resolved.
