### ISSUE TITLE
add support for `DISTINCT ON` keyword in SQL select clauses

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8821]
### Problem description

`DISTINCT ON (var1, var2, ...)` is a powerful but lesser-known postgres function that I use it all the time. It does the following in one operation:

1. Does a `GROUPBY` on the variables in parentheses.
2. Selects the first record in each group.

This would be anatomically equivalent of calling:

```python
(
    df.sort(by=order)
    .groupby(groups)
    .agg(pl.all().first())
)
```

Example: Return the top-scoring record for each player

### standard Polars
```python
import polars as pl
from datetime import date

df = pl.DataFrame(
    [
        ["Bob",    date(2020, 1,  1), 8],
        ["Pete",   date(2020, 1,  1), 2],
        ["Pete",   date(2021, 2,  5), 9],
        ["Pete",   date(2023, 4,  6), 3],
        ["Martha", date(2020, 1,  1), 2],
        ["Martha", date(2022, 8, 16), 6],
    ],
    schema={
        "Name": pl.Utf8,
        "Record Date": pl.Date,
        "Score": pl.UInt8
    },
    orient="row"
)

(
    df.sort(by=["Name", "Score"], descending=[False, True])
    .groupby("Name")
    .first()
)
```
```
shape: (3, 3)
┌────────┬─────────────┬───────┐
│ Name   ┆ Record Date ┆ Score │
│ ---    ┆ ---         ┆ ---   │
│ str    ┆ date        ┆ u8    │
╞════════╪═════════════╪═══════╡
│ Pete   ┆ 2021-02-05  ┆ 9     │
│ Martha ┆ 2022-08-16  ┆ 6     │
│ Bob    ┆ 2020-01-01  ┆ 8     │
└────────┴─────────────┴───────┘
```

### SQL
```sql
SELECT DISTINCT ON ("Name")
  "Name",
  "Record Date",
  "Score"
FROM
  player_scores
ORDER BY
  "Name",
  "Record Date" DESC;
```
Name | Record Date | Score
---|---|---
Bob | 2020-01-01 | 8
Martha | 2022-08-16 | 6
Pete | 2023-04-06 | 3

**Comment by universalmind303** [comment]
So it doesn't look like [sqlparser](https://github.com/sqlparser-rs/sqlparser-rs) natively supports `DISTINCT ON`. 

I'd suggest opening up a feature request with them. I'll see if I can come up with something using the current sqlparser version.

**Comment by cmdlineluser** [comment]
@universalmind303 Was it added in https://github.com/sqlparser-rs/sqlparser-rs/pull/852

**Comment by universalmind303** [comment]
Oh nice, I was looking at the latest version: `0.33` on docs.rs. I didn't realize that was just added.
