### ISSUE TITLE
df.transpose() fails if it contains categoricals

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8829]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If a dataframe has categoricals, `transpose` fails. There are a few details here:

* if the string cache is **not** enabled, transpose never works if categorical columns exist
* if the string cache **is** enabled, transpose works as long as there are only categorical and string dtypes in the dataframe

#### With only categorical column, it fails without string cache and works with:
```python
import polars as pl

# works
with pl.StringCache():
    pl.DataFrame({
        'b': pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
    }).transpose()

# fails
pl.DataFrame({
    'b': pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
}).transpose()
```
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot construct
Categorical from these categories, at least on of them is out of bounds"))
```

#### With any non-str columns additionally, it fails regardless:
```python
import polars as pl

# fails
with pl.StringCache():
    pl.DataFrame({
        'a': [1, 2, 3],
        'b': pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
    }).transpose()
```
```
exceptions.ComputeError: failed to determine supertype of date and cat
```

### Expected behavior

Should work, possibly converting to `str` if necessary.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.13
Index type:  UInt32 
Platform:    Windows-10-10.0.19044-SP0
Python:      3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  0.3.2_alpha.2
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.0.9
```

</details>

**Comment by mcrumiller** [comment]
Ok, it works when the string cache is enabled. Perhaps we it should raise an Exception here?

**Comment by ritchie46** [comment]
I think we should succeed either way. Can take a look later.
