### ISSUE TITLE
Expose the SQL expr parser to end users

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars#8839]
### Problem description

Currently the `parse_expr` function that takes in a sql expr & returns a polars expr is private & only part of polars-sql internals. 

It would be a nice addition if end-users could access this functionality. It'd add a lot of extensibility to applications that are built on top of polars. 

```python
sql = "max(column_1) as max_col_1"
expr = pl.parse_sql_expr(sql)
df.select(expr)
```

```rust
let sql = "max(column_1) as max_col_1";
let expr = polars::parse_sql_expr(sql)?;
let df = df.select(vec![expr]);
```

**Comment by ritchie46** [comment]
Yes, good point. Would be cool in python as well.

**Comment by avimallu** [comment]
Another cool thing this would allow is to translate Polars expressions to database queries directly, [much like dbplyr](https://dbplyr.tidyverse.org/). We could allow then, for instance, to run a Polars query on an external table where it is inconvenient to use Polars directly (can't download full table, too big to run without distributed infrastructure), bring it to a size manageable on a single machine, and then seamlessly transition to using Polars.
