### ISSUE TITLE
Group by memory leak

### ISSUE THREAD

**Issue by tamasfe** [pola-rs/polars#8844]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

If a groupby is done by multiple columns, allocated memory is never freed and grows fast at a linear rate until OOM.

The bug seems to have been introduced in f09fd6f66f8fc31f51b69fe93a09e955c9be3490, there were leaks in prior versions but not of this magnitude.

According to heaptrack the allocations happen by a `Vec::with_capacity` in `groupby_threaded_multiple_keys_flat`, so I suspect the memory that is leaked is allocated here: https://github.com/pola-rs/polars/blob/ff8b9db72e8caa07a2ef6672c76b76ae009f5a86/polars/polars-core/src/frame/groupby/hashing.rs#L486

Passing an empty vec here seemingly fixes the leak:
https://github.com/pola-rs/polars/blob/ff8b9db72e8caa07a2ef6672c76b76ae009f5a86/polars/polars-core/src/frame/groupby/hashing.rs#L145

Thus the next logical step was this fn:

https://github.com/pola-rs/polars/blob/ff8b9db72e8caa07a2ef6672c76b76ae009f5a86/polars/polars-core/src/frame/groupby/proxy.rs#L49

Replacing the parallel loop body to do nothing seemed to fix _some_ of the leaks, but at this point without domain knowledge things are pretty arcane for me so I decided not to go deeper for now.

### Reproducible example

The examples in the following repo leak around 2gb of memory in a minute: https://github.com/tamasfe/polars-groupby-leak, no matter the datatype.

The heaptrack artifacts can be found here: https://github.com/tamasfe/polars-groupby-leak/releases/tag/stuff

### Expected behavior

No leaks

### Installed versions

```
polars = { version = "0.29.0", features = ["lazy", "performant", "temporal", "timezones", "nightly", "dtype-categorical"] }
```

**Comment by ritchie46** [comment]
Thanks! Fix coming up.
