### ISSUE TITLE
Can't install polars on a multi-stage container image (Alpine Linux)

### ISSUE THREAD

**Issue by S0LERA** [pola-rs/polars#8852]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Good morning,

I need to install polars on a container image based on alpine linux. The problem is that it depends on rust and some system libraries that alpine doesn't have. Once all the dependencies are installed, polars works, but the image is 4.5 GB and this is too much considering that the alpine image is 3 MB.

To reduce weight, I have tried to make a multi-stage image, in which polars are installed in the first phase and in the second phase polars are copied to the final image. To do this, I have tried various methods such as encapsulating the installation in a virtual environment, or installing it with the --user flag, following the steps on this [web](https://pythonspeed.com/articles/multi-stage-docker-python/).

The problem is that in the final image, once you try to import polars, it gives the following error:

```
>>> import polars
/root/.local/lib/python3.11/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
   from polars.utils.polars_version import get_polars_version
```

What binary is this referring to? Can I copy it from the base image?

If not, is there a way to install polars via a multi-stage image or to have polars on a light alpine-linux based image?

### Reproducible example

```python
One of the tested Dockerfiles:

## BASE IMAGE
FROM docker.io/python:3.11.3-slim-bullseye AS image-polars
RUN apt -y update
RUN pip3 --no-cache-dir install --upgrade pip setuptools
RUN pip3 install --user polars


## FINAL IMAGE
FROM docker.io/alpine:3.18
RUN apk --no-cache update
RUN apk add --no-cache python3
COPY --from=image-polars /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
```

### Expected behavior

Polars is imported and can be used without errors

### Installed versions

<details>

```
0.17.13
```

</details>

**Comment by stinodego** [comment]
`python:3.11.3-slim-bullseye` is not an Alpine image. So you're compiling Polars on a different architecture than where you're using it. That won't work.

Try building the wheel on an Alpine image using `maturin` and copying that to the new image, and then install it using pip. That could work.

**Comment by julivi72** [comment]
Hi!!,

I have the same issue, i´m trying to install polars in Alpine image but when i try to compile with maturin "**maturin build --release -- -C target-cpu=native**" it throws this error:

![image](https://github.com/pola-rs/polars/assets/11858584/55b2b5c4-5d52-438b-aac7-8850ae5cff3c)

I have also tried to install polars with "command", after installing the nightly version of rustup. Attached error:

![image](https://github.com/pola-rs/polars/assets/11858584/bde881c9-5c36-4793-9179-a41900d265e5)

I am using version 3.18 of Alpine and Python3.11.

What is the solution if I need polars?

**Comment by stinodego** [comment]
I believe SIMD is a separate feature flag. You could try turning it off and see if compilation succeeds.

That does mean you will get a less optimized version of Polars. So my previous comment still stands: don't use Alpine if you don't absolutely have to.

**Comment by julivi72** [comment]
How can I turn off the SIMD?

**Comment by stinodego** [comment]
Maybe we can build a `musllinux` wheel in our release process. I'll look into it.

**Comment by ritchie46** [comment]
I am not sure this is worth the binary. We have limited space on PYPI. Musl also doesn't have libc, so I expect several problems.

**Comment by S0LERA** [comment]
I encourage you to bring alpine-linux distros support. Maybe alpine is not the best option to work with python, but is widely used on containerized environments.

**Comment by stinodego** [comment]
You say you can build it on Alpine - while @julivi72 says he cannot manage to do so.

Can you show me the Dockerfile of that 'heavy' image?

**Comment by ritchie46** [comment]
Not having alpine wheels isn't that strange. For instance, numpy also doesn't support alpine wheels. Alpine is a whole can of worms, that we should not open. For instance the SIMD code doesn't work. Probably the allocator doesn't work, probably memory map doesn't work. You are not asking something trivial here.

**Comment by rnarkk** [comment]
Seems NumPy is going to ship musllinux since its next version 1.25 https://github.com/numpy/numpy/issues/20089.

**Comment by sanmai-NL** [comment]
> I am not sure this is worth the binary. We have limited space on PYPI. Musl also doesn't have libc, so I expect several problems.

This sentence suggest gross misunderstanding of the topic.

musl _is_ a libc implementation itself.  In fact, it is a careful, high quality and POSIX-compliant one, much more so than glibc. Alpine Linux uses musl libc by default, and can in addition support glibc.

Pandas also has a musllinux wheel. musl targets are one tier 2 for Rust, in fact the default targets for statically linked Linux binaries use musl libc.

I highly doubt the features you list don't work with Alpine Linux. SIMD has nothing to do with libc. If it doesn't work due to implementation limitations, that in itself isn't an argument to not support musl libc. Rather, it suggests some implementation quality limitations.

**Comment by tooptoop4** [comment]
@S0LERA can u share the dockerfile for the 4,5GB image?

**Comment by coastalwhite** [comment]
> This sentence suggests gross misunderstanding of the topic

I agree that this issue originally might not have been handled with the greatest understanding of what musl is, where it is used and why it is used. I do, however, agree with the current conclusion of @ritchie46 and @stinodego that this is not really in scope for Polars at the moment and maintaining another target is a lot of work. It is always a question of effort vs. pay-off.

What we are usually very open to is for someone or a group of people to maintain such targets or bindings with us. At that point, we can of course facilitate if we are really doing incompatible practices. People putting in this effort is also a sign that people are serious enough about a technology.

**Comment by ritchie46** [comment]
> I highly doubt the features you list don't work with Alpine Linux. SIMD has nothing to do with libc. If it doesn't work due to implementation limitations, that in itself isn't an argument to not support musl libc. Rather, it suggests some implementation quality limitations.

Feel free to add support for that. We are open to contributions. I am not an expert on musl, nor I claim to be. Please keep it lightly. Polars is free software and comes as is. Suggesting that we have quality issues because our project is scoped differently than what you'd like to see is not constructive and I ask you to refrain from that.

I am open to contributions that add support for MUSL, if they don't hinder our own goals of the project.

**Comment by sanmai-NL** [comment]
@ritchie46 Please refrain from (unstatedly) scoping things out before having taken the time to learn, and verifying you understand, what it is your users requested. If you think that requires expertise, which it doesn't, leave it to be experts please.

**Comment by ritchie46** [comment]
> @ritchie46 Please refrain from (unstatedly) scoping things out before having taken the time to learn, and verifying you understand, what it is your users requested. If you think that requires expertise, which it doesn't, leave it to be experts please.

I believe I am in the right to scope my own open source project and time. It is free software.

**Comment by sanmai-NL** [comment]
Thanks but closing and commenting cost you time while discouraging others.
