### ISSUE TITLE
`DataFrame.equals` gives unexpected result for Categorical columns

### ISSUE THREAD

**Issue by klamann** [pola-rs/polars#8853]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`frame_equal` allows us to check polars DataFrames for equality and the current implementation is pretty relaxed about data types, e.g. an Int32 column is considered equal to a UInt64 column as long as all integers are equal. Same counts for comparisons between strings an categoricals with one notable exception: categorical is never equal to another categorical, even if there are exactly the same categories.

### Reproducible example

```python
import polars as pl

df_str_1 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Utf8})
df_str_2 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Utf8})
df_cat_1 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Categorical})
df_cat_2 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Categorical})

# utf8 vs utf8: check
assert df_str_1.frame_equal(df_str_2)
# utf8 vs categorical: check
assert df_str_1.frame_equal(df_cat_1)
# categorical vs utf8: check
assert df_cat_1.frame_equal(df_str_1)
# categorical vs categorical: uh oh 😢
assert df_cat_1.frame_equal(df_cat_2)
```

### Expected behavior

I would expect `df_cat_1.frame_equal(df_cat_2)` to return `True`. If this is intended behaviour, I would expect a docstring that explains which data types can be compared and which ones can not.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Windows-10-10.0.22621-SP0
Python:      3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    0.8.1
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
For `Categorical` values to be comparable they need to be created under the same `StringCache` (so that the same string will map to the same category), eg:
```python
with pl.StringCache():
    df1 = pl.DataFrame( {"a": ["x", "y", "z"]}, schema={'a': pl.Categorical} )
    df2 = pl.DataFrame( {"a": ["x", "y", "z"]}, schema={'a': pl.Categorical} )
    
df1.frame_equal( df2 )
# True
```

**Comment by klamann** [comment]
I see, thanks! Still a bit unexpected for me, since it works when I compare strings to categorical.

Since categorical columns are always backed by string values, I think it may be a good idea to compare the actual string values in the `frame_equal` function, and not the hidden internal state (i.e. the integers that map to the actual strings). I feel like this would be in line with the behaviour when e.g. different integer types are used, or when strings are compared to categorical values.

**Comment by mcrumiller** [comment]
> Since categorical columns are always backed by string values, I think it may be a good idea to compare the actual string values in the frame_equal function, and not the hidden internal state (i.e. the integers that map to the actual strings).

This is a big can of worms to open, because now you're either requesting that we should *also* compare two categorical series as equal based on their underlying strings as well. If we didn't do that too, we'd get `df1['a'] != df2['a']` while at the same time having `df1.series_equal(df2)` evaluating to `True`, which would be nonsensical.

So, then we would need to also implement this for all comparison operators, sorting, etc. After all, if `df1['a'] == df2['a']`, then any operation applied on either side of the equals sign should preserve the equality, and at the end of the day, what we have a global string cache.

I personally feel like the string cache should be on by default because *every* newcomer to polars gets screwed by categoricals. Is the downside that, once we have more than 255 distinct categoricals, the string cache needs to bump up to `u16` and that's wasteful for categoricals in a smaller context? I admit I don't really know the internal works.

Anyway, I think we should raise a warning when any comparison operator is applied to two categorical columns outside of the string cache.

**Comment by klamann** [comment]
So, I've been looking into this a little more... let's try some stuff

```python
import polars as pl

df_str_1 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Utf8})
df_str_2 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Utf8})
df_cat_1 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Categorical})
df_cat_2 = pl.DataFrame({"a": ["x", "y", "z"]}, schema={'a': pl.Categorical})

# comparing utf8 series to utf8 series with series_equal
assert df_str_1['a'].series_equal(df_str_2['a'])

# comparing utf8 series to utf8 series with ==
assert (df_str_1['a'] == df_str_2['a']).all()

# let's try the same with utf8 and categorical
assert (df_str_1['a'] == df_cat_1['a']).all()
assert df_str_1['a'].series_equal(df_cat_1['a'])

# now let's compare different categoricals: series_equal works fine!
assert df_cat_1['a'].series_equal(df_cat_1['a'])

# comparison with == fails with "exceptions.ComputeError: cannot compare categoricals originating from different sources; consider setting a global string cache"
assert (df_cat_1['a'] == df_cat_2['a']).all()
```

@mcrumiller it looks like the edge case you mentioned regarding `df1['a'] == df2['a']` is already solved by raising an exception, which seems like the right thing to do in this situation.

Also, it seems like `series_equal` already works fine for categorical types. Does `frame_equal` not use `series_equal` internally?

**Comment by stinodego** [comment]
The example in the original issue now produces the expected result.
