### ISSUE TITLE
exclude option in arr.take()

### ISSUE THREAD

**Issue by alonket** [pola-rs/polars#8857]
### Problem description

I have column with text in format of `"a.b.c.d"` into two parts:
column with the last variable after the ".", and column with the rest when the length is different between rows.

I can easily get the last variable with:
`
.with_columns([
        pl.col('text').str.split('.').arr.last().alias('last')]
)
`
But for the rest it's little tricky...

### Suggested Solution 
It will be very helpful if I could do something like:
`
.with_columns([
        pl.col('text').str.split('.').arr.get(-1, exclude = True).alias('rest')]
)
`

For example:
```
list = [1,2,3,4]

list.arr.get([1,2], exclude = True)  # [1,4]
```

**Comment by cmdlineluser** [comment]
It looks like negative indexing for head/tail that works on Series/DataFrame isn't yet implemented for the `.arr` methods:
```
pl.Series([1, 2, 3, 4]).head(1)

# shape: (1,)
# Series: '' [i64]
# [
# 	1
# ]

pl.Series([1, 2, 3, 4]).head(-1)

# shape: (3,)
# Series: '' [i64]
# [
# 	1
# 	2
# 	3
# ]

pl.Series([[1, 2, 3, 4]]).arr.head(1)

# shape: (1,)
# Series: '' [list[i64]]
# [
# 	[1]
# ]

pl.Series([[1, 2, 3, 4]]).arr.head(-1)

# shape: (1,)
# Series: '' [list[i64]]
# [
# 	[1, 2, … 4]
# ]
```
You can slice but that requires calculating the length, there's also `.str.extract_all`:
```
s = pl.Series(["a.b.c.d"])

s.str.split(".").arr.slice(0, s.str.split(".").arr.lengths() - 1)

# shape: (1,)
# Series: '' [list[str]]
# [
#	["a", "b", "c"]
# ]

s.str.extract_all(r"[^.]+$|.+[.]")

# shape: (1,)
# Series: '' [list[str]]
# [
#	["a.b.c.", "d"]
# ]
```

**Comment by alonket** [comment]
Thanks this exactly what I tried to do!
If this is already planned I will close this issue
