### ISSUE TITLE
`fill_infinite` functionality analogous to `fill_nan`

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8863]
### Problem description

Polars has a `fill_nan` method on Lazy/DataFrames, which just does a `when -> then -> otherwise` call using `is_not_nan`. It would be nice to have an analogous `fill_infinite` to replace infinite values (with a `when -> then -> otherwise` call using the `is_finite` expression). Something like

```python
pl.DataFrame({"A": [-math.inf]}).fill_infinite(None)

shape: (1, 1)
┌──────┐
│ A    │
│ ---- │
│ f64  │
╞══════╡
│ null │
└──────┘
```

**Comment by stinodego** [comment]
This would be easy enough to add, but I don't know if it's worth adding.

**Comment by erinov1** [comment]
> This would be easy enough to add, but I don't know if it's worth adding.

I think its worth adding for feature parity between degenerate float values, NaN and +-inf. I fill the latter with `None` just as much as the former.

**Comment by stinodego** [comment]
We do not plan to implement this at this point. Use `when/then/otherwise` instead.
