### ISSUE TITLE
`SQLContext` description is not available in the API documentation

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8867]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is not new, but I notice that details for the `SQLContext` method are not available in the API documentation:
https://pola-rs.github.io/polars/py-polars/html/reference/sql.html

That means that users cannot see the description for the 2 new parameters: register_globals and eager_execution

### Reproducible example

```python
# n/a
```

### Expected behavior

The API documentation includes a description for the SQLContext method

### Installed versions

<details>

```
N/A
```

</details>

**Comment by alexander-beedie** [comment]
Ahh, the class isn't documenting its `__init__` for some reason. I can improve that page with plenty of additional detail tomorrow night (I won't have access to a computer again until then ;))

**Comment by lucazanna** [comment]
@alexander-beedie good! so more people can know about all those improvements

**Comment by alexander-beedie** [comment]
Closed by #8944.
