### ISSUE TITLE
ArrowErrorException: NotYetImplemented("Casting from Int64 to LargeList

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#8882]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Error filtering list type data

### Reproducible example

```python
import polars as pl

test_df = pl.DataFrame({
    'm':[[11, 106], [485, 566]],
    'n':[7, 34]
})

# error
test_df.filter(pl.col('m') == test_df[0,0])

# error
test_df.filter(pl.col('m') ==  [11, 106])


```
```


### Expected behavior

Correct filtering

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.13
Index type:  UInt32
Platform:    Linux-5.15.0-50-generic-x86_64-with-glibc2.31
Python:      3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]

----Optional dependencies----
numpy:       1.23.4
pandas:      2.0.1
pyarrow:     10.0.1
connectorx:  0.3.1
deltalake:   0.6.4
fsspec:      2022.11.0
matplotlib:  3.5.1
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by lucazanna** [comment]
There's one question on StackOverflow which seems to have the same problem:
https://stackoverflow.com/questions/76285142/compare-polars-list-to-python-list

**Comment by lucazanna** [comment]
Maybe there is a different way to filter based on lists?

I also tried to wrap the list for comparison with pl.lit() and pl.Series(), but that doesn't seem to help

**Comment by avimallu** [comment]
I tried a variety of different ways, so I guess the most straightforward answer right now is that it's simply not available as a feature yet. The best solution right now would be to go by the Stackoverflow answers.

**Comment by stinodego** [comment]
This now works correctly.
