### ISSUE TITLE
Cannot read from and then write to same ipc file - PanicException

### ISSUE THREAD

**Issue by gjwebber** [pola-rs/polars#8886]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading from and then writing to the same ipc file, a panic occurs:

> PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 1224, kind: Uncategorized, message: "The requested operation cannot be performed on a file with a user-mapped section open." }

Tested exactly the same with `read_csv` and `write_csv` without any issues.

### Reproducible example

```python
import polars as pl
import random

data = [
    pl.Series("col1", random.sample(range(1, 10000), 1000)),
    pl.Series("col2", random.sample(range(1, 10000), 1000)),
    pl.Series("col3", random.sample(range(1, 10000), 1000)),
    pl.Series("col4", random.sample(range(1, 10000), 1000)),
    pl.Series("col5", random.sample(range(1, 10000), 1000)),
]

df = pl.DataFrame(data)

df.write_ipc("output")
df = pl.read_ipc("output")
df.write_ipc("output")
```

### Expected behavior

The file is created, re-read and then re-written without error.

### Installed versions

--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

**Comment by VictorLemosR** [comment]
For me, that still did not solve the issue.
Changed to parquet and worked fine.

```
df = pl.read_ipc(path, memory_map=False)
df.write_ipc(path)
```

> PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Acesso negado." }

"Acesso negado." is a portuguese message (probably because of my system) which means permission denied.

**Comment by gjwebber** [comment]
> Set memory map to False.

This fixes the issue for me @VictorLemosR . I'm on Windows 10 if it makes any difference. I'm going to close this here, also because your and my error message are slightly different.

Thanks @ritchie46
