### ISSUE TITLE
Read Delta Lake metadata first

### ISSUE THREAD

**Issue by everestas** [pola-rs/polars#8887]
### Problem description

It seems that when Polars is working with Delta Lake (ADLS v2 in my case), he doesn't read metadata of delta tables and scans all parquet files. 

This shows up when you try to use filtering on Delta Lake with Polars. If where clause is applied on query, it will take the same time to process a query as without filterring. For example:

```
lf_posit = pl.scan_delta(
    table_path, storage_options=storage_options, raw_filesystem=pa_fs, delta_table_options=delta_table_options, pyarrow_options=pyarrow_options
).select(["imo", "mmsi", "lat", "lon", "msg_time", 'speed']).filter(pl.col("mmsi").is_in(["331000065"])).collect()
```

```
lf_posit = pl.scan_delta(
    table_path, storage_options=storage_options, raw_filesystem=pa_fs, delta_table_options=delta_table_options, pyarrow_options=pyarrow_options
).select(["imo", "mmsi", "lat", "lon", "msg_time", 'speed']).collect()
```

It takes the same to process these two queries. This must mean that both queries are scanning through every parquet file. Instead it could read metadata file first and check what files need to be read.

I compared the same query with Spark, Spark process query faster if filtering is applied.

**Suggestion:** When scanning Delta Table and .filter is used, first check Delta Table's metadata (__delta_log_) to see what files need to be read. 

_delta_log includes _stats_ field which tells about specific parquet file and its min/max column values. For testing purposes, Z Order Optimization should be applied on Delta Table.

**Comment by stinodego** [comment]
You should use `pyarrow_options` for this. From the docs:

```python
pl.scan_delta(  
    table_path,
    pyarrow_options={"partitions": [("year", "=", "2021")]},
)
```

It would be nice though if the filter would be pushed up properly.

**Comment by everestas** [comment]
> You should use `pyarrow_options` for this. From the docs:
> 
> ```python
> pl.scan_delta(  
>     table_path,
>     pyarrow_options={"partitions": [("year", "=", "2021")]},
> )
> ```
> 
> It would be nice though if the filter was applied properly.

This only applies if you partition your table on year, but if we take a high-cardinality column on which we didn't partition, this wouldn't work. However, a good thing that there is statistics in _delta_log which tells about every parquet file and its column min and max values. So, if I have ID column which ranges from 1000000 to 9999999, the _delta_log will tell me that in 1_file.parquet there are IDs between 1000000 and 2000000, 2_file.parquet there are IDs between 2000000 and 3000000, and so on

**Comment by stinodego** [comment]
I see, thanks for the insight. Then I think this might need to be done on the side of `delta-rs`. @chitralverma do you have any input here?

**Comment by chitralverma** [comment]
AFAIK, this is due to polars not pushing filters correctly to `scan_ds`. there were a few issues raised regarding this and some work was done in this direction (#https://github.com/pola-rs/polars/issues/6395).

seems like there is still some work left on this because certain operators along with certain types work correctly, while others don't.

Apparently, duckdb also had similar issues in the past (https://github.com/delta-io/delta-rs/issues/764). Not sure if they were able to fix this or not.

**Comment by chitralverma** [comment]
Also see Will's comment [here](https://github.com/pola-rs/polars/issues/7750#issuecomment-1541013054).
He has described the same thing.

links to https://github.com/pola-rs/polars/issues/7750

**Comment by chitralverma** [comment]
Update: I dug into this and found that apparently `is_in(..)` is not being pushed down. Other functions like =, < , >, is_between etc. are being converted to predicates successfully.

**Comment by chitralverma** [comment]
update: this is correct, as I can see here, is in is missing in pyarrow predicates.

https://github.com/pola-rs/polars/blob/main/polars/polars-lazy/polars-plan/src/logical_plan/pyarrow.rs

I will raise a PR for this
