### ISSUE TITLE
Cannot reuse series in DataFrame init from dict of series

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8909]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following raises an error:

```python
series = pl.Series([1, 2, 3])
pl.DataFrame({"A": series, "B": series})

DuplicateError: column with name 'B' has more than one occurrences
```

But it works fine if aliasing one of the series first (with any random name)

```python
pl.DataFrame({"A": series, "B": series.alias("some_random_name"})

shape: (3, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
│ 3   ┆ 3   │
└─────┴─────┘
```

I would have expected the original example to work successfully without aliasing, like when using a python list instead of a series:

```python
lst = [1, 2, 3]
pl.DataFrame({"A": lst, "B": lst})

shape: (3, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
│ 3   ┆ 3   │
└─────┴─────┘
```

### Reproducible example

```python
series = pl.Series([1, 2, 3])
pl.DataFrame({"A": series, "B": series})
```

### Expected behavior

The dataframe initialization should succeed.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    macOS-13.2-arm64-arm-64bit
Python:      3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by alexander-beedie** [comment]
I see what's going on here...there's a secondary/related edge-case too. 
Will have a patch that takes care of both shortly.

**Comment by erinov1** [comment]
Thanks @alexander-beedie !
