### ISSUE TITLE
`Expr.repeat_by` gives wrong output with literal inputs

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8910]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Inputting a literal caps the length of the resulting expression to 1.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame(
    {
        "a": ["x", "y", "z"],
        "n": [3, 3, 3],
    }
)
expected = pl.DataFrame({"a": [["x", "x", "x"], ["y", "y", "y"], ["z", "z", "z"]]})

result = df.select(pl.col("a").repeat_by("n"))
assert_frame_equal(result, expected)  # Succeeds

result = df.select(pl.col("a").repeat_by(3))
assert_frame_equal(result, expected)  # Fails
```

Inputting the literal results in:
```
shape: (1, 1)
┌─────────────────┐
│ a               │
│ ---             │
│ list[str]       │
╞═════════════════╡
│ ["x", "x", "x"] │
└─────────────────┘
```

### Expected behavior

Test above should pass.

### Installed versions

master

**Comment by mcrumiller** [comment]
`repeat_by` expects an `Expr`, not a literal input. See [the documentation for `repeat_by`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.repeat_by.html):

>Expr.repeat_by(
>    *by: Expr | [str](https://docs.python.org/3/library/stdtypes.html#str)*
>) → Self[[source]](https://github.com/pola-rs/polars/blob/main/py-polars/polars/expr/expr.py#L4281-L4320)

which means you need to supply a `pl.lit(3)`. But yes, it still doesn't work:

```
df.select(pl.col("a").repeat_by(pl.lit(3)))
```
```
shape: (1, 1)
┌─────────────────┐
│ a               │
│ ---             │
│ list[str]       │
╞═════════════════╡
│ ["x", "x", "x"] │
└─────────────────┘
```

**Comment by stinodego** [comment]
It uses the input parsing util, so supplying 3 or lit(3) is the same. It's on my to do list to further formalize this.
