### ISSUE TITLE
sort_by_expr with a boolean column fails

### ISSUE THREAD

**Issue by qrilka** [pola-rs/polars#8926]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

`sort_by_expr` with two columns one of which is a boolean fails with `ComputeError(ErrString("cannot create series from UInt8"))`

### Reproducible example

    let df = df![
        "a" => [8,1],
        "b" => [false,true],
    ]?;
    let result = df
        .lazy().select([col("a"), col("b")])
        .sort_by_exprs(vec![col("b"), col("a")], vec![false, false], false)
        .collect()?;
    println!("Result: {result}");

### Expected behavior

console output
```
Result: shape: (2, 2)
┌─────┬───────┐
│ a   ┆ b     │
│ --- ┆ ---   │
│ i32 ┆ bool  │
╞═════╪═══════╡
│ 8   ┆ false │
│ 1   ┆ true  │
└─────┴───────┘
```

### Installed versions

<details>
features = ["json","parquet","lazy"]
using commit 81a2450b8ab73fdbdc68a248cde174bc1f7a33a8 as 0.29.0 doesn't include the fix for bitwise operations
</details>

**Comment by ritchie46** [comment]
You must activate `dtype-u8`.

**Comment by qrilka** [comment]
For documentation purposes: I've enabled the feature flag `dtype-u8`(default `dtype-slim` doesn't activate numeric types) and it resolves the problem.
At the same time the behavior is quite surprising to me as for example sorting by a single boolean column works OK but boolean+i32 - doesn't if `dtype-u8` is not enabled.
