### ISSUE TITLE
Support `value_counts` on `LazyFrame`?

### ISSUE THREAD

**Issue by ianozsvald** [pola-rs/polars#8933]
### Problem description

If I'm missing something - sorry for the noise. Is there a more appropriate place (a discord/chat location?) to ask these sorts of questions?

It looks like `value_counts` isn't present on a `LazyFrame`, leading to a little confusion for me when using the `LazyFrame`. I've tried to see if there's a good reason why a `Series` can't be supported on a `LazyFrame` but I don't see any documentation about it, so maybe I'm just missing something?

Using a large (circa 650M row) parquet file set I'd like to do a `value_counts` on one column. I have a solution for eager evaluation, a part-lazy and part-eager solution and a full-lazy solution which gives me a result that I don't understand.

First if I query the parquet fileset and load just my column, I can then select a column (which yields a dataframe), then ask for this single column to be a series, then run `value_counts` (as `value_counts` only operates on a Series):

```
# eager solution, fits in RAM
dfp = pl.read_parquet(parquet_test_result + "/*.parquet", columns=['test_class_id'])
dfp.select('test_class_id')['test_class_id'].value_counts().sort(by='counts', descending=True)
# I could also use dfp.select('test_class_id').to_series() 
# overall this takes 9 seconds
```

Next I can try a part-lazy solution:
```
dfp = pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id")).collect()
dfp['test_class_id'].value_counts().sort(by='counts', descending=True)
# I could also use dfp.select('test_class_id').to_series() 
# overall this takes 7 seconds
```

I can't do a full-Lazy solution:
```
pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id")).to_series().collect()
# AttributeError: 'LazyFrame' object has no attribute 'to_series'
# and a LazyFrame has no value_counts attribute
```

I can do a full-Lazy column operation to yield a struct, but I'm not sure how I'm supposed to convert this back to a dataframe? I have seen `to_struct` but no equivalent `from_struct`?
```
pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id").value_counts()).collect()
test_class_id
--
struct[2]
{5,920358}
{7,15206290}
...
# taking 7 seconds (and the results match the counts in the other results)
```

I've seen the advice to do operations that lack a schema on a materialised DataFrame, I'm not sure why a `value_counts` can't determine the dtype of its column in a lazy context? https://pola-rs.github.io/polars-book/user-guide/lazy/schemas/#the-lazy-api-must-know-the-schema

Is there a fundamental reason why this doesn't exist (which would help my mental model)? Maybe it just hasn't been a priority yet? If I ask for the schema then I get a result:
```
pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id")).schema
{'test_class_id': Int64}
```

Possibly related to https://github.com/pola-rs/polars/issues/4670

Thanks for any guidance, given that a `value_counts` is a typical first operation when looking at unknown data I'd like to have a reasonable idea of the "right way" to go about solving this on a larger-than-RAM dataset that's consistent. If mixing lazy and eager is the right solution then fair enough, I'm just checking if I'm mixing something obvious.

**Comment by cmdlineluser** [comment]
There is a discord link in the readme: 
- https://github.com/pola-rs/polars#readme
- https://discord.gg/4UfP5cfBE7

You can [`.unnest`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.unnest.html#polars.DataFrame.unnest) struct columns:
```python

df = pl.DataFrame(dict(id=[1, 2, 3, 2, 2, 3])).lazy()

(df.select(pl.col("id").value_counts(sort=True))
    .unnest("id").collect())

# shape: (3, 2)
# ┌─────┬────────┐
# │ id  ┆ counts │
# │ --- ┆ ---    │
# │ i64 ┆ u32    │
# ╞═════╪════════╡
# │ 2   ┆ 3      │
# │ 3   ┆ 2      │
# │ 1   ┆ 1      │
# └─────┴────────┘
```
There's also [`.groupby().count`](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.lazyframe.groupby.LazyGroupBy.count.html#polars.lazyframe.groupby.LazyGroupBy.count)
```python
df.groupby("id").count().collect()

# shape: (3, 2)
# ┌─────┬───────┐
# │ id  ┆ count │
# │ --- ┆ ---   │
# │ i64 ┆ u32   │
# ╞═════╪═══════╡
# │ 2   ┆ 3     │
# │ 1   ┆ 1     │
# │ 3   ┆ 2     │
# └─────┴───────┘
```

**Comment by ianozsvald** [comment]
@cmdlineluser thanks for the quick response. I'd missed the Discord link, I'm in there now, thanks.

`unnest` works, I've now got `pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id").value_counts()).unnest("test_class_id") \
.sort(by='counts', descending=True).collect()` which gives an equivalent result (albeit a bit hard to read) - thanks.

Do you happen to know if there's a philosophical reason why a LazySeries can't exist? Presumably if it did, a `value_counts` would be easy to implement with a matching API to the eager version.

**Comment by ritchie46** [comment]
It isn't on `LazyFrame` as it is a typical EDA functionality. 

`LazyFrames` are not meant for exploration of data. On a `LazyFrame` you can do the groupby + count explicity. And then you probably also add other expressions that you need grouped in you query. This nudges you to do it in a single group pass.

**Comment by ianozsvald** [comment]
So I'll gently push back - I was doing EDA on a larger-than-RAM dataset and had to find an alternate way to express a Series `value_counts` on the LazyFrame. I solved it using a column-based `value_counts` (which makes a struct which needed unpacking) by hacking around:
```pl.scan_parquet(parquet_test_result + "/*.parquet").select(pl.col("test_class_id").value_counts()).unnest("test_class_id")```
or by using a `groupby` as you note.
So whilst technically I can get the answer that I want, I needed to figure out alternate ways to express my query. I was just surprised that I _could_ do it, but not with the obvious verb that an Eager dataframe provides. The fact that I have two ways to express code between an Eager and a Lazy dataframe makes my learning process a bit slower, that's all, so I'm posting these issues and asking in Discord to make sure I'm not missing anything obvious. Being aware of the performance considerations is certainly interesting, thanks for flagging that.

**Comment by ritchie46** [comment]
LazyFrame nodes are much more optimized and can take much more resources than expressions can. The expressions must run on much more context, need to share resources with other expressions and there are much more of them.

In general we want the LazyFrame API to encourage you to do the least amount of work and expressively write your query.
If you do a value_counts, you actually are doing a groupby + count.

But the method `value_counts` doesn't leave any space for other aggregations, and you probably didn't think of what happens under the hood. Making it more likely that you do a value_counts and a separate groupby. Doing 2 passes over the data and all previous lazy dag nodes.

Think of `value_counts` on `Series` as us being lenient. ;) It should be an explicit groupby + count. 

We are lenient because we understand the merit in EDA. 

Doing EDA on a lazyframe to view the results is a bad idea IMO. We want to encourage you to collect first and then do the interactive EDA as that caches the possibly very expensive LazyFrame Dag.

**Comment by MarcoGorelli** [comment]
thanks @ianozsvald for the request!

closing then as per the response (do a group-by + count on a lazyframe)
