### ISSUE TITLE
Rolling weighted mean and variance are incorrect

### ISSUE THREAD

**Issue by magarick** [pola-rs/polars#8941]
They divide by the window length instead of the sum of the weights or a function thereof for the variance.
This affects every language but here's a Python example because it's simple:
```python
s = pl.Series([0, 2, 4])
w = pl.Series([1, 2, 3])

s.rolling_mean(3, weights=w)
# Last value is 5.333333
s.rolling_var(3, weights=w)
# Last value is 37.333333

s.rolling_mean(3, weights=w / 10)
# Last value is 0.533333

s.rolling_var(3, weights=w / 10)
# Last value is 0.373333

```

For the mean, you get a result that's scaled by the mean value of the weights, but for the variance you get nonsense. For reference, the weighted mean should be:
$$\bar{x}^* = \frac{\sum_{i} w_i x_i}{\sum_i w_i} = 2.666667$$
And the variance, depending on if you use no weights, frequency weights, or reliability weights should be:

$$\frac{\sum_{i} w_i (x_i - \bar{x}^*)^2}{\sum_i w_i} = 2.222222$$ or

$$\frac{\sum_{i} w_i (x_i - \bar{x}^*)^2}{\sum_i w_i - 1} = 2.666667$$ or

$$\frac{\sum_{i} w_i (x_i - \bar{x}^*)^2}{\sum_i w_i - (\sum_i w_i^2)/(\sum_i w_i)} = 3.636364$$

See `compute_var_weights` and `compute_mean_weights` here:
https://github.com/pola-rs/polars/blob/ebc17a272a3e9406774863089835d356a870c932/polars/polars-arrow/src/kernels/rolling/no_nulls/mod.rs#L109

I noticed this while working on https://github.com/pola-rs/polars/issues/7999 and I can fix it along with that improvement or do it separately depending on how folks prefer things around here.

**Comment by mcrumiller** [comment]
So, based on the documentation, I would *not* expect polars to perform any normalization on the weights:

> An optional slice with the same length as the window that will be multiplied elementwise with the values in the window.

which means that, in your example of `s.rolling_mean(3, weights=w)`, I would expect the result to be `0*1 + 2*2 + 4*3 = 16`. We should either:

1) normalize the weights properly and document that normalization will be applied;
2) not normalize anything and leave that up to the user; or
3) add arguments to the functions to allow the user to pick a normalization procedure

**Comment by magarick** [comment]
That's a bug in the documentation because it's the definition of a rolling sum. And in fact, the `rolling_mean` and `rolling_sum` documentation are identical. So we should fix the documentation along with fixing the function. For variance, we will need parameters since there's more than one right way, but for a mean as long as the weights don't sum to 0 you're just dealing with a constant multiple of the operation done with normalized (to sum to 1) weights.

**Comment by ritchie46** [comment]
Why is that a bug in the documentation? It states we only multiply with the weights. Which is all we do.

**Comment by magarick** [comment]
> Why is that a bug in the documentation? It states we only multiply with the weights. Which is all we do.

Because the mean and sum have the same docstring, and they both describe what the rolling sum does. For the rolling mean what's actually done is a weighted sum divided by the count, which isn't what the docs say it'll do or the definition of a weighted mean.

**Comment by mcrumiller** [comment]
> It states we only multiply with the weights. Which is all we do.

It looks like it's multiplying by (weights/count), which is pretty nonstandard AFAIK. The weights should probably be normalized by the sum of the weights, or not at all.

**Comment by magarick** [comment]
For a sum: that's fine.
For a mean:
- If the weights don't sum to 0, normalizing them to sum to 1 and then taking a weighted sum with the normalized weights is equivalent to taking a weighted sum and dividing by the sum.
- Strictly speaking, negative weights aren't allowed, but nothing will break computationally if you use them and the weights don't sum to 0. And numpy allows it so maybe some people expect it?
- This is all bog-standard as
For variance:
- Here things get tricky depending on how you interpret the weights and I'd bet the "normal" biased definition is what most people most of the time expect and want. That is, center by weighted mean, take weighted sum of squares, divide by sum of weights.
- If you interpret the weights as _counts_ for each value, you could divide by sum of weights - 1 instead of the sum of the weights.
- But if they're not counts, you can use the "reliability weights" formula (see above and also wiki) for an unbiased estimate. The giganto caveat here and above is that this is assuming your observations come from the same distribution. If you're rolling, you're probably not dealing with IID samples so I'd say ignore this one entirely for now.
