### ISSUE TITLE
List assignment to a DataFrame column using with_columns()

### ISSUE THREAD

**Issue by Dixhom** [pola-rs/polars#8942]
### Problem description

I wish I could assign a list to a DataFrame column using with_columns() in polars.

The following code shows what I want to achieve. 

```
import polars as pl
import pandas as pd

df = pl.DataFrame({'a':[i/10 for i in range(100)]})
l = pd.qcut(df['a'].to_numpy(), 10, labels=range(10)).to_list()
df.with_columns(b=l)
```

Expected output: column b is pl.Series(l)
Actual output: object l is in every cell in the column b

In addition, if df['a'] is very long and the code is executed on Jupyter Notebook in VSCode, the app crashes.

Can someone add the feature please?

**Comment by alexander-beedie** [comment]
> Can someone add the feature please?

The feature already exists ;)
DataFrames are made up of Series, so you should add your list like so:
```python
df.with_columns( b=pl.Series(l) )
```

**Comment by Dixhom** [comment]
Thank you, alexander. I just thought I could assign a list _directly_ so I wanted a feature like that.

**Comment by alexander-beedie** [comment]
> Thank you, alexander. I just thought it would be nice to assign a list _directly_ so I wanted a feature like that.

No problem; note that you can also do this...
```python
df.with_columns( b=pl.lit(l) )
```
...and it'll still be converted to a Series; you can use whichever syntax you prefer (I find Series less ambiguous).
