### ISSUE TITLE
Polars silently dropping rows when number of rows larger than index type

### ISSUE THREAD

**Issue by mzjp2** [pola-rs/polars#8945]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars version: 0.17.14

Minimum reproducible example (on my system):

```python
df = pl.DataFrame({
    "idx": range(2**32 + 1024),
    "val": 0,
})

print(len(df))
```

gives `1024`.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "idx": range(2**32 + 1024),
    "val": 0,
})

print(len(df))
```

### Expected behavior

I expect the `len(df)` to be `2**32 + 1024` or an exception to be raised saying that my index type `pl.Uint32` is too small.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    Linux-5.4.206-1.el8.elrepo.x86_64-x86_64-with-glibc2.31
Python:      3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
We cannot do overflow checks that would be too expensive. As stated in the readme, you must use another polars version:

https://github.com/pola-rs/polars#going-big
