### ISSUE TITLE
Arithmetic with UInt x Int should not cast to float

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#8950]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

All (some?) operations with UInt and Int have Float64 outputs. IMO this is surprising; I expect integer operations to always have integer outputs or overflow.

Also, as shown in the example below, we might get silent loss of precision, something that's really surprising IMO.

### Reproducible example

```python
In [49]: (pl.Series([2**63+1], dtype=pl.UInt64) * pl.Series([1])).cast(pl.UInt64)
Out[49]:
shape: (1,)
Series: '' [u64]
[
	9223372036854775808
]

In [50]: (pl.Series([2**63+1], dtype=pl.UInt64) * pl.Series([1]).cast(pl.UInt8))
Out[50]:
shape: (1,)
Series: '' [u64]
[
	9223372036854775809
]
```

### Expected behavior

XInt x YInt operations should have ZInt output, or raise because of overflow.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.9.6 (default, Mar 10 2023, 20:16:38)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  0.3.2a5
deltalake:   0.9.0
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by ritchie46** [comment]
Its choosing between to unfortunate outcomes. The other is silent over/underflow. We follow numpy on this regard.

**Comment by jonashaag** [comment]
Interesting that NumPy decided to go this way. Are you open to discuss or do you want to stick to NumPy behaviour?

**Comment by ritchie46** [comment]
I rather go to float than having negative values go positive.

**Comment by jonashaag** [comment]
I agree, my proposal is to have it behave like UInt x UInt arithmetic:

```py
 [89]: (pl.Series([2**63+1], dtype=pl.UInt64) * pl.Series([1]).cast(pl.UInt8))
Out[89]:
shape: (1,)
Series: '' [u64]
[
	9223372036854775809
]

In [90]: (pl.Series([2**63+1], dtype=pl.UInt64) * pl.Series([2]).cast(pl.UInt8))
...
PanicException: attempt to multiply with overflow
```

**Comment by ritchie46** [comment]
Where does it panic? Our arithmetic doesn't do overflow checks in release mode?

**Comment by jonashaag** [comment]
Oh! This was in debug mode, good catch. Sorry! I think your point is solid in that case :-)
