### ISSUE TITLE
Allow passing only `schema` to `pl.struct`

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#8951]
### Problem description

If I want to create a `pl.struct` with guaranteed dtypes, currently I have to do this:

```py
pl.DataFrame({"x": [42], "y": [42]}).select(pl.struct("x", "y", schema={"x": pl.UInt8, "y": pl.UInt16}))
```

Would be nice to skip the `"x", "y"` and just write

```py
pl.struct(schema={"x": pl.UInt8, "y": pl.UInt16})
```

or even

```py
pl.struct({"x": pl.UInt8, "y": pl.UInt16})
```

**Comment by mcrumiller** [comment]
I agree that it's redundant, a schema by itself should be sufficient.
