### ISSUE TITLE
Constructing dataframe from list of empty-named series changes series' names

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8955]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If you construct a DataFrame from a list of empty-string named Series without supplying a schema, the individual series' names are changed.

### Reproducible example

```python
import polas as pl

### Create unnamed series
# both have name ''
s1 = pl.Series([1, 2, 3])
s2 = pl.Series([1, 2, 3])

print(s1)
```
```
shape: (3,)
Series: '' [i64]
[
        1
        2
        3
]
```
### Create dataframe and re-print s1
```ptyhon
pl.DataFrame([s1, s2])
print(s1)
```
```
shape: (3,)
Series: 'column_0' [i64]
[
        1
        2
        3
]
```

Name has changed to `column_0`, likewise `s2` changes to `column_1`.

### Expected behavior

Original series should not be modified in-place.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr 15 2023, 14:44:51) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   0.8.1
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by mcrumiller** [comment]
I'm not sure if this is actually a bug or an unexpected side-effect of what is proably a zero-copy move of the Series into the frame along with some automatic naming code happening.

**Comment by alexander-beedie** [comment]
Interesting; I found/fixed two related cases recently (https://github.com/pola-rs/polars/pull/8915).
Will track this one down too.
