### ISSUE TITLE
`flatten` changes behaviour if it's right after the `over` statement

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#8965]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

While looking at `over` and `flatten`, I realize `flatten` changes behaviour if used in a separate context.

Example:
```python

df = pl.DataFrame({
    'type': ['water','fire','water','earth']
})

# Test 1: Apply flatten before over => this returns the initial column
df.select(
    pl.col('type').implode().flatten().over('type')
)

┌───────┐
│ type  │
│ ---   │
│ str   │
╞═══════╡
│ water │
│ fire  │
│ water │
│ earth │
└───────┘

# Test 2 : Apply flatten after over => this reorders the column
df.select(
    pl.col('type').implode().over('type').flatten()
)

shape: (4, 1)
┌───────┐
│ type  │
│ ---   │
│ str   │
╞═══════╡
│ water │
│ water │
│ fire  │
│ earth │
└───────┘

# Test 3: Apply flatten after over, but in a separate statement => this 'explodes' the column
df.select(
    pl.col('type').implode().over('type')
).select(
    pl.col('type').flatten()
)

┌───────┐
│ type  │
│ ---   │
│ str   │
╞═══════╡
│ water │
│ water │
│ fire  │
│ water │
│ water │
│ earth │
└───────┘

```

I would expect Test 2 and Test 3 to return the same result, so that one operation applied on the same data returns the same result even if used in another context. 

Regarding Test 1 and Test 2, I see the value in reordering the column as that allows to put rows belonging to the same group next to each other. However it's not too clear that `flatten` would reorder the rows.

Here is one proposal for it:
- Test 1 returns the initial column as it does today (imploding and flattening is a no-op)
- Test 2 and 3 return the exploded column
- the `over` statement has an optional parameter `sort` that allows for sorting, similar to the PySpark Windows function: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Window.html
There was another discussion about this: https://github.com/pola-rs/polars/issues/8662

### Reproducible example

```python
# see above
```

### Expected behavior

See above

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.1.0
```

</details>

**Comment by ritchie46** [comment]
Fixed by #8992
