### ISSUE TITLE
Iterator over lazy groupby

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8966]
### Problem description

Is there a fundamental obstruction to being able to consume a lazy groupby as an iterator? I often wish I could do something like

```python
# Each `gdf` is a LazyFrame.
pl.concat(
    complicated_function(gdf, keys, other_lazyframe) for keys, gdf in ldf.groupby(by)
)
```
where `complicated_function` depends on the specific keys and some other lazyframes, but cannot be expressed in an agg context. (This works fine for eager DataFrames.) 

This is of course similar to a groupby-apply, but my understanding is that groupby-apply kills parallelism even when `complicated_function` involves only native polars functionality.

**Comment by warpedgeoid** [comment]
I often miss the way that Pandas allows iteration over groups. This request would seem to be a step in the right direction.

**Comment by leunga1000** [comment]
A note for people running into the same issue, other than calling the .collect() function on the lazy frame to make it a frame and then grouping by that (it is not quite as speedy), you might be able to use partition_by() with the over() window function.

**Comment by ritchie46** [comment]
This is something we will not support as there will be no benefit over `collect()`-ing first. A group-by can only produce a group once it has scanned and aggregated all the data. Which is what a collect is.

**Comment by jl3720** [comment]
I know this is closed but would a decent method to get this behavior to get the unique values of the group, and then filter upon each iteration for the unique value. E.g.
```
group_values = ldf.select(pl.col(by).unique()).collect()[by]
for val in group_values:
    group_ldf = ldf.filter(pl.col(by) == val)
    complicated_function(group_ldf, ...)
```
Would this filtering operation by terribly slow?

**Comment by seanv507** [comment]
> This is something we will not support as there will be no benefit over `collect()`-ing first. A group-by can only produce a group once it has scanned and aggregated all the data. Which is what a collect is.

I would claim a common use case is that the data is already sorted in the file or is available partitioned.
eg say the file is partitioned by day. then  it would be possible to process by days or weeks etc.

the point is to process a chunk containing a full day (or other hierarchy) together.
