### ISSUE TITLE
`.implode().first()` raises exception or hangs

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#8968]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I mistakingly used `.implode().first()` instead of `.implode().arr.first()` which caused a thread panic - which seems to be coming from arrow2?
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: 
OutOfSpec("offsets must not exceed the values length")',

/Users/user/.cargo/git/checkouts/arrow2-945af624853845da/b2922f4/src/array/list/mod.rs:88:61
```
One run raised a different error which I haven't been able to replicate:
```
thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
``` 
Other times - there is no exception, but it hangs whilst MEM% increases rapidly.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'type': ['water','fire','water','earth']
})

for _ in range(100):
    try:
        print(
           df.select(
              pl.col('type').implode().first().over('type')
           )
        ) 
    except:
        pass
```

### Expected behavior

No thread panic / hang.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Python:      3.10.9 (main, Jan 14 2023, 16:56:26)

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.8.2
matplotlib:  3.5.1
xlsx2csv:    0.8
xlsxwriter:  3.0.8
```

</details>

**Comment by lucazanna** [comment]
I just did the same with `implode.head()` and it hanged
