### ISSUE TITLE
Naming expressions resulting from functions

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8972]
Trying to find some consistency in the following chaos:

* Some functions result in an expression with no name (empty string), e.g. `date_range`.
* Some functions result in an expression with the name `'literal'`, e.g. `arange`, `repeat`.
* Some functions result in an expression with the name of the function, e.g. `count`.

And also:
* Some functions have a `name` argument that allows for controlling the resulting name. Others do not.

What is the logic that we should follow here? Some of my thoughts:
* Using `literal` as a column name does not feel great.
* Using the name of the function sometimes makes sense, like `count`. But as a user, I never like to rely on these kind of defaults.
* Empty string as a name often feels appropriate.
* Allowing a `name` argument does not feel very Polars. We'd have to add this to every single function to be consistent. Users should just call `alias` on the resulting expression.

**Comment by ritchie46** [comment]
I think from a debugging perspective it would be best to name them the function names. Emptry strings will collide and then it is hard to find the culprit.

Now "literal" also often collides, but at least it clear where that came from most of the time.

**Comment by stinodego** [comment]
Right, so I think we can follow the following logic:

* Most functions operate on one or multiple existing expressions. These will be named after the left-most expression.
* Some other functions create an entirely new expression, e.g. `time`, `date_range`, `repeat`, etc. These will be given a logical name based on the function itself. No more empty string / "literal".
* None of the functions will have a `name` argument - just call `alias` on the resulting expression if you want to override the existing name.

**Comment by ritchie46** [comment]
Sound good. Agree on the name/alias part as well.

**Comment by mcrumiller** [comment]
Just throwing this out there, another option is to use a global name cache to generate new names, like `series_4`, `series_5`, etc. Similar to how say Excel names their sheets. It's simple, obvious to the user, and doesn't require a lot of custom logic.

**Comment by stinodego** [comment]
From recent changes (https://github.com/pola-rs/polars/issues/13314, ...) it seems that the idea of naming expressions after their function name is no longer desired. 

So we'll name all expressions after the left-most expression input instead.

**Comment by stinodego** [comment]
I am closing this since all functions now follow this pattern, as far as I can tell. Functions that don't can be adjusted as a bug fix.
