### ISSUE TITLE
ComputeError: could not append {:?} to the builder

### ISSUE THREAD

**Issue by mvanaltvorst** [pola-rs/polars#8975]
I think this is a mix of two issues, one of which is incorrect string formatting.

I use `jupysql` which has a `res.PolarsDataFrame()` method. When I call this, I get the following error:

`ComputeError: could not append {:?} to the builder; make sure that all rows have the same schema or consider increasing "schema_inference_length"`

I can work around the issue by doing `pl.DataFrame(res.DataFrame())` (an intermittent Pandas step). This leads me to believe this is mostly a `jupysql` and not a `polars` issue. Still, I believe the error formatting should be fixed.

**Comment by ritchie46** [comment]
Can you create a minimal example in python? I don't know what jupysql does.

**Comment by 2-5** [comment]
Is it possible that you have a dtype overflow in your data?

Because I encountered this error message in that case.

https://github.com/pola-rs/polars/issues/8902

**Comment by mvanaltvorst** [comment]
That could be! Unfortunately I cannot reproduce this issue except for with jupysql and a specific 10GB dataframe. I'll try to see if I can figure out the problem now that I know it's potentially overflow related.

**Comment by ritchie46** [comment]
Found an mwe in https://github.com/pola-rs/polars/issues/8902
