### ISSUE TITLE
`dtype` argument for `Series` does not work correctly on float values

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8985]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It seems like the `dtype` argument is simply disregarded when the passed values are floats.

### Reproducible example

```python
import polars as pl

s1 = pl.Series([1.0, 1.2], dtype=pl.Int32)
s2 = pl.Series([1.0, 1.2], dtype=pl.Date)
```

Both result in:
```
shape: (2,)
Series: '' [f64]
[
        1.0
        1.2
]
```

### Expected behavior

Values should be cast to the proper dtype, or raise an error if casting would result in unexpected behaviour.

### Installed versions

master

**Comment by stinodego** [comment]
Might be a case for Doctor Constructor @alexander-beedie ? 😄

**Comment by alexander-beedie** [comment]
> Might be a case for Doctor Constructor @alexander-beedie ? 😄 

Ahaha... no problem; can take a look shortly ;)
