### ISSUE TITLE
python 0.18 release

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#8987]
I think we should go for a 0.18 release after 0.17.15. There are some things that block development currently that should be out of the way.

Things I want to break:

- [x] Magic in window functions regarding to flattening of groups. This must be explicit as it cannot be inferred correctly once people have multiple implodes and operations that change the number of elements in a group (unique, slice).
- [x] `.arr` namespace must be renamed to `.list` namespace. This opens up the `.arr` namespace for the new `Array` datatype.
- [ ] Hard error on data that hasn't got a sorted flag where it should
- [x] Simplify timezone handling, the PR's already ready by @MarcoGorelli 

Other things?

**Comment by ritchie46** [comment]
> That would be a hard break - it is not deprecated yet (was not possible due to the existing Expr.list). I'm OK with that, just a heads up.

I know, but there wasn't a smooth break options without waiting a full release cycle. I think we should document this very clearly in the release guide.

**Comment by MarcoGorelli** [comment]
looks like https://github.com/pola-rs/polars/pull/8712 didn't make it into 0.17.15

OK to just enforce as breaking change in 0.18 then?

**Comment by ritchie46** [comment]
> OK to just enforce as breaking change in 0.18 then?

Yeap, sorry bout that.

Merging of breaking changes can begin. :)

**Comment by stinodego** [comment]
I'd like to go ahead with https://github.com/pola-rs/polars/pull/7746 - though I need to do some final checks before I am confident in merging that.

Also I think we should set `date_range` to `eager=False`. That future warning is really annoying 😄 same with any other functions with an eager flag.

**Comment by chitralverma** [comment]
@ritchie46  what about cloud object store support on the missing paths?
This can be a pretty essential feature before 1.0?

**Comment by ritchie46** [comment]
> @ritchie46 @stinodego what about cloud object store support on the missing paths? This can be a pretty essential feature before 1.0?

What do you mean? Should we break any functionality there?

**Comment by ritchie46** [comment]
Doesn't change anything on the python side. And we can always make it work with rayon. It just means we block on that thread. Our whole design is around threading on rayon and not on tokio. And we also don't regret it, so nothing changes on that part. 

We shall do async differently.

**Comment by chitralverma** [comment]
> Doesn't change anything on the python side. And we can always make it work with rayon. It just means we block on that thread. Our whole design is around threading on rayon and not on tokio. And we also don't regret it, so nothing changes on that part.
> 
> We shall do async differently.

Ok, let me check this out. what can be done for this.

**Comment by chitralverma** [comment]
as far as API changes go, can we take this one up https://github.com/pola-rs/polars/issues/8646.

there are some suggestions on the ticket.

**Comment by stinodego** [comment]
> as far as API changes go, can we take this one up #8646.

I'll pick that up as soon as I can, but it can be done in a non-breaking way. So it doesn't need to be part of 0.18.0 per se.

**Comment by avimallu** [comment]
From the perspective of accuracy, probably resolve https://github.com/pola-rs/polars/issues/8183 and https://github.com/pola-rs/polars/issues/8182, since they are for sure errors that don't need discussion to align on? More important for a 1.0 release, and I think that's what Polars is gearing up for?

**Comment by mcrumiller** [comment]
**Proposal**: enable string cache by default.

The string cache is constantly mucking people up all over StackOverflow and here. It is **very rarely** the case that someone will have dataframes with the same categorical label but desire them to be treated as different items. In fact, I can't think of *any* scenario in which that would be true.

I'm assuming using a global string cache is somehow less performant, but I think that, even if that is the case, we should enable it by default, simply to make categoricals more accessible to the public.

**Comment by stinodego** [comment]
Not an unreasonable request. Can you make an issue for this? I don't think it needs to be part of 0.18.0 per se, but it's worth discussing.

**Comment by ghuls** [comment]
Another nice feature related to categoricals would be to have a function for converting categoricals created without string cache (created with or different ones) to a homogenious one. At the moment I have have to enable the string global cache in a library, so
different functions that read files get created with the same string cache, but there is no way to enforce that the code that is calling the function is not disabling the string cache inbetween.

PyArrow has `unify_dictionaries` for it: https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.unify_dictionaries I believe the functionality is already in rust Polars as it is able to work with PyArrow dictionaries, which require remapping most of the time.

**Comment by stinodego** [comment]
@ghuls Could you please make an issue for this? I'm closing this as 0.18 has been released!
