### ISSUE TITLE
make `time_zone` attribute available on column

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#8989]
### Problem description

I wish i could access the timezone of a column the same way i can access its time unit. 
Currently, i can access the `time_unit` attribute as:
```python
df['time_column'].time_unit
```
It would be great if the `time_zone` attribute was exposed in a similar way. As in:
```python
df['time_column'].time_zone
```

Example:
```python
>>> import polars as pl
>>> from datetime import datetime 
>>> df = pl.DataFrame(
...         {
...             "delivery_datetime": pl.date_range(
...                 start=datetime.fromisoformat("2023-01-01T00:00:00+00:00"),
...                 end=datetime.fromisoformat("2023-04-01T00:00:00+00:00"),
...                 interval="1h",
...             ),
...         }
...     )
<stdin>:3: FutureWarning: In a future version of polars, the default will change from `lazy=False` to `eager=False`. To silence this warning, please:
- set `eager=False` to opt in to the new default behaviour, or
- set `eager=True` to retain the old one.
>>> df["delivery_datetime"].time_unit
'us'
>>> df["delivery_datetime"].time_zone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Series' object has no attribute 'time_zone'
>>> pl.__version__
'0.17.14' 
```

**Comment by MarcoGorelli** [comment]
hey @tim-habitat 

you can do
```python
In [6]: df['delivery_datetime'].dtype.time_zone
Out[6]: 'UTC'
```

To be honest I'm not sure I see the use of `df['delivery_datetime'].time_unit` when there's already `.dtype.time_unit`. Maybe it should be deprecated, both to avoid duplication, and to help with discoverability of how to get the time zone?

**Comment by stinodego** [comment]
I would argue the other way - `Series.time_unit` should not exist. It is a property of the dtype, not of the Series.

For now, I would advise using the `dtype` attribute:

```python
df["delivery_datetime"].dtype.time_zone
```

**Comment by MarcoGorelli** [comment]
😄 looks like we left the same comment at the same, and that we're in agreement. let's do this then

**Comment by stinodego** [comment]
Will you do the honors? :)

**Comment by MarcoGorelli** [comment]
could do - or @tim-habitat , @mcrumiller - are either of you interested in contributing this? No worries if not, I can do this later
