### ISSUE TITLE
`.is_duplicated()` and `.is_unique()` give same results

### ISSUE THREAD

**Issue by dschoenleber** [pola-rs/polars#899]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.8.6

#### What operating system are you using polars on?

macOS 11.4

#### Describe your bug.

`.is_duplicated()` and `.is_unique()` give the same results.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import numpy as np

dataset = pl.read_csv("https://j.mp/iriscsv")
# the below selection provides a minimal example: the first two rows are duplicates, the last two unique
dataset[[9, 34, 1, 2]]
# out:
```
|   sepal_length |   sepal_width |   petal_length |   petal_width | species   |
|---------------:|--------------:|---------------:|--------------:|:----------|
|            4.9 |           3.1 |            1.5 |           0.1 | setosa    |
|            4.9 |           3.1 |            1.5 |           0.1 | setosa    |
|            4.9 |           3   |            1.4 |           0.2 | setosa    |
|            4.7 |           3.2 |            1.3 |           0.2 | setosa    |

#### What is the actual behavior?

```python
dataset[[9, 34, 1, 2]].is_duplicated().to_numpy()
# out: array([False, False,  True,  True])
dataset[[9, 34, 1, 2]].is_unique().to_numpy()
# out: array([False, False,  True,  True])
```

#### What is the expected behavior?

```python
dataset[[9, 34, 1, 2]].is_duplicated().to_numpy()
# out: array([True, True,  False,  False])
dataset[[9, 34, 1, 2]].is_unique().to_numpy()
# out: array([False, False,  True,  True])
```

**Comment by ritchie46** [comment]
Fixed and releasdd
