### ISSUE TITLE
OOM errors with scan_parquet > limit > collect

### ISSUE THREAD

**Issue by gwvr** [pola-rs/polars#9001]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm getting to grips with Polars, working towards a talk with @ianozsvald, using the UK MOT vehicle test dataset (~635m rows, 854 partitions on disk, dataset explained [here](https://github.com/pola-rs/polars/issues/8925)).

When prototyping code with Pandas, Dask or PySpark I would often use .head() or .limit(), in order to eyeball data at different stages in a method chained process. With Dask & PySpark I usually expect to be able to do this with large data, without issue. With Polars, I'm finding that I'm getting bitten by OOM errors, and am trying to understand why.

### Reproducible example

I started with

`pl.scan_parquet(path).limit(5).collect()` - results in OOM

Then I tried

`pl.scan_parquet(path, n_rows=100).limit(5).collect()` - completes in 1.9s

Having discovered streaming, I found that to be much faster

`pl.scan_parquet(path, n_rows=100).limit(5).collect(streaming=True)` - completes in 85ms

I then tried increasing n_rows on scan, eventually reaching a number larger than the row count of our dataset

`pl.scan_parquet(path, n_rows=1000000000).limit(5).collect(streaming=True)` - completes in 110ms

But without passing n_rows

`pl.scan_parquet(path).limit(5).collect(streaming=True)` - results in OOM

For completeness

`pl.scan_parquet(path, n_rows=1000000000).limit(5).collect()` - results in OOM

### Expected behavior

I expected the following to "just work".

```
pl.scan_parquet(scan_path).limit(5).collect()
```

The outcomes above raise a few questions:

- Is OOM error expected with (large) LazyFrame.limit(5) ?
- Why would I not want to use streaming=True ? (I'm aware that the functionality behind this may be incomplete)
- Why does scanning n_rows larger than my dataset prevent OOM error in conjunction with streaming=True ?
- Are there any plans for a use_pyarrow option to scan_parquet, as with read_parquet?

I have discovered LazyFrame.fetch() and can see how that would be useful. I'm also aware that df.limit is an alias to df.head.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    Linux-6.0.0-0.deb11.2-amd64-x86_64-with-glibc2.31
Python:      3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you share the file? The limit should be pushed down in all cases.

**Comment by ianozsvald** [comment]
@ritchie46 whilst the data is open, it is processed from a UK public source (driving vehicle test status as CSV files, processed by us through Dask due to varying CSV standards over the years). The output is circa 855 parquet files and 16GB in total, snappy compressed, exported using the Dask defaults.
Currently we haven't shared this anywhere. I'll try to zip it into one file and stick it into Dropbox (which might take some hours), I'll message back if successful.

**Comment by ritchie46** [comment]
Wait, so the `path` has got a glob string? E.g. you are not reading a single file, but them all at once. 

In any case, if I got the data, can you also include a MWE? :)

**Comment by ianozsvald** [comment]
@ritchie46 I'll let @gwvr comment on the above and provide a working example but yes, I think there's a glob string. Maybe you can give us a steer on what Polars expects to see if hundreds of parquet files are not a suitable input?

Here's the zip (14GB) of the circa 800+ parquet files (generated by Dask): https://www.dropbox.com/s/7wq2og6vig5zxbd/test_result.parquet.zip?dl=0

I can leave that up for a couple of weeks and it is public data, but it'd be good to delete that link in a while.

**Comment by ritchie46** [comment]
> @ritchie46 I'll let @gwvr comment on the above and provide a working example but yes, I think there's a glob string. Maybe you can give us a steer on what Polars expects to see if hundreds of parquet files are not a suitable input?
> 
> Here's the zip (14GB) of the circa 800+ parquet files (generated by Dask): https://www.dropbox.com/s/7wq2og6vig5zxbd/test_result.parquet.zip?dl=0
> 
> I can leave that up for a couple of weeks and it is public data, but it'd be good to delete that link in a while.

I will have to look. We should not OOM if we apply a limit. Will come back on this. Thanks for the data.

**Comment by gwvr** [comment]
Thanks @ritchie46 

> Wait, so the `path` has got a glob string? E.g. you are not reading a single file, but them all at once.

That is correct. The path string for pl.scan_parquet is `test_result.parquet/*.parquet` (854 items, totalling 16.7 GB).

If passing the path `test_result.parquet`, Dask sees this as one parquet dataset with 854 partitions, and PySpark reports 169 partitions (not sure why this is, but maybe relates to row group count?).

`pl.read_parquet('test_result.parquet', use_pyarrow=True, pyarrow_options = {'filters':...) )` also allows me to read the dataset without a wildcard path. The pyarrow filters can be helpful in avoiding OOM.

I could create a synthetic MWE, but hopefully you're able to reproduce the issue with the dataset that Ian shared above. Let us know if there's anything you need in order to reproduce this behaviour.

**Comment by ritchie46** [comment]
We indeed didn't apply the `limit` within the UNION node. This is fixed in #9018.

**Comment by ritchie46** [comment]
And to answer you questions.

> Is OOM error expected with (large) LazyFrame.limit(5) ?

NO! Fixed now. :)

> Why would I not want to use streaming=True ? (I'm aware that the functionality behind this may be incomplete)

The engine is in alpha. Though if you deal with large datasets, it might already be worth it for you. 

- Default engine: speed optimized and versatile
- Streaming engine: optimized for dealing with larger than RAM datasets, but supports a subset of the functionality. 

Note that does engines can be used hybridly. If you `collect(streaming=True)` we will do as much streaming as possible and operations that cannot be done, will be executed on the default engine.

> Why does scanning n_rows larger than my dataset prevent OOM error in conjunction with streaming=True ?

Doesn't matter, an implementation detail. It is fixed now.
   
   
> Are there any plans for a use_pyarrow option to scan_parquet, as with read_parquet?

We already have that in `scan_pyarrow_dataset`. This accepts a pyarrow dataset and pushes optimizations in the pyarrow scanner.

**Comment by gwvr** [comment]
Thanks @ritchie46 , for the fix and for the answers.

I'll run my test cases again once you've tagged the next release.
I've just tested `scan_pyarrow_dataset` with our parquet dataset and I prefer it to `scan_parquet` - will watch this to see how it matures.

**Comment by ritchie46** [comment]
Polars 0.18.0 is released. Give it a spin. It should work now.

**Comment by gwvr** [comment]
@ritchie46 I've re-run my test cases with polars 0.18.3, with the following results:

`pl.scan_parquet(scan_path).limit(5).collect()` - previously OOM, now fixed. 106ms

`pl.scan_parquet(scan_path, n_rows=100).limit(5).collect()` - now faster, 40ms vs 1.9s previously

`pl.scan_parquet(scan_path, n_rows=100).limit(5).collect(streaming=True)` - works but takes 16s (previously took 85ms)

`pl.scan_parquet(scan_path, n_rows=1000000000).limit(5).collect(streaming=True)` - OOM, previously completed successfully in 110ms

`pl.scan_parquet(scan_path).limit(5).collect(streaming=True)` - previously OOM, now fixed. 76ms

`pl.scan_parquet(scan_path, n_rows=1000000000).limit(5).collect()` - OOM, as before

Good to see the original bug fixed, and the performance improvement with a couple of the other operations above.

Obviously the OOM errors with `pl.scan_parquet(scan_path, n_rows=1000000000)` are edge cases that only came about through testing, and nobody should need this in the real world. Note the regression with streaming, which did complete successfully with polars 0.17.14.

IMHO the performance regression with `pl.scan_parquet(scan_path, n_rows=100).limit(5).collect(streaming=True)` is more relevant to real world usage, and probably worth investigating.

**Comment by ianozsvald** [comment]
Hi @ritchie46. I've rerun the above with `0.18.15` today. One more test passes on my machine that crashed on @gwvr 's machine (he has no SWAP, I have 96GB SWAP). The test that failed on Giles' machine with an OOM still fails on mine.

The failure - the last case - was pretty evil. My machine locked up, Activity Monitor was on screen and it showed 64GB RAM and >64GB SWAP, I could barely move my mouse, Jupyter Lab reset the kernel and Firefox crashed but the underlying Polars process seemed to run on, I couldn't use the terminal or swap to a bare console, I had no control. I gave it 10 minutes and then performed a hard reboot. I haven't run it again (e.g. at the terminal in a Python shell outside of Jupyter) and I know that Giles noted that it is a bit of a pathological expression, but maybe the `limit=5` expression isn't being pushed up and that's an easy fix?

Results from rerunning Giles' tests:

```
path = "/home/ian/workspace/personal/mot_pandas2_polars_dask/test_result.parquet/*"
# Same data as we supplied using dropbox, that link is still valid if you need it
%time pl.scan_parquet(path).limit(5).collect()
#CPU times: user 348 ms, sys: 238 ms, total: 585 ms
#Wall time: 805 ms # similar to Giles' last result

%time pl.scan_parquet(path, n_rows=100).limit(5).collect()
#CPU times: user 64.4 ms, sys: 41.1 ms, total: 106 ms
#Wall time: 88.5 ms # similar to Giles' last result

%time pl.scan_parquet(path, n_rows=100).limit(5).collect(streaming=True)
#CPU times: user 13.9 s, sys: 9.05 s, total: 22.9 s
#Wall time: 4.04 s # faster than Giles' last result

%time pl.scan_parquet(path, n_rows=1000000000).limit(5).collect(streaming=True)
# did complete but used all RAM 64GB and circa 30GB swap, so better than Giles' result but something's not right
#CPU times: user 4min 37s, sys: 3min 3s, total: 7min 41s
#Wall time: 1min 18s

%time pl.scan_parquet(path).limit(5).collect(streaming=True)
#CPU times: user 416 ms, sys: 81.6 ms, total: 498 ms
#Wall time: 135 ms # similar to Giles' last result

# Can't run as it causes machine to lock-up and requires a hard reboot
#pl.scan_parquet(path, n_rows=1000000000).limit(5).collect()
```

**Comment by ritchie46** [comment]
Right, so we must look at the
