### ISSUE TITLE
As of Join Strategy nearest

### ISSUE THREAD

**Issue by linusheinz** [pola-rs/polars#9003]
### Problem description

Hey :)

Thanks for such a great library.

The join_asof function is currently missing a AsofJoinStrategy = 'nearest', analogous to pandas direction="nearest".

**Comment by cmdlineluser** [comment]
Yes, someone was looking to implement this a while back  https://github.com/pola-rs/polars/issues/5710

Currently you need to run it twice and compare the distances: https://stackoverflow.com/a/72708292

**Comment by mcrumiller** [comment]
I have a PR incoming for this.
