### ISSUE TITLE
Cannot use `with_context` with output of `scan_*` functions

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#9006]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following raises an error:

```python
import polars as pl

df1 = pl.LazyFrame({"A": [1]})
pl.DataFrame({"B": [1]}).write_csv("test.csv")

# This fails with PanicException: called `Option::unwrap()` on a `None` value
df1.with_context(pl.scan_csv("test.csv")).collect()

# This succeeds
df1.with_context(pl.scan_csv("test.csv").collect().lazy()).collect()

# Reversing the order also succeeds 
pl.scan_csv("test.csv").with_context(df1).collect()
```

The same error arises for `scan_parquet` and `scan_ipc`.

### Reproducible example

```python
import polars as pl

df1 = pl.LazyFrame({"A": [1]})
pl.DataFrame({"B": [1]}).write_csv("test.csv")

# This fails with PanicException: called `Option::unwrap()` on a `None` value
df1.with_context(pl.scan_csv("test.csv")).collect()
```

### Expected behavior

Code should run regardless of the source of the lazyframe.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.15
Index type:  UInt32
Platform:    macOS-13.2-arm64-arm-64bit
Python:      3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by daviskirk** [comment]
I have this as well, interestingly only for polars  > 0.19.6.  Since this issue is older I'm not sure if it's really the same issue, or if https://github.com/pola-rs/polars/issues/12416 also came up in newer versions.

**Comment by stinodego** [comment]
`LazyFrame.with_context` will be deprecated with the release of `1.0.0` (https://github.com/pola-rs/polars/pull/16860). We will not fix any bugs associated with it.

Please use `pl.concat(..., how="horizontal")` instead to combine LazyFrames into a single context.
