### ISSUE TITLE
`arange` and `date_range` expressions differ in dimensions

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9019]
Consider the following behaviour for `arange`:

```
>>> pl.select(pl.arange(0, 3))
shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ i64     │
╞═════════╡
│ 0       │
│ 1       │
│ 2       │
└─────────┘
```

And compare it with the behaviour of `date_range`:

```
>>> pl.select(pl.date_range(date(2022,1,1), date(2022,1, 3)))
shape: (1, 1)
┌───────────────────────────────────┐
│ literal                           │
│ ---                               │
│ list[date]                        │
╞═══════════════════════════════════╡
│ [2022-01-01, 2022-01-02, 2022-01… │
└───────────────────────────────────┘
```

`arange` creates an expression with length `n`, while `date_range` creates a list-type expression with a single item: a list of length `n`.

To me, the `date_range` behaviour is surprising. For `arange`, the eager and lazy variants are similar in dimension, while for `date_range`, they are completely different (requires explode/implode to convert between the two).

What's the reason `date_range` behaves this way in lazy? And should we have the same behaviour for `arange`?

**Comment by ritchie46** [comment]
The idea is that you can create a date range per row. Imagine having a column `start` and column `offset`. Then you create a range per element.

We tried to infer the behavior earlier, but this turns out to lead to inconsistencies, so I think we should accept a keyword that defines if we want to evaluate a single element or a column of elements.

**Comment by ritchie46** [comment]
> For consistency, perhaps the last one should be

Yeap, let's do that.

**Comment by MarcoGorelli** [comment]
is an extra keyword necessary? can't you implode/explode your way into the output you want
```python
In [31]: pl.select(pl.arange(0, 3, eager=True).implode())
Out[31]:
shape: (1, 1)
┌───────────┐
│ arange    │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [0, 1, 2] │
└───────────┘

In [32]: pl.select(pl.arange(0, 3, eager=True).implode().explode())
Out[32]:
shape: (3, 1)
┌────────┐
│ arange │
│ ---    │
│ i64    │
╞════════╡
│ 0      │
│ 1      │
│ 2      │
└────────┘
```
?

**Comment by stinodego** [comment]
Your examples are strange to me because you're using `eager=True` in a `select` context.

But yes, if you implode the result of `eager=True` then you get the same output as when running `eager=False`. But that's the problem - the `eager` flag changes the behaviour. That flag should only change the compute strategy.

**Comment by ritchie46** [comment]
I agree with @stinodego. `eager` shouldn't change behavior. I think we need an extra argument.

**Comment by josh** [comment]
The other bug is that the lazy dtype is wrong.

```python
ldf = pl.LazyFrame().select(pl.date_range(date(2022,1,1), date(2022,1, 3), eager=False))
ldf.schema # {'literal': Date}
df = ldf.collect()
df.schema # {'date': List(Date)}
```

**Comment by MarcoGorelli** [comment]
thanks @josh - I'll check when I'm home, but I'd like to think that that would be fixed by https://github.com/pola-rs/polars/pull/8591

---

Regarding the extra keyword (say, `orientation`), what would the expected output be for
```python
>>> df
shape: (3, 2)
┌────────────┬────────────┐
│ start      ┆ end        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2020-01-01 ┆ 2020-01-03 │
│ 2020-01-02 ┆ 2020-01-04 │
│ 2020-01-03 ┆ 2020-01-05 │
└────────────┴────────────┘
>>> df.with_columns(pl.date_range(pl.col('start'), pl.col('end'), orientation='vertical'))
```
? Should it just raise in that case?

**Comment by stinodego** [comment]
Idea: let's have a pair of methods:

* `date_range`: Generate a single date range column
* `date_ranges`: Generate a date range for each row of the input columns.

This solves a bunch of things: we now have a single output type per method, and the naming makes it very clear what to expect.

**Comment by MarcoGorelli** [comment]
Nice! The output dtype could still change depending on the `time_zone` argument, but at least it would resolve the `List(T)` vs `T` issue. So, 👍 to that

**Comment by MarcoGorelli** [comment]
@stinodego is this something you're already working on? If not, I have some time today, could give it a go

**Comment by stinodego** [comment]
Just working on it right now, actually! But I am starting with `arange` - feel free to take up `date_range` / `time_range` if you want!

**Comment by MarcoGorelli** [comment]
The only use cases I can think of for `date_ranges` / `time_ranges` / `aranges` is when you have a `DataFrame` where one column is `start` and another is `stop`

In which case, I'd suggest that `date_ranges` / `time_ranges` / `aranges` don't have an `eager` argument, and only return expressions.
If a use case for `time_ranges(..., eager=True)` emerges, which isn't covered by `time_range(...).implode()`, then we can always add it later

**Comment by stinodego** [comment]
Actually you can have this:

```python
start = pl.Series([1,2,3])
pl.int_ranges(start, 5, eager=True)  # -> Returns a Series with multiple ranges
```

So it should have an `eager` argument.
