### ISSUE TITLE
Specify first character of CSV header row

### ISSUE THREAD

**Issue by tikkanz** [pola-rs/polars#9030]
### Problem description

It would be great if it were possible to specify a character(/string) to prefix to the header line of a CSV file that Polars writes. This would likely be an additional option for `write_csv` called something like `header_prefix` with a default value of None or empty string.

The minimally sufficient solution for my use case would be the ability to specify a single character. 
The ability to specify a string instead would potentially handle multi-character comment indicators, and if it were possible to include newlines, it would be possible to add custom metadata/comments to the top of a CSV file.

### Background
I need to write CSV files that are the input for an application. That application expects the header line (with the column names) to be the last "commented" line in the file, prior to the data. Currently I write the CSV file using polars and then edit it to add a `#` to the start of the first line.

```
# this is an example csv input file
# it has one or more commented lines at the top
# the last commented line specifies the column headers
#id,name,age,weight
1,Neil,24,75.3
2,Jane,33,68.9
```

**Comment by mcrumiller** [comment]
This is a sufficiently specific request that it should definitely not go into the API in my opinion. Use one of the workarounds suggested above.

**Comment by ritchie46** [comment]
This is something you can perfectly do yourself indeed. We shouldn't clutter our API with stuff that should be in the programmers domain.

**Comment by tikkanz** [comment]
Thanks to those who suggested alternative solutions to the issue. Happy with the decision.
