### ISSUE TITLE
Add statistical methods to the List namespace (`median`, `std`, `var`)

### ISSUE THREAD

**Issue by wanderer1988** [pola-rs/polars#9033]
I wanted to do some statistics over lists in a Dataframe, and realized, that it is not implemented in a straightforward way. 

To give an example, let's assume this DataFrame with a nested list in a column:
```python
df=pl.DataFrame(
    {"values":[[1.2,1.5,1.7,1.3]]}
)
```

When I try to calculate this
```python
df.with_columns([
    pl.col("values").arr.mean().suffix(" mean"),
    pl.col("values").arr.median().suffix(" median"),
    pl.col("values").arr.std().suffix(" std")
])
```
I get an AttributeError, because mean() is implemented in this context, but median() and std() are not. To get the result I want I currently have to do this workaround:
```python
df.with_columns([
    pl.col("values").arr.mean().suffix(" mean"),
    pl.col("values").arr.eval(pl.element().median()).explode().suffix(" median"),
    pl.col("values").arr.eval(pl.element().std()).explode().suffix(" std")
])
```
(I don't know if there is an easier way.)

I would say this is an inconsistency, and all statistical methods, that are available elsewhere should also be availabe in the List context.

**Comment by wanderer1988** [comment]
Sorry, I forgot to add the "enhancement" tag when I posted it, but can't find how to add it now.

**Comment by stinodego** [comment]
An implementation is welcome!

**Comment by ion-elgreco** [comment]
I can pick this up after Christmas 🎄

**Comment by ion-elgreco** [comment]
@stinodego we can close this one now :)
