### ISSUE TITLE
Add another example of `join_asof(...)`, which shows the usage of `by` arg

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#9045]
### Problem description

I wish there was another example on this page: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.join_asof.html

I wish it gave an example of the join, showing how the `by`/`by_left`/`by_right` args work. It's reasonably clear from the explanation, but an example would solidify it better.

**Comment by ritchie46** [comment]
Can you open a PR on this? I mean it's a small thing to do and slightly more effort than opening an issue. 

Don't get me wrong, you are free to open issues, but if we have tons of these super small issues. It clutters our issue board and takes a little bit of time of everybody working on this project. I will close this. Feel free to open a PR with the changes you'd like to see in the docstring.

**Comment by NedJWestern** [comment]
Perhaps this can be closed then?

**Comment by MarcoGorelli** [comment]
yup thanks
