### ISSUE TITLE
Build of dependency fails on PYPY

### ISSUE THREAD

**Issue by thedroppedpocket** [pola-rs/polars#9055]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

  When installing in PYPY environment, polars fails to build all dependencies because of an error in the hashbrown dependency? 

     error: could not compile `hashbrown` due to 10 previous errors
      warning: build failed, waiting for other jobs to finish...
      ≡ƒÆÑ maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--release" "--manifest-path" "C:\\Users\\wyatt\\AppData\\Local\\Temp\\pip-install-wa9ikhia\\polars_6ad95fa6161b404c93920250af0e69c2\\Cargo.toml" "--message-format" "json" "--lib"`
      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:15:5
         |
      15 | /     feature(
      16 | |         test,
      17 | |         core_intrinsics,
      18 | |         dropck_eyepatch,
      ...  |
      25 | |         build_hasher_simple_hash_one
      26 | |     )
         | |_____^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:16:9
         |
      16 |         test,
         |         ^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:17:9
         |
      17 |         core_intrinsics,
         |         ^^^^^^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:20:9
         |
      20 |         extend_one,
         |         ^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:21:9
         |
      21 |         allocator_api,
         |         ^^^^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:22:9
         |
      22 |         slice_ptr_get,
         |         ^^^^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:23:9
         |
      23 |         nonnull_slice_from_raw_parts,
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:24:9
         |
      24 |         maybe_uninit_array_assume_init,
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      error[E0554]: `#![feature]` may not be used on the stable release channel
        --> C:\Users\wyatt\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.13.2\src\lib.rs:25:9
         |
      25 |         build_hasher_simple_hash_one
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      error: aborting due to 9 previous errors

      For more information about this error, try `rustc --explain E0554`.

      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\Program Files\\pypy3.9-v7.3.11-win64\\pypy.exe', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for polars
Failed to build polars
ERROR: Could not build wheels for polars, which is required to install pyproject.toml-based projects

### Reproducible example

```python
create pypy environment
run pypy3 -mpip install polars
see error above
```

### Expected behavior

whether this is a problem with hashbrown or something wrong with my environment, this error should have a workaround, what am I missing?

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by thedroppedpocket** [comment]
This is a 64bit vs 32bit issue and fixing my environment will fix issue

**Comment by abhishekbhakat** [comment]
@ritchie46 which exact version of rust we should be using ? I tried the latest nightly and it still fails.
I'm on a mac btw.

**Comment by ritchie46** [comment]
See https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml
