### ISSUE TITLE
Series(strict=True) ignored

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#9067]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

[Also reported here](https://github.com/pola-rs/polars/issues/7737#issuecomment-1565687071).

```py
In [3]: pl.Series(["a"], dtype=pl.UInt64, strict=True)
Out[2]:
shape: (1,)
Series: '' [str]
[
	"a"
]
```

### Reproducible example

```python
pl.Series(["a"], dtype=pl.UInt64, strict=True)
```

### Expected behavior

Should raise

### Installed versions

`main` from today

**Comment by CloseChoice** [comment]
Not sure if this is bug. `strict` means that an error is thrown on a numeric overflow. Types
I would argue that `strict` is kind of misleading but that would be a breaking change and once introduced we probably should not change this anymore.

We should specify if we want to ignore the in dtype specified type as we do now or if we want to raise an error in this case. Either way, we should add this case to the documentation of [`dtype`](https://github.com/pola-rs/polars/blob/main/py-polars/polars/series/series.py#L162)
