### ISSUE TITLE
is_in returns True for int/float where it shouldn't, e.g. [5].is_in[5.8].

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9070]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Found after reading through #9068. My guess is that the float array is being downcast to the int array and then compared, whereas we should probably be *up*casting instead.

### Reproducible example

```python
import polars as pl

pl.Series([1]).is_in(pl.Series([1.99]) # returns True
```

### Expected behavior

Should return `False`.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.15
Index type:  UInt32
Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr 15 2023, 14:44:51) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   0.8.1
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by mcrumiller** [comment]
@ritchie46 I'm still too new to Rust to fix this, but I think the issue is here: https://github.com/pola-rs/polars/blob/5a326616684c5831831af6e34d52be06fde2901c/polars/polars-core/src/chunked_array/ops/is_in.rs#L14

I think `downcast_iter` is probably downcasting the target type whenever possible, whereas instead it should downcast according to a set of rules that may end up being complicated.

**Comment by CloseChoice** [comment]
The cast actually happens previously [here](https://github.com/pola-rs/polars/blob/main/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs#L373). This is pretty generic code and am not sure how to actually fix this. See the related issue #9068
