### ISSUE TITLE
`df.with_columns` cannot be used with `dtype=pl.Decimal`

### ISSUE THREAD

**Issue by sslivkoff** [pola-rs/polars#9086]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It seems that `df.with_columns` cannot be used with a `Series`/`DataFrame` of dtype `Decimal`

### Reproducible example

```python
df_int = pl.DataFrame({'hi': pl.Series([1,2,3], dtype=pl.Int64)})
df_float = pl.DataFrame({'bye': pl.Series([1,2,3], dtype=pl.Float64)})
df_decimal = pl.DataFrame({'bye': pl.Series([1,2,3], dtype=pl.Decimal)})

# these work fine
df_int.with_columns(df_float)  
df_int.with_columns(df_float['bye'])

# these throw PanicException
df_int.with_columns(df_decimal)
df_int.with_columns(df_decimal['bye'])
> PanicException: `clone_inner` operation not supported for dtype `decimal[0]`
```

### Expected behavior

no exception

### Installed versions

<details>

```
polars 0.17.15
```

</details>

**Comment by M-Salti** [comment]
I think this issue should be closed, because the code now works without exceptions (version 0.18.13).
