### ISSUE TITLE
Add a "filename" column option when reading multiple CSVs with globbing

### ISSUE THREAD

**Issue by Tiv0w** [pola-rs/polars#9096]
### Problem description

I'd like to use Polars (in Python) to read multiple CSVs at once, using a glob `pl.read_csv('*.csv')`, but all those files have exactly the same structure, and are **only identifiable** via their respective filename.

For now, my code is:
```python
    files = glob.glob('./*.csv')
    data = pl.concat(
        [
            pl.read_csv(f).with_columns(pl.lit(os.path.basename(f)).alias("Symbol"))
            for f in files
        ]
    )
```

It would be great if an `add_filename` option could be added to the `read_csv`/`scan_csv` functions.
If set, this would include an extra filename column in the resulting DataFrame/LazyFrame, so further processing can be done with this information.

**Comment by ritchie46** [comment]
Your code is already a fine solution isn't it? No need to put it in polars itself.

**Comment by Tiv0w** [comment]
Yeah, realistically, it's fine. Thanks.
