### ISSUE TITLE
Wrong error message when using `is_in` on categorical with other dtype

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#9097]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If you use `cat_series.is_in(noncat_series)`, Polars gives an error about the lack of use of `pl.StringCache`.

I guess something is trying to convert to cat/str under the hood.

### Reproducible example

```python
pl.Series([None]).cast(pl.Categorical).is_in(pl.Series([None]))
# => ComputeError: joins/or comparisons on categoricals can only happen if they were created under the same global string cache
```

### Expected behavior

Should give a more specific error message.

### Installed versions

`main` from today

**Comment by ritchie46** [comment]
It is a correct error message. You try to compare categoricals, that needs a `StringCache`. 

```python
with pl.StringCache():
    print(pl.Series([None]).cast(pl.Categorical).is_in(pl.Series([None])))

shape: (1,)
Series: '' [bool]
[
	true
]

```

**Comment by jonashaag** [comment]
You are right
