### ISSUE TITLE
Warn if `return_dtype` is not set in `map_elements`

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#9099]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Below an example

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'group': ['A', 'A', 'A', 'B', 'B', 'B'],
    'number': [49, 62, 100, 52, 64, 104]})

def my_function(group_elements):
    return sum([number * 1.1 if number < 50 else number for number in group_elements])

for i in range(10):
    print(df.head(6).groupby('group').agg(pl.col('number').apply(my_function)))

shape: (2, 2)
┌───────┬────────┐
│ group ┆ number │
│ ---   ┆ ---    │
│ str   ┆ i64    │
╞═══════╪════════╡
│ B     ┆ 220    │
│ A     ┆ null   │
└───────┴────────┘
shape: (2, 2)
┌───────┬────────┐
│ group ┆ number │
│ ---   ┆ ---    │
│ str   ┆ i64    │
╞═══════╪════════╡
│ B     ┆ 220    │
│ A     ┆ null   │
└───────┴────────┘
shape: (2, 2)
┌───────┬────────┐
│ group ┆ number │
│ ---   ┆ ---    │
│ str   ┆ f64    │
╞═══════╪════════╡
│ A     ┆ 215.9  │
│ B     ┆ 220.0  │
└───────┴────────┘
...
```

### Expected behavior

Same result on each run.
I imagine related to determining the data type of the calculated column.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.15
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is a bug in your query. You must set the return type in an `apply`. If you don't we try to infer based on the first value, but given that we don't guarantee the order in which we evaluate, results may differ.

It is the callers responsibility to pass the dtype.

**Comment by lucazanna** [comment]
thank you @ritchie46 , I imagined that setting the dtype would fix the issue. (I just tried and indeed it's ok now)

however, I'd say that the same code can generate different numbers might be surprising. 

what do you think about adding something to the docs? or maybe make the return_dtype a required parameter?

data type as a required parameter would force the developer to think about the return type, and it would make it clear for anyone reading the code. 
I cannot think of a situation where a developer would not know the return type of a custom function.

**Comment by ritchie46** [comment]
Yes, I think we should at least raise a warning when a user doesn't provide a `return_dtype`. Could you make a PR?

**Comment by lucazanna** [comment]
@ritchie46 will do. I can make this on the Python side with `warning.warn()`.

If I should also add it on the Rust side, could you give me some pointers for how to do it (an example of it, or a similar PR) ?

**Comment by MarcoGorelli** [comment]
The docs already contain

> If return_dtype is not provided, this may lead to unexpected results. We allow this, but it is considered a bug in the user’s query.

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.map_elements.html

TBH I don't think a runtime warning is necessarily the right solution, I'd suggest closing

**Comment by ritchie46** [comment]
We want to raise a warning if the dtype is not set. Setting the dtype will silence that warning.
