### ISSUE TITLE
Add contains to Polars supported SQL functions to simulate SQL's like statement

### ISSUE THREAD

**Issue by junsongzhao** [pola-rs/polars#9104]
### Problem description

Currently polars provides a wide range of SQL functions, including starts_with and ends with. It will be extremely useful to add "contains" function to simulate SQL's like statement.

**Comment by alexander-beedie** [comment]
FYI, we support the PostgreSQL regexp operators now, which represents a superset of this functionality, though we haven't (at time of writing) actually implemented `LIKE` itself yet:

_(ref: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)._

* `~` → contains pattern (case-sensitive)
* `~*` → contains pattern (case-INsensitive)
* `!~` → does not contain pattern (case-sensitive)
* `!~*` → does not contain pattern (case-INsensitive)
