### ISSUE TITLE
`.is_in` inconsistency with null/boolean/struct

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#9105]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I feel like there is an inconsistency in the example below. It could also be the case that it all makes sense and is working as intended in a way that I don't understand.

NB. After #9053 I wonder if the first expression should return `None`. That's how it seems to be evaluated in SQLite:

```
sqlite> .nullvalue null;
sqlite> select null in (42);
null;
```

### Reproducible example

```python
pl.Series([None], dtype=pl.Float32).is_in(pl.Series([42])).item()
# => False
pl.Series([{"a": None}], dtype=pl.Struct({"a": pl.Float32})).is_in(pl.Series([{"a": 42}])).item()
# => False

pl.Series([None], dtype=pl.Boolean).is_in(pl.Series([42])).item()
# => None
pl.Series([{"a": None}], dtype=pl.Struct({"a": pl.Boolean})).is_in(pl.Series([{"a": 42}])).item()
# => False
```

### Expected behavior

I would have expected the two last expressions to have the same result.

### Installed versions

`main` from today

**Comment by CloseChoice** [comment]
Quite a lot of `is_in` bugs/inconsistencies here, see #9070 and #9068. Maybe we should create one issue where we discuss an unified approach to solve this.

**Comment by CameronBieganek** [comment]
I've run into the same issue. Here's a similar example, expressed in a slightly different way:

```python
In [27]: df = pl.DataFrame({"x": [1, 2, None]})

In [28]: df.with_columns(
    ...:     pl.col("x").is_in([2, 3]).alias("`x` is in [2, 3]")
    ...: )
Out[28]:
shape: (3, 2)
┌──────┬──────────────────┐
│ x    ┆ `x` is in [2, 3] │
│ ---  ┆ ---              │
│ i64  ┆ bool             │
╞══════╪══════════════════╡
│ 1    ┆ false            │
│ 2    ┆ true             │
│ null ┆ false            │
└──────┴──────────────────┘
```

Here is the result I expect:

```python
Out[28]:
shape: (3, 2)
┌──────┬──────────────────┐
│ x    ┆ `x` is in [2, 3] │
│ ---  ┆ ---              │
│ i64  ┆ bool             │
╞══════╪══════════════════╡
│ 1    ┆ false            │
│ 2    ┆ true             │
│ null ┆ null             │
└──────┴──────────────────┘
```

In other words, I expect `null` values in the `x` column to propagate through `is_in`.

**Comment by evbo** [comment]
What I find confusing about this decision is `filter` will treat `null` the same as `false` rather than pass it through.

so `filter` misleads people that `null` is interchangeable with `false` but it is the exception to the rule.

**Comment by ritchie46** [comment]
null isn't interchangeable with false. It isn't true, we select the `true` items in a filter. And in combination we follow kleene logic where unknown is its own state: https://en.wikipedia.org/wiki/Three-valued_logic

**Comment by evbo** [comment]
Unless `coalesce` is used where indicated in comments, rows of `null` and `false` both get removed, which is what I meant by "interchangeable" in this particular case:

```rust
    #[test]
    fn test_filters_in_null() {
        let lf = df!(
            "colname" => ["excluded", "not_excluded"]
        )
        .unwrap()
        .lazy()
        // must use coalesce with a `lit(true)` array element since nulls are otherwise filtered out along with false
        .filter(col("colname").is_in(lit(Series::from_iter(["excluded"]))).not());

        assert_eq!(
            lf.collect().unwrap(),
            df!(
                PROP => [
                    Some("not_excluded"), 
                    None // test fails because this row gets filtered out
                ]
            )
            .unwrap()
        )
    }

```

**Comment by ritchie46** [comment]
There is an option to keep nulls, just adapt your predicate. Our filter selects the true elements, that are the semantics we've chosen. 

How elemtwise functions behave with regard to null propagation is irrelevant.

**Comment by evbo** [comment]
yes, using `coalesce` keeps nulls, like I mentioned above:

`coalesce(&[null_expr, lit(true)])`
