### ISSUE TITLE
Address intermittently failing tests

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9122]
There are some tests that fail occasionally:
* [x] [test_streaming_groupby_ooc](https://github.com/pola-rs/polars/actions/runs/5121758866/jobs/9209931975)
* [x] [test_polars_import](https://github.com/pola-rs/polars/actions/runs/5115520160/jobs/9196860470)

We should look into these to fix them, or skip them temporarily.

**Comment by mcrumiller** [comment]
Ok, I looked into the `test_polars_import` and I've found the issue:

```python
        if_err = f"Possible import speed regression; took {total_import_time//1_000}ms"
        assert total_import_time < 200_000, f"{if_err}\n{df_import}"
```

The total import time was taking too long. The test runs the following:

```
python -X importtime -c "import polars"
```

And looking at the output, we have this:

```
FAILED tests/unit/test_polars_import.py::test_polars_import - AssertionError: Possible import speed regression; took 205ms
  ┌───────────────────────────────────────────────────────────────┬──────────┬─────────────────┐
  │ import                                                        ┆ own_time ┆ cumulative_time │
  │ ---                                                           ┆ ---      ┆ ---             │
  │ str                                                           ┆ i32      ┆ i32             │
  ╞═══════════════════════════════════════════════════════════════╪══════════╪═════════════════╡
  │  polars                                                       ┆ 1298     ┆ 123721          │
  |                                      ...                                                   |
  │        email                                                  ┆ 469      ┆ 469             │
  │  site                                                         ┆ 64801    ┆ 205091          │
  │    sitecustomize                                              ┆ 232      ┆ 232             │
  │    _sysconfigdata_m_linux_x86_64-linux-gnu                    ┆ 734      ┆ 734             │
  │    coverage                                                   ┆ 341      ┆ 122808          │
  │      coverage.control                                         ┆ 2058     ┆ 122007          │
                   ...
```

The `site` import is separate from `polars`. Looking at the [docs for the site module](https://docs.python.org/3/library/site.html), we have this:

> **This module is automatically imported during initialization**. The automatic import can be suppressed using the interpreter’s [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) option.
>
>Importing this module will append site-specific paths to the module search path and add a few builtins, unless [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) was used. In that case, this module can be safely imported with no automatic modifications to the module search path or additions to the builtins. To explicitly trigger the usual site-specific additions, call the [`site.main()`](https://docs.python.org/3/library/site.html#site.main) function.

So, for our import test, I believe we should use the `-S` option, since we're only concerned with how long polars takes to load, not the `site` module, which is outside of our control.

**Comment by ritchie46** [comment]
It is allowed to fail. It serves as a safeguard against import time regressions and there will be volatility.

**Comment by mcrumiller** [comment]
@ritchie46 the import time test is also testing the time it takes to import additional python modules; we should probably only look at the polars import time, no?

**Comment by mcrumiller** [comment]
Yeah, this may take a little bit more research. I \*think\* the results from `python -X importtime` returns contiguous results related to individual packages, but I can't find that guarantee, and it's also hard to isolate polars alone. It also seems machine-dependent: when I run the command on my machine here, I get import times for `io`, `zipimport`. So one of the questions is: were these called by `polars` (I know `io` is used but `zipimport is not`), in which case we should probably include their load time.

Let me look a bit into this more and hopefully something will resolve.

**Comment by alexander-beedie** [comment]
I can address `test_polars_import` (as an aside, one of the reasons it may fail locally a lot more often than in CI is because things can be a bit slower when running a debug build).

**Comment by mcrumiller** [comment]
@alexander-beedie I think the issue is that it's failing a lot more in CI than locally, at least that's what I've noticed.  Might also be having a wailing fast machine helps...

**Comment by stinodego** [comment]
I think I know how to address the groupby one. It looks like the culprit are those temporary directories. Let's try to use pytest's [tmp_path](https://docs.pytest.org/en/6.2.x/tmpdir.html) and see if that resolves some of our issues. I will pick this up later.

**Comment by stinodego** [comment]
Ah, looks like the `test_streaming_groupby_ooc` test actually doesn't use a temporary directory. So my idea does not affect this test.

That begs the question: where does this test write its data? Can we control where this is written somehow? The error states `OSError: No such file or directory`, so it must be related to this somehow.

@ritchie46 could you point me in the right direction here?

**Comment by ritchie46** [comment]
> That begs the question: where does this test write its data? 

Because it test out-of-core. The algorithm spills to disk when we run out of memory. Here we force it to take that code path.
