### ISSUE TITLE
add label='right' option to group_by_dynamic

### ISSUE THREAD

**Issue by djbarker** [pola-rs/polars#9134]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When passing `-every` and `+every`  to the offset parameter polars returns different results.
My understanding is that these should be equivalent because the aggregation grid shifted by `n*every` for all integer `n` is equal.

### Reproducible example

```python
X = pl.DataFrame(dict(
    time = ["2023-05-30 08:01:00", "2023-05-30 08:23:00", "2023-05-30 09:13:00"],
    value = [1, 2, 3],
)).with_columns(
    pl.col("time").str.strptime(pl.Datetime),
).set_sorted("time")


# 1. Gives times [08:00, 09:00]:
X.groupby_dynamic("time", every="30m", offset="-30m").agg(pl.col("value").sum())

# 2. Gives times [07:59, 08:59]:
X.groupby_dynamic("time", every="30m", offset="-1m").agg(pl.col("value").sum())

# 3. Gives times [08:00, 09:00]:
X.groupby_dynamic("time", every="30m", offset="0m").agg(pl.col("value").sum())

# 4. Gives times [08:01, 09:01]:
X.groupby_dynamic("time", every="30m", offset="1m").agg(pl.col("value").sum())

# 5. Gives times [09:00]:
X.groupby_dynamic("time", every="30m", offset="30m").agg(pl.col("value").sum())
```

### Expected behavior

Examples 1., 3. and 5. should give identical results.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.11
Index type: UInt32
Platform: Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64-with-glibc2.28
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.3
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.5.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by djbarker** [comment]
Not really related to the issue but I find it a bit confusing that the aggregation returns the timestamp at the beginning of the bucket. Most uses I've seen need the timestamp at the end of the bucket. It's simple enough to add a timedelta of `every` after the `groupby_dynamic` call, but would it be possible to add an option to `groupby_dynamic` to use the bin end? I see there is the `include_boundaries` option but this warns it can impact performance. (OOI why is that so?)

If this is reasonable I can create a separate issue for that. Thanks.

**Comment by ritchie46** [comment]
You are running `0.17.11`. Can you try `0.18.0`?

**Comment by djbarker** [comment]
I see the same behaviour with 0.18.0

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.14.0-162.6.1.el9_1.x86_64-x86_64-with-glibc2.34
Python:      3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]

----Optional dependencies----
numpy:       1.21.6
pandas:      1.5.3
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.5.2
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

**Comment by ritchie46** [comment]
I am not convinced this is incorrect? It applies the offset correctly?

**Comment by ritchie46** [comment]
I believe the offset is applied, but that window window doesn't have any members, so it is skipped. We apply the offsets, but look for the first matching window to start the grouping.

**Comment by djbarker** [comment]
Okay, perhaps I just don't understand the offsets properly. Happy to close if you're sure it's behaving as expected. 
How about an option to return the bin end time, rather than the start, do you think that warrants a new issue?

**Comment by mcrumiller** [comment]
@ritchie46 it looks to me as though the offset is relative to the actual hour, and not the first value in the dataframe, which is very confusing. Does the offset pick the nearest hour, or the beginning of the current hour? This may be the source of confusion and maybe should be clarified in the docs, as I would normally expect the former.

@djbarker this explains your results. See here: ignoring date, here are your calls, and the corresponding windows:

#### 1. Gives times [08:00, 09:00]:
```python
X.groupby_dynamic("time", every="30m", offset="-30m").agg(pl.col("value").sum())
```

Window| window start | window stop | values contained
--|---|---| ---
1 | 7:30 | 8:00 | None -> throw out result
2 | 8:00 | 8:30 | 8:01 (1) + 8:23 (2) = 3
3 | 8:30 | 9:00 | 9:01 (3) = 3

#### 2. Gives times [07:59, 08:59]:
```python
X.groupby_dynamic("time", every="30m", offset="-1m").agg(pl.col("value").sum())
```
Window| window start | window stop | values contained
--|---|---| ---
1 | 7:59 | 8:29 | 8:01 (1) + 8:23 (2) = 3
2 | 8:29 | 8:59 | None -> throw out result
3 | 8:59 | 9:29 | 9:01 (3) = 3

#### 3. Gives times [08:00, 09:00]:
```python
X.groupby_dynamic("time", every="30m", offset="0m").agg(pl.col("value").sum())
```

Window| window start | window stop | values contained
--|---|---| ---
1 | 8:00 | 8:30 | 8:01 (1) + 8:23 (2) = 3
2 | 8:30 | 9:00 | None -> throw out result
3 | 9:00 | 9:30 | 9:01 (3) = 3

#### 4. Gives times [08:01, 09:01]:
```python
X.groupby_dynamic("time", every="30m", offset="1m").agg(pl.col("value").sum())
```
Window| window start | window stop | values contained
--|---|---| ---
1 | 8:01 | 8:31 | 8:01 (1) + 8:23 (2) = 3
2 | 8:31 | 9:01 | None -> throw out result
3 | 9:01 | 9:31 | 9:01 (3) = 3

Note here that our intervals are [start, stop) so `9:01` doesn't make it into bucket #2.

#### 5. Gives times [09:00]:
```python
X.groupby_dynamic("time", every="30m", offset="30m").agg(pl.col("value").sum())
```
Window| window start | window stop | values contained
--|---|---| ---
1 | 8:30 | 9:00 | None -> Throw out result
2 | 9:00 | 9:30 | 9:01 (3) = 3

**Comment by SaneBow** [comment]
> Not really related to the issue but I find it a bit confusing that the aggregation returns the timestamp at the beginning of the bucket. Most uses I've seen need the timestamp at the end of the bucket. It's simple enough to add a timedelta of `every` after the `groupby_dynamic` call, but would it be possible to add an option to `groupby_dynamic` to use the bin end? I see there is the `include_boundaries` option but this warns it can impact performance. (OOI why is that so?)
> 
> If this is reasonable I can create a separate issue for that. Thanks.

I second that. Adding an option to use bin end could be very useful. 

In [pandas resample](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html), we can simply set `label='right'`, but in polars we need to shift/offset the index_column separately. I'm switching from Pandas to Polars. Most transitions are quite smooth, I only found it a bit painful to do correct resampling in Polars.

**Comment by MarcoGorelli** [comment]
The current argument `truncate` does:
- `True`: label goes to the lower boundary of the window
- `False`: label goes to the first datapoint in the window

Maybe `truncate` should be deprecated, in favour of `label`, which could take values:
- 'left': lower boundary of window
- 'right': upper boundary of window
- 'datapoint': first datapoint

**Comment by ritchie46** [comment]
I am in favor of the `"label"` enum for this. Open for a PR on this!

**Comment by MarcoGorelli** [comment]
on it 🚀
