### ISSUE TITLE
test_polars_import intermittently fails

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9138]
### Issue description

One of the two intermittently failed tests mentioned in #9122.

I looked into the `test_polars_import` and I've found the issue:

```python
        if_err = f"Possible import speed regression; took {total_import_time//1_000}ms"
        assert total_import_time < 200_000, f"{if_err}\n{df_import}"
```

The total import time was taking too long. The test runs the following:

```
python -X importtime -c "import polars"
```

And looking at the output, we have this:

```
FAILED tests/unit/test_polars_import.py::test_polars_import - AssertionError: Possible import speed regression; took 205ms
  ┌───────────────────────────────────────────────────────────────┬──────────┬─────────────────┐
  │ import                                                        ┆ own_time ┆ cumulative_time │
  │ ---                                                           ┆ ---      ┆ ---             │
  │ str                                                           ┆ i32      ┆ i32             │
  ╞═══════════════════════════════════════════════════════════════╪══════════╪═════════════════╡
  │  polars                                                       ┆ 1298     ┆ 123721          │
  |                                      ...                                                   |
  │        email                                                  ┆ 469      ┆ 469             │
  │  site                                                         ┆ 64801    ┆ 205091          │
  │    sitecustomize                                              ┆ 232      ┆ 232             │
  │    _sysconfigdata_m_linux_x86_64-linux-gnu                    ┆ 734      ┆ 734             │
  │    coverage                                                   ┆ 341      ┆ 122808          │
  │      coverage.control                                         ┆ 2058     ┆ 122007          │
                   ...
```

The `site` import is separate from `polars`. Looking at the [docs for the site module](https://docs.python.org/3/library/site.html), we have this:

> **This module is automatically imported during initialization**. The automatic import can be suppressed using the interpreter’s [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) option.
>
>Importing this module will append site-specific paths to the module search path and add a few builtins, unless [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) was used. In that case, this module can be safely imported with no automatic modifications to the module search path or additions to the builtins. To explicitly trigger the usual site-specific additions, call the [`site.main()`](https://docs.python.org/3/library/site.html#site.main) function.

So, for our import test, I believe we should use the `-S` option, since we're only concerned with how long polars takes to load, not the `site` module, which is outside of our control.

**Comment by mcrumiller** [comment]
Update: Using `-S` prevents the the import of the `site` module, but that may be undesirable. Instead, we should ignore the timings of the `site import during the test.

**Comment by mcrumiller** [comment]
@alexander-beedie any thoughts on how to proceed here? I'm not entirely sure how to parse the output of `-X importtime`. Does the "cumulative" field include other modules, do we only want to exclude a couple of specific modules (i.e. `site`)? Part of polars' import time is the time it takes to import its dependencies, so we don't want to exclude any of those.

**Comment by alexander-beedie** [comment]
Ok, fixed it; apparently I was lazy with the check and was picking the `max` cumulative time (not completely crazy, given polars is the only thing being explicitly imported in the line of code `import polars`, heh) - _however_... occasionally `site` can randomly spike, as above, resulting in the check picking the wrong cumulative time to validate :)
