### ISSUE TITLE
Series created via `Logical::new_logical` panics when displayed

### ISSUE THREAD

**Issue by amunra** [pola-rs/polars#9147]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

All I was trying to do is create a `DateTime` column that I'm parsing via `reqwest` and the `csv_async` crates.

Here was my approach:

```rust
let mut builder = PrimitiveChunkedBuilder<Int64Type>::new("foo", 0);
builder.append_value(42);
let logical: DatetimeChunked = DatetimeChunked::new_logical(builder.finish());
let series = Series::from(logical);
let df = DataFrame::new(vec![series]);
```

Then, this goes _kaboom_!:

```rust
println!("{}", df);
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.30.0/src/chunked_array/logical/datetime.rs:16:25
```

I.e., in this piece of code:

```rust
impl LogicalType for DatetimeChunked {
    fn dtype(&self) -> &DataType {
        self.2.as_ref().unwrap()          // <-- bad unwrap
    }
```

I think the culprit is:

```rust
impl<K: PolarsDataType, T: PolarsDataType> Logical<K, T> {
    pub fn new_logical<J: PolarsDataType>(ca: ChunkedArray<T>) -> Logical<J, T> {
        Logical(ca, PhantomData, None)
    }  //                        ^_______ None passed to `.2` of type `pub Option<DataType>`.
}
```

My work-around is to use the API properly. I eventually noticed that I could do this:

```rust
builder.finish().into_datetime(TimeUnit::Nanoseconds, None);
```

Suggested resolutions:

* I feel the `new_logical` API should probably be a `pub(crate)` rather than a `pub` to avoid invalid API usage.

* I feel there should also be docs on how to create a DataFrame for all existing datatypes: At the moment it's left as an exercise to the reader (digging through the source code) to figure out how to use `Utf8ChunkedBuilder`, `PrimitiveChunkedBuilder` and friends.

I'm a newbie: it's quite possible that the docs exist, but I simply didn't come across them: My total Polars experience now is around 1h so far. Neat project!

### Reproducible example

See above.

### Expected behavior

See above.

### Installed versions

polars = { version = "0.30.0", features = ["lazy", "dtype-categorical", "dtype-datetime", "performant", "temporal"] }

**Comment by ritchie46** [comment]
You shouldn't use those constructors. I will see if I can make them private.

**Comment by ritchie46** [comment]
made private
