### ISSUE TITLE
Make value_counts (optionally) output a struct where the key is the value and value is the count

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#9158]
### Problem description

Inspired from [this](https://stackoverflow.com/questions/76380172/polars-groupby-value-counts/76380522#76380522)

Now, `value_counts` outputs a series of structs where each element of the series has {'column_name':'some_value', 'counts':'u32_count'}.

It'd be nice if we could, optionally, get the following instead {'some_value':'u32_count'}.

Say we start with:

```
train=pl.from_repr(
     """┌───────────────────┬──────────────┬────────┐
        │ session_id        ┆ elapsed_time ┆ fqid   │
        │ ---               ┆ ---          ┆ ---    │
        │ i64               ┆ i32          ┆ cat    │
        ╞═══════════════════╪══════════════╪════════╡
        │ 20090312431273200 ┆ 0            ┆ intro  │
        │ 20090312431273200 ┆ 1323         ┆ gramps │
        │ 20090312431273200 ┆ 831          ┆ gramps │
        │ 20090312431273100 ┆ 1147         ┆ gramps │
        │ 20090312431273100 ┆ 5197         ┆ teddy  │
        │ 20090312431273200 ┆ 6180         ┆ teddy  │
        │ 20090312431273200 ┆ 7014         ┆ teddy  │
        │ 20090312431273200 ┆ 7946         ┆ teddy  │
        └───────────────────┴──────────────┴────────┘""")
```

The existing behavior for `value_counts` let's us do

```
train.select(pl.col('fqid').value_counts()).unnest('fqid')
```

to get

```
shape: (3, 2)
┌────────┬────────┐
│ fqid   ┆ counts │
│ ---    ┆ ---    │
│ cat    ┆ u32    │
╞════════╪════════╡
│ intro  ┆ 1      │
│ gramps ┆ 3      │
│ teddy  ┆ 4      │
└────────┴────────┘
```

but we can't do 

```
train.select(pl.col('fqid').value_counts().over('session_id'))
```

we could implode the `value_counts()` before the `over` but then we have a list of structs which is a bit unwieldy. If the output of `value_structs` was a single element struct with {'some_value':'u32_count'} for all the values in the underlying column then the above window function would work and it'd be an easy to unnest field.

To give a more concrete example of what I'm looking for would be that this:

```
train.groupby('session_id').agg(pl.col('fqid').value_counts(new_output_behavior=True))
```

would have the same output as 

```
(
    train
        .groupby(['session_id','fqid']) 
        .count()  #same as .agg(pl.count())
        .pivot('count','session_id','fqid','first')
        .select('session_id', fqid=pl.struct(pl.exclude('session_id')))
)
```

**Comment by cmdlineluser** [comment]
In a struct column, they must all have the same keys:
```python
pl.Series([ dict(intro=1), dict(gramps=3), dict(teddy=4) ])

# shape: (3,)
# Series: '' [struct[1]]
# [
# 	{1}
# 	{null}
# 	{null}
# ]
```
To hold them together, you would end up with:
```python
pl.Series([ 
   dict(intro=1, gramps=None, teddy=None), 
   dict(intro=None, gramps=3, teddy=None), 
   dict(intro=None, gramps=None, teddy=4)
])
 
# shape: (3,)
# Series: '' [struct[3]]
# [
#     {1,null,null}
#     {null,3,null}
#     {null,null,4}
# ]
```

**Comment by deanm0000** [comment]
@cmdlineluser That seems fine to me. That sort of thing already exists with `list.to_struct(n_field_strategy='max_width')`.

**Comment by cmdlineluser** [comment]
I guess I was trying to say that I didn't think it would be possible for `.value_counts` to return just `{'some_value': count}` 

And it would have to return `{'some_value_0': count, 'some_value_1': null, 'some_value_2': null, ...}`

But perhaps that's not relevant.

Maybe I'm wrong, but it seems like apart from a pivot, the only way to get column values as struct field names is to use an apply of some sort and return dicts?
```python
from collections import Counter

df.groupby("session_id").agg(pl.col("fqid").apply(Counter))

# shape: (2, 2)
# ┌───────────────────┬────────────┐
# │ session_id        ┆ fqid       │
# │ ---               ┆ ---        │
# │ i64               ┆ struct[3]  │
# ╞═══════════════════╪════════════╡
# │ 20090312431273200 ┆ {2,1,3}    │
# │ 20090312431273100 ┆ {1,null,1} │
# └───────────────────┴────────────┘
```
It looks like `.value_counts()` essentially does `df.groupby().count().to_struct()`:

https://github.com/pola-rs/polars/blob/main/polars/polars-ops/src/series/ops/various.rs#L11-L24

I thought perhaps `fields=` may be able to read from a column/expression which could avoid a pivot:
```python
(
   df.groupby("fqid", "session_id").count()
     .groupby("session_id")
     .all()
     .select("session_id", fqid = pl.col("count").list.to_struct(fields="fqid", n_field_strategy="max_width"))
)

# shape: (2, 2)
# ┌───────────────────┬────────────┐
# │ session_id        ┆ fqid       │
# │ ---               ┆ ---        │
# │ i64               ┆ struct[3]  │
# ╞═══════════════════╪════════════╡
# │ 20090312431273100 ┆ {1,1,null} │
# │ 20090312431273200 ┆ {1,2,3}    │
# └───────────────────┴────────────┘
```
But it seems like `fields=` accepting string input is a bug:
```python
_.unnest("fqid")

# shape: (2, 4)
# ┌───────────────────┬─────┬─────┬──────┐
# │ session_id        ┆ f   ┆ q   ┆ i    │
# │ ---               ┆ --- ┆ --- ┆ ---  │
# │ i64               ┆ u32 ┆ u32 ┆ u32  │
# ╞═══════════════════╪═════╪═════╪══════╡
# │ 20090312431273100 ┆ 1   ┆ 1   ┆ null │
# │ 20090312431273200 ┆ 1   ┆ 2   ┆ 3    │
# └───────────────────┴─────┴─────┴──────┘
```
Perhaps `struct.rename_fields()` being able to read from a column/expression would be more useful if that was possible.

**Comment by ritchie46** [comment]
I don't understand the distinction. We return a struct with the value fields and the count fields. That's exactly what value counts is right?

The reason you cannot use it with window functions is the same you cannot use `unique` with window functions. The number of unique values may be smaller than the group, so we cannot map them back.

**Comment by deanm0000** [comment]
unique outputs a varying length of outputs.

value_counts should give the same number of outputs, unlike unique, if something doesn't exist in a group then it should output a 0 for that group not a null (I failed to account for that in my example).

For those reasons, I don't think they're good analogs to each other.

The main distinction though in what I'm saying would be helpful vs the current behavior is that getting a df with a List nested with structs is hard to deal with. If someone just wants to look at the output of, for example:

```
train.groupby('session_id').agg(pl.col('fqid').value_counts())
```

then that output has everything you need. On the other hand, if you need to do something with those values, it's kind of tough to get them out since they're structs inside lists.

Is it more tenable to ask for list.to_struct to have a feature to take the [{'value':'value1', 'count':'count1'}, {'value':'value2', 'count':'count2'}, ... {'value':'valuen', 'count':'countn'}] format and convert it to {'value1':'count1', 'value2':'count2', ..., 'valuen':'countn'} format? I'm not trying to make things _more_ complicated with this ask, just wondering if this is a better way to get the same result. This obviously only works if the list of structs have exactly two struct elements.

Don't get me wrong, this is pretty low impact given that `count` and `pivot` work I just thought it was worth bringing up. If actually making it work is big effort then I certainly wouldn't want to take away time from doing other items.

**Comment by ritchie46** [comment]
Yes, but all duplicates are removed. If we have 7 duplicates for `"a"`, we get a single entry `"a": 7`
