### ISSUE TITLE
Adjust number of threads in Expr.apply()

### ISSUE THREAD

**Issue by rmekdma** [pola-rs/polars#9174]
### Problem description

[Expr.apply()](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.apply.html) runs as many threads as `POLARS_MAX_THREADS`. In the previous [pr](https://github.com/pola-rs/polars/pull/7277), the use case assumption was calling HTTPS requests. For this use case, I hope I can set the number of threads so that I can limit the number of requests per second.

My suggestion is to add `n_thread` argument:
```python
def Expr.apply(function, return_dtype, *, skip_nulls, pass_name, strategy, n_threads=0):
    if strategy == "thread_local":
        # single thread processing
    elif strategy == "threading":
        # multithread processing
        if n_threads <= 0:
            n_threads = threadpool_size()
        else:
            n_threads = min(n_threads, threadpool_size())
```

If you plant to keep two strategies, `n_threads` can replace it:
```python
def Expr.apply(function, return_dtype, *, skip_nulls, pass_name, n_threads=None):
    if n_threads is None:
        # single thread processing
    else:
        # multithread processing
        if n_threads <= 0:
            n_threads = threadpool_size()
        else:
            n_threads = min(n_threads, threadpool_size())
```

**Comment by ritchie46** [comment]
Polars doesn't allow that. Expressions run on the default threadpool, and if the would create their own threadpool we will have lot of contention / locking problems.

You can modify the global threadpool size.

**Comment by rmekdma** [comment]
Ah, I see. Thank you for reviewing.
