### ISSUE TITLE
Shift + Apply fails

### ISSUE THREAD

**Issue by fierzdev** [pola-rs/polars#9180]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have a usecase where I want to compare the values from row n with the values from row n+1. I thought thay I could accomplish this by calling select and selecting the column + column shifted by 1. As I deal with Strings, I cannot really use Windowing for it. 
When now trying to select a column + the column shifted by 1 and calling apply on the resulting DataFrame, I get an error.
<details>

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`: impl error', /home/runner/work/polars/polars/polars/polars-core/src/series/iterator.rs:70:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 5670, in apply
    out, is_df = self._df.apply(function, return_dtype, inference_size)
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `2`,
 right: `1`: impl error

</details>

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(pl.Series('texts', ["test", "test123", "tests"]))
# Shifting + apply fails:
df.select(pl.col('texts'), pl.col('texts').shift(1).alias("texts_shifted")).apply(lambda x: x)
# This works:
df.select(pl.col('texts'), pl.col('texts').alias("texts_")).apply(lambda x: x)
```

### Expected behavior

It should essentially produce the same result, as if we select the same column twice and call apply. It should not lead to an error.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.15.0-72-generic-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      <not installed>
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce, `Dataframe.apply`:
```
PanicException: assertion failed: `(left == right)`
  left: `2`,
 right: `1`: impl error
```
If you haven't tried, [Expr.apply](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.apply.html#polars.Expr.apply) works:

```python
df.select(
   pl.struct(pl.col('texts'), pl.col('texts').shift(1).alias("texts_shifted"))
     .apply(lambda x: print(f"{x=}"))
)

# x={'texts': 'test', 'texts_shifted': None}
# x={'texts': 'test123', 'texts_shifted': 'test'}
# x={'texts': 'tests', 'texts_shifted': 'test123'}
```
Although depending on what exactly it is you're doing, it may be possible to do it without having to use `.apply`

**Comment by fierzdev** [comment]
Nice, that workaround works. Thanks! But it's probably still a good idea to look into this as I assume it should also work on datasets.

Yeah I think for my usecase I can not come around apply. We want the Levenshtein distance, for which we use a Python UDF to compute.

**Comment by cmdlineluser** [comment]
Ah, apologies for any confusion - I was just commenting as a fellow polars user.

The actual bug will also be addressed by the relevant people.
