### ISSUE TITLE
Series::new panics when created with a vector containing an empty series.

### ISSUE THREAD

**Issue by KonstantinRr** [pola-rs/polars#9182]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Series::new panics when created with a vector containing an empty series.

### Reproducible example

```rust
Series::new("test", Vec::<Series>::new());
```

gives this panic:

```
thread panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/./.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.28.0/src/named_from.rs:126:18
stack backtrace:
```

### Expected behavior

It should create an empty Series.

### Installed versions

Installed version: 0.28.

**Comment by parkma99** [comment]
#9422

**Comment by coastalwhite** [comment]
This is resolved by the `Series::new_empty` method. Closing.
