### ISSUE TITLE
Allow arithmetic operations for list and array type

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#9188]
### Problem description

I wish Polars could allows arithmetic operations for list and array types with an inner numeric data type.

Taking an example from this GitHub question: https://stackoverflow.com/questions/76389832/polars-how-to-add-two-series-that-contain-lists-as-elements

I would be nice to be able to do:
```python
a = pl.Series("a",[[1,2],[2,3]])
b = pl.Series("b",[[4,5],[6,7]])
c = a+b
```

Currently, it panicks: PanicException: `add` operation not supported for dtype `list[i64]`

**Comment by cmdlineluser** [comment]
While experimenting with the example I found it interesting you can add structs:
```python
a.list.to_struct() + b.list.to_struct()

# shape: (2,)
# Series: 'a' [struct[2]]
# [
# 	{5,7}
# 	{8,10}
# ]
```
Although it only works with 2d, and requires turning back into a list.

**Comment by lucazanna** [comment]
thanks for sharing @cmdlineluser ! 

I would not have guessed it would work with structs.

**Comment by itamarst** [comment]
Going to try to implement this.

**Comment by cmdlineluser** [comment]
It was added for Array https://github.com/pola-rs/polars/pull/16791

```python
import polars as pl
import numpy as np

a = pl.Series("a",np.array([[1,2],[2,3]]))
b = pl.Series("b",np.array([[4,5],[6,7]]))

a + b

# shape: (2,)
# Series: 'a' [array[i64, 2]]
# [
# 	[5, 7]
# 	[8, 10]
# ]
```

**Comment by itamarst** [comment]
Thank you, that'll make it easier for me to implement given the example.

**Comment by itamarst** [comment]
OK, it appears to be working at least in the happy path.

Remaining work:

* [ ] Thorough test suite, handling any bugs it catches.
* [ ] Test for division of arrays, since I fixed that as part of this.

**Comment by bike-picket** [comment]
@itamarst is it feasible to add pow support?

```
(pl.Series("a",[[1,2],[2,3]]) ** pl.Series("a",[[1,2],[2,3]])).to_list()

# Polars 1.8.2 gives the error:
# polars.exceptions.InvalidOperationError: `pow` operation not supported for dtype `list[i64]` as base
```
