### ISSUE TITLE
Apply is only working on first row

### ISSUE THREAD

**Issue by gjwebber** [pola-rs/polars#9190]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Trying to apply a specific function to a dataframe, it only works for the first row - all others return null

When printing the result, all are displayed on the console as expected

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [[1,2],[2,3]], 'b': [[4,5],[6,7]]})

def cmb(row):
    res = [x + y for x, y in zip(row[0], row[1])]
    print(res) #works as expected for both rows
    return [res] #Only works on the first row

df.apply(cmb)

#Output:
# [5, 7]
# [8, 10]
#
# shape: (2, 1)
# column_0
# list[i64]
# [5, 7]
# null
```

### Expected behavior

The output matches what is printed, all rows should have data, not null

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Not sure why anything is being printed at all, seems like an artifact:

```
>>> df2 = df.apply(cmb)
[5, 7]     <-- shouldn't see this
[8, 10]
```

**Comment by gjwebber** [comment]
I added the print in the function `cmb` for some debugging, it wouldn't usually appear otherwise

**Comment by mcrumiller** [comment]
Ha, I missed that.

**Comment by cjackal** [comment]
It is somehow related to polars distinguishing tuple and list:

```python

def cmb(row):
    res = [x + y for x, y in zip(row[0], row[1])]
    print(res) #works as expected for both rows
    return (res,) #works like a charm

df.apply(cmb)
```
