### ISSUE TITLE
`rolling_apply` still does not respect the value of `min_periods` parameter

### ISSUE THREAD

**Issue by mostwk** [pola-rs/polars#9191]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is a continuation of https://github.com/pola-rs/polars/issues/9160
The problem still persists in master

### Reproducible example

```python
import polars as pl

pl.Series([1]).rolling_apply(lambda x : sum(x), window_size=2, min_periods=1)
shape: (1,)
Series: '' [i64]
[
        null
]

pl.Series([1, 2, 3, 4, 5]).rolling_apply(lambda x : sum(x), window_size=12, min_periods=1)
shape: (5,)
Series: '' [i64]
[
        null
        null
        null
        null
        null
]
```

### Expected behavior

Working examples of pandas 1.1.5 equivalent and `rolling_sum` function
```python
import pandas as pd
import polars as pl

pd.Series([1]).rolling(2, min_periods=1).apply(lambda x: sum(x))
0    1.0
dtype: float64

pd.Series([1, 2, 3, 4, 5]).rolling(12, min_periods=1).apply(lambda x: sum(x))
0     1.0
1     3.0
2     6.0
3    10.0
4    15.0
dtype: float64

pl.Series([1]).rolling_sum(window_size=2, min_periods=1)
shape: (1,)
Series: '' [i64]
[
        1
]

pl.Series([1, 2, 3, 4, 5]).rolling_sum(window_size=12, min_periods=1)
shape: (5,)
Series: '' [i64]
[
        1
        3
        6
        10
        15
]
```

### Installed versions

Changes were tested on master
<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
Python:      3.9.10 (main, Mar  2 2022, 04:31:58) 
[GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.22.4
pandas:      1.1.5
pyarrow:     8.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.11.0
matplotlib:  3.6.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by avimallu** [comment]
Just to confirm - you compiled polars from source and tested, or did you do `pip install polars` (or equivalent)? If the latter, it wouldn't show up because a new release of polars isn't out yet.

**Comment by mostwk** [comment]
I compiled from source yes, one of the examples provided in previous issue is fixed
```python
pl.Series([1, 5]).rolling_sum(window_size=2, min_periods=1)
shape: (2,)
Series: '' [i64]
[
        1
        6
]
```
 but not the other one, and I provided one more generic example

**Comment by cmdlineluser** [comment]
I don't think the problem is `min_periods` not being respected - it's that you're passing a `window_size` larger than the size of the series.

The fixed example was because of the off-by-one due to `>=` instead of `>`

Polars is returning null if the window_size is greater than the input length:
```
 if options.window_size > self.len() {
     return Ok(Self::full_null(self.name(), self.len()).into_series());
```
But instead of this, you want `window_size` to be clipped to `self.len()`

**Comment by cmdlineluser** [comment]
Yeah, I'm not sure why that check exists in `.rolling_apply` compared to the other rolling functions.

I imagine it's not by design, it's probably just that it is a rarely used function and you're the first person to encounter the issue.

It should be consistent as you say, and the devs will fix it.
