### ISSUE TITLE
Documentation: `polars.Expr.str.to_decimal()` lists incorrect resulting dtype

### ISSUE THREAD

**Issue by owenprough-sift** [pola-rs/polars#9194]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

https://github.com/pola-rs/polars/blob/db2cbc030dc66c89380790537e3f745fb13df9d7/py-polars/polars/expr/string.py#L309-L314

The docstring incorrectly states that the resulting type will be `Date` instead of `Decimal`

### Reproducible example

```python
Not applicable (documentation)
```

### Expected behavior

Docstring (and therefore online API reference) lists the correct resulting type for `str.to_decimal()`

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-4.15.0-123-generic-x86_64-with-glibc2.31
Python:      3.10.11 (main, May 23 2023, 14:03:36) [GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Oops - thanks for spotting this ;)
