### ISSUE TITLE
100,000 Rows File x 3,000

### ISSUE THREAD

**Issue by hkpeaks** [pola-rs/polars#9201]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars can run a 300 million rows csv file, but fail to run if it is divided by 3,000 files.

D:\Benchmark>python PolarsFilterGroupByCSV.py
memory allocation of 16392 bytes failed

### Reproducible example

```python
import polars as pl
import time
import pathlib
s = time.time()

table1 = (
     pl.scan_csv("Input/Copy3000/*.csv")
     .filter((pl.col('Ledger') >= "L30") & (pl.col('Ledger') <= "L70"))      
     .groupby(by=["Ledger", "Account", "DC","Currency"])
    .agg([    
        pl.sum('Base_Amount').alias('Total_Base_Amount'),        
    ])) 

path = "Output/PolarsFilterGroupByCSV.csv"
table1.lazy().collect(streaming=True).write_csv(path)

e = time.time()
print("Polars FilterGroupBy CSV Time = {}".format(round(e-s,3)))

One of the input file
https://github.com/hkpeaks/peaks-consolidation/blob/main/Benchmark20230602/1.csv
```

### Expected behavior

D:\Benchmark>python PolarsDBFilterGroupByCSV.py
Polars FilterGroupBy CSV Time = ??.???

### Installed versions

<details>

```
0.18.0
```

</details>

**Comment by ritchie46** [comment]
Can you create a MWE?

**Comment by hkpeaks** [comment]
Every file is same, you can use script to copy files in your machine very easily. So it is simplex case. I test is again, it can complete for 1,000 files. But fail when I use 1,200 or more.
So I will use 1,000 files for benchmarking with Spark, DuckDB and Peaks.

**Comment by zundertj** [comment]
Can you include the download + file copying code in the code?

On the MWE, at a minimum, you should try to address the following:
1. the `time` is not needed? If so, please remove
2. does the problem also occur if any or all of the following is taken out: `filter`, `groupby` (which of the columns you group there, or can all be taken out)
3. does the problem occur if you do not call `write_csv` at the end?

**Comment by hkpeaks** [comment]
This copy file code is derived from Bing Chat.

package main

import (
    "fmt"
    "io"
    "os"
    "strconv"
)

func main() {
    source := "D:\\Go\\Input\\100000.csv"
    var target string

    for i := 0; i < 3000; i++ {
        // Open the source file
        srcFile, err := os.Open(source)
        if err != nil {
            fmt.Println(err)
            return
        }
        defer srcFile.Close()

        target = "D:\\Go\\Input\\Copy3000\\" + strconv.Itoa(i) + ".csv";
        // Create the target file
        dstFile, err := os.Create(target)
        if err != nil {
            fmt.Println(err)
            return
        }
        defer dstFile.Close()

        // Copy the contents of the source file to the target file
        _, err = io.Copy(dstFile, srcFile)
        if err != nil {
            fmt.Println(err)
            return
        }
    }

    fmt.Println("File copied successfully!")
}

**Comment by hkpeaks** [comment]
The root problem may be the design of the steaming engine. The author told me that it is in alpha stage. So I have opened my steaming source for Polars team to learn. https://github.com/hkpeaks/peaks-consolidation, this project has only 3 months history, but I consider the steaming engine become in mature stage for single big file. Now I am extending it to support many small/big files in a folder.

**Comment by hkpeaks** [comment]
To implement of separation of concern is very important for steaming model. For example, if Filter and GroupBy are first two query commands you build, and it is separate from how the system steaming and management of in-memory partition, after you success in first 2 commands in steaming, you can enjoy 3rd command e.g. JoinTable also support steaming automatically. No matter how much commands you build afterward, all these command can be enjoyed steaming automatically. I am a non-code consultant working with FlexSystem for a decade. I had learnt a lot of software design principal from the CEO. What I had learn from him in fact is valuable to my current design of Peaks Consolidation.

**Comment by zundertj** [comment]
The only way we can help you is if you help us. In particular, you haven't come back on the questions by both Ritchie and myself to create a MWE. The same question that was also asked in the issue template. See [this article](https://matthewrocklin.com/minimal-bug-reports) for how to create a MWE. Idem for the output of `pl.show_versions()`. 

Instead, you have posted a lot of text, almost all off-topic and irrelevant, such as talk about other software, your background and other programming languages. Please answer on topic in a constructive way.

**Comment by hkpeaks** [comment]
I am a developer of simiar software, so I understand the issue. The error I state is not whether it can print or it can output a file or it calc incorrectly, is "Out of Memory". I assume it is the limiation of the software, so run 1,000 file is fine for me for benchmarking. Do what you request to do provide nothing help to fix the issue as scirpt is provided and file is provided.

**Comment by mcrumiller** [comment]
@hkpeaks we are happy to help you diagnose the issue, but we also request that you listen to us.

> I am a developer of simiar software, so I understand the issue

I am not sure that you do. The issue is that you have not provided a minimally working example, which is code that we can run without spending a bunch of our own time figuring out how to get it to run. Your initial code is *almost* there, except that it assumes we have and `Input/Copy3000` folder populated with CSV files. So, all you need to do in this case is to add a little bit of code that 1) somehow supplies the files (try using `requests.get()`), and maybe 2) copies it 3000 times.

**Comment by Bidek56** [comment]
MWE on a Windows 11 machine with 32Gb of memory, Python 3.11.3, Polars 0.18

1. `curl -o ./data/1.csv https://raw.githubusercontent.com/hkpeaks/peaks-consolidation/main/Benchmark20230602/1.csv`
2. Create 3000 copies of the `1.csv` file using this Powershell `copy.ps1` scripts:

```
$NumArray = (1..3001)
ForEach ($number in $numArray) {
   Copy-Item  `
        -Path C:\Users\foo\Documents\pl-9201\data\1.csv  `
        -Destination "C:\Users\foo\Documents\pl-9201\data\raw$number.csv"
}
```
Execute the following Python script:

```
import polars as pl
import time
import pathlib
s = time.time()

table1 = (
     pl.scan_csv("data/*.csv")
     .filter((pl.col('Ledger') >= "L30") & (pl.col('Ledger') <= "L70"))      
     .groupby(by=["Ledger", "Account", "DC","Currency"])
    .agg([    
        pl.sum('Base_Amount').alias('Total_Base_Amount'),        
    ])) 

path = "Output/PolarsFilterGroupByCSV.csv"
table1.lazy().collect(streaming=True).write_csv(path)

e = time.time()
print("Polars FilterGroupBy CSV Time = {}".format(round(e-s,3)))
```

This script works with less than 2600 files on my Windows 11 laptop.
Somewhere above 2600 files, the script just crashes with no error message.
I hope this helps.
Thanks

**Comment by Bidek56** [comment]
Similar Rust code on the same 3K files works just fine.
```
use polars::prelude::*;

fn main() {
    let path = "./data/*.csv";
    let ldf = LazyCsvReader::new(path)
        .has_header(true)
        .finish().unwrap()
        .filter( col("Ledger").is_in( lit("L30" ) ) )
        .groupby(["DC"])
        .agg([ 
            count().alias("Count"),        
        ]);

    print!("{:?}", ldf.collect());
}
```

**Comment by hkpeaks** [comment]
If a steaming model is designed properly, there shall be no limit on number of file and rows except hard disk space. I have implemented a water tank model for my app. So I have solved billion-row Jointabe using only 32GB memory. Now I explore how to upgrade my computer SSD, to test for million files and trillion rows scenarios. I have opened my source code for Polars team, use or not use is their option.

**Comment by ritchie46** [comment]
Thank you for creating a repro @Bidek56. 

On my linux machine it fails with 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" })', /home/ritchie46/code/polars/polars/polars-lazy/polars-pipe/src/executors/sources/csv.rs:57:14
```

So I am looking into that. Maybe on windows it stackoverflows when many file handles are open? This is just a guess on my side, I have no expertise on that.

**Comment by hkpeaks** [comment]
I have similar experience when I extend to support a folder which contain 100,000 files. After many many amendments of the code, I have solved the issues but not remember it very clearly which changed of code can support 100,000 files. https://github.com/hkpeaks/peaks-consolidation/blob/main/src/file.go

**Comment by ritchie46** [comment]
> Our house water tank is small, but I enjoy unlimit water supply. Sometime suspension of water supply is due to cleaning of water tank. I have not hear so called crashing of water tank.

@hkpeaks just curious. Is this an analogy?

**Comment by hkpeaks** [comment]
I test on Windows, you test on Linux. Development environment is not exactly the same.

May be due to my background  is an accountant, not very understand the need of MWE to support your bug fix for this scenario. My MWE for many file is very simple https://github.com/hkpeaks/peaks-consolidation/blob/main/CombineFile.txt

ReadFile{C:\peaks-consolidation-main\Input\1000SmallFiles\*.csv ~ Table}
WriteFile{Table ~ PeaksCombineFile.csv}

How to copy so many file, I use Bing Chat to gen target copy file code directly.

**Comment by hkpeaks** [comment]
Congratulations on achieving the second stage of success with Polars! I hope you continue to excel and reach the third stage of success with the AI/BI apps on a new cloud platform. Best of luck! 😊

Now  I am rewritten wholly of my Peaks, to provide both Python and Go version using a new ETL Framework. https://github.com/hkpeaks/pypeaks 

Since there are no official support Golang can build binary library for Windows platform, so it is no proper way to create Python bindings. So the ETL Framework for Python I will use Apache Arrow compatible python dataframe libraries as calc engine. If I use Rust, I do not comfort with the use of Rayon-rs. Reconsider using C# is alternative option when Microsoft in recent years is very active to involve the Python language. But the disadvantage of C# is framework dependent. And .net is changing the game very frequently.
