### ISSUE TITLE
LazyCsvReader based melt + groupby causes panic

### ISSUE THREAD

**Issue by 9SMTM6** [pola-rs/polars#9202]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Title for rough idea, example for details. 

AFAICT the fix for  https://github.com/pola-rs/polars/issues/4997 should be in the latest version. This panic is also caused in a different file and with different setups.

However, considering that that similar setup already caused issues, perhaps It'd be a good idea add a few of these situations to the tests. I could probably contribute test cases in the future to spot regressions in different paths/ spot other connected issues, but right now I need my time otherwise.

### Reproducible example

`main.rs`:
```rs
use polars::{
    lazy::{dsl, frame::OptState},
    prelude::{
        self as pl, 
        // IntoLazy as _, 
        LazyFileListReader as _, 
        // NamedFrom,
    },
};

fn main() {
    // this causes no panic
    // let csv = pl::DataFrame
    //     ::from_iter([pl::Series::new("row1", &[1,2]), pl::Series::new("row2", &["ab", "etb"])])
    //     .lazy()
    //     .with_optimizations(OptState { ..Default::default() })
    // ;
    let csv = pl::LazyCsvReader::new(format!("test.csv"))
        .finish()
        .unwrap()
        // we dont need to change any optimizations form default to get the error,
        // but without this it doesnt fail...
        // Considering that all these optimizations probably lead to different paths
        // being executed, please check all of them if a resolution is found!
        .with_optimizations(OptState {
            // common_subplan_elimination: false,
            // streaming: true,
            // doesnt work with or without that option
            // file_caching: false,
            ..Default::default()
        });
    dbg!(csv
        .melt(pl::MeltArgs {
            id_vars: vec!["row1".into()],
            value_vars: vec!["row2".into()],
            streamable: true,
            variable_name: Some("var".into()),
            value_name: Some("val".into()),
        })
        .groupby(&[dsl::col("var")])
        .agg(&[dsl::col("val"),])
        .collect()
        .unwrap());
}
```
`test.csv`:
```csv
row1,row2,
1,ab,
2,etb,
```
panic:
```sh
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/min_example`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/[snip]/polars-lazy-0.30.0/src/physical_plan/file_cache.rs:55:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: polars_lazy::physical_plan::file_cache::FileCache::read
   4: polars_lazy::physical_plan::state::ExecutionState::record
   5: <polars_lazy::physical_plan::executors::scan::csv::CsvExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   6: <polars_lazy::physical_plan::executors::udf::UdfExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   7: <polars_lazy::physical_plan::executors::udf::UdfExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   8: <polars_lazy::physical_plan::executors::groupby::GroupByExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   9: polars_lazy::frame::LazyFrame::collect
  10: min_example::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

Shouldn't panic but behave correctly, such as the code without lazycsvreader (uncomment these lines, comment lazycsv variant).

### Installed versions

<details>
polars = { version = "0.30.0", features = ["streaming", "lazy", "csv", "strings", "fmt", "describe", "cse"] }
</details>

**Comment by ritchie46** [comment]
Can somebody confirm the same issue with a python example?

**Comment by zundertj** [comment]
I cant reproduce in Python:

```python
>>> pl.scan_csv("~/test.csv").melt(id_vars="row1",value_vars="row2",variable_name="var",value_name="val").groupby("var").agg("val"
).collect()     
shape: (1, 2)
┌──────┬───────────────┐
│ var  ┆ val           │
│ ---  ┆ ---           │
│ str  ┆ list[str]     │
╞══════╪═══════════════╡
│ row2 ┆ ["ab", "etb"] │
└──────┴───────────────┘

```

But I dont think we have something as the below in the Python API either?

```rust
.with_optimizations(OptState {
            // common_subplan_elimination: false,
            // streaming: true,
            // doesnt work with or without that option
            // file_caching: false,
            ..Default::default()
        })
```

I tried on the `collect()` to set `streaming=True`, but that also works.

**Comment by 9SMTM6** [comment]
@ritchie46 Are you unable to reproduce it with the Rust code? I was using it on stable-x86_64-unknown-linux-gnu (`rustup toolchain list`).

The `streamable` parameter in MeltArgs can apparantly also be false, same panic.

The output of the python sample matches what I get with the 'lazified Dataframe'.

**Comment by 9SMTM6** [comment]
I've also tried polars 0.29, got the same error (that one had different features tho I think).

**Comment by 9SMTM6** [comment]
Huh. Yeah. Rust code with
```rs
            .with_streaming(true)
            // optional, to suppress disclaimer
            .with_common_subplan_elimination(false)
```
instead of the `with_optimizations` is also working fine.

Thats really weird stuff.

**Comment by 9SMTM6** [comment]
Calling `without_optimizations()` also fails! The one common thing I can see is that without_optimizations() assigns a new struct, while with_streaming etc only assign the value to a single field.

Not sure how, but does that perhaps in some super indirect way invalidate the hash of FileFingerPrint, which is used for the lookup?! I've never seen such a thing from Rust, only other languages, but I've got no other ideas.

**Comment by 9SMTM6** [comment]
I believe that MAY be a separate issue, but the groupby + agg following melt also seem to somehow remove any streaming from the resulting plan. Looking at the output of `.explain(true)` without these basically everything (which isnt much at that point) is wrapped in the`--PIPELINE`... comment(? what even is that syntax based on? SQL), with these theres no trace left of this. This is different from the behavior I saw with other things that were incompatible with streaming (eg `with_row_count`) where it just limited the streaming to a very small part of the plan.

This has been my observation in the project that this issue came from, and would aos have to be solved for my usecase to be possible.

For the moment I guess I'll just have to keep my fingers of the streaming mode, and stick that stuff in a cluster where I can throw RAM at it, even if that means I'll have to upload several gigabyes of data to the server, which will take ages, even if its wasteful and will mean I can't really iterate with out huge breaks.

An old version of the project is on discord/polars-developement. THe issue mentioned there I can work around- mostly extremly surprising and makes debugging annoying - , this one is a much harder regression.

The code also contains a few comments regarding other surprising behaviors that I cant really put into issue form right now.

**Comment by 9SMTM6** [comment]
> Calling `without_optimizations()` also fails! The one common thing I can see is that without_optimizations() assigns a new struct, while with_streaming etc only assign the value to a single field.
> 
> Not sure how, but does that perhaps in some super indirect way invalidate the hash of FileFingerPrint, which is used for the lookup?! I've never seen such a thing from Rust, only other languages, but I've got no other ideas.

That didn't really make sense. I investigated further. I think I've isolated the issue.

```rs
// this works
.with_optimizations(OptState {
            file_caching: true,
            ..Default::default()
        })
// this doesn't
.with_optimizations(OptState {
            file_caching: false,
            ..Default::default()
        })
```

I didn't think of turning file caching manually on.

If thats the cause either the API should be changed, or at the very least a big disclaimer should be added. In particular turning that off is part of Default::default.

**Comment by 9SMTM6** [comment]
Closing this. The root cause for this issue was made clearer in a new issue. I'll hopefully get around to creating other issues for other things I discussed here / that made this issue be so confusing to me
