### ISSUE TITLE
memory does not get freed

### ISSUE THREAD

**Issue by kootenpv** [pola-rs/polars#9225]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I like using polars interactively but I have noticed it blows up my memory really quickly when I keep reloading dataframes

### Reproducible example

when I use:

```python
>>> pl.read_parquet("my.parquet")
>>> pl.read_parquet("my.parquet")
>>>
```

it actually keeps the objects around in ipython (this is not the case for pandas).

I understand this, so I wrote something to delete the object from memory.

I made a helper function for myself, but even with that, I don't see a way to free up previous memory.

setup (I understand this should only clean up previous dangling dataframes, not the current one):

```python
import polars as pl
pl._read_parquet = pl.read_parquet

def cleanup_pl(*args, **kwargs):
    gls = globals()
    for k in list(gls):
        v = gls[k]
        if k.startswith("_") and isinstance(v, pl.DataFrame):
            del gls[k]
    return pl._read_parquet(*args, **kwargs)

pl.read_parquet = cleanup_pl
```

I can see that the objects disappears from the globals dictionary, but still the memory does not get freed.

how can I achieve this?

### Expected behavior

while I understand I can assign it to a variable and then delete, I'd prefer to be able to have temporary reads and not worry about deleting the objects (hence my own hook)

I would expect though that when there are no references to the polars dataframe that it would get cleaned up

### Installed versions

pip install polars==0.18.0

**Comment by kootenpv** [comment]
I think it should not have rust tag but python tag, my bad!

**Comment by ritchie46** [comment]
That's how memory allocators work. They keep a hold of freed memory and don't give it back to the OS. They will reuse that memory. So if you would run that snippet in a loop memory usage would saturate.

**Comment by CodeCoral** [comment]
@ritchie46 Can you please elaborate on this:  `That's how memory allocators work.` or give any reference that explains the why ?

**Comment by ritchie46** [comment]
> @ritchie46 Can you please elaborate on this: `That's how memory allocators work.` or give any reference that explains the why ?

https://stackoverflow.com/questions/45538993/why-dont-memory-allocators-actively-return-freed-memory-to-the-os
