### ISSUE TITLE
Consider using #[track_caller] + std::panic::Location::caller() in expression contexts

### ISSUE THREAD

**Issue by 9SMTM6** [pola-rs/polars#9237]
### Problem description

For reference: https://doc.rust-lang.org/reference/attributes/codegen.html#the-track_caller-attribute

Polars deals with a lot of delayed execution, which is invoked via executors, where the stack trace doesn't show the location the "code" thats executed was provided from.

While working on a few of the issues I've earlier alluded to, and generally, I've observed how much easier things were to track down panics even in delayed execution, if they happened inside of my "own" code, even if that code was a Closure that get executed in a delayed fashion. The reason is that panics of course include the source code location. Meanwhile, when I made an assertion with Polars expressions, stuff like polars_plan::dsl::Expr::cast, this was often very hard to track down, because I might have multiple cast candidates. And as said eariler, because of delayed execution, the stack trace often also isn't helpful.

However, if one would use the #[track_caller] attribute - which is how unwrap etc are implemented in rust to show source code locations - and then save the result of std::panic::Location::caller() in the descriptor for potentially failing expressions, then one should be able to show the source code location when it actually fails.

This is a huge ask. I can imagine though that this would cut down on a lot of issues where people misunderstood the problem at hand, and thus it could pay off.

One big negative is that I'm not aware of a Python equivalent (track_caller + std::panic::Location::caller rely on compiler support), so supporting this feature in that API (and others, I have no clue of R, not aware of similar JS functionality either) might be harder or impossible. This means that the wins would be reduced.

**Comment by 9SMTM6** [comment]
Any reaction? I could probably submit an experimental PR that does this for some things, if that helps understanding @ritchie46. The feature ought to be able to be placed behind a feature too.

Frankly even when just using the lazy API without stuff like streaming, I've seen all kinds of bugs or at least for me unexpected behaviors, which would be much easier to diagnose with something like this.

**Comment by ritchie46** [comment]
I am not sure of this. How is that tracked? Doesn't cost that runtime performance and extra code in the binary?

**Comment by 9SMTM6** [comment]
That's why I said it should be possible to place it behind a feature. 

Yeah, just like any code using panics, this leads to paths being in the resulting binary, and while without track caller these strings are limited to paths in your crate, with track caller you'll have these for the definition location.

Regarding runtime costs, yeah, obviously it has some runtime costs. But the performance limiting thing when using polars doesn't tend to be the size of the expression themself. You will be better able to answer this, if panics connected with, dunno the wrong datatype somewhere, don't get created in the hot code, it should be neglegible.

Also, I mean, binaries with debug info also have runtime costs. Still they get used, sometimes even in production, if the alternative is the software not working without having an idea why.

**Comment by 9SMTM6** [comment]
There's a disconnect between things you express in your lazy API, and the full evaluation of the expression. And when the validation doesn't work out, I commonly only get a stack trace from the polars runtime up, not helpful.

What I suggest is applying track_caller to at least some of the expressions that can end up failing, then one can call core::panic::Location::caller() to get a static reference to the location in library code.

This would need to be transported to the location where the panic is actually caused in the end. So eg place it in a field (behind a feature) in the struct representing this expression.

**Comment by 9SMTM6** [comment]
This location then gets printed in the panic text, as the true location. Or something like that.

**Comment by ritchie46** [comment]
I don't know. We don't want to panic, and now we want to add more info to the panics when we do. We are trying to remove all the panics and ensure we error in such a case.

**Comment by 9SMTM6** [comment]
Right. I wasn't particularly careful, again, sorry for that. Yeah, many issues (though not all) I had did concern errors not panics, that just got surfaced by an unwrap on my code. But with that its still often hard to track down what's going wrong where, as what you're unwrapping is a large aggregate of different assumptions, and often the errors don't contain enough Information. 

Also btw the information presented tends to be debug formatted, which is also difficult to read because this means newlines don't get interpreted as newlines but as \n, which breaks formatting - but thats separate.

In my experience with this library I think I've often used the API in potentially unintended ways, which contributes to the confusion. But the issue is that this misuse often isn't transparent to me. According to documentation were supposed to rename columns in select, but why were supposed to do that but - I beliefe this is protected against with a fairly clear panic or an error - not change the datatype in there isn't immediately clear to me. Since the API isn't super widely documented I have to come up with how to use it, and some hacks seem to me required and as intended.

And the issue is that very often things seem to work a long time beyond the root cause when you're using the API wrong.

Perhaps we could also speak on discord or similar with me demonstrating some of the things to you. I'm often very uncertain what is the issue, and even if I know, it's hard to put into issue form and find the root cause. This is what caused the issue I closed myself.

There's stuff like a panic I get, that I can "fix" by putting `.collect().unwrap().lazy()` between, which I don't think should happen? I BELIEFE that this panic is the result of an unreachable in a Debug trait impl caused by it not knowing a type, for some reason.

**Comment by 9SMTM6** [comment]
It was the Display impl that panics:

```sh
thread 'main' panicked at 'internal error: entered unreachable code', /home/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.30.0/src/datatypes/dtype.rs:333:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: <polars_core::datatypes::dtype::DataType as core::fmt::Display>::fmt
   4: core::fmt::write
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5: core::fmt::Write::write_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:197:9
   6: alloc::fmt::format::format_inner
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/fmt.rs:612:9
   7: polars_plan::logical_plan::functions::FunctionNode::schema
   8: polars_plan::logical_plan::schema::<impl polars_plan::logical_plan::LogicalPlan>::schema
   9: polars_plan::logical_plan::builder::LogicalPlanBuilder::with_columns
  10: polars_lazy::frame::LazyFrame::with_column
  11: local::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The thread I closed I'm referring to is https://github.com/pola-rs/polars/issues/9202

**Comment by 9SMTM6** [comment]
I do realize that in this panic case my suggestion would not help. In this case it seems to me that an earlier panic or error somewhere else is required. Still it'd help in many other situations.

**Comment by stinodego** [comment]
Thanks for the suggestion - I'll close this in favor of #10149. We can discuss the right way to achieve better error messages under  that issue.
