### ISSUE TITLE
`pl.lit` + `pl.struct` inside `.groupby` raises `ComputeError` / `InvalidOperationError`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9238]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Follow on from #9217 - after applying that fix:

If `pl.lit()` is the first argument to `pl.struct()` it raises.

The exception changes if an `.alias()` is added.

If `pl.lit()` is the 2nd argument, there is no error.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(dict(unique_id = ["a", "b"]))

# OK - pl.lit() second arg 
df.groupby(True).agg(pl.struct("unique_id", pl.lit("moo")))

# shape: (1, 2)
# ┌─────────┬────────────────────────────┐
# │ literal ┆ unique_id                  │
# │ ---     ┆ ---                        │
# │ bool    ┆ list[struct[2]]            │
# ╞═════════╪════════════════════════════╡
# │ true    ┆ [{"a","moo"}, {"b","moo"}] │
# └─────────┴────────────────────────────┘

# NOT OK - pl.lit() first arg
df.groupby(True).agg(pl.struct(pl.lit("moo"), "unique_id"))

# ComputeError: unable to find root column name for expr '{expr:?}' when calling 'output_name'

# Adding `.alias()` raises different error:
df.groupby(True).agg(pl.struct(pl.lit("moo").alias("name"), "unique_id"))

# InvalidOperationError: output length of `map` (1) must be equal to the input length (2); consider using `apply` instead
```

### Expected behavior

No exception.

### Installed versions

<details>

```
Latest commit from main.
```

</details>

**Comment by stinodego** [comment]
This has been fixed on main. Note that your second example raises a `DuplicateError`, as the first column of a struct is set to the name of the struct column, and it is the same as the `True` literal passed to `group_by`.
