### ISSUE TITLE
It's seems LazyFrame.sink_parquet not finish write file.

### ISSUE THREAD

**Issue by natir** [pola-rs/polars#9243]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

First  Thank for your amazing work.

I concatenate several parquet files and use unique to eliminate duplicates before writing the result. I perform the operation in a Lazy way.

When I try to read the file with `pqrs` all goes well at first and then I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EOF("Not enough bytes to decode")', /srv/conda/cargo/registry/src/github.com-1ecc6299db9ec823/parquet-12.0.0/src/record/reader.rs:578:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

When I try to read them with polars I get the error:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `0`', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow2-0.17.2/src/io/parquet/read/deserialize/primitive/basic.rs:53:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It seems to me that the file isn't completely written on the disk.  Maybe a flush is missing.
The behavior occurs whether the value of POLARS_MAX_THREADS env value is 1 or some other value.

### Reproducible example

```python
paths = [{a list of parquet file with same struct and a column id}]
output = "/any/path/you/want"

lf = polars.concat([polars.scan_parquet(path) for path in paths])

lf = lf.unique(subset=("id"))

lf.sink_parquet(output)

##### 

df = polars.read_parquet(output)
```

### Expected behavior

`sink_parquet` write the end of the file correctly :)

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-glibc2.17
Python:      3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29)
[GCC 10.4.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.0
connectorx:  0.3.1
deltalake:   0.9.0
fsspec:      2023.5.0
matplotlib:  3.4.3
xlsx2csv:    0.8.1
xlsxwriter:  3.0.9
```

File system: ext4

</details>

**Comment by natir** [comment]
Sorry It's hard to produce a MWE because I work on human genome data but not impossible.

And in fact I realized that my `how to reproduce` was not good.

I don't do `unique` on one column but on 4 columns (2 uint64 and 2 utf8). On one uint64 column  I haven't any trouble.

**Comment by natir** [comment]
I found a way to get MWE, sorry, it's need to download a files (around 100 Mb), I tried to reproduce the bug with only the beginning of this files but it's not enough.

You need to execute this bash command

```bash
URI_ROOT="https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release"
curl ${URI_ROOT}/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz | gunzip - | grep -v '^#' | cut -d$'\t' -f 1-4 > HG002.csv 
```

And run this python script (I try with python3.11)
```python
import polars

lf = polars.scan_csv(
    f"HG002.csv",
    new_columns=["chr", "pos", "ref", "alt"],
    has_header=False,
    separator="\t",
)

lf = lf.with_columns(
    polars.col("chr")
    .str.replace("chr", "")
    .str.replace("X", "23")
    .str.replace("Y", "24")
    .str.replace("MT", "25")
    .str.parse_int(10, strict=False)
    .cast(polars.UInt8)
)

lf = lf.with_columns(
    polars.concat_str(
        [
            polars.col("chr"),
            polars.lit("-"),
            polars.col("pos"),
            polars.lit("-"),
            polars.col("ref"),
            polars.lit("-"),
            polars.col("alt"),
        ],
    )
    .hash()
    .alias("id"),
)

lf = lf.select(["id", "chr", "pos", "ref", "alt"])

lf = lf.unique(subset=("chr", "pos", "ref", "alt"))

lf.sink_parquet("merge.parquet")

df = polars.read_parquet("merge.parquet")

print("If you see this you didn't reproduce the bug.")
```

Sorry some step could seems strange, but I need it in my original code and I need it to reproduce bug in this example.

While writing this example I realized that if I comment on the line:
```
lf = lf.select(["id", "chr", "pos", "ref", "alt"])
```

The bug didn't occur, as the order of the columns wasn't important in my current usage, I found a way around it.  But it seems very strange to me that the order of the columns could trigger this bug.

**Comment by ritchie46** [comment]
Thank you @natir. I can reproduce

**Comment by ritchie46** [comment]
Fix coming up. It turned out we actually wrote the chunks in the wrong schema order after the unique changed the order.

**Comment by natir** [comment]
Thank for your reactivity, just a question, When can I expect the patch to be included in a release?
