### ISSUE TITLE
~dot or~ matmul  not supported

### ISSUE THREAD

**Issue by michaelice** [pola-rs/polars#925]
The operation Dot in pandas is useful. Hope added behind a feature flag.

**Comment by ritchie46** [comment]
Do you use this from Rust? Polars has the ability to convert to `ndarray` which has linear algebra support.

**Comment by MarcoGorelli** [comment]
> But if you try to do this on DataFrame level, it seems to run it per series? I'm not sure if the output is correct.
> # 5x3 dot 5*1 should not be possible (misaligned matrices)

This looks correct to me - what the syntax provided means is that, for each of the columns `'a', 'b', 'c'`, to evaluate the dot product with column 'a'

**Comment by orlp** [comment]
Implementing matrix multiplication efficiently is rather involved, and it means either re-implementing BLAS or linking with BLAS. Neither of those things are things we'd like to do in Polars at this time. But Polars has good inter-op with numpy so this shouldn't be a big limitation.

**Comment by cmdlineluser** [comment]
Looks like it has some polars interop @alippai: 
- <sup>https://github.com/sarah-ek/faer-rs/blob/50affce6a66d75a0456e932df213a80969352825/faer-libs/faer/src/lib.rs#L4069-L4071</sup>

It seems it's used in the  [polars-ds](https://github.com/abstractqqq/polars_ds_extension) extension:

- https://github.com/abstractqqq/polars_ds_extension/blob/main/src/num_ext/ols.rs</sup>

**Comment by orlp** [comment]
@alippai You can argue that faer-rs is a BLAS implementation. They themselves say

> It exposes a high level abstraction over a lower level API, similar to the one offered by BLAS/Lapack libraries, modified to better match the capabilities of modern computers

For the moment I feel this is better left to an extension, or done with numpy interop. It would make polars quite a bit bigger and need new expertise.

**Comment by alippai** [comment]
SQL:2023 added multidimensional arrays recently. As it’s an ISO standard (paid) I’m not sure what’s included, but I can imagine it narrows, standardizes the scope avoiding the feature bloat. I have a feeling it’s similar to your recent Array type additions
