### ISSUE TITLE
Respect `flags` after applying `offset_by` transformation

### ISSUE THREAD

**Issue by chaaland** [pola-rs/polars#9252]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I _think_ that applying `.dt.offset_by` to a date column should preserve sortedness of that column. Use case was that I was doing a `join_asof` with a dataframe and itself, lagged by one year, and getting an error about `join_asof` requiring the column to be sorted.

### Reproducible example

```python
import polars as pl
from datetime import date

foo = pl.DataFrame({"a":[date(2001,1,1), date(2002,1,1), date(2003, 1,1)]})
foo = foo.select(pl.col("a").set_sorted())
foo["a"].flags
# {'SORTED_ASC': True, 'SORTED_DESC': False}

foo = foo.with_columns(pl.col("a").dt.offset_by("1d"))
foo["a"].flags
# {'SORTED_ASC': False, 'SORTED_DESC': False}
```

### Expected behavior

I would think the flags from the original "a" column should be preserved under a monotonic transformation like `offset_by`.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    macOS-10.16-x86_64-i386-64bit
Python:      3.10.9 (main, Jan 11 2023, 09:18:20) [Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.2
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.0
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by CHDev93** [comment]
@ritchie46 thanks for the insanely quick fix! Should the same be done for`.dt.truncate`? They're may be other monotonic functions in the API but that's the other obvious one to me

**Comment by ritchie46** [comment]
Yes, please open an issue (or PR) for any function you can find that should remain flags, but doesn't
