### ISSUE TITLE
Regression from 0.17.15: ne_missing (0.18.0) behaves differently from ne (0.17.15)

### ISSUE THREAD

**Issue by datenzauberai** [pola-rs/polars#9256]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As I understand, the new `ne_missing` should replicate the behavior of `ne` in 0.17.15 after #9035 has been implemented.

When replacing ne with ne_missing I came across a strange behavior that does not match `ne` in 0.17.15:

Combining ne_missing with another Boolean expression raises `cannot unpack series of type 'i64' into 'bool'`.
However, doing the same combination in two steps (calculate Series with ne_missing first), does not raise an error.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "a": [0, 1, None],
    "b": [True, False, True]
})

# 1. ne works
df.select(pl.col("a").ne(0).or_(pl.col("b")))

# 2. ne_missing fails with: cannot unpack series of type `i64` into `bool`
df.select(pl.col("a").ne_missing(0).or_(pl.col("b")))

# 3. ne_missing works when calculated separately
df.with_columns(pl.col("a").ne_missing(0)).select(pl.col("a").or_(pl.col("b")))
```

### Expected behavior

All three cases should show the same behavior and should not fail.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.11.3 (main, May 13 2023, 07:40:09) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       <not installed>
pandas:      <not installed>
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks. Fix coming up.
