### ISSUE TITLE
join cardinality validation

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#9263]
### Problem description

I believe we can add (most of) these validation for free inside the join engine. (This wouldn't include streaming)

https://stackoverflow.com/questions/76414161/how-do-i-add-cardinality-validation-to-a-polars-join

**Comment by DeflateAwning** [comment]
I think this issue can be closed now

**Comment by mkleinbort-ic** [comment]
The cardinality validation feature could support more things (eg. multi-key joins) but that should rightly be it's own issue.

**Comment by DeflateAwning** [comment]
I created a separate issue for the multi-key joins: https://github.com/pola-rs/polars/issues/10784
