### ISSUE TITLE
Filter pushdown to pyarrow is broken for boolean series

### ISSUE THREAD

**Issue by himikof** [pola-rs/polars#9273]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Since #8930 small literal series are getting pushed down to pyarrow dataset filters, but the new code does not handle boolean series properly. They currently get serialized as `[true,true,true]`, leading to a `NameError` during `eval()`.

### Reproducible example

```python
import polaris as pl
import pyarrow.dataset

pl.DataFrame({"foo": [1, 2, 3]}).write_parquet('test-crash.parquet')
q = pl.scan_pyarrow_dataset(pyarrow.dataset.dataset('test-crash.parquet'))
q.filter(pl.Series([True] * 3)).collect()

# Crashes with ComputeError: NameError: name 'true' is not defined
```

### Expected behavior

Filtering should just work without crashing.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.17.12-100.fc34.x86_64-x86_64-with-glibc2.33
Python:      3.9.13 (main, May 18 2022, 00:00:00) 
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks, fix coming up.
