### ISSUE TITLE
Logical or operator ("|") fails for multiple filter expressions applied tot the same column

### ISSUE THREAD

**Issue by laakejs** [pola-rs/polars#929]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.8.8

#### What operating system are you using polars on?

Python 3.6.9 on Ubuntu 18.04 (WSL)

#### Describe your bug.

When applying multiple logical (or) operations on the same column (or a copy of this column) in one filter() expression the result does not behave as expected. It seems like only one of the expressions is evaluated. 

#### What are the steps to reproduce the behavior?

**Example**

```python
import polars as pl
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, 4],
        "names": ["ham", "spam","foo", None],
        "names2": ["ham", "spam","foo", None],
    }
)
# working example with different columns
print(df.filter((col("nrs") <= 2) | col("names").is_null()))
# Bug example
print(df.filter(col("names").str.contains("am") | col("names").is_null()))
# Bug example with differend order
print(df.filter(col("names").is_null() | col("names").str.contains("am")))
# Bug example with two differnd columns
print(df.filter(col("names").str.contains("am") | col("names2").is_null()))
```

```
shape: (3, 3)
╭─────┬────────┬────────╮
│ nrs ┆ names  ┆ names2 │
│ --- ┆ ---    ┆ ---    │
│ i64 ┆ str    ┆ str    │
╞═════╪════════╪════════╡
│ 1   ┆ "ham"  ┆ "ham"  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ "spam" ┆ "spam" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4   ┆ null   ┆ null   │
╰─────┴────────┴────────╯
shape: (2, 3)
╭─────┬────────┬────────╮
│ nrs ┆ names  ┆ names2 │
│ --- ┆ ---    ┆ ---    │
│ i64 ┆ str    ┆ str    │
╞═════╪════════╪════════╡
│ 1   ┆ "ham"  ┆ "ham"  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ "spam" ┆ "spam" │
╰─────┴────────┴────────╯
shape: (2, 3)
╭─────┬────────┬────────╮
│ nrs ┆ names  ┆ names2 │
│ --- ┆ ---    ┆ ---    │
│ i64 ┆ str    ┆ str    │
╞═════╪════════╪════════╡
│ 1   ┆ "ham"  ┆ "ham"  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ "spam" ┆ "spam" │
╰─────┴────────┴────────╯
shape: (2, 3)
╭─────┬────────┬────────╮
│ nrs ┆ names  ┆ names2 │
│ --- ┆ ---    ┆ ---    │
│ i64 ┆ str    ┆ str    │
╞═════╪════════╪════════╡
│ 1   ┆ "ham"  ┆ "ham"  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ "spam" ┆ "spam" │
╰─────┴────────┴────────╯
```

#### What is the expected behavior?

The result should be the "working example" in any case.

**Comment by ritchie46** [comment]
Thanks for your example. This is due to the null value propagating in the or operation. This is probably never what is intended by the user and is something I will fix.

**Comment by jorgecarleitao** [comment]
check out kleene logic: https://en.wikipedia.org/wiki/Three-valued_logic

Arrow (and arrow2) have the kleene versions of AND and OR :)

**Comment by ritchie46** [comment]
> check out kleene logic: https://en.wikipedia.org/wiki/Three-valued_logic
> Arrow (and arrow2) have the kleene versions of AND and OR :)

Thanks a lot @jorgecarleitao , I did not realize this very _clean_ solution for this. (pun, not intended) ;)

**Comment by ritchie46** [comment]
Fixed and released :+1:
