### ISSUE TITLE
Agg "horizontal function" not working when only one row in group

### ISSUE THREAD

**Issue by KasperLin** [pola-rs/polars#9299]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

"Horizontal function" (such as [`pl.max`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.max.html) / [`pl.sum`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.sum.html)) seems not working when the aggregation (`groupby` / `over`) *has only one row* in the group, raising error :  

```
ComputeError: cannot aggregate as {}, the column is already aggregated
```

> Some speculations : 
> * Might be related to #6185 
> * Seems like the function is trying to work vertically in this case, instead of horizontally
> * Technically, same issue happens when there's "zero row" in the group, like an empty dataframe

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [0], "b": [1]})
df.groupby("a").agg(pl.max(["b", 0]).sum())
# ComputeError: cannot aggregate as {}, the column is already aggregated
```

### Expected behavior

Once the group has more than one row, it works as expected : 

```python
import polars as pl
df = pl.DataFrame({"a": [0], "b": [1]})
df = pl.concat([df] * 2)
df.groupby("a").agg(pl.sum(["b", 1]).sum())
```

Avoid a "horizontal function" can also work, as always : 

```python
import polars as pl
df = pl.DataFrame({"a": [0], "b": [1]})
df.groupby("a").agg((pl.col("b") + 1).sum())
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.1
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     11.0.0
connectorx:  0.3.0
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  <not installed>
```

</details>

**Comment by stinodego** [comment]
This now seems to work as expected.
