### ISSUE TITLE
`fields` parameter in `.list.to_struct` accepts "invalid" inputs

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9305]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is a user-error issue but:

I thought it might be possible to read fields from a column so I tried `fields = "column_name"` which ends up using individual characters as field names.

Upon noticing this, I tried some other random inputs which lead to various PanicExceptions.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"value": [["a", "b", "c"], ["d", "e"]], "count": [[1, 2, 3], [4, 5]]})

# shape: (2, 2)
# ┌─────────────────┬───────────┐
# │ value           ┆ count     │
# │ ---             ┆ ---       │
# │ list[str]       ┆ list[i64] │
# ╞═════════════════╪═══════════╡
# │ ["a", "b", "c"] ┆ [1, 2, 3] │
# │ ["d", "e"]      ┆ [4, 5]    │
# └─────────────────┴───────────┘

df.with_columns(
   pl.col("count").list.to_struct(fields = "value", n_field_strategy="max_width")
).unnest("count")

# shape: (2, 4)
# ┌─────────────────┬─────┬─────┬──────┐
# │ value           ┆ v   ┆ a   ┆ l    │
# │ ---             ┆ --- ┆ --- ┆ ---  │
# │ list[str]       ┆ i64 ┆ i64 ┆ i64  │
# ╞═════════════════╪═════╪═════╪══════╡
# │ ["a", "b", "c"] ┆ 1   ┆ 2   ┆ 3    │
# │ ["d", "e"]      ┆ 4   ┆ 5   ┆ null │
# └─────────────────┴─────┴─────┴──────┘

df.with_columns(
   pl.col("count").list.to_struct(fields = "A")
)

# PanicException: called `Result::unwrap()` on an `Err` value: 
# PyErr { type: <class 'IndexError'>, value: IndexError('list index out of range'), traceback: Some(<traceback object at 0x126f74880>) }

df.with_columns(
   pl.col("count").list.to_struct(fields = 1234)
)

# PanicException: called `Result::unwrap()` on an `Err` value: 
# PyErr { type: <class 'TypeError'>, value: TypeError("'int' object is not callable"), traceback: None }
```

### Expected behavior

I'm not sure.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.1
Index type:  UInt32
Python:      3.10.9 (main, Jan 14 2023, 16:56:26) 

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.8.2
matplotlib:  3.5.1
xlsx2csv:    0.8
xlsxwriter:  3.0.8
```

</details>

**Comment by alexander-beedie** [comment]
That actually looks like correct behaviour; I think you may have misread the docstring for the "fields" param? It is used to _name_ the fields it finds, by index. So, by passing "value", you are going to name the value at index 0 as "v", the value at index 1 will be "a", etc.

The errors are also expected - you are creating a struct from a nested list (in the "count" column) that has up to three elements (1, 2, 3), but you have not provided enough names. The letter "A" will only cover the first of those values; when it comes to name the second and third, you get an index error.

**Comment by cmdlineluser** [comment]
Thank you for the explanation @alexander-beedie - sorry for the noise.
