### ISSUE TITLE
Wrong time stamp when converting to pyarrow for dates after 2038

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#9315]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following outputs:
```python
>>> print(df)
shape: (1, 1)
┌─────────────────────────────┐
│ a                           │
│ ---                         │
│ datetime[μs, America/Boise] │
╞═════════════════════════════╡
│ 2038-03-14 03:00:00 MDT     │
└─────────────────────────────┘
>>> print(tbl['a'][0])
2038-03-14 02:00:00-07:00
```

The practical result of this is that when converting to pandas, the datetime isn't the same:
```python
>>> df
shape: (1, 1)
┌─────────────────────────────┐
│ a                           │
│ ---                         │
│ datetime[μs, America/Boise] │
╞═════════════════════════════╡
│ 2038-03-14 03:00:00 MDT     │
└─────────────────────────────┘
>>> df.to_pandas()
                          a
0 2038-03-14 02:00:00-07:00
```

### Reproducible example

```python
import datetime as dt

import polars as pl

df = (
    pl.DataFrame(
        {'a': [dt.datetime(2038, 3, 14, 3)]}
    )
    .select(pl.col('a').dt.replace_time_zone('America/Boise'))
)
tbl = df.to_arrow()
print(df)
print(tbl['a'][0])
```

### Expected behavior

```python
>>> df.to_pandas()
                          a
0 2038-03-14 03:00:00-07:00
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.1
Index type:  UInt32
Platform:    Linux-5.4.0-149-generic-x86_64-with-glibc2.31
Python:      3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by MarcoGorelli** [comment]
Some other ones which differ:
```
['America/Adak', 'America/Boise', 'Africa/Abidjan', 'America/Anchorage', 'Asia/Famagusta', 'America/La_Paz', 'America/Indiana/Indianapolis']
```

Credit to @Honno for helping generate `hypothesis` tests to find this!

**Comment by alexander-beedie** [comment]
> Credit to @honno for helping generate hypothesis tests to find this!

Nice... :)  Let's integrate some version of those?

**Comment by honno** [comment]
> Nice... :) Let's integrate some version of those?

Feel free to request additional reviews from me on any PRs adding Hypothesis-powered tests, would love polars to adopt Hypothesis in its test suite :grin:

**Comment by alexander-beedie** [comment]
> Feel free to request additional reviews from me on any PRs adding Hypothesis-powered tests, would love polars to adopt Hypothesis in its test suite 😁

We already did - I wrote all of our polars-specific hypothesis primitives and merged them back here: https://github.com/pola-rs/polars/pull/3842, heh. Have a look in `tests/parametric` for some of the current examples; would be very happy to expand coverage (as long as the tests aren't too gargantuan ;)

We have dedicated `dataframes` and `series` strategies, as well as dtype-specific strategies, and so on.

**Comment by MarcoGorelli** [comment]
Looks like this one is wrong in both pyarrow and pandas due to pytz (https://github.com/apache/arrow/issues/15047), so closing this issue as an upstream bug

When writing the parametric tests, I was expecting to uncover a whole load of issues in polars - instead, [polars has come out as the more robust one here](https://github.com/pola-rs/polars/pull/9334#issue-1752060663)
