### ISSUE TITLE
Return of pl.mean is differrent with that of pandas

### ISSUE THREAD

**Issue by ysq151944** [pola-rs/polars#9318]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

i got different mean() return from pandas and polars

Here is the test data(5.02MB):

https://drive.google.com/file/d/1b8ntGWPp6Zo2ZF7mRyfVmB4DkzPpIK0e/view?usp=drive_link

### Reproducible example

```python
import polars as pl
import pandas as pd


df_pd = pd.read_parquet('test_data.parquet')
df_pl = pl.read_parquet('test_data.parquet')

print(df_pd['a1_p'].mean())  # 9188.875
print(df_pl.select(pl.col('a1_p')).mean())  #  9188.873047
```

### Expected behavior

pandas and polars should return the same value

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

--------Version info---------
Polars:      0.18.1
Index type:  UInt32
Platform:    Linux-5.15.0-57-generic-x86_64-with-glibc2.35
Python:      3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

</details>

**Comment by ysq151944** [comment]
even if I cast column 'a1_p' to pl.Float64, the result is still different from pandas:

print(df_pd['a1_p'].mean())
print(df_pd['a1_p'].sum() / df_pd.shape[0])
print(df_pl.sum() / df_pl.shape[0])
print(df_pl.select(pl.col('a1_p').cast(pl.Float64)).sum() / df_pl.shape[0])
print(df_pl.select(pl.col('a1_p').cast(pl.Float64).mean()))
print(df_pl.select(pl.col('a1_p').mean()))

**Comment by ritchie46** [comment]
Floating point data is not associative. Different algorithms have different rounding errors. Neither one will be exact. I suggest reading more on floating data types.

**Comment by s-banach** [comment]
I seem to remember that polars isn't using any kind of compensating summtion yet?

For example, I can run the following tests:

```python
import numpy as np
import polars as pl


def test_1():
    n = int(1e9)
    x = np.arange(1, n, dtype=np.float64)

    correct = n * (n - 1) / 2
    numpy_error = x.sum() - correct
    polars_error = pl.Series(x).sum() - correct

    assert numpy_error == 0
    assert polars_error > 0


def test_2():
    small = 1e-8
    big = 1e8

    x = np.empty(int(1e8) + 1)
    x[0] = big
    x[1:] = small

    correct = big + 1
    numpy_error = np.abs(x.sum() - correct)
    polars_error = np.abs(pl.Series(x).sum() - correct)

    assert polars_error > 700 * numpy_error
```

I don't personally have any kind of dataset where this error would make a difference, but it seems like a legitimate issue.

**Comment by ritchie46** [comment]
@s-banach I don't follow. What is the question/code?

**Comment by ritchie46** [comment]
Well even pandas mean is not the same to itself. If you use pyarrow ad backend the mean will be different as well. For instance that mean overflows by a naive sum / count.

**Comment by magarick** [comment]
To clarify a little floating point addition should be commutative, so `SUM(A) + SUM(B) == SUM(B) + SUM(A)` if `SUM(A)` and `SUM(B)` were computed in the same order but like you said it's not associative so it's possible that `(SUM(A) + SUM(B)) + SUM(C) != SUM(A) + (SUM(B) + SUM(C))`. That is, the order in which the slice results finish and are recombined matters.
There's a tradeoff between speed and accuracy/numerical stability. For most applications it won't matter and it's better to be faster. But sometimes precision counts, so it could be worth it to add a flag or option to choose between multiple algorithms.  I've seen this before. For example, in R, `data.table`'s `frollmean` function has this option. Even if parallelism makes perfect consistency impossible, errors do compound. So it might be worth it to allow correcting each slice.

**Comment by ysq151944** [comment]
> This type of thing has been discussed before: [#5325 (comment)](https://github.com/pola-rs/polars/issues/5325#issuecomment-1291294576)
> 
> Perhaps the conclusion is that "floating point differences shouldn't matter for legitimate data science applications".

"floating point differences shouldn't matter for legitimate data science applications" is exact what I want to say.

**Comment by avimallu** [comment]
+1 on the option for choosing a more exact algorithm like data.table's frollmean. I think the user can be given the option to choose a slower algorithm that is less prone to rounding error, and is commutative. Definitely doesn't matter for most data science cases, but for those special ones where it does, it should help greatly.

**Comment by ritchie46** [comment]
I am not convinced our mean is unprecice. Why would A+B be more precise than B+A. They can have different results, but one is not generally more precise than the other.

**Comment by alexander-beedie** [comment]
@ysq151944: I'd suggest raising this as a new feature request for [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) 👍

**Comment by ysq151944** [comment]
> @ysq151944: I'd suggest raising this as a new feature request for [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) 👍

You are right, this is more like a feature request.
