### ISSUE TITLE
SQL: Support parameters

### ISSUE THREAD

**Issue by alex** [pola-rs/polars#9321]
### Problem description

Right now SQL queries in `SQLContext.execute` take a string, there is no way to pass an external set of parameters. This means that all of the idioms for parameterizing a SQL query are vulnerable to SQL injection.

A solution might look like `ctx.execute("SELECT COUNT(*) FROM TABLE WHERE id = ?", (my_id,))`

**Comment by alexander-beedie** [comment]
Duplicate of https://github.com/pola-rs/polars/issues/8991 ;)

**Comment by alex** [comment]
Ooops, sorry about that!
