### ISSUE TITLE
TypeError when using set containing None with `is_in`

### ISSUE THREAD

**Issue by mishamsk** [pola-rs/polars#9322]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`is_in` function uses `sorted` internally to convert set/frozenset to a sequence, which fails if the set has None value.

Using say list with None, works.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": ["1", "2", "3"]})

print(df.filter(pl.col("a").is_in({"1", None})))
# Traceback (most recent call last):
#   File "polars_is_in_bug.py", line 5, in <module>
#     print(df.filter(pl.col("a").is_in({"1", None})))
#                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File ".venv/lib/python3.11/site-packages/polars/expr/expr.py", line 4272, in is_in
#     other = sorted(other)
#             ^^^^^^^^^^^^^
# TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

### Expected behavior

Sets should work where lists/tuples do

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.11.0 (main, Oct 25 2022, 16:13:21) [Clang 14.0.0 (clang-1400.0.29.102)]

----Optional dependencies----
numpy:       <not installed>
pandas:      <not installed>
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Fixed; thanks for the heads-up 👍

**Comment by mishamsk** [comment]
@alexander-beedie sure. always happy to help polars become better. Probably should have created PR directly, easy fix;-)
