### ISSUE TITLE
Panic when collecting JoinType::AsOf

### ISSUE THREAD

**Issue by jajetloh** [pola-rs/polars#9326]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Attempting to perform an JoinType::AsOf panics due to Polars attempting to unwrap Err with value
``ComputeError(ErrString("chunked array is not contiguous"))'``
at location
``polars-core-0.30.0/src/frame/asof_join/mod.rs:91:60``

If this is intended, Err should presumably be handled and propagated properly.

### Reproducible example

From empty application project, use following snippets and run ``cargo run``.

``Cargo.toml``
```toml
[package]
name = "polars-bug-20230610"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.30", features = ["lazy", "asof_join"] }
```

``main.rs``
```rust
use polars::prelude::*;

fn main() {
    let left_lf = df!("date_str" => &["2023/02/15"]).unwrap().lazy().sort("date_str", SortOptions::default());
    let right_lf = df!("date_str" => &["2023/01/31", "2023/02/28"], "value" => &[0,1]).unwrap().lazy().sort("date_str", SortOptions::default());

    let jb = JoinBuilder::new(left_lf)
        .with(right_lf)
        .how(JoinType::AsOf(AsOfOptions::default()))
        .on(&[col("date_str")]);

    let lf = jb.finish();
    println!("Works fine until here.");
    lf.collect();
}
```

### Expected behavior

Join should be successful - or in case there is a reason not to be, the error should be propagated properly.

### Installed versions

<details>
["lazy", "asof_join"]
</details>

**Comment by cmdlineluser** [comment]
Python:
```python
left  = pl.LazyFrame(dict(date_str = ["2023/02/15"])).sort("date_str")
right = pl.LazyFrame(dict(date_str = ["2023/01/31", "2023/02/28"], value = [0, 1])).sort("date_str")

left.join_asof(right, on="date_str").collect()

# PanicException: called `Result::unwrap()` on an `Err` value: 
# ComputeError(ErrString("chunked array is not contiguous"))
```
