### ISSUE TITLE
`pl.Expr.streaks()` (simplify identifying consecutive same value sequences)

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9328]
### Problem description

ref: https://stackoverflow.com/questions/76443773/implementing-a-streak-counter-in-polars

This seems to have a few different names and seems to come up quite frequently: grouping based on consecutive/adjacent same value runs, streaks, value changes. 

The idiom for this seems to be comparing `!=` against `.shift()` and using `.cumsum()` to generate "group ids".

Another recent example:

Identify the first change from `Below` -> `Above` and add a "running counter" to each "streak" that comes after.
```python
┌─────────┐          ┌─────────┬─────┐
│ Status  │          │ Status  ┆ id  │
│ ---     │          │ ---     ┆ --- │
│ str     │          │ str     ┆ u32 │
╞═════════╡          ╞═════════╪═════╡
│ No Data │          │ No Data ┆ 0   │
│ No Data │          │ No Data ┆ 0   │
│ No Data │          │ No Data ┆ 0   │
│ Below   │          │ Below   ┆ 0   │
│ Below   │          │ Below   ┆ 0   │
│ Below   │          │ Below   ┆ 0   │
│ Above   │     ->   │ Above   ┆ 1   │ 
│ Above   │          │ Above   ┆ 2   │
│ Above   │          │ Above   ┆ 3   │
│ Below   │          │ Below   ┆ 1   │
│ Below   │          │ Below   ┆ 2   │
│ Above   │          │ Above   ┆ 1   │
│ Above   │          │ Above   ┆ 2   │
└─────────┘          └─────────┴─────┘
```
```python
df.with_columns(id =
   pl.when(((pl.all() == 'Above') & (pl.all().shift() == 'Below')).cumsum() > 0)
     .then(pl.first().cumcount().over((pl.all() != pl.all().shift()).cumsum()) + 1)
     .otherwise(0)
)
```
Or perhaps using variables one might do something like:
```python
first_change = (
   pl.when((pl.all() == 'Above') & (pl.all().shift() == 'Below'))
     .then(True).forward_fill()
)

streaks = (pl.all() != pl.all().shift()).cumsum()

df.with_columns(id =
   pl.when(first_change)
     .then(pl.first().cumcount().over(streaks) + 1)
     .otherwise(0)
)
```
The ne/shift/cumsum gets somewhat annoying to type, so I end up doing something like:
```python
pl.Expr.next = lambda expr: expr.shift(-1)
pl.Expr.previous = lambda expr: expr.shift(+1)
pl.Expr.has_changed = lambda expr: (expr != expr.previous()).backward_fill()
pl.Expr.streaks = lambda expr: expr.has_changed().cumsum()

pl.cumcount = lambda offset=0: (lambda offset=offset: pl.first().cumcount() + offset)()
```
- I seem to have to re-learn what  direction `.shift` goes quite a bit, checking just the previous/next is quite common
- #7120 asks for `pl.cumcount` - it seems `offset=` would also be useful (similar to `.with_row_count`)
- Not sure if `.has_changed` is useful in any other cases or whether it should just be moved into `.streaks` 
- I had been calling this `.consecutive_ids()` myself but it seems `streaks` is a common term for it?

It's not a groundbreaking difference for the recent example:
```python
first_change = (
   pl.when((pl.all() == 'Above') & (pl.all().previous() == 'Below'))
     .then(True).forward_fill()
)

df.with_columns(id =
   pl.when(first_change)
     .then(pl.cumcount(1).over(pl.all().streaks()))
     .otherwise(0)
)
```
But it seems like a useful upgrade in isolation:
```python
df.with_columns(id = pl.all().streaks())

# shape: (13, 2)
# ┌─────────┬─────┐
# │ Status  ┆ id  │
# │ ---     ┆ --- │
# │ str     ┆ u32 │
# ╞═════════╪═════╡
# │ No Data ┆ 0   │
# │ No Data ┆ 0   │
# │ No Data ┆ 0   │
# │ Below   ┆ 1   │
# │ Below   ┆ 1   │
# │ Below   ┆ 1   │
# │ Above   ┆ 2   │
# │ Above   ┆ 2   │
# │ Above   ┆ 2   │
# │ Below   ┆ 3   │
# │ Below   ┆ 3   │
# │ Above   ┆ 4   │
# │ Above   ┆ 4   │
# └─────────┴─────┘
```
And although it doesn't technically account for the specific value change, if desired one could perhaps write:
```python
df.with_columns(id =
   pl.when(pl.all().streaks() > 1)
     .then(pl.cumcount(1).over(pl.all().streaks()))
     .otherwise(0)
)
```
Not sure if this is so common that it warrants a new expression but perhaps others have some useful input on the topic.

Thanks all.

**Comment by avimallu** [comment]
I think the name for this is called "running length ID" as well.

**Comment by mcrumiller** [comment]
A simpler way may be to do a simple `map_dict`:

```python
from polars import col

unique_values = df["Status"].unique(maintain_order=True)
df.with_columns(
    col("Status").map_dict({
        zip(unique_values, range(len(unique_values)))
    }).alias("ID")
)
```

**Comment by StefanBRas** [comment]
This comes up for me too - I know it as [Run-Length Encoding](https://en.wikipedia.org/wiki/Run-length_encoding).

R for example has it as a built-in called [`rle`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/rle) (Yes, right there as a global value).

**Comment by ion-elgreco** [comment]
This is actually a very common thing I do with timeseries data with categorical features. Would be a nice addition to the API.
