### ISSUE TITLE
Outer join fills in missing values in join columns.

### ISSUE THREAD

**Issue by bfeif** [pola-rs/polars#9335]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When joining two dataframes with `pl.DataFrame.join()`, the join column has values filled in where it should be null.

Note to Reviewer: I wasn't sure whether to enter this as an enhancement or as a bug. Thank you for your patience.

### Reproducible example

```python
import polars as pl
left_df = pl.DataFrame({"A_left": [1, 2, 3], "B_left": ["a", "b", "c"]})
right_df = pl.DataFrame({"A_right": [2, 3, 4], "C_right": ["jo", "shmo", "bo"]})
print(left_df.join(right_df, left_on="A_left", right_on="A_right", how="outer"))

# shape: (4, 3)
# ┌────────┬────────┬─────────┐
# │ A_left ┆ B_left ┆ C_right │
# │ ---    ┆ ---    ┆ ---     │
# │ i64    ┆ str    ┆ str     │
# ╞════════╪════════╪═════════╡
# │ 2      ┆ b      ┆ jo      │
# │ 3      ┆ c      ┆ shmo    │
# │ 4      ┆ null   ┆ bo      │
# │ 1      ┆ a      ┆ null    │
# └────────┴────────┴─────────┘
```

### Expected behavior

In my opinion the result **should** emulate that of a [SQL Outer Join](https://en.wikipedia.org/wiki/Join_(SQL)#Full_outer_join), i.e. look like this:
```
# shape: (4, 3)
# ┌────────┬────────┬─────────┬─────────┐
# │ A_left ┆ B_left ┆ A_right ┆ C_right │
# │ ---    ┆ ---    ┆ ---     ┆ ---     │
# │ i64    ┆ str    ┆ str     ┆ str     │
# ╞════════╪════════╪═════════╪═════════╡
# │ 2      ┆ b      ┆ 2       ┆ jo      │
# │ 3      ┆ c      ┆ 3       ┆ shmo    │
# │ null   ┆ null   ┆ 4       ┆ bo      │
# │ 1      ┆ a      ┆ null    ┆ null    │
# └────────┴────────┴─────────┴─────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.2
Index type:  UInt32
Platform:    macOS-12.1-x86_64-i386-64bit
Python:      3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.24.2
pandas:      1.3.5
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.3.4
xlsx2csv:    <not installed>
xlsxwriter:  1.3.9
```

</details>

**Comment by cjackal** [comment]
Current definition of outer join in polars is consistent with that of pandas or dplyr (and most other data manipulation library), though the documentation on "how" keyword is missing. I guess it would be helpful to copy-paste pandas' documentation to polars?

**Comment by mcrumiller** [comment]
Yeah, the polars join is different from SQL join, in that the "joined on" columns are always merged. This isn't how pandas does it and it's also not how SQL does it, so I don't know if this should be updated and/or fixed. See the pandas code:

```python
import pandas as pd

left_df = pd.DataFrame({
    "A_left": [1, 2, 3],
    "B_left": ["a", "b", "c"]
})
right_df = pd.DataFrame({
    "A_right": [2, 3, 4],
    "C_right": ["jo", "shmo", "bo"]
})
left_df.merge(right_df, left_on="A_left", right_on="A_right", how="outer")
```
```
   A_left B_left  A_right C_right
0     1.0      a      NaN     NaN
1     2.0      b      2.0      jo
2     3.0      c      3.0    shmo
3     NaN    NaN      4.0      bo
```

In polars, the `left_on` and `right_on` columns are merged into a single column, as shown in your example.

A current work around, if you'd like, would be to create a temporary column, join on that, and then remove the temp columns, but this is obviously not ideal:

```python
import polars as pl
from polars import col

def outer_join_like_sql(df1, df2, left_on, right_on):
    new_names = [f"{x}_tmp" for x in left_on]
    
    # replicate join columns with new names
    df1 = df1.with_columns(col(x).alias(y) for x,y in zip(left_on, new_names))
    df2 = df2.with_columns(col(x).alias(y) for x,y in zip(right_on, new_names))
    
    # perform join and drop columns
    return df1.join(df2, on=new_names, how="outer").drop(new_names)


left_df = pl.DataFrame({
    "A_left": [1, 2, 3],
    "B_left": ["a", "b", "c"]
})
right_df = pl.DataFrame({
    "A_right": [2, 3, 4],
    "C_right": ["jo", "shmo", "bo"]
})

print(
    outer_join_like_sql(left_df, right_df, left_on=["A_left"], right_on=["A_right"])
)
```

**Comment by bfeif** [comment]
@mcrumiller 100%, thank you for the pandas comparison (@cjackal see the comment, polars is out of alignment with pandas and sql on this one).

Thanks for the function too btw; I'm not in a rush though, I'd rather wait to get it fixed.

**Comment by cjackal** [comment]
Hmm, I thought the pandas equivalent is `pd.DataFrame.join` via `pd.DataFrame.set_index`... Then I guess it is a matter of preference

**Comment by mcrumiller** [comment]
@cjackal there's not a direct comparison--polars doesn't have an index, so the closest comparison in pandas is `merge`, not `join`. Indexes are sort of special and so you're right, a `join` in pandas on indexes *does* merge the indexes:

```python
import pandas as pd

left_df = pd.DataFrame({
    "A_left": [1, 2, 3],
    "B_left": ["a", "b", "c"]
}).set_index("A_left")

right_df = pd.DataFrame({
    "A_right": [2, 3, 4],
    "C_right": ["jo", "shmo", "bo"]
}).set_index("A_right")

print(
    left_df.join(right_df, how="outer")
)
```
```
(.venv_art) C:\Projects\project-art\scripts>python check_merge.py
  B_left C_right
1      a     NaN
2      b      jo
3      c    shmo
4    NaN      bo
```

**Comment by cjackal** [comment]
@mcrumiller @bfeif Right, I have no strong opinion on which must be the "canon", and agree that if there must, ANSI-standard SQL behavior wins. It's kind of clumsy that SQL style inner join always comes with duplicated columns though.

**Comment by ritchie46** [comment]
I think that's a bug on our side. It should emulate sql indeed.

**Comment by mcrumiller** [comment]
@ritchie46 unfortunately it's not so cut and dry for SQL because the query itself explicitly specifies what's in the output:

**table_1**:
```
A       B       C
-----------------
1	1	1
2	2	2
3	3	3
```
**table_2**
```
A       B       C
-----------------
1	1	1
2	2	2
3	3	3
4	4	4
```
```sql
SELECT
  A.*, B.* <-- this is where you specify how the output looks
FROM
  table_1 A
FULL OUTER JOIN
  table_2 B
ON
  A.A = B.A;
```
```
A       B       C       A       B       C
-----------------------------------------
1	1	1	1	1	1
2	2	2	2	2	2
3	3	3	3	3	3
NULL	NULL	NULL	4	4	4
```

What about having a `.merge` that combines the JOIN columns versus having `join` that doesn't?

**Comment by cjackal** [comment]
@ritchie46 `pyspark` support both join styles in one API:

```python
left_df.join(right_df, left_df.A == right_df.A, how="full")  # SQL full outer join, allow duplicated column name
left_df.join(right_df, ["A"], how="full") # polars style join with merged index column
```

`dplyr` provides similar API using `join_by`.

**Comment by ritchie46** [comment]
Right, I think we must call this a feature request then. Does it only make sense for the outer join to add the right column name, or do other joins also should have that option?

**Comment by avimallu** [comment]
Why not leave that choice to the user with an argument (and maybe a Config option)? That way, everybody would be happy 😄.

**Comment by evbo** [comment]
So glad Polars community is open to retaining all columns being joined on. Just wanted to add a great use-case for this:

While not ideal, at times we need to join on inequality expressions, and in those cases retaining all join columns is still helpful since they are not equal in those cases and contain useful information still.
