### ISSUE TITLE
`pl.when().then()` is not supported is streaming mode

### ISSUE THREAD

**Issue by elephantum** [pola-rs/polars#9337]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When working with huge parquet files I encountered that `pl.when().then()` breaks streaming mode and requires `.collect()` which might not be feasible due to memory restrictions.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3]}).lazy()

df = df.with_columns(
    pl.when(pl.col("a") >= 2).then(pl.col("a")).otherwise(None).alias("b"),
)

df.sink_parquet("test.parquet")
```

### Expected behavior

Data is processed in streaming mode, parquet file is created.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.2
Index type:  UInt32
Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by elephantum** [comment]
My current workaround is:

```python
df = df.map(
    lambda df: df.with_columns(
        pl.when(pl.col("a") >= 2).then(pl.col("a")).otherwise(None).alias("b"),
    ),
    streamable=True,
    schema={
        "a": pl.Int64,
        "b": pl.Int64,
    }
)
```

It works in streaming mode, but requires full schema definition which might be huge in practical cases.

**Comment by ritchie46** [comment]
Oh, it definitely should. Will add it.
