### ISSUE TITLE
with_column and filter are not commutative, one of them produces null!

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#9357]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is very hard to reproduce, but it is a real bug.

Sorry you must download the dataset here: https://drive.google.com/file/d/10Oe3tQdxG8aywuW2c0StAQFMGK-mTx2B/view?usp=sharing.

### Reproducible example
Once you have downloaded the dataset, try these commands:

```python

polars.read_parquet("ethusdt-mint-burn.parquet")\
.with_columns([
        polars.col("data").apply(lambda x: int(x[-192:-128], 16)).alias('amount'),
        polars.col("data").apply(lambda x: int(x[-128:-64], 16)).alias('amount0'),
        polars.col("data").apply(lambda x: int(x[-64:], 16)).alias('amount1')
    ]).filter(polars.col('blockNumber') ==2912978)


polars.read_parquet("ethusdt-mint-burn.parquet").filter(polars.col('blockNumber') ==2912978).with_columns([
        polars.col("data").apply(lambda x: int(x[-192:-128], 16)).alias('amount'),
        polars.col("data").apply(lambda x: int(x[-128:-64], 16)).alias('amount0'),
        polars.col("data").apply(lambda x: int(x[-64:], 16)).alias('amount1')
    ])

```

### Expected behavior

You will notice that the "amount" field is different depending on if you filtered first or did with_columns first.

One is null, one is correct value

### Installed versions

<details>

```
0.18.2
```

</details>

**Comment by ritchie46** [comment]
It has to do with schema inference. Not applying the output dtype to `apply` is considered a bug in the users query. We allow it, but you may get differences due to schema inference.
