### ISSUE TITLE
Ability to pass pyarrow schema when writing the parquet file

### ISSUE THREAD

**Issue by artsiom-tsaryonau** [pola-rs/polars#9386]
### Problem description

Hi!

When writing to parquet file, I wanted to use my custom schema service that was using `pyarrow` to create schema.
But even when specifying the flag `use_pyarrow` it does not allow to pass `schema` parameters. 
```
from polars import DataFrame, Int64
import pyarrow

df = DataFrame(
    data={'column': [1, 2, 3, 5]},
    schema={
        'column': Int64()
    }
)

df.write_parquet('sample_1.parquet')

# ParquetWriter.__init__() got multiple values for argument 'schema'
df.write_parquet('sample_2.parquet', use_pyarrow=True, pyarrow_options={'schema': {'column': pyarrow.int64() }})
```

From my understanding it is happening due to Polars passing its own schema as the argument to pyarrow function. It would be nice to have an option to ignore Polars' generated schema and pass custom schema, especially considering that the flag `use_pyarrow` is already in place.

**Comment by wyatt0xcube** [comment]
While also passing use_pyarrow=True, I'm having the same difficulties when passing the pyarrow_options for compression (and compression_level), with error # ParquetWriter.__init__() got multiple values for argument 'compression'.

**Comment by benjs** [comment]
You can use
```
pq.write_to_dataset(
    df.to_arrow(),
    schema=...,
)
```
