### ISSUE TITLE
`top_k` does not preserve original row order

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#9401]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

From empirical tests I did, `sort` was always implicitly maintaining the order ( when there is duplicated values on the column you sort on). For me this is a good behavior, even though I can understand it could more costly in particular in streaming mode. In this case we should add an argument `maintain_order` to allow the user to remove the randomness.

This issue is linked to this one #8410. The question behind is: Should the `sort` operation should maintain the order and can the user control this behavior?

Today, the answer to this question is not really clear and "weird" behaviors can araise. See below :

### Reproducible example

```python
import polars as pl

(
 pl.LazyFrame({'A': [1] * 4, 'B': ['A', 'B', 'C', 'D']})
 .sort('A')
 .slice(0, 3)
 .collect()['B'].to_list()
) # ['D', 'B', 'C'] <- top_k does not preserve row order


(
 pl.LazyFrame({'A': [1] * 4, 'B': ['A', 'B', 'C', 'D']})
 .sort('A')
 .collect()
 .slice(0, 3)['B'].to_list()
) # ['A', 'B', 'C'] <- simple sort: row order in maintain
```

### Expected behavior

I think,  `sort` should have a `maintain_order` (defaulting to False, if less costly). But the user should ideally control this behavior.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment]
Right.. that was not guaranteed indeed. We can add that keyword and block certain optimizations if needed

**Comment by CloseChoice** [comment]
I'd like to take this on

**Comment by ritchie46** [comment]
Alright. It is a bit of chore to get through all the dispatch layers, let me know if you need help.
