### ISSUE TITLE
Cast multiple column dtypes at the same time

### ISSUE THREAD

**Issue by ryantaylor406** [pola-rs/polars#9402]
### Problem description

Currently, you can only cast the dtype of a column one at a time.

In pandas, you can cast multiple columns in one line of code via a dictionary e.g.
`df = df.astype({'col1':str, col2:float})`

It would be very useful to have this functionality in Polars, perhaps something like:
```
df = df.select(
   pl.col('*').cast({'col1':pl.Utf8, col2:pl.Float64})
)
```

**Comment by ritchie46** [comment]
@ryantaylor406 that doesn't align with out expansion rules. We should only expand the column selectors, not the operations. That would become a spaghetti mess. How would we reason at what the output expressions would be?

@avimallu answer is how it should be done with our expansion rules. I will close this as not planned, as I don't see this fit with our engine.
