### ISSUE TITLE
LazyFrame::groupby_stable panics under some circumstances

### ISSUE THREAD

**Issue by mt-caret** [pola-rs/polars#9408]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I've been writing some bindings to the Polars Rust library from OCaml, and when porting over the Polars user guide I ran into some code which causes panics.

### Reproducible example

Running `cargo test` for this https://github.com/mt-caret/polars-ocaml/blob/d0ab2d86943ae6f3e628766ebbaa639c57026f5d/rust/src/lib.rs:
```rust
    #[test]
    fn lazy_groupby_issue() {
        let dataset = CsvReader::from_path("../test/data/legislators-historical.csv")
            .unwrap()
            .finish()
            .unwrap()
            .head(Some(1000));

        let df = dataset
            .lazy()
            .groupby_stable(vec![col("state")])
            .agg(vec![col("party").eq(lit("some_string")).sum()])
            .collect()
            .unwrap();

        expect![[""]].assert_eq(&df.to_string());
    }
```
Results in:
```
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', /home/ubuntu/.cargo/registry/src/index.crate
s.io-6f17d22bba15001f/polars-arrow-0.30.0/src/kernels/take_agg/mod.rs:29:5                                          
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                       
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', /home/ubuntu/.cargo/registry/src/index.crate
s.io-6f17d22bba15001f/polars-arrow-0.30.0/src/kernels/take_agg/mod.rs:29:5                                          
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', /home/ubuntu/.cargo/registry/src/index.crate
s.io-6f17d22bba15001f/polars-arrow-0.30.0/src/kernels/take_agg/mod.rs:29:5                                          
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', /home/ubuntu/.cargo/registry/src/index.crate
s.io-6f17d22bba15001f/polars-arrow-0.30.0/src/kernels/take_agg/mod.rs:29:5                                          
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', /home/ubuntu/.cargo/registry/src/index.crate
s.io-6f17d22bba15001f/polars-arrow-0.30.0/src/kernels/take_agg/mod.rs:29:5
... many many more lines of this error
```

Notably, changing small details about above example results in this panic not triggering (e.g. changing `Some(1000)` to `Some(999)` or changing `col("party")` to `col("last_name")`).

### Expected behavior

Do something other than panic.

### Installed versions

[ "lazy", "dot_diagram", "parquet", "approx_unique", "dtype-date", "dtype-datetime", "dtype-i8", "dtype-i16", "dtype-u8", "dtype-u16", "random", "describe", "streaming" ]

**Comment by ritchie46** [comment]
This has been fixed in `main`.

**Comment by mt-caret** [comment]
Thank you so much for the quick fix! Out of curiosity, what was the cause of the issue (and why did it only occur in some configurations)?

**Comment by ritchie46** [comment]
Yeah, not that important. :P A silly thing.
