### ISSUE TITLE
pl.concat of a df to itself modifies input

### ISSUE THREAD

**Issue by bmschmidt** [pola-rs/polars#941]
Thank you for your work on this great library.

#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.8.9

#### What operating system are you using polars on?

OS X 10.15.7

#### Describe your bug.

When pl.concat is used to concatenate a table to itself, the input table is doubled in place each time it appears.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
a = pl.from_rows(((1,2),(1,2)))
b = pl.concat([a, a, a])
a.shape
```

#### What is the actual behavior?

`a.shape` is `(8, 2)`

#### What is the expected behavior?

`a` should not be changed.

**Comment by ritchie46** [comment]
Thank you for the issue report. I will fix this.
