### ISSUE TITLE
DataFrame.corr() incorrectly utilizing np.corrcoef()

### ISSUE THREAD

**Issue by chris-santiago** [pola-rs/polars#9430]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The pl.DataFrame.corr() [func](https://github.com/pola-rs/polars/blob/ff2a97e0728d5fcdd01e3998c9d9995411f462b7/py-polars/polars/dataframe/frame.py#L8718-L8751) is using `np.corrcoef` incorrectly. Specifically, it's calling a transpose operation prior to `np.corrcoef`, which results in incorrect shape-- it's effectively calculating correlation of columns vice rows.

### Reproducible example

```python
import polars as pl
import numpy as np

a = np.random.random(30).reshape(10, -1)
a.shape. # returns (10, 3)
b = np.corrcoef(a)
b.shape # returns (10, 10)

aa = pl.DataFrame(a)
aa.shape. # returns (10, 3)
bb = aa.corr()
bb.shape # returns (3,3)
```

### Expected behavior

The expected behavior should match that of the Numpy implementation, returning a 10x10 dataframe (matrix) of correlation coefficients.  Users can easily remedy this by calling `.transpose()` on polars dataframe prior to `.corr()`, but the difference should be called out in docs.

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ]
----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

**Comment by CHDev93** [comment]
I'd argue this is not a bug. Numpy arrays are C major ordered. Polars is columnar. In a dataframe, columns should represent variables/metrics and rows represent observations/samples of said metric. Ordinarily you want correlation of variables (for which you have many observations). I think it would be extremely surprising if the correlation was done between observations rather than variables.

**Comment by zundertj** [comment]
This is because Polars is columnar, as @CHDev93  points out. Pandas, another columnar dataframe library, behaves the same: [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html). I have added clarification to the docstring.
