### ISSUE TITLE
Add quoting parameter in pl.write_csv()

### ISSUE THREAD

**Issue by aisayko** [pola-rs/polars#9433]
### Problem description

It will be good to have a `quoting` parameter in `df.write_csv()` method.

Something like
```
df.write_csv(path, separator=",", quoting=QuoteStyle.Necessary)
```

For reference here is a doc page in Rust
https://docs.rs/csv/latest/csv/enum.QuoteStyle.html

As example Pandas have similar parameter which is defaults to `csv.QUOTE_MINIMAL`

**Comment by aisayko** [comment]
@ritchie46 Hi, how do you think it will be possible to implement it in the near future? Thank you

**Comment by aisayko** [comment]
At the moment I can do
```
pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6, 7, 8],
        "ham": ["a", "b", "c"],
    }
).to_pandas().to_csv(quoting=csv.QUOTE_MINIMAL)
```
But seems it is not optimal on large data frames.

**Comment by ritchie46** [comment]
@stinodego I want to accept this. How do I do that?^^

**Comment by stinodego** [comment]
@ritchie46 Add the "accepted" label 😄

**Comment by ritchie46** [comment]
Ah!

**Comment by ritchie46** [comment]
Just a question. Doesn't polars already default to quote style minimal?
