### ISSUE TITLE
Delta partitioning produces folders in some strange encoding

### ISSUE THREAD

**Issue by artsiom-tsaryonau** [pola-rs/polars#9441]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi!

I am trying to partition my dataframe and write it as delta format. However the resulting folder structure looks like this
```
root/
    _delta_log/
        00000000000000000000.json
    GROUP=%255B%250A%2520%2520%2522A%2522%250A%255D/
        0-f570f86e-f1bc-46aa-8b11-af4ab8acb086-0.parquet
    GROUP=GROUP=%255B%250A%2520%2520%2522B%2522%250A%255D/
        0-f570f86e-f1bc-46aa-8b11-af4ab8acb086-0.parquet
```

It seems it has encoded string group values in some encoding. This issues does not happen when the partition has "Int32" type for example. 

### Reproducible example

```python
df = DataFrame(
    data={
        'NAME': ['John', 'Max', 'Henry'],
        'GROUP': ['A', 'B', 'A']
    }, 
    schema={
        'NAME': pl.Utf8(),
        'GROUP': pl.Utf8()
    }
)

df.write_delta(
    'current_folder/',
    delta_write_options={
        'partition_by': ['GROUP']
    }
)
```

### Expected behavior

I expect it to create this folder structure

```
current_folder/
    _delta_log/
        00000000000000000000.json
    GROUP=A/
        0-f570f86e-f1bc-46aa-8b11-af4ab8acb086-0.parquet
    GROUP=B/
        0-f570f86e-f1bc-46aa-8b11-af4ab8acb086-0.parquet
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    macOS-13.2-arm64-arm-64bit
Python:      3.10.4 (main, May 10 2023, 16:05:44) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.25.0
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   0.9.0
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by rune-bk** [comment]
It seems to have URL encoded the string twice. I have a similar issue. 

So your 
`GROUP=%255B%250A%2520%2520%2522A%2522%250A%255D` folder is actually 

`GROUP=[
"A"
]`

**Comment by ion-elgreco** [comment]
You should create an issue at Delta-RS, Polars doesn't do anything here.

**Comment by ion-elgreco** [comment]
I think this issue was related to <12 pyarrow issue. We fixed it now with a workaround in delta-rs.

@stinodego can we close this?
