### ISSUE TITLE
Pickling lazy dataframe with `map` stage raises with `BindingsError`

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#9454]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When trying to pickle a lazy dataframe with `.map`, I'd assume we would use python's pickle on the udf and then wrap that in the rust serde mechanism for the lazyframe.

### Reproducible example

```python
import pickle
import polars as pl

ldf = pl.DataFrame(
    {"a": [1, 2], "b": [3, 4], "c": [5.6, 6.7]},
).lazy()

def run(df):
    print("hello")
    return df

udf_ldf = ldf.map(run)
pickle.dumps(udf_ldf)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[15], line 13
     10     return df
     12 udf_ldf = ldf.udf.noop()
---> 13 pickle.dumps(udf_ldf)

File /...site-packages/polars/lazyframe/frame.py:296, in LazyFrame.__getstate__(self)
    295 def __getstate__(self) -> Any:
--> 296     return self._ldf.__getstate__()

RuntimeError: BindingsError: "Value(\"the enum variant FunctionNode::Opaque cannot be serialized\")"
```

### Expected behavior

I would've expected:

```
pickle.loads(pickle.dumps(udf_ldf))
```

to return the same udf back, but `pickle.dumps` currently fails.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux
Python:      3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
```

</details>

**Comment by ritchie46** [comment]
Until we support this, does pickling the function that generates the lazy frame work?

**Comment by OneRaynyDay** [comment]
Could you give me an example? If I understand correctly you mean something like:

```
lf = get_lazy_frame()
lf_foo = lf.map(foo)
lf_bar = lf_foo.map(bar)

# instead of pickle.dumps(lf_bar)...
lf_pkl = pickle.dumps(lf)
foo_pkl = pickle.dumps(foo)
bar_pkl = pickle.dumps(bar)

pickle.loads(lf).map(pickle.loads(foo_pkl)).map(pickle.loads(bar_pkl))
```

This would be too cumbersome if we have a really long graph, where certain stages may be `.map`s depending on arguments to construct the lazyframe.
