### ISSUE TITLE
pl.col(...).str.decode('json')

### ISSUE THREAD

**Issue by sslivkoff** [pola-rs/polars#9469]
### Problem description

It would be nice to have native support for decoding json str's as `pl.col(...).str.decode('json')`

Using `pl.col(...).apply(json.loads)` and `pl.col(...).apply(orjson.loads)` are both limited in performance due to GIL

**Comment by ritchie46** [comment]
We have that:

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.json_extract.html#polars.Expr.str.json_extract

**Comment by sslivkoff** [comment]
awesome thank you
