### ISSUE TITLE
Support three-valued logic in `any` and `all`

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#9472]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

As I noted in [this comment](https://github.com/pola-rs/polars/issues/7595#issuecomment-1558166821), polars has the proper three-valued truth tables for `&`, `|`, and `~`. The `any` method is conceptually a reduction with the `|` operator, and the `all` method is conceptually a reduction with the `&` operator, so `any` and `all` should propagate the behavior of `|` and `&`, respectively. Unfortunately, they do not.

### Reproducible example

```python
df = pl.DataFrame(dict(
    x = [None, False],
    y = [None, True]
))
```
```python
┌───────┬──────┐
│ x     ┆ y    │
│ ---   ┆ ---  │
│ bool  ┆ bool │
╞═══════╪══════╡
│ null  ┆ null │
│ false ┆ true │
└───────┴──────┘
```
```python
df.select(
    any_x = pl.col("x").any(),
    all_x = pl.col("x").all(),
    any_y = pl.col("y").any(),
    all_y = pl.col("y").all()
)
```
```python
┌───────┬───────┬───────┬───────┐
│ any_x ┆ all_x ┆ any_y ┆ all_y │
│ ---   ┆ ---   ┆ ---   ┆ ---   │
│ bool  ┆ bool  ┆ bool  ┆ bool  │
╞═══════╪═══════╪═══════╪═══════╡
│ false ┆ false ┆ true  ┆ false │
└───────┴───────┴───────┴───────┘
```

### Expected behavior

```python
df.select(
    any_x = pl.col("x").any(),
    all_x = pl.col("x").all(),
    any_y = pl.col("y").any(),
    all_y = pl.col("y").all()
)
```
```python
┌───────┬───────┬───────┬───────┐
│ any_x ┆ all_x ┆ any_y ┆ all_y │
│ ---   ┆ ---   ┆ ---   ┆ ---   │
│ bool  ┆ bool  ┆ bool  ┆ bool  │
╞═══════╪═══════╪═══════╪═══════╡
│ null  ┆ false ┆ true  ┆ null  │
└───────┴───────┴───────┴───────┘
```

The expected behavior can easily be demonstrated in the R REPL:

```r
> any(c(NA, FALSE))
[1] NA
> all(c(NA, FALSE))
[1] FALSE
> any(c(NA, TRUE))
[1] TRUE
> all(c(NA, TRUE))
[1] NA
```

The expected behavior can also easily be demonstrated in the Julia REPL:

```julia
julia> any([missing, false])
missing

julia> all([missing, false])
false

julia> any([missing, true])
true

julia> all([missing, true])
missing
```

### Installed versions

<details>
In [26]: pl.show_versions()
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.21.5
pandas:      1.4.4
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.3.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.0.3
</details>

**Comment by CameronBieganek** [comment]
It looks like I accidentally opened this as a Rust bug instead of a Python bug (though chances are it applies to both).

**Comment by mcrumiller** [comment]
I appreciate 3-valued logic but dear god do I hate it. It never serves my purpose and has ruined countless hours.

When I call `any`, I want to know if any values in the column are true; that is a simple and obvious request. But a single `null` value ruins the entire thing and sets my result to `null`.

I can stand by having `null | true` evaluate to null, but I dont' know if I can stand by having `any` do it too.
