### ISSUE TITLE
rolling_mean closed param seems never works as expected. 

### ISSUE THREAD

**Issue by kennyzli** [pola-rs/polars#9476]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

tried to use Expr.rolling_mean method to define the value with closed params, 
follow the instruction here https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.rolling_mean.html#polars.Expr.rolling_mean

but no matter what I put in, the  `none/left/right/none` produce all the same result 

### Reproducible example

```python
>>> import polars as pl
>>> df = pl.DataFrame(
... {
... "A": [1.0, 8.0, 6.0, 2.0, 16.0, 10.0]
... 
... }
... ) 


>>> df.select( pl.col('A').rolling_mean(window_size=3,min_periods=1, closed='none'))
shape: (6, 1)
┌──────────┐
│ A        │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
│ 4.5      │
│ 5.0      │
│ 5.333333 │
│ 8.0      │
│ 9.333333 │
└──────────┘
>>> df.select( pl.col('A').rolling_mean(window_size=3,min_periods=1, closed='left'))
shape: (6, 1)
┌──────────┐
│ A        │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
│ 4.5      │
│ 5.0      │
│ 5.333333 │
│ 8.0      │
│ 9.333333 │
└──────────┘
>>> df.select( pl.col('A').rolling_mean(window_size=3,min_periods=1, closed='right'))
shape: (6, 1)
┌──────────┐
│ A        │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
│ 4.5      │
│ 5.0      │
│ 5.333333 │
│ 8.0      │
│ 9.333333 │
>>> df.select( pl.col('A').rolling_mean(window_size=3,min_periods=1, closed='both'))
shape: (6, 1)
┌──────────┐
│ A        │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
│ 4.5      │
│ 5.0      │
│ 5.333333 │
│ 8.0      │
│ 9.333333 │
└──────────┘
```

### Expected behavior

the left/right/none/both should show different result.  

### Installed versions

<details>

```
>>> >>> pl.show_versions()
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.8.10 (default, Nov  4 2022, 16:37:45)
[Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.21.3
pandas:      1.3.5
pyarrow:     9.0.0
connectorx:  0.3.1
deltalake:   0.8.1
fsspec:      2022.7.1
matplotlib:  <not installed>
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0

```
</details>

**Comment by MarcoGorelli** [comment]
thanks @kennyzli for the report - `closed` only takes effect if `by` was set

**Comment by MarcoGorelli** [comment]
there was a recent PR to clarify this in the docs, but it doesn't show up yet

https://github.com/pola-rs/polars/blob/c868164908a54ba106d250e744c32c861a5e6f77/py-polars/polars/expr/expr.py#L5266-L5268
