### ISSUE TITLE
Add case-insensitive option to JoinBuilder

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#9479]
### Problem description

It would be great if a case-insensitive option is added to JoinBuilder for convenience as its not uncommon requirement when dealing with real-world data.

**Comment by jqnatividad** [comment]
I mean to have something like this:

```
 let mut join_results =  lf1.join_builder()
                .with(lf2)
                .left_on(cols1)
                .right_on(cols2)
                .case_insensitive(true)
                .how(jointype)
                .finish()
                .collect()?
```

So the join will be a case_insensitive comparison on `cols1` and `cols2`.

**Comment by ritchie46** [comment]
We don't want to push compute into keywords. You can pass an expression that converts the join key to lowercase.

**Comment by jqnatividad** [comment]
Thanks for the quick response and suggestion @ritchie46 !

**Comment by jqnatividad** [comment]
If it's not too much of a bother @ritchie46 , can you provide a hint on how to pass an expression that converts the join key to lowercase in Rust?

I looked at the [User Guide](https://pola-rs.github.io/polars-book/user-guide/expressions/strings/) and I couldn't find an equivalent example in Rust for what seemed to be a straightforward thing to do in Python with the `str` namespace string functions.

**Comment by ritchie46** [comment]
Rust also has the `str()` namespace
