### ISSUE TITLE
Lazily sorting and sinking a large dataframe to IPC is indeterministic and causes data loss

### ISSUE THREAD

**Issue by Marnixvdb** [pola-rs/polars#9503]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When aggregating and sorting a large lazy dataframe and saving it using sink_ipc, I noticed that the shape of the output changed from run to run, using the same input data.

I was able to reproduce this with fake data and have narrowed the cause down to the combination of sort() and sink_ipc() used in the context of a big enough lazy dataframe. Attached is a reproducible example that often but not always reproduces the behaviour. If you don't observe the same behaviour, try setting a larger number_of_rows. 

The script generates 10 tables with 24 columns and 1 million rows each and stores them as parquet files using PyArrow. Using polars, the files are read back in and sorted. The script prints the shape of resulting dataframe using four methods:
1. read as lazy dataframe using scan_parquet, sort it, collect it and print the shape
2. read as lazy dataframe using scan_parquet, sort it, and store it using sink_ipc. Read the arrow file back in and print the shape. 
3. read a regular dataframe using read_parquet, sort it and print the shape
4. read as regular dataframe using read_parquet, sort it, store it using write_ipc. Read the arrow file back in and print the shape.

I've included three consecutive runs of the script on my computer:

```
(.venv) ➜  polarsbug python main.py && python main.py && python main.py

generating 10 random tables with 24 columns and 1000000 rows each.
Sorting the dataframe and counting records...
1) shape of sorted and collected lazy dataframe: (10000000, 24)
2) shape of sorted lazy dataframe sunk as arrow file and read back in: (9991439, 24)
3) shape of sorted regular dataframe: (10000000, 24)
4) shape of sorted regular dataframe sunk as arrow file and read back in: (10000000, 24)

generating 10 random tables with 24 columns and 1000000 rows each.
Sorting the dataframe and counting records...
1) shape of sorted and collected lazy dataframe: (10000000, 24)
2) shape of sorted lazy dataframe sunk as arrow file and read back in: (10000000, 24)
3) shape of sorted regular dataframe: (10000000, 24)
4) shape of sorted regular dataframe sunk as arrow file and read back in: (10000000, 24)

generating 10 random tables with 24 columns and 1000000 rows each.
Sorting the dataframe and counting records...
1) shape of sorted and collected lazy dataframe: (10000000, 24)
2) shape of sorted lazy dataframe sunk as arrow file and read back in: (9985393, 24)
3) shape of sorted regular dataframe: (10000000, 24)
4) shape of sorted regular dataframe sunk as arrow file and read back in: (10000000, 24)
```

As you can see all three results of the second count are different, with only one out of three being correct. 

### Reproducible example

```python
import os
import tempfile
import pyarrow.parquet as pq
import pyarrow as pa
import numpy as np
import polars as pl

def generate_fake_table(num_rows, num_columns, file_name):
    arrays = [pa.array(np.random.randint(0, 10000, size=num_rows)) for i in range(num_columns)]
    table = pa.Table.from_arrays(arrays, names=[f'col_{i}' for i in range(num_columns)])

    pq.write_table(table, file_path)

    return file_path

# Define temporary directory
temp_dir = tempfile.mkdtemp()

# issue on my computer doesn't appear for 100_000 rows, but often does when setting this variable to 1_000_000 rows
num_rows = 1_000_000
num_columns = 24
num_tables = 10

print (f'generating {num_tables} random tables with {num_columns} columns and {num_rows} rows each.')

# Generate tables and store as individual Parquet files
parquet_files = []
for i in range(num_tables):
    num_rows = num_rows
    num_columns = num_columns
    file_name = f"table_{i}.parquet"
    file_path = os.path.join(temp_dir, file_name)

    # Generate and save fake table
    parquet_files.append(generate_fake_table(num_rows, num_columns, file_path))

# Stream read all Parquet files into one big DataFrame
print("Sorting the dataframe and counting records...")
streaming_dataframe = pl.scan_parquet(temp_dir + '/*.parquet')

# sort dataframe on all columns
sorted_streaming_dataframe = streaming_dataframe.sort(streaming_dataframe.columns)

# and sink it
sorted_streaming_dataframe.sink_ipc(temp_dir + "/sorted_streaming_dataframe.arrow")

# read back in
sorted_streaming_dataframe_arrow = pl.read_ipc(temp_dir + "/sorted_streaming_dataframe.arrow", memory_map=False)

# try the same with a regular, non streaming dataframe 
regular_dataframe = pl.read_parquet(temp_dir + '/*.parquet')

# sort it
sorted_regular_dataframe = regular_dataframe.sort(regular_dataframe.columns)

# write it to ipc
sorted_regular_dataframe.write_ipc(temp_dir + "/sorted_regular_dataframe.arrow")

# read back in
sorted_regular_dataframe_arrow = pl.read_ipc(temp_dir + "/sorted_regular_dataframe.arrow", memory_map=False)

print(f'1) shape of sorted and collected lazy dataframe: {sorted_streaming_dataframe.collect().shape}')
print(f'2) shape of sorted lazy dataframe sunk as arrow file and read back in: {sorted_streaming_dataframe_arrow.shape}')
print(f'3) shape of sorted regular dataframe: {sorted_regular_dataframe.shape}')
print(f'4) shape of sorted regular dataframe sunk as arrow file and read back in: {sorted_regular_dataframe_arrow.shape}')
```

### Expected behavior

Regardless of how we read, write or collect the dataframe, the shape of the output should always be correct and the same. In the output of the reproducible example, all shapes should match exactly. 

### Installed versions

<details>

--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

</details>

**Comment by ritchie46** [comment]
Thanks for the issue. How much ram do you have on your machine?

**Comment by Marnixvdb** [comment]
32 GB, but quite some of it was being in use by other processes obviously.

**Comment by ritchie46** [comment]
Right, can reproduce on the out-of-core sort algorithm. :+1:
