### ISSUE TITLE
Filter combination does not work when predicate pushdown is disabled

### ISSUE THREAD

**Issue by benjs** [pola-rs/polars#9504]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Filters are not combined when `predicate_pushdown = False`.

Not sure if this is important, as `predicate_pushdown=True` is very useful.

### Reproducible example

```python
import datetime
import polars as pl

test_data = pl.DataFrame(
    data = {
        "types": ["Apple", "Banana", "Orange", "Peach"],
        "date": pl.date_range(start=datetime.date(2023, 6, 20), end=datetime.date(2023, 6, 23), eager=True),
        "vals": [1, 2, 3, 4]
    }
)

test_data.lazy().filter(pl.col("vals")  > 1).filter(pl.col("vals") < 4).explain(predicate_pushdown=False)
```

### Expected behavior

`FILTER ([(col("vals")) < (4)]) & ([(col("vals")) > (1)]) FROMDF ["types", "date", "vals"]; PROJECT */3 COLUMNS; SELECTION: "None"
`

Actual behaviour:
`FILTER [(col("vals")) < (4)] FROMFILTER [(col("vals")) > (1)] FROMDF ["types", "date", "vals"]; PROJECT */3 COLUMNS; SELECTION: "None"`

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.31
Python:      3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]

----Optional dependencies----
numpy:       1.25.0
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
That's not a bug right? If we don't run the optimization, we don't execute it?

**Comment by benjs** [comment]
In my understanding, predicate pushdown means that the filters are forwarded to the data loader.
Filter optimization is in my understanding something different.

Just wanted to point this behaviour out, if it is intended, then no worries.

**Comment by ritchie46** [comment]
This is intended. :)
