### ISSUE TITLE
Get null values reading csv file using try_parse_dates=true

### ISSUE THREAD

**Issue by iBuitron** [pola-rs/polars#9508]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi! 
I'm new on polars, so i just follow the guide and get several `null `with:
Data: https://www.kaggle.com/datasets/tarunpaparaju/apple-aapl-historical-stock-data

```
import polars as pl

df1 = pl.read_csv("HistoricalQuotes.csv", try_parse_dates=True)
```

as well, i doit on pandas and had no problem.

### Reproducible example

```python
import polars as pl

df1 = pl.read_csv("HistoricalQuotes.csv",try_parse_dates=True)
print(df1)
```

┌────────────┬─────────────┬───────────┬───────────┬───────────┬───────────┐
│ Date       ┆  Close/Last ┆  Volume   ┆  Open     ┆  High     ┆  Low      │
│ ---        ┆ ---         ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆ str         ┆ i64       ┆ str       ┆ str       ┆ str       │
╞════════════╪═════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null       ┆  $273.36    ┆ 106721200 ┆  $257.26  ┆  $278.41  ┆  $256.37  │
│ null       ┆  $273.52    ┆ 80151380  ┆  $281.1   ┆  $286     ┆  $272.96  │
│ null       ┆  $292.65    ┆ 49678430  ┆  $286.53  ┆  $297.88  ┆  $286.5   │
│ null       ┆  $288.08    ┆ 57668360  ┆  $300.95  ┆  $302.53  ┆  $286.13  │
│ …          ┆ …           ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2010-04-03 ┆  $30.1014   ┆ 89591907  ┆  $29.8971 ┆  $30.1314 ┆  $29.8043 │
│ 2010-03-03 ┆  $29.9043   ┆ 92846488  ┆  $29.8486 ┆  $29.9814 ┆  $29.7057 │
│ 2010-02-03 ┆  $29.8357   ┆ 141486282 ┆  $29.99   ┆  $30.1186 ┆  $29.6771 │
│ 2010-01-03 ┆  $29.8557   ┆ 137312041 ┆  $29.3928 ┆  $29.9286 ┆  $29.35   │
└────────────┴─────────────┴───────────┴───────────┴───────────┴───────────┘
```


### Expected behavior

```
import pandas as pd

df2 = pd.read_csv("HistoricalQuotes.csv", parse_dates=["Date"])
print(df2)
```
```

           Date  Close/Last     Volume       Open       High        Low
0    2020-02-28     $273.36  106721200    $257.26    $278.41    $256.37
1    2020-02-27     $273.52   80151380     $281.1       $286    $272.96
2    2020-02-26     $292.65   49678430    $286.53    $297.88     $286.5
3    2020-02-25     $288.08   57668360    $300.95    $302.53    $286.13
4    2020-02-24     $298.18   55548830    $297.26    $304.18    $289.23
...         ...         ...        ...        ...        ...        ...
2513 2010-03-05    $31.2786  224647427   $30.7057   $31.3857   $30.6614
2514 2010-03-04    $30.1014   89591907   $29.8971   $30.1314   $29.8043
2515 2010-03-03    $29.9043   92846488   $29.8486   $29.9814   $29.7057
2516 2010-03-02    $29.8357  141486282     $29.99   $30.1186   $29.6771
2517 2010-03-01    $29.8557  137312041   $29.3928   $29.9286     $29.35
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr  5 2023, 14:14:37) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  3.1.2
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @iBuitron for the report

the reason is that polars doesn't auto-infer "month-day-year" format yet (only "day-month-year" or "year-month-day")

those that can be parsed as DMY are being parsed as such, and the others are left as nulls

it may be that a `date_format` argument needs adding to `read_csv`, not sure yet

for now, I'd suggest:
```python
In [8]: pl.scan_csv("HistoricalQuotes.csv").with_columns(pl.col('Date').str.to_date(format='%m/%d/%Y')).collect()
Out[8]:
shape: (2_518, 6)
┌────────────┬─────────────┬───────────┬───────────┬───────────┬───────────┐
│ Date       ┆  Close/Last ┆  Volume   ┆  Open     ┆  High     ┆  Low      │
│ ---        ┆ ---         ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆ str         ┆ i64       ┆ str       ┆ str       ┆ str       │
╞════════════╪═════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020-02-28 ┆  $273.36    ┆ 106721200 ┆  $257.26  ┆  $278.41  ┆  $256.37  │
│ 2020-02-27 ┆  $273.52    ┆ 80151380  ┆  $281.1   ┆  $286     ┆  $272.96  │
│ 2020-02-26 ┆  $292.65    ┆ 49678430  ┆  $286.53  ┆  $297.88  ┆  $286.5   │
│ 2020-02-25 ┆  $288.08    ┆ 57668360  ┆  $300.95  ┆  $302.53  ┆  $286.13  │
│ …          ┆ …           ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2010-03-04 ┆  $30.1014   ┆ 89591907  ┆  $29.8971 ┆  $30.1314 ┆  $29.8043 │
│ 2010-03-03 ┆  $29.9043   ┆ 92846488  ┆  $29.8486 ┆  $29.9814 ┆  $29.7057 │
│ 2010-03-02 ┆  $29.8357   ┆ 141486282 ┆  $29.99   ┆  $30.1186 ┆  $29.6771 │
│ 2010-03-01 ┆  $29.8557   ┆ 137312041 ┆  $29.3928 ┆  $29.9286 ┆  $29.35   │
└────────────┴─────────────┴───────────┴───────────┴───────────┴───────────┘
```

**Comment by iBuitron** [comment]
Thx! It fix the problem.
