### ISSUE TITLE
date_range returns Object rather than Datetime when eager=False

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#9510]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not sure if this is a bug but if I create a lazy `pl.date_range` (i.e. eager=False) then the expression has type Object which is inconsistent with eager=True (which has the expected type of Datetime)

### Reproducible example

```python
import datetime, zoneinfo
import polars as pl

from_datetime = datetime.datetime(2014, 1, 1, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
to_datetime = datetime.datetime(2015, 1, 1, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC'))

resample_index = pl.DataFrame({"ts": pl.date_range(from_datetime, to_datetime, '1h', time_unit="ms", time_zone="UTC", eager=True)})
print(resample_index.schema)

resample_index = pl.DataFrame({"ts": pl.date_range(from_datetime, to_datetime, '1h', time_unit="ms", time_zone="UTC", eager=False)})
print(resample_index.schema)
```

### Expected behavior

I would expect resample_index.schema to be the same in both instances, i.e. if I try and join `resample_index` to a dataframe with a `ts` column that is a `Datetime(time_unit='ms', time_zone='UTC')` it works if `resample_index` is created eagerly and fails when it is lazy (because of a type mismathc)

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-4.14.314-238.539.amzn2.x86_64-x86_64-with-glibc2.31
Python:      3.10.8 (main, Oct 13 2022, 22:36:54) [GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
No, your query is flawed. You pass an `Expr` to the column `ts`. An expression is a python `object`. You can put them into a `DataFrame`, but you shouldn't. 

I will close this as this isn't a bug on our side. Discussion can continue.
