### ISSUE TITLE
Read from generated csv file in memory without writing to hard disk using `scan_csv()`

### ISSUE THREAD

**Issue by arnabadas** [pola-rs/polars#9511]
### Problem description

I know that I can use `read_csv()` with `lazy()`, but I want to use `scan_csv()` to get the benefits of lazy eval. How to go about doing that?

**Comment by cmdlineluser** [comment]
May be of use:

> You can use parquet-fromcsv in the meantime to convert compressed CSV/TSV files to parquet and use pl.scan_parquet on them

https://github.com/pola-rs/polars/issues/4950#issuecomment-1594517272

**Comment by arnabadas** [comment]
Closing this in favour of issue #4950
