### ISSUE TITLE
`cumulative_eval()` error if result is a List type series

### ISSUE THREAD

**Issue by bingbong-sempai** [pola-rs/polars#9517]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I want to use `cumulative_eval()` on a List column, but operations that result in a List have this error:  
ComputeError: expected single value, got a result with length n...

A different error happens when i want to get the length of each nested list by calling `list.lengths()`:  
SchemaError: invalid series dtype: expected `List`, got `i64`

### Reproducible example

```python
import polars as pl

# Setup
df = pl.DataFrame({
    'id': [1, 2, 3],
    'lists': [
        [1, 2],
        [2, 3],
        [3, 4]
    ]
})

# List type output - fails
df_expanding = (
    df.with_columns(
        pl.col('lists')
        .cumulative_eval(pl.element().list.explode())
        .alias('expanding_lists')
    )
)

# Scalar output - ok
df_expanding = (
    df.with_columns(
        pl.col('lists')
        .cumulative_eval(pl.element().list.explode().mean())
        .alias('expanding_mean')
    )
)

# Scalar output - fails
df_expanding = (
    df.with_columns(
        pl.col('lists')
        .cumulative_eval(pl.element().list.explode().list.lengths())
        .alias('expanding_length')
    )
)
```

### Expected behavior

Preferably the output would not be type restricted and all 3 examples would work.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-5.15.107+-x86_64-with-glibc2.31
Python:      3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]

----Optional dependencies----
numpy:       1.22.4
pandas:      1.5.3
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by avimallu** [comment]
> I want to use cumulative_eval() on a List column, but operations that result in a List have this error:

That's because you're trying to return an output value that is a `Series` with as many rows as the concatenated list's elements. See output from this code for your `DataFrame`:

```py
(
    df.with_columns(
        pl.col('lists').cumulative_eval(
            pl.element().list.explode(), min_periods=2)
        .alias('expanding_lists'))
)
```

You'll see that it returns a `Series` with 4 values to be fit in a single row. Instead, here you should just do:

```py
(
    df.with_columns(
        pl.col('lists').cumulative_eval(
            pl.element().list.explode().implode())
        .alias('expanding_lists'))
)
```
> A different error happens when i want to get the length of each nested list by calling list.lengths():

The same problem is there in your expression construct - you need to instead do:

```py
(
    df.with_columns(
        pl.col('lists').cumulative_eval(
            pl.element().list.explode().implode().list.lengths())
        .alias('expanding_lists'))
)
```

**Comment by bingbong-sempai** [comment]
Wow thanks so much! Sorry I did not think to use implode with explode at all. Everything works now :)
