### ISSUE TITLE
strange behavior of df.join when `suffix` is also suffix of `on` (under lazy mode)

### ISSUE THREAD

**Issue by whatever60** [pola-rs/polars#9519]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I encountered a strange error when performing join under lazy mode. When I use a `suffix` argument that happens to also be the suffix of the column I am joining on, such error occurs:

```
ComputeError: column 'xxx' not available in schema Schema:
```

It seems that the `xxx` is the name of the `on` column, striped by `suffix` from the right. For example, if I am joining on `ham`, and the suffix happens to be `m`, I get the error saying `ha` not available in the schema.

Similarly, one will be in bad luck when joining on a column whose name ends with "_right", the default value of `suffix`.

In eager mode the above error won't happen.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6.0, 7.0, 8.0],
        "ham": ["a", "b", "c"],
    }
)
other_df = pl.DataFrame(
    {
        "apple": ["x", "y", "z"],
        "ham": ["a", "b", "d"],
    }
)
df.join(other_df, on="ham")
df.lazy().join(other_df.lazy(), how="inner", left_on="ham", right_on="ham", suffix="m").select("ham").collect()
```

### Expected behavior

Run without error and output

```
shape: (2, 1)
┌─────┐
│ ham │
│ --- │
│ str │
╞═════╡
│ a   │
│ b   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-5.15.107+-x86_64-with-glibc2.31
Python:      3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]

----Optional dependencies----
numpy:       1.22.4
pandas:      1.5.3
pyarrow:     9.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

**Comment by stinodego** [comment]
This works as expected on main.
