### ISSUE TITLE
Lazy processing delays throwing exceptions till collect()

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#9522]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When an exception is "raised" during lazy processing. Everything is delayed. Even though it is known already that a certain action (in my case a column inclusion) will fail.

It would be better to fail fast in my opinion, so error processing can happen in each phase. And not all the error processing needs to happen during the collect-phase.

### Reproducible example

```python
import polars as pl

df = pl.LazyFrame({"head1": [1, 2]})
df.select("head2")  # Expecting an exception ColumnNotFoundError
df.select("head2").collect()  # But it's not raised, until the collect stage.
```

### Expected behavior

I am expecting an exception ColumnNotFoundError when selecting an inexisting column

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is something we don't want. There is a non-trivial cost on checking/materializing the schema and we don't want this on every node that is added to the tree. 

Currently it is similar to SQL, you first make your query and then the query gets evaluated once.
