### ISSUE TITLE
Version 0.18.4 can't install due to Maturin error

### ISSUE THREAD

**Issue by parafoxia** [pola-rs/polars#9528]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This issue may be macOS exclusive, as Linux appeared to work okay. I pushed some changes to my repo that requires Polars, and it's suddenly unable to install. This also happens locally.

[CI logs: https://github.com/parafoxia/analytix/actions/runs/5358193182/jobs/9720138943](https://github.com/parafoxia/analytix/actions/runs/5358193182/jobs/9720138943)

(The Windows failures in that pipeline are unrelated -- they've been caused trying to fix *another* problem. Been a good day to do this 😅)

### Reproducible example

```python
`pip install polars`
```

### Expected behavior

The package installs.

### Installed versions

Technically none?

**Comment by avimallu** [comment]
Maybe you're just unlucky to be caught when the repos are being uploaded to PyPI? 😓 
The packages were just released [about an hour ago](https://github.com/pola-rs/polars/releases/tag/py-0.18.4).

**Comment by parafoxia** [comment]
One can hope -- Linux and Windows are now confirmed working in my tests, so it *is* a macOS exclusive problem.

**Comment by ritchie46** [comment]
> Maybe you're just unlucky to be caught when the repos are being uploaded to/compiled on PyPI? sweat_smile The packages were just released [about an hour ago](https://github.com/pola-rs/polars/releases/tag/py-0.18.4), and got onto PyPI about 30 minutes ago.

This :point_up: Sometimes the timing is bad. I will close this.

**Comment by parafoxia** [comment]
Sorry, forgot to update. All seemed to work about an hour after I opened this. Thanks!
