### ISSUE TITLE
Read excel with filtered header

### ISSUE THREAD

**Issue by balakhaniyan** [pola-rs/polars#9529]
### Polars version checks

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

- [X] I have checked that this issue has not already been reported.

### Issue description

I have been used pandas to read excel for a while, and it is ok for all types, but just now I wanted to test polars.read_excel, and I surprised with it behavior: It only reads a few numbers of data (409 rows) but it has more than 100,000 rows

I think it is related to filter option on header, but I'm not sure, and it is important to say that pandas reads this file perfectly and xlsx2csv converts it good.

file: 
[test.xlsx](https://github.com/pola-rs/polars/files/11850336/test.xlsx)

### Reproducible example

```python
pl.read_excel("data.xlsx", read_csv_options={"null_values":["_x005F_x000D_00", "NaN", "_x000D_00"]})
```

### Expected behavior

Return all rows of data as pandas do (but it returns only a few numbers of data)

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Windows-10-10.0.22621-SP0
Python:      3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    0.8.1
xlsxwriter:  3.1.2
```

</details>

**Comment by avimallu** [comment]
Your test file has a filter in it. I removed it (not sure why it impacts the reading, maybe one of the devs can comment), and then I was able to get it to work. First, remove the filter you've applied on the first column. Then run:

```py
pl.read_excel("test.xlsx", read_csv_options = {
    "infer_schema_length": 10000,
    "null_values":["_x005F_x000D_00", "NaN", "_x000D_00"]})
```

I get:

```py
shape: (104_891, 12)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────────┬──────┐
│ نام استان  ┆  کد استان  ┆ نام        ┆ کد شهرستان ┆ … ┆ نام شهر    ┆ CODEREC ┆ NAME       ┆ DIAG │
│ ---        ┆ ---        ┆ شهرستان    ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---        ┆ ---  │
│ str        ┆ i64        ┆ ---        ┆ i64        ┆   ┆ str        ┆ i64     ┆ str        ┆ i64  │
│            ┆            ┆ str        ┆            ┆   ┆            ┆         ┆            ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════════╪══════╡
│ مرکزي      ┆ 0          ┆ اراک       ┆ 1          ┆ … ┆ null       ┆ 4       ┆ امان آباد  ┆ null │
│ مرکزي      ┆ 0          ┆ اراک       ┆ 1          ┆ … ┆ null       ┆ 8       ┆ امان آباد  ┆ 3238 │
│ مرکزي      ┆ 0          ┆ اراک       ┆ 1          ┆ … ┆ null       ┆ 6       ┆ انجدان     ┆ null │
│ مرکزي      ┆ 0          ┆ اراک       ┆ 1          ┆ … ┆ null       ┆ 6       ┆ انجيرک     ┆ null │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …          ┆ …    │
│ البرز      ┆ 30         ┆ چهارباغ    ┆ 7          ┆ … ┆ null       ┆ 8       ┆ لشکراباد   ┆ 3507 │
│ البرز      ┆ 30         ┆ چهارباغ    ┆ 7          ┆ … ┆ null       ┆ 3       ┆ بخش رامجين ┆ null │
│ البرز      ┆ 30         ┆ چهارباغ    ┆ 7          ┆ … ┆ null       ┆ 2       ┆ چهارباغ    ┆ null │
│ البرز      ┆ 30         ┆ null       ┆ null       ┆ … ┆ null       ┆ 1       ┆ البرز      ┆ null │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────────┴──────┘

```

Some formatting issues when rendering in ASCII because of the UTF encoded strings, but otherwise matches youre requirements, right?

**Comment by balakhaniyan** [comment]
Yes, that's true. I have removed filter and got same result, but I thought it isn't ok to remove filter and at least it must warn somewhere in code or doc... for me, it took a while to find the reason.
But, again, I'm not sure that it is related to filter, and it's just a guess and need more checks for confirmation because I create a test and minimal data with filtered header, and it was OK!
Thanks for your reply

**Comment by mcrumiller** [comment]
Hi @balakhaniyan, you need to pass the ` skip_hidden_rows=False` option to `xlsx2csv_options`, as follows:

```python
import polars as pol

pl.read_excel(
    "data.xlsx",
    read_csv_options={
        "null_values":["_x005F_x000D_00", "NaN", "_x000D_00"],
        "skip_hidden_rows": False, # see here
    }
)
```

**Comment by mcrumiller** [comment]
@balakhaniyan did the suggestion work? If so, can this be closed?

**Comment by mcrumiller** [comment]
@balakhaniyan it's a problem with `xlsx2csv` actually. I don't think my above example works (fixed now), you need to pass in that keyword into `xlsx2csv_options`:

```python
import polars as pol

pl.read_excel(
    "data.xlsx",
    read_csv_options={
        "null_values": ["_x005F_x000D_00", "NaN", "_x000D_00"],
    },
    xlsx2csv_options = {
        "skip_hidden_rows": False, # see here
    }
)
```

**Comment by balakhaniyan** [comment]
@mcrumiller I understood it and fixed problems in my code, because you mention it correctly in your comment
> option to xlsx2csv_options
One other minor problem: you import polars as pol and invoke method as pl.read_excel...
But totally it was OK...
