### ISSUE TITLE
read csv fails with large multiline fields

### ISSUE THREAD

**Issue by marcvanheerden** [pola-rs/polars#953]
I was trying to import the training set for this [kaggle competition](https://www.kaggle.com/c/commonlitreadabilityprize) and noticed that it was failing with an incorrect error message
`thread 'main' panicked at 'Field with non closing double-quote at: "`

Since I'm not sure that the kaggle license allows me to share the dataset here I have made a reproducible example [reprex.csv](https://github.com/pola-rs/polars/files/6794801/reprex.csv) . 

After a quick look I _think_ the issue is that this line in get_line_stats:
https://github.com/pola-rs/polars/blob/c8a1d257776e1290ffaf336a1f54c89bb6413bc6/polars/polars-io/src/csv_core/parser.rs#L146

takes the first newline character but that newline character might be within a quoted field which wouldn't indicate a new record in the dataframe. This causes the size of the records to be underestimated and then truncated, losing the closing quote. 

I think it would be good to:
- fix the issue that is causing the error
- make it explicit to the user when a record is truncated (perhaps for datasets with highly skewed record length) and recommend how to fix it

let me know what you think, I would like to work on this issue if you don't mind

**Comment by ritchie46** [comment]
Thanks for reproducing the error.

I don't think the statistics are of influence as that shouldn't truncate the lines. The panic is from this [debug_assert](https://github.com/pola-rs/polars/blob/61ac434e6ab4f14e1c460637ca58a31fa5eec07c/polars/polars-io/src/csv_core/parser.rs#L288). Which I am not confident about being relevant anymore. If I remove it, the file parses correctly. So will a release build.

I think I will remove the debug_assert to fix this issue.

**Comment by ritchie46** [comment]
fixed and released :+1:
