### ISSUE TITLE
Inconsistent behaviour of df.columns vs df argument

### ISSUE THREAD

**Issue by SujeetO** [pola-rs/polars#9536]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

to get the sum along rows of dataframe, we can use any of below commands

```
df.select(pl.sum(df.columns))
df.select(pl.sum(df))
```
however, for pl.implode() , works only with df.columns and not with df

### Reproducible example

```python
`df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]  , "c" : [6,7,8]})

df.select(pl.sum(df.columns))
df.select(pl.sum(df))

df.select( pl.implode(df.columns)  )

df.select( pl.implode(df)  )
`
```

### Expected behavior

df.select( pl.implode(df)  ) should give same o/p as df.select( pl.implode(df.columns)  )

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.02.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.0.3
```

</details>

**Comment by ritchie46** [comment]
We shouldn't accept a DataFrame as argument in any of that. If it works it's coincidental because of "sigh" duck typing.

**Comment by stinodego** [comment]
This now works as expected.
