### ISSUE TITLE
write_database function does not correctly interpret schema in table name

### ISSUE THREAD

**Issue by Niqnil** [pola-rs/polars#9548]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using the `write_database` function in Polars, the function does not correctly interpret the schema and table name when they are provided in the format schema.table. Instead of creating the table in the specified schema, it creates the table in the public schema with the name `schema.table`.

### Reproducible example

```python
import polars as pl
import os
from dotenv import load_dotenv

load_dotenv("../../.env")

CONNECTION_URI = f"postgres://{os.getenv('POSTGRES_USER')}:{os.getenv('PGPASSWORD_POSTGRES')}@{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DBNAME')}"
SCHEMA = os.getenv("POSTGRES_SCHEMA")

# Create a simple DataFrame
df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "B": [6, 7, 8, 9, 10],
    }
)

# Write the DataFrame to the database
df.write_database(
    table_name=f"{SCHEMA}.test_table",
    connection_uri=CONNECTION_URI,
    if_exists="append",
)
```

### Expected behavior

The table should be created in the specified schema with the name `test_table`. However, the table is created in the `public` schema with the name `schema.test_table`.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.19.0-45-generic-x86_64-with-glibc2.35
Python:      3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

OS: Ubuntu 22.04
DB info: "PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit"
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the bug report and example - will have a fix in the next release 👍

**Comment by alexander-beedie** [comment]
FYI the fix for this is now available: 
* https://github.com/pola-rs/polars/releases/tag/py-0.18.7
