### ISSUE TITLE
Series.apply() for pl.Object dtype raises pyo3_runtime.PanicException: not yet implemented

### ISSUE THREAD

**Issue by aploium** [pola-rs/polars#9549]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using apply() to pl.Object dtype, sometimes raise error
```
  File "/opt/miniforge311/lib/python3.11/site-packages/polars/series/series.py", line 4232, in apply
    self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
pyo3_runtime.PanicException: not yet implemented
```
see example below

### Reproducible example

```python
import polars as pl
# force use object here for demo, custom object in real production
s=pl.Series([0,1,2], dtype=pl.Object) 

s.apply(lambda x:{"a":str(x), "b":x})
# raise error
#  File "/opt/miniforge311/lib/python3.11/site-packages/polars/series/series.py", line 4232, in apply
#    self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
# pyo3_runtime.PanicException: not yet implemented

# simple expression seems good
s.apply(lambda x:x+1) 
#shape: (3,)
#Series: '' [i64]
#[
#	1
#	2
#	3
#]
```

### Expected behavior
```
it should gives 
# shape: (3,)
# Series: '' [struct[2]]
# [
# 	{"0",0}
# 	{"1",1}
# 	{"2",2}
# ]
```
### Installed versions

<details>

--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-6.2.1-060201-generic-x86_64-with-glibc2.35
Python:      3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

</details>

**Comment by avimallu** [comment]
You need to specify the return data type so that Polars knows how to handle a dict input (in your example case, and likely your custom object in the production environment):

```py
import polars as pl
s=pl.Series([0,1,2], dtype=pl.Object) 

s.apply(lambda x: {"a":str(x), "b":x}, return_dtype=pl.Object)
```

returns for me

```py
shape: (3,)
Series: '' [o][object]
[
	{'a': '0', 'b': 0}
	{'a': '1', 'b': 1}
	{'a': '2', 'b': 2}
]
```
