### ISSUE TITLE
Add option to quote strings in write_csv

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9555]
### Problem description

When writing a CSV file, a nice feature would be to add quotations around strings, as some programs (like Excel) will auto-infer numeric data if they don't have quotes, which is irritating in some instances like zip codes, where leading 0's get stripped during display. Something like:

```python
df.write_csv("out.csv", quote_strings=True)
```

**Comment by aisayko** [comment]
https://github.com/pola-rs/polars/issues/9433
