### ISSUE TITLE
Add Partition by Booleans/Logical Expressions

### ISSUE THREAD

**Issue by abstractqqq** [pola-rs/polars#9556]
### Problem description

On eager frames, we can only partition by list of column names. This is fine, but sometimes we want to create quick splits like: df_bef_x, df_aft_x, or df_train and df_test. Typically, this is done by creating another boolean column first and then partition. 

I think it is more convenient to allow a logical statement in here. For example
df.partition_by(pl.col('a') < 2000)

I don't know how exactly partition works, but it is possible that this will be much faster than creating the boolean column first and then filter.

**Comment by cmdlineluser** [comment]
Can you use `.groupby()` for this?
```
df = pl.DataFrame({"a": range(20)})

list(df.groupby(pl.col("a") < 10))

# [(False,
#   shape: (10, 1)
#   ┌─────┐
#   │ a   │
#   │ --- │
#   │ i64 │
#   ╞═════╡
#   │ 10  │
#   │ 11  │
#   │ 12  │
#   │ 13  │
#   │ …   │
#   │ 16  │
#   │ 17  │
#   │ 18  │
#   │ 19  │
#   └─────┘),
#  (True,
#   shape: (10, 1)
#   ┌─────┐
#   │ a   │
#   │ --- │
#   │ i64 │
#   ╞═════╡
#   │ 0   │
#   │ 1   │
#   │ 2   │
#   │ 3   │
#   │ …   │
#   │ 6   │
#   │ 7   │
#   │ 8   │
#   │ 9   │
#   └─────┘)]
```

**Comment by abstractqqq** [comment]
Thank you! Never thought about using groupby... I am wondering if this is possible in Lazy mode. We might need some other hacks It looks like LazyGroupBy is not iterable,
