### ISSUE TITLE
Reusing Execution Plan Leads to Float Point Precision Issues

### ISSUE THREAD

**Issue by abstractqqq** [pola-rs/polars#9557]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I saved my LazyFrame's execution plan as a json using .write_json(path). When I loaded it back, reused it on another LazyFrame with the same schema, I realized not all entries are equal. I noticed that sometimes I get errors of magnitude 1e-8, which is quite small but still is some precision loss.

I suspect this is because of something in the json parsing stage that caused this precision loss. 

I am wondering (1) Is it possible to fix this issue? (2) Can we add a tolerance threshold on the frame_equal call?

### Reproducible example

```python
import numpy as np

d = pl.DataFrame(
    {
        'num': np.random.random(1000),
    }
)
plan = d.lazy().select(
    new_col = (pl.col("num") - 2.55678623)/1.11111111
)
plan.write_json("test.json")
d2 = d.clone()
f = open("test.json", "r")
json_str = f.read()
f.close()
test = d2.lazy().from_json(json_str).rename({"new_col":"new_col2"})

different_values = plan.collect()["new_col"] != test.collect()["new_col2"]
print(different_values.sum())
combined = pl.concat([plan.collect(), test.collect()], how="horizontal")
data = combined.filter(pl.col("new_col") != pl.col("new_col2"))
print(data[1, 0])
print(data[1, 1])
```

### Expected behavior

Floats should be the same.  print(different_values.sum()) should print 0.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Windows-10-10.0.19045-SP0
Python:      3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
(2) [polars.testing.assert_frame_equal](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.testing.assert_frame_equal.html#polars.testing.assert_frame_equal) has tolerance params.
