### ISSUE TITLE
csv-parser: remove dependency on csv crate.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#956]
Remove csv crate dependency and only use csv-core

**Comment by ritchie46** [comment]
@marcvanheerden This is maybe an interesting one? The current schema inference uses the `csv` crate. But if we do this with `csv-core` only, we can drop that dependency.

**Comment by marcvanheerden** [comment]
Great, I'll have a look, thanks

**Comment by marcvanheerden** [comment]
Hi @ritchie46 just want to check that I'm doing the right thing here. Should I recreate the functionality in the csv crate that we're using in polars and then drop the dependency? 

That is, should I recreate the setter methods like .has_headers(), .flexible(), .from_reader() and the ByteRecordsIntoIter struct in the polars-io crate?

**Comment by ritchie46** [comment]
@marcvanheerden,  I think we can replace the logic of the `csv` crate with that of the `csv-core`. I believe we only need that during the schema inference. The rest already uses `csv-core`.

**Comment by marcvanheerden** [comment]
Sorry for the delay and lots of questions here, just wanted to clarify.
If I'm not mistaken we do use the `csv` crate outside of schema inference.

We currently rely on the `csv` crate for the following:
1) `csv::Reader`, which is a wrapper for the `csv_core::Reader`, and is used in the `build_csv_reader` and `infer_file_schema` functions and the `build_inner_reader` method.
2) `ByteRecordsIntoIter`, used in `SequentialReader` and the `build_csv_reader` function
3) `ReaderBuilder` which builds Readers

no 3) is quite small and easy to replace, 1) and 2) are quite a bit larger. 

Please let me know if I've made a mistake, seems like a lot of code would need to be rewritten from the csv crate into polars and might not be worth dropping the dependency? Happy to go ahead if that's what you want

**Comment by ritchie46** [comment]
Hi Marc,

I understand you're questions. There is a bit of legacy. I did some pre-work for you in #1001. This removes the `csv_core::Reader` from `SequentialReader` (renamed to `CoreReader`) as it was not used. `CoreReader` only needed an `R: Read`.

I believe that after #1001. The only function using the `csv` readers is `infer_file_schema`.

**Comment by marcvanheerden** [comment]
Sorry for the delay, still working on this. Should wrap it up this weekend

**Comment by ritchie46** [comment]
No worries, it's your time. :)

**Comment by marcvanheerden** [comment]
this issue can be closed, not sure why github didn't autoclose it
