### ISSUE TITLE
pl.Decimal implements equality, but hashes are not equal

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#9564]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When comparing a decimal with `==`, it returns `True`.
But when comparing it with a frozenset with `Decimal` in it, it will return `False`.

I think this is because `frozenset` compares based on hash, and not based on `__eq__`.

The reason that comparing with `NUMERIC_DTYPES` works is because `DataTypeGroup` compares them item by item.

### Reproducible example

```python
from decimal import Decimal
import polars as pl

df = pl.DataFrame( {"decimal": [
    Decimal("5.123456789123456789"),
    Decimal("8.5"),
]})

assert df.schema['decimal'] == pl.Decimal, "Decimal should be a decimal (1)..."
assert df.schema['decimal'] in pl.NUMERIC_DTYPES, "Decimal should be a decimal (2)..."
assert df.schema['decimal'] in frozenset([pl.Decimal]), "Decimal should be a decimal (3)..."
```

### Expected behavior

No asserts should be triggered

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Windows-10-10.0.19044-SP0
Python:      3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.25.0
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> Thanks for the detailed explanation @alexander-beedie !

No problem :)
