### ISSUE TITLE
groupby_dynamic fails on leap years

### ISSUE THREAD

**Issue by peter-fm** [pola-rs/polars#9583]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Running groupby_dynamic on dates with leap years with period='1y' fails as presumably that date doesn't exist in the following year. Error thrown:

**pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot advance '2016-02-29 00:00:00' by 12 month(s). If you were trying to get the last day of each month, you may want to try `.dt.month_end` or append \"_saturating\" to your duration string."))**

### Reproducible example

```python
# no leap year succeeds
pl.DataFrame({'date': pl.Series(['2015-02-28','2015-02-28','2015-03-01']).str.strptime(pl.Date,'%Y-%m-%d'),'value':[1.,2.,3.]}).sort('date').groupby_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())

'value':[1.,2.,3.]}).sort('date').groupby_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())
shape: (2, 2)
┌────────────┬───────┐
│ date       ┆ value │
│ ---        ┆ ---   │
│ date       ┆ f64   │
╞════════════╪═══════╡
│ 2015-02-28 ┆ 2.0   │
│ 2015-03-01 ┆ 3.0   │
└────────────┴───────┘

# with leap year fails
pl.DataFrame({'date': pl.Series(['2016-02-29','2016-02-29','2016-03-01']).str.strptime(pl.Date,'%Y-%m-%d'),'value':[1.,2.,3.]}).sort('date').groupby_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())

pyo3_runtime.PanicException: called Result::unwrap() on an Err value: ComputeError(ErrString("cannot advance '2016-02-29 00:00:00' by 12 month(s). If you were trying to get the last day of each month, you may want to try .dt.month_end or append "_saturating" to your duration string."))


# but changing the first date so only 1 leap year date succeeds
pl.DataFrame({'date': pl.Series(['2016-02-28','2016-02-29','2016-03-01']).str.strptime(pl.Date,'%Y-%m-%d'),'value':[1.,2.,3.]}).sort('date').groupby_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())

'value':[1.,2.,3.]}).sort('date').groupby_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())
shape: (3, 2)
┌────────────┬───────┐
│ date       ┆ value │
│ ---        ┆ ---   │
│ date       ┆ f64   │
╞════════════╪═══════╡
│ 2016-02-28 ┆ 2.0   │
│ 2016-02-29 ┆ 2.5   │
│ 2016-03-01 ┆ 3.0   │
└────────────┴───────┘
```

### Expected behavior

I discovered this when I added a by="group_id" argument which found some cases where a group_id just happened to have some values that were only in a leap year and so the groupby failed. Ideally need it to not fail in these edge cases and just use the month end instead of the 29th in the following year.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    macOS-13.4.1-arm64-arm-64bit
Python:      3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:11:32) 
[Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.23.2
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by peter-fm** [comment]
Thanks, that seems to work as expected!

**Comment by MarcoGorelli** [comment]
nice! any suggestions on how to make the error message clearer, so users would know to try this?

**Comment by peter-fm** [comment]
At least to me it wasn't entirely clear which "duration string" was at fault (since my call had two) and the word "saturating" was very confusing in relation to dates. But I think just an example might have helped, something like `... append "_saturating" to your duration string, e.g. period="1y_saturating"`. Is there any reason why saturating isn't the default?

**Comment by MarcoGorelli** [comment]
thanks - OK I'll see how to clarify. multiple paths can get there, so it's not a given which argument to use in the example

regarding defaults - because it can potentially hide bugs. e.g. if you wanted the last day of the each month, you might erroneously do `pl.date_range(date(2020, 1, 31), date(2020, 6, 30), '1mo', eager=True)` - if 'saturating' was the default, then you'd get
```python
shape: (6,)
Series: 'date' [date]
[
        2020-01-31
        2020-02-29
        2020-03-29
        2020-04-29
        2020-05-29
        2020-06-29
]
```
which probably wasn't what you were expecting. By being strict by default, you're "forced" to ask yourself what you really intended - in this case, it was probably
```python
In [15]: pl.date_range(date(2020, 1, 1), date(2020, 6, 1), '1mo_saturating', eager=True).dt.month_end()
Out[15]:
shape: (6,)
Series: 'date' [date]
[
        2020-01-31
        2020-02-29
        2020-03-31
        2020-04-30
        2020-05-31
        2020-06-30
]
```
, whereas in your case, `_saturating` seems fine

**Comment by peter-fm** [comment]
Ah I see, yes in that kind of situation it shouldn't be default. I guess I assumed it was somehow smarter than just blindly incrementing the number in the relevant part of the date. But I suppose it would be too difficult to identify those situations when it is clear the user would want saturating (i.e. in my case of `groupby_dynamic` with `every=1d` and `period=1y`)? Either way many thanks, I understand how it all works now!

**Comment by MarcoGorelli** [comment]
thanks - reckon
```
cannot advance '2016-02-29 00:00:00' by 12 month(s).
You may want to try using "1y_saturating" instead of "1y".
```
would be clearer? This would require a little refactor, but I think it might be worth it

And perhaps "month_end" doesn't need mentioning here and can be removed from the error message

**Comment by peter-fm** [comment]
That would be better if possible. I think it makes it a lot clearer.

**Comment by MarcoGorelli** [comment]
`_saturating` has since been removed and is now applied automatically, so this can be closed
```
In [23]: pl.DataFrame({'date': pl.Series(['2016-02-29','2016-02-29','2016-03-01']).str.strptime(pl.Date,'%Y-%m-%d'),'val
    ...: ue':[1.,2.,3.]}).sort('date').group_by_dynamic('date', every='1d', period='1y').agg(pl.col('value').mean())
Out[23]:
shape: (3, 2)
┌────────────┬───────┐
│ date       ┆ value │
│ ---        ┆ ---   │
│ date       ┆ f64   │
╞════════════╪═══════╡
│ 2016-02-28 ┆ 2.0   │
│ 2016-02-29 ┆ 2.0   │
│ 2016-03-01 ┆ 3.0   │
└────────────┴───────┘
```
