### ISSUE TITLE
unable to convert json to dataframe, polars panicked

### ISSUE THREAD

**Issue by arthur19q3** [pola-rs/polars#9584]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

i have written a script that retrieves raw data from my server and i was able to print out the JSON 'stock_zh_a_hist'. 
```rust
use reqwest::blocking::get;
use polars::prelude::*;
use serde::{Deserialize, Serialize};
use std::io::Cursor;


#[derive(Serialize, Deserialize, Debug)]
struct StockZhAHist {
    date: String,
    open: f64,
    close: f64,
    high: f64,
    low: f64,
    volume: f64,
    turnover: f64,
    amplitude: f64,
    change_rate: f64,
    change_amount: f64,
    turnover_rate: f64,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let url = "http://127.0.0.1:8080/api/public/stock_zh_a_hist";
    let response = get(url)?.text()?;
    // println!("{}", response);
    // deserialize response with serde
    let stock_zh_a_hist: Vec<StockZhAHist> = serde_json::from_str(&response)?;
    // convert to polars dataframe
    println!("{:?}", stock_zh_a_hist);
    let df = JsonReader::new(Cursor::new(response))
        .infer_schema_len(Some(1000))
        .finish()?;
    println!("{:?}", df);
    Ok(())
}
```

but somehow when i tried to print out the dataframe converted from this JSON, the programme panicked and returned:

`thread 'main' panicked at 'Arrow datatype Struct([Field { name: "date", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: "open", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "close", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "high", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "low", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "volume", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: "turnover", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "amplitude", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "change_rate", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "change_amount", data_type: Float64, is_nullable: true, metadata: {} }, Field { name: "turnover_rate", data_type: Float64, is_nullable: true, metadata: {} }]) not supported by Polars. You probably need to activate that data-type feature.', /home/arthur/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.30.0/src/datatypes/field.rs:158:19.`

and even if i have added the feature dtype-decimal in cargo.toml, the same error persists.

### Reproducible example

-

### Expected behavior

-

### Installed versions

<details>
polars = {version = "0.30.0", features = ["lazy","json","dtype-decimal"]}
</details>

**Comment by universalmind303** [comment]
@arthur19q3 you should be able to get it working by adding `"dtype-struct"` to your polars features.

**Comment by arthur19q3** [comment]
working now. thanks a lot.
