### ISSUE TITLE
init `pl.Dataframe` with generator and single value

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#9587]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

For consistency, I would think that creating dataframe from generator instead of list would be the same thing. I found a case where it works with list and not with generator.

### Reproducible example

```python
import polars as pl

pl.DataFrame({'a': [0, 1], 'b': 1}) # works
pl.DataFrame({'a': [0, 1].__iter__(), 'b': 1}) # ShapeError
```

### Expected behavior

Same result

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:      3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.1
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

**Comment by alexander-beedie** [comment]
FYI: fun python trivia - technically that's an `Iterator` rather than a `Generator` :)

**Comment by alexander-beedie** [comment]
> So this is working now ?

Yes :)
