### ISSUE TITLE
Rust unit test fails on Debian

### ISSUE THREAD

**Issue by vidhyasasi** [pola-rs/polars#9596]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

cargo test faild on Debian

I installed cargo from the source via cargo install --path . and ran cargo test for unit testing and got the following error:

'''
error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:14:20
   |
14 |         let json = serde_json::to_string(&ca).unwrap();
   |                    ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:16:19
   |
16 |         let out = serde_json::from_str::<Series>(&json).unwrap();
   |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:21:20
   |
21 |         let json = serde_json::to_string(&ca).unwrap();
   |                    ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:23:19
   |
23 |         let out = serde_json::from_str::<Series>(&json).unwrap(); // uses `Deserialize<'de>`
   |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:34:20
   |
34 |         let json = serde_json::to_string(&ca).unwrap();
   |                    ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:36:19
   |
36 |         let out = serde_json::from_reader::<_, Series>(json.as_bytes()).unwrap(); // uses `DeserializeOwned`
   |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:52:20
   |
52 |         let json = serde_json::to_string(&df).unwrap();
   |                    ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:53:19
   |
53 |         let out = serde_json::from_str::<DataFrame>(&json).unwrap(); // uses `Deserialize<'de>`
   |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:69:20
   |
69 |         let json = serde_json::to_string(&df).unwrap();
   |                    ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> polars/polars-core/src/serde/mod.rs:71:19
   |
71 |         let out = serde_json::from_reader::<_, DataFrame>(json.as_bytes()).unwrap(); // uses `DeserializeOwned`
   |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> polars/polars-core/src/serde/mod.rs:125:22
    |
125 |         let df_str = serde_json::to_string(&df).unwrap();
    |                      ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> polars/polars-core/src/serde/mod.rs:126:19
    |
126 |         let out = serde_json::from_str::<DataFrame>(&df_str).unwrap();
    |                   ^^^^^^^^^^ use of undeclared crate or module `serde_json`

For more information about this error, try `rustc --explain E0433`.
warning: `polars-core` (lib test) generated 1 warning
error: could not compile `polars-core` (lib test) due to 12 previous errors; 1 warning emitted 

'''

polar version - "polars-cli 0.2.0"
OS - Debian 11

### Reproducible example

cargo test 

### Expected behavior

Expected behaviour is to pass all the tests

### Installed versions

<details>
"polars-cli 0.2.0"
</details>

**Comment by ritchie46** [comment]
> Expected behaviour is to pass all the tests

No, you must use our `Makefile` we don't guarantee to run the tests by running `cargo test` on any rust compiler. You must use exactly our version.

**Comment by vidhyasasi** [comment]
In that case, can you explain how to do unit test for polars in rust?

**Comment by universalmind303** [comment]
@vidhyasasi you should be able to use the `make` commands available in `/crates/Makefile` for testing & building rust polars
