### ISSUE TITLE
`DataFrame.write_csv(sys.stdout, ...)` throws OSError

### ISSUE THREAD

**Issue by julibeg** [pola-rs/polars#9618]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Passing `sys.stdout` to `DataFrame.write_csv()` throws `OSError: write() argument must be str, not bytes`.

I have classes wrapping DataFrames that expose `.write_csv`. I want to be able to write to STDOUT with the same signature as if I was writing to a file (which also works in pandas etc.), but this breaks.

### Reproducible example

```python
import sys

import pandas as pd
import polars as pl
import numpy as np

pandas_df = pd.DataFrame(np.arange(12).reshape(4, 3), columns=list('abc'))

# the below writes to STDOUT as expected
pandas_df.to_csv(sys.stdout)

# this fails with `OSError`
pl.from_pandas(pandas_df).write_csv(sys.stdout)
```

### Expected behavior

The expected behaviour is writing the CSV to STDOUT.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-4.15.0-133-generic-x86_64-with-glibc2.23
Python:      3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by owrior** [comment]
Writing to buffer should fix this:

`pl.from_pandas(pandas_df).write_csv(sys.stdout.buffer)`

**Comment by julibeg** [comment]
Writing to buffer indeed works. Would be great if the docs could be updated to mention this for others who might be unaware. E.g. add the following sentence or similar to the description of the `file` parameter: "Set to `sys.stdout.buffer` to write to STDOUT".

**Comment by avimallu** [comment]
Feel free to raise a PR. Always a help to improve the docs!

**Comment by mcrumiller** [comment]
I think we should allow writing directly to `sys.stdout`, which is a [`TextIOWrapper`](https://docs.python.org/3/library/io.html#io.TextIOWrapper) object that supports `write` directly. I think the Rust side is throwing out this object as invalid when it shouldn't be, but I'm not quite sure how to work around it.
