### ISSUE TITLE
Euclidian division by zero unexpected result

### ISSUE THREAD

**Issue by Beranger** [pola-rs/polars#9620]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When Euclidian division is performed by 0, the result is min int in i64

### Reproducible example

```python
import polars as pl
pl.DataFrame(
    {'a': [1, 1], 
     'b': [0, 2]})\
  .select(pl.col('a')//pl.col('b'))
```
###  Result
```python
shape: (2, 1)
┌──────────────────────┐
│ a                    │
│ ---                  │
│ i64                  │
╞══════════════════════╡
│ -9223372036854775808 │
│ 0                    │
└──────────────────────┘
```

### Expected behavior

Throwing ZeroDivisionError

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.15.0-75-generic-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr  5 2023, 14:14:37) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.1
pandas:      1.5.3
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Regular division returns `inf`:

```python
pl.Series([1])/pl.Series([0])
```
I think `//` should return the same.

**Comment by ritchie46** [comment]
We don't check this, similar to overflow. On the rust side we have `checked_div` that does error/null for this case. We can expose that to python.

**Comment by Wainberg** [comment]
FWIW, pandas auto-converts to float in this scenario:

```python
>>> pd.Series([1, 2]) // pd.Series([1, 2])
0    1
1    1
dtype: int64
>>> pd.Series([1, 2]) // pd.Series([1, 0])
0    1.0
1    inf
dtype: float64
```

while NumPy gives a warning and sets the result to 0:

```python
>>> np.array([1, 2]) // np.array([1, 2])
array([1, 1])
>>> np.array([1, 2]) // np.array([1, 0])
<stdin>:1: RuntimeWarning: divide by zero encountered in floor_divide
array([1, 0])
```

These both seem acceptable. On the other hand, polars's current behavior of setting the result to a finite integer without giving a warning is dangerous and can lead to propagation of errors. It's really important to change this!

**Comment by stinodego** [comment]
This now returns `0` for the floordiv by `0` which is still incorrect.

**Comment by stinodego** [comment]
Closing in favor of #13703
