### ISSUE TITLE
(Python) `apply` not available for Groupby.select_all()

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#963]
I came across this while fixing type hints, will pick this up later in a separate pull request.

The error:
```
>>> df = pl.DataFrame({"a": [2,1,1], "b": [1,2,3], "c": [1.0, 2.0, 3.0]})
>>> df.groupby('a').select_all().apply(lambda x: x.sum())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/.cache/pypoetry/virtualenvs/dataframe-typing-3etD3Smm-py3.9/lib/python3.9/site-packages/polars/frame.py", line 2509, in apply
    for name in selection:  # type: ignore
TypeError: 'NoneType' object is not iterable
```

In contrast, the same statement using `select(['b', 'c'])` instead of `select_all()` works fine.

I will first explicitly handle this error in the pull request with type hints I am working on right now. Will try to implement a fix later.

**Comment by ritchie46** [comment]
Good that you stumble upon this. I want to deprecate this logic. Maybe we can push more into the lazy sugar.

Here is a braindump of how I want the groupby syntax to work:

So the idiomatic groupby+ apply syntax is:

```python
(df.groupby("foo")
   .agg(col("bar").apply(..))
)
```

or if you want to select all, you use the wildcard expression.

```python
(df.groupby("foo")
   .agg(col("*").apply(..))
)
```

Both the above expressions are actually executed in the lazy engine and give allow you to use all the expressions.

There is also syntax that allows looping the groups, which I like to maintain:

```python
for df_group in df.groupby("foo"):
    print(df_group)
```

We also want the shortcuts to work, here I am thinking of:

```python
df.groupby(("foo").first()
```

which aggregates all the columns.


The `select` and `select_all` syntax dates back to one of the first implementations. So lets see what we can delete/deprecate and what we still need for doing a `pivot` and a `downsample`.

**Comment by stinodego** [comment]
Okay that sounds clear. I'm not picking this up right now, but maybe sometime in the coming weeks.

**Comment by zundertj** [comment]
Closing as `select_all` has been deprecated and removed for some time now.
