### ISSUE TITLE
on df creation, if dtypes are specified, it silently does nothing if it can't cast

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#9634]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

inspired from [this SO question](https://stackoverflow.com/questions/76587811/polars-enforcing-dtypes-doesnt-work-why/76588460#76588460)

if we create a df specifying a dtype that doesn't map, it will silently pick a different dtype.

### Reproducible example

```python
import polars as pl

# Create a dictionary with some dummy data
data = {
    'Age': [28, 32, 24, 45, 29],
    'Date of Birth': ['1995-03-15', '1989-08-22', '1999-11-05', '1978-02-10', '1994-06-07'],
    'City': ['New York', 'San Francisco', 'London', 'Tokyo', 'Sydney'],
}

dtypes = {
    'Age': pl.Int64,
    'Date of Birth': pl.Date,
    'City': pl.Utf8
}

# Create the DataFrame with specified data types
df_listing_data = pl.DataFrame(data, schema=dtypes)

```

### Expected behavior

The resulting df should have the schema that was specified or raise an error. In the case of date and datetime, it should try to parse in the way that `str.to_date()` and `str.to_datetime()` do.

### Installed versions

<details>

--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Good news - this actually does now raise the correct error in the current dev branch (the upcoming `0.18.5`), following a semi-related fix; specifically, you'll now get the following useful error instead of a frame with the wrong dtype:
```
ComputeError: strict conversion from `str` to `date` failed for value(s) ["1995-03-15", "1994-06-07", … "1989-08-22"]; 
  if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`.
```
