### ISSUE TITLE
import polars in python throw no module pandas error

### ISSUE THREAD

**Issue by metya** [pola-rs/polars#965]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.8.10

#### What operating system are you using polars on?

Windows

#### Describe your bug.

import `polars` requires `pandas`

#### What are the steps to reproduce the behavior?

Here my example:
```python
In [1]: import polars as pl
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5a5660e7af75> in <module>
----> 1 import polars as pl

~\scoop\apps\miniconda3\current\lib\site-packages\polars\__init__.py in <module>
      1 # flake8: noqa
      2 from .series import Series, wrap_s
----> 3 from .frame import DataFrame, wrap_df, StringCache
      4 from .functions import *
      5 from .lazy import *

~\scoop\apps\miniconda3\current\lib\site-packages\polars\frame.py in <module>
     41 from .utils import coerce_arrow, _is_expr, _process_null_values
     42 import polars
---> 43 import pandas as pd
     44 import pyarrow as pa
     45 import pyarrow.parquet

ModuleNotFoundError: No module named 'pandas'
```

#### What is the expected behavior?
`import polars` shouldn't get that exception so that need to delete `import pandas` from frame.py.

**Comment by ritchie46** [comment]
You are right. This probably slipped in this week. Will fix it. Next week a release without pandas. :)

**Comment by ritchie46** [comment]
Fixed by #968

**Comment by ritchie46** [comment]
Fixed in pre-release: https://pypi.org/project/polars/0.8.11_beta.1/

**Comment by ritchie46** [comment]
fixed and released :+1:
