### ISSUE TITLE
Why CsvWritter only accepts a &mut Writer?

### ISSUE THREAD

**Issue by PatatasDelPapa** [pola-rs/polars#967]
This is probably a breaking change if implemented but I can't help but wonder why does `CsvWriter` only accepts a `&mut Writer` instead of taking ownership of the generic `Writer`. by taking ownership of it the user could decide if it want to pass a the the `Writer` directly or a `&mut Writer` like they do now because of the implementation of `impl<W: Write + ?Sized> Write for &mut W`. If there's a reason why this is this way I would like to know.

As a side note I would like the docs to be a little more user friendly with a note like the `csv` crate like so

> Note that the CSV writer is buffered automatically, so you should not wrap wtr in a buffered writer like io::BufWriter

Even if `polars` doesn't buffer the writer automatically I would still like the docs to say so.

**Comment by ritchie46** [comment]
> Even if polars doesn't buffer the writer automatically I would still like the docs to say so.

Feel free to open a PR and add clarifications to the docs. :) Its really hard for me to see where that's missing.

No specific reason. Could be a `W: Write` indeed. I shall change that.

**Comment by PatatasDelPapa** [comment]
> Feel free to open a PR and add clarifications to the docs. :) 

Will see if I can, haven't really used Github or helped other open source project so I'm rather ignorant on the process.
>Its really hard for me to see where that's missing.

It took me some time but looking at the code, the implementation of `polars::prelude::CsvWriter;` uses `arrow::csv::WriterBuilder` which in itself calls (including others) to `csv::WriterBuilder::from_writer<W: Write>(&self, wtr: W) -> Writer<W>` which in its docs says

> Build a CSV writer from this configuration that writes data to `wtr`.
>
>Note that the CSV writer is buffered automatically, so you should not wrap `wtr` in a buffered writer like `io::BufWriter`.

Nowhere on Polars docs I have seen a similar note but I'm not really sure where to put it, maybe on the [Write CSV Example](https://docs.rs/polars/0.14.6/polars/docs/eager/index.html#write-csv) or the `new` method on `impl<'a, W> SerWriter<'a, W> for CsvWriter<'a, W> ` ([docs](https://docs.rs/polars/0.14.6/polars/prelude/struct.CsvWriter.html#method.new)) but I'm not sure if a note can be put there.
