### ISSUE TITLE
`date < str` raises but `str > date` is allowed

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9674]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Apologies if this is mislabelled but it was somewhat surprising.

I was experiencing odd behaviour without realizing I had a `str` column instead of an actual `date`.

Is there a reason why comparing a date against a string does not raise when the string is the LHS?

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"A": ["2023-12-1", "2022-11-10"]})

df.filter(pl.col("A") > pl.date(2022, 11, 20))

# shape: (1, 1)
# ┌───────────┐
# │ A         │
# │ ---       │
# │ str       │
# ╞═══════════╡
# │ 2023-12-1 │
# └───────────┘


df.filter(pl.date(2022, 11, 20) < pl.col("A"))

# ComputeError: cannot compare 'date/datetime/time' to a string value 
# (create native python {{ 'date', 'datetime', 'time' }} or compare to a temporal column)
```

### Expected behavior

Should both examples not raise?

### Installed versions

<details>

```
Latest commit from main.
```

</details>

**Comment by ritchie46** [comment]
fixed by #9693
