### ISSUE TITLE
Filtering on equality between int and null gives unexpected results

### ISSUE THREAD

**Issue by johanbog** [pola-rs/polars#9689]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When running `.filter(pl.col('a') != pl.col('b'))` on a dataframe where one of the columns contains nulls, rows where one column is `null` and the other is not are filtered out. 

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [1, 3], 'b':[2, None]})
df.filter(pl.col('a') != pl.col('b'))


┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
└─────┴─────┘
```
```


### Expected behavior

I expect no rows to be filtered out, as 3 != null. 

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.31
Python:      3.10.11 (main, May 23 2023, 09:27:52) [GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.2
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
None
```

</details>

**Comment by ritchie46** [comment]
Null values propagate in comparisons. There has been extensive discussion about this. You can use `ne_missing` and `eq_missing` to have you desired behavior.

**Comment by ritchie46** [comment]
See: #9053
