### ISSUE TITLE
`cumsum` does not work on literals

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9712]
### Polars version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It simply does not take effect. Maybe the expression is applied before expanding the literal?

When used inside a window function, there is an error message.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_series_equal

df = pl.DataFrame({"a": [1, 1, 1, 2, 2]})

result = df.with_columns(pl.lit(1).cumsum().alias("result"))
```

Results in:
```
shape: (5, 2)
┌─────┬────────┐
│ a   ┆ result │
│ --- ┆ ---    │
│ i64 ┆ i32    │
╞═════╪════════╡
│ 1   ┆ 1      │
│ 1   ┆ 1      │
│ 1   ┆ 1      │
│ 2   ┆ 1      │
│ 2   ┆ 1      │
└─────┴────────┘
```

Expected:
```python
expected_col = pl.Series("result", [1, 2, 3, 4, 5], dtype=pl.Int32)
expected = df.with_columns(expected_col)
```

```
shape: (5, 2)
┌─────┬────────┐
│ a   ┆ result │
│ --- ┆ ---    │
│ i64 ┆ i32    │
╞═════╪════════╡
│ 1   ┆ 1      │
│ 1   ┆ 2      │
│ 1   ┆ 3      │
│ 2   ┆ 4      │
│ 2   ┆ 5      │
└─────┴────────┘
```

Doing this in a window function throws a ComputeError:
```python
result = df.with_columns(pl.lit(1).cumsum().over("a").alias("result")) 
# ComputeError: the length of the window expression did not match that of the group
```

### Expected behavior

cumsum should be applied properly.

### Installed versions

master

**Comment by mcrumiller** [comment]
> Maybe the expression is applied before expanding the literal?

This must be the case:

```python
df.select(
    (pl.lit(1) - (pl.col('a') + pl.col('a'))  ) # add and subtract for 0
    .cumsum()
    .alias("result")
)
```
```
shape: (5, 1)
┌────────┐
│ result │
│ ---    │
│ i64    │
╞════════╡
│ 1      │
│ 2      │
│ 3      │
│ 4      │
│ 5      │
└────────┘
```

**Comment by ritchie46** [comment]
It is expected. Expansion happens after evaluation. The cumsum of `[1]` = `[1]`. This is what I would expect.

**Comment by stinodego** [comment]
I'm not sure that makes total sense. 

Here's three ways to create the same column:

```python
df = pl.DataFrame({"a": [1, 2, 3]})

lit1 = pl.lit(1).alias("lit1")  # This is the only literal with magic auto-resizing
lit2 = pl.ones(3, dtype=pl.Int32).alias("lit2")
lit3 = pl.lit(pl.Series("lit3", [1, 1, 1], dtype=pl.Int32))

result = df.with_columns(lit1, lit2, lit3)
```
```
shape: (3, 4)
┌─────┬──────┬──────┬──────┐
│ a   ┆ lit1 ┆ lit2 ┆ lit3 │
│ --- ┆ ---  ┆ ---  ┆ ---  │
│ i64 ┆ i32  ┆ i32  ┆ i32  │
╞═════╪══════╪══════╪══════╡
│ 1   ┆ 1    ┆ 1    ┆ 1    │
│ 2   ┆ 1    ┆ 1    ┆ 1    │
│ 3   ┆ 1    ┆ 1    ┆ 1    │
└─────┴──────┴──────┴──────┘
```

But if we add `cumsum`,  the results differ:

```python
result = df.with_columns(lit1.cumsum(), lit2.cumsum(), lit3.cumsum())
```
```
shape: (3, 4)
┌─────┬──────┬──────┬──────┐
│ a   ┆ lit1 ┆ lit2 ┆ lit3 │
│ --- ┆ ---  ┆ ---  ┆ ---  │
│ i64 ┆ i32  ┆ i32  ┆ i32  │
╞═════╪══════╪══════╪══════╡
│ 1   ┆ 1    ┆ 1    ┆ 1    │
│ 2   ┆ 1    ┆ 2    ┆ 2    │
│ 3   ┆ 1    ┆ 3    ┆ 3    │
└─────┴──────┴──────┴──────┘
```

It's not clear to me as a user that `lit1` is special and will behave differently in this situation.

Overall, I think we need some way to discern auto-resizing literals from fixed-length literals.

**Comment by stinodego** [comment]
Ok, I thought there was a distinction between fixed-length literals and auto-resizing literals, but turns out that's not really the case. Any literal of length 1 will be broadcast. That leads to some weird behaviour...

```
df = pl.DataFrame({"a": [1, 2, 3]})

df.with_columns(pl.ones(n=1))  # Works, gets broadcast
df.with_columns(pl.ones(n=2))  # ShapeError
df.with_columns(pl.ones(n=3))  # Works, length is equal to existing columns
```

I would expect the first one to give a ShapeError as well. The literal has the wrong size. Just assuming any expression of length 1 can be broadcast seems very risky to me.

**Comment by ritchie46** [comment]
Numpy does the same. And you if you know the rules it is very clear and perfectly possible to write correct code. You want to be able to broadcast any singleton. That can be a literal or an aggregation or a taken value. All can be valid in business logic.

We must only follow these rules, to make sure that the business logic is resoectedm

**Comment by mcrumiller** [comment]
I know this was closed, but I agree with @stinodego initial report that this behavior is a bit confusing. The reason isn't about broadcasting singletons, it's because of the difference conceptually between `df.select` and `pl.select`.

If I do a `pl.select(pl.lit(1))` it means "select the literal value 1." If I do a `df.select(pl.lit(1))` it means "select a column from `df` with the literal value 1." These have two separate meanings. I would expect the former to be of length 1 and the latter to be the length of `df`. Similarly, separate expressions should be independent, but that's violated by the fact that column `b` differs in `df.select('a', pl.lit(1).alias('b'))` and `df.select(pl.lit(1).alias('b'))`.

I don't care a ton about this but wanted to chime in.

**Comment by ritchie46** [comment]
> it's because of the difference conceptually between df.select and pl.select.

There is not difference. Polars only uses the context `select` to determine the output of columns. After that, the results are as is and singletons will get broadcasted to the output size.

Otherwise you could not combine `col(..).explode() + 1` for instance as your columns would not match.
