### ISSUE TITLE
Literals do not have the correct length if `select` does not include any original columns

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9713]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I would expect the literal to expand to the size of the context.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame({"a": [1, 2, 3]})

result = df.select(pl.lit(1).alias("result"))  # This has length 1...

expected = pl.DataFrame({"result": [1, 1, 1]})
assert_frame_equal(result, expected)  # Fails
```

### Expected behavior

I would expect the literal to expand to the size of the context.

### Installed versions

master

**Comment by ritchie46** [comment]
This is also expected. The context is not leading, the result is. 


```python
df = pl.DataFrame({"a": [1, 2, 3]})
df.select(
    pl.col("a").head(2), # note we only slice 2 rows
    pl.lit(1).alias("result")
) 
```

```
shape: (2, 2)
┌─────┬────────┐
│ a   ┆ result │
│ --- ┆ ---    │
│ i64 ┆ i32    │
╞═════╪════════╡
│ 1   ┆ 1      │
│ 2   ┆ 1      │
└─────┴────────┘
```

Singletons broadcast to the size of the result.

**Comment by stinodego** [comment]
Hmm... fair enough, this makes sense!

I have to change the way I think about literals, I guess.
