### ISSUE TITLE
finding columns with polars datetime objects from a newly created dataframe

### ISSUE THREAD

**Issue by annariley** [pola-rs/polars#9717]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am trying to create a function that finds all entries in a polars DataFrame that are of polars datetime type, and convert them to python datetime objects. When I create a dataframe with a "date" column with polars datetime objects and print the schema, the "date" column is of type "Object" instead of "datetime". This leaves me unable to differentiate between types.

Related question:
Is there a simple way to convert polars datetime objects to python datetime objects? I can't find anything about this in the polars datetime documentation.

Thank you!

### Reproducible example

```python
import polars as pl
# Create Polars DataFrame
polars_df = pl.DataFrame(
    {
        "integer": [1, 2, 3, 4, 5],
        "date": [
            pl.datetime(2022, 1, 1),
            pl.datetime(2022, 1, 2),
            pl.datetime(2022, 1, 3),
            pl.datetime(2022, 1, 4),
            pl.datetime(2022, 1, 5),
        ],
        "float": [4.0, 5.0, 6.0, 7.0, 8.0],
    }
)
print(polars_df.schema)
Output: {'integer': Int64, 'date': Object, 'float': Float64}
```

### Expected behavior

Output: {'integer': Int64, 'date': datetime, 'float': Float64}

### Installed versions

<details>

```
--------Version info---------                                                   
Polars:      0.18.4
Index type:  UInt32
Platform:    macOS-10.16-x86_64-i386-64bit
Python:      3.9.16 (main, May 15 2023, 18:51:40) 
[Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.4
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    macOS-10.16-x86_64-i386-64bit
Python:      3.9.16 (main, May 15 2023, 18:51:40) 
[Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.24.4
pandas:      2.0.2
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Ahh - as per the docstring `pl.datetime` creates a polars _expression_; it is not a datetime _value_. Consequently you're creating a frame that contains `Expr` objects (hence the `Object` dtype) ;)

You should just pass regular python datetimes into the frame constructor instead:
```python
from datetime import datetime
import polars as pl

polars_df = pl.DataFrame(
    {
        "integer": [1, 2, 3, 4, 5],
        "date": [
            datetime(2022, 1, 1),
            datetime(2022, 1, 2),
            datetime(2022, 1, 3),
            datetime(2022, 1, 4),
            datetime(2022, 1, 5),
        ],
        "float": [4.0, 5.0, 6.0, 7.0, 8.0],
    }
)
print(polars_df.schema)
# {'integer': Int64, 'date': Datetime(time_unit='us', time_zone=None), 'float': Float64}

```

**Comment by annariley** [comment]
Thank you! Is it possible with this example to create a DataFrame with polars datetime _values_ then?

**Comment by alexander-beedie** [comment]
I did it above ;)  Polars handles all the necessary conversions for you; you can feed it python (or numpy/pandas/arrow/parquet, etc) values and it'll convert as necessary - and when you read back out, the same is true. 

The frame created in the above (passing python native datetimes in) looks like:

```
# shape: (5, 3)
# ┌─────────┬─────────────────────┬───────┐
# │ integer ┆ date                ┆ float │
# │ ---     ┆ ---                 ┆ ---   │
# │ i64     ┆ datetime[μs]        ┆ f64   │  << note: native datetime type
# ╞═════════╪═════════════════════╪═══════╡
# │ 1       ┆ 2022-01-01 00:00:00 ┆ 4.0   │
# │ 2       ┆ 2022-01-02 00:00:00 ┆ 5.0   │
# │ 3       ┆ 2022-01-03 00:00:00 ┆ 6.0   │
# │ 4       ┆ 2022-01-04 00:00:00 ┆ 7.0   │
# │ 5       ┆ 2022-01-05 00:00:00 ┆ 8.0   │
# └─────────┴─────────────────────┴───────┘
```

**Comment by annariley** [comment]
Oh okay great, thank you!
