### ISSUE TITLE
Unable to convert a pandas Dataframe to a polars Dataframe due to import error with pyarrow

### ISSUE THREAD

**Issue by ZekeMarshall** [pola-rs/polars#9726]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am unable to convert a pandas Dataframe to polars Dataframe due to import error with pyarrow, similarly to this issue https://github.com/pola-rs/polars/issues/2392.

### Reproducible example

```python
import polars
import pandas

# Create a simple dataset on which we can reproduce the bug.
df_test = pandas.DataFrame({
    "foo": [None, 1, 2],
    "bar": [3, 4, 5]
})

# Attempt to convert to pandas
polars.from_pandas(df_test)
```

### Expected behavior

I expect to be able to convert a pandas Dataframe to a polars Dataframe, however I receive the error `ModuleNotFoundError: pa.array requires 'pyarrow' module to be installed`, despite having the latest version of pyarrow installed.

Any help would be greatly appreciated!

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.5
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.6.0
numpy:               1.23.3
pandas:              1.4.4
pyarrow:             12.0.1
pydantic:            1.10.2
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ZekeMarshall** [comment]
Hi @ritchie46 , thanks you that worked, apologies for taking up your time with such a simple error!

**Comment by MarcoGorelli** [comment]
@jackitchai  if you're working in a jupyter notebook, you may want to try this:

![image](https://github.com/pola-rs/polars/assets/33491632/0f318857-20e8-4509-8d56-a12e14bb4d24)

**Comment by jackitchai** [comment]
omg thankyou so much !! @MarcoGorelli it is a simple error lol
