### ISSUE TITLE
Can't read simple ndjson file

### ISSUE THREAD

**Issue by pdufour** [pola-rs/polars#9733]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hi I am trying to read a ndjson file but having cryptic parse errors. Think you can help?

**applicants.jsonl**
```
{"Type":"insert","Key":[1],"SeqNo":1,"Timestamp":1,"Fields":[{"Name":"added_id","Value":2},{"Name":"body","Value":{"a": 1}}]}
{"Type":"insert","Key":[1],"SeqNo":1,"Timestamp":1,"Fields":[{"Name":"added_id","Value":2},{"Name":"body","Value":{"a": 1}}]}
```

**Jupyter Notebook:**
```
snap = "applicants.jsonl"
df = pl.read_ndjson(snap)
```

**Error:**
```
RuntimeError: BindingsError: "expected {dtype} in json value, got object"
```

**Same code on pandas:**
```
pd.read_json(snap, lines=True)
```

**Output:**
Displays the DF

### Reproducible example

```python
snap = "applicants.jsonl"
df = pl.read_ndjson(snap)
```

### Expected behavior

Should parse the new line delimited json into a polars DF.

### Installed versions

<details>

```
Polars:              0.18.5
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.18
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I'm guessing the error is because `Value` has different types:
```python
"Value":2
"Value":{"a": 1}
```
For example, if you try to create a dataframe directly the `2` is lost:
```python
pl.DataFrame(
   [{"Name":"added_id","Value":2},{"Name":"body","Value":{"a": 1}}]
)

# shape: (2, 2)
# ┌──────────┬───────────┐
# │ Name     ┆ Value     │
# │ ---      ┆ ---       │
# │ str      ┆ struct[1] │
# ╞══════════╪═══════════╡
# │ added_id ┆ {null}    │
# │ body     ┆ {1}       │
# └──────────┴───────────┘
```

**Comment by pdufour** [comment]
Thanks @cmdlineluser unfortunately I don't have control over the format of the JSON, I suppose I could preprocess it to make the types more consistent, but trying to avoid an extra step in the process.

**Comment by cmdlineluser** [comment]
You could read the data in a string and split it up:
```python
df.with_columns(
   pl.col('data').str.json_extract(), 
   Fields = pl.col('data').str.json_path_match('$.Fields')
)

# shape: (2, 2)
# ┌───────────────────────────────────┬───────────────────────────────────┐
# │ data                              ┆ Fields                            │
# │ ---                               ┆ ---                               │
# │ struct[5]                         ┆ str                               │
# ╞═══════════════════════════════════╪═══════════════════════════════════╡
# │ {"insert",[1],1,1,[{"added_id","… ┆ [{"Name":"added_id","Value":2},{… │
# │ {"insert",[1],1,1,[{"added_id","… ┆ [{"Name":"added_id","Value":2},{… │
# └───────────────────────────────────┴───────────────────────────────────┘
```
But if you want `Fields` to be unpacked into structs and stored in a single column, they must all have the same schema.

**Comment by pdufour** [comment]
@cmdlineluser I greatly appreciate you writing that solution up, that is very helpful. But that requires putting everything into memory, which I am trying to avoid.

**Comment by ritchie46** [comment]
#9882 gives a user the possibility to control the schema and ignore errors

**Comment by pdufour** [comment]
Hi @ritchie46 If I'm reading this right https://github.com/pola-rs/polars/blob/9d4ba051fa78c0c0579fabbf42154cc8cbaeb686/py-polars/tests/unit/io/test_json.py#L157 the PR just allows you to ignore the errors, but having inconsistent values for types is still not supported? I.e. `[{value: "Foo"}, {value: 2}]`. Is that not something that will be supported in polars?
