### ISSUE TITLE
Support SQL-style null handling in joins

### ISSUE THREAD

**Issue by water-ghosts** [pola-rs/polars#9738]
### Problem description

In SQL, `null` is not equal to itself. As a result, when joining two columns that contain `null` values, these `null` values will not match each other.

Right now, Polars does not follow SQL's behavior. Instead, `null` values do match each other, making it easy to unintentionally duplicate data:

```
>>> df_a = pl.DataFrame([['a', 1], ['b', None], ['c', None]], schema=['name', 'id'])
>>> df_b = pl.DataFrame([['x', 1], ['y', None], ['z', None]], schema=['group', 'id'])
>>> df_a
shape: (3, 2)
┌──────┬──────┐
│ name ┆ id   │
│ ---  ┆ ---  │
│ str  ┆ i64  │
╞══════╪══════╡
│ a    ┆ 1    │
│ b    ┆ null │
│ c    ┆ null │
└──────┴──────┘
>>> df_b
shape: (3, 2)
┌───────┬──────┐
│ group ┆ id   │
│ ---   ┆ ---  │
│ str   ┆ i64  │
╞═══════╪══════╡
│ x     ┆ 1    │
│ y     ┆ null │
│ z     ┆ null │
└───────┴──────┘
>>> df_a.join(df_b, on='id')
shape: (5, 3)
┌──────┬──────┬───────┐
│ name ┆ id   ┆ group │
│ ---  ┆ ---  ┆ ---   │
│ str  ┆ i64  ┆ str   │
╞══════╪══════╪═══════╡
│ a    ┆ 1    ┆ x     │
│ b    ┆ null ┆ y     │
│ c    ┆ null ┆ y     │
│ b    ┆ null ┆ z     │
│ c    ┆ null ┆ z     │
└──────┴──────┴───────┘
```

Polars' behavior is consistent with Pandas, which calls out this difference from SQL in its documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

However, in my opinion, the Polars and Pandas behavior is almost always "wrong" (or, less provocatively, unexpected and potentially misleading), while SQL's behavior is usually "right." `Null` typically represents missing or not-applicable data. SQL takes the position that one missing piece of data is not necessarily the same as another missing piece of data, while Pandas and Polars seem to treat `Null` as a specific discrete value. Besides being confusing for users coming from SQL, this behavior forces users to do additional work to prevent data duplication when joining two columns that might both be missing values.

If the current behavior is desirable as the default (e.g. for compatibility with Pandas), I propose adding a new keyword argument which allows a user to opt into SQL-style joins and prevent `null` values from matching with each other. This will make it much easier to work with datasets with large amounts of missing data. Alternately, I recommend updating the documentation to highlight this potential pitfall, as Pandas does, and provide examples of ways to work around it.

**Comment by avimallu** [comment]
> However, in my opinion, the Polars and Pandas behavior is almost always "wrong" (or, less provocatively, unexpected and potentially misleading)

All in for an option, but my case for not wanting it to be the default:

```py
>>> import polars as pl
>>> import duckdb as db
>>> 
>>> df1 = pl.DataFrame({
...     "a": [1, None, None],
...     "b": [2, 4, None],
...     "c": ["c1", "c2", "c3"]})
>>> 
>>> df2 = pl.DataFrame({
...     "a": [1, None, None],
...     "b": [2, 4, None],
...     "d": ["d1", "d2", "d3"]})
>>> 
>>> print(df1.join(df2, how="left", on=["a", "b"]))
shape: (3, 4)
┌──────┬──────┬─────┬─────┐
│ a    ┆ b    ┆ c   ┆ d   │
│ ---  ┆ ---  ┆ --- ┆ --- │
│ i64  ┆ i64  ┆ str ┆ str │
╞══════╪══════╪═════╪═════╡
│ 1    ┆ 2    ┆ c1  ┆ d1  │
│ null ┆ 4    ┆ c2  ┆ d2  │
│ null ┆ null ┆ c3  ┆ d3  │
└──────┴──────┴─────┴─────┘
>>> 
>>> print(db.sql("""
...     SELECT X.a, X.b, X.c, Y.d
...     FROM df1 X
...     LEFT JOIN df2 Y
...     ON X.a = Y.a AND X.b = Y.b
... """).pl())
shape: (3, 4)
┌──────┬──────┬─────┬──────┐
│ a    ┆ b    ┆ c   ┆ d    │
│ ---  ┆ ---  ┆ --- ┆ ---  │
│ i64  ┆ i64  ┆ str ┆ str  │
╞══════╪══════╪═════╪══════╡
│ 1    ┆ 2    ┆ c1  ┆ d1   │
│ null ┆ 4    ┆ c2  ┆ null │
│ null ┆ null ┆ c3  ┆ null │
└──────┴──────┴─────┴──────┘
```

I would argue that Polars' logic for joining is _correct_ here, and will always be from a Data Science / Analytics perspective.

> SQL takes the position that one missing piece of data is not necessarily the same as another missing piece of data, while Pandas and Polars seem to treat Null as a specific discrete value. 

`NULL` here **does mean** missing data, and for a downstream AI/ML algorithm, it means that my data point for row 2 and 3 `a` is "missing", as is my data point for row 3 for `b`. I **do want** `d` to show up as `d2` and `d3` respectively, because that's an important piece of info that the AI/ML algorithm will use for its prediction.
