### ISSUE TITLE
Add `__hash__` to `DataFrame` class

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#9743]
### Problem description

I wish I could use `hash(df)` on a `polars` dataframe, in particular this would be useful for implementing "cached functions".
An example of that would be:
```python
from functools import lru_cache

@lru_cache
def foo(df: pl.DataFrame):
  ... # do heavy work, e.g validation
```
My understanding is that `polars` dataframes are immutable objects so we should be able to do that ?
I think this could be done by implementing  `__hash__` ?

**Comment by alexander-beedie** [comment]
This isn't a good idea - in order to get an accurate hash you need to hash _all_ of the data that the DataFrame contains, which could be 10s of GB... ;)

**Comment by ritchie46** [comment]
Containers shouldn't be hash for that reason:

```python
>>> hash([1, 2])
TypeError: unhashable type: 'list'
```

**Comment by mcrumiller** [comment]
How about a `pl.Config` setting for a "deep" hash versus a "shallow" schema+size hash?

**Comment by mkleinbort-ic** [comment]
Some notes to this:

I did end up implementing a __hash__ method, it does make caching results much simpler.

I implemented two approaches, in case anyone wants to borrow the code snippet:

```python 

# Very strange, setting a hash yourself - manually

import polars as pl 
from functools import lru_cache

def set_frameHashId(df:pl.DataFrame, frameHashId:int)->pl.DataFrame:
    df._frameHashId = frameHashId
    return df 

def _my_hash_(self)->int|ValueError:
    return self._frameHashId
    
pl.DataFrame.__hash__ = _my_hash_ #! This is dangerous - use carefully 

# Example Use

@lru_cache
def load_data(filepath):
    df = pl.read_csv(filepath).pipe(set_frameHashId, hash(filepath))
    return df

@lru_cache
def summarize_data(df):
    return df.describe()

filepath = 'https://raw.githubusercontent.com/mkleinbort/resource-datasets/master/churn_rate/churn-bigml-20.csv'

df = load_data(filepath)
df.pipe(summarize_data)
```

How does the above work? The key idea is to take a function that is itself fully deterministic, and set some "id" on the output dataframe. The intention is that downstream functions can check that "_frameHashId" via `__hash__` to test if they need to re-run.

The other implementation is a brute-force hashing of the hashes of all the columns (yes, expensive, but sometimes it's best - eg for log files / tags - I don't always want to load a 3Gb file over the network just to check if it's different). 

```python
def _my_hash_(self)->int|ValueError:
    return (self
            .with_row_count(name = '__row_number_for_hash__') # This makes it so that the order of rows matters to the hash
            .select(row_hash = pl.sum_horizontal(pl.all().hash())) # Reduces each row to some big integer
            .select(pl.all().sum().hash()) # Reduces all rows to a very big integer, which is then hashed
            .item()
)
```

**Comment by MarcSkovMadsen** [comment]
+1

Users have started requesting the ability to cache Polars dataframes in HoloViz Panel. So probably lots of users are already requesting this in other frameworks with even more usage. I believe these frameworks normally hash from a large sample of data for Pandas DataFrames. Which in practice works. I would be better for Polars to provide the hashing function instead of many dependent frameworks implementing this.

**Comment by MarcoGorelli** [comment]
@mkleinbort-ic do you need `sum_horizontal`? I think you could just do `.select(pl.struct(pl.all()).hash().sum()).item()`?

Hi @MarcSkovMadsen - could you explain how you hash pandas dataframes please? looks like `pandas.DataFrame.__hash__` just returns `None`
```python
In [25]: pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]}).__hash__ is None
Out[25]: True
```

**Comment by MarcSkovMadsen** [comment]
I'm not the expert. But to me it looks like its defined here @MarcoGorelli . https://github.com/holoviz/panel/blob/2a892a3a2208aac5cef60e1180ed873bb10d43e0/panel/io/cache.py#L106

**Comment by MarcoGorelli** [comment]
Thanks!

Looks like they have their own custom logic, including sampling if the dataframe has many rows. I'd suggest that they do the same for polars then

**Comment by mkleinbort-ic** [comment]
Note that streamlit (popular front-end framework) also struggles to hash polars dataframes. 

I've implemented my own __hash__ similar to what's discussed her, and I found it worth while if used carefully to skip only very intense computations.
