### ISSUE TITLE
polars constructs empty string column name when assigning datetime column to dataframe

### ISSUE THREAD

**Issue by benmaier** [pola-rs/polars#975]
#### Are you using Python or Rust?

Python v3.8.10

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.8.10

#### What operating system are you using polars on?

Ubuntu 20.04

#### Describe your bug.

Setting a column on a dateframe containing Python datetime objects, the datetime values get cast correctly, but the column name is an empty string.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import datetime

df = pl.DataFrame({'a':[0,1], 'b':['r','f']})
df['this_date_column'] = [ datetime.datetime(2020,1,1), datetime.datetime(2020,1,2) ]
print(df.columns)
```
#### What is the actual behavior?

```python
>>> print(df.columns)
['a', 'b', '']
```

#### What is the expected behavior?

```python
>>> print(df.columns)
['a', 'b', 'this_date_column']
```

Edit: initially reported pyarrow version instead of polars version

**Comment by benmaier** [comment]
note: this does not happen when using `datetime.date` objects (get casted to `pl.Date32`)

**Comment by ritchie46** [comment]
Thanks for the issue report. I will fix it.

**Comment by benmaier** [comment]
Related: `datetime.date` should probably get casted to `pl.Date32`, should I open another issue?

**Comment by benmaier** [comment]
btw thanks for developing this. Polars does so many things right, I haven't been using it for long, but it's already my favorite DataFrame framework

**Comment by ritchie46** [comment]
> Related: datetime.date should probably get casted to pl.Date32, should I open another issue?

Yes please.

> btw thanks for developing this. Polars does so many things right, I haven't been using it for long, but it's already my favorite DataFrame framework

Thank you! Now let's hope it gets some traction. Do you use the expressions?

**Comment by benmaier** [comment]
the expressions were the major reason I got into polars if I'm being honest 🎉 

I'm not worried about the traction, I think it's taking off. I'm advertising for it where I can too

**Comment by ritchie46** [comment]
fixed and released :+1:
