### ISSUE TITLE
Make `qcut` support `labels` truncation

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#9755]
### Problem description

The following code will raise exception / panic as of now (py-polars v0.18.6):
```
import polars as pl

df = pl.DataFrame({"x": [1, 1, 1, 1, 2, 2]})

bins = [0.2, 0.4, 0.6, 0.8]
labels = ["q1", "q2", "q3", "q4", "q5"]

df.with_columns(
    pl.col("x").qcut(bins, labels=labels, allow_duplicates=True).alias("q")
)
```

If we omit `labels` in the above `qcut` call, there is no problem. But, the resulting column contains `ranges` instead of custom labels.

I think it would great and reasonable to allow truncating labels (as an option for users) such that we can have the code running fine as well as getting back meaningful labels we want. Something like the following:
```
df.with_columns(
    pl.col("x").qcut(bins, labels=labels, allow_duplicates=True, allow_label_truncation=True).alias("q")
)
```
```
x       q
---    ---
i64    cat
---------
1       q1
1       q1
1       q1
1       q1
2       q2
2       q2
```

**Comment by magarick** [comment]
How is it supposed to know which labels to drop?

**Comment by qqlearn123** [comment]
I think truncating from the end is a reasonable way. Or, provide a few options, such as truncate from start/end/both sides.

**Comment by paladin158** [comment]
How about just truncating from the start as in my example. Or, to make it more flexible, can provide a few reasonable options, like truncating from start, end, or just returning `None`.

The use case is applying `qcut` `over` groups in a large dataset, where there may be several problematic groups (with dup bins), with this feature, we can have both 'getting meaning results for well-behaved groups' and 'no failure (otherwise, need to clean dataset first ourselves by checking quantiles/bins)'.

**Comment by magarick** [comment]
OK, this use case is fair, and it had crossed my mind but I didn't fully consider it. You can't truncate from the start though. I think there's only one logical way to do it, but it still needs to be gated behind an option to avoid confusion.
Let's say you have 5 bins as in your example, assume left-closed intervals the breaks end up being at `[a, a, b, b]` and your labels are `q{1..5}`.
Your only potentially valid intervals are `[-inf, a)`, `[a, b)`, and `[b, inf)`. This corresponds to indices 1, 3, and 5. Notice that if `a` is also the smallest value the first bin will never be filled but that shouldn't cause a problem. What do we do about labels? `q2` and `q4` correspond to guaranteed empty intervals `[a, a)` and `[b, b)` so maybe we don't need them. On the other hand they're just as valid labels for the first and last group as `q1` and `q5`. And if you want to be consistent, you should either go with `[q1, q3, q4]` or `[q2, q3, q5]` as your labels. That way, even though the meaning of the labels is changing, you're picking the first or last per group consistently. 

But in any case, I think there needs to be some warning about what's going on. Maybe adding something to the labels to indicate there was an issue, maybe a warning, maybe refusing to bin bad groups and returning nulls by default?

**Comment by paladin158** [comment]
I think how to align `labels` with `bins` when `bins` has duplicates is more of a design choice or dependent on downstream use cases, because the scenario when `bins` has duplicates is ill-behaved in the first place, we can not expect to make things well-behaved.

So, I think a good middle ground is to think of a couple of truncation/alignment strategies and let user choose which strategy to take based on their needs. For example, if they would like just use the first few they can choose truncation from the start; if an user does not even care ill-behaved cases, they can just specify `return null`.

In terms of API, this is what I cam imagine:
```
df.with_columns(
    pl.col("x").qcut(bins, labels=labels, allow_duplicates=True, allow_label_truncation=True, tuncation_strategy="Start").alias("q")
)
```

**Comment by stinodego** [comment]
The reproducible example does not panic anymore.

Closing in favor of https://github.com/pola-rs/polars/issues/10483
