### ISSUE TITLE
sink_parquet / write_parquet performance issue starting from 0.16.5

### ISSUE THREAD

**Issue by yuuuxt** [pola-rs/polars#9756]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

It seems `sink_parquet` is way slower than pandas' `to_parquet` - 251 times slower in my test below. The issue first appears in `0.16.5` and the last working version is `0.16.4` (back then it was `pl.scan_parquet -> collect -> write_parquet`).

A minimal example would be comparing `pl.scan_parquet -> sink_parquet` and `pd.read_parquet -> to_parquet`. 
For a 13.7M parquet file (created by another `pd.DataFrame.to_parquet`) : 
- `pd.read_parquet -> to_parquet` took 13.1s, the result file size is exactly the same.
- `pl.scan_parquet -> sink_parquet` took 55min 1.8s, the result file size is 15.19M.

(`pl.scan_parquet -> collect -> write_parquet` is as slow as `pl.scan_parquet -> sink_parquet`.)

The file size difference may result from different compression setting - I use pandas to read & save a new version, and the export file size is the same as the original one.

### Reproducible example

```python
# I'm using a 13.7M parquet file
file_path = "an_arbitrary_parquet_file"

# case 1 took 13.1s
pd.read_parquet(file_path).to_parquet("output_path_1")

# case 2 took 55min 1.8s
pl.scan_parquet(file_path).sink_parquet("output_path_2)
```

### Expected behavior

I expect the "to_parquet" process to be as fast as that of pandas, if not faster.

(Also for the file size, if possible - I hope it could be consistent with the ones from `pd.DataFrame.to_parquet`)

(in `0.16.4` the parquet file size from `polars` is smaller than the ones from `pd.DataFrame.to_parquet`)

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          3.5.1
numpy:               1.22.4
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.4
sqlalchemy:          1.4.32
xlsx2csv:            <not installed>
xlsxwriter:          3.0.3
```

</details>

**Comment by cmdlineluser** [comment]
Can you perhaps provide some test data?

If I try on a random file locally I cannot reproduce the timing issue:
```python
!ls -lh pandas.parquet
# -rw-r--r--  1 user  group   122M  7 Jul 05:52 pandas.parquet

%%time
pd.read_parquet('pandas.parquet').to_parquet('pandas-out.parquet')

# CPU times: user 9.97 s, sys: 6.9 s, total: 16.9 s
# Wall time: 15.5 s

%%time
pl.scan_parquet('pandas.parquet').sink_parquet('polars-out.parquet')

# CPU times: user 17 s, sys: 2.57 s, total: 19.6 s
# Wall time: 15.6 s

!ls -lh p*-out.parquet
# -rw-r--r--  1 user  group   122M  7 Jul 05:56 pandas-out.parquet
# -rw-r--r--  1 user  group   229M  7 Jul 05:57 polars-out.parquet
```

**Comment by yuuuxt** [comment]
sure: `data = pd.DataFrame({"col_1":[1,2,3]*1000, "col_2":["a", "b", "c"]*1000})`
![image](https://github.com/pola-rs/polars/assets/3153534/7b398814-d86b-4ad5-b9a1-e82f7799ce27)

and I guess it's os related.

**Comment by cmdlineluser** [comment]
Ah, good point.

There were a couple of Windows related performance issues recently ,perhaps there is a connection.

https://github.com/pola-rs/polars/issues/9731

https://github.com/pola-rs/polars/issues/9497

**Comment by ritchie46** [comment]
I think pyarrows writer has better endoding/compression for repeated strings. You can use polars `write_parquet(use_pyarrow=True)` to use the same writer.

**Comment by yuuuxt** [comment]
> I think pyarrows writer has better endoding/compression for repeated strings. You can use polars `write_parquet(use_pyarrow=True)` to use the same writer.

This helps! updated again to 0.18.6 and `pl.scan_parquet -> collect -> write_parquet(use_pyarrow=True)` works as expected.

Meanwhile `use_pyarrow=False` and `pl.scan_parquet -> sink_parquet` are still (way) slower. Testing on another arbitrary 2.87 MB parquet file:
-  `pl.read_parquet -> write_parquet(use_pyarrow=True)`: 0.8s
- `pl.read_parquet -> write_parquet(use_pyarrow=False)`: 16.1s
- `pl.scan_parquet -> sink_parquet`: 15min 19.5s

**Comment by itamarst** [comment]
I tried on Linux with 0.20.1 and PyArrow 15 and couldn't reproduce the problem. `write_parquet()` was fastest, `sink_parquet()` was a bit slower, `write_parquet(use_pyarrow=True)` was much slower.

```python
# import pandas as pd

# data = pd.DataFrame({"col_1": [1, 2, 3] * 1000, "col_2": ["a", "b", "c"] * 1000})
# data.to_parquet("9756.parquet")

import time
import polars as pl

df = pl.read_parquet("9756.parquet")
start = time.time()
df.write_parquet("/tmp/no_arrow.parquet", use_pyarrow=False)
print("Not", time.time() - start)

start = time.time()
df.write_parquet("/tmp/arrow.parquet", use_pyarrow=True)
print("PyArrow", time.time() - start)

start = time.time()
pl.scan_parquet("9756.parquet").sink_parquet("/tmp/sink.parquet")
print("Sink", time.time() - start)
```

Output:

```
Not 0.0011112689971923828
PyArrow 0.09234476089477539
Sink 0.0017380714416503906
```

**Comment by itamarst** [comment]
With https://github.com/jonashaag/tmp/raw/master/pl-perf-medium.parquet:

```
Pandas 2.443847894668579
Not 1.7407357692718506
PyArrow 1.3975272178649902
Sink 1.9835336208343506
```

**Comment by yuuuxt** [comment]
seems this issue doesn't exist for me using 0.20.10: 
```
Pandas 0.00500178337097168
Not 0.002998828887939453
PyArrow 0.002000093460083008
Sink 0.005013465881347656
```
