### ISSUE TITLE
partition_by(maintain_order=True) doesn't preserve SORTED_ASC/SORTED_DESC flags

### ISSUE THREAD

**Issue by leifmetcalf** [pola-rs/polars#9757]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

partition_by(maintain_order=True) doesn't seem to preserve sorted flags, so you need to run set_sorted again.

### Reproducible example

```python
>>> pl.DataFrame({'one': [1, 2, 3], 'two': ['a', 'a', 'b']}).set_sorted('one').partition_by('two', maintain_order=True)[0]['one'].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}
```

### Expected behavior

{'SORTED_ASC': True, 'SORTED_DESC': False}

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Linux-3.10.0-1160.92.1.el7.jane1.x86_64-x86_64-with-glibc2.2.5
Python:              3.8.8 (default, May 23 2023, 16:41:50) 
[GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2021.11.1
matplotlib:          3.5.1
numpy:               1.21.6
pandas:              1.3.5
pyarrow:             11.0.0
pydantic:            1.8.2
sqlalchemy:          1.3.24
xlsx2csv:            <not installed>
xlsxwriter:          1.4.5
```

</details>

**Comment by m-legrand** [comment]
There is a similar issue with inner joins:

```python
>>> df1 = pl.DataFrame({"x": [1, 2, 3], "y": [2, 4, 6]})
>>> df2 = pl.DataFrame({"x": [1, 2, 3], "z": [1, 4, 9]})
>>> df1.set_sorted("x").join(df2, on="x", how="inner")["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}
>>> df1.join(df2.set_sorted("x"), on="x", how="inner")["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}
```

A subset of a sorted collection should remain sorted IMHO.

**Comment by ritchie46** [comment]
> There is a similar issue with inner joins:
> 
> ```python
> >>> df1 = pl.DataFrame({"x": [1, 2, 3], "y": [2, 4, 6]})
> >>> df2 = pl.DataFrame({"x": [1, 2, 3], "z": [1, 4, 9]})
> >>> df1.set_sorted("x").join(df2, on="x", how="inner")["x"].flags
> {'SORTED_ASC': False, 'SORTED_DESC': False}
> >>> df1.join(df2.set_sorted("x"), on="x", how="inner")["x"].flags
> {'SORTED_ASC': False, 'SORTED_DESC': False}
> ```
> 
> A subset of a sorted collection should remain sorted IMHO.

No, it shouldn't https://github.com/pola-rs/polars/issues/9931#issuecomment-1638553278

**Comment by mcrumiller** [comment]
@ritchie46 there's another `partition_by` issue at #9862 FYI.
