### ISSUE TITLE
set operations do not work with `pl.lit`, only with dataframe columns

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#9764]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The newly added set operations seem to have problems with using `pl.lit()`. They only work as expected on other dataframe columns.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [[1, 2, 3], [4, 5]]})

df.with_columns(b=pl.lit([[3, 4, 6]])).select(pl.col("a").list.intersection("b"))
# shape: (2, 1)
# ┌───────────┐
# │ a         │
# │ ---       │
# │ list[i64] │
# ╞═══════════╡
# │ [3]       │
# │ [4]       │
# └───────────┘

df.select(pl.col("a").list.intersection(pl.lit([[3, 4, 6]])))
# PanicException: assertion failed: `(left == right)`
#   left: `3`,
#  right: `2`
```

### Expected behavior

The behavior should be identical between using a literal expression or an existing dataframe column.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Linux-5.4.0-1103-aws-x86_64-with-glibc2.31
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.21.6
pandas:              1.5.3
pyarrow:             12.0.0
pydantic:            1.10.9
sqlalchemy:          1.4.48
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
This is intended, see [here](https://github.com/pola-rs/polars/issues/6360)

**Comment by moritzwilksch** [comment]
Hmm fair, but then I would expect this to behave similarly to `is_in` which can also take literal lists as arguments, no?
```python
df.select(pl.col("a").list.intersection([3, 4, 6]))
# PanicException: assertion failed: `(left == right)`
#  left: `3`,
#  right: `2`
```

**Comment by deanm0000** [comment]
I'm not following you.

**Comment by ritchie46** [comment]
No, the literal should broadcast in this case. As it is an argument to the set function. That's within our broadcasting rules.

**Comment by orlp** [comment]
This was solved in https://github.com/pola-rs/polars/pull/10668.
