### ISSUE TITLE
Nanosecond timestamps truncated instead of rounded

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [pola-rs/polars#9774]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Nanosecond timestamps are truncated instead of rounded when they are converted to Python datetimes. This behavior was introduced in https://github.com/pola-rs/polars/pull/8337 to fix a different issue.

### Reproducible example

```python
import polars as pl

s = pl.Series([1646058685919897849], dtype=pl.Datetime(time_unit='ns'))

print(s[0])  # 2022-02-28 14:31:25.919897
```

### Expected behavior

```python
print(s[0])
>> 2022-02-28 14:31:25.919898
```

Happy to open a PR for this if you agree that this is expected behavior. If the existing is desired behavior then I'll open a docs PR instead because this tripped me up in migrating from 0.16.x to 0.18.x. 

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.1 (main, Jan 16 2023, 22:41:20) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          0.3.2_alpha.2
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.7
sqlalchemy:          1.4.41
xlsx2csv:            0.8.1
xlsxwriter:          3.1.0
```

</details>

**Comment by mcrumiller** [comment]
I have a PR that rounds, but--is this something we actually _want_ to do? Downcasting almost always truncates in every other case: float to int truncates, datetime to date truncates, etc.

**Comment by rafmagns-skepa-dreag** [comment]
That's a good point. If we want to truncate I think we should update all warnings about ns->us timestamps in the python docs because it's not immediately obvious/on anyone's mind that this would truncate if you're doing something like `df.to_dicts()`

**Comment by mcrumiller** [comment]
I think we should close this, as there's more or less a consensus that we should be truncating. Feel free to make a PR to update the docs if you think it would be helpful.
