### ISSUE TITLE
Support `numpy.datetime64` conversion.

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9779]
### Problem description

This was the first mention of `numpy.datetime64` I had seen so I'm not sure how common its usage is?

From https://stackoverflow.com/questions/76636116
```python
import polars as pl
import numpy as np

busdays = np.busday_offset(["2011-03-20", "2011-03-22", "2011-03-24"], 0, roll="forward")

pl.Series(busdays)

# shape: (3,)
# Series: '' [o][object]
# [
# 	2011-03-21
# 	2011-03-22
# 	2011-03-24
# ]

type(busdays[0])
# numpy.datetime64
```

**Comment by cjackal** [comment]
I'm +1 on this enhancement, this lack of numpy datetime conversion is the reason I always have numpy -> pyarrow -> polars conversion chains instead of simple `pl.from_numpy` in my pipeline.

**Comment by MarcoGorelli** [comment]
For now you  could do
```python
In [16]: busdays = np.busday_offset(["2011-03-20", "2011-03-22", "2011-03-24"], 0, roll="forward")

In [17]: (
    ...:     pl.from_numpy(
    ...:         busdays.astype("datetime64[ms]").astype("int64"), schema=["dates"]
    ...:     ).with_columns(pl.col("dates").cast(pl.Datetime("ms")))
    ...: )
Out[17]:
shape: (3, 1)
┌─────────────────────┐
│ dates               │
│ ---                 │
│ datetime[ms]        │
╞═════════════════════╡
│ 2011-03-21 00:00:00 │
│ 2011-03-22 00:00:00 │
│ 2011-03-24 00:00:00 │
└─────────────────────┘
```
, no pyarrow necessary

**Comment by cjackal** [comment]
@MarcoGorelli I'm afraid your code snippet shows the necessity of `np.datetime64` support; the dtype of `busdays` is `datetime64[D]` so the correct conversion must be to `pl.Date` (which `pyarrow` successfully done):

```python
import polars as pl
import numpy as np
import pyarrow as pa

busdays = np.busday_offset(["2011-03-20", "2011-03-22", "2011-03-24"], 0, roll="forward")
pl.Series(pa.array(busdays))
# shape: (3,)
# Series: '' [date]
# [
# 	2011-03-21
# 	2011-03-22
# 	2011-03-24
# ]
```
To do it in pure polars, one should first parse the dtype of input array and match all the variants of numpy datetime dtype to polars alternatives. I'd say the situation is now numpy-to-polars-knowledge necessary. Of course it is not that hard, but think of a small part of a big data pipeline which consumes any type of index column (most tables allow index columns to be not only integer dtype but timeseries).

**Comment by MarcoGorelli** [comment]
yup, working on this
