### ISSUE TITLE
`polars.last` doesn't appear in the docs

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9781]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`pl.first` exists: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.first.html

`pl.last` does not: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.last.html

Looking at how #9766 was resolved, I think it needs to be added here?

https://github.com/pola-rs/polars/blob/main/py-polars/docs/source/reference/expressions/functions.rst

### Reproducible example

```python
N/A
```

### Expected behavior

Appears in documentation.

### Installed versions

<details>

```
N/A
```

</details>

**Comment by alexander-beedie** [comment]
Yup - well spotted ;)
