### ISSUE TITLE
PanicException when using `Expr.exclude` after a regex column selection

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#9800]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {f'col_{i}': [i] for i in range(10)}
)

df.select(
    pl.col('^col_.*$').exclude('col_0')
)

```

### Issue description

```
PanicException: no exclude expected at this point
```

### Expected behavior

According to the [doc](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.exclude.html) 
> Only works after a wildcard or regex column selection.

I would expect it will return col_1...col_9 exclude col_0

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            macOS-13.4-arm64-arm-64bit
Python:              3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.22.4
pandas:              2.0.2
pyarrow:             11.0.0
pydantic:            1.10.7
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Aside from the exception, you could use the new selectors module for this if you're not aware of it:

https://pola-rs.github.io/polars/py-polars/html/reference/selectors.html

```python
df.select(
   cs.by_name('^col_.+$') & ~cs.by_name('col_0')
)

# ┌───────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
# │ col_1 ┆ col_2 ┆ col_3 ┆ col_4 ┆ … ┆ col_6 ┆ col_7 ┆ col_8 ┆ col_9 │
# │ ---   ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
# │ i64   ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
# ╞═══════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
# │ 1     ┆ 2     ┆ 3     ┆ 4     ┆ … ┆ 6     ┆ 7     ┆ 8     ┆ 9     │
# └───────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘
```

**Comment by stevenlis** [comment]
@cmdlineluser Is this a bug or the doc is wrong. I hope `exclude()` could support this so that you could chain other exprs and do something on the fly.

**Comment by cmdlineluser** [comment]
@stevenlis I'm not entirely sure. Perhaps this worked previously and a regression has occurred.

The docs suggest that it should work.

It only seems to work with `pl.col('*').exclude()` or `pl.all().exclude()` from some brief testing.

**Comment by stevenlis** [comment]
@cmdlineluser Indeed, it is what I found as well...
