### ISSUE TITLE
Add `dataframe.add` and other arithmetic operators with `fill_value`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9804]
### Problem description

Pandas has a very useful set of functions, e.g. [`DataFrame.add`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.add.html), which adds two dataframes similarly to `df1 + df2`, but also allows for the `fill_value` parameter to fill in missing values in one dataframe if the values are not present in the other. It does this by aligning on the index.

Because polars doesn't have an index, an equivalent function would require an (optional) `on` parameter. This function would essentially be syntactic sugar for an outer join + add columns + remove columns. Without the `on` parameter, the frames would just be added with null values filled with the fill value.

Example:

```python
df1 = pl.DataFrame(
    {
        "key": [1, 2, 3, 4, 5],
        "a": [1, 2, 3, 4, None],
        "b": [1, 2, 3, None, 5],
        "c": ["a", "b", "c", "d", None],
        "d": ["a", "b", "c", None, "e"],
    }
)

df2 = pl.DataFrame(
    {
        "key": [1, 2, 3, 4, 5],
        "a": [1, None, 3, 4, 5],
        "b": [1, 2, None, 4, 5],
        "c": ["a", None, "c", "d", "e"],
        "d": ["a", "b", None, "d", "e"],
    }
)

out = df1.add(
    df2, fill_value={
        "a": 100,
        "b": 0,
        "c":
        "*FILL_C*",
        "d": "*FILL_D*"
    }, on="key"
)

print(f"df1:\n{df1}")
print(f"df2:\n{df2}")
print(f"out:\n{out}")
```
```
df1:
shape: (5, 5)
┌─────┬──────┬──────┬──────┬──────┐
│ key ┆ a    ┆ b    ┆ c    ┆ d    │
│ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64 ┆ i64  ┆ i64  ┆ str  ┆ str  │
╞═════╪══════╪══════╪══════╪══════╡
│ 1   ┆ 1    ┆ 1    ┆ a    ┆ a    │
│ 2   ┆ 2    ┆ 2    ┆ b    ┆ b    │
│ 3   ┆ 3    ┆ 3    ┆ c    ┆ c    │
│ 4   ┆ 4    ┆ null ┆ d    ┆ null │
│ 5   ┆ null ┆ 5    ┆ null ┆ e    │
└─────┴──────┴──────┴──────┴──────┘

df2:
shape: (5, 5)
┌─────┬──────┬──────┬──────┬──────┐
│ key ┆ a    ┆ b    ┆ c    ┆ d    │
│ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64 ┆ i64  ┆ i64  ┆ str  ┆ str  │
╞═════╪══════╪══════╪══════╪══════╡
│ 1   ┆ 1    ┆ 1    ┆ a    ┆ a    │
│ 2   ┆ null ┆ 2    ┆ null ┆ b    │
│ 3   ┆ 3    ┆ null ┆ c    ┆ null │
│ 4   ┆ 4    ┆ 4    ┆ d    ┆ d    │
│ 5   ┆ 5    ┆ 5    ┆ e    ┆ e    │
└─────┴──────┴──────┴──────┴──────┘

out:
shape: (5, 5)
┌─────┬─────┬─────┬───────────┬───────────┐
│ key ┆ a   ┆ b   ┆ c         ┆ d         │
│ --- ┆ --- ┆ --- ┆ ---       ┆ ---       │
│ i64 ┆ i64 ┆ i64 ┆ str       ┆ str       │
╞═════╪═════╪═════╪═══════════╪═══════════╡
│ 1   ┆ 2   ┆ 2   ┆ aa        ┆ aa        │
│ 2   ┆ 102 ┆ 4   ┆ b*FILL_C* ┆ bb        │
│ 3   ┆ 6   ┆ 3   ┆ cc        ┆ c*FILL_D* │
│ 4   ┆ 8   ┆ 4   ┆ dd        ┆ *FILL_D*d │
│ 5   ┆ 105 ┆ 10  ┆ *FILL_C*e ┆ ee        │
└─────┴─────┴─────┴───────────┴───────────┘
```

**Comment by gab23r** [comment]
IMO, the `on` keyword is adding too much complexity to a simple `add` function. If the user needs to join two dataframes then he can use the join function.
For the `fill_na`, maybe pandas added them for performance reason or because of their bad NA handling. I don't think polars need this. 
In my understanding the beauty of the laziness is that we can write our query with small building block ie; `join` -> `add` -> `fill_null` and the optimizer would be able to understand what he can do. Si that we don't need to complexity our function signature for performance.

**Comment by mcrumiller** [comment]
@gab23r the reason pandas has it isn't for performance reasons or bad NA handling: it's so that you can add two dataframes, one with new information, without the NaN values clobbering new data. Consider you have data coming in with new records and you're finding a running total:

`df1`:
| Country | total beers |
|----------|-------------:|
| Finland  |  83 |
| Belgium | 91 |
| Spain     | 54 |
| Ireland | 984 |

`df2`:
| Country | total beers |
|----------|-------------:|
| Finland  |  16 |
| Belgium | 14 |
| Spain   | 23 |
| Ireland | 91 |
| USA     | 54 |

Adding these frames isn't easy because, even after aligning, old missing data will be `None` which, when added to new data, remains as `None`, so we have to fill with 0s. Thus, we require the following steps:

1. Rename `df2.[total beers]` to `df2.[total beers right]`
2. Outer join the tables
3. Fill nulls with  in the beers columns
4. Add `df1.[total beers]` to `df2.[total beers right]`
5. Remove the `total beers right` column

Result:
`total`:
`df2`:
| Country | total beers |
|----------|-------------:|
| Finland  |  99 |
| Belgium | 105 |
| Spain   | 77 |
| Ireland | 1,075 |
| USA     | 54 |

I'd think this functionality would be useful enough for the API, and when called something like `add_missing` it would be obvious enough what's going on. The `on` keyword could be renamed to `keys` perhaps, as I agree it's not quite as obvious.

**Comment by gab23r** [comment]
Ah.. Right because `pd.DataFrame` align on the index. Ok I understand where you come from. I personnaly never use the index in pandas so I don't miss this 'auto alignement' 'functionality with polars. And yeah, I join, fillna and sum in 3 steps

**Comment by stinodego** [comment]
I don't think we should support this. `DataFrame.add` could do any number of things. If you want to do what you want `add` to do here, just `join`/`add`/`fill`. That way, it's easy to see exactly what is going on.
