### ISSUE TITLE
Use pyarrow write_to_dataset instead of write_table when writing parquet files

### ISSUE THREAD

**Issue by potzenhotz** [pola-rs/polars#9812]
### Problem description

Hey,

currently _pyarrow.write_table()_ function is used when writing a parquet file using _use_pyarrow=True_.

This does not support a variety of pyarrow features like for example partitioned parquet files.

Is it possible to switch from _pyarrow.write_table()_ to _pyarrow.write_to_dataset()_? With that partitioned parquet files would be possible to write and you could still backport the _write_table()_ function with the _use_legacy_dataset=True_ parameter.

Following Function  [write_parquet()](https://github.com/pola-rs/polars/blob/main/py-polars/polars/dataframe/frame.py#L3025-L3113) would need to be updated.
We could use the  _use_legacy_dataset=True_ parameter inside of pyarrow_options to switch between _write_table()_ and _write_dataset()_

**Would it be a plausible change to you? If so, I could draft a  PR.**

Links:

- https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_to_dataset.html

- https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html

**Comment by deanm0000** [comment]
I would be against changing default behavior unless there's a really compelling reason to. I'd rather see a new parameter maybe call it `use_pyarrow_dataset` that would change the usage from `write_table` to `write_to_dataset`.

There'd just need to be a check to raise an error if both are set to True.

Otherwise the `pyarrow_options` would just be used in either case.

**Comment by deanm0000** [comment]
As a tangent, one thing I've [brought up before](https://github.com/pola-rs/polars/issues/5278) is to, at least change the docs, if not the behavior, around statistics. Specifically, if you use `use_pyarrow` then the polars default of False on statistics is carried over to pyarrow where the default is True. It seems there should be at least be a note warning people that that is going to happen if not just let the pyarrow default prevail. 

As an even deeper tangent, I've never seen a noticeable difference in writing files with statistics on in terms of write times or file sizes that justifies the default being False but I digress.

**Comment by potzenhotz** [comment]
After #9835 and #10471 are merged this can be closed
