### ISSUE TITLE
repeat_by does not work with pl.lit

### ISSUE THREAD

**Issue by markxwang** [pola-rs/polars#9815]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({"a": [2, 3, 4]}).select(pl.lit("*").repeat_by(pl.col("a")))
```

### Issue description

ComputeError: Length of repeat_by argument needs to be 1 or equal to the length of the Series. Series length 1, by length 3

### Expected behavior

Expect to return a series of lists where the * literal is repeated by column a

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.10.5 (main, Sep  6 2022, 09:52:19) [Clang 13.1.6 (clang-1316.0.21.2.5)]

----Optional dependencies----
numpy:       1.23.4
pandas:      2.0.0
pyarrow:     10.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.6.2
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

**Comment by deanm0000** [comment]
This is intended. See https://github.com/pola-rs/polars/issues/6360

To make it work as expected, create the column first like this:

```
(
    pl.DataFrame({"a": [2, 3, 4]})
        .with_columns(s=pl.lit('*'))
        .select(pl.col('s').repeat_by(pl.col('a')))
        )
```

**Comment by cmdlineluser** [comment]
Just browsing old issues, this was implemented in https://github.com/pola-rs/polars/pull/10735 and can be closed.
```python
pl.DataFrame({"a": [2, 3, 4]}).select(pl.lit("*").repeat_by(pl.col("a")))

# shape: (3, 1)
# ┌───────────────────┐
# │ literal           │
# │ ---               │
# │ list[str]         │
# ╞═══════════════════╡
# │ ["*", "*"]        │
# │ ["*", "*", "*"]   │
# │ ["*", "*", … "*"] │
# └───────────────────┘
```

**Comment by romanovacca** [comment]
@stinodego can be closed
