### ISSUE TITLE
read parquet s3 wildcard only reads one parquet

### ISSUE THREAD

**Issue by markxwang** [pola-rs/polars#9817]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.read_parquet("s3://bucket/*.parquet")
```

### Issue description

This only reads one partition

### Expected behavior

Read all the partitions and concatenate them together

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by deanm0000** [comment]
wildcards in read_parquet or scan_parquet only works for local filesystems.

[See here](https://stackoverflow.com/a/75892438/1818713)

**Comment by mberlinger3** [comment]
you can use [universal-pathlib](https://github.com/fsspec/universal_pathlib) to create an iterator to read in multiple files and concatenate them like this:
```python

from upath import UPath
import polars as pl

pl.concat(
    [
        pl.read_parquet(f.as_posix())
        for f in UPath(f"s3://{bucket}/{key}").glob("**/*.parquet")
    ]
)
```

**Comment by someaveragepunter** [comment]
Upvoting and reviving this feature request since 0.20.x now has native rust support for cloud reads. supporting wildcards in scan_parquet and read_parquet would likely provide a meaningful performance boost over a 2nd call to first list all files.

**Comment by someaveragepunter** [comment]
I tested on 0.19.19 and 0.20.4 python 3.10 and 3.11 on linux and windows in all cases pl.read_parquet and pl.scan_parquet read only one read one single file when wildcard * is used.

**Comment by deanm0000** [comment]
Take out the extension so it's just s3://bucket/*

**Comment by deanm0000** [comment]
@someaveragepunter please open an issue with a MRE of a situation where it doesn't work in scan_parquet
