### ISSUE TITLE
Unify `sort` and `sort_with_options`

### ISSUE THREAD

**Issue by CloseChoice** [pola-rs/polars#9820]
### Problem description

Currently there are two main ways how we can sort: There is [`sort_with_options`](https://github.com/pola-rs/polars/blob/main/polars/polars-core/src/frame/mod.rs#L1975) which takes the struct [`SortOptions`](https://github.com/pola-rs/polars/blob/main/polars/polars-core/src/chunked_array/ops/mod.rs#L478) as input and [`sort`](https://github.com/pola-rs/polars/blob/main/polars/polars-core/src/frame/mod.rs#L1964) which uses single arguments. The difference between the two is that we can pass multiple columns on which to sort in descending order to the `sort` function while this is not possible for `sort_with_options`. 

This should be fixed, probably in favor of using `SortOptions` or [`SortMultipleOptions`](https://github.com/pola-rs/polars/blob/main/polars/polars-core/src/chunked_array/ops/mod.rs#L486C19-L486C19) for the `sort` function but by keeping it's functionality.

I would propose to use `SortMultipleOptions` for the `sort` function and removing `sort_with_options`. Then one needs to check whether we can implement `Default` for `SortMultipleOptions`.

**Comment by CloseChoice** [comment]
I would like to take this on. Would be great if someone can assign me.

**Comment by CloseChoice** [comment]
Okay, this turns out to be quite complicated because of we are already using `SortOptions` and `SortOptionsMultiple` in various different places (e.g. in the sorting of `ChunkedArray`). My plan was basically to change `SortMulitpleOptions` from
```rust
#[derive(Clone)]
#[cfg_attr(feature = "serde-lazy", derive(Serialize, Deserialize))]
pub struct SortMultipleOptions {
    pub other: Vec<Series>,
    pub descending: Vec<bool>,
    pub multithreaded: bool,
}
```
to
```rust
#[derive(Clone)]
#[cfg_attr(feature = "serde-lazy", derive(Serialize, Deserialize))]
pub struct SortMultipleOptions {
    pub by_columns: Vec<SmartString>,
    pub descending: Vec<bool>,
    pub multithreaded: bool,
    pub maintain_order: bool,
    pub nulls_last: bool,
}
```
But this does not work, since we the sorting of `ChunkedArray` needs `other` to be a series. I am thinking of changing the type of `by_columns` (which would be the replacement of `other`) to `Vec<Series>` and then creating some constructor function `SortMultipleOptions::new_from_columns(by_column_names: Vec<SmartString>, descending: Vec<bool>)`. Does this sound acceptable?

**Comment by CanglongCl** [comment]
Hi @CloseChoice, are you working on this? If you did not start yet, I'd like to help.
