### ISSUE TITLE
Fix Rust test for logical plan optimizer for categoricals

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9828]
There's a Rust test for the logical plan optimizer for categorical columns. It should do the following:
* Make sure categorical columns are not cast to Utf8 when doing an equality check with a string literal.
* Make sure categorical columns ARE cast to Utf8 when doing an addition with a string literal

See code here:
https://github.com/pola-rs/polars/blob/a1d5a228eb054d9679239f235eab1d236f3820f1/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs#L518-L541

However, the test does not compile. It is outdated and hasn't been run in a while. Still, we want to test this functionality. So the test should be rewritten for the latest syntax.

**Comment by ritchie46** [comment]
Thanks! :)
