### ISSUE TITLE
String column concatenation

### ISSUE THREAD

**Issue by potter420** [pola-rs/polars#983]
#### Describe your feature request
In our ETL flow, we usually concatenate multiple column after casting them to strings then hash them for fast change comparison.
This can be done quite fast in pandas but for some reason, it taking quite a while in polars.
```python
import pandas as pd
import pyarrow as pa
import polars as pl
import numpy as np
import time

long_string = 'This is a very long ass string column that make us mad just to process this'
sample_data = pd.DataFrame({
    **{'i'+str(i): np.random.randint(3500000,9500000,200000)  for i in range(10)},
    **{'s'+str(i): [long_string]*200000 for i in range(15)}
}
)
# We mostly load our data from S3 as parquet file, read by pyarrow first then convert to polars
sample_data_pa = pa.Table.from_pandas(sample_data)
sample_data_pl = pl.from_arrow(sample_data_pa)

# Get the real size of data
sample_data_pa.nbytes/1024**2
# Pandas string concatenation
start = time.time()
sample_data['i1'].astype('str').str.cat(sample_data.loc[:,'i2':].astype('str'),sep='@')
end = time.time()
print(end-start) # 3.5446646213531494 seconds.
# Polars equivalent
expr = None
for col in sample_data_pl.columns:
    if expr:
        expr += pl.col(col).cast(pl.Utf8) + pl.lit('@', pl.Utf8)
    else:
        expr =  pl.col(col).cast(pl.Utf8)
start = time.time()
sample_data_pl.with_columns(expr.alias('help')).select('help')
end = time.time()
print(end-start) # 13.494059324264526 seconds
```
In the above scripts, if I try increase the number of string columns, it get worse.

Is there any reason for this slow operation or I did something wrong?

**Comment by ritchie46** [comment]
This is an interesting one! :slightly_smiling_face: 

Your query is accidentally quadratic. The columnar string addition creates a new `str` column every iteration.

Let's say we have this column: `["a", "b", "c"]`. This column is represented in memory as: `"abc"`. -> 3 bytes

If we add this to itself, we get a new memory location with:

`"aabbcc"`  -> 6 bytes

If we then add it again, 

"aaabbbccc" -> 9 bytes

We keep writing bytes to  a new memory buffer and only the last iteration does the same amount of work as pandas does.

I will make sure that there is a `concat` kernel/ function to this operation in linear time.

**Comment by potter420** [comment]
I changed the code using fold and it quite fast now:

```python
start = time.time()
expr1 = pl.fold(pl.lit('', pl.Utf8), lambda x, y: x + '@' + y, [pl.col(e).cast(pl.Utf8) for e in sample_data_pl.columns] )
sample_data_pl.select(expr1.alias('help'))
end = time.time()
print(end-start) # 5.489788770675659
```
WIth 20 string columns:
polars: 9.843178749084473
pandas: 5.053622245788574
Much better than previous result. I did set the number of string columns to 40 before to match our real data, pandas in 7.5 secs and polars with the previous approach straight up take forever (waited for 4 min then I cancel).

**Comment by ritchie46** [comment]
> I changed the code using fold and it quite fast now:

Again interesting! It should not have less algorithmic complexity. After inspecting the code, I found that `fold` parallelizes the arguments evaluation in a divide and conquer manner, where a normal `+` operation does not.

I also added `concat_str` function in #984. This should have linear time complexity.

I will benchmark later. Or you could already try it out, if you don't mind compiling. :)

**Comment by ritchie46** [comment]
Benchmarks with the new `concat_str` function:

pandas: 
```python
start = time.time()
sample_data['i1'].astype('str').str.cat(sample_data.loc[:,'i2':].astype('str'),sep='@')
end = time.time()
```
2.721155881881714 s

polars as in this issue:
```python
expr = None
for col in sample_data_pl.columns:
    if expr:
        expr += pl.col(col).cast(pl.Utf8) + pl.lit('@', pl.Utf8)
    else:
        expr =  pl.col(col).cast(pl.Utf8)
start = time.time()
sample_data_pl.with_columns(expr.alias('help')).select('help')
end = time.time()
print(end-start)
```
11.807398319244385 s

polars fold:

```python
start = time.time()
expr1 = pl.fold(pl.lit('', pl.Utf8), lambda x, y: x + '@' + y, [pl.col(e).cast(pl.Utf8) for e in sample_data_pl.columns] )
sample_data_pl.select(expr1.alias('help'))
end = time.time()
print(end-start) 
```
3.3436739444732666 s

polars concat_str

```python
start = time.time()
sample_data_pl.select([pl.concat_str(sample_data_pl.columns)])
end = time.time()
print(end-start) 
```
0.38724207878112793 s

**Comment by potter420** [comment]
Thanks for the benchmark. I did my own test too on AWS c5 EC2, 3.61GZ , total of 50 columns:
pandas: 10.800254106521606 s
polars: 1.4643571376800537 s

Blazingly fast as promised.

**Comment by ritchie46** [comment]
> Blazingly fast as promised. 

:slightly_smiling_face:

**Comment by ritchie46** [comment]
@potter420 Would a `hash_row` method be of value to you guys? Internally this is also needed for grouping and joining. A row would be hashed to a `UInt64` Series, which would be a lot quicker.

**Comment by potter420** [comment]
Yes it is, but we also need it casted to Int64 as well. Redshift does not like Uint64 for some reason :(
Currently we use xxh3 as our hashing algorithm.
Our python hash function currently:
```python
def hash(x):
    return int.from_bytes(xxhash.xxh3_64_digest(x),'big', signed=True)
```

**Comment by ritchie46** [comment]
Added and released
