### ISSUE TITLE
Polars spills a gigantic amount of data to disk while sorting

### ISSUE THREAD

**Issue by orf** [pola-rs/polars#9847]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
q = pl.scan_parquet("../data/original/*.parquet")
df = q.select(pl.col("path"), pl.col("size")).top_k(10, by="size").fetch(5, streaming=True)
```

### Issue description

I have a set of 215 parquet files with a total size of 29.6gb. Each parquet file is between 100MiB and 227MiB, the data is public but slightly involved to fetch. I can provide it if it is really needed.

Upon running the query above to find the top 10 `(path, size)` rows my machine runs out of disk - polars writes over 400gb of data to the `polars/sort/...` temporary directory. I see the following warning which may be relevant:

```
Cannot combine 'streaming' with 'common_subplan_elimination'. CSE will be turned off.
```

Removing the `p.select("path")` expression results in the process working as expected and returning results. Removing `streaming=True` also works.

Total rows in the files is ~983 million, and the schema:

```
version: 2
num of rows: 3158460
created by: Arrow2 - Native Rust implementation of Arrow
metadata:
message root {
  OPTIONAL BYTE_ARRAY project_name (STRING);
  OPTIONAL BYTE_ARRAY project_version (STRING);
  OPTIONAL BYTE_ARRAY project_release (STRING);
  OPTIONAL INT64 uploaded_on (TIMESTAMP(MILLIS,false));
  OPTIONAL BYTE_ARRAY path (STRING);
  OPTIONAL INT64 size (INTEGER(64,false));
  OPTIONAL BYTE_ARRAY hash (STRING);
  OPTIONAL BYTE_ARRAY skip_reason (STRING);
  OPTIONAL INT64 lines (INTEGER(64,false));
}
```

### Expected behavior

It should not do this.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by ritchie46** [comment]
I think the `fetch` should be adapted for the streaming engine.

> It should not do this.

In any case, it should. The streaming engine will use an out-of-core sort when we are close to OOM. That means we spill to disk to be able to finish the sort.

**Comment by orf** [comment]
> In any case, it should. The streaming engine will use an out-of-core sort when we are close to OOM. That means we spill to disk to be able to finish the sort.

Oh, yeah so spilling to disk is fine. But the thing is that my machine has 96GB of memory, so something has gone pretty wrong if it is generating 400+GB of spill files + causing us to get close to OOM?

**Comment by ritchie46** [comment]
Can you run `collect(streaming=False)`?

**Comment by orf** [comment]
I can but it never terminates. I also managed to get polars to reliably segfault with some combination of things I was trying when using `streaming=False`, but it worked fine with `streaming=True`.

I was rushing to run get some data for a talk I’m giving this evening, but I promise I’ll follow up here with more info and a reproduction for this issue and the segfault.

**Comment by ritchie46** [comment]
> I can but it never terminates. 

Probably because you go out of memory?

**Comment by ritchie46** [comment]
Without a MWE, I can only guess we spill to disk because we otherwise go OOM and thus this is expected behavior.

**Comment by sebastienvercammen** [comment]
I just encountered the same symptom (disk filled) in `streaming=True` but without any sorting. I don't know if they are similar cases and share a common cause or if they're entirely different, so I'll leave that up to @ritchie46 to judge.

Either way, I can produce a mwe.

I expanded on my work [in this bug report](https://github.com/pola-rs/polars/issues/12735) - though this is a different bug. On top of this cartesian join, I've added another left join + a sum aggregate + a filter (remove rows with no value in sum) (for which I can take time to make a mwe if necessary).

The `explain(streaming=True)` plan is entirely within the streaming block. Running these operations with `streaming=True` causes polars to use the configured RAM limit (80% of total RAM) - and at some point it start writing to its temp folder until it exhausted my 350GB disk.

Let me know if this belongs in this report or in its own report, and whether you need me to write the additional code to go with the mwe in my other bug report.

**Comment by jmakov** [comment]
Same case here: https://github.com/pola-rs/polars/issues/13059
