### ISSUE TITLE
`is_last()`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9850]
### Problem description

To go with [`.is_first()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.is_first.html)

There does seem to be mention of `is_last` already in the codebase:

https://github.com/pola-rs/polars/blob/main/polars/src/lib.rs#L224

```rust
//!     - `is_last` - Check if element is last unique value.
```

https://github.com/pola-rs/polars/blob/main/polars/polars-core/src/chunked_array/ops/mod.rs#L757

But it doesn't seem to exist?

**Comment by cmdlineluser** [comment]
I guess it can be emulated by checking counts with `.over()`
```python
pl.Expr.is_last = lambda expr: (
   pl.int_range(0, pl.count()) ==
   pl.int_range(0, pl.count()).max()
).over(expr)

```

**Comment by ritchie46** [comment]
I believe we already have this? Did we not expose this?

**Comment by cmdlineluser** [comment]
Perhaps I'm being `.rank("dense")` - but there doesn't seem to be an implementation of it.

There's no `is_last.rs` in polars-ops

https://github.com/pola-rs/polars/blob/main/polars/polars-ops/src/series/ops/

(I'm guessing that's where it would be as that is where `is_first.rs` lives)

**Comment by mcrumiller** [comment]
@ritchie46 it's implemented in a few places but not in general.
