### ISSUE TITLE
consider adding repo-reviews badges to share UX with open-source community

### ISSUE THREAD

**Issue by repo-reviews** [pola-rs/polars#9858]
### Problem description

Hello!  UX can vary, so maybe consider adding badges to your README to solicit independent reviews:

<a href='https://github.com/repo-reviews/repo-reviews.github.io/blob/main/create.md' target="_blank"><img alt='Github' src='https://img.shields.io/badge/review_me-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>

- Add the `Review me` badge to your repo's **README.md** by copying the code below:

```
<a href='https://github.com/repo-reviews/repo-reviews.github.io/blob/main/create.md' target="_blank"><img alt='Github' src='https://img.shields.io/badge/review_me-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>
```

<a href='https://repo-reviews.github.io/repos/pola-rs/polars' target="_blank"><img alt='Github' src='https://img.shields.io/badge/view_reviews-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>

- Add the `View reviews` badge to your repo's **README.md** by copying the code below:

```
<a href='https://repo-reviews.github.io/repos/pola-rs/polars' target="_blank"><img alt='Github' src='https://img.shields.io/badge/view_reviews-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>
```

**Comment by stinodego** [comment]
Might do this at some point in the future, but for now I don't think it's worth adding a badge like this.
