### ISSUE TITLE
Support pint (unit of measure library)

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#9866]
### Problem description

It would be great to have support for [pint](https://github.com/hgrecco/pint) in polars.

Ideally this would avoid a direct dependency on pint but would involve opening the appropriate hooks needed to enable a package similar to [pint-pandas](https://github.com/hgrecco/pint-pandas).

Relates to:
https://github.com/hgrecco/pint/issues/1811

If you have a good idea for polars extension points and provide the necessary extension points, I perhaps could try to write `pint-polars`.

**Comment by stinodego** [comment]
We do not plan to implement this functionality directly in Polars.

You can implement an integration as a plugin. See the docs:
https://pola-rs.github.io/polars/user-guide/expressions/plugins/

More simple integrations could be done as a custom namespace. See the docs on extending the API:
https://pola-rs.github.io/polars/py-polars/html/reference/api.html
