### ISSUE TITLE
Custom PolarsPerformanceWarning when using `apply` / `GroupBy.apply`?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#9870]
### Problem description

Someone recently asked me why their polars groupby was so slow (taking ~6 minutes for something quite simple) - I had a look, and they were using `GroupBy.apply`. Rewriting it using a simple expression, it took ~5 seconds, which really surprised them.

The Expression API allows for practically anything, I've never had the need for `apply`.

The docs already mention the performance hit from `apply`, but people often don't read docs and just copy snippets they find on the web.

Thoughts on always emitting a custom `PolarsPerformanceWarning` in `apply` / `map`? Not sure it jumps out at people enough otherwise

**Comment by ritchie46** [comment]
> The docs already mention the performance hit from apply, but people often don't read docs and just copy snippets they find on the web.

I do know this, but this makes me so sad.

We could explore this. We must add a kwarg that can silence the warning then. There are places where we call `map` or `apply` internally.

**Comment by stinodego** [comment]
I recently used my first `apply` - there is some neat functionality in SciPy that we do not implement and isn't vectorized.

I'm not sure about emitting a warning. It would be great if we could detect functions that can easily be rewritten to expressions, and warn for those. But a blanket warning on core functionality does not seem ideal.

Warnings can also scare people off - they have to be handled, which isn't hard but you need to know how. And it adds some code bloat that I don't want in my production code.

**Comment by cmdlineluser** [comment]
It seems to stem from how `.apply` is used/needed in pandas.

There was a question the other day where the user had their expressions in a custom function and was using `.apply()` to call it.

It seemed like perhaps they assumed `.apply` was needed and wasn't aware the expressions could be used directly.

Perhaps it's a silly idea, but should `.apply` have a different name?

`.udf()` (user-defined-function) or `.custom_function()` - something that sort of self-documents that this is something you may not need?

**Comment by ritchie46** [comment]
> Warnings can also scare people off - they have to be handled, which isn't hard but you need to know how. And it adds some code bloat that I don't want in my production code.

Yes, I understand that sentiment. It is also a hard problem to do static analysis on the python functions.

**Comment by MarcoGorelli** [comment]
🤔 would renaming to `slow_apply` / `slow_map` be a possibility? This way it's really "in your face" but there's no warning silence

**Comment by ritchie46** [comment]
I would want to swap the order. First `map..` or `apply..`.

Then an extra word might nudge people to think indeed. `map_udf` or `map_slow`.

**Comment by stinodego** [comment]
`map_udf` and `apply_udf` seem best to me. If there's a `map_slow`, I'll be searching through the API docs to find `map_fast` :)

Though I am not 100% convinced yet we should go for this.

**Comment by MarcoGorelli** [comment]
This is being addressed by the bytecodeparsing stuff, so closing. thanks for the discussion!
