### ISSUE TITLE
Partial collection of results in a LazyFrame applied json.loads followed by unnest causes PanicException

### ISSUE THREAD

**Issue by RiceMunk** [pola-rs/polars#9871]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I have 2 examples, which highlight (in my opinion) different aspects of the bug:

First example:
```python
import polars as pl
import json
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(pl.col('foo').apply(json.loads)).unnest('foo')
```

Second example:
```python
import polars as pl
import json
pl.DataFrame({'foo':['{"bar": 0,"baz":1}']}).lazy().select(pl.col('foo').apply(json.loads)).unnest('foo').select(pl.col('bar')).collect()
```

The exception thrown in both cases is as follows:
```python
File /path/to/site-packages/polars/lazyframe/frame.py:2078, in LazyFrame.select(self, *exprs, **named_exprs)
   2073 else:
   2074     pyexprs = parse_as_list_of_expressions(
   2075         *exprs, **named_exprs, __structify=structify
   2076     )
-> 2078 return self._from_pyldf(self._ldf.select(pyexprs))

PanicException: internal error: entered unreachable code
```

### Issue description

In the mock examples above I am following a common data cleaning pattern of using Python's interal `json` library to parse a JSON string data column into a python dictionary, followed by unnesting the contents of the dictionary into separate columns (or in the first example, a single column) of an output dataframe.
This pattern of chaining `json.loads` with `unnest` produces output similar to the functionality of [`json_normalize` in Pandas](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html), which I am trying to replicate from my previous workflows.
I am also using polars' LazyFrame feature to avoid running the actual operations until I invoke `collect` on my desired final output.

The first example creates a 1-row dataframe where the column 'foo' contains a JSON string containing the dictionary `{"bar":0}`. This DataFrame is then turned into a LazyFrame through `lazy()`, after which `json.loads` is applied to the foo-column, followed by unnesting the un-JSONed python dictionary in it using `unnest('foo')`. The result is *not* `collect`ed.

The second example is similar, except the JSON string contains an additional field 'baz'. The same steps are applied to this, except in the end we select only the 'bar' column of the unnested results, and also apply `collect` to the results.

### Expected behavior

The expected output of the first example is a LazyFrame, which can e.g. have additional operations applied to it before collection. Were the output `collect`ed at this point, it would look as follows:
```
shape: (1, 1)
┌─────┐
│ bar │
│ --- │
│ i64 │
╞═════╡
│ 0   │
└─────┘
```
The second example is supposed to produce the same output as above, with the additional note that it is only part of the contents of the full LazyFrame.

Contrast the breaking examples with the following two examples which do *not* break, and produce their followed outputs:
```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(pl.col('foo').apply(json.loads)).unnest('foo').collect()
pl.DataFrame({'foo':['{"bar": 0,"baz":1}']}).lazy().select(pl.col('foo').apply(json.loads)).unnest('foo').collect()
```

In the first example, we `collect` the results of the breaking example. This outputs the collected result as a dataframe as expected.
The second example does not select only the `bar` column of the output but also includes `baz`, which was also inside the JSON string originally. The output is as expected:
```
shape: (1, 2)
┌─────┬─────┐
│ bar ┆ baz │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 0   ┆ 1   │
└─────┴─────┘
```

Another way to make the output not break is to not use LazyFrames. It appears that this exception is only thrown when operating on LazyFrames.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Linux-5.15.0-76-generic-x86_64-with-glibc2.10
Python:              3.8.2 (default, Mar 25 2020, 17:03:02) 
[GCC 7.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.5.1
numpy:               1.22.3
pandas:              1.4.2
pyarrow:             8.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by RiceMunk** [comment]
I am speculating, but it appears to me that this is a symptom of the lazy evaluation graph-building not understanding that multiple new columns are appearing from the combination of `json.loads` and `unnest`, and unless polars is forced to evaluate the full output of `json.loads`, it freaks out from trying to operate on output in one new column which also has a dependency on another new column.

Workaround is to always `collect` the full output of a `json.loads`+`collect` combo on a LazyFrame, though this may be impossible on very large datasets.

**Comment by cmdlineluser** [comment]
Not that it addresses the exception, but Polars has [`.json_extract()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.json_extract.html#polars.Expr.str.json_extract) for this.
```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
   pl.col('foo').str.json_extract()
).collect().unnest('foo')

# shape: (1, 1)
# ┌─────┐
# │ bar │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 0   │
# └─────┘

pl.DataFrame({'foo':['{"bar": 0,"baz":1}']}).lazy().select(
   pl.col('foo').str.json_extract()
).collect().unnest('foo')

# shape: (1, 2)
# ┌─────┬─────┐
# │ bar ┆ baz │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 0   ┆ 1   │
# └─────┴─────┘
```

**Comment by RiceMunk** [comment]
> Not that it addresses the exception, but Polars has [.json_extract()](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.json_extract.html#polars.Expr.str.json_extract) for this.

Ahh, good to know, thanks! Somehow I managed to miss that command while digging through the API. This will at least lest me get ahead with the analysis that made me run into this problem.

**Comment by cmdlineluser** [comment]
Perhaps it could be added to https://pola-rs.github.io/polars/py-polars/html/reference/io.html#json with an explicit mention of `json.loads` for better visibility.

**Comment by RiceMunk** [comment]
Actually this seems to happen with `json_extract` as well, if you do it before doing `collect` first:
```python
>>> pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
...    pl.col('foo').str.json_extract()
... ).unnest('foo')
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/runner/work/polars/polars/polars/polars-core/src/datatypes/dtype.rs:335:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/site-packages/polars/lazyframe/frame.py", line 674, in __repr__
    width = self.width
  File "/path/to/site-packages/polars/lazyframe/frame.py", line 640, in width
    return self._ldf.width()
pyo3_runtime.PanicException: internal error: entered unreachable code
```

Happens in the same ways as the `json.loads`+`unnest` combo as far as I can tell.

**Comment by ritchie46** [comment]
That's because we don't know the schema. Fix coming up and now we got a proper `SchemaError` hinting you to define the data type.

**Comment by RiceMunk** [comment]
Thanks! So how would one go about defining the data type in an example such as the one I have above?

**Comment by cmdlineluser** [comment]
Oddly, if you actually add the `.collect()` it doesn't raise:
```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
   pl.col('foo').str.json_extract()
).unnest('foo').collect()

# shape: (1, 1)
# ┌─────┐
# │ bar │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 0   │
# └─────┘
```
You can supply a schema like so:
```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
   pl.col('foo').str.json_extract(pl.Struct({"bar": pl.Int64}))
).unnest('foo')

# <LazyFrame [1 col, {"bar": Int64}] at 0x128864820>
```

**Comment by cmdlineluser** [comment]
Hmm, Is there some other issue at play here @ritchie46 ?

```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
   pl.col('foo').str.json_extract()
).unnest('foo')

SchemaError: expected struct dtype, got: `unknown`
```
Because it actually runs without error if you add the `.collect()`

```python
pl.DataFrame({'foo':['{"bar": 0}']}).lazy().select(
   pl.col('foo').str.json_extract()
).unnest('foo').collect()

# shape: (1, 1)
# ┌─────┐
# │ bar │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 0   │
# └─────┘
```

**Comment by ritchie46** [comment]
That's expected. The lazy API must know the schema at all time. If you extract json and you don't provide the `dtype` we set the `dtype` to `Unknown`. The `unnest` function then fail as it doesn't know what schema it should report during optimization. It can only know it, once the data is parsed.
