### ISSUE TITLE
Auto-sort column order when concat `vertical` and `vertical_relaxed`

### ISSUE THREAD

**Issue by stevenlis** [pola-rs/polars#9891]
### Problem description

As of `0.18.7`, Polars will return an error if columns' order does not align with one another when concat vertically.

```python
import polars as pl

df1 = pl.DataFrame({'a': [1, 2], 'b': [2, 1]})
df2 = pl.DataFrame({'b': [1, 2], 'a': [None, 1]})
```
```python
pl.concat([df1, df2], how='vertical')
# ShapeError: unable to vstack, column names don't match: "a" and "b"
```

```python
pl.concat([df1, df2], how='vertical_relaxed')
# ComputeError: schema names differ: got a, expected b
```

It would be great if polars could sort the columns itself.

**Comment by stevenlis** [comment]
It might be worth mentioning this requirement in the [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.concat.html) in the meantime.

**Comment by avimallu** [comment]
This might help you from previous discussions: https://github.com/pola-rs/polars/issues/7866#issuecomment-1489746598

**Comment by ritchie46** [comment]
> It would be great if polars could sort the columns itself. 

And a great source of silent bugs.

If you want them sorted, why not do it yourself?

```python
columns = df1.columns
pl.concat([df.select(columns) for df in [df1, df2]])
```

This has been asked before and this remains my answer, as this is super solvable as the snippet above shows.

**Comment by stinodego** [comment]
I will clarify this in the docs and then close these issues as not planned.

**Comment by magarick** [comment]
I'm happy to do this unless you have a reason not to want it. It's much more conducive to how  a lot of people work to have this as an option. I like the way data.table does it where everything is opt-in and the default is very strict. Having to do 3 operations (get the columns, sort the columns for each one, concat) is just a slight bit of cognitive burden that we don't need.

**Comment by ritchie46** [comment]
Opt-in sorting seems ok. What I am wary of, is cases where schema width differs. 

@magarick if you want to add opt-in sorting (or using the first df as guiding schema), can you add that logic on the rust side?

**Comment by magarick** [comment]
Yeah, happy to do it.
The way that `data.table` handles it, which I like, is that by default it matches on the names and it will yell at you if they aren't all equal. You can opt in to filling columns not present in all tables will nulls if you want, but that's off by default, as it should be. Here, I assume you're also being strict on column types, which maybe should also have an option to cast up.

But to be very clear, the default is that all names and types have to match. In that case I think sorting is fine by default, but I'm ok being extra strict and requiring a perfect match with no flags set.

**Comment by ritchie46** [comment]
> I assume you're also being strict on column types, which maybe should also have an option to cast up.

Yes, that's what strategy `vertical_relaxed`

@magarick hold your horses!

I realize we already have this. :see_no_evil: 

Strategy `diagonal` will solve this.

We could have a `diagonal_relaxed` as well. That one would then also upcast columns to their supertype.

**Comment by stinodego** [comment]
So we won't change the `vertical` and `vertical_relaxed` options, but an implementation for `diagonal_relaxed` is welcome.

**Comment by stevenlis** [comment]
It's getting a bit messy. If the doc allows, I hope we could put a chart like the following to help users to find their desired `how`

|         | Data Type Match | Column Order Match |
|---------------------|-----------------|--------------------|
|      vertical       |        Y        |         Y          |
|  vertical_relaxed   |        N        |         Y          |
|       diagonal      |        Y        |         N          |
| diagonal_relaxed    |        N        |         N          |

**Comment by stinodego** [comment]
Maybe we should have a separate boolean `relaxed` parameter?

**Comment by ritchie46** [comment]
> Maybe we should have a separate boolean `relaxed` parameter?

I don't like arguments influening each other. Especially if you have cases where the relaxed isn't supported.

Currently that is the case with diagonal. What id we get a new strategy for which relaxed isn't supported?

**Comment by ritchie46** [comment]
> It's getting a bit messy. If the doc allows, I hope we could put a chart like the following to help users to find their desired `how`
> 	Data Type Match 	Column Order Match
> vertical 	Y 	Y
> vertical_relaxed 	N 	Y
> diagonal 	Y 	N
> diagonal_relaxed 	N 	N

Not that diagonal allows for missing columns as well.

**Comment by stevenlis** [comment]
If I understand you correctly, maybe something like this?

|         | Data Type Match Requirement| Column Order Match Requirement| Join Type |
|---------------------|-----------------|--------------------|-----------|
|      vertical       |        Y        |         N          |   inner   |
|  vertical_relaxed   |        N        |         Y          |   inner   |
|       diagonal      |        N        |         Y          |   outer   |
| diagonal_relaxed    |        N        |         N          |   outer   |

**Comment by ritchie46** [comment]
"diagonal" does more than the schema order. It grows in a diagonal matter. New columns are added if they don't exist. So you grow horizontal and vertically -> diagonal.

I think that makes sense. :)

"relaxed" is mean to be the opposite of "strict". Open to a better name of that opposite.

**Comment by stevenlis** [comment]
@ritchie46 This `diagonal_relaxed` appears to be the only missing feature at the moment and occasionally confuses me. 😅

**Comment by alexander-beedie** [comment]
>  This `diagonal_relaxed` appears to be the only missing feature at the moment and occasionally confuses me. 😅

@stevenlis: "diagonal_relaxed" will be available as a first-class strategy option in the upcoming `0.19.8` ;)

**Comment by stevenlis** [comment]
@alexander-beedie Thanks! I hope you could also consider adding the table above to the document because it's becoming a bit complicated, or perhaps finding another way to differentiate them.
