### ISSUE TITLE
Kernel crashed when `align_frames`

### ISSUE THREAD

**Issue by Teamon9161** [pola-rs/polars#9910]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

def produce_df():
    return pl.DataFrame({'g': ['a', 'b', 'c'], 'v': np.random.randint(0, 3, 3)})

dfs = []
for i in range(500):
    dfs.append(produce_df())
out = pl.align_frames(*dfs, on='g', how='outer')
```

### Issue description

When I align more than 210 DataFrames, the IPython kernel crashes, but it works fine for 209 or fewer. However, the number of DataFrame that cause the python kernel to crash also varies across different IDEs.

### Expected behavior

See above

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Windows-10-10.0.22621-SP0
Python:      3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  0.3.1
deltalake:   0.9.0
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.1.2
```

</details>

**Comment by cjackal** [comment]
Can reproduce with 700 < N <= 800 on my machine with latest polars (==0.18.7). It segfaults pretty quickly unlike having a few seconds of runtime when it succeeded.

**Comment by ritchie46** [comment]
That's a stackoverflow. I will see if we can make s dynamic stack in that recursive optimization.

**Comment by cjackal** [comment]
For the moment, one can chop the list of frames into batches and run `align_frames` iteratively on that batches to avoid segfault. Of course it is slower than doing it as a whole though, but a safer option...

**Comment by ritchie46** [comment]
You can manually increase your stacksize btw.
