### ISSUE TITLE
Request: add real description of "semi-join"

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#9915]
### Problem description

At the top of the [semi join](https://pola-rs.github.io/polars-book/user-guide/transformations/joins/#cross-join:~:text=join%20strategies%20below.-,Semi%20join,-Consider%20the%20following) section, you could add a summary like:

> A semi-join filters the first dataframe to rows contained within the second dataframe, without adding any new columns.

**Comment by ritchie46** [comment]
Can you make a PR? For these trivial changes to the docs, we would prefer you to make a PR with the suggestions/improvements you like to see. That saves us a lot of work.
