### ISSUE TITLE
`scan_parquet` gives incorrect dataframe after `filter`

### ISSUE THREAD

**Issue by fachra** [pola-rs/polars#9925]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [1]: import pandas as pd
   ...: import polars as pl
   ...: 
   ...: # create a parquet file
   ...: df = pd.DataFrame({'code': [300964, 300972, 500000, 26]})
   ...: df.to_parquet('codes.parquet')
   ...: 
   ...: # WRONG
   ...: pl_lf = pl.scan_parquet('codes.parquet').filter((pl.col('code').floordiv(100000)).is_in([0, 3]))
   ...: print(pl_lf.collect())
shape: (0, 1)
┌──────┐
│ code │
│ ---  │
│ i64  │
╞══════╡
└──────┘

In [2]: # CORRECT
   ...: pl_df = pl.read_parquet('codes.parquet').filter((pl.col('code').floordiv(100000)).is_in([0, 3]))
   ...: print(pl_df)
shape: (3, 1)
┌────────┐
│ code   │
│ ---    │
│ i64    │
╞════════╡
│ 300964 │
│ 300972 │
│ 26     │
└────────┘
```

### Issue description

I would have expected the code
```python
pl_lf = pl.scan_parquet('codes.parquet').filter((pl.col('code').floordiv(100000)).is_in([0, 3]))
print(pl_lf.collect())
```
to print
```python
shape: (3, 1)
┌────────┐
│ code   │
│ ---    │
│ i64    │
╞════════╡
│ 300964 │
│ 300972 │
│ 26     │
└────────┘
```
not
```python
shape: (0, 1)
┌──────┐
│ code │
│ ---  │
│ i64  │
╞══════╡
└──────┘
```

### Expected behavior

```python
shape: (3, 1)
┌────────┐
│ code   │
│ ---    │
│ i64    │
╞════════╡
│ 300964 │
│ 300972 │
│ 26     │
└────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Thanks for the report. We very likely process a statistic wrongly. This should be fairly doable for someone with a little rust experience.

Anyone care to take a stab at this?

**Comment by cmdlineluser** [comment]
If it helps with debugging: it works with `streaming=True`
```python
(pl.scan_parquet('codes.parquet').filter((pl.col('code').floordiv(100000)).is_in([0, 3]))
   .collect(streaming=True))

# shape: (3, 1)
# ┌────────┐
# │ code   │
# │ ---    │
# │ i64    │
# ╞════════╡
# │ 300964 │
# │ 300972 │
# │ 26     │
# └────────┘
```

**Comment by ttdotsh** [comment]
> Thanks for the report. We very likely process a statistic wrongly. This should be fairly doable for someone with a little rust experience.
> 
> 
> 
> Anyone care to take a stab at this?

Hey there, I'm new here but would be happy to take a look.

**Comment by ttdotsh** [comment]
I tried reproducing the example shown in a test and the test passes without any changes to the code:

<img width="1510" alt="image" src="https://github.com/pola-rs/polars/assets/102175985/9dedbce4-ec51-4d18-9776-b94f64f58d1a">

**Comment by fachra** [comment]
Hi @ttdotsh , thanks for the help. Actually, there is a difference. I create and save the "codes.parquet" using Pandas' methods instead of Polars'.

**Comment by taozuoqiao** [comment]
It also works with `==`  (and other relational operators).
```
import pandas as pd
import polars as pl

# create a parquet file
df = pd.DataFrame({'code': [300964, 300972, 500000, 26]})
df.to_parquet('codes.parquet')
pl_lf = pl.scan_parquet("codes.parquet").filter(
    ((pl.col("code").floordiv(100000)) == 0) | ((pl.col("code").floordiv(100000)) == 3)
)
print(pl_lf.collect())

# shape: (3, 1)
# ┌────────┐
# │ code   │
# │ ---    │
# │ i64    │
# ╞════════╡
# │ 300964 │
# │ 300972 │
# │ 26     │
# └────────┘
```

**Comment by ttdotsh** [comment]
> Hi @ttdotsh , thanks for the help. Actually, there is a difference. I create and save the "codes.parquet" using Pandas' methods (with `engine`='pyarrow') instead of Polars'.

I changed the test config to write to a parquet file using pandas and was able to reproduce the issue, thanks for pointing that out.

The interesting thing I did find was that it appears to be isolated to the use of the `.is_in` method. I ran the test with several other filters that should all result in the same and the one that used `.is_in` is the only one that failed:

```python
        pl.scan_parquet(filepath).filter((pl.col("code").floordiv(100000)).is_in([0, 3]))              # fail
        pl.scan_parquet(filepath).filter((pl.col("code").floordiv(100000)).le(3))                          # pass
        pl.scan_parquet(filepath).filter(
            ((pl.col("code").floordiv(100000)) == 0) | ((pl.col("code").floordiv(100000)) == 3)   # pass
        )
        pl.scan_parquet(filepath).filter(
            ((pl.col("code").floordiv(100000)).eq(0)) | ((pl.col("code").floordiv(100000)).eq(3)) # pass
        )
        pl.scan_parquet(filepath).filter((pl.col("code").floordiv(100000)).ne(5))                         # pass

```

Interestingly, this one passed:

```python
expected_matches = [300964, 300972, 26]
pl_lf = pl.scan_parquet(filepath).filter((pl.col("code").is_in(expected_matches)))
```

**Comment by ttdotsh** [comment]
I've been spending some more time investigating and I am having a hard time pinning down where to look in the rust codebase. I have looked at:
* Checking into the collect method, tracing down what influence `streaming = true` has on the outcome
* Checking into how the `is_in` method evaluates, and checking to see if any of the FunctionOptions would have any influence
* Checking into how the filter method evaluates, and to see if the expected output from `is_in` is in any way inconsistent compared to the expected output of the other methods that have worked in testing like `.eq` or using the `==` operator
* Checking the `floor_div` method to see if its output is in anyway a mismatch (since `.is_in` worked just fine without using `.floordiv` in the tests)

If anyone else who is more familiar with the codebase has any ideas for where to look, I would be happy to try again.
