### ISSUE TITLE
Consider moving the `sink` methods to the I/O part of the Polars API guide

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#9928]
### Problem description

I noticed that the `sink_parquet` and `sink_ipc` methods are in the Miscellaneous part of the API guide instead of the I/O part.

Moving them to the Input/Output part of the guide might make them easier to find

![Screenshot 2023-07-17 153940](https://github.com/pola-rs/polars/assets/60814290/1bce912f-a958-4299-bac0-666aca5c9999)

**Comment by stinodego** [comment]
Agreed. We can do a better job in general structuring the docs. I'll give that some thought.
