### ISSUE TITLE
(Python) DataFrame constructor improvements

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#993]
I think the `DataFrame` constructor can be a lot more user friendly and consistent. Here how the constructor currently reacts to a bunch of different inputs (:heavy_check_mark:=works as expected, :x:=error, :large_orange_diamond:=works but has limitations)

:x: empty constructor
:heavy_check_mark: empty list
:heavy_check_mark: empty dict
:heavy_check_mark: dict of lists
:heavy_check_mark: dict of tuples
:large_orange_diamond: np.ndarray -> works but cannot specify columns
:x: np.ndarray with labeled columns
:x: list of lists
:heavy_check_mark: list of polars Series with unique names
:x: list of unnamed polars Series
:x: tuple of polars Series
:x: single polars Series
:heavy_check_mark: pandas DataFrame with named columns
:x: pandas DataFrame with unnamed columns
:large_orange_diamond: using `from_rows` on list of lists -> automatic column naming inconsistent with np.ndarray constructor; cannot specify `nullable`

_[See this notebook](https://github.com/stinodego/polars/blob/research/DataFrame_constructor.ipynb) for the actual error messages / results._

The way I see it, it shouldn't be difficult to support all these options with some proper control flow in the `__init__` of `DataFrame`. I'd suggest adding a `columns` keyword argument to help parsing stuff without column name info, and possibly a `dtype` argument, as it seems that there is no way to get around the automatic dtype inference of `polars` right now.

I do see a hurdle for the "list of unnamed polars Series", because the `name` attribute of the Series is set to an empty string instead of `None`. That makes it difficult to distinguish from the case with multiple identical names, which you do want to throw an error for. But that's a different subject.

If you agree with this direction, I'd be happy to implement this.

**Comment by ritchie46** [comment]
I totally agree on this one. I think that all paths you tested should be added to the tests and/ we probably can improve error messages as well.

In the csv-parser, in the case of no header, we create the columns ourselves: `column_0, column_1, ... column_n`. We could do something similar for unnamed values.

> I'd suggest adding a columns keyword argument to help parsing stuff without column name info, 

Agree, I think the behavior should be:

columns = None -> use the `Series` name attribute
columns = List[str] -> use the columns argument to overwrite the names.

> I do see a hurdle for the "list of unnamed polars Series", because the name attribute of the Series is set to an empty string instead of None. That makes it difficult to distinguish from the case with multiple identical names, which you do want to throw an error for. But that's a different subject.

IMO, it should throw an error, unless the columns kwarg is set.

**Comment by stinodego** [comment]
Cool, I'll do some work on this then.

> In the csv-parser, in the case of no header, we create the columns ourselves: `column_0, column_1, ... column_n`. We could do something similar for unnamed values.

If you give the constructor an np.ndarray right now, it names the columns `0`, `1`, `2`, etc. In other places like `from_rows` I've seen `column_0`, etc. like you mentioned. Which do you prefer? I find it more clear without the `column_` prefix; we know that they're columns, no need to specify that. It's also easier to iterately call the columns by name if they're just integers cast as strings.

> Agree, I think the behavior should be:
> 
> columns = None -> use the `Series` name attribute
> columns = List[str] -> use the columns argument to overwrite the names.

Yes, agreed!

> > I do see a hurdle for the "list of unnamed polars Series", because the name attribute of the Series is set to an empty string instead of None. That makes it difficult to distinguish from the case with multiple identical names, which you do want to throw an error for. But that's a different subject.
> 
> IMO, it should throw an error, unless the columns kwarg is set.

Why would a list of unnamed Series handle any differenly from a list of lists? It's just unnamed data. We should detect that they are unnamed and use the default column naming `0`, `1`, ... (or `column_0`, ...). For now I can do the check with `if not series.name`, that matches the empty string and in the future possible a `None`. Does that seem reasonable?

**Comment by ritchie46** [comment]
> I find it more clear without the column_ prefix; we know that they're columns

The `column_` prefix is already used in the csv-parser. So that would be more consistent. I don't really care about the actual naming, but the prefix would reduce some breakage and refactors.

> Why would a list of unnamed Series handle any differently from a list of lists? It's just unnamed data. We should detect that they are unnamed and use the default column naming 0, 1, ... (or column_0, ...). For now I can do the check with if not series.name, that matches the empty string and in the future possible a None. Does that seem reasonable?

Yes, you are right. I think its highly improbable that a user uses an empty string as column name. Ignore what I said. :)

**Comment by stinodego** [comment]
All right, we'll include the `column_` prefix!
