### ISSUE TITLE
set_sorted seems too often necessary

### ISSUE THREAD

**Issue by m-legrand** [pola-rs/polars#9931]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# 1. Inner joins
>>> df1 = pl.DataFrame({"x": [1, 2, 3], "y": [2, 4, 6]})
>>> df2 = pl.DataFrame({"x": [1, 2, 3], "z": [1, 4, 9]})
>>> df1.set_sorted("x").join(df2, on="x", how="inner")["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}
>>> df1.join(df2.set_sorted("x"), on="x", how="inner")["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}

# 2. Singleton dataframes
>>> pl.DataFrame({"x": [1]})["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}

# 3. Left of an asof join
>>> df1.join_asof(df2.set_sorted("x"), on="x")
InvalidOperationError: argument in operation 'asof_join' is not explicitly sorted
```

### Issue description

These days working with Polars I run very very often into the now dreaded

```
exceptions.InvalidOperationError: argument in operation 'asof_join' is not explicitly sorted
- If your data is ALREADY sorted, set the sorted flag with: '.set_sorted()'.
- If your data is NOT sorted, sort the 'expr/series/column' first.
```

I therefore end up adding `set_sorted` flags absolutely everywhere, and is actually tempted to implement an extension roughly being `df1.ext.unsafe_asof(df2, on=cols) = df1.set_sorted(cols) .join_asof(df2.set_sorted(cols), on=cols)`... which is obviously not ideal.

Digging into casesof my code where this is coming from I isolated some examples reproduced above, but I'm sure there are more where they come from.

I just want to stress this is not a critical bug (as it is more conservative than necessary rather than throwing wrong results).
However this is greatly impacting the ease and joy of using polars, and ultimately weighs into the decision of using it for a given task of data combination or not.

### Related issues:

- https://github.com/pola-rs/polars/issues/9757 (`partition_by`)

### Expected behavior

In case 1 I would expect to have a sorted result as the inner join should preserve the order.

In case 2 it would be convenient to have the dataframe already set to sorted whenever it contains only one column.
It happens to me a lot when constructing a dummy single-row dataframe to extract the "as-of value" of another, non-trivial dataset (cf. case 3).

In case 3 I genuinely don't understand why the left dataframe would need to be sorted.
The operation on its side is similar to a join and I often don't even want to sort it by the the time value!
Only the right dataframe (the one on which we're running the as-of logic) should be required to be sorted.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2021.11.1
matplotlib:          3.5.1
numpy:               1.21.5
pandas:              1.3.5
pyarrow:             6.0.1
pydantic:            1.8.2
sqlalchemy:          1.4.28
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by ritchie46** [comment]
I don't agree with the sentiment that asking for a set_sorted is worse than silently producing flawed results. 

However, I do agree that we must maintain those flags. So in the case of a `singleton`, yes we must set the sorted flag.

And in case of the inner join, IFF sortedness is maintained (I have to check) we must maintain the flags.

Case 3, I also have to investigate, I don't have it clear on top of mind.

**Comment by cmdlineluser** [comment]
> In case 3 I genuinely don't understand why the left dataframe would need to be sorted.

It's similar to a `.search_sorted()` operation i.e it only "works" on sorted data.

```python
s = pl.Series([5, 9, 2, 10, 8])

s.search_sorted(6, side='left')
# 3

# NOT OK - 2 and 10 are not the nearest values
s[2:4]

# shape: (2,)
# Series: '' [i64]
# [
# 	2
# 	10
# ]
```

If the data is sorted, the nearest values are either side of the insertion index.

```python
s = pl.Series([5, 9, 2, 10, 8]).sort()

s.search_sorted(6, side='left')
# 2

# OK - 5 and 8 are the nearest values
s[1:3]

# shape: (2,)
# Series: '' [i64]
# [
# 	5 # <- backward
# 	8 # <- forward
# ]
```

**Comment by ritchie46** [comment]
Yes, I can confirm case 3 just needs sorted data on both sides. So that is a correct Error.

**Comment by ritchie46** [comment]
Case 1:

An inner joins is not guaranteed to return in sorted order that why the flags represent that. This can change on the number of rows in your data. So the correct query in your case would be to sort the data after the inner join. 

So this is a correct Error and would have possible saved you from silently producing incorrect data  if your input size changed.

```python
df1 = pl.DataFrame({"x": [1, 2, 3, 4], "y": [2, 4, 6, 6]}).set_sorted("x")
df2 = pl.DataFrame({"x": [4, 2, 3, 1], "z": [1, 4, 9, 1]})

df1.join(df2, on="x", how="inner")["x"]
```

**Comment by ritchie46** [comment]
Case 2: #9933 adds sorted flags for singletons

I think we can close this now. As case 1 and case 3 are correct positives and case 2 is fixed now.

**Comment by m-legrand** [comment]
**Case 1**

Agreed that the behaviour in practice doesn't preserve order.
Your example @ritchie46 seems to infer that the order _of the second dataframe_ could be preserved, so just putting here a counter-example I found testing it, for curious minds:

```python
>>> df = pl.DataFrame({"x": [0, 2, 1, 0]})
>>> df.join(pl.DataFrame({"x": [1, 2, 3]}), on="x", how="inner")
shape: (2, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
│ 1   │
└─────┘
>>> df.join(pl.DataFrame({"x": [0, 1, 2, 3]}), on="x", how="inner")
shape: (4, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 0   │
│ 0   │
│ 1   │
│ 2   │
└─────┘
```

I still think the order of at least one of the dataframes could be preserved (ideally the left one, to be consistent with other cases), maybe adding a `maintain_order: bool` argument?
A naive implementation could look like this:

```python
def inner_join(df1, df2, on: str, *, maintain_order: bool = False):
    if maintain_order:
        df1 = df1.filter(pl.col(on).is_in(df2[on]))
        df2 = df2.filter(pl.col(on).is_in(df1[on]))
        return df1.join(df2, on=on, how="left")
    else:
        return df1.join(df2, on=on, how="inner")
```

**Case 3**

Yes it is similar to a `search_sorted` operation, but on the right dataframe, not the left.
Functionally an asof join is a `search_sorted` operation on the right dataframe, mapped to each row of the left dataframe.
The fact that the left dataframe has to be sorted makes sense after some thought from a performance POV though (as you don't have to search in the parts of right-dataframe you've already searched), but not because of the `search_sorted` semantic IMHO.
Maybe a mention in the docs of why each dataframe needs to be sorted would help users like me develop a better intuition and write code more naturally.
