### ISSUE TITLE
Docs on `polars.Expr.interpolate` doesn't mention `nearest`

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#9934]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

.

### Issue description

Polars.expr.interpolate mentions interpolation method "linear" twice, while it also supports "nearest".

https://github.com/pola-rs/polars/blob/1a4eaa5e4f025119cd495dcad83be862422c4150/py-polars/polars/expr/expr.py#L5020C12-L5020C12

### Expected behavior

Add nearest in docs.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ion-elgreco** [comment]
> Hi, may I know how you got to know that it can also accept "nearest"? I am looking for some first good issue.

I saw that the method was available in rust and it was mentioned in Series.interpolate(). I already created a PR to fix the issue.

**Comment by Teut2711** [comment]
Thanks for the insights.
