### ISSUE TITLE
Implement a `sort` that is stable with regards to null values

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9940]
### Problem description

See discussion #9916

We currently have a `maintain_order` option for sorts, but it does not respect the order of null values.
It would be nice to have this option.

Example:

```python
import polars as pl

lf = pl.LazyFrame({"a": [None, None, 1, 1, 2], "b": [2, 1, 3, 4, 5]})

print(lf.sort("a", maintain_order=True).collect())
```

We want to be able to guarantee that rows containing null values are in the same order as they were in the original dataframe:
```
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ null ┆ 2   │
│ null ┆ 1   │
│ 1    ┆ 3   │
│ 1    ┆ 4   │
│ 2    ┆ 5   │
└──────┴─────┘
```

Although this is not a good example (too small to trigger the randomness I think?), this is not guaranteed for bigger data, as shown in the linked example.

Current workaround is to add a row index and sort on that.

**Comment by orlp** [comment]
What do we mean by 'respect the order of null values'? Could we add an example of what we'd want?

E.g. do we want to group all the null values at the start/end of the dataframe with the rows in the relative order they were in in the original dataframe?

**Comment by orlp** [comment]
So essentially a [stable sort](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability) where nulls compare to be less than any other value.

**Comment by dmitrybugakov** [comment]
Hello @stinodego 

I've been attempting to recreate an issue related to stable sorting based on the instructions in my Gist (https://gist.github.com/dmitrybugakov/1e29bda05f5a8d96599676c62fc67ead), 
but everything appears to be functioning correctly. 

Could it be that the issue no longer exists, or is there a possibility that I'm missing something in my approach?

**Comment by stinodego** [comment]
I'll close this then, if someone can show the instability we can reopen this.

**Comment by wence-** [comment]
This issue is still observable if sorting with `descending=True`:
```
import polars as pl

lf = pl.LazyFrame({"a": [None, None, 1, 1, 2], "b": [2, 1, 3, 4, 5]})

print(lf.sort("a", descending=True, maintain_order=True).collect())
shape: (5, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ null ┆ 1   │
│ null ┆ 2   │
│ 2    ┆ 5   │
│ 1    ┆ 3   │
│ 1    ┆ 4   │
└──────┴─────┘
```
