### ISSUE TITLE
Can't stop process on StorageFull with streaming engine

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#9945]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

n/a

### Issue description

If you use `streaming=True` and run out of disk space, you get

```
ArrowError(Io(Os { code : 28, kind: StorageFull, message: "No space left on device" }))
```

which is fine in itself but then you can't use ^C to cancel the Polars process.

### Expected behavior

^C should work.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by jonashaag** [comment]
Does it make sense to attempt a clean Polars shutdown (without using ^C) in case of out of disk?

**Comment by ritchie46** [comment]
Doesn't the error do that already? If polars returns an error it isn't doing anything anymore. Or do you mean a complete polars abort of the process? I don't know, that seems a decision left to the caller.

**Comment by jonashaag** [comment]
Hm the thing is that control isn't given back to the Python interpreter because then ^C would raise KeyboardInterrupt?

**Comment by ritchie46** [comment]
It might be that things are now horrendously slow as your hard drive is full. I am not sure, but I can imagine that this slows down other processes as well.

**Comment by jonashaag** [comment]
Good point, will investigate some more!
