### ISSUE TITLE
Dataframe flags are not preserved by pickling/unpickling

### ISSUE THREAD

**Issue by m-legrand** [pola-rs/polars#9956]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import pickle
>>> df1 = pl.DataFrame({"x": [1, 2, 3]}).set_sorted("x"); df1["x"].flags
{'SORTED_ASC': True, 'SORTED_DESC': False}
>>> df2 = pickle.loads(pickle.dumps(df1)); df2["x"].flags
{'SORTED_ASC': False, 'SORTED_DESC': False}
```

### Issue description

When running long-running computations such as data retrieval, I sometimes use caching strategies such as `functools.lru_cache` or `diskcache.Cache` to cache the results with minimum efforts.
Oftentimes these tools use `pickle` for serializing/deserializing, but it seems like this doesn't preserve the flags, and in particular the "SORTED_*" ones.
A typical use case would be something like:

```python
import diskcache

cache = diskcache.Cache(mycachedir)

@cache.memoize(expire=3600)
def get_latest_data(id: str) -> pl.DataFrame:
    # do a very slow thing
    return df.set_sorted("time")

def get_analyzed_data(id: str) -> pl.DataFrame:
    data = get_latest_data(id: str)
    # do something using the sorted property of data
    # ERROR
```

I traced this issue back to the pickling/unpickling behaviour I displayed above, but I'm not sure _why_ that happens.
If that's an easy fix that would certainly make my life much easier.
Otherwise I'm guessing I could try and come up with my own parquet-based on-disk caching utility, but that would be a big overhead compared to the example above.
I could also keep doing that I'm doing, always rerunning `.sort("x")` whenever it is needed, but that's making the code very verbose and potentially slower than usual (I do a _lot_ of asof joins!).

### Expected behavior

```python
assert df2["x"].flags == {'SORTED_ASC': False, 'SORTED_DESC': False}
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.19
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by universalmind303** [comment]
It should be pretty straightforward to add the settings flags to the serde implementations for the chunked_arrays. `polars/polars-core/src/serde/chunked_array.rs`

**Comment by ritchie46** [comment]
Yes, it is. We should add the flags to the serde struct we serialize.
