### ISSUE TITLE
Add `.cast` as DataFrame method

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#9959]
### Problem description

It would be useful to add .cast as a method on the dataframe class which takes a dictionary as input with full or partial schema and their polars dtypes. 

Example:

```python
schema = {"foo": pl.Uint64, "bar": pl.List}

df = df.cast(schema)

```

**Comment by ion-elgreco** [comment]
> The implementation for this would be simple:
> 
> ```python
> df = df.with_columns(pl.col(c).cast(dtype) for c, dtype in schema.items())
> ```
> 
> I'm not 100% convinced yet it's worth adding this as a DataFrame method.

It's rather some syntactic sugar and makes it slightly more readable. 

PyArrow also has the ability to do this on table level: https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.cast

**Comment by mcrumiller** [comment]
We already have this for `pl.struct` which works much the same way:

```python
import polars as pl

df = pl.DataFrame({
    'a': pl.Series([1, 2, 3], dtype=pl.Int32),
    'b': pl.Series([1.0, 2.0, 3.0], dtype=pl.Float64)
}).select(
    pl.struct(schema={'a': pl.UInt8, 'b': pl.UInt16})
)
print(df['a'])
print(df['a'].dtype)
```
```
Series: 'a' [struct[2]]
[
        {1,1}
        {2,2}
        {3,3}
]
Struct([Field('a', UInt8), Field('b', UInt16)])
```

I like the idea of being able to apply a new schema onto an existing DataFrame, and I can see a lot of reasons where it could be useful: namely, where multiple processes are supplying you the same data, but may not know the intended schema. For example, you might get `UInt64` from some places and `Int32` from others, or `pl.Datetime` and `pl.Date`, etc. Having a simple `df.cast(schema)` using a predefined schema would make this code very clean.

Alternatively we could have a `df.apply_schema` or some such, but I think `cast` is obvious enough.

**Comment by mkleinbort-ic** [comment]
I have that implementation myself, I call it `astype` because that's the name I'm used to:

```python
df.astype({'date':pl.Date(), 'userId':pl.Int64()})
```

This is very useful when converting back and forth from pandas to polars, where the data type specifics can get lost.

```python
    # My implementation is a bit messy because it handles dates and datetimes to some extent

    def _astype(df:pl.DataFrame, dtype_dict:dict[str,pl.DataType])->pl.DataFrame:      
    
        current_types = df.select(pl.col(list(dtype_dict.keys()))).schema
        
        type_tuples = {k: (current_types[k], dtype_dict[k]) for k in dtype_dict.keys()}
        
        conversion_dict = {col: pl.col(col).cast(dtype) 
                        
                                if (dtype not in [pl.Date, pl.Datetime] or (cdtype != pl.Utf8())) else 
                        
                                pl.col(col).str.strptime(dtype)     
                                            
                        for col, (cdtype, dtype) in type_tuples.items()}
        
        return df.with_columns(**conversion_dict)
```

**Comment by stinodego** [comment]
Right, I think this makes sense. Could exist on both `DataFrame` and `LazyFrame`. I like the name `cast` for this.

I guess we would accept as input a dictionary of `name -> dtype`, and partial schemas would also be accepted.

Sample test:

```
from datetime import date, datetime

import polars as pl
from polars.testing import assert_frame_equal


def test_df_cast() -> None:
    df = pl.DataFrame(
        {"a": [1, 2], "b": [3.0, 4.0], "c": [date(2022, 1, 1), date(2022, 1, 2)]}
    )
    schema = {"a": pl.Int8, "c": pl.Datetime}

    result = df.cast(schema)

    expected = pl.DataFrame(
        {
            "a": [1, 2],
            "b": [3.0, 4.0],
            "c": [datetime(2022, 1, 1), datetime(2022, 1, 2)],
        },
        schema_overrides=schema,
    )
    assert_frame_equal(result, expected)
```

**Comment by mkleinbort-ic** [comment]
I like this, though note that support for pl.UTF8 -> Date/Datetime would be a very good to have - a lot of APIs return dates as strings.

```python
def test_df_cast() -> None:
    df = pl.DataFrame({
          "a": [1, 2], 
          "b": [3.0, 4.0], 
          "c": [date(2022, 1, 1), date(2022, 1, 2)], 
          "d": ['2022-01-01', '2022-01-02']
        })

    schema = {"a": pl.Int8, "c": pl.Datetime, "d": pl.Date}

    result = df.cast(schema)

    expected = pl.DataFrame(
        {
            "a": [1, 2],
            "b": [3.0, 4.0],
            "c": [datetime(2022, 1, 1), datetime(2022, 1, 2)],
            "d": [pl.date(2022, 1, 1), pl.date(2022, 1, 2)],
        },
        schema_overrides=schema,
    )
    assert_frame_equal(result, expected)
```

**Comment by stinodego** [comment]
`DataFrame.cast` should not do anything that `Expr.cast` does not also do. We can consider expanding `Expr.cast` to be able to cast strings to dates, but that's a different topic altogether.

**Comment by mkleinbort-ic** [comment]
That makes sense to me.

**Comment by mcrumiller** [comment]
The strings to dates has been discussed a lot. I think @ritchie46 is pretty strongly against it. I think supporting ISO8601 strings as dates would make using dates in polars way easier.

**Comment by alexander-beedie** [comment]
> I like this, though note that support for pl.UTF8 -> Date/Datetime would be a very good to have - a lot of APIs return dates as strings.

The problem there is there is no one string format to cast from - it's not really a cast, it's a parse/translation (eg: `strptime`) ;)

**Comment by zundertj** [comment]
Given some of the use cases of this, like casting to a schema you already know, could we also add the ability to pass in a dataframe, i.e.

```python
df1.cast(df2)
```
as short-hand for 

```python
df1.cast(df2.schema)
```
?

I guess the only question is what you do if the column names dont match, but if we are flexible on doing a "partial cast" with passing a schema as a dict, it could be argued the same should apply for a dataframe input? That is, keep the same columns as the original, but only cast dtypes.

**Comment by mcrumiller** [comment]
> could we also add the ability to pass in a dataframe

@zundertj that's a good idea. I would recommend using the `like` keyword, as this is often used in other libraries when you want one thing to look like another.

```python
df1.cast(like=df2)
```

**Comment by stinodego** [comment]
I don't like that at all. Just be explicit and pass the schema.

`df1.cast(like=df2)` isn't any shorter or more readable than `df1.cast(df2.schema)`.

Let's not make things more complicated than they need to be.

**Comment by zundertj** [comment]
I agree on the `like` keyword, but passing in the dataframe directly is not any less explicit as there cannot be any confusion what the schema is or what it would set to be, as we use the same semantics as passing in as a dict? I agree that it adds "another way", but imo worth the tiny complication. 

There have been many issues here on the tracker for people requesting to cast data types automatically (joins, concat, etc), and I agree we should keep things explicit and not auto cast data types. But I don't see how `df1.cast(df2)` is considered any less explicit than `df1.cast(df2.schema)`.

**Comment by itsakettle** [comment]
Hi there, could I have a go at this one?

**Comment by stinodego** [comment]
Sure, looking forward to the PR!

**Comment by itsakettle** [comment]
Hi again. First contribution for me, so I've been going through the relevant code bit by bit and making good progress I think. 

In terms of this change I'm wondering is

`def cast(self, new_dtypes: dict[str, pl.DataType]) -> DataFrame`

more descriptive than

`def cast(self, schema: dict[str, pl.DataType]) -> DataFrame`

If `schema` is the argument name it might give the impression that we are applying a new schema to the df which, for example, could look something like this: 

```
>>> df = pl.DataFrame(
        ...     {
        ...         "apple": [1, 2, 3],
        ...         "banana": [6, 7, 8],
        ...         "orange": ["a", "b", "c"],
        ...     }
        ... )
>>> df
shape: (3, 3)

│ apple ┆ banana ┆ orange │
│ i64   ┆ i64    ┆ str    │
│ ---   ┆ ---    ┆ ---    │
│ 1     ┆ 6      ┆ a      │
│ 2     ┆ 7      ┆ b      │
│ 3     ┆ 8      ┆ c      │

>>> schema = {"banana": pl.String, "pear": pl.String}
>>> df.cast(schema)
shape: (3, 3)

│ banana┆ pear   │
│ str   ┆ str    │
│ ---   ┆ ---    │
│ 6     ┆ null   │
│ 7     ┆ null   │
│ 8     ┆ null   │

```

But this isn't what we're proposing that df.cast will do. It will look more like this (per tests above):

```
>>> new_dtypes = {"banana": pl.String, "pear": pl.String}
>>> df.cast(new_dtypes)
shape: (3, 3)

│ apple ┆ banana ┆ orange │
│ i64   ┆ str    ┆ str    │
│ ---   ┆ ---    ┆ ---    │
│ 1     ┆ 6      ┆ a      │
│ 2     ┆ 7      ┆ b      │
│ 3     ┆ 8      ┆ c      │
```


So here are my questions:
* Does using `def cast(self, new_dtypes: dict[str, pl.DataType]) -> DataFrame` as the signature sound ok?
* If there are columns that don't exist in `new_dtypes` do you think df.cast should error or just ignore them? (`pear` in the second example above is ignored)
* If multiple columns in `new_dtypes` cause `expr.cast` to throw errors is it preferred to present these all to the user in one go so they can fix them in one go? Or should we do the easier thing and show them the first error, let them fix it, then show them the second and so on?

Hope that makes sense, thanks!

**Comment by alexander-beedie** [comment]
> The pandas .astype method uses the parameter dtype and so does the polars pl.Expr.cast method

I'd make a slight amendment here; the `Expr` version can only cast from _one_ type to another - this function will potentially cast to/from `n`, so I'd advocate keeping the parameter name both familiar (similar to the expression-level `cast`) but _also_ accurate by pluralising it as `dtypes`. (Looks pretty odd to declare a singular dtype as a dict contains _lots_ of dtypes). Can make a good case for either that or `schema`; I'm somewhat neutral as to which ;)

**Comment by mkleinbort-ic** [comment]
@alexander-beedie - in your view should "convert all to a given type" inputs be supported:

Eg.
```python
df = pl.DataFrame({'x1': [1], 'x2':[2.0], 'x3':['3']})
df.cast(pl.Float64) # Equivalent to df.select(pl.all().cast(pl.Float65))
```

**Comment by mcrumiller** [comment]
@mkleinbort-ic I think yes, but continuing to use the parameter name `dtypes` works. The dtypes of all the columns will be "`pl.Float65`", whatever that is. I'd recommend using `pl.Float64` instead though :)

**Comment by mkleinbort-ic** [comment]
pl.Float66 removes the Jedi overhead

**Comment by alexander-beedie** [comment]
> @mkleinbort-ic I think yes, but continuing to use the parameter name `dtypes` works. The dtypes of all the columns will be "`pl.Float65`", whatever that is. I'd recommend using `pl.Float64` instead though :)

Float65 [goes to 11](https://www.youtube.com/watch?v=hW008FcKr3Q) - what if you need that little extra?  ;)

(But more seriously, yes, the param name `dtypes` still works in this case; I also think that's a convenience shortcut worth supporting).

**Comment by alexander-beedie** [comment]
Landing a PR tomorrow - just finished the implementation (including `selector` support), but still need to write some tests and it's late here now. Will finish up tomorrow morning.

**Examples**:
* `df.cast( {"foo": pl.Float32, "bar": pl.UInt8} )`
* `df.cast( {cs.numeric(): pl.UInt32}) `
* `df.cast( dtypes=pl.Utf8 )`

**Comment by itsakettle** [comment]
Ah I was too slow. I'll be quicker next time!

**Comment by alexander-beedie** [comment]
> Ah I was too slow. I'll be quicker next time! Away with family and had less time than I thought.

Apologies! I joined in the discussion a bit late and somehow completely missed your offering to work on this one...😅

**Comment by itsakettle** [comment]
No worries, I'm in it for the learning and looking at your PR will give me lots of that.

**Comment by alexander-beedie** [comment]
> No worries, I'm in it for the learning and looking at your PR will give me lots of that.

Apparently I learned a few things too while refining it, haha... :))
