### ISSUE TITLE
Provide an interface for R language

### ISSUE THREAD

**Issue by XianglinZhang-risker** [pola-rs/polars#996]
Hello, have you considered providing an interface for R language? R language has packages to call Rust. I don’t know the difficulty level. If you want, I hope we can work together or find someone who is very good at R language to complete this task. This must be a great job, and I have observed that it is faster than data.table. Thanks.

**Comment by jonekeat** [comment]
@andy-thomason & @jeroen might able to leave some suggestions

**Comment by xianglinZ** [comment]
> 
> 
> @andy-thomason & @jeroen might able to leave some suggestions

**Comment by xianglinZ** [comment]
> 
> 
> @andy-thomason & @jeroen might able to leave some suggestions

**Comment by xianglinZ** [comment]
Sorry, I clicked close by mistake.

Of course, they are all outstanding contributors to the R language, and extendr provides a good way to call Rust for R. It would be great if they were willing to join.

**Comment by andy-thomason** [comment]
This looks like an interesting project. I made a fairly large contribution to Arrow a couple of years ago as we were using it for bioinformatics data at work.

It should be fairly easy to generate bindings using **extendr** and you would be welcome to raise an issue and get some help from the team.

I'll try to look over your project in the next few days.

**Comment by ChristopherEeles** [comment]
Has any progress on this topic been made? I am a full-time R developer with an interest in high-performance data frame libraries as well as an inkling to learn Rust. 

If someone has already started an R project, I would love to contribute.

**Comment by xianglinZ** [comment]
Because of my lack of programming skills and busy work, I did not start this project.

**Comment by andy-thomason** [comment]
We (the extendr team) would be happy to help to interface anything to R.

https://github.com/extendr/extendr

**Comment by lmeninato** [comment]
Happy to help with this as well. I have _some_ but not a lot of Rust experience. I have a fair amount of R programming background. One project to look for inspiration from would be: [https://dtplyr.tidyverse.org](https://dtplyr.tidyverse.org) since it would be cool to be able to keep as much of the dplyr syntax with a faster polars backend (eventually).

**Comment by grantmcdermott** [comment]
For those who don’t want to follow the daisy chain of links, just to point out that an R implementation of polars is already quite far under way thanks to @sorhawell: https://github.com/sorhawell/minipolars/

**Comment by sorhawell** [comment]
Hi all!
I have moved and renamed minipolars to here:
### [https://github.com/rpolars/rpolars](https://github.com/rpolars/rpolars)

Though quite far, I have to postpone target deadline to March '23. If any want to contribute I could really need some help: 
 - You can easily contribute also as a rust beginner as maybe half of implementations are simple pass-troughs of the rust-polars API, see contribution example [here](https://github.com/rpolars/rpolars/blob/main/README.md#contribute)
 - Anybody are also welcome to just try it out and post their opinion on the rpolars-issue track or send me an email. It takes ~15 seconds to install R-package from weekly released binaries see [rpolars readme](https://github.com/rpolars/rpolars#install-latest-rpolars-release). [Latest documentation](https://rpolars.github.io/reference/index.html) shows what have been translated so far.

A great thanks to the pola-rs organization for making all this possible!

**Comment by CGMossa** [comment]
New location of this project is here: https://github.com/pola-rs/r-polars

**Comment by grantmcdermott** [comment]
Given that development of **r-polars** has been officially ported to https://github.com/pola-rs org, I think this issue can be closed now.

**Comment by ritchie46** [comment]
Jep. :)
