### ISSUE TITLE
Horizontal Mean for Lazy or Expr 

### ISSUE THREAD

**Issue by baron-digit** [pola-rs/polars#9963]
### Problem description

So far only the DataFrame implementation of column-wise mean is implemented.
As requested by Ritchie, putting the request for the Expr API for row-wise mean here.

Thanks for your support and the great work.

**Comment by ritchie46** [comment]
We already have this implemented as `DataFrame::hmean`, so we just need to expose a horizontal expression.

**Comment by deanm0000** [comment]
Is this going to be the same performance or better than doing?

```
df.select(pl.concat_list('a','b').list.mean())
``

**Comment by ritchie46** [comment]
Probablr better, it will not reallocate into a list, but will compute the intermediate states columnar.

**Comment by stinodego** [comment]
Duplicate of #9966

Closing in favor of #9966 as it is more complete.
