### ISSUE TITLE
Consider `Option<String>` for Series::name

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#997]
This would allow use replacing `None` with a column name in `DataFrame` creation. Currently, an empty string is often used, but we are not allowed to replace that empty string as it could be user provided and then we must throw an error because of duplicate names. An `Option<String>` would provide more information to us.

Following #995

**Comment by ritchie46** [comment]
@stinodego following your proposal at #995. I do think that this would be a good API improvement. I will refactor to make this happen.

**Comment by stinodego** [comment]
Great! I could take care of the Python side if you wish, once you're done with the Rust implementation.

**Comment by matteosantama** [comment]
Is there still interest in this? Happy to take a crack at it

**Comment by ritchie46** [comment]
No, I have been thinking about this and polars expressions/series always must be named. This premise is also everywhere in the code base and is not worth the giant refactor IMO.

I think we can close this one.
