### ISSUE TITLE
Add agg DataFrame method like pandas

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#9977]
### Problem description

Inspired by [this SO](https://stackoverflow.com/questions/76720815/apply-operations-from-string-list-to-one-or-more-columns-in-polars) question, it seems that `agg` would be pretty helpful and isn't too bad to code up so I wrote this, I don't know if people want to use it as is, improve it and put it in the official python release or implement it in rust or none of the above but here it is:

```
def agg(df, func: str | list | dict) -> pl.DataFrame:
    """Function to replicate pandas agg function, will take either a single string,
         a list of strings, or a dict mapping columns to functions"""
    if isinstance(func, str):
        func=[func]
    if isinstance(func, list):
        return (
            df
                .select(getattr(pl.all(), fun)().suffix(f"_{fun}") for fun in func)
        )
    elif isinstance(func, dict):
        return (
            df
            .select(getattr(pl.col(col), fun)().suffix(f"_{fun}")
                    for col,funL in func.items()
                    for fun in funL)
        )
pl.DataFrame.agg=agg
```

With this you can do

```
df=pl.DataFrame({'a':[1,2,3,4], 'b':[3,4,5,6]})
df.agg(['min','max','mean'])
shape: (1, 6)
┌───────┬───────┬───────┬───────┬────────┬────────┐
│ a_min ┆ b_min ┆ a_max ┆ b_max ┆ a_mean ┆ b_mean │
│ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---    │
│ i64   ┆ i64   ┆ i64   ┆ i64   ┆ f64    ┆ f64    │
╞═══════╪═══════╪═══════╪═══════╪════════╪════════╡
│ 1     ┆ 3     ┆ 4     ┆ 6     ┆ 2.5    ┆ 4.5    │
└───────┴───────┴───────┴───────┴────────┴────────┘
df.agg({'a' : ['sum', 'min'], 'b' : ['min', 'max']})
shape: (1, 4)
┌───────┬───────┬───────┬───────┐
│ a_sum ┆ a_min ┆ b_min ┆ b_max │
│ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64   ┆ i64   ┆ i64   ┆ i64   │
╞═══════╪═══════╪═══════╪═══════╡
│ 10    ┆ 1     ┆ 3     ┆ 6     │
└───────┴───────┴───────┴───────┘

**Comment by mcrumiller** [comment]
If this were implemented, I think a `df.stats(...)` would be a better name.

**Comment by ritchie46** [comment]
But do we really need it?:

```python
df = pl.DataFrame({
    "a": [1, 2],
    "b": [3, 2],
})

df.select([
    eval(f"pl.all().{agg}().suffix('_{agg}')") for agg in ["min", "max", "var"]
])
```

**Comment by deanm0000** [comment]
I don't know if we need it _per se_ but it is a thing that pandas users are used to having and it's not the first time a question pertaining to that functionality has come up on SO.

**Comment by ritchie46** [comment]
Yes, I understand, but I'd like to keep the number of ways to do things close to 1.

I also really don't like passing strings as a way to do aggregation. We even removed that functionality from `groupby.agg`.

What I'd rather do is find a way to make meta-programming a first class citizen in polars. E.g. using python + something provided by us to cleanly avoid repition and construct expressions.

**Comment by deanm0000** [comment]
¯\_(ツ)_/¯

**Comment by avimallu** [comment]
@ritchie46, is it safe to use eval though? It's almost always condemned as bad practice, and the get attribute method isn't intuitive.

I'm not a fan of the idea of an agg method accepting strings, but is there no easy way to send multiple calculations as we can expressions? Kind of like a _calculation expansion_?

**Comment by ritchie46** [comment]
It is safe in this case. You construct the snippet yourself. It is unsafe if you run user/external provided strings in eval.
