### ISSUE TITLE
Add option `infer_width` to cast List to Arrays

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#9978]
### Problem description

I occasionally cast back and forward between List and Array dtypes. This is slightly cumbersome because I have to know the width of my List for it to be properly casted to an Array, however it's the same across the Series but I need to manually fetch that information first before casting. If the width you pass is incorrect it will return an Exception: 

`ArrowErrorException: InvalidArgumentError("incompatible offsets in source list")`

Could be more practical for the user to automatically infer the width of the Array. If it's not consistent it should throw the same ArrowErrorException.

```python
s = pl.Series(
    "foo", [[1, 2], [4, 3]], dtype=pl.List(inner=pl.Int64)
)
s = s.cast(pl.Array(inner=pl.Int64, infer_width=True))

print(s)

```
```python
shape: (2,)
Series: 'a' [array[i64, 2]]
[
	[1, 2]
	[4, 3]
]
```

**Comment by stinodego** [comment]
I don't think this is possible as part of the `Array` data type definition. But we could add a `.to_array` method to the `list` namespace that automatically sets it to the right length.

**Comment by ion-elgreco** [comment]
> I don't think this is possible as part of the `Array` data type definition. But we could add a `.to_array` method to the `list` namespace that automatically sets it to the right length.

If it is possible in Array dtype, then we could also add the casting from Array to List in df.cast() once that is implemented. But if that's not feasible then `.to_array' will also work.

**Comment by stinodego** [comment]
The logic could be in the `cast` definition. Just not in the datatype class itself.

**Comment by ritchie46** [comment]
> The logic could be in the cast definition. Just not in the datatype class itself.

Yes, but not in the "generic" cast, but a dedicated `to_array` method. As width inference needs a pass over (parts of) the data, it does more than casting.

**Comment by stinodego** [comment]
Right, so after adding the expression I realized that we cannot actually do this in the optimizer. We need to determine the output schema given the input schema, and we cannot determine the width from just the List dtype. We'd have to scan the data, which isn't allowed.

What you COULD do as a workaround is collect first, determine the desired dtype, then `cast` (or use `to_array` if it's added https://github.com/pola-rs/polars/pull/12192).

```python
import polars as pl

# Lazy state
lf = pl.LazyFrame({"a": [[1, 2], [3, 4]], "b": [[1], [2]]})

# Collect and determine Array dtypes
df = lf.collect()
lengths = df.select(pl.col("a", "b").first().list.len()).row(0, named=True)
dtypes = {c: pl.Array(inner=df.schema[c].inner, width=w) for c, w in lengths.items()}

# Cast
df = df.with_columns(pl.col(c).cast(dt) for c, dt in dtypes.items())

# Continue in lazy
lf = df.lazy()
```

**Comment by stinodego** [comment]
There's no reason we couldn't infer the shape during DataFrame construction. I was talking purely about the lazy API.
