### ISSUE TITLE
suffix ignores alias

### ISSUE THREAD

**Issue by markxwang** [pola-rs/polars#9992]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 2]})


df.select(pl.col("a").alias("b").suffix("_c")).columns
```
output
```
['a_c']
```

### Issue description

suffix ignores ignores `alias`

### Expected behavior

Expect

```
["b_c"]
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            macOS-13.3.1-arm64-arm-64bit
Python:              3.10.5 (main, Sep  6 2022, 09:52:19) [Clang 13.1.6 (clang-1316.0.21.2.5)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          2.0.19
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by stinodego** [comment]
This is not a bug, though I agree it may be unexpected behaviour. The docs on this have just been updated to reflect this.

See:
https://pola-rs.github.io/polars/py-polars/dev/reference/expressions/api/polars.Expr.suffix.html

> This will undo any previous renaming operations on the expression.
