### ISSUE TITLE
Extend pl.Expr.cast to support UTF8 to Date and Datetime data types via the default options

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#9994]
### Problem description

I think since the inclusion of 

```python
pl.Expr.str.to_date
pl.Expr.str.to_datetime
```

It should be possible to support:

```python
pl.DataFrame({
    'x1': ['2021-01-01'], 
    'x2': ['2021-01-01 12:54:58'],
}).with_columns(**{
        'x1-date':pl.col('x1').cast(pl.Date),
        'x2-datetime':pl.col('x2').cast(pl.Datetime)
})
```

I personally find this a very common task.

This is related to a data-frame level .cast() method here: https://github.com/pola-rs/polars/issues/9959#issuecomment-1643790546

**Comment by alexander-beedie** [comment]
Given the number of possible date/datetime formats and their variations I'm not convinced about putting this in `cast`, where we can't provide any non-ISO alternatives (as the only sensible format to prioritise over everything else would be ISO - and even that has some variations, such as with/without "T" and with/without timezones, etc).

The following might make life a bit easier than typing out the full ISO format for strptime every time though?
```
pl.DataFrame({
    'x1': ['2021-01-01'], 
    'x2': ['2021-01-01 12:54:58'],
}).with_columns(**{
    'x1-date':pl.col('x1').str.strptime(pl.Date,"ISO"),
    'x2-datetime':pl.col('x2').str.strptime(pl.Datetime,"ISO"),
})
```
That way it's both unambiguous _and_ not as much of a hassle to type? We could infer the right ISO format (date or datetime) from the dtype so you just use "ISO" in both cases.

**Comment by stinodego** [comment]
I think this could be a useful addition.

It can call `to_date` or `to_datetime` under the hood, either with a default `fmt` string, or using the auto-infer format capability.

Apparently there is some debate on whether this is a good idea (see the linked topic), so I won't `accept` this proposal just yet.

**Comment by ritchie46** [comment]
This has been discussed before and I don't think it should be in `cast`. I see `cast` as someting similar to `as` casting in rust. E.g. casting:

```rust
let a: bool = true;
let b = a as i64
```

This is something that is unambiguous. We cannot `as` convert a `&str` into a `Datetime` and I don't think we should. It is a parsing operations. In python we need a `strptime` for that and in polars we have that function as well.

**Comment by mkleinbort-ic** [comment]
Yes, as usual, some transformations will fail:
```python
pl.DatatFrame({'x1':['Apple', 'Pie']}).with_columns(x2 = pl.col('x1').cast(pl.Date)) # I expect this to fail
```

That said, I think the affordance of calling `.to_date` or `.to_datetime` on string columns with whatever the agreed default is should be fine. 

From the `.str.to_date` documentation we see an allusion to some default string to date conversion that is inferred from the string:

```markdown
Parameters:
============
    format
       Format to use for conversion. Refer to the [chrono crate documentation] 
       (https://docs.rs/chrono/latest/chrono/format/strftime/index.html) for the full specification. 
       Example: "%Y-%m-%d". 
       If set to None (default), the format is inferred from the data.
```

The ambiguity is also not new - this works:

```python
pl.DataFrame({'x1':[0]}).with_columns(x2=pl.col('x1').cast(pl.Date))
```

without having to specify how integers have to be mapped to dates.

**Comment by ritchie46** [comment]
Alright, willing to budge on this one. Though the default casting is `strict` which will error whereas `to_date` allows for failing parses.

So with not so clean data, your default cast has a higher probability on erroring.

**Comment by mkleinbort-ic** [comment]
> Though the default casting is `strict` which will error whereas `to_date` allows for failing parses.
> 
> So with not so clean data, your default cast has a higher probability on erroring. I think we should refer to `to_date` and `to_datetime` in those errors.

I 100% agree - `.cast` should not be magic, just apply the defaults if we ask it to.

**Comment by cmdlineluser** [comment]
Does anybody have any pointers as to how/where this should be implemented exactly?

If I'm understanding things, the agreement here is to make these calls equivalent? 
```python
pl.col(...).cast(pl.Date)     -> pl.col(...).str.to_date()
pl.col(...).cast(pl.Datetime) -> pl.col(...).str.to_datetime()
pl.col(...).cast(pl.Time)     -> pl.col(...).str.to_time()
```
(I'm assuming Time will be allowed also?)

The casting for ChunkedArray seems to be here:
https://github.com/pola-rs/polars/blob/d745a2fba22d124bdb8aca2040bb26c0a0c51e0f/polars/polars-core/src/chunked_array/cast.rs#L171

Whereas the string functions are here:
https://github.com/pola-rs/polars/blob/d745a2fba22d124bdb8aca2040bb26c0a0c51e0f/polars/polars-lazy/polars-plan/src/dsl/string.rs#L148

Does this need to be done at the ChunkedArray level?

Or could `pl.col(...).cast(pl.Date)` actually be turned into `pl.col(...).str.to_date()` at the `Expr` level?

Or perhaps it's none of the above.

**Comment by brayanjuls** [comment]
Hi! I would like to take this task, @cmdlineluser are you planning to work on this? If so then I will leave it alone. 

Also, even though I have many years of experience in other programming languages such as Scala, I am currently in the process of learning Rust, so I hope I can get some guidance if I end up taking this issue.

**Comment by cmdlineluser** [comment]
It's all yours @brayanjuls.
