### ISSUE TITLE
Six columns on which you perform `sample`, `implode`, `cache` and then return a struct of two values give duplicate output for first and sixth column if the first three have `drop_nans` run on them first

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#9999]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
def bootstrap(expr: pl.Expr, n=1000) -> pl.Expr:
    return expr.sample(fraction=n, with_replacement=True).reshape((n, -1)).list.mean()


def ci(samples: pl.Expr, level=0.95) -> pl.Expr:
    samples = samples.implode().cache()
    return pl.struct(
        lower=samples.list.eval(pl.element().quantile((1 - level) / 2)).list.first(),
        upper=samples.list.eval(pl.element().quantile((1 + level) / 2)).list.first(),
    )


samples = 1
pl.DataFrame({str(i): [i] for i in range(6)}).select(
    zero=pl.col("0").drop_nans().pipe(bootstrap, n=samples).pipe(ci),
    one=pl.col("1").drop_nans().pipe(bootstrap, n=samples).pipe(ci),
    two=pl.col("2").drop_nans().pipe(bootstrap, n=samples).pipe(ci),
    three=pl.col("3").pipe(bootstrap, n=samples).pipe(ci),
    four=pl.col("4").pipe(bootstrap, n=samples).pipe(ci),
    five=pl.col("5").pipe(bootstrap, n=samples).pipe(ci),
)
```

Output:
```
┌───────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ zero      ┆ one       ┆ two       ┆ three     ┆ four      ┆ five      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ {0.0,0.0} ┆ {1.0,1.0} ┆ {2.0,2.0} ┆ {3.0,3.0} ┆ {4.0,4.0} ┆ {0.0,0.0} │
└───────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
```

### Issue description

This one is utterly bizarre. The goal of the above is to bootstrap confidence intervals of the mean of six columns. The weird `.implode().cach()` followed by `list.eval` thing in the `ci` function is to workaround #9767 (the real code I'm running this in is doing this in a `groupby`).

The bug here is that the sixth column (labelled `five` here) has duplicate values as the first column. This still occurs in more complex versions of this, such as having real data in the columns, performing more than one bootstrap sample (`samples` here refers to the number of bootstrapped samples of the mean), and doing this in a `groupby`.

Changing virtually any part of the expressions themselves causes it to behave as expected. Doing any of the following gets rid of the bug:

- Removing any column
- Adding `drop_nans` to *any* of the last three columns
- Removing `drop_nans` from any of the first three columns (note that there are no actuals nans in the data...)
- Swapping the position of one of the first three columns with one of the last three
- Removing the `sample` (which isn't actually doing anything since the columns only have a single element)
- Removing the `cache`
- Changing the `implode().cach()` -> `.list.eval ...` to just `.cache()` -> `.quantile(...)`
- **Adding or removing elements from the result struct in `ci`** (seriously, w t actual f)

If you add additional columns, the sixth column will still duplicate the first.

If you changes `boostrap` to be

```
def bootstrap(expr: pl.Expr, n=1000) -> pl.Expr:
    return expr.sample(1)
```

(that is, eliminating the mean list stuff).... the **fifth** column duplicates the first instead of sixth.

Super curious about what's going on here...

Fortunately, given the highly specific constraints of the bug, its pretty easy to workaround. Just add a superfluous `drop_nans` or whatever. But I do worry how else the underlying might manifest

### Expected behavior

```
┌───────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ zero      ┆ one       ┆ two       ┆ three     ┆ four      ┆ five      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] ┆ struct[2] │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ {0.0,0.0} ┆ {1.0,1.0} ┆ {2.0,2.0} ┆ {3.0,3.0} ┆ {4.0,4.0} ┆ {5.0,5.0} │
└───────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Linux-6.3.12-200.fc38.x86_64-x86_64-with-glibc2.37
Python:              3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.0
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Yeah, I am going to remove and make it a no-op. It is badly implemented. Almost done with CSE which will make it redundant

**Comment by mcrumiller** [comment]
> Almost done with CSE

Looking forward to that!

**Comment by qiemem** [comment]
> Yeah, I am going to remove and make it a no-op. It is badly implemented. Almost done with CSE which will make it redundant

CSE = common subexpression elimination? That sounds sweet! So I'm assuming you mean that you're removing `cache`?

Question about the semantics here, since the way CSE should interact with `sample` is a bit unclear. So, in the above `.cache()` is *not* being used for performance, but rather to make sure that we use the same samples in both expressions. Under CSE, can we ensure same sampling vs different sampling by reusing the expression reference, like so?

```python
def sample_once(expr):
    s = expr.sample(1)
    return pl.struct(one=s, two=s)


def sample_twice(expr):
    return pl.struct(one=expr.sample(1), two=expr.sample(1))


pl.DataFrame({"foo": [1,2,3]}).select(
    should_be_same=pl.col("foo").pipe(sample_once),
    should_be_different=pl.col("foo").pipe(sample_twice),
)
```

or will there be another way to get same samples vs different samples?

**Comment by ritchie46** [comment]
Yes, cached removed per #10066

>  So, in the above .cache() is not being used for performance, but rather to make sure that we use the same samples in both expressions.

If you want to reuse sampled values, you must create them in another context. So 

```python
df.with_columns(
    sample = sample_expr()
).select(
  use_samples_1,
  use_samples_2,
)
```

**Comment by ritchie46** [comment]
I will close this issue as that is solved now we don't have `cache` anymore. Discussion can ofcourse continue.

**Comment by qiemem** [comment]
Replacing `.cache()` with CSE seems like a huge win from a API simplicity, usability, and performance perspective. Great stuff!

> If you want to reuse sampled values, you must create them in another context.

This is what I was doing before I figured out the trick with `.cache()`. When bootstrapping confidence intervals, you resample a bunch of times, take the means of those samples, and then take the quantiles of the sampled means. Since you want to aggregate away the samples/sampled means anyway, my thinking was that doing it all in the same context would be a lot more memory friendly. However, testing it now, that does not seem to be the case. In fact, using separate contexts appears to use slightly *less* memory and to be a good bit faster. So the whole premise of this was pointless anyway. I guess this is great example of how removing `.cache()` helps stop users shooting themselves in the foot by using it for hacky shit like this...

**Comment by ritchie46** [comment]
Great to hear. :) 

It also removed a lot of concurrency complexity that I wasn't happy about and showing by the existence of this issue didn't work correctly.
